include::./index.adoc[]

[[v58-3-0]]
=== Hebreus, 3
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v58-3-1]]

^<<v58-3-1,1>>^ Por conseguinte, santos irmãos, participantes da chamada^&#42;1^ celestial, considerai o apóstolo e sumo sacerdote que confessamos^&#42;2^ — Jesus.

[NOTE]
====
. Ou “convite”.
. Lit.: “principal sacerdote de nossa confissão”.
====

[[v58-3-2]]

^<<v58-3-2,2>>^ Ele foi fiel Àquele que o fez tal, assim como também Moisés o foi em toda a casa Daquele.

[[v58-3-3]]

^<<v58-3-3,3>>^ Pois este último é considerado digno de maior glória do que Moisés, visto que aquele que a constrói tem maior honra do que a casa.

[[v58-3-4]]

^<<v58-3-4,4>>^ Cada casa, naturalmente, é construída por alguém, mas quem construiu todas as coisas é Deus.

[[v58-3-5]]

^<<v58-3-5,5>>^ E Moisés, como assistente, foi fiel em toda a casa^&#42;1^ Daquele, como testemunho das coisas de que se havia de falar depois,^&#42;2^

[NOTE]
====
. Veja Núm 12:7 e n.
. Lit.: “falar futuramente”.
====

[[v58-3-6]]

^<<v58-3-6,6>>^ mas Cristo [foi fiel] como Filho sobre a casa Daquele. Nós somos a casa Daquele, se fizermos firme o nosso apego à nossa franqueza no falar e à nossa jactância a respeito da esperança firme até o fim.^&#42;1^

[NOTE]
====
. “Firme até o fim”, אACDVg; P46B omitem isso.
====

[[v58-3-7]]

^<<v58-3-7,7>>^ Por esta razão, como diz o espírito santo: “Hoje, se escutardes a sua própria voz,

[[v58-3-8]]

^<<v58-3-8,8>>^ não endureçais os vossos corações como na ocasião em que se causou ira amarga,^&#42;1^ como no dia em que se fez a prova no ermo,

[NOTE]
====
. Lit.: “amargura”.
====

[[v58-3-9]]

^<<v58-3-9,9>>^ em que os vossos antepassados me submeteram a uma prova, com uma provação, e, no entanto, tinham visto as minhas obras por quarenta anos.

[[v58-3-10]]

^<<v58-3-10,10>>^ Por esta razão me aborreci desta geração e disse: ‘Eles sempre se perdem nos seus corações, e eles mesmos não chegaram a conhecer os meus caminhos.’

[[v58-3-11]]

^<<v58-3-11,11>>^ De modo que jurei na minha ira: ‘Não entrarão no meu descanso.’”

[[v58-3-12]]

^<<v58-3-12,12>>^ Acautelai-vos, irmãos, para que nunca se desenvolva em nenhum de vós um coração iníquo, falto de fé,^&#42;1^ por se separar^&#42;2^ do Deus vivente;

[NOTE]
====
. “Falto de fé.” Lit.: “de descrença”. Gr.: a·pi·stí·as.
. Lit.: “se apartar”. Gr.: a·po·sté·nai.
====

[[v58-3-13]]

^<<v58-3-13,13>>^ mas, persisti em exortar-vos uns aos outros cada dia, enquanto se possa chamar de “hoje”, para que nenhum de vós fique endurecido pelo poder enganoso^&#42;1^ do pecado.

[NOTE]
====
. “Poder enganoso.” Lit.: “sedução”.
====

[[v58-3-14]]

^<<v58-3-14,14>>^ Porque nós nos tornamos realmente participantes do Cristo somente se fizermos firme o nosso apego à confiança que tivemos no princípio, firme até o fim,^&#42;1^

[NOTE]
====
. Ou “término”. Gr.: té·lous.
====

[[v58-3-15]]

^<<v58-3-15,15>>^ enquanto se diz: “Hoje, se escutardes a sua própria voz, não endureçais os vossos corações como na ocasião em que se causou ira amarga.”

[[v58-3-16]]

^<<v58-3-16,16>>^ Pois, quem foram os que ouviram e ainda assim provocaram à ira amarga? Não fizeram isso, de fato, todos os que tinham saído do Egito, sob Moisés?

[[v58-3-17]]

^<<v58-3-17,17>>^ Ainda mais, de quem ficou [Deus]^&#42;1^ aborrecido por quarenta anos? Não foi daqueles que pecaram, cujos cadáveres caíram no ermo?

[NOTE]
====
. Lit.: “ele”.
====

[[v58-3-18]]

^<<v58-3-18,18>>^ Mas, a quem jurou que não haviam de entrar no seu descanso, senão aos que agiram de modo desobediente?

[[v58-3-19]]

^<<v58-3-19,19>>^ Vemos assim que não podiam entrar por causa da falta de fé.

'''

xref:058-hebreus/058-hebreus-002.adoc#v58-2-0[&#60; Capítulo Anterior] | <<v58-3-0,Topo>> | xref:058-hebreus/058-hebreus-004.adoc#v58-4-0[Próximo Capítulo &#62;]