include::./index.adoc[]

[[v58-10-0]]
=== Hebreus, 10
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v58-10-1]]

^<<v58-10-1,1>>^ Pois, visto que a Lei tem uma sombra das boas coisas vindouras, mas não a própria substância das coisas, [os homens] nunca podem, com os mesmos sacrifícios que oferecem continuamente, de ano em ano, aperfeiçoar os que se aproximam.

[[v58-10-2]]

^<<v58-10-2,2>>^ De outro modo, não se teria parado de oferecer os [sacrifícios], visto que os que prestam serviço sagrado,^&#42;1^ purificados uma vez para sempre, não teriam mais consciência de pecados?

[NOTE]
====
. “Prestam serviço sagrado.” Gr.: la·treú·on·tas; J18(hebr.): ha·‛o·vedhím, “os que servem (adoram)”. Veja Êx 3:12 n.
====

[[v58-10-3]]

^<<v58-10-3,3>>^ Ao contrário, por meio destes sacrifícios há de ano em ano uma lembrança dos pecados,

[[v58-10-4]]

^<<v58-10-4,4>>^ porque não é possível que o sangue de touros e de bodes tire pecados.

[[v58-10-5]]

^<<v58-10-5,5>>^ Por isso, ao entrar no mundo, ele diz: “‘Sacrifício e oferta não quiseste, porém, preparaste-me um corpo.

[[v58-10-6]]

^<<v58-10-6,6>>^ Não aprovaste os holocaustos^&#42;1^ e [as ofertas pelos] pecados.’

[NOTE]
====
. “Holocaustos.” Gr.: ho·lo·kau·tó·ma·ta; lat.: ho·lo·cau·stó·ma·ta. Tais holocaustos são sacrifícios totalmente consumidos pelo fogo.
====

[[v58-10-7]]

^<<v58-10-7,7>>^ Então disse eu: ‘Eis aqui vim (no rolo do livro está escrito a meu respeito) para fazer a tua vontade, ó Deus.’”

[[v58-10-8]]

^<<v58-10-8,8>>^ Dizendo primeiro: “Não quiseste nem aprovaste sacrifícios, e ofertas, e holocaustos, e [ofertas pelo] pecado” — [sacrifícios] que se oferecem segundo a Lei —

[[v58-10-9]]

^<<v58-10-9,9>>^ ele diz então realmente: “Eis aqui vim para fazer a tua vontade.”^&#42;1^ Ele elimina o primeiro para estabelecer o segundo.

[NOTE]
====
. “Tua vontade.” Gr.: to thé·le·má sou; lat.: vo·lun·tá·tem tú·am; J17,18,22(hebr.): retsoh·nekhá.
====

[[v58-10-10]]

^<<v58-10-10,10>>^ Pela dita “vontade” [é que] temos sido santificados por intermédio da oferta do corpo de Jesus Cristo, uma vez para sempre.

[[v58-10-11]]

^<<v58-10-11,11>>^ Também, cada sacerdote assume o seu posto, de dia a dia, para prestar serviço público e para oferecer os mesmos sacrifícios, muitas vezes, visto que estes nunca podem tirar completamente os pecados.

[[v58-10-12]]

^<<v58-10-12,12>>^ Mas, este [homem] ofereceu um só sacrifício pelos pecados, perpetuamente, e se assentou à direita de Deus,

[[v58-10-13]]

^<<v58-10-13,13>>^ daí em diante esperando até que os seus inimigos sejam postos por escabelo dos seus pés.

[[v58-10-14]]

^<<v58-10-14,14>>^ Porque é por meio de uma só oferta [sacrificial] que ele aperfeiçoou perpetuamente os que estão sendo santificados.

[[v58-10-15]]

^<<v58-10-15,15>>^ Além disso, o espírito santo também nos dá testemunho, porque, depois de dizer:

[[v58-10-16]]

^<<v58-10-16,16>>^ “‘Este é o pacto que celebrarei com eles depois daqueles dias’, diz Jeová.^&#42;1^ ‘Porei as minhas leis nos seus corações e as escreverei nas suas mentes’”,

[NOTE]
====
. Veja Ap. 1D.
====

[[v58-10-17]]

^<<v58-10-17,17>>^ [diz posteriormente:]^&#42;1^ “E de modo algum me lembrarei mais dos seus pecados e das suas ações contra a lei.”

[NOTE]
====
. “Diz posteriormente”, Vgmss.Syh(margem) e mss. Minúsculos 104, 323, 945, 1739, 1881, etc.
====

[[v58-10-18]]

^<<v58-10-18,18>>^ Ora, onde há perdão desses, não há mais oferta pelo pecado.

[[v58-10-19]]

^<<v58-10-19,19>>^ Portanto, irmãos, visto que temos denodo^&#42;1^ para com o caminho de entrada no lugar santo,^&#42;2^ pelo sangue de Jesus,

[NOTE]
====
. Ou “franqueza no falar”.
. Veja 9:8 n.
====

[[v58-10-20]]

^<<v58-10-20,20>>^ que ele inaugurou para nós como caminho novo e vivente através da cortina, isto é, sua carne,

[[v58-10-21]]

^<<v58-10-21,21>>^ e, visto que temos um grande sacerdote sobre a casa de Deus,

[[v58-10-22]]

^<<v58-10-22,22>>^ aproximemo-nos com corações sinceros na plena certeza da fé, tendo os nossos corações aspergidos [eximindo] duma consciência iníqua e os nossos corpos banhados com água limpa.

[[v58-10-23]]

^<<v58-10-23,23>>^ Apeguemo-nos à declaração pública^&#42;1^ da nossa esperança, sem vacilação, pois aquele que prometeu é fiel.

[NOTE]
====
. “Declaração pública.” Lit.: “confissão”.
====

[[v58-10-24]]

^<<v58-10-24,24>>^ E consideremo-nos uns aos outros para nos estimularmos ao amor e a obras excelentes,

[[v58-10-25]]

^<<v58-10-25,25>>^ não deixando de nos ajuntar, como é costume de alguns, mas encorajando-nos uns aos outros, e tanto mais quanto vedes chegar o dia.

[[v58-10-26]]

^<<v58-10-26,26>>^ Pois, se praticarmos o pecado deliberadamente, depois de termos recebido o conhecimento exato da verdade, não há mais nenhum sacrifício pelos pecados,

[[v58-10-27]]

^<<v58-10-27,27>>^ mas [há] uma certa expectativa terrível de julgamento e [há] um ciúme ardente que vai consumir os que estão em oposição.

[[v58-10-28]]

^<<v58-10-28,28>>^ Qualquer homem que tiver desconsiderado a lei de Moisés morre sem compaixão, pelo testemunho de dois ou três.

[[v58-10-29]]

^<<v58-10-29,29>>^ De quanto mais severa punição, achais, será contado digno aquele que tiver pisado o Filho de Deus e que tiver considerado de pouco valor o sangue do pacto com que foi santificado, e que tiver ultrajado com desdém o espírito de benignidade imerecida?

[[v58-10-30]]

^<<v58-10-30,30>>^ Pois, conhecemos aquele que disse: “Minha é a vingança; eu recompensarei”;^&#42;1^ e, novamente: “Jeová^&#42;2^ julgará o seu povo.”

[NOTE]
====
. “Eu recompensarei”, P46א°D°ItSyp; אcADcSyh: “‘eu recompensarei’, diz [o] Senhor”; J3,7,8,11-16,24: “‘eu recompensarei’, diz Jeová”.
. Veja Ap. 1D.
====

[[v58-10-31]]

^<<v58-10-31,31>>^ Coisa terrível é cair nas mãos do Deus vivente.

[[v58-10-32]]

^<<v58-10-32,32>>^ No entanto, persisti em lembrar-vos dos dias anteriores, em que, depois de terdes sido esclarecidos, perseverastes em uma grande competição, debaixo de sofrimentos,

[[v58-10-33]]

^<<v58-10-33,33>>^ às vezes enquanto expostos como que num teatro, tanto a vitupérios como a tribulações, e tornando-vos às vezes parceiros dos que estavam tendo tal experiência.

[[v58-10-34]]

^<<v58-10-34,34>>^ Porque vós tanto expressastes compaixão pelos em prisão como suportastes alegremente o saque de vossos bens, sabendo que vós mesmos tendes uma possessão melhor e subsistente.

[[v58-10-35]]

^<<v58-10-35,35>>^ Portanto, não lanceis fora a vossa franqueza no falar, que recebe a paga duma grande recompensa.

[[v58-10-36]]

^<<v58-10-36,36>>^ Pois tendes necessidade de perseverança, a fim de que, depois de terdes feito a vontade de Deus, recebais o [cumprimento da] promessa.

[[v58-10-37]]

^<<v58-10-37,37>>^ Pois, ainda “por um pouquinho”, e “aquele que vem chegará e não demorará”.

[[v58-10-38]]

^<<v58-10-38,38>>^ “Mas o meu justo viverá em razão da fé”, e, “se ele retroceder, minha alma não terá prazer nele”.

[[v58-10-39]]

^<<v58-10-39,39>>^ Ora, nós não somos dos que retrocedem para a destruição, mas dos que têm fé para preservar viva a alma.

'''

xref:058-hebreus/058-hebreus-009.adoc#v58-9-0[&#60; Capítulo Anterior] | <<v58-10-0,Topo>> | xref:058-hebreus/058-hebreus-011.adoc#v58-11-0[Próximo Capítulo &#62;]