include::./index.adoc[]

[[v58-11-0]]
=== Hebreus, 11
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v58-11-1]]

^<<v58-11-1,1>>^ A fé é a expectativa certa^&#42;1^ de coisas esperadas, a demonstração evidente^&#42;2^ de realidades,^&#42;3^ embora não observadas.

[NOTE]
====
. “Expectativa certa.” Lit.: “substância”. Gr.: hy·pó·sta·sis; lat.: sub·stán·ti·a.
. “Demonstração evidente.” Ou “evidência convincente”. Gr.: é·leg·khos; lat.: ar·gu·mén·tum. Veja Jo 16:8 n.
. Lit.: “de coisas”. Gr.: prag·má·ton.
====

[[v58-11-2]]

^<<v58-11-2,2>>^ Porque, por meio desta, os antigos^&#42;1^ receberam testemunho.

[NOTE]
====
. “Os antigos.” Lit.: “os anciãos”. Gr.: pre·sbý·te·roi.
====

[[v58-11-3]]

^<<v58-11-3,3>>^ Pela fé percebemos que os sistemas de coisas^&#42;1^ foram postos em ordem^&#42;2^ pela palavra de Deus, de modo que aquilo que se observa veio a existir das coisas que não aparecem.

[NOTE]
====
. Ou “as ordens de coisas”. Gr.: tous ai·ó·nas; lat.: saé·cu·la; J22(hebr.): ha·‛oh·la·mím.
. Ou “foram preparados; foram ajustados”. Lit.: “ter sido ajustados para baixo”. Gr.: ka·ter·tí·sthai.
====

[[v58-11-4]]

^<<v58-11-4,4>>^ Pela fé Abel ofereceu a Deus um sacrifício de maior valor do que Caim, sendo por esta [fé] que se lhe deu testemunho de que era justo, dando Deus testemunho com respeito a suas dádivas; e por intermédio dela, embora morto, ainda fala.

[[v58-11-5]]

^<<v58-11-5,5>>^ Pela fé Enoque foi transferido para não ver a morte, e não foi achado em parte alguma, porque Deus o havia transferido; pois, antes de sua transferência, ele teve o testemunho de que agradara bem a Deus.

[[v58-11-6]]

^<<v58-11-6,6>>^ Além disso, sem fé é impossível agradar-lhe bem, pois aquele que se aproxima de Deus tem de crer que ele existe e que se torna o recompensador^&#42;1^ dos que seriamente o buscam.

[NOTE]
====
. Lit.: “remunerador”.
====

[[v58-11-7]]

^<<v58-11-7,7>>^ Pela fé Noé, depois de receber aviso divino de coisas ainda não observadas, mostrou temor piedoso e construiu uma arca para a salvação de sua família; e, por intermédio desta [fé], ele condenou o mundo e tornou-se herdeiro da justiça que é segundo a fé.

[[v58-11-8]]

^<<v58-11-8,8>>^ Pela fé Abraão, quando chamado, obedeceu, saindo para um lugar que estava destinado a receber em herança; e ele saiu, embora não soubesse para onde ia.

[[v58-11-9]]

^<<v58-11-9,9>>^ Pela fé residia como forasteiro na terra da promessa, como em terra estrangeira, e morava em tendas, com Isaque e Jacó, herdeiros com ele da mesmíssima promessa.

[[v58-11-10]]

^<<v58-11-10,10>>^ Pois aguardava a cidade que tem verdadeiros alicerces, cujo construtor^&#42;1^ e fazedor é Deus.

[NOTE]
====
. Lit.: “artífice”. Gr.: te·khní·tes.
====

[[v58-11-11]]

^<<v58-11-11,11>>^ Pela fé, também, a própria Sara recebeu poder para conceber um descendente, embora estivesse além do limite da idade, visto que considerava fiel aquele que prometera.

[[v58-11-12]]

^<<v58-11-12,12>>^ Por isso, também, de um só [homem], e este já como que morto, nasceram [filhos] em multidão como as estrelas do céu e como a areia que está à beira do mar, inumeráveis.

[[v58-11-13]]

^<<v58-11-13,13>>^ Todos estes morreram em fé, embora não recebessem o [cumprimento das] promessas, mas viram-nas de longe e acolheram-nas,^&#42;1^ e declararam publicamente que eram estranhos e residentes temporários no país.

[NOTE]
====
. Ou “cumprimentaram-nas; abraçaram-nas; aclamaram-nas”.
====

[[v58-11-14]]

^<<v58-11-14,14>>^ Pois, os que dizem tais coisas dão evidência de que buscam seriamente um lugar para si próprios.

[[v58-11-15]]

^<<v58-11-15,15>>^ Contudo, se deveras se tivessem lembrado do [lugar] de que tinham saído, teriam tido a oportunidade de voltar.

[[v58-11-16]]

^<<v58-11-16,16>>^ Mas agora procuram alcançar um [lugar] melhor, isto é, um pertencente ao céu. Por isso, Deus não se envergonha deles, de ser chamado seu Deus, porque aprontou para eles uma cidade.

[[v58-11-17]]

^<<v58-11-17,17>>^ Pela fé Abraão, quando provado, a bem dizer ofereceu Isaque,^&#42;1^ e o homem que recebera de bom grado as promessas, tentou^&#42;2^ oferecer [seu] unigênito,

[NOTE]
====
. Ou “Abraão, ao ser testado, (como que) ofereceu”.
. Ou “passou a”.
====

[[v58-11-18]]

^<<v58-11-18,18>>^ embora se lhe tivesse dito: “Aquilo que se chamar ‘teu descendente’ será por intermédio de Isaque.”

[[v58-11-19]]

^<<v58-11-19,19>>^ Mas ele achava que Deus era capaz de levantá-lo até mesmo dentre os mortos; e dali o recebeu também em sentido ilustrativo.^&#42;1^

[NOTE]
====
. Lit.: “em parábola”. Gr.: en pa·ra·bo·leí.
====

[[v58-11-20]]

^<<v58-11-20,20>>^ Pela fé, também, Isaque abençoou Jacó e Esaú concernente a coisas vindouras.

[[v58-11-21]]

^<<v58-11-21,21>>^ Pela fé Jacó, quando estava para morrer, abençoou a cada um dos filhos de José e adorou debruçado^&#42;1^ sobre a extremidade do seu bordão.

[NOTE]
====
. Em harmonia com o sentido do texto hebr. de Gên 47:31, onde veja a n.
====

[[v58-11-22]]

^<<v58-11-22,22>>^ Pela fé José, próximo do seu fim, fez menção do êxodo dos filhos de Israel; e ele deu mandado a respeito dos seus ossos.

[[v58-11-23]]

^<<v58-11-23,23>>^ Pela fé, Moisés foi escondido pelos seus pais por três meses depois de ter nascido, porque viam que a criancinha era bela e não temiam a ordem do rei.

[[v58-11-24]]

^<<v58-11-24,24>>^ Pela fé Moisés, quando cresceu, negou-se^&#42;1^ a ser chamado filho da filha de Faraó,

[NOTE]
====
. Lit.: “repeliu”.
====

[[v58-11-25]]

^<<v58-11-25,25>>^ escolhendo antes ser maltratado com o povo de Deus do que ter o usufruto temporário do pecado,

[[v58-11-26]]

^<<v58-11-26,26>>^ porque estimava o vitupério do Cristo^&#42;1^ como riqueza maior do que os tesouros do Egito, pois olhava atentamente para o pagamento da recompensa.

[NOTE]
====
. “Do Cristo.” Gr.: tou Khri·stoú; lat.: Chrí·sti; J17,18,22(hebr.): ham·Ma·shí·ahh, “do Messias (Ungido)”.
====

[[v58-11-27]]

^<<v58-11-27,27>>^ Pela fé abandonou o Egito, mas sem temer a ira do rei, porque permanecia constante como que vendo Aquele que é invisível.

[[v58-11-28]]

^<<v58-11-28,28>>^ Pela fé tinha celebrado^&#42;1^ a páscoa^&#42;2^ e a aspersão do sangue, para que o destruidor não tocasse nos primogênitos deles.

[NOTE]
====
. Ou “realmente celebrou”.
. Gr.: pá·skha; lat.: pá·scha; J17,18,22(hebr.): hap·pé·sahh, “a páscoa”.
====

[[v58-11-29]]

^<<v58-11-29,29>>^ Pela fé passaram através do Mar Vermelho como em terra seca, mas, quando os egípcios se aventuraram nele, foram tragados.

[[v58-11-30]]

^<<v58-11-30,30>>^ Pela fé caíram os muros de Jericó, depois de terem sido rodeados^&#42;1^ por sete dias.

[NOTE]
====
. Ou “terem sido sitiados (circundados)”.
====

[[v58-11-31]]

^<<v58-11-31,31>>^ Pela fé Raabe, a meretriz, não pereceu com os que agiram desobedientemente, porque ela recebeu os espiões de modo pacífico.

[[v58-11-32]]

^<<v58-11-32,32>>^ E que mais hei de dizer? Pois o tempo me faltaria se prosseguisse relatando sobre Gideão, Baraque, Sansão, Jefté, Davi, bem como Samuel e os [outros] profetas,

[[v58-11-33]]

^<<v58-11-33,33>>^ os quais, pela fé, derrotaram reinos, puseram em execução a justiça, obtiveram promessas, taparam as bocas de leões,

[[v58-11-34]]

^<<v58-11-34,34>>^ pararam a força do fogo, escaparam do fio^&#42;1^ da espada, dum estado fraco foram feitos poderosos, tornaram-se valentes na guerra, desbarataram os exércitos de estrangeiros.

[NOTE]
====
. Lit.: “das bocas”.
====

[[v58-11-35]]

^<<v58-11-35,35>>^ Mulheres receberam os seus mortos pela ressurreição; mas outros [homens] foram torturados porque não queriam aceitar um livramento por meio de algum resgate, a fim de que pudessem alcançar uma ressurreição melhor.

[[v58-11-36]]

^<<v58-11-36,36>>^ Sim, outros receberam a sua provação por mofas e por açoites, deveras, mais do que isso, por laços e prisões.

[[v58-11-37]]

^<<v58-11-37,37>>^ Foram apedrejados, foram provados, foram serrados em pedaços, morreram abatidos pela espada, andavam vestidos de peles de ovelhas [e] de peles de cabras, passando necessidade, tribulação, [sofrendo] maus tratos;

[[v58-11-38]]

^<<v58-11-38,38>>^ e o mundo não era digno deles. Vagueavam pelos desertos, e pelas montanhas, e pelas cavernas, e pelas covas da terra.

[[v58-11-39]]

^<<v58-11-39,39>>^ Contudo, embora todos estes recebessem testemunho por intermédio de sua fé, não obtiveram o [cumprimento da] promessa,

[[v58-11-40]]

^<<v58-11-40,40>>^ visto que Deus previu^&#42;1^ algo melhor para nós, a fim de que eles não fossem aperfeiçoados à parte de nós.

[NOTE]
====
. Ou “proveu”.
====

'''

xref:058-hebreus/058-hebreus-010.adoc#v58-10-0[&#60; Capítulo Anterior] | <<v58-11-0,Topo>> | xref:058-hebreus/058-hebreus-012.adoc#v58-12-0[Próximo Capítulo &#62;]