include::./index.adoc[]

[[v58-5-0]]
=== Hebreus, 5
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v58-5-1]]

^<<v58-5-1,1>>^ Pois todo sumo sacerdote tomado dentre os homens é designado a favor dos homens sobre as coisas referentes a Deus, a fim de oferecer dádivas e sacrifícios pelos pecados.

[[v58-5-2]]

^<<v58-5-2,2>>^ Ele é capaz de lidar moderadamente com os ignorantes e com os que erram, visto que ele também está cercado pela sua própria fraqueza,

[[v58-5-3]]

^<<v58-5-3,3>>^ e por causa dela está obrigado a fazer ofertas pelos pecados, tanto por si mesmo como pelo povo.

[[v58-5-4]]

^<<v58-5-4,4>>^ Também, o homem não se arroga esta honra por si mesmo, mas apenas quando é chamado por Deus, assim como também Arão [foi].

[[v58-5-5]]

^<<v58-5-5,5>>^ Assim, também, o Cristo não se glorificou a si mesmo por se tornar sumo sacerdote, mas [foi glorificado por aquele] que falou com referência a ele: “Tu és meu filho; hoje eu me tornei teu pai.”

[[v58-5-6]]

^<<v58-5-6,6>>^ Assim como ele diz também em outro lugar: “Tu és sacerdote para sempre à maneira^&#42;1^ de Melquisedeque.”

[NOTE]
====
. Lit.: “o arranjo [a feição]”.
====

[[v58-5-7]]

^<<v58-5-7,7>>^ [Cristo,] nos dias da sua carne, ofereceu súplicas e também petições Àquele que era capaz de salvá-lo da morte, com fortes clamores e lágrimas, e ele foi ouvido favoravelmente pelo seu temor piedoso.

[[v58-5-8]]

^<<v58-5-8,8>>^ Embora fosse Filho, aprendeu a obediência pelas coisas que sofreu;

[[v58-5-9]]

^<<v58-5-9,9>>^ e, depois de ter sido aperfeiçoado,^&#42;1^ tornou-se responsável pela salvação eterna de todos os que lhe obedecem,

[NOTE]
====
. Ou “depois de ter sido inaugurado (investido; empossado; consagrado no cargo)”. Gr.: te·lei·o·theís. Veja Le 21:10 n. Compare isso com Le 8:33 n.
====

[[v58-5-10]]

^<<v58-5-10,10>>^ porque ele tem sido chamado especificamente por Deus como sumo sacerdote à maneira de Melquisedeque.

[[v58-5-11]]

^<<v58-5-11,11>>^ A respeito dele temos muito a dizer e difícil de explicar,^&#42;1^ visto que ficastes obtusos no vosso ouvir.

[NOTE]
====
. Lit.: “difícil de interpretar”.
====

[[v58-5-12]]

^<<v58-5-12,12>>^ Pois, deveras, embora devêsseis ser instrutores, em vista do tempo, precisais novamente que alguém vos ensine desde o princípio as coisas elementares das proclamações sagradas de Deus e vos tornastes tais que precisais de leite, não de alimento^&#42;1^ sólido.

[NOTE]
====
. Lit.: “nutrição”.
====

[[v58-5-13]]

^<<v58-5-13,13>>^ Porque todo aquele que toma leite desconhece a palavra da justiça, pois é criancinha.

[[v58-5-14]]

^<<v58-5-14,14>>^ O alimento sólido, porém, é para as pessoas maduras, para aqueles que pelo uso têm as suas faculdades perceptivas^&#42;1^ treinadas^&#42;2^ para distinguir tanto o certo como o errado.

[NOTE]
====
. Lit.: “órgãos sensoriais”.
. Lit.: “têm sido treinadas (como ginastas)”. Gr.: ge·gy·mna·smé·na.
====

'''

xref:058-hebreus/058-hebreus-004.adoc#v58-4-0[&#60; Capítulo Anterior] | <<v58-5-0,Topo>> | xref:058-hebreus/058-hebreus-006.adoc#v58-6-0[Próximo Capítulo &#62;]