include::./index.adoc[]

[[v58-13-0]]
=== Hebreus, 13
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v58-13-1]]

^<<v58-13-1,1>>^ Continue o vosso amor fraternal.

[[v58-13-2]]

^<<v58-13-2,2>>^ Não vos esqueçais da hospitalidade,^&#42;1^ porque por meio dela alguns, sem o saberem, hospedaram^&#42;2^ anjos.

[NOTE]
====
. Ou “bondade para com estranhos”.
. Lit.: “tendo tratado como estranhos a”.
====

[[v58-13-3]]

^<<v58-13-3,3>>^ Lembrai-vos dos que estão em cadeias, como se tivésseis sido presos com eles, e dos que estão sendo maltratados, visto que vós mesmos também estais ainda num corpo.

[[v58-13-4]]

^<<v58-13-4,4>>^ O matrimônio seja honroso entre todos e o leito conjugal imaculado, porque Deus julgará os fornicadores e os adúlteros.^&#42;1^

[NOTE]
====
. “Adúlteros.” Lat.: a·dúl·te·ros.
====

[[v58-13-5]]

^<<v58-13-5,5>>^ [Vossa] maneira de viver esteja livre do amor ao dinheiro, ao passo que estais contentes com as coisas atuais. Pois ele disse: “De modo algum te deixarei e de modo algum te abandonarei.”

[[v58-13-6]]

^<<v58-13-6,6>>^ Para que tenhamos boa coragem e digamos: “Jeová^&#42;1^ é o meu ajudador; não terei medo. Que me pode^&#42;2^ fazer o homem?”

[NOTE]
====
. Veja Ap. 1D.
. Lit.: “irá”.
====

[[v58-13-7]]

^<<v58-13-7,7>>^ Lembrai-vos dos que tomam a dianteira entre vós,^&#42;1^ os que vos falaram a palavra de Deus, e, ao contemplardes em que resulta a [sua] conduta, imitai a [sua] fé.

[NOTE]
====
. Ou “que são vossos governadores”. Gr.: he·gou·mé·non hy·món. Veja Mt 2:6 n: “governadores”.
====

[[v58-13-8]]

^<<v58-13-8,8>>^ Jesus Cristo é o mesmo, ontem, hoje e para sempre.

[[v58-13-9]]

^<<v58-13-9,9>>^ Não vos deixeis levar por ensinos vários e estranhos; pois é excelente que o coração receba firmeza^&#42;1^ pela benignidade imerecida, não por comestíveis, que não aproveitaram aos que se ocupam com eles.

[NOTE]
====
. Lit.: “seja estabilizado”.
====

[[v58-13-10]]

^<<v58-13-10,10>>^ Nós temos um altar do qual os que fazem serviço sagrado^&#42;1^ na tenda^&#42;2^ não têm autoridade para comer.

[NOTE]
====
. “Fazem serviço sagrado.” Gr.: la·treú·on·tes. Veja Êx 3:12 n.
. Ou “tabernáculo”.
====

[[v58-13-11]]

^<<v58-13-11,11>>^ Porque os corpos daqueles animais, cujo sangue é levado para dentro do lugar^&#42;1^ santo pelo sumo sacerdote, pelo pecado, são queimados fora do acampamento.

[NOTE]
====
. Ou “lugares”.
====

[[v58-13-12]]

^<<v58-13-12,12>>^ Por isso, Jesus também, para santificar o povo com o seu próprio sangue, sofreu fora do portão.

[[v58-13-13]]

^<<v58-13-13,13>>^ Saiamos, pois, a ele, fora do acampamento, levando o vitupério que ele levou,^&#42;1^

[NOTE]
====
. Ou “vitupério para ele; seu vitupério”.
====

[[v58-13-14]]

^<<v58-13-14,14>>^ porque não temos aqui uma cidade que permaneça, mas buscamos seriamente aquela que vem.

[[v58-13-15]]

^<<v58-13-15,15>>^ Por intermédio dele, ofereçamos sempre a Deus um sacrifício de louvor, isto é, o fruto de lábios que fazem declaração pública^&#42;1^ do seu nome.

[NOTE]
====
. Lit.: “que confessam o”.
====

[[v58-13-16]]

^<<v58-13-16,16>>^ Além disso, não vos esqueçais de fazer o bem e de partilhar as coisas com outros, porque Deus se agrada bem de tais sacrifícios.

[[v58-13-17]]

^<<v58-13-17,17>>^ Sede obedientes aos que tomam a dianteira entre vós^&#42;1^ e sede submissos,^&#42;2^ pois vigiam sobre as vossas almas como quem há de prestar contas; para que façam isso com alegria e não com suspiros, porque isso vos seria prejudicial.

[NOTE]
====
. Ou “são vossos governadores”. Gr.: he·gou·mé·nois hy·món. Veja Mt 2:6 n.: “governadores”.
. Lit.: “cedei debaixo de”.
====

[[v58-13-18]]

^<<v58-13-18,18>>^ Fazei orações por nós, pois confiamos em ter uma consciência honesta, visto que queremos comportar-nos honestamente em todas as coisas.

[[v58-13-19]]

^<<v58-13-19,19>>^ Mas, exorto-vos mais especificamente a que façais isso, para que eu vos seja restituído tanto mais cedo.

[[v58-13-20]]

^<<v58-13-20,20>>^ Agora, o Deus de paz, que com o sangue dum pacto eterno tirou dentre os mortos o grande pastor das ovelhas, o nosso Senhor Jesus,

[[v58-13-21]]

^<<v58-13-21,21>>^ vos equipe com toda coisa boa, para fazerdes a sua vontade, realizando em nós, por intermédio de Jesus Cristo, aquilo que é bem agradável à sua vista; a ele seja a glória para todo o sempre. Amém.

[[v58-13-22]]

^<<v58-13-22,22>>^ Exorto-vos agora, irmãos, a que suporteis esta palavra de encorajamento, porque, deveras, tenho composto uma carta de poucas palavras para vós.

[[v58-13-23]]

^<<v58-13-23,23>>^ Tomai nota de que o nosso irmão Timóteo foi livrado, sendo que vos verei junto com ele, se vier em breve.^&#42;1^

[NOTE]
====
. Ou “se vier mais depressa (do que eu esperava)”.
====

[[v58-13-24]]

^<<v58-13-24,24>>^ Dai os meus cumprimentos a todos os que estão tomando a dianteira entre vós^&#42;1^ e a todos os santos. Os da^&#42;2^ Itália mandam-vos os seus cumprimentos.

[NOTE]
====
. Veja v. 17 n.: “vós”.
. Ou então: “na”.
====

[[v58-13-25]]

^<<v58-13-25,25>>^ A benignidade imerecida seja com todos vós.^&#42;1^

[NOTE]
====
. אcACDItVgSyh,p acrescentam “Amém”; P46א°Arm omitem isso.
====

'''

xref:058-hebreus/058-hebreus-012.adoc#v58-12-0[&#60; Capítulo Anterior] | <<v58-13-0,Topo>> | xref:059-tiago/059-tiago-001.adoc#v59-1-0[Próximo Capítulo &#62;]