include::./index.adoc[]

[[v58-2-0]]
=== Hebreus, 2
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v58-2-1]]

^<<v58-2-1,1>>^ É por isso que é necessário prestarmos mais do que a costumeira atenção às^&#42;1^ coisas ouvidas por nós, para que nunca nos desviemos.

[NOTE]
====
. Lit.: “atentar mais abundantemente nas”.
====

[[v58-2-2]]

^<<v58-2-2,2>>^ Pois, se a palavra falada por intermédio de anjos mostrou-se firme, e toda transgressão e ato desobediente recebeu retribuição^&#42;1^ em harmonia com a justiça,

[NOTE]
====
. Lit.: “remuneração”.
====

[[v58-2-3]]

^<<v58-2-3,3>>^ como escaparemos nós, se tivermos negligenciado^&#42;1^ uma salvação de tal magnitude, sendo que começou a ser anunciada por intermédio do [nosso] Senhor e nos foi confirmada por aqueles que o ouviram,

[NOTE]
====
. Lit.: “estado desinteressados”.
====

[[v58-2-4]]

^<<v58-2-4,4>>^ ao passo que Deus se juntou em dar testemunho com sinais, e também com portentos e várias obras poderosas,^&#42;1^ e com distribuições de espírito santo, segundo a sua vontade?

[NOTE]
====
. Ou “vários milagres”.
====

[[v58-2-5]]

^<<v58-2-5,5>>^ Pois, não é a anjos que ele sujeitou a vindoura terra habitada,^&#42;1^ da qual estamos falando.

[NOTE]
====
. Lit. só “habitada”. Gr.: oi·kou·mé·nen, fem. sing., referindo-se à terra; lat.: ór·bem tér·rae, “círculo da terra”. Veja Is 13:11 n.: “produtivo”.
====

[[v58-2-6]]

^<<v58-2-6,6>>^ Mas, certa testemunha deu prova, em alguma parte, dizendo: “Que é o homem para que te lembres dele, ou [o] filho do homem, para que tomes conta dele?

[[v58-2-7]]

^<<v58-2-7,7>>^ Tu o fizeste um pouco^&#42;1^ menor que os anjos; de glória e honra o coroaste e o designaste sobre as obras das tuas mãos.^&#42;2^

[NOTE]
====
. Ou “por um pouco [de tempo]”.
. “E o designaste sobre as obras das tuas mãos”, אACD°VgSyp e Sal 8:6; P46BDc omitem isso.
====

[[v58-2-8]]

^<<v58-2-8,8>>^ Sujeitaste todas as coisas aos seus pés.” Ora, ao lhe sujeitar todas as coisas, [Deus]^&#42;1^ não deixou nada que não lhe fosse sujeito. Agora, porém, ainda não vemos todas as coisas sujeitas a ele,

[NOTE]
====
. Lit.: “ele”.
====

[[v58-2-9]]

^<<v58-2-9,9>>^ mas observamos a Jesus, que havia sido feito um pouco^&#42;1^ menor que os anjos, coroado de glória e de honra por ter sofrido a morte, para que, pela benignidade imerecida de Deus, provasse a morte por todo^&#42;2^ [homem].

[NOTE]
====
. Ou “por um pouco [de tempo]”.
. Ou “toda sorte de”.
====

[[v58-2-10]]

^<<v58-2-10,10>>^ Porque era próprio que aquele, para quem são todas as coisas e por intermédio de quem são todas as coisas, trazendo muitos filhos à glória, aperfeiçoasse por sofrimentos o Agente Principal^&#42;1^ da salvação deles.

[NOTE]
====
. Lit.: “Líder Principal.”
====

[[v58-2-11]]

^<<v58-2-11,11>>^ Porque tanto aquele que santifica como os que estão sendo santificados^&#42;1^ [provêm] todos de um só, e por esta causa ele não se envergonha de chamá-los “irmãos”,^&#42;2^

[NOTE]
====
. Ou “os que são tidos por sagrados (tratados como santos)”. Gr.: hoi ha·gi·a·zó·me·noi; lat.: qui sanc·ti·fi·cán·tur; J17,22(hebr.): ham·qud·da·shím.
. “Irmãos.” Gr.: a·del·foús; lat.: frá·tes; J17,18,22(hebr.): ’a·hhím.
====

[[v58-2-12]]

^<<v58-2-12,12>>^ dizendo: “Declararei o teu nome a meus irmãos; no meio da congregação^&#42;1^ louvar-te-ei com cântico.”

[NOTE]
====
. Lit.: “de eclésia”. Gr.: ek·kle·sí·as; lat.: ec·clé·si·ae; J17,18,22(hebr.): qa·hál.
====

[[v58-2-13]]

^<<v58-2-13,13>>^ E, novamente: “Terei nele a minha confiança.” E, novamente: “Aqui estou eu e as criancinhas que Jeová^&#42;1^ me deu.”

[NOTE]
====
. Veja Ap. 1D.
====

[[v58-2-14]]

^<<v58-2-14,14>>^ Portanto, visto que as “criancinhas” são partícipes de sangue e carne, ele participou também similarmente das mesmas coisas, para que, pela sua morte, reduzisse a nada^&#42;1^ aquele que tem os meios de causar a morte, isto é, o Diabo,^&#42;2^

[NOTE]
====
. Ou “destruísse (tornasse inativo)”.
. “Diabo”, אABVg; SypJ17, 18,22: “Satanás; Satã”.
====

[[v58-2-15]]

^<<v58-2-15,15>>^ e [para que] emancipasse todos os que pelo temor da morte estavam toda a sua vida sujeitos à escravidão.

[[v58-2-16]]

^<<v58-2-16,16>>^ Pois ele realmente não auxilia em nada os anjos, mas auxilia o descendente de Abraão.

[[v58-2-17]]

^<<v58-2-17,17>>^ Conseqüentemente, ele estava obrigado a tornar-se igual aos seus “irmãos” em todos os sentidos, para se tornar sumo sacerdote^&#42;1^ misericordioso e fiel nas coisas referentes a Deus, a fim de oferecer sacrifício propiciatório^&#42;2^ pelos pecados do povo.

[NOTE]
====
. Lit.: “principal sacerdote”.
. Lit.: “estar fazendo propiciação”.
====

[[v58-2-18]]

^<<v58-2-18,18>>^ Por ter ele mesmo sofrido, ao ser posto à prova, pode vir em auxílio daqueles que estão sendo postos à prova.

'''

xref:058-hebreus/058-hebreus-001.adoc#v58-1-0[&#60; Capítulo Anterior] | <<v58-2-0,Topo>> | xref:058-hebreus/058-hebreus-003.adoc#v58-3-0[Próximo Capítulo &#62;]