include::./index.adoc[]

[[v58-7-0]]
=== Hebreus, 7
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v58-7-1]]

^<<v58-7-1,1>>^ Porque este Melquisedeque, rei de Salém, sacerdote do Deus Altíssimo, que foi ao encontro de Abraão, quando [este] voltava da matança dos reis, e o abençoou,

[[v58-7-2]]

^<<v58-7-2,2>>^ e a quem Abraão repartiu um décimo de todas as coisas, é primeiramente, por tradução, “Rei da Justiça”, e é então também rei de Salém, isto é, “Rei da Paz”.

[[v58-7-3]]

^<<v58-7-3,3>>^ Sem pai, sem mãe, sem genealogia, não tendo nem princípio de dias nem fim de vida, mas tendo sido feito semelhante ao Filho de Deus, permanece sacerdote perpetuamente.

[[v58-7-4]]

^<<v58-7-4,4>>^ Observai, pois, quão grande era este homem, a quem Abraão, o chefe de família,^&#42;1^ deu o décimo dos principais despojos.

[NOTE]
====
. “Chefe de família.” Lit.: “patriarca”. Gr.: pa·tri·ár·khes.
====

[[v58-7-5]]

^<<v58-7-5,5>>^ Deveras, os homens dos filhos de Levi que recebem o seu cargo sacerdotal têm o mandamento de cobrar dízimos do povo, segundo a Lei, isto é, dos seus irmãos, embora estes procedessem dos lombos de Abraão;

[[v58-7-6]]

^<<v58-7-6,6>>^ mas o homem que não derivou deles a sua genealogia tomou dízimos de Abraão e abençoou aquele que tinha as promessas.

[[v58-7-7]]

^<<v58-7-7,7>>^ Ora, além de qualquer disputa,^&#42;1^ o que é menor é abençoado pelo maior.

[NOTE]
====
. Lit.: “contradição”. Gr.: an·ti·lo·gí·as.
====

[[v58-7-8]]

^<<v58-7-8,8>>^ E, num caso, os que recebem dízimos são homens que morrem, mas, no outro caso, é alguém de quem se testemunha que vive.

[[v58-7-9]]

^<<v58-7-9,9>>^ E, se eu puder usar a expressão, por intermédio de Abraão, até mesmo Levi, que recebe dízimos, pagou dízimos,

[[v58-7-10]]

^<<v58-7-10,10>>^ porque ele estava ainda nos lombos de seu antepassado quando Melquisedeque foi ao encontro dele.

[[v58-7-11]]

^<<v58-7-11,11>>^ Se, pois, a perfeição fosse realmente por intermédio do sacerdócio levítico, (porque o povo recebeu a Lei com ele por particularidade,)^&#42;1^ que necessidade adicional haveria de surgir outro sacerdote à maneira^&#42;2^ de Melquisedeque e de quem não se diz que seja à maneira de Arão?

[NOTE]
====
. Ou “tendo-o por base”.
. Veja 5:6 n.
====

[[v58-7-12]]

^<<v58-7-12,12>>^ Pois, mudando-se o sacerdócio, necessariamente há também mudança da lei.

[[v58-7-13]]

^<<v58-7-13,13>>^ Porque o homem de quem se dizem estas coisas tem sido membro de outra tribo, da qual ninguém oficiou junto ao altar.

[[v58-7-14]]

^<<v58-7-14,14>>^ Pois é bastante claro que o nosso Senhor procedeu de Judá, tribo da qual Moisés não disse nada quanto a sacerdotes.

[[v58-7-15]]

^<<v58-7-15,15>>^ E é ainda muito mais claro que, na semelhança de Melquisedeque, surge outro sacerdote,

[[v58-7-16]]

^<<v58-7-16,16>>^ que se tornou tal, não segundo a lei dum mandamento dependente da carne, mas segundo o poder duma vida indestrutível,^&#42;1^

[NOTE]
====
. Lit.: “indissolúvel”.
====

[[v58-7-17]]

^<<v58-7-17,17>>^ pois se diz em testemunho: “Tu és sacerdote para sempre à maneira de Melquisedeque.”

[[v58-7-18]]

^<<v58-7-18,18>>^ Certamente, pois, há uma ab-rogação do mandamento precedente por causa da sua fraqueza e ineficácia.^&#42;1^

[NOTE]
====
. Lit.: “improficuidade”.
====

[[v58-7-19]]

^<<v58-7-19,19>>^ Porque a Lei não fez nada perfeito, mas a introdução adicional duma melhor esperança o fez, sendo por intermédio dela que nos chegamos a Deus.

[[v58-7-20]]

^<<v58-7-20,20>>^ Também, ao ponto que não foi sem juramento afiançado,

[[v58-7-21]]

^<<v58-7-21,21>>^ (pois há deveras homens que se tornaram sacerdotes sem juramento afiançado, mas há um com juramento afiançado por Aquele que disse com respeito a ele: “Jeová^&#42;1^ jurou (e não o deplorará): ‘Tu és sacerdote para sempre’”,)

[NOTE]
====
. Veja Ap. 1D.
====

[[v58-7-22]]

^<<v58-7-22,22>>^ a este ponto também Jesus se tornou aquele que foi dado em penhor dum pacto^&#42;1^ melhor.

[NOTE]
====
. Veja Ap. 7D.
====

[[v58-7-23]]

^<<v58-7-23,23>>^ Outrossim, muitos se tinham de tornar sacerdotes [em sucessão], por serem impedidos pela morte de continuarem como tais,

[[v58-7-24]]

^<<v58-7-24,24>>^ mas ele, por continuar vivo para sempre, tem o seu sacerdócio sem quaisquer sucessores.^&#42;1^

[NOTE]
====
. Ou “sacerdócio não sucessível (não transferível)”.
====

[[v58-7-25]]

^<<v58-7-25,25>>^ Por conseguinte, ele é também capaz de salvar completamente os que se aproximam de Deus por intermédio dele, porque está sempre vivo para interceder^&#42;1^ por eles.

[NOTE]
====
. Lit.: “para estar intercedendo”.
====

[[v58-7-26]]

^<<v58-7-26,26>>^ Pois, para nós era apropriado tal sumo sacerdote, leal, cândido, imaculado, separado dos pecadores e que chegou a ser mais alto do que os céus.

[[v58-7-27]]

^<<v58-7-27,27>>^ Ele não precisa, como aqueles sumos sacerdotes, oferecer diariamente sacrifícios, primeiro pelos seus próprios pecados e depois pelos do povo: (porque isto ele fez uma vez para sempre quando se ofereceu a si mesmo;)

[[v58-7-28]]

^<<v58-7-28,28>>^ porque a Lei designa como sumos sacerdotes a homens que têm fraquezas, mas a palavra do juramento afiançado, que veio depois da Lei, [designa] um Filho, que é aperfeiçoado^&#42;1^ para sempre.

[NOTE]
====
. Ou “inaugurado; investido; consagrado no cargo; empossado”. Gr.: te·te·lei·o·mé·non. Veja 5:9 n.
====

'''

xref:058-hebreus/058-hebreus-006.adoc#v58-6-0[&#60; Capítulo Anterior] | <<v58-7-0,Topo>> | xref:058-hebreus/058-hebreus-008.adoc#v58-8-0[Próximo Capítulo &#62;]