include::./index.adoc[]

[[v63-1-0]]
=== 2 João, 1
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v63-1-1]]

^<<v63-1-1,1>>^ O ancião,^&#42;1^ à senhora escolhida^&#42;2^ e aos filhos dela, a quem eu amo verdadeiramente,^&#42;3^ e não somente eu, mas também todos os que chegaram a conhecer a verdade,

[NOTE]
====
. “Ancião.” Gr.: pre·sbý·te·ros.
. Ou “à mulher escolhida, Kyria”. Gr.: e·kle·kteí ky·rí·ai.
. Ou “eu amo na verdade”.
====

[[v63-1-2]]

^<<v63-1-2,2>>^ por causa da verdade que permanece em nós, e ela estará conosco para sempre.

[[v63-1-3]]

^<<v63-1-3,3>>^ Haverá conosco benignidade imerecida, misericórdia [e] paz da parte de Deus, o Pai, e da parte de Jesus Cristo, o Filho do Pai, com verdade e amor.

[[v63-1-4]]

^<<v63-1-4,4>>^ Alegro-me muitíssimo por ter achado^&#42;1^ certos dos teus filhos andando na verdade, assim como recebemos mandamento da parte do Pai.

[NOTE]
====
. Ou: “Alegrei-me muitíssimo de realmente achar.”
====

[[v63-1-5]]

^<<v63-1-5,5>>^ Agora, pois, solicito-te, senhora,^&#42;1^ como [alguém] que te escreve, não um novo mandamento, mas um que temos tido desde [o] princípio:^&#42;2^ que nos amemos uns aos outros.

[NOTE]
====
. Ou “Kyria”.
. “Desde [o] princípio.” Gr.: ap’ ar·khés; lat.: ab i·ní·ti·o; J17(hebr.): me·ró’sh.
====

[[v63-1-6]]

^<<v63-1-6,6>>^ E o amor significa o seguinte: que prossigamos andando segundo os seus mandamentos. O mandamento é este, como ouvistes desde [o] princípio: que deveis prosseguir andando nele.

[[v63-1-7]]

^<<v63-1-7,7>>^ Pois, muitos enganadores saíram pelo mundo afora, pessoas que não confessam Jesus Cristo vindo^&#42;1^ na carne. Este é o enganador^&#42;2^ e o anticristo.

[NOTE]
====
.  “Vindo.” Gr.: er·khó·me·non, referindo-se à vinda passada de Cristo. Refere-se ao tempo passado, como no caso do particípio gr. em 3Jo 3, onde veja a n.: “vieram”.
. “Lit.: “o errante”.
====

[[v63-1-8]]

^<<v63-1-8,8>>^ Acautelai-vos para que não percais^&#42;1^ as coisas que produzimos por trabalho, mas para que obtenhais uma plena recompensa.

[NOTE]
====
. Lit.: “destruais”.
====

[[v63-1-9]]

^<<v63-1-9,9>>^ Todo aquele que se adianta^&#42;1^ e não permanece no ensino do Cristo não tem Deus. Quem permanece neste ensino é quem tem tanto o Pai como o Filho.

[NOTE]
====
. Lit.: “Todo aquele que vai na frente.”
====

[[v63-1-10]]

^<<v63-1-10,10>>^ Se alguém se chegar a vós e não trouxer este ensino, nunca o recebais nos vossos lares, nem o cumprimenteis.^&#42;1^

[NOTE]
====
. Lit.: “vos estejais alegrando”.
====

[[v63-1-11]]

^<<v63-1-11,11>>^ Pois, quem o cumprimenta é partícipe^&#42;1^ das suas obras iníquas.^&#42;2^

[NOTE]
====
. Lit.: “participa”.
. Vgs acrescenta: “Eis que eu vos disse [isso] de antemão, para que não ficásseis confusos no dia do Senhor”; J7,8 acrescentam: “(Eis que eu vos disse [isso] de antemão, para que não ficásseis envergonhados no dia de Jeová.)”
====

[[v63-1-12]]

^<<v63-1-12,12>>^ Embora eu tenha muitas coisas para vos escrever, não desejo fazer isso com papel e tinta, mas espero ir ter convosco e falar-vos face a face,^&#42;1^ para que a vossa alegria seja plena.

[NOTE]
====
. Lit.: “boca a boca”.
====

[[v63-1-13]]

^<<v63-1-13,13>>^ Os filhos da tua irmã, a escolhida, mandam-te os seus cumprimentos.

'''

xref:062-1-joao/062-1-joao-005.adoc#v62-5-0[&#60; Capítulo Anterior] | <<v63-1-0,Topo>> | xref:064-3-joao/064-3-joao-001.adoc#v64-1-0[Próximo Capítulo &#62;]