include::./index.adoc[]

[[v53-3-0]]
=== 2 Tessalonicenses, 3
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v53-3-1]]

^<<v53-3-1,1>>^ Finalmente, irmãos, fazei orações por nós, para que a palavra de Jeová^&#42;1^ prossiga rapidamente e seja glorificada, assim como de fato se dá convosco;

[NOTE]
====
. Veja Ap. 1D.
====

[[v53-3-2]]

^<<v53-3-2,2>>^ e que sejamos livrados de homens nocivos e iníquos, pois a fé não é propriedade de todos.

[[v53-3-3]]

^<<v53-3-3,3>>^ Mas o Senhor é fiel, e ele vos fará firmes e vos guardará do iníquo.

[[v53-3-4]]

^<<v53-3-4,4>>^ Ademais, temos confiança no Senhor, quanto a vós, de que fazeis e continuareis a fazer as coisas que ordenamos.

[[v53-3-5]]

^<<v53-3-5,5>>^ O Senhor continue a dirigir os vossos corações com bom êxito ao amor de Deus e à perseverança pelo Cristo.

[[v53-3-6]]

^<<v53-3-6,6>>^ Ora, nós vos ordenamos, irmãos, no nome do Senhor Jesus Cristo, que vos retireis de todo irmão que andar desordeiramente e não segundo a tradição^&#42;1^ que recebestes de nós.

[NOTE]
====
. Ou “instrução”.
====

[[v53-3-7]]

^<<v53-3-7,7>>^ Porque vós mesmos sabeis o modo em que deveis imitar-nos, porque nós não nos comportamos desordeiramente entre vós,

[[v53-3-8]]

^<<v53-3-8,8>>^ nem comemos de graça o alimento de outro. Ao contrário, por labor e labuta, noite e dia, trabalhávamos para não impor a nenhum de vós um fardo dispendioso.

[[v53-3-9]]

^<<v53-3-9,9>>^ Não é que não tenhamos autoridade, mas a fim de que nos oferecêssemos a vós como exemplo, para nos imitardes.

[[v53-3-10]]

^<<v53-3-10,10>>^ De fato, também, quando estávamos convosco, costumávamos dar-vos esta ordem: “Se alguém não quiser trabalhar, tampouco coma.”

[[v53-3-11]]

^<<v53-3-11,11>>^ Pois ouvimos que certos estão andando desordeiramente entre vós, não trabalhando nada, mas intrometendo-se no que não lhes diz respeito.

[[v53-3-12]]

^<<v53-3-12,12>>^ A tais pessoas damos a ordem e a exortação, no Senhor Jesus Cristo, que, por trabalharem com sossego, comam o alimento que eles mesmos ganham.

[[v53-3-13]]

^<<v53-3-13,13>>^ Da vossa parte, irmãos, não desistais de fazer o que é direito.

[[v53-3-14]]

^<<v53-3-14,14>>^ Mas, se alguém não for obediente à nossa palavra por intermédio desta carta, tomai nota de tal,^&#42;1^ parai de associar-vos com^&#42;2^ ele, para que fique envergonhado.

[NOTE]
====
. Lit.: “ponde sinal neste”.
. Lit.: “não vos mistureis com”.
====

[[v53-3-15]]

^<<v53-3-15,15>>^ Contudo, não o considereis como inimigo, mas continuai a admoestá-lo^&#42;1^ como irmão.

[NOTE]
====
. Lit.: “ponde mente nele”.
====

[[v53-3-16]]

^<<v53-3-16,16>>^ O próprio Senhor da paz vos dê agora constantemente a paz, de toda maneira. O Senhor seja com todos vós.

[[v53-3-17]]

^<<v53-3-17,17>>^ [Aqui está] o meu cumprimento, o de Paulo, pela minha própria mão, que é sinal em cada carta; é assim que eu escrevo.

[[v53-3-18]]

^<<v53-3-18,18>>^ A benignidade imerecida de nosso Senhor Jesus Cristo seja com todos vós.

'''

xref:053-2-tessalonicenses/053-2-tessalonicenses-002.adoc#v53-2-0[&#60; Capítulo Anterior] | <<v53-3-0,Topo>> | xref:054-1-timoteo/054-1-timoteo-001.adoc#v54-1-0[Próximo Capítulo &#62;]