include::./index.adoc[]

[[v55-2-0]]
=== 2 Timóteo, 2
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v55-2-1]]

^<<v55-2-1,1>>^ Tu, pois, filho meu, persiste em adquirir poder^&#42;1^ na benignidade imerecida que há em conexão com Cristo Jesus,

[NOTE]
====
. Lit.: “vem recebendo poder”.
====

[[v55-2-2]]

^<<v55-2-2,2>>^ e as coisas que ouviste de mim, com o apoio de muitas testemunhas, destas coisas encarrega homens fiéis, os quais, por sua vez, estarão adequadamente habilitados para ensinar outros.

[[v55-2-3]]

^<<v55-2-3,3>>^ Como soldado excelente de Cristo Jesus, participa em sofrer o mal.

[[v55-2-4]]

^<<v55-2-4,4>>^ Nenhum homem, servindo como soldado,^&#42;1^ se envolve nos negócios comerciais da vida, a fim de que possa ganhar a aprovação daquele que o alistou como soldado.

[NOTE]
====
. Lit.: “prestando serviço militar”.
====

[[v55-2-5]]

^<<v55-2-5,5>>^ Além disso, quando alguém compete, mesmo nos jogos,^&#42;1^ não é coroado a menos que tenha competido segundo as regras.

[NOTE]
====
. Lit.: “quando alguém está atuando como atleta”.
====

[[v55-2-6]]

^<<v55-2-6,6>>^ O lavrador que trabalha arduamente tem de ser o primeiro a participar dos frutos.

[[v55-2-7]]

^<<v55-2-7,7>>^ Pensa constantemente^&#42;1^ no que digo; o Senhor te dará realmente discernimento em todas as coisas.

[NOTE]
====
. Lit.: “Vê mentalmente o.”
====

[[v55-2-8]]

^<<v55-2-8,8>>^ Lembra-te de que Jesus Cristo foi levantado dentre os mortos e era do descendente de Davi, segundo as boas novas que prego,

[[v55-2-9]]

^<<v55-2-9,9>>^ sendo que em conexão com elas estou sofrendo o mal a ponto de [estar em] cadeias como malfeitor. Não obstante, a palavra de Deus não está amarrada.

[[v55-2-10]]

^<<v55-2-10,10>>^ Por isso prossigo perseverando em todas as coisas pela causa dos escolhidos, para que eles também possam obter a salvação que há em união com Cristo Jesus, junto com glória eterna.

[[v55-2-11]]

^<<v55-2-11,11>>^ Fiel é a palavra: Se morrermos juntos, certamente havemos também de viver juntos;

[[v55-2-12]]

^<<v55-2-12,12>>^ se perseverarmos, havemos também de reinar juntos; se negarmos, ele também nos negará;

[[v55-2-13]]

^<<v55-2-13,13>>^ se formos infiéis, ele permanece fiel, pois não se pode negar a si mesmo.

[[v55-2-14]]

^<<v55-2-14,14>>^ Persiste em fazê-los lembrar essas coisas, advertindo-os perante Deus,^&#42;1^ como testemunha, de que não lutem sobre palavras, coisa que não é de nenhuma utilidade, porque subverte os que estão escutando.

[NOTE]
====
. “Deus”, אC; ADVg: “o Senhor”; J7,8,13,14,16: “Jeová”.
====

[[v55-2-15]]

^<<v55-2-15,15>>^ Faze o máximo para te apresentar a Deus aprovado, obreiro que não tem nada de que se envergonhar, manejando corretamente a palavra da verdade.

[[v55-2-16]]

^<<v55-2-16,16>>^ Mas esquiva-te dos falatórios vãos que violam o que é santo; porque passarão a impiedade^&#42;1^ cada vez maior

[NOTE]
====
. Lit.: “irreverência”.
====

[[v55-2-17]]

^<<v55-2-17,17>>^ e a palavra deles se espalhará como gangrena. Himeneu e Fileto são desses.

[[v55-2-18]]

^<<v55-2-18,18>>^ Estes mesmos se desviaram da verdade, dizendo que a ressurreição já ocorreu; e estão subvertendo a fé que alguns têm.

[[v55-2-19]]

^<<v55-2-19,19>>^ Apesar de tudo isso, o sólido alicerce^&#42;1^ de Deus fica de pé, tendo este selo: “Jeová^&#42;2^ conhece os que lhe pertencem”, e: “Todo aquele que menciona o nome de Jeová^&#42;3^ renuncie à injustiça.”

[NOTE]
====
. “Alicerce.” Gr.: the·mé·li·os; lat.: fun·da·mén·tum.
. Veja Ap. 1D.
. Veja Ap. 1D.
====

[[v55-2-20]]

^<<v55-2-20,20>>^ Ora, numa casa grande não há só vasos de ouro e de prata, mas também de madeira e de barro, e alguns para fim honroso, mas outros para fim sem honra.

[[v55-2-21]]

^<<v55-2-21,21>>^ Portanto, se alguém se mantiver livre destes últimos,^&#42;1^ será vaso para fim honroso, santificado, útil para o seu dono, preparado para toda boa obra.

[NOTE]
====
. Ou, só “destes”.
====

[[v55-2-22]]

^<<v55-2-22,22>>^ Por isso, foge dos desejos pertinentes à mocidade,^&#42;1^ mas empenha-te pela justiça, pela fé, pelo amor, pela paz, ao lado dos que invocam o Senhor^&#42;2^ dum coração puro.

[NOTE]
====
. “Pertinentes à mocidade.” Ou “naturais aos jovens”. Lit.: “juvenis”. Gr.: ne·o·te·ri·kás; lat.: iu·ve·ní·li·a.
. “O Senhor”, אAVg; J7,8,17,22: “Jeová”.
====

[[v55-2-23]]

^<<v55-2-23,23>>^ Outrossim, recusa questões tolas e ignorantes, sabendo que produzem lutas.

[[v55-2-24]]

^<<v55-2-24,24>>^ Mas o escravo do Senhor^&#42;1^ não precisa lutar, porém, precisa ser meigo^&#42;2^ para com todos, qualificado para ensinar, restringindo-se sob o mal,

[NOTE]
====
. “Senhor”, אAVg; J16,24: “Jeová”.
. Ou “jeitoso”.
====

[[v55-2-25]]

^<<v55-2-25,25>>^ instruindo com brandura os que não estiverem favoravelmente dispostos, visto que talvez Deus lhes dê arrependimento conduzindo a um conhecimento exato da verdade

[[v55-2-26]]

^<<v55-2-26,26>>^ e eles voltem ao seu próprio juízo, saindo do laço do Diabo, visto que foram apanhados vivos por ele para a vontade deste.

'''

xref:055-2-timoteo/055-2-timoteo-001.adoc#v55-1-0[&#60; Capítulo Anterior] | <<v55-2-0,Topo>> | xref:055-2-timoteo/055-2-timoteo-003.adoc#v55-3-0[Próximo Capítulo &#62;]