include::./index.adoc[]

[[v55-1-0]]
=== 2 Timóteo, 1
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v55-1-1]]

^<<v55-1-1,1>>^ Paulo, apóstolo de Cristo Jesus, pela vontade de Deus, segundo a promessa da vida que está em união com Cristo Jesus,

[[v55-1-2]]

^<<v55-1-2,2>>^ a Timóteo, filho amado:
Haja benignidade imerecida, misericórdia, paz da parte de Deus, [o] Pai, e de Cristo Jesus, nosso Senhor.

[[v55-1-3]]

^<<v55-1-3,3>>^ Sou grato a Deus, a quem estou prestando serviço sagrado^&#42;1^ assim como os meus antepassados fizeram, e com uma consciência limpa, que nunca deixo de me lembrar de ti nas minhas súplicas, noite e dia,

[NOTE]
====
. “Estou prestando serviço sagrado.” Gr.: la·treú·o; J17(hebr.): ’aní ‛o·védh, “eu sirvo (adoro)”. Veja Êx 3:12 n.
====

[[v55-1-4]]

^<<v55-1-4,4>>^ tendo saudade de ti, ao me lembrar de tuas lágrimas, para que eu fique cheio de alegria.

[[v55-1-5]]

^<<v55-1-5,5>>^ Pois eu me recordo da fé que há em ti sem qualquer hipocrisia, e que houve primeiro em tua avó Lóide e em tua mãe Eunice, mas, estou confiante, que há também em ti.

[[v55-1-6]]

^<<v55-1-6,6>>^ Por esta mesma causa faço-te lembrar que atices, como a um fogo, o dom de Deus que há em ti pela imposição das minhas mãos.

[[v55-1-7]]

^<<v55-1-7,7>>^ Porque Deus não nos deu um espírito de covardia, mas de poder, e de amor, e de bom juízo.

[[v55-1-8]]

^<<v55-1-8,8>>^ Portanto, não te envergonhes do testemunho^&#42;1^ a respeito de nosso Senhor, nem de mim, prisioneiro pela causa dele,^&#42;2^ mas participa em sofrer o mal pelas boas novas, segundo o poder de Deus.

[NOTE]
====
. “Testemunho.” Gr.: mar·tý·ri·on; lat.: te·sti·mó·ni·um.
. Ou “de mim, seu prisioneiro”.
====

[[v55-1-9]]

^<<v55-1-9,9>>^ Ele nos salvou e nos chamou com uma chamada santa, não em razão de nossas obras, mas em razão de seu próprio propósito e benignidade imerecida. Isto nos foi dado em conexão com Cristo Jesus antes dos tempos de longa duração,^&#42;1^

[NOTE]
====
. Ou “tempos eternos”.
====

[[v55-1-10]]

^<<v55-1-10,10>>^ mas agora se tornou claramente evidente pela manifestação de nosso Salvador, Cristo Jesus, que aboliu^&#42;1^ a morte, mas lançou luz sobre a vida e a incorrupção por intermédio das boas novas,

[NOTE]
====
. Lit.: “tendo ab-rogado”.
====

[[v55-1-11]]

^<<v55-1-11,11>>^ para as quais fui designado pregador, e apóstolo, e instrutor.

[[v55-1-12]]

^<<v55-1-12,12>>^ Por esta mesma causa eu também sofro essas coisas, mas não me envergonho. Pois conheço aquele em quem tenho crido e estou confiante^&#42;1^ em que ele é capaz de guardar o que lhe confiei, até aquele dia.

[NOTE]
====
. Lit.: “fiquei persuadido de”.
====

[[v55-1-13]]

^<<v55-1-13,13>>^ Apega-te ao modelo de palavras salutares que ouviste de mim com a fé e o amor que há em conexão com Cristo Jesus.

[[v55-1-14]]

^<<v55-1-14,14>>^ Guarda, por intermédio do espírito santo que mora em nós, o que de excelente te foi confiado.

[[v55-1-15]]

^<<v55-1-15,15>>^ Sabes o seguinte, que todos os homens no^&#42;1^ [distrito da] Ásia se desviaram de mim. Figelo e Hermógenes são desses.

[NOTE]
====
. Ou “do”.
====

[[v55-1-16]]

^<<v55-1-16,16>>^ O Senhor^&#42;1^ conceda misericórdia à família de Onesíforo, porque ele muitas vezes me trouxe revigoramento e não se envergonhou das minhas cadeias.

[NOTE]
====
. “O Senhor”, אAVg; J7,8,13,14,16: “Jeová”.
====

[[v55-1-17]]

^<<v55-1-17,17>>^ Ao contrário, quando ele estava em Roma, procurou-me diligentemente e me achou.

[[v55-1-18]]

^<<v55-1-18,18>>^ O Senhor^&#42;1^ lhe conceda achar naquele dia misericórdia da parte de Jeová.^&#42;2^ E sabes muito bem^&#42;3^ todos os serviços que ele prestou em Éfeso.

[NOTE]
====
. “O Senhor”, אAVg; J7,8,13,14,16: “Jeová”.
. Veja Ap. 1D.
. Ou “sabes melhor do que eu”.
====

'''

xref:054-1-timoteo/054-1-timoteo-006.adoc#v54-6-0[&#60; Capítulo Anterior] | <<v55-1-0,Topo>> | xref:055-2-timoteo/055-2-timoteo-002.adoc#v55-2-0[Próximo Capítulo &#62;]