include::./index.adoc[]

[[v55-3-0]]
=== 2 Timóteo, 3
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v55-3-1]]

^<<v55-3-1,1>>^ Sabe, porém, isto, que nos últimos dias haverá tempos críticos, difíceis de manejar.^&#42;1^

[NOTE]
====
. Lit.: “ferozes”.
====

[[v55-3-2]]

^<<v55-3-2,2>>^ Pois os homens serão amantes de si mesmos, amantes do dinheiro, pretensiosos, soberbos,^&#42;1^ blasfemadores,^&#42;2^ desobedientes aos pais, ingratos, desleais,

[NOTE]
====
. Lit.: “com ares de superioridade”.
. Ou “falando de modo ultrajante”.
====

[[v55-3-3]]

^<<v55-3-3,3>>^ sem afeição natural, não dispostos a acordos,^&#42;1^ caluniadores,^&#42;2^ sem autodomínio, ferozes,^&#42;3^ sem amor à bondade,

[NOTE]
====
. Lit.: “sem trégua”.
. Lit.: “diabos”. Gr.: di·á·bo·loi.
. Lit.: “indômitos”.
====

[[v55-3-4]]

^<<v55-3-4,4>>^ traidores, teimosos, enfunados [de orgulho], mais amantes de prazeres do que amantes de Deus,

[[v55-3-5]]

^<<v55-3-5,5>>^ tendo uma forma de devoção piedosa,^&#42;1^ mostrando-se, porém, falsos para com o seu poder; e destes afasta-te.

[NOTE]
====
. “Devoção piedosa.” Lit.: “reverenciando bem”.
====

[[v55-3-6]]

^<<v55-3-6,6>>^ Pois, dentre estes surgem aqueles homens que se introduzem ardilosamente^&#42;1^ nas famílias e levam cativas mulheres fracas, sobrecarregadas de pecados, levadas por vários desejos,

[NOTE]
====
. “Se introduzem ardilosamente.” Lit.: “infiltram-se”.
====

[[v55-3-7]]

^<<v55-3-7,7>>^ sempre aprendendo, contudo, nunca podendo chegar a um conhecimento exato da verdade.

[[v55-3-8]]

^<<v55-3-8,8>>^ Ora, do modo como Janes e Jambres resistiram a Moisés, assim também estes prosseguem resistindo à verdade, homens completamente corruptos na mente, reprovados quanto à fé.

[[v55-3-9]]

^<<v55-3-9,9>>^ Não obstante, não farão mais progresso, pois a insensatez deles ficará bem clara a todos, assim como ficou a daqueles [dois homens].

[[v55-3-10]]

^<<v55-3-10,10>>^ Mas tu seguiste de perto o meu ensino, meu proceder na vida, meu propósito, minha fé, minha longanimidade, meu amor, minha perseverança,

[[v55-3-11]]

^<<v55-3-11,11>>^ minhas perseguições, meus sofrimentos, a sorte de coisa que me aconteceu em Antioquia, em Icônio, em Listra, a sorte de perseguição que agüentei; contudo, o Senhor me livrou de todos esses.

[[v55-3-12]]

^<<v55-3-12,12>>^ De fato, todos os que desejarem viver com devoção piedosa em associação com Cristo Jesus também serão perseguidos.

[[v55-3-13]]

^<<v55-3-13,13>>^ Mas os homens iníquos e os impostores passarão de mal a pior, desencaminhando e sendo desencaminhados.

[[v55-3-14]]

^<<v55-3-14,14>>^ Tu, porém, continua nas coisas que aprendeste e ficaste persuadido a crer, sabendo de que pessoas as aprendeste

[[v55-3-15]]

^<<v55-3-15,15>>^ e que desde a infância tens conhecido os escritos sagrados, que te podem fazer sábio para a salvação, por intermédio da fé em conexão com Cristo Jesus.

[[v55-3-16]]

^<<v55-3-16,16>>^ Toda a Escritura é inspirada por Deus^&#42;1^ e proveitosa para ensinar, para repreender, para endireitar as coisas,^&#42;2^ para disciplinar em justiça,

[NOTE]
====
. Lit.: “soprada por Deus”. Gr.: The·ó·pneu·stos; lat.: Di·ví·ni·tus in·spi·rá·ta; J17(hebr.): berú·ahh ’Elo·hím, “pelo espírito de Deus”.
. Lit.: “endireitando sobre”.
====

[[v55-3-17]]

^<<v55-3-17,17>>^ a fim de que o homem de Deus seja plenamente competente, completamente equipado^&#42;1^ para toda boa obra.

[NOTE]
====
. Lit.: “tendo sido equipado”.
====

'''

xref:055-2-timoteo/055-2-timoteo-002.adoc#v55-2-0[&#60; Capítulo Anterior] | <<v55-3-0,Topo>> | xref:055-2-timoteo/055-2-timoteo-004.adoc#v55-4-0[Próximo Capítulo &#62;]