include::./index.adoc[]

[[v55-4-0]]
=== 2 Timóteo, 4
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v55-4-1]]

^<<v55-4-1,1>>^ Eu te mando solenemente, perante Deus e Cristo Jesus,^&#42;1^ que está destinado a julgar os vivos e os mortos, e pela sua manifestação e pelo seu reino:

[NOTE]
====
. Veja Ap. 6E.
====

[[v55-4-2]]

^<<v55-4-2,2>>^ prega a palavra, ocupa-te nisso urgentemente, em época favorável, em época dificultosa, repreende, adverte,^&#42;1^ exorta, com toda a longanimidade e [arte de] ensino.

[NOTE]
====
. Lit.: “censura”, imperativo.
====

[[v55-4-3]]

^<<v55-4-3,3>>^ Pois haverá um período de tempo em que não suportarão o ensino salutar, porém, de acordo com os seus próprios desejos, acumularão para si instrutores para lhes fazerem cócegas nos ouvidos;

[[v55-4-4]]

^<<v55-4-4,4>>^ e desviarão os seus ouvidos da verdade, ao passo que serão desviados para histórias falsas.^&#42;1^

[NOTE]
====
. Lit.: “mitos”. Gr.: mý·thous; lat.: fá·bu·las, “fábulas”.
====

[[v55-4-5]]

^<<v55-4-5,5>>^ Tu, porém, mantém os teus sentidos em todas as coisas, sofre o mal, faze [a] obra dum evangelizador,^&#42;1^ efetua plenamente^&#42;2^ o teu ministério.

[NOTE]
====
. Ou “dum missionário”. Gr.: eu·ag·ge·li·stoú; lat.: e·van·ge·lí·stae.
. Lit.: “arca plenamente com”.
====

[[v55-4-6]]

^<<v55-4-6,6>>^ Pois, já estou sendo derramado como oferta de bebida, e o tempo devido para o meu livramento^&#42;1^ é iminente.

[NOTE]
====
. Veja Ap. 5D.
====

[[v55-4-7]]

^<<v55-4-7,7>>^ Tenho travado a luta excelente,^&#42;1^ tenho corrido até o fim da carreira, tenho observado a fé.^&#42;2^

[NOTE]
====
. Lit.: “A peleja excelente eu tenho pelejado.”
. Ou “tenho mantido a fidelidade”.
====

[[v55-4-8]]

^<<v55-4-8,8>>^ Doravante me está reservada a coroa da justiça, que o Senhor, o justo juiz, me dará como recompensa naquele dia, contudo, não somente a mim, mas também a todos os que amaram a sua manifestação.

[[v55-4-9]]

^<<v55-4-9,9>>^ Faze o máximo para vir ter comigo em breve.

[[v55-4-10]]

^<<v55-4-10,10>>^ Pois Demas me abandonou, porque amava o atual sistema de coisas,^&#42;1^ e foi para Tessalônica; Crescente [foi] para a Galácia, Tito para a Dalmácia.

[NOTE]
====
. Ou “ordem de coisas”. Gr.: ai·ó·na; lat.: saé·cu·lum; J17,18,22(hebr.): ha·‛oh·lám, “a ordem de coisas”.
====

[[v55-4-11]]

^<<v55-4-11,11>>^ Apenas Lucas está comigo. Toma a Marcos e traze-o contigo, porque ele me é útil para ministrar.

[[v55-4-12]]

^<<v55-4-12,12>>^ Porém, mandei Tíquico para Éfeso.

[[v55-4-13]]

^<<v55-4-13,13>>^ Quando vieres, traze o manto que deixei em Trôade com Carpo, e os rolos,^&#42;1^ especialmente os pergaminhos.

[NOTE]
====
. Lit.: “livrinhos”. Gr.: bi·blí·a; lat.: lí·bros, “livros”.
====

[[v55-4-14]]

^<<v55-4-14,14>>^ Alexandre, o latoeiro, causou-me muitos danos — Jeová^&#42;1^ lhe pagará de volta segundo as suas ações —

[NOTE]
====
. Veja Ap. 1D.
====

[[v55-4-15]]

^<<v55-4-15,15>>^ e tu também, guarda-te dele, porque ele resistiu às nossas palavras num grau excessivo.

[[v55-4-16]]

^<<v55-4-16,16>>^ Na minha primeira defesa, ninguém se pôs do meu lado, mas todos passaram a abandonar-me — não lhes seja isso posto na conta —

[[v55-4-17]]

^<<v55-4-17,17>>^ mas o Senhor estava perto de mim e me infundiu poder, para que, por meu intermédio, se efetuasse plenamente a pregação e todas as nações a ouvissem; e fui livrado da boca do leão.

[[v55-4-18]]

^<<v55-4-18,18>>^ O Senhor me livrará de toda obra iníqua e [me] salvará para o seu reino celestial. A ele seja a glória para todo o sempre. Amém.

[[v55-4-19]]

^<<v55-4-19,19>>^ Dá os meus cumprimentos a Prisca^&#42;1^ e a Áquila, e à família de Onesíforo.

[NOTE]
====
. Ou “Priscila”.
====

[[v55-4-20]]

^<<v55-4-20,20>>^ Erasto ficou em Corinto, mas deixei Trófimo doente em Mileto.

[[v55-4-21]]

^<<v55-4-21,21>>^ Faze o máximo para chegar antes do inverno.
Êubulo manda os seus cumprimentos, e [também] Pudente, e Lino, e Cláudia, e todos^&#42;1^ os irmãos.

[NOTE]
====
. “Todos”, AVgSyp; א° omite isso.
====

[[v55-4-22]]

^<<v55-4-22,22>>^ O Senhor [esteja] com o espírito que [mostras]. Sua benignidade imerecida [seja] convosco.

'''

xref:055-2-timoteo/055-2-timoteo-003.adoc#v55-3-0[&#60; Capítulo Anterior] | <<v55-4-0,Topo>> | xref:056-tito/056-tito-001.adoc#v56-1-0[Próximo Capítulo &#62;]