include::./index.adoc[]

[[v15-8-0]]
=== Esdras, 8
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v15-8-1]]

^<<v15-8-1,1>>^ Ora, estes foram os cabeças das suas casas paternas e o registro genealógico dos que subiram comigo de Babilônia durante o reinado de Artaxerxes, o rei:

[[v15-8-2]]

^<<v15-8-2,2>>^ Dos filhos de Finéias, Gersom; dos filhos de Itamar, Daniel; dos filhos de Davi, Hatus;

[[v15-8-3]]

^<<v15-8-3,3>>^ dos filhos de Secanias, dos filhos de Parós, Zacarias, e com ele havia uma lista de cento e cinqüenta machos;

[[v15-8-4]]

^<<v15-8-4,4>>^ dos filhos de Paate-Moabe, Elieó-Enai, filho de Zeraías, e com ele duzentos machos;

[[v15-8-5]]

^<<v15-8-5,5>>^ dos filhos de [Zatu],^&#42;1^ Secanias, filho de Jaaziel, e com ele trezentos machos;

[NOTE]
====
. “Dos filhos de Zatu”, LXX.
====

[[v15-8-6]]

^<<v15-8-6,6>>^ e dos filhos de Adim, Ebede, filho de Jonatã, e com ele cinqüenta machos;

[[v15-8-7]]

^<<v15-8-7,7>>^ e dos filhos de Elão, Jesaías, filho de Atalias, e com ele setenta machos;

[[v15-8-8]]

^<<v15-8-8,8>>^ e dos filhos de Sefatias, Zebadias, filho de Micael, e com ele oitenta machos;

[[v15-8-9]]

^<<v15-8-9,9>>^ dos filhos de Joabe, Obadias, filho de Jeiel, e com ele duzentos e dezoito machos;

[[v15-8-10]]

^<<v15-8-10,10>>^ e dos filhos de [Bani],^&#42;1^ Selomite, filho de Josifias, e com ele cento e sessenta machos;

[NOTE]
====
. “Bani”, LXX. Veja 2:10.
====

[[v15-8-11]]

^<<v15-8-11,11>>^ e dos filhos de Bebai, Zacarias, filho de Bebai, e com ele vinte e oito machos;

[[v15-8-12]]

^<<v15-8-12,12>>^ e dos filhos de Asgade, Joanã, filho de Hacatã, e com ele cento e dez machos;

[[v15-8-13]]

^<<v15-8-13,13>>^ e dos filhos de Adonicão, os que foram os últimos, e seus nomes eram estes: Elifelete, Jeiel e Semaías, e com eles sessenta machos;

[[v15-8-14]]

^<<v15-8-14,14>>^ e dos filhos de Bigvai, Utai e Zábude,^&#42;1^ e com eles setenta machos.

[NOTE]
====
. “Zacur”, Mmargem.
====

[[v15-8-15]]

^<<v15-8-15,15>>^ E passei a reuni-los junto ao rio que chega a Aava; e ali ficamos acampados por três dias, para que eu pudesse inspecionar o povo e os sacerdotes, mas não achei ali nenhum dos filhos de Levi.

[[v15-8-16]]

^<<v15-8-16,16>>^ Por conseguinte, mandei [chamar] a Eliézer, Ariel, Semaías e Elnatã, e Jaribe, e Elnatã, e Natã, e Zacarias, e Mesulão, os cabeças, e Joiaribe e Elnatã, instrutores.^&#42;1^

[NOTE]
====
. Ou “homens inteligentes (entendidos)”.
====

[[v15-8-17]]

^<<v15-8-17,17>>^ Dei-lhes então ordem referente a Ido, o cabeça na localidade de Casifia, e pus na sua boca as palavras que deviam falar a Ido [e] a seus irmãos,^&#42;1^ os netineus,^&#42;2^ na localidade de Casifia, a fim de que nos trouxessem ministros^&#42;3^ para a casa de nosso Deus.

[NOTE]
====
. “Ido e a seus irmãos”, Vgc; M: “Ido, seu irmão”.
. Veja 2:43 n.
. Ou “ajudantes”. Hebr.: meshor·thím; lat.: mi·ní·stros.
====

[[v15-8-18]]

^<<v15-8-18,18>>^ Portanto, segundo a boa mão de nosso Deus sobre nós, trouxeram-nos um homem de discrição dos filhos de Mali, neto de Levi, filho de Israel, a saber, Serebias, e seus filhos, e seus irmãos, dezoito;

[[v15-8-19]]

^<<v15-8-19,19>>^ e Hasabias e com ele Jesaías, dos filhos de Merari, seus irmãos e seus filhos, vinte.

[[v15-8-20]]

^<<v15-8-20,20>>^ E dos netineus, que Davi e os príncipes deram para o serviço dos levitas, duzentos e vinte netineus, todos eles tendo sido designados por nomes.

[[v15-8-21]]

^<<v15-8-21,21>>^ Então proclamei um jejum ali junto ao rio Aava, para nos humilharmos diante de nosso Deus, a fim de procurarmos dele o caminho direito para nós, e para os nossos pequeninos, e para todos os nossos bens.

[[v15-8-22]]

^<<v15-8-22,22>>^ Porque tive vergonha de pedir ao rei uma força militar e cavaleiros para nos ajudar contra o inimigo no caminho, porque tínhamos dito ao rei: “A mão de nosso Deus está sobre todos os que o procuram para o bem, mas a sua força e a sua ira são contra todos os que o abandonam.”

[[v15-8-23]]

^<<v15-8-23,23>>^ Por isso jejuamos e fizemos uma solicitação a nosso Deus concernente a isso, de modo que ele se deixou suplicar por nós.

[[v15-8-24]]

^<<v15-8-24,24>>^ Então separei dentre os chefes dos sacerdotes doze, a saber, Serebias, Hasabias e com eles dez de seus irmãos.

[[v15-8-25]]

^<<v15-8-25,25>>^ E passei a pesar-lhes a prata e o ouro, e os utensílios, a contribuição para a casa de nosso Deus, contribuída pelo rei e por seus conselheiros, e seus príncipes, e todos os israelitas que se podiam achar.

[[v15-8-26]]

^<<v15-8-26,26>>^ Assim pesei-lhe na mão seiscentos e cinqüenta talentos^&#42;1^ de prata e cem utensílios de prata valendo [dois] talentos, [e] ouro, cem talentos,

[NOTE]
====
. Um talento pesava 34,2 kg.
====

[[v15-8-27]]

^<<v15-8-27,27>>^ e vinte tigelinhas de ouro valendo mil daricos,^&#42;1^ e dois utensílios de cobre bom, de brilho vermelho, tão desejável como o ouro.

[NOTE]
====
. Moeda persa de ouro, que pesava 8,4 g.
====

[[v15-8-28]]

^<<v15-8-28,28>>^ Eu lhes disse então: “Vós sois algo santo para Jeová, e os utensílios são algo santo, e a prata e o ouro são uma oferta voluntária a Jeová, o Deus de vossos antepassados.

[[v15-8-29]]

^<<v15-8-29,29>>^ Ficai alerta e vigiai até [os] terdes pesado diante dos chefes dos sacerdotes e dos levitas, e dos príncipes dos pais de Israel em Jerusalém, nos refeitórios da casa de Jeová.”

[[v15-8-30]]

^<<v15-8-30,30>>^ E os sacerdotes e os levitas receberam o peso da prata, e do ouro, e dos utensílios, a fim de [os] levar a Jerusalém, à casa de nosso Deus.

[[v15-8-31]]

^<<v15-8-31,31>>^ Por fim partimos do rio Aava no décimo segundo [dia] do primeiro mês, a fim de ir para Jerusalém, e a própria mão de nosso Deus mostrou estar sobre nós, de modo que ele nos livrou da palma da mão do inimigo e da emboscada no caminho.

[[v15-8-32]]

^<<v15-8-32,32>>^ Chegamos, pois, a Jerusalém e moramos ali por três dias.

[[v15-8-33]]

^<<v15-8-33,33>>^ E no quarto dia passamos a pesar a prata, e o ouro, e os utensílios, na casa de nosso Deus, na mão de Meremote, filho de Urijá, o sacerdote, e com ele Eleazar, filho de Finéias, e com eles Jozabade, filho de Jesua,^&#42;1^ e Noadias, filho de Binui, os levitas,

[NOTE]
====
. “Jesus”, LXX.
====

[[v15-8-34]]

^<<v15-8-34,34>>^ por número [e] por peso para tudo, anotando-se depois todo o peso naquele tempo.

[[v15-8-35]]

^<<v15-8-35,35>>^ Os que saíram do cativeiro, os anteriores exilados,^&#42;1^ apresentaram eles mesmos sacrifícios queimados ao Deus de Israel, doze novilhos para todo o Israel, noventa e seis carneiros, setenta e sete cordeiros, doze bodes como oferta pelo pecado, tudo como oferta queimada a Jeová.

[NOTE]
====
. Lit.: “os filhos do Exílio”.
====

[[v15-8-36]]

^<<v15-8-36,36>>^ Então entregamos as leis do rei aos sátrapas^&#42;1^ do rei e aos governadores de além do Rio,^&#42;2^ e eles auxiliaram o povo e a casa do [verdadeiro] Deus.

[NOTE]
====
. Significando “protetores do domínio”, aplicado aos principais governantes de distritos jurisdicionais.
. Isto é, o Eufrates.
====

'''

xref:015-esdras/015-esdras-007.adoc#v15-7-0[&#60; Capítulo Anterior] | <<v15-8-0,Topo>> | xref:015-esdras/015-esdras-009.adoc#v15-9-0[Próximo Capítulo &#62;]