include::./index.adoc[]

[[v39-2-0]]
=== Malaquias, 2
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v39-2-1]]

^<<v39-2-1,1>>^ “E agora, este mandamento é para vós, ó sacerdotes.

[[v39-2-2]]

^<<v39-2-2,2>>^ Se não escutardes, e se não [o] tomardes ao coração dar glória ao meu nome”, disse Jeová dos exércitos, “então hei de enviar sobre vós a maldição e vou amaldiçoar as vossas bênçãos. Sim, eu até mesmo amaldiçoei a [bênção],^&#42;1^ porque não [o] tomais ao coração.”

[NOTE]
====
. Lit.: “ela”, hebr. fem., referindo-se à bênção, hebr. fem.
====

[[v39-2-3]]

^<<v39-2-3,3>>^ “Eis que por vossa causa censuro a semente [semeada] e vou espalhar esterco^&#42;1^ sobre as vossas faces, o esterco das vossas festividades; e alguém realmente vos carregará até ele.

[NOTE]
====
. Ou “fezes”. Possivelmente: “o conteúdo do estômago”.
====

[[v39-2-4]]

^<<v39-2-4,4>>^ E tereis de saber que vos enviei este mandamento, a fim de que continue meu pacto com Levi”,^&#42;1^ disse Jeová dos exércitos.

[NOTE]
====
. “Levi”, MTSyVg; LXX: “os levitas”.
====

[[v39-2-5]]

^<<v39-2-5,5>>^ “Quanto ao meu pacto, mostrou ser com ele, [um] de vida e de paz, e continuei a dá-las a ele, junto com medo. E ele continuou a temer-me; sim, porque ele mesmo ficou aterrorizado por causa do meu nome.

[[v39-2-6]]

^<<v39-2-6,6>>^ A própria lei da verdade^&#42;1^ mostrou estar na sua boca e não se achou injustiça nos seus lábios. Andava comigo em paz e em retidão, e muitos foram os que ele fez recuar do erro.

[NOTE]
====
. Ou “veridicidade; veracidade”. Hebr.: ’eméth; lat.: ve·ri·tá·tis.
====

[[v39-2-7]]

^<<v39-2-7,7>>^ Pois, são os lábios do sacerdote que devem guardar o conhecimento e da sua boca devem as pessoas procurar [a] lei; porque ele é o mensageiro^&#42;1^ de Jeová dos exércitos.

[NOTE]
====
. “Mensageiro.” Hebr.: mal·’ákh; gr.: ág·ge·los; lat.: án·ge·lus.
====

[[v39-2-8]]

^<<v39-2-8,8>>^ “Mas vós, homens — vós vos desviastes do caminho. Fizestes muitos tropeçar na lei. Arruinastes o pacto de Levi”, disse Jeová dos exércitos.

[[v39-2-9]]

^<<v39-2-9,9>>^ “E também eu, da minha parte, certamente farei que sejais desprezados e rebaixados para todo o povo, porquanto não guardastes meus caminhos, porém, mostrastes parcialidade na lei.”

[[v39-2-10]]

^<<v39-2-10,10>>^ “Não é um só pai que todos nós temos? Não foi um só Deus^&#42;1^ que nos criou? Por que é que agimos traiçoeiramente uns para com os outros, profanando o pacto de nossos antepassados?

[NOTE]
====
. “Deus.” Hebr.: ’El; gr.: The·ós; lat.: Dé·us.
====

[[v39-2-11]]

^<<v39-2-11,11>>^ Judá agiu traiçoeiramente e cometeu-se uma coisa detestável em Israel e em Jerusalém; porque Judá profanou a santidade de Jeová, que Ele amou, e apossou-se da filha dum deus^&#42;1^ estrangeiro como noiva.

[NOTE]
====
. “Deus.” Hebr.: ’el; gr.: the·oús, “deuses”; lat.: dé·i.
====

[[v39-2-12]]

^<<v39-2-12,12>>^ Jeová decepará a todo aquele que fizer isso, aquele que estiver desperto e aquele que responder, das tendas de Jacó, e aquele que apresentar uma oferenda a Jeová dos exércitos.”

[[v39-2-13]]

^<<v39-2-13,13>>^ “E esta é a segunda coisa que fazeis, [resultando em] que o altar de Jeová esteja coberto de lágrimas, de choro e de suspiros, de modo que não mais se olha para a oferenda, nem se tem prazer [em qualquer coisa] procedente da vossa mão.

[[v39-2-14]]

^<<v39-2-14,14>>^ E dissestes: ‘Por que razão?’ Por esta razão: que o próprio Jeová deu testemunho entre ti e a esposa da tua mocidade, para com a qual tu mesmo agiste traiçoeiramente, embora ela seja tua parceira e a esposa do teu pacto.

[[v39-2-15]]

^<<v39-2-15,15>>^ E houve um que não [o] fez, visto que tinha o que restava^&#42;1^ do espírito. E o que procurava este um? A descendência de Deus.^&#42;2^ E vós tereis de guardar-vos quanto ao vosso espírito, e que nenhum [de vós] aja traiçoeiramente com a esposa da sua mocidade.

[NOTE]
====
. Lit.: “visto que . . . o restante (resto)”. Hebr.: u·she’ár.
. “Deus.” Hebr.: ’Elo·hím; gr.: ho The·ós; lat.: Dé·i.
====

[[v39-2-16]]

^<<v39-2-16,16>>^ Pois ele tem odiado o divórcio”,^&#42;1^ disse Jeová, o Deus de Israel; “e aquele que cobriu a sua vestimenta de violência”, disse Jeová dos exércitos. “E tendes de guardar-vos quanto ao vosso espírito e não deveis agir traiçoeiramente.

[NOTE]
====
. Lit.: “despedir; mandar embora”. Veja Mt 1:19 n.
====

[[v39-2-17]]

^<<v39-2-17,17>>^ “Fatigastes a Jeová com as vossas palavras e dissestes: ‘De que modo [o] fatigamos?’ Por dizerdes: ‘Todo aquele que faz o mal é bom aos olhos de Jeová e de tais é que ele mesmo se agrada’; ou: ‘Onde está o Deus^&#42;1^ da justiça?’”

[NOTE]
====
. “Deus da.” Hebr.: ’Elo·héh; lat.: Dé·us.
====

'''

xref:039-malaquias/039-malaquias-001.adoc#v39-1-0[&#60; Capítulo Anterior] | <<v39-2-0,Topo>> | xref:039-malaquias/039-malaquias-003.adoc#v39-3-0[Próximo Capítulo &#62;]