include::./index.adoc[]

[[v39-3-0]]
=== Malaquias, 3
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v39-3-1]]

^<<v39-3-1,1>>^ “Eis que envio o meu mensageiro^&#42;1^ e ele terá de desobstruir o caminho diante de mim. E repentinamente virá ao Seu templo^&#42;2^ o [verdadeiro] Senhor,^&#42;3^ a quem procurais, e o mensageiro^&#42;4^ do pacto, em quem vos agradais. Eis que virá certamente”, disse Jeová dos exércitos.

[NOTE]
====
. “Meu mensageiro.” Hebr.: mal·’a·khí; lat.: án·ge·lum. Veja n. do Título.
. “Seu templo.” Hebr.: heh·kha·lóh; gr.: na·ón; lat.: tém·plum. Veja Mt 23:16 n.
. “O [verdadeiro] Senhor.” Hebr.: ha·’A·dhóhn; gr.: Ký·ri·os; lat.: Do·mi·ná·tor. Veja Ap. 1H.
. “E o mensageiro (anjo).” Hebr.: u·mal·’akh; gr.: ág·ge·los; lat.: án·ge·lus.
====

[[v39-3-2]]

^<<v39-3-2,2>>^ “Mas quem agüentará o dia da sua vinda e quem se manterá de pé quando ele aparecer? Pois ele será como o fogo do refinador e como a barrela dos lavadeiros.

[[v39-3-3]]

^<<v39-3-3,3>>^ E terá de assentar-se como refinador e purificador de prata e terá de purificar os filhos de Levi;^&#42;1^ e terá de depurá-los como o ouro e como a prata, e hão de tornar-se para Jeová pessoas que apresentam uma oferenda em justiça.

[NOTE]
====
. “Levi.” Hebr.: Le·wí.
====

[[v39-3-4]]

^<<v39-3-4,4>>^ E a oferenda de Judá e de Jerusalém será realmente agradável a Jeová, como nos dias de há muito tempo e como nos anos da antiguidade.

[[v39-3-5]]

^<<v39-3-5,5>>^ “E vou chegar-me a vós para julgamento e vou tornar-me testemunha veloz contra os feiticeiros, e contra os adúlteros,^&#42;1^ e contra os que juram falsamente, e contra os que agem fraudulentamente com o salário do assalariado, com [a] viúva e com [o] menino órfão de pai, e os que repelem o residente forasteiro, ao passo que não me temeram”, disse Jeová dos exércitos.

[NOTE]
====
. “Adúlteros.” Lat.: a·dúl·te·ris.
====

[[v39-3-6]]

^<<v39-3-6,6>>^ “Pois eu sou Jeová; não mudei. E vós sois filhos de Jacó; não chegastes ao vosso fim.

[[v39-3-7]]

^<<v39-3-7,7>>^ Desde os dias de vossos antepassados vos desviastes dos meus regulamentos e não [os] guardastes. Retornai a mim e eu vou retornar a vós”, disse Jeová dos exércitos.
E vós dissestes: “De que modo retornaremos?”

[[v39-3-8]]

^<<v39-3-8,8>>^ “Porventura roubará o homem terreno^&#42;1^ a Deus?^&#42;2^ Mas vós me roubais.”
E dissestes: “De que modo te roubamos?”
“Nas décimas partes^&#42;3^ e nas contribuições.

[NOTE]
====
. “Homem terreno.” Hebr.: ’a·dhám; lat.: hó·mo.
. “Deus.” Hebr.: ’Elo·hím; lat.: Dé·um.
. “Décimas partes.” Ou “dízimos”.
====

[[v39-3-9]]

^<<v39-3-9,9>>^ Vós [me] amaldiçoais^&#42;1^ com a maldição e é a mim que roubais — a nação na sua inteireza.

[NOTE]
====
. “Vós [me] amaldiçoais” era a versão original. Os soferins alteraram o texto para rezar “vós sois amaldiçoados”, por respeito a Deus. Veja Ap. 2B.
====

[[v39-3-10]]

^<<v39-3-10,10>>^ Trazei todas as décimas partes à casa do depósito para que venha a haver alimento na minha casa; e experimentai-me, por favor, neste respeito”, disse Jeová dos exércitos, “se eu não vos abrir as comportas dos céus e realmente despejar sobre vós uma bênção até que não haja mais necessidade”.

[[v39-3-11]]

^<<v39-3-11,11>>^ “E eu vou censurar por vós o devorador^&#42;1^ e ele não mais arruinará para vós o fruto do solo, nem se mostrará a videira no campo infrutífera para vós”, disse Jeová dos exércitos.

[NOTE]
====
. Ou “o comedor”, referindo-se a um inseto.
====

[[v39-3-12]]

^<<v39-3-12,12>>^ “E todas as nações terão de declarar-vos felizes, porque vós mesmos vos tornareis uma terra de agrado”, disse Jeová dos exércitos.

[[v39-3-13]]

^<<v39-3-13,13>>^ “Fortes foram as vossas palavras contra mim”, disse Jeová.
E dissestes: “Que falamos entre nós contra ti?”

[[v39-3-14]]

^<<v39-3-14,14>>^ “Dissestes: ‘De nada vale servir a Deus. E que lucro há em termos cumprido a obrigação para com ele e em termos andado acabrunhados por causa de Jeová dos exércitos?

[[v39-3-15]]

^<<v39-3-15,15>>^ E atualmente declaramos felizes os presunçosos. Também os praticantes da iniqüidade foram edificados. Eles também têm experimentado a Deus^&#42;1^ e conseguem safar-se.’”

[NOTE]
====
. “Deus.” Hebr.: ’Elo·hím; lat.: Dé·um.
====

[[v39-3-16]]

^<<v39-3-16,16>>^ Naquele tempo, os que temiam a Jeová falaram um ao outro, cada um ao seu companheiro, e Jeová prestava atenção e escutava. E começou-se a escrever perante ele um livro de recordação^&#42;1^ para os que temiam a Jeová e para os que pensavam no seu nome.

[NOTE]
====
. Ou “registro”.
====

[[v39-3-17]]

^<<v39-3-17,17>>^ “E eles hão de tornar-se meus”, disse Jeová dos exércitos, “no dia em que eu produzir uma propriedade especial. E vou ter compaixão deles assim como o homem^&#42;1^ tem compaixão do seu filho que o serve.

[NOTE]
====
. “O homem.” Hebr.: ’ish.
====

[[v39-3-18]]

^<<v39-3-18,18>>^ E vós haveis de ver novamente^&#42;1^ [a diferença] entre o justo e o iníquo, entre o que serve a Deus e o que não o serviu.”

[NOTE]
====
. Lit.: “haveis de retornar e ver”.
====

'''

xref:039-malaquias/039-malaquias-002.adoc#v39-2-0[&#60; Capítulo Anterior] | <<v39-3-0,Topo>> | xref:039-malaquias/039-malaquias-004.adoc#v39-4-0[Próximo Capítulo &#62;]