include::./index.adoc[]

[[v25-4-0]]
=== Lamentações, 4
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

_א [Álefe]_

[[v25-4-1]]

^<<v25-4-1,1>>^ Como fica fosco o ouro reluzente, o ouro bom!^&#42;1^
Como se derramaram as pedras sagradas^&#42;2^ à cabeceira de todas as ruas!

[NOTE]
====
. Ou: “Como fica fosco o ouro [hebr.: za·háv], como fica mudado o ouro [hebr.: hak·ké·them] bom!” Veja Jó 28:16, 17 n.
. Ou “as pedras do santuário”.
====

_ב [Bete]_

[[v25-4-2]]

^<<v25-4-2,2>>^ Quanto aos filhos preciosos de Sião, os que foram pesados com ouro refinado,^&#42;1^
Como foram considerados como grandes talhas de barro, trabalho das mãos dum oleiro!

[NOTE]
====
. “Com ouro refinado.” Hebr.: bap·páz.
====

_ג [Guímel]_

[[v25-4-3]]

^<<v25-4-3,3>>^ Até mesmo os próprios chacais ofereceram o úbere. Amamentaram suas crias.
A filha do meu povo está ficando cruel, quais avestruzes no ermo.

_ד [Dálete]_

[[v25-4-4]]

^<<v25-4-4,4>>^ A língua da criança de peito ficou apegada ao céu de sua boca por causa da sede.
As próprias crianças pediram pão. Não há quem [o] reparta a elas.

_ה [Hê]_

[[v25-4-5]]

^<<v25-4-5,5>>^ Os mesmos que comiam coisas agradáveis foram tomados de espanto nas ruas.
Os mesmos que foram criados em escarlate tiveram de abraçar montes de cinzas.

_ו [Vau]_

[[v25-4-6]]

^<<v25-4-6,6>>^ A [punição pelo] erro da filha do meu povo vem a ser também maior do que a [punição pelo] pecado de Sodoma,
Que foi subvertida como que num instante e para a qual não se voltaram mãos [para ajudar].

_ז [Zaine]_

[[v25-4-7]]

^<<v25-4-7,7>>^ Seus nazireus eram mais puros do que a neve; eram mais brancos do que o leite.
Eram de fato mais corados do que corais; seu lustro era o da safira.

_ח [Hete]_

[[v25-4-8]]

^<<v25-4-8,8>>^ Seu aspecto ficou mais escuro do que o próprio negrume. Não foram reconhecidos nas ruas.
Sua pele enrugou-se sobre os seus ossos. Ficou tão seca como uma árvore.

_ט [Tete]_

[[v25-4-9]]

^<<v25-4-9,9>>^ Melhores mostraram ser os mortos à espada do que os mortos pela fome,
Porque estes se definham,^&#42;1^ traspassados pela falta dos produtos da campina.

[NOTE]
====
. Lit.: “escorrem”, evidentemente em sentido figurativo.
====

_י [Iode]_

[[v25-4-10]]

^<<v25-4-10,10>>^ As próprias mãos de mulheres compassivas cozinharam seus próprios filhos.
Tornaram-se qual pão para alguém durante o desmoronamento da filha do meu povo.

_כ [Cafe]_

[[v25-4-11]]

^<<v25-4-11,11>>^ Jeová levou a cabo seu furor. Derramou a sua ira ardente.
E ele acende um fogo em Sião, que consome os alicerces dela.

_ל [Lâmede]_

[[v25-4-12]]

^<<v25-4-12,12>>^ Os reis da terra e todos os habitantes do solo produtivo^&#42;1^ não acreditaram
Que o adversário e o inimigo iam entrar pelos portões de Jerusalém.

[NOTE]
====
. “Do solo produtivo.” Hebr.: the·vél; LXX: “da terra habitada”; lat.: ór·bis, “o círculo”, isto é, da terra.
====

_מ [Meme]_

[[v25-4-13]]

^<<v25-4-13,13>>^ Por causa dos pecados dos seus profetas, pelos erros de seus sacerdotes,
Havia no meio dela os que derramavam o sangue dos justos.

_נ [Nune]_

[[v25-4-14]]

^<<v25-4-14,14>>^ Andavam errantes como cegos pelas ruas. Poluíram-se com sangue,
De modo que ninguém pode tocar nas suas vestimentas.

_ם [Sâmeque]_

[[v25-4-15]]

^<<v25-4-15,15>>^ “Saí do caminho! Imundo!” clamaram para eles. “Saí do caminho! Saí do caminho! Não toqueis!”
Pois ficaram sem lar. Também andaram errantes. Disse-se entre as nações: “Não residirão mais como forasteiros.

_פ [Pê]_

[[v25-4-16]]

^<<v25-4-16,16>>^ A face de Jeová os repartiu. Não olhará mais para eles.
Os homens certamente não mostrarão consideração nem mesmo pelos sacerdotes. Certamente não mostrarão favor nem mesmo para com os homens idosos.”

_ע [Aine]_

[[v25-4-17]]

^<<v25-4-17,17>>^ Ainda enquanto existimos, nossos olhos estão esmorecendo em vão pelo auxílio para nós.
Enquanto olhávamos em volta, olhávamos para uma nação que não podia trazer salvação.

_צ [Tsadê]_

[[v25-4-18]]

^<<v25-4-18,18>>^ Acossavam os nossos passos, de modo que não se anda nas nossas praças públicas.
Chegou perto o nosso fim. Cumpriram-se os nossos dias, pois chegou o nosso fim.

_ק [Cofe]_

[[v25-4-19]]

^<<v25-4-19,19>>^ Nossos perseguidores mostraram ser mais velozes do que as águias dos céus.
Perseguiram-nos encarniçadamente sobre os montes. No ermo puseram-se de emboscada contra nós.

_ר [Rexe]_

[[v25-4-20]]

^<<v25-4-20,20>>^ O próprio fôlego^&#42;1^ das nossas narinas, o ungido^&#42;2^ de Jeová,^&#42;3^ foi capturado na sua grande cova,
Aquele de quem dissemos: “À sua sombra viveremos entre as nações.”

[NOTE]
====
. Ou “espírito (vento)”. Hebr.: rú·ahh; gr.: pneú·ma; lat.: spí·ri·tus.
. “Ungido de.” Hebr.: meshí·ahh; gr.: khri·stós; sir.: meshi·hheh; lat.: chrí·stus.
. “O ungido Senhor”, LXXBagsterVg.
====

_ש [Sim]_

[[v25-4-21]]

^<<v25-4-21,21>>^ Exulta e alegra-te, ó filha de Edom, morando como estás na terra de Uz.
Também a ti se passará o copo.^&#42;1^ Ficarás embriagada e te mostrarás desnuda.

[NOTE]
====
. “O copo”, MSyVg; T: “o copo de maldição”; LXX: “o copo de Jeová”.
====

_ת [Tau]_

[[v25-4-22]]

^<<v25-4-22,22>>^ Teu erro, ó filha de Sião, chegou ao seu fim. Ele não^&#42;1^ te levará novamente ao exílio.
Ele voltou a sua atenção para o teu erro, ó filha de Edom. Expôs os teus pecados.

[NOTE]
====
. Ou: “Ninguém.”
====

'''

xref:025-lamentacoes/025-lamentacoes-003.adoc#v25-3-0[&#60; Capítulo Anterior] | <<v25-4-0,Topo>> | xref:025-lamentacoes/025-lamentacoes-005.adoc#v25-5-0[Próximo Capítulo &#62;]