include::./index.adoc[]

[[v25-2-0]]
=== Lamentações, 2
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

_א [Álefe]_

[[v25-2-1]]

^<<v25-2-1,1>>^ Como Jeová,^&#42;1^ na sua ira, enublou a filha de Sião!
Lançou a beleza de Israel do céu para a terra.
E não se lembrou do seu escabelo no dia da sua ira.

[NOTE]
====
. Uma das 134 mudanças de YHWH para ’Adho·naí feitas pelos escribas. Veja Ap. 1B.
====

_ב [Bete]_

[[v25-2-2]]

^<<v25-2-2,2>>^ Jeová^&#42;1^ tragou, não teve compaixão de qualquer lugar de permanência de Jacó.
Na sua fúria derrubou as praças fortes da filha de Judá.
Pôs em contato com a terra, profanou o reino e os príncipes dela.

[NOTE]
====
. Veja v. 1 n.
====

_ג [Guímel]_

[[v25-2-3]]

^<<v25-2-3,3>>^ No ardor da ira, ele cortou todo chifre de Israel.
Fez recuar a sua direita de diante do inimigo;
E continua ardendo em Jacó como fogo chamejante que devora em todo o redor.

_ד [Dálete]_

[[v25-2-4]]

^<<v25-2-4,4>>^ Ele entesou seu arco como um inimigo. Sua direita tomou posição
Como um adversário, e ele matava a todos os desejáveis aos olhos.
Derramou seu furor como fogo na tenda da filha de Sião.

_ה [Hê]_

[[v25-2-5]]

^<<v25-2-5,5>>^ Jeová^&#42;1^ tornou-se como um inimigo. Tragou a Israel.
Tragou todas as suas torres de habitação; arruinou as suas praças fortes.
E na filha de Judá faz abundar luto e lamentação.

[NOTE]
====
. Veja v. 1 n.
====

_ו [Vau]_

[[v25-2-6]]

^<<v25-2-6,6>>^ E ele trata com violência a sua barraca, como a que há num jardim. Arruinou a sua festividade.
Jeová fez esquecer em Sião a festividade e o sábado.
E na sua verberação irada não respeita nem rei nem sacerdote.

_ז [Zaine]_

[[v25-2-7]]

^<<v25-2-7,7>>^ Jeová^&#42;1^ deitou fora seu altar. Repeliu seu santuário.
Entregou na mão do inimigo as muralhas das suas torres de habitação.
Deram vazão à [sua] própria voz na casa de Jeová, como num dia de festividade.

[NOTE]
====
. Veja v. 1 n.
====

_ח [Hete]_

[[v25-2-8]]

^<<v25-2-8,8>>^ Jeová pensou em arruinar a muralha da filha de Sião.
Estendeu o cordel de medir. Não fez a sua mão recuar do tragar.
E ele faz prantear a escarpa e a muralha. Juntamente se desfizeram.

_ט [Tete]_

[[v25-2-9]]

^<<v25-2-9,9>>^ Seus portões afundaram na própria terra. Destruiu-lhe e destroçou-lhe as trancas.
O rei e os príncipes dela estão entre as nações. Não há lei.
Também os seus próprios profetas não encontraram nenhuma visão da parte de Jeová.

_י [Iode]_

[[v25-2-10]]

^<<v25-2-10,10>>^ Os anciãos da filha de Sião assentam-se na terra, ficando quietos.
Puseram pó sobre a sua cabeça. Cingiram-se de serapilheira.
As virgens de Jerusalém baixaram a sua cabeça até o chão.

_כ [Cafe]_

[[v25-2-11]]

^<<v25-2-11,11>>^ Meus olhos acabaram em puras lágrimas. Meus intestinos estão em fermento.
Meu fígado se derramou por terra por causa da derrocada da filha do meu povo,
Por se debilitarem a criança e o bebê nas praças públicas da vila.

_ל [Lâmede]_

[[v25-2-12]]

^<<v25-2-12,12>>^ Diziam às suas mães: “Onde estão o cereal e o vinho?”
Por se debilitarem como alguém que foi morto nas praças públicas da cidade,
Por se derramar a sua alma no seio de suas mães.

_מ [Meme]_

[[v25-2-13]]

^<<v25-2-13,13>>^ De que é que te usarei por testemunha? A que te assemelharei, ó filha de Jerusalém?
A que te igualarei para te consolar, ó virgem filha de Sião?
Pois o teu quebrantamento é tão grande como o mar. Quem te pode trazer cura?

_נ [Nune]_

[[v25-2-14]]

^<<v25-2-14,14>>^ Teus próprios profetas tiveram para ti visões de coisas fúteis e insatisfatórias,
E não expuseram o teu erro para fazer recuar o teu cativeiro,
Mas continuaram a ter para ti visões de pronúncias fúteis e desencaminhantes.

_ם [Sâmeque]_

[[v25-2-15]]

^<<v25-2-15,15>>^ Por causa de ti bateram palmas todos os que passaram pela estrada.
Assobiaram e continuaram a menear a cabeça por causa da filha de Jerusalém, [dizendo:]
“É esta a cidade da qual se dizia: ‘Ela é a perfeição da lindeza, uma exultação para toda a terra’?”

_פ [Pê]^&#42;1^_

[[v25-2-16]]

^<<v25-2-16,16>>^ Todos os teus inimigos abriram a boca contra ti.
Assobiaram e continuaram a ranger os dentes. Disseram: “Nós [a]^&#42;1^ tragaremos.
Este é deveras o dia que esperávamos. Achamos! Vimos!”

[NOTE]
====
. “A”, LXXSy.
====

_ע [Aine]^&#42;1^_

[[v25-2-17]]

^<<v25-2-17,17>>^ Jeová fez o que intentou. Executou a sua declaração,
O que ordenara desde os dias de outrora. Derrubou e não teve compaixão.
E ele faz o inimigo alegrar-se por tua causa. Fez alto o chifre dos teus adversários.

_צ [Tsadê]_

[[v25-2-18]]

^<<v25-2-18,18>>^ O coração deles clamou a Jeová,^&#42;1^ ó muralha da filha de Sião.
Faze verter lágrimas qual torrente, dia e noite.
Não te entregues ao entorpecimento. Não fique quieta a menina^&#42;2^ de teu olho.

[NOTE]
====
. Veja v. 1 n.
. Lit.: “filha”.
====

_ק [Cofe]_

[[v25-2-19]]

^<<v25-2-19,19>>^ Levanta-te! Choraminga durante a noite, no começo das vigílias da madrugada.
Derrama teu coração qual água perante a face de Jeová.^&#42;1^
Levanta para ele as palmas das tuas mãos por causa da alma das tuas crianças,
Que se debilitam devido à fome na cabeceira de todas as ruas.

[NOTE]
====
. Veja v. 1 n.
====

_ר [Rexe]_

[[v25-2-20]]

^<<v25-2-20,20>>^ Vê, ó Jeová, e olha deveras para aquele a quem trataste severamente desta maneira.
Acaso devem as mulheres estar comendo os seus próprios frutos, as crianças que nascem plenamente formadas,
Ou devem ser mortos o sacerdote e o profeta no santuário de Jeová?^&#42;1^

[NOTE]
====
. Veja v. 1 n.
====

_ש [Chim]_

[[v25-2-21]]

^<<v25-2-21,21>>^ Rapaz e homem idoso deitaram-se na terra das ruas.
Minhas virgens e meus jovens caíram eles mesmos à espada.
Mataste no dia da tua ira. Abateste; não tiveste compaixão.

_ת [Tau]_

[[v25-2-22]]

^<<v25-2-22,22>>^ Como num dia de festividade passaste a convocar meus lugares de residência como forasteira em todo o redor.
E no dia da ira de Jeová não se mostrou haver nem fugitivo nem sobrevivente;
Os que eu produzi plenamente formados e criei, meu próprio inimigo exterminou.

'''

xref:025-lamentacoes/025-lamentacoes-001.adoc#v25-1-0[&#60; Capítulo Anterior] | <<v25-2-0,Topo>> | xref:025-lamentacoes/025-lamentacoes-003.adoc#v25-3-0[Próximo Capítulo &#62;]