include::./index.adoc[]

[[v25-1-0]]
=== Lamentações, 1
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

_א [Álefe]^&#42;1^_

[[v25-1-1]]

^<<v25-1-1,1>>^ ^&#42;1^ Como ela veio a ficar sentada sozinha, a cidade que abundava em povo!
Como ela se tornou igual a uma viúva, aquela que era populosa entre as nações!
Como veio a ficar para trabalho forçado aquela que era princesa entre os distritos jurisdicionais!

[NOTE]
====
. LXX apresenta a seguinte introdução: “E aconteceu que, depois de Israel ter sido levado cativo e Jerusalém ter sido desolada, Jeremias sentou-se chorando e lamentando com este lamento sobre Jerusalém, e disse.” Vgmss. têm a seguinte introdução: “E aconteceu que, depois de Israel ter sido levado ao cativeiro e Jerusalém ter ficado deserta, Jeremias, o profeta, estava sentado chorando e lamentou com este lamento sobre Jerusalém; e suspirando com espírito amargurado, e gemendo pesarosamente, ele disse.” T tem a seguinte introdução: “Jeremias, o profeta e grande sacerdote, disse.”
====

_ב [Bete]_

[[v25-1-2]]

^<<v25-1-2,2>>^ Ela chora muito durante a noite, e suas lágrimas estão sobre as suas faces.
Não tem ninguém que a console, dentre todos os seus amantes.
Todos os seus próprios companheiros agiram traiçoeiramente com ela. Tornaram-se inimigos dela.

_ג [Guímel]_

[[v25-1-3]]

^<<v25-1-3,3>>^ Judá foi para o exílio por causa da tribulação e por causa da abundância de servidão.
Ela mesma teve de morar entre as nações. Não encontrou nenhum lugar de descanso.
Todos os que a perseguiam^&#42;1^ a alcançaram em circunstâncias aflitivas.

[NOTE]
====
. Ou “acossavam”.
====

_ד [Dálete]_

[[v25-1-4]]

^<<v25-1-4,4>>^ Os caminhos de Sião são luto, porque não há quem venha à festividade.
Todos os seus portões foram desolados; seus sacerdotes estão suspirando.
Suas virgens estão pesarosas e ela mesma sente amargura.

_ה [Hê]_

[[v25-1-5]]

^<<v25-1-5,5>>^ Seus adversários tornaram-se a cabeça. Os que são seus inimigos estão despreocupados.
Porque o próprio Jeová causou-lhe pesar em vista da abundância das suas transgressões,
As próprias crianças dela têm andado cativas diante do adversário.

_ו [Vau]_

[[v25-1-6]]

^<<v25-1-6,6>>^ E da filha de Sião está saindo todo o seu esplendor.
Seus príncipes mostraram ser como veados que não acharam pasto;
E estão andando sem poder diante do perseguidor.^&#42;1^

[NOTE]
====
. Ou “acossador”.
====

_ז [Zaine]_

[[v25-1-7]]

^<<v25-1-7,7>>^ Jerusalém, [nos] dias da sua tribulação e das suas pessoas sem lar, lembrou-se de
Todas as suas coisas desejáveis que vieram a existir desde os dias de outrora.
Quando seu povo caiu na mão do adversário e ela não teve ajudador,
Viram-na os adversários. Riram-se de sua queda.

_ח [Hete]_

[[v25-1-8]]

^<<v25-1-8,8>>^ Jerusalém cometeu flagrante pecado. Por isso tornou-se meramente uma coisa abominável.
Todos os que a honravam trataram-na como algo ordinário, pois viram a sua nudez.
Ela mesma também está suspirando e vira as costas.

_ט [Tete]_

[[v25-1-9]]

^<<v25-1-9,9>>^ Sua impureza está nas suas saias. Ela não se lembrou do seu futuro,
E vai abaixo de maneira prodigiosa. Ela não tem consolador.
Ó Jeová, vê a minha tribulação, pois o inimigo assumiu ares de grandeza.

_י [Iode]_

[[v25-1-10]]

^<<v25-1-10,10>>^ O adversário estendeu a sua própria mão contra todas as coisas desejáveis que ela possuía.
Pois ela viu entrar no seu santuário nações
Acerca das quais ordenaste que não entrassem na congregação^&#42;1^ que pertence a ti.

[NOTE]
====
. “Na congregação.” Hebr.: vaq·qa·hál; gr.: ek·kle·sí·an; lat.: ec·clé·si·am.
====

_כ [Cafe]_

[[v25-1-11]]

^<<v25-1-11,11>>^ Todo o seu povo está suspirando; estão procurando pão.
Deram as suas coisas desejáveis em troca de algo para comer, a fim de reanimarem a alma.^&#42;1^
Vê, ó Jeová, e olha deveras, pois tornei-me qual mulher sem valor.^&#42;2^

[NOTE]
====
. “Alma.” Hebr.: ná·fesh; lat.: á·ni·mam. Veja Ap. 4A.
. A palavra hebr. para “sem valor” é fem. sing., como se uma mulher representando a cidade estivesse falando.
====

_ל [Lâmede]_

[[v25-1-12]]

^<<v25-1-12,12>>^ Não é isso nada para todos vós que estais passando pelo caminho? Olhai e vede.
Existe alguma dor igual à minha dor, que se me fez sentir agudamente,
Com que Jeová me causou pesar no dia de sua ira ardente?

_מ [Meme]_

[[v25-1-13]]

^<<v25-1-13,13>>^ Do alto ele enviou fogo aos meus ossos e subjuga a cada um.
Estendeu uma rede para os meus pés. Fez-me voltar atrás.
Fez de mim uma mulher desolada. Estou enferma o dia inteiro.

_נ [Nune]_

[[v25-1-14]]

^<<v25-1-14,14>>^ Ele se manteve alerta contra as minhas transgressões. Estão entrelaçadas entre si na sua mão.
Subiram ao meu pescoço. Meu poder tropeçou.
Jeová^&#42;1^ me entregou na mão daqueles contra os quais não me posso levantar.

[NOTE]
====
. Uma das 134 mudanças de YHWH para ’Adho·naí feitas pelos escribas. Veja Ap. 1B.
====

_ם [Sâmeque]_

[[v25-1-15]]

^<<v25-1-15,15>>^ Todos os meus poderosos, Jeová^&#42;1^ jogou fora do meu meio.
Convocou contra mim uma reunião para destroçar os meus jovens.
Jeová^&#42;2^ pisou o próprio lagar de vinho pertencente à virgem filha de Judá.

[NOTE]
====
. Veja v. 14 n.
. Veja v. 14 n.
====

_ע [Aine]_

[[v25-1-16]]

^<<v25-1-16,16>>^ Por causa destas coisas estou chorando como mulher.^&#42;1^ Meu olho, águas estão descendo do meu olho.
Pois longe de mim ficou o consolador, alguém para reanimar a minha alma.
Meus filhos tornaram-se os que foram desolados porque o inimigo assumiu ares de grandeza.

[NOTE]
====
. Veja v. 11 n.: “valor”.
====

_פ [Pê]_

[[v25-1-17]]

^<<v25-1-17,17>>^ Sião estendeu as suas mãos. Não tem consolador.
Jeová deu ordem a respeito de Jacó a todos os em volta dele como seus adversários.
Jerusalém tornou-se algo abominável entre eles.

_צ [Tsadê]_

[[v25-1-18]]

^<<v25-1-18,18>>^ Jeová é justo, pois foi contra a sua boca que me rebelei.
Escutai, pois, todos os povos, e vede a minha dor.
Minhas próprias virgens e meus próprios jovens foram para o cativeiro.

_ק [Cofe]_

[[v25-1-19]]

^<<v25-1-19,19>>^ Chamei os que me amavam intensamente. Eles mesmos é que me lograram.
Na cidade expiraram os meus próprios sacerdotes e os meus próprios homens idosos,
Enquanto tinham de procurar para si algo para comer, para reanimarem a sua alma.

_ר [Rexe]_

[[v25-1-20]]

^<<v25-1-20,20>>^ Vê, ó Jeová, pois estou num sério aperto. Meus próprios intestinos estão em fermento.
Meu coração se revolveu no meu íntimo, pois fui inteiramente rebelde.
Lá fora, a espada está privando de filhos. Dentro de casa é como a morte.

_ש [Chim]_

[[v25-1-21]]

^<<v25-1-21,21>>^ As pessoas ouviram^&#42;1^ como estou suspirando qual mulher. Não há consolador para mim.
Todos os meus inimigos é que ouviram [a notícia] da minha calamidade. Exultaram porque tu mesmo [a] causaste.
Certamente farás chegar o dia que proclamaste, para que se tornem iguais a mim.

[NOTE]
====
. “Eles ouviram”, MVg; T: “Nações ouviram”; LXX: “Ouvi, por favor”; Sy: “Ouve.”
====

_ת [Tau]_

[[v25-1-22]]

^<<v25-1-22,22>>^ Chegue perante ti toda a maldade deles, e trata-os com severidade,
Assim como me trataste severamente por causa de todas as minhas transgressões.
Porque muitos são os meus suspiros e meu coração está enfermo.

'''

xref:024-jeremias/024-jeremias-052.adoc#v24-52-0[&#60; Capítulo Anterior] | <<v25-1-0,Topo>> | xref:025-lamentacoes/025-lamentacoes-002.adoc#v25-2-0[Próximo Capítulo &#62;]