include::./index.adoc[]

[[v5-22-0]]
=== Deuteronômio, 22
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v5-22-1]]

^<<v5-22-1,1>>^ “Não deves ver o touro de teu irmão ou seu ovídeo extraviar-se e deliberadamente esquivar-te^&#42;1^ deles. Deves terminantemente conduzi-los de volta ao teu irmão.

[NOTE]
====
. Ou “esconder-te”.
====

[[v5-22-2]]

^<<v5-22-2,2>>^ E se teu irmão não estiver perto de ti e não o chegaste a conhecer, então tens de levá-lo para casa, para o meio da tua casa, e tem de ficar contigo até que teu irmão o busque. E tens de devolver-lho.

[[v5-22-3]]

^<<v5-22-3,3>>^ Assim farás também com o seu jumento e assim farás com a sua capa, e assim farás com qualquer coisa que teu irmão perdeu, que ele perdeu e que tu achaste. Não se te permitirá esquivar-te.

[[v5-22-4]]

^<<v5-22-4,4>>^ “Não deves ver o jumento de teu irmão ou seu touro cair na estrada e deliberadamente esquivar-te deles. Deves terminantemente ajudar-lhe a levantá-los.

[[v5-22-5]]

^<<v5-22-5,5>>^ “Não se deve pôr vestimenta de varão vigoroso em mulher, nem deve o varão vigoroso usar capa de mulher; porque todo aquele que faz tais coisas é algo detestável para Jeová, teu Deus.

[[v5-22-6]]

^<<v5-22-6,6>>^ “Caso haja um ninho de pássaro diante de ti no caminho, numa árvore ou no chão, com filhotes ou ovos, e a mãe estiver agachada sobre os filhotes ou sobre os ovos, não deves tomar a mãe junto com a ninhada.

[[v5-22-7]]

^<<v5-22-7,7>>^ Deves terminantemente mandar a mãe embora, mas podes tomar para ti a ninhada; a fim de que te vá bem e deveras prolongues os teus dias.

[[v5-22-8]]

^<<v5-22-8,8>>^ “Caso construas uma casa nova, tens de fazer também um parapeito para o teu terraço, a fim de que não ponhas culpa de sangue sobre a tua casa porque alguém caindo se precipite dela.

[[v5-22-9]]

^<<v5-22-9,9>>^ “Não deves semear teu vinhedo com duas espécies de semente, para não acontecer que os plenos produtos da semente que semeares e o produto do vinhedo sejam perdidos em proveito do santuário.^&#42;1^

[NOTE]
====
. “Sejam perdidos em proveito do santuário.” Lit.: “sejam santos”, isto é, venham a ser o quinhão do santuário. Hebr.: tiq·dásh.
====

[[v5-22-10]]

^<<v5-22-10,10>>^ “Não deves arar com junta de touro e de jumento.

[[v5-22-11]]

^<<v5-22-11,11>>^ “Não deves usar mescla de lã e de linho.

[[v5-22-12]]

^<<v5-22-12,12>>^ “Deves fazer para ti borlas nas quatro extremidades do teu vestuário com que te cobres.

[[v5-22-13]]

^<<v5-22-13,13>>^ “Caso um homem tome esposa e realmente tenha relações com ela, e venha a odiá-la,

[[v5-22-14]]

^<<v5-22-14,14>>^ e ele a tenha acusado de atos notórios e lhe tenha dado má fama, e tenha dito: ‘Esta é a mulher que tomei, e passei a chegar-me a ela e não achei nela evidência de virgindade’,

[[v5-22-15]]

^<<v5-22-15,15>>^ então o pai da moça e a mãe dela têm de tomar a evidência da virgindade da moça e apresentá-la aos anciãos da cidade, junto ao portão dela;

[[v5-22-16]]

^<<v5-22-16,16>>^ e o pai da moça tem de dizer aos anciãos: ‘Dei minha filha a este homem por esposa e ele passou a odiá-la.^&#42;1^

[NOTE]
====
. Ou “desprezá-la”.
====

[[v5-22-17]]

^<<v5-22-17,17>>^ E eis que a acusa de atos notórios, dizendo: “Não achei na tua filha evidência de virgindade.” Ora, esta é a evidência da virgindade de minha filha.’ E eles têm de estender a capa diante dos anciãos da cidade.

[[v5-22-18]]

^<<v5-22-18,18>>^ E os anciãos daquela cidade têm de tomar o homem e têm de discipliná-lo.

[[v5-22-19]]

^<<v5-22-19,19>>^ E têm de multá-lo em cem siclos de prata^&#42;1^ e dá-los ao pai da moça, porque deu má fama a uma virgem em Israel; e ela continuará a ser sua esposa. Não se lhe permitirá divorciar-se dela^&#42;2^ em todos os seus dias.

[NOTE]
====
. “Siclos de prata”, Vg; MSam: “moedas de prata”; LXX: “siclos”. Para saber o valor, veja Ap. 8A.
. Lit.: “mandá-la embora”.
====

[[v5-22-20]]

^<<v5-22-20,20>>^ “Se, porém, este assunto se provou verdadeiro, não se achando evidência de virgindade na moça,

[[v5-22-21]]

^<<v5-22-21,21>>^ então eles têm de levar a moça para fora, à entrada da casa de seu pai, e os homens da sua cidade têm de matá-la a pedradas e ela tem de morrer, porque cometeu uma ignominiosa insensatez em Israel, cometendo prostituição na casa de seu pai. Assim tens de eliminar o mal do teu meio.

[[v5-22-22]]

^<<v5-22-22,22>>^ “Caso um homem seja encontrado deitado com uma mulher que tenha^&#42;1^ dono, então ambos têm de morrer juntos, o homem que se deitou com a mulher e a mulher. Assim tens de eliminar o mal de Israel.

[NOTE]
====
. Lit.: “possuída por”, isto é, como esposa.
====

[[v5-22-23]]

^<<v5-22-23,23>>^ “Caso haja uma virgem, noiva dum homem, e um homem realmente a achou na cidade e se deitou com ela,

[[v5-22-24]]

^<<v5-22-24,24>>^ então tendes de levar ambos para fora ao portão daquela cidade e tendes de matá-los a pedradas, e eles têm de morrer, a moça, por não ter gritado na cidade, e o homem, por ter humilhado a esposa de seu próximo. Assim tens de eliminar o mal do teu meio.

[[v5-22-25]]

^<<v5-22-25,25>>^ “Se, porém, foi no campo que o homem achou a moça que era noiva, e o homem a agarrou e se deitou com ela, então só o homem que se deitou com ela tem de morrer

[[v5-22-26]]

^<<v5-22-26,26>>^ e não deves fazer nada à moça. A moça não tem pecado que mereça a morte, pois, assim como um homem se levanta contra seu próximo e deveras o assassina, sim, uma alma, assim é neste caso.

[[v5-22-27]]

^<<v5-22-27,27>>^ Porque foi no campo que a achou. A moça que era noiva gritou, mas não houve quem a socorresse.

[[v5-22-28]]

^<<v5-22-28,28>>^ “Caso um homem ache uma moça, uma virgem que não é noiva, e ele realmente a pegue e se deite com ela, e forem achados,

[[v5-22-29]]

^<<v5-22-29,29>>^ então o homem que se deitou com ela tem de dar cinqüenta siclos de prata^&#42;1^ ao pai da moça e ela se tornará sua esposa devido ao fato de que a humilhou. Não se lhe permitirá divorciar-se dela em todos os seus dias.^&#42;2^

[NOTE]
====
. “Siclos de prata”, Vg; M: “moedas de prata”; LXX: “didracmas de prata”.
. MSamLXX terminam aqui o capítulo 22.
====

[[v5-22-30]]

^<<v5-22-30,30>>^ “Nenhum homem deve tomar a esposa de seu pai, para não descobrir a aba [da veste] de seu pai.^&#42;1^

[NOTE]
====
. Ou “não se deitar com a esposa de seu pai”.
====

'''

xref:005-deuteronomio/005-deuteronomio-021.adoc#v5-21-0[&#60; Capítulo Anterior] | <<v5-22-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-023.adoc#v5-23-0[Próximo Capítulo &#62;]