include::./index.adoc[]

[[v5-21-0]]
=== Deuteronômio, 21
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v5-21-1]]

^<<v5-21-1,1>>^ “Caso se ache caído no campo alguém que foi morto no solo que Jeová,^&#42;1^ teu Deus, te dá para tomares posse dele, e não se ficou sabendo quem o golpeou fatalmente,

[NOTE]
====
. Veja Ap. 1C sec. 1.
====

[[v5-21-2]]

^<<v5-21-2,2>>^ então teus anciãos e teus juízes têm de sair e medir [a distância] até as cidades que há ao redor daquele que foi morto;

[[v5-21-3]]

^<<v5-21-3,3>>^ e tem de ser a cidade mais próxima daquele que foi morto. E os anciãos daquela cidade têm de tomar uma novilha da manada, com que não se trabalhou^&#42;1^ [ainda], que não puxou num jugo;

[NOTE]
====
. Possivelmente: “que não tenha sido cruzada (acasalada; fecundada)”; por meio duma correção. Veja VT, Vol. II, 1952, p. 356.
====

[[v5-21-4]]

^<<v5-21-4,4>>^ e os anciãos daquela cidade têm de conduzir a novilha para baixo a um vale de torrente em que corra água, no qual não se costumava lavrar ou semear, e ali, no vale da torrente, têm de quebrar a nuca da novilha.

[[v5-21-5]]

^<<v5-21-5,5>>^ “E têm de aproximar-se os sacerdotes, os filhos de Levi, porque são eles os que Jeová, teu Deus, escolheu para lhe ministrarem e para abençoarem em nome de Jeová, e por cuja boca se deve resolver toda disputa sobre todo ato de violência.^&#42;1^

[NOTE]
====
. Lit.: “toda disputa e todo ato de violência”. Esta é uma forma de hendíadis. Veja Gên 3:16 n.
====

[[v5-21-6]]

^<<v5-21-6,6>>^ Então todos os anciãos daquela cidade, mais próximos daquele que foi morto, devem lavar suas mãos por cima da novilha cuja nuca foi quebrada no vale da torrente;

[[v5-21-7]]

^<<v5-21-7,7>>^ e eles têm de responder e dizer: ‘Nossas mãos não derramaram este sangue, nem [o] viram nossos olhos [ser derramado].

[[v5-21-8]]

^<<v5-21-8,8>>^ Não o lances na conta do teu povo Israel, que remiste, ó Jeová,^&#42;1^ e não ponhas a culpa pelo sangue inocente no meio do teu povo Israel.’ E não se deve lançar na conta deles a culpa de sangue.

[NOTE]
====
. Veja Ap. 1C sec. 1.
====

[[v5-21-9]]

^<<v5-21-9,9>>^ E tu — tu eliminarás do teu meio a culpa pelo sangue inocente, porque farás o que é direito aos olhos de Jeová.

[[v5-21-10]]

^<<v5-21-10,10>>^ “Caso saias à batalha contra os teus inimigos e Jeová, teu Deus, os tenha entregado na tua mão e tu os tenhas levado cativos,

[[v5-21-11]]

^<<v5-21-11,11>>^ e tenhas visto entre os cativos uma mulher de figura bela, e te tenhas afeiçoado a ela e a tenhas tomado por tua esposa,

[[v5-21-12]]

^<<v5-21-12,12>>^ então tens de trazê-la para o meio da tua casa. Ela tem de rapar então sua cabeça e cuidar das suas unhas,

[[v5-21-13]]

^<<v5-21-13,13>>^ e tem de remover de si o manto do seu cativeiro e morar na tua casa, e tem de chorar seu pai e sua mãe por todo um mês lunar;^&#42;1^ e depois deves ter relações com ela, e tens de tomar posse dela como tua noiva, e ela tem de tornar-se tua esposa.

[NOTE]
====
. Lit.: “um mês lunar de dias”.
====

[[v5-21-14]]

^<<v5-21-14,14>>^ E tem de suceder que, se não te agradares dela, então tens de mandá-la embora, conforme agradar à própria alma dela;^&#42;1^ porém, de modo algum a deves vender por dinheiro. Não a deves tratar com tirania depois de a teres humilhado.

[NOTE]
====
. “Conforme agradar à própria alma dela”, M(hebr.: lenaf·sháh)SamSy. Ou “conforme agradar a ela; aonde ela quiser”. LXXVg: “livre”.
====

[[v5-21-15]]

^<<v5-21-15,15>>^ “Caso um homem venha a ter duas esposas, uma amada e a outra odiada, e elas, a amada e a odiada, lhe tiverem dado filhos, e o filho primogênito veio a ser o da odiada,

[[v5-21-16]]

^<<v5-21-16,16>>^ então tem de suceder que, no dia em que ele der aquilo que tiver como herança aos seus filhos, não se lhe permitirá constituir o filho da amada em primogênito às custas do filho da odiada, o primogênito.

[[v5-21-17]]

^<<v5-21-17,17>>^ Porque deve reconhecer como primogênito o filho da odiada, dando-lhe duas partes de tudo o que achou possuir, visto que este é o princípio da sua faculdade de procriação. O direito da primogenitura pertence a ele.

[[v5-21-18]]

^<<v5-21-18,18>>^ “Caso um homem tenha um filho obstinado e rebelde, que não escuta a voz de seu pai nem a voz de sua mãe, e eles o tenham corrigido, porém, ele não os queira escutar,

[[v5-21-19]]

^<<v5-21-19,19>>^ então seu pai e sua mãe têm de pegar nele e trazê-lo para fora aos anciãos da cidade dele e ao portão do seu lugar,

[[v5-21-20]]

^<<v5-21-20,20>>^ e têm de dizer aos anciãos da sua cidade: ‘Este filho nosso é obstinado e rebelde; não escuta a nossa voz, sendo glutão^&#42;1^ e beberrão.’

[NOTE]
====
. Ou “pródigo”.
====

[[v5-21-21]]

^<<v5-21-21,21>>^ Então todos os homens da sua cidade têm de atirar nele pedras e ele tem de morrer. Assim tens de eliminar o mal do teu meio, e todo o Israel ouvirá e deveras ficará com medo.

[[v5-21-22]]

^<<v5-21-22,22>>^ “E caso venha a haver num homem um pecado que mereça a sentença de morte, e ele tenha sido morto e tu o tenhas pendurado num madeiro,^&#42;1^

[NOTE]
====
. Lit.: “árvore”; ou: “lenho”.
====

[[v5-21-23]]

^<<v5-21-23,23>>^ seu cadáver não deve ficar toda a noite no madeiro; mas deves terminantemente enterrá-lo naquele dia, pois o pendurado é algo amaldiçoado^&#42;1^ por Deus; e não deves aviltar teu solo que Jeová, teu Deus, te dá por herança.

[NOTE]
====
. Lit.: “por causa duma maldição [em sentido concreto]”.
====

'''

xref:005-deuteronomio/005-deuteronomio-020.adoc#v5-20-0[&#60; Capítulo Anterior] | <<v5-21-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-022.adoc#v5-22-0[Próximo Capítulo &#62;]