include::./index.adoc[]

[[v5-10-0]]
=== Deuteronômio, 10
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v5-10-1]]

^<<v5-10-1,1>>^ “Naquele tempo específico, Jeová disse-me: ‘Lavra para ti duas tábuas de pedra iguais às primeiras e sobe a mim ao monte, e tens de fazer para ti uma arca de madeira.

[[v5-10-2]]

^<<v5-10-2,2>>^ E escreverei nas tábuas as palavras que apareceram nas primeiras tábuas que destroçaste, e tens de colocá-las na arca.’

[[v5-10-3]]

^<<v5-10-3,3>>^ Fiz assim uma arca de madeira de acácia e lavrei duas tábuas de pedra iguais às primeiras, e subi ao monte, e as duas tábuas estavam na minha mão.

[[v5-10-4]]

^<<v5-10-4,4>>^ Ele escreveu então nas tábuas a mesma escrita como nas primeiras, as Dez Palavras,^&#42;1^ que Jeová vos havia falado no monte do meio do fogo, no dia da congregação; depois Jeová mas deu.

[NOTE]
====
. “As Dez Palavras”, isto é, palavras de ordem, mandamentos. Hebr.: ‛asé·reth had·deva·rím; gr.: dé·ka ló·gous, “Decálogo”; lat.: vér·ba dé·cem. Veja 4:13 n.; Êx 34:28 n.: “Palavras”.
====

[[v5-10-5]]

^<<v5-10-5,5>>^ Virei-me então e desci do monte, e coloquei as tábuas na arca que eu tinha feito, para que continuassem nela, assim como Jeová me ordenara.

[[v5-10-6]]

^<<v5-10-6,6>>^ “E os filhos de Israel partiram de Beerote Bene-Jaacã para Moserá. Arão morreu ali e foi enterrado ali; e Eleazar, seu filho, começou a atuar como sacerdote em seu lugar.

[[v5-10-7]]

^<<v5-10-7,7>>^ Dali partiram para Gudegodá, e de Gudegodá para Jotbata, uma terra de vales de torrente em que corria água.

[[v5-10-8]]

^<<v5-10-8,8>>^ “Naquele tempo específico Jeová separou a tribo de Levi para carregar a arca do pacto de Jeová, para ficar de pé perante Jeová, a fim de lhe ministrar e para bendizer seu nome até o dia de hoje.

[[v5-10-9]]

^<<v5-10-9,9>>^ É por isso que Levi não veio a ter nem quinhão nem herança com os seus irmãos. Jeová é a sua herança, assim como Jeová, teu Deus, lhe dissera.

[[v5-10-10]]

^<<v5-10-10,10>>^ E eu — eu fiquei^&#42;1^ no monte assim como nos primeiros dias, quarenta dias e quarenta noites, e Jeová passou a escutar-me também essa vez. Jeová não te quis arruinar.

[NOTE]
====
. Lit.: “fiquei de pé”. Veja Êx 9:16 n.: “existência”.
====

[[v5-10-11]]

^<<v5-10-11,11>>^ Jeová me disse então: ‘Levanta-te, vai diante do povo, a fim de partirem, para que entrem e tomem posse da terra de que jurei aos seus antepassados que lhes havia de dar.’

[[v5-10-12]]

^<<v5-10-12,12>>^ “E agora, ó Israel, que é que Jeová, teu Deus, pede de ti senão que temas a Jeová, teu Deus, para andares em todos os seus caminhos e o amares, e para servires a Jeová, teu Deus, de todo o teu coração e de toda a tua alma;

[[v5-10-13]]

^<<v5-10-13,13>>^ que guardes os mandamentos de Jeová e seus estatutos que hoje te ordeno, para o teu bem?

[[v5-10-14]]

^<<v5-10-14,14>>^ Eis que a Jeová, teu Deus, pertencem os céus, sim, os céus dos céus, a terra e tudo o que nela há.

[[v5-10-15]]

^<<v5-10-15,15>>^ Somente de teus antepassados se afeiçoou Jeová, amando-os, de modo que escolheu sua descendência após eles, sim, a vós, dentre todos os povos, como no dia de hoje.

[[v5-10-16]]

^<<v5-10-16,16>>^ E tendes de circuncidar o prepúcio dos vossos corações e não deveis mais endurecer^&#42;1^ a vossa cerviz.

[NOTE]
====
. Ou “enrijecer”.
====

[[v5-10-17]]

^<<v5-10-17,17>>^ Pois, Jeová, vosso Deus, é o Deus dos deuses^&#42;1^ e o Senhor dos senhores,^&#42;2^ o Deus^&#42;3^ grande, poderoso e atemorizante, que não trata a ninguém com parcialidade, nem aceita suborno,^&#42;4^

[NOTE]
====
. “O Deus dos deuses.” Ou “Deus de deuses”. MSam(hebr.): ’Elo·héh ha·’elo·hím; gr.: The·ós ton the·ón; lat.: Dé·us de·ó·rum.
. “E o Senhor dos senhores.” Ou “e o Senhor de senhores”. Hebr.: wa·’Adho·néh (pl. para denotar excelência) ha·’adho·ním; gr.: Ký·ri·os ton ky·rí·on; lat.: Dó·mi·nus do·mi·nán·ti·um, “Senhor dos que dominam”.
. Ou “o [verdadeiro] Deus”. MSam(hebr.): ha·’Él; gr.: ho The·ós; lat.: Dé·us. Veja Ap. 1G.
. Ou “presente”.
====

[[v5-10-18]]

^<<v5-10-18,18>>^ executando julgamento pelo menino órfão de pai e pela viúva, e amando o residente forasteiro, de modo a dar-lhe pão e uma capa.

[[v5-10-19]]

^<<v5-10-19,19>>^ Também vós tendes de amar o residente forasteiro, pois vos tornastes residentes forasteiros na terra do Egito.

[[v5-10-20]]

^<<v5-10-20,20>>^ “Deves temer a Jeová, teu Deus. A ele é que deves servir e a ele te deves apegar, e pelo seu nome deves fazer declarações juramentadas.

[[v5-10-21]]

^<<v5-10-21,21>>^ É a ele que deves louvar^&#42;1^ e ele é o teu Deus, que fez contigo estas coisas grandes e atemorizantes que teus olhos viram.

[NOTE]
====
. Lit.: “Ele é teu louvor.”
====

[[v5-10-22]]

^<<v5-10-22,22>>^ Com setenta almas desceram os teus antepassados ao Egito, e agora, Jeová, teu Deus, te fez como as estrelas dos céus em multidão.

'''

xref:005-deuteronomio/005-deuteronomio-009.adoc#v5-9-0[&#60; Capítulo Anterior] | <<v5-10-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-011.adoc#v5-11-0[Próximo Capítulo &#62;]