include::./index.adoc[]

[[v5-11-0]]
=== Deuteronômio, 11
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v5-11-1]]

^<<v5-11-1,1>>^ “E tens de amar a Jeová, teu Deus, e cumprir a tua obrigação para com ele, e seus estatutos, e suas decisões judiciais, e seus mandamentos, para sempre.

[[v5-11-2]]

^<<v5-11-2,2>>^ E hoje sabeis muito bem (pois não [me dirijo] aos vossos filhos que não conheceram nem viram a disciplina de Jeová, vosso Deus, sua grandeza, sua mão forte e seu braço estendido,

[[v5-11-3]]

^<<v5-11-3,3>>^ nem seus sinais, nem seus atos que realizou no meio do Egito para com Faraó, rei do Egito, e para com toda a sua terra;

[[v5-11-4]]

^<<v5-11-4,4>>^ nem o que ele fez às forças militares do Egito, aos seus cavalos e aos seus carros de guerra, contra cujas faces fez transbordar as águas do Mar Vermelho quando vinham no encalço deles, e Jeová passou a destruí-los até o dia de hoje;

[[v5-11-5]]

^<<v5-11-5,5>>^ nem o que ele fez convosco no ermo, até que chegastes a este lugar;

[[v5-11-6]]

^<<v5-11-6,6>>^ nem o que fez a Datã e a Abirão, filhos de Eliabe, filho de Rubem, quando a terra abriu a sua boca e passou a tragar tanto a eles como os da sua casa e suas tendas, e toda a coisa existente que andava nas pisadas deles no meio de todo o Israel);

[[v5-11-7]]

^<<v5-11-7,7>>^ pois foram os vossos olhos que viram todos os grandes atos de Jeová, os quais ele realizou.

[[v5-11-8]]

^<<v5-11-8,8>>^ “E tendes de guardar o mandamento inteiro que hoje te ordeno, para que fiqueis fortes e deveras entreis e tomeis posse da terra à qual estais passando para tomar posse dela,

[[v5-11-9]]

^<<v5-11-9,9>>^ e para que prolongueis os vossos dias no solo de que Jeová jurou aos vossos antepassados que havia de dar a eles e à sua descendência, uma terra que mana leite e mel.

[[v5-11-10]]

^<<v5-11-10,10>>^ “Pois a terra à qual vais para tomar posse dela não é como a terra do Egito de que saístes, onde semeavas a tua semente e precisavas irrigar com o teu pé,^&#42;1^ como a uma horta de verduras.

[NOTE]
====
. Ou “precisavas regá-lo com o teu pé”, isto é, por alguma força fornecida pelos pés, quer impulsionando uma roda de água, quer por construir e abrir canais de água.
====

[[v5-11-11]]

^<<v5-11-11,11>>^ Mas a terra à qual passais para tomar posse dela é uma terra de montes e de vales planos. Ela bebe a água da chuva dos céus;

[[v5-11-12]]

^<<v5-11-12,12>>^ uma terra pela qual Jeová, teu Deus, está zelando. Os olhos de Jeová, teu Deus, estão continuamente sobre ela, do princípio do ano até o fim do ano.

[[v5-11-13]]

^<<v5-11-13,13>>^ “E terá de acontecer que, se impreterivelmente obedecerdes aos meus mandamentos que hoje vos ordeno, de modo a amardes a Jeová, vosso Deus, e o servirdes de todo o vosso coração e de toda a vossa alma,

[[v5-11-14]]

^<<v5-11-14,14>>^ então darei^&#42;1^ certamente chuva à vossa terra no seu tempo designado, a chuva outonal e a chuva primaveril,^&#42;2^ e deveras recolherás teus cereais, e teu vinho doce, e teu azeite.

[NOTE]
====
. “Darei”, MSy; SamLXXVgc: “dará”.
. Lit.: “chuva anterior (temporã) e chuva posterior (serôdia)”.
====

[[v5-11-15]]

^<<v5-11-15,15>>^ E darei certamente vegetação no teu campo para os teus animais domésticos, e deveras comerás e te fartarás.

[[v5-11-16]]

^<<v5-11-16,16>>^ Guardai-vos para não acontecer que o vosso coração seja engodado, e deveras vos desvieis e adoreis outros deuses, e deveras vos curveis diante deles,

[[v5-11-17]]

^<<v5-11-17,17>>^ e deveras se acenda a ira de Jeová contra vós e ele cerre os céus, de modo que não haja chuva e o solo não dê sua produção, e tenhais de perecer depressa da boa terra que Jeová vos dá.

[[v5-11-18]]

^<<v5-11-18,18>>^ “E estas minhas palavras tendes de fixar no vosso coração e na vossa alma, e atá-las como sinal sobre a vossa mão, e elas têm de servir de frontal entre os vossos olhos.

[[v5-11-19]]

^<<v5-11-19,19>>^ Também, tendes de ensiná-las aos vossos filhos, falando delas sentado na tua casa e andando pela estrada, e ao deitar-te e ao levantar-te.

[[v5-11-20]]

^<<v5-11-20,20>>^ E tens de escrevê-las sobre as ombreiras da tua casa e nos teus portões,

[[v5-11-21]]

^<<v5-11-21,21>>^ para que sejam muitos os vossos dias e os dias de vossos filhos sobre o solo de que Jeová jurou aos vossos antepassados que lhes havia de dar, como os dias dos céus sobre a terra.

[[v5-11-22]]

^<<v5-11-22,22>>^ “Pois, se guardardes estritamente todo este mandamento que vos ordeno, para o cumprir, amando a Jeová, vosso Deus, andando em todos os seus caminhos e apegando-vos a ele,

[[v5-11-23]]

^<<v5-11-23,23>>^ então Jeová terá de desalojar todas estas nações por vossa causa, e certamente desapossareis nações maiores e mais numerosas do que vós.

[[v5-11-24]]

^<<v5-11-24,24>>^ Todo lugar em que pisar a sola de vosso pé se tornará vosso. Desde o ermo até^&#42;1^ o Líbano, desde o Rio, o rio Eufrates, até o mar ocidental^&#42;2^ se tornará o vosso termo.

[NOTE]
====
. “Até.” Lit.: “e”, MSamLXXSyVg.
. Lit.: “atrás”, quer dizer, atrás da pessoa ao encarar o leste.
====

[[v5-11-25]]

^<<v5-11-25,25>>^ Nenhum homem se manterá firme contra vós. Jeová, vosso Deus, porá o pavor de vós e o temor de vós diante da face de toda a terra em que pisareis, assim como vos prometeu.

[[v5-11-26]]

^<<v5-11-26,26>>^ “Vede, ponho hoje diante de vós a bênção e a invocação do mal:

[[v5-11-27]]

^<<v5-11-27,27>>^ a bênção, se obedecerdes aos mandamentos de Jeová, vosso Deus, que hoje vos ordeno;

[[v5-11-28]]

^<<v5-11-28,28>>^ e a invocação do mal, se não obedecerdes aos mandamentos de Jeová, vosso Deus, e vos desviardes do caminho que hoje vos ordeno, de modo a andardes seguindo outros deuses que não conhecestes.

[[v5-11-29]]

^<<v5-11-29,29>>^ “E terá de acontecer que, quando Jeová, teu Deus, te introduzir na terra à qual vais para tomar posse dela, então terás de dar^&#42;1^ a bênção sobre o monte Gerizim e a invocação do mal sobre o monte Ebal.

[NOTE]
====
. Ou “proferir”.
====

[[v5-11-30]]

^<<v5-11-30,30>>^ Não estão eles do lado do Jordão que está na direção do pôr do sol, na terra dos cananeus que moram no Arabá, defronte de Gilgal, junto às árvores grandes de Moré?^&#42;1^

[NOTE]
====
. Sam acrescenta: “defronte de Siquém”.
====

[[v5-11-31]]

^<<v5-11-31,31>>^ Pois, estais passando o Jordão para entrar e tomar posse da terra que Jeová, vosso Deus, vos dá, e tendes de tomar posse dela e morar nela.

[[v5-11-32]]

^<<v5-11-32,32>>^ E tendes de cuidar em cumprir todos os regulamentos e as decisões judiciais que hoje ponho diante de vós.

'''

xref:005-deuteronomio/005-deuteronomio-010.adoc#v5-10-0[&#60; Capítulo Anterior] | <<v5-11-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-012.adoc#v5-12-0[Próximo Capítulo &#62;]