include::./index.adoc[]

[[v5-3-0]]
=== Deuteronômio, 3
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v5-3-1]]

^<<v5-3-1,1>>^ “Depois nos viramos e subimos pelo caminho de Basã. Em vista disso, saiu-nos ao encontro Ogue, rei de Basã, na batalha de Edrei.

[[v5-3-2]]

^<<v5-3-2,2>>^ Portanto, Jeová me disse: ‘Não tenhas medo dele, pois certamente entregarei na tua mão tanto ele como todo o seu povo e seu país; e tens de fazer-lhe assim como fizeste a Síon, rei dos amorreus, que morava em Hésbon.’

[[v5-3-3]]

^<<v5-3-3,3>>^ Concordemente, Jeová, nosso Deus, entregou-nos na mão também Ogue, rei de Basã, e todo o seu povo, e fomos golpeá-lo até que não lhe restou sobrevivente.

[[v5-3-4]]

^<<v5-3-4,4>>^ E naquele tempo específico fomos capturar todas as suas cidades. Mostrou-se não haver vila que não lhes tirássemos, sessenta cidades, toda a região de Argobe, o reino de Ogue em Basã.

[[v5-3-5]]

^<<v5-3-5,5>>^ Todas estas eram cidades fortificadas com muralha alta, portas e tranca, além de muitíssimas cidades campestres.

[[v5-3-6]]

^<<v5-3-6,6>>^ No entanto, devotamo-las à destruição, assim como fizéramos a Síon, rei de Hésbon, ao devotarmos cada cidade à destruição, homens, mulheres e criancinhas.

[[v5-3-7]]

^<<v5-3-7,7>>^ E todos os animais domésticos e o despojo das cidades tomamos para nós como saque.

[[v5-3-8]]

^<<v5-3-8,8>>^ “E naquele tempo específico passamos a tirar o país da mão dos dois reis dos amorreus que havia na região do Jordão, desde o vale da torrente do Árnon até o monte Hermom;

[[v5-3-9]]

^<<v5-3-9,9>>^ (os sidônios chamavam o Hermom de Sírion e os amorreus chamavam-no de Senir,)^&#42;1^

[NOTE]
====
. “Sírion . . . Senir.” Estes nomes aparecem nos textos ugaríticos encontrados em Ras Xamra, na Síria, e nos documentos procedentes de Bogazköy, Turquia.
====

[[v5-3-10]]

^<<v5-3-10,10>>^ todas as cidades do planalto e todo o Gileade, e todo o Basã, até Salecá e Edrei, as cidades do reino de Ogue em Basã.

[[v5-3-11]]

^<<v5-3-11,11>>^ Pois, somente Ogue, rei de Basã, restou daquilo que sobrou dos refains. Eis que seu esquife era um esquife de ferro.^&#42;1^ Não se acha ele em Rabá dos filhos de Amom? Nove côvados^&#42;2^ é seu comprimento e quatro côvados a sua largura, segundo o côvado de homem.

[NOTE]
====
. Ou “um sarcófago de basalto preto”. Os árabes ainda chamam o basalto de ferro.
. Um côvado equivalia a 44,5 cm.
====

[[v5-3-12]]

^<<v5-3-12,12>>^ E naquele tempo específico tomamos posse do país; desde Aroer, que está junto ao vale da torrente do Árnon, e^&#42;1^ metade da região montanhosa de Gileade e suas cidades dei aos rubenitas e aos gaditas.

[NOTE]
====
. “E”, MLXXSy; Vg: “até à”.
====

[[v5-3-13]]

^<<v5-3-13,13>>^ E o resto de Gileade e todo o Basã, do reino de Ogue, dei à meia tribo de Manassés. Não é toda a região de Argobe de todo o Basã chamada de terra dos refains?

[[v5-3-14]]

^<<v5-3-14,14>>^ “Jair, filho de Manassés, tomou toda a região de Argobe até o termo dos gesuritas e dos maacatitas, e passou a chamar essas aldeias de Basã^&#42;1^ pelo seu próprio nome, Havote-Jair,^&#42;2^ até o dia de hoje.

[NOTE]
====
. “Chamar essas aldeias de Basã.” Lit.: “chamá-las de Basã”.
. Significando “Aldeias de Tendas de Jair”.
====

[[v5-3-15]]

^<<v5-3-15,15>>^ E a Maquir dei Gileade.

[[v5-3-16]]

^<<v5-3-16,16>>^ E aos rubenitas e aos gaditas dei desde Gileade até o vale da torrente do Árnon, o meio do vale da torrente sendo o termo, e até o Jaboque, o vale da torrente que é o termo dos filhos de Amom;

[[v5-3-17]]

^<<v5-3-17,17>>^ e o Arabá,^&#42;1^ e o Jordão, e a região adjacente, desde Quinerete até o mar do Arabá, o Mar Salgado, ao sopé das encostas do Pisga, para o nascente.

[NOTE]
====
. Ou “as planícies desérticas”.
====

[[v5-3-18]]

^<<v5-3-18,18>>^ “Por isso vos ordenei naquele tempo específico, dizendo: ‘Jeová, vosso Deus, vos deu esta terra para tomardes posse dela. Atravessareis equipados diante dos vossos irmãos, os filhos de Israel, todos os homens valentes.^&#42;1^

[NOTE]
====
. Lit.: “os filhos de aptidão”.
====

[[v5-3-19]]

^<<v5-3-19,19>>^ Somente vossas esposas e vossos pequeninos, e vosso gado (bem sei que tendes muitíssimo gado) continuarão a morar nas vossas cidades que vos dei

[[v5-3-20]]

^<<v5-3-20,20>>^ até que Jeová dê descanso aos vossos irmãos, bem como a vós, e eles também tenham tomado posse da terra que Jeová, vosso Deus, lhes dá do outro lado do Jordão; depois tendes de voltar, cada um à sua posse que vos dei.’

[[v5-3-21]]

^<<v5-3-21,21>>^ “E naquele tempo específico ordenei a Josué, dizendo: ‘Teus olhos vêem tudo o que Jeová, vosso Deus, tem feito a estes dois reis. Jeová fará o mesmo com todos os reinos aos quais estás passando para lá.

[[v5-3-22]]

^<<v5-3-22,22>>^ Não deveis ter medo deles, pois Jeová, vosso Deus, é quem luta por vós.’

[[v5-3-23]]

^<<v5-3-23,23>>^ “E naquele tempo específico passei a implorar o favor de Jeová, dizendo:

[[v5-3-24]]

^<<v5-3-24,24>>^ ‘Ó Soberano Senhor Jeová, tu mesmo principiaste a fazer teu servo ver a tua grandeza e o teu braço forte, pois, que deus^&#42;1^ há nos céus ou na terra que faça atos iguais aos teus e realizações potentes iguais às tuas?

[NOTE]
====
. “Deus.” MSam(hebr.): ’el; gr.: the·ós; lat.: Dé·us.
====

[[v5-3-25]]

^<<v5-3-25,25>>^ Deixa-me atravessar, por favor, e ver a boa terra que está do outro lado do Jordão, esta boa região montanhosa e o Líbano.’

[[v5-3-26]]

^<<v5-3-26,26>>^ E Jeová continuou furioso^&#42;1^ comigo por vossa causa e não me escutou; mas Jeová me disse: ‘Já chega de ti! Nunca mais me fales neste assunto.

[NOTE]
====
. Ou “Jeová ficou furioso”.
====

[[v5-3-27]]

^<<v5-3-27,27>>^ Sobe ao cume do Pisga e levanta os teus olhos para o oeste, e para o norte, e para o sul, e para o leste, e vê com os teus olhos, pois não passarás este Jordão.

[[v5-3-28]]

^<<v5-3-28,28>>^ E comissiona Josué, e encoraja-o e fortifica-o, porque é ele quem atravessará diante deste povo e é ele quem os fará herdar a terra que verás.’

[[v5-3-29]]

^<<v5-3-29,29>>^ Tudo isso enquanto morávamos no vale defronte de Bete-Peor.

'''

xref:005-deuteronomio/005-deuteronomio-002.adoc#v5-2-0[&#60; Capítulo Anterior] | <<v5-3-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-004.adoc#v5-4-0[Próximo Capítulo &#62;]