include::./index.adoc[]

[[v5-8-0]]
=== Deuteronômio, 8
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v5-8-1]]

^<<v5-8-1,1>>^ “Deveis cuidar em guardar cada mandamento que hoje te ordeno, para que continueis a viver e deveras vos multipliqueis, e entreis e tomeis posse da terra que Jeová jurou aos vossos antepassados.

[[v5-8-2]]

^<<v5-8-2,2>>^ E tens de lembrar-te de todo o caminho que Jeová, teu Deus, te fez andar estes quarenta anos no ermo para te humilhar, para te pôr à prova, a fim de saber o que havia no teu coração, se guardarias ou não os seus mandamentos.

[[v5-8-3]]

^<<v5-8-3,3>>^ Por isso te humilhou e te deixou passar fome, e te alimentou com o maná que nem tu conhecias, nem teus pais conheciam; para que soubesses que o homem não vive somente de pão, mas que o homem vive de toda expressão da boca de Jeová.

[[v5-8-4]]

^<<v5-8-4,4>>^ Tua capa não se gastou sobre ti, nem inchou teu pé nestes quarenta anos.

[[v5-8-5]]

^<<v5-8-5,5>>^ E bem sabes no teu próprio coração que Jeová, teu Deus, te corrigia assim como um homem corrige seu filho.

[[v5-8-6]]

^<<v5-8-6,6>>^ “E tens de guardar os mandamentos de Jeová, teu Deus, andando nos seus caminhos e temendo-o.

[[v5-8-7]]

^<<v5-8-7,7>>^ Pois Jeová, teu Deus, te introduz numa terra boa, uma terra de vales de torrentes de água, de fontes e de águas de profundeza^&#42;1^ surgindo no vale plano e na região montanhosa,

[NOTE]
====
. “E de águas de profundeza (grandes quantidades de água).” Hebr.: u·theho·móth, pl., como no Sam.
====

[[v5-8-8]]

^<<v5-8-8,8>>^ uma terra de trigo e de cevada, e de videiras, e de figos, e de romãs, uma terra de azeitonas e de mel,

[[v5-8-9]]

^<<v5-8-9,9>>^ uma terra em que não comerás pão com escassez, em que não carecerás de nada, uma terra cujas pedras são ferro e de cujas montanhas extrairás o cobre.

[[v5-8-10]]

^<<v5-8-10,10>>^ “Quando tiveres comido e te tiveres fartado, então terás de bendizer a Jeová, teu Deus, pela boa terra que te deu.

[[v5-8-11]]

^<<v5-8-11,11>>^ Guarda-te para que não te esqueças de Jeová, teu Deus, de modo a não guardares seus mandamentos e suas decisões judiciais, e seus estatutos que hoje te ordeno,

[[v5-8-12]]

^<<v5-8-12,12>>^ para não acontecer que comas e deveras te fartes, e construas boas casas e deveras mores nelas,

[[v5-8-13]]

^<<v5-8-13,13>>^ e tua manada e teu rebanho aumentem, e acumules para ti prata e ouro, e aumente tudo o que for teu,

[[v5-8-14]]

^<<v5-8-14,14>>^ e teu coração deveras se enalteça e deveras te esqueças de Jeová, teu Deus, que te tirou da terra do Egito, da casa dos escravos,

[[v5-8-15]]

^<<v5-8-15,15>>^ que te fez andar através do grande e atemorizante ermo de serpentes venenosas^&#42;1^ e de escorpiões,^&#42;2^ e de terra sedenta sem água, que te fez sair água da rocha de pederneira,

[NOTE]
====
. Ou “ardentes; inflamatórias”. LXX: “picadoras; mordentes”; Vg: “de fôlego ardente (queimante)”.
. Lit.: “e lutador”. Hebr.: we‛aq·ráv; lat.: et scór·pi·o.
====

[[v5-8-16]]

^<<v5-8-16,16>>^ que te alimentou no ermo com maná que teus pais não conheceram, para te humilhar e para te pôr à prova, a fim de fazer-te o bem nos teus dias posteriores;

[[v5-8-17]]

^<<v5-8-17,17>>^ e digas no teu coração: ‘Meu próprio poder e a plena força da minha própria mão me produziram esta riqueza.’

[[v5-8-18]]

^<<v5-8-18,18>>^ E tens de lembrar-te de Jeová, teu Deus, porque é ele quem te dá o poder para produzir riqueza, a fim de cumprir seu pacto que jurou aos teus antepassados, como no dia de hoje.

[[v5-8-19]]

^<<v5-8-19,19>>^ “E tem de dar-se que, se é que te esqueceres de Jeová, teu Deus, e realmente andares seguindo outros deuses, e os servires e te curvares diante deles, deveras testifico hoje contra vós que definitivamente perecereis.

[[v5-8-20]]

^<<v5-8-20,20>>^ Perecereis como as nações que Jeová está destruindo de diante de vós, por não escutardes a voz de Jeová, vosso Deus.

'''

xref:005-deuteronomio/005-deuteronomio-007.adoc#v5-7-0[&#60; Capítulo Anterior] | <<v5-8-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-009.adoc#v5-9-0[Próximo Capítulo &#62;]