include::./index.adoc[]

[[v5-28-0]]
=== Deuteronômio, 28
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v5-28-1]]

^<<v5-28-1,1>>^ “E tem de suceder que, se sem falta escutares a voz de Jeová,^&#42;1^ teu Deus, cuidando em cumprir todos os seus mandamentos que hoje te ordeno, então Jeová,^&#42;2^ teu Deus, certamente te porá alto acima de todas as outras nações da terra.

[NOTE]
====
. Veja Ap. 1C sec. 1.
. Veja Ap. 1C sec. 1.
====

[[v5-28-2]]

^<<v5-28-2,2>>^ E todas estas bênçãos terão de vir sobre ti e terão de alcançar-te, por escutares a voz de Jeová, teu Deus:

[[v5-28-3]]

^<<v5-28-3,3>>^ “Bendito serás na cidade e bendito serás no campo.

[[v5-28-4]]

^<<v5-28-4,4>>^ “Bendito será o fruto do teu ventre, e o fruto do teu solo, e o fruto do teu animal doméstico, a cria do teu gado e a prole do teu rebanho.

[[v5-28-5]]

^<<v5-28-5,5>>^ “Bendito será teu cesto e tua amassadeira.

[[v5-28-6]]

^<<v5-28-6,6>>^ “Bendito serás quando entrares e bendito serás quando saíres.

[[v5-28-7]]

^<<v5-28-7,7>>^ “Jeová^&#42;1^ fará que sejam derrotados diante de ti os teus inimigos que se levantarem contra ti. Por um só caminho sairão contra ti, mas por sete caminhos fugirão diante de ti.

[NOTE]
====
. Veja Ap. 1C sec. 1.
====

[[v5-28-8]]

^<<v5-28-8,8>>^ Jeová^&#42;1^ decretará para ti a bênção sobre os teus depósitos de suprimentos e sobre todo empreendimento teu, e ele certamente te abençoará na terra que Jeová, teu Deus, te dá.

[NOTE]
====
. Veja Ap. 1C sec. 1.
====

[[v5-28-9]]

^<<v5-28-9,9>>^ Jeová te estabelecerá para si como povo santo, assim como te jurou, por continuares a guardar os mandamentos de Jeová,^&#42;1^ teu Deus, e teres andado nos seus caminhos.

[NOTE]
====
. Veja Ap. 1C sec. 1.
====

[[v5-28-10]]

^<<v5-28-10,10>>^ E todos os povos da terra terão de ver que o nome de Jeová foi invocado sobre ti e hão de ficar com medo de ti.

[[v5-28-11]]

^<<v5-28-11,11>>^ “Jeová deveras te fará também transbordar de prosperidade no fruto do teu ventre e no fruto dos teus animais domésticos, e nos frutos do teu solo, no solo de que Jeová jurou aos teus antepassados que to havia de dar.

[[v5-28-12]]

^<<v5-28-12,12>>^ Jeová te abrirá seu bom depósito, os céus, para dar chuva à tua terra na sua estação e para abençoar todo ato da tua mão; e certamente emprestarás a muitas nações, ao passo que tu mesmo não tomarás empréstimo.

[[v5-28-13]]

^<<v5-28-13,13>>^ E Jeová te porá deveras à cabeça e não na cauda; e terás de vir a estar somente em cima e não virás a estar embaixo, por estares obedecendo aos mandamentos de Jeová,^&#42;1^ teu Deus, que hoje te ordeno observar e cumprir.

[NOTE]
====
. Veja Ap. 1C sec. 1.
====

[[v5-28-14]]

^<<v5-28-14,14>>^ E não te deves desviar de todas as palavras que hoje vos ordeno, nem para a direita nem para a esquerda, a fim de andar seguindo outros deuses para os servires.

[[v5-28-15]]

^<<v5-28-15,15>>^ “E terá de suceder que, se não escutares a voz de Jeová, teu Deus, cuidando em cumprir todos os seus mandamentos e seus estatutos que hoje te ordeno, então terão de vir sobre ti todas estas invocações do mal e elas terão de alcançar-te:

[[v5-28-16]]

^<<v5-28-16,16>>^ “Maldito serás na cidade e maldito serás no campo.

[[v5-28-17]]

^<<v5-28-17,17>>^ “Maldito será teu cesto e tua amassadeira.

[[v5-28-18]]

^<<v5-28-18,18>>^ “Maldito será o fruto do teu ventre e os frutos do teu solo, a cria do teu gado e a prole do teu rebanho.

[[v5-28-19]]

^<<v5-28-19,19>>^ “Maldito serás quando entrares e maldito serás quando saíres.

[[v5-28-20]]

^<<v5-28-20,20>>^ “Jeová enviará sobre ti a maldição, a confusão e a reprimenda em todo empreendimento teu que tentares executar, até que tenhas sido aniquilado e tenhas perecido depressa, por causa da ruindade das tuas práticas por me teres abandonado.

[[v5-28-21]]

^<<v5-28-21,21>>^ Jeová fará que a peste se apegue a ti até que te tenha exterminado do solo para o qual vais a fim de tomar posse dele.

[[v5-28-22]]

^<<v5-28-22,22>>^ Jeová te golpeará com a tuberculose e com a febre ardente, e com a inflamação, e com o calor febril, e com a espada,^&#42;1^ e com o crestamento, e com o bolor, e certamente te perseguirão até que tenhas perecido.

[NOTE]
====
. “Espada”, MSy; com uma mudança dos sinais vocálicos: “secura; seca”; Vg: “calor”; LXXB omite isso.
====

[[v5-28-23]]

^<<v5-28-23,23>>^ Também teus céus por cima da tua cabeça têm de tornar-se em cobre e a terra debaixo de ti em ferro.

[[v5-28-24]]

^<<v5-28-24,24>>^ Jeová dará poeira e pó como chuva da tua terra. Descerá sobre ti desde os céus até que tenhas sido aniquilado.

[[v5-28-25]]

^<<v5-28-25,25>>^ Jeová fará que sejas derrotado diante dos teus inimigos. Por um só caminho sairás contra eles, mas por sete caminhos fugirás diante deles; e tens de tornar-te objeto de estremecimento para todos os reinos da terra.

[[v5-28-26]]

^<<v5-28-26,26>>^ E teu cadáver tem de tornar-se alimento para toda criatura voadora dos céus e para o animal do campo,^&#42;1^ sem que alguém [os] faça tremer.

[NOTE]
====
. Lit.: “terra”.
====

[[v5-28-27]]

^<<v5-28-27,27>>^ “Jeová te golpeará com o furúnculo do Egito, e com hemorróidas, e com eczema, e com erupção da pele, de que não poderás ser curado.

[[v5-28-28]]

^<<v5-28-28,28>>^ Jeová te golpeará com loucura, e com a perda da vista, e com desnorteamento do coração.

[[v5-28-29]]

^<<v5-28-29,29>>^ E tornar-te-ás deveras alguém que anda às apalpadelas ao meio-dia, assim como o cego anda às apalpadelas nas trevas, e não farás bem sucedidos os teus caminhos; e terás de tornar-te apenas alguém que é sempre defraudado e roubado, sem haver quem te salve.

[[v5-28-30]]

^<<v5-28-30,30>>^ Ficarás noivo duma mulher, mas outro homem a violentará. Construirás uma casa, mas não morarás nela. Plantarás um vinhedo, mas não começarás a desfrutá-lo.

[[v5-28-31]]

^<<v5-28-31,31>>^ Teu touro abatido ali diante de teus olhos — mas nada comerás dele. Teu jumento roubado diante de tua face — mas não voltará a ti. Tuas ovelhas dadas aos teus inimigos — mas não terás salvador.

[[v5-28-32]]

^<<v5-28-32,32>>^ Teus filhos e tuas filhas dados a outro povo, e teus olhos vendo isso e sempre estando saudosos deles — mas as tuas mãos^&#42;1^ estarão sem poder.

[NOTE]
====
. “Mãos”, Sy e 46 mss. hebr.; MSamLXXVg: “mão”.
====

[[v5-28-33]]

^<<v5-28-33,33>>^ Os frutos do teu solo e toda a tua produção serão comidos por um povo que não conheceste; e terás de tornar-te alguém que sempre é apenas defraudado e esmagado.

[[v5-28-34]]

^<<v5-28-34,34>>^ E certamente ficarás enlouquecido com o que vires com os teus olhos.

[[v5-28-35]]

^<<v5-28-35,35>>^ “Jeová te golpeará com um furúnculo maligno em ambos os joelhos e em ambas as pernas, de que não poderás ser curado, desde a sola do teu pé até o alto da tua cabeça.

[[v5-28-36]]

^<<v5-28-36,36>>^ Jeová fará que tu, bem como teu rei que constituirás sobre ti, marchem para uma nação que não conheceste, nem tu nem os teus antepassados; e ali hás de servir a outros deuses, de madeira e de pedra.

[[v5-28-37]]

^<<v5-28-37,37>>^ E terás de tornar-te um assombro, uma expressão proverbial e um escárnio para todos os povos aos quais Jeová te conduzirá.

[[v5-28-38]]

^<<v5-28-38,38>>^ “Levarás muita semente ao campo, mas pouco recolherás, porque o gafanhoto a devorará.

[[v5-28-39]]

^<<v5-28-39,39>>^ Plantarás e certamente cultivarás vinhedos, mas não beberás vinho e nada recolherás, porque o verme o consumirá.

[[v5-28-40]]

^<<v5-28-40,40>>^ Chegarás a ter oliveiras em todo o teu território, mas não te esfregarás com óleo, porque as tuas azeitonas cairão.

[[v5-28-41]]

^<<v5-28-41,41>>^ Gerarás filhos e filhas, mas não permanecerão teus, porque irão ao cativeiro.

[[v5-28-42]]

^<<v5-28-42,42>>^ Insetos zumbidores^&#42;1^ tomarão posse de todas as tuas árvores e dos frutos do teu solo.

[NOTE]
====
. Ou “exércitos estrepitosos”. LXXVg: “ferrugem”.
====

[[v5-28-43]]

^<<v5-28-43,43>>^ O residente forasteiro que está no teu meio se elevará cada vez mais sobre ti, ao passo que tu — tu descerás cada vez mais.

[[v5-28-44]]

^<<v5-28-44,44>>^ Será ele quem te fará empréstimo, ao passo que tu — tu não lhe farás empréstimo. Ele se tornará a cabeça, ao passo que tu — tu te tornarás a cauda.

[[v5-28-45]]

^<<v5-28-45,45>>^ “E todas estas invocações do mal virão certamente sobre ti e te perseguirão, e te alcançarão, até que tenhas sido aniquilado, porque não escutaste a voz de Jeová, teu Deus, guardando os seus mandamentos e os seus estatutos que te ordenou.

[[v5-28-46]]

^<<v5-28-46,46>>^ E têm de permanecer sobre ti e sobre a tua descendência como sinal e como portento por tempo indefinido,

[[v5-28-47]]

^<<v5-28-47,47>>^ devido ao fato de que não serviste a Jeová, teu Deus, com alegria e contentamento do coração^&#42;1^ pela abundância de tudo.

[NOTE]
====
. Ou “e contentamento”.
====

[[v5-28-48]]

^<<v5-28-48,48>>^ E terás de servir aos teus inimigos que Jeová enviará contra ti, com fome e sede, e nudez, e carência de tudo; e ele certamente porá um jugo de ferro sobre o teu pescoço até que te tenha aniquilado.

[[v5-28-49]]

^<<v5-28-49,49>>^ “Jeová levantará contra ti uma nação mui longínqua, desde os confins da terra, assim como a águia arremete, uma nação cuja língua não entenderás,

[[v5-28-50]]

^<<v5-28-50,50>>^ uma nação de semblante feroz, que não será parcial para com o velho, nem mostrará favor ao moço.

[[v5-28-51]]

^<<v5-28-51,51>>^ E certamente comerão o fruto dos teus animais domésticos e os frutos do teu solo, até que tenhas sido aniquilado, e não te deixarão sobrar nem cereais, nem vinho novo, nem azeite, nem a cria do teu gado, nem a prole do teu rebanho, até que te tenham destruído.

[[v5-28-52]]

^<<v5-28-52,52>>^ E deveras te sitiarão dentro de todos os teus portões até que se desmoronem as tuas muralhas altas e fortificadas em que confias, em toda a tua terra, sim, certamente te sitiarão dentro de todos os teus portões em toda a tua terra que Jeová, teu Deus, te deu.

[[v5-28-53]]

^<<v5-28-53,53>>^ Então terás de comer o fruto de teu ventre, a carne de teus filhos e de tuas filhas, os quais Jeová, teu Deus, te deu, por causa do cerco e do aperto com que teus inimigos te assediarão.

[[v5-28-54]]

^<<v5-28-54,54>>^ “Quanto ao homem mui delicado e mimoso no meio de ti, seu olho será mal-intencionado para com seu irmão, e para com sua querida esposa, e para com o resto dos seus filhos que lhe sobrarem,

[[v5-28-55]]

^<<v5-28-55,55>>^ de modo a não dar a nenhum deles da carne dos seus filhos que ele comerá, visto que não lhe sobra nada por causa do cerco e do aperto com que teu inimigo te assediará dentro de todos os teus portões.

[[v5-28-56]]

^<<v5-28-56,56>>^ Quanto à mulher delicada e mimosa no teu meio, que nunca tentou pôr a sola de seu pé na terra, por ser de hábito mimoso e por ser delicada, seu olho será mal-intencionado para com seu querido esposo, e para com seu filho e sua filha,

[[v5-28-57]]

^<<v5-28-57,57>>^ até mesmo para com as suas secundinas que saírem de entre as suas pernas, e para com os seus filhos que passou a dar à luz, visto que os comerá às escondidas pela carência de tudo, por causa do cerco e do aperto com que teu inimigo te assediará dentro dos teus portões.

[[v5-28-58]]

^<<v5-28-58,58>>^ “Se não cuidares em cumprir todas as palavras desta lei que se acham escritas neste livro, de modo a temeres este glorioso e atemorizante nome, sim, Jeová, teu Deus,

[[v5-28-59]]

^<<v5-28-59,59>>^ então Jeová há de fazer especialmente severas as tuas pragas e as pragas da tua descendência, pragas grandes e duradouras, e doenças malignas e duradouras.

[[v5-28-60]]

^<<v5-28-60,60>>^ E deveras trará de volta sobre ti todas as moléstias do Egito, diante das quais te amedrontaste, e elas certamente se apegarão a ti.

[[v5-28-61]]

^<<v5-28-61,61>>^ Também, qualquer doença e qualquer praga que não se achar escrita no livro desta lei, Jeová^&#42;1^ as fará vir sobre ti até que tenhas sido aniquilado.

[NOTE]
====
. Veja Ap. 1C sec. 1.
====

[[v5-28-62]]

^<<v5-28-62,62>>^ E deveras sereis deixados poucos em número, embora vos tornastes em multidão como as estrelas dos céus, por não teres escutado a voz de Jeová,^&#42;1^ teu Deus.

[NOTE]
====
. Veja Ap. 1C sec. 1.
====

[[v5-28-63]]

^<<v5-28-63,63>>^ “E tem de dar-se que, assim como Jeová exultou sobre vós para vos fazer bem e para vos multiplicar, assim Jeová exultará sobre vós para vos destruir e para vos aniquilar; e sereis simplesmente arrancados do solo ao qual vais para tomares posse dele.

[[v5-28-64]]

^<<v5-28-64,64>>^ “E Jeová^&#42;1^ certamente te espalhará entre todos os povos, de um confim da terra ao outro confim da terra, e lá terás de servir a outros deuses que não conheceste, nem tu nem os teus antepassados, madeira e pedra.

[NOTE]
====
. Veja Ap. 1C sec. 1.
====

[[v5-28-65]]

^<<v5-28-65,65>>^ E não terás repouso entre estas nações, nem se mostrará haver pouso para a sola de teu pé; e Jeová^&#42;1^ deveras te dará ali um coração tremente, e debilidade dos olhos, e desespero da alma.

[NOTE]
====
. Veja Ap. 1C sec. 1.
====

[[v5-28-66]]

^<<v5-28-66,66>>^ E certamente estarás no maior perigo da tua vida^&#42;1^ e ficarás apavorado noite e dia, e não estarás certo da tua vida.

[NOTE]
====
. Lit.: “E tua vida certamente ficará suspensa para ti sobre o caminho.”
====

[[v5-28-67]]

^<<v5-28-67,67>>^ De manhã dirás: ‘Tomara que fosse noitinha!’^&#42;1^ e à noitinha dirás: ‘Tomara que fosse manhã!’^&#42;2^ por causa do pavor do teu coração com que estarás apavorado e por causa do que verás com os teus olhos.

[NOTE]
====
. Lit.: “Quem dará noitinha?”
. Lit.: “Quem dará manhã?”
====

[[v5-28-68]]

^<<v5-28-68,68>>^ E Jeová certamente te levará de volta ao Egito, em navios, pelo caminho de que eu te disse: ‘Nunca mais o verás’, e tereis de vender-vos aos teus inimigos como escravos e servas, mas não haverá comprador.”

'''

xref:005-deuteronomio/005-deuteronomio-027.adoc#v5-27-0[&#60; Capítulo Anterior] | <<v5-28-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-029.adoc#v5-29-0[Próximo Capítulo &#62;]