include::./index.adoc[]

[[v5-13-0]]
=== Deuteronômio, 13
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v5-13-1]]

^<<v5-13-1,1>>^ “Caso se levante no teu meio um profeta ou um sonhador de sonho e ele te dê um sinal ou um portento,

[[v5-13-2]]

^<<v5-13-2,2>>^ e se cumpra o sinal ou o portento de que te falou, dizendo: ‘Andemos seguindo outros deuses, que não conheceste, e sirvamo-los’,

[[v5-13-3]]

^<<v5-13-3,3>>^ não deves escutar as palavras deste profeta ou o sonhador daquele sonho, porque Jeová, vosso Deus, vos está pondo à prova para saber se amais a Jeová, vosso Deus, de todo o vosso coração e de toda a vossa alma.

[[v5-13-4]]

^<<v5-13-4,4>>^ Deveis andar seguindo a Jeová, vosso Deus, e a ele deveis temer, e seus mandamentos deveis guardar, a sua voz deveis escutar, e a ele deveis servir, e a ele vos deveis apegar.

[[v5-13-5]]

^<<v5-13-5,5>>^ E aquele profeta ou aquele sonhador do sonho deve ser morto, porque falou em revolta contra Jeová, vosso Deus, que vos fez sair da terra do Egito e que te remiu da casa dos escravos, para te desviar do caminho em que Jeová, teu Deus, te mandou andar; e tens de eliminar o mal do teu meio.

[[v5-13-6]]

^<<v5-13-6,6>>^ “Caso teu irmão, filho de tua mãe, ou teu filho, ou tua filha, ou tua querida esposa,^&#42;1^ ou teu companheiro que é como a tua própria alma tente engodar-te às escondidas, dizendo: ‘Vamos e sirvamos a outros deuses’, que não conheceste, nem tu nem teus antepassados,

[NOTE]
====
. Lit.: “ou a esposa do teu seio”.
====

[[v5-13-7]]

^<<v5-13-7,7>>^ alguns dos deuses dos povos ao redor de vós, os que estão perto de ti e os que estão longe de ti, de uma extremidade do país à outra extremidade do país,

[[v5-13-8]]

^<<v5-13-8,8>>^ não deves aceder ao seu desejo, nem o deves escutar, nem deve teu olho ter dó dele, nem deves ter compaixão, nem deves encobri-lo [em proteção];

[[v5-13-9]]

^<<v5-13-9,9>>^ mas deves impreterivelmente matá-lo. Tua mão deve ser a primeira a vir sobre ele para o entregar à morte, e depois a mão de todo o povo.

[[v5-13-10]]

^<<v5-13-10,10>>^ E tens de matá-lo a pedradas e ele tem de morrer, visto que procurou desviar-te de Jeová, teu Deus, que te fez sair da terra do Egito, da casa dos escravos.

[[v5-13-11]]

^<<v5-13-11,11>>^ Então todo o Israel ouvirá e ficará com medo, e não mais farão algo semelhante a esta coisa má no teu meio.

[[v5-13-12]]

^<<v5-13-12,12>>^ “Caso ouças dizer numa das tuas cidades que Jeová, teu Deus, te dá para ali morares:

[[v5-13-13]]

^<<v5-13-13,13>>^ ‘Homens imprestáveis^&#42;1^ saíram do teu meio para tentar desviar os habitantes da sua cidade, dizendo: “Vamos e sirvamos a outros deuses”, que não conheceste’,

[NOTE]
====
. Lit.: “Homens, filhos de belial (inutilidade).”
====

[[v5-13-14]]

^<<v5-13-14,14>>^ então tens de pesquisar, e investigar, e indagar cabalmente; e se a coisa fica estabelecida como verdadeira, tal coisa detestável foi feita no teu meio,

[[v5-13-15]]

^<<v5-13-15,15>>^ deves impreterivelmente golpear os habitantes daquela cidade com o fio da espada. Devota à destruição pelo fio da espada tanto a ela como a tudo o que houver nela, bem como seus animais domésticos.

[[v5-13-16]]

^<<v5-13-16,16>>^ E deves reunir todo o seu despojo no meio da sua praça pública e tens de queimar no fogo tanto a cidade como todo o seu despojo, como oferta inteira a Jeová, teu Deus, e ela tem de tornar-se um monte de ruínas por tempo indefinido. Nunca mais deve ser reconstruída.

[[v5-13-17]]

^<<v5-13-17,17>>^ E absolutamente nada da coisa feita sagrada pela proscrição^&#42;1^ deve ficar apegado à tua mão, para que Jeová se desvie da sua ira ardente e deveras te dê misericórdia, e certamente tenha misericórdia de ti e te multiplique, assim como jurou aos teus antepassados.

[NOTE]
====
. “Da coisa feita sagrada pela proscrição.” Hebr.: ha·hhé·rem; gr.: tou a·na·thé·ma·tos, “a coisa tornada amaldiçoada”. Veja Gál 1:8 n.
====

[[v5-13-18]]

^<<v5-13-18,18>>^ Pois, deves escutar a voz de Jeová, teu Deus, guardando todos os seus mandamentos que hoje te ordeno, para fazer o que é direito aos olhos de Jeová, teu Deus.

'''

xref:005-deuteronomio/005-deuteronomio-012.adoc#v5-12-0[&#60; Capítulo Anterior] | <<v5-13-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-014.adoc#v5-14-0[Próximo Capítulo &#62;]