include::./index.adoc[]

[[v34-3-0]]
=== Naum, 3
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v34-3-1]]

^<<v34-3-1,1>>^ Ai da cidade de derramamento de sangue.^&#42;1^ Ela está cheia de impostura [e] de roubo. A presa não se afasta!

[NOTE]
====
. Lit.: “sangues”.
====

[[v34-3-2]]

^<<v34-3-2,2>>^ Há o som do chicote e o ruído do sacolejo da roda, e o cavalo galopante e o carro saltante.

[[v34-3-3]]

^<<v34-3-3,3>>^ O cavaleiro montado, e a chama da espada, e o raio da lança, e a multidão dos que foram mortos, e a massa pesada de cadáveres; e não há fim de corpos mortos. Estão tropeçando entre os seus corpos mortos;

[[v34-3-4]]

^<<v34-3-4,4>>^ devido à abundância das prostituições da prostituta, atraente com encanto, senhora de feitiçarias, que enlaça nações com as suas prostituições e famílias com as suas feitiçarias.

[[v34-3-5]]

^<<v34-3-5,5>>^ “Eis que sou contra ti”,^&#42;1^ é a pronunciação de Jeová dos exércitos,^&#42;2^ “e vou pôr a cobertura das tuas saias sobre a tua face e vou fazer as nações ver a tua nudez, e os reinos a tua desonra.

[NOTE]
====
. “Ti”, hebr. fem. sing., referindo-se a Nínive.
. “Jeová dos exércitos”, MTVg; LXX: “Jeová Deus, o Todo-poderoso.”
====

[[v34-3-6]]

^<<v34-3-6,6>>^ E vou lançar sobre ti coisas repugnantes e vou fazer-te desprezível; e vou pôr-te por espetáculo.

[[v34-3-7]]

^<<v34-3-7,7>>^ E terá de acontecer que todo aquele que te vir fugirá de ti e certamente dirá: ‘Nínive foi assolada! Quem se compadecerá dela?’ Onde procurarei consoladores para ti?

[[v34-3-8]]

^<<v34-3-8,8>>^ És tu melhor do que Nô-Amom, assentada junto aos canais do Nilo? Havia águas ao redor dela, cuja riqueza era [o] mar, cuja muralha era do mar.

[[v34-3-9]]

^<<v34-3-9,9>>^ A Etiópia^&#42;1^ era a sua plena força, também o Egito; e isso sem limite. Pute e os próprios líbios^&#42;2^ mostraram-se de auxílio para ti.^&#42;3^

[NOTE]
====
. “Etiópia”, LXXVg; MTSy: “Cus”.
. “E os . . . líbios.” Hebr.: weLu·vím.
. “Ti”, MTVg; LXX: “ela”.
====

[[v34-3-10]]

^<<v34-3-10,10>>^ Também ela se destinava ao exílio; ela foi ao cativeiro. Também as suas próprias crianças foram despedaçadas à cabeceira de todas as ruas; e lançaram-se sortes sobre os seus homens glorificados e todos os seus grandes foram presos com grilhões.

[[v34-3-11]]

^<<v34-3-11,11>>^ “Tu mesma também ficarás embriagada; tornar-te-ás algo oculto. Tu mesma também procurarás do inimigo um baluarte.

[[v34-3-12]]

^<<v34-3-12,12>>^ Todas as tuas praças fortes são como figueiras com os primeiros frutos maduros, que, quando sacudidos, certamente cairão na boca de quem come.

[[v34-3-13]]

^<<v34-3-13,13>>^ “Eis que teu povo são mulheres no teu meio. Sem falta terão de abrir-se os portões da tua terra aos teus inimigos. O fogo há de devorar as tuas trancas.

[[v34-3-14]]

^<<v34-3-14,14>>^ Puxa para ti água para o sítio. Fortifica as tuas praças fortes. Entra na lama e pisa no barro; agarra [a] forma para tijolos.

[[v34-3-15]]

^<<v34-3-15,15>>^ Até mesmo ali te devorará o fogo. A espada te decepará. Devorar-te-á como certa espécie de gafanhoto.^&#42;1^ Faze-te pesada em número como certa espécie de gafanhoto; faze-te pesada em número como o gafanhoto.^&#42;2^

[NOTE]
====
. Ou “como a larva de gafanhoto”. Hebr.: kai·yá·leq. Veja Jl 1:4 n.
. Ou “como a multidão de gafanhotos”. Hebr.: ka·’ar·béh, o gafanhoto migratório, ou do deserto, no estágio plenamente desenvolvido, já com asas.
====

[[v34-3-16]]

^<<v34-3-16,16>>^ Multiplicaste os teus negociantes mais do que as estrelas dos céus.
“Quanto a certa espécie de gafanhoto,^&#42;1^ realmente despe-se da sua pele; então sai voando.

[NOTE]
====
. “Certa espécie de gafanhoto.” Ou “larva de gafanhoto”.
====

[[v34-3-17]]

^<<v34-3-17,17>>^ Teus vigilantes são como o gafanhoto^&#42;1^ e teus oficiais de recrutamento como o enxame de gafanhotos.^&#42;2^ Acampam-se nos redis de pedra num dia de frio. Basta o sol raiar e lá se vão voando; e realmente é desconhecido seu lugar em que estão.

[NOTE]
====
. Veja v. 15 n.: “como o gafanhoto”.
. “Como o enxame de gafanhotos.” Hebr.: keghóhv go·vaí, usado coletivamente; chamado assim por causa de seu enxamear.
====

[[v34-3-18]]

^<<v34-3-18,18>>^ “Teus pastores ficaram sonolentos, ó rei da Assíria; teus majestosos ficam nas suas residências. Teu povo foi espalhado sobre os montes e não há quem [o] reúna.

[[v34-3-19]]

^<<v34-3-19,19>>^ Não há alívio da tua catástrofe. Teu golpe ficou incurável. Todos os que ouvem as notícias a teu respeito hão de bater palmas sobre ti; pois, sobre quem foi que a tua maldade não passava constantemente?”

'''

xref:034-naum/034-naum-002.adoc#v34-2-0[&#60; Capítulo Anterior] | <<v34-3-0,Topo>> | xref:035-habacuque/035-habacuque-001.adoc#v35-1-0[Próximo Capítulo &#62;]