include::./index.adoc[]

[[v48-5-0]]
=== Gálatas, 5
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v48-5-1]]

^<<v48-5-1,1>>^ Para tal liberdade^&#42;1^ [é que] Cristo nos libertou. Portanto, ficai firmes e não vos deixeis restringir novamente num jugo de escravidão.

[NOTE]
====
. Ou: “Com a liberdade dela.” Gr.: Tei e·leu·the·rí·ai.
====

[[v48-5-2]]

^<<v48-5-2,2>>^ Eis que eu, Paulo, vos digo que, se fordes circuncidados, Cristo não será de nenhum proveito para vós.

[[v48-5-3]]

^<<v48-5-3,3>>^ Além disso, dou novamente testemunho a todo homem que se deixa circuncidar, que ele está sob a obrigação de cumprir toda a Lei.

[[v48-5-4]]

^<<v48-5-4,4>>^ Estais apartados de Cristo, quem quer que sejais que tenteis ser declarados justos por meio de lei; decaístes da sua benignidade imerecida.

[[v48-5-5]]

^<<v48-5-5,5>>^ Nós, por espírito, aguardamos ansiosamente a justiça esperada^&#42;1^ em resultado da fé.

[NOTE]
====
. Lit.: “esperança da justiça”.
====

[[v48-5-6]]

^<<v48-5-6,6>>^ Pois, quanto a Cristo Jesus,^&#42;1^ nem a circuncisão nem a incircuncisão é de qualquer valor, mas a fé que opera por intermédio do amor [é].

[NOTE]
====
. “Jesus.” B omite isso.
====

[[v48-5-7]]

^<<v48-5-7,7>>^ Corríeis bem. Quem vos impediu de persistirdes em obedecer à verdade?

[[v48-5-8]]

^<<v48-5-8,8>>^ Esta sorte de persuasão não vem Daquele que vos chama.

[[v48-5-9]]

^<<v48-5-9,9>>^ Um pouco de fermento leveda a massa toda.

[[v48-5-10]]

^<<v48-5-10,10>>^ Estou confiante, quanto a vós os que estais em união com [o] Senhor,^&#42;1^ de que não chegareis a pensar de outro modo; mas aquele que vos causa dificuldades levará o [seu] julgamento, não importa quem seja.

[NOTE]
====
. “Confio em Jeová quanto a vós”, J7,8.
====

[[v48-5-11]]

^<<v48-5-11,11>>^ Quanto a mim, irmãos, se eu ainda pregasse a circuncisão, por que estaria ainda sendo perseguido? Então, deveras, a pedra de tropeço^&#42;1^ da estaca de tortura^&#42;2^ foi abolida.

[NOTE]
====
. Ou “a ofensa”. Lit.: “o motivo (a causa) da queda”. Gr.: to skán·da·lon; lat.: scán·da·lum.
. Veja Ap. 5C.
====

[[v48-5-12]]

^<<v48-5-12,12>>^ Quisera eu que os homens que estão tentando subverter-vos ficassem eles mesmos emasculados.^&#42;1^

[NOTE]
====
. “Ficassem eles mesmos emasculados”, P46אABD; J7,8: “fossem decepados diante dos olhos de Jeová”.
====

[[v48-5-13]]

^<<v48-5-13,13>>^ Fostes, naturalmente, chamados à liberdade, irmãos; apenas não useis esta liberdade como induzimento para a carne, mas, por intermédio do amor, trabalhai como escravos uns para os outros.

[[v48-5-14]]

^<<v48-5-14,14>>^ Pois a Lei inteira está cumprida numa só expressão, a saber: “Tens de^&#42;1^ amar o teu próximo como a ti mesmo.”

[NOTE]
====
. Ou: “Deves.”
====

[[v48-5-15]]

^<<v48-5-15,15>>^ Se vós, porém, persistis em morder-vos e em devorar-vos uns aos outros, acautelai-vos de que não fiqueis aniquilados uns pelos outros.

[[v48-5-16]]

^<<v48-5-16,16>>^ Mas eu digo: Persisti em andar por espírito, e não executareis nenhum desejo carnal.

[[v48-5-17]]

^<<v48-5-17,17>>^ Pois a carne é contra o espírito no seu desejo, e o espírito contra a carne; porque estes estão opostos um ao outro, de modo que as próprias coisas que gostaríeis de fazer, não fazeis.

[[v48-5-18]]

^<<v48-5-18,18>>^ Ademais, se estais sendo conduzidos por espírito, não estais debaixo de lei.

[[v48-5-19]]

^<<v48-5-19,19>>^ Ora, as obras da carne são manifestas, as quais são fornicação,^&#42;1^ impureza,^&#42;2^ conduta desenfreada,^&#42;3^

[NOTE]
====
. Veja Ap. 5A.
. Ou “imundícia; depravação; lascívia”. Gr.: a·ka·thar·sí·a; J17,22(hebr.): tum·’áh. Veja Ez 22:15 n.: “impureza”.
. Ou “licenciosidade; libertinagem; impudicícia”. Gr.: a·sél·gei·a; Vgc(lat.): im·pu·di·cí·ti·a; J18,22(hebr.): zim·máh. Veja Pr 10:23 n.: “desenfreada”.
====

[[v48-5-20]]

^<<v48-5-20,20>>^ idolatria, prática de espiritismo,^&#42;1^ inimizades, rixa, ciúme, acessos de ira, contendas, divisões, seitas,^&#42;2^

[NOTE]
====
. Ou “drogaria; drogueamento”. Gr.: far·ma·kí·a. Veja Re 21:8 n.: “espiritismo”.
. “Seitas.” Gr.: hai·ré·seis; lat.: séc·tae.
====

[[v48-5-21]]

^<<v48-5-21,21>>^ invejas, bebedeiras, festanças e coisas semelhantes a estas. Quanto a tais coisas, aviso-vos de antemão, do mesmo modo como já vos avisei de antemão, de que os que praticam tais coisas não herdarão o reino de Deus.

[[v48-5-22]]

^<<v48-5-22,22>>^ Por outro lado, os frutos do espírito são amor, alegria, paz, longanimidade, benignidade, bondade, fé,

[[v48-5-23]]

^<<v48-5-23,23>>^ brandura, autodomínio. Contra tais coisas não há lei.

[[v48-5-24]]

^<<v48-5-24,24>>^ Além disso, os que pertencem a Cristo Jesus pregaram na estaca^&#42;1^ a carne com as suas paixões e desejos.

[NOTE]
====
. Ou “fixaram numa estaca (poste)”. Veja Ap. 5C.
====

[[v48-5-25]]

^<<v48-5-25,25>>^ Se estamos vivendo por espírito, continuemos também a andar ordeiramente por espírito.

[[v48-5-26]]

^<<v48-5-26,26>>^ Não fiquemos egotistas, atiçando competição entre uns e outros,^&#42;1^ invejando-nos uns aos outros.

[NOTE]
====
. Ou “compelindo uns aos outros a uma confrontação”.
====

'''

xref:048-galatas/048-galatas-004.adoc#v48-4-0[&#60; Capítulo Anterior] | <<v48-5-0,Topo>> | xref:048-galatas/048-galatas-006.adoc#v48-6-0[Próximo Capítulo &#62;]