include::./index.adoc[]

[[v48-2-0]]
=== Gálatas, 2
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v48-2-1]]

^<<v48-2-1,1>>^ Daí, quatorze anos depois, subi novamente a Jerusalém, com Barnabé, tomando também comigo a Tito.

[[v48-2-2]]

^<<v48-2-2,2>>^ Mas, subi em resultado duma revelação. E eu lhes expus as boas novas que estou pregando^&#42;1^ entre as nações, em particular, porém, perante os que eram homens de destaque, com receio de que de algum modo eu estivesse correndo ou tivesse corrido em vão.

[NOTE]
====
. Ou “estou proclamando”. Gr.: ke·rýs·so; lat.: praé·di·co. Veja Da 5:29 n.: “proclamaram”.
====

[[v48-2-3]]

^<<v48-2-3,3>>^ Não obstante, nem mesmo Tito, que estava comigo, foi compelido a ser circuncidado, embora fosse grego.

[[v48-2-4]]

^<<v48-2-4,4>>^ Mas, por causa dos falsos irmãos, introduzidos quietamente, que entraram furtivamente para espreitar a nossa liberdade, que temos em união com Cristo Jesus, a fim de que nos escravizassem completamente —

[[v48-2-5]]

^<<v48-2-5,5>>^ a estes não cedemos no sentido de nos submetermos, não, nem por uma hora, para que a verdade das boas novas continuasse convosco.

[[v48-2-6]]

^<<v48-2-6,6>>^ Mas, da parte dos que pareciam ser alguma coisa — que sorte de homens eles eram anteriormente não faz diferença para mim — Deus^&#42;1^ não vai pela aparência externa dum homem — a mim, de fato, estes homens de destaque não transmitiram nada de novo.

[NOTE]
====
. “Deus”, P46אABCD; J7,8: “Jeová”.
====

[[v48-2-7]]

^<<v48-2-7,7>>^ Mas, ao contrário, quando viram que eu tinha sido incumbido das boas novas para com os incircuncisos,^&#42;1^ assim como Pedro [tinha sido] para com os circuncisos^&#42;2^ —

[NOTE]
====
. Lit.: “da incircuncisão”.
. Lit.: “da circuncisão”.
====

[[v48-2-8]]

^<<v48-2-8,8>>^ pois, Aquele que deu a Pedro os poderes necessários a um apostolado para com os circuncisos, deu também a mim poderes para com os que são das nações;

[[v48-2-9]]

^<<v48-2-9,9>>^ sim, quando ficaram sabendo da benignidade imerecida que me tinha sido concedida, Tiago, e Cefas, e João, os que pareciam ser colunas, deram a mim e a Barnabé a mão direita da parceria, para que fôssemos às nações, mas eles aos circuncisos.

[[v48-2-10]]

^<<v48-2-10,10>>^ Apenas devíamos lembrar-nos dos pobres. Esta mesma coisa diligenciei também fazer.

[[v48-2-11]]

^<<v48-2-11,11>>^ No entanto, quando Cefas veio a Antioquia, resisti-lhe^&#42;1^ face a face, porque se tornara condenado.

[NOTE]
====
. Lit.: “ergui-me contra ele”.
====

[[v48-2-12]]

^<<v48-2-12,12>>^ Pois, antes da chegada de certos homens da parte de Tiago, ele costumava comer com pessoas das nações; mas, ao chegarem, passou a retirar-se e a separar-se, temendo os da classe circuncisa.^&#42;1^

[NOTE]
====
. Lit.: “os da circuncisão”.
====

[[v48-2-13]]

^<<v48-2-13,13>>^ Também os demais judeus juntaram-se a ele neste fingimento, de modo que até mesmo Barnabé se deixou levar por eles no seu fingimento.^&#42;1^

[NOTE]
====
. Lit.: “na sua hipocrisia”. Gr.: hy·po·krí·sei.
====

[[v48-2-14]]

^<<v48-2-14,14>>^ Quando vi, porém, que não estavam andando direito segundo a verdade das boas novas, eu disse a Cefas na frente de todos eles: “Se tu, embora sejas judeu, vives como as nações e não como os judeus, como é que compeles as pessoas das nações a viver segundo as práticas judaicas?”

[[v48-2-15]]

^<<v48-2-15,15>>^ Nós, os que somos judeus por natureza e não pecadores das nações,

[[v48-2-16]]

^<<v48-2-16,16>>^ bem sabendo que o homem é declarado justo,^&#42;1^ não devido a obras da lei, mas apenas por intermédio da fé para com Cristo Jesus, sim, nós temos depositado a nossa fé em Cristo Jesus, para sermos declarados justos devido à fé para com Cristo e não devido a obras da lei, porque nenhuma carne será declarada justa devido a obras da lei.

[NOTE]
====
. Lit.: “é justificado”. Gr.: di·kai·oú·tai.
====

[[v48-2-17]]

^<<v48-2-17,17>>^ Ora, ao buscarmos ser declarados justos por meio de Cristo, se nós mesmos formos também achados pecadores, é Cristo na realidade ministro do pecado? Que isso nunca aconteça!

[[v48-2-18]]

^<<v48-2-18,18>>^ Pois, se eu estiver edificando novamente as próprias coisas que uma vez derrubei, demonstro ser transgressor.

[[v48-2-19]]

^<<v48-2-19,19>>^ Quanto a mim, morri por intermédio da lei para com a lei, a fim de que me tornasse vivo para com Deus.

[[v48-2-20]]

^<<v48-2-20,20>>^ Estou pregado na estaca^&#42;1^ junto com Cristo. Quem vive não sou mais eu, mas é Cristo quem está vivendo em união comigo. Deveras, a vida que agora vivo na carne, eu a vivo pela fé que é para com o Filho de Deus, o qual me amou e se entregou por mim.

[NOTE]
====
. Ou “fixado numa estaca (poste)”. Veja Ap. 5C.
====

[[v48-2-21]]

^<<v48-2-21,21>>^ Eu não repilo a benignidade imerecida de Deus; pois, se a justiça é por intermédio da lei, Cristo realmente morreu em vão.

'''

xref:048-galatas/048-galatas-001.adoc#v48-1-0[&#60; Capítulo Anterior] | <<v48-2-0,Topo>> | xref:048-galatas/048-galatas-003.adoc#v48-3-0[Próximo Capítulo &#62;]