include::./index.adoc[]

[[v48-4-0]]
=== Gálatas, 4
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v48-4-1]]

^<<v48-4-1,1>>^ Ora, digo que, enquanto o herdeiro é pequenino, não difere em nada dum escravo, embora seja senhor de todas as coisas,

[[v48-4-2]]

^<<v48-4-2,2>>^ mas está debaixo de encarregados e mordomos,^&#42;1^ até o dia designado de antemão pelo seu pai.

[NOTE]
====
. Ou “administradores domésticos”.
====

[[v48-4-3]]

^<<v48-4-3,3>>^ Igualmente também nós, quando éramos pequeninos, continuávamos escravizados pelas coisas elementares, pertencentes ao mundo.

[[v48-4-4]]

^<<v48-4-4,4>>^ Mas, quando chegou o pleno limite do tempo, Deus enviou o seu Filho, que veio a proceder duma mulher e que veio a estar debaixo de lei,

[[v48-4-5]]

^<<v48-4-5,5>>^ para livrar por meio duma compra os debaixo de lei, para que nós, da nossa parte, recebêssemos a adoção como filhos.

[[v48-4-6]]

^<<v48-4-6,6>>^ Ora, visto que sois filhos, Deus enviou o espírito do seu Filho aos nossos corações, e ele clama: “Aba,^&#42;1^ Pai!”

[NOTE]
====
. “Aba.” Esta é uma palavra aram. que significa “o pai”, ou: “Ó Pai!”
====

[[v48-4-7]]

^<<v48-4-7,7>>^ De modo que não és mais escravo, mas filho; e, se filho, também herdeiro por intermédio de Deus.

[[v48-4-8]]

^<<v48-4-8,8>>^ Não obstante, quando não conhecíeis a Deus, então foi que trabalhastes como escravos para os que por natureza não são deuses.

[[v48-4-9]]

^<<v48-4-9,9>>^ Mas, agora que viestes a conhecer a Deus, ou, antes, agora que viestes a ser conhecidos por Deus, como é que retornais novamente às coisas elementares, fracas e mesquinhas, e quereis novamente trabalhar como escravos para elas?

[[v48-4-10]]

^<<v48-4-10,10>>^ Observais escrupulosamente dias, e meses, e épocas,^&#42;1^ e anos.

[NOTE]
====
. Ou “tempos designados”. Gr.: kai·roús.
====

[[v48-4-11]]

^<<v48-4-11,11>>^ Temo por vós, que de algum modo eu tenha labutado em vão com respeito a vós.

[[v48-4-12]]

^<<v48-4-12,12>>^ Irmãos, rogo-vos: Tornai-vos assim como eu sou, porque eu também costumava ser assim como vós. Não me fizestes nenhuma injustiça.

[[v48-4-13]]

^<<v48-4-13,13>>^ Mas sabeis que foi por intermédio de uma doença da minha carne que eu vos declarei as boas novas pela primeira vez.

[[v48-4-14]]

^<<v48-4-14,14>>^ E aquilo que foi uma provação^&#42;1^ para vós na minha carne, vós não tratastes com desdém, nem cuspistes em repugnância; porém, recebestes-me como a um anjo de Deus, como a Cristo Jesus.

[NOTE]
====
. Ou “tentação”. Lit.: “prova”.
====

[[v48-4-15]]

^<<v48-4-15,15>>^ Onde está então essa felicidade que tivestes? Pois eu vos dou testemunho de que, se tivesse sido possível, teríeis até arrancado os vossos olhos e mos teríeis dado.

[[v48-4-16]]

^<<v48-4-16,16>>^ Pois bem, tornei-me vosso inimigo porque estou falando a verdade?

[[v48-4-17]]

^<<v48-4-17,17>>^ Eles vos buscam zelosamente, não de modo excelente, mas querem separar-vos [de mim], para que busqueis zelosamente a eles.

[[v48-4-18]]

^<<v48-4-18,18>>^ No entanto, é excelente que sempre estejais sendo zelosamente procurados numa causa excelente, e não somente quando estou presente convosco,

[[v48-4-19]]

^<<v48-4-19,19>>^ meus filhinhos, com os quais estou novamente em dores de parto até que Cristo seja formado em vós.

[[v48-4-20]]

^<<v48-4-20,20>>^ Mas, quisera eu estar agora presente convosco e falar-vos de modo diferente,^&#42;1^ porque estou perplexo por causa de vós.

[NOTE]
====
. Lit.: “e alterar a minha voz”.
====

[[v48-4-21]]

^<<v48-4-21,21>>^ Dizei-me, vós os que quereis estar debaixo de lei: Não dais ouvidos à Lei?

[[v48-4-22]]

^<<v48-4-22,22>>^ Por exemplo, está escrito que Abraão adquiriu dois filhos, um por meio da serva e outro por meio da livre;

[[v48-4-23]]

^<<v48-4-23,23>>^ mas aquele por meio da serva nasceu realmente na maneira da carne, o outro, por meio da livre, por intermédio duma promessa.

[[v48-4-24]]

^<<v48-4-24,24>>^ Estas coisas são como que um drama simbólico;^&#42;1^ pois estas [mulheres] significam dois pactos, um do monte Sinai, que dá à luz filhos para a escravidão, e que é Agar.

[NOTE]
====
. Ou “como que uma alegoria”. Gr.: al·le·go·roú·me·na; lat.: per al·le·gó·ri·am.
====

[[v48-4-25]]

^<<v48-4-25,25>>^ Ora, esta Agar significa Sinai, um monte na Arábia, e ela corresponde à Jerusalém atual, pois está em escravidão com os seus filhos.

[[v48-4-26]]

^<<v48-4-26,26>>^ Mas a Jerusalém de cima é livre, e ela é a nossa mãe.

[[v48-4-27]]

^<<v48-4-27,27>>^ Porque está escrito: “Regozija-te, ó mulher estéril, que não dás à luz; irrompe e grita alto, ó mulher que não tens dores de parto; pois os filhos da desolada são mais numerosos do que [os] daquela que tem marido.”

[[v48-4-28]]

^<<v48-4-28,28>>^ Ora, nós, irmãos, somos filhos pertencentes à promessa, assim como Isaque foi.

[[v48-4-29]]

^<<v48-4-29,29>>^ Mas, assim como então aquele nascido na maneira da carne começou a perseguir o nascido na maneira do espírito, assim também é agora.

[[v48-4-30]]

^<<v48-4-30,30>>^ Não obstante, o que diz a Escritura? “Expulsa a serva e o filho dela, pois de modo algum será o filho da serva herdeiro junto com o filho da livre.”

[[v48-4-31]]

^<<v48-4-31,31>>^ Por conseguinte, irmãos, somos filhos, não duma serva, mas da livre.

'''

xref:048-galatas/048-galatas-003.adoc#v48-3-0[&#60; Capítulo Anterior] | <<v48-4-0,Topo>> | xref:048-galatas/048-galatas-005.adoc#v48-5-0[Próximo Capítulo &#62;]