include::./index.adoc[]

[[v48-6-0]]
=== Gálatas, 6
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v48-6-1]]

^<<v48-6-1,1>>^ Irmãos, mesmo que um homem dê um passo em falso^&#42;1^ antes de se aperceber disso, vós, os que tendes qualificações espirituais, tentai reajustar^&#42;2^ tal homem num espírito de brandura, ao passo que cada um olha para si mesmo, para que tu não sejas também tentado.

[NOTE]
====
. Lit.: “alguns caiam ao lado”.
. Ou “restabelecer na posição correta; colocar no alinhamento correto”.
====

[[v48-6-2]]

^<<v48-6-2,2>>^ Prossegui em levar os fardos^&#42;1^ uns dos outros e cumpri assim a lei do Cristo.

[NOTE]
====
. Ou “coisas penosas”. Lit.: “coisas pesadas”. Gr.: bá·re.
====

[[v48-6-3]]

^<<v48-6-3,3>>^ Pois, se alguém acha que ele é alguma coisa, quando não é nada, está enganando a sua própria mente.

[[v48-6-4]]

^<<v48-6-4,4>>^ Mas, prove cada um^&#42;1^ quais são as suas próprias obras, e então terá causa para exultação, apenas com respeito a si próprio e não em comparação com outra pessoa.

[NOTE]
====
. “Cada um”, אACDVg; P46B: “ele”.
====

[[v48-6-5]]

^<<v48-6-5,5>>^ Pois cada um levará a sua própria carga.^&#42;1^

[NOTE]
====
. “Carga.” Gr.: for·tí·on. Veja v. 2.
====

[[v48-6-6]]

^<<v48-6-6,6>>^ Além disso, todo aquele a quem estiver sendo ensinada oralmente^&#42;1^ a palavra, partilhe todas as boas coisas com aquele que lhe dá tal ensino oral.

[NOTE]
====
. Lit.: “sendo ressoado para baixo a”. Gr.: ka·te·khoú·me·nos; lat.: ca·te·ci·zá·tur.
====

[[v48-6-7]]

^<<v48-6-7,7>>^ Não vos deixeis desencaminhar: De Deus não se mofa. Pois, o que o homem semear, isso também ceifará;

[[v48-6-8]]

^<<v48-6-8,8>>^ porque aquele que semeia visando a sua carne, ceifará da carne corrupção, mas aquele que semeia visando o espírito, ceifará do espírito vida eterna.

[[v48-6-9]]

^<<v48-6-9,9>>^ Assim, não desistamos de fazer aquilo que é excelente, pois ceifaremos na época devida, se não desfalecermos.

[[v48-6-10]]

^<<v48-6-10,10>>^ Realmente, então, enquanto tivermos tempo favorável para isso, façamos o que é bom para com todos, mas especialmente para com os aparentados [conosco] na fé.

[[v48-6-11]]

^<<v48-6-11,11>>^ Vede com quão grandes letras^&#42;1^ vos tenho escrito com a minha própria mão.

[NOTE]
====
. Ou “com que letra comprida”.
====

[[v48-6-12]]

^<<v48-6-12,12>>^ Todos os que querem apresentar uma aparência agradável na carne são os que tentam compelir-vos a ser circuncidados, apenas para que não sejam perseguidos pela estaca de tortura^&#42;1^ do Cristo, Jesus.^&#42;2^

[NOTE]
====
. Veja Ap. 5C.
. “Cristo, Jesus”, P46B; אACDVgSyp: “Cristo”.
====

[[v48-6-13]]

^<<v48-6-13,13>>^ Pois, nem mesmo os que se deixam circuncidar guardam a Lei, mas querem que vós sejais circuncidados, para que tenham causa para jactância na vossa carne.

[[v48-6-14]]

^<<v48-6-14,14>>^ Que nunca ocorra que eu me jacte, exceto da estaca de tortura de nosso Senhor Jesus Cristo, por intermédio de quem o mundo tem sido para mim pregado numa estaca, e eu para o mundo.

[[v48-6-15]]

^<<v48-6-15,15>>^ Pois nem a circuncisão é alguma coisa nem a incircuncisão, mas [sim] uma nova criação.

[[v48-6-16]]

^<<v48-6-16,16>>^ E todos os que andarem ordeiramente segundo esta regra de conduta,^&#42;1^ sobre estes haja paz e misericórdia, sim, sobre o Israel^&#42;2^ de Deus.

[NOTE]
====
. “Segundo . . . regra de conduta”. Ou “segundo . . . cânon (regra)”. Lit.: “pela cana (de medir)”. Gr.: toi ka·nó·ni; lat.: ré·gu·lam, “regulamento”; J18(hebr.): qenéh ham·mid·dáh, “a cana de medir”. Veja Ez 40:5 n.: “medir”.
. Significando “Deus Contende; Contendedor (Perseverador) com Deus”.
====

[[v48-6-17]]

^<<v48-6-17,17>>^ Doravante,^&#42;1^ que ninguém me cause dificuldades, pois estou levando no meu corpo as marcas [dum escravo] de Jesus.

[NOTE]
====
. Ou: “Finalmente.”
====

[[v48-6-18]]

^<<v48-6-18,18>>^ A benignidade imerecida de nosso^&#42;1^ Senhor Jesus Cristo [seja] com o espírito que vós [mostrais], irmãos. Amém.

[NOTE]
====
. “Nosso”, P46ABCDVgSyp; א: “o”.
====

'''

xref:048-galatas/048-galatas-005.adoc#v48-5-0[&#60; Capítulo Anterior] | <<v48-6-0,Topo>> | xref:049-efesios/049-efesios-001.adoc#v49-1-0[Próximo Capítulo &#62;]