include::./index.adoc[]

[[v48-1-0]]
=== Gálatas, 1
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v48-1-1]]

^<<v48-1-1,1>>^ Paulo, apóstolo, não da parte dos homens, nem por intermédio dum homem, mas por intermédio de Jesus Cristo e de Deus, o Pai, que o levantou dentre os mortos,

[[v48-1-2]]

^<<v48-1-2,2>>^ e todos os irmãos comigo, às congregações da Galácia:^&#42;1^

[NOTE]
====
. A província romana que ocupava a parte central do que agora é conhecido como Ásia Menor.
====

[[v48-1-3]]

^<<v48-1-3,3>>^ Que tenhais benignidade imerecida e paz da parte de Deus, nosso Pai, e do Senhor Jesus Cristo.

[[v48-1-4]]

^<<v48-1-4,4>>^ Ele se entregou pelos nossos pecados, a fim de nos livrar do atual iníquo sistema de coisas,^&#42;1^ segundo a vontade de nosso Deus e Pai,

[NOTE]
====
. Ou “ordem de coisas”. Gr.: ai·ó·nos; lat.: saé·cu·lo; J17,18,22(hebr.): ha·‛oh·lám, “a ordem de coisas”.
====

[[v48-1-5]]

^<<v48-1-5,5>>^ a quem seja [dada] a glória para todo o sempre. Amém.

[[v48-1-6]]

^<<v48-1-6,6>>^ Estou admirado de que estais sendo removidos tão depressa Daquele que vos chamou com a benignidade imerecida de Cristo, para outra sorte de boas novas.

[[v48-1-7]]

^<<v48-1-7,7>>^ Mas não são outras; há apenas certos que vos estão causando dificuldades e que querem desvirtuar as boas novas acerca do Cristo.

[[v48-1-8]]

^<<v48-1-8,8>>^ No entanto, mesmo que nós ou um anjo do céu vos declarássemos como boas novas algo além daquilo que vos declaramos como boas novas, seja amaldiçoado.^&#42;1^

[NOTE]
====
. Lit.: “anátema”, isto é, alguém devotado à destruição ou amaldiçoado. Veja De 7:26 n. e De 13:17 n.
====

[[v48-1-9]]

^<<v48-1-9,9>>^ Como já dissemos, também digo agora novamente: Quem quer que vos esteja declarando como boas novas algo além daquilo que aceitastes, seja amaldiçoado.

[[v48-1-10]]

^<<v48-1-10,10>>^ É, de fato, a homens que agora estou tentando persuadir, ou [é] a Deus? Ou busco eu agradar a homens? Se ainda estivesse agradando a homens, não seria escravo de Cristo.

[[v48-1-11]]

^<<v48-1-11,11>>^ Pois, faço-vos saber, irmãos, que as boas novas que vos foram declaradas por mim não são algo humano;

[[v48-1-12]]

^<<v48-1-12,12>>^ porque nem as recebi dum homem, nem me foram ensinadas, exceto por intermédio duma revelação^&#42;1^ de Jesus Cristo.

[NOTE]
====
. Lit.: “exposição; exibição”. Gr.: a·po·ka·lý·pse·os.
====

[[v48-1-13]]

^<<v48-1-13,13>>^ Vós, naturalmente, ouvistes [falar] da minha conduta anterior no judaísmo, que eu perseguia a congregação de Deus e a devastava até o excesso,

[[v48-1-14]]

^<<v48-1-14,14>>^ e que eu fazia mais progresso no judaísmo do que muitos da minha própria idade na minha raça, visto que eu era muito mais zeloso das tradições de meus pais.

[[v48-1-15]]

^<<v48-1-15,15>>^ Mas, quando Deus, que me separou da madre de minha mãe^&#42;1^ e [me] chamou por intermédio da sua benignidade imerecida, achou bom

[NOTE]
====
. Lit.: “tendo-me delimitado para fora da cavidade de minha mãe”.
====

[[v48-1-16]]

^<<v48-1-16,16>>^ revelar o seu Filho em conexão comigo, para que eu declarasse às nações as boas novas a respeito dele, não entrei imediatamente em conferência com carne e sangue.

[[v48-1-17]]

^<<v48-1-17,17>>^ Tampouco subi a Jerusalém, aos que eram apóstolos antes de mim, mas parti para a Arábia e voltei novamente a Damasco.

[[v48-1-18]]

^<<v48-1-18,18>>^ Então, três anos depois, subi a Jerusalém para visitar^&#42;1^ a Cefas, e fiquei com ele quinze dias.

[NOTE]
====
. Lit.: “para visitar, a fim de indagar”.
====

[[v48-1-19]]

^<<v48-1-19,19>>^ Mas, não vi nenhum outro dos apóstolos, a não ser Tiago, o irmão do Senhor.

[[v48-1-20]]

^<<v48-1-20,20>>^ Agora, quanto às coisas acerca das quais vos estou escrevendo, eis que não estou mentindo à vista de Deus.

[[v48-1-21]]

^<<v48-1-21,21>>^ Depois disso, fui para as regiões da Síria e da Cilícia.

[[v48-1-22]]

^<<v48-1-22,22>>^ Mas, de rosto eu era desconhecido às congregações da Judéia, que estavam em união com Cristo;

[[v48-1-23]]

^<<v48-1-23,23>>^ eles apenas costumavam ouvir: “O homem que anteriormente nos perseguia está agora declarando as boas novas a respeito da fé que ele anteriormente devastava.”

[[v48-1-24]]

^<<v48-1-24,24>>^ De modo que começaram a glorificar a Deus por causa de mim.

'''

xref:047-2-corintios/047-2-corintios-013.adoc#v47-13-0[&#60; Capítulo Anterior] | <<v48-1-0,Topo>> | xref:048-galatas/048-galatas-002.adoc#v48-2-0[Próximo Capítulo &#62;]