include::./index.adoc[]

[[v48-3-0]]
=== Gálatas, 3
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v48-3-1]]

^<<v48-3-1,1>>^ Ó insensatos gálatas! Quem é que vos submeteu à influência má, a vós, perante os olhos de quem Jesus Cristo foi retratado abertamente como pregado numa estaca?

[[v48-3-2]]

^<<v48-3-2,2>>^ Eu só gostaria de aprender de vós o seguinte: Recebestes o espírito devido a obras da lei ou devido a terdes ouvido por fé?^&#42;1^

[NOTE]
====
. Ou “devido a um relatório de fé”.
====

[[v48-3-3]]

^<<v48-3-3,3>>^ Sois vós tão insensatos? Depois de terdes principiado em espírito, estais agora sendo completados em carne?

[[v48-3-4]]

^<<v48-3-4,4>>^ Foi em vão que passastes por tantos sofrimentos? Se é que realmente foi em vão.

[[v48-3-5]]

^<<v48-3-5,5>>^ Portanto, aquele que vos supre o espírito e realiza obras poderosas^&#42;1^ entre vós, será que ele faz isto devido a obras da lei ou devido a se ter ouvido por fé?

[NOTE]
====
. Ou “realiza milagres”.
====

[[v48-3-6]]

^<<v48-3-6,6>>^ Assim como Abraão “depositou fé em Jeová,^&#42;1^ e isso lhe foi contado como justiça”.

[NOTE]
====
. Veja Ap. 1D.
====

[[v48-3-7]]

^<<v48-3-7,7>>^ Certamente sabeis que os que aderem à fé é que são filhos de Abraão.

[[v48-3-8]]

^<<v48-3-8,8>>^ Ora, a Escritura, vendo de antemão que Deus declararia justas a pessoas das nações devido à fé, declarou de antemão as boas novas a Abraão, a saber: “Por meio de ti serão abençoadas todas as nações.”

[[v48-3-9]]

^<<v48-3-9,9>>^ Conseqüentemente, os que aderem à fé são abençoados junto com o fiel^&#42;1^ Abraão.

[NOTE]
====
. Ou “crente”.
====

[[v48-3-10]]

^<<v48-3-10,10>>^ Pois todos os que dependem de obras da lei estão sob maldição; porque está escrito: “Maldito é todo aquele que não continuar em todas as coisas escritas no rolo da Lei, a fim de as fazer.”

[[v48-3-11]]

^<<v48-3-11,11>>^ Além disso, é evidente que pela lei ninguém é declarado justo diante de Deus, porque “o justo viverá em razão da fé”.

[[v48-3-12]]

^<<v48-3-12,12>>^ Ora, a Lei não adere à fé, mas “quem os cumprir, viverá por meio deles”.

[[v48-3-13]]

^<<v48-3-13,13>>^ Cristo nos livrou da maldição da Lei por meio duma compra, por se tornar maldição em nosso lugar, porque está escrito: “Maldito é todo aquele pendurado num madeiro.”^&#42;1^

[NOTE]
====
. Ou “árvore”. Gr.: xý·lou. Veja Ap. 5C.
====

[[v48-3-14]]

^<<v48-3-14,14>>^ O propósito foi que a bênção de Abraão, por meio de Jesus Cristo, fosse para as nações, a fim de que recebêssemos o espírito prometido,^&#42;1^ por intermédio da nossa fé.

[NOTE]
====
. Lit.: “a promessa do espírito”.
====

[[v48-3-15]]

^<<v48-3-15,15>>^ Irmãos, falo com uma ilustração humana: Um pacto validado, embora seja de homem, ninguém repele nem lhe faz acréscimos.

[[v48-3-16]]

^<<v48-3-16,16>>^ Ora, as promessas foram feitas a Abraão e a seu descendente. Não diz: “E a descendentes”, como no caso de muitos, mas como no caso de um só: “E a teu descendente”, que é Cristo.

[[v48-3-17]]

^<<v48-3-17,17>>^ Outrossim, digo o seguinte: Quanto ao pacto anteriormente validado por Deus, a Lei, que veio à existência quatrocentos e trinta anos depois, não o invalida, de modo a abolir a promessa.

[[v48-3-18]]

^<<v48-3-18,18>>^ Pois, se a herança se deve a uma lei, já não se deve mais a uma promessa; ao passo que Deus a deu bondosamente a Abraão por intermédio duma promessa.

[[v48-3-19]]

^<<v48-3-19,19>>^ Por que, então, a Lei? Ela foi acrescentada para tornar manifestas as transgressões,^&#42;1^ até que chegasse o descendente a quem se fizera a promessa; e ela foi transmitida por intermédio de anjos, pela mão dum mediador.

[NOTE]
====
. Ou “acrescentada a favor das transgressões”.
====

[[v48-3-20]]

^<<v48-3-20,20>>^ Ora, não há mediador onde apenas uma pessoa está envolvida, mas Deus^&#42;1^ é apenas um.

[NOTE]
====
. “Deus”, P46אABVgSyp; J7,8: “Jeová”.
====

[[v48-3-21]]

^<<v48-3-21,21>>^ Portanto, é a Lei contra as promessas de Deus?^&#42;1^ Que isso nunca aconteça! Porque, se tivesse sido dada uma lei que fosse capaz de dar vida, a justiça teria sido realmente por meio da lei.

[NOTE]
====
. “De Deus”, אACDItVgSyh,pArm; P46B omitem isso.
====

[[v48-3-22]]

^<<v48-3-22,22>>^ Mas a Escritura entregou todas as coisas juntas à detenção pelo pecado, para que a promessa resultante da fé para com Jesus Cristo fosse dada aos que exercessem fé.

[[v48-3-23]]

^<<v48-3-23,23>>^ No entanto, antes de chegar a fé, estávamos sendo guardados debaixo de lei, entregues juntos à detenção, aguardando a fé que estava destinada a ser revelada.

[[v48-3-24]]

^<<v48-3-24,24>>^ A Lei, por conseguinte, tornou-se o nosso tutor,^&#42;1^ conduzindo a Cristo, para que fôssemos declarados justos devido à fé.

[NOTE]
====
. Lit.: “pedagogo”. Gr.: pai·da·go·gós; lat.: pe·da·gó·gus.
====

[[v48-3-25]]

^<<v48-3-25,25>>^ Mas agora que chegou a fé, não estamos mais debaixo dum tutor.

[[v48-3-26]]

^<<v48-3-26,26>>^ Todos vós sois, de fato, filhos de Deus, por intermédio da vossa fé em Cristo Jesus.

[[v48-3-27]]

^<<v48-3-27,27>>^ Pois todos vós, os que fostes batizados em Cristo, vos revestistes de Cristo.^&#42;1^

[NOTE]
====
. Ou “vos vestistes (identificastes) com Cristo”.
====

[[v48-3-28]]

^<<v48-3-28,28>>^ Não há nem judeu nem grego, não há nem escravo nem homem livre, não há nem macho nem fêmea; pois todos vós sois um só em união com Cristo Jesus.

[[v48-3-29]]

^<<v48-3-29,29>>^ Além disso, se pertenceis a Cristo, sois realmente descendente de Abraão, herdeiros com referência a uma promessa.

'''

xref:048-galatas/048-galatas-002.adoc#v48-2-0[&#60; Capítulo Anterior] | <<v48-3-0,Topo>> | xref:048-galatas/048-galatas-004.adoc#v48-4-0[Próximo Capítulo &#62;]