include::./index.adoc[]

[[v21-5-0]]
=== Eclesiastes, 5
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v21-5-1]]

^<<v21-5-1,1>>^ Guarda os teus pés, sempre que fores à casa do [verdadeiro] Deus; e haja um achegamento^&#42;1^ para ouvir, em vez de se dar um sacrifício como fazem os estúpidos, pois não se apercebem de que fazem o que é mau.^&#42;2^

[NOTE]
====
. “Haja um achegamento.” No hebr., isto é um verbo no infinitivo absoluto, indefinido quanto ao tempo e impessoal.
. MTLXXSyVg terminam aqui o capítulo 4 com o v. 17.
====

[[v21-5-2]]

^<<v21-5-2,2>>^ Não te precipites com respeito à tua boca; e quanto ao teu coração, não o deixes apressar-se a produzir uma palavra diante do [verdadeiro] Deus. Pois o [verdadeiro] Deus está nos céus, mas tu estás na terra. Por isso é que as tuas palavras devem mostrar ser poucas.

[[v21-5-3]]

^<<v21-5-3,3>>^ Pois o sonho certamente chega por causa da abundância de ocupação, e a voz do estúpido, por causa da abundância de palavras.

[[v21-5-4]]

^<<v21-5-4,4>>^ Sempre que fizeres um voto a Deus, não hesites em pagá-lo, pois não há agrado nos estúpidos. O que votares, paga.

[[v21-5-5]]

^<<v21-5-5,5>>^ Melhor é que não votes, do que votares e não pagares.

[[v21-5-6]]

^<<v21-5-6,6>>^ Não permitas que a tua boca faça a tua carne pecar,^&#42;1^ nem digas diante do anjo^&#42;2^ que foi um engano. Por que devia o [verdadeiro] Deus ficar indignado por causa da tua voz e ter de estragar o trabalho das tuas mãos?

[NOTE]
====
. “Não permitas que a palavra da tua boca determine o julgamento da Geena sobre a tua carne”, T.
. “Anjo”, MTVg; LXXSy: “Deus.”
====

[[v21-5-7]]

^<<v21-5-7,7>>^ Pois, por causa da abundância [de ocupação] há sonhos, e há vaidades e palavras em abundância. Mas teme o próprio [verdadeiro] Deus.

[[v21-5-8]]

^<<v21-5-8,8>>^ Se vires o de poucos meios sofrer opressão, e o arrebatamento violento do juízo e da justiça num distrito jurisdicional, não fiques pasmado com o assunto, pois alguém que é mais alto do que o alto está vigiando, e há os que estão alto por cima deles.^&#42;1^

[NOTE]
====
. Ou “e há o Supremo acima deles”.
====

[[v21-5-9]]

^<<v21-5-9,9>>^ Também, o proveito da terra está entre eles todos; pois, por um campo, o próprio rei foi servido.

[[v21-5-10]]

^<<v21-5-10,10>>^ O mero amante da prata não se fartará de prata, nem o amante da opulência, da renda.^&#42;1^ Também isto é vaidade.

[NOTE]
====
. Lit.: “e que fixa seu amor na riqueza sem ter renda (rendimento)?”
====

[[v21-5-11]]

^<<v21-5-11,11>>^ Quando as coisas boas se tornam muitas, os que as comem certamente se tornam muitos. E que vantagem há nisso para o grandioso dono delas, exceto olhar [para elas] com os seus olhos?

[[v21-5-12]]

^<<v21-5-12,12>>^ Doce é o sono de quem serve, quer seja pouco quer muito o que ele come; mas a fartura do rico não o deixa dormir.

[[v21-5-13]]

^<<v21-5-13,13>>^ Há uma grave calamidade que tenho visto debaixo do sol: riquezas guardadas para o seu grandioso dono,^&#42;1^ para a sua calamidade.

[NOTE]
====
. “Para o seu grandioso dono.” Hebr.: liv·‛a·láv.
====

[[v21-5-14]]

^<<v21-5-14,14>>^ E estas riquezas pereceram por causa duma ocupação calamitosa, e ele se tornou pai de um filho quando não há absolutamente nada na sua mão.

[[v21-5-15]]

^<<v21-5-15,15>>^ Assim como se saiu do ventre da mãe, nu se irá novamente embora, assim como se veio; e não se pode levar absolutamente nada pelo seu trabalho árduo, que se possa levar junto na mão.

[[v21-5-16]]

^<<v21-5-16,16>>^ E também isto é uma grave calamidade: exatamente assim como se veio, assim se irá embora; e que proveito há para quem continua a trabalhar arduamente para o vento?

[[v21-5-17]]

^<<v21-5-17,17>>^ Também, todos os seus dias ele come na própria escuridão, com muito vexame, com doença da sua parte e [com causa para] indignação.

[[v21-5-18]]

^<<v21-5-18,18>>^ Eis que a melhor coisa que eu mesmo vi, que é bonita, é que a pessoa coma, e beba, e veja o que é bom por toda a sua labuta com que trabalha arduamente debaixo do sol pelo número dos dias da sua vida que o [verdadeiro] Deus lhe deu, pois este é seu quinhão.

[[v21-5-19]]

^<<v21-5-19,19>>^ Também, todo homem a quem o [verdadeiro] Deus tem dado riquezas e bens materiais, ele até mesmo habilitou a comer disso, e a levar o seu quinhão, e a alegrar-se no seu trabalho árduo. Esta é a dádiva de Deus.

[[v21-5-20]]

^<<v21-5-20,20>>^ Pois não é muitas vezes que ele se lembrará dos dias da sua vida, porque o [verdadeiro] Deus [o] preocupa^&#42;1^ com a alegria do seu coração.

[NOTE]
====
. Possivelmente: “[lhe] responde”, segundo outra derivação do verbo hebr.
====

'''

xref:021-eclesiastes/021-eclesiastes-004.adoc#v21-4-0[&#60; Capítulo Anterior] | <<v21-5-0,Topo>> | xref:021-eclesiastes/021-eclesiastes-006.adoc#v21-6-0[Próximo Capítulo &#62;]