include::./index.adoc[]

[[v21-2-0]]
=== Eclesiastes, 2
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v21-2-1]]

^<<v21-2-1,1>>^ Eu é que disse no meu coração: “Ora, vem deveras, deixa-me experimentar-te com alegria. Também, vê o que é bom.” E eis que isso também era vaidade.

[[v21-2-2]]

^<<v21-2-2,2>>^ Eu disse ao riso: “Insânia!” e à alegria: “Que está fazendo esta?”

[[v21-2-3]]

^<<v21-2-3,3>>^ Perscrutei com o meu coração, animando minha carne até mesmo com vinho, ao passo que eu conduzia meu coração com sabedoria, sim, para apoderar-me da estultícia, até que eu pudesse ver o que havia de bom para os filhos da humanidade naquilo que faziam debaixo dos céus, pelo número dos dias da sua vida.

[[v21-2-4]]

^<<v21-2-4,4>>^ Empenhei-me em trabalhos maiores. Construí para mim casas; plantei para mim vinhedos.

[[v21-2-5]]

^<<v21-2-5,5>>^ Fiz para mim jardins e parques,^&#42;1^ e plantei neles toda sorte de árvores frutíferas.

[NOTE]
====
. “E parques.” Hebr.: u·far·de·sím, pl. de par·dés; LXXSy: “parques; paraísos”.
====

[[v21-2-6]]

^<<v21-2-6,6>>^ Fiz para mim reservatórios de água para irrigar com eles a floresta em que crescem árvores.

[[v21-2-7]]

^<<v21-2-7,7>>^ Adquiri servos e servas, e vim a ter filhos dos da casa. Vim a ter também gado, gado vacum e rebanhos em grande quantidade, mais do que todos os que vieram a estar antes de mim em Jerusalém.

[[v21-2-8]]

^<<v21-2-8,8>>^ Acumulei também para mim prata e ouro, bem como propriedade peculiar de reis e de distritos jurisdicionais. Constituí para mim cantores e cantoras, bem como as delícias dos filhos da humanidade, uma dama, sim, damas.

[[v21-2-9]]

^<<v21-2-9,9>>^ E tornei-me maior e aumentei mais do que qualquer outro que veio a estar antes de mim em Jerusalém. Além disso, minha própria sabedoria permaneceu minha.

[[v21-2-10]]

^<<v21-2-10,10>>^ E tudo o que os meus olhos pediram, eu não retive deles. Não neguei ao meu coração nenhuma espécie de alegria, pois meu coração se alegrava por causa de todo o meu trabalho árduo, e isto veio a ser meu quinhão de todo o meu trabalho árduo.

[[v21-2-11]]

^<<v21-2-11,11>>^ E eu, sim, eu me virei para todos os meus trabalhos que minhas mãos tinham feito e para a labuta em que eu tinha trabalhado arduamente para a realizar, e eis que tudo era vaidade e um esforço para alcançar o vento, e não havia nada de vantagem debaixo do sol.

[[v21-2-12]]

^<<v21-2-12,12>>^ E eu é que me virei para ver sabedoria, e doidice, e estultícia; pois o que pode fazer o homem terreno que entra depois do rei? A coisa que já se fez.

[[v21-2-13]]

^<<v21-2-13,13>>^ E eu é que vi que há mais vantagem na sabedoria do que na estultícia, do mesmo modo como há mais vantagem na luz do que na escuridão.

[[v21-2-14]]

^<<v21-2-14,14>>^ Quanto àquele que é sábio, tem os olhos na cabeça; mas o estúpido está andando em profunda escuridão. E também eu é que vim a saber que há um só evento conseqüente que sucede eventualmente a todos eles.

[[v21-2-15]]

^<<v21-2-15,15>>^ E eu mesmo disse no meu coração: “Um evento conseqüente igual a este para o estúpido sucederá eventualmente a mim, sim, a mim.” Então, por que é que me tornei sábio, extremamente assim naquele tempo? E falei no meu coração: “Também isto é vaidade.”

[[v21-2-16]]

^<<v21-2-16,16>>^ Porque não há mais recordação do sábio do que do estúpido, por tempo indefinido. Nos dias que já estão entrando, todos já estão esquecidos; e como morrerá o sábio? Junto com o estúpido.

[[v21-2-17]]

^<<v21-2-17,17>>^ E odiei a vida, porque o trabalho que se tem feito debaixo do sol tem sido calamitoso do meu ponto de vista, pois tudo era vaidade e um esforço para alcançar o vento.

[[v21-2-18]]

^<<v21-2-18,18>>^ E eu é que odiei toda a minha labuta em que trabalhava arduamente debaixo do sol, que eu deixaria atrás para o homem que viria a suceder-me.

[[v21-2-19]]

^<<v21-2-19,19>>^ E quem sabe se ele se mostrará sábio ou estulto? No entanto, assumirá o controle sobre toda a minha labuta em que trabalhei arduamente e em que mostrei sabedoria debaixo do sol. Também isto é vaidade.

[[v21-2-20]]

^<<v21-2-20,20>>^ E eu mesmo me voltei para fazer meu coração desesperar de toda a labuta em que tinha trabalhado arduamente debaixo do sol.

[[v21-2-21]]

^<<v21-2-21,21>>^ Pois há um homem cujo trabalho árduo foi com sabedoria, e com conhecimento, e com proficiência, mas ao homem que não trabalhou arduamente em tal coisa se dará o quinhão daquele. Também isto é vaidade e uma grande calamidade.

[[v21-2-22]]

^<<v21-2-22,22>>^ Pois, o que é que o homem vem a ter^&#42;1^ de todo o seu trabalho árduo e do esforço de seu coração com que trabalha arduamente debaixo do sol?

[NOTE]
====
. Lit.: “o que se mostra haver para o homem?” Hebr.: meh-ho·wéh la·’a·dhám? O particípio hebr. ho·wéh provém do verbo básico ha·wáh, relacionado com o nome divino, Yeho·wáh.
====

[[v21-2-23]]

^<<v21-2-23,23>>^ Porque todos os seus dias sua ocupação significa dores e vexame, também durante a noite seu coração simplesmente não se deita. Também isto é mera vaidade.

[[v21-2-24]]

^<<v21-2-24,24>>^ Para o homem não há nada melhor [do] que comer, e deveras beber, e fazer sua alma ver o que é bom por causa do seu trabalho árduo. Isto também tenho visto, sim eu, que isto procede da mão do [verdadeiro] Deus.^&#42;1^

[NOTE]
====
. “Do [verdadeiro] Deus.” Hebr.: ha·’Elo·hím, tendo ha, “o”, para ênfase; TSy: “Jeová”. Veja Ap. 1F.
====

[[v21-2-25]]

^<<v21-2-25,25>>^ Pois, quem come e quem bebe^&#42;1^ melhor do que eu?

[NOTE]
====
. “Bebe”, LXXBagsterSy; M: “se apressa”.
====

[[v21-2-26]]

^<<v21-2-26,26>>^ Pois, ao homem que é bom diante dele, ele tem dado sabedoria, e conhecimento, e alegria, mas ao pecador tem dado a ocupação de ajuntar e de recolher, apenas para dar àquele que é bom diante do [verdadeiro] Deus. Também isto é vaidade e um esforço para alcançar o vento.

'''

xref:021-eclesiastes/021-eclesiastes-001.adoc#v21-1-0[&#60; Capítulo Anterior] | <<v21-2-0,Topo>> | xref:021-eclesiastes/021-eclesiastes-003.adoc#v21-3-0[Próximo Capítulo &#62;]