include::./index.adoc[]

[[v21-1-0]]
=== Eclesiastes, 1
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v21-1-1]]

^<<v21-1-1,1>>^ As palavras do congregante,^&#42;1^ filho de Davi, rei em Jerusalém.

[NOTE]
====
. Ou “reunidor; ajuntador; convocador”, M; LXXVg: “Eclesiastes”, isto é, membro duma eclésia (congregação; assembléia).
====

[[v21-1-2]]

^<<v21-1-2,2>>^ “A maior das vaidades”,^&#42;1^ disse o congregante, “a maior das vaidades! Tudo é vaidade!”

[NOTE]
====
. “A maior das vaidades.” Lit.: “Vaidade das vaidades”, M(hebr.: havél hava·lím)LXXSyVg.
====

[[v21-1-3]]

^<<v21-1-3,3>>^ Que proveito tem o homem^&#42;1^ de toda a sua labuta em que trabalha arduamente debaixo do sol?^&#42;2^

[NOTE]
====
. Lit.: “para o homem terreno”. Hebr.: la·’a·dhám.
. “Debaixo do sol.” Hebr.: ta·hháth hash·shá·mesh. Esta frase ocorre 29 vezes em Eclesiastes.
====

[[v21-1-4]]

^<<v21-1-4,4>>^ Uma geração vai e outra geração vem; mas a terra permanece por tempo indefinido.

[[v21-1-5]]

^<<v21-1-5,5>>^ E também o sol raiou e o sol se pôs, e vem ofegante ao seu lugar onde vai raiar.

[[v21-1-6]]

^<<v21-1-6,6>>^ O vento^&#42;1^ vai para o sul e faz o giro para o norte. Gira^&#42;2^ e gira continuamente em volta, e o vento^&#42;3^ retorna logo aos seus giros.

[NOTE]
====
. “O vento.” Lit.: “ele”, possivelmente referindo-se ao sol nos seus movimentos para o sul e para o norte entre os solstícios do verão e do inverno.
. “Gira.” Lit.: “o vento gira”, mas na tradução “vento” é transferido para o início do v.
. “O vento.” Hebr.: ha·rú·ahh; gr.: pneú·ma. Veja Gên 1:2 n.: “ativa”.
====

[[v21-1-7]]

^<<v21-1-7,7>>^ Todas as torrentes hibernais correm para o mar, contudo, o próprio mar não está cheio. Ao lugar de onde correm as torrentes hibernais, para lá elas voltam a fim de sair correndo.

[[v21-1-8]]

^<<v21-1-8,8>>^ Todas as coisas são fatigantes; ninguém pode falar disso. O olho não se farta de ver, nem o ouvido se enche de ouvir.

[[v21-1-9]]

^<<v21-1-9,9>>^ Aquilo que veio a ser é o que virá a ser; e o que se tem feito é o que se fará; de modo que não há nada de novo debaixo do sol.^&#42;1^

[NOTE]
====
. Veja v. 3 n.: “sol”.
====

[[v21-1-10]]

^<<v21-1-10,10>>^ Existe algo de que se possa dizer: “Vê isto; isto é novo”? Já tem existido por tempo indefinido; o que veio à existência é de tempo anterior a nós.

[[v21-1-11]]

^<<v21-1-11,11>>^ Não há recordação de gente de outrora, nem haverá dos que virão a ser mais tarde. Não se mostrará haver recordação nem mesmo daqueles entre os que virão a ser ainda mais tarde.

[[v21-1-12]]

^<<v21-1-12,12>>^ Eu, o congregante,^&#42;1^ vim a ser rei sobre Israel em Jerusalém.

[NOTE]
====
. Veja v. 1 n.
====

[[v21-1-13]]

^<<v21-1-13,13>>^ E pus meu coração a buscar e a perscrutar a sabedoria em relação a tudo o que se tem feito debaixo dos céus — a ocupação calamitosa que Deus tem dado aos filhos da humanidade^&#42;1^ para se ocuparem nela.

[NOTE]
====
. Ou “homens”. Hebr.: ha·’a·dhám.
====

[[v21-1-14]]

^<<v21-1-14,14>>^ Vi todos os trabalhos que se faziam debaixo do sol, e eis que tudo era vaidade e um esforço para alcançar o vento.^&#42;1^

[NOTE]
====
. Veja v. 6, a segunda nota sobre “vento”.
====

[[v21-1-15]]

^<<v21-1-15,15>>^ Aquilo que foi feito torto não pode ser endireitado, e aquilo que é carente é que não se pode contar.

[[v21-1-16]]

^<<v21-1-16,16>>^ Eu é que falei com o meu coração, dizendo: “Eis que eu mesmo aumentei grandemente em sabedoria, mais do que qualquer outro que veio a estar antes de mim em Jerusalém, e meu próprio coração tem visto muita sabedoria e conhecimento.”

[[v21-1-17]]

^<<v21-1-17,17>>^ E passei a empenhar meu coração a conhecer a sabedoria e a conhecer a doidice, e vim a conhecer a estultícia, que isto também é um esforço para alcançar o vento.^&#42;1^

[NOTE]
====
. Veja v. 6, a segunda nota sobre “vento”.
====

[[v21-1-18]]

^<<v21-1-18,18>>^ Porque na abundância de sabedoria há abundância de vexame, de modo que aquele que incrementa o conhecimento incrementa a dor.

'''

xref:020-proverbios/020-proverbios-031.adoc#v20-31-0[&#60; Capítulo Anterior] | <<v21-1-0,Topo>> | xref:021-eclesiastes/021-eclesiastes-002.adoc#v21-2-0[Próximo Capítulo &#62;]