include::./index.adoc[]

[[v6-22-0]]
=== Josué, 22
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v6-22-1]]

^<<v6-22-1,1>>^ Naquele tempo, Josué passou a chamar os rubenitas e os gaditas, e a meia tribo de Manassés,

[[v6-22-2]]

^<<v6-22-2,2>>^ e passou a dizer-lhes: “Vós, da vossa parte, guardastes tudo o que Moisés, servo de Jeová, vos ordenou e fostes obedientes à minha voz em tudo o que vos ordenei.

[[v6-22-3]]

^<<v6-22-3,3>>^ Não deixastes os vossos irmãos durante estes muitos dias até o dia de hoje e cumpristes a obrigação para com o mandamento de Jeová, vosso Deus.

[[v6-22-4]]

^<<v6-22-4,4>>^ E agora, Jeová, vosso Deus, deu descanso aos vossos irmãos, assim como lhes prometeu. Portanto, agora dai volta e ide-vos embora para as vossas tendas na terra de vossa propriedade, que Moisés, servo de Jeová, vos deu no outro lado do Jordão.

[[v6-22-5]]

^<<v6-22-5,5>>^ Somente tende muito cuidado em cumprir o mandamento e a lei que Moisés, servo de Jeová, vos ordenou, amando a Jeová, vosso Deus, e andando em todos os seus caminhos e guardando seus mandamentos, e apegando-vos a ele e servindo-o de todo o vosso coração e de toda a vossa alma.”

[[v6-22-6]]

^<<v6-22-6,6>>^ Com isso Josué os abençoou e os mandou embora, para que fossem para as suas tendas.^&#42;1^

[NOTE]
====
. Ou “lares”.
====

[[v6-22-7]]

^<<v6-22-7,7>>^ E à meia tribo de Manassés Moisés dera um presente em Basã, e à outra meia tribo Josué deu um presente junto a seus irmãos no lado do Jordão que dá para o oeste. Assim também, quando Josué os mandou embora para as suas tendas, ele passou a abençoá-los.

[[v6-22-8]]

^<<v6-22-8,8>>^ E prosseguiu, dizendo-lhes: “Retornai às vossas tendas com muitos bens materiais e com muitíssimo gado, com prata e ouro, e cobre, e ferro, e mantos em quantidade muito grande. Tomai a vossa parte do despojo dos vossos inimigos junto com os vossos irmãos.”

[[v6-22-9]]

^<<v6-22-9,9>>^ Após isso, os filhos de Rubem e os filhos de Gade, e a meia tribo de Manassés, voltaram e se afastaram dos outros filhos de Israel, de Silo, que está na terra de Canaã, a fim de irem para a terra de Gileade, para a terra de sua propriedade na qual se haviam estabelecido segundo a ordem de Jeová por intermédio de Moisés.

[[v6-22-10]]

^<<v6-22-10,10>>^ Quando chegaram às regiões do Jordão que se achavam na terra de Canaã, então os filhos de Rubem e os filhos de Gade, e a meia tribo de Manassés, construíram ali um altar junto ao Jordão, um altar grande que dava na vista.

[[v6-22-11]]

^<<v6-22-11,11>>^ Mais tarde, os outros filhos de Israel ouviram dizer: “Eis que os filhos de Rubem e os filhos de Gade, e a meia tribo de Manassés construíram um altar na fronteira da terra de Canaã, nas regiões do Jordão, no lado que pertence aos filhos de Israel.”

[[v6-22-12]]

^<<v6-22-12,12>>^ Quando os filhos de Israel chegaram a ouvir isso, então se congregou a assembléia inteira dos filhos de Israel em Silo, a fim de subirem numa ação militar contra eles.

[[v6-22-13]]

^<<v6-22-13,13>>^ Os filhos de Israel enviaram então Finéias, filho de Eleazar, o sacerdote, aos filhos de Rubem e aos filhos de Gade, e à meia tribo de Manassés, na terra de Gileade,

[[v6-22-14]]

^<<v6-22-14,14>>^ bem como dez maiorais com ele, um maioral de cada casa paterna de todas as tribos de Israel, e cada um deles cabeça da casa de seus pais dos milhares de Israel.

[[v6-22-15]]

^<<v6-22-15,15>>^ Chegaram então aos filhos de Rubem e aos filhos de Gade, e à meia tribo de Manassés, na terra de Gileade, e começaram a falar com eles, dizendo:

[[v6-22-16]]

^<<v6-22-16,16>>^ “Assim disse toda a assembléia de Jeová: ‘Que ato de infidelidade é este que cometestes contra o Deus de Israel, recuando hoje de seguirdes a Jeová, construindo para vós um altar para vos rebelardes hoje contra Jeová?

[[v6-22-17]]

^<<v6-22-17,17>>^ Foi pequeno demais para nós o erro de Peor, do qual não nos purificamos até o dia de hoje, embora viesse a praga sobre a assembléia de Jeová?

[[v6-22-18]]

^<<v6-22-18,18>>^ E vós é que recuaríeis hoje de seguir a Jeová; e terá de acontecer que, se vós, da vossa parte, vos rebelardes hoje contra Jeová, então amanhã será contra a assembléia inteira de Israel que ele se indignará.

[[v6-22-19]]

^<<v6-22-19,19>>^ Agora, se é que a terra de vossa propriedade é impura, então passai para o outro lado, para a terra da propriedade de Jeová, onde tem residido o tabernáculo de Jeová, e estabelecei-vos no nosso meio; e não vos rebeleis contra Jeová e não façais que sejamos rebeldes por construirdes para vós um altar em adição ao altar de Jeová, nosso Deus.

[[v6-22-20]]

^<<v6-22-20,20>>^ Não cometeu Acã, filho de Zerá, um ato de infidelidade com a coisa devotada à destruição, e não veio a haver indignação contra toda a assembléia de Israel? E ele não foi o único homem a expirar no seu erro.’”

[[v6-22-21]]

^<<v6-22-21,21>>^ Nisso os filhos de Rubem e os filhos de Gade, e a meia tribo de Manassés, responderam e falaram com os cabeças dos milhares de Israel:

[[v6-22-22]]

^<<v6-22-22,22>>^ “Divino, Deus, Jeová, Divino, Deus, Jeová,^&#42;1^ ele sabe, e Israel, ele também saberá. Se foi em rebeldia^&#42;2^ e se foi em infidelidade contra Jeová, não nos salves neste dia.

[NOTE]
====
. Ou: “O Deus de deuses, Jeová, o Deus de deuses, Jeová.” Hebr.: ’El ׀ ’Elo·hím ׀ Yehwáh, ’El ׀ ’Elo·hím ׀ Yehwáh, com o sinal divisório (pa·séq) entre as palavras. Esta expressão, ’El ’Elo·hím Yehwáh, ocorre sem repetição no Sal 50:1. Lat.: For·tís·si·mus Dé·us Dó·mi·nus, For·tís·si·mus Dé·us Dó·mi·nus, “O Poderosíssimo Deus Jeová, O Poderosíssimo Deus Jeová”. A primeira palavra, ’El, da expressão hebr. foi vertida por nós por “Divino”. Pode ser vertida também por “Deus; Poderoso”.
. “Rebeldia”, M. Gr.: a·po·sta·sí·ai, “apostasia”, do verbo a·fí- ste·mi, “apartar-se de”; o substantivo tem o sentido de “deserção; abandono; rebeldia”. Veja notas sobre 2Cr 29:19; At 21:21; 2Te 2:3.
====

[[v6-22-23]]

^<<v6-22-23,23>>^ Se^&#42;1^ foi para construirmos para nós um altar, de modo a recuarmos de seguir a Jeová, e se foi para oferecer nele ofertas queimadas e ofertas de cereais, e se foi para ofertar nele sacrifícios de participação em comum, o próprio Jeová o pesquisará;

[NOTE]
====
. “E se”, LXXVg; M omite isso.
====

[[v6-22-24]]

^<<v6-22-24,24>>^ ou se não foi antes de ansiedade por outra coisa que fizemos isso, dizendo: ‘Num dia futuro vossos filhos dirão aos nossos filhos: “Que tendes vós que ver com Jeová,^&#42;1^ o Deus de Israel?

[NOTE]
====
. Ou: “Que tendes em comum com Jeová?” Lit.: “Que [há] para ti e para Jeová?” Esta é uma expressão idiomática hebr.; é uma pergunta de repulsa, indicando objeção. Veja Ap. 7B.
====

[[v6-22-25]]

^<<v6-22-25,25>>^ E há um termo que Jeová pôs entre nós e vós, os filhos de Rubem e os filhos de Gade, a saber, o Jordão. Não tendes quinhão em Jeová.” E vossos filhos certamente farão os nossos filhos desistir de temer a Jeová.’

[[v6-22-26]]

^<<v6-22-26,26>>^ “Por isso dissemos: ‘Por favor, tomemos ação em nosso benefício, construindo um altar, não para oferta queimada nem para sacrifício,

[[v6-22-27]]

^<<v6-22-27,27>>^ mas para que seja testemunha entre nós e vós, e nossas gerações depois de nós, de que prestaremos serviço^&#42;1^ a Jeová diante dele com as nossas ofertas queimadas e os nossos sacrifícios, e os nossos sacrifícios de participação em comum, para que os vossos filhos não digam num dia futuro aos nossos filhos: “Não tendes quinhão em Jeová.”’

[NOTE]
====
. Ou “particularidade de adoração”. Hebr.: ‛avo·dháth; gr.: la·treí·an, “serviço sagrado”. Veja Êx 3:12 n.
====

[[v6-22-28]]

^<<v6-22-28,28>>^ Por isso dissemos: ‘E terá de dar-se que, caso num dia futuro digam isso a nós e às nossas gerações, então teremos de dizer: “Vede a representação do altar de Jeová feita pelos nossos pais, não para oferta queimada nem para sacrifício, mas como testemunha entre nós e vós.”’

[[v6-22-29]]

^<<v6-22-29,29>>^ É inconcebível, da nossa parte, rebelar-nos de nossa própria iniciativa contra Jeová e recuarmos hoje de seguir a Jeová por construirmos um altar para oferta queimada, para oferta de cereais e para sacrifício, além do altar de Jeová, nosso Deus, que está diante do seu tabernáculo!”

[[v6-22-30]]

^<<v6-22-30,30>>^ Ora, quando Finéias, o sacerdote, e os maiorais da assembléia, e os cabeças dos milhares de Israel, que estavam com ele, ouviram as palavras faladas pelos filhos de Rubem, e pelos filhos de Gade, e pelos filhos de Manassés, veio a ser bom aos seus olhos.

[[v6-22-31]]

^<<v6-22-31,31>>^ Portanto, Finéias, filho de Eleazar, o sacerdote, disse aos filhos de Rubem, e aos filhos de Gade, e aos filhos de Manassés: “Hoje sabemos que Jeová está no nosso meio, porque não cometestes este ato de infidelidade contra Jeová. Agora livrastes os filhos de Israel da mão de Jeová.”

[[v6-22-32]]

^<<v6-22-32,32>>^ Com isso Finéias, filho de Eleazar, o sacerdote, e os maiorais voltaram dos filhos de Rubem e dos filhos de Gade, na terra de Gileade, para a terra de Canaã, aos outros filhos de Israel, e trouxeram-lhes a informação.

[[v6-22-33]]

^<<v6-22-33,33>>^ E a informação veio a ser boa aos olhos dos filhos de Israel; e os filhos de Israel passaram a bendizer a Deus, e não falaram mais em subir no serviço armado contra eles para arruinar a terra em que moravam os filhos de Rubem e os filhos de Gade.

[[v6-22-34]]

^<<v6-22-34,34>>^ E os filhos de Rubem e os filhos de Gade começaram a dar um nome ao altar,^&#42;1^ porque “é testemunha entre nós de que Jeová é o [verdadeiro] Deus”.

[NOTE]
====
. Em vista da explicação dada, o altar provavelmente foi chamado de Testemunha. Sy acrescenta: “o altar de testemunho”.
====

'''

xref:006-josue/006-josue-021.adoc#v6-21-0[&#60; Capítulo Anterior] | <<v6-22-0,Topo>> | xref:006-josue/006-josue-023.adoc#v6-23-0[Próximo Capítulo &#62;]