include::./index.adoc[]

[[v6-15-0]]
=== Josué, 15
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v6-15-1]]

^<<v6-15-1,1>>^ E a sorte da tribo dos filhos de Judá, segundo as suas famílias, veio a ser para o [lado do] termo de Edom, o ermo de Zim, até o Negebe, na sua extremidade meridional.

[[v6-15-2]]

^<<v6-15-2,2>>^ E seu termo meridional veio a ser desde a extremidade do Mar Salgado, desde a baía que está encarando o sul.

[[v6-15-3]]

^<<v6-15-3,3>>^ E saía para o sul, para a subida^&#42;1^ de Acrabim, e passava para Zim, e subia do sul para Cades-Barnéia e passava para Esrom, e subia até Adar, e dava volta até Carca.

[NOTE]
====
. Ou “passo”.
====

[[v6-15-4]]

^<<v6-15-4,4>>^ E passava para Azmom e saía até o vale da torrente do Egito; e o ponto final do termo mostrou ser o mar. Este veio a ser seu^&#42;1^ termo meridional.

[NOTE]
====
. “Seu”, LXX; MSy: “vosso”; Vg omite isso.
====

[[v6-15-5]]

^<<v6-15-5,5>>^ E o termo ao leste era o Mar Salgado, para cima até o fim^&#42;1^ do Jordão, e o termo no canto setentrional era a baía do mar, no fim do Jordão.

[NOTE]
====
. Ou “boca”.
====

[[v6-15-6]]

^<<v6-15-6,6>>^ E o termo subia até Bete-Hogla e passava para o norte de Bete-Arabá, e o termo subia até a pedra de Boã, filho de Rubem.

[[v6-15-7]]

^<<v6-15-7,7>>^ E o termo subia até Debir, na baixada de Acor, e se virava para o norte, para Gilgal, que está defronte da subida de Adumim, que se acha ao sul do vale da torrente; e o termo passava para as águas de En-Semes e seu ponto final mostrou ser En-Rogel.

[[v6-15-8]]

^<<v6-15-8,8>>^ E o termo subia até o vale do filho de Hinom para a encosta do jebuseu, ao sul, isto é, Jerusalém; e o termo subia para o cume do monte que defronta com o vale de Hinom^&#42;1^ ao oeste, que se acha na extremidade da baixada de Refaim, ao norte.

[NOTE]
====
. “Vale de Hinom.” Hebr.: gheh-Hin·nóm; LXXA(gr.): fá·rag·gos En·nóm; lat.: Ge·hén·nom. Veja Ap. 4C.
====

[[v6-15-9]]

^<<v6-15-9,9>>^ E o termo estava demarcado desde o cume do monte para o manancial das águas de Neftoa, e saía para as cidades do monte Efrom; e o termo estava demarcado até Baalá, isto é, Quiriate-Jearim.

[[v6-15-10]]

^<<v6-15-10,10>>^ E o termo dava volta de Baalá para o oeste, para a montanha de Seir, e passava para a encosta do monte Jearim, ao norte, isto é, Quesalom; e descia até Bete-Semes e passava para Timná.

[[v6-15-11]]

^<<v6-15-11,11>>^ E o termo saía para a encosta de Ecrom, para o norte, e o termo estava demarcado até Siquerom e passava para o monte Baalá, e saía até Jabneel; e o ponto final do termo mostrou ser o mar.

[[v6-15-12]]

^<<v6-15-12,12>>^ E o termo ocidental era o Grande Mar e seu litoral. Este era o termo, em toda a volta, dos filhos de Judá, segundo as suas famílias.

[[v6-15-13]]

^<<v6-15-13,13>>^ E a Calebe, filho de Jefuné, deu um quinhão no meio dos filhos de Judá, segundo a ordem de Jeová a Josué, a saber, Quiriate-Arba ([este Arba sendo] o pai de Anaque), isto é, Hébron.

[[v6-15-14]]

^<<v6-15-14,14>>^ Portanto, Calebe desalojou dali os três filhos de Anaque, a saber, Sesai e Aimã, e Talmai, os que nasceram a Anaque.^&#42;1^

[NOTE]
====
. Veja Núm 13:22 n.
====

[[v6-15-15]]

^<<v6-15-15,15>>^ Então subiu dali até os habitantes de Debir. (Ora, o nome anterior de Debir era Quiriate-Sefer.)

[[v6-15-16]]

^<<v6-15-16,16>>^ E Calebe passou a dizer: “Quem golpear Quiriate-Sefer e deveras a capturar, a este hei de dar minha filha Acsa por esposa.”

[[v6-15-17]]

^<<v6-15-17,17>>^ Então Otniel, filho de Quenaz, irmão de Calebe, a capturou. Portanto, deu-lhe sua filha Acsa por esposa.

[[v6-15-18]]

^<<v6-15-18,18>>^ E sucedeu que, quando ela ia para casa, instigava-o a pedir ao pai dela um campo. Ela bateu então palmas enquanto estava montada no jumento.^&#42;1^ Calebe disse-lhe, pois: “Que queres?”

[NOTE]
====
. Ou: “Então ela deslisou (apeou) do jumento.”
====

[[v6-15-19]]

^<<v6-15-19,19>>^ Ela disse, portanto: “Dá-me deveras uma bênção, pois me deste um pedaço de terra ao sul, e tens de dar-me Gulote-Maim.”^&#42;1^ Por conseguinte, deu-lhe Gulote Alta e Gulote Baixa.^&#42;2^

[NOTE]
====
. Significando “Bacias de Água”.
. Ou “a bacia superior e a bacia inferior”.
====

[[v6-15-20]]

^<<v6-15-20,20>>^ Esta foi a herança da tribo dos filhos de Judá, segundo as suas famílias.

[[v6-15-21]]

^<<v6-15-21,21>>^ E as cidades na extremidade da tribo dos filhos de Judá em direção ao termo de Edom, no sul, vieram a ser Cabzeel, e Éder, e Jagur,

[[v6-15-22]]

^<<v6-15-22,22>>^ e Quiná, e Dimona, e Adada,

[[v6-15-23]]

^<<v6-15-23,23>>^ e Quedes, e Hazor, e Itnã,

[[v6-15-24]]

^<<v6-15-24,24>>^ Zife e Telém, e Bealote,

[[v6-15-25]]

^<<v6-15-25,25>>^ e Hazor-Hadata, e Queriote-Esrom, isto é, Hazor,

[[v6-15-26]]

^<<v6-15-26,26>>^ Amão e Sema, e Moladá,

[[v6-15-27]]

^<<v6-15-27,27>>^ e Hazar-Gada, e Hesmom, e Bete-Pelete,

[[v6-15-28]]

^<<v6-15-28,28>>^ e Hazar-Sual, e Berseba, e Biziotiá,

[[v6-15-29]]

^<<v6-15-29,29>>^ Baalá e Ijim, e Ezem,

[[v6-15-30]]

^<<v6-15-30,30>>^ e Eltolade, e Quesil, e Hormá,

[[v6-15-31]]

^<<v6-15-31,31>>^ e Ziclague, e Madmana, e Sansana,

[[v6-15-32]]

^<<v6-15-32,32>>^ e Lebaote, e Silhim, e Aim, e Rimom; todas as cidades sendo vinte e nove, junto com os seus povoados.

[[v6-15-33]]

^<<v6-15-33,33>>^ Na Sefelá havia Estaol, e Zorá, e Asná,

[[v6-15-34]]

^<<v6-15-34,34>>^ e Zanoa, e En-Ganim, Tapua e Enão,

[[v6-15-35]]

^<<v6-15-35,35>>^ Jarmute e Adulão, Socó e Azeca,

[[v6-15-36]]

^<<v6-15-36,36>>^ e Saaraim, e Aditaim, e Gedera, e Gederotaim; quatorze cidades e seus povoados.

[[v6-15-37]]

^<<v6-15-37,37>>^ Zenã e Hadasa, e Migdal-Gade,

[[v6-15-38]]

^<<v6-15-38,38>>^ e Dileã, e Mispé, e Jocteel,

[[v6-15-39]]

^<<v6-15-39,39>>^ Laquis e Boscate, e Eglom,

[[v6-15-40]]

^<<v6-15-40,40>>^ e Cabom, e Lamão, e Quitlis,

[[v6-15-41]]

^<<v6-15-41,41>>^ e Gederote, Bete-Dagom e Naamá, e Maquedá; dezesseis cidades e seus povoados.

[[v6-15-42]]

^<<v6-15-42,42>>^ Libna e Eter, e Asã,

[[v6-15-43]]

^<<v6-15-43,43>>^ e Iftá, e Asná, e Nezibe,

[[v6-15-44]]

^<<v6-15-44,44>>^ e Queila, e Aczibe, e Maresa; nove cidades e seus povoados.

[[v6-15-45]]

^<<v6-15-45,45>>^ Ecrom e suas aldeias dependentes,^&#42;1^ e seus povoados.

[NOTE]
====
. Lit.: “suas filhas”.
====

[[v6-15-46]]

^<<v6-15-46,46>>^ De Ecrom para o oeste, tudo o que havia do lado de Asdode e seus povoados.

[[v6-15-47]]

^<<v6-15-47,47>>^ Asdode, suas aldeias dependentes e seus povoados; Gaza, suas aldeias dependentes e seus povoados, para baixo até o vale da torrente do Egito, e o Grande Mar^&#42;1^ e a região adjacente.

[NOTE]
====
. “O Grande Mar”, MmargemLXXSyVg; M: “o mar da fronteira; o mar fronteiriço”.
====

[[v6-15-48]]

^<<v6-15-48,48>>^ E na região montanhosa, Samir e Jatir, e Socó,

[[v6-15-49]]

^<<v6-15-49,49>>^ e Daná e Quiriate-Sana, isto é, Debir,

[[v6-15-50]]

^<<v6-15-50,50>>^ e Anabe, e Estemo, e Anim,

[[v6-15-51]]

^<<v6-15-51,51>>^ e Gósen, e Holom, e Gilo; onze cidades e seus povoados.

[[v6-15-52]]

^<<v6-15-52,52>>^ Arabe e Dumá, e Esã,

[[v6-15-53]]

^<<v6-15-53,53>>^ e Janim, e Bete-Tapua, e Afeca,

[[v6-15-54]]

^<<v6-15-54,54>>^ e Hunta, e Quiriate-Arba, isto é, Hébron, e Zior; nove cidades e seus povoados.

[[v6-15-55]]

^<<v6-15-55,55>>^ Maom, Carmelo e Zife, e Jutá,

[[v6-15-56]]

^<<v6-15-56,56>>^ e Jezreel, e Jocdeão, e Zanoa,

[[v6-15-57]]

^<<v6-15-57,57>>^ Caim, Gibeá e Timná; dez cidades e seus povoados.

[[v6-15-58]]

^<<v6-15-58,58>>^ Halul, Bete-Zur e Gedor,

[[v6-15-59]]

^<<v6-15-59,59>>^ e Maarate, e Bete-Anote, e Eltecom; seis cidades e seus povoados.

[[v6-15-60]]

^<<v6-15-60,60>>^ Quiriate-Baal, isto é, Quiriate-Jearim, e Rabá; duas cidades e seus povoados.

[[v6-15-61]]

^<<v6-15-61,61>>^ No ermo: Bete-Arabá, Midim e Secacá,

[[v6-15-62]]

^<<v6-15-62,62>>^ e Nibsã e a Cidade do Sal, e En-Gedi; seis cidades e seus povoados.

[[v6-15-63]]

^<<v6-15-63,63>>^ Quanto aos jebuseus que moravam em Jerusalém, os filhos de Judá não os puderam desalojar; e os jebuseus continuam morando com os filhos de Judá em Jerusalém até o dia de hoje.

'''

xref:006-josue/006-josue-014.adoc#v6-14-0[&#60; Capítulo Anterior] | <<v6-15-0,Topo>> | xref:006-josue/006-josue-016.adoc#v6-16-0[Próximo Capítulo &#62;]