include::./index.adoc[]

[[v6-7-0]]
=== Josué, 7
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v6-7-1]]

^<<v6-7-1,1>>^ E os filhos de Israel foram praticar um ato de infidelidade com respeito à coisa devotada à destruição, visto que Acã,^&#42;1^ filho de Carmi, filho de Zabdi, filho de Zerá, da tribo de Judá, tomou algo da coisa devotada à destruição. Em vista disso acendeu-se a ira de Jeová contra os filhos de Israel.

[NOTE]
====
. “Acã.” Hebr.: ‛A·khán; em 1Cr 2:7: “Acar”, palavras que ambas significam “Causador de Banimento; Causador de Dificuldade”. Veja 1Cr 2:7 n.
====

[[v6-7-2]]

^<<v6-7-2,2>>^ Josué enviou então homens de Jericó a Ai, que está perto de Bete-Áven, ao oriente de Betel, e disse-lhes: “Subi e espionai a terra.” Por conseguinte, os homens subiram e espionaram Ai.

[[v6-7-3]]

^<<v6-7-3,3>>^ Depois voltaram a Josué e lhe disseram: “Não suba todo o povo. Subam cerca de dois mil homens ou cerca de três mil homens e golpeiem Ai. Não fatigues todo o povo com a ida para lá, pois eles são poucos.”

[[v6-7-4]]

^<<v6-7-4,4>>^ De modo que subiram para lá cerca de três mil homens do povo, mas puseram-se em fuga diante dos homens de Ai.

[[v6-7-5]]

^<<v6-7-5,5>>^ E os homens de Ai chegaram a golpear cerca de trinta e seis homens deles, e foram persegui-los desde diante do portão até Sebarim,^&#42;1^ e continuaram a golpeá-los na descida. Em conseqüência, o coração do povo começou a derreter-se e ficou como água.

[NOTE]
====
. Significando “Pedreiras”.
====

[[v6-7-6]]

^<<v6-7-6,6>>^ Em vista disso, Josué rasgou as suas capas e lançou-se com a sua face por terra diante da arca de Jeová, até à noitinha, ele e os anciãos de Israel, e punham pó sobre as suas cabeças.

[[v6-7-7]]

^<<v6-7-7,7>>^ E Josué prosseguiu, dizendo: “Ai! Soberano Senhor Jeová, por que trouxeste este povo desde lá através do Jordão só para nos entregar na mão dos amorreus, para que nos destruam? E se tão-somente nos tivéssemos resolvido e continuado a morar no outro lado do Jordão!

[[v6-7-8]]

^<<v6-7-8,8>>^ Perdão, ó Jeová,^&#42;1^ mas o que posso dizer depois de Israel ter virado as costas diante dos seus inimigos?

[NOTE]
====
. Uma das 134 mudanças de YHWH para ’Adho·naí feitas pelos escribas. Veja Ap. 1B.
====

[[v6-7-9]]

^<<v6-7-9,9>>^ E os cananeus e todos os habitantes do país ouvirão isso, e certamente nos cercarão e deceparão o nosso nome da terra; e o que farás tu para com o teu grande nome?”

[[v6-7-10]]

^<<v6-7-10,10>>^ Jeová, por sua vez, disse a Josué: “Levanta-te, ó tu! Por que é que te estás lançando com a tua face [por terra]?

[[v6-7-11]]

^<<v6-7-11,11>>^ Israel pecou, e eles infringiram também meu pacto que lhes ordenei; e tomaram também da coisa devotada à destruição, e também furtaram e também o mantiveram secreto, e também o puseram entre os seus próprios objetos.

[[v6-7-12]]

^<<v6-7-12,12>>^ E os filhos de Israel não se poderão levantar contra os seus inimigos. Hão de virar as costas diante dos seus inimigos, visto que se tornaram algo devotado à destruição. Não mais mostrarei estar convosco, a menos que aniquileis do vosso meio a coisa devotada à destruição.

[[v6-7-13]]

^<<v6-7-13,13>>^ Levanta-te! Santifica o povo, e tens de dizer: ‘Santificai-vos amanhã, pois assim disse Jeová, o Deus de Israel: “Há uma coisa devotada à destruição no vosso meio, ó Israel. Não te poderás levantar contra os teus inimigos até que tenhais removido do vosso meio a coisa devotada à destruição.

[[v6-7-14]]

^<<v6-7-14,14>>^ E de manhã vos tereis de apresentar tribo por tribo, e tem de dar-se que a tribo que Jeová selecionar chegar-se-á família por família, e a família que Jeová selecionar chegar-se-á casa por casa, e a casa que Jeová selecionar chegar-se-á varão vigoroso por varão vigoroso.

[[v6-7-15]]

^<<v6-7-15,15>>^ E tem de suceder que aquele que for apanhado com a coisa devotada à destruição será queimado em fogo, ele e tudo o que for dele, porque transgrediu o pacto de Jeová e porque cometeu uma ignominiosa insensatez em Israel.”’”

[[v6-7-16]]

^<<v6-7-16,16>>^ Josué levantou-se então de manhã cedo e fez Israel chegar perto, tribo por tribo dele, e foi selecionada a tribo de Judá.

[[v6-7-17]]

^<<v6-7-17,17>>^ A seguir fez as famílias de Judá chegar perto e selecionou a família dos zeraítas, fazendo depois a família dos zeraítas chegar perto, varão vigoroso por varão vigoroso,^&#42;1^ e foi selecionado Zabdi.

[NOTE]
====
. Lit.: “pelos varões vigorosos”. Hebr.: lag·geva·rím; gr.: ka·tá án·dra, usada em sentido distributivo; SyVgc e seis mss. hebr.: “família por família”.
====

[[v6-7-18]]

^<<v6-7-18,18>>^ Por fim fez chegar perto os da casa dele, varão vigoroso por varão vigoroso, e foi selecionado Acã, filho de Carmi, filho de Zabdi, filho de Zerá, da tribo de Judá.

[[v6-7-19]]

^<<v6-7-19,19>>^ Josué disse então a Acã: “Meu filho,^&#42;1^ por favor, dá glória a Jeová, o Deus de Israel, e faze confissão a ele, e por favor, dize-me: O que fizeste? Não mo ocultes.”

[NOTE]
====
. “Meu filho”, MVg; LXXSy omitem isso.
====

[[v6-7-20]]

^<<v6-7-20,20>>^ Nisso Acã respondeu a Josué e disse: “De fato, eu é que pequei contra Jeová, o Deus de Israel, e fiz assim e assim.

[[v6-7-21]]

^<<v6-7-21,21>>^ Quando cheguei a ver no meio do despojo um manto oficial de Sinear, de bom aspecto, e duzentos siclos^&#42;1^ de prata e um lingote de ouro, cujo peso era de cinqüenta siclos, então os desejei e os tomei, e eis que se acham encobertos na terra, no meio da minha tenda, com o dinheiro^&#42;2^ por baixo dele.”^&#42;3^

[NOTE]
====
. Veja Ap. 8A.
. Ou “prata”.
. “Dele”, isto é, o “manto”.
====

[[v6-7-22]]

^<<v6-7-22,22>>^ Josué enviou imediatamente mensageiros e estes foram correndo até a tenda, e eis que estava encoberto na sua tenda com o dinheiro por baixo dele.

[[v6-7-23]]

^<<v6-7-23,23>>^ Tiraram-nos, pois, do meio da tenda e trouxeram-nos a Josué e a todos os filhos de Israel, e despejaram-nos diante de Jeová.

[[v6-7-24]]

^<<v6-7-24,24>>^ Josué, e todo o Israel com ele, tomou então Acã, filho de Zerá, e a prata, e o manto oficial, e o lingote de ouro, e seus filhos, e suas filhas, e seu touro, e seu jumento, e seu rebanho, e sua tenda, e tudo o que era seu, e os levaram para cima à baixada de Acor.

[[v6-7-25]]

^<<v6-7-25,25>>^ Josué disse então: “Por que nos trouxeste o banimento? Neste dia Jeová te banirá.” Nisso todo o Israel foi matá-lo a pedradas; depois queimaram-nos em fogo. Assim os mataram a pedradas.

[[v6-7-26]]

^<<v6-7-26,26>>^ E passaram a levantar sobre ele um grande montão de pedras, até o dia de hoje. Em vista disso, Jeová se desviou da sua ira ardente. É por isso que este lugar é chamado pelo nome de Baixada de Acor^&#42;1^ até o dia de hoje.

[NOTE]
====
. Significando “Banimento; Dificuldade”.
====

'''

xref:006-josue/006-josue-006.adoc#v6-6-0[&#60; Capítulo Anterior] | <<v6-7-0,Topo>> | xref:006-josue/006-josue-008.adoc#v6-8-0[Próximo Capítulo &#62;]