include::./index.adoc[]

[[v6-11-0]]
=== Josué, 11
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v6-11-1]]

^<<v6-11-1,1>>^ E sucedeu que, assim que Jabim, rei de Hazor, ouviu isso, foi enviar [mensageiros] a Jobabe, rei de Madom, e ao rei de Sinrom, e ao rei de Acsafe,

[[v6-11-2]]

^<<v6-11-2,2>>^ e aos reis que estavam ao norte, na região montanhosa e nas planícies desérticas ao sul de Quinerete, e na Sefelá, e nos serros de Dor, ao oeste,

[[v6-11-3]]

^<<v6-11-3,3>>^ os cananeus ao leste e ao oeste, e os amorreus e os hititas, e os perizeus, e os jebuseus na região montanhosa, e os heveus ao sopé do Hermom, na terra de Mispá.

[[v6-11-4]]

^<<v6-11-4,4>>^ Portanto, eles saíram, e com eles todos os seus acampamentos, um povo tão numeroso em multidão como os grãos de areia que há à beira do mar, e muitíssimos cavalos e carros de guerra.

[[v6-11-5]]

^<<v6-11-5,5>>^ Todos estes reis se encontraram então por combinação, e vieram e se acamparam juntos perto das águas de Merom para lutar contra Israel.

[[v6-11-6]]

^<<v6-11-6,6>>^ Por isso Jeová disse a Josué: “Não tenhas medo por causa deles, pois amanhã, por esta hora, entregarei a todos eles como mortos a Israel. Jarretarás os seus cavalos e queimarás no fogo os seus carros.”

[[v6-11-7]]

^<<v6-11-7,7>>^ E Josué e toda a gente de guerra com ele passou a vir de surpresa contra eles junto às águas de Merom e a lançar-se sobre eles.

[[v6-11-8]]

^<<v6-11-8,8>>^ Jeová os entregou então na mão de Israel, e foram golpeá-los e persegui-los até à populosa Sídon e Misrefote-Maim, e o vale plano de Mispé ao leste; e continuaram a golpeá-los até que não lhes deixaram restar sobrevivente.

[[v6-11-9]]

^<<v6-11-9,9>>^ Depois lhes fez Josué assim como Jeová lhe dissera: jarretou seus cavalos e queimou seus carros no fogo.

[[v6-11-10]]

^<<v6-11-10,10>>^ Ademais, naquele tempo Josué deu volta e capturou Hazor; e golpeou seu rei com a espada, visto que Hazor tinha sido antes a cabeça de todos estes reinos.

[[v6-11-11]]

^<<v6-11-11,11>>^ E foram^&#42;1^ golpear toda alma que havia nela com o fio da espada, devotando[-as] à destruição.^&#42;2^ Não sobrou absolutamente nada que respirasse, e ele queimou Hazor com fogo.

[NOTE]
====
. “Foram”, MLXXB; LXXASyVg: “foi”.
. “Devotando[-as] à destruição.” No hebr., esta frase é um verbo no infinitivo absoluto, indefinido quanto ao tempo e impessoal.
====

[[v6-11-12]]

^<<v6-11-12,12>>^ E Josué capturou todas as cidades destes reis e todos os seus reis, e foi golpeá-los com o fio da espada. Devotou-os à destruição, assim como lhe ordenara Moisés, servo de Jeová.

[[v6-11-13]]

^<<v6-11-13,13>>^ Israel apenas não queimou a todas as cidades que estavam sobre os seus próprios montes de terra, exceto Hazor, que Josué queimou isoladamente.

[[v6-11-14]]

^<<v6-11-14,14>>^ E os filhos de Israel saquearam para si todo o despojo destas cidades e os animais domésticos. Foi somente a todo o gênero humano que golpearam com o fio da espada até que os aniquilaram. Não deixaram restar quem respirasse.

[[v6-11-15]]

^<<v6-11-15,15>>^ Assim como Jeová ordenara a Moisés, seu servo, assim Moisés ordenou a Josué, e assim Josué fez. Não tirou nenhuma palavra de tudo o que Jeová ordenara a Moisés.

[[v6-11-16]]

^<<v6-11-16,16>>^ E Josué passou a tomar toda esta terra, a região montanhosa e todo o Negebe, e toda a terra de Gósen, e a Sefelá, e o Arabá, e a região montanhosa de Israel e sua Sefelá,

[[v6-11-17]]

^<<v6-11-17,17>>^ desde o monte Halaque, que sobe até Seir, e até Baal-Gade, no vale plano do Líbano, ao sopé do monte Hermom, e capturou todos os seus reis, e foi golpeá-los e entregá-los à morte.

[[v6-11-18]]

^<<v6-11-18,18>>^ Foi por muitos dias que Josué travou guerra com todos estes reis.

[[v6-11-19]]

^<<v6-11-19,19>>^ Não se mostrou haver nenhuma cidade que fizesse paz com os filhos de Israel, exceto os heveus que habitavam em Gibeão. A todas as outras tomaram por meio de guerra.

[[v6-11-20]]

^<<v6-11-20,20>>^ Pois, mostrou ser a maneira de agir de Jeová, deixar seus corações ficar obstinados para que declarassem guerra à Israel, a fim de que os devotasse à destruição, para que não obtivessem consideração favorável, mas para que os aniquilasse, assim como Jeová ordenara a Moisés.

[[v6-11-21]]

^<<v6-11-21,21>>^ Outrossim, naquele tempo específico Josué foi e decepou os anaquins da região montanhosa, de Hébron, de Debir, de Anabe e de toda a região montanhosa de Judá e de toda a região montanhosa de Israel. Josué os devotou à destruição junto com as suas cidades.

[[v6-11-22]]

^<<v6-11-22,22>>^ Não sobraram anaquins na terra dos filhos de Israel. Restaram somente em Gaza, em Gate e em Asdode.

[[v6-11-23]]

^<<v6-11-23,23>>^ De modo que Josué tomou todo o país, segundo tudo o que Jeová prometera a Moisés, e Josué o deu a Israel como herança, segundo as suas partes, conforme as suas tribos. E o país teve sossego da guerra.

'''

xref:006-josue/006-josue-010.adoc#v6-10-0[&#60; Capítulo Anterior] | <<v6-11-0,Topo>> | xref:006-josue/006-josue-012.adoc#v6-12-0[Próximo Capítulo &#62;]