include::./index.adoc[]

[[v6-12-0]]
=== Josué, 12
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v6-12-1]]

^<<v6-12-1,1>>^ Ora, estes são os reis do país, que os filhos de Israel derrotaram e de cuja terra tomaram posse no lado do Jordão que dá para o nascente do sol, desde o vale da torrente do Árnon para cima até o monte Hermom, e todo o Arabá em direção ao nascente:^&#42;1^

[NOTE]
====
. Ou “leste”.
====

[[v6-12-2]]

^<<v6-12-2,2>>^ Síon, rei dos amorreus, que morava em Hésbon, dominando desde Aroer, que se acha na beira do vale da torrente do Árnon, e o meio do vale da torrente, e metade de Gileade, até Jaboque, o vale da torrente, o termo dos filhos de Amom,

[[v6-12-3]]

^<<v6-12-3,3>>^ e o Arabá até o mar de Quinerete para o leste e até o mar do Arabá, o Mar Salgado, para o leste em direção a Bete-Jesimote, e para o sul, abaixo das encostas do Pisga.

[[v6-12-4]]

^<<v6-12-4,4>>^ E o território de Ogue, rei de Basã, do que sobrou dos refains, que morava em Astarote e em Edrei,

[[v6-12-5]]

^<<v6-12-5,5>>^ e que dominava no monte Hermom e em Salecá, e em todo o Basã, até o termo dos gesuritas e dos maacatitas, e metade de Gileade, até o território de Síon, rei de Hésbon.

[[v6-12-6]]

^<<v6-12-6,6>>^ Foi Moisés, servo de Jeová, e os filhos de Israel que os derrotaram, dando-o depois Moisés, servo de Jeová, como posse aos rubenitas e aos gaditas, e à meia tribo de Manassés.

[[v6-12-7]]

^<<v6-12-7,7>>^ E estes são os reis do país que Josué e os filhos de Israel derrotaram no lado do Jordão que dá para o oeste, desde Baal-Gade, no vale plano do Líbano, e até o monte Halaque, que sobe até Seir, dando-o depois Josué como posse às tribos de Israel, segundo as suas partes,

[[v6-12-8]]

^<<v6-12-8,8>>^ na região montanhosa, e na Sefelá, e no Arabá, e nas encostas, e no ermo, e no Negebe — os hititas, os amorreus e os cananeus, os perizeus, os heveus e os jebuseus:

[[v6-12-9]]

^<<v6-12-9,9>>^ O rei de Jericó, um; o rei de Ai, que estava ao lado de Betel, um;

[[v6-12-10]]

^<<v6-12-10,10>>^ o rei de Jerusalém, um; o rei de Hébron, um;

[[v6-12-11]]

^<<v6-12-11,11>>^ o rei de Jarmute, um; o rei de Laquis, um;

[[v6-12-12]]

^<<v6-12-12,12>>^ o rei de Eglom, um; o rei de Gezer, um;

[[v6-12-13]]

^<<v6-12-13,13>>^ o rei de Debir, um; o rei de Geder, um;

[[v6-12-14]]

^<<v6-12-14,14>>^ o rei de Hormá, um; o rei de Arade, um;

[[v6-12-15]]

^<<v6-12-15,15>>^ o rei de Libna, um; o rei de Adulão, um;

[[v6-12-16]]

^<<v6-12-16,16>>^ o rei de Maquedá, um; o rei de Betel, um;

[[v6-12-17]]

^<<v6-12-17,17>>^ o rei de Tapua, um; o rei de Héfer, um;

[[v6-12-18]]

^<<v6-12-18,18>>^ o rei de Afeque, um; o rei de Lassarom, um;

[[v6-12-19]]

^<<v6-12-19,19>>^ o rei de Madom, um; o rei de Hazor, um;

[[v6-12-20]]

^<<v6-12-20,20>>^ o rei de Sinrom-Merom,^&#42;1^ um; o rei de Acsafe, um;

[NOTE]
====
. “Sinrom-Merom”, M; Sy: “Sinrom e Merom”; LXXLVg: “Sinrom”.
====

[[v6-12-21]]

^<<v6-12-21,21>>^ o rei de Taanaque, um; o rei de Megido, um;

[[v6-12-22]]

^<<v6-12-22,22>>^ o rei de Quedes, um; o rei de Jocneão, no Carmelo, um;

[[v6-12-23]]

^<<v6-12-23,23>>^ o rei de Dor, no serro de Dor, um; o rei de Goim, em Gilgal,^&#42;1^ um;

[NOTE]
====
. Provavelmente Jiljulieh, ao norte do riacho Caná, na planície de Sarom. LXX: “Galiléia”.
====

[[v6-12-24]]

^<<v6-12-24,24>>^ o rei de Tirza, um;
todos os reis sendo trinta e um.

'''

xref:006-josue/006-josue-011.adoc#v6-11-0[&#60; Capítulo Anterior] | <<v6-12-0,Topo>> | xref:006-josue/006-josue-013.adoc#v6-13-0[Próximo Capítulo &#62;]