include::./index.adoc[]

[[v6-14-0]]
=== Josué, 14
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v6-14-1]]

^<<v6-14-1,1>>^ Ora, isto é o que os filhos de Israel tomaram como propriedade hereditária na terra de Canaã, que Eleazar, o sacerdote, e Josué, filho de Num, e os cabeças dos pais das tribos dos filhos de Israel os fizeram herdar.

[[v6-14-2]]

^<<v6-14-2,2>>^ Sua herança foi por sortes, assim como Jeová ordenara para as nove tribos e a meia tribo por intermédio de Moisés.

[[v6-14-3]]

^<<v6-14-3,3>>^ Pois, Moisés dera a herança das outras duas tribos e da outra meia tribo ao outro lado do Jordão; e aos levitas não deu herança no seu meio.

[[v6-14-4]]

^<<v6-14-4,4>>^ Porque os filhos de José se tinham tornado duas tribos, Manassés e Efraim, e aos levitas não se dera nenhum quinhão no país, a não ser cidades para morar e os pastios delas para o seu gado e seus bens.

[[v6-14-5]]

^<<v6-14-5,5>>^ Os filhos de Israel fizeram assim como Jeová ordenara a Moisés; e passaram a repartir a terra.

[[v6-14-6]]

^<<v6-14-6,6>>^ Os filhos de Judá se aproximaram então de Josué, em Gilgal, e Calebe, filho de Jefuné, o quenizeu, disse-lhe: “Tu mesmo bem sabes da palavra que Jeová falou a Moisés, o homem do [verdadeiro] Deus,^&#42;1^ no que se refere a mim e no que se refere a ti, em Cades-Barnéia.

[NOTE]
====
. “Do [verdadeiro] Deus.” Hebr.: ha- ’Elo·hím. Veja Ap. 1F.
====

[[v6-14-7]]

^<<v6-14-7,7>>^ Eu tinha quarenta anos de idade quando Moisés, servo de Jeová, me enviou de Cades-Barnéia para espionar o país, e vim trazer-lhe de volta notícia assim como estava no meu coração.

[[v6-14-8]]

^<<v6-14-8,8>>^ E meus irmãos, que subiram comigo, fizeram que o coração do povo se derretesse; mas eu, eu segui integralmente a Jeová, meu Deus.

[[v6-14-9]]

^<<v6-14-9,9>>^ Por conseguinte, Moisés jurou naquele dia, dizendo: ‘A terra em que teu pé pisou tornar-se-á tua e dos teus filhos como herança por tempo indefinido por teres seguido integralmente a Jeová, meu Deus.’

[[v6-14-10]]

^<<v6-14-10,10>>^ E agora, eis que Jeová me preservou vivo, assim como prometeu, durante estes quarenta e cinco anos desde que Jeová fez esta promessa a Moisés, quando Israel andou no ermo, e agora, eis que tenho hoje oitenta e cinco anos de idade.

[[v6-14-11]]

^<<v6-14-11,11>>^ Contudo, sou hoje tão forte como no dia em que Moisés me enviou. Como era meu poder então, assim é meu poder agora para a guerra, tanto para sair como para entrar.

[[v6-14-12]]

^<<v6-14-12,12>>^ E agora, dá-me deveras esta região montanhosa que Jeová prometeu naquele dia, pois tu mesmo ouviste naquele dia que havia ali os anaquins e grandes cidades fortificadas. Possivelmente, Jeová estará comigo e eu hei de desapossá-los, assim como Jeová prometeu.”

[[v6-14-13]]

^<<v6-14-13,13>>^ Nisso Josué o abençoou e deu Hébron por herança a Calebe, filho de Jefuné.

[[v6-14-14]]

^<<v6-14-14,14>>^ É por isso que Hébron veio a pertencer a Calebe, filho de Jefuné, o quenizeu, por herança até o dia de hoje, por ele ter seguido integralmente a Jeová, o Deus de Israel.

[[v6-14-15]]

^<<v6-14-15,15>>^ O nome anterior de Hébron era Quiriate-Arba ([tendo sido este Arba] o grande homem entre os anaquins).^&#42;1^ E o país teve sossego da guerra.

[NOTE]
====
. “Era a cidade de Arboque [LXXB: “Argobe”], sendo esta a metrópole dos anaquins”, LXX.
====

'''

xref:006-josue/006-josue-013.adoc#v6-13-0[&#60; Capítulo Anterior] | <<v6-14-0,Topo>> | xref:006-josue/006-josue-015.adoc#v6-15-0[Próximo Capítulo &#62;]