include::./index.adoc[]

[[v6-6-0]]
=== Josué, 6
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v6-6-1]]

^<<v6-6-1,1>>^ Ora, Jericó estava rigorosamente fechada por causa dos filhos de Israel; ninguém saía e ninguém entrava.

[[v6-6-2]]

^<<v6-6-2,2>>^ E Jeová prosseguiu, dizendo a Josué: “Vê, entreguei na tua mão Jericó e seu rei, os valentes poderosos.

[[v6-6-3]]

^<<v6-6-3,3>>^ E todos vós, homens de guerra, tendes de marchar em volta da cidade, rodeando^&#42;1^ a cidade uma vez. Assim deves fazer por seis dias.

[NOTE]
====
. “Rodeando.” No hebr., este verbo está no infinitivo absoluto, indefinido quanto ao tempo.
====

[[v6-6-4]]

^<<v6-6-4,4>>^ E sete sacerdotes devem carregar sete buzinas de carneiro adiante da Arca, e no sétimo dia deveis marchar sete vezes em volta da cidade e os sacerdotes devem tocar as buzinas.

[[v6-6-5]]

^<<v6-6-5,5>>^ E terá de acontecer que, quando fizerem soar o corno de carneiro, quando ouvirdes o som da buzina,^&#42;1^ então todo o povo deve dar um grande grito de guerra; e a muralha da cidade tem de cair rente ao chão, e o povo tem de subir, cada um diretamente na frente de si.”

[NOTE]
====
. Ou “o shofar”. Hebr.: hash·shoh·fár.
====

[[v6-6-6]]

^<<v6-6-6,6>>^ Por conseguinte, Josué, filho de Num, chamou os sacerdotes e disse-lhes: “Levantai a arca do pacto, e sete sacerdotes devem carregar sete buzinas de carneiro adiante da arca de Jeová.”

[[v6-6-7]]

^<<v6-6-7,7>>^ E prosseguiu,^&#42;1^ dizendo ao povo: “Passai adiante e marchai em volta da cidade, e a força equipada para a guerra deve passar adiante da arca de Jeová.”

[NOTE]
====
. “Prosseguiu”, TSyVg; M: “prosseguiram”.
====

[[v6-6-8]]

^<<v6-6-8,8>>^ Aconteceu, pois, assim como Josué dissera ao povo; e sete sacerdotes, carregando sete buzinas de carneiro diante de Jeová, passaram adiante e tocaram as buzinas, e a arca do pacto de Jeová os seguia.

[[v6-6-9]]

^<<v6-6-9,9>>^ E a força equipada para a guerra ia na frente dos sacerdotes que tocavam as buzinas, ao passo que a retaguarda seguia a Arca, tocando-se continuamente^&#42;1^ as buzinas.

[NOTE]
====
. “Tocando-se continuamente.” No hebr., estas palavras são dois verbos no infinitivo absoluto, indefinidos quanto ao tempo.
====

[[v6-6-10]]

^<<v6-6-10,10>>^ Ora, Josué ordenara ao povo, dizendo: “Não deveis nem gritar nem deixar ouvir as vossas vozes, e nenhuma palavra deve sair das vossas bocas até o dia em que eu vos disser: ‘Gritai!’ Então tereis de gritar.”

[[v6-6-11]]

^<<v6-6-11,11>>^ E ele fez a arca de Jeová marchar em volta da cidade, rodeando-a uma vez; depois foram ao acampamento e pernoitaram no acampamento.

[[v6-6-12]]

^<<v6-6-12,12>>^ Josué levantou-se então de manhã cedo e os sacerdotes foram carregar a arca de Jeová,

[[v6-6-13]]

^<<v6-6-13,13>>^ e sete sacerdotes andavam carregando sete buzinas de carneiro adiante da arca de Jeová [e] tocando continuamente as buzinas, e a força equipada para a guerra andava na frente deles, ao passo que a retaguarda seguia a arca de Jeová, tocando-se continuamente as buzinas.

[[v6-6-14]]

^<<v6-6-14,14>>^ E no dia seguinte foram marchar uma vez em volta da cidade, retornando depois ao acampamento. Assim fizeram por seis dias.

[[v6-6-15]]

^<<v6-6-15,15>>^ E no sétimo dia sucedeu que passaram a levantar-se cedo, assim que subiu a alva, e puseram-se a marchar desta maneira sete vezes em volta da cidade. Só neste dia é que marcharam sete vezes em volta da cidade.

[[v6-6-16]]

^<<v6-6-16,16>>^ E sucedeu, na sétima vez, que os sacerdotes tocaram as buzinas e Josué passou a dizer ao povo: “Gritai; porque Jeová vos entregou a cidade.

[[v6-6-17]]

^<<v6-6-17,17>>^ E a cidade tem de tornar-se algo devotado à destruição;^&#42;1^ ela com tudo o que há nela pertence a Jeová. Somente Raabe, a prostituta, pode continuar a viver, ela e todos os que estiverem com ela na casa, pois escondeu os mensageiros que enviamos.

[NOTE]
====
. Ou “algo condenado”.
====

[[v6-6-18]]

^<<v6-6-18,18>>^ Quanto a vós, mantende-vos tão-somente afastados da coisa devotada à destruição, para que não fiqueis com desejo^&#42;1^ e deveras tomeis algo da coisa devotada à destruição e deveras torneis o acampamento de Israel algo devotado à destruição, e façais vir o banimento sobre ele.

[NOTE]
====
. “Para que não fiqueis com desejo”, em harmonia com LXX, que reza: “para que, fixando vossa mente [nisso], (vós mesmos não tomeis)”; M: “para que não [o] devoteis à destruição”.
====

[[v6-6-19]]

^<<v6-6-19,19>>^ Mas toda a prata, e o ouro, e os objetos de cobre e de ferro são algo sagrado para Jeová. Deve ir ao tesouro de Jeová.”

[[v6-6-20]]

^<<v6-6-20,20>>^ Então, quando passaram a tocar as buzinas, o povo gritou. E sucedeu que, assim que o povo ouviu o som da buzina e o povo começou a dar um grande grito de guerra, então a muralha começou a cair rente ao chão. Após isso, o povo subiu à cidade, cada um diretamente na frente de si, e capturou a cidade.

[[v6-6-21]]

^<<v6-6-21,21>>^ E a tudo o que havia na cidade, desde o homem até a mulher, desde o moço até o velho, e até o touro, e o ovídeo, e o jumento, devotavam à destruição ao fio da espada.

[[v6-6-22]]

^<<v6-6-22,22>>^ E aos dois homens que tinham espionado o país Josué disse: “Entrai na casa da mulher, da prostituta, e de lá trazei para fora tanto a mulher como todos os seus, assim como lhe jurastes.”

[[v6-6-23]]

^<<v6-6-23,23>>^ Portanto, os moços que tinham feito a espionagem entraram e trouxeram para fora Raabe e seu pai, e sua mãe, e seus irmãos, e todos os seus, sim, trouxeram para fora todos os que eram da sua família; e passaram a situá-los fora do acampamento de Israel.

[[v6-6-24]]

^<<v6-6-24,24>>^ E queimaram a fogo a cidade e tudo o que nela havia. Somente a prata e o ouro, e os objetos de cobre e de ferro, entregaram ao tesouro da casa de Jeová.

[[v6-6-25]]

^<<v6-6-25,25>>^ E a Raabe, a prostituta, e aos da casa de seu pai e a todos os seus, Josué preservou vivos; e ela mora no meio de Israel até o dia de hoje, por ter escondido os mensageiros que Josué enviara para espionar Jericó.

[[v6-6-26]]

^<<v6-6-26,26>>^ Então, naquele tempo específico, Josué fez proclamar um juramento, dizendo: “Maldito perante Jeová seja o homem que se levantar e reconstruir esta cidade, sim, Jericó. Lance ele os alicerces dela pagando com a perda de seu primogênito e ponha-lhe as portas pagando com a perda de seu [filho] mais jovem.”

[[v6-6-27]]

^<<v6-6-27,27>>^ Jeová, pois, mostrou estar com Josué, e a sua fama veio a ser [conhecida] em toda a terra.

'''

xref:006-josue/006-josue-005.adoc#v6-5-0[&#60; Capítulo Anterior] | <<v6-6-0,Topo>> | xref:006-josue/006-josue-007.adoc#v6-7-0[Próximo Capítulo &#62;]