include::./index.adoc[]

[[v6-21-0]]
=== Josué, 21
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v6-21-1]]

^<<v6-21-1,1>>^ Os cabeças dos pais dos levitas aproximaram-se então de Eleazar, o sacerdote, e de Josué, filho de Num, e dos cabeças dos pais das tribos dos filhos de Israel,

[[v6-21-2]]

^<<v6-21-2,2>>^ e passaram a falar-lhes em Silo, na terra de Canaã, dizendo: “Jeová, por meio de Moisés, ordenou que se nos dessem cidades para morar, junto com os seus pastios para os nossos animais domésticos.”

[[v6-21-3]]

^<<v6-21-3,3>>^ Portanto, os filhos de Israel, por ordem de Jeová, deram aos levitas estas cidades e seus pastios, tirados da sua herança.

[[v6-21-4]]

^<<v6-21-4,4>>^ Saiu então a sorte para as famílias dos coatitas, e por sortes vieram a pertencer aos filhos de Arão, o sacerdote, dos levitas, treze cidades, da tribo de Judá, e da tribo dos simeonitas, e da tribo de Benjamim.

[[v6-21-5]]

^<<v6-21-5,5>>^ E para os filhos de Coate que sobraram havia, por sortes, dez cidades das famílias da tribo^&#42;1^ de Efraim, e da tribo de Dã, e da meia tribo de Manassés.

[NOTE]
====
. Segundo M; LXXSyVg: “[cidades] da tribo de”.
====

[[v6-21-6]]

^<<v6-21-6,6>>^ E para os filhos de Gérson havia, por sortes, treze cidades das famílias da tribo de Issacar, e da tribo de Aser, e da tribo de Naftali, e da meia tribo de Manassés em Basã.

[[v6-21-7]]

^<<v6-21-7,7>>^ Para os filhos de Merari, segundo as suas famílias, havia doze cidades, da tribo de Rubem, e da tribo de Gade, e da tribo de Zebulão.

[[v6-21-8]]

^<<v6-21-8,8>>^ Os filhos de Israel deram assim aos levitas, por sortes, estas cidades e seus pastios, assim como Jeová mandara por intermédio de Moisés.

[[v6-21-9]]

^<<v6-21-9,9>>^ Portanto, da tribo dos filhos de Judá e da tribo dos filhos de Simeão deram estas cidades que foram chamadas por nome,

[[v6-21-10]]

^<<v6-21-10,10>>^ e elas vieram a pertencer aos filhos de Arão das famílias dos coatitas, dos filhos de Levi, porque a primeira sorte veio a ser a deles.

[[v6-21-11]]

^<<v6-21-11,11>>^ De modo que lhes deram Quiriate-Arba ([este Arba sendo] o pai de Anaque), isto é, Hébron, na região montanhosa de Judá, e seus pastios ao redor dela;

[[v6-21-12]]

^<<v6-21-12,12>>^ e o campo da cidade e seus povoados deram a Calebe, filho de Jefuné, como sua propriedade.

[[v6-21-13]]

^<<v6-21-13,13>>^ E aos filhos de Arão, o sacerdote, deram a cidade de refúgio para o homicida, a saber, Hébron, e seus pastios, bem como Libna e seus pastios,

[[v6-21-14]]

^<<v6-21-14,14>>^ e Jatir e seus pastios, e Estemoa e seus pastios,

[[v6-21-15]]

^<<v6-21-15,15>>^ e Holom^&#42;1^ e seus pastios, e Debir e seus pastios,

[NOTE]
====
. “Hilém” em 1Cr 6:58.
====

[[v6-21-16]]

^<<v6-21-16,16>>^ e Aim^&#42;1^ e seus pastios, e Jutá e seus pastios, Bete-Semes e seus pastios; nove cidades destas duas tribos.

[NOTE]
====
. “Asã” em 15:42; 19:7; 1Cr 6:59.
====

[[v6-21-17]]

^<<v6-21-17,17>>^ E da tribo de Benjamim: Gibeão e seus pastios, Geba e seus pastios,

[[v6-21-18]]

^<<v6-21-18,18>>^ Anatote e seus pastios, e Almom^&#42;1^ e seus pastios; quatro cidades.

[NOTE]
====
. “Alemete” em 1Cr 6:60.
====

[[v6-21-19]]

^<<v6-21-19,19>>^ Todas as cidades dos filhos de Arão, os sacerdotes, eram treze cidades e seus pastios.

[[v6-21-20]]

^<<v6-21-20,20>>^ E para as famílias dos filhos de Coate, os levitas que sobraram dentre os filhos de Coate, veio a haver pela sua sorte cidades da tribo de Efraim.

[[v6-21-21]]

^<<v6-21-21,21>>^ Por conseguinte, deram-lhes a cidade de refúgio para o homicida, a saber, Siquém e seus pastios na região montanhosa de Efraim, e Gezer e seus pastios,

[[v6-21-22]]

^<<v6-21-22,22>>^ e Quibzaim^&#42;1^ e seus pastios, e Bete-Horom e seus pastios; quatro cidades.

[NOTE]
====
. “Jocmeão” em 1Cr 6:68.
====

[[v6-21-23]]

^<<v6-21-23,23>>^ E da tribo de Dã: Elteque e seus pastios, Gibetom e seus pastios,

[[v6-21-24]]

^<<v6-21-24,24>>^ Aijalom e seus pastios, Gate-Rimom e seus pastios; quatro cidades.

[[v6-21-25]]

^<<v6-21-25,25>>^ E da meia tribo de Manassés: Taanaque e seus pastios, e Gate-Rimom e seus pastios; duas cidades.

[[v6-21-26]]

^<<v6-21-26,26>>^ Todas as cidades junto com os seus pastios que eram das famílias dos filhos de Coate que sobraram eram dez.

[[v6-21-27]]

^<<v6-21-27,27>>^ E para os filhos de Gérson, das famílias dos levitas, havia da meia tribo de Manassés a cidade de refúgio para o homicida, a saber, Golã, em Basã, e seus pastios, e Beesterá^&#42;1^ e seus pastios; duas cidades.

[NOTE]
====
. “Astarote” em 1Cr 6:71.
====

[[v6-21-28]]

^<<v6-21-28,28>>^ E da tribo de Issacar: Quisiom e seus pastios, Daberate e seus pastios,

[[v6-21-29]]

^<<v6-21-29,29>>^ Jarmute^&#42;1^ e seus pastios, En-Ganim e seus pastios; quatro cidades.

[NOTE]
====
. “Remete” em 19:21; em 1Cr 6:73: “Ramote”.
====

[[v6-21-30]]

^<<v6-21-30,30>>^ E da tribo de Aser: Misal e seus pastios, Abdom e seus pastios,

[[v6-21-31]]

^<<v6-21-31,31>>^ Helcate e seus pastios, e Reobe e seus pastios; quatro cidades.

[[v6-21-32]]

^<<v6-21-32,32>>^ E da tribo de Naftali: a cidade de refúgio para o homicida, a saber, Quedes na Galiléia^&#42;1^ e seus pastios, e Hamote-Dor e seus pastios, e Cartã^&#42;2^ e seus pastios; três cidades.

[NOTE]
====
. Veja 20:7 n.: “Galiléia”.
. “Quiriataim” em 1Cr 6:76.
====

[[v6-21-33]]

^<<v6-21-33,33>>^ Todas as cidades dos gersonitas, segundo as suas famílias, eram treze cidades e seus pastios.

[[v6-21-34]]

^<<v6-21-34,34>>^ E as famílias dos filhos de Merari, os levitas que sobraram, tinham da tribo de Zebulão: Jocneão e seus pastios, Carta e seus pastios,

[[v6-21-35]]

^<<v6-21-35,35>>^ Dimna^&#42;1^ e seus pastios, Naalal e seus pastios; quatro cidades.

[NOTE]
====
. “Rimono” em 1Cr 6:77.
====

[[v6-21-36]]

^<<v6-21-36,36>>^ E da tribo de Rubem: Bezer e seus pastios, e Jaaz e seus pastios,

[[v6-21-37]]

^<<v6-21-37,37>>^ Quedemote e seus pastios, e Mefaate e seus pastios; quatro cidades.^&#42;1^

[NOTE]
====
. Vv. 36 e 37 seguem alguns mss. hebr., LXXSyVg e 1Cr 6:63, 78, 79 (Sy menciona essas quatro cidades, começando no v. 34); Al, Ca e Leningrad B 19A omitem os vv. 36 e 37, pelo visto por um erro de escriba cometido porque tanto o v. 35 como o v. 37 terminam com “quatro cidades”.
====

[[v6-21-38]]

^<<v6-21-38,38>>^ E da tribo de Gade: a cidade de refúgio para o homicida, a saber, Ramote em Gileade e seus pastios, e Maanaim e seus pastios,

[[v6-21-39]]

^<<v6-21-39,39>>^ Hésbon e seus pastios, Jázer e seus pastios; todas as cidades sendo quatro.

[[v6-21-40]]

^<<v6-21-40,40>>^ Todas as cidades que vieram a pertencer aos filhos de Merari, segundo as suas famílias, os que sobraram das famílias dos levitas, foram, como a sua sorte, doze cidades.

[[v6-21-41]]

^<<v6-21-41,41>>^ Todas as cidades dos levitas no meio da propriedade dos filhos de Israel foram quarenta e oito cidades junto com os seus pastios.

[[v6-21-42]]

^<<v6-21-42,42>>^ Cada uma destas cidades veio a ser uma cidade junto com os seus pastios ao redor — assim foi com todas estas cidades.

[[v6-21-43]]

^<<v6-21-43,43>>^ Jeová deu, pois, a Israel toda a terra que havia jurado dar aos seus antepassados, e eles passaram a tomar posse dela e a morar nela.

[[v6-21-44]]

^<<v6-21-44,44>>^ Além disso, Jeová lhes deu descanso em todo o redor, segundo tudo o que havia jurado aos seus antepassados, e nem mesmo um de todos os seus inimigos se manteve de pé diante deles. Jeová lhes entregou na mão todos os seus inimigos.

[[v6-21-45]]

^<<v6-21-45,45>>^ Não falhou nem uma única de todas as boas promessas que Jeová fizera à casa de Israel; tudo se cumpriu.

'''

xref:006-josue/006-josue-020.adoc#v6-20-0[&#60; Capítulo Anterior] | <<v6-21-0,Topo>> | xref:006-josue/006-josue-022.adoc#v6-22-0[Próximo Capítulo &#62;]