include::./index.adoc[]

[[v19-58-0]]
=== Salmos, 58
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

_Ao regente. “Não arruínes.” De Davi. Mictão.^&#42;1^_

[[v19-58-1]]

^<<v19-58-1,1>>^ [No vosso] silêncio, podeis realmente falar sobre a própria justiça?
Podeis mesmo julgar em retidão, ó filhos dos homens?^&#42;1^

[NOTE]
====
. Ou “homem terreno”. Hebr.: ’a·dhám.
====

[[v19-58-2]]

^<<v19-58-2,2>>^ Antes, quanta injustiça flagrante praticais na terra com o coração
[E] preparais a estrada para a própria violência das vossas mãos!

[[v19-58-3]]

^<<v19-58-3,3>>^ Os iníquos têm sido depravados desde a madre;
Andaram vagueando desde o ventre;
Falam mentiras.

[[v19-58-4]]

^<<v19-58-4,4>>^ A peçonha deles é como a peçonha da serpente,
Estão surdos como a naja que tapa o ouvido,

[[v19-58-5]]

^<<v19-58-5,5>>^ Que não quer escutar a voz dos encantadores,
Embora alguém sábio faça o encantamento.^&#42;1^

[NOTE]
====
. Veja Ap. 7A a respeito de cobras reagirem a sons.
====

[[v19-58-6]]

^<<v19-58-6,6>>^ Ó Deus, quebra-lhes os dentes na sua boca.
Rebenta as próprias mandíbulas de leões novos jubados, ó Jeová.

[[v19-58-7]]

^<<v19-58-7,7>>^ Que se dissolvam como em águas que seguem seu caminho;
Que ele entese [o arco para] as suas flechas ao tombarem.

[[v19-58-8]]

^<<v19-58-8,8>>^ Ele anda como a lesma que se dilui;^&#42;1^
Iguais ao aborto duma mulher, eles certamente não observarão o sol.

[NOTE]
====
. Ou “deixando uma trilha pegajosa”.
====

[[v19-58-9]]

^<<v19-58-9,9>>^ Antes que as vossas panelas sintam o espinheiro-de-casca-branca [queimando],
Tanto o verde como o que queima, ele os arrebatará como um vento tempestuoso.

[[v19-58-10]]

^<<v19-58-10,10>>^ O justo se alegrará por ter observado a vingança.
Banhará os seus passos no sangue do iníquo.

[[v19-58-11]]

^<<v19-58-11,11>>^ E a humanidade dirá: “De fato, há frutos para o justo.
De fato, há um Deus que julga^&#42;1^ na terra.”

[NOTE]
====
. “Que julga.” Hebr.: sho·fetím, pl., para concordar com ’Elo·hím, “Deus”, que está no pl. para denotar excelência e grandiosidade; LXXSyVg apresentam o particípio do verbo hebr. no sing.: “que os está julgando”.
====

'''

xref:019-salmo/019-salmo-057.adoc#v19-57-0[&#60; Capítulo Anterior] | <<v19-58-0,Topo>> | xref:019-salmo/019-salmo-059.adoc#v19-59-0[Próximo Capítulo &#62;]