include::./index.adoc[]

[[v19-27-0]]
=== Salmos, 27
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

_De Davi._

[[v19-27-1]]

^<<v19-27-1,1>>^ Jeová é a minha luz e a minha salvação.
De quem terei medo?
Jeová é o baluarte da minha vida.
De quem terei pavor?

[[v19-27-2]]

^<<v19-27-2,2>>^ Quando os malfeitores se chegaram a mim para devorar minha carne,
Sendo eles pessoalmente meus adversários e meus inimigos,
Eles mesmos tropeçaram e caíram.

[[v19-27-3]]

^<<v19-27-3,3>>^ Ainda que um acampamento arme tendas contra mim,
Meu coração não temerá.
Ainda que estoure uma guerra contra mim,
Mesmo assim estarei confiante.

[[v19-27-4]]

^<<v19-27-4,4>>^ Uma coisa pedi a Jeová —
É o que procurarei:
Morar na casa de Jeová todos os dias da minha vida,
Para contemplar a afabilidade de Jeová
E olhar com apreciação para o seu templo.^&#42;1^

[NOTE]
====
. “Para o seu templo.” Hebr.: beheh·kha·lóh; gr.: na·ón; lat.: tém·plum. Compare isso com 2Rs 20:18 n. Veja Mt 23:16 n.
====

[[v19-27-5]]

^<<v19-27-5,5>>^ Porque no dia da calamidade ele me ocultará no seu abrigo;
Esconder-me-á no lugar secreto da sua tenda;
Ele me porá alto sobre uma rocha.

[[v19-27-6]]

^<<v19-27-6,6>>^ E agora a minha cabeça ficará elevada acima dos meus inimigos ao redor;
E eu vou sacrificar na sua tenda sacrifícios de gritos de alegria;
Vou cantar e entoar melodias a Jeová.

[[v19-27-7]]

^<<v19-27-7,7>>^ Ouve, ó Jeová, quando chamo com a minha voz,
E mostra-me favor e responde-me.

[[v19-27-8]]

^<<v19-27-8,8>>^ Meu coração disse a teu respeito: “Procurai achar a minha face.”
Procurarei achar a tua face, ó Jeová.

[[v19-27-9]]

^<<v19-27-9,9>>^ Não escondas de mim a tua face.
Não repilas o teu servo em ira.
Tens de tornar-te meu auxílio.
Não me abandones e não me deixes, ó meu Deus de salvação.

[[v19-27-10]]

^<<v19-27-10,10>>^ Caso meu próprio pai e minha própria mãe me abandonassem,
O próprio Jeová me acolheria.

[[v19-27-11]]

^<<v19-27-11,11>>^ Instrui-me no teu caminho, ó Jeová,
E guia-me na vereda da retidão por causa dos meus adversários hostis.

[[v19-27-12]]

^<<v19-27-12,12>>^ Não me entregues à alma dos meus adversários;
Pois levantaram-se contra mim testemunhas falsas
E aquele que lança de si violência.

[[v19-27-13]]

^<<v19-27-13,13>>^ Se eu não^&#42;1^ tivesse tido fé em ver a bondade de Jeová na terra dos viventes . . .!

[NOTE]
====
. “Se . . . não.” Hebr.: lu·lé’; LXXSyVg e cinco mss. hebr. omitem isso. No M, esta palavra foi marcada com pontos extraordinários pelos soferins. Veja Ap. 2A.
====

[[v19-27-14]]

^<<v19-27-14,14>>^ Espera em Jeová; sê corajoso e fortifique-se teu coração.
Sim, espera em Jeová.

'''

xref:019-salmo/019-salmo-026.adoc#v19-26-0[&#60; Capítulo Anterior] | <<v19-27-0,Topo>> | xref:019-salmo/019-salmo-028.adoc#v19-28-0[Próximo Capítulo &#62;]