include::./index.adoc[]

[[v19-119-0]]
=== Salmos, 119
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

_א [Álefe]^&#42;1^_

[[v19-119-1]]

^<<v19-119-1,1>>^ ^&#42;1^ Felizes os sem defeito no [seu]  caminho,
Os que andam na lei de  Jeová.

[NOTE]
====
. Este é um salmo acróstico ou alfabético com 22 estrofes (ou seções), para corresponder às 22 letras do alfabeto hebr.; cada estrofe (ou seção) contém oito vv.
====

[[v19-119-2]]

^<<v19-119-2,2>>^ Felizes os que observam as suas advertências;
Continuam a buscá-lo de todo o coração.

[[v19-119-3]]

^<<v19-119-3,3>>^ Realmente, eles não praticaram nenhuma injustiça.
Têm andado nos Seus caminhos.

[[v19-119-4]]

^<<v19-119-4,4>>^ Tu mesmo ordenaste as tuas ordens
Para serem cuidadosamente guardadas.

[[v19-119-5]]

^<<v19-119-5,5>>^ Quisera eu que meus caminhos fossem firmemente estabelecidos
Para guardar teus regulamentos!

[[v19-119-6]]

^<<v19-119-6,6>>^ Neste caso não me envergonharia
Ao olhar para todos os teus mandamentos.

[[v19-119-7]]

^<<v19-119-7,7>>^ Elogiar-te-ei em retidão de coração
Ao aprender as tuas justas decisões judiciais.

[[v19-119-8]]

^<<v19-119-8,8>>^ Continuo a guardar os teus regulamentos.
Oh! não me abandones inteiramente.

_ב [Bete]^&#42;1^_

[[v19-119-9]]

^<<v19-119-9,9>>^ Como purificará um moço a sua vereda?
Por estar vigilante segundo a tua palavra.^&#42;1^

[NOTE]
====
. Ou: “purificará . . . a sua vereda para estar vigilante segundo a tua palavra?”
====

[[v19-119-10]]

^<<v19-119-10,10>>^ Busquei-te de todo o meu coração.
Não me faças transviar-me dos teus mandamentos.

[[v19-119-11]]

^<<v19-119-11,11>>^ Entesourei^&#42;1^ a tua declaração no meu coração,
A fim de que eu não pecasse contra ti.

[NOTE]
====
. Ou: “Escondi.”
====

[[v19-119-12]]

^<<v19-119-12,12>>^ Bendito és, ó Jeová.
Ensina-me os teus regulamentos.

[[v19-119-13]]

^<<v19-119-13,13>>^ Com os meus lábios tenho declarado
Todas as decisões judiciais da tua boca.

[[v19-119-14]]

^<<v19-119-14,14>>^ Exultei no caminho das tuas advertências,
Assim como sobre todas as outras coisas valiosas.^&#42;1^

[NOTE]
====
. “Mais do que sobre todas as outras riquezas”, Sy.
====

[[v19-119-15]]

^<<v19-119-15,15>>^ Vou ocupar-me com as tuas ordens
E vou olhar para as tuas veredas.

[[v19-119-16]]

^<<v19-119-16,16>>^ Terei gosto em teus estatutos.
Não esquecerei a tua palavra.

_ג [Guímel]^&#42;1^_

[[v19-119-17]]

^<<v19-119-17,17>>^ Age apropriadamente para com o teu servo, para que eu viva
E para que eu guarde a tua palavra.

[[v19-119-18]]

^<<v19-119-18,18>>^ Desvenda os meus olhos, para que eu olhe
Para as coisas maravilhosas procedentes da tua lei.

[[v19-119-19]]

^<<v19-119-19,19>>^ Sou apenas residente forasteiro no país.
Não escondas de mim os teus mandamentos.

[[v19-119-20]]

^<<v19-119-20,20>>^ Minha alma está esmagada de anseio
Pelas tuas decisões judiciais, todo o tempo.

[[v19-119-21]]

^<<v19-119-21,21>>^ Censuraste os presunçosos amaldiçoados
Que se transviam dos teus mandamentos.

[[v19-119-22]]

^<<v19-119-22,22>>^ Rola de cima de mim o vitupério e o desprezo,
Pois observei as tuas próprias advertências.

[[v19-119-23]]

^<<v19-119-23,23>>^ Até mesmo príncipes se assentaram; contra mim falaram um com o outro.
Quanto ao teu servo, ele se ocupa com os teus regulamentos.

[[v19-119-24]]

^<<v19-119-24,24>>^ Também, é das tuas advertências que eu gosto,
Como homens do meu conselho.

_ד [Dálete]^&#42;1^_

[[v19-119-25]]

^<<v19-119-25,25>>^ Minha alma tem-se apegado ao próprio pó.
Preserva-me vivo,^&#42;1^ de acordo com a tua palavra.

[NOTE]
====
. Ou: “Faze-me viver.”
====

[[v19-119-26]]

^<<v19-119-26,26>>^ Declarei os meus próprios caminhos, a fim de que me respondesses.
Ensina-me os teus regulamentos.

[[v19-119-27]]

^<<v19-119-27,27>>^ Faze-me entender o caminho das tuas próprias ordens,
Para que eu me ocupe com as tuas obras maravilhosas.

[[v19-119-28]]

^<<v19-119-28,28>>^ Minha alma, de pesar, tem passado em claro.
Levanta-me, de acordo com a tua palavra.

[[v19-119-29]]

^<<v19-119-29,29>>^ Remove de mim o próprio caminho falso
E favorece-me com a tua própria lei.

[[v19-119-30]]

^<<v19-119-30,30>>^ Escolhi o caminho da fidelidade.
Considerei apropriadas as tuas decisões judiciais.

[[v19-119-31]]

^<<v19-119-31,31>>^ Apeguei-me às tuas advertências.
Ó Jeová, não me faças ficar envergonhado.

[[v19-119-32]]

^<<v19-119-32,32>>^ Correrei no próprio caminho dos teus mandamentos,
Porque fazes espaço^&#42;1^ para meu coração.

[NOTE]
====
. Ou “dás confiança (coragem) ao”.
====

_ה [Hê]^&#42;1^_

[[v19-119-33]]

^<<v19-119-33,33>>^ Instrui-me, ó Jeová, no caminho dos teus regulamentos,
Para que eu o observe até o último.

[[v19-119-34]]

^<<v19-119-34,34>>^ Faze-me entender, para que eu observe a tua lei
E para que eu a guarde de todo o coração.

[[v19-119-35]]

^<<v19-119-35,35>>^ Faze-me pisar na senda dos teus mandamentos,
Pois eu me agradei dela.

[[v19-119-36]]

^<<v19-119-36,36>>^ Inclina meu coração às tuas advertências
E não a lucros.^&#42;1^

[NOTE]
====
. Ou “lucro injusto”.
====

[[v19-119-37]]

^<<v19-119-37,37>>^ Faze meus olhos passar adiante de ver o que é fútil;
Preserva-me vivo no teu próprio caminho.

[[v19-119-38]]

^<<v19-119-38,38>>^ Cumpre para com o teu servo a tua declaração
Que [tende] ao temor de ti.

[[v19-119-39]]

^<<v19-119-39,39>>^ Faze passar meu vitupério de que fiquei amedrontado,
Porque as tuas decisões judiciais são boas.

[[v19-119-40]]

^<<v19-119-40,40>>^ Eis que anelei as tuas ordens.
Na tua justiça, preserva-me vivo.

_ו [Vau]^&#42;1^_

[[v19-119-41]]

^<<v19-119-41,41>>^ E cheguem a mim as tuas benevolências,^&#42;1^ ó Jeová,
Tua salvação, segundo a tua declaração,

[NOTE]
====
. “Benevolências”, TSy e muitos mss. hebr.; M: “benevolência”, mas com o verbo no pl.
====

[[v19-119-42]]

^<<v19-119-42,42>>^ Para que eu responda àquele que me vitupera com uma palavra,
Pois confiei na tua palavra.

[[v19-119-43]]

^<<v19-119-43,43>>^ E não tires inteiramente da minha boca a palavra da verdade,
Pois esperei a tua própria decisão judicial.

[[v19-119-44]]

^<<v19-119-44,44>>^ E vou guardar constantemente a tua lei
Por tempo indefinido, para todo o sempre.

[[v19-119-45]]

^<<v19-119-45,45>>^ E vou andar num lugar espaçoso,
Pois é as tuas ordens que tenho buscado.

[[v19-119-46]]

^<<v19-119-46,46>>^ Vou também falar sobre as tuas advertências diante de reis
E não ficarei envergonhado.

[[v19-119-47]]

^<<v19-119-47,47>>^ E terei gosto em teus mandamentos
Que tenho amado.

[[v19-119-48]]

^<<v19-119-48,48>>^ E levantarei as palmas das minhas mãos aos teus mandamentos que tenho amado,
E vou ocupar-me com os teus regulamentos.

_ז [Zaine]^&#42;1^_

[[v19-119-49]]

^<<v19-119-49,49>>^ Lembra-te da palavra ao teu servo,
Pela qual me fizeste esperar.

[[v19-119-50]]

^<<v19-119-50,50>>^ Este é meu consolo na minha tribulação,
Pois a tua própria declaração me preservou vivo.

[[v19-119-51]]

^<<v19-119-51,51>>^ Os próprios presunçosos caçoaram de mim ao extremo.
Não me apartei da tua lei.

[[v19-119-52]]

^<<v19-119-52,52>>^ Lembrei-me das tuas decisões judiciais desde tempo indefinido, ó Jeová,
E acho consolo para mim.

[[v19-119-53]]

^<<v19-119-53,53>>^ Um calor tórrido é que me segurou por causa dos iníquos
Que estão abandonando a tua lei.

[[v19-119-54]]

^<<v19-119-54,54>>^ Teus regulamentos tornaram-se para mim melodias
Na casa das minhas residências como forasteiro.

[[v19-119-55]]

^<<v19-119-55,55>>^ À noite lembrei-me do teu nome, ó Jeová,
A fim de que eu guarde a tua lei.

[[v19-119-56]]

^<<v19-119-56,56>>^ Até mesmo isto se tornou meu,
Porque tenho observado as tuas ordens.

_ח [Hete]^&#42;1^_

[[v19-119-57]]

^<<v19-119-57,57>>^ Jeová é meu quinhão;
Prometi guardar as tuas palavras.

[[v19-119-58]]

^<<v19-119-58,58>>^ Abrandei a tua face com todo o [meu] coração.
Mostra-me favor segundo a tua declaração.

[[v19-119-59]]

^<<v19-119-59,59>>^ Tenho considerado os meus caminhos
Para fazer meus pés voltar às tuas advertências.

[[v19-119-60]]

^<<v19-119-60,60>>^ Apressei-me e não me demorei
Para guardar os teus mandamentos.

[[v19-119-61]]

^<<v19-119-61,61>>^ Cercaram-me as próprias cordas dos iníquos.
Não me esqueci da tua lei.

[[v19-119-62]]

^<<v19-119-62,62>>^ À meia-noite me levanto para agradecer-te
As tuas decisões judiciais justas.

[[v19-119-63]]

^<<v19-119-63,63>>^ Sou associado de todos os que deveras te temem
E dos que guardam as tuas ordens.

[[v19-119-64]]

^<<v19-119-64,64>>^ A tua benevolência,^&#42;1^ ó Jeová, encheu a terra.
Ensina-me os teus próprios regulamentos.

[NOTE]
====
. Ou “amor leal”.
====

_ט [Tete]^&#42;1^_

[[v19-119-65]]

^<<v19-119-65,65>>^ Lidaste deveras bem com o teu servo,
Ó Jeová, de acordo com a tua palavra.

[[v19-119-66]]

^<<v19-119-66,66>>^ Ensina-me a própria bondade, a sensatez e o conhecimento,
Pois tive fé nos teus mandamentos.

[[v19-119-67]]

^<<v19-119-67,67>>^ Antes de estar em tribulação, eu pecava por engano,
Mas agora tenho guardado a tua própria declaração.

[[v19-119-68]]

^<<v19-119-68,68>>^ Tu és bom e fazes o bem.
Ensina-me os teus regulamentos.

[[v19-119-69]]

^<<v19-119-69,69>>^ Os presunçosos besuntaram-me com falsidade.
Quanto a mim, observarei as tuas ordens de todo o coração.

[[v19-119-70]]

^<<v19-119-70,70>>^ O coração deles tornou-se insensível igual à gordura.
Eu, da minha parte, tenho gostado da tua própria lei.

[[v19-119-71]]

^<<v19-119-71,71>>^ É bom para mim que tenho sido atribulado,
A fim de aprender os teus regulamentos.

[[v19-119-72]]

^<<v19-119-72,72>>^ A lei da tua boca é boa para mim,
Mais do que milhares de peças de ouro e de prata.

_י [Iode]^&#42;1^_

[[v19-119-73]]

^<<v19-119-73,73>>^ Tuas próprias mãos me fizeram e passaram a fixar-me solidamente.
Faze-me entender, para que eu aprenda os teus mandamentos.

[[v19-119-74]]

^<<v19-119-74,74>>^ Os que te temem são os que me vêem e se alegram,
Pois tenho esperado a tua própria palavra.

[[v19-119-75]]

^<<v19-119-75,75>>^ Bem sei, ó Jeová, que as tuas decisões judiciais são justiça
E que me atribulaste com fidelidade.

[[v19-119-76]]

^<<v19-119-76,76>>^ Por favor, sirva a tua benevolência para consolar-me,
Segundo a tua declaração ao teu servo.

[[v19-119-77]]

^<<v19-119-77,77>>^ Cheguem a mim as tuas misericórdias, para que eu continue vivendo;
Pois é da tua lei que eu gosto.

[[v19-119-78]]

^<<v19-119-78,78>>^ Envergonhem-se os presunçosos, pois me desencaminharam sem causa alguma.^&#42;1^
Quanto a mim, ocupo-me com as tuas ordens.

[NOTE]
====
. “Sem causa alguma.” Lit.: “[com] falsidade”.
====

[[v19-119-79]]

^<<v19-119-79,79>>^ Voltem a mim os que te temem,
Também os que conhecem as tuas advertências.^&#42;1^

[NOTE]
====
. Segundo MmargemTLXXSy e muitos mss. hebr.; M: “para que conheçam as tuas advertências”.
====

[[v19-119-80]]

^<<v19-119-80,80>>^ Mostre meu coração ser sem defeito nos teus regulamentos,
A fim de que eu não seja envergonhado.

_כ [Cafe]^&#42;1^_

[[v19-119-81]]

^<<v19-119-81,81>>^ Minha alma está definhando [à espera] da tua salvação;
Pois tenho esperado a tua palavra.

[[v19-119-82]]

^<<v19-119-82,82>>^ Meus olhos estão definhando [à espera] da tua declaração,
Ao passo que digo: “Quando me consolarás?”

[[v19-119-83]]

^<<v19-119-83,83>>^ Pois tornei-me como um odre na fumaça.
Não me esqueci dos teus regulamentos.

[[v19-119-84]]

^<<v19-119-84,84>>^ Quantos são os dias do teu servo?
Quando executarás o julgamento contra os que me perseguem?

[[v19-119-85]]

^<<v19-119-85,85>>^ Os presunçosos escavaram fojos para me [apanhar],
Aqueles que não estão de acordo com a tua lei.

[[v19-119-86]]

^<<v19-119-86,86>>^ Todos os teus mandamentos são a própria fidelidade.
Perseguiram-me sem causa alguma. Oh! ajuda-me.

[[v19-119-87]]

^<<v19-119-87,87>>^ Dentro em pouco me teriam exterminado na terra;
Mas eu mesmo não abandonei as tuas ordens.

[[v19-119-88]]

^<<v19-119-88,88>>^ Preserva-me vivo segundo a tua benevolência,
Para que eu guarde a advertência da tua boca.

_ל [Lâmede]^&#42;1^_

[[v19-119-89]]

^<<v19-119-89,89>>^ Por tempo indefinido, ó Jeová,
Tua palavra está posta nos céus.^&#42;1^

[NOTE]
====
. “Tu és por tempo indefinido, ó Jeová; e tua palavra está posta nos céus”, Sy.
====

[[v19-119-90]]

^<<v19-119-90,90>>^ Tua fidelidade é para geração após geração.^&#42;1^
Estabeleceste solidamente a terra para que continuasse firme.

[NOTE]
====
. “Para geração após geração.” Ou “para todas as gerações”. Hebr.: ledhór wa·dhór.
====

[[v19-119-91]]

^<<v19-119-91,91>>^ Segundo as tuas decisões judiciais, ficaram [até] hoje,
Pois todos são os teus servos.

[[v19-119-92]]

^<<v19-119-92,92>>^ Se não fosse que gosto da tua lei,
Então eu teria perecido na minha tribulação.

[[v19-119-93]]

^<<v19-119-93,93>>^ Não me esquecerei das tuas ordens por tempo indefinido,
Porque por meio delas me preservaste vivo.

[[v19-119-94]]

^<<v19-119-94,94>>^ Sou teu. Oh! salva-me,
Porque tenho buscado as tuas próprias ordens.

[[v19-119-95]]

^<<v19-119-95,95>>^ Os iníquos me aguardaram para me destruir.
Continuo a mostrar-me atento às tuas advertências.

[[v19-119-96]]

^<<v19-119-96,96>>^ Tenho visto o fim de toda a perfeição.
Teu mandamento é muito amplo.

_מ [Meme]^&#42;1^_

[[v19-119-97]]

^<<v19-119-97,97>>^ Quanto eu amo a tua lei!
O dia inteiro ela é a minha preocupação.

[[v19-119-98]]

^<<v19-119-98,98>>^ Teu mandamento me faz^&#42;1^ mais sábio do que os meus inimigos,
Porque é meu por tempo indefinido.

[NOTE]
====
. “Teu mandamento [sing.] me faz”, segundo LXXVg e um ms. hebr.; segundo M: “teus mandamentos [pl.] me fazem”.
====

[[v19-119-99]]

^<<v19-119-99,99>>^ Vim a ter mais perspicácia do que todos os meus mestres,
Porque as tuas advertências são minha preocupação.

[[v19-119-100]]

^<<v19-119-100,100>>^ Comporto-me com mais entendimento do que homens mais idosos,
Pois observei as tuas próprias ordens.

[[v19-119-101]]

^<<v19-119-101,101>>^ Contive meus pés de toda vereda má,
Com o fim de guardar a tua palavra.

[[v19-119-102]]

^<<v19-119-102,102>>^ Não me afastei das tuas decisões judiciais,
Porque tu mesmo me instruíste.

[[v19-119-103]]

^<<v19-119-103,103>>^ Quão suaves para o meu paladar têm sido as tuas declarações,^&#42;1^
Mais do que o mel para a minha boca!

[NOTE]
====
. “Declarações”, TLXXSyVg e cinco mss. hebr.; M: “declaração”, mas o verbo está no pl.
====

[[v19-119-104]]

^<<v19-119-104,104>>^ Devido às tuas ordens comporto-me com entendimento.
Por isso é que tenho odiado toda vereda falsa.

_נ [Nune]^&#42;1^_

[[v19-119-105]]

^<<v19-119-105,105>>^ Lâmpada para o meu pé^&#42;1^ é a tua palavra
E luz para a minha senda.

[NOTE]
====
. “Pé”, M; LXXSyVg e um ms. hebr.: “pés”.
====

[[v19-119-106]]

^<<v19-119-106,106>>^ Fiz uma declaração juramentada e vou cumpri-la:
Guardar as tuas decisões judiciais justas.

[[v19-119-107]]

^<<v19-119-107,107>>^ Fui muitíssimo atribulado.
Ó Jeová, preserva-me vivo, segundo a tua palavra.

[[v19-119-108]]

^<<v19-119-108,108>>^ Por favor, tem prazer nas ofertas voluntárias de minha boca, ó Jeová,
E ensina-me as tuas próprias decisões judiciais.

[[v19-119-109]]

^<<v19-119-109,109>>^ Minha alma está constantemente na palma da minha mão;
Mas não me esqueci da tua lei.

[[v19-119-110]]

^<<v19-119-110,110>>^ Os iníquos armaram-me uma armadilha,
Mas não me afastei vagueando das tuas ordens.

[[v19-119-111]]

^<<v19-119-111,111>>^ Tomei posse das tuas advertências por tempo indefinido,
Pois são a exultação de meu coração.

[[v19-119-112]]

^<<v19-119-112,112>>^ Inclinei meu coração para cumprir teus regulamentos
Por tempo indefinido, até o último.

_ם [Sâmeque]^&#42;1^_

[[v19-119-113]]

^<<v19-119-113,113>>^ Tenho odiado os dúbios,
Mas tenho amado a tua lei.

[[v19-119-114]]

^<<v19-119-114,114>>^ Tu és meu esconderijo e meu escudo.
Por tua palavra tenho esperado.

[[v19-119-115]]

^<<v19-119-115,115>>^ Afastai-vos de mim, malfeitores,
Para que eu observe os mandamentos de meu Deus.

[[v19-119-116]]

^<<v19-119-116,116>>^ Sustenta-me segundo a tua declaração, para que eu continue vivendo,
E não me faças ficar envergonhado por causa da minha esperança.

[[v19-119-117]]

^<<v19-119-117,117>>^ Ampara-me, para que eu seja salvo,
E atentarei constantemente nos teus regulamentos.

[[v19-119-118]]

^<<v19-119-118,118>>^ Lançaste fora todos os que se transviaram dos teus regulamentos;
Pois a sua ardileza é falsidade.

[[v19-119-119]]

^<<v19-119-119,119>>^ Fizeste cessar, como escória, todos os iníquos da terra.
Por isso tenho amado as tuas advertências.

[[v19-119-120]]

^<<v19-119-120,120>>^ De pavor de ti arrepiou-se a minha carne;
E tive medo por causa das tuas decisões judiciais.

_ע [Aine]^&#42;1^_

[[v19-119-121]]

^<<v19-119-121,121>>^ Executei o julgamento^&#42;1^ e a justiça.
Oh! não me entregues aos que me defraudam.

[NOTE]
====
. Ou “decisão judicial”.
====

[[v19-119-122]]

^<<v19-119-122,122>>^ Age como penhor do teu servo para o que é bom.
Não me defraudem os presunçosos.

[[v19-119-123]]

^<<v19-119-123,123>>^ Meus próprios olhos se definham [ansiando] a tua salvação
E a tua declaração justa.

[[v19-119-124]]

^<<v19-119-124,124>>^ Faze com o teu servo segundo a tua benevolência
E ensina-me os teus próprios regulamentos.

[[v19-119-125]]

^<<v19-119-125,125>>^ Sou teu servo. Faze-me entender,
Para que eu conheça as tuas advertências.

[[v19-119-126]]

^<<v19-119-126,126>>^ É tempo para Jeová agir.
Violaram a tua lei.

[[v19-119-127]]

^<<v19-119-127,127>>^ Por isso é que tenho amado os teus mandamentos
Mais do que o ouro, sim, o ouro refinado.

[[v19-119-128]]

^<<v19-119-128,128>>^ Por isso é que tenho considerado direitas todas as ordens referentes a todas as coisas;
Tenho odiado toda vereda falsa.

_פ [Pê]^&#42;1^_

[[v19-119-129]]

^<<v19-119-129,129>>^ Tuas advertências são maravilhosas.
Por isso é que a minha alma as tem observado.

[[v19-119-130]]

^<<v19-119-130,130>>^ A própria exposição das tuas palavras dá luz,
Fazendo que os inexperientes entendam.

[[v19-119-131]]

^<<v19-119-131,131>>^ Abri bem a minha boca para ofegar,
Porque tenho almejado os teus mandamentos.

[[v19-119-132]]

^<<v19-119-132,132>>^ Vira-te para mim e mostra-me favor,
Segundo a [tua] decisão judicial^&#42;1^ para com os que amam o teu nome.

[NOTE]
====
. Ou “[teu] costume”.
====

[[v19-119-133]]

^<<v19-119-133,133>>^ Firma solidamente os meus próprios passos na tua declaração
E não me tiranize nenhuma espécie de coisa prejudicial.

[[v19-119-134]]

^<<v19-119-134,134>>^ Redime-me de qualquer defraudador da humanidade^&#42;1^
E eu vou guardar as tuas ordens.

[NOTE]
====
. “Humanidade.” Hebr.: ’a·dhám.
====

[[v19-119-135]]

^<<v19-119-135,135>>^ Faze a tua própria face luzir sobre o teu servo
E ensina-me os teus regulamentos.

[[v19-119-136]]

^<<v19-119-136,136>>^ Correntes de água desceram dos meus olhos
Pelo fato de que não guardaram a tua lei.

_צ [Tsadê]^&#42;1^_

[[v19-119-137]]

^<<v19-119-137,137>>^ Tu és justo, ó Jeová,
E tuas decisões judiciais são retas.

[[v19-119-138]]

^<<v19-119-138,138>>^ Ordenaste as tuas advertências em justiça
E em extrema fidelidade.

[[v19-119-139]]

^<<v19-119-139,139>>^ Meu fervor deu cabo de mim,
Porque os meus adversários se esqueceram das tuas palavras.

[[v19-119-140]]

^<<v19-119-140,140>>^ Tua declaração é muitíssimo refinada
E teu próprio servo a ama.

[[v19-119-141]]

^<<v19-119-141,141>>^ Sou insignificante e desprezível.
Não me esqueci das tuas ordens.

[[v19-119-142]]

^<<v19-119-142,142>>^ Tua justiça é justiça por tempo indefinido
E tua lei é verdade.

[[v19-119-143]]

^<<v19-119-143,143>>^ A própria aflição e dificuldade me acharam.
Gostei dos teus mandamentos.

[[v19-119-144]]

^<<v19-119-144,144>>^ A justiça das tuas advertências é por tempo indefinido.
Faze-me entender, para que eu continue vivendo.

_ק [Cofe]^&#42;1^_

[[v19-119-145]]

^<<v19-119-145,145>>^ Clamei de todo o [meu] coração. Responde-me, ó Jeová.
Vou observar os teus regulamentos.

[[v19-119-146]]

^<<v19-119-146,146>>^ Eu te invoquei. Oh! salva-me.
E eu vou guardar as tuas advertências.

[[v19-119-147]]

^<<v19-119-147,147>>^ Levantei-me cedo no crepúsculo matutino, a fim de clamar por ajuda.
Esperei as tuas palavras.

[[v19-119-148]]

^<<v19-119-148,148>>^ Meus olhos se adiantaram às vigílias noturnas,
[A fim de] eu me ocupar com a tua declaração.

[[v19-119-149]]

^<<v19-119-149,149>>^ Oh! ouve deveras a minha própria voz segundo a tua benevolência.
Ó Jeová, preserva-me vivo segundo a tua decisão judicial.

[[v19-119-150]]

^<<v19-119-150,150>>^ Chegaram-se os que se empenham pela conduta desenfreada;^&#42;1^
Vieram ficar longe da tua própria lei.

[NOTE]
====
. Segundo MT; LXXSyVg e mediante uma ligeira correção do M: “Os que me perseguem chegaram-se à conduta desenfreada”. “Conduta desenfreada”, hebr.: zim·máh; lat.: in·i·qui·tá·te. Veja Gál 5:19 n.: “desenfreada”.
====

[[v19-119-151]]

^<<v19-119-151,151>>^ Tu estás perto, ó Jeová,
E todos os teus mandamentos são verdade.

[[v19-119-152]]

^<<v19-119-152,152>>^ Outrora fiquei conhecendo algumas das tuas advertências,
Pois tu as fundaste por tempo indefinido.

_ר [Rexe]^&#42;1^_

[[v19-119-153]]

^<<v19-119-153,153>>^ Oh! vê a minha tribulação e socorre-me;
Pois não me esqueci da tua própria lei.

[[v19-119-154]]

^<<v19-119-154,154>>^ Oh! pleiteia deveras a minha causa e recupera-me;
Preserva-me vivo, de acordo com a tua declaração.

[[v19-119-155]]

^<<v19-119-155,155>>^ A salvação está longe dos iníquos,
Porque eles não buscaram os teus próprios regulamentos.

[[v19-119-156]]

^<<v19-119-156,156>>^ Muitas são as tuas misericórdias, ó Jeová.
Segundo as tuas decisões judiciais, oh! preserva-me vivo.

[[v19-119-157]]

^<<v19-119-157,157>>^ São muitos os meus perseguidores e meus adversários.
Não me apartei das tuas advertências.

[[v19-119-158]]

^<<v19-119-158,158>>^ Tenho visto os que agem traiçoeiramente
E tenho deveras aversão, porque não guardaram a tua própria declaração.

[[v19-119-159]]

^<<v19-119-159,159>>^ Vê deveras que tenho amado as tuas próprias ordens.
Ó Jeová, preserva-me vivo segundo a tua benevolência.

[[v19-119-160]]

^<<v19-119-160,160>>^ A substância^&#42;1^ da tua palavra é a verdade
E toda decisão judicial justa tua é por tempo indefinido.

[NOTE]
====
. Ou “soma”.
====

_ש [Sim] ou [Chim]^&#42;1^_

[[v19-119-161]]

^<<v19-119-161,161>>^ Os próprios príncipes me perseguiram sem causa alguma,
Meu coração, porém, tem estado apavorado das tuas próprias palavras.

[[v19-119-162]]

^<<v19-119-162,162>>^ Exulto sobre a tua declaração
Assim como quando alguém acha muito despojo.

[[v19-119-163]]

^<<v19-119-163,163>>^ Tenho odiado a falsidade e continuo deveras a detestá-la.
Tenho amado a tua lei.

[[v19-119-164]]

^<<v19-119-164,164>>^ Eu te tenho louvado sete vezes por dia
Por causa das tuas decisões judiciais justas.

[[v19-119-165]]

^<<v19-119-165,165>>^ Paz abundante pertence aos que amam a tua lei,
E para eles não há pedra de tropeço.

[[v19-119-166]]

^<<v19-119-166,166>>^ Tenho esperado a tua salvação, ó Jeová,
E tenho executado os teus próprios mandamentos.

[[v19-119-167]]

^<<v19-119-167,167>>^ Minha alma tem guardado as tuas advertências,
E eu as amo extraordinariamente.

[[v19-119-168]]

^<<v19-119-168,168>>^ Tenho guardado as tuas ordens e as tuas advertências,
Pois todos os meus caminhos estão diante de ti.

_ת [Tau]^&#42;1^_

[[v19-119-169]]

^<<v19-119-169,169>>^ Chegue-se diante de ti o meu clamor suplicante, ó Jeová.
Segundo a tua palavra, oh! faze-me entender.

[[v19-119-170]]

^<<v19-119-170,170>>^ Entre diante de ti meu pedido de favor.
Segundo a tua declaração, oh! livra-me.

[[v19-119-171]]

^<<v19-119-171,171>>^ Borbulhem meus lábios louvor,
Pois me ensinas os teus regulamentos.

[[v19-119-172]]

^<<v19-119-172,172>>^ Cante minha língua a tua declaração,
Pois todos os teus mandamentos são justiça.

[[v19-119-173]]

^<<v19-119-173,173>>^ Sirva a tua mão para me ajudar,
Pois escolhi as tuas ordens.

[[v19-119-174]]

^<<v19-119-174,174>>^ Tenho anelado a tua salvação, ó Jeová,
E gosto da tua lei.

[[v19-119-175]]

^<<v19-119-175,175>>^ Continue minha alma a viver e a louvar-te,
E ajudem-me as tuas próprias decisões judiciais.

[[v19-119-176]]

^<<v19-119-176,176>>^ Tenho vagueado como um ovídeo perdido. Oh! procura o teu servo,
Pois não me esqueci dos teus próprios mandamentos.^&#42;1^

[NOTE]
====
. Com exceção dos vv. 90 e 122, cada v. deste salmo alfabético contém uma ou mais das seguintes dez expressões: CAMINHO(S), 13 vezes (x); ADVERTÊNCIA(S), 23x; ORDENS, 21x; MANDAMENTO(S), 22x; DECLARAÇÃO(ÕES), 19x; LEI, 25x; DECISÃO(ÕES) JUDICIAL(AIS) ou JULGAMENTO, 23x; JUSTO, JUSTA(S) ou JUSTIÇA, 15x; REGULAMENTOS ou ESTATUTOS, 22x, e PALAVRA(S), 24x. Na maioria das 22 seções há também ocorrências dos oito termos jurídicos principais do Sal 19:7-14, a saber: LEI, ADVERTÊNCIA, ORDENS, MANDAMENTO, TEMOR, DECISÕES JUDICIAIS, JUSTAS e DECLARAÇÕES.
====

'''

xref:019-salmo/019-salmo-118.adoc#v19-118-0[&#60; Capítulo Anterior] | <<v19-119-0,Topo>> | xref:019-salmo/019-salmo-120.adoc#v19-120-0[Próximo Capítulo &#62;]