include::./index.adoc[]

[[v19-2-0]]
=== Salmos, 2
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v19-2-1]]

^<<v19-2-1,1>>^ Por que se alvoroçaram as nações
E continuam os próprios grupos nacionais a murmurar coisa vã?

[[v19-2-2]]

^<<v19-2-2,2>>^ Os reis da terra tomam sua posição,
E os próprios dignitários se aglomeraram à uma
Contra Jeová e contra o seu ungido,^&#42;1^

[NOTE]
====
. “E contra o seu ungido.” Hebr.: we‛al-meshi·hhóh; gr.: khri·stoú; sir.: meshi·hheh; lat.: chrí·stum.
====

[[v19-2-3]]

^<<v19-2-3,3>>^ [Dizendo:] “Rompamos as suas ligaduras
E lancemos de nós as suas cordas!”

[[v19-2-4]]

^<<v19-2-4,4>>^ Aquele mesmo que está sentado nos céus se rirá;
O próprio Jeová^&#42;1^ caçoará deles.

[NOTE]
====
. Uma das 134 mudanças de YHWH para ’Adho·naí feitas pelos escribas. Veja Ap. 1B.
====

[[v19-2-5]]

^<<v19-2-5,5>>^ Nesse tempo lhes falará na sua ira
E os perturbará no seu ardente desagrado,

[[v19-2-6]]

^<<v19-2-6,6>>^ [Dizendo:] “Eu é que empossei o meu rei
Em Sião, meu santo monte.”^&#42;1^

[NOTE]
====
. Lit.: “monte de minha santidade”.
====

[[v19-2-7]]

^<<v19-2-7,7>>^ Cite eu o decreto de Jeová;
Ele me disse: “Tu és meu filho;
Hoje eu me tornei teu pai.

[[v19-2-8]]

^<<v19-2-8,8>>^ Pede-me, para que eu te dê nações por tua herança
E os confins da terra por tua propriedade.

[[v19-2-9]]

^<<v19-2-9,9>>^ Tu as quebrantarás^&#42;1^ com um cetro de ferro,
Espatifá-las-ás como se fossem um vaso de oleiro.”

[NOTE]
====
. “Quebrantarás”, M; LXX: “pastorearás”.
====

[[v19-2-10]]

^<<v19-2-10,10>>^ E agora, ó reis, usai de perspicácia;
Deixai-vos corrigir, ó juízes da terra.

[[v19-2-11]]

^<<v19-2-11,11>>^ Servi a Jeová com temor
E jubilai com tremor.

[[v19-2-12]]

^<<v19-2-12,12>>^ Beijai ao filho,^&#42;1^ para que Ele não se ire
E não pereçais [no] caminho,^&#42;2^
Pois a sua ira se acende facilmente.^&#42;3^
Felizes todos os que se refugiam nele.

[NOTE]
====
. “Beijai ao filho.” Hebr.: nash·shequ·vár. Aqui se usa o var (de bar) aram.; não o ben hebr., como em 3:cab.; T: “Recebei instrução”; LXX: “Aceitai correção”; Vg: “Aprendei disciplina”. Veja Pr 31:2 n.
. “[No] caminho”, em harmonia com LXXVg, que rezam: “no caminho justo”.
. Ou “depressa”.
====

'''

xref:019-salmo/019-salmo-001.adoc#v19-1-0[&#60; Capítulo Anterior] | <<v19-2-0,Topo>> | xref:019-salmo/019-salmo-003.adoc#v19-3-0[Próximo Capítulo &#62;]