include::./index.adoc[]

[[v19-122-0]]
=== Salmos, 122
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

_Cântico das Subidas. De Davi._

[[v19-122-1]]

^<<v19-122-1,1>>^ Alegrei-me quando me disseram:
“Vamos à casa de Jeová.”

[[v19-122-2]]

^<<v19-122-2,2>>^ Nossos pés mostraram estar postos
Dentro dos teus portões, ó Jerusalém.

[[v19-122-3]]

^<<v19-122-3,3>>^ Jerusalém é aquela que é construída como cidade,
Coligada em união,

[[v19-122-4]]

^<<v19-122-4,4>>^ À qual subiram as tribos,
As tribos de Jah,^&#42;1^
Como advertência a Israel,
Para dar graças ao nome de Jeová.

[NOTE]
====
. “Jah.” Veja 68:4 n.
====

[[v19-122-5]]

^<<v19-122-5,5>>^ Pois ali estavam assentados os tronos^&#42;1^ para julgamento,
Tronos para a casa de Davi.

[NOTE]
====
. Ou “o grandioso trono”, se for pl. para denotar excelência.
====

[[v19-122-6]]

^<<v19-122-6,6>>^ Pedi a paz de Jerusalém.
Os que te^&#42;1^ amam, [ó cidade,] ficarão livres de cuidados.

[NOTE]
====
. “Te”, fem. sing. no hebr., referindo-se a “Jerusalém”.
====

[[v19-122-7]]

^<<v19-122-7,7>>^ Continue a paz dentro da tua escarpa,
A despreocupação dentro das tuas torres de habitação.

[[v19-122-8]]

^<<v19-122-8,8>>^ Agora vou falar por causa dos meus irmãos e dos meus companheiros:
“Haja paz em ti.”

[[v19-122-9]]

^<<v19-122-9,9>>^ Por causa da casa de Jeová, nosso Deus,
Vou continuar a procurar o teu^&#42;1^ bem.

[NOTE]
====
. Veja v. 6 n.
====

'''

xref:019-salmo/019-salmo-121.adoc#v19-121-0[&#60; Capítulo Anterior] | <<v19-122-0,Topo>> | xref:019-salmo/019-salmo-123.adoc#v19-123-0[Próximo Capítulo &#62;]