include::./index.adoc[]

[[v19-69-0]]
=== Salmos, 69
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

_Ao regente, segundo Os Lírios.^&#42;1^ De Davi._

[[v19-69-1]]

^<<v19-69-1,1>>^ Salva-me, ó Deus, porque as águas chegaram até a alma.^&#42;1^

[NOTE]
====
. Ou “vida”. Hebr.: ná·fesh; T(aram.)sir.: naf·sha’; gr.: psy·khés; lat.: á·ni·mam.
====

[[v19-69-2]]

^<<v19-69-2,2>>^ Afundei em lodo profundo, em que não se pode ficar de pé.
Entrei em águas fundas,
E um caudal^&#42;1^ é que me levou de enxurrada.

[NOTE]
====
. “E um caudal.” Hebr.: weshib·bó·leth.
====

[[v19-69-3]]

^<<v19-69-3,3>>^ Fatiguei-me de clamar;
Minha garganta ficou rouca.
Meus olhos falharam na espera pelo meu Deus.

[[v19-69-4]]

^<<v19-69-4,4>>^ Os que me odeiam sem causa tornaram-se até mais do que os cabelos da minha cabeça.
Os que me silenciam, sendo meus inimigos por nenhuma razão, tornaram-se numerosos.
O que eu não roubara, passei então a devolver.

[[v19-69-5]]

^<<v19-69-5,5>>^ Ó Deus, tu mesmo vieste conhecer minha tolice,
E não ficou oculta de ti a minha própria culpa.

[[v19-69-6]]

^<<v19-69-6,6>>^ Não fiquem envergonhados por minha causa os que esperam em ti,
Ó Soberano Senhor, Jeová dos exércitos.
Não sejam humilhados por minha causa os que te procuram,
Ó Deus de Israel.

[[v19-69-7]]

^<<v19-69-7,7>>^ Pois, por tua causa tenho levado vitupério,
Humilhação cobriu minha face.

[[v19-69-8]]

^<<v19-69-8,8>>^ Tenho-me tornado estranho para os meus irmãos
E estrangeiro para os filhos de minha mãe.

[[v19-69-9]]

^<<v19-69-9,9>>^ Pois, consumiu-me o puro zelo pela tua casa
E caíram sobre mim os próprios vitupérios dos que te vituperam.

[[v19-69-10]]

^<<v19-69-10,10>>^ E passei a chorar com o jejum da minha alma,
Mas veio a ser para mim vitupérios.

[[v19-69-11]]

^<<v19-69-11,11>>^ Quando da serapilheira fiz a minha vestimenta,
Então me tornei para eles uma expressão proverbial.

[[v19-69-12]]

^<<v19-69-12,12>>^ Os que estavam sentados no portão começaram a ocupar-se comigo,
E [eu era] o assunto dos cantos de bebedores de bebida inebriante.

[[v19-69-13]]

^<<v19-69-13,13>>^ Quanto a mim, porém, minha oração era a ti, ó Jeová,^&#42;1^
Num tempo aceitável, ó Deus.
Responde-me na abundância da tua benevolência com a verdade da salvação por meio de ti.

[NOTE]
====
. “Jeová.” Hebr.: Yehwáh; o fragmento SymP. Vindºb. G. 39777: o Tetragrama em antigos caracteres hebr. Veja Ap. 1C sec. 9.
====

[[v19-69-14]]

^<<v19-69-14,14>>^ Livra-me da lama, para que eu não afunde.
Seja eu livrado dos que me odeiam e das águas fundas.

[[v19-69-15]]

^<<v19-69-15,15>>^ Que não me arraste um caudal de águas,
Nem me trague a profundeza,
Nem feche o poço a sua boca sobre mim.

[[v19-69-16]]

^<<v19-69-16,16>>^ Responde-me, ó Jeová, pois a tua benevolência é boa.
Vira-te para mim segundo a multidão das tuas misericórdias

[[v19-69-17]]

^<<v19-69-17,17>>^ E não escondas tua face do teu servo.
Responde-me rapidamente, porque estou em sério aperto.

[[v19-69-18]]

^<<v19-69-18,18>>^ Chega-te deveras à minha alma, reivindica-a;
Redime-me por causa dos meus inimigos.

[[v19-69-19]]

^<<v19-69-19,19>>^ Tu mesmo vieste conhecer meu vitupério, e minha vergonha, e minha humilhação.
Diante de ti estão todos os que me são hostis.

[[v19-69-20]]

^<<v19-69-20,20>>^ O próprio vitupério me quebrantou o coração, e [a ferida] é incurável.
E eu estava esperando que alguém se compadecesse [de mim], mas não havia ninguém;
E consoladores, mas não achei nenhum.

[[v19-69-21]]

^<<v19-69-21,21>>^ Mas, por alimento^&#42;1^ [me] deram uma planta venenosa,^&#42;2^
E para a minha sede tentaram fazer-me beber vinagre.

[NOTE]
====
. Ou “pão de consolo”.
. Ou “passaram a pôr veneno”.
====

[[v19-69-22]]

^<<v19-69-22,22>>^ Torne-se a sua mesa^&#42;1^ diante deles em armadilha
E o que é para o seu bem-estar, em laço.

[NOTE]
====
. Isto é, uma mesa para sacrifícios. Ou “banquete”.
====

[[v19-69-23]]

^<<v19-69-23,23>>^ Obscureçam-se-lhes os olhos para que não vejam;
E faze seus próprios quadris vacilar constantemente.

[[v19-69-24]]

^<<v19-69-24,24>>^ Derrama sobre eles a tua verberação
E alcance-os a tua própria ira ardente.

[[v19-69-25]]

^<<v19-69-25,25>>^ Fique desolado seu acampamento murado;
Não venha a haver morador nas suas tendas.

[[v19-69-26]]

^<<v19-69-26,26>>^ Pois perseguiram aquele que tu mesmo golpeaste
E prosseguem narrando as dores dos que tu traspassaste.

[[v19-69-27]]

^<<v19-69-27,27>>^ Dá deveras erro sobre seu erro,
E não entrem na tua justiça.

[[v19-69-28]]

^<<v19-69-28,28>>^ Sejam extintos do livro dos viventes,^&#42;1^
E não sejam inscritos com os justos.

[NOTE]
====
. Ou “livro da vida”.
====

[[v19-69-29]]

^<<v19-69-29,29>>^ Mas eu estou atribulado e sinto dores.
Proteja-me a tua própria salvação, ó Deus.

[[v19-69-30]]

^<<v19-69-30,30>>^ Vou louvar o nome de Deus^&#42;1^ com cântico
E vou magnificá-lo com agradecimento.

[NOTE]
====
. “Deus.” Hebr.: ’Elo·hím. O fragmento SymP. Vindºb. G. 39777 aqui tem “Jeová Deus”, com o Tetragrama em antigos caracteres hebr.. Veja Ap. 1C sec. 9.
====

[[v19-69-31]]

^<<v19-69-31,31>>^ Isto também agradará mais a Jeová^&#42;1^ do que um touro,
Mais do que um novilho de chifres, de casco fendido.

[NOTE]
====
. Veja Ap. 1C sec. 9.
====

[[v19-69-32]]

^<<v19-69-32,32>>^ Os mansos certamente [o] verão; alegrar-se-ão.
Vós os que buscais a Deus, mantenha-se vivo também o vosso coração.

[[v19-69-33]]

^<<v19-69-33,33>>^ Pois Jeová está escutando os pobres
E deveras não desprezará os seus próprios prisioneiros.^&#42;1^

[NOTE]
====
. Ou “os seus que são prisioneiros”.
====

[[v19-69-34]]

^<<v19-69-34,34>>^ Louvem-no céu e terra,
Os mares e tudo o que neles se move.

[[v19-69-35]]

^<<v19-69-35,35>>^ Porque o próprio Deus salvará a Sião
E construirá as cidades de Judá;
E ali hão de morar e tomar posse dela.^&#42;1^

[NOTE]
====
. “Dela”, hebr. fem., referindo-se à terra.
====

[[v19-69-36]]

^<<v19-69-36,36>>^ E a própria descendência^&#42;1^ dos seus servos a herdará,
E os que amam seu nome serão os que nela residirão.

[NOTE]
====
. Lit.: “semente”.
====

'''

xref:019-salmo/019-salmo-068.adoc#v19-68-0[&#60; Capítulo Anterior] | <<v19-69-0,Topo>> | xref:019-salmo/019-salmo-070.adoc#v19-70-0[Próximo Capítulo &#62;]