include::./index.adoc[]

[[v19-77-0]]
=== Salmos, 77
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

_Ao regente, segundo Jedutum.^&#42;1^ De Asafe. Uma melodia._

[[v19-77-1]]

^<<v19-77-1,1>>^ Com a minha voz clamarei ao próprio Deus,^&#42;1^
Com a minha voz, a Deus, e ele certamente me dará ouvidos.

[NOTE]
====
. “Deus.” Hebr.: ’Elo·hím; TLXXVg: “Jeová”.
====

[[v19-77-2]]

^<<v19-77-2,2>>^ No dia da minha aflição busquei o próprio Jeová.^&#42;1^
À noite, minha própria mão tem ficado estendida^&#42;2^ e não fica entorpecida;
Minha alma tem-se recusado a ser consolada.

[NOTE]
====
. Uma das 134 mudanças de YHWH para ’Adho·naí feitas pelos escribas. Veja Ap. 1B.
. Lit.: “derramada”.
====

[[v19-77-3]]

^<<v19-77-3,3>>^ Vou lembrar-me de Deus e ser turbulento;
Vou preocupar-me, para que meu espírito se debilite. Selá.

[[v19-77-4]]

^<<v19-77-4,4>>^ Seguraste as minhas pálpebras;
Fiquei agitado e não posso falar.

[[v19-77-5]]

^<<v19-77-5,5>>^ Pensei nos dias de outrora,
Nos anos do passado indefinido.

[[v19-77-6]]

^<<v19-77-6,6>>^ Vou lembrar-me da minha música de cordas na noite;
Vou preocupar-me com o meu coração,
E meu espírito fará uma busca cuidadosa.

[[v19-77-7]]

^<<v19-77-7,7>>^ Será por tempos indefinidos que Jeová^&#42;1^ continuará a deitar fora,
E não terá mais prazer?

[NOTE]
====
. Veja v. 2 n.: “Jeová”.
====

[[v19-77-8]]

^<<v19-77-8,8>>^ Terminou para sempre a sua benevolência?
Acabou em nada a [sua] declaração por geração após geração?

[[v19-77-9]]

^<<v19-77-9,9>>^ Esqueceu-se Deus^&#42;1^ de ser favorável
Ou tem ele cortado em ira as suas misericórdias? Selá.

[NOTE]
====
. “Deus.” Hebr.: ’El.
====

[[v19-77-10]]

^<<v19-77-10,10>>^ E devo continuar a dizer: “Isto é o que me traspassa,
A mudança da direita do Altíssimo”?

[[v19-77-11]]

^<<v19-77-11,11>>^ Lembrar-me-ei das práticas de Jah;^&#42;1^
Pois, vou lembrar-me da tua maravilha de outrora.

[NOTE]
====
. Veja 68:4 n.
====

[[v19-77-12]]

^<<v19-77-12,12>>^ E meditarei certamente em toda a tua atividade
E vou ocupar-me com as tuas ações.

[[v19-77-13]]

^<<v19-77-13,13>>^ Ó Deus,^&#42;1^ teu caminho está no lugar santo.
Quem é um grande Deus^&#42;2^ tal como Deus?

[NOTE]
====
. “Deus.” Hebr.: ’Elo·hím.
. “Deus.” Hebr.: ’El.
====

[[v19-77-14]]

^<<v19-77-14,14>>^ Tu és o [verdadeiro] Deus, fazendo maravilhas.
Deste a conhecer a tua força entre os povos.

[[v19-77-15]]

^<<v19-77-15,15>>^ Com o [teu] braço recuperaste teu povo,
Os filhos de Jacó e de José. Selá.

[[v19-77-16]]

^<<v19-77-16,16>>^ As águas te viram, ó Deus,
As águas te viram; começaram a sentir dores agudas.
Também as águas de profundeza^&#42;1^ começaram a ficar agitadas.

[NOTE]
====
. Veja Êx 15:5 n.
====

[[v19-77-17]]

^<<v19-77-17,17>>^ As nuvens verteram água estrepitosamente;
O céu nublado emitiu um som.
Também, as tuas próprias flechas passaram a ir para lá e para cá.

[[v19-77-18]]

^<<v19-77-18,18>>^ O som do teu trovão foi como rodas de carros;
Relâmpagos iluminaram o solo produtivo;^&#42;1^
A terra ficou agitada e começou a tremer.

[NOTE]
====
. “O solo produtivo.” Hebr.: te·vél; LXX: “a terra habitada”; lat.: ór·bi tér·rae, “o círculo terrestre”.
====

[[v19-77-19]]

^<<v19-77-19,19>>^ Teu caminho foi através do mar
E tua vereda foi através de muitas águas;
E não se chegaram a conhecer as tuas próprias pegadas.

[[v19-77-20]]

^<<v19-77-20,20>>^ Guiaste o teu povo como a um rebanho
Pela mão de Moisés e de Arão.

'''

xref:019-salmo/019-salmo-076.adoc#v19-76-0[&#60; Capítulo Anterior] | <<v19-77-0,Topo>> | xref:019-salmo/019-salmo-078.adoc#v19-78-0[Próximo Capítulo &#62;]