include::./index.adoc[]

[[v19-116-0]]
=== Salmos, 116
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v19-116-1]]

^<<v19-116-1,1>>^ Deveras amo, porque Jeová ouve^&#42;1^
A minha voz, os meus rogos.^&#42;2^

[NOTE]
====
. Ou: “Amei que Jeová escutasse.”
. “A minha voz, os meus rogos”, M; LXXSyVg: “a voz da minha súplica (oração)”.
====

[[v19-116-2]]

^<<v19-116-2,2>>^ Pois ele me inclinou seu ouvido,
E eu chamarei durante os meus dias.

[[v19-116-3]]

^<<v19-116-3,3>>^ Cercaram-me as cordas da morte
E acharam-me as próprias circunstâncias aflitivas do Seol.
Continuei a encontrar aflição e pesar.

[[v19-116-4]]

^<<v19-116-4,4>>^ Mas, passei a invocar o nome de Jeová:
“Ai! Jeová, põe deveras a minha alma a salvo!”

[[v19-116-5]]

^<<v19-116-5,5>>^ Jeová é clemente e justo;
E nosso Deus é quem mostra ter misericórdia.

[[v19-116-6]]

^<<v19-116-6,6>>^ Jeová está guardando os inexperientes.
Eu estava empobrecido, e ele passou a salvar até mesmo a mim.

[[v19-116-7]]

^<<v19-116-7,7>>^ Retorna ao teu lugar de descanso, ó minha alma,
Pois o próprio Jeová agiu apropriadamente para contigo.

[[v19-116-8]]

^<<v19-116-8,8>>^ Pois socorreste minha alma da morte,
Meu olho das lágrimas, meu pé do tropeço.

[[v19-116-9]]

^<<v19-116-9,9>>^ Vou andar diante de Jeová nas terras dos viventes.

[[v19-116-10]]

^<<v19-116-10,10>>^ ^&#42;1^ Tive fé, pois passei a falar.
Eu mesmo estava muito atribulado.

[NOTE]
====
. LXXVg iniciam aqui seu Sal 115, com o cabeçalho: “Aleluia.”
====

[[v19-116-11]]

^<<v19-116-11,11>>^ Da minha parte, eu disse, quando fui tomado de pânico:
“Todo homem^&#42;1^ é mentiroso.”

[NOTE]
====
. Ou: “Toda a humanidade.” Hebr.: kol·ha·’a·dhám.
====

[[v19-116-12]]

^<<v19-116-12,12>>^ Que pagarei de volta a Jeová
Por todos os benefícios que me fez?

[[v19-116-13]]

^<<v19-116-13,13>>^ Levantarei o copo da grandiosa salvação
E invocarei o nome de Jeová.

[[v19-116-14]]

^<<v19-116-14,14>>^ Pagarei meus votos a Jeová,
Sim, diante de todo o seu povo.

[[v19-116-15]]

^<<v19-116-15,15>>^ Preciosa aos olhos de Jeová
É a morte dos que lhe são leais.

[[v19-116-16]]

^<<v19-116-16,16>>^ Ai! Jeová,
Pois sou teu servo.
Sou teu servo, filho da tua escrava.
Soltaste as minhas ligaduras.

[[v19-116-17]]

^<<v19-116-17,17>>^ Oferecer-te-ei o sacrifício de agradecimento
E invocarei o nome de Jeová.

[[v19-116-18]]

^<<v19-116-18,18>>^ Pagarei meus votos a Jeová,
Sim, diante de todo o seu povo,

[[v19-116-19]]

^<<v19-116-19,19>>^ Nos pátios da casa de Jeová,
No meio de ti, ó Jerusalém.
Louvai a Jah!^&#42;1^

[NOTE]
====
. Veja 104:35 n.
====

'''

xref:019-salmo/019-salmo-115.adoc#v19-115-0[&#60; Capítulo Anterior] | <<v19-116-0,Topo>> | xref:019-salmo/019-salmo-117.adoc#v19-117-0[Próximo Capítulo &#62;]