include::./index.adoc[]

[[v19-102-0]]
=== Salmos, 102
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

_Uma oração do atribulado no caso de ele se debilitar e derramar sua preocupação diante do próprio Jeová._

[[v19-102-1]]

^<<v19-102-1,1>>^ Ó Jeová, ouve deveras a minha oração;
E chegue a ti o meu próprio clamor por ajuda.

[[v19-102-2]]

^<<v19-102-2,2>>^ Não escondas de mim a tua face no dia em que eu estiver em sério aperto.
Inclina-me teu ouvido;
No dia em que eu chamar, apressa-te em responder-me.

[[v19-102-3]]

^<<v19-102-3,3>>^ Pois os meus dias findaram igual à fumaça,
E meus próprios ossos ficaram incandescentes como uma lareira.

[[v19-102-4]]

^<<v19-102-4,4>>^ Meu coração foi golpeado como a vegetação e se ressecou,
Pois me esqueci de comer meu alimento.^&#42;1^

[NOTE]
====
. Lit.: “pão”.
====

[[v19-102-5]]

^<<v19-102-5,5>>^ Por causa do som do meu suspiro
Apegaram-se-me os ossos à carne.

[[v19-102-6]]

^<<v19-102-6,6>>^ Pareço-me deveras ao pelicano do ermo.
Tornei-me como o mocho dos lugares desolados.

[[v19-102-7]]

^<<v19-102-7,7>>^ Fiquei emaciado^&#42;1^
E tornei-me igual a um pássaro isolado sobre o telhado.

[NOTE]
====
. Possivelmente: “Fiquei acordado”, mediante outra derivação do verbo hebr.
====

[[v19-102-8]]

^<<v19-102-8,8>>^ Meus inimigos me têm vituperado o dia inteiro.
Os que me fazem de tolo juraram até mesmo por mim.

[[v19-102-9]]

^<<v19-102-9,9>>^ Pois comi as próprias cinzas como pão;
E as coisas que bebo misturei até mesmo com choro,

[[v19-102-10]]

^<<v19-102-10,10>>^ Por causa da tua verberação e da tua indignação;
Pois tu me levantaste para me lançar fora.

[[v19-102-11]]

^<<v19-102-11,11>>^ Meus dias são como a sombra que declinou^&#42;1^
E eu mesmo estou ressequido como a mera vegetação.

[NOTE]
====
. “Meus próprios dias declinaram iguais a uma sombra”, LXXSyVg e mediante um ligeira correção do M.
====

[[v19-102-12]]

^<<v19-102-12,12>>^ Quanto a ti, ó Jeová, morarás por tempo indefinido,
E a recordação de ti será para geração após geração.

[[v19-102-13]]

^<<v19-102-13,13>>^ Tu mesmo te levantarás, terás misericórdia com Sião,
Pois é a época para ser-lhe favorável,
Porque chegou o tempo designado.

[[v19-102-14]]

^<<v19-102-14,14>>^ Pois os teus servos acharam prazer nas pedras dela
E dirigem seu favor ao seu pó.

[[v19-102-15]]

^<<v19-102-15,15>>^ E as nações temerão o nome de Jeová^&#42;1^
E todos os reis da terra a tua glória.

[NOTE]
====
. Veja Ap. 1C sec. 8.
====

[[v19-102-16]]

^<<v19-102-16,16>>^ Porque Jeová^&#42;1^ há de construir Sião;
Ele terá de aparecer na sua glória.

[NOTE]
====
. Veja Ap. 1C sec. 8.
====

[[v19-102-17]]

^<<v19-102-17,17>>^ Ele há de virar-se para a oração dos que foram despojados [de tudo]
E não desprezará a sua oração.

[[v19-102-18]]

^<<v19-102-18,18>>^ Isto está escrito para a geração futura;
E o povo que vai ser criado louvará a Jah.^&#42;1^

[NOTE]
====
. Veja 68:4 n.
====

[[v19-102-19]]

^<<v19-102-19,19>>^ Pois ele olhou para baixo desde a sua altura sagrada,
Jeová^&#42;1^ mesmo, dos próprios céus, olhou para a terra,

[NOTE]
====
. Veja Ap. 1C sec. 8.
====

[[v19-102-20]]

^<<v19-102-20,20>>^ Para ouvir o suspiro do prisioneiro,
Para soltar os destinados à morte;^&#42;1^

[NOTE]
====
. Lit.: “os filhos da morte”.
====

[[v19-102-21]]

^<<v19-102-21,21>>^ Para que o nome de Jeová^&#42;1^ seja declarado^&#42;2^ em Sião
E seu louvor em Jerusalém,

[NOTE]
====
. Veja Ap. 1C sec. 8.
. Lit.: “para declarar o nome de Jeová”.
====

[[v19-102-22]]

^<<v19-102-22,22>>^ Quando os povos estiverem reunidos juntos,
E para os reinos servirem^&#42;1^ a Jeová.

[NOTE]
====
. Ou “adorarem (prestarem serviço sagrado)”. Hebr.: la·‛avódh.
====

[[v19-102-23]]

^<<v19-102-23,23>>^ No caminho ele atribulou meu poder,
Encurtou meus dias.

[[v19-102-24]]

^<<v19-102-24,24>>^ Passei a dizer: “Ó meu Deus,^&#42;1^
Não me retires na metade dos meus dias;
Teus anos são por todas as gerações.^&#42;2^

[NOTE]
====
. “Ó meu Deus.” Hebr.: ’E·lí.
. Lit.: “por (durante) a geração de gerações”.
====

[[v19-102-25]]

^<<v19-102-25,25>>^ Há muito lançaste os alicerces da própria terra
E os céus são o trabalho das tuas mãos.

[[v19-102-26]]

^<<v19-102-26,26>>^ Eles é que perecerão, mas tu mesmo continuarás de pé;^&#42;1^
E todos eles se gastarão como a roupa.
Tu os substituirás assim como a uma vestimenta e eles terminarão a sua vez.

[NOTE]
====
. Ou “existindo”. Veja Êx 9:16 n.: “existência”.
====

[[v19-102-27]]

^<<v19-102-27,27>>^ Mas tu és o mesmo,^&#42;1^ e os teus próprios anos não se completarão.

[NOTE]
====
. Lit.: “tu és ele”.
====

[[v19-102-28]]

^<<v19-102-28,28>>^ Os filhos dos teus servos continuarão residindo;
E sua própria descendência será firmemente estabelecida diante de ti.”

'''

xref:019-salmo/019-salmo-101.adoc#v19-101-0[&#60; Capítulo Anterior] | <<v19-102-0,Topo>> | xref:019-salmo/019-salmo-103.adoc#v19-103-0[Próximo Capítulo &#62;]