include::./index.adoc[]

[[v19-106-0]]
=== Salmos, 106
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v19-106-1]]

^<<v19-106-1,1>>^ Louvai a Jah!^&#42;1^
Agradecei a Jeová, porque ele é bom;
Pois a sua benevolência^&#42;2^ é por tempo indefinido.

[NOTE]
====
. Veja 104:35 n.
. Ou “amor leal”.
====

[[v19-106-2]]

^<<v19-106-2,2>>^ Quem pode enunciar as realizações potentes de Jeová
[Ou] quem pode fazer ouvir todo o seu louvor?

[[v19-106-3]]

^<<v19-106-3,3>>^ Felizes os que observam o juízo,
Praticando^&#42;1^ a justiça todo o tempo.

[NOTE]
====
. “Praticando”, sujeito pl., TLXXSyVg; M: “alguém praticando”.
====

[[v19-106-4]]

^<<v19-106-4,4>>^ Lembra-te de mim, ó Jeová, com a boa vontade para com o teu povo.
Toma conta de mim com a tua salvação,

[[v19-106-5]]

^<<v19-106-5,5>>^ A fim de que eu veja a bondade para com os teus escolhidos,
Para que eu me alegre com a alegria da tua nação,
Para que eu me jacte com a tua herança.

[[v19-106-6]]

^<<v19-106-6,6>>^ Pecamos assim como os nossos antepassados;
Cometemos falta; agimos iniquamente.

[[v19-106-7]]

^<<v19-106-7,7>>^ Quanto aos nossos antepassados no Egito,
Não mostraram ter nenhuma perspicácia quanto às tuas obras maravilhosas.
Não se lembraram da abundância da tua grandiosa benevolência,
Mas foram rebeldes junto ao mar, junto ao Mar Vermelho.

[[v19-106-8]]

^<<v19-106-8,8>>^ E ele passou a salvá-los por causa do Seu nome,
A fim de dar a conhecer a sua potência.

[[v19-106-9]]

^<<v19-106-9,9>>^ Conseqüentemente, ele censurou o Mar Vermelho e este se secou gradualmente;
E ele os fez andar através da água de profundeza^&#42;1^ como através do ermo;

[NOTE]
====
. Ou “através das águas empoladas”. Hebr.: bat·teho·móhth, pl. de tehóhm; LXXVg: “abismo(s)”. Veja Gên 1:2 n.: “profundeza”.
====

[[v19-106-10]]

^<<v19-106-10,10>>^ E assim os salvou da mão do odiador
E os reivindicou da mão do inimigo.

[[v19-106-11]]

^<<v19-106-11,11>>^ E as águas foram cobrir os seus adversários;
Nem sequer um deles sobrou.

[[v19-106-12]]

^<<v19-106-12,12>>^ Então tiveram fé na sua palavra;
Começaram a cantar o seu louvor.

[[v19-106-13]]

^<<v19-106-13,13>>^ Esqueceram-se depressa dos seus trabalhos;
Não ficaram esperando por seu conselho.

[[v19-106-14]]

^<<v19-106-14,14>>^ Mas, mostraram seu desejo egoísta no ermo
E foram pôr Deus^&#42;1^ à prova no deserto.

[NOTE]
====
. “Deus.” Hebr.: ’El.
====

[[v19-106-15]]

^<<v19-106-15,15>>^ E ele passou a conceder-lhes seu pedido
E a enviar-lhes a emaciação^&#42;1^ para dentro da sua alma.

[NOTE]
====
. “Emaciação.” Hebr.: ra·zóhn; T: “magreza”; LXXVg: “saciedade; empanturramento”.
====

[[v19-106-16]]

^<<v19-106-16,16>>^ E começaram a invejar a Moisés no acampamento,
Até mesmo a Arão, o santo de Jeová.

[[v19-106-17]]

^<<v19-106-17,17>>^ Então se abriu a terra e tragou a Datã
E encobriu a assembléia de Abirão.

[[v19-106-18]]

^<<v19-106-18,18>>^ E um fogo foi arder no meio da sua assembléia;
A própria chama devorava os iníquos.

[[v19-106-19]]

^<<v19-106-19,19>>^ Além disso, fizeram em Horebe um bezerro
E curvaram-se diante duma imagem fundida,

[[v19-106-20]]

^<<v19-106-20,20>>^ De modo que trocaram a minha glória^&#42;1^
Pela representação de um touro, um herbívoro.

[NOTE]
====
. “Minha glória.” M: “a glória deles”. Uma das Dezoito Emendas dos soferins, que mudaram a versão, porque a expressão “minha glória” era considerada como pejorativa para Deus. LXXmss.Vg: “sua glória”. Veja Ap. 2B.
====

[[v19-106-21]]

^<<v19-106-21,21>>^ Esqueceram-se de Deus, seu Salvador,^&#42;1^
Aquele que fez grandes coisas no Egito,

[NOTE]
====
. “Deus, seu Salvador.” Hebr.: ’El Moh·shi·‛ám.
====

[[v19-106-22]]

^<<v19-106-22,22>>^ Obras maravilhosas na terra de Cã,
Coisas atemorizantes no Mar Vermelho.

[[v19-106-23]]

^<<v19-106-23,23>>^ E ele estava para dizer que fossem aniquilados,
Se não fosse por Moisés, seu escolhido,
Parado na brecha diante dele,
Para fazer o seu furor recuar de arruiná-los.

[[v19-106-24]]

^<<v19-106-24,24>>^ E chegaram a menosprezar a terra desejável;
Não tinham fé na sua palavra.

[[v19-106-25]]

^<<v19-106-25,25>>^ E estavam murmurando nas suas tendas;
Não escutaram a voz de Jeová.

[[v19-106-26]]

^<<v19-106-26,26>>^ Por isso passou a levantar a mão [em juramento] a seu respeito,
De que os faria cair no ermo,

[[v19-106-27]]

^<<v19-106-27,27>>^ E que faria sua descendência cair entre as nações,
E que os espalharia entre os países.

[[v19-106-28]]

^<<v19-106-28,28>>^ E eles começaram a ligar-se ao Baal de Peor
E a comer dos sacrifícios dos mortos.

[[v19-106-29]]

^<<v19-106-29,29>>^ Visto que estavam ofendendo com as suas ações,
Irrompeu então um flagelo entre eles.

[[v19-106-30]]

^<<v19-106-30,30>>^ Quando Finéias se pôs de pé e interveio,
Então se fez parar o flagelo.

[[v19-106-31]]

^<<v19-106-31,31>>^ E isso veio a ser-lhe contado como justiça,
De geração em geração, por tempo indefinido.

[[v19-106-32]]

^<<v19-106-32,32>>^ Além disso, causaram indignação junto às águas de Meribá,
De modo que, por causa deles, sucedeu mal a Moisés.

[[v19-106-33]]

^<<v19-106-33,33>>^ Pois amarguraram-lhe o espírito^&#42;1^
E ele começou a falar precipitadamente com os seus lábios.

[NOTE]
====
. “O espírito.” Hebr.: ru·hhóh; gr.: pneú·ma; lat.: spí·ri·tum.
====

[[v19-106-34]]

^<<v19-106-34,34>>^ Não aniquilaram os povos
Como Jeová lhes dissera.

[[v19-106-35]]

^<<v19-106-35,35>>^ E foram misturar-se com as nações
E passaram a aprender os seus trabalhos.

[[v19-106-36]]

^<<v19-106-36,36>>^ E continuaram a servir^&#42;1^ a seus ídolos
E estes vieram a ser-lhes um laço.

[NOTE]
====
. Ou: “E continuaram a adorar (prestar serviço sagrado).” Hebr.: wai·ya·‛av·dhú.
====

[[v19-106-37]]

^<<v19-106-37,37>>^ E sacrificavam seus filhos
E suas filhas a demônios.^&#42;1^

[NOTE]
====
. “A demônios (espíritos iníquos)”, M(hebr.: lash·shé·dhim)LXXVg.
====

[[v19-106-38]]

^<<v19-106-38,38>>^ De modo que derramavam sangue inocente,
O sangue de seus filhos e de suas filhas,
Que sacrificaram aos ídolos de Canaã;
E a terra ficou poluída com o derramamento de sangue.^&#42;1^

[NOTE]
====
. Lit.: “sangues”.
====

[[v19-106-39]]

^<<v19-106-39,39>>^ E ficaram impuros pelos seus trabalhos
E continuaram a ter relações imorais pelas suas ações.

[[v19-106-40]]

^<<v19-106-40,40>>^ E a ira de Jeová começou a acender-se contra o seu povo,
E ele chegou a detestar a sua herança.

[[v19-106-41]]

^<<v19-106-41,41>>^ E entregou-os repetidamente na mão das nações,
Para que dominassem sobre eles os que os odiavam,

[[v19-106-42]]

^<<v19-106-42,42>>^ E para que seus inimigos os oprimissem,
E para que fossem subjugados sob a sua mão.

[[v19-106-43]]

^<<v19-106-43,43>>^ Muitas vezes os livrava,
Mas eles mesmos eram rebeldes no seu proceder desobediente
E foram rebaixados pelo seu erro.

[[v19-106-44]]

^<<v19-106-44,44>>^ E ele^&#42;1^ via a sua aflição
Ao ouvir seu clamor suplicante.

[NOTE]
====
. “Ele”, MTSyVg; LXXA e um ms. hebr.: “Jeová”.
====

[[v19-106-45]]

^<<v19-106-45,45>>^ E lembrava-se do seu pacto concernente a eles
E deplorava [isso] segundo a abundância da sua grandiosa benevolência.

[[v19-106-46]]

^<<v19-106-46,46>>^ E concedia-lhes ser objetos de misericórdia
Perante todos os que os mantinham cativos.

[[v19-106-47]]

^<<v19-106-47,47>>^ Salva-nos, ó Jeová, nosso Deus,
E reúne-nos das nações,
Para darmos graças ao teu santo nome,
Para falarmos com exultação em teu louvor.

[[v19-106-48]]

^<<v19-106-48,48>>^ Bendito seja Jeová, o Deus de Israel,
De tempo indefinido a tempo indefinido;
E todo o povo tem de dizer^&#42;1^ amém.
Louvai a Jah!^&#42;2^

[NOTE]
====
. Lit.: “disse”.
. Veja 41:13 n. e 104:35 n.
====

'''

xref:019-salmo/019-salmo-105.adoc#v19-105-0[&#60; Capítulo Anterior] | <<v19-106-0,Topo>> | xref:019-salmo/019-salmo-107.adoc#v19-107-0[Próximo Capítulo &#62;]