include::./index.adoc[]

[[v19-15-0]]
=== Salmos, 15
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

_Uma melodia de Davi._

[[v19-15-1]]

^<<v19-15-1,1>>^ Ó Jeová, quem será hóspede na tua tenda?
Quem residirá no teu santo monte?

[[v19-15-2]]

^<<v19-15-2,2>>^ Aquele que anda sem defeito e pratica a justiça,
E fala a verdade no seu coração.

[[v19-15-3]]

^<<v19-15-3,3>>^ Não caluniou com a sua língua.
Não fez nenhum mal ao seu companheiro,
E não levantou nenhum vitupério contra o seu conhecido íntimo.

[[v19-15-4]]

^<<v19-15-4,4>>^ Aos seus olhos certamente é rejeitado o desprezível,
Mas ele honra aos que temem a Jeová.
Jurou concernente àquilo que é mau [para ele próprio],^&#42;1^ e ainda assim nada modifica.

[NOTE]
====
. “Jurou ao seu próximo”, LXXSyVg.
====

[[v19-15-5]]

^<<v19-15-5,5>>^ Não deu seu dinheiro a juros
E não aceitou suborno contra o inocente.
Quem fizer tais coisas, nunca será abalado.

'''

xref:019-salmo/019-salmo-014.adoc#v19-14-0[&#60; Capítulo Anterior] | <<v19-15-0,Topo>> | xref:019-salmo/019-salmo-016.adoc#v19-16-0[Próximo Capítulo &#62;]