include::./index.adoc[]

[[v19-35-0]]
=== Salmos, 35
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

_De Davi._

[[v19-35-1]]

^<<v19-35-1,1>>^ Pleiteia deveras a minha causa contra os meus oponentes, ó Jeová;^&#42;1^
Guerreia contra os que guerreiam contra mim.

[NOTE]
====
. Veja Ap. 1C sec. 10.
====

[[v19-35-2]]

^<<v19-35-2,2>>^ Agarra o broquel e o escudo grande
E levanta-te deveras em meu auxílio,

[[v19-35-3]]

^<<v19-35-3,3>>^ E puxa da lança e da acha bipene para enfrentar os que me perseguem.
Dize à minha alma: “Sou a tua salvação.”

[[v19-35-4]]

^<<v19-35-4,4>>^ Sejam envergonhados e humilhados os que caçam a minha alma.
Faça-se que tornem atrás e fiquem encabulados os que maquinam calamidade para mim.

[[v19-35-5]]

^<<v19-35-5,5>>^ Tornem-se eles como a pragana diante do vento,
E empurre-os o anjo de Jeová.

[[v19-35-6]]

^<<v19-35-6,6>>^ Torne-se o caminho deles em escuridão e em lugares escorregadios,
E persiga-os o anjo de Jeová.

[[v19-35-7]]

^<<v19-35-7,7>>^ Pois, sem causa encobriram de mim a sua cova de redes;
Sem causa a cavaram para a minha alma.^&#42;1^

[NOTE]
====
. “Para a minha alma.” Hebr.: lenaf·shí; gr.: psy·khén; lat.: á·ni·mam. Veja Ap. 4A.
====

[[v19-35-8]]

^<<v19-35-8,8>>^ Venha sobre ele a ruína sem que o saiba
E apanhe-o a sua própria rede que encobriu;
Caia nela com ruína.

[[v19-35-9]]

^<<v19-35-9,9>>^ Mas jubile a minha própria alma em Jeová;
Exulte ela na sua salvação.

[[v19-35-10]]

^<<v19-35-10,10>>^ Digam todos os meus ossos:
“Ó Jeová, quem é semelhante a ti,
Livrando o atribulado daquele que é mais forte do que ele,
E o atribulado e o pobre, daquele que o rouba?”

[[v19-35-11]]

^<<v19-35-11,11>>^ Levantam-se testemunhas violentas;
Perguntam-me o que não sei.

[[v19-35-12]]

^<<v19-35-12,12>>^ Retribuem-me o mal pelo bem,
A privação para a minha alma.

[[v19-35-13]]

^<<v19-35-13,13>>^ Eu, porém, quando ficaram doentes, usei serapilheira por vestimenta,
Atribulei a minha alma com jejum,
E a minha própria oração retornava ao meu seio.

[[v19-35-14]]

^<<v19-35-14,14>>^ Por um companheiro, por um irmão meu,
Andei em volta como quem pranteia a mãe.
Entristecido, encurvei-me.

[[v19-35-15]]

^<<v19-35-15,15>>^ Eles, porém, se alegraram e se ajuntaram quando manquejei.
Ajuntaram-se contra mim,
Golpeando-me quando eu não o sabia;
Rasgaram-me em pedaços e não ficaram quietos.

[[v19-35-16]]

^<<v19-35-16,16>>^ Entre os caçoadores que apostatam por um bolo,^&#42;1^
Foi contra mim que houve o ranger^&#42;2^ dos seus dentes.

[NOTE]
====
. “Os caçoadores que apostatam por um bolo”, isto é, fanfarrões ímpios.
. “Houve o ranger.” No hebr., este é um verbo no infinitivo absoluto, indefinido quanto ao tempo e impessoal.
====

[[v19-35-17]]

^<<v19-35-17,17>>^ Ó Jeová,^&#42;1^ até quando continuarás a ver [isso]?
Faze deveras a minha alma voltar das suas assolações,
Sim, a minha única,^&#42;2^ dos leões novos jubados.

[NOTE]
====
. Uma das 134 mudanças de YHWH para ’Adho·naí feitas pelos escribas. Veja Ap. 1B.
. “A minha única”, hebr. fem., referindo-se a “minha alma”, hebr. fem.
====

[[v19-35-18]]

^<<v19-35-18,18>>^ Vou elogiar-te na grande congregação;^&#42;1^
Louvar-te-ei entre um povo numeroso.

[NOTE]
====
. “Na grande congregação.” Hebr.: beqa·hál rav; gr.: ek·kle·sí·ai; lat.: ec·clé·si·a.
====

[[v19-35-19]]

^<<v19-35-19,19>>^ Que não se alegrem de mim os que por razão nenhuma são meus inimigos;
Quanto aos que me odeiam sem causa, não pisquem eles o olho.

[[v19-35-20]]

^<<v19-35-20,20>>^ Pois não falam de paz;
Mas contra os quietos da terra
Estão maquinando coisas de engano.

[[v19-35-21]]

^<<v19-35-21,21>>^ Contra mim é que abrem muito a sua boca.
Disseram: “Ah! Ah! Nosso olho [o] viu.”

[[v19-35-22]]

^<<v19-35-22,22>>^ Tu [o] viste, ó Jeová.^&#42;1^ Não fiques calado.^&#42;2^
Ó Jeová,^&#42;3^ não te mantenhas longe de mim.

[NOTE]
====
. Veja Ap. 1C sec. 10.
. Ou: “Não sejas surdo.”
. Veja v. 17 n.: “Jeová”.
====

[[v19-35-23]]

^<<v19-35-23,23>>^ Desperta deveras^&#42;1^ e acorda para o meu julgamento,
Ó meu Deus, sim, Jeová,^&#42;2^ para a minha causa jurídica.

[NOTE]
====
. LXX acrescenta: “ó Jeová”.
. Veja v. 17 n.: “Jeová”.
====

[[v19-35-24]]

^<<v19-35-24,24>>^ Julga-me segundo a tua justiça, ó Jeová,^&#42;1^ meu Deus,
E não se alegrem eles por minha causa.

[NOTE]
====
. Veja Ap. 1C sec. 10.
====

[[v19-35-25]]

^<<v19-35-25,25>>^ Oh! não digam no seu coração: “Ah! Nossa alma!”^&#42;1^
Não digam: “Nós o tragamos.”

[NOTE]
====
. Isto é: ‘O que as nossas almas queriam!’
====

[[v19-35-26]]

^<<v19-35-26,26>>^ Sejam juntos envergonhados e encabulados
Os que se alegram da minha calamidade.
Sejam vestidos de vergonha e de humilhação os que assumem ares de grandeza contra mim.

[[v19-35-27]]

^<<v19-35-27,27>>^ Gritem de júbilo e alegrem-se os que se agradam da minha justiça,
E digam constantemente:
“Magnificado seja Jeová^&#42;1^ que se agrada da paz do seu servo.”

[NOTE]
====
. Veja Ap. 1C sec. 10.
====

[[v19-35-28]]

^<<v19-35-28,28>>^ E a minha própria língua profira em voz baixa a tua justiça,
O teu louvor, o dia inteiro.

'''

xref:019-salmo/019-salmo-034.adoc#v19-34-0[&#60; Capítulo Anterior] | <<v19-35-0,Topo>> | xref:019-salmo/019-salmo-036.adoc#v19-36-0[Próximo Capítulo &#62;]