include::./index.adoc[]

[[v19-19-0]]
=== Salmos, 19
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

_Ao regente. Uma melodia de Davi._

[[v19-19-1]]

^<<v19-19-1,1>>^ Os céus declaram a glória de Deus;^&#42;1^
E a expansão está contando o trabalho das suas mãos.

[NOTE]
====
. “Deus.” Hebr.: ’El.
====

[[v19-19-2]]

^<<v19-19-2,2>>^ Um dia após outro dia faz borbulhar a fala,
E uma noite após outra noite exibe conhecimento.

[[v19-19-3]]

^<<v19-19-3,3>>^ Não há fala e não há palavras;
Nenhuma voz se ouve da sua parte.

[[v19-19-4]]

^<<v19-19-4,4>>^ Seu cordel de medir^&#42;1^ saiu por toda a terra
E suas expressões até a extremidade do solo produtivo.^&#42;2^
Neles colocou uma tenda para o sol,

[NOTE]
====
. “Seu cordel de medir.” Hebr.: qaw·wám; LXXVg: “som”; Sy: “notícias”.
. “Solo produtivo.” Hebr.: the·vél; LXX: “terra habitada”; lat.: ór·bis tér·rae, “círculo da terra”.
====

[[v19-19-5]]

^<<v19-19-5,5>>^ E este é como um noivo quando sai da câmara nupcial;
Exulta como um poderoso para correr numa vereda.

[[v19-19-6]]

^<<v19-19-6,6>>^ Sai de uma extremidade dos céus
E sua volta [completa] vai até as suas [outras] extremidades;
E não há nada escondido do seu calor.

[[v19-19-7]]

^<<v19-19-7,7>>^ A lei de Jeová é perfeita, fazendo retornar a alma.
A advertência de Jeová é fidedigna, tornando sábio o inexperiente.

[[v19-19-8]]

^<<v19-19-8,8>>^ As ordens de Jeová são retas, fazendo o coração alegrar-se;
O mandamento de Jeová é limpo, fazendo os olhos brilhar.

[[v19-19-9]]

^<<v19-19-9,9>>^ O temor de Jeová é puro, permanecendo de pé para todo o sempre.
As decisões judiciais de Jeová são verdadeiras;^&#42;1^ mostraram-se inteiramente justas.

[NOTE]
====
. Lit.: “verdade”.
====

[[v19-19-10]]

^<<v19-19-10,10>>^ São mais desejáveis do que o ouro,^&#42;1^ sim, mais do que muito ouro refinado;^&#42;2^
E são mais doces do que o mel e o mel escorrendo dos favos.

[NOTE]
====
. “Do que o ouro.” Hebr.: miz·za·háv.
. “Sim, mais do que . . . ouro refinado.” Hebr.: u·mip·páz.
====

[[v19-19-11]]

^<<v19-19-11,11>>^ Também o teu próprio servo foi avisado por elas;
Há grande recompensa em guardá-las.

[[v19-19-12]]

^<<v19-19-12,12>>^ Enganos — quem pode discernir?
Declara-me inocente de pecados escondidos.

[[v19-19-13]]

^<<v19-19-13,13>>^ Refreia também teu servo de atos presunçosos;^&#42;1^
Não deixes que me dominem.
Neste caso serei completo
E terei permanecido inocente de muita transgressão.

[NOTE]
====
. Ou “de homens presunçosos; de presunçosos [masc. pl.]”.
====

[[v19-19-14]]

^<<v19-19-14,14>>^ As declarações de minha boca e a meditação de meu coração,
Tornem-se elas agradáveis diante de ti, ó Jeová, minha Rocha e meu Redentor.^&#42;1^

[NOTE]
====
. “E meu Redentor (Resgatador).” Ampliando-se a idéia: “e meu Vingador (Vindicador)”. Hebr.: wegho·’alí; lat.: re·dém·ptor. Veja Jó 19:25; Pr 23:11.
====

'''

xref:019-salmo/019-salmo-018.adoc#v19-18-0[&#60; Capítulo Anterior] | <<v19-19-0,Topo>> | xref:019-salmo/019-salmo-020.adoc#v19-20-0[Próximo Capítulo &#62;]