include::./index.adoc[]

[[v19-31-0]]
=== Salmos, 31
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

_Ao regente. Uma melodia de Davi._

[[v19-31-1]]

^<<v19-31-1,1>>^ Em ti me refugiei, ó Jeová.^&#42;1^
Nunca seja eu envergonhado.
Na tua justiça, põe-me a salvo.

[NOTE]
====
. Veja Ap. 1C sec. 10.
====

[[v19-31-2]]

^<<v19-31-2,2>>^ Inclina-me teu ouvido.
Livra-me depressa.
Torna-te para mim um baluarte rochoso,
Uma casa de fortalezas para me salvar.

[[v19-31-3]]

^<<v19-31-3,3>>^ Pois tu és meu rochedo e minha fortaleza;
E tu me guiarás e me conduzirás por causa do teu nome.

[[v19-31-4]]

^<<v19-31-4,4>>^ Tu me tirarás da rede que encobriram para mim,
Porque és meu baluarte.

[[v19-31-5]]

^<<v19-31-5,5>>^ À tua mão confio o meu espírito.
Tu me remiste, ó Jeová,^&#42;1^ Deus da verdade.^&#42;2^

[NOTE]
====
. Veja Ap. 1C sec. 10.
. “Deus da verdade.” Ou “o verdadeiro Deus”. Hebr.: ’El ’eméth.
====

[[v19-31-6]]

^<<v19-31-6,6>>^ Odeio deveras os que dão consideração a ídolos vãos, fúteis;^&#42;1^
Eu, porém, confio deveras em Jeová.^&#42;2^

[NOTE]
====
. Lit.: “vaidades”.
. Veja Ap. 1C sec. 10.
====

[[v19-31-7]]

^<<v19-31-7,7>>^ Vou jubilar e alegrar-me na tua benevolência,^&#42;1^
Porque tens visto a minha tribulação;
Soubeste das aflições da minha alma

[NOTE]
====
. Ou “amor leal”.
====

[[v19-31-8]]

^<<v19-31-8,8>>^ E não me entregaste na mão do inimigo.
Fizeste meus pés ficar postos num lugar espaçoso.

[[v19-31-9]]

^<<v19-31-9,9>>^ Mostra-me favor, ó Jeová,^&#42;1^ porque estou em sério aperto.
Com o vexame se enfraqueceu meu olho, minha alma e meu ventre.

[NOTE]
====
. Veja Ap. 1C sec. 10.
====

[[v19-31-10]]

^<<v19-31-10,10>>^ Pois é com pesar que minha vida tem chegado ao fim,
E meus anos, com suspiro.
Tropeçou meu poder por causa do meu erro,
E meus próprios ossos ficaram fracos.

[[v19-31-11]]

^<<v19-31-11,11>>^ Do ponto de vista de todos os que me são hostis tornei-me um vitupério,
E isso muito para os meus vizinhos,
E um pavor para os meus conhecidos.
Ao me verem portas afora, fugiram de mim.

[[v19-31-12]]

^<<v19-31-12,12>>^ Igual a alguém morto [e] não no coração, fui esquecido;
Tornei-me como um vaso danificado;^&#42;1^

[NOTE]
====
. Ou “faltante”.
====

[[v19-31-13]]

^<<v19-31-13,13>>^ Pois ouvi o relato mau da parte de muitos,
Havendo horror por todos os lados.
Quando se aglomeram à uma contra mim,
Tramam tirar-me a alma.^&#42;1^

[NOTE]
====
. Ou “[tirar-]me a vida”. Hebr.: naf·shí; gr.: psy·khén; lat.: á·ni·mam.
====

[[v19-31-14]]

^<<v19-31-14,14>>^ Eu, porém — em ti tenho posto a minha confiança, ó Jeová.
Eu disse: “Tu és o meu Deus.”^&#42;1^

[NOTE]
====
. “Meu Deus.” Hebr.: ’Elo·haí.
====

[[v19-31-15]]

^<<v19-31-15,15>>^ Meus tempos estão na tua mão.
Livra-me da mão dos meus inimigos e dos que me perseguem.

[[v19-31-16]]

^<<v19-31-16,16>>^ Faze a tua face luzir sobre o teu servo.
Salva-me na tua benevolência.

[[v19-31-17]]

^<<v19-31-17,17>>^ Ó Jeová, não seja eu envergonhado, pois te invoquei.
Fiquem envergonhados os iníquos;
Fiquem eles quietos no Seol.

[[v19-31-18]]

^<<v19-31-18,18>>^ Fiquem mudos os lábios falsos
Que falam irrestritamente contra o justo em altivez e em desprezo.

[[v19-31-19]]

^<<v19-31-19,19>>^ Quão abundante é a tua bondade que entesouraste para os que te temem!
[Que] concedeste aos que se refugiam em ti,
Diante dos filhos dos homens.^&#42;1^

[NOTE]
====
. Ou “homens terrenos”. Hebr.: ’a·dhám.
====

[[v19-31-20]]

^<<v19-31-20,20>>^ Tu os esconderás no lugar secreto da tua pessoa,^&#42;1^
Da coligação dos homens.^&#42;2^
Tu os ocultarás na tua barraca, da altercação das línguas.

[NOTE]
====
. Lit.: “face”. Veja 2Sa 17:11 n.: “pessoa”.
. “Homens.” Hebr.: ’ish.
====

[[v19-31-21]]

^<<v19-31-21,21>>^ Bendito seja Jeová,^&#42;1^
Porque me concedeu benevolência maravilhosa numa cidade em aperto.

[NOTE]
====
. Veja Ap. 1C sec. 10.
====

[[v19-31-22]]

^<<v19-31-22,22>>^ Quanto a mim, eu disse quando fiquei em pânico:
“Certamente serei exterminado de diante dos teus olhos.”
Decerto ouviste a voz dos meus rogos quando clamei a ti por ajuda.

[[v19-31-23]]

^<<v19-31-23,23>>^ Amai a Jeová,^&#42;1^ todos os que lhe sois leais.
Jeová^&#42;2^ resguarda os fiéis,
Mas retribui em extremo a qualquer que mostra altivez.

[NOTE]
====
. Veja Ap. 1C sec. 10.
. Veja Ap. 1C sec. 10.
====

[[v19-31-24]]

^<<v19-31-24,24>>^ Sede corajosos e fortifique-se o vosso coração,
Todos vós os que esperais por Jeová.^&#42;1^

[NOTE]
====
. Veja Ap. 1C sec. 10.
====

'''

xref:019-salmo/019-salmo-030.adoc#v19-30-0[&#60; Capítulo Anterior] | <<v19-31-0,Topo>> | xref:019-salmo/019-salmo-032.adoc#v19-32-0[Próximo Capítulo &#62;]