include::./index.adoc[]

[[v19-118-0]]
=== Salmos, 118
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v19-118-1]]

^<<v19-118-1,1>>^ Agradecei a Jeová, porque ele é bom;
Pois a sua benevolência é por tempo indefinido.

[[v19-118-2]]

^<<v19-118-2,2>>^ Diga então Israel:
“Pois a sua benevolência é por tempo indefinido.”

[[v19-118-3]]

^<<v19-118-3,3>>^ Digam então os da casa de Arão:
“Pois a sua benevolência é por tempo indefinido.”

[[v19-118-4]]

^<<v19-118-4,4>>^ Digam então os que temem a Jeová:
“Pois a sua benevolência é por tempo indefinido.”

[[v19-118-5]]

^<<v19-118-5,5>>^ Das circunstâncias aflitivas invoquei a Jah;^&#42;1^
Jah me respondeu [e me pôs] num lugar espaçoso.^&#42;2^

[NOTE]
====
. Veja 68:4 n.
. “Ele me respondeu com o lugar espaçoso (amplo) de Jah”, segundo muitos mss. hebr.
====

[[v19-118-6]]

^<<v19-118-6,6>>^ Jeová está do meu lado;^&#42;1^ não terei medo.
Que me pode fazer o homem terreno?^&#42;2^

[NOTE]
====
. Ou: “Jeová é meu (pertence a mim).”
. “Homem terreno.” Hebr.: ’a·dhám.
====

[[v19-118-7]]

^<<v19-118-7,7>>^ Jeová está do meu lado entre os que me ajudam,
De modo que eu mesmo olharei para os que me odeiam.

[[v19-118-8]]

^<<v19-118-8,8>>^ Melhor é refugiar-se em Jeová
Do que confiar no homem terreno.

[[v19-118-9]]

^<<v19-118-9,9>>^ Melhor é refugiar-se em Jeová
Do que confiar nos nobres.

[[v19-118-10]]

^<<v19-118-10,10>>^ As próprias nações me cercaram todas elas.
Foi em nome de Jeová que as mantive à distância.

[[v19-118-11]]

^<<v19-118-11,11>>^ Cercaram-me, sim, tinham-me cercado.
Foi em nome de Jeová que as mantive à distância.

[[v19-118-12]]

^<<v19-118-12,12>>^ Cercaram-me como abelhas;
Foram apagadas como um fogo de espinheiros.
Foi em nome de Jeová que as mantive à distância.

[[v19-118-13]]

^<<v19-118-13,13>>^ Empurraste-me fortemente para que eu caísse,
Mas o próprio Jeová me ajudou.

[[v19-118-14]]

^<<v19-118-14,14>>^ Jah é meu abrigo e [meu] poder,^&#42;1^
E ele se torna salvação para mim.

[NOTE]
====
. Possivelmente: “Jah é minha força e [minha] melodia.”
====

[[v19-118-15]]

^<<v19-118-15,15>>^ A voz de clamor jubilante e de salvação
Está nas tendas dos justos.
A direita de Jeová está demonstrando energia vital.

[[v19-118-16]]

^<<v19-118-16,16>>^ A direita de Jeová [se]^&#42;1^ está exaltando;
A direita de Jeová está demonstrando energia vital.

[NOTE]
====
. “Me”, LXXSyVg.
====

[[v19-118-17]]

^<<v19-118-17,17>>^ Não morrerei, mas continuarei vivendo,
Para narrar os trabalhos de Jah.^&#42;1^

[NOTE]
====
. “Jah.” Hebr.: Yah; LXXSyVg: “Jeová”.
====

[[v19-118-18]]

^<<v19-118-18,18>>^ Jah corrigiu-me severamente,
Mas não me entregou à própria morte.

[[v19-118-19]]

^<<v19-118-19,19>>^ Abri-me os portões da justiça.
Entrarei neles; elogiarei a Jah.^&#42;1^

[NOTE]
====
. Veja 68:4 n.
====

[[v19-118-20]]

^<<v19-118-20,20>>^ Este é o portão de Jeová.
Os justos é que entrarão por ele.

[[v19-118-21]]

^<<v19-118-21,21>>^ Eu te elogiarei, pois tu me respondeste
E vieste a ser minha salvação.

[[v19-118-22]]

^<<v19-118-22,22>>^ A pedra que os construtores rejeitaram
Tem-se tornado a principal do ângulo.

[[v19-118-23]]

^<<v19-118-23,23>>^ Isto veio a ser da parte do próprio Jeová;
É^&#42;1^ maravilhoso aos nossos olhos.

[NOTE]
====
. “Isto . . . é”, ambos hebr. fem.; possivelmente referindo-se à “pedra”, hebr. fem., no v. 22.
====

[[v19-118-24]]

^<<v19-118-24,24>>^ Este é o dia feito por Jeová;^&#42;1^
Nele jubilaremos e nos alegraremos.

[NOTE]
====
. Ou: “Este é o dia em que Jeová [o] fez.”
====

[[v19-118-25]]

^<<v19-118-25,25>>^ Ai! Jeová, salva deveras, por favor!
Ai! Jeová, concede deveras bom êxito, por favor!

[[v19-118-26]]

^<<v19-118-26,26>>^ Bendito Aquele que vem em nome de Jeová;
Abençoamo-vos da casa de Jeová.

[[v19-118-27]]

^<<v19-118-27,27>>^ Jeová é o Divino,^&#42;1^
E ele nos dá luz.
Prendei a procissão festiva com ramos
Até os chifres do altar.

[NOTE]
====
. “Divino.” Ou “Deus”. Hebr.: ’El.
====

[[v19-118-28]]

^<<v19-118-28,28>>^ Tu és o meu Divino e eu te elogiarei;
Meu Deus^&#42;1^ — eu te exaltarei.

[NOTE]
====
. “Meu Deus.” Hebr.: ’Elo·haí.
====

[[v19-118-29]]

^<<v19-118-29,29>>^ Agradecei a Jeová, porque ele é bom;
Pois a sua benevolência é por tempo indefinido.

'''

xref:019-salmo/019-salmo-117.adoc#v19-117-0[&#60; Capítulo Anterior] | <<v19-118-0,Topo>> | xref:019-salmo/019-salmo-119.adoc#v19-119-0[Próximo Capítulo &#62;]