include::./index.adoc[]

[[v50-3-0]]
=== Filipenses, 3
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v50-3-1]]

^<<v50-3-1,1>>^ Por fim, meus irmãos, continuai a alegrar-vos no Senhor. Não me é molesto escrever-vos as mesmas coisas, mas é de segurança para vós.

[[v50-3-2]]

^<<v50-3-2,2>>^ Acautelai-vos dos cães, acautelai-vos dos obreiros do dano, acautelai-vos dos que mutilam a carne.^&#42;1^

[NOTE]
====
. “Dos que mutilam a carne.” Ou “da incisão”. Lit.: “do corte”.
====

[[v50-3-3]]

^<<v50-3-3,3>>^ Pois nós somos os que temos a verdadeira circuncisão,^&#42;1^ os que prestamos serviço sagrado^&#42;2^ pelo espírito de Deus e temos a nossa jactância em Cristo Jesus, e não temos a nossa confiança na carne,

[NOTE]
====
. Lit.: “nós somos a circuncisão”.
. “Prestamos serviço sagrado.” Gr.: la·treú·on·tes; J17(hebr.): ha·‛o·vedhím, “que servimos (adoramos)”. Veja Êx 3:12 n.
====

[[v50-3-4]]

^<<v50-3-4,4>>^ se bem que eu, mais que qualquer outro, teria base para ter também confiança na carne.
Se qualquer outro homem acha que tem base para ter confiança na carne, eu ainda mais;

[[v50-3-5]]

^<<v50-3-5,5>>^ circuncidado no oitavo dia, da linhagem de Israel, da tribo de Benjamim, hebreu [nascido] de hebreus; com respeito à lei, fariseu;

[[v50-3-6]]

^<<v50-3-6,6>>^ com respeito ao zelo, perseguindo a congregação; com respeito à justiça que é por meio de lei, um que se mostrou inculpe.

[[v50-3-7]]

^<<v50-3-7,7>>^ Contudo, as coisas que para mim eram ganhos, estas eu considerei perda por causa do Cristo.

[[v50-3-8]]

^<<v50-3-8,8>>^ Ora, neste respeito, considero também, deveras, todas as coisas como perda, por causa do valor superior do conhecimento de Cristo Jesus, meu Senhor. Por causa dele tenho aceito a perda de todas as coisas e as considero como uma porção de refugo, para que eu possa ganhar a Cristo

[[v50-3-9]]

^<<v50-3-9,9>>^ e ser achado em união com ele, não tendo a minha própria justiça, que resulta da lei, mas aquela que vem por intermédio da fé em Cristo, a justiça que procede de Deus, à base da fé,

[[v50-3-10]]

^<<v50-3-10,10>>^ a fim de conhecer a ele e o poder de sua ressurreição, e a participação nos seus sofrimentos, submetendo-me a uma morte semelhante à dele,

[[v50-3-11]]

^<<v50-3-11,11>>^ [para ver] se de algum modo consigo alcançar a ressurreição [a ocorrer] mais cedo^&#42;1^ dentre os mortos.

[NOTE]
====
. “Ressurreição [a ocorrer] mais cedo.” Lit.: “dentre-ressurreição”. Gr.: e·xa·ná·sta·sin.
====

[[v50-3-12]]

^<<v50-3-12,12>>^ Não é que eu já tenha recebido isso ou que eu já tenha sido aperfeiçoado, mas empenho-me para ver se posso também obter aquilo pelo qual também fui obtido por Cristo Jesus.^&#42;1^

[NOTE]
====
. “Jesus”, P46אAVg; BD omitem isso.
====

[[v50-3-13]]

^<<v50-3-13,13>>^ Irmãos, não me considero ainda como [o] tendo obtido; mas há uma coisa a respeito disso: Esquecendo-me das coisas atrás e esticando-me para [alcançar] as coisas na frente,

[[v50-3-14]]

^<<v50-3-14,14>>^ empenho-me para [alcançar] o alvo do prêmio^&#42;1^ da chamada para cima, da parte de Deus, por meio de Cristo Jesus.

[NOTE]
====
. Lit.: “para dentro do prêmio”.
====

[[v50-3-15]]

^<<v50-3-15,15>>^ Tenhamos então esta atitude mental, tantos quantos formos maduros; e, se estiverdes mentalmente inclinados em outro sentido, Deus vos revelará a [atitude] indicada.

[[v50-3-16]]

^<<v50-3-16,16>>^ De qualquer modo, ao ponto que fizemos progresso, prossigamos andando ordeiramente nesta mesma rotina.^&#42;1^

[NOTE]
====
. Lit.: “no mesmo andar na linha”.
====

[[v50-3-17]]

^<<v50-3-17,17>>^ Tornai-vos unidamente imitadores meus, irmãos, e ficai observando os que estão andando dum modo que está de acordo com o exemplo que tendes em nós.

[[v50-3-18]]

^<<v50-3-18,18>>^ Pois há muitos, os quais eu costumava mencionar muitas vezes, mas agora os menciono também com choro, que estão andando como inimigos da estaca de tortura^&#42;1^ do Cristo,

[NOTE]
====
. Veja Ap. 5C.
====

[[v50-3-19]]

^<<v50-3-19,19>>^ e o seu fim^&#42;1^ é a destruição, e o seu deus é o ventre, e a sua glória consiste na sua vergonha, e eles fixam as suas mentes nas coisas da terra.

[NOTE]
====
. Ou “fim; remate”. Gr.: té·los.
====

[[v50-3-20]]

^<<v50-3-20,20>>^ Quanto a nós, a nossa cidadania^&#42;1^ existe nos céus, donde também aguardamos ansiosamente um salvador, o Senhor Jesus Cristo,

[NOTE]
====
. Ou “a nossa vida como cidadãos”.
====

[[v50-3-21]]

^<<v50-3-21,21>>^ o qual remodelará o nosso corpo humilhado^&#42;1^ para ser conforme ao seu corpo glorioso,^&#42;2^ segundo a operação do poder que ele tem, sim, de sujeitar todas as coisas a si mesmo.

[NOTE]
====
. Lit.: “o corpo de nossa humildade (inferioridade)”.
. Lit.: “ao corpo de sua glória”.
====

'''

xref:050-filipenses/050-filipenses-002.adoc#v50-2-0[&#60; Capítulo Anterior] | <<v50-3-0,Topo>> | xref:050-filipenses/050-filipenses-004.adoc#v50-4-0[Próximo Capítulo &#62;]