include::./index.adoc[]

[[v50-4-0]]
=== Filipenses, 4
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v50-4-1]]

^<<v50-4-1,1>>^ Por conseguinte, meus amados e saudosos irmãos, minha alegria e coroa, mantende-vos deste modo firmes no Senhor,^&#42;1^ amados.

[NOTE]
====
. “Senhor”, אABVg; J7,8,13,14,16,24: “Jeová”.
====

[[v50-4-2]]

^<<v50-4-2,2>>^ Exorto Evódia e exorto Síntique a serem da mesma mentalidade no Senhor.

[[v50-4-3]]

^<<v50-4-3,3>>^ Sim, solicito-te também, genuíno companheiro de jugo, que persistas em auxiliar estas [mulheres], que se esforçaram lado a lado comigo nas boas novas, em companhia de Clemente bem como dos demais colaboradores meus, cujos nomes estão no livro da vida.

[[v50-4-4]]

^<<v50-4-4,4>>^ Alegrai-vos sempre no Senhor.^&#42;1^ Mais uma vez direi: Alegrai-vos!

[NOTE]
====
. “Senhor”, אABVg; J7,8,13,14,16,24: “Jeová”.
====

[[v50-4-5]]

^<<v50-4-5,5>>^ Seja a vossa razoabilidade conhecida de todos os homens. O Senhor^&#42;1^ está perto.

[NOTE]
====
. “O Senhor”, אABVg; J7,8: “Jeová”.
====

[[v50-4-6]]

^<<v50-4-6,6>>^ Não estejais ansiosos de coisa alguma, mas em tudo, por oração e súplica, junto com agradecimento, fazei conhecer as vossas petições a Deus;

[[v50-4-7]]

^<<v50-4-7,7>>^ e a paz de Deus, que excede todo pensamento, guardará os vossos corações e as vossas faculdades mentais por meio de Cristo Jesus.

[[v50-4-8]]

^<<v50-4-8,8>>^ Por fim, irmãos, todas as coisas^&#42;1^ que são verdadeiras, todas as que são de séria preocupação, todas as que são justas, todas as que são castas, todas as que são amáveis,^&#42;2^ todas as coisas de que se fala bem, toda virtude que há e toda coisa louvável que há, continuai a considerar tais coisas.

[NOTE]
====
. Lit.: “tantas (coisas) quantas”.
. Lit.: “que induzem à afeição”.
====

[[v50-4-9]]

^<<v50-4-9,9>>^ As coisas que aprendestes bem como aceitastes, e ouvistes, e vistes, em conexão comigo, estas praticai; e o Deus de paz estará convosco.

[[v50-4-10]]

^<<v50-4-10,10>>^ Eu me alegro grandemente no Senhor^&#42;1^ de que agora, por fim, reanimastes a vossa maneira de pensar a meu respeito, à qual realmente destes consideração, mas faltou-vos a oportunidade.

[NOTE]
====
. “Senhor”, אABVg; J7,8,13,14,16,24: “Jeová”.
====

[[v50-4-11]]

^<<v50-4-11,11>>^ Não é que eu esteja falando com respeito a ter carência, pois aprendi a ser auto-suficiente^&#42;1^ em qualquer circunstância em que esteja.

[NOTE]
====
. Ou “estar contente”.
====

[[v50-4-12]]

^<<v50-4-12,12>>^ Eu sei, deveras, estar reduzido [em provisões], sei, deveras, ter abundância. Em tudo e em todas as circunstâncias aprendi o segredo tanto de estar suprido como de ter fome, tanto de ter abundância como de sofrer carência.

[[v50-4-13]]

^<<v50-4-13,13>>^ Para todas as coisas tenho força em virtude daquele que me confere poder.

[[v50-4-14]]

^<<v50-4-14,14>>^ Não obstante, agistes bem em vos tornardes parceiros meus na minha tribulação.

[[v50-4-15]]

^<<v50-4-15,15>>^ De fato, vós, filipenses, sabeis também que, quando se principiou a declarar as boas novas, quando parti da Macedônia, nenhuma congregação tomou parte comigo no assunto de dar e de receber, exceto somente vós;

[[v50-4-16]]

^<<v50-4-16,16>>^ porque até mesmo me enviastes algo a Tessalônica, tanto uma vez como uma segunda vez, para as minhas necessidades.

[[v50-4-17]]

^<<v50-4-17,17>>^ Não é que eu esteja seriamente buscando a dádiva, mas é que estou seriamente buscando os frutos que trazem mais crédito para a vossa conta.

[[v50-4-18]]

^<<v50-4-18,18>>^ No entanto, tenho plenamente todas as coisas e tenho abundância. Estou suprido, agora que recebi de Epafrodito as coisas [provenientes] de vós, um cheiro fragrante, um sacrifício aceitável, bem agradável a Deus.^&#42;1^

[NOTE]
====
. “Deus”, אABVgSyp; J7,8: “Jeová”.
====

[[v50-4-19]]

^<<v50-4-19,19>>^ Meu Deus, por sua vez, suprirá plenamente todas as vossas necessidades ao alcance das suas riquezas, em glória, por meio de Cristo Jesus.

[[v50-4-20]]

^<<v50-4-20,20>>^ Ora, a nosso Deus e Pai seja [dada] a glória para todo o sempre. Amém.

[[v50-4-21]]

^<<v50-4-21,21>>^ Dai os meus cumprimentos a cada santo em união com Cristo Jesus. Os irmãos que estão comigo mandam-vos os seus cumprimentos.

[[v50-4-22]]

^<<v50-4-22,22>>^ Todos os santos, mas especialmente os da família de César,^&#42;1^ mandam-vos os seus cumprimentos.

[NOTE]
====
. Ou “do imperador”.
====

[[v50-4-23]]

^<<v50-4-23,23>>^ A benignidade imerecida do Senhor Jesus Cristo [seja] com o espírito que vós [mostrais].^&#42;1^

[NOTE]
====
. P46אADItVgSyh,pArm terminam com “Amém”; B o omite.
====

'''

xref:050-filipenses/050-filipenses-003.adoc#v50-3-0[&#60; Capítulo Anterior] | <<v50-4-0,Topo>> | xref:051-colossenses/051-colossenses-001.adoc#v51-1-0[Próximo Capítulo &#62;]