include::./index.adoc[]

[[v50-2-0]]
=== Filipenses, 2
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v50-2-1]]

^<<v50-2-1,1>>^ Se há, pois, algum encorajamento em Cristo, se alguma consolação de amor, se alguma partilha do espírito, se quaisquer ternas afeições e compaixões,

[[v50-2-2]]

^<<v50-2-2,2>>^ tornai plena a minha alegria por serdes da mesma mentalidade e terdes o mesmo amor, conjuntados em alma, tendo um só pensamento na mente,

[[v50-2-3]]

^<<v50-2-3,3>>^ não fazendo nada por briga ou por egotismo, mas, com humildade mental, considerando os outros superiores a vós,

[[v50-2-4]]

^<<v50-2-4,4>>^ não visando, em interesse pessoal, apenas os vossos próprios assuntos,^&#42;1^ mas também, em interesse pessoal, os dos outros.

[NOTE]
====
. Lit.: “não nas (coisas) de si mesmos, cada (um)”.
====

[[v50-2-5]]

^<<v50-2-5,5>>^ Mantende em vós esta atitude mental^&#42;1^ que houve também em Cristo Jesus,

[NOTE]
====
. Lit.: “Estai pensando nisso.”
====

[[v50-2-6]]

^<<v50-2-6,6>>^ o qual, embora existisse em forma de Deus, não deu consideração a uma usurpação,^&#42;1^ a saber, que devesse ser igual a Deus.

[NOTE]
====
. Ou “coisa a ser usurpada”. Lit.: “arrebatamento”.
====

[[v50-2-7]]

^<<v50-2-7,7>>^ Não, mas ele se esvaziou e assumiu a forma de escravo, vindo a ser na semelhança dos homens.

[[v50-2-8]]

^<<v50-2-8,8>>^ Mais do que isso, quando se achou na feição de homem, humilhou-se e tornou-se obediente até à morte, sim, morte numa estaca de tortura.^&#42;1^

[NOTE]
====
. Veja Ap. 5C.
====

[[v50-2-9]]

^<<v50-2-9,9>>^ Por esta mesma razão, também, Deus o enalteceu a uma posição superior e lhe deu bondosamente o nome que está acima de todo [outro] nome,

[[v50-2-10]]

^<<v50-2-10,10>>^ a fim de que, no nome de Jesus, se dobre todo joelho dos no céu, e dos na terra, e dos debaixo do chão,

[[v50-2-11]]

^<<v50-2-11,11>>^ e toda língua reconheça abertamente^&#42;1^ que Jesus Cristo é Senhor, para a glória de Deus, o Pai.

[NOTE]
====
. Lit.: “confesse para fora”.
====

[[v50-2-12]]

^<<v50-2-12,12>>^ Conseqüentemente, meus amados, do modo como sempre obedecestes, não somente durante a minha presença, mas agora muito mais prontamente durante a minha ausência, persisti em produzir a vossa própria salvação com temor e tremor;

[[v50-2-13]]

^<<v50-2-13,13>>^ pois Deus é aquele que, por causa do [seu] beneplácito, está agindo em vós, para que tanto queirais como atueis.

[[v50-2-14]]

^<<v50-2-14,14>>^ Persisti em fazer todas as coisas livres de resmungos e de argüições,^&#42;1^

[NOTE]
====
. Lit.: “cálculos divididos; discussões”.
====

[[v50-2-15]]

^<<v50-2-15,15>>^ para que venhais a ser inculpes e inocentes, filhos de Deus sem mácula no meio duma geração pervertida e deturpada, entre a qual estais brilhando como iluminadores no mundo,

[[v50-2-16]]

^<<v50-2-16,16>>^ mantendo-vos firmemente agarrados à palavra da vida, para que eu tenha causa para exultação no dia de Cristo, de que não corri em vão nem trabalhei arduamente em vão.

[[v50-2-17]]

^<<v50-2-17,17>>^ Não obstante, mesmo que eu esteja^&#42;1^ sendo derramado como oferta de bebida^&#42;2^ sobre o sacrifício e serviço público a que vos conduziu a fé, regozijo-me e alegro-me com todos vós.^&#42;3^

[NOTE]
====
. Ou “minha vida esteja; meu sangue esteja”.
. “Oferta de bebida.” Ou “libação”.
. “Congratulo a todos vós”, Vg.
====

[[v50-2-18]]

^<<v50-2-18,18>>^ Ora, do mesmo modo, vós também regozijai-vos e alegrai-vos comigo.^&#42;1^

[NOTE]
====
. “E congratulai-me”, Vg.
====

[[v50-2-19]]

^<<v50-2-19,19>>^ Eu, da minha parte, espero no Senhor Jesus enviar-vos em breve Timóteo, para que eu seja uma alma animada ao ficar sabendo das coisas referentes a vós.

[[v50-2-20]]

^<<v50-2-20,20>>^ Pois não tenho a nenhum outro de disposição igual à dele, que cuidará genuinamente das coisas referentes a vós.

[[v50-2-21]]

^<<v50-2-21,21>>^ Pois todos os outros estão buscando os seus próprios interesses, não os de Cristo Jesus.

[[v50-2-22]]

^<<v50-2-22,22>>^ Vós, porém, conheceis a prova que ele deu de si mesmo, que ele trabalhou como escravo comigo na promoção das boas novas, como um filho junto ao pai.

[[v50-2-23]]

^<<v50-2-23,23>>^ Este, portanto, é o homem que espero enviar assim que eu tiver visto como vão as coisas a meu respeito.

[[v50-2-24]]

^<<v50-2-24,24>>^ Deveras, estou confiante^&#42;1^ no Senhor de que eu mesmo hei de ir também em breve.

[NOTE]
====
. Ou “confio”.
====

[[v50-2-25]]

^<<v50-2-25,25>>^ No entanto, considero necessário enviar-vos Epafrodito, meu irmão e colaborador, e soldado companheiro, mas vosso enviado^&#42;1^ e servidor particular para as minhas necessidades,

[NOTE]
====
. Ou “apóstolo”. Gr.: a·pó·sto·lon.
====

[[v50-2-26]]

^<<v50-2-26,26>>^ visto que ele tem saudade de ver todos vós^&#42;1^ e está deprimido por terdes ouvido que ele adoeceu.

[NOTE]
====
. “Tem saudade de ver todos vós”, א°ACDSyh,hi,pArm; אcBVg: “tem saudade de todos vós”.
====

[[v50-2-27]]

^<<v50-2-27,27>>^ Sim, deveras, ele adoeceu quase a ponto de morrer; mas Deus teve misericórdia dele, de fato, não só dele, mas também de mim, para que eu não tivesse pesar sobre pesar.

[[v50-2-28]]

^<<v50-2-28,28>>^ Por isso eu o envio com a maior pressa, para que, vendo-o, vos alegreis novamente e eu esteja mais livre de pesar.

[[v50-2-29]]

^<<v50-2-29,29>>^ Portanto, dai-lhe a acolhida costumeira no Senhor, com toda a alegria; e tende em estima a homens desta sorte,

[[v50-2-30]]

^<<v50-2-30,30>>^ porque ele chegou quase a morrer por causa da obra do Senhor,^&#42;1^ expondo a sua alma^&#42;2^ ao perigo, a fim de compensar plenamente o não estardes aqui para me prestar serviço particular.

[NOTE]
====
. “Do Senhor”, אA; P46BDItVgSyp: “de Cristo”.
. Ou “vida”.
====

'''

xref:050-filipenses/050-filipenses-001.adoc#v50-1-0[&#60; Capítulo Anterior] | <<v50-2-0,Topo>> | xref:050-filipenses/050-filipenses-003.adoc#v50-3-0[Próximo Capítulo &#62;]