include::./index.adoc[]

[[v31-1-0]]
=== Obadias, 1
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v31-1-1]]

^<<v31-1-1,1>>^ Visão de Obadias:
Assim disse o Soberano Senhor Jeová com respeito a Edom: “Ouvimos uma notícia da parte de Jeová e enviou-se um emissário entre as nações: ‘Levantai-vos, e levantemo-nos contra ela em batalha.’”

[[v31-1-2]]

^<<v31-1-2,2>>^ “Eis que te fiz pequeno entre as nações. És muito desprezado.

[[v31-1-3]]

^<<v31-1-3,3>>^ Enganou-te a presunção de teu coração, tu que resides nos retiros do rochedo, a altura onde ele mora,^&#42;1^ dizendo no seu coração: ‘Quem me fará descer para [a] terra?’

[NOTE]
====
. “Fazendo sua morada no alto”, mediante uma ligeira correção.
====

[[v31-1-4]]

^<<v31-1-4,4>>^ Se fizesses a tua posição tão alta como a águia ou se se colocasse teu ninho entre as estrelas, de lá eu te faria descer”, é a pronunciação de Jeová.

[[v31-1-5]]

^<<v31-1-5,5>>^ “Se chegassem a ti ladrões, se de noite [entrassem] assoladores, até que ponto^&#42;1^ serias silenciado? Não furtariam quanto quisessem? Ou se chegassem a ti vindimadores, não deixariam restar algumas rebuscas?

[NOTE]
====
. Ou: “como?” Hebr.: ’ehkh.
====

[[v31-1-6]]

^<<v31-1-6,6>>^ Até que ponto^&#42;1^ foram devassados os de Esaú! [Como] foram vasculhados os seus tesouros escondidos!

[NOTE]
====
. Veja v. 5 n.
====

[[v31-1-7]]

^<<v31-1-7,7>>^ Enviaram-te até a fronteira. Os próprios homens^&#42;1^ que estavam em pacto contigo enganaram-te todos. Os homens em paz contigo prevaleceram contra ti. Os que [comem] alimento contigo^&#42;2^ colocarão uma rede debaixo de ti como alguém em quem não há discernimento.

[NOTE]
====
. “Homens.” Hebr.: an·shéh, pl. de ’ish.
. Lit.: “[Os do] teu pão.”
====

[[v31-1-8]]

^<<v31-1-8,8>>^ Não será naquele dia?” é a pronunciação de Jeová.
“E eu hei de destruir os sábios dentre Edom e o discernimento dentre a região montanhosa de Esaú.

[[v31-1-9]]

^<<v31-1-9,9>>^ E teus poderosos hão de ficar aterrorizados, ó Temã, visto que cada um^&#42;1^ será decepado da região montanhosa de Esaú, por causa duma matança.

[NOTE]
====
. “Cada um.” Hebr.: ’ish.
====

[[v31-1-10]]

^<<v31-1-10,10>>^ Por causa da violência [feita] ao teu irmão Jacó cobrir-te-á a vergonha e terás de ser decepado por tempo indefinido.

[[v31-1-11]]

^<<v31-1-11,11>>^ No dia em que ficaste parado de lado, no dia em que estranhos levaram ao cativeiro a sua força militar e [quando] até estrangeiros entraram pelo seu portão e lançaram sortes sobre Jerusalém, tu também eras como um deles.

[[v31-1-12]]

^<<v31-1-12,12>>^ “E não devias ter contemplado o espetáculo no dia de teu irmão, no dia do seu infortúnio; e não te devias ter alegrado sobre os filhos de Judá no dia de seu perecimento; e não devias ter uma boca grande no dia da [sua] aflição.

[[v31-1-13]]

^<<v31-1-13,13>>^ Não devias ter entrado pelo portão do meu povo no dia do seu desastre. Tu, sim, tu não devias ter espreitado a sua calamidade no dia do seu desastre; e não devias ter estendido a mão sobre a sua riqueza^&#42;1^ no dia do seu desastre.

[NOTE]
====
. “Não devias ter estendido a mão sobre a sua riqueza”, mediante uma correção; M: “não devíeis [hebr. fem. pl.] ter avançado contra a sua riqueza”.
====

[[v31-1-14]]

^<<v31-1-14,14>>^ E não devias ter ficado de pé na bifurcação dos caminhos para decepar-lhe os fugitivos; e não devias ter entregue os seus sobreviventes no dia da aflição.

[[v31-1-15]]

^<<v31-1-15,15>>^ Pois está próximo o dia de Jeová contra todas as nações.^&#42;1^ Assim como fizeste, será feito a ti. Tua espécie de tratamento retornará sobre a tua própria cabeça.

[NOTE]
====
. Ou “está próximo o dia de Jeová sobre todas as nações”.
====

[[v31-1-16]]

^<<v31-1-16,16>>^ Pois assim como vós bebestes sobre o meu santo monte, estarão bebendo continuamente todas as nações. E certamente beberão, e engolirão, e ficarão como se nunca tivessem existido.

[[v31-1-17]]

^<<v31-1-17,17>>^ “E é no monte Sião que mostrarão estar os que escaparem, e ele terá de tornar-se algo sagrado; e a casa de Jacó terá de tomar posse das coisas a serem possuídas por eles.^&#42;1^

[NOTE]
====
. “Tomar posse dos que estão de posse deles”, mediante uma ligeira correção, para concordar com LXXSyVg.
====

[[v31-1-18]]

^<<v31-1-18,18>>^ E a casa de Jacó terá de tornar-se um fogo, e a casa de José, uma chama, e a casa de Esaú, como restolho; e terão de pô-los em chamas e consumi-los. E não se mostrará haver nenhum sobrevivente da casa de Esaú; porque o próprio Jeová [o] falou.

[[v31-1-19]]

^<<v31-1-19,19>>^ E terão de tomar posse do Negebe,^&#42;1^ sim, da região montanhosa de Esaú, e da Sefelá,^&#42;2^ sim, dos filisteus. E terão de tomar posse do campo de Efraim e do campo de Samaria; e Benjamim [terá de tomar posse de] Gileade.

[NOTE]
====
. Ou “do sul”, isto é, da parte sulina da Terra da Promessa.
. Ou “da terra baixa”.
====

[[v31-1-20]]

^<<v31-1-20,20>>^ E quanto aos exilados desta escarpa,^&#42;1^ pertencerá aos filhos de Israel o que os cananeus [possuíram] até Sarefá. E os exilados de Jerusalém, que estavam em Sefarade, tomarão posse das cidades do Negebe.

[NOTE]
====
. “Desta escarpa.” Hebr.: ha·hhel-haz·zéh.
====

[[v31-1-21]]

^<<v31-1-21,21>>^ “E certamente subirão salvadores^&#42;1^ ao^&#42;2^ monte Sião para julgar a região montanhosa de Esaú; e o reinado terá de tornar-se de Jeová.”

[NOTE]
====
. “Salvadores”, MTVg; LXX: “homens salvos”; Sy: “os remidos”.
. “Ao”, MTSyVg; LXX: “do”.
====

'''

xref:030-amos/030-amos-009.adoc#v30-9-0[&#60; Capítulo Anterior] | <<v31-1-0,Topo>> | xref:032-jonas/032-jonas-001.adoc#v32-1-0[Próximo Capítulo &#62;]