include::./index.adoc[]

[[v64-1-0]]
=== 3 João, 1
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v64-1-1]]

^<<v64-1-1,1>>^ O ancião,^&#42;1^ a Gaio, o amado, a quem amo verdadeiramente.^&#42;2^

[NOTE]
====
. “Ancião.” Gr.: pre·sbý·te·ros.
. Ou “eu amo na verdade”.
====

[[v64-1-2]]

^<<v64-1-2,2>>^ Amado, oro para que em todas as coisas estejas prosperando^&#42;1^ e tenhas boa saúde, assim como a tua alma está prosperando.

[NOTE]
====
. Lit.: “se torne bem o caminho [da pessoa]”.
====

[[v64-1-3]]

^<<v64-1-3,3>>^ Pois eu me alegrei muitíssimo^&#42;1^ quando os irmãos vieram^&#42;2^ e deram testemunho da verdade que reténs, assim como estás andando na verdade.

[NOTE]
====
. Lit.: “excessivamente”.
. “Vieram.” Gr.: er·kho·mé·non, referindo-se a uma vinda passada.
====

[[v64-1-4]]

^<<v64-1-4,4>>^ Não tenho nenhuma causa maior para gratidão do que estas coisas, de que eu esteja ouvindo que os meus filhos estão andando na verdade.

[[v64-1-5]]

^<<v64-1-5,5>>^ Amado, estás fazendo uma obra fiel naquilo que fazes para os irmãos, e ainda por cima estranhos,

[[v64-1-6]]

^<<v64-1-6,6>>^ os quais deram testemunho do teu amor perante a congregação. A estes, por favor,^&#42;1^ encaminha na sua jornada duma maneira digna de Deus.

[NOTE]
====
. Ou “farás bem em [encaminhar]”.
====

[[v64-1-7]]

^<<v64-1-7,7>>^ Porque foi a favor do nome [dele] que saíram, não tomando nada das pessoas das nações.

[[v64-1-8]]

^<<v64-1-8,8>>^ Nós, portanto, temos a obrigação de receber a tais de modo hospitaleiro, para que nos tornemos colaboradores na verdade.^&#42;1^

[NOTE]
====
. Ou “nos tornemos trabalhadores com a verdade”.
====

[[v64-1-9]]

^<<v64-1-9,9>>^ Escrevi algo à congregação, mas Diótrefes, que gosta de ocupar o primeiro lugar^&#42;1^ entre eles, não recebe nada de nós com respeito.

[NOTE]
====
. Lit.: “que gosta de ser (o) primeiro”.
====

[[v64-1-10]]

^<<v64-1-10,10>>^ É por isso que, se eu for [aí], farei lembrar as obras dele, que ele prossegue fazendo, parolando acerca de nós com palavras iníquas. Também, não contente^&#42;1^ com estas coisas, nem ele mesmo recebe os irmãos com respeito, e, os que querem recebê-los, ele procura^&#42;2^ impedir e lançar fora da congregação.

[NOTE]
====
. Lit.: “não satisfeito”.
. Ou “continua a; toma por prática”.
====

[[v64-1-11]]

^<<v64-1-11,11>>^ Amado, sê imitador, não daquilo que é mau, mas daquilo que é bom. Quem faz o bem origina-se de Deus. Quem faz o mal não tem visto a Deus.

[[v64-1-12]]

^<<v64-1-12,12>>^ Todos eles deram testemunho de Demétrio, e assim também a própria verdade. De fato, nós também damos testemunho, e tu sabes que o testemunho que damos é verdadeiro.

[[v64-1-13]]

^<<v64-1-13,13>>^ Eu tinha muitas coisas para te escrever, contudo, não quero estar escrevendo com tinta e pena.^&#42;1^

[NOTE]
====
. Lit.: “cana”.
====

[[v64-1-14]]

^<<v64-1-14,14>>^ Espero, porém, ver-te logo, e havemos de falar face a face.^&#42;1^
Paz seja contigo.
Os amigos mandam-te os seus cumprimentos. Dá os meus cumprimentos aos amigos, por nome.

[NOTE]
====
. Lit.: “boca a boca”.
====

'''

xref:063-2-joao/063-2-joao-001.adoc#v63-1-0[&#60; Capítulo Anterior] | <<v64-1-0,Topo>> | xref:065-judas/065-judas-001.adoc#v65-1-0[Próximo Capítulo &#62;]