include::./index.adoc[]

[[v26-28-0]]
=== Ezequiel, 28
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v26-28-1]]

^<<v26-28-1,1>>^ E continuou a vir a haver para mim a palavra de Jeová, dizendo:

[[v26-28-2]]

^<<v26-28-2,2>>^ “Filho do homem, dize ao líder de Tiro: ‘Assim disse o Soberano Senhor Jeová:
“‘“Visto que teu coração se ensoberbeceu e estás dizendo: ‘Sou deus.^&#42;1^ No assento de deus^&#42;2^ me assentei, no coração do alto-mar’, sendo que tu és homem terreno^&#42;3^ e não deus, e continuas a fazer teu coração como o coração de deus —

[NOTE]
====
. “Deus (divino).” Hebr.: ’el; gr.: the·ós; lat.: dé·us.
. “Deus.” Hebr.: ’elo·hím; lat.: dé·i.
. Ou “humano”. Hebr.: ’a·dhám; gr.: án·thro·pos; lat.: hó·mo.
====

[[v26-28-3]]

^<<v26-28-3,3>>^ eis que és mais sábio do que Daniel! Não há segredos que estejam à altura de ti.

[[v26-28-4]]

^<<v26-28-4,4>>^ Pela tua sabedoria e pelo teu discernimento produziste riqueza para ti mesmo, e continuas a receber ouro e prata nos teus depósitos.

[[v26-28-5]]

^<<v26-28-5,5>>^ Pela abundância da tua sabedoria, pelas tuas mercadorias, fizeste abundar a tua riqueza e teu coração começou a ensoberbecer-se por causa da tua riqueza.”’

[[v26-28-6]]

^<<v26-28-6,6>>^ “‘Portanto, assim disse o Soberano Senhor Jeová: “Visto que fizeste teu coração igual ao coração de deus,

[[v26-28-7]]

^<<v26-28-7,7>>^ por isso, eis que farei chegar sobre ti estranhos, os tiranos das nações, e eles hão de desembainhar as suas espadas contra a beleza da tua sabedoria e profanar a tua refulgência.

[[v26-28-8]]

^<<v26-28-8,8>>^ À cova te farão descer, e terás de ter a morte de alguém morto no coração do alto-mar.

[[v26-28-9]]

^<<v26-28-9,9>>^ Acaso dirás terminantemente: ‘Sou deus’, diante daquele que te mata, sendo que és mero homem terreno e não deus na mão dos que te profanam?”’

[[v26-28-10]]

^<<v26-28-10,10>>^ “‘Terás as mortes dos incircuncisos às mãos de estranhos, pois eu é que falei’, é a pronunciação do Soberano Senhor Jeová.”

[[v26-28-11]]

^<<v26-28-11,11>>^ E continuou a vir a haver para mim a palavra de Jeová, dizendo:

[[v26-28-12]]

^<<v26-28-12,12>>^ “Filho do homem, levanta uma endecha concernente ao rei de Tiro, e tens de dizer-lhe: ‘Assim disse o Soberano Senhor Jeová:
“‘“Tu estás selando o modelo, cheio de sabedoria e perfeito em beleza.

[[v26-28-13]]

^<<v26-28-13,13>>^ Vieste a estar no Éden, jardim^&#42;1^ de Deus.^&#42;2^ Toda pedra preciosa era a tua cobertura: rubi, topázio e jaspe; crisólito,^&#42;3^ ônix e jade; safira, turquesa e esmeralda; e era de ouro o artesanato dos teus engastes e dos teus encaixes em ti. Foram aprontados no dia em que foste criado.

[NOTE]
====
. “Jardim.” Hebr.: gan; gr.: pa·ra·deí·sou; sir.: par·dai·seh; lat.: pa·ra·dí·si.
. “Deus.” Hebr.: ’Elo·hím; gr.: The·oú; lat.: Dé·i.
. “Crisólito”, Vg; hebr.: tar·shísh.
====

[[v26-28-14]]

^<<v26-28-14,14>>^ Tu és o^&#42;1^ querubim ungido^&#42;2^ que cobre, e eu te constituí.^&#42;3^ Vieste a estar no monte santo de Deus.^&#42;4^ No meio de pedras afogueadas^&#42;5^ andavas.

[NOTE]
====
. “Tu és o”, MTVg; mediante sinais vocálicos diferentes: “Com o”, em harmonia com LXXSy e o árabe.
. Lit.: “querubim duma unção [possivelmente: expansão]”. Hebr.: kerúv mim·sháhh.
. Lit.: “dei”. “Tu és o rei ungido no reino, e eu te dei grandeza”, T; LXX: “Com o querubim eu te constituí”; Sy: “Vieste a estar com o querubim ungido que cobre, e eu te constituí”; Vg: “Tu és o querubim estendido e protetor, e eu te constituí.”
. “Deus.” Hebr.: ’Elo·hím; lat.: Dé·i.
. Lit.: “pedras de fogo”.
====

[[v26-28-15]]

^<<v26-28-15,15>>^ Eras sem defeito nos teus caminhos, desde o dia em que foste criado, até que se achou injustiça em ti.

[[v26-28-16]]

^<<v26-28-16,16>>^ “‘“Por causa da abundância das tuas mercadorias encheu-se o teu meio^&#42;1^ de violência, e começaste a pecar. E eu te porei para fora do monte de Deus,^&#42;2^ por seres profano, e te destruirei, ó querubim que cobre,^&#42;3^ do meio das pedras afogueadas.^&#42;4^

[NOTE]
====
. “Encheu-se o teu meio”, M; Sy: “encheste o teu próprio meio”; T: “teus depósitos foram enchidos”; LXX: “encheste os teus depósitos”; Vg: “tuas entranhas foram enchidas”.
. “Deus.” Hebr.: ’Elo·hím; gr.: The·oú; lat.: Dé·i.
. “Te destruirei, ó querubim que cobre”, MSy; Vg: “Eu te destruí, ó querubim protetor”; LXX: “o querubim te levou embora”.
. Lit.: “pedras de fogo”.
====

[[v26-28-17]]

^<<v26-28-17,17>>^ “‘“Teu coração se ensoberbeceu por causa da tua beleza. Arruinaste a tua sabedoria por causa da tua refulgência. Vou lançar-te para a terra. Vou pôr-te diante de reis, [para que] olhem para ti.

[[v26-28-18]]

^<<v26-28-18,18>>^ “‘“Devido à abundância dos teus erros, por causa da injustiça das tuas mercadorias, profanaste^&#42;1^ os teus santuários. E farei sair um fogo do teu meio. É o que terá de devorar-te. E farei de ti cinzas sobre a terra diante dos olhos de todos os que te vêem.

[NOTE]
====
. “Profanaste”, MSyVg; LXXB: “profanei”.
====

[[v26-28-19]]

^<<v26-28-19,19>>^ Quanto a todos os que te conhecem entre os povos, hão de olhar para ti espantados. Terrores repentinos é o que te terás de tornar, e não serás mais por tempo indefinido.”’”

[[v26-28-20]]

^<<v26-28-20,20>>^ E continuou a vir a haver para mim a palavra de Jeová, dizendo:

[[v26-28-21]]

^<<v26-28-21,21>>^ “Filho do homem, fixa a tua face em direção a Sídon e profetiza contra ela.

[[v26-28-22]]

^<<v26-28-22,22>>^ E tens de dizer: ‘Assim disse o Soberano Senhor Jeová: “Eis que sou contra ti, ó Sídon, e eu certamente serei glorificado no meio de ti; e as pessoas terão de saber que eu sou Jeová, quando eu executar atos de julgamento nela e eu realmente for santificado nela.

[[v26-28-23]]

^<<v26-28-23,23>>^ E vou enviar a peste para dentro dela e sangue para dentro das suas ruas. E o que for morto terá de cair no seu meio pela espada contra ela, por todos os lados; e as pessoas terão de saber que eu sou Jeová.

[[v26-28-24]]

^<<v26-28-24,24>>^ E não mais se mostrará haver para a casa de Israel um ferrão maligno ou um espinho doloroso dentre todos os que estão em volta deles, todos os que os menosprezam; e as pessoas terão de saber que eu sou o Soberano Senhor Jeová.”’

[[v26-28-25]]

^<<v26-28-25,25>>^ “‘Assim disse o Soberano Senhor Jeová: “Quando eu reunir a casa de Israel dentre os povos entre os quais foram espalhados, vou também ser santificado entre eles aos olhos das nações. E certamente morarão sobre o seu solo que dei ao meu servo, a Jacó.

[[v26-28-26]]

^<<v26-28-26,26>>^ E realmente morarão sobre ele em segurança, e construirão casas e plantarão vinhedos, e terão de morar em segurança quando eu executar atos de julgamento em todos os que os menosprezam ao redor deles; e terão de saber que eu sou Jeová, seu Deus.”’”^&#42;1^

[NOTE]
====
. Ou “eu, Jeová, sou seu Deus”. Hebr.: ’aní Yehwáh ’Elo·heh·hém.
====

'''

xref:026-ezequiel/026-ezequiel-027.adoc#v26-27-0[&#60; Capítulo Anterior] | <<v26-28-0,Topo>> | xref:026-ezequiel/026-ezequiel-029.adoc#v26-29-0[Próximo Capítulo &#62;]