include::./index.adoc[]

[[v26-44-0]]
=== Ezequiel, 44
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v26-44-1]]

^<<v26-44-1,1>>^ E ele passou a levar-me de volta pelo caminho do portão do santuário,^&#42;1^ o externo que dá para o leste, e estava fechado.

[NOTE]
====
. “Do santuário.” Hebr.: ham·miq·dásh; gr.: ha·gí·on; lat.: sanc·tu·á·ri·i.
====

[[v26-44-2]]

^<<v26-44-2,2>>^ Jeová disse-me então: “Quanto a este portão, continuará fechado. Não será aberto, e nenhum mero homem^&#42;1^ entrará por ele; pois o próprio Jeová, o Deus^&#42;2^ de Israel, entrou por ele, e ele tem de continuar fechado.

[NOTE]
====
. “E . . . homem.” Hebr.: we’ísh.
. “O Deus de.” Hebr.: ’Elo·héh.
====

[[v26-44-3]]

^<<v26-44-3,3>>^ Todavia, o maioral — ele mesmo, como maioral, estará sentado nele para comer pão perante Jeová. Entrará pelo caminho do pórtico do portão e sairá por este caminho.”

[[v26-44-4]]

^<<v26-44-4,4>>^ E ele me levou então pelo caminho do portão setentrional até diante da Casa para que eu visse, e eis que a glória de Jeová enchera a casa de Jeová. E eu fui lançar-me com a face [por terra].

[[v26-44-5]]

^<<v26-44-5,5>>^ Jeová disse-me então: “Filho do homem, fixa teu coração e vê com os teus olhos, e ouve com os teus ouvidos tudo o que eu falar contigo com respeito a todos os estatutos da casa de Jeová e com respeito a todas as suas leis, e tens de fixar teu coração na entrada da Casa com todas as saídas do santuário.

[[v26-44-6]]

^<<v26-44-6,6>>^ E tens de dizer à Rebeldia,^&#42;1^ à casa de Israel: ‘Assim disse o Soberano Senhor Jeová: “Já chega de vós, por causa de todas as vossas coisas detestáveis, ó casa de Israel,

[NOTE]
====
. “Rebeldia”, M; T: “ao povo rebelde”; LXX: “à casa rebelde”.
====

[[v26-44-7]]

^<<v26-44-7,7>>^ ao introduzirdes os estrangeiros^&#42;1^ de coração incircunciso e de carne incircuncisa, para que venham a estar no meu santuário a fim de profaná-lo, sim, a minha casa; ao apresentardes meu pão, gordura e sangue, ao passo que violam o meu pacto por causa de todas as vossas coisas detestáveis.

[NOTE]
====
. Lit.: “filhos dum (país) estrangeiro”.
====

[[v26-44-8]]

^<<v26-44-8,8>>^ Tampouco cuidastes da obrigação para com as minhas coisas sagradas, nem fostes constituir para vós [outros] em guardiães da obrigação para comigo no meu santuário.”’

[[v26-44-9]]

^<<v26-44-9,9>>^ “‘Assim disse o Soberano Senhor Jeová: “Nenhum estrangeiro,^&#42;1^ de coração incircunciso e de carne incircuncisa, pode entrar no meu santuário, quer dizer, nenhum estrangeiro que estiver no meio dos filhos de Israel.”’

[NOTE]
====
. Veja v. 7 n.
====

[[v26-44-10]]

^<<v26-44-10,10>>^ “‘Mas, no que se refere aos levitas que se afastaram para longe de mim quando Israel, que se transviou de mim, andou perdido atrás dos seus ídolos sórdidos, também terão de levar seu erro.

[[v26-44-11]]

^<<v26-44-11,11>>^ E terão de tornar-se ministros^&#42;1^ no meu santuário, em postos de supervisão sobre os portões da Casa, e ministros na Casa. Eles mesmos abaterão o holocausto e o sacrifício para o povo, e eles mesmos estarão de pé perante eles para ministrar-lhes.

[NOTE]
====
. Ou “ajudantes”. Hebr.: mesha·rethím.
====

[[v26-44-12]]

^<<v26-44-12,12>>^ Visto que lhes ministravam perante os seus ídolos sórdidos e se tornaram para a casa de Israel uma pedra de tropeço para [cair no] erro, por isso levantei a minha mão contra eles’, é a pronunciação do Soberano Senhor Jeová, ‘e terão de levar seu erro.

[[v26-44-13]]

^<<v26-44-13,13>>^ E não se aproximarão de mim para atuarem para mim como sacerdotes ou para se aproximarem de quaisquer das minhas coisas sagradas, das coisas santíssimas, e terão de levar sua humilhação e as coisas detestáveis que fizeram.

[[v26-44-14]]

^<<v26-44-14,14>>^ E eu certamente farei deles guardiães da obrigação para com a Casa, com respeito a todo o seu serviço e com respeito a tudo o que se deve fazer nela.’

[[v26-44-15]]

^<<v26-44-15,15>>^ “‘E no que se refere aos sacerdotes levíticos, os filhos de Zadoque, que cuidavam da obrigação para com o meu santuário quando os filhos de Israel se transviaram de mim, eles é que se chegarão a mim para ministrar-me e terão de ficar de pé diante de mim para apresentar-me a gordura e o sangue’, é a pronunciação do Soberano Senhor Jeová.

[[v26-44-16]]

^<<v26-44-16,16>>^ ‘Eles é que serão os que entrarão no meu santuário e eles é que se chegarão à minha mesa para ministrar-me, e terão de cuidar da obrigação para comigo.

[[v26-44-17]]

^<<v26-44-17,17>>^ “‘E terá de acontecer que, quando entrarem nos portões do pátio interno, deverão usar vestes de linho e não deve haver sobre eles nenhuma lã ao ministrarem nos portões do pátio interno e por dentro.

[[v26-44-18]]

^<<v26-44-18,18>>^ Deve vir a haver na sua cabeça coberturas de linho e deve vir a haver calções de linho sobre os seus quadris. Não devem cingir-se de [nada que cause] suor.

[[v26-44-19]]

^<<v26-44-19,19>>^ E quando saírem ao pátio externo, [sim,] ao pátio externo, ao povo, devem despir-se das suas vestes em que ministraram e terão de depositá-las nos refeitórios sagrados e pôr outras vestes, para que não santifiquem o povo com as suas vestes.

[[v26-44-20]]

^<<v26-44-20,20>>^ E não devem raspar a sua cabeça e não devem usar solto o cabelo da cabeça. Decididamente devem cortar [o cabelo das] suas cabeças.

[[v26-44-21]]

^<<v26-44-21,21>>^ E nenhum dos sacerdotes deve beber vinho ao entrar no pátio interno.

[[v26-44-22]]

^<<v26-44-22,22>>^ E eles não devem tomar para si por esposa nenhuma viúva ou divorciada, senão virgens da descendência da casa de Israel ou a viúva que veio a ficar viúva de sacerdote podem tomar.’

[[v26-44-23]]

^<<v26-44-23,23>>^ “‘E devem instruir meu povo na diferença entre a coisa sagrada e a coisa profana; e devem fazê-los saber a diferença entre o que é impuro e o que é puro.

[[v26-44-24]]

^<<v26-44-24,24>>^ E numa causa jurídica são eles os que devem estar de pé para julgar; também terão de julgá-la com as minhas decisões judiciais. E devem guardar as minhas leis e os meus estatutos relativos a todas as minhas épocas festivas, e devem santificar os meus sábados.

[[v26-44-25]]

^<<v26-44-25,25>>^ E ele não deve chegar a nenhum morto^&#42;1^ humano^&#42;2^ de modo a se tornar impuro, mas podem tornar-se impuros pelo pai, ou pela mãe, ou pelo filho, ou pela filha, [ou] pelo irmão, ou pela irmã que não viera a ser de um marido.^&#42;3^

[NOTE]
====
. “[Nenhum] morto.” Hebr.: meth; gr.: psy·khén, “alma”.
. Ou “homem terreno”. Hebr.: ’a·dhám; gr.: an·thró·pou; lat.: hó·mi·nem.
. Lit.: “a um homem”. Hebr.: le’ísh.
====

[[v26-44-26]]

^<<v26-44-26,26>>^ E depois da sua purificação devem enumerar-lhe sete dias.

[[v26-44-27]]

^<<v26-44-27,27>>^ E no dia em que entrar no lugar santo,^&#42;1^ no pátio interno, para ministrar no lugar santo, deve apresentar a sua oferta pelo pecado’, é a pronunciação do Soberano Senhor Jeová.

[NOTE]
====
. “No lugar santo.” Hebr.: haq·qó·dhesh; lat.: sanc·tu·á·ri·um.
====

[[v26-44-28]]

^<<v26-44-28,28>>^ “‘E deve tornar-se deles como herança:^&#42;1^ Eu sou a sua herança. E não deveis dar-lhes nenhuma propriedade em Israel: Eu sou a sua propriedade.

[NOTE]
====
. “Não haverá, porém, herança para eles”, Vgc.
====

[[v26-44-29]]

^<<v26-44-29,29>>^ A oferta de cereais, e a oferta pelo pecado, e a oferta pela culpa — eles é que as comerão. E toda coisa devotada em Israel — tornar-se-á deles.

[[v26-44-30]]

^<<v26-44-30,30>>^ E as primeiras de todas as primícias maduras de tudo e toda contribuição de tudo dentre todas as vossas contribuições — aos sacerdotes é que virá a pertencer; e as primícias de vossas massas de farinha deveis dar ao sacerdote, para que venha a descansar uma bênção sobre a tua casa.^&#42;1^

[NOTE]
====
. “Sobre a tua casa”, MTVgc; LXXSy: “sobre as vossas casas”.
====

[[v26-44-31]]

^<<v26-44-31,31>>^ Os sacerdotes não devem comer nenhum corpo [já] morto e nenhuma criatura dilacerada das criaturas voadoras ou dos animais.’

'''

xref:026-ezequiel/026-ezequiel-043.adoc#v26-43-0[&#60; Capítulo Anterior] | <<v26-44-0,Topo>> | xref:026-ezequiel/026-ezequiel-045.adoc#v26-45-0[Próximo Capítulo &#62;]