include::./index.adoc[]

[[v26-7-0]]
=== Ezequiel, 7
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v26-7-1]]

^<<v26-7-1,1>>^ E continuou a vir a haver para mim a palavra de Jeová, dizendo:

[[v26-7-2]]

^<<v26-7-2,2>>^ “E no que se refere a ti, ó filho do homem, assim disse o Soberano Senhor Jeová ao solo de Israel: ‘Um fim, o fim chegou para as quatro extremidades^&#42;1^ do país.^&#42;2^

[NOTE]
====
. Lit.: “asas”.
. Ou “da terra”. Hebr.: ha·’á·rets.
====

[[v26-7-3]]

^<<v26-7-3,3>>^ Agora te^&#42;1^ sobreveio o fim, e eu terei de enviar a minha ira contra ti, e vou julgar-te segundo os teus caminhos e trazer sobre ti todas as tuas coisas detestáveis.

[NOTE]
====
. “Te”, hebr. fem. sing., referindo-se ao “solo [hebr. fem.] de Israel”.
====

[[v26-7-4]]

^<<v26-7-4,4>>^ E meu olho não terá dó de ti, nem terei compaixão, pois trarei sobre ti os teus próprios caminhos, e no teu meio virão a estar as tuas próprias coisas detestáveis; e tereis de saber que eu sou Jeová.’

[[v26-7-5]]

^<<v26-7-5,5>>^ “Assim disse o Soberano Senhor Jeová: ‘Eis que vem uma calamidade, uma calamidade única!

[[v26-7-6]]

^<<v26-7-6,6>>^ Terá de chegar o próprio fim. Terá de chegar o fim; terá de acordar para ti.^&#42;1^ Eis que está chegando!

[NOTE]
====
. Veja v. 3 n.
====

[[v26-7-7]]

^<<v26-7-7,7>>^ A grinalda^&#42;1^ terá de chegar a ti,^&#42;2^ ó habitante do país,^&#42;3^ terá de chegar o tempo, o dia está próximo. Há confusão e não a exclamação dos montes.

[NOTE]
====
. Ou: “A reviravolta [da situação].” O significado e a aplicação da palavra hebr. são incertos.
. “Ti”, hebr. masc. sing., referindo-se ao “habitante”.
. Ou “da terra”. Hebr.: ha·’á·rets.
====

[[v26-7-8]]

^<<v26-7-8,8>>^ “‘Agora, brevemente derramarei sobre ti o meu furor e vou levar a cabo a minha ira contra ti, e vou julgar-te segundo os teus caminhos e trazer sobre ti todas as tuas coisas detestáveis.

[[v26-7-9]]

^<<v26-7-9,9>>^ Nem o meu olho terá dó, nem terei compaixão. Segundo os teus caminhos trarei [isso] sobre ti mesmo e as tuas próprias coisas detestáveis virão a estar bem no teu meio; e vós tereis de saber que eu sou Jeová quem dá o golpe.^&#42;1^

[NOTE]
====
. Ou “eu, Jeová, sou quem dá o golpe”.
====

[[v26-7-10]]

^<<v26-7-10,10>>^ “‘Eis o dia! Eis que está chegando! Saiu a grinalda. Brotou o bastão. Floresceu a presunção.

[[v26-7-11]]

^<<v26-7-11,11>>^ A própria violência se levantou como bastão de iniqüidade. Não procede deles, nem procede da sua opulência; e não procede deles próprios, nem há neles qualquer eminência.^&#42;1^

[NOTE]
====
. Ou “lamentação; gemido”. O significado da palavra hebr. é incerto.
====

[[v26-7-12]]

^<<v26-7-12,12>>^ Tem de vir o tempo, tem de chegar o dia. Quanto ao comprador, não se alegre ele; e no que toca ao vendedor, não se ponha de luto, porque há animosidade ardente contra toda a sua massa de gente.

[[v26-7-13]]

^<<v26-7-13,13>>^ Porque o próprio vendedor não voltará àquilo que se vendeu, enquanto a vida deles ainda estiver entre os viventes; porque a visão é para toda a sua massa de gente. Ninguém voltará, e não se apossarão cada um^&#42;1^ da sua própria vida, pelo seu próprio erro.

[NOTE]
====
. “E . . . cada um.” Hebr.: we’ísh.
====

[[v26-7-14]]

^<<v26-7-14,14>>^ “‘Tocaram a trombeta e houve preparação por parte de todos, mas não há quem vá à batalha, porque a minha animosidade ardente é contra toda a sua massa de gente.

[[v26-7-15]]

^<<v26-7-15,15>>^ Lá fora está a espada e por dentro há peste e fome. Quem estiver no campo, morrerá à espada, e quem estiver na cidade, a este devorarão a própria fome e peste.

[[v26-7-16]]

^<<v26-7-16,16>>^ E seus fugitivos certamente conseguirão escapar e tornar-se-ão nos montes quais pombas dos vales, todos gemendo, cada um no seu próprio erro.

[[v26-7-17]]

^<<v26-7-17,17>>^ Quanto a todas as mãos, continuam a abaixar-se; e quanto a todos os joelhos, continuam a pingar água.^&#42;1^

[NOTE]
====
. Isto é, pela urinação por causa da pressão decorrente do medo.
====

[[v26-7-18]]

^<<v26-7-18,18>>^ E cingiram-se com serapilheira e cobriu-os o estremecimento; e em todas as faces há vergonha e em todas as suas cabeças há calvície.

[[v26-7-19]]

^<<v26-7-19,19>>^ “‘A própria prata deles lançarão nas ruas e o próprio ouro deles tornar-se-á uma coisa abominável. Nem a sua prata nem o seu ouro poderá livrá-los no dia da fúria de Jeová. Não fartarão as suas almas e não encherão os seus intestinos, porque isso se tornou uma pedra de tropeço, causando seu erro.

[[v26-7-20]]

^<<v26-7-20,20>>^ E o ornato do enfeite que a pessoa tem — coloca-se como razão para orgulho; e eles fizeram com isso^&#42;1^ suas imagens detestáveis, suas coisas repugnantes. Por isso é que vou fazer dele uma coisa abominável para eles.

[NOTE]
====
. “Isso”, hebr. masc. sing., possivelmente referindo-se ao metal precioso.
====

[[v26-7-21]]

^<<v26-7-21,21>>^ E vou entregá-lo na mão dos estranhos como saque e aos iníquos da terra como despojo, e eles certamente o profanarão.

[[v26-7-22]]

^<<v26-7-22,22>>^ “‘E terei de desviar deles a minha face e eles realmente profanarão meu lugar escondido,^&#42;1^ e por certo entrarão nela^&#42;2^ salteadores e a profanarão.

[NOTE]
====
. Ou “minhas coisas ocultas”.
. “Nela”, hebr. fem. sing., provavelmente referindo-se à cidade santa.
====

[[v26-7-23]]

^<<v26-7-23,23>>^ “‘Faze a corrente,^&#42;1^ porque a própria terra^&#42;2^ ficou cheia de julgamentos sangrentos^&#42;3^ e a própria cidade ficou cheia de violência.

[NOTE]
====
. “Matança”, mediante uma ligeira correção.
. “A . . . terra.” Hebr.: ha·’á·rets.
. Lit.: “julgamento de sangues”.
====

[[v26-7-24]]

^<<v26-7-24,24>>^ E vou fazer entrar os piores das nações e eles certamente se apossarão das suas casas, e vou fazer cessar o orgulho dos fortes, e seus santuários terão de ser profanados.

[[v26-7-25]]

^<<v26-7-25,25>>^ Virá angústia, e eles hão de procurar a paz, mas não haverá nenhuma.

[[v26-7-26]]

^<<v26-7-26,26>>^ Virá adversidade sobre adversidade e virá a haver notícia sobre notícia, e as pessoas procurarão realmente uma visão do profeta, e do sacerdote perecerá a própria lei e dos homens idosos o conselho.

[[v26-7-27]]

^<<v26-7-27,27>>^ O próprio rei pôr-se-á a prantear; até mesmo o maioral se vestirá de desolação, e as próprias mãos do povo da terra^&#42;1^ ficarão perturbadas. Agirei para com eles segundo o seu caminho e os julgarei com os seus julgamentos; e terão de saber que eu sou Jeová.’”

[NOTE]
====
. “Do povo da terra.” Hebr.: ‛am-ha·’á·rets. Posteriormente usado em sentido de desprezo. Veja Jo 7:47-49.
====

'''

xref:026-ezequiel/026-ezequiel-006.adoc#v26-6-0[&#60; Capítulo Anterior] | <<v26-7-0,Topo>> | xref:026-ezequiel/026-ezequiel-008.adoc#v26-8-0[Próximo Capítulo &#62;]