include::./index.adoc[]

[[v26-4-0]]
=== Ezequiel, 4
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v26-4-1]]

^<<v26-4-1,1>>^ “E tu, ó filho do homem, toma para ti um tijolo, e tens de pô-lo diante de ti e gravar sobre ele uma cidade, sim, Jerusalém.

[[v26-4-2]]

^<<v26-4-2,2>>^ E tens de sitiá-la e construir contra ela um muro de sítio, e erguer^&#42;1^ contra ela um aterro de sítio, e armar acampamentos contra ela, e colocar contra ela aríetes ao redor.

[NOTE]
====
. Lit.: “derramar”.
====

[[v26-4-3]]

^<<v26-4-3,3>>^ E no que se refere a ti, toma para ti uma assadeira de ferro e tens de pô-la como muro de ferro entre ti e a cidade, e tens de firmar tua face contra ela, e ela tem de ficar sitiada, e tu tens de sitiá-la. É um sinal para a casa de Israel.

[[v26-4-4]]

^<<v26-4-4,4>>^ “E no que se refere a ti, deita-te sobre o teu lado esquerdo, e tens de deitar sobre ele o erro da casa de Israel. Pelo número dos dias que ficares deitado sobre ele levarás o erro deles.

[[v26-4-5]]

^<<v26-4-5,5>>^ E eu é que tenho de dar-te os anos de seu erro no número de trezentos e noventa dias, e tens de levar o erro da casa de Israel.

[[v26-4-6]]

^<<v26-4-6,6>>^ E tens de completá-los.
“E tens de deitar-te sobre o teu lado direito, no segundo caso, e tens de levar o erro da casa de Judá por quarenta dias. Um dia por um ano, um dia por um ano é o que te dei.

[[v26-4-7]]

^<<v26-4-7,7>>^ E firmarás a tua face para o sítio de Jerusalém, com o teu braço desnudo, e tens de profetizar contra ela.

[[v26-4-8]]

^<<v26-4-8,8>>^ “E eis que vou pôr sobre ti cordas para que não te vires de um lado para outro, até que tenhas completado os dias do teu sítio.

[[v26-4-9]]

^<<v26-4-9,9>>^ “E no que se refere a ti, toma para ti trigo, e cevada, e favas, e lentilhas, e painço, e espelta, e tens de pô-los numa só vasilha e fazer deles pão^&#42;1^ para ti, pelo número dos dias que estiveres deitado sobre o teu lado; por trezentos e noventa dias o comerás.

[NOTE]
====
. Ou “alimento”.
====

[[v26-4-10]]

^<<v26-4-10,10>>^ E teu alimento que comerás será por peso — vinte siclos por dia. De tempo em tempo o comerás.

[[v26-4-11]]

^<<v26-4-11,11>>^ “E beberás água apenas por medida, a sexta parte de um him.^&#42;1^ De tempo em tempo beberás.

[NOTE]
====
. Um him equivalia a 3,67 l.
====

[[v26-4-12]]

^<<v26-4-12,12>>^ “E tu o comerás como bolo redondo de cevada; e a este cozerás perante os olhos deles sobre fezes de excremento humano.”^&#42;1^

[NOTE]
====
. Lit.: “de homem terreno”. Hebr.: ha·’a·dhám.
====

[[v26-4-13]]

^<<v26-4-13,13>>^ E Jeová prosseguiu, dizendo: “Exatamente assim é que os filhos de Israel comerão seu pão de modo impuro entre as nações às quais os dispersarei.”

[[v26-4-14]]

^<<v26-4-14,14>>^ E eu passei a dizer: “Ai! Soberano Senhor Jeová! Eis que a minha alma não é aviltada; nem comi qualquer corpo [já] morto, nem qualquer animal dilacerado, desde a minha mocidade e até agora, e não entrou carne imunda na minha boca.”

[[v26-4-15]]

^<<v26-4-15,15>>^ Por conseguinte, ele me disse: “Vê, eu te dei estrume de gado em vez de fezes humanas, e tens de fazer o teu pão sobre ele.”

[[v26-4-16]]

^<<v26-4-16,16>>^ E continuou a dizer-me: “Filho do homem, eis que quebro os varais nos quais se penduram os pães de forma anular,^&#42;1^ em Jerusalém, e eles terão de comer pão por peso e em ansiedade, e será por medida e em horror que beberão a própria água,

[NOTE]
====
. Lit.: “o varal de pão”.
====

[[v26-4-17]]

^<<v26-4-17,17>>^ com o objetivo de que careçam de pão e de água e olhem espantados um para o outro e apodreçam no seu erro.

'''

xref:026-ezequiel/026-ezequiel-003.adoc#v26-3-0[&#60; Capítulo Anterior] | <<v26-4-0,Topo>> | xref:026-ezequiel/026-ezequiel-005.adoc#v26-5-0[Próximo Capítulo &#62;]