include::./index.adoc[]

[[v26-21-0]]
=== Ezequiel, 21
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v26-21-1]]

^<<v26-21-1,1>>^ ^&#42;1^ E continuou a vir a haver para mim a palavra de Jeová, dizendo:

[NOTE]
====
. TSyVg começam aqui o capítulo 21.
====

[[v26-21-2]]

^<<v26-21-2,2>>^ “Filho do homem, fixa a tua face na direção de Jerusalém e goteja [palavras] na direção dos lugares santos, e profetiza contra o solo de Israel.

[[v26-21-3]]

^<<v26-21-3,3>>^ E terás de dizer ao solo de Israel: ‘Assim disse Jeová: “Eis que sou contra ti, e vou fazer a minha espada sair de sua bainha e decepar de ti o justo e o iníquo.

[[v26-21-4]]

^<<v26-21-4,4>>^ Para que eu realmente decepe de ti o justo e o iníquo, minha espada sairá da sua bainha contra toda a carne, de sul a norte.

[[v26-21-5]]

^<<v26-21-5,5>>^ E todos os carnais terão de saber que eu mesmo, Jeová, fiz sair a minha espada de sua bainha. Não mais retornará.”’

[[v26-21-6]]

^<<v26-21-6,6>>^ “E quanto a ti, ó filho do homem, suspira com quadris vacilantes.^&#42;1^ Até mesmo com amargura deves suspirar diante dos seus olhos.

[NOTE]
====
. Lit.: “com o quebrantamento dos quadris”.
====

[[v26-21-7]]

^<<v26-21-7,7>>^ E terá de acontecer que, caso te disserem: ‘Por que estás suspirando?’ terás de dizer: ‘Por causa duma notícia.’ Pois ela certamente virá, e todo coração terá de derreter-se, e todas as mãos terão de abaixar-se, e todo espírito terá de ficar desanimado, e todos os joelhos é que pingarão água.^&#42;1^ ‘Eis que certamente virá e se fará que aconteça’, é a pronunciação do Soberano Senhor Jeová.”

[NOTE]
====
. Isto é, pela urinação por causa da pressão decorrente do medo.
====

[[v26-21-8]]

^<<v26-21-8,8>>^ E continuou a vir a haver para mim a palavra de Jeová, dizendo:

[[v26-21-9]]

^<<v26-21-9,9>>^ “Filho do homem, profetiza, e tens de dizer: ‘Assim disse Jeová:^&#42;1^ “Dize: ‘Uma espada, uma espada! Ela foi afiada e está também polida.

[NOTE]
====
. Uma das 134 mudanças de YHWH para ’Adho·naí feitas pelos escribas. Veja Ap. 1B.
====

[[v26-21-10]]

^<<v26-21-10,10>>^ Foi afiada com o objetivo de organizar um abate; foi polida para que lampejasse.’”’”^&#42;1^
“Ou exultaremos?”
“‘Acaso rejeita o cetro de meu próprio filho, assim [como faz] com toda árvore?

[NOTE]
====
. Lit.: “tivesse lampejo”. Hebr.: bá·roq.
====

[[v26-21-11]]

^<<v26-21-11,11>>^ “‘E ela foi dada para ser polida, a fim de que fosse brandida pela mão. Ela — uma espada foi afiada, e ela — foi polida, para ser entregue na mão dum matador.

[[v26-21-12]]

^<<v26-21-12,12>>^ “‘Clama e uiva, ó filho do homem, porque ela mesma veio a ser contra o meu povo; ela é contra todos os maiorais de Israel. Os próprios que foram atirados à espada vieram a estar com o meu povo. Portanto, bate na coxa.

[[v26-21-13]]

^<<v26-21-13,13>>^ Pois, fez-se um extermínio, e que [tem,] se também rejeitar o cetro? Este^&#42;1^ não continuará a existir’, é a pronunciação do Soberano Senhor Jeová.

[NOTE]
====
. “Este”, hebr. masc., referindo-se ao “cetro”, hebr. masc.; não se refere à “espada”, hebr. fem.
====

[[v26-21-14]]

^<<v26-21-14,14>>^ “E tu, ó filho do homem — profetiza, e bate palma contra palma, e deves repetir três vezes: ‘Uma espada!’ Ela é a espada dos que foram mortos. É a espada de alguém grande que foi morto, a qual os está circundando.

[[v26-21-15]]

^<<v26-21-15,15>>^ Para que o coração se derreta e [para que] sejam multiplicados os derrubados em todos os seus portões, vou fazer uma matança com a espada. Ai! ela é feita para lampejar,^&#42;1^ polida para o abate!

[NOTE]
====
. Veja v. 10 n.
====

[[v26-21-16]]

^<<v26-21-16,16>>^ Mostra-te afiada;^&#42;1^ vai para a direita! Fixa tua posição; vai para a esquerda! Para onde quer que estiver dirigida a tua face!

[NOTE]
====
. “Mostra-te afiada”, hebr. fem., dirigido à “espada”.
====

[[v26-21-17]]

^<<v26-21-17,17>>^ E eu mesmo também baterei uma palma contra a minha outra palma da mão, e vou fazer descansar o meu furor. Eu, Jeová, é que falei.”

[[v26-21-18]]

^<<v26-21-18,18>>^ E continuou a vir a haver para mim a palavra de Jeová, dizendo:

[[v26-21-19]]

^<<v26-21-19,19>>^ “E quanto a ti, ó filho do homem, estabelece para ti dois caminhos para a entrada da espada do rei de Babilônia.^&#42;1^ Ambos devem proceder do mesmo país, e deve-se recortar uma mão [indicadora]; deve ser recortada^&#42;2^ à cabeceira do caminho para a cidade.

[NOTE]
====
. “Babilônia”, LXXVg; MTSy: “Babel”.
. “Deve ser recortada.” No hebr., isto é um verbo no infinitivo absoluto, indefinido quanto ao tempo e impessoal.
====

[[v26-21-20]]

^<<v26-21-20,20>>^ Deves estabelecer um caminho para [a] espada entrar contra Rabá dos filhos de Amom e [o outro] contra Judá, contra a fortificada Jerusalém.

[[v26-21-21]]

^<<v26-21-21,21>>^ Porque o rei de Babilônia parou na encruzilhada,^&#42;1^ na cabeceira dos dois caminhos, para recorrer à adivinhação. Sacudiu as flechas. Indagou por meio dos terafins;^&#42;2^ examinou o fígado.

[NOTE]
====
. Lit.: “mãe do caminho”.
. “Terafins”, M; LXX: “imagens esculpidas”; Vg: “ídolos”.
====

[[v26-21-22]]

^<<v26-21-22,22>>^ Na sua direita mostrou-se haver a adivinhação referente à Jerusalém, para dispor os aríetes, para abrir a boca para a chacina,^&#42;1^ para elevar o som dum sinal de alarme, para dispor os aríetes contra os portões, para levantar um aterro de sítio, para construir um muro de sítio.

[NOTE]
====
. Ou “o grito de guerra”, mediante a transposição de letras.
====

[[v26-21-23]]

^<<v26-21-23,23>>^ E isso se tornou para eles como uma adivinhação inverídica aos seus olhos — os que lhes eram ajuramentados; e ele faz lembrar o erro, para que fossem capturados.

[[v26-21-24]]

^<<v26-21-24,24>>^ “Portanto, assim disse o Soberano Senhor Jeová: ‘Visto que fazeis lembrar o vosso erro por se descobrirem as vossas transgressões, para que se vejam os vossos pecados segundo todas as vossas ações, por serdes lembrados, sereis pegados pela mão.’

[[v26-21-25]]

^<<v26-21-25,25>>^ “E no que se refere a ti, ó mortalmente ferido maioral iníquo de Israel, cujo dia chegou no tempo do erro do fim,

[[v26-21-26]]

^<<v26-21-26,26>>^ assim disse o Soberano Senhor Jeová: ‘Remove o turbante e retira a coroa. Esta^&#42;1^ não será a mesma.^&#42;2^ Põe no alto o rebaixado e rebaixa o que estiver no alto.

[NOTE]
====
. “Esta.” Hebr.: zo’th, fem.
. “A mesma.” Lit.: “esta”, hebr. fem.
====

[[v26-21-27]]

^<<v26-21-27,27>>^ Uma ruína, uma ruína, uma ruína^&#42;1^ a^&#42;2^ farei. Também, quanto a esta,^&#42;3^ certamente não virá a ser de [ninguém], até que venha aquele que tem o direito legal, e a ele é que terei de dá-lo.’^&#42;4^

[NOTE]
====
. Ou “uma distorção (torcedura)”.
. “A.” Hebr. fem.
. “Esta.” Hebr.: zo’th, fem.
. Isto é, o que lhe é devido.
====

[[v26-21-28]]

^<<v26-21-28,28>>^ “E tu, ó filho do homem, profetiza, e tens de dizer: ‘Assim disse o Soberano Senhor Jeová a respeito dos filhos de Amom e a respeito do vitupério da parte deles.’ E tens de dizer: ‘Uma espada, uma espada desembainhada para o abate, polida para fazê-la devorar,^&#42;1^ a fim de lampejar,

[NOTE]
====
. Ou “polida para um extermínio”.
====

[[v26-21-29]]

^<<v26-21-29,29>>^ por [eles] observarem para ti^&#42;1^ uma irrealidade, por [eles] adivinharem para ti uma mentira, a fim de pôr-te ao pescoço dos que foram mortos, os homens iníquos, cujo dia chegou no tempo do erro do fim.

[NOTE]
====
. “Ti”, hebr. fem. sing., evidentemente referindo-se a Rabá dos amonitas.
====

[[v26-21-30]]

^<<v26-21-30,30>>^ Retorna-a à sua bainha. No lugar em que foste criada, na terra da tua origem, te julgarei.

[[v26-21-31]]

^<<v26-21-31,31>>^ Vou derramar sobre ti a minha verberação. Soprarei sobre ti com o fogo da minha fúria e vou entregar-te na mão de homens desarrazoados, os artífices da ruína.

[[v26-21-32]]

^<<v26-21-32,32>>^ Tornar-te-ás combustível para o fogo. Teu próprio sangue virá a estar no meio da terra. Não serás lembrada, porque eu, Jeová, é que falei.’”

'''

xref:026-ezequiel/026-ezequiel-020.adoc#v26-20-0[&#60; Capítulo Anterior] | <<v26-21-0,Topo>> | xref:026-ezequiel/026-ezequiel-022.adoc#v26-22-0[Próximo Capítulo &#62;]