include::./index.adoc[]

[[v26-36-0]]
=== Ezequiel, 36
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v26-36-1]]

^<<v26-36-1,1>>^ “E quanto a ti, ó filho do homem, profetiza concernente aos montes de Israel, e tens de dizer: ‘Ó montes de Israel, ouvi a palavra de Jeová.

[[v26-36-2]]

^<<v26-36-2,2>>^ Assim disse o Soberano Senhor Jeová: “Visto que o inimigo disse contra ti: ‘Ah! Sim, os altos do tempo antigo — isso veio a ser possessão nossa!’”’

[[v26-36-3]]

^<<v26-36-3,3>>^ “Por isso profetiza, e tens de dizer: ‘Assim disse o Soberano Senhor Jeová: “Pela razão, sim, pela razão de que houve desolação e fostes abocanhados de todos os lados, para que vos tornásseis possessão dos remanescentes das nações, e de que se continua a falar de vós com a língua e há um relato mau entre o povo,

[[v26-36-4]]

^<<v26-36-4,4>>^ por isso, ó montes de Israel, ouvi a palavra do Soberano Senhor Jeová! Assim disse o Soberano Senhor Jeová aos montes e aos morros, aos regos e aos vales, e aos lugares devastados que foram desolados, e às cidades abandonadas que vieram a ficar para saque e para caçoada para os remanescentes das nações ao redor;

[[v26-36-5]]

^<<v26-36-5,5>>^ portanto, assim disse o Soberano Senhor Jeová: ‘Eu certamente vou falar no fogo do meu zelo contra os remanescentes das nações e contra Edom, na sua inteireza, os que se deram a si mesmos a minha terra como possessão com alegria de todo o coração, com menosprezo na alma, por causa do seu pasto [e] para saque.’”’

[[v26-36-6]]

^<<v26-36-6,6>>^ “Portanto, profetiza a respeito do solo de Israel, e tens de dizer aos montes e aos morros, aos regos e aos vales: ‘Assim disse o Soberano Senhor Jeová: “Eis que eu mesmo tenho de falar no meu zelo e no meu furor, por terdes levado humilhação da parte das nações.”’

[[v26-36-7]]

^<<v26-36-7,7>>^ “Portanto, assim disse o Soberano Senhor Jeová: ‘Eu mesmo levantei a minha mão [em juramento] de que as nações em volta de vós — elas é que levarão a sua própria humilhação.

[[v26-36-8]]

^<<v26-36-8,8>>^ E vós mesmos, ó montes de Israel, produzireis os vossos próprios galhos e dareis os vossos próprios frutos para meu povo de Israel, pois chegaram-se perto ao ponto de entrar.

[[v26-36-9]]

^<<v26-36-9,9>>^ Pois, eis que sou a favor de vós e hei de virar-me para vós, e sereis realmente cultivados e semeados com semente.

[[v26-36-10]]

^<<v26-36-10,10>>^ E eu vou multiplicar em vós o gênero humano,^&#42;1^ toda a casa de Israel, na sua inteireza, e as cidades terão de ser habitadas e os próprios lugares devastados serão reconstruídos.

[NOTE]
====
. Ou “homens terrenos”. Hebr.: ’a·dhám; lat.: hó·mi·nes.
====

[[v26-36-11]]

^<<v26-36-11,11>>^ Sim, vou multiplicar sobre vós o gênero humano e os animais, e eles certamente se multiplicarão e se tornarão fecundos, e realmente farei que sejais habitados, como na vossa condição anterior, e vou fazer mais bem do que na vossa situação inicial; e tereis de saber que eu sou Jeová.

[[v26-36-12]]

^<<v26-36-12,12>>^ E farei andar sobre vós o gênero humano, sim, meu povo de Israel, e terão de tomar posse de vós^&#42;1^ e tereis de tornar-vos para eles uma propriedade hereditária, e vós não mais os privareis de filhos.’”

[NOTE]
====
. “Vós”, LXXSy; MTVg: “ti”.
====

[[v26-36-13]]

^<<v26-36-13,13>>^ “Assim disse o Soberano Senhor Jeová: ‘Visto que há os que vos dizem: “Devorador da humanidade é o que tu és, e [uma terra]^&#42;1^ que priva as nações de filhos é o que te tornaste”’,

[NOTE]
====
. Lit.: “uma”, hebr. fem., referindo-se à terra, hebr. fem.
====

[[v26-36-14]]

^<<v26-36-14,14>>^ ‘por isso, não mais devorarás o gênero humano e não mais privarás as tuas nações de filhos’,^&#42;1^ é a pronunciação do Soberano Senhor Jeová.

[NOTE]
====
. “Privarás . . . de filhos”, MmargemLXXSy e muitos mss. hebr.; M: “farás . . . tropeçar”.
====

[[v26-36-15]]

^<<v26-36-15,15>>^ ‘E farei que não se ouça mais nenhuma conversa humilhante a teu respeito da parte das nações, e não levarás mais o vitupério dos povos, e não mais farás tropeçar as tuas nações’, é a pronunciação do Soberano Senhor Jeová.”

[[v26-36-16]]

^<<v26-36-16,16>>^ E continuou a vir a haver para mim a palavra de Jeová, dizendo:

[[v26-36-17]]

^<<v26-36-17,17>>^ “Filho do homem, a casa de Israel [estava] morando sobre o seu solo, e eles continuavam a fazê-lo impuro com o seu procedimento e com as suas ações. Seu procedimento tornou-se diante de mim como a impureza da menstruação.

[[v26-36-18]]

^<<v26-36-18,18>>^ E passei a derramar sobre eles meu furor por causa do sangue que derramaram sobre a terra, a qual tornaram impura com os seus ídolos sórdidos.

[[v26-36-19]]

^<<v26-36-19,19>>^ E passei a espalhá-los entre as nações, de modo que ficaram dispersos entre as terras. Julguei-os segundo o seu procedimento e segundo as suas ações.

[[v26-36-20]]

^<<v26-36-20,20>>^ E entraram^&#42;1^ nas nações em que tinham de entrar, e as pessoas^&#42;2^ passaram a profanar o meu santo nome, dizendo com referência a eles: ‘Este é o povo de Jeová, e saíram da sua terra.’

[NOTE]
====
. “Entraram”, TLXXSyVg e alguns mss. hebr.; M: “entrou”.
. Lit.: “eles”.
====

[[v26-36-21]]

^<<v26-36-21,21>>^ E eu me compadecerei do meu santo nome que a casa de Israel tem profanado entre as nações nas quais entraram.”

[[v26-36-22]]

^<<v26-36-22,22>>^ “Portanto, dize à casa de Israel: ‘Assim disse o Soberano Senhor Jeová: “Não é por vós que eu faço [isso], ó casa de Israel, mas por meu santo nome que tendes profanado entre as nações nas quais entrastes.”’

[[v26-36-23]]

^<<v26-36-23,23>>^ ‘E hei de santificar^&#42;1^ meu grande nome que tem sido profanado entre as nações, que tendes profanado no meio delas; e as nações terão de saber que eu sou Jeová’, é a pronunciação do Soberano Senhor Jeová, ‘quando eu for santificado entre vós diante dos seus olhos.

[NOTE]
====
. Ou: “E hei de ter como sagrado (tratar como santo).” Hebr.: weqid·dash·tí; gr.: ha·gi·á·so; lat.: sanc·ti·fi·cá·bo.
====

[[v26-36-24]]

^<<v26-36-24,24>>^ E vou tirar-vos dentre as nações e reunir-vos dentre todas as terras, e vou fazer-vos chegar ao vosso solo.

[[v26-36-25]]

^<<v26-36-25,25>>^ E vou aspergir-vos com água limpa e vós vos tornareis limpos; purificar-vos-ei de todas as vossas impurezas e de todos os vossos ídolos sórdidos.

[[v26-36-26]]

^<<v26-36-26,26>>^ E vou dar-vos um coração novo, e porei no vosso íntimo um espírito novo, e vou remover da vossa carne o coração de pedra e dar-vos um coração de carne.

[[v26-36-27]]

^<<v26-36-27,27>>^ E porei meu espírito no vosso íntimo, e vou agir de modo a que andeis nos meus regulamentos, e guardareis as minhas decisões judiciais e realmente as cumprireis.

[[v26-36-28]]

^<<v26-36-28,28>>^ E haveis de morar na terra que dei aos vossos antepassados, e tereis de tornar-vos meu povo e eu mesmo me tornarei o vosso Deus.’^&#42;1^

[NOTE]
====
. Lit.: “para vós para Deus”. Hebr.: la·khém lE’·lo·hím.
====

[[v26-36-29]]

^<<v26-36-29,29>>^ “‘E vou salvar-vos de todas as vossas impurezas, e vou chamar o cereal e fazê-lo abundar, e não porei sobre vós nenhuma fome.

[[v26-36-30]]

^<<v26-36-30,30>>^ E certamente farei abundar os frutos da árvore e os produtos do campo, para que não mais recebais entre as nações o vitupério da fome.

[[v26-36-31]]

^<<v26-36-31,31>>^ E forçosamente haveis de lembrar-vos dos vossos maus caminhos e das vossas ações que não eram boas, e forçosamente tereis aversão à vossa própria pessoa por causa dos vossos erros e por causa das vossas coisas detestáveis.

[[v26-36-32]]

^<<v26-36-32,32>>^ Não é por vós que faço [isso]’, é a pronunciação do Soberano Senhor Jeová, ‘seja isso sabido por vós. Envergonhai-vos e senti-vos humilhados por causa dos vossos caminhos, ó casa de Israel.’

[[v26-36-33]]

^<<v26-36-33,33>>^ “Assim disse o Soberano Senhor Jeová: ‘No dia em que eu vos purificar de todos os vossos erros vou fazer também que as cidades sejam habitadas, e terão de ser reconstruídos os lugares devastados.

[[v26-36-34]]

^<<v26-36-34,34>>^ E a própria terra desolada será cultivada, sendo que se tornara um baldio desolado diante dos olhos de todo transeunte.

[[v26-36-35]]

^<<v26-36-35,35>>^ E as pessoas hão de dizer: “Aquela terra lá, que fora desolada, tem-se tornado como o jardim^&#42;1^ do Éden, e as cidades que estavam devastadas e que tinham sido desoladas e derrubadas estão fortificadas; foram habitadas.”

[NOTE]
====
. “Como o jardim.” Hebr.: keghán; sir.: par·dai·sa’, “o paraíso”.
====

[[v26-36-36]]

^<<v26-36-36,36>>^ E as nações que se deixarão restar em volta de vós terão de saber que eu, Jeová, é que construí as coisas derrubadas, plantei o que estava desolado. Eu, Jeová, é que falei e fiz [isso].’

[[v26-36-37]]

^<<v26-36-37,37>>^ “Assim disse o Soberano Senhor Jeová: ‘Por isso é que me deixarei ainda ser buscado pela casa de Israel, para fazer para eles: Multiplicá-los-ei com homens^&#42;1^ qual rebanho.

[NOTE]
====
. Ou “humanidade”. Hebr.: ’a·dhám; lat.: hó·mi·num.
====

[[v26-36-38]]

^<<v26-36-38,38>>^ Qual rebanho de pessoas santas, qual rebanho de Jerusalém nas suas épocas festivas, assim é que as cidades que estavam devastadas se tornarão cheias de um rebanho de homens; e as pessoas terão de saber que eu sou Jeová.’”

'''

xref:026-ezequiel/026-ezequiel-035.adoc#v26-35-0[&#60; Capítulo Anterior] | <<v26-36-0,Topo>> | xref:026-ezequiel/026-ezequiel-037.adoc#v26-37-0[Próximo Capítulo &#62;]