include::./index.adoc[]

[[v26-25-0]]
=== Ezequiel, 25
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v26-25-1]]

^<<v26-25-1,1>>^ E continuou a vir a haver para mim a palavra de Jeová, dizendo:

[[v26-25-2]]

^<<v26-25-2,2>>^ “Filho do homem, fixa a tua face em direção aos filhos de Amom e profetiza contra eles.

[[v26-25-3]]

^<<v26-25-3,3>>^ E tens de dizer a respeito dos filhos de Amom: ‘Ouvi a palavra do Soberano Senhor Jeová. Assim disse o Soberano Senhor Jeová: “Visto que disseste^&#42;1^ Ah! contra o meu santuário, por ele ter sido profanado, e contra o solo de Israel, por ele ter sido desolado, e contra a casa de Judá, porque foram para o exílio,

[NOTE]
====
. “Disseste”, hebr. fem. sing., referindo-se à terra de Amom.
====

[[v26-25-4]]

^<<v26-25-4,4>>^ por isso, eis que te entrego aos orientais^&#42;1^ como possessão, e eles armarão em ti os seus acampamentos murados e certamente porão em ti os seus tabernáculos. Eles mesmos comerão os teus frutos e eles mesmos beberão o teu leite.

[NOTE]
====
. Lit.: “aos filhos do Oriente”.
====

[[v26-25-5]]

^<<v26-25-5,5>>^ E vou fazer de Rabá uma pastagem de camelos e dos filhos de Amom um lugar de repouso do rebanho; e tereis de saber que eu sou Jeová.”’”

[[v26-25-6]]

^<<v26-25-6,6>>^ “Pois assim disse o Soberano Senhor Jeová: ‘Visto que bateste^&#42;1^ as mãos e bateste com os pés, e continuaste a alegrar-te com todo o menosprezo da tua parte na [tua] alma contra o solo de Israel,

[NOTE]
====
. “Bateste”, hebr. masc. sing., referindo-se a Amom.
====

[[v26-25-7]]

^<<v26-25-7,7>>^ portanto, eis que estou aqui; estendi a mão contra ti e vou entregar-te às nações como algo a ser saqueado; e vou decepar-te dos povos e destruir-te das terras. Aniquilar-te-ei, e terás de saber que eu sou Jeová.’

[[v26-25-8]]

^<<v26-25-8,8>>^ “Assim disse o Soberano Senhor Jeová: ‘Visto que Moabe e Seir disseram: “Eis que a casa de Judá é igual a todas as outras nações”,

[[v26-25-9]]

^<<v26-25-9,9>>^ por isso, eis que estou abrindo a encosta de Moabe nas cidades, nas suas cidades até os seus limites, o ornato da terra, Bete-Jesimote, Baal-Meom, até mesmo a Quiriataim,

[[v26-25-10]]

^<<v26-25-10,10>>^ aos orientais,^&#42;1^ ao lado dos filhos de Amom; e vou fazê-lo uma possessão, para que não seja lembrado, [quer dizer,] os filhos de Amom, entre as nações.

[NOTE]
====
. Veja v. 4 n.
====

[[v26-25-11]]

^<<v26-25-11,11>>^ E executarei atos de julgamento em Moabe; e terão de saber que eu sou Jeová.’

[[v26-25-12]]

^<<v26-25-12,12>>^ “Assim disse o Soberano Senhor Jeová: ‘Visto que Edom agiu, tomando vingança da casa de Judá, e eles continuam a proceder extensivamente em erro e a vingar-se deles,

[[v26-25-13]]

^<<v26-25-13,13>>^ por isso, assim disse o Soberano Senhor Jeová: “Vou também estender a minha mão contra Edom e decepar dele homem^&#42;1^ e animal doméstico, e vou fazer dele um lugar devastado, desde Temã até Dedã. À espada é que cairão.

[NOTE]
====
. Ou “homem terreno”. Hebr.: ’a·dhám.
====

[[v26-25-14]]

^<<v26-25-14,14>>^ ‘E eu vou trazer minha vingança sobre Edom pela mão do meu povo de Israel; e terão de fazer em Edom segundo a minha ira e segundo o meu furor; e terão de conhecer a minha vingança’, é a pronunciação do Soberano Senhor Jeová.”’

[[v26-25-15]]

^<<v26-25-15,15>>^ “Assim disse o Soberano Senhor Jeová: ‘Visto que os filisteus agiram com vingança e foram vingar-se com vingança, com menosprezo na alma,^&#42;1^ para arruinar, com inimizade de duração indefinida,

[NOTE]
====
. “Na alma.” Hebr.: bené·fesh; gr.: psy·khés; lat.: á·ni·mo. Veja Ap. 4A.
====

[[v26-25-16]]

^<<v26-25-16,16>>^ por isso, assim disse o Soberano Senhor Jeová: “Eis que estendo a minha mão contra os filisteus, e vou decepar os queretitas^&#42;1^ e destruir o resto da costa marítima.

[NOTE]
====
. “Cretenses”, LXX.
====

[[v26-25-17]]

^<<v26-25-17,17>>^ E vou executar neles grandes atos de vingança, com furiosas repreensões; e terão de saber que eu sou Jeová, quando eu trouxer sobre eles a minha vingança.”’”

'''

xref:026-ezequiel/026-ezequiel-024.adoc#v26-24-0[&#60; Capítulo Anterior] | <<v26-25-0,Topo>> | xref:026-ezequiel/026-ezequiel-026.adoc#v26-26-0[Próximo Capítulo &#62;]