include::./index.adoc[]

[[v26-38-0]]
=== Ezequiel, 38
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v26-38-1]]

^<<v26-38-1,1>>^ E continuou a vir a haver para mim a palavra de Jeová, dizendo:

[[v26-38-2]]

^<<v26-38-2,2>>^ “Filho do homem, fixa a tua face contra Gogue da terra de Magogue,^&#42;1^ o maioral-chefe^&#42;2^ de Meseque e Tubal, e profetiza contra ele.

[NOTE]
====
. “Gogue da terra de Magogue”, MT; LXX: “Gogue e a terra de Magogue”; Sy: “Gogue e contra a terra de Magogue”; Vg: “Gogue, a terra de Magogue.” “Magogue” é uma forma artificial, equivalente a “lar de Gogue”, segundo KB, p. 493.
. “Maioral-chefe.” Ou “maioral de Rôs”. Vg: “principal príncipe”; LXX: “governante de Rôs”; Sy: “líder e cabeça”.
====

[[v26-38-3]]

^<<v26-38-3,3>>^ E tens de dizer: ‘Assim disse o Soberano Senhor Jeová: “Eis que sou contra ti, ó Gogue, maioral-chefe de Meseque e Tubal.

[[v26-38-4]]

^<<v26-38-4,4>>^ E hei de voltar-te e pôr ganchos nas tuas maxilas, e hei de fazer-te sair com toda a tua força militar, cavalos e cavaleiros, todos eles vestidos com esmero, uma congregação numerosa, com escudo grande e broquel, todos eles manejando espadas;

[[v26-38-5]]

^<<v26-38-5,5>>^ com eles Pérsia, Etiópia^&#42;1^ e Pute, todos eles com broquel e capacete;

[NOTE]
====
. “Etiópia.” Hebr.: Kush; LXXVg: “etíopes”.
====

[[v26-38-6]]

^<<v26-38-6,6>>^ Gômer e todas as suas tropas, a casa de Togarma, [das] partes mais remotas do norte, e todas as suas tropas, muitos povos contigo.

[[v26-38-7]]

^<<v26-38-7,7>>^ “‘“Apronta-te e faze preparativos, tu com toda a tua congregação, os congregados ao teu lado, e tens de tornar-te guarda deles.

[[v26-38-8]]

^<<v26-38-8,8>>^ “‘“Depois de muitos dias se fixará a atenção em ti. Na parte final dos anos virás à terra [daqueles] que foram recuperados da espada, reunidos dentre muitos povos, aos montes de Israel, que mostraram ser um lugar perenemente devastado; sim, [uma terra]^&#42;1^ tirada dos povos, [em que] todos eles moravam em segurança.

[NOTE]
====
. Lit.: “ela”, hebr. fem., referindo-se à “terra”, hebr. fem.
====

[[v26-38-9]]

^<<v26-38-9,9>>^ E forçosamente subirás. Entrarás como tempestade. Tornar-te-ás como nuvens para cobrir a terra, tu e todas as tuas tropas, e muitos povos contigo.”’

[[v26-38-10]]

^<<v26-38-10,10>>^ “Assim disse o Soberano Senhor Jeová: ‘E naquele dia terá de acontecer que subirão coisas ao teu coração e certamente inventarás um ardil maligno;

[[v26-38-11]]

^<<v26-38-11,11>>^ e terás de dizer: “Subirei contra a terra campestre. Chegarei aos que têm sossego, morando em segurança, todos eles habitando sem muralha, e eles não têm nem mesmo tranca e portas.”

[[v26-38-12]]

^<<v26-38-12,12>>^ Será para ganhar muito despojo e fazer grande saque, a fim de fazer a tua mão voltar aos lugares devastados, novamente habitados, e a um povo reunido dentre as nações, que está acumulando riqueza e bens, morando no meio^&#42;1^ da terra.

[NOTE]
====
. Lit.: “umbigo”. Lat.: um·bi·lí·ci.
====

[[v26-38-13]]

^<<v26-38-13,13>>^ “‘Sabá e Dedã, e os mercadores de Társis, e todos os seus leões novos jubados — eles te dirão: “É para ganhar muito despojo que estás entrando? É para fazer grande saque que congregaste a tua congregação, para carregar com prata e ouro, para tomar riqueza e bens, para ganhar um grandíssimo despojo?”’

[[v26-38-14]]

^<<v26-38-14,14>>^ “Portanto, profetiza, ó filho do homem, e tens de dizer a Gogue: ‘Assim disse o Soberano Senhor Jeová: “Não [o] saberás tu naquele dia quando meu povo de Israel morar em segurança?

[[v26-38-15]]

^<<v26-38-15,15>>^ E hás de vir do teu lugar, das partes mais remotas do norte, tu e muitos povos contigo, todos eles montados em cavalos, uma grande congregação, sim, uma numerosa força militar.

[[v26-38-16]]

^<<v26-38-16,16>>^ E forçosamente subirás contra o meu povo de Israel como nuvens cobrindo a terra. Isto ocorrerá na parte final dos dias, e eu certamente te trarei contra a minha terra, com o fim de que as nações me conheçam quando eu me santificar em ti perante os seus olhos, ó Gogue.”’

[[v26-38-17]]

^<<v26-38-17,17>>^ “Assim disse o Soberano Senhor Jeová: ‘És tu o mesmo de quem falei nos dias anteriores pela mão dos meus servos, os profetas de Israel, que profetizavam naqueles dias — anos — quanto a fazer-te chegar contra eles?’

[[v26-38-18]]

^<<v26-38-18,18>>^ “‘E terá de acontecer naquele dia, no dia em que Gogue chegar ao solo de Israel’, é a pronunciação do Soberano Senhor Jeová, ‘que meu furor me subirá no nariz.

[[v26-38-19]]

^<<v26-38-19,19>>^ E terei de falar no meu fervor, no fogo da minha fúria. Naquele dia seguramente ocorrerá um grande tremor no solo^&#42;1^ de Israel.

[NOTE]
====
. “No solo.” Hebr.: ’adh·máth.
====

[[v26-38-20]]

^<<v26-38-20,20>>^ E, por minha causa, forçosamente tremerão os peixes do mar, e as criaturas voadoras dos céus, e os animais selváticos do campo, e todas as coisas rastejantes que se arrastam sobre o solo, e todo o gênero humano^&#42;1^ na superfície do solo, e realmente serão derrubados os montes e terão de cair os caminhos escarpados, e até mesmo toda muralha cairá por terra.’

[NOTE]
====
. Ou “homens terrenos”. Hebr.: ha·’a·dhám.
====

[[v26-38-21]]

^<<v26-38-21,21>>^ “‘E vou chamar contra ele uma espada em toda a minha região montanhosa’, é a pronunciação do Soberano Senhor Jeová. ‘A espada de cada um virá a ser contra o seu próprio irmão.

[[v26-38-22]]

^<<v26-38-22,22>>^ E vou pôr-me em julgamento contra ele, com peste e com sangue; e farei cair um aguaceiro inundante e pedras de saraiva, fogo e enxofre sobre ele, e sobre as suas tropas, e sobre os muitos povos com ele.

[[v26-38-23]]

^<<v26-38-23,23>>^ E eu hei de magnificar-me, e santificar-me, e dar-me a conhecer aos olhos de muitas nações; e terão de saber que eu sou Jeová.’

'''

xref:026-ezequiel/026-ezequiel-037.adoc#v26-37-0[&#60; Capítulo Anterior] | <<v26-38-0,Topo>> | xref:026-ezequiel/026-ezequiel-039.adoc#v26-39-0[Próximo Capítulo &#62;]