include::./index.adoc[]

[[v26-47-0]]
=== Ezequiel, 47
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v26-47-1]]

^<<v26-47-1,1>>^ E ele me levou aos poucos de volta à entrada da Casa, e eis que saía água de debaixo do limiar da Casa para o leste, pois a frente da Casa dava para o leste. E a água saía de debaixo, do lado direito da Casa, ao sul do altar.

[[v26-47-2]]

^<<v26-47-2,2>>^ E ele me fez sair aos poucos pelo caminho do portão setentrional e me fez dar volta pelo caminho de fora até o portão externo que dá para o leste, e eis que escorria água do lado direito.

[[v26-47-3]]

^<<v26-47-3,3>>^ Quando o homem^&#42;1^ saiu para o leste com o cordel de medir na mão, passou a medir também mil côvados e a fazer-me passar pela água, água [até] os tornozelos.^&#42;2^

[NOTE]
====
. “O homem.” Hebr.: ha·’ísh.
. Lit.: “água de tornozelos”.
====

[[v26-47-4]]

^<<v26-47-4,4>>^ E continuou a medir mil e então me fez passar pela água, água [até] os joelhos.
E continuou a medir mil e então me fez passar — água [até] os quadris.

[[v26-47-5]]

^<<v26-47-5,5>>^ E ele continuou a medir mil. Era uma torrente pela qual não pude passar, porque a água ficara alta, água [em que se podia] nadar, uma torrente pela qual não se podia passar.

[[v26-47-6]]

^<<v26-47-6,6>>^ Então me disse ele: “Viste [isso], ó filho do homem?”
Então me fez andar e me fez voltar^&#42;1^ à beira da torrente.

[NOTE]
====
. “Me fez voltar”, MTVg; Sy: “me fez sentar”; LXX omite isso.
====

[[v26-47-7]]

^<<v26-47-7,7>>^ Quando retornei, ora, eis que havia à beira da torrente muitíssimas árvores, deste lado e daquele lado.

[[v26-47-8]]

^<<v26-47-8,8>>^ E ele prosseguiu, dizendo-me: “Esta água sai para a região oriental e tem de descer pelo Arabá.^&#42;1^ E tem de chegar ao mar. Sendo levada ao próprio mar, então a água^&#42;2^ [deste] ficará realmente curada.

[NOTE]
====
. Ou “pela planície desértica”. Veja De 1:1 n.: “desérticas”.
. “Às águas fedorentas, e as águas”, Sy.
====

[[v26-47-9]]

^<<v26-47-9,9>>^ E terá de acontecer que toda alma vivente,^&#42;1^ pululante, em todo lugar ao qual chegar a torrente de tamanho duplo,^&#42;2^ terá vida.^&#42;3^ E terá de acontecer que haverá muitíssimos peixes, porque é para lá que há de chegar esta água, e a [água do mar] ficará curada, e aonde chegar a torrente, tudo ficará vivo.

[NOTE]
====
. “Alma vivente.” Hebr.: né·fesh hhai·yáh; gr.: psy·khé ton zoí·on; lat.: á·ni·ma ví·vens. Veja Gên 2:7 n.: “vivente”; Ap. 4A.
. Lit.: “duas torrentes”, M; TSy: “as águas da torrente”; LXX: “o rio”; Vg: “a torrente”.
. Ou “passará a viver; viverá”. Hebr.: yihh·yéh.
====

[[v26-47-10]]

^<<v26-47-10,10>>^ “E terá de acontecer que realmente haverá pescadores de pé ao longo dela, desde En-Gedi para cima até En-Eglaim. Virá a haver um enxugadouro de redes de arrasto. Os peixes mostrarão ser das suas espécies,^&#42;1^ iguais aos peixes do Grande Mar,^&#42;2^ muitíssimos.

[NOTE]
====
. “Das suas espécies.” Hebr.: lemi·náh; lat.: spé·ci·es.
. Isto é, o Mar Mediterrâneo.
====

[[v26-47-11]]

^<<v26-47-11,11>>^ “Ali estarão os seus brejos e os seus charcos, e estes não serão curados. Hão de ser entregues ao sal.

[[v26-47-12]]

^<<v26-47-12,12>>^ “E ao longo da torrente, ao longo da sua beira, surgirá toda sorte de árvore para alimento. Sua folhagem não murchará, nem se acabará seu fruto. Darão novo fruto nos seus meses, porque a água para elas — ela sai do próprio santuário.^&#42;1^ E seu fruto terá de mostrar ser para alimento e sua folhagem para cura.”

[NOTE]
====
. “Do . . . santuário.” Hebr.: ham·miq·dásh.
====

[[v26-47-13]]

^<<v26-47-13,13>>^ Assim disse o Soberano Senhor Jeová: “Este é o território que designareis a vós mesmos por herança como terra para as doze tribos de Israel, com dois lotes para José.

[[v26-47-14]]

^<<v26-47-14,14>>^ E tereis de herdá-la, cada um igual ao seu irmão, [terra] a respeito da qual levantei a minha mão [em juramento] de dá-la aos vossos antepassados; e esta terra terá de cair para vós [por sortes] como herança.

[[v26-47-15]]

^<<v26-47-15,15>>^ “E este é o termo da terra do lado setentrional, desde o Grande Mar pelo caminho de Hetlom, conforme se chega a Zedade,

[[v26-47-16]]

^<<v26-47-16,16>>^ Hamate, Berota, Sibraim, entre o termo de Damasco e o termo de Hamate; Hazer-Haticom que está na direção do termo de Haurã.

[[v26-47-17]]

^<<v26-47-17,17>>^ E o termo do mar tem de mostrar ser Hazar-Enom,^&#42;1^ o termo de Damasco para o norte — na direção do norte, e o termo de Hamate. Este é o lado setentrional.

[NOTE]
====
. “Hazar-Enom”, M; LXX: “o pátio de Ainã”.
====

[[v26-47-18]]

^<<v26-47-18,18>>^ “E o lado oriental é desde entre Haurã e Damasco, e desde entre Gileade e a terra de Israel; o Jordão^&#42;1^ deveis medir desde o termo até o mar oriental. Este é o lado oriental.

[NOTE]
====
. Possivelmente, paralelo ao rio Jordão.
====

[[v26-47-19]]

^<<v26-47-19,19>>^ “E o lado meridional^&#42;1^ é para o sul,^&#42;2^ desde Tamar até as águas de Meribate-Cades, o vale de torrente até o Grande Mar. Este é o lado meridional em direção ao Negebe.^&#42;3^

[NOTE]
====
. “Meridional.” Hebr.: né·ghev.
. “Para o sul.” Hebr.: teh·má·nah.
. Ou “sul”. Isto é, a parte meridional da Terra da Promessa. Veja Gên 12:9 n.
====

[[v26-47-20]]

^<<v26-47-20,20>>^ “E o lado ocidental é o Grande Mar, desde o termo diretamente adiante até a entrada de Hamate.^&#42;1^ Este é o lado ocidental.”

[NOTE]
====
. “Até a entrada de Hamate.” Possivelmente: “Lebo-Hamate”. Hebr.: levóh’ Hhamáth. Veja Jos 13:5 n.: “Hamate”; KB, p. 470, sob לבא (La·vó’).
====

[[v26-47-21]]

^<<v26-47-21,21>>^ “E tereis de repartir esta terra entre vós mesmos, entre as doze tribos de Israel.

[[v26-47-22]]

^<<v26-47-22,22>>^ E terá de acontecer que deveis loteá-la como herança para vós e para os residentes forasteiros que residem no vosso meio, que se tornaram pais de filhos no vosso meio. E eles terão de tornar-se para vós iguais ao natural entre os filhos de Israel. Convosco terão [por sortes] uma herança no meio das tribos de Israel.

[[v26-47-23]]

^<<v26-47-23,23>>^ E terá de acontecer que tereis de dar-lhe a herança na tribo em que o residente forasteiro estabeleceu residência”, é a pronunciação do Soberano Senhor Jeová.

'''

xref:026-ezequiel/026-ezequiel-046.adoc#v26-46-0[&#60; Capítulo Anterior] | <<v26-47-0,Topo>> | xref:026-ezequiel/026-ezequiel-048.adoc#v26-48-0[Próximo Capítulo &#62;]