include::./index.adoc[]

[[v26-24-0]]
=== Ezequiel, 24
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v26-24-1]]

^<<v26-24-1,1>>^ E continuou a vir a haver para mim a palavra de Jeová no nono ano, no décimo mês, no décimo [dia] do mês, dizendo:

[[v26-24-2]]

^<<v26-24-2,2>>^ “Filho do homem, escreve para ti o nome do dia, deste mesmo dia. O rei de Babilônia lançou-se neste mesmo dia contra Jerusalém.

[[v26-24-3]]

^<<v26-24-3,3>>^ E compõe uma expressão proverbial a respeito da casa rebelde, e tens de dizer a seu respeito:
“‘Assim disse o Soberano Senhor Jeová: “Põe a panela de boca larga; põe-na e despeja nela água.

[[v26-24-4]]

^<<v26-24-4,4>>^ Ajunta pedaços nela, todo pedaço bom, coxa e espádua; enche-a mesmo com os ossos mais seletos.

[[v26-24-5]]

^<<v26-24-5,5>>^ Tomem-se as ovelhas mais seletas, e empilha também a lenha^&#42;1^ num círculo debaixo dela. Fervam-se seus pedaços,^&#42;2^ cozinha também os seus ossos dentro dela.”’”

[NOTE]
====
. Mediante uma correção; M: “ossos”.
. “Pedaços”, dois mss. hebr.; M: “fervuras”.
====

[[v26-24-6]]

^<<v26-24-6,6>>^ “Portanto, assim disse o Soberano Senhor Jeová: ‘Ai da cidade de derramamentos de sangue,^&#42;1^ da panela de boca larga, cuja ferrugem está nela, e sua própria ferrugem não saiu dela! Traze-a para fora, pedaço por pedaço dela; não se deve lançar sortes sobre ela.

[NOTE]
====
. “Derramamentos de sangue.” Lit.: “sangues”.
====

[[v26-24-7]]

^<<v26-24-7,7>>^ Porque o próprio sangue dela veio a estar bem no seu meio. Colocou-o sobre a lustrosa superfície escalvada dum rochedo. Não o derramou sobre a terra para cobri-lo com pó.

[[v26-24-8]]

^<<v26-24-8,8>>^ A fim de suscitar furor para a execução de vingança, eu pus o sangue dela sobre a lustrosa superfície escalvada dum rochedo, para que não fosse encoberto.’

[[v26-24-9]]

^<<v26-24-9,9>>^ “Portanto, assim disse o Soberano Senhor Jeová: ‘Ai da cidade de derramamentos de sangue! Eu mesmo também farei grande a pilha [de lenha].

[[v26-24-10]]

^<<v26-24-10,10>>^ Faze que haja muita lenha. Acende o fogo. Faze ferver cabalmente a carne. Despeja o caldo^&#42;1^ e tornem-se candentes os próprios ossos.

[NOTE]
====
. “Despeja o caldo”, mediante uma correção; M: “tempere-se com ervas aromáticas”.
====

[[v26-24-11]]

^<<v26-24-11,11>>^ Põe-na^&#42;1^ vazia sobre as brasas para que fique aquecida; e seu cobre tem de ficar candente e sua impureza terá de ser fundida no meio dela. Seja consumida a sua ferrugem.

[NOTE]
====
. “[Põe-]na”, hebr. fem.
====

[[v26-24-12]]

^<<v26-24-12,12>>^ Dificuldades! Isso fatiga [a pessoa], mas a grande quantidade da sua ferrugem não sai dela. Para [o] fogo com a sua ferrugem!’

[[v26-24-13]]

^<<v26-24-13,13>>^ “‘Havia conduta desenfreada na tua^&#42;1^ impureza. Por esta razão tive de purificar-te, mas não ficaste limpa da tua impureza. Não mais ficarás limpa, até que eu faça o meu furor descansar no teu caso.

[NOTE]
====
. “Tua”, hebr. fem. sing., dirigido à cidade.
====

[[v26-24-14]]

^<<v26-24-14,14>>^ Eu, Jeová, é que falei. Isso tem de vir, e eu vou agir. Não negligenciarei, nem terei dó, nem sentirei lástima. Hão^&#42;1^ de julgar-te segundo os teus caminhos e segundo as tuas ações’, é a pronunciação do Soberano Senhor Jeová.”

[NOTE]
====
. “Hão”, M; TLXXSyVg: “Hei”.
====

[[v26-24-15]]

^<<v26-24-15,15>>^ E continuou a vir a haver para mim a palavra de Jeová, dizendo:

[[v26-24-16]]

^<<v26-24-16,16>>^ “Filho do homem, eis que te tiro a coisa desejável aos teus olhos por meio dum golpe, e não deves bater-te no peito, nem deves chorar, nem deves derramar lágrimas.

[[v26-24-17]]

^<<v26-24-17,17>>^ Suspira sem palavras.^&#42;1^ Não deves prantear os mortos. Ata sobre ti a tua cobertura para a cabeça, e deves pôr as tuas sandálias nos teus pés. E não deves encobrir [o] bigode^&#42;2^ e não deves comer o pão dos homens.”

[NOTE]
====
. “Sem palavras.” Lit.: “Fica calado.”
. Ou “lábio superior”.
====

[[v26-24-18]]

^<<v26-24-18,18>>^ E passei a falar ao povo de manhã, e minha esposa morreu então à noitinha. Fiz, pois, de manhã assim como eu fora mandado.

[[v26-24-19]]

^<<v26-24-19,19>>^ E as pessoas me diziam: “Não nos contarás o que têm que ver conosco estas coisas que estás fazendo?”

[[v26-24-20]]

^<<v26-24-20,20>>^ Então eu lhes disse: “Veio a haver para mim a própria palavra de Jeová, dizendo:

[[v26-24-21]]

^<<v26-24-21,21>>^ ‘Dize à casa de Israel: “Assim disse o Soberano Senhor Jeová: ‘Eis que estou profanando o meu santuário, o orgulho da vossa força, a coisa desejável aos vossos olhos e o objeto da compaixão da vossa alma, e os vossos filhos e as vossas filhas que deixastes atrás — à espada é que cairão.

[[v26-24-22]]

^<<v26-24-22,22>>^ E tereis de fazer assim como eu fiz. Não encobrireis os bigodes^&#42;1^ e não comereis o pão dos homens.

[NOTE]
====
. Ou “lábios superiores”.
====

[[v26-24-23]]

^<<v26-24-23,23>>^ E a vossa cobertura para a cabeça estará nas vossas cabeças e as vossas sandálias estarão nos vossos pés. Não vos batereis no peito, nem chorareis, e tereis de apodrecer nos vossos erros, e realmente gemereis um pelo outro.

[[v26-24-24]]

^<<v26-24-24,24>>^ E Ezequiel tornou-se para vós um portento. Fareis segundo tudo o que ele fez. Quando vier, então tereis de saber que eu sou o Soberano Senhor Jeová.’”’”

[[v26-24-25]]

^<<v26-24-25,25>>^ “E quanto a ti, ó filho do homem, não será no dia em que eu tirar deles o seu baluarte, o belo objeto de sua exultação, a coisa desejável aos seus olhos e o anseio da sua alma, seus filhos e suas filhas, que

[[v26-24-26]]

^<<v26-24-26,26>>^ nesse dia virá a ti o fugitivo para fazer os ouvidos ouvir?

[[v26-24-27]]

^<<v26-24-27,27>>^ Nesse dia se abrirá a tua boca para com o fugitivo, e falarás e não mais ficarás mudo; e hás de tornar-te para eles um portento, e terão de saber que eu sou Jeová.”

'''

xref:026-ezequiel/026-ezequiel-023.adoc#v26-23-0[&#60; Capítulo Anterior] | <<v26-24-0,Topo>> | xref:026-ezequiel/026-ezequiel-025.adoc#v26-25-0[Próximo Capítulo &#62;]