include::./index.adoc[]

[[v26-8-0]]
=== Ezequiel, 8
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v26-8-1]]

^<<v26-8-1,1>>^ E sucedeu, no sexto ano, no sexto [mês], no quinto dia do mês, que eu estava sentado na minha casa e os anciãos de Judá estavam sentados na minha frente, quando ali caiu sobre mim a mão do Soberano Senhor Jeová.

[[v26-8-2]]

^<<v26-8-2,2>>^ E comecei a ver, e eis uma semelhança tal como o aspecto do fogo; da aparência dos seus quadris para baixo havia fogo e dos seus quadris para cima havia algo do aspecto dum resplendor, como o brilho de electro.^&#42;1^

[NOTE]
====
. Veja 1:4 n.: “electro”.
====

[[v26-8-3]]

^<<v26-8-3,3>>^ Ele estendeu então a representação duma mão e pegou-me por um cacho de cabelo da minha cabeça, e um espírito^&#42;1^ carregou-me entre a terra e os céus, e levou-me a Jerusalém, nas visões de Deus, à entrada do portão interno que dá para o norte, onde está a morada do símbolo de ciúme que incita ao ciúme.

[NOTE]
====
. “Um espírito.” Hebr.: rú·ahh; gr.: pneú·ma; lat.: spí·ri·tus. Veja Gên 1:2 n.: “ativa”.
====

[[v26-8-4]]

^<<v26-8-4,4>>^ E eis que estava ali a glória do Deus^&#42;1^ de Israel, igual à aparência que eu tinha visto no vale plano.

[NOTE]
====
. “Deus de.” Hebr.: ’Elohéh, pl.
====

[[v26-8-5]]

^<<v26-8-5,5>>^ E ele passou a dizer-me: “Filho do homem, por favor, levanta teus olhos na direção do norte.” De modo que levantei meus olhos na direção do norte, e eis que havia do lado do norte do portão do altar este símbolo^&#42;1^ de ciúme^&#42;2^ na entrada!

[NOTE]
====
. “Havia . . . do portão do altar este símbolo [hebr.: sé·mel, “imagem”]”, M; mediante uma correção do M, em harmonia com LXXSy: “portão do lado do nascente . . .”; mediante uma ligeira mudança dos sinais vocálicos no M: “havia . . . do portão o altar deste símbolo”.
. “Este . . . ciúme.” Hebr.: haq·qin·’áh haz·zéh. Veja Êx 34:14 n.
====

[[v26-8-6]]

^<<v26-8-6,6>>^ E ele prosseguiu, dizendo-me: “Filho do homem, estás vendo que grandes coisas detestáveis estão fazendo, as coisas que a casa de Israel está fazendo aqui [para eu] ficar longe do meu santuário? E ainda verás mais grandes coisas detestáveis.”

[[v26-8-7]]

^<<v26-8-7,7>>^ Conseqüentemente, ele me levou à entrada do pátio e comecei a ver, e eis um buraco na parede!

[[v26-8-8]]

^<<v26-8-8,8>>^ Ele me disse então: “Filho do homem, por favor, cava através da parede.” E eu fui cavando através da parede, e eis que havia uma entrada!

[[v26-8-9]]

^<<v26-8-9,9>>^ E ele me disse mais: “Entra e vê as más coisas detestáveis que estão fazendo ali.”

[[v26-8-10]]

^<<v26-8-10,10>>^ De modo que entrei e comecei a ver, e eis que havia toda representação de coisas rastejantes e de animais repugnantes, e todos os ídolos sórdidos da casa de Israel, esculpidos na parede em todo o derredor.

[[v26-8-11]]

^<<v26-8-11,11>>^ E setenta homens^&#42;1^ dos idosos da casa de Israel, com Jaazanias,^&#42;2^ filho de Safã, de pé entre eles, estavam parados diante deles, cada um com o seu incensário na mão, e ascendia o perfume da nuvem de incenso.

[NOTE]
====
. “Homens dos.” Hebr.: ’ish.
. “Com Jaazanias.” Hebr.: weYa·’azan·yá·hu, significando “Jeová Dá Ouvido”.
====

[[v26-8-12]]

^<<v26-8-12,12>>^ E ele passou a dizer-me: “Viste, ó filho do homem, o que os idosos da casa de Israel estão fazendo na escuridão, cada um nos quartos internos da sua peça de exibição? Pois estão dizendo: ‘Jeová não nos vê.^&#42;1^ Jeová deixou o país.’”^&#42;2^

[NOTE]
====
. Ou: “Não há Jeová que nos veja.”
. Ou “a terra”. Hebr.: ha·’á·rets.
====

[[v26-8-13]]

^<<v26-8-13,13>>^ E ele continuou a dizer-me: “Ainda verás mais grandes coisas detestáveis que estão fazendo.”

[[v26-8-14]]

^<<v26-8-14,14>>^ Ele me levou então à entrada do portão da casa de Jeová que dá para o norte, e eis que havia ali mulheres sentadas, chorando o [deus] Tamuz!^&#42;1^

[NOTE]
====
. “O [deus] Tamuz.” Hebr.: hat·Tam·múz; gr.: ton Tham·moúz; lat.: A·dó·ni·dem, “Adônis”.
====

[[v26-8-15]]

^<<v26-8-15,15>>^ E ele me disse mais: “Viste [isso], ó filho do homem? Ainda verás mais grandes coisas detestáveis, piores do que estas.”

[[v26-8-16]]

^<<v26-8-16,16>>^ Levou-me, pois, ao pátio interno da casa de Jeová, e eis que à entrada do templo de Jeová, entre o pórtico e o altar, havia cerca de vinte e cinco homens^&#42;1^ com as suas costas viradas para o templo^&#42;2^ de Jeová e suas faces viradas para o leste, e eles se curvaram para o leste, para o sol!

[NOTE]
====
. “Homens.” Hebr.: ’ish.
. Veja 41:1 n.: “templo”.
====

[[v26-8-17]]

^<<v26-8-17,17>>^ E ele prosseguiu, dizendo-me: “Viste [isso], ó filho do homem? É coisa tão trivial para a casa de Judá fazer as coisas detestáveis que fizeram aqui, que eles tenham de encher o país^&#42;1^ de violência e que me devam ofender de novo, e eis que estendem o rebento^&#42;2^ ao meu nariz?^&#42;3^

[NOTE]
====
. Ou “a terra”. Hebr.: ha·’á·rets.
. Ou “o ramo (galhinho)”. Hebr.: haz·zemoh·ráh; sem dúvida, usado na adoração idólatra. Talvez representasse o órgão masculino humano.
. “Meu nariz”, no texto original hebr.; M: “seu nariz”. Esta é uma das Dezoito Emendas feitas pelos soferins para evitar uma referência aparentemente depreciativa a Jeová. Veja Ap. 2B.
====

[[v26-8-18]]

^<<v26-8-18,18>>^ E eu mesmo também agirei em furor. Meu olho não terá dó, nem terei compaixão. E certamente clamarão aos meus ouvidos em alta voz, mas eu não os ouvirei.”

'''

xref:026-ezequiel/026-ezequiel-007.adoc#v26-7-0[&#60; Capítulo Anterior] | <<v26-8-0,Topo>> | xref:026-ezequiel/026-ezequiel-009.adoc#v26-9-0[Próximo Capítulo &#62;]