include::./index.adoc[]

[[v26-32-0]]
=== Ezequiel, 32
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v26-32-1]]

^<<v26-32-1,1>>^ E aconteceu mais, no décimo segundo ano, no décimo segundo mês, no primeiro [dia] do mês, que veio a haver para mim a palavra de Jeová, dizendo:

[[v26-32-2]]

^<<v26-32-2,2>>^ “Filho do homem, levanta uma endecha concernente a Faraó, rei do Egito, e tens de dizer-lhe: ‘Foste silenciado como leão novo jubado das nações.
“‘E tu te assemelhavas ao monstro marinho nos mares, e espadanavas nos teus rios,^&#42;1^ e turvavas as águas com os teus pés, e sujavas os seus rios.’

[NOTE]
====
. Possivelmente: “durante os teus resfôlegos”; ou: “pelas tuas narinas”, mediante uma ligeira correção.
====

[[v26-32-3]]

^<<v26-32-3,3>>^ “Assim disse o Soberano Senhor Jeová: ‘Vou também estender sobre ti a minha rede por meio duma congregação de muitos povos, e eles^&#42;1^ certamente te trarão na minha rede de arrasto.

[NOTE]
====
. “Eles”, MSyVg; LXXVgc: “eu”.
====

[[v26-32-4]]

^<<v26-32-4,4>>^ E terei de abandonar-te em terra. Arremessar-te-ei sobre a superfície do campo. E sobre ti vou fazer residir todas as criaturas voadoras dos céus, e contigo fartarei as feras de toda a terra.

[[v26-32-5]]

^<<v26-32-5,5>>^ E vou pôr tua carne sobre os montes e encher os vales com o teu refugo.^&#42;1^

[NOTE]
====
. “Refugo”, M; LXX: “sangue”; Sy: “gusanos”; Vg: “sangue corrompido”.
====

[[v26-32-6]]

^<<v26-32-6,6>>^ E vou fazer [a] terra beber a tua matéria supurante, do teu sangue, sobre os montes; e os próprios regos se encherão de ti.’

[[v26-32-7]]

^<<v26-32-7,7>>^ “‘E quando fores extinguido, cobrirei [os] céus e enegrecerei as suas estrelas. Quanto ao sol, cobri-lo-ei com nuvens, e [a] própria lua não dará a sua luz.

[[v26-32-8]]

^<<v26-32-8,8>>^ Todos os luzeiros de luz nos céus — eu os enegrecerei por tua causa e vou pôr escuridão sobre a tua terra’, é a pronunciação do Soberano Senhor Jeová.

[[v26-32-9]]

^<<v26-32-9,9>>^ “‘E eu vou ofender o coração de muitos povos, quando eu levar de ti os cativos^&#42;1^ entre as nações, a terras que não conheceste.

[NOTE]
====
. “Grupo de cativos”, LXX; MSy: “quebrantamento [ou: partes quebradas]”.
====

[[v26-32-10]]

^<<v26-32-10,10>>^ E hei de fazer muitos povos ficar espantados a teu respeito e seus próprios reis arrepiar-se-ão de horror por tua causa, quando eu brandir a minha espada nas suas faces, e terão de tremer a todo instante, cada um pela sua própria alma, no dia da tua queda.’

[[v26-32-11]]

^<<v26-32-11,11>>^ “Pois assim disse o Soberano Senhor Jeová: ‘A própria espada do rei de Babilônia virá sobre ti.

[[v26-32-12]]

^<<v26-32-12,12>>^ Farei a tua massa de gente cair pelas próprias espadas dos poderosos, todos eles tiranos das nações; e eles assolarão realmente o orgulho do Egito, e toda a sua massa de gente terá de ser aniquilada.

[[v26-32-13]]

^<<v26-32-13,13>>^ E eu vou destruir todos os seus animais domésticos ao longo de muitas águas, e o pé do homem terreno não mais as turvará, nem as sujarão os cascos do animal doméstico.’

[[v26-32-14]]

^<<v26-32-14,14>>^ “‘Naquele tempo farei que se clareiem as suas águas e farei os seus rios correr como óleo’, é a pronunciação do Soberano Senhor Jeová.

[[v26-32-15]]

^<<v26-32-15,15>>^ “‘Quando eu fizer da terra do Egito um baldio desolado e a terra estiver destituída de sua plenitude, quando eu golpear nela todos os habitantes, então terão de saber que eu sou Jeová.

[[v26-32-16]]

^<<v26-32-16,16>>^ “‘Esta é uma endecha e as pessoas certamente a entoarão. Até mesmo as filhas das nações a entoarão; a respeito do Egito e a respeito de toda a sua massa de gente a entoarão’, é a pronunciação do Soberano Senhor Jeová.”

[[v26-32-17]]

^<<v26-32-17,17>>^ E aconteceu mais, no décimo segundo ano,^&#42;1^ no décimo quinto [dia] do mês, que veio a haver para mim a palavra de Jeová, dizendo:

[NOTE]
====
. LXX acrescenta: “no primeiro mês”; MTSyVg omitem isso.
====

[[v26-32-18]]

^<<v26-32-18,18>>^ “Filho do homem, lamenta a massa de gente do Egito e faze-a descer, a ela e as filhas de nações majestosas, à terra lá embaixo, com os que descem ao poço.

[[v26-32-19]]

^<<v26-32-19,19>>^ “‘Em comparação com quem és mais agradável? Desce, e tens de ser deitado com os incircuncisos!’

[[v26-32-20]]

^<<v26-32-20,20>>^ “‘Cairão no meio dos mortos à espada. [À] espada foi ela entregue. Arrastai-a [para longe], a ela e a todas as suas massas de gente.

[[v26-32-21]]

^<<v26-32-21,21>>^ “‘Os principais homens dos poderosos falarão do meio do Seol até mesmo a ele, com os seus ajudantes. Eles certamente descerão; terão de deitar-se como os incircuncisos, mortos à espada.

[[v26-32-22]]

^<<v26-32-22,22>>^ É ali que estão a Assíria e toda a sua congregação. Suas sepulturas estão em volta dele. Todos eles foram mortos, caindo à espada.

[[v26-32-23]]

^<<v26-32-23,23>>^ Porque as suas sepulturas foram postas nas partes mais recônditas dum poço, e sua congregação vem a estar em volta do seu sepulcro, todos eles mortos, caídos à espada, porque tinham causado o terror na terra dos viventes.

[[v26-32-24]]

^<<v26-32-24,24>>^ “‘Ali estão Elão e toda a sua massa de gente em volta do seu sepulcro, todos eles mortos, caídos à espada, que desceram incircuncisos à terra lá embaixo, os que causaram seu terror na terra dos viventes; e levarão a sua humilhação com os que descem ao poço.

[[v26-32-25]]

^<<v26-32-25,25>>^ No meio dos mortos puseram para ela uma cama entre toda a sua massa de gente. Suas sepulturas estão em volta dela. Todos eles são incircuncisos, mortos à espada, porque se causou o seu terror na terra dos viventes; e levarão a sua humilhação com os que descem ao poço. Foi^&#42;1^ colocado no meio dos que foram mortos.

[NOTE]
====
. “Foi”, M; em TSyVg: “Foram”.
====

[[v26-32-26]]

^<<v26-32-26,26>>^ “‘Ali estão Meseque, Tubal e toda a sua massa de gente. Suas sepulturas estão em volta dele. Todos eles são incircuncisos, traspassados pela espada, porque causaram seu terror na terra dos viventes.

[[v26-32-27]]

^<<v26-32-27,27>>^ E não se deitarão com os poderosos, caindo dentre os incircuncisos, que desceram ao Seol com as suas armas de guerra? E colocarão as suas espadas debaixo das suas cabeças, e seu erro virá a estar sobre os seus ossos, porque [os] poderosos foram um terror na terra dos viventes.

[[v26-32-28]]

^<<v26-32-28,28>>^ E no que se refere a ti,^&#42;1^ serás quebrado no meio da terra dos incircuncisos e deitar-te-ás com os mortos à espada.

[NOTE]
====
. “Ti”, hebr. masc. sing.
====

[[v26-32-29]]

^<<v26-32-29,29>>^ “‘Ali estão Edom, seus reis e todos os seus maiorais, os quais, na sua potência, foram postos com os mortos à espada; eles é que se deitarão com os próprios incircuncisos e com os que descem ao poço.

[[v26-32-30]]

^<<v26-32-30,30>>^ “‘Ali estão os caudilhos do norte, todos eles, e todos os sidônios, que desceram envergonhados junto com os que foram mortos, na sua terribilidade, por causa da sua potência. E deitar-se-ão incircuncisos com os que foram mortos à espada e levarão a sua humilhação com os que descem ao poço.

[[v26-32-31]]

^<<v26-32-31,31>>^ “‘Estes são os que Faraó verá e ele certamente será consolado quanto a toda a sua massa de gente. Faraó e toda a sua força militar serão pessoas mortas à espada’, é a pronunciação do Soberano Senhor Jeová.

[[v26-32-32]]

^<<v26-32-32,32>>^ “‘Pois ele causou^&#42;1^ o seu terror^&#42;2^ na terra dos viventes e terá de ser deitado no meio dos incircuncisos, com os que foram mortos à espada, sim, Faraó e toda a sua massa de gente’, é a pronunciação do Soberano Senhor Jeová.”

[NOTE]
====
. “Ele causou”, mediante uma ligeira correção em harmonia com “seu”; MLXXSyVg: “eu causei”.
. “Seu terror”, MLXXSy; MmargemVg: “meu terror”.
====

'''

xref:026-ezequiel/026-ezequiel-031.adoc#v26-31-0[&#60; Capítulo Anterior] | <<v26-32-0,Topo>> | xref:026-ezequiel/026-ezequiel-033.adoc#v26-33-0[Próximo Capítulo &#62;]