include::./index.adoc[]

[[v26-12-0]]
=== Ezequiel, 12
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v26-12-1]]

^<<v26-12-1,1>>^ E continuou a vir a haver para mim a palavra de Jeová, dizendo:

[[v26-12-2]]

^<<v26-12-2,2>>^ “Filho do homem, estás morando no meio duma casa rebelde, sendo que eles têm olhos para ver, mas realmente não vêem, e têm ouvidos para ouvir, mas realmente não ouvem, pois são uma casa rebelde.

[[v26-12-3]]

^<<v26-12-3,3>>^ Quanto a ti, ó filho do homem, apronta para ti bagagem para o exílio e exila-te de dia, perante os seus olhos, e tens de exilar-te do teu lugar para outro lugar perante os seus olhos. Talvez vejam, embora^&#42;1^ sejam uma casa rebelde.

[NOTE]
====
. Ou “vejam que são”.
====

[[v26-12-4]]

^<<v26-12-4,4>>^ E tens de tirar a tua bagagem como bagagem para o exílio, de dia, perante os seus olhos, e tu mesmo sairás à noitinha perante os seus olhos, como os que estão sendo levados de saída ao exílio.

[[v26-12-5]]

^<<v26-12-5,5>>^ “Perante os seus olhos, cava através da parede, e por ali tens de carregar [as coisas] para fora.

[[v26-12-6]]

^<<v26-12-6,6>>^ Farás o carregamento no próprio ombro, diante dos seus olhos. Na escuridão é que carregarás [as coisas] para fora. Encobrirás a tua própria face para que não vejas a terra, porque eu te fiz um portento para a casa de Israel.”

[[v26-12-7]]

^<<v26-12-7,7>>^ E passei a fazer exatamente assim como se me mandara. Carreguei minha bagagem para fora, como a bagagem para o exílio, de dia; e à noitinha cavei à mão através da parede. Fiz o carregamento para fora na escuridão. Fiz o carregamento no meu ombro, perante os seus olhos.

[[v26-12-8]]

^<<v26-12-8,8>>^ E continuou a vir a haver para mim a palavra de Jeová, de manhã, dizendo:

[[v26-12-9]]

^<<v26-12-9,9>>^ “Filho do homem, não te disseram os da casa de Israel, a casa rebelde: ‘Que estás fazendo?’

[[v26-12-10]]

^<<v26-12-10,10>>^ Dize-lhes: ‘Assim disse o Soberano Senhor Jeová: “No que se refere ao maioral, há esta pronúncia contra Jerusalém e contra toda a casa de Israel no meio deles.”’

[[v26-12-11]]

^<<v26-12-11,11>>^ “Dize: ‘Sou um portento para vós. Assim como eu fiz, assim se fará a eles. Irão para o exílio, para o cativeiro.

[[v26-12-12]]

^<<v26-12-12,12>>^ E no que se refere ao maioral no seu meio, carregará [as coisas] no ombro, no escuro, e sairá; cavarão através da parede, a fim de por ali levarem [as coisas] para fora. Ele encobrirá a sua face para não ver a terra com os seus próprios olhos.’

[[v26-12-13]]

^<<v26-12-13,13>>^ E eu hei de estender a minha rede sobre ele e terá de ser apanhado na minha rede de caça; e vou levá-lo a Babilônia,^&#42;1^ à terra dos caldeus, mas não a verá; e ali morrerá.

[NOTE]
====
. “Babilônia”, LXXVg; MTSy: “Babel”.
====

[[v26-12-14]]

^<<v26-12-14,14>>^ E a todos os que estiverem em volta dele para ajudar e a todas as suas tropas militares eu espalharei a todo vento;^&#42;1^ e desembainharei uma espada atrás deles.

[NOTE]
====
. “Vento.” Hebr.: rúahh; gr.: á·ne·mon; lat.: vén·tum.
====

[[v26-12-15]]

^<<v26-12-15,15>>^ E terão de saber que eu sou Jeová, quando eu os dispersar entre as nações e realmente os espalhar entre as terras.

[[v26-12-16]]

^<<v26-12-16,16>>^ E vou deixar sobrar deles poucos homens^&#42;1^ da espada, da fome e da peste, a fim de que narrem todas as suas coisas detestáveis entre as nações nas quais terão de entrar; e terão de saber que eu sou Jeová.”

[NOTE]
====
. “Homens.” Hebr.: ’an·shéh.
====

[[v26-12-17]]

^<<v26-12-17,17>>^ E continuou a vir a haver para mim a palavra de Jeová, dizendo:

[[v26-12-18]]

^<<v26-12-18,18>>^ “Filho do homem, com tremor deves comer o teu pão, e com agitação e com ansiedade deves beber a tua água.

[[v26-12-19]]

^<<v26-12-19,19>>^ E tens de dizer ao povo da terra:^&#42;1^ ‘Assim disse o Soberano Senhor Jeová aos habitantes de Jerusalém sobre o solo^&#42;2^ de Israel: “Comerão o seu pão com ansiedade e beberão a sua água com horror, a fim de que a sua terra seja desolada de sua plenitude por causa da violência de todos os que moram nela.

[NOTE]
====
. Veja 7:27 n.
. Ou “a respeito do solo”. Hebr.: ’el-’adh·máth; TLXXVg: “sobre a terra”.
====

[[v26-12-20]]

^<<v26-12-20,20>>^ E as próprias cidades habitadas serão devastadas e a própria terra tornar-se-á meramente um baldio desolado; e tereis de saber que eu sou Jeová.”’”

[[v26-12-21]]

^<<v26-12-21,21>>^ E veio a haver para mim adicionalmente a palavra de Jeová, dizendo:

[[v26-12-22]]

^<<v26-12-22,22>>^ “Filho do homem, que expressão proverbial é essa que tendes no solo de Israel, dizendo: ‘Os dias se prolongam e pereceu toda visão’?

[[v26-12-23]]

^<<v26-12-23,23>>^ Portanto, dize-lhes: ‘Assim disse o Soberano Senhor Jeová: “Certamente farei cessar tal expressão proverbial e não mais a dirão como provérbio em Israel.”’ Mas fala-lhes: ‘Chegaram-se os dias e o assunto de toda visão.’

[[v26-12-24]]

^<<v26-12-24,24>>^ Pois não se mostrará mais haver qualquer visão fútil, nem adivinhação dúplice^&#42;1^ no meio da casa de Israel.

[NOTE]
====
. Ou “suave”.
====

[[v26-12-25]]

^<<v26-12-25,25>>^ ‘“Pois eu mesmo, Jeová, falarei a palavra que eu falar, e será cumprida. Não haverá mais postergação, pois nos vossos dias, ó casa rebelde, falarei uma palavra e certamente a cumprirei”, é a pronunciação do Soberano Senhor Jeová.’”

[[v26-12-26]]

^<<v26-12-26,26>>^ E continuou a vir a haver para mim a palavra de Jeová, dizendo:

[[v26-12-27]]

^<<v26-12-27,27>>^ “Filho do homem, eis que os da casa de Israel estão dizendo: ‘A visão que ele observou é para muitos dias [no futuro] e ele profetiza sobre tempos longínquos.’

[[v26-12-28]]

^<<v26-12-28,28>>^ Por isso, dize-lhes: ‘Assim disse o Soberano Senhor Jeová: “‘Não haverá mais postergação quanto a quaisquer palavras minhas. A palavra que eu falar, esta é que se cumprirá’, é a pronunciação do Soberano Senhor Jeová.”’”

'''

xref:026-ezequiel/026-ezequiel-011.adoc#v26-11-0[&#60; Capítulo Anterior] | <<v26-12-0,Topo>> | xref:026-ezequiel/026-ezequiel-013.adoc#v26-13-0[Próximo Capítulo &#62;]