include::./index.adoc[]

[[v26-5-0]]
=== Ezequiel, 5
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v26-5-1]]

^<<v26-5-1,1>>^ “E quanto a ti, ó filho do homem, toma para ti uma espada afiada. Tu a tomarás para ti como navalha de barbeiro e tens de fazê-la passar sobre a tua cabeça e sobre a tua barba, e tens de tomar para ti uma balança para pesar e repartir [os cabelos]^&#42;1^ em porções.

[NOTE]
====
. Lit.: “reparti-los”.
====

[[v26-5-2]]

^<<v26-5-2,2>>^ Uma terça parte queimarás no próprio fogo, no meio da cidade, assim que se tiverem completado os dias do sítio. E tens de tomar outra terça parte. Tu [a] golpearás com a espada em seu redor, e a [última] terça parte espalharás ao vento,^&#42;1^ e desembainharei a própria espada atrás deles.

[NOTE]
====
. “Ao vento.” Hebr.: la·rú·ahh; gr.: pneú·ma·ti; lat.: vén·tum. Veja Gên 1:2 n.: “ativa”.
====

[[v26-5-3]]

^<<v26-5-3,3>>^ “E terás de tirar dali poucos em número e terás de embrulhá-los nas abas da tua [veste].

[[v26-5-4]]

^<<v26-5-4,4>>^ E tomarás outros deles e terás de lançá-los no meio do fogo, e incinerá-los no fogo. De um^&#42;1^ sairá um fogo a toda a casa de Israel.

[NOTE]
====
. “Um”, hebr. masc.
====

[[v26-5-5]]

^<<v26-5-5,5>>^ “Assim disse o Soberano Senhor Jeová: ‘Esta é Jerusalém. Coloquei-a no meio das nações, com terras ao seu redor.

[[v26-5-6]]

^<<v26-5-6,6>>^ E ela passou a comportar-se rebeldemente contra as minhas decisões judiciais, em iniqüidade maior do que as nações, e contra os meus estatutos, mais do que as terras ao seu redor, pois rejeitaram as minhas decisões judiciais, e quanto aos meus estatutos, não andaram neles.’

[[v26-5-7]]

^<<v26-5-7,7>>^ “Portanto, assim disse o Soberano Senhor Jeová: ‘Visto que fostes mais tumultuosos^&#42;1^ do que as nações ao vosso redor, não andastes nos meus estatutos e não executastes as minhas decisões judiciais — mas, porventura não agistes segundo as decisões judiciais das nações ao vosso redor? —

[NOTE]
====
. “Rebeldes”, mediante uma correção.
====

[[v26-5-8]]

^<<v26-5-8,8>>^ portanto, assim disse o Soberano Senhor Jeová: “Eis que sou contra ti,^&#42;1^ [ó cidade,] sim, eu, e vou executar no teu meio decisões judiciais aos olhos das nações.

[NOTE]
====
. “Ti”, hebr. fem. sing., referindo-se à cidade de Jerusalém, hebr. fem. sing.
====

[[v26-5-9]]

^<<v26-5-9,9>>^ E vou fazer em ti o que não fiz e como não mais farei, por causa de todas as tuas coisas detestáveis.

[[v26-5-10]]

^<<v26-5-10,10>>^ “‘“Portanto, os próprios pais comerão os filhos no teu meio, e os próprios filhos comerão seus pais, e eu vou executar em ti atos de julgamento e espalhar tudo o que restar de ti a todo vento.”’^&#42;1^

[NOTE]
====
. “Vento.” Hebr.: rú·ahh; gr.: á·ne·mon; lat.: vén·tum. Isto é, todas as direções em que o vento sopra.
====

[[v26-5-11]]

^<<v26-5-11,11>>^ “‘Portanto, assim como vivo’, é a pronunciação do Soberano Senhor Jeová, ‘seguramente, visto que foi meu santuário que aviltaste com todas as tuas coisas repugnantes e com todas as tuas coisas detestáveis, também sou Eu quem [te] vai diminuir, e meu olho não terá dó, nem tampouco terei compaixão.

[[v26-5-12]]

^<<v26-5-12,12>>^ Um terço de ti — de peste morrerão e de fome chegarão ao seu fim no teu meio. E outro terço — à espada cairão ao teu redor. E o [último] terço é que espalharei a todo vento, e é uma espada que desembainharei atrás deles.

[[v26-5-13]]

^<<v26-5-13,13>>^ E a minha ira certamente acabará e vou aplacar neles o meu furor e consolar-me; e terão de saber que eu, Jeová, é que falei na minha insistência em devoção exclusiva, quando eu levar a cabo meu furor contra eles.

[[v26-5-14]]

^<<v26-5-14,14>>^ “‘E farei de ti^&#42;1^ um lugar devastado e um vitupério entre as nações ao redor de ti diante dos olhos de todo transeunte.

[NOTE]
====
. Veja v. 8 n.
====

[[v26-5-15]]

^<<v26-5-15,15>>^ E terás de tornar-te vitupério e objeto de palavras injuriosas, exemplo de advertência e coisa horrorosa para as nações ao redor de ti, quando eu fizer em ti atos de julgamento em ira, e em furor, e em furiosas repreensões. Eu, Jeová, é que falei.

[[v26-5-16]]

^<<v26-5-16,16>>^ “‘Quando eu enviar contra eles as flechas malignas da fome, que terão de mostrar ser para a ruína, [flechas] que enviarei para vos arruinar, aumentarei sobre vós até mesmo a fome e vou quebrar os vossos varais nos quais se penduram os pães de forma anular.^&#42;1^

[NOTE]
====
. Lit.: “varal de pão”.
====

[[v26-5-17]]

^<<v26-5-17,17>>^ E vou enviar sobre vós fome e feras nocivas, e elas terão de privar-te de filhos, e até mesmo a peste e o sangue passarão pelo teu meio, e trarei sobre ti uma espada. Eu, Jeová, é que falei.’”

'''

xref:026-ezequiel/026-ezequiel-004.adoc#v26-4-0[&#60; Capítulo Anterior] | <<v26-5-0,Topo>> | xref:026-ezequiel/026-ezequiel-006.adoc#v26-6-0[Próximo Capítulo &#62;]