include::./index.adoc[]

[[v26-18-0]]
=== Ezequiel, 18
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v26-18-1]]

^<<v26-18-1,1>>^ E continuou a vir a haver para mim a palavra de Jeová, dizendo:

[[v26-18-2]]

^<<v26-18-2,2>>^ “Que significa para vós que proferis esta expressão proverbial sobre o solo de Israel, dizendo: ‘Os pais é que comem as uvas verdes, mas são os dentes dos filhos que ficam embotados’?^&#42;1^

[NOTE]
====
. Lit.: “obtusos (rombudos)”.
====

[[v26-18-3]]

^<<v26-18-3,3>>^ “‘Assim como vivo’, é a pronunciação do Soberano Senhor Jeová, ‘não continuará mais a caber a vós proferir esta expressão proverbial em Israel.

[[v26-18-4]]

^<<v26-18-4,4>>^ Eis que todas as almas^&#42;1^ — a mim me pertencem. Como a alma do pai, assim também a alma do filho — a mim me pertencem. A alma que pecar — ela é que morrerá.^&#42;2^

[NOTE]
====
. “As almas.” Hebr.: han·nefa·shóhth; gr.: psy·khaí; lat.: á·ni·mae. Veja Ap. 4A.
. Ou: “A alma que pecar é a que morrerá.” Hebr.: han·né·fesh ha·hho·té’th hi’ tha·múth.
====

[[v26-18-5]]

^<<v26-18-5,5>>^ “‘E no que se refere ao homem,^&#42;1^ se ele veio a ser justo e tem praticado o juízo e a justiça;

[NOTE]
====
. Lit.: “E um homem.” Hebr.: we’ísh.
====

[[v26-18-6]]

^<<v26-18-6,6>>^ se não comeu nos montes e não elevou seus olhos para os ídolos sórdidos da casa de Israel, e não aviltou a esposa de seu companheiro, e não se chegou a uma mulher na sua impureza;

[[v26-18-7]]

^<<v26-18-7,7>>^ e se não maltratou a nenhum homem; se restituiu o penhor tomado pela dívida; se não arrebatou nada em roubo; se deu o seu próprio pão ao faminto e cobriu com roupa ao que estava nu;

[[v26-18-8]]

^<<v26-18-8,8>>^ se não deu nada em troca de juros e não tomou usura; se retirou sua mão da injustiça; se praticou a verdadeira justiça entre homem e homem;

[[v26-18-9]]

^<<v26-18-9,9>>^ se tem andado nos meus estatutos e tem guardado as minhas decisões judiciais para praticar a verdade, ele é justo. Ele positivamente continuará a viver’, é a pronunciação do Soberano Senhor Jeová.

[[v26-18-10]]

^<<v26-18-10,10>>^ “‘E [se] alguém se tornou pai de um filho que é salteador, derramador de sangue, que fez coisas semelhantes a uma destas;^&#42;1^

[NOTE]
====
. Lit.: “fez o irmão de uma destas coisas”, M; T: “fez a seu irmão uma destas coisas”; SyVg: “fez (qualquer) uma destas coisas”.
====

[[v26-18-11]]

^<<v26-18-11,11>>^ (mas ele mesmo não fez nenhuma destas coisas;) se também comeu sobre os montes e aviltou a esposa de seu companheiro;

[[v26-18-12]]

^<<v26-18-12,12>>^ se maltratou o atribulado e pobre; se arrebatou coisas em roubo, não restituindo a coisa tomada em penhor; e se elevou seus olhos para os ídolos sórdidos, fez uma coisa detestável.

[[v26-18-13]]

^<<v26-18-13,13>>^ Deu em troca de usura e cobrou juros, e ele positivamente não continuará a viver. Fez todas estas coisas detestáveis. Positivamente será morto. Sobre ele é que virá a haver seu próprio sangue.

[[v26-18-14]]

^<<v26-18-14,14>>^ “‘E eis que alguém se tornou pai de um filho que continua vendo todos os pecados de seu pai, que este tem praticado, e ele [os] vê^&#42;1^ e não faz coisas semelhantes a eles.

[NOTE]
====
. “Vê”, MT; LXXVg: “teme”.
====

[[v26-18-15]]

^<<v26-18-15,15>>^ Não comeu sobre os montes e não elevou seus olhos para os ídolos sórdidos da casa de Israel; não aviltou a esposa de seu companheiro;

[[v26-18-16]]

^<<v26-18-16,16>>^ e não maltratou homem algum,^&#42;1^ nem se apoderou de alguma coisa penhorada, e não tomou nada em roubo; deu o seu próprio pão ao faminto e cobriu com roupa ao que estava nu;

[NOTE]
====
. “E . . . homem algum.” Hebr.: we’ísh lo’.
====

[[v26-18-17]]

^<<v26-18-17,17>>^ retirou sua mão do atribulado;^&#42;1^ não tomou nem usura nem juros; cumpriu as minhas decisões judiciais; andou nos meus estatutos; ele mesmo não morrerá por causa do erro de seu pai. Positivamente continuará a viver.

[NOTE]
====
. “Atribulado”, M; LXX: “injustiça”.
====

[[v26-18-18]]

^<<v26-18-18,18>>^ Quanto a seu pai, por ter praticado flagrante defraudação, arrebatando em roubo algo de um irmão e fazendo o que não é bom no meio dos seus povos, eis que então terá de morrer pelo seu erro.

[[v26-18-19]]

^<<v26-18-19,19>>^ “‘E certamente direis: “Por que é que o filho não levará nenhuma [culpa] pelo erro do pai?” Ora, quanto ao filho, praticou o juízo e a justiça, guardou todos os meus estatutos e continua a cumpri-los. Ele positivamente continuará a viver.

[[v26-18-20]]

^<<v26-18-20,20>>^ A alma que pecar — ela é que morrerá.^&#42;1^ O próprio filho não levará nenhuma [culpa] pelo erro do pai e o próprio pai não levará nenhuma [culpa] pelo erro do filho. A própria justiça do justo virá a estar sobre ele mesmo, e a própria iniqüidade do iníquo virá a estar sobre ele mesmo.

[NOTE]
====
. Veja v. 4 n.: “morrerá”.
====

[[v26-18-21]]

^<<v26-18-21,21>>^ “‘Ora, quanto ao iníquo, se ele recuar de todos os seus pecados que praticou e realmente guardar todos os meus estatutos e praticar o juízo e a justiça, ele positivamente continuará a viver. Não morrerá.

[[v26-18-22]]

^<<v26-18-22,22>>^ Todas as suas transgressões que praticou — não serão lembradas contra ele. Continuará a viver por causa da justiça que praticou.’

[[v26-18-23]]

^<<v26-18-23,23>>^ “‘Acaso me agrado de algum modo na morte do iníquo’, é a pronunciação do Soberano Senhor Jeová, ‘[e] não em que ele recue dos seus caminhos e realmente continue a viver?’

[[v26-18-24]]

^<<v26-18-24,24>>^ “‘Ora, quando o justo recuar da sua justiça e realmente fizer injustiça; se estiver fazendo segundo todas as coisas detestáveis que o iníquo tem feito e estiver vivendo, não será lembrado nenhum dos seus atos justos que praticou. Por sua infidelidade que praticou e por seu pecado com que pecou, por estes é que morrerá.

[[v26-18-25]]

^<<v26-18-25,25>>^ “‘E certamente direis: “O caminho de Jeová^&#42;1^ não é acertado.” Ouvi, por favor, ó casa de Israel. Não é acertado o meu próprio caminho? Não são os vossos caminhos que não são acertados?

[NOTE]
====
. Uma das 134 mudanças de YHWH para ’Adho·naí feitas pelos escribas. Veja Ap. 1B.
====

[[v26-18-26]]

^<<v26-18-26,26>>^ “‘Quando o justo recuar de sua justiça e realmente fizer injustiça e morrer por causa de tais [atos], morrerá pela sua injustiça que fez.

[[v26-18-27]]

^<<v26-18-27,27>>^ “‘E quando o iníquo recuar de sua iniqüidade que praticou e passar a praticar o juízo e a justiça, é ele quem preservará viva a sua própria alma.

[[v26-18-28]]

^<<v26-18-28,28>>^ Quando vir^&#42;1^ todas as suas transgressões que praticou e recuar delas, positivamente continuará a viver. Não morrerá.

[NOTE]
====
. “Vir”, MTSyVg; LXX omite isso.
====

[[v26-18-29]]

^<<v26-18-29,29>>^ “‘E a casa de Israel certamente dirá: “O caminho de Jeová^&#42;1^ não é acertado.” Quanto aos meus caminhos, acaso não são acertados, ó casa de Israel? Não são os vossos caminhos que não são acertados?’

[NOTE]
====
. Veja v. 25 n.
====

[[v26-18-30]]

^<<v26-18-30,30>>^ “‘Portanto, eu vos julgarei, a cada um segundo os seus caminhos, ó casa de Israel’, é a pronunciação do Soberano Senhor Jeová. ‘Retornai, sim, fazei um recuo de todas as vossas transgressões, e que nada se mostre para vós pedra de tropeço que induz ao erro.

[[v26-18-31]]

^<<v26-18-31,31>>^ Lançai de vós todas as vossas transgressões com as quais transgredistes e fazei para vós um novo coração e um novo espírito, pois, por que devíeis morrer, ó casa de Israel?’

[[v26-18-32]]

^<<v26-18-32,32>>^ “‘Pois, não me agrado na morte de quem morre’, é a pronunciação do Soberano Senhor Jeová. ‘Portanto, fazei um recuo e continuai a viver.’”

'''

xref:026-ezequiel/026-ezequiel-017.adoc#v26-17-0[&#60; Capítulo Anterior] | <<v26-18-0,Topo>> | xref:026-ezequiel/026-ezequiel-019.adoc#v26-19-0[Próximo Capítulo &#62;]