include::./index.adoc[]

[[v26-19-0]]
=== Ezequiel, 19
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v26-19-1]]

^<<v26-19-1,1>>^ “E no que se refere a ti, levanta uma endecha a respeito dos maiorais de Israel,

[[v26-19-2]]

^<<v26-19-2,2>>^ e tens de dizer: ‘Que foi a tua mãe? Uma leoa entre leões.^&#42;1^ Deitou-se entre leões novos jubados. Criou os seus filhotes.

[NOTE]
====
. “Leões.” Hebr.: ’ara·yóhth, leões africanos.
====

[[v26-19-3]]

^<<v26-19-3,3>>^ “‘E aos poucos ela criou um dos seus filhotes. Um leão novo jubado é o que se tornou, e ele começou a aprender a dilacerar a presa. Devorou até mesmo o homem terreno.^&#42;1^

[NOTE]
====
. “Homem terreno.” Hebr.: ’a·dhám.
====

[[v26-19-4]]

^<<v26-19-4,4>>^ E as nações ouviam [falar] dele. Foi apanhado na cova delas, e passaram a levá-lo por meio de ganchos^&#42;1^ à terra do Egito.

[NOTE]
====
. Ou “espinhos”; enfiados através das bochechas ou do nariz de animais, bem como de cativos, para conduzi-los por meio duma corda.
====

[[v26-19-5]]

^<<v26-19-5,5>>^ “‘Quando ela chegou a ver que tinha esperado [e] que sua esperança tinha perecido, então tomou outro dos seus filhotes. Constituiu-o em leão novo jubado.

[[v26-19-6]]

^<<v26-19-6,6>>^ E ele começou a andar no meio dos leões. Um leão novo jubado é o que se tornou. E aos poucos aprendeu a dilacerar a presa. Devorou até mesmo o homem terreno.

[[v26-19-7]]

^<<v26-19-7,7>>^ E ele chegou a conhecer as suas torres de habitação^&#42;1^ e devastou até mesmo as cidades deles, de modo que a terra ficou desolada e ele a encheu com o som do seu bramido.

[NOTE]
====
. “Torres de habitação; palácios”, pela substituição de uma letra; M: “viúvas”.
====

[[v26-19-8]]

^<<v26-19-8,8>>^ E as nações em redor, dos distritos jurisdicionais, começaram a armar^&#42;1^ contra ele e a estender sobre ele a sua rede. Ele foi apanhado na sua cova.

[NOTE]
====
. Possivelmente “acampar”, mediante uma ligeira mudança no M.
====

[[v26-19-9]]

^<<v26-19-9,9>>^ Por fim puseram-no na jaula, por meio de ganchos,^&#42;1^ e levaram-no ao rei de Babilônia.^&#42;2^ Foram levá-lo por meio de redes de caça, para que não se ouvisse mais a sua voz nos montes de Israel.

[NOTE]
====
. Veja v. 4 n.
. “Babilônia”, LXXVg; MTSy: “Babel”.
====

[[v26-19-10]]

^<<v26-19-10,10>>^ “‘Tua mãe era como videira no teu sangue,^&#42;1^ plantada junto a águas. Frutífera e cheia de ramos se tornou ela por causa da água abundante.

[NOTE]
====
. “No teu sangue”, MSyVg; dois mss. hebr.: “do teu vinhedo”; T: “ela costumava parecer-se a”.
====

[[v26-19-11]]

^<<v26-19-11,11>>^ E vieram a ser para ela bastões fortes, destinados a ser cetros de governantes. E sua altura atingiu gradualmente a altura dos ramos, e chegou a ser visível por causa da sua altura, por causa da abundância da sua folhagem.

[[v26-19-12]]

^<<v26-19-12,12>>^ Mas ela foi finalmente desarraigada em furor. Foi lançada por terra, e houve um vento oriental que lhe secou o fruto. Seu bastão forte foi arrancado e secou-se. O próprio fogo o consumiu.

[[v26-19-13]]

^<<v26-19-13,13>>^ E agora está plantada no ermo, numa terra árida e sedenta.

[[v26-19-14]]

^<<v26-19-14,14>>^ E passou a sair fogo do [seu] bastão. Devorou os próprios sarmentos dela, o próprio fruto dela, e não se mostrou haver nela nenhum bastão forte, nenhum cetro para governar.
“‘Esta é uma endecha, e tornar-se-á uma endecha.’”

'''

xref:026-ezequiel/026-ezequiel-018.adoc#v26-18-0[&#60; Capítulo Anterior] | <<v26-19-0,Topo>> | xref:026-ezequiel/026-ezequiel-020.adoc#v26-20-0[Próximo Capítulo &#62;]