include::./index.adoc[]

[[v26-39-0]]
=== Ezequiel, 39
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v26-39-1]]

^<<v26-39-1,1>>^ “E no que se refere a ti, ó filho do homem, profetiza contra Gogue, e tens de dizer: ‘Assim disse o Soberano Senhor Jeová: “Eis que sou contra ti, ó Gogue, maioral-chefe de Meseque^&#42;1^ e Tubal.

[NOTE]
====
. Ou “maioral de Rôs, Meseque”. Vg: “principal príncipe de Meseque”; T: “o cabeça, [o] grande de Meseque”; LXX: “governante de Rôs, Meseque”; Sy: “líder e cabeça de Meseque”.
====

[[v26-39-2]]

^<<v26-39-2,2>>^ E eu vou fazer que te voltes e vou conduzir-te e fazer-te subir das partes mais remotas do norte, e vou fazer-te chegar aos montes de Israel.

[[v26-39-3]]

^<<v26-39-3,3>>^ E vou tirar de golpe o teu arco da tua mão esquerda e farei as tuas flechas cair da tua mão direita.

[[v26-39-4]]

^<<v26-39-4,4>>^ Cairás nos montes de Israel, tu e todas as tuas tropas e os povos que estarão contigo. Entregar-te-ei por alimento às aves de rapina, às aves de toda espécie de asa e aos animais selváticos do campo.”’

[[v26-39-5]]

^<<v26-39-5,5>>^ “‘Cairás na superfície do campo, pois eu mesmo falei’, é a pronunciação do Soberano Senhor Jeová.

[[v26-39-6]]

^<<v26-39-6,6>>^ “‘E vou enviar fogo sobre Magogue^&#42;1^ e sobre os que habitam nas ilhas em segurança; e as pessoas terão de saber que eu sou Jeová.

[NOTE]
====
. “Magogue”, MTSyVg; LXX: “Gogue”. Veja 38:2 n.: “Magogue”.
====

[[v26-39-7]]

^<<v26-39-7,7>>^ E tornarei conhecido meu santo nome no meio do meu povo de Israel e não mais deixarei meu santo nome ser profanado; e as nações terão de saber que eu sou Jeová, o Santo em Israel.’^&#42;1^

[NOTE]
====
. Ou “que eu, Jeová, sou santo em Israel”. Hebr.: ki-’aní Yehwáh qa·dhóhsh beYis·ra·’él.
====

[[v26-39-8]]

^<<v26-39-8,8>>^ “‘Eis que tem de vir e tem de acontecer’, é a pronunciação do Soberano Senhor Jeová. ‘Este é o dia de que falei.

[[v26-39-9]]

^<<v26-39-9,9>>^ E os habitantes das cidades de Israel certamente sairão, e farão uma queima, e farão fogo com o armamento, e com os broquéis, e com os escudos grandes — com os arcos, e com as flechas, e com os bordões, e com as lanças; e terão de fazer fogo com eles por sete anos.

[[v26-39-10]]

^<<v26-39-10,10>>^ Não trarão lenha do campo, nem ajuntarão gravetos das florestas, pois acenderão fogo com o armamento.’
“‘E hão de despojar os que os tinham despojado e saquear os que os tinham saqueado’, é a pronunciação do Soberano Senhor Jeová.

[[v26-39-11]]

^<<v26-39-11,11>>^ “‘E naquele dia terá de acontecer que darei ali a Gogue um lugar,^&#42;1^ uma sepultura em Israel, o vale dos que passam, ao leste do mar, e ele^&#42;2^ impedirá os que passarem. E ali terão de enterrar a Gogue e toda a sua massa de gente, e certamente [o] chamarão de Vale da Massa de Gente de Gogue.^&#42;3^

[NOTE]
====
. “Um lugar de nome (renome)”, LXXVg.
. “Ele”, hebr. fem., referindo-se ao “vale”, hebr. fem.
. Ou “Vale de Hamom-Gogue”.
====

[[v26-39-12]]

^<<v26-39-12,12>>^ E os da casa de Israel terão de enterrá-los com o fim de purificar a terra, por sete meses.

[[v26-39-13]]

^<<v26-39-13,13>>^ E todo o povo da terra terá de fazer o sepultamento e isso há de tornar-se para eles uma questão de fama no dia em que eu me glorificar’, é a pronunciação do Soberano Senhor Jeová.

[[v26-39-14]]

^<<v26-39-14,14>>^ “‘E serão separados homens^&#42;1^ para [serviço] contínuo, que passarão pela terra para enterrar, com os que passam,^&#42;2^ aqueles que tiverem sobrado na superfície da terra, a fim de purificá-la. Continuarão a fazer a busca até o fim de sete meses.

[NOTE]
====
. “E . . . homens.” Hebr.: we’an·shéh, forma pl. de ’ish.
. “Com os que passam”, MT; LXXSy omitem isso.
====

[[v26-39-15]]

^<<v26-39-15,15>>^ E os que estiverem passando pela terra terão de atravessá-la, e se alguém realmente vir o osso de um homem,^&#42;1^ então terá de erigir ao seu lado um marco, até que seja sepultado pelos enterradores no Vale da Massa de Gente de Gogue.^&#42;2^

[NOTE]
====
. “Homem.” Hebr.: ’a·dhám.
. Veja v. 11 n.: “Gogue”.
====

[[v26-39-16]]

^<<v26-39-16,16>>^ E o nome da cidade também será Hamoná.^&#42;1^ E terão de purificar a terra.’

[NOTE]
====
. Significando “Massa de Gente”. Hebr.: Hamoh·náh, forma fem. de Ha·móhn nos vv. 11, 15.
====

[[v26-39-17]]

^<<v26-39-17,17>>^ “E no que se refere a ti, ó filho do homem, assim disse o Soberano Senhor Jeová: ‘Dize às aves de toda espécie de asa e a todos os animais selváticos do campo: “Reuni-vos e vinde. Ajuntai-vos em volta do meu sacrifício que sacrifico para vós, um grande sacrifício nos montes de Israel. E haveis de comer carne e beber sangue.

[[v26-39-18]]

^<<v26-39-18,18>>^ Comereis a carne de poderosos e bebereis o sangue dos maiorais da terra, de carneiros, de cordeirinhos e de cabritos, de novilhos, todos eles [animais] cevados de Basã.

[[v26-39-19]]

^<<v26-39-19,19>>^ E haveis de comer gordura até à saciedade e beber sangue até à embriaguez, do meu sacrifício que vou sacrificar para vós.”’

[[v26-39-20]]

^<<v26-39-20,20>>^ “‘E tereis de fartar-vos, à minha mesa, de cavalos e de condutores de carros,^&#42;1^ de poderosos e de toda sorte de guerreiros’,^&#42;2^ é a pronunciação do Soberano Senhor Jeová.

[NOTE]
====
. Ou “cavaleiros”, em harmonia com LXXSyVg; M: “carro de guerra”.
. Lit.: “todo homem [hebr.: ’ish] de guerra”.
====

[[v26-39-21]]

^<<v26-39-21,21>>^ “‘E eu vou pôr a minha glória entre as nações; e todas as nações terão de ver meu julgamento que executei e minha mão que coloquei entre eles.

[[v26-39-22]]

^<<v26-39-22,22>>^ E os da casa de Israel terão de saber que eu sou Jeová, seu Deus, daquele dia em diante.

[[v26-39-23]]

^<<v26-39-23,23>>^ E as nações terão de saber que foi por causa de seu erro que eles, os da casa de Israel, foram ao exílio, pelo fato de que se comportaram de modo infiel para comigo, de modo que escondi deles a minha face e os entreguei na mão dos seus adversários, e eles foram caindo, todos eles, à espada.

[[v26-39-24]]

^<<v26-39-24,24>>^ Fiz com eles segundo a sua impureza e segundo as suas transgressões, e continuei a esconder deles a minha face.’

[[v26-39-25]]

^<<v26-39-25,25>>^ “Portanto, assim disse o Soberano Senhor Jeová: ‘É agora que trarei de volta os cativos de Jacó e realmente terei misericórdia de toda a casa de Israel; e vou mostrar devoção exclusiva ao meu santo nome.

[[v26-39-26]]

^<<v26-39-26,26>>^ E terão levado a sua humilhação e toda a sua infidelidade com que agiram para comigo, ao morarem sobre o seu solo em segurança, sem que alguém [os] faça tremer.

[[v26-39-27]]

^<<v26-39-27,27>>^ Quando eu os trouxer de volta dentre os povos e realmente os reunir das terras dos seus inimigos, também vou santificar-me^&#42;1^ entre eles perante os olhos de muitas nações.’

[NOTE]
====
. Ou “também vou ter-me por sagrado (tratar-me como santo)”. Hebr.: weniq·dásh·ti; gr.: ha·gi·a·sthé·so·mai; lat.: sanc·ti·fi·cá·tus.
====

[[v26-39-28]]

^<<v26-39-28,28>>^ “‘E terão de saber que eu sou Jeová, seu Deus, quando eu os enviar ao exílio nas nações e realmente os reunir sobre o seu solo, de modo que lá não deixarei restar mais nenhum deles.

[[v26-39-29]]

^<<v26-39-29,29>>^ E não mais esconderei deles a minha face, porque vou derramar meu espírito sobre a casa de Israel’, é a pronunciação do Soberano Senhor Jeová.”

'''

xref:026-ezequiel/026-ezequiel-038.adoc#v26-38-0[&#60; Capítulo Anterior] | <<v26-39-0,Topo>> | xref:026-ezequiel/026-ezequiel-040.adoc#v26-40-0[Próximo Capítulo &#62;]