include::./index.adoc[]

[[v26-29-0]]
=== Ezequiel, 29
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v26-29-1]]

^<<v26-29-1,1>>^ No décimo ano, no décimo [mês], no décimo segundo [dia] do mês, veio a haver para mim a palavra de Jeová, dizendo:

[[v26-29-2]]

^<<v26-29-2,2>>^ “Filho do homem, fixa a tua face contra Faraó, rei do Egito, e profetiza contra ele e contra o Egito na sua inteireza.

[[v26-29-3]]

^<<v26-29-3,3>>^ Fala, e tens de dizer: ‘Assim disse o Soberano Senhor Jeová: “Eis que sou contra ti, ó Faraó, rei do Egito, o grande monstro marinho jazendo no meio dos seus canais do Nilo, que disse: ‘Meu rio Nilo é meu, e eu é que [o] fiz para mim mesmo.’

[[v26-29-4]]

^<<v26-29-4,4>>^ E eu vou pôr ganchos^&#42;1^ nas tuas queixadas e vou fazer que os peixes dos teus canais do Nilo se apeguem às tuas escamas. E vou fazer-te subir do meio dos teus canais do Nilo, bem como todos os peixes dos teus canais do Nilo que se apegam às tuas próprias escamas.

[NOTE]
====
. Ou “espinhos”; enfiados através das bochechas ou do nariz de animais, bem como de cativos, para conduzi-los por meio duma corda.
====

[[v26-29-5]]

^<<v26-29-5,5>>^ E vou abandonar-te ao ermo, a ti e a todos os peixes dos teus canais do Nilo. Cairás sobre a superfície do campo. Não serás ajuntado nem reunido. Às feras da terra e às criaturas voadoras dos céus vou entregar-te como alimento.

[[v26-29-6]]

^<<v26-29-6,6>>^ E todos os habitantes do Egito terão de saber que eu sou Jeová, visto que eles,^&#42;1^ como apoio, mostraram ser um caniço para a casa de Israel.

[NOTE]
====
. “Eles”, MT; LXXSyVg: “tu”.
====

[[v26-29-7]]

^<<v26-29-7,7>>^ Quando te pegaram pela mão,^&#42;1^ foste esmagado, e causaste uma rachadura em todo o seu ombro.^&#42;2^ E quando se apoiaram em ti, foste quebrado, e fizeste todos os seus quadris vacilar.”^&#42;3^

[NOTE]
====
. “Pela mão”, MmargemVg e muitos mss. hebr.; M: “pela tua mão”; LXXSy: “pela(s) sua(s) mão(s)”.
. “Ombro”, MVg; Sy: “mãos”.
. “Vacilar”, Sy; M: “parar”.
====

[[v26-29-8]]

^<<v26-29-8,8>>^ “‘Portanto, assim disse o Soberano Senhor Jeová: “Eis que faço chegar sobre ti uma espada, e vou decepar de ti o homem terreno e o animal doméstico.

[[v26-29-9]]

^<<v26-29-9,9>>^ E a terra do Egito terá de tornar-se um baldio desolado e um lugar devastado; e terão de saber que eu sou Jeová, pela razão de que ele disse: ‘A mim me pertence o rio Nilo e eu mesmo [o] fiz.’

[[v26-29-10]]

^<<v26-29-10,10>>^ Por isso, eis que sou contra ti e contra os teus canais do Nilo, e vou fazer da terra do Egito lugares devastados, secura, baldio desolado, desde Migdol até Siene,^&#42;1^ e até o termo da Etiópia.^&#42;2^

[NOTE]
====
. Ou “Assuã”. Hebr.: Sewe·néh.
. “Etiópia”, Vg; LXX: “dos etíopes”; MTSy: “Cus”.
====

[[v26-29-11]]

^<<v26-29-11,11>>^ Não passará por ela pé de homem terreno, nem passará por ela pé de animal doméstico, e não será habitada por quarenta anos.

[[v26-29-12]]

^<<v26-29-12,12>>^ E eu vou fazer da terra do Egito um baldio desolado no meio de terras desoladas; e suas próprias cidades se tornarão um baldio desolado no próprio meio de cidades devastadas, por quarenta anos; e eu vou espalhar os egípcios entre as nações e dispersá-los entre as terras.”

[[v26-29-13]]

^<<v26-29-13,13>>^ “‘Pois assim disse o Soberano Senhor Jeová: “Ao fim dos quarenta anos reunirei os egípcios dentre os povos entre os quais terão sido espalhados,

[[v26-29-14]]

^<<v26-29-14,14>>^ e eu vou trazer de volta o grupo de cativos dos egípcios; e vou trazê-los de volta à terra de Patros, à terra da sua origem, e ali terão de tornar-se um reino humilde.

[[v26-29-15]]

^<<v26-29-15,15>>^ Tornar-se-á mais humilde do que os [outros] reinos e não mais se erguerá sobre as [outras] nações, e vou fazê-los tão poucos para que não tenham as [outras] nações em sujeição.

[[v26-29-16]]

^<<v26-29-16,16>>^ E não mais mostrará ser a confiança da casa de Israel, fazendo lembrar o erro por se virarem para eles. E terão de saber que eu sou o Soberano Senhor Jeová.”’”

[[v26-29-17]]

^<<v26-29-17,17>>^ Sucedeu, então, no vigésimo sétimo ano, no primeiro [mês], no primeiro [dia] do mês, que veio a haver para mim a palavra de Jeová, dizendo:

[[v26-29-18]]

^<<v26-29-18,18>>^ “Filho do homem, o próprio Nabucodorosor, rei de Babilônia,^&#42;1^ fez a sua força militar realizar um grande serviço contra Tiro. Toda cabeça ficou calva e todo ombro ficou esfolado. Mas, quanto ao salário, não se mostrou haver nenhum para ele e para a sua força militar, provindo de Tiro, pelo serviço que realizou contra ela.

[NOTE]
====
. “Babilônia”, LXXVg; MTSy: “Babel”.
====

[[v26-29-19]]

^<<v26-29-19,19>>^ “Portanto, assim disse o Soberano Senhor Jeová: ‘Eis que dou a Nabucodorosor, rei de Babilônia, a terra do Egito, e ele terá de carregar com a sua opulência e fazer dela um grande despojo, e fazer dela um grande saque; e terá de tornar-se o salário para a sua força militar.’

[[v26-29-20]]

^<<v26-29-20,20>>^ “‘Como remuneração pelo serviço que prestou contra ela dei-lhe a terra do Egito, visto que agiram por mim’, é a pronunciação do Soberano Senhor Jeová.

[[v26-29-21]]

^<<v26-29-21,21>>^ “Naquele dia farei brotar um chifre para a casa de Israel, e dar-te-ei a oportunidade de abrir a boca no meio deles; e terão de saber que eu sou Jeová.”

'''

xref:026-ezequiel/026-ezequiel-028.adoc#v26-28-0[&#60; Capítulo Anterior] | <<v26-29-0,Topo>> | xref:026-ezequiel/026-ezequiel-030.adoc#v26-30-0[Próximo Capítulo &#62;]