include::./index.adoc[]

[[v26-17-0]]
=== Ezequiel, 17
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v26-17-1]]

^<<v26-17-1,1>>^ E continuou a vir a haver para mim a palavra de Jeová, dizendo:

[[v26-17-2]]

^<<v26-17-2,2>>^ “Filho do homem, propõe um enigma e compõe uma expressão proverbial com respeito à casa de Israel.

[[v26-17-3]]

^<<v26-17-3,3>>^ E tens de dizer: ‘Assim disse o Soberano Senhor Jeová: “A grande águia, com grandes asas, de compridas guias, cheia de penas, de cores variadas, chegou ao Líbano e passou a tomar a copa do cedro.

[[v26-17-4]]

^<<v26-17-4,4>>^ Arrancou mesmo o topo dos seus noveleiros e foi levá-lo à terra de Canaã; colocou-o na cidade dos negociantes.

[[v26-17-5]]

^<<v26-17-5,5>>^ Além disso, tomou da semente da terra e a pôs num campo de sementeira. Qual salgueiro junto a vastas águas, qual salgueiro a colocou.

[[v26-17-6]]

^<<v26-17-6,6>>^ E começou a brotar e tornou-se aos poucos uma frondosa videira de pouca altura, inclinada para virar as suas folhas para dentro; e, quanto às suas raízes, vieram a existir gradualmente debaixo dela. E por fim se tornou uma videira, e produziu sarmentos, e lançou ramos.

[[v26-17-7]]

^<<v26-17-7,7>>^ “‘“E veio a haver outra grande águia, com grandes asas e com grandes penas, e eis que esta mesma videira estendeu avidamente as suas raízes para ela. E estendeu a sua folhagem para ela, a fim de que a regasse, longe dos canteiros em que estava plantada.

[[v26-17-8]]

^<<v26-17-8,8>>^ Já estava transplantada num bom campo, junto a vastas águas, para produzir ramos e dar fruto, para se tornar uma videira majestosa.”’

[[v26-17-9]]

^<<v26-17-9,9>>^ “Dize: ‘Assim disse o Soberano Senhor Jeová: “Será bem sucedida? Não arrancará alguém as suas próprias raízes e fará que até o fruto dela seja escamoso? E [não] terão de secar-se todos os seus renovos recém-arrancados? Secar-se-á. Nem por um grande braço nem por um povo numeroso terá de ser levantada das suas raízes.

[[v26-17-10]]

^<<v26-17-10,10>>^ E eis que, embora transplantada, será bem sucedida? Não se secará completamente, assim como quando tocada pelo vento oriental? Secar-se-á no canteiro do seu renovo.”’”

[[v26-17-11]]

^<<v26-17-11,11>>^ E continuou a vir a haver para mim a palavra de Jeová, dizendo:

[[v26-17-12]]

^<<v26-17-12,12>>^ “Por favor, dize à casa rebelde: ‘Não sabeis o que estas coisas significam?’ Dize: ‘Eis que o rei de Babilônia^&#42;1^ chegou a Jerusalém e passou a tomar seu rei e seus príncipes e a trazê-los a si em Babilônia.

[NOTE]
====
. “Babilônia”, LXXVg; MTSy: “Babel”.
====

[[v26-17-13]]

^<<v26-17-13,13>>^ Além disso, tomou um da descendência real e concluiu^&#42;1^ com ele um pacto, e o introduziu num juramento; e levou embora os principais homens do país,

[NOTE]
====
. Lit.: “cortou”.
====

[[v26-17-14]]

^<<v26-17-14,14>>^ a fim de que o reino fosse rebaixado, incapaz de se erguer, para que ficasse^&#42;1^ de pé por guardar o seu pacto.

[NOTE]
====
. “Ficasse”, M, hebr. fem. sing., referindo-se ao “reino”, hebr. fem.; a margem de um ms. hebr. tem isso no masc. sing., referindo-se ao rei.
====

[[v26-17-15]]

^<<v26-17-15,15>>^ Mas este finalmente se rebelou contra ele, enviando seus mensageiros ao Egito, [para que] lhe desse cavalos e um povo numeroso. Será bem sucedido? Escapará aquele que está fazendo tais coisas e que violou um pacto? E escapará ele realmente?’

[[v26-17-16]]

^<<v26-17-16,16>>^ “‘“Assim como vivo”, é a pronunciação do Soberano Senhor Jeová, “no lugar do rei que constituiu rei àquele que desprezou seu juramento e que violou seu pacto, junto a ele, no meio de Babilônia, é que morrerá.

[[v26-17-17]]

^<<v26-17-17,17>>^ E Faraó não o fará eficiente na guerra por meio duma grande força militar e por meio duma congregação numerosa, levantando um aterro de sítio e construindo um muro de sítio, a fim de decepar muitas almas.

[[v26-17-18]]

^<<v26-17-18,18>>^ E ele desprezou o juramento, violando o pacto, e eis que dera a sua mão, e assim mesmo fez todas estas coisas. Não escapará.”’

[[v26-17-19]]

^<<v26-17-19,19>>^ “‘Portanto, assim disse o Soberano Senhor Jeová: “Assim como vivo, seguramente, meu juramento que ele desprezou e meu pacto que ele violou — isso é que vou trazer sobre a sua cabeça.

[[v26-17-20]]

^<<v26-17-20,20>>^ E vou estender sobre ele a minha rede e certamente será apanhado na minha rede de caça; e vou levá-lo a Babilônia e pôr-me ali em julgamento com ele quanto à sua infidelidade com que agiu contra mim.

[[v26-17-21]]

^<<v26-17-21,21>>^ E no que se refere a todos os seus fugitivos, em todas as suas tropas, cairão à espada, e os remanescentes serão dispersados para todo vento.^&#42;1^ E tereis de saber que eu, Jeová, é que falei [isso].”’

[NOTE]
====
. “Para todo vento”, representando direção. Hebr.: lekhol-rú·ahh; gr.: eis pán·ta á·ne·mon; lat.: in ó·mnem vén·tum. Veja Gên 1:2 n.: “ativa”.
====

[[v26-17-22]]

^<<v26-17-22,22>>^ “‘Assim disse o Soberano Senhor Jeová: “Eu mesmo também tomarei e porei parte da copa altaneira do cedro; do topo dos seus rebentos arrancarei um tenro, e eu mesmo vou transplantá-lo para um monte alto e elevado.

[[v26-17-23]]

^<<v26-17-23,23>>^ Transplantá-lo-ei para o monte da elevação de Israel, e certamente brotarão ramos nele, e produzirá fruto, e tornar-se-á um cedro majestoso. E debaixo dele hão de residir realmente todas as aves de toda asa; residirão à sombra da sua folhagem.

[[v26-17-24]]

^<<v26-17-24,24>>^ E todas as árvores do campo terão de saber que eu mesmo, Jeová, rebaixei a árvore alta, pus no alto a árvore baixa, sequei a árvore ainda viçosa e fiz florescer a árvore seca. Eu, Jeová, é que falei e fiz [isso].”’”

'''

xref:026-ezequiel/026-ezequiel-016.adoc#v26-16-0[&#60; Capítulo Anterior] | <<v26-17-0,Topo>> | xref:026-ezequiel/026-ezequiel-018.adoc#v26-18-0[Próximo Capítulo &#62;]