include::./index.adoc[]

[[v26-22-0]]
=== Ezequiel, 22
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v26-22-1]]

^<<v26-22-1,1>>^ E continuou a vir a haver para mim a palavra de Jeová, dizendo:

[[v26-22-2]]

^<<v26-22-2,2>>^ “E quanto a ti, ó filho do homem, julgarás, julgarás a cidade culpada de sangue^&#42;1^ e certamente a farás saber todas as suas coisas detestáveis?

[NOTE]
====
. Lit.: “a cidade dos sangues”.
====

[[v26-22-3]]

^<<v26-22-3,3>>^ E terás de dizer: ‘Assim disse o Soberano Senhor Jeová: “Ó cidade que derrama sangue no seu meio até chegar o seu tempo, e que fez ídolos sórdidos no seu meio para se tornar impura,

[[v26-22-4]]

^<<v26-22-4,4>>^ pelo teu sangue que derramaste tornaste-te culpada, e pelos teus ídolos sórdidos que fizeste tornaste-te impura. E fazes chegar perto os teus dias e chegarás aos teus anos. Por isso terei de fazer-te objeto de vitupério para as nações e troça para todas as terras.

[[v26-22-5]]

^<<v26-22-5,5>>^ As [terras] próximas e as longe de ti farão troça de ti, ó tu que és impura de nome, que abundas em confusão.

[[v26-22-6]]

^<<v26-22-6,6>>^ Eis que vieram a estar em ti os maiorais de Israel, cada um [entregue] ao seu braço para derramar sangue.

[[v26-22-7]]

^<<v26-22-7,7>>^ Pai e mãe eles trataram com desprezo em ti. Para com o residente forasteiro agiram com defraudação no teu meio. O menino órfão de pai e a viúva eles maltrataram em ti.”’”

[[v26-22-8]]

^<<v26-22-8,8>>^ “‘Desprezaste os meus lugares santos e profanaste os meus sábados.

[[v26-22-9]]

^<<v26-22-9,9>>^ Mostrou-se haver em ti flagrantes caluniadores,^&#42;1^ com o fim de derramar sangue; e em ti comeram sobre os montes. No teu meio praticaram conduta desenfreada.

[NOTE]
====
. Lit.: “homens de calúnia”. Hebr.: ’an·shéh ra·khíl.
====

[[v26-22-10]]

^<<v26-22-10,10>>^ Expuseram^&#42;1^ em ti a nudez do pai; humilharam em ti a mulher que estava impura na [sua] menstruação.

[NOTE]
====
. Lit.: “Expôs-se [ou: ele expôs].”
====

[[v26-22-11]]

^<<v26-22-11,11>>^ E o homem fez uma coisa detestável com a esposa de seu companheiro, e ele aviltou a sua própria nora com conduta desenfreada; e o homem humilhou em ti a sua irmã, filha de seu próprio pai.

[[v26-22-12]]

^<<v26-22-12,12>>^ Em ti aceitaram suborno com o fim de derramar sangue. Cobraste juros e usura, e continuas a lucrar violentamente dos teus companheiros com defraudação, e a mim me esqueceste’, é a pronunciação do Soberano Senhor Jeová.

[[v26-22-13]]

^<<v26-22-13,13>>^ “‘E eis que golpeei com a minha mão o teu lucro injusto que obtiveste, e por teus atos de derramamento de sangue^&#42;1^ que veio a haver no meio de ti.

[NOTE]
====
. Lit.: “teu sangue”, hebr. sing., mas é o sujeito dum verbo no pl.
====

[[v26-22-14]]

^<<v26-22-14,14>>^ Acaso o suportará o teu coração ou te fortalecerão as tuas mãos nos dias em que eu tomar ação contra ti? Eu mesmo, Jeová, falei e vou tomar ação.

[[v26-22-15]]

^<<v26-22-15,15>>^ E vou espalhar-te entre as nações e dispersar-te entre as terras, e vou destruir^&#42;1^ a tua impureza^&#42;2^ dentro de ti.

[NOTE]
====
. Lit.: “acabar com”.
. “Tua impureza.” Hebr.: tum·’a·thékh; gr.: a·ka·thar·sí·a. Veja 2Co 12:21 n. e Ga 5:19 n.: “impureza”.
====

[[v26-22-16]]

^<<v26-22-16,16>>^ E certamente serás profanada em ti mesma perante os olhos das nações, e terás de saber que eu sou Jeová.’”

[[v26-22-17]]

^<<v26-22-17,17>>^ E continuou a vir a haver para mim a palavra de Jeová, dizendo:

[[v26-22-18]]

^<<v26-22-18,18>>^ “Filho do homem, os da casa de Israel tornaram-se para mim como escória. Todos eles são cobre, e estanho, e ferro, e chumbo dentro de um forno de fundição. Tornaram-se muita escória, [a de] prata.

[[v26-22-19]]

^<<v26-22-19,19>>^ “Portanto, assim disse o Soberano Senhor Jeová: ‘Visto que todos vós vos tornastes como muita escória, portanto, eis que vos reúno no meio de Jerusalém.

[[v26-22-20]]

^<<v26-22-20,20>>^ Assim como se reúne prata, e cobre, e ferro, e chumbo, e estanho no meio do forno de fundição, para soprar sobre ele com fogo para que seja fundido, assim [os] reunirei na minha ira e no meu furor, e vou soprar^&#42;1^ e fazer que sejais fundidos.

[NOTE]
====
. “Soprar”, mediante uma correção; M: “depositar”, intransitivo.
====

[[v26-22-21]]

^<<v26-22-21,21>>^ E vou reunir-vos e soprar sobre vós com o fogo da minha fúria, e tereis de ser fundidos no meio dela.^&#42;1^

[NOTE]
====
. “Dela”, hebr. fem., referindo-se à cidade de Jerusalém.
====

[[v26-22-22]]

^<<v26-22-22,22>>^ Assim como se funde prata dentro de um forno de fundição, assim vós sereis fundidos no meio dela; e tereis de saber que eu mesmo, Jeová, derramei sobre vós o meu furor.’”

[[v26-22-23]]

^<<v26-22-23,23>>^ E continuou a vir a haver para mim a palavra de Jeová, dizendo:

[[v26-22-24]]

^<<v26-22-24,24>>^ “Filho do homem, dize-lhe: ‘Tu és uma terra que não se purifica, uma em que não chove no dia da verberação.

[[v26-22-25]]

^<<v26-22-25,25>>^ Há no meio dela uma conspiração dos seus profetas, qual leão que brame, dilacerando a presa. É realmente uma alma que eles devoram. Continuam a apanhar tesouro e coisas preciosas. Multiplicaram as viúvas dela no seu meio.

[[v26-22-26]]

^<<v26-22-26,26>>^ Os próprios sacerdotes dela têm feito violência à minha lei, e eles continuam a profanar meus lugares santos. Não fizeram nenhuma diferença entre a coisa santa e a comum,^&#42;1^ e nada deram a conhecer entre a coisa impura e a pura, e ocultaram os seus olhos dos meus sábados, e eu sou profanado no meio deles.

[NOTE]
====
. Ou “profana”.
====

[[v26-22-27]]

^<<v26-22-27,27>>^ Os príncipes dela no seu meio são como lobos dilacerando a presa em derramamento de sangue, destruindo almas^&#42;1^ para obter lucro injusto.

[NOTE]
====
. “Almas.” Hebr.: nefa·shóhth; lat.: á·ni·mas. Veja Ap. 4A.
====

[[v26-22-28]]

^<<v26-22-28,28>>^ E seus profetas deram uma caiadura para eles, visionando uma irrealidade e adivinhando para eles uma mentira, dizendo: “Assim disse o Soberano Senhor Jeová”, quando o próprio Jeová não tinha falado.

[[v26-22-29]]

^<<v26-22-29,29>>^ Os do próprio povo da terra executaram um plano de defraudação e arrebataram em roubo, e maltrataram o atribulado e o pobre, e defraudaram o residente forasteiro sem qualquer justiça.’

[[v26-22-30]]

^<<v26-22-30,30>>^ “‘E eu estava procurando um homem^&#42;1^ dentre eles que reparasse o muro de pedras e que se pusesse de pé na brecha perante mim, a favor da terra, para que [eu] não a arruinasse; e não achei nenhum.

[NOTE]
====
. “Um homem.” Hebr.: ’ish.
====

[[v26-22-31]]

^<<v26-22-31,31>>^ Por isso derramarei sobre eles a minha verberação. Vou exterminá-los com o fogo da minha fúria. Vou trazer seu procedimento sobre a própria cabeça deles’, é a pronunciação do Soberano Senhor Jeová.”

'''

xref:026-ezequiel/026-ezequiel-021.adoc#v26-21-0[&#60; Capítulo Anterior] | <<v26-22-0,Topo>> | xref:026-ezequiel/026-ezequiel-023.adoc#v26-23-0[Próximo Capítulo &#62;]