include::./index.adoc[]

[[v26-14-0]]
=== Ezequiel, 14
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v26-14-1]]

^<<v26-14-1,1>>^ E homens^&#42;1^ dentre os idosos de Israel passaram a chegar a mim e a sentar-se diante de mim.

[NOTE]
====
. “Homens.” Hebr.: ’ana·shím, pl. de ’ish.
====

[[v26-14-2]]

^<<v26-14-2,2>>^ Então veio a haver para mim a palavra de Jeová, dizendo:

[[v26-14-3]]

^<<v26-14-3,3>>^ “Filho do homem, no que se refere a estes homens, fizeram seus ídolos sórdidos subir ao seu coração e puseram diante das suas faces a pedra de tropeço que causa o seu erro. Acaso devia eu ser consultado por eles?

[[v26-14-4]]

^<<v26-14-4,4>>^ Portanto, fala com eles e tens de dizer-lhes: ‘Assim disse o Soberano Senhor Jeová: “Todo homem^&#42;1^ de Israel que fizer os seus ídolos sórdidos subir ao seu coração e que colocar diante da sua face a própria pedra de tropeço que causa o seu erro, e que realmente chegar ao profeta, eu, Jeová, vou deixar-me induzir a lhe responder na questão segundo a multidão de seus ídolos sórdidos,

[NOTE]
====
. “Todo homem.” Hebr.: ’ish ’ish.
====

[[v26-14-5]]

^<<v26-14-5,5>>^ com o objetivo de pegar a casa de Israel pelo coração, porque se apartaram de mim devido aos seus ídolos sórdidos — todos eles.”’

[[v26-14-6]]

^<<v26-14-6,6>>^ “Portanto, dize à casa de Israel: ‘Assim disse o Soberano Senhor Jeová: “Retornai e recuai dos vossos ídolos sórdidos, e voltai as vossas faces de todas as vossas coisas detestáveis;

[[v26-14-7]]

^<<v26-14-7,7>>^ pois absolutamente todo homem da casa de Israel ou dos residentes forasteiros que residem em Israel, que se apartar de me seguir, e que fizer os seus ídolos sórdidos subir ao seu coração, e que colocar diante da sua face a própria pedra de tropeço que causa o seu erro, e que realmente chegar ao profeta para consultar-me para si, a este eu, Jeová, me deixarei responder por mim mesmo.

[[v26-14-8]]

^<<v26-14-8,8>>^ E terei de pôr minha face contra tal homem^&#42;1^ e terei de constituí-lo em sinal e em expressões proverbiais, e terei de decepá-lo do meio do meu povo; e tereis de saber que eu sou Jeová.”’

[NOTE]
====
. “Contra tal homem.” Hebr.: ba·’ísh ha·hú’.
====

[[v26-14-9]]

^<<v26-14-9,9>>^ “‘E quanto ao profeta, caso ele for logrado e realmente falar uma palavra, fui eu, Jeová, que logrei este profeta; e vou estender contra ele a minha mão e vou aniquilá-lo do meio do meu povo Israel.

[[v26-14-10]]

^<<v26-14-10,10>>^ E eles terão de levar sobre si o seu erro. O erro do consulente mostrará ser o mesmo que o erro do profeta,

[[v26-14-11]]

^<<v26-14-11,11>>^ a fim de que os da casa de Israel não mais se percam, [deixando] de me seguir e não mais se aviltem com todas as suas transgressões. E terão de tornar-se meu povo e eu mesmo me tornarei seu Deus’,^&#42;1^ é a pronunciação do Soberano Senhor Jeová.”

[NOTE]
====
. Lit.: “para eles para Deus”. Hebr.: la·hém lE’·lo·hím.
====

[[v26-14-12]]

^<<v26-14-12,12>>^ E a palavra de Jeová continuou a vir a mim, dizendo:

[[v26-14-13]]

^<<v26-14-13,13>>^ “Filho do homem, quanto a uma terra, caso cometa pecado contra mim, agindo de modo infiel, então vou estender a minha mão contra ela e vou quebrar-lhe os varais em que se penduram os pães de forma anular,^&#42;1^ e vou enviar sobre ela a fome e decepar dela o homem terreno e o animal doméstico.”

[NOTE]
====
. Lit.: “a vara de pão”.
====

[[v26-14-14]]

^<<v26-14-14,14>>^ “‘E se tivessem vindo a estar no meio dela estes três homens:^&#42;1^ Noé, Daniel e Jó, eles mesmos, por causa da sua justiça, é que livrariam a sua alma’, é a pronunciação do Soberano Senhor Jeová.”

[NOTE]
====
. Lit.: “os homens”. Hebr.: ha·’ana·shím, pl. de ’ish.
====

[[v26-14-15]]

^<<v26-14-15,15>>^ “‘Ou, se eu fizesse passar pela terra feras nocivas e estas realmente a privassem de filhos, e ela realmente se tornasse um baldio desolado, sem que alguém passasse por ela, por causa das feras,

[[v26-14-16]]

^<<v26-14-16,16>>^ se estes três homens estivessem no meio dela, assim como vivo’, é a pronunciação do Soberano Senhor Jeová, ‘não livrariam nem a filhos nem a filhas; eles, somente eles é que seriam livrados e a própria terra se tornaria um baldio desolado’.”

[[v26-14-17]]

^<<v26-14-17,17>>^ “‘Ou, se eu trouxesse uma espada sobre aquela terra e eu realmente dissesse: “Passe uma espada pela terra”, e se eu realmente decepasse dela o homem terreno^&#42;1^ e o animal doméstico,

[NOTE]
====
. “Homem terreno.” Hebr.: ’a·dhám.
====

[[v26-14-18]]

^<<v26-14-18,18>>^ mesmo que estivessem no meio dela estes três homens, assim como vivo’, é a pronunciação do Soberano Senhor Jeová, ‘não livrariam nem a filhos nem a filhas, mas eles, somente eles seriam livrados’.”

[[v26-14-19]]

^<<v26-14-19,19>>^ “‘Ou, se eu enviasse^&#42;1^ uma peste sobre aquela terra e realmente derramasse sobre ela meu furor com sangue, para decepar dela o homem terreno e o animal doméstico,

[NOTE]
====
. Ou “soltasse”.
====

[[v26-14-20]]

^<<v26-14-20,20>>^ mesmo que estivessem no meio dela Noé, Daniel e Jó, assim como vivo’, é a pronunciação do Soberano Senhor Jeová, ‘não livrariam nem a filhos nem a filhas; eles mesmos é que livrariam a sua alma por causa da sua justiça’.”

[[v26-14-21]]

^<<v26-14-21,21>>^ “Pois assim disse o Soberano Senhor Jeová: ‘Assim [será] também quando houver os meus quatro atos prejudiciais de julgamento — a espada, e a fome, e a fera nociva, e a peste — que eu realmente enviarei sobre Jerusalém, a fim de decepar dela o homem terreno e o animal doméstico.

[[v26-14-22]]

^<<v26-14-22,22>>^ Mas, eis que certamente se deixará sobrar nela um grupo dos que escapam, os que serão levados para fora. Aqui estão os filhos e as filhas! Estão saindo até a vós, e vós tereis de ver seu caminho e suas ações. E certamente sereis consolados pela calamidade que terei trazido sobre Jerusalém, sim, por tudo o que eu tiver trazido sobre ela.’”

[[v26-14-23]]

^<<v26-14-23,23>>^ “‘E eles certamente vos consolarão ao virdes seu caminho e suas ações; e tereis de saber que não é sem causa que terei feito tudo o que terei de fazer contra^&#42;1^ ela’, é a pronunciação do Soberano Senhor Jeová.”

[NOTE]
====
. Ou “em [ela] (nela)”.
====

'''

xref:026-ezequiel/026-ezequiel-013.adoc#v26-13-0[&#60; Capítulo Anterior] | <<v26-14-0,Topo>> | xref:026-ezequiel/026-ezequiel-015.adoc#v26-15-0[Próximo Capítulo &#62;]