include::./index.adoc[]

[[v26-43-0]]
=== Ezequiel, 43
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v26-43-1]]

^<<v26-43-1,1>>^ Então me fez ir ao portão, o portão que dá para o leste.

[[v26-43-2]]

^<<v26-43-2,2>>^ E eis que vinha a glória do Deus de Israel^&#42;1^ da direção do leste, e sua voz era como a voz de vastas águas; e a própria terra brilhava por causa da sua glória.

[NOTE]
====
. “A glória do Deus de Israel.” Hebr.: kevóhdh ’Elo·héh Yis·ra·’él.
====

[[v26-43-3]]

^<<v26-43-3,3>>^ E era como a aparência da visão que tive, como a visão que tive quando vim^&#42;1^ para arruinar a cidade; e havia aparições^&#42;2^ como a aparição^&#42;3^ que vi junto ao rio Quebar, e fui lançar-me com a face [por terra].

[NOTE]
====
. “Quando vim”, M; ThVg e seis mss. hebr.: “quando veio”; T: “quando profetizei para fazer [a cidade] definhar”.
. “Havia aparições”, M; LXX: “a visão do carro, que eu vi (era)”.
. Ou “visão”.
====

[[v26-43-4]]

^<<v26-43-4,4>>^ E a própria glória de Jeová entrou na Casa pelo caminho do portão cuja frente dava para o leste.

[[v26-43-5]]

^<<v26-43-5,5>>^ E um espírito^&#42;1^ passou a levantar-me e a levar-me para dentro do pátio interno, e eis que a Casa tinha ficado cheia da glória de Jeová.^&#42;2^

[NOTE]
====
. “Um espírito.” Hebr.: rú·ahh; gr.: pneú·ma; lat.: spí·ri·tus.
. Ou “a glória de Jeová encheu a Casa”.
====

[[v26-43-6]]

^<<v26-43-6,6>>^ E comecei a ouvir alguém falar comigo de dentro da Casa, e [o] próprio homem^&#42;1^ viera a ficar de pé ao meu lado.

[NOTE]
====
. “E [o] . . . homem.” Hebr.: we’ísh.
====

[[v26-43-7]]

^<<v26-43-7,7>>^ E ele prosseguiu, dizendo-me:
“Filho do homem,^&#42;1^ [este é]^&#42;2^ o lugar do meu trono e o lugar das solas dos meus pés, onde residirei no meio dos filhos de Israel por tempo indefinido; e eles, a casa de Israel, não mais profanarão o meu santo nome, eles e seus reis, com a sua fornicação e com os cadáveres de seus reis na sua morte,^&#42;3^

[NOTE]
====
. Ou “homem terreno”. Hebr.: ’a·dhám.
. “Este é”, T; LXX: “viste”; mas M tem somente a partícula que indica o caso acusativo para a próxima palavra.
. “Na sua morte”, TTh e cerca de 20 mss. e ed. hebr.; M: “nos seus altos”; LXX: “no meio deles”.
====

[[v26-43-8]]

^<<v26-43-8,8>>^ por porem seu limiar junto ao meu limiar e sua ombreira ao lado da minha ombreira, com a parede entre mim e eles. E eles aviltaram o meu santo nome com as suas coisas detestáveis que fizeram, de modo que fui exterminá-los na minha ira.

[[v26-43-9]]

^<<v26-43-9,9>>^ Agora, removam para longe de mim a sua fornicação e os cadáveres de seus reis, e eu certamente residirei no seu meio por tempo indefinido.

[[v26-43-10]]

^<<v26-43-10,10>>^ “Quanto a ti, ó filho do homem, informa a casa de Israel a respeito da Casa, para que se sintam humilhados por causa dos seus erros, e eles terão de medir o modelo.

[[v26-43-11]]

^<<v26-43-11,11>>^ E se realmente se sentirem humilhados por causa de tudo o que fizeram, dá-lhes a conhecer e escreve perante os seus olhos a planta da Casa, e seu arranjo, e suas saídas, e suas entradas, e todas as suas plantas e todas as suas especificações, e todas as suas plantas e todas as suas leis, para que observem toda a sua planta e todas as suas especificações e realmente as executem.

[[v26-43-12]]

^<<v26-43-12,12>>^ Esta é a lei da Casa. No cume do monte, todo o seu território circundante é algo santíssimo. Eis que esta é a lei da Casa.

[[v26-43-13]]

^<<v26-43-13,13>>^ “E estas são as medidas do altar em côvados, o côvado sendo um côvado e uma largura de mão.^&#42;1^ E [seu] fundo^&#42;2^ é de um côvado. E a largura é de um côvado. E sua beirada está na sua borda ao redor, de um palmo. E esta é a base do altar.

[NOTE]
====
. Veja 40:5 n.: “mão”.
. Ou “canal de sangue”; ou: “moldura”.
====

[[v26-43-14]]

^<<v26-43-14,14>>^ E desde o fundo no chão até a [reentrância da] banda inferior circundante há dois côvados, e a largura é de um côvado. E [da reentrância] da pequena banda circundante até a [reentrância da] grande banda circundante há quatro côvados, e [sua] largura é de um côvado.

[[v26-43-15]]

^<<v26-43-15,15>>^ E a lareira do altar tem quatro côvados, e procedentes da lareira do altar e para cima há quatro chifres.

[[v26-43-16]]

^<<v26-43-16,16>>^ E a lareira do altar tem doze [côvados] de comprimento, com doze [côvados] de largura, sendo quadrada nos quatro lados.

[[v26-43-17]]

^<<v26-43-17,17>>^ E a banda circundante tem quatorze [côvados] de comprimento, com quatorze [côvados] de largura, nos seus quatro lados; e a borda que o rodeia tem meio côvado, e sua base tem um côvado em volta.
“E seus^&#42;1^ degraus estão virados para o leste.”

[NOTE]
====
. “Seus”, hebr. masc., referindo-se ao altar.
====

[[v26-43-18]]

^<<v26-43-18,18>>^ E ele passou a dizer-me: “Filho do homem, assim disse o Soberano Senhor Jeová: ‘Estes são os estatutos do altar no dia de ser feito, para se oferecerem sobre ele holocaustos e se aspergir sobre ele sangue.’

[[v26-43-19]]

^<<v26-43-19,19>>^ “‘E aos sacerdotes levíticos, que são da descendência^&#42;1^ de Zadoque, os que se chegam a mim para ministrar-me’, é a pronunciação do Soberano Senhor Jeová, ‘tens de dar um novilho, filho da manada, como oferta pelo pecado.

[NOTE]
====
. Lit.: “semente”.
====

[[v26-43-20]]

^<<v26-43-20,20>>^ E tens de tomar do seu sangue e pô-lo sobre os seus quatro chifres, e sobre os quatro cantos da banda circundante, e sobre a beira em redor, e tens de purificá-lo de pecado e fazer expiação por ele.

[[v26-43-21]]

^<<v26-43-21,21>>^ E tens de tomar o novilho, a oferta pelo pecado, e tens de queimá-lo no lugar designado da Casa, fora do santuário.

[[v26-43-22]]

^<<v26-43-22,22>>^ E no segundo dia trarás perto um bode dos caprídeos, sadio, como oferta pelo pecado; e terão de purificar o altar de pecado assim como [o] purificaram de pecado com o novilho.’

[[v26-43-23]]

^<<v26-43-23,23>>^ “‘Quando acabares a purificação de pecado, trarás perto um novilho, filho da manada, sadio, e um carneiro do rebanho, sadio.

[[v26-43-24]]

^<<v26-43-24,24>>^ E tens de fazê-lo chegar perante Jeová, e os sacerdotes têm de lançar sal sobre eles e oferecê-los como holocausto a Jeová.

[[v26-43-25]]

^<<v26-43-25,25>>^ Por sete dias ofertarás, por dia, um bode como oferta pelo pecado; e ofertarão um novilho, filho da manada, e um carneiro do rebanho, perfeitos.

[[v26-43-26]]

^<<v26-43-26,26>>^ Por sete dias farão expiação pelo altar, e terão de purificá-lo e de inaugurá-lo.^&#42;1^

[NOTE]
====
. Lit.: “encher-lhe a mão”. Veja 2Cr 13:9 n.: “poder”.
====

[[v26-43-27]]

^<<v26-43-27,27>>^ E completarão os dias. E terá de acontecer do oitavo dia em diante que os sacerdotes ofertarão sobre o altar os vossos holocaustos e os vossos sacrifícios de participação em comum; e eu certamente me agradarei de vós’, é a pronunciação do Soberano Senhor Jeová.”

'''

xref:026-ezequiel/026-ezequiel-042.adoc#v26-42-0[&#60; Capítulo Anterior] | <<v26-43-0,Topo>> | xref:026-ezequiel/026-ezequiel-044.adoc#v26-44-0[Próximo Capítulo &#62;]