include::./index.adoc[]

[[v26-40-0]]
=== Ezequiel, 40
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v26-40-1]]

^<<v26-40-1,1>>^ No vigésimo quinto ano de nosso exílio, no começo do ano, no décimo [dia] do mês, no décimo quarto ano depois de a cidade ter sido golpeada, no mesmíssimo dia, veio a estar sobre mim a mão de Jeová, de modo que me levou àquele lugar.

[[v26-40-2]]

^<<v26-40-2,2>>^ Nas visões de Deus,^&#42;1^ ele me levou à terra de Israel e me pousou aos poucos sobre um monte muito alto, em que havia ao sul^&#42;2^ algo como a estrutura de uma cidade.

[NOTE]
====
. “Nas visões de Deus.” Hebr.: bemar·’óhth ’Elo·hím.
. Ou “em direção ao Negebe”.
====

[[v26-40-3]]

^<<v26-40-3,3>>^ E ele passou a levar-me para lá, e eis que havia ali um homem.^&#42;1^ Sua aparência era como a aparência de cobre, e havia na sua mão um cordel de linho e uma cana de medir, e ele estava parado no portão.^&#42;2^

[NOTE]
====
. “Homem.” Hebr.: ’ish; gr.: a·nér; lat.: vir.
. Ou “portal”, segundo a sua descrição.
====

[[v26-40-4]]

^<<v26-40-4,4>>^ E o homem começou a falar comigo: “Filho do homem,^&#42;1^ vê com os teus olhos e ouve com os teus ouvidos, e fixa teu coração em tudo o que eu te mostrar, porque foste trazido para cá para que [eu] te mostrasse [isso]. Conta à casa de Israel tudo o que estás vendo.”

[NOTE]
====
. “Filho do homem.” Hebr.: ben-’a·dhám; gr.: hui·é an·thró·pou; lat.: fí·li hó·mi·nis.
====

[[v26-40-5]]

^<<v26-40-5,5>>^ E eis que havia uma muralha fora da casa em todo o redor. E na mão do homem havia uma cana de medir^&#42;1^ de seis côvados, de um côvado e uma largura de mão.^&#42;2^ E ele começou a medir a largura da coisa construída,^&#42;3^ uma cana; e a altura, uma cana.

[NOTE]
====
. “Uma cana de medir.” Hebr.: qenéh ham·mid·dáh; gr.: ká·la·mos; lat.: cá·la·mus men·sú·rae. Veja Gál 6:16 n.: “conduta”; Re 11:1.
. “Um côvado e uma largura de mão.” Um côvado de uns 44,5 cm e uma largura de mão de uns 7,4 cm equivaliam a cerca de 51,8 cm, e representavam o côvado longo. Portanto, “uma cana de medir de seis côvados” equivalia a 3,11 m.
. “Da coisa construída.” Hebr.: hab·bin·yán; LXX: “muralha externa (avançada)”.
====

[[v26-40-6]]

^<<v26-40-6,6>>^ Então chegou ao portão, cuja frente dava para o leste, e subiu pelos seus degraus. E ele começou a medir o limiar do portão, uma cana de largura, e o outro limiar, uma cana de largura.

[[v26-40-7]]

^<<v26-40-7,7>>^ E a saleta da guarda tinha uma cana de comprimento e uma cana de largura, e entre as saletas da guarda havia cinco côvados; e o limiar do portão ao lado do pórtico do portão, para o lado de dentro, era de uma cana.

[[v26-40-8]]

^<<v26-40-8,8>>^ E ele passou a medir o pórtico do portão para o lado de dentro, uma cana.

[[v26-40-9]]

^<<v26-40-9,9>>^ Mediu, pois, o pórtico do portão, oito côvados; e suas pilastras laterais,^&#42;1^ dois côvados; e o pórtico do portão estava para o lado de dentro.

[NOTE]
====
. Ou “saliências”.
====

[[v26-40-10]]

^<<v26-40-10,10>>^ E as saletas da guarda do portão que dava para o leste eram três deste lado e três daquele lado. As três delas tinham a mesma medida, e as pilastras laterais tinham a mesma medida, deste lado e daquele lado.

[[v26-40-11]]

^<<v26-40-11,11>>^ Então mediu a largura da entrada do portão, dez côvados; o comprimento do portão, treze côvados.

[[v26-40-12]]

^<<v26-40-12,12>>^ E a área cercada defronte das saletas da guarda era de um côvado, e havia uma área cercada de um côvado em [ambos os] lados. E a saleta da guarda tinha seis côvados deste lado e seis côvados daquele lado.

[[v26-40-13]]

^<<v26-40-13,13>>^ E ele prosseguiu, medindo o portão desde o teto de [uma] saleta da guarda até o teto da outra, uma largura de vinte e cinco côvados; uma entrada estava defronte de outra entrada.

[[v26-40-14]]

^<<v26-40-14,14>>^ Então fez pilastras laterais de sessenta côvados, sim, até a[s] pilastra[s] latera[is] do pátio nos port[ões] ao redor.^&#42;1^

[NOTE]
====
. “E a parte aberta do pórtico do portão do lado de fora era de vinte côvados, as saletas do portão estando ao redor”, LXXB.
====

[[v26-40-15]]

^<<v26-40-15,15>>^ E da frente do portão de entrada [até] a frente do pórtico do portão interno eram cinqüenta côvados.

[[v26-40-16]]

^<<v26-40-16,16>>^ E havia janelas de vãos que se estreitavam para as saletas da guarda e para as suas pilastras laterais para o lado de dentro do portão, em todo o redor, e assim era para os pórticos. E as janelas estavam em todo o redor para o lado de dentro, e nas pilastras laterais havia figuras de palmeiras.

[[v26-40-17]]

^<<v26-40-17,17>>^ E ele me levou aos poucos ao pátio externo, e eis que havia [ali] refeitórios e um pavimento feito para o pátio em redor. Havia trinta refeitórios no pavimento.

[[v26-40-18]]

^<<v26-40-18,18>>^ E o pavimento do lado dos portões tinha o comprimento exato dos portões — o pavimento inferior.

[[v26-40-19]]

^<<v26-40-19,19>>^ E ele passou a medir a largura desde a frente do portão inferior até a frente do pátio interno. Fora dele era de cem côvados, para o leste e para o norte.

[[v26-40-20]]

^<<v26-40-20,20>>^ E o pátio externo tinha um portão cuja frente dava para o norte. Ele lhe mediu o comprimento e a largura.

[[v26-40-21]]

^<<v26-40-21,21>>^ E suas saletas da guarda eram três deste lado e três daquele lado. E suas próprias pilastras laterais e seu próprio pórtico mostraram ter a mesma medida do primeiro portão. Tinha cinqüenta côvados de comprimento e vinte e cinco côvados de largura.

[[v26-40-22]]

^<<v26-40-22,22>>^ E suas janelas, e seu pórtico, e suas figuras de palmeiras eram da mesma medida como os do portão, cuja frente dava para o leste. E as pessoas podiam subir a ele por sete degraus, e seu pórtico estava na sua frente.

[[v26-40-23]]

^<<v26-40-23,23>>^ E o portão do pátio interno estava defronte do portão ao norte; também [havia um] ao leste. E ele passou a medir de portão a portão, cem côvados.

[[v26-40-24]]

^<<v26-40-24,24>>^ E ele me levou aos poucos para o sul,^&#42;1^ e eis que havia um portão que dava para o sul, e ele mediu suas pilastras laterais e seu pórtico como tendo as mesmas medidas que estes.

[NOTE]
====
. “O sul.” Hebr.: had·da·róhm.
====

[[v26-40-25]]

^<<v26-40-25,25>>^ E o mesmo e seu pórtico tinham janelas ao redor, iguais a estas janelas. Tinha cinqüenta côvados de comprimento e vinte e cinco côvados de largura.

[[v26-40-26]]

^<<v26-40-26,26>>^ E havia sete degraus para se subir a ele, e seu pórtico estava na sua frente. E tinha figuras de palmeiras, uma deste lado e outra daquele lado das suas pilastras laterais.

[[v26-40-27]]

^<<v26-40-27,27>>^ E o pátio interno tinha um portão que dava para o sul. E ele mediu de portão a portão para o sul, cem côvados.

[[v26-40-28]]

^<<v26-40-28,28>>^ E ele me levou aos poucos ao pátio interno pelo portão do sul. E passou a medir o portão do sul como tendo as mesmas medidas que estes.

[[v26-40-29]]

^<<v26-40-29,29>>^ E suas saletas da guarda, e suas pilastras laterais, e seu pórtico tinham as mesmas medidas que estes. E o mesmo e seu pórtico tinham janelas ao redor. Tinha cinqüenta côvados de comprimento e vinte e cinco côvados de largura.

[[v26-40-30]]

^<<v26-40-30,30>>^ ^&#42;1^ E havia pórticos em redor; o comprimento era de vinte e cinco côvados e a largura de cinco côvados.

[NOTE]
====
. O v. 30, não encontrado em LXXIt e em alguns mss. hebr., é considerado como ditografia do v. 29.
====

[[v26-40-31]]

^<<v26-40-31,31>>^ E seu pórtico dava para o pátio externo, e havia figuras de palmeiras nas suas pilastras laterais, e sua subida tinha oito degraus.

[[v26-40-32]]

^<<v26-40-32,32>>^ E ele me levou aos poucos ao pátio interno, pelo caminho do leste, e passou a medir o portão como tendo as mesmas medidas que estes.

[[v26-40-33]]

^<<v26-40-33,33>>^ E suas saletas da guarda, e suas pilastras laterais, e seu pórtico tinham as mesmas medidas que estes, e o mesmo e seu pórtico tinham janelas ao redor. Tinha cinqüenta côvados de comprimento e vinte e cinco côvados de largura.

[[v26-40-34]]

^<<v26-40-34,34>>^ E seu pórtico dava para o pátio externo, e havia figuras de palmeiras nas suas pilastras laterais, deste lado e daquele lado. E sua subida tinha oito degraus.

[[v26-40-35]]

^<<v26-40-35,35>>^ E ele passou a levar-me ao portão setentrional e mediu, com as mesmas medidas que estes,

[[v26-40-36]]

^<<v26-40-36,36>>^ suas saletas da guarda, suas pilastras laterais e seu pórtico. E tinha janelas ao redor. Tinha cinqüenta côvados de comprimento e vinte e cinco côvados de largura.

[[v26-40-37]]

^<<v26-40-37,37>>^ E suas pilastras laterais davam para o pátio externo, e havia figuras de palmeiras nas suas pilastras laterais, deste lado e daquele lado. E sua subida tinha oito degraus.

[[v26-40-38]]

^<<v26-40-38,38>>^ E havia um refeitório com a sua entrada junto às pilastras laterais dos portões. Era ali que enxaguavam o holocausto.

[[v26-40-39]]

^<<v26-40-39,39>>^ E no pórtico do portão havia duas mesas deste lado e duas mesas daquele lado, para se abaterem sobre elas o holocausto, e a oferta pelo pecado, e a oferta pela culpa.

[[v26-40-40]]

^<<v26-40-40,40>>^ E do lado de fora, quando se sobe à entrada do portão setentrional, havia duas mesas. E do outro lado, pertencente ao pórtico do portão, havia duas mesas.

[[v26-40-41]]

^<<v26-40-41,41>>^ Havia quatro mesas do lado de cá e quatro mesas do lado de lá ao lado do portão — oito mesas, nas quais se fazia o abate.

[[v26-40-42]]

^<<v26-40-42,42>>^ E as quatro mesas^&#42;1^ para o holocausto eram de pedra lavrada. O comprimento era de um côvado e meio e a largura era de um côvado e meio, e a altura era de um côvado. Depositavam também sobre elas os instrumentos com os quais abatiam o holocausto e o sacrifício.

[NOTE]
====
. Não se especifica o lugar exato dessas quatro mesas junto ao portão setentrional.
====

[[v26-40-43]]

^<<v26-40-43,43>>^ E as bordas para se colocarem as coisas tinham a largura de uma mão, fixas na parte de dentro em todo o redor; e sobre as mesas [se punha]^&#42;1^ a carne da oferta presenteada.^&#42;2^

[NOTE]
====
. “Se punha”, Sy; MVg omitem isso.
. “Da oferta presenteada.” Hebr.: haq·qor·ván; lat.: ob·la·ti·ó·nis. Veja Mr 7:11.
====

[[v26-40-44]]

^<<v26-40-44,44>>^ E do lado de fora do portão interno havia os refeitórios dos cantores, no pátio interno, que estava do lado do portão setentrional. E sua frente dava para o sul. Havia um do lado do portão oriental.^&#42;1^ A frente dava para o norte.

[NOTE]
====
. “Oriental”, MTSyVg; LXX: “meridional”.
====

[[v26-40-45]]

^<<v26-40-45,45>>^ E ele passou a falar comigo: “Este, o refeitório cuja frente dá para o sul, é para os sacerdotes que cuidam da obrigação para com a casa.

[[v26-40-46]]

^<<v26-40-46,46>>^ E o refeitório cuja frente dá para o norte é para os sacerdotes que cuidam da obrigação para com o altar. São os filhos de Zadoque, dos filhos de Levi, que se chegam a Jeová para lhe ministrar.”

[[v26-40-47]]

^<<v26-40-47,47>>^ E ele prosseguiu medindo o pátio [interno]. Tinha cem côvados de comprimento e cem côvados de largura, sendo quadrado. E o altar achava-se diante da casa.

[[v26-40-48]]

^<<v26-40-48,48>>^ E ele passou a levar-me ao pórtico da casa e prosseguiu medindo a pilastra lateral do pórtico, cinco côvados deste lado e cinco côvados daquele lado. E a largura do portão era de três côvados deste lado e três côvados daquele lado.

[[v26-40-49]]

^<<v26-40-49,49>>^ O comprimento do pórtico era de vinte côvados e a largura de onze^&#42;1^ côvados. E subia-se a ele por degraus.^&#42;2^ E havia colunas ao lado das pilastras laterais, uma aqui e outra ali.

[NOTE]
====
. “Onze”, MTSyVg; LXX: “doze”.
. “E subia-se a ele sobre dez degraus”, LXX; Vg: “E por oito degraus se subia a ele.”
====

'''

xref:026-ezequiel/026-ezequiel-039.adoc#v26-39-0[&#60; Capítulo Anterior] | <<v26-40-0,Topo>> | xref:026-ezequiel/026-ezequiel-041.adoc#v26-41-0[Próximo Capítulo &#62;]