include::./index.adoc[]

[[v26-35-0]]
=== Ezequiel, 35
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v26-35-1]]

^<<v26-35-1,1>>^ E continuou a vir a haver para mim a palavra de Jeová, dizendo:

[[v26-35-2]]

^<<v26-35-2,2>>^ “Filho do homem, fixa a tua face contra a região montanhosa de Seir e profetiza contra ela.

[[v26-35-3]]

^<<v26-35-3,3>>^ E tens de dizer-lhe: ‘Assim disse o Soberano Senhor Jeová: “Eis que sou contra ti, ó região montanhosa de Seir, e vou estender a minha mão contra ti e fazer de ti um baldio desolado, sim, uma desolação.

[[v26-35-4]]

^<<v26-35-4,4>>^ Constituirei as tuas cidades em lugar desolado e tu mesma te tornarás mero baldio desolado; e terás de saber que eu sou Jeová,

[[v26-35-5]]

^<<v26-35-5,5>>^ visto que mostraste ter uma inimizade de duração indefinida e continuaste a entregar os filhos de Israel ao poder^&#42;1^ da espada, no tempo do seu desastre, no tempo do [seu] erro final.”’^&#42;2^

[NOTE]
====
. Lit.: “mãos”.
. Lit.: “no tempo do erro de [o] fim”.
====

[[v26-35-6]]

^<<v26-35-6,6>>^ “‘Portanto, assim como vivo’, é a pronunciação do Soberano Senhor Jeová, ‘visto que foi para o sangue que te preparei, então o próprio sangue te perseguirá. Decerto foi o sangue que odiaste, e o próprio sangue^&#42;1^ te perseguirá.

[NOTE]
====
. Ou “visto que não odiaste o sangue, o próprio sangue também”.
====

[[v26-35-7]]

^<<v26-35-7,7>>^ E hei de fazer da região montanhosa de Seir um baldio desolado, sim, uma desolação, e vou decepar dela aquele que passa e aquele que retorna.

[[v26-35-8]]

^<<v26-35-8,8>>^ E vou encher-lhe os montes com os seus mortos; quanto aos teus morros e teus vales e todos os teus regos, cairão neles os mesmos que são mortos à espada.

[[v26-35-9]]

^<<v26-35-9,9>>^ Baldios desolados de duração indefinida é o que farei de ti, e tuas próprias cidades não serão habitadas; e tereis de saber que eu sou Jeová.’

[[v26-35-10]]

^<<v26-35-10,10>>^ “Visto que dizes: ‘Estas duas nações e estas duas terras — minhas é que se tornarão, e havemos de tomar posse de cada [terra]’, quando aconteceu estar ali mesmo o próprio Jeová,

[[v26-35-11]]

^<<v26-35-11,11>>^ ‘portanto, assim como vivo’, é a pronunciação do Soberano Senhor Jeová, ‘vou também agir segundo a tua ira e segundo o teu ciúme que expressaste devido aos teus sentimentos de ódio contra elas; e vou dar-me a conhecer entre elas^&#42;1^ quando eu te julgar.

[NOTE]
====
. “Entre elas”, MTSyVg; LXX: “a ti”.
====

[[v26-35-12]]

^<<v26-35-12,12>>^ E terás de saber que eu mesmo, Jeová, ouvi todas as tuas coisas desrespeitosas que disseste a respeito dos montes de Israel, dizendo: “Foram^&#42;1^ desolados. Foram-nos dados por alimento.”

[NOTE]
====
. “Foram”, Mmargem; MT: “Ela foi.”
====

[[v26-35-13]]

^<<v26-35-13,13>>^ E continuastes a agir em estilo grandioso contra mim com as vossas bocas^&#42;1^ e multiplicastes contra mim as vossas palavras. Eu mesmo [as] ouvi.’

[NOTE]
====
. Ou “mantendes uma grande boca contra mim”.
====

[[v26-35-14]]

^<<v26-35-14,14>>^ “Assim disse o Soberano Senhor Jeová: ‘No mesmo tempo em que toda a terra se alegra, farei de ti um baldio desolado.

[[v26-35-15]]

^<<v26-35-15,15>>^ Assim como houve alegria da tua parte com a herança da casa de Israel, por ter sido desolada, farei a ti a mesma coisa. Um baldio desolado é o que te tornarás, ó região montanhosa de Seir, sim, todo o Edom, na inteireza; e terão de saber que eu sou Jeová.’”

'''

xref:026-ezequiel/026-ezequiel-034.adoc#v26-34-0[&#60; Capítulo Anterior] | <<v26-35-0,Topo>> | xref:026-ezequiel/026-ezequiel-036.adoc#v26-36-0[Próximo Capítulo &#62;]