include::./index.adoc[]

[[v26-3-0]]
=== Ezequiel, 3
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v26-3-1]]

^<<v26-3-1,1>>^ E ele passou a dizer-me: “Filho do homem, come o que achares. Come este rolo, e vai, fala à casa de Israel.”

[[v26-3-2]]

^<<v26-3-2,2>>^ Abri, pois, a minha boca, e ele, aos poucos, me fez comer este rolo.

[[v26-3-3]]

^<<v26-3-3,3>>^ E prosseguiu, dizendo-me: “Filho do homem, deves fazer o teu próprio ventre comer, para encheres os teus próprios intestinos com este rolo que te dou.” E eu comecei a comê-lo, e veio a ser na minha boca doce como mel.

[[v26-3-4]]

^<<v26-3-4,4>>^ E ele continuou a dizer-me: “Filho do homem, vai, entra no meio da casa de Israel, e tens de falar-lhes com as minhas palavras.

[[v26-3-5]]

^<<v26-3-5,5>>^ Pois não estás sendo enviado a um povo de idioma^&#42;1^ incompreensível ou de língua pesada,^&#42;2^ [mas] à casa de Israel,

[NOTE]
====
. Lit.: “lábio”. Veja Gên 11:1 n.: “idioma”.
. Ou “vagarosa”.
====

[[v26-3-6]]

^<<v26-3-6,6>>^ não a numerosos povos de idioma incompreensível ou de língua pesada, cujas palavras não possas ouvir [com entendimento]. Se eu te tivesse enviado a tais, seriam eles os que te escutariam.

[[v26-3-7]]

^<<v26-3-7,7>>^ Mas, quanto à casa de Israel, não vão querer escutar-te, pois não querem escutar a mim; porque todos os da casa de Israel são de cabeça dura^&#42;1^ e de coração duro.

[NOTE]
====
. Lit.: “de testa forte”.
====

[[v26-3-8]]

^<<v26-3-8,8>>^ Eis que fiz^&#42;1^ a tua face tão dura como as faces deles e a tua testa tão dura como as testas deles.

[NOTE]
====
. Lit.: “dei”.
====

[[v26-3-9]]

^<<v26-3-9,9>>^ Igual ao diamante,^&#42;1^ mais dura do que a pederneira fiz^&#42;2^ a tua testa. Não deves ter medo deles e não deves ficar aterrorizado diante das suas faces, porque são uma casa rebelde.”

[NOTE]
====
. Ou “esmeril”.
. Lit.: “dei”.
====

[[v26-3-10]]

^<<v26-3-10,10>>^ E prosseguiu, dizendo-me: “Filho do homem, todas as minhas palavras que eu te falar aceita no teu coração e ouve com os teus próprios ouvidos.

[[v26-3-11]]

^<<v26-3-11,11>>^ E vai, entra no meio do povo exilado, no meio dos filhos de teu povo, e tens de falar-lhes e dizer-lhes: ‘Assim disse o Soberano Senhor Jeová’, quer ouçam quer se refreiem [de ouvir].”

[[v26-3-12]]

^<<v26-3-12,12>>^ E um espírito^&#42;1^ passou a carregar-me e comecei a ouvir atrás de mim o ruído dum grande zunido: “Bendita seja a glória de Jeová desde o seu lugar.”

[NOTE]
====
. “Um espírito.” Hebr.: rú·ahh; gr.: pneú·ma; lat.: spí·ri·tus. Veja 1:4 n.: “vento”.
====

[[v26-3-13]]

^<<v26-3-13,13>>^ E havia o ruído das asas das criaturas viventes que se tocavam de perto, e o ruído das rodas bem ao lado delas, e o ruído dum grande zunido.

[[v26-3-14]]

^<<v26-3-14,14>>^ E [o] espírito me carregava, e passou a tomar-me, de modo que fui, amargurado, no furor do meu espírito, e a mão de Jeová sobre mim era forte.

[[v26-3-15]]

^<<v26-3-15,15>>^ Entrei, pois, entre o povo exilado em Tel-Abibe, que morava junto ao rio Quebar, e comecei a morar onde eles moravam; e fiquei morando^&#42;1^ ali por sete dias, aturdido no meio deles.

[NOTE]
====
. “E fiquei morando”, Mmargem e muitos mss. hebr.
====

[[v26-3-16]]

^<<v26-3-16,16>>^ E aconteceu, ao fim dos sete dias, que passou a vir a haver para mim a palavra de Jeová, dizendo:

[[v26-3-17]]

^<<v26-3-17,17>>^ “Filho do homem, constituí-te vigia^&#42;1^ para a casa de Israel, e terás de ouvir a fala procedente da minha boca e terás de avisá-los da minha parte.

[NOTE]
====
. Ou “atalaia; sentinela”. Hebr.: tso·féh.
====

[[v26-3-18]]

^<<v26-3-18,18>>^ Quando eu disser ao iníquo: ‘Positivamente morrerás’,^&#42;1^ e tu realmente não o avisares e não falares para avisar o iníquo do seu caminho iníquo, a fim de preservá-lo vivo, ele, sendo iníquo, morrerá no seu erro, mas o seu sangue demandarei da tua própria mão.

[NOTE]
====
. “Positivamente morrerás.” Lit.: “Morrendo morrerás.” Hebr.: mohth ta·múth. Veja Gên 2:17 n.
====

[[v26-3-19]]

^<<v26-3-19,19>>^ Mas, no que se refere a ti, se tiveres avisado o iníquo e ele realmente não recuar de sua iniqüidade e de seu caminho iníquo, ele é que morrerá pelo seu erro; mas tu, tu terás livrado a tua própria alma.^&#42;1^

[NOTE]
====
. “Tua própria alma.” Hebr.: naf·shekhá; gr.: psy·khén sou; lat.: á·ni·mam tú·am. Veja Ap. 4A.
====

[[v26-3-20]]

^<<v26-3-20,20>>^ E quando o justo recuar de sua justiça e realmente fizer injustiça, e eu tiver de pôr diante dele uma pedra de tropeço, ele é que morrerá por não o teres avisado. Morrerá por seu pecado, e seus atos justos que praticou não serão lembrados, mas demandarei o sangue dele da tua própria mão.

[[v26-3-21]]

^<<v26-3-21,21>>^ E se tu tiveres avisado o justo para que o justo não peque, e ele realmente não pecar, continuará a viver impreterivelmente porque foi avisado, e tu mesmo terás livrado a tua própria alma.”

[[v26-3-22]]

^<<v26-3-22,22>>^ E a mão de Jeová veio a estar ali sobre mim e ele passou a dizer-me: “Levanta-te, sai até o vale plano e lá eu falarei contigo.”

[[v26-3-23]]

^<<v26-3-23,23>>^ Levantei-me, pois, e saí ao vale plano, e eis que estava ali parada a glória de Jeová, igual à glória que eu tinha visto junto ao rio Quebar, e eu fui lançar-me com a minha face [por terra].

[[v26-3-24]]

^<<v26-3-24,24>>^ Então entrou em mim espírito e me fez ficar de pé, e ele começou a falar comigo e a dizer-me:
“Vem, fica encerrado na tua casa.

[[v26-3-25]]

^<<v26-3-25,25>>^ E tu, ó filho do homem, eis que certamente porão sobre ti cordas e te atarão com elas, para que não possas sair para o meio deles.

[[v26-3-26]]

^<<v26-3-26,26>>^ E a tua própria língua eu farei ficar apegada ao céu da boca e certamente ficarás mudo, e não te tornarás para eles um homem^&#42;1^ que dá repreensão, porque são uma casa rebelde.

[NOTE]
====
. “Um homem.” Hebr.: le’ísh; gr.: án·dra; lat.: vir.
====

[[v26-3-27]]

^<<v26-3-27,27>>^ E quando eu falar contigo, abrirei a tua boca, e terás de dizer-lhes: ‘Assim disse o Soberano Senhor Jeová.’ Ouça aquele que ouve e refreie-se aquele que se refreia [de ouvir], porque são uma casa rebelde.

'''

xref:026-ezequiel/026-ezequiel-002.adoc#v26-2-0[&#60; Capítulo Anterior] | <<v26-3-0,Topo>> | xref:026-ezequiel/026-ezequiel-004.adoc#v26-4-0[Próximo Capítulo &#62;]