include::./index.adoc[]

[[v26-30-0]]
=== Ezequiel, 30
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v26-30-1]]

^<<v26-30-1,1>>^ E continuou a vir a haver para mim a palavra de Jeová, dizendo:

[[v26-30-2]]

^<<v26-30-2,2>>^ “Filho do homem, profetiza, e tens de dizer: ‘Assim disse o Soberano Senhor Jeová: “Uivai: ‘Ai do dia!’

[[v26-30-3]]

^<<v26-30-3,3>>^ porque está próximo o dia, sim, está próximo o dia pertencente a Jeová. Dia de nuvens, tempo fixado de nações mostrará ser.

[[v26-30-4]]

^<<v26-30-4,4>>^ E uma espada há de entrar no Egito e terá de vir a haver dores agudas na Etiópia,^&#42;1^ quando se cair morto no Egito e realmente se lhe tirar a opulência e realmente se lhe derrubarem os alicerces.

[NOTE]
====
. “Etiópia”, LXXVg; MTSy: “Cus”.
====

[[v26-30-5]]

^<<v26-30-5,5>>^ Etiópia, e Pute, e Lude, e toda a mistura de gente,^&#42;1^ e Cube e os filhos da terra do pacto — com eles é que cairão pela própria espada.”’

[NOTE]
====
. “Mistura de gente”, MLXX; Sy: “Arábia”.
====

[[v26-30-6]]

^<<v26-30-6,6>>^ “Assim disse Jeová: ‘Também os sustentadores do Egito terão de cair e o orgulho da sua força terá de vir abaixo.’
“‘Desde Migdol até Siene^&#42;1^ cairão nela pela própria espada’, é a pronunciação do Soberano Senhor Jeová.

[NOTE]
====
. Ou “Assuã”. Hebr.: Sewe·néh.
====

[[v26-30-7]]

^<<v26-30-7,7>>^ ‘Também terão de ser desolados no meio de terras desoladas, e suas próprias cidades virão a estar bem no meio de cidades devastadas.

[[v26-30-8]]

^<<v26-30-8,8>>^ E terão de saber que eu sou Jeová, quando eu acender um fogo no Egito e todos os seus ajudadores forem realmente quebrados.

[[v26-30-9]]

^<<v26-30-9,9>>^ Naquele dia sairão mensageiros de diante de mim nos navios,^&#42;1^ a fim de fazer tremer a Etiópia confiante em si própria. E terá de vir a haver entre eles dores agudas no dia do Egito, pois, eis que terá de vir.’

[NOTE]
====
. “Nos navios”, M; lat.: in tri·é·ri·bus, “nas trirremes”; LXXSy: “apressados”.
====

[[v26-30-10]]

^<<v26-30-10,10>>^ “Assim disse o Soberano Senhor Jeová: ‘Vou também fazer cessar a massa de gente do Egito pela mão de Nabucodorosor, rei de Babilônia.

[[v26-30-11]]

^<<v26-30-11,11>>^ Ele e seu povo com ele, os tiranos das nações, estão sendo trazidos para arruinar a terra. E eles terão de desembainhar as suas espadas contra o Egito e encher a terra de mortos.

[[v26-30-12]]

^<<v26-30-12,12>>^ E eu vou fazer dos canais do Nilo solo seco e vou vender a terra na mão de homens maus, e vou fazer que a terra e sua plenitude sejam desoladas pela mão de estranhos. Eu, Jeová, é que falei.’

[[v26-30-13]]

^<<v26-30-13,13>>^ “Assim disse o Soberano Senhor Jeová: ‘Vou também destruir os ídolos sórdidos e fazer cessar em Nofe^&#42;1^ os deuses que nada valem, e não mais se mostrará haver maioral procedente da terra do Egito; e hei de pôr medo na terra do Egito.

[NOTE]
====
. “Nofe”, M; LXXSyVg: “Mênfis”.
====

[[v26-30-14]]

^<<v26-30-14,14>>^ Vou desolar Patros e acender um fogo em Zoã e executar atos de julgamento em Nô.^&#42;1^

[NOTE]
====
. “Nô”, MSy; TVg: “Alexandria”.
====

[[v26-30-15]]

^<<v26-30-15,15>>^ E vou derramar meu furor sobre Sim,^&#42;1^ o baluarte do Egito, e decepar a massa de gente de Nô.

[NOTE]
====
. “Sim”, MTSy; Vg: “Pelúsio”.
====

[[v26-30-16]]

^<<v26-30-16,16>>^ E vou acender um fogo no Egito. Sim estará impreterivelmente em severas dores, e a própria Nô virá a ficar para ser capturada através de brechas; e no que se refere a Nofe — haverá adversários durante o dia!

[[v26-30-17]]

^<<v26-30-17,17>>^ Quanto aos jovens de Om^&#42;1^ e Pi-Besete, cairão à espada, e as próprias [cidades] irão ao cativeiro.

[NOTE]
====
. Lit.: “Aven”, M; LXXVg: “Heliópolis”.
====

[[v26-30-18]]

^<<v26-30-18,18>>^ E em Tafnes o dia realmente ficará escuro, quando eu quebrar as cangas do Egito. E realmente se fará cessar nela o orgulho da sua força. Quanto a ela, as próprias nuvens a cobrirão, e as suas próprias aldeias dependentes^&#42;1^ irão ao cativeiro.

[NOTE]
====
. Lit.: “suas . . . filhas”.
====

[[v26-30-19]]

^<<v26-30-19,19>>^ E eu vou executar atos de julgamento no Egito; e terão de saber que eu sou Jeová.’”

[[v26-30-20]]

^<<v26-30-20,20>>^ E aconteceu mais, naquele décimo primeiro ano, no primeiro [mês], no sétimo [dia] do mês, que veio a haver para mim a palavra de Jeová, dizendo:

[[v26-30-21]]

^<<v26-30-21,21>>^ “Filho do homem, hei de quebrar o braço de Faraó, rei do Egito, e eis que absolutamente não será pensado para que sare, pondo-se-lhe uma atadura para pensá-lo, a fim de que fique forte para agarrar a espada.”

[[v26-30-22]]

^<<v26-30-22,22>>^ “Portanto, assim disse o Soberano Senhor Jeová: ‘Eis que sou contra Faraó, rei do Egito, e vou quebrar-lhe os braços, o forte e o quebrado, e vou fazer a espada cair-lhe da mão.

[[v26-30-23]]

^<<v26-30-23,23>>^ E vou espalhar os egípcios entre as nações e dispersá-los entre as terras.

[[v26-30-24]]

^<<v26-30-24,24>>^ E vou fortalecer os braços do rei de Babilônia e dar a minha espada na sua mão, e vou quebrar os braços de Faraó, e, como alguém mortalmente ferido, certamente gemerá muitíssimo diante dele.

[[v26-30-25]]

^<<v26-30-25,25>>^ E vou fortalecer os braços do rei de Babilônia, e os próprios braços de Faraó cairão; e terão de saber que eu sou Jeová, quando eu der a minha espada na mão do rei de Babilônia e ele realmente a estender contra a terra do Egito.

[[v26-30-26]]

^<<v26-30-26,26>>^ E vou espalhar os egípcios entre as nações e dispersá-los entre as terras; e terão de saber que eu sou Jeová.’”

'''

xref:026-ezequiel/026-ezequiel-029.adoc#v26-29-0[&#60; Capítulo Anterior] | <<v26-30-0,Topo>> | xref:026-ezequiel/026-ezequiel-031.adoc#v26-31-0[Próximo Capítulo &#62;]