include::./index.adoc[]

[[v26-16-0]]
=== Ezequiel, 16
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v26-16-1]]

^<<v26-16-1,1>>^ E a palavra de Jeová veio a mim adicionalmente, dizendo:

[[v26-16-2]]

^<<v26-16-2,2>>^ “Filho do homem, faze saber a Jerusalém as suas coisas detestáveis.

[[v26-16-3]]

^<<v26-16-3,3>>^ E terás de dizer: ‘Assim disse o Soberano Senhor Jeová a Jerusalém: “Tua origem e teu nascimento é da terra do cananeu. Teu pai era amorreu e tua mãe hitita.

[[v26-16-4]]

^<<v26-16-4,4>>^ E quanto ao teu nascimento, no dia em que nasceste não te foi cortado o cordão umbilical e não foste lavada em água para purificação, e não foste esfregada com sal, e de modo algum foste enfaixada.

[[v26-16-5]]

^<<v26-16-5,5>>^ Nenhum olho teve dó de ti para fazer-te uma destas coisas em compaixão para contigo, mas foste lançada na superfície do campo, porque se abominava a tua alma no dia em que nasceste.

[[v26-16-6]]

^<<v26-16-6,6>>^ “‘“E eu vim passando por ti e cheguei a ver-te espernear no teu sangue, e passei a dizer-te no teu sangue: ‘Continua vivendo!’ sim, a dizer-te no teu sangue: ‘Continua vivendo!’

[[v26-16-7]]

^<<v26-16-7,7>>^ Fiz de ti uma multidão muito grande,^&#42;1^ qual renovo do campo, para que crescesses, e te tornasses grande, e entrasses com o enfeite mais belo. Os próprios dois seios se desenvolveram firmemente e teu próprio cabelo cresceu abundantemente, sendo que tinhas estado nua e despida.”’^&#42;2^

[NOTE]
====
. Lit.: “miríade; dez mil”.
. Lit.: “eras nudez e desnudamento”.
====

[[v26-16-8]]

^<<v26-16-8,8>>^ “‘E eu vim passando por ti e cheguei a ver-te, e eis que o teu tempo era o tempo para expressões de amor. De modo que passei a estender sobre ti a aba da minha [veste] e a cobrir a tua nudez, e a fazer-te uma declaração juramentada, e a entrar num pacto contigo’, é a pronunciação do Soberano Senhor Jeová, ‘e assim te tornaste minha.

[[v26-16-9]]

^<<v26-16-9,9>>^ Além disso, lavei-te com água e lavei de ti o teu sangue, e untei-te com óleo.

[[v26-16-10]]

^<<v26-16-10,10>>^ E fui vestir-te com uma veste bordada, e calçar-te com pele de foca, e envolver-te em linho fino, e cobrir-te com tecido suntuoso.

[[v26-16-11]]

^<<v26-16-11,11>>^ E fui ataviar-te com enfeites e colocar pulseiras sobre as tuas mãos e um colar em volta do teu pescoço.

[[v26-16-12]]

^<<v26-16-12,12>>^ Além disso, coloquei uma argola na tua narina, e arrecadas nas tuas orelhas, e uma bela coroa sobre a tua cabeça.

[[v26-16-13]]

^<<v26-16-13,13>>^ E tu te ataviavas com ouro e com prata, e teu vestuário era linho fino, e tecido suntuoso, e uma veste bordada. Flor de farinha, e mel, e azeite era o que comias, e cresceste, tornando-te muitíssimo bonita, e aos poucos te tornaste habilitada para a posição régia.’”

[[v26-16-14]]

^<<v26-16-14,14>>^ “‘E um nome começou a sair para ti entre as nações por causa da tua lindeza, pois era perfeita devido ao meu esplendor que eu tinha posto sobre ti’, é a pronunciação do Soberano Senhor Jeová.”

[[v26-16-15]]

^<<v26-16-15,15>>^ “‘Mas, começaste a confiar na tua lindeza, e a tornar-te prostituta por causa do teu nome, e [começaste] a derramar os teus atos de prostituição sobre todo transeunte; veio a ser dele.

[[v26-16-16]]

^<<v26-16-16,16>>^ E passaste a tomar algumas das tuas vestes e a fazer para ti altos de cores variadas, e sobre eles te prostituías — tais coisas não entram e isso não deve acontecer.^&#42;1^

[NOTE]
====
. O significado desta expressão hebr. é incerto. LXX: “e de modo algum entrarás, e de modo algum acontecerá”; Vg: “assim como não aconteceu, nem vai acontecer”.
====

[[v26-16-17]]

^<<v26-16-17,17>>^ E tomavas os teus belos objetos do meu ouro e da minha prata, que eu te dera, e fazias para ti imagens de um macho e te prostituías com elas.^&#42;1^

[NOTE]
====
. Ou “e tinhas relações sexuais infiéis com elas”. Hebr.: wat·tiz·ni·vám; lat.: et for·ni·cá·ta es in é·is.
====

[[v26-16-18]]

^<<v26-16-18,18>>^ E tomavas as tuas vestes bordadas e as cobrias; e realmente punhas diante delas meu óleo e meu incenso.

[[v26-16-19]]

^<<v26-16-19,19>>^ E meu pão que eu te dera — a flor de farinha, e o azeite, e o mel que te fiz comer — tu realmente também os puseste diante delas como cheiro repousante,^&#42;1^ e isto continuou ocorrendo’, é a pronunciação do Soberano Senhor Jeová.”

[NOTE]
====
. Ou “calmante; tranqüilizante”.
====

[[v26-16-20]]

^<<v26-16-20,20>>^ “‘E tomavas teus filhos e tuas filhas que me deste à luz e os sacrificavas para que fossem devorados — não chega isso dos teus atos de prostituição?

[[v26-16-21]]

^<<v26-16-21,21>>^ E matavas os meus filhos,^&#42;1^ e por fazê-los passar pelo [fogo] tu lhes entregavas estes.

[NOTE]
====
. “Meus filhos”, MSyVg; LXX e oito mss. hebr.: “teus filhos”.
====

[[v26-16-22]]

^<<v26-16-22,22>>^ E em todas as tuas coisas detestáveis e em teus atos de prostituição não te lembraste dos dias da tua mocidade quando estavas nua e despida; vieste a estar esperneando no teu sangue.

[[v26-16-23]]

^<<v26-16-23,23>>^ Sucedeu, assim, depois de toda a tua maldade, (“ai, ai de ti”, é a pronunciação do Soberano Senhor Jeová,)

[[v26-16-24]]

^<<v26-16-24,24>>^ que foste construir para ti uma proeminência^&#42;1^ e a fazer para ti uma elevação em cada praça pública.

[NOTE]
====
. Ou “uma bossa (protuberância arredondada)”, ao pé do altar, evidentemente para fins imorais.
====

[[v26-16-25]]

^<<v26-16-25,25>>^ Em cada cabeceira do caminho construíste a tua elevação, e começaste a fazer da tua lindeza algo detestável, e a escarranchar as pernas a todo transeunte, e a multiplicar os teus atos de prostituição.

[[v26-16-26]]

^<<v26-16-26,26>>^ E foste prostituir-te com os filhos do Egito, teus vizinhos de carne^&#42;1^ grande, e continuaste a fazer abundar a tua prostituição para me ofender.

[NOTE]
====
. Ou “órgão genital”. Veja Le 15:2, 3.
====

[[v26-16-27]]

^<<v26-16-27,27>>^ E eis que certamente estenderei a minha mão contra ti e reduzirei a tua porção concedida, e entregar-te-ei ao [desejo de] alma das mulheres que te odeiam, as filhas dos filisteus, as mulheres que foram humilhadas por causa do teu proceder com respeito à conduta desenfreada.

[[v26-16-28]]

^<<v26-16-28,28>>^ “‘E foste prostituir-te com os filhos da Assíria, porque não te fartavas, e continuaste a prostituir-te com eles e tampouco te fartaste.

[[v26-16-29]]

^<<v26-16-29,29>>^ Assim fizeste abundar a tua prostituição para com a terra de Canaã, para com os caldeus; e mesmo nisso não te fartaste.

[[v26-16-30]]

^<<v26-16-30,30>>^ Oh! como estou cheio de ira contra ti’,^&#42;1^ é a pronunciação do Soberano Senhor Jeová, ‘por fazeres todas estas coisas, trabalho de mulher, de prostituta prepotente!

[NOTE]
====
. Possivelmente: “Oh! quão fraco é o teu coração!”
====

[[v26-16-31]]

^<<v26-16-31,31>>^ Quando construíste a tua proeminência na cabeceira de todo caminho e fizeste a tua própria elevação em cada praça pública, tornaste-te, não obstante, dessemelhante de uma prostituta, por desdenhares a paga.

[[v26-16-32]]

^<<v26-16-32,32>>^ No caso da esposa que comete adultério,^&#42;1^ ela acolhe estranhos em lugar de seu próprio marido.

[NOTE]
====
. Ou “que comete infidelidade marital sexual”. Hebr.: ham·mena·’á·feth; gr.: he moi·kho·mé·ne; lat.: a·dúl·te·ra. Veja Mt 5:32 n.: “adultério”.
====

[[v26-16-33]]

^<<v26-16-33,33>>^ A todas as prostitutas costuma-se dar um presente, mas tu — tu deste os teus presentes a todos os que te amavam apaixonadamente e lhes ofereces suborno para que cheguem a ti de todas as redondezas, nos teus atos de prostituição.

[[v26-16-34]]

^<<v26-16-34,34>>^ E no teu caso dá-se o oposto do que se dá com outras mulheres, nos teus atos de prostituição, e à tua maneira não se tem cometido prostituição, visto que dás a paga, não se tendo dado a paga a ti, e deste modo sucede o contrário.’

[[v26-16-35]]

^<<v26-16-35,35>>^ “Portanto, ó prostituta, ouve a palavra de Jeová.

[[v26-16-36]]

^<<v26-16-36,36>>^ Assim disse o Soberano Senhor Jeová: ‘Visto que se derramou a tua lascívia^&#42;1^ e se descobrem as tuas partes pudendas nos teus atos de prostituição para com os que te amam apaixonadamente e para com todos os teus detestáveis ídolos sórdidos, até mesmo com o sangue dos teus filhos que lhes entregaste,

[NOTE]
====
. Possivelmente: “menstruação”.
====

[[v26-16-37]]

^<<v26-16-37,37>>^ portanto, eis que estou reunindo contra ti todos os que te amam apaixonadamente, aos quais davas prazer, e todos os que amaste, junto com todos os que odiaste, e eu vou reuni-los contra ti de todos os arredores e vou descobrir para eles as tuas partes pudendas, e eles terão de ver todas as tuas partes pudendas.

[[v26-16-38]]

^<<v26-16-38,38>>^ “‘E eu vou julgar-te com os julgamentos de adúlteras e de mulheres que derramam sangue, e vou dar-te o sangue de furor e de ciúme.

[[v26-16-39]]

^<<v26-16-39,39>>^ E vou entregar-te na sua mão e eles certamente derrubarão a tua proeminência e certamente demolirão as tuas elevações, e terão de tirar-te as tuas vestes e tomar os teus belos objetos, e terão de deixar-te para trás nua e despida.

[[v26-16-40]]

^<<v26-16-40,40>>^ E terão de fazer subir contra ti uma congregação, e atirar pedras em ti, e trucidar-te com as suas espadas.

[[v26-16-41]]

^<<v26-16-41,41>>^ E terão de queimar as tuas casas com fogo e executar em ti atos de julgamento perante os olhos de muitas mulheres; e eu vou fazer-te cessar de [ser] prostituta, nem tampouco darás mais paga.

[[v26-16-42]]

^<<v26-16-42,42>>^ E vou fazer o meu furor descansar em ti e meu ciúme terá de desviar-se de ti; e vou sossegar e não me sentirei mais ofendido.’

[[v26-16-43]]

^<<v26-16-43,43>>^ “‘Visto que não te lembraste dos dias da tua mocidade e me causavas agitação por causa de todas estas coisas, eis que também eu, da minha parte, porei teu próprio procedimento sobre a [tua] própria cabeça’, é a pronunciação do Soberano Senhor Jeová, ‘e certamente não praticarás mais nenhuma conduta desenfreada junto com todas as tuas coisas detestáveis.

[[v26-16-44]]

^<<v26-16-44,44>>^ “‘Eis que todo aquele que usar um provérbio contra ti usará o provérbio, dizendo: “Tal mãe, tal filha!”

[[v26-16-45]]

^<<v26-16-45,45>>^ Tu és a filha de tua mãe, que abominava seu marido e seus filhos. E és a irmã de tuas irmãs, que abominavam seus maridos e seus filhos. A mãe de vós, mulheres, era hitita e vosso pai, amorreu.’”

[[v26-16-46]]

^<<v26-16-46,46>>^ “‘E tua irmã mais velha é a própria Samaria com as suas aldeias dependentes,^&#42;1^ que mora à tua esquerda, e tua irmã mais moça do que tu, que mora à tua direita, é Sodoma com as suas aldeias dependentes.

[NOTE]
====
. “Aldeias dependentes.” Lit.: “filhas”.
====

[[v26-16-47]]

^<<v26-16-47,47>>^ E não andaste nos seus caminhos, nem fizeste segundo as suas coisas detestáveis. Em pouco tempo começaste a agir ainda mais ruinosamente do que elas, em todos os teus caminhos.

[[v26-16-48]]

^<<v26-16-48,48>>^ Assim como vivo’, é a pronunciação do Soberano Senhor Jeová, ‘Sodoma, tua irmã, ela com as suas aldeias dependentes, não fez segundo o que tu fizeste, tu e as tuas aldeias dependentes.

[[v26-16-49]]

^<<v26-16-49,49>>^ Eis que este é o que mostrou ser o erro de Sodoma, tua irmã: Orgulho, fartura de pão e a despreocupação do sossego foram [as coisas] que vieram a ser dela e das suas aldeias dependentes, e ela não fortaleceu a mão do atribulado e do pobre.

[[v26-16-50]]

^<<v26-16-50,50>>^ E elas^&#42;1^ continuaram a ser soberbas e a praticar uma coisa detestável diante de mim, e eu finalmente as removi, assim como vi [ser conveniente].^&#42;2^

[NOTE]
====
. “Elas”, hebr. fem., referindo-se a “Sodoma” e suas “aldeias dependentes [lit.: filhas]”.
. “Vi [ser conveniente]”, MLXX; Vg: “viste”.
====

[[v26-16-51]]

^<<v26-16-51,51>>^ “‘E quanto a Samaria, ela não cometeu nem a metade dos teus pecados, mas tu continuaste a fazer abundar as tuas coisas detestáveis mais do que elas, de modo que fizeste as tuas irmãs parecer justas por causa de todas as tuas coisas detestáveis que praticaste.

[[v26-16-52]]

^<<v26-16-52,52>>^ Também tu, carrega a tua humilhação ao teres de argumentar a favor de tuas irmãs. Em vista dos teus pecados, nos quais agiste de modo mais detestável do que elas [agiram], elas são mais justas do que tu. E também tu, envergonha-te e carrega a tua humilhação por fazeres as tuas irmãs parecer justas.’

[[v26-16-53]]

^<<v26-16-53,53>>^ “‘E eu vou recolher os seus cativos, os cativos de Sodoma e das suas aldeias dependentes, e os cativos de Samaria e das suas aldeias dependentes; vou recolher também^&#42;1^ os teus cativos no seu meio,

[NOTE]
====
. “Vou recolher também”, TLXXSyVg.
====

[[v26-16-54]]

^<<v26-16-54,54>>^ para que carregues a tua humilhação; e terás de sentir-te humilhada em vista de tudo o que fizeste, sendo que tu as consolaste.

[[v26-16-55]]

^<<v26-16-55,55>>^ E tuas próprias irmãs, Sodoma e suas aldeias dependentes, retornarão ao seu estado anterior, e Samaria e suas aldeias dependentes retornarão ao seu estado anterior, e tu mesma e tuas aldeias dependentes retornareis ao vosso estado anterior.

[[v26-16-56]]

^<<v26-16-56,56>>^ E Sodoma, tua irmã, não se mostrou algo digno de se ouvir tua boca [mencionar] no dia do teu orgulho,

[[v26-16-57]]

^<<v26-16-57,57>>^ antes que a tua própria maldade chegasse a ser exposta, assim como no tempo do vitupério das filhas da Síria^&#42;1^ e de todas ao redor dela, as filhas dos filisteus, as que te menosprezam, por todos os lados.

[NOTE]
====
. “Síria (Arã)”, MTLXXVg; Sy e muitos mss. e ed. hebr. impressos: “Edom”.
====

[[v26-16-58]]

^<<v26-16-58,58>>^ A tua conduta desenfreada e as tuas coisas detestáveis, tu mesma terás de carregá-las’, é a pronunciação de Jeová.”

[[v26-16-59]]

^<<v26-16-59,59>>^ “Pois assim disse o Soberano Senhor Jeová: ‘Também terei de fazer contigo assim como tu fizeste, porque desprezaste o juramento, violando [meu] pacto.^&#42;1^

[NOTE]
====
. “Meu pacto”, LXXSy.
====

[[v26-16-60]]

^<<v26-16-60,60>>^ E eu, eu mesmo, terei de lembrar-me do meu pacto contigo nos dias da tua mocidade e terei de estabelecer para ti um pacto de duração indefinida.

[[v26-16-61]]

^<<v26-16-61,61>>^ E certamente te lembrarás dos teus caminhos e te sentirás humilhada ao acolheres as tuas irmãs, as mais velhas do que tu bem como as mais moças do que tu, e eu hei de dá-las a ti por filhas, mas não devido ao teu pacto.’

[[v26-16-62]]

^<<v26-16-62,62>>^ “‘E eu, eu mesmo, vou estabelecer contigo o meu pacto; e terás de saber que eu sou Jeová,

[[v26-16-63]]

^<<v26-16-63,63>>^ para te lembrares e realmente te envergonhares, e para que não mais venhas a ter razão para abrir a boca por causa da tua humilhação, quando eu fizer expiação por ti, por tudo o que fizeste’, é a pronunciação do Soberano Senhor Jeová.”

'''

xref:026-ezequiel/026-ezequiel-015.adoc#v26-15-0[&#60; Capítulo Anterior] | <<v26-16-0,Topo>> | xref:026-ezequiel/026-ezequiel-017.adoc#v26-17-0[Próximo Capítulo &#62;]