include::./index.adoc[]

[[v26-11-0]]
=== Ezequiel, 11
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v26-11-1]]

^<<v26-11-1,1>>^ E um espírito passou a levantar-me e a levar-me ao portão oriental da casa de Jeová, que dava para o leste, e eis que havia na entrada do portão vinte e cinco homens,^&#42;1^ e cheguei a ver no meio deles Jaazanias, filho de Azur, e Pelatias,^&#42;2^ filho de Benaia,^&#42;3^ príncipes do povo.

[NOTE]
====
. “Homens.” Hebr.: ’ish.
. Significando “Jeová Proveu Fuga”. Hebr.: Pelat·yá·hu.
. Significando “Jeová Edificou”. Hebr.: Bena·yá·hu.
====

[[v26-11-2]]

^<<v26-11-2,2>>^ Ele^&#42;1^ me disse então: “Filho do homem, estes são os homens^&#42;2^ que maquinam o que é prejudicial e que dão mau conselho contra esta cidade;

[NOTE]
====
. “Ele”, MTVg; LXXSy: “Jeová”.
. “Os homens.” Hebr.: ha·’ana·shím, pl. de ’ish.
====

[[v26-11-3]]

^<<v26-11-3,3>>^ que dizem: ‘Não está próxima a construção de casas? Ela^&#42;1^ é a panela de boca larga e nós somos a carne.’

[NOTE]
====
. “Ela”, hebr. fem., referindo-se à “cidade” de Jerusalém.
====

[[v26-11-4]]

^<<v26-11-4,4>>^ “Portanto, profetiza contra eles. Profetiza, ó filho do homem.”

[[v26-11-5]]

^<<v26-11-5,5>>^ Então caiu sobre mim o espírito^&#42;1^ de Jeová, e ele prosseguiu, dizendo-me: “Dize: ‘Assim disse Jeová: “Vós dissestes a coisa certa, ó casa de Israel; e no que se refere às coisas que vos subiram no espírito,^&#42;2^ eu mesmo o^&#42;3^ conhecia.

[NOTE]
====
. Ou “força ativa”. Hebr.: rú·ahh; gr.: pneú·ma; lat.: spí·ri·tus. Veja Gên 1:2 n.: “ativa”.
. Lit.: “e as subidas de vosso espírito”. Hebr.: u·ma·‛alóhth ru·hhakhém.
. “O”, no hebr. fem., referindo-se a “espírito”, hebr. fem.
====

[[v26-11-6]]

^<<v26-11-6,6>>^ Fizestes muitos os vossos mortos nesta cidade e enchestes as suas ruas de mortos.”’”

[[v26-11-7]]

^<<v26-11-7,7>>^ “Portanto, assim disse o Soberano Senhor Jeová: ‘Quanto aos vossos mortos que pusestes no meio dela,^&#42;1^ eles é que são a carne, e ela é a panela de boca larga; e vós mesmos é que sereis tirados^&#42;2^ do meio dela.’”

[NOTE]
====
. “Dela”, hebr. fem., referindo-se à “cidade” de Jerusalém.
. “Sereis tirados.” Entende-se que, no hebr., isto é um verbo no infinitivo absoluto, indefinido quanto ao tempo e impessoal, usado como sujeito da sentença.
====

[[v26-11-8]]

^<<v26-11-8,8>>^ “‘Temestes a espada, e é a espada que trarei sobre vós’, é a pronunciação do Soberano Senhor Jeová.

[[v26-11-9]]

^<<v26-11-9,9>>^ ‘E eu certamente vos farei sair do meio dela e vos entregarei na mão de estranhos, e executarei em vós atos de julgamento.

[[v26-11-10]]

^<<v26-11-10,10>>^ Caireis à espada. No termo^&#42;1^ de Israel vos julgarei; e tereis de saber que eu sou Jeová.

[NOTE]
====
. Ou “território”.
====

[[v26-11-11]]

^<<v26-11-11,11>>^ Ela mesma não virá a ser para vós uma panela de boca larga e vós mesmos não^&#42;1^ vireis a ser carne no meio dela. No termo^&#42;2^ de Israel vos julgarei,

[NOTE]
====
. “Não”, LXXSyVg.
. Ou “território”.
====

[[v26-11-12]]

^<<v26-11-12,12>>^ e tereis de saber que eu sou Jeová, pois não andastes nos meus regulamentos e não executastes os meus julgamentos, mas fizestes segundo os julgamentos das nações ao vosso redor.’”

[[v26-11-13]]

^<<v26-11-13,13>>^ E sucedeu que, assim que profetizei, morreu o próprio Pelatias, filho de Benaia,^&#42;1^ e eu passei a lançar-me com a minha face [por terra] e a clamar com alta voz e a dizer: “Ai! Soberano Senhor Jeová! Estás executando a exterminação dos remanescentes de Israel?”

[NOTE]
====
. Hebr.: Bena·yáh. Veja v. 1 n.: “Benaia”.
====

[[v26-11-14]]

^<<v26-11-14,14>>^ E continuou a vir a haver para mim a palavra de Jeová, dizendo:

[[v26-11-15]]

^<<v26-11-15,15>>^ “Filho do homem, no que se refere aos teus irmãos, teus irmãos, os homens^&#42;1^ relacionados com o teu direito de resgate, bem como toda a casa de Israel, toda ela, são os a quem os habitantes de Jerusalém disseram: ‘Afastai-vos para longe de Jeová. Ela nos pertence; a terra que [nos] foi dada como possessão’;

[NOTE]
====
. “Homens.” Hebr.: ’an·shéh, pl. de ’ish.
====

[[v26-11-16]]

^<<v26-11-16,16>>^ portanto, dize: ‘Assim disse o Soberano Senhor Jeová: “Embora eu os tenha afastado para longe entre as nações e embora eu os tenha espalhado entre as terras, contudo me tornarei para eles um santuário, por um pouco de tempo,^&#42;1^ entre as terras às quais foram.”’

[NOTE]
====
. Ou “em pequena escala”.
====

[[v26-11-17]]

^<<v26-11-17,17>>^ “Portanto, dize: ‘Assim disse o Soberano Senhor Jeová: “Vou também reunir-vos dentre os povos e ajuntar-vos das terras entre as quais fostes espalhados, e vou dar-vos o solo de Israel.

[[v26-11-18]]

^<<v26-11-18,18>>^ E eles certamente chegarão lá e removerão dele todas as suas coisas repugnantes e todas as suas coisas detestáveis.

[[v26-11-19]]

^<<v26-11-19,19>>^ E vou dar-lhes um só coração e porei no seu^&#42;1^ íntimo um espírito novo; e certamente removerei da sua carne o coração de pedra e lhes darei um coração de carne,

[NOTE]
====
. “Seu”, TLXXSyVg e muitos mss. hebr.; M: “vosso”.
====

[[v26-11-20]]

^<<v26-11-20,20>>^ para que andem nos meus próprios estatutos e guardem as minhas próprias decisões judiciais e realmente as executem; e eles poderão realmente tornar-se meu povo e eu mesmo poderei tornar-me seu Deus.”’

[[v26-11-21]]

^<<v26-11-21,21>>^ “‘“Mas quanto àqueles cujo coração está andando nas^&#42;1^ suas coisas repugnantes e nas suas coisas detestáveis, hei de trazer seu próprio procedimento sobre a sua cabeça”, é a pronunciação do Soberano Senhor Jeová.’”

[NOTE]
====
. Lit.: “para dentro do coração das”, M.
====

[[v26-11-22]]

^<<v26-11-22,22>>^ E os querubins levantaram então suas asas, e as rodas estavam perto deles, e a glória do Deus de Israel estava sobre eles, de cima.

[[v26-11-23]]

^<<v26-11-23,23>>^ E a glória de Jeová subia de sobre o meio da cidade e começou a ficar parada sobre o monte que está ao oriente da cidade.

[[v26-11-24]]

^<<v26-11-24,24>>^ E um espírito é que me levantou e me levou finalmente à Caldéia, ao povo exilado, na visão pelo espírito^&#42;1^ de Deus; e a visão que eu vira foi subindo de sobre mim.

[NOTE]
====
. Ou “pela força ativa”. Hebr.: berú·ahh; gr.: pneú·ma·ti; lat.: spí·ri·tu. Veja Gên 1:2 n. e Gên 6:17 n.: “ativa”.
====

[[v26-11-25]]

^<<v26-11-25,25>>^ E eu comecei a falar ao povo exilado todas as coisas de Jeová, que ele me fizera ver.

'''

xref:026-ezequiel/026-ezequiel-010.adoc#v26-10-0[&#60; Capítulo Anterior] | <<v26-11-0,Topo>> | xref:026-ezequiel/026-ezequiel-012.adoc#v26-12-0[Próximo Capítulo &#62;]