include::./index.adoc[]

[[v26-33-0]]
=== Ezequiel, 33
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v26-33-1]]

^<<v26-33-1,1>>^ E passou a vir a haver para mim a palavra de Jeová, dizendo:

[[v26-33-2]]

^<<v26-33-2,2>>^ “Filho do homem, fala aos filhos do teu povo, e tens de dizer-lhes:
“‘No que se refere à terra, se eu trouxer sobre ela uma espada e o povo da terra,^&#42;1^ à uma, realmente tomar um homem^&#42;2^ e o constituir seu vigia,^&#42;3^

[NOTE]
====
. “O povo da terra.” Hebr.: ‛am-ha·’á·rets. Posteriormente usado como expressão de desprezo. Veja Jo 7:47-49.
. Ou “e o povo da terra realmente tomar um homem [hebr.: ’ish], um dentre seus termos”.
. Ou “sua sentinela; seu atalaia”. Hebr.: la·hém letso·féh.
====

[[v26-33-3]]

^<<v26-33-3,3>>^ e ele realmente vir a espada chegar sobre a terra e tocar a buzina,^&#42;1^ e avisar o povo,

[NOTE]
====
. Ou “shofar”.
====

[[v26-33-4]]

^<<v26-33-4,4>>^ e o ouvinte realmente ouvir o som da buzina, mas absolutamente não se der por avisado, e vier a espada e o levar, seu próprio sangue virá a estar sobre a sua própria cabeça.

[[v26-33-5]]

^<<v26-33-5,5>>^ Ele ouviu o som da buzina, mas não se deu por avisado. Seu próprio sangue virá a estar sobre ele mesmo. E se ele se tivesse dado por avisado, sua própria alma^&#42;1^ teria escapado.

[NOTE]
====
. Ou “sua própria vida”. Hebr.: naf·shóh; gr.: psy·khén; lat.: á·ni·mam. Veja Ap. 4A.
====

[[v26-33-6]]

^<<v26-33-6,6>>^ “‘E no que se refere ao vigia, se ele vir a espada chegar e realmente não tocar a buzina, e o povo não receber nenhum aviso, e a espada vier e lhes tirar a alma, terá de ser tirada pelo seu próprio erro, mas o seu sangue exigirei de volta da mão do próprio vigia.’^&#42;1^

[NOTE]
====
. Ou “sentinela; atalaia”.
====

[[v26-33-7]]

^<<v26-33-7,7>>^ “E no que se refere a ti, ó filho do homem, constituí-te vigia para a casa de Israel, e da minha boca terás de ouvir [a] palavra e dar-lhes aviso da minha parte.

[[v26-33-8]]

^<<v26-33-8,8>>^ Quando eu disser ao iníquo: ‘Ó iníquo, positivamente morrerás!’ mas tu realmente não falares para avisar o iníquo do seu caminho, ele mesmo morrerá como iníquo no seu próprio erro, mas o sangue dele requererei de volta da tua própria mão.

[[v26-33-9]]

^<<v26-33-9,9>>^ Mas, no que se refere a ti, se realmente avisares o iníquo do seu caminho, [para que] recue dele, mas ele realmente não recuar do seu caminho, ele mesmo morrerá no seu próprio erro, ao passo que tu mesmo certamente livrarás a tua própria alma.^&#42;1^

[NOTE]
====
. Ou “tua própria vida”. Hebr.: naf·shekhá.
====

[[v26-33-10]]

^<<v26-33-10,10>>^ “E no que se refere a ti, ó filho do homem, dize à casa de Israel: ‘Assim é que dissestes: “Visto que as nossas revoltas e os nossos pecados estão sobre nós e estamos apodrecendo neles, então, como é que continuaremos a viver?”’

[[v26-33-11]]

^<<v26-33-11,11>>^ Dize-lhes: ‘“Assim como vivo”, é a pronunciação do Soberano Senhor Jeová, “não me agrado na morte do iníquo, mas em que o iníquo recue do seu caminho e realmente continue vivendo. Recuai, recuai dos vossos maus caminhos, pois, por que devíeis morrer, ó casa de Israel?”’

[[v26-33-12]]

^<<v26-33-12,12>>^ “E quanto a ti, ó filho do homem, dize aos filhos do teu povo: ‘Nem a justiça do justo o livrará no dia da sua revolta. Mas, no que se refere à iniqüidade do iníquo, não se fará que tropece por causa dela no dia em que recuar da sua iniqüidade. Tampouco poderá ficar vivo aquele que tiver justiça, por causa dela, no dia em que pecar.

[[v26-33-13]]

^<<v26-33-13,13>>^ Quando eu disser ao justo: “Positivamente continuarás vivendo”, e ele mesmo realmente confiar na sua própria justiça e fizer injustiça, todos os seus próprios atos justos não serão lembrados, mas, pela sua injustiça que fez — por esta é que morrerá.

[[v26-33-14]]

^<<v26-33-14,14>>^ “‘E quando eu disser ao iníquo: “Positivamente morrerás”, e ele realmente recuar do seu pecado e praticar o juízo e a justiça,

[[v26-33-15]]

^<<v26-33-15,15>>^ [e] o iníquo restituir a própria coisa penhorada e devolver as próprias coisas roubadas, andando realmente nos próprios estatutos da vida por não fazer injustiça, positivamente continuará vivendo. Não morrerá.

[[v26-33-16]]

^<<v26-33-16,16>>^ Nenhum dos seus pecados com que pecou será lembrado contra ele. Juízo e justiça é o que praticou. Ele positivamente continuará vivendo.’

[[v26-33-17]]

^<<v26-33-17,17>>^ “E os filhos do teu povo disseram: ‘O caminho de Jeová^&#42;1^ não é acertado’, mas, no que se refere a eles, é o caminho deles que não é acertado.

[NOTE]
====
. Uma das 134 mudanças de YHWH para ’Adho·naí feitas pelos escribas. Veja Ap. 1B.
====

[[v26-33-18]]

^<<v26-33-18,18>>^ “Quando o justo recuar da sua justiça e realmente fizer injustiça, então terá de morrer por tais [atos].

[[v26-33-19]]

^<<v26-33-19,19>>^ E quando o iníquo recuar da sua iniqüidade e realmente praticar o juízo e a justiça, será por causa deles que ele mesmo continuará vivendo.

[[v26-33-20]]

^<<v26-33-20,20>>^ “E vós dissestes: ‘O caminho de Jeová^&#42;1^ não é acertado.’ Será segundo o caminho de cada um de vós que vos julgarei, ó casa de Israel.”

[NOTE]
====
. Veja v. 17 n.
====

[[v26-33-21]]

^<<v26-33-21,21>>^ Por fim aconteceu no décimo segundo ano, no décimo [mês], no quinto [dia] do mês de nosso exílio, que chegou a mim o fugitivo de Jerusalém, dizendo: “A cidade foi golpeada!”

[[v26-33-22]]

^<<v26-33-22,22>>^ Ora, a própria mão de Jeová viera a estar sobre mim na noitinha antes da chegada do fugitivo, e Ele passou a abrir-me a boca antes de [aquele] chegar a mim de manhã, e minha boca foi aberta e mostrou-se que eu não estava mais mudo.

[[v26-33-23]]

^<<v26-33-23,23>>^ E começou a vir a haver para mim a palavra de Jeová, dizendo:

[[v26-33-24]]

^<<v26-33-24,24>>^ “Filho do homem, os habitantes destes lugares devastados estão dizendo até mesmo a respeito do solo de Israel: ‘Abraão veio a ser apenas um, e assim mesmo tomou posse do país. E nós somos muitos; o país nos foi dado como possessão.’

[[v26-33-25]]

^<<v26-33-25,25>>^ “Portanto, dize-lhes: ‘Assim disse o Soberano Senhor Jeová: “Continuais a comer com^&#42;1^ sangue e os vossos olhos continuam a levantar-se para os vossos ídolos sórdidos e continuais a derramar sangue. Portanto, deveis vós possuir o país?

[NOTE]
====
. Lit.: “sobre”.
====

[[v26-33-26]]

^<<v26-33-26,26>>^ Dependestes^&#42;1^ da vossa espada. Fizestes^&#42;2^ uma coisa detestável e aviltastes, cada um, a esposa de seu companheiro. Portanto, deveis vós possuir o país?”’

[NOTE]
====
. Lit.: “Parastes em.”
. “Fizestes”, hebr. masc. pl., TSy e 18 mss. hebr.; M: “Fizestes”, hebr. fem. pl.
====

[[v26-33-27]]

^<<v26-33-27,27>>^ “Deves dizer-lhes o seguinte: ‘Assim disse o Soberano Senhor Jeová: “Assim como vivo, os que estão nos lugares devastados seguramente cairão pela própria espada; e aquele que está na superfície do campo, este hei de entregar às feras por alimento; e os que estão nos fortes e nas cavernas morrerão da própria peste.

[[v26-33-28]]

^<<v26-33-28,28>>^ E eu farei realmente da terra um baldio desolado, sim, uma desolação, e terá de fazer-se cessar o orgulho da sua força e terão de ser desolados os montes de Israel, sem que alguém passe por [eles].

[[v26-33-29]]

^<<v26-33-29,29>>^ E terão de saber que eu sou Jeová, quando eu fizer da terra um baldio desolado, sim, uma desolação, por causa de todas as suas coisas detestáveis que fizeram.”’

[[v26-33-30]]

^<<v26-33-30,30>>^ “E quanto a ti, ó filho do homem, os filhos do teu povo estão falando uns aos outros a teu respeito junto às paredes e nas entradas das casas, e um falou ao outro, cada um ao seu irmão, dizendo: ‘Vinde, por favor, e ouçamos qual é a palavra procedente de Jeová.’

[[v26-33-31]]

^<<v26-33-31,31>>^ E eles entrarão [chegando] a ti, como a entrada do povo, e se assentarão diante de ti como o meu povo; e certamente ouvirão as tuas palavras, mas não as porão em prática, porque com a sua boca expressam desejos sensuais [e] seu coração vai atrás de seu lucro injusto.

[[v26-33-32]]

^<<v26-33-32,32>>^ E eis que tu és para eles como uma canção de amores sensuais, como alguém com voz bonita e que toca bem um instrumento de cordas. E certamente ouvirão as tuas palavras, mas não há quem as ponha em prática.

[[v26-33-33]]

^<<v26-33-33,33>>^ E quando isso se cumprir — eis que tem de se cumprir — então terão de saber que foi um profeta que veio a estar no meio deles.”

'''

xref:026-ezequiel/026-ezequiel-032.adoc#v26-32-0[&#60; Capítulo Anterior] | <<v26-33-0,Topo>> | xref:026-ezequiel/026-ezequiel-034.adoc#v26-34-0[Próximo Capítulo &#62;]