include::./index.adoc[]

[[v26-26-0]]
=== Ezequiel, 26
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v26-26-1]]

^<<v26-26-1,1>>^ E sucedeu, no décimo primeiro ano, no primeiro [dia] do mês, que veio a haver para mim a palavra de Jeová, dizendo:

[[v26-26-2]]

^<<v26-26-2,2>>^ “Filho do homem, visto que Tiro disse contra Jerusalém: ‘Ah! Ela foi quebrada, as portas^&#42;1^ dos povos! A tendência será certamente para mim. Encher-me-ei — ela foi devastada’,

[NOTE]
====
. Ou “folhas duma porta”, M; T: “mercadora”.
====

[[v26-26-3]]

^<<v26-26-3,3>>^ por isso, assim disse o Soberano Senhor Jeová: ‘Eis que sou contra ti, ó Tiro, e vou fazer subir contra ti muitas nações, assim como o mar faz subir as suas ondas.

[[v26-26-4]]

^<<v26-26-4,4>>^ E elas certamente arruinarão as muralhas de Tiro e derrubarão as suas torres, e vou raspar dela o seu pó e fazer dela a lustrosa superfície escalvada dum rochedo.

[[v26-26-5]]

^<<v26-26-5,5>>^ Enxugadouro de redes de arrasto é o que ela se tornará no meio do mar.’
“‘Pois eu é que falei’, é a pronunciação do Soberano Senhor Jeová, ‘e ela terá de tornar-se objeto de saque para as nações.

[[v26-26-6]]

^<<v26-26-6,6>>^ E suas aldeias dependentes^&#42;1^ no campo — pela espada é que serão mortas, e as pessoas^&#42;2^ terão de saber que eu sou Jeová.’

[NOTE]
====
. Veja 16:46 n.
. Lit.: “eles”.
====

[[v26-26-7]]

^<<v26-26-7,7>>^ “Pois assim disse o Soberano Senhor Jeová: ‘Eis que trago contra Tiro a Nabucodorosor, rei de Babilônia,^&#42;1^ desde o norte, um rei de reis, com cavalos, e carros de guerra, e cavalarianos, e com uma congregação, sim, um povo numeroso.

[NOTE]
====
. “Babilônia”, LXXVg; MTSy: “Babel”.
====

[[v26-26-8]]

^<<v26-26-8,8>>^ Ele matará tuas^&#42;1^ aldeias dependentes no campo, sim, à espada, e terá de fazer contra ti um muro de sítio, e levantar contra ti um aterro de sítio, e erguer contra ti um escudo grande;

[NOTE]
====
. “Tuas”, hebr. fem. sing., referindo-se a “Tiro”.
====

[[v26-26-9]]

^<<v26-26-9,9>>^ e dirigirá o impacto da sua máquina de assalto contra as tuas muralhas e demolirá as tuas torres, com as suas espadas.

[[v26-26-10]]

^<<v26-26-10,10>>^ Devido à massa movimentada de seus cavalos, cobrir-te-á a poeira deles. Devido ao ruído do cavalariano, e da roda, e do carro de guerra, tremerão as tuas muralhas, quando ele entrar pelos teus portões, como nos casos de se entrar numa cidade aberta por brechas.

[[v26-26-11]]

^<<v26-26-11,11>>^ Pisará todas as tuas ruas com os cascos dos seus cavalos. À espada é que matará teu povo, e tuas próprias colunas de força cairão por terra.^&#42;1^

[NOTE]
====
. “Cairão por terra”, MVg; TLXXSy: “ele fará cair por terra”.
====

[[v26-26-12]]

^<<v26-26-12,12>>^ E eles hão de despojar-te dos teus recursos e saquear as tuas mercadorias, e derrubar as tuas muralhas, e eles demolirão as tuas casas desejáveis. E as tuas pedras, e o teu madeiramento, e o teu pó colocarão no próprio meio da água.’

[[v26-26-13]]

^<<v26-26-13,13>>^ “‘E eu vou fazer cessar o tumulto do teu canto e não se ouvirá mais o próprio som das tuas harpas.

[[v26-26-14]]

^<<v26-26-14,14>>^ Vou fazer de ti a lustrosa superfície escalvada dum rochedo. Enxugadouro de redes de arrasto é o que te tornarás. Nunca mais serás reconstruída; porque eu, Jeová, é que falei’, é a pronunciação do Soberano Senhor Jeová.

[[v26-26-15]]

^<<v26-26-15,15>>^ “Assim disse o Soberano Senhor Jeová a Tiro: ‘Ao ruído da tua queda, quando gemer o mortalmente ferido, quando houver no teu meio uma matança com chacina, não tremerão as ilhas?^&#42;1^

[NOTE]
====
. Ou “litorais”.
====

[[v26-26-16]]

^<<v26-26-16,16>>^ E todos os maiorais do mar hão de descer dos seus tronos e tirar as suas túnicas sem mangas, e eles despirão as suas próprias vestes bordadas. Vestir-se-ão de tremores. Sentar-se-ão na terra e certamente tremerão a cada instante e olharão espantados para ti.

[[v26-26-17]]

^<<v26-26-17,17>>^ E terão de levantar sobre ti uma endecha e dizer-te:
“‘“Como pereceste, tu que costumavas ser habitada desde os mares,^&#42;1^ ó cidade louvada, que te tornaste forte no mar, ela e os que habitavam nela, os que deram seu terror a todos os habitantes [da terra]!^&#42;2^

[NOTE]
====
. Segundo M; Sy: “ó habitante [hebr. fem.] dos mares”; Vg: “tu que moras no mar”.
. Lit.: “dela”.
====

[[v26-26-18]]

^<<v26-26-18,18>>^ Agora tremerão as ilhas no dia da tua queda. E as ilhas no mar terão de ficar perturbadas devido à tua saída.”’

[[v26-26-19]]

^<<v26-26-19,19>>^ “Pois assim disse o Soberano Senhor Jeová: ‘Quando eu fizer de ti uma cidade devastada, igual às cidades que realmente não são habitadas, quando [eu] fizer subir sobre ti a água de profundeza^&#42;1^ e tiveres sido coberta por vastas águas,

[NOTE]
====
. Ou “águas empoladas”. Hebr.: tehóhm; LXXVg: “abismo”. Veja Gên 1:2 n.: “profundeza”.
====

[[v26-26-20]]

^<<v26-26-20,20>>^ também vou fazer-te descer com os que descem ao poço, ao povo de há muito tempo, e vou fazer-te morar na terra mais baixa, igual aos lugares devastados por muito tempo, com os que descem ao poço, para que não sejas habitada; e vou pôr um ornato na terra dos viventes.

[[v26-26-21]]

^<<v26-26-21,21>>^ “‘Terrores repentinos é o que farei de ti, e não existirás; e serás procurada, mas não serás mais achada por tempo indefinido’, é a pronunciação do Soberano Senhor Jeová.”

'''

xref:026-ezequiel/026-ezequiel-025.adoc#v26-25-0[&#60; Capítulo Anterior] | <<v26-26-0,Topo>> | xref:026-ezequiel/026-ezequiel-027.adoc#v26-27-0[Próximo Capítulo &#62;]