include::./index.adoc[]

[[v26-34-0]]
=== Ezequiel, 34
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v26-34-1]]

^<<v26-34-1,1>>^ E continuou a vir a haver para mim a palavra de Jeová, dizendo:

[[v26-34-2]]

^<<v26-34-2,2>>^ “Filho do homem, profetiza contra os pastores de Israel. Profetiza, e tens de dizer-lhes, aos pastores: ‘Assim disse o Soberano Senhor Jeová: “Ai dos pastores de Israel, que foram tornar-se apascentadores^&#42;1^ de si mesmos! Não é ao rebanho que os pastores devem apascentar?

[NOTE]
====
. Ou “pastores”.
====

[[v26-34-3]]

^<<v26-34-3,3>>^ A gordura é o que comeis e com lã é que vestis a vós mesmos. Abateis o animal gordo. Não apascentais o próprio rebanho.^&#42;1^

[NOTE]
====
. Ou “as ovelhas”. Hebr.: hats·tsó’n.
====

[[v26-34-4]]

^<<v26-34-4,4>>^ Não fortalecestes as adoentadas, e não curastes a doentia, e não pensastes a quebrada, e não trouxestes de volta a dispersada, e não procurastes a perdida,^&#42;1^ porém, mantiveste-as em sujeição com severidade, sim, com tirania.

[NOTE]
====
. Lit.: “a que perece”.
====

[[v26-34-5]]

^<<v26-34-5,5>>^ E aos poucos foram espalhadas por não haver pastor, de modo que se tornaram alimento de toda fera do campo e continuaram a ser espalhadas.

[[v26-34-6]]

^<<v26-34-6,6>>^ Minhas ovelhas^&#42;1^ continuaram a perder-se em todos os montes e em todo morro alto; e minhas ovelhas foram espalhadas sobre a superfície inteira da terra, sem haver quem [as] buscasse e sem haver quem [as] procurasse.

[NOTE]
====
. Ou “Meu rebanho”. Hebr.: tso’·ní.
====

[[v26-34-7]]

^<<v26-34-7,7>>^ “‘“Portanto, pastores, ouvi a palavra de Jeová:

[[v26-34-8]]

^<<v26-34-8,8>>^ ‘“Assim como vivo”, é a pronunciação do Soberano Senhor Jeová, “por certo, visto que as minhas ovelhas se tornaram algo a ser saqueado e minhas ovelhas continuaram a ser alimento para toda fera do campo, por não haver pastor, e meus pastores não buscaram as minhas ovelhas, mas os pastores continuaram a apascentar a si mesmos e não apascentaram as minhas próprias ovelhas”’,

[[v26-34-9]]

^<<v26-34-9,9>>^ por isso, pastores, ouvi a palavra de Jeová.

[[v26-34-10]]

^<<v26-34-10,10>>^ Assim disse o Soberano Senhor Jeová: ‘Eis que sou contra os pastores, e certamente exigirei de volta as minhas ovelhas da sua mão e os farei cessar de apascentar^&#42;1^ as [minhas] ovelhas, e os pastores não mais se apascentarão a si mesmos; e vou livrar as minhas ovelhas da sua boca e elas não se tornarão alimento para eles.’”

[NOTE]
====
. Ou “pastorear”.
====

[[v26-34-11]]

^<<v26-34-11,11>>^ “‘Pois assim disse o Soberano Senhor Jeová: “Eis aqui estou, eu mesmo, e vou buscar as minhas ovelhas e cuidar delas.

[[v26-34-12]]

^<<v26-34-12,12>>^ Com o cuidado de alguém que apascenta a sua grei no dia em que chega a estar no meio das suas ovelhas que foram espalhadas, assim cuidarei das minhas ovelhas; e vou livrá-las de todos os lugares aos quais foram espalhadas no dia de nuvens e de densas trevas.

[[v26-34-13]]

^<<v26-34-13,13>>^ E vou fazê-las sair dentre os povos e reuni-las das terras, e vou fazê-las chegar ao seu solo e apascentá-las nos montes de Israel, junto aos regos e junto a todos os lugares de morada da terra.

[[v26-34-14]]

^<<v26-34-14,14>>^ Apascentá-las-ei num bom pasto e seu lugar de permanência virá a estar nos montes altos de Israel. Ali se deitarão num bom lugar de permanência e pastarão num pasto gordo sobre os montes de Israel.”

[[v26-34-15]]

^<<v26-34-15,15>>^ “‘“Eu mesmo apascentarei as minhas ovelhas^&#42;1^ e eu mesmo as farei deitar-se”, é a pronunciação do Soberano Senhor Jeová.

[NOTE]
====
. Veja v. 6 n.
====

[[v26-34-16]]

^<<v26-34-16,16>>^ “Procurarei a perdida^&#42;1^ e trarei de volta a dispersa, e pensarei a quebrada e fortalecerei a doentia, mas aniquilarei a gorda e a forte. A esta^&#42;2^ apascentarei com julgamento.”^&#42;3^

[NOTE]
====
. Lit.: “a que perece”.
. “Esta.” Lit.: “ela”, M; LXXSyVg: “elas”.
. Ou “com justiça”. Hebr.: vemish·pát.
====

[[v26-34-17]]

^<<v26-34-17,17>>^ “‘E quanto a vós, minhas ovelhas, assim disse o Soberano Senhor Jeová: “Eis que julgo entre ovídeo e ovídeo,^&#42;1^ entre os carneiros e os cabritos.

[NOTE]
====
. Lit.: “entre ovídeo para o ovídeo”. Hebr.: behn-séh la·séh.
====

[[v26-34-18]]

^<<v26-34-18,18>>^ É algo de somenos importância para vós apascentardes a vós mesmos no melhor dos pastos,^&#42;1^ mas pisardes o resto dos vossos pastos com os vossos pés, e beberdes água pura,^&#42;2^ mas sujardes a que sobra, batendo com os vossos próprios pés?

[NOTE]
====
. Lit.: “na boa pastagem”.
. Ou “assentada”.
====

[[v26-34-19]]

^<<v26-34-19,19>>^ E quanto às minhas ovelhas, devem elas pastar no pasto pisado pelos vossos pés e devem elas beber a água tornada suja pelo bater de vossos pés?”

[[v26-34-20]]

^<<v26-34-20,20>>^ “‘Portanto, assim lhes disse o Soberano Senhor Jeová: “Eis aqui estou, eu mesmo, e hei de julgar entre o ovídeo^&#42;1^ gordo e o ovídeo magro,

[NOTE]
====
. “Ovídeo.” Hebr.: seh, sing.
====

[[v26-34-21]]

^<<v26-34-21,21>>^ visto que continuastes a empurrar com o lado e com o ombro, e visto que continuastes a marrar com os vossos chifres a todas as adoentadas até que as tínheis espalhado para fora.

[[v26-34-22]]

^<<v26-34-22,22>>^ E eu vou salvar as minhas ovelhas^&#42;1^ e elas não mais se tornarão algo a ser saqueado; e vou julgar entre ovídeo e ovídeo.^&#42;2^

[NOTE]
====
. Ou “o meu rebanho”. Hebr.: letso’·ní.
. Veja v. 17 n.
====

[[v26-34-23]]

^<<v26-34-23,23>>^ E vou suscitar sobre elas um só pastor e ele terá de apascentá-las,^&#42;1^ sim, meu servo Davi. Ele mesmo as apascentará e ele mesmo se tornará seu pastor.

[NOTE]
====
. Ou “pastoreá-las”.
====

[[v26-34-24]]

^<<v26-34-24,24>>^ E eu mesmo, Jeová, me tornarei seu Deus,^&#42;1^ e meu servo Davi, maioral^&#42;2^ no meio delas. Eu, Jeová, é que falei.

[NOTE]
====
. Lit.: “para eles para Deus”. Hebr.: la·hém lE’·lo·hím.
. Ou “nase”.
====

[[v26-34-25]]

^<<v26-34-25,25>>^ “‘“E vou concluir^&#42;1^ com elas um pacto de paz, e hei de fazer cessar no país a fera nociva, e elas realmente morarão no ermo em segurança e dormirão nas florestas.

[NOTE]
====
. Lit.: “cortar”.
====

[[v26-34-26]]

^<<v26-34-26,26>>^ E delas e dos arredores do meu morro vou fazer uma bênção e vou fazer as chuvadas descer no seu tempo. Chuvadas de bênção virá a haver.

[[v26-34-27]]

^<<v26-34-27,27>>^ E a árvore do campo terá de dar seu fruto e a própria terra dará a sua produção, e mostrarão estar realmente em segurança no seu solo. E terão de saber que eu sou Jeová, quando eu quebrar os paus do seu jugo e eu as tiver livrado da mão dos que as tinham escravizado.

[[v26-34-28]]

^<<v26-34-28,28>>^ E não mais se tornarão para as nações algo a ser saqueado; e quanto à fera da terra, não as devorará, e elas morarão realmente em segurança, sem que alguém [as] faça tremer.

[[v26-34-29]]

^<<v26-34-29,29>>^ “‘“E vou suscitar para elas a plantação de um nome,^&#42;1^ e elas não se tornarão mais as que são tiradas pela fome na terra e não mais levarão humilhação da parte das nações.

[NOTE]
====
. Lit.: “fama; renome”.
====

[[v26-34-30]]

^<<v26-34-30,30>>^ ‘E terão de saber que eu, Jeová, seu Deus, estou com elas e que são meu povo, a casa de Israel’, é a pronunciação do Soberano Senhor Jeová.”’

[[v26-34-31]]

^<<v26-34-31,31>>^ “‘E no que se refere a vós,^&#42;1^ minhas ovelhas,^&#42;2^ ovelhas do meu pasto, vós^&#42;3^ sois homens terrenos.^&#42;4^ Eu sou vosso Deus’, é a pronunciação do Soberano Senhor Jeová.”

[NOTE]
====
. “Vós”, hebr. fem. pl.
. Veja v. 6 n.
. “Vós”, hebr. masc. pl.
. “Homens terrenos.” Hebr.: ’a·dhám.
====

'''

xref:026-ezequiel/026-ezequiel-033.adoc#v26-33-0[&#60; Capítulo Anterior] | <<v26-34-0,Topo>> | xref:026-ezequiel/026-ezequiel-035.adoc#v26-35-0[Próximo Capítulo &#62;]