include::./index.adoc[]

[[v26-48-0]]
=== Ezequiel, 48
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v26-48-1]]

^<<v26-48-1,1>>^ “E estes são os nomes das tribos. Desde a extremidade setentrional, do lado junto ao caminho de Hetlom até a entrada de Hamate, Hazar-Enã, o termo de Damasco para o norte, do lado de Hamate; e terá de mostrar ter uma banda oriental [e] a ocidental, Dã, uma [parte].

[[v26-48-2]]

^<<v26-48-2,2>>^ E contígua ao termo de Dã, desde a banda oriental até a banda ocidental, Aser, uma.

[[v26-48-3]]

^<<v26-48-3,3>>^ E contígua ao termo de Aser, desde a banda oriental até a banda ocidental, Naftali, uma.

[[v26-48-4]]

^<<v26-48-4,4>>^ E contígua ao termo de Naftali, desde a banda oriental até a banda ocidental, Manassés, uma.

[[v26-48-5]]

^<<v26-48-5,5>>^ E contígua ao termo de Manassés, desde a banda oriental até a banda ocidental, Efraim, uma.

[[v26-48-6]]

^<<v26-48-6,6>>^ E contígua ao termo de Efraim, desde a banda oriental, sim, até a banda ocidental, Rubem, uma.

[[v26-48-7]]

^<<v26-48-7,7>>^ E contígua ao termo de Rubem, desde a banda oriental até a banda ocidental, Judá, uma.

[[v26-48-8]]

^<<v26-48-8,8>>^ E contígua ao termo de Judá, desde a banda oriental até a banda ocidental, a contribuição que contribuireis deve mostrar ter vinte e cinco mil [côvados] de largura e [o] comprimento segundo uma das partes, desde o termo oriental até o termo ocidental. E o santuário^&#42;1^ terá de vir a estar no seu meio.

[NOTE]
====
. “O santuário.” Hebr.: ham·miq·dásh; gr.: to há·gi·on; lat.: sanc·tu·á·ri·um.
====

[[v26-48-9]]

^<<v26-48-9,9>>^ “Quanto à contribuição que deveis contribuir a Jeová, terá [o] comprimento de vinte e cinco mil [côvados] e [a] largura de dez mil.

[[v26-48-10]]

^<<v26-48-10,10>>^ E [pertencente] a estes deve vir a haver a contribuição sagrada para os sacerdotes, ao norte vinte e cinco mil [côvados], e ao oeste a largura de dez mil, e ao leste a largura de dez mil, e ao sul o comprimento de vinte e cinco mil. E o santuário de Jeová^&#42;1^ terá de vir a estar no seu meio.

[NOTE]
====
. “O santuário de Jeová.” Hebr.: miq·dash-Yehwáh; lat.: sanc·tu·á·ri·um Dó·mi·ni; LXX: “o monte de coisas santas”.
====

[[v26-48-11]]

^<<v26-48-11,11>>^ Será para os sacerdotes, para os santificados dentre os filhos de Zadoque, que cuidaram da obrigação para comigo, que não se transviaram quando os filhos de Israel se transviaram, assim como os levitas se transviaram.

[[v26-48-12]]

^<<v26-48-12,12>>^ E terão de vir a ter uma contribuição da contribuição de terra como algo santíssimo no termo dos levitas.

[[v26-48-13]]

^<<v26-48-13,13>>^ “E os levitas devem ter logo anexo ao território dos sacerdotes vinte e cinco mil [côvados] de comprimento e dez mil de largura; o comprimento inteiro sendo de vinte e cinco mil e a largura de dez mil.

[[v26-48-14]]

^<<v26-48-14,14>>^ E não devem vender nenhuma [parte] dela, nem se deve fazer uma troca, nem se deve fazer que a [parte] mais seleta da terra passe [deles para outro]; pois é algo sagrado para Jeová.

[[v26-48-15]]

^<<v26-48-15,15>>^ “Quanto aos cinco mil [côvados] que sobram na largura ao longo dos vinte e cinco mil, são algo profano para a cidade, para morada e para pastio. E a cidade terá de vir a estar no seu meio.

[[v26-48-16]]

^<<v26-48-16,16>>^ E estas são as medidas [da cidade]:^&#42;1^ a banda setentrional, quatro mil e quinhentos [côvados], e a banda meridional, quatro mil e quinhentos, e a banda oriental, quatro mil e quinhentos, e a banda ocidental, quatro mil e quinhentos.

[NOTE]
====
. Lit.: “dela”, hebr. fem., referindo-se à “cidade”, hebr. fem.
====

[[v26-48-17]]

^<<v26-48-17,17>>^ E a cidade tem de vir a ter um pastio, ao norte duzentos e cinqüenta [côvados], e ao sul duzentos e cinqüenta, e ao leste duzentos e cinqüenta, e ao oeste duzentos e cinqüenta.

[[v26-48-18]]

^<<v26-48-18,18>>^ “E o que sobrar no comprimento será exatamente como a contribuição sagrada, dez mil [côvados] ao leste, e dez mil ao oeste; e terá de mostrar ser exatamente como a contribuição sagrada, e seus produtos terão de vir a ser para pão para os que servem a cidade.

[[v26-48-19]]

^<<v26-48-19,19>>^ E os que servem a cidade, dentre todas as tribos de Israel, o cultivarão.

[[v26-48-20]]

^<<v26-48-20,20>>^ “A contribuição inteira é de vinte e cinco mil [côvados] por vinte e cinco mil. Deveis contribuir uma parte quadrada como contribuição sagrada com a propriedade da cidade.

[[v26-48-21]]

^<<v26-48-21,21>>^ “E o que sobrar pertencerá ao maioral, deste lado e daquele lado da contribuição sagrada e da propriedade da cidade, ao longo dos vinte e cinco mil [côvados] da contribuição até o termo oriental; e no oeste, ao longo dos vinte e cinco mil [côvados], até o termo ocidental. Exatamente como as partes, [assim será] para o maioral. E a contribuição sagrada e o santuário^&#42;1^ da Casa^&#42;2^ terão de vir a estar no meio dela.

[NOTE]
====
. “E o santuário da.” Hebr.: u·miq·dásh; gr.: ha·gí·a·sma; lat.: sanc·tu·á·ri·um.
. “Da Casa”, M(hebr.: hab·bá·yith)TLXXSy; lat.: tém·pli.
====

[[v26-48-22]]

^<<v26-48-22,22>>^ “E no que se refere à propriedade dos levitas e à propriedade da cidade, deve vir a estar entre o que pertence ao maioral. Entre o termo de Judá e o termo de Benjamim deve vir a pertencer ao maioral.

[[v26-48-23]]

^<<v26-48-23,23>>^ “E quanto ao resto das tribos, desde a banda oriental até a banda ocidental, Benjamim, uma [parte].

[[v26-48-24]]

^<<v26-48-24,24>>^ E contígua ao termo de Benjamim, desde a banda oriental até a banda ocidental, Simeão, uma.

[[v26-48-25]]

^<<v26-48-25,25>>^ E contígua ao termo de Simeão, desde a banda oriental até a banda ocidental, Issacar, uma.

[[v26-48-26]]

^<<v26-48-26,26>>^ E contígua ao termo de Issacar, desde a banda oriental até a banda ocidental, Zebulão, uma.

[[v26-48-27]]

^<<v26-48-27,27>>^ E contígua ao termo de Zebulão, desde a banda oriental até a banda ocidental, Gade, uma.

[[v26-48-28]]

^<<v26-48-28,28>>^ E contígua ao termo de Gade, até a banda meridional,^&#42;1^ será para o sul;^&#42;2^ e o termo terá de mostrar ser desde Tamar até as águas de Meribate-Cades, até o vale de torrente, até o Grande Mar.

[NOTE]
====
. “Meridional.” Hebr.: né·ghev.
. “Para o sul.” Hebr.: teh·má·nah.
====

[[v26-48-29]]

^<<v26-48-29,29>>^ “Esta será a terra que fareis cair [por sortes] como herança para as tribos de Israel, e estas serão as suas partes”, é a pronunciação do Soberano Senhor Jeová.

[[v26-48-30]]

^<<v26-48-30,30>>^ “E estas serão as saídas da cidade: Na banda setentrional, quatro mil e quinhentos [côvados] será [a] medida.

[[v26-48-31]]

^<<v26-48-31,31>>^ “E os portões da cidade serão segundo os nomes das tribos de Israel, havendo três portões ao norte; o portão de Rubem, um; o portão de Judá, um; o portão de Levi, um.

[[v26-48-32]]

^<<v26-48-32,32>>^ “E na banda oriental haverá quatro mil e quinhentos [côvados] e três portões: sim, o portão de José, um; o portão de Benjamim, um; o portão de Dã, um.

[[v26-48-33]]

^<<v26-48-33,33>>^ “E a banda meridional será de quatro mil e quinhentos [côvados] em medida, com três portões: o portão de Simeão, um; o portão de Issacar, um; o portão de Zebulão, um.

[[v26-48-34]]

^<<v26-48-34,34>>^ “A banda ocidental será de quatro mil e quinhentos [côvados], havendo três portões: o portão de Gade, um; o portão de Aser, um; o portão de Naftali, um.

[[v26-48-35]]

^<<v26-48-35,35>>^ “Em contorno [haverá] dezoito mil [côvados]; e daquele dia em diante o nome da cidade será O Próprio Jeová Está Ali.”^&#42;1^

[NOTE]
====
. “O Próprio Jeová Está Ali.” Ou “Jeová-Samá”. Hebr.: Yehwáh Shám·mah; LXXAVg: “Jeová [Está] Ali.”
====

'''

xref:026-ezequiel/026-ezequiel-047.adoc#v26-47-0[&#60; Capítulo Anterior] | <<v26-48-0,Topo>> | xref:027-daniel/027-daniel-001.adoc#v27-1-0[Próximo Capítulo &#62;]