include::./index.adoc[]

[[v26-45-0]]
=== Ezequiel, 45
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v26-45-1]]

^<<v26-45-1,1>>^ “‘E quando loteardes a terra como herança, deveis oferecer uma contribuição a Jeová, uma porção santa da terra; quanto ao comprimento, terá vinte e cinco mil [côvados] de comprimento, e quanto à largura, dez^&#42;1^ mil. Será uma porção santa em todos os seus^&#42;2^ termos ao redor.

[NOTE]
====
. “Dez”, MTSyVg; LXX: “vinte”.
. “Seus”, hebr. fem., referindo-se à “contribuição”, hebr. fem.
====

[[v26-45-2]]

^<<v26-45-2,2>>^ Desta virá a haver para o lugar santo^&#42;1^ quinhentos por quinhentos, sendo quadrado em contorno; e terá cinqüenta côvados como pastio em cada lado.

[NOTE]
====
. “O lugar santo.” Hebr.: haq·qó·dhesh; gr.: ha·gí·a·sma.
====

[[v26-45-3]]

^<<v26-45-3,3>>^ E desta medida deves medir o comprimento de vinte e cinco mil e a largura de dez^&#42;1^ mil, e nela virá a haver o santuário,^&#42;2^ algo santíssimo.

[NOTE]
====
. “Dez”, MTSyVg; LXXA,B: “vinte”.
. “O santuário.” Hebr.: ham·miq·dásh.
====

[[v26-45-4]]

^<<v26-45-4,4>>^ Quanto à porção santa da terra, virá a ser para os próprios sacerdotes, os ministros do santuário, os que se chegam para ministrar a Jeová. E terá de mostrar-se para eles um lugar para casas e um lugar sagrado^&#42;1^ para o santuário.

[NOTE]
====
. “E um lugar sagrado.” Hebr.: u·miq·dásh; T: “um caminho pavimentado”.
====

[[v26-45-5]]

^<<v26-45-5,5>>^ “‘Haverá vinte e cinco mil de comprimento e dez mil de largura. Virá a ser dos levitas’, os ministros da casa. Terão como propriedade vinte refeitórios.

[[v26-45-6]]

^<<v26-45-6,6>>^ “‘E como propriedade da cidade dareis cinco mil de largura e vinte e cinco mil de comprimento, exatamente como a contribuição sagrada. Virá a pertencer a toda a casa de Israel.

[[v26-45-7]]

^<<v26-45-7,7>>^ “‘E para o maioral haverá deste e daquele lado da contribuição sagrada e da propriedade da cidade, além da contribuição sagrada e além da propriedade da cidade, algo no lado ocidental para o oeste e algo do lado oriental para o leste. E o comprimento será exatamente como o de um dos quinhões, desde o termo ocidental até o termo oriental.

[[v26-45-8]]

^<<v26-45-8,8>>^ Quanto à terra, tornar-se-á sua como propriedade em Israel. E meus maiorais não mais maltratarão meu povo, e darão a terra à casa de Israel com relação às suas tribos.’

[[v26-45-9]]

^<<v26-45-9,9>>^ “Assim disse o Soberano Senhor Jeová: ‘Já chega de vós, ó maiorais de Israel!’
“‘Removei a violência e a assolação, e praticai o próprio juízo e justiça. Retirai as vossas expropriações^&#42;1^ de cima do meu povo’, é a pronunciação do Soberano Senhor Jeová.

[NOTE]
====
. Ou “os vossos atos de expulsões”.
====

[[v26-45-10]]

^<<v26-45-10,10>>^ ‘Deveis vir a ter balança exata, e um efa exato, e um bato exato.

[[v26-45-11]]

^<<v26-45-11,11>>^ No que se refere ao efa e ao bato, deve vir a haver apenas uma só quantidade fixa, levando o bato^&#42;1^ um décimo de um ômer,^&#42;2^ e o décimo do ômer, um efa;^&#42;3^ quanto ao ômer, deve vir a haver sua quantidade exigida.

[NOTE]
====
. Uma medida de líquidos que equivalia a 22 l e correspondia ao efa, uma medida de secos.
. Um ômer equivalia a 220 l.
. Um efa equivalia a 22 l.
====

[[v26-45-12]]

^<<v26-45-12,12>>^ E o siclo^&#42;1^ é de vinte geras.^&#42;2^ Vinte siclos, vinte e cinco siclos, quinze siclos devem mostrar ser para vós o mané.’

[NOTE]
====
. Um siclo pesava 11,4 g.
. Um gera pesava 0,57 g.
====

[[v26-45-13]]

^<<v26-45-13,13>>^ “‘Esta é a contribuição que deveis oferecer: a sexta parte do efa do ômer de trigo e a sexta parte do efa do ômer de cevada;

[[v26-45-14]]

^<<v26-45-14,14>>^ e quanto à porção concedida de azeite, há o bato de azeite. O bato é o décimo do coro. Dez batos são um ômer; porque dez batos são um ômer.

[[v26-45-15]]

^<<v26-45-15,15>>^ E um ovídeo dentre o rebanho, dentre duzentos do gado^&#42;1^ de Israel, para a oferta de cereais, e para o holocausto, e para os sacrifícios de participação em comum, a fim de se fazer expiação por eles’, é a pronunciação do Soberano Senhor Jeová.

[NOTE]
====
. “Gado”, mediante uma correção do M; ou, possivelmente, para concordar com LXX: “famílias”; M: “[terra] bem irrigada”.
====

[[v26-45-16]]

^<<v26-45-16,16>>^ “‘No que se refere ao povo da terra,^&#42;1^ serão responsáveis por esta contribuição ao maioral em Israel.

[NOTE]
====
. Veja 7:27 n.
====

[[v26-45-17]]

^<<v26-45-17,17>>^ E ao maioral caberá [prover] os holocaustos, e a oferta de cereais, e a oferta de bebida durante as festividades, e durante as luas novas, e durante os sábados, durante todas as épocas festivas da casa de Israel. Será ele quem proverá a oferta pelo pecado, e a oferta de cereais, e o holocausto, e os sacrifícios de participação em comum, para se fazer expiação pela casa de Israel.’

[[v26-45-18]]

^<<v26-45-18,18>>^ “Assim disse o Soberano Senhor Jeová: ‘No primeiro [mês], no primeiro [dia] do mês, deves tomar um novilho, filho da manada, sadio, e tens de purificar de pecado o santuário.^&#42;1^

[NOTE]
====
. “O santuário.” Hebr.: ham·miq·dásh; gr.: há·gi·on; lat.: sanc·tu·á·ri·um.
====

[[v26-45-19]]

^<<v26-45-19,19>>^ E o sacerdote tem de tomar do sangue da oferta pelo pecado e pô-lo sobre a ombreira^&#42;1^ da Casa, e sobre os quatro cantos [da reentrância] da banda circundante do altar, e sobre a ombreira do portão do pátio interno.

[NOTE]
====
. “A ombreira da.” Hebr.: mezu·záth.
====

[[v26-45-20]]

^<<v26-45-20,20>>^ E assim farás no sétimo [dia] do mês, por causa de qualquer homem^&#42;1^ que cometa engano e por causa de qualquer inexperiente; e tereis de fazer expiação pela Casa.

[NOTE]
====
. Ou “por causa da pessoa”. Hebr.: me·’ísh.
====

[[v26-45-21]]

^<<v26-45-21,21>>^ “‘No primeiro [mês], no décimo quarto dia do mês, deve ocorrer para vós a páscoa. Sendo uma festividade, devem-se comer por sete dias pães não fermentados.^&#42;1^

[NOTE]
====
. Ou “pão não levedado (asmo; ázimo)”. Hebr.: mats·tsóhth.
====

[[v26-45-22]]

^<<v26-45-22,22>>^ E naquele dia o maioral tem de prover um novilho como oferta pelo pecado por si mesmo e por todo o povo da terra.

[[v26-45-23]]

^<<v26-45-23,23>>^ E para os sete dias da festividade deve prover como holocausto a Jeová sete novilhos e sete carneiros, sadios, diariamente, durante os sete dias, e como oferta pelo pecado, diariamente um bode dos caprídeos.

[[v26-45-24]]

^<<v26-45-24,24>>^ E como oferta de cereais deve prover um efa para o novilho e um efa para o carneiro, e quanto ao azeite, um him por efa.

[[v26-45-25]]

^<<v26-45-25,25>>^ “‘No sétimo [mês], no décimo quinto dia do mês, durante a festividade, deve prover tais para os sete dias, assim como a oferta pelo pecado, como o holocausto, e como a oferta de cereais, e como o azeite.’”

'''

xref:026-ezequiel/026-ezequiel-044.adoc#v26-44-0[&#60; Capítulo Anterior] | <<v26-45-0,Topo>> | xref:026-ezequiel/026-ezequiel-046.adoc#v26-46-0[Próximo Capítulo &#62;]