include::./index.adoc[]

[[v26-37-0]]
=== Ezequiel, 37
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v26-37-1]]

^<<v26-37-1,1>>^ A mão de Jeová veio a estar sobre mim, de modo que ele me levou para fora no espírito^&#42;1^ de Jeová e me pousou no meio do vale plano, e [este] estava cheio de ossos.

[NOTE]
====
. “No espírito de.” Hebr.: verú·ahh. Veja Gên 1:2 n.: “ativa”.
====

[[v26-37-2]]

^<<v26-37-2,2>>^ E fez-me passar por eles ao redor, e eis que havia muitíssimos na superfície do vale plano, e eis que estavam muito secos.

[[v26-37-3]]

^<<v26-37-3,3>>^ E ele começou a dizer-me: “Filho do homem, poderão reviver estes ossos?” A isto eu disse: “Soberano Senhor Jeová, tu mesmo o sabes muito bem.”

[[v26-37-4]]

^<<v26-37-4,4>>^ E ele prosseguiu, dizendo-me: “Profetiza a respeito destes ossos, e tens de dizer-lhes: ‘Ó ossos secos, ouvi a palavra de Jeová:

[[v26-37-5]]

^<<v26-37-5,5>>^ “‘Assim disse o Soberano Senhor Jeová a estes ossos: “Eis que introduzirei fôlego^&#42;1^ em vós e tereis de reviver.

[NOTE]
====
. “Fôlego.” Hebr.: rú·ahh. Veja Gên 1:2 n.: “ativa”.
====

[[v26-37-6]]

^<<v26-37-6,6>>^ E vou pôr tendões sobre vós e fazer que venha carne sobre vós, e vou revestir-vos de pele e pôr fôlego em vós, e tereis de reviver; e tereis de saber que eu sou Jeová.”’”

[[v26-37-7]]

^<<v26-37-7,7>>^ E eu profetizei assim como fora mandado. E assim que profetizei veio a haver um ruído, e eis que havia um [som] retininte, e os ossos começaram a chegar-se osso a osso.

[[v26-37-8]]

^<<v26-37-8,8>>^ E eu vi, e eis que vieram sobre eles os próprios tendões e a própria carne, e começaram a ser revestidos de pele por cima. Mas, quanto a fôlego, não havia neles nenhum.

[[v26-37-9]]

^<<v26-37-9,9>>^ E ele prosseguiu, dizendo-me: “Profetiza ao vento.^&#42;1^ Profetiza, ó filho do homem, e tens de dizer ao vento: ‘Assim disse o Soberano Senhor Jeová: “Entra dos quatro ventos, ó vento, e sopra sobre estes mortos para que revivam.”’”

[NOTE]
====
. “Ao vento.” Hebr.: ha·rú·ahh. Veja Gên 1:2 n.: “ativa”.
====

[[v26-37-10]]

^<<v26-37-10,10>>^ E profetizei assim como me mandara, e passou a entrar fôlego neles, e começaram a viver e a pôr-se de pé, uma força militar muitíssimo grande.

[[v26-37-11]]

^<<v26-37-11,11>>^ E ele prosseguiu, dizendo-me: “Filho do homem, no que se refere a estes ossos, são a casa inteira de Israel. Eis que estão dizendo: ‘Nossos ossos ficaram secos e nossa esperança pereceu. Fomos cerceados, ficando sozinhos.’

[[v26-37-12]]

^<<v26-37-12,12>>^ Por isso profetiza, e tens de dizer-lhes: ‘Assim disse o Soberano Senhor Jeová: “Eis que estou abrindo as vossas sepulturas e vou fazer-vos subir das vossas sepulturas, ó meu povo, e vou fazer-vos chegar ao solo de Israel.

[[v26-37-13]]

^<<v26-37-13,13>>^ E tereis de saber que eu sou Jeová, quando eu abrir as vossas sepulturas e quando vos fizer subir das vossas sepulturas, ó meu povo.”’

[[v26-37-14]]

^<<v26-37-14,14>>^ ‘E vou pôr em vós o meu espírito^&#42;1^ e tereis de reviver, e vou estabelecer-vos sobre o vosso solo; e tereis de saber que eu, Jeová, é que falei e fiz [isso]’, é a pronunciação de Jeová.”

[NOTE]
====
. “Meu espírito.” Hebr.: ru·hhí.
====

[[v26-37-15]]

^<<v26-37-15,15>>^ E continuou a vir a haver para mim a palavra de Jeová, dizendo:

[[v26-37-16]]

^<<v26-37-16,16>>^ “E quanto a ti, ó filho do homem, toma para ti uma vareta e escreve nela: ‘Para Judá e para os filhos de Israel, seus associados.’^&#42;1^ E toma outra vareta e escreve nela: ‘Para José, a vareta de Efraim, e para toda a casa de Israel, seus associados.’

[NOTE]
====
. “Associados”, MmargemTLXXSyVg; M: “associado”.
====

[[v26-37-17]]

^<<v26-37-17,17>>^ E faze chegar uma à outra para serem para ti uma só vareta, e elas realmente se tornarão uma só na tua mão.

[[v26-37-18]]

^<<v26-37-18,18>>^ E quando os filhos do teu povo começarem a dizer-te: ‘Não nos contarás o que significam estas coisas para ti?’

[[v26-37-19]]

^<<v26-37-19,19>>^ fala-lhes: ‘Assim disse o Soberano Senhor Jeová: “Eis que tomo a vareta de José, que está na mão de Efraim, e as tribos de Israel, seus associados, e vou pô-las sobre ela, isto é,^&#42;1^ [sobre] a vareta de Judá, e realmente farei delas uma só vareta e terão de tornar-se uma só na minha mão.”’

[NOTE]
====
. “Isto é.” Ou “com [a vareta]”.
====

[[v26-37-20]]

^<<v26-37-20,20>>^ E as varetas em que escreverás terão de vir a estar na tua mão diante dos seus olhos.

[[v26-37-21]]

^<<v26-37-21,21>>^ “E fala-lhes: ‘Assim disse o Soberano Senhor Jeová: “Eis que tomo os filhos de Israel dentre as nações às quais foram e vou reuni-los de todo o redor e trazê-los ao seu solo.

[[v26-37-22]]

^<<v26-37-22,22>>^ E realmente farei deles uma só nação no país, nos montes de Israel, e um só rei é o que todos eles virão a ter como rei, e não mais continuarão a ser duas nações, nem mais ficarão divididos em dois reinos.

[[v26-37-23]]

^<<v26-37-23,23>>^ E eles não mais se aviltarão com os seus ídolos sórdidos, e com as suas coisas repugnantes, e com todas as suas transgressões; e eu hei de salvá-los de todos os seus lugares de morada^&#42;1^ em que pecaram e vou purificá-los, e terão de tornar-se meu povo e eu mesmo me tornarei seu Deus.^&#42;2^

[NOTE]
====
. “Atos contra a lei”, LXX; Sym: “apostasias”.
. Lit.: “para eles para Deus”. Hebr.: la·hém lE’·lo·hím.
====

[[v26-37-24]]

^<<v26-37-24,24>>^ “‘“E meu servo Davi será rei sobre eles e todos eles virão a ter um só pastor; e andarão nas minhas decisões judiciais e guardarão os meus estatutos, e certamente os cumprirão.

[[v26-37-25]]

^<<v26-37-25,25>>^ E realmente hão de morar na terra que dei ao meu servo, a Jacó, na qual moravam os vossos antepassados, e realmente hão de morar nela, eles e seus filhos, e os filhos de seus filhos, por tempo indefinido, e Davi, meu servo, será seu maioral^&#42;1^ por tempo indefinido.

[NOTE]
====
. Ou “nase”. Hebr.: na·sí’; gr.: ár·khon; lat.: prín·ceps.
====

[[v26-37-26]]

^<<v26-37-26,26>>^ “‘“E vou concluir com eles um pacto de paz; um pacto de duração indefinida é que virá a haver com eles. E vou estabelecê-los e multiplicá-los, e vou pôr meu santuário no seu meio por tempo indefinido.

[[v26-37-27]]

^<<v26-37-27,27>>^ E meu tabernáculo virá realmente a estar sobre eles, e hei de tornar-me seu Deus e eles mesmos se tornarão meu povo.

[[v26-37-28]]

^<<v26-37-28,28>>^ E as nações terão de saber que eu, Jeová, estou santificando Israel, quando meu santuário vier a estar no seu meio por tempo indefinido.”’”

'''

xref:026-ezequiel/026-ezequiel-036.adoc#v26-36-0[&#60; Capítulo Anterior] | <<v26-37-0,Topo>> | xref:026-ezequiel/026-ezequiel-038.adoc#v26-38-0[Próximo Capítulo &#62;]