include::./index.adoc[]

[[v61-2-0]]
=== 2 Pedro, 2
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v61-2-1]]

^<<v61-2-1,1>>^ No entanto, houve também falsos profetas entre o povo, assim como haverá falsos instrutores entre vós. Estes mesmos introduzirão quietamente seitas^&#42;1^ destrutivas e repudiarão até mesmo o dono que os comprou, trazendo sobre si mesmos uma destruição veloz.

[NOTE]
====
. Ou “heresias”. Gr.: hai·ré·seis; lat.: séc·tas.
====

[[v61-2-2]]

^<<v61-2-2,2>>^ Outrossim, muitos seguirão os seus atos de conduta desenfreada,^&#42;1^ e, por causa destes, falar-se-á de modo ultrajante do caminho da verdade.

[NOTE]
====
. “Atos de conduta desenfreada.” Gr.: a·sel·geí·ais. Veja Gál 5:19 n.: “desenfreada”.
====

[[v61-2-3]]

^<<v61-2-3,3>>^ Explorar-vos-ão também em cobiça com palavras simuladas. Mas, quanto a eles, o julgamento, desde a antiguidade, não está avançando vagarosamente e a destruição deles não está cochilando.

[[v61-2-4]]

^<<v61-2-4,4>>^ Certamente, se Deus não se refreou de punir os anjos que pecaram, mas, lançando-os no Tártaro,^&#42;1^ entregou-os a covas de profunda escuridão, reservando-os para o julgamento;

[NOTE]
====
. Para um exame mais detido de “Tártaro”, veja Ap. 4D.
====

[[v61-2-5]]

^<<v61-2-5,5>>^ e ele não se refreou de punir um mundo antigo,^&#42;1^ mas preservou a Noé, pregador da justiça, junto com mais sete, quando trouxe um dilúvio^&#42;2^ sobre um mundo de pessoas ímpias;

[NOTE]
====
. Lit.: “arcaico”. Gr.: ar·khaí·ou.
. Ou “grande inundação; cataclismo”. Gr.: ka·ta·kly·smón; lat.: di·lú·vi·um.
====

[[v61-2-6]]

^<<v61-2-6,6>>^ e, reduzindo a cinzas as cidades de Sodoma e Gomorra, ele as condenou, estabelecendo para as pessoas ímpias^&#42;1^ um modelo das coisas que hão de vir;

[NOTE]
====
. Lit.: “os irreverentes”.
====

[[v61-2-7]]

^<<v61-2-7,7>>^ e ele livrou o justo Ló, a quem afligia grandemente que os que desafiavam a lei se entregavam à conduta desenfreada^&#42;1^ —

[NOTE]
====
. “Conduta desenfreada.” Lit.: “conduta lasciva”.
====

[[v61-2-8]]

^<<v61-2-8,8>>^ porque esse justo, pelo que via e ouvia de dia a dia, enquanto morava entre eles, atormentava a sua alma justa em razão das ações deles contra a lei —

[[v61-2-9]]

^<<v61-2-9,9>>^ Jeová^&#42;1^ sabe livrar da provação os de devoção piedosa, mas reservar os injustos para o dia do julgamento, para serem decepados,^&#42;2^

[NOTE]
====
. Veja Ap. 1D.
. Ou “atalhados”. Veja Mt 25:46.
====

[[v61-2-10]]

^<<v61-2-10,10>>^ porém, especialmente os que vão atrás da carne com o desejo de aviltá-la e que menosprezam^&#42;1^ o senhorio.
Atrevidos, obstinados, não tremem diante dos gloriosos,^&#42;2^ mas falam de modo ultrajante,

[NOTE]
====
. Lit.: “rebaixam mentalmente”.
. Lit.: “das glórias”.
====

[[v61-2-11]]

^<<v61-2-11,11>>^ ao passo que os anjos, embora sejam maiores em força e poder, não levantam contra eles nenhuma acusação em termos ultrajantes, [não o fazendo] de respeito por Jeová.^&#42;1^

[NOTE]
====
. “Por Jeová”, J7,8,13,16-18,22-24; אBC(gr.): Ky·rí·oi; AVgSyh omitem isso. Veja Ap. 1D.
====

[[v61-2-12]]

^<<v61-2-12,12>>^ Mas estes [homens], iguais a animais irracionais, nascidos naturalmente para serem apanhados e destruídos, nas coisas em que são ignorantes e falam de modo ultrajante, sofrerão a destruição até mesmo no seu próprio [proceder de] destruição,

[[v61-2-13]]

^<<v61-2-13,13>>^ fazendo a si mesmos injustiça em recompensa de fazerem injustiça.
Acham um prazer viver em luxo durante o dia. São manchas e máculas, entregando-se com deleite irrestrito aos seus ensinos enganosos,^&#42;1^ enquanto se banqueteiam convosco.

[NOTE]
====
. Ou “às suas dissipações”.
====

[[v61-2-14]]

^<<v61-2-14,14>>^ Eles têm olhos cheios de adultério^&#42;1^ e são incapazes de desistir do pecado, e engodam^&#42;2^ as almas instáveis. Eles têm um coração treinado na cobiça. São filhos amaldiçoados.

[NOTE]
====
. Lit.: “cheios de adúltera”.
. Lit.: “iscam”.
====

[[v61-2-15]]

^<<v61-2-15,15>>^ Abandonando a vereda reta, foram desencaminhados. Seguiram a vereda de Balaão, [filho] de Beor, que amava a recompensa de fazer injustiça,

[[v61-2-16]]

^<<v61-2-16,16>>^ mas ele recebeu uma repreensão pela sua própria violação daquilo que era direito.^&#42;1^ Um animal de carga, sem voz, fazendo pronunciação com voz de homem, impediu o proceder louco do profeta.

[NOTE]
====
. Lit.: “transgressão da lei”.
====

[[v61-2-17]]

^<<v61-2-17,17>>^ Estes são fontes sem água e brumas impelidas por uma tempestade violenta, e para eles tem sido reservado o negrume da escuridão.

[[v61-2-18]]

^<<v61-2-18,18>>^ Porque proferem expressões bombásticas de nenhum proveito, e, pelos desejos da carne e pelos hábitos desenfreados, engodam os que acabam de escapar dos que se comportam com erro.

[[v61-2-19]]

^<<v61-2-19,19>>^ Embora lhes prometam liberdade, eles mesmos existem como escravos da corrupção. Pois todo aquele que é vencido por outro é escravizado por este.^&#42;1^

[NOTE]
====
. Ou “é vencido por algo é escravizado por isso”.
====

[[v61-2-20]]

^<<v61-2-20,20>>^ Certamente, se eles, depois de terem escapado dos aviltamentos do mundo pelo conhecimento exato do Senhor e Salvador Jesus Cristo, ficam novamente envolvidos^&#42;1^ nestas mesmas coisas e são vencidos, as condições derradeiras tornaram-se piores para eles do que as primeiras.

[NOTE]
====
. Lit.: “tendo ficado entretecidos”.
====

[[v61-2-21]]

^<<v61-2-21,21>>^ Porque teria sido melhor para eles que não tivessem conhecido de modo exato a vereda da justiça, do que, depois de a terem conhecido de modo exato, se desviarem do mandamento santo que lhes foi entregue.

[[v61-2-22]]

^<<v61-2-22,22>>^ Com eles aconteceu o que diz o provérbio verdadeiro: “O cão voltou ao seu próprio vômito e a porca lavada a revolver-se no lamaçal.”

'''

xref:061-2-pedro/061-2-pedro-001.adoc#v61-1-0[&#60; Capítulo Anterior] | <<v61-2-0,Topo>> | xref:061-2-pedro/061-2-pedro-003.adoc#v61-3-0[Próximo Capítulo &#62;]