include::./index.adoc[]

[[v61-1-0]]
=== 2 Pedro, 1
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v61-1-1]]

^<<v61-1-1,1>>^ Simão Pedro, escravo e apóstolo de Jesus Cristo, aos que obtiveram uma fé, tida por igual privilégio como a nossa, pela justiça de nosso Deus^&#42;1^ e [do] Salvador Jesus Cristo:^&#42;2^

[NOTE]
====
. “Nosso Deus”, ABVg; אSyh: “nosso Senhor”.
. “De nosso Deus e do Salvador Jesus Cristo”, em harmonia com a diferenciação entre Deus e Jesus no v. que segue. Veja Ap. 6E.
====

[[v61-1-2]]

^<<v61-1-2,2>>^ Benignidade imerecida e paz vos sejam aumentadas pelo conhecimento exato de Deus e de Jesus,^&#42;1^ nosso Senhor,

[NOTE]
====
. Veja Ap. 6E.
====

[[v61-1-3]]

^<<v61-1-3,3>>^ visto que o seu divino poder^&#42;1^ nos tem dado gratuitamente todas as coisas que se referem à vida e à devoção piedosa, por intermédio do conhecimento exato daquele que nos chamou pela glória e virtude.

[NOTE]
====
. “Seu divino poder”, אAB; J18: “Jeová, pelo seu poder.”
====

[[v61-1-4]]

^<<v61-1-4,4>>^ Por intermédio destas coisas ele nos tem dado gratuitamente as promessas preciosas e mui grandiosas, para que, por intermédio delas, vos tornásseis parceiros na natureza divina,^&#42;1^ tendo escapado da corrupção que há no mundo pela concupiscência.

[NOTE]
====
. “Na natureza divina.” Gr.: theí·as . . . fý·se·os.
====

[[v61-1-5]]

^<<v61-1-5,5>>^ Sim, por esta mesma razão, por contribuirdes em resposta todo esforço sério, supri à vossa fé a virtude, à [vossa] virtude, o conhecimento,

[[v61-1-6]]

^<<v61-1-6,6>>^ ao [vosso] conhecimento, o autodomínio, ao [vosso] autodomínio, a perseverança, à [vossa] perseverança, a devoção piedosa,

[[v61-1-7]]

^<<v61-1-7,7>>^ à [vossa] devoção piedosa, a afeição fraternal, à [vossa] afeição fraternal, o amor.

[[v61-1-8]]

^<<v61-1-8,8>>^ Pois, se estas coisas existirem em vós e transbordarem, impedirão que sejais quer inativos quer infrutíferos^&#42;1^ no que se refere ao conhecimento exato de nosso Senhor Jesus Cristo.

[NOTE]
====
. Ou “farão com que não sejais nem inativos, nem infrutíferos”.
====

[[v61-1-9]]

^<<v61-1-9,9>>^ Porque, se essas coisas não estiverem presentes em alguém, ele é cego, fechando os seus olhos [à luz],^&#42;1^ e chegou a esquecer a sua purificação de seus pecados de há muito.

[NOTE]
====
. Ou “cego, vendo somente o que está perto”.
====

[[v61-1-10]]

^<<v61-1-10,10>>^ Por esta razão, irmãos, fazei tanto mais o vosso máximo para vos assegurar da vossa chamada e escolha; pois, se persistirdes em fazer estas coisas, de nenhum modo falhareis jamais.

[[v61-1-11]]

^<<v61-1-11,11>>^ De fato, assim vos será ricamente suprida a entrada no reino eterno de nosso Senhor e Salvador Jesus Cristo.

[[v61-1-12]]

^<<v61-1-12,12>>^ Por esta razão, estarei sempre disposto a lembrar-vos estas coisas, embora [as] saibais e estejais firmemente estabelecidos na verdade que está presente [em vós].

[[v61-1-13]]

^<<v61-1-13,13>>^ Mas, eu acho direito, enquanto estiver nesta habitação, acordar-vos por vos fazer recordar,

[[v61-1-14]]

^<<v61-1-14,14>>^ sabendo que em breve^&#42;1^ se há de eliminar a minha habitação, assim como também o nosso Senhor Jesus Cristo me indicou.

[NOTE]
====
. Ou “rapidamente”.
====

[[v61-1-15]]

^<<v61-1-15,15>>^ Assim, farei também o máximo, em toda ocasião, para que, depois da minha partida, vós mesmos possais fazer menção destas coisas.^&#42;1^

[NOTE]
====
. Ou “relembrar essas coisas”.
====

[[v61-1-16]]

^<<v61-1-16,16>>^ Não, não foi por seguirmos histórias falsas, engenhosamente inventadas, que vos familiarizamos com o poder e a presença^&#42;1^ de nosso Senhor Jesus Cristo, mas foi por nos termos tornado testemunhas oculares da sua magnificência.

[NOTE]
====
. Veja Ap. 5B.
====

[[v61-1-17]]

^<<v61-1-17,17>>^ Pois ele recebeu de Deus, o Pai, honra e glória, quando pela glória magnificente lhe foram dirigidas palavras tais como estas:^&#42;1^ “Este é meu Filho, meu amado, a quem eu mesmo tenho aprovado.”^&#42;2^

[NOTE]
====
. “Palavras tais como estas.” Lit.: “tal voz”.
. Lit.: “achei bom”.
====

[[v61-1-18]]

^<<v61-1-18,18>>^ Sim, estas palavras^&#42;1^ nós ouvimos dirigidas desde o céu, enquanto estávamos com ele no monte santo.

[NOTE]
====
. Lit.: “esta voz”.
====

[[v61-1-19]]

^<<v61-1-19,19>>^ Por conseguinte, temos a palavra profética tanto mais assegurada; e fazeis bem em prestar atenção a ela como a uma lâmpada que brilha em lugar escuro, até que amanheça o dia e se levante a estrela da alva,^&#42;1^ em vossos corações.

[NOTE]
====
. Lit.: “porta-luz”.
====

[[v61-1-20]]

^<<v61-1-20,20>>^ Pois sabeis primeiramente isto, que nenhuma profecia da Escritura procede de qualquer interpretação particular.^&#42;1^

[NOTE]
====
. Ou “procede de revelação [ou: divulgação] particular”.
====

[[v61-1-21]]

^<<v61-1-21,21>>^ Porque a profecia nunca foi produzida pela vontade do homem, mas os homens falaram da parte de Deus conforme eram movidos por espírito santo.

'''

xref:060-1-pedro/060-1-pedro-005.adoc#v60-5-0[&#60; Capítulo Anterior] | <<v61-1-0,Topo>> | xref:061-2-pedro/061-2-pedro-002.adoc#v61-2-0[Próximo Capítulo &#62;]