include::./index.adoc[]

[[v61-3-0]]
=== 2 Pedro, 3
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v61-3-1]]

^<<v61-3-1,1>>^ Amados, esta é agora a segunda carta que vos escrevo, sendo que nela, como na minha primeira, estou acordando as vossas claras faculdades de pensar^&#42;1^ por meio dum lembrete,

[NOTE]
====
. Lit.: “percepção mental”.
====

[[v61-3-2]]

^<<v61-3-2,2>>^ para que vos lembreis das declarações anteriormente feitas pelos santos profetas e do mandamento do Senhor e Salvador por intermédio dos vossos apóstolos.

[[v61-3-3]]

^<<v61-3-3,3>>^ Pois sabeis primeiramente isto, que nos últimos dias virão ridicularizadores^&#42;1^ com os seus escárnios, procedendo segundo os seus próprios desejos

[NOTE]
====
. Lit.: “jogadores do esporte [da zombaria]”.
====

[[v61-3-4]]

^<<v61-3-4,4>>^ e dizendo: “Onde está essa prometida presença^&#42;1^ dele? Ora, desde o dia em que os nossos antepassados adormeceram [na morte], todas as coisas estão continuando exatamente como desde o princípio da criação.”

[NOTE]
====
. Veja Ap. 5B.
====

[[v61-3-5]]

^<<v61-3-5,5>>^ Pois, segundo o desejo deles, escapa-lhes este fato, de que desde a antiguidade havia céus, e uma terra sobressaindo compactamente à água e no meio da água, pela palavra de Deus;

[[v61-3-6]]

^<<v61-3-6,6>>^ e, por esses [meios], o mundo daquele tempo sofreu destruição, ao ser inundado pela água.

[[v61-3-7]]

^<<v61-3-7,7>>^ Mas, pela mesma palavra, os céus e a terra que agora existem estão sendo guardados para o fogo e estão sendo reservados para o dia do julgamento e da destruição dos homens ímpios.

[[v61-3-8]]

^<<v61-3-8,8>>^ No entanto, não vos escape este único fato, amados, que um só dia é para Jeová^&#42;1^ como mil anos, e mil anos, como um só dia.

[NOTE]
====
. Veja Ap. 1D.
====

[[v61-3-9]]

^<<v61-3-9,9>>^ Jeová^&#42;1^ não é vagaroso com respeito à sua promessa, conforme alguns consideram a vagarosidade, mas ele é paciente convosco, porque não deseja que alguém seja destruído, mas deseja que todos alcancem o arrependimento.^&#42;2^

[NOTE]
====
. Veja Ap. 1D.
. Lit.: “mudança de idéia”. Gr.: me·tá·noi·an.
====

[[v61-3-10]]

^<<v61-3-10,10>>^ Contudo, o dia de Jeová^&#42;1^ virá como ladrão, sendo que nele passarão os céus com som sibilante, mas os elementos,^&#42;2^ estando intensamente quentes, serão dissolvidos,^&#42;3^ e a terra e as obras nela serão descobertas.^&#42;4^

[NOTE]
====
. Veja Ap. 1D.
. Ou “os corpos celestes”. Gr.: stoi·kheí·a.
. Lit.: “serão soltos”.
. “Serão descobertas”, אB; AVgc: “serão queimadas”.
====

[[v61-3-11]]

^<<v61-3-11,11>>^ Visto que todas estas coisas hão de ser assim dissolvidas, que sorte de pessoas deveis ser em atos santos de conduta e em ações de devoção piedosa,

[[v61-3-12]]

^<<v61-3-12,12>>^ aguardando e tendo bem em mente^&#42;1^ a presença^&#42;2^ do dia de Jeová,^&#42;3^ pelo qual [os] céus, estando incendiados, serão dissolvidos, e [os] elementos, estando intensamente quentes, se derreterão!

[NOTE]
====
. “Tendo bem em mente.” Ou “desejando ardentemente”. Lit.: “apressando”.
. Veja Ap. 5B.
. “De Jeová”, J7,8,17; CVgc(gr.): tou Ky·rí·ou; אABVgSyh: “de Deus”. Veja Ap. 1D.
====

[[v61-3-13]]

^<<v61-3-13,13>>^ Mas, há novos céus e uma nova terra que aguardamos segundo a sua promessa, e nestes há de morar a justiça.

[[v61-3-14]]

^<<v61-3-14,14>>^ Por isso, amados, visto que aguardais estas coisas, fazei o máximo para serdes finalmente achados por ele sem mancha nem mácula, e em paz.

[[v61-3-15]]

^<<v61-3-15,15>>^ Além disso, considerai a paciência^&#42;1^ de nosso Senhor como salvação, assim como vos escreveu também o nosso amado irmão Paulo, segundo a sabedoria que lhe foi dada,

[NOTE]
====
. Lit.: “longura de espírito; longanimidade”.
====

[[v61-3-16]]

^<<v61-3-16,16>>^ falando destas coisas, como faz também em todas as [suas] cartas. Nelas, porém, há algumas coisas difíceis de entender, as quais os não ensinados^&#42;1^ e instáveis estão deturpando,^&#42;2^ assim como fazem também com o resto das Escrituras, para a sua própria destruição.

[NOTE]
====
. Lit.: “indoutos” ou “ignorantes”.
. Lit.: “distorcendo”.
====

[[v61-3-17]]

^<<v61-3-17,17>>^ Vós, portanto, amados, tendo este conhecimento adiantado, guardai-vos para que não sejais desviados com eles pelo erro dos que desafiam a lei^&#42;1^ e não decaiais da vossa firmeza.

[NOTE]
====
. Lit.: “dos ilegais”.
====

[[v61-3-18]]

^<<v61-3-18,18>>^ Não, mas prossegui crescendo na benignidade imerecida e no conhecimento de nosso Senhor e Salvador Jesus Cristo. A ele [seja dada] a glória tanto agora como até o dia da eternidade.

'''

xref:061-2-pedro/061-2-pedro-002.adoc#v61-2-0[&#60; Capítulo Anterior] | <<v61-3-0,Topo>> | xref:062-1-joao/062-1-joao-001.adoc#v62-1-0[Próximo Capítulo &#62;]