include::./index.adoc[]

[[v38-3-0]]
=== Zacarias, 3
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v38-3-1]]

^<<v38-3-1,1>>^ E ele passou a mostrar-me Josué,^&#42;1^ o sumo sacerdote, de pé perante o anjo^&#42;2^ de Jeová, e Satanás^&#42;3^ de pé à sua direita para se lhe opor.

[NOTE]
====
. “Josué.” Hebr.: Yehoh·shú·a‛; LXXVg: “Jesus”. Veja He 4:8 n.: “Josué”.
. Ou “o mensageiro”.
. Ou “e o Opositor”. Lit.: “e o Satanás”. Hebr.: wehas·Sa·tán; lat.: Sá·tan; gr.: Di·á·bo·los, “o Diabo”. Veja Jó 1:6 n.: “Satanás”.
====

[[v38-3-2]]

^<<v38-3-2,2>>^ [O anjo de] Jeová^&#42;1^ disse então a Satanás: “Jeová te censure, ó Satanás, sim, censure-te Jeová, aquele que escolhe Jerusalém! Não é este um tição arrancado do fogo?”

[NOTE]
====
. “O anjo (mensageiro) de Jeová”, Sy; MLXXVg: “Jeová”.
====

[[v38-3-3]]

^<<v38-3-3,3>>^ Ora, quanto a Josué, aconteceu que estava vestido de vestes imundas^&#42;1^ e estava de pé perante o anjo.

[NOTE]
====
. Ou “sujas”, isto é, de excremento.
====

[[v38-3-4]]

^<<v38-3-4,4>>^ Então ele respondeu e disse aos que estavam de pé perante ele: “Removei dele as vestes imundas.” E prosseguiu, dizendo-lhe: “Vê, fiz que passasse de ti o teu erro, e és vestido de trajes de gala.”

[[v38-3-5]]

^<<v38-3-5,5>>^ Então eu disse:^&#42;1^ “Ponha-se-lhe um turbante limpo na cabeça.” E eles passaram a pôr-lhe o turbante limpo na cabeça e a trajá-lo de vestes; e o anjo de Jeová^&#42;2^ estava de pé ali.

[NOTE]
====
. “Então eu disse”, M; TSyVg: “E ele disse”; LXX omite isso.
. Veja Ap. 1C sec. 2.
====

[[v38-3-6]]

^<<v38-3-6,6>>^ E o anjo de Jeová^&#42;1^ começou a dar testemunho a Josué, dizendo:

[NOTE]
====
. Veja Ap. 1C sec. 2.
====

[[v38-3-7]]

^<<v38-3-7,7>>^ “Assim disse Jeová^&#42;1^ dos exércitos: ‘Se andares nos meus caminhos e se cumprires a obrigação para comigo, então serás também tu quem julgarás a minha casa e também guardarás os meus pátios; e hei de dar-te livre acesso entre estes que ali estão de pé.’

[NOTE]
====
. Veja Ap. 1C sec. 2.
====

[[v38-3-8]]

^<<v38-3-8,8>>^ “‘Ouve, por favor, ó Josué, sumo sacerdote, tu e teus companheiros sentados diante de ti, pois são homens^&#42;1^ [servindo] como portentos;^&#42;2^ pois eis que estou trazendo meu servo Renovo!^&#42;3^

[NOTE]
====
. “Homens.” Hebr.: an·shéh, pl. de ’ish.
. Lit.: “homens de portento (sinal; maravilha)”.
. “Renovo.” Hebr.: Tsé·mahh. Veja Is 4:2 n.: “brotar”; Je 23:5; Je 33:15.
====

[[v38-3-9]]

^<<v38-3-9,9>>^ Pois, eis a pedra que pus diante de Josué! Sobre a única pedra há sete olhos.^&#42;1^ Eis que gravo a sua gravura’, é a pronunciação de Jeová dos exércitos, ‘e num só dia vou afastar o erro daquela terra’.

[NOTE]
====
. Ou “sete pares de olhos”, visto que a palavra para “olhos” é dual em número. Hebr.: shiv·‛áh ‛eh·ná·yim. Veja Ap. 3B.
====

[[v38-3-10]]

^<<v38-3-10,10>>^ “‘Naquele dia’, é a pronunciação de Jeová dos exércitos, ‘chamareis um ao outro, enquanto debaixo da videira e debaixo da figueira’.”

'''

xref:038-zacarias/038-zacarias-002.adoc#v38-2-0[&#60; Capítulo Anterior] | <<v38-3-0,Topo>> | xref:038-zacarias/038-zacarias-004.adoc#v38-4-0[Próximo Capítulo &#62;]