include::./index.adoc[]

[[v38-8-0]]
=== Zacarias, 8
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v38-8-1]]

^<<v38-8-1,1>>^ E continuou a vir a haver a palavra de Jeová dos exércitos, dizendo:

[[v38-8-2]]

^<<v38-8-2,2>>^ “Assim disse Jeová dos exércitos: ‘Com grande ciúme vou ser ciumento de Sião e com grande furor vou ser ciumento dela.’”

[[v38-8-3]]

^<<v38-8-3,3>>^ “Assim disse Jeová: ‘Vou retornar a Sião e residir no meio de Jerusalém; e Jerusalém há de ser chamada de cidade da veracidade,^&#42;1^ e o monte de Jeová dos exércitos, de santo monte.’”

[NOTE]
====
. Ou “cidade da verdade”. Hebr.: ‛ir-ha·’eméth.
====

[[v38-8-4]]

^<<v38-8-4,4>>^ “Assim disse Jeová dos exércitos: ‘Ainda sentar-se-ão homens idosos e mulheres idosas nas praças públicas de Jerusalém, cada um também com o seu bastão na mão, por causa da abundância dos [seus] dias.

[[v38-8-5]]

^<<v38-8-5,5>>^ E as próprias praças públicas da cidade encher-se-ão de meninos e de meninas brincando nas suas praças públicas.’”

[[v38-8-6]]

^<<v38-8-6,6>>^ “Assim disse Jeová dos exércitos: ‘Embora pareça difícil demais^&#42;1^ aos olhos dos remanescentes deste povo naqueles dias, deve também parecer difícil demais aos meus olhos?’^&#42;2^ é a pronunciação de Jeová dos exércitos.”

[NOTE]
====
. Ou “maravilhoso”. LXX: “impossível”.
. “Embora seja impossível à vista dos remanescentes deste povo naqueles dias, será também impossível à minha vista?” LXX. Veja Mt 19:26.
====

[[v38-8-7]]

^<<v38-8-7,7>>^ “Assim disse Jeová dos exércitos: ‘Eis que salvo meu povo da terra do nascente e da terra do pôr-do-sol.

[[v38-8-8]]

^<<v38-8-8,8>>^ E certamente os farei entrar, e terão de residir no meio de Jerusalém; e terão de tornar-se meu povo e eu mesmo me tornarei^&#42;1^ seu Deus, em veracidade e em justiça.’”

[NOTE]
====
. Ou “eu . . . mostrarei ser”. Hebr.: ’eh·yéh. Veja Êx 3:14 n.
====

[[v38-8-9]]

^<<v38-8-9,9>>^ “Assim disse Jeová dos exércitos: ‘Sejam fortes as vossas mãos, vós os que nestes dias estais ouvindo estas palavras da boca dos profetas, no dia em que se lançou o alicerce da casa de Jeová dos exércitos para se construir o templo.

[[v38-8-10]]

^<<v38-8-10,10>>^ Pois antes daqueles dias não se fizera existir salário para o gênero humano;^&#42;1^ e quanto ao salário dos animais domésticos, não havia tal coisa;^&#42;2^ e não havia paz para quem saía e para quem entrava, por causa do adversário,^&#42;3^ visto que eu lançava toda a humanidade uns contra os outros.’

[NOTE]
====
. Lit.: “salário do homem terreno”. Hebr.: sekhár ha·’a·dhám.
. “Não . . . tal coisa.” Lit.: “nenhuma”, hebr. fem., não se referindo a “salário”, hebr. masc., mas ao pagamento de salários.
. Ou “da aflição”.
====

[[v38-8-11]]

^<<v38-8-11,11>>^ “‘E agora não serei como nos dias anteriores para com os remanescentes deste povo’, é a pronunciação de Jeová dos exércitos.

[[v38-8-12]]

^<<v38-8-12,12>>^ ‘Pois haverá a semente de paz; a própria videira dará os seus frutos, e a própria terra dará a sua produção, e os próprios céus darão o seu orvalho; e eu hei de fazer os remanescentes deste povo herdar todas estas [coisas].

[[v38-8-13]]

^<<v38-8-13,13>>^ E terá de acontecer que assim como vos tornastes uma invocação do mal entre as nações, ó casa de Judá e casa de Israel, assim vos salvarei e tereis de tornar-vos uma bênção. Não tenhais medo. Sejam fortes as vossas mãos.’

[[v38-8-14]]

^<<v38-8-14,14>>^ “Pois assim disse Jeová dos exércitos: ‘“Assim como intentei fazer-vos o que era calamitoso, por me terem indignado os vossos antepassados”, disse Jeová dos exércitos, “e não [o] deplorei,

[[v38-8-15]]

^<<v38-8-15,15>>^ assim vou intentar novamente, naqueles dias, tratar bem a Jerusalém e a casa de Judá. Não tenhais medo”.’

[[v38-8-16]]

^<<v38-8-16,16>>^ “‘Estas são as coisas que deveis fazer: Falai verazmente uns com os outros.^&#42;1^ Fazei o vosso julgamento nos vossos portões com verdade e com julgamento de paz.

[NOTE]
====
. Ou: “Falai a verdade cada um com o seu companheiro.”
====

[[v38-8-17]]

^<<v38-8-17,17>>^ E não maquineis nos vossos corações a calamidade um para com outro e não ameis nenhum juramento falso; pois todas estas são as coisas que tenho odiado’, é a pronunciação de Jeová.”

[[v38-8-18]]

^<<v38-8-18,18>>^ E continuou a vir a haver para mim a palavra de Jeová dos exércitos, dizendo:

[[v38-8-19]]

^<<v38-8-19,19>>^ “Assim disse Jeová dos exércitos: ‘O jejum do quarto [mês], e o jejum do quinto [mês], e o jejum do sétimo [mês], e o jejum do décimo [mês] tornar-se-ão para a casa de Judá exultação, e alegria, e boas épocas festivas. Portanto, amai a verdade e a paz.’

[[v38-8-20]]

^<<v38-8-20,20>>^ “Assim disse Jeová^&#42;1^ dos exércitos: ‘Ainda será que virão povos e os habitantes de muitas cidades;

[NOTE]
====
. Veja Ap. 1C sec. 4.
====

[[v38-8-21]]

^<<v38-8-21,21>>^ e os habitantes de uma [cidade] certamente irão ter com [os de] outra, dizendo: “Vamos seriamente para abrandar a face de Jeová e para procurar a Jeová dos exércitos. Eu mesmo vou ir também.”

[[v38-8-22]]

^<<v38-8-22,22>>^ E muitos povos e poderosas nações virão realmente para procurar a Jeová dos exércitos em Jerusalém e para abrandar a face de Jeová.’

[[v38-8-23]]

^<<v38-8-23,23>>^ “Assim disse Jeová dos exércitos: ‘Naqueles dias, dez homens^&#42;1^ dentre todas as línguas^&#42;2^ das nações agarrarão, sim, agarrarão realmente a aba [da veste] dum homem^&#42;3^ judeu,^&#42;4^ dizendo: “Iremos convosco, pois ouvimos [que] Deus^&#42;5^ está convosco.”’”

[NOTE]
====
. “Homens.” Hebr.: ’ana·shím, pl. de ’ish.
. “As línguas.” Veja Gên 11:1.
. “Dum homem.” Hebr.: ’ish.
. “Judeu.” Hebr.: Yehu·dhí.
. “Deus.” Hebr.: ’Elo·hím.
====

'''

xref:038-zacarias/038-zacarias-007.adoc#v38-7-0[&#60; Capítulo Anterior] | <<v38-8-0,Topo>> | xref:038-zacarias/038-zacarias-009.adoc#v38-9-0[Próximo Capítulo &#62;]