include::./index.adoc[]

[[v38-9-0]]
=== Zacarias, 9
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v38-9-1]]

^<<v38-9-1,1>>^ Uma pronúncia: 
“A palavra de Jeová^&#42;1^ é contra a terra de Hadraque e descansa em Damasco; porque Jeová^&#42;2^ tem o olho [posto] no homem terreno e em todas as tribos de Israel.

[NOTE]
====
. Veja Ap. 1C sec. 4.
. Veja Ap. 1C sec. 4.
====

[[v38-9-2]]

^<<v38-9-2,2>>^ E a própria Hamate também confinará com ela; Tiro e Sídon, porque ela é muito sábia.

[[v38-9-3]]

^<<v38-9-3,3>>^ E Tiro passou a construir para si uma escarpa e a amontoar prata como pó e ouro^&#42;1^ como a lama das ruas.

[NOTE]
====
. “E ouro.” Hebr.: wehha·rúts.
====

[[v38-9-4]]

^<<v38-9-4,4>>^ Eis que o próprio Jeová^&#42;1^ a desapossará e certamente golpeará a sua força militar [lançando-a] dentro do mar; e ela mesma será devorada pelo fogo.

[NOTE]
====
. Uma das 134 mudanças de YHWH para ’Adho·naí feitas pelos escribas. Veja Ap. 1B e 1C sec. 4.
====

[[v38-9-5]]

^<<v38-9-5,5>>^ Ascalom [o] verá e ficará com medo; e quanto a Gaza, também sentirá dores muito severas; também Ecrom, porque a sua esperança aguardada terá de sofrer vergonha. E de Gaza há de perecer um rei e a própria Ascalom não será habitada.

[[v38-9-6]]

^<<v38-9-6,6>>^ E será realmente um filho ilegítimo que se sentará em Asdode, e eu certamente deceparei o orgulho do filisteu.

[[v38-9-7]]

^<<v38-9-7,7>>^ E vou remover-lhe da boca as suas coisas manchadas de sangue e de entre os seus dentes as suas coisas repugnantes, e então ele mesmo há de restar para o nosso Deus;^&#42;1^ e terá de tornar-se como um xeque^&#42;2^ em Judá, e Ecrom, como o jebuseu.

[NOTE]
====
. “Para o nosso Deus.” Hebr.: lE’·lo·héh·nu; gr.: The·oí; lat.: Dé·o.
. Veja Gên 36:15 n.
====

[[v38-9-8]]

^<<v38-9-8,8>>^ E eu vou acampar-me como posto avançado para a minha casa, de modo que ninguém passará e ninguém retornará; e não mais passará por eles algum feitor, porque agora eu [o] vi com os meus olhos.

[[v38-9-9]]

^<<v38-9-9,9>>^ “Jubila grandemente, ó filha de Sião. Brada em triunfo, ó filha de Jerusalém. Eis que vem a ti o teu próprio rei. Ele é justo, sim, salvo;^&#42;1^ humilde,^&#42;2^ e montado num jumento, sim, num animal plenamente desenvolvido, filho de jumenta.^&#42;3^

[NOTE]
====
. Ou “sim, tendo salvação”; ou: “sim, tendo sido salvo”; ou: “e sendo vitorioso”. Hebr.: wenoh·shá‛, passivo, como em De 33:29 e Sal 33:16; LXX: “e salvando”, ou: “e trazendo salvação”; lat.: et sal·vá·tor, “e salvador”.
. Ou “afligido”. Hebr.: ‛a·ní; lat.: paú·per.
. Lit.: “jumentas”.
====

[[v38-9-10]]

^<<v38-9-10,10>>^ E hei de decepar^&#42;1^ de Efraim [o] carro de guerra e de Jerusalém [o] cavalo. E o arco de batalha terá de ser decepado. E ele falará realmente de paz às nações; e seu domínio será de mar a mar e desde o Rio^&#42;2^ até os confins^&#42;3^ da terra.

[NOTE]
====
. Segundo MTVg; LXXSy: “ele destruirá cabalmente”.
. Isto é, o Eufrates.
. Veja Je 16:19 n.
====

[[v38-9-11]]

^<<v38-9-11,11>>^ “Também tu, [ó mulher,]^&#42;1^ pelo sangue do teu^&#42;2^ pacto vou enviar teus prisioneiros para fora do poço em que não há água.

[NOTE]
====
. “Tu, [ó mulher].” Lit.: “tu”. Hebr.: ’at, fem. sing.; isto é, Sião ou Jerusalém.
. “Teu”, no hebr., sujeito fem. sing., referindo-se à mulher, isto é, Sião ou Jerusalém.
====

[[v38-9-12]]

^<<v38-9-12,12>>^ “Voltai ao reduto,^&#42;1^ prisioneiros da esperança.
“Também, hoje [eu te] informo: ‘Pagar-te-ei de volta em dobro,^&#42;2^ [ó mulher].^&#42;3^

[NOTE]
====
. Ou “ao lugar inacessível (impenetrável)”. Hebr.: levits·tsa·róhn; esta é a única ocorrência no M.
. “Em dobro.” Hebr.: mish·néh. Veja  Is 61:7.
. “Pagar-te-ei . . ., [ó mulher].” Lit.: “Pagarei . . . a ti.” Hebr.: lakh, fem. sing. Veja v. 11 n.: “mulher”.
====

[[v38-9-13]]

^<<v38-9-13,13>>^ Pois vou entesar Judá como meu [arco].^&#42;1^ Vou encher o arco com Efraim e vou despertar^&#42;2^ teus filhos, ó Sião, contra os teus filhos, ó Grécia,^&#42;3^ e vou fazer-te^&#42;4^ como a espada de um poderoso.’^&#42;5^

[NOTE]
====
. “Como meu [arco].” Lit.: “para mim”. Hebr.: li; mas é o arco que é entesado.
. Ou “acordar (incitar)”.
. “Grécia”, Vg; LXX: “(filhos) dos gregos”; MSy: “Javã”. Veja Gên 10:2; Da 8:21 n.
. “Te”, hebr. fem. sing., referindo-se a “Sião”.
. “Um poderoso.” Hebr.: gib·bóhr.
====

[[v38-9-14]]

^<<v38-9-14,14>>^ E o próprio Jeová será visto sobre eles e sua flecha há de sair como raio. E o próprio Soberano Senhor Jeová tocará a buzina^&#42;1^ e ele há de andar com os vendavais do sul.^&#42;2^

[NOTE]
====
. Ou “o shofar”. Hebr.: bash·shoh·fár.
. “Sul.” Hebr.: teh·mán.
====

[[v38-9-15]]

^<<v38-9-15,15>>^ O próprio Jeová dos exércitos os defenderá, e eles realmente devorarão e subjugarão as pedras de funda. E hão de beber — ser turbulentos — como se houvesse vinho; e ficarão realmente cheios como a tigela, como os ângulos do altar.

[[v38-9-16]]

^<<v38-9-16,16>>^ “E Jeová, seu Deus,^&#42;1^ os há de salvar naquele dia como o rebanho do seu povo; pois serão como as pedras dum diadema cintilando sobre o seu^&#42;2^ solo.

[NOTE]
====
. “Seu Deus.” Em hebr.: ’Elo·heh·hém.
. “Seu”, referindo-se ao “povo”.
====

[[v38-9-17]]

^<<v38-9-17,17>>^ Pois, quão [grande] é a sua bondade e quão [grande] é a sua formosura! O cereal é o que fará os jovens medrar, e o vinho novo, as virgens.”

'''

xref:038-zacarias/038-zacarias-008.adoc#v38-8-0[&#60; Capítulo Anterior] | <<v38-9-0,Topo>> | xref:038-zacarias/038-zacarias-010.adoc#v38-10-0[Próximo Capítulo &#62;]