include::./index.adoc[]

[[v38-12-0]]
=== Zacarias, 12
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v38-12-1]]

^<<v38-12-1,1>>^ Uma pronúncia:
“A palavra de Jeová a respeito de Israel”, é a pronunciação de Jeová, Aquele que estendeu [os] céus, e lançou o alicerce da terra, e formou o espírito do homem^&#42;1^ no seu íntimo.

[NOTE]
====
. “O espírito do homem.” Hebr.: ru·ahh-’a·dhám.
====

[[v38-12-2]]

^<<v38-12-2,2>>^ “Eis que eu faço de Jerusalém uma taça [que causa] tontura a todos os povos ao redor; e também contra Judá ele virá a estar em sítio, [sim,] contra Jerusalém.

[[v38-12-3]]

^<<v38-12-3,3>>^ E naquele dia terá de acontecer [que] farei de Jerusalém uma pedra pesada para todos os povos. Todos os que a levantarem, sem falta se arranharão severamente; e todas as nações da terra hão de ser ajuntadas contra ela.

[[v38-12-4]]

^<<v38-12-4,4>>^ Naquele dia”, é a pronunciação de Jeová, “golpearei todo cavalo com desnorteamento e seu cavaleiro com loucura; e abrirei meus olhos sobre a casa de Judá e golpearei todo cavalo dos povos com a perda da vista.

[[v38-12-5]]

^<<v38-12-5,5>>^ E os xeques de Judá terão de dizer no seu coração: ‘Os habitantes de Jerusalém são para mim uma força por Jeová dos exércitos, seu Deus.’^&#42;1^

[NOTE]
====
. “Seu Deus.” Hebr.: ’Elo·heh·hém.
====

[[v38-12-6]]

^<<v38-12-6,6>>^ Naquele dia farei os xeques de Judá como um braseiro entre as árvores e como uma tocha acesa entre gavelas de cereal recém-segado, e terão de devorar à direita e à esquerda todos os povos ao redor; e Jerusalém ainda terá de ser habitada no seu [próprio] lugar, em Jerusalém.

[[v38-12-7]]

^<<v38-12-7,7>>^ “E Jeová há de salvar primeiro as tendas de Judá, com o fim de que a beleza da casa de Davi e a beleza dos habitantes de Jerusalém não fique engrandecida demais sobre Judá.

[[v38-12-8]]

^<<v38-12-8,8>>^ Naquele dia Jeová será uma defesa ao redor dos habitantes de Jerusalém; e quem entre eles estiver tropeçando terá de tornar-se naquele dia como Davi, e a casa de Davi, como Deus,^&#42;1^ como o anjo de Jeová diante deles.

[NOTE]
====
. Ou “como semelhantes a Deus”. Hebr.: ke’·lo·hím, pl.; LXX: “como a casa de Deus”; lat.: quá·si Dé·i. Veja Sal 8:5 n.
====

[[v38-12-9]]

^<<v38-12-9,9>>^ E naquele dia terá de acontecer [que] procurarei aniquilar todas as nações que chegarem contra Jerusalém.

[[v38-12-10]]

^<<v38-12-10,10>>^ “E eu vou derramar sobre a casa de Davi e sobre os habitantes de Jerusalém o espírito^&#42;1^ de favor e de rogos, e eles certamente olharão para Aquele a quem^&#42;2^ traspassaram e certamente O lamentarão como no lamento por um [filho] único; e haverá lamentação amarga por ele como quando há lamentação amarga por um [filho] primogênito.

[NOTE]
====
. “Espírito de.” Hebr.: rú·ahh; gr.: pneú·ma; lat.: spí·ri·tum.
. “Para Aquele a quem”, Th e Jo 19:37; MVg: “para mim, a quem”.
====

[[v38-12-11]]

^<<v38-12-11,11>>^ Naquele dia será grande o lamento em Jerusalém, como o lamento de Hadadrimom no vale plano de Megido.^&#42;1^

[NOTE]
====
. “Megido.” Hebr.: Meghid·dóhn; lat.: Ma·géd·don. Veja Re 16:16 n.: “Har-Magedon”.
====

[[v38-12-12]]

^<<v38-12-12,12>>^ E a terra^&#42;1^ certamente lamentará, cada família sozinha;^&#42;2^ a família da casa de Davi sozinha, e suas mulheres sozinhas; a família da casa de Natã sozinha, e suas mulheres sozinhas;

[NOTE]
====
. “A terra.” Hebr.: ha·’á·rets.
. Lit.: “famílias famílias à parte”.
====

[[v38-12-13]]

^<<v38-12-13,13>>^ a família da casa de Levi sozinha, e suas mulheres sozinhas; a família dos simeítas sozinha, e suas mulheres sozinhas;

[[v38-12-14]]

^<<v38-12-14,14>>^ todas as famílias restantes, cada família sozinha, e suas mulheres sozinhas.

'''

xref:038-zacarias/038-zacarias-011.adoc#v38-11-0[&#60; Capítulo Anterior] | <<v38-12-0,Topo>> | xref:038-zacarias/038-zacarias-013.adoc#v38-13-0[Próximo Capítulo &#62;]