include::./index.adoc[]

[[v38-2-0]]
=== Zacarias, 2
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v38-2-1]]

^<<v38-2-1,1>>^ E passei a levantar os olhos e a ver; e eis que havia um homem,^&#42;1^ e na sua mão havia uma corda de medir.

[NOTE]
====
. “Um homem.” Hebr.: ’ish.
====

[[v38-2-2]]

^<<v38-2-2,2>>^ Eu disse, pois: “Aonde vais?”
Por sua vez, ele me disse: “Medir Jerusalém para ver qual é a sua largura e qual é o seu comprimento.”

[[v38-2-3]]

^<<v38-2-3,3>>^ E eis que saía o anjo que falara comigo e outro anjo saía ao seu encontro.

[[v38-2-4]]

^<<v38-2-4,4>>^ Ele lhe disse então: “Corre, fala àquele moço lá, dizendo: ‘“Como terra campestre será Jerusalém habitada, por causa da multidão de homens e de animais domésticos no meio dela.

[[v38-2-5]]

^<<v38-2-5,5>>^ E eu mesmo”, é a pronunciação de Jeová, “tornar-me-ei para ela uma muralha de fogo ao redor e tornar-me-ei^&#42;1^ uma glória no meio dela”.’”

[NOTE]
====
. Ou “mostrarei ser”. Hebr.: ’eh·yéh. Veja Êx 3:14 n.
====

[[v38-2-6]]

^<<v38-2-6,6>>^ “Eh! Eh! Fugi, pois, da terra do norte”, é a pronunciação de Jeová.
“Pois eu vos dispersei na direção dos quatro ventos^&#42;1^ dos céus”, é a pronunciação de Jeová.

[NOTE]
====
. “Ventos.” Hebr.: ru·hhóhth, pl.; gr.: a·né·mon; lat.: vén·tos. Veja Gên 1:2 n.: “ativa”.
====

[[v38-2-7]]

^<<v38-2-7,7>>^ “Eh, Sião! Escapa-te, tu que moras com a filha de Babilônia.^&#42;1^

[NOTE]
====
. “Babilônia”, LXXVg; MTSy: “Babel”.
====

[[v38-2-8]]

^<<v38-2-8,8>>^ Pois assim disse Jeová dos exércitos: ‘Indo atrás da glória, ele me enviou às nações que vos despojavam; pois aquele que toca em vós, toca no globo do meu olho.^&#42;1^

[NOTE]
====
. “No globo do meu olho” era a versão original. Os soferins mudaram o texto para rezar “no globo do seu olho”. Veja Ap. 2B.
====

[[v38-2-9]]

^<<v38-2-9,9>>^ Pois eis que sacudo minha mão contra eles e terão de tornar-se despojo para os seus escravos.’ E vós haveis de saber que o próprio Jeová dos exércitos me enviou.

[[v38-2-10]]

^<<v38-2-10,10>>^ “Grita alto e alegra-te, ó filha de Sião; pois eis que venho, e vou residir no teu meio”, é a pronunciação de Jeová.

[[v38-2-11]]

^<<v38-2-11,11>>^ “E naquele dia certamente se juntarão muitas nações a Jeová e tornar-se-ão realmente meu povo; e eu vou residir no teu^&#42;1^ meio.” E terás de saber que foi o próprio Jeová dos exércitos quem me enviou a ti.

[NOTE]
====
. “Teu”, hebr. fem. sing., dirigido à “filha de Sião”.
====

[[v38-2-12]]

^<<v38-2-12,12>>^ E Jeová há de tomar posse de Judá como seu quinhão sobre o solo sagrado e ainda terá de escolher Jerusalém.

[[v38-2-13]]

^<<v38-2-13,13>>^ Cala-te, toda a carne, perante Jeová, porque ele despertou na sua santa habitação.

'''

xref:038-zacarias/038-zacarias-001.adoc#v38-1-0[&#60; Capítulo Anterior] | <<v38-2-0,Topo>> | xref:038-zacarias/038-zacarias-003.adoc#v38-3-0[Próximo Capítulo &#62;]