include::./index.adoc[]

[[v38-6-0]]
=== Zacarias, 6
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v38-6-1]]

^<<v38-6-1,1>>^ Então levantei novamente os olhos e vi; e eis que vinham quatro carros de entre dois montes, e os montes eram montes de cobre.

[[v38-6-2]]

^<<v38-6-2,2>>^ No primeiro carro havia cavalos vermelhos; e no segundo carro, cavalos pretos.

[[v38-6-3]]

^<<v38-6-3,3>>^ E no terceiro carro havia cavalos brancos; e no quarto carro, cavalos malhados, variegados.

[[v38-6-4]]

^<<v38-6-4,4>>^ E passei a responder e a dizer ao anjo^&#42;1^ que falava comigo: “Que são estes, meu senhor?”^&#42;2^

[NOTE]
====
. Ou “mensageiro”.
. “Meu senhor.” Hebr.: adho·ní; gr.: ký·ri·e; lat.: dó·mi·ne.
====

[[v38-6-5]]

^<<v38-6-5,5>>^ Portanto, o anjo respondeu e disse-me: “Estes são os quatro espíritos^&#42;1^ dos céus que saem depois de terem tomado sua posição perante o Senhor^&#42;2^ de toda a terra.

[NOTE]
====
. “Espíritos.” Hebr.: ru·hhóhth; LXXVg: “ventos”. Veja Gên 1:2 n.: “ativa”.
. “Senhor de.” Hebr.: ’Adhóhn; gr.: Ky·rí·oi; lat.: Do·mi·na·tó·re.
====

[[v38-6-6]]

^<<v38-6-6,6>>^ Quanto àquele^&#42;1^ em que estão os cavalos pretos, estes saem para a terra do norte; e quanto aos brancos, estes têm de sair para além do mar;^&#42;2^ e quanto aos malhados, estes têm de sair para a terra do sul.^&#42;3^

[NOTE]
====
. “Àquele”, fem. no hebr., referindo-se ao carro, hebr. fem.
. “Além do mar”, mediante uma ligeira mudança; MLXXVg: “atrás deles”; não na mesma direção, mas para o oeste, em direção ao Grande Mar, o Mediterrâneo.
. “Do sul”, M(hebr.: hat·teh·mán)TLXXSyVg.
====

[[v38-6-7]]

^<<v38-6-7,7>>^ E quanto aos variegados, têm de sair e continuar a procurar para [onde] ir, a fim de andar pela terra.” Então ele disse: “Ide, andai pela terra.” E começaram^&#42;1^ a andar pela terra.

[NOTE]
====
. “Começaram”, hebr. fem., possivelmente referindo-se a espíritos.
====

[[v38-6-8]]

^<<v38-6-8,8>>^ E ele passou a clamar a mim e a falar-me, dizendo: “Vê, os que vão para a terra do norte são os que fizeram o espírito de Jeová^&#42;1^ descansar na terra do norte.”

[NOTE]
====
. “O espírito de Jeová”, segundo n. em BHK e BHS; MSyVg: “meu espírito”; LXX: “minha ira”; T: “[fazem] minha vontade”. Veja Ap. 1A.
====

[[v38-6-9]]

^<<v38-6-9,9>>^ E continuou a vir a haver para mim a palavra de Jeová, dizendo:

[[v38-6-10]]

^<<v38-6-10,10>>^ “Tire-se algo do povo exilado, [sim,] de Heldai, e de Tobijá, e de Jedaías; e tu mesmo tens de entrar naquele dia, e tens de entrar na casa de Josias, filho de Sofonias, [junto com estes] que vieram de Babilônia.^&#42;1^

[NOTE]
====
. “Babilônia”, LXXVg; MTSy: “Babel”.
====

[[v38-6-11]]

^<<v38-6-11,11>>^ E tens de tomar prata e ouro, e tens de fazer uma grandiosa coroa^&#42;1^ e pô-la sobre a cabeça de Josué,^&#42;2^ filho de Jeozadaque, o sumo sacerdote.

[NOTE]
====
. “Uma grandiosa coroa”, T; LXXmss.Sy: “uma coroa”; MLXXVg: “coroas”. Veja v. 14 n.: “coroa”.
. Veja 3:1 n.: “Josué”.
====

[[v38-6-12]]

^<<v38-6-12,12>>^ E tens de dizer-lhe:
“‘Assim disse Jeová dos exércitos: “Aqui está o homem^&#42;1^ cujo nome é Renovo. E ele brotará de seu próprio lugar e certamente construirá o templo^&#42;2^ de Jeová.

[NOTE]
====
. “Aqui está o homem.” Hebr.: hin·neh-’ísh; gr.: I·doú a·nér; lat.: éc·ce vir. Veja Jo 19:5.
. “O templo de.” Hebr.: heh·khál; lat.: tém·plum. Veja Mt 23:16 n.
====

[[v38-6-13]]

^<<v38-6-13,13>>^ E ele mesmo construirá o templo de Jeová, e ele, da sua parte, levará [a] dignidade; e terá de assentar-se e governar no seu trono, e terá de tornar-se sacerdote sobre o seu trono, e o próprio conselho de paz mostrará estar entre ambos.

[[v38-6-14]]

^<<v38-6-14,14>>^ E a própria grandiosa coroa^&#42;1^ virá a pertencer a Helém,^&#42;2^ e a Tobijá, e a Jedaías, e a Hem,^&#42;3^ filho de Sofonias, como recordação no templo de Jeová.

[NOTE]
====
. “Grandiosa coroa.” Lit.: “coroas”, pl. para denotar excelência, e acompanhado por um verbo no sing.
. “Helém”, MTVg; Sy: “Heldai.”
. “Hem”, Vgc; MTVg: “Hen”; Sy: “Josias”.
====

[[v38-6-15]]

^<<v38-6-15,15>>^ E virão os que estão longe e realmente construirão no templo de Jeová.” E vós tereis de saber que o próprio Jeová dos exércitos me enviou a vós. E terá de acontecer — se sem falta escutardes a voz de Jeová, vosso Deus.’”

'''

xref:038-zacarias/038-zacarias-005.adoc#v38-5-0[&#60; Capítulo Anterior] | <<v38-6-0,Topo>> | xref:038-zacarias/038-zacarias-007.adoc#v38-7-0[Próximo Capítulo &#62;]