include::./index.adoc[]

[[v38-10-0]]
=== Zacarias, 10
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v38-10-1]]

^<<v38-10-1,1>>^ “Pedi a Jeová chuva no tempo da chuva primaveril, sim, a Jeová que faz as nuvens de temporal e [que] lhes dá o aguaceiro de chuva, a cada um vegetação no campo.

[[v38-10-2]]

^<<v38-10-2,2>>^ Pois os próprios terafins falaram aquilo que é mágico;^&#42;1^ e os adivinhos, da sua parte, visionaram falsidade, e continuam a falar de sonhos fúteis, e tentam consolar em vão. Por isso hão de partir qual rebanho; ficarão atribulados por não haver pastor.

[NOTE]
====
. Ou “prejudicial”.
====

[[v38-10-3]]

^<<v38-10-3,3>>^ “Minha ira acendeu-se contra os pastores e ajustarei contas com os líderes caprinos; pois Jeová dos exércitos tem voltado sua atenção para a sua grei, a casa de Judá, e ele os fez como o seu cavalo de dignidade na batalha.

[[v38-10-4]]

^<<v38-10-4,4>>^ Dele procede o homem-chave,^&#42;1^ dele procede o governante sustentador,^&#42;2^ dele procede o arco de batalha; dele procede todo feitor, [todos] juntos.

[NOTE]
====
. Lit.: “a torre de ângulo”, expressão gráfica aplicada a um homem vital ou importante; chefe.
. Lit.: “o tarugo”, expressão gráfica aplicada a alguém que provê apoio; governante.
====

[[v38-10-5]]

^<<v38-10-5,5>>^ E terão de tornar-se como homens poderosos calcando a lama das ruas na batalha. E terão de travar batalha, pois Jeová está com eles; e os que montam em cavalos terão de passar vergonha.

[[v38-10-6]]

^<<v38-10-6,6>>^ E vou fazer a casa de Judá superior e salvarei a casa de José. E vou dar-lhes morada,^&#42;1^ porque terei misericórdia com eles; e terão de tornar-se como os que eu não pus fora; porque eu sou Jeová, seu Deus,^&#42;2^ e lhes responderei.

[NOTE]
====
. Possivelmente: “Farei com que retornem.”
. “Seu Deus.” Hebr.: ’Elo·heh·hém.
====

[[v38-10-7]]

^<<v38-10-7,7>>^ E os de Efraim terão de tornar-se como um homem poderoso e seu coração terá de alegrar-se como que por causa de vinho. E seus próprios filhos verão e certamente se alegrarão; seu coração jubilará em Jeová.

[[v38-10-8]]

^<<v38-10-8,8>>^ “‘Vou assobiar para eles e reuni-los; porque certamente os remirei e terão de tornar-se muitos, iguais aos que se tornaram muitos.

[[v38-10-9]]

^<<v38-10-9,9>>^ E eu os espalharei como semente entre os povos, e lembrar-se-ão de mim nos lugares distantes; e terão de reviver com os seus filhos e voltar.

[[v38-10-10]]

^<<v38-10-10,10>>^ E terei de trazê-los de volta da terra do Egito; e reuni-los-ei da Assíria; e levá-los-ei à terra de Gileade e ao Líbano e não se achará [lugar] para eles.

[[v38-10-11]]

^<<v38-10-11,11>>^ E ele terá de passar pelo mar [com] aflição; e no mar terá de golpear [as] ondas e terão de secar-se todas as profundezas^&#42;1^ do Nilo. E o orgulho da Assíria terá de vir abaixo e o próprio cetro do Egito se retirará.

[NOTE]
====
. “Profundezas.” Hebr.: metsu·lóhth; gr.: bá·the; lat.: pro·fún·da.
====

[[v38-10-12]]

^<<v38-10-12,12>>^ E vou fazê-los superiores em Jeová, e andarão em seu nome’, é a pronunciação de Jeová.”

'''

xref:038-zacarias/038-zacarias-009.adoc#v38-9-0[&#60; Capítulo Anterior] | <<v38-10-0,Topo>> | xref:038-zacarias/038-zacarias-011.adoc#v38-11-0[Próximo Capítulo &#62;]