include::./index.adoc[]

[[v38-14-0]]
=== Zacarias, 14
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v38-14-1]]

^<<v38-14-1,1>>^ “Eis que vem um dia pertencente a Jeová, e teu^&#42;1^ despojo certamente será repartido no meio de ti.

[NOTE]
====
. “Teu”, hebr. fem. sing., referindo-se à “cidade” no v. 2.
====

[[v38-14-2]]

^<<v38-14-2,2>>^ E hei de ajuntar todas as nações contra Jerusalém para a guerra; e a cidade será realmente capturada e as casas rapinadas, e as próprias mulheres serão violentadas. E metade da cidade terá de ir para o exílio; mas, quanto aos que sobrarem^&#42;1^ do povo, não serão decepados da cidade.

[NOTE]
====
. Ou “ao restante; ao resto”.
====

[[v38-14-3]]

^<<v38-14-3,3>>^ “E Jeová há de sair e guerrear contra essas nações como no dia em que guerreia, no dia da peleja.

[[v38-14-4]]

^<<v38-14-4,4>>^ E naquele dia seus pés estarão realmente postados no monte das oliveiras, que está defronte de Jerusalém, ao leste; e o monte das oliveiras^&#42;1^ terá de ser fendido pelo meio, desde o nascente e até o oeste.^&#42;2^ Haverá um vale muito grande; e metade do monte será realmente movida para o norte e metade dele para o sul.^&#42;3^

[NOTE]
====
. Ou “o Monte das Oliveiras”.
. Lit.: “o mar”, isto é, o Mar Mediterrâneo ao oeste.
. Ou “Negebe”.
====

[[v38-14-5]]

^<<v38-14-5,5>>^ E vós certamente fugireis para o vale dos meus montes; porque o vale dos montes chegará até Azel.^&#42;1^ E tereis de fugir, assim como fugistes por causa do tremor [de terra] nos dias de Uzias, rei de Judá. E Jeová, meu Deus, certamente chegará, estando com ele^&#42;2^ todos os santos.

[NOTE]
====
. Um lugar perto de Jerusalém. Talvez o nome Azel repercuta no de Uádi Yasul, que é um afluente do vale do Cédron, procedente do Monte das Oliveiras.
. “Com ele”, TLXXSyVg e muitos mss. hebr.; M: “contigo”.
====

[[v38-14-6]]

^<<v38-14-6,6>>^ “E naquele dia terá de acontecer [que] não se mostrará haver nenhuma luz preciosa — as coisas ficarão solidificadas.

[[v38-14-7]]

^<<v38-14-7,7>>^ E terá de tornar-se um dia conhecido como pertencente a Jeová. Não será dia, nem será noite; e terá de suceder [que] ao tempo da noitinha ficará claro.

[[v38-14-8]]

^<<v38-14-8,8>>^ E naquele dia terá de acontecer [que] sairão de Jerusalém águas vivas, metade delas para o mar oriental^&#42;1^ e metade delas para o mar ocidental.^&#42;2^ Isto se dará no verão e no inverno.^&#42;3^

[NOTE]
====
. Ou “mar anterior”.
. Ou “mar posterior”, isto é, atrás da pessoa que encara o leste.
. Ou “outono”, isto é, no começo do inverno.
====

[[v38-14-9]]

^<<v38-14-9,9>>^ E Jeová terá de tornar-se rei sobre toda a terra.^&#42;1^ Naquele dia Jeová mostrará ser um só e seu nome um só.

[NOTE]
====
. “A terra.” Hebr.: ha·’á·rets.
====

[[v38-14-10]]

^<<v38-14-10,10>>^ “Toda a terra se transformará como o Arabá,^&#42;1^ desde Geba até Rimom, ao sul^&#42;2^ de Jerusalém; e ela terá de erguer-se e ficar habitada no seu lugar, desde o Portão de Benjamim até o lugar do Primeiro Portão, até o Portão da Esquina, e [desde] a Torre de Hananel até os tanques de lagar do rei.

[NOTE]
====
. Ou “a planície desértica”. Veja De 1:1 n.: “desérticas”.
. “Sul.” Hebr.: né·ghev.
====

[[v38-14-11]]

^<<v38-14-11,11>>^ E as pessoas certamente habitarão nela; e não virá a haver mais nenhuma condenação [à destruição], e Jerusalém terá de ser habitada em segurança.

[[v38-14-12]]

^<<v38-14-12,12>>^ “E este mostrará ser o flagelo com que Jeová flagelará todos os povos que realmente prestarem serviço militar contra Jerusalém: Haverá apodrecimento da carne enquanto a pessoa estiver de pé; e os próprios olhos da pessoa apodrecerão nas suas órbitas e a própria língua apodrecerá na boca da pessoa.

[[v38-14-13]]

^<<v38-14-13,13>>^ “E naquele dia terá de acontecer [que] se espalhará entre eles a confusão da parte de Jeová; e eles realmente agarrarão, cada um, a mão de seu companheiro, e sua mão realmente se levantará contra a mão de seu companheiro.

[[v38-14-14]]

^<<v38-14-14,14>>^ E o próprio Judá também guerreará em Jerusalém; e certamente se ajuntará a riqueza de todas as nações ao redor, o ouro, e a prata, e as vestes, em quantidade excessiva.

[[v38-14-15]]

^<<v38-14-15,15>>^ “E assim mostrará ser o flagelo do cavalo, do mulo, do camelo e do jumento, e de toda sorte de animal doméstico que vier a estar naqueles campos, semelhante a este flagelo.

[[v38-14-16]]

^<<v38-14-16,16>>^ “E terá de acontecer [que], quanto a todos aqueles que sobrarem dentre todas as nações que vêm contra Jerusalém, terão de subir também de ano em ano para se curvarem diante do Rei, Jeová dos exércitos, e para celebrarem a festividade das barracas.

[[v38-14-17]]

^<<v38-14-17,17>>^ E terá de acontecer que, quanto a todo aquele dentre as famílias da terra que não subir a Jerusalém para se curvar diante do Rei, Jeová dos exércitos, sim, sobre estes não virá a haver chuva copiosa.

[[v38-14-18]]

^<<v38-14-18,18>>^ E se a própria família do Egito não subir e realmente não entrar, também sobre eles não haverá nenhuma. Virá a haver o flagelo^&#42;1^ com que Jeová flagela as nações que não sobem para celebrar a festividade das barracas.

[NOTE]
====
. “Também sobre eles virá a haver a calamidade (o flagelo)”, LXXSy.
====

[[v38-14-19]]

^<<v38-14-19,19>>^ Esta é que mostrará ser a [punição pelo] pecado do Egito e pelo pecado de todas as nações que não subirem para celebrar a festividade das barracas.

[[v38-14-20]]

^<<v38-14-20,20>>^ “Naquele dia virá a haver sobre as sinetas do cavalo: ‘A santidade pertence a Jeová!’ E as panelas de boca larga na casa de Jeová terão de tornar-se como as tigelas perante o altar.

[[v38-14-21]]

^<<v38-14-21,21>>^ E toda panela de boca larga, em Jerusalém e em Judá, terá de tornar-se algo sagrado pertencente a Jeová dos exércitos, e todos os que oferecerem sacrifícios terão de entrar e tirar delas, e terão de cozinhar nelas. E não mais virá a haver naquele dia cananeu^&#42;1^ na casa de Jeová dos exércitos.”

[NOTE]
====
. Ou “comerciante”, como em TVg; hebr.: Khena·‛aní.
====

'''

xref:038-zacarias/038-zacarias-013.adoc#v38-13-0[&#60; Capítulo Anterior] | <<v38-14-0,Topo>> | xref:039-malaquias/039-malaquias-001.adoc#v39-1-0[Próximo Capítulo &#62;]