include::./index.adoc[]

[[v38-5-0]]
=== Zacarias, 5
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v38-5-1]]

^<<v38-5-1,1>>^ Então levantei novamente os olhos e vi; e eis um rolo voador!

[[v38-5-2]]

^<<v38-5-2,2>>^ Portanto, ele me disse: “Que estás vendo?”
Eu disse, da minha parte: “Estou vendo um rolo voador, cujo comprimento é de vinte côvados e cuja largura é de dez côvados.”

[[v38-5-3]]

^<<v38-5-3,3>>^ Então ele me disse: “Esta é a maldição que sai sobre a superfície de toda a terra, porque todo aquele que furta, segundo ela, neste lado, tem ficado impune; e todo aquele que faz um juramento, segundo ela, naquele lado, tem ficado impune.

[[v38-5-4]]

^<<v38-5-4,4>>^ ‘Eu a fiz sair’, é a pronunciação de Jeová dos exércitos, ‘e terá de entrar na casa do ladrão e na casa daquele que faz um juramento falso em meu nome; e terá de pousar no meio de sua casa e terá de exterminar a ela, e seu madeiramento, e suas pedras.’”

[[v38-5-5]]

^<<v38-5-5,5>>^ Então o anjo que falava comigo saiu e disse-me: “Levanta os olhos, por favor, e vê o que é que está saindo.”

[[v38-5-6]]

^<<v38-5-6,6>>^ Eu disse, pois: “O que é?”
Ele disse, por sua vez: “Este é o efa^&#42;1^ que está saindo.” E ele prosseguiu, dizendo: “Este é seu aspecto^&#42;2^ em toda a terra.”^&#42;3^

[NOTE]
====
. Cerca de 22 l.
. Lit.: “olho”, MVg; LXX: “injustiça”; Sy: “dívidas”.
. “A terra.” Hebr.: ha·’á·rets.
====

[[v38-5-7]]

^<<v38-5-7,7>>^ E eis que foi levantada a tampa circular de chumbo; e esta é certa mulher sentada no meio do efa.

[[v38-5-8]]

^<<v38-5-8,8>>^ De modo que ele disse: “Esta é a Iniqüidade.” E ele passou a lançá-la [de volta] no meio do efa, após o que lançou o peso de chumbo sobre a sua boca.

[[v38-5-9]]

^<<v38-5-9,9>>^ Então levantei os olhos e vi, e eis que saíam duas mulheres, e havia vento^&#42;1^ nas suas asas. E tinham asas semelhantes às asas da cegonha. E aos poucos levantaram o efa entre a terra e os céus.

[NOTE]
====
. “E . . . vento.” Hebr.: werú·ahh; gr.: pneú·ma; lat.: spí·ri·tus. Veja Gên 1:2 n.: “ativa”.
====

[[v38-5-10]]

^<<v38-5-10,10>>^ De modo que eu disse ao anjo que falava comigo: “Para onde levam o efa?”

[[v38-5-11]]

^<<v38-5-11,11>>^ Ele me disse, por sua vez: “Para construir-lhe uma casa na terra de Sinear;^&#42;1^ e terá de ficar firmemente estabelecida, e ali terá de ser depositada sobre o seu devido lugar.”

[NOTE]
====
. “Sinear”, M; lat.: Sén·na·ar; LXX: “Babilônia”; TSy: “Babel”.
====

'''

xref:038-zacarias/038-zacarias-004.adoc#v38-4-0[&#60; Capítulo Anterior] | <<v38-5-0,Topo>> | xref:038-zacarias/038-zacarias-006.adoc#v38-6-0[Próximo Capítulo &#62;]