include::./index.adoc[]

[[v38-11-0]]
=== Zacarias, 11
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v38-11-1]]

^<<v38-11-1,1>>^ “Abre as tuas portas, ó Líbano, para que um fogo devore entre os teus cedros.

[[v38-11-2]]

^<<v38-11-2,2>>^ Uiva, ó junípero, pois o cedro caiu; porque os próprios majestosos foram assolados! Uivai, árvores maciças de Basã, porque foi deitada abaixo a floresta impenetrável!^&#42;1^

[NOTE]
====
. Ou “fortificada; inacessível”. Mmargem: “interditada”.
====

[[v38-11-3]]

^<<v38-11-3,3>>^ Escuta! O uivo dos pastores, porque a sua majestade foi assolada. Escuta! O bramido de leões novos jubados, porque as [moitas] orgulhosas^&#42;1^ ao longo do Jordão foram assoladas.

[NOTE]
====
. “[Moitas] orgulhosas.” Ou “[árvores] altas”. Lit.: “orgulho”.
====

[[v38-11-4]]

^<<v38-11-4,4>>^ “Assim disse Jeová, meu Deus:^&#42;1^ ‘Pastoreia o rebanho [destinado] à matança,

[NOTE]
====
. “Jeová, meu Deus”, M(hebr.: Yehwáh ’Elo·haí)TSyVg; gr.: Ký·ri·os pan·to·krá·tor, “Jeová Todo-poderoso”.
====

[[v38-11-5]]

^<<v38-11-5,5>>^ cujos compradores passam a matá-las, embora não sejam tidos por culpados. E os que as vendem dizem: “Bendito seja Jeová, enquanto eu ganho riquezas.” E seus próprios pastores não têm nenhuma compaixão com elas.’

[[v38-11-6]]

^<<v38-11-6,6>>^ “‘Pois, não mais me compadecerei dos habitantes da terra’, é a pronunciação de Jeová. ‘Portanto, eis que faço que [os da] humanidade^&#42;1^ se encontrem, cada um na mão do seu companheiro e na mão do seu rei; e certamente esmiuçarão a terra e eu não livrarei da sua mão.’”

[NOTE]
====
. Ou “homem terreno”. Hebr.: ha·’a·dhám.
====

[[v38-11-7]]

^<<v38-11-7,7>>^ E passei a pastorear por vós o rebanho [destinado] à matança, ó atribulados do rebanho.^&#42;1^ Portanto, tomei para mim dois bordões. A um chamei de Afabilidade e ao outro chamei de União,^&#42;2^ e fui pastorear o rebanho.

[NOTE]
====
. Segundo M; mediante o reagrupamento e uma mudança dos sinais vocálicos: “a favor dos comerciantes do rebanho”.
. Lit.: “Atadores”. Hebr.: Hho·velím; aquilo que resulta numa união de coisas.
====

[[v38-11-8]]

^<<v38-11-8,8>>^ E finalmente eliminei três pastores num só mês lunar, visto que a minha alma ficou gradualmente impaciente com eles e também a própria alma deles me abominava.

[[v38-11-9]]

^<<v38-11-9,9>>^ Por fim eu disse: “Não continuarei a pastorear-vos. Morra aquela que estiver morrendo. E seja eliminada aquela que estiver sendo eliminada. E quanto às que restarem, que devorem cada uma a carne de sua companheira.”

[[v38-11-10]]

^<<v38-11-10,10>>^ Portanto, tomei o meu bordão Afabilidade e o cortei em pedaços, a fim de romper meu pacto que eu concluíra com todos os povos.

[[v38-11-11]]

^<<v38-11-11,11>>^ E ele ficou rompido naquele dia, e os atribulados do rebanho^&#42;1^ que me observavam ficaram assim sabendo que era a palavra de Jeová.

[NOTE]
====
. “Os atribulados do rebanho”, M. Veja v. 7 n.: “rebanho”.
====

[[v38-11-12]]

^<<v38-11-12,12>>^ Então eu lhes^&#42;1^ disse: “Se for bom aos vossos olhos, dai-me o meu salário; mas, se não, deixai-o.” E passaram a pagar-me^&#42;2^ o meu salário, trinta moedas de prata.

[NOTE]
====
. “Lhes”, hebr. masc.
. Lit.: “pesar [para mim]”.
====

[[v38-11-13]]

^<<v38-11-13,13>>^ Nisso Jeová me disse: “Lança-o na tesouraria^&#42;1^ — o valor majestoso com que fui avaliado do seu ponto de vista.” Concordemente, tomei as trinta moedas de prata e lancei-as na tesouraria da casa de Jeová.

[NOTE]
====
. “Tesouraria”, mediante uma correção; M: “fundador” ou “oleiro”; LXX: “forno de fundição”; Vg: “estatuaria”.
====

[[v38-11-14]]

^<<v38-11-14,14>>^ Então cortei em pedaços o meu segundo bordão, União, para romper a fraternidade entre Judá e Israel.

[[v38-11-15]]

^<<v38-11-15,15>>^ E Jeová prosseguiu, dizendo-me: “Toma ainda para ti os apetrechos dum pastor inútil.

[[v38-11-16]]

^<<v38-11-16,16>>^ Pois, eis que deixo surgir no país um pastor. Não voltará a [sua] atenção para as [ovelhas]^&#42;1^ que estão sendo eliminadas. Não procurará a nova e não curará a [ovelha] quebrantada. Não suprirá [alimento] à que está postada^&#42;2^ e comerá a carne da gorda, e ele arrancará os cascos das [ovelhas].^&#42;3^

[NOTE]
====
. Lit.: “Para aquelas”, hebr. fem., referindo-se às ovelhas simbólicas.
. “À que se fez adoecer”, mediante uma correção; mediante uma correção diferente: “à que está faminta”.
. Lit.: “delas”.
====

[[v38-11-17]]

^<<v38-11-17,17>>^ Ai do meu pastor imprestável que abandona o rebanho! Haverá uma espada sobre o seu braço e sobre o seu olho direito. Seu próprio braço secar-se-á impreterivelmente e seu próprio olho direito turvar-se-á sem falta.”

'''

xref:038-zacarias/038-zacarias-010.adoc#v38-10-0[&#60; Capítulo Anterior] | <<v38-11-0,Topo>> | xref:038-zacarias/038-zacarias-012.adoc#v38-12-0[Próximo Capítulo &#62;]