include::./index.adoc[]

[[v38-4-0]]
=== Zacarias, 4
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v38-4-1]]

^<<v38-4-1,1>>^ E o anjo que falava comigo passou a voltar e a despertar-me, como a um homem que desperta do seu sono.

[[v38-4-2]]

^<<v38-4-2,2>>^ Então ele me disse: “Que estás vendo?”
De modo que eu disse: “Vi, e eis que há um candelabro, todo ele de ouro, tendo no alto uma tigela. E sobre ele estão as suas sete lâmpadas, sim, sete; e as lâmpadas no alto dele têm sete tubos.

[[v38-4-3]]

^<<v38-4-3,3>>^ E há duas oliveiras ao lado dele, uma à direita da tigela e outra à sua esquerda.”

[[v38-4-4]]

^<<v38-4-4,4>>^ Então respondi e disse ao anjo que falava comigo, dizendo: “Que significam estas [coisas], meu senhor?”^&#42;1^

[NOTE]
====
. “Meu senhor.” Hebr.: ’adho·ní.
====

[[v38-4-5]]

^<<v38-4-5,5>>^ Portanto, o anjo que falava comigo respondeu e me disse: “Não sabes realmente o que significam estas coisas?”
Eu disse, da minha parte: “Não, meu senhor.”

[[v38-4-6]]

^<<v38-4-6,6>>^ Por conseguinte, ele respondeu e me disse: “Esta é a palavra de Jeová a Zorobabel, dizendo: ‘“Não por força militar,^&#42;1^ nem por poder,^&#42;2^ mas por meu espírito”,^&#42;3^ disse Jeová dos exércitos.

[NOTE]
====
. Ou “por energia vital”. Hebr.: vehhá·yil.
. “Por poder.” Hebr.: vekhó·ahh.
. “Por meu espírito.” Hebr.: beru·hhí; gr.: pneú·ma·ti; lat.: spí·ri·tu. Veja Gên 1:2 n.: “ativa”.
====

[[v38-4-7]]

^<<v38-4-7,7>>^ Quem és tu, ó grande monte? Diante de Zorobabel [tornar-te-ás] uma planície. E ele certamente produzirá a pedra de remate. Será aclamada: “Quão encantadora! Quão encantadora!”’”

[[v38-4-8]]

^<<v38-4-8,8>>^ E continuou a vir a haver para mim a palavra de Jeová, dizendo:

[[v38-4-9]]

^<<v38-4-9,9>>^ “As próprias mãos de Zorobabel lançaram o alicerce desta casa e suas próprias mãos [a] terminarão. E terás de saber que o próprio Jeová dos exércitos me enviou a vós.

[[v38-4-10]]

^<<v38-4-10,10>>^ Pois, quem desprezou o dia das coisas pequenas? E hão de alegrar-se e ver o prumo^&#42;1^ na mão de Zorobabel. Estes sete são os olhos de Jeová. Percorrem toda a terra.”

[NOTE]
====
. Lit.: “a pedra [ou: o peso], o estanho”. Hebr.: ha·’é·ven hab·bedhíl.
====

[[v38-4-11]]

^<<v38-4-11,11>>^ E passei a responder e a dizer-lhe: “Que significam estas duas oliveiras à direita do candelabro e à sua esquerda?”

[[v38-4-12]]

^<<v38-4-12,12>>^ Então respondi pela segunda vez e lhe disse: “Que são estes dois punhados de raminhos^&#42;1^ das oliveiras, que, por meio dos dois tubos de ouro, despejam de si o [líquido] dourado?”

[NOTE]
====
. “Punhados de raminhos das.” Hebr.: shib·baléh, pl. Veja a palavra similar em Jz 12:6 n.: “Xibolete”.
====

[[v38-4-13]]

^<<v38-4-13,13>>^ Ele me disse, pois: “Não sabes realmente o que significam estas [coisas]?”
Eu disse, da minha parte: “Não, meu senhor.”

[[v38-4-14]]

^<<v38-4-14,14>>^ Por conseguinte, ele disse: “São os dois ungidos^&#42;1^ que estão de pé ao lado do Senhor de toda a terra.”^&#42;2^

[NOTE]
====
. Lit.: “filhos do óleo”, MVg; LXXSy: “filhos da gordura”; T: “filhos de príncipes”.
. “Senhor de toda a terra.” Hebr.: ’Adhóhn kol-ha·’á·rets.
====

'''

xref:038-zacarias/038-zacarias-003.adoc#v38-3-0[&#60; Capítulo Anterior] | <<v38-4-0,Topo>> | xref:038-zacarias/038-zacarias-005.adoc#v38-5-0[Próximo Capítulo &#62;]