include::./index.adoc[]

[[v38-13-0]]
=== Zacarias, 13
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v38-13-1]]

^<<v38-13-1,1>>^ “Naquele dia virá a haver uma fonte aberta para a casa de Davi e para os habitantes de Jerusalém, para o pecado e para uma coisa abominável.

[[v38-13-2]]

^<<v38-13-2,2>>^ “E naquele dia terá de acontecer”, é a pronunciação de Jeová dos exércitos, “[que] deceparei do país os nomes dos ídolos e eles não serão mais lembrados;^&#42;1^ e também farei passar para fora do país os profetas e o espírito de impureza.^&#42;2^

[NOTE]
====
. Ou “mencionados”.
. Ou “a expressão inspirada por impureza”; ou: “a impura expressão inspirada”. Veja Re 16:13 n.: “inspiradas”.
====

[[v38-13-3]]

^<<v38-13-3,3>>^ E terá de acontecer [que], caso um homem^&#42;1^ ainda profetize, seu pai e sua mãe, aqueles que fizeram que nascesse, também terão de dizer-lhe: ‘Não viverás, porque falaste falsidade em nome de Jeová.’ E seu pai e sua mãe, aqueles que fizeram que nascesse, terão de traspassá-lo por ele ter profetizado.

[NOTE]
====
. “Um homem.” Hebr.: ’ish.
====

[[v38-13-4]]

^<<v38-13-4,4>>^ “E naquele dia terá de acontecer [que] os profetas ficarão envergonhados, cada um da sua visão ao profetizar; e não usarão um manto oficial de pêlo com o fim de enganar.

[[v38-13-5]]

^<<v38-13-5,5>>^ E ele certamente dirá: ‘Não sou profeta. Sou homem^&#42;1^ que lavra [o] solo, porque foi um homem terreno^&#42;2^ que me adquiriu desde a minha mocidade.’

[NOTE]
====
. “Homem.” Hebr.: ’ish.
. “Um homem terreno.” Hebr.: ’a·dhám; gr.: án·thro·pos; Vg: “Adão ([era, ou é] meu exemplo).”
====

[[v38-13-6]]

^<<v38-13-6,6>>^ E terá de dizer-se-lhe: ‘Que feridas^&#42;1^ são essas [na tua pessoa] entre as tuas mãos?’ E ele terá de dizer: ‘São de eu ter sido golpeado^&#42;2^ na casa dos que me amavam intensamente.’”

[NOTE]
====
. Ou “golpes”.
. Ou “ferido”.
====

[[v38-13-7]]

^<<v38-13-7,7>>^ “Ó espada, desperta contra meu pastor, sim, contra o varão vigoroso que é meu colega”, é a pronunciação de Jeová dos exércitos. “Golpeia o pastor e sejam espalhadas as [ovelhas] do rebanho; e eu hei de fazer a minha mão voltar sobre os insignificantes.”^&#42;1^

[NOTE]
====
. Ou “os guardiães meninos”. Hebr.: hats·tso·‛arím; LXXA: “os pastores”; LXXא,BVg: “os pequeninos”, masc.; Sy: “os superiores (grandes)”.
====

[[v38-13-8]]

^<<v38-13-8,8>>^ “E terá de acontecer em toda a terra”,^&#42;1^ é a pronunciação de Jeová, “[que] duas partes nela serão decepadas [e] expirarão; e quanto à terceira [parte], será deixada sobrar nela.

[NOTE]
====
. “A terra.” Hebr.: ha·’á·rets.
====

[[v38-13-9]]

^<<v38-13-9,9>>^ E eu certamente levarei a terceira [parte] através do fogo; e eu realmente os refinarei como se refina a prata e os examinarei como se examina o ouro. Ela, da sua parte, invocará o meu nome, e eu, da minha parte, lhes responderei. Vou dizer: ‘É meu povo’, e ela, por sua vez, dirá: ‘Jeová é meu Deus.’”

'''

xref:038-zacarias/038-zacarias-012.adoc#v38-12-0[&#60; Capítulo Anterior] | <<v38-13-0,Topo>> | xref:038-zacarias/038-zacarias-014.adoc#v38-14-0[Próximo Capítulo &#62;]