include::./index.adoc[]

[[v27-3-0]]
=== Daniel, 3
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v27-3-1]]

^<<v27-3-1,1>>^ Nabucodonosor, o rei, fez uma imagem de ouro, cuja altura era de sessenta côvados [e] cuja largura era de seis côvados. Erigiu-a na planície de Dura, no distrito jurisdicional de Babilônia.

[[v27-3-2]]

^<<v27-3-2,2>>^ E o próprio Nabucodonosor, como rei, mandou reunir os sátrapas, os prefeitos e os governadores, os conselheiros, os tesoureiros, os juízes, os magistrados policiais e todos os administradores dos distritos jurisdicionais, para que viessem à inauguração da imagem erigida por Nabucodonosor, o rei.

[[v27-3-3]]

^<<v27-3-3,3>>^ Naquele tempo reuniram-se os sátrapas, os prefeitos e os governadores, os conselheiros, os tesoureiros, os juízes, os magistrados policiais e todos os administradores dos distritos jurisdicionais para a inauguração da imagem erigida por Nabucodonosor, o rei, e estavam de pé diante da imagem erigida por Nabucodonosor.

[[v27-3-4]]

^<<v27-3-4,4>>^ E o arauto^&#42;1^ clamou em alta [voz]: “Diz-se a vós, ó povos, grupos nacionais e línguas,

[NOTE]
====
. “E o arauto.” Aram.: wekha·roh·zá’, derivado do antigo substantivo persa xrausa, “pregoeiro”; gr.: ké·ryx; lat.: praé·co. Veja 5:29 n.: “proclamaram”.
====

[[v27-3-5]]

^<<v27-3-5,5>>^ que, quando ouvirdes o som da buzina, do pífaro, da cítara, da harpa triangular, do instrumento de cordas, da gaita de foles e de toda sorte de instrumentos musicais, vos prostreis e adoreis a imagem de ouro erigida por Nabucodonosor, o rei.

[[v27-3-6]]

^<<v27-3-6,6>>^ E quem não se prostrar e [não] adorar, será no mesmo instante lançado dentro da fornalha de fogo ardente.”

[[v27-3-7]]

^<<v27-3-7,7>>^ Por causa disso, ao mesmo tempo em que todos os povos ouviam o som da buzina, do pífaro, da cítara, da harpa triangular, do instrumento de cordas e de toda sorte de instrumentos musicais, todos os povos, grupos nacionais e línguas prostraram-se [e] adoraram a imagem de ouro erigida por Nabucodonosor, o rei.

[[v27-3-8]]

^<<v27-3-8,8>>^ Por causa disso, ao mesmo tempo chegaram-se certos caldeus^&#42;1^ e acusaram os judeus.^&#42;2^

[NOTE]
====
. Lit.: “varões vigorosos, caldeus”. Aram.: guv·rín Kas·da·’ín.
. Ou “caluniaram os judeus”. Lit.: “comeram os pedaços [de carne arrancados dos corpos] dos judeus”.
====

[[v27-3-9]]

^<<v27-3-9,9>>^ Eles responderam e disseram a Nabucodonosor, o rei: “Ó rei, vive por tempos indefinidos.

[[v27-3-10]]

^<<v27-3-10,10>>^ Tu mesmo, ó rei, deste a ordem de que todo homem que ouvir o som da buzina, do pífaro, da cítara, da harpa triangular, do instrumento de cordas, e da gaita de foles e de toda sorte de instrumentos musicais, deve prostrar-se e adorar a imagem de ouro;

[[v27-3-11]]

^<<v27-3-11,11>>^ e quem não se prostrar e adorar deve ser lançado dentro da fornalha de fogo ardente.

[[v27-3-12]]

^<<v27-3-12,12>>^ Há certos judeus^&#42;1^ que designaste sobre a administração do distrito jurisdicional de Babilônia, Sadraque, Mesaque e Abednego; estes varões vigorosos não fizeram caso de ti, ó rei, não servem os teus próprios deuses^&#42;2^ e não adoram a imagem de ouro que erigiste.”

[NOTE]
====
. Lit.: “varões vigorosos, judeus”. Aram.: guv·rín Yehu·dha’·yín.
. “Os teus próprios deuses.” Aram.: le’·la·haíkh; LXXBagster(gr.): the·oís; lat.: dé·os.
====

[[v27-3-13]]

^<<v27-3-13,13>>^ Nisso Nabucodonosor, em cólera e furor, disse que trouxessem Sadraque, Mesaque e Abednego. Por conseguinte, estes varões vigorosos foram levados perante o rei.

[[v27-3-14]]

^<<v27-3-14,14>>^ Nabucodonosor respondeu e disse-lhes: “É realmente assim, ó Sadraque, Mesaque e Abednego, que não servis os meus próprios deuses^&#42;1^ e que não adorais a imagem de ouro que erigi?

[NOTE]
====
. “Os meus próprios deuses.” Em aram.: le’·la·haí.
====

[[v27-3-15]]

^<<v27-3-15,15>>^ Agora, se estiverdes prontos, de modo que, ao ouvirdes o som da buzina, do pífaro, da cítara, da harpa triangular, do instrumento de cordas, e da gaita de foles e de toda sorte de instrumentos musicais, vos prostreis e adoreis a imagem que fiz, [muito bem]. Mas, se não adorardes, no mesmo instante sereis lançados dentro da fornalha de fogo ardente. E quem é esse deus^&#42;1^ que vos pode salvar das minhas mãos?”

[NOTE]
====
. “Deus.” Aram.: ’eláh.
====

[[v27-3-16]]

^<<v27-3-16,16>>^ Sadraque, Mesaque e Abednego responderam e disseram ao rei: “Ó Nabucodonosor, neste respeito não temos necessidade de te replicar qualquer palavra.

[[v27-3-17]]

^<<v27-3-17,17>>^ Se for preciso, nosso Deus,^&#42;1^ a quem servimos, poderá salvar-nos. Ele [nos] salvará da fornalha de fogo ardente e da tua mão, ó rei.

[NOTE]
====
. “Nosso Deus.” Em aram.: ’Ela·há·na’.
====

[[v27-3-18]]

^<<v27-3-18,18>>^ Mas, se não, seja do teu conhecimento, ó rei, que não é a teus deuses^&#42;1^ que servimos e que não é a tua imagem de ouro que erigiste que adoraremos.”

[NOTE]
====
. “Teus deuses.” Aram.: le’·la·haíkh.
====

[[v27-3-19]]

^<<v27-3-19,19>>^ Foi então que o próprio Nabucodonosor se encheu de fúria e a própria expressão do seu rosto mudou para com Sadraque, Mesaque e Abednego. Ele respondeu e disse que se aquecesse a fornalha sete vezes mais do que era costumeiro fazer.

[[v27-3-20]]

^<<v27-3-20,20>>^ E ele disse a certos varões vigorosos de energia vital na sua força militar que amarrassem Sadraque, Mesaque e Abednego para [os] lançar na fornalha de fogo ardente.

[[v27-3-21]]

^<<v27-3-21,21>>^ Foi então que estes varões vigorosos foram amarrados nas suas capas, nas suas vestes e nos seus gorros, e na sua outra vestimenta, e foram lançados dentro da fornalha de fogo ardente.

[[v27-3-22]]

^<<v27-3-22,22>>^ Visto que a palavra do rei era dura e a fornalha estava aquecida ao extremo, aqueles varões vigorosos que levaram Sadraque, Mesaque e Abednego foram os que a chama ardente matou.

[[v27-3-23]]

^<<v27-3-23,23>>^ Mas, estes [outros] varões vigorosos, os três, Sadraque, Mesaque e Abednego, caíram amarrados no meio da fornalha de fogo ardente.^&#42;1^

[NOTE]
====
. LXXVg fazem aqui uma longa inserção, e recomeçam no seu v. 91 a versão do texto do M.
====

[[v27-3-24]]

^<<v27-3-24,24>>^ Nisso Nabucodonosor, o próprio rei, ficou com medo e se levantou depressa. Ele respondeu e disse aos seus altos funcionários reais: “Não foram três os varões vigorosos que lançamos amarrados no meio do fogo?” Eles responderam e disseram ao rei: “Sim, ó rei.”

[[v27-3-25]]

^<<v27-3-25,25>>^ Ele respondeu e disse: “Eis que estou vendo quatro varões vigorosos andando livres no meio do fogo e sem nenhum dano para eles, e a aparência do quarto é semelhante à de um filho dos deuses.”^&#42;1^

[NOTE]
====
. “É semelhante à de um filho dos deuses.” Aram.: da·méh levar-’ela·hín; gr.: the·oú; sir.: ’a·la·hin.
====

[[v27-3-26]]

^<<v27-3-26,26>>^ Então Nabucodonosor se chegou à porta da fornalha de fogo ardente. Ele respondeu e disse: “Sadraque, Mesaque e Abednego, vós servos do Deus Altíssimo,^&#42;1^ saí e vinde para cá!” Então Sadraque, Mesaque e Abednego saíram do meio do fogo.

[NOTE]
====
. “Do Deus Altíssimo.” Aram.: ’Ela·há’ ‛Il·lai·’á. Veja 5:18 n.
====

[[v27-3-27]]

^<<v27-3-27,27>>^ E os sátrapas, os prefeitos e os governadores, e os altos funcionários do rei, que se achavam reunidos, viram estes varões vigorosos, que o fogo não tivera domínio sobre os seus corpos e que nenhum cabelo da sua cabeça fora chamuscado, e nem mesmo as suas capas se mudaram e não ficara neles o cheiro do próprio fogo.

[[v27-3-28]]

^<<v27-3-28,28>>^ Nabucodonosor respondeu e disse: “Bendito seja o Deus de Sadraque, Mesaque e Abednego, que enviou seu anjo e salvou seus servos que confiaram nele, e que mudaram^&#42;1^ a própria palavra do rei e entregaram seus corpos, porque não quiseram servir e não quiseram adorar nenhum deus exceto o seu próprio Deus.^&#42;2^

[NOTE]
====
. Ou “anularam”.
. “O seu próprio Deus.” Aram.: lE’·la·hahóhn.
====

[[v27-3-29]]

^<<v27-3-29,29>>^ E eu dou ordem para que todo povo, grupo nacional ou língua que disser algo de errado contra o Deus de Sadraque, Mesaque e Abednego seja desmembrado, e sua casa seja transformada em latrina pública; pois não há outro deus^&#42;1^ que possa livrar assim como este.”

[NOTE]
====
. “Deus.” Aram.: ’eláh.
====

[[v27-3-30]]

^<<v27-3-30,30>>^ Naquele tempo, o próprio rei fez que Sadraque, Mesaque e Abednego prosperassem no distrito jurisdicional de Babilônia.^&#42;1^

[NOTE]
====
. Sy termina aqui o cap. 3; MLXXBagsterVg continuam com o cap. 3 por mais três vv.
====

'''

xref:027-daniel/027-daniel-002.adoc#v27-2-0[&#60; Capítulo Anterior] | <<v27-3-0,Topo>> | xref:027-daniel/027-daniel-004.adoc#v27-4-0[Próximo Capítulo &#62;]