include::./index.adoc[]

[[v27-7-0]]
=== Daniel, 7
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v27-7-1]]

^<<v27-7-1,1>>^ No primeiro ano de Belsazar,^&#42;1^ rei de Babilônia,^&#42;2^ o próprio Daniel teve um sonho e visões da sua cabeça, sobre a sua cama. Naquele tempo ele anotou o próprio sonho. Fez o relato completo dos assuntos.

[NOTE]
====
. Veja 5:1 n.: “Belsazar”.
. “Babilônia”, Vg; MSy: “Babel”; LXX: “da terra de Babilônia”; LXXBagster: “dos caldeus”.
====

[[v27-7-2]]

^<<v27-7-2,2>>^ Daniel falou e disse:
“Aconteceu que eu estava vendo nas minhas visões durante a noite, e eis que os quatro ventos^&#42;1^ dos céus agitavam o vasto mar.

[NOTE]
====
. “Ventos dos.” Aram.: ru·hhéh; lat.: vén·ti.
====

[[v27-7-3]]

^<<v27-7-3,3>>^ E quatro animais gigantescos subiam do mar, cada um diferente dos outros.

[[v27-7-4]]

^<<v27-7-4,4>>^ “O primeiro era como leão e tinha asas de águia. Eu estava observando até que se lhe arrancaram as asas, e ele foi levantado da terra e posto nos dois pés como um homem, e deu-se-lhe um coração de homem.

[[v27-7-5]]

^<<v27-7-5,5>>^ “E eis aqui outro animal, um segundo, semelhante a um urso. E estava levantado dum lado, e havia três costelas na sua boca entre os seus dentes; e dizia-se-lhe o seguinte: ‘Levanta-te, come muita carne.’

[[v27-7-6]]

^<<v27-7-6,6>>^ “Depois disso continuei observando, e eis aqui outro [animal],^&#42;1^ semelhante a um leopardo, mas tinha quatro asas de criatura voadora nas suas costas.^&#42;2^ E o animal tinha quatro cabeças e deveras foi-lhe dado domínio.

[NOTE]
====
. “Animal”, LXXSy; M omite isso.
. “Costas”, Mmargem; M: “lados”.
====

[[v27-7-7]]

^<<v27-7-7,7>>^ “Depois disso continuei observando nas visões da noite, e eis aqui um quarto animal, atemorizante e terrível, e extraordinariamente forte. E tinha dentes de ferro, grandes. Devorava e esmiuçava, e o resto calcava com os seus pés. E era diferente de todos os [outros] animais que lhe precederam, e tinha dez chifres.

[[v27-7-8]]

^<<v27-7-8,8>>^ Eu estava contemplando os chifres, e eis que subiu entre eles outro chifre, um pequeno, e três dos primeiros chifres foram arrancados diante dele. E eis que havia olhos semelhantes aos olhos de homem neste chifre e havia uma boca falando coisas grandiosas.

[[v27-7-9]]

^<<v27-7-9,9>>^ “Eu estava observando até que se colocaram uns tronos^&#42;1^ e o Antigo de Dias^&#42;2^ se assentou. Sua vestimenta era branca como a neve e o cabelo de sua cabeça era como pura lã. Seu trono era chamas de fogo; as rodas dele eram fogo ardente.

[NOTE]
====
. Ou “colocou um grandioso trono”, se o substantivo aram. estiver no pl. para denotar majestade.
. “E o Antigo de Dias.” Aram.: we‛At·tíq Yoh·mín; lat.: An·tí·qu·us Di·é·rum.
====

[[v27-7-10]]

^<<v27-7-10,10>>^ De diante dele corria e saía um rio de fogo. Mil [vezes] mil lhe ministravam^&#42;1^ e dez mil vezes dez mil ficavam de pé logo diante dele. Assentou-se o Tribunal^&#42;2^ e abriram-se livros.

[NOTE]
====
. “Lhe ministravam.” Aram.: yesham·meshun·néh; lat.: mi·ni·strá·bant é·i.
. Lit.: “o Julgamento”. Aram.: Di·ná’; lat.: iu·dí·ci·um.
====

[[v27-7-11]]

^<<v27-7-11,11>>^ “Continuei observando naquele tempo por causa do som das palavras grandiosas faladas pelo chifre; eu estava observando até que o animal foi morto e seu corpo foi destruído, e foi entregue ao fogo ardente.

[[v27-7-12]]

^<<v27-7-12,12>>^ Mas, quanto aos demais animais, tirou-se-lhes o seu domínio e foi-lhes dado prolongamento de vida por um tempo e uma época.^&#42;1^

[NOTE]
====
. Ou “por um tempo e um tempo designado”. Aram.: ‛adh·zemán we‛id·dán; gr.: hé·os khró·nou kai kai·roú; lat.: ús·que ad tém·pus et tém·pus.
====

[[v27-7-13]]

^<<v27-7-13,13>>^ “Continuei observando nas visões da noite e eis que aconteceu que chegou com as nuvens dos céus alguém semelhante a um filho de homem;^&#42;1^ e ele obteve acesso ao Antigo de Dias, e fizeram-no chegar perto perante Este.

[NOTE]
====
. “Alguém semelhante a um filho de homem.” Aram.: kevár ’enásh. Compare isso com u·ven-’a·dhám, “e o filho do homem terreno”, no Sal 8:4.
====

[[v27-7-14]]

^<<v27-7-14,14>>^ E foi-lhe dado domínio, e dignidade, e um reino,^&#42;1^ para que todos os povos, grupos nacionais e línguas o servissem. Seu domínio é um domínio de duração indefinida, que não passará, e seu reino é um que não será arruinado.

[NOTE]
====
. “E um reino.” Aram.: u·mal·khú; lat.: ré·gnum.
====

[[v27-7-15]]

^<<v27-7-15,15>>^ “Quanto a mim, Daniel, meu espírito^&#42;1^ estava aflito dentro [de mim] por causa disso, e as próprias visões da minha cabeça começaram a amedrontar-me.

[NOTE]
====
. “Meu espírito.” Aram.: ru·hhí; Th(gr.): pneú·ma; lat.: spí·ri·tus.
====

[[v27-7-16]]

^<<v27-7-16,16>>^ Cheguei-me a um dos que estavam de pé, para pedir informação fidedigna sobre tudo isso. E ele me disse, ao me dar a conhecer a própria interpretação dos assuntos:

[[v27-7-17]]

^<<v27-7-17,17>>^ “‘Quanto a estes animais gigantescos, por serem quatro, são quatro reis que se erguerão da terra.

[[v27-7-18]]

^<<v27-7-18,18>>^ Mas os santos do Supremo^&#42;1^ receberão o reino e tomarão posse do reino por tempo indefinido, sim, por tempo indefinido sobre tempos indefinidos.’

[NOTE]
====
. Ou “os santos do Altíssimo”. Aram.: qad·di·shéh ‛El·yoh·nín (pl. de ‛El·yóhn), constituindo com a palavra aram. para “santos” uma segunda palavra no pl., ou então está copiando a pluralidade de “santos” por estar tão perto na sentença. Pelo visto, isto não pretende indicar que os “santos” sejam altíssimos. “Altíssimo” está no sing. em LXXSyVg e em muitos mss. hebr.
====

[[v27-7-19]]

^<<v27-7-19,19>>^ “Foi então que quis certificar-me do quarto animal, que mostrava ser diferente de todos os outros, extraordinariamente atemorizante, cujos dentes eram de ferro e cujas garras eram de cobre, que devorava [e] esmiuçava, e que calcava o que restou com os seus pés;

[[v27-7-20]]

^<<v27-7-20,20>>^ e dos dez chifres que havia na sua cabeça, e do outro [chifre] que subiu e perante o qual^&#42;1^ caíram três, sim, daquele chifre que tinha olhos e uma boca falando coisas grandiosas, e cuja aparência era maior do que a de seus companheiros.

[NOTE]
====
. Ou “e abrindo caminho para o qual”.
====

[[v27-7-21]]

^<<v27-7-21,21>>^ “Eu estava observando quando este mesmo chifre fez guerra aos santos, e prevalecia contra eles,

[[v27-7-22]]

^<<v27-7-22,22>>^ até que veio o Antigo de Dias e se fez o próprio julgamento a favor dos santos do Supremo, e chegou o tempo específico de os santos tomarem posse do próprio reino.

[[v27-7-23]]

^<<v27-7-23,23>>^ “Ele disse assim: ‘Quanto ao quarto animal, virá a haver na terra um quarto reino que será diferente de todos os [outros] reinos; e devorará toda a terra e a pisoteará e esmiuçará.

[[v27-7-24]]

^<<v27-7-24,24>>^ E quanto aos dez chifres, daquele reino levantar-se-ão dez reis; e depois deles levantar-se-á ainda outro, e ele mesmo será diferente dos primeiros, e três reis serão humilhados.

[[v27-7-25]]

^<<v27-7-25,25>>^ E falará até mesmo palavras contra o Altíssimo^&#42;1^ e hostilizará continuamente^&#42;2^ os próprios santos do Supremo.^&#42;3^ E tentará mudar tempos^&#42;4^ e lei, e serão^&#42;5^ entregues à sua mão por um tempo, e tempos e metade de um tempo.^&#42;6^

[NOTE]
====
. “O Altíssimo.” Aram.: ‛Il·lai·’á, sing.; gr.: Hý·psi·ston; lat.: Ex·cél·sum.
. Lit.: “esgotará (desgastará)”.
. Veja v. 18 n.
. “Tempos.” Aram.: zim·nín.
. “Serão”, MSyVg; LXX: “todas as coisas serão”; LXXBagster: “será”.
. Ou “por uma época, e épocas e metade de uma época”. Aram.: ‛adh-‛id·dán we‛id·da·nín u·felágh ‛id·dán. Aqui, we‛id·da·nín é considerado como dual, significando assim “e dois tempos”. Lexicon Linguae Aramaicae Veteris Testamenti, de E. Vogt, Roma, 1971, p. 124: “‘per tempus et (duo) tempora et dimidium tempus’ i.e. per 31⁄2 annos [‘por um tempo, e (dois) tempos e metade de um tempo’, isto é, por 31⁄2 anos]”. Veja BDB, p. 1105; KB, p. 1106; BHS, sobre Da 7:25 n. “b”; veja também 4:16 n.; 12:7 n.: “metade”.
====

[[v27-7-26]]

^<<v27-7-26,26>>^ E o próprio Tribunal^&#42;1^ passou a assentar-se, e tiraram-lhe finalmente seu próprio domínio, a fim de [o] aniquilar e destruir totalmente.^&#42;2^

[NOTE]
====
. Lit.: “Julgamento.”
. Lit.: “até o fim”.
====

[[v27-7-27]]

^<<v27-7-27,27>>^ “‘E o reino, e o domínio, e a grandiosidade dos reinos debaixo de todos os céus foram entregues ao povo que são os santos do Supremo.^&#42;1^ Seu^&#42;2^ reino é um reino de duração indefinida e a eles é que servirão e obedecerão todos os domínios.’

[NOTE]
====
. Veja v. 18 n.
. “Seu”, referindo-se ao “povo que são os santos”.
====

[[v27-7-28]]

^<<v27-7-28,28>>^ “Aqui termina o assunto. Quanto a mim, Daniel, amedrontavam-me muito os meus próprios pensamentos, de modo que até mesmo mudei de cor; mas o assunto mesmo eu guardei no meu próprio coração.”^&#42;1^

[NOTE]
====
. O aram. que começou em 2:4 termina aqui.
====

'''

xref:027-daniel/027-daniel-006.adoc#v27-6-0[&#60; Capítulo Anterior] | <<v27-7-0,Topo>> | xref:027-daniel/027-daniel-008.adoc#v27-8-0[Próximo Capítulo &#62;]