include::./index.adoc[]

[[v27-11-0]]
=== Daniel, 11
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v27-11-1]]

^<<v27-11-1,1>>^ “E quanto a mim, no primeiro ano de Dario,^&#42;1^ o medo, pus-me de pé como fortalecedor e como baluarte para ele.

[NOTE]
====
. “Dario”, MSyVg; LXX: “Ciro”. Veja 5:31 n.: “Dario”.
====

[[v27-11-2]]

^<<v27-11-2,2>>^ E agora te contarei a verdade:
“Eis que ainda se porão de pé três reis para a Pérsia, e o quarto acumulará maiores riquezas do que todos [os outros]. E assim que se tiver tornado forte nas suas riquezas, incitará tudo contra o reino da Grécia.^&#42;1^

[NOTE]
====
. “Grécia.” Lat.: Graé·ci·ae; LXX: “dos gregos”; hebr.: Ya·wán, “Javã”.
====

[[v27-11-3]]

^<<v27-11-3,3>>^ “E um rei poderoso^&#42;1^ se há de pôr de pé, e ele há de dominar com domínio^&#42;2^ extenso e fazer segundo o seu bel-prazer.^&#42;3^

[NOTE]
====
. “Poderoso.” Hebr.: gib·bóhr.
. Ou “governo”.
. Ou “segundo a sua vontade”. Hebr.: kir·tsoh·nóh.
====

[[v27-11-4]]

^<<v27-11-4,4>>^ E quando se tiver posto de pé, seu reino será destroçado e repartido para os quatro ventos^&#42;1^ dos céus, mas não para a sua posteridade e não segundo o seu domínio com que tinha dominado; porque seu reino será desarraigado, sim, para outros fora destes.

[NOTE]
====
. Ou “direções”. Hebr.: ru·hhóhth; gr.: a·né·mous; lat.: vén·tos.
====

[[v27-11-5]]

^<<v27-11-5,5>>^ “E o rei do sul^&#42;1^ se tornará forte, sim, [um] dos seus príncipes; e prevalecerá contra ele e certamente dominará com domínio extenso, [maior do que] o poder dominante dele.

[NOTE]
====
. “Rei do sul.” Hebr.: me·lekh-han·né·ghev.
====

[[v27-11-6]]

^<<v27-11-6,6>>^ “E ao fim de [alguns] anos aliar-se-ão um ao outro e a própria filha do rei do sul chegará ao rei do norte^&#42;1^ para estabelecer um acordo eqüitativo. Mas ela não reterá o poder do seu braço; e ele não ficará de pé, nem tampouco seu braço; e ela mesma será entregue, bem como os que a trouxeram e aquele que causou seu nascimento, e aquele que a tornou forte [naqueles] tempos.

[NOTE]
====
. “Rei do norte.” Hebr.: mé·lekh hats·tsa·fóhn.
====

[[v27-11-7]]

^<<v27-11-7,7>>^ E alguém procedente do rebentão das suas raízes há de pôr-se de pé na sua posição, e ele chegará à força militar e virá contra o baluarte do rei do norte, e certamente agirá contra ele e prevalecerá.

[[v27-11-8]]

^<<v27-11-8,8>>^ E chegará ao Egito também com os deuses deles,^&#42;1^ com as suas imagens fundidas, com os seus objetos desejáveis de prata e de ouro, [e] com os cativos. E ele mesmo se manterá [alguns] anos longe do rei do norte.

[NOTE]
====
. “Deuses deles.” Hebr.: ’elo·heh·hém, pl.; gr.: the·oús; lat.: dé·os.
====

[[v27-11-9]]

^<<v27-11-9,9>>^ “E ele entrará realmente no reino do rei do sul e retornará ao seu próprio solo.

[[v27-11-10]]

^<<v27-11-10,10>>^ “Ora, no que se refere aos seus filhos,^&#42;1^ excitar-se-ão e realmente ajuntarão uma multidão de grandes forças militares. E entrando, ele certamente chegará, e inundará, e passará. Mas retornará e se excitará^&#42;2^ até [chegar] ao seu baluarte.

[NOTE]
====
. “Filhos”, MmargemLXXBagsterVg; MLXX: “filho”.
. “Excitará”, MmargemLXXVg e muitos mss. hebr.; MSy: “excitarão”.
====

[[v27-11-11]]

^<<v27-11-11,11>>^ “E o rei do sul ficará amargurado e terá de sair e lutar contra ele, [isto é,] contra o rei do norte; e certamente fará erguer-se uma grande massa de gente, e a massa de gente será realmente entregue na mão daquele.

[[v27-11-12]]

^<<v27-11-12,12>>^ E a massa de gente há de ser levada embora. Seu coração se enaltecerá e fará cair realmente dezenas de milhares; mas não usará a sua forte posição.

[[v27-11-13]]

^<<v27-11-13,13>>^ “E o rei do norte terá de voltar e dispor uma massa de gente maior do que a primeira; e no fim dos tempos, [de alguns] anos, chegará, fazendo-o com uma grande força militar e com muitos bens.

[[v27-11-14]]

^<<v27-11-14,14>>^ E naqueles tempos haverá muitos que se erguerão contra o rei do sul.
“E os filhos dos salteadores do teu povo, da sua parte, serão levados a tentar fazer uma visão tornar-se realidade; e terão de tropeçar.

[[v27-11-15]]

^<<v27-11-15,15>>^ “E o rei do norte chegará e levantará^&#42;1^ um aterro de sítio, e realmente capturará uma cidade com fortificações. E quanto aos braços do sul, não se manterão firmes, tampouco o povo dos seus selecionados; e não haverá poder para se manter firme.

[NOTE]
====
. Lit.: “derramará”.
====

[[v27-11-16]]

^<<v27-11-16,16>>^ E aquele que chegará contra ele fará segundo o seu bel-prazer, e ninguém se manterá firme diante dele. E estará de pé na terra do Ornato, e haverá extermínio^&#42;1^ na sua mão.

[NOTE]
====
. “Haverá extermínio”, M; mediante uma mudança dos sinais vocálicos: “toda ela estará”.
====

[[v27-11-17]]

^<<v27-11-17,17>>^ E ele fixará a sua face para vir com o poderio de todo o seu reino, e haverá um [acordo] eqüitativo com ele; e agirá com eficiência. E quanto à filha de mulher,^&#42;1^ ser-lhe-á concedido arruiná-la. E ela não se manterá firme e não continuará a pertencer-lhe.

[NOTE]
====
. Lit.: “das mulheres”.
====

[[v27-11-18]]

^<<v27-11-18,18>>^ E ele voltará a sua face para as terras litorâneas^&#42;1^ e realmente capturará muitas. E um comandante terá de fazer o vitupério procedente dele cessar para si, [de modo que] não existirá seu vitupério. Fará que retorne àquele.

[NOTE]
====
. Ou “ilhas”.
====

[[v27-11-19]]

^<<v27-11-19,19>>^ E [ele] voltará a sua face para os baluartes da sua [própria] terra, e certamente tropeçará e cairá, e não será [mais] achado.

[[v27-11-20]]

^<<v27-11-20,20>>^ “E na sua posição terá de erguer-se alguém que fará um exator^&#42;1^ passar pelo esplendoroso reino^&#42;2^ e em poucos dias^&#42;3^ será destroçado, mas não em ira nem em guerra.

[NOTE]
====
. “Um exator”, possivelmente de impostos. Ou “feitor”. Hebr.: noh·ghés. Veja 2Rs 23:35.
. Lit.: “pelo esplendor dum reino”.
. “Em poucos dias”, MVg; um ms. hebr.: “em dias posteriores”; LXX: “em dias finais (mais longínquos)”.
====

[[v27-11-21]]

^<<v27-11-21,21>>^ “E na sua posição terá de erguer-se um que há de ser desprezado, e certamente não colocarão sobre ele a dignidade do reino; e realmente chegará durante a despreocupação e apossar-se-á do reino por meio de insídia.^&#42;1^

[NOTE]
====
. Ou “conduta [ou: declarações] lisonjeira[s]”.
====

[[v27-11-22]]

^<<v27-11-22,22>>^ E quanto aos braços da inundação, serão inundados por sua causa e serão destroçados; assim como também [o será] o Líder do pacto.

[[v27-11-23]]

^<<v27-11-23,23>>^ E por se aliarem a ele, praticará o engano e realmente subirá e se tornará forte por meio de uma nação pequena.^&#42;1^

[NOTE]
====
. Lit.: “pouquidade de nação”.
====

[[v27-11-24]]

^<<v27-11-24,24>>^ Durante a despreocupação entrará até mesmo na fartura do distrito jurisdicional e fará realmente aquilo que seus pais e os pais de seus pais não fizeram. Espalhará entre eles saque, e despojo, e bens; e maquinará os seus ardis contra as praças fortes, mas apenas até um tempo.

[[v27-11-25]]

^<<v27-11-25,25>>^ “E ele despertará seu poder e seu coração contra o rei do sul, com uma grande força militar; e o rei do sul, da sua parte, excitar-se-á para a guerra com uma força militar extraordinariamente grande e poderosa. E ele não se manterá de pé, porque maquinarão ardis contra os seus ardis.

[[v27-11-26]]

^<<v27-11-26,26>>^ E os mesmos que comem os seus petiscos^&#42;1^ causarão a sua derrocada.
“E quanto à sua força militar, será levada de enxurrada^&#42;2^ e muitos hão de cair mortos.

[NOTE]
====
. Ou “à sua mesa [de refeições]”.
. “Transbordará”, MLXX; LXXBagster: “arrasará (exércitos)”; Sy: “será espalhada”; Vg: “será derrubada”.
====

[[v27-11-27]]

^<<v27-11-27,27>>^ “E no que se refere a estes dois reis, seu coração se inclinará a fazer o que é mau, e a uma só mesa continuarão a falar mentira. Mas nada será bem sucedido, porque [o] fim é ainda para o tempo designado.

[[v27-11-28]]

^<<v27-11-28,28>>^ “E ele retornará à sua terra com grande quantidade de bens, e seu coração será contra o pacto sagrado. E agirá com eficiência e certamente retornará à sua terra.

[[v27-11-29]]

^<<v27-11-29,29>>^ “Retornará no tempo designado^&#42;1^ e virá realmente contra o sul;^&#42;2^ mas no fim não virá a ser como foi no princípio.

[NOTE]
====
. “No tempo designado.” Hebr.: lam·moh·‛édh.
. “Contra o sul.” Hebr.: van·né·ghev.
====

[[v27-11-30]]

^<<v27-11-30,30>>^ E certamente virão contra ele os navios de Quitim^&#42;1^ e ele terá de ficar desalentado.
“E ele realmente voltará e lançará verberações contra o pacto sagrado e agirá com eficiência; e terá de voltar e dará consideração aos que abandonam o pacto sagrado.

[NOTE]
====
. “Navios de Quitim”, M; LXX: “romanos”; Vg: “trirremes e romanos”.
====

[[v27-11-31]]

^<<v27-11-31,31>>^ E erguer-se-ão braços^&#42;1^ procedentes dele; e eles hão de profanar o santuário,^&#42;2^ o baluarte,^&#42;3^ e remover o [sacrifício] contínuo.^&#42;4^
“E hão de constituir^&#42;5^ a coisa repugnante que causa desolação.^&#42;6^

[NOTE]
====
. Isto é, braços humanos, usados aqui simbolicamente.
. “O santuário.” Hebr.: ham·miq·dásh; LXXBagster(gr.): ha·gí·a·sma; lat.: sanc·tu·á·ri·um.
. Ou “a fortaleza”. Hebr.: ham·ma·‛óhz.
. “O [sacrifício] contínuo.” Hebr.: hat·ta·mídh; Vg: “o sacrifício contínuo”; LXX: “o sacrifício”. Veja 8:11 n.
. Lit.: “hão de dar”.
. Ou “que causa assombro”. Hebr.: meshoh·mém. Veja 9:27 n.: “desolado”.
====

[[v27-11-32]]

^<<v27-11-32,32>>^ “E os que agirem iniquamente contra [o] pacto, ele levará à apostasia por meio de palavras macias. Mas, quanto ao povo que conhece seu Deus,^&#42;1^ eles prevalecerão^&#42;2^ e agirão com eficiência.

[NOTE]
====
. “Seu Deus.” Hebr.: ’Elo·háv; “seu” referindo-se ao “povo”.
. Ou “mostrarão [ter] força”.
====

[[v27-11-33]]

^<<v27-11-33,33>>^ E quanto aos que dentre o povo tiverem perspicácia, darão entendimento a muitos. E certamente se fará que tropecem, pela espada e pela chama, pelo cativeiro e pelo saque, por [alguns] dias.^&#42;1^

[NOTE]
====
. “Por muitos dias”, muitos mss. e ed. hebr. impressos.
====

[[v27-11-34]]

^<<v27-11-34,34>>^ Mas, quando se fizer que tropecem serão ajudados com um pouco de ajuda; e muitos hão de juntar-se a eles por meio de insídia.^&#42;1^

[NOTE]
====
. Ou “conduta [ou: declarações] lisonjeira[s]”.
====

[[v27-11-35]]

^<<v27-11-35,35>>^ E far-se-á que tropecem alguns dos que têm perspicácia, a fim de se fazer uma obra de refinação por causa deles, e para se fazer uma limpeza e um embranquecimento, até o tempo do fim; porque é ainda para o tempo designado.^&#42;1^

[NOTE]
====
. “Para o tempo designado.” Hebr.: lam·moh·‛édh.
====

[[v27-11-36]]

^<<v27-11-36,36>>^ “E o rei fará realmente segundo o seu bel-prazer,^&#42;1^ e ele se enaltecerá e magnificará^&#42;2^ acima de todo deus;^&#42;3^ e falará coisas prodigiosas contra o Deus dos deuses.^&#42;4^ E certamente se mostrará bem sucedido até ter acabado [a] verberação; porque a coisa determinada terá de ser feita.

[NOTE]
====
. Ou “segundo a sua própria vontade”. Hebr.: khir·tsoh·nóh.
. Ou “e se jactará”.
. “Deus.” Hebr.: ’el; gr.: the·ón; lat.: dé·um.
. “Deus dos deuses.” Hebr.: ’El ’e·lím; lat.: Dé·um de·ó·rum.
====

[[v27-11-37]]

^<<v27-11-37,37>>^ E não dará consideração ao Deus^&#42;1^ de seus pais; e não dará consideração ao desejo de mulheres, nem a todo outro deus, porém, magnificar-se-á acima de todos os outros.

[NOTE]
====
. Ou “aos deuses”.
====

[[v27-11-38]]

^<<v27-11-38,38>>^ Mas dará glória ao deus dos baluartes,^&#42;1^ na sua posição; e dará glória a um deus que seus pais não conheceram, por meio de ouro, e por meio de prata, e por meio de pedras preciosas, e por meio de coisas desejáveis.

[NOTE]
====
. “Mas . . . ao deus dos baluartes (fortalezas).” Hebr.: wele·’eló·ah ma·‛uz·zím; lat.: dé·um aú·tem Má·o·zim.
====

[[v27-11-39]]

^<<v27-11-39,39>>^ E agirá com eficiência contra os baluartes mais fortificados, junto com um deus estrangeiro. Àquele que [lhe] der reconhecimento ele fará abundar com glória, e realmente fará tais dominar entre muitos; e repartirá [o] solo por um preço.

[[v27-11-40]]

^<<v27-11-40,40>>^ “E, no tempo do fim, o rei do sul^&#42;1^ se empenhará com ele em dar empurrões, e o rei do norte^&#42;2^ arremeterá contra ele com carros, e com cavaleiros, e com muitos navios; e ele há de entrar nas terras, e inundar, e passar.

[NOTE]
====
. Veja v. 5 n.
. Veja v. 6 n.
====

[[v27-11-41]]

^<<v27-11-41,41>>^ Também entrará realmente na terra do Ornato^&#42;1^ e haverá muitas^&#42;2^ [terras] que se farão tropeçar. Mas, estes são os que escaparão da sua mão: Edom e Moabe, e a parte principal^&#42;3^ dos filhos de Amom.

[NOTE]
====
. Ou “na terra ornada (bela)”. Hebr.: be’é·rets hats·Tseví.
. “Muitas”, hebr. fem., evidentemente referindo-se a terras, hebr. fem.
. Lit.: “o princípio”.
====

[[v27-11-42]]

^<<v27-11-42,42>>^ E continuará a estender a sua mão contra as terras; e no que se refere à terra do Egito, não virá a ser uma que escapou.

[[v27-11-43]]

^<<v27-11-43,43>>^ E ele dominará realmente sobre os tesouros ocultos de ouro e de prata e sobre todas as coisas desejáveis do Egito. E os líbios^&#42;1^ e os etíopes^&#42;2^ [acompanharão] os seus passos.

[NOTE]
====
. “E os líbios”, M(hebr.: weLu·vím)LXX; lat.: Lý·bi·as.
. “E os etíopes.” Hebr.: we·Khu·shím; gr.: kai Ai·thí·o·pes; lat.: et Ae·thi·ó·pi·as.
====

[[v27-11-44]]

^<<v27-11-44,44>>^ “Mas, haverá notícias^&#42;1^ que o perturbarão, procedentes do nascente e do norte, e ele há de sair em grande furor para aniquilar e para devotar muitos à destruição.

[NOTE]
====
. Lit.: “coisas ouvidas”.
====

[[v27-11-45]]

^<<v27-11-45,45>>^ E armará suas tendas palaciais entre [o] grande mar^&#42;1^ e o monte santo do Ornato;^&#42;2^ e terá de chegar até o seu fim, e não haverá quem o ajude.

[NOTE]
====
. “[O] grande mar.” Lit.: “mares”, MLXXVg; Sy: “mar”.
. Lit.: “ao monte de santo Ornato”. Hebr.: lehar-Tsevi-qó·dhesh.
====

'''

xref:027-daniel/027-daniel-010.adoc#v27-10-0[&#60; Capítulo Anterior] | <<v27-11-0,Topo>> | xref:027-daniel/027-daniel-012.adoc#v27-12-0[Próximo Capítulo &#62;]