include::./index.adoc[]

[[v27-4-0]]
=== Daniel, 4
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v27-4-1]]

^<<v27-4-1,1>>^ “Nabucodonosor, o rei, a todos os povos, grupos nacionais e línguas que habitam em toda a terra: Aumente a vossa paz.

[[v27-4-2]]

^<<v27-4-2,2>>^ Pareceu-me bem declarar os sinais e as maravilhas que o Deus Altíssimo realizou para comigo.

[[v27-4-3]]

^<<v27-4-3,3>>^ Quão grandiosos são os seus sinais e quão poderosas são as suas maravilhas! Seu reino é um reino por tempo indefinido e seu domínio é para geração após geração.

[[v27-4-4]]

^<<v27-4-4,4>>^ ^&#42;1^ “Eu, Nabucodonosor, vim a estar tranqüilo na minha casa e a prosperar no meu palácio.

[NOTE]
====
. MLXXBagsterVg começam aqui o cap. 4.
====

[[v27-4-5]]

^<<v27-4-5,5>>^ Houve um sonho que tive e ele começou a atemorizar-me. E havia imagens mentais sobre a minha cama e visões da minha cabeça que começaram a amedrontar-me.

[[v27-4-6]]

^<<v27-4-6,6>>^ E dei ordem para que se fizessem entrar perante mim todos os sábios de Babilônia, a fim de que me fizessem saber a própria interpretação do sonho.

[[v27-4-7]]

^<<v27-4-7,7>>^ “Naquele tempo entraram os sacerdotes-magos, os conjuradores, os caldeus e os astrólogos; e eu relatava na frente deles qual tinha sido o sonho, mas não me fizeram saber a sua interpretação.

[[v27-4-8]]

^<<v27-4-8,8>>^ E por fim entrou perante mim Daniel, cujo nome é Beltessazar, segundo o nome de meu deus, e em quem há o espírito dos deuses^&#42;1^ santos; e relatei perante ele qual tinha sido o sonho:

[NOTE]
====
. Veja v. 18 n.
====

[[v27-4-9]]

^<<v27-4-9,9>>^ “‘Ó Beltessazar, chefe dos sacerdotes-magos, visto que eu mesmo bem sei que há em ti o espírito dos deuses santos e que não há absolutamente nenhum segredo^&#42;1^ que te perturbe, dize-me as visões do meu sonho que vi e a sua interpretação.

[NOTE]
====
. “Segredo.” Aram.: raz; Th(gr.): my·sté·ri·on; lat.: sa·cra·mén·tum.
====

[[v27-4-10]]

^<<v27-4-10,10>>^ “‘Ora, aconteceu que eu estava vendo as visões da minha cabeça, sobre a minha cama, e eis que havia uma árvore no meio da terra, sendo enorme a sua altura.

[[v27-4-11]]

^<<v27-4-11,11>>^ A árvore tornou-se grande e ficou forte, e a própria altura dela por fim atingiu os céus, e ela era visível^&#42;1^ até a extremidade da terra inteira.

[NOTE]
====
. Lit.: “e o aspecto dela era”.
====

[[v27-4-12]]

^<<v27-4-12,12>>^ Sua folhagem era bela e seu fruto abundante, e havia nela alimento para todos. Debaixo dela os animais do campo procuravam sombra e nos seus galhos habitavam as aves dos céus, e toda a carne se alimentava dela.

[[v27-4-13]]

^<<v27-4-13,13>>^ “‘Eu continuei a ver nas visões da minha cabeça, sobre a minha cama, e eis que havia um vigilante,^&#42;1^ sim, um santo, descendo dos próprios céus.

[NOTE]
====
. “Um vigilante.” Aram.: ‛ir; LXXBagster(gr.): eir; gr.: ág·ge·los, “anjo”; lat.: ví·gil.
====

[[v27-4-14]]

^<<v27-4-14,14>>^ Ele clamava em alta [voz]^&#42;1^ e dizia o seguinte: “Derrubai a árvore e cortai-lhe os galhos. Sacudi a sua folhagem e espalhai os seus frutos. Fujam os animais de debaixo dela e as aves dos seus galhos.

[NOTE]
====
. Lit.: “com energia vital”.
====

[[v27-4-15]]

^<<v27-4-15,15>>^ Todavia, deixai-lhe o próprio toco na terra, sim, com banda de ferro e de cobre, entre a relva do campo; e seja molhado pelo orvalho dos céus e seja seu quinhão entre a vegetação da terra.

[[v27-4-16]]

^<<v27-4-16,16>>^ Mude-se-lhe o coração daquele do gênero humano e dê-se-lhe um coração de animal, e passem sobre ele sete tempos.^&#42;1^

[NOTE]
====
. Ou “tempos designados (definidos)”; ou: “períodos de tempo”. Aram.: ‛id·da·nín; gr.: é·te, “anos”; LXXBagster(gr.): kai·roí, “tempos designados”; lat.: tém·po·ra, “tempos”. “Anos”, BDB, p. 1105; KB, p. 1106; Lexicon Linguae Aramaicae Veteris Testamenti, de E. Vogt, Roma, 1971, p. 124. “Sete tempos”, visto que sete anos são duas vezes três tempos e meio. Veja 7:25 n.: “tempo”; 12:7 n.: “metade”.
====

[[v27-4-17]]

^<<v27-4-17,17>>^ A coisa é por decreto dos vigilantes^&#42;1^ e o pedido é [pela] declaração dos santos, para que os viventes saibam que o Altíssimo é Governante^&#42;2^ no reino da humanidade^&#42;3^ e que ele o dá a quem quiser, e estabelece nele até mesmo o mais humilde da humanidade.”^&#42;4^

[NOTE]
====
. “Vigilantes.” Aram.: ‛i·rín; LXXBagster(gr.): eir; lat.: ví·gi·lum.
. Ou “está governando”. Aram.: shal·lít.
. “Humanidade.” Aram.: ’anow·shá’.
. “E . . . o mais humilde da humanidade.” Aram.: u·shefál ’ana·shím (pl. de ’enásh).
====

[[v27-4-18]]

^<<v27-4-18,18>>^ “‘Este foi o sonho visto por mim, o Rei Nabucodonosor; e tu mesmo, ó Beltessazar, dize qual é a interpretação, visto que todos os [outros] sábios do meu reino são incapazes de me fazerem saber a própria interpretação. Mas tu és competente, porque há em ti o espírito de deuses^&#42;1^ santos.’

[NOTE]
====
. “Espírito de deuses.” Aram.: ruahh-’ela·hín; lat.: spí·ri·tus de·ó·rum.
====

[[v27-4-19]]

^<<v27-4-19,19>>^ “Nisso o próprio Daniel, cujo nome é Beltessazar, ficou por um momento estarrecido e seus próprios pensamentos começaram a amedrontá-lo.
“O rei respondeu e disse: ‘Ó Beltessazar, não te amedrontem o sonho e a interpretação.’
“Beltessazar respondeu e disse: ‘Ó meu senhor,^&#42;1^ [aplique-se] o sonho aos que te odeiam e a sua interpretação aos teus adversários.

[NOTE]
====
. “Ó meu senhor.” Aram.: ma·ri’ý.
====

[[v27-4-20]]

^<<v27-4-20,20>>^ “‘A árvore que viste, que se tornou grande e ficou forte, e cuja altura finalmente atingiu os céus, e que era visível a toda a terra,

[[v27-4-21]]

^<<v27-4-21,21>>^ e cuja folhagem era bela e cujo fruto era abundante, e em que havia alimento para todos; debaixo da qual habitavam os animais do campo e em cujos galhos residiam as aves dos céus,

[[v27-4-22]]

^<<v27-4-22,22>>^ és tu, ó rei, porque te tornaste grande e ficaste forte, e tua grandiosidade cresceu e atingiu os céus, e teu domínio, a extremidade da terra.

[[v27-4-23]]

^<<v27-4-23,23>>^ “‘E sendo que o rei viu um vigilante,^&#42;1^ sim, um santo, descendo dos céus, dizendo também: “Derrubai a árvore e arruinai-a. Todavia, deixai-lhe o toco na terra, mas com banda de ferro e de cobre, entre a relva do campo, e seja molhado pelo orvalho dos céus e seja seu quinhão com os animais do campo, até terem passado sobre ele sete tempos”,^&#42;2^

[NOTE]
====
. “Um vigilante.” Aram.: ‛ir; LXXBagster(gr.): eir; lat.: ví·gi·lem.
. Veja v. 16 n.
====

[[v27-4-24]]

^<<v27-4-24,24>>^ esta é a interpretação, ó rei, e o decreto do Altíssimo é o que tem de sobrevir ao meu senhor,^&#42;1^ o rei.

[NOTE]
====
. “Meu senhor.” Aram.: ma·ri’ý.
====

[[v27-4-25]]

^<<v27-4-25,25>>^ E expulsar-te-ão de entre os homens e tua morada virá a ser com os animais do campo, e vegetação é o que te darão para comer, como a touros; e tu mesmo virás a ser molhado pelo orvalho dos céus, e passarão mesmo sete tempos^&#42;1^ sobre ti, até saberes que o Altíssimo é Governante^&#42;2^ no reino da humanidade^&#42;3^ e que ele o dá a quem quiser.

[NOTE]
====
. Veja v. 16 n.
. Ou “está governando”.
. Ou “dos homens”. Aram.: ’ana·shá’.
====

[[v27-4-26]]

^<<v27-4-26,26>>^ “‘E por terem dito que se deixasse o toco da árvore, teu reino te estará assegurado depois de saberes que são os céus que governam.

[[v27-4-27]]

^<<v27-4-27,27>>^ Portanto, ó rei, pareça-te bom o meu conselho, e remove os teus próprios pecados por meio da justiça e a tua iniqüidade por teres misericórdia para com os pobres. Talvez venha a haver um prolongamento da tua prosperidade.’”

[[v27-4-28]]

^<<v27-4-28,28>>^ Tudo isso sobreveio a Nabucodonosor, o rei.

[[v27-4-29]]

^<<v27-4-29,29>>^ Ao fim de doze meses lunares aconteceu que ele estava passeando sobre o palácio real de Babilônia.

[[v27-4-30]]

^<<v27-4-30,30>>^ O rei respondeu e disse: “Não é esta Babilônia, a Grande, que eu mesmo construí para a casa real com o poderio da minha potência e para a dignidade da minha majestade?”

[[v27-4-31]]

^<<v27-4-31,31>>^ Enquanto a palavra estava ainda na boca do rei, houve uma voz baixando dos céus: “A ti se diz, ó Nabucodonosor, o rei: ‘O próprio reino se afastou de ti

[[v27-4-32]]

^<<v27-4-32,32>>^ e a ti mesmo expulsarão de entre a humanidade, e tua morada será com os animais do campo. A ti mesmo darão vegetação para comer, como a touros, e sete tempos^&#42;1^ é que passarão sobre ti, até saberes que o Altíssimo é Governante^&#42;2^ no reino da humanidade^&#42;3^ e que ele o dá a quem quiser.’”

[NOTE]
====
. Veja v. 16 n.
. Ou “está governando”.
. Veja v. 25 n.: “humanidade”.
====

[[v27-4-33]]

^<<v27-4-33,33>>^ Naquele instante cumpriu-se a própria palavra em Nabucodonosor e ele foi expulso de entre a humanidade, e começou a comer vegetação como os touros, e seu próprio corpo foi molhado pelo orvalho dos céus, até que seu cabelo ficou tão comprido como [penas de] águias, e suas unhas, como [garras] de aves.

[[v27-4-34]]

^<<v27-4-34,34>>^ “E ao fim dos dias, eu, Nabucodonosor, levantei os olhos ao céu e meu próprio entendimento começou a retornar a mim; e eu bendisse o próprio Altíssimo, e louvei e glorifiquei Aquele que vive por tempo indefinido, porque seu domínio é um domínio por tempo indefinido e seu reino é para geração após geração.

[[v27-4-35]]

^<<v27-4-35,35>>^ E todos os habitantes da terra são considerados como simplesmente nada, e ele age segundo a sua própria vontade^&#42;1^ entre o exército dos céus e os habitantes da terra. E não há quem lhe possa deter a mão ou quem lhe possa dizer: ‘Que estás fazendo?’

[NOTE]
====
. Ou “e . . . segundo o seu próprio desejo”. Aram.: u·khemits·beyéh, um infinitivo.
====

[[v27-4-36]]

^<<v27-4-36,36>>^ “Ao mesmo tempo começou a retornar a mim o meu próprio entendimento, e para a dignidade do meu reino começaram a retornar a mim a minha majestade e o meu esplendor; e até mesmo os meus altos funcionários reais e os meus grandes começaram a procurar-me ansiosamente, e fui restabelecido no meu próprio reino e acrescentou-se-me extraordinária grandeza.

[[v27-4-37]]

^<<v27-4-37,37>>^ “Agora, eu, Nabucodonosor, louvo, e enalteço, e glorifico o Rei dos céus, porque todas as suas obras são verdade e seus caminhos são justiça,^&#42;1^ e porque ele é capaz de humilhar os que andam em orgulho.”

[NOTE]
====
. Ou “julgamento”. Aram.: din.
====

'''

xref:027-daniel/027-daniel-003.adoc#v27-3-0[&#60; Capítulo Anterior] | <<v27-4-0,Topo>> | xref:027-daniel/027-daniel-005.adoc#v27-5-0[Próximo Capítulo &#62;]