include::./index.adoc[]

[[v27-6-0]]
=== Daniel, 6
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v27-6-1]]

^<<v27-6-1,1>>^ Pareceu bem a Dario, e ele estabeleceu sobre o reino cento e vinte sátrapas que estariam sobre o reino inteiro;

[[v27-6-2]]

^<<v27-6-2,2>>^ e sobre eles três altos funcionários, dos quais Daniel era um, para que estes sátrapas lhes dessem continuamente o relatório e o próprio rei não saísse perdendo.

[[v27-6-3]]

^<<v27-6-3,3>>^ Foi então que este Daniel constantemente se distinguia entre os altos funcionários e os sátrapas, visto que havia nele um espírito^&#42;1^ extraordinário; e o rei intencionava elevá-lo sobre todo o reino.

[NOTE]
====
. “Espírito.” Aram.: rú·ahh; LXXBagster(gr.): pneú·ma; lat.: spí·ri·tus.
====

[[v27-6-4]]

^<<v27-6-4,4>>^ Naquele tempo, os próprios altos funcionários e os sátrapas procuravam constantemente achar um pretexto contra Daniel com respeito ao reino; mas não havia pretexto nem coisa corrupta alguma que pudessem achar, pois era digno de confiança, e não se achava nele nenhuma coisa negligente ou corrupta.

[[v27-6-5]]

^<<v27-6-5,5>>^ Por conseguinte, estes varões vigorosos diziam: “Não acharemos neste Daniel nenhum pretexto a não ser que [o] encontremos contra ele na lei de seu Deus.”^&#42;1^

[NOTE]
====
. “Seu Deus.” Aram.: ’Ela·héh; lat.: Dé·i sú·i.
====

[[v27-6-6]]

^<<v27-6-6,6>>^ Concordemente, estes altos funcionários e sátrapas entraram em conjunto até o rei e disseram-lhe o seguinte: “Ó Dario, o rei, vive por tempos indefinidos.

[[v27-6-7]]

^<<v27-6-7,7>>^ Todos os altos funcionários do reino, os prefeitos e os sátrapas, os altos funcionários reais e os governadores, em conselho, deliberaram estabelecer um estatuto real e pôr em vigor um interdito, de que todo aquele que fizer petição a qualquer deus ou homem^&#42;1^ sem ser a ti, durante trinta dias, ó rei, seja lançado na cova dos leões.

[NOTE]
====
. “Deus ou homem.” Aram.: ’eláh we·’enásh; lat.: dé·o et hó·mi·ne.
====

[[v27-6-8]]

^<<v27-6-8,8>>^ Agora, ó rei, estabelece o estatuto e assina a escritura, para que não seja mudado, segundo a lei dos medos e dos persas, que é irrevogável.”

[[v27-6-9]]

^<<v27-6-9,9>>^ Em conformidade com isso, o próprio Rei Dario assinou a escritura e o interdito.

[[v27-6-10]]

^<<v27-6-10,10>>^ Daniel, porém, assim que soube que se assinara a escritura, entrou na sua casa, e, com as janelas do seu quarto de terraço abertas para ele do lado de Jerusalém, foi pôr-se de joelhos, até mesmo três vezes por dia, e orava e oferecia louvor perante seu Deus,^&#42;1^ assim como havia feito regularmente antes disso.

[NOTE]
====
. “Seu Deus.” Aram.: ’Ela·héh.
====

[[v27-6-11]]

^<<v27-6-11,11>>^ Então estes mesmos varões vigorosos entraram em massa e acharam Daniel fazendo petição e implorando favor perante seu Deus.

[[v27-6-12]]

^<<v27-6-12,12>>^ Foi então que se chegaram e disseram perante o rei a respeito do interdito do rei: “Não assinaste um interdito no sentido de que todo homem que fizesse uma petição a qualquer deus ou homem sem ser a ti, durante trinta dias, ó rei, fosse lançado na cova dos leões?” O rei respondeu e disse: “O assunto está bem estabelecido segundo a lei dos medos e dos persas, que é irrevogável.”

[[v27-6-13]]

^<<v27-6-13,13>>^ Responderam imediatamente e disseram perante o rei: “Daniel, que é dos exilados^&#42;1^ de Judá, não fez caso de ti, ó rei, nem do interdito que assinaste, mas está fazendo a sua petição três vezes por dia.”

[NOTE]
====
. Veja 2:25 n.
====

[[v27-6-14]]

^<<v27-6-14,14>>^ Por conseguinte, assim que o rei ouviu a palavra, desagradava-lhe isso muito, e ele fixou a mente em Daniel para salvá-lo; e até o pôr-do-sol se esforçava em livrá-lo.

[[v27-6-15]]

^<<v27-6-15,15>>^ Por fim entraram estes mesmos varões vigorosos em conjunto até o rei e disseram ao rei: “Fica sabendo, ó rei, que a lei dos medos e dos persas é que qualquer interdito ou estatuto estabelecido pelo próprio rei é imutável.”

[[v27-6-16]]

^<<v27-6-16,16>>^ Concordemente, o próprio rei deu ordens,^&#42;1^ e trouxeram Daniel e o lançaram na cova dos leões. O rei respondeu e disse a Daniel: “Teu Deus,^&#42;2^ a quem serves com constância, ele mesmo te salvará.”

[NOTE]
====
. Lit.: “disse”.
. “Teu Deus.” Aram.: ’Ela·hákh; LXXBagster(gr.): The·ós; lat.: Dé·us.
====

[[v27-6-17]]

^<<v27-6-17,17>>^ E trouxe-se uma pedra e ela foi colocada sobre a boca da cova, e o rei selou-a com o seu anel de sinete e com o anel de sinete dos seus grandes, para que não se mudasse nada no caso de Daniel.

[[v27-6-18]]

^<<v27-6-18,18>>^ Então, o rei foi ao palácio e passou a noite jejuando, e não se levaram perante ele nenhuns instrumentos musicais,^&#42;1^ e fugia-lhe o próprio sono.

[NOTE]
====
. Ou “dançarinas”; ou “concubinas”.
====

[[v27-6-19]]

^<<v27-6-19,19>>^ Finalmente, o próprio rei, de madrugada, passou a levantar-se ao clarear o dia e foi apressadamente à cova dos leões.

[[v27-6-20]]

^<<v27-6-20,20>>^ E ao chegar perto da cova, clamou com voz triste a Daniel. O rei falou e disse a Daniel: “Ó Daniel, servo do Deus vivente, pôde o teu Deus,^&#42;1^ a quem serves com constância, salvar-te dos leões?”

[NOTE]
====
. Veja v. 16 n.: “Deus”.
====

[[v27-6-21]]

^<<v27-6-21,21>>^ O próprio Daniel falou imediatamente ao rei: “Ó rei, vive por tempos indefinidos.

[[v27-6-22]]

^<<v27-6-22,22>>^ Meu próprio Deus enviou seu anjo e fechou a boca dos leões, e eles não me causaram dano, pois diante dele se achou em mim a própria inocência; e também perante ti, ó rei, não fiz nada prejudicial.”

[[v27-6-23]]

^<<v27-6-23,23>>^ Nisso o próprio rei se alegrou muito e ordenou que o próprio Daniel fosse retirado da cova. E Daniel foi retirado da cova e não se achou nenhum dano nele, porque confiara em seu Deus.

[[v27-6-24]]

^<<v27-6-24,24>>^ E o rei deu ordens, e trouxeram aqueles varões vigorosos que acusaram^&#42;1^ a Daniel e lançaram-nos na cova dos leões, [com] seus filhos e suas esposas; e nem tinham atingido o fundo quando os leões já os dominaram, e foram esmiuçados todos os seus ossos.

[NOTE]
====
. Ou “caluniaram”. Lit.: “comeram os pedaços [de carne arrancados do corpo] de”.
====

[[v27-6-25]]

^<<v27-6-25,25>>^ Foi então que o próprio Dario,^&#42;1^ o rei, escreveu a todos os povos, grupos nacionais e línguas que habitavam em toda a terra: “Aumente muito a vossa paz!

[NOTE]
====
. Veja 5:31 n.: “Dario”.
====

[[v27-6-26]]

^<<v27-6-26,26>>^ De diante de mim se deu ordem para que em todo o domínio do meu reino as pessoas tremam e temam diante do Deus de Daniel. Porque ele é o Deus vivente e Aquele que permanece por tempos indefinidos, e seu reino é um que não será arruinado e seu domínio^&#42;1^ é para sempre.^&#42;2^

[NOTE]
====
. Ou “e seu governo (soberania)”. Aram.: weshol·ta·néh. Veja Sal 103:22 n.
. Lit.: “até o fim”.
====

[[v27-6-27]]

^<<v27-6-27,27>>^ Ele salva, e livra, e realiza sinais e maravilhas nos céus e na terra, pois salvou a Daniel da pata dos leões.”

[[v27-6-28]]

^<<v27-6-28,28>>^ E quanto a este Daniel, ele prosperou no reino de Dario^&#42;1^ e no reino de Ciro,^&#42;2^ o persa.

[NOTE]
====
. Veja 5:31 n.: “Dario”.
. Veja 1:21 n.
====

'''

xref:027-daniel/027-daniel-005.adoc#v27-5-0[&#60; Capítulo Anterior] | <<v27-6-0,Topo>> | xref:027-daniel/027-daniel-007.adoc#v27-7-0[Próximo Capítulo &#62;]