include::./index.adoc[]

[[v27-8-0]]
=== Daniel, 8
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v27-8-1]]

^<<v27-8-1,1>>^ No terceiro ano do reinado de Belsazar, o rei, apareceu-me uma visão, a mim, Daniel, depois daquela que me apareceu no início.

[[v27-8-2]]

^<<v27-8-2,2>>^ E comecei a ver na visão; e sucedeu, enquanto eu estava vendo, que eu estava em Susã, o castelo, que está no distrito jurisdicional de Elão; e passei a ver na visão, e eu mesmo vim a estar junto ao curso de água^&#42;1^ do Ulai.

[NOTE]
====
. Ou “junto ao canal”. Hebr.: ‛al·’u·vál.
====

[[v27-8-3]]

^<<v27-8-3,3>>^ Quando levantei os olhos então vi, e eis um carneiro de pé diante do curso de água, e ele tinha dois chifres. E os dois chifres eram altos, porém, um era mais alto do que o outro,^&#42;1^ e o mais alto é que subira depois.

[NOTE]
====
. Lit.: “o segundo”.
====

[[v27-8-4]]

^<<v27-8-4,4>>^ Vi o carneiro dar marradas para o oeste,^&#42;1^ e para o norte, e para o sul,^&#42;2^ e nenhum dos animais selváticos se manteve de pé diante dele, e não havia quem livrasse da sua mão. E ele fez segundo o seu bel-prazer^&#42;3^ e assumiu ares de grandeza.

[NOTE]
====
. Lit.: “o mar”, isto é, o Mar Mediterrâneo, ao oeste.
. Lit.: “o Negebe”.
. Ou “segundo a sua vontade”. Hebr.: khir·tso·nóh.
====

[[v27-8-5]]

^<<v27-8-5,5>>^ E eu, da minha parte, estava ponderando, e eis que vinha um bode dos caprídeos desde o poente sobre a superfície de toda a terra,^&#42;1^ e ele não tocava na terra. E quanto ao bode, havia entre os seus olhos um chifre proeminente.

[NOTE]
====
. “A terra.” Hebr.: ha·’á·rets.
====

[[v27-8-6]]

^<<v27-8-6,6>>^ E ele foi chegando ao carneiro dos dois chifres, que eu vira estar de pé diante do curso de água;^&#42;1^ e vinha correndo em direção a ele em seu poderoso furor.

[NOTE]
====
. Ou “do canal”. Hebr.: ha·’u·vál.
====

[[v27-8-7]]

^<<v27-8-7,7>>^ E eu o vi atingir o carneiro, e começou a mostrar amargura para com ele, e passou a golpear o carneiro e a quebrar-lhe os dois chifres, e mostrou-se não haver poder no carneiro para se manter de pé diante dele. De modo que o lançou por terra e o pisoteou, e o carneiro não mostrou ter alguém que o livrasse da sua mão.

[[v27-8-8]]

^<<v27-8-8,8>>^ E o bode dos caprídeos, da sua parte, assumiu ares de grandeza, em extremo; mas, assim que se tornou forte, foi quebrado o grande chifre, e passaram a subir de modo proeminente quatro em lugar dele, em direção aos quatro ventos^&#42;1^ dos céus.

[NOTE]
====
. Ou “direções”. Veja 11:4 n.
====

[[v27-8-9]]

^<<v27-8-9,9>>^ E de um deles saiu outro chifre, um pequeno, e este se tornava muito maior para o sul,^&#42;1^ e para o nascente, e para o Ornato.^&#42;2^

[NOTE]
====
. Ou “o Negebe”.
. Ou “a Beleza”. Possivelmente referindo-se a Jerusalém e ao seu templo. Veja 11:16, 41.
====

[[v27-8-10]]

^<<v27-8-10,10>>^ E tornava-se cada vez maior até [atingir] o exército dos céus, de modo que fez alguns do exército e algumas das estrelas cair para a terra, e foi pisoteá-los.

[[v27-8-11]]

^<<v27-8-11,11>>^ E assumiu ares de grandeza para com o Príncipe do exército, e foi-lhe tirado o [sacrifício] contínuo^&#42;1^ e foi deitado abaixo o lugar estabelecido do seu santuário.

[NOTE]
====
. “O [sacrifício] contínuo”, M(hebr.: hat·ta·mídh)Sy; lat.: iú·ge sa·cri·fí·ci·um, “o sacrifício contínuo”; LXXBagster(gr.): thy·sí·a, “sacrifício”.
====

[[v27-8-12]]

^<<v27-8-12,12>>^ E aos poucos foi entregue o próprio exército, junto com o [sacrifício] contínuo, por causa da transgressão; e ele continuou a lançar a verdade por terra, e agiu e foi bem sucedido.

[[v27-8-13]]

^<<v27-8-13,13>>^ E eu estava ouvindo certo santo falar, e outro santo passou a dizer àquele que falava: “Até quando durará a visão do [sacrifício] contínuo e da transgressão que causa desolação,^&#42;1^ para fazer tanto [do] lugar santo como [do] exército algo a ser pisoteado?”

[NOTE]
====
. Ou “causa assombro (horror)”. Hebr.: sho·mém. Veja 9:27 n.: “desolado”.
====

[[v27-8-14]]

^<<v27-8-14,14>>^ Ele me disse, pois: “Até duas mil e trezentas noitinhas [e] manhãs; e [o] lugar santo certamente será levado à sua condição correta.”^&#42;1^

[NOTE]
====
. Ou “terá de ser justificado (declarado justo)”; ou: “terá de ser estabelecido no seu direito”.
====

[[v27-8-15]]

^<<v27-8-15,15>>^ Sucedeu então, enquanto eu, Daniel, estava tendo a visão e procurando compreensão, ora, eis que estava parado na minha frente alguém da aparência de um varão vigoroso.^&#42;1^

[NOTE]
====
. “Um varão vigoroso.” Hebr.: ghá·ver.
====

[[v27-8-16]]

^<<v27-8-16,16>>^ E comecei a ouvir a voz de um homem terreno no meio do Ulai,^&#42;1^ e ele passou a clamar e a dizer: “Gabriel,^&#42;2^ faze aquele ali entender a coisa vista.”

[NOTE]
====
. Ou “Eulaeus”. LXXBagster(gr.): Ou·bál; gr.: Ou·lai; lat.: Ú·lai.
. Significando “Um Vigoroso de Deus”. Hebr.: Gav·ri·’él, uma combinação de gé·ver, “varão vigoroso”, e ’El, “Deus”.
====

[[v27-8-17]]

^<<v27-8-17,17>>^ Portanto, ele chegou até onde eu estava parado, mas quando chegou fiquei apavorado, de modo que me lancei com a face [por terra]. E ele passou a dizer-me: “Entende, ó filho do homem,^&#42;1^ que^&#42;2^ a visão é para o tempo do fim.”

[NOTE]
====
. “Filho do homem.” Hebr.: ben-’a·dhám. Veja 7:13 n.; Ez 2:1 n.
. Ou “porque”.
====

[[v27-8-18]]

^<<v27-8-18,18>>^ E enquanto ele falara comigo, eu adormecera com a face por terra. Portanto, ele me tocou e me fez ficar de pé onde eu estivera parado.

[[v27-8-19]]

^<<v27-8-19,19>>^ E prosseguiu, dizendo: “Eis que te faço saber o que ocorrerá na parte final da verberação, porque é para o tempo designado^&#42;1^ do fim.

[NOTE]
====
. Ou “para o designado tempo”. Hebr.: lemoh·‛édh.
====

[[v27-8-20]]

^<<v27-8-20,20>>^ “O carneiro que viste, tendo dois chifres, [representa] os reis da Média e da Pérsia.

[[v27-8-21]]

^<<v27-8-21,21>>^ E o bode peludo [representa] o rei da Grécia;^&#42;1^ e quanto ao chifre grande que havia entre os seus olhos, este [representa] o primeiro rei.

[NOTE]
====
. “Grécia.” Hebr.: Ya·wán, “Javã”; gr.: Hel·lé·non, “os helenos (gregos)”; lat.: Grae·có·rum, “dos gregos”.
====

[[v27-8-22]]

^<<v27-8-22,22>>^ E que este foi quebrado, de modo que por fim se ergueram quatro em seu lugar, haverá quatro reinos que se erguerão de [sua]^&#42;1^ nação, mas não com o seu poder.

[NOTE]
====
. “Sua”, LXXVg; MSy omitem isso.
====

[[v27-8-23]]

^<<v27-8-23,23>>^ “E na parte final do reino deles, completando os transgressores a sua ação, erguer-se-á um rei de semblante feroz e entendendo declarações ambíguas.^&#42;1^

[NOTE]
====
. Ou “enigmas, perguntas desconcertantes”.
====

[[v27-8-24]]

^<<v27-8-24,24>>^ E seu poder terá de tornar-se grande, mas não pelo seu próprio poder. E causará a ruína dum modo prodigioso, e certamente se mostrará bem sucedido e agirá com eficiência. E realmente arruinará poderosos, também o povo constituído dos santos.

[[v27-8-25]]

^<<v27-8-25,25>>^ E, segundo a sua perspicácia,^&#42;1^ certamente fará também o engano bem sucedido na sua mão. E no seu coração assumirá ares de grandeza e arruinará a muitos durante a sua despreocupação. E pôr-se-á de pé contra o Príncipe dos príncipes, mas será destroçado sem mão.

[NOTE]
====
. “Segundo a sua perspicácia”, M; LXX: “contra os santos [se voltará] seu pensamento”.
====

[[v27-8-26]]

^<<v27-8-26,26>>^ “E a coisa vista a respeito da noitinha e da manhã, que se disse, ela é verdadeira.^&#42;1^ E tu, da tua parte, mantém em segredo a visão, porque é ainda para muitos dias.”

[NOTE]
====
. Lit.: “verdade”. Hebr.: ’eméth.
====

[[v27-8-27]]

^<<v27-8-27,27>>^ E quanto a mim, Daniel, senti-me exausto e adoeci por [vários] dias. Então me levantei e fiz a obra do rei; porém, continuei a mostrar-me estupefato por causa da coisa vista, e não havia quem entendesse [isso].

'''

xref:027-daniel/027-daniel-007.adoc#v27-7-0[&#60; Capítulo Anterior] | <<v27-8-0,Topo>> | xref:027-daniel/027-daniel-009.adoc#v27-9-0[Próximo Capítulo &#62;]