include::./index.adoc[]

[[v13-26-0]]
=== 1 Crônicas, 26
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v13-26-1]]

^<<v13-26-1,1>>^ Para as turmas dos porteiros: Dos coraítas, Meselemias, filho de Core, dos filhos de Asafe.

[[v13-26-2]]

^<<v13-26-2,2>>^ E Meselemias teve filhos: Zacarias, o primogênito, Jediael, o segundo, Zebadias, o terceiro, Jatniel, o quarto,

[[v13-26-3]]

^<<v13-26-3,3>>^ Elão, o quinto, Jeoanã,^&#42;1^ o sexto, Elieó-Enai, o sétimo.

[NOTE]
====
. Significando “Jeová Mostrou Favor; Jeová Foi Clemente”. Hebr.: Yehoh·hha·nán. Veja Jo Título n.
====

[[v13-26-4]]

^<<v13-26-4,4>>^ E Obede-Edom teve filhos: Semaías, o primogênito, Jeozabade, o segundo, Joá, o terceiro, e Sacar, o quarto, e Netanel, o quinto,

[[v13-26-5]]

^<<v13-26-5,5>>^ Amiel, o sexto, Issacar, o sétimo, Peuletai, o oitavo; pois Deus o havia abençoado.

[[v13-26-6]]

^<<v13-26-6,6>>^ E a Semaías, seu filho, nasceram filhos que foram governantes da casa de seu pai, pois foram homens poderosos, capazes.

[[v13-26-7]]

^<<v13-26-7,7>>^ Os filhos de Semaías: Otni, e Refael, e Obede, Elzabade, cujos irmãos foram homens capazes, Eliú e Semaquias.

[[v13-26-8]]

^<<v13-26-8,8>>^ Todos estes foram dos filhos de Obede-Edom, eles, e seus filhos, e seus irmãos, homens capazes com poder para o serviço, sessenta e dois, pertencendo a Obede-Edom.

[[v13-26-9]]

^<<v13-26-9,9>>^ E Meselemias teve filhos e irmãos, homens capazes, dezoito.

[[v13-26-10]]

^<<v13-26-10,10>>^ E Hosa, dos filhos de Merari, teve filhos. Sinri foi o cabeça, porque não viera a ser o primogênito, mas seu pai o designou como cabeça;

[[v13-26-11]]

^<<v13-26-11,11>>^ Hilquias, o segundo, Tebalias, o terceiro, Zacarias, o quarto. Todos os filhos e irmãos de Hosa foram treze.

[[v13-26-12]]

^<<v13-26-12,12>>^ Destas turmas de porteiros, os cabeças tinham deveres exatamente como seus irmãos, para ministrar na casa de Jeová.

[[v13-26-13]]

^<<v13-26-13,13>>^ De modo que lançaram sortes para o pequeno assim como para o grande, segundo as suas casas paternas, com respeito aos diferentes portões.

[[v13-26-14]]

^<<v13-26-14,14>>^ Então a sorte referente ao leste caiu a Selemias. Lançaram as sortes para Zacarias, seu filho, conselheiro com discrição, e a sua sorte veio a sair referente ao norte.

[[v13-26-15]]

^<<v13-26-15,15>>^ Obede-Edom teve a sua ao sul, e seus filhos tiveram as casas de armazenagem.

[[v13-26-16]]

^<<v13-26-16,16>>^ Supim e Hosa tiveram a sua ao oeste, perto do Portão Salequete, junto à estrada principal que sobe, grupo de guardas correspondendo a grupo de guardas;

[[v13-26-17]]

^<<v13-26-17,17>>^ ao leste havia seis levitas; ao norte, por dia, quatro; ao sul, por dia, quatro; e para os armazéns, de dois em dois;

[[v13-26-18]]

^<<v13-26-18,18>>^ para o pórtico ao oeste, quatro junto à estrada principal, dois junto ao pórtico.

[[v13-26-19]]

^<<v13-26-19,19>>^ Estas foram as turmas dos porteiros dos filhos dos coraítas e dos filhos de Merari.

[[v13-26-20]]

^<<v13-26-20,20>>^ Quanto aos levitas, Aijá estava sobre os tesouros da casa do [verdadeiro] Deus e sobre os tesouros das coisas tornadas sagradas.

[[v13-26-21]]

^<<v13-26-21,21>>^ Os filhos de Ladã, os filhos do gersonita pertencentes a Ladã; os cabeças das casas paternas pertencentes a Ladã, o gersonita: Jeieli.

[[v13-26-22]]

^<<v13-26-22,22>>^ Os filhos de Jeieli, Zetão e Joel, seu irmão, estavam sobre os tesouros da casa de Jeová.

[[v13-26-23]]

^<<v13-26-23,23>>^ Para os anramitas, para os izaritas, para os hebronitas, para os uzielitas,

[[v13-26-24]]

^<<v13-26-24,24>>^ sim, Sebuel,^&#42;1^ filho de Gersom, filho de Moisés, foi líder sobre os armazéns.

[NOTE]
====
. “Subael”, LXXVgc. Veja 23:16 n.
====

[[v13-26-25]]

^<<v13-26-25,25>>^ Quanto aos seus irmãos, de Eliézer havia Reabias seu filho, e Jesaías seu filho, e Jorão seu filho, e Zicri seu filho, e Selomote seu filho.

[[v13-26-26]]

^<<v13-26-26,26>>^ Este Selomote e seus irmãos estavam sobre todos os tesouros das coisas tornadas sagradas, que Davi, o rei, e os cabeças das casas paternas, e os chefes de mil e de cem, e os chefes do exército tinham tornado sagradas.

[[v13-26-27]]

^<<v13-26-27,27>>^ Das guerras e do despojo tinham feito [certas coisas] sagradas para a manutenção da casa de Jeová.

[[v13-26-28]]

^<<v13-26-28,28>>^ E também tudo o que Samuel, o vidente, e Saul, filho de Quis, e Abner, filho de Ner, e Joabe, filho de Zeruia, tinham tornado sagrado. Aquilo que alguém tornasse sagrado^&#42;1^ ficava sob o controle de Selomite^&#42;2^ e de seus irmãos.

[NOTE]
====
. Lit.: “tudo o que alguém santificasse”.
. “Selomite”, MVgc; LXX: “Selomote”.
====

[[v13-26-29]]

^<<v13-26-29,29>>^ Dos izaritas, Quenanias e seus filhos estavam sobre o negócio externo como oficiais e como juízes sobre Israel.

[[v13-26-30]]

^<<v13-26-30,30>>^ Dos hebronitas, Hasabias e seus irmãos, homens capazes, mil e setecentos, tinham a seu cargo a administração de Israel na região do Jordão, ao oeste, quanto a toda a obra de Jeová e quanto ao serviço do rei.

[[v13-26-31]]

^<<v13-26-31,31>>^ Dos hebronitas, Jerijá era o cabeça dos hebronitas segundo as suas gerações, pelos antepassados. Foram procurados no quadragésimo ano do reinado de Davi e vieram achar-se entre eles homens poderosos, valentes, em Jázer, em Gileade.

[[v13-26-32]]

^<<v13-26-32,32>>^ E seus irmãos, homens capazes, foram dois mil e setecentos, cabeças das casas paternas. De modo que Davi, o rei, os encarregou dos rubenitas, e dos gaditas, e da meia tribo dos manassitas, referente a todo assunto do [verdadeiro] Deus e ao assunto do rei.

'''

xref:013-1-cronicas/013-1-cronicas-025.adoc#v13-25-0[&#60; Capítulo Anterior] | <<v13-26-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-027.adoc#v13-27-0[Próximo Capítulo &#62;]