include::./index.adoc[]

[[v13-24-0]]
=== 1 Crônicas, 24
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v13-24-1]]

^<<v13-24-1,1>>^ Ora, os filhos de Arão tinham as suas turmas. Os filhos de Arão foram Nadabe e Abiú, Eleazar e Itamar.

[[v13-24-2]]

^<<v13-24-2,2>>^ No entanto, Nadabe e Abiú morreram antes de seu pai, e eles não vieram a ter filhos, mas Eleazar e Itamar continuaram a atuar como sacerdotes.

[[v13-24-3]]

^<<v13-24-3,3>>^ E Davi, e Zadoque, dos filhos de Eleazar, e Aimeleque, dos filhos de Itamar, passaram a fazer turmas deles para o seu cargo no seu serviço.

[[v13-24-4]]

^<<v13-24-4,4>>^ Mas achou-se que os filhos de Eleazar eram mais numerosos em varões principais do que os filhos de Itamar. De modo que os distribuíram aos filhos de Eleazar, como cabeças das [suas]^&#42;1^ casas paternas, dezesseis, e aos filhos de Itamar, [como cabeças] das suas casas paternas, oito.

[NOTE]
====
. “Suas”, Sy e cinco mss. hebr.
====

[[v13-24-5]]

^<<v13-24-5,5>>^ Outrossim, distribuíram-nos por sortes, estes junto com aqueles, pois tinha de haver chefes do lugar santo e chefes do [verdadeiro] Deus, dos filhos de Eleazar e dos filhos de Itamar.

[[v13-24-6]]

^<<v13-24-6,6>>^ Então Semaías, filho de Netanel, o secretário dos levitas, assentou-os por escrito perante o rei e os príncipes, e Zadoque, o sacerdote, e Aimeleque, filho de Abiatar, e os cabeças dos pais dos sacerdotes e dos levitas, sendo uma casa paterna selecionada para Eleazar e uma selecionada para Itamar.^&#42;1^

[NOTE]
====
. “Uma casa paterna, uma por uma, para Eleazar e, uma por uma, para Itamar”, LXX.
====

[[v13-24-7]]

^<<v13-24-7,7>>^ E passou a sair a sorte: a primeira para Jeoiaribe; para Jedaías a segunda,

[[v13-24-8]]

^<<v13-24-8,8>>^ para Harim a terceira, para Seorim a quarta,

[[v13-24-9]]

^<<v13-24-9,9>>^ para Malquijá a quinta, para Mijamim a sexta,

[[v13-24-10]]

^<<v13-24-10,10>>^ para Hacoz a sétima, para Abias a oitava,

[[v13-24-11]]

^<<v13-24-11,11>>^ para Jesua a nona, para Secanias a décima,

[[v13-24-12]]

^<<v13-24-12,12>>^ para Eliasibe a décima primeira, para Jaquim a décima segunda,

[[v13-24-13]]

^<<v13-24-13,13>>^ para Hupa a décima terceira, para Jesebeabe a décima quarta,

[[v13-24-14]]

^<<v13-24-14,14>>^ para Bilga a décima quinta, para Imer a décima sexta,

[[v13-24-15]]

^<<v13-24-15,15>>^ para Hezir a décima sétima, para Hapizez a décima oitava,

[[v13-24-16]]

^<<v13-24-16,16>>^ para Petaías a décima nona, para Jeezquel a vigésima,

[[v13-24-17]]

^<<v13-24-17,17>>^ para Jaquim a vigésima primeira, para Gamul a vigésima segunda,

[[v13-24-18]]

^<<v13-24-18,18>>^ para Delaías a vigésima terceira, para Maazias a vigésima quarta.

[[v13-24-19]]

^<<v13-24-19,19>>^ Estes foram os cargos do seu serviço: entrar na casa de Jeová segundo a sua prerrogativa legítima pela mão de Arão, seu antepassado, assim como lhe mandara Jeová, o Deus de Israel.

[[v13-24-20]]

^<<v13-24-20,20>>^ E dos filhos de Levi que sobraram, dos filhos de Anrão, havia Subael; dos filhos de Subael, Jedeías;

[[v13-24-21]]

^<<v13-24-21,21>>^ de Reabias: dos filhos de Reabias, Issias, o cabeça;

[[v13-24-22]]

^<<v13-24-22,22>>^ dos izaritas, Selomote; dos filhos de Selomote, Jaate;

[[v13-24-23]]

^<<v13-24-23,23>>^ e dos filhos [de Hébron], Jerias, o cabeça,^&#42;1^ Amarias, o segundo, Jaaziel, o terceiro, Jecameão, o quarto.

[NOTE]
====
. “Dos filhos de Hébron, Jerias, o cabeça”, LXXL e 23:19.
====

[[v13-24-24]]

^<<v13-24-24,24>>^ Os filhos de Uziel, Micá; dos filhos de Micá, Samir.

[[v13-24-25]]

^<<v13-24-25,25>>^ O irmão de Micá foi Issias; dos filhos de Issias, Zacarias.

[[v13-24-26]]

^<<v13-24-26,26>>^ Os filhos de Merari foram Mali e Musi; os filhos de Jaazias,^&#42;1^ Beno.

[NOTE]
====
. “Jaazias”, M; LXX: “Uzias”.
====

[[v13-24-27]]

^<<v13-24-27,27>>^ Os filhos de Merari: De Jaazias, Beno, e Soão, e Zacur, e Ibri.

[[v13-24-28]]

^<<v13-24-28,28>>^ De Mali, Eleazar, que não veio a ter filhos.

[[v13-24-29]]

^<<v13-24-29,29>>^ De Quis: os filhos de Quis: Jerameel.

[[v13-24-30]]

^<<v13-24-30,30>>^ E os filhos de Musi foram Mali, e Éder, e Jerimote.
Estes foram os filhos dos levitas segundo as suas casas paternas.

[[v13-24-31]]

^<<v13-24-31,31>>^ E eles mesmos também passaram a lançar sortes exatamente como seus irmãos, os filhos de Arão, fizeram perante Davi, o rei, e Zadoque e Aimeleque, e os cabeças das casas paternas dos sacerdotes e dos levitas. No que se refere às casas paternas, o cabeça era exatamente como o seu irmão mais moço.

'''

xref:013-1-cronicas/013-1-cronicas-023.adoc#v13-23-0[&#60; Capítulo Anterior] | <<v13-24-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-025.adoc#v13-25-0[Próximo Capítulo &#62;]