include::./index.adoc[]

[[v13-8-0]]
=== 1 Crônicas, 8
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v13-8-1]]

^<<v13-8-1,1>>^ Quanto a Benjamim, tornou-se ele pai de Bela, seu primogênito, de Asbel, o segundo, e de Aará, o terceiro,

[[v13-8-2]]

^<<v13-8-2,2>>^ de Noá, o quarto, e de Rafa, o quinto.

[[v13-8-3]]

^<<v13-8-3,3>>^ E Bela veio a ter filhos: Adar, e Gera, e Abiúde,

[[v13-8-4]]

^<<v13-8-4,4>>^ e Abisua, e Naamã, e Aoá,

[[v13-8-5]]

^<<v13-8-5,5>>^ e Gera, e Sefufã, e Hurão.

[[v13-8-6]]

^<<v13-8-6,6>>^ E estes foram os filhos de Eúde. Estes foram os cabeças [das casas] dos antepassados pertencentes aos habitantes de Geba, e passaram a levá-los ao exílio em Manaate.

[[v13-8-7]]

^<<v13-8-7,7>>^ E Naamã e Aijá; e Gera — foi ele quem os levou ao exílio, e ele tornou-se pai de Uza e de Aiúde.

[[v13-8-8]]

^<<v13-8-8,8>>^ Quanto a Saraim, tornou-se ele pai de [filhos] no campo de Moabe, depois de os ter mandado embora. Husim e Baara foram as suas esposas.

[[v13-8-9]]

^<<v13-8-9,9>>^ E por meio de Hodes, sua esposa, veio a tornar-se pai de Jobabe, e de Zibia, e de Mesa, e de Malcão,

[[v13-8-10]]

^<<v13-8-10,10>>^ e de Jeuz, e de Saquia, e de Mirma. Estes foram seus filhos, cabeças [das casas] dos antepassados.

[[v13-8-11]]

^<<v13-8-11,11>>^ E por meio de Husim tornou-se ele pai de Abitube e de Elpaal.

[[v13-8-12]]

^<<v13-8-12,12>>^ E os filhos de Elpaal foram Éber, e Misão, e Semede, que construiu Ono e Lode, e suas aldeias dependentes,

[[v13-8-13]]

^<<v13-8-13,13>>^ e Berias e Sema. Estes foram cabeças [das casas] dos antepassados, pertencentes aos habitantes de Aijalom. Estes foram os que puseram em fuga os habitantes de Gate.

[[v13-8-14]]

^<<v13-8-14,14>>^ E [havia] Aiô,^&#42;1^ Sasaque e Jeremote,

[NOTE]
====
. “E [havia] Aiô”, M; LXXA,L: “E seus irmãos eram”.
====

[[v13-8-15]]

^<<v13-8-15,15>>^ e Zebadias, e Arade, e Éder,

[[v13-8-16]]

^<<v13-8-16,16>>^ e Micael, e Ispa, e Joa, filhos de Berias,

[[v13-8-17]]

^<<v13-8-17,17>>^ e Zebadias, e Mesulão, e Hisqui, e Héber,

[[v13-8-18]]

^<<v13-8-18,18>>^ e Ismerai, e Islias, e Jobabe, filhos de Elpaal,

[[v13-8-19]]

^<<v13-8-19,19>>^ e Jaquim, e Zicri, e Zabdi,

[[v13-8-20]]

^<<v13-8-20,20>>^ e Elienai, e Ziletai, e Eliel,

[[v13-8-21]]

^<<v13-8-21,21>>^ e Adaías, e Beraías, e Sinrate, filhos de Simei,

[[v13-8-22]]

^<<v13-8-22,22>>^ e Ispã, e Éber, e Eliel,

[[v13-8-23]]

^<<v13-8-23,23>>^ e Abdom, e Zicri, e Hanã,

[[v13-8-24]]

^<<v13-8-24,24>>^ e Hananias, e Elão, e Antotias,

[[v13-8-25]]

^<<v13-8-25,25>>^ e Ifdéias, e Penuel, filhos de Sasaque,

[[v13-8-26]]

^<<v13-8-26,26>>^ e Sanserai, e Searias, e Atalias,

[[v13-8-27]]

^<<v13-8-27,27>>^ e Jaaresias, e Elias, e Zicri, filhos de Jeroão.

[[v13-8-28]]

^<<v13-8-28,28>>^ Estes foram cabeças [das casas] dos antepassados segundo os seus descendentes, os principais. Estes foram os que moravam em Jerusalém.

[[v13-8-29]]

^<<v13-8-29,29>>^ E foi em Gibeão que morava o pai de Gibeão, [Jeiel,]^&#42;1^ e o nome de sua esposa foi Maacá.

[NOTE]
====
. “O pai de Gibeão, Jeiel”, LXXL e 9:35.
====

[[v13-8-30]]

^<<v13-8-30,30>>^ E seu filho, o primogênito, foi Abdom, e Zur, e Quis, e Baal, e Nadabe,

[[v13-8-31]]

^<<v13-8-31,31>>^ e Gedor, e Aiô, e Zequer.

[[v13-8-32]]

^<<v13-8-32,32>>^ Quanto a Miclote, tornou-se ele pai de Simeá. E estes foram realmente os que moravam defronte dos seus irmãos em Jerusalém, junto com irmãos seus.

[[v13-8-33]]

^<<v13-8-33,33>>^ Quanto a Ner, tornou-se ele pai de Quis; Quis, por sua vez, tornou-se pai de Saul; Saul, por sua vez, tornou-se pai de Jonatã,^&#42;1^ e de Malquisua, e de Abinadabe, e de Esbaal.

[NOTE]
====
. “Jonatã.” Hebr.: Yehoh·na·thán.
====

[[v13-8-34]]

^<<v13-8-34,34>>^ E o filho de Jonatã foi Meribe-Baal. Quanto a Meribe-Baal, tornou-se ele pai de Micá.

[[v13-8-35]]

^<<v13-8-35,35>>^ E os filhos de Micá foram Pitom, e Meleque, e Taréia, e Acaz.

[[v13-8-36]]

^<<v13-8-36,36>>^ Quanto a Acaz, tornou-se ele pai de Jeoada; e Jeoada, por sua vez, tornou-se pai de Alemete, e de Asmavete, e de Zinri. Zinri, por sua vez, tornou-se pai de Moza;

[[v13-8-37]]

^<<v13-8-37,37>>^ Moza, por sua vez, tornou-se pai de Binéia, de Rafa seu filho, de Eleasá seu filho, de Azel seu filho.

[[v13-8-38]]

^<<v13-8-38,38>>^ E Azel teve seis filhos, e estes foram os seus nomes: Azricão, Boqueru, e Ismael, e Searias, e Obadias, e Hanã. Todos estes foram os filhos de Azel.

[[v13-8-39]]

^<<v13-8-39,39>>^ E os filhos de Eseque, seu irmão, foram Ulão, seu primogênito, Jeús, o segundo, e Elifelete, o terceiro.

[[v13-8-40]]

^<<v13-8-40,40>>^ E os filhos de Ulão vieram a ser homens poderosos, valentes, entesando o arco, e tendo muitos filhos e netos, cento e cinqüenta. Todos estes foram dos filhos de Benjamim.

'''

xref:013-1-cronicas/013-1-cronicas-007.adoc#v13-7-0[&#60; Capítulo Anterior] | <<v13-8-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-009.adoc#v13-9-0[Próximo Capítulo &#62;]