include::./index.adoc[]

[[v13-7-0]]
=== 1 Crônicas, 7
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v13-7-1]]

^<<v13-7-1,1>>^ Ora, os filhos de Issacar foram Tola e Puá, Jasube e Sinrom, quatro.

[[v13-7-2]]

^<<v13-7-2,2>>^ E os filhos de Tola foram Uzi, e Refaías, e Jeriel, e Jamai, e Ibsão, e Semuel, cabeças da casa dos seus antepassados. De Tola havia homens poderosos, valentes, segundo os seus descendentes. Seu número, nos dias de Davi, foi de vinte e dois mil e seiscentos.

[[v13-7-3]]

^<<v13-7-3,3>>^ E os filhos de Uzi: Izraías; e os filhos de Izraías foram Micael, e Obadias, e Joel, Issias,     , cinco,^&#42;1^ todos eles cabeças.

[NOTE]
====
. “Cinco”, MLXXVg; Sy: “quatro”.
====

[[v13-7-4]]

^<<v13-7-4,4>>^ E com eles, pelos seus descendentes, segundo a casa dos seus antepassados, havia tropas do exército para a guerra, trinta e seis mil, pois tinham muitas^&#42;1^ esposas e filhos.

[NOTE]
====
. Ou “multiplicavam”.
====

[[v13-7-5]]

^<<v13-7-5,5>>^ E seus irmãos, de todas as famílias de Issacar, eram homens poderosos, valentes, oitenta e sete mil segundo o registro genealógico de todos eles.

[[v13-7-6]]

^<<v13-7-6,6>>^ [Os filhos de] Benjamim foram Bela, e Bequer, e Jediael, três.

[[v13-7-7]]

^<<v13-7-7,7>>^ E os filhos de Bela foram Esbom, e Uzi, e Uziel, e Jerimote, e Iri, cinco, cabeças da casa dos seus antepassados, homens poderosos, valentes; e seu registro genealógico foi de vinte e dois mil e trinta e quatro.

[[v13-7-8]]

^<<v13-7-8,8>>^ E os filhos de Bequer foram Zemira, e Joás, e Eliézer, e Elioenai, e Onri, e Jeremote, e Abias, e Anatote, e Alemete, todos eles filhos de Bequer.

[[v13-7-9]]

^<<v13-7-9,9>>^ E seu registro genealógico segundo os seus descendentes, quanto aos cabeças da casa dos seus antepassados, homens poderosos, valentes, foi de vinte mil e duzentos.

[[v13-7-10]]

^<<v13-7-10,10>>^ E os filhos de Jediael: Bilã; e os filhos de Bilã foram Jeús, e Benjamim, e Eúde, e Quenaaná, e Zetã, e Társis, e Aisaar.

[[v13-7-11]]

^<<v13-7-11,11>>^ Todos estes foram os filhos de Jediael, segundo os cabeças dos seus antepassados, homens poderosos, valentes, dezessete mil e duzentos saindo para o exército, para a guerra.

[[v13-7-12]]

^<<v13-7-12,12>>^ E os supins e os hupins foram os filhos de Ir; os husins foram os filhos de Aer.

[[v13-7-13]]

^<<v13-7-13,13>>^ Os filhos de Naftali foram Jaziel, e Guni, e Jézer, e Salum,^&#42;1^ filhos de Bila.

[NOTE]
====
. “Salum”, MLXX; LXXL, sete mss. hebr., Gên 46:24 e Núm 26:49: “Silém”.
====

[[v13-7-14]]

^<<v13-7-14,14>>^ Os filhos de Manassés foram Asriel, que a sua concubina síria deu à luz. (Ela deu à luz Maquir, pai de Gileade.

[[v13-7-15]]

^<<v13-7-15,15>>^ E o próprio Maquir tomou esposa para Hupim e para Supim, e o nome de sua irmã foi Maacá.) E o nome do segundo foi Zelofeade, mas Zelofeade veio a ter filhas.

[[v13-7-16]]

^<<v13-7-16,16>>^ Com o tempo Maacá, esposa de Maquir, deu à luz um filho e chamou-o pelo nome de Peres; e o nome de seu irmão foi Seres; e seus filhos foram Ulão e Requém.

[[v13-7-17]]

^<<v13-7-17,17>>^ E os filhos de Ulão: Bedã. Estes foram os filhos de Gileade, filho de Maquir, filho de Manassés.

[[v13-7-18]]

^<<v13-7-18,18>>^ E sua irmã foi Hamolequete. Ela deu à luz Isode, e Abiezer, e Maala.

[[v13-7-19]]

^<<v13-7-19,19>>^ E os filhos de Semida vieram a ser Aiã, e Siquém, e Liqui, e Anião.

[[v13-7-20]]

^<<v13-7-20,20>>^ E os filhos de Efraim foram Sutela, e Berede seu filho, e Taate seu filho, e Eleada seu filho, e Taate seu filho,

[[v13-7-21]]

^<<v13-7-21,21>>^ e Zabade seu filho, e Sutela seu filho, e Ezer, e Eleade. E os homens de Gate que nasceram no país mataram-nos, porque desceram para tomar seu gado.

[[v13-7-22]]

^<<v13-7-22,22>>^ E Efraim, seu pai, entregou-se ao luto por muitos dias, e seus irmãos chegavam para consolá-lo.

[[v13-7-23]]

^<<v13-7-23,23>>^ Depois ele teve relações com a sua esposa, de modo que ela ficou grávida e deu à luz um filho. Mas ele o chamou pelo nome^&#42;1^ de Berias, porque foi com calamidade que ela veio a estar na sua casa.

[NOTE]
====
. “Ele o chamou pelo nome.” Ou “seu nome chamava-se”. TSy e quatro mss. hebr.: “ela o chamou pelo nome”.
====

[[v13-7-24]]

^<<v13-7-24,24>>^ E sua filha foi Seerá, e ela chegou a construir Bete-Horom, a baixa e a alta, e Uzém-Seerá.

[[v13-7-25]]

^<<v13-7-25,25>>^ E havia Refa, filho dele, e Resefe seu filho, e Tela seu filho, e Taã seu filho,

[[v13-7-26]]

^<<v13-7-26,26>>^ Ladã seu filho, Amiúde seu filho, Elisama seu filho,

[[v13-7-27]]

^<<v13-7-27,27>>^ Num^&#42;1^ seu filho, Jeosué^&#42;2^ seu filho.

[NOTE]
====
. “Num”, Vg; M: “Nom”.
. Ou “Josué”.
====

[[v13-7-28]]

^<<v13-7-28,28>>^ E sua propriedade e suas moradas foram Betel e suas aldeias dependentes, e para o leste, Naarã, e para o oeste, Gezer e suas aldeias dependentes, e Siquém e suas aldeias dependentes até Gaza^&#42;1^ e suas aldeias dependentes;

[NOTE]
====
. “Gaza”, T e muitos mss. hebr. Não a Gaza na Filístia, que fora designada a Judá.
====

[[v13-7-29]]

^<<v13-7-29,29>>^ e ao lado dos filhos de Manassés: Bete-Seã e suas aldeias dependentes, Taanaque e suas aldeias dependentes, Megido e suas aldeias dependentes, Dor e suas aldeias dependentes. Nestas moravam os filhos de José, filho de Israel.

[[v13-7-30]]

^<<v13-7-30,30>>^ Os filhos de Aser foram Imná, e Isvá, e Isvi, e Berias; e Sera foi a irmã deles.

[[v13-7-31]]

^<<v13-7-31,31>>^ E os filhos de Berias foram Héber e Malquiel, que foi o pai de Birzaíte.

[[v13-7-32]]

^<<v13-7-32,32>>^ Quanto a Héber, tornou-se ele pai de Jaflete, e de Somer, e de Hotão, e de Sua, irmã deles.

[[v13-7-33]]

^<<v13-7-33,33>>^ E os filhos de Jaflete foram Pasaque, e Bimal, e Asvate. Estes foram os filhos de Jaflete.

[[v13-7-34]]

^<<v13-7-34,34>>^ E os filhos de Semer^&#42;1^ foram Aí e Roga, Jeubá e Arã.

[NOTE]
====
. “Semer”, MLXXB; LXXAVg: “Somer”.
====

[[v13-7-35]]

^<<v13-7-35,35>>^ E os filhos de Helém, seu irmão, foram Zofa, e Imna, e Seles, e Amal.

[[v13-7-36]]

^<<v13-7-36,36>>^ Os filhos de Zofa foram Suá, e Harnefer, e Sual, e Beri, e Inra,

[[v13-7-37]]

^<<v13-7-37,37>>^ Bezer, e Hode, e Sama, e Silsa, e Itrã, e Beera.

[[v13-7-38]]

^<<v13-7-38,38>>^ E os filhos de Jeter foram Jefuné, e Pispa, e Ara.

[[v13-7-39]]

^<<v13-7-39,39>>^ E os filhos de Ula foram Ará, e Haniel, e Rizia.

[[v13-7-40]]

^<<v13-7-40,40>>^ Todos estes foram os filhos de Aser, cabeças da casa dos seus antepassados, homens selecionados, poderosos, valentes, cabeças dos maiorais; e seu registro genealógico estava no exército, na guerra. Seu número foi de vinte e seis mil homens.

'''

xref:013-1-cronicas/013-1-cronicas-006.adoc#v13-6-0[&#60; Capítulo Anterior] | <<v13-7-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-008.adoc#v13-8-0[Próximo Capítulo &#62;]