include::./index.adoc[]

[[v13-14-0]]
=== 1 Crônicas, 14
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v13-14-1]]

^<<v13-14-1,1>>^ E Hirão, rei de Tiro, passou a enviar mensageiros a Davi, bem como madeiras de cedro, e construtores de muros, e trabalhadores em madeira para lhe construir uma casa.

[[v13-14-2]]

^<<v13-14-2,2>>^ E Davi veio a saber que Jeová o estabelecera firmemente como rei sobre Israel, porque o seu reinado estava grandemente exaltado por causa de seu povo Israel.

[[v13-14-3]]

^<<v13-14-3,3>>^ E Davi foi tomar mais esposas em Jerusalém e Davi tornou-se pai de mais filhos e filhas.

[[v13-14-4]]

^<<v13-14-4,4>>^ E estes são os nomes dos filhos que se tornaram seus em Jerusalém: Samua e Sobabe, Natã e Salomão,

[[v13-14-5]]

^<<v13-14-5,5>>^ e Ibar, e Elisua, e Elpelete,

[[v13-14-6]]

^<<v13-14-6,6>>^ e Nogá, e Nefegue, e Jafia,

[[v13-14-7]]

^<<v13-14-7,7>>^ e Elisama, e Beeliada, e Elifelete.

[[v13-14-8]]

^<<v13-14-8,8>>^ E os filisteus chegaram a ouvir que Davi tinha sido ungido rei sobre todo o Israel. Em vista disso subiram todos os filisteus para procurar Davi. Quando Davi ouviu isso, então saiu contra eles.^&#42;1^

[NOTE]
====
. Lit.: “diante deles”. Veja Gên 10:9 n.: “oposição a”.
====

[[v13-14-9]]

^<<v13-14-9,9>>^ E os filisteus, da sua parte, entraram e foram fazer incursões na baixada de Refaim.

[[v13-14-10]]

^<<v13-14-10,10>>^ E Davi começou a indagar de Deus, dizendo: “Devo subir contra os filisteus e entregar-mos-ás certamente na mão?” A isso Jeová lhe disse: “Sobe, e eu hei de entregá-los na tua mão.”

[[v13-14-11]]

^<<v13-14-11,11>>^ Portanto, Davi subiu a Baal-Perazim e foi golpeá-los ali. Davi disse então: “O [verdadeiro] Deus irrompeu através dos meus inimigos, por minha mão, como uma brecha feita por águas.” É por isso que se chamou aquele lugar pelo nome de Baal-Perazim.

[[v13-14-12]]

^<<v13-14-12,12>>^ Por conseguinte, deixaram ali os seus deuses.^&#42;1^ Davi disse então [a palavra], e eles foram assim queimados no fogo.

[NOTE]
====
. “Seus deuses”, M(hebr.: ’elo·heh·hém)LXXVg.
====

[[v13-14-13]]

^<<v13-14-13,13>>^ Mais tarde, os filisteus fizeram mais uma vez uma incursão na baixada.

[[v13-14-14]]

^<<v13-14-14,14>>^ Em vista disso, Davi indagou novamente de Deus, e o [verdadeiro] Deus lhe disse então: “Não deves subir atrás deles. Vai em contorno, [em vez] de diretamente contra eles, e tens de chegar a eles defronte dos lentiscos.^&#42;1^

[NOTE]
====
. “Dos lentiscos.” Hebr.: hab·bekha·’ím; LXXVg: “pereiras”.
====

[[v13-14-15]]

^<<v13-14-15,15>>^ E suceda que, quando ouvires o ruído da marcha nas copas dos lentiscos, então sai à luta, porque o [verdadeiro] Deus terá ido na tua frente para golpear o acampamento dos filisteus.”

[[v13-14-16]]

^<<v13-14-16,16>>^ Portanto, Davi fez assim como o [verdadeiro] Deus lhe mandara, e foram golpear o acampamento dos filisteus desde Gibeão até Gezer.

[[v13-14-17]]

^<<v13-14-17,17>>^ E a fama^&#42;1^ de Davi começou a sair a todas as terras, e o próprio Jeová pôs o pavor dele sobre todas as nações.

[NOTE]
====
. Lit.: “nome”.
====

'''

xref:013-1-cronicas/013-1-cronicas-013.adoc#v13-13-0[&#60; Capítulo Anterior] | <<v13-14-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-015.adoc#v13-15-0[Próximo Capítulo &#62;]