include::./index.adoc[]

[[v13-11-0]]
=== 1 Crônicas, 11
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v13-11-1]]

^<<v13-11-1,1>>^ Com o tempo, todos os israelitas se reuniram a Davi em Hébron, dizendo: “Eis que somos teu osso e tua carne.

[[v13-11-2]]

^<<v13-11-2,2>>^ Tanto ontem como anteriormente, mesmo quando sucedia que Saul era rei, foste tu quem fazias Israel sair e o fazias entrar; e Jeová, teu Deus, passou a dizer-te: ‘És tu que pastorearás meu povo Israel e és tu que te tornarás líder do meu povo Israel.’”

[[v13-11-3]]

^<<v13-11-3,3>>^ Chegaram, pois, todos os anciãos de Israel ao rei em Hébron, e Davi concluiu com eles um pacto em Hébron, perante Jeová; depois ungiram a Davi como rei sobre Israel, de acordo com a palavra de Jeová por intermédio de Samuel.

[[v13-11-4]]

^<<v13-11-4,4>>^ Mais tarde, Davi e todo o Israel foram a Jerusalém, isto é, a Jebus, onde os jebuseus eram os habitantes do país.

[[v13-11-5]]

^<<v13-11-5,5>>^ E os habitantes de Jebus começaram a dizer a Davi: “Aqui não entrarás.” Não obstante, Davi passou a capturar a fortaleza de Sião, isto é, a Cidade de Davi.

[[v13-11-6]]

^<<v13-11-6,6>>^ De modo que Davi disse: “Quem golpear primeiro os jebuseus tornar-se-á cabeça e príncipe.” E Joabe, filho de Zeruia, chegou a subir primeiro e tornou-se cabeça.

[[v13-11-7]]

^<<v13-11-7,7>>^ E Davi passou a morar no lugar de difícil acesso. É por isso que a chamaram de Cidade de Davi.

[[v13-11-8]]

^<<v13-11-8,8>>^ E começou a construir a cidade em redor, desde o Aterro até às partes em redor, mas o próprio Joabe deu vida ao restante da cidade.

[[v13-11-9]]

^<<v13-11-9,9>>^ E Davi estava ficando cada vez maior, porque Jeová dos exércitos estava com ele.

[[v13-11-10]]

^<<v13-11-10,10>>^ Ora, estes são os cabeças dos poderosos que pertenciam a Davi, mantendo-se firmes com ele no seu reinado junto com todo o Israel para fazê-lo rei de acordo com a palavra de Jeová referente a Israel.

[[v13-11-11]]

^<<v13-11-11,11>>^ E esta é a relação dos poderosos que pertenciam a Davi: Jasobeão, filho dum acmonita, cabeça dos três.^&#42;1^ Ele tinha brandido a sua lança sobre trezentos que foram mortos de uma só vez.

[NOTE]
====
. “Três”, LXXL; MLXXSyVg: “trinta”.
====

[[v13-11-12]]

^<<v13-11-12,12>>^ E depois dele vinha Eleazar, filho de Dodo, o aoíta. Ele estava entre os três poderosos.

[[v13-11-13]]

^<<v13-11-13,13>>^ Foi ele quem veio a estar com Davi em Pas-Damim, onde os filisteus se tinham ajuntado para a guerra. Ora, aconteceu que havia um pedaço de campo cheio de cevada, e o povo, da sua parte, fugira por causa dos filisteus.

[[v13-11-14]]

^<<v13-11-14,14>>^ Mas ele^&#42;1^ tomou posição no meio do lote de terreno e livrou-o, e seguiu golpeando os filisteus de modo que Jeová salvou com uma grande salvação.

[NOTE]
====
. “Ele”, LXXVg e 2Sa 23:12; MSyVgc: “eles”.
====

[[v13-11-15]]

^<<v13-11-15,15>>^ E três dos trinta cabeças passaram a descer à rocha, a Davi na caverna de Adulão, ao passo que o acampamento dos filisteus estava acampado na baixada de Refaim.

[[v13-11-16]]

^<<v13-11-16,16>>^ E Davi estava então no lugar de difícil acesso; e havia então uma guarnição de filisteus em Belém.

[[v13-11-17]]

^<<v13-11-17,17>>^ Depois de um tempo Davi mostrou o seu almejo e disse: “Oh! quem me dera beber da água da cisterna de Belém, que está junto ao portão!”

[[v13-11-18]]

^<<v13-11-18,18>>^ Então os três romperam pelo acampamento dos filisteus e puxaram água da cisterna de Belém, que está junto ao portão, e vieram carregá-la e trazê-la a Davi. E Davi não consentiu em bebê-la, mas derramou-a para Jeová.

[[v13-11-19]]

^<<v13-11-19,19>>^ E prosseguiu, dizendo: “Da minha parte, no que se refere ao meu Deus, é inconcebível fazer isso! Beberia eu o sangue destes homens que arriscaram as suas almas?^&#42;1^ Porque foi arriscando as suas almas que a trouxeram.” E não consentiu em bebê-la. Estas são as coisas feitas pelos três poderosos.

[NOTE]
====
. Ou “vidas”.
====

[[v13-11-20]]

^<<v13-11-20,20>>^ Quanto a Abisai, irmão de Joabe, tornou-se ele cabeça dos três; e ele tinha brandido a sua lança sobre trezentos que foram mortos e tinha uma reputação igual à dos três.^&#42;1^

[NOTE]
====
. “Tinha nome entre os três”, TLXXSyVg e muitos dos mss. hebr. Veja também 2Sa 23:18.
====

[[v13-11-21]]

^<<v13-11-21,21>>^ Dos três^&#42;1^ se distinguia mais do que os outros dois e veio a ser chefe deles; e, no entanto, não chegou aos [primeiros] três.

[NOTE]
====
. “Três”, MLXX; Sy: “trinta”; Vg: “os segundos três”.
====

[[v13-11-22]]

^<<v13-11-22,22>>^ Quanto a Benaia, filho de Jeoiada, filho dum homem valente, que fez muitas façanhas em Cabzeel, ele mesmo golpeou os dois [filhos] de Ariel de Moabe; e ele mesmo desceu e golpeou um leão dentro de uma cisterna no dia em que nevou.

[[v13-11-23]]

^<<v13-11-23,23>>^ E foi ele quem golpeou o homem egípcio, homem de tamanho extraordinário, de cinco côvados.^&#42;1^ E na mão do egípcio havia uma lança igual ao cilindro dos tecelões; ainda assim desceu a ele com uma vara e arrebatou a lança da mão do egípcio, e matou-o com a sua própria lança.

[NOTE]
====
. Cerca de 2,23 m.
====

[[v13-11-24]]

^<<v13-11-24,24>>^ Estas coisas fez Benaia, filho de Jeoiada, e ele tinha um nome entre os três poderosos.

[[v13-11-25]]

^<<v13-11-25,25>>^ Embora se distinguisse mais do que os trinta, contudo, não chegou ao grau dos [primeiros] três. Todavia, Davi o pôs sobre a sua própria escolta.

[[v13-11-26]]

^<<v13-11-26,26>>^ Quanto aos poderosos das forças militares, havia Asael, irmão de Joabe, Elanã, filho de Dodo de Belém,

[[v13-11-27]]

^<<v13-11-27,27>>^ Samote, o harorita, Helez, o pelonita,

[[v13-11-28]]

^<<v13-11-28,28>>^ Ira, filho de Iques, o tecoíta, Abiezer, o anatotita,

[[v13-11-29]]

^<<v13-11-29,29>>^ Sibecai, o husatita, Ilai, o aoíta,

[[v13-11-30]]

^<<v13-11-30,30>>^ Maarai, o netofatita, Helede, filho de Baaná, o netofatita,

[[v13-11-31]]

^<<v13-11-31,31>>^ Itai, filho de Ribai de Gibeá dos filhos de Benjamim, Benaia, o piratonita,

[[v13-11-32]]

^<<v13-11-32,32>>^ Hurai, dos vales de torrente de Gaás, Abiel, o arbatita,

[[v13-11-33]]

^<<v13-11-33,33>>^ Asmavete, o barumita, Eliaba, o saalbonita,

[[v13-11-34]]

^<<v13-11-34,34>>^ os filhos de Hasém, o gizonita, Jonatã, filho de Sage, o hararita,

[[v13-11-35]]

^<<v13-11-35,35>>^ Aião, filho de Sacar, o hararita, Elifal, filho de Ur,

[[v13-11-36]]

^<<v13-11-36,36>>^ Hefer, o mequeratita, Aijá, o pelonita,

[[v13-11-37]]

^<<v13-11-37,37>>^ Hezro, o carmelita, Naarai, filho de Esbai,

[[v13-11-38]]

^<<v13-11-38,38>>^ Joel, irmão de Natã, Mibar, filho de Hagri,

[[v13-11-39]]

^<<v13-11-39,39>>^ Zeleque, o amonita, Naarai, o berotita, escudeiro de Joabe, filho de Zeruia,

[[v13-11-40]]

^<<v13-11-40,40>>^ Ira, o itrita, Garebe, o itrita,

[[v13-11-41]]

^<<v13-11-41,41>>^ Urias, o hitita, Zabade, filho de Alai,

[[v13-11-42]]

^<<v13-11-42,42>>^ Adina, filho de Siza, o rubenita, cabeça dos rubenitas, com quem havia trinta;

[[v13-11-43]]

^<<v13-11-43,43>>^ Hanã, filho de Maacá, e Josafá, o mitnita,

[[v13-11-44]]

^<<v13-11-44,44>>^ Uzia, o asteratita, Sama e Jeiel, filhos de Hotão, o aroerita,

[[v13-11-45]]

^<<v13-11-45,45>>^ Jediael, filho de Sinri, e Joa, seu irmão, o tizita,

[[v13-11-46]]

^<<v13-11-46,46>>^ Eliel, o maavita, e Jeribai e Josavias, filhos de Elnaão, e Itma, o moabita.

[[v13-11-47]]

^<<v13-11-47,47>>^ Eliel e Obede, e Jaasiel, o mezobaíta.

'''

xref:013-1-cronicas/013-1-cronicas-010.adoc#v13-10-0[&#60; Capítulo Anterior] | <<v13-11-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-012.adoc#v13-12-0[Próximo Capítulo &#62;]