include::./index.adoc[]

[[v13-20-0]]
=== 1 Crônicas, 20
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v13-20-1]]

^<<v13-20-1,1>>^ E sucedeu, aproximadamente no tempo da volta do ano, no tempo em que os reis fazem surtidas, que Joabe passou a chefiar a força combatente do exército e a arruinar a terra dos filhos de Amom, e passou a vir e a sitiar Rabá, enquanto Davi morava em Jerusalém; e Joabe prosseguiu, golpeando Rabá e derrubando-a.

[[v13-20-2]]

^<<v13-20-2,2>>^ Mas Davi tirou a coroa de Malcão^&#42;1^ da cabeça deste e achou-a de um talento^&#42;2^ de ouro em peso, e nela havia pedras preciosas;^&#42;3^ e ela veio a ficar na cabeça de Davi. E foi muito grande o despojo que tirou da cidade.

[NOTE]
====
. “Molcol, seu rei”, LXX; Vg: “Melcom”. Veja 2Sa 12:30 n.: “Malcão”.
. Veja Ap. 8A.
. Ou “havia uma pedra preciosa”.
====

[[v13-20-3]]

^<<v13-20-3,3>>^ E tirou o povo que havia nela, e manteve-os ocupados em serrar pedras, e com ferramentas afiadas, e com machados;^&#42;1^ e Davi foi fazer assim a todas as cidades dos filhos de Amom. Por fim, Davi e todo o povo retornaram a Jerusalém.

[NOTE]
====
. “Com machados”, mediante uma ligeira correção para concordar com 2Sa 12:31; M: “com serras de pedra”.
====

[[v13-20-4]]

^<<v13-20-4,4>>^ E depois sucedeu que irrompeu guerra em Gezer, com os filisteus. Foi então que Sibecai, o husatita, golpeou a Sipai,^&#42;1^ dos que nasceram dos refains,^&#42;2^ de modo que foram subjugados.

[NOTE]
====
. “Safe” em 2Sa 21:18.
. “Dos refains.” BHK(hebr.): ha·Refa·’ím; Vg: “Rafaim”; LXX: “dos gigantes”.
====

[[v13-20-5]]

^<<v13-20-5,5>>^ E novamente veio a haver guerra com os filisteus; e Elanã, filho de Jair, chegou a golpear Lami, irmão de Golias, o geteu,^&#42;1^ cuja haste de lança era como o cilindro dos tecelões.

[NOTE]
====
. Ou “Golias de Gate”.
====

[[v13-20-6]]

^<<v13-20-6,6>>^ E novamente veio a haver guerra em Gate, quando sucedeu haver [ali] um homem de tamanho extraordinário, cujos dedos das mãos e dos pés eram aos seis, vinte e quatro; e ele também nascera aos refains.^&#42;1^

[NOTE]
====
. Lit.: “ao Rafa”. Hebr.: leha·Ra·fá’. O nome do pai é adotado para representar toda a raça de gigantes.
====

[[v13-20-7]]

^<<v13-20-7,7>>^ E ele escarnecia de Israel. Por fim o golpeou Jonatã,^&#42;1^ filho de Siméia, irmão de Davi.

[NOTE]
====
. Lit.: “Jeonatã”.
====

[[v13-20-8]]

^<<v13-20-8,8>>^ Estes foram os que nasceram aos refains em Gate; e vieram a cair pela mão de Davi e pela mão dos seus servos.

'''

xref:013-1-cronicas/013-1-cronicas-019.adoc#v13-19-0[&#60; Capítulo Anterior] | <<v13-20-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-021.adoc#v13-21-0[Próximo Capítulo &#62;]