include::./index.adoc[]

[[v13-18-0]]
=== 1 Crônicas, 18
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v13-18-1]]

^<<v13-18-1,1>>^ E sucedeu, depois, que Davi passou a golpear os filisteus e a subjugá-los, e foi tomar Gate e suas aldeias dependentes^&#42;1^ da mão dos filisteus.

[NOTE]
====
. Lit.: “e suas filhas”.
====

[[v13-18-2]]

^<<v13-18-2,2>>^ Então golpeou Moabe, e os moabitas vieram a ser servos de Davi, carregando tributo.^&#42;1^

[NOTE]
====
. Lit.: “presente”.
====

[[v13-18-3]]

^<<v13-18-3,3>>^ E Davi prosseguiu, golpeando Hadadezer, rei de Zobá, em Hamate, quando ia para estabelecer seu controle^&#42;1^ junto ao rio Eufrates.

[NOTE]
====
. Lit.: “sua mão”.
====

[[v13-18-4]]

^<<v13-18-4,4>>^ Além disso, Davi capturou dele mil carros, e sete mil cavaleiros, e vinte mil homens a pé. Davi jarretou então todos os cavalos dos carros, mas deixou remanescer cem cavalos de carros.^&#42;1^

[NOTE]
====
. Possivelmente: “parelhas”.
====

[[v13-18-5]]

^<<v13-18-5,5>>^ Quando a Síria^&#42;1^ de Damasco veio ajudar Hadadezer, rei de Zobá, Davi foi golpear dentre os sírios vinte e dois mil homens.

[NOTE]
====
. Ou “os sírios”.
====

[[v13-18-6]]

^<<v13-18-6,6>>^ Depois Davi pôs [guarnições]^&#42;1^ na Síria de Damasco e os sírios vieram a ser servos de Davi, carregando tributo. E Jeová dava salvação a Davi aonde quer que fosse.

[NOTE]
====
. “Pôs guarnições”, TLXXVg, um ms. hebr. e 2Sa 8:6.
====

[[v13-18-7]]

^<<v13-18-7,7>>^ Além disso, Davi tomou os escudos redondos de ouro que vieram a estar nos servos de Hadadezer e trouxe-os a Jerusalém.

[[v13-18-8]]

^<<v13-18-8,8>>^ E de Tibate e de Cum, cidades de Hadadezer, Davi tomou muitíssimo cobre. Com ele Salomão fez o mar de cobre e as colunas, bem como os utensílios de cobre.

[[v13-18-9]]

^<<v13-18-9,9>>^ Quando Toú,^&#42;1^ rei de Hamate, ouviu que Davi golpeara toda a força militar de Hadadezer, rei de Zobá,

[NOTE]
====
. “Toú”, M; Vg: “Thou”; 2Sa 8:9, 10: “Toi”.
====

[[v13-18-10]]

^<<v13-18-10,10>>^ enviou imediatamente Hadorão, seu filho, ao Rei Davi para perguntar-lhe sobre o seu bem-estar e para congratulá-lo^&#42;1^ pelo fato de ter lutado contra Hadadezer de modo a golpeá-lo, (porque Hadadezer havia ficado treinado na guerra contra Toú,)^&#42;2^ e [havia com ele] toda sorte de objetos de ouro, e de prata, e de cobre.

[NOTE]
====
. Lit.: “abençoá-lo”.
. Lit.: “havia-se tornado homem de guerras de Toú”.
====

[[v13-18-11]]

^<<v13-18-11,11>>^ Estes o Rei Davi também santificou a Jeová, junto com a prata e o ouro que trouxera de todas as nações, de Edom, e de Moabe, e dos filhos de Amom, e dos filisteus, e de Amaleque.

[[v13-18-12]]

^<<v13-18-12,12>>^ Quanto a Abisai, filho de Zeruia, golpeou ele os edomitas no Vale do Sal, dezoito mil.

[[v13-18-13]]

^<<v13-18-13,13>>^ De modo que pôs guarnições em Edom, e todos os edomitas vieram a ser servos de Davi. E Jeová salvava a Davi aonde quer que fosse.

[[v13-18-14]]

^<<v13-18-14,14>>^ E Davi continuou a reinar sobre todo o Israel, e ele fazia continuamente decisões judiciais e justiça para todo o seu povo.

[[v13-18-15]]

^<<v13-18-15,15>>^ E Joabe, filho de Zeruia, estava sobre o exército, e Jeosafá, filho de Ailude, era cronista.^&#42;1^

[NOTE]
====
. Lit.: “recordador”.
====

[[v13-18-16]]

^<<v13-18-16,16>>^ E Zadoque, filho de Aitube, e Aimeleque,^&#42;1^ filho de Abiatar, eram sacerdotes, e Savsa era secretário.

[NOTE]
====
. “Aimeleque”, LXXSyVg, 12 mss. hebr. e 2Sa 8:17; MLXXא: “Abimeleque”.
====

[[v13-18-17]]

^<<v13-18-17,17>>^ E Benaia, filho de Jeoiada, estava sobre os queretitas e os peletitas; e os filhos de Davi eram os primeiros colocados ao lado do rei.

'''

xref:013-1-cronicas/013-1-cronicas-017.adoc#v13-17-0[&#60; Capítulo Anterior] | <<v13-18-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-019.adoc#v13-19-0[Próximo Capítulo &#62;]