include::./index.adoc[]

[[v13-29-0]]
=== 1 Crônicas, 29
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v13-29-1]]

^<<v13-29-1,1>>^ Davi, o rei, disse então a toda a congregação: “Salomão, meu filho, a quem Deus escolheu, é moço e delicado, mas a obra é grande; pois o castelo^&#42;1^ não é para um homem, mas para Jeová Deus.

[NOTE]
====
. Ou “o templo”. Hebr.: hab·bi·ráh.
====

[[v13-29-2]]

^<<v13-29-2,2>>^ E preparei segundo todo o meu poder para a casa do meu Deus o ouro para o trabalho de ouro, e a prata para o trabalho de prata, e o cobre para o trabalho de cobre, o ferro para o trabalho de ferro e as madeiras para o trabalho de madeira; pedras de ônix, e pedras para engastar com argamassa dura, e pedrinhas de mosaico, e toda pedra preciosa, e pedras de alabastro, em grande quantidade.

[[v13-29-3]]

^<<v13-29-3,3>>^ E visto que tenho prazer na casa de meu Deus, ainda tenho uma propriedade especial, ouro e prata; deveras a dou à casa de meu Deus em adição a tudo o que preparei para a casa santa:

[[v13-29-4]]

^<<v13-29-4,4>>^ três mil talentos de ouro do ouro de Ofir e sete mil talentos de prata refinada para o revestimento das paredes das casas;

[[v13-29-5]]

^<<v13-29-5,5>>^ do ouro para o trabalho de ouro, e da prata para o trabalho de prata e para toda a obra pela mão dos artífices. E quem se oferece voluntariamente para encher hoje a sua mão [com um presente] para Jeová?”

[[v13-29-6]]

^<<v13-29-6,6>>^ E os príncipes das casas paternas,^&#42;1^ e os príncipes das tribos de Israel, e os chefes de mil e de cem, e os chefes dos negócios do rei passaram a oferecer-se voluntariamente.

[NOTE]
====
. Lit.: “dos pais”.
====

[[v13-29-7]]

^<<v13-29-7,7>>^ Por conseguinte, deram para o serviço da casa do [verdadeiro] Deus ouro no valor de cinco mil talentos,^&#42;1^ e dez mil daricos,^&#42;2^ e prata no valor de dez mil talentos, e cobre no valor de dezoito mil talentos, e ferro no valor de cem mil talentos.

[NOTE]
====
. Cerca de US$ 1.926.750.000, com o ouro a US$ 11,25 o g. Veja Ap. 8A.
. Moeda persa de ouro. Veja Ap. 8A.
====

[[v13-29-8]]

^<<v13-29-8,8>>^ E as pedras que se achavam com qualquer pessoa eles deram ao tesouro da casa de Jeová sob o controle de Jeiel, o gersonita.

[[v13-29-9]]

^<<v13-29-9,9>>^ E o povo se alegrava por fazerem ofertas voluntárias, pois era de pleno coração que faziam ofertas voluntárias a Jeová; e até mesmo Davi, o rei, se alegrou com grande gozo.

[[v13-29-10]]

^<<v13-29-10,10>>^ Conseqüentemente, Davi bendisse a Jeová diante dos olhos de toda a congregação e Davi disse: “Bendito sejas, ó Jeová, Deus de Israel, nosso pai, de tempo indefinido a tempo indefinido.

[[v13-29-11]]

^<<v13-29-11,11>>^ Tuas, ó Jeová, são a grandeza, e a potência, e a beleza, e a excelência, e a dignidade; pois [teu] é tudo nos céus e na terra. Teu é o reino, ó Jeová, que te ergues como cabeça sobre todos.

[[v13-29-12]]

^<<v13-29-12,12>>^ As riquezas e a glória existem por tua causa e tu dominas^&#42;1^ sobre tudo; e na tua mão há poder e potência, e na tua mão há [a capacidade] para engrandecer e para dar força a todos.

[NOTE]
====
. “Dominas.” Hebr.: moh·shél. Veja Sal 103:22, onde ocorre uma forma do substantivo relacionado mem·sha·láh, significando “dominação (domínio)” ou “soberania”.
====

[[v13-29-13]]

^<<v13-29-13,13>>^ E agora, ó nosso Deus, te agradecemos e louvamos o teu belo nome.

[[v13-29-14]]

^<<v13-29-14,14>>^ “E, no entanto, quem sou eu e quem é meu povo, que retenhamos poder para fazer ofertas voluntárias tais como estas? Porque tudo procede de ti e da tua própria mão o demos a ti.

[[v13-29-15]]

^<<v13-29-15,15>>^ Pois diante de ti somos residentes forasteiros e colonos, assim como todos os nossos antepassados. Nossos dias sobre a terra são como uma sombra e não há esperança.

[[v13-29-16]]

^<<v13-29-16,16>>^ Ó Jeová, nosso Deus, toda esta abundância que preparamos para construir-te uma casa ao teu santo nome procede da tua mão e a ti pertence tudo.

[[v13-29-17]]

^<<v13-29-17,17>>^ E eu bem sei, ó meu Deus, que tu examinas o coração e que tens prazer na retidão. Eu, da minha parte, na retidão do meu coração, ofereci voluntariamente todas estas coisas, e agora alegrei-me de ver teu povo que está aqui presente fazer-te ofertas voluntárias.

[[v13-29-18]]

^<<v13-29-18,18>>^ Ó Jeová, Deus de Abraão, de Isaque e de Israel, nossos antepassados, conserva isto por tempo indefinido como inclinação dos pensamentos do coração do teu povo e dirige seu coração a ti.

[[v13-29-19]]

^<<v13-29-19,19>>^ E dá a Salomão, meu filho, um coração pleno para guardar teus mandamentos, teus testemunhos^&#42;1^ e teus regulamentos, e para fazer tudo, e para construir o castelo para o qual fiz preparativos.”

[NOTE]
====
. Ou “advertências”.
====

[[v13-29-20]]

^<<v13-29-20,20>>^ E Davi prosseguiu, dizendo a toda a congregação: “Bendizei agora a Jeová, vosso Deus.” E toda a congregação passou a bendizer a Jeová, o Deus de seus antepassados, e a inclinar-se, e a prostrar-se diante de Jeová e diante do rei.

[[v13-29-21]]

^<<v13-29-21,21>>^ E continuaram a ofertar sacrifícios a Jeová e a fazer ofertas queimadas a Jeová no dia que seguiu àquele dia: mil novilhos, mil carneiros, mil cordeiros e suas ofertas de bebida, sim, sacrifícios em grande número para todo o Israel.

[[v13-29-22]]

^<<v13-29-22,22>>^ E seguiram comendo e bebendo diante de Jeová naquele dia com grande alegria; e pela segunda vez passaram a fazer rei a Salomão, filho de Davi, e a ungi-lo para Jeová como líder, e também a Zadoque, como sacerdote.

[[v13-29-23]]

^<<v13-29-23,23>>^ E Salomão começou a sentar-se no trono de Jeová como rei em lugar de Davi, seu pai, e para ser bem sucedido, e todos os israelitas lhe obedeciam.

[[v13-29-24]]

^<<v13-29-24,24>>^ Quanto a todos os príncipes e os poderosos, e também todos os filhos do Rei Davi, submeteram-se a Salomão, o rei.^&#42;1^

[NOTE]
====
. Lit.: “deram (colocaram) mão sob Salomão, o rei”. Veja Gên 24:2; Gên 47:29.
====

[[v13-29-25]]

^<<v13-29-25,25>>^ E Jeová continuou a fazer Salomão extraordinariamente grande aos olhos de todo o Israel e a pôr sobre ele tal dignidade real como não viera a haver antes dele sobre nenhum rei de Israel.

[[v13-29-26]]

^<<v13-29-26,26>>^ Quanto a Davi, filho de Jessé, reinou sobre todo o Israel;

[[v13-29-27]]

^<<v13-29-27,27>>^ e os dias que ele reinou sobre Israel foram quarenta anos. Em Hébron reinou sete anos e em Jerusalém reinou trinta e três [anos].

[[v13-29-28]]

^<<v13-29-28,28>>^ E por fim morreu numa boa velhice, saciado de dias, de riquezas e de glória; e Salomão, seu filho, começou a reinar em seu lugar.

[[v13-29-29]]

^<<v13-29-29,29>>^ Quanto aos assuntos de Davi, o rei, os primeiros e os últimos, eis que estão escritos entre as palavras de Samuel, o vidente,^&#42;1^ e entre as palavras de Natã, o profeta, e entre as palavras de Gade, o visionário,^&#42;2^

[NOTE]
====
. “O vidente.” Hebr.: ha·ro·’éh.
. “O visionário.” Hebr.: ha·hho·zéh, isto é, alguém que tem visões da parte de Deus a respeito de assuntos ocultos ou futuros.
====

[[v13-29-30]]

^<<v13-29-30,30>>^ junto com todo o seu reinado, e sua potência, e os tempos que passaram sobre ele e sobre Israel, e sobre todos os reinos dos países.

'''

xref:013-1-cronicas/013-1-cronicas-028.adoc#v13-28-0[&#60; Capítulo Anterior] | <<v13-29-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-001.adoc#v14-1-0[Próximo Capítulo &#62;]