include::./index.adoc[]

[[v13-16-0]]
=== 1 Crônicas, 16
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v13-16-1]]

^<<v13-16-1,1>>^ Assim trouxeram a arca do [verdadeiro] Deus para dentro e a colocaram na tenda que Davi tinha armado para ela; e começaram a apresentar ofertas queimadas e sacrifícios de participação em comum perante o [verdadeiro] Deus.^&#42;1^

[NOTE]
====
. “O [verdadeiro] Deus.” Hebr.: ha·’Elo·hím; gr.: The·oú; Sy: “a arca de Jeová”.
====

[[v13-16-2]]

^<<v13-16-2,2>>^ Quando Davi acabou de oferecer a oferta queimada e os sacrifícios de participação em comum, passou a abençoar o povo em nome de Jeová.

[[v13-16-3]]

^<<v13-16-3,3>>^ Além disso, repartiu a todos os israelitas, tanto a homem como a mulher, a cada um um pão redondo e um bolo de tâmaras, e um bolo de passas.

[[v13-16-4]]

^<<v13-16-4,4>>^ Então pôs diante da arca de Jeová alguns dos levitas como ministros,^&#42;1^ tanto para fazer lembrar como para agradecer e louvar a Jeová, o Deus de Israel:

[NOTE]
====
. “Como ministros (ajudantes).” Hebr.: meshor·thím. Veja 6:32 n.
====

[[v13-16-5]]

^<<v13-16-5,5>>^ Asafe, o cabeça, e o segundo depois dele, Zacarias, [e] Jeiel, e Semiramote, e Jeiel, e Matitias, e Eliabe, e Benaia, e Obede-Edom, e Jeiel, com instrumentos do tipo dos de cordas e com harpas, e Asafe com os címbalos, tocando alto,

[[v13-16-6]]

^<<v13-16-6,6>>^ e Benaia e Jaaziel, os sacerdotes, com as trombetas constantemente diante da arca do pacto do [verdadeiro] Deus.

[[v13-16-7]]

^<<v13-16-7,7>>^ Foi então, naquele dia, que Davi fez pela primeira vez uma contribuição para agradecer a Jeová por meio de Asafe e seus irmãos:

[[v13-16-8]]

^<<v13-16-8,8>>^ “Agradecei a Jeová; invocai o seu nome,
Tornai conhecidos entre os povos os seus atos!

[[v13-16-9]]

^<<v13-16-9,9>>^ Cantai-lhe, entoai-lhe melodias,
Ocupai-vos com todos os seus atos maravilhosos.

[[v13-16-10]]

^<<v13-16-10,10>>^ Gabai-vos no seu santo nome,
Alegre-se o coração dos que procuram a Jeová.

[[v13-16-11]]

^<<v13-16-11,11>>^ Buscai a Jeová e a sua força,
Procurai a sua face constantemente.

[[v13-16-12]]

^<<v13-16-12,12>>^ Lembrai-vos dos seus atos maravilhosos que realizou,
Dos seus milagres^&#42;1^ e das decisões judiciais da sua boca,

[NOTE]
====
. Ou “maravilhas”; ou: “sinais”.
====

[[v13-16-13]]

^<<v13-16-13,13>>^ Ó descendência^&#42;1^ de Israel, seu servo,
Filhos de Jacó, seus escolhidos.

[NOTE]
====
. Lit.: “semente”.
====

[[v13-16-14]]

^<<v13-16-14,14>>^ Ele é Jeová, nosso Deus; suas decisões judiciais estão em toda a terra.

[[v13-16-15]]

^<<v13-16-15,15>>^ Lembrai-vos do seu pacto, sim, por tempo indefinido,
Da palavra que ele ordenou, por mil gerações,

[[v13-16-16]]

^<<v13-16-16,16>>^ [Pacto] que concluiu com Abraão,
E sua declaração juramentada a Isaque.

[[v13-16-17]]

^<<v13-16-17,17>>^ E a esta ele manteve de pé como regulamento, sim, para Jacó,
Como pacto de duração indefinida, sim, para Israel,

[[v13-16-18]]

^<<v13-16-18,18>>^ Dizendo: ‘A ti darei a terra de Canaã,
Como lote da vossa herança.’

[[v13-16-19]]

^<<v13-16-19,19>>^ [Isto se deu] quando viestes a ser poucos em número,
Sim, muito poucos, e residentes forasteiros nela.

[[v13-16-20]]

^<<v13-16-20,20>>^ E andavam de nação em nação,
E de um reino a outro povo.

[[v13-16-21]]

^<<v13-16-21,21>>^ Ele não permitiu que alguém os defraudasse,
Mas por causa deles repreendeu reis,

[[v13-16-22]]

^<<v13-16-22,22>>^ [Dizendo:] ‘Não toqueis nos meus ungidos^&#42;1^
E não façais nada de mal aos meus profetas.’

[NOTE]
====
. “Meus ungidos.” Hebr.: bim·shi·hhaí; gr.: khri·stón; sir.: lam·shi·hhai; lat.: chrí·stos.
====

[[v13-16-23]]

^<<v13-16-23,23>>^ Cantai a Jeová, todos vós da terra!
Anunciai de dia em dia a salvação que ele dá!

[[v13-16-24]]

^<<v13-16-24,24>>^ Relatai entre as nações a sua glória,
Entre todos os povos os seus atos maravilhosos.

[[v13-16-25]]

^<<v13-16-25,25>>^ Pois Jeová é grande e para ser louvado muito,
E para ser temido mais do que todos os [outros] deuses.^&#42;1^

[NOTE]
====
. “Deuses.” Hebr.: ’elo·hím.
====

[[v13-16-26]]

^<<v13-16-26,26>>^ Porque todos os deuses dos povos são deuses que nada valem.^&#42;1^
Quanto a Jeová, ele fez os céus.

[NOTE]
====
. Ou “deuses inúteis”. Hebr.: ’eli·lím; LXXVg: “ídolos”; Sy: “imagens”.
====

[[v13-16-27]]

^<<v13-16-27,27>>^ Diante dele há dignidade e esplendor,
No seu lugar há força e regozijo.

[[v13-16-28]]

^<<v13-16-28,28>>^ Atribuí a Jeová, ó famílias de povos,
Atribuí a Jeová glória e força.

[[v13-16-29]]

^<<v13-16-29,29>>^ Atribuí a Jeová a glória do seu nome,
Carregai um presente e entrai perante ele.
Curvai-vos diante de Jeová em santo adorno.

[[v13-16-30]]

^<<v13-16-30,30>>^ Estai em severas dores por causa dele, todos [vós da] terra!
Também o solo produtivo^&#42;1^ está firmemente estabelecido:
Nunca será abalado.

[NOTE]
====
. “Solo produtivo.” Hebr.: te·vél; gr.: ge; lat.: ór·bem, “círculo”, isto é, da terra.
====

[[v13-16-31]]

^<<v13-16-31,31>>^ Alegrem-se os céus, e jubile a terra,
E digam entre as nações: ‘O próprio Jeová se tornou rei!’

[[v13-16-32]]

^<<v13-16-32,32>>^ Troveje o mar e também o que o enche,
Regozije-se o campo e tudo o que nele há.

[[v13-16-33]]

^<<v13-16-33,33>>^ Ao mesmo tempo, irrompam as árvores da floresta em grito de júbilo por causa de Jeová,
Porque chegou para julgar a terra.

[[v13-16-34]]

^<<v13-16-34,34>>^ Agradecei a Jeová, porque ele é bom,
Pois a sua benevolência^&#42;1^ é por tempo indefinido.

[NOTE]
====
. Ou “amor leal”.
====

[[v13-16-35]]

^<<v13-16-35,35>>^ E dizei: ‘Salva-nos, ó Deus de nossa salvação,
E reúne-nos e livra-nos das nações,
Para darmos graças ao teu santo nome, para falarmos com exultação em teu louvor.

[[v13-16-36]]

^<<v13-16-36,36>>^ Bendito seja Jeová, o Deus de Israel, de tempo indefinido a tempo indefinido.’”
E todo o povo passou a dizer: “Amém!” e a louvar a Jeová.^&#42;1^

[NOTE]
====
. Ou: “E que todo o povo diga: ‘Amém!’ e eles terão de louvar a Jeová.” Vg: “E que todo o povo diga: ‘Amém!’ e um hino a Jeová.”
====

[[v13-16-37]]

^<<v13-16-37,37>>^ Deixou então ali diante da arca do pacto de Jeová a Asafe e seus irmãos para que ministrassem constantemente diante da Arca, conforme a exigência de cada dia;

[[v13-16-38]]

^<<v13-16-38,38>>^ e Obede-Edom e seus irmãos, sessenta e oito, e Obede-Edom, filho de Jedutum, e Hosa, como porteiros;

[[v13-16-39]]

^<<v13-16-39,39>>^ e Zadoque, o sacerdote, e seus irmãos, os sacerdotes, diante do tabernáculo de Jeová no alto que havia em Gibeão,

[[v13-16-40]]

^<<v13-16-40,40>>^ para oferecer ofertas queimadas a Jeová no altar da oferta queimada, constantemente, de manhã e à noitinha, e para tudo o que está escrito na lei de Jeová que ele impusera como ordem a Israel;

[[v13-16-41]]

^<<v13-16-41,41>>^ e com eles Hemã e Jedutum, e os restantes homens selecionados que tinham sido designados por nomes, para agradecer a Jeová, porque “a sua benevolência é por tempo indefinido”;

[[v13-16-42]]

^<<v13-16-42,42>>^ e com eles Hemã e Jedutum, para fazer soar as trombetas, e os címbalos, e os instrumentos de canto do [verdadeiro] Deus; e os filhos de Jedutum no portão.

[[v13-16-43]]

^<<v13-16-43,43>>^ E todo o povo passou a ir cada um para a sua própria casa. Por conseguinte, Davi deu volta para abençoar a sua própria casa.

'''

xref:013-1-cronicas/013-1-cronicas-015.adoc#v13-15-0[&#60; Capítulo Anterior] | <<v13-16-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-017.adoc#v13-17-0[Próximo Capítulo &#62;]