include::./index.adoc[]

[[v13-19-0]]
=== 1 Crônicas, 19
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v13-19-1]]

^<<v13-19-1,1>>^ E sucedeu, depois, que veio a falecer Naás, rei dos filhos de Amom, e seu filho começou a reinar em seu lugar.

[[v13-19-2]]

^<<v13-19-2,2>>^ Então disse Davi: “Usarei de benevolência para com Hanum, filho de Naás, porque seu pai usou de benevolência para comigo.” Por conseguinte, Davi enviou mensageiros para consolá-lo por seu pai, e os servos de Davi passaram a chegar à terra dos filhos de Amom, a Hanum, para consolá-lo.

[[v13-19-3]]

^<<v13-19-3,3>>^ No entanto, os príncipes dos filhos de Amom disseram a Hanum: “Honra Davi a teu pai aos teus olhos, enviando-te consoladores? Não é para fazer um reconhecimento cabal, e para causar uma subversão, e para espionar o país, que seus servos chegaram a ti?”

[[v13-19-4]]

^<<v13-19-4,4>>^ Hanum tomou, pois, os servos de Davi e rapou-os, e cortou suas roupas pelo meio, até às suas nádegas, e mandou-os embora.

[[v13-19-5]]

^<<v13-19-5,5>>^ Mais tarde, pessoas foram e informaram Davi sobre os homens; e ele enviou imediatamente [alguém] ao encontro deles, porque se tinham tornado homens muito humilhados; e o rei prosseguiu, dizendo: “Morai em Jericó até que as vossas barbas tenham crescido abundantemente. Então tereis de retornar.”

[[v13-19-6]]

^<<v13-19-6,6>>^ Com o tempo, os filhos de Amom viram que se tornaram malcheirosos para Davi, e Hanum e os filhos de Amom passaram a enviar mil talentos^&#42;1^ de prata, a fim de contratar para si carros e cavaleiros da Mesopotâmia,^&#42;2^ e de Arã-Maacá, e de Zobá.

[NOTE]
====
. Veja Ap. 8A.
. Veja Gên 24:10 n.
====

[[v13-19-7]]

^<<v13-19-7,7>>^ Assim contrataram para si trinta e dois mil carros, bem como o rei de Maacá e seu povo. Eles chegaram então e se acamparam diante de Medeba; e quanto aos filhos de Amom, ajuntaram-se das suas cidades e entraram então para a guerra.

[[v13-19-8]]

^<<v13-19-8,8>>^ Quando Davi o ouviu, enviou imediatamente Joabe e todo o exército, [bem como] os poderosos.^&#42;1^

[NOTE]
====
. Lit.: “todo o exército — os poderosos”. Veja 2Sa (16:6; 20:7; 23:8).
====

[[v13-19-9]]

^<<v13-19-9,9>>^ E os filhos de Amom começaram a sair e a pôr-se em formação de batalha à entrada da cidade, e os reis que chegaram estavam à parte, no campo aberto.

[[v13-19-10]]

^<<v13-19-10,10>>^ Quando Joabe viu que as cargas da batalha^&#42;1^ vieram a ser contra ele da frente e da retaguarda, escolheu imediatamente alguns dentre todos os homens seletos de Israel e os pôs em formação para enfrentar os sírios.

[NOTE]
====
. Lit.: “a face da batalha”.
====

[[v13-19-11]]

^<<v13-19-11,11>>^ E o resto do povo ele entregou na mão de Abisai, seu irmão, para que se pusessem em formação para enfrentar os filhos de Amom.

[[v13-19-12]]

^<<v13-19-12,12>>^ E prosseguiu, dizendo: “Se os sírios se tornarem fortes demais para mim, então terás de servir-me de salvação; mas, se os próprios filhos de Amom se tornarem fortes demais para ti, então eu terei de salvar-te.

[[v13-19-13]]

^<<v13-19-13,13>>^ Sê forte, para que demonstremos ser corajosos a favor do nosso povo e a favor das cidades de nosso Deus; e quanto a Jeová, fará o que for bom aos seus próprios olhos.”

[[v13-19-14]]

^<<v13-19-14,14>>^ Então Joabe e o povo com ele avançaram diante dos sírios à batalha, e estes se puseram em fuga diante dele.

[[v13-19-15]]

^<<v13-19-15,15>>^ Quanto aos filhos de Amom, viram que os sírios haviam fugido, e eles mesmos também se puseram em fuga diante de Abisai, irmão dele, e então entraram na cidade. Mais tarde, Joabe entrou em Jerusalém.

[[v13-19-16]]

^<<v13-19-16,16>>^ Quando os sírios viram que tinham sido derrotados diante de Israel, passaram a enviar mensageiros e a trazer os sírios que estavam na região do Rio,^&#42;1^ tendo na sua frente Sofaque,^&#42;2^ chefe do exército de Hadadezer.

[NOTE]
====
. Isto é, o Eufrates.
. “Sobaque” em 2Sa 10:16.
====

[[v13-19-17]]

^<<v13-19-17,17>>^ Quando Davi foi informado disso, ajuntou imediatamente todo o Israel e atravessou o Jordão, e chegou a eles e se pôs em formação de batalha contra eles. Quando Davi se pôs em formação de batalha para enfrentar os sírios, começaram a lutar contra ele.

[[v13-19-18]]

^<<v13-19-18,18>>^ Mas os sírios se puseram em fuga por causa de Israel; e Davi foi matar dos sírios sete mil condutores de carros e quarenta mil homens a pé, e entregou à morte o próprio Sofaque, chefe do exército.

[[v13-19-19]]

^<<v13-19-19,19>>^ Quando os servos de Hadadezer viram que tinham sido derrotados diante de Israel, fizeram prontamente paz com Davi e começaram a servi-lo; e a Síria não quis mais tentar salvar os filhos de Amom.

'''

xref:013-1-cronicas/013-1-cronicas-018.adoc#v13-18-0[&#60; Capítulo Anterior] | <<v13-19-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-020.adoc#v13-20-0[Próximo Capítulo &#62;]