include::./index.adoc[]

[[v13-2-0]]
=== 1 Crônicas, 2
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v13-2-1]]

^<<v13-2-1,1>>^ Estes foram os filhos de Israel: Rubem, Simeão, Levi e Judá, Issacar e Zebulão,

[[v13-2-2]]

^<<v13-2-2,2>>^ Dã, José e Benjamim, Naftali, Gade e Aser.

[[v13-2-3]]

^<<v13-2-3,3>>^ Os filhos de Judá foram Er, e Onã, e Selá. Os três nasceram-lhe da filha de Sua, a cananéia. E Er, o primogênito de Judá, veio a ser mau aos olhos de Jeová, de modo que o entregou à morte.

[[v13-2-4]]

^<<v13-2-4,4>>^ E foi Tamar, sua nora, que lhe deu à luz Peres e Zerá. Foram cinco todos os filhos de Judá.

[[v13-2-5]]

^<<v13-2-5,5>>^ Os filhos de Peres foram Esrom e Hamul.

[[v13-2-6]]

^<<v13-2-6,6>>^ E os filhos de Zerá foram Zinri, e Etã, e Hemã, e Calcol, e Dara. Ao todo foram cinco.

[[v13-2-7]]

^<<v13-2-7,7>>^ E os filhos de Carmi: Acar,^&#42;1^ quem trouxe o banimento^&#42;2^ a Israel, cometendo um ato de infidelidade com respeito à coisa devotada à destruição.

[NOTE]
====
. Significando “Causador de Banimento; Causador de Dificuldade”. Hebr.: ‛A·khár; em Jos 7:1, 18: “Acã”.
. Ou “quem trouxe dificuldade”. Hebr.: ‛oh·khér, trocadilho de ‛A·khár, o nome do homem.
====

[[v13-2-8]]

^<<v13-2-8,8>>^ E os filhos de Etã: Azarias.

[[v13-2-9]]

^<<v13-2-9,9>>^ E os filhos de Esrom, que lhe nasceram, foram Jerameel, e Rão, e Quelubai.^&#42;1^

[NOTE]
====
. “Calebe” nos vv. 18, 19, 42.
====

[[v13-2-10]]

^<<v13-2-10,10>>^ Quanto a Rão, tornou-se pai de Aminadabe. Aminadabe, por sua vez, tornou-se pai de Nasom, maioral dos filhos de Judá.

[[v13-2-11]]

^<<v13-2-11,11>>^ Nasom, por sua vez, tornou-se pai de Salma. Salma, por sua vez, tornou-se pai de Boaz.

[[v13-2-12]]

^<<v13-2-12,12>>^ Boaz, por sua vez, tornou-se pai de Obede. Obede, por sua vez, tornou-se pai de Jessé.

[[v13-2-13]]

^<<v13-2-13,13>>^ Jessé, por sua vez, tornou-se pai do seu primogênito, Eliabe, e de Abinadabe, o segundo, e de Siméia, o terceiro,

[[v13-2-14]]

^<<v13-2-14,14>>^ de Netanel, o quarto, de Radai, o quinto,

[[v13-2-15]]

^<<v13-2-15,15>>^ de Ozem, o sexto, de Davi, o sétimo.

[[v13-2-16]]

^<<v13-2-16,16>>^ E suas irmãs foram Zeruia e Abigail; e os filhos de Zeruia foram Abisai, e Joabe, e Asael, três.

[[v13-2-17]]

^<<v13-2-17,17>>^ Quanto a Abigail, deu à luz Amasa; e o pai de Amasa foi Jeter, o ismaelita.

[[v13-2-18]]

^<<v13-2-18,18>>^ Quanto a Calebe,^&#42;1^ filho de Esrom, tornou-se ele pai de filhos por Azuba, sua esposa, e por Jeriote; e estes foram os seus filhos: Jeser e Sobabe, e Ardom.

[NOTE]
====
. “Quelubai” no v. 9.
====

[[v13-2-19]]

^<<v13-2-19,19>>^ Por fim morreu Azuba. De modo que Calebe tomou para si Efrate, que com o tempo lhe deu à luz Hur.

[[v13-2-20]]

^<<v13-2-20,20>>^ Hur, por sua vez, tornou-se pai de Uri. Uri, por sua vez, tornou-se pai de Bezalel.

[[v13-2-21]]

^<<v13-2-21,21>>^ E depois Esrom teve relações com a filha de Maquir, pai de Gileade. E ele mesmo tomou-a quando tinha sessenta anos de idade, mas ela lhe deu à luz Segube.

[[v13-2-22]]

^<<v13-2-22,22>>^ Segube, por sua vez, tornou-se pai de Jair, que veio a ter vinte e três cidades na terra de Gileade.

[[v13-2-23]]

^<<v13-2-23,23>>^ Mais tarde, Gesur e a Síria tomaram deles a Havote-Jair, junto com Quenate e suas aldeias dependentes,^&#42;1^ sessenta cidades. Todos estes foram os filhos de Maquir, pai de Gileade.

[NOTE]
====
. Lit.: “e suas filhas”.
====

[[v13-2-24]]

^<<v13-2-24,24>>^ E depois da morte de Esrom em Calebe-Efrata, sendo Abias esposa de Esrom, ela lhe deu então à luz Assur, pai de Tecoa.

[[v13-2-25]]

^<<v13-2-25,25>>^ E os filhos de Jerameel, primogênito de Esrom, foram Rão, o primogênito, e Buna, e Orem, e Ozem, Aijá.^&#42;1^

[NOTE]
====
. “Ozem, Aijá”, M; LXX: “Asom, seu irmão”; Vg: “Asom e Aía”.
====

[[v13-2-26]]

^<<v13-2-26,26>>^ E Jerameel veio a ter outra esposa cujo nome foi Atara. Ela foi a mãe de Onão.

[[v13-2-27]]

^<<v13-2-27,27>>^ E os filhos de Rão, primogênito de Jerameel, vieram a ser Maaz, e Jamim, e Equer.

[[v13-2-28]]

^<<v13-2-28,28>>^ E os filhos de Onão vieram a ser Samai e Jada. E os filhos de Samai foram Nadabe e Abisur.

[[v13-2-29]]

^<<v13-2-29,29>>^ E o nome da esposa de Abisur foi Abiail, a qual com o tempo lhe deu à luz Abã e Molide.

[[v13-2-30]]

^<<v13-2-30,30>>^ E os filhos de Nadabe foram Selede e Apaim. Mas Selede morreu sem filhos.

[[v13-2-31]]

^<<v13-2-31,31>>^ E os filhos de Apaim: Isi. E os filhos de Isi: Sesã; e os filhos de Sesã: Alai.

[[v13-2-32]]

^<<v13-2-32,32>>^ E os filhos de Jada, irmão de Samai, foram Jeter e Jonatã. Mas Jeter morreu sem filhos.

[[v13-2-33]]

^<<v13-2-33,33>>^ E os filhos de Jonatã foram Pelete e Zaza. Estes se tornaram filhos de Jerameel.

[[v13-2-34]]

^<<v13-2-34,34>>^ E Sesã não veio a ter filhos, mas filhas. Ora, Sesã tinha um servo egípcio cujo nome era Jara.

[[v13-2-35]]

^<<v13-2-35,35>>^ De modo que Sesã deu a sua filha a Jara, seu servo, por esposa, sendo que com o tempo ela lhe deu à luz Atai.

[[v13-2-36]]

^<<v13-2-36,36>>^ Atai, por sua vez, tornou-se pai de Natã. Natã, por sua vez, tornou-se pai de Zabade.

[[v13-2-37]]

^<<v13-2-37,37>>^ Zabade, por sua vez, tornou-se pai de Eflal. Eflal, por sua vez, tornou-se pai de Obede.

[[v13-2-38]]

^<<v13-2-38,38>>^ Obede, por sua vez, tornou-se pai de Jeú. Jeú, por sua vez, tornou-se pai de Azarias.

[[v13-2-39]]

^<<v13-2-39,39>>^ Azarias, por sua vez, tornou-se pai de Helez. Helez, por sua vez, tornou-se pai de Eleasá.

[[v13-2-40]]

^<<v13-2-40,40>>^ Eleasá, por sua vez, tornou-se pai de Sismai. Sismai, por sua vez, tornou-se pai de Salum.

[[v13-2-41]]

^<<v13-2-41,41>>^ Salum, por sua vez, tornou-se pai de Jecamias. Jecamias, por sua vez, tornou-se pai de Elisama.

[[v13-2-42]]

^<<v13-2-42,42>>^ E os filhos de Calebe,^&#42;1^ irmão de Jerameel, foram Mesa, seu primogênito, que foi o pai de Zife, e os filhos de Maressa, pai de Hébron.

[NOTE]
====
. “Quelubai” no v. 9.
====

[[v13-2-43]]

^<<v13-2-43,43>>^ E os filhos de Hébron foram Corá, e Tapua, e Requém, e Sema.

[[v13-2-44]]

^<<v13-2-44,44>>^ Sema, por sua vez, tornou-se pai de Raão, pai de Jorqueão. Requém, por sua vez, tornou-se pai de Samai.

[[v13-2-45]]

^<<v13-2-45,45>>^ E o filho de Samai foi Maom; e Maom foi o pai de Bete-Zur.

[[v13-2-46]]

^<<v13-2-46,46>>^ Quanto a Efá, concubina de Calebe, deu à luz Harã, e Moza, e Gazez. Quanto a Harã, tornou-se pai de Gazez.

[[v13-2-47]]

^<<v13-2-47,47>>^ E os filhos de Jadai foram Regém, e Jotão, e Gesã, e Pelete, e Efá, e Saafe.

[[v13-2-48]]

^<<v13-2-48,48>>^ Quanto a Maacá, concubina de Calebe, deu à luz Seber e Tirana.

[[v13-2-49]]

^<<v13-2-49,49>>^ Com o tempo ela deu à luz Saafe, pai de Madmana, Seva, pai de Macbena e pai de Gibéia. E Acsa foi a filha de Calebe.

[[v13-2-50]]

^<<v13-2-50,50>>^ Estes tornaram-se filhos de Calebe.
Os filhos de Hur, primogênito de Efrata: Sobal, pai de Quiriate-Jearim,

[[v13-2-51]]

^<<v13-2-51,51>>^ Salma, pai de Belém, Harefe, pai de Bete-Gader.

[[v13-2-52]]

^<<v13-2-52,52>>^ E Sobal, pai de Quiriate-Jearim, veio a ter filhos: Haroé, metade dos menuotitas.

[[v13-2-53]]

^<<v13-2-53,53>>^ E as famílias de Quiriate-Jearim foram os itritas, e os putitas, e os sumatitas, e os misraítas. Foi destes que procederam os zoratitas e os estaolitas.

[[v13-2-54]]

^<<v13-2-54,54>>^ Os filhos de Salma foram Belém e os netofatitas, Atrote-Bete-Joabe e metade dos manaatitas, os zoritas.

[[v13-2-55]]

^<<v13-2-55,55>>^ E as famílias dos escribas, morando em Jabez, foram os tiratitas, os simeatitas, os sucatitas. Estes foram os queneus que procederam de Hamate, pai da casa de Recabe.

'''

xref:013-1-cronicas/013-1-cronicas-001.adoc#v13-1-0[&#60; Capítulo Anterior] | <<v13-2-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-003.adoc#v13-3-0[Próximo Capítulo &#62;]