include::./index.adoc[]

[[v13-27-0]]
=== 1 Crônicas, 27
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v13-27-1]]

^<<v13-27-1,1>>^ Quanto aos filhos de Israel, segundo o seu número, os cabeças das casas paternas, e os chefes de mil e de cem, e seus oficiais que ministravam ao rei em todo assunto das turmas daqueles que entravam e que saíam mês após mês em todos os meses do ano, cada turma tinha vinte e quatro mil.

[[v13-27-2]]

^<<v13-27-2,2>>^ Sobre a primeira turma do primeiro mês estava Jasobeão, filho de Zabdiel, e na sua turma havia vinte e quatro mil.

[[v13-27-3]]

^<<v13-27-3,3>>^ Alguns dos filhos de Peres, cabeça de todos os chefes dos grupos de serviço, eram para o primeiro mês.

[[v13-27-4]]

^<<v13-27-4,4>>^ E sobre a turma do segundo mês estava Dodai, o aoíta, com a sua turma, e Miclote era o líder, e na sua turma havia vinte e quatro mil.

[[v13-27-5]]

^<<v13-27-5,5>>^ O chefe do terceiro grupo de serviço para o terceiro mês era Benaia, filho de Jeoiada, o sacerdote principal, e na sua turma havia vinte e quatro mil.

[[v13-27-6]]

^<<v13-27-6,6>>^ Este Benaia era homem poderoso dos trinta e estava sobre os trinta; e [sobre] a sua turma estava Amizabade, seu filho.

[[v13-27-7]]

^<<v13-27-7,7>>^ O quarto para o quarto mês era Asael, irmão de Joabe, e Zebadias, seu filho, depois dele, e na sua turma havia vinte e quatro mil.

[[v13-27-8]]

^<<v13-27-8,8>>^ O quinto chefe para o quinto mês era Samute, o izraíta, e na sua turma havia vinte e quatro mil.

[[v13-27-9]]

^<<v13-27-9,9>>^ O sexto para o sexto mês era Ira, filho de Iques, o tecoíta, e na sua turma havia vinte e quatro mil.

[[v13-27-10]]

^<<v13-27-10,10>>^ O sétimo para o sétimo mês era Helez, o pelonita, dos filhos de Efraim, e na sua turma havia vinte e quatro mil.

[[v13-27-11]]

^<<v13-27-11,11>>^ O oitavo para o oitavo mês era Sibecai, o husatita, dos zeraítas, e na sua turma havia vinte e quatro mil.

[[v13-27-12]]

^<<v13-27-12,12>>^ O nono para o nono mês era Abiezer, o anatotita, dos benjaminitas, e na sua turma havia vinte e quatro mil.

[[v13-27-13]]

^<<v13-27-13,13>>^ O décimo para o décimo mês era Maarai, o netofatita, dos zeraítas, e na sua turma havia vinte e quatro mil.

[[v13-27-14]]

^<<v13-27-14,14>>^ O décimo primeiro para o décimo primeiro mês era Benaia, o piratonita, dos filhos de Efraim, e na sua turma havia vinte e quatro mil.

[[v13-27-15]]

^<<v13-27-15,15>>^ O décimo segundo para o décimo segundo mês era Heldai, o netofatita, de Otniel, e na sua turma havia vinte e quatro mil.

[[v13-27-16]]

^<<v13-27-16,16>>^ E sobre as tribos de Israel, dos rubenitas, era líder Eliézer, filho de Zicri; dos simeonitas, Sefatias, filho de Maacá;

[[v13-27-17]]

^<<v13-27-17,17>>^ de Levi, Hasabias, filho de Quemuel; de Arão, Zadoque;

[[v13-27-18]]

^<<v13-27-18,18>>^ de Judá, Eliú, um dos irmãos de Davi; de Issacar, Onri, filho de Micael;

[[v13-27-19]]

^<<v13-27-19,19>>^ de Zebulão, Ismaías, filho de Obadias; de Naftali, Jerimote, filho de Azriel;

[[v13-27-20]]

^<<v13-27-20,20>>^ dos filhos de Efraim, Oséias, filho de Azazias; da meia tribo de Manassés, Joel, filho de Pedaías;

[[v13-27-21]]

^<<v13-27-21,21>>^ da meia tribo de Manassés em Gileade, Ido, filho de Zacarias; de Benjamim, Jaasiel, filho de Abner;

[[v13-27-22]]

^<<v13-27-22,22>>^ de Dã, Azarel, filho de Jeroão. Estes foram os príncipes das tribos de Israel.

[[v13-27-23]]

^<<v13-27-23,23>>^ E Davi não tomou o número dos de vinte anos de idade e para baixo, porque Jeová prometera fazer Israel tantos quantas as estrelas dos céus.

[[v13-27-24]]

^<<v13-27-24,24>>^ Joabe, filho de Zeruia, é que tinha principiado a fazer o recenseamento, mas não o terminou; e por isto veio a haver indignação contra Israel e o número não entrou na narração dos assuntos dos dias do Rei Davi.

[[v13-27-25]]

^<<v13-27-25,25>>^ E sobre os tesouros do rei estava Asmavete, filho de Adiel. E sobre os tesouros no campo, nas cidades e nas aldeias, bem como nas torres, estava Jonatã,^&#42;1^ filho de Uzias.

[NOTE]
====
. Hebr.: Yehoh·na·thán.
====

[[v13-27-26]]

^<<v13-27-26,26>>^ E sobre os que faziam a obra no campo para o cultivo do solo estava Ezri, filho de Quelube.

[[v13-27-27]]

^<<v13-27-27,27>>^ E sobre os vinhedos estava Simei, o ramatita; e sobre o que havia nos vinhedos para o suprimento de vinho estava Zabdi, o sifmita.

[[v13-27-28]]

^<<v13-27-28,28>>^ E sobre os olivais e os sicômoros que havia na Sefelá^&#42;1^ estava Baal-Hanã, o gederita; e sobre os suprimentos de azeite estava Joás.

[NOTE]
====
. Ou “terra baixa”.
====

[[v13-27-29]]

^<<v13-27-29,29>>^ E sobre as manadas que pastavam em Sarom estava Sitrai, o saronita; e sobre as manadas nas baixadas estava Safate, filho de Adlai.

[[v13-27-30]]

^<<v13-27-30,30>>^ E sobre os camelos estava Obil, o ismaelita; e sobre as jumentas estava Jedeías, o meronotita.

[[v13-27-31]]

^<<v13-27-31,31>>^ E sobre os rebanhos estava Jaziz, o agareno. Todos estes eram chefes dos bens que pertenciam ao Rei Davi.

[[v13-27-32]]

^<<v13-27-32,32>>^ E Jonatã, sobrinho^&#42;1^ de Davi, era conselheiro, homem de entendimento, sendo também secretário; e Jeiel, filho de Acmoni, estava com os filhos do rei.

[NOTE]
====
. “Sobrinho.” Hebr.: dohdh, usualmente “tio”, mas aqui: “filho do tio; sobrinho”. Veja 20:7; 2Sa 21:21.
====

[[v13-27-33]]

^<<v13-27-33,33>>^ E Aitofel era conselheiro do rei; e Husai, o arquita, era companheiro do rei.

[[v13-27-34]]

^<<v13-27-34,34>>^ E depois de Aitofel havia Jeoiada, filho de Benaia, e Abiatar; e Joabe era o chefe do exército do rei.

'''

xref:013-1-cronicas/013-1-cronicas-026.adoc#v13-26-0[&#60; Capítulo Anterior] | <<v13-27-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-028.adoc#v13-28-0[Próximo Capítulo &#62;]