include::./index.adoc[]

[[v13-21-0]]
=== 1 Crônicas, 21
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v13-21-1]]

^<<v13-21-1,1>>^ E Satanás^&#42;1^ passou a pôr-se de pé contra Israel e a instigar Davi a recensear Israel.

[NOTE]
====
. Ou “opositor”. Hebr.: Sa·tán; sir.: Sa·ta·na’; LXX: “Diabo”; lat.: Sá·tan.
====

[[v13-21-2]]

^<<v13-21-2,2>>^ De modo que Davi disse a Joabe e aos chefes do povo: “Ide, contai Israel desde Berseba até Dã, e trazei-mo para que eu saiba o seu número.”

[[v13-21-3]]

^<<v13-21-3,3>>^ Mas Joabe disse: “Acrescente Jeová ao seu povo cem vezes mais do que são. Ó meu senhor, o rei, não pertencem todos eles ao meu senhor como servos? Por que procura isto meu senhor? Por que se deve ele tornar causa de culpa para Israel?”

[[v13-21-4]]

^<<v13-21-4,4>>^ Todavia, a palavra do rei prevaleceu sobre Joabe, de modo que Joabe saiu e percorreu todo o Israel, chegando depois a Jerusalém.

[[v13-21-5]]

^<<v13-21-5,5>>^ Joabe deu então a Davi o número do registro do povo; e todo o Israel somou um milhão^&#42;1^ e cem mil homens que puxavam da espada, e Judá, quatrocentos e setenta mil homens puxando da espada.

[NOTE]
====
. Lit.: “mil milhares”.
====

[[v13-21-6]]

^<<v13-21-6,6>>^ E a Levi e a Benjamim não registrou entre eles, porque a palavra do rei tinha sido detestável para Joabe.

[[v13-21-7]]

^<<v13-21-7,7>>^ Ora, esta coisa foi má aos olhos do [verdadeiro] Deus e por isso golpeou Israel.

[[v13-21-8]]

^<<v13-21-8,8>>^ Conseqüentemente, Davi disse ao [verdadeiro] Deus: “Pequei muitíssimo por ter feito esta coisa. E agora, por favor, faze passar o erro do teu servo; pois agi muito nesciamente.”

[[v13-21-9]]

^<<v13-21-9,9>>^ E Jeová passou a falar a Gade, visionário de Davi, dizendo:

[[v13-21-10]]

^<<v13-21-10,10>>^ “Vai, e tens de falar a Davi, dizendo: ‘Assim disse Jeová: “Há três coisas que dirijo contra ti. Escolhe para ti uma delas, para que eu ta faça.”’”

[[v13-21-11]]

^<<v13-21-11,11>>^ Por conseguinte, Gade entrou até Davi e disse-lhe: “Assim disse Jeová: ‘Faze a tua escolha:

[[v13-21-12]]

^<<v13-21-12,12>>^ se há de haver três anos de fome; ou se por três meses há de haver um arrasamento diante dos teus adversários e para [te] alcançar a espada dos teus inimigos, ou se por três dias há de haver a espada de Jeová, sim, pestilência no país, o anjo de Jeová arruinando todo o território de Israel.’ E agora vê o que devo responder Àquele que me envia.”

[[v13-21-13]]

^<<v13-21-13,13>>^ Então Davi disse a Gade: “É muito aflitivo para mim. Por favor, caia eu na mão de Jeová, porque são muitas as suas misericórdias; mas não caia eu na mão do homem.”

[[v13-21-14]]

^<<v13-21-14,14>>^ Jeová deu então uma pestilência em Israel, de modo que caíram de Israel setenta mil pessoas.

[[v13-21-15]]

^<<v13-21-15,15>>^ Outrossim, o [verdadeiro] Deus enviou um anjo a Jerusalém para a arruinar; e assim que ele começou a arruinar, Jeová o viu e começou a deplorar a calamidade; e por isso disse ao anjo que causava a ruína: “Basta! Abaixe-se agora a tua mão.” E o anjo de Jeová estava perto da eira de Ornã,^&#42;1^ o jebuseu.

[NOTE]
====
. “Araúna” em 2Sa 24:16.
====

[[v13-21-16]]

^<<v13-21-16,16>>^ Quando Davi levantou os seus olhos, chegou a ver o anjo de Jeová de pé entre a terra e os céus, com a espada desembainhada na mão estendida para Jerusalém; e Davi e os anciãos, cobertos de serapilheira, lançaram-se imediatamente com as suas faces [por terra].

[[v13-21-17]]

^<<v13-21-17,17>>^ E Davi passou a dizer ao [verdadeiro] Deus: “Não fui eu quem disse que se fizesse o recenseamento do povo, e não fui eu^&#42;1^ quem pequei e fiz indubitavelmente o mal? Quanto a estas ovelhas, que fizeram elas? Ó Jeová, meu Deus, por favor, venha a tua mão sobre mim e sobre a casa de meu pai; mas não para flagelo sobre o teu povo.”

[NOTE]
====
. “E não fui eu.” Lit.: “e eu o sou (ou: “e eu sou ele”)”. Hebr.: wa·’ani-hú’; gr.: e·gó ei·mí. A expressão ’aní hu’, “eu o sou”, é usada aqui por um homem, Davi. Em outros lugares, no M, esta expressão é usada por Deus. Veja De 32:39; Is (41:4; 43:10, 13; 46:4; 48:12; 52:6).
====

[[v13-21-18]]

^<<v13-21-18,18>>^ E o anjo de Jeová, da sua parte, disse a Gade para dizer a Davi que subisse, a fim de erigir um altar a Jeová na eira de Ornã, o jebuseu.

[[v13-21-19]]

^<<v13-21-19,19>>^ Por conseguinte, Davi subiu segundo a palavra de Gade, que este falara em nome de Jeová.

[[v13-21-20]]

^<<v13-21-20,20>>^ Entrementes, Ornã voltou-se e viu o anjo; e seus quatro filhos com ele se esconderam. Ora, Ornã estivera trilhando trigo.

[[v13-21-21]]

^<<v13-21-21,21>>^ De modo que Davi chegou até Ornã. Quando Ornã olhou e viu Davi, saiu imediatamente da eira e se curvou diante de Davi com o seu rosto por terra.

[[v13-21-22]]

^<<v13-21-22,22>>^ Davi disse então a Ornã: “Dá-me deveras o lugar da eira, para que eu construa nele um altar a Jeová. Dá-mo pelo pleno montante de dinheiro, a fim de que se faça parar o flagelo sobre o povo.”

[[v13-21-23]]

^<<v13-21-23,23>>^ Ornã, porém, disse a Davi: “Toma-o para ti, e faça meu senhor, o rei, o que for bom aos seus próprios olhos. Vê, dou deveras o gado vacum para ofertas queimadas, e o trenó debulhador como lenha, e o trigo como oferta de cereais. Dou-te deveras tudo.”

[[v13-21-24]]

^<<v13-21-24,24>>^ No entanto, o Rei Davi disse a Ornã: “Não, mas sem falta farei a compra pelo pleno montante de dinheiro, porque não levarei a Jeová o que é teu, para oferecer sacrifícios queimados sem custo.”

[[v13-21-25]]

^<<v13-21-25,25>>^ De modo que Davi deu a Ornã pelo lugar siclos^&#42;1^ de ouro no peso de seiscentos.

[NOTE]
====
. Veja Ap. 8A.
====

[[v13-21-26]]

^<<v13-21-26,26>>^ Então Davi construiu ali um altar a Jeová e ofereceu sacrifícios queimados e sacrifícios de participação em comum, e passou a invocar a Jeová, que lhe respondeu então com fogo desde os céus sobre o altar da oferta queimada.

[[v13-21-27]]

^<<v13-21-27,27>>^ Ademais, Jeová disse a palavra ao anjo, o qual, por conseguinte, retornou a sua espada à sua bainha.

[[v13-21-28]]

^<<v13-21-28,28>>^ Naquele tempo, vendo Davi que Jeová lhe respondera na eira de Ornã, o jebuseu, continuou a oferecer ali sacrifícios.

[[v13-21-29]]

^<<v13-21-29,29>>^ Mas o tabernáculo de Jeová, que Moisés fizera no ermo, e o altar da oferta queimada achavam-se naquele tempo no alto em Gibeão.

[[v13-21-30]]

^<<v13-21-30,30>>^ E Davi não foi capaz de ir perante ele para consultar a Deus^&#42;1^ porque ficara apavorado por causa da espada do anjo de Jeová.

[NOTE]
====
. “Deus.” Hebr.: ’Elo·hím; gr.: The·ón; Sy: “Jeová”; lat.: Dé·um.
====

'''

xref:013-1-cronicas/013-1-cronicas-020.adoc#v13-20-0[&#60; Capítulo Anterior] | <<v13-21-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-022.adoc#v13-22-0[Próximo Capítulo &#62;]