include::./index.adoc[]

[[v59-3-0]]
=== Tiago, 3
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v59-3-1]]

^<<v59-3-1,1>>^ Não muitos de vós deviam tornar-se instrutores, meus irmãos, sabendo que havemos de receber um julgamento mais pesado.

[[v59-3-2]]

^<<v59-3-2,2>>^ Pois, todos nós tropeçamos muitas vezes. Se alguém não tropeçar em palavra, este é homem perfeito, capaz de refrear também todo o [seu] corpo.

[[v59-3-3]]

^<<v59-3-3,3>>^ Se pomos freios nas bocas dos cavalos, para que nos obedeçam, dirigimos também todo o seu corpo.

[[v59-3-4]]

^<<v59-3-4,4>>^ Eis que até mesmo barcos, embora sejam grandes e sejam impelidos por fortes ventos, são dirigidos por um leme muito pequeno para onde queira a inclinação do timoneiro.

[[v59-3-5]]

^<<v59-3-5,5>>^ Assim também a língua é um membro pequeno, contudo, faz grandes fanfarrices. Vede quão pouco fogo é preciso para incendiar um bosque tão grande!

[[v59-3-6]]

^<<v59-3-6,6>>^ Ora, a língua é um fogo. A língua constitui um mundo de injustiça entre os nossos membros, pois mancha todo o corpo e incendeia a roda da vida natural, e é incendiada pela Geena.^&#42;1^

[NOTE]
====
. Veja Ap. 4C.
====

[[v59-3-7]]

^<<v59-3-7,7>>^ Porque toda espécie de fera, bem como de ave, e de bicho rastejante, e de animal marinho, há de ser domada e tem sido domada pelo gênero humano.

[[v59-3-8]]

^<<v59-3-8,8>>^ Mas a língua, ninguém da humanidade a pode domar. É uma coisa indisciplinada [e] prejudicial, cheia de veneno mortífero.

[[v59-3-9]]

^<<v59-3-9,9>>^ Com ela bendizemos a Jeová,^&#42;1^ sim, [o] Pai, e ainda assim amaldiçoamos com ela a homens que vieram a existir “na semelhança de Deus”.

[NOTE]
====
. “Jeová”, J18,23,28; אABC(gr.): ton Ký·ri·on; VgcSyh: “Deus”. Veja Ap. 1D.
====

[[v59-3-10]]

^<<v59-3-10,10>>^ Da mesma boca procedem bênção e maldição.
Não é correto, meus irmãos, que estas coisas se dêem assim.

[[v59-3-11]]

^<<v59-3-11,11>>^ Será que uma fonte faz brotar pela mesma abertura o que é doce e o que é amargo?

[[v59-3-12]]

^<<v59-3-12,12>>^ Meus irmãos, será que a figueira pode produzir azeitonas ou a videira figos? Tampouco pode água salgada produzir água doce.

[[v59-3-13]]

^<<v59-3-13,13>>^ Quem é sábio e entendido entre vós? Mostre ele as suas obras pela sua conduta excelente com a brandura que pertence à sabedoria.

[[v59-3-14]]

^<<v59-3-14,14>>^ Mas, se tiverdes ciúme amargo e briga nos vossos corações, não vos jacteis^&#42;1^ e não mintais contra a verdade.

[NOTE]
====
. Lit.: “não vos estejais gabando para baixo”.
====

[[v59-3-15]]

^<<v59-3-15,15>>^ Esta não é a sabedoria que desce de cima, mas é [a] terrena, animalesca,^&#42;1^ demoníaca.

[NOTE]
====
. Lit.: “de alma”. Gr.: psy·khi·ké; lat.: a·ni·má·lis. Veja 1Co 2:14 n. e 1Co 15:44 n.
====

[[v59-3-16]]

^<<v59-3-16,16>>^ Porque, onde há ciúme e briga, ali há desordem^&#42;1^ e toda coisa ruim.

[NOTE]
====
. Lit.: “instabilidade”.
====

[[v59-3-17]]

^<<v59-3-17,17>>^ Mas a sabedoria de cima é primeiramente casta, depois pacífica, razoável,^&#42;1^ pronta para obedecer, cheia de misericórdia e de bons frutos, sem parcialidade, sem hipocrisia.

[NOTE]
====
. Lit.: “dócil”.
====

[[v59-3-18]]

^<<v59-3-18,18>>^ Além disso, o fruto da justiça tem a sua semente semeada sob condições pacíficas^&#42;1^ para os^&#42;2^ que fazem paz.

[NOTE]
====
. Ou “semeada com paz”.
. Ou “pelos”.
====

'''

xref:059-tiago/059-tiago-002.adoc#v59-2-0[&#60; Capítulo Anterior] | <<v59-3-0,Topo>> | xref:059-tiago/059-tiago-004.adoc#v59-4-0[Próximo Capítulo &#62;]