include::./index.adoc[]

[[v59-5-0]]
=== Tiago, 5
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v59-5-1]]

^<<v59-5-1,1>>^ Vinde agora, vós ricos, chorai, uivando por causa das misérias que vos hão de sobrevir.

[[v59-5-2]]

^<<v59-5-2,2>>^ Vossas riquezas apodreceram e vossas roupas exteriores ficaram roídas pelas traças.

[[v59-5-3]]

^<<v59-5-3,3>>^ Vosso ouro e vossa prata estão corroídos, e a sua ferrugem será por testemunho contra vós e consumirá as vossas carnes. Algo como fogo é o que armazenastes nos últimos dias.^&#42;1^

[NOTE]
====
. Ou “e consumirá as vossas partes carnais como fogo. Armazenastes tesouro nos últimos dias”, mediante uma ligeira mudança na pontuação.
====

[[v59-5-4]]

^<<v59-5-4,4>>^ Eis que os salários devidos aos trabalhadores que ceifaram os vossos campos, mas que são retidos por vós, estão clamando, e os clamores por ajuda, da parte dos ceifeiros, chegaram aos ouvidos de Jeová^&#42;1^ dos exércitos.

[NOTE]
====
. Veja Ap. 1D.
====

[[v59-5-5]]

^<<v59-5-5,5>>^ Vivestes em luxo na terra e vos entregastes ao prazer sensual.^&#42;1^ Engordastes os vossos corações no dia da matança.

[NOTE]
====
. Lit.: “vos comportastes voluptuosamente”.
====

[[v59-5-6]]

^<<v59-5-6,6>>^ Condenastes, assassinastes o justo. Não se opõe ele a vós?^&#42;1^

[NOTE]
====
. Ou “o justo; ele não se opõe a vós”.
====

[[v59-5-7]]

^<<v59-5-7,7>>^ Portanto, exercei paciência, irmãos, até a presença^&#42;1^ do Senhor. Eis que o lavrador fica esperando o precioso fruto da terra, exercendo paciência com ele, até que venha a chuva temporã e a chuva serôdia.

[NOTE]
====
. Veja Ap. 5B.
====

[[v59-5-8]]

^<<v59-5-8,8>>^ Vós também exercei paciência; firmai os vossos corações, porque se tem aproximado a presença do Senhor.

[[v59-5-9]]

^<<v59-5-9,9>>^ Não suspireis^&#42;1^ uns contra os outros, irmãos, para que não sejais julgados. Eis que o Juiz está parado diante das portas.

[NOTE]
====
. Lit.: “Não estejais gemendo.”
====

[[v59-5-10]]

^<<v59-5-10,10>>^ Irmãos, tomai por modelo do sofrimento do mal e do exercício da paciência os profetas, que falaram em nome de Jeová.^&#42;1^

[NOTE]
====
. Veja Ap. 1D.
====

[[v59-5-11]]

^<<v59-5-11,11>>^ Eis que proclamamos felizes os que perseveraram. Ouvistes [falar] da perseverança de Jó e vistes o resultado^&#42;1^ que Jeová^&#42;2^ deu, que Jeová^&#42;3^ é mui terno em afeição e [é] misericordioso.^&#42;4^

[NOTE]
====
. Lit.: “fim”. Gr.: té·los.
. Veja Ap. 1D.
. Veja Ap. 1D.
. Lit.: “compassivo”.
====

[[v59-5-12]]

^<<v59-5-12,12>>^ Acima de tudo, porém, meus irmãos, parai de jurar, sim, quer pelo céu, quer pela terra, quer por qualquer outro juramento. Mas, o vosso sim signifique sim e o vosso não, não, para que não caiais sob o julgamento.

[[v59-5-13]]

^<<v59-5-13,13>>^ Há entre vós alguém que sofre o mal? Faça orações. Há alguém bem animado? Cante salmos.^&#42;1^

[NOTE]
====
. Ou “louvores a Deus”.
====

[[v59-5-14]]

^<<v59-5-14,14>>^ Há alguém doente entre vós? Chame a [si] os anciãos^&#42;1^ da congregação, e orem sobre ele, untando-o com óleo em nome de Jeová.^&#42;2^

[NOTE]
====
. “Anciãos.” Gr.: pre·sby·té·rous; J17,22(hebr.): ziq·néh. Veja Núm 11:25.
. Veja Ap. 1D.
====

[[v59-5-15]]

^<<v59-5-15,15>>^ E a oração de fé fará que o indisposto fique bom,^&#42;1^ e Jeová^&#42;2^ o levantará. Também, se ele tiver cometido pecados, ser-lhe-á isso perdoado.

[NOTE]
====
. Lit.: “salvará o cansado”.
. Veja Ap. 1D.
====

[[v59-5-16]]

^<<v59-5-16,16>>^ Portanto, confessai abertamente os vossos pecados uns aos outros e orai uns pelos outros, para que sejais sarados. A súplica do justo, quando em operação,^&#42;1^ tem muita força.

[NOTE]
====
. Ou “quando feita com fervor (seriedade)”.
====

[[v59-5-17]]

^<<v59-5-17,17>>^ Elias era homem com sentimentos iguais aos nossos, contudo, em oração, ele orou para que não chovesse; e não choveu no país por três anos e seis meses.

[[v59-5-18]]

^<<v59-5-18,18>>^ E ele orou novamente, e o céu deu chuva e a terra produziu os seus frutos.

[[v59-5-19]]

^<<v59-5-19,19>>^ Meus irmãos, se alguém entre vós se desencaminhar^&#42;1^ da verdade e outro o fizer voltar,

[NOTE]
====
. Lit.: “for feito errar”.
====

[[v59-5-20]]

^<<v59-5-20,20>>^ sabei que aquele que fizer um pecador voltar do erro do seu caminho salvará a sua alma da morte e cobrirá uma multidão de pecados.

'''

xref:059-tiago/059-tiago-004.adoc#v59-4-0[&#60; Capítulo Anterior] | <<v59-5-0,Topo>> | xref:060-1-pedro/060-1-pedro-001.adoc#v60-1-0[Próximo Capítulo &#62;]