include::./index.adoc[]

[[v59-1-0]]
=== Tiago, 1
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v59-1-1]]

^<<v59-1-1,1>>^ Tiago,^&#42;1^ escravo de Deus e do Senhor Jesus Cristo, às doze tribos que estão espalhadas:^&#42;2^
Cumprimentos!

[NOTE]
====
. Lit.: “Jacó”. Gr.: I·á·ko·bos. “Tiago”, nome derivado de Iago, que é uma forma abreviada de Jacó, nome que significa “Agarrar o Calcanhar; Suplantador”.
. “Que estão espalhadas.” Lit.: “os da dispersão [gr.: di·a·spo·raí; lat.: di·sper·si·ó·ne]”.
====

[[v59-1-2]]

^<<v59-1-2,2>>^ Considerai tudo com alegria, meus irmãos, ao enfrentardes diversas provações,

[[v59-1-3]]

^<<v59-1-3,3>>^ sabendo que esta qualidade provada^&#42;1^ da vossa fé produz perseverança.

[NOTE]
====
. Lit.: “a (coisa) testada”.
====

[[v59-1-4]]

^<<v59-1-4,4>>^ Mas, a perseverança tenha a sua obra completa, para que sejais completos e sãos em todos os sentidos, não vos faltando nada.

[[v59-1-5]]

^<<v59-1-5,5>>^ Portanto, se alguém de vós tiver falta de sabedoria, persista ele em pedi-la a Deus, pois ele dá generosamente a todos, e sem censurar; e ser-lhe-á dada.

[[v59-1-6]]

^<<v59-1-6,6>>^ Mas, persista ele em pedir com fé, em nada duvidando,^&#42;1^ pois quem duvida é semelhante a uma onda do mar, impelida pelo vento e agitada.

[NOTE]
====
. Lit.: “em nada julgando para si mesmo de modo dividido”.
====

[[v59-1-7]]

^<<v59-1-7,7>>^ De fato, não suponha tal homem que há de receber algo de Jeová;^&#42;1^

[NOTE]
====
. Veja Ap. 1D.
====

[[v59-1-8]]

^<<v59-1-8,8>>^ ele é homem indeciso,^&#42;1^ instável em todos os seus caminhos.

[NOTE]
====
. Lit.: “de duas almas; alma dupla”. Gr.: dí·psy·khos; lat.: dú·plex á·ni·mo.
====

[[v59-1-9]]

^<<v59-1-9,9>>^ O irmão humilde, porém, exulte sobre o seu enaltecimento,

[[v59-1-10]]

^<<v59-1-10,10>>^ e o rico, sobre a sua humilhação, porque ele passará como a flor da vegetação.

[[v59-1-11]]

^<<v59-1-11,11>>^ Pois o sol se levanta com o seu calor ardente e murcha a vegetação, e a flor dela cai e a beleza da sua aparência externa perece. Assim se desvanecerá também o rico no seu modo de vida.

[[v59-1-12]]

^<<v59-1-12,12>>^ Feliz o homem que estiver perseverando em provação, porque, ao ser aprovado, receberá a coroa da vida, que Jeová^&#42;1^ prometeu aos que continuarem a amá-lo.

[NOTE]
====
. “Jeová”, J7,8,13,16,17; C(gr.): Ký·ri·os; ItVgSyp: “Deus”; אAB: “ele”. Veja Ap. 1D.
====

[[v59-1-13]]

^<<v59-1-13,13>>^ Quando posto à prova, ninguém diga: “Estou sendo provado por Deus.” Pois, por coisas más, Deus não pode ser provado, nem prova ele a alguém.

[[v59-1-14]]

^<<v59-1-14,14>>^ Mas cada um é provado por ser provocado e engodado^&#42;1^ pelo seu próprio desejo.

[NOTE]
====
. Ou “apanhado como que com isca”. Lit.: “iscado”.
====

[[v59-1-15]]

^<<v59-1-15,15>>^ Então o desejo, tendo-se tornado fértil, dá à luz o pecado; o pecado, por sua vez, tendo sido consumado, produz a morte.

[[v59-1-16]]

^<<v59-1-16,16>>^ Não sejais desencaminhados, meus amados irmãos.

[[v59-1-17]]

^<<v59-1-17,17>>^ Toda boa dádiva e todo presente perfeito vem de cima, pois desce do Pai das luzes [celestiais], com quem não há variação da virada da sombra.^&#42;1^

[NOTE]
====
. Ou “variação ou sombra causada por uma virada”.
====

[[v59-1-18]]

^<<v59-1-18,18>>^ Porque ele o quis, ele nos produziu pela palavra da verdade, para que fôssemos certas primícias das suas criaturas.

[[v59-1-19]]

^<<v59-1-19,19>>^ Sabei isto, meus amados irmãos. Todo homem tem de ser rápido no ouvir, vagaroso no falar, vagaroso no furor;

[[v59-1-20]]

^<<v59-1-20,20>>^ pois o furor do homem não produz a justiça de Deus.

[[v59-1-21]]

^<<v59-1-21,21>>^ Por isso, afastai toda a imundície e aquela coisa supérflua, a maldade, e aceitai com brandura a implantação da palavra que é capaz de salvar as vossas almas.^&#42;1^

[NOTE]
====
. Ou “vossas vidas”. Gr.: tas psy·khás hy·món; lat.: á·ni·mas vé·stras; J17(hebr.): naf·sho·theh·khém.
====

[[v59-1-22]]

^<<v59-1-22,22>>^ Entretanto, tornai-vos cumpridores da palavra e não apenas ouvintes, enganando-vos com falsos raciocínios.

[[v59-1-23]]

^<<v59-1-23,23>>^ Porque, se alguém for ouvinte da palavra e não cumpridor, este é igual a um homem que olha para o seu rosto natural num espelho.

[[v59-1-24]]

^<<v59-1-24,24>>^ Pois, ele olha para si mesmo e vai embora, e esquece imediatamente que sorte de homem ele é.

[[v59-1-25]]

^<<v59-1-25,25>>^ Mas aquele que olha de perto^&#42;1^ para a lei perfeita que pertence à liberdade e que persiste nisso, este, porque se tornou, não ouvinte esquecediço, mas fazedor da obra, será feliz em fazê-la.

[NOTE]
====
. Lit.: “que se abaixou ao lado”.
====

[[v59-1-26]]

^<<v59-1-26,26>>^ Se algum homem achar que é^&#42;1^ adorador formal,^&#42;2^ contudo não refrear a sua língua, mas prosseguir enganando seu próprio coração, a forma de adoração de tal homem é fútil.

[NOTE]
====
. Ou “pensa ser”.
. “Adorador formal.” Lat.: re·li·gi·ó·sum, “religioso”.
====

[[v59-1-27]]

^<<v59-1-27,27>>^ A forma de adoração^&#42;1^ que é pura e imaculada do ponto de vista de nosso Deus e Pai é esta: cuidar dos órfãos^&#42;2^ e das viúvas na sua tribulação, e manter-se sem mancha do mundo.

[NOTE]
====
. “Forma de adoração.” Gr.: thre·skeí·a; lat.: re·lí·gi·o, “religião”.
. Ou “privados [dos pais, parentes]”.
====

'''

xref:058-hebreus/058-hebreus-013.adoc#v58-13-0[&#60; Capítulo Anterior] | <<v59-1-0,Topo>> | xref:059-tiago/059-tiago-002.adoc#v59-2-0[Próximo Capítulo &#62;]