include::./index.adoc[]

[[v59-2-0]]
=== Tiago, 2
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v59-2-1]]

^<<v59-2-1,1>>^ Meus irmãos, será que mantendes a fé do nosso Senhor Jesus Cristo, nossa glória, com atos de favoritismo?^&#42;1^

[NOTE]
====
. Ou: “Meus irmãos, parai de manter . . . favoritismo.”
====

[[v59-2-2]]

^<<v59-2-2,2>>^ Pois, se entrar na vossa reunião^&#42;1^ um homem com anéis de ouro nos dedos e em vestuário esplêndido, mas entrar também um pobre, em vestuário imundo,

[NOTE]
====
. “Reunião.” Gr.: sy·na·go·gén.
====

[[v59-2-3]]

^<<v59-2-3,3>>^ vós, contudo, olhardes com favor para aquele que traja vestuário esplêndido e disserdes: “Toma este assento aqui, num lugar excelente”, e disserdes ao pobre: “Fica de pé”, ou: “Toma aquele assento ali, abaixo do meu escabelo”,

[[v59-2-4]]

^<<v59-2-4,4>>^ não tendes distinções de classes entre vós e não vos tendes tornado juízes, fazendo decisões iníquas?

[[v59-2-5]]

^<<v59-2-5,5>>^ Escutai, meus amados irmãos. Não escolheu Deus os que são pobres com respeito ao mundo, para serem ricos na fé e herdeiros do reino, que ele prometeu aos que o amam?

[[v59-2-6]]

^<<v59-2-6,6>>^ Vós, porém, desonrastes o pobre. Não vos oprimem os ricos e vos arrastam perante os tribunais?^&#42;1^

[NOTE]
====
. Lit.: “lugares de julgamento”.
====

[[v59-2-7]]

^<<v59-2-7,7>>^ Não blasfemam eles do nome excelente pelo qual fostes chamados?

[[v59-2-8]]

^<<v59-2-8,8>>^ Ora, se estiverdes executando a lei régia, segundo a escritura: “Tens de amar o teu próximo como a ti mesmo”, fazeis muito bem.

[[v59-2-9]]

^<<v59-2-9,9>>^ Mas, se continuardes a mostrar favoritismo, estais praticando um pecado, porque sois repreendidos pela lei como transgressores.

[[v59-2-10]]

^<<v59-2-10,10>>^ Pois, quem observar toda a Lei, mas der um passo em falso^&#42;1^ num só ponto, tem-se tornado ofensor contra todos eles.

[NOTE]
====
. Lit.: “mas tropeçar”.
====

[[v59-2-11]]

^<<v59-2-11,11>>^ Pois, aquele que disse: “Não deves cometer adultério”, disse também: “Não deves assassinar.” Ora, se não cometeres adultério, mas assassinares, tens-te tornado transgressor da lei.

[[v59-2-12]]

^<<v59-2-12,12>>^ Persisti em falar de tal modo e persisti em proceder de modo tal como os que hão de ser julgados pela lei dum povo livre.^&#42;1^

[NOTE]
====
. Ou “lei que pertence à liberdade”.
====

[[v59-2-13]]

^<<v59-2-13,13>>^ Pois, quem não praticar a misericórdia terá o [seu] julgamento sem misericórdia. A misericórdia exulta triunfantemente sobre^&#42;1^ o julgamento.

[NOTE]
====
. Ou “como superior ao”.
====

[[v59-2-14]]

^<<v59-2-14,14>>^ De que proveito é, meus irmãos, se alguém disser que tem fé, mas ele não tiver obras? Será que tal fé o pode salvar?

[[v59-2-15]]

^<<v59-2-15,15>>^ Se um irmão ou uma irmã estiverem em nudez e lhes faltar alimento suficiente para o dia,

[[v59-2-16]]

^<<v59-2-16,16>>^ contudo, alguém de vós lhes disser: “Ide em paz, mantende-vos aquecidos e bem alimentados”, mas não lhes derdes o necessário para os [seus] corpos, de que proveito é?

[[v59-2-17]]

^<<v59-2-17,17>>^ Assim também a fé, se não tiver obras, está morta em si mesma.

[[v59-2-18]]

^<<v59-2-18,18>>^ Não obstante, alguém dirá: “Tu tens fé e eu tenho obras. Mostra-me a tua fé à parte das obras, e eu te mostrarei a minha fé pelas minhas obras.”

[[v59-2-19]]

^<<v59-2-19,19>>^ Crês tu que há um só Deus? Fazes muito bem. Contudo, os demônios crêem e estremecem.^&#42;1^

[NOTE]
====
. Lit.: “arrepiam-se”.
====

[[v59-2-20]]

^<<v59-2-20,20>>^ Mas, queres saber, ó homem vão, que a fé à parte das obras é inativa?

[[v59-2-21]]

^<<v59-2-21,21>>^ Não foi Abraão, nosso pai, declarado justo por obras, depois de ter oferecido Isaque, seu filho, no altar?

[[v59-2-22]]

^<<v59-2-22,22>>^ Observas que a [sua] fé cooperou com as suas obras e que a [sua] fé foi aperfeiçoada pelas [suas] obras,

[[v59-2-23]]

^<<v59-2-23,23>>^ e cumpriu-se a escritura que diz: “Abraão depositou fé em Jeová,^&#42;1^ e isso lhe foi contado como justiça”, e ele veio a ser chamado “amigo de Jeová”.^&#42;2^

[NOTE]
====
. Veja Ap. 1D.
. Veja Ap. 1D.
====

[[v59-2-24]]

^<<v59-2-24,24>>^ Vedes que o homem há de ser declarado justo por obras e não apenas pela fé.

[[v59-2-25]]

^<<v59-2-25,25>>^ Da mesma maneira, não foi também Raabe, a meretriz, declarada justa pelas obras, depois de ter acolhido hospitaleiramente os mensageiros e os ter enviado embora por outro caminho?

[[v59-2-26]]

^<<v59-2-26,26>>^ Deveras, assim como o corpo sem espírito^&#42;1^ está morto, assim também a fé sem obras está morta.

[NOTE]
====
. Ou “fôlego”.
====

'''

xref:059-tiago/059-tiago-001.adoc#v59-1-0[&#60; Capítulo Anterior] | <<v59-2-0,Topo>> | xref:059-tiago/059-tiago-003.adoc#v59-3-0[Próximo Capítulo &#62;]