include::./index.adoc[]

[[v59-4-0]]
=== Tiago, 4
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v59-4-1]]

^<<v59-4-1,1>>^ Donde procedem as guerras e donde vêm as lutas entre vós? Não vêm disso, a saber, dos vossos desejos ardentes de prazer sensual, que travam um combate nos vossos membros?

[[v59-4-2]]

^<<v59-4-2,2>>^ Desejais, e ainda assim não tendes. Prosseguis assassinando e cobiçando,^&#42;1^ contudo, sois incapazes de obter. Prosseguis lutando e guerreando. Não tendes porque não pedis.

[NOTE]
====
. Ou “estais ciumentos”.
====

[[v59-4-3]]

^<<v59-4-3,3>>^ Pedis, e ainda assim não recebeis, porque estais pedindo com propósito errado, para que [o] possais gastar nos vossos desejos ardentes de prazer sensual.

[[v59-4-4]]

^<<v59-4-4,4>>^ Adúlteras,^&#42;1^ não sabeis que a amizade com o mundo é inimizade com Deus? Portanto, todo aquele que quiser ser amigo do mundo constitui-se inimigo de Deus.

[NOTE]
====
. “Adúlteras.” Lat.: a·dúl·te·ri, “adúlteros”.
====

[[v59-4-5]]

^<<v59-4-5,5>>^ Ou parece-vos que a escritura diz sem propósito: “É com a tendência de invejar que o espírito que estabeleceu residência em nós está ansiando”?

[[v59-4-6]]

^<<v59-4-6,6>>^ No entanto, a benignidade imerecida que ele dá é maior. Por isso diz: “Deus opõe-se aos soberbos, mas dá benignidade imerecida aos humildes.”

[[v59-4-7]]

^<<v59-4-7,7>>^ Sujeitai-vos, portanto, a Deus; mas oponde-vos^&#42;1^ ao Diabo, e ele fugirá de vós.

[NOTE]
====
. Lit.: “postai-vos contra”.
====

[[v59-4-8]]

^<<v59-4-8,8>>^ Chegai-vos a Deus, e ele se chegará a vós. Limpai as vossas mãos, ó pecadores, e purificai os vossos corações, ó indecisos.^&#42;1^

[NOTE]
====
. Lit.: “vós de duas almas; alma dupla”.
====

[[v59-4-9]]

^<<v59-4-9,9>>^ Entregai-vos à mágoa, e pranteai e chorai. Transforme-se o vosso riso em pranto e a [vossa] alegria em abatimento.

[[v59-4-10]]

^<<v59-4-10,10>>^ Humilhai-vos aos olhos de Jeová,^&#42;1^ e ele vos enaltecerá.

[NOTE]
====
. Veja Ap. 1D.
====

[[v59-4-11]]

^<<v59-4-11,11>>^ Cessai de falar uns contra os outros, irmãos. Quem falar contra um irmão ou julgar seu irmão fala contra a lei e julga a lei. Ora, se tu julgas a lei, não és cumpridor da lei, mas juiz.

[[v59-4-12]]

^<<v59-4-12,12>>^ Há um que é legislador e juiz, aquele que é capaz de salvar e de destruir. Mas tu, quem és tu para julgares o [teu] próximo?

[[v59-4-13]]

^<<v59-4-13,13>>^ Vinde agora, vós os que dizeis: “Hoje ou amanhã viajaremos para esta cidade e passaremos ali um ano, e negociaremos e teremos lucros”,

[[v59-4-14]]

^<<v59-4-14,14>>^ ao passo que nem sabeis qual será a vossa vida amanhã. Porque sois uma bruma que aparece por um pouco de tempo e depois desaparece.

[[v59-4-15]]

^<<v59-4-15,15>>^ Devíeis dizer, em vez disso: “Se Jeová^&#42;1^ quiser, havemos de viver e também de fazer isso ou aquilo.”

[NOTE]
====
. Veja Ap. 1D.
====

[[v59-4-16]]

^<<v59-4-16,16>>^ Mas agora vos orgulhais de vossas fanfarrices pretensiosas. Todo esse orgulho é iníquo.

[[v59-4-17]]

^<<v59-4-17,17>>^ Portanto, se alguém souber fazer o que é direito e ainda assim não o faz, é pecado para ele.

'''

xref:059-tiago/059-tiago-003.adoc#v59-3-0[&#60; Capítulo Anterior] | <<v59-4-0,Topo>> | xref:059-tiago/059-tiago-005.adoc#v59-5-0[Próximo Capítulo &#62;]