include::./index.adoc[]

[[v62-4-0]]
=== 1 João, 4
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v62-4-1]]

^<<v62-4-1,1>>^ Amados, não acrediteis em toda expressão inspirada,^&#42;1^ mas provai as expressões inspiradas^&#42;2^ para ver se se originam de Deus, porque muitos falsos profetas têm saído pelo mundo afora.

[NOTE]
====
. “Expressão inspirada.” Lit.: “espírito”. Gr.: pneú·ma·ti; lat.: spi·rí·tu·i; J17,18,22(hebr.): rú·ahh.
. Ou “provai os espíritos”. Lit.: “estai provando os espíritos”.
====

[[v62-4-2]]

^<<v62-4-2,2>>^ Obtendes o conhecimento da expressão inspirada da parte de Deus pelo seguinte: Toda expressão inspirada que confessa Jesus Cristo como tendo vindo na carne origina-se de Deus,

[[v62-4-3]]

^<<v62-4-3,3>>^ mas toda expressão inspirada que não confessa a Jesus não se origina de Deus. Além disso, esta é a [expressão inspirada] do anticristo, de que ouvistes que viria, e agora já está no mundo.

[[v62-4-4]]

^<<v62-4-4,4>>^ Vós vos originais de Deus, filhinhos, e tendes vencido a tais [pessoas], porque aquele que está em união convosco é maior do que aquele que está em união com o mundo.

[[v62-4-5]]

^<<v62-4-5,5>>^ Eles se originam do mundo; é por isso que eles falam [aquilo que procede] do mundo e o mundo os escuta.

[[v62-4-6]]

^<<v62-4-6,6>>^ Nós nos originamos de Deus. Quem obtiver conhecimento de Deus nos escuta; quem não se originar de Deus não nos escuta. É assim que reconhecemos a expressão inspirada da verdade e a expressão inspirada do erro.

[[v62-4-7]]

^<<v62-4-7,7>>^ Amados, continuemos a amar-nos uns aos outros, porque o amor é de Deus, e todo aquele que ama tem nascido de Deus e obtém o conhecimento de Deus.

[[v62-4-8]]

^<<v62-4-8,8>>^ Quem não amar, não chegou a conhecer a Deus, porque Deus é amor.

[[v62-4-9]]

^<<v62-4-9,9>>^ Por meio disso é que se manifestou o amor de Deus em nosso caso, porque Deus enviou o seu Filho unigênito^&#42;1^ ao mundo, para que ganhássemos a vida por intermédio dele.

[NOTE]
====
. “Unigênito.” Gr.: mo·no·ge·né; lat.: u·ni·gé·ni·tum.
====

[[v62-4-10]]

^<<v62-4-10,10>>^ O amor é neste sentido, não que nós tenhamos amado a Deus, mas que ele nos amou e enviou seu Filho como sacrifício propiciatório^&#42;1^ pelos nossos pecados.

[NOTE]
====
. Veja 1Jo 2:2 n.
====

[[v62-4-11]]

^<<v62-4-11,11>>^ Amados, se é assim que Deus nos amou, então nós mesmos temos a obrigação de nos amarmos uns aos outros.

[[v62-4-12]]

^<<v62-4-12,12>>^ Ninguém jamais viu a Deus. Se continuarmos a amar uns aos outros, Deus permanece em nós e o seu amor é aperfeiçoado em nós.

[[v62-4-13]]

^<<v62-4-13,13>>^ Assim é que obtemos o conhecimento de que estamos permanecendo em união com ele e ele em união conosco, porque ele nos conferiu o seu espírito.

[[v62-4-14]]

^<<v62-4-14,14>>^ Adicionalmente, nós mesmos temos observado e estamos dando testemunho de que o Pai enviou seu Filho como Salvador do mundo.

[[v62-4-15]]

^<<v62-4-15,15>>^ Todo aquele que faz a confissão de que Jesus Cristo^&#42;1^ é o Filho de Deus, com tal Deus permanece em união e ele em união com Deus.

[NOTE]
====
. “Cristo”, B; אAVgSyh omitem isso.
====

[[v62-4-16]]

^<<v62-4-16,16>>^ E nós mesmos chegamos a conhecer e temos crido o amor que Deus tem em nosso caso.
Deus é amor, e quem permanece no amor permanece em união com Deus, e Deus permanece em união com ele.

[[v62-4-17]]

^<<v62-4-17,17>>^ É assim que o amor tem sido aperfeiçoado para conosco, para que tivéssemos franqueza no falar^&#42;1^ no dia do julgamento, porque, assim como esse é, assim também nós somos neste mundo.

[NOTE]
====
. “Franqueza no falar.” Ou “denodo”.
====

[[v62-4-18]]

^<<v62-4-18,18>>^ No amor não há temor, mas o perfeito amor lança fora o temor, porque o temor exerce uma restrição.^&#42;1^ Deveras, quem está em temor não tem sido aperfeiçoado no amor.

[NOTE]
====
. Ou “atalhamento; correção; punição”. Lit.: “truncamento”. Gr.: kó·la·sin. Veja Mt 25:46, onde ocorre a mesma palavra gr.
====

[[v62-4-19]]

^<<v62-4-19,19>>^ Quanto a nós, amamos porque ele nos amou primeiro.

[[v62-4-20]]

^<<v62-4-20,20>>^ Se alguém fizer a declaração: “Eu amo a Deus”, e ainda assim odiar o seu irmão, é mentiroso. Pois, quem não ama o seu irmão, a quem tem visto, não pode estar amando a Deus, a quem não tem visto.

[[v62-4-21]]

^<<v62-4-21,21>>^ E temos dele este mandamento, que aquele que ama a Deus esteja também amando o seu irmão.

'''

xref:062-1-joao/062-1-joao-003.adoc#v62-3-0[&#60; Capítulo Anterior] | <<v62-4-0,Topo>> | xref:062-1-joao/062-1-joao-005.adoc#v62-5-0[Próximo Capítulo &#62;]