include::./index.adoc[]

[[v62-3-0]]
=== 1 João, 3
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v62-3-1]]

^<<v62-3-1,1>>^ Vede que sorte de amor o Pai nos tem dado, para que fôssemos chamados filhos de Deus; e nós somos tais. É por isso que o mundo não tem conhecimento de nós, porque não chegou a conhecê-lo.

[[v62-3-2]]

^<<v62-3-2,2>>^ Amados, agora somos filhos de Deus, mas ainda não está manifesto o que havemos de ser. Sabemos que, quando ele^&#42;1^ for manifestado, seremos semelhantes a ele, porque o veremos assim como ele é.

[NOTE]
====
. Ou “isso”.
====

[[v62-3-3]]

^<<v62-3-3,3>>^ E todo aquele que tem esta esperança nele purifica-se assim como esse é puro.

[[v62-3-4]]

^<<v62-3-4,4>>^ Todo aquele que pratica^&#42;1^ o pecado está também praticando o que é contra a lei, e assim o pecado é aquilo que é contra a lei.

[NOTE]
====
. Lit.: “Todo aquele que fizer.”
====

[[v62-3-5]]

^<<v62-3-5,5>>^ Sabeis também que esse foi manifestado para tirar os [nossos]^&#42;1^ pecados, e não há nele pecado.

[NOTE]
====
. Lit. só “os”.
====

[[v62-3-6]]

^<<v62-3-6,6>>^ Todo aquele que permanece em união com ele não pratica o pecado; ninguém que pratica o pecado o tem visto, nem o chegou a conhecer.

[[v62-3-7]]

^<<v62-3-7,7>>^ Filhinhos, não vos deixeis desencaminhar; quem estiver praticando a justiça é justo, assim como esse é justo.

[[v62-3-8]]

^<<v62-3-8,8>>^ Quem estiver praticando o pecado origina-se do Diabo,^&#42;1^ porque o Diabo tem estado pecando desde [o] princípio.^&#42;2^ Com este objetivo foi manifestado o Filho de Deus, a saber, para desfazer as obras do Diabo.

[NOTE]
====
. “Do Diabo.” Gr.: tou Di·a·bó·lou; lat.: Di·á·bo·lo; J17,18,22(hebr.): has·Sa·tán.
. Ou “desde quando começou”.
====

[[v62-3-9]]

^<<v62-3-9,9>>^ Todo aquele que nasceu^&#42;1^ de Deus não está praticando o pecado, porque a Sua semente [reprodutiva] permanece em tal, e ele não pode praticar o pecado, porque nasceu de Deus.

[NOTE]
====
. Lit.: “que foi gerado”.
====

[[v62-3-10]]

^<<v62-3-10,10>>^ Os filhos de Deus e os filhos do Diabo evidenciam-se pelo seguinte fato: Todo aquele que não está praticando a justiça não se origina de Deus, nem aquele que não ama seu irmão.

[[v62-3-11]]

^<<v62-3-11,11>>^ Porque esta é a mensagem que ouvistes desde [o] princípio,^&#42;1^ que devemos ter amor uns pelos outros;

[NOTE]
====
. “Desde [o] princípio.” Gr.: ap’ ar·khés; lat.: ab i·ní·ti·o; J17(hebr.): me·ró’sh.
====

[[v62-3-12]]

^<<v62-3-12,12>>^ não como Caim, que se originou do iníquo e que matou a seu irmão. E por que causa o matou? Porque as suas próprias obras eram iníquas, mas as de seu irmão [eram] justas.

[[v62-3-13]]

^<<v62-3-13,13>>^ Não vos maravilheis, irmãos, de que o mundo vos odeie.

[[v62-3-14]]

^<<v62-3-14,14>>^ Nós sabemos que temos passado da morte para a vida porque amamos os irmãos. Quem não ama, permanece na morte.

[[v62-3-15]]

^<<v62-3-15,15>>^ Todo aquele que odeia seu irmão é homicida, e vós sabeis que nenhum homicida tem permanecente nele a vida eterna.

[[v62-3-16]]

^<<v62-3-16,16>>^ Por meio disso chegamos a conhecer o amor, porque esse entregou a sua alma^&#42;1^ por nós; e nós temos a obrigação de entregar as [nossas] almas^&#42;2^ pelos [nossos]^&#42;3^ irmãos.

[NOTE]
====
. Ou “vida”. Gr.: psy·khén; lat.: á·ni·mam; J17,18,22(hebr.): naf·shóh, “sua alma”. Veja Ap. 4A.
. Ou “vidas”.
. Lit. só “pelos”.
====

[[v62-3-17]]

^<<v62-3-17,17>>^ Mas, todo aquele que tiver os meios deste mundo para sustentar a vida e observar que o seu irmão padece necessidade, e ainda assim lhe fechar a porta das suas ternas compaixões, de que modo permanece nele o amor de Deus?

[[v62-3-18]]

^<<v62-3-18,18>>^ Filhinhos, amemos, não em palavra nem com a língua, mas em ação e em verdade.

[[v62-3-19]]

^<<v62-3-19,19>>^ Por meio disso é que saberemos que nos originamos da verdade e asseguraremos^&#42;1^ os nossos corações diante dele

[NOTE]
====
. Lit.: “persuadiremos”.
====

[[v62-3-20]]

^<<v62-3-20,20>>^ quanto a tudo em que os nossos corações nos possam condenar, porque Deus é maior do que os nossos corações e ele sabe todas as coisas.

[[v62-3-21]]

^<<v62-3-21,21>>^ Amados, se os [nossos] corações não [nos] condenarem, temos franqueza no falar para com Deus;

[[v62-3-22]]

^<<v62-3-22,22>>^ e tudo o que pedimos recebemos dele, porque estamos observando os seus mandamentos e estamos fazendo as coisas que são agradáveis aos seus olhos.

[[v62-3-23]]

^<<v62-3-23,23>>^ Deveras, este é o seu mandamento, que tenhamos fé no nome do seu Filho Jesus Cristo e que estejamos amando uns aos outros, assim como ele nos deu mandamento.

[[v62-3-24]]

^<<v62-3-24,24>>^ Ainda mais, quem observa os seus mandamentos permanece em união com ele, e ele em união com tal; e por meio disso obtemos o conhecimento de que ele permanece em união conosco, devido ao espírito que ele nos deu.

'''

xref:062-1-joao/062-1-joao-002.adoc#v62-2-0[&#60; Capítulo Anterior] | <<v62-3-0,Topo>> | xref:062-1-joao/062-1-joao-004.adoc#v62-4-0[Próximo Capítulo &#62;]