include::./index.adoc[]

[[v62-5-0]]
=== 1 João, 5
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v62-5-1]]

^<<v62-5-1,1>>^ Todo aquele que crê que Jesus é o Cristo nasceu de Deus, e todo aquele que ama a esse que fez nascer, ama [também] aquele que nasceu desse.

[[v62-5-2]]

^<<v62-5-2,2>>^ É assim que obtemos o conhecimento de que estamos amando os filhos de Deus, quando amamos a Deus e cumprimos os seus mandamentos.

[[v62-5-3]]

^<<v62-5-3,3>>^ Pois o amor de Deus significa o seguinte: que observemos os seus mandamentos; contudo, os seus mandamentos não são pesados,

[[v62-5-4]]

^<<v62-5-4,4>>^ porque tudo o que nasceu de Deus vence o mundo. E a vitória que venceu o mundo é esta: a nossa fé.

[[v62-5-5]]

^<<v62-5-5,5>>^ Quem é que vence o mundo senão aquele que tem fé em que Jesus é o Filho de Deus?

[[v62-5-6]]

^<<v62-5-6,6>>^ É este quem veio por meio de água e sangue, Jesus Cristo; não apenas com água, mas com a água e com o sangue. E é o espírito que está dando testemunho,^&#42;1^ porque o espírito é a verdade.

[NOTE]
====
. “Está dando testemunho.” Gr.: mar·ty·roún; lat.: te·sti·fi·cá·tur.
====

[[v62-5-7]]

^<<v62-5-7,7>>^ Porque são três os que dão testemunho:^&#42;1^

[NOTE]
====
. Depois de “os que dão testemunho”, אABVgSyh,p omitem as palavras acrescentadas em mss. gr. posteriores e na Vgc, a saber: “no céu, o Pai, a Palavra, e o espírito santo; e estes três são um. (8) E três são os que testificam na terra”.
====

[[v62-5-8]]

^<<v62-5-8,8>>^ o espírito, e a água, e o sangue, e os três estão de acordo.^&#42;1^

[NOTE]
====
. Lit.: “os três [testificadores] estão na uma só (coisa)”. Veja Jo 10:30 n. Para um exame mais detido deste v., veja Ap. 6B.
====

[[v62-5-9]]

^<<v62-5-9,9>>^ Se recebemos o testemunho dado por homens, o testemunho que Deus dá é maior, porque o testemunho dado por Deus é o seguinte: o fato de que ele tem dado testemunho a respeito do seu Filho.

[[v62-5-10]]

^<<v62-5-10,10>>^ Quem deposita a sua fé no Filho de Deus, este tem o testemunho no seu próprio caso.^&#42;1^ Quem não tem fé em Deus, fez dele um mentiroso, porque não depositou fé no testemunho dado, o qual Deus, como testemunha, tem dado a respeito do seu Filho.

[NOTE]
====
. Ou “em si mesmo”.
====

[[v62-5-11]]

^<<v62-5-11,11>>^ E o testemunho dado é o seguinte: que Deus nos deu a vida eterna, e esta vida está em seu Filho.

[[v62-5-12]]

^<<v62-5-12,12>>^ Quem tem o Filho, tem esta vida; quem não tem o Filho de Deus, não tem esta vida.

[[v62-5-13]]

^<<v62-5-13,13>>^ Escrevo-vos estas coisas para que saibais que tendes vida eterna, vós os que depositastes a vossa fé no nome do Filho de Deus.

[[v62-5-14]]

^<<v62-5-14,14>>^ E esta é a confiança^&#42;1^ que temos nele, que, não importa o que peçamos segundo a sua vontade, ele nos ouve.

[NOTE]
====
. Ou “esta é a franqueza no falar”.
====

[[v62-5-15]]

^<<v62-5-15,15>>^ Ainda mais, se soubermos que ele nos ouve com respeito àquilo que pedimos, sabemos que havemos de ter as coisas pedidas, visto que as pedimos a ele.

[[v62-5-16]]

^<<v62-5-16,16>>^ Se alguém avistar seu irmão cometendo um pecado que não incorre em morte,^&#42;1^ pedirá,^&#42;2^ e ele^&#42;3^ lhe dará vida, sim, aos que pecarem sem incorrer em morte. Há um pecado que incorre em morte. A respeito deste pecado não lhe digo que faça solicitação.

[NOTE]
====
. Ou “um pecado não para a morte”.
. Ou “terá de pedir”.
. Isto é, Deus, segundo o contexto.
====

[[v62-5-17]]

^<<v62-5-17,17>>^ Toda a injustiça é pecado; contudo, há um pecado que não incorre em morte.

[[v62-5-18]]

^<<v62-5-18,18>>^ Sabemos que todo aquele que tem nascido de Deus não pratica o pecado, mas o Nascido de Deus^&#42;1^ vigia sobre ele, e o iníquo não o segura.

[NOTE]
====
. “O Nascido de Deus”, isto é, Jesus Cristo, o Filho de Deus, como no v. 1 de 1Jo 5; א: “o nascido de Deus (guarda-se)”; Vg: “a geração de Deus (guarda-o)”.
====

[[v62-5-19]]

^<<v62-5-19,19>>^ Sabemos que nos originamos de Deus, mas o mundo inteiro jaz no [poder do] iníquo.

[[v62-5-20]]

^<<v62-5-20,20>>^ Mas, sabemos que o Filho de Deus veio e nos deu capacidade intelectual^&#42;1^ para podermos obter conhecimento do verdadeiro. E nós estamos em união com o verdadeiro, por meio do seu Filho Jesus Cristo. Esse é o verdadeiro Deus e a vida eterna.

[NOTE]
====
. Lit.: “percepção mental”.
====

[[v62-5-21]]

^<<v62-5-21,21>>^ Filhinhos, guardai-vos dos ídolos.

'''

xref:062-1-joao/062-1-joao-004.adoc#v62-4-0[&#60; Capítulo Anterior] | <<v62-5-0,Topo>> | xref:063-2-joao/063-2-joao-001.adoc#v63-1-0[Próximo Capítulo &#62;]