include::./index.adoc[]

[[v62-1-0]]
=== 1 João, 1
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v62-1-1]]

^<<v62-1-1,1>>^ Aquilo que era desde [o] princípio,^&#42;1^ o que temos ouvido, o que temos visto com os nossos olhos, o que temos observado atentamente e as nossas mãos têm apalpado, com respeito à palavra da vida,

[NOTE]
====
. Veja 3:11 n.
====

[[v62-1-2]]

^<<v62-1-2,2>>^ (sim, a vida foi manifestada, e nós temos visto, e estamos dando testemunho, e relatamos a vós a vida eterna que estava com o Pai e nos foi manifestada,)

[[v62-1-3]]

^<<v62-1-3,3>>^ aquilo que temos visto e ouvido também vos estamos relatando, para que vós também possais ter parceria conosco. Além disso, esta parceria nossa é com o Pai e com o seu Filho Jesus Cristo.

[[v62-1-4]]

^<<v62-1-4,4>>^ E assim escrevemos essas coisas, para que a nossa alegria seja plena.^&#42;1^

[NOTE]
====
. Lit.: “se tenha cumprido”.
====

[[v62-1-5]]

^<<v62-1-5,5>>^ E esta é a mensagem que temos ouvido dele e que vos estamos anunciando, que Deus é luz e não há nenhuma escuridão em união com ele.^&#42;1^

[NOTE]
====
. Ou “nenhuma escuridão nele”.
====

[[v62-1-6]]

^<<v62-1-6,6>>^ Se fizermos a declaração:^&#42;1^ “Temos parceria com ele”, contudo prosseguirmos andando na escuridão, estamos mentindo e não estamos praticando a verdade.

[NOTE]
====
. Lit.: “dissermos”.
====

[[v62-1-7]]

^<<v62-1-7,7>>^ No entanto, se estivermos andando na luz, assim como ele mesmo está na luz, temos parceria um com o outro, e o sangue de Jesus, seu Filho, purifica-nos de todo o pecado.

[[v62-1-8]]

^<<v62-1-8,8>>^ Se fizermos a declaração: “Não temos pecado”, estamos desencaminhando^&#42;1^ a nós mesmos e a verdade não está em nós.

[NOTE]
====
. Lit.: “estamos fazendo errar”.
====

[[v62-1-9]]

^<<v62-1-9,9>>^ Se confessarmos os nossos pecados, ele é fiel e justo para nos perdoar os nossos pecados e para nos purificar de toda a injustiça.

[[v62-1-10]]

^<<v62-1-10,10>>^ Se fizermos a declaração: “Não temos [cometido] pecado”, fazemo-lo mentiroso e a sua palavra não está em nós.

'''

xref:061-2-pedro/061-2-pedro-003.adoc#v61-3-0[&#60; Capítulo Anterior] | <<v62-1-0,Topo>> | xref:062-1-joao/062-1-joao-002.adoc#v62-2-0[Próximo Capítulo &#62;]