include::./index.adoc[]

[[v16-4-0]]
=== Neemias, 4
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v16-4-1]]

^<<v16-4-1,1>>^ ^&#42;1^ Ora, sucedeu que, assim que Sambalá ouviu que estávamos reconstruindo a muralha, ficou irado e muito ofendido, e caçoava dos judeus.

[NOTE]
====
. No M é 3:33.
====

[[v16-4-2]]

^<<v16-4-2,2>>^ E começou a dizer diante dos seus irmãos e da força militar de Samaria, sim, começou a dizer: “Que fazem estes judeus decrépitos? Dependerão de si mesmos? Farão sacrifícios? Acabarão num dia? Farão reviver as pedras dentre os montes de entulho poeirento, estando elas queimadas?”

[[v16-4-3]]

^<<v16-4-3,3>>^ Ora, Tobias, o amonita, estava ao seu lado e prosseguiu, dizendo: “Mesmo aquilo que estão construindo, se uma raposa subisse [contra aquilo], certamente derrocaria a sua muralha de pedras.”

[[v16-4-4]]

^<<v16-4-4,4>>^ Ouve, ó nosso Deus, porque nos temos tornado objeto de desprezo; e faze seu vitupério voltar sobre as suas próprias cabeças e entrega-os ao saque na terra do cativeiro.

[[v16-4-5]]

^<<v16-4-5,5>>^ E não encubras o seu erro e o seu pecado diante de ti. Não seja extinguido, pois cometeram uma ofensa contra os construtores.

[[v16-4-6]]

^<<v16-4-6,6>>^ Assim, continuamos a construir a muralha e a muralha inteira ficou ligada até à metade da sua [altura], e o povo continuou a ter coração para trabalhar.

[[v16-4-7]]

^<<v16-4-7,7>>^ ^&#42;1^ Sucedeu então que, assim que Sambalá, e Tobias, e os árabes, e os amonitas, e os asdoditas ouviram que o conserto das muralhas de Jerusalém tinha progredido, porque as brechas principiaram a ficar tapadas, eles ficaram muito irados.

[NOTE]
====
. No M, o capítulo 4 começa aqui.
====

[[v16-4-8]]

^<<v16-4-8,8>>^ E todos juntos começaram a conspirar para vir e lutar contra Jerusalém, e causar-me^&#42;1^ atrapalhação.

[NOTE]
====
. “Causar-me”, mediante uma ligeira correção; M: “causar-lhe”.
====

[[v16-4-9]]

^<<v16-4-9,9>>^ Mas oramos ao nosso Deus e por causa deles mantivemos uma guarda estacionada contra eles, dia e noite.

[[v16-4-10]]

^<<v16-4-10,10>>^ E Judá começou a dizer: “Tropeçou o poder dos carregadores, e há muito entulho; e nós mesmos não podemos construir na muralha.”

[[v16-4-11]]

^<<v16-4-11,11>>^ Além disso, os nossos adversários diziam: “Não [o] saberão nem verão até estarmos bem no meio deles, e certamente os mataremos e faremos cessar a obra.”

[[v16-4-12]]

^<<v16-4-12,12>>^ E sucedeu que, sempre que os judeus que moravam perto deles entravam, passaram a dizer-nos dez vezes: “[Subirão]^&#42;1^ de todos os lugares aonde vós retornareis a nós.”

[NOTE]
====
. “Estão subindo”, LXX; M omite isso.
====

[[v16-4-13]]

^<<v16-4-13,13>>^ De modo que mantive [homens] postados nas partes mais baixas do lugar atrás da muralha nos espaços abertos, e mantive o povo postado por famílias, com as suas espadas, suas lanças e seus arcos.

[[v16-4-14]]

^<<v16-4-14,14>>^ Quando vi [seu temor], levantei-me imediatamente e disse aos nobres e aos delegados governantes, bem como ao resto do povo: “Não tenhais medo por causa deles. Lembrai-vos de Jeová,^&#42;1^ o Grande e o Atemorizante; e lutai por vossos irmãos, vossos filhos e vossas filhas, vossas esposas e vossos lares.”

[NOTE]
====
. Uma das 134 mudanças de YHWH para ’Adho·naí feitas pelos escribas. Veja Ap. 1B.
====

[[v16-4-15]]

^<<v16-4-15,15>>^ Sucedeu então que, assim que os nossos inimigos ouviram que soubemos disso, de modo que o [verdadeiro] Deus^&#42;1^ tinha frustrado seu conselho e todos nós tínhamos voltado à muralha, cada um à sua obra,

[NOTE]
====
. “O [verdadeiro] Deus.” O artigo definido ha, “o”, precede ao título ’Elo·hím para dar ênfase. Veja Ap. 1F.
====

[[v16-4-16]]

^<<v16-4-16,16>>^ sim, sucedeu que, daquele dia em diante, metade dos meus moços estava ativa na obra e metade deles agarrava as lanças, os escudos e os arcos, e as cotas de malha; e os príncipes estavam atrás da casa inteira de Judá.

[[v16-4-17]]

^<<v16-4-17,17>>^ Quanto aos construtores sobre a muralha e os que carregavam o fardo dos carregadores, [cada] um estava ativo na obra com uma mão, ao passo que a outra agarrava a arma de arremesso.

[[v16-4-18]]

^<<v16-4-18,18>>^ E os construtores estavam cingidos, cada um com a sua espada sobre o quadril enquanto construíam; e o que tocava a buzina estava ao meu lado.

[[v16-4-19]]

^<<v16-4-19,19>>^ E passei a dizer aos nobres, e aos delegados governantes, e ao resto do povo: “A obra é grande e extensiva, e nós estamos espalhados sobre a muralha muito separados um do outro.

[[v16-4-20]]

^<<v16-4-20,20>>^ No lugar onde ouvirdes o som da buzina,^&#42;1^ ali é que vos reunireis a nós. Nosso Deus é que lutará por nós.”

[NOTE]
====
. Ou “do shofar”.
====

[[v16-4-21]]

^<<v16-4-21,21>>^ Enquanto estávamos ativos na obra, a outra metade deles agarrava também as lanças, desde o subir da alva até saírem as estrelas.

[[v16-4-22]]

^<<v16-4-22,22>>^ Outrossim, naquele tempo eu disse ao povo: “Que os homens passem a noite no meio de Jerusalém, cada um com o seu ajudante, e terão de tornar-se para nós uma guarda de noite e obreiros^&#42;1^ de dia.”

[NOTE]
====
. Lit.: “trabalhar”.
====

[[v16-4-23]]

^<<v16-4-23,23>>^ Quanto a mim e meus irmãos, e meus ajudantes, e os homens da guarda que estavam atrás de mim, não tirávamos as vestes, cada um [tendo] sua arma de arremesso na sua mão direita.^&#42;1^

[NOTE]
====
. “Na sua mão direita”, mediante uma correção; M é obscuro. Lit.: “as águas”.
====

'''

xref:016-neemias/016-neemias-003.adoc#v16-3-0[&#60; Capítulo Anterior] | <<v16-4-0,Topo>> | xref:016-neemias/016-neemias-005.adoc#v16-5-0[Próximo Capítulo &#62;]