include::./index.adoc[]

[[v16-5-0]]
=== Neemias, 5
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v16-5-1]]

^<<v16-5-1,1>>^ Entretanto, veio a haver um grande clamor da parte do povo e das suas esposas contra os seus irmãos judeus.

[[v16-5-2]]

^<<v16-5-2,2>>^ E havia os que diziam: “Estamos dando nossos filhos e nossas filhas em penhor^&#42;1^ para obtermos cereais e comermos, e para ficarmos vivos.”

[NOTE]
====
. “Dando . . . em penhor”, mediante uma ligeira correção do M. Veja v. 3.
====

[[v16-5-3]]

^<<v16-5-3,3>>^ E havia os que diziam: “Estamos dando nossos campos, e nossos vinhedos, e nossas casas em penhor para obtermos cereais durante a escassez de víveres.”

[[v16-5-4]]

^<<v16-5-4,4>>^ E havia os que diziam: “Tomamos dinheiro emprestado para o tributo do rei sobre os nossos campos e sobre os nossos vinhedos.

[[v16-5-5]]

^<<v16-5-5,5>>^ E agora, a nossa carne é igual à carne de nossos irmãos; nossos filhos são como os seus filhos, mas eis que reduzimos nossos filhos e nossas filhas a escravos, e há algumas de nossas filhas já reduzidas [a isso]; e não há poder em nossas mãos enquanto nossos campos e nossos vinhedos pertencem a outros.”

[[v16-5-6]]

^<<v16-5-6,6>>^ Fiquei então muito irado, assim que ouvi seu clamor e estas palavras.

[[v16-5-7]]

^<<v16-5-7,7>>^ De modo que meu coração fez cogitações no meu íntimo e comecei a ralhar com os nobres e com os delegados governantes, e fui dizer-lhes: “É usura que estais demandando, cada um do seu próprio irmão.”
Além disso, providenciei uma grande assembléia por causa deles.

[[v16-5-8]]

^<<v16-5-8,8>>^ E passei a dizer-lhes: “Nós mesmos compramos de volta os nossos irmãos judeus que tinham sido vendidos às nações, ao ponto que esteve em nosso poder; e ao mesmo tempo, venderíeis vós os vossos próprios irmãos e teriam eles de ser vendidos a nós?” Em vista disso ficaram sem fala e não acharam palavra.

[[v16-5-9]]

^<<v16-5-9,9>>^ E prossegui,^&#42;1^ dizendo: “Não é boa a coisa que estais fazendo. Não deveis andar no temor de nosso Deus por causa do vitupério das nações, nossos inimigos?

[NOTE]
====
. “Prossegui”, MmargemLXXSyVg; M: “prosseguiu”.
====

[[v16-5-10]]

^<<v16-5-10,10>>^ E também eu, meus irmãos e meus ajudantes emprestamos entre eles dinheiro e cereais. Por favor, deixemos de emprestar com juros.

[[v16-5-11]]

^<<v16-5-11,11>>^ Por favor, devolvei-lhes neste dia seus campos, seus vinhedos, seus olivais e suas casas e o centésimo^&#42;1^ do dinheiro, e os cereais, o vinho novo e o azeite que exigis deles como juros.”

[NOTE]
====
. Ou “um por cento”, isto é, mensalmente.
====

[[v16-5-12]]

^<<v16-5-12,12>>^ A isto disseram: “Faremos a devolução e nada requereremos deles de volta. Faremos exatamente como estás dizendo.” Chamei, portanto, os sacerdotes e os fiz jurar para fazerem segundo esta palavra.

[[v16-5-13]]

^<<v16-5-13,13>>^ Também sacudi a dobra da minha veste e disse então: “Desta maneira o [verdadeiro] Deus sacuda de sua casa e de sua propriedade adquirida a todo homem que não cumprir esta palavra; e desta maneira fique ele sacudido e vazio.” A isto disse toda a congregação:^&#42;1^ “Amém!”^&#42;2^ E começaram a louvar a Jeová. E o povo passou a fazer segundo esta palavra.

[NOTE]
====
. “A congregação.” Hebr.: haq·qa·hál; gr.: ek·kle·sí·a.
. Ou: “Assim seja!” Hebr.: ’a·mén; gr.: A·mén; lat.: á·men. Veja Ro 1:25.
====

[[v16-5-14]]

^<<v16-5-14,14>>^ Outra coisa: Desde o dia em que me comissionou para me tornar governador deles^&#42;1^ na terra de Judá, do vigésimo ano ao trigésimo segundo ano de Artaxerxes, o rei, por doze anos, eu mesmo e meus irmãos não comemos o pão devido ao governador.

[NOTE]
====
. “Governador deles”, LXX; SyVg e um ms. hebr. omitem “deles”.
====

[[v16-5-15]]

^<<v16-5-15,15>>^ Quanto aos governadores anteriores que vieram antes de mim, fizeram-no pesado ao povo, e tinham tomado deles diariamente^&#42;1^ quarenta siclos^&#42;2^ de prata para pão e vinho. Também os próprios ajudantes deles tiranizavam o povo. Quanto a mim, não fiz assim por causa do temor de Deus.

[NOTE]
====
. “Diariamente”, Vg; M: “depois”. Provavelmente: “depois, à taxa de”.
. Um siclo pesava 11,4 g. Veja Ap. 8A.
====

[[v16-5-16]]

^<<v16-5-16,16>>^ E ainda mais, participei na obra desta muralha, e não adquirimos nenhum campo; e todos os meus ajudantes estavam reunidos ali para a obra.

[[v16-5-17]]

^<<v16-5-17,17>>^ E os judeus e os delegados governantes, cento e cinqüenta homens, e os que chegavam a nós das nações ao nosso redor estavam à minha mesa.

[[v16-5-18]]

^<<v16-5-18,18>>^ Quanto ao que se veio aprontar diariamente, um touro, seis ovelhas seletas e aves, eram aprontados para mim, e uma vez cada dez dias, toda sorte de vinho em abundância. E junto com isto não requeri o pão devido ao governador, porque o serviço estava pesado sobre este povo.

[[v16-5-19]]

^<<v16-5-19,19>>^ Lembra-te deveras a meu favor, ó meu Deus, para o meu bem, de tudo o que fiz por este povo.

'''

xref:016-neemias/016-neemias-004.adoc#v16-4-0[&#60; Capítulo Anterior] | <<v16-5-0,Topo>> | xref:016-neemias/016-neemias-006.adoc#v16-6-0[Próximo Capítulo &#62;]