include::./index.adoc[]

[[v16-2-0]]
=== Neemias, 2
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v16-2-1]]

^<<v16-2-1,1>>^ E sucedeu no mês de nisã,^&#42;1^ no vigésimo ano de Artaxerxes, o rei, que havia vinho diante dele, e, como de costume, tomei o vinho e o dei ao rei. Mas nunca antes eu tinha estado sombrio diante dele.

[NOTE]
====
. “Nisã.” Esta é a primeira de duas ocorrências deste nome pós-exílico do primeiro mês lunar judaico, que cai em março e abril. Veja Est 3:7.
====

[[v16-2-2]]

^<<v16-2-2,2>>^ De modo que o rei me disse: “Por que está sombria a tua face, sendo que não estás doente? Isto não é mais que tristeza de coração.” Nisso fiquei com muito medo.

[[v16-2-3]]

^<<v16-2-3,3>>^ Então eu disse ao rei: “Viva o próprio rei por tempo indefinido! Por que não deve a minha face ficar sombria quando a cidade, a casa das sepulturas de meus antepassados, está devastada e seus próprios portões foram consumidos pelo fogo?”

[[v16-2-4]]

^<<v16-2-4,4>>^ O rei, por sua vez, me disse: “O que é que estás procurando obter?” Orei imediatamente ao Deus dos céus.

[[v16-2-5]]

^<<v16-2-5,5>>^ Depois eu disse ao rei: “Se parecer bem ao rei e se teu servo parecer bom diante de ti, que me envies a Judá, à cidade das sepulturas de meus antepassados, para que eu a reconstrua.”

[[v16-2-6]]

^<<v16-2-6,6>>^ A isto me disse o rei, enquanto sua consorte real estava sentada ao seu lado: “Até quando virá durar a tua viagem e quando retornarás?” De modo que pareceu bem perante o rei enviar-me quando lhe dei o tempo determinado.

[[v16-2-7]]

^<<v16-2-7,7>>^ E eu prossegui, dizendo ao rei: “Se parecer bem ao rei, dêem-se-me cartas para os governadores de além do Rio,^&#42;1^ para que me deixem passar até eu chegar a Judá;

[NOTE]
====
. Isto é, o Eufrates.
====

[[v16-2-8]]

^<<v16-2-8,8>>^ também uma carta para Asafe, guarda do parque^&#42;1^ que pertence ao rei, para que me dê árvores para construir com madeira os portões do Castelo^&#42;2^ que pertence à casa, e para a muralha da cidade e para a casa em que vou entrar.” Portanto, o rei mas deu, segundo a boa mão de meu Deus sobre mim.

[NOTE]
====
. “Do parque.” Hebr.: hap·par·dés; gr.: pa·ra·deí·sou; sir.: par·dai·sa’.
. Ou “da Fortaleza”, situada ao noroeste do templo reconstruído.
====

[[v16-2-9]]

^<<v16-2-9,9>>^ Por fim cheguei aos governadores de além do Rio e dei-lhes as cartas do rei. Além disso, o rei enviara comigo chefes da força militar e cavaleiros.

[[v16-2-10]]

^<<v16-2-10,10>>^ Quando Sambalá, o horonita, e Tobias, o servo, amonita, chegaram a ouvir [isso], então lhes pareceu algo muito mau, que tivesse chegado um homem^&#42;1^ para procurar algo de bom para os filhos de Israel.

[NOTE]
====
. Ou “um homem terreno”. Hebr.: ’a·dhám.
====

[[v16-2-11]]

^<<v16-2-11,11>>^ Finalmente cheguei a Jerusalém e fiquei ali por três dias.

[[v16-2-12]]

^<<v16-2-12,12>>^ Então me levantei de noite, eu e alguns homens comigo, e não informei a nenhum homem o que meu Deus me pôs no coração para fazer por Jerusalém, e não havia comigo nenhum animal doméstico exceto o animal doméstico em que eu cavalgava.

[[v16-2-13]]

^<<v16-2-13,13>>^ E passei a sair de noite pelo Portão do Vale e defronte da Fonte da Cobra Grande,^&#42;1^ e ao Portão dos Montes de Cinzas,^&#42;2^ e examinava constantemente as muralhas de Jerusalém, como tinham sido derrocadas e os portões dela tinham sido consumidos pelo fogo.

[NOTE]
====
. Lit.: “Fonte do Dragão”, MVg; mediante uma correção do M em harmonia com LXX: “Fonte das Figueiras”. Provavelmente o Poço de En-Rogel.
. “Portão dos Montes de Cinzas.” Usualmente chamado de Portão do Esterco, como em LXXVg.
====

[[v16-2-14]]

^<<v16-2-14,14>>^ E passei adiante ao Portão da Fonte e ao Reservatório de Água do Rei e não havia ali lugar para o animal doméstico debaixo de mim passar.

[[v16-2-15]]

^<<v16-2-15,15>>^ Mas continuei subindo de noite pelo vale da torrente e prossegui examinando a muralha; depois voltei e entrei pelo Portão do Vale, e assim cheguei de volta.

[[v16-2-16]]

^<<v16-2-16,16>>^ E os próprios delegados governantes não sabiam aonde eu tinha ido e o que estava fazendo; e eu não comunicara ainda nada aos judeus, nem aos sacerdotes, nem aos nobres, nem aos delegados governantes, nem ao resto dos que faziam a obra.

[[v16-2-17]]

^<<v16-2-17,17>>^ Finalmente, eu lhes disse: “Vós estais vendo os sérios apuros em que estamos, como Jerusalém está devastada e seus portões foram queimados com fogo. Vinde e reconstruamos a muralha de Jerusalém, para que não continuemos mais a ser um vitupério.”

[[v16-2-18]]

^<<v16-2-18,18>>^ E prossegui, contando-lhes a respeito da mão de meu Deus, como fora boa sobre mim, e também a respeito das palavras do rei, as quais ele me dissera. Então disseram: “Levantemo-nos, e temos de construir.” Fortaleceram assim as suas mãos para a boa obra.

[[v16-2-19]]

^<<v16-2-19,19>>^ Ora, ouvindo isso Sambalá, o horonita, e Tobias, o servo, amonita, e Gesém, o árabe, começaram a caçoar de nós e a olhar com desprezo para nós, e passaram a dizer: “Que coisa é esta que estais fazendo? É contra o rei que vos estais rebelando?”

[[v16-2-20]]

^<<v16-2-20,20>>^ Todavia, repliquei-lhes e disse-lhes: “O Deus dos céus é quem nos concederá bom êxito, e nós mesmos, seus servos, nos levantaremos e teremos de construir; mas vós mesmos não tendes quinhão, nem reivindicação justa, nem recordação em Jerusalém.”

'''

xref:016-neemias/016-neemias-001.adoc#v16-1-0[&#60; Capítulo Anterior] | <<v16-2-0,Topo>> | xref:016-neemias/016-neemias-003.adoc#v16-3-0[Próximo Capítulo &#62;]