include::./index.adoc[]

[[v16-11-0]]
=== Neemias, 11
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v16-11-1]]

^<<v16-11-1,1>>^ Ora, os príncipes do povo tinham a sua morada em Jerusalém; mas, quanto ao restante do povo, lançaram sortes para trazer para dentro um em cada dez, para morar em Jerusalém, a cidade santa, e as outras nove partes nas outras cidades.

[[v16-11-2]]

^<<v16-11-2,2>>^ Além disso, o povo abençoou todos os homens que se ofereceram voluntariamente para morar em Jerusalém.

[[v16-11-3]]

^<<v16-11-3,3>>^ E estes são os cabeças do distrito jurisdicional que moravam em Jerusalém; mas nas cidades de Judá morava cada um na sua própria propriedade, nas suas cidades, Israel, os sacerdotes e os levitas, e os netineus,^&#42;1^ e os filhos dos servos de Salomão.

[NOTE]
====
. Veja 10:28 n.
====

[[v16-11-4]]

^<<v16-11-4,4>>^ Também, em Jerusalém moravam alguns dos filhos de Judá e alguns dos filhos de Benjamim. Dos filhos de Judá havia Ataías, filho de Uzias, filho de Zacarias, filho de Amarias, filho de Sefatias, filho de Malalel, dos filhos de Peres;

[[v16-11-5]]

^<<v16-11-5,5>>^ e Maaséias, filho de Baruque, filho de Colozé, filho de Hazaías, filho de Adaías, filho de Joiaribe, filho de Zacarias, filho do selanita.^&#42;1^

[NOTE]
====
. “Selanita”, mediante uma correção dos sinais vocálicos; M: “silonita”. Veja Núm 26:20.
====

[[v16-11-6]]

^<<v16-11-6,6>>^ Todos os filhos de Peres que moravam em Jerusalém eram quatrocentos e sessenta e oito, homens capazes.

[[v16-11-7]]

^<<v16-11-7,7>>^ E estes foram os filhos de Benjamim: Salu, filho de Mesulão, filho de Joede, filho de Pedaías, filho de Colaías, filho de Maaséias, filho de Itiel, filho de Jesaías;

[[v16-11-8]]

^<<v16-11-8,8>>^ e depois dele^&#42;1^ Gabai [e] Salai,^&#42;2^ novecentos e vinte e oito;

[NOTE]
====
. “E seus irmãos”, LXXL.
. Possivelmente: “e seus irmãos, homens poderosos de valor”, mediante uma correção do M. Veja v. 14a.
====

[[v16-11-9]]

^<<v16-11-9,9>>^ e Joel, filho de Zicri, superintendente^&#42;1^ deles, e Judá, filho de Hassenua, [que estava] sobre a cidade como segundo.

[NOTE]
====
. “Superintendente.” Hebr.: pa·qídh; gr.: e·pí·sko·pos. Veja 2Rs 11:18 n.; At 20:28 n.: “superintendentes”.
====

[[v16-11-10]]

^<<v16-11-10,10>>^ Dos sacerdotes: Jedaías, filho de Joiaribe, Jaquim,

[[v16-11-11]]

^<<v16-11-11,11>>^ Seraías, filho de Hilquias, filho de Mesulão, filho de Zadoque, filho de Meraiote, filho de Aitube, líder da casa do [verdadeiro] Deus;

[[v16-11-12]]

^<<v16-11-12,12>>^ e seus irmãos, os que faziam a obra da casa, oitocentos e vinte e dois; e Adaías, filho de Jeroão, filho de Pelalias, filho de Anzi, filho de Zacarias, filho de Pasur, filho de Malquijá,

[[v16-11-13]]

^<<v16-11-13,13>>^ e seus irmãos, cabeças de casas paternas, duzentos e quarenta e dois, e Amassai, filho de Azarel, filho de Azai, filho de Mesilemote, filho de Imer,

[[v16-11-14]]

^<<v16-11-14,14>>^ e seus irmãos, homens poderosos de valor, cento e vinte e oito, e sobre eles havia um superintendente, Zabdiel, filho dos grandes.

[[v16-11-15]]

^<<v16-11-15,15>>^ E dos levitas: Semaías, filho de Hassube, filho de Azricão, filho de Hasabias, filho de Buni,

[[v16-11-16]]

^<<v16-11-16,16>>^ e Sabetai, e Jozabade, dos cabeças dos levitas, sobre os negócios externos da casa do [verdadeiro] Deus;

[[v16-11-17]]

^<<v16-11-17,17>>^ e o próprio Matanias, filho de Micá, filho de Zabdi, filho de Asafe, dirigente^&#42;1^ do [canto de] louvor, fazia os elogios na oração, e Bacbuquias foi o segundo dos seus irmãos, e Abda, filho de Samua, filho de Galal, filho de Jedutum.

[NOTE]
====
. Lit.: “cabeça”. Hebr.: ro’sh.
====

[[v16-11-18]]

^<<v16-11-18,18>>^ Todos os levitas na cidade santa foram duzentos e oitenta e quatro.

[[v16-11-19]]

^<<v16-11-19,19>>^ E os porteiros foram Acube, Talmom e seus irmãos, que montavam guarda nos portões, cento e setenta e dois.

[[v16-11-20]]

^<<v16-11-20,20>>^ E o restante de Israel, dos sacerdotes [e] dos levitas, estava em todas as outras cidades de Judá, cada um na sua própria propriedade hereditária.

[[v16-11-21]]

^<<v16-11-21,21>>^ E os netineus moravam em Ofel; e Ziá e Gispa estavam sobre os netineus.

[[v16-11-22]]

^<<v16-11-22,22>>^ E o superintendente dos levitas em Jerusalém foi Uzi, filho de Bani, filho de Hasabias, filho de Matanias, filho de Mica, dos filhos de Asafe, os cantores, no que se referia à obra da casa do [verdadeiro] Deus.

[[v16-11-23]]

^<<v16-11-23,23>>^ Pois havia um mandamento do rei a favor deles e havia uma provisão fixa para os cantores, conforme cada dia exigia.

[[v16-11-24]]

^<<v16-11-24,24>>^ E Petaías, filho de Mesezabel, dos filhos de Zerá, filho de Judá, estava ao lado do rei para todo assunto do povo.

[[v16-11-25]]

^<<v16-11-25,25>>^ E no que se referia aos seus povoados nos campos, havia alguns dos filhos de Judá morando em Quiriate-Arba e nas suas aldeias dependentes,^&#42;1^ e em Díbon^&#42;2^ e nas suas aldeias dependentes, e em Jecabzeel e nos seus povoados,

[NOTE]
====
. Lit.: “e nas suas filhas”.
. Provavelmente a “Dimona” de Jos 15:22.
====

[[v16-11-26]]

^<<v16-11-26,26>>^ e em Jesua,^&#42;1^ e em Moladá, e em Bete-Pelete,

[NOTE]
====
. “Jesus”, LXX.
====

[[v16-11-27]]

^<<v16-11-27,27>>^ e em Hazar-Sual, e em Berseba e nas suas aldeias dependentes,

[[v16-11-28]]

^<<v16-11-28,28>>^ e em Ziclague, e em Meconá e nas suas aldeias dependentes,

[[v16-11-29]]

^<<v16-11-29,29>>^ e em En-Rimom, e em Zorá, e em Jarmute,

[[v16-11-30]]

^<<v16-11-30,30>>^ Zanoa, Adulão e seus povoados, Laquis e seus campos, Azeca e suas aldeias dependentes. E passaram a acampar-se desde Berseba até o vale de Hinom.^&#42;1^

[NOTE]
====
. “Vale de Hinom.” Hebr.: geh’-Hin·nóm; lat.: vál·lem Én·nom. Veja Ap. 4C.
====

[[v16-11-31]]

^<<v16-11-31,31>>^ E os filhos de Benjamim eram de Geba, Micmás e Aija, e Betel e suas aldeias dependentes,

[[v16-11-32]]

^<<v16-11-32,32>>^ Anatote, Nobe, Ananias,

[[v16-11-33]]

^<<v16-11-33,33>>^ Hazor, Ramá, Gitaim,

[[v16-11-34]]

^<<v16-11-34,34>>^ Hadide, Zeboim, Nebalate,

[[v16-11-35]]

^<<v16-11-35,35>>^ Lode e Ono, o vale dos artífices.

[[v16-11-36]]

^<<v16-11-36,36>>^ E dos levitas havia turmas de Judá para Benjamim.^&#42;1^

[NOTE]
====
. “Para Judá e para Benjamim”, LXXL.
====

'''

xref:016-neemias/016-neemias-010.adoc#v16-10-0[&#60; Capítulo Anterior] | <<v16-11-0,Topo>> | xref:016-neemias/016-neemias-012.adoc#v16-12-0[Próximo Capítulo &#62;]