include::./index.adoc[]

[[v4-23-0]]
=== Números, 23
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v4-23-1]]

^<<v4-23-1,1>>^ Balaão disse então a Balaque: “Constrói para mim neste ponto sete altares e apronta para mim neste ponto sete novilhos e sete carneiros.”

[[v4-23-2]]

^<<v4-23-2,2>>^ Balaque fez imediatamente como Balaão falou. Depois, Balaque e Balaão ofereceram em cada altar^&#42;1^ um novilho e um carneiro.

[NOTE]
====
. Lit.: “no altar”, MSamLXX; Sy: “nos altares”.
====

[[v4-23-3]]

^<<v4-23-3,3>>^ E Balaão prosseguiu, dizendo a Balaque: “Posta-te junto à tua oferta queimada e deixa-me ir. Talvez Jeová entre em contato comigo e tenha encontro comigo. Neste caso hei de contar-te o que ele me mostrar.” Ele foi assim a um morro calvo.

[[v4-23-4]]

^<<v4-23-4,4>>^ Quando Deus entrou em contato com Balaão, então este lhe disse: “Enfileirei os sete altares e passei a oferecer em cada altar um novilho e um carneiro.”

[[v4-23-5]]

^<<v4-23-5,5>>^ Por conseguinte, Jeová^&#42;1^ pôs uma palavra na boca de Balaão e disse: “Volta a Balaque, e isto é o que falarás.”

[NOTE]
====
. “Jeová”, M; Sam: “o anjo de Jeová”; LXX: “Deus”.
====

[[v4-23-6]]

^<<v4-23-6,6>>^ De modo que voltou a ele, e eis que ele e todos os príncipes de Moabe estavam de pé junto à sua oferta queimada.

[[v4-23-7]]

^<<v4-23-7,7>>^ Encetou então seu dito proverbial e disse:
“Desde Arã^&#42;1^ [foi que] Balaque, rei de Moabe, procurou guiar-me,
Desde as montanhas do oriente:
‘Vem deveras, amaldiçoa-me deveras a Jacó.
Sim, vem deveras, verbera deveras a Israel.’

[NOTE]
====
. “Arã”, MSamSyVg; LXX: “Mesopotâmia”.
====

[[v4-23-8]]

^<<v4-23-8,8>>^ Como poderia eu maldizer os que Deus^&#42;1^ não maldisse?
E como poderia eu verberar os que Jeová não verberou?

[NOTE]
====
. “Deus.” Hebr.: ’El; gr.: Ký·ri·os, “Jeová”; lat.: Dé·us.
====

[[v4-23-9]]

^<<v4-23-9,9>>^ Pois vejo-os^&#42;1^ do cume das rochas,
E avisto-os das colinas.
Ali residem isolados como povo,
E não se consideram^&#42;2^ entre as nações.

[NOTE]
====
. Lit.: “vejo-o”, isto é, a Jacó, ou Israel, como povo.
. Lit.: “considera”.
====

[[v4-23-10]]

^<<v4-23-10,10>>^ Quem computou as partículas de pó de Jacó,
E quem contou a quarta parte^&#42;1^ de Israel?
Morra minha alma a morte dos retos,
E seja meu fim posteriormente igual ao deles.”^&#42;2^

[NOTE]
====
. Possivelmente deveria rezar: “contou as miríades (dezenas de milhares)”.
. “Deles”, LXXSyVg; Sam: “dele”.
====

[[v4-23-11]]

^<<v4-23-11,11>>^ Em vista disso, Balaque disse a Balaão: “O que me fizeste? Foi para maldizer os meus inimigos que te tomei, e eis que os abençoaste até o limite.”

[[v4-23-12]]

^<<v4-23-12,12>>^ Ele respondeu por sua vez e disse: “Não é aquilo que Jeová põe na minha boca que eu devo cuidar em falar?”

[[v4-23-13]]

^<<v4-23-13,13>>^ Balaque disse-lhe então: “Por favor, vem deveras comigo a outro lugar do qual os poderás ver. Verás apenas a extremidade deles e não verás a todos eles. E maldize-os dali para mim.”

[[v4-23-14]]

^<<v4-23-14,14>>^ Levou-o, pois, ao campo de Zofim, ao cume do Pisga, e passou a construir sete altares e a oferecer em cada altar um novilho e um carneiro.

[[v4-23-15]]

^<<v4-23-15,15>>^ Depois ele disse a Balaque: “Posta-te aqui junto à tua oferta queimada, e, quanto a mim, deixa-me ali entrar em contato com ele.”

[[v4-23-16]]

^<<v4-23-16,16>>^ Subseqüentemente, Jeová^&#42;1^ entrou em contato com Balaão e pôs uma palavra na sua boca, e disse: “Volta a Balaque, e isto é o que falarás.”

[NOTE]
====
. Veja v. 5 n.
====

[[v4-23-17]]

^<<v4-23-17,17>>^ Assim, foi ter com ele, e eis que estava de pé junto à sua oferta queimada, e com ele os príncipes de Moabe. Balaque disse-lhe então: “Que falou Jeová?”

[[v4-23-18]]

^<<v4-23-18,18>>^ Nisso ele encetou seu dito proverbial e disse:
“Levanta-te, Balaque, e escuta.
Dá-me ouvidos, ó filho de Zipor.

[[v4-23-19]]

^<<v4-23-19,19>>^ Deus^&#42;1^ não é homem para mentir,
Nem filho da humanidade para ter lástima.
Foi ele mesmo quem o disse, e não o fará?
E falou ele, e não o cumprirá?

[NOTE]
====
. “Deus.” Hebr.: ’El; gr.: ho The·ós; lat.: Dé·us.
====

[[v4-23-20]]

^<<v4-23-20,20>>^ Eis que fui tomado^&#42;1^ para abençoar,
E Ele tem abençoado^&#42;2^ e eu não o inverterei.

[NOTE]
====
. “Fui tomado”, LXXSyVg; M: “Tomei [a ordem].”
. “Ele tem abençoado”, M; SamLXX: “abençoarei”.
====

[[v4-23-21]]

^<<v4-23-21,21>>^ Não reconheceu nenhum poder mágico^&#42;1^ contra Jacó,
E não viu desgraça para Israel.
Jeová, seu Deus, está com ele,
E a aclamação alta dum rei está no seu meio.

[NOTE]
====
. Ou “nenhum estado de tabu”.
====

[[v4-23-22]]

^<<v4-23-22,22>>^ Deus^&#42;1^ os^&#42;2^ está fazendo sair do Egito.
Sua carreira veloz é como a dum touro selvagem.^&#42;3^

[NOTE]
====
. “Deus.” Hebr.: ’El; gr.: The·ós; lat.: Dé·us.
. “Os”, MSamLXXSy; Vg: “o”.
. Ou “búfalo”. LXX: “unicórnio”; Vg: “rinoceronte”.
====

[[v4-23-23]]

^<<v4-23-23,23>>^ Pois contra Jacó não há feitiço de azar,
Nem adivinhação contra Israel.
Nesta hora se pode dizer com respeito a Jacó e Israel:
‘O que Deus^&#42;1^ tem realizado!’

[NOTE]
====
. “Deus.” MSam(hebr.): ’El; gr.: ho The·ós; lat.: Dé·us.
====

[[v4-23-24]]

^<<v4-23-24,24>>^ Eis que um povo se levantará como leão,^&#42;1^
E como o leão^&#42;2^ se erguerá.
Não se deitará até comer alguma presa,
E beberá o sangue dos que foram mortos.”

[NOTE]
====
. “Como leão.” Hebr.: kela·ví, o leão asiático.
. “E como o leão.” Hebr.: wekha·’arí, o leão africano.
====

[[v4-23-25]]

^<<v4-23-25,25>>^ Nisso Balaque disse a Balaão: “Se, por um lado, absolutamente não o podes maldizer, então, por outro lado, absolutamente não o deves abençoar.”

[[v4-23-26]]

^<<v4-23-26,26>>^ Balaão respondeu, por sua vez, e disse a Balaque: “Não te falei, dizendo: ‘Tudo o que Jeová falar é o que farei’?”

[[v4-23-27]]

^<<v4-23-27,27>>^ Balaque disse então a Balaão: “Oh! vem, por favor. Deixa-me levar-te ainda a outro lugar. Talvez seja direito aos olhos do [verdadeiro] Deus, de modo que certamente o maldigas dali para mim.”

[[v4-23-28]]

^<<v4-23-28,28>>^ Com isso Balaque levou Balaão ao cume de Peor, que olha para Jesimom.

[[v4-23-29]]

^<<v4-23-29,29>>^ Balaão disse então a Balaque: “Constrói para mim neste ponto sete altares e apronta para mim neste ponto sete novilhos e sete carneiros.”

[[v4-23-30]]

^<<v4-23-30,30>>^ De modo que Balaque fez exatamente como Balaão dissera e foi oferecer em cada altar um novilho e um carneiro.

'''

xref:004-numeros/004-numeros-022.adoc#v4-22-0[&#60; Capítulo Anterior] | <<v4-23-0,Topo>> | xref:004-numeros/004-numeros-024.adoc#v4-24-0[Próximo Capítulo &#62;]