include::./index.adoc[]

[[v4-11-0]]
=== Números, 11
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v4-11-1]]

^<<v4-11-1,1>>^ Então, o povo tornou-se como homens que têm algo de mau a queixar-se aos ouvidos de Jeová. Quando Jeová chegou a ouvir isso, então se acendeu a sua ira, e um fogo da parte de Jeová começou a arder contra eles e a consumir a alguns na extremidade do acampamento.

[[v4-11-2]]

^<<v4-11-2,2>>^ Quando o povo começou a clamar a Moisés, então ele fez rogos a Jeová, e o fogo baixou.

[[v4-11-3]]

^<<v4-11-3,3>>^ E aquele lugar chegou a ser chamado^&#42;1^ pelo nome de Taberá,^&#42;2^ porque um fogo da parte de Jeová havia ardido contra eles.

[NOTE]
====
. Lit.: “E ele passou a chamar o nome daquele lugar.”
. Significando “Queima; Conflagração; Incêndio”.
====

[[v4-11-4]]

^<<v4-11-4,4>>^ E a multidão mista^&#42;1^ que havia no seu meio expressou almejos egoístas, e também os filhos de Israel começaram a chorar novamente e a dizer: “Quem nos dará carne para comer?

[NOTE]
====
. Ou “a aglomeração [de gente]; a ralé”.
====

[[v4-11-5]]

^<<v4-11-5,5>>^ Como nos lembramos dos peixes que costumávamos comer de graça no Egito, dos pepinos e das melancias, e dos alhos-porros, e das cebolas, e do alho!

[[v4-11-6]]

^<<v4-11-6,6>>^ Mas agora a nossa alma está ressequida. Nossos olhos não vêem nada senão o maná.”

[[v4-11-7]]

^<<v4-11-7,7>>^ Incidentalmente, o maná era como semente de coentro e seu aspecto^&#42;1^ era como o aspecto de bdélio.

[NOTE]
====
. Ou “cor”.
====

[[v4-11-8]]

^<<v4-11-8,8>>^ O povo se espalhava e o apanhava, e moía-o em moinhos manuais ou pilava-o num gral, e cozinhavam-no em caçarolas ou faziam dele bolos redondos, e seu sabor era semelhante ao sabor dum bolo doce com azeite.

[[v4-11-9]]

^<<v4-11-9,9>>^ E descendo o orvalho sobre o acampamento durante a noite, descia sobre ele o maná.

[[v4-11-10]]

^<<v4-11-10,10>>^ E Moisés chegou a ouvir o povo chorando nas suas famílias, cada homem à entrada da sua tenda. E começou a acender-se grandemente a ira de Jeová, e era mau aos olhos de Moisés.

[[v4-11-11]]

^<<v4-11-11,11>>^ Moisés disse então a Jeová: “Por que causaste o mal ao teu servo^&#42;1^ e por que não achei favor aos teus olhos, pondo sobre mim a carga de todo este povo?

[NOTE]
====
. Ou “escravo”.
====

[[v4-11-12]]

^<<v4-11-12,12>>^ Fui eu quem concebeu todo este povo? Fui eu quem os deu à luz, de modo que me digas: ‘Carrega-os ao teu colo, assim como o aio carrega a criança de peito’, para o solo que juraste aos seus antepassados?

[[v4-11-13]]

^<<v4-11-13,13>>^ Onde é que tenho carne para dar a todo este povo? Pois persistem em chorar diante de mim, dizendo: ‘Dá-nos carne, e comamos!’

[[v4-11-14]]

^<<v4-11-14,14>>^ Não posso, por mim mesmo, carregar todo este povo, porque são pesados demais para mim.

[[v4-11-15]]

^<<v4-11-15,15>>^ Portanto, se é assim que fazes comigo, por favor, mata-me^&#42;1^ então de vez, se eu tiver achado favor aos teus olhos, e não me deixes olhar para a minha calamidade.”^&#42;2^

[NOTE]
====
. “Mata-me.” Lit.: “para matar-me”. No hebr., este verbo está no infinitivo construto, mas alguns o lêem como imperativo.
. “Para a minha calamidade”, corrigido pelos soferins para rezar assim, em vez de “para a tua calamidade”. Esta é uma das Dezoito Emendas dos soferins. Veja Ap. 2B.
====

[[v4-11-16]]

^<<v4-11-16,16>>^ Jeová, por sua vez, disse a Moisés: “Ajunta-me setenta homens dos anciãos de Israel, dos quais deveras sabes que são anciãos do povo e oficiais deles, e tens de levá-los à tenda de reunião e eles têm de postar-se ali contigo.

[[v4-11-17]]

^<<v4-11-17,17>>^ E eu terei de descer e falar contigo ali; e terei de tirar um pouco do espírito que há sobre ti e colocá-lo sobre eles, e terão de ajudar-te a levar a carga do povo, para que tu mesmo não a leves sozinho.

[[v4-11-18]]

^<<v4-11-18,18>>^ E deves dizer ao povo: ‘Santificai-vos para amanhã, visto que certamente comereis carne, porque chorastes aos ouvidos de Jeová, dizendo: “Quem nos dará carne para comer, pois ia-nos bem no Egito?” E Jeová certamente vos dará carne e deveras comereis.

[[v4-11-19]]

^<<v4-11-19,19>>^ Comereis, não um dia, nem dois dias, nem cinco dias, nem dez dias, nem vinte dias,

[[v4-11-20]]

^<<v4-11-20,20>>^ mas até um mês de dias, até que saia das vossas narinas e fiqueis com aversão dela, só porque rejeitastes a Jeová, que está no vosso meio, e fostes chorar diante dele, dizendo: “Por que é que saímos do Egito?”’”

[[v4-11-21]]

^<<v4-11-21,21>>^ Moisés disse então: “O povo no meio do qual estou são seiscentos mil homens a pé, e ainda assim tu — tu disseste: ‘Dar-lhes-ei carne, e certamente comerão por um mês de dias’!

[[v4-11-22]]

^<<v4-11-22,22>>^ Abater-se-ão para eles rebanhos e manadas, a fim de que seja suficiente para eles? Ou apanhar-se-ão para eles todos os peixes do mar, a fim de que seja suficiente para eles?”

[[v4-11-23]]

^<<v4-11-23,23>>^ A isso Jeová disse a Moisés: “Será que a mão de Jeová é encurtada? Agora verás se vem ou não [vem] sobre ti o que eu digo.”

[[v4-11-24]]

^<<v4-11-24,24>>^ Após isso, Moisés saiu e falou ao povo as palavras de Jeová. E foi ajuntar setenta homens dos anciãos do povo e passou a fazê-los ficar de pé em volta da tenda.

[[v4-11-25]]

^<<v4-11-25,25>>^ Jeová desceu então numa nuvem e falou com ele, e tirou um pouco do espírito que havia sobre ele e o pôs sobre cada um dos setenta anciãos.^&#42;1^ E sucedeu que assim que o espírito pousou sobre eles, passaram então a proceder como profetas; mas não o fizeram outra vez.^&#42;2^

[NOTE]
====
. “Dos . . . anciãos.” Hebr.: haz·zeqe·ním; gr.: pre·sby·té·rous. Veja At 15:2 n.
. “Mas não o fizeram outra vez”, MLXXSy; com sinais vocálicos diferentes no verbo hebr., de acordo com TJ,OVg: “e não pararam”.
====

[[v4-11-26]]

^<<v4-11-26,26>>^ Ora, havia dois dos homens que tinham ficado no acampamento. O nome de um era Eldade e o nome do outro era Medade. E o espírito começou a pousar sobre eles, visto que se achavam entre os anotados, mas não tinham saído até a tenda. De modo que passaram a proceder como profetas no acampamento.

[[v4-11-27]]

^<<v4-11-27,27>>^ E um jovem foi correndo e o comunicou a Moisés, dizendo: “Eldade e Medade estão procedendo como profetas no acampamento!”

[[v4-11-28]]

^<<v4-11-28,28>>^ Então Josué,^&#42;1^ filho de Num, ministro de Moisés desde a sua idade viril, respondeu e disse: “Meu senhor Moisés, reprime-os!”

[NOTE]
====
. “Josué.” Hebr.: Yehoh·shú·a‛, “Jeosué”. Veja Êx 17:9 n.
====

[[v4-11-29]]

^<<v4-11-29,29>>^ No entanto, Moisés disse-lhe: “Tens ciúmes em meu lugar? Não; quisera eu^&#42;1^ que todo o povo de Jeová fosse profeta, porque Jeová poria seu espírito^&#42;2^ sobre eles!”

[NOTE]
====
. Lit.: “E quem dará?”
. “Seu espírito.” Hebr.: ru·hhóh; gr.: pneú·ma; lat.: spí·ri·tum.
====

[[v4-11-30]]

^<<v4-11-30,30>>^ Mais tarde, Moisés se retirou para o acampamento, ele e os anciãos de Israel.

[[v4-11-31]]

^<<v4-11-31,31>>^ E levantou-se um vento^&#42;1^ da parte de Jeová e começou a impelir codornizes desde o mar e a deixá-las cair sobre o acampamento, cerca de um dia de jornada deste lado e cerca de um dia de jornada daquele lado, em volta do acampamento, e por cerca de dois côvados acima da superfície da terra.^&#42;2^

[NOTE]
====
. “E . . . um vento.” Hebr.: werú·ahh; gr.: pneú·ma; lat.: vén·tus. Veja v. 29 n.: “espírito”; Gên 8:1 n.
. “Todo em volta do acampamento, a cerca de dois côvados da terra”, LXX; Vg: “todo em volta do acampamento, e voavam no ar numa altitude de dois côvados acima da terra”. Um côvado equivalia a 44,5 cm.
====

[[v4-11-32]]

^<<v4-11-32,32>>^ O povo levantou-se então todo aquele dia e toda a noite, e todo o dia seguinte, e foram recolher as codornizes. Quem recolhia menos ajuntou dez ômeres,^&#42;1^ e estendiam-nas para si por toda a parte,^&#42;2^ em volta do acampamento.

[NOTE]
====
. Um ômer equivalia a 220 l.
. “Haviam aquecido para si fornos”, LXXThºmsºn; Vg: “haviam-nos secado”.
====

[[v4-11-33]]

^<<v4-11-33,33>>^ A carne estava ainda entre os seus dentes, antes que pudesse ser mastigada, quando se acendeu a ira de Jeová contra o povo e Jeová começou a atingir o povo com uma matança muito grande.

[[v4-11-34]]

^<<v4-11-34,34>>^ Aquele lugar veio a ser chamado pelo nome de Quibrote-Ataavá,^&#42;1^ porque ali enterraram o povo que mostrou ter almejo egoísta.

[NOTE]
====
. Significando “Sepulturas do Almejo”.
====

[[v4-11-35]]

^<<v4-11-35,35>>^ De Quibrote-Ataavá o povo partiu para Hazerote, e ficaram em Hazerote.

'''

xref:004-numeros/004-numeros-010.adoc#v4-10-0[&#60; Capítulo Anterior] | <<v4-11-0,Topo>> | xref:004-numeros/004-numeros-012.adoc#v4-12-0[Próximo Capítulo &#62;]