include::./index.adoc[]

[[v4-30-0]]
=== Números, 30
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v4-30-1]]

^<<v4-30-1,1>>^ Moisés falou então aos cabeças das tribos dos filhos de Israel, dizendo: “Esta é a palavra que Jeová ordenou:

[[v4-30-2]]

^<<v4-30-2,2>>^ Caso um homem faça um voto a Jeová ou faça um juramento para impor à sua alma um voto de abstinência, não deve violar a sua palavra. Deve fazer segundo tudo o que saiu da sua boca.

[[v4-30-3]]

^<<v4-30-3,3>>^ “E caso uma mulher faça um voto a Jeová ou ela imponha a si mesma um voto de abstinência na casa de seu pai, na sua mocidade,^&#42;1^

[NOTE]
====
. Ou “enquanto ainda não estava prometida em casamento”.
====

[[v4-30-4]]

^<<v4-30-4,4>>^ e seu pai realmente ouvir seu voto ou seu voto de abstinência que impôs à sua alma, e seu pai se mantiver calado para com ela, então terão de ficar de pé todos os votos dela e ficará de pé todo voto de abstinência que ela impôs à sua alma.

[[v4-30-5]]

^<<v4-30-5,5>>^ Mas, se o seu pai lhe proibiu [isso] no dia em que ouviu todos os seus votos ou seus votos de abstinência que ela impôs à sua alma, [então] não ficará de pé, mas Jeová lhe perdoará, porque seu pai lhe proibiu [isso].

[[v4-30-6]]

^<<v4-30-6,6>>^ “No entanto, se é que ela pertence a um esposo e tem sobre si seu voto ou a promessa irrefletida dos seus lábios, que impôs à sua alma,

[[v4-30-7]]

^<<v4-30-7,7>>^ e seu esposo realmente o ouvir e se mantiver calado para com ela no dia em que o ouve,^&#42;1^ então terão de ficar de pé os seus votos, ou ficarão de pé seus votos de abstinência que ela impôs à sua alma.

[NOTE]
====
. “E se mantiver calado para com ela no dia em que o ouve”, para concordar com LXX; M tem: “no dia de ele o ouvir”, antes da conjunção “e”.
====

[[v4-30-8]]

^<<v4-30-8,8>>^ Mas, se o seu esposo lhe proibir [isso] no dia em que o ouve, então anulou o voto que havia sobre ela ou a promessa irrefletida dos seus lábios, que ela impôs à sua alma, e Jeová lhe perdoará.

[[v4-30-9]]

^<<v4-30-9,9>>^ “No caso do voto duma viúva ou duma mulher divorciada, tudo o que ela impôs à sua alma ficará de pé contra ela.

[[v4-30-10]]

^<<v4-30-10,10>>^ “No entanto, se foi na casa de seu esposo que ela fez um voto ou impôs à sua alma um voto de abstinência por meio dum juramento,

[[v4-30-11]]

^<<v4-30-11,11>>^ e seu esposo o ouviu e se manteve calado para com ela, ele não lhe proibiu [isso];^&#42;1^ e terão de ficar de pé todos os seus votos ou ficará de pé qualquer voto de abstinência que ela impôs à sua alma.

[NOTE]
====
. “Ele não lhe proibiu”, M; LXX: “e ele não lhe proibiu”.
====

[[v4-30-12]]

^<<v4-30-12,12>>^ Mas, se o seu esposo os tiver totalmente anulado no dia em que ouviu qualquer expressão dos lábios dela como votos seus ou como um voto de abstinência de sua alma, não ficarão de pé. Seu esposo os anulou e Jeová lhe perdoará.

[[v4-30-13]]

^<<v4-30-13,13>>^ Seu esposo deve efetivar ou seu esposo deve anular qualquer voto ou qualquer juramento dum voto de abstinência para atribular a alma.

[[v4-30-14]]

^<<v4-30-14,14>>^ Mas, se o seu esposo se mantiver absolutamente calado para com ela, de dia a dia, então efetivou todos os votos dela e todos os seus votos de abstinência que há sobre ela. Efetivou-os porque ficou calado para com ela no dia em que os ouviu.

[[v4-30-15]]

^<<v4-30-15,15>>^ E se os anular totalmente depois de ouvi-los, realmente leva também o erro dela.^&#42;1^

[NOTE]
====
. “Dela”, M; SamLXX: “dele”.
====

[[v4-30-16]]

^<<v4-30-16,16>>^ “Estes são os regulamentos que Jeová ordenou a Moisés entre o esposo e sua esposa, entre o pai e sua filha na mocidade dela, na casa de seu pai.”

'''

xref:004-numeros/004-numeros-029.adoc#v4-29-0[&#60; Capítulo Anterior] | <<v4-30-0,Topo>> | xref:004-numeros/004-numeros-031.adoc#v4-31-0[Próximo Capítulo &#62;]