include::./index.adoc[]

[[v4-3-0]]
=== Números, 3
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v4-3-1]]

^<<v4-3-1,1>>^ Ora, estas eram as gerações^&#42;1^ de Arão e de Moisés no dia em que Jeová falou com Moisés no monte Sinai.

[NOTE]
====
. Ou “acontecimentos; história”. Veja Gên 2:4 n.: “história”.
====

[[v4-3-2]]

^<<v4-3-2,2>>^ E estes eram os nomes dos filhos de Arão: o primogênito Nadabe e Abiú, Eleazar e Itamar.

[[v4-3-3]]

^<<v4-3-3,3>>^ Estes eram os nomes dos filhos de Arão, os sacerdotes ungidos cujas mãos tinham sido enchidas de poder para atuarem como sacerdotes.

[[v4-3-4]]

^<<v4-3-4,4>>^ No entanto, Nadabe e Abiú morreram diante de Jeová quando ofereceram fogo ilegítimo perante Jeová no ermo de Sinai; e não vieram a ter filhos. Mas Eleazar e Itamar continuaram a atuar como sacerdotes junto com Arão, seu pai.

[[v4-3-5]]

^<<v4-3-5,5>>^ E Jeová passou a falar a Moisés, dizendo:

[[v4-3-6]]

^<<v4-3-6,6>>^ “Faze chegar a tribo de Levi e tens de fazê-los ficar de pé diante de Arão, o sacerdote, e eles têm de ministrar-lhe.

[[v4-3-7]]

^<<v4-3-7,7>>^ E têm de cuidar da sua obrigação para com ele e da sua obrigação para com toda a assembléia diante da tenda de reunião ao se desincumbirem do serviço do tabernáculo.

[[v4-3-8]]

^<<v4-3-8,8>>^ E têm de cuidar de todos os utensílios da tenda de reunião, sim, da obrigação dos filhos de Israel ao se desincumbirem do serviço do tabernáculo.

[[v4-3-9]]

^<<v4-3-9,9>>^ E os levitas tens de dar a Arão e a seus filhos. São os dados,^&#42;1^ que foram dados a ele dentre os filhos de Israel.

[NOTE]
====
. “Dados.” Hebr.: nethu·ním, relacionado com o título “netineus”. Veja Esd 2:43.
====

[[v4-3-10]]

^<<v4-3-10,10>>^ E deves encarregar Arão e seus filhos, e eles têm de cuidar do seu sacerdócio; e qualquer estranho^&#42;1^ que se chegar deve ser morto.”

[NOTE]
====
. Isto é, qualquer não-aronita.
====

[[v4-3-11]]

^<<v4-3-11,11>>^ E Jeová continuou a falar a Moisés, dizendo:

[[v4-3-12]]

^<<v4-3-12,12>>^ “Quanto a mim, eis que deveras tomo os levitas dentre os filhos de Israel em lugar de todos os primogênitos dos filhos de Israel, que abrem a madre; e os levitas têm de tornar-se meus.

[[v4-3-13]]

^<<v4-3-13,13>>^ Pois todo primogênito é meu. No dia em que golpeei todo primogênito na terra do Egito santifiquei para mim todo primogênito em Israel, desde o homem até o animal. Devem tornar-se meus. Eu sou Jeová.”

[[v4-3-14]]

^<<v4-3-14,14>>^ E Jeová falou mais a Moisés no ermo de Sinai, dizendo:

[[v4-3-15]]

^<<v4-3-15,15>>^ “Registra os filhos de Levi segundo a casa de seus pais, pelas suas famílias. Deves registrar todo macho da idade de um mês para cima.”

[[v4-3-16]]

^<<v4-3-16,16>>^ E Moisés começou a registrá-los segundo a ordem de Jeová, assim como se lhe ordenara.

[[v4-3-17]]

^<<v4-3-17,17>>^ E estes vieram a ser os filhos de Levi pelos seus nomes: Gérson e Coate, e Merari.

[[v4-3-18]]

^<<v4-3-18,18>>^ Ora, estes eram os nomes dos filhos de Gérson, pelas suas famílias: Libni e Simei.

[[v4-3-19]]

^<<v4-3-19,19>>^ E os filhos de Coate, pelas suas famílias, eram Anrão e Izar, Hébron e Uziel.

[[v4-3-20]]

^<<v4-3-20,20>>^ E os filhos de Merari, pelas suas famílias, eram Mali e Musi.
Estas eram as famílias dos levitas segundo a casa de seus pais.

[[v4-3-21]]

^<<v4-3-21,21>>^ De Gérson havia a família dos libnitas e a família dos simeítas. Estas eram as famílias dos gersonitas.

[[v4-3-22]]

^<<v4-3-22,22>>^ Seus registrados eram por número de todos os machos da idade de um mês para cima. Seus registrados eram sete mil e quinhentos.

[[v4-3-23]]

^<<v4-3-23,23>>^ As famílias dos gersonitas ficavam atrás do tabernáculo. Acampavam-se ao oeste.

[[v4-3-24]]

^<<v4-3-24,24>>^ E o maioral da casa paterna dos gersonitas era Eliasafe, filho de Lael.

[[v4-3-25]]

^<<v4-3-25,25>>^ E a obrigação dos filhos de Gérson na tenda de reunião era o tabernáculo e a tenda, sua cobertura e o reposteiro da entrada da tenda de reunião,

[[v4-3-26]]

^<<v4-3-26,26>>^ e os cortinados do pátio e o reposteiro da entrada do pátio, que há em volta do tabernáculo e do altar, e seus cordões de tenda, para todo o seu serviço.

[[v4-3-27]]

^<<v4-3-27,27>>^ E de Coate havia a família dos anramitas, e a família dos izaritas, e a família dos hebronitas, e a família dos uzielitas. Estas eram as famílias dos coatitas.

[[v4-3-28]]

^<<v4-3-28,28>>^ Entre o número de todos os machos da idade de um mês para cima havia oito mil e seiscentos^&#42;1^ cuidando da obrigação para com o lugar santo.

[NOTE]
====
. “Seiscentos”, MSamSyVg; alguns mss. da LXX: “trezentos”, os quais, acrescentados às somas nos vv. 22 e 34, totalizam 22.000, conforme dado no v. 39.
====

[[v4-3-29]]

^<<v4-3-29,29>>^ As famílias dos filhos de Coate estavam acampadas ao lado meridional do tabernáculo.

[[v4-3-30]]

^<<v4-3-30,30>>^ E o maioral da casa paterna das famílias dos coatitas era Elizafã, filho de Uziel.

[[v4-3-31]]

^<<v4-3-31,31>>^ E sua obrigação era a Arca e a mesa, e o candelabro, e os altares, e os utensílios do lugar santo com que ministravam, e o reposteiro, e todo o seu serviço.

[[v4-3-32]]

^<<v4-3-32,32>>^ E o maioral dos maiorais dos levitas era Eleazar, filho de Arão, o sacerdote, que tinha a supervisão sobre os que cuidavam da obrigação para com o lugar santo.

[[v4-3-33]]

^<<v4-3-33,33>>^ De Merari havia a família dos malitas e a família dos musitas. Estas eram as famílias de Merari.

[[v4-3-34]]

^<<v4-3-34,34>>^ E seus registrados pelo número de todos os machos da idade de um mês para cima eram seis mil e duzentos.

[[v4-3-35]]

^<<v4-3-35,35>>^ E o maioral da casa paterna das famílias de Merari era Zuriel, filho de Abiail. Estavam acampados ao lado setentrional do tabernáculo.

[[v4-3-36]]

^<<v4-3-36,36>>^ E a supervisão que era da obrigação dos filhos de Merari era sobre as armações de painel do tabernáculo e suas trancas, e suas colunas, e seus pedestais de encaixe, e todos os seus utensílios, e todo o seu serviço,

[[v4-3-37]]

^<<v4-3-37,37>>^ e as colunas do pátio ao redor, e seus pedestais de encaixe, e suas estacas de tenda, e seus cordões de tenda.

[[v4-3-38]]

^<<v4-3-38,38>>^ E os que se acampavam diante do tabernáculo para o leste, diante da tenda de reunião, para o nascente, eram Moisés e Arão, e seus filhos, os que cuidavam da obrigação para com o santuário, como obrigação dos filhos de Israel. E qualquer estranho^&#42;1^ que se chegava era morto.

[NOTE]
====
. Isto é, um não-levita. Veja 1:51.
====

[[v4-3-39]]

^<<v4-3-39,39>>^ Todos os registrados dos levitas, que Moisés e Arão^&#42;1^ registraram por ordem de Jeová, segundo as suas famílias, todos os machos da idade de um mês para cima, eram vinte e dois mil.

[NOTE]
====
. “E Arão”, MLXXVg. No M, as palavras traduzidas assim foram marcadas com pontos extraordinários pelos soferins. Ordenou-se a Moisés fazer o censo, mas, visto que Arão participava nisso com Moisés, alguns antigos copistas inseriram “e Arão” no texto. Mais tarde, os escribas colocaram pontinhos sobre as palavras, em vez de tirá-las. SamSy e 11 mss. hebr. as omitem. Veja Ap. 2A.
====

[[v4-3-40]]

^<<v4-3-40,40>>^ Jeová disse então a Moisés: “Registra todos os machos primogênitos dos filhos de Israel, da idade de um mês para cima, e toma o número dos seus nomes.

[[v4-3-41]]

^<<v4-3-41,41>>^ E os levitas tens de tomar para mim — eu sou Jeová — em lugar de todos os primogênitos entre os filhos de Israel, e os animais domésticos dos levitas em lugar de todos os primogênitos entre os animais domésticos dos filhos de Israel.”

[[v4-3-42]]

^<<v4-3-42,42>>^ E Moisés, assim como Jeová lhe mandara, passou a registrar todos os primogênitos entre os filhos de Israel.

[[v4-3-43]]

^<<v4-3-43,43>>^ E todos os machos primogênitos, pelo número dos nomes, da idade de um mês para cima, dos seus registrados, vieram a ser vinte e dois mil duzentos e setenta e três.

[[v4-3-44]]

^<<v4-3-44,44>>^ E Jeová continuou a falar a Moisés, dizendo:

[[v4-3-45]]

^<<v4-3-45,45>>^ “Toma os levitas em lugar de todos os primogênitos entre os filhos de Israel e os animais domésticos dos levitas em lugar dos seus animais domésticos; e os levitas têm de tornar-se meus. Eu sou Jeová.

[[v4-3-46]]

^<<v4-3-46,46>>^ E como preço de resgate dos duzentos e setenta e três dos primogênitos dos filhos de Israel que excedem os levitas

[[v4-3-47]]

^<<v4-3-47,47>>^ tens de tomar cinco siclos por cabeça. Deves tomá-lo em siclos do lugar santo. Um siclo são vinte geras.

[[v4-3-48]]

^<<v4-3-48,48>>^ E tens de dar o dinheiro a Arão e a seus filhos como preço de resgate dos excedentes deles.”

[[v4-3-49]]

^<<v4-3-49,49>>^ Assim, Moisés tomou o dinheiro do preço de redenção daqueles que excediam o preço de resgate dos levitas.

[[v4-3-50]]

^<<v4-3-50,50>>^ Tomou o dinheiro dos primogênitos dos filhos de Israel, mil trezentos e sessenta e cinco siclos,^&#42;1^ em siclos do lugar santo.

[NOTE]
====
. “Siclos”, TJ,OLXXSyVg; MSam omitem isso.
====

[[v4-3-51]]

^<<v4-3-51,51>>^ Moisés deu então o dinheiro do preço de resgate a Arão e a seus filhos por ordem de Jeová, assim como Jeová mandara a Moisés.

'''

xref:004-numeros/004-numeros-002.adoc#v4-2-0[&#60; Capítulo Anterior] | <<v4-3-0,Topo>> | xref:004-numeros/004-numeros-004.adoc#v4-4-0[Próximo Capítulo &#62;]