include::./index.adoc[]

[[v4-22-0]]
=== Números, 22
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v4-22-1]]

^<<v4-22-1,1>>^ Os filhos de Israel partiram então e acamparam-se nas planícies desérticas de Moabe, defronte de Jericó, do outro lado do Jordão.

[[v4-22-2]]

^<<v4-22-2,2>>^ E Balaque, filho de Zipor, chegou a ver tudo o que Israel tinha feito aos amorreus.

[[v4-22-3]]

^<<v4-22-3,3>>^ E Moabe ficou muito amedrontado por causa do povo, porque eram muitos; e Moabe começou a ter um pavor mórbido dos filhos de Israel.

[[v4-22-4]]

^<<v4-22-4,4>>^ E Moabe passou a dizer aos anciãos de Midiã: “Esta^&#42;1^ congregação lamberá agora tudo ao redor de nós assim como o touro lambe a erva verde do campo.”
E Balaque, filho de Zipor, naquele tempo específico, era rei de Moabe.

[NOTE]
====
. “Esta”, SamLXXSyVg; M: “a”.
====

[[v4-22-5]]

^<<v4-22-5,5>>^ Enviou então mensageiros a Balaão, filho de Beor, em Petor, que está junto ao Rio^&#42;1^ da terra dos filhos do seu povo, a fim de chamá-lo, dizendo: “Eis que um povo saiu do Egito. Eis que cobriram a terra até onde se pode ver^&#42;2^ e estão morando bem defronte de mim.

[NOTE]
====
. “Ao Rio”, evidentemente o Eufrates.
. Lit.: “cobriram o olho da terra”.
====

[[v4-22-6]]

^<<v4-22-6,6>>^ E agora vem deveras, por favor; amaldiçoa-me deveras este povo, pois são mais fortes do que eu. Talvez eu possa golpeá-los e expulsá-los do país; porque bem sei que aquele a quem abençoas é abençoado e aquele a quem amaldiçoas é amaldiçoado.”

[[v4-22-7]]

^<<v4-22-7,7>>^ Portanto, os anciãos de Moabe e os anciãos de Midiã viajaram com os honorários pela adivinhação nas suas mãos e foram ter com Balaão, e falaram-lhe as palavras de Balaque.

[[v4-22-8]]

^<<v4-22-8,8>>^ A isto ele lhes disse: “Pousai esta noite aqui e eu certamente vos trarei de volta informação assim como Jeová me falar.” Concordemente, os príncipes de Moabe ficaram com Balaão.

[[v4-22-9]]

^<<v4-22-9,9>>^ Deus veio então a Balaão e disse: “Quem são estes homens contigo?”

[[v4-22-10]]

^<<v4-22-10,10>>^ De modo que Balaão disse ao [verdadeiro] Deus: “Balaque, filho de Zipor, rei de Moabe, mandou dizer-me:^&#42;1^

[NOTE]
====
. “Dizer-me”, LXXSyVg.
====

[[v4-22-11]]

^<<v4-22-11,11>>^ ‘Eis o povo que está saindo do Egito, e estão cobrindo a terra até onde o olho pode ver. Agora, vem deveras, maldize-os deveras para mim. Talvez eu possa lutar contra eles e eu realmente os expulse.’”

[[v4-22-12]]

^<<v4-22-12,12>>^ Mas Deus disse a Balaão: “Não deves ir com eles. Não deves amaldiçoar o povo, pois são benditos.”

[[v4-22-13]]

^<<v4-22-13,13>>^ Após isso, Balaão levantou-se de manhã e disse aos príncipes de Balaque: “Ide para a vossa terra, porque Jeová se negou a deixar-me ir convosco.”

[[v4-22-14]]

^<<v4-22-14,14>>^ Os príncipes de Moabe levantaram-se então e foram ter com Balaque, e disseram: “Balaão negou-se a vir conosco.”

[[v4-22-15]]

^<<v4-22-15,15>>^ No entanto, Balaque enviou novamente outros príncipes em maior número e mais honrados do que os anteriores.

[[v4-22-16]]

^<<v4-22-16,16>>^ Eles, por sua vez, foram ter com Balaão e disseram-lhe: “Assim disse Balaque, filho de Zipor: ‘Por favor, não te detenhas de vir a mim.

[[v4-22-17]]

^<<v4-22-17,17>>^ Pois, sem falta te honrarei grandemente e farei tudo o que me disseres. Portanto, vem deveras, por favor. Maldize-me deveras este povo.’”

[[v4-22-18]]

^<<v4-22-18,18>>^ Mas Balaão respondeu e disse aos servos de Balaque: “Se Balaque me desse a sua casa cheia de prata e de ouro, eu não poderia infringir a ordem de Jeová, meu Deus, para fazer algo pequeno ou grande.

[[v4-22-19]]

^<<v4-22-19,19>>^ E agora, por favor, ficai também vós aqui esta noite, para que eu saiba que mais Jeová falará comigo.”

[[v4-22-20]]

^<<v4-22-20,20>>^ Deus^&#42;1^ veio então a Balaão de noite e disse-lhe: “Se os homens vieram para te chamar, levanta-te, vai com eles. Mas, somente a palavra que eu te falar é que podes falar.”

[NOTE]
====
. “Deus”, MLXXSyVg; Sam: “o anjo de Deus”.
====

[[v4-22-21]]

^<<v4-22-21,21>>^ Após isso, Balaão levantou-se de manhã e selou sua jumenta, e foi com os príncipes de Moabe.

[[v4-22-22]]

^<<v4-22-22,22>>^ E começou a acender-se a ira de Deus,^&#42;1^ porque ele ia; e o anjo de Jeová foi postar-se na estrada para se lhe opor.^&#42;2^ E ele estava montado em sua jumenta, e havia com ele dois ajudantes^&#42;3^ seus.

[NOTE]
====
. “Deus”, MLXXSyVg; Sam e um ms. hebr.: “Jeová”.
. Lit.: “na estrada como opositor dele”.
. Ou “meninos; moços”.
====

[[v4-22-23]]

^<<v4-22-23,23>>^ E a jumenta pôde ver o anjo de Jeová parado na estrada, tendo sua espada desembainhada na mão; e a jumenta procurou desviar-se da estrada para entrar no campo, mas Balaão começou a espancar a jumenta para fazê-la voltar à estrada.

[[v4-22-24]]

^<<v4-22-24,24>>^ E o anjo de Jeová ficou parado no caminho estreito entre os vinhedos, havendo um muro de pedras deste lado e um muro de pedras daquele lado.

[[v4-22-25]]

^<<v4-22-25,25>>^ E a jumenta via o anjo de Jeová, e ela começou a apertar-se contra o muro e assim a apertar o pé de Balaão contra o muro; e ele passou a espancá-la ainda mais.

[[v4-22-26]]

^<<v4-22-26,26>>^ O anjo de Jeová passou então novamente e ficou de pé num lugar estreito, onde não havia meio de se desviar nem para a direita nem para a esquerda.

[[v4-22-27]]

^<<v4-22-27,27>>^ Quando a jumenta chegou a ver o anjo de Jeová, então se deitou debaixo de Balaão; de modo que se acendeu a ira de Balaão e ele foi espancar a jumenta com seu bordão.

[[v4-22-28]]

^<<v4-22-28,28>>^ Por fim, Jeová abriu a boca da jumenta e ela disse a Balaão: “Que te fiz para me teres espancado estas três vezes?”

[[v4-22-29]]

^<<v4-22-29,29>>^ Então disse Balaão à jumenta: “Foi porque me trataste cruelmente. Se tão-somente houvesse uma espada na minha mão, eu já te teria matado!”

[[v4-22-30]]

^<<v4-22-30,30>>^ A jumenta disse então a Balaão: “Não sou a tua jumenta em que montaste toda a tua vida até o dia de hoje? Procedi alguma vez deste modo?” A isso ele disse: “Não!”

[[v4-22-31]]

^<<v4-22-31,31>>^ E Jeová passou a desvendar os olhos de Balaão, de modo que viu o anjo de Jeová parado na estrada, tendo sua espada desembainhada na mão. Inclinou-se imediatamente e prostrou-se com o seu rosto [em terra].

[[v4-22-32]]

^<<v4-22-32,32>>^ O anjo de Jeová disse-lhe então: “Por que espancaste tua jumenta estas três vezes? Eis que eu é que saí para fazer oposição, porque teu caminho tem sido temerariamente^&#42;1^ contrário à minha vontade.

[NOTE]
====
. “Teu caminho não é elegante (encantador; bom)”, LXX; Vg: “teu caminho é perverso”.
====

[[v4-22-33]]

^<<v4-22-33,33>>^ E a jumenta pôde ver-me e procurou desviar-se de mim estas três vezes. Suponhamos que ela não se tivesse^&#42;1^ desviado de mim! Pois agora eu já te teria matado, mas a ela eu teria preservado viva.”

[NOTE]
====
. “A menos que ela se tivesse”, LXX; Vg: “A menos que a jumenta se tivesse”; M: “Talvez ela se tenha.”
====

[[v4-22-34]]

^<<v4-22-34,34>>^ Em vista disso, Balaão disse ao anjo de Jeová: “Pequei, porque eu não sabia que estavas parado na estrada ao meu encontro. E agora, se isso é mau aos teus olhos, deixa-me voltar.”

[[v4-22-35]]

^<<v4-22-35,35>>^ Mas o anjo de Jeová disse a Balaão: “Vai com os homens; e nada a não ser a palavra que eu te falar é a que podes falar.” E Balaão seguiu com os príncipes de Balaque.

[[v4-22-36]]

^<<v4-22-36,36>>^ Quando Balaque chegou a ouvir que Balaão havia chegado, saiu imediatamente ao seu encontro na cidade de Moabe, que se acha na margem do Árnon, que está na extremidade do território.

[[v4-22-37]]

^<<v4-22-37,37>>^ Balaque disse então a Balaão: “Não é que te mandei chamar? Por que não vieste a mim? Não sou real e verdadeiramente capaz de te honrar?”

[[v4-22-38]]

^<<v4-22-38,38>>^ Então Balaão disse a Balaque: “Eis que agora vim ter contigo. Acaso serei capaz de falar alguma coisa? Falarei a palavra que Deus puser na minha boca.”

[[v4-22-39]]

^<<v4-22-39,39>>^ Portanto, Balaão foi com Balaque e eles chegaram a Quiriate-Huzote.

[[v4-22-40]]

^<<v4-22-40,40>>^ E Balaque passou a oferecer em sacrifício gado vacum e ovelhas, e enviou alguns a Balaão e aos príncipes que estavam com ele.

[[v4-22-41]]

^<<v4-22-41,41>>^ E sucedeu, de manhã, que Balaque foi tomar Balaão e foi levá-lo para cima a Bamote-Baal,^&#42;1^ para que dali visse^&#42;2^ o povo inteiro.

[NOTE]
====
. “Bamote-Baal”, significando “Altos de Baal”. Os baalins cananeus usualmente tinham nomes que indicavam uma ligação com determinadas localidades. Esses nomes depois vieram a ser dados às próprias localidades, tais como Baal-Hermom, Baal-Hazor, Baal-Zefom.
. Ou “e chegou a ver”.
====

'''

xref:004-numeros/004-numeros-021.adoc#v4-21-0[&#60; Capítulo Anterior] | <<v4-22-0,Topo>> | xref:004-numeros/004-numeros-023.adoc#v4-23-0[Próximo Capítulo &#62;]