include::./index.adoc[]

[[v4-18-0]]
=== Números, 18
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v4-18-1]]

^<<v4-18-1,1>>^ E Jeová passou a dizer a Arão: “Tu e teus filhos, e a casa de teu pai contigo, responderão pelo erro contra o santuário, e tu e teus filhos contigo responderão pelo erro contra o vosso sacerdócio.

[[v4-18-2]]

^<<v4-18-2,2>>^ E faze chegar contigo também teus irmãos da tribo de Levi, o clã de teu pai, para que sejam agregados a ti e te ministrem, tanto a ti como a teus filhos contigo, diante da tenda do Testemunho.

[[v4-18-3]]

^<<v4-18-3,3>>^ E eles têm de cuidar da sua obrigação para contigo e da sua obrigação para com a tenda inteira. Somente não se devem chegar aos utensílios do lugar santo e ao altar, para que não morram, nem eles nem vós.

[[v4-18-4]]

^<<v4-18-4,4>>^ E têm de ser agregados a ti e têm de cuidar da sua obrigação para com a tenda de reunião, referente a todo o serviço da tenda, e nenhum estranho se pode chegar a vós.

[[v4-18-5]]

^<<v4-18-5,5>>^ E tendes de cuidar da vossa obrigação para com o lugar santo e da vossa obrigação para com o altar, para que não haja mais indignação contra os filhos de Israel.

[[v4-18-6]]

^<<v4-18-6,6>>^ E eu, eis que tomei os vossos irmãos, os levitas, dentre os filhos de Israel como dádiva para vós, como os que são dados a Jeová para executarem o serviço da tenda de reunião.

[[v4-18-7]]

^<<v4-18-7,7>>^ E tu e teus filhos contigo deveis resguardar vosso sacerdócio quanto a toda incumbência do altar e quanto ao que há por dentro da cortina; e tendes de prestar serviço. Darei vosso sacerdócio como serviço de dádiva, e o estranho que se chegar deve ser morto.”

[[v4-18-8]]

^<<v4-18-8,8>>^ E Jeová falou mais a Arão: “Quanto a mim, eis que te tenho dado a custódia das contribuições feitas a mim. De todas as coisas sagradas dos filhos de Israel tenho-as dado a ti e a teus filhos como quinhão, como porção concedida, por tempo indefinido.

[[v4-18-9]]

^<<v4-18-9,9>>^ Isto é o que se deve tornar teu dentre as coisas santíssimas, dentre a oferta feita por fogo: toda oferta dele junto com toda sua oferta de cereais e toda sua oferta pelo pecado, e toda sua oferta pela culpa, que me restituírem. É algo santíssimo para ti e para os teus filhos.

[[v4-18-10]]

^<<v4-18-10,10>>^ Deves comê-lo num lugar santíssimo. Todo macho deve comê-lo. Deve tornar-se para ti algo sagrado.

[[v4-18-11]]

^<<v4-18-11,11>>^ E a ti pertence o seguinte: a contribuição da sua dádiva junto com todas as ofertas movidas dos filhos de Israel. Eu as tenho dado a ti e a teus filhos, e a tuas filhas contigo, como porção concedida, por tempo indefinido. Todo aquele que for limpo na tua casa pode comê-la.

[[v4-18-12]]

^<<v4-18-12,12>>^ “Todo o melhor^&#42;1^ do azeite e todo o melhor do vinho novo e dos cereais, as suas primícias que darão a Jeová, a ti as tenho dado.

[NOTE]
====
. Lit.: “gordura”.
====

[[v4-18-13]]

^<<v4-18-13,13>>^ Os primeiros frutos maduros de tudo o que há na terra deles, que trarão a Jeová, tornar-se-ão teus. Todo aquele que for limpo na tua casa pode comê-los.

[[v4-18-14]]

^<<v4-18-14,14>>^ “Toda coisa devotada^&#42;1^ em Israel deve tornar-se tua.

[NOTE]
====
. Isto é, tudo o que foi tornado sagrado para Deus por meio duma proscrição.
====

[[v4-18-15]]

^<<v4-18-15,15>>^ “Tudo o que abre a madre, de toda sorte de carne, que apresentarem a Jeová, de homem e de animal, deve tornar-se teu. No entanto, sem falta deves remir o primogênito do gênero humano; e deves remir o primogênito do animal impuro.

[[v4-18-16]]

^<<v4-18-16,16>>^ E deves remi-lo da idade de um mês para cima com um preço de redenção, segundo o valor calculado, cinco siclos de prata segundo o siclo do lugar santo. É de vinte geras.

[[v4-18-17]]

^<<v4-18-17,17>>^ Somente não deves remir o touro primogênito, ou o cordeiro primogênito, ou o caprídeo primogênito. São algo sagrado. Deves aspergir o sangue deles sobre o altar e deves fazer fumegar a gordura deles como oferta feita por fogo, de cheiro repousante para Jeová.

[[v4-18-18]]

^<<v4-18-18,18>>^ E sua carne deve tornar-se tua. Igual ao peito da oferta movida e igual à perna direita, deve tornar-se tua.

[[v4-18-19]]

^<<v4-18-19,19>>^ Toda a contribuição sagrada que os filhos de Israel contribuirão a Jeová tenho dado a ti e a teus filhos, e a tuas filhas contigo, como porção concedida por tempo indefinido. É um pacto de sal por tempo indefinido diante de Jeová para ti e para tua descendência contigo.”

[[v4-18-20]]

^<<v4-18-20,20>>^ E Jeová prosseguiu, dizendo a Arão: “Não terás herança na terra deles e nenhum quinhão se tornará teu no seu meio. Eu sou teu quinhão e tua herança no meio dos filhos de Israel.

[[v4-18-21]]

^<<v4-18-21,21>>^ “E aos filhos de Levi, eis que [lhes] tenho dado por herança cada décima parte em Israel, em troca do seu serviço que executam, o serviço da tenda de reunião.

[[v4-18-22]]

^<<v4-18-22,22>>^ E os filhos de Israel não mais se devem chegar à tenda de reunião, incorrendo em pecado a ponto de morrerem.

[[v4-18-23]]

^<<v4-18-23,23>>^ E os próprios levitas têm de executar o serviço da tenda de reunião e eles é que devem responder pelo seu erro. É um estatuto por tempo indefinido nas vossas gerações, que não devem obter posse duma herança no meio dos filhos de Israel.

[[v4-18-24]]

^<<v4-18-24,24>>^ Pois, a décima parte, dos filhos de Israel, que estes contribuirão a Jeová como contribuição, eu tenho dado por herança aos levitas. É por isso que eu lhes disse: ‘Não devem obter posse duma herança no meio dos filhos de Israel.’”

[[v4-18-25]]

^<<v4-18-25,25>>^ Jeová falou então a Moisés, dizendo:

[[v4-18-26]]

^<<v4-18-26,26>>^ “E deves falar aos levitas, e tens de dizer-lhes: ‘Recebereis dos filhos de Israel a décima parte que vos dei da parte deles como vossa herança e tereis de contribuir dela a décima parte da décima parte como contribuição a Jeová.

[[v4-18-27]]

^<<v4-18-27,27>>^ E ela terá de ser atribuída a vós como vossa contribuição, igual aos cereais da eira e igual ao pleno produto do lagar de vinho ou de azeite.

[[v4-18-28]]

^<<v4-18-28,28>>^ Deste modo vós mesmos também fareis uma contribuição a Jeová, de todas as vossas décimas partes que recebereis dos filhos de Israel, e delas tereis de dar a Arão, o sacerdote, a contribuição a Jeová.

[[v4-18-29]]

^<<v4-18-29,29>>^ De todas as dádivas [feitas] a vós fareis toda sorte de contribuição a Jeová, do melhor dela, como algo sagrado da parte delas.’

[[v4-18-30]]

^<<v4-18-30,30>>^ “E tens de dizer-lhes: ‘Quando contribuirdes o melhor delas, então será certamente atribuído aos levitas como produtos da eira e como produtos do lagar de vinho ou de azeite.

[[v4-18-31]]

^<<v4-18-31,31>>^ E tereis de comê-lo em todo lugar, vós e os da vossa casa, porque é vosso salário pelo vosso serviço na tenda de reunião.

[[v4-18-32]]

^<<v4-18-32,32>>^ E não deveis incorrer em pecado por ele ao contribuirdes o melhor delas e não deveis profanar as coisas sagradas dos filhos de Israel, para que não morrais.’”

'''

xref:004-numeros/004-numeros-017.adoc#v4-17-0[&#60; Capítulo Anterior] | <<v4-18-0,Topo>> | xref:004-numeros/004-numeros-019.adoc#v4-19-0[Próximo Capítulo &#62;]