include::./index.adoc[]

[[v4-8-0]]
=== Números, 8
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v4-8-1]]

^<<v4-8-1,1>>^ E Jeová passou a falar a Moisés, dizendo:

[[v4-8-2]]

^<<v4-8-2,2>>^ “Fala a Arão, e tens de dizer-lhe: ‘Sempre que acenderes as lâmpadas, as sete lâmpadas devem iluminar a área na frente do candelabro.’”

[[v4-8-3]]

^<<v4-8-3,3>>^ E Arão começou a fazer assim. Acendeu-lhe as lâmpadas para a área na frente do candelabro, assim como Jeová mandara a Moisés.

[[v4-8-4]]

^<<v4-8-4,4>>^ Ora, a seguinte era a feitura do candelabro: Era obra de ouro batida ao martelo. Até os seus lados e até as suas flores era obra batida ao martelo. Fizera o candelabro segundo a visão que Jeová mostrara a Moisés.

[[v4-8-5]]

^<<v4-8-5,5>>^ E Jeová falou mais a Moisés, dizendo:

[[v4-8-6]]

^<<v4-8-6,6>>^ “Toma os levitas dentre os filhos de Israel, e tens de purificá-los.

[[v4-8-7]]

^<<v4-8-7,7>>^ E isto é o que deves fazer com eles para purificá-los: Esparge sobre eles água purificadora de pecado, e eles têm de fazer passar uma navalha sobre toda a sua carne e têm de lavar suas roupas e purificar-se.

[[v4-8-8]]

^<<v4-8-8,8>>^ Então têm de tomar um novilho e sua oferta de cereais de flor de farinha umedecida com azeite, e tu tens de tomar outro novilho como oferta pelo pecado.

[[v4-8-9]]

^<<v4-8-9,9>>^ E tens de apresentar os levitas diante da tenda de reunião e congregar toda a assembléia dos filhos de Israel.

[[v4-8-10]]

^<<v4-8-10,10>>^ E tens de apresentar os levitas perante Jeová, e os filhos de Israel têm de pôr suas mãos sobre os levitas.

[[v4-8-11]]

^<<v4-8-11,11>>^ E Arão tem de fazer os levitas mover-se para lá e para cá perante Jeová como oferta movida da parte dos filhos de Israel e eles têm de servir para executar o serviço de Jeová.

[[v4-8-12]]

^<<v4-8-12,12>>^ “Então os levitas porão suas mãos sobre as cabeças dos novilhos. Após isso, faze a oferta de um [deles] como oferta pelo pecado e o outro como oferta queimada para Jeová, a fim de fazer expiação pelos levitas.

[[v4-8-13]]

^<<v4-8-13,13>>^ E tens de fazer os levitas ficar de pé diante de Arão e seus filhos, e tens de fazê-los mover-se para lá e para cá como oferta movida para Jeová.

[[v4-8-14]]

^<<v4-8-14,14>>^ E tens de separar os levitas dentre os filhos de Israel e os levitas têm de tornar-se meus.

[[v4-8-15]]

^<<v4-8-15,15>>^ E depois os levitas entrarão para servir junto à tenda de reunião. Assim tens de purificá-los e fazê-los mover-se para lá e para cá como oferta movida.

[[v4-8-16]]

^<<v4-8-16,16>>^ Pois, eles são os dados,^&#42;1^ dados a mim dentre os filhos de Israel. Terei de tomá-los para mim em lugar dos que abrem todas as madres, todos os primogênitos dos filhos de Israel.

[NOTE]
====
. “Dados.” Hebr.: nethu·ním, relacionado com o título “netineus”. Veja 1Cr 9:2.
====

[[v4-8-17]]

^<<v4-8-17,17>>^ Pois, todo primogênito dentre os filhos de Israel é meu, dentre homem e dentre animal. Santifiquei-os para mim no dia em que golpeei todo primogênito na terra do Egito.

[[v4-8-18]]

^<<v4-8-18,18>>^ E tomarei os levitas em lugar de todos os primogênitos dentre os filhos de Israel.

[[v4-8-19]]

^<<v4-8-19,19>>^ E darei os levitas como os que são dados a Arão e a seus filhos dentre os filhos de Israel para executarem o serviço dos filhos de Israel na tenda de reunião e fazerem expiação pelos filhos de Israel, para que não haja praga entre os filhos de Israel, visto que os filhos de Israel se aproximam ao lugar santo.”

[[v4-8-20]]

^<<v4-8-20,20>>^ E Moisés e Arão, e toda a assembléia dos filhos de Israel, passaram a fazer assim com os levitas. De acordo com tudo o que Jeová ordenara a Moisés com respeito aos levitas, assim lhes fizeram os filhos de Israel.

[[v4-8-21]]

^<<v4-8-21,21>>^ Portanto, os levitas purificaram-se e lavaram suas vestes, após o que Arão os fez mover-se para lá e para cá como oferta movida perante Jeová. Arão fez então uma expiação por eles, para purificá-los.

[[v4-8-22]]

^<<v4-8-22,22>>^ Só depois é que os levitas entraram para executar seu serviço na tenda de reunião diante de Arão e seus filhos. Assim como Jeová ordenara a Moisés com respeito aos levitas, assim lhes fizeram.

[[v4-8-23]]

^<<v4-8-23,23>>^ Jeová falou então a Moisés, dizendo:

[[v4-8-24]]

^<<v4-8-24,24>>^ “Isto é o que se aplica aos levitas:^&#42;1^ Da idade de vinte e cinco anos para cima ele ingressará na companhia do serviço da tenda de reunião.

[NOTE]
====
. “Esta é a lei para os levitas”, SyVg.
====

[[v4-8-25]]

^<<v4-8-25,25>>^ Mas, depois da idade de cinqüenta anos retirar-se-á da companhia de serviço e não fará mais nenhum serviço.

[[v4-8-26]]

^<<v4-8-26,26>>^ E ele terá de ministrar aos seus irmãos na tenda de reunião, cuidando da obrigação, mas não deve fazer nenhum serviço. De acordo com isso é que farás com os levitas nas suas obrigações.”

'''

xref:004-numeros/004-numeros-007.adoc#v4-7-0[&#60; Capítulo Anterior] | <<v4-8-0,Topo>> | xref:004-numeros/004-numeros-009.adoc#v4-9-0[Próximo Capítulo &#62;]