include::./index.adoc[]

[[v4-16-0]]
=== Números, 16
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v4-16-1]]

^<<v4-16-1,1>>^ E Corá, filho de Izar, filho de Coate, filho de Levi, passou a levantar-se,^&#42;1^ junto com Datã e Abirão, filhos de Eliabe, e Om, filho de Pelete, filhos de Rubem.

[NOTE]
====
. “Passou a levantar-se” e “passou a congregar” são versões propostas. Lit.: “passou a tomar”, M; LXX: “falou”.
====

[[v4-16-2]]

^<<v4-16-2,2>>^ E passaram a levantar-se diante de Moisés, eles e [mais] duzentos e cinqüenta homens dos filhos de Israel, maiorais da assembléia, convocados da reunião, homens de fama.^&#42;1^

[NOTE]
====
. Lit.: “nome”.
====

[[v4-16-3]]

^<<v4-16-3,3>>^ Congregaram-se, pois, contra Moisés e Arão, e disseram-lhes: “Já chega de vós, pois a assembléia inteira, todos eles, são santos e Jeová está no seu meio. Então, por que vos devíeis erguer acima da congregação de Jeová?”

[[v4-16-4]]

^<<v4-16-4,4>>^ Quando Moisés chegou a ouvir isso, lançou-se imediatamente com a face [por terra].

[[v4-16-5]]

^<<v4-16-5,5>>^ Falou então a Corá e a toda a sua assembléia, dizendo: “Pela manhã Jeová fará saber quem pertence a ele, e quem é santo, e quem tem de chegar-se a ele, e aquele a quem escolher se chegará a ele.

[[v4-16-6]]

^<<v4-16-6,6>>^ Fazei o seguinte: Tomai para vós porta-lumes, Corá e toda a sua assembléia,

[[v4-16-7]]

^<<v4-16-7,7>>^ e amanhã ponde fogo neles e colocai incenso sobre eles perante Jeová, e tem de dar-se que o homem que Jeová escolher é o santo. Já chega de vós, filhos de Levi!”

[[v4-16-8]]

^<<v4-16-8,8>>^ E Moisés prosseguiu, dizendo a Corá: “Escutai, por favor, filhos de Levi.

[[v4-16-9]]

^<<v4-16-9,9>>^ É para vós uma coisa tão insignificante que o Deus de Israel vos separou dentre a assembléia de Israel para vos apresentar a si mesmo, para executardes o serviço do tabernáculo de Jeová e para ficardes de pé diante da assembléia, a fim de ministrar-lhes,

[[v4-16-10]]

^<<v4-16-10,10>>^ e para te fazer chegar perto, a ti e a todos os teus irmãos, os filhos de Levi, contigo? Tendes de procurar também obter o sacerdócio?

[[v4-16-11]]

^<<v4-16-11,11>>^ Por esta razão, tu e toda a tua assembléia, que vos estais combinando, sois contra Jeová. Quanto a Arão, o que é ele que havíeis de resmungar contra ele?”

[[v4-16-12]]

^<<v4-16-12,12>>^ Mais tarde, Moisés mandou chamar Datã e Abirão, filhos de Eliabe, mas eles disseram: “Não subiremos!

[[v4-16-13]]

^<<v4-16-13,13>>^ É coisa tão insignificante que nos fizeste subir de uma terra que manava leite e mel para nos fazeres morrer no ermo, que também hás de desempenhar até o máximo o papel de príncipe sobre nós?

[[v4-16-14]]

^<<v4-16-14,14>>^ Do jeito como é, não nos trouxeste a uma terra que mana leite e mel, para nos dares uma herdade de campo e de vinhedo. Queres furar os olhos desses homens? Não subiremos!”

[[v4-16-15]]

^<<v4-16-15,15>>^ Em vista disso, Moisés ficou muito irado e disse a Jeová: “Não te vires para olhar para a sua oferta de cereais. Nem um único jumento lhes tirei, nem prejudiquei sequer a um deles.”

[[v4-16-16]]

^<<v4-16-16,16>>^ Moisés disse então a Corá: “Tu e toda a tua assembléia, comparecei perante Jeová, tu e eles, e Arão, amanhã.

[[v4-16-17]]

^<<v4-16-17,17>>^ E tomai cada um seu porta-lume, e tendes de pôr incenso sobre eles e apresentar cada um seu porta-lume perante Jeová, duzentos e cinqüenta porta-lumes, e tu e Arão, cada um seu porta-lume.”

[[v4-16-18]]

^<<v4-16-18,18>>^ Tomaram então cada um seu porta-lume e puseram fogo neles, e colocaram incenso sobre eles e ficaram de pé à entrada da tenda de reunião, junto com Moisés e Arão.

[[v4-16-19]]

^<<v4-16-19,19>>^ Quando Corá havia congregado contra eles toda a^&#42;1^ assembléia à entrada da tenda de reunião, então apareceu a glória de Jeová a toda a assembléia.

[NOTE]
====
. “A”, MSamSy; LXX: “sua”.
====

[[v4-16-20]]

^<<v4-16-20,20>>^ Jeová falou então a Moisés e a Arão, dizendo:

[[v4-16-21]]

^<<v4-16-21,21>>^ “Separai-vos do meio desta assembléia, para que eu os extermine num instante.”

[[v4-16-22]]

^<<v4-16-22,22>>^ Em vista disso, lançaram-se com as faces [por terra] e disseram: “Ó Deus,^&#42;1^ o Deus^&#42;2^ dos espíritos de toda sorte de carne, pecará um só homem e indignar-te-ás com a assembléia inteira?”

[NOTE]
====
. “Ó Deus.” Hebr.: ’El; gr.: The·ós.
. “O Deus dos.” Hebr.: ’Elo·héh, pl.; gr.: The·ós; lat.: Dé·us.
====

[[v4-16-23]]

^<<v4-16-23,23>>^ Jeová, por sua vez, falou a Moisés, dizendo:

[[v4-16-24]]

^<<v4-16-24,24>>^ “Fala à assembléia, dizendo: ‘Afastai-vos do redor dos tabernáculos^&#42;1^ de Corá, Datã e Abirão!’”

[NOTE]
====
. “Tabernáculos”, Vg; MSamSy: “tabernáculo”.
====

[[v4-16-25]]

^<<v4-16-25,25>>^ Após isso, Moisés levantou-se e foi ter com Datã e Abirão, e os anciãos de Israel foram com ele.

[[v4-16-26]]

^<<v4-16-26,26>>^ Falou então à assembléia, dizendo: “Retirai-vos, por favor, de diante das tendas destes homens iníquos e não toqueis em nada do que lhes pertence, para que não sejais arrasados em todo o seu pecado.”

[[v4-16-27]]

^<<v4-16-27,27>>^ Afastaram-se imediatamente de diante do tabernáculo de Corá, Datã e Abirão, por todos os lados, e saíram Datã e Abirão, postando-se à entrada das suas tendas, junto com suas esposas, e seus filhos, e seus pequeninos.

[[v4-16-28]]

^<<v4-16-28,28>>^ Moisés disse então: “Pelo seguinte sabereis que Jeová me enviou para realizar todos estes atos, que isso não é do meu próprio coração:

[[v4-16-29]]

^<<v4-16-29,29>>^ Se todos estes morrerem segundo a morte de toda a humanidade^&#42;1^ e se trouxer sobre eles punição com a punição de toda a humanidade, então não foi Jeová quem me enviou.

[NOTE]
====
. Ou “os terrenos; humanidade”. Hebr.: ha·’a·dhám.
====

[[v4-16-30]]

^<<v4-16-30,30>>^ Mas, se for algo criado, que Jeová criar, e o solo tiver de abrir a sua boca e tragar tanto a eles como a tudo o que lhes pertence, e tiverem de descer vivos ao Seol,^&#42;1^ então sabereis com certeza que estes homens trataram Jeová sem respeito.”

[NOTE]
====
. “Ao Seol.” Hebr.: she’ó·lah; gr.: haí·dou; lat.: in·fér·num.
====

[[v4-16-31]]

^<<v4-16-31,31>>^ E sucedeu que, assim que acabara de falar todas estas palavras, começou a partir-se o solo debaixo deles.

[[v4-16-32]]

^<<v4-16-32,32>>^ E a terra passou a abrir a sua boca e a tragar tanto a eles como os da sua casa, e todo o gênero humano que pertencia a Corá, e todos os bens.^&#42;1^

[NOTE]
====
. Ou “a propriedade”. SyVgc: “sua propriedade”; LXX: “seu gado”.
====

[[v4-16-33]]

^<<v4-16-33,33>>^ Assim, tanto eles como todos os que lhes pertenciam desceram vivos ao Seol e a terra foi cobri-los, de modo que pereceram do meio da congregação.

[[v4-16-34]]

^<<v4-16-34,34>>^ E todos os israelitas em volta deles fugiram aos seus gritos,^&#42;1^ pois começaram a dizer: “Temos medo de que a terra nos trague!”

[NOTE]
====
. Lit.: “voz”.
====

[[v4-16-35]]

^<<v4-16-35,35>>^ E saiu fogo da parte de Jeová e passou a consumir os duzentos e cinqüenta homens que ofereciam incenso.^&#42;1^

[NOTE]
====
. MLXX terminam aqui o capítulo 16.
====

[[v4-16-36]]

^<<v4-16-36,36>>^ Jeová falou então a Moisés, dizendo:

[[v4-16-37]]

^<<v4-16-37,37>>^ “Dize a Eleazar, filho de Arão, o sacerdote, que retire os porta-lumes do meio da conflagração: ‘E espalha o fogo por lá; porque são sagrados,

[[v4-16-38]]

^<<v4-16-38,38>>^ sim, os porta-lumes destes homens que pecaram contra as suas próprias almas. E têm de se fazer deles lâminas finas de metal como revestimento para o altar, porque os apresentaram perante Jeová, de modo que se tornaram sagrados; e devem servir de sinal para os filhos de Israel.’”

[[v4-16-39]]

^<<v4-16-39,39>>^ Concordemente, Eleazar, o sacerdote, tomou os porta-lumes de cobre, apresentados por aqueles que foram queimados, e passaram a achatá-los, batendo-os num revestimento para o altar

[[v4-16-40]]

^<<v4-16-40,40>>^ como recordação para os filhos de Israel, com o fim de que nenhum homem estranho, que não fosse da descendência de Arão, se chegasse para fazer fumegar incenso perante Jeová e ninguém se tornasse igual a Corá e sua assembléia, assim como Jeová lhe falara por meio de Moisés.

[[v4-16-41]]

^<<v4-16-41,41>>^ E logo no dia seguinte, toda a assembléia dos filhos de Israel começou a resmungar contra Moisés e Arão, dizendo: “Vós é que fizestes morrer o povo de Jeová.”

[[v4-16-42]]

^<<v4-16-42,42>>^ E sucedeu que, quando a assembléia se havia congregado contra Moisés e Arão, viraram-se então para a tenda de reunião; e eis que a nuvem a cobriu e a glória de Jeová começou a aparecer.

[[v4-16-43]]

^<<v4-16-43,43>>^ E Moisés e Arão passaram a chegar-se perante a tenda de reunião.

[[v4-16-44]]

^<<v4-16-44,44>>^ Jeová falou então a Moisés,^&#42;1^ dizendo:

[NOTE]
====
. “Moisés”, MSamVg; LXXSy: “Moisés e Arão”.
====

[[v4-16-45]]

^<<v4-16-45,45>>^ “Levantai-vos do meio desta assembléia, para que eu os extermine num instante.” Em vista disso, lançaram-se com as suas faces [por terra].

[[v4-16-46]]

^<<v4-16-46,46>>^ Depois, Moisés disse a Arão: “Toma o porta-lume e põe nele fogo do altar, e põe incenso, e vai depressa à assembléia e faze expiação por eles, porque saiu indignação de diante de Jeová. Principiou a praga!”

[[v4-16-47]]

^<<v4-16-47,47>>^ Arão tomou-o imediatamente, assim como Moisés falara, e foi correndo para o meio da congregação; e eis que a praga havia principiado entre o povo. Pôs assim o incenso e começou a fazer expiação pelo povo.

[[v4-16-48]]

^<<v4-16-48,48>>^ E ficou de pé entre os mortos e os vivos. Finalmente se fez cessar o flagelo.

[[v4-16-49]]

^<<v4-16-49,49>>^ E os mortos pelo flagelo somaram quatorze mil e setecentos, além dos mortos por causa de Corá.

[[v4-16-50]]

^<<v4-16-50,50>>^ Quando Arão, por fim, voltou a Moisés, à entrada da tenda de reunião, fizera-se cessar o flagelo.

'''

xref:004-numeros/004-numeros-015.adoc#v4-15-0[&#60; Capítulo Anterior] | <<v4-16-0,Topo>> | xref:004-numeros/004-numeros-017.adoc#v4-17-0[Próximo Capítulo &#62;]