include::./index.adoc[]

[[v4-24-0]]
=== Números, 24
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v4-24-1]]

^<<v4-24-1,1>>^ Quando Balaão pôde ver que era bom aos olhos de Jeová abençoar Israel, não se afastou como das outras vezes para encontrar quaisquer presságios de azar,^&#42;1^ mas pôs a sua face para o ermo.

[NOTE]
====
. Ou “encantamentos”, isto é, lançados contra Israel.
====

[[v4-24-2]]

^<<v4-24-2,2>>^ Quando Balaão levantou os olhos e viu Israel residir segundo as suas tribos, então veio sobre ele o espírito de Deus.

[[v4-24-3]]

^<<v4-24-3,3>>^ Por isso encetou seu dito proverbial e disse:
“A pronunciação de Balaão, filho de Beor,
E a pronunciação do varão vigoroso^&#42;1^ de olho não selado,^&#42;2^

[NOTE]
====
. “Do varão vigoroso.” Hebr.: hag·gé·ver, uma pessoa viril; gr.: án·thro·pos; lat.: hó·mo.
. “Olho não selado.” Ou “olho implacável”. Veja VT, Vol. III, 1953, pp. 78, 79. Também v. 15.
====

[[v4-24-4]]

^<<v4-24-4,4>>^ A pronunciação daquele que ouve as declarações de Deus,^&#42;1^
Que chegou a ter uma visão do Todo-poderoso,
Ao cair com os olhos desvendados:

[NOTE]
====
. “Deus.” Hebr.: ’El; LXXBagster: “o Poderoso”; lat.: Dé·i.
====

[[v4-24-5]]

^<<v4-24-5,5>>^ Quão bem-parecidas são as tuas tendas, ó Jacó, os teus tabernáculos, ó Israel!

[[v4-24-6]]

^<<v4-24-6,6>>^ Como vales de torrente se estendem até longe,
Como jardins^&#42;1^ junto ao rio.
Como aloés^&#42;2^ plantados por Jeová,
Como cedros junto às águas.

[NOTE]
====
. “Paraísos”, LXX(gr.: pa·rá·dei·soi)Sy.
. “Aloés”, M. Possivelmente: “árvores maciças”. LXXSyVg: “tendas”.
====

[[v4-24-7]]

^<<v4-24-7,7>>^ Água está escorrendo dos seus dois baldes de couro,
E sua semente está junto a muitas águas.
Também seu rei será mais elevado do que Agague,^&#42;1^
E seu reino ficará erguido.

[NOTE]
====
. “Agague”, MSyVg; SamLXX: “Gogue”.
====

[[v4-24-8]]

^<<v4-24-8,8>>^ Deus o está fazendo sair do Egito;
Sua é a carreira veloz dum touro selvagem.^&#42;1^
Consumirá as nações, seus opressores,
E roerá os seus ossos e os despedaçará com as suas flechas.^&#42;2^

[NOTE]
====
. Ou “búfalo”. LXX: “unicórnio”; Vg: “rinoceronte”.
. “Flechas”, MVg; LXX: “projéteis”.
====

[[v4-24-9]]

^<<v4-24-9,9>>^ Abaixou-se, deitou-se como leão,^&#42;1^
E, como ao leão,^&#42;2^ quem se atreve a acordá-lo?
Os que te abençoam são os benditos,
E os que te amaldiçoam são os malditos.”

[NOTE]
====
. O leão africano. Veja 23:24 n.: “o leão”.
. O leão asiático. Veja 23:24 n.: “leão”.
====

[[v4-24-10]]

^<<v4-24-10,10>>^ Nisso se acendeu a ira de Balaque contra Balaão e ele bateu palmas, e Balaque prosseguiu, dizendo a Balaão: “Foi para maldizer meus inimigos que te chamei, e eis que estas três vezes os tens abençoado até o limite.

[[v4-24-11]]

^<<v4-24-11,11>>^ E agora corre depressa para o teu lugar. Eu havia dito a mim mesmo que sem falta te honraria, mas, eis que Jeová te negou a honra.”

[[v4-24-12]]

^<<v4-24-12,12>>^ Balaão, por sua vez, disse a Balaque: “Não foi que falei também aos teus mensageiros que me enviaste, dizendo:

[[v4-24-13]]

^<<v4-24-13,13>>^ ‘Se Balaque me desse a sua casa cheia de prata e de ouro, eu não poderia infringir a ordem de Jeová para fazer do meu próprio coração algo de bom ou algo de mau. Falarei o que Jeová falar’?

[[v4-24-14]]

^<<v4-24-14,14>>^ E agora, eis que vou para meu povo. Vem deveras, deixa-me advertir-te do que este povo fará ao teu povo, posteriormente, no fim dos dias.”

[[v4-24-15]]

^<<v4-24-15,15>>^ Assim, encetou seu dito proverbial e disse:
“A pronunciação de Balaão, filho de Beor,
E a pronunciação do varão vigoroso^&#42;1^ de olho não selado,^&#42;2^

[NOTE]
====
. Veja v. 3 n.: “vigoroso”.
. Veja v. 3 n.: “não selado”.
====

[[v4-24-16]]

^<<v4-24-16,16>>^ A pronunciação daquele que ouve as declarações de Deus,^&#42;1^
E daquele que conhece o conhecimento do Altíssimo —
Chegou a ter uma visão do Todo-poderoso,
Ao cair com os olhos desvendados:

[NOTE]
====
. “Deus.” Hebr.: ’El; gr.: The·oú; lat.: Dé·i.
====

[[v4-24-17]]

^<<v4-24-17,17>>^ Vê-lo-ei, mas não agora;
Avistá-lo-ei, mas não de perto.
Uma estrela^&#42;1^ há de avançar^&#42;2^ de Jacó,
E um cetro^&#42;3^ há de se levantar de Israel.
E ele há de rachar as têmporas [da cabeça] de Moabe,
E o crânio de todos os filhos do tumulto de guerra.^&#42;4^

[NOTE]
====
. “Estrela”, MSamLXXSyVg; TJ: “rei”.
. Ou “sair marchando”, MSam; LXXSyVg: “surgir”.
. Ou “vara”, MVg; TJ: “Messias”; LXX: “homem”; Sy: “cabeça”.
. “Filhos do tumulto de guerra”, para concordar com Je 48:45; MSamLXXSyVg: “filhos de Sete”.
====

[[v4-24-18]]

^<<v4-24-18,18>>^ E Edom tem de tornar-se uma possessão,
Sim, Seir tem de tornar-se possessão de seus inimigos,
Enquanto Israel está demonstrando a sua coragem.

[[v4-24-19]]

^<<v4-24-19,19>>^ E de Jacó sairá alguém subjugando,^&#42;1^
E ele terá de destruir a qualquer sobrevivente da cidade.”

[NOTE]
====
. Possivelmente: “E Jacó subjugará seus inimigos.” Vg: “De Jacó haverá alguém que governará.”
====

[[v4-24-20]]

^<<v4-24-20,20>>^ Quando chegou a ver Amaleque, levou mais avante seu dito proverbial e prosseguiu, dizendo:
“Amaleque foi a primeira^&#42;1^ das nações,
Mas o seu fim posterior será mesmo seu perecimento.”^&#42;2^

[NOTE]
====
. Ou “a principal; o princípio”.
. Possivelmente: “será para perecer para sempre”.
====

[[v4-24-21]]

^<<v4-24-21,21>>^ Quando chegou a ver os queneus, levou mais avante seu dito proverbial e prosseguiu, dizendo:
“Durável é a tua morada e no rochedo está posta a tua moradia.^&#42;1^

[NOTE]
====
. Ou “ninho”.
====

[[v4-24-22]]

^<<v4-24-22,22>>^ Mas haverá um que consumirá Caim^&#42;1^ com fogo.
Quando será que a Assíria te levará cativo?”

[NOTE]
====
. Isto é, a tribo dos queneus.
====

[[v4-24-23]]

^<<v4-24-23,23>>^ E ele levou mais avante seu dito proverbial e prosseguiu, dizendo:
“Ai! Quem sobreviverá quando Deus^&#42;1^ o causar?

[NOTE]
====
. “Deus.” Hebr.: ’El; gr.: ho The·ós; lat.: Dé·us.
====

[[v4-24-24]]

^<<v4-24-24,24>>^ E haverá navios da costa de Quitim,
E hão de afligir a Assíria,
E hão de afligir Éber.^&#42;1^
Mas também ele perecerá por fim.”

[NOTE]
====
. “Éber”, MSam; LXXSyVg: “os hebreus”. “Éber” pode referir-se à terra ou ao povo do outro lado, quer dizer, do Eufrates.
====

[[v4-24-25]]

^<<v4-24-25,25>>^ Depois, Balaão se levantou e foi embora, e voltou ao seu lugar. E Balaque também seguiu seu próprio caminho.

'''

xref:004-numeros/004-numeros-023.adoc#v4-23-0[&#60; Capítulo Anterior] | <<v4-24-0,Topo>> | xref:004-numeros/004-numeros-025.adoc#v4-25-0[Próximo Capítulo &#62;]