include::./index.adoc[]

[[v4-26-0]]
=== Números, 26
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v4-26-1]]

^<<v4-26-1,1>>^ E sucedeu, depois do flagelo,^&#42;1^ que Jeová prosseguiu, dizendo o seguinte a Moisés e a Eleazar, filho de Arão, o sacerdote:

[NOTE]
====
. No M, o capítulo 25 termina aqui, com a oração precedente constando como o v. 19.
====

[[v4-26-2]]

^<<v4-26-2,2>>^ “Fazei a soma de toda a assembléia dos filhos de Israel, da idade de vinte anos para cima, segundo a casa de seus pais, todos os que saem para o exército em Israel.”

[[v4-26-3]]

^<<v4-26-3,3>>^ E Moisés e Eleazar, o sacerdote, passaram a falar-lhes nas planícies desérticas de Moabe, junto ao Jordão, [na altura] de Jericó, dizendo:

[[v4-26-4]]

^<<v4-26-4,4>>^ “[Fazei a soma deles] da idade de vinte anos para cima, assim como Jeová mandara a Moisés.”
Ora, os filhos de Israel que saíram da terra do Egito foram:

[[v4-26-5]]

^<<v4-26-5,5>>^ Rubem, primogênito de Israel; os filhos de Rubem: De Anoque, a família dos anoquitas; de Palu, a família dos paluítas;

[[v4-26-6]]

^<<v4-26-6,6>>^ de Esrom, a família dos esronitas; de Carmi, a família dos carmitas.

[[v4-26-7]]

^<<v4-26-7,7>>^ Estas foram as famílias dos rubenitas, e seus registrados somaram quarenta e três mil setecentos e trinta.

[[v4-26-8]]

^<<v4-26-8,8>>^ E o filho^&#42;1^ de Palu foi Eliabe.

[NOTE]
====
. “Filho”, Vg; MSamLXXSy: “filhos”.
====

[[v4-26-9]]

^<<v4-26-9,9>>^ E os filhos de Eliabe: Nemuel e Datã, e Abirão. Este Datã e Abirão foram os convocados da assembléia que se empenharam numa peleja contra Moisés e Arão, na assembléia de Corá, quando se empenharam numa peleja contra Jeová.

[[v4-26-10]]

^<<v4-26-10,10>>^ A terra abriu então a sua boca e os tragou. Quanto a Corá, [faleceu] na morte da assembléia, quando o fogo consumiu duzentos e cinqüenta homens.^&#42;1^ E eles vieram a tornar-se um símbolo.

[NOTE]
====
. “Então a terra abriu a sua boca e a terra os tragou, quando a assembléia morreu, quando o fogo consumiu Corá e duzentos e cinqüenta homens”, Sam.
====

[[v4-26-11]]

^<<v4-26-11,11>>^ No entanto, os filhos de Corá não morreram.

[[v4-26-12]]

^<<v4-26-12,12>>^ Os filhos de Simeão, pelas suas famílias: De Nemuel,^&#42;1^ a família dos nemuelitas; de Jamim, a família dos jaminitas; de Jaquim, a família dos jaquinitas;

[NOTE]
====
. “Jemuel”, em Gên 46:10; Êx 6:15.
====

[[v4-26-13]]

^<<v4-26-13,13>>^ de Zerá,^&#42;1^ a família dos zeraítas; de Saul, a família dos saulitas.

[NOTE]
====
. “Zoar”, em Gên 46:10; Êx 6:15.
====

[[v4-26-14]]

^<<v4-26-14,14>>^ Estas foram as famílias dos simeonitas: vinte e dois mil e duzentos.

[[v4-26-15]]

^<<v4-26-15,15>>^ Os filhos de Gade, pelas suas famílias: De Zefom,^&#42;1^ a família dos zefonitas; de Hagi, a família dos hagitas; de Suni, a família dos sunitas;

[NOTE]
====
. “Zifiom”, em Gên 46:16.
====

[[v4-26-16]]

^<<v4-26-16,16>>^ de Ozni,^&#42;1^ a família dos oznitas; de Eri, a família dos eritas;

[NOTE]
====
. “Esbom”, em Gên 46:16.
====

[[v4-26-17]]

^<<v4-26-17,17>>^ de Arode,^&#42;1^ a família dos aroditas; de Areli, a família dos arelitas.

[NOTE]
====
. “Arodi”, em Gên 46:16.
====

[[v4-26-18]]

^<<v4-26-18,18>>^ Estas foram as famílias dos filhos de Gade, dos seus registrados: quarenta mil e quinhentos.

[[v4-26-19]]

^<<v4-26-19,19>>^ Os filhos de Judá foram Er e Onã. No entanto, Er e Onã morreram na terra de Canaã.

[[v4-26-20]]

^<<v4-26-20,20>>^ E os filhos de Judá vieram a ser, pelas suas famílias: De Selá, a família dos selanitas; de Peres, a família dos peresitas; de Zerá, a família dos zeraítas.

[[v4-26-21]]

^<<v4-26-21,21>>^ E os filhos de Peres vieram a ser: De Esrom, a família dos esronitas; de Hamul, a família dos hamulitas.

[[v4-26-22]]

^<<v4-26-22,22>>^ Estas foram as famílias de Judá, dos seus registrados: setenta e seis mil e quinhentos.

[[v4-26-23]]

^<<v4-26-23,23>>^ Os filhos de Issacar, pelas suas famílias, foram: De Tola, a família dos tolaítas; de Puva, a família dos punitas;

[[v4-26-24]]

^<<v4-26-24,24>>^ de Jasube,^&#42;1^ a família dos jasubitas; de Sinrom, a família dos sinronitas.

[NOTE]
====
. “Ió”, em Gên 46:13.
====

[[v4-26-25]]

^<<v4-26-25,25>>^ Estas foram as famílias de Issacar, dos seus registrados: sessenta e quatro mil e trezentos.

[[v4-26-26]]

^<<v4-26-26,26>>^ Os filhos de Zebulão, pelas suas famílias, foram: De Serede, a família dos sereditas; de Elom, a família dos elonitas; de Jaleel, a família dos jaleelitas.

[[v4-26-27]]

^<<v4-26-27,27>>^ Estas foram as famílias dos zebulonitas, dos seus registrados: sessenta mil e quinhentos.

[[v4-26-28]]

^<<v4-26-28,28>>^ Os filhos de José, pelas suas famílias, foram Manassés e Efraim.

[[v4-26-29]]

^<<v4-26-29,29>>^ Os filhos de Manassés foram: De Maquir, a família dos maquiritas. E Maquir tornou-se pai de Gileade. De Gileade, a família dos gileaditas.

[[v4-26-30]]

^<<v4-26-30,30>>^ Estes foram os filhos de Gileade: De Iézer, a família dos iezeritas; de Heleque, a família dos helequitas;

[[v4-26-31]]

^<<v4-26-31,31>>^ de Asriel, a família dos asrielitas; de Siquém, a família dos siquemitas;

[[v4-26-32]]

^<<v4-26-32,32>>^ de Semida, a família dos semidaítas; de Hefer, a família dos heferitas.

[[v4-26-33]]

^<<v4-26-33,33>>^ Ora, mostrou-se que Zelofeade, filho de Hefer, não tinha filhos, mas filhas, e os nomes das filhas de Zelofeade eram Maala e Noa, Hogla, Milca e Tirza.

[[v4-26-34]]

^<<v4-26-34,34>>^ Estas foram as famílias de Manassés, e seus registrados foram cinqüenta e dois mil e setecentos.

[[v4-26-35]]

^<<v4-26-35,35>>^ Estes foram os filhos de Efraim, pelas suas famílias: De Sutela, a família dos sutelaítas; de Bequer, a família dos bequeritas; de Taã, a família dos taanitas.

[[v4-26-36]]

^<<v4-26-36,36>>^ E estes foram os filhos de Sutela: De Erã, a família dos eranitas.

[[v4-26-37]]

^<<v4-26-37,37>>^ Estas foram as famílias dos filhos de Efraim, dos seus registrados: trinta e dois mil e quinhentos. Estes foram os filhos de José, pelas suas famílias.

[[v4-26-38]]

^<<v4-26-38,38>>^ Os filhos de Benjamim, pelas suas famílias, foram: De Bela, a família dos belaítas; de Asbel, a família dos asbelitas; de Airão,^&#42;1^ a família dos airamitas;

[NOTE]
====
. “Eí”, em Gên 46:21.
====

[[v4-26-39]]

^<<v4-26-39,39>>^ de Sefufão,^&#42;1^ a família dos sufamitas; de Hufão,^&#42;2^ a família dos hufamitas.

[NOTE]
====
. “Mupim”, em Gên 46:21; “supins”, em 1Cr 7:12.
. “Hupim”, em Gên 46:21.
====

[[v4-26-40]]

^<<v4-26-40,40>>^ Os filhos de Bela vieram a ser Arde e Naamã: [De Arde,]^&#42;1^ a família dos arditas; de Naamã, a família dos naamitas.

[NOTE]
====
. “[De Arde]”, de acordo com SamLXXVg.
====

[[v4-26-41]]

^<<v4-26-41,41>>^ Estes foram os filhos de Benjamim, pelas suas famílias, e seus registrados foram quarenta e cinco mil e seiscentos.

[[v4-26-42]]

^<<v4-26-42,42>>^ Estes foram os filhos de Dã, pelas suas famílias: De Suão,^&#42;1^ a família dos suamitas. Estas foram as famílias de Dã pelas suas famílias.

[NOTE]
====
. “Husim”, em Gên 46:23.
====

[[v4-26-43]]

^<<v4-26-43,43>>^ Todas as famílias dos suamitas, dos seus registrados, foram sessenta e quatro mil e quatrocentos.

[[v4-26-44]]

^<<v4-26-44,44>>^ Os filhos de Aser, pelas suas famílias, foram: De Imná, a família dos imnitas; de Isvi, a família dos isvitas; de Berias, a família dos beriitas;

[[v4-26-45]]

^<<v4-26-45,45>>^ dos filhos de Berias: De Héber, a família dos heberitas; de Malquiel, a família dos malquielitas.

[[v4-26-46]]

^<<v4-26-46,46>>^ E o nome da filha de Aser era Sera.

[[v4-26-47]]

^<<v4-26-47,47>>^ Estas foram as famílias dos filhos de Aser, dos seus registrados: cinqüenta e três mil e quatrocentos.

[[v4-26-48]]

^<<v4-26-48,48>>^ Os filhos de Naftali, pelas suas famílias, foram: De Jazeel, a família dos jazeelitas; de Guni, a família dos gunitas;

[[v4-26-49]]

^<<v4-26-49,49>>^ de Jézer, a família dos jezeritas; de Silém, a família dos silemitas.

[[v4-26-50]]

^<<v4-26-50,50>>^ Estas foram as famílias de Naftali, pelas suas famílias, e seus registrados foram quarenta e cinco mil e quatrocentos.

[[v4-26-51]]

^<<v4-26-51,51>>^ Estes foram os registrados dos filhos de Israel: seiscentos e um mil setecentos e trinta.

[[v4-26-52]]

^<<v4-26-52,52>>^ Depois, Jeová falou a Moisés, dizendo:

[[v4-26-53]]

^<<v4-26-53,53>>^ “A estes se deve repartir a terra como herança, pelo número dos nomes.

[[v4-26-54]]

^<<v4-26-54,54>>^ Conforme for grande o número, deves aumentar a sua herança, e conforme for pouco, deves reduzir a sua herança. A herança de cada um deve ser dada proporcional aos seus registrados.

[[v4-26-55]]

^<<v4-26-55,55>>^ Somente por sorte se deve repartir a terra. Devem receber uma herança segundo os nomes das tribos de seus pais.

[[v4-26-56]]

^<<v4-26-56,56>>^ Pela determinação das sortes se deve repartir a sua herança entre os muitos e os poucos.”

[[v4-26-57]]

^<<v4-26-57,57>>^ Ora, estes foram os registrados dos levitas, pelas suas famílias: De Gérson, a família dos gersonitas; de Coate, a família dos coatitas; de Merari, a família dos meraritas.

[[v4-26-58]]

^<<v4-26-58,58>>^ Estas foram as famílias dos levitas:^&#42;1^ a família dos libnitas, a família dos hebronitas, a família dos malitas, a família dos musitas, a família dos coraítas.
E Coate tornou-se pai de Anrão.

[NOTE]
====
. “Dos levitas”, Sy; MVg: “Levi”; LXX: “dos filhos de Levi”.
====

[[v4-26-59]]

^<<v4-26-59,59>>^ E o nome da esposa de Anrão era Joquebede, filha de Levi, que a sua esposa deu à luz^&#42;1^ para Levi, no Egito. No tempo correspondente deu à luz Arão e Moisés para Anrão, e Miriã, irmã deles.

[NOTE]
====
. “Filha . . . que passou a dar à luz estes”, LXX; SyVg: “filha que nasceu”.
====

[[v4-26-60]]

^<<v4-26-60,60>>^ A Arão nasceram então Nadabe e Abiú, Eleazar e Itamar.

[[v4-26-61]]

^<<v4-26-61,61>>^ Mas Nadabe e Abiú morreram por apresentarem fogo ilegítimo perante Jeová.

[[v4-26-62]]

^<<v4-26-62,62>>^ E seus registrados somaram vinte e três mil, todos os machos da idade de um mês para cima. Pois, não foram registrados entre os filhos de Israel, porque não se lhes devia dar nenhuma herança entre os filhos de Israel.

[[v4-26-63]]

^<<v4-26-63,63>>^ Estes foram os registrados por Moisés e Eleazar, o sacerdote, quando registraram os filhos de Israel nas planícies desérticas de Moabe, junto ao Jordão, [na altura] de Jericó.

[[v4-26-64]]

^<<v4-26-64,64>>^ Mas, entre estes não se mostrava haver qualquer homem dos registrados por Moisés e Arão, o sacerdote, quando registraram os filhos de Israel no ermo de Sinai.

[[v4-26-65]]

^<<v4-26-65,65>>^ Pois Jeová havia dito concernente a eles: “Sem falta morrerão no ermo.” De modo que não lhes sobrou nenhum homem a não ser Calebe, filho de Jefuné, e Josué, filho de Num.

'''

xref:004-numeros/004-numeros-025.adoc#v4-25-0[&#60; Capítulo Anterior] | <<v4-26-0,Topo>> | xref:004-numeros/004-numeros-027.adoc#v4-27-0[Próximo Capítulo &#62;]