include::./index.adoc[]

[[v11-8-0]]
=== 1 Reis, 8
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v11-8-1]]

^<<v11-8-1,1>>^ Naquele tempo Salomão passou a congregar os anciãos de Israel, todos os cabeças das tribos, os maiorais^&#42;1^ dos pais, dos filhos de Israel, ao Rei Salomão em Jerusalém, para que fizessem a arca do pacto de Jeová subir da Cidade de Davi, isto é, Sião.

[NOTE]
====
. Ou “nases”.
====

[[v11-8-2]]

^<<v11-8-2,2>>^ De modo que todos os homens de Israel se congregaram ao Rei Salomão no mês lunar de etanim, na festividade, isto é, no sétimo mês.

[[v11-8-3]]

^<<v11-8-3,3>>^ Vieram, pois, todos os anciãos de Israel e os sacerdotes começaram a carregar a Arca.

[[v11-8-4]]

^<<v11-8-4,4>>^ E foram levar a arca de Jeová para cima, bem como a tenda de reunião e todos os utensílios sagrados que havia na tenda; e os sacerdotes e os levitas foram levá-los para cima.

[[v11-8-5]]

^<<v11-8-5,5>>^ E o Rei Salomão e com ele toda a assembléia de Israel, os que mantinham seu encontro com ele, estavam diante da Arca, fazendo sacrifícios de ovelhas e de gado vacum que não se podiam contar nem computar pela sua multidão.

[[v11-8-6]]

^<<v11-8-6,6>>^ Então os sacerdotes levaram a arca do pacto de Jeová para dentro, ao seu lugar, ao compartimento mais recôndito da casa, ao Santíssimo, debaixo das asas dos querubins.

[[v11-8-7]]

^<<v11-8-7,7>>^ Pois os querubins estendiam as suas asas sobre o lugar da Arca, de modo que os querubins abrigavam por cima a Arca e seus varais.

[[v11-8-8]]

^<<v11-8-8,8>>^ Mas os varais eram compridos, de modo que as pontas dos varais eram visíveis desde o Santo na frente do compartimento mais recôndito, mas não eram visíveis de fora. E ali continuam até o dia de hoje.

[[v11-8-9]]

^<<v11-8-9,9>>^ Não havia nada na Arca a não ser as duas tábuas de pedra^&#42;1^ que Moisés tinha depositado ali em Horebe, quando Jeová fizera um pacto^&#42;2^ com os filhos de Israel ao saírem da terra do Egito.

[NOTE]
====
. LXX acrescenta “tábuas do pacto”.
. Lit.: “cortara [um pacto]”.
====

[[v11-8-10]]

^<<v11-8-10,10>>^ E sucedeu que, quando os sacerdotes saíram do lugar santo, a própria nuvem encheu a casa de Jeová.

[[v11-8-11]]

^<<v11-8-11,11>>^ E os sacerdotes não puderam ficar de pé para fazer a sua ministração, por causa da nuvem, pois a glória de Jeová enchia a casa de Jeová.

[[v11-8-12]]

^<<v11-8-12,12>>^ Naquele tempo disse Salomão: “O próprio Jeová disse que ia residir em densas trevas.

[[v11-8-13]]

^<<v11-8-13,13>>^ Construí para ti com bom êxito uma casa de morada excelsa, um lugar estabelecido para nele morares por tempo indefinido.”^&#42;1^

[NOTE]
====
. “Por tempo indefinido.” Lit.: “tempos indefinidos”. Hebr.: ‛oh·la·mím, pl.
====

[[v11-8-14]]

^<<v11-8-14,14>>^ Voltou então o rei a sua face e começou a abençoar toda a congregação de Israel enquanto toda a congregação^&#42;1^ de Israel estava de pé.

[NOTE]
====
. “Congregação de.” Hebr.: qehál; LXXVg: “eclésia”.
====

[[v11-8-15]]

^<<v11-8-15,15>>^ E ele prosseguiu, dizendo: “Bendito é Jeová, o Deus de Israel, que falou pela sua própria boca com Davi, meu pai, e que pela sua própria mão deu cumprimento, dizendo:

[[v11-8-16]]

^<<v11-8-16,16>>^ ‘Desde o dia em que fiz meu povo Israel sair do Egito não escolhi cidade dentre todas as tribos de Israel, a fim de construir uma casa para que o meu nome continuasse ali; mas escolherei a Davi para vir a estar sobre o meu povo Israel.’

[[v11-8-17]]

^<<v11-8-17,17>>^ E ficou achegado ao coração de Davi, meu pai, construir uma casa ao nome de Jeová, o Deus de Israel.

[[v11-8-18]]

^<<v11-8-18,18>>^ Mas Jeová disse a Davi, meu pai: ‘Visto que ficou achegado ao teu coração construir uma casa ao meu nome, fizeste bem, pois isso se mostrou achegado ao teu coração.

[[v11-8-19]]

^<<v11-8-19,19>>^ Apenas tu mesmo não construirás a casa, mas teu filho, que sai dos teus lombos, é quem construirá a casa ao meu nome.’

[[v11-8-20]]

^<<v11-8-20,20>>^ E Jeová passou a cumprir a sua palavra que falara, para que eu me levantasse em lugar de Davi, meu pai, e me sentasse no trono de Israel, assim como Jeová havia falado, e para que eu construísse a casa ao nome de Jeová, o Deus de Israel,

[[v11-8-21]]

^<<v11-8-21,21>>^ e para que eu estabelecesse ali um lugar para a Arca, onde está o pacto de Jeová, que ele concluiu com os nossos antepassados quando os fez sair da terra do Egito.”

[[v11-8-22]]

^<<v11-8-22,22>>^ E Salomão começou a ficar de pé diante do altar de Jeová, na frente de toda a congregação de Israel, e então estendeu as palmas das suas mãos para os céus;

[[v11-8-23]]

^<<v11-8-23,23>>^ e prosseguiu, dizendo: “Ó Jeová, Deus de Israel, não há Deus^&#42;1^ igual a ti nos céus em cima, nem na terra embaixo, guardando o pacto e a benevolência^&#42;2^ para com os teus servos que andam diante de ti de todo o seu coração,

[NOTE]
====
. “Deus.” Hebr.: ’Elo·hím; gr.: The·ós.
. Ou “amor leal”.
====

[[v11-8-24]]

^<<v11-8-24,24>>^ tu, que cumpriste para com o teu servo Davi, meu pai, aquilo que lhe prometeste, de modo que fizeste a promessa^&#42;1^ com a tua própria boca e deste cumprimento com a tua própria mão, como no dia de hoje.

[NOTE]
====
. Lit.: “falaste”.
====

[[v11-8-25]]

^<<v11-8-25,25>>^ E agora, ó Jeová, Deus de Israel, cumpre para com o teu servo Davi, meu pai, aquilo que lhe prometeste, dizendo: ‘Não se decepará diante de mim homem teu, [impedindo-o] de sentar-se no trono de Israel, se os teus filhos tão-somente cuidarem do seu caminho, andando diante de mim assim como tu andaste diante de mim.’

[[v11-8-26]]

^<<v11-8-26,26>>^ E agora, ó Deus de Israel,^&#42;1^ por favor, mostre-se fidedigna a tua promessa^&#42;2^ que fizeste ao teu servo Davi, meu pai.

[NOTE]
====
. “Ó Deus de Israel”, M; Tmss.LXXSyVgc e 35 mss. hebr.: “ó Jeová, Deus de Israel”.
. Lit.: “palavras”. Mmargem: “palavra”.
====

[[v11-8-27]]

^<<v11-8-27,27>>^ “Porém, morará Deus verdadeiramente na terra? Eis que os próprios céus, sim, o céu dos céus, não te podem conter; quanto menos, então, esta casa que construí!

[[v11-8-28]]

^<<v11-8-28,28>>^ E terás de virar-te para a oração do teu servo e para o seu pedido de favor, ó Jeová, meu Deus, para escutar o clamor suplicante e a oração com que teu servo hoje está orando diante de ti;

[[v11-8-29]]

^<<v11-8-29,29>>^ a fim de que os teus olhos se mostrem abertos para com esta casa noite e dia, para com o lugar de que disseste: ‘Ali mostrará estar o meu nome’, para escutar a oração com que teu servo ora em direção a este lugar.

[[v11-8-30]]

^<<v11-8-30,30>>^ E terás de escutar o pedido de favor da parte do teu servo e do teu povo Israel com que orarem em direção a este lugar; e que tu mesmo ouças no lugar em que moras, nos céus, e terás de ouvir e perdoar.

[[v11-8-31]]

^<<v11-8-31,31>>^ “Quando um homem pecar contra o seu próximo e realmente puser sobre ele uma maldição, para sujeitá-lo à maldição, e ele realmente vier [na] maldição perante o teu altar nesta casa,

[[v11-8-32]]

^<<v11-8-32,32>>^ então que tu mesmo ouças desde os céus, e terás de agir e julgar os teus servos, pronunciando iníquo ao iníquo por lançares o seu caminho sobre a sua própria cabeça, e declarando justo ao justo por lhe dares segundo a sua própria justiça.

[[v11-8-33]]

^<<v11-8-33,33>>^ “Quando o teu povo Israel for derrotado diante do inimigo, porque estiveram pecando contra ti, e eles deveras voltarem a ti e elogiarem o teu nome, e orarem e fizerem um pedido de favor em direção a ti, nesta casa,

[[v11-8-34]]

^<<v11-8-34,34>>^ então, que tu mesmo ouças desde os céus, e terás de perdoar o pecado do teu povo Israel e terás de trazê-los de volta ao solo que deste aos seus antepassados.

[[v11-8-35]]

^<<v11-8-35,35>>^ “Quando o céu estiver cerrado, de modo que não venha a haver chuva, porque estiveram pecando contra ti, e eles realmente orarem em direção a este lugar e elogiarem o teu nome, e recuarem do seu pecado, por tu os teres atribulado,

[[v11-8-36]]

^<<v11-8-36,36>>^ então que tu mesmo ouças desde os céus, e terás de perdoar o pecado dos teus servos, sim, do teu povo Israel, porque lhes ensinas o bom caminho em que devem andar; e terás de dar chuva sobre a tua terra que deste ao teu povo como propriedade hereditária.

[[v11-8-37]]

^<<v11-8-37,37>>^ “Caso ocorra uma fome no país, caso ocorra uma pestilência, caso venha a haver crestamento, bolor, gafanhotos, baratas; caso seu inimigo os sitie na terra dos seus portões^&#42;1^ — qualquer tipo de praga, qualquer tipo de enfermidade —

[NOTE]
====
. Ou “cidades”, representadas pelos “portões”, por uma figura de linguagem, uma sinédoque.
====

[[v11-8-38]]

^<<v11-8-38,38>>^ qualquer oração, qualquer pedido de favor que venha a haver da parte de qualquer homem [ou] de todo o teu povo Israel, por conhecerem, cada um, a praga do seu próprio coração, e eles realmente estenderem as palmas das suas mãos para esta casa,

[[v11-8-39]]

^<<v11-8-39,39>>^ então, que tu mesmo ouças desde os céus, teu lugar estabelecido de morada, e terás de perdoar e agir, e dar a cada um segundo todos os seus caminhos, porque conheces o seu coração (porque somente tu conheces bem o coração de todos os filhos da humanidade);^&#42;1^

[NOTE]
====
. “Humanidade.” Hebr.: ha·’a·dhám; LXXVg: “homens”.
====

[[v11-8-40]]

^<<v11-8-40,40>>^ a fim de que te temam todos os dias em que estiverem vivos sobre a face do solo que deste aos nossos antepassados.

[[v11-8-41]]

^<<v11-8-41,41>>^ “E também ao estrangeiro que não faz parte do teu povo Israel e que realmente vem duma terra distante por causa do teu nome,

[[v11-8-42]]

^<<v11-8-42,42>>^ (pois ouvirão [falar] do teu grande nome, e da tua forte mão, e do teu braço estendido,) e ele realmente vem e ora em direção a esta casa,

[[v11-8-43]]

^<<v11-8-43,43>>^ que tu mesmo ouças desde os céus, teu lugar estabelecido de morada, e terás de fazer segundo tudo aquilo pelo qual o estrangeiro te invocar; para que todos os povos da terra conheçam o teu nome para te temer assim como teu povo Israel faz, e a fim de que saibam que o teu próprio nome tem sido invocado sobre esta casa que construí.

[[v11-8-44]]

^<<v11-8-44,44>>^ “Caso teu povo saia à guerra contra os seus inimigos no caminho em que os envias e eles deveras orem a Jeová em direção à cidade que escolheste e à casa que construí ao teu nome,

[[v11-8-45]]

^<<v11-8-45,45>>^ então terás de ouvir desde os céus a sua oração e o seu pedido de favor, e terás de executar o julgamento para eles.

[[v11-8-46]]

^<<v11-8-46,46>>^ “Caso pequem contra ti, (pois não há homem que não peque,) e tenhas de irar-te com eles e entregá-los ao inimigo, e seus captores realmente os levem cativos à terra do inimigo, distante ou próxima;

[[v11-8-47]]

^<<v11-8-47,47>>^ e eles deveras voltem ao seu juízo^&#42;1^ na terra à qual foram levados cativos, e realmente retornem e te façam um pedido de favor na terra dos seus captores, dizendo: ‘Pecamos e erramos, agimos iniquamente’;

[NOTE]
====
. Lit.: “e eles deveras façam um retorno ao seu coração”.
====

[[v11-8-48]]

^<<v11-8-48,48>>^ e eles deveras retornem a ti de todo o seu coração e de toda a sua alma, na terra dos seus inimigos que os levaram cativos, e deveras orem a ti em direção à sua terra que deste aos seus antepassados, à cidade que escolheste e à casa que construí ao teu nome;

[[v11-8-49]]

^<<v11-8-49,49>>^ então, desde os céus, teu lugar estabelecido de morada, terás de ouvir a sua oração e o seu pedido de favor, e terás de executar julgamento para eles,

[[v11-8-50]]

^<<v11-8-50,50>>^ e terás de perdoar ao teu povo que pecou contra ti, bem como todas as suas transgressões com que transgrediram contra ti; e terás de fazê-los objetos de misericórdia diante dos seus captores e estes terão de apiedar-se deles,

[[v11-8-51]]

^<<v11-8-51,51>>^ (porque são teu povo e tua herança, que fizeste sair do Egito, de dentro do forno de fundição de ferro,)

[[v11-8-52]]

^<<v11-8-52,52>>^ para que os teus olhos se mostrem abertos ao pedido de favor do teu servo e ao pedido de favor do teu povo Israel, escutando-os em tudo aquilo pelo qual te invocarem.

[[v11-8-53]]

^<<v11-8-53,53>>^ Pois, tu mesmo os separaste como a tua herança dentre todos os povos da terra, assim como falaste por intermédio de Moisés, teu servo, quando fizeste os nossos antepassados sair do Egito, ó Soberano Senhor Jeová.”

[[v11-8-54]]

^<<v11-8-54,54>>^ E sucedeu que, acabando Salomão de orar a Jeová com toda esta oração e pedido de favor, ele se levantou de diante do altar de Jeová, de estar de joelhos com as suas palmas estendidas para os céus;

[[v11-8-55]]

^<<v11-8-55,55>>^ e começou a ficar de pé e a abençoar toda a congregação^&#42;1^ de Israel em alta voz, dizendo:

[NOTE]
====
. “Congregação de.” Hebr.: qehál; gr.: ek·kle·sí·an; lat.: ec·clé·si·ae.
====

[[v11-8-56]]

^<<v11-8-56,56>>^ “Bendito seja Jeová, que deu ao seu povo Israel um lugar de descanso segundo tudo o que prometeu. Não falhou nem uma única palavra de toda a sua boa promessa que ele fez^&#42;1^ por intermédio de Moisés, seu servo.

[NOTE]
====
. Lit.: “sua boa palavra que ele falou”.
====

[[v11-8-57]]

^<<v11-8-57,57>>^ Mostre Jeová, nosso Deus, estar conosco assim como mostrou estar com os nossos antepassados. Que não nos deixe nem nos abandone,

[[v11-8-58]]

^<<v11-8-58,58>>^ a fim de inclinar nosso coração a si, para andar em todos os seus caminhos e para guardar seus mandamentos, e seus regulamentos, e suas decisões judiciais, que ele ordenou aos nossos antepassados.

[[v11-8-59]]

^<<v11-8-59,59>>^ E que estas palavras minhas, com as quais fiz o pedido de favor perante Jeová, mostrem estar sempre perto de Jeová, nosso Deus, de dia e de noite, para que ele execute o julgamento para o seu servo e o julgamento para o seu povo Israel, conforme necessário de dia em dia;

[[v11-8-60]]

^<<v11-8-60,60>>^ com o fim de que todos os povos da terra saibam que Jeová é o [verdadeiro] Deus. Não há outro.

[[v11-8-61]]

^<<v11-8-61,61>>^ E vosso coração tem de mostrar-se pleno para com Jeová, nosso Deus, andando nos seus regulamentos e guardando seus mandamentos como no dia de hoje.”

[[v11-8-62]]

^<<v11-8-62,62>>^ E o rei e todo o Israel com ele ofereciam um grande sacrifício perante Jeová.

[[v11-8-63]]

^<<v11-8-63,63>>^ E Salomão passou a oferecer os sacrifícios de participação em comum que tinha para oferecer a Jeová, vinte e duas mil cabeças de gado vacum e cento e vinte mil ovelhas, para que o rei e todos os filhos de Israel inaugurassem a casa de Jeová.

[[v11-8-64]]

^<<v11-8-64,64>>^ Naquele dia, o rei teve de santificar o centro do pátio que há diante da casa de Jeová, porque tinha de ofertar ali o sacrifício queimado e a oferta de cereais, e os pedaços gordos dos sacrifícios de participação em comum, pois o altar de cobre que havia diante de Jeová era pequeno demais para conter o sacrifício queimado e a oferta de cereais, bem como os pedaços gordos dos sacrifícios de participação em comum.

[[v11-8-65]]

^<<v11-8-65,65>>^ E Salomão passou a realizar a festividade naquele tempo, e com ele todo o Israel, uma grande congregação, desde a entrada de Hamate^&#42;1^ para baixo até o vale da torrente do Egito, perante Jeová, nosso Deus,^&#42;2^ por sete dias e mais sete dias, quatorze dias.

[NOTE]
====
. Veja Jos 13:5 n.: “Hamate”.
. “Perante Jeová, nosso Deus, na casa que ele construiu, comendo e bebendo, e alegrando-se diante de Jeová, nosso Deus”, LXX.
====

[[v11-8-66]]

^<<v11-8-66,66>>^ E no oitavo dia mandou o povo embora; e eles começaram a abençoar o rei e a ir para os seus lares,^&#42;1^ alegrando-se e sentindo-se contentes de coração por toda a bondade que Jeová havia feito a Davi, seu servo, e a Israel, seu povo.

[NOTE]
====
. Lit.: “tendas”.
====

'''

xref:011-1-reis/011-1-reis-007.adoc#v11-7-0[&#60; Capítulo Anterior] | <<v11-8-0,Topo>> | xref:011-1-reis/011-1-reis-009.adoc#v11-9-0[Próximo Capítulo &#62;]