include::./index.adoc[]

[[v11-18-0]]
=== 1 Reis, 18
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v11-18-1]]

^<<v11-18-1,1>>^ E sucedeu, [depois de] muitos dias, que a própria palavra de Jeová veio a Elias no terceiro ano, dizendo: “Vai, mostra-te a Acabe, visto que estou decidido a dar chuva^&#42;1^ sobre a superfície do solo.”

[NOTE]
====
. Ou “dê eu chuva”.
====

[[v11-18-2]]

^<<v11-18-2,2>>^ Por conseguinte, Elias foi para se mostrar a Acabe, enquanto a fome era severa em Samaria.

[[v11-18-3]]

^<<v11-18-3,3>>^ Entrementes, Acabe chamou a Obadias,^&#42;1^ que estava sobre os da casa. (Ora, o próprio Obadias mostrara ser alguém que temia grandemente a Jeová.

[NOTE]
====
. Significando “Servo de Jeová”. Hebr.: ‛O·vadh·yá·hu.
====

[[v11-18-4]]

^<<v11-18-4,4>>^ Por isso, aconteceu que, quando Jezabel decepou os profetas de Jeová, Obadias passou a tomar cem profetas e a mantê-los escondidos aos cinqüenta numa caverna, e ele os supriu de pão e de água.)

[[v11-18-5]]

^<<v11-18-5,5>>^ E Acabe prosseguiu, dizendo a Obadias: “Vai pelo país a todos os mananciais de água e a todos os vales de torrente. Talvez achemos capim verde, para preservarmos vivos os cavalos e os mulos, e não se decepe [mais nenhum] dos animais.”

[[v11-18-6]]

^<<v11-18-6,6>>^ Repartiram, pois, entre si a terra que iam atravessar. O próprio Acabe foi sozinho por um caminho e o próprio Obadias foi sozinho por outro caminho.

[[v11-18-7]]

^<<v11-18-7,7>>^ Enquanto Obadias seguia no caminho, ora, eis que veio Elias ao seu encontro. Ele o reconheceu imediatamente, e lançou-se com a sua face [por terra] e disse: “És tu, meu senhor Elias?”

[[v11-18-8]]

^<<v11-18-8,8>>^ A isto ele lhe disse: “Sou eu. Vai, dize ao teu senhor: ‘Eis aqui Elias.’”

[[v11-18-9]]

^<<v11-18-9,9>>^ Mas ele disse: “Que pecado cometi que devias entregar teu servo na mão de Acabe para entregar-me à morte?

[[v11-18-10]]

^<<v11-18-10,10>>^ Assim como vive Jeová, teu Deus, não há nação nem reino em que meu senhor não te mandou procurar. Depois de dizerem: ‘Não está [aqui]’, fez o reino e a nação jurar que não te podiam achar.

[[v11-18-11]]

^<<v11-18-11,11>>^ E agora dizes: ‘Vai, dize ao teu senhor: “Eis aqui Elias.”’

[[v11-18-12]]

^<<v11-18-12,12>>^ E forçosamente se há de dar que, quando eu mesmo me retirar de ti, então o próprio espírito de Jeová te levará embora para onde não sei; e eu terei ido informar Acabe e ele não te achará, e forçosamente me matará, visto que este teu servo tem temido a Jeová desde a sua mocidade.

[[v11-18-13]]

^<<v11-18-13,13>>^ Não se informou ao meu senhor o que fiz quando Jezabel matou os profetas de Jeová, como mantive escondidos a alguns dos profetas de Jeová, cem homens aos cinqüenta, numa caverna, e os supria de pão e de água?

[[v11-18-14]]

^<<v11-18-14,14>>^ E agora estás dizendo: ‘Vai, dize ao teu senhor: “Eis aqui Elias.”’ E forçosamente me matará.”

[[v11-18-15]]

^<<v11-18-15,15>>^ Todavia, Elias disse: “Assim como vive Jeová dos exércitos, perante quem deveras estou de pé,^&#42;1^ hoje eu me mostrarei a ele.”

[NOTE]
====
. Ou “a quem deveras assisto”.
====

[[v11-18-16]]

^<<v11-18-16,16>>^ Por conseguinte, Obadias foi ao encontro de Acabe e o informou; e Acabe, pois, foi ao encontro de Elias.

[[v11-18-17]]

^<<v11-18-17,17>>^ E sucedeu que, assim que Acabe viu Elias, Acabe disse-lhe imediatamente: “És tu, aquele que trouxe o banimento a Israel?”

[[v11-18-18]]

^<<v11-18-18,18>>^ A isto ele disse: “Eu não trouxe o banimento a Israel, mas foste tu e a casa de teu pai, porque deixastes os mandamentos de Jeová e fostes seguir os Baalins.

[[v11-18-19]]

^<<v11-18-19,19>>^ E agora, manda reunir todo o Israel a mim no monte Carmelo, e também os quatrocentos e cinqüenta profetas de Baal e os quatrocentos profetas do poste sagrado, que estão comendo à mesa de Jezabel.”

[[v11-18-20]]

^<<v11-18-20,20>>^ E Acabe passou a enviar [mensageiros] entre todos os filhos de Israel e a reunir os profetas no monte Carmelo.

[[v11-18-21]]

^<<v11-18-21,21>>^ Elias aproximou-se então de todo o povo e disse: “Até quando ficareis mancando em duas opiniões diferentes?^&#42;1^ Se Jeová é o [verdadeiro] Deus,^&#42;2^ ide segui-lo; mas se é Baal, ide segui-lo.” E o povo não lhe disse uma palavra em resposta.

[NOTE]
====
. Ou “duas muletas”, KB, p. 663.
. “O [verdadeiro] Deus.” Hebr.: ha·’Elo·hím, com o artigo definido ha, “o”, precedendo o título ’Elo·hím. Isto se faz para dar ênfase no contraste com Baal, o falso deus. Veja Ap. 1F.
====

[[v11-18-22]]

^<<v11-18-22,22>>^ E Elias prosseguiu, dizendo ao povo: “Eu mesmo sobrei como profeta de Jeová, só eu, ao passo que os profetas de Baal são quatrocentos e cinqüenta homens.

[[v11-18-23]]

^<<v11-18-23,23>>^ Agora dêem-se-nos dois novilhos, e escolham eles para si um novilho e cortem-no em pedaços, e coloquem-no sobre a lenha, mas não lhe devem pôr fogo. E eu mesmo prepararei o outro novilho e terei de colocá-lo sobre a lenha, mas não lhe porei fogo.

[[v11-18-24]]

^<<v11-18-24,24>>^ E tereis de invocar o nome de vosso deus,^&#42;1^ e eu, da minha parte, invocarei o nome de Jeová; e terá de dar-se que o [verdadeiro] Deus^&#42;2^ que responder por fogo é o [verdadeiro] Deus.”^&#42;3^ A isto todo o povo respondeu e disse: “A coisa é boa.”

[NOTE]
====
. “Vosso deus.” Hebr.: ’elo·heh·khém, pl. de ’elóh·ah, referindo-se a Baal, o falso deus.
. “O [verdadeiro] Deus.” Hebr.: ha·’Elo·hím, seguido pela oração relativa: “que responder por fogo”.
. “O [verdadeiro] Deus.” Hebr.: ha·’Elo·hím, absoluto, no predicado. Veja Ap. 1F.
====

[[v11-18-25]]

^<<v11-18-25,25>>^ Elias disse então aos profetas de Baal:^&#42;1^ “Escolhei para vós um novilho e o preparai primeiro, visto que sois a maioria; e invocai o nome de vosso deus, mas não lhe deveis pôr fogo.”

[NOTE]
====
. Lit.: “do Baal”. Hebr.: hab·Bá‛al.
====

[[v11-18-26]]

^<<v11-18-26,26>>^ Concordemente, tomaram o novilho que lhes deu. Prepararam-no então e continuaram a invocar o nome de Baal, desde a manhã até ao meio-dia, dizendo: “Ó Baal, responde-nos!” Mas não havia voz e não havia quem respondesse. E eles continuaram a mancar em volta do altar que tinham feito.

[[v11-18-27]]

^<<v11-18-27,27>>^ E sucedeu, ao meio-dia, que Elias começou a mofar deles e a dizer: “Clamai ao máximo da vossa voz,^&#42;1^ pois ele é deus; porque deve estar preocupado com algum assunto, e tem excremento e precisa ir à privada. Ou talvez esteja dormindo e precise acordar!”

[NOTE]
====
. Lit.: “Clamai com grande voz.”
====

[[v11-18-28]]

^<<v11-18-28,28>>^ E começaram a clamar ao máximo da sua voz e a fazer cortes em si mesmos com punhais e com lanças, segundo o seu costume, até derramarem sangue sobre si.

[[v11-18-29]]

^<<v11-18-29,29>>^ E sucedeu que, assim que passou o meio-dia e eles continuaram a comportar-se como profetas, até a ascensão da oferta de cereais, não havia voz e não havia quem respondesse, e não se dava atenção.

[[v11-18-30]]

^<<v11-18-30,30>>^ Por fim, Elias disse a todo o povo: “Aproximai-vos de mim.” Assim, todo o povo aproximou-se dele. Então ele passou a restaurar o altar de Jeová que havia sido derrubado.

[[v11-18-31]]

^<<v11-18-31,31>>^ Portanto, Elias tomou doze pedras, segundo o número das tribos dos filhos de Jacó, a quem tinha chegado a palavra de Jeová, dizendo: “Israel é o que o teu nome virá a ser.”

[[v11-18-32]]

^<<v11-18-32,32>>^ E ele prosseguiu, construindo com as pedras um altar em nome de Jeová e fazendo um rego, de aproximadamente a área semeada com dois seás^&#42;1^ de semente, em todo o redor do altar.

[NOTE]
====
. Um seá equivalia a 7,33 l.
====

[[v11-18-33]]

^<<v11-18-33,33>>^ Depois pôs a lenha em ordem, e cortou o novilho em pedaços, e colocou-o sobre a lenha. Então disse: “Enchei quatro jarros grandes com água e despejai-a sobre a oferta queimada e sobre a lenha.”

[[v11-18-34]]

^<<v11-18-34,34>>^ Então ele disse: “Fazei-o outra vez.” Portanto, fizeram-no outra vez. Mas ele disse: “Fazei-o pela terceira vez.” Portanto, fizeram-no pela terceira vez.

[[v11-18-35]]

^<<v11-18-35,35>>^ A água ficou assim toda em volta do altar, e também o rego ele encheu de água.

[[v11-18-36]]

^<<v11-18-36,36>>^ E aconteceu, na hora em que ascende a oferta de cereais, que Elias, o profeta, começou a aproximar-se e a dizer: “Ó Jeová, Deus de Abraão, de Isaque e de Israel, saiba-se hoje que tu és Deus em Israel e que eu sou o teu servo, e que é pela tua palavra que fiz todas estas coisas.

[[v11-18-37]]

^<<v11-18-37,37>>^ Responde-me, ó Jeová, responde-me, para que este povo saiba que tu, Jeová, és o [verdadeiro] Deus^&#42;1^ e que tu mesmo fizeste o coração deles voltar atrás.”

[NOTE]
====
. Lit.: “Jeová, o [verdadeiro] Deus.” Hebr.: Yehwáh ha·’Elo·hím; gr.: Ký·ri·os ho The·ós; lat.: Dó·mi·nus Dé·us.
====

[[v11-18-38]]

^<<v11-18-38,38>>^ Nisto veio cair fogo da parte de Jeová e passou a consumir a oferta queimada e a lenha, bem como as pedras, e o pó, e lambeu a água que havia no rego.

[[v11-18-39]]

^<<v11-18-39,39>>^ Quando todo o povo o viu, lançaram-se imediatamente com as suas faces [por terra] e disseram: “Jeová é o [verdadeiro] Deus! Jeová é o [verdadeiro] Deus!”

[[v11-18-40]]

^<<v11-18-40,40>>^ Elias disse-lhes então: “Pegai os profetas de Baal! Não deixeis escapar nem sequer um deles!” Pegaram-nos imediatamente, e Elias os fez levar para baixo ao vale da torrente do Quisom e os abateu ali.

[[v11-18-41]]

^<<v11-18-41,41>>^ Elias disse então a Acabe: “Sobe, come e bebe; pois há o ruído da turbulência dum aguaceiro.”

[[v11-18-42]]

^<<v11-18-42,42>>^ E Acabe passou a subir para comer e beber. Quanto a Elias, subiu ao cume do Carmelo e começou a agachar-se no chão e a manter a face entre os joelhos.

[[v11-18-43]]

^<<v11-18-43,43>>^ Então ele disse ao seu ajudante: “Por favor, sobe. Olha na direção do mar.” Ele subiu, pois, e olhou, e então disse: “Não há absolutamente nada.” E ele prosseguiu, dizendo: “Volta”, por sete vezes.

[[v11-18-44]]

^<<v11-18-44,44>>^ E sucedeu, na sétima vez, que ele passou a dizer: “Eis que sobe do mar uma nuvem pequena, como a palma da mão dum homem.” Ele disse então: “Sobe, dize a Acabe: ‘Atrela! E desce para que o aguaceiro não te detenha!’”

[[v11-18-45]]

^<<v11-18-45,45>>^ E no ínterim sucedeu que os próprios céus se enegreceram com nuvens e vento,^&#42;1^ e começou a haver um grande aguaceiro. E Acabe seguiu [no carro] e foi para Jezreel.

[NOTE]
====
. “E vento.” Hebr.: werú·ahh; gr.: pneú·ma·ti; lat.: vén·tus. Veja Gên 1:2 n.: “ativa”; Gên 8:1 n.
====

[[v11-18-46]]

^<<v11-18-46,46>>^ E a própria mão de Jeová mostrou estar sobre Elias, de modo que ele cingiu seus quadris e foi correr adiante de Acabe até Jezreel.

'''

xref:011-1-reis/011-1-reis-017.adoc#v11-17-0[&#60; Capítulo Anterior] | <<v11-18-0,Topo>> | xref:011-1-reis/011-1-reis-019.adoc#v11-19-0[Próximo Capítulo &#62;]