include::./index.adoc[]

[[v11-16-0]]
=== 1 Reis, 16
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v11-16-1]]

^<<v11-16-1,1>>^ A palavra de Jeová veio então a Jeú, filho de Hanani, contra Baasa, dizendo:

[[v11-16-2]]

^<<v11-16-2,2>>^ “Visto que eu te ergui do pó para te constituir líder do meu povo Israel, mas tu foste andar no caminho de Jeroboão e assim fizeste meu povo Israel pecar, ofendendo-me eles com os seus pecados,

[[v11-16-3]]

^<<v11-16-3,3>>^ eis que faço uma varredura atrás de Baasa e atrás da sua casa, e hei de constituir a sua casa igual à casa de Jeroboão, filho de Nebate.

[[v11-16-4]]

^<<v11-16-4,4>>^ Quem de Baasa morrer na cidade, os cães devorarão; e quem dele morrer no campo, as aves dos céus comerão.”

[[v11-16-5]]

^<<v11-16-5,5>>^ Quanto ao resto dos assuntos de Baasa, e o que ele fez e sua potência, não estão escritos no livro dos assuntos dos dias dos reis de Israel?

[[v11-16-6]]

^<<v11-16-6,6>>^ Por fim, Baasa deitou-se com os seus antepassados e foi enterrado em Tirza; e Elá, seu filho, começou a reinar em seu lugar.

[[v11-16-7]]

^<<v11-16-7,7>>^ E também por intermédio de Jeú, filho de Hanani, viera a própria palavra de Jeová contra Baasa e sua casa, tanto por causa de toda a maldade que ele fez aos olhos de Jeová, ofendendo-o com o trabalho das suas mãos, para que ela se tornasse igual à casa de Jeroboão, como porque o^&#42;1^ havia golpeado.

[NOTE]
====
. “O”, isto é, Nadabe, filho de Jeroboão. Veja 15:25-29.
====

[[v11-16-8]]

^<<v11-16-8,8>>^ No vigésimo sexto ano de Asa, rei de Judá, Elá, filho de Baasa, tornou-se rei sobre Israel em Tirza, por dois anos.

[[v11-16-9]]

^<<v11-16-9,9>>^ E seu servo Zinri, chefe da metade dos carros, começou a conspirar contra ele enquanto este estava em Tirza, bebendo até ficar bêbedo na casa de Arza, que estava sobre os da casa, em Tirza.

[[v11-16-10]]

^<<v11-16-10,10>>^ E Zinri passou a entrar e a golpeá-lo, e a entregá-lo à morte no vigésimo sétimo ano de Asa, rei de Judá, e começou a reinar em seu lugar.

[[v11-16-11]]

^<<v11-16-11,11>>^ E aconteceu que, quando começou a reinar, assim que se assentou no seu trono, golpeou toda a casa de Baasa. Não lhe deixou restar quem urinasse contra o muro,^&#42;1^ nem seus vingadores de sangue,^&#42;2^ nem seus amigos.

[NOTE]
====
. “Quem urinasse contra o muro.” Esta é uma expressão idiomática hebr. referindo-se a varões.
. Ou “seus goels”, M; SyVg: “seus parentes”.
====

[[v11-16-12]]

^<<v11-16-12,12>>^ Assim Zinri aniquilou toda a casa de Baasa, segundo a palavra de Jeová, que este falara contra Baasa por intermédio de Jeú, o profeta,

[[v11-16-13]]

^<<v11-16-13,13>>^ por causa de todos os pecados de Baasa e dos pecados de Elá, seu filho, com que pecaram e com que fizeram Israel pecar, ofendendo a Jeová, o Deus de Israel, com os seus ídolos vãos.^&#42;1^

[NOTE]
====
. Lit.: “suas vaidades”.
====

[[v11-16-14]]

^<<v11-16-14,14>>^ Quanto ao resto dos assuntos de Elá e tudo o que ele fez, não estão escritos no livro dos assuntos dos dias dos reis de Israel?

[[v11-16-15]]

^<<v11-16-15,15>>^ No vigésimo sétimo ano de Asa, rei de Judá, Zinri tornou-se rei por sete dias em Tirza, enquanto o povo estava acampado contra Gibetom, que pertencia aos filisteus.

[[v11-16-16]]

^<<v11-16-16,16>>^ Então o povo que estava acampado ouviu dizer: “Zinri conspirou e também golpeou o rei.” Portanto, todo o Israel fez Onri, chefe do exército, rei sobre Israel naquele dia no acampamento.

[[v11-16-17]]

^<<v11-16-17,17>>^ Onri e todo o Israel com ele subiram então de Gibetom e começaram a sitiar Tirza.

[[v11-16-18]]

^<<v11-16-18,18>>^ E sucedeu que, assim que Zinri viu que a cidade tinha sido capturada, ele entrou então na torre de habitação da casa do rei e queimou com fogo a casa do rei sobre si mesmo, de modo que morreu

[[v11-16-19]]

^<<v11-16-19,19>>^ pelos seus pecados com que havia pecado, fazendo o que era mau aos olhos de Jeová por andar no caminho de Jeroboão e no seu pecado que cometeu, fazendo Israel pecar.

[[v11-16-20]]

^<<v11-16-20,20>>^ Quanto ao resto dos assuntos de Zinri, e sua conspiração com que conspirou, não estão escritos no livro dos assuntos dos dias dos reis de Israel?

[[v11-16-21]]

^<<v11-16-21,21>>^ Foi então que o povo de Israel começou a dividir-se em duas partes. Havia uma parte do povo que se tornou seguidores de Tibni, filho de Ginate, para fazê-lo rei, e a outra parte, seguidores de Onri.

[[v11-16-22]]

^<<v11-16-22,22>>^ Finalmente, o povo que seguia a Onri prevaleceu sobre o povo que seguia a Tibni, filho de Ginate; de modo que Tibni encontrou a morte e Onri começou a reinar.

[[v11-16-23]]

^<<v11-16-23,23>>^ No trigésimo primeiro ano de Asa, rei de Judá, Onri tornou-se rei^&#42;1^ sobre Israel por doze anos. Reinou em Tirza por seis anos.

[NOTE]
====
. “Tornou-se rei”, isto é, tornou-se governante exclusivo quando morreu seu rival, Tibni.
====

[[v11-16-24]]

^<<v11-16-24,24>>^ E ele passou a comprar de Semer o monte de Samaria^&#42;1^ por dois talentos^&#42;2^ de prata e começou a construir [no] monte, e a cidade que construiu ele chamou pelo nome de Semer, o senhor^&#42;3^ do monte: Samaria.

[NOTE]
====
. Significando “Pertencente ao Clã de Semer”. Hebr.: Sho·meróhn.
. Veja Ap. 8A.
. Ou “amo do”. Hebr.: ’adho·néh, pl. de ’a·dhóhn, para denotar excelência.
====

[[v11-16-25]]

^<<v11-16-25,25>>^ E Onri fazia o que era mau aos olhos de Jeová e veio a fazer pior do que todos os que o precederam.

[[v11-16-26]]

^<<v11-16-26,26>>^ E ele andava em todo o caminho de Jeroboão, filho de Nebate, e no seu pecado com que fez Israel pecar, ofendendo a Jeová, o Deus de Israel, com os seus ídolos vãos.

[[v11-16-27]]

^<<v11-16-27,27>>^ Quanto ao resto dos assuntos de Onri, o que ele fez e sua potência com que agiu, não estão escritos no livro dos assuntos dos dias dos reis de Israel?

[[v11-16-28]]

^<<v11-16-28,28>>^ Por fim, Onri deitou-se com os seus antepassados e foi enterrado em Samaria; e Acabe, seu filho, começou a reinar em seu lugar.

[[v11-16-29]]

^<<v11-16-29,29>>^ E quanto a Acabe, filho de Onri, tornou-se ele rei sobre Israel no trigésimo oitavo ano de Asa, rei de Judá; e Acabe, filho de Onri, continuou a reinar sobre Israel em Samaria por vinte e dois anos.

[[v11-16-30]]

^<<v11-16-30,30>>^ E Acabe, filho de Onri, passou a fazer pior aos olhos de Jeová do que todos os que o precederam.

[[v11-16-31]]

^<<v11-16-31,31>>^ E sucedeu que, [como se fosse] a coisa mais trivial andar ele nos pecados de Jeroboão, filho de Nebate, tomou então por esposa a Jezabel, filha de Etbaal, rei dos sidônios, e começou a ir e a servir Baal,^&#42;1^ e a curvar-se diante dele.

[NOTE]
====
. Lit.: “o Baal”. Hebr.: hab·Bá·‛al.
====

[[v11-16-32]]

^<<v11-16-32,32>>^ Além disso, erigiu um altar a Baal na casa de Baal, que construiu em Samaria.

[[v11-16-33]]

^<<v11-16-33,33>>^ E Acabe prosseguiu, fazendo o poste sagrado;^&#42;1^ e Acabe veio a fazer mais para ofender a Jeová, o Deus de Israel, do que todos os reis de Israel que vieram a ser antes dele.

[NOTE]
====
. Ou “a Axerá”. Hebr.: ha·’Ashe·ráh.
====

[[v11-16-34]]

^<<v11-16-34,34>>^ Nos seus dias, Hiel, o betelita, construiu Jericó. Lançou os alicerces dela com a perda de Abirão, seu primogênito, e com a perda de Segube, seu mais moço, pôs-lhe as portas, segundo a palavra de Jeová, que este havia falado por intermédio de Josué,^&#42;1^ filho de Num.

[NOTE]
====
. “Josué.” Hebr.: Yehoh·shú·a‛, “Jeosué”; LXX: “Jesus”.
====

'''

xref:011-1-reis/011-1-reis-015.adoc#v11-15-0[&#60; Capítulo Anterior] | <<v11-16-0,Topo>> | xref:011-1-reis/011-1-reis-017.adoc#v11-17-0[Próximo Capítulo &#62;]