include::./index.adoc[]

[[v11-12-0]]
=== 1 Reis, 12
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v11-12-1]]

^<<v11-12-1,1>>^ E Roboão passou a ir a Siquém, pois foi a Siquém que todo o Israel veio para fazê-lo rei.

[[v11-12-2]]

^<<v11-12-2,2>>^ E sucedeu que, assim que Jeroboão, filho de Nebate, ouviu isso enquanto ainda estava no Egito, (pois havia fugido por causa do Rei Salomão, para que Jeroboão morasse no Egito,)

[[v11-12-3]]

^<<v11-12-3,3>>^ então mandaram chamá-lo. Depois veio Jeroboão e toda a congregação de Israel, e começaram a falar a Roboão, dizendo:

[[v11-12-4]]

^<<v11-12-4,4>>^ “Teu pai, da sua parte, fez duro o nosso jugo, e tu, alivia agora o serviço duro de teu pai e seu jugo pesado que ele pôs sobre nós, e te serviremos.”

[[v11-12-5]]

^<<v11-12-5,5>>^ Então ele lhes disse: “Ide-vos por três dias e retornai a mim.” Portanto, o povo foi embora.

[[v11-12-6]]

^<<v11-12-6,6>>^ E o Rei Roboão começou a aconselhar-se com os anciãos que haviam assistido a Salomão, seu pai, enquanto estava vivo, dizendo: “Como aconselhais que se deve responder a este povo?”

[[v11-12-7]]

^<<v11-12-7,7>>^ Por conseguinte, falaram-lhe, dizendo: “Se hoje te mostrares servo deste povo e realmente os servires, então terás de responder-lhes e falar-lhes com boas palavras; e eles forçosamente se tornarão teus servos para sempre.”

[[v11-12-8]]

^<<v11-12-8,8>>^ No entanto, ele abandonou o conselho dos anciãos com que o tinham aconselhado e começou a aconselhar-se com os jovens que haviam crescido com ele, os quais eram os que assistiam a ele.

[[v11-12-9]]

^<<v11-12-9,9>>^ E prosseguiu, dizendo-lhes: “O que ofereceis vós como conselho para que respondamos a este povo que me falou, dizendo: ‘Alivia o jugo que teu pai pôs sobre nós’?”

[[v11-12-10]]

^<<v11-12-10,10>>^ Por sua vez, os jovens que haviam crescido com ele falaram-lhe, dizendo: “Isto é o que deves dizer a este povo que te falou, dizendo: ‘Teu pai, da sua parte, fez pesado o nosso jugo, mas tu, alivia-o para nós’; assim deves falar-lhes: ‘Meu próprio dedo mínimo há de ser mais grosso do que os quadris de meu pai.

[[v11-12-11]]

^<<v11-12-11,11>>^ E agora, meu pai, da sua parte, carregou-vos dum jugo pesado; mas eu, da minha parte, aumentarei o vosso jugo. Meu pai, da sua parte, castigou-vos com chicotes, mas eu, da minha parte, vos castigarei com azorragues.’”^&#42;1^

[NOTE]
====
. “Azorragues.” A palavra hebr. significa também “escorpiões”, como em De 8:15.
====

[[v11-12-12]]

^<<v11-12-12,12>>^ E Jeroboão e todo o povo passaram a vir a Roboão no terceiro dia, assim como o rei havia falado, dizendo: “Retornai a mim no terceiro dia.”

[[v11-12-13]]

^<<v11-12-13,13>>^ E o rei começou a responder ao povo rispidamente e a abandonar o conselho dos anciãos que o tinham aconselhado.

[[v11-12-14]]

^<<v11-12-14,14>>^ E foi falar-lhes segundo o conselho dos jovens, dizendo: “Meu pai, da sua parte, fez pesado o vosso jugo, mas eu, da minha parte, aumentarei o vosso jugo. Meu pai, da sua parte, castigou-vos com chicotes, mas eu, da minha parte, vos castigarei com azorragues.”

[[v11-12-15]]

^<<v11-12-15,15>>^ E o rei não escutou o povo, porque o desenvolvimento se deu da parte de Jeová, a fim de que pudesse deveras executar a sua palavra, que Jeová falara por intermédio de Aijá, o silonita, a Jeroboão, filho de Nebate.

[[v11-12-16]]

^<<v11-12-16,16>>^ Quando todo o Israel chegou a ver que o rei não os havia escutado, então o povo replicou ao rei, dizendo: “Que quinhão temos em Davi? E não há herança no filho de Jessé. Aos teus deuses,^&#42;1^ ó Israel. Olha agora pela tua própria casa, ó Davi!” Com isso Israel começou a ir para as suas tendas.

[NOTE]
====
. “Aos teus deuses.” Lit.: “Às tuas tendas.” Hebr.: le’o·ha·leí·kha. Uma das Dezoito Emendas dos soferins. Alega-se que o texto original hebr. tenha tido uma forma de ’elo·hím (“deuses”; ou: “Deus”), mas que os soferins judaicos, pela transposição de l e h, a segunda e a terceira consoante da palavra, fizeram com que o M rezasse “tendas”. Veja 2Sa 20:1 n.: “deuses”; 2Cr 10:16 n.; Ap. 2B.
====

[[v11-12-17]]

^<<v11-12-17,17>>^ Quanto aos filhos de Israel que moravam nas cidades de Judá, sobre estes Roboão continuou a reinar.

[[v11-12-18]]

^<<v11-12-18,18>>^ Subseqüentemente, o Rei Roboão enviou Adorão, que estava sobre os recrutados para o trabalho forçado, mas todo o Israel atirou pedras nele, de modo que morreu. E o próprio Rei Roboão conseguiu subir ao carro, a fim de fugir para Jerusalém.

[[v11-12-19]]

^<<v11-12-19,19>>^ E os israelitas têm persistido na sua revolta contra a casa de Davi até o dia de hoje.

[[v11-12-20]]

^<<v11-12-20,20>>^ E sucedeu que, assim que todo o Israel ouviu que Jeroboão tinha voltado, mandaram imediatamente chamá-lo à assembléia^&#42;1^ e o fizeram rei sobre todo o Israel. Ninguém ficou seguidor da casa de Davi, a não ser somente a tribo de Judá.

[NOTE]
====
. “Assembléia.” Gr.: sy·na·go·gén.
====

[[v11-12-21]]

^<<v11-12-21,21>>^ Quando Roboão chegou a Jerusalém, congregou imediatamente toda a casa de Judá e a tribo de Benjamim, cento e oitenta mil homens escolhidos, aptos para a guerra,^&#42;1^ para lutar contra a casa de Israel, a fim de fazer voltar o reinado a Roboão, filho de Salomão.

[NOTE]
====
. “Aptos para a guerra.” Lit.: “guerreando”.
====

[[v11-12-22]]

^<<v11-12-22,22>>^ Então veio a palavra do [verdadeiro] Deus^&#42;1^ a Semaías, homem do [verdadeiro] Deus, dizendo:

[NOTE]
====
. “Do [verdadeiro] Deus.” Hebr.: ha·’Elo·hím; LXXSyVg: “Jeová”.
====

[[v11-12-23]]

^<<v11-12-23,23>>^ “Dize a Roboão, filho de Salomão, rei de Judá, e a toda a casa de Judá e a Benjamim, e ao resto do povo:

[[v11-12-24]]

^<<v11-12-24,24>>^ ‘Assim disse Jeová: “Não deveis subir e lutar contra os vossos irmãos, os filhos de Israel. Voltai cada um para a sua casa, pois é da minha parte que esta coisa sucedeu.”’” Obedeceram, pois, à palavra de Jeová e retornaram para casa, segundo a palavra de Jeová.

[[v11-12-25]]

^<<v11-12-25,25>>^ E Jeroboão passou a construir Siquém na região montanhosa de Efraim e a morar nela. Então saiu de lá e construiu Penuel.

[[v11-12-26]]

^<<v11-12-26,26>>^ E Jeroboão começou a dizer no seu coração: “Agora retornará o reino à casa de Davi.

[[v11-12-27]]

^<<v11-12-27,27>>^ Se este povo continuar a subir para ofertar sacrifícios na casa de Jeová em Jerusalém, o coração deste povo forçosamente retornará ao seu senhor,^&#42;1^ Roboão, rei de Judá; e certamente me matarão e retornarão a Roboão, rei de Judá.”

[NOTE]
====
. “Seu senhor.” Hebr.: ’adho·neh·hém, pl. de ’a·dhóhn, para denotar excelência.
====

[[v11-12-28]]

^<<v11-12-28,28>>^ Conseqüentemente, o rei tomou conselho e fez dois bezerros de ouro, e disse ao povo:^&#42;1^ “É demais para vós subir a Jerusalém. Eis o teu Deus,^&#42;2^ ó Israel, que te fez subir da terra do Egito.”

[NOTE]
====
. “Ao povo”, LXXIt; Sy: “a todo o Israel”; MVg: “a eles”.
. Lit.: “os teus deuses”. Hebr.: ’elo·heí·kha, seguido pelo verbo hebr. para “fez” no pl. Veja Êx 32:1, 4 n.: “Deus”.
====

[[v11-12-29]]

^<<v11-12-29,29>>^ Então colocou um em Betel e o outro em Dã.

[[v11-12-30]]

^<<v11-12-30,30>>^ E esta coisa veio a ser causa de pecado, e o povo começou a ir [apresentar-se] perante um até Dã.

[[v11-12-31]]

^<<v11-12-31,31>>^ E ele começou a fazer uma casa de altos e a constituir sacerdotes dentre o povo em geral, os quais não vieram a ser dos filhos de Levi.

[[v11-12-32]]

^<<v11-12-32,32>>^ E Jeroboão foi realizar uma festividade no oitavo mês, no décimo quinto dia do mês, igual à festividade que havia em Judá, para fazer ofertas sobre o altar que fizera em Betel, a fim de oferecer sacrifícios aos bezerros que fizera; e estabeleceu em Betel os sacerdotes dos altos que tinha feito.

[[v11-12-33]]

^<<v11-12-33,33>>^ E começou a fazer ofertas sobre o altar que fizera em Betel, no décimo quinto dia do oitavo mês, no mês que ele mesmo^&#42;1^ inventara; e passou a realizar uma festividade para os filhos de Israel e a fazer ofertas sobre o altar para fazer fumaça sacrificial.

[NOTE]
====
. “Ele mesmo.” Mmargem: “no seu coração”.
====

'''

xref:011-1-reis/011-1-reis-011.adoc#v11-11-0[&#60; Capítulo Anterior] | <<v11-12-0,Topo>> | xref:011-1-reis/011-1-reis-013.adoc#v11-13-0[Próximo Capítulo &#62;]