include::./index.adoc[]

[[v11-14-0]]
=== 1 Reis, 14
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v11-14-1]]

^<<v11-14-1,1>>^ Naquele tempo específico adoeceu Abias, filho de Jeroboão.

[[v11-14-2]]

^<<v11-14-2,2>>^ Jeroboão disse, pois, à sua esposa: “Por favor, levanta-te, e tens de disfarçar-te para que não saibam que és esposa de Jeroboão, e tens de ir a Silo. Eis que é ali que está Aijá, o profeta. Foi ele quem falou referente a mim quanto a tornar-me rei^&#42;1^ sobre este povo.

[NOTE]
====
. “Quanto a tornar-me rei”, LXXASyVg; M: “como rei”.
====

[[v11-14-3]]

^<<v11-14-3,3>>^ E tens de tomar na mão dez pães, e bolos borrifados, e uma botija de mel, e tens de entrar até ele. É ele quem te há de dizer o que vai acontecer ao menino.”

[[v11-14-4]]

^<<v11-14-4,4>>^ E a esposa de Jeroboão passou a fazer assim. Por conseguinte, ela se levantou e foi a Silo, e chegou à casa de Aijá. Ora, o próprio Aijá^&#42;1^ não podia ver, pois os seus olhos estavam parados por causa da sua idade.

[NOTE]
====
. “Ora, . . . Aijá.” Hebr.: wa·’Ahhi·yá·hu.
====

[[v11-14-5]]

^<<v11-14-5,5>>^ E o próprio Jeová havia dito a Aijá: “Eis que vem a esposa de Jeroboão para solicitar uma palavra tua referente ao seu filho, pois está doente. Assim e assim é que lhe deves falar. E sucederá^&#42;1^ que, assim que ela chegar, far-se-á irreconhecível.”

[NOTE]
====
. Ou: “E suceda.”
====

[[v11-14-6]]

^<<v11-14-6,6>>^ E aconteceu que, assim que Aijá ouviu o som dos pés dela, chegando ela à entrada, começou a dizer: “Entra, ó esposa de Jeroboão. Por que te fazes irreconhecível quando estou sendo enviado a ti com uma mensagem dura?

[[v11-14-7]]

^<<v11-14-7,7>>^ Vai, dize a Jeroboão: ‘Assim disse Jeová, o Deus de Israel: “Visto que eu te ergui do meio do teu povo para te constituir líder do meu povo Israel,

[[v11-14-8]]

^<<v11-14-8,8>>^ e fui arrancar o reino da casa de Davi e dá-lo a ti, e tu não te tornaste igual ao meu servo Davi, que guardou os meus mandamentos e que andou atrás de mim de todo o seu coração, fazendo somente o que era direito aos meus olhos,

[[v11-14-9]]

^<<v11-14-9,9>>^ mas tu começaste a agir pior do que todos os que vieram a ser antes de ti, e foste e fizeste para ti outro deus^&#42;1^ e imagens fundidas para me ofender, e sou eu a quem lançaste atrás das tuas costas,

[NOTE]
====
. Lit.: “outros deuses”. Hebr.: ’elo·hím ’ahhe·rím. Veja 12:28 n.: “Deus”.
====

[[v11-14-10]]

^<<v11-14-10,10>>^ por esta razão, eis que trago calamidade sobre a casa de Jeroboão, e certamente deceparei de Jeroboão aquele que urina contra o muro,^&#42;1^ o incapacitado e o rejeitado em Israel;^&#42;2^ e farei deveras uma varredura atrás da casa de Jeroboão, assim como se varre o esterco até se dar cabo dele.

[NOTE]
====
. “Que urina contra o muro.” Esta é uma expressão idiomática hebr. referindo-se a varões.
. Lit.: “o restrito e o largado (abandonado) em Israel”. Veja De 32:36 n.: “rejeitado”.
====

[[v11-14-11]]

^<<v11-14-11,11>>^ Quem de Jeroboão morrer na cidade, os cães devorarão, e quem morrer no campo, as aves dos céus comerão, porque o próprio Jeová o falou.”’

[[v11-14-12]]

^<<v11-14-12,12>>^ “E tu mesma, levanta-te, vai para a tua casa. Quando os teus pés entrarem na cidade, a criança certamente morrerá.

[[v11-14-13]]

^<<v11-14-13,13>>^ E todo o Israel deveras o lamentará e o enterrará, porque só este de Jeroboão entrará numa sepultura, visto que nele se achou algo de bom para com Jeová, o Deus de Israel, na casa de Jeroboão.

[[v11-14-14]]

^<<v11-14-14,14>>^ E Jeová certamente suscitará para si um rei sobre Israel, o qual decepará a casa de Jeroboão naquele dia, e quem sabe, agora mesmo?

[[v11-14-15]]

^<<v11-14-15,15>>^ E Jeová deveras golpeará Israel, assim como a cana balança na água; e ele certamente desarraigará Israel deste solo bom que deu aos seus antepassados e deveras os espalhará além do Rio,^&#42;1^ por terem feito os postes sagrados deles, ofendendo assim a Jeová.

[NOTE]
====
. Isto é, o Eufrates.
====

[[v11-14-16]]

^<<v11-14-16,16>>^ E ele entregará Israel por causa dos pecados de Jeroboão com que este pecou e com que fez Israel pecar.”

[[v11-14-17]]

^<<v11-14-17,17>>^ Então se levantou a esposa de Jeroboão e foi embora, e chegou a Tirza. Quando chegou ao limiar da casa, o rapaz morreu.

[[v11-14-18]]

^<<v11-14-18,18>>^ Enterraram-no, pois, e todo o Israel lamentava-o, segundo a palavra de Jeová, que ele havia falado por intermédio do seu servo Aijá, o profeta.

[[v11-14-19]]

^<<v11-14-19,19>>^ E o resto dos assuntos de Jeroboão, como ele guerreou e como reinou, eis que estão escritos no livro dos assuntos dos dias dos reis de Israel.

[[v11-14-20]]

^<<v11-14-20,20>>^ E os dias que Jeroboão reinou foram vinte e dois anos, após os quais se deitou com os seus antepassados; e Nadabe, seu filho, começou a reinar em seu lugar.

[[v11-14-21]]

^<<v11-14-21,21>>^ Quanto a Roboão, filho de Salomão, tornara-se rei em Judá. Roboão tinha quarenta e um anos de idade quando começou a reinar e reinou dezessete anos em Jerusalém, a cidade que Jeová escolhera dentre todas as tribos de Israel para pôr ali seu nome. E o nome de sua mãe era Naamá, a amonita.

[[v11-14-22]]

^<<v11-14-22,22>>^ E Judá prosseguiu fazendo o que era mau aos olhos de Jeová, de modo que o provocaram mais ao ciúme do que tudo o que os seus antepassados tinham feito por meio dos seus pecados com que pecaram.

[[v11-14-23]]

^<<v11-14-23,23>>^ E também construíam para si altos, e colunas sagradas, e postes sagrados sobre todo morro elevado e debaixo de cada árvore frondosa.

[[v11-14-24]]

^<<v11-14-24,24>>^ E até mesmo veio a haver no país homem que se prostituía no serviço dum templo.^&#42;1^ Agiam de acordo com todas as coisas detestáveis das nações que Jeová tinha desalojado de diante dos filhos de Israel.

[NOTE]
====
. “Homem que se prostituía no serviço dum templo.” Hebr.: qa·dhésh; lat.: ef·fe·mi·ná·ti, “efeminados”.
====

[[v11-14-25]]

^<<v11-14-25,25>>^ E sucedeu no quinto ano do Rei Roboão que Sisaque, rei do Egito, subiu contra Jerusalém.

[[v11-14-26]]

^<<v11-14-26,26>>^ E ele foi tirar os tesouros da casa de Jeová e os tesouros da casa do rei; e tomou tudo. E foi tomar todos os escudos de ouro que Salomão tinha feito.

[[v11-14-27]]

^<<v11-14-27,27>>^ Por conseguinte, o Rei Roboão fez em lugar deles escudos de cobre e os entregou aos cuidados dos chefes dos batedores, os guardas da entrada da casa do rei.

[[v11-14-28]]

^<<v11-14-28,28>>^ E acontecia que, sempre que o rei vinha à casa de Jeová, os batedores os carregavam, e os devolviam à sala da guarda dos batedores.

[[v11-14-29]]

^<<v11-14-29,29>>^ E o resto dos assuntos de Roboão e tudo o que ele fez, não estão escritos no livro dos assuntos dos tempos dos reis de Judá?

[[v11-14-30]]

^<<v11-14-30,30>>^ E sucedeu haver sempre guerra entre Roboão e Jeroboão.

[[v11-14-31]]

^<<v11-14-31,31>>^ Por fim, Roboão deitou-se com os seus antepassados e foi enterrado com os seus antepassados na Cidade de Davi. E o nome de sua mãe era Naamá, a amonita. E Abijão,^&#42;1^ seu filho, começou a reinar em seu lugar.

[NOTE]
====
. “Abijão”, MVg; cerca de 12 mss. hebr. e a edição Bomberg da Bíblia hebraica (1524-1525 EC), de Jacob ben Hayim: “Abias”.
====

'''

xref:011-1-reis/011-1-reis-013.adoc#v11-13-0[&#60; Capítulo Anterior] | <<v11-14-0,Topo>> | xref:011-1-reis/011-1-reis-015.adoc#v11-15-0[Próximo Capítulo &#62;]