include::./index.adoc[]

[[v11-11-0]]
=== 1 Reis, 11
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v11-11-1]]

^<<v11-11-1,1>>^ E o próprio Rei Salomão amava muitas mulheres estrangeiras além da filha de Faraó, mulheres moabitas, amonitas, edomitas, sidônias [e] hititas,

[[v11-11-2]]

^<<v11-11-2,2>>^ das nações de que Jeová havia dito aos filhos de Israel: “Não deveis entrar no meio delas e elas mesmas não devem entrar no vosso meio; decerto inclinarão o vosso coração a seguir os seus deuses.” Foi a elas que Salomão se apegou para [as] amar.

[[v11-11-3]]

^<<v11-11-3,3>>^ E ele veio a ter setecentas esposas, princesas, e trezentas concubinas; e suas esposas gradualmente lhe inclinaram o coração.

[[v11-11-4]]

^<<v11-11-4,4>>^ E sucedeu, no tempo da velhice de Salomão, que as próprias esposas dele lhe haviam inclinado o coração para seguir outros deuses; e seu coração não se mostrou pleno para com Jeová, seu Deus, como o coração de Davi, seu pai.

[[v11-11-5]]

^<<v11-11-5,5>>^ E Salomão começou a ir atrás de Astorete, deusa^&#42;1^ dos sidônios, e atrás de Milcom, a coisa repugnante dos amonitas.

[NOTE]
====
. “Deusa dos.” Hebr.: ’elo·héh, pl. de ’elóh·ah, para denotar excelência. Masc. no hebr., mas aqui aplicado a uma deidade feminina.
====

[[v11-11-6]]

^<<v11-11-6,6>>^ E Salomão começou a fazer o que era mau aos olhos de Jeová e não seguiu plenamente a Jeová como Davi, seu pai.

[[v11-11-7]]

^<<v11-11-7,7>>^ Foi então que Salomão passou a construir um alto a Quemós, a coisa repugnante de Moabe, no monte que estava defronte de Jerusalém, e a Moloque, a coisa repugnante dos filhos de Amom.

[[v11-11-8]]

^<<v11-11-8,8>>^ E foi assim que ele fez para todas as suas esposas estrangeiras que faziam fumaça sacrificial e ofereciam sacrifícios aos seus deuses.

[[v11-11-9]]

^<<v11-11-9,9>>^ E Jeová ficou irado com Salomão, porque seu coração se tinha inclinado para longe de Jeová, o Deus de Israel, aquele que lhe aparecera duas vezes.

[[v11-11-10]]

^<<v11-11-10,10>>^ E com respeito a esta coisa ordenara-lhe que não fosse atrás de outros deuses; mas ele não havia guardado o que Jeová ordenara.

[[v11-11-11]]

^<<v11-11-11,11>>^ Jeová disse então a Salomão: “Visto que se deu isto contigo e por não teres guardado o meu pacto e os meus estatutos que te impus como ordem, sem falta arrancarei de ti o reino e o hei de dar ao teu servo.

[[v11-11-12]]

^<<v11-11-12,12>>^ No entanto, não o farei nos teus dias, por causa de Davi, teu pai. Da mão do teu filho o arrancarei.

[[v11-11-13]]

^<<v11-11-13,13>>^ Apenas não arrancarei todo o reino. Darei uma tribo ao teu filho, por causa de Davi, meu servo, e por causa de Jerusalém que escolhi.”

[[v11-11-14]]

^<<v11-11-14,14>>^ E Jeová começou a suscitar a Salomão um opositor,^&#42;1^ a saber, Hadade, o edomita, da descendência do rei. Ele estava em Edom.

[NOTE]
====
. “Um opositor.” Hebr. e gr.: sa·tán; sir.: sa·ta·na’, “o opositor”; Vg: “adversário”.
====

[[v11-11-15]]

^<<v11-11-15,15>>^ E havia sucedido que, quando Davi golpeou Edom,^&#42;1^ quando Joabe, chefe do exército, subiu para enterrar os que foram mortos, ele tentou golpear todo macho em Edom.

[NOTE]
====
. “Quando Davi golpeou Edom”, mediante uma ligeira emenda para concordar com LXXSy; M: “quando Davi veio a estar com Edom”.
====

[[v11-11-16]]

^<<v11-11-16,16>>^ (Pois foi por seis meses que Joabe e todo o Israel moraram ali até terem decepado todo macho em Edom.)

[[v11-11-17]]

^<<v11-11-17,17>>^ E Hadade pusera-se em fuga, ele e alguns homens edomitas dos servos de seu pai com ele, para entrarem no Egito, enquanto Hadade era ainda um rapazinho pequeno.^&#42;1^

[NOTE]
====
. Lit.: “jovem”.
====

[[v11-11-18]]

^<<v11-11-18,18>>^ Levantaram-se, pois, de Midiã e entraram em Parã, e tomaram consigo homens de Parã e entraram no Egito, [chegando] a Faraó, rei do Egito, que lhe deu então uma casa. Também lhe proporcionou pão e lhe deu terra.

[[v11-11-19]]

^<<v11-11-19,19>>^ E Hadade continuou a achar favor aos olhos de Faraó, tanto assim que lhe deu uma esposa, a irmã de sua própria esposa, a irmã de Tafnes, a senhora.

[[v11-11-20]]

^<<v11-11-20,20>>^ Com o tempo, a irmã de Tafnes lhe deu à luz Genubate, seu filho, e Tafnes foi desmamá-lo na própria casa de Faraó; e Genubate continuou na casa de Faraó no meio dos filhos de Faraó.

[[v11-11-21]]

^<<v11-11-21,21>>^ E o próprio Hadade ouviu no Egito que Davi se tinha deitado com os seus antepassados e que Joabe, chefe do exército, tinha morrido. Por isso Hadade disse a Faraó: “Manda-me embora, para que eu vá para a minha própria terra.”

[[v11-11-22]]

^<<v11-11-22,22>>^ O Faraó, porém, lhe disse: “De que careces enquanto estás comigo, que estás procurando ir para a tua própria terra?” A isto ele disse: “Nada; mas deves decididamente mandar-me embora.”

[[v11-11-23]]

^<<v11-11-23,23>>^ E Deus passou a suscitar-lhe outro opositor, a saber, Rezom, filho de Eliada, que havia fugido de Hadadezer, rei de Zobá, seu senhor.^&#42;1^

[NOTE]
====
. “Seu senhor.” Hebr.: ’adho·náv; pl. de ’a·dhóhn, para denotar excelência.
====

[[v11-11-24]]

^<<v11-11-24,24>>^ E ele foi reunir a si homens e veio a ser chefe duma guerrilha, quando Davi os^&#42;1^ matou. De modo que foram para Damasco e passaram a morar nela, e começaram a reinar em Damasco.

[NOTE]
====
. “Os”, M; mediante uma correção no M: “Síria”.
====

[[v11-11-25]]

^<<v11-11-25,25>>^ E ele veio a ser opositor de Israel em todos os dias de Salomão, e isso além do mal que Hadade causava; e ele abominava Israel enquanto reinava sobre a Síria.

[[v11-11-26]]

^<<v11-11-26,26>>^ E havia Jeroboão, filho de Nebate, efraimita de Zereda, servo de Salomão, e o nome de sua mãe era Zerua, uma mulher enviuvada. Ele também começou a erguer a mão contra o rei.

[[v11-11-27]]

^<<v11-11-27,27>>^ E a seguinte foi a razão porque ergueu a mão contra o rei: o próprio Salomão tinha construído o Aterro.^&#42;1^ Tinha fechado a brecha da Cidade de Davi, seu pai.

[NOTE]
====
. “O Aterro.” Hebr.: ham·mil·lóh’. Veja 9:15 n.
====

[[v11-11-28]]

^<<v11-11-28,28>>^ Ora, o homem Jeroboão era homem valente, poderoso. E vendo Salomão que o moço era trabalhador árduo, passou a encarregá-lo^&#42;1^ de todo o serviço compulsório da casa de José.

[NOTE]
====
. “Passou a encarregá-lo.” Hebr.: wai·yaf·qédh ’o·thóh.
====

[[v11-11-29]]

^<<v11-11-29,29>>^ E sucedeu, naquele tempo específico, que o próprio Jeroboão estava saindo de Jerusalém, e Aijá, o silonita, o profeta, foi encontrá-lo na estrada, e [Aijá]^&#42;1^ se cobria com um manto novo; e os dois estavam sozinhos no campo.

[NOTE]
====
. “Aijá”, LXXSy; MVg: “ele”.
====

[[v11-11-30]]

^<<v11-11-30,30>>^ Aijá pegou então no manto novo que vestia e o rasgou em doze pedaços.

[[v11-11-31]]

^<<v11-11-31,31>>^ E prosseguiu, dizendo a Jeroboão:
“Toma para ti dez pedaços; pois assim disse Jeová, o Deus de Israel: ‘Eis que arranco o reino da mão de Salomão e hei de dar-te dez tribos.

[[v11-11-32]]

^<<v11-11-32,32>>^ E é uma tribo que continuará a ser dele por causa do meu servo Davi e por causa de Jerusalém, a cidade que escolhi dentre todas as tribos de Israel.

[[v11-11-33]]

^<<v11-11-33,33>>^ A razão é que me deixaram e começaram a curvar-se diante de Astorete, a deusa^&#42;1^ dos sidônios, e diante de Quemós, o deus^&#42;2^ de Moabe, e diante de Milcom, o deus dos filhos de Amom; e não andaram nos meus caminhos para fazerem o que é direito aos meus olhos, e meus estatutos e minhas decisões judiciais, assim como Davi, pai dele.

[NOTE]
====
. Veja o v. 5 n.
. “O deus de.” Hebr.: ’elo·héh, pl. de ’elóh·ah, aplicado a uma deidade pagã. Veja Jz 16:23 n.
====

[[v11-11-34]]

^<<v11-11-34,34>>^ Mas, não tirarei o reino inteiro da sua mão, porque eu o porei por maioral^&#42;1^ todos os dias da sua vida, por causa de Davi, meu servo, a quem escolhi, pois guardou os meus mandamentos e os meus estatutos.

[NOTE]
====
. Ou “nase”.
====

[[v11-11-35]]

^<<v11-11-35,35>>^ E hei de tirar o reinado da mão de seu filho e dá-lo a ti, sim, dez tribos.

[[v11-11-36]]

^<<v11-11-36,36>>^ E ao filho dele darei uma tribo, a fim de que Davi, meu servo, continue a ter sempre uma lâmpada diante de mim em Jerusalém, a cidade que escolhi para mim, a fim de pôr ali o meu nome.

[[v11-11-37]]

^<<v11-11-37,37>>^ E é a ti que tomarei, e tu reinarás deveras sobre tudo o que a tua alma almejar e hás de tornar-te rei sobre Israel.

[[v11-11-38]]

^<<v11-11-38,38>>^ E terá de acontecer que, se obedeceres a tudo o que eu te mandar, e se deveras andares nos meus caminhos e realmente fizeres o que é direito aos meus olhos, guardando os meus estatutos e os meus mandamentos, assim como fez Davi, meu servo, então vou mostrar que estou contigo e vou edificar-te uma casa duradoura, assim como edifiquei para Davi, e vou dar-te Israel.

[[v11-11-39]]

^<<v11-11-39,39>>^ E humilharei a descendência de Davi por causa disso, apenas não para sempre.’”

[[v11-11-40]]

^<<v11-11-40,40>>^ E Salomão começou a procurar entregar Jeroboão à morte. Portanto, Jeroboão se levantou e se pôs em fuga para o Egito, indo ter com Sisaque, rei do Egito, e ficou no Egito até a morte de Salomão.

[[v11-11-41]]

^<<v11-11-41,41>>^ Quanto ao resto dos assuntos de Salomão, e a tudo o que fez e à sua sabedoria, não estão escritos no livro dos assuntos de Salomão?

[[v11-11-42]]

^<<v11-11-42,42>>^ E os dias que Salomão reinou em Jerusalém sobre todo o Israel foram quarenta anos.

[[v11-11-43]]

^<<v11-11-43,43>>^ Salomão deitou-se então com os seus antepassados e foi enterrado na Cidade de Davi, seu pai; e Roboão, seu filho, começou a reinar em seu lugar.

'''

xref:011-1-reis/011-1-reis-010.adoc#v11-10-0[&#60; Capítulo Anterior] | <<v11-11-0,Topo>> | xref:011-1-reis/011-1-reis-012.adoc#v11-12-0[Próximo Capítulo &#62;]