include::./index.adoc[]

[[v11-1-0]]
=== 1 Reis, 1
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

_ou, segundo a Versão dos Setenta grega: O TERCEIRO DOS REIS_

[[v11-1-1]]

^<<v11-1-1,1>>^ Ora, o Rei^&#42;1^ Davi era idoso, avançado em dias; e cobriam-no com vestes, mas não se aquecia.

[NOTE]
====
. “Ora, o Rei.” Hebr.: weham·mé·lekh, sing.
====

[[v11-1-2]]

^<<v11-1-2,2>>^ Disseram-lhe, pois, os seus servos: “Procure-se uma moça, uma virgem, para meu senhor, o rei, e ela terá de assistir diante do rei, tornando-se sua enfermeira; e terá de deitar-se ao teu seio, e meu senhor, o rei, certamente se aquecerá.”

[[v11-1-3]]

^<<v11-1-3,3>>^ E foram^&#42;1^ procurar uma moça bela em todo o território de Israel, e por fim acharam Abisague, a sunamita, e trouxeram-na então para dentro ao rei.

[NOTE]
====
. Não se refere aos “servos” do v. 2, mas aos mandados a fazer a busca.
====

[[v11-1-4]]

^<<v11-1-4,4>>^ E a moça era extremamente bela; e ela veio a ser a enfermeira do rei e servia-o, e o próprio rei não teve relações com ela.

[[v11-1-5]]

^<<v11-1-5,5>>^ Entrementes se erguia Adonias, filho de Hagite, dizendo: “Eu é que reinarei!” E ele passou a mandar fazer para si um carro, com cavaleiros e cinqüenta homens correndo na sua frente.

[[v11-1-6]]

^<<v11-1-6,6>>^ E seu pai não lhe feriu nenhuma vez^&#42;1^ a suscetibilidade, dizendo: “Por que procedeste assim?” E ele tinha também muito boa figura, e [sua mãe]^&#42;2^ o havia dado à luz depois de Absalão.

[NOTE]
====
. Ou “em toda a sua vida”. Lit.: “desde os seus dias (anos)”.
. Lit.: “ela”.
====

[[v11-1-7]]

^<<v11-1-7,7>>^ E ele veio a ter entendimentos com Joabe, filho de Zeruia, e com Abiatar, o sacerdote, e eles começaram a oferecer ajuda como seguidores de Adonias.

[[v11-1-8]]

^<<v11-1-8,8>>^ Quanto a Zadoque, o sacerdote, e Benaia,^&#42;1^ filho de Jeoiada, e Natã, o profeta, e Simei e Reí, e os poderosos que pertenciam a Davi, não ficaram envolvidos com Adonias.^&#42;2^

[NOTE]
====
. “E Benaia.” Hebr.: u·Vena·yá·hu.
. “Adonias.” Hebr.: ’Adho·ni·yá·hu.
====

[[v11-1-9]]

^<<v11-1-9,9>>^ Por fim, Adonias ofereceu sacrifícios de ovelhas e de gado vacum, e de animais cevados, junto à pedra de Zoelete,^&#42;1^ que está junto a En-Rogel, e passou a convidar todos os seus irmãos, os filhos do rei, e todos os homens de Judá, os servos do rei;

[NOTE]
====
. Ou “a Pedra Deslizante”.
====

[[v11-1-10]]

^<<v11-1-10,10>>^ e não convidou Natã, o profeta, nem Benaia e os poderosos, nem Salomão, seu irmão.

[[v11-1-11]]

^<<v11-1-11,11>>^ Natã disse então a Bate-Seba, mãe de Salomão: “Não ouviste que Adonias, filho de Hagite, se tornou rei, e nosso senhor^&#42;1^ Davi não sabe disso?

[NOTE]
====
. “E nosso senhor.” Hebr.: wa·’adho·néh·nu, pl. de ’a·dhóhn, para denotar excelência. Veja Gên 39:2 n.
====

[[v11-1-12]]

^<<v11-1-12,12>>^ Portanto, vem agora, por favor, deixa-me aconselhar-te solenemente. E põe a salvo a tua própria alma e a alma de teu filho, Salomão.

[[v11-1-13]]

^<<v11-1-13,13>>^ Vai e entra até o Rei Davi, e tens de dizer-lhe: ‘Não foste tu, meu senhor, o rei, que juraste à tua escrava, dizendo: “Salomão, teu filho, é quem se tornará rei depois de mim e é ele quem se assentará no meu trono”? Então, por que se tornou Adonias rei?’

[[v11-1-14]]

^<<v11-1-14,14>>^ Eis que enquanto ainda estiveres falando lá com o rei, entrarei então eu depois de ti e certamente confirmarei as tuas palavras.”

[[v11-1-15]]

^<<v11-1-15,15>>^ Conseqüentemente, Bate-Seba entrou até o rei no quarto interior, e o rei era muito idoso, e Abisague, a sunamita, servia o rei.

[[v11-1-16]]

^<<v11-1-16,16>>^ Bate-Seba inclinou-se então e prostrou-se diante do rei, a que o rei disse: “Que tens [a pedir]?”

[[v11-1-17]]

^<<v11-1-17,17>>^ Então ela lhe disse: “Meu senhor, foste tu que juraste à tua escrava por Jeová, teu Deus: ‘Salomão, teu filho, é quem se tornará rei depois de mim e é ele quem se assentará no meu trono.’

[[v11-1-18]]

^<<v11-1-18,18>>^ E agora, eis que o próprio Adonias se tornou rei, e agora meu senhor, o próprio rei, não sabe disso.

[[v11-1-19]]

^<<v11-1-19,19>>^ Assim, ele sacrificou touros e animais cevados, bem como ovelhas, em grande quantidade, e convidou todos os filhos do rei, bem como Abiatar, o sacerdote, e Joabe, chefe do exército; mas não convidou Salomão, teu servo.

[[v11-1-20]]

^<<v11-1-20,20>>^ E tu, meu senhor, o rei — em ti estão os olhos de todo o Israel, para dizer-lhes quem vai sentar-se no trono de meu senhor, o rei, depois dele.

[[v11-1-21]]

^<<v11-1-21,21>>^ E certamente se dará que assim que meu senhor, o rei, se deitar com os seus antepassados, eu mesma e também meu filho Salomão havemos de tornar-nos ofensores.”

[[v11-1-22]]

^<<v11-1-22,22>>^ E eis que enquanto ela ainda falava com o rei, entrou o próprio Natã, o profeta.

[[v11-1-23]]

^<<v11-1-23,23>>^ Informaram imediatamente o rei, dizendo: “Aí está Natã, o profeta!” Depois ele entrou perante o rei e prostrou-se diante do rei com o rosto por terra.

[[v11-1-24]]

^<<v11-1-24,24>>^ Natã disse então: “Meu senhor, o rei, foste tu quem disseste: ‘É Adonias quem se tornará rei depois de mim e é ele quem se assentará no meu trono’?

[[v11-1-25]]

^<<v11-1-25,25>>^ Pois ele desceu hoje para sacrificar touros e animais cevados, bem como ovelhas, em grande quantidade, e para convidar todos os filhos do rei e os chefes do exército, e Abiatar, o sacerdote; e eis que estão comendo e bebendo diante dele, e estão dizendo: ‘Viva o Rei Adonias!’

[[v11-1-26]]

^<<v11-1-26,26>>^ Mas quanto a mim, teu servo, a mim e a Zadoque, o sacerdote, e a Benaia, filho de Jeoiada, e a Salomão, teu servo, não convidou.

[[v11-1-27]]

^<<v11-1-27,27>>^ Se esta coisa procede de meu senhor, o rei, então não fizeste teu servo saber quem se deve assentar no trono de meu senhor, o rei, depois dele.”

[[v11-1-28]]

^<<v11-1-28,28>>^ O Rei Davi respondeu então e disse: “Chamai-me a Bate-Seba.” Então ela entrou perante o rei e ficou de pé diante do rei.

[[v11-1-29]]

^<<v11-1-29,29>>^ E o rei passou a jurar e a dizer: “Por Jeová que vive, que remiu a minha alma de toda aflição,

[[v11-1-30]]

^<<v11-1-30,30>>^ assim como te jurei por Jeová, o Deus de Israel, dizendo: ‘Salomão, teu filho, é quem se tornará rei depois de mim e é ele quem se assentará no meu trono em meu lugar!’ assim farei neste dia.”

[[v11-1-31]]

^<<v11-1-31,31>>^ Então Bate-Seba se inclinou com o rosto por terra e se prostrou diante do rei, e ela disse: “Viva meu senhor, o Rei Davi, por tempo indefinido!”

[[v11-1-32]]

^<<v11-1-32,32>>^ O Rei Davi disse imediatamente: “Chamai-me a Zadoque, o sacerdote, e a Natã, o profeta, e a Benaia, filho de Jeoiada.” Eles entraram, pois, perante o rei.

[[v11-1-33]]

^<<v11-1-33,33>>^ E o rei prosseguiu, dizendo-lhes: “Tomai convosco os servos de vosso senhor^&#42;1^ e tereis de fazer Salomão, meu filho, montar na mula que me pertence e tereis de conduzi-lo para baixo a Giom.

[NOTE]
====
. Veja v. 11 n.
====

[[v11-1-34]]

^<<v11-1-34,34>>^ E Zadoque, o sacerdote, e Natã, o profeta, terão de ungi-lo rei sobre Israel; e tereis de tocar a buzina e dizer: ‘Viva o Rei Salomão!’

[[v11-1-35]]

^<<v11-1-35,35>>^ E tereis de subir atrás dele, e ele terá de entrar e sentar-se no meu trono; e ele mesmo será rei em meu lugar e é a ele que terei de comissionar para se tornar líder de Israel e de Judá.”

[[v11-1-36]]

^<<v11-1-36,36>>^ Benaia, filho de Jeoiada, respondeu imediatamente ao rei e disse: “Amém!^&#42;1^ Assim diga^&#42;2^ Jeová, o Deus de meu senhor, o rei.

[NOTE]
====
. Ou: “Assim seja!” Hebr.: ’a·mén.
. “Diga”, MVg; Sy e dois mss. hebr.: “faça”.
====

[[v11-1-37]]

^<<v11-1-37,37>>^ Assim como Jeová se mostrou com o meu senhor, o rei, assim se mostre com Salomão, e faça ele seu trono maior do que o trono de meu senhor, o Rei Davi.”

[[v11-1-38]]

^<<v11-1-38,38>>^ E Zadoque, o sacerdote, e Natã, o profeta, e Benaia, filho de Jeoiada, e os queretitas e os peletitas passaram a descer e a fazer Salomão montar na mula do Rei Davi e então o levaram a Giom.

[[v11-1-39]]

^<<v11-1-39,39>>^ Zadoque, o sacerdote, tomou então da tenda o chifre de óleo e ungiu Salomão; e começaram a tocar a buzina, e todo o povo irrompeu em dizer: “Viva o Rei Salomão!”

[[v11-1-40]]

^<<v11-1-40,40>>^ Depois, todo o povo subiu atrás dele, e o povo tocava flautas e alegrava-se com grande gozo, de modo que a terra se fendeu com o alarido deles.

[[v11-1-41]]

^<<v11-1-41,41>>^ E Adonias e todos os convidados que estavam com ele chegaram a ouvi-lo quando eles mesmos acabaram de comer. Quando Joabe chegou a ouvir o som da buzina, disse imediatamente: “Que significa o alarido da vila em alvoroço?”

[[v11-1-42]]

^<<v11-1-42,42>>^ Enquanto ainda falava, eis que vinha Jonatã, filho de Abiatar, o sacerdote. Adonias disse então: “Entra, pois és um homem valente e trazes boas novas.”

[[v11-1-43]]

^<<v11-1-43,43>>^ Mas Jonatã respondeu e disse a Adonias: “Não! Nosso senhor,^&#42;1^ o próprio Rei Davi, fez Salomão rei.

[NOTE]
====
. Veja v. 11 n.
====

[[v11-1-44]]

^<<v11-1-44,44>>^ Assim, o rei enviou com ele Zadoque, o sacerdote, e Natã, o profeta, e Benaia, filho de Jeoiada, bem como os queretitas e os peletitas, e fizeram-no montar na mula do rei.

[[v11-1-45]]

^<<v11-1-45,45>>^ Então Zadoque, o sacerdote, e Natã, o profeta, ungiram-no rei em Giom; depois subiram de lá alegrando-se, e a vila está em alvoroço. Este foi o alarido que ouvistes.

[[v11-1-46]]

^<<v11-1-46,46>>^ E, além disso, Salomão se assentou no trono do reinado.

[[v11-1-47]]

^<<v11-1-47,47>>^ E outra coisa, os servos do rei entraram para congratular o nosso senhor, o Rei Davi, dizendo: ‘Teu Deus^&#42;1^ faça o nome de Salomão mais esplêndido do que o teu nome e faça-lhe o trono maior do que o teu trono!’ Então o rei prostrou-se sobre a sua cama.

[NOTE]
====
. “Teu Deus”, M; MmargemLXXVg: “Deus”; Sy: “Jeová, teu Deus”.
====

[[v11-1-48]]

^<<v11-1-48,48>>^ E também foi isto o que o rei disse: ‘Bendito seja Jeová, o Deus de Israel, que hoje deu alguém para se assentar no meu trono, vendo-o os meus próprios olhos!’”

[[v11-1-49]]

^<<v11-1-49,49>>^ E todos os convidados que estavam com Adonias começaram a tremer e a levantar-se, e começaram a seguir cada um seu próprio caminho.

[[v11-1-50]]

^<<v11-1-50,50>>^ E o próprio Adonias teve medo por causa de Salomão. Por isso se levantou e se foi, e agarrou os chifres do altar.

[[v11-1-51]]

^<<v11-1-51,51>>^ Comunicou-se então ao Rei Salomão, dizendo-se: “Eis que o próprio Adonias ficou com medo do Rei Salomão; e eis que se agarrou aos chifres do altar, dizendo: ‘Jure-me primeiro o Rei Salomão que não entregará seu servo à morte pela espada.’”

[[v11-1-52]]

^<<v11-1-52,52>>^ A isto disse Salomão: “Se ele se tornar um homem valente, não cairá nem sequer um cabelo seu por terra; mas, se se achar nele o que é mau, então terá de morrer.”

[[v11-1-53]]

^<<v11-1-53,53>>^ Portanto, o Rei Salomão mandou fazê-lo descer do altar. Ele entrou então e se curvou diante do Rei Salomão; Salomão disse-lhe depois: “Vai para a tua própria casa.”

'''

xref:010-2-samuel/010-2-samuel-024.adoc#v10-24-0[&#60; Capítulo Anterior] | <<v11-1-0,Topo>> | xref:011-1-reis/011-1-reis-002.adoc#v11-2-0[Próximo Capítulo &#62;]