include::./index.adoc[]

[[v11-19-0]]
=== 1 Reis, 19
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v11-19-1]]

^<<v11-19-1,1>>^ Acabe contou então a Jezabel tudo o que Elias tinha feito e tudo sobre como tinha matado todos os profetas à espada.

[[v11-19-2]]

^<<v11-19-2,2>>^ Em vista disso, Jezabel enviou um mensageiro a Elias, dizendo: “Assim façam os deuses^&#42;1^ e assim lhe acrescentem mais, se nesta hora, amanhã, eu não fizer a tua alma igual à alma de cada um deles!”

[NOTE]
====
. “Os deuses.” Hebr.: ’elo·hím, acompanhado pelo verbo “façam” no pl.; gr.: ho the·ós, “o deus”; lat.: dí·i, “deuses”.
====

[[v11-19-3]]

^<<v11-19-3,3>>^ E ele ficou com medo.^&#42;1^ Por conseguinte, levantou-se e começou a ir embora, pela sua alma,^&#42;2^ e chegou a Berseba, que pertence a Judá. Ali deixou então seu ajudante para trás.

[NOTE]
====
. “Ficou com medo”, LXXSyVg e muitos mss. hebr.; M: “chegou a ver”.
. “Sua alma (vida).” Hebr.: naf·shóh; gr.: psy·khén.
====

[[v11-19-4]]

^<<v11-19-4,4>>^ E ele mesmo entrou no ermo, caminho de um dia, e por fim chegou e sentou-se debaixo de certa giesta-das-vassouras. E começou a pedir que a sua alma morresse e a dizer: “Basta! Agora, ó Jeová, tira a minha alma, pois não sou melhor do que os meus antepassados.”

[[v11-19-5]]

^<<v11-19-5,5>>^ Por fim ele se deitou e adormeceu debaixo da giesta-das-vassouras. Mas, eis que aí tocou nele um anjo. Ele lhe disse então: “Levanta-te, come.”

[[v11-19-6]]

^<<v11-19-6,6>>^ Quando olhou, ora, eis que havia junto à sua cabeça um bolo redondo sobre pedras aquecidas e uma bilha de água. E ele começou a comer e a beber, deitando-se depois outra vez.

[[v11-19-7]]

^<<v11-19-7,7>>^ Mais tarde voltou o anjo de Jeová pela segunda vez, e tocou nele e disse: “Levanta-te, come, porque a viagem é demais para ti.”

[[v11-19-8]]

^<<v11-19-8,8>>^ Levantou-se, pois, e comeu e bebeu, e foi indo no poder desta nutrição por quarenta dias e quarenta noites, até o monte do [verdadeiro] Deus, Horebe.

[[v11-19-9]]

^<<v11-19-9,9>>^ Por fim entrou ali numa caverna para passar ali a noite; e eis que havia para ele a palavra de Jeová e ela foi dizer-lhe: “Que estás fazendo aqui, Elias?”

[[v11-19-10]]

^<<v11-19-10,10>>^ A isto ele disse: “Fui absolutamente ciumento por Jeová, o Deus dos exércitos; pois os filhos de Israel abandonaram o teu pacto, derrubaram os teus altares e mataram os teus profetas à espada, de modo que só eu fiquei; e estão começando a procurar a minha alma para a tirar.”

[[v11-19-11]]

^<<v11-19-11,11>>^ Mas ela disse: “Sai, e tens de ficar de pé no monte diante de Jeová.” E eis que Jeová estava passando, e um vento grande e forte estava rompendo montes e destroçando rochedos diante de Jeová. (Jeová não estava no vento.) E depois do vento houve um tremor. (Jeová não estava no tremor.)

[[v11-19-12]]

^<<v11-19-12,12>>^ E depois do tremor houve fogo. (Jeová não estava no fogo.) E depois do fogo houve uma voz calma, baixa.^&#42;1^

[NOTE]
====
. “Voz, e Jeová estava ali”, LXX.
====

[[v11-19-13]]

^<<v11-19-13,13>>^ E sucedeu que, assim que Elias a ouviu, envolveu imediatamente a face no seu manto oficial e saiu, e ficou de pé à entrada da caverna; e eis que houve uma voz para ele, e ela passou a dizer-lhe: “Que estás fazendo aqui, Elias?”

[[v11-19-14]]

^<<v11-19-14,14>>^ A isto ele disse: “Fui absolutamente ciumento por Jeová, o Deus dos exércitos; pois os filhos de Israel abandonaram o teu pacto, derrubaram os teus altares e mataram os teus profetas à espada, de modo que só eu fiquei; e estão começando a procurar a minha alma para a tirar.”

[[v11-19-15]]

^<<v11-19-15,15>>^ Jeová disse-lhe então: “Vai, volta pelo teu caminho ao ermo de Damasco; e tens de entrar e ungir Hazael como rei sobre a Síria.

[[v11-19-16]]

^<<v11-19-16,16>>^ E a Jeú, neto^&#42;1^ de Ninsi, deves ungir como rei sobre Israel; e a Eliseu,^&#42;2^ filho de Safate, de Abel-Meolá, deves ungir como profeta em teu lugar.

[NOTE]
====
. Lit.: “filho”.
. Significando “Deus É Salvação”. Hebr.: ’Eli·shá‛; gr.: He·li·sai·é; lat.: He·li·sé·um.
====

[[v11-19-17]]

^<<v11-19-17,17>>^ E terá de acontecer que aquele que escapar da espada de Hazael, Jeú entregará à morte; e quem escapar da espada de Jeú, Eliseu entregará à morte.

[[v11-19-18]]

^<<v11-19-18,18>>^ E deixei sete mil remanescer em Israel, todos os joelhos que não se dobraram diante de Baal e toda boca que não o beijou.”

[[v11-19-19]]

^<<v11-19-19,19>>^ Conseqüentemente, ele se foi dali e achou Eliseu, filho de Safate, enquanto arava com doze juntas diante de si e estava com a décima segunda. Assim, Elias passou por ele e lançou sobre ele seu manto oficial.

[[v11-19-20]]

^<<v11-19-20,20>>^ Em vista disso, este deixou os touros e saiu correndo atrás de Elias, e disse: “Por favor, deixa-me beijar meu pai e minha mãe. Então irei seguir-te.” A isto lhe disse ele: “Vai, volta; pois, que te tenho feito?”

[[v11-19-21]]

^<<v11-19-21,21>>^ Portanto, ele retornou de segui-lo e tomou então uma junta de touros e os ofereceu em sacrifício, e com a apeiragem dos touros cozinhou a carne deles e deu-a então ao povo, e passaram a comer. Depois se levantou e foi seguir Elias, e começou a ministrar-lhe.

'''

xref:011-1-reis/011-1-reis-018.adoc#v11-18-0[&#60; Capítulo Anterior] | <<v11-19-0,Topo>> | xref:011-1-reis/011-1-reis-020.adoc#v11-20-0[Próximo Capítulo &#62;]