include::./index.adoc[]

[[v11-10-0]]
=== 1 Reis, 10
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v11-10-1]]

^<<v11-10-1,1>>^ Ora, a rainha de Sabá ouvira as notícias a respeito de Salomão em conexão com o nome de Jeová. Por isso ela veio para pô-lo à prova com perguntas difíceis.^&#42;1^

[NOTE]
====
. Ou “com enigmas”.
====

[[v11-10-2]]

^<<v11-10-2,2>>^ Por fim chegou a Jerusalém com um séquito bem impressionante, camelos carregando óleo de bálsamo, e muitíssimo ouro e pedras preciosas; e entrando, foi ter com Salomão e começou a falar-lhe sobre tudo o que lhe veio a ser achegado ao coração.

[[v11-10-3]]

^<<v11-10-3,3>>^ Salomão, por sua vez, informava-a sobre todos os assuntos dela. Não se mostrava haver nenhum assunto oculto ao rei, que ele não lhe comunicasse.

[[v11-10-4]]

^<<v11-10-4,4>>^ Quando a rainha de Sabá chegou a ver toda a sabedoria de Salomão e a casa que tinha construído,

[[v11-10-5]]

^<<v11-10-5,5>>^ e o alimento^&#42;1^ da sua mesa, e a maneira de se assentarem os seus servos, e o serviço à mesa^&#42;2^ dos seus garçons e o vestuário deles, e suas bebidas e seus sacrifícios queimados que oferecia regularmente na casa de Jeová, então se mostrou não haver mais espírito nela.

[NOTE]
====
. Ou “pratos”.
. Lit.: “ficar de pé”.
====

[[v11-10-6]]

^<<v11-10-6,6>>^ Ela disse, pois, ao rei: “Veraz se mostrou a palavra que ouvi na minha própria terra a respeito dos teus assuntos e sobre a tua sabedoria.

[[v11-10-7]]

^<<v11-10-7,7>>^ E eu não depositava fé nas palavras até que vim ver com os meus próprios olhos; e eis que não se me contou nem a metade. Ultrapassaste em sabedoria e em prosperidade as coisas ouvidas que escutei.

[[v11-10-8]]

^<<v11-10-8,8>>^ Felizes são os teus homens;^&#42;1^ felizes são estes servos teus que estão constantemente de pé diante de ti, escutando a tua sabedoria!

[NOTE]
====
. “Homens”, MVg; LXXSyIt: “esposas”.
====

[[v11-10-9]]

^<<v11-10-9,9>>^ Que Jeová, teu Deus, venha a ser bendito, aquele que se agradou de ti, pondo-te no trono de Israel; porque Jeová ama a Israel por tempo indefinido, de modo que te designou como rei para fazer decisões judiciais e justiça.”

[[v11-10-10]]

^<<v11-10-10,10>>^ Então ela deu ao rei cento e vinte talentos de ouro, e muitíssimo óleo de bálsamo, e pedras preciosas. Nunca mais veio óleo de bálsamo como este em quantidade tal como a que a rainha de Sabá deu ao Rei Salomão.

[[v11-10-11]]

^<<v11-10-11,11>>^ E a frota de navios de Hirão, que carregavam ouro de Ofir, também trouxeram de Ofir madeira de algum^&#42;1^ em quantidade muito grande, bem como pedras preciosas.

[NOTE]
====
. Hebr.: ’al·mug·gím. Veja 2Cr 2:8 n.: “algum”.
====

[[v11-10-12]]

^<<v11-10-12,12>>^ E o rei passou a fazer da madeira de algum escoras para a casa de Jeová e para a casa do rei, bem como harpas e instrumentos de cordas para os cantores. Madeira de algum semelhante a esta nunca mais entrou nem se viu até o dia de hoje.

[[v11-10-13]]

^<<v11-10-13,13>>^ E o próprio Rei Salomão deu à rainha de Sabá tudo do seu agrado que pediu, além do que lhe deu segundo a liberalidade do Rei Salomão. Depois ela se virou e foi para a sua própria terra, ela junto com os seus servos.

[[v11-10-14]]

^<<v11-10-14,14>>^ E o peso do ouro que chegou a Salomão num só ano ascendeu a seiscentos e sessenta e seis talentos de ouro,^&#42;1^

[NOTE]
====
. Cerca de US$ 256.643.000, com o grama de ouro no valor de US$ 11,25.
====

[[v11-10-15]]

^<<v11-10-15,15>>^ além dos viajantes e do lucro proveniente dos negociantes, e de todos os reis dos árabes, e dos governadores do país.

[[v11-10-16]]

^<<v11-10-16,16>>^ E o Rei Salomão foi fazer duzentos escudos grandes de liga de ouro (passou a pôr em cada escudo grande seiscentos [siclos]^&#42;1^ de ouro)

[NOTE]
====
. “Seiscentos siclos”, Vg; M: “seiscentos”; Sy: “seiscentas minas”. Veja Ap. 8A.
====

[[v11-10-17]]

^<<v11-10-17,17>>^ e trezentos broquéis de liga de ouro (passou a pôr em cada broquel^&#42;1^ três minas^&#42;2^ de ouro). O rei os colocou então na Casa da Floresta do Líbano.

[NOTE]
====
. “Em . . . broquel.” Em hebr.: ‛al·ham·ma·ghén, um escudo menor do que o tsin·náh, “escudo grande”, mencionado no v. 16.
. Veja Ap. 8A.
====

[[v11-10-18]]

^<<v11-10-18,18>>^ Além disso, o rei fez um grande trono de marfim e o recobriu de ouro refinado.

[[v11-10-19]]

^<<v11-10-19,19>>^ Havia seis degraus [levando] ao trono, e o trono tinha um dossel redondo por detrás, e havia braços deste lado e daquele lado junto ao assento, e dois leões estavam em pé ao lado dos braços.

[[v11-10-20]]

^<<v11-10-20,20>>^ E havia ali doze leões em pé sobre os seis degraus, deste lado e daquele lado. Nenhum outro reino tinha feito um exatamente igual a ele.

[[v11-10-21]]

^<<v11-10-21,21>>^ E todos os vasos para beber, do Rei Salomão, eram de ouro, e todos os vasos da Casa da Floresta do Líbano eram de ouro puro. Não havia nada de prata; nos dias de Salomão não se lhe dava nenhuma importância.

[[v11-10-22]]

^<<v11-10-22,22>>^ Pois o rei tinha uma frota de navios de Társis no mar junto com a frota de navios de Hirão. Uma vez em cada três anos a frota de navios de Társis vinha trazendo ouro e prata, marfim, e macacos e pavões.

[[v11-10-23]]

^<<v11-10-23,23>>^ De modo que o Rei Salomão era maior em riquezas e em sabedoria do que todos os outros reis da terra.

[[v11-10-24]]

^<<v11-10-24,24>>^ E todas as pessoas da terra^&#42;1^ procuravam a face de Salomão para ouvir a sua sabedoria que Deus^&#42;2^ lhe pusera no coração.

[NOTE]
====
. Lit.: “E toda a terra”, mas com o verbo hebr. para “procuravam” no pl. LXXSy: “E todos os reis da terra.”
. “Deus”, M(hebr.: ’Elo·hím)Vg; LXX: “Jeová”.
====

[[v11-10-25]]

^<<v11-10-25,25>>^ E traziam-lhe cada um o seu presente: objetos de prata e objetos de ouro, e mantos, e armamento, e óleo de bálsamo, cavalos e mulos, como questão rotineira anual.

[[v11-10-26]]

^<<v11-10-26,26>>^ E Salomão estava ajuntando mais carros e corcéis;^&#42;1^ e ele veio a ter mil e quatrocentos carros e doze mil corcéis, e manteve-os aquartelados em cidades de carros perto do rei em Jerusalém.

[NOTE]
====
. Ou “cavaleiros”.
====

[[v11-10-27]]

^<<v11-10-27,27>>^ E o rei veio a tornar a prata em Jerusalém igual às pedras, e a madeira de cedro ele tornou igual aos sicômoros que há na Sefelá,^&#42;1^ por causa da grande quantidade.

[NOTE]
====
. Ou “terra baixa”.
====

[[v11-10-28]]

^<<v11-10-28,28>>^ E do Egito havia uma exportação de cavalos para Salomão, e o grupo dos mercadores do rei é que levava a tropa de cavalos por um preço.

[[v11-10-29]]

^<<v11-10-29,29>>^ E um carro costumava subir e era exportado do Egito por seiscentas moedas de prata e um cavalo por cento e cinqüenta; e assim era para todos os reis dos hititas e para os reis da Síria. Era por meio deles^&#42;1^ que se fazia a exportação.

[NOTE]
====
. “Era por meio deles”, M; LXX: “Era pelo mar.”
====

'''

xref:011-1-reis/011-1-reis-009.adoc#v11-9-0[&#60; Capítulo Anterior] | <<v11-10-0,Topo>> | xref:011-1-reis/011-1-reis-011.adoc#v11-11-0[Próximo Capítulo &#62;]