include::./index.adoc[]

[[v11-2-0]]
=== 1 Reis, 2
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v11-2-1]]

^<<v11-2-1,1>>^ E pouco a pouco chegaram-se os dias de Davi morrer; e ele passou a ordenar a Salomão, seu filho, dizendo:

[[v11-2-2]]

^<<v11-2-2,2>>^ “Eu vou no caminho de toda a terra, e tu terás de ser forte e mostrar-te homem.

[[v11-2-3]]

^<<v11-2-3,3>>^ E terás de cumprir a obrigação para com Jeová, teu Deus, andando nos seus caminhos, guardando os seus estatutos, seus mandamentos e suas decisões judiciais, e seus testemunhos,^&#42;1^ segundo o que está escrito na lei de Moisés, para agir com circunspeção em tudo o que fizeres e aonde quer que te virares;

[NOTE]
====
. Ou “advertências; exortações”.
====

[[v11-2-4]]

^<<v11-2-4,4>>^ a fim de que Jeová cumpra a sua palavra que falou referente a mim, dizendo: ‘Se os teus filhos cuidarem do seu caminho, andando perante mim em verdade,^&#42;1^ de todo o seu coração e de toda a sua alma, não se decepará homem teu, [impedindo-o de sentar-se] no trono de Israel.’

[NOTE]
====
. Ou “fidelidade”.
====

[[v11-2-5]]

^<<v11-2-5,5>>^ “E tu mesmo também sabes muito bem o que me fez Joabe, filho de Zeruia, naquilo que fez aos dois chefes dos exércitos de Israel, a Abner, filho de Ner, e a Amasa, filho de Jeter, quando os matou e fez que houvesse sangue de guerra em tempo de paz, e pôs sangue de guerra no seu cinto que tinha em volta dos quadris e nas suas sandálias que tinha nos pés.

[[v11-2-6]]

^<<v11-2-6,6>>^ E terás de agir segundo a tua sabedoria e não deixar que seus cabelos grisalhos desçam em paz ao Seol.^&#42;1^

[NOTE]
====
. “Seol.” Hebr.: she’ól; gr.: haí·dou; sir.: la·shiul; lat.: ín·fe·ros. Veja Ap. 4B.
====

[[v11-2-7]]

^<<v11-2-7,7>>^ “E deves usar de benevolência^&#42;1^ para com os filhos de Barzilai, o gileadita, e eles têm de mostrar estar entre os que comem à tua mesa; pois foi assim que se chegaram a mim quando fugi de diante de Absalão, teu irmão.

[NOTE]
====
. Ou “amor leal”.
====

[[v11-2-8]]

^<<v11-2-8,8>>^ “E eis que há contigo Simei, filho de Gera, benjaminita de Baurim, e foi ele quem invocou o mal sobre mim com uma penosa invocação do mal, no dia em que fui a Maanaim; e foi ele quem desceu ao meu encontro até o Jordão, de modo que lhe jurei por Jeová, dizendo: ‘Não te entregarei à morte pela espada.’

[[v11-2-9]]

^<<v11-2-9,9>>^ E agora, não o deixes impune, porque és homem sábio e sabes muito bem o que lhe deves fazer, e terás de fazer os seus cabelos grisalhos descer com sangue ao Seol.”

[[v11-2-10]]

^<<v11-2-10,10>>^ Davi deitou-se então com os seus antepassados e foi enterrado na Cidade de Davi.

[[v11-2-11]]

^<<v11-2-11,11>>^ E os dias que Davi reinou sobre Israel foram quarenta anos. Em Hébron ele reinou sete anos e em Jerusalém reinou trinta e três anos.

[[v11-2-12]]

^<<v11-2-12,12>>^ Quanto a Salomão, sentou-se no trono de Davi, seu pai; e, aos poucos, seu reinado ficou estabelecido com muita firmeza.

[[v11-2-13]]

^<<v11-2-13,13>>^ Passado tempo, chegou Adonias, filho de Hagite, a Bate-Seba, mãe de Salomão. Então ela disse: “É pacífica a tua vinda?” ao que ele disse: “É pacífica.”

[[v11-2-14]]

^<<v11-2-14,14>>^ E prosseguiu, dizendo: “Tenho um assunto para ti.” De modo que ela disse: “Fala.”

[[v11-2-15]]

^<<v11-2-15,15>>^ E ele continuou: “Tu mesma bem sabes que o reinado ia tornar-se meu e que foi em mim que todo o Israel fixou a sua face para eu me tornar rei; mas o reinado mudou de rumo e veio a ser de meu irmão, porque era da parte de Jeová que se tornou seu.

[[v11-2-16]]

^<<v11-2-16,16>>^ E agora há um pedido que te faço. Não faças a minha face voltar atrás.” Por conseguinte, ela lhe disse: “Fala.”

[[v11-2-17]]

^<<v11-2-17,17>>^ E ele prosseguiu, dizendo: “Por favor, dize a Salomão, o rei, (pois ele não fará a tua face voltar atrás,) que me dê Abisague, a sunamita, por esposa.”

[[v11-2-18]]

^<<v11-2-18,18>>^ A isto disse Bate-Seba: “Está bem! Eu mesma falarei por ti ao rei.”

[[v11-2-19]]

^<<v11-2-19,19>>^ Portanto, Bate-Seba entrou até o Rei Salomão para falar com ele por Adonias. O rei se levantou imediatamente para ir ao encontro dela e curvou-se diante dela. Então se sentou no seu trono e fez pôr um trono para a mãe do rei, para que se sentasse à sua direita.

[[v11-2-20]]

^<<v11-2-20,20>>^ E ela passou a dizer: “Há um pequeno pedido que te faço. Não faças a minha face voltar atrás.” O rei lhe disse, pois: “Faze-o, minha mãe; porque não farei a tua face voltar atrás.”

[[v11-2-21]]

^<<v11-2-21,21>>^ E ela prosseguiu, dizendo: “Dê-se Abisague, a sunamita, a Adonias, teu irmão, por esposa.”

[[v11-2-22]]

^<<v11-2-22,22>>^ Então respondeu o Rei Salomão e disse à sua mãe: “E por que pedes Abisague, a sunamita, para Adonias? Pede também para ele o reinado (porque é meu irmão mais velho do que eu), sim, para ele, e para Abiatar, o sacerdote, e para Joabe, filho de Zeruia.”

[[v11-2-23]]

^<<v11-2-23,23>>^ Com isso o Rei Salomão jurou por Jeová, dizendo: “Assim me faça Deus e assim lhe acrescente mais, se não foi contra a sua própria alma que Adonias falou nesta coisa.

[[v11-2-24]]

^<<v11-2-24,24>>^ E agora, por Jeová que vive, que me estabeleceu firmemente e que me mantém sentado no trono de Davi, meu pai, e que fez para mim uma casa, assim como falou, hoje Adonias será morto.”

[[v11-2-25]]

^<<v11-2-25,25>>^ O Rei Salomão enviou imediatamente por meio de Benaia, filho de Jeoiada; e este passou a lançar-se sobre ele de modo que morreu.^&#42;1^

[NOTE]
====
. “Sobre ele, e Adonias morreu naquele dia”, LXX.
====

[[v11-2-26]]

^<<v11-2-26,26>>^ E a Abiatar, o sacerdote, o rei disse: “Vai para Anatote, para os teus campos! Pois mereces a morte;^&#42;1^ mas neste dia não te entregarei à morte, porque carregaste a arca do Soberano Senhor Jeová diante de Davi, meu pai, e porque foste atribulado durante todo o tempo que meu pai foi atribulado.”

[NOTE]
====
. Lit.: “és homem de morte”.
====

[[v11-2-27]]

^<<v11-2-27,27>>^ Portanto, Salomão expulsou a Abiatar do serviço de sacerdote de Jeová, para cumprir a palavra de Jeová, que ele havia falado contra a casa de Eli, em Silo.

[[v11-2-28]]

^<<v11-2-28,28>>^ E a própria notícia chegou até Joabe — porque o próprio Joabe se inclinara a seguir Adonias, embora não se tivesse inclinado a seguir Absalão^&#42;1^ — e Joabe se pôs a fugir para a tenda de Jeová e começou a segurar os chifres do altar.

[NOTE]
====
. “Absalão”, MLXXBVg; LXXSyVgc: “Salomão”.
====

[[v11-2-29]]

^<<v11-2-29,29>>^ Informou-se então ao Rei Salomão: “Joabe fugiu para a tenda de Jeová, e eis que está ao lado do altar.” Salomão enviou, pois, Benaia, filho de Jeoiada, dizendo: “Vai, lança-te sobre ele!”

[[v11-2-30]]

^<<v11-2-30,30>>^ Por conseguinte, Benaia chegou à tenda de Jeová e disse-lhe: “Assim disse o rei: ‘Vem para fora!’” Mas ele disse: “Não! Pois é aqui que morrerei.” Então Benaia trouxe a informação de volta ao rei, dizendo: “Assim falou Joabe e assim me respondeu.”

[[v11-2-31]]

^<<v11-2-31,31>>^ O rei disse-lhe então: “Faze-lhe assim como falou e lança-te sobre ele; e tens de enterrá-lo e remover de mim e da casa de meu pai o sangue^&#42;1^ imerecidamente derramado que Joabe derramou.

[NOTE]
====
. Lit.: “sangues”, denotando casos de derramamento de sangue.
====

[[v11-2-32]]

^<<v11-2-32,32>>^ E Jeová fará certamente retornar seu sangue sobre a sua própria cabeça, porque se lançou sobre dois homens mais justos e melhores do que ele, e passou a matá-los com a espada, quando meu pai, o próprio Davi, nada sabia disso, a saber, Abner, filho de Ner, chefe do exército de Israel, e Amasa, filho de Jeter, chefe do exército de Judá.

[[v11-2-33]]

^<<v11-2-33,33>>^ E o sangue deles terá de retornar sobre a cabeça de Joabe e sobre a cabeça da sua descendência, por tempo indefinido; mas para Davi e para a sua descendência, e para a sua casa e para o seu trono virá a haver paz da parte de Jeová, por tempo indefinido.”

[[v11-2-34]]

^<<v11-2-34,34>>^ Então subiu Benaia, filho de Jeoiada, e lançou-se sobre ele e entregou-o à morte; e ele foi enterrado em sua própria casa, no ermo.

[[v11-2-35]]

^<<v11-2-35,35>>^ Após isso, o rei colocou Benaia, filho de Jeoiada, no lugar dele sobre o exército; e a Zadoque, o sacerdote, o rei colocou^&#42;1^ no lugar de Abiatar.

[NOTE]
====
. “O rei colocou”, M; LXX: “o rei colocou como sumo sacerdote”.
====

[[v11-2-36]]

^<<v11-2-36,36>>^ Por fim, o rei mandou chamar Simei e disse-lhe: “Constrói para ti uma casa em Jerusalém, e terás de morar ali e não sair dali para este ou aquele lugar.

[[v11-2-37]]

^<<v11-2-37,37>>^ E terá de ocorrer que, no dia em que saíres e quando atravessares o vale da torrente do Cédron, deves saber inequivocamente que positivamente morrerás. A própria culpa pelo teu sangue^&#42;1^ virá a estar sobre a tua própria cabeça.

[NOTE]
====
. Lit.: “teu sangue”. Hebr.: dom·khá.
====

[[v11-2-38]]

^<<v11-2-38,38>>^ Então disse Simei ao rei: “A palavra é boa. Assim como falou meu senhor, o rei, assim fará teu servo.” E Simei ficou morando em Jerusalém por muitos dias.

[[v11-2-39]]

^<<v11-2-39,39>>^ E sucedeu, ao fim de três anos, que dois escravos de Simei puseram-se a fugir para Aquis, filho de Maacá, rei de Gate; e pessoas vieram contar isso a Simei, dizendo: “Eis que os teus escravos estão em Gate.”

[[v11-2-40]]

^<<v11-2-40,40>>^ Simei levantou-se imediatamente e selou seu jumento, e foi a Gate, a Aquis, procurar seus escravos; depois, Simei foi e trouxe seus escravos de Gate.

[[v11-2-41]]

^<<v11-2-41,41>>^ Informou-se então a Salomão: “Simei saiu de Jerusalém a Gate e está de volta.”

[[v11-2-42]]

^<<v11-2-42,42>>^ Em vista disso, o rei mandou chamar Simei e disse-lhe: “Não te pus sob juramento por Jeová para te advertir, dizendo: ‘No dia em que saíres e deveras fores para cá e para lá, deves saber inequivocamente que positivamente morrerás’, e então, não me disseste: ‘É boa a palavra que ouvi’?

[[v11-2-43]]

^<<v11-2-43,43>>^ Então, por que não guardaste o juramento de Jeová e o mandamento que te impus solenemente?”

[[v11-2-44]]

^<<v11-2-44,44>>^ E o rei prosseguiu, dizendo a Simei: “Tu mesmo certamente sabes todo o mal que fizeste a Davi, meu pai, como teu coração sabe muito bem; e Jeová certamente fará voltar sobre a tua própria cabeça o mal causado por ti.

[[v11-2-45]]

^<<v11-2-45,45>>^ Mas o Rei Salomão será bendito e o próprio trono de Davi se mostrará firmemente estabelecido perante Jeová para sempre.”^&#42;1^

[NOTE]
====
. Ou “perante Jeová por tempo indefinido”.
====

[[v11-2-46]]

^<<v11-2-46,46>>^ Com isto o rei deu ordem a Benaia, filho de Jeoiada, que então saiu e se lançou sobre ele, de modo que morreu.
E o reino ficou firmemente estabelecido na mão de Salomão.

'''

xref:011-1-reis/011-1-reis-001.adoc#v11-1-0[&#60; Capítulo Anterior] | <<v11-2-0,Topo>> | xref:011-1-reis/011-1-reis-003.adoc#v11-3-0[Próximo Capítulo &#62;]