include::./index.adoc[]

[[v11-9-0]]
=== 1 Reis, 9
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v11-9-1]]

^<<v11-9-1,1>>^ E sucedeu que, assim que Salomão tinha acabado de construir a casa de Jeová, e a casa do rei, e toda coisa desejável de Salomão, que ele se agradou de fazer,

[[v11-9-2]]

^<<v11-9-2,2>>^ então Jeová apareceu a Salomão pela segunda vez, assim como lhe havia aparecido em Gibeão.

[[v11-9-3]]

^<<v11-9-3,3>>^ E Jeová passou a dizer-lhe: “Ouvi a tua oração e o teu pedido de favor com que pediste um favor diante de mim. Santifiquei esta casa que construíste, pondo ali meu nome por tempo indefinido; e meus olhos e meu coração certamente mostrarão estar ali para sempre.

[[v11-9-4]]

^<<v11-9-4,4>>^ E tu, se andares diante de mim assim como andou Davi, teu pai, com integridade de coração e com retidão, fazendo segundo tudo o que te ordenei, e se guardares os meus regulamentos e as minhas decisões judiciais,

[[v11-9-5]]

^<<v11-9-5,5>>^ então deveras estabelecerei o trono do teu reino sobre Israel por tempo indefinido,^&#42;1^ assim como prometi a Davi, teu pai, dizendo: ‘Não se decepará homem teu, [impedindo-o de sentar-se] no trono de Israel.’

[NOTE]
====
. Ou “sobre Israel para sempre”.
====

[[v11-9-6]]

^<<v11-9-6,6>>^ Se vós mesmos e os vossos filhos definitivamente recuardes de me seguir e não guardardes os meus mandamentos e os meus estatutos que pus diante de vós, e se realmente fordes e servirdes outros deuses, e vos curvardes diante deles,^&#42;1^

[NOTE]
====
. Ou “e os adorardes”.
====

[[v11-9-7]]

^<<v11-9-7,7>>^ então eu vou decepar Israel da superfície do solo que lhes dei; e a casa que santifiquei ao meu nome lançarei para longe^&#42;1^ de mim, e Israel deveras se tornará uma expressão proverbial e um escárnio entre todos os povos.

[NOTE]
====
. “Lançarei para longe”, TLXXVg e 2Cr 7:20; M: “mandarei embora”.
====

[[v11-9-8]]

^<<v11-9-8,8>>^ E esta mesma casa se tornará montões de ruínas.^&#42;1^ Todo aquele que passar por ela olhará espantado, e certamente assobiará e dirá: ‘Por que razão fez Jeová assim a esta terra e a esta casa?’

[NOTE]
====
. “Se tornará montões de ruínas”, mediante uma pequena correção para concordar com SyIt; M: “se tornará mui proeminente (destacada; conspícua)”.
====

[[v11-9-9]]

^<<v11-9-9,9>>^ E terá de dizer-se: ‘Pela razão de terem deixado a Jeová, seu Deus, que fizera os antepassados deles sair da terra do Egito, e eles terem passado a agarrar-se a outros deuses, e a curvar-se diante deles e a servi-los. É por isso que Jeová trouxe sobre eles toda esta calamidade.’”

[[v11-9-10]]

^<<v11-9-10,10>>^ E sucedeu, ao fim de vinte anos, nos quais Salomão construiu as duas casas, a casa de Jeová e a casa do rei,

[[v11-9-11]]

^<<v11-9-11,11>>^ (tendo o próprio Hirão, rei de Tiro, auxiliado Salomão com madeiras de cedro e com madeiras de junípero, e com ouro tanto quanto lhe agradou,) que o Rei Salomão, naquele tempo, passou a dar a Hirão vinte cidades na terra da Galiléia.^&#42;1^

[NOTE]
====
. Ou “do circuito”. Hebr.: hag·Ga·líl; gr.: Ga·li·laí·ai; lat.: Ga·li·lé·ae. “Galiléia” veio posteriormente designar a província romana ao norte de Samaria.
====

[[v11-9-12]]

^<<v11-9-12,12>>^ Por conseguinte, Hirão saiu de Tiro para ver as cidades que Salomão lhe dera e elas não estavam bem direitas aos seus olhos.

[[v11-9-13]]

^<<v11-9-13,13>>^ Por isso ele disse: “Que tipo de cidades são estas que me deste, meu irmão?” E elas vieram a ser chamadas de Terra de Cabul^&#42;1^ até o dia de hoje.

[NOTE]
====
. Ou “Terra Que É o Mesmo Que Nada”; talvez: “Terra Agrilhoada”.
====

[[v11-9-14]]

^<<v11-9-14,14>>^ No ínterim, Hirão enviara ao rei cento e vinte talentos^&#42;1^ de ouro.

[NOTE]
====
. Veja Ap. 8A.
====

[[v11-9-15]]

^<<v11-9-15,15>>^ Ora, este é o relato sobre os recrutados para trabalho forçado, que o Rei Salomão recrutou para construir a casa de Jeová, e a sua própria casa, e o Aterro,^&#42;1^ e a muralha de Jerusalém, e Hazor, e Megido, e Gezer.

[NOTE]
====
. “O Aterro.” Hebr.: ham·mil·lóh’. Possivelmente uma construção semelhante a uma cidadela.
====

[[v11-9-16]]

^<<v11-9-16,16>>^ (O próprio Faraó, rei do Egito, tinha subido e então capturado Gezer, e a tinha queimado com fogo, e ele matara os cananeus que moravam na cidade. De modo que a deu como presente de despedida à sua filha, a esposa de Salomão.)

[[v11-9-17]]

^<<v11-9-17,17>>^ E Salomão prosseguiu, construindo Gezer e Bete-Horom Baixa,

[[v11-9-18]]

^<<v11-9-18,18>>^ e Baalate e Tamar,^&#42;1^ no ermo, no país,

[NOTE]
====
. “Tadmor”, MmargemSy (veja 2Cr 8:4); Vg: “Palmira”.
====

[[v11-9-19]]

^<<v11-9-19,19>>^ e todas as cidades-armazéns que vieram a ser de Salomão, e as cidades para os carros e as cidades para os cavaleiros, e as coisas desejáveis de Salomão, que desejou construir em Jerusalém e no Líbano, bem como em toda a terra do seu domínio.

[[v11-9-20]]

^<<v11-9-20,20>>^ Quanto a todo o povo que sobrara dos amorreus, dos hititas, dos perizeus, dos heveus e dos jebuseus, que não eram parte dos filhos de Israel,

[[v11-9-21]]

^<<v11-9-21,21>>^ seus filhos que sobraram depois deles no país, os quais os filhos de Israel não puderam devotar à destruição, a estes Salomão continuou a recrutar para trabalho forçado de escravos até o dia de hoje.

[[v11-9-22]]

^<<v11-9-22,22>>^ E a nenhum dos filhos de Israel constituiu Salomão em escravo; pois eram os guerreiros, e seus servos, e seus príncipes, e seus ajudantes-de-ordens, e os chefes dos seus condutores de carros e dos seus cavaleiros.

[[v11-9-23]]

^<<v11-9-23,23>>^ Estes eram os chefes dos prepostos que estavam sobre a obra de Salomão: quinhentos e cinqüenta, os capatazes sobre o povo que se empenhava na obra.

[[v11-9-24]]

^<<v11-9-24,24>>^ No entanto, a própria filha de Faraó subiu da Cidade de Davi para a sua própria casa que ele havia construído para ela. Foi então que construiu o Aterro.

[[v11-9-25]]

^<<v11-9-25,25>>^ E Salomão continuou a oferecer três vezes ao ano sacrifícios queimados e sacrifícios de participação em comum sobre o altar que tinha construído a Jeová, e fazia-se fumaça sacrificial^&#42;1^ sobre ele, que estava perante Jeová; e ele terminou a casa.

[NOTE]
====
. “Fazia-se fumaça sacrificial.” No hebr., este verbo está no infinitivo absoluto, indefinido quanto ao tempo e impessoal.
====

[[v11-9-26]]

^<<v11-9-26,26>>^ E havia uma frota de navios que o Rei Salomão fez em Eziom-Géber, que está junto a Elote, à beira do Mar Vermelho, na terra de Edom.

[[v11-9-27]]

^<<v11-9-27,27>>^ E Hirão enviava na frota de navios os seus próprios servos, marinheiros^&#42;1^ que conheciam o mar, junto com os servos de Salomão.

[NOTE]
====
. Lit.: “homens de navios”.
====

[[v11-9-28]]

^<<v11-9-28,28>>^ E eles passaram a ir a Ofir e tomar de lá quatrocentos e vinte talentos^&#42;1^ de ouro, e vieram trazê-lo ao Rei Salomão.

[NOTE]
====
. Veja Ap. 8A.
====

'''

xref:011-1-reis/011-1-reis-008.adoc#v11-8-0[&#60; Capítulo Anterior] | <<v11-9-0,Topo>> | xref:011-1-reis/011-1-reis-010.adoc#v11-10-0[Próximo Capítulo &#62;]