include::./index.adoc[]

[[v11-21-0]]
=== 1 Reis, 21
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v11-21-1]]

^<<v11-21-1,1>>^ E sucedeu, depois destas coisas, que um vinhedo, que viera a ser de Nabote, o jezreelita, achava-se em Jezreel ao lado do palácio de Acabe, rei de Samaria.

[[v11-21-2]]

^<<v11-21-2,2>>^ Acabe falou, pois, a Nabote, dizendo: “Dá-me deveras o teu vinhedo, para que me sirva de horta de verduras, pois está perto da minha casa; e deixa-me dar-te em lugar dele um vinhedo melhor do que este. [Ou] se for bom aos teus olhos, dar-te-ei deveras dinheiro como preço deste.”

[[v11-21-3]]

^<<v11-21-3,3>>^ Mas Nabote disse a Acabe: “É inconcebível da minha parte, do ponto de vista de Jeová, dar-te a propriedade hereditária dos meus antepassados.”

[[v11-21-4]]

^<<v11-21-4,4>>^ Conseqüentemente, Acabe entrou na sua casa, taciturno e abatido por causa da palavra que Nabote, o jezreelita, lhe falara, dizendo: “Não te darei a propriedade hereditária dos meus antepassados.” Deitou-se então sobre o seu leito e manteve a sua face voltada, e não comeu pão.

[[v11-21-5]]

^<<v11-21-5,5>>^ Por fim entrou até ele Jezabel, sua esposa, e falou-lhe: “Por que está triste o teu espírito e não comes pão?”

[[v11-21-6]]

^<<v11-21-6,6>>^ Então lhe falou ele: “Porque passei a falar com Nabote, o jezreelita, e a dizer-lhe: ‘Dá-me deveras o teu vinhedo por dinheiro. Ou, se preferires, deixa-me dar-te outro vinhedo em seu lugar.’ Mas ele disse: ‘Não te darei o meu vinhedo.’”

[[v11-21-7]]

^<<v11-21-7,7>>^ Jezabel, sua esposa, disse-lhe então: “Agora, és tu que exerces as funções de rei sobre Israel? Levanta-te, come pão e esteja contente o teu coração. Eu mesma te darei o vinhedo de Nabote, o jezreelita.”

[[v11-21-8]]

^<<v11-21-8,8>>^ Concordemente, ela escreveu cartas em nome de Acabe e as selou com o sinete dele, e enviou as cartas aos anciãos e aos nobres que havia na cidade dele, morando com Nabote.

[[v11-21-9]]

^<<v11-21-9,9>>^ Mas ela escreveu nas cartas, dizendo: “Proclamai um jejum e fazei Nabote sentar-se à cabeça do povo.

[[v11-21-10]]

^<<v11-21-10,10>>^ E fazei dois homens, homens imprestáveis,^&#42;1^ sentar-se defronte dele, e dêem eles testemunho contra ele, dizendo: ‘Amaldiçoaste^&#42;2^ a Deus e ao rei!’ E levai-o para fora e apedrejai-o para que morra.”

[NOTE]
====
. “Homens imprestáveis.” Lit.: “filhos de belial (inutilidade)”. Hebr.: beneh-veli·yá·‛al.
. A versão original rezava “amaldiçoaste”. O texto foi emendado para rezar “abençoaste”. Veja Ap. 2B.
====

[[v11-21-11]]

^<<v11-21-11,11>>^ Portanto, os homens de sua cidade, os anciãos e os nobres que moravam na sua cidade fizeram exatamente como Jezabel lhes enviara [recado], assim como estava escrito nas cartas que lhes enviara.

[[v11-21-12]]

^<<v11-21-12,12>>^ Proclamaram um jejum e fizeram Nabote sentar-se à cabeça do povo.

[[v11-21-13]]

^<<v11-21-13,13>>^ Então entraram dois dos homens, homens imprestáveis, e sentaram-se defronte dele; e os homens imprestáveis começaram a dar testemunho contra ele, isto é, contra Nabote, na frente de todo o povo, dizendo: “Nabote amaldiçoou^&#42;1^ a Deus e ao rei!” Depois o levaram para fora aos arrabaldes da cidade e o mataram a pedradas, de modo que morreu.

[NOTE]
====
. Veja v. 10 n.: “Amaldiçoaste.”
====

[[v11-21-14]]

^<<v11-21-14,14>>^ Mandaram então dizer a Jezabel: “Nabote foi apedrejado, de modo que está morto.”

[[v11-21-15]]

^<<v11-21-15,15>>^ E sucedeu que, assim que Jezabel ouviu que Nabote fora apedrejado de modo que morreu, Jezabel disse imediatamente a Acabe: “Levanta-te, toma posse do vinhedo de Nabote, o jezreelita, que ele se negou a dar-te por dinheiro; porque Nabote não mais vive, mas está morto.”

[[v11-21-16]]

^<<v11-21-16,16>>^ E aconteceu que, assim que Acabe ouviu que Nabote estava morto, Acabe se levantou imediatamente para descer ao vinhedo de Nabote, o jezreelita, a fim de tomar posse dele.

[[v11-21-17]]

^<<v11-21-17,17>>^ E a palavra de Jeová veio a Elias, o tisbita, dizendo:

[[v11-21-18]]

^<<v11-21-18,18>>^ “Levanta-te, desce ao encontro de Acabe, rei de Israel, que está em Samaria. Eis que está no vinhedo de Nabote, ao qual desceu para tomar posse dele.

[[v11-21-19]]

^<<v11-21-19,19>>^ E tens de falar-lhe, dizendo: ‘Assim disse Jeová: “Assassinaste e também tomaste posse?”’ E tens de falar-lhe, dizendo: ‘Assim disse Jeová: “No lugar onde os cães lamberam o sangue de Nabote, os cães lamberão o teu sangue, sim, o teu.”’”

[[v11-21-20]]

^<<v11-21-20,20>>^ E Acabe passou a dizer a Elias: “Achaste-me, inimigo meu?” a que ele disse: “Achei-te. ‘Visto que te vendeste para fazer o que é mau aos olhos de Jeová,

[[v11-21-21]]

^<<v11-21-21,21>>^ eis que trago sobre ti calamidade; e hei de fazer uma varredura depois de ti e decepar de Acabe todo aquele que urina contra o muro,^&#42;1^ bem como o incapacitado e o rejeitado^&#42;2^ em Israel.

[NOTE]
====
. “Que urina contra o muro.” Esta é uma expressão idiomática hebr. referindo-se a varões.
. Lit.: “e o restrito e o largado (abandonado)”. Veja De 32:36 n.: “rejeitado”.
====

[[v11-21-22]]

^<<v11-21-22,22>>^ E certamente constituirei a tua casa igual à casa de Jeroboão, filho de Nebate, e igual à casa de Baasa, filho de Aijá, pela ofensa com que ofendeste e então fizeste Israel pecar.’

[[v11-21-23]]

^<<v11-21-23,23>>^ E Jeová falou também referente a Jezabel, dizendo: ‘Os próprios cães devorarão Jezabel no lote de terreno de Jezreel.

[[v11-21-24]]

^<<v11-21-24,24>>^ Quem de Acabe morrer na cidade, os cães devorarão; e quem morrer no campo, as aves dos céus comerão.

[[v11-21-25]]

^<<v11-21-25,25>>^ Sem exceção, ninguém se mostrou igual a Acabe, que se vendeu para fazer o que é mau aos olhos de Jeová, instigando-o Jezabel, sua esposa.

[[v11-21-26]]

^<<v11-21-26,26>>^ E ele procedia de modo muito detestável, indo atrás dos ídolos sórdidos, igual a tudo o que fizeram os amorreus que Jeová desalojou de diante dos filhos de Israel.’”

[[v11-21-27]]

^<<v11-21-27,27>>^ E sucedeu que, assim que Acabe ouviu estas palavras, passou a rasgar as suas vestes e a pôr serapilheira sobre a sua carne; e foi fazer um jejum e ficou deitado em serapilheira, e andava acabrunhado.

[[v11-21-28]]

^<<v11-21-28,28>>^ E a palavra de Jeová veio a Elias, o tisbita, dizendo:

[[v11-21-29]]

^<<v11-21-29,29>>^ “Viste como Acabe se humilhou por minha causa? Uma vez que se humilhou por minha causa, não trarei a calamidade nos seus próprios dias. Nos dias de seu filho trarei a calamidade sobre a sua casa.”

'''

xref:011-1-reis/011-1-reis-020.adoc#v11-20-0[&#60; Capítulo Anterior] | <<v11-21-0,Topo>> | xref:011-1-reis/011-1-reis-022.adoc#v11-22-0[Próximo Capítulo &#62;]