include::./index.adoc[]

[[v11-3-0]]
=== 1 Reis, 3
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v11-3-1]]

^<<v11-3-1,1>>^ E Salomão passou a formar uma aliança matrimonial com Faraó, o rei do Egito, e a tomar a filha de Faraó e a trazê-la à Cidade de Davi, até que acabou de construir a sua própria casa e a casa de Jeová, bem como a muralha de Jerusalém, em toda a volta.

[[v11-3-2]]

^<<v11-3-2,2>>^ Só que o povo oferecia sacrifícios nos altos, pois até aqueles dias não se construíra ainda uma casa ao nome de Jeová.

[[v11-3-3]]

^<<v11-3-3,3>>^ E Salomão continuou a amar a Jeová, andando nos estatutos de Davi, seu pai. Só que era nos altos que oferecia regularmente sacrifícios e fazia fumegar as ofertas.

[[v11-3-4]]

^<<v11-3-4,4>>^ Conseqüentemente, o rei foi a Gibeão para oferecer ali sacrifícios, pois aquele era o grande alto. Mil sacrifícios queimados passou Salomão a oferecer naquele altar.

[[v11-3-5]]

^<<v11-3-5,5>>^ Em Gibeão apareceu Jeová a Salomão num sonho, de noite; e Deus^&#42;1^ passou a dizer: “Pede o que te devo dar.”

[NOTE]
====
. “Deus”, MSy; TLXX: “Jeová”.
====

[[v11-3-6]]

^<<v11-3-6,6>>^ Então disse Salomão: “Tu mesmo usaste de grande benevolência^&#42;1^ para com o teu servo Davi, meu pai, conforme ele andou diante de ti em verdade, e em justiça, e em retidão de coração para contigo; e continuaste a ter para com ele esta grande benevolência, de modo que lhe deste um filho para sentar-se^&#42;2^ no seu trono, como no dia de hoje.

[NOTE]
====
. Ou “amor leal”.
. Lit.: “um filho sentado”.
====

[[v11-3-7]]

^<<v11-3-7,7>>^ E agora, Jeová, meu Deus, tu mesmo fizeste teu servo rei em lugar de Davi, meu pai, e eu sou apenas um rapazinho. Não sei como sair e como entrar.

[[v11-3-8]]

^<<v11-3-8,8>>^ E teu servo está no meio do teu povo que escolheste, um povo numeroso que não pode ser computado nem contado por sua multidão.

[[v11-3-9]]

^<<v11-3-9,9>>^ E tens de dar ao teu servo um coração obediente^&#42;1^ para julgar teu povo, para discernir entre o que é bom e o que é mau; pois, quem pode julgar este difícil^&#42;2^ povo teu?”

[NOTE]
====
. Lit.: “um coração ouvinte”.
. Ou “numeroso”. Lit.: “pesado”.
====

[[v11-3-10]]

^<<v11-3-10,10>>^ E esta coisa agradou^&#42;1^ aos olhos de Jeová,^&#42;2^ por Salomão ter pedido tal coisa.

[NOTE]
====
. Ou “era boa”.
. Uma das 134 mudanças de YHWH para ’Adho·naí feitas pelos escribas. Veja Ap. 1B.
====

[[v11-3-11]]

^<<v11-3-11,11>>^ E Deus^&#42;1^ prosseguiu, dizendo-lhe: “Visto que pediste tal coisa e não pediste para ti muitos dias, nem pediste para ti riquezas, nem pediste a alma^&#42;2^ dos teus inimigos, e pediste para ti entendimento,^&#42;3^ a fim de ouvir pleitos judiciais,^&#42;4^

[NOTE]
====
. “Deus”, MVg; LXXSyVgc: “Jeová”.
. Ou “vida”. Hebr.: né·fesh; gr.: psy·khás, pl.; Vgc(lat.): á·ni·mas, pl.
. Ou “discernimento”.
. Ou “obedecer ao julgamento”.
====

[[v11-3-12]]

^<<v11-3-12,12>>^ eis que certamente farei segundo as tuas palavras. Eis que certamente te darei um coração sábio e entendido,^&#42;1^ de modo que antes de ti não veio a haver ninguém igual a ti e depois de ti não se levantará quem te seja igual.

[NOTE]
====
. Ou “discernidor”.
====

[[v11-3-13]]

^<<v11-3-13,13>>^ E também vou dar-te aquilo que não pediste, tanto riquezas como glória, de modo que não virá a haver entre os reis nenhum igual a ti, em todos os teus dias.

[[v11-3-14]]

^<<v11-3-14,14>>^ E se andares nos meus caminhos, guardando os meus regulamentos e os meus mandamentos, assim como andou Davi, teu pai, também vou prolongar os teus dias.”

[[v11-3-15]]

^<<v11-3-15,15>>^ Quando Salomão acordou, ora, eis que tinha sido um sonho. Ele veio então a Jerusalém e ficou de pé diante da arca do pacto de Jeová,^&#42;1^ e ofereceu sacrifícios queimados e fez ofertas de participação em comum, e fez um banquete para todos os seus servos.

[NOTE]
====
. Veja v. 10 n.: “Jeová”.
====

[[v11-3-16]]

^<<v11-3-16,16>>^ Naquele tempo, duas mulheres, prostitutas, chegaram a entrar até o rei e a ficar de pé diante dele.

[[v11-3-17]]

^<<v11-3-17,17>>^ Então disse uma mulher: “Perdão, meu senhor, eu e esta mulher moramos numa só casa, de modo que dei à luz perto dela na casa.

[[v11-3-18]]

^<<v11-3-18,18>>^ E sucedeu, no terceiro dia depois de eu ter dado à luz, que esta mulher também passou a dar à luz. E estávamos juntas. Não havia estranho conosco na casa, ninguém senão nós duas na casa.

[[v11-3-19]]

^<<v11-3-19,19>>^ Mais tarde, de noite, morreu o filho desta mulher, porque ela se deitara sobre ele.

[[v11-3-20]]

^<<v11-3-20,20>>^ Portanto, ela se levantou no meio da noite e tomou meu filho do meu lado, enquanto a tua escrava dormia, e deitou-o ao seu próprio seio, e seu filho morto ela deitou ao meu seio.

[[v11-3-21]]

^<<v11-3-21,21>>^ Quando me levantei de manhã para amamentar meu filho, ora, eis que estava morto. Portanto, examinei-o de perto, de manhã, e eis que não se mostrou ser meu filho que eu tinha dado à luz.”

[[v11-3-22]]

^<<v11-3-22,22>>^ Mas a outra mulher disse: “Não, mas o meu filho é o vivo e o teu filho é o morto!” Todo o tempo esta mulher estava dizendo: “Não, mas o teu filho é o morto e o meu filho é o vivo.” E continuaram a falar perante o rei.

[[v11-3-23]]

^<<v11-3-23,23>>^ Finalmente, o rei disse: “Esta diz: ‘Este é meu filho, o vivo, e teu filho é o morto!’, e aquela diz: ‘Não, mas o teu filho é o morto e o meu filho é o vivo!’”

[[v11-3-24]]

^<<v11-3-24,24>>^ E o rei prosseguiu, dizendo: “Trazei-me uma espada.” Assim, trouxeram a espada perante o rei.

[[v11-3-25]]

^<<v11-3-25,25>>^ E o rei passou a dizer: “Cortai o menino vivo em dois e dai uma metade a uma mulher e a outra metade à outra.”

[[v11-3-26]]

^<<v11-3-26,26>>^ Imediatamente, a mulher cujo filho era o vivo disse ao rei (pois as suas emoções íntimas estavam agitadas para com o seu filho, de modo que disse): “Perdão, meu senhor! Dai-lhe o menino vivo. De modo algum o entregueis à morte.” Enquanto isso, a outra mulher dizia: “Não se tornará nem meu nem teu. Fazei o corte!”

[[v11-3-27]]

^<<v11-3-27,27>>^ Então respondeu o rei e disse: “Dai-lhe o menino vivo e de modo algum o deveis entregar à morte. Ela é sua mãe.”

[[v11-3-28]]

^<<v11-3-28,28>>^ E todo o Israel chegou a ouvir a decisão judicial que o rei havia proferido; e ficaram temerosos por causa do rei, pois viram que havia nele a sabedoria de Deus para executar decisões judiciais.

'''

xref:011-1-reis/011-1-reis-002.adoc#v11-2-0[&#60; Capítulo Anterior] | <<v11-3-0,Topo>> | xref:011-1-reis/011-1-reis-004.adoc#v11-4-0[Próximo Capítulo &#62;]