include::./index.adoc[]

[[v11-22-0]]
=== 1 Reis, 22
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v11-22-1]]

^<<v11-22-1,1>>^ E continuaram morando por três anos sem haver guerra entre a Síria e Israel.

[[v11-22-2]]

^<<v11-22-2,2>>^ E sucedeu, no terceiro ano, que Jeosafá,^&#42;1^ rei de Judá, passou a descer até o rei de Israel.

[NOTE]
====
. Significando “Jeová É Juiz”. Hebr.: Yehoh·sha·fát.
====

[[v11-22-3]]

^<<v11-22-3,3>>^ O rei de Israel disse então aos seus servos: “Sabeis realmente que Ramote-Gileade pertence a nós? Contudo, hesitamos em tirá-la da mão do rei da Síria.”

[[v11-22-4]]

^<<v11-22-4,4>>^ E ele prosseguiu, dizendo a Jeosafá: “Irás comigo à luta em Ramote-Gileade?” Então disse Jeosafá ao rei de Israel: “Eu sou como tu. Meu povo é como o teu povo. Meus cavalos são como os teus cavalos.”

[[v11-22-5]]

^<<v11-22-5,5>>^ Todavia, Jeosafá prosseguiu, dizendo ao rei de Israel: “Por favor, consulta primeiro de tudo a palavra de Jeová.”

[[v11-22-6]]

^<<v11-22-6,6>>^ Reuniu, pois, o rei de Israel os profetas, cerca de quatrocentos homens, e disse-lhes: “Devo ir contra Ramote-Gileade em guerra ou devo refrear-me?” E eles começaram a dizer: “Sobe, e Jeová^&#42;1^ [a] entregará na mão do rei.”

[NOTE]
====
. Uma das 134 mudanças de YHWH para ’Adho·naí feitas pelos escribas. Veja Ap. 1B.
====

[[v11-22-7]]

^<<v11-22-7,7>>^ Mas Jeosafá disse: “Não há aqui ainda um profeta de Jeová? Então consultemos por intermédio dele.”

[[v11-22-8]]

^<<v11-22-8,8>>^ Então disse o rei de Israel a Jeosafá: “Há ainda um homem por meio de quem se pode consultar a Jeová; mas eu mesmo certamente o odeio, pois não profetiza boas coisas a meu respeito, senão más — Micaías,^&#42;1^ filho de Inlá.” No entanto, Jeosafá disse: “Não diga o rei uma coisa dessas.”

[NOTE]
====
. Significando “Quem É Semelhante a Jeová?”. Hebr.: Mi·khá·yehu.
====

[[v11-22-9]]

^<<v11-22-9,9>>^ Por conseguinte, o rei de Israel chamou a certo oficial da corte e disse: “Traze deveras a Micaías, filho de Inlá, depressa.”

[[v11-22-10]]

^<<v11-22-10,10>>^ Ora, o rei de Israel e Jeosafá, rei de Judá, estavam sentados, cada um no seu trono, vestidos de roupagem, na eira à entrada do portão de Samaria; e todos os profetas procediam como profetas diante deles.

[[v11-22-11]]

^<<v11-22-11,11>>^ Então Zedequias, filho de Quenaaná, fez para si chifres de ferro e disse: “Assim disse Jeová: ‘Com estes marrarás os sírios até os exterminares.’”

[[v11-22-12]]

^<<v11-22-12,12>>^ E todos os outros profetas estavam profetizando a mesma coisa, dizendo: “Sobe a Ramote-Gileade e mostra-te bem sucedido; e Jeová certamente [a] entregará na mão do rei.”

[[v11-22-13]]

^<<v11-22-13,13>>^ E o mensageiro que havia ido chamar Micaías falou-lhe, dizendo: “Eis que agora as palavras dos profetas são unanimemente^&#42;1^ do que é bom para o rei. Por favor, torne-se a tua palavra igual à palavra de um deles, e tens de falar o que é bom.”

[NOTE]
====
. Lit.: “uma só boca”.
====

[[v11-22-14]]

^<<v11-22-14,14>>^ Micaías disse, porém: “Por Jeová que vive, o que Jeová me disser é o que falarei.”

[[v11-22-15]]

^<<v11-22-15,15>>^ Então entrou até o rei e o rei passou a dizer-lhe: “Micaías, devemos ir a Ramote-Gileade em guerra ou devemos refrear-nos?” Ele lhe disse imediatamente: “Sobe e mostra-te bem sucedido; e Jeová a há de dar na mão do rei.”

[[v11-22-16]]

^<<v11-22-16,16>>^ Então o rei lhe disse: “Quantas vezes te ponho sob juramento para não me falares nada senão a verdade em nome de Jeová?”

[[v11-22-17]]

^<<v11-22-17,17>>^ De modo que ele disse: “Deveras, vejo todos os israelitas espalhados pelos montes como ovelhas sem pastor.” E Jeová prosseguiu, dizendo: “Estes não têm amos.^&#42;1^ Que voltem cada um para a sua casa em paz.”

[NOTE]
====
. Ou “senhor”. Hebr.: ’adho·ním, pl. de ’a·dhóhn, para denotar excelência.
====

[[v11-22-18]]

^<<v11-22-18,18>>^ O rei de Israel disse então a Jeosafá: “Não te disse eu: ‘Ele profetizará a meu respeito não boas coisas, senão más’?”

[[v11-22-19]]

^<<v11-22-19,19>>^ E ele prosseguiu, dizendo: “Portanto, ouve a palavra de Jeová: Deveras vejo a Jeová sentado no seu trono e todo o exército dos céus em pé junto a ele, à sua direita e à sua esquerda.

[[v11-22-20]]

^<<v11-22-20,20>>^ E Jeová passou a dizer: ‘Quem logrará a Acabe, para que suba e caia em Ramote-Gileade?’ E este começou a dizer uma coisa ao passo que aquele dizia outra coisa.

[[v11-22-21]]

^<<v11-22-21,21>>^ Por fim saiu um espírito e ficou de pé perante Jeová, e disse: ‘Eu mesmo o lograrei.’ Então lhe disse Jeová: ‘Por meio de quê?’

[[v11-22-22]]

^<<v11-22-22,22>>^ A isto ele disse: ‘Sairei e certamente me tornarei um espírito enganoso na boca de todos os seus profetas.’ De modo que ele disse: ‘Tu o lograrás, e ainda mais, sairás vencedor. Sai e faze assim.’

[[v11-22-23]]

^<<v11-22-23,23>>^ E agora, eis que Jeová pôs um espírito enganoso na boca de todos estes profetas teus; mas o próprio Jeová falou de calamidade a teu respeito.”

[[v11-22-24]]

^<<v11-22-24,24>>^ Zedequias, filho de Quenaaná, aproximou-se então e deu uma bofetada em Micaías, e disse: “Por onde é que passou o espírito de Jeová de mim para falar contigo?”

[[v11-22-25]]

^<<v11-22-25,25>>^ Então disse Micaías: “Eis que estarás vendo [por onde], naquele dia em que entrarás na câmara mais recôndita para te esconder.”

[[v11-22-26]]

^<<v11-22-26,26>>^ Disse então o rei de Israel: “Toma a Micaías e faze-o voltar a Amom, chefe da cidade, e a Joás, filho do rei.

[[v11-22-27]]

^<<v11-22-27,27>>^ E tens de dizer: ‘Assim disse o rei: “Ponde a este na casa de detenção e alimentai-o com uma ração reduzida de pão e com uma ração reduzida de água até eu chegar em paz.”’”

[[v11-22-28]]

^<<v11-22-28,28>>^ A isso Micaías disse: “Se de fato voltares em paz, Jeová não falou comigo.”^&#42;1^ E acrescentou: “Ouvi, todos os povos.”

[NOTE]
====
. Ou “falou por [mim]”. Veja Núm 12:8a.
====

[[v11-22-29]]

^<<v11-22-29,29>>^ E o rei de Israel e Jeosafá, rei de Judá, passaram a subir a Ramote-Gileade.

[[v11-22-30]]

^<<v11-22-30,30>>^ O rei de Israel disse então a Jeosafá: “[Para mim é] disfarçar e entrar^&#42;1^ na batalha, mas tu, da tua parte, põe a tua roupagem.” Por conseguinte, o rei de Israel disfarçou-se e entrou na batalha.

[NOTE]
====
. “Disfarçar e entrar.” No hebr., estes verbos estão no infinitivo absoluto, indefinidos quanto ao tempo e impessoais. TLXXSy: “Cobrir-me-ei completamente e entrarei”; Vg: “Tomar armadura e entrar.”
====

[[v11-22-31]]

^<<v11-22-31,31>>^ Quanto ao rei da Síria, tinha ordenado aos trinta e dois chefes dos carros que eram dele, dizendo: “Não deveis lutar nem com pequeno nem com grande, mas somente com o rei de Israel.”

[[v11-22-32]]

^<<v11-22-32,32>>^ E sucedeu que, assim que os chefes dos carros viram Jeosafá, eles, da sua parte, disseram para si: “Por certo é este o rei de Israel.” Por isso se desviaram para ele a fim de lutar; e Jeosafá começou a clamar por socorro.

[[v11-22-33]]

^<<v11-22-33,33>>^ E sucedeu que, assim que os chefes dos carros viram que não era o rei de Israel, retornaram imediatamente de segui-lo.

[[v11-22-34]]

^<<v11-22-34,34>>^ E havia um homem que entesou o arco na sua inocência, mas foi atingir o rei de Israel entre as peças acessórias e a cota de malha, de modo que este disse ao condutor do seu carro: “Dá volta com a tua mão e leva-me para fora do acampamento, porque fui seriamente ferido.”

[[v11-22-35]]

^<<v11-22-35,35>>^ E a batalha continuou a aumentar em intensidade naquele dia, e o próprio rei teve de ser mantido em pé no seu carro, enfrentando os sírios, e por fim morreu à noitinha; e o sangue da ferida derramava-se sobre o interior do carro de guerra.

[[v11-22-36]]

^<<v11-22-36,36>>^ E por volta do pôr do sol começou a passar pelo acampamento um grito ressoante,^&#42;1^ dizendo: “Cada qual para a sua cidade e cada qual para a sua terra!”

[NOTE]
====
. Ou “e . . . o arauto”, em harmonia com LXX.
====

[[v11-22-37]]

^<<v11-22-37,37>>^ Assim morreu o rei. Quando foi trazido^&#42;1^ a Samaria, então enterraram o rei em Samaria.

[NOTE]
====
. “Foi trazido”, Vg; MSy: “ele veio”; LXX: “eles vieram”.
====

[[v11-22-38]]

^<<v11-22-38,38>>^ E começaram a lavar o carro de guerra junto ao reservatório de Samaria, e os cães lambiam o sangue dele (e ali se banhavam as próprias prostitutas), segundo a palavra de Jeová, que ele havia falado.

[[v11-22-39]]

^<<v11-22-39,39>>^ Quanto ao resto dos assuntos de Acabe e tudo o que ele fez, e a casa de marfim que construiu e todas as cidades que construiu, não estão escritos no livro dos assuntos dos dias dos reis de Israel?

[[v11-22-40]]

^<<v11-22-40,40>>^ Por fim, Acabe deitou-se com os seus antepassados; e Acazias,^&#42;1^ seu filho, começou a reinar em seu lugar.

[NOTE]
====
. Significando “Jeová se Apoderou”. Hebr.: ’Ahhaz·yá·hu.
====

[[v11-22-41]]

^<<v11-22-41,41>>^ Quanto a Jeosafá, filho de Asa, tornara-se rei sobre Judá no quarto ano de Acabe, rei de Israel.

[[v11-22-42]]

^<<v11-22-42,42>>^ Jeosafá tinha trinta e cinco anos de idade quando começou a reinar e reinou por vinte e cinco anos em Jerusalém; e o nome de sua mãe era Azuba, filha de Sili.

[[v11-22-43]]

^<<v11-22-43,43>>^ E ele andava em todo o caminho de Asa, seu pai. Não se desviou dele, fazendo o que era direito aos olhos de Jeová. Apenas os altos é que não desapareceram.^&#42;1^ O povo ainda oferecia sacrifícios e fazia fumaça sacrificial nos altos.

[NOTE]
====
. “Não desapareceram”, M; LXXSyVg: “ele não removeu”.
====

[[v11-22-44]]

^<<v11-22-44,44>>^ E Jeosafá manteve relações pacíficas com o rei de Israel.

[[v11-22-45]]

^<<v11-22-45,45>>^ Quanto ao resto dos assuntos de Jeosafá e a potência com que agiu, e como guerreou, não estão escritos no livro dos assuntos dos dias dos reis de Judá?

[[v11-22-46]]

^<<v11-22-46,46>>^ E ele eliminou do país o resto dos homens que se prostituíam no serviço dum templo, que foram deixados nos dias de Asa, seu pai.

[[v11-22-47]]

^<<v11-22-47,47>>^ No que se refere a um rei, não havia nenhum em Edom; um preposto era rei.

[[v11-22-48]]

^<<v11-22-48,48>>^ Jeosafá, da sua parte, fez navios de Társis para irem a Ofir em busca de ouro; mas não foram, porque os navios sofreram naufrágio em Eziom-Géber.

[[v11-22-49]]

^<<v11-22-49,49>>^ Foi então que Acazias, filho de Acabe, disse a Jeosafá: “Deixa os meus servos ir com os teus servos nos navios”, mas Jeosafá não consentiu nisso.

[[v11-22-50]]

^<<v11-22-50,50>>^ Por fim, Jeosafá deitou-se com os seus antepassados e foi enterrado com os seus antepassados na Cidade de Davi, seu antepassado; e Jeorão, seu filho, começou a reinar em seu lugar.

[[v11-22-51]]

^<<v11-22-51,51>>^ Quanto a Acazias, filho de Acabe, tornou-se ele rei sobre Israel em Samaria no décimo sétimo ano de Jeosafá, rei de Judá, e continuou a reinar sobre Israel por dois anos.

[[v11-22-52]]

^<<v11-22-52,52>>^ E fazia o que era mau aos olhos de Jeová e andava no caminho de seu pai, e no caminho de sua mãe, e no caminho de Jeroboão, filho de Nebate, que fizera Israel pecar.

[[v11-22-53]]

^<<v11-22-53,53>>^ E ele servia Baal e se curvava diante dele, e ofendia a Jeová, o Deus de Israel, segundo tudo o que seu pai tinha feito.

'''

xref:011-1-reis/011-1-reis-021.adoc#v11-21-0[&#60; Capítulo Anterior] | <<v11-22-0,Topo>> | xref:012-2-reis/012-2-reis-001.adoc#v12-1-0[Próximo Capítulo &#62;]