include::./index.adoc[]

[[v11-20-0]]
=== 1 Reis, 20
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v11-20-1]]

^<<v11-20-1,1>>^ ^&#42;1^ Quanto a Ben-Hadade, rei da Síria, ele reuniu todas as suas forças militares e também trinta e dois reis consigo, e cavalos e carros, e passou a subir e a sitiar Samaria, e a lutar contra ela.

[NOTE]
====
. LXX transpõe os capítulos 20 e 21; portanto, na LXX, o capítulo 21 começa aqui.
====

[[v11-20-2]]

^<<v11-20-2,2>>^ Então enviou mensageiros a Acabe, rei de Israel, na cidade. E ele foi dizer-lhe: “Assim disse Ben-Hadade:

[[v11-20-3]]

^<<v11-20-3,3>>^ ‘Tua prata e teu ouro são meus, e tuas esposas e teus filhos, os mais bem-parecidos, são meus.’”

[[v11-20-4]]

^<<v11-20-4,4>>^ A isto respondeu o rei de Israel e disse: “Segundo a tua palavra, meu senhor, o rei, sou teu com tudo o que me pertence.”

[[v11-20-5]]

^<<v11-20-5,5>>^ Mais tarde voltaram os mensageiros e disseram: “Assim disse Ben-Hadade: ‘Eu te mandei dizer: “Tua prata, e teu ouro, e tuas esposas, e teus filhos me darás.

[[v11-20-6]]

^<<v11-20-6,6>>^ Mas, por volta desta hora, amanhã, enviarei a ti os meus servos, e eles terão de dar uma busca cuidadosa na tua casa e nas casas dos teus servos; e terá de acontecer que tudo o que for desejável aos teus olhos porão na sua mão e terão de levá-lo embora.”’”

[[v11-20-7]]

^<<v11-20-7,7>>^ Em vista disso, o rei de Israel convocou todos os anciãos do país e disse: “Notai, por favor, e vede que é calamidade o que este está procurando; pois mandou [exigir] de mim as minhas esposas, e os meus filhos, e a minha prata, e o meu ouro, e eu não lhos neguei.”

[[v11-20-8]]

^<<v11-20-8,8>>^ Então lhe disseram todos os anciãos e todo o povo: “Não obedeças, e não deves consentir nisso.”

[[v11-20-9]]

^<<v11-20-9,9>>^ Portanto, ele disse aos mensageiros de Ben-Hadade: “Dizei ao meu senhor, o rei: ‘Tudo o que mandaste [exigir] do teu servo no princípio, eu farei; mas esta coisa não posso fazer.’” Com isso os mensageiros se foram e lhe trouxeram de volta a informação.

[[v11-20-10]]

^<<v11-20-10,10>>^ Ben-Hadade mandou-lhe então dizer: “Assim me façam os deuses e assim lhe acrescentem mais, se o pó de Samaria será suficiente em punhados para todo o povo que me segue!”^&#42;1^

[NOTE]
====
. Lit.: “que está junto aos meus pés!”
====

[[v11-20-11]]

^<<v11-20-11,11>>^ O rei de Israel, por sua vez, respondeu e disse: “Falai [com ele]: ‘Não se jacte aquele que se cinge como quem se descinge.’”

[[v11-20-12]]

^<<v11-20-12,12>>^ E sucedeu que, assim que ouviu esta palavra, enquanto ele mesmo e os reis bebiam nas barracas, disse imediatamente aos seus servos: “Aprontai-vos!” E começaram a aprontar-se contra a cidade.

[[v11-20-13]]

^<<v11-20-13,13>>^ E eis que se aproximou de Acabe, rei de Israel, certo profeta e disse então: “Assim disse Jeová:^&#42;1^ ‘Viste toda esta grande massa de gente? Eis que hoje a dou na tua mão e certamente saberás que eu sou Jeová.’”^&#42;2^

[NOTE]
====
. “Jeová.” Hebr.: Yehwáh; AqBurkitt usa o Tetragrama na forma dos antigos caracteres hebr. ; gr.: Ký·ri·os. Veja Ap. 1C sec. 7.
. Veja Ap. 1C sec. 7.
====

[[v11-20-14]]

^<<v11-20-14,14>>^ Acabe disse então: “Por meio de quem?” a que ele disse: “Assim disse Jeová:^&#42;1^ ‘Por meio dos moços dos príncipes dos distritos jurisdicionais.’” Por fim ele disse: “Quem abrirá a batalha?” a que ele disse: “Tu!”

[NOTE]
====
. Veja Ap. 1C sec. 7.
====

[[v11-20-15]]

^<<v11-20-15,15>>^ E ele passou a fazer a contagem dos moços dos príncipes dos distritos jurisdicionais, e eles vieram a ser duzentos e trinta e dois; e depois deles fez a contagem de todo o povo, de todos os filhos de Israel, sete mil.

[[v11-20-16]]

^<<v11-20-16,16>>^ E começaram a sair ao meio-dia, enquanto Ben-Hadade bebia nas barracas até ficar bêbedo, ele junto com os reis, os trinta e dois reis que o ajudavam.

[[v11-20-17]]

^<<v11-20-17,17>>^ Quando os moços dos príncipes dos distritos jurisdicionais saíram primeiro, Ben-Hadade mandou imediatamente [ver]; e vieram informá-lo, dizendo: “Estão saindo homens de Samaria.”

[[v11-20-18]]

^<<v11-20-18,18>>^ Então ele disse: “Quer tenham saído para paz, deveis pegá-los vivos; quer tenham saído para a batalha, vivos é que os deveis pegar.”

[[v11-20-19]]

^<<v11-20-19,19>>^ E foram estes os que saíram da cidade: os moços dos príncipes dos distritos jurisdicionais e as forças militares que estavam atrás deles.

[[v11-20-20]]

^<<v11-20-20,20>>^ E eles começaram a golpear cada um o seu homem; e os sírios puseram-se em fuga e Israel foi no encalço deles, mas Ben-Hadade, rei da Síria, conseguiu escapar num cavalo junto com os cavaleiros.

[[v11-20-21]]

^<<v11-20-21,21>>^ O rei de Israel, porém, saiu e foi golpear os cavalos e os carros, e golpeou os sírios com uma grande matança.

[[v11-20-22]]

^<<v11-20-22,22>>^ Mais tarde se aproximou o profeta do rei de Israel e disse-lhe: “Vai, fortalece-te, e percebe e vê o que vais fazer; pois, pela volta do ano^&#42;1^ o rei da Síria subirá contra ti.”

[NOTE]
====
. “Pela volta do ano”, isto é, na primavera seguinte. Veja 2Cr 36:10.
====

[[v11-20-23]]

^<<v11-20-23,23>>^ Quanto aos servos do rei da Síria, disseram-lhe: “O Deus deles é um Deus de montes.^&#42;1^ É por isso que se mostraram mais fortes do que nós. Assim, ao contrário, lutemos contra eles na planície [e vejamos] se não nos mostraremos mais fortes do que eles.

[NOTE]
====
. Ou: “Os deuses deles são deuses de montes.” Veja v. 28 n.
====

[[v11-20-24]]

^<<v11-20-24,24>>^ E faze a seguinte coisa: Remove os reis, cada um do seu lugar, e põe em lugar deles governadores.

[[v11-20-25]]

^<<v11-20-25,25>>^ Quanto a ti, deves computar para ti uma força militar igual à força militar que caiu do teu lado, cavalo por cavalo e carro por carro; e lutemos contra eles na planície [e vejamos] se não nos mostraremos mais fortes do que eles.” Conseqüentemente, ele escutou a sua voz e fez exatamente assim.

[[v11-20-26]]

^<<v11-20-26,26>>^ E sucedeu, pela volta do ano, que Ben-Hadade pôs-se a passar em revista os sírios e a subir a Afeque para a batalha contra Israel.

[[v11-20-27]]

^<<v11-20-27,27>>^ Quanto aos filhos de Israel, foram passados em revista e munidos, e começaram a sair ao encontro deles; e os filhos de Israel foram acampar-se defronte deles como dois minúsculos rebanhos de caprídeos, ao passo que os sírios, da sua parte, enchiam a terra.

[[v11-20-28]]

^<<v11-20-28,28>>^ Aproximou-se então o homem do [verdadeiro] Deus e disse ao rei de Israel, sim, ele prosseguiu, dizendo: “Assim disse Jeová: ‘Visto que os sírios disseram: “Jeová é Deus^&#42;1^ de montes e não é Deus de baixadas”, terei de entregar na tua mão toda esta grande massa de gente e certamente sabereis que eu sou Jeová.’”

[NOTE]
====
. “Deus de.” Hebr.: ’Elo·héh, pl. de ’Elóh·ah, para denotar excelência ou majestade.
====

[[v11-20-29]]

^<<v11-20-29,29>>^ E continuaram acampados por sete dias, estes defronte daqueles. E sucedeu, no sétimo dia, que começou a travar-se a batalha; e os filhos de Israel foram golpear os sírios, cem mil homens a pé, num só dia.

[[v11-20-30]]

^<<v11-20-30,30>>^ E os que sobraram puseram-se em fuga para Afeque, para a cidade; e caiu a muralha sobre vinte e sete mil homens que sobraram. Quanto a Ben-Hadade, fugiu e entrou por fim na cidade, na câmara mais recôndita.

[[v11-20-31]]

^<<v11-20-31,31>>^ Disseram-lhe, pois, os seus servos: “Ora, eis que ouvimos [dizer] que os reis da casa de Israel são reis de benevolência. Por favor, usemos de serapilheira sobre os nossos lombos e de cordas sobre as nossas cabeças, e saiamos ao rei de Israel. Talvez ele preserve viva a tua alma.”

[[v11-20-32]]

^<<v11-20-32,32>>^ Por conseguinte, cingiram-se de serapilheira sobre os seus lombos, com cordas sobre as suas cabeças, e entraram até o rei de Israel e disseram: “Teu servo Ben-Hadade disse: ‘Por favor, deixa a minha alma viver.’” A isto ele disse: “Ainda está vivo? Ele é meu irmão.”

[[v11-20-33]]

^<<v11-20-33,33>>^ Portanto, os próprios homens tomaram isso como presságio e o consideraram prontamente como decisão dele próprio, e prosseguiram, dizendo: “Ben-Hadade é teu irmão.” A isto ele disse: “Vinde, trazei-o.” Então Ben-Hadade saiu a ele; e ele o fez imediatamente subir ao carro.

[[v11-20-34]]

^<<v11-20-34,34>>^ [Ben-Hadade] disse-lhe então: “As cidades que meu pai tomou ao teu pai, eu restituirei; e designarás para ti ruas em Damasco, assim como meu pai designou em Samaria.”
“E eu, da minha parte, te mandarei embora num pacto.”
Com isso concluiu com ele um pacto e o mandou embora.

[[v11-20-35]]

^<<v11-20-35,35>>^ E certo homem dos filhos dos profetas^&#42;1^ disse ao seu amigo, pela palavra de Jeová: “Por favor, golpeia-me.” Mas o homem se negou a golpeá-lo.

[NOTE]
====
. “Dos filhos dos profetas.” Hebr.: min·benéh han·nevi·’ím; esta é a primeira ocorrência desta expressão.
====

[[v11-20-36]]

^<<v11-20-36,36>>^ Por isso lhe disse ele: “Visto que não escutaste a voz de Jeová, eis que te irás embora de mim e certamente te golpeará um leão.” Depois, este se foi do lado dele, e o leão foi achá-lo e o golpeou.

[[v11-20-37]]

^<<v11-20-37,37>>^ E ele pôs-se a achar outro homem e a dizer: “Por favor, golpeia-me.” Golpeou-o, pois, o homem, golpeando e ferindo.^&#42;1^

[NOTE]
====
. “Golpeando e ferindo.” No hebr., estes verbos estão no infinitivo absoluto, indefinidos quanto ao tempo e impessoais.
====

[[v11-20-38]]

^<<v11-20-38,38>>^ Então o profeta foi e ficou parado junto à estrada [à espera] do rei, e ele se manteve disfarçado com uma atadura sobre os seus olhos.

[[v11-20-39]]

^<<v11-20-39,39>>^ E sucedeu que, passando o rei, ele clamou ao rei e passou a dizer: “Teu servo saiu, ele próprio, entrando no grosso da batalha; e eis que saía um homem da linha e veio trazer-me um homem, e disse então: ‘Guarda este homem. Se de algum modo se der falta dele, tua alma terá de tomar o lugar da alma dele, senão terás de pesar um talento^&#42;1^ de prata.’

[NOTE]
====
. Veja Ap. 8A.
====

[[v11-20-40]]

^<<v11-20-40,40>>^ E sucedeu que, estando teu servo ativo por cá e por lá, ora, ele sumiu.” Então lhe disse o rei de Israel: “Assim é o teu próprio julgamento. Tu mesmo decidiste.”

[[v11-20-41]]

^<<v11-20-41,41>>^ Ele removeu, então, depressa a atadura de cima dos seus olhos e foi reconhecido pelo rei de Israel como sendo dos profetas.

[[v11-20-42]]

^<<v11-20-42,42>>^ Ele lhe disse então: “Assim disse Jeová: ‘Visto que deixaste escapar da tua mão o homem que me foi devotado à destruição,^&#42;1^ tua alma tem de tomar o lugar dele e teu povo o lugar de seu povo.’”

[NOTE]
====
. Lit.: “o homem da minha coisa devotada”.
====

[[v11-20-43]]

^<<v11-20-43,43>>^ Em vista disso, o rei de Israel foi embora para a sua casa, taciturno e abatido, e chegou a Samaria.

'''

xref:011-1-reis/011-1-reis-019.adoc#v11-19-0[&#60; Capítulo Anterior] | <<v11-20-0,Topo>> | xref:011-1-reis/011-1-reis-021.adoc#v11-21-0[Próximo Capítulo &#62;]