include::./index.adoc[]

[[v57-1-0]]
=== Filêmon, 1
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v57-1-1]]

^<<v57-1-1,1>>^ Paulo, prisioneiro pela causa de Cristo Jesus,^&#42;1^ e Timóteo, [nosso] irmão, a Filêmon,^&#42;2^ nosso amado e nosso colaborador,

[NOTE]
====
. Ou “prisioneiro de Cristo Jesus”.
. “A Filêmon.” Gr.: Fi·lé·mo·ni, significando “Amoroso”.
====

[[v57-1-2]]

^<<v57-1-2,2>>^ e a Áfia, nossa irmã, e a Arquipo, nosso soldado companheiro, e à congregação que está na tua casa:

[[v57-1-3]]

^<<v57-1-3,3>>^ Que tenhais benignidade imerecida e paz da parte de Deus, nosso Pai, e do Senhor Jesus Cristo.

[[v57-1-4]]

^<<v57-1-4,4>>^ Sempre agradeço a meu Deus ao fazer menção de ti nas minhas orações,

[[v57-1-5]]

^<<v57-1-5,5>>^ pois continuo a ouvir [falar] do teu amor e da fé que tens para com o Senhor Jesus e para com todos os santos,

[[v57-1-6]]

^<<v57-1-6,6>>^ a fim de que entre em ação^&#42;1^ a partilha da tua fé por reconheceres^&#42;2^ toda boa coisa entre nós como relacionada com o Cristo.

[NOTE]
====
. “Entre em ação.” Lit.: “se torne operante no íntimo”.
. “Por reconheceres.” Lit.: “em conhecimento exato”.
====

[[v57-1-7]]

^<<v57-1-7,7>>^ Pois tive muita alegria e consolo com o teu amor, visto que as ternas afeições^&#42;1^ dos santos foram reanimadas por intermédio de ti, irmão.

[NOTE]
====
. “As ternas afeições.” Lit.: “as entranhas”.
====

[[v57-1-8]]

^<<v57-1-8,8>>^ Por esta mesma razão, embora eu tenha muita franqueza no falar em conexão com Cristo para te ordenar a fazer o que é correto,

[[v57-1-9]]

^<<v57-1-9,9>>^ exorto-te^&#42;1^ antes à base do amor, visto que eu sou o que sou, Paulo, homem idoso,^&#42;2^ sim, agora também prisioneiro pela causa de Cristo Jesus;

[NOTE]
====
. Lit.: “incentivo-te”.
. Ou “embaixador”.
====

[[v57-1-10]]

^<<v57-1-10,10>>^ exorto-te concernente a meu filho, para quem me tornei pai enquanto estava nas minhas cadeias, Onésimo,^&#42;1^

[NOTE]
====
. “Onésimo”, significando “Proveitoso”.
====

[[v57-1-11]]

^<<v57-1-11,11>>^ anteriormente inútil para ti, mas agora útil para ti e para mim.

[[v57-1-12]]

^<<v57-1-12,12>>^ A este mesmo eu te mando de volta, sim, a ele, isto é, as minhas próprias ternas afeições.^&#42;1^

[NOTE]
====
. Veja v. 7 n.
====

[[v57-1-13]]

^<<v57-1-13,13>>^ Eu gostaria de retê-lo para mim, a fim de que, em vez de [ministrar] a ti, estivesse ministrando^&#42;1^ a mim nas cadeias que levo pela causa das boas novas.^&#42;2^

[NOTE]
====
. Lit.: “servisse”.
. Ou “nas cadeias das boas novas”.
====

[[v57-1-14]]

^<<v57-1-14,14>>^ Mas, sem consentimento teu, não quero fazer nada, para que o teu bom ato não seja como que sob compulsão,^&#42;1^ mas de tua própria livre vontade.^&#42;2^

[NOTE]
====
. Lit.: “necessidade”.
. Lit.: “mas segundo o que é voluntário”.
====

[[v57-1-15]]

^<<v57-1-15,15>>^ Talvez seja realmente por esta razão que ele escapou por uma hora, para que o tenhas de volta para sempre,

[[v57-1-16]]

^<<v57-1-16,16>>^ não mais como escravo, mas, como mais do que escravo, como irmão amado, especialmente por mim, no entanto, quanto mais por ti, tanto na relação carnal como no Senhor.

[[v57-1-17]]

^<<v57-1-17,17>>^ Portanto, se me considerares parceiro, recebe-o bondosamente como farias comigo.

[[v57-1-18]]

^<<v57-1-18,18>>^ Além disso, se ele te fez alguma injustiça ou te deve algo, põe isso na minha conta.^&#42;1^

[NOTE]
====
. Lit.: “a mim me põe isso na conta”.
====

[[v57-1-19]]

^<<v57-1-19,19>>^ Eu, Paulo, estou escrevendo isso com a minha própria mão: Eu o pagarei de volta — para não te dizer que, além disso, tu me deves até mesmo a ti próprio.

[[v57-1-20]]

^<<v57-1-20,20>>^ Sim, irmão, derive eu lucro de ti em conexão com [o] Senhor: reanima as minhas ternas afeições em conexão com Cristo.

[[v57-1-21]]

^<<v57-1-21,21>>^ Escrevo-te confiante no teu acatamento,^&#42;1^ sabendo que farás ainda mais do que as coisas que digo.

[NOTE]
====
. Lit.: “obediência”.
====

[[v57-1-22]]

^<<v57-1-22,22>>^ Mas, ao mesmo tempo, apronta também pousada para mim, pois espero que, por intermédio das vossas orações, serei posto em liberdade para vós.

[[v57-1-23]]

^<<v57-1-23,23>>^ Mandam-te cumprimentos Epafras, companheiro meu de cativeiro em união com Cristo,

[[v57-1-24]]

^<<v57-1-24,24>>^ [e também] Marcos, Aristarco, Demas [e] Lucas, meus colaboradores.

[[v57-1-25]]

^<<v57-1-25,25>>^ A benignidade imerecida do Senhor Jesus Cristo [seja] com o espírito que vós [mostrais].^&#42;1^

[NOTE]
====
. Lit.: “com o vosso espírito”.
====

'''

xref:056-tito/056-tito-003.adoc#v56-3-0[&#60; Capítulo Anterior] | <<v57-1-0,Topo>> | xref:058-hebreus/058-hebreus-001.adoc#v58-1-0[Próximo Capítulo &#62;]