include::./index.adoc[]

[[v42-24-0]]
=== Lucas, 24
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v42-24-1]]

^<<v42-24-1,1>>^ No primeiro dia da semana, porém, foram muito cedo ao túmulo, levando os aromas que tinham preparado.

[[v42-24-2]]

^<<v42-24-2,2>>^ Mas, acharam a pedra rolada [da frente] do túmulo memorial,

[[v42-24-3]]

^<<v42-24-3,3>>^ e, quando entraram, não acharam o corpo do Senhor Jesus.^&#42;1^

[NOTE]
====
. “Do Senhor Jesus”, P75אABCWVgSyhArm; DItmss. omitem isso.
====

[[v42-24-4]]

^<<v42-24-4,4>>^ Enquanto estavam perplexas sobre isso, eis que pararam ao lado delas dois homens em vestuário reluzente.

[[v42-24-5]]

^<<v42-24-5,5>>^ Visto que as [mulheres] ficaram amedrontadas e mantinham os rostos voltados para o chão, os [homens] disseram-lhes: “Por que estais procurando o Vivente entre os mortos?

[[v42-24-6]]

^<<v42-24-6,6>>^ [[Ele não está aqui, mas foi levantado.]]^&#42;1^ Lembrai-vos de como vos falou enquanto ainda estava na Galiléia,

[NOTE]
====
. “Ele não está aqui, mas foi levantado”, P75אABVgSyArm; DItmss. omitem isso.
====

[[v42-24-7]]

^<<v42-24-7,7>>^ dizendo que o Filho do homem tinha de ser entregue às mãos de homens pecaminosos e ser pregado numa estaca,^&#42;1^ sendo, no entanto, levantado no terceiro dia.”

[NOTE]
====
. Ou “fixado numa estaca (poste)”. Veja Ap. 5C.
====

[[v42-24-8]]

^<<v42-24-8,8>>^ Lembraram-se assim das suas declarações,

[[v42-24-9]]

^<<v42-24-9,9>>^ e voltaram do túmulo memorial^&#42;1^ e relataram todas estas coisas aos onze e a todo o resto.

[NOTE]
====
. “Do túmulo memorial”, P75אABWVgSy; DItmss.Arm omitem isso.
====

[[v42-24-10]]

^<<v42-24-10,10>>^ Eram Maria Madalena e Joana, e Maria, [mãe] de Tiago. Também as demais mulheres com elas estavam contando estas coisas aos apóstolos.

[[v42-24-11]]

^<<v42-24-11,11>>^ No entanto, estas declarações pareciam-lhes tolice e não acreditavam nas [mulheres].
[[

[[v42-24-12]]

^<<v42-24-12,12>>^ Mas Pedro levantou-se e correu para o túmulo memorial, e, inclinando-se para a frente, viu somente as faixas. Ele foi assim embora, perguntando-se o que tinha ocorrido.]]^&#42;1^

[NOTE]
====
. Segundo P75אABWVgSy; DItmss. omitem estas palavras entre colchetes.
====

[[v42-24-13]]

^<<v42-24-13,13>>^ Mas, eis que naquele mesmo dia dois deles estavam caminhando para uma aldeia, cerca de onze quilômetros^&#42;1^ distante de Jerusalém, de nome Emaús,

[NOTE]
====
. Ou “sete e meia milhas [romanas]”. Lit.: “sessenta estádios”. Gr.: sta·dí·ous he·xé·kon·ta; lat.: sta·di·ó·rum se·xa·gín·ta; cerca de 11 km. Compare isso com Mt 5:41 n.; veja Ap. 8A.
====

[[v42-24-14]]

^<<v42-24-14,14>>^ e estavam conversando entre si sobre todas essas coisas que tinham acontecido.

[[v42-24-15]]

^<<v42-24-15,15>>^ Ora, enquanto conversavam e palestravam, aproximou-se o próprio Jesus e começou a andar com eles;

[[v42-24-16]]

^<<v42-24-16,16>>^ mas os olhos deles foram impedidos de reconhecê-lo.

[[v42-24-17]]

^<<v42-24-17,17>>^ Ele lhes disse: “Que assuntos são estes que debateis entre vós enquanto estais caminhando?” E eles ficaram parados de rostos tristes.

[[v42-24-18]]

^<<v42-24-18,18>>^ Em resposta disse-lhe aquele que tinha o nome de Cléopas: “Moras sozinho, como forasteiro, em Jerusalém, e não sabes as coisas que ocorreram nela nestes dias?”

[[v42-24-19]]

^<<v42-24-19,19>>^ E ele lhes disse: “Que coisas?” Disseram-lhe: “As coisas a respeito de Jesus, o nazareno, que se tornou profeta poderoso em obras e palavra perante Deus e todo o povo;

[[v42-24-20]]

^<<v42-24-20,20>>^ e como os nossos principais sacerdotes e governantes o entregaram à sentença de morte e o pregaram numa estaca.

[[v42-24-21]]

^<<v42-24-21,21>>^ Mas nós esperávamos que este [homem] fosse o destinado a livrar Israel; sim, e além de todas estas coisas, este já é o terceiro dia desde que essas coisas ocorreram.

[[v42-24-22]]

^<<v42-24-22,22>>^ Além disso, certas mulheres dentre nós também nos assombraram, porque tinham ido cedo ao túmulo memorial,

[[v42-24-23]]

^<<v42-24-23,23>>^ mas, não achando seu corpo, voltaram dizendo que tiveram também uma visão sobrenatural de anjos, que disseram que ele estava vivo.

[[v42-24-24]]

^<<v42-24-24,24>>^ Ademais, alguns dos que estavam conosco foram ao túmulo memorial; e acharam que era assim, exatamente como as mulheres disseram, mas não o viram.”

[[v42-24-25]]

^<<v42-24-25,25>>^ Disse-lhes assim: “Ó insensatos e vagarosos de coração no que se refere a crer em todas as coisas faladas pelos profetas!

[[v42-24-26]]

^<<v42-24-26,26>>^ Não era necessário que o Cristo sofresse estas coisas e que entrasse na sua glória?”

[[v42-24-27]]

^<<v42-24-27,27>>^ E, principiando por Moisés e por todos os Profetas, interpretou-lhes em todas as Escrituras as coisas referentes a si mesmo.

[[v42-24-28]]

^<<v42-24-28,28>>^ Por fim chegaram perto da aldeia para a qual caminhavam, e ele fez como se fosse caminhar mais para diante.

[[v42-24-29]]

^<<v42-24-29,29>>^ Mas eles exerceram pressão sobre ele, dizendo: “Fica conosco, porque já está anoitecendo e o dia já está declinando.” Em vista disso, entrou para ficar com eles.

[[v42-24-30]]

^<<v42-24-30,30>>^ E, ao se recostar com eles à mesa, tomou o pão, abençoou-o, partiu-o e começou a dar-lho.

[[v42-24-31]]

^<<v42-24-31,31>>^ Com isso abriram-se-lhes plenamente os olhos e o reconheceram; e ele desapareceu de diante deles.

[[v42-24-32]]

^<<v42-24-32,32>>^ E disseram um ao outro: “Não se nos abrasavam^&#42;1^ os corações quando nos falava na estrada, ao nos abrir plenamente as Escrituras?”

[NOTE]
====
. “Abrasavam”, אAB; D: “estavam velados”; Syp,s: “estavam pesados”; Itms. l: “estavam obtusos”; Itms. c: “estavam cegos”.
====

[[v42-24-33]]

^<<v42-24-33,33>>^ E eles se levantaram naquela mesma hora e voltaram a Jerusalém, e acharam reunidos os onze e os com eles,

[[v42-24-34]]

^<<v42-24-34,34>>^ que diziam: “O Senhor^&#42;1^ foi de fato levantado e apareceu a Simão!”

[NOTE]
====
. Ou “Amo”.
====

[[v42-24-35]]

^<<v42-24-35,35>>^ Eles mesmos relataram então os [eventos ocorridos] na estrada e como foi reconhecido por eles pelo partir do pão.

[[v42-24-36]]

^<<v42-24-36,36>>^ Enquanto ainda falavam destas coisas, ele mesmo estava em pé no meio deles [[e disse-lhes: “Paz seja convosco.”]]^&#42;1^

[NOTE]
====
. “E disse-lhes . . . convosco”, P75אAB; DIt omitem isso.
====

[[v42-24-37]]

^<<v42-24-37,37>>^ Mas, visto que estavam apavorados e tinham ficado amedrontados, imaginavam ver um espírito.

[[v42-24-38]]

^<<v42-24-38,38>>^ De modo que lhes disse: “Por que estais aflitos e por que é que se levantam dúvidas nos vossos corações?

[[v42-24-39]]

^<<v42-24-39,39>>^ Vede minhas mãos e meus pés, que sou eu mesmo; apalpai-me e vede, porque um espírito não tem carne e ossos assim como observais que eu tenho.”

[[v42-24-40]]

^<<v42-24-40,40>>^ [[E, dizendo isso, mostrou-lhes suas mãos e seus pés.]]^&#42;1^

[NOTE]
====
. Segundo P75אABWVgSyh,hi,pArm (veja Jo 20:20); DItSyc,s omitem o v. 40.
====

[[v42-24-41]]

^<<v42-24-41,41>>^ Mas, não acreditando eles ainda de pura alegria e admirando-se, disse-lhes: “Tendes aqui algo para comer?”

[[v42-24-42]]

^<<v42-24-42,42>>^ E entregaram-lhe um pedaço de peixe assado;^&#42;1^

[NOTE]
====
. VgSyc,p e mss. ENXΔΘ (do sexto ao décimo séc.) acrescentam: “e um favo de mel”; P75אABDSys omitem isso.
====

[[v42-24-43]]

^<<v42-24-43,43>>^ e ele o tomou e comeu diante dos seus olhos.

[[v42-24-44]]

^<<v42-24-44,44>>^ Disse-lhes então: “Estas são as minhas palavras que vos falei enquanto ainda estava convosco, que todas as coisas escritas na lei de Moisés, e nos Profetas, e nos Salmos, a respeito de mim, têm de se cumprir.”

[[v42-24-45]]

^<<v42-24-45,45>>^ Abriu-lhes então plenamente as mentes para que compreendessem o significado das Escrituras

[[v42-24-46]]

^<<v42-24-46,46>>^ e disse-lhes: “Assim está escrito que o Cristo havia de sofrer e de ser levantado dentre os mortos no terceiro dia,

[[v42-24-47]]

^<<v42-24-47,47>>^ e que, à base do seu nome, se havia de pregar arrependimento para o perdão de pecados, em todas as nações — principiando por Jerusalém,

[[v42-24-48]]

^<<v42-24-48,48>>^ haveis de ser testemunhas destas coisas.

[[v42-24-49]]

^<<v42-24-49,49>>^ E eis que vos estou enviando o que foi prometido por meu Pai. Vós, porém, permanecei na cidade até serdes revestidos de poder vindo do alto.”

[[v42-24-50]]

^<<v42-24-50,50>>^ Mas ele os conduziu para fora, até Betânia, e, erguendo as suas mãos, abençoou-os.

[[v42-24-51]]

^<<v42-24-51,51>>^ Enquanto os abençoava, foi separado deles e começou a ser levado para o céu.^&#42;1^

[NOTE]
====
. “E começou a ser levado para o céu”, P75אcABCWVgSypArm; א°DSys omitem isso.
====

[[v42-24-52]]

^<<v42-24-52,52>>^ E prestaram-lhe homenagem e^&#42;1^ voltaram para Jerusalém com grande alegria.

[NOTE]
====
. “Prestaram-lhe homenagem e”, P75אABCWSyh,p; DItmss.Sys omitem isso. Veja He 1:6.
====

[[v42-24-53]]

^<<v42-24-53,53>>^ E estavam continuamente no templo, bendizendo a Deus.

'''

xref:042-lucas/042-lucas-023.adoc#v42-23-0[&#60; Capítulo Anterior] | <<v42-24-0,Topo>> | xref:043-joao/043-joao-001.adoc#v43-1-0[Próximo Capítulo &#62;]