include::./index.adoc[]

[[v42-2-0]]
=== Lucas, 2
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v42-2-1]]

^<<v42-2-1,1>>^ Ora, naqueles dias saiu um decreto da parte de César^&#42;1^ Augusto, para que toda a terra habitada^&#42;2^ se registrasse;

[NOTE]
====
. Ou “Imperador”. Lat.: Caé·sa·re.
. Lit.: “a habitada”. Gr.: ten oi·kou·mé·nen, fem. sing., referindo-se à terra.
====

[[v42-2-2]]

^<<v42-2-2,2>>^ (este primeiro registro ocorreu quando Quirino era governador da Síria;)

[[v42-2-3]]

^<<v42-2-3,3>>^ e todos viajaram para se registrarem, cada um na sua própria cidade.

[[v42-2-4]]

^<<v42-2-4,4>>^ José, naturalmente, subiu também da Galiléia, da cidade de Nazaré, e foi à Judéia, à cidade de Davi, que se chama Belém, por ser membro da casa e família de Davi,

[[v42-2-5]]

^<<v42-2-5,5>>^ a fim de ser registrado com Maria, que lhe fora dada em casamento, conforme prometido, nesta ocasião já em estado avançado de gravidez.

[[v42-2-6]]

^<<v42-2-6,6>>^ Enquanto estavam ali, completaram-se os dias para ela dar à luz.

[[v42-2-7]]

^<<v42-2-7,7>>^ E ela deu à luz o seu filho, o primogênito, e o enfaixou e deitou numa manjedoura, porque não havia lugar para eles no alojamento.^&#42;1^

[NOTE]
====
. Ou “sala dos hóspedes”. Veja Mr 14:14.
====

[[v42-2-8]]

^<<v42-2-8,8>>^ Havia também no mesmo país pastores vivendo ao ar livre^&#42;1^ e mantendo de noite vigílias sobre os seus rebanhos.

[NOTE]
====
. Ou “morando nos campos”.
====

[[v42-2-9]]

^<<v42-2-9,9>>^ E, repentinamente estava parado ao lado deles o anjo de Jeová,^&#42;1^ e a glória de Jeová^&#42;2^ reluzia em volta deles, e ficaram muito temerosos.

[NOTE]
====
. Veja Ap. 1D.
. Veja Ap. 1D.
====

[[v42-2-10]]

^<<v42-2-10,10>>^ Mas o anjo disse-lhes: “Não temais, pois, eis que vos declaro boas novas duma grande alegria que todo o povo terá,

[[v42-2-11]]

^<<v42-2-11,11>>^ porque hoje vos nasceu na cidade de Davi um Salvador, que é^&#42;1^ Cristo, [o] Senhor.^&#42;2^

[NOTE]
====
. Ou “há de ser”.
. “Cristo, [o] Senhor.” Gr.: Khri·stós ký·ri·os. Esta expressão talvez seja uma versão grega do hebr. ma·shí·ahh Yeho·wáh, “Cristo de Jeová”, como em J5-8,10. Veja 2:26.
====

[[v42-2-12]]

^<<v42-2-12,12>>^ E este é um sinal para vós: achareis uma criança enfaixada e deitada numa manjedoura.”

[[v42-2-13]]

^<<v42-2-13,13>>^ E, repentinamente houve com o anjo uma multidão do exército^&#42;1^ celestial, louvando a Deus e dizendo:

[NOTE]
====
. Ou “da hoste”. Lat.: mi·lí·ti·ae.
====

[[v42-2-14]]

^<<v42-2-14,14>>^ “Glória a Deus nas maiores alturas, e na terra paz entre homens de boa vontade.”^&#42;1^

[NOTE]
====
. Ou “homens que ele aprova”. Gr.: an·thró·pois eu·do·kí·as.
====

[[v42-2-15]]

^<<v42-2-15,15>>^ Assim, quando os anjos se afastaram deles para o céu, os pastores começaram a dizer uns aos outros: “Vamos de todos os modos até Belém e vejamos esta coisa que ocorreu, que Jeová^&#42;1^ nos fez saber.”

[NOTE]
====
. Veja Ap. 1D.
====

[[v42-2-16]]

^<<v42-2-16,16>>^ E foram apressadamente e acharam Maria, bem como José, e a criança deitada na manjedoura.

[[v42-2-17]]

^<<v42-2-17,17>>^ Quando a viram, fizeram saber a declaração que se lhes fizera a respeito desta criancinha.

[[v42-2-18]]

^<<v42-2-18,18>>^ E todos os que ouviram [isso] maravilhavam-se com as coisas que os pastores lhes contavam;

[[v42-2-19]]

^<<v42-2-19,19>>^ Maria, porém começou a preservar todas essas declarações, tirando conclusões no seu coração.

[[v42-2-20]]

^<<v42-2-20,20>>^ Os pastores voltaram então, glorificando e louvando a Deus por todas as coisas que ouviram e viram, exatamente como se lhes dissera.

[[v42-2-21]]

^<<v42-2-21,21>>^ Então, quando se completaram os oito dias para que fosse circuncidado, deram-lhe também o nome de Jesus,^&#42;1^ nome dado pelo anjo antes de ele ter sido concebido na madre.

[NOTE]
====
. Veja Mt 1:21 n.
====

[[v42-2-22]]

^<<v42-2-22,22>>^ Completando-se também os dias para a purificação deles, segundo a lei de Moisés, trouxeram-no a Jerusalém para o apresentarem a Jeová,^&#42;1^

[NOTE]
====
. Veja Ap. 1D.
====

[[v42-2-23]]

^<<v42-2-23,23>>^ assim como está escrito na lei de Jeová:^&#42;1^ “Todo macho que abre a madre tem de ser chamado santo para Jeová”,^&#42;2^

[NOTE]
====
. Veja Ap. 1D.
. Veja Ap. 1D.
====

[[v42-2-24]]

^<<v42-2-24,24>>^ e para oferecer sacrifício segundo o que se diz na lei de Jeová:^&#42;1^ “Um par de rolas ou dois pombos novos.”

[NOTE]
====
. Veja Ap. 1D.
====

[[v42-2-25]]

^<<v42-2-25,25>>^ E, eis que havia em Jerusalém um homem de nome Simeão, e este homem era justo e reverente, esperando a consolação de Israel, e espírito santo estava sobre ele.

[[v42-2-26]]

^<<v42-2-26,26>>^ Ademais, fora-lhe divinamente revelado, pelo espírito santo, que não veria a morte antes de ter visto o Cristo de Jeová.^&#42;1^

[NOTE]
====
. Veja Ap. 1D.
====

[[v42-2-27]]

^<<v42-2-27,27>>^ Assim, sob o poder do espírito, ele veio ao templo; e quando os pais trouxeram para dentro o menino Jesus, a fim de fazerem para ele segundo a prática costumeira da lei,

[[v42-2-28]]

^<<v42-2-28,28>>^ foi ele mesmo quem o recebeu nos braços e bendisse a Deus, e disse:

[[v42-2-29]]

^<<v42-2-29,29>>^ “Agora, Soberano Senhor,^&#42;1^ deixas o teu escravo ir livre em paz, segundo a tua declaração;

[NOTE]
====
. “Soberano Senhor”, אAB; gr.: dé·spo·ta; J7,8,10,13,16,17,22(hebr.): ’Adho·naí; J9,18: “Jeová”.
====

[[v42-2-30]]

^<<v42-2-30,30>>^ porque os meus olhos viram o teu meio de salvar,

[[v42-2-31]]

^<<v42-2-31,31>>^ que aprontaste à vista de todos os povos,

[[v42-2-32]]

^<<v42-2-32,32>>^ uma luz para remover das nações o véu^&#42;1^ e uma glória para o teu povo Israel.”

[NOTE]
====
. Ou “uma luz para uma revelação das nações”.
====

[[v42-2-33]]

^<<v42-2-33,33>>^ E o pai e a mãe [do menino] admiravam-se das coisas que se falavam dele.

[[v42-2-34]]

^<<v42-2-34,34>>^ Simeão os abençoou também, mas disse a Maria, a mãe [do menino]: “Eis que este é posto para a queda e para o novo levantamento^&#42;1^ de muitos em Israel, e para sinal contra que se fale

[NOTE]
====
. Ou “a ressurreição”. Gr.: a·ná·sta·sin. Veja Mt 22:23 n.
====

[[v42-2-35]]

^<<v42-2-35,35>>^ (sim, uma longa espada traspassará a tua própria alma),^&#42;1^ a fim de que sejam desvendados os raciocínios de muitos corações.”

[NOTE]
====
. Ou “vida”. Gr.: psy·khén. Veja Ap. 4A.
====

[[v42-2-36]]

^<<v42-2-36,36>>^ Havia também Ana, uma profetisa, filha de Fanuel, da tribo de Aser (esta mulher estava bem avançada em anos e tinha vivido com um marido por sete anos, desde a sua virgindade,

[[v42-2-37]]

^<<v42-2-37,37>>^ e ela era viúva, já com oitenta e quatro anos de idade), que nunca estava ausente do templo, prestando noite e dia serviço sagrado,^&#42;1^ com jejuns e súplicas.

[NOTE]
====
. Ou “prestando . . . adoração”. Gr.: la·treú·ou·sa; J22(hebr.): be‛ov·dháh, “em ela servir (adorar)”. Veja Êx 3:12 n.
====

[[v42-2-38]]

^<<v42-2-38,38>>^ E ela se aproximou naquela mesma hora e começou a dar graças a Deus^&#42;1^ e a falar sobre [a criança]^&#42;2^ a todos os que aguardavam o livramento de Jerusalém.

[NOTE]
====
. “Deus”, אAB; VgSyp,s: “ao Senhor”; J5,7-17,28: “a Jeová”.
. Lit.: “sobre ela [ou: ele]”.
====

[[v42-2-39]]

^<<v42-2-39,39>>^ Tendo assim executado todas as coisas segundo a lei de Jeová,^&#42;1^ voltaram à Galiléia, à sua própria cidade de Nazaré.

[NOTE]
====
. Veja Ap. 1D.
====

[[v42-2-40]]

^<<v42-2-40,40>>^ E o menino continuava a crescer e a ficar forte, estando cheio de sabedoria, e o favor de Deus continuava com ele.

[[v42-2-41]]

^<<v42-2-41,41>>^ Ora, de ano em ano, seus pais costumavam ir a Jerusalém para a festividade da páscoa.

[[v42-2-42]]

^<<v42-2-42,42>>^ E quando ele atingiu os doze anos de idade, subiram segundo o costume da festividade

[[v42-2-43]]

^<<v42-2-43,43>>^ e completaram os dias. Mas, ao voltarem, o menino Jesus permaneceu em Jerusalém e seus pais não notaram isso.

[[v42-2-44]]

^<<v42-2-44,44>>^ Presumindo que ele estivesse na companhia dos que viajavam juntos, cobriram a distância de um dia e então começaram a ir em busca dele entre os parentes e conhecidos.

[[v42-2-45]]

^<<v42-2-45,45>>^ Mas, não o encontrando, voltaram a Jerusalém, indo diligentemente à procura dele.

[[v42-2-46]]

^<<v42-2-46,46>>^ Bem, depois de três dias, acharam-no no templo, sentado no meio dos instrutores, e escutando-os e interrogando-os.

[[v42-2-47]]

^<<v42-2-47,47>>^ Mas, todos os que o escutavam ficavam constantemente pasmados com o seu entendimento e suas respostas.

[[v42-2-48]]

^<<v42-2-48,48>>^ Ora, quando o viram, ficaram assombrados, e sua mãe disse-lhe: “Filho, por que nos tratas deste modo? Eis que teu pai e eu, em aflição mental, estivemos à tua procura.”

[[v42-2-49]]

^<<v42-2-49,49>>^ Mas ele lhes disse: “Por que tivestes de ir à minha procura? Não sabíeis que eu tenho de estar na [casa] de meu Pai?”

[[v42-2-50]]

^<<v42-2-50,50>>^ No entanto, não compreenderam a declaração que lhes fizera.

[[v42-2-51]]

^<<v42-2-51,51>>^ E ele desceu com eles e chegou a Nazaré, e continuou a estar-lhes sujeito. Sua mãe, também, guardava cuidadosamente todas essas declarações^&#42;1^ no coração.

[NOTE]
====
. Ou “coisas”. Gr.: rhé·ma·ta. Veja 1:37 n.
====

[[v42-2-52]]

^<<v42-2-52,52>>^ E Jesus progredia em sabedoria e em desenvolvimento físico, e no favor de Deus e dos homens.

'''

xref:042-lucas/042-lucas-001.adoc#v42-1-0[&#60; Capítulo Anterior] | <<v42-2-0,Topo>> | xref:042-lucas/042-lucas-003.adoc#v42-3-0[Próximo Capítulo &#62;]