include::./index.adoc[]

[[v42-5-0]]
=== Lucas, 5
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v42-5-1]]

^<<v42-5-1,1>>^ Em certa ocasião, quando a multidão o apertava e escutava a palavra de Deus, ele estava parado à beira do lago de Genesaré.

[[v42-5-2]]

^<<v42-5-2,2>>^ E viu dois barcos atracados à beira do lago, mas os pescadores tinham desembarcado e lavavam as suas redes.

[[v42-5-3]]

^<<v42-5-3,3>>^ Embarcando num dos barcos, que era o de Simão, pediu-lhe que o afastasse um pouco da terra. Assentou-se então, e, de dentro do barco, começou a ensinar as multidões.

[[v42-5-4]]

^<<v42-5-4,4>>^ Quando parou de falar, disse a Simão: “Rema para onde é fundo, e abaixai as vossas redes para uma pesca.”

[[v42-5-5]]

^<<v42-5-5,5>>^ Simão, porém, disse em resposta: “Preceptor, labutamos toda a noite e não apanhamos nada, mas, ao teu pedido, abaixarei as redes.”

[[v42-5-6]]

^<<v42-5-6,6>>^ Pois bem, quando fizeram isso, cercaram uma grande multidão de peixes. De fato, suas redes começaram a romper-se.

[[v42-5-7]]

^<<v42-5-7,7>>^ Acenaram então para os seus associados no outro barco, para que viessem e os auxiliassem; e eles vieram, e encheram ambos os barcos, de modo que estes começaram a afundar-se.

[[v42-5-8]]

^<<v42-5-8,8>>^ Vendo isso, Simão Pedro prostrou-se aos joelhos de Jesus, dizendo: “Afasta-te de mim, porque sou homem pecaminoso, Senhor.”^&#42;1^

[NOTE]
====
. Ou “Amo”.
====

[[v42-5-9]]

^<<v42-5-9,9>>^ Pois à vista da safra de peixes que apanharam, tanto ele como os com ele foram tomados de assombro,

[[v42-5-10]]

^<<v42-5-10,10>>^ e assim também Tiago e João, filhos de Zebedeu, que eram parceiros de Simão. Mas Jesus disse a Simão: “Pára de estar com medo. Doravante apanharás vivos a homens.”

[[v42-5-11]]

^<<v42-5-11,11>>^ Trouxeram assim os barcos de volta à terra, abandonaram tudo e o seguiram.

[[v42-5-12]]

^<<v42-5-12,12>>^ Em outra ocasião, enquanto ele estava numa das cidades, eis um homem cheio de lepra! Quando avistou Jesus, prostrou-se com o rosto [em terra] e rogou-lhe, dizendo: “Senhor, se apenas quiseres, podes tornar-me limpo.”

[[v42-5-13]]

^<<v42-5-13,13>>^ E assim, estendendo a sua mão, tocou nele, dizendo: “Eu quero. Torna-te limpo.” E a lepra desapareceu dele imediatamente.

[[v42-5-14]]

^<<v42-5-14,14>>^ E ele deu ao homem ordens de não [o] contar a ninguém: “Mas vai e mostra-te ao sacerdote, e faze uma oferta em conexão com a tua purificação, assim como Moisés determinou, em testemunho^&#42;1^ para eles.”

[NOTE]
====
. “Testemunho.” Gr.: mar·tý·ri·on; lat.: te·sti·mó·ni·um.
====

[[v42-5-15]]

^<<v42-5-15,15>>^ Mas a palavra a respeito dele espalhava-se tanto mais, e grandes multidões reuniam-se para escutar e para ser curadas de suas doenças.

[[v42-5-16]]

^<<v42-5-16,16>>^ No entanto, ele continuava em retiro nos desertos e orava.

[[v42-5-17]]

^<<v42-5-17,17>>^ No decorrer de um desses dias, ele estava ensinando, e havia ali sentados fariseus e instrutores da lei, que haviam chegado de toda aldeia da Galiléia e da Judéia, e de Jerusalém; e o poder de Jeová^&#42;1^ estava presente para ele fazer curas.

[NOTE]
====
. Veja Ap. 1D.
====

[[v42-5-18]]

^<<v42-5-18,18>>^ E, eis uns homens carregando numa cama um homem paralítico, e eles buscavam um meio de levá-lo para dentro e de colocá-lo diante dele.

[[v42-5-19]]

^<<v42-5-19,19>>^ Assim, não encontrando meio de levá-lo para dentro, por causa da multidão, subiram ao telhado e baixaram-no por entre as telhas, com a pequena cama, no meio dos que [estavam] na frente de Jesus.

[[v42-5-20]]

^<<v42-5-20,20>>^ E, quando ele viu a fé que tinham, disse: “Homem, teus pecados te estão perdoados.”

[[v42-5-21]]

^<<v42-5-21,21>>^ Em conseqüência disso, os escribas e os fariseus principiaram a raciocinar, dizendo: “Quem é este que fala blasfêmias? Quem pode perdoar pecados senão somente Deus?”

[[v42-5-22]]

^<<v42-5-22,22>>^ Mas Jesus, discernindo os seus raciocínios, disse-lhes em resposta: “O que estais raciocinando em vossos corações?

[[v42-5-23]]

^<<v42-5-23,23>>^ O que é mais fácil, dizer: ‘Teus pecados te estão perdoados’, ou dizer: ‘Levanta-te e anda’?

[[v42-5-24]]

^<<v42-5-24,24>>^ Mas, a fim de que saibais que o Filho do homem tem na terra autoridade para perdoar pecados —” ele disse ao paralítico: “Eu te digo: Levanta-te, apanha a tua pequena cama e vai para casa.”

[[v42-5-25]]

^<<v42-5-25,25>>^ E, no mesmo instante, este se levantou diante deles, apanhou aquilo em que se deitara e foi para casa, glorificando a Deus.

[[v42-5-26]]

^<<v42-5-26,26>>^ Todos foram então tomados de êxtase e começaram a glorificar a Deus, e ficaram cheios de temor, dizendo: “Vimos hoje coisas estranhas!”

[[v42-5-27]]

^<<v42-5-27,27>>^ Então, depois destas coisas, ele saiu e observou um cobrador de impostos, de nome Levi, sentado na coletoria, e disse-lhe: “Sê meu seguidor.”

[[v42-5-28]]

^<<v42-5-28,28>>^ E este, deixando tudo, levantou-se e seguiu-o.

[[v42-5-29]]

^<<v42-5-29,29>>^ Levi ofereceu-lhe também uma grande festa de recepção na sua casa; e havia ali uma grande multidão de cobradores de impostos e de outros, recostados com eles, na refeição.

[[v42-5-30]]

^<<v42-5-30,30>>^ Em vista disso, os fariseus e seus escribas começaram a murmurar aos discípulos dele, dizendo: “Por que é que comeis e bebeis com os cobradores de impostos e os pecadores?”

[[v42-5-31]]

^<<v42-5-31,31>>^ Em resposta, Jesus disse-lhes: “Os que têm saúde não precisam de médico, mas sim os que estão adoentados.

[[v42-5-32]]

^<<v42-5-32,32>>^ Eu não vim chamar os que são justos, mas sim pecadores ao arrependimento.”

[[v42-5-33]]

^<<v42-5-33,33>>^ Disseram-lhe: “Os discípulos de João jejuam freqüentemente e oferecem súplicas, e o mesmo fazem os dos fariseus, mas os teus comem e bebem.”

[[v42-5-34]]

^<<v42-5-34,34>>^ Jesus disse-lhes: “Será que podeis fazer os amigos do noivo^&#42;1^ jejuar enquanto o noivo está com eles?

[NOTE]
====
. Lit.: “os filhos da câmara nupcial”.
====

[[v42-5-35]]

^<<v42-5-35,35>>^ Contudo, virão dias em que o noivo deveras lhes será tirado; então, naqueles dias, jejuarão.”

[[v42-5-36]]

^<<v42-5-36,36>>^ Outrossim, prosseguiu a dar-lhes uma ilustração: “Ninguém corta um remendo duma nova roupa exterior e o costura numa velha roupa exterior; mas, se o fizer, então, tanto o remendo novo se arrancará como o remendo da roupa nova não combinará com a velha.

[[v42-5-37]]

^<<v42-5-37,37>>^ Além disso, ninguém põe vinho novo em odres velhos; mas, se o fizer, então o vinho novo rebentará os odres e se derramará, e os odres ficarão arruinados.

[[v42-5-38]]

^<<v42-5-38,38>>^ Mas, vinho novo tem de ser posto em odres novos.

[[v42-5-39]]

^<<v42-5-39,39>>^ Ninguém, tendo bebido vinho velho, quer o novo; pois ele diz: ‘O velho é saboroso.’”^&#42;1^

[NOTE]
====
. “Saboroso”, אBSyp; ACVg: “mais saboroso; melhor”.
====

'''

xref:042-lucas/042-lucas-004.adoc#v42-4-0[&#60; Capítulo Anterior] | <<v42-5-0,Topo>> | xref:042-lucas/042-lucas-006.adoc#v42-6-0[Próximo Capítulo &#62;]