include::./index.adoc[]

[[v42-22-0]]
=== Lucas, 22
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v42-22-1]]

^<<v42-22-1,1>>^ Aproximava-se então a festividade dos pães não fermentados, a chamada Páscoa.

[[v42-22-2]]

^<<v42-22-2,2>>^ Também, os principais sacerdotes e os escribas estavam buscando um meio eficiente de se livrar dele, pois estavam em temor do povo.

[[v42-22-3]]

^<<v42-22-3,3>>^ Mas, Satanás entrou em Judas, o chamado Iscariotes, que era contado entre os doze;

[[v42-22-4]]

^<<v42-22-4,4>>^ e ele foi e falou com os principais sacerdotes e os capitães [do templo] sobre o modo eficiente de traí-lo a eles.

[[v42-22-5]]

^<<v42-22-5,5>>^ Bem, eles se alegraram e concordaram em dar-lhe dinheiro de prata.

[[v42-22-6]]

^<<v42-22-6,6>>^ Ele consentiu assim e começou a buscar uma boa oportunidade para traí-lo a eles sem [que houvesse] uma multidão em volta.

[[v42-22-7]]

^<<v42-22-7,7>>^ Chegou então o dia dos pães não fermentados, em que se tinha de sacrificar a [vítima] pascoal;

[[v42-22-8]]

^<<v42-22-8,8>>^ e ele mandou Pedro e João, dizendo: “Ide e aprontai a páscoa, para que comamos.”

[[v42-22-9]]

^<<v42-22-9,9>>^ Disseram-lhe: “Onde queres que [a] aprontemos?”

[[v42-22-10]]

^<<v42-22-10,10>>^ Ele lhes disse: “Eis que, ao entrardes na cidade, virá ao encontro de vós um homem levando um vaso de barro com água. Segui-o para dentro da casa em que ele entrar.

[[v42-22-11]]

^<<v42-22-11,11>>^ E tendes de dizer ao proprietário da casa: ‘O Instrutor te diz: “Onde está a sala dos hóspedes, em que eu possa comer a páscoa com meus discípulos?”’

[[v42-22-12]]

^<<v42-22-12,12>>^ E esse [homem] vos mostrará uma grande sala de sobrado, mobiliada. Aprontai-a ali.”

[[v42-22-13]]

^<<v42-22-13,13>>^ Eles foram então e acharam-no assim como lhes dissera, e aprontaram a páscoa.

[[v42-22-14]]

^<<v42-22-14,14>>^ Por fim, quando chegou a hora, recostou-se à mesa, e os apóstolos com ele.

[[v42-22-15]]

^<<v42-22-15,15>>^ E ele lhes disse: “Desejei muito comer esta páscoa convosco antes de eu sofrer;

[[v42-22-16]]

^<<v42-22-16,16>>^ pois, eu vos digo: Não a comerei de novo até que se cumpra no reino de Deus.”

[[v42-22-17]]

^<<v42-22-17,17>>^ E, aceitando um copo, deu graças e disse: “Tomai isto e passai-o de um para outro entre vós;

[[v42-22-18]]

^<<v42-22-18,18>>^ pois, eu vos digo: Doravante não beberei mais do produto da videira até que chegue o reino de Deus.”

[[v42-22-19]]

^<<v42-22-19,19>>^ Tomou também um pão, deu graças, partiu-o e deu-lho, dizendo: “Isto significa^&#42;1^ meu corpo que há de ser dado em vosso benefício. Persisti em fazer isso em memória de mim.”

[NOTE]
====
. Ou “é”, no sentido de significar, importar em, representar. Veja Mt 26:26 n.
====

[[v42-22-20]]

^<<v42-22-20,20>>^ Do mesmo modo também o copo, depois de terem [tomado] a refeição noturna, dizendo: “Este copo significa o novo pacto em virtude do meu sangue, que há de ser derramado em vosso benefício.^&#42;1^

[NOTE]
====
. “Que há de ser dado . . . derramado em vosso benefício”, P75אABWVgSyh,pArm; DIt omitem essas palavras dos vv. 19, 20 .
====

[[v42-22-21]]

^<<v42-22-21,21>>^ “Mas, eis que a mão do que me trai está comigo à mesa.

[[v42-22-22]]

^<<v42-22-22,22>>^ Porque o Filho do homem vai embora, segundo o que foi especificado; de qualquer modo, ai do homem por quem ele é traído!”

[[v42-22-23]]

^<<v42-22-23,23>>^ Principiaram assim a discutir entre si a questão de qual deles seria realmente aquele que estava prestes a fazer isso.

[[v42-22-24]]

^<<v42-22-24,24>>^ No entanto, levantou-se também uma disputa acalorada entre eles sobre qual deles parecia ser o maior.

[[v42-22-25]]

^<<v42-22-25,25>>^ Mas ele lhes disse: “Os reis das nações dominam sobre elas, e os que têm autoridade sobre elas são chamados de Benfeitores.

[[v42-22-26]]

^<<v42-22-26,26>>^ Vós, porém, não deveis ser assim. Mas, que o maior entre vós se torne como o mais jovem, e o que age como principal, como aquele que ministra.^&#42;1^

[NOTE]
====
. Ou “serve”.
====

[[v42-22-27]]

^<<v42-22-27,27>>^ Pois, quem é maior, aquele que se recosta à mesa ou aquele que ministra? Não é aquele que se recosta à mesa? Mas eu estou no vosso meio como quem ministra.

[[v42-22-28]]

^<<v42-22-28,28>>^ “No entanto, vós sois os que ficastes comigo nas minhas provações;

[[v42-22-29]]

^<<v42-22-29,29>>^ e eu faço convosco um pacto, assim como meu Pai fez comigo um pacto, para um reino,

[[v42-22-30]]

^<<v42-22-30,30>>^ a fim de que comais e bebais à minha mesa, no meu reino, e vos senteis em tronos para julgar as doze tribos de Israel.

[[v42-22-31]]

^<<v42-22-31,31>>^ “Simão, Simão, eis que Satanás reclamou que fôsseis peneirados como trigo.

[[v42-22-32]]

^<<v42-22-32,32>>^ Mas tenho feito súplica por ti, para que a tua fé não fraquejasse; e tu, uma vez que tiveres voltado, fortalece os teus irmãos.”

[[v42-22-33]]

^<<v42-22-33,33>>^ Então lhe disse: “Senhor,^&#42;1^ estou pronto a ir contigo tanto para a prisão como para a morte.”

[NOTE]
====
. Ou “Amo”.
====

[[v42-22-34]]

^<<v42-22-34,34>>^ Mas ele disse: “Eu te digo, Pedro: O galo não cantará hoje até que tenhas negado três vezes que me conheces.”

[[v42-22-35]]

^<<v42-22-35,35>>^ Ele lhes disse também: “Quando vos enviei sem bolsa, e sem alforje, e sem sandálias, carecestes porventura de alguma coisa?” Disseram: “Não!”^&#42;1^

[NOTE]
====
. Lit.: “De nada!”
====

[[v42-22-36]]

^<<v42-22-36,36>>^ Então lhes disse: “Mas agora, quem tiver bolsa, apanhe-a, e assim também um alforje; e quem não tiver espada, venda a sua roupa exterior e compre uma.

[[v42-22-37]]

^<<v42-22-37,37>>^ Pois eu vos digo que se tem de efetuar em mim o que foi escrito, a saber: ‘E ele foi contado com os que são contra a lei.’ Porque aquilo que se refere a mim está sendo efetuado.”

[[v42-22-38]]

^<<v42-22-38,38>>^ Disseram então: “Senhor,^&#42;1^ eis aqui duas espadas.” Ele lhes disse: “Basta.”

[NOTE]
====
. Ou “Amo”.
====

[[v42-22-39]]

^<<v42-22-39,39>>^ Saindo, ele foi, como de costume, para o Monte das Oliveiras; e os discípulos também o seguiram.

[[v42-22-40]]

^<<v42-22-40,40>>^ Chegando ao lugar, disse-lhes: “Fazei orações, para que não entreis em tentação.”

[[v42-22-41]]

^<<v42-22-41,41>>^ E ele mesmo se afastou deles, cerca de um tiro de pedra, e dobrou os joelhos e começou a orar,

[[v42-22-42]]

^<<v42-22-42,42>>^ dizendo: “Pai, se tu quiseres, remove de mim este copo. Não obstante, ocorra, não a minha vontade, mas a tua.”

[[v42-22-43]]

^<<v42-22-43,43>>^ Apareceu-lhe então um anjo do céu e o fortaleceu.

[[v42-22-44]]

^<<v42-22-44,44>>^ Mas, ficando em agonia, continuava a orar mais seriamente; e seu suor tornou-se como gotas de sangue caindo ao chão.^&#42;1^

[NOTE]
====
. Os vv. : 43, 44, constam em א°DVgSyc,h,hi,pArm; P75אcABWSys omitem isso.
====

[[v42-22-45]]

^<<v42-22-45,45>>^ E ele se levantou da oração, dirigiu-se aos discípulos e os achou dormitando de pesar;

[[v42-22-46]]

^<<v42-22-46,46>>^ e disse-lhes: “Por que estais dormindo? Levantai-vos e fazei orações, para que não entreis em tentação.”

[[v42-22-47]]

^<<v42-22-47,47>>^ Enquanto ainda falava, eis uma multidão, e o [homem] chamado Judas, um dos doze, ia na frente deles; e ele se aproximou de Jesus para beijá-lo.

[[v42-22-48]]

^<<v42-22-48,48>>^ Mas Jesus disse-lhe: “Judas, trais o Filho do homem com um beijo?”

[[v42-22-49]]

^<<v42-22-49,49>>^ Quando os em volta dele viram o que estava para acontecer, disseram: “Senhor, devemos golpeá-los com a espada?”

[[v42-22-50]]

^<<v42-22-50,50>>^ E um certo deles até mesmo golpeou o escravo do sumo sacerdote e lhe tirou a orelha direita.

[[v42-22-51]]

^<<v42-22-51,51>>^ Mas Jesus disse, em resposta: “Deixai-o ficar nisso.” E tocou na orelha e o curou.

[[v42-22-52]]

^<<v42-22-52,52>>^ Jesus disse então aos principais sacerdotes e capitães do templo, e aos anciãos que vieram ali em busca dele: “Viestes com espadas e com cacetes, como contra um salteador?

[[v42-22-53]]

^<<v42-22-53,53>>^ Enquanto eu estava convosco no templo, dia após dia, não estendestes as vossas mãos contra mim. Mas esta é a vossa hora e a autoridade da escuridão.”

[[v42-22-54]]

^<<v42-22-54,54>>^ Prenderam-no então, e o levaram e trouxeram à casa do sumo sacerdote; mas Pedro seguia à distância.

[[v42-22-55]]

^<<v42-22-55,55>>^ Quando acenderam um fogo no meio do pátio e se assentaram juntos, Pedro estava sentado no meio deles.

[[v42-22-56]]

^<<v42-22-56,56>>^ Mas, certa serva o viu sentado junto ao fogo aceso e o examinou, e disse: “Este homem também estava com ele.”

[[v42-22-57]]

^<<v42-22-57,57>>^ Mas ele o^&#42;1^ negou, dizendo: “Não o conheço, mulher.”

[NOTE]
====
. “O”, AD°VgSyh.
====

[[v42-22-58]]

^<<v42-22-58,58>>^ E, depois de pouco tempo, outra pessoa, vendo-o, disse: “Tu também és um deles.” Mas Pedro disse: “Homem, não sou.”

[[v42-22-59]]

^<<v42-22-59,59>>^ E, depois de passar aproximadamente uma hora, outro [homem] começou a insistir fortemente: “Este [homem] certamente também estava com ele; pois, de fato, é galileu!”

[[v42-22-60]]

^<<v42-22-60,60>>^ Mas Pedro disse: “Homem, não sei o que dizes.” E, instantaneamente, enquanto ainda falava, cantou um galo.

[[v42-22-61]]

^<<v42-22-61,61>>^ E o Senhor voltou-se e olhou para Pedro, e Pedro lembrou-se da pronunciação do Senhor, quando lhe disse: “Hoje, antes de o galo cantar, repudiar-me-ás três vezes.”

[[v42-22-62]]

^<<v42-22-62,62>>^ E ele saiu e chorou amargamente.

[[v42-22-63]]

^<<v42-22-63,63>>^ Os homens que o^&#42;1^ tinham em detenção começaram então a divertir-se às custas dele, batendo nele;

[NOTE]
====
. “O”, אBDItVg; ASyp: “[a] Jesus”.
====

[[v42-22-64]]

^<<v42-22-64,64>>^ e, depois de o cobrirem, perguntavam-lhe e diziam: “Profetiza. Quem foi que te golpeou?”

[[v42-22-65]]

^<<v42-22-65,65>>^ E prosseguiam a dizer muitas outras coisas em blasfêmia contra ele.

[[v42-22-66]]

^<<v42-22-66,66>>^ Por fim, quando se tornou dia, ajuntou-se a assembléia dos anciãos do povo, tanto os principais sacerdotes como os escribas, e o arrastaram para a sua sala do Sinédrio,^&#42;1^ dizendo:

[NOTE]
====
. Ou “seu Sinédrio”.
====

[[v42-22-67]]

^<<v42-22-67,67>>^ “Se tu és o Cristo, dize-nos.” Mas ele lhes disse: “Mesmo se eu vos dissesse, não o acreditaríeis absolutamente.

[[v42-22-68]]

^<<v42-22-68,68>>^ Além disso, se eu vos interrogasse, não me responderíeis absolutamente.

[[v42-22-69]]

^<<v42-22-69,69>>^ No entanto, doravante o Filho do homem estará sentado à destra poderosa^&#42;1^ de Deus.”

[NOTE]
====
. Ou “à destra do poder”.
====

[[v42-22-70]]

^<<v42-22-70,70>>^ Em vista disso, todos disseram: “És tu, portanto, o Filho de Deus?” Disse-lhes ele: “Vós mesmos dizeis que eu sou.”

[[v42-22-71]]

^<<v42-22-71,71>>^ Eles disseram: “Por que precisamos de mais testemunho? Pois nós mesmos ouvimos [isso] de sua própria boca.”

'''

xref:042-lucas/042-lucas-021.adoc#v42-21-0[&#60; Capítulo Anterior] | <<v42-22-0,Topo>> | xref:042-lucas/042-lucas-023.adoc#v42-23-0[Próximo Capítulo &#62;]