include::./index.adoc[]

[[v42-20-0]]
=== Lucas, 20
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v42-20-1]]

^<<v42-20-1,1>>^ Num dos dias em que estava ensinando o povo no templo e declarando as boas novas, aproximaram-se os principais sacerdotes e os escribas, com os anciãos,

[[v42-20-2]]

^<<v42-20-2,2>>^ e falaram sem rebuços, dizendo-lhe: “Dize-nos com que autoridade fazes estas coisas, e quem é que te deu esta autoridade.”

[[v42-20-3]]

^<<v42-20-3,3>>^ Ele lhes disse, em resposta: “Eu também vos farei uma pergunta, e vós, dizei-me:

[[v42-20-4]]

^<<v42-20-4,4>>^ Foi o batismo^&#42;1^ de João do céu ou dos homens?”

[NOTE]
====
. Ou “imersão; submersão (mergulho)”. Gr.: bá·pti·sma.
====

[[v42-20-5]]

^<<v42-20-5,5>>^ Tiraram então conclusões entre si, dizendo: “Se dissermos: ‘Do céu’, ele dirá: ‘Por que é que não acreditastes nele?’

[[v42-20-6]]

^<<v42-20-6,6>>^ Mas, se dissermos: ‘Dos homens’, o povo todo nos apedrejará, pois estão persuadidos de que João era profeta.”

[[v42-20-7]]

^<<v42-20-7,7>>^ De modo que responderam que não sabiam a sua fonte.

[[v42-20-8]]

^<<v42-20-8,8>>^ E Jesus disse-lhes: “Tampouco eu vos digo com que autoridade faço estas coisas.”

[[v42-20-9]]

^<<v42-20-9,9>>^ Então, principiou a contar ao povo a seguinte ilustração: “Um homem plantou um vinhedo e o arrendou a lavradores, e viajou para fora, por bastante tempo.

[[v42-20-10]]

^<<v42-20-10,10>>^ Mas, na época devida, enviou um escravo aos lavradores, para que lhe dessem dos frutos do vinhedo. Os lavradores, porém, mandaram-no embora de mãos vazias, depois de o espancarem.

[[v42-20-11]]

^<<v42-20-11,11>>^ Mas ele repetiu [isso] e lhes enviou um escravo diferente. A este também espancaram e desonraram, e mandaram embora de mãos vazias.

[[v42-20-12]]

^<<v42-20-12,12>>^ Contudo, mais uma vez mandou um terceiro; a este também feriram e lançaram fora.

[[v42-20-13]]

^<<v42-20-13,13>>^ Em vista disso, o dono do vinhedo disse: ‘Que farei? Enviarei o meu filho, o amado. É provável que respeitem a este.’

[[v42-20-14]]

^<<v42-20-14,14>>^ Quando os lavradores o avistaram, raciocinaram entre si, dizendo: ‘Este é o herdeiro; matemo-lo, para que a herança se torne nossa.’

[[v42-20-15]]

^<<v42-20-15,15>>^ Com isso lançaram-no fora do vinhedo e o mataram. O que, portanto, lhes fará o dono do vinhedo?

[[v42-20-16]]

^<<v42-20-16,16>>^ Virá e destruirá esses lavradores e dará o vinhedo a outros.”
Ouvindo [isso], disseram: “Que isso nunca aconteça!”

[[v42-20-17]]

^<<v42-20-17,17>>^ Mas ele olhou para eles e disse: “Que significa então aquilo que está escrito: ‘A pedra que os construtores rejeitaram, esta se tem tornado a principal pedra angular’?

[[v42-20-18]]

^<<v42-20-18,18>>^ Todo aquele que cair sobre esta pedra, será despedaçado. Quanto àquele sobre quem ela cair, será pulverizado por ela.”

[[v42-20-19]]

^<<v42-20-19,19>>^ Os escribas e os principais sacerdotes procuravam então, naquela mesma hora, deitar mãos nele, mas temiam o povo; porque percebiam que contara esta ilustração pensando neles.

[[v42-20-20]]

^<<v42-20-20,20>>^ E, depois de o observarem de perto, enviaram homens secretamente contratados para pretenderem ser justos, a fim de que o pudessem apanhar na palavra, para o entregarem ao governo e à autoridade do governador.

[[v42-20-21]]

^<<v42-20-21,21>>^ E interrogaram-no, dizendo: “Instrutor, sabemos que falas e ensinas corretamente e não mostras parcialidade, mas que ensinas o caminho de Deus em harmonia com a verdade:

[[v42-20-22]]

^<<v42-20-22,22>>^ É lícito ou não que paguemos imposto a César?”^&#42;1^

[NOTE]
====
. Ou “ao imperador”. Gr.: Kaí·sa·ri; lat.: Caé·sa·ri.
====

[[v42-20-23]]

^<<v42-20-23,23>>^ Mas ele percebia a sua astúcia, e disse-lhes:

[[v42-20-24]]

^<<v42-20-24,24>>^ “Mostrai-me um denário.^&#42;1^ A imagem e inscrição de quem está nele?” Disseram: “De César.”

[NOTE]
====
. Este era uma moeda romana de prata que pesava 3,85 g.
====

[[v42-20-25]]

^<<v42-20-25,25>>^ Disse-lhes ele: “De todos os modos, pois, pagai de volta a César as coisas de César, mas a Deus as coisas de Deus.”

[[v42-20-26]]

^<<v42-20-26,26>>^ Bem, não foram capazes de apanhá-lo nesta declaração perante o povo, mas, pasmados com a resposta dele, não disseram nada.

[[v42-20-27]]

^<<v42-20-27,27>>^ No entanto, chegaram-se alguns dos saduceus, aqueles que dizem não haver ressurreição, e interrogaram-no,

[[v42-20-28]]

^<<v42-20-28,28>>^ dizendo: “Instrutor, Moisés nos escreveu: ‘Se morrer o irmão dum homem que tiver esposa, mas não tiver filhos, seu irmão deve tomar a esposa e suscitar dela descendência para seu irmão.’

[[v42-20-29]]

^<<v42-20-29,29>>^ Concordemente, havia sete irmãos; e o primeiro tomou uma esposa e morreu sem filhos.

[[v42-20-30]]

^<<v42-20-30,30>>^ De modo que o segundo

[[v42-20-31]]

^<<v42-20-31,31>>^ e o terceiro a tomaram. Do mesmo modo até os sete: não deixaram filhos, porém morreram.

[[v42-20-32]]

^<<v42-20-32,32>>^ Por último, morreu também a mulher.

[[v42-20-33]]

^<<v42-20-33,33>>^ Conseqüentemente, na ressurreição,^&#42;1^ de qual deles torna-se ela esposa? Pois os sete a tiveram como esposa.”

[NOTE]
====
. “Ressurreição.” Gr.: a·na·stá·sei, “levantar-se; erguer-se” (de a·ná, “para cima”, e stá·sis, “estar de pé”); lat.: re·sur·rec·ti·ó·ne.
====

[[v42-20-34]]

^<<v42-20-34,34>>^ Jesus disse-lhes: “Os filhos deste sistema de coisas^&#42;1^ casam-se e são dados em casamento,

[NOTE]
====
. Ou “ordem de coisas”. Gr.: ai·ó·nos; lat.: saé·cu·li; J17,18,22(hebr.): ha·‛oh·lám, “a ordem de coisas”.
====

[[v42-20-35]]

^<<v42-20-35,35>>^ mas os que têm sido contados dignos de ganhar aquele sistema de coisas e a ressurreição dentre os mortos, nem se casam nem são dados em casamento.

[[v42-20-36]]

^<<v42-20-36,36>>^ De fato, tampouco podem mais morrer, porque são como os anjos, e são filhos de Deus por serem filhos da ressurreição.

[[v42-20-37]]

^<<v42-20-37,37>>^ Mas, que os mortos são levantados, até mesmo Moisés expôs, no relato sobre o espinheiro, quando ele chama Jeová^&#42;1^ ‘o Deus de Abraão,^&#42;2^ e o Deus de Isaque, e o Deus de Jacó’.

[NOTE]
====
. Veja Ap. 1D.
. Ou “quando ele diz: ‘Jeová, o Deus de Abraão’”.
====

[[v42-20-38]]

^<<v42-20-38,38>>^ Ele é Deus, não de mortos, mas de viventes, pois, para ele, todos estes vivem.”^&#42;1^

[NOTE]
====
. Ou “vivem do seu ponto de vista”.
====

[[v42-20-39]]

^<<v42-20-39,39>>^ Em resposta, alguns dos escribas disseram: “Instrutor, falaste bem.”

[[v42-20-40]]

^<<v42-20-40,40>>^ Porque não tinham mais a coragem de lhe fazerem uma só pergunta.

[[v42-20-41]]

^<<v42-20-41,41>>^ Ele, por sua vez, lhes disse: “Como é que dizem que o Cristo é filho de Davi?

[[v42-20-42]]

^<<v42-20-42,42>>^ Porque o próprio Davi diz no livro dos Salmos: ‘Jeová^&#42;1^ disse ao meu Senhor: “Senta-te à minha direita,

[NOTE]
====
. Veja Ap. 1D.
====

[[v42-20-43]]

^<<v42-20-43,43>>^ até que eu ponha os teus inimigos como escabelo para os teus pés.”’

[[v42-20-44]]

^<<v42-20-44,44>>^ Davi, portanto, chama-o de ‘Senhor’; então, como é que ele é seu filho?”

[[v42-20-45]]

^<<v42-20-45,45>>^ Então, enquanto todo o povo estava escutando, ele disse aos discípulos:

[[v42-20-46]]

^<<v42-20-46,46>>^ “Acautelai-vos dos escribas, que desejam andar de vestes compridas e que gostam dos cumprimentos nas feiras,^&#42;1^ e dos primeiros assentos nas sinagogas e dos lugares mais destacados nas refeições noturnas,

[NOTE]
====
. Veja 11:43 n.
====

[[v42-20-47]]

^<<v42-20-47,47>>^ e que devoram as casas das viúvas, e, como pretexto, fazem longas orações. Estes receberão um julgamento mais pesado.”

'''

xref:042-lucas/042-lucas-019.adoc#v42-19-0[&#60; Capítulo Anterior] | <<v42-20-0,Topo>> | xref:042-lucas/042-lucas-021.adoc#v42-21-0[Próximo Capítulo &#62;]