include::./index.adoc[]

[[v42-15-0]]
=== Lucas, 15
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v42-15-1]]

^<<v42-15-1,1>>^ Todos os cobradores de impostos e pecadores chegavam-se então perto dele para o ouvirem.

[[v42-15-2]]

^<<v42-15-2,2>>^ Conseqüentemente, tanto os fariseus como os escribas murmuravam, dizendo: “Este homem acolhe pecadores e come com eles.”

[[v42-15-3]]

^<<v42-15-3,3>>^ Então lhes contou a seguinte ilustração, dizendo:

[[v42-15-4]]

^<<v42-15-4,4>>^ “Que homem dentre vós, com cem ovelhas, perdendo uma delas, não deixa as noventa e nove atrás no ermo e vai em busca da perdida, até a achar?

[[v42-15-5]]

^<<v42-15-5,5>>^ E quando a tiver achado, ele a põe sobre os seus ombros e se alegra.

[[v42-15-6]]

^<<v42-15-6,6>>^ E, ao chegar à casa, convoca seus amigos e seus vizinhos, dizendo-lhes: ‘Alegrai-vos comigo, porque achei a minha ovelha que estava perdida.’

[[v42-15-7]]

^<<v42-15-7,7>>^ Eu vos digo que assim haverá mais alegria no céu por causa de um pecador que se arrepende, do que por causa de noventa e nove justos que não precisam de arrependimento.

[[v42-15-8]]

^<<v42-15-8,8>>^ “Ou que mulher, com dez moedas de dracma,^&#42;1^ se perder uma moeda de dracma, não acende uma lâmpada e varre a sua casa, e procura cuidadosamente até achá-la?

[NOTE]
====
. A dracma era uma moeda gr. de prata que pesava 3,4 g.
====

[[v42-15-9]]

^<<v42-15-9,9>>^ E quando a tiver achado, convoca as mulheres que são suas amigas e vizinhas, dizendo: ‘Alegrai-vos comigo, porque achei a moeda de dracma que perdi.’

[[v42-15-10]]

^<<v42-15-10,10>>^ Assim, eu vos digo, surge alegria entre os anjos de Deus por causa de um pecador que se arrepende.”

[[v42-15-11]]

^<<v42-15-11,11>>^ Ele disse então: “Certo homem tinha dois filhos.

[[v42-15-12]]

^<<v42-15-12,12>>^ E o mais jovem deles disse a seu pai: ‘Pai, dá-me a parte dos bens que me cabe.’ Dividiu então os seus meios de vida entre eles.

[[v42-15-13]]

^<<v42-15-13,13>>^ Mais tarde, não muitos dias depois, o filho mais jovem ajuntou todas as coisas e viajou para fora, a um país distante, e ali esbanjou os seus bens por levar uma vida devassa.

[[v42-15-14]]

^<<v42-15-14,14>>^ Quando já tinha gasto tudo, ocorreu uma fome severa em todo aquele país, e ele principiou a passar necessidade.

[[v42-15-15]]

^<<v42-15-15,15>>^ Ele até mesmo foi e se agregou a um dos cidadãos daquele país, e este o enviou aos seus campos para pastar porcos.

[[v42-15-16]]

^<<v42-15-16,16>>^ E costumava desejar saciar-se das alfarrobas que os porcos comiam, e ninguém lhe dava [nada].

[[v42-15-17]]

^<<v42-15-17,17>>^ “Quando caiu em si, disse: ‘Quantos empregados de meu pai têm abundância de pão, enquanto eu pereço aqui de fome!

[[v42-15-18]]

^<<v42-15-18,18>>^ Levantar-me-ei e viajarei para meu pai e lhe direi: ‘Pai, pequei contra o céu e contra ti.^&#42;1^

[NOTE]
====
. Ou “à tua vista”; como em 1Sa 20:1 na LXX.
====

[[v42-15-19]]

^<<v42-15-19,19>>^ Não sou mais digno de ser chamado teu filho. Faze de mim um dos teus empregados.”’

[[v42-15-20]]

^<<v42-15-20,20>>^ Levantou-se assim e foi ter com seu pai. Enquanto ainda estava longe, seu pai o avistou e teve pena, e correu e lançou-se-lhe ao pescoço e o beijou ternamente.

[[v42-15-21]]

^<<v42-15-21,21>>^ O filho disse-lhe então: ‘Pai, pequei contra o céu e contra ti.^&#42;1^ Não sou mais digno de ser chamado teu filho. Faze de mim um dos teus empregados.’^&#42;2^

[NOTE]
====
. Veja v. 18 n.
. “Faze de mim um dos teus empregados”, אBDSyh; P75AWVgSyp,s omitem isso.
====

[[v42-15-22]]

^<<v42-15-22,22>>^ Mas o pai disse aos seus escravos: ‘Ligeiro! Trazei uma veste comprida, a melhor, vesti-o com ela, e ponde-lhe um anel na mão e sandálias nos pés.

[[v42-15-23]]

^<<v42-15-23,23>>^ E trazei o novilho cevado e abatei-o,^&#42;1^ e comamos e alegremo-nos,

[NOTE]
====
. Ou “sacrificai-o”.
====

[[v42-15-24]]

^<<v42-15-24,24>>^ porque este meu filho estava morto, e voltou a viver; estava perdido, mas foi achado.’ E principiaram a regalar-se.

[[v42-15-25]]

^<<v42-15-25,25>>^ “Ora, o filho mais velho dele estava no campo; e quando chegou e se aproximou da casa, ouviu um concerto de música e dança.

[[v42-15-26]]

^<<v42-15-26,26>>^ De modo que chamou a si um dos servos e indagou o significado destas coisas.

[[v42-15-27]]

^<<v42-15-27,27>>^ Este lhe disse: ‘Chegou teu irmão, e teu pai abateu o novilho cevado, porque o recebeu de volta em boa saúde.’

[[v42-15-28]]

^<<v42-15-28,28>>^ Mas ele ficou furioso e não quis entrar. Saiu então seu pai e começou a suplicar-lhe.

[[v42-15-29]]

^<<v42-15-29,29>>^ Em resposta, ele disse ao seu pai: ‘Eis que trabalhei tantos anos como escravo para ti, e nunca, nem uma única vez, transgredi o teu mandamento, contudo, nunca, nem uma única vez, me deste um cabritinho para alegrar-me com os meus amigos.

[[v42-15-30]]

^<<v42-15-30,30>>^ Mas, assim que chegou este teu filho, que consumiu com as meretrizes o teu meio de vida, abates para ele o novilho cevado.’

[[v42-15-31]]

^<<v42-15-31,31>>^ Disse-lhe então: ‘Filho, tu sempre estiveste comigo e todas as minhas coisas são tuas;

[[v42-15-32]]

^<<v42-15-32,32>>^ mas nós simplesmente tivemos de nos regalar e alegrar, porque este teu irmão estava morto, e voltou a viver, e estava perdido, mas foi achado.’”

'''

xref:042-lucas/042-lucas-014.adoc#v42-14-0[&#60; Capítulo Anterior] | <<v42-15-0,Topo>> | xref:042-lucas/042-lucas-016.adoc#v42-16-0[Próximo Capítulo &#62;]