include::./index.adoc[]

[[v42-4-0]]
=== Lucas, 4
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v42-4-1]]

^<<v42-4-1,1>>^ Ora, Jesus, cheio de espírito santo, afastou-se do Jordão e foi conduzido pelo espírito,^&#42;1^ lá no ermo,

[NOTE]
====
. Ou “força ativa”. Gr.: pneú·ma·ti; lat.: Spí·ri·tu; J17,18,22(hebr.): ha·rú·ahh, “pela força ativa”. Veja Gên 1:2 n.: “ativa”.
====

[[v42-4-2]]

^<<v42-4-2,2>>^ por quarenta dias, sendo tentado pelo Diabo. Outrossim, ele não comeu nada naqueles dias, e por isso, ao terminarem, sentiu fome.

[[v42-4-3]]

^<<v42-4-3,3>>^ O Diabo disse-lhe assim: “Se tu és filho de Deus, dize a esta pedra que se transforme em pão.”

[[v42-4-4]]

^<<v42-4-4,4>>^ Mas Jesus replicou-lhe: “Está escrito: ‘O homem não deve viver só de pão.’”^&#42;1^

[NOTE]
====
. Segundo אB; ADItVgSyh,p acrescentam: “mas de toda palavra de Deus”; J7,8,10,13-15,17 acrescentam: “mas de tudo o que procede da boca de Jeová”.
====

[[v42-4-5]]

^<<v42-4-5,5>>^ Ele o levou assim para cima e lhe mostrou todos os reinos da terra habitada, num instante de tempo;

[[v42-4-6]]

^<<v42-4-6,6>>^ e o Diabo disse-lhe: “Eu te darei toda esta autoridade^&#42;1^ e a glória deles, porque me foi entregue e a dou a quem eu quiser.

[NOTE]
====
. “Esta autoridade.” Gr.: ten e·xou·sí·an taú·ten.
====

[[v42-4-7]]

^<<v42-4-7,7>>^ Se tu, pois, fizeres um ato de adoração diante de mim, tudo será teu.”

[[v42-4-8]]

^<<v42-4-8,8>>^ Em resposta, Jesus disse-lhe: “Está escrito: ‘É a Jeová,^&#42;1^ teu Deus, que tens de adorar e é somente a ele que tens de prestar serviço sagrado.’”^&#42;2^

[NOTE]
====
. Veja Ap. 1D.
. “Tens de prestar serviço sagrado.” Gr.: la·treú·seis; J17,18,22(hebr.): ta·‛avódh. Veja Êx 3:12 n.
====

[[v42-4-9]]

^<<v42-4-9,9>>^ Ele o levou então a Jerusalém e o postou sobre o parapeito do templo e lhe disse: “Se tu és filho de Deus, lança-te daqui para baixo;

[[v42-4-10]]

^<<v42-4-10,10>>^ pois está escrito: ‘Dará aos seus anjos um encargo concernente a ti, para preservar-te’,

[[v42-4-11]]

^<<v42-4-11,11>>^ e: ‘Eles te carregarão nas mãos, para que nunca batas com o pé contra uma pedra.’”

[[v42-4-12]]

^<<v42-4-12,12>>^ Jesus disse-lhe, em resposta: “Dito está: ‘Não deves pôr Jeová,^&#42;1^ teu Deus, à prova.’”

[NOTE]
====
. Veja Ap. 1D.
====

[[v42-4-13]]

^<<v42-4-13,13>>^ Assim, o Diabo, tendo terminado com toda a tentação, retirou-se dele até outra ocasião conveniente.

[[v42-4-14]]

^<<v42-4-14,14>>^ Jesus voltou então no poder do espírito para a Galiléia. E a boa fama dele espalhou-se por toda a região circunvizinha.

[[v42-4-15]]

^<<v42-4-15,15>>^ Começou também a ensinar nas sinagogas deles, sendo tido em honra por todos.

[[v42-4-16]]

^<<v42-4-16,16>>^ E ele chegou a Nazaré, onde tinha sido criado; e, segundo o seu costume no dia de sábado, entrou na sinagoga e levantou-se para ler.

[[v42-4-17]]

^<<v42-4-17,17>>^ Foi-lhe assim entregue o rolo do profeta Isaías, e ele abriu o rolo e achou o lugar onde estava escrito:

[[v42-4-18]]

^<<v42-4-18,18>>^ “O espírito de Jeová^&#42;1^ está sobre mim, porque me ungiu^&#42;2^ para declarar boas novas aos pobres, enviou-me para pregar livramento aos cativos e recuperação da vista aos cegos, para mandar embora os esmagados, com livramento,

[NOTE]
====
. Veja Ap. 1D.
. “Ungiu”, אAB; J7,8,10,13-15: “Jeová me ungiu.”
====

[[v42-4-19]]

^<<v42-4-19,19>>^ para pregar o ano aceitável de Jeová.”^&#42;1^

[NOTE]
====
. Veja Ap. 1D.
====

[[v42-4-20]]

^<<v42-4-20,20>>^ Com isto enrolou o rolo, entregou-o de volta ao assistente e se assentou; e os olhos de todos na sinagoga estavam atentamente fixos nele.

[[v42-4-21]]

^<<v42-4-21,21>>^ Principiou então a dizer-lhes: “Hoje se cumpriu esta escritura que acabais de ouvir.”^&#42;1^

[NOTE]
====
. Lit.: “esta escritura nos vossos ouvidos”.
====

[[v42-4-22]]

^<<v42-4-22,22>>^ E todos começaram a dar-lhe testemunho favorável e a maravilhar-se das palavras cativantes que saíam de sua boca, e diziam: “Não é este um filho de José?”

[[v42-4-23]]

^<<v42-4-23,23>>^ A isto lhes disse: “Sem dúvida aplicareis a mim a seguinte ilustração:^&#42;1^ ‘Médico, cura-te a ti mesmo; as coisas que ouvimos acontecer em Cafarnaum faze também aqui no teu próprio território.’”

[NOTE]
====
. Ou “parábola”.
====

[[v42-4-24]]

^<<v42-4-24,24>>^ Mas ele disse: “Deveras, eu vos digo que nenhum profeta é aceito no seu próprio território.

[[v42-4-25]]

^<<v42-4-25,25>>^ Por exemplo, em verdade vos digo: Havia muitas viúvas em Israel nos dias de Elias, quando o céu ficou fechado por três anos e seis meses, de modo que sobreveio grande fome a toda a terra,

[[v42-4-26]]

^<<v42-4-26,26>>^ contudo, Elias não foi enviado a nenhuma destas [mulheres], mas apenas a Sarefá,^&#42;1^ na terra de Sídon, a uma viúva.

[NOTE]
====
. Lit.: “Sarepta”; nome gr. desta cidade.
====

[[v42-4-27]]

^<<v42-4-27,27>>^ Havia também muitos leprosos em Israel, no tempo de Eliseu, o profeta, contudo, nenhum deles foi purificado, a não ser Naamã, o homem da Síria.”

[[v42-4-28]]

^<<v42-4-28,28>>^ Ora, todos os que ouviam estas coisas na sinagoga ficaram cheios de ira;

[[v42-4-29]]

^<<v42-4-29,29>>^ e levantaram-se e o conduziram às pressas para fora da cidade, e o levaram à beirada do monte^&#42;1^ em que se situava a sua cidade, a fim de o lançarem de cabeça para baixo.

[NOTE]
====
. Ou “morro”.
====

[[v42-4-30]]

^<<v42-4-30,30>>^ Mas ele passou pelo seu meio e seguiu caminho.

[[v42-4-31]]

^<<v42-4-31,31>>^ E desceu a Cafarnaum, uma cidade da Galiléia. E ele os ensinava no sábado;

[[v42-4-32]]

^<<v42-4-32,32>>^ e ficaram assombrados com o seu modo de ensinar, porque a sua palavra era com autoridade.

[[v42-4-33]]

^<<v42-4-33,33>>^ Ora, havia na sinagoga um homem com um espírito, um demônio impuro,^&#42;1^ e ele gritava com voz alta:

[NOTE]
====
. Ou “com um espírito demoníaco impuro”. Possivelmente: “com uma expressão inspirada dum demônio impuro”. Veja Re 16:14.
====

[[v42-4-34]]

^<<v42-4-34,34>>^ “Ah! que temos nós contigo,^&#42;1^ Jesus, nazareno? Vieste destruir-nos? Sei exatamente quem és, o Santo de Deus.”

[NOTE]
====
. “Que temos nós contigo?” Esta é uma expressão idiomática; é uma pergunta de repulsa, indicando objeção. Veja Ap. 7B.
====

[[v42-4-35]]

^<<v42-4-35,35>>^ Mas Jesus censurou-o, dizendo: “Cala-te e sai dele.” Assim, depois de lançar o homem no meio deles, saiu dele o demônio sem lhe fazer dano.

[[v42-4-36]]

^<<v42-4-36,36>>^ Em vista disso, todos se assombraram e começaram a conversar entre si, dizendo: “Que sorte de palavra é esta, porque ordena aos espíritos impuros com autoridade e poder, e eles saem?”

[[v42-4-37]]

^<<v42-4-37,37>>^ De modo que a notícia a respeito dele se espalhava por todo canto da região circunvizinha.

[[v42-4-38]]

^<<v42-4-38,38>>^ Depois de se levantar e sair da sinagoga, entrou no lar de Simão. Ora, a sogra de Simão estava padecendo de febre alta, e fizeram-lhe uma solicitação a favor dela.

[[v42-4-39]]

^<<v42-4-39,39>>^ Inclinou-se então sobre ela e censurou a febre, e esta a abandonou. Ela se levantou no mesmo instante e começou a ministrar-lhes.

[[v42-4-40]]

^<<v42-4-40,40>>^ Mas, pondo-se o sol, todos os que tinham doentes com várias moléstias vieram trazê-los a ele. Curava-os, pondo suas mãos sobre cada um deles.

[[v42-4-41]]

^<<v42-4-41,41>>^ De muitos saíam também demônios, clamando e dizendo: “Tu és o Filho de Deus.” Censurando-os, porém, não lhes permitia que falassem, porque sabiam que ele era o Cristo.

[[v42-4-42]]

^<<v42-4-42,42>>^ No entanto, ficando dia, saiu e foi para um lugar solitário. As multidões, porém, começaram a ir em busca dele e vieram até o lugar onde ele estava, e tentaram impedir que se afastasse deles.

[[v42-4-43]]

^<<v42-4-43,43>>^ Mas ele lhes disse: “Tenho de declarar as boas novas do reino de Deus também a outras cidades, porque fui enviado para isso.”

[[v42-4-44]]

^<<v42-4-44,44>>^ Concordemente, pregava nas sinagogas da Judéia.

'''

xref:042-lucas/042-lucas-003.adoc#v42-3-0[&#60; Capítulo Anterior] | <<v42-4-0,Topo>> | xref:042-lucas/042-lucas-005.adoc#v42-5-0[Próximo Capítulo &#62;]