include::./index.adoc[]

[[v42-9-0]]
=== Lucas, 9
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v42-9-1]]

^<<v42-9-1,1>>^ Ele convocou então os doze e deu-lhes poder e autoridade sobre todos os demônios, e para curar doenças.

[[v42-9-2]]

^<<v42-9-2,2>>^ E assim os enviou a pregar o reino de Deus e a curar,

[[v42-9-3]]

^<<v42-9-3,3>>^ e disse-lhes: “Não leveis nada para a viagem, nem bastão, nem alforje, nem pão, nem dinheiro de prata; tampouco tenhais duas peças de roupa interior.

[[v42-9-4]]

^<<v42-9-4,4>>^ Mas, onde quer que entrardes num lar, ficai ali e parti dali.

[[v42-9-5]]

^<<v42-9-5,5>>^ E onde quer que não vos receberem, ao sairdes daquela cidade, sacudi o pó dos vossos pés em testemunho contra eles.”

[[v42-9-6]]

^<<v42-9-6,6>>^ Partindo então, passaram pelo território, de aldeia em aldeia, declarando as boas novas e realizando curas em toda a parte.

[[v42-9-7]]

^<<v42-9-7,7>>^ Herodes, o governante distrital,^&#42;1^ ouviu então [falar] de todas as coisas que estavam acontecendo e ficou em grande perplexidade, porque alguns diziam que João fora levantado dentre os mortos,

[NOTE]
====
. Ou “o tetrarca”. Veja 3:1 e n.
====

[[v42-9-8]]

^<<v42-9-8,8>>^ mas outros [diziam] que Elias aparecera, e ainda outros, que certo dos antigos profetas se tinha levantado.

[[v42-9-9]]

^<<v42-9-9,9>>^ Herodes disse: “Eu decapitei a João. Quem é então este de quem ouço [falar] tais coisas?” De modo que buscava vê-lo.

[[v42-9-10]]

^<<v42-9-10,10>>^ E quando os apóstolos voltaram, narraram-lhe as coisas que tinham feito. Ele os levou então consigo e se retirou em isolamento para uma cidade chamada Betsaida.

[[v42-9-11]]

^<<v42-9-11,11>>^ Mas as multidões, sabendo disso, seguiam-no. E ele as recebeu benevolamente, e começou a falar-lhes do reino de Deus e sarou os necessitados de cura.

[[v42-9-12]]

^<<v42-9-12,12>>^ O dia principiou então a declinar. Os doze chegaram-se então e disseram-lhe: “Despede a multidão, para que possam ir às aldeias e à zona rural circunvizinha procurar alojamento e achar provisões, porque aqui fora estamos num lugar solitário.”

[[v42-9-13]]

^<<v42-9-13,13>>^ Mas ele lhes disse: “Dai-lhes vós algo para comer.” Disseram: “Não temos nada mais do que cinco pães e dois peixes, a menos que talvez nós mesmos vamos e compremos comestíveis para todo este povo.”

[[v42-9-14]]

^<<v42-9-14,14>>^ Havia ali, de fato, cerca de cinco mil homens. Mas ele disse aos seus discípulos: “Fazei-os recostar-se como nas refeições, em grupos de cerca de cinqüenta cada um.”

[[v42-9-15]]

^<<v42-9-15,15>>^ E eles fizeram isso e mandaram-nos recostar-se.

[[v42-9-16]]

^<<v42-9-16,16>>^ Tomando então os cinco pães e os dois peixes, olhou para o céu, abençoou-os e partiu-os, e começou a dá-los aos discípulos, para que os pusessem diante da multidão.

[[v42-9-17]]

^<<v42-9-17,17>>^ Assim, todos comeram e ficaram satisfeitos, e recolheu-se o que lhes sobrava, doze cestos de pedaços.

[[v42-9-18]]

^<<v42-9-18,18>>^ Mais tarde, enquanto estava orando sozinho, os discípulos ajuntaram-se a ele^&#42;1^ e ele os interrogou, dizendo: “Quem dizem as multidões que eu sou?”

[NOTE]
====
. Ou “os discípulos estavam com ele”. B°: “os discípulos vieram ter com ele”.
====

[[v42-9-19]]

^<<v42-9-19,19>>^ Em resposta, disseram: “João Batista;^&#42;1^ mas outros, Elias,^&#42;2^ e ainda outros, que um dos antigos profetas se levantou.”

[NOTE]
====
. Ou “o Imersor; Submersor (Mergulhador)”. Gr.: ton Ba·pti·stén.
. Significando “Meu Deus É Jeová”. J17,18,22(hebr.): ’E·li·yá·hu.
====

[[v42-9-20]]

^<<v42-9-20,20>>^ Então lhes disse: “Vós, porém, quem dizeis que eu sou?” Pedro disse, em resposta: “O Cristo de Deus.”

[[v42-9-21]]

^<<v42-9-21,21>>^ Então, numa conversa severa com eles, ordenou-lhes que não dissessem isso a ninguém,

[[v42-9-22]]

^<<v42-9-22,22>>^ mas disse: “O Filho do homem tem de passar por muitos sofrimentos e ser rejeitado pelos anciãos e pelos principais sacerdotes, e pelos escribas, e ser morto, e [tem de] ser levantado no terceiro dia.”

[[v42-9-23]]

^<<v42-9-23,23>>^ Ele prosseguiu então a dizer a todos: “Se alguém quer vir após mim, repudie-se a si mesmo e apanhe a sua estaca de tortura,^&#42;1^ dia após dia, e siga-me continuamente.

[NOTE]
====
. Veja Ap. 5C.
====

[[v42-9-24]]

^<<v42-9-24,24>>^ Pois todo aquele que quiser salvar a sua alma,^&#42;1^ perdê-la-á; mas todo aquele que perder a sua alma por minha causa é o que a salvará.

[NOTE]
====
. Ou “vida”. Gr.: psy·khén; J17,18,22(hebr.): naf·shóh (de né·fesh). Veja Ap. 4A.
====

[[v42-9-25]]

^<<v42-9-25,25>>^ Realmente, de que proveito é para um homem ganhar o mundo inteiro, mas perder a si próprio ou sofrer prejuízo?

[[v42-9-26]]

^<<v42-9-26,26>>^ Porque todo aquele que ficar envergonhado de mim e das minhas palavras, deste o Filho do homem se envergonhará quando chegar na sua glória e na de seu Pai e dos santos anjos.

[[v42-9-27]]

^<<v42-9-27,27>>^ Mas eu vos digo em verdade: Há alguns dos em pé aqui, que não provarão absolutamente a morte, até que primeiro vejam o reino de Deus.”

[[v42-9-28]]

^<<v42-9-28,28>>^ Em realidade, cerca de oito dias depois destas palavras, tomou consigo a Pedro, e a João, e a Tiago, e subiu ao monte para orar.

[[v42-9-29]]

^<<v42-9-29,29>>^ E, enquanto orava, a aparência do seu rosto tornou-se diferente e a sua vestimenta tornou-se resplendentemente branca.^&#42;1^

[NOTE]
====
. Ou “brilhante”.
====

[[v42-9-30]]

^<<v42-9-30,30>>^ Também, eis que dois homens conversavam com ele, sendo eles Moisés e Elias.

[[v42-9-31]]

^<<v42-9-31,31>>^ Estes apareceram com glória e começaram a falar sobre a sua partida,^&#42;1^ que ele estava destinado a cumprir em Jerusalém.

[NOTE]
====
. “Partida.” Gr.: é·xo·don, como em 2Pe 1:15.
====

[[v42-9-32]]

^<<v42-9-32,32>>^ Ora, Pedro e os com ele estavam premidos de sono; mas, ao acordarem plenamente, viram a glória dele e os dois homens em pé com ele.

[[v42-9-33]]

^<<v42-9-33,33>>^ E, enquanto estes estavam sendo separados dele, Pedro disse a Jesus: “Preceptor, é excelente que estejamos aqui; armemos, pois, três tendas, uma para ti, e uma para Moisés, e uma para Elias”, não se dando ele conta do que estava dizendo.

[[v42-9-34]]

^<<v42-9-34,34>>^ Mas, enquanto dizia estas coisas, formou-se uma nuvem e começou a encobri-los. Ao entrarem na nuvem, ficaram temerosos.

[[v42-9-35]]

^<<v42-9-35,35>>^ E uma voz saiu da nuvem, dizendo: “Este é meu Filho, aquele que foi escolhido. Escutai-o.”

[[v42-9-36]]

^<<v42-9-36,36>>^ E, quando houve a voz, Jesus achou-se sozinho. Mas eles ficaram calados e não relataram a ninguém naqueles dias quaisquer das coisas que viram.

[[v42-9-37]]

^<<v42-9-37,37>>^ No dia seguinte, ao descerem do monte, veio ao encontro dele uma grande multidão.

[[v42-9-38]]

^<<v42-9-38,38>>^ E eis que um homem dentre a multidão clamava, dizendo: “Instrutor, rogo-te que dês uma olhada no meu filho, porque ele é o meu unigênito,^&#42;1^

[NOTE]
====
. Ou “único”. Gr.: mo·no·ge·nés.
====

[[v42-9-39]]

^<<v42-9-39,39>>^ e eis que um espírito o apanha, e ele clama repentinamente, e [o espírito] lança-o em convulsões, com espuma, e quase não se retira dele depois de o machucar.

[[v42-9-40]]

^<<v42-9-40,40>>^ E roguei a teus discípulos que o expulsassem, mas não puderam.”

[[v42-9-41]]

^<<v42-9-41,41>>^ Em resposta, Jesus disse: “Ó geração sem fé e deturpada, até quando terei de continuar convosco e terei de suportar-vos? Traze teu filho para cá.”

[[v42-9-42]]

^<<v42-9-42,42>>^ Enquanto este se aproximava, porém, o demônio lançou-o ao chão e o convulsionou violentamente. No entanto, Jesus censurou o espírito impuro e sarou o menino, e o entregou ao seu pai.

[[v42-9-43]]

^<<v42-9-43,43>>^ Pois bem, todos ficaram assombrados com o poder majestoso^&#42;1^ de Deus.
Então, enquanto todos se maravilhavam com todas as coisas que fazia, ele disse aos seus discípulos:

[NOTE]
====
. “Poder majestoso.” Ou “majestade”. Gr.: me·ga·lei·ó·te·ti; lat.: ma·gni·tú·di·ne; J17,22(hebr.): gedhul·láth.
====

[[v42-9-44]]

^<<v42-9-44,44>>^ “Alojai estas palavras nos vossos ouvidos, porque o Filho do homem está destinado a ser entregue nas mãos dos homens.”

[[v42-9-45]]

^<<v42-9-45,45>>^ Mas continuaram sem entendimento desta declaração. De fato, foi-lhes oculto para que não o percebessem, e tinham medo de interrogá-lo sobre esta declaração.

[[v42-9-46]]

^<<v42-9-46,46>>^ Chegaram então a raciocinar quem dentre eles seria^&#42;1^ o maior deles.

[NOTE]
====
. Ou “quem . . . era”.
====

[[v42-9-47]]

^<<v42-9-47,47>>^ Jesus, sabendo os raciocínios dos seus corações, tomou uma criancinha, colocou-a ao seu lado

[[v42-9-48]]

^<<v42-9-48,48>>^ e disse-lhes: “Todo aquele que receber esta criancinha à base do meu nome, [também] a mim me recebe, e todo aquele que me receber, recebe [também] aquele que me enviou. Pois, quem se comportar como menor entre todos vós é o que é^&#42;1^ grande.”

[NOTE]
====
. Ou “há de ser”.
====

[[v42-9-49]]

^<<v42-9-49,49>>^ Em resposta, João disse: “Preceptor, vimos certo homem expulsar demônios pelo uso de teu nome e tentamos impedi-lo, porque ele não segue^&#42;1^ conosco.”

[NOTE]
====
. Ou “vai”.
====

[[v42-9-50]]

^<<v42-9-50,50>>^ Mas Jesus disse-lhe: “Não tenteis impedi[-lo], pois quem não é contra vós, é por vós.”

[[v42-9-51]]

^<<v42-9-51,51>>^ Chegando então a completar-se para ele os dias de ser tomado para cima,^&#42;1^ endureceu o rosto [na determinação] de ir a Jerusalém.

[NOTE]
====
. Ou “de sua ascensão”.
====

[[v42-9-52]]

^<<v42-9-52,52>>^ De modo que enviou mensageiros na sua frente. E eles foram e entraram numa aldeia de samaritanos, a fim de fazerem os preparativos para ele;

[[v42-9-53]]

^<<v42-9-53,53>>^ mas não o receberam, porque o seu rosto estava endurecido [na determinação] de ir a Jerusalém.

[[v42-9-54]]

^<<v42-9-54,54>>^ Vendo isso os discípulos Tiago e João, disseram: “Senhor,^&#42;1^ queres que mandemos que desça fogo do céu e os aniquile?”

[NOTE]
====
. Ou “Amo”.
====

[[v42-9-55]]

^<<v42-9-55,55>>^ Mas ele se voltou e os censurou.

[[v42-9-56]]

^<<v42-9-56,56>>^ Foram assim a uma aldeia diferente.

[[v42-9-57]]

^<<v42-9-57,57>>^ Enquanto caminhavam assim pela estrada, alguém lhe disse: “Eu te seguirei para onde quer que partires.”

[[v42-9-58]]

^<<v42-9-58,58>>^ E Jesus lhe disse: “As raposas têm covis e as aves do céu têm poleiros, mas o Filho do homem não tem onde deitar a cabeça.”

[[v42-9-59]]

^<<v42-9-59,59>>^ Disse então a outro: “Sê meu seguidor.” O homem disse: “Permite-me primeiro ir e enterrar meu pai.”

[[v42-9-60]]

^<<v42-9-60,60>>^ Mas ele lhe disse: “Deixa que os mortos enterrem seus mortos, mas tu, vai e divulga o reino de Deus.”

[[v42-9-61]]

^<<v42-9-61,61>>^ E ainda outro disse: “Eu te seguirei, Senhor; mas permite-me primeiro que eu me despeça dos da minha família.”^&#42;1^

[NOTE]
====
. Ou “casa”.
====

[[v42-9-62]]

^<<v42-9-62,62>>^ Jesus disse-lhe: “Ninguém que tiver posto a mão num arado e olhar para as coisas atrás é bem apto para o reino de Deus.”

'''

xref:042-lucas/042-lucas-008.adoc#v42-8-0[&#60; Capítulo Anterior] | <<v42-9-0,Topo>> | xref:042-lucas/042-lucas-010.adoc#v42-10-0[Próximo Capítulo &#62;]