include::./index.adoc[]

[[v42-16-0]]
=== Lucas, 16
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v42-16-1]]

^<<v42-16-1,1>>^ Prosseguiu então a dizer também aos discípulos: “Certo homem era rico e tinha um mordomo,^&#42;1^ e este foi acusado diante dele de manejar com desperdício os seus bens.

[NOTE]
====
. Ou “administrador doméstico”. Gr.: oi·ko·nó·mon; J22(hebr.): soh·khen-bá·yith.
====

[[v42-16-2]]

^<<v42-16-2,2>>^ Chamou-o assim e disse-lhe: ‘Que é isso que ouço a teu respeito? Presta contas da tua mordomia, pois não podes mais administrar a casa.’

[[v42-16-3]]

^<<v42-16-3,3>>^ O mordomo disse então no seu íntimo: ‘Que é que vou fazer, visto que o meu amo vai tirar-me a mordomia? Não sou bastante forte para cavar; tenho vergonha de mendigar.

[[v42-16-4]]

^<<v42-16-4,4>>^ Ah! Sei o que vou fazer, para que, quando eu for demitido da mordomia, as pessoas me recebam nos seus lares.’

[[v42-16-5]]

^<<v42-16-5,5>>^ E, chamando a si a cada um dos devedores de seu amo, passou a dizer ao primeiro: ‘Quanto deves ao meu amo?’

[[v42-16-6]]

^<<v42-16-6,6>>^ Ele disse: ‘Cem batos^&#42;1^ de azeite.’ Disse-lhe ele: ‘Toma de volta o teu acordo escrito e assenta-te, e escreve rapidamente cinqüenta’.

[NOTE]
====
. O bato equivalia a 22 l.
====

[[v42-16-7]]

^<<v42-16-7,7>>^ A seguir, disse a outro: ‘Agora tu, quanto estás devendo?’ Ele disse: ‘Cem coros^&#42;1^ de trigo.’ Ele lhe disse: ‘Toma de volta o teu acordo escrito e escreve oitenta.’

[NOTE]
====
. O coro equivalia a 220 l.
====

[[v42-16-8]]

^<<v42-16-8,8>>^ E o seu amo elogiou o mordomo, embora [fosse] injusto, porque agiu com sabedoria prática; pois os filhos deste sistema de coisas^&#42;1^ são mais sábios, em sentido prático, para com a sua própria geração, do que os filhos da luz.

[NOTE]
====
. Ou “ordem de coisas”. Gr.: ai·ó·nos; lat.: saé·cu·li; J17,18,22(hebr.): ha·‛oh·lám, “da ordem de coisas”.
====

[[v42-16-9]]

^<<v42-16-9,9>>^ “Eu vos digo também: Fazei para vós amigos por meio das riquezas injustas,^&#42;1^ para que, quando estas vos falharem, vos recebam nas moradias eternas.^&#42;2^

[NOTE]
====
. Lit.: “mamom da injustiça”. Gr.: ma·mo·ná tes a·di·kí·as.
. Lit.: “tendas eternas”.
====

[[v42-16-10]]

^<<v42-16-10,10>>^ Quem é fiel no mínimo, é também fiel no muito, e quem é injusto no mínimo, é também injusto no muito.

[[v42-16-11]]

^<<v42-16-11,11>>^ Portanto, se não vos mostrastes fiéis em conexão com as riquezas injustas, quem vos confiará o que é verdadeiro?

[[v42-16-12]]

^<<v42-16-12,12>>^ E, se não vos mostrastes fiéis em conexão com o que é de outro, quem vos dará o que é para vós mesmos?^&#42;1^

[NOTE]
====
. Ou “o que é vosso”, P75אADWVgSyh,p,s; B: “o que é nosso”.
====

[[v42-16-13]]

^<<v42-16-13,13>>^ Nenhum servo doméstico pode ser escravo de dois amos; pois, ou há de odiar um e amar o outro, ou se apegará a um e desprezará o outro. Não podeis ser escravos de Deus e das Riquezas.”^&#42;1^

[NOTE]
====
. Lit.: “de mamom”. Gr.: ma·mo·naí; lat.: ma·mó·nae; J17,18,22(hebr.): ham·ma·móhn, “de mamom”.
====

[[v42-16-14]]

^<<v42-16-14,14>>^ Ora, os fariseus, que eram amantes do dinheiro, estavam escutando todas estas coisas, e começaram a escarnecer dele.

[[v42-16-15]]

^<<v42-16-15,15>>^ Conseqüentemente, ele lhes disse: “Vós sois os que vos declarais justos perante os homens, mas Deus conhece os vossos corações; porque aquilo que é altivo entre os homens é uma coisa repugnante à vista de Deus.

[[v42-16-16]]

^<<v42-16-16,16>>^ “A Lei e os Profetas [existiram] até João. Dali em diante, o reino de Deus está sendo declarado como boas novas,^&#42;1^ e toda sorte de pessoa avança impetuosamente em direção dele.

[NOTE]
====
. “Está sendo declarado como boas novas.” Gr.: eu·ag·ge·lí·ze·tai; lat.: e·van·ge·li·zá·tur; J22(hebr.): mith·bas·sé·reth.
====

[[v42-16-17]]

^<<v42-16-17,17>>^ Deveras, mais fácil é passarem céu e terra do que passar sem cumprimento uma só partícula duma letra da Lei.

[[v42-16-18]]

^<<v42-16-18,18>>^ “Todo aquele que se divorciar de sua esposa e se casar com outra, comete adultério,^&#42;1^ e quem se casar com uma mulher divorciada^&#42;2^ do marido, comete adultério.

[NOTE]
====
. Veja Mt 5:32 n.: “adultério”.
. Lit.: “solta”.
====

[[v42-16-19]]

^<<v42-16-19,19>>^ “Mas, certo homem era rico e costumava cobrir-se de púrpura e de linho, regalando-se de dia a dia com magnificência.

[[v42-16-20]]

^<<v42-16-20,20>>^ Mas, certo mendigo,^&#42;1^ de nome Lázaro,^&#42;2^ costumava ser colocado junto ao seu portão, [estando] cheio de úlceras

[NOTE]
====
. Ou “pobre”.
. “Lázaro”, אAB; J18,22(hebr.): ’El·‛a·zár, “Eleazar”, significando “Deus Ajudou”.
====

[[v42-16-21]]

^<<v42-16-21,21>>^ e desejoso de saciar-se com as coisas que caíam da mesa do rico. Sim, também os cães vinham e lambiam as suas úlceras.

[[v42-16-22]]

^<<v42-16-22,22>>^ Ora, no decorrer do tempo, morreu o mendigo e foi carregado pelos anjos para [a posição junto ao] seio^&#42;1^ de Abraão.
“Também o rico morreu e foi enterrado.

[NOTE]
====
. “[A posição junto ao] seio”, como quando alguém se recosta na frente de outro, no mesmo leito, numa refeição.
====

[[v42-16-23]]

^<<v42-16-23,23>>^ E no Hades,^&#42;1^ ele^&#42;2^ ergueu os olhos, estando em tormentos, e viu Abraão de longe, e Lázaro com ele [na posição junto] ao seio.

[NOTE]
====
. “Hades”, אAB; J6-8,10-18,22: “Seol”; lat.: in·fér·no. Veja Ap. 4B.
. “E foi enterrado. E no Hades, ele”, AB; א°: “e foi sepultado no Hades, ele”; Vg(lat.): “e ele foi sepultado in in·fér·no. Mas ele”.
====

[[v42-16-24]]

^<<v42-16-24,24>>^ Por isso chamou e disse: ‘Pai Abraão, tem misericórdia de mim e manda que Lázaro mergulhe a ponta do seu dedo em água e refresque a minha língua, porque eu estou em angústia neste fogo intenso.’

[[v42-16-25]]

^<<v42-16-25,25>>^ Mas Abraão disse: ‘Filho, lembra-te de que recebeste plenamente as tuas boas coisas no curso da tua vida, mas Lázaro, correspondentemente, as coisas prejudiciais. Agora, porém, ele está tendo consolo aqui, mas tu estás em angústia.

[[v42-16-26]]

^<<v42-16-26,26>>^ E, além de todas essas coisas, estabeleceu-se um grande precipício entre nós e vós, de modo que os que querem passar daqui para vós não o podem, nem podem pessoas passar de lá para nós.’

[[v42-16-27]]

^<<v42-16-27,27>>^ Ele disse então: ‘Neste caso, peço-te, pai, que o envies à casa de meu pai,

[[v42-16-28]]

^<<v42-16-28,28>>^ pois eu tenho cinco irmãos, a fim de que lhes dê um testemunho cabal, para que não cheguem a entrar neste lugar de tormento.’

[[v42-16-29]]

^<<v42-16-29,29>>^ Mas Abraão disse: ‘Eles têm Moisés e os Profetas; que escutem a estes.’

[[v42-16-30]]

^<<v42-16-30,30>>^ Ele disse então: ‘Não assim, pai Abraão, mas, se alguém dentre os mortos for ter com eles, arrepender-se-ão.’

[[v42-16-31]]

^<<v42-16-31,31>>^ Mas ele lhe disse: ‘Se não escutam Moisés e os Profetas, tampouco serão persuadidos se alguém se levantar dentre os mortos.’”

'''

xref:042-lucas/042-lucas-015.adoc#v42-15-0[&#60; Capítulo Anterior] | <<v42-16-0,Topo>> | xref:042-lucas/042-lucas-017.adoc#v42-17-0[Próximo Capítulo &#62;]