include::./index.adoc[]

[[v42-8-0]]
=== Lucas, 8
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v42-8-1]]

^<<v42-8-1,1>>^ Pouco depois, ele viajava de cidade em cidade e de aldeia em aldeia, pregando^&#42;1^ e declarando as boas novas do reino de Deus. E os doze estavam com ele,

[NOTE]
====
. Ou “proclamando”. Gr.: ke·rýs·son; lat.: praé·di·cans.
====

[[v42-8-2]]

^<<v42-8-2,2>>^ bem como certas mulheres que tinham sido curadas de espíritos iníquos e de doenças, Maria, a chamada Madalena, da qual saíram sete demônios,

[[v42-8-3]]

^<<v42-8-3,3>>^ e Joana, esposa de Cuza, encarregado de Herodes, e Susana, e muitas outras mulheres, que lhes ministravam de seus bens.

[[v42-8-4]]

^<<v42-8-4,4>>^ Tendo-se então reunido uma grande multidão com os que se dirigiam a ele de cidade após cidade, falou por meio duma ilustração:

[[v42-8-5]]

^<<v42-8-5,5>>^ “Um semeador saiu a semear a sua semente. Ora, ao passo que semeava, parte dela caiu à beira da estrada e foi pisada, e as aves do céu a comeram.

[[v42-8-6]]

^<<v42-8-6,6>>^ Outra caiu sobre a rocha, e, depois de brotar, secou-se, porque não tinha umidade.

[[v42-8-7]]

^<<v42-8-7,7>>^ Outra caiu entre os espinhos, e os espinhos que cresceram junto com ela a sufocaram.

[[v42-8-8]]

^<<v42-8-8,8>>^ Outra caiu em solo bom, e, depois de brotar, produziu fruto cem vezes mais.” Ao dizer-lhes estas coisas, passou a clamar: “Escute aquele que tem ouvidos para escutar.”

[[v42-8-9]]

^<<v42-8-9,9>>^ Mas os seus discípulos começaram a perguntar-lhe o que significava esta ilustração.

[[v42-8-10]]

^<<v42-8-10,10>>^ Ele disse: “A vós é concedido entender os segredos sagrados do reino de Deus, mas para os demais é em ilustrações, a fim de que, embora olhem, olhem em vão, e, embora ouçam, não compreendam o significado.

[[v42-8-11]]

^<<v42-8-11,11>>^ Ora, a ilustração significa o seguinte: A semente é a palavra de Deus.

[[v42-8-12]]

^<<v42-8-12,12>>^ Os à beira da estrada são os que ouviram, depois vem o Diabo e tira dos seus corações a palavra, a fim de que não creiam e sejam salvos.

[[v42-8-13]]

^<<v42-8-13,13>>^ Aqueles na rocha são os que, quando a ouvem, recebem a palavra com alegria, mas esses não têm raiz; crêem por certa época, mas numa época de prova afastam-se.

[[v42-8-14]]

^<<v42-8-14,14>>^ Quanto à que caiu entre os espinhos, estes são os que têm ouvido, mas, por serem arrebatados pelas ansiedades, e riquezas, e prazeres desta vida, ficam completamente sufocados e não trazem nada à perfeição.

[[v42-8-15]]

^<<v42-8-15,15>>^ Quanto àquela em solo excelente, estes são os que, depois de ouvirem a palavra com um coração excelente e bom, a retêm e dão fruto com perseverança.

[[v42-8-16]]

^<<v42-8-16,16>>^ “Ninguém, depois de acender uma lâmpada, a cobre com um vaso ou a põe debaixo duma cama, mas a coloca num velador, para que os que entram possam observar a luz.

[[v42-8-17]]

^<<v42-8-17,17>>^ Pois, não há nada escondido que não se torne manifesto, tampouco há nada cuidadosamente oculto que nunca se torne conhecido e nunca venha à tona.

[[v42-8-18]]

^<<v42-8-18,18>>^ Portanto, prestai atenção a como escutais; pois a quem tiver, mais será dado, mas quem não tiver, até mesmo o que imagina ter lhe será tirado.”

[[v42-8-19]]

^<<v42-8-19,19>>^ Vieram ter com ele então sua mãe e seus irmãos, mas não puderam chegar a ele por causa da multidão.

[[v42-8-20]]

^<<v42-8-20,20>>^ No entanto, relatou-se-lhe: “Tua mãe e teus irmãos estão parados lá fora, querendo ver-te.”

[[v42-8-21]]

^<<v42-8-21,21>>^ Em resposta, ele lhes disse: “Minha mãe e meus irmãos são estes os que ouvem a palavra de Deus e a praticam.”

[[v42-8-22]]

^<<v42-8-22,22>>^ No decorrer de um daqueles dias, ele e seus discípulos entraram num barco, e ele lhes disse: “Passemos para o outro lado do lago.” Assim, fizeram-se à vela.

[[v42-8-23]]

^<<v42-8-23,23>>^ Mas, enquanto velejavam, ele adormeceu. Abateu-se então uma violenta tempestade de vento sobre o lago, e começaram a ficar inundados e a estar em perigo.

[[v42-8-24]]

^<<v42-8-24,24>>^ Por fim se dirigiram a ele e o acordaram, dizendo: “Preceptor, Preceptor, estamos prestes a perecer!” Acordando, censurou o vento e a fúria da água, e eles cessaram, e deu-se uma calmaria.

[[v42-8-25]]

^<<v42-8-25,25>>^ Então lhes disse: “Onde está a vossa fé?” Mas eles se maravilhavam, tomados de temor, dizendo um ao outro: “Quem é realmente este, porque dá ordens até mesmo aos ventos e à água, e eles lhe obedecem?”

[[v42-8-26]]

^<<v42-8-26,26>>^ E rumaram para a margem no país dos gerasenos,^&#42;1^ que se acha no lado oposto à Galiléia.

[NOTE]
====
. “Gerasenos”, P75BDItVg; א: “gergesenos”; ASyp,s: “gadarenos”.
====

[[v42-8-27]]

^<<v42-8-27,27>>^ Mas, ao saltar em terra, veio encontrá-lo certo homem da cidade, que tinha demônios. E ele não tinha usado roupa por bastante tempo, e ficava, não em casa, mas entre os túmulos.

[[v42-8-28]]

^<<v42-8-28,28>>^ À vista de Jesus, gritou alto e prostrou-se diante dele, e disse com voz alta: “Que tenho eu contigo,^&#42;1^ Jesus, Filho do Deus Altíssimo? Eu te peço que não me atormentes.”

[NOTE]
====
. Esta é uma expressão idiomática; é uma pergunta de repulsa, indicando objeção. Veja Ap. 7B.
====

[[v42-8-29]]

^<<v42-8-29,29>>^ (Pois ele tinha ordenado ao espírito impuro que saísse do homem. Porque por longo tempo o mantivera agarrado, e ele fora repetidas vezes amarrado com cadeias e grilhões, sob guarda, mas rebentava os laços e era impelido pelo demônio para os lugares solitários.)

[[v42-8-30]]

^<<v42-8-30,30>>^ Jesus perguntou-lhe: “Qual é teu nome?” Ele disse: “Legião”, porque muitos demônios haviam entrado nele.

[[v42-8-31]]

^<<v42-8-31,31>>^ E suplicavam-lhe que não lhes ordenasse que se afastassem para o abismo.^&#42;1^

[NOTE]
====
. Ou “a profundeza”. Veja Ro 10:7.
====

[[v42-8-32]]

^<<v42-8-32,32>>^ Ora, ali no monte pastava uma manada de um número considerável de porcos; de modo que lhe suplicaram que lhes permitisse entrar nesses. E ele lhes deu permissão.

[[v42-8-33]]

^<<v42-8-33,33>>^ Os demônios saíram então do homem e entraram nos porcos, e a manada precipitou-se despenhadeiro abaixo para dentro do lago e se afogou.

[[v42-8-34]]

^<<v42-8-34,34>>^ Mas, quando os porqueiros viram o que tinha acontecido, fugiram e o relataram na cidade e na zona rural.

[[v42-8-35]]

^<<v42-8-35,35>>^ As pessoas chegaram-se então para ver o que tinha acontecido, e chegaram a Jesus e encontraram o homem, de quem saíram os demônios, vestido e de são juízo, sentado aos pés de Jesus; e ficaram temerosos.

[[v42-8-36]]

^<<v42-8-36,36>>^ Os que tinham visto isso relataram-lhes como o homem possesso de demônios ficara bom.^&#42;1^

[NOTE]
====
. Ou “fora salvo”.
====

[[v42-8-37]]

^<<v42-8-37,37>>^ Assim, toda a multidão da região circunvizinha dos gerasenos^&#42;1^ pediu-lhe que se afastasse deles, porque estavam tomados de grande temor. Ele entrou então no barco e afastou-se.

[NOTE]
====
. Veja v. 26 n.
====

[[v42-8-38]]

^<<v42-8-38,38>>^ No entanto, o homem de quem saíram os demônios pedia-lhe para continuar com ele; mas ele despediu o homem, dizendo:

[[v42-8-39]]

^<<v42-8-39,39>>^ “Vai de volta para casa e persiste em relatar as coisas que Deus fez para ti.” Concordemente, foi embora, proclamando em toda a cidade as coisas que Jesus fizera para ele.

[[v42-8-40]]

^<<v42-8-40,40>>^ Quando Jesus voltou, a multidão o recebeu benevolamente, pois todos o esperavam.

[[v42-8-41]]

^<<v42-8-41,41>>^ Mas, eis que veio um homem de nome Jairo, e este homem era um presidente da sinagoga. E ele se prostrou aos pés de Jesus e começou a suplicar-lhe que entrasse na sua casa,

[[v42-8-42]]

^<<v42-8-42,42>>^ porque tinha uma filha unigênita,^&#42;1^ de cerca de doze anos, e ela estava à morte.
Enquanto ia, as multidões o comprimiam.

[NOTE]
====
. Ou “única”. Gr.: mo·no·ge·nés. Veja Jz 11:34 n.: “única”.
====

[[v42-8-43]]

^<<v42-8-43,43>>^ E uma mulher, por doze anos padecendo dum fluxo de sangue, que não conseguira cura da parte de ninguém,

[[v42-8-44]]

^<<v42-8-44,44>>^ aproximou-se por detrás e tocou na orla^&#42;1^ de sua roupa exterior, e o seu fluxo de sangue parou instantaneamente.

[NOTE]
====
. Ou “bainha; borla”.
====

[[v42-8-45]]

^<<v42-8-45,45>>^ De modo que Jesus disse: “Quem foi que me tocou?” Quando todos o negavam, Pedro disse: “Preceptor, as multidões te rodeiam e apertam.”

[[v42-8-46]]

^<<v42-8-46,46>>^ Contudo, Jesus disse: “Alguém me tocou, pois percebi que poder saiu de mim.”

[[v42-8-47]]

^<<v42-8-47,47>>^ Vendo que não passara despercebida, a mulher veio trêmula e prostrou-se diante dele, e revelou perante todo o povo a causa pela qual o tocara e como fora curada instantaneamente.

[[v42-8-48]]

^<<v42-8-48,48>>^ Mas ele lhe disse: “Filha, a tua fé te fez ficar boa;^&#42;1^ vai em paz.”

[NOTE]
====
. Ou “te salvou”.
====

[[v42-8-49]]

^<<v42-8-49,49>>^ Enquanto ainda falava, chegou certo representante do presidente da sinagoga, dizendo: “A tua filha morreu; não incomodes mais o instrutor.”

[[v42-8-50]]

^<<v42-8-50,50>>^ Ouvindo isso, Jesus respondeu-lhe: “Não temas, apenas exerce fé, e ela será salva.”

[[v42-8-51]]

^<<v42-8-51,51>>^ Chegando à casa, não deixou ninguém entrar com ele, exceto Pedro, e João, e Tiago, e o pai e a mãe da menina.

[[v42-8-52]]

^<<v42-8-52,52>>^ E todos choravam e se batiam de pesar por ela. De modo que ele disse: “Parai de chorar, pois ela não está morta, mas dorme.”

[[v42-8-53]]

^<<v42-8-53,53>>^ Começaram então a rir-se dele desdenhosamente, porque sabiam que ela havia morrido.

[[v42-8-54]]

^<<v42-8-54,54>>^ Mas ele a tomou pela mão e chamou, dizendo: “Menina, levanta-te!”^&#42;1^

[NOTE]
====
. Ou: “desperta!”
====

[[v42-8-55]]

^<<v42-8-55,55>>^ E voltou-lhe o espírito^&#42;1^ e ela se levantou instantaneamente, e ele ordenou que se lhe desse algo para comer.

[NOTE]
====
. Ou “o fôlego (força de vida)”. Gr.: to pneú·ma au·tés; J17,18,22(hebr.): ru·hháh.
====

[[v42-8-56]]

^<<v42-8-56,56>>^ Ora, os pais dela estavam fora de si; mas ele lhes ordenou que não dissessem a ninguém o que tinha acontecido.

'''

xref:042-lucas/042-lucas-007.adoc#v42-7-0[&#60; Capítulo Anterior] | <<v42-8-0,Topo>> | xref:042-lucas/042-lucas-009.adoc#v42-9-0[Próximo Capítulo &#62;]