include::./index.adoc[]

[[v42-21-0]]
=== Lucas, 21
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v42-21-1]]

^<<v42-21-1,1>>^ Erguendo então os olhos, viu os ricos lançarem suas dádivas nos cofres do tesouro.^&#42;1^

[NOTE]
====
. Ou “da tesouraria sagrada”.
====

[[v42-21-2]]

^<<v42-21-2,2>>^ Viu então certa viúva necessitada lançar [neles] duas pequenas moedas de muito pouco valor^&#42;1^

[NOTE]
====
. Lit.: “dois leptas”. Veja Ap. 8A.
====

[[v42-21-3]]

^<<v42-21-3,3>>^ e disse: “Eu vos digo verazmente: Esta viúva, embora pobre, lançou [neles] mais do que todos eles.

[[v42-21-4]]

^<<v42-21-4,4>>^ Porque todos estes lançaram [neles] dádivas^&#42;1^ do que lhes sobrava, mas esta [mulher], de sua carência, lançou [neles] todo o seu meio de vida.”

[NOTE]
====
. Ou “contribuíram para as dádivas”.
====

[[v42-21-5]]

^<<v42-21-5,5>>^ Mais tarde, visto que havia certos falando sobre o templo, que este estava adornado com pedras excelentes e com coisas dedicadas,

[[v42-21-6]]

^<<v42-21-6,6>>^ ele disse: “Quanto a estas coisas que estais observando, virão os dias em que não ficará aqui pedra sobre pedra sem ser derrubada.”

[[v42-21-7]]

^<<v42-21-7,7>>^ Interrogaram-no então, dizendo: “Instrutor, quando serão realmente estas coisas e qual será o sinal quando estas coisas estão destinadas a ocorrer?”

[[v42-21-8]]

^<<v42-21-8,8>>^ Ele disse: “Acautelai-vos de que ninguém vos desencaminhe; porque muitos virão à base do meu nome, dizendo: ‘Sou eu’, e: ‘Aproximou-se o tempo devido.’ Não vades após eles.

[[v42-21-9]]

^<<v42-21-9,9>>^ Além disso, quando ouvirdes [falar] de guerras e desordens, não fiqueis apavorados. Porque estas coisas têm de ocorrer primeiro, mas o fim^&#42;1^ não [ocorre] imediatamente.”

[NOTE]
====
. Ou “remate; fim completo”. Gr.: té·los.
====

[[v42-21-10]]

^<<v42-21-10,10>>^ Então prosseguiu a dizer-lhes: “Nação se levantará^&#42;1^ contra nação e reino contra reino;

[NOTE]
====
. Ou “se agitará; se excitará”.
====

[[v42-21-11]]

^<<v42-21-11,11>>^ e haverá grandes terremotos, e, num lugar após outro, pestilências e escassez de víveres; e haverá vistas aterrorizantes e grandes sinais do céu.

[[v42-21-12]]

^<<v42-21-12,12>>^ “Mas, antes de todas estas coisas, as pessoas deitarão mãos em vós e vos perseguirão, entregando-vos às sinagogas e às prisões, sendo vós arrastados perante reis e governadores por causa do meu nome.

[[v42-21-13]]

^<<v42-21-13,13>>^ Isto vos resultará num testemunho.^&#42;1^

[NOTE]
====
. “Testemunho.” Gr.: mar·tý·ri·on; lat.: te·sti·mó·ni·um.
====

[[v42-21-14]]

^<<v42-21-14,14>>^ Portanto, assentai nos vossos corações não ensaiar de antemão como fazer a vossa defesa,

[[v42-21-15]]

^<<v42-21-15,15>>^ porque eu vos darei uma boca^&#42;1^ e sabedoria, à qual todos os vossos opositores juntos não poderão resistir, nem [a] disputar.

[NOTE]
====
. Ou “fala vigorosa”.
====

[[v42-21-16]]

^<<v42-21-16,16>>^ Além disso, sereis entregues até mesmo por pais, e irmãos, e parentes, e amigos, e eles entregarão alguns de vós à morte;

[[v42-21-17]]

^<<v42-21-17,17>>^ e vós sereis pessoas odiadas por todos, por causa do meu nome.

[[v42-21-18]]

^<<v42-21-18,18>>^ Contudo, nenhum cabelo de vossa cabeça perecerá de modo algum.

[[v42-21-19]]

^<<v42-21-19,19>>^ Pela perseverança da vossa parte adquirireis as vossas almas.^&#42;1^

[NOTE]
====
. Ou “as vossas vidas [futuras]”. Gr.: psy·khás hy·món; J17(hebr.): naf·sho·theh·khém. Veja Mt 10:28.
====

[[v42-21-20]]

^<<v42-21-20,20>>^ “Outrossim, quando virdes Jerusalém cercada por exércitos acampados, então sabei que se tem aproximado a desolação dela.

[[v42-21-21]]

^<<v42-21-21,21>>^ Então, comecem a fugir para os montes os que estiverem na Judéia, e retirem-se os que estiverem no meio dela, e não entrem nela os que estiverem nos campos;

[[v42-21-22]]

^<<v42-21-22,22>>^ porque estes são dias para se executar a justiça,^&#42;1^ para que se cumpram todas as coisas escritas.

[NOTE]
====
. Lit.: “dias de vingança”.
====

[[v42-21-23]]

^<<v42-21-23,23>>^ Ai das mulheres grávidas e das que amamentarem naqueles dias! Porque haverá grande necessidade na terra e furor sobre este povo;

[[v42-21-24]]

^<<v42-21-24,24>>^ e cairão pelo fio da espada e serão levados cativos para todas as nações; e Jerusalém será pisada pelas nações,^&#42;1^ até se cumprirem^&#42;2^ os tempos designados das nações.

[NOTE]
====
. “Nações.” Gr.: e·thnón; lat.: gén·ti·bus, “gentios”; J17(hebr.): ghoh·yím, “goim”.
. “Se cumprirem e serem”, B.
====

[[v42-21-25]]

^<<v42-21-25,25>>^ “Também, haverá sinais no sol, e na lua, e nas estrelas, e na terra angústia de nações, não sabendo o que fazer por causa do rugido do mar e da [sua] agitação,

[[v42-21-26]]

^<<v42-21-26,26>>^ os homens ficando desalentados de temor e na expectativa das coisas que vêm sobre a terra habitada;^&#42;1^ porque os poderes^&#42;2^ dos céus serão abalados.

[NOTE]
====
. Lit.: “a habitada”. Gr.: tei oi·kou·mé·nei, dativo, fem. sing., referindo-se à terra; lat.: u·ni·vér·so ór·bi, “o círculo inteiro”, isto é, da terra. Veja Is 13:11 n.: “produtivo”; Na 1:5 n.
. Ou “as forças; hostes”.
====

[[v42-21-27]]

^<<v42-21-27,27>>^ E então verão o Filho do homem vindo^&#42;1^ numa nuvem, com poder e grande glória.

[NOTE]
====
. “Vindo.” Gr.: er·khó·me·non.
====

[[v42-21-28]]

^<<v42-21-28,28>>^ Mas, quando estas coisas principiarem a ocorrer, erguei-vos e levantai as vossas cabeças, porque o vosso livramento está-se aproximando.”

[[v42-21-29]]

^<<v42-21-29,29>>^ Com isso contou-lhes uma ilustração: “Reparai na figueira e em todas as outras árvores:

[[v42-21-30]]

^<<v42-21-30,30>>^ Quando já estão em flor, sabeis por vós mesmos, observando isso, que já está próximo o verão.

[[v42-21-31]]

^<<v42-21-31,31>>^ Deste modo também vós, quando virdes estas coisas ocorrer, sabei que está próximo o reino de Deus.

[[v42-21-32]]

^<<v42-21-32,32>>^ Deveras, eu vos digo: Esta geração^&#42;1^ de modo algum passará até que todas estas coisas ocorram.

[NOTE]
====
. “Geração.” Gr.: ge·ne·á; é diferente de gé·nos, “raça”, como em 1Pe 2:9.
====

[[v42-21-33]]

^<<v42-21-33,33>>^ Céu e terra passarão, mas as minhas palavras de modo algum passarão.

[[v42-21-34]]

^<<v42-21-34,34>>^ “Mas, prestai atenção a vós mesmos, para que os vossos corações nunca fiquem sobrecarregados com o excesso no comer, e com a imoderação no beber, e com as ansiedades da vida,^&#42;1^ e aquele dia venha sobre vós instantaneamente

[NOTE]
====
. Ou “ansiedade quanto aos meios de vida”.
====

[[v42-21-35]]

^<<v42-21-35,35>>^ como um laço. Pois virá sobre todos os que moram na face de toda a terra.

[[v42-21-36]]

^<<v42-21-36,36>>^ Portanto, mantende-vos despertos, fazendo todo o tempo súplica para que sejais bem sucedidos em escapar de todas estas coisas que estão destinadas a ocorrer, e em ficar em pé diante do Filho do homem.”

[[v42-21-37]]

^<<v42-21-37,37>>^ Assim, de dia ele ensinava no templo, mas de noite saía e pousava no monte chamado Monte das Oliveiras.

[[v42-21-38]]

^<<v42-21-38,38>>^ E todo o povo, de manhã cedo, ia ter com ele no templo, para ouvi-lo.

'''

xref:042-lucas/042-lucas-020.adoc#v42-20-0[&#60; Capítulo Anterior] | <<v42-21-0,Topo>> | xref:042-lucas/042-lucas-022.adoc#v42-22-0[Próximo Capítulo &#62;]