include::./index.adoc[]

[[v42-10-0]]
=== Lucas, 10
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v42-10-1]]

^<<v42-10-1,1>>^ Depois destas coisas, o Senhor indicou outros setenta^&#42;1^ e os enviou, aos dois, na sua frente, a cada cidade e lugar aonde ele mesmo estava para ir.

[NOTE]
====
. “Setenta”, אACWSyp; P75BDVgSyc,sArm: “setenta e dois”.
====

[[v42-10-2]]

^<<v42-10-2,2>>^ Começou então a dizer-lhes: “A colheita, deveras, é grande, mas os trabalhadores são poucos. Por isso, rogai ao Senhor da colheita que mande trabalhadores para a sua colheita.

[[v42-10-3]]

^<<v42-10-3,3>>^ Ide. Eis que eu vos envio como cordeiros no meio de lobos.

[[v42-10-4]]

^<<v42-10-4,4>>^ Não leveis bolsa, nem alforje, nem sandálias, e não abraceis a ninguém em cumprimento ao longo da estrada.

[[v42-10-5]]

^<<v42-10-5,5>>^ Onde quer que entrardes numa casa, dizei primeiro: ‘Haja paz nesta casa.’

[[v42-10-6]]

^<<v42-10-6,6>>^ E, se ali houver um amigo^&#42;1^ da paz, descansará sobre ele^&#42;2^ a vossa paz. Mas, se não houver, ela voltará para vós.

[NOTE]
====
. Lit.: “filho”.
. Ou “ela”.
====

[[v42-10-7]]

^<<v42-10-7,7>>^ Assim, ficai naquela casa, comendo e bebendo as coisas que provêem, porque o trabalhador é digno de seu salário. Não vos estejais transferindo de casa em casa.

[[v42-10-8]]

^<<v42-10-8,8>>^ “Também, onde quer que entrardes numa cidade e eles vos receberem, comei as coisas postas diante de vós,

[[v42-10-9]]

^<<v42-10-9,9>>^ e curai os doentes nela e continuai a dizer-lhes: ‘O reino de Deus se tem chegado a vós.’

[[v42-10-10]]

^<<v42-10-10,10>>^ Mas, onde quer que entrardes numa cidade e eles não vos receberem, saí para as suas ruas largas e dizei:

[[v42-10-11]]

^<<v42-10-11,11>>^ ‘Até mesmo o pó de vossa cidade, que se prendeu aos nossos pés, tiraremos contra vós. Não obstante, lembrai-vos do seguinte, que o reino de Deus se tem chegado.’

[[v42-10-12]]

^<<v42-10-12,12>>^ Eu vos digo que naquele dia será mais suportável para Sodoma do que para essa cidade.

[[v42-10-13]]

^<<v42-10-13,13>>^ “Ai de ti, Corazim! Ai de ti, Betsaida! Porque se as obras poderosas que ocorreram em vós tivessem ocorrido em Tiro e Sídon, há muito se teriam arrependido, sentadas em saco e cinzas.

[[v42-10-14]]

^<<v42-10-14,14>>^ Conseqüentemente, no julgamento, será mais suportável para Tiro e Sídon do que para vós.

[[v42-10-15]]

^<<v42-10-15,15>>^ E tu, Cafarnaum, serás por acaso enaltecida ao céu? Até o Hades^&#42;1^ descerás!

[NOTE]
====
. “Hades”, אABJ21; J7-18,22: “Seol”.
====

[[v42-10-16]]

^<<v42-10-16,16>>^ “Quem vos escuta, escuta [também] a mim. E quem vos desconsidera, desconsidera [também] a mim. Ademais, quem me desconsidera, desconsidera [também] aquele que me enviou.”

[[v42-10-17]]

^<<v42-10-17,17>>^ Os setenta^&#42;1^ voltaram então com alegria, dizendo: “Senhor,^&#42;2^ até mesmo os demônios nos ficam sujeitos pelo uso do teu nome.”

[NOTE]
====
. “Setenta”, אACWSyp; P45,75BDVgArm: “setenta e dois”.
. Ou “Amo”.
====

[[v42-10-18]]

^<<v42-10-18,18>>^ A isso lhes disse: “Comecei a observar Satanás já caído como relâmpago do céu.

[[v42-10-19]]

^<<v42-10-19,19>>^ Eis que eu vos tenho dado autoridade para pisardes serpentes e escorpiões sob os pés, e sobre todo o poder do inimigo, e nada, de modo algum, vos fará dano.

[[v42-10-20]]

^<<v42-10-20,20>>^ Não obstante, não vos alegreis com isso, que os espíritos estão sendo sujeitos a vós, mas alegrai-vos de que os vossos nomes foram inscritos nos céus.”

[[v42-10-21]]

^<<v42-10-21,21>>^ Naquela mesma hora ficou cheio de alegria no espírito santo e disse: “Eu te louvo publicamente, ó Pai, Senhor do céu e da terra, porque escondeste cuidadosamente estas coisas dos sábios e dos intelectuais, e as revelaste aos pequeninos. Sim, ó Pai, porque fazer assim veio a ser o modo aprovado por ti.

[[v42-10-22]]

^<<v42-10-22,22>>^ Todas as coisas me foram entregues por meu Pai, e quem o Filho é, ninguém sabe, exceto o Pai; e quem o Pai é, ninguém [sabe] exceto o Filho, e aquele a quem o Filho estiver disposto a revelá-lo.”

[[v42-10-23]]

^<<v42-10-23,23>>^ Com isso ele se voltou para os discípulos, em particular, e disse: “Felizes são os olhos que observam as coisas que vós estais observando.

[[v42-10-24]]

^<<v42-10-24,24>>^ Pois eu vos digo: Muitos profetas e reis desejaram ver as coisas que vós estais observando, mas não as viram, e ouvir as coisas que vós estais ouvindo, mas não as ouviram.”

[[v42-10-25]]

^<<v42-10-25,25>>^ Então, eis que se levantou certo homem versado na Lei, para prová-lo, e disse: “Instrutor, por fazer o que hei de herdar a vida eterna?”

[[v42-10-26]]

^<<v42-10-26,26>>^ Ele lhe disse: “O que está escrito na Lei? Como é que lês?”

[[v42-10-27]]

^<<v42-10-27,27>>^ Em resposta, disse: “‘Tens de amar a Jeová,^&#42;1^ teu Deus, de todo o teu coração, e de toda a tua alma,^&#42;2^ e de toda a tua força, e de toda a tua mente’, e, ‘o teu próximo como a ti mesmo’.”

[NOTE]
====
. Veja Ap. 1D.
. Ou “vida”. Veja Ap. 4A.
====

[[v42-10-28]]

^<<v42-10-28,28>>^ Ele lhe disse: “Respondeste corretamente; ‘persiste em fazer isso e obterás a vida’.”

[[v42-10-29]]

^<<v42-10-29,29>>^ Mas, querendo mostrar-se justo, o homem disse a Jesus: “Quem é realmente o meu próximo?”

[[v42-10-30]]

^<<v42-10-30,30>>^ Em resposta, Jesus disse: “Certo homem descia de Jerusalém para Jericó e caiu entre salteadores, que tanto o despojaram como lhe infligiram golpes, e foram embora, deixando-o semimorto.

[[v42-10-31]]

^<<v42-10-31,31>>^ Ora, por coincidência, certo sacerdote descia por aquela estrada, mas, quando o viu, passou pelo lado oposto.

[[v42-10-32]]

^<<v42-10-32,32>>^ Do mesmo modo também um levita, quando, descendo, chegou ao lugar e o viu, passou pelo lado oposto.

[[v42-10-33]]

^<<v42-10-33,33>>^ Mas, certo samaritano, viajando pela estrada, veio encontrá-lo, e, vendo-o, teve pena.

[[v42-10-34]]

^<<v42-10-34,34>>^ De modo que se aproximou dele e lhe atou as feridas, derramando nelas azeite e vinho. Depois o pôs no seu próprio animal e o trouxe a uma hospedaria, e tomou conta dele.

[[v42-10-35]]

^<<v42-10-35,35>>^ E no dia seguinte tirou dois denários,^&#42;1^ deu-os ao hospedeiro e disse: ‘Toma conta dele, e tudo o que gastares além disso, eu te pagarei de volta ao retornar para cá.’

[NOTE]
====
. Veja Ap. 8A.
====

[[v42-10-36]]

^<<v42-10-36,36>>^ Qual destes três te parece ter-se feito próximo do homem que caiu entre os salteadores?”

[[v42-10-37]]

^<<v42-10-37,37>>^ Ele disse: “Aquele que agiu misericordiosamente para com ele.” Jesus disse-lhe então: “Vai e faze tu o mesmo.”

[[v42-10-38]]

^<<v42-10-38,38>>^ Ao prosseguirem então no caminho, ele entrou em certa aldeia. Ali, certa mulher, de nome Marta, recebeu-o como hóspede em sua casa.

[[v42-10-39]]

^<<v42-10-39,39>>^ Esta mulher tinha também uma irmã, chamada Maria, a qual, porém, se assentara aos pés do Senhor e escutava a palavra dele.

[[v42-10-40]]

^<<v42-10-40,40>>^ Marta, por outro lado, estava desatenta por cuidar de muitos deveres. Ela chegou assim perto e disse: “Senhor,^&#42;1^ não te importa que minha irmã me deixou sozinha para cuidar das coisas? Dize-lhe, portanto, que venha ajudar-me.”

[NOTE]
====
. Ou “Amo”.
====

[[v42-10-41]]

^<<v42-10-41,41>>^ Em resposta, o Senhor disse-lhe: “Marta, Marta, estás ansiosa e perturbada com muitas coisas.

[[v42-10-42]]

^<<v42-10-42,42>>^ Poucas coisas, porém, são necessárias, ou apenas uma.^&#42;1^ Maria, por sua parte, escolheu a boa porção, e esta não lhe será tirada.”

[NOTE]
====
. Segundo אcBCc; P45,75AC°WVgSyc: “Uma coisa, porém, é necessária.”
====

'''

xref:042-lucas/042-lucas-009.adoc#v42-9-0[&#60; Capítulo Anterior] | <<v42-10-0,Topo>> | xref:042-lucas/042-lucas-011.adoc#v42-11-0[Próximo Capítulo &#62;]