include::./index.adoc[]

[[v42-1-0]]
=== Lucas, 1
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v42-1-1]]

^<<v42-1-1,1>>^ Considerando que muitos empreenderam compilar uma declaração dos fatos que entre nós recebem pleno crédito,

[[v42-1-2]]

^<<v42-1-2,2>>^ assim como no-los transmitiram os que desde [o] princípio se tornaram testemunhas oculares e assistentes da mensagem,^&#42;1^

[NOTE]
====
. Lit.: “da palavra”. Gr.: tou ló·gou; J18,22: “da palavra de Jeová”.
====

[[v42-1-3]]

^<<v42-1-3,3>>^ também eu, tendo pesquisado todas as coisas com exatidão, desde o início, resolvi escrevê-las para ti em ordem lógica, excelentíssimo Teófilo,

[[v42-1-4]]

^<<v42-1-4,4>>^ para que saibas plenamente a certeza das coisas que te foram ensinadas oralmente.

[[v42-1-5]]

^<<v42-1-5,5>>^ Nos dias de Herodes, rei da Judéia, havia certo sacerdote, de nome Zacarias,^&#42;1^ da turma de Abias,^&#42;2^ e ele tinha por esposa [uma] das filhas de Arão, e o nome dela era Elisabete.

[NOTE]
====
. “Zacarias” (significando “Jah Lembrou-se”), J7-18,21,22; אAB: “Zacarias”.
. “Abias” (significando “Meu Pai É Jah”), J7-18,21,22; אAB: “Abia”.
====

[[v42-1-6]]

^<<v42-1-6,6>>^ Ambos eram justos diante de Deus por andarem inculpes de acordo com todos os mandamentos e exigências legais de Jeová.^&#42;1^

[NOTE]
====
. Veja Ap. 1D.
====

[[v42-1-7]]

^<<v42-1-7,7>>^ Mas não tinham filho, porque Elisabete era estéril e ambos já estavam bem avançados em anos.

[[v42-1-8]]

^<<v42-1-8,8>>^ Ora, atuando ele perante Deus como sacerdote na designação de sua divisão,

[[v42-1-9]]

^<<v42-1-9,9>>^ segundo a prática solene do cargo sacerdotal, chegou a sua vez para oferecer incenso ao entrar no santuário^&#42;1^ de Jeová;^&#42;2^

[NOTE]
====
. Ou “habitação (morada) divina”. Gr.: na·ón; lat.: tém·plum; J17,18,22(hebr.): heh·khál, “palácio; templo”.
. Veja Ap. 1D.
====

[[v42-1-10]]

^<<v42-1-10,10>>^ e toda a multidão do povo orava do lado de fora, na hora de se oferecer incenso.

[[v42-1-11]]

^<<v42-1-11,11>>^ Apareceu-lhe um anjo de Jeová,^&#42;1^ parado à direita do altar do incenso.

[NOTE]
====
. Veja Ap. 1D.
====

[[v42-1-12]]

^<<v42-1-12,12>>^ Zacarias, porém, ficou aflito ao vê-lo e foi tomado de temor.

[[v42-1-13]]

^<<v42-1-13,13>>^ No entanto, o anjo disse-lhe: “Não temas, Zacarias, porque a tua súplica tem sido ouvida favoravelmente, e tua esposa Elisabete tornar-se-á para ti mãe dum filho, e hás de dar-lhe o nome de João.^&#42;1^

[NOTE]
====
. Veja Mt 3:1 n.: “João”.
====

[[v42-1-14]]

^<<v42-1-14,14>>^ E terás alegria e grande regozijo, e muitos se alegrarão com o seu nascimento;

[[v42-1-15]]

^<<v42-1-15,15>>^ pois será grande diante de Jeová.^&#42;1^ Mas não deve beber nenhum vinho nem bebida forte, e será cheio de espírito^&#42;2^ santo desde a madre de sua mãe;

[NOTE]
====
. Veja Ap. 1D.
. “Espírito.” Gr.: pneú·ma·tos; lat.: Spí·ri·tu; J22(hebr.): rú·ahh.
====

[[v42-1-16]]

^<<v42-1-16,16>>^ e retornará muitos dos filhos de Israel a Jeová,^&#42;1^ seu Deus.

[NOTE]
====
. Veja Ap. 1D.
====

[[v42-1-17]]

^<<v42-1-17,17>>^ Também, irá diante dele com o espírito e o poder de Elias,^&#42;1^ para retornar os corações dos pais aos filhos e os desobedientes à sabedoria prática dos justos, a fim de aprontar para Jeová^&#42;2^ um povo preparado.”

[NOTE]
====
. Significando “Meu Deus É Jeová”. J17,18,22(hebr.): ’E·li·yá·hu.
. Veja Ap. 1D.
====

[[v42-1-18]]

^<<v42-1-18,18>>^ E Zacarias disse ao anjo: “Como hei de ter certeza disso? Pois sou idoso e minha esposa está bem avançada em anos.”

[[v42-1-19]]

^<<v42-1-19,19>>^ Em resposta, o anjo disse-lhe: “Eu sou Gabriel,^&#42;1^ que está a postos logo diante de Deus, e fui enviado para falar-te e declarar-te as boas novas^&#42;2^ destas coisas.

[NOTE]
====
. Significando “Um Vigoroso de Deus”. Gr.: Ga·bri·él; J17,18(hebr.): Ghav·ri·’él.
. Ou “declarar-te o evangelho”. Gr.: eu·ag·ge·lí·sa·sthai; lat.: e·van·ge·li·zá·re.
====

[[v42-1-20]]

^<<v42-1-20,20>>^ Mas, eis que ficarás mudo e não poderás falar até o dia em que estas coisas ocorram, porque não acreditaste nas minhas palavras, as quais se cumprirão no seu tempo designado.”

[[v42-1-21]]

^<<v42-1-21,21>>^ Entrementes, o povo continuava à espera de Zacarias; e começavam a admirar-se de sua demora no santuário.

[[v42-1-22]]

^<<v42-1-22,22>>^ Mas, quando saiu, não lhes pôde falar, e perceberam que acabara de ter uma visão sobrenatural no santuário; e fazia-lhes sinais, mas permanecia mudo.

[[v42-1-23]]

^<<v42-1-23,23>>^ Completando-se então os dias de seu serviço público,^&#42;1^ foi para casa.

[NOTE]
====
. “Serviço público.” Gr.: lei·tour·gí·as; J17,18(hebr.): ‛avo·dha·thóh, “seu serviço sagrado [como sacerdote]”. Veja He 8:6; He 9:6.
====

[[v42-1-24]]

^<<v42-1-24,24>>^ Depois destes dias, porém, Elisabete, sua esposa, ficou grávida; e ela se manteve apartada por cinco meses, dizendo:

[[v42-1-25]]

^<<v42-1-25,25>>^ “É assim que Jeová^&#42;1^ tem procedido comigo nestes dias, dando-me sua atenção para tirar o meu vitupério entre os homens.”

[NOTE]
====
. Veja Ap. 1D.
====

[[v42-1-26]]

^<<v42-1-26,26>>^ No sexto mês dela,^&#42;1^ o anjo Gabriel foi enviado da parte de Deus a uma cidade da Galiléia, de nome Nazaré,

[NOTE]
====
. Lit. só “no sexto mês”.
====

[[v42-1-27]]

^<<v42-1-27,27>>^ a uma virgem prometida em casamento a um homem de nome José, da casa de Davi; e o nome da virgem era Maria.^&#42;1^

[NOTE]
====
. Gr.: Ma·ri·ám; lat.: Ma·rí·a; J17,18,22(hebr.): Mir·yám.
====

[[v42-1-28]]

^<<v42-1-28,28>>^ E, ao se lhe apresentar, disse: “Bom dia, altamente favorecida, Jeová^&#42;1^ está contigo.”

[NOTE]
====
. Veja Ap. 1D.
====

[[v42-1-29]]

^<<v42-1-29,29>>^ Mas ela ficou profundamente perturbada com estas palavras e começou a raciocinar que sorte de cumprimento era este.

[[v42-1-30]]

^<<v42-1-30,30>>^ De modo que o anjo lhe disse: “Não temas, Maria, pois achaste favor diante de Deus;

[[v42-1-31]]

^<<v42-1-31,31>>^ e eis que conceberás na tua madre e darás à luz um filho, e deves dar-lhe o nome de Jesus.^&#42;1^

[NOTE]
====
. Veja Mt 1:21 n.
====

[[v42-1-32]]

^<<v42-1-32,32>>^ Este será grande e será chamado Filho do Altíssimo; e Jeová^&#42;1^ Deus lhe dará o trono de Davi, seu pai,

[NOTE]
====
. Veja Ap. 1D.
====

[[v42-1-33]]

^<<v42-1-33,33>>^ e ele reinará sobre a casa de Jacó para sempre, e não haverá fim do seu reino.”

[[v42-1-34]]

^<<v42-1-34,34>>^ Maria, porém, disse ao anjo: “Como se há de dar isso, visto que não tenho relações com um homem?”

[[v42-1-35]]

^<<v42-1-35,35>>^ O anjo disse-lhe, em resposta: “Espírito santo virá sobre ti e poder do Altíssimo te encobrirá. Por esta razão, também, o nascido será chamado santo, Filho de Deus.

[[v42-1-36]]

^<<v42-1-36,36>>^ E eis que a própria Elisabete, tua parenta, também concebeu um filho, na sua velhice, e este é o sexto mês para ela, a chamada estéril;

[[v42-1-37]]

^<<v42-1-37,37>>^ porque para Deus nenhuma declaração^&#42;1^ será uma impossibilidade.”

[NOTE]
====
. Ou “coisa; dito”. Gr.: rhé·ma.
====

[[v42-1-38]]

^<<v42-1-38,38>>^ Maria disse então: “Eis a escrava de Jeová!^&#42;1^ Ocorra comigo segundo a tua declaração.” Com isso, o anjo ausentou-se dela.

[NOTE]
====
. Veja Ap. 1D.
====

[[v42-1-39]]

^<<v42-1-39,39>>^ Maria levantou-se então naqueles dias e foi apressadamente à região montanhosa, a uma cidade de Judá,

[[v42-1-40]]

^<<v42-1-40,40>>^ e entrou no lar de Zacarias e cumprimentou Elisabete.

[[v42-1-41]]

^<<v42-1-41,41>>^ Pois bem, quando Elisabete ouviu o cumprimento de Maria, pulou a criança na sua madre; e Elisabete ficou cheia de espírito santo,

[[v42-1-42]]

^<<v42-1-42,42>>^ e exclamou com um alto grito e disse: “Abençoada és tu entre as mulheres e abençoado é o fruto de tua madre!

[[v42-1-43]]

^<<v42-1-43,43>>^ Como é então que tenho este [privilégio], de vir a mim a mãe de meu Senhor?

[[v42-1-44]]

^<<v42-1-44,44>>^ Pois, eis que assim que o som de teu cumprimento chegou aos meus ouvidos, a criança na minha madre pulou de regozijo.

[[v42-1-45]]

^<<v42-1-45,45>>^ Feliz também é aquela que acreditou, porque haverá uma completa realização das coisas que lhe foram faladas da parte de Jeová.”^&#42;1^

[NOTE]
====
. Veja Ap. 1D.
====

[[v42-1-46]]

^<<v42-1-46,46>>^ E Maria disse: “Minha alma magnifica^&#42;1^ a Jeová^&#42;2^

[NOTE]
====
. “Minha alma magnifica.” Lat.: Ma·gní·fi·cat á·ni·ma mé·a.
. Veja Ap. 1D.
====

[[v42-1-47]]

^<<v42-1-47,47>>^ e meu espírito não pode deixar de estar cheio de alegria por Deus, meu Salvador;

[[v42-1-48]]

^<<v42-1-48,48>>^ pois ele tem olhado para a situação humilde de sua escrava. Porque, eis que doravante todas as gerações me proclamarão feliz;

[[v42-1-49]]

^<<v42-1-49,49>>^ visto que o Poderoso tem feito grandes ações para comigo, e santo é o seu nome;

[[v42-1-50]]

^<<v42-1-50,50>>^ e sua misericórdia é de geração em geração sobre os que o temem.

[[v42-1-51]]

^<<v42-1-51,51>>^ Ele tem agido valorosamente com o seu braço, tem espalhado os que são soberbos na intenção dos seus corações.

[[v42-1-52]]

^<<v42-1-52,52>>^ Tem derrubado de tronos homens de poder e tem enaltecido humildes;

[[v42-1-53]]

^<<v42-1-53,53>>^ tem plenamente saciado os famintos com coisas boas e tem mandado embora, de mãos vazias, os que tinham riqueza.

[[v42-1-54]]

^<<v42-1-54,54>>^ Ele tem vindo em socorro de Israel, seu servo, para fazer lembrar a misericórdia,

[[v42-1-55]]

^<<v42-1-55,55>>^ assim como disse aos nossos antepassados, a Abraão e a seu descendente,^&#42;1^ para sempre.”

[NOTE]
====
. Ou “sua prole”.
====

[[v42-1-56]]

^<<v42-1-56,56>>^ Maria permaneceu então com ela cerca de três meses, e voltou para o seu próprio lar.

[[v42-1-57]]

^<<v42-1-57,57>>^ Chegou então o tempo para Elisabete dar à luz, e ela se tornou mãe dum filho.

[[v42-1-58]]

^<<v42-1-58,58>>^ E os vizinhos e os parentes dela ouviram que Jeová^&#42;1^ tinha magnificado a sua misericórdia para com ela, e começaram a alegrar-se com ela.

[NOTE]
====
. Veja Ap. 1D.
====

[[v42-1-59]]

^<<v42-1-59,59>>^ E, no oitavo dia, foram circuncidar o menino, e iam dar-lhe o nome do pai dele, Zacarias.

[[v42-1-60]]

^<<v42-1-60,60>>^ Mas a mãe dele respondeu e disse: “De modo nenhum! Mas ele se chamará João.”

[[v42-1-61]]

^<<v42-1-61,61>>^ Em vista disso disseram-lhe: “Não há nenhum entre os teus parentes que seja chamado por este nome.”

[[v42-1-62]]

^<<v42-1-62,62>>^ Foram então perguntar ao pai dele, por sinais, como queria que se chamasse.

[[v42-1-63]]

^<<v42-1-63,63>>^ E ele pediu uma tabuinha [para escrever] e escreveu: “João é o nome dele.” Todos se maravilharam em vista disso.

[[v42-1-64]]

^<<v42-1-64,64>>^ Sua boca foi instantaneamente aberta e a sua língua foi solta, e ele começou a falar, bendizendo a Deus.

[[v42-1-65]]

^<<v42-1-65,65>>^ E caiu temor sobre todos os que moravam na vizinhança deles; e falava-se sobre estas coisas em toda a região montanhosa da Judéia,

[[v42-1-66]]

^<<v42-1-66,66>>^ e todos os que [as] ouviam guardavam isso nos seus corações, dizendo: “O que será realmente deste menino?” Pois a mão de Jeová^&#42;1^ estava deveras com ele.

[NOTE]
====
. Veja Ap. 1D.
====

[[v42-1-67]]

^<<v42-1-67,67>>^ E Zacarias, seu pai, ficou cheio de espírito santo e profetizou, dizendo:

[[v42-1-68]]

^<<v42-1-68,68>>^ “Bendito seja Jeová,^&#42;1^ o Deus de Israel, porque voltou a sua atenção e realizou livramento para com seu povo.

[NOTE]
====
. Veja Ap. 1D.
====

[[v42-1-69]]

^<<v42-1-69,69>>^ E ele nos suscitou um chifre de salvação^&#42;1^ na casa de Davi, seu servo,

[NOTE]
====
. “Chifre de salvação.” Ou “um poderoso salvador”. Gr.: ké·ras so·te·rí·as; lat.: cór·nu sa·lú·tis; J17,18,22(hebr.): qé·ren yeshu·‛áh.
====

[[v42-1-70]]

^<<v42-1-70,70>>^ assim como ele, pela boca de seus santos profetas da antiguidade, tem falado

[[v42-1-71]]

^<<v42-1-71,71>>^ duma salvação [nossa] dos nossos inimigos e da mão de todos os que nos odeiam;

[[v42-1-72]]

^<<v42-1-72,72>>^ para realizar a misericórdia em conexão com os nossos antepassados e para fazer lembrar o seu santo pacto,

[[v42-1-73]]

^<<v42-1-73,73>>^ o juramento que fez a Abraão, nosso antepassado,

[[v42-1-74]]

^<<v42-1-74,74>>^ de nos conceder, depois de termos sido resgatados das mãos dos inimigos, o privilégio de lhe prestarmos destemidamente serviço sagrado,^&#42;1^

[NOTE]
====
. Ou “prestarmos . . . adoração”. Gr.: la·treú·ein; J17,18,22(hebr.): le‛ov·dhóh, “o servirmos (adorarmos)”. Veja Êx 3:12 n.
====

[[v42-1-75]]

^<<v42-1-75,75>>^ com lealdade e justiça, diante dele, todos os nossos dias.

[[v42-1-76]]

^<<v42-1-76,76>>^ Mas, quanto a ti, menino, serás chamado profeta do Altíssimo, pois irás de antemão na frente de Jeová^&#42;1^ para aprontar os seus caminhos,

[NOTE]
====
. Veja Ap. 1D.
====

[[v42-1-77]]

^<<v42-1-77,77>>^ para dar ao seu povo conhecimento da salvação por meio do perdão dos seus pecados,

[[v42-1-78]]

^<<v42-1-78,78>>^ por causa da terna compaixão de nosso Deus. Com esta [compaixão] nos visitará do alto uma alvorada,

[[v42-1-79]]

^<<v42-1-79,79>>^ para dar luz aos sentados na escuridão e na sombra da morte, para dirigir os nossos pés prosperamente no caminho da paz.”

[[v42-1-80]]

^<<v42-1-80,80>>^ E a criancinha crescia e se tornava forte em espírito, e continuava nos desertos, até o dia em que se mostrou abertamente a Israel.

'''

xref:041-marcos/041-marcos-016.adoc#v41-16-0[&#60; Capítulo Anterior] | <<v42-1-0,Topo>> | xref:042-lucas/042-lucas-002.adoc#v42-2-0[Próximo Capítulo &#62;]