include::./index.adoc[]

[[v42-3-0]]
=== Lucas, 3
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v42-3-1]]

^<<v42-3-1,1>>^ No décimo quinto ano do reinado de Tibério César,^&#42;1^ quando Pôncio Pilatos era governador da Judéia e Herodes^&#42;2^ era governante distrital^&#42;3^ da Galiléia, mas Filipe, seu irmão, era governante distrital do país da Ituréia e de Traconítis, e Lisânias era governante distrital de Abilene,

[NOTE]
====
. Ou “o imperador”. Gr.: Kaí·sa·ros; lat.: Caé·sa·ris.
. Isto é, Herodes Ântipas, filho de Herodes, o Grande.
. “Governante distrital.” Lit.: “tetrarca”; príncipe territorial agindo pelo imperador romano. Lat.: te·trár·cha.
====

[[v42-3-2]]

^<<v42-3-2,2>>^ nos dias do principal sacerdote Anás e de Caifás, veio a declaração de Deus a João, filho de Zacarias, no ermo.

[[v42-3-3]]

^<<v42-3-3,3>>^ Ele percorreu assim toda a região em volta do Jordão, pregando [o] batismo [em símbolo] de arrependimento para o perdão de pecados,

[[v42-3-4]]

^<<v42-3-4,4>>^ assim como está escrito no livro das palavras de Isaías, o profeta: “Escutai! Alguém está clamando no ermo: ‘Preparai o caminho de Jeová,^&#42;1^ fazei retas as suas estradas.

[NOTE]
====
. Veja Ap. 1D.
====

[[v42-3-5]]

^<<v42-3-5,5>>^ Cada vala tem de ser enchida e cada monte e colina [têm de ser] nivelados, e as curvas têm de tornar-se caminhos retos, e os lugares escabrosos, caminhos planos;

[[v42-3-6]]

^<<v42-3-6,6>>^ e toda a carne verá o meio salvador de Deus.’”

[[v42-3-7]]

^<<v42-3-7,7>>^ Portanto, começou a dizer às multidões que vinham para ser batizadas por ele: “Descendência de víboras, quem vos insinuou fugir do vindouro furor?

[[v42-3-8]]

^<<v42-3-8,8>>^ Produzi, pois, frutos próprios do arrependimento.^&#42;1^ E não principieis a dizer no vosso íntimo: ‘Temos por pai a Abraão.’ Pois eu vos digo que Deus tem poder para suscitar destas pedras filhos a Abraão.

[NOTE]
====
. Lit.: “da mudança de idéia”. Gr.: me·ta·noí·as.
====

[[v42-3-9]]

^<<v42-3-9,9>>^ Deveras, o machado já está em posição na raiz das árvores; toda árvore, pois, que não produzir fruto excelente, há de ser cortada e lançada no fogo.”

[[v42-3-10]]

^<<v42-3-10,10>>^ E as multidões perguntavam-lhe: “Que devemos fazer, então?”

[[v42-3-11]]

^<<v42-3-11,11>>^ Em resposta, ele lhes dizia: “Aquele que tiver duas peças de roupa interior partilhe com aquele que não tiver nenhuma, e aquele que tiver coisas para comer, faça o mesmo.”

[[v42-3-12]]

^<<v42-3-12,12>>^ Vinham, porém, até mesmo cobradores de impostos para ser batizados, e disseram-lhe: “Instrutor, que devemos fazer?”

[[v42-3-13]]

^<<v42-3-13,13>>^ Ele lhes disse: “Não reclameis mais do que a taxa do imposto.”

[[v42-3-14]]

^<<v42-3-14,14>>^ Também os em serviço militar perguntavam-lhe: “Também nós, que devemos fazer?” E ele lhes disse: “Não hostilizeis a ninguém e não acuseis a ninguém falsamente, mas contentai-vos com o vosso soldo.”^&#42;1^

[NOTE]
====
. Ou “salário”. Lat.: sti·pén·di·is.
====

[[v42-3-15]]

^<<v42-3-15,15>>^ Ora, visto que o povo estava em expectativa e todos raciocinavam nos seus corações a respeito de João: “Será este o Cristo?”

[[v42-3-16]]

^<<v42-3-16,16>>^ João deu a resposta, dizendo a todos: “Eu, da minha parte, batizo-vos com água; mas vem aquele que é mais forte do que eu, não sendo eu nem apto para desatar-lhe o cordão de suas sandálias. Ele vos batizará com espírito santo e com fogo.

[[v42-3-17]]

^<<v42-3-17,17>>^ Tem na mão a sua pá de joeirar para limpar completamente a sua eira e para ajuntar o trigo no seu celeiro, mas a palha ele queimará em fogo inextinguível.”

[[v42-3-18]]

^<<v42-3-18,18>>^ Dava assim também muitas outras exortações e declarava as boas novas ao povo.

[[v42-3-19]]

^<<v42-3-19,19>>^ Mas Herodes, o governante distrital,^&#42;1^ por ter sido repreendido por ele com respeito a Herodias, esposa de seu irmão, e com respeito a todas as ações iníquas que Herodes havia feito,

[NOTE]
====
. Veja v. 1 n.: “distrital”.
====

[[v42-3-20]]

^<<v42-3-20,20>>^ acrescentou também a seguinte a todas essas [ações]: encerrou João na prisão.

[[v42-3-21]]

^<<v42-3-21,21>>^ Então, quando todo o povo fora batizado, Jesus também foi batizado,^&#42;1^ e, enquanto orava, abriu-se o céu

[NOTE]
====
. Ou “foi imerso; foi submerso (mergulhado)”. Gr.: ba·pti·sthén·tos.
====

[[v42-3-22]]

^<<v42-3-22,22>>^ e desceu sobre ele o espírito santo, em forma corpórea, semelhante a uma pomba, e uma voz saiu do céu: “Tu és meu Filho, o amado; eu te tenho aprovado.”

[[v42-3-23]]

^<<v42-3-23,23>>^ Outrossim, o próprio Jesus, ao principiar [a sua obra],^&#42;1^ tinha cerca de trinta anos de idade, sendo, como era a opinião,^&#42;2^ filho
de José,
[filho] de Eli,

[NOTE]
====
. Ou “principiar [a ensinar]”.
. Ou “conforme determinado por lei”.
====

[[v42-3-24]]

^<<v42-3-24,24>>^ [filho] de Matate,
[filho] de Levi,
[filho] de Melqui,
[filho] de Janai,
[filho] de José,

[[v42-3-25]]

^<<v42-3-25,25>>^ [filho] de Matatias,
[filho] de Amós,
[filho] de Naum,
[filho] de Esli,
[filho] de Nagai,

[[v42-3-26]]

^<<v42-3-26,26>>^ [filho] de Maate,
[filho] de Matatias,
[filho] de Semei,
[filho] de Joseque,
[filho] de Jodá,

[[v42-3-27]]

^<<v42-3-27,27>>^ [filho] de Joanã,
[filho] de Resa,
[filho] de Zorobabel,
[filho] de Sealtiel,^&#42;1^
[filho] de Néri,

[NOTE]
====
. Lit.: “Salatiel”.
====

[[v42-3-28]]

^<<v42-3-28,28>>^ [filho] de Melqui,
[filho] de Adi,
[filho] de Cosã,
[filho] de Elmadã,
[filho] de Er,

[[v42-3-29]]

^<<v42-3-29,29>>^ [filho] de Jesus,^&#42;1^
[filho] de Eliézer,
[filho] de Jorim,
[filho] de Matate,
[filho] de Levi,

[NOTE]
====
. “Jesus”, אABVgSysJ18,22; SypJ17,21: “José(s)”.
====

[[v42-3-30]]

^<<v42-3-30,30>>^ [filho] de Simeão,
[filho] de Judas,
[filho] de José,
[filho] de Jonã,
[filho] de Eliaquim,

[[v42-3-31]]

^<<v42-3-31,31>>^ [filho] de Meleá,
[filho] de Mena,
[filho] de Matatá,
[filho] de Natã,
[filho] de Davi,

[[v42-3-32]]

^<<v42-3-32,32>>^ [filho] de Jessé,
[filho] de Obede,^&#42;1^
[filho] de Boaz,
[filho] de Salmom,^&#42;2^
[filho] de Nasom,

[NOTE]
====
. “Jobel”, א°BSys.
. “Sala”, א°BSys.
====

[[v42-3-33]]

^<<v42-3-33,33>>^ [filho] de Aminadabe,^&#42;1^
[filho] de Arni,^&#42;2^
[filho] de Esrom,
[filho] de Peres,
[filho] de Judá,

[NOTE]
====
. “Aminadabe”, AVgSyp; B: “Admein”.
. “Arã”, ADVgSyp. Ou “Rão”. Veja 1Cr 2:9; Mt 1:3, 4.
====

[[v42-3-34]]

^<<v42-3-34,34>>^ [filho] de Jacó,
[filho] de Isaque,
[filho] de Abraão,
[filho] de Tera,
[filho] de Naor,

[[v42-3-35]]

^<<v42-3-35,35>>^ [filho] de Serugue,
[filho] de Reú,
[filho] de Pelegue,
[filho] de Éber,
[filho] de Selá,

[[v42-3-36]]

^<<v42-3-36,36>>^ [filho] de Cainã,^&#42;1^
[filho] de Arfaxade,
[filho] de Sem,
[filho] de Noé,
[filho] de Lameque,

[NOTE]
====
. P75D omitem “filho de Cainã”, em harmonia com Gên 10:24; Gên 11:12, 15; 1Cr 1:18.
====

[[v42-3-37]]

^<<v42-3-37,37>>^ [filho] de Metusalém,
[filho] de Enoque,
[filho] de Jarede,
[filho] de Malaleel,
[filho] de Cainã,

[[v42-3-38]]

^<<v42-3-38,38>>^ [filho] de Enos,
[filho] de Sete,
[filho] de Adão,
[filho] de Deus.

'''

xref:042-lucas/042-lucas-002.adoc#v42-2-0[&#60; Capítulo Anterior] | <<v42-3-0,Topo>> | xref:042-lucas/042-lucas-004.adoc#v42-4-0[Próximo Capítulo &#62;]