include::./index.adoc[]

[[v42-11-0]]
=== Lucas, 11
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v42-11-1]]

^<<v42-11-1,1>>^ Então, na ocasião em que estava em certo lugar orando, quando parou, disse-lhe certo dos seus discípulos: “Senhor, ensina-nos a orar, assim como também João ensinou aos seus discípulos.”

[[v42-11-2]]

^<<v42-11-2,2>>^ Ele lhes disse então: “Sempre que orardes, dizei: ‘Pai, santificado seja^&#42;1^ o teu nome. Venha o teu reino.

[NOTE]
====
. Ou “seja tido por sagrado; seja tratado como santo”. Gr.: ha·gi·a·sthé·to; lat.: sanc·ti·fi·cé·tur; J17,18(hebr.): yith·qad·dásh.
====

[[v42-11-3]]

^<<v42-11-3,3>>^ Dá-nos o nosso pão para o dia, segundo as exigências do dia.

[[v42-11-4]]

^<<v42-11-4,4>>^ E perdoa-nos os nossos pecados, pois nós mesmos também perdoamos a todo aquele que está em dívida conosco; e não nos leves à tentação.’”

[[v42-11-5]]

^<<v42-11-5,5>>^ Ainda mais, disse-lhes: “Quem de vós terá um amigo e irá a ele à meia-noite, e lhe dirá: ‘Amigo, empresta-me três pães,

[[v42-11-6]]

^<<v42-11-6,6>>^ porque um amigo meu acaba de chegar a mim duma viagem e eu não tenho nada para pôr diante dele’?

[[v42-11-7]]

^<<v42-11-7,7>>^ E aquele diz lá de dentro, em resposta: ‘Deixa de incomodar-me. A porta já está fechada à chave e meus filhinhos estão comigo na cama; não posso levantar-me e dar-te algo.’

[[v42-11-8]]

^<<v42-11-8,8>>^ Eu vos digo: Embora não se levante e não lhe dê nada por ser seu amigo, certamente por causa da persistência ousada deste ele se levantará e lhe dará as coisas que necessita.

[[v42-11-9]]

^<<v42-11-9,9>>^ Concordemente, eu vos digo: Persisti em pedir, e dar-se-vos-á; persisti em buscar, e achareis; persisti em bater, e abrir-se-vos-á.

[[v42-11-10]]

^<<v42-11-10,10>>^ Pois, todo o que [persistir em] pedir, receberá, e todo o que [persistir em] buscar, achará, e a todo o que [persistir em] bater, abrir-se-á.

[[v42-11-11]]

^<<v42-11-11,11>>^ Deveras, qual é o pai entre vós que, se o seu filho lhe pedir um peixe, lhe entregará uma serpente em vez de um peixe?

[[v42-11-12]]

^<<v42-11-12,12>>^ Ou, se lhe pedir um ovo, lhe entregará um escorpião?

[[v42-11-13]]

^<<v42-11-13,13>>^ Portanto, se vós, embora iníquos, sabeis dar boas dádivas a vossos filhos, quanto mais o Pai, no céu, dará espírito santo aos que lhe pedirem!”

[[v42-11-14]]

^<<v42-11-14,14>>^ Mais tarde expulsou um demônio mudo. Depois de o demônio sair, o mudo falou. E as multidões maravilhavam-se.

[[v42-11-15]]

^<<v42-11-15,15>>^ Mas, certos deles disseram: “Ele expulsa os demônios por meio de Belzebu,^&#42;1^ o governante dos demônios.”

[NOTE]
====
. “Belzebu”, VgSyc,p,s; P45,75ACDW(gr.): Be·el·ze·boúl; אB(gr.): Be·e·ze·boúl. Veja Mt 12:24 n.
====

[[v42-11-16]]

^<<v42-11-16,16>>^ No entanto, outros, para tentá-lo, começaram a buscar dele um sinal do céu.

[[v42-11-17]]

^<<v42-11-17,17>>^ Conhecendo as suas imaginações, disse-lhes: “Todo reino dividido contra si mesmo cai em desolação, e a casa [dividida] contra si mesma cai.

[[v42-11-18]]

^<<v42-11-18,18>>^ Portanto, se Satanás também está dividido contra si mesmo, então, como ficará de pé o seu reino? Porque vós dizeis que eu expulso os demônios por meio de Belzebu.

[[v42-11-19]]

^<<v42-11-19,19>>^ Se é por meio de Belzebu que eu expulso os demônios, por meio de quem os expulsam os vossos filhos? Por causa disso, serão juízes de vós.

[[v42-11-20]]

^<<v42-11-20,20>>^ Mas, se é por meio do dedo de Deus que eu expulso os demônios, o reino de Deus realmente vos sobreveio.

[[v42-11-21]]

^<<v42-11-21,21>>^ Quando um homem forte, bem armado, guarda o seu palácio, seus bens continuam em paz.

[[v42-11-22]]

^<<v42-11-22,22>>^ Mas, quando alguém mais forte do que ele vem contra ele e o vence, tira-lhe todo o seu armamento em que confiava e reparte as coisas das quais o despojou.

[[v42-11-23]]

^<<v42-11-23,23>>^ Quem não está do meu lado é contra mim, e quem comigo não ajunta, espalha.

[[v42-11-24]]

^<<v42-11-24,24>>^ “Quando um espírito impuro sai dum homem, passa por lugares áridos em busca dum lugar de descanso, e, não achando nenhum, diz: ‘Voltarei para a minha casa da qual me mudei.’

[[v42-11-25]]

^<<v42-11-25,25>>^ E, chegando, acha-a varrida^&#42;1^ e adornada.

[NOTE]
====
. “Varrida”, אAD; B: “desocupada, varrida”.
====

[[v42-11-26]]

^<<v42-11-26,26>>^ Então vai e toma consigo sete espíritos diferentes,^&#42;1^ mais iníquos do que ele mesmo, e, entrando, ficam morando ali; e as condições finais desse homem tornam-se piores do que a primeira.”

[NOTE]
====
. Ou “outros”.
====

[[v42-11-27]]

^<<v42-11-27,27>>^ Ora, dizendo ele estas coisas, certa mulher, dentre a multidão, levantou a sua voz e disse-lhe: “Feliz é a madre que te carregou e os peitos em que mamaste!”

[[v42-11-28]]

^<<v42-11-28,28>>^ Mas ele disse: “Não, antes: Felizes são os que ouvem a palavra de Deus e a guardam!”

[[v42-11-29]]

^<<v42-11-29,29>>^ Quando as multidões se apinhavam, principiou a dizer: “Esta geração é uma geração iníqua; procura um sinal. Mas nenhum sinal lhe será dado, exceto o sinal de Jonas.

[[v42-11-30]]

^<<v42-11-30,30>>^ Porque, assim como Jonas se tornou um sinal para os ninivitas, do mesmo modo o será também o Filho do homem para esta geração.

[[v42-11-31]]

^<<v42-11-31,31>>^ A rainha do sul será levantada no julgamento com os homens desta geração e os condenará; porque ela veio dos confins^&#42;1^ da terra para ouvir a sabedoria de Salomão, mas, eis que algo mais do que Salomão está aqui.

[NOTE]
====
. Veja Mt 12:42 n.
====

[[v42-11-32]]

^<<v42-11-32,32>>^ Os homens de Nínive se levantarão no julgamento com esta geração e a condenarão; porque eles se arrependeram com o que Jonas pregou; mas, eis que algo mais do que Jonas está aqui.

[[v42-11-33]]

^<<v42-11-33,33>>^ Não se põe uma lâmpada, depois de acesa, num lugar oculto, nem debaixo dum cesto de medida, mas no velador, para que os que entram possam observar a luz.

[[v42-11-34]]

^<<v42-11-34,34>>^ A lâmpada do corpo é o teu olho. Quando o teu olho é singelo,^&#42;1^ todo o teu corpo também é luminoso; mas, quando é iníquo,^&#42;2^ teu corpo também é escuro.

[NOTE]
====
. Ou “sincero; unidirecional; em foco; generoso”.
. Ou “mau; invejoso”.
====

[[v42-11-35]]

^<<v42-11-35,35>>^ Está alerta, pois. Talvez a luz que há em ti seja escuridão.

[[v42-11-36]]

^<<v42-11-36,36>>^ Portanto, se todo o teu corpo for luminoso, sem nenhuma parte escura, todo ele será tão luminoso como uma lâmpada que te dá luz pelos seus raios.”

[[v42-11-37]]

^<<v42-11-37,37>>^ Tendo falado isso, certo fariseu pediu-lhe que almoçasse com ele. De modo que entrou e se recostou à mesa.

[[v42-11-38]]

^<<v42-11-38,38>>^ No entanto, o fariseu ficou surpreso quando viu que não se lavou primeiro^&#42;1^ antes do almoço.

[NOTE]
====
. Lit.: “não foi primeiro submerso (batizado)”.
====

[[v42-11-39]]

^<<v42-11-39,39>>^ Mas o Senhor disse-lhe: “Ora, vós fariseus limpais por fora o copo e o prato, mas por dentro estais cheios de saque e de iniqüidade.

[[v42-11-40]]

^<<v42-11-40,40>>^ Desarrazoados! Quem fez o exterior também fez o interior, não fez?

[[v42-11-41]]

^<<v42-11-41,41>>^ Não obstante, dai como dádivas de misericórdia as coisas que estão no íntimo, e, eis que todas as [outras] coisas acerca de vós^&#42;1^ serão limpas.

[NOTE]
====
. Ou “para vós”.
====

[[v42-11-42]]

^<<v42-11-42,42>>^ Mas, ai de vós, fariseus, porque dais o décimo da hortelã, e da arruda, e de todas as [outras] hortaliças, mas deixais de lado a justiça^&#42;1^ e o amor de Deus! Estas coisas tínheis a obrigação de fazer, mas sem omitir aquelas outras.

[NOTE]
====
. Ou “o julgamento”. Gr.: ten krí·sin; lat.: iu·dí·ci·um; J17,18,22(hebr.): ham·mish·pát.
====

[[v42-11-43]]

^<<v42-11-43,43>>^ Ai de vós, fariseus, porque amais os primeiros lugares nas sinagogas e os cumprimentos nas feiras!^&#42;1^

[NOTE]
====
. Ou “lugares de reunião”. Gr.: a·go·raís.
====

[[v42-11-44]]

^<<v42-11-44,44>>^ Ai de vós, porque sois como aqueles túmulos memoriais que não estão em evidência, de modo que os homens andam sobre eles e não [o] sabem!”

[[v42-11-45]]

^<<v42-11-45,45>>^ Em resposta, certo dos versados na Lei disse-lhe: “Instrutor, dizendo estas coisas também insultas a nós.”

[[v42-11-46]]

^<<v42-11-46,46>>^ Ele disse então: “Também ai de vós, versados na Lei, porque carregais os homens de cargas difíceis de levar, mas vós mesmos não tocais nas cargas nem com um dos vossos dedos!

[[v42-11-47]]

^<<v42-11-47,47>>^ “Ai de vós, porque construís os túmulos memoriais dos profetas, mas os vossos antepassados os mataram!

[[v42-11-48]]

^<<v42-11-48,48>>^ Vós, certamente, sois testemunhas das ações de vossos antepassados, contudo, consentis nelas, porque estes mataram os profetas,^&#42;1^ mas vós construís [os seus túmulos].

[NOTE]
====
. Lit.: “os mataram”.
====

[[v42-11-49]]

^<<v42-11-49,49>>^ Por esta razão, a sabedoria de Deus também disse: ‘Eu lhes enviarei profetas e apóstolos, e eles matarão e perseguirão a alguns deles,

[[v42-11-50]]

^<<v42-11-50,50>>^ para que o sangue de todos os profetas, derramado desde a fundação^&#42;1^ do mundo, seja exigido desta geração,

[NOTE]
====
. Lit.: “o lançamento para baixo [de semente]”. Gr.: ka·ta·bo·lés.
====

[[v42-11-51]]

^<<v42-11-51,51>>^ desde o sangue de Abel até o sangue de Zacarias, que foi morto entre o altar e a casa.’ Sim, eu vos digo, será exigido desta geração.

[[v42-11-52]]

^<<v42-11-52,52>>^ “Ai de vós, versados na Lei, porque tirastes a chave do conhecimento; vós mesmos não entrastes e impedistes os que estavam entrando!”

[[v42-11-53]]

^<<v42-11-53,53>>^ Assim, ao sair dali, os escribas e os fariseus principiaram a apertá-lo terrivelmente e a assediá-lo com perguntas sobre coisas adicionais,

[[v42-11-54]]

^<<v42-11-54,54>>^ armando-lhe ciladas para apanhar algo de sua boca.

'''

xref:042-lucas/042-lucas-010.adoc#v42-10-0[&#60; Capítulo Anterior] | <<v42-11-0,Topo>> | xref:042-lucas/042-lucas-012.adoc#v42-12-0[Próximo Capítulo &#62;]