include::./index.adoc[]

[[v42-18-0]]
=== Lucas, 18
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v42-18-1]]

^<<v42-18-1,1>>^ Depois prosseguiu a contar-lhes uma ilustração a respeito da necessidade de sempre orarem e de nunca desistirem,

[[v42-18-2]]

^<<v42-18-2,2>>^ dizendo: “Em certa cidade havia certo juiz que não temia a Deus e não respeitava homem.

[[v42-18-3]]

^<<v42-18-3,3>>^ Mas, havia naquela cidade uma viúva, e ela persistia em ir ter com ele, dizendo: ‘Cuida de que eu obtenha justiça do meu adversário em juízo.’

[[v42-18-4]]

^<<v42-18-4,4>>^ Pois bem, por um tempo ele não estava disposto, mas depois disse para si mesmo: ‘Embora eu não tema a Deus nem respeite o homem,

[[v42-18-5]]

^<<v42-18-5,5>>^ de qualquer modo, visto que esta viúva me causa continuamente contrariedade, cuidarei de que ela obtenha justiça, para que não persista em vir e em amofinar-me^&#42;1^ até o fim.’”

[NOTE]
====
. Ou “intimidar-me”. Provém duma palavra que significa “socar sob o olho”.
====

[[v42-18-6]]

^<<v42-18-6,6>>^ O Senhor disse então: “Ouvi o que disse o juiz, embora injusto!

[[v42-18-7]]

^<<v42-18-7,7>>^ Certamente, então, não causará Deus que se faça justiça aos seus escolhidos que clamam a ele dia e noite, embora seja longânime para com eles?

[[v42-18-8]]

^<<v42-18-8,8>>^ Eu vos digo: Ele causará que se lhes faça velozmente justiça. Não obstante, quando chegar o Filho do homem, achará realmente fé^&#42;1^ na terra?”

[NOTE]
====
. Ou “achará . . . tal fé”.
====

[[v42-18-9]]

^<<v42-18-9,9>>^ Mas, ele contou a seguinte ilustração também a alguns que confiavam em si mesmos como sendo justos e que consideravam os demais como nada:

[[v42-18-10]]

^<<v42-18-10,10>>^ “Dois homens subiram ao templo para orar, um sendo fariseu e o outro cobrador de impostos.

[[v42-18-11]]

^<<v42-18-11,11>>^ O fariseu estava em pé e começou a orar as seguintes coisas no seu íntimo: ‘Ó Deus, agradeço-te que não sou como o resto dos homens, extorsores, injustos, adúlteros, ou mesmo como este cobrador de impostos.

[[v42-18-12]]

^<<v42-18-12,12>>^ Jejuo duas vezes por semana, dou o décimo de todas as coisas que adquiro.’

[[v42-18-13]]

^<<v42-18-13,13>>^ O cobrador de impostos, porém, estando em pé à distância, não estava nem disposto a levantar os olhos para o céu, mas batia no peito, dizendo: ‘Ó Deus, sê clemente para comigo pecador.’

[[v42-18-14]]

^<<v42-18-14,14>>^ Digo-vos: Este homem desceu para sua casa provado mais justo do que aquele homem; porque todo o que se enaltecer será humilhado, mas quem se humilhar será enaltecido.”

[[v42-18-15]]

^<<v42-18-15,15>>^ As pessoas começaram então a trazer-lhe também suas crianças,^&#42;1^ para que as tocasse; mas, vendo isso os discípulos, começaram a adverti-las.

[NOTE]
====
. Ou “seus filhos”.
====

[[v42-18-16]]

^<<v42-18-16,16>>^ No entanto, Jesus chamou a si as [crianças], dizendo: “Deixai vir a mim as criancinhas e não tenteis impedi-las. Pois o reino de Deus pertence a tais.

[[v42-18-17]]

^<<v42-18-17,17>>^ Deveras, eu vos digo: Quem não receber o reino de Deus como uma criancinha, de modo algum entrará nele.”

[[v42-18-18]]

^<<v42-18-18,18>>^ E certo governante interrogou-o, dizendo: “Bom Instrutor, por fazer o que hei de herdar a vida eterna?”

[[v42-18-19]]

^<<v42-18-19,19>>^ Jesus disse-lhe: “Por que me chamas de bom? Ninguém é bom, a não ser um só, Deus.

[[v42-18-20]]

^<<v42-18-20,20>>^ Sabes os mandamentos: ‘Não cometas adultério, não assassines, não furtes, não dês falso testemunho, honra a teu pai e a tua mãe.’”

[[v42-18-21]]

^<<v42-18-21,21>>^ Ele disse então: “Tenho guardado a todos estes desde a mocidade.”

[[v42-18-22]]

^<<v42-18-22,22>>^ Ouvindo isso, Jesus disse-lhe: “Há ainda uma coisa que falta a respeito de ti: Vende todas as coisas que tens e distribui aos pobres, e terás um tesouro nos céus; e vem ser meu seguidor.”

[[v42-18-23]]

^<<v42-18-23,23>>^ Ouvindo isso, ele ficou profundamente contristado, pois era muito rico.

[[v42-18-24]]

^<<v42-18-24,24>>^ Jesus olhou para ele e disse: “Quão difícil será para os que têm dinheiro abrirem caminho para entrar no reino de Deus!

[[v42-18-25]]

^<<v42-18-25,25>>^ De fato, é mais fácil para um camelo passar pelo orifício duma agulha de costura, do que para um rico entrar no reino de Deus.”

[[v42-18-26]]

^<<v42-18-26,26>>^ Os que ouviram isso disseram: “Quem é que é capaz de ser salvo?”

[[v42-18-27]]

^<<v42-18-27,27>>^ Ele disse: “As coisas impossíveis aos homens são possíveis a Deus.”

[[v42-18-28]]

^<<v42-18-28,28>>^ Mas Pedro disse: “Eis que abandonamos as nossas próprias coisas e te seguimos.”

[[v42-18-29]]

^<<v42-18-29,29>>^ Ele lhes disse: “Deveras, eu vos digo: Não há ninguém que tenha abandonado casa, ou esposa, ou irmãos, ou pais ou filhos, pela causa do reino de Deus,

[[v42-18-30]]

^<<v42-18-30,30>>^ que não receba de algum modo muitas vezes mais neste período de tempo, e no vindouro sistema de coisas^&#42;1^ a vida eterna.”

[NOTE]
====
. Ou “ordem de coisas”. Gr.: ai·ó·ni; lat.: saé·cu·lo; J22(hebr.): ba·‛oh·lám, “na ordem de coisas”.
====

[[v42-18-31]]

^<<v42-18-31,31>>^ Então tomou os doze à parte e disse-lhes: “Eis que estamos subindo para Jerusalém e completar-se-ão todas as coisas escritas por meio dos profetas quanto ao Filho do homem.

[[v42-18-32]]

^<<v42-18-32,32>>^ Por exemplo, ele será entregue a [homens das] nações e divertir-se-ão às custas dele, e será tratado com insolência e cuspirão nele;

[[v42-18-33]]

^<<v42-18-33,33>>^ e, depois de o açoitarem, matá-lo-ão, mas no terceiro dia ele será levantado.”

[[v42-18-34]]

^<<v42-18-34,34>>^ No entanto, não compreenderam o significado de nenhuma destas coisas; mas esta pronunciação lhes era escondida, e não sabiam as coisas faladas.

[[v42-18-35]]

^<<v42-18-35,35>>^ Chegando ele então perto de Jericó, havia certo cego sentado à beira da estrada, mendigando.

[[v42-18-36]]

^<<v42-18-36,36>>^ Visto que ouvia uma multidão passar por ali, começou a indagar de que se tratava.

[[v42-18-37]]

^<<v42-18-37,37>>^ Relataram-lhe: “Jesus, o nazareno, está passando por aqui!”

[[v42-18-38]]

^<<v42-18-38,38>>^ Em vista disso, clamou, dizendo: “Jesus, Filho de Davi, tem misericórdia de mim!”

[[v42-18-39]]

^<<v42-18-39,39>>^ E os que iam na frente começaram a dizer-lhe severamente que ficasse calado, mas ele gritava tanto mais: “Filho de Davi, tem misericórdia de mim.”

[[v42-18-40]]

^<<v42-18-40,40>>^ Jesus parou então e ordenou que [o homem] fosse levado a ele. Tendo-se este aproximado, [Jesus]^&#42;1^ perguntou-lhe:

[NOTE]
====
. Lit.: “ele”.
====

[[v42-18-41]]

^<<v42-18-41,41>>^ “Que queres que eu faça para ti?” Ele disse: “Senhor,^&#42;1^ deixa-me recuperar a vista.”

[NOTE]
====
. Ou “Amo”.
====

[[v42-18-42]]

^<<v42-18-42,42>>^ De modo que Jesus lhe disse: “Recupera a tua vista; tua fé te fez ficar bom.”^&#42;1^

[NOTE]
====
. Ou “te salvou”.
====

[[v42-18-43]]

^<<v42-18-43,43>>^ E ele recuperou instantaneamente a vista e começou a segui-lo, glorificando a Deus. Também todo o povo, vendo [isso], deu louvor a Deus.

'''

xref:042-lucas/042-lucas-017.adoc#v42-17-0[&#60; Capítulo Anterior] | <<v42-18-0,Topo>> | xref:042-lucas/042-lucas-019.adoc#v42-19-0[Próximo Capítulo &#62;]