include::./index.adoc[]

[[v42-13-0]]
=== Lucas, 13
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v42-13-1]]

^<<v42-13-1,1>>^ Naquela mesma época, estavam ali presentes certos que lhe relataram o caso dos galileus, cujo sangue Pilatos misturara com os sacrifícios deles.

[[v42-13-2]]

^<<v42-13-2,2>>^ Ele lhes disse, assim, em resposta: “Imaginais que esses galileus se mostraram piores pecadores do que todos os outros galileus, porque sofreram tais coisas?

[[v42-13-3]]

^<<v42-13-3,3>>^ Deveras, eu vos digo que não; mas, a menos que vos arrependais, sereis todos igualmente destruídos.

[[v42-13-4]]

^<<v42-13-4,4>>^ Ou aqueles dezoito, sobre os quais caiu a torre de Siloé,^&#42;1^ matando-os, imaginais que eles se mostraram maiores devedores do que todos os outros homens que habitam em Jerusalém?

[NOTE]
====
. “Siloé”, אAB; J17,18,22: “Siloá”.
====

[[v42-13-5]]

^<<v42-13-5,5>>^ Deveras, eu vos digo que não; mas, a menos que vos arrependais, sereis todos destruídos da mesma maneira.”

[[v42-13-6]]

^<<v42-13-6,6>>^ Prosseguiu então, contando a seguinte ilustração: “Certo homem plantara uma figueira no seu vinhedo e veio procurar fruto nela, mas não achou nenhum.

[[v42-13-7]]

^<<v42-13-7,7>>^ Ele disse então ao vinhateiro: ‘Já faz agora três anos que venho procurar fruto nesta figueira, mas não achei nenhum. Corta-a! Realmente, por que devia ela manter o solo inútil?’

[[v42-13-8]]

^<<v42-13-8,8>>^ Em resposta, este lhe disse: ‘Amo, deixa-a também este ano, até que eu cave em volta dela e lhe ponha estrume;

[[v42-13-9]]

^<<v42-13-9,9>>^ e, se então produzir fruto no futuro, [muito bem]; mas, se não, hás^&#42;1^ de cortá-la.’”

[NOTE]
====
. Ou “tens”.
====

[[v42-13-10]]

^<<v42-13-10,10>>^ Ele estava então ensinando numa das sinagogas, no sábado.

[[v42-13-11]]

^<<v42-13-11,11>>^ E eis uma mulher com um espírito de fraqueza, já por dezoito anos, e ela estava encurvada e não podia absolutamente endireitar-se.

[[v42-13-12]]

^<<v42-13-12,12>>^ Quando a viu, Jesus dirigiu-lhe a palavra e disse-lhe: “Mulher, estás livre de tua fraqueza.”

[[v42-13-13]]

^<<v42-13-13,13>>^ E pôs as suas mãos sobre ela; e ela se endireitou instantaneamente e começou a glorificar a Deus.

[[v42-13-14]]

^<<v42-13-14,14>>^ Mas, em resposta, o presidente da sinagoga, indignado porque Jesus fizera a cura no sábado, começou a dizer à multidão: “Há seis dias em que se deve trabalhar; nestes, pois, vinde e sede curados, não no dia de sábado.”

[[v42-13-15]]

^<<v42-13-15,15>>^ O Senhor,^&#42;1^ porém, respondeu-lhe e disse: “Hipócritas, não é que cada um de vós, no sábado, desata da baia o seu touro ou o seu jumento e o leva para dar-lhe de beber?

[NOTE]
====
. Ou “Amo”.
====

[[v42-13-16]]

^<<v42-13-16,16>>^ Não era então apropriado que esta mulher, que é filha de Abraão, e a quem Satanás manteve amarrada, ora! por dezoito anos, fosse solta deste laço no dia de sábado?”

[[v42-13-17]]

^<<v42-13-17,17>>^ Pois bem, quando ele disse estas coisas, todos os seus opositores começaram a ficar envergonhados; mas toda a multidão começou a alegrar-se com todas as coisas gloriosas feitas por ele.

[[v42-13-18]]

^<<v42-13-18,18>>^ Por isso prosseguiu a dizer: “A que se assemelha o reino de Deus e com que o compararei?

[[v42-13-19]]

^<<v42-13-19,19>>^ É semelhante a um grão de mostarda, que um homem tomou e pôs na sua horta, e o qual cresceu e se tornou uma árvore, e as aves do céu ficaram pousando nos seus ramos.”

[[v42-13-20]]

^<<v42-13-20,20>>^ E, novamente, ele disse: “Com que compararei o reino de Deus?

[[v42-13-21]]

^<<v42-13-21,21>>^ É semelhante ao fermento, que certa mulher tomou e escondeu em^&#42;1^ três grandes medidas^&#42;2^ de farinha, até que a massa inteira ficou levedada.”

[NOTE]
====
. Ou “misturou com”.
. Lit.: “seás”. Gr.: sá·ta. O seá equivalia a 7,33 l.
====

[[v42-13-22]]

^<<v42-13-22,22>>^ E ele viajava de cidade em cidade e de aldeia em aldeia, ensinando e continuando na sua viagem a Jerusalém.

[[v42-13-23]]

^<<v42-13-23,23>>^ Então, certo homem lhe disse: “Senhor, são poucos os que estão sendo salvos?” Ele lhes disse:

[[v42-13-24]]

^<<v42-13-24,24>>^ “Esforçai-vos vigorosamente^&#42;1^ a entrar pela porta estreita, porque eu vos digo que muitos buscarão entrar, mas não poderão,

[NOTE]
====
. Lit.: “Estai forcejando.”
====

[[v42-13-25]]

^<<v42-13-25,25>>^ uma vez que o dono de casa se tiver levantado e fechado a porta à chave, e vós principiardes a ficar de fora e a bater na porta, dizendo: ‘Senhor, abre-nos.’ Mas ele, em resposta, vos dirá: ‘Não sei donde sois.’

[[v42-13-26]]

^<<v42-13-26,26>>^ Então principiareis a dizer: ‘Comemos e bebemos na tua frente e tu ensinaste nas nossas ruas largas.’

[[v42-13-27]]

^<<v42-13-27,27>>^ Mas ele falará e vos dirá: ‘Não sei donde sois. Afastai-vos de mim, todos vós obreiros da injustiça!’

[[v42-13-28]]

^<<v42-13-28,28>>^ Ali é que haverá o [vosso] choro e o ranger de [vossos] dentes, quando virdes Abraão, e Isaque, e Jacó, e todos os profetas, no reino de Deus, mas vós mesmos lançados fora.

[[v42-13-29]]

^<<v42-13-29,29>>^ Outrossim, pessoas virão das regiões orientais e das ocidentais, e do norte e do sul, e se recostarão à mesa no reino de Deus.

[[v42-13-30]]

^<<v42-13-30,30>>^ E, eis que há os que são últimos, que serão primeiros, e há os que são primeiros, que serão últimos.”

[[v42-13-31]]

^<<v42-13-31,31>>^ Naquela mesma hora chegaram-se certos fariseus, dizendo-lhe: “Sai e vai embora daqui, porque Herodes^&#42;1^ quer matar-te.”

[NOTE]
====
. Isto é, Herodes Ântipas, filho de Herodes, o Grande. Veja 3:1.
====

[[v42-13-32]]

^<<v42-13-32,32>>^ E ele lhes disse: “Ide e dizei àquela raposa: ‘Eis que estou expulsando demônios e efetuando curas hoje e amanhã, e no terceiro dia terei terminado.’^&#42;1^

[NOTE]
====
. Lit.: “estarei aperfeiçoado”.
====

[[v42-13-33]]

^<<v42-13-33,33>>^ Não obstante, preciso estar em caminho hoje e amanhã, e no dia seguinte, porque não é admissível que um profeta seja destruído fora de Jerusalém.

[[v42-13-34]]

^<<v42-13-34,34>>^ Jerusalém, Jerusalém, matadora dos profetas e apedrejadora dos que lhe são enviados — quantas vezes quis eu ajuntar os teus filhos, da maneira em que a galinha ajunta a sua ninhada de pintinhos debaixo de suas asas, mas vós não quisestes [isso]!

[[v42-13-35]]

^<<v42-13-35,35>>^ Eis que a vossa casa vos fica abandonada. Eu vos digo: De modo algum me vereis até que digais: ‘Bendito aquele que vem em nome de Jeová!’”^&#42;1^

[NOTE]
====
. Veja Ap. 1D.
====

'''

xref:042-lucas/042-lucas-012.adoc#v42-12-0[&#60; Capítulo Anterior] | <<v42-13-0,Topo>> | xref:042-lucas/042-lucas-014.adoc#v42-14-0[Próximo Capítulo &#62;]