include::./index.adoc[]

[[v20-3-0]]
=== Provérbios, 3
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v20-3-1]]

^<<v20-3-1,1>>^ Filho meu, não te esqueças da minha lei, e observe teu coração os meus mandamentos,

[[v20-3-2]]

^<<v20-3-2,2>>^ porque te serão acrescentados^&#42;1^ longura de dias e anos de vida e paz.

[NOTE]
====
. Lit.: “acrescentarão”. O verbo hebr. está na terceira pessoa masc. pl. (não hebr. fem., como “lei” e “mandamentos” no v. 1), referindo-se a um sujeito indefinido.
====

[[v20-3-3]]

^<<v20-3-3,3>>^ Não te abandonem a própria benevolência^&#42;1^ e veracidade.^&#42;2^ Ata-as à tua garganta. Inscreve-as na tábua do teu coração,

[NOTE]
====
. Ou “amor leal”.
. Ou “e verdade”. Hebr.: we·’eméth.
====

[[v20-3-4]]

^<<v20-3-4,4>>^ e acha assim favor e boa perspicácia aos olhos de Deus^&#42;1^ e do homem terreno.^&#42;2^

[NOTE]
====
. “Aos olhos de Deus.” Hebr.: be‛eh·néh ’Elo·hím.
. “E do homem terreno.” Hebr.: we’a·dhám.
====

[[v20-3-5]]

^<<v20-3-5,5>>^ Confia em Jeová de todo o teu coração e não te estribes na tua própria compreensão.

[[v20-3-6]]

^<<v20-3-6,6>>^ Nota-o em todos os teus caminhos, e ele mesmo endireitará as tuas veredas.

[[v20-3-7]]

^<<v20-3-7,7>>^ Não te tornes sábio aos teus próprios olhos. Teme a Jeová e desvia-te do mal.

[[v20-3-8]]

^<<v20-3-8,8>>^ Torne-se isso uma cura para o teu umbigo e refrigério^&#42;1^ para os teus ossos.

[NOTE]
====
. Ou “bebida; umedecimento”. Veja o Sal 102:9.
====

[[v20-3-9]]

^<<v20-3-9,9>>^ Honra a Jeová com as tuas coisas valiosas e com as primícias de todos os teus produtos.

[[v20-3-10]]

^<<v20-3-10,10>>^ Então os teus depósitos de suprimentos se encherão de fartura; e teus tanques de lagar transbordarão^&#42;1^ de vinho novo.

[NOTE]
====
. Lit.: “irromperão”.
====

[[v20-3-11]]

^<<v20-3-11,11>>^ Filho meu, não rejeites a disciplina de Jeová; e não abomines a sua repreensão,

[[v20-3-12]]

^<<v20-3-12,12>>^ porque Jeová repreende aquele a quem ama, assim como o pai faz com o filho em quem tem prazer.

[[v20-3-13]]

^<<v20-3-13,13>>^ Feliz o homem que achou sabedoria e o homem que obtém discernimento,

[[v20-3-14]]

^<<v20-3-14,14>>^ porque tê-la por ganho é melhor do que ter por ganho a prata, e tê-la como produto [é melhor] do que o próprio ouro.^&#42;1^

[NOTE]
====
. “E . . . do que . . . ouro.” Hebr.: u·me·hha·rúts.
====

[[v20-3-15]]

^<<v20-3-15,15>>^ Ela^&#42;1^ é mais preciosa do que os corais, e todos os outros agrados teus não se podem igualar a ela.

[NOTE]
====
. “Ela”, referindo-se à “sabedoria” no v. 13.
====

[[v20-3-16]]

^<<v20-3-16,16>>^ Na sua direita há longura de dias; na sua esquerda há riquezas e glória.^&#42;1^

[NOTE]
====
. Ou “honra”.
====

[[v20-3-17]]

^<<v20-3-17,17>>^ Seus caminhos são caminhos aprazíveis e todas as suas sendas são paz.

[[v20-3-18]]

^<<v20-3-18,18>>^ Ela é árvore de vida para os que a agarram, e os que a seguram bem devem ser chamados de felizes.

[[v20-3-19]]

^<<v20-3-19,19>>^ O próprio Jeová fundou a terra em sabedoria. Firmou solidamente os céus em discernimento.

[[v20-3-20]]

^<<v20-3-20,20>>^ Pelo seu conhecimento foram partidas as próprias águas de profundeza^&#42;1^ e o céu nublado está destilando o chuvisco.

[NOTE]
====
. Ou “águas empoladas”. Hebr.: tehoh·móhth. Veja Sal 33:7 n.: “empoladas”; Sal 42:7 n.: “profundeza”.
====

[[v20-3-21]]

^<<v20-3-21,21>>^ Filho meu, que não se afastem dos teus olhos. Resguarda a sabedoria prática e o raciocínio,

[[v20-3-22]]

^<<v20-3-22,22>>^ e mostrar-se-ão vida para a tua alma e encanto para a tua garganta.

[[v20-3-23]]

^<<v20-3-23,23>>^ Neste caso andarás em segurança no teu caminho e até mesmo teu pé não baterá em coisa alguma.

[[v20-3-24]]

^<<v20-3-24,24>>^ Quando te deitares, não sentirás pavor; e hás de deitar-te e teu sono terá de ser prazenteiro.

[[v20-3-25]]

^<<v20-3-25,25>>^ Não precisarás ter medo de uma repentina coisa pavorosa, nem da tempestade sobre os iníquos, porque ela está chegando.

[[v20-3-26]]

^<<v20-3-26,26>>^ Porque o próprio Jeová, de fato, mostrará ser tua confiança^&#42;1^ e ele certamente guardará teu pé da captura.

[NOTE]
====
. Lit.: “mostrará ter a tua confiança”, M; LXX: “estará em todos os teus caminhos”.
====

[[v20-3-27]]

^<<v20-3-27,27>>^ Não negues o bem àqueles a quem é devido,^&#42;1^ quando estiver no poder da tua mão fazê-lo.

[NOTE]
====
. Lit.: “aos seus donos”. Hebr.: mib·be‛a·láv, pl. de bá·‛al.
====

[[v20-3-28]]

^<<v20-3-28,28>>^ Não digas ao teu próximo: “Vai, e volta, e amanhã darei”, quando tens alguma coisa contigo.

[[v20-3-29]]

^<<v20-3-29,29>>^ Não projetes nenhum mal contra o teu próximo, quando ele está morando contigo em sentimento de segurança.

[[v20-3-30]]

^<<v20-3-30,30>>^ Não alterques com um homem^&#42;1^ sem causa, se não te fez nenhum mal.

[NOTE]
====
. Ou “um homem terreno”. Hebr.: ’a·dhám.
====

[[v20-3-31]]

^<<v20-3-31,31>>^ Não fiques invejoso do homem^&#42;1^ de violência, nem escolhas a quaisquer dos seus caminhos.

[NOTE]
====
. “Do homem de.” Hebr.: be’ísh.
====

[[v20-3-32]]

^<<v20-3-32,32>>^ Porque a pessoa sinuosa é algo detestável para Jeová, mas ele tem intimidade com os retos.

[[v20-3-33]]

^<<v20-3-33,33>>^ A maldição de Jeová está sobre a casa do iníquo, mas ele abençoa o lugar de permanência dos justos.

[[v20-3-34]]

^<<v20-3-34,34>>^ Se o caso for com os zombadores, ele mesmo zombará; porém, mostrará favor aos mansos.

[[v20-3-35]]

^<<v20-3-35,35>>^ Honra^&#42;1^ é o que os sábios virão possuir, mas os estúpidos enaltecem a desonra.

[NOTE]
====
. Ou: “Glória”.
====

'''

xref:020-proverbios/020-proverbios-002.adoc#v20-2-0[&#60; Capítulo Anterior] | <<v20-3-0,Topo>> | xref:020-proverbios/020-proverbios-004.adoc#v20-4-0[Próximo Capítulo &#62;]