include::./index.adoc[]

[[v20-4-0]]
=== Provérbios, 4
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v20-4-1]]

^<<v20-4-1,1>>^ Escutai, ó filhos, a disciplina do pai e prestai atenção, para conhecerdes a compreensão.

[[v20-4-2]]

^<<v20-4-2,2>>^ Pois é boa instrução o que vos hei de dar. Não abandoneis a minha lei.

[[v20-4-3]]

^<<v20-4-3,3>>^ Pois, mostrei-me verdadeiro filho para meu pai, terno e o único diante de minha mãe.

[[v20-4-4]]

^<<v20-4-4,4>>^ E ele me instruía e me dizia: “Segure teu coração as minhas palavras. Guarda os meus mandamentos e continua vivendo.

[[v20-4-5]]

^<<v20-4-5,5>>^ Adquire sabedoria, adquire compreensão. Não te esqueças e não te apartes das declarações da minha boca.

[[v20-4-6]]

^<<v20-4-6,6>>^ Não a^&#42;1^ abandones, e ela te guardará. Ama-a, e ela te resguardará.

[NOTE]
====
. “A”, referindo-se à “sabedoria”.
====

[[v20-4-7]]

^<<v20-4-7,7>>^ Sabedoria é a coisa principal. Adquire sabedoria; e com tudo o que adquirires, adquire compreensão.

[[v20-4-8]]

^<<v20-4-8,8>>^ Estima-a muito, e ela te exaltará. Ela te glorificará, porque a abraças.

[[v20-4-9]]

^<<v20-4-9,9>>^ Dará à tua cabeça uma grinalda de encanto; presentear-te-á com uma coroa de beleza.”

[[v20-4-10]]

^<<v20-4-10,10>>^ Ouve, filho meu, e aceita as minhas declarações. Então os anos de vida se tornarão muitos para ti.^&#42;1^

[NOTE]
====
. Ou: “E elas [as minhas declarações] se tornarão muitas para ti durante os anos de vida.”
====

[[v20-4-11]]

^<<v20-4-11,11>>^ Vou instruir-te no próprio caminho da sabedoria; vou fazer que pises nos trilhos da retidão.

[[v20-4-12]]

^<<v20-4-12,12>>^ Ao andares, teu passo não ficará tolhido; e se correres, não tropeçarás.

[[v20-4-13]]

^<<v20-4-13,13>>^ Agarra a disciplina; não [a] largues.^&#42;1^ Resguarda-a,^&#42;2^ pois ela mesma é a tua vida.

[NOTE]
====
. Ou “não [a] deixes sozinha”.
. “A.” Veja v. 6 n.
====

[[v20-4-14]]

^<<v20-4-14,14>>^ Não entres na vereda dos iníquos e não te encaminhes diretamente para o caminho dos maus.

[[v20-4-15]]

^<<v20-4-15,15>>^ Evita-o, não passes por ele; aparta-te dele e passa adiante.

[[v20-4-16]]

^<<v20-4-16,16>>^ Pois eles não dormem a menos que façam alguma maldade, e o sono lhes é arrebatado a menos que façam alguém tropeçar.

[[v20-4-17]]

^<<v20-4-17,17>>^ Pois alimentaram-se do pão da iniqüidade e bebem o vinho de atos de violência.

[[v20-4-18]]

^<<v20-4-18,18>>^ Mas a vereda dos justos é como a luz clara que clareia mais e mais até o dia estar firmemente estabelecido.

[[v20-4-19]]

^<<v20-4-19,19>>^ O caminho dos iníquos é como as trevas; não souberam em que têm estado tropeçando.

[[v20-4-20]]

^<<v20-4-20,20>>^ Filho meu, presta deveras atenção às minhas palavras. Inclina teu ouvido às minhas declarações.

[[v20-4-21]]

^<<v20-4-21,21>>^ Não se afastem elas dos teus olhos. Guarda-as no meio do teu coração.

[[v20-4-22]]

^<<v20-4-22,22>>^ Porque são vida para os que as acham e saúde para toda a sua carne.

[[v20-4-23]]

^<<v20-4-23,23>>^ Mais do que qualquer outra coisa a ser guardada, resguarda teu coração, pois dele procedem as fontes da vida.

[[v20-4-24]]

^<<v20-4-24,24>>^ Remove de ti a perversão da fala;^&#42;1^ e põe longe de ti a sinuosidade dos lábios.

[NOTE]
====
. Lit.: “boca”.
====

[[v20-4-25]]

^<<v20-4-25,25>>^ Quanto aos teus olhos, devem olhar diretamente para a frente, sim, teus olhos radiantes devem mirar diretamente para diante de ti.

[[v20-4-26]]

^<<v20-4-26,26>>^ Aplana o rumo de teu pé,^&#42;1^ e sejam firmemente estabelecidos todos os teus próprios caminhos.

[NOTE]
====
. “Faze retas as veredas para os teus pés”, LXX. Veja He 12:13.
====

[[v20-4-27]]

^<<v20-4-27,27>>^ Não te inclines nem para a direita nem para a esquerda. Remove teu pé daquilo que é mau.

'''

xref:020-proverbios/020-proverbios-003.adoc#v20-3-0[&#60; Capítulo Anterior] | <<v20-4-0,Topo>> | xref:020-proverbios/020-proverbios-005.adoc#v20-5-0[Próximo Capítulo &#62;]