include::./index.adoc[]

[[v20-5-0]]
=== Provérbios, 5
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v20-5-1]]

^<<v20-5-1,1>>^ Filho meu, presta deveras atenção à minha sabedoria. Inclina teus ouvidos ao meu discernimento,

[[v20-5-2]]

^<<v20-5-2,2>>^ para guardar os raciocínios; e resguardem os teus lábios o próprio conhecimento.

[[v20-5-3]]

^<<v20-5-3,3>>^ Pois os lábios duma mulher estranha estão gotejando como favo de mel e seu paladar é mais macio do que o azeite.

[[v20-5-4]]

^<<v20-5-4,4>>^ Mas o efeito posterior dela é tão amargo como o absinto; é tão afiado como uma espada de dois gumes.

[[v20-5-5]]

^<<v20-5-5,5>>^ Seus pés descem à morte. Mesmo os passos dela firmam-se no próprio Seol.^&#42;1^

[NOTE]
====
. “Seol.” Hebr.: she’óhl; gr.: haí·den; lat.: ín·fe·ros.
====

[[v20-5-6]]

^<<v20-5-6,6>>^ Ela não contempla a vereda da vida. Seus trilhos seguiram errantes, ela nem sabe [para onde].

[[v20-5-7]]

^<<v20-5-7,7>>^ Portanto, agora, ó filhos, escutai-me e não vos desvieis das declarações da minha boca.

[[v20-5-8]]

^<<v20-5-8,8>>^ Guarda teu caminho longe dela e não te chegues à entrada da sua casa,

[[v20-5-9]]

^<<v20-5-9,9>>^ para que não dês a tua dignidade^&#42;1^ a outros, nem os teus anos ao que é cruel;

[NOTE]
====
. “Dignidade”, M; TSy: “energia vital”; LXX: “vida”; Vg: “honra”.
====

[[v20-5-10]]

^<<v20-5-10,10>>^ para que os estranhos não se fartem com o teu poder, nem as coisas que obtiveste com dor fiquem na casa dum estrangeiro,

[[v20-5-11]]

^<<v20-5-11,11>>^ nem tenhas de gemer no teu futuro, quando tua carne e teu organismo chegarem ao fim.

[[v20-5-12]]

^<<v20-5-12,12>>^ E terás de dizer: “Quanto odiei a disciplina e desrespeitou meu coração até mesmo a repreensão!

[[v20-5-13]]

^<<v20-5-13,13>>^ E não escutei a voz dos meus instrutores e não inclinei meu ouvido aos meus mestres.

[[v20-5-14]]

^<<v20-5-14,14>>^ Vim a estar facilmente em toda sorte de maldade no meio da congregação e da assembléia.”

[[v20-5-15]]

^<<v20-5-15,15>>^ Bebe água da tua própria cisterna e filetes de água do meio do teu próprio poço.

[[v20-5-16]]

^<<v20-5-16,16>>^ Porventura se deviam espalhar teus mananciais portas afora, [tuas] correntes de água nas próprias praças públicas?

[[v20-5-17]]

^<<v20-5-17,17>>^ Que mostrem ser somente para ti e não para os estranhos contigo.

[[v20-5-18]]

^<<v20-5-18,18>>^ Mostre-se abençoada a tua fonte de água e alegra-te com a esposa da tua mocidade,

[[v20-5-19]]

^<<v20-5-19,19>>^ gama amável e encantadora cabra-montesa. Inebriem-te os seus próprios seios todo o tempo. Que te extasies constantemente com o seu amor.

[[v20-5-20]]

^<<v20-5-20,20>>^ Portanto, meu filho, por que te devias extasiar com uma mulher estranha ou abraçar o seio duma mulher estrangeira?

[[v20-5-21]]

^<<v20-5-21,21>>^ Porque os caminhos do homem^&#42;1^ estão diante dos olhos de Jeová e ele contempla todos os seus trilhos.

[NOTE]
====
. “Homem.” Hebr.: ‘ish.
====

[[v20-5-22]]

^<<v20-5-22,22>>^ Ao iníquo apanharão^&#42;1^ os seus próprios erros e ele será segurado pelas cordas do seu próprio pecado.

[NOTE]
====
. Ou: “Com o iníquo o apanharão.”
====

[[v20-5-23]]

^<<v20-5-23,23>>^ Será ele quem morrerá por não haver disciplina e [por] ele se perder^&#42;1^ na abundância da sua tolice.

[NOTE]
====
. “E será varrido”, mediante uma correção do M; LXX: “e foi destruído”.
====

'''

xref:020-proverbios/020-proverbios-004.adoc#v20-4-0[&#60; Capítulo Anterior] | <<v20-5-0,Topo>> | xref:020-proverbios/020-proverbios-006.adoc#v20-6-0[Próximo Capítulo &#62;]