include::./index.adoc[]

[[v20-22-0]]
=== Provérbios, 22
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v20-22-1]]

^<<v20-22-1,1>>^ Deve-se escolher antes um nome^&#42;1^ do que riquezas abundantes; o favor é melhor do que mesmo a prata e o ouro.

[NOTE]
====
. “Um nome”, M(hebr.: shem)Sy; TLXXVg: “um bom nome”.
====

[[v20-22-2]]

^<<v20-22-2,2>>^ Encontraram-se o rico e o de poucos meios. Aquele que fez a todos eles é Jeová.

[[v20-22-3]]

^<<v20-22-3,3>>^ Argucioso é aquele que tem visto a calamidade e passa a esconder-se, mas os inexperientes passaram adiante e terão de sofrer a penalidade.

[[v20-22-4]]

^<<v20-22-4,4>>^ O resultado da humildade [e] do temor de Jeová é riquezas, e glória, e vida.

[[v20-22-5]]

^<<v20-22-5,5>>^ Há espinhos [e] armadilhas no caminho do pervertido; quem guarda a sua alma mantém-se longe deles.

[[v20-22-6]]

^<<v20-22-6,6>>^ Educa o rapaz segundo^&#42;1^ o caminho que é para ele; mesmo quando envelhecer não se desviará dele.

[NOTE]
====
. Lit.: “à boca (abertura) do”.
====

[[v20-22-7]]

^<<v20-22-7,7>>^ O rico é quem domina sobre os de poucos meios, e quem toma emprestado é servo do homem que empresta.

[[v20-22-8]]

^<<v20-22-8,8>>^ Quem semeia a injustiça ceifará o que é prejudicial, mas a própria vara da sua fúria chegará ao seu fim.

[[v20-22-9]]

^<<v20-22-9,9>>^ Quem é bondoso de olho será abençoado, porque deu do seu alimento ao de condição humilde.

[[v20-22-10]]

^<<v20-22-10,10>>^ Expulsa ao zombador para que saia a contenda e cessem o litígio e a desonra.

[[v20-22-11]]

^<<v20-22-11,11>>^ Quem ama a pureza de coração^&#42;1^ — pelo encanto dos seus lábios o rei será seu companheiro.

[NOTE]
====
. “Deus ama o de coração puro”, TSy; LXX: “Jeová ama corações puros.”
====

[[v20-22-12]]

^<<v20-22-12,12>>^ Os olhos do próprio Jeová têm resguardado o conhecimento, mas ele transtorna as palavras^&#42;1^ do traiçoeiro.

[NOTE]
====
. Ou “assuntos”.
====

[[v20-22-13]]

^<<v20-22-13,13>>^ O preguiçoso disse: “Há um leão lá fora! Serei assassinado no meio das praças públicas!”

[[v20-22-14]]

^<<v20-22-14,14>>^ A boca da mulher estranha é uma cova funda. Aquele que é verberado por Jeová cairá nela.

[[v20-22-15]]

^<<v20-22-15,15>>^ A tolice está ligada ao coração do rapaz; a vara da disciplina é a que a removerá para longe dele.

[[v20-22-16]]

^<<v20-22-16,16>>^ Quem defrauda ao de condição humilde para suprir-se de muitas coisas, bem como aquele que dá ao rico, seguramente se destina à carência.

[[v20-22-17]]

^<<v20-22-17,17>>^ Inclina teu ouvido e ouve as palavras dos sábios, para que fixes teu próprio coração no meu conhecimento.

[[v20-22-18]]

^<<v20-22-18,18>>^ Pois é agradável que as guardes no teu ventre, para que juntas fiquem firmemente estabelecidas sobre os teus lábios.

[[v20-22-19]]

^<<v20-22-19,19>>^ Para que viesses a ter confiança no próprio Jeová, dei-te hoje conhecimento, sim, a ti.^&#42;1^

[NOTE]
====
. “Fiz que conhecesses hoje tuas veredas”, mediante uma correção do M, em harmonia com LXXB.
====

[[v20-22-20]]

^<<v20-22-20,20>>^ Não te escrevi até agora^&#42;1^ com conselhos e conhecimento,

[NOTE]
====
. Ou “em trinta seções (partes)”. M não é claro.
====

[[v20-22-21]]

^<<v20-22-21,21>>^ para mostrar-te a veracidade^&#42;1^ de declarações verazes, a fim de replicar declarações que são verdade — àquele que te envia?

[NOTE]
====
. “Veracidade de.” Hebr.: qosht, palavra encontrada em aram. bíblico, como em Da 2:47.
====

[[v20-22-22]]

^<<v20-22-22,22>>^ Não roubes ao de condição humilde por ele ser de condição humilde e não esmigalhes o atribulado no portão.

[[v20-22-23]]

^<<v20-22-23,23>>^ Porque o próprio Jeová pleiteará a sua causa e certamente roubará a alma^&#42;1^ dos que os roubam.

[NOTE]
====
. Ou “vida”. Hebr.: ná·fesh; gr.: psy·khén; lat.: á·ni·mam. Veja Ap. 4A.
====

[[v20-22-24]]

^<<v20-22-24,24>>^ Não tenhas companheirismo com alguém dado à ira; e não deves entrar com o homem que tem acessos de furor,

[[v20-22-25]]

^<<v20-22-25,25>>^ para não te familiarizares com as suas veredas e certamente tomares um laço para a tua alma.

[[v20-22-26]]

^<<v20-22-26,26>>^ Não venhas a ficar entre os que batem as mãos, entre os que são fiadores de empréstimos.

[[v20-22-27]]

^<<v20-22-27,27>>^ Se não tiveres nada com que pagar, por que tirarias a tua cama de debaixo de ti?

[[v20-22-28]]

^<<v20-22-28,28>>^ Não recues algum termo [existente] há muito tempo, feito pelos teus antepassados.

[[v20-22-29]]

^<<v20-22-29,29>>^ Observaste o homem que é destro na sua obra? É perante reis que ele se postará; não se postará diante de homens comuns.

'''

xref:020-proverbios/020-proverbios-021.adoc#v20-21-0[&#60; Capítulo Anterior] | <<v20-22-0,Topo>> | xref:020-proverbios/020-proverbios-023.adoc#v20-23-0[Próximo Capítulo &#62;]