include::./index.adoc[]

[[v20-8-0]]
=== Provérbios, 8
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v20-8-1]]

^<<v20-8-1,1>>^ Não está chamando [a] sabedoria e não está [o] discernimento emitindo a sua voz?

[[v20-8-2]]

^<<v20-8-2,2>>^ Postou-se no cume das elevações, junto ao caminho, na encruzilhada das sendas.

[[v20-8-3]]

^<<v20-8-3,3>>^ Ao lado dos portões, na boca da vila, no acesso das entradas ela continua a gritar alto:

[[v20-8-4]]

^<<v20-8-4,4>>^ “A vós, ó homens,^&#42;1^ é que estou chamando, e minha voz é para os filhos dos homens.^&#42;2^

[NOTE]
====
. “Homens.” Hebr.: ’i·shím, pl. de ’ish. Veja Is 53:3 n.: “homens”.
. Lit.: “homem terreno”. Hebr.: ’a·dhám.
====

[[v20-8-5]]

^<<v20-8-5,5>>^ Ó inexperientes, compreendei a argúcia; e vós, estúpidos, entendei o coração.^&#42;1^

[NOTE]
====
. Ou “tende boa motivação”. Hebr.: ha·ví·nu lev.
====

[[v20-8-6]]

^<<v20-8-6,6>>^ Escutai, pois estou falando sobre as coisas primordiais e meus lábios se abrem a respeito da retidão.

[[v20-8-7]]

^<<v20-8-7,7>>^ Porque meu palato profere em voz baixa a própria verdade; e a iniqüidade é algo detestável para os meus lábios.

[[v20-8-8]]

^<<v20-8-8,8>>^ Todas as declarações da minha boca são [feitas] em justiça. Entre elas não há nada tortuoso ou pervertido.

[[v20-8-9]]

^<<v20-8-9,9>>^ Todas elas são direitas para quem tem discernimento e retas para os que acham conhecimento.

[[v20-8-10]]

^<<v20-8-10,10>>^ Tomai a minha disciplina, e não a prata, e o conhecimento em vez de ouro escolhido.

[[v20-8-11]]

^<<v20-8-11,11>>^ Porque melhor é a sabedoria do que os corais, e mesmo todos os outros agrados não se podem igualar a ela.

[[v20-8-12]]

^<<v20-8-12,12>>^ “Eu, [a] sabedoria, tenho residido com argúcia e acho até mesmo o conhecimento dos raciocínios.

[[v20-8-13]]

^<<v20-8-13,13>>^ O temor de Jeová significa odiar o mal. A exaltação de si próprio e o orgulho, bem como o caminho mau e a boca perversa eu tenho odiado.

[[v20-8-14]]

^<<v20-8-14,14>>^ Tenho conselho e sabedoria prática. Eu — compreensão; tenho potência.

[[v20-8-15]]

^<<v20-8-15,15>>^ Por mim é que reinam os próprios reis e os próprios dignitários continuam a decretar justiça.

[[v20-8-16]]

^<<v20-8-16,16>>^ Por mim é que os próprios príncipes governam como príncipes e todos os nobres estão julgando em justiça.

[[v20-8-17]]

^<<v20-8-17,17>>^ Eu mesma amo os que me^&#42;1^ amam, e os que estão à minha procura são os que me acham.

[NOTE]
====
. “Me”, MmargemTLXXSyVg; M: “a (ela)”.
====

[[v20-8-18]]

^<<v20-8-18,18>>^ Comigo há riquezas e glória,^&#42;1^ valores hereditários e justiça.

[NOTE]
====
. Ou “honra”.
====

[[v20-8-19]]

^<<v20-8-19,19>>^ Meus frutos são melhores do que o ouro,^&#42;1^ sim, [melhores] do que o ouro refinado, e meus produtos [são melhores] do que a prata escolhida.

[NOTE]
====
. “Do que o ouro.” Hebr.: me·hha·rúts.
====

[[v20-8-20]]

^<<v20-8-20,20>>^ Ando na vereda da justiça, no meio da senda do juízo,

[[v20-8-21]]

^<<v20-8-21,21>>^ para fazer os que me amam tomar posse de haveres; e mantenho cheios os seus depósitos.

[[v20-8-22]]

^<<v20-8-22,22>>^ “O próprio Jeová me produziu^&#42;1^ como princípio^&#42;2^ do seu caminho, a mais antiga das suas realizações de há muito.

[NOTE]
====
. “Me produziu.” Hebr.: qa·ná·ni; TLXX(gr.: é·kti·sén me)Sy: “me criou”; lat.: pos·sé·dit me, “possuiu-me”. Veja Gên 14:19 n.
. “Como princípio do.” Hebr.: re’·shíth; gr.: ar·khén; não bere’·shíth (hebr.), nem en ar·kheí (gr.), como em Gên 1:1; TSyVgc(lat.: in i·ní·ti·o), “no início”.
====

[[v20-8-23]]

^<<v20-8-23,23>>^ Fui empossada desde tempo indefinido, desde o começo,^&#42;1^ desde tempos mais remotos do que a terra.

[NOTE]
====
. Lit.: “desde a cabeça”. Hebr.: me·ró’sh.
====

[[v20-8-24]]

^<<v20-8-24,24>>^ Quando não havia águas de profundeza,^&#42;1^ fui produzida como que com dores de parto, quando não havia mananciais fortemente carregados com água.

[NOTE]
====
. Ou “águas empoladas”. Hebr.: teho·móhth. Veja Gên 1:2 n.: “profundeza”.
====

[[v20-8-25]]

^<<v20-8-25,25>>^ Antes de serem assentados os próprios montes, adiante dos morros, fui produzida como que com dores de parto,

[[v20-8-26]]

^<<v20-8-26,26>>^ quando ele ainda não havia feito a terra e os espaços abertos, nem a primeira parte das massas de pó do solo produtivo.^&#42;1^

[NOTE]
====
. “Solo produtivo.” Hebr.: te·vél; lat.: ór·bis tér·rae, “círculo da terra”.
====

[[v20-8-27]]

^<<v20-8-27,27>>^ Quando ele preparou os céus, eu estava lá; quando decretou o círculo sobre a face da água de profundeza,

[[v20-8-28]]

^<<v20-8-28,28>>^ quando firmou as massas de nuvens acima, quando fez ficar fortes as fontes da água de profundeza,

[[v20-8-29]]

^<<v20-8-29,29>>^ quando fixou ao mar o seu decreto, para que as próprias águas não ultrapassassem a sua ordem,^&#42;1^ quando decretou os alicerces da terra,

[NOTE]
====
. Lit.: “boca”.
====

[[v20-8-30]]

^<<v20-8-30,30>>^ então vim a estar ao seu lado como mestre-de-obras,^&#42;1^ e vim a ser aquele de quem ele^&#42;2^ gostava especialmente de dia a dia, regozijando-me perante ele todo o tempo,

[NOTE]
====
. Ou “adotivo”. Hebr.: ’a·móhn; T: “mostrando-me fiel”; LXX: “agindo adequadamente”; Vg: “compondo todas as coisas”.
. “Ele”, LXXSy.
====

[[v20-8-31]]

^<<v20-8-31,31>>^ regozijando-me com o solo produtivo^&#42;1^ da sua terra, e as coisas de que eu gostava estavam com os filhos dos homens.^&#42;2^

[NOTE]
====
. “Com o solo produtivo da.” Hebr.: bethe·vél; LXX: “a terra habitada”.
. Lit.: “homem terreno”. Hebr.: ’a·dhám.
====

[[v20-8-32]]

^<<v20-8-32,32>>^ “E agora, ó filhos, escutai-me; sim, felizes são os que guardam os próprios caminhos meus.

[[v20-8-33]]

^<<v20-8-33,33>>^ Escutai a disciplina e tornai-vos sábios, e não sejais negligentes.

[[v20-8-34]]

^<<v20-8-34,34>>^ Feliz o homem que me está escutando por ficar alerta às minhas portas dia a dia, vigiando junto às ombreiras das minhas entradas.

[[v20-8-35]]

^<<v20-8-35,35>>^ Pois, quem me achar, há de achar a vida, e ele obterá boa vontade da parte de Jeová.

[[v20-8-36]]

^<<v20-8-36,36>>^ Mas aquele que não acerta comigo faz violência à sua alma; todos os que me odeiam intensamente são os que amam a morte.”

'''

xref:020-proverbios/020-proverbios-007.adoc#v20-7-0[&#60; Capítulo Anterior] | <<v20-8-0,Topo>> | xref:020-proverbios/020-proverbios-009.adoc#v20-9-0[Próximo Capítulo &#62;]