include::./index.adoc[]

[[v20-21-0]]
=== Provérbios, 21
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v20-21-1]]

^<<v20-21-1,1>>^ O coração do rei é como correntes de água na mão de Jeová. Vira-o para onde quer que se agrade.

[[v20-21-2]]

^<<v20-21-2,2>>^ Todo caminho do homem é reto aos seus próprios olhos, mas Jeová faz a avaliação dos corações.

[[v20-21-3]]

^<<v20-21-3,3>>^ Executar a justiça e o juízo é preferido por Jeová a um sacrifício.

[[v20-21-4]]

^<<v20-21-4,4>>^ Olhos altaneiros e um coração arrogante, a lâmpada dos iníquos, são pecado.^&#42;1^

[NOTE]
====
. Ou “são [para eles preferíveis a] uma oferta pelo pecado”.
====

[[v20-21-5]]

^<<v20-21-5,5>>^ Os planos do diligente seguramente resultam em vantagem, mas todo precipitado seguramente [se encaminha] para a carência.

[[v20-21-6]]

^<<v20-21-6,6>>^ A obtenção de tesouros por meio duma língua falsa é uma exalação impelida [para longe] no caso dos que procuram a morte.

[[v20-21-7]]

^<<v20-21-7,7>>^ A própria assolação por parte dos iníquos os arrastará, pois negaram-se a fazer justiça.

[[v20-21-8]]

^<<v20-21-8,8>>^ O homem, mesmo o estranho, é tortuoso no [seu] caminho;^&#42;1^ mas o puro é reto na sua atuação.

[NOTE]
====
. Ou: “O caminho do homem, mesmo dum estranho, é tortuoso”; ou: “O caminho do homem é tortuoso e estranho.”
====

[[v20-21-9]]

^<<v20-21-9,9>>^ Melhor é morar num canto do terraço, do que com uma esposa contenciosa, embora numa casa em comum.

[[v20-21-10]]

^<<v20-21-10,10>>^ A própria alma do iníquo tem almejado o que é mau; aos olhos dele não se mostrará favor ao seu próximo.

[[v20-21-11]]

^<<v20-21-11,11>>^ Por se impor uma multa ao zombador, o inexperiente torna-se sábio; e por se dar perspicácia ao sábio, ele obtém conhecimento.^&#42;1^

[NOTE]
====
. “E, por agir com discrição, o sábio obtém conhecimento”, T.
====

[[v20-21-12]]

^<<v20-21-12,12>>^ O Justo dá consideração à casa^&#42;1^ do iníquo, transtornando os iníquos para a [sua] calamidade.

[NOTE]
====
. Ou “age discretamente para com a casa”.
====

[[v20-21-13]]

^<<v20-21-13,13>>^ Quanto àquele que tapa seu ouvido contra o clamor queixoso do de condição humilde, ele mesmo também clamará e não se lhe responderá.

[[v20-21-14]]

^<<v20-21-14,14>>^ Uma dádiva feita às escondidas aplaca a ira; e o suborno no peito, o forte furor.

[[v20-21-15]]

^<<v20-21-15,15>>^ Para o justo é uma alegria fazer justiça, mas há algo terrível para os que praticam o que é prejudicial.

[[v20-21-16]]

^<<v20-21-16,16>>^ Quanto ao homem^&#42;1^ que se vai perdendo do caminho da perspicácia, descansará na própria congregação dos impotentes na morte.^&#42;2^

[NOTE]
====
. Ou “homem terreno”. Hebr.: ’a·dhám.
. “Dos impotentes na morte.” Hebr.: refa·’ím; TSy: “dos filhos da terra”; LXXVg: “gigantes”.
====

[[v20-21-17]]

^<<v20-21-17,17>>^ Aquele que ama a hilaridade será alguém em necessidade; quem ama o vinho e o azeite não enriquecerá.

[[v20-21-18]]

^<<v20-21-18,18>>^ O iníquo é resgate para o justo; e quem age traiçoeiramente toma o lugar dos retos.

[[v20-21-19]]

^<<v20-21-19,19>>^ Melhor é morar numa terra erma, do que com uma esposa contenciosa junto com vexame.

[[v20-21-20]]

^<<v20-21-20,20>>^ Há tesouro desejável e azeite na residência do sábio, mas o homem estúpido o engolirá.

[[v20-21-21]]

^<<v20-21-21,21>>^ Quem se empenha pela justiça e pela benevolência achará vida, justiça e glória.

[[v20-21-22]]

^<<v20-21-22,22>>^ O sábio escalou a própria cidade dos poderosos, para deitar abaixo a força da sua confiança.

[[v20-21-23]]

^<<v20-21-23,23>>^ Quem guarda a sua boca e a sua língua está guardando a sua alma das aflições.

[[v20-21-24]]

^<<v20-21-24,24>>^ Fanfarrão presunçoso, pretensioso, é o nome daquele que age numa fúria de presunção.

[[v20-21-25]]

^<<v20-21-25,25>>^ O próprio anelo do preguiçoso o entregará à morte, pois as suas mãos se negaram a trabalhar.

[[v20-21-26]]

^<<v20-21-26,26>>^ O dia inteiro ele demonstrou anelar ansiosamente, mas o justo dá e não nega nada.

[[v20-21-27]]

^<<v20-21-27,27>>^ O sacrifício dos iníquos é algo detestável. Quanto mais quando é trazido junto com conduta desenfreada.

[[v20-21-28]]

^<<v20-21-28,28>>^ A testemunha mentirosa perecerá, mas o homem que escuta falará, sim, para sempre.

[[v20-21-29]]

^<<v20-21-29,29>>^ O homem iníquo fez a sua face atrevida, mas o reto é aquele que será firmemente estabelecido nos seus caminhos.

[[v20-21-30]]

^<<v20-21-30,30>>^ Não há sabedoria, nem discernimento, nem conselho em oposição a Jeová.

[[v20-21-31]]

^<<v20-21-31,31>>^ O cavalo é algo preparado para o dia da batalha, mas a salvação pertence a Jeová.

'''

xref:020-proverbios/020-proverbios-020.adoc#v20-20-0[&#60; Capítulo Anterior] | <<v20-21-0,Topo>> | xref:020-proverbios/020-proverbios-022.adoc#v20-22-0[Próximo Capítulo &#62;]