include::./index.adoc[]

[[v20-16-0]]
=== Provérbios, 16
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v20-16-1]]

^<<v20-16-1,1>>^ Ao homem terreno^&#42;1^ pertencem os arranjos do coração, mas de Jeová é a resposta da língua.

[NOTE]
====
. “Ao homem terreno.” Hebr.: le’a·dhám.
====

[[v20-16-2]]

^<<v20-16-2,2>>^ Todos os caminhos do homem^&#42;1^ são puros aos seus próprios olhos, mas Jeová faz a avaliação dos espíritos.

[NOTE]
====
. “Todos os caminhos do homem.” Hebr.: kal-dar·kheh-’ísh.
====

[[v20-16-3]]

^<<v20-16-3,3>>^ Rola os teus trabalhos sobre o próprio Jeová e os teus planos ficarão firmemente estabelecidos.

[[v20-16-4]]

^<<v20-16-4,4>>^ Tudo Jeová fez para seu propósito, sim, mesmo o iníquo para o dia mau.

[[v20-16-5]]

^<<v20-16-5,5>>^ Todo o soberbo de coração é algo detestável para Jeová. Mão [talvez se junte] a mão, [contudo,] não se ficará impune.

[[v20-16-6]]

^<<v20-16-6,6>>^ Pela benevolência^&#42;1^ e pela veracidade se expia o erro, e no temor de Jeová a pessoa se desvia do mal.

[NOTE]
====
. Ou “amor leal”.
====

[[v20-16-7]]

^<<v20-16-7,7>>^ Quando Jeová tem prazer nos caminhos de um homem, faz que até os seus próprios inimigos estejam em paz com ele.

[[v20-16-8]]

^<<v20-16-8,8>>^ Melhor é um pouco com justiça do que uma abundância de produtos sem justiça.^&#42;1^

[NOTE]
====
. Ou “julgamento”.
====

[[v20-16-9]]

^<<v20-16-9,9>>^ O coração do homem terreno talvez conceba o seu caminho, mas é o próprio Jeová quem dirige os seus passos.

[[v20-16-10]]

^<<v20-16-10,10>>^ Deve haver decisão inspirada sobre os lábios do rei; no julgamento, sua boca não se deve mostrar infiel.

[[v20-16-11]]

^<<v20-16-11,11>>^ Fiel e balança justos pertencem a Jeová; todos os pesos de pedra da bolsa são seu trabalho.

[[v20-16-12]]

^<<v20-16-12,12>>^ Fazer o que é iníquo é algo detestável para os reis, porque é pela justiça que se estabelece firmemente o trono.

[[v20-16-13]]

^<<v20-16-13,13>>^ Os lábios de justiça são um prazer para o grandioso rei;^&#42;1^ e ele ama a quem fala coisas retas.

[NOTE]
====
. “O grandioso rei.” Lit.: “reis”, como no v. 12, pl. para denotar majestade.
====

[[v20-16-14]]

^<<v20-16-14,14>>^ O furor de um rei significa mensageiros da morte, mas homem sábio é aquele que o evita.^&#42;1^

[NOTE]
====
. Lit.: “ele o cobrirá”. Hebr.: yekhap·perén·nah.
====

[[v20-16-15]]

^<<v20-16-15,15>>^ Na luz da face do rei há vida, e sua boa vontade é como a nuvem da chuva primaveril.

[[v20-16-16]]

^<<v20-16-16,16>>^ Quanto melhor é obter sabedoria do que ouro! E obter compreensão deve ser preferido à prata.

[[v20-16-17]]

^<<v20-16-17,17>>^ A estrada principal dos retos é para se desviar do mal. Quem resguarda seu caminho guarda sua alma.

[[v20-16-18]]

^<<v20-16-18,18>>^ O orgulho vem antes da derrocada e o espírito soberbo^&#42;1^ antes do tropeço.

[NOTE]
====
. Lit.: “altura (altivez) de espírito”. Hebr.: gó·vah rú·ahh.
====

[[v20-16-19]]

^<<v20-16-19,19>>^ Melhor é ser humilde em espírito^&#42;1^ com os mansos,^&#42;2^ do que repartir despojo com os que se enaltecem.

[NOTE]
====
. “Ser humilde em espírito.” Hebr.: shefal-rú·ahh.
. “Mansos”, Mmargem; M: “aflitos”.
====

[[v20-16-20]]

^<<v20-16-20,20>>^ Quem mostrar perspicácia num assunto achará o bem, e feliz é aquele que confia em Jeová.

[[v20-16-21]]

^<<v20-16-21,21>>^ Ao sábio no coração chamar-se-á de entendido, e aquele que é doce de lábios acrescenta persuasão.

[[v20-16-22]]

^<<v20-16-22,22>>^ Para os seus donos, a perspicácia é fonte de vida; e a disciplina dos tolos é tolice.

[[v20-16-23]]

^<<v20-16-23,23>>^ O coração do sábio faz que a sua boca mostre perspicácia e acrescenta persuasão aos seus lábios.

[[v20-16-24]]

^<<v20-16-24,24>>^ Declarações afáveis são um favo de mel, doces para a alma e uma cura para os ossos.

[[v20-16-25]]

^<<v20-16-25,25>>^ Há um caminho que é reto diante do homem, mas o fim posterior dele são os caminhos da morte.

[[v20-16-26]]

^<<v20-16-26,26>>^ A alma^&#42;1^ do labutador trabalhou arduamente por ele porque a sua boca exerceu muita pressão sobre ele.

[NOTE]
====
. Ou “desejo de alma; almejo”.
====

[[v20-16-27]]

^<<v20-16-27,27>>^ O homem imprestável^&#42;1^ escava o que é mau, e sobre os seus lábios há como que um fogo causticante.

[NOTE]
====
. Lit.: “O homem de belial.” Hebr.: ’ish beli·yá·‛al.
====

[[v20-16-28]]

^<<v20-16-28,28>>^ O homem de intrigas continua a criar contenda e o caluniador separa os que estão familiarizados uns com os outros.

[[v20-16-29]]

^<<v20-16-29,29>>^ O homem de violência seduzirá seu próximo e certamente o fará ir num caminho que não é bom.

[[v20-16-30]]

^<<v20-16-30,30>>^ Ele pisca os olhos para maquinar intrigas. Apertando os lábios, certamente leva a cabo a maldade.

[[v20-16-31]]

^<<v20-16-31,31>>^ As cãs são uma coroa de beleza quando se acham no caminho da justiça.

[[v20-16-32]]

^<<v20-16-32,32>>^ Melhor é o vagaroso em irar-se do que o homem poderoso, e aquele que controla seu espírito, do que aquele que captura uma cidade.

[[v20-16-33]]

^<<v20-16-33,33>>^ A sorte se lança no colo, mas toda decisão por ela é da parte de Jeová.

'''

xref:020-proverbios/020-proverbios-015.adoc#v20-15-0[&#60; Capítulo Anterior] | <<v20-16-0,Topo>> | xref:020-proverbios/020-proverbios-017.adoc#v20-17-0[Próximo Capítulo &#62;]