include::./index.adoc[]

[[v40-8-0]]
=== Mateus, 8
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v40-8-1]]

^<<v40-8-1,1>>^ Tendo ele descido do monte, seguiam-no grandes multidões.

[[v40-8-2]]

^<<v40-8-2,2>>^ E eis que veio um leproso e começou a prestar-lhe homenagem, dizendo: “Senhor, se apenas quiseres, podes tornar-me limpo.”

[[v40-8-3]]

^<<v40-8-3,3>>^ E assim, estendendo a [sua] mão, tocou nele, dizendo: “Eu quero. Torna-te limpo.” E ele ficou imediatamente limpo da lepra.

[[v40-8-4]]

^<<v40-8-4,4>>^ Jesus disse-lhe então: “Cuida de que não digas nada a ninguém, mas vai, mostra-te ao sacerdote e oferece a dádiva designada por Moisés, como testemunho para eles.”

[[v40-8-5]]

^<<v40-8-5,5>>^ Quando entrou em Cafarnaum, veio a ele um oficial do exército,^&#42;1^ suplicando-lhe

[NOTE]
====
. Ou “centurião”, isto é, o comandante de 100 soldados. Lat.: cen·tú·ri·o.
====

[[v40-8-6]]

^<<v40-8-6,6>>^ e dizendo: “Senhor, meu servo está de cama em casa, com paralisia, sendo terrivelmente atormentado.”

[[v40-8-7]]

^<<v40-8-7,7>>^ Disse-lhe ele: “Quando eu chegar lá, irei curá-lo.”

[[v40-8-8]]

^<<v40-8-8,8>>^ O oficial do exército disse, em resposta: “Senhor, eu não sou homem apto para entrares debaixo do meu teto, mas, dize apenas a palavra e meu servo estará curado.

[[v40-8-9]]

^<<v40-8-9,9>>^ Pois eu também sou homem sujeito à autoridade, tendo soldados sob as minhas ordens, e digo a este: ‘Vai!’ e ele vai, e a outro: ‘Vem!’ e ele vem, e ao meu escravo: ‘Faze isto!’ e ele o faz.”

[[v40-8-10]]

^<<v40-8-10,10>>^ Ouvindo isso, Jesus ficou pasmado e disse aos que o seguiam: “Em verdade vos digo: Em ninguém em Israel tenho encontrado tamanha fé.

[[v40-8-11]]

^<<v40-8-11,11>>^ Mas, eu vos digo que muitos virão das regiões orientais e das regiões ocidentais e se recostarão à mesa junto com Abraão, Isaque e Jacó, no reino dos céus;

[[v40-8-12]]

^<<v40-8-12,12>>^ ao passo que os filhos do reino serão lançados na escuridão lá fora. Ali é que haverá o [seu] choro e o ranger^&#42;1^ de [seus] dentes.”

[NOTE]
====
. Ou “rilhar; cerrar”.
====

[[v40-8-13]]

^<<v40-8-13,13>>^ Jesus disse então ao oficial do exército: “Vai. Assim como tem sido a tua fé, assim aconteça para ti.” E o servo sarou naquela hora.

[[v40-8-14]]

^<<v40-8-14,14>>^ E Jesus, entrando na casa de Pedro, viu a sogra deste acamada e atacada de febre.

[[v40-8-15]]

^<<v40-8-15,15>>^ De modo que tocou na mão dela e a febre a abandonou, e ela se levantou e começou a ministrar-lhe.

[[v40-8-16]]

^<<v40-8-16,16>>^ Mas, depois do anoitecer,^&#42;1^ trouxeram-lhe muitas pessoas possessas de demônios; e ele expulsou os espíritos com uma palavra e curou a todos os que passavam mal;

[NOTE]
====
. Isto é, depois do sábado. Veja Mr 1:21-32; Lu 4:31-40.
====

[[v40-8-17]]

^<<v40-8-17,17>>^ para que se cumprisse o que fora falado por intermédio de Isaías, o profeta, dizendo: “Ele mesmo tomou as nossas doenças e levou as nossas moléstias.”

[[v40-8-18]]

^<<v40-8-18,18>>^ Quando Jesus viu uma multidão em volta de si, deu ordem para que partissem para a outra margem.

[[v40-8-19]]

^<<v40-8-19,19>>^ E certo escriba aproximou-se e disse-lhe: “Instrutor, eu te seguirei para onde quer que fores.”

[[v40-8-20]]

^<<v40-8-20,20>>^ Mas Jesus disse-lhe: “As raposas têm covis e as aves do céu têm poleiros, mas o Filho do homem não tem onde deitar a cabeça.”

[[v40-8-21]]

^<<v40-8-21,21>>^ Outro dos discípulos disse-lhe então: “Senhor, permite-me primeiro ir e enterrar meu pai.”

[[v40-8-22]]

^<<v40-8-22,22>>^ Jesus disse-lhe: “Persiste em seguir-me e deixa que os mortos enterrem seus mortos.”

[[v40-8-23]]

^<<v40-8-23,23>>^ E, tendo entrado num barco, seguiram-no seus discípulos.

[[v40-8-24]]

^<<v40-8-24,24>>^ Ora, eis que se levantou uma grande agitação no mar, de modo que o barco estava sendo coberto pelas ondas; ele, porém, estava dormindo.

[[v40-8-25]]

^<<v40-8-25,25>>^ E eles vieram e o acordaram, dizendo: “Senhor, salva-nos, pois estamos prestes a perecer!”

[[v40-8-26]]

^<<v40-8-26,26>>^ Mas ele lhes disse: “Por que sois medrosos, vós os de pouca fé?” Levantando-se, então, censurou os ventos e o mar, e deu-se uma grande calmaria.

[[v40-8-27]]

^<<v40-8-27,27>>^ Os homens ficaram por isso pasmados e disseram: “Que sorte de pessoa é este, que até mesmo os ventos e o mar lhe obedecem?”

[[v40-8-28]]

^<<v40-8-28,28>>^ Quando chegou à outra margem, ao país dos gadarenos,^&#42;1^ vieram-lhe ao encontro dois homens possessos de demônios, saindo dentre^&#42;2^ os túmulos memoriais, extremamente ferozes, de modo que ninguém tinha a coragem de passar por aquela estrada.

[NOTE]
====
. “Ao país dos gerasenos”, em Mr 5:1; Lu 8:26.
. Ou “saindo dos”.
====

[[v40-8-29]]

^<<v40-8-29,29>>^ E eis que bradavam, dizendo: “Que temos nós contigo,^&#42;1^ Filho de Deus? Vieste aqui atormentar-nos antes do tempo designado?”

[NOTE]
====
. “Que temos nós contigo?” Esta é uma expressão idiomática; é uma pergunta de repulsa, indicando objeção. Veja Ap. 7B.
====

[[v40-8-30]]

^<<v40-8-30,30>>^ Ora, bastante longe dali havia uma manada de muitos porcos pastando.

[[v40-8-31]]

^<<v40-8-31,31>>^ Os demônios começaram assim a suplicar-lhe, dizendo: “Se nos expulsares, envia-nos para a manada de porcos.”

[[v40-8-32]]

^<<v40-8-32,32>>^ Concordemente, ele lhes disse: “Ide!” Eles saíram e passaram para os porcos; e eis que toda a manada se precipitou despenhadeiro abaixo, para dentro do mar, e morreu nas águas.

[[v40-8-33]]

^<<v40-8-33,33>>^ Mas os porqueiros fugiram, e, entrando na cidade, relataram tudo, inclusive o caso dos homens possessos de demônios.

[[v40-8-34]]

^<<v40-8-34,34>>^ E eis que toda a cidade saiu e veio ao encontro de Jesus; e, tendo-o visto, instaram muito com ele para que saísse dos seus distritos.

'''

xref:040-mateus/040-mateus-007.adoc#v40-7-0[&#60; Capítulo Anterior] | <<v40-8-0,Topo>> | xref:040-mateus/040-mateus-009.adoc#v40-9-0[Próximo Capítulo &#62;]