include::./index.adoc[]

[[v40-9-0]]
=== Mateus, 9
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v40-9-1]]

^<<v40-9-1,1>>^ Entrando então no barco, passou para a outra margem e entrou na sua própria cidade.

[[v40-9-2]]

^<<v40-9-2,2>>^ E eis que lhe trouxeram um homem paralítico, deitado numa cama. Vendo a fé que tinham, Jesus disse ao paralítico: “Coragem, filho! Teus pecados estão perdoados.”

[[v40-9-3]]

^<<v40-9-3,3>>^ E eis que certos escribas disseram para si mesmos: “Este blasfema.”

[[v40-9-4]]

^<<v40-9-4,4>>^ E Jesus, sabendo os seus pensamentos, disse: “Por que imaginais coisas iníquas nos vossos corações?

[[v40-9-5]]

^<<v40-9-5,5>>^ Por exemplo, o que é mais fácil, dizer: Teus pecados estão perdoados, ou dizer: Levanta-te e anda?

[[v40-9-6]]

^<<v40-9-6,6>>^ No entanto, a fim de que saibais que o Filho do homem tem na terra autoridade para perdoar pecados —”, ele disse então ao paralítico: “Levanta-te, apanha a tua cama e vai para casa.”

[[v40-9-7]]

^<<v40-9-7,7>>^ E ele se levantou e foi para casa.

[[v40-9-8]]

^<<v40-9-8,8>>^ As multidões, ao verem isso, ficaram com medo e glorificaram a Deus, que concedera tal autoridade a homens.

[[v40-9-9]]

^<<v40-9-9,9>>^ A seguir, passando dali para diante, Jesus avistou um homem chamado Mateus, sentado na coletoria, e disse-lhe: “Sê meu seguidor.” Em conseqüência disso, este se levantou e o seguiu.

[[v40-9-10]]

^<<v40-9-10,10>>^ Mais tarde, enquanto estava recostado à mesa, na casa, eis que vieram muitos cobradores de impostos e pecadores, e começaram a recostar-se com Jesus e seus discípulos.

[[v40-9-11]]

^<<v40-9-11,11>>^ Vendo isso, porém, os fariseus começaram a dizer aos discípulos dele: “Por que é que o vosso instrutor come com os cobradores de impostos e os pecadores?”

[[v40-9-12]]

^<<v40-9-12,12>>^ Ouvindo-os, ele disse: “As pessoas com saúde não precisam de médico, mas sim os enfermos.

[[v40-9-13]]

^<<v40-9-13,13>>^ Ide, pois, e aprendei o que significa: ‘Misericórdia quero, e não sacrifício.’ Pois eu não vim chamar os que são justos, mas pecadores.”

[[v40-9-14]]

^<<v40-9-14,14>>^ Vieram então a ele os discípulos de João e perguntaram-lhe: “Por que é que nós e os fariseus praticamos o jejum, mas os teus discípulos não jejuam?”

[[v40-9-15]]

^<<v40-9-15,15>>^ A isto, Jesus lhes disse: “Será que os amigos do noivo^&#42;1^ têm razão para prantear enquanto o noivo está com eles? Mas, virão dias em que o noivo lhes será tirado, e então jejuarão.

[NOTE]
====
. Lit.: “os filhos da câmara nupcial”, isto é, os convidados ao casamento.
====

[[v40-9-16]]

^<<v40-9-16,16>>^ Ninguém costura um remendo de pano não pré-encolhido numa velha roupa exterior; pois a sua plena força o arrancaria da roupa exterior e o rasgão ficaria pior.

[[v40-9-17]]

^<<v40-9-17,17>>^ Tampouco se põe vinho novo em odres velhos; mas, caso o façam, então os odres rebentarão e o vinho se derramará, e os odres ficarão arruinados. Mas, põe-se vinho novo em odres novos, e ambas as coisas ficam preservadas.”

[[v40-9-18]]

^<<v40-9-18,18>>^ Enquanto lhes dizia estas coisas, eis que certo governante, que se havia aproximado, começou a prestar-lhe homenagem, dizendo: “Minha filha, agora, já deve estar morta; mas vem e põe a tua mão sobre ela, e passará a viver.”

[[v40-9-19]]

^<<v40-9-19,19>>^ Jesus, levantando-se, começou a segui-lo; e o mesmo fizeram os seus discípulos.

[[v40-9-20]]

^<<v40-9-20,20>>^ E eis que uma mulher, que já por doze anos padecia dum fluxo de sangue, veio por detrás e tocou na orla^&#42;1^ de sua roupa exterior;

[NOTE]
====
. Ou “bainha; borla”.
====

[[v40-9-21]]

^<<v40-9-21,21>>^ pois dizia para si mesma: “Se eu apenas tocar na sua roupa exterior, ficarei boa.”^&#42;1^

[NOTE]
====
. Ou “serei salva”.
====

[[v40-9-22]]

^<<v40-9-22,22>>^ Jesus, voltando-se e vendo-a, disse: “Coragem, filha! A tua fé te fez ficar boa.”^&#42;1^ E, daquela hora em diante, a mulher ficou boa.

[NOTE]
====
. Ou “te salvou”.
====

[[v40-9-23]]

^<<v40-9-23,23>>^ Chegando então à casa do governante e avistando os flautistas e a multidão em confusão barulhenta,

[[v40-9-24]]

^<<v40-9-24,24>>^ Jesus começou a dizer: “Retirai-vos daqui, pois a menina não morreu, mas está dormindo.” Eles, porém, começaram a rir-se dele desdenhosamente.

[[v40-9-25]]

^<<v40-9-25,25>>^ Assim que a multidão tinha sido mandada para fora, ele entrou e pegou na mão da menina, e ela se levantou.

[[v40-9-26]]

^<<v40-9-26,26>>^ Naturalmente, a notícia disso espalhou-se por toda aquela região.

[[v40-9-27]]

^<<v40-9-27,27>>^ Enquanto Jesus passava adiante, seguiam-no dois cegos, clamando e dizendo: “Tem misericórdia de nós, Filho de Davi.”

[[v40-9-28]]

^<<v40-9-28,28>>^ Tendo ele entrado na casa, dirigiram-se a ele os cegos e Jesus perguntou-lhes: “Tendes fé que eu possa fazer isso?” Responderam-lhe: “Sim, Senhor.”

[[v40-9-29]]

^<<v40-9-29,29>>^ Então tocou nos olhos deles, dizendo: “Aconteça-vos segundo a vossa fé.”

[[v40-9-30]]

^<<v40-9-30,30>>^ E os olhos deles receberam visão. Ainda mais, Jesus advertiu-os severamente, dizendo: “Cuidai de que ninguém venha a saber disso.”

[[v40-9-31]]

^<<v40-9-31,31>>^ Mas eles, uma vez fora, tornaram isso público a respeito dele, em toda aquela região.

[[v40-9-32]]

^<<v40-9-32,32>>^ Ora, enquanto estes saíam, eis que lhe trouxeram um homem mudo, possesso dum demônio;

[[v40-9-33]]

^<<v40-9-33,33>>^ e, tendo sido expulso o demônio, o mudo falou. Bem, as multidões ficaram pasmadas e disseram: “Nunca se viu nada igual em Israel.”

[[v40-9-34]]

^<<v40-9-34,34>>^ Mas os fariseus começaram a dizer: “É pelo governante dos demônios que ele expulsa os demônios.”

[[v40-9-35]]

^<<v40-9-35,35>>^ E Jesus empreendeu uma viagem por todas as cidades e aldeias, ensinando nas sinagogas deles e pregando^&#42;1^ as boas novas do reino, e curando toda sorte de moléstias e toda sorte de padecimentos.

[NOTE]
====
. Ou “proclamando”. Gr.: ke·rýs·son; lat.: praé·di·cans.
====

[[v40-9-36]]

^<<v40-9-36,36>>^ Vendo as multidões, sentia compaixão delas, porque andavam esfoladas^&#42;1^ e empurradas dum lado para outro como ovelhas sem pastor.

[NOTE]
====
. Ou “atormentadas; molestadas”.
====

[[v40-9-37]]

^<<v40-9-37,37>>^ Ele disse então aos seus discípulos: “Sim, a colheita é grande, mas os trabalhadores são poucos.

[[v40-9-38]]

^<<v40-9-38,38>>^ Por isso, rogai ao Senhor da colheita que mande trabalhadores para a sua colheita.”

'''

xref:040-mateus/040-mateus-008.adoc#v40-8-0[&#60; Capítulo Anterior] | <<v40-9-0,Topo>> | xref:040-mateus/040-mateus-010.adoc#v40-10-0[Próximo Capítulo &#62;]