include::./index.adoc[]

[[v40-14-0]]
=== Mateus, 14
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v40-14-1]]

^<<v40-14-1,1>>^ Naquele mesmo tempo, Herodes, o governante distrital,^&#42;1^ ouviu relatos sobre Jesus

[NOTE]
====
. Lit.: “o tetrarca”, o príncipe territorial agindo pelo imperador.
====

[[v40-14-2]]

^<<v40-14-2,2>>^ e disse aos seus servos: “Este é João Batista. Ele foi levantado dentre os mortos, e é por isso que operam nele obras poderosas.”^&#42;1^

[NOTE]
====
. Ou “milagres”.
====

[[v40-14-3]]

^<<v40-14-3,3>>^ Pois Herodes havia mandado prender a João, amarrando-o e lançando-o na prisão, por causa de Herodias, esposa de Filipe, seu irmão.

[[v40-14-4]]

^<<v40-14-4,4>>^ Porque João lhe estivera dizendo: “Não te é lícito tê-la.”

[[v40-14-5]]

^<<v40-14-5,5>>^ No entanto, embora quisesse matá-lo, temia a multidão, pois consideravam-no profeta.

[[v40-14-6]]

^<<v40-14-6,6>>^ Mas, quando se celebrava o aniversário natalício de Herodes, dançou nesta ocasião a filha de Herodias, e ela agradou tanto a Herodes,

[[v40-14-7]]

^<<v40-14-7,7>>^ que ele prometeu com juramento dar-lhe tudo o que pedisse.

[[v40-14-8]]

^<<v40-14-8,8>>^ Ela disse então, sob as instigações de sua mãe: “Dá-me aqui numa travessa a cabeça de João Batista.”

[[v40-14-9]]

^<<v40-14-9,9>>^ O rei, embora contristado, em respeito pelos seus juramentos e pelos que se recostavam com ele, ordenou que lhe fosse entregue;

[[v40-14-10]]

^<<v40-14-10,10>>^ e mandou e fez que João fosse decapitado na prisão.

[[v40-14-11]]

^<<v40-14-11,11>>^ E a cabeça dele foi trazida numa travessa e entregue à donzela, e ela a levou à sua mãe.

[[v40-14-12]]

^<<v40-14-12,12>>^ Por fim, vindo os discípulos dele, removeram o seu cadáver e o enterraram; e vieram relatá-lo a Jesus.

[[v40-14-13]]

^<<v40-14-13,13>>^ Ouvindo isso, Jesus retirou-se dali de barco para um lugar solitário, para isolamento; mas as multidões, chegando a ouvir isso, seguiram-no a pé, vindo das cidades.

[[v40-14-14]]

^<<v40-14-14,14>>^ Saindo ele então, viu uma grande multidão; e teve pena deles e curou os seus doentes.

[[v40-14-15]]

^<<v40-14-15,15>>^ Mas, ao cair a noite, chegaram-se a ele seus discípulos e disseram: “O lugar é solitário e a hora já está bem avançada; despede as multidões, para que possam entrar nas aldeias e comprar para si algo para comer.”

[[v40-14-16]]

^<<v40-14-16,16>>^ No entanto, Jesus disse-lhes: “Não precisam ir embora; dai-lhes vós algo para comer.”

[[v40-14-17]]

^<<v40-14-17,17>>^ Disseram-lhe: “Não temos aqui senão cinco pães e dois peixes.”

[[v40-14-18]]

^<<v40-14-18,18>>^ Ele disse: “Trazei-mos aqui.”

[[v40-14-19]]

^<<v40-14-19,19>>^ A seguir, ordenou que as multidões se recostassem na grama, e tomou os cinco pães e os dois peixes, e, olhando para o céu, proferiu uma bênção, e, depois de partir os pães, distribuiu-os entre os discípulos, e os discípulos, por sua vez, entre as multidões.

[[v40-14-20]]

^<<v40-14-20,20>>^ Todos comeram assim e ficaram satisfeitos, e recolheram os pedaços que sobraram, doze cestos cheios.

[[v40-14-21]]

^<<v40-14-21,21>>^ Contudo, os que comeram foram cerca de cinco mil homens, além de mulheres e criancinhas.

[[v40-14-22]]

^<<v40-14-22,22>>^ Daí, sem demora, compeliu os discípulos a entrar no barco e a partir na sua frente para a outra margem, enquanto ele despedia as multidões.

[[v40-14-23]]

^<<v40-14-23,23>>^ Por fim, tendo despedido as multidões, subiu sozinho ao monte para orar. Embora ficasse tarde, estava ali sozinho.

[[v40-14-24]]

^<<v40-14-24,24>>^ O barco já estava então a muitas centenas de metros^&#42;1^ da terra, sendo duramente castigado pelas ondas, porque o vento era contrário.

[NOTE]
====
. Lit.: “muitos estádios”. Um estádio equivalia a um oitavo de milha romana, ou 185 m.
====

[[v40-14-25]]

^<<v40-14-25,25>>^ Mas, no período da quarta vigília^&#42;1^ da noite, foi ter com eles andando sobre o mar.

[NOTE]
====
. A última vigília (de aproximadamente as 3 horas da madrugada até o nascer do sol), segundo a divisão gr. e romana da noite. Os judeus tinham três divisões, ou vigílias, segundo Êx 14:24 e Jz 7:19, mas eles posteriormente adotaram o sistema romano de quatro vigílias noturnas. Veja Mr 13:35 n.
====

[[v40-14-26]]

^<<v40-14-26,26>>^ Quando o avistaram andando sobre o mar, os discípulos ficaram perturbados, dizendo: “É uma aparição!” E clamaram de temor.

[[v40-14-27]]

^<<v40-14-27,27>>^ Mas, Jesus falou-lhes imediatamente com as palavras: “Coragem! Sou eu; não temais.”

[[v40-14-28]]

^<<v40-14-28,28>>^ Pedro disse-lhe, em resposta: “Senhor, se és tu, ordena-me ir ter contigo por cima das águas.”

[[v40-14-29]]

^<<v40-14-29,29>>^ Ele disse: “Vem.” Em vista disso, Pedro, descendo do barco, andou por cima das águas e dirigiu-se a Jesus.

[[v40-14-30]]

^<<v40-14-30,30>>^ Mas, olhando para a ventania, ficou com medo, e, começando a afundar-se, clamou: “Senhor, salva-me!”

[[v40-14-31]]

^<<v40-14-31,31>>^ Estendendo imediatamente a mão, Jesus agarrou-o e disse-lhe: “Ó tu, de pouca fé, por que cedeste à dúvida?”

[[v40-14-32]]

^<<v40-14-32,32>>^ E, depois de terem novamente subido ao barco, cessou a ventania.

[[v40-14-33]]

^<<v40-14-33,33>>^ Os que estavam no barco prestaram-lhe então homenagem, dizendo: “Tu és realmente o Filho de Deus.”

[[v40-14-34]]

^<<v40-14-34,34>>^ E fizeram a travessia, desembarcando em Genesaré.

[[v40-14-35]]

^<<v40-14-35,35>>^ Reconhecendo-o os homens daquele lugar, mandaram avisar toda a região circunvizinha, e o povo trouxe-lhe todos os que estavam enfermos.

[[v40-14-36]]

^<<v40-14-36,36>>^ E instavam com ele para que pudessem ao menos tocar a orla de sua roupa exterior; e todos os que a tocaram ficaram completamente bons.

'''

xref:040-mateus/040-mateus-013.adoc#v40-13-0[&#60; Capítulo Anterior] | <<v40-14-0,Topo>> | xref:040-mateus/040-mateus-015.adoc#v40-15-0[Próximo Capítulo &#62;]