include::./index.adoc[]

[[v40-11-0]]
=== Mateus, 11
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v40-11-1]]

^<<v40-11-1,1>>^ Então, quando Jesus tinha terminado de dar instruções aos seus doze discípulos, partiu dali para ensinar e pregar nas cidades deles.

[[v40-11-2]]

^<<v40-11-2,2>>^ João, na cadeia, porém, tendo ouvido [falar] das obras do Cristo, enviou os seus próprios discípulos

[[v40-11-3]]

^<<v40-11-3,3>>^ e mandou dizer-lhe: “És tu Aquele Que Vem, ou devemos esperar alguém diferente?”

[[v40-11-4]]

^<<v40-11-4,4>>^ Jesus disse-lhes, em resposta: “Ide e relatai a João o que ouvis e vedes:

[[v40-11-5]]

^<<v40-11-5,5>>^ Os cegos estão vendo novamente e os coxos estão andando, os leprosos estão sendo purificados e os surdos estão ouvindo, e os mortos estão sendo levantados, e aos pobres estão sendo declaradas as boas novas;

[[v40-11-6]]

^<<v40-11-6,6>>^ e feliz é aquele que não achar em mim nenhuma causa para tropeço.”

[[v40-11-7]]

^<<v40-11-7,7>>^ Enquanto estes estavam em caminho, Jesus principiou a dizer às multidões a respeito de João: “O que fostes ver no ermo? Uma cana jogada pelo vento?

[[v40-11-8]]

^<<v40-11-8,8>>^ O que, pois, fostes ver lá fora? Um homem vestido de roupagem macia? Ora, os que vestem roupagem macia estão nas casas dos reis.

[[v40-11-9]]

^<<v40-11-9,9>>^ Realmente, então, por que fostes lá fora? Para ver um profeta? Sim, eu vos digo, e muito mais do que um profeta.

[[v40-11-10]]

^<<v40-11-10,10>>^ Este é aquele a respeito de quem se escreveu: ‘Eis que eu mesmo envio o meu mensageiro^&#42;1^ diante da tua face, o qual preparará o teu caminho adiante de ti!’

[NOTE]
====
. Ou “anjo”.
====

[[v40-11-11]]

^<<v40-11-11,11>>^ Deveras, eu vos digo: Entre os nascidos de mulheres não se levantou ninguém maior do que João Batista;^&#42;1^ mas aquele que é menor no reino dos céus é maior do que ele.

[NOTE]
====
. Ou “Imersor; Submersor (Mergulhador)”. Gr.: Ba·pti·stoú.
====

[[v40-11-12]]

^<<v40-11-12,12>>^ Mas, desde os dias de João Batista até agora, o reino dos céus é o alvo para o qual os homens avançam impetuosamente, e os que avançam impetuosamente se apoderam dele.

[[v40-11-13]]

^<<v40-11-13,13>>^ Pois todos, os Profetas e a Lei, profetizaram até João;

[[v40-11-14]]

^<<v40-11-14,14>>^ e, se quiserdes aceitá-lo: Ele mesmo é ‘Elias,^&#42;1^ que está destinado a vir’.

[NOTE]
====
. Significando “Meu Deus É Jeová”. J18,22(hebr.): ’E·li·yá·hu. Veja 1Rs 17:1 n. e 2Rs 1:3 n.: “Elias”.
====

[[v40-11-15]]

^<<v40-11-15,15>>^ Escute quem tem ouvidos.

[[v40-11-16]]

^<<v40-11-16,16>>^ “Com quem compararei esta geração? Ela é semelhante às criancinhas sentadas nas feiras, que gritam para seus companheiros de folguedos,

[[v40-11-17]]

^<<v40-11-17,17>>^ dizendo: ‘Nós tocamos flauta para vós, mas não dançastes; lamuriamos, mas não vos batestes em lamento.’

[[v40-11-18]]

^<<v40-11-18,18>>^ Correspondentemente, João não veio nem comendo nem bebendo, contudo dizem: ‘Ele tem demônio’;

[[v40-11-19]]

^<<v40-11-19,19>>^ o Filho do homem veio comendo e bebendo, todavia dizem: ‘Eis um homem comilão e dado a beber vinho, amigo de cobradores de impostos e de pecadores.’ Não obstante, a sabedoria é provada justa pelas suas obras.”

[[v40-11-20]]

^<<v40-11-20,20>>^ Principiou então a censurar as cidades nas quais se realizaram a maioria das suas obras poderosas, porque não se arrependeram:

[[v40-11-21]]

^<<v40-11-21,21>>^ “Ai de ti, Corazim! Ai de ti, Betsaida! Porque se tivessem ocorrido em Tiro e Sídon as obras poderosas que ocorreram em vós, há muito se teriam arrependido em saco e cinzas.

[[v40-11-22]]

^<<v40-11-22,22>>^ Conseqüentemente, eu vos digo: No Dia do Juízo será mais suportável para Tiro e Sídon do que para vós.

[[v40-11-23]]

^<<v40-11-23,23>>^ E tu, Cafarnaum, serás por acaso enaltecida ao céu?^&#42;1^ Até o Hades^&#42;2^ descerás; porque, se as obras poderosas que ocorreram em ti tivessem ocorrido em Sodoma, ela teria permanecido até o dia de hoje.

[NOTE]
====
. Ou: “não serás enaltecida ao céu?”
. “Hades.” Gr.: ᾅδου (haí·dou); J7-14,16-18,22(hebr.): שאול (she’óhl). Veja Ap. 4B.
====

[[v40-11-24]]

^<<v40-11-24,24>>^ Conseqüentemente, eu vos digo: No Dia do Juízo será mais suportável para a terra de Sodoma do que para ti.”^&#42;1^

[NOTE]
====
. “Para ti”, referindo-se a “ti” como a uma cidade.
====

[[v40-11-25]]

^<<v40-11-25,25>>^ Naquela ocasião, Jesus disse, em resposta: “Eu te louvo publicamente, ó Pai, Senhor do céu e da terra, porque escondeste estas coisas dos sábios e dos intelectuais, e as revelaste aos pequeninos.

[[v40-11-26]]

^<<v40-11-26,26>>^ Sim, ó Pai, porque fazer assim veio a ser o modo aprovado por ti.

[[v40-11-27]]

^<<v40-11-27,27>>^ Todas as coisas me foram entregues por meu Pai, e ninguém conhece plenamente o Filho, exceto o Pai, tampouco há quem conheça plenamente o Pai, exceto o Filho e todo aquele a quem o Filho estiver disposto a revelá-lo.

[[v40-11-28]]

^<<v40-11-28,28>>^ Vinde a mim, todos os que estais labutando e que estais sobrecarregados, e eu vos reanimarei.

[[v40-11-29]]

^<<v40-11-29,29>>^ Tomai sobre vós o meu jugo^&#42;1^ e aprendei de mim,^&#42;2^ pois sou de temperamento brando e humilde de coração, e achareis revigoramento para as vossas almas.^&#42;3^

[NOTE]
====
. Ou: “Entrai sob o meu jugo comigo.”
. Ou “tornai-vos meus discípulos”. Veja Jz 7:17.
. Ou “vidas”. Veja Ap. 4A.
====

[[v40-11-30]]

^<<v40-11-30,30>>^ Pois o meu jugo é benévolo e minha carga é leve.”

'''

xref:040-mateus/040-mateus-010.adoc#v40-10-0[&#60; Capítulo Anterior] | <<v40-11-0,Topo>> | xref:040-mateus/040-mateus-012.adoc#v40-12-0[Próximo Capítulo &#62;]