include::./index.adoc[]

[[v40-17-0]]
=== Mateus, 17
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v40-17-1]]

^<<v40-17-1,1>>^ Seis dias depois, Jesus tomou a Pedro, e a Tiago, e a João, irmão deste, e levou-os à parte, a um alto monte.

[[v40-17-2]]

^<<v40-17-2,2>>^ E ele foi transfigurado diante deles, e o seu rosto brilhava como o sol, e a sua roupagem exterior tornou-se brilhante como a luz.

[[v40-17-3]]

^<<v40-17-3,3>>^ E eis que lhes apareceram Moisés e Elias, conversando com ele.

[[v40-17-4]]

^<<v40-17-4,4>>^ Como resposta, Pedro disse a Jesus: “Senhor, é excelente que estejamos aqui. Se desejares, armarei aqui três tendas, uma para ti, e uma para Moisés, e uma para Elias.”

[[v40-17-5]]

^<<v40-17-5,5>>^ Enquanto ele ainda falava, eis que uma nuvem luminosa os encobriu, e eis uma voz vinda da nuvem, dizendo: “Este é meu Filho, o amado, a quem tenho aprovado; escutai-o.”

[[v40-17-6]]

^<<v40-17-6,6>>^ Ouvindo isso, os discípulos prostraram-se com os seus rostos [em terra] e ficaram com muito medo.

[[v40-17-7]]

^<<v40-17-7,7>>^ Jesus aproximou-se, então, e, tocando-os, disse: “Levantai-vos e não temais.”

[[v40-17-8]]

^<<v40-17-8,8>>^ Ao levantarem os olhos, não viram mais ninguém a não ser Jesus sozinho.

[[v40-17-9]]

^<<v40-17-9,9>>^ E, ao descerem do monte, Jesus ordenou-lhes, dizendo: “A ninguém conteis esta visão, até que o Filho do homem seja levantado dentre os mortos.”

[[v40-17-10]]

^<<v40-17-10,10>>^ No entanto, os discípulos fizeram-lhe a pergunta: “Por que dizem então os escribas que Elias tem de vir primeiro?”

[[v40-17-11]]

^<<v40-17-11,11>>^ Em resposta, ele disse: “Elias, de fato, vem e restabelecerá todas as coisas.

[[v40-17-12]]

^<<v40-17-12,12>>^ No entanto, eu vos digo que Elias já veio e não o reconheceram, mas fizeram com ele o que quiseram. Do mesmo modo também o Filho do homem está destinado a sofrer às mãos deles.”

[[v40-17-13]]

^<<v40-17-13,13>>^ Os discípulos perceberam então que lhes falara de João Batista.

[[v40-17-14]]

^<<v40-17-14,14>>^ E, ao se chegarem à multidão, aproximou-se-lhe um homem que se ajoelhou diante dele e disse:

[[v40-17-15]]

^<<v40-17-15,15>>^ “Senhor, tem misericórdia de meu filho, porque ele é epiléptico e está enfermo, pois cai muitas vezes no fogo e muitas vezes na água;

[[v40-17-16]]

^<<v40-17-16,16>>^ e eu o trouxe aos teus discípulos, mas eles não o puderam curar.”

[[v40-17-17]]

^<<v40-17-17,17>>^ Jesus disse, em resposta: “Ó geração sem fé e deturpada, até quando terei de continuar convosco? Até quando terei de suportar-vos? Trazei-mo aqui.”

[[v40-17-18]]

^<<v40-17-18,18>>^ Jesus censurou então o demônio e este saiu dele; e o menino ficou curado daquela hora em diante.

[[v40-17-19]]

^<<v40-17-19,19>>^ Chegando-se então os discípulos a Jesus, em particular, disseram: “Por que é que nós não pudemos expulsá-lo?”

[[v40-17-20]]

^<<v40-17-20,20>>^ Ele lhes disse: “Por terdes pouca fé. Pois, deveras, eu vos digo: Se tiverdes fé do tamanho dum grão de mostarda, direis a este monte: ‘Transfere-te daqui para lá’, e ele se transferirá, e nada vos será impossível.”

[[v40-17-21]]

^<<v40-17-21,21>>^ ^&#42;1^ ——

[NOTE]
====
. א°BSyc,s omitem o v. 21; CDWVgSypArm: “No entanto, esta espécie não sai, exceto por oração e jejum.” (Veja Mr 9:29.)
====

[[v40-17-22]]

^<<v40-17-22,22>>^ Foi quando estavam ajuntados na Galiléia que Jesus lhes disse: “O Filho do homem está destinado a ser traído às mãos dos homens,

[[v40-17-23]]

^<<v40-17-23,23>>^ e o matarão, e no terceiro dia ele será levantado.” Conseqüentemente, ficaram muito contristados.

[[v40-17-24]]

^<<v40-17-24,24>>^ Chegando eles a Cafarnaum, dirigiram-se a Pedro os homens que cobravam as duas dracmas^&#42;1^ [de imposto] e disseram: “Não paga o vosso instrutor as duas dracmas [de imposto]?”

[NOTE]
====
. Lit.: “as dracmas duplas”. Gr.: ta dí·drakh·ma. Veja Ap. 8A.
====

[[v40-17-25]]

^<<v40-17-25,25>>^ Ele disse: “Sim.” No entanto, quando entrou na casa, Jesus adiantou-se-lhe por dizer: “O que achas, Simão? De quem recebem os reis da terra os direitos ou o imposto por cabeça? Dos seus filhos ou dos estranhos?”

[[v40-17-26]]

^<<v40-17-26,26>>^ Quando ele disse: “Dos estranhos”, Jesus disse-lhe: “Realmente, então, os filhos estão isentos de impostos.

[[v40-17-27]]

^<<v40-17-27,27>>^ Mas, para que não os façamos tropeçar, vai ao mar, lança o anzol e toma o primeiro peixe apanhado, e, quando lhe abrires a boca, acharás uma moeda de estáter.^&#42;1^ Leva-a e dá-lha por mim e por ti.”

[NOTE]
====
. “Uma moeda de estáter”, considerada ser a tetradracma. Veja Ap. 8A.
====

'''

xref:040-mateus/040-mateus-016.adoc#v40-16-0[&#60; Capítulo Anterior] | <<v40-17-0,Topo>> | xref:040-mateus/040-mateus-018.adoc#v40-18-0[Próximo Capítulo &#62;]