include::./index.adoc[]

[[v40-28-0]]
=== Mateus, 28
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v40-28-1]]

^<<v40-28-1,1>>^ Depois^&#42;1^ do sábado, quando estava ficando claro, no primeiro dia da semana, Maria Madalena e a outra Maria foram ver o sepulcro.

[NOTE]
====
. “Depois”, J17,18,21,22. Veja a consideração de “Depois do Sábado” no Ap. 7C.
====

[[v40-28-2]]

^<<v40-28-2,2>>^ E eis que tinha havido um grande terremoto; pois o anjo de Jeová^&#42;1^ descera do céu, e, aproximando-se, rolara a pedra [da frente] e estava sentado sobre ela.

[NOTE]
====
. Veja Ap. 1D.
====

[[v40-28-3]]

^<<v40-28-3,3>>^ Sua aparência exterior era como relâmpago e seu vestuário era branco como a neve.

[[v40-28-4]]

^<<v40-28-4,4>>^ Sim, os vigias tremeram de temor dele e ficaram como que mortos.

[[v40-28-5]]

^<<v40-28-5,5>>^ Mas o anjo disse em resposta às mulheres: “Não sejais temerosas, pois eu sei que estais procurando a Jesus, que foi pregado numa estaca.^&#42;1^

[NOTE]
====
. Ou “fixado numa estaca (poste)”. Veja Ap. 5C.
====

[[v40-28-6]]

^<<v40-28-6,6>>^ Ele não está aqui, pois foi levantado, assim como disse. Vinde, vede o lugar onde estava deitado.

[[v40-28-7]]

^<<v40-28-7,7>>^ E ide rapidamente e dizei aos seus discípulos que ele foi levantado dentre os mortos, e eis que vai adiante de vós para a Galiléia; ali o vereis. Eis que eu vo-lo disse.”

[[v40-28-8]]

^<<v40-28-8,8>>^ Deixando assim rapidamente o túmulo memorial, com temor e grande alegria, correram para relatar isso aos discípulos dele.

[[v40-28-9]]

^<<v40-28-9,9>>^ E eis que Jesus foi ao encontro delas e disse: “Bom dia!” Elas aproximaram-se e agarraram-no pelos pés, e prestaram-lhe homenagem.

[[v40-28-10]]

^<<v40-28-10,10>>^ Jesus disse-lhes então: “Não temais! Ide, relatai isso a meus irmãos, a fim de que vão para a Galiléia; e ali me verão.”

[[v40-28-11]]

^<<v40-28-11,11>>^ Enquanto elas estavam em caminho, eis que alguns da guarda foram à cidade e relataram aos principais sacerdotes todas as coisas que tinham acontecido.

[[v40-28-12]]

^<<v40-28-12,12>>^ E, depois de estes se terem ajuntado com os anciãos e terem deliberado, deram aos soldados um número suficiente de moedas de prata

[[v40-28-13]]

^<<v40-28-13,13>>^ e disseram: “Dizei: ‘Seus discípulos vieram de noite e o furtaram, enquanto estávamos dormindo.’

[[v40-28-14]]

^<<v40-28-14,14>>^ E, se isso chegar aos ouvidos do governador, nós [o] persuadiremos e vos livraremos de preocupação.”

[[v40-28-15]]

^<<v40-28-15,15>>^ Assim tomaram as moedas de prata e fizeram como se lhes mandou; e esta palavra se tem espalhado entre os judeus até o dia de hoje.

[[v40-28-16]]

^<<v40-28-16,16>>^ No entanto, os onze discípulos foram para a Galiléia, para o monte que Jesus lhes designara,

[[v40-28-17]]

^<<v40-28-17,17>>^ e quando o viram, prestaram-lhe homenagem, mas alguns^&#42;1^ duvidaram.

[NOTE]
====
. Ou “outros”, como em Mt 26:67.
====

[[v40-28-18]]

^<<v40-28-18,18>>^ E Jesus, aproximando-se, falou-lhes, dizendo: “Foi-me dada toda a autoridade^&#42;1^ no céu e na terra.

[NOTE]
====
. “Autoridade.” Gr.: e·xou·sí·a; lat.: po·té·stas; J18(hebr.): mim·shál.
====

[[v40-28-19]]

^<<v40-28-19,19>>^ Ide, portanto, e fazei discípulos^&#42;1^ de pessoas de todas as nações, batizando-as em^&#42;2^ o nome do Pai, e do Filho, e do espírito santo,

[NOTE]
====
. Ou “fazei aprendizes”. Gr.: ma·the·teú·sa·te.
. Ou “dentro do”.
====

[[v40-28-20]]

^<<v40-28-20,20>>^ ensinando-as a observar todas as coisas que vos ordenei. E eis que estou convosco todos os dias, até à terminação^&#42;1^ do sistema de coisas.”^&#42;2^

[NOTE]
====
. Veja também 24:3 n.: “terminação”.
. Veja 13:39 n.: “coisas”.
====

'''

xref:040-mateus/040-mateus-027.adoc#v40-27-0[&#60; Capítulo Anterior] | <<v40-28-0,Topo>> | xref:041-marcos/041-marcos-001.adoc#v41-1-0[Próximo Capítulo &#62;]