include::./index.adoc[]

[[v40-21-0]]
=== Mateus, 21
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v40-21-1]]

^<<v40-21-1,1>>^ Ora, quando se aproximavam de Jerusalém, e chegaram a Betfagé, no Monte das Oliveiras, Jesus enviou então dois discípulos,

[[v40-21-2]]

^<<v40-21-2,2>>^ dizendo-lhes: “Ide à aldeia que está ao alcance de vossa vista, e logo achareis atada uma jumenta, e um jumentinho com ela; desatai-os e trazei-mos.

[[v40-21-3]]

^<<v40-21-3,3>>^ E, se alguém vos disser alguma coisa, tendes de dizer: ‘O Senhor precisa deles.’ Com isso, ele os enviará imediatamente.”

[[v40-21-4]]

^<<v40-21-4,4>>^ Isto aconteceu realmente para que se cumprisse o que fora falado por intermédio do profeta, que disse:

[[v40-21-5]]

^<<v40-21-5,5>>^ “Dizei à filha de Sião: ‘Eis que o teu Rei está vindo a ti, de temperamento brando e montado num jumento, sim, num jumentinho, descendência dum animal de carga.’”

[[v40-21-6]]

^<<v40-21-6,6>>^ Os discípulos foram então e fizeram conforme Jesus lhes ordenara.

[[v40-21-7]]

^<<v40-21-7,7>>^ E trouxeram a jumenta e seu jumentinho, e colocaram sobre estes as suas roupas exteriores, e ele se sentou nelas.

[[v40-21-8]]

^<<v40-21-8,8>>^ A maior parte da multidão estendeu na estrada as suas roupas exteriores, ao passo que outros cortaram ramos das árvores e os espalhavam pela estrada.

[[v40-21-9]]

^<<v40-21-9,9>>^ Quanto às multidões, os que lhe precediam e os que lhe seguiam clamavam: “Salva, rogamos,^&#42;1^ o Filho de Davi! Bendito é aquele que vem em nome de Jeová!^&#42;2^ Salva-o, rogamos, nas maiores alturas!”^&#42;3^

[NOTE]
====
. Lit.: “Hosana.” Gr.: Ho·san·ná; Vgc(lat.): Ho·sán·na; J1-14,16-18,22(hebr.): Hoh·sha‛·ná’, “Salva, rogamos!”
. Veja Ap. 1D.
. Ou “nos lugares mais altos”.
====

[[v40-21-10]]

^<<v40-21-10,10>>^ Entrando ele então em Jerusalém, a cidade inteira ficou em comoção, dizendo: “Quem é este?”

[[v40-21-11]]

^<<v40-21-11,11>>^ As multidões diziam: “Este é o profeta Jesus, de Nazaré da Galiléia!”

[[v40-21-12]]

^<<v40-21-12,12>>^ E Jesus entrou no templo e lançou fora todos os que vendiam e compravam no templo, e derrubou as mesas dos cambistas e as bancas dos que vendiam pombas.

[[v40-21-13]]

^<<v40-21-13,13>>^ E disse-lhes: “Está escrito: ‘Minha casa será chamada casa de oração’, mas vós fazeis dela um covil de salteadores.”

[[v40-21-14]]

^<<v40-21-14,14>>^ Aproximaram-se dele no templo também cegos e coxos, e ele os curou.

[[v40-21-15]]

^<<v40-21-15,15>>^ Quando os principais sacerdotes e os escribas viram as coisas maravilhosas que ele fazia e os meninos que clamavam no templo e diziam: “Salva, rogamos, o Filho de Davi!” ficaram indignados

[[v40-21-16]]

^<<v40-21-16,16>>^ e disseram-lhe: “Ouves o que estes estão dizendo?” Jesus disse-lhes: “Sim. Nunca lestes o seguinte: ‘Da boca de pequeninos e de crianças de peito forneceste louvor’?”

[[v40-21-17]]

^<<v40-21-17,17>>^ E deixando-os, saiu da cidade para Betânia e passou ali a noite.

[[v40-21-18]]

^<<v40-21-18,18>>^ Ao voltar à cidade de manhã cedo, ficou com fome.

[[v40-21-19]]

^<<v40-21-19,19>>^ E avistando uma figueira à beira da estrada, dirigiu-se a ela; mas, não encontrou nela nada, a não ser folhas, e disse-lhe: “Nunca mais venha de ti fruto algum.” E a figueira secou-se instantaneamente.

[[v40-21-20]]

^<<v40-21-20,20>>^ Mas, quando os discípulos viram isso, admiraram-se, dizendo: “Como é que a figueira se secou instantaneamente?”

[[v40-21-21]]

^<<v40-21-21,21>>^ Em resposta, Jesus disse-lhes: “Deveras, eu vos digo: Se somente tiverdes fé e não duvidardes, não só fareis o que eu fiz à figueira, mas também, se disserdes a este monte: ‘Sê levantado e lançado no mar’, acontecerá isso.

[[v40-21-22]]

^<<v40-21-22,22>>^ E todas as coisas que pedirdes em oração, tendo fé, recebereis.”

[[v40-21-23]]

^<<v40-21-23,23>>^ Ora, tendo ele entrado no templo, chegaram-se a ele os principais sacerdotes e os anciãos dentre o povo, ao estar ele ensinando, e disseram: “Com que autoridade fazes estas coisas? E quem te deu esta autoridade?”

[[v40-21-24]]

^<<v40-21-24,24>>^ Jesus disse-lhes, em resposta: “Também eu vos pergunto uma coisa. Se ma disserdes, também eu vos direi com que autoridade faço estas coisas:

[[v40-21-25]]

^<<v40-21-25,25>>^ O batismo de João, donde se originou? Do céu ou dos homens?” Mas eles começaram a raciocinar entre si mesmos, dizendo: “Se dissermos: ‘Do céu’, ele nos dirá: ‘Então, por que não acreditastes nele?’

[[v40-21-26]]

^<<v40-21-26,26>>^ Se, porém, dissermos: ‘Dos homens’, temos a multidão para temer, porque todos eles consideram João como profeta.”

[[v40-21-27]]

^<<v40-21-27,27>>^ De modo que disseram a Jesus, em resposta: “Não sabemos.” Ele, por sua vez, disse-lhes: “Tampouco eu vos digo com que autoridade faço estas coisas.

[[v40-21-28]]

^<<v40-21-28,28>>^ “Que achais? Um homem tinha dois filhos. Dirigindo-se ao primeiro, disse: ‘Filho, vai trabalhar hoje no vinhedo.’

[[v40-21-29]]

^<<v40-21-29,29>>^ Em resposta, este lhe disse: ‘Irei, senhor’, mas não foi.

[[v40-21-30]]

^<<v40-21-30,30>>^ Dirigindo-se ao segundo, disse-lhe a mesma coisa. Em resposta, este lhe disse: ‘Não irei.’ Depois deplorou isso e foi.

[[v40-21-31]]

^<<v40-21-31,31>>^ Qual dos dois fez a vontade do pai?” Eles disseram: “O último.” Jesus disse-lhes: “Deveras, eu vos digo que os cobradores de impostos e as meretrizes entrarão na frente de vós no reino de Deus.

[[v40-21-32]]

^<<v40-21-32,32>>^ Porque João veio a vós num caminho de justiça, mas vós não acreditastes nele. No entanto, os cobradores de impostos e as meretrizes acreditaram nele, e vós, embora vísseis [isto], não o deplorastes depois, a ponto de acreditardes nele.

[[v40-21-33]]

^<<v40-21-33,33>>^ “Ouvi outra ilustração:^&#42;1^ Havia um homem, dono de casa, que plantou um vinhedo e pôs uma cerca em volta dele, e escavou um lagar, e erigiu uma torre, e o arrendou a lavradores, e foi viajar para fora.

[NOTE]
====
. Ou “parábola”.
====

[[v40-21-34]]

^<<v40-21-34,34>>^ Quando veio a estação dos frutos, mandou seus escravos aos lavradores, para receber os seus frutos.

[[v40-21-35]]

^<<v40-21-35,35>>^ No entanto, os lavradores tomaram os escravos dele, e a um espancaram, a outro mataram, a outro apedrejaram.

[[v40-21-36]]

^<<v40-21-36,36>>^ Mandou novamente outros escravos, mais do que os primeiros, mas fizeram-lhes a mesma coisa.

[[v40-21-37]]

^<<v40-21-37,37>>^ Por fim mandou a eles seu filho, dizendo: ‘Respeitarão o meu filho.’

[[v40-21-38]]

^<<v40-21-38,38>>^ Ao verem o filho, os lavradores disseram entre si: ‘Este é o herdeiro; vinde, matemo-lo e apoderemo-nos da sua herança!’

[[v40-21-39]]

^<<v40-21-39,39>>^ Tomando-o assim, lançaram-no fora do vinhedo e o mataram.

[[v40-21-40]]

^<<v40-21-40,40>>^ Portanto, quando vier o dono do vinhedo, que fará àqueles lavradores?”

[[v40-21-41]]

^<<v40-21-41,41>>^ Disseram-lhe: “Por serem maus, trará sobre eles uma destruição calamitosa e arrendará o vinhedo a outros lavradores que lhe entregarão os frutos quando forem devidos.”

[[v40-21-42]]

^<<v40-21-42,42>>^ Jesus disse-lhes: “Nunca lestes nas Escrituras: ‘A pedra que foi rejeitada pelos construtores é a que se tem tornado a principal pedra angular. Isto procede de Jeová^&#42;1^ e é maravilhoso aos nossos olhos’?

[NOTE]
====
. Veja Ap. 1D.
====

[[v40-21-43]]

^<<v40-21-43,43>>^ É por isso que vos digo: O reino de Deus vos será tirado e será dado a uma nação que produza os seus frutos.

[[v40-21-44]]

^<<v40-21-44,44>>^ Também, quem cair sobre esta pedra, será despedaçado. Quanto àquele sobre quem ela cair, será pulverizado por ela.”

[[v40-21-45]]

^<<v40-21-45,45>>^ Ora, quando os principais sacerdotes e os fariseus ouviram as ilustrações dele, repararam que falava deles.

[[v40-21-46]]

^<<v40-21-46,46>>^ Mas, embora procurassem apoderar-se dele, temiam as multidões, porque estas o consideravam como profeta.

'''

xref:040-mateus/040-mateus-020.adoc#v40-20-0[&#60; Capítulo Anterior] | <<v40-21-0,Topo>> | xref:040-mateus/040-mateus-022.adoc#v40-22-0[Próximo Capítulo &#62;]