include::./index.adoc[]

[[v40-18-0]]
=== Mateus, 18
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v40-18-1]]

^<<v40-18-1,1>>^ Naquela hora, aproximaram-se de Jesus os discípulos e disseram: “Quem é realmente o maior no reino dos céus?”

[[v40-18-2]]

^<<v40-18-2,2>>^ Portanto, chamando a si uma criancinha, colocou-a no meio deles

[[v40-18-3]]

^<<v40-18-3,3>>^ e disse: “Deveras, eu vos digo: A menos que deis meia-volta e vos torneis como criancinhas, de modo algum entrareis no reino dos céus.

[[v40-18-4]]

^<<v40-18-4,4>>^ Por isso, todo aquele que se humilhar, semelhante a esta criancinha, é o que é o maior no reino dos céus;

[[v40-18-5]]

^<<v40-18-5,5>>^ e todo aquele que receber uma de tais criancinhas à base do meu nome, [também] a mim me recebe.

[[v40-18-6]]

^<<v40-18-6,6>>^ Mas, todo aquele que fizer tropeçar a um destes pequenos que têm fé em mim, para este seria mais proveitoso que se lhe pendurasse em volta do pescoço uma mó daquelas que o burro faz girar e que fosse afundado no alto-mar.

[[v40-18-7]]

^<<v40-18-7,7>>^ “Ai do mundo, devido às pedras de tropeço! Naturalmente, é necessário que venham pedras de tropeço, mas ai do homem por meio de quem vem a pedra de tropeço!

[[v40-18-8]]

^<<v40-18-8,8>>^ Se, pois, a tua mão ou o teu pé te faz tropeçar, corta-o e lança-o para longe de ti; é melhor para ti entrares na vida aleijado ou coxo, do que seres lançado com duas mãos ou dois pés no fogo eterno.

[[v40-18-9]]

^<<v40-18-9,9>>^ Também, se o teu olho te faz tropeçar, arranca-o e lança-o para longe de ti; é melhor para ti entrares com um só olho na vida, do que seres com os dois olhos lançado na Geena^&#42;1^ ardente.

[NOTE]
====
. Veja Ap. 4C.
====

[[v40-18-10]]

^<<v40-18-10,10>>^ Cuidai de que não desprezeis a um destes pequenos; pois eu vos digo que os seus anjos no céu sempre observam o rosto de meu Pai,^&#42;1^ que está no céu.

[NOTE]
====
. Ou “sempre têm acesso ao meu Pai”.
====

[[v40-18-11]]

^<<v40-18-11,11>>^ ^&#42;1^ ——

[NOTE]
====
. אBSys omitem isso; DWVgSyc,pArm: “Porque o Filho do homem veio para salvar o que estava perdido.” (Veja Lu 19:10.)
====

[[v40-18-12]]

^<<v40-18-12,12>>^ “Que pensais? Se um certo homem vem a ter cem ovelhas e uma delas se perder, não deixará ele as noventa e nove sobre os montes e irá à procura daquela que se perdeu?

[[v40-18-13]]

^<<v40-18-13,13>>^ E, se por acaso a encontrar, certamente vos digo que se alegrará mais com ela do que com as noventa e nove que não se perderam.

[[v40-18-14]]

^<<v40-18-14,14>>^ Do mesmo modo, não é algo desejável para meu Pai, que está no céu, que pereça um destes pequenos.

[[v40-18-15]]

^<<v40-18-15,15>>^ “Outrossim, se o teu irmão cometer um pecado, vai expor a falta^&#42;1^ dele entre ti e ele só. Se te escutar, ganhaste o teu irmão.

[NOTE]
====
. Lit.: “repreende-o”.
====

[[v40-18-16]]

^<<v40-18-16,16>>^ Mas, se não te escutar, toma contigo mais um ou dois, para que, pela boca de duas ou três testemunhas, todo assunto^&#42;1^ seja estabelecido.^&#42;2^

[NOTE]
====
. Ou “tudo o que é dito”.
. Lit.: “fique de pé”.
====

[[v40-18-17]]

^<<v40-18-17,17>>^ Se não os escutar,^&#42;1^ fala à congregação.^&#42;2^ Se não escutar nem mesmo a congregação, seja ele para ti apenas como homem das nações e como cobrador de impostos.

[NOTE]
====
. Lit.: “recusar ouvir”.
. Ou “à eclésia (assembléia)”. Gr.: tei ek·kle·sí·ai; J17(hebr.): ’el-haq·qa·hál.
====

[[v40-18-18]]

^<<v40-18-18,18>>^ “Deveras, eu vos digo: Todas as coisas que amarrardes na terra serão as coisas amarradas^&#42;1^ no céu, e todas as coisas que soltardes na terra serão as coisas soltas^&#42;2^ no céu.

[NOTE]
====
. Ou “coisas já amarradas”, o particípio passivo perfeito.
. Ou “coisas já soltas”, o particípio passivo perfeito.
====

[[v40-18-19]]

^<<v40-18-19,19>>^ Novamente, deveras vos digo: Se dois de vós, na terra, concordarem em qualquer coisa de importância que solicitarem, ela se realizará para eles devido ao meu Pai no céu.

[[v40-18-20]]

^<<v40-18-20,20>>^ Pois, onde há dois ou três ajuntados em meu nome, ali estou eu no meio deles.”

[[v40-18-21]]

^<<v40-18-21,21>>^ Pedro aproximou-se então e disse-lhe: “Senhor, quantas vezes há de pecar contra mim o meu irmão e eu lhe hei de perdoar? Até sete vezes?”

[[v40-18-22]]

^<<v40-18-22,22>>^ Jesus disse-lhe: “Eu não te digo: Até sete vezes, mas: Até setenta e sete vezes.^&#42;1^

[NOTE]
====
. “Setenta e sete vezes”, em harmonia com Gên 4:24. Lit.: “setenta vezes sete”.
====

[[v40-18-23]]

^<<v40-18-23,23>>^ “É por isso que o reino dos céus se tem tornado semelhante a um homem, um rei, que queria ajustar contas com os seus escravos.

[[v40-18-24]]

^<<v40-18-24,24>>^ Quando começou a ajustá-las, trouxeram-lhe um homem que lhe devia dez mil talentos [= 60.000.000 de denários].^&#42;1^

[NOTE]
====
. Um talento de prata equivalia a 6.000 denários. Veja Ap. 8A.
====

[[v40-18-25]]

^<<v40-18-25,25>>^ Mas, porque não tinha os meios de pagar [isso] de volta, seu amo mandou que ele, e a esposa dele, e os filhos dele, e todas as coisas que tivesse, fossem vendidos e fosse feito o pagamento.

[[v40-18-26]]

^<<v40-18-26,26>>^ Por isso, o escravo prostrou-se e começou a prestar-lhe homenagem, dizendo: ‘Tem paciência comigo, e eu te pagarei tudo de volta.’

[[v40-18-27]]

^<<v40-18-27,27>>^ Penalizado, por causa disso, o amo daquele escravo deixou-o ir e cancelou a sua dívida.^&#42;1^

[NOTE]
====
. Ou “perdoou-lhe a dívida”.
====

[[v40-18-28]]

^<<v40-18-28,28>>^ Mas aquele escravo saiu e achou um dos seus co-escravos, que lhe devia cem denários;^&#42;1^ e, agarrando-o, começou a estrangulá-lo, dizendo: ‘Paga de volta o que deves.’

[NOTE]
====
. Veja Ap. 8A.
====

[[v40-18-29]]

^<<v40-18-29,29>>^ Por isso, seu co-escravo prostrou-se e começou a suplicar-lhe, dizendo: ‘Tem paciência comigo, e eu te pagarei de volta.’

[[v40-18-30]]

^<<v40-18-30,30>>^ No entanto, ele não estava disposto, mas foi e mandou lançá-lo na prisão, até que pagasse de volta o que devia.

[[v40-18-31]]

^<<v40-18-31,31>>^ Portanto, quando seus co-escravos viram o que tinha acontecido, ficaram muito contristados, e foram e esclareceram ao seu amo tudo o que tinha acontecido.

[[v40-18-32]]

^<<v40-18-32,32>>^ O amo dele convocou-o então e disse-lhe: ‘Escravo iníquo, eu te cancelei toda aquela dívida,^&#42;1^ quando me suplicaste.

[NOTE]
====
. Ou “perdoei-te toda aquela dívida”.
====

[[v40-18-33]]

^<<v40-18-33,33>>^ Não devias tu, por tua vez, ter tido misericórdia do teu co-escravo, assim como eu também tive misericórdia de ti?’

[[v40-18-34]]

^<<v40-18-34,34>>^ Com isso, seu amo, furioso, entregou-o aos carcereiros,^&#42;1^ até que pagasse de volta tudo o que devia.

[NOTE]
====
. Ou “aos atormentadores”. Gr.: tois ba·sa·ni·staís; lat.: tor·tó·ri·bus.
====

[[v40-18-35]]

^<<v40-18-35,35>>^ Do mesmo modo lidará também convosco o meu Pai celestial, se não perdoardes de coração cada um ao seu irmão.”

'''

xref:040-mateus/040-mateus-017.adoc#v40-17-0[&#60; Capítulo Anterior] | <<v40-18-0,Topo>> | xref:040-mateus/040-mateus-019.adoc#v40-19-0[Próximo Capítulo &#62;]