include::./index.adoc[]

[[v40-5-0]]
=== Mateus, 5
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v40-5-1]]

^<<v40-5-1,1>>^ Quando viu as multidões, subiu ao monte; e, depois de se assentar, vieram a ele os seus discípulos;

[[v40-5-2]]

^<<v40-5-2,2>>^ e ele abriu a boca e começou a ensiná-los, dizendo:

[[v40-5-3]]

^<<v40-5-3,3>>^ “Felizes^&#42;1^ os cônscios de sua necessidade espiritual,^&#42;2^ porque a eles pertence o reino dos céus.

[NOTE]
====
. “Felizes.” Gr.: Ma·ká·ri·oi; lat.: be·á·ti, que é a base do termo “beatitudes”.
. Ou “os indigentes do espírito”.
====

[[v40-5-4]]

^<<v40-5-4,4>>^ “Felizes os que pranteiam, porque serão consolados.

[[v40-5-5]]

^<<v40-5-5,5>>^ “Felizes os de temperamento brando, porque herdarão a terra.

[[v40-5-6]]

^<<v40-5-6,6>>^ “Felizes os famintos e sedentos da justiça, porque serão saciados.

[[v40-5-7]]

^<<v40-5-7,7>>^ “Felizes os misericordiosos, porque serão tratados com misericórdia.

[[v40-5-8]]

^<<v40-5-8,8>>^ “Felizes os puros de coração, porque verão a Deus.

[[v40-5-9]]

^<<v40-5-9,9>>^ “Felizes os pacíficos,^&#42;1^ porque serão chamados ‘filhos de Deus’.

[NOTE]
====
. Lit.: “pacificadores”. Gr.: ei·re·no·poi·oí.
====

[[v40-5-10]]

^<<v40-5-10,10>>^ “Felizes os que têm sido perseguidos por causa da justiça, porque a eles pertence o reino dos céus.

[[v40-5-11]]

^<<v40-5-11,11>>^ “Felizes sois quando vos vituperarem e perseguirem, e, mentindo, disserem toda sorte de coisas iníquas contra vós, por minha causa.

[[v40-5-12]]

^<<v40-5-12,12>>^ Alegrai-vos e pulai de alegria, porque a vossa recompensa é grande nos céus; pois assim perseguiram os profetas antes de vós.

[[v40-5-13]]

^<<v40-5-13,13>>^ “Vós sois o sal da terra; mas, se o sal perder a sua força, como se lhe restabelecerá a sua salinidade? Não presta mais para nada, senão para ser lançado fora, a fim de ser pisado pelos homens.

[[v40-5-14]]

^<<v40-5-14,14>>^ “Vós sois a luz do mundo. Não se pode esconder uma cidade situada sobre um monte.

[[v40-5-15]]

^<<v40-5-15,15>>^ As pessoas acendem uma lâmpada e a colocam, não debaixo do cesto de medida, mas no velador, e ela brilha sobre todos na casa.

[[v40-5-16]]

^<<v40-5-16,16>>^ Do mesmo modo, deixai brilhar a vossa luz perante os homens, para que vejam as vossas obras excelentes e dêem glória ao vosso Pai, que está nos céus.

[[v40-5-17]]

^<<v40-5-17,17>>^ “Não penseis que vim destruir a Lei ou os Profetas. Não vim destruir, mas cumprir;

[[v40-5-18]]

^<<v40-5-18,18>>^ pois, deveras, eu vos digo que antes passariam o céu e a terra, do que passaria uma só letra menor ou uma só partícula duma letra da Lei sem que tudo se cumprisse.

[[v40-5-19]]

^<<v40-5-19,19>>^ Quem, portanto, violar um destes mínimos mandamentos e ensinar a humanidade neste sentido, será chamado ‘mínimo’ com relação ao reino dos céus. Quanto àquele que os cumprir e ensinar, esse será chamado ‘grande’ com relação ao reino dos céus.

[[v40-5-20]]

^<<v40-5-20,20>>^ Pois eu vos digo que, se a vossa justiça não abundar mais do que a dos escribas e fariseus, de modo algum entrareis no reino dos céus.

[[v40-5-21]]

^<<v40-5-21,21>>^ “Ouvistes que se disse aos dos tempos antigos: ‘Não deves assassinar; mas quem cometer um assassínio terá de prestar contas ao tribunal de justiça.’

[[v40-5-22]]

^<<v40-5-22,22>>^ No entanto, digo-vos que todo aquele que continuar furioso com seu irmão terá de prestar contas ao tribunal de justiça; mas, quem se dirigir a seu irmão com uma palavra imprópria de desprezo^&#42;1^ terá de prestar contas ao Supremo Tribunal;^&#42;2^ ao passo que quem disser: ‘Tolo desprezível!’, estará sujeito à Geena^&#42;3^ ardente.

[NOTE]
====
. “Uma palavra imprópria de desprezo.” Gr.: Rha·ká; J17, Re·qá’, palavra aram. de desprezo.
. Ou “Sinédrio”.
. “Geena.” Gr.: γέενναν (gé·en·nan); J1-14,16-18(hebr.): גיהנם (geh·hin·nóm, “vale de Hinom”). Era o lugar onde se queimava o lixo fora de Jerusalém. Veja Ap. 4C.
====

[[v40-5-23]]

^<<v40-5-23,23>>^ “Se tu, pois, trouxeres a tua dádiva ao altar e ali te lembrares de que o teu irmão tem algo contra ti,

[[v40-5-24]]

^<<v40-5-24,24>>^ deixa a tua dádiva ali na frente do altar e vai; faze primeiro as pazes com o teu irmão, e então, tendo voltado, oferece a tua dádiva.

[[v40-5-25]]

^<<v40-5-25,25>>^ “Resolve prontamente os assuntos com aquele que se queixa de ti em juízo, enquanto ainda estás com ele em caminho para lá, para que, de algum modo, o queixoso não te entregue ao juiz, e o juiz, ao oficial de justiça, e sejas lançado na prisão.

[[v40-5-26]]

^<<v40-5-26,26>>^ Eu te digo categoricamente: Certamente não sairás dali até pagares a última moeda de pouco valor.^&#42;1^

[NOTE]
====
. Lit.: “o último quadrante”; a sexagésima quarta parte dum denário. Veja Ap. 8A.
====

[[v40-5-27]]

^<<v40-5-27,27>>^ “Ouvistes que se disse: ‘Não deves cometer adultério.’

[[v40-5-28]]

^<<v40-5-28,28>>^ Mas eu vos digo que todo aquele que persiste em olhar para uma mulher, a ponto de ter paixão por ela, já cometeu no coração adultério com ela.

[[v40-5-29]]

^<<v40-5-29,29>>^ Se, pois, aquele olho direito teu te faz tropeçar, arranca-o e lança-o para longe de ti. Porque é mais proveitoso para ti que percas um dos teus membros, do que ser todo o teu corpo lançado na Geena.

[[v40-5-30]]

^<<v40-5-30,30>>^ Também, se a tua mão direita te faz tropeçar, corta-a e lança-a para longe de ti. Porque te é mais proveitoso perder um dos teus membros, do que todo o teu corpo acabar na Geena.

[[v40-5-31]]

^<<v40-5-31,31>>^ “Outrossim, foi dito: ‘Quem se divorciar de sua esposa, dê-lhe certificado de divórcio.’

[[v40-5-32]]

^<<v40-5-32,32>>^ No entanto, eu vos digo que todo aquele que se divorciar de sua esposa, a não ser por causa de fornicação,^&#42;1^ expõe-na ao adultério, e quem se casar com uma mulher divorciada^&#42;2^ comete adultério.^&#42;3^

[NOTE]
====
. “Fornicação.” Gr.: por·neí·as; lat.: for·ni·ca·ti·ó·nis; J17,18,22(hebr.): zenúth. Veja Ap. 5A.
. Ou “solta”.
. Ou “comete infidelidade marital sexual”. Gr.: moi·khá·tai; lat.: a·dúl·te·rat; J22(hebr.): noh·’éf. Veja Ez 16:32 n.
====

[[v40-5-33]]

^<<v40-5-33,33>>^ “Novamente, ouvistes que se disse aos dos tempos antigos: ‘Não deves jurar sem cumprir, mas tens de pagar os teus votos a Jeová.’^&#42;1^

[NOTE]
====
. Veja Ap. 1D.
====

[[v40-5-34]]

^<<v40-5-34,34>>^ No entanto, eu vos digo: Não jureis absolutamente, nem pelo céu, porque é o trono de Deus;

[[v40-5-35]]

^<<v40-5-35,35>>^ nem pela terra, porque é o escabelo de seus pés; nem por Jerusalém, porque é a cidade do grande Rei.

[[v40-5-36]]

^<<v40-5-36,36>>^ Tampouco deves jurar pela tua cabeça, porque não podes tornar nem um só cabelo branco ou preto.

[[v40-5-37]]

^<<v40-5-37,37>>^ Deixai simplesmente que a vossa palavra Sim signifique Sim, e o vosso Não, Não; pois tudo o que for além disso é do iníquo.^&#42;1^

[NOTE]
====
. Ou “daquilo que é iníquo”.
====

[[v40-5-38]]

^<<v40-5-38,38>>^ “Ouvistes que se disse: ‘Olho por olho e dente por dente.’

[[v40-5-39]]

^<<v40-5-39,39>>^ No entanto, eu vos digo: Não resistais àquele que é iníquo;^&#42;1^ mas, a quem te esbofetear a face direita, oferece-lhe também a outra.

[NOTE]
====
. Ou “àquilo que é iníquo”.
====

[[v40-5-40]]

^<<v40-5-40,40>>^ E, se alguém quiser levar-te perante o tribunal para obter posse de tua roupa interior, deixa-o ter também a tua roupa exterior;

[[v40-5-41]]

^<<v40-5-41,41>>^ e, se alguém sob autoridade te obrigar a prestar serviço por mil passos,^&#42;1^ vai com ele dois mil.

[NOTE]
====
. “Mil passos.” Gr.: mí·li·on; lat.: míl·le pás·sus. A milha romana tinha 1.479,5 m. Veja Lu 24:13 n.; Ap. 8A.
====

[[v40-5-42]]

^<<v40-5-42,42>>^ Dá ao que te pede e não te desvies daquele que deseja tomar emprestado de ti [sem juros].

[[v40-5-43]]

^<<v40-5-43,43>>^ “Ouvistes que se disse: ‘Tens de amar o teu próximo e odiar o teu inimigo.’

[[v40-5-44]]

^<<v40-5-44,44>>^ No entanto, eu vos digo: Continuai a amar os vossos inimigos e a orar pelos que vos perseguem;

[[v40-5-45]]

^<<v40-5-45,45>>^ para que mostreis ser filhos de vosso Pai, que está nos céus, visto que ele faz o seu sol levantar-se sobre iníquos e sobre bons, e faz chover sobre justos e sobre injustos.

[[v40-5-46]]

^<<v40-5-46,46>>^ Pois, se amardes aos que vos amam, que recompensa tendes? Não fazem também a mesma coisa os cobradores de impostos?

[[v40-5-47]]

^<<v40-5-47,47>>^ E, se cumprimentardes somente os vossos irmãos, que fazeis de extraordinário? Não fazem também a mesma coisa as pessoas das nações?

[[v40-5-48]]

^<<v40-5-48,48>>^ Concordemente, tendes de ser perfeitos, assim como o vosso Pai celestial é perfeito.^&#42;1^

[NOTE]
====
. Ou “completo”.
====

'''

xref:040-mateus/040-mateus-004.adoc#v40-4-0[&#60; Capítulo Anterior] | <<v40-5-0,Topo>> | xref:040-mateus/040-mateus-006.adoc#v40-6-0[Próximo Capítulo &#62;]