include::./index.adoc[]

[[v40-6-0]]
=== Mateus, 6
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v40-6-1]]

^<<v40-6-1,1>>^ “Tomai muito cuidado em não praticardes a vossa justiça diante dos homens, a fim de serdes observados por eles; do contrário não tereis recompensa junto de vosso Pai que está nos céus.

[[v40-6-2]]

^<<v40-6-2,2>>^ Portanto, quando fizeres dádivas de misericórdia, não toques a trombeta diante de ti, assim como fazem os hipócritas nas sinagogas e nas ruas, para serem glorificados pelos homens. Deveras, eu vos digo: Eles já têm plenamente a sua recompensa.

[[v40-6-3]]

^<<v40-6-3,3>>^ Mas tu, quando fizeres dádivas de misericórdia, não deixes a tua esquerda saber o que a tua direita está fazendo,

[[v40-6-4]]

^<<v40-6-4,4>>^ para que as tuas dádivas de misericórdia fiquem em secreto; então o teu Pai, que está olhando em secreto, te pagará de volta.

[[v40-6-5]]

^<<v40-6-5,5>>^ “Também, quando orardes, não deveis ser como os hipócritas; porque eles gostam de orar em pé nas sinagogas e nas esquinas das ruas largas, para serem vistos pelos homens. Deveras, eu vos digo: Eles já têm plenamente a sua recompensa.

[[v40-6-6]]

^<<v40-6-6,6>>^ Tu, porém, quando orares, entra no teu quarto particular, e, fechando a tua porta, ora a teu Pai que está em secreto; então o teu Pai, que olha em secreto, te pagará de volta.

[[v40-6-7]]

^<<v40-6-7,7>>^ Mas, ao orares, não digas as mesmas coisas vez após vez,^&#42;1^ assim como fazem os das nações, pois imaginam que serão ouvidos por usarem de muitas palavras.

[NOTE]
====
. Ou “não balbucies; não profiras repetições vãs”.
====

[[v40-6-8]]

^<<v40-6-8,8>>^ Portanto, não vos façais semelhantes a eles, porque Deus, vosso Pai, sabe de que coisas necessitais antes de lhe pedirdes.

[[v40-6-9]]

^<<v40-6-9,9>>^ “Portanto, tendes de orar do seguinte modo:
“‘Nosso Pai nos céus, santificado seja^&#42;1^ o teu nome.

[NOTE]
====
. Ou “seja tido por sagrado; seja tratado como santo”. Gr.: ha·gi·a·sthé·to; lat.: sanc·ti·fi·cé·tur; J17,18(hebr.): yith·qad·dásh, “seja santificado”. Veja Êx 29:43 n.: “santificado”.
====

[[v40-6-10]]

^<<v40-6-10,10>>^ Venha o teu reino. Realize-se a tua vontade, como no céu, assim também na terra.

[[v40-6-11]]

^<<v40-6-11,11>>^ Dá-nos hoje o nosso pão para este dia;

[[v40-6-12]]

^<<v40-6-12,12>>^ e perdoa-nos^&#42;1^ as nossas dívidas, assim como nós também temos perdoado aos nossos devedores.

[NOTE]
====
. Lit.: “solta-nos”.
====

[[v40-6-13]]

^<<v40-6-13,13>>^ E não nos leves à tentação, mas livra-nos^&#42;1^ do iníquo.’^&#42;2^

[NOTE]
====
. Ou “socorre-nos”.
. Ou “daquilo que é iníquo”.
====

[[v40-6-14]]

^<<v40-6-14,14>>^ “Pois, se perdoardes aos homens as suas falhas, também o vosso Pai celestial vos perdoará;

[[v40-6-15]]

^<<v40-6-15,15>>^ ao passo que, se não perdoardes aos homens as suas falhas, tampouco o vosso Pai vos perdoará as vossas falhas.

[[v40-6-16]]

^<<v40-6-16,16>>^ “Quando jejuardes, parai de ficar com o rosto triste, como os hipócritas, pois desfiguram os seus rostos para que pareça aos homens que estão jejuando. Deveras, eu vos digo: Eles já têm plenamente a sua recompensa.

[[v40-6-17]]

^<<v40-6-17,17>>^ Mas tu, quando jejuares, unta a tua cabeça e lava o rosto,

[[v40-6-18]]

^<<v40-6-18,18>>^ para que não pareça aos homens que estás jejuando, mas ao teu Pai, que está em secreto; então o teu Pai, que olha em secreto, te recompensará.

[[v40-6-19]]

^<<v40-6-19,19>>^ “Parai de armazenar para vós tesouros na terra, onde a traça e a ferrugem consomem, e onde ladrões arrombam e furtam.

[[v40-6-20]]

^<<v40-6-20,20>>^ Antes, armazenai para vós tesouros no céu, onde nem a traça nem a ferrugem consomem, e onde ladrões não arrombam nem furtam.

[[v40-6-21]]

^<<v40-6-21,21>>^ Pois, onde estiver o teu tesouro, ali estará também o teu coração.

[[v40-6-22]]

^<<v40-6-22,22>>^ “A lâmpada do corpo é o olho. Se, pois, o teu olho for singelo,^&#42;1^ todo o teu corpo será luminoso;

[NOTE]
====
. Ou “sincero; unidirecional; em foco; generoso”.
====

[[v40-6-23]]

^<<v40-6-23,23>>^ mas, se o teu olho for iníquo,^&#42;1^ todo o teu corpo será escuro. Se, na realidade, a luz que está em ti é escuridão, quão grande é essa escuridão!

[NOTE]
====
. Ou “mau; invejoso”.
====

[[v40-6-24]]

^<<v40-6-24,24>>^ “Ninguém pode trabalhar como escravo para dois amos; pois, ou há de odiar um e amar o outro, ou há de apegar-se a um e desprezar o outro. Não podeis trabalhar como escravos para Deus e para as Riquezas.^&#42;1^

[NOTE]
====
. Ou “Mamom”. Gr.: ma·mo·naí, no dativo; J17, 18,22(hebr.): ham·ma·móhn, “o mamom”.
====

[[v40-6-25]]

^<<v40-6-25,25>>^ “Por esta razão eu vos digo: Parai de estar ansiosos pelas vossas almas,^&#42;1^ quanto a que haveis de comer ou quanto a que haveis de beber, ou pelos vossos corpos, quanto a que haveis de vestir. Não significa a alma mais do que o alimento e o corpo mais do que o vestuário?

[NOTE]
====
. Ou “vidas”. Lit.: “alma”. Gr.: psy·kheí, sing. Veja Ap. 4A.
====

[[v40-6-26]]

^<<v40-6-26,26>>^ Observai atentamente as aves do céu, porque elas não semeiam nem ceifam, nem ajuntam em celeiros; contudo, vosso Pai celestial as alimenta. Não valeis vós mais do que elas?

[[v40-6-27]]

^<<v40-6-27,27>>^ Quem de vós, por estar ansioso, pode acrescentar um só côvado à duração de sua vida?

[[v40-6-28]]

^<<v40-6-28,28>>^ Também no assunto do vestuário, por que estais ansiosos? Aprendei uma lição dos lírios do campo, como eles crescem; não labutam nem fiam;

[[v40-6-29]]

^<<v40-6-29,29>>^ mas eu vos digo que nem mesmo Salomão, em toda a sua glória, se vestia como um destes.

[[v40-6-30]]

^<<v40-6-30,30>>^ Se Deus, pois, veste assim a vegetação do campo, que hoje existe e amanhã é lançada no forno, não vestirá ele tanto mais a vós, ó vós os de pouca fé?

[[v40-6-31]]

^<<v40-6-31,31>>^ Portanto, nunca estejais ansiosos, dizendo: ‘Que havemos de comer?’ ou: ‘Que havemos de beber?’ ou: ‘Que havemos de vestir?’

[[v40-6-32]]

^<<v40-6-32,32>>^ Porque todas estas são as coisas pelas quais se empenham avidamente as nações. Pois o vosso Pai celestial sabe que necessitais de todas essas coisas.

[[v40-6-33]]

^<<v40-6-33,33>>^ “Persisti, pois, em buscar^&#42;1^ primeiro o reino e a Sua justiça, e todas estas [outras] coisas vos serão acrescentadas.

[NOTE]
====
. Ou: “Estai buscando.” Gr.: ze·teí·te; a forma do verbo indica uma ação contínua.
====

[[v40-6-34]]

^<<v40-6-34,34>>^ Portanto, nunca estejais ansiosos quanto ao dia seguinte, pois o dia seguinte terá as suas próprias ansiedades. Basta a cada dia o seu próprio mal.

'''

xref:040-mateus/040-mateus-005.adoc#v40-5-0[&#60; Capítulo Anterior] | <<v40-6-0,Topo>> | xref:040-mateus/040-mateus-007.adoc#v40-7-0[Próximo Capítulo &#62;]