include::./index.adoc[]

[[v40-27-0]]
=== Mateus, 27
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v40-27-1]]

^<<v40-27-1,1>>^ Ao amanhecer, todos os principais sacerdotes e os anciãos do povo realizaram uma consulta contra Jesus, a fim de o entregarem à morte.

[[v40-27-2]]

^<<v40-27-2,2>>^ E, depois de o amarrarem, levaram-no e entregaram-no a Pilatos, o governador.

[[v40-27-3]]

^<<v40-27-3,3>>^ Então Judas, que o traiu, vendo que tinha sido condenado, sentiu remorso e devolveu as trinta moedas de prata aos principais sacerdotes e anciãos,

[[v40-27-4]]

^<<v40-27-4,4>>^ dizendo: “Pequei quando traí sangue justo.” Eles disseram: “Que temos nós com isso? Isso é contigo!”

[[v40-27-5]]

^<<v40-27-5,5>>^ De modo que ele lançou as moedas de prata dentro do templo^&#42;1^ e retirou-se, e, tendo saído, enforcou-se.

[NOTE]
====
. Veja 26:61 n.
====

[[v40-27-6]]

^<<v40-27-6,6>>^ Mas os principais sacerdotes tomaram as moedas de prata e disseram: “Não é lícito deitá-las no tesouro sagrado, porque são o preço de sangue.”

[[v40-27-7]]

^<<v40-27-7,7>>^ Depois de se consultarem entre si, compraram com elas o campo do oleiro, para enterrar os estranhos.

[[v40-27-8]]

^<<v40-27-8,8>>^ Aquele campo veio por isso a ser chamado de “Campo de Sangue”, até o dia de hoje.

[[v40-27-9]]

^<<v40-27-9,9>>^ Cumpriu-se assim aquilo que fora falado por intermédio de Jeremias,^&#42;1^ o profeta, que disse: “E tomaram^&#42;2^ as trinta moedas de prata, o preço do homem com que foi avaliado, daquele a quem alguns dos filhos de Israel puseram um preço,

[NOTE]
====
. “Jeremias”, אAB; Syh(margem): “Zacarias”; Syp,s omitem isso.
. “Tomaram”, AB; אSyh,p,s: “tomei”.
====

[[v40-27-10]]

^<<v40-27-10,10>>^ e deram-nas^&#42;1^ pelo campo do oleiro, segundo o que Jeová^&#42;2^ me tinha ordenado.”

[NOTE]
====
. “Deram-nas”, AcB°CItVg; אBcWSyh,p,s: “dei-as”.
. Veja Ap. 1D.
====

[[v40-27-11]]

^<<v40-27-11,11>>^ Jesus estava então perante o governador; e o governador fez-lhe a pergunta: “És tu o rei dos judeus?” Jesus replicou: “Tu mesmo [o] dizes.”

[[v40-27-12]]

^<<v40-27-12,12>>^ Mas ele não deu nenhuma resposta enquanto estava sendo acusado pelos principais sacerdotes e anciãos.

[[v40-27-13]]

^<<v40-27-13,13>>^ Pilatos disse-lhe então: “Não ouves quantas coisas testificam contra ti?”

[[v40-27-14]]

^<<v40-27-14,14>>^ Contudo, ele não lhe respondeu, não, nem com uma só palavra, de modo que o governador ficou muito admirado.

[[v40-27-15]]

^<<v40-27-15,15>>^ Ora, de festividade em festividade, era costume do governador livrar para a multidão um preso, aquele a quem desejassem.

[[v40-27-16]]

^<<v40-27-16,16>>^ Naquela mesma ocasião estavam retendo um preso notório, chamado Barrabás.

[[v40-27-17]]

^<<v40-27-17,17>>^ Portanto, quando estavam ajuntados, Pilatos disse-lhes: “A qual deles quereis que eu vos livre, a Barrabás ou a Jesus, o chamado Cristo?”

[[v40-27-18]]

^<<v40-27-18,18>>^ Pois ele se apercebia de que o tinham entregado por inveja.

[[v40-27-19]]

^<<v40-27-19,19>>^ Além disso, enquanto estava sentado na cadeira de juiz, sua esposa mandou dizer-lhe: “Não tenhas nada que ver com esse homem justo,^&#42;1^ pois eu sofri hoje muito, num sonho, por causa dele.”

[NOTE]
====
. Veja Ap. 7B.
====

[[v40-27-20]]

^<<v40-27-20,20>>^ Mas os principais sacerdotes e anciãos persuadiram as multidões a pedir Barrabás e fazer Jesus ser destruído.

[[v40-27-21]]

^<<v40-27-21,21>>^ Então, em resposta, o governador disse-lhes: “A qual dos dois quereis que eu vos livre?” Disseram: “Barrabás.”

[[v40-27-22]]

^<<v40-27-22,22>>^ Pilatos disse-lhes: “O que quereis, então, que eu faça com Jesus, o chamado Cristo?” Todos disseram: “Seja pregado numa estaca!”^&#42;1^

[NOTE]
====
. Ou: “fixado numa estaca (poste)!” Veja Ap. 5C.
====

[[v40-27-23]]

^<<v40-27-23,23>>^ Ele disse: “Por que, o que fez ele de mal?” Todavia, clamaram ainda mais: “Seja pregado numa estaca!”

[[v40-27-24]]

^<<v40-27-24,24>>^ Vendo que nada adiantava, mas, ao contrário, que se criava um alvoroço, Pilatos tomou água e lavou as mãos diante da multidão, dizendo: “Eu sou inocente do sangue deste [homem].^&#42;1^ Isso é convosco.”

[NOTE]
====
. Ou “inocente deste sangue”.
====

[[v40-27-25]]

^<<v40-27-25,25>>^ A isso, todo o povo disse em resposta: “O sangue dele caia sobre nós e sobre os nossos filhos.”

[[v40-27-26]]

^<<v40-27-26,26>>^ Livrou-lhes então Barrabás, porém, mandou que Jesus fosse chicoteado e o entregou para ser pregado numa estaca.

[[v40-27-27]]

^<<v40-27-27,27>>^ Os soldados do governador levaram então Jesus para o palácio do governador e ajuntaram em volta dele todo o corpo de tropa.

[[v40-27-28]]

^<<v40-27-28,28>>^ E, tendo-o despido, puseram sobre ele um manto escarlate,

[[v40-27-29]]

^<<v40-27-29,29>>^ e trançaram uma coroa de espinhos e a puseram na cabeça dele, e [puseram] uma cana na sua direita. E, ajoelhando-se diante dele, divertiam-se às custas dele, dizendo: “Bom dia, ó Rei dos judeus!”

[[v40-27-30]]

^<<v40-27-30,30>>^ E, cuspindo nele, tomaram a cana e começaram a bater-lhe na cabeça.

[[v40-27-31]]

^<<v40-27-31,31>>^ Por fim, tendo-se divertido às custas dele, tiraram o manto e puseram nele sua roupagem exterior, e o levaram para ser pregado numa estaca.

[[v40-27-32]]

^<<v40-27-32,32>>^ Saindo, encontraram um nativo de Cirene, de nome Simão. A este homem obrigaram a prestar serviço por levar a sua estaca de tortura.

[[v40-27-33]]

^<<v40-27-33,33>>^ E, quando chegaram ao lugar chamado Gólgota,^&#42;1^ que quer dizer Lugar da Caveira,^&#42;2^

[NOTE]
====
. “Gólgota.” Gr.: Gol·go·thá; lat.: Gól·go·tha; J17,18(hebr.): Gol·gol·tá’.
. “Lugar da Caveira.” Gr.: Kra·ní·ou Tó·pos; lat.: Cal·vá·ri·ae ló·cus; J17(hebr.): meqóhm Gul·gó·leth.
====

[[v40-27-34]]

^<<v40-27-34,34>>^ deram-lhe a beber vinho misturado com fel; mas ele, depois de prová-lo, recusou-se a beber.

[[v40-27-35]]

^<<v40-27-35,35>>^ Tendo-o pregado numa estaca, distribuíram a sua roupagem exterior por lançar sortes,

[[v40-27-36]]

^<<v40-27-36,36>>^ e, sentados, vigiavam sobre ele ali.

[[v40-27-37]]

^<<v40-27-37,37>>^ Também puseram por cima de sua cabeça a acusação contra ele, por escrito: “Este é Jesus, o Rei dos judeus.”

[[v40-27-38]]

^<<v40-27-38,38>>^ Dois salteadores foram então com ele pregados em estacas, um à sua direita e outro à sua esquerda.

[[v40-27-39]]

^<<v40-27-39,39>>^ Os que passavam começaram assim a falar dele de modo ultrajante, sacudindo a cabeça

[[v40-27-40]]

^<<v40-27-40,40>>^ e dizendo: “Ó tu, pretenso derrubador do templo e construtor dele em três dias, salva-te a ti mesmo! Se tu és filho de Deus, desce da estaca de tortura!”

[[v40-27-41]]

^<<v40-27-41,41>>^ Do mesmo modo também os principais sacerdotes, junto com os escribas e os anciãos, começaram a divertir-se às custas dele e a dizer:

[[v40-27-42]]

^<<v40-27-42,42>>^ “A outros ele salvou; a si mesmo não pode salvar! Ele é Rei de Israel; desça agora da estaca de tortura, e nós acreditaremos nele.

[[v40-27-43]]

^<<v40-27-43,43>>^ Depositou a sua confiança em Deus; que Ele o socorra agora, se Ele o quiser, pois este disse: ‘Sou Filho de Deus.’”

[[v40-27-44]]

^<<v40-27-44,44>>^ Do mesmo modo, até os salteadores, que com ele estavam pregados em estacas, começaram a vituperá-lo.

[[v40-27-45]]

^<<v40-27-45,45>>^ Da sexta hora^&#42;1^ em diante, caiu uma escuridão sobre toda aquela terra, até a nona hora.^&#42;2^

[NOTE]
====
. “Sexta hora”, isto é, por volta do meio-dia.
. “Nona hora”, isto é, por volta das 15 horas.
====

[[v40-27-46]]

^<<v40-27-46,46>>^ Por volta da nona hora, Jesus exclamou com voz alta, dizendo: “Eli, Eli, lama sabactâni?”^&#42;1^ isto é: “Deus meu, Deus meu, por que me abandonaste?”

[NOTE]
====
. “Eli, Eli, lama sabactâni?” Veja Sal 22:1 n.: “abandonaste”.
====

[[v40-27-47]]

^<<v40-27-47,47>>^ Ouvindo isso, alguns dos que estavam por ali em pé começaram a dizer: “Este homem está chamando Elias.”

[[v40-27-48]]

^<<v40-27-48,48>>^ E um deles correu imediatamente, e, tomando uma esponja, ensopou-a em vinho acre e a pôs numa cana, dando-lhe de beber.

[[v40-27-49]]

^<<v40-27-49,49>>^ Mas os restantes deles disseram: “Deixa[-o]! Vejamos se Elias vem salvá-lo.” [[Outro homem tomou uma lança e furou-lhe o lado, e saiu sangue e água.]]^&#42;1^

[NOTE]
====
. “Outro homem . . . água”, אBC; ADWItVgSyh,p,sArm omitem isso.
====

[[v40-27-50]]

^<<v40-27-50,50>>^ Novamente, Jesus clamou com alta voz e entregou o [seu] espírito.^&#42;1^

[NOTE]
====
. Ou “deixou de respirar”. Lit.: “soltou o espírito”. Gr.: a·fé·ken to pneú·ma.
====

[[v40-27-51]]

^<<v40-27-51,51>>^ E eis que a cortina do santuário se rasgou em dois, de alto a baixo, e a terra tremeu, e as rochas se fenderam.

[[v40-27-52]]

^<<v40-27-52,52>>^ E abriram-se os túmulos memoriais e muitos corpos dos santos que tinham adormecido foram levantados,

[[v40-27-53]]

^<<v40-27-53,53>>^ (e pessoas,^&#42;1^ saindo dentre os túmulos memoriais depois de ele ter sido levantado, entraram na cidade santa,) e tornaram-se visíveis a muitas pessoas.

[NOTE]
====
. Ou “eles”, não se referindo aos “corpos”.
====

[[v40-27-54]]

^<<v40-27-54,54>>^ Mas o oficial do exército^&#42;1^ e os que com ele vigiavam sobre Jesus, quando viram o terremoto e as coisas que aconteciam, ficaram com muito medo, dizendo: “Certamente este era o Filho de Deus.”^&#42;2^

[NOTE]
====
. Lit.: “o centurião”, isto é, o comandante de 100 soldados.
. Ou “um filho de Deus; um filho de um deus”.
====

[[v40-27-55]]

^<<v40-27-55,55>>^ Além disso, observando de certa distância, havia ali muitas mulheres que tinham acompanhado Jesus desde a Galiléia, para ministrar-lhe;

[[v40-27-56]]

^<<v40-27-56,56>>^ entre estas estava Maria Madalena, também Maria, a mãe de Tiago e Josés,^&#42;1^ e a mãe dos filhos de Zebedeu.

[NOTE]
====
. “Josés”, ABCDcSyh,p; אD°WVgSys: “José”.
====

[[v40-27-57]]

^<<v40-27-57,57>>^ Então, visto que a tarde já estava avançada, veio um homem rico de Arimatéia, de nome José, que também se tinha tornado discípulo de Jesus.

[[v40-27-58]]

^<<v40-27-58,58>>^ Este homem dirigiu-se a Pilatos e pediu o corpo de Jesus. Pilatos ordenou então que lhe fosse entregue.

[[v40-27-59]]

^<<v40-27-59,59>>^ E José tomou o corpo, enrolou-o em puro linho fino

[[v40-27-60]]

^<<v40-27-60,60>>^ e deitou-o no seu novo túmulo memorial, que ele tinha aberto na rocha. E, depois de rolar uma grande pedra à porta do túmulo memorial, partiu.

[[v40-27-61]]

^<<v40-27-61,61>>^ Porém, Maria Madalena e a outra Maria permaneceram ali, sentadas diante do sepulcro.

[[v40-27-62]]

^<<v40-27-62,62>>^ No dia seguinte, que era depois da Preparação, ajuntaram-se perante Pilatos os principais sacerdotes e os fariseus,

[[v40-27-63]]

^<<v40-27-63,63>>^ dizendo: “Senhor, lembramo-nos de que esse impostor dizia, enquanto ainda estava vivo: ‘Depois de três dias eu hei de ser levantado.’

[[v40-27-64]]

^<<v40-27-64,64>>^ Portanto, ordena que o sepulcro seja feito seguro até o terceiro dia, para que não venham os seus discípulos e o furtem, e digam ao povo: ‘Ele foi levantado dentre os mortos!’ e esta última impostura seja pior do que a primeira.”

[[v40-27-65]]

^<<v40-27-65,65>>^ Pilatos disse-lhes: “Tendes uma guarda. Ide fazê-lo tão seguro como sabeis.”

[[v40-27-66]]

^<<v40-27-66,66>>^ De modo que foram e fizeram o sepulcro seguro por selarem a pedra e terem a guarda.

'''

xref:040-mateus/040-mateus-026.adoc#v40-26-0[&#60; Capítulo Anterior] | <<v40-27-0,Topo>> | xref:040-mateus/040-mateus-028.adoc#v40-28-0[Próximo Capítulo &#62;]