include::./index.adoc[]

[[v40-22-0]]
=== Mateus, 22
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v40-22-1]]

^<<v40-22-1,1>>^ Em resposta adicional, Jesus falou-lhes novamente com ilustrações, dizendo:

[[v40-22-2]]

^<<v40-22-2,2>>^ “O reino dos céus tem-se tornado semelhante a um homem, um rei, que fez uma festa de casamento para seu filho.

[[v40-22-3]]

^<<v40-22-3,3>>^ E ele mandou os seus escravos chamar os convidados à festa de casamento, mas não quiseram vir.

[[v40-22-4]]

^<<v40-22-4,4>>^ Mandou novamente outros escravos, dizendo: ‘Dizei aos convidados: “Eis que tenho preparado o meu repasto, meus touros e animais cevados já foram abatidos e todas as coisas estão prontas. Vinde à festa de casamento.”’

[[v40-22-5]]

^<<v40-22-5,5>>^ Mas eles, indiferentes, foram embora, um para o seu próprio campo, outro para o seu negócio comercial;

[[v40-22-6]]

^<<v40-22-6,6>>^ mas os restantes, agarrando os escravos dele, trataram-nos com insolência e os mataram.

[[v40-22-7]]

^<<v40-22-7,7>>^ “O rei, porém, ficou furioso e enviou os seus exércitos, e destruiu aqueles assassinos e queimou a cidade deles.

[[v40-22-8]]

^<<v40-22-8,8>>^ Depois disse aos seus escravos: ‘A festa de casamento, deveras, está pronta, mas os convidados não eram dignos.

[[v40-22-9]]

^<<v40-22-9,9>>^ Ide, portanto, às estradas que saem da cidade e convidai a qualquer^&#42;1^ que achardes para a festa de casamento.’

[NOTE]
====
. Ou “tantos quantos”.
====

[[v40-22-10]]

^<<v40-22-10,10>>^ Concordemente, esses escravos foram às estradas e ajuntaram a todos os que acharam, tanto iníquos como bons; e a sala para as cerimônias do casamento ficou cheia dos que se recostavam à mesa.

[[v40-22-11]]

^<<v40-22-11,11>>^ “Quando o rei entrou para inspecionar os convidados, avistou ali um homem que não vestia a roupa de casamento.

[[v40-22-12]]

^<<v40-22-12,12>>^ Disse-lhe, portanto: ‘Amigo, como entraste aqui sem roupa de casamento?’ Ele ficou sem fala.

[[v40-22-13]]

^<<v40-22-13,13>>^ O rei disse então aos seus servos:^&#42;1^ ‘Amarrai-lhe as mãos e os pés, e lançai-o na escuridão lá fora. Ali é onde haverá o [seu] choro e o ranger^&#42;2^ de [seus] dentes.’

[NOTE]
====
. Ou “aos seus ministros (ajudantes)”. Gr.: tois di·a·kó·nois; lat.: mi·ní·stris; J22(hebr.): lam·sha·rethím.
. Ou “rilhar; cerrar”.
====

[[v40-22-14]]

^<<v40-22-14,14>>^ “Porque há muitos convidados, mas poucos escolhidos.”

[[v40-22-15]]

^<<v40-22-15,15>>^ Os fariseus foram então embora e realizaram uma consulta entre si para o enlaçarem na sua palavra.

[[v40-22-16]]

^<<v40-22-16,16>>^ Mandaram-lhe por isso discípulos seus, junto com partidários de Herodes,^&#42;1^ dizendo: “Instrutor, sabemos que és veraz e que ensinas o caminho de Deus em verdade, e que não te importas com ninguém, pois não olhas para a aparência externa dos homens.

[NOTE]
====
. Ou “com os herodianos”.
====

[[v40-22-17]]

^<<v40-22-17,17>>^ Dize-nos, portanto: Que pensas? É lícito ou não pagar a César^&#42;1^ o imposto por cabeça?”

[NOTE]
====
. Ou “ao Imperador”. Gr.: Kaí·sa·ri; lat.: Caé·sa·ri; J22(hebr.): laq·Qeh·sár.
====

[[v40-22-18]]

^<<v40-22-18,18>>^ Mas Jesus, conhecendo a iniqüidade deles, disse: “Por que me pondes à prova, hipócritas?

[[v40-22-19]]

^<<v40-22-19,19>>^ Mostrai-me a moeda do imposto por cabeça.” Trouxeram-lhe um denário.^&#42;1^

[NOTE]
====
. Veja 20:2 n.
====

[[v40-22-20]]

^<<v40-22-20,20>>^ E ele lhes disse: “De quem é esta imagem^&#42;1^ e inscrição?”

[NOTE]
====
. “Imagem.” Gr.: ei·kón; lat.: i·má·go; J22(hebr.): had·demúth, “a imagem”.
====

[[v40-22-21]]

^<<v40-22-21,21>>^ Disseram: “De César.” Então lhes disse ele: “Portanto, pagai de volta^&#42;1^ a César as coisas de César, mas a Deus as coisas de Deus.”

[NOTE]
====
. Lit.: “Dai de volta.” Gr.: A·pó·do·te; lat.: réd·di·te; J17,22(hebr.): tenú.
====

[[v40-22-22]]

^<<v40-22-22,22>>^ Ora, quando ouviram [isso], ficaram maravilhados, e, deixando-o, foram embora.

[[v40-22-23]]

^<<v40-22-23,23>>^ Naquele dia, os saduceus, que dizem não haver ressurreição,^&#42;1^ chegaram-se a ele e perguntaram-lhe:

[NOTE]
====
. “Ressurreição.” Gr.: a·ná·sta·sin, “levantar-se; erguer-se” (de a·ná, “para cima”, e stá·sis, “estar de pé”); lat.: re·sur·rec·ti·ó·nem; J17(hebr.): tehhi·yáth ham·me·thím, “revivificação dos mortos”.
====

[[v40-22-24]]

^<<v40-22-24,24>>^ “Instrutor, Moisés disse: ‘Se um homem morrer sem filhos, seu irmão tem de tomar a esposa dele em casamento e suscitar descendência para seu irmão.’

[[v40-22-25]]

^<<v40-22-25,25>>^ Ora, havia conosco sete irmãos; e o primeiro casou-se e faleceu, e, não tendo descendência, deixou a sua esposa para seu irmão.

[[v40-22-26]]

^<<v40-22-26,26>>^ Aconteceu do mesmo modo também com o segundo e com o terceiro, até passar por todos os sete.

[[v40-22-27]]

^<<v40-22-27,27>>^ Por último, morreu a mulher.

[[v40-22-28]]

^<<v40-22-28,28>>^ Conseqüentemente, na ressurreição, de qual dos sete será ela esposa? Pois todos a tiveram.”

[[v40-22-29]]

^<<v40-22-29,29>>^ Em resposta, Jesus disse-lhes: “Estais equivocados, porque não conheceis nem as Escrituras, nem o poder de Deus;

[[v40-22-30]]

^<<v40-22-30,30>>^ pois na ressurreição, os homens não se casam, nem são as mulheres dadas em casamento, mas são como os anjos no céu.

[[v40-22-31]]

^<<v40-22-31,31>>^ Quanto à ressurreição dos mortos, não lestes o que vos foi falado por Deus, que disse:

[[v40-22-32]]

^<<v40-22-32,32>>^ ‘Eu sou o Deus de Abraão, e o Deus de Isaque, e o Deus de Jacó’? Ele é o Deus,^&#42;1^ não de mortos, mas de vivos.”

[NOTE]
====
. “Ele é o Deus”, B; J18: “Jeová é Deus.”
====

[[v40-22-33]]

^<<v40-22-33,33>>^ Ouvindo [isso], as multidões ficaram assombradas com o seu ensino.

[[v40-22-34]]

^<<v40-22-34,34>>^ Tendo os fariseus ouvido que ele silenciara os saduceus, ajuntaram-se num só grupo.

[[v40-22-35]]

^<<v40-22-35,35>>^ E um deles, versado na Lei, perguntou para prová-lo:

[[v40-22-36]]

^<<v40-22-36,36>>^ “Instrutor, qual é o maior mandamento na Lei?”

[[v40-22-37]]

^<<v40-22-37,37>>^ Disse-lhe: “‘Tens de amar a Jeová,^&#42;1^ teu Deus, de todo o teu coração, de toda a tua alma e de toda a tua mente.’

[NOTE]
====
. Veja Ap. 1D.
====

[[v40-22-38]]

^<<v40-22-38,38>>^ Este é o maior e primeiro mandamento.

[[v40-22-39]]

^<<v40-22-39,39>>^ O segundo, semelhante a este, é: ‘Tens de amar o teu próximo como a ti mesmo.’

[[v40-22-40]]

^<<v40-22-40,40>>^ Destes dois mandamentos dependem toda a Lei e os Profetas.”

[[v40-22-41]]

^<<v40-22-41,41>>^ Enquanto os fariseus estavam ajuntados, Jesus perguntou-lhes:

[[v40-22-42]]

^<<v40-22-42,42>>^ “Que pensais do Cristo? De quem é ele filho?” Disseram-lhe: “De Davi.”

[[v40-22-43]]

^<<v40-22-43,43>>^ Ele lhes disse: “Como é, então, que Davi, por inspiração,^&#42;1^ lhe chama ‘Senhor’, dizendo:

[NOTE]
====
. Lit.: “no espírito”. Gr.: en pneú·ma·ti; lat.: in spí·ri·tu; J17,18(hebr.): ba·rú·ahh.
====

[[v40-22-44]]

^<<v40-22-44,44>>^ ‘Jeová^&#42;1^ disse ao meu Senhor: “Senta-te à minha direita, até que eu ponha os teus inimigos debaixo dos teus pés”’?

[NOTE]
====
. Veja Ap. 1D.
====

[[v40-22-45]]

^<<v40-22-45,45>>^ Se, portanto, Davi o chama de ‘Senhor’, como é ele seu filho?”

[[v40-22-46]]

^<<v40-22-46,46>>^ E ninguém foi capaz de dizer-lhe uma só palavra em resposta, nem se atreveu alguém, daquele dia em diante, a interrogá-lo mais.

'''

xref:040-mateus/040-mateus-021.adoc#v40-21-0[&#60; Capítulo Anterior] | <<v40-22-0,Topo>> | xref:040-mateus/040-mateus-023.adoc#v40-23-0[Próximo Capítulo &#62;]