include::./index.adoc[]

[[v40-1-0]]
=== Mateus, 1
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v40-1-1]]

^<<v40-1-1,1>>^ O livro da história^&#42;1^ de Jesus Cristo, filho de Davi, filho de Abraão:

[NOTE]
====
. Ou “linhagem; origem”. Gr.: ge·né·se·os, “gênesis”; lat.: ge·ne·ra·ti·ó·nis, “geração”; J17,18(hebr.): toh·ledhóth, “genealogia”. Veja Gên 2:4 n. e Gên 5:1 n.: “história”.
====

[[v40-1-2]]

^<<v40-1-2,2>>^ Abraão tornou-se pai de^&#42;1^ Isaque;
Isaque tornou-se pai de Jacó;
Jacó tornou-se pai de Judá e seus irmãos;

[NOTE]
====
. Lit.: “procriou”. Gr.: e·gén·ne·sen; lat.: gé·nu·it, “gerou”.
====

[[v40-1-3]]

^<<v40-1-3,3>>^ Judá tornou-se pai de Peres e de Zerá por meio de Tamar;
Peres tornou-se pai de Esrom;
Esrom tornou-se pai de Rão;

[[v40-1-4]]

^<<v40-1-4,4>>^ Rão tornou-se pai de Aminadabe;
Aminadabe tornou-se pai de Nasom;
Nasom tornou-se pai de Salmom;

[[v40-1-5]]

^<<v40-1-5,5>>^ Salmom tornou-se pai de Boaz por meio de Raabe;
Boaz tornou-se pai de Obede por meio de Rute;
Obede tornou-se pai de Jessé;

[[v40-1-6]]

^<<v40-1-6,6>>^ Jessé tornou-se pai de Davi, o rei.
 Davi tornou-se pai de Salomão por meio da esposa de Urias;^&#42;1^

[NOTE]
====
. Ou “por aquela que havia pertencido a Urias”.
====

[[v40-1-7]]

^<<v40-1-7,7>>^ Salomão tornou-se pai de Roboão;
Roboão tornou-se pai de Abias;
Abias tornou-se pai de Asa;

[[v40-1-8]]

^<<v40-1-8,8>>^ Asa tornou-se pai de Jeosafá;
Jeosafá tornou-se pai de Jeorão;
Jeorão tornou-se pai de^&#42;1^ Uzias;

[NOTE]
====
. WH omite Acazias, Jeoás, Amazias. Mas veja 1Cr 3:11, 12.
====

[[v40-1-9]]

^<<v40-1-9,9>>^ Uzias tornou-se pai de Jotão;
Jotão tornou-se pai de Acaz;
Acaz tornou-se pai de Ezequias;

[[v40-1-10]]

^<<v40-1-10,10>>^ Ezequias tornou-se pai de Manassés;
Manassés tornou-se pai de Amom;
Amom tornou-se pai de Josias;

[[v40-1-11]]

^<<v40-1-11,11>>^ Josias tornou-se pai de Jeconias e seus irmãos, por ocasião da deportação para Babilônia.^&#42;1^

[NOTE]
====
. Gr.: Ba·by·ló·nos; J17,22(hebr.): Ba·vél. Veja 2Rs 17:24 n.
====

[[v40-1-12]]

^<<v40-1-12,12>>^ Depois da deportação para Babilônia, Jeconias tornou-se pai de Sealtiel;
Sealtiel tornou-se pai de Zorobabel;

[[v40-1-13]]

^<<v40-1-13,13>>^ Zorobabel tornou-se pai de Abiúde;
Abiúde tornou-se pai de Eliaquim;
Eliaquim tornou-se pai de Azor;

[[v40-1-14]]

^<<v40-1-14,14>>^ Azor tornou-se pai de Sadoque;
Sadoque tornou-se pai de Aquim;
Aquim tornou-se pai de Eliúde;

[[v40-1-15]]

^<<v40-1-15,15>>^ Eliúde tornou-se pai de Eleazar;
Eleazar tornou-se pai de Matã;
Matã tornou-se pai de Jacó;

[[v40-1-16]]

^<<v40-1-16,16>>^ Jacó tornou-se pai de José, marido de Maria, da qual nasceu Jesus, que é chamado Cristo.

[[v40-1-17]]

^<<v40-1-17,17>>^ Assim, todas as gerações, desde Abraão até Davi, foram quatorze gerações, e desde Davi até à deportação para Babilônia, quatorze gerações, e desde a deportação para Babilônia até ao Cristo, quatorze gerações.

[[v40-1-18]]

^<<v40-1-18,18>>^ Mas, o nascimento de Jesus Cristo deu-se da seguinte maneira: Durante o tempo em que a sua mãe Maria estava prometida em casamento a José, ela foi achada grávida por espírito santo, antes de se unirem.

[[v40-1-19]]

^<<v40-1-19,19>>^ No entanto, José, seu marido, porque era justo e não queria fazer dela um espetáculo público, pretendeu divorciar-se^&#42;1^ dela secretamente.

[NOTE]
====
. Ou “liberá-la”. Lit.: “soltá-la”.
====

[[v40-1-20]]

^<<v40-1-20,20>>^ Mas, depois de ter cogitado estas coisas, eis que lhe apareceu em sonho um anjo de Jeová,^&#42;1^ dizendo: “José, filho de Davi, não tenhas medo de levar para casa Maria, tua esposa, pois aquilo que tem sido gerado nela é por espírito santo.

[NOTE]
====
. “De Jeová.” J3,4,7-14,16-18,22-24,28(hebr.): יהוה (Yeho·wáh); gr.: Κυρίου (Ky·rí·ou), sem o artigo definido: “de Senhor”. The Holy Scriptures, de J. N. Darby, 1920 (correspondendo à Bíblia alemã chamada “Elberfelder Bibel”, 1891), diz numa n. sobre Mt 1:20: “‘Senhor’ sem o artigo, significando, como muitas vezes acontece: ‘Jeová.’” Este é o primeiro de 237 lugares nas Escrituras Gregas Cristãs em que ocorre o nome divino “Jeová” no próprio texto desta tradução. Em adição a isso, ele ocorre 72 vezes nas n., fora do texto propriamente dito. Veja Ap. 1D.
====

[[v40-1-21]]

^<<v40-1-21,21>>^ Ela dará à luz um filho, e terás de dar-lhe o nome de Jesus,^&#42;1^ pois ele salvará o seu povo dos pecados deles.”

[NOTE]
====
. “Jesus.” Gr.: ’Ιησοῦν (I·e·soún); J1-14,16-18,22(hebr.): ישוע (Ye·shú·a‛, “Jesua”, significando “Jeová É Salvação”).
====

[[v40-1-22]]

^<<v40-1-22,22>>^ Tudo isso aconteceu realmente para que se cumprisse o que fora falado por Jeová^&#42;1^ por intermédio do seu profeta, dizendo:

[NOTE]
====
. Veja Ap. 1D.
====

[[v40-1-23]]

^<<v40-1-23,23>>^ “Eis que a virgem^&#42;1^ ficará grávida e dará à luz um filho, e dar-lhe-ão o nome de Emanuel”,^&#42;2^ que quer dizer, traduzido: “Conosco Está Deus.”

[NOTE]
====
. “A virgem.” Gr.: he par·thé·nos; J22(hebr.): ha·‛al·máh.
. Gr.: Em·ma·nou·él; J17,18,22(hebr.): ‛Im·ma·nu·’él.
====

[[v40-1-24]]

^<<v40-1-24,24>>^ José, acordando do sono, fez conforme o anjo de Jeová^&#42;1^ lhe indicara e levou sua esposa para casa.

[NOTE]
====
. Veja Ap. 1D.
====

[[v40-1-25]]

^<<v40-1-25,25>>^ Mas não teve relações com ela^&#42;1^ até ela ter dado à luz um filho; e deu-lhe o nome de Jesus.

[NOTE]
====
. Lit.: “ele não a estava conhecendo”.
====

'''

xref:039-malaquias/039-malaquias-004.adoc#v39-4-0[&#60; Capítulo Anterior] | <<v40-1-0,Topo>> | xref:040-mateus/040-mateus-002.adoc#v40-2-0[Próximo Capítulo &#62;]