include::./index.adoc[]

[[v17-2-0]]
=== Ester, 2
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v17-2-1]]

^<<v17-2-1,1>>^ Depois destas coisas, tendo-se aplacado o furor do Rei Assuero, lembrou-se ele de Vasti e do que ela tinha feito e do que se decidira contra ela.

[[v17-2-2]]

^<<v17-2-2,2>>^ Então disseram os ajudantes do rei, seus ministros: “Procurem-se para o rei moças, virgens, de linda aparência,

[[v17-2-3]]

^<<v17-2-3,3>>^ e encarregue o rei comissários em todos os distritos jurisdicionais do seu domínio real, e sejam reunidas todas as moças, virgens, de linda aparência, em Susã, o castelo, na casa das mulheres a cargo de Hegai, eunuco do rei, guardião das mulheres; e dêem-se-lhes^&#42;1^ as massagens.

[NOTE]
====
. “Dêem-se-lhes.” No hebr., este verbo está no infinitivo absoluto, indefinido quanto ao tempo e impessoal.
====

[[v17-2-4]]

^<<v17-2-4,4>>^ E a moça que agradar aos olhos do rei será rainha em lugar de Vasti.” E a coisa agradava aos olhos do rei, e ele passou a fazer assim.

[[v17-2-5]]

^<<v17-2-5,5>>^ Aconteceu haver em Susã, o castelo, certo homem, judeu, e seu nome era Mordecai, filho de Jair, filho de Simei, filho de Quis, benjaminita,

[[v17-2-6]]

^<<v17-2-6,6>>^ que tinha sido levado ao exílio, de Jerusalém, junto com o povo deportado^&#42;1^ que foi levado ao exílio junto com Jeconias,^&#42;2^ rei de Judá, a quem Nabucodonosor, rei de Babilônia,^&#42;3^ levara ao exílio.

[NOTE]
====
. Ou “o povo exilado”. Hebr.: hag·go·láh.
. “Joaquim” em 2Rs 24:8; em Je 22:24: “Conias”.
. “Babilônia”, LXXVg; MSy: “Babel”.
====

[[v17-2-7]]

^<<v17-2-7,7>>^ E ele veio a ser o tutor de Hadassa,^&#42;1^ isto é, Ester, filha do irmão de seu pai, porque ela não tinha nem pai nem mãe; e a moça era bonita de figura e bela de aparência, e na morte de seu pai e de sua mãe, Mordecai a tomou como sua filha.

[NOTE]
====
. Significando “Murta”. Hebr.: Hadhas·sáh.
====

[[v17-2-8]]

^<<v17-2-8,8>>^ E sucedeu que, quando se ouviram a palavra do rei e a sua lei, e quando muitas moças foram reunidas em Susã, o castelo, a cargo de Hegai, então Ester foi levada à casa do rei, a cargo de Hegai, guardião das mulheres.

[[v17-2-9]]

^<<v17-2-9,9>>^ Ora, a moça agradava aos seus olhos, de modo que ela obteve benevolência^&#42;1^ diante dele e ele se apressou em dar-lhe as suas massagens e seu alimento devido, e a dar-lhe sete moças escolhidas da casa do rei, e passou a transferir tanto a ela como as suas moças ao melhor lugar da casa das mulheres.

[NOTE]
====
. Ou “amor leal”.
====

[[v17-2-10]]

^<<v17-2-10,10>>^ Ester não dera informações sobre o seu povo ou sobre a sua parentela, porque o próprio Mordecai lhe dera ordem de que não o contasse.

[[v17-2-11]]

^<<v17-2-11,11>>^ E Mordecai andava dia após dia diante do pátio da casa das mulheres para saber do bem-estar de Ester e o que se fazia com ela.

[[v17-2-12]]

^<<v17-2-12,12>>^ E chegando a vez de cada moça para entrar até o Rei Assuero, depois de lhe ter acontecido segundo o regulamento das mulheres, por doze meses, pois era assim que se cumpriam gradualmente os dias de seu tratamento por massagens, seis meses com óleo de mirra, e seis meses com óleo de bálsamo, e com as massagens das mulheres;

[[v17-2-13]]

^<<v17-2-13,13>>^ então nestas condições entrava a própria moça até o rei. Dava-se-lhe tudo o que mencionasse, para acompanhá-la da casa das mulheres à casa do rei.

[[v17-2-14]]

^<<v17-2-14,14>>^ Ela mesma entrava à noitinha e ela mesma retornava de manhã à segunda casa das mulheres, a cargo de Saasgaz, eunuco do rei, guardião das concubinas. Não entrava mais até o rei a menos que o rei se tivesse agradado dela e ela fosse chamada por nome.

[[v17-2-15]]

^<<v17-2-15,15>>^ E quando chegou a vez de entrar até o rei, Ester, filha de Abiail, tio de Mordecai, que a tinha tomado como sua filha, ela não solicitou nada senão o que Hegai, eunuco do rei, guardião das mulheres, passou a mencionar (no ínterim Ester ganhara continuamente favor aos olhos de todos os que a viam).

[[v17-2-16]]

^<<v17-2-16,16>>^ Então Ester foi levada ao Rei Assuero, à sua casa real, no décimo mês, isto é, no mês de tebete,^&#42;1^ no sétimo ano do seu reinado.

[NOTE]
====
. Nome pós-exílico do décimo mês do calendário sagrado. Veja Ap. 8B.
====

[[v17-2-17]]

^<<v17-2-17,17>>^ E o rei veio a amar Ester mais do que a todas as outras mulheres, de modo que ela obteve mais favor e benevolência diante dele do que todas as outras virgens. E passou a pôr-lhe o toucado real sobre a cabeça e a fazê-la rainha em lugar de Vasti.

[[v17-2-18]]

^<<v17-2-18,18>>^ E o rei foi dar um grande banquete a todos os seus príncipes e a seus servos, o banquete de Ester; e concedeu anistia aos distritos jurisdicionais, e ele dava presentes segundo os meios do rei.

[[v17-2-19]]

^<<v17-2-19,19>>^ Ora, quando foram reunidas virgens pela segunda vez, Mordecai estava sentado no portão do rei.

[[v17-2-20]]

^<<v17-2-20,20>>^ Ester não contava nada sobre a sua parentela e seu povo, assim como Mordecai lhe ordenara; Ester fazia o que Mordecai dissera, assim como quando viera a estar sob os seus cuidados.

[[v17-2-21]]

^<<v17-2-21,21>>^ Naqueles dias, enquanto Mordecai estava sentado no portão do rei, Bigtã e Teres, dois oficiais da corte do rei, porteiros, ficaram indignados e estavam procurando deitar a mão no Rei Assuero.

[[v17-2-22]]

^<<v17-2-22,22>>^ E Mordecai ficou sabendo da coisa e [a] contou imediatamente a Ester, a rainha. Ester, por sua vez, falou ao rei em nome de Mordecai.

[[v17-2-23]]

^<<v17-2-23,23>>^ De modo que o assunto foi pesquisado e finalmente descoberto, e ambos chegaram a ser pendurados num madeiro;^&#42;1^ depois foi inscrito no livro dos assuntos dos dias perante o rei.

[NOTE]
====
. Ou “lenho”. Lit.: “árvore (madeira)”, M; lat.: pa·tí·bu·lo.
====

'''

xref:017-ester/017-ester-001.adoc#v17-1-0[&#60; Capítulo Anterior] | <<v17-2-0,Topo>> | xref:017-ester/017-ester-003.adoc#v17-3-0[Próximo Capítulo &#62;]