include::./index.adoc[]

[[v17-3-0]]
=== Ester, 3
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v17-3-1]]

^<<v17-3-1,1>>^ Depois destas coisas, o Rei Assuero engrandeceu a Hamã, filho de Hamedata, agagita, e passou a exaltá-lo e a colocar seu trono acima de todos os outros príncipes que estavam com ele.

[[v17-3-2]]

^<<v17-3-2,2>>^ E todos os servos do rei que estavam no portão do rei dobravam-se e prostravam-se diante de Hamã, pois assim tinha ordenado o rei a seu respeito. Mordecai, porém, não se dobrava nem se prostrava.

[[v17-3-3]]

^<<v17-3-3,3>>^ E os servos do rei que estavam no portão do rei começaram a dizer a Mordecai: “Por que te furtas ao mandamento do rei?”

[[v17-3-4]]

^<<v17-3-4,4>>^ E sucedeu que, falando-lhe eles dia após dia e não os escutando ele, contaram-no então a Hamã para ver se os assuntos de Mordecai ficariam de pé; pois contara-lhes que era judeu.

[[v17-3-5]]

^<<v17-3-5,5>>^ Ora, Hamã via que Mordecai não se dobrava nem se prostrava diante dele, e Hamã ficou cheio de furor.

[[v17-3-6]]

^<<v17-3-6,6>>^ Mas era desprezível aos seus olhos deitar a mão só em Mordecai, pois o tinham informado sobre o povo de Mordecai; e Hamã começou a procurar aniquilar todos os judeus que estavam em todo o domínio real de Assuero, o povo de Mordecai.

[[v17-3-7]]

^<<v17-3-7,7>>^ No primeiro mês, que é o mês de nisã,^&#42;1^ no décimo segundo ano do Rei Assuero, alguém lançou Pur,^&#42;2^ isto é, a Sorte, diante de Hamã, de dia em dia e de mês em mês, [até] o décimo segundo, isto é, o mês de adar.^&#42;3^

[NOTE]
====
. Veja Ne 2:1 n.
. “Pur”, significando “Sorte”. “Purim”, pl. hebr., passou a designar a festividade judaica celebrada no 12.º mês do calendário sagrado. Veja Ap. 8B.
. “Adar.” Hebr.: ’Adhár. Este nome do 12.º mês do calendário sagrado, judaico, ocorre somente em Esd 6:15 e oito vezes em Ester. Adar cai em fevereiro e março. Veja Ap. 8B.
====

[[v17-3-8]]

^<<v17-3-8,8>>^ E Hamã passou a dizer ao Rei Assuero: “Há um povo disperso e separado entre os povos em todos os distritos jurisdicionais do teu domínio real; e suas leis são diferentes de todo outro povo e não executam as leis do próprio rei, e não convém ao rei deixá-los ficar.

[[v17-3-9]]

^<<v17-3-9,9>>^ Se parecer bem ao rei, escreva-se que sejam destruídos; e eu pagarei dez mil talentos de prata^&#42;1^ nas mãos dos que fizerem a obra, trazendo-os ao tesouro do rei.”

[NOTE]
====
. Cerca de US$ 77.070.000, com a prata valendo uns US$ 0,22 o g.
====

[[v17-3-10]]

^<<v17-3-10,10>>^ Então o rei tirou da sua própria mão seu anel de sinete e o deu a Hamã, filho de Hamedata, agagita, que mostrava hostilidade para com os judeus.

[[v17-3-11]]

^<<v17-3-11,11>>^ E o rei prosseguiu, dizendo a Hamã: “Dá-se-te a prata, também o povo, para fazer com eles conforme for bom aos teus próprios olhos.”

[[v17-3-12]]

^<<v17-3-12,12>>^ Foram então chamados os secretários do rei, no primeiro mês, no décimo terceiro dia do mesmo, e escreveu-se segundo tudo o que Hamã ordenava aos sátrapas do rei e aos governadores que estavam sobre os diversos distritos jurisdicionais, e aos príncipes dos diversos povos, de cada distrito jurisdicional, no seu próprio estilo de escrita, e a cada povo na sua própria língua; foi escrito em nome do Rei Assuero e foi selado com o anel de sinete do rei.

[[v17-3-13]]

^<<v17-3-13,13>>^ E enviavam-se^&#42;1^ as cartas por meio de correios a todos os distritos jurisdicionais do rei, para aniquilar, matar e destruir todos os judeus, tanto o moço como o velho, pequeninos e mulheres, num só dia, no décimo terceiro [dia] do décimo segundo mês, que é o mês de adar, e para saquear o despojo deles.

[NOTE]
====
. “Enviavam-se.” No hebr., este verbo está no infinitivo absoluto, indefinido quanto ao tempo e impessoal.
====

[[v17-3-14]]

^<<v17-3-14,14>>^ Uma cópia da escrita a ser dada como lei em todos os diversos distritos jurisdicionais estava sendo publicada para todos os povos, [a fim de] que ficassem prontos para aquele dia.

[[v17-3-15]]

^<<v17-3-15,15>>^ Os próprios correios saíram, movidos à velocidade por causa da palavra do rei, e a própria lei foi dada em Susã, o castelo. Quanto ao rei e a Hamã, sentaram-se para beber; mas no que se referia à cidade de Susã, estava em confusão.

'''

xref:017-ester/017-ester-002.adoc#v17-2-0[&#60; Capítulo Anterior] | <<v17-3-0,Topo>> | xref:017-ester/017-ester-004.adoc#v17-4-0[Próximo Capítulo &#62;]