include::./index.adoc[]

[[v17-7-0]]
=== Ester, 7
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v17-7-1]]

^<<v17-7-1,1>>^ O rei e Hamã entraram então para banquetear-se com Ester, a rainha.

[[v17-7-2]]

^<<v17-7-2,2>>^ O rei disse então a Ester também no segundo dia durante o banquete de vinho: “Qual é o teu pedido, ó Ester, a rainha? A ti seja dado. E qual é a tua solicitação? Até a metade do reinado — seja feito!”

[[v17-7-3]]

^<<v17-7-3,3>>^ Então respondeu Ester, a rainha, e disse: “Se eu tiver achado favor aos teus olhos, ó rei, e se parecer bem ao rei, dê-se-me a minha própria alma^&#42;1^ ao meu pedido, e meu povo, à minha solicitação.

[NOTE]
====
. “Minha própria alma (vida).” Hebr.: naf·shí; sir.: nafshi; lat.: á·ni·mam mé·am.
====

[[v17-7-4]]

^<<v17-7-4,4>>^ Pois fomos vendidos, eu e meu povo, para sermos aniquilados, mortos e destruídos. Ora, se tivéssemos sido vendidos apenas como escravos e apenas como servas, eu teria ficado calada. Mas a aflição não convém quando é com dano para o rei.”^&#42;1^

[NOTE]
====
. Ou: “Mas a aflição nem se compara com o dano para o rei.” Vg: “Mas agora, nosso inimigo é alguém cuja crueldade redunda contra o rei.”
====

[[v17-7-5]]

^<<v17-7-5,5>>^ O Rei Assuero disse então, sim, prosseguiu dizendo a Ester, a rainha: “Quem é este, e onde é que está este^&#42;1^ que se afoitou^&#42;2^ a fazer assim?”

[NOTE]
====
. “Este, e onde é que está este?” Parece tratar-se aqui dum acróstico da declaração divina “mostrarei ser”. O acróstico é formado pelas letras finais אהיה (EHYH), e alguns mss. hebr. salientam isso por usarem letras maiúsculas, como segue: הז-יוא הז אהו. Veja Êx 3:14 n.
. Lit.: “que o encheu quanto ao seu coração”. Veja At 5:3 n.
====

[[v17-7-6]]

^<<v17-7-6,6>>^ Ester disse então: “O homem, o adversário e inimigo, é este mau Hamã.”
Quanto a Hamã, ficou apavorado por causa do rei e da rainha.

[[v17-7-7]]

^<<v17-7-7,7>>^ Quanto ao rei, levantou-se no seu furor do banquete de vinho, [indo] ao jardim do palácio; e o próprio Hamã se levantou para fazer um pedido pela sua alma^&#42;1^ a Ester, a rainha, pois viu que se resolvera o mal contra ele^&#42;2^ da parte do rei.

[NOTE]
====
. “Sua alma (vida).” Hebr.: naf·shóh; lat.: á·ni·ma sú·a.
. “Que se resolvera o mal contra ele.” Neste acróstico kI-khol·tháH ’e·láV ha·ra·‛áH (hebr.), o I corresponde ao Y, e o V corresponde ao W. Este parece ser o quarto acróstico do nome divino, יהוה (YHWH), em Ester. É formado pelas letras finais das quatro palavras, lidas da direita para a esquerda em hebr., como segue: ההרע ואלי הכלת–יכ.
====

[[v17-7-8]]

^<<v17-7-8,8>>^ E o próprio rei retornou do jardim do palácio à casa do banquete de vinho; e Hamã tinha caído sobre o leito em que se achava Ester. Conseqüentemente, o rei disse: “Há de se violar também a rainha, estando eu na casa?” A própria palavra saiu da boca do rei, e eles cobriram a face de Hamã.

[[v17-7-9]]

^<<v17-7-9,9>>^ Harbona, um dos oficiais da corte perante o rei, disse então: “Há também o madeiro que Hamã fez para Mordecai, que falou bem referente ao rei, erguido na casa de Hamã — de cinqüenta côvados^&#42;1^ de altura.” Então disse o rei: “Pendurai-o nele.”

[NOTE]
====
. Veja 5:14 n.: “côvados”.
====

[[v17-7-10]]

^<<v17-7-10,10>>^ E passaram a pendurar Hamã no madeiro que tinha preparado para Mordecai; e o furor do rei se aplacou.

'''

xref:017-ester/017-ester-006.adoc#v17-6-0[&#60; Capítulo Anterior] | <<v17-7-0,Topo>> | xref:017-ester/017-ester-008.adoc#v17-8-0[Próximo Capítulo &#62;]