include::./index.adoc[]

[[v17-1-0]]
=== Ester, 1
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v17-1-1]]

^<<v17-1-1,1>>^ Ora, aconteceu nos dias de^&#42;1^ Assuero,^&#42;2^ que é o Assuero que reinava desde a Índia^&#42;3^ até a Etiópia^&#42;4^ [sobre] cento e vinte e sete distritos jurisdicionais,^&#42;5^

[NOTE]
====
. Veja Gên 14:1 n.: “dias de”.
. “Artaxerxes”, LXX. Entende-se tratar-se de Xerxes I, filho de Dario, o Grande (Dario Histaspes).
. “Desde a Índia.” Hebr.: me·Hód·du; gr.: In·di·kés, “[terra] indiana”; sir.: Hudh; lat.: Ín·di·a.
. “Etiópia”, Vg; MSy: “Cus”.
. “Províncias”, Vg; lat.: pro·vín·ci·as.
====

[[v17-1-2]]

^<<v17-1-2,2>>^ [que] naqueles dias, estando o Rei Assuero sentado no seu trono real que se achava em Susã, o castelo,^&#42;1^

[NOTE]
====
. Ou “a fortaleza”.
====

[[v17-1-3]]

^<<v17-1-3,3>>^ no terceiro ano de ele reinar, ele deu um banquete a todos os seus príncipes e seus servos, a força militar da Pérsia e da Média, os nobres e os príncipes dos distritos jurisdicionais diante dele,

[[v17-1-4]]

^<<v17-1-4,4>>^ mostrando-lhes as riquezas do seu glorioso reino, e a honra [e] a beleza da sua grandeza, por muitos dias, cento e oitenta dias.

[[v17-1-5]]

^<<v17-1-5,5>>^ E ao se completarem estes dias, o rei deu um banquete por sete dias a todo o povo que se achava em Susã, o castelo, tanto para o grande como para o pequeno, no pátio do jardim do palácio do rei.

[[v17-1-6]]

^<<v17-1-6,6>>^ Havia linho, fino algodão e pano azul, seguros com cordas de tecido fino, e lã tingida de roxo em argolas de prata, e colunas de mármore, leitos de ouro e de prata sobre um pavimento de pórfiro,^&#42;1^ e de mármore, e de pérola, e de mármore negro.

[NOTE]
====
. Rocha muito dura, amiúde com textura púrpura escura e com cristais de feldspato.
====

[[v17-1-7]]

^<<v17-1-7,7>>^ E fazia-se passar [vinho] para beber^&#42;1^ em vasos de ouro; e os vasos diferiam um do outro, e havia vinho real em grande quantidade, de acordo com os meios do rei.

[NOTE]
====
. “Fazia-se passar vinho para beber.” No hebr., isto é considerado como um verbo que está no infinitivo absoluto, indefinido quanto ao tempo e impessoal.
====

[[v17-1-8]]

^<<v17-1-8,8>>^ Quanto ao tempo de se beber segundo a lei, não havia compulsão, pois era assim que o rei tinha providenciado para todo grande homem dos da sua casa, para fazer segundo o bel-prazer de cada um.

[[v17-1-9]]

^<<v17-1-9,9>>^ Também a própria Vasti, a rainha, deu um banquete às mulheres na casa real que pertencia ao Rei Assuero.^&#42;1^

[NOTE]
====
. “Artaxerxes”, LXX.
====

[[v17-1-10]]

^<<v17-1-10,10>>^ No sétimo dia, quando o coração do rei se sentia bem por causa do vinho, ele disse a Meumã, Bista, Harbona, Bigtá e Abagta, Zetar e Carcas, os sete oficiais da corte que ministravam^&#42;1^ à pessoa do Rei Assuero,

[NOTE]
====
. Lit.: “os ministrantes”. Hebr.: ham·sha·rethím; gr.: tois di·a·kó·nois; lat.: qui mi·ni·strá·bant.
====

[[v17-1-11]]

^<<v17-1-11,11>>^ que trouxessem Vasti, a rainha, no toucado real perante o rei, para mostrar aos povos e aos príncipes a sua lindeza; pois ela era linda de aparência.

[[v17-1-12]]

^<<v17-1-12,12>>^ Mas a Rainha Vasti se negava a vir à palavra do rei [transmitida] por intermédio dos oficiais da corte. Em vista disso, o rei ficou muito indignado e se acendeu a sua ira no seu íntimo.

[[v17-1-13]]

^<<v17-1-13,13>>^ E o rei passou a dizer aos sábios que tinham conhecimento dos tempos (pois assim [vinha] o assunto do rei perante todos os versados em lei e em causas jurídicas,

[[v17-1-14]]

^<<v17-1-14,14>>^ e os mais chegados a ele eram Carsena, Setar, Admata, Társis, Meres, Marsena [e] Memucã, sete príncipes da Pérsia e da Média, que tinham acesso ao rei,^&#42;1^ estando sentados em primeiro lugar no reino):

[NOTE]
====
. Lit.: “viam a face do rei”.
====

[[v17-1-15]]

^<<v17-1-15,15>>^ “Segundo a lei, o que se deve fazer com a Rainha Vasti por ela não ter feito o que foi dito pelo Rei Assuero por meio dos oficiais da corte?”

[[v17-1-16]]

^<<v17-1-16,16>>^ A isto disse Memucã perante o rei e os príncipes: “Não é somente contra o rei que Vasti, a rainha, cometeu falta, mas contra todos os príncipes e contra todos os povos que estão em todos os distritos jurisdicionais do Rei Assuero.

[[v17-1-17]]

^<<v17-1-17,17>>^ Porque o assunto da rainha sairá a todas as esposas, de modo que desprezarão os seus donos^&#42;1^ nos seus próprios olhos ao dizerem: ‘O próprio Rei Assuero disse que se trouxesse Vasti, a rainha, perante ele e ela não entrou.’

[NOTE]
====
. “Seus donos.” Hebr.: ba‛·leh·hén.
====

[[v17-1-18]]

^<<v17-1-18,18>>^ E neste dia, as princesas da Pérsia e da Média, que tiverem ouvido o assunto da rainha, falarão a todos os príncipes do rei, e haverá muito desprezo e indignação.

[[v17-1-19]]

^<<v17-1-19,19>>^ Se parecer bem ao rei, proceda da sua pessoa uma palavra real e seja ela inscrita entre as leis da Pérsia e da Média, para que não passe, que Vasti não pode entrar perante o Rei Assuero; e dê o rei sua realeza a uma companheira dela, uma mulher melhor do que ela.

[[v17-1-20]]

^<<v17-1-20,20>>^ E o decreto emitido pelo rei terá de ser ouvido em todo o seu domínio real (pois ele é vasto) e as próprias esposas, todas, darão^&#42;1^ honra aos seus donos, tanto ao grande como ao pequeno.”

[NOTE]
====
. “Ele . . . e as próprias esposas, todas, darão.” Hi’ Wekhol-Han·na·shím Yit·tenú (hebr.) parece ser um acróstico inverso do Tetragrama, יהוה (YHWH). Sabe-se de três antigos mss. hebr. que apresentam aqui o nome divino em acróstico com letras maiúsculas, como segue: תנוי נשיםהכל־ו יאה. Este é o primeiro de quatro de tais acrósticos do nome “Jeová”, e a Massorá, numa rubrica, ou em letras vermelhas, traz isso à atenção.
====

[[v17-1-21]]

^<<v17-1-21,21>>^ E a coisa agradava aos olhos do rei e dos príncipes, e o rei passou a fazer segundo a palavra de Memucã.

[[v17-1-22]]

^<<v17-1-22,22>>^ De modo que enviou documentos escritos a todos os distritos jurisdicionais do rei, a cada distrito jurisdicional no seu próprio estilo de escrita e a cada povo na sua própria língua, para que cada esposo agisse continuamente como príncipe na sua própria casa e falasse na língua do seu próprio povo.

'''

xref:016-neemias/016-neemias-013.adoc#v16-13-0[&#60; Capítulo Anterior] | <<v17-1-0,Topo>> | xref:017-ester/017-ester-002.adoc#v17-2-0[Próximo Capítulo &#62;]