include::./index.adoc[]

[[v3-26-0]]
=== Levítico, 26
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v3-26-1]]

^<<v3-26-1,1>>^ “‘Não deveis fazer para vós deuses que nada valem^&#42;1^ e não deveis erigir para vós uma imagem esculpida ou uma coluna sagrada, e não deveis pôr alguma pedra como peça de exibição na vossa terra, com o fim de vos curvardes em direção a ela; pois eu sou Jeová, vosso Deus.

[NOTE]
====
. “Fazer um ídolo”, Vg.
====

[[v3-26-2]]

^<<v3-26-2,2>>^ Deveis guardar os meus sábados e ter espanto reverente do meu santuário. Eu sou Jeová.

[[v3-26-3]]

^<<v3-26-3,3>>^ “‘Se continuardes a andar nos meus estatutos e a guardar os meus mandamentos, e deveras os cumprirdes,

[[v3-26-4]]

^<<v3-26-4,4>>^ então darei certamente as vossas chuvadas no seu tempo devido e a terra há de dar a sua produção, e a árvore do campo dará seu fruto.

[[v3-26-5]]

^<<v3-26-5,5>>^ E a vossa debulha há de alcançar a vossa vindima e a vindima alcançará a sementeira; e deveras comereis o vosso pão a fartar e morareis em segurança na vossa terra.

[[v3-26-6]]

^<<v3-26-6,6>>^ E vou colocar a paz no país, e deveras vos deitareis sem que alguém [vos] faça tremer; e vou fazer cessar no país a fera nociva, e não passará espada pela vossa terra.

[[v3-26-7]]

^<<v3-26-7,7>>^ E certamente ireis no encalço dos vossos inimigos e eles hão de cair diante de vós pela espada.

[[v3-26-8]]

^<<v3-26-8,8>>^ E cinco de vós certamente irão no encalço de cem e cem de vós irão no encalço de dez mil, e vossos inimigos hão de cair diante de vós pela espada.

[[v3-26-9]]

^<<v3-26-9,9>>^ “‘E vou virar-me para vós e fazer-vos fecundos, e multiplicar-vos, e vou cumprir meu pacto convosco.

[[v3-26-10]]

^<<v3-26-10,10>>^ E certamente comereis o antigo do ano precedente e trareis para fora o antigo na frente do novo.

[[v3-26-11]]

^<<v3-26-11,11>>^ E hei de pôr meu tabernáculo no vosso meio e minha alma não vos abominará.

[[v3-26-12]]

^<<v3-26-12,12>>^ E deveras andarei no vosso meio e mostrarei ser vosso Deus, e vós, da vossa parte, mostrareis ser meu povo.

[[v3-26-13]]

^<<v3-26-13,13>>^ Eu sou Jeová, vosso Deus, que vos fiz sair da terra do Egito, de atuar como escravos para eles, e passei a quebrar os paus do vosso jugo e a fazer-vos andar eretos.

[[v3-26-14]]

^<<v3-26-14,14>>^ “‘No entanto, se não me escutardes, nem cumprirdes todos estes mandamentos,

[[v3-26-15]]

^<<v3-26-15,15>>^ e se rejeitardes os meus estatutos, e se as vossas almas abominarem as minhas decisões judiciais de modo a não cumprirem todos os meus mandamentos, a ponto de violardes meu pacto,

[[v3-26-16]]

^<<v3-26-16,16>>^ então eu, da minha parte, vos farei o seguinte, e certamente trarei sobre vós como punição a perturbação com tuberculose e a febre ardente, fazendo os olhos falhar e a alma definhar-se. E semeareis simplesmente em vão a vossa semente, visto que os vossos inimigos certamente a comerão.

[[v3-26-17]]

^<<v3-26-17,17>>^ E hei de pôr minha face contra vós e sereis certamente derrotados diante dos vossos inimigos; e os que vos odeiam vos hão de espezinhar, e vós realmente fugireis quando ninguém vos persegue.

[[v3-26-18]]

^<<v3-26-18,18>>^ “‘Porém, se apesar destas coisas não me escutardes, então terei de castigar-vos sete vezes mais^&#42;1^ pelos vossos pecados.

[NOTE]
====
. Ou “sete vezes”, sem referência a qualquer elemento de tempo.
====

[[v3-26-19]]

^<<v3-26-19,19>>^ E terei de destroçar o orgulho da vossa força e fazer os vossos céus como ferro, e a vossa terra como cobre.

[[v3-26-20]]

^<<v3-26-20,20>>^ E vosso poder se gastará simplesmente em vão, visto que a vossa terra não dará sua produção e a árvore da terra não dará seu fruto.

[[v3-26-21]]

^<<v3-26-21,21>>^ “‘Mas, se persistirdes em andar em oposição a mim e em não querer escutar-me, então terei de infligir-vos sete vezes mais golpes segundo os vossos pecados.

[[v3-26-22]]

^<<v3-26-22,22>>^ E vou enviar ao vosso meio as feras do campo e elas certamente vos privarão de filhos, e deceparão os vossos animais domésticos, e reduzirão o vosso número, e vossas estradas ficarão realmente desoladas.

[[v3-26-23]]

^<<v3-26-23,23>>^ “‘Não obstante, se não vos deixardes corrigir por mim com estas coisas e simplesmente tiverdes de andar em oposição a mim,

[[v3-26-24]]

^<<v3-26-24,24>>^ então eu é que terei de andar em oposição a vós; e eu é que terei de golpear-vos sete vezes pelos vossos pecados.

[[v3-26-25]]

^<<v3-26-25,25>>^ E hei de trazer sobre vós uma espada que fará vingança pelo pacto; e deveras vos ajuntareis nas vossas cidades, e eu hei de enviar a pestilência para o vosso meio, e tereis de ser entregues na mão dum inimigo.

[[v3-26-26]]

^<<v3-26-26,26>>^ Quando eu vos tiver quebrado os varais em que se penduram os pães de forma anular,^&#42;1^ então é que dez mulheres cozerão vosso pão em apenas um forno e darão vosso pão de volta pelo peso; e tereis de comer, mas não vos fartareis.

[NOTE]
====
. Lit.: “o varal de pão”.
====

[[v3-26-27]]

^<<v3-26-27,27>>^ “‘Se com isso, porém, não me escutardes e simplesmente tiverdes de andar em oposição a mim,

[[v3-26-28]]

^<<v3-26-28,28>>^ então terei de andar em oposição veemente a vós, e eu é que terei de castigar-vos sete vezes pelos vossos pecados.

[[v3-26-29]]

^<<v3-26-29,29>>^ Assim, tereis de comer a carne de vossos filhos e comereis a carne de vossas filhas.

[[v3-26-30]]

^<<v3-26-30,30>>^ E eu certamente aniquilarei os vossos altos sagrados e deceparei os vossos pedestais-incensários, e deitarei os vossos próprios cadáveres sobre os cadáveres dos vossos ídolos sórdidos; e minha alma deveras vos abominará.

[[v3-26-31]]

^<<v3-26-31,31>>^ E deveras entregarei vossas cidades à espada e farei desolados os vossos santuários,^&#42;1^ e não sentirei os vossos cheiros repousantes.

[NOTE]
====
. “Santuários”, MLXXVg; SamSy e 53 mss. hebr.: “santuário”.
====

[[v3-26-32]]

^<<v3-26-32,32>>^ E eu, da minha parte, vou desolar o país, e vossos inimigos que moram nele olharão simplesmente espantados.

[[v3-26-33]]

^<<v3-26-33,33>>^ E a vós é que espalharei entre as nações e vou desembainhar a espada atrás de vós; e vossa terra terá de tornar-se uma desolação e vossas cidades se tornarão ruínas desoladas.

[[v3-26-34]]

^<<v3-26-34,34>>^ “‘E naquele tempo saldará a terra os seus sábados, todos os dias em que jazer desolada, enquanto estiverdes na terra dos vossos inimigos. Naquele tempo a terra guardará o sábado, visto que tem de saldar os seus sábados.

[[v3-26-35]]

^<<v3-26-35,35>>^ Guardará o sábado todos os dias em que jazer desolada, visto que não guardou o sábado nos vossos sábados quando moráveis nela.

[[v3-26-36]]

^<<v3-26-36,36>>^ “‘Quanto aos remanescentes entre vós, hei de pôr timidez nos seus corações, nas terras dos seus inimigos; e o ruído duma folha [sendo] impelida deveras os afugentará, e fugirão realmente como na fuga diante duma espada e cairão sem que alguém os persiga.

[[v3-26-37]]

^<<v3-26-37,37>>^ E hão de tropeçar uns nos outros como que diante duma espada, sem que alguém os persiga, e não haverá para vós a capacidade de resistir aos vossos inimigos.

[[v3-26-38]]

^<<v3-26-38,38>>^ E tereis de perecer entre as nações e a terra dos vossos inimigos terá de consumir-vos.

[[v3-26-39]]

^<<v3-26-39,39>>^ Quanto aos remanescentes entre vós, apodrecerão por causa do seu erro nas terras dos vossos inimigos. Sim, apodrecerão até mesmo por causa dos erros de seus pais, com eles.

[[v3-26-40]]

^<<v3-26-40,40>>^ E certamente confessarão seu próprio erro e o erro de seus pais na sua infidelidade, quando se comportaram de modo infiel para comigo, sim, mesmo quando andaram em oposição a mim.

[[v3-26-41]]

^<<v3-26-41,41>>^ Eu, da minha parte, porém, passei a andar em oposição a eles e tive de levá-los à terra dos seus inimigos.
“‘Naquele tempo talvez^&#42;1^ se humilhe o seu coração incircunciso e naquele tempo talvez saldem o seu erro.

[NOTE]
====
. “Talvez; ou”, MSam; Sy: “E”; LXX o omite.
====

[[v3-26-42]]

^<<v3-26-42,42>>^ E eu deveras me lembrarei do meu pacto com Jacó; e lembrar-me-ei até mesmo do meu pacto com Isaque e até mesmo do meu pacto com Abraão, e lembrar-me-ei da terra.

[[v3-26-43]]

^<<v3-26-43,43>>^ No ínterim, a terra foi deixada abandonada por eles e saldava os seus sábados, enquanto jazia desolada, sem eles, e eles mesmos saldavam seu erro, porque, sim, porque^&#42;1^ tinham rejeitado as minhas decisões judiciais e suas almas tinham abominado os meus estatutos.

[NOTE]
====
. “Porque, sim, porque.” Hebr.: yá·‛an u·veyá·‛an. Esta duplicação enfática da conjunção yá·‛an ocorre três vezes: aqui, em Ez 13:10, e, sem o copulativo Waw (u), em Ez 36:3.
====

[[v3-26-44]]

^<<v3-26-44,44>>^ E apesar de tudo isso, enquanto continuarem na terra dos seus inimigos, certamente não os rejeitarei, nem os abominarei a ponto de exterminá-los, para violar meu pacto com eles; pois eu sou Jeová, seu Deus.

[[v3-26-45]]

^<<v3-26-45,45>>^ E vou lembrar-me, em seu benefício, do pacto dos antecessores que fiz sair da terra do Egito sob os olhares das nações, para mostrar-me seu Deus. Eu sou Jeová.’”

[[v3-26-46]]

^<<v3-26-46,46>>^ Estes são os regulamentos, e as decisões judiciais, e as leis que Jeová estabeleceu entre si e os filhos de Israel no monte Sinai, por meio de Moisés.

'''

xref:003-levitico/003-levitico-025.adoc#v3-25-0[&#60; Capítulo Anterior] | <<v3-26-0,Topo>> | xref:003-levitico/003-levitico-027.adoc#v3-27-0[Próximo Capítulo &#62;]