include::./index.adoc[]

[[v3-16-0]]
=== Levítico, 16
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v3-16-1]]

^<<v3-16-1,1>>^ E Jeová passou a falar a Moisés depois de os dois filhos de Arão terem morrido por se terem chegado^&#42;1^ perante Jeová, de modo que morreram.

[NOTE]
====
. “Por se terem chegado”, MSam; LXXSyVg: “por apresentarem fogo estranho (ilegítimo)”. Veja 10:1; Núm 3:4.
====

[[v3-16-2]]

^<<v3-16-2,2>>^ E Jeová passou a dizer a Moisés: “Fala a Arão, teu irmão, que não deve entrar a toda hora no lugar santo^&#42;1^ dentro da cortina, diante da tampa^&#42;2^ que há sobre a Arca, para que não morra; porque aparecerei numa nuvem por cima da tampa.

[NOTE]
====
. “No lugar santo.” Hebr.: haq·qó·dhesh.
. “Da tampa (trono de misericórdia; propiciatório).” Hebr.: hak·kap·pó·reth; gr.: hi·la·ste·rí·ou; lat.: pro·pi·ti·a·tó·ri·o. Veja He 9:5 n.
====

[[v3-16-3]]

^<<v3-16-3,3>>^ “Com o seguinte deve Arão entrar no lugar santo: com um novilho como oferta pelo pecado e um carneiro como oferta queimada.

[[v3-16-4]]

^<<v3-16-4,4>>^ Deve vestir-se da sagrada veste comprida de linho, e os calções de linho devem ficar sobre a sua carne, e deve cingir-se da faixa de linho e enrolar sobre si o turbante de linho. São vestes sagradas. E tem de banhar sua carne em água e vestir-se delas.

[[v3-16-5]]

^<<v3-16-5,5>>^ “E da assembléia dos filhos de Israel deve tomar dois cabritinhos como oferta pelo pecado e um carneiro como oferta queimada.

[[v3-16-6]]

^<<v3-16-6,6>>^ “E Arão tem de apresentar o novilho da oferta pelo pecado, que é por ele mesmo, e tem de fazer expiação^&#42;1^ por si e por sua casa.

[NOTE]
====
. “E tem de fazer expiação.” Hebr.: wekhip·pér.
====

[[v3-16-7]]

^<<v3-16-7,7>>^ “E tem de tomar os dois bodes^&#42;1^ e fazê-los ficar de pé perante Jeová à entrada da tenda de reunião.

[NOTE]
====
. Ou “dois cabritinhos”, como no v. 5.
====

[[v3-16-8]]

^<<v3-16-8,8>>^ E Arão tem de tirar sortes sobre os dois bodes, uma sorte para Jeová e a outra sorte para Azazel.^&#42;1^

[NOTE]
====
. “Para Azazel”, M(hebr.: la·‛Aza’·zél)Sam; LXX: “Aquele que leva embora (afasta) o mal”; lat.: cá·pro e·mis·sá·ri·o, “o bode emissário; o bode expiatório”.
====

[[v3-16-9]]

^<<v3-16-9,9>>^ E Arão tem de apresentar o bode sobre o qual recaiu a sorte para Jeová e tem de fazer dele uma oferta pelo pecado.

[[v3-16-10]]

^<<v3-16-10,10>>^ Mas o bode sobre o qual recaiu a sorte para Azazel deve ser posto vivo perante Jeová para fazer expiação por ele, a fim de ser enviado ao ermo, para Azazel.

[[v3-16-11]]

^<<v3-16-11,11>>^ “E Arão tem de apresentar o novilho da oferta pelo pecado, que é por ele mesmo,^&#42;1^ e fazer expiação por si e por sua casa; e tem de abater o novilho da oferta pelo pecado, que é por ele mesmo.

[NOTE]
====
. LXX acrescenta: “e só por sua casa”.
====

[[v3-16-12]]

^<<v3-16-12,12>>^ “E tem de tomar o porta-lume cheio de brasas de fogo de cima do altar perante Jeová e as concavidades de ambas as suas mãos cheias de incenso^&#42;1^ perfumado, miúdo, e tem de trazê-los para dentro da cortina.

[NOTE]
====
. “Incenso.” Hebr.: qetó·reth; lat.: in·cén·sum.
====

[[v3-16-13]]

^<<v3-16-13,13>>^ Também tem de pôr o incenso sobre o fogo perante Jeová, e a nuvem do incenso tem de estender-se por cima da tampa da Arca, a qual está sobre o Testemunho,^&#42;1^ para que não morra.

[NOTE]
====
. “O Testemunho.” Hebr.: ha·‛e·dhúth; gr.: mar·ty·rí·on, pl.; lat.: te·sti·mó·ni·um.
====

[[v3-16-14]]

^<<v3-16-14,14>>^ “E tem de tomar um pouco do sangue do novilho e espargi-lo com o dedo na frente da tampa,^&#42;1^ para o leste, e espargirá um pouco do sangue com o dedo sete vezes perante a tampa.

[NOTE]
====
. “Na frente da tampa (trono de misericórdia).” Hebr.: ‛al-penéh hak·kap·pó·reth; LXX: “sobre o propiciatório”; Vg: “em direção ao propiciatório”. Veja v. 2.
====

[[v3-16-15]]

^<<v3-16-15,15>>^ “E tem de abater o bode da oferta pelo pecado, que é para o povo, e tem de trazer seu sangue para dentro da cortina e fazer com o seu sangue o mesmo que fez com o sangue do novilho; e tem de espargi-lo em direção à tampa^&#42;1^ e diante da tampa.

[NOTE]
====
. “Em direção à tampa (trono de misericórdia).” Hebr.: ‛al-hak·kap·pó·reth; gr.: e·pí to hi·la·sté·ri·on, “sobre o propiciatório”; lat.: e re·gi·ó·ne o·rá·cu·li, “contra (oposto a) o oráculo”.
====

[[v3-16-16]]

^<<v3-16-16,16>>^ “E tem de fazer expiação pelo lugar santo com respeito^&#42;1^ à impureza dos filhos de Israel e com respeito às suas revoltas em todos os seus pecados; e assim deve fazer pela tenda de reunião, que reside com eles no meio das suas impurezas.

[NOTE]
====
. Ou “da”.
====

[[v3-16-17]]

^<<v3-16-17,17>>^ “E nenhum outro homem^&#42;1^ deve estar na tenda de reunião desde que ele entra para fazer expiação no lugar santo até que saia; e ele tem de fazer expiação por si e por sua casa, e por toda a congregação^&#42;2^ de Israel.

[NOTE]
====
. Ou “[homem] terreno”. Hebr.: ’a·dhám.
. “Toda a congregação de.” Hebr.: kol-qehál.
====

[[v3-16-18]]

^<<v3-16-18,18>>^ “E tem de sair ao altar que está perante Jeová e fazer expiação^&#42;1^ por ele, e tem de tomar um pouco do sangue do novilho e um pouco do sangue do bode e pô-lo sobre os chifres em roda do altar.

[NOTE]
====
. “E fazer expiação.” Hebr.: wekhip·pér.
====

[[v3-16-19]]

^<<v3-16-19,19>>^ Também tem de espargir um pouco do sangue sobre ele com o seu dedo, sete vezes, e purificá-lo e santificá-lo das impurezas dos filhos de Israel.

[[v3-16-20]]

^<<v3-16-20,20>>^ “Quando tiver acabado de fazer expiação pelo lugar santo, e pela tenda de reunião, e pelo altar, então terá de apresentar o bode vivo.

[[v3-16-21]]

^<<v3-16-21,21>>^ E Arão tem de pôr ambas as suas mãos sobre a cabeça do bode vivo e confessar sobre ele todos os erros dos filhos de Israel e todas as suas revoltas em todos os seus pecados, e tem de pô-las sobre a cabeça do bode e tem de enviá-lo ao ermo pela mão de um homem preparado.

[[v3-16-22]]

^<<v3-16-22,22>>^ E o bode tem de levar sobre si todos os erros deles a uma terra desértica; e ele tem de enviar o bode ao ermo.

[[v3-16-23]]

^<<v3-16-23,23>>^ “E Arão tem de entrar na tenda de reunião e despir-se das roupas de linho de que se vestiu ao entrar no lugar santo, e tem de depositá-las ali.

[[v3-16-24]]

^<<v3-16-24,24>>^ E tem de banhar sua carne em água num lugar santo e vestir-se das suas roupas, e tem de sair e ofertar a sua oferta queimada, e a oferta queimada do povo, e fazer expiação por si e pelo povo.^&#42;1^

[NOTE]
====
. “Por si, e pela sua casa, e pelo povo, bem como pelos sacerdotes”, LXX.
====

[[v3-16-25]]

^<<v3-16-25,25>>^ E fará fumegar sobre o altar a gordura da oferta pelo pecado.

[[v3-16-26]]

^<<v3-16-26,26>>^ “Quanto àquele que enviou o bode para Azazel, deve lavar as suas vestes e tem de banhar sua carne em água, e depois pode entrar no acampamento.

[[v3-16-27]]

^<<v3-16-27,27>>^ “No entanto, fará levar para fora do acampamento o novilho da oferta pelo pecado e o bode da oferta pelo pecado, dos quais o sangue fora levado para dentro, a fim de fazer expiação no lugar santo; e eles têm de queimar no fogo suas peles, e sua carne, e seu esterco.

[[v3-16-28]]

^<<v3-16-28,28>>^ E aquele que os queimar deve lavar suas vestes e tem de banhar sua carne em água, e depois pode entrar no acampamento.

[[v3-16-29]]

^<<v3-16-29,29>>^ “E isso vos tem de servir de estatuto por tempo indefinido:^&#42;1^ No sétimo mês,^&#42;2^ no décimo [dia] do mês, deveis atribular as vossas almas, e não deveis fazer obra alguma, quer o natural^&#42;3^ quer o residente forasteiro^&#42;4^ que reside no vosso meio.

[NOTE]
====
. “Por tempo indefinido.” Hebr.: ‛oh·lám.
. Veja Ap. 8B.
. “O natural.” Hebr.: ha·’ez·ráhh; lat.: in·dí·ge·na.
. “Quer o residente forasteiro.” Hebr.: wehag·gér; lat.: ád·ve·na.
====

[[v3-16-30]]

^<<v3-16-30,30>>^ Pois neste dia se fará expiação^&#42;1^ por vós, para declarar-vos limpos. Sereis limpos de todos os vossos pecados perante Jeová.

[NOTE]
====
. Lit.: “Pois neste dia ele fará expiação.” LXX reza de modo similar.
====

[[v3-16-31]]

^<<v3-16-31,31>>^ É um sábado de completo repouso^&#42;1^ para vós, e tendes de atribular as vossas almas. É um estatuto por tempo indefinido.

[NOTE]
====
. Ou “de observância sabática”.
====

[[v3-16-32]]

^<<v3-16-32,32>>^ “E o sacerdote que será ungido^&#42;1^ e cuja mão será enchida de poder^&#42;2^ para atuar como sacerdote, como sucessor de seu pai, tem de fazer expiação e tem de vestir as roupas de linho. São roupas sagradas.

[NOTE]
====
. Segundo SyVg; M: “a quem ungirá”; LXX: “a quem ungirão”.
. Segundo Vg; M: “ele encherá de poder”; LXX: “eles encherão de poder”.
====

[[v3-16-33]]

^<<v3-16-33,33>>^ E ele tem de fazer expiação pelo santuário sagrado, e fará expiação pela tenda de reunião e pelo altar; e fará expiação pelos sacerdotes e por todo o povo da congregação.

[[v3-16-34]]

^<<v3-16-34,34>>^ E isto vos tem de servir de estatuto por tempo indefinido, a fim de se fazer expiação pelos filhos de Israel, uma vez por ano, com respeito a todos os seus pecados.”
Concordemente, ele fez assim como Jeová mandara a Moisés.

'''

xref:003-levitico/003-levitico-015.adoc#v3-15-0[&#60; Capítulo Anterior] | <<v3-16-0,Topo>> | xref:003-levitico/003-levitico-017.adoc#v3-17-0[Próximo Capítulo &#62;]