include::./index.adoc[]

[[v3-21-0]]
=== Levítico, 21
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v3-21-1]]

^<<v3-21-1,1>>^ E Jeová prosseguiu, dizendo a Moisés: “Fala aos sacerdotes, os filhos de Arão, e tens de dizer-lhes: ‘Ninguém se pode aviltar entre o seu povo por uma alma falecida.^&#42;1^

[NOTE]
====
. Lit.: “por uma alma”, isto é, uma alma falecida. Hebr.: lené·fesh; gr.: psy·khaís, pl. Veja v. 11 n. e Núm 6:6 n. Veja Ap. 4A.
====

[[v3-21-2]]

^<<v3-21-2,2>>^ Mas, por um parente consangüíneo seu, que lhe é chegado, por sua mãe, e por seu pai, e por seu filho, e por sua filha, e por seu irmão,

[[v3-21-3]]

^<<v3-21-3,3>>^ e por sua irmã, uma virgem que lhe é chegada, que não se tornou de um homem, por ela^&#42;1^ pode aviltar-se.

[NOTE]
====
. “Ela”, M; LXX: “elas”.
====

[[v3-21-4]]

^<<v3-21-4,4>>^ Não se pode aviltar por uma mulher possuída por um dono^&#42;1^ dentre seu povo, de modo a profanar-se.

[NOTE]
====
. “Não se pode aviltar por uma mulher possuída por um dono”, é a versão proposta, visto que M é obscuro; LXX: “Não se deve aviltar repentinamente”; Vg: “Não se deve aviltar por um príncipe.”
====

[[v3-21-5]]

^<<v3-21-5,5>>^ Não devem fazer calva nas suas cabeças e não devem rapar a extremidade da sua barba, e não devem fazer incisão na sua carne.

[[v3-21-6]]

^<<v3-21-6,6>>^ Devem mostrar-se santos para seu Deus e não devem profanar o nome de seu Deus, porque são os que apresentam as ofertas de Jeová feitas por fogo, o pão de seu Deus; e eles têm de mostrar-se santos.^&#42;1^

[NOTE]
====
. “Santos”, SamLXXSyVg; M: “algo santo”.
====

[[v3-21-7]]

^<<v3-21-7,7>>^ Não devem tomar uma prostituta ou uma mulher violentada; e não devem tomar uma mulher divorciada de seu esposo, porque ele é santo para seu Deus.

[[v3-21-8]]

^<<v3-21-8,8>>^ De modo que tens de santificá-lo, porque ele é quem apresenta o pão de teu Deus. Deve mostrar-se santo para vós, porque eu, Jeová, que vos santifico, sou santo.

[[v3-21-9]]

^<<v3-21-9,9>>^ “‘Ora, caso a filha de um sacerdote se profane por cometer prostituição, é a seu pai que ela está profanando. Deve ser queimada no fogo.

[[v3-21-10]]

^<<v3-21-10,10>>^ “‘E quanto ao sumo sacerdote dos seus irmãos, sobre cuja cabeça se despeje o óleo de unção e cuja mão foi enchida de poder^&#42;1^ para usar as vestes, não deve deixar sua cabeça ficar desgrenhada e não deve rasgar as suas vestes.

[NOTE]
====
. “E cuja mão foi enchida de poder.” Ou “e que foi empossado (inaugurado; instalado)”. Hebr.: u·mil·lé’ ’eth·ya·dhóh; gr.: te·te·lei·o·mé·nou (LXXThºmsºn, “tendo sido consagrado”). Veja He 5:9 n. e He 7:28 n.
====

[[v3-21-11]]

^<<v3-21-11,11>>^ E não se deve chegar a uma alma morta.^&#42;1^ Não se pode aviltar por seu pai e por sua mãe.

[NOTE]
====
. Lit.: “almas de um morto”. Hebr.: naf·shóth, pl., seguido por meth, “morto”; gr.: psy·kheí, seguido por te·te·leu·te·kuí·ai, o particípio perfeito de “falecer”, dá o sentido de “alma falecida”; Sy: “alma de um morto”; Vg: “morto”.
====

[[v3-21-12]]

^<<v3-21-12,12>>^ Tampouco deve sair do santuário e não deve profanar o santuário de seu Deus, porque há sobre ele o sinal de dedicação, o óleo de unção de seu Deus. Eu sou Jeová.

[[v3-21-13]]

^<<v3-21-13,13>>^ “‘E da sua parte deve tomar uma mulher na sua virgindade.

[[v3-21-14]]

^<<v3-21-14,14>>^ Quanto à viúva ou à mulher divorciada, e à violentada, uma prostituta, nenhuma destas pode tomar, mas deve tomar por esposa uma virgem do seu povo.

[[v3-21-15]]

^<<v3-21-15,15>>^ E não deve profanar sua descendência^&#42;1^ entre seu povo, porque eu sou Jeová que o santifico.’”

[NOTE]
====
. Ou “prole”.
====

[[v3-21-16]]

^<<v3-21-16,16>>^ E Jeová continuou a falar a Moisés, dizendo:

[[v3-21-17]]

^<<v3-21-17,17>>^ “Fala a Arão, dizendo: ‘Nenhum homem da tua descendência, nas suas gerações, em quem se mostre haver defeito, pode chegar-se para apresentar o pão de seu Deus.

[[v3-21-18]]

^<<v3-21-18,18>>^ Caso haja algum homem em quem há defeito, não se pode chegar: um homem cego, ou coxo, ou de nariz fendido, ou com um membro comprido demais,^&#42;1^

[NOTE]
====
. Ou “com um membro supérfluo”.
====

[[v3-21-19]]

^<<v3-21-19,19>>^ ou um homem em quem se mostre haver fratura do pé ou fratura da mão,

[[v3-21-20]]

^<<v3-21-20,20>>^ ou corcunda, ou franzino,^&#42;1^ ou com moléstia nos olhos, ou eczematoso, ou que padece de tinha favosa, ou que tenha os testículos quebrados.

[NOTE]
====
. Ou “ananicado”. Possivelmente: “tísico”.
====

[[v3-21-21]]

^<<v3-21-21,21>>^ Qualquer homem da descendência de Arão, o sacerdote, em quem haja um defeito, não se pode aproximar para apresentar as ofertas de Jeová feitas por fogo. Há defeito nele. Não se pode aproximar para apresentar o pão de seu Deus.

[[v3-21-22]]

^<<v3-21-22,22>>^ Pode comer o pão de seu Deus das coisas santíssimas e das coisas sagradas.

[[v3-21-23]]

^<<v3-21-23,23>>^ No entanto, não se pode chegar à cortina e não se pode aproximar do altar, porque há defeito nele; e não deve profanar meu santuário, pois eu sou Jeová que os santifico.’”

[[v3-21-24]]

^<<v3-21-24,24>>^ Concordemente, Moisés falou a Arão e aos filhos dele, e a todos os filhos de Israel.

'''

xref:003-levitico/003-levitico-020.adoc#v3-20-0[&#60; Capítulo Anterior] | <<v3-21-0,Topo>> | xref:003-levitico/003-levitico-022.adoc#v3-22-0[Próximo Capítulo &#62;]