include::./index.adoc[]

[[v3-20-0]]
=== Levítico, 20
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v3-20-1]]

^<<v3-20-1,1>>^ E Jeová passou a falar a Moisés, dizendo:

[[v3-20-2]]

^<<v3-20-2,2>>^ “Hás de dizer aos filhos de Israel: ‘Qualquer homem dos filhos de Israel e qualquer residente forasteiro que reside em Israel, que der alguém da sua descendência a Moloque,^&#42;1^ sem falta deve ser morto. O povo da terra deve atirar nele pedras até que morra.

[NOTE]
====
. “Moloque”, M; Vg: “o ídolo Moloque”; LXX: “o governante”.
====

[[v3-20-3]]

^<<v3-20-3,3>>^ E quanto a mim, porei minha face contra tal homem, e eu vou decepá-lo dentre seu povo, porque deu alguém da sua descendência a Moloque, com o objetivo de aviltar meu lugar santo e profanar meu santo nome.^&#42;1^

[NOTE]
====
. Lit.: “o nome de minha santidade”.
====

[[v3-20-4]]

^<<v3-20-4,4>>^ E se o povo da terra ocultar deliberadamente seus olhos daquele homem, quando ele der alguém da sua descendência a Moloque, por não o entregarem à morte,

[[v3-20-5]]

^<<v3-20-5,5>>^ então eu, da minha parte, certamente porei minha face contra aquele homem e sua família, e deveras deceparei dentre seu povo tanto a ele como a todos os que junto com ele tiverem relações imorais por terem relações imorais^&#42;1^ com Moloque.

[NOTE]
====
. Ou “cometerem fornicação”.
====

[[v3-20-6]]

^<<v3-20-6,6>>^ “‘Quanto à alma que se vira para os médiuns espíritas e para os prognosticadores profissionais de eventos, a fim de ter relações imorais com eles, certamente porei minha face contra essa alma e a deceparei dentre seu povo.

[[v3-20-7]]

^<<v3-20-7,7>>^ “‘E tendes de santificar-vos e mostrar-vos santos, porque eu sou Jeová, vosso Deus.

[[v3-20-8]]

^<<v3-20-8,8>>^ E tendes de guardar os meus estatutos e cumpri-los. Eu sou Jeová que vos santifico.^&#42;1^

[NOTE]
====
. Ou “que vos tenho como sagrados (vos trato como sagrados)”. Hebr.: meqad·dish·khém; gr.: ho ha·gi·á·zon hy·más; lat.: qui sanc·tí·fi·co vos.
====

[[v3-20-9]]

^<<v3-20-9,9>>^ “‘Caso haja um homem que invoque o mal sobre seu pai e sua mãe, sem falta deve ser morto. É sobre seu pai e sua mãe que invocou o mal. Seu próprio sangue^&#42;1^ está sobre ele.

[NOTE]
====
. Quer dizer, a responsabilidade pelo seu sangue.
====

[[v3-20-10]]

^<<v3-20-10,10>>^ “‘Ora, o homem que comete adultério com a esposa de outro homem é um que comete adultério^&#42;1^ com a esposa de seu próximo. Sem falta deve^&#42;2^ ser morto, tanto o adúltero como a adúltera.

[NOTE]
====
. “Adultério.” Lat.: a·dul·té·ri·um.
. “Deve”, MSam; LXXSyVg: “devem”.
====

[[v3-20-11]]

^<<v3-20-11,11>>^ E o homem que se deita com a esposa de seu pai realmente descobre a nudez de seu pai. Sem falta, ambos devem ser mortos. Seu próprio sangue está sobre eles.

[[v3-20-12]]

^<<v3-20-12,12>>^ E quando um homem se deita com a sua nora, sem falta, ambos devem ser mortos. Cometeram uma violação daquilo que é natural. Seu próprio sangue está sobre eles.

[[v3-20-13]]

^<<v3-20-13,13>>^ “‘E quando um homem se deita com um macho assim como alguém se deita com uma mulher, ambos realmente fazem algo detestável. Sem falta devem ser mortos. Seu próprio sangue está sobre eles.

[[v3-20-14]]

^<<v3-20-14,14>>^ “‘E quando um homem toma uma mulher e a mãe dela, é conduta desenfreada. Devem queimar tanto a ele como a elas no fogo, para que a conduta desenfreada não continue no vosso meio.

[[v3-20-15]]

^<<v3-20-15,15>>^ “‘E quando um homem dá a sua emissão seminal a um animal, sem falta deve ser morto, e deveis matar o animal.

[[v3-20-16]]

^<<v3-20-16,16>>^ E quando uma mulher se aproxima de algum animal para ter contato com ele,^&#42;1^ tens de matar a mulher e o animal. Sem falta devem ser mortos. Seu próprio sangue está sobre eles.

[NOTE]
====
. Ou “ela”.
====

[[v3-20-17]]

^<<v3-20-17,17>>^ “‘E quando um homem toma sua irmã, a filha de seu pai ou a filha de sua mãe, e deveras vê a sua nudez, e ela mesma vê a nudez dele, é uma vergonha. De modo que têm de ser decepados diante dos olhos dos filhos do seu povo. É a nudez de sua irmã que ele descobriu. Deve responder pelo seu erro.

[[v3-20-18]]

^<<v3-20-18,18>>^ “‘E quando um homem se deita com uma mulher menstruada e deveras lhe descobre a nudez, realmente expõe a sua fonte e ela mesma realmente descobre a fonte de seu sangue. Portanto, ambos têm de ser decepados dentre seu povo.

[[v3-20-19]]

^<<v3-20-19,19>>^ “‘E não deves descobrir a nudez da irmã de tua mãe e da irmã de teu pai, porque é a sua parenta consangüínea que [a pessoa] expôs. Devem responder pelo seu erro.

[[v3-20-20]]

^<<v3-20-20,20>>^ E o homem que se deita com a esposa de seu tio realmente descobre a nudez de seu tio. Devem responder pelo seu erro. Devem morrer sem filhos.

[[v3-20-21]]

^<<v3-20-21,21>>^ E quando um homem toma a esposa de seu irmão, é algo abominável. É a nudez de seu irmão que ele descobriu. Devem ficar^&#42;1^ sem filhos.

[NOTE]
====
. “Ficar”, M; LXX: “morrer”.
====

[[v3-20-22]]

^<<v3-20-22,22>>^ “‘E tendes de guardar todos os meus estatutos e todas as minhas decisões judiciais, e tendes de cumpri-las, para que não sejais vomitados pela terra à qual vos levo para morardes nela.

[[v3-20-23]]

^<<v3-20-23,23>>^ E não deveis andar nos estatutos das nações que ponho para fora diante de vós, porque fizeram todas estas coisas e eu as abomino.

[[v3-20-24]]

^<<v3-20-24,24>>^ Por isso eu vos disse: “Vós, da vossa parte, tomareis posse do seu terreno, e eu, da minha parte, vo-lo darei para tomardes posse dele, [de] uma terra que mana leite e mel. Sou Jeová, vosso Deus, que vos separei dos povos.”

[[v3-20-25]]

^<<v3-20-25,25>>^ E tendes de fazer diferença entre o animal limpo e o impuro, e entre a ave impura e a limpa; e não deveis fazer vossas almas repugnantes com o animal, e com a ave, e com qualquer coisa que se mova sobre o solo, que separei de vós por declará-los impuros.

[[v3-20-26]]

^<<v3-20-26,26>>^ E tendes de mostrar-vos santos para mim, porque eu, Jeová, sou santo; e estou passando a separar-vos dos povos para vos tornardes meus.

[[v3-20-27]]

^<<v3-20-27,27>>^ “‘E quanto ao homem ou à mulher em quem se mostre haver um espírito mediúnico ou um espírito de predição, sem falta devem ser mortos. Devem atirar neles pedras até morrerem. Seu próprio sangue está sobre eles.’”

'''

xref:003-levitico/003-levitico-019.adoc#v3-19-0[&#60; Capítulo Anterior] | <<v3-20-0,Topo>> | xref:003-levitico/003-levitico-021.adoc#v3-21-0[Próximo Capítulo &#62;]