include::./index.adoc[]

[[v3-23-0]]
=== Levítico, 23
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v3-23-1]]

^<<v3-23-1,1>>^ E Jeová prosseguiu, falando a Moisés, dizendo:

[[v3-23-2]]

^<<v3-23-2,2>>^ “Fala aos filhos de Israel, e tens de dizer-lhes: ‘As festividades periódicas de Jeová, que deveis proclamar, são santos congressos. Estas são as minhas festividades periódicas:

[[v3-23-3]]

^<<v3-23-3,3>>^ “‘Por seis dias se pode fazer alguma obra, mas no sétimo dia há um sábado de completo repouso, um santo congresso. Não podeis fazer nenhuma sorte de obra. É um sábado para Jeová em todos os lugares em que morardes.

[[v3-23-4]]

^<<v3-23-4,4>>^ “‘Estas são as festividades periódicas de Jeová, santos congressos, que deveis proclamar nos seus tempos designados:

[[v3-23-5]]

^<<v3-23-5,5>>^ No primeiro mês, no décimo quarto dia do mês, entre as duas noitinhas,^&#42;1^ há a páscoa para Jeová.

[NOTE]
====
. Veja Êx 12:6 n.
====

[[v3-23-6]]

^<<v3-23-6,6>>^ “‘E no décimo quinto dia deste mês há a festividade dos pães não fermentados para Jeová. Por sete dias deveis comer pães não fermentados.

[[v3-23-7]]

^<<v3-23-7,7>>^ No primeiro dia haverá para vós um santo congresso. Não podeis fazer nenhuma sorte de obra laboriosa.

[[v3-23-8]]

^<<v3-23-8,8>>^ Mas tendes de apresentar a Jeová uma oferta feita por fogo, por sete dias. No sétimo dia haverá um santo congresso. Não podeis fazer nenhuma sorte de obra laboriosa.’”

[[v3-23-9]]

^<<v3-23-9,9>>^ E Jeová continuou a falar a Moisés, dizendo:

[[v3-23-10]]

^<<v3-23-10,10>>^ “Fala aos filhos de Israel, e tens de dizer-lhes: ‘Quando por fim entrardes na terra que eu vos dou e tiverdes ceifado a sua colheita, então tereis de trazer ao sacerdote um molho^&#42;1^ das primícias da vossa colheita.

[NOTE]
====
. Ou “gômor”, que equivalia a 2,2 l.
====

[[v3-23-11]]

^<<v3-23-11,11>>^ E ele terá de mover o molho para lá e para cá perante Jeová, a fim de ganhar aprovação para vós. Logo no dia depois do sábado, o sacerdote deve movê-lo para lá e para cá.

[[v3-23-12]]

^<<v3-23-12,12>>^ E no dia em que fizerdes mover o molho para lá e para cá tereis de ofertar um carneirinho sadio, no seu primeiro ano, como oferta queimada a Jeová;

[[v3-23-13]]

^<<v3-23-13,13>>^ e como sua oferta de cereais, dois décimos de um efa de flor de farinha umedecida com azeite, como oferta a Jeová feita por fogo, um cheiro repousante; e como sua oferta de bebida, um quarto de um him^&#42;1^ de vinho.

[NOTE]
====
. Um him equivalia a 3,67 l.
====

[[v3-23-14]]

^<<v3-23-14,14>>^ E não deveis comer nenhum pão, nem grão torrado, nem cereal novo até este mesmo dia, até trazerdes a oferta de vosso Deus. É um estatuto por tempo indefinido para as vossas gerações, em todos os lugares em que morardes.

[[v3-23-15]]

^<<v3-23-15,15>>^ “‘E tendes de contar para vós sete sábados,^&#42;1^ a partir do dia depois do sábado, desde o dia em que trazeis o molho da oferta movida. Devem mostrar-se completos.

[NOTE]
====
. Ou “semanas”. Hebr.: shab·ba·thóhth. Veja Mt 28:1.
====

[[v3-23-16]]

^<<v3-23-16,16>>^ Deveis contar até o dia depois do sétimo sábado, cinqüenta dias, e tendes de apresentar uma nova oferta de cereais a Jeová.

[[v3-23-17]]

^<<v3-23-17,17>>^ Dos vossos lugares de morada deveis trazer dois pães como oferta movida. Devem mostrar ser de dois décimos de um efa de flor de farinha. Devem ser cozidos levedados, como primeiros frutos maduros para Jeová.

[[v3-23-18]]

^<<v3-23-18,18>>^ E junto com os pães tendes de apresentar sete cordeiros sadios, cada um de um ano, e um novilho e dois carneiros. Devem servir de oferta queimada para Jeová, junto com a sua oferta de cereais e suas ofertas de bebida, como oferta feita por fogo, de cheiro repousante para Jeová.

[[v3-23-19]]

^<<v3-23-19,19>>^ E tendes de ofertar um cabritinho como oferta pelo pecado, e dois cordeiros, cada um da idade de um ano, como sacrifício de participação em comum.

[[v3-23-20]]

^<<v3-23-20,20>>^ E o sacerdote tem de movê-los para lá e para cá, junto com os pães dos primeiros frutos maduros, como oferta movida perante Jeová, junto com os dois cordeiros. Devem servir como algo sagrado a Jeová para o sacerdote.

[[v3-23-21]]

^<<v3-23-21,21>>^ E neste mesmo dia tendes de fazer uma proclamação; haverá para vós um santo congresso. Não podeis fazer nenhuma sorte de obra laboriosa. É um estatuto por tempo indefinido em todos os vossos lugares de morada, para as vossas gerações.

[[v3-23-22]]

^<<v3-23-22,22>>^ “‘E quando ceifardes a colheita da vossa terra, não deves acabar completamente o canto do teu campo quando estás ceifando e não deves apanhar a respiga da tua colheita. Deves deixá-los para o atribulado e para o residente forasteiro. Eu sou Jeová, vosso Deus.’”

[[v3-23-23]]

^<<v3-23-23,23>>^ E Jeová prosseguiu, falando a Moisés, dizendo:

[[v3-23-24]]

^<<v3-23-24,24>>^ “Fala aos filhos de Israel, dizendo: ‘No sétimo mês, no primeiro [dia] do mês, deve haver para vós um completo repouso, uma recordação ao toque de trombeta, um santo congresso.

[[v3-23-25]]

^<<v3-23-25,25>>^ Não podeis fazer nenhuma sorte de obra laboriosa e tendes de apresentar a Jeová uma oferta feita por fogo.’”

[[v3-23-26]]

^<<v3-23-26,26>>^ E Jeová falou mais a Moisés, dizendo:

[[v3-23-27]]

^<<v3-23-27,27>>^ “No entanto, no décimo [dia] deste sétimo mês há o dia da expiação. Deve haver para vós um santo congresso, e tendes de atribular as vossas almas e apresentar a Jeová uma oferta feita por fogo.

[[v3-23-28]]

^<<v3-23-28,28>>^ E neste mesmo dia não deveis fazer nenhuma sorte de obra, porque é dia de expiação, para se fazer expiação por vós perante Jeová, vosso Deus;

[[v3-23-29]]

^<<v3-23-29,29>>^ porque toda alma que não se atribular neste mesmo dia terá de ser decepada do seu povo.

[[v3-23-30]]

^<<v3-23-30,30>>^ Quanto a qualquer alma que fizer qualquer sorte de obra neste mesmo dia, terei de destruir esta alma dentre o seu povo.

[[v3-23-31]]

^<<v3-23-31,31>>^ Não deveis fazer nenhuma sorte de obra. É um estatuto por tempo indefinido para as vossas gerações em todos os lugares em que morardes.

[[v3-23-32]]

^<<v3-23-32,32>>^ É para vós um sábado de completo repouso, e no nono [dia] do mês, à noitinha, tendes de atribular as vossas almas. Deveis observar o vosso sábado de noitinha a noitinha.”

[[v3-23-33]]

^<<v3-23-33,33>>^ E Jeová continuou a falar a Moisés, dizendo:

[[v3-23-34]]

^<<v3-23-34,34>>^ “Fala aos filhos de Israel, dizendo: ‘No décimo quinto [dia] deste sétimo mês há a festividade das barracas, por sete dias, para Jeová.^&#42;1^

[NOTE]
====
. “Para Jeová.” Hebr.: la·Yho·wáh. Veja Ap. 1A.
====

[[v3-23-35]]

^<<v3-23-35,35>>^ No primeiro dia há um santo congresso. Não podeis fazer nenhuma sorte de obra laboriosa.

[[v3-23-36]]

^<<v3-23-36,36>>^ Por sete dias deveis apresentar a Jeová uma oferta feita por fogo. No oitavo dia deve haver para vós um santo congresso, e tendes de apresentar a Jeová uma oferta feita por fogo. É uma assembléia solene.^&#42;1^ Não podeis fazer nenhuma sorte de obra laboriosa.

[NOTE]
====
. “Uma assembléia solene.” Hebr.: ‛atsé·reth; gr.: e·xó·di·on; isto é, um dia festivo para comemorar o êxodo do Egito.
====

[[v3-23-37]]

^<<v3-23-37,37>>^ “‘Estas são as festividades periódicas de Jeová, que deveis proclamar como santos congressos, para se apresentar a Jeová uma oferta feita por fogo: a oferta queimada e a oferta de cereais do sacrifício, e as ofertas de bebida, segundo o programa diário,^&#42;1^

[NOTE]
====
. “Segundo o programa diário.” Lit.: “uma coisa (obra) dum dia no seu dia”.
====

[[v3-23-38]]

^<<v3-23-38,38>>^ além dos sábados de Jeová, e além das vossas dádivas, e além de todas as vossas ofertas votivas, e além de todas as vossas ofertas voluntárias, que deveis dar a Jeová.

[[v3-23-39]]

^<<v3-23-39,39>>^ No entanto, no décimo quinto dia do sétimo mês, quando tiverdes recolhido os produtos da terra, deveis celebrar a festividade de Jeová por sete dias. No primeiro dia há um completo repouso e no oitavo dia há um completo repouso.

[[v3-23-40]]

^<<v3-23-40,40>>^ E no primeiro dia tendes de tomar para vós o fruto de árvores esplêndidas, as folhas de palmeiras e os galhos de árvores ramosas, e choupos do vale da torrente, e tendes de alegrar-vos perante Jeová, vosso Deus, por sete dias.

[[v3-23-41]]

^<<v3-23-41,41>>^ E tendes de celebrá-la como festividade para Jeová, por sete dias no ano. Deveis celebrá-la no sétimo mês, como estatuto por tempo indefinido nas vossas gerações.

[[v3-23-42]]

^<<v3-23-42,42>>^ É nas barracas que deveis morar por sete dias. Todos os naturais de Israel devem morar nas barracas,

[[v3-23-43]]

^<<v3-23-43,43>>^ para que as vossas gerações saibam que foi nas barracas que fiz os filhos de Israel morar quando os fiz sair da terra do Egito. Eu sou Jeová, vosso Deus.’”

[[v3-23-44]]

^<<v3-23-44,44>>^ Concordemente, Moisés falou aos filhos de Israel a respeito das festividades periódicas de Jeová.

'''

xref:003-levitico/003-levitico-022.adoc#v3-22-0[&#60; Capítulo Anterior] | <<v3-23-0,Topo>> | xref:003-levitico/003-levitico-024.adoc#v3-24-0[Próximo Capítulo &#62;]