include::./index.adoc[]

[[v28-6-0]]
=== Oseias, 6
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v28-6-1]]

^<<v28-6-1,1>>^ “Vinde, e retornemos a Jeová, pois ele mesmo dilacerou, mas há de curar-nos. Ele estava dando os golpes, mas há de nos pensar.

[[v28-6-2]]

^<<v28-6-2,2>>^ Fará que vivamos depois de dois dias. No terceiro dia fará que nos levantemos, e viveremos perante ele.

[[v28-6-3]]

^<<v28-6-3,3>>^ E conheceremos, empenhar-nos-emos em conhecer a Jeová. Como a alva, sua saída está firmemente estabelecida. E chegará a nós como o aguaceiro; como a chuva primaveril que satura [a] terra.”

[[v28-6-4]]

^<<v28-6-4,4>>^ “Que hei de fazer-te, ó Efraim? Que hei de fazer-te, ó Judá, quando a vossa benevolência^&#42;1^ é como as nuvens da madrugada e como o orvalho que logo desaparece?

[NOTE]
====
. Ou “o . . . amor leal”.
====

[[v28-6-5]]

^<<v28-6-5,5>>^ Por isso terei de talhá-los por meio dos profetas; terei de matá-los por meio das declarações da minha boca. E os julgamentos sobre ti serão como a luz que sai.

[[v28-6-6]]

^<<v28-6-6,6>>^ Pois, agrado-me da benevolência e não do sacrifício; e do conhecimento de Deus^&#42;1^ antes do que de holocaustos.

[NOTE]
====
. “Deus.” Hebr.: ’Elo·hím.
====

[[v28-6-7]]

^<<v28-6-7,7>>^ Mas eles mesmos, tal como um homem terreno,^&#42;1^ infringiram [o] pacto. É nisso que agiram traiçoeiramente para comigo.

[NOTE]
====
. Ou “como Adão”. Hebr.: ke’a·dhám.
====

[[v28-6-8]]

^<<v28-6-8,8>>^ Gileade é uma vila dos que praticam o que é prejudicial; suas pegadas são sangue.

[[v28-6-9]]

^<<v28-6-9,9>>^ E como que atocaiados contra um homem,^&#42;1^ a associação dos sacerdotes são guerrilhas. À beira do caminho cometem assassinato em Siquém, porque só se empenharam em conduta desenfreada.

[NOTE]
====
. “Um homem.” Hebr.: ’ish.
====

[[v28-6-10]]

^<<v28-6-10,10>>^ Vi uma coisa horrível na casa de Israel. Há ali fornicação da parte de Efraim. Israel se aviltou.

[[v28-6-11]]

^<<v28-6-11,11>>^ Além disso, ó Judá, fixou-se uma colheita para ti, quando eu recolher os cativos do meu povo.”

'''

xref:028-oseias/028-oseias-005.adoc#v28-5-0[&#60; Capítulo Anterior] | <<v28-6-0,Topo>> | xref:028-oseias/028-oseias-007.adoc#v28-7-0[Próximo Capítulo &#62;]