include::./index.adoc[]

[[v28-12-0]]
=== Oseias, 12
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v28-12-1]]

^<<v28-12-1,1>>^ “Efraim apascenta-se de vento^&#42;1^ e corre atrás do vento oriental o dia inteiro. Mentira e assolação é o que ele multiplica. E concluíram um pacto com a Assíria e leva-se azeite ao próprio Egito.

[NOTE]
====
. “Vento.” Hebr.: rú·ahh. Veja Gên 1:2 n.: “ativa”.
====

[[v28-12-2]]

^<<v28-12-2,2>>^ “E Jeová tem uma causa jurídica contra Judá, sim, para fazer um ajuste de contas com Jacó segundo os seus caminhos; pagar-lhe-á de volta segundo as suas ações.

[[v28-12-3]]

^<<v28-12-3,3>>^ No ventre agarrou seu irmão pelo calcanhar^&#42;1^ e com a sua energia dinâmica contendeu com Deus.^&#42;2^

[NOTE]
====
. Ou “ele suplantou seu irmão”.
. “Deus.” Hebr.: ’Elo·hím.
====

[[v28-12-4]]

^<<v28-12-4,4>>^ E continuou a contender com um anjo e gradualmente prevaleceu. Chorou para implorar favor para si mesmo.”
Ele foi encontrá-lo em Betel e ali começou a falar conosco.^&#42;1^

[NOTE]
====
. “Conosco”, MTVg; LXXSy: “com ele”.
====

[[v28-12-5]]

^<<v28-12-5,5>>^ E Jeová, o Deus dos exércitos,^&#42;1^ Jeová é sua recordação.

[NOTE]
====
. “O Deus dos exércitos”, MVg; LXX: “o Deus todo-poderoso”.
====

[[v28-12-6]]

^<<v28-12-6,6>>^ “E no que se refere a ti, deves voltar ao teu Deus, guardando a benevolência^&#42;1^ e a justiça; e haja constantemente esperança em teu Deus.

[NOTE]
====
. Ou “amor leal”.
====

[[v28-12-7]]

^<<v28-12-7,7>>^ Quanto ao comerciante,^&#42;1^ há na sua mão a balança de engano; o que ele ama é defraudar.

[NOTE]
====
. Ou “cananeu”. Hebr.: kená·‛an; gr.: Kha·na·án; lat.: Hhá·na·an. Veja Za 14:21 n.
====

[[v28-12-8]]

^<<v28-12-8,8>>^ E Efraim está dizendo: ‘Deveras, fiquei rico; achei para mim coisas valiosas. Quanto a toda a minha labuta, não acharão da minha parte nenhum erro que seja pecado.’

[[v28-12-9]]

^<<v28-12-9,9>>^ “Mas eu sou Jeová, teu Deus, desde a terra do Egito. Contudo, farei que mores em tendas como nos dias de um tempo designado.

[[v28-12-10]]

^<<v28-12-10,10>>^ E falei aos profetas e eu mesmo multipliquei as visões, e continuei a fazer semelhanças pela mão dos profetas.

[[v28-12-11]]

^<<v28-12-11,11>>^ “Com Gileade^&#42;1^ tem ocorrido aquilo que é mágico, também a inveracidade. Em Gilgal sacrificaram até mesmo touros. Além disso, seus altares são^&#42;2^ como montões de pedras nos sulcos da campina.

[NOTE]
====
. “Com Gileade”, mediante uma ligeira correção; M: “Se Gileade.”
. Ou “serão”.
====

[[v28-12-12]]

^<<v28-12-12,12>>^ E Jacó passou a fugir para o campo da Síria,^&#42;1^ e Israel continuou a servir por uma esposa,^&#42;2^ e por uma esposa guardava [ovelhas].

[NOTE]
====
. “Síria”, LXXVg; MSy: “Arã”.
. Ou “por uma mulher”. Hebr.: be·’ish·sháh.
====

[[v28-12-13]]

^<<v28-12-13,13>>^ E foi por meio dum profeta que Jeová fez Israel subir do Egito, e ele foi guardado por meio dum profeta.

[[v28-12-14]]

^<<v28-12-14,14>>^ Efraim causou ofensa até à amargura, e seus atos de derramamento de sangue ele deixou sobre si próprio, e seu grandioso Amo^&#42;1^ lhe retribuirá o seu vitupério.”

[NOTE]
====
. “Seu grandioso Amo.” Gr.: ’Adho·náv, pl. de ’A·dhóhn, para denotar excelência ou grandiosidade, acompanhado pelo verbo “retribuir” no sing. Veja Gên 39:2 n.
====

'''

xref:028-oseias/028-oseias-011.adoc#v28-11-0[&#60; Capítulo Anterior] | <<v28-12-0,Topo>> | xref:028-oseias/028-oseias-013.adoc#v28-13-0[Próximo Capítulo &#62;]