include::./index.adoc[]

[[v28-7-0]]
=== Oseias, 7
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v28-7-1]]

^<<v28-7-1,1>>^ “No tempo em que eu curar Israel, também se exporá realmente o erro de Efraim e as coisas más de Samaria; pois praticaram a falsidade, e entra até o próprio ladrão; do lado de fora é realmente uma guerrilha que faz uma incursão.

[[v28-7-2]]

^<<v28-7-2,2>>^ E não dizem ao seu próprio coração que vou lembrar-me de toda a sua maldade. Agora os cercaram as suas ações. Vieram a estar diante da minha face.

[[v28-7-3]]

^<<v28-7-3,3>>^ Com a sua maldade eles alegram [o] rei, e com as suas imposturas, príncipes.

[[v28-7-4]]

^<<v28-7-4,4>>^ Todos eles são adúlteros, como forno aceso pelo padeiro [que] cessa de atiçar depois de amassar a massa até que ela fique levedada.

[[v28-7-5]]

^<<v28-7-5,5>>^ No dia de nosso rei, os príncipes fizeram-se a si mesmos doentes — há furor por causa do vinho. Puxou a sua mão com os zombadores.

[[v28-7-6]]

^<<v28-7-6,6>>^ Pois fizeram seu coração chegar perto como a um forno; está ardendo dentro deles. Seu padeiro está dormindo a noite inteira; de manhã, [o forno]^&#42;1^ está aceso como que com um fogo chamejante.

[NOTE]
====
. Lit.: “ele”, hebr. masc., referindo-se ao “forno”, hebr. masc.
====

[[v28-7-7]]

^<<v28-7-7,7>>^ Ficam quentes, todos eles, como o forno, e realmente devoram os seus juízes. Seus próprios reis caíram; nenhum deles clama a mim.

[[v28-7-8]]

^<<v28-7-8,8>>^ “Quanto a Efraim, mistura-se pessoalmente com os povos. O próprio Efraim se tornou um bolo redondo que não foi virado.

[[v28-7-9]]

^<<v28-7-9,9>>^ Estranhos consumiram-lhe o poder, e ele mesmo não veio a saber [disso]. Também, os próprios cabelos grisalhos se embranqueceram nele, mas ele mesmo não veio a saber [disso].

[[v28-7-10]]

^<<v28-7-10,10>>^ E o orgulho de Israel testificou-lhe na face, e eles não retornaram a Jeová, seu Deus,^&#42;1^ nem o procuraram em vista de tudo isso.

[NOTE]
====
. “Seu Deus.” Hebr.: ’Elo·heh·hém.
====

[[v28-7-11]]

^<<v28-7-11,11>>^ E Efraim mostra ser igual a uma pomba simplória sem coração.^&#42;1^ Clamaram ao Egito; foram à Assíria.

[NOTE]
====
. Ou “sem boa motivação”. Hebr.: ’ehn lev.
====

[[v28-7-12]]

^<<v28-7-12,12>>^ “Aonde quer que forem, estenderei sobre eles a minha rede. Como a criaturas voadoras dos céus os farei vir abaixo. Discipliná-los-ei de acordo com o relatório à sua assembléia.

[[v28-7-13]]

^<<v28-7-13,13>>^ Ai deles, pois fugiram de mim! Assolação para eles, pois transgrediram contra mim! E eu mesmo passei a remi-los, porém, eles mesmos falaram mentiras até contra mim.

[[v28-7-14]]

^<<v28-7-14,14>>^ E não clamaram a mim por socorro de seu coração, embora continuassem uivando sobre as suas camas. Estavam vadiando por causa do seu cereal e do seu vinho doce; voltavam-se contra mim.

[[v28-7-15]]

^<<v28-7-15,15>>^ E eu, da minha parte, apliquei a disciplina; fortaleci os seus braços, porém, continuaram a maquinar o mal contra mim.

[[v28-7-16]]

^<<v28-7-16,16>>^ E passaram a retornar, não a algo mais elevado;^&#42;1^ tinham-se tornado como um arco frouxo. Seus príncipes cairão à espada por causa da verberação da sua língua. Esta será a caçoada deles na terra do Egito.”

[NOTE]
====
. “Não a algo mais elevado.” Lit.: “não para cima”, isto é, não para uma forma elevada de adoração. Hebr.: lo’ ‛al.
====

'''

xref:028-oseias/028-oseias-006.adoc#v28-6-0[&#60; Capítulo Anterior] | <<v28-7-0,Topo>> | xref:028-oseias/028-oseias-008.adoc#v28-8-0[Próximo Capítulo &#62;]