include::./index.adoc[]

[[v28-2-0]]
=== Oseias, 2
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v28-2-1]]

^<<v28-2-1,1>>^ “Dizei aos vossos irmãos: ‘Meu povo!’^&#42;1^ e às vossas irmãs: ‘Ó mulher de que se teve misericórdia!’^&#42;2^

[NOTE]
====
. “Meu povo!” Hebr.: ‛am·mí.
. Lit.: “Com Ela se Teve Misericórdia.” Hebr.: ru·hhá·mah.
====

[[v28-2-2]]

^<<v28-2-2,2>>^ Pleiteai a causa jurídica com a vossa mãe; pleiteai a causa jurídica, porque ela não é minha esposa^&#42;1^ e eu não sou seu marido.^&#42;2^ E ela deve afastar de diante de si a sua fornicação e de entre os seus seios os seus atos de adultério,

[NOTE]
====
. Ou “minha mulher”. Hebr.: ’ish·tí.
. Ou “seu homem”. Hebr.: ’i·sháh.
====

[[v28-2-3]]

^<<v28-2-3,3>>^ para que eu não a dispa e realmente a ponha como no dia em que nasceu, e realmente a torne semelhante a um ermo, e a ponha semelhante a uma terra árida, e a mate de sede.

[[v28-2-4]]

^<<v28-2-4,4>>^ E não terei misericórdia para com os seus filhos, porque são filhos de fornicação.

[[v28-2-5]]

^<<v28-2-5,5>>^ Pois a mãe deles cometeu fornicação. Aquela que esteve grávida deles tem agido vergonhosamente, pois disse: ‘Quero ir atrás dos que me amam apaixonadamente, os que me dão meu pão e minha água, minha lã e meu linho, meu azeite e minha bebida.’

[[v28-2-6]]

^<<v28-2-6,6>>^ “Portanto, eis que cerco o teu caminho com uma sebe de espinhos; e vou erguer um muro de pedras contra ela, de modo que não achará as suas próprias sendas.

[[v28-2-7]]

^<<v28-2-7,7>>^ E ela realmente irá no encalço dos seus amantes apaixonados, mas não os alcançará; e certamente os procurará, mas não [os] achará. E terá de dizer: ‘Quero ir e voltar a meu marido, o primeiro, porque me ia melhor naquele tempo do que agora.’

[[v28-2-8]]

^<<v28-2-8,8>>^ Mas ela mesma não reconheceu que fui eu quem lhe dera o cereal, e o vinho doce, e o azeite, e que fiz abundar para ela a própria prata, e ouro, [que] usaram para Baal.^&#42;1^

[NOTE]
====
. Ou “que transformaram em [imagem de] Baal”.
====

[[v28-2-9]]

^<<v28-2-9,9>>^ “‘Por isso retornarei e certamente tirarei meu cereal no seu tempo e meu vinho doce na sua época, e vou arrebatar a minha lã e o meu linho cobrindo a sua nudez.

[[v28-2-10]]

^<<v28-2-10,10>>^ E agora exporei as suas partes pudendas aos olhos de seus amantes apaixonados, e nenhum homem^&#42;1^ a arrebatará da minha mão.

[NOTE]
====
. “E . . . homem.” Hebr.: we’ísh.
====

[[v28-2-11]]

^<<v28-2-11,11>>^ E certamente farei cessar toda a sua exultação, sua festividade, sua lua nova e seu sábado, e toda época festiva sua.

[[v28-2-12]]

^<<v28-2-12,12>>^ E vou desolar sua videira e sua figueira, das quais ela disse: “São um presente que me foi dado pelos meus amantes apaixonados”; e vou constituí-las em floresta e o animal selvático do campo certamente as devorará.

[[v28-2-13]]

^<<v28-2-13,13>>^ E eu vou ajustar contas com ela pelos dias das imagens de Baal,^&#42;1^ às quais ela continuou a fazer fumaça sacrificial, quando se ataviava com seu anel e com seu adorno, e quando ia atrás dos seus amantes apaixonados, e era eu quem ela esquecia’, é a pronunciação de Jeová.

[NOTE]
====
. Ou “dos Baalins”. Hebr.: hab·Be‛a·lím; gr.: Ba·a·lím; lat.: Bá·a·lim.
====

[[v28-2-14]]

^<<v28-2-14,14>>^ “‘Portanto, eis que a induzirei e vou fazê-la ir ao ermo, e vou falar-lhe ao coração.

[[v28-2-15]]

^<<v28-2-15,15>>^ E dali em diante vou dar-lhe seus vinhedos, e a baixada^&#42;1^ de Acor^&#42;2^ como entrada à esperança; e ela certamente responderá ali como nos dias de sua mocidade e como no dia em que subiu da terra do Egito.

[NOTE]
====
. Ou “o vale”.
. Significando “Banimento; Dificuldade”.
====

[[v28-2-16]]

^<<v28-2-16,16>>^ E naquele dia terá de acontecer’, é a pronunciação de Jeová, ‘que [me] chamarás de meu esposo,^&#42;1^ e não mais me chamarás de meu dono’.^&#42;2^

[NOTE]
====
. Ou “meu homem”. Hebr.: ’i·shí.
. Ou “meu baal”. Hebr.: ba‛·lí.
====

[[v28-2-17]]

^<<v28-2-17,17>>^ “‘E vou remover de sua boca os nomes das imagens de Baal e não serão mais lembradas^&#42;1^ pelo seu nome.

[NOTE]
====
. Ou “mencionadas”.
====

[[v28-2-18]]

^<<v28-2-18,18>>^ E naquele dia certamente concluirei para eles um pacto em conexão com o animal selvático do campo, e com a criatura voadora dos céus, e com a coisa rastejante do solo, e quebrarei o arco e a espada, e a guerra, [eliminando-os] do país, e vou fazer que se deitem em segurança.

[[v28-2-19]]

^<<v28-2-19,19>>^ E vou tomar-te por noiva por tempo indefinido e vou tomar-te por noiva em justiça, e em juízo, e em benevolência,^&#42;1^ e em misericórdias.

[NOTE]
====
. Ou “e em amor leal”. Hebr.: u·vehhé·sedh.
====

[[v28-2-20]]

^<<v28-2-20,20>>^ E vou tomar-te por noiva em fidelidade; e certamente conhecerás a Jeová.’^&#42;1^

[NOTE]
====
. “Conhecerás a Jeová”, MLXXSy; Vg e cerca de 45 mss. hebr.: “saberás que eu sou Jeová”.
====

[[v28-2-21]]

^<<v28-2-21,21>>^ “‘E naquele dia terá de acontecer que responderei’, é a pronunciação de Jeová, ‘responderei aos céus, e eles, da sua parte, responderão à terra;

[[v28-2-22]]

^<<v28-2-22,22>>^ e a terra, da sua parte, responderá ao cereal, e ao vinho doce, e ao azeite; e eles, da sua parte, responderão a Jezreel [‘Deus semeará’].

[[v28-2-23]]

^<<v28-2-23,23>>^ E certamente a semearei como semente para mim na terra, e vou ter misericórdia para com aquela com que não se teve misericórdia,^&#42;1^ e vou dizer aos que não são meu povo:^&#42;2^ “Tu és meu povo”; e eles, da sua parte,^&#42;3^ dirão: “[Tu és] meu Deus.”’”^&#42;4^

[NOTE]
====
. “Aquela com quem não se teve misericórdia.” Hebr.: lo’ ru·hhá·mah. Veja 1:6 n.: “Lo-Ruama”.
. Ou “ao que não é meu povo”. Hebr.: lelo’-‛am·mí. Veja 1:9 n.: “Lo-Ami”.
. Lit.: “ele mesmo”, referindo-se ao “povo”, hebr. masc. sing.
. “Meu Deus.” Hebr.: ’Elo·haí.
====

'''

xref:028-oseias/028-oseias-001.adoc#v28-1-0[&#60; Capítulo Anterior] | <<v28-2-0,Topo>> | xref:028-oseias/028-oseias-003.adoc#v28-3-0[Próximo Capítulo &#62;]