include::./index.adoc[]

[[v28-4-0]]
=== Oseias, 4
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v28-4-1]]

^<<v28-4-1,1>>^ Ouvi a palavra de Jeová, ó filhos de Israel, porque Jeová tem uma causa jurídica contra os habitantes da terra,^&#42;1^ pois não há verdade, nem benevolência,^&#42;2^ nem conhecimento de Deus na terra.

[NOTE]
====
. “Da terra.” Hebr.: ha·’á·rets.
. Ou “amor leal”. Hebr.: hhé·sedh.
====

[[v28-4-2]]

^<<v28-4-2,2>>^ Irrompeu o proferimento de maldições, e a prática do engano, e assassinato, e furto, e adultério, e atos de derramamento de sangue têm tocado em [outros] atos de derramamento de sangue.

[[v28-4-3]]

^<<v28-4-3,3>>^ Por isso a terra pranteará e todo habitante nela terá de definhar-se com o animal selvático do campo e com a criatura voadora dos céus, e até mesmo os próprios peixes do mar serão ajuntados [na morte].^&#42;1^

[NOTE]
====
. Ou “morrerão”; ou: “serão levados embora”. Veja Is 57:1.
====

[[v28-4-4]]

^<<v28-4-4,4>>^ “No entanto, que nenhum homem contenda e que nenhum homem repreenda, visto que o teu povo é como aqueles que contendem com o sacerdote.^&#42;1^

[NOTE]
====
. M é aqui obscuro.
====

[[v28-4-5]]

^<<v28-4-5,5>>^ E certamente tropeçarás de dia, e até mesmo o profeta terá de tropeçar contigo como à noite. E eu vou silenciar a tua mãe.

[[v28-4-6]]

^<<v28-4-6,6>>^ Meu povo certamente será silenciado, pois não há conhecimento. Visto que tu rejeitaste o conhecimento, também eu te rejeitarei para que não me sirvas como sacerdote; e [visto] que te estás esquecendo da lei de teu Deus,^&#42;1^ eu me esquecerei dos teus filhos, sim, eu.

[NOTE]
====
. “Teu Deus.” Hebr.: ’Elo·heí·kha.
====

[[v28-4-7]]

^<<v28-4-7,7>>^ Pecaram contra mim na proporção da sua multidão. Trocaram a minha própria glória^&#42;1^ pela mera desonra.

[NOTE]
====
. “Trocaram a minha própria glória” era a versão original. Os soferins emendaram (alteraram) o texto para rezar: “Trocarei a própria glória deles.” TSy confirmam a versão original do verbo. Veja Ap. 2B.
====

[[v28-4-8]]

^<<v28-4-8,8>>^ Continuam a devorar o pecado do meu povo e continuam a levantar a sua alma^&#42;1^ ao seu erro.

[NOTE]
====
. “Sua(s) alma(s)”, TLXXSyVg e cerca de 20 mss. hebr.; M: “sua alma (seu desejo de alma; almejo)”. Veja Ap. 4A.
====

[[v28-4-9]]

^<<v28-4-9,9>>^ “E terá de tornar-se para o povo assim como para o sacerdote; e certamente ajustarei contas com eles pelos seus caminhos; e farei recair sobre eles as suas ações.

[[v28-4-10]]

^<<v28-4-10,10>>^ E realmente comerão, mas não se saciarão. Realmente tratarão [as mulheres] como meretrizes; mas não aumentarão, porque deixaram de atentar para o próprio Jeová.

[[v28-4-11]]

^<<v28-4-11,11>>^ A fornicação,^&#42;1^ e o vinho, e o vinho doce é que tiram o bom motivo.^&#42;2^

[NOTE]
====
. “Fornicação.” Hebr.: zenúth; gr.: por·neí·an; lat.: for·ni·cá·ti·o. Veja Ap. 5A.
. Lit.: “tiram coração”. Hebr.: yiq·qahh·lév.
====

[[v28-4-12]]

^<<v28-4-12,12>>^ Meu próprio povo está consultando seu [ídolo] de madeira,^&#42;1^ e seu próprio bordão os está informando; pois o próprio espírito de fornicação fez que se transviassem e pela fornicação saem de debaixo de seu Deus.^&#42;2^

[NOTE]
====
. Lit.: “sua árvore (madeira)”.
. “Seu Deus.” Hebr.: Elo·heh·hém.
====

[[v28-4-13]]

^<<v28-4-13,13>>^ Oferecem sacrifícios nos cumes dos montes e fazem fumaça sacrificial nos morros, debaixo da árvore maciça, e do estoraque, e da árvore grande, porque sua sombra é boa. Por isso é que as vossas filhas cometem fornicação e as vossas próprias noras cometem adultério.

[[v28-4-14]]

^<<v28-4-14,14>>^ “Não ajustarei contas com as vossas filhas por cometerem fornicação e com as vossas noras por cometerem adultério. Pois, no que se refere aos [homens], é com as meretrizes que eles se retiram e é com as prostitutas de templo que oferecem sacrifícios; e o povo [que] não entende será pisoteado.

[[v28-4-15]]

^<<v28-4-15,15>>^ Embora cometas fornicação, ó Israel, não se torne Judá culpado, e não chegueis a Gilgal, nem subais a Bete-Áven, nem jureis: ‘Por Jeová que vive!’

[[v28-4-16]]

^<<v28-4-16,16>>^ Pois Israel se tornou obstinado igual a uma vaca obstinada. É agora que Jeová os pastoreará como a um carneirinho num lugar espaçoso?

[[v28-4-17]]

^<<v28-4-17,17>>^ Efraim uniu-se a ídolos. Deixa-o ficar!

[[v28-4-18]]

^<<v28-4-18,18>>^ Tendo sumido a sua cerveja de trigo,^&#42;1^ trataram [a mulher] positivamente como meretriz. Os que a escudavam decididamente amaram a desonra.

[NOTE]
====
. Ou “sua bebida alcoólica”. Hebr.: sov·’ám.
====

[[v28-4-19]]

^<<v28-4-19,19>>^ Um vento^&#42;1^ a embrulhou nas suas asas. E envergonhar-se-ão dos seus sacrifícios.”

[NOTE]
====
. Ou: “Um espírito.” Hebr.: rú·ahh; gr.: pneú·ma·tos; lat.: spí·ri·tus.
====

'''

xref:028-oseias/028-oseias-003.adoc#v28-3-0[&#60; Capítulo Anterior] | <<v28-4-0,Topo>> | xref:028-oseias/028-oseias-005.adoc#v28-5-0[Próximo Capítulo &#62;]