include::./index.adoc[]

[[v41-9-0]]
=== Marcos, 9
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v41-9-1]]

^<<v41-9-1,1>>^ Ainda mais, prosseguiu a dizer-lhes: “Deveras, eu vos digo: Há alguns dos que estão parados aqui, que não provarão absolutamente a morte, até que primeiro vejam o reino de Deus já vindo em poder.”

[[v41-9-2]]

^<<v41-9-2,2>>^ Concordemente, seis dias depois, Jesus tomou a Pedro, e a Tiago, e a João, e os levou a sós a um alto monte. E ele foi transfigurado diante deles,

[[v41-9-3]]

^<<v41-9-3,3>>^ e sua roupagem exterior tornou-se cintilante, muito mais branca do que qualquer lavadeiro na terra poderia alvejar.

[[v41-9-4]]

^<<v41-9-4,4>>^ Apareceu-lhes também Elias com Moisés, e estes estavam conversando com Jesus.

[[v41-9-5]]

^<<v41-9-5,5>>^ E, como resposta, Pedro disse a Jesus: “Rabi, é excelente que estejamos aqui; armemos, pois, três tendas, uma para ti, e uma para Moisés, e uma para Elias.”

[[v41-9-6]]

^<<v41-9-6,6>>^ De fato, não sabia que resposta devia dar, porque ficaram bastante temerosos.

[[v41-9-7]]

^<<v41-9-7,7>>^ E formou-se uma nuvem, encobrindo-os, e uma voz saiu da nuvem: “Este é meu Filho, o amado; escutai-o.”

[[v41-9-8]]

^<<v41-9-8,8>>^ Repentinamente, porém, olharam em volta e não viram mais ninguém com eles, a não ser apenas Jesus.

[[v41-9-9]]

^<<v41-9-9,9>>^ Ao descerem do monte, ordenou-lhes expressamente que não relatassem a ninguém o que viram, até depois de o Filho do homem se ter levantado dentre os mortos.

[[v41-9-10]]

^<<v41-9-10,10>>^ E tomaram a palavra a peito,^&#42;1^ mas discutiram entre si o que significava este levantamento dentre os mortos.

[NOTE]
====
. Ou “guardaram a palavra para si mesmos”.
====

[[v41-9-11]]

^<<v41-9-11,11>>^ E começaram a interrogá-lo, dizendo: “Por que dizem os escribas que primeiro tem de vir Elias?”

[[v41-9-12]]

^<<v41-9-12,12>>^ Disse-lhes ele: “Elias vem primeiro e restabelece todas as coisas; mas, como é que está escrito a respeito do Filho do homem, que ele tem de passar por muitos sofrimentos e não ser tido em conta?

[[v41-9-13]]

^<<v41-9-13,13>>^ Mas eu vos digo: Elias, de fato, já veio, e fizeram com ele quantas coisas quiseram, assim como está escrito a seu respeito.”

[[v41-9-14]]

^<<v41-9-14,14>>^ Ao chegarem então perto dos outros discípulos, notaram uma grande multidão em volta deles e escribas discutindo com eles.

[[v41-9-15]]

^<<v41-9-15,15>>^ Mas, assim que toda a multidão o avistou, ficaram atônitos, e, correndo para ele, começaram a cumprimentá-lo.

[[v41-9-16]]

^<<v41-9-16,16>>^ E ele lhes perguntou: “O que estais discutindo com eles?”

[[v41-9-17]]

^<<v41-9-17,17>>^ E um da multidão respondeu-lhe: “Instrutor, eu te trouxe meu filho, porque tem um espírito sem fala;

[[v41-9-18]]

^<<v41-9-18,18>>^ e, onde quer que o apanhe, lança-o ao chão, e ele espuma e range os dentes, e perde a sua força. E eu disse aos teus discípulos que o expulsassem, mas eles não foram capazes.”

[[v41-9-19]]

^<<v41-9-19,19>>^ Em resposta, ele lhes disse: “Ó geração sem fé, até quando terei de continuar convosco? Até quando terei de suportar-vos? Trazei-mo.”

[[v41-9-20]]

^<<v41-9-20,20>>^ De modo que lho trouxeram. Mas à vista dele, o espírito lançou [o menino]^&#42;1^ imediatamente em convulsões, e depois de ele cair ao chão, rolava por ali espumando.

[NOTE]
====
. Lit.: “lançou-o”.
====

[[v41-9-21]]

^<<v41-9-21,21>>^ E perguntou ao pai dele: “Há quanto tempo lhe acontece isso?” Ele disse: “Desde a infância;

[[v41-9-22]]

^<<v41-9-22,22>>^ e repetidas vezes o lança tanto no fogo como na água para o destruir. Mas, se puderes fazer algo, tem pena de nós e ajuda-nos.”

[[v41-9-23]]

^<<v41-9-23,23>>^ Jesus disse-lhe: “Esta expressão: ‘Se puderes’! Ora, todas as coisas podem suceder ao que tem fé.”

[[v41-9-24]]

^<<v41-9-24,24>>^ Clamando imediatamente, o pai do menino dizia: “Tenho fé! Ajuda-me onde necessito de fé!”^&#42;1^

[NOTE]
====
. Lit.: “Ajuda a minha falta de fé!”
====

[[v41-9-25]]

^<<v41-9-25,25>>^ Jesus, observando então que a multidão afluía, censurou o espírito impuro, dizendo-lhe: “Espírito sem fala e surdo, ordeno-te que saias dele e não entres mais nele.”

[[v41-9-26]]

^<<v41-9-26,26>>^ E depois de clamar e de passar por muitas convulsões, saiu; e [o menino] ficou como que morto, de modo que a maioria deles dizia: “Ele está morto!”

[[v41-9-27]]

^<<v41-9-27,27>>^ Mas Jesus o tomou pela mão e o levantou, e ele se ergueu.

[[v41-9-28]]

^<<v41-9-28,28>>^ Assim, depois de entrar numa casa, seus discípulos passaram a perguntar-lhe em particular: “Por que não o pudemos expulsar?”

[[v41-9-29]]

^<<v41-9-29,29>>^ E ele lhes disse: “Esta espécie não pode sair exceto por oração.”

[[v41-9-30]]

^<<v41-9-30,30>>^ Partiram dali e passaram através da Galiléia, mas ele não quis que se soubesse disso.

[[v41-9-31]]

^<<v41-9-31,31>>^ Pois estava ensinando os seus discípulos e dizia-lhes: “O Filho do homem há de ser entregue^&#42;1^ às mãos dos homens, e matá-lo-ão; mas, embora seja morto, será levantado três dias depois.”

[NOTE]
====
. Ou “traído”.
====

[[v41-9-32]]

^<<v41-9-32,32>>^ No entanto, não estavam entendendo a declaração e tinham medo de interrogá-lo.

[[v41-9-33]]

^<<v41-9-33,33>>^ E entraram em Cafarnaum. Então, quando ele estava dentro da casa, fez-lhes a pergunta: “Sobre que estáveis disputando na estrada?”

[[v41-9-34]]

^<<v41-9-34,34>>^ Eles ficaram calados, pois, na estrada tinham disputado entre si quem era maior.

[[v41-9-35]]

^<<v41-9-35,35>>^ Assentou-se assim, chamou os doze e disse-lhes: “Se alguém quer ser o primeiro, tem de ser o último de todos e ministro de todos.”

[[v41-9-36]]

^<<v41-9-36,36>>^ E tomou uma criancinha, postou-a no meio deles, e, pondo os seus braços em volta dela, disse-lhes:

[[v41-9-37]]

^<<v41-9-37,37>>^ “Todo aquele que receber uma dessas criancinhas à base do meu nome, a mim me recebe; e todo aquele que me receber, recebe não [só] a mim, mas [também] aquele que me enviou.”

[[v41-9-38]]

^<<v41-9-38,38>>^ João disse-lhe: “Instrutor, vimos certo homem expulsar demônios pelo uso de teu nome, e tentamos impedi-lo, porque não nos acompanhava.”

[[v41-9-39]]

^<<v41-9-39,39>>^ Mas Jesus disse: “Não tenteis impedi-lo, porque ninguém há que faça uma obra poderosa à base do meu nome que logo possa injuriar-me;

[[v41-9-40]]

^<<v41-9-40,40>>^ pois quem não é contra nós, é por nós.

[[v41-9-41]]

^<<v41-9-41,41>>^ Porque quem vos der um copo de água a beber em razão de pertencerdes a Cristo, deveras, eu vos digo que de nenhum modo perderá a sua recompensa.

[[v41-9-42]]

^<<v41-9-42,42>>^ Mas, quem fizer tropeçar a um destes pequenos que crêem, melhor lhe seria que se lhe pusesse em volta do pescoço uma mó daquelas que o burro faz girar e que fosse realmente lançado no mar.

[[v41-9-43]]

^<<v41-9-43,43>>^ “E se a tua mão te fizer alguma vez tropeçar, corta-a; melhor te é entrares na vida aleijado, do que ires com as duas mãos para a Geena,^&#42;1^ para o fogo inextinguível.

[NOTE]
====
. Veja Ap. 4C.
====

[[v41-9-44]]

^<<v41-9-44,44>>^ ^&#42;1^ ——

[NOTE]
====
. אBCW omitem isso; AD: “onde o seu gusano não morre e o fogo não se extingue”. (Veja v. 48.)
====

[[v41-9-45]]

^<<v41-9-45,45>>^ E, se o teu pé te fizer tropeçar, corta-o; melhor te é entrares na vida coxo, do que seres com os dois pés lançado na Geena.

[[v41-9-46]]

^<<v41-9-46,46>>^ ^&#42;1^ ——

[NOTE]
====
. אBCW omitem isso; AD: “onde o seu gusano não morre e o fogo não se extingue”. (Veja v. 48.)
====

[[v41-9-47]]

^<<v41-9-47,47>>^ E, se o teu olho te fizer tropeçar, lança-o fora; melhor te é entrares com um olho no reino de Deus, do que seres com os dois olhos lançado na Geena,

[[v41-9-48]]

^<<v41-9-48,48>>^ onde o seu gusano não morre e o fogo não se extingue.

[[v41-9-49]]

^<<v41-9-49,49>>^ “Porque cada um tem de ser salgado com fogo.

[[v41-9-50]]

^<<v41-9-50,50>>^ O sal é excelente; mas, se o sal perder a sua força,^&#42;1^ com que é que o temperareis? Tende sal em vós mesmos e mantende a paz entre vós.”

[NOTE]
====
. Ou então, “ficar sem salinidade”.
====

'''

xref:041-marcos/041-marcos-008.adoc#v41-8-0[&#60; Capítulo Anterior] | <<v41-9-0,Topo>> | xref:041-marcos/041-marcos-010.adoc#v41-10-0[Próximo Capítulo &#62;]