include::./index.adoc[]

[[v41-3-0]]
=== Marcos, 3
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v41-3-1]]

^<<v41-3-1,1>>^ Novamente, ele entrou numa sinagoga, e ali havia um homem com a mão ressequida.

[[v41-3-2]]

^<<v41-3-2,2>>^ Vigiaram-no assim de perto para ver se curaria o homem no sábado, a fim de que pudessem acusá-lo.

[[v41-3-3]]

^<<v41-3-3,3>>^ E ele disse ao homem com a mão ressequida: “Levanta-te [e vem] para o centro.”

[[v41-3-4]]

^<<v41-3-4,4>>^ A seguir, disse-lhes: “É lícito, no sábado, fazer uma boa ação ou fazer uma má ação, salvar ou matar uma alma?”^&#42;1^ Mas eles ficaram calados.

[NOTE]
====
. Ou “uma vida”. Gr.: psy·khén; lat.: á·ni·mam; J17,18,22(hebr.): né·fesh. Veja Ap. 4A.
====

[[v41-3-5]]

^<<v41-3-5,5>>^ E, depois de olhar para eles, ao redor, com indignação, estando profundamente contristado com a insensibilidade dos seus corações, disse ao homem: “Estende a tua mão.” E ele a estendeu, e sua mão foi restabelecida.

[[v41-3-6]]

^<<v41-3-6,6>>^ Os fariseus saíram então e começaram imediatamente a entrar em conselho contra ele com os partidários de Herodes,^&#42;1^ a fim de o destruírem.

[NOTE]
====
. Ou “com os herodianos”.
====

[[v41-3-7]]

^<<v41-3-7,7>>^ Mas Jesus, com os seus discípulos, retirou-se para o mar; e seguia-o uma grande multidão da Galiléia e da Judéia.

[[v41-3-8]]

^<<v41-3-8,8>>^ Até mesmo de Jerusalém, e da Iduméia, e de além do Jordão, e dos arredores de Tiro e de Sídon, veio ter com ele uma grande multidão, ao ouvir [falar] de quantas coisas fazia.

[[v41-3-9]]

^<<v41-3-9,9>>^ E ele disse aos seus discípulos que mantivessem continuamente à sua disposição um pequeno barco, para que a multidão não o apertasse.

[[v41-3-10]]

^<<v41-3-10,10>>^ Porque curava a muitos, com o resultado de que todos os que tinham moléstias penosas lançavam-se sobre ele para tocá-lo.

[[v41-3-11]]

^<<v41-3-11,11>>^ Até mesmo os espíritos impuros, sempre que o viam, prostravam-se diante dele e clamavam, dizendo: “Tu és o Filho de Deus.”

[[v41-3-12]]

^<<v41-3-12,12>>^ Muitas vezes, porém, os advertia rigorosamente que não o dessem a conhecer.

[[v41-3-13]]

^<<v41-3-13,13>>^ E subiu a um monte e convocou os que quis, e eles foram ter com ele.

[[v41-3-14]]

^<<v41-3-14,14>>^ E formou [um grupo de] doze, aos quais chamou também de “apóstolos”, para que continuassem com ele e para que pudesse enviá-los a pregar

[[v41-3-15]]

^<<v41-3-15,15>>^ e a ter autoridade para expulsar os demônios.

[[v41-3-16]]

^<<v41-3-16,16>>^ E os [do grupo dos] doze que formou eram Simão, a quem também deu o sobrenome de Pedro,

[[v41-3-17]]

^<<v41-3-17,17>>^ e Tiago, o [filho] de Zebedeu, e João, irmão de Tiago (a estes deu também o sobrenome de Boanerges,^&#42;1^ que significa Filhos do Trovão),

[NOTE]
====
. “Boanerges.” Sir.: Benai Reghshi; J17(hebr.): Beneh-reghóhsh; J18(hebr.): Beneh-rá·ghesh.
====

[[v41-3-18]]

^<<v41-3-18,18>>^ e André, e Filipe, e Bartolomeu, e Mateus, e Tomé, e Tiago, [filho] de Alfeu, e Tadeu, e Simão, o Cananita,

[[v41-3-19]]

^<<v41-3-19,19>>^ e Judas Iscariotes, que mais tarde o traiu.
E ele entrou numa casa.

[[v41-3-20]]

^<<v41-3-20,20>>^ Mais uma vez se ajuntou a multidão, de modo que não puderam mais nem sequer tomar uma refeição.

[[v41-3-21]]

^<<v41-3-21,21>>^ Mas, quando os seus parentes ouviram isso, saíram para o pegarem, pois diziam: “Ele perdeu o juízo.”

[[v41-3-22]]

^<<v41-3-22,22>>^ Também os escribas que desceram de Jerusalém diziam: “Ele está com Belzebu^&#42;1^ e expulsa os demônios por meio do governante dos demônios.”

[NOTE]
====
. “Belzebu”, VgSypJ18; אACDW(gr.): Be·el·ze·boúl; B(gr.): Be·e·ze·boúl; J22(hebr.): Ba·‛al-zevúl.
====

[[v41-3-23]]

^<<v41-3-23,23>>^ Portanto, tendo-os chamado a si, começou a dizer-lhes com ilustrações:^&#42;1^ “Como pode Satanás expulsar a Satanás?

[NOTE]
====
. Ou “parábolas”.
====

[[v41-3-24]]

^<<v41-3-24,24>>^ Ora, se um reino fica dividido contra si mesmo, este reino não pode ficar de pé;

[[v41-3-25]]

^<<v41-3-25,25>>^ e se uma casa fica dividida contra si mesma, esta casa não poderá ficar de pé.

[[v41-3-26]]

^<<v41-3-26,26>>^ Também, se Satanás se levantou contra si mesmo e ficou dividido, não pode ficar de pé, mas está chegando ao fim.

[[v41-3-27]]

^<<v41-3-27,27>>^ De fato, ninguém que tenha entrado na casa dum homem forte é capaz de saquear os seus bens móveis, a menos que primeiro amarre o homem forte, e então saqueará a sua casa.

[[v41-3-28]]

^<<v41-3-28,28>>^ Deveras, eu vos digo que todas as coisas serão perdoadas aos filhos dos homens, não importa que pecados e blasfêmias cometam blasfemamente.

[[v41-3-29]]

^<<v41-3-29,29>>^ No entanto, quem blasfemar contra o espírito santo, nunca terá perdão, mas é culpado de pecado eterno.”

[[v41-3-30]]

^<<v41-3-30,30>>^ Isto, porque diziam: “Ele tem um espírito impuro.”

[[v41-3-31]]

^<<v41-3-31,31>>^ Vieram então sua mãe e seus irmãos, e, visto que estavam em pé do lado de fora, mandaram chamá-lo.

[[v41-3-32]]

^<<v41-3-32,32>>^ Acontece que havia uma multidão sentada em volta dele, de modo que lhe disseram: “Eis que tua mãe e teus irmãos, lá fora, estão-te procurando.”

[[v41-3-33]]

^<<v41-3-33,33>>^ Mas ele lhes disse, em resposta: “Quem é minha mãe e meus irmãos?”

[[v41-3-34]]

^<<v41-3-34,34>>^ E, tendo olhado em volta para os sentados ao redor dele num círculo, disse: “Eis minha mãe e meus irmãos!

[[v41-3-35]]

^<<v41-3-35,35>>^ Todo aquele que faz a vontade de Deus, este é meu irmão, e [minha] irmã e [minha] mãe.”

'''

xref:041-marcos/041-marcos-002.adoc#v41-2-0[&#60; Capítulo Anterior] | <<v41-3-0,Topo>> | xref:041-marcos/041-marcos-004.adoc#v41-4-0[Próximo Capítulo &#62;]