include::./index.adoc[]

[[v41-13-0]]
=== Marcos, 13
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v41-13-1]]

^<<v41-13-1,1>>^ Ao sair do templo, um dos seus discípulos disse-lhe: “Instrutor, vê que sorte de pedras e que sorte de edifícios!”

[[v41-13-2]]

^<<v41-13-2,2>>^ No entanto, Jesus disse-lhe: “Observas estes grandes edifícios? De modo algum ficará aqui pedra sobre pedra sem ser derrubada.”

[[v41-13-3]]

^<<v41-13-3,3>>^ E, enquanto ele estava sentado no Monte das Oliveiras, com o templo à vista, Pedro, e Tiago, e João, e André começaram a perguntar-lhe em particular:

[[v41-13-4]]

^<<v41-13-4,4>>^ “Dize-nos: Quando serão estas coisas e qual será o sinal quando todas estas coisas estão destinadas a chegar a uma terminação?”^&#42;1^

[NOTE]
====
. Ou “fim conjunto”. Veja Mt 13:39 n.: “terminação”.
====

[[v41-13-5]]

^<<v41-13-5,5>>^ Jesus principiou assim a dizer-lhes: “Acautelai-vos de que ninguém vos desencaminhe.

[[v41-13-6]]

^<<v41-13-6,6>>^ Muitos virão à base do meu nome, dizendo: ‘Sou eu’, e desencaminharão a muitos.

[[v41-13-7]]

^<<v41-13-7,7>>^ Além disso, quando ouvirdes [falar] de guerras e de relatos de guerras, não fiqueis apavorados; [estas coisas] têm de acontecer, mas ainda não é o fim.^&#42;1^

[NOTE]
====
. Ou “remate; fim completo; término”. Gr.: τέλος (té·los).
====

[[v41-13-8]]

^<<v41-13-8,8>>^ “Pois nação se levantará^&#42;1^ contra nação e reino contra reino; haverá terremotos^&#42;2^ num lugar após outro; haverá escassez de víveres. Estas [coisas] são um princípio das dores de aflição.

[NOTE]
====
. Ou “se agitará; se excitará”.
. “Terremotos.” Gr.: sei·smoí.
====

[[v41-13-9]]

^<<v41-13-9,9>>^ “Quanto a vós, acautelai-vos; entregar-vos-ão aos tribunais locais^&#42;1^ e sereis espancados nas sinagogas, e sereis postos diante de governadores e reis, por minha causa, em testemunho^&#42;2^ para eles.

[NOTE]
====
. Ou “aos sinédrios inferiores”.
. “Testemunho.” Gr.: mar·tý·ri·on; lat.: te·sti·mó·ni·um.
====

[[v41-13-10]]

^<<v41-13-10,10>>^ Também, em todas as nações têm de ser pregadas^&#42;1^ primeiro as boas novas.

[NOTE]
====
. Ou “ser proclamadas”. Gr.: ke·ry·khthé·nai; lat.: prae·di·cá·ri. Veja Da 5:29 n.: “proclamaram”.
====

[[v41-13-11]]

^<<v41-13-11,11>>^ Mas, quando vos levarem para vos entregar, não estejais ansiosos de antemão sobre o que haveis de falar; mas, o que vos for dado naquela hora, isso falai, porque não sois vós quem fala, mas o espírito santo.

[[v41-13-12]]

^<<v41-13-12,12>>^ Outrossim, irmão entregará irmão à morte, e o pai ao filho, e os filhos se levantarão contra os pais, e os farão matar;

[[v41-13-13]]

^<<v41-13-13,13>>^ e vós sereis pessoas odiadas por todos, por causa do meu nome. Mas aquele que tiver perseverado até o fim^&#42;1^ é o que será salvo.

[NOTE]
====
. Veja v. 7 n.
====

[[v41-13-14]]

^<<v41-13-14,14>>^ “No entanto, quando avistardes a coisa repugnante que causa desolação estar de pé num lugar onde não devia (que o leitor use de discernimento), então, comecem a fugir para os montes os que estiverem na Judéia.

[[v41-13-15]]

^<<v41-13-15,15>>^ Que o homem [que estiver] no alto da casa não desça, nem entre para tirar algo de sua casa;

[[v41-13-16]]

^<<v41-13-16,16>>^ e que o homem [que estiver] no campo não volte para as coisas deixadas atrás, para apanhar sua roupa exterior.

[[v41-13-17]]

^<<v41-13-17,17>>^ Ai das mulheres grávidas e das que amamentarem naqueles dias!

[[v41-13-18]]

^<<v41-13-18,18>>^ Persisti em orar que não ocorra no tempo do inverno;

[[v41-13-19]]

^<<v41-13-19,19>>^ pois estes dias serão [dias de] tribulação tal como nunca ocorreu desde [o] princípio da criação, que Deus criou, até esse tempo,^&#42;1^ nem ocorrerá de novo.

[NOTE]
====
. Lit.: “até o tempo atual”.
====

[[v41-13-20]]

^<<v41-13-20,20>>^ De fato, se Jeová^&#42;1^ não tivesse abreviado os dias, nenhuma carne se salvaria. Mas, por causa dos escolhidos, que ele escolheu, abreviou os dias.

[NOTE]
====
. Veja Ap. 1D.
====

[[v41-13-21]]

^<<v41-13-21,21>>^ “Então, também, se alguém vos disser: ‘Eis aqui está o Cristo!’, ‘eis ali está ele!’, não [o] acrediteis.

[[v41-13-22]]

^<<v41-13-22,22>>^ Porque surgirão falsos cristos e falsos profetas, e farão sinais e prodígios, a fim de desencaminhar, se possível, os escolhidos.

[[v41-13-23]]

^<<v41-13-23,23>>^ Vós, portanto, vigiai; eu vos disse todas as coisas de antemão.

[[v41-13-24]]

^<<v41-13-24,24>>^ “Mas, naqueles dias, depois dessa tribulação, o sol ficará escurecido e a lua não dará a sua luz,

[[v41-13-25]]

^<<v41-13-25,25>>^ e as estrelas cairão do céu, e os poderes que estão nos céus serão abalados.

[[v41-13-26]]

^<<v41-13-26,26>>^ E então verão o Filho do homem vir^&#42;1^ nas nuvens, com grande poder e glória.

[NOTE]
====
. “Vir.” Em gr.: er·khó·me·non.
====

[[v41-13-27]]

^<<v41-13-27,27>>^ E então enviará os anjos e ajuntará os seus escolhidos desde os quatro ventos, desde a extremidade da terra até a extremidade do céu.

[[v41-13-28]]

^<<v41-13-28,28>>^ “Agora, aprendei da figueira a ilustração: Assim que o seu ramo novo se torna tenro e brota suas folhas, sabeis que o verão está próximo.

[[v41-13-29]]

^<<v41-13-29,29>>^ Assim também vós, quando virdes estas coisas acontecer, sabei que ele está próximo, às portas.

[[v41-13-30]]

^<<v41-13-30,30>>^ Deveras, eu vos digo que esta geração^&#42;1^ de modo algum passará até que todas estas coisas aconteçam.

[NOTE]
====
. “Geração.” Gr.: ge·ne·á; diferente de gé·nos, “raça”, como em 1Pe 2:9.
====

[[v41-13-31]]

^<<v41-13-31,31>>^ Céu e terra passarão, mas as minhas palavras não passarão.

[[v41-13-32]]

^<<v41-13-32,32>>^ “Acerca daquele dia e daquela hora ninguém sabe, nem os anjos no céu, nem o Filho, senão o Pai.

[[v41-13-33]]

^<<v41-13-33,33>>^ Persisti em olhar, mantende-vos despertos, pois não sabeis quando é o tempo designado.

[[v41-13-34]]

^<<v41-13-34,34>>^ É semelhante a um homem que viajou para fora e deixou a sua casa, dando autoridade aos seus escravos, a cada um o seu trabalho, e ordenou ao porteiro que se mantivesse vigilante.

[[v41-13-35]]

^<<v41-13-35,35>>^ Portanto, mantende-vos vigilantes, pois não sabeis quando vem o senhor da casa, quer tarde no dia,^&#42;1^ quer à meia-noite,^&#42;2^ quer ao canto do galo,^&#42;3^ quer cedo de manhã;^&#42;4^

[NOTE]
====
. “Tarde no dia.” Esta era a primeira vigília segundo a divisão gr. e romana da noite, desde o pôr-do-sol até por volta das 21 horas.
. “À meia-noite.” Esta era a segunda vigília segundo a divisão gr. e romana da noite, desde por volta das 21 horas até a meia-noite.
. “Ao canto do galo.” Esta era a terceira vigília segundo a divisão gr. e romana da noite, desde meia-noite até por volta das 3 horas da madrugada.
. “Cedo de manhã.” Esta era a quarta vigília segundo a divisão gr. e romana da noite, desde por volta das 3 horas da madrugada até o nascer do sol.
====

[[v41-13-36]]

^<<v41-13-36,36>>^ a fim de que, ao chegar ele repentinamente, não vos ache dormindo.

[[v41-13-37]]

^<<v41-13-37,37>>^ Mas, o que eu vos digo, digo a todos: Mantende-vos vigilantes.”

'''

xref:041-marcos/041-marcos-012.adoc#v41-12-0[&#60; Capítulo Anterior] | <<v41-13-0,Topo>> | xref:041-marcos/041-marcos-014.adoc#v41-14-0[Próximo Capítulo &#62;]