include::./index.adoc[]

[[v41-11-0]]
=== Marcos, 11
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v41-11-1]]

^<<v41-11-1,1>>^ Ora, quando chegaram perto de Jerusalém, a Betfagé e Betânia, no Monte das Oliveiras, mandou dois de seus discípulos

[[v41-11-2]]

^<<v41-11-2,2>>^ e disse-lhes: “Ide à aldeia que está ao alcance de vossa vista, e assim que entrardes nela, achareis amarrado um jumentinho em que ninguém da humanidade ainda montou; soltai-o e trazei-o.

[[v41-11-3]]

^<<v41-11-3,3>>^ E, se alguém vos disser: ‘Por que fazeis isso?’ dizei: ‘O Senhor precisa dele, e o mandará logo de volta para cá.’”

[[v41-11-4]]

^<<v41-11-4,4>>^ Foram assim embora e acharam o jumentinho amarrado à porta, do lado de fora, numa rua lateral, e soltaram-no.

[[v41-11-5]]

^<<v41-11-5,5>>^ Mas, alguns dos parados ali começaram a dizer-lhes: “Que estais fazendo, soltando o jumentinho?”

[[v41-11-6]]

^<<v41-11-6,6>>^ Disseram a estes exatamente o que Jesus dissera; e deixaram-nos ir.

[[v41-11-7]]

^<<v41-11-7,7>>^ E trouxeram o jumentinho a Jesus e puseram nele suas roupas exteriores, e ele se sentou nele.

[[v41-11-8]]

^<<v41-11-8,8>>^ Também, muitos estenderam suas roupas exteriores pela estrada, mas outros cortaram folhagem dos campos.

[[v41-11-9]]

^<<v41-11-9,9>>^ E os que iam na frente e os que vinham atrás clamavam: “Salva, rogamos!^&#42;1^ Bendito é aquele que vem em nome de Jeová!^&#42;2^

[NOTE]
====
. Lit.: “Hosana.” Gr.: Ho·san·ná; J7-14,16-18,22(hebr.): Hoh·sha‛·ná’, “Salva, rogamos”.
. Veja Ap. 1D.
====

[[v41-11-10]]

^<<v41-11-10,10>>^ Bendito é o reino vindouro de nosso pai Davi!^&#42;1^ Salva, rogamos, nas maiores alturas!”^&#42;2^

[NOTE]
====
. “O reino vindouro de nosso pai Davi”, אBCD; ASyh: “o reino de nosso pai Davi que vem no nome do Senhor”; J7,8,10-14,16,17: “o reino de nosso pai Davi que vem no nome de Jeová”.
. Ou “nos lugares mais altos”.
====

[[v41-11-11]]

^<<v41-11-11,11>>^ E ele entrou em Jerusalém, no templo; e olhou em volta, para todas as coisas, e, visto que a hora já estava avançada, saiu com os doze para Betânia.

[[v41-11-12]]

^<<v41-11-12,12>>^ No dia seguinte, tendo eles saído de Betânia, ficou com fome.

[[v41-11-13]]

^<<v41-11-13,13>>^ E avistando de certa distância uma figueira que tinha folhas, dirigiu-se para ela, para ver se acharia nela algo. Mas, chegando-se a ela, não encontrou nada senão folhas, pois não era a estação dos figos.

[[v41-11-14]]

^<<v41-11-14,14>>^ Assim, como resposta, ele lhe disse: “Nunca mais ninguém coma de ti fruto.” E os seus discípulos estavam escutando.

[[v41-11-15]]

^<<v41-11-15,15>>^ Chegaram então a Jerusalém. Ali entrou no templo e principiou a lançar fora os que vendiam e compravam no templo, e derrubou as mesas dos cambistas e as bancas dos que vendiam pombas;

[[v41-11-16]]

^<<v41-11-16,16>>^ e não deixou ninguém carregar qualquer utensílio através do templo,

[[v41-11-17]]

^<<v41-11-17,17>>^ mas ensinava e dizia: “Não está escrito: ‘Minha casa será chamada casa de oração para todas as nações’? Mas vós fizestes dela um covil de salteadores.”

[[v41-11-18]]

^<<v41-11-18,18>>^ E os principais sacerdotes e os escribas ouviram isso, e começaram a procurar um meio de destruí-lo; pois estavam com temor dele, porque toda a multidão ficava continuamente assombrada com o seu ensino.

[[v41-11-19]]

^<<v41-11-19,19>>^ E sempre que ficava tarde no dia, saíam da cidade.

[[v41-11-20]]

^<<v41-11-20,20>>^ Mas, passando de manhã cedo, viram a figueira já seca, das raízes para cima.

[[v41-11-21]]

^<<v41-11-21,21>>^ Pedro, portanto, lembrando-se, disse-lhe: “Rabi, eis que se secou a figueira que amaldiçoaste.”

[[v41-11-22]]

^<<v41-11-22,22>>^ E Jesus disse-lhe em resposta: “Tende fé em Deus.

[[v41-11-23]]

^<<v41-11-23,23>>^ Deveras, eu vos digo que quem disser a este monte: ‘Sê levantado e lançado no mar’, e não duvidar no seu coração, mas tiver fé, que aquilo que disser vai acontecer, ele o terá assim.

[[v41-11-24]]

^<<v41-11-24,24>>^ É por isso que vos digo: Todas as coisas pelas quais orais e que pedis, tende fé que praticamente já [as] recebestes, e as tereis.

[[v41-11-25]]

^<<v41-11-25,25>>^ E quando estiverdes orando em pé, perdoai o que tiverdes contra outro; a fim de que o vosso Pai, que está nos céus, também vos perdoe as vossas falhas.”

[[v41-11-26]]

^<<v41-11-26,26>>^ ^&#42;1^ ——

[NOTE]
====
. אBWSys omitem isso; ACDVgSyp: “Mas, se não perdoardes, tampouco vosso Pai, que está nos céus, perdoará as vossas falhas.” (Veja Mt 6:15.)
====

[[v41-11-27]]

^<<v41-11-27,27>>^ E chegaram novamente a Jerusalém. E andando ele pelo templo, chegaram-se a ele os principais sacerdotes, e os escribas, e os anciãos,

[[v41-11-28]]

^<<v41-11-28,28>>^ e começaram a dizer-lhe: “Com que autoridade fazes estas coisas? Ou quem te deu tal autoridade para fazeres estas coisas?”

[[v41-11-29]]

^<<v41-11-29,29>>^ Jesus disse-lhes: “Eu vos farei uma só pergunta. Respondei-me, e eu também vos direi com que autoridade faço estas coisas.

[[v41-11-30]]

^<<v41-11-30,30>>^ Era o batismo de João do céu ou dos homens? Respondei-me.”

[[v41-11-31]]

^<<v41-11-31,31>>^ Começaram então a raciocinar entre si, dizendo: “Se dissermos: ‘Do céu’, ele dirá: ‘Por que é, então, que não acreditastes nele?’

[[v41-11-32]]

^<<v41-11-32,32>>^ Mas, atrevemo-nos a dizer: ‘Dos homens’?” — Estavam com temor da multidão, pois todos consideravam que João tinha sido realmente um profeta.

[[v41-11-33]]

^<<v41-11-33,33>>^ Bem, disseram a Jesus, em resposta: “Não sabemos.” E Jesus disse-lhes: “Tampouco eu vos digo com que autoridade faço estas coisas.”

'''

xref:041-marcos/041-marcos-010.adoc#v41-10-0[&#60; Capítulo Anterior] | <<v41-11-0,Topo>> | xref:041-marcos/041-marcos-012.adoc#v41-12-0[Próximo Capítulo &#62;]