include::./index.adoc[]

[[v41-12-0]]
=== Marcos, 12
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v41-12-1]]

^<<v41-12-1,1>>^ Principiou também a falar-lhes com ilustrações: “Um homem plantou um vinhedo e pôs uma cerca em volta dele, e escavou um recipiente para o lagar, e erigiu uma torre, e o arrendou a lavradores, e foi viajar para fora.

[[v41-12-2]]

^<<v41-12-2,2>>^ Então, na época devida, enviou um escravo aos lavradores, para obter alguns dos frutos do vinhedo da parte dos lavradores.

[[v41-12-3]]

^<<v41-12-3,3>>^ Mas tomaram-no, espancaram-no e mandaram-no embora de mãos vazias.

[[v41-12-4]]

^<<v41-12-4,4>>^ E enviou-lhes novamente outro escravo; e a este bateram na cabeça e desonraram.

[[v41-12-5]]

^<<v41-12-5,5>>^ E enviou outro, e a este mataram; e muitos outros, dos quais espancaram alguns e mataram outros.

[[v41-12-6]]

^<<v41-12-6,6>>^ Ele tinha mais um, um filho amado. Por fim o enviou a eles, dizendo: ‘Respeitarão meu filho.’

[[v41-12-7]]

^<<v41-12-7,7>>^ Mas esses lavradores disseram entre si: ‘Este é o herdeiro. Vinde, matemo-lo, e a herança será nossa.’

[[v41-12-8]]

^<<v41-12-8,8>>^ Tomaram-no assim e mataram-no, e lançaram-no fora do vinhedo.

[[v41-12-9]]

^<<v41-12-9,9>>^ Que fará o dono do vinhedo? Virá e destruirá os lavradores, e dará o vinhedo a outros.

[[v41-12-10]]

^<<v41-12-10,10>>^ Nunca lestes esta escritura: ‘A pedra que os construtores rejeitaram, esta se tem tornado a principal pedra angular.

[[v41-12-11]]

^<<v41-12-11,11>>^ Isto procede de Jeová,^&#42;1^ e é maravilhoso aos nossos olhos’?”

[NOTE]
====
. Veja Ap. 1D.
====

[[v41-12-12]]

^<<v41-12-12,12>>^ Em vista disso, começaram a procurar um meio de se apoderar dele, mas temiam a multidão, porque observavam que falara a ilustração pensando neles. Deixaram-no assim e afastaram-se.

[[v41-12-13]]

^<<v41-12-13,13>>^ A seguir, enviaram-lhe alguns dos fariseus e dos partidários de Herodes,^&#42;1^ para apanhá-lo na sua palavra.

[NOTE]
====
. Ou “dos herodianos”.
====

[[v41-12-14]]

^<<v41-12-14,14>>^ Ao chegarem, disseram-lhe: “Instrutor, sabemos que és veraz e que não te importas com ninguém, pois não olhas para a aparência exterior dos homens, mas ensinas o caminho de Deus em harmonia com a verdade: É lícito ou não pagar a César^&#42;1^ o imposto por cabeça?

[NOTE]
====
. Ou “ao imperador”. Gr.: Kaí·sa·ri.
====

[[v41-12-15]]

^<<v41-12-15,15>>^ Devemos pagar ou não devemos pagar?” Percebendo a hipocrisia deles, disse-lhes: “Por que me pondes à prova? Trazei-me um denário^&#42;1^ para ver.”

[NOTE]
====
. Veja 6:37 n.
====

[[v41-12-16]]

^<<v41-12-16,16>>^ Trouxeram-lhe um. E ele lhes disse: “De quem é esta imagem e inscrição?” Disseram-lhe: “De César.”

[[v41-12-17]]

^<<v41-12-17,17>>^ Jesus disse então: “Pagai de volta^&#42;1^ a César as coisas de César, mas a Deus as coisas de Deus.” E começaram a maravilhar-se dele.

[NOTE]
====
. Lit.: “Dai de volta.”
====

[[v41-12-18]]

^<<v41-12-18,18>>^ Chegaram-se a ele então uns saduceus, que dizem não haver ressurreição, e fizeram-lhe a pergunta:

[[v41-12-19]]

^<<v41-12-19,19>>^ “Instrutor, Moisés nos escreveu que, se o irmão de alguém morre e deixa esposa, mas não deixa filho, seu irmão deve tomar a esposa e suscitar dela descendência para seu irmão.

[[v41-12-20]]

^<<v41-12-20,20>>^ Havia sete irmãos; e o primeiro tomou uma esposa, mas quando morreu, não deixou descendência.

[[v41-12-21]]

^<<v41-12-21,21>>^ E o segundo a tomou, porém morreu sem deixar descendência; e o terceiro, do mesmo modo.

[[v41-12-22]]

^<<v41-12-22,22>>^ E os sete não deixaram nenhuma descendência. Por fim morreu também a mulher.

[[v41-12-23]]

^<<v41-12-23,23>>^ Na ressurreição, de qual deles será ela esposa? Pois os sete a tiveram como esposa.”

[[v41-12-24]]

^<<v41-12-24,24>>^ Jesus disse-lhes: “Não é por isso que estais equivocados, por não conhecerdes nem as Escrituras, nem o poder de Deus?

[[v41-12-25]]

^<<v41-12-25,25>>^ Porque, quando se levantarem dentre os mortos, nem os homens se casam, nem as mulheres são dadas em casamento, mas são como os anjos nos céus.

[[v41-12-26]]

^<<v41-12-26,26>>^ Mas, a respeito dos mortos, que eles são levantados, não lestes no livro de Moisés, no relato sobre o espinheiro, que Deus lhe disse: ‘Eu sou o Deus de Abraão, e o Deus de Isaque, e o Deus de Jacó’?

[[v41-12-27]]

^<<v41-12-27,27>>^ Ele não é Deus de mortos, mas de viventes. Estais muito equivocados.”

[[v41-12-28]]

^<<v41-12-28,28>>^ Ora, um dos escribas, que se aproximara e os ouvira discutindo, sabendo que ele lhes tinha respondido de modo excelente, perguntou-lhe: “Que mandamento é o primeiro de todos?”

[[v41-12-29]]

^<<v41-12-29,29>>^ Jesus respondeu: “O primeiro é: ‘Ouve, ó Israel: Jeová,^&#42;1^ nosso Deus, é um só Jeová,^&#42;2^

[NOTE]
====
. Veja Ap. 1D.
. Veja Ap. 1D.
====

[[v41-12-30]]

^<<v41-12-30,30>>^ e tens de amar a Jeová,^&#42;1^ teu Deus, de todo o teu coração, e de toda a tua alma,^&#42;2^ e de toda a tua mente, e de toda a tua força.’

[NOTE]
====
. Veja Ap. 1D.
. Ou “tua vida”. Gr.: tes psy·khés sou; J17,18,22(hebr.): naf·shekhá.
====

[[v41-12-31]]

^<<v41-12-31,31>>^ O segundo é este: ‘Tens de amar o teu próximo como a ti mesmo.’ Não há outro mandamento maior do que estes.”

[[v41-12-32]]

^<<v41-12-32,32>>^ O escriba disse-lhe: “Instrutor, bem disseste em harmonia com a verdade: ‘Ele é Um só, e não há outro senão Ele’;

[[v41-12-33]]

^<<v41-12-33,33>>^ e este amá-lo de todo o coração e de todo o entendimento, e de toda a força, e este amar o próximo como a si mesmo, vale muito mais do que todos os holocaustos e sacrifícios.”

[[v41-12-34]]

^<<v41-12-34,34>>^ Jesus, em vista disso, discernindo que tinha respondido inteligentemente, disse-lhe: “Não estás longe do reino de Deus.” Mas, ninguém tinha mais coragem de interrogá-lo.

[[v41-12-35]]

^<<v41-12-35,35>>^ No entanto, ao dar uma resposta, Jesus começou a dizer, ao ensinar no templo: “Como é que os escribas dizem que o Cristo é filho de Davi?

[[v41-12-36]]

^<<v41-12-36,36>>^ O próprio Davi disse, pelo espírito santo: ‘Jeová^&#42;1^ disse ao meu Senhor: “Senta-te à minha direita, até que eu ponha os teus inimigos debaixo dos teus pés.”’

[NOTE]
====
. Veja Ap. 1D.
====

[[v41-12-37]]

^<<v41-12-37,37>>^ O próprio Davi o chama de ‘Senhor’, mas como é que ele é seu filho?”
E a grande multidão escutava-o com prazer.

[[v41-12-38]]

^<<v41-12-38,38>>^ E ele prosseguiu a dizer no seu ensino: “Acautelai-vos dos escribas, que querem andar de vestes compridas e querem cumprimentos nas feiras,^&#42;1^

[NOTE]
====
. Ou “nos lugares de reunião”.
====

[[v41-12-39]]

^<<v41-12-39,39>>^ e os primeiros assentos nas sinagogas e os lugares mais destacados nas refeições noturnas.

[[v41-12-40]]

^<<v41-12-40,40>>^ Estes são os que devoram as casas das viúvas, e que, por pretexto, fazem longas orações; estes receberão um julgamento mais pesado.”

[[v41-12-41]]

^<<v41-12-41,41>>^ E ele se assentou, tendo os cofres do tesouro ao alcance da vista, e começou a observar como a multidão lançava dinheiro^&#42;1^ nos cofres do tesouro;^&#42;2^ e muitos ricos lançavam [neles] muitas moedas.

[NOTE]
====
. Lit.: “[dinheiro de] cobre”.
. Ou “na tesouraria sagrada”.
====

[[v41-12-42]]

^<<v41-12-42,42>>^ Veio então uma viúva pobre e lançou [neles] duas pequenas moedas^&#42;1^ de muito pouco valor.^&#42;2^

[NOTE]
====
. Lit.: “dois leptas”. O lépton era a menor moeda judaica de cobre ou bronze. Veja Ap. 8A.
. Lit.: “que é um quadrante”. Esta era uma moeda romana de cobre ou bronze, avaliada em uma sexagésima quarta parte do denário. Veja Ap. 8A.
====

[[v41-12-43]]

^<<v41-12-43,43>>^ Ele chamou então a si os discípulos e lhes disse: “Deveras, eu vos digo que esta viúva pobre lançou [neles] mais do que todos estes que lançam dinheiro nos cofres do tesouro;

[[v41-12-44]]

^<<v41-12-44,44>>^ pois todos eles lançaram [neles] dos seus excedentes, mas ela, de sua carência, lançou [neles] tudo o que tinha, todo o seu meio de vida.”

'''

xref:041-marcos/041-marcos-011.adoc#v41-11-0[&#60; Capítulo Anterior] | <<v41-12-0,Topo>> | xref:041-marcos/041-marcos-013.adoc#v41-13-0[Próximo Capítulo &#62;]