include::./index.adoc[]

[[v41-1-0]]
=== Marcos, 1
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v41-1-1]]

^<<v41-1-1,1>>^ [O] princípio das boas novas^&#42;1^ a respeito de^&#42;2^ Jesus Cristo:

[NOTE]
====
. “Boas novas.” Ou “evangelho”. Gr.: eu·ag·ge·lí·ou; lat.: e·van·gé·li·i.
. Ou “de”.
====

[[v41-1-2]]

^<<v41-1-2,2>>^ Conforme está escrito em Isaías, o profeta: “(Eis que eu envio o meu mensageiro^&#42;1^ diante da tua face, o qual preparará o teu caminho;)

[NOTE]
====
. Ou “anjo”.
====

[[v41-1-3]]

^<<v41-1-3,3>>^ eis que alguém está clamando no ermo: ‘Preparai o caminho de Jeová,^&#42;1^ fazei retas as suas estradas’”,

[NOTE]
====
. Veja Ap. 1D.
====

[[v41-1-4]]

^<<v41-1-4,4>>^ apareceu João, o batizador,^&#42;1^ no ermo, pregando [o] batismo [em símbolo] de arrependimento para o perdão de pecados.

[NOTE]
====
. Ou “imersor; submersor (mergulhador)”. Gr.: ba·ptí·zon.
====

[[v41-1-5]]

^<<v41-1-5,5>>^ Conseqüentemente, todo o território da Judéia e todos os habitantes de Jerusalém saíam a ter com ele e eram batizados por ele no rio Jordão, confessando abertamente os seus pecados.

[[v41-1-6]]

^<<v41-1-6,6>>^ Ora, João estava vestido de pêlos de camelo e com um cinto de couro em volta dos seus lombos, e comia gafanhotos e mel silvestre.

[[v41-1-7]]

^<<v41-1-7,7>>^ E pregava, dizendo: “Depois de mim vem alguém mais forte do que eu; não sou nem apto para me abaixar e desatar os cordões de suas sandálias.

[[v41-1-8]]

^<<v41-1-8,8>>^ Eu vos batizei com água, mas ele vos batizará com espírito santo.”

[[v41-1-9]]

^<<v41-1-9,9>>^ No decorrer daqueles dias, veio Jesus de Nazaré da Galiléia e foi batizado por João no Jordão.

[[v41-1-10]]

^<<v41-1-10,10>>^ E, subindo da água, viu imediatamente os céus serem partidos e o espírito descer como pomba sobre^&#42;1^ ele;

[NOTE]
====
. Ou “dentro”; isto é, para entrar nele.
====

[[v41-1-11]]

^<<v41-1-11,11>>^ e uma voz saiu dos céus: “Tu és meu Filho, o amado; eu te tenho aprovado.”

[[v41-1-12]]

^<<v41-1-12,12>>^ E o espírito^&#42;1^ impeliu-o imediatamente a ir para o ermo.

[NOTE]
====
. Ou “a força ativa”. Gr.: to pneú·ma; J17,18,22(hebr.): ha·rú·ahh. Veja Gên 1:2 n.: “ativa”.
====

[[v41-1-13]]

^<<v41-1-13,13>>^ Ele continuou assim no ermo por quarenta dias, sendo tentado por Satanás, e estava com os animais selváticos, mas os anjos lhe ministravam.

[[v41-1-14]]

^<<v41-1-14,14>>^ Ora, depois de João ter sido preso, Jesus entrou na Galiléia, pregando as boas novas de Deus

[[v41-1-15]]

^<<v41-1-15,15>>^ e dizendo: “Tem-se cumprido o tempo designado e o reino de Deus se tem aproximado. Arrependei-vos e tende fé nas boas novas.”

[[v41-1-16]]

^<<v41-1-16,16>>^ Andando à beira do mar da Galiléia, viu Simão e André, irmão de Simão, lançando [suas redes] ao mar, pois eram pescadores.

[[v41-1-17]]

^<<v41-1-17,17>>^ De maneira que Jesus lhes disse: “Vinde após mim, e eu farei que vos torneis pescadores de homens.”

[[v41-1-18]]

^<<v41-1-18,18>>^ E eles abandonaram imediatamente as suas redes e o seguiram.

[[v41-1-19]]

^<<v41-1-19,19>>^ E, tendo andado um pouco mais adiante, viu Tiago, o [filho] de Zebedeu, e João, seu irmão, de fato, enquanto estavam no seu barco consertando as suas redes;

[[v41-1-20]]

^<<v41-1-20,20>>^ e logo os chamou. Eles, por sua vez, abandonaram seu pai Zebedeu, no barco, com os homens contratados, e foram após ele.

[[v41-1-21]]

^<<v41-1-21,21>>^ E entraram em Cafarnaum.
Assim que chegou o sábado, entrou na sinagoga e começou a ensinar.

[[v41-1-22]]

^<<v41-1-22,22>>^ E ficaram assombrados com o seu modo de ensinar, pois eis que os ensinava como quem tinha autoridade e não como os escribas.

[[v41-1-23]]

^<<v41-1-23,23>>^ Também, logo naquela ocasião havia na sinagoga deles um homem sob o poder dum espírito impuro, e ele gritou,

[[v41-1-24]]

^<<v41-1-24,24>>^ dizendo: “Que temos nós contigo,^&#42;1^ Jesus, nazareno? Vieste destruir-nos? Eu sei exatamente quem és, o Santo de Deus.”

[NOTE]
====
. Esta é uma expressão idiomática; é uma repulsa em forma de pergunta. Veja Ap. 7B.
====

[[v41-1-25]]

^<<v41-1-25,25>>^ Mas Jesus censurou-o, dizendo: “Cala-te e sai dele!”

[[v41-1-26]]

^<<v41-1-26,26>>^ E o espírito impuro, depois de o lançar em convulsão, e berrando ao máximo da sua voz, saiu dele.

[[v41-1-27]]

^<<v41-1-27,27>>^ Ora, todos ficaram tão assombrados, que começaram uma discussão entre si, dizendo: “Que é isso? Um novo ensino! Ele dá ordens com autoridade, até mesmo a espíritos impuros, e eles lhe obedecem.”

[[v41-1-28]]

^<<v41-1-28,28>>^ De modo que o relato a respeito dele se espalhou imediatamente em todas as direções, através de toda a região circunvizinha na Galiléia.

[[v41-1-29]]

^<<v41-1-29,29>>^ E saíram imediatamente da sinagoga e entraram na casa de Simão e André, junto com Tiago e João.

[[v41-1-30]]

^<<v41-1-30,30>>^ Ora, a sogra de Simão estava acamada com febre, e falaram-lhe dela imediatamente.

[[v41-1-31]]

^<<v41-1-31,31>>^ E, dirigindo-se a ela, levantou-a, tomando-a pela mão; e a febre a abandonou e ela começou a ministrar-lhes.

[[v41-1-32]]

^<<v41-1-32,32>>^ Ao anoitecer, tendo-se posto o sol, trouxeram-lhe todos os doentes e os possessos de demônios;

[[v41-1-33]]

^<<v41-1-33,33>>^ e a cidade toda estava ajuntada na frente da porta.

[[v41-1-34]]

^<<v41-1-34,34>>^ Curou assim a muitos dos que estavam enfermos com várias doenças e expulsou muitos demônios, mas não deixou os demônios falar, porque sabiam que ele era Cristo.

[[v41-1-35]]

^<<v41-1-35,35>>^ E, de manhã cedo, quando ainda estava escuro, levantou-se e foi para fora, e partiu para um lugar solitário, e ali começou a orar.

[[v41-1-36]]

^<<v41-1-36,36>>^ No entanto, Simão e os com ele foram à sua procura

[[v41-1-37]]

^<<v41-1-37,37>>^ e acharam-no, e disseram-lhe: “Todos te procuram.”

[[v41-1-38]]

^<<v41-1-38,38>>^ Mas ele lhes disse: “Vamos a outro lugar, às vilas vizinhas, para que eu pregue também ali, pois é com este objetivo que saí.”

[[v41-1-39]]

^<<v41-1-39,39>>^ E foi, pregando nas sinagogas deles, em toda a Galiléia, e expulsando os demônios.

[[v41-1-40]]

^<<v41-1-40,40>>^ Veio também a ele um leproso, suplicando-lhe, até de joelhos, [e] dizendo-lhe: “Se apenas quiseres, podes tornar-me limpo.”

[[v41-1-41]]

^<<v41-1-41,41>>^ Em vista disso, penalizou-se, e, estendendo a mão, tocou nele e disse-lhe: “Eu quero. Torna-te limpo.”

[[v41-1-42]]

^<<v41-1-42,42>>^ E a lepra desapareceu-lhe imediatamente e ele se tornou limpo.

[[v41-1-43]]

^<<v41-1-43,43>>^ Outrossim, dando-lhe ordens estritas, mandou-o imediatamente embora

[[v41-1-44]]

^<<v41-1-44,44>>^ e disse-lhe: “Cuida de que não digas nada a ninguém, mas vai, mostra-te ao sacerdote e oferece pela tua purificação as coisas determinadas por Moisés, em testemunho para eles.”

[[v41-1-45]]

^<<v41-1-45,45>>^ Mas, depois de se afastar, o homem principiou a proclamar isso consideravelmente e a divulgar o relato, de modo que [Jesus]^&#42;1^ não podia mais entrar abertamente numa cidade, mas continuava fora, nos lugares solitários. Contudo, eles continuavam a vir a ele, de todos os lados.

[NOTE]
====
. Lit.: “ele”.
====

'''

xref:040-mateus/040-mateus-028.adoc#v40-28-0[&#60; Capítulo Anterior] | <<v41-1-0,Topo>> | xref:041-marcos/041-marcos-002.adoc#v41-2-0[Próximo Capítulo &#62;]