include::./index.adoc[]

[[v41-5-0]]
=== Marcos, 5
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v41-5-1]]

^<<v41-5-1,1>>^ Pois bem, chegaram ao outro lado do mar, ao país dos gerasenos.^&#42;1^

[NOTE]
====
. “Gerasenos”, א°BDVg; ACSyh,p: “gadarenos”.
====

[[v41-5-2]]

^<<v41-5-2,2>>^ E assim que ele saiu do barco, veio ao encontro dele, dentre os túmulos memoriais, um homem sob o poder dum espírito impuro.

[[v41-5-3]]

^<<v41-5-3,3>>^ Seu antro era entre os túmulos; e, até aquele tempo, absolutamente ninguém fora capaz de amarrá-lo, nem mesmo com uma cadeia,

[[v41-5-4]]

^<<v41-5-4,4>>^ porque tinha sido muitas vezes amarrado com grilhões e cadeias, mas as cadeias foram quebradas por ele e os grilhões foram até despedaçados; e ninguém tinha força para subjugá-lo.

[[v41-5-5]]

^<<v41-5-5,5>>^ E ele clamava continuamente, noite e dia, nos túmulos e nos montes, e se cortava com pedras.

[[v41-5-6]]

^<<v41-5-6,6>>^ Mas, ao avistar Jesus de certa distância, correu e prestou-lhe homenagem,

[[v41-5-7]]

^<<v41-5-7,7>>^ e, tendo clamado com alta voz, disse: “Que tenho eu que ver contigo,^&#42;1^ Jesus, Filho do Deus Altíssimo? Eu te ponho sob juramento por Deus, que não me atormentes.”

[NOTE]
====
. Esta é uma expressão idiomática; é uma repulsa em forma de pergunta. Veja Ap. 7B.
====

[[v41-5-8]]

^<<v41-5-8,8>>^ Porque lhe dissera: “Sai do homem, ó espírito impuro.”

[[v41-5-9]]

^<<v41-5-9,9>>^ Mas, começou a perguntar-lhe: “Qual é teu nome?” E ele lhe disse: “Meu nome é Legião, porque há muitos de nós.”

[[v41-5-10]]

^<<v41-5-10,10>>^ E suplicou-lhe muitas vezes que não enviasse os espíritos para fora do país.

[[v41-5-11]]

^<<v41-5-11,11>>^ Ora, havia uma grande manada de porcos pastando no monte.

[[v41-5-12]]

^<<v41-5-12,12>>^ Por isso lhe suplicaram, dizendo: “Manda-nos para os porcos, para que entremos neles.”

[[v41-5-13]]

^<<v41-5-13,13>>^ E ele lho permitiu. Os espíritos impuros saíram assim e entraram nos porcos; e a manada precipitou-se despenhadeiro abaixo para dentro do mar, cerca de dois mil deles, e afogaram-se um por um no mar.

[[v41-5-14]]

^<<v41-5-14,14>>^ Mas os seus porqueiros fugiram e relataram isso na cidade e na zona rural; e as pessoas vieram ver o que tinha acontecido.

[[v41-5-15]]

^<<v41-5-15,15>>^ Vieram assim a Jesus e viram o [homem] possesso de demônios sentado vestido e de juízo são, esse [homem] que tinha tido a legião; e ficaram temerosos.

[[v41-5-16]]

^<<v41-5-16,16>>^ Os que tinham visto isso relataram-lhes também como isso tinha acontecido ao [homem] possesso de demônios, e acerca dos porcos.

[[v41-5-17]]

^<<v41-5-17,17>>^ E principiaram assim a suplicar-lhe que saísse dos seus distritos.

[[v41-5-18]]

^<<v41-5-18,18>>^ Então, ao entrar ele no barco, o [homem] que tinha estado possesso de demônios começou a suplicar-lhe que pudesse continuar com ele.

[[v41-5-19]]

^<<v41-5-19,19>>^ No entanto, ele não o deixou, mas disse-lhe: “Vai para casa, para teus parentes e relata-lhes todas as coisas que Jeová^&#42;1^ tem feito para ti e a misericórdia que teve de ti.”

[NOTE]
====
. Veja Ap. 1D.
====

[[v41-5-20]]

^<<v41-5-20,20>>^ E ele foi embora e principiou a proclamar^&#42;1^ em Decápolis^&#42;2^ todas as coisas que Jesus fizera para ele, e todos começaram a ficar admirados.

[NOTE]
====
. Lit.: “a estar proclamando”. Gr.: ke·rýs·sein. Veja 13:10 n.
. Ou “Dez Cidades”. Gr.: De·ka·pó·lei.
====

[[v41-5-21]]

^<<v41-5-21,21>>^ Depois de Jesus ter passado novamente de volta, no barco, para a margem oposta, ajuntou-se a ele uma grande multidão; e ele estava à beira do mar.

[[v41-5-22]]

^<<v41-5-22,22>>^ Veio então um dos presidentes da sinagoga, de nome Jairo, e, ao avistá-lo, lançou-se-lhe aos pés

[[v41-5-23]]

^<<v41-5-23,23>>^ e suplicou-lhe muitas vezes, dizendo: “Minha filhinha está nas últimas. Vem, por favor, e põe tuas mãos sobre ela, para que possa ficar boa e viver.”

[[v41-5-24]]

^<<v41-5-24,24>>^ Foi assim com ele. E uma grande multidão seguia-o e apertava-o.

[[v41-5-25]]

^<<v41-5-25,25>>^ Ora, havia ali uma mulher que já por doze anos padecia dum fluxo de sangue,

[[v41-5-26]]

^<<v41-5-26,26>>^ e ela tinha sido submetida a muitas dores, por muitos médicos, e tinha gasto todos os seus recursos, sem ter sido beneficiada, mas, antes, tinha ficado pior.

[[v41-5-27]]

^<<v41-5-27,27>>^ Quando ouviu as coisas a respeito de Jesus, veio por detrás, na multidão, e tocou na roupa exterior dele;

[[v41-5-28]]

^<<v41-5-28,28>>^ pois dizia: “Se eu apenas tocar na sua roupagem exterior, ficarei boa.”^&#42;1^

[NOTE]
====
. Ou “serei salva”.
====

[[v41-5-29]]

^<<v41-5-29,29>>^ E a sua fonte de sangue secou-se imediatamente, e ela sentiu no seu corpo que tinha sido curada da penosa doença.

[[v41-5-30]]

^<<v41-5-30,30>>^ Jesus, também, reconhecendo imediatamente em si mesmo que saíra poder dele, voltou-se na multidão e começou a dizer: “Quem tocou na minha roupagem exterior?”

[[v41-5-31]]

^<<v41-5-31,31>>^ Mas os seus discípulos começaram a dizer-lhe: “Vês que a multidão te aperta, e dizes tu: ‘Quem me tocou?’”

[[v41-5-32]]

^<<v41-5-32,32>>^ No entanto, ele estava olhando em volta para ver aquela que tinha feito isso.

[[v41-5-33]]

^<<v41-5-33,33>>^ A mulher, porém, amedrontada e trêmula, sabendo o que lhe tinha acontecido, veio e prostrou-se diante dele, e disse-lhe toda a verdade.

[[v41-5-34]]

^<<v41-5-34,34>>^ Disse-lhe ele: “Filha, a tua fé te fez ficar boa.^&#42;1^ Vai em paz^&#42;2^ e fica curada da tua doença penosa.”

[NOTE]
====
. Ou “te salvou”.
. “Em paz.” Gr.: eis ei·ré·nen; lat.: in pá·ce; J17,18,22(hebr.): lesha·lóhm.
====

[[v41-5-35]]

^<<v41-5-35,35>>^ Enquanto ainda falava, vieram alguns homens da casa do presidente da sinagoga e disseram: “Tua filha morreu! Por que incomodar ainda o instrutor?”

[[v41-5-36]]

^<<v41-5-36,36>>^ Mas Jesus, ouvindo a palavra falada, disse ao presidente da sinagoga: “Não temas, apenas exerce fé.”

[[v41-5-37]]

^<<v41-5-37,37>>^ Não deixou então ninguém acompanhá-lo, exceto Pedro, e Tiago, e João, irmão de Tiago.

[[v41-5-38]]

^<<v41-5-38,38>>^ Chegaram assim à casa do presidente da sinagoga, e ele observou a confusão barulhenta, e os que choravam e deixavam escapar muitos lamentos,

[[v41-5-39]]

^<<v41-5-39,39>>^ e, tendo entrado, disse-lhes: “Por que estais causando confusão barulhenta e choro? A menina não morreu, mas está dormindo.”

[[v41-5-40]]

^<<v41-5-40,40>>^ A isso começaram a rir-se dele desdenhosamente. Mas ele, tendo mandado todos para fora, tomou consigo o pai e a mãe da menina, e os com ele, e entrou onde estava a menina.

[[v41-5-41]]

^<<v41-5-41,41>>^ E, tomando a mão da menina, disse-lhe: “Talita cumi”, que, traduzido, significa: “Donzela, digo-te: Levanta-te!”

[[v41-5-42]]

^<<v41-5-42,42>>^ E a donzela levantou-se imediatamente e começou a andar, pois tinha doze anos de idade. E eles ficaram logo fora de si com grande êxtase.

[[v41-5-43]]

^<<v41-5-43,43>>^ Mas ele lhes ordenou vez após vez que não deixassem ninguém saber disso, e disse que dessem a ela algo para comer.

'''

xref:041-marcos/041-marcos-004.adoc#v41-4-0[&#60; Capítulo Anterior] | <<v41-5-0,Topo>> | xref:041-marcos/041-marcos-006.adoc#v41-6-0[Próximo Capítulo &#62;]