include::./index.adoc[]

[[v41-10-0]]
=== Marcos, 10
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v41-10-1]]

^<<v41-10-1,1>>^ Dali ele se levantou e chegou às fronteiras da Judéia e ao outro lado do Jordão, e novamente se ajuntaram a ele as multidões, e assim como costumava fazer, tornou a ensiná-las.

[[v41-10-2]]

^<<v41-10-2,2>>^ Aproximaram-se então fariseus, e, para o porem à prova, começaram a interrogá-lo, se era lícito que um homem se divorciasse da esposa.

[[v41-10-3]]

^<<v41-10-3,3>>^ Em resposta, ele lhes disse: “Que vos ordenou Moisés?”

[[v41-10-4]]

^<<v41-10-4,4>>^ Disseram: “Moisés concedeu a escrita dum certificado de repúdio e divorciar-se [dela].”

[[v41-10-5]]

^<<v41-10-5,5>>^ Mas Jesus disse-lhes: “Foi por causa da dureza de vossos corações que ele vos escreveu este mandamento.

[[v41-10-6]]

^<<v41-10-6,6>>^ No entanto, desde [o] princípio da criação ‘Ele^&#42;1^ os fez macho e fêmea.

[NOTE]
====
. “Ele”, אBC; ADVgSyh,p,sArm: “Deus”.
====

[[v41-10-7]]

^<<v41-10-7,7>>^ Por esta razão deixará o homem seu pai e sua mãe,

[[v41-10-8]]

^<<v41-10-8,8>>^ e os dois serão uma só carne’; de modo que não são mais dois, mas uma só carne.

[[v41-10-9]]

^<<v41-10-9,9>>^ Portanto, o que Deus pôs sob o mesmo jugo, não o separe o homem.”

[[v41-10-10]]

^<<v41-10-10,10>>^ Quando novamente na casa, os discípulos começaram a interrogá-lo a respeito disso.

[[v41-10-11]]

^<<v41-10-11,11>>^ E ele lhes disse: “Quem se divorciar^&#42;1^ de sua esposa e se casar com outra, comete adultério contra ela,

[NOTE]
====
. Lit.: “se soltar de”. Veja Mal 2:16 n.
====

[[v41-10-12]]

^<<v41-10-12,12>>^ e, se uma mulher, depois de divorciar-se de seu marido, se casar com outro, ela comete adultério.”

[[v41-10-13]]

^<<v41-10-13,13>>^ As pessoas começaram então a trazer-lhe criancinhas, para que as tocasse; mas os discípulos as censuraram.

[[v41-10-14]]

^<<v41-10-14,14>>^ Vendo isso, Jesus ficou indignado e disse-lhes: “Deixai vir a mim as criancinhas; não tenteis impedi-las, pois o reino de Deus pertence a tais.

[[v41-10-15]]

^<<v41-10-15,15>>^ Deveras, eu vos digo: Quem não receber o reino de Deus como uma criancinha, de modo algum entrará nele.”

[[v41-10-16]]

^<<v41-10-16,16>>^ E tomou as criancinhas nos seus braços e começou a abençoá-las, impondo-lhes as suas mãos.

[[v41-10-17]]

^<<v41-10-17,17>>^ E, enquanto saía, chegou correndo certo homem e se pôs de joelhos diante dele, perguntando-lhe: “Bom Instrutor, que tenho de fazer para herdar a vida eterna?”^&#42;1^

[NOTE]
====
. “Vida eterna.” Gr.: zo·én ai·ó·ni·on; lat.: ví·tam ae·tér·nam; J17,18,22(hebr.): hhai·yéh ‛oh·lám.
====

[[v41-10-18]]

^<<v41-10-18,18>>^ Jesus disse-lhe: “Por que me chamas de bom? Ninguém é bom, exceto um só, Deus.

[[v41-10-19]]

^<<v41-10-19,19>>^ Sabes os mandamentos: ‘Não assassines, não cometas adultério, não furtes, não dês falso testemunho, não defraudes, honra a teu pai e a tua mãe.’”

[[v41-10-20]]

^<<v41-10-20,20>>^ O homem disse-lhe: “Instrutor, todas estas coisas tenho guardado desde a minha mocidade.”

[[v41-10-21]]

^<<v41-10-21,21>>^ Jesus olhou para ele e sentiu amor por ele, e disse-lhe: “Uma coisa falta a respeito de ti: Vai, vende o que tiveres e dá aos pobres, e terás um tesouro no céu, e vem ser meu seguidor.”

[[v41-10-22]]

^<<v41-10-22,22>>^ Mas ele ficou triste com as palavras e se afastou contristado, pois tinha muitas propriedades.

[[v41-10-23]]

^<<v41-10-23,23>>^ Depois de olhar em volta, Jesus disse aos seus discípulos: “Quão difícil será para os de dinheiro entrar no reino de Deus!”

[[v41-10-24]]

^<<v41-10-24,24>>^ Mas os discípulos ficaram surpresos com as suas palavras. Em resposta, Jesus disse-lhes novamente: “Filhos, quão difícil é entrar no reino de Deus!

[[v41-10-25]]

^<<v41-10-25,25>>^ É mais fácil um camelo passar pelo orifício duma agulha, do que um rico entrar no reino de Deus.”

[[v41-10-26]]

^<<v41-10-26,26>>^ Eles ficaram ainda mais assombrados e disseram-lhe: “Quem, de fato, pode ser salvo?”

[[v41-10-27]]

^<<v41-10-27,27>>^ Olhando diretamente para eles, Jesus disse: “Para homens é impossível, mas não é assim para Deus, pois para Deus todas as coisas são possíveis.”

[[v41-10-28]]

^<<v41-10-28,28>>^ Pedro principiou a dizer-lhe: “Eis que abandonamos todas as coisas e te temos seguido.”

[[v41-10-29]]

^<<v41-10-29,29>>^ Jesus disse: “Deveras, eu vos digo: Ninguém abandonou casa, ou irmãos, ou irmãs, ou mãe, ou pai, ou filhos, ou campos, por minha causa e pela causa das boas novas,

[[v41-10-30]]

^<<v41-10-30,30>>^ que não receba cem vezes mais agora, neste período de tempo, casas, e irmãos, e irmãs, e mães, e filhos, e campos, com perseguições, e no vindouro sistema de coisas^&#42;1^ a vida eterna.

[NOTE]
====
. Ou “ordem de coisas”. Gr.: ai·ó·ni; J17,22(hebr.): u·va·‛oh·lám, “e na ordem de coisas”.
====

[[v41-10-31]]

^<<v41-10-31,31>>^ No entanto, muitos dos primeiros serão últimos, e os últimos, primeiros.”

[[v41-10-32]]

^<<v41-10-32,32>>^ Estavam então avançando pela estrada, subindo a Jerusalém, e Jesus ia na frente deles, e eles estavam pasmados; mas os que seguiam começaram a temer. Tornou a tomar à parte os doze e principiou a dizer-lhes as seguintes coisas destinadas a lhe sobrevirem:

[[v41-10-33]]

^<<v41-10-33,33>>^ “Aqui estamos, avançando para Jerusalém, e o Filho do homem será entregue aos principais sacerdotes e aos escribas, e condená-lo-ão à morte e o entregarão a [homens das] nações,

[[v41-10-34]]

^<<v41-10-34,34>>^ e divertir-se-ão às custas dele, e cuspirão nele, e o açoitarão, e o matarão, mas, três dias depois será levantado.”

[[v41-10-35]]

^<<v41-10-35,35>>^ E Tiago e João, os dois filhos de Zebedeu, aproximaram-se dele e disseram-lhe: “Instrutor, queremos que faças para nós o que for que te peçamos.”

[[v41-10-36]]

^<<v41-10-36,36>>^ Disse-lhes ele: “Que quereis que eu faça para vós?”

[[v41-10-37]]

^<<v41-10-37,37>>^ Disseram-lhe: “Concede-nos que nos assentemos um à tua direita e outro à tua esquerda, na tua glória.”

[[v41-10-38]]

^<<v41-10-38,38>>^ Mas Jesus disse-lhes: “Não sabeis o que pedis. Podeis beber o copo que eu estou bebendo ou ser batizados com o batismo^&#42;1^ com que eu estou sendo batizado?”

[NOTE]
====
. Ou “imersão; submersão”. Gr.: bá·pti·sma.
====

[[v41-10-39]]

^<<v41-10-39,39>>^ Disseram-lhe: “Podemos.” A isso Jesus disse-lhes: “Bebereis o copo que eu estou bebendo e sereis batizados com o batismo com que eu estou sendo batizado.

[[v41-10-40]]

^<<v41-10-40,40>>^ No entanto, este assentar-se à minha direita ou à minha esquerda não é meu para dar, mas pertence àqueles para quem tem sido preparado.”

[[v41-10-41]]

^<<v41-10-41,41>>^ Ora, quando os outros dez ficaram sabendo disso, principiaram a indignar-se com Tiago e João.

[[v41-10-42]]

^<<v41-10-42,42>>^ Mas Jesus, depois de chamá-los a si, disse-lhes: “Sabeis que os que parecem estar governando as nações dominam sobre elas, e seus grandes exercem autoridade sobre elas.

[[v41-10-43]]

^<<v41-10-43,43>>^ Não é assim entre vós; mas quem quiser tornar-se grande entre vós, terá de ser o vosso ministro,

[[v41-10-44]]

^<<v41-10-44,44>>^ e quem quiser ser o primeiro entre vós, tem de ser o escravo de todos.

[[v41-10-45]]

^<<v41-10-45,45>>^ Pois até mesmo o Filho do homem veio, não para que se lhe ministrasse, mas para ministrar e dar a sua alma^&#42;1^ como resgate em troca de muitos.”

[NOTE]
====
. Ou “vida”. Veja Mt 20:28 n.: “alma”.
====

[[v41-10-46]]

^<<v41-10-46,46>>^ E chegaram a Jericó. Mas quando ele, e seus discípulos, e uma multidão considerável, estavam saindo de Jericó, encontrava-se sentado à beira da estrada Bartimeu (filho de Timeu), um mendigo cego.

[[v41-10-47]]

^<<v41-10-47,47>>^ Quando ouviu que era Jesus, o nazareno, principiou a gritar e a dizer: “Filho de Davi, Jesus, tem misericórdia de mim!”

[[v41-10-48]]

^<<v41-10-48,48>>^ A isso, muitos começaram a dizer-lhe severamente que se calasse; mas ele gritava tanto mais: “Filho de Davi, tem misericórdia de mim!”

[[v41-10-49]]

^<<v41-10-49,49>>^ Jesus parou assim e disse: “Chamai-o.” E chamaram o cego, dizendo-lhe: “Coragem! Levanta-te, ele te chama.”

[[v41-10-50]]

^<<v41-10-50,50>>^ Lançando de si a sua roupa exterior, pulou de pé e foi ter com Jesus.

[[v41-10-51]]

^<<v41-10-51,51>>^ E Jesus disse-lhe, em resposta: “Que queres que eu faça para ti?” O cego disse-lhe: “Rabôni,^&#42;1^ deixa-me recuperar a vista.”

[NOTE]
====
. “Rabôni.” Veja Jo 20:16.
====

[[v41-10-52]]

^<<v41-10-52,52>>^ E Jesus disse-lhe: “Vai, tua fé te fez ficar bom.”^&#42;1^ E ele recuperou imediatamente a vista e começou a segui-lo pela estrada.

[NOTE]
====
. Ou “te salvou”.
====

'''

xref:041-marcos/041-marcos-009.adoc#v41-9-0[&#60; Capítulo Anterior] | <<v41-10-0,Topo>> | xref:041-marcos/041-marcos-011.adoc#v41-11-0[Próximo Capítulo &#62;]