include::./index.adoc[]

[[v41-14-0]]
=== Marcos, 14
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v41-14-1]]

^<<v41-14-1,1>>^ Ora, a páscoa e a [festividade dos] pães não fermentados era dali a dois dias. E os principais sacerdotes e os escribas estavam procurando um meio de se apoderarem dele por meio dum ardil e de o matarem;

[[v41-14-2]]

^<<v41-14-2,2>>^ pois diziam repetidas vezes: “Não durante a festividade; talvez haja um alvoroço do povo.”

[[v41-14-3]]

^<<v41-14-3,3>>^ E, enquanto ele estava em Betânia, na casa de Simão, o leproso, ao estar recostado durante uma refeição, veio uma mulher com um vaso de alabastro com óleo perfumado, nardo genuíno, muito dispendioso. Rompendo o vaso de alabastro, começou a derramá-lo sobre a cabeça dele.

[[v41-14-4]]

^<<v41-14-4,4>>^ À vista disso, alguns expressavam indignação entre si mesmos: “Por que se deu este desperdício de óleo perfumado?

[[v41-14-5]]

^<<v41-14-5,5>>^ Pois este óleo perfumado poderia ter sido vendido por mais de trezentos denários^&#42;1^ e dado aos pobres!” E sentiam grande desgosto com ela.

[NOTE]
====
. Veja 6:37 n.
====

[[v41-14-6]]

^<<v41-14-6,6>>^ Mas Jesus disse: “Deixai-a. Por que procurais causar-lhe aflição? Ela fez uma ação excelente para comigo.

[[v41-14-7]]

^<<v41-14-7,7>>^ Porque vós sempre tendes convosco os pobres, e quando quiserdes, podeis sempre fazer-lhes bem, mas a mim nem sempre tendes.

[[v41-14-8]]

^<<v41-14-8,8>>^ Ela fez o que pôde; antecipou-se em derramar óleo perfumado sobre o meu corpo, em vista de meu enterro.

[[v41-14-9]]

^<<v41-14-9,9>>^ Deveras, eu vos digo: Onde quer que se pregarem as boas novas em todo o mundo, o que esta mulher fez também será contado em lembrança dela.”

[[v41-14-10]]

^<<v41-14-10,10>>^ E Judas Iscariotes, um dos doze, dirigiu-se aos principais sacerdotes, a fim de traí-lo a eles.

[[v41-14-11]]

^<<v41-14-11,11>>^ Quando ouviram isso, alegraram-se e prometeram dar-lhe dinheiro de prata. Ele começou assim a buscar um modo de traí-lo convenientemente.

[[v41-14-12]]

^<<v41-14-12,12>>^ Ora, no primeiro dia dos^&#42;1^ pães não fermentados, quando costumavam sacrificar a [vítima] pascoal, seus discípulos disseram-lhe: “Aonde queres que vamos e preparemos para comeres a páscoa?”

[NOTE]
====
. Veja Mt 26:17 n.
====

[[v41-14-13]]

^<<v41-14-13,13>>^ Em vista disso, ele enviou dois dos seus discípulos e disse-lhes: “Ide à cidade, e um homem levando um vaso de barro com água virá ao encontro de vós. Segui-o,

[[v41-14-14]]

^<<v41-14-14,14>>^ e onde quer que ele entrar, dizei ao dono da casa: ‘O Instrutor diz: “Onde está a sala dos hóspedes para mim, onde eu possa comer a páscoa com meus discípulos?”’

[[v41-14-15]]

^<<v41-14-15,15>>^ E ele vos mostrará uma grande sala de sobrado, mobiliada em preparação; ali preparai para nós.”

[[v41-14-16]]

^<<v41-14-16,16>>^ Os discípulos saíram, assim, e entraram na cidade, e acharam-no assim como ele lhes dissera; e fizeram preparativos para a páscoa.

[[v41-14-17]]

^<<v41-14-17,17>>^ Depois de anoitecer, chegou ele com os doze.

[[v41-14-18]]

^<<v41-14-18,18>>^ E, enquanto se recostavam à mesa e comiam, Jesus disse: “Deveras, eu vos digo: Um de vós, que está comendo comigo, me trairá.”

[[v41-14-19]]

^<<v41-14-19,19>>^ Eles principiaram a ficar contristados e a dizer-lhe um por um: “Não sou por acaso eu?”

[[v41-14-20]]

^<<v41-14-20,20>>^ Ele lhes disse: “É um dos doze, aquele que mete comigo [a mão] no prato fundo comum.

[[v41-14-21]]

^<<v41-14-21,21>>^ É verdade, o Filho do homem vai embora, assim como está escrito a respeito dele, mas ai daquele homem por quem o Filho do homem está sendo traído! Teria sido melhor para este homem, se não tivesse nascido.”

[[v41-14-22]]

^<<v41-14-22,22>>^ E, enquanto continuavam a comer, tomou um pão, proferiu uma bênção, partiu-o e o deu a eles, e disse: “Tomai-o, isto significa meu corpo.”

[[v41-14-23]]

^<<v41-14-23,23>>^ E, tomando um copo, rendeu graças e o deu a eles, e todos beberam dele.

[[v41-14-24]]

^<<v41-14-24,24>>^ E disse-lhes: “Isto significa^&#42;1^ meu ‘sangue do pacto’, que há de ser derramado em benefício de muitos.

[NOTE]
====
. Ou “é”, no sentido de significar, importar em, representar. Veja Mt 26:26 n.
====

[[v41-14-25]]

^<<v41-14-25,25>>^ Deveras, eu vos digo: De modo algum beberei mais do produto da videira, até o dia em que o beberei novo^&#42;1^ no reino de Deus.”

[NOTE]
====
. “Novo”, isto é, o produto novo da videira.
====

[[v41-14-26]]

^<<v41-14-26,26>>^ Finalmente, depois de cantarem louvores,^&#42;1^ saíram para o Monte das Oliveiras.

[NOTE]
====
. Ou “hinos; salmos”. Sem dúvida, os Salmos de Halel. Veja Sal. 114:1 n.
====

[[v41-14-27]]

^<<v41-14-27,27>>^ E Jesus disse-lhes: “Todos vós tropeçareis, porque está escrito: ‘Golpearei o pastor, e as ovelhas serão espalhadas.’

[[v41-14-28]]

^<<v41-14-28,28>>^ Mas, depois de eu ter sido levantado, irei na frente de vós para a Galiléia.”

[[v41-14-29]]

^<<v41-14-29,29>>^ Mas Pedro disse-lhe: “Ainda que todos os outros tropecem, eu não.”

[[v41-14-30]]

^<<v41-14-30,30>>^ Em vista disso, Jesus disse-lhe: “Deveras, eu te digo: Hoje, sim, esta noite, antes de o galo cantar duas vezes, até mesmo tu me terás repudiado três vezes.”

[[v41-14-31]]

^<<v41-14-31,31>>^ Mas ele começou a dizer profusamente: “Mesmo que eu tenha de morrer contigo, de modo algum te repudiarei.” Também todos os outros começaram a dizer a mesma coisa.

[[v41-14-32]]

^<<v41-14-32,32>>^ Chegaram assim ao lugar de nome Getsêmani, e ele disse aos seus discípulos: “Sentai-vos aqui enquanto eu oro.”

[[v41-14-33]]

^<<v41-14-33,33>>^ E tomou a Pedro, e a Tiago, e a João, e principiou a ficar atônito e muito aflito.

[[v41-14-34]]

^<<v41-14-34,34>>^ E ele lhes disse: “Minha alma está profundamente contristada, até à morte. Ficai aqui e mantende-vos vigilantes.”

[[v41-14-35]]

^<<v41-14-35,35>>^ E, avançando um pouco, passou a prostrar-se no chão e começou a orar que, se fosse possível, a hora se afastasse dele.

[[v41-14-36]]

^<<v41-14-36,36>>^ E prosseguiu a dizer: “Aba,^&#42;1^ Pai, todas as coisas te são possíveis; remove de mim este copo. Contudo, não o que eu quero, mas o que tu queres.”

[NOTE]
====
. Esta é uma palavra aram. que significa “o pai”, ou: “Ó Pai!” Gr.: Ab·bá; J17,22(hebr.): ’Ab·bá’.
====

[[v41-14-37]]

^<<v41-14-37,37>>^ E veio e os achou dormindo, e disse a Pedro: “Simão, estás dormindo? Não tiveste força para te manteres vigilante por uma hora?

[[v41-14-38]]

^<<v41-14-38,38>>^ Homens, mantende-vos vigilantes e orai, a fim de que não entreis em tentação. O espírito, naturalmente, está ansioso, mas a carne é fraca.”

[[v41-14-39]]

^<<v41-14-39,39>>^ E ele se afastou novamente e orou, dizendo a mesma palavra.

[[v41-14-40]]

^<<v41-14-40,40>>^ E veio novamente e os achou dormindo, pois estavam com os olhos pesados, e por isso não sabiam o que lhe responder.

[[v41-14-41]]

^<<v41-14-41,41>>^ E veio pela terceira vez e disse-lhes: “Numa ocasião destas, vós estais dormindo e descansando! Basta! Chegou a hora! Eis que o Filho do homem está sendo traído às mãos de pecadores.

[[v41-14-42]]

^<<v41-14-42,42>>^ Levantai-vos, vamos embora. Eis que se tem aproximado aquele que me trai.”

[[v41-14-43]]

^<<v41-14-43,43>>^ E imediatamente, enquanto ainda falava, chegou Judas, um dos doze, e com ele uma multidão com espadas e cacetes, da parte dos principais sacerdotes, e dos escribas, e dos anciãos.

[[v41-14-44]]

^<<v41-14-44,44>>^ Ora, o que o traía havia-lhes dado um sinal convencionado, dizendo: “A quem eu beijar, este é ele; detende-o e levai-o seguramente^&#42;1^ embora.”

[NOTE]
====
. Ou “sem falta”.
====

[[v41-14-45]]

^<<v41-14-45,45>>^ E ele veio diretamente e se aproximou dele, e disse: “Rabi!” e beijou-o mui ternamente.

[[v41-14-46]]

^<<v41-14-46,46>>^ Deitaram assim mãos nele e o detiveram.

[[v41-14-47]]

^<<v41-14-47,47>>^ No entanto, um dos que estavam parados ali puxou a espada e golpeou o escravo do sumo sacerdote, e cortou-lhe a orelha.

[[v41-14-48]]

^<<v41-14-48,48>>^ Mas Jesus, em resposta, disse-lhes: “Viestes com espadas e com cacetes, como contra um salteador, para prender-me?

[[v41-14-49]]

^<<v41-14-49,49>>^ Dia após dia estava eu convosco no templo, ensinando; contudo, não me detivestes. Não obstante, é para que se cumpram as Escrituras.”

[[v41-14-50]]

^<<v41-14-50,50>>^ E todos o abandonaram e fugiram.

[[v41-14-51]]

^<<v41-14-51,51>>^ Mas, certo jovem, que usava uma roupa de linho fino por cima do [corpo] nu, começou a segui-lo de perto; e tentaram apoderar-se dele,

[[v41-14-52]]

^<<v41-14-52,52>>^ mas ele largou a sua roupa de linho e escapou nu.^&#42;1^

[NOTE]
====
. Ou “pouco vestido”. Veja Mt 25:36 n.
====

[[v41-14-53]]

^<<v41-14-53,53>>^ Levaram então Jesus ao sumo sacerdote, e todos os principais sacerdotes, e os anciãos, e os escribas, reuniram-se.

[[v41-14-54]]

^<<v41-14-54,54>>^ Mas Pedro, duma boa distância, seguia-o até o pátio do sumo sacerdote; e ele estava sentado junto com os criados e se aquecia diante dum fogo.

[[v41-14-55]]

^<<v41-14-55,55>>^ No ínterim, os principais sacerdotes e todo o Sinédrio estavam procurando testemunho contra Jesus, para o entregarem à morte, mas não encontravam nenhum.

[[v41-14-56]]

^<<v41-14-56,56>>^ Muitos, de fato, davam testemunho falso contra ele, mas os seus testemunhos não estavam em acordo.

[[v41-14-57]]

^<<v41-14-57,57>>^ Levantaram-se também certos e deram testemunho falso contra ele, dizendo:

[[v41-14-58]]

^<<v41-14-58,58>>^ “Nós o ouvimos dizer: ‘Derrubarei este templo^&#42;1^ feito por mãos e em três dias construirei outro, não feito por mãos.’”

[NOTE]
====
. Ou “habitação (morada) divina”. Gr.: na·ón; lat.: tém·plum; J17,18,22(hebr.): ha·heh·khál, “o palácio (templo)”.
====

[[v41-14-59]]

^<<v41-14-59,59>>^ Mas, nem mesmo nesta base estava em acordo o seu testemunho.

[[v41-14-60]]

^<<v41-14-60,60>>^ Por fim se levantou o sumo sacerdote no meio deles e interrogou Jesus, dizendo: “Não dizes nada em resposta? O que é que estes testificam contra ti?”

[[v41-14-61]]

^<<v41-14-61,61>>^ Mas ele ficou calado e não deu nenhuma resposta. O sumo sacerdote começou novamente a interrogá-lo e disse-lhe: “És tu o Cristo, o Filho do Bendito?”

[[v41-14-62]]

^<<v41-14-62,62>>^ Jesus disse então: “Sou; e vós vereis o Filho do homem sentado à destra de poder e vindo^&#42;1^ com as nuvens do céu.”

[NOTE]
====
. “Vindo.” Em gr.: er·khó·me·non.
====

[[v41-14-63]]

^<<v41-14-63,63>>^ Em vista disso, o sumo sacerdote rasgou a sua roupa interior e disse: “Que necessidade temos ainda de testemunhas?

[[v41-14-64]]

^<<v41-14-64,64>>^ Ouvistes a blasfêmia. O que vos é evidente?” Todos o condenaram a estar sujeito à morte.

[[v41-14-65]]

^<<v41-14-65,65>>^ E alguns principiaram a cuspir nele, e a encobrir-lhe o rosto todo, e a esmurrá-lo, e a dizer-lhe: “Profetiza!” E os oficiais de justiça levaram-no, esbofeteando-lhe o rosto.

[[v41-14-66]]

^<<v41-14-66,66>>^ Ora, enquanto Pedro estava sentado embaixo, no pátio, veio uma das servas do sumo sacerdote,

[[v41-14-67]]

^<<v41-14-67,67>>^ e, vendo Pedro aquecer-se, olhou diretamente para ele e disse: “Tu também estavas com o Nazareno, este Jesus.”

[[v41-14-68]]

^<<v41-14-68,68>>^ Mas ele o negou, dizendo: “Nem o conheço nem entendo^&#42;1^ o que dizes”, e saiu para o vestíbulo.

[NOTE]
====
. Ou: “Nem conheço, nem entendo.”
====

[[v41-14-69]]

^<<v41-14-69,69>>^ Avistando-o ali a serva, principiou novamente a dizer aos que estavam parados ali: “Este é um deles.”

[[v41-14-70]]

^<<v41-14-70,70>>^ Negou-o novamente. E mais uma vez, pouco depois, os que estavam parados ali começaram a dizer a Pedro: “Certamente tu és um deles, pois, de fato, és galileu.”

[[v41-14-71]]

^<<v41-14-71,71>>^ Mas ele principiou a praguejar e a jurar: “Não conheço este homem de quem falais.”

[[v41-14-72]]

^<<v41-14-72,72>>^ E imediatamente cantou um galo, pela segunda vez; e Pedro lembrou-se da declaração que Jesus lhe fizera: “Antes de o galo cantar duas vezes, repudiar-me-ás três vezes.” E ele ficou abatido e se entregou ao choro.

'''

xref:041-marcos/041-marcos-013.adoc#v41-13-0[&#60; Capítulo Anterior] | <<v41-14-0,Topo>> | xref:041-marcos/041-marcos-015.adoc#v41-15-0[Próximo Capítulo &#62;]