include::./index.adoc[]

[[v41-8-0]]
=== Marcos, 8
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v41-8-1]]

^<<v41-8-1,1>>^ Naqueles dias, quando havia novamente uma grande multidão e não tinham nada para comer, convocou os discípulos e disse-lhes:

[[v41-8-2]]

^<<v41-8-2,2>>^ “Tenho pena da multidão, porque já faz três dias que permanecem perto de mim e não têm nada para comer;

[[v41-8-3]]

^<<v41-8-3,3>>^ e, se eu os enviar em jejum para seus lares, desfalecerão pela estrada. Deveras, alguns deles vieram de longe.”

[[v41-8-4]]

^<<v41-8-4,4>>^ Mas os seus discípulos responderam-lhe: “Donde poderia alguém satisfazê-los de pães aqui, num lugar isolado?”

[[v41-8-5]]

^<<v41-8-5,5>>^ Contudo, prosseguiu a perguntar-lhes: “Quantos pães tendes?” Disseram: “Sete.”

[[v41-8-6]]

^<<v41-8-6,6>>^ E ordenou que a multidão se recostasse no chão, e tomou os sete pães, deu graças, partiu-os e começou a dá-los aos seus discípulos para os servirem, e serviram-nos à multidão.

[[v41-8-7]]

^<<v41-8-7,7>>^ Tinham também alguns peixinhos; e, tendo-os abençoado, disse-lhes que os servissem também.

[[v41-8-8]]

^<<v41-8-8,8>>^ Concordemente, comeram e ficaram satisfeitos, e recolheram os pedaços que sobraram, sete cabazes cheios.

[[v41-8-9]]

^<<v41-8-9,9>>^ Contudo, havia cerca de quatro mil [homens]. Por fim os despediu.

[[v41-8-10]]

^<<v41-8-10,10>>^ E ele entrou imediatamente no barco, com seus discípulos, e chegou às regiões de Dalmanuta.

[[v41-8-11]]

^<<v41-8-11,11>>^ Ali saíram os fariseus e começaram a discutir com ele, buscando [obter] dele um sinal do céu, para o porem à prova.

[[v41-8-12]]

^<<v41-8-12,12>>^ Ele gemeu então profundamente com seu espírito e disse: “Por que busca esta geração um sinal? Deveras, eu digo: Nenhum sinal será dado a esta geração.”

[[v41-8-13]]

^<<v41-8-13,13>>^ Com isso os deixou, embarcou novamente e dirigiu-se à margem oposta.

[[v41-8-14]]

^<<v41-8-14,14>>^ Aconteceu que se esqueceram de levar pães, e, com a exceção de um só pão, não tinham nada consigo no barco.

[[v41-8-15]]

^<<v41-8-15,15>>^ E ele começou a ordenar-lhes expressamente, dizendo: “Mantende os olhos abertos, acautelai-vos do fermento dos fariseus e do fermento de Herodes.”

[[v41-8-16]]

^<<v41-8-16,16>>^ Disputaram então entre si sobre o fato de não terem pães.

[[v41-8-17]]

^<<v41-8-17,17>>^ Notando isso, ele lhes disse: “Por que disputais sobre não terdes pães? Não percebeis ainda e não compreendeis o significado? Estão os vossos corações obtusos no entendimento?

[[v41-8-18]]

^<<v41-8-18,18>>^ ‘Embora tenhais olhos, não vedes; e embora tenhais ouvidos, não ouvis?’ E não vos lembrais,

[[v41-8-19]]

^<<v41-8-19,19>>^ quando parti os cinco pães para os cinco mil [homens], quantos cestos cheios de pedaços recolhestes?” Disseram-lhe: “Doze.”

[[v41-8-20]]

^<<v41-8-20,20>>^ “Quando parti os sete para os quatro mil [homens], quantos cabazes cheios de pedaços recolhestes?” E disseram-lhe: “Sete.”

[[v41-8-21]]

^<<v41-8-21,21>>^ Com isso disse-lhes: “Ainda não compreendeis o significado?”

[[v41-8-22]]

^<<v41-8-22,22>>^ Aportaram então em Betsaida. Trouxeram-lhe ali um cego e suplicaram-lhe que tocasse nele.

[[v41-8-23]]

^<<v41-8-23,23>>^ E ele tomou o cego pela mão, levou-o para fora da aldeia, e, tendo cuspido nos olhos dele, pôs as mãos sobre ele e começou a dizer-lhe: “Vês alguma coisa?”

[[v41-8-24]]

^<<v41-8-24,24>>^ E o homem olhou^&#42;1^ e começou a dizer: “Vejo homens, pois observo o que parecem ser árvores, mas estão andando.”

[NOTE]
====
. Ou “recuperou a vista; voltou a enxergar”.
====

[[v41-8-25]]

^<<v41-8-25,25>>^ Então pôs as mãos novamente sobre os olhos do homem, e o homem viu claramente e ficou restabelecido, e estava vendo tudo distintamente.

[[v41-8-26]]

^<<v41-8-26,26>>^ Mandou-o assim para casa, dizendo: “Mas não entres na aldeia.”

[[v41-8-27]]

^<<v41-8-27,27>>^ Jesus e seus discípulos partiram então para as aldeias de Cesaréia de Filipe, e, em caminho, ele começou a interrogar os seus discípulos, dizendo-lhes: “Quem dizem os homens que eu sou?”

[[v41-8-28]]

^<<v41-8-28,28>>^ Disseram-lhe: “João Batista,^&#42;1^ e outros, Elias, ainda outros, Um dos profetas.”

[NOTE]
====
. Ou “Imersor; Submersor (Mergulhador)”. Gr.: Ba·pti·stén.
====

[[v41-8-29]]

^<<v41-8-29,29>>^ E ele lhes fez a pergunta: “Vós, porém, quem dizeis que eu sou?” Pedro^&#42;1^ disse-lhe, em resposta: “Tu és o Cristo.”

[NOTE]
====
. “Pedro”, אAB; Syp: “Simão”; Sys: “Kefa”. Veja Mt 16:18 n.: “rocha”.
====

[[v41-8-30]]

^<<v41-8-30,30>>^ Então os advertiu estritamente que não dissessem [isso] a ninguém a respeito dele.

[[v41-8-31]]

^<<v41-8-31,31>>^ Principiou também a ensinar-lhes que o Filho do homem tinha de passar por muitos sofrimentos e ser rejeitado pelos anciãos e pelos principais sacerdotes, e pelos escribas, e ser morto, e [que tinha de ser] levantado três dias depois.

[[v41-8-32]]

^<<v41-8-32,32>>^ De fato, fez esta declaração com franqueza. Mas Pedro tomou-o à parte e começou a censurá-lo.

[[v41-8-33]]

^<<v41-8-33,33>>^ Ele se voltou, olhou para os seus discípulos e censurou Pedro, dizendo: “Para trás de mim, Satanás, porque não tens os pensamentos de Deus, mas os de homens.”^&#42;1^

[NOTE]
====
. Ou “não tens a mente de Deus, mas a de homens”.
====

[[v41-8-34]]

^<<v41-8-34,34>>^ Chamou então a multidão a si, com seus discípulos, e disse-lhes: “Se alguém quer vir após mim, repudie-se a si mesmo e apanhe a sua estaca de tortura,^&#42;1^ e siga-me continuamente.

[NOTE]
====
. Veja Ap. 5C.
====

[[v41-8-35]]

^<<v41-8-35,35>>^ Pois, todo aquele que quiser salvar a sua alma,^&#42;1^ perdê-la-á; mas todo aquele que perder a sua alma por causa de mim e das boas novas, salvá-la-á.

[NOTE]
====
. Ou “vida”. Gr.: psy·khén; J17,18,22(hebr.): naf·shóh (de né·fesh). Veja Ap. 4A.
====

[[v41-8-36]]

^<<v41-8-36,36>>^ Realmente, de que proveito é para um homem ganhar o mundo inteiro e pagar com a perda da sua alma?

[[v41-8-37]]

^<<v41-8-37,37>>^ O que, realmente, daria o homem em troca de sua alma?

[[v41-8-38]]

^<<v41-8-38,38>>^ Porque todo aquele que ficar envergonhado de mim e das minhas palavras, nesta geração adúltera e pecaminosa, deste o Filho do homem também se envergonhará, quando chegar na glória de seu Pai, com os santos anjos.”

'''

xref:041-marcos/041-marcos-007.adoc#v41-7-0[&#60; Capítulo Anterior] | <<v41-8-0,Topo>> | xref:041-marcos/041-marcos-009.adoc#v41-9-0[Próximo Capítulo &#62;]