include::./index.adoc[]

[[v43-13-0]]
=== João, 13
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v43-13-1]]

^<<v43-13-1,1>>^ Ora, visto que ele sabia antes da festividade da páscoa que havia chegado a sua hora para se transferir deste mundo para o Pai, Jesus, tendo amado os seus próprios que estavam no mundo, amou-os até o fim.

[[v43-13-2]]

^<<v43-13-2,2>>^ Assim, enquanto prosseguia^&#42;1^ a refeição noturna, tendo o Diabo já posto no coração de Judas Iscariotes, filho de Simão, que o traísse,

[NOTE]
====
. Ou “se preparava”.
====

[[v43-13-3]]

^<<v43-13-3,3>>^ ele, sabendo que o Pai dera todas as coisas nas [suas] mãos, e que procedera de Deus e ia para Deus,

[[v43-13-4]]

^<<v43-13-4,4>>^ levantou-se da refeição noturna e pôs de lado a sua roupagem exterior. E, tomando uma toalha, cingiu-se.

[[v43-13-5]]

^<<v43-13-5,5>>^ Depois pôs água numa bacia e principiou a lavar os pés dos discípulos e a enxugá-los com a toalha de que estava cingido.

[[v43-13-6]]

^<<v43-13-6,6>>^ E, assim chegou a Simão Pedro. Este lhe disse: “Senhor,^&#42;1^ estás lavando os meus pés?”

[NOTE]
====
. Ou “Amo”.
====

[[v43-13-7]]

^<<v43-13-7,7>>^ Em resposta, Jesus disse-lhe: “O que estou fazendo, tu não entendes atualmente, mas entenderás depois destas coisas.”

[[v43-13-8]]

^<<v43-13-8,8>>^ Pedro disse-lhe: “Certamente nunca lavarás os meus pés.” Jesus respondeu-lhe: “A menos que eu te lave, não tens parte comigo.”

[[v43-13-9]]

^<<v43-13-9,9>>^ Simão Pedro disse-lhe: “Senhor, não só os meus pés, mas também as minhas mãos e a minha cabeça.”

[[v43-13-10]]

^<<v43-13-10,10>>^ Jesus disse-lhe: “Quem se banhou, não precisa lavar senão os seus pés, mas está inteiramente limpo. E vós estais limpos, mas não todos.”

[[v43-13-11]]

^<<v43-13-11,11>>^ Ele sabia, deveras, quem o traía. É por isso que disse: “Nem todos vós estais limpos.”

[[v43-13-12]]

^<<v43-13-12,12>>^ Tendo então lavado os pés deles e vestido a sua roupagem exterior, e tendo-se deitado novamente à mesa, disse-lhes: “Sabeis o que vos tenho feito?

[[v43-13-13]]

^<<v43-13-13,13>>^ Vós me chamais de ‘Instrutor’ e ‘Senhor’, e falais corretamente, pois eu o sou.

[[v43-13-14]]

^<<v43-13-14,14>>^ Portanto, se eu, embora Senhor e Instrutor, lavei os vossos pés, vós também deveis lavar os pés uns dos outros.

[[v43-13-15]]

^<<v43-13-15,15>>^ Pois estabeleci o modelo para vós, a fim de que, assim como eu vos fiz, vós também façais.

[[v43-13-16]]

^<<v43-13-16,16>>^ Digo-vos em toda a verdade: O escravo não é maior do que o seu amo, nem é o enviado^&#42;1^ maior do que aquele que o enviou.

[NOTE]
====
. “O enviado.” Ou “um apóstolo (emissário)”. Gr.: a·pó·sto·los; lat.: a·pó·sto·lus.
====

[[v43-13-17]]

^<<v43-13-17,17>>^ Se sabeis estas coisas, felizes sois se as fizerdes.

[[v43-13-18]]

^<<v43-13-18,18>>^ Não estou falando a respeito de todos vós; conheço os que tenho escolhido. Mas, é para que se cumpra a escritura: ‘Aquele que costumava alimentar-se do meu pão ergueu o seu calcanhar contra mim.’

[[v43-13-19]]

^<<v43-13-19,19>>^ Deste momento em diante, digo-vos antes que ocorra, para que, quando ocorrer, acrediteis que sou eu.

[[v43-13-20]]

^<<v43-13-20,20>>^ Digo-vos em toda a verdade: Quem receber a qualquer que eu enviar, recebe [também] a mim. Por sua vez, quem me receber, recebe [também] aquele que me enviou.”

[[v43-13-21]]

^<<v43-13-21,21>>^ Depois de dizer estas coisas, Jesus ficou aflito em espírito, e deu testemunho e disse: “Digo-vos em toda a verdade: Um de vós me trairá.”

[[v43-13-22]]

^<<v43-13-22,22>>^ Os discípulos começaram a olhar uns para os outros, sem saber de qual deles dizia [isso].

[[v43-13-23]]

^<<v43-13-23,23>>^ Recostava-se na frente do seio de Jesus um dos seus discípulos, e Jesus o amava.^&#42;1^

[NOTE]
====
. Ou “preferia”.
====

[[v43-13-24]]

^<<v43-13-24,24>>^ Portanto, Simão Pedro acenou com a cabeça para este e disse-lhe: “Dize a respeito de quem ele está dizendo [isso].”

[[v43-13-25]]

^<<v43-13-25,25>>^ De modo que este último se encostou no peito de Jesus e lhe disse: “Senhor, quem é?”

[[v43-13-26]]

^<<v43-13-26,26>>^ Jesus respondeu-lhe, portanto: “É aquele a quem eu der o bocado que mergulho.” E assim, tendo mergulhado o bocado, tomou-o e deu-o a Judas, filho de Simão Iscariotes.

[[v43-13-27]]

^<<v43-13-27,27>>^ E após o bocado, Satanás entrou então neste último. Jesus, portanto, disse-lhe: “O que fazes, faze-o mais depressa.”

[[v43-13-28]]

^<<v43-13-28,28>>^ No entanto, nenhum dos que se recostavam à mesa sabia para que fim ele lhe disse isso.

[[v43-13-29]]

^<<v43-13-29,29>>^ Alguns, de fato, visto que Judas tinha a caixa de dinheiro, imaginavam que Jesus lhe dizia: “Compra as coisas que necessitamos para a festividade”, ou que desse algo aos pobres.

[[v43-13-30]]

^<<v43-13-30,30>>^ Portanto, depois de ter recebido o bocado, saiu imediatamente. E era noite.

[[v43-13-31]]

^<<v43-13-31,31>>^ Por isso, tendo ele saído, Jesus disse: “Agora é glorificado o Filho do homem, e Deus é glorificado em conexão com ele.^&#42;1^

[NOTE]
====
. Ou “por meio dele”.
====

[[v43-13-32]]

^<<v43-13-32,32>>^ E Deus mesmo o glorificará, e o glorificará imediatamente.

[[v43-13-33]]

^<<v43-13-33,33>>^ Filhinhos, estou convosco mais um pouco. Procurar-me-eis; e, assim como eu disse aos judeus: ‘Para onde eu vou, não podeis ir’, digo também a vós atualmente.

[[v43-13-34]]

^<<v43-13-34,34>>^ Eu vos dou um novo mandamento, que vos ameis uns aos outros; assim como eu vos amei, que também vos ameis uns aos outros.

[[v43-13-35]]

^<<v43-13-35,35>>^ Por meio disso saberão todos que sois meus discípulos, se tiverdes amor entre vós.”

[[v43-13-36]]

^<<v43-13-36,36>>^ Simão Pedro disse-lhe: “Senhor, para onde vais?” Jesus respondeu: “Para onde eu vou, não podes seguir-me agora, mas, seguir-me-ás depois.”

[[v43-13-37]]

^<<v43-13-37,37>>^ Pedro disse-lhe: “Senhor, por que é que não te posso seguir atualmente? Entregarei a minha alma em benefício de ti.”

[[v43-13-38]]

^<<v43-13-38,38>>^ Jesus respondeu: “Entregarás a tua alma^&#42;1^ em meu benefício? Digo-te em toda a verdade: De modo algum cantará o galo até que me tenhas repudiado três vezes.”

[NOTE]
====
. Ou “vida”. Gr.: psy·khén; lat.: á·ni·mam; J17,18,22(hebr.): naf·shekhá (de né·fesh).
====

'''

xref:043-joao/043-joao-012.adoc#v43-12-0[&#60; Capítulo Anterior] | <<v43-13-0,Topo>> | xref:043-joao/043-joao-014.adoc#v43-14-0[Próximo Capítulo &#62;]