include::./index.adoc[]

[[v43-8-0]]
=== João, 8
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v43-8-1]]

^<<v43-8-1,1>>^ Mas Jesus foi para o Monte das Oliveiras.

[[v43-8-2]]

^<<v43-8-2,2>>^ De madrugada, porém, ele se apresentou novamente no templo e todo o povo começou a vir a ele, e ele se assentou e começou a ensiná-los.

[[v43-8-3]]

^<<v43-8-3,3>>^ Os escribas e os fariseus trouxeram então uma mulher apanhada em adultério, e, depois de a postarem no meio deles,

[[v43-8-4]]

^<<v43-8-4,4>>^ disseram-lhe: “Instrutor, esta mulher foi apanhada no ato de cometer adultério.

[[v43-8-5]]

^<<v43-8-5,5>>^ Na Lei, Moisés prescreve que apedrejemos tal sorte de mulher. Realmente, o que dizes tu?”

[[v43-8-6]]

^<<v43-8-6,6>>^ Naturalmente, diziam isso para o porem à prova, a fim de terem algo com que o acusar. Mas, Jesus abaixou-se e começou a escrever no chão com o seu dedo.

[[v43-8-7]]

^<<v43-8-7,7>>^ Quando persistiram em perguntar-lhe, endireitou-se e disse-lhes: “Que aquele de vós que estiver sem pecado seja o primeiro a atirar-lhe uma pedra.”

[[v43-8-8]]

^<<v43-8-8,8>>^ E, abaixando-se novamente, escrevia no chão.

[[v43-8-9]]

^<<v43-8-9,9>>^ Mas, os que ouviram isso começaram a sair, um por um, principiando com os anciãos, e ele foi deixado só, bem como a mulher que estivera no meio deles.

[[v43-8-10]]

^<<v43-8-10,10>>^ Endireitando-se, Jesus disse-lhe: “Mulher, onde estão eles? Não te condenou ninguém?”

[[v43-8-11]]

^<<v43-8-11,11>>^ Ela disse: “Ninguém, senhor.” Jesus disse: “Tampouco eu te condeno. Vai embora; doravante não pratiques mais pecado.”

[[v43-8-12]]

^<<v43-8-12,12>>^ Portanto, Jesus falou-lhes novamente, dizendo: “Eu sou a luz do mundo. Quem me segue, de modo algum andará na escuridão, mas possuirá a luz da vida.”

[[v43-8-13]]

^<<v43-8-13,13>>^ Os fariseus disseram-lhe, por isso: “Dás testemunho de ti mesmo; teu testemunho não é verdadeiro.”

[[v43-8-14]]

^<<v43-8-14,14>>^ Em resposta, Jesus disse-lhes: “Mesmo que eu dê testemunho de mim mesmo, meu testemunho^&#42;1^ é verdadeiro, porque sei donde vim e para onde vou. Mas vós não sabeis donde vim e para onde vou.

[NOTE]
====
. “Testemunho.” Gr.: mar·ty·rí·a; lat.: te·sti·mó·ni·um.
====

[[v43-8-15]]

^<<v43-8-15,15>>^ Vós julgais segundo a carne; eu não julgo a nenhum homem.

[[v43-8-16]]

^<<v43-8-16,16>>^ E, contudo, se eu julgo, o meu julgamento é veraz, porque não estou sozinho, mas o Pai,^&#42;1^ que me enviou, está comigo.

[NOTE]
====
. “O Pai”, P66,75אcBVg; א°DSyc,s: “aquele”.
====

[[v43-8-17]]

^<<v43-8-17,17>>^ Também, na vossa própria Lei está escrito: ‘O testemunho de dois homens é verdadeiro.’

[[v43-8-18]]

^<<v43-8-18,18>>^ Eu sou um que dá testemunho de mim mesmo, e o Pai que me enviou dá testemunho de mim.”

[[v43-8-19]]

^<<v43-8-19,19>>^ Portanto, prosseguiram a dizer-lhe: “Onde está o teu Pai?” Jesus respondeu: “Vós não conheceis nem a mim nem a meu Pai. Se me conhecêsseis, conheceríeis também a meu Pai.”

[[v43-8-20]]

^<<v43-8-20,20>>^ Fez estas declarações na tesouraria, ao estar ensinando no templo. Mas ninguém o segurou, porque a sua hora ainda não havia chegado.

[[v43-8-21]]

^<<v43-8-21,21>>^ Ele lhes disse, por isso, novamente: “Eu vou embora, e vós me procurareis, contudo, morrereis nos vossos pecados. Para onde eu vou, não podeis ir.”

[[v43-8-22]]

^<<v43-8-22,22>>^ Portanto, os judeus começaram a dizer: “Será que ele se matará? Porque diz: ‘Para onde eu vou, não podeis ir.’”

[[v43-8-23]]

^<<v43-8-23,23>>^ De modo que prosseguiu a dizer-lhes: “Vós sois dos domínios^&#42;1^ de baixo; eu sou dos domínios de cima. Vós sois deste mundo; eu não sou deste mundo.

[NOTE]
====
. Ou “das coisas”.
====

[[v43-8-24]]

^<<v43-8-24,24>>^ Portanto, eu vos disse: Morrereis nos vossos pecados. Pois, se não acreditardes que sou eu, morrereis nos vossos pecados.”

[[v43-8-25]]

^<<v43-8-25,25>>^ Começaram então a dizer-lhe: “Quem és?” Jesus disse-lhes: “Por que é que estou falando convosco?^&#42;1^

[NOTE]
====
. Ou: “O que é que eu vos estive dizendo.”
====

[[v43-8-26]]

^<<v43-8-26,26>>^ Tenho muitas coisas para falar a respeito de vós e para julgar. De fato, aquele que me enviou é verdadeiro, e as próprias coisas que ouvi dele, eu falo no mundo.”

[[v43-8-27]]

^<<v43-8-27,27>>^ Não compreenderam que lhes falava do Pai.

[[v43-8-28]]

^<<v43-8-28,28>>^ Portanto, Jesus disse: “Uma vez que tiverdes erguido o Filho do homem, então sabereis que sou eu e que não faço nada de minha própria iniciativa;^&#42;1^ mas assim como o Pai me ensinou, estas coisas eu falo.

[NOTE]
====
. Lit.: “de mim mesmo”.
====

[[v43-8-29]]

^<<v43-8-29,29>>^ E aquele que me enviou está comigo; ele não me deixou só, porque faço sempre as coisas que lhe agradam.”

[[v43-8-30]]

^<<v43-8-30,30>>^ Ao falar estas coisas, muitos depositaram fé nele.

[[v43-8-31]]

^<<v43-8-31,31>>^ E Jesus prosseguiu assim a dizer aos judeus que acreditavam nele: “Se permanecerdes na minha palavra, sois realmente meus discípulos,

[[v43-8-32]]

^<<v43-8-32,32>>^ e conhecereis a verdade, e a verdade vos libertará.”

[[v43-8-33]]

^<<v43-8-33,33>>^ Replicaram-lhe: “Somos descendência^&#42;1^ de Abraão e nunca fomos escravos de ninguém. Como é que dizes: ‘Ficareis livres’?”

[NOTE]
====
. Ou “semente”.
====

[[v43-8-34]]

^<<v43-8-34,34>>^ Jesus respondeu-lhes: “Digo-vos em toda a verdade: Todo praticante do pecado é escravo do pecado.

[[v43-8-35]]

^<<v43-8-35,35>>^ Ainda mais, o escravo não permanece para sempre na família; o filho permanece para sempre.

[[v43-8-36]]

^<<v43-8-36,36>>^ Portanto, se o Filho vos libertar, sereis realmente livres.

[[v43-8-37]]

^<<v43-8-37,37>>^ Sei que sois descendência de Abraão; mas vós buscais matar-me, porque a minha palavra não faz progresso entre vós.

[[v43-8-38]]

^<<v43-8-38,38>>^ Eu falo das coisas que vi junto de meu Pai; e vós, portanto, fazeis as coisas que ouvistes de vosso pai.”

[[v43-8-39]]

^<<v43-8-39,39>>^ Em resposta, disseram-lhe: “Nosso pai é Abraão.” Jesus disse-lhes: “Se sois filhos de Abraão, fazei as obras de Abraão.

[[v43-8-40]]

^<<v43-8-40,40>>^ Mas agora buscais matar a mim, um homem que vos disse a verdade que eu ouvi de Deus. Abraão não fez isso.

[[v43-8-41]]

^<<v43-8-41,41>>^ Vós fazeis a obra de vosso pai.” Disseram-lhe: “Não nascemos de fornicação; temos um só Pai, Deus.”

[[v43-8-42]]

^<<v43-8-42,42>>^ Jesus disse-lhes: “Se Deus fosse o vosso Pai, vós me amaríeis, pois procedi de Deus e aqui estou. Nem tampouco vim de minha própria iniciativa, mas Este me enviou.

[[v43-8-43]]

^<<v43-8-43,43>>^ Por que é que não sabeis de que estou falando? Porque não podeis escutar a minha palavra.

[[v43-8-44]]

^<<v43-8-44,44>>^ Vós sois de vosso pai, o Diabo, e quereis fazer os desejos de vosso pai. Esse foi um homicida quando começou, e não permaneceu firme na verdade, porque não há nele verdade. Quando fala a mentira, fala segundo a sua própria disposição, porque é um mentiroso e o pai da [mentira].^&#42;1^

[NOTE]
====
. “Da mentira”, J17,22. Lit.: “dela”.
====

[[v43-8-45]]

^<<v43-8-45,45>>^ Porque eu, por outro lado, digo a verdade, vós não me acreditais.

[[v43-8-46]]

^<<v43-8-46,46>>^ Quem de vós me declara culpado de pecado? Se falo a verdade, por que não me acreditais?

[[v43-8-47]]

^<<v43-8-47,47>>^ Quem é de Deus escuta as declarações de Deus. É por isso que não escutais, porque não sois de Deus.”

[[v43-8-48]]

^<<v43-8-48,48>>^ Em resposta, os judeus disseram-lhe: “Não dizemos corretamente: Tu és samaritano e tens demônio?”^&#42;1^

[NOTE]
====
. Ou “e estás endemoninhado”.
====

[[v43-8-49]]

^<<v43-8-49,49>>^ Jesus respondeu: “Eu não tenho demônio,^&#42;1^ mas honro a meu Pai, e vós me desonrais.

[NOTE]
====
. Ou: “Eu não estou endemoninhado.”
====

[[v43-8-50]]

^<<v43-8-50,50>>^ Mas não busco glória para mim mesmo; há Um que busca e julga.

[[v43-8-51]]

^<<v43-8-51,51>>^ Digo-vos em toda a verdade: Se alguém observar a minha palavra, nunca jamais verá a morte.”

[[v43-8-52]]

^<<v43-8-52,52>>^ Os judeus disseram-lhe: “Agora sabemos que tens demônio.^&#42;1^ Abraão morreu, também os profetas; mas tu dizes: ‘Se alguém observar a minha palavra, nunca jamais provará a morte.’

[NOTE]
====
. Ou “estás endemoninhado”.
====

[[v43-8-53]]

^<<v43-8-53,53>>^ Será que tu és maior do que nosso pai Abraão, que morreu? Também os profetas morreram. Quem afirmas ser?”

[[v43-8-54]]

^<<v43-8-54,54>>^ Jesus respondeu: “Se eu glorificar a mim mesmo, a minha glória não é nada. É meu Pai quem me glorifica, aquele que dizeis ser vosso Deus;

[[v43-8-55]]

^<<v43-8-55,55>>^ e, no entanto, vós não o conhecestes. Mas eu o conheço. E, se eu dissesse que não o conheço, seria igual a vós, mentiroso. Mas eu o conheço e observo a sua palavra.

[[v43-8-56]]

^<<v43-8-56,56>>^ Abraão, vosso pai, alegrou-se grandemente na perspectiva de ver o meu dia, e ele o viu e se alegrou.”

[[v43-8-57]]

^<<v43-8-57,57>>^ Portanto, os judeus disseram-lhe: “Não tens nem cinqüenta anos, e ainda assim viste Abraão?”^&#42;1^

[NOTE]
====
. “Viste Abraão?” P66אcABCDVg; P75א°Sys: “Abraão te viu?”
====

[[v43-8-58]]

^<<v43-8-58,58>>^ Jesus disse-lhes: “Digo-vos em toda a verdade: Antes de Abraão vir à existência, eu tenho sido.”^&#42;1^

[NOTE]
====
. “Eu tenho sido.” Veja o Ap. 6F para um exame da existência pré-humana de Jesus.
====

[[v43-8-59]]

^<<v43-8-59,59>>^ Apanharam assim pedras para lhe atirarem; mas Jesus se escondeu e saiu do templo.

'''

xref:043-joao/043-joao-007.adoc#v43-7-0[&#60; Capítulo Anterior] | <<v43-8-0,Topo>> | xref:043-joao/043-joao-009.adoc#v43-9-0[Próximo Capítulo &#62;]