include::./index.adoc[]

[[v43-20-0]]
=== João, 20
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v43-20-1]]

^<<v43-20-1,1>>^ No primeiro dia da semana, Maria Madalena veio cedo ao túmulo memorial, enquanto ainda estava escuro, e observou a pedra já retirada do túmulo memorial.

[[v43-20-2]]

^<<v43-20-2,2>>^ Ela correu, portanto, e veio a Simão Pedro e ao outro discípulo, por quem Jesus tinha afeição, e disse-lhes: “Retiraram o Senhor^&#42;1^ do túmulo memorial, e não sabemos onde o deitaram.”

[NOTE]
====
. Ou “Amo”.
====

[[v43-20-3]]

^<<v43-20-3,3>>^ Pedro e o outro discípulo saíram então e partiram para o túmulo memorial.

[[v43-20-4]]

^<<v43-20-4,4>>^ Sim, os dois começaram a correr juntos; mas o outro discípulo correu na frente de Pedro, com mais velocidade, e atingiu primeiro o túmulo memorial.

[[v43-20-5]]

^<<v43-20-5,5>>^ E, inclinando-se para a frente, observou as faixas deitadas [ali], contudo, não entrou.

[[v43-20-6]]

^<<v43-20-6,6>>^ Então veio também Simão Pedro, seguindo-o, e ele entrou no túmulo memorial. E observou as faixas deitadas,

[[v43-20-7]]

^<<v43-20-7,7>>^ também que o pano que tinha estado sobre a cabeça dele não estava deitado com as faixas, mas [estava] enrolado separadamente num só lugar.

[[v43-20-8]]

^<<v43-20-8,8>>^ Naquela ocasião, portanto, o outro discípulo, que tinha atingido primeiro o túmulo memorial, também entrou, e viu e acreditou.

[[v43-20-9]]

^<<v43-20-9,9>>^ Porque ainda não discerniam a escritura, de que ele tinha de ser levantado dentre os mortos.

[[v43-20-10]]

^<<v43-20-10,10>>^ E os discípulos voltaram assim para os seus lares.

[[v43-20-11]]

^<<v43-20-11,11>>^ Maria, porém, ficou parada do lado de fora, perto do túmulo memorial, chorando. Então, enquanto chorava, inclinou-se para a frente a fim de olhar para dentro do túmulo memorial

[[v43-20-12]]

^<<v43-20-12,12>>^ e observou dois anjos, de branco, sentados um à cabeceira e outro aos pés do lugar onde o corpo de Jesus estivera deitado.

[[v43-20-13]]

^<<v43-20-13,13>>^ E disseram-lhe: “Mulher, por que estás chorando?” Ela lhes disse: “Retiraram o meu Senhor, e não sei onde o deitaram.”

[[v43-20-14]]

^<<v43-20-14,14>>^ Depois de dizer estas coisas, ela se voltou e observou Jesus em pé, mas não discernia que era Jesus.

[[v43-20-15]]

^<<v43-20-15,15>>^ Jesus disse-lhe: “Mulher, por que estás chorando? A quem estás procurando?” Ela, imaginando que fosse o jardineiro, disse-lhe: “Senhor, se tu o levaste embora, dize-me onde o deitaste, e eu o retirarei.”

[[v43-20-16]]

^<<v43-20-16,16>>^ Jesus disse-lhe: “Maria!” Dando meia-volta, ela disse-lhe, em hebraico: “Rabôni!”^&#42;1^ (que significa “Instrutor!”).

[NOTE]
====
. “Rabôni!” J18(hebr.): Rib·boh·ní.
====

[[v43-20-17]]

^<<v43-20-17,17>>^ Jesus disse-lhe: “Pára de agarrar-te a mim. Porque ainda não ascendi para junto do Pai. Mas, vai aos meus irmãos e dize-lhes: ‘Eu ascendo para junto de meu Pai e vosso Pai, e para meu Deus e vosso Deus.’”

[[v43-20-18]]

^<<v43-20-18,18>>^ Maria Madalena veio e trouxe a notícia aos discípulos: “Tenho visto o Senhor!” e que ele lhe dissera essas coisas.

[[v43-20-19]]

^<<v43-20-19,19>>^ Portanto, quando já era tarde naquele dia, o primeiro da semana, e, embora estivessem fechadas à chave as portas onde os discípulos estavam, de temor dos judeus, veio Jesus e ficou em pé no meio deles, e disse-lhes: “Haja paz convosco.”

[[v43-20-20]]

^<<v43-20-20,20>>^ E, depois de dizer isso, mostrou-lhes tanto as suas mãos como o seu lado. Os discípulos alegraram-se então por verem o Senhor.

[[v43-20-21]]

^<<v43-20-21,21>>^ Jesus, portanto, disse-lhes novamente: “Haja paz convosco. Assim como o Pai me enviou, eu também vos envio.”

[[v43-20-22]]

^<<v43-20-22,22>>^ E, depois de dizer isso, soprou sobre eles e disse-lhes: “Recebei espírito santo.

[[v43-20-23]]

^<<v43-20-23,23>>^ Se perdoardes os pecados de quaisquer pessoas, ficam-lhes perdoados; se retiverdes os de quaisquer pessoas, ficam-lhes retidos.”

[[v43-20-24]]

^<<v43-20-24,24>>^ Tomé, porém, um dos doze, que era chamado O Gêmeo,^&#42;1^ não estava com eles quando Jesus veio.

[NOTE]
====
. Ou “Dídimo”. Gr.: Dí·dy·mos; lat.: Dí·dy·mus.
====

[[v43-20-25]]

^<<v43-20-25,25>>^ Conseqüentemente, os outros discípulos diziam-lhe: “Temos visto o Senhor!” Mas, ele lhes disse: “A menos que eu veja nas suas mãos o sinal dos pregos e ponha o meu dedo no sinal dos pregos, e ponha a minha mão no seu lado, certamente não acreditarei.”

[[v43-20-26]]

^<<v43-20-26,26>>^ Bem, oito dias depois, seus discípulos estavam novamente portas adentro, e Tomé com eles. Jesus veio, embora as portas estivessem fechadas à chave, e ficou em pé no meio deles e disse: “Haja paz convosco.”

[[v43-20-27]]

^<<v43-20-27,27>>^ A seguir, disse a Tomé: “Põe o teu dedo aqui, e vê as minhas mãos, e toma a tua mão e põe-na no meu lado, e pára de ser incrédulo, mas torna-te crente.”

[[v43-20-28]]

^<<v43-20-28,28>>^ Em resposta, Tomé disse-lhe: “Meu Senhor e meu Deus!”

[[v43-20-29]]

^<<v43-20-29,29>>^ Jesus disse-lhe: “Creste porque me viste? Felizes são os que não vêem, contudo, crêem.”

[[v43-20-30]]

^<<v43-20-30,30>>^ De certo, Jesus efetuou muitos outros sinais, também diante dos discípulos, os quais não estão escritos neste rolo.

[[v43-20-31]]

^<<v43-20-31,31>>^ Mas, estes foram escritos para que creiais que Jesus é o Cristo, o Filho de Deus, e que, por crerdes, tenhais vida por meio do seu nome.

'''

xref:043-joao/043-joao-019.adoc#v43-19-0[&#60; Capítulo Anterior] | <<v43-20-0,Topo>> | xref:043-joao/043-joao-021.adoc#v43-21-0[Próximo Capítulo &#62;]