include::./index.adoc[]

[[v43-18-0]]
=== João, 18
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v43-18-1]]

^<<v43-18-1,1>>^ Tendo dito estas coisas, Jesus saiu com seus discípulos para o outro lado da torrente hibernal^&#42;1^ do Cédron, onde havia um horto, e ele e seus discípulos entraram nele.

[NOTE]
====
. Ou “do vale”.
====

[[v43-18-2]]

^<<v43-18-2,2>>^ Ora, Judas, quem o traía, também conhecia o lugar, porque Jesus muitas vezes se havia reunido ali com seus discípulos.

[[v43-18-3]]

^<<v43-18-3,3>>^ Portanto, Judas, tomando o destacamento de soldados e os oficiais dos principais sacerdotes e dos fariseus, foi para lá com tochas, e lâmpadas, e armas.

[[v43-18-4]]

^<<v43-18-4,4>>^ Jesus, portanto, sabendo todas as coisas que lhe sobrevinham, saiu e disse-lhes: “A quem procurais?”

[[v43-18-5]]

^<<v43-18-5,5>>^ Responderam-lhe: “A Jesus, o nazareno.” Disse-lhes ele: “Sou eu.” Então Judas, quem o traía, estava também parado com eles.

[[v43-18-6]]

^<<v43-18-6,6>>^ No entanto, quando lhes disse: “Sou eu”, recuaram e caíram no chão.

[[v43-18-7]]

^<<v43-18-7,7>>^ Portanto, perguntou-lhes novamente: “A quem procurais?” Disseram: “A Jesus, o nazareno.”

[[v43-18-8]]

^<<v43-18-8,8>>^ Jesus respondeu: “Eu vos disse que sou eu. Se, portanto, sou eu a quem procurais, deixai ir a estes”;

[[v43-18-9]]

^<<v43-18-9,9>>^ a fim de que se cumprisse a palavra que ele dissera: “Não perdi nem um único daqueles que me deste.”

[[v43-18-10]]

^<<v43-18-10,10>>^ Então Simão Pedro, visto que tinha espada, puxou-a e golpeou o escravo do sumo sacerdote, e cortou-lhe a orelha direita. O nome do escravo era Malco.

[[v43-18-11]]

^<<v43-18-11,11>>^ Jesus, porém, disse a Pedro: “Põe a espada na [sua] bainha. Não devia eu de toda maneira beber o copo que o Pai me tem dado?”

[[v43-18-12]]

^<<v43-18-12,12>>^ O destacamento de soldados, e o comandante militar,^&#42;1^ e os oficiais dos judeus apoderaram-se então de Jesus e o amarraram,

[NOTE]
====
. Ou “o quiliarca”. Gr.: ho khi·lí·ar·khos; o comandante de 1.000 soldados.
====

[[v43-18-13]]

^<<v43-18-13,13>>^ e levaram-no primeiro a Anás; pois ele era sogro de Caifás, que era sumo sacerdote naquele ano.

[[v43-18-14]]

^<<v43-18-14,14>>^ Caifás era, de fato, quem aconselhara aos judeus que era do seu proveito que um só homem morresse a favor do povo.

[[v43-18-15]]

^<<v43-18-15,15>>^ Ora, Simão Pedro, bem como outro discípulo, seguia Jesus. Esse discípulo era conhecido do sumo sacerdote, e ele entrou com Jesus no pátio do sumo sacerdote,

[[v43-18-16]]

^<<v43-18-16,16>>^ mas Pedro estava parado do lado de fora, junto à porta. Portanto, o outro discípulo, que era conhecido do sumo sacerdote, saiu e falou com a porteira e trouxe Pedro para dentro.

[[v43-18-17]]

^<<v43-18-17,17>>^ A serva, a porteira, disse então a Pedro: “Não és tu também um dos discípulos deste homem?” Ele disse: “Não sou.”

[[v43-18-18]]

^<<v43-18-18,18>>^ Ora, os escravos e os oficiais estavam parados por ali, visto que tinham aceso um fogo de brasas, porque fazia frio, e se aqueciam. Pedro também estava parado com eles e se aquecia.

[[v43-18-19]]

^<<v43-18-19,19>>^ E o principal sacerdote interrogou assim Jesus sobre os seus discípulos e sobre o seu ensino.

[[v43-18-20]]

^<<v43-18-20,20>>^ Jesus respondeu-lhe: “Falei ao mundo publicamente. Sempre ensinei numa sinagoga e no templo, onde todos os judeus se reúnem; e não falei nada em secreto.

[[v43-18-21]]

^<<v43-18-21,21>>^ Por que me interrogas? Interroga os que ouviram o que lhes falei. Eis que estes sabem o que eu disse.”

[[v43-18-22]]

^<<v43-18-22,22>>^ Depois de ele dizer estas coisas, um dos oficiais parados ali deu uma bofetada em Jesus e disse: “É assim que respondes ao principal sacerdote?”

[[v43-18-23]]

^<<v43-18-23,23>>^ Jesus respondeu-lhe: “Se falei de modo errado, dá testemunho acerca do erro; mas, se [falei] de modo correto, por que me bates?”

[[v43-18-24]]

^<<v43-18-24,24>>^ Anás mandou-o então amarrado a Caifás, o sumo sacerdote.

[[v43-18-25]]

^<<v43-18-25,25>>^ Ora, Simão Pedro estava parado e se aquecia. Disseram-lhe então: “Não és tu também um dos seus discípulos?” Ele o negou e disse: “Não sou.”

[[v43-18-26]]

^<<v43-18-26,26>>^ Um dos escravos do sumo sacerdote, sendo parente do homem cuja orelha Pedro cortara, disse: “Não te vi no jardim com ele?”

[[v43-18-27]]

^<<v43-18-27,27>>^ No entanto, Pedro negou-o novamente; e, imediatamente, cantou um galo.

[[v43-18-28]]

^<<v43-18-28,28>>^ Conduziram então Jesus de Caifás para o palácio do governador. Já era de manhã cedo. Mas eles mesmos não entraram no palácio do governador, para que não se aviltassem, mas pudessem comer a páscoa.

[[v43-18-29]]

^<<v43-18-29,29>>^ Portanto, Pilatos saiu a ter com eles e disse: “Que acusação levantais contra este homem?”

[[v43-18-30]]

^<<v43-18-30,30>>^ Disseram-lhe, em resposta: “Se este homem não fosse delinqüente, não o teríamos entregado a ti.”

[[v43-18-31]]

^<<v43-18-31,31>>^ Pilatos disse-lhes, por isso: “Tomai-o e julgai-o vós mesmos segundo a vossa lei.” Os judeus disseram-lhe: “Não nos é lícito matar alguém.”

[[v43-18-32]]

^<<v43-18-32,32>>^ Isto, a fim de que se cumprisse a palavra de Jesus, que ele dissera para indicar de que sorte de morte estava destinado a morrer.

[[v43-18-33]]

^<<v43-18-33,33>>^ De modo que Pilatos entrou novamente no palácio do governador e chamou Jesus e disse-lhe: “És tu o rei dos judeus?”^&#42;1^

[NOTE]
====
. “Rei dos judeus.” Gr.: ba·si·leús ton I·ou·daí·on; lat.: rex Iu·dae·ó·rum; J17,18,22(hebr.): mé·lekh hai·Yehu·dhím.
====

[[v43-18-34]]

^<<v43-18-34,34>>^ Jesus respondeu: “É de tua própria iniciativa que dizes isso ou te contaram outros a respeito de mim?”

[[v43-18-35]]

^<<v43-18-35,35>>^ Pilatos respondeu: “Será que eu sou judeu? A tua própria nação e os principais sacerdotes te entregaram a mim. O que fizeste?”

[[v43-18-36]]

^<<v43-18-36,36>>^ Jesus respondeu: “Meu reino não faz parte deste mundo. Se o meu reino fizesse parte deste mundo, meus assistentes teriam lutado para que eu não fosse entregue aos judeus. Mas, assim como é, o meu reino não é desta fonte.”

[[v43-18-37]]

^<<v43-18-37,37>>^ Portanto, Pilatos disse-lhe: “Pois bem, és tu rei?” Jesus respondeu: “Tu mesmo estás dizendo que eu sou rei. Para isso nasci e para isso vim ao mundo, a fim de dar testemunho^&#42;1^ da verdade. Todo aquele que está do lado da verdade escuta a minha voz.”

[NOTE]
====
. “A fim de dar testemunho.” Gr.: mar·ty·ré·so; lat.: te·sti·mó·ni·um per·hí·be·am.
====

[[v43-18-38]]

^<<v43-18-38,38>>^ Pilatos disse-lhe: “Que é verdade?”^&#42;1^
E, depois de dizer isso, saiu novamente para os judeus e disse-lhes: “Não acho falta nele.

[NOTE]
====
. “Que é verdade?” Gr.: Tí e·stin a·lé·thei·a; lat.: Quid est vé·ri·tas; J17,18(hebr.): Mah hi’ ha·’eméth.
====

[[v43-18-39]]

^<<v43-18-39,39>>^ Ainda mais, tendes o costume de que eu vos livre um homem por ocasião da páscoa. Quereis, portanto, que eu vos livre o rei dos judeus?”

[[v43-18-40]]

^<<v43-18-40,40>>^ Gritaram então de novo, dizendo: “Não este homem, mas Barrabás!” Ora, Barrabás era salteador.

'''

xref:043-joao/043-joao-017.adoc#v43-17-0[&#60; Capítulo Anterior] | <<v43-18-0,Topo>> | xref:043-joao/043-joao-019.adoc#v43-19-0[Próximo Capítulo &#62;]