include::./index.adoc[]

[[v43-12-0]]
=== João, 12
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v43-12-1]]

^<<v43-12-1,1>>^ Concordemente, Jesus, seis dias antes da páscoa, chegou a Betânia, onde estava Lázaro,^&#42;1^ a quem Jesus levantara dentre os mortos.

[NOTE]
====
. Veja 11:1 n.
====

[[v43-12-2]]

^<<v43-12-2,2>>^ Ofereceram-lhe ali, portanto, uma refeição noturna, e Marta ministrava, mas Lázaro era um dos que se recostavam à mesa com ele.

[[v43-12-3]]

^<<v43-12-3,3>>^ Maria, portanto, tomou quase meio quilo^&#42;1^ de óleo perfumado, nardo genuíno, muito dispendioso, e untou os pés de Jesus e enxugou os pés dele com seu cabelo. A casa encheu-se com a fragrância do óleo perfumado.

[NOTE]
====
. Gr.: lí·tran. Cerca de 327 g.
====

[[v43-12-4]]

^<<v43-12-4,4>>^ Mas Judas Iscariotes, um dos seus discípulos, que estava para traí-lo, disse:

[[v43-12-5]]

^<<v43-12-5,5>>^ “Por que não se vendeu este óleo perfumado por trezentos denários^&#42;1^ e se deu aos pobres?”

[NOTE]
====
. Cerca de US$ 260, quando se calcula a prata a US$ 0,22 por g. Veja Ap. 8A.
====

[[v43-12-6]]

^<<v43-12-6,6>>^ Ele disse isso, porém, não porque estivesse preocupado com os pobres, mas porque era um ladrão e tinha a caixa de dinheiro e costumava retirar dinheiro posto nela.

[[v43-12-7]]

^<<v43-12-7,7>>^ Portanto, Jesus disse: “Deixai-a, para que ela mantenha esta observância, em vista do dia do meu enterro.

[[v43-12-8]]

^<<v43-12-8,8>>^ Pois vós tendes sempre convosco os pobres, mas a mim nem sempre tereis.”

[[v43-12-9]]

^<<v43-12-9,9>>^ Portanto, uma grande multidão dos judeus ficou sabendo que ele estava ali, e eles vieram, não somente por causa de Jesus, mas também para ver Lázaro, a quem levantara dentre os mortos.

[[v43-12-10]]

^<<v43-12-10,10>>^ Os principais sacerdotes deliberaram matar também Lázaro,

[[v43-12-11]]

^<<v43-12-11,11>>^ visto que por causa dele muitos dos judeus iam para lá e depositavam fé em Jesus.

[[v43-12-12]]

^<<v43-12-12,12>>^ No dia seguinte, a grande multidão que tinha vindo à festividade, ao ouvirem que Jesus vinha a Jerusalém,

[[v43-12-13]]

^<<v43-12-13,13>>^ tomaram ramos de palmeiras e saíram ao encontro dele. E começaram a clamar: “Salva, rogamos-te!^&#42;1^ Bendito aquele que vem em nome de Jeová,^&#42;2^ sim, o rei de Israel!”

[NOTE]
====
. Lit.: “Hosana.” J7-14,16-19,22(hebr.): Hoh·sha‛-ná’.
. Veja Ap. 1D.
====

[[v43-12-14]]

^<<v43-12-14,14>>^ Mas, tendo Jesus achado um jumentinho, sentou-se nele, assim como está escrito:

[[v43-12-15]]

^<<v43-12-15,15>>^ “Não temas, filha de Sião. Eis que vem o teu rei, sentado num filho de jumenta.”

[[v43-12-16]]

^<<v43-12-16,16>>^ No princípio, os discípulos não fizeram caso destas coisas, mas, quando Jesus foi glorificado, então se lembraram de que estas coisas estavam escritas a respeito dele e que lhe fizeram estas coisas.

[[v43-12-17]]

^<<v43-12-17,17>>^ A multidão, que estivera com ele quando chamou Lázaro para fora do túmulo memorial e o levantou dentre os mortos, concordemente, dava testemunho.

[[v43-12-18]]

^<<v43-12-18,18>>^ Por esta razão, a multidão também foi ao encontro dele, porque ouviram que ele realizara este sinal.

[[v43-12-19]]

^<<v43-12-19,19>>^ Os fariseus disseram, por isso, entre si mesmos: “Observais que não conseguis absolutamente nada. Eis que o mundo foi atrás dele.”

[[v43-12-20]]

^<<v43-12-20,20>>^ Ora, havia alguns gregos entre os que subiram para adorar na festividade.

[[v43-12-21]]

^<<v43-12-21,21>>^ Estes, portanto, chegaram-se a Filipe, que era de Betsaida da Galiléia, e começaram a solicitar-lhe, dizendo: “Senhor, queremos ver Jesus.”

[[v43-12-22]]

^<<v43-12-22,22>>^ Filipe veio e [o] disse a André. André e Filipe vieram e [o] disseram a Jesus.

[[v43-12-23]]

^<<v43-12-23,23>>^ Mas Jesus respondeu-lhes, dizendo: “Chegou a hora para o Filho do homem ser glorificado.

[[v43-12-24]]

^<<v43-12-24,24>>^ Eu vos digo em toda a verdade: A menos que o grão de trigo caia ao solo e morra, permanece apenas um só [grão]; mas, se morre, então dá muito fruto.

[[v43-12-25]]

^<<v43-12-25,25>>^ Quem estiver afeiçoado à sua alma,^&#42;1^ destruí-la-á, mas quem odiar a sua alma neste mundo, protegê-la-á para a vida eterna.

[NOTE]
====
. Ou “vida”. Gr.: psy·khén; J17,18,22(hebr.): naf·shóh (de né·fesh).
====

[[v43-12-26]]

^<<v43-12-26,26>>^ Se alguém quiser ministrar-me, siga-me, e onde eu estiver, estará também o meu ministro.^&#42;1^ Quem quiser ministrar-me, a este o Pai honrará.

[NOTE]
====
. “Ministro.” Gr.: di·á·ko·nos; lat.: mi·ní·ster (de mí·nus, “menos”); J18,22(hebr.): mesha·rethí, “meu ministro”.
====

[[v43-12-27]]

^<<v43-12-27,27>>^ Minha alma está aflita agora, e que hei de dizer? Pai, salva-me desta hora. Não obstante, foi por isso que vim a esta hora.

[[v43-12-28]]

^<<v43-12-28,28>>^ Pai, glorifica o teu nome.” Saiu, portanto, uma voz do céu: “Eu tanto [o] glorifiquei como [o] glorificarei de novo.”

[[v43-12-29]]

^<<v43-12-29,29>>^ Por isso, a multidão parada ali e ouvindo-o começou a dizer que tinha trovejado. Outros começaram a dizer: “Um anjo lhe falou.”

[[v43-12-30]]

^<<v43-12-30,30>>^ Em resposta, Jesus disse: “Esta voz ocorreu, não por minha causa, mas por vossa causa.

[[v43-12-31]]

^<<v43-12-31,31>>^ Agora há um julgamento deste mundo; agora será lançado fora o governante deste mundo.

[[v43-12-32]]

^<<v43-12-32,32>>^ Contudo, eu, quando for erguido da terra, atrairei a mim toda sorte de homens.”^&#42;1^

[NOTE]
====
. Ou “todos os homens”.
====

[[v43-12-33]]

^<<v43-12-33,33>>^ Dizia isso realmente para indicar de que sorte de morte estava para morrer.

[[v43-12-34]]

^<<v43-12-34,34>>^ Portanto, a multidão respondeu-lhe: “Ouvimos da Lei que o Cristo permanece para sempre; e como é que tu dizes que o Filho do homem tem de ser erguido? Quem é este Filho do homem?”

[[v43-12-35]]

^<<v43-12-35,35>>^ Jesus disse-lhes, portanto: “A luz estará entre vós por mais um pouco de tempo. Andai enquanto tendes a luz, para que não vos vença a escuridão; e, quem anda na escuridão, não sabe para onde vai.

[[v43-12-36]]

^<<v43-12-36,36>>^ Enquanto tendes a luz, exercei fé na luz, a fim de que vos torneis filhos da luz.”
Jesus falou estas coisas e foi embora, e escondeu-se deles.

[[v43-12-37]]

^<<v43-12-37,37>>^ Mas, embora tivesse realizado tantos sinais na frente deles, não depositavam fé nele,

[[v43-12-38]]

^<<v43-12-38,38>>^ de modo que se cumpriu a palavra de Isaías, o profeta, que disse: “Jeová,^&#42;1^ quem depositou fé na coisa ouvida por nós?^&#42;2^ E quanto ao braço de Jeová,^&#42;3^ a quem tem sido revelado?”

[NOTE]
====
. Veja Ap. 1D.
. Ou: “quem acreditou no nosso relato?”
. Veja Ap. 1D.
====

[[v43-12-39]]

^<<v43-12-39,39>>^ A razão por que não podiam crer é que Isaías disse novamente:

[[v43-12-40]]

^<<v43-12-40,40>>^ “Cegou-lhes os olhos e endureceu-lhes os corações, para que não vissem com os seus olhos, nem compreendessem o pensamento com os seus corações, nem se voltassem e eu os sarasse.”

[[v43-12-41]]

^<<v43-12-41,41>>^ Isaías disse estas coisas, porque viu a sua glória e falou dele.

[[v43-12-42]]

^<<v43-12-42,42>>^ De qualquer modo, muitos dos próprios governantes depositavam realmente fé nele, mas, por causa dos fariseus, não [o] confessavam, a fim de que não fossem expulsos da sinagoga;^&#42;1^

[NOTE]
====
. Veja 9:22 n.
====

[[v43-12-43]]

^<<v43-12-43,43>>^ pois amavam mais a glória dos homens do que mesmo a glória de Deus.

[[v43-12-44]]

^<<v43-12-44,44>>^ No entanto, Jesus clamou e disse: “Quem depositar fé em mim, deposita fé, não [somente] em mim, mas [também] naquele que me enviou;

[[v43-12-45]]

^<<v43-12-45,45>>^ e quem me observar, observa [também] aquele que me enviou.

[[v43-12-46]]

^<<v43-12-46,46>>^ Eu vim como luz ao mundo, a fim de que todo aquele que depositar fé em mim não permaneça na escuridão.

[[v43-12-47]]

^<<v43-12-47,47>>^ Mas, se alguém ouvir as minhas declarações e não as guardar, eu não o julgo; pois não vim julgar o mundo, mas salvar o mundo.

[[v43-12-48]]

^<<v43-12-48,48>>^ Quem me desconsiderar e não receber as minhas declarações, tem quem o julgue. A palavra que eu tenho falado é que o julgará no último dia;

[[v43-12-49]]

^<<v43-12-49,49>>^ porque não falei de meu próprio impulso, mas o próprio Pai que me enviou tem-me dado um mandamento quanto a que dizer e que falar.

[[v43-12-50]]

^<<v43-12-50,50>>^ Sei também que o seu mandamento significa^&#42;1^ vida eterna. Portanto, as coisas que eu falo, assim como o Pai mas disse, assim [as] falo.”

[NOTE]
====
. Ou “é”.
====

'''

xref:043-joao/043-joao-011.adoc#v43-11-0[&#60; Capítulo Anterior] | <<v43-12-0,Topo>> | xref:043-joao/043-joao-013.adoc#v43-13-0[Próximo Capítulo &#62;]