include::./index.adoc[]

[[v43-17-0]]
=== João, 17
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v43-17-1]]

^<<v43-17-1,1>>^ Jesus falou estas coisas, e, levantando os olhos para o céu, disse: “Pai, veio a hora; glorifica o teu filho, para que o teu filho te glorifique,

[[v43-17-2]]

^<<v43-17-2,2>>^ segundo lhe deste autoridade sobre toda a carne, para que, com respeito ao [número] inteiro dos que lhe deste, ele lhes dê vida eterna.

[[v43-17-3]]

^<<v43-17-3,3>>^ Isto significa vida eterna, que absorvam conhecimento de ti,^&#42;1^ o único Deus verdadeiro, e daquele que enviaste, Jesus Cristo.

[NOTE]
====
. Ou “que te conheçam”. Gr.: hí·na gi·nó·sko·si se.
====

[[v43-17-4]]

^<<v43-17-4,4>>^ Eu te tenho glorificado na terra, havendo terminado a obra que me deste para fazer.

[[v43-17-5]]

^<<v43-17-5,5>>^ De modo que agora, Pai, glorifica-me junto de ti com a glória que eu tive junto de ti antes de haver o mundo.

[[v43-17-6]]

^<<v43-17-6,6>>^ “Tenho feito manifesto o teu nome aos homens que me deste do mundo. Eram teus e tu mos deste, e eles têm observado a tua palavra.

[[v43-17-7]]

^<<v43-17-7,7>>^ Eles vieram agora a saber que todas as coisas que me deste são de ti;

[[v43-17-8]]

^<<v43-17-8,8>>^ porque eu lhes tenho dado as declarações que me deste, e eles as têm recebido e têm certamente chegado a saber que saí como teu representante, e eles têm acreditado que tu me enviaste.

[[v43-17-9]]

^<<v43-17-9,9>>^ Faço solicitação a respeito deles; faço solicitação, não a respeito do mundo, mas a respeito daqueles que me deste; porque são teus,

[[v43-17-10]]

^<<v43-17-10,10>>^ e todas as minhas coisas são tuas e as tuas são minhas, e eu tenho sido glorificado entre eles.

[[v43-17-11]]

^<<v43-17-11,11>>^ “Também, não estou mais no mundo, mas eles estão no mundo e eu vou para ti. Santo Pai, vigia sobre eles por causa do teu próprio nome que me deste, para que sejam um, assim como nós somos.

[[v43-17-12]]

^<<v43-17-12,12>>^ Quando eu estava com eles, costumava vigiar sobre eles por causa do teu próprio nome que me deste; e tenho-os guardado, e nenhum deles está destruído exceto o filho da destruição, para que se cumprisse a escritura.

[[v43-17-13]]

^<<v43-17-13,13>>^ Mas agora vou para ti e estou falando estas coisas no mundo, a fim de que tenham a minha alegria plenamente em si mesmos.

[[v43-17-14]]

^<<v43-17-14,14>>^ Tenho-lhes dado a tua palavra, mas o mundo os tem odiado, porque não fazem parte do mundo, assim como eu não faço parte do mundo.

[[v43-17-15]]

^<<v43-17-15,15>>^ “Solicito-te, não que os tires do mundo, mas que vigies sobre eles, por causa do iníquo.

[[v43-17-16]]

^<<v43-17-16,16>>^ Não fazem parte do mundo, assim como eu não faço parte do mundo.

[[v43-17-17]]

^<<v43-17-17,17>>^ Santifica-os por meio da verdade; a tua palavra é a verdade.

[[v43-17-18]]

^<<v43-17-18,18>>^ Assim como tu me enviaste ao mundo, eu também os enviei ao mundo.

[[v43-17-19]]

^<<v43-17-19,19>>^ E santifico-me^&#42;1^ em seu benefício, para que também sejam santificados por meio da verdade.

[NOTE]
====
. Ou: “E eu me tenho por sagrado (trato-me como santo).” Gr.: kai . . . e·gó ha·gi·á·zo e·mau·tón; lat.: et . . . é·go sanc·tí·fi·co me íp·sum; J17(hebr.): wehith·qad·dash·tí.
====

[[v43-17-20]]

^<<v43-17-20,20>>^ “Faço solicitação, não somente a respeito destes, mas também a respeito daqueles que depositam fé em mim por intermédio da palavra deles;

[[v43-17-21]]

^<<v43-17-21,21>>^ a fim de que todos sejam um,^&#42;1^ assim como tu, Pai, estás em união comigo e eu estou em união contigo, para que eles também estejam em união conosco, a fim de que o mundo acredite que me enviaste.

[NOTE]
====
. Ou “estejam em união”. Lit.: “uma (só coisa)”. Gr.: hen, neutro, para mostrar unidade na cooperação. Veja 10:30 n.
====

[[v43-17-22]]

^<<v43-17-22,22>>^ Também, eu lhes tenho dado a glória que tu me tens dado, a fim de que sejam um, assim como nós somos um.

[[v43-17-23]]

^<<v43-17-23,23>>^ Eu em união com eles e tu em união comigo, a fim de que sejam aperfeiçoados em um, para que o mundo tenha conhecimento de que tu me enviaste e que os amaste assim como amaste a mim.

[[v43-17-24]]

^<<v43-17-24,24>>^ Pai, quanto ao que me tens dado, quero que, onde eu estiver, eles também estejam comigo, a fim de que observem a minha glória que me tens dado, porque me amaste antes da fundação^&#42;1^ do mundo.

[NOTE]
====
. Lit.: “antes do lançamento para baixo [de semente]”. Gr.: pro ka·ta·bo·lés.
====

[[v43-17-25]]

^<<v43-17-25,25>>^ Justo Pai, o mundo, deveras, não veio a conhecer-te; mas eu vim a conhecer-te, e estes vieram a saber que tu me enviaste.

[[v43-17-26]]

^<<v43-17-26,26>>^ E eu lhes tenho dado a conhecer o teu nome e o hei de dar a conhecer, a fim de que o amor com que me amaste esteja neles e eu em união com eles.”

'''

xref:043-joao/043-joao-016.adoc#v43-16-0[&#60; Capítulo Anterior] | <<v43-17-0,Topo>> | xref:043-joao/043-joao-018.adoc#v43-18-0[Próximo Capítulo &#62;]