include::./index.adoc[]

[[v43-11-0]]
=== João, 11
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v43-11-1]]

^<<v43-11-1,1>>^ Ora, havia um homem doente, Lázaro^&#42;1^ de Betânia, da aldeia de Maria e de Marta, sua irmã.

[NOTE]
====
. “Lázaro”, אABJ17; J7-14,16,18,19,22: “Eleazar”, significando “Deus Ajudou”.
====

[[v43-11-2]]

^<<v43-11-2,2>>^ Era, de fato, Maria quem untara o Senhor^&#42;1^ com óleo perfumado e lhe enxugara os pés com o seu cabelo, sendo o irmão dela, Lázaro, quem estava doente.

[NOTE]
====
. Ou “Amo”.
====

[[v43-11-3]]

^<<v43-11-3,3>>^ Portanto, as irmãs deste mandaram-lhe dizer: “Senhor, eis que aquele por quem tens afeição está doente.”

[[v43-11-4]]

^<<v43-11-4,4>>^ Mas, quando Jesus o soube, disse: “Esta doença não tem a morte por seu objetivo, mas é para a glória de Deus, a fim de que o Filho de Deus seja glorificado por intermédio dela.”

[[v43-11-5]]

^<<v43-11-5,5>>^ Ora, Jesus amava a Marta, e a sua irmã, e a Lázaro.

[[v43-11-6]]

^<<v43-11-6,6>>^ No entanto, quando soube que este estava doente, permaneceu realmente dois dias no lugar onde estava.

[[v43-11-7]]

^<<v43-11-7,7>>^ Depois disse aos discípulos: “Vamos novamente à Judéia.”

[[v43-11-8]]

^<<v43-11-8,8>>^ Os discípulos disseram-lhe: “Rabi, os da Judéia^&#42;1^ têm ultimamente buscado apedrejar-te, e tu vais novamente para lá?”

[NOTE]
====
. Ou “judeus”. Gr.: I·ou·daí·oi, como em 10:31, 33.
====

[[v43-11-9]]

^<<v43-11-9,9>>^ Jesus respondeu: “Não há doze horas de luz no dia? Se alguém andar na luz do dia, não colidirá com coisa alguma, porque vê a luz deste mundo.

[[v43-11-10]]

^<<v43-11-10,10>>^ Mas, se alguém andar na noite, colidirá com algo, porque a luz não está nele.”

[[v43-11-11]]

^<<v43-11-11,11>>^ Ele disse estas coisas, e depois disso lhes disse: “Lázaro, nosso amigo, foi descansar, mas eu viajo para lá para o despertar do sono.”

[[v43-11-12]]

^<<v43-11-12,12>>^ Os discípulos disseram-lhe, portanto: “Senhor, se ele foi descansar, ficará bom.”^&#42;1^

[NOTE]
====
. Ou “será salvo”.
====

[[v43-11-13]]

^<<v43-11-13,13>>^ Jesus falara, porém, da morte dele. Mas, eles imaginavam que estivesse falando do descanso no sono.

[[v43-11-14]]

^<<v43-11-14,14>>^ Nessa ocasião, portanto, Jesus disse-lhes francamente: “Lázaro morreu,

[[v43-11-15]]

^<<v43-11-15,15>>^ e eu me alegro por causa de vós que não estava lá, a fim de que acrediteis. Mas, vamos ter com ele.”

[[v43-11-16]]

^<<v43-11-16,16>>^ Portanto, Tomé, que era chamado O Gêmeo,^&#42;1^ disse aos seus condiscípulos: “Vamos também, para que morramos com ele.”

[NOTE]
====
. Ou “Dídimo”. Gr.: Dí·dy·mos; lat.: Dí·dy·mus.
====

[[v43-11-17]]

^<<v43-11-17,17>>^ Conseqüentemente, quando Jesus chegou, achou que já estava quatro dias no túmulo memorial.

[[v43-11-18]]

^<<v43-11-18,18>>^ Ora, Betânia era perto de Jerusalém, a uma distância de cerca de três quilômetros.^&#42;1^

[NOTE]
====
. Lit.: “afastada uns quinze estádios”. Cerca de 2,8 km. O estádio equivalia a um oitavo de milha romana, 185 m.
====

[[v43-11-19]]

^<<v43-11-19,19>>^ Concordemente, muitos dos judeus haviam vindo a Marta e Maria, a fim de confortá-las pelo seu irmão.

[[v43-11-20]]

^<<v43-11-20,20>>^ Marta, portanto, quando ouviu que Jesus vinha, foi ao encontro dele; Maria, porém, ficou sentada em casa.

[[v43-11-21]]

^<<v43-11-21,21>>^ Marta, portanto, disse a Jesus: “Senhor,^&#42;1^ se tivesses estado aqui, meu irmão não teria morrido.

[NOTE]
====
. Ou “Amo”.
====

[[v43-11-22]]

^<<v43-11-22,22>>^ E, contudo, sei atualmente que quantas coisas pedires a Deus, Deus te dará.”

[[v43-11-23]]

^<<v43-11-23,23>>^ Jesus disse-lhe: “Teu irmão se levantará.”

[[v43-11-24]]

^<<v43-11-24,24>>^ Marta disse-lhe: “Sei que ele se levantará na ressurreição, no último dia.”

[[v43-11-25]]

^<<v43-11-25,25>>^ Jesus disse-lhe: “Eu sou a ressurreição e a vida.^&#42;1^ Quem exercer fé em mim, ainda que morra, viverá [outra vez];

[NOTE]
====
. “Eu sou a ressurreição e a vida.” Gr.: E·gó ei·mi he a·ná·sta·sis kai he zo·é; lat.: É·go sum re·sur·réc·ti·o et ví·ta; J17(hebr.): ’A·no·khí hat·tequ·máh weha·hhai·yím.
====

[[v43-11-26]]

^<<v43-11-26,26>>^ e todo aquele que vive e exerce fé em mim nunca jamais morrerá. Crês isso?”

[[v43-11-27]]

^<<v43-11-27,27>>^ Ela lhe disse: “Sim, Senhor; tenho crido que tu és o Cristo, o Filho de Deus, Aquele que vem ao mundo.”

[[v43-11-28]]

^<<v43-11-28,28>>^ E, dizendo isso, ela foi e chamou Maria, sua irmã, dizendo em secreto: “O Instrutor está presente e te chama.”

[[v43-11-29]]

^<<v43-11-29,29>>^ Esta última, quando ouviu isso, levantou-se depressa e foi ter com ele.

[[v43-11-30]]

^<<v43-11-30,30>>^ Jesus, de fato, ainda não tinha entrado na aldeia, mas estava ainda no lugar onde Marta o encontrara.

[[v43-11-31]]

^<<v43-11-31,31>>^ Portanto, os judeus que estavam com ela na casa e que a confortavam, vendo Maria levantar-se depressa e sair, seguiram-na, supondo que fosse ao túmulo memorial para ali chorar.

[[v43-11-32]]

^<<v43-11-32,32>>^ E Maria, chegando assim ao lugar onde Jesus estava e avistando-o, prostrou-se aos seus pés, dizendo-lhe: “Senhor, se tivesses estado aqui, meu irmão não teria morrido.”

[[v43-11-33]]

^<<v43-11-33,33>>^ Jesus, portanto, quando a viu chorar e [que] os judeus que vieram com ela choravam, gemeu no espírito e ficou aflito;

[[v43-11-34]]

^<<v43-11-34,34>>^ e disse: “Onde o deitastes?” Disseram-lhe: “Senhor, vem e vê.”

[[v43-11-35]]

^<<v43-11-35,35>>^ Jesus entregava-se ao choro.

[[v43-11-36]]

^<<v43-11-36,36>>^ Portanto, os judeus começaram a dizer: “Vede, quanta afeição tinha por ele!”

[[v43-11-37]]

^<<v43-11-37,37>>^ Mas alguns deles diziam: “Não podia este [homem], que abriu os olhos do cego, impedir que este aqui morresse?”

[[v43-11-38]]

^<<v43-11-38,38>>^ Por isso, Jesus, depois de gemer novamente no seu íntimo, foi ao túmulo memorial. Era, de fato, uma caverna e havia uma pedra encostada nela.

[[v43-11-39]]

^<<v43-11-39,39>>^ Jesus disse: “Retirai a pedra.” Marta, irmã do falecido, disse-lhe: “Senhor, ele já deve estar cheirando, porque já faz quatro dias.”

[[v43-11-40]]

^<<v43-11-40,40>>^ Jesus disse-lhe: “Não te disse eu que, se cresses, verias a glória de Deus?”

[[v43-11-41]]

^<<v43-11-41,41>>^ Portanto, retiraram a pedra. Jesus levantou então os olhos para o céu e disse: “Pai, eu te agradeço que me ouviste.

[[v43-11-42]]

^<<v43-11-42,42>>^ Deveras, eu sabia que sempre me ouves; mas falei por causa da multidão parada aqui, a fim de que creiam que tu me enviaste.”

[[v43-11-43]]

^<<v43-11-43,43>>^ E, ao ter dito estas coisas, clamou com voz alta: “Lázaro,^&#42;1^ vem para fora!”

[NOTE]
====
. Veja v. 1 n.
====

[[v43-11-44]]

^<<v43-11-44,44>>^ O [homem] que estivera morto saiu com os pés e as mãos amarrados com faixas, e o seu semblante enrolado num pano. Jesus disse-lhes: “Soltai-o e deixai-o ir.”

[[v43-11-45]]

^<<v43-11-45,45>>^ Portanto, muitos dos judeus, que tinham vindo a Maria e que observaram o que ele fez, depositaram fé nele;

[[v43-11-46]]

^<<v43-11-46,46>>^ mas alguns deles foram ter com os fariseus e lhes contaram as coisas que Jesus fez.

[[v43-11-47]]

^<<v43-11-47,47>>^ Conseqüentemente, os principais sacerdotes e os fariseus ajuntaram o Sinédrio e começaram a dizer: “Que devemos fazer, visto que este homem realiza muitos sinais?

[[v43-11-48]]

^<<v43-11-48,48>>^ Se o deixarmos assim, todos depositarão fé nele, e virão os romanos e tirarão tanto o nosso lugar^&#42;1^ como a nossa nação.”

[NOTE]
====
. Isto é, o templo.
====

[[v43-11-49]]

^<<v43-11-49,49>>^ Mas um certo deles, Caifás, que era sumo sacerdote naquele ano, disse-lhes: “Vós não sabeis nada

[[v43-11-50]]

^<<v43-11-50,50>>^ e não deduzis logicamente que é para o vosso proveito que um só homem morra a favor do povo e não que toda a nação seja destruída.”

[[v43-11-51]]

^<<v43-11-51,51>>^ Isto, porém, não dizia de sua própria iniciativa; mas, porque era sumo sacerdote naquele ano, profetizava que Jesus estava destinado a morrer pela nação,

[[v43-11-52]]

^<<v43-11-52,52>>^ e não só pela nação, mas, a fim de que os filhos de Deus, que se acham espalhados, fossem também por ele ajuntados numa unidade.

[[v43-11-53]]

^<<v43-11-53,53>>^ Portanto, daquele dia em diante deliberaram matá-lo.

[[v43-11-54]]

^<<v43-11-54,54>>^ Por isso, Jesus não andava mais publicamente entre os judeus, mas partiu dali para o país perto do ermo, para uma cidade chamada Efraim, e ali permaneceu com os discípulos.

[[v43-11-55]]

^<<v43-11-55,55>>^ Ora, estava próxima a páscoa dos judeus, e muitos do país subiam para Jerusalém antes da páscoa, a fim de se purificarem cerimonialmente.

[[v43-11-56]]

^<<v43-11-56,56>>^ Foram, portanto, procurar Jesus e diziam uns aos outros, ao estarem parados ociosos no templo: “Qual é a vossa opinião? Que ele não virá absolutamente à festividade?”

[[v43-11-57]]

^<<v43-11-57,57>>^ Acontece que os principais sacerdotes e os fariseus tinham dado ordens que, se alguém soubesse onde ele estava, devia denunciar [isso], a fim de que pudessem apoderar-se dele.

'''

xref:043-joao/043-joao-010.adoc#v43-10-0[&#60; Capítulo Anterior] | <<v43-11-0,Topo>> | xref:043-joao/043-joao-012.adoc#v43-12-0[Próximo Capítulo &#62;]