include::./index.adoc[]

[[v43-15-0]]
=== João, 15
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v43-15-1]]

^<<v43-15-1,1>>^ “Eu sou a verdadeira videira e meu Pai é o lavrador.

[[v43-15-2]]

^<<v43-15-2,2>>^ Todo ramo em mim que não dá fruto, ele tira, e todo o que dá fruto, ele limpa,^&#42;1^ para que dê mais fruto.

[NOTE]
====
. Ou “ele poda”.
====

[[v43-15-3]]

^<<v43-15-3,3>>^ Vós já estais limpos, por causa da palavra que vos falei.

[[v43-15-4]]

^<<v43-15-4,4>>^ Permanecei em união comigo, e eu em união convosco. Assim como o ramo não pode dar fruto de si mesmo, a menos que permaneça na videira, do mesmo modo tampouco vós podeis, a menos que permaneçais em união comigo.

[[v43-15-5]]

^<<v43-15-5,5>>^ Eu sou a videira, vós sois os ramos. Quem permanece em união comigo, e eu em união com ele, este dá muito fruto; porque separados de mim não podeis fazer^&#42;1^ nada.

[NOTE]
====
. Ou “produzir”.
====

[[v43-15-6]]

^<<v43-15-6,6>>^ Se alguém não permanece em união comigo, ele é lançado fora como ramo e seca-se; e homens ajuntam estes ramos e os jogam no fogo, e eles se queimam.

[[v43-15-7]]

^<<v43-15-7,7>>^ Se permanecerdes em união comigo e as minhas declarações permanecerem em vós, pedi o que quiserdes e ocorrerá para vós.

[[v43-15-8]]

^<<v43-15-8,8>>^ Nisto é glorificado o meu Pai, que persistais em dar muito fruto e vos mostreis meus discípulos.

[[v43-15-9]]

^<<v43-15-9,9>>^ Assim como o Pai me tem amado e eu vos tenho amado, permanecei no meu amor.

[[v43-15-10]]

^<<v43-15-10,10>>^ Se observardes os meus mandamentos, permanecereis no meu amor, assim como eu tenho observado os mandamentos do Pai e permaneço no seu amor.

[[v43-15-11]]

^<<v43-15-11,11>>^ “Estas coisas eu vos falei para que a minha alegria esteja em vós e a vossa alegria se torne plena.

[[v43-15-12]]

^<<v43-15-12,12>>^ Este é o meu mandamento, que vos ameis uns aos outros, assim como eu vos amei.

[[v43-15-13]]

^<<v43-15-13,13>>^ Ninguém tem maior amor do que este, que alguém entregue a sua alma^&#42;1^ a favor de seus amigos.

[NOTE]
====
. Ou “vida”.
====

[[v43-15-14]]

^<<v43-15-14,14>>^ Vós sois meus amigos, se fizerdes o que vos mando.

[[v43-15-15]]

^<<v43-15-15,15>>^ Não mais vos chamo de escravos, porque o escravo não sabe o que seu amo faz. Mas, eu vos chamei de amigos, porque todas as coisas que tenho ouvido do meu Pai vos tenho deixado saber.

[[v43-15-16]]

^<<v43-15-16,16>>^ Vós não me escolhestes, mas eu escolhi a vós, e eu vos designei para prosseguirdes e persistirdes em dar fruto, e que o vosso fruto permaneça; a fim de que, não importa o que pedirdes ao Pai em meu nome, ele vo-lo dê.

[[v43-15-17]]

^<<v43-15-17,17>>^ “Estas coisas eu vos mando, que vos ameis uns aos outros.

[[v43-15-18]]

^<<v43-15-18,18>>^ Se o mundo vos odeia, sabeis que me odiou antes de odiar a vós.

[[v43-15-19]]

^<<v43-15-19,19>>^ Se vós fizésseis parte do mundo, o mundo estaria afeiçoado ao que é seu. Agora, porque não fazeis parte do mundo, mas eu vos escolhi do mundo, por esta razão o mundo vos odeia.

[[v43-15-20]]

^<<v43-15-20,20>>^ Lembrai-vos da palavra que eu vos disse: O escravo não é maior do que o seu amo. Se me perseguiram a mim, perseguirão também a vós; se observaram a minha palavra, observarão também a vossa.

[[v43-15-21]]

^<<v43-15-21,21>>^ Mas, farão todas estas coisas contra vós por causa do meu nome, porque não conhecem aquele que me enviou.

[[v43-15-22]]

^<<v43-15-22,22>>^ Se eu não tivesse vindo e falado com eles, não teriam pecado; mas agora não têm desculpa para o seu pecado.

[[v43-15-23]]

^<<v43-15-23,23>>^ Quem me odeia, odeia também o meu Pai.

[[v43-15-24]]

^<<v43-15-24,24>>^ Se eu não tivesse feito entre eles as obras que ninguém mais fez, não teriam pecado; mas agora eles têm visto e têm odiado tanto a mim como a meu Pai.

[[v43-15-25]]

^<<v43-15-25,25>>^ Mas, é para que se cumpra a palavra escrita na Lei deles: ‘Odiaram-me sem causa.’

[[v43-15-26]]

^<<v43-15-26,26>>^ Quando chegar o ajudador^&#42;1^ que eu vos enviarei do Pai, o espírito da verdade, que procede do Pai, esse^&#42;2^ dará testemunho de mim;

[NOTE]
====
. Ou “o paracleto (consolador)”. Gr.: ho pa·rá·kle·tos, masc.
. “Esse”, gr. masc., referindo-se ao “ajudador”, gr. masc. Veja 16:7.
====

[[v43-15-27]]

^<<v43-15-27,27>>^ e vós, igualmente, haveis de dar testemunho, porque estivestes comigo desde que comecei.

'''

xref:043-joao/043-joao-014.adoc#v43-14-0[&#60; Capítulo Anterior] | <<v43-15-0,Topo>> | xref:043-joao/043-joao-016.adoc#v43-16-0[Próximo Capítulo &#62;]