include::./index.adoc[]

[[v43-3-0]]
=== João, 3
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v43-3-1]]

^<<v43-3-1,1>>^ Ora, havia um homem dos fariseus, cujo nome era Nicodemos, um governante dos judeus.

[[v43-3-2]]

^<<v43-3-2,2>>^ Este veio a ele de noite e disse-lhe: “Rabi, sabemos que tu, como instrutor, tens vindo de Deus; pois, ninguém pode realizar esses sinais que tu realizas, a menos que Deus esteja com ele.”

[[v43-3-3]]

^<<v43-3-3,3>>^ Em resposta, Jesus disse-lhe: “Digo-te em toda a verdade: A menos que alguém nasça de novo,^&#42;1^ não pode ver o reino de Deus.”

[NOTE]
====
. “Nasça de novo.” Lit.: “seja gerado de cima”. Gr.: gen·ne·theí á·no·then.
====

[[v43-3-4]]

^<<v43-3-4,4>>^ Nicodemos disse-lhe: “Como pode um homem nascer, sendo velho? Será que pode entrar pela segunda vez na madre de sua mãe e nascer?”

[[v43-3-5]]

^<<v43-3-5,5>>^ Jesus respondeu: “Eu te digo em toda a verdade: A menos que alguém nasça de água e espírito,^&#42;1^ não pode entrar no reino de Deus.

[NOTE]
====
. Ou “força ativa”. Gr.: pneú·ma·tos; lat.: Spí·ri·tu; J17,22(hebr.): weha·rú·ahh, “e a força ativa”. Veja Gên 1:2 n.: “ativa”.
====

[[v43-3-6]]

^<<v43-3-6,6>>^ O que tem nascido da carne é carne, e o que tem nascido do espírito é espírito.

[[v43-3-7]]

^<<v43-3-7,7>>^ Não te maravilhes por eu te dizer: Vós tendes de nascer de novo.

[[v43-3-8]]

^<<v43-3-8,8>>^ O vento^&#42;1^ sopra para onde quer, e ouves o som dele, mas não sabes donde vem e para onde vai. Assim é todo aquele que tem nascido do espírito.”

[NOTE]
====
. “Vento.” Gr.: pneú·ma.
====

[[v43-3-9]]

^<<v43-3-9,9>>^ Nicodemos disse-lhe, em resposta: “Como podem suceder estas coisas?”

[[v43-3-10]]

^<<v43-3-10,10>>^ Em resposta, Jesus disse-lhe: “És tu instrutor de Israel e ainda assim não sabes estas coisas?

[[v43-3-11]]

^<<v43-3-11,11>>^ Digo-te em toda a verdade: O que sabemos, falamos, e o que temos visto, disso damos testemunho, mas vós não recebeis o testemunho que damos.

[[v43-3-12]]

^<<v43-3-12,12>>^ Se eu vos disse coisas terrenas e ainda assim não credes, como crereis se eu vos disser coisas celestiais?^&#42;1^

[NOTE]
====
. “Coisas celestiais.” Gr.: e·pou·rá·ni·a; lat.: cae·lé·sti·a, “coisas celestes”.
====

[[v43-3-13]]

^<<v43-3-13,13>>^ Ademais, nenhum homem ascendeu ao céu, senão aquele que desceu do céu, o Filho do homem.

[[v43-3-14]]

^<<v43-3-14,14>>^ E assim como Moisés ergueu a serpente no ermo, assim tem de ser erguido o Filho do homem,

[[v43-3-15]]

^<<v43-3-15,15>>^ para que todo o que nele crer tenha vida eterna.

[[v43-3-16]]

^<<v43-3-16,16>>^ “Porque Deus amou tanto o mundo,^&#42;1^ que deu o seu Filho unigênito, a fim de que todo aquele que nele exercer fé não seja destruído, mas tenha vida eterna.

[NOTE]
====
. “O mundo.” Gr.: ton kó·smon; lat.: mún·dum; J17,18,22(hebr.): ha·‛oh·lám.
====

[[v43-3-17]]

^<<v43-3-17,17>>^ Pois, Deus enviou seu Filho ao mundo, não para julgar o mundo, mas para que o mundo fosse salvo por intermédio dele.

[[v43-3-18]]

^<<v43-3-18,18>>^ Quem nele exercer fé, não há de ser julgado. Quem não exercer fé, já foi julgado porque não exerceu fé no nome do Filho unigênito de Deus.

[[v43-3-19]]

^<<v43-3-19,19>>^ Agora, esta é a base para o julgamento: que a luz veio ao mundo, mas os homens amaram mais a escuridão do que a luz, porque as suas obras eram iníquas.

[[v43-3-20]]

^<<v43-3-20,20>>^ Pois quem pratica coisas ruins odeia a luz e não se chega à luz, a fim de que as suas obras não sejam repreendidas.

[[v43-3-21]]

^<<v43-3-21,21>>^ Mas, quem faz o que é verdadeiro se chega à luz, a fim de que as suas obras sejam manifestas como tendo sido feitas em harmonia com Deus.”

[[v43-3-22]]

^<<v43-3-22,22>>^ Depois dessas coisas, Jesus e seus discípulos foram para o país da Judéia, e ali passou algum tempo com eles e batizava.

[[v43-3-23]]

^<<v43-3-23,23>>^ Mas, João também estava batizando em Enom, perto de Salim, porque havia ali uma grande quantidade de água e as pessoas vinham e eram batizadas;

[[v43-3-24]]

^<<v43-3-24,24>>^ pois, João ainda não tinha sido lançado na prisão.

[[v43-3-25]]

^<<v43-3-25,25>>^ Surgiu assim da parte dos discípulos de João uma disputa com um judeu, a respeito da purificação.

[[v43-3-26]]

^<<v43-3-26,26>>^ Vieram assim a João e disseram-lhe: “Rabi, o homem que estava contigo do outro lado do Jordão, de quem deste testemunho, eis que este está batizando e todos vão a ele.”

[[v43-3-27]]

^<<v43-3-27,27>>^ Em resposta, João disse: “O homem não pode receber nem uma única coisa a menos que lhe seja dada do céu.

[[v43-3-28]]

^<<v43-3-28,28>>^ Vós mesmos me dais testemunho de que eu disse: Eu não sou o Cristo, mas, fui enviado na frente deste.

[[v43-3-29]]

^<<v43-3-29,29>>^ Quem tem a noiva é o noivo. No entanto, o amigo do noivo, estando em pé e ouvindo-o, tem muita alegria por causa da voz do noivo. Esta alegria minha, por isso, ficou completa.

[[v43-3-30]]

^<<v43-3-30,30>>^ Este tem de estar aumentando, mas eu tenho de estar diminuindo.”

[[v43-3-31]]

^<<v43-3-31,31>>^ Aquele que vem de cima é sobre todos os outros.^&#42;1^ Quem é da terra é da terra e fala as coisas da terra. Aquele que vem do céu é sobre todos os outros.

[NOTE]
====
. Ou “todas as coisas”.
====

[[v43-3-32]]

^<<v43-3-32,32>>^ O que ele tem visto e ouvido, disso dá testemunho, mas nenhum homem está aceitando o seu testemunho.

[[v43-3-33]]

^<<v43-3-33,33>>^ Quem tem aceito o seu testemunho, tem posto neste o seu selo, de que Deus é verdadeiro.

[[v43-3-34]]

^<<v43-3-34,34>>^ Pois aquele a quem Deus enviou fala as declarações de Deus, porque ele não dá o espírito por medida.^&#42;1^

[NOTE]
====
. Ou “parcamente”.
====

[[v43-3-35]]

^<<v43-3-35,35>>^ O Pai ama o Filho e tem entregue todas as coisas na sua mão.

[[v43-3-36]]

^<<v43-3-36,36>>^ Quem exerce fé no Filho tem vida eterna; quem desobedece ao Filho não verá a vida, mas o furor de Deus permanece sobre ele.

'''

xref:043-joao/043-joao-002.adoc#v43-2-0[&#60; Capítulo Anterior] | <<v43-3-0,Topo>> | xref:043-joao/043-joao-004.adoc#v43-4-0[Próximo Capítulo &#62;]