include::./index.adoc[]

[[v43-4-0]]
=== João, 4
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v43-4-1]]

^<<v43-4-1,1>>^ Então, quando o Senhor^&#42;1^ se apercebeu de que os fariseus tinham ouvido [falar] que Jesus fazia e batizava mais discípulos do que João —

[NOTE]
====
. Ou “Amo”.
====

[[v43-4-2]]

^<<v43-4-2,2>>^ embora, deveras, o próprio Jesus não batizasse, mas sim os seus discípulos —

[[v43-4-3]]

^<<v43-4-3,3>>^ abandonou a Judéia e partiu novamente para a Galiléia.

[[v43-4-4]]

^<<v43-4-4,4>>^ Mas, era necessário que passasse por Samaria.

[[v43-4-5]]

^<<v43-4-5,5>>^ Concordemente, veio a uma cidade de Samaria, chamada Sicar,^&#42;1^ perto do campo que Jacó dera a José, seu filho.

[NOTE]
====
. “Sychem (Siquém)”, Sys. Veja At 7:16 n.: “Siquém”.
====

[[v43-4-6]]

^<<v43-4-6,6>>^ De fato, ali se achava a fonte de Jacó. Ora, Jesus, cansado da jornada, estava sentado junto à fonte, assim como estava. Era cerca da sexta hora.^&#42;1^

[NOTE]
====
. Isto é, por volta do meio-dia, contada desde o nascer do sol.
====

[[v43-4-7]]

^<<v43-4-7,7>>^ Veio uma mulher de Samaria para tirar água. Jesus disse-lhe: “Dá-me de beber.”

[[v43-4-8]]

^<<v43-4-8,8>>^ (Pois os seus discípulos tinham ido à cidade para comprar comestíveis.)

[[v43-4-9]]

^<<v43-4-9,9>>^ Portanto, a mulher samaritana disse-lhe: “Como é que tu, apesar de ser judeu, me pedes de beber, quando eu sou mulher samaritana?” (Porque os judeus não têm tratos com os samaritanos.)^&#42;1^

[NOTE]
====
. “Porque os judeus . . . samaritanos”, ABCWVgSyp,s; א°DItmss. omitem isso.
====

[[v43-4-10]]

^<<v43-4-10,10>>^ Em resposta, Jesus disse-lhe: “Se tivesses sabido da dádiva gratuita de Deus e quem é que te diz: ‘Dá-me de beber’, tu lhe terias pedido e ele te teria dado água viva.”

[[v43-4-11]]

^<<v43-4-11,11>>^ Ela lhe disse: “Senhor, não tens nem mesmo um balde para tirar água, e o poço é profundo. Donde tens então esta água viva?

[[v43-4-12]]

^<<v43-4-12,12>>^ Será que és maior do que o nosso antepassado Jacó, que nos deu o poço e que bebeu dele junto com os seus filhos e seu gado?”

[[v43-4-13]]

^<<v43-4-13,13>>^ Em resposta, Jesus disse-lhe: “Todo aquele que beber desta água ficará novamente com sede.

[[v43-4-14]]

^<<v43-4-14,14>>^ Quem beber da água que eu lhe der, nunca mais ficará com sede, mas a água que eu lhe der se tornará nele uma fonte de água que borbulha para dar vida eterna.”

[[v43-4-15]]

^<<v43-4-15,15>>^ A mulher disse-lhe: “Senhor, dá-me desta água, para que eu não tenha sede nem venha mais para este lugar a fim de tirar água.”

[[v43-4-16]]

^<<v43-4-16,16>>^ Disse-lhe ele: “Vai, chama teu marido e vem para este lugar.”

[[v43-4-17]]

^<<v43-4-17,17>>^ Em resposta, a mulher disse: “Não tenho marido.” Jesus disse-lhe: “Disseste bem: ‘Não tenho marido.’

[[v43-4-18]]

^<<v43-4-18,18>>^ Pois, tiveste cinco maridos, e o [homem] que agora tens não é teu marido. Isso disseste verazmente.”

[[v43-4-19]]

^<<v43-4-19,19>>^ A mulher disse-lhe: “Senhor, percebo que és um profeta.

[[v43-4-20]]

^<<v43-4-20,20>>^ Nossos antepassados adoravam neste monte; mas vós dizeis que o lugar onde as pessoas devem adorar é em Jerusalém.”

[[v43-4-21]]

^<<v43-4-21,21>>^ Jesus disse-lhe: “Acredita-me, mulher: Vem a hora em que nem neste monte, nem em Jerusalém, adorareis o Pai.

[[v43-4-22]]

^<<v43-4-22,22>>^ Adorais o que não conheceis; nós adoramos o que conhecemos, porque a salvação se origina dos judeus.

[[v43-4-23]]

^<<v43-4-23,23>>^ Não obstante, vem a hora, e agora é, quando os verdadeiros adoradores adorarão o Pai com espírito e verdade, pois, deveras, o Pai está procurando a tais para o adorarem.

[[v43-4-24]]

^<<v43-4-24,24>>^ Deus é Espírito,^&#42;1^ e os que o adoram têm de adorá-lo com espírito e verdade.”

[NOTE]
====
. Lit.: “Espírito [é] o Deus.” Gr.: Pneú·ma ho The·ós.
====

[[v43-4-25]]

^<<v43-4-25,25>>^ A mulher disse-lhe: “Eu sei que vem [o] Messias, que é chamado Cristo. Quando este chegar, ele nos declarará abertamente todas as coisas.”

[[v43-4-26]]

^<<v43-4-26,26>>^ Jesus disse-lhe: “Eu, que falo contigo, sou ele.”

[[v43-4-27]]

^<<v43-4-27,27>>^ Ora, foi neste ponto que chegaram os seus discípulos, e eles começaram a admirar-se, porque falava com uma mulher. Naturalmente, ninguém disse: “O que estás procurando?” ou: “Por que falas com ela?”

[[v43-4-28]]

^<<v43-4-28,28>>^ A mulher, portanto, deixou o seu cântaro e foi à cidade, e disse aos homens:

[[v43-4-29]]

^<<v43-4-29,29>>^ “Vinde, vede um homem que me disse todas as coisas que eu fiz. Será que este é o Cristo?”

[[v43-4-30]]

^<<v43-4-30,30>>^ Saíram da cidade e começaram a chegar-se a ele.

[[v43-4-31]]

^<<v43-4-31,31>>^ Entrementes, os discípulos instavam com ele, dizendo: “Rabi, come.”

[[v43-4-32]]

^<<v43-4-32,32>>^ Mas ele lhes disse: “Tenho alimento para comer de que vós não sabeis.”

[[v43-4-33]]

^<<v43-4-33,33>>^ Os discípulos começaram assim a dizer uns aos outros: “Será que alguém lhe trouxe algo para comer?”

[[v43-4-34]]

^<<v43-4-34,34>>^ Jesus disse-lhes: “Meu alimento é eu fazer a vontade daquele que me enviou e terminar a sua obra.

[[v43-4-35]]

^<<v43-4-35,35>>^ Não dizeis que ainda faltam quatro meses até chegar a colheita? Eis que vos digo: Erguei os vossos olhos e observai os campos, que estão brancos para a colheita. Desde já

[[v43-4-36]]

^<<v43-4-36,36>>^ o ceifeiro está recebendo salário e está ajuntando fruto para a vida eterna, para que o semeador e o ceifeiro se alegrem juntos.

[[v43-4-37]]

^<<v43-4-37,37>>^ Neste respeito, de fato, é verdadeira a palavra: Um é o semeador e outro o ceifador.

[[v43-4-38]]

^<<v43-4-38,38>>^ Eu vos mandei ceifar aquilo em que não labutastes. Outros labutaram, e vós entrastes no proveito do seu labor.”

[[v43-4-39]]

^<<v43-4-39,39>>^ Ora, muitos samaritanos daquela cidade depositaram nele fé por causa da palavra da mulher que dissera em testemunho: “Ele me disse todas as coisas que fiz.”

[[v43-4-40]]

^<<v43-4-40,40>>^ Portanto, chegando-se a ele os samaritanos, começaram a pedir-lhe que ficasse com eles; e ficou ali dois dias.

[[v43-4-41]]

^<<v43-4-41,41>>^ Em conseqüência disso, muitos mais creram por causa do que dizia,

[[v43-4-42]]

^<<v43-4-42,42>>^ e começaram a dizer à mulher: “Não é mais pela tua conversa que cremos; porque nós mesmos temos ouvido e sabemos que este homem certamente é o salvador do mundo.”

[[v43-4-43]]

^<<v43-4-43,43>>^ Depois desses dois dias, partiu dali para a Galiléia.

[[v43-4-44]]

^<<v43-4-44,44>>^ O próprio Jesus, porém, dava testemunho de que um profeta não tem honra na sua própria pátria.

[[v43-4-45]]

^<<v43-4-45,45>>^ Portanto, ao chegar à Galiléia, os galileus receberam-no porque tinham visto todas as coisas que ele fizera em Jerusalém, na festividade, pois eles também tinham ido à festividade.

[[v43-4-46]]

^<<v43-4-46,46>>^ Por conseguinte, ele veio novamente à Caná da Galiléia, onde transformara a água em vinho. Havia então ali certo assistente do rei, cujo filho estava doente em Cafarnaum.

[[v43-4-47]]

^<<v43-4-47,47>>^ Quando este homem ouviu que Jesus saíra da Judéia para a Galiléia, foi ter com ele e começou a pedir-lhe que descesse e sarasse seu filho, pois estava às portas da morte.

[[v43-4-48]]

^<<v43-4-48,48>>^ Jesus, porém, disse-lhe: “A menos que vós vejais sinais e prodígios, de modo algum acreditareis.”

[[v43-4-49]]

^<<v43-4-49,49>>^ O assistente do rei disse-lhe: “Senhor,^&#42;1^ desce antes de minha criancinha morrer.”

[NOTE]
====
. Ou “Amo”.
====

[[v43-4-50]]

^<<v43-4-50,50>>^ Jesus disse-lhe: “Vai; teu filho vive.” O homem acreditou na palavra que Jesus lhe falou e foi embora.

[[v43-4-51]]

^<<v43-4-51,51>>^ Mas, enquanto ainda estava descendo, vieram ao encontro dele seus escravos para dizer que seu menino estava vivo.

[[v43-4-52]]

^<<v43-4-52,52>>^ Começou assim a indagar deles a hora em que ficou melhor de saúde. Concordemente lhe disseram: “Ontem, na sétima hora,^&#42;1^ a febre o abandonou.”

[NOTE]
====
. Isto é, por volta das 13 horas, contada desde o nascer do sol.
====

[[v43-4-53]]

^<<v43-4-53,53>>^ Portanto, o pai sabia que fora naquela mesma hora que Jesus lhe dissera: “Teu filho vive.” E ele e toda a sua família creram.

[[v43-4-54]]

^<<v43-4-54,54>>^ Demais, este foi o segundo sinal que Jesus realizou depois de sair da Judéia para a Galiléia.

'''

xref:043-joao/043-joao-003.adoc#v43-3-0[&#60; Capítulo Anterior] | <<v43-4-0,Topo>> | xref:043-joao/043-joao-005.adoc#v43-5-0[Próximo Capítulo &#62;]