include::./index.adoc[]

[[v43-21-0]]
=== João, 21
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v43-21-1]]

^<<v43-21-1,1>>^ Depois destas coisas, Jesus manifestou-se novamente aos discípulos junto do mar de Tiberíades; mas, fez a manifestação do seguinte modo.

[[v43-21-2]]

^<<v43-21-2,2>>^ Estavam juntos Simão Pedro, e Tomé, que era chamado O Gêmeo, e Natanael, de Caná da Galiléia, e os filhos de Zebedeu, e mais dois dos seus discípulos.

[[v43-21-3]]

^<<v43-21-3,3>>^ Simão Pedro disse-lhes: “Vou pescar.” Disseram-lhe: “Nós também vamos contigo.” Foram assim e entraram no barco, mas, durante aquela noite não apanharam nada.

[[v43-21-4]]

^<<v43-21-4,4>>^ No entanto, quando estava amanhecendo, Jesus estava parado na praia, mas os discípulos, naturalmente, não discerniam que era Jesus.

[[v43-21-5]]

^<<v43-21-5,5>>^ Jesus disse-lhes então: “Criancinhas, será que tendes algo para comer?” Responderam-lhe: “Não.”

[[v43-21-6]]

^<<v43-21-6,6>>^ Disse-lhes ele: “Lançai a rede do lado direito do barco e achareis [algo].” Lançaram-na então, mas não puderam mais recolhê-la por causa da multidão de peixes.

[[v43-21-7]]

^<<v43-21-7,7>>^ Portanto, aquele discípulo a quem Jesus amava^&#42;1^ disse a Pedro: “É o Senhor!”^&#42;2^ Por isso, Simão Pedro, ouvindo que era o Senhor, cingiu-se de sua roupa de cima, pois estava nu, e lançou-se no mar.

[NOTE]
====
. Ou “preferia”.
. Ou “o Amo”.
====

[[v43-21-8]]

^<<v43-21-8,8>>^ Mas os outros discípulos vieram no pequeno barco, pois não estavam longe da terra, apenas a cerca de noventa metros,^&#42;1^ arrastando a rede de peixes.

[NOTE]
====
. Lit.: “a cerca de duzentos côvados”. Veja Ap. 8A.
====

[[v43-21-9]]

^<<v43-21-9,9>>^ No entanto, quando desembarcaram em terra, observaram ali um fogo de brasas e peixe deitado nele, e pão.

[[v43-21-10]]

^<<v43-21-10,10>>^ Jesus disse-lhes: “Trazei alguns dos peixes que acabais de apanhar.”

[[v43-21-11]]

^<<v43-21-11,11>>^ Simão Pedro, portanto, subiu a bordo e puxou a rede para terra, cheia de grandes peixes, cento e cinqüenta e três deles. Mas, embora houvesse tantos, a rede não se rompeu.

[[v43-21-12]]

^<<v43-21-12,12>>^ Jesus disse-lhes: “Vinde, tomai o vosso primeiro almoço.” Nenhum dos discípulos tinha a coragem de indagar-lhe: “Quem és?” porque sabiam que era o Senhor.

[[v43-21-13]]

^<<v43-21-13,13>>^ Jesus veio e tomou o pão, e deu-o a eles, e assim também o peixe.

[[v43-21-14]]

^<<v43-21-14,14>>^ Esta foi então a terceira vez que Jesus apareceu aos discípulos depois de ter sido levantado dentre os mortos.

[[v43-21-15]]

^<<v43-21-15,15>>^ Então, depois de terem almoçado, Jesus disse a Simão Pedro: “Simão, filho de João,^&#42;1^ amas-me^&#42;2^ mais do que estes?” Ele lhe disse: “Sim, Senhor, tu sabes que tenho afeição por ti.”^&#42;3^ Disse-lhe ele: “Apascenta meus cordeiros.”

[NOTE]
====
. “João”, BVg; ASyp,s: “Jona”. Veja 1:42 n.: “João”.
. “Amas-me.” Gr.: a·ga·país.
. “Tenho afeição por ti.” Gr.: fi·ló se.
====

[[v43-21-16]]

^<<v43-21-16,16>>^ Novamente lhe disse ele, pela segunda vez: “Simão, filho de João, amas-me?”^&#42;1^ Ele lhe disse: “Sim, Senhor, tu sabes que tenho afeição por ti.”^&#42;2^ Disse-lhe ele: “Pastoreia minhas ovelhinhas.”

[NOTE]
====
. “Amas-me?” Gr.: a·ga·país.
. “Tenho afeição por ti.” Gr.: fi·ló se.
====

[[v43-21-17]]

^<<v43-21-17,17>>^ Disse-lhe ele pela terceira vez: “Simão, filho de João, tens afeição por mim?”^&#42;1^ Pedro ficou contristado por ele lhe dizer pela terceira vez: “Tens afeição por mim?” De modo que lhe disse: “Senhor, tu sabes todas as coisas; tu te apercebes que eu tenho afeição por ti.”^&#42;2^ Jesus disse-lhe: “Apascenta as minhas ovelhinhas.

[NOTE]
====
. “Tens afeição por mim?” Gr.: fi·leís me.
. “Eu tenho afeição por ti.” Gr.: fi·ló se.
====

[[v43-21-18]]

^<<v43-21-18,18>>^ Eu te digo em toda a verdade: Quando eras mais jovem, costumavas cingir-te e andar onde querias. Mas, quando ficares velho, estenderás as tuas mãos e outro [homem] te cingirá e te levará para onde não queres.”

[[v43-21-19]]

^<<v43-21-19,19>>^ Isto ele disse para indicar por que sorte de morte havia de glorificar a Deus. Assim, depois de dizer isso, disse-lhe: “Continua a seguir-me.”

[[v43-21-20]]

^<<v43-21-20,20>>^ Voltando-se, Pedro viu seguindo o discípulo a quem Jesus havia amado,^&#42;1^ aquele que na refeição noturna também se encostara no peito dele e dissera: “Senhor, quem é que te trai?”

[NOTE]
====
. Ou “preferido”.
====

[[v43-21-21]]

^<<v43-21-21,21>>^ Concordemente, quando o avistou, Pedro disse a Jesus: “Senhor, este [homem fará] o quê?”

[[v43-21-22]]

^<<v43-21-22,22>>^ Jesus disse-lhe: “Se for a minha vontade que ele permaneça até eu vir, de que preocupação é isso para ti? Continua tu a seguir-me.”

[[v43-21-23]]

^<<v43-21-23,23>>^ Em conseqüência, difundia-se esta palavra entre os irmãos, que esse discípulo não ia morrer. No entanto, Jesus não lhe disse que não ia morrer, mas: “Se for a minha vontade que ele permaneça até eu vir, de que preocupação é isso para ti?”

[[v43-21-24]]

^<<v43-21-24,24>>^ Este é o discípulo que dá testemunho destas coisas e que escreveu estas coisas, e nós sabemos que o testemunho que ele dá é verdadeiro.

[[v43-21-25]]

^<<v43-21-25,25>>^ Há, de fato, também muitas outras coisas que Jesus fez, as quais, se alguma vez fossem escritas em todos os pormenores, suponho que o próprio mundo não poderia conter os rolos escritos.^&#42;1^

[NOTE]
====
. O v. 25 consta em אcABCVgSyp,s; א° omite isso.
====

'''

xref:043-joao/043-joao-020.adoc#v43-20-0[&#60; Capítulo Anterior] | <<v43-21-0,Topo>> | xref:044-atos/044-atos-001.adoc#v44-1-0[Próximo Capítulo &#62;]