include::./index.adoc[]

[[v43-16-0]]
=== João, 16
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v43-16-1]]

^<<v43-16-1,1>>^ “Tenho falado estas coisas para que não tropeceis.

[[v43-16-2]]

^<<v43-16-2,2>>^ [Os] homens vos expulsarão da sinagoga.^&#42;1^ De fato, vem a hora em que todo aquele que vos matar imaginará que tem prestado um serviço sagrado^&#42;2^ a Deus.

[NOTE]
====
. Veja 9:22 n.
. “Um serviço sagrado.” Gr.: la·treí·an. Veja Êx 12:25 n.
====

[[v43-16-3]]

^<<v43-16-3,3>>^ Mas, farão estas coisas porque não vieram a conhecer nem o Pai nem a mim.

[[v43-16-4]]

^<<v43-16-4,4>>^ Não obstante, tenho-vos falado estas coisas para que, quando chegar a hora delas, vos lembreis de que vos falei delas.
“Estas coisas, porém, eu não vos disse no princípio, porque eu estava convosco.

[[v43-16-5]]

^<<v43-16-5,5>>^ Mas agora vou para aquele que me enviou, e, ainda assim, nem um só de vós me pergunta: ‘Para onde vais?’

[[v43-16-6]]

^<<v43-16-6,6>>^ Mas, porque vos falei estas coisas, vossos corações estão cheios de pesar.

[[v43-16-7]]

^<<v43-16-7,7>>^ Não obstante, eu vos digo a verdade: É para o vosso proveito que vou embora. Pois, se eu não for embora, de modo algum virá a vós o ajudador;^&#42;1^ mas, se eu for embora, vo-lo enviarei.

[NOTE]
====
. Ou “o paracleto (consolador)”. Gr.: ho pa·rá·kle·tos, masc.
====

[[v43-16-8]]

^<<v43-16-8,8>>^ E, quando este chegar, dará ao mundo evidência convincente^&#42;1^ a respeito do pecado, e a respeito da justiça, e a respeito do julgamento:

[NOTE]
====
. “Dará . . . evidência convincente.” Ou “repreenderá”. Gr.: e·lég·xei.
====

[[v43-16-9]]

^<<v43-16-9,9>>^ em primeiro lugar, a respeito do pecado, porque não exercem fé em mim;

[[v43-16-10]]

^<<v43-16-10,10>>^ daí, a respeito da justiça, porque vou para o Pai e não me observareis mais;

[[v43-16-11]]

^<<v43-16-11,11>>^ então a respeito do julgamento, porque o governante deste mundo tem sido julgado.

[[v43-16-12]]

^<<v43-16-12,12>>^ “Ainda tenho muitas coisas para vos dizer, mas não sois atualmente capazes de suportá-las.

[[v43-16-13]]

^<<v43-16-13,13>>^ No entanto, quando esse^&#42;1^ chegar, o espírito da verdade, ele vos guiará a toda a verdade, pois não falará de seu próprio impulso, mas falará as coisas que ouvir e vos declarará as coisas vindouras.

[NOTE]
====
. “Esse”, referindo-se a “o ajudador” no v. 7.
====

[[v43-16-14]]

^<<v43-16-14,14>>^ Esse me glorificará, porque receberá do que é meu e vo[-lo] declarará.

[[v43-16-15]]

^<<v43-16-15,15>>^ Todas as coisas que meu Pai tem são minhas. É por isso que eu disse que recebe do que é meu e [o] declara a vós.

[[v43-16-16]]

^<<v43-16-16,16>>^ Dentro em pouco não me observareis mais, e, novamente, dentro em pouco me vereis.”

[[v43-16-17]]

^<<v43-16-17,17>>^ Portanto, alguns dos seus discípulos disseram um ao outro: “Que significa isto que ele nos diz: ‘Dentro em pouco não me observareis, e novamente, dentro em pouco me vereis’, e, ‘porque eu vou para o Pai’?”

[[v43-16-18]]

^<<v43-16-18,18>>^ Por isso diziam: “Que significa isto que ele diz: ‘dentro em pouco’? Não sabemos de que está falando.”^&#42;1^

[NOTE]
====
. “De que está falando.” B omite isso.
====

[[v43-16-19]]

^<<v43-16-19,19>>^ Jesus sabia que queriam interrogá-lo, de modo que lhes disse: “Estais indagando entre vós mesmos sobre isso, porque eu disse: Dentro em pouco não me observareis, e novamente, dentro em pouco me vereis?

[[v43-16-20]]

^<<v43-16-20,20>>^ Digo-vos em toda a verdade: Chorareis e lamentareis, mas o mundo se alegrará; vós sereis contristados, mas o vosso pesar será transformado em alegria.

[[v43-16-21]]

^<<v43-16-21,21>>^ Uma mulher, quando dá à luz, tem pesar, porque chegou a sua hora; mas, quando ela deu à luz a criancinha, não se lembra mais da tribulação, por causa da alegria de que um homem tem nascido no mundo.

[[v43-16-22]]

^<<v43-16-22,22>>^ Portanto, vós também, deveras, tendes agora pesar; mas, hei de ver-vos novamente e os vossos corações se alegrarão, e ninguém vos tirará a vossa alegria.

[[v43-16-23]]

^<<v43-16-23,23>>^ E naquele dia não me fareis absolutamente nenhuma pergunta. Eu vos digo em toda a verdade: Se pedirdes ao Pai qualquer coisa, ele vo-la dará em meu nome.

[[v43-16-24]]

^<<v43-16-24,24>>^ Até o momento não pedistes nem uma única coisa em meu nome. Pedi e recebereis, para que a vossa alegria seja plena.

[[v43-16-25]]

^<<v43-16-25,25>>^ “Eu vos falei estas coisas em comparações. Vem a hora em que não vos falarei mais em comparações, mas eu vos relatarei com clareza a respeito do Pai.

[[v43-16-26]]

^<<v43-16-26,26>>^ Naquele dia pedireis em meu nome, e não vos digo que hei de fazer solicitação ao meu Pai a respeito de vós.

[[v43-16-27]]

^<<v43-16-27,27>>^ Pois o próprio Pai tem afeição por vós, porque tivestes afeição por mim e acreditastes que saí como representante do Pai.

[[v43-16-28]]

^<<v43-16-28,28>>^ Saí da parte do Pai e vim ao mundo. Outrossim, deixo o mundo e vou embora para o Pai.”

[[v43-16-29]]

^<<v43-16-29,29>>^ Seus discípulos disseram: “Eis que agora falas com clareza e não proferes nenhuma comparação.

[[v43-16-30]]

^<<v43-16-30,30>>^ Agora sabemos que sabes todas as coisas e que não necessitas de que alguém te interrogue. Por meio disso cremos que saíste da parte de Deus.”

[[v43-16-31]]

^<<v43-16-31,31>>^ Jesus respondeu-lhes: “Credes atualmente?

[[v43-16-32]]

^<<v43-16-32,32>>^ Eis que vem a hora, deveras, já veio, em que sereis espalhados cada um para a sua própria casa e me deixareis sozinho; e, contudo, não estou sozinho, porque o Pai está comigo.

[[v43-16-33]]

^<<v43-16-33,33>>^ Eu vos disse estas coisas para que, por meio de mim,^&#42;1^ tenhais paz. No mundo tereis tribulação, mas, coragem! eu venci o mundo.”

[NOTE]
====
. Ou “em união comigo”. Gr.: en e·moí. Veja 6:56 n.
====

'''

xref:043-joao/043-joao-015.adoc#v43-15-0[&#60; Capítulo Anterior] | <<v43-16-0,Topo>> | xref:043-joao/043-joao-017.adoc#v43-17-0[Próximo Capítulo &#62;]