include::./index.adoc[]

[[v32-2-0]]
=== Jonas, 2
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v32-2-1]]

^<<v32-2-1,1>>^ Então Jonas orou a Jeová, seu Deus,^&#42;1^ desde as entranhas do peixe

[NOTE]
====
. “Seu Deus.” Hebr.: ’Elo·háv.
====

[[v32-2-2]]

^<<v32-2-2,2>>^ e disse:
“Na minha aflição clamei a Jeová e ele passou a responder-me.
Do ventre do Seol^&#42;1^ clamei por ajuda.
Ouviste a minha voz.

[NOTE]
====
. “Seol.” Hebr.: she’óhl; gr: haí·dou; lat.: in·fér·ni. Veja Ap. 4B.
====

[[v32-2-3]]

^<<v32-2-3,3>>^ Quando me lançaste nas profundezas, no coração do alto-mar,
Então me cercou um verdadeiro rio.
Todas as tuas ondas de rebentação e tuas vagas — sobre mim é que passaram.

[[v32-2-4]]

^<<v32-2-4,4>>^ E quanto a mim, eu disse: ‘Fui expulso de diante dos teus olhos!
Como é que olharei^&#42;1^ novamente para o teu santo templo?’

[NOTE]
====
. Ou: “Deveras (certamente) olharei.” Th: “Como olharei?”
====

[[v32-2-5]]

^<<v32-2-5,5>>^ As águas me cercaram até à alma; a própria água de profundeza^&#42;1^ continuou a circundar-me.
Algas se enrolaram na minha cabeça.

[NOTE]
====
. Ou “as próprias águas empoladas”. Hebr.: tehóhm; LXXVg: “um abismo”.
====

[[v32-2-6]]

^<<v32-2-6,6>>^ Desci aos fundos dos montes.
Quanto à terra, suas trancas estavam sobre mim por tempo indefinido.
Mas foi da cova que passaste a fazer subir minha vida, ó Jeová, meu Deus.

[[v32-2-7]]

^<<v32-2-7,7>>^ Quando a minha alma^&#42;1^ se debilitou no meu íntimo, foi Jeová Aquele de quem me lembrei.
Então a minha oração chegou a ti dentro do teu santo templo.

[NOTE]
====
. “Minha alma.” Hebr.: naf·shí; gr.: psy·khén; lat.: á·ni·ma. Veja Ap. 4A.
====

[[v32-2-8]]

^<<v32-2-8,8>>^ Quanto aos que observam os ídolos da inveracidade, deixam a sua própria benevolência.

[[v32-2-9]]

^<<v32-2-9,9>>^ Mas, quanto a mim, vou oferecer sacrifícios a ti com voz de agradecimento.
O que votei, vou pagar. A salvação pertence a Jeová.”

[[v32-2-10]]

^<<v32-2-10,10>>^ Então Jeová deu ordem^&#42;1^ ao peixe, de modo que vomitou Jonas em terra seca.

[NOTE]
====
. Lit.: “disse ao”.
====

'''

xref:032-jonas/032-jonas-001.adoc#v32-1-0[&#60; Capítulo Anterior] | <<v32-2-0,Topo>> | xref:032-jonas/032-jonas-003.adoc#v32-3-0[Próximo Capítulo &#62;]