include::./index.adoc[]

[[v47-12-0]]
=== 2 Coríntios, 12
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v47-12-1]]

^<<v47-12-1,1>>^ Tenho de me jactar. Não é proveitoso; mas passarei para visões sobrenaturais e revelações da parte do Senhor.

[[v47-12-2]]

^<<v47-12-2,2>>^ Conheço um homem em união com Cristo, o qual, há quatorze anos — quer [no] corpo, não sei, quer fora do corpo, não sei; Deus sabe — foi arrebatado como tal até o terceiro céu.

[[v47-12-3]]

^<<v47-12-3,3>>^ Sim, conheço a tal homem — quer no corpo, quer à parte do corpo, não sei,^&#42;1^ Deus sabe —

[NOTE]
====
. “Não sei.” B omite isso.
====

[[v47-12-4]]

^<<v47-12-4,4>>^ que foi arrebatado para o paraíso^&#42;1^ e ouviu palavras inefáveis, as quais não são lícitas ao homem falar.

[NOTE]
====
. “Paraíso”, P46אBVgSypJ11,17,18; J22: “jardim do Éden”.
====

[[v47-12-5]]

^<<v47-12-5,5>>^ De tal homem^&#42;1^ é que me jactarei, mas não me jactarei de mim mesmo, exceto com respeito às [minhas] fraquezas.

[NOTE]
====
. Ou “coisa”, isto é, acontecimento.
====

[[v47-12-6]]

^<<v47-12-6,6>>^ Pois, se é que eu quiser jactar-me, não serei desarrazoado, porque direi a verdade. Abstenho-me, porém, a fim de que ninguém ponha para meu crédito mais do que ele vê que sou ou do que ele ouve de mim,

[[v47-12-7]]

^<<v47-12-7,7>>^ só por causa do excesso^&#42;1^ das revelações.
Portanto, a fim de que eu não me sentisse enaltecido demais, foi-me dado um espinho^&#42;2^ na carne, um anjo de Satanás, para que me estivesse esbofeteando, a fim de que eu não me enaltecesse demais.

[NOTE]
====
. Ou “da excelência”.
. Ou “estaca pontiaguda”.
====

[[v47-12-8]]

^<<v47-12-8,8>>^ Neste respeito supliquei três vezes ao Senhor para que isso se afastasse de mim;

[[v47-12-9]]

^<<v47-12-9,9>>^ contudo, ele me disse realmente: “Basta-te a minha benignidade imerecida; pois o [meu] poder está sendo aperfeiçoado na fraqueza.” De muito bom grado, portanto, jactar-me-ei antes com respeito às minhas fraquezas, para que o poder do Cristo permaneça sobre mim igual a uma tenda.

[[v47-12-10]]

^<<v47-12-10,10>>^ Portanto, tenho prazer em fraquezas, em insultos, em necessidades, em perseguições e dificuldades, por Cristo. Pois quando estou fraco, então é que sou poderoso.

[[v47-12-11]]

^<<v47-12-11,11>>^ Tornei-me desarrazoado. Vós me compelistes a isso, porque eu deveria ter sido recomendado por vós. Pois não me mostrei em nem uma única coisa inferior aos [vossos] superfinos apóstolos, embora eu não seja nada.

[[v47-12-12]]

^<<v47-12-12,12>>^ Deveras, os sinais de apóstolo foram produzidos entre vós em toda a perseverança, e por sinais, e portentos, e obras poderosas.^&#42;1^

[NOTE]
====
. Ou “e milagres”.
====

[[v47-12-13]]

^<<v47-12-13,13>>^ Pois, em que sentido é que vos tornastes menos que o resto das congregações, exceto que eu mesmo não me tornei fardo para vós? Perdoai-me bondosamente este erro.

[[v47-12-14]]

^<<v47-12-14,14>>^ Eis que esta é a terceira vez que estou pronto para ir ter convosco, contudo, não me tornarei fardo. Pois estou buscando, não as vossas posses, mas a vós; porque os filhos é que não deviam acumular para os [seus] pais, mas os pais para os [seus] filhos.

[[v47-12-15]]

^<<v47-12-15,15>>^ Pois eu, da minha parte, de muito bom grado gastarei e serei completamente gasto em prol das vossas almas. Se eu vos amo mais abundantemente, hei de ser amado menos?

[[v47-12-16]]

^<<v47-12-16,16>>^ Mas, seja como for, não vos sobrecarreguei. Não obstante, dizeis que fui “ardiloso” e que vos apanhei “com velhacaria”.

[[v47-12-17]]

^<<v47-12-17,17>>^ Quanto a qualquer daqueles que vos mandei, será que me aproveitei de vós por intermédio dele?

[[v47-12-18]]

^<<v47-12-18,18>>^ Instei com Tito e mandei o irmão com ele. Será que Tito é quem se aproveitou de vós? Não andamos no mesmo espírito, nas mesmas pisadas?

[[v47-12-19]]

^<<v47-12-19,19>>^ Pensastes todo esse tempo que estávamos fazendo a nossa defesa perante vós? É perante Deus que estamos falando em conexão com Cristo. Mas, amados, todas as coisas são para a vossa edificação.

[[v47-12-20]]

^<<v47-12-20,20>>^ Pois receio que, quando eu chegar aí, não vos ache, de algum modo, assim como queria, e eu não mostre ser para vós assim como queríeis, mas, em vez disso, que haja de algum modo rixa, ciúme, casos de ira, contendas, maledicências, cochichos, casos de enfunação, desordens.

[[v47-12-21]]

^<<v47-12-21,21>>^ Talvez, vindo eu novamente, meu Deus me humilhe entre vós e eu pranteie por muitos daqueles que anteriormente pecaram, mas não se arrependeram de sua impureza,^&#42;1^ e fornicação,^&#42;2^ e conduta desenfreada^&#42;3^ que praticaram.

[NOTE]
====
. “Impureza.” Gr.: a·ka·thar·sí·ai, dativo, sing.; J17,22(hebr.): hat·tum·’áh, “da impureza”. Veja Ez 22:15 n. e Gál 5:19 n.: “impureza”.
. Veja Ap. 5A.
. “Conduta desenfreada.” Gr.: a·sel·geí·ai, dativo, sing.; Vgc(lat.): im·pu·di·cí·ti·a; J17,22(hebr.): haz·zim·máh, “a conduta desenfreada”. Veja Gál 5:19 n.: “desenfreada”. Compare isso com Le 18:17 n.
====

'''

xref:047-2-corintios/047-2-corintios-011.adoc#v47-11-0[&#60; Capítulo Anterior] | <<v47-12-0,Topo>> | xref:047-2-corintios/047-2-corintios-013.adoc#v47-13-0[Próximo Capítulo &#62;]