include::./index.adoc[]

[[v47-7-0]]
=== 2 Coríntios, 7
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v47-7-1]]

^<<v47-7-1,1>>^ Portanto, amados, visto que temos estas promessas, purifiquemo-nos de toda imundície da carne e do espírito, aperfeiçoando a santidade em temor de Deus.

[[v47-7-2]]

^<<v47-7-2,2>>^ Concedei-nos espaço.^&#42;1^ Não temos feito injustiça a ninguém, não temos corrompido a ninguém, não nos temos aproveitado de ninguém.

[NOTE]
====
. Ou: “Acolhei-nos.”
====

[[v47-7-3]]

^<<v47-7-3,3>>^ Não digo isso para vos condenar. Pois eu já disse que estais em nossos corações para morrer e para viver conosco.

[[v47-7-4]]

^<<v47-7-4,4>>^ Uso para convosco de muita franqueza no falar.^&#42;1^ Tenho muita jactância com respeito a vós. Estou cheio de consolo, estou transbordando de alegria em toda a nossa aflição.

[NOTE]
====
. Ou “grande denodo no falar”.
====

[[v47-7-5]]

^<<v47-7-5,5>>^ De fato, quando chegamos à Macedônia, nossa carne não teve alívio, mas continuamos a ser afligidos de toda maneira — havia lutas por fora, temores por dentro.

[[v47-7-6]]

^<<v47-7-6,6>>^ Não obstante, Deus, que consola os abatidos, consolou-nos com a presença^&#42;1^ de Tito;

[NOTE]
====
. Veja Ap. 5B.
====

[[v47-7-7]]

^<<v47-7-7,7>>^ contudo, não somente com a presença dele, mas também com o consolo pelo qual tinha sido consolado quanto a vós, visto que nos trouxe notícia de vossa saudade, de vosso lamento, de vosso zelo por mim; de modo que me alegrei ainda mais.

[[v47-7-8]]

^<<v47-7-8,8>>^ Por isso, mesmo que eu vos tenha entristecido com a minha carta, não o deploro. Embora eu o tenha no princípio deplorado, (vejo que aquela carta vos entristeceu, embora por pouco tempo,)^&#42;1^

[NOTE]
====
. Ou “por uma hora”.
====

[[v47-7-9]]

^<<v47-7-9,9>>^ agora me alegro, não porque fostes entristecidos, mas porque fostes entristecidos até o arrependimento; pois fostes entristecidos de modo piedoso, para que não sofrêsseis dano em algo devido a nós.

[[v47-7-10]]

^<<v47-7-10,10>>^ Porque a tristeza de modo piedoso produz arrependimento^&#42;1^ para a salvação que não se há de deplorar; mas, a tristeza do mundo produz a morte.

[NOTE]
====
. Lit.: “mudança de idéia”. Gr.: me·tá·noi·an.
====

[[v47-7-11]]

^<<v47-7-11,11>>^ Pois, esta mesma coisa, a de serdes entristecidos de modo piedoso, eis que grande seriedade produziu em vós, sim, a vossa reabilitação, sim, indignação, sim, temor, sim, saudade, sim, zelo, sim, o endireitamento do errado! Demonstrastes em todo sentido que sois castos neste assunto.

[[v47-7-12]]

^<<v47-7-12,12>>^ Certamente, embora eu vos tenha escrito, fiz isso, não para aquele que fez injustiça, nem para aquele a quem se fez injustiça, mas para que a vossa seriedade por nós fosse manifesta entre vós à vista de Deus.

[[v47-7-13]]

^<<v47-7-13,13>>^ É por isso que temos sido consolados.
No entanto, em adição ao nosso consolo, alegramo-nos ainda mais abundantemente por causa da alegria de Tito, porque o seu espírito tem sido reanimado por todos vós.

[[v47-7-14]]

^<<v47-7-14,14>>^ Pois, se de algum modo eu me jactei de vós diante dele, não fui envergonhado; mas, assim como vos temos falado todas as coisas em verdade, assim também se mostrou veraz a nossa jactância diante de Tito.

[[v47-7-15]]

^<<v47-7-15,15>>^ As ternas afeições dele, também, são mais abundantes para convosco, ao se lembrar ele da obediência de todos vós, de como o recebestes com temor e tremor.

[[v47-7-16]]

^<<v47-7-16,16>>^ Alegro-me que de todo modo posso ter boa coragem em razão de vós.

'''

xref:047-2-corintios/047-2-corintios-006.adoc#v47-6-0[&#60; Capítulo Anterior] | <<v47-7-0,Topo>> | xref:047-2-corintios/047-2-corintios-008.adoc#v47-8-0[Próximo Capítulo &#62;]