include::./index.adoc[]

[[v47-11-0]]
=== 2 Coríntios, 11
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v47-11-1]]

^<<v47-11-1,1>>^ Quisera eu que me suportásseis numa pequena irracionalidade. Mas, de fato, vós me estais suportando!

[[v47-11-2]]

^<<v47-11-2,2>>^ Pois, estou ciumento de vós com ciúme piedoso, porque eu, pessoalmente, vos prometi em casamento a um só marido, a fim de vos apresentar como virgem casta ao Cristo.

[[v47-11-3]]

^<<v47-11-3,3>>^ Mas, tenho medo de que, de algum modo, assim como a serpente seduziu Eva pela sua astúcia, vossas mentes sejam corrompidas, afastando-se da sinceridade e da castidade que se devem ao Cristo.

[[v47-11-4]]

^<<v47-11-4,4>>^ Pois, do modo como é, se alguém vem e prega um Jesus diferente do que nós pregamos, ou recebeis um espírito diferente do que recebestes, ou boas novas diferentes do que aceitastes, vós facilmente [o] suportais.

[[v47-11-5]]

^<<v47-11-5,5>>^ Porque eu considero que em nem uma única coisa me mostrei inferior aos vossos superfinos apóstolos.

[[v47-11-6]]

^<<v47-11-6,6>>^ Porém, mesmo que eu seja imperito na palavra, certamente não o sou no conhecimento; porém, manifestamo-vos [isso] de todo modo em todas as coisas.

[[v47-11-7]]

^<<v47-11-7,7>>^ Ou cometi um pecado por me humilhar, para que vós fôsseis enaltecidos, porque de bom grado, sem custo, vos declarei as boas novas de Deus?

[[v47-11-8]]

^<<v47-11-8,8>>^ A outras congregações roubei, por aceitar provisões,^&#42;1^ a fim de ministrar a vós;

[NOTE]
====
. Lit.: “uma provisão (salário)”. Lat.: sti·pén·di·um.
====

[[v47-11-9]]

^<<v47-11-9,9>>^ contudo, quando estive presente entre vós e padeci necessidade, não me tornei fardo nem mesmo para um único, pois os irmãos que vieram da Macedônia supriram abundantemente a minha deficiência. Sim, guardei-me de todos os modos para não me tornar oneroso para vós, e guardar-me-ei assim.

[[v47-11-10]]

^<<v47-11-10,10>>^ É verdade de Cristo, no meu caso, que não se fará parar esta jactância minha nas regiões da Acaia.

[[v47-11-11]]

^<<v47-11-11,11>>^ Por que razão? Porque não vos amo? Deus sabe [que vos amo].

[[v47-11-12]]

^<<v47-11-12,12>>^ Ora, o que venho fazendo, fá-lo-ei ainda mais, a fim de decepar o pretexto daqueles que estão querendo um pretexto para ser achados iguais a nós no cargo de que se jactam.

[[v47-11-13]]

^<<v47-11-13,13>>^ Porque tais homens são falsos apóstolos, trabalhadores fraudulentos, transformando-se em apóstolos de Cristo.

[[v47-11-14]]

^<<v47-11-14,14>>^ E não é de admirar, pois o próprio Satanás persiste em transformar-se em anjo de luz.

[[v47-11-15]]

^<<v47-11-15,15>>^ Portanto, não é grande coisa se os ministros dele também persistem em transformar-se em ministros da justiça. Mas o fim deles será segundo as suas obras.

[[v47-11-16]]

^<<v47-11-16,16>>^ Digo novamente: Ninguém pense que sou desarrazoado. Contudo, se realmente [o pensardes], aceitai-me mesmo como desarrazoado, para que eu também me jacte um pouco.

[[v47-11-17]]

^<<v47-11-17,17>>^ O que estou falando, não falo segundo o exemplo do Senhor, mas como em irracionalidade, neste convencimento peculiar da jactância.

[[v47-11-18]]

^<<v47-11-18,18>>^ Visto que muitos se jactam segundo a carne, eu também me jactarei.

[[v47-11-19]]

^<<v47-11-19,19>>^ Pois suportais de bom grado os desarrazoados, visto que sois razoáveis.

[[v47-11-20]]

^<<v47-11-20,20>>^ De fato, suportais a quem quer que vos escravize, quem quer que devore [o que tendes], quem quer que tome [o que tendes], quem quer que se enalteça sobre [vós], quem quer que vos bata no rosto.

[[v47-11-21]]

^<<v47-11-21,21>>^ Digo isso para a [nossa] desonra, como se a nossa posição tivesse ficado enfraquecida.
Mas, se outro for ousado em alguma coisa — estou falando desarrazoadamente — eu também sou ousado nela.

[[v47-11-22]]

^<<v47-11-22,22>>^ São eles hebreus? Eu também o sou. São israelitas? Eu também o sou. São [o] descendente de Abraão? Eu também o sou.

[[v47-11-23]]

^<<v47-11-23,23>>^ São ministros de Cristo? Respondo como louco: eu o sou ainda mais destacadamente: em labores mais abundantemente, em prisões mais abundantemente, em golpes até o excesso, muitas vezes perto da morte.

[[v47-11-24]]

^<<v47-11-24,24>>^ Dos judeus recebi cinco vezes quarenta golpes menos um,

[[v47-11-25]]

^<<v47-11-25,25>>^ três vezes fui espancado com varas, uma vez fui apedrejado, três vezes sofri naufrágio, uma noite e um dia passei no profundo;

[[v47-11-26]]

^<<v47-11-26,26>>^ em jornadas muitas vezes, em perigos de rios, em perigos de salteadores de estradas, em perigos da [minha própria] raça, em perigos das nações, em perigos na cidade, em perigos no ermo, em perigos no mar, em perigos entre falsos irmãos,

[[v47-11-27]]

^<<v47-11-27,27>>^ em labor e labuta, muitas vezes em noites sem dormir, em fome e sede, muitas vezes em abstinência de comida, em frio e nudez.

[[v47-11-28]]

^<<v47-11-28,28>>^ Além destas coisas de espécie externa, há o que de dia a dia me assedia, a ansiedade por todas as congregações.

[[v47-11-29]]

^<<v47-11-29,29>>^ Quem é fraco, e não sou eu fraco? Quem tropeça, e não estou eu enfurecido?

[[v47-11-30]]

^<<v47-11-30,30>>^ Se precisa haver jactância, jactar-me-ei das coisas que têm que ver com a minha fraqueza.

[[v47-11-31]]

^<<v47-11-31,31>>^ O Deus e Pai do Senhor Jesus, sim, Aquele que há de ser louvado^&#42;1^ para sempre, sabe que não estou mentindo.

[NOTE]
====
. Ou “que é bendito”.
====

[[v47-11-32]]

^<<v47-11-32,32>>^ Em Damasco, o governador,^&#42;1^ sob Aretas, o rei, guardava a cidade dos damascenos para se apoderar de mim,

[NOTE]
====
. Lit.: “o etnarca”. Gr.: ho e·thnár·khes.
====

[[v47-11-33]]

^<<v47-11-33,33>>^ mas, fizeram-me descer num cesto de vime por uma janela na muralha, e escapei das suas mãos.

'''

xref:047-2-corintios/047-2-corintios-010.adoc#v47-10-0[&#60; Capítulo Anterior] | <<v47-11-0,Topo>> | xref:047-2-corintios/047-2-corintios-012.adoc#v47-12-0[Próximo Capítulo &#62;]