include::./index.adoc[]

[[v47-10-0]]
=== 2 Coríntios, 10
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v47-10-1]]

^<<v47-10-1,1>>^ Ora, eu mesmo, Paulo, suplico-vos pela brandura e benignidade^&#42;1^ do Cristo, humilde como eu seja na aparência entre vós, embora, quando ausente, eu seja ousado para convosco.

[NOTE]
====
. Ou “razoabilidade”. Lit.: “docilidade”. Gr.: e·pi·ei·kí·as; lat.: mo·dé·sti·am.
====

[[v47-10-2]]

^<<v47-10-2,2>>^ Deveras, rogo para que, quando eu estiver presente, não use de ousadia com aquela confiança com que espero tomar medidas firmes contra alguns que nos avaliam como se andássemos segundo [o que somos na] carne.

[[v47-10-3]]

^<<v47-10-3,3>>^ Pois, embora andemos na carne, não travamos combate^&#42;1^ segundo [o que somos na] carne.

[NOTE]
====
. “Não travamos combate.” Lit.: “não prestamos serviço militar”. Gr.: ou . . . stra·teu·ó·me·tha; lat.: non . . . mi·li·tá·mus.
====

[[v47-10-4]]

^<<v47-10-4,4>>^ Porque as armas de nosso combate não são carnais, mas poderosas em Deus para demolir as coisas fortemente entrincheiradas.

[[v47-10-5]]

^<<v47-10-5,5>>^ Pois estamos demolindo raciocínios e toda coisa altiva levantada contra o conhecimento de Deus; e trazemos todo pensamento ao cativeiro, para fazê-lo obediente ao Cristo;

[[v47-10-6]]

^<<v47-10-6,6>>^ e mantemo-nos em prontidão, para infligir punição por toda desobediência, assim que a vossa própria obediência tiver sido executada plenamente.

[[v47-10-7]]

^<<v47-10-7,7>>^ Olhais para as coisas segundo o seu valor aparente. Se alguém confiar em si mesmo, de que pertence a Cristo, tome novamente em conta o seguinte fato para si mesmo, que, assim como ele pertence a Cristo, também nós [pertencemos].

[[v47-10-8]]

^<<v47-10-8,8>>^ Pois, mesmo que eu me jactasse um pouco demais da autoridade que o Senhor nos deu para vos edificar e não para vos demolir, eu não seria envergonhado,

[[v47-10-9]]

^<<v47-10-9,9>>^ para que não pareça que quero apavorar-vos com as [minhas] cartas.

[[v47-10-10]]

^<<v47-10-10,10>>^ Pois, eles dizem: “As [suas] cartas são ponderosas e vigorosas, mas a [sua] presença^&#42;1^ em pessoa é fraca e a [sua] palavra, desprezível.”

[NOTE]
====
. Veja Ap. 5B.
====

[[v47-10-11]]

^<<v47-10-11,11>>^ Que tal homem tome em conta o seguinte: que aquilo que somos em nossa palavra por cartas, quando ausentes, seremos também em ação, quando presentes.

[[v47-10-12]]

^<<v47-10-12,12>>^ Pois, não nos atrevemos a classificar-nos entre alguns ou a comparar-nos com alguns que recomendam a si mesmos. Certamente, ao se medirem consigo mesmos e se compararem consigo mesmos, eles não têm entendimento.

[[v47-10-13]]

^<<v47-10-13,13>>^ Da nossa parte, nós nos jactaremos, não fora de nossos termos determinados, mas segundo os termos do território que Deus nos repartiu por medida, fazendo-o alcançar até vós.

[[v47-10-14]]

^<<v47-10-14,14>>^ Realmente, não nos estamos esticando demais, como se não vos alcançássemos, pois fomos os primeiros a ir até vós, declarando as boas novas acerca do Cristo.

[[v47-10-15]]

^<<v47-10-15,15>>^ Não, não nos jactamos fora dos nossos termos determinados dos labores de outro, mas alimentamos a esperança de que, ao passo que a vossa fé está sendo aumentada, possamos ficar grandes entre vós, com referência ao nosso território. Então abundaremos ainda mais,

[[v47-10-16]]

^<<v47-10-16,16>>^ para declarar as boas novas aos países mais além de vós, a fim de não nos jactarmos em território de outro, onde as coisas já estão preparadas.

[[v47-10-17]]

^<<v47-10-17,17>>^ “Mas quem se jactar, jacte-se em Jeová.”^&#42;1^

[NOTE]
====
. Veja Ap. 1D.
====

[[v47-10-18]]

^<<v47-10-18,18>>^ Pois não é aprovado aquele que se recomenda a si mesmo, mas sim o homem a quem Jeová^&#42;1^ recomenda.

[NOTE]
====
. Veja Ap. 1D.
====

'''

xref:047-2-corintios/047-2-corintios-009.adoc#v47-9-0[&#60; Capítulo Anterior] | <<v47-10-0,Topo>> | xref:047-2-corintios/047-2-corintios-011.adoc#v47-11-0[Próximo Capítulo &#62;]