include::./index.adoc[]

[[v47-5-0]]
=== 2 Coríntios, 5
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v47-5-1]]

^<<v47-5-1,1>>^ Pois, nós sabemos que, se a nossa casa terrestre, esta tenda, se dissolver, havemos de ter um edifício da parte de Deus, uma casa não feita por mãos, eterna, nos céus.

[[v47-5-2]]

^<<v47-5-2,2>>^ Pois gememos deveras nesta casa de moradia, desejando seriamente revestir-nos da nossa, provinda do céu,

[[v47-5-3]]

^<<v47-5-3,3>>^ para que, revestindo-nos dela realmente, não sejamos achados nus.

[[v47-5-4]]

^<<v47-5-4,4>>^ De fato, nós, os que estamos nesta tenda, gememos, acabrunhados; porque queremos, não despir-nos dela, mas revestir-nos da outra, para que aquilo que é mortal seja tragado pela vida.

[[v47-5-5]]

^<<v47-5-5,5>>^ Ora, quem nos produziu para esta mesma coisa é Deus, que nos deu o penhor daquilo que há de vir,^&#42;1^ isto é, o espírito.

[NOTE]
====
. Ou “nos deu o sinal (pagamento adiantado) do que há de vir”. Veja 1:22 n.
====

[[v47-5-6]]

^<<v47-5-6,6>>^ Temos, portanto, sempre boa coragem e sabemos que, enquanto tivermos o nosso lar no corpo, estamos ausentes do Senhor,

[[v47-5-7]]

^<<v47-5-7,7>>^ pois estamos andando pela fé, não pela vista.

[[v47-5-8]]

^<<v47-5-8,8>>^ Mas, temos boa coragem e bem nos agradamos antes de ficar ausentes do corpo e de fazer o nosso lar com o Senhor.

[[v47-5-9]]

^<<v47-5-9,9>>^ Portanto, tomamos também por nosso alvo que, quer tenhamos o nosso lar com ele, quer estejamos ausentes dele, sejamos aceitáveis para ele.

[[v47-5-10]]

^<<v47-5-10,10>>^ Pois todos nós temos de ser manifestados perante a cadeira de juiz do Cristo, para que cada um receba o seu prêmio pelas coisas feitas por intermédio do corpo, segundo as coisas que praticou, quer boas, quer ruins.

[[v47-5-11]]

^<<v47-5-11,11>>^ Conhecendo, portanto, o temor do Senhor, persistimos em persuadir os homens, mas temos sido manifestados a Deus. No entanto, espero que tenhamos sido também manifestados às vossas consciências.

[[v47-5-12]]

^<<v47-5-12,12>>^ Não nos recomendamos novamente a vós, mas damo-vos um induzimento à jactância com respeito a nós, a fim de que tenhais uma resposta para os que se jactam da aparência externa, mas não do coração.

[[v47-5-13]]

^<<v47-5-13,13>>^ Pois, se não tivemos bom juízo, foi para Deus; se temos bom juízo, é para vós.

[[v47-5-14]]

^<<v47-5-14,14>>^ Pois o amor de Cristo^&#42;1^ nos compele, porque foi isso o que julgamos, que um só homem morreu por todos; de modo que, então, todos tinham morrido;

[NOTE]
====
. Ou “amor do Cristo”.
====

[[v47-5-15]]

^<<v47-5-15,15>>^ e ele morreu por todos, para que os que vivem não vivessem mais para si mesmos, mas para aquele que morreu por eles e foi levantado.

[[v47-5-16]]

^<<v47-5-16,16>>^ Por conseguinte, doravante não conhecemos mais a nenhum homem segundo a carne. Embora tenhamos conhecido a Cristo segundo a carne, certamente agora não o conhecemos mais assim.

[[v47-5-17]]

^<<v47-5-17,17>>^ Conseqüentemente, se alguém estiver em união com Cristo, ele é uma nova criação;^&#42;1^ as coisas antigas passaram, eis que novas coisas vieram à existência!

[NOTE]
====
. Ou “criatura”. Gr.: ktí·sis; lat.: cre·a·tú·ra.
====

[[v47-5-18]]

^<<v47-5-18,18>>^ Mas, todas as coisas são de Deus, que nos reconciliou consigo mesmo por intermédio de Cristo e nos deu o ministério da reconciliação,

[[v47-5-19]]

^<<v47-5-19,19>>^ a saber, que Deus, por meio de Cristo, estava reconciliando um mundo consigo mesmo, não lhes imputando as suas falhas, e ele nos encarregou da palavra da reconciliação.

[[v47-5-20]]

^<<v47-5-20,20>>^ Somos, portanto, embaixadores, substituindo a^&#42;1^ Cristo, como se Deus instasse por nosso intermédio. Rogamos, como substitutos de Cristo: “Sede reconciliados com Deus.”

[NOTE]
====
. Ou “em lugar de; em nome de”.
====

[[v47-5-21]]

^<<v47-5-21,21>>^ Àquele que não conheceu pecado, ele fez pecado^&#42;1^ por nós, para que, por meio dele, nos tornássemos a justiça de Deus.

[NOTE]
====
. Ou “oferta pelo pecado”. Gr.: ha·mar·tí·an; J17,18,22(hebr.): lehhat·tá’th, “como oferta pelo pecado”, como no M, em Le 4:3.
====

'''

xref:047-2-corintios/047-2-corintios-004.adoc#v47-4-0[&#60; Capítulo Anterior] | <<v47-5-0,Topo>> | xref:047-2-corintios/047-2-corintios-006.adoc#v47-6-0[Próximo Capítulo &#62;]