include::./index.adoc[]

[[v47-8-0]]
=== 2 Coríntios, 8
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v47-8-1]]

^<<v47-8-1,1>>^ Agora, deixamo-vos saber, irmãos, com respeito à benignidade imerecida de Deus, que tem sido concedida às congregações da Macedônia,

[[v47-8-2]]

^<<v47-8-2,2>>^ que, durante uma grande prova, sob tribulação, a abundância da alegria e a profunda pobreza deles fizeram abundar as riquezas de sua generosidade.

[[v47-8-3]]

^<<v47-8-3,3>>^ Pois, isso foi segundo a capacidade real deles, sim, testifico que foi além de sua capacidade real,

[[v47-8-4]]

^<<v47-8-4,4>>^ ao passo que nos rogavam espontaneamente, com muita súplica, pelo [privilégio de] dar bondosamente e pela participação no ministério destinado aos santos.

[[v47-8-5]]

^<<v47-8-5,5>>^ E não somente conforme esperávamos, mas, primeiro, entregaram-se ao Senhor e a nós por intermédio da vontade de Deus.

[[v47-8-6]]

^<<v47-8-6,6>>^ Isto nos levou a encorajar Tito, para que, assim como fora ele quem o iniciou entre vós, também complete esta mesma espécie de dar da vossa parte.

[[v47-8-7]]

^<<v47-8-7,7>>^ Não obstante, assim como vós abundais em tudo, em fé, e em palavra, e em conhecimento, e em toda a seriedade, e neste amor nosso por vós, que abundeis também nesta dádiva benigna.

[[v47-8-8]]

^<<v47-8-8,8>>^ Não é como se fôsseis mandados, mas em vista da seriedade dos outros e para fazer uma prova da genuinidade do vosso amor é que eu estou falando.

[[v47-8-9]]

^<<v47-8-9,9>>^ Pois conheceis a benignidade imerecida de nosso Senhor Jesus Cristo,^&#42;1^ que ele, embora fosse rico, tornou-se pobre por vossa causa, para que vos tornásseis ricos por intermédio de sua pobreza.

[NOTE]
====
. “Cristo.” B omite isso.
====

[[v47-8-10]]

^<<v47-8-10,10>>^ E é nisso que dou uma opinião: pois este assunto é de proveito para vós, visto que já faz um ano que iniciastes não somente o fazer, mas também o querer [fazer];

[[v47-8-11]]

^<<v47-8-11,11>>^ agora, pois, acabai também de fazer isso, a fim de que, assim como houve prontidão para querer fazer, haja também a conclusão disso dentre aquilo que tendes.^&#42;1^

[NOTE]
====
. Ou “disso segundo puderdes”.
====

[[v47-8-12]]

^<<v47-8-12,12>>^ Pois, se houver primeiro a prontidão, é especialmente aceitável segundo o que a pessoa tem, não segundo o que a pessoa não tem.

[[v47-8-13]]

^<<v47-8-13,13>>^ Porque não tenciono que seja fácil para os outros, mas difícil para vós;

[[v47-8-14]]

^<<v47-8-14,14>>^ mas que o vosso excedente, por meio duma reciprocidade, contrabalance agora mesmo a deficiência deles, a fim de que o excedente deles também venha a contrabalançar a vossa deficiência, para que haja reciprocidade.

[[v47-8-15]]

^<<v47-8-15,15>>^ Assim como está escrito: “Quem [teve] muito, não teve de mais, e quem [teve] pouco, não teve de menos.”

[[v47-8-16]]

^<<v47-8-16,16>>^ Ora, graças a Deus por ter colocado a mesma seriedade por vós no coração de Tito,

[[v47-8-17]]

^<<v47-8-17,17>>^ porque, deveras, ele correspondeu ao nosso encorajamento, mas, sendo muito sério, está partindo espontaneamente para ir ter convosco.

[[v47-8-18]]

^<<v47-8-18,18>>^ Nós, porém, enviamos junto com ele o irmão cujo louvor em conexão com as boas novas se tem espalhado por todas as congregações.

[[v47-8-19]]

^<<v47-8-19,19>>^ Não só isso, mas ele foi também designado pelas congregações para ser nosso companheiro de viagem, em conexão com esta dádiva benigna a ser administrada por nós para a glória do Senhor e em prova de nossa mente disposta.

[[v47-8-20]]

^<<v47-8-20,20>>^ Estamos assim evitando que algum homem ache falta em nós em conexão com esta contribuição liberal a ser administrada por nós.

[[v47-8-21]]

^<<v47-8-21,21>>^ Pois nós ‘fazemos provisão honesta, não somente à vista de Jeová,^&#42;1^ mas também à vista dos homens’.

[NOTE]
====
. “De Jeová”, J7,8,24; אB(gr.): Ky·rí·ou; P46VgSyp: “de Deus”. Veja Ap. 1D.
====

[[v47-8-22]]

^<<v47-8-22,22>>^ Além disso, estamos enviando com eles o nosso irmão, a respeito de quem provamos muitas vezes, em muitas coisas, que ele é sério, mas agora muito mais sério, devido à sua grande confiança em vós.

[[v47-8-23]]

^<<v47-8-23,23>>^ Se, porém, houver qualquer pergunta sobre Tito, ele é parceiro meu e colaborador nos vossos interesses; ou, se a respeito de nossos irmãos, eles são apóstolos^&#42;1^ de congregações e glória de Cristo.

[NOTE]
====
. Ou “enviados; homens mandados”.
====

[[v47-8-24]]

^<<v47-8-24,24>>^ Portanto, demonstrai-lhes a prova de vosso amor e daquilo de que nos jactamos a respeito de vós, à face de todas as congregações.

'''

xref:047-2-corintios/047-2-corintios-007.adoc#v47-7-0[&#60; Capítulo Anterior] | <<v47-8-0,Topo>> | xref:047-2-corintios/047-2-corintios-009.adoc#v47-9-0[Próximo Capítulo &#62;]