include::./index.adoc[]

[[v47-13-0]]
=== 2 Coríntios, 13
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v47-13-1]]

^<<v47-13-1,1>>^ Esta é a terceira vez que vou ter convosco. “Todo assunto tem de ser estabelecido pela boca de duas ou três testemunhas.”

[[v47-13-2]]

^<<v47-13-2,2>>^ Eu já disse anteriormente, e como que presente pela segunda vez, contudo ausente agora, digo de antemão aos que antes pecaram e a todos os demais, que não pouparei, se é que eu for outra vez^&#42;1^ aí,

[NOTE]
====
. Ou “eu voltar”.
====

[[v47-13-3]]

^<<v47-13-3,3>>^ visto que estais buscando uma prova de que Cristo fala por mim, [Cristo] que não é fraco para convosco, mas é poderoso entre vós.

[[v47-13-4]]

^<<v47-13-4,4>>^ De fato, é verdade que ele foi pregado numa estaca^&#42;1^ devido à fraqueza, mas ele está vivo devido ao poder de Deus. É também verdade que nós somos fracos com ele, mas, havemos de viver junto com ele devido ao poder de Deus para convosco.^&#42;2^

[NOTE]
====
. Ou “fixado numa estaca (poste)”. Veja Ap. 5C.
. “Para convosco.” B omite isso.
====

[[v47-13-5]]

^<<v47-13-5,5>>^ Persisti em examinar se estais na fé, persisti em provar o que vós mesmos sois. Ou não reconheceis que Jesus Cristo está em união convosco? A menos que estejais reprovados.

[[v47-13-6]]

^<<v47-13-6,6>>^ Eu espero, deveras, que venhais a saber que não estamos reprovados.

[[v47-13-7]]

^<<v47-13-7,7>>^ Agora, oramos a Deus para que não façais nada de errado, não para que nós mesmos pareçamos aprovados, mas para que façais o que é excelente, embora nós mesmos pareçamos reprovados.

[[v47-13-8]]

^<<v47-13-8,8>>^ Pois, não podemos fazer nada contra a verdade, mas somente a favor da verdade.

[[v47-13-9]]

^<<v47-13-9,9>>^ Certamente nos regozijamos sempre que estejamos fracos, mas vós poderosos; e por isso é que oramos, que sejais reajustados.^&#42;1^

[NOTE]
====
. Ou “colocados no alinhamento correto”.
====

[[v47-13-10]]

^<<v47-13-10,10>>^ É por isso que escrevo estas coisas enquanto ausente, para que, quando eu estiver presente, não aja com severidade segundo a autoridade que o Senhor me deu, para edificar e não para demolir.

[[v47-13-11]]

^<<v47-13-11,11>>^ Finalmente, irmãos, continuai a alegrar-vos, a ser reajustados, a ser consolados, a pensar em acordo, a viver pacificamente; e o Deus de amor e de paz estará convosco.

[[v47-13-12]]

^<<v47-13-12,12>>^ Cumprimentai-vos uns aos outros com beijo santo.

[[v47-13-13]]

^<<v47-13-13,13>>^ Todos os santos vos mandam os seus cumprimentos.

[[v47-13-14]]

^<<v47-13-14,14>>^ A benignidade imerecida do Senhor Jesus Cristo,^&#42;1^ e o amor de Deus, e a participação no espírito santo sejam com todos vós.

[NOTE]
====
. “Cristo.” B omite isso.
====

'''

xref:047-2-corintios/047-2-corintios-012.adoc#v47-12-0[&#60; Capítulo Anterior] | <<v47-13-0,Topo>> | xref:048-galatas/048-galatas-001.adoc#v48-1-0[Próximo Capítulo &#62;]