include::./index.adoc[]

[[v47-9-0]]
=== 2 Coríntios, 9
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v47-9-1]]

^<<v47-9-1,1>>^ Agora, a respeito do ministério que é para os santos, é supérfluo que eu vos escreva,

[[v47-9-2]]

^<<v47-9-2,2>>^ pois conheço a vossa prontidão mental, da qual me estou jactando perante os macedônios a respeito de vós, que a Acaia já está agora pronta por um ano, e o vosso zelo tem atiçado a maioria deles.

[[v47-9-3]]

^<<v47-9-3,3>>^ Mas, envio os irmãos, para que a nossa jactância de vós não se mostre vã neste respeito, mas para que estejais realmente prontos, assim como eu costumava dizer que estaríeis.

[[v47-9-4]]

^<<v47-9-4,4>>^ De outro modo, se os macedônios viessem de algum modo comigo e não vos achassem prontos, nós — para não dizer vós — seríamos envergonhados nesta afirmação nossa.

[[v47-9-5]]

^<<v47-9-5,5>>^ Por isso achei necessário encorajar os irmãos para irem ter convosco com antecedência e aprontarem com antecedência a vossa abundante dádiva, anteriormente prometida, para que estivesse pronta como dádiva abundante e não como algo extorquido.^&#42;1^

[NOTE]
====
. Ou “algo dado com avareza”.
====

[[v47-9-6]]

^<<v47-9-6,6>>^ Mas, quanto a isso, quem semear parcimoniosamente, ceifará também parcimoniosamente; e quem semear generosamente, ceifará também generosamente.

[[v47-9-7]]

^<<v47-9-7,7>>^ Faça cada um conforme tem resolvido no seu coração, não de modo ressentido, nem sob compulsão, pois Deus ama o dador animado.

[[v47-9-8]]

^<<v47-9-8,8>>^ Ademais, Deus é capaz de fazer abundar para vós toda a sua benignidade imerecida, para que, embora tenhais sempre plena auto-suficiência em tudo, tenhais bastante para toda boa obra.

[[v47-9-9]]

^<<v47-9-9,9>>^ (Assim como está escrito: “Ele tem distribuído amplamente, ele tem dado aos pobres, a sua justiça^&#42;1^ continua para sempre.”

[NOTE]
====
. Ou “beneficência”.
====

[[v47-9-10]]

^<<v47-9-10,10>>^ Ora, quem supre abundantemente semente ao semeador e pão para comer vos fornecerá e multiplicará semente para semear e aumentará os produtos da vossa justiça.)

[[v47-9-11]]

^<<v47-9-11,11>>^ Em tudo estais sendo enriquecidos para toda sorte de generosidade, a qual, por nosso intermédio, produz uma expressão de agradecimento a Deus;

[[v47-9-12]]

^<<v47-9-12,12>>^ porque o ministério deste serviço público não é somente para suprir abundantemente a carência dos santos, mas também para ser rico com muitas expressões de agradecimentos a Deus.

[[v47-9-13]]

^<<v47-9-13,13>>^ Por intermédio da prova fornecida por este ministério, eles glorificam a Deus porque sois submissos às boas novas a respeito do Cristo, conforme declarais publicamente que sois, e porque sois generosos na vossa contribuição para eles e para todos;

[[v47-9-14]]

^<<v47-9-14,14>>^ e eles, com súplicas por vós, têm saudade de vós, por causa da sobrepujante benignidade imerecida de Deus para convosco.

[[v47-9-15]]

^<<v47-9-15,15>>^ Graças a Deus por sua indescritível dádiva gratuita.

'''

xref:047-2-corintios/047-2-corintios-008.adoc#v47-8-0[&#60; Capítulo Anterior] | <<v47-9-0,Topo>> | xref:047-2-corintios/047-2-corintios-010.adoc#v47-10-0[Próximo Capítulo &#62;]