include::./index.adoc[]

[[v47-3-0]]
=== 2 Coríntios, 3
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v47-3-1]]

^<<v47-3-1,1>>^ Estamos novamente principiando a recomendar a nós mesmos? Ou necessitamos talvez, como alguns homens, de cartas de recomendação para vós ou de vós?

[[v47-3-2]]

^<<v47-3-2,2>>^ Vós mesmos sois a nossa carta, inscrita nos nossos^&#42;1^ corações, e conhecida e lida por toda a humanidade.

[NOTE]
====
. “Nossos”, P46ABCDVgSyh,p; א: “vossos”.
====

[[v47-3-3]]

^<<v47-3-3,3>>^ Porque vós sois demonstrados ser carta de Cristo, escrita por nós, como ministros, inscrita, não com tinta, mas com espírito dum Deus vivente, não em tábuas de pedra, mas em tábuas carnais, nos corações.^&#42;1^

[NOTE]
====
. Ou “em tábuas, em corações carnais”.
====

[[v47-3-4]]

^<<v47-3-4,4>>^ Ora, é por intermédio do Cristo que temos esta sorte de confiança em Deus.

[[v47-3-5]]

^<<v47-3-5,5>>^ Não é que de nós mesmos estejamos adequadamente habilitados para considerar qualquer coisa como procedente de nós mesmos, mas, estarmos adequadamente habilitados^&#42;1^ procede de Deus,

[NOTE]
====
. Lit.: “nossa suficiência”.
====

[[v47-3-6]]

^<<v47-3-6,6>>^ quem deveras nos habilitou adequadamente para sermos ministros^&#42;1^ dum novo pacto, não dum código escrito,^&#42;2^ mas de espírito; pois o código escrito condena à morte, mas o espírito vivifica.

[NOTE]
====
. Ou “servos”. Gr.: di·a·kó·nous; lat.: mi·ní·stros (de mí·nus, “menos”); J22(hebr.): mesha·rethím.
. Lit.: “em forma escrita”. Gr.: grám·ma·tos; lat.: lít·te·rae.
====

[[v47-3-7]]

^<<v47-3-7,7>>^ Além disso, se o código que administra a morte e que foi gravado^&#42;1^ com letras em pedras veio a existir em glória, de modo que os filhos de Israel não podiam fitar atentamente os olhos no rosto de Moisés, por causa da glória do seu rosto, [glória] que havia de ser eliminada,

[NOTE]
====
. Ou “se a administração da morte gravada”.
====

[[v47-3-8]]

^<<v47-3-8,8>>^ por que não deve a administração do espírito ser com muito mais glória?

[[v47-3-9]]

^<<v47-3-9,9>>^ Porque, se o código que administrava a condenação^&#42;1^ era glorioso,^&#42;2^ muito mais abundará com glória a administração da justiça.

[NOTE]
====
. Ou “se a administração da condenação”.
. Lit.: “era glória”.
====

[[v47-3-10]]

^<<v47-3-10,10>>^ De fato, mesmo aquilo que outrora fora feito glorioso tem sido despojado de glória neste respeito, por causa da glória que a excede.

[[v47-3-11]]

^<<v47-3-11,11>>^ Pois, se aquilo que havia de ser eliminado foi introduzido com glória, muito mais glória teria aquilo que permanece.

[[v47-3-12]]

^<<v47-3-12,12>>^ Portanto, visto que temos tal esperança, estamos usando de muita franqueza no falar,

[[v47-3-13]]

^<<v47-3-13,13>>^ e não fazemos como Moisés [fazia], pondo um véu sobre o seu rosto, para que os filhos de Israel não fitassem atentamente os olhos no fim daquilo que havia de ser eliminado.

[[v47-3-14]]

^<<v47-3-14,14>>^ Mas as suas faculdades mentais estavam obtusas. Pois até o dia atual permanece o mesmo véu sem ser levantado, por ocasião da leitura do antigo pacto,^&#42;1^ porque é eliminado por meio de Cristo.

[NOTE]
====
. Para um exame das expressões “O Antigo (Velho) Testamento” e “O Novo Testamento” veja Ap. 7E.
====

[[v47-3-15]]

^<<v47-3-15,15>>^ De fato, até o dia de hoje, sempre que se lê Moisés, há um véu deitado sobre os seus corações.

[[v47-3-16]]

^<<v47-3-16,16>>^ Mas, quando há um retorno a Jeová,^&#42;1^ é retirado o véu.

[NOTE]
====
. Veja Ap. 1D.
====

[[v47-3-17]]

^<<v47-3-17,17>>^ Ora, Jeová^&#42;1^ é o Espírito; e onde estiver o espírito de Jeová,^&#42;2^ ali há liberdade.

[NOTE]
====
. Veja Ap. 1D.
. Veja Ap. 1D.
====

[[v47-3-18]]

^<<v47-3-18,18>>^ E todos nós, ao passo que com rostos desvelados refletimos como espelhos a glória de Jeová,^&#42;1^ somos transformados na mesma imagem, de glória em glória, exatamente como feito por Jeová,^&#42;2^ [o] Espírito.^&#42;3^

[NOTE]
====
. Veja Ap. 1D.
. Veja Ap. 1D.
. Ou “pelo espírito de Jeová”.
====

'''

xref:047-2-corintios/047-2-corintios-002.adoc#v47-2-0[&#60; Capítulo Anterior] | <<v47-3-0,Topo>> | xref:047-2-corintios/047-2-corintios-004.adoc#v47-4-0[Próximo Capítulo &#62;]