include::./index.adoc[]

[[v47-2-0]]
=== 2 Coríntios, 2
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v47-2-1]]

^<<v47-2-1,1>>^ Pois decidi o seguinte para mim mesmo: não ir ter convosco novamente em tristeza.

[[v47-2-2]]

^<<v47-2-2,2>>^ Porque, se eu vos entristecer, deveras, quem há para me animar, exceto aquele que é entristecido por mim?

[[v47-2-3]]

^<<v47-2-3,3>>^ E assim escrevi esta mesma coisa, para que, quando eu for aí, eu não fique entristecido por causa daqueles de quem devia alegrar-me; porque tenho confiança em todos vós, de que a alegria que tenho é a de todos vós.

[[v47-2-4]]

^<<v47-2-4,4>>^ Pois eu vos escrevi em muita tribulação e angústia de coração, com muitas lágrimas, não para vos entristecer, mas para que soubésseis que amor tenho, mais especificamente por vós.

[[v47-2-5]]

^<<v47-2-5,5>>^ Ora, se alguém causou tristeza, ele entristeceu, não a mim, mas a todos vós, até certo ponto — para não ser rigoroso demais naquilo que digo.

[[v47-2-6]]

^<<v47-2-6,6>>^ Esta censura da parte da maioria é suficiente para tal homem,

[[v47-2-7]]

^<<v47-2-7,7>>^ de modo que agora, ao contrário, deveis perdoar-lhe bondosamente e [deveis] consolá-lo, para que tal homem não seja de algum modo tragado pela sua excessiva tristeza.

[[v47-2-8]]

^<<v47-2-8,8>>^ Exorto-vos, portanto, a que confirmeis o vosso amor por ele.

[[v47-2-9]]

^<<v47-2-9,9>>^ Porque eu vos escrevo também com o fim de averiguar de vós a prova, se sois obedientes em todas as coisas.

[[v47-2-10]]

^<<v47-2-10,10>>^ O que bondosamente perdoardes a alguém, eu também [perdôo]. De fato, quanto a mim, o que eu tiver bondosamente perdoado, se é que perdoei bondosamente alguma coisa, tem sido por vossa causa à vista de Cristo;

[[v47-2-11]]

^<<v47-2-11,11>>^ para que não sejamos sobrepujados por Satanás, pois não desconhecemos os seus desígnios.

[[v47-2-12]]

^<<v47-2-12,12>>^ Ora, quando cheguei a Trôade, para declarar as boas novas a respeito do Cristo, e se me abriu uma porta no Senhor,

[[v47-2-13]]

^<<v47-2-13,13>>^ não tive alívio no meu espírito, por não achar Tito, meu irmão, mas despedi-me deles e parti para a Macedônia.

[[v47-2-14]]

^<<v47-2-14,14>>^ Graças, porém, a Deus, que sempre nos conduz numa procissão triunfal, em companhia do Cristo, e que faz que o cheiro do conhecimento dele seja perceptível em toda a parte por nosso intermédio!

[[v47-2-15]]

^<<v47-2-15,15>>^ Pois, para Deus somos cheiro fragrante de Cristo entre os que estão sendo salvos e entre os que estão perecendo;

[[v47-2-16]]

^<<v47-2-16,16>>^ para estes últimos, cheiro que procede da morte para a morte, para os primeiros, cheiro que procede da vida para a vida. E quem está adequadamente habilitado para estas coisas?

[[v47-2-17]]

^<<v47-2-17,17>>^ [Nós estamos;] pois não somos vendedores ambulantes^&#42;1^ da palavra de Deus, assim como muitos homens são, mas falamos em sinceridade, sim, como enviados por Deus, sob a vista de Deus, em companhia de Cristo.

[NOTE]
====
. Ou “os que comercializam (lucram com) a; adulteradores”.
====

'''

xref:047-2-corintios/047-2-corintios-001.adoc#v47-1-0[&#60; Capítulo Anterior] | <<v47-2-0,Topo>> | xref:047-2-corintios/047-2-corintios-003.adoc#v47-3-0[Próximo Capítulo &#62;]