include::./index.adoc[]

[[v47-6-0]]
=== 2 Coríntios, 6
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v47-6-1]]

^<<v47-6-1,1>>^ Cooperando com ele, também nós instamos convosco para que não aceiteis a benignidade imerecida de Deus e desacerteis o propósito dela.

[[v47-6-2]]

^<<v47-6-2,2>>^ Pois ele diz: “Num tempo aceitável te ouvi e num dia de salvação te ajudei.” Eis que agora é o tempo especialmente aceitável. Eis que agora é o dia de salvação.

[[v47-6-3]]

^<<v47-6-3,3>>^ De modo algum damos qualquer causa para tropeço, para que não se ache falta no nosso ministério;

[[v47-6-4]]

^<<v47-6-4,4>>^ mas, recomendamo-nos de todo modo como ministros^&#42;1^ de Deus, na perseverança em muito, em tribulações, em necessidades, em dificuldades,

[NOTE]
====
. Ou “servos”. Gr.: di·á·ko·noi; lat.: mi·ní·stros (de mí·nus, “menos”); J18,22(hebr.): kim·sha·rethéh, “como ministros de”.
====

[[v47-6-5]]

^<<v47-6-5,5>>^ em espancamentos, em prisões, em desordens, em labores, em noites sem dormir, em tempos sem comida,

[[v47-6-6]]

^<<v47-6-6,6>>^ pela pureza, pelo conhecimento, pela longanimidade, pela benignidade, por espírito santo, pelo amor livre de hipocrisia,

[[v47-6-7]]

^<<v47-6-7,7>>^ pela palavra veraz, pelo poder de Deus; por intermédio das armas da justiça à direita e à esquerda,^&#42;1^

[NOTE]
====
. Ou “para ofensiva e para defesa”.
====

[[v47-6-8]]

^<<v47-6-8,8>>^ por intermédio de glória e de desonra, através de relatos maus e de relatos bons; como enganadores, e ainda assim verazes,

[[v47-6-9]]

^<<v47-6-9,9>>^ como desconhecidos, e ainda assim reconhecidos, como morrendo, e ainda assim, eis que vivemos, como disciplinados, e ainda assim não entregues à morte,

[[v47-6-10]]

^<<v47-6-10,10>>^ como pesarosos, mas sempre alegres, como pobres, mas enriquecendo a muitos, como não tendo nada, e ainda assim possuindo todas as coisas.

[[v47-6-11]]

^<<v47-6-11,11>>^ A nossa boca abriu-se para vós, coríntios, o nosso coração alargou-se.

[[v47-6-12]]

^<<v47-6-12,12>>^ Não estais comprimidos quanto ao espaço no nosso íntimo, mas estais comprimidos quanto ao espaço nas vossas próprias ternas afeições.

[[v47-6-13]]

^<<v47-6-13,13>>^ Assim, como recompensa dada em troca — falo como a filhos — alargai-vos também.

[[v47-6-14]]

^<<v47-6-14,14>>^ Não vos ponhais em jugo desigual^&#42;1^ com incrédulos. Pois, que associação tem a justiça com o que é contra a lei? Ou que parceria tem a luz com a escuridão?

[NOTE]
====
. Lit.: “sejais jungidos diferentemente”.
====

[[v47-6-15]]

^<<v47-6-15,15>>^ Além disso, que harmonia há entre Cristo e Belial?^&#42;1^ Ou que quinhão tem o fiel^&#42;2^ com o incrédulo?

[NOTE]
====
. “Belial”, Vg; P46אBC: “Beliar”; Syp: “Satanás”.
. Ou “crente”.
====

[[v47-6-16]]

^<<v47-6-16,16>>^ E que acordo tem o templo^&#42;1^ de Deus com os ídolos? Pois nós somos templo dum Deus vivente; assim como Deus disse: “Residirei entre eles e andarei entre [eles], e eu serei o seu Deus, e eles serão o meu povo.”

[NOTE]
====
. Ou “habitação (morada) divina”. Gr.: na·oí, dativo, sing.; J17,18,22(hebr.): leheh·khál, “ao palácio (templo) de”.
====

[[v47-6-17]]

^<<v47-6-17,17>>^ “‘Portanto, saí do meio deles e separai-vos’, diz Jeová,^&#42;1^ ‘e cessai de tocar em coisa impura’”; “‘e eu vos acolherei’”.

[NOTE]
====
. Veja Ap. 1D.
====

[[v47-6-18]]

^<<v47-6-18,18>>^ “‘E eu serei pai para vós e vós sereis filhos e filhas para mim’, diz Jeová,^&#42;1^ o Todo-poderoso.”

[NOTE]
====
. Veja Ap. 1D.
====

'''

xref:047-2-corintios/047-2-corintios-005.adoc#v47-5-0[&#60; Capítulo Anterior] | <<v47-6-0,Topo>> | xref:047-2-corintios/047-2-corintios-007.adoc#v47-7-0[Próximo Capítulo &#62;]