include::./index.adoc[]

[[v10-13-0]]
=== 2 Samuel, 13
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v10-13-1]]

^<<v10-13-1,1>>^ E depois destas coisas aconteceu que Absalão, filho de Davi, tinha uma bela irmã, cujo nome era Tamar, e que Amnom, filho de Davi, se enamorou dela.

[[v10-13-2]]

^<<v10-13-2,2>>^ E isso era tão aflitivo para Amnom que se sentia doente por causa de Tamar, sua irmã, visto que ela era virgem e aos olhos de Amnom era difícil fazer-lhe alguma coisa.

[[v10-13-3]]

^<<v10-13-3,3>>^ Ora, Amnom tinha um companheiro de nome Jonadabe,^&#42;1^ filho de Simeá, irmão de Davi; e Jonadabe era um homem muito sábio.

[NOTE]
====
. Lit.: “Jonadabe”. Em outros lugares no M ele é chamado de “Jeonadabe”.
====

[[v10-13-4]]

^<<v10-13-4,4>>^ Portanto, ele lhe disse: “Por que estás tu, filho do rei, tão abatido assim, manhã após manhã? Não mo queres contar?” Amnom disse-lhe então: “Estou enamorado de Tamar, irmã de Absalão, meu irmão.”

[[v10-13-5]]

^<<v10-13-5,5>>^ Disse-lhe, pois, Jonadabe: “Deita-te na tua cama e finge-te doente. E teu pai virá certamente visitar-te, e tu terás de dizer-lhe: ‘Por favor, deixa que Tamar, minha irmã, entre e me dê pão, como paciente, e ela terá de fazer o pão de consolo sob os meus olhares para que eu o veja, e terei de comer da mão dela.’”

[[v10-13-6]]

^<<v10-13-6,6>>^ Concordemente, Amnom deitou-se e fingiu-se doente, e por isso veio visitá-lo o rei. Amnom disse então ao rei: “Por favor, deixa que Tamar, minha irmã, entre e coza sob os meus olhares dois bolos em forma de coração para que eu coma pão como paciente da mão dela.”

[[v10-13-7]]

^<<v10-13-7,7>>^ Então, Davi mandou dizer a Tamar, na casa: “Por favor, vai à casa de Amnom, teu irmão, e faze para ele o pão de consolo.”

[[v10-13-8]]

^<<v10-13-8,8>>^ Tamar foi, pois, à casa de Amnom, seu irmão, enquanto ele estava deitado. Ela tomou então a massa e a amassou, e sob os olhares dele fez bolos e fritou os bolos em forma de coração.^&#42;1^

[NOTE]
====
. Evidentemente similares a roscas fritas, em vez de cozidas no forno.
====

[[v10-13-9]]

^<<v10-13-9,9>>^ Por fim tomou a panela funda e a esvaziou diante dele, mas Amnom negou-se a comer e disse: “Fazei que todos se retirem de mim!” Então todos se retiraram dele.

[[v10-13-10]]

^<<v10-13-10,10>>^ Amnom disse então a Tamar: “Traze o pão do consolo ao quarto interior, para que eu o coma como paciente da tua mão.” Tamar tomou, pois, os bolos em forma de coração que tinha feito e os levou para dentro a Amnom, seu irmão, no quarto interior.

[[v10-13-11]]

^<<v10-13-11,11>>^ Quando se aproximou dele para que comesse, ele a agarrou imediatamente e lhe disse: “Vem, deita-te comigo, minha irmã.”

[[v10-13-12]]

^<<v10-13-12,12>>^ Todavia, ela lhe disse: “Não, meu irmão! Não me humilhes; pois não se costuma fazer assim em Israel. Não cometas esta ignominiosa insensatez.

[[v10-13-13]]

^<<v10-13-13,13>>^ E eu — aonde farei ir meu vitupério? E tu — tu te tornarás como um dos insensatos em Israel. E agora, por favor, fala ao rei; porque ele não me negará a ti.”

[[v10-13-14]]

^<<v10-13-14,14>>^ E ele não quis escutar a sua voz, mas usou de força superior à dela e a humilhou, e deitou-se com ela.

[[v10-13-15]]

^<<v10-13-15,15>>^ E Amnom começou a odiá-la com um ódio muito grande, porque o ódio com que a odiava era maior do que o amor com que a havia amado, de modo que Amnom lhe disse: “Levanta-te, vai embora!”

[[v10-13-16]]

^<<v10-13-16,16>>^ A isto ela lhe disse: “Não, meu irmão; pois^&#42;1^ esta maldade de me mandar embora é maior do que a outra que me fizeste!” E ele não quis escutá-la.

[NOTE]
====
. “Não, meu irmão; pois”, LXXLIt.
====

[[v10-13-17]]

^<<v10-13-17,17>>^ Com isso ele chamou seu ajudante que o servia e disse: “Por favor, manda esta pessoa embora de mim, lá para fora e tranca a porta atrás dela.”

[[v10-13-18]]

^<<v10-13-18,18>>^ (Ora, ela usava uma comprida veste listrada, pois era desta maneira que as filhas do rei, as virgens, costumavam vestir-se com túnicas sem mangas.) Portanto, seu servente passou a levá-la para fora e trancou a porta atrás dela.

[[v10-13-19]]

^<<v10-13-19,19>>^ Tamar pôs então cinzas sobre a sua cabeça, e a comprida veste listrada que usava, ela rasgou; e manteve as mãos^&#42;1^ sobre a sua cabeça e saiu andando, clamando ao andar.

[NOTE]
====
. “Mãos”, LXXVg; M: “mão”.
====

[[v10-13-20]]

^<<v10-13-20,20>>^ Então lhe disse Absalão, seu irmão: “Foi Amnom, teu irmão, que veio a estar contigo? E agora, minha irmã, fica calada. Ele é teu irmão. Não fixes teu coração neste assunto.” E Tamar começou a morar na casa de Absalão, seu irmão, todavia, afastada da associação [com outros].

[[v10-13-21]]

^<<v10-13-21,21>>^ E o próprio Rei Davi soube de todas estas coisas e ficou muito irado.

[[v10-13-22]]

^<<v10-13-22,22>>^ E Absalão não falou com Amnom nem mal nem bem; porque Absalão odiava a Amnom por causa do fato de ter humilhado a Tamar, sua irmã.

[[v10-13-23]]

^<<v10-13-23,23>>^ E resultou, depois de dois anos inteiros, que Absalão veio a ter tosquiadores em Baal-Hazor, que está perto de Efraim; e Absalão passou a convidar todos os filhos do rei.

[[v10-13-24]]

^<<v10-13-24,24>>^ Portanto, Absalão entrou até o rei e disse: “Eis que agora teu servo tem tosquiadores! Por favor, vá o rei e também seus servos juntos com teu servo.”

[[v10-13-25]]

^<<v10-13-25,25>>^ O rei disse, porém, a Absalão: “Não, meu filho! Não vamos todos, por favor, para que não te sejamos pesados.” Embora instasse com ele, não consentiu em ir, mas o abençoou.

[[v10-13-26]]

^<<v10-13-26,26>>^ Absalão disse, por fim: “Senão [tu], por favor, deixa Amnom, meu irmão, ir conosco.” A isto o rei lhe disse: “Por que devia ele ir contigo?”

[[v10-13-27]]

^<<v10-13-27,27>>^ E Absalão começou a instar com ele, de modo que mandou com ele Amnom e todos os filhos do rei.^&#42;1^

[NOTE]
====
. LXX termina o v. com: “E Absalão fez um banquete como o banquete do rei.”
====

[[v10-13-28]]

^<<v10-13-28,28>>^ Absalão ordenou então aos seus ajudantes, dizendo: “Vede, por favor, que assim que o coração de Amnom se estiver sentindo bem por causa do vinho e eu certamente vos disser: ‘Golpeai a Amnom!’ então tereis de entregá-lo à morte. Não tenhais medo. Não fui eu quem vos dei ordens? Sede fortes e mostrai-vos homens valentes.”

[[v10-13-29]]

^<<v10-13-29,29>>^ E os ajudantes de Absalão passaram a fazer a Amnom assim como Absalão lhes ordenara; e todos os outros filhos do rei começaram a levantar-se e a montar, cada um no seu mulo,^&#42;1^ e puseram-se em fuga.

[NOTE]
====
. “Seu mulo.” Hebr.: pir·dóh; esta é a primeira ocorrência desta palavra.
====

[[v10-13-30]]

^<<v10-13-30,30>>^ E sucedeu que, enquanto estavam em caminho, a própria notícia chegou a Davi, dizendo-se: “Absalão golpeou todos os filhos do rei e não sobrou nem sequer um deles.”

[[v10-13-31]]

^<<v10-13-31,31>>^ Nisto se levantou o rei e rasgou as suas roupas e deitou-se no chão, e todos os seus servos ficaram de pé com as suas roupas rasgadas.^&#42;1^

[NOTE]
====
. “E todos os seus servos que estavam em pé em volta dele rasgaram as suas roupas exteriores”, LXXVg.
====

[[v10-13-32]]

^<<v10-13-32,32>>^ Todavia, Jonadabe, filho de Simeá, irmão de Davi, respondeu e disse: “Não pense meu senhor que foram todos os moços, os filhos do rei, os que foram mortos, pois foi somente Amnom quem morreu, porque se deu às ordens de Absalão como algo estabelecido desde o dia em que humilhou a Tamar, sua irmã.

[[v10-13-33]]

^<<v10-13-33,33>>^ E agora, não tome meu senhor, o rei, ao coração a palavra que diz: ‘Morreram todos os filhos do rei’; mas foi apenas Amnom quem morreu.”

[[v10-13-34]]

^<<v10-13-34,34>>^ Entrementes, Absalão pôs-se em fuga. Mais tarde, o moço, o vigia, levantou os olhos e viu, e eis que vinha muita gente pela estrada atrás dele, do lado do monte.^&#42;1^

[NOTE]
====
. LXX acrescenta: “E o atalaia aproximou-se, e anunciou ao rei, e disse: ‘Vi homens do caminho para Horonaim do lado da montanha.’”
====

[[v10-13-35]]

^<<v10-13-35,35>>^ Jonadabe disse então ao rei: “Eis que entraram os próprios filhos do rei. Conforme a palavra do teu servo, assim sucedeu.”

[[v10-13-36]]

^<<v10-13-36,36>>^ E aconteceu que, assim que acabou de falar, eis que entraram os próprios filhos do rei, e eles começaram a levantar as suas vozes e a chorar; e até mesmo o rei e todos os seus servos choraram com um choro muito grande.

[[v10-13-37]]

^<<v10-13-37,37>>^ Quanto a Absalão, fugiu para ir ter com Talmai, filho de Amiúde, rei de Gesur. E [Davi]^&#42;1^ continuou a prantear seu filho todos os dias.

[NOTE]
====
. Inserido para identificar o sujeito do verbo; SyVg: “Davi”; LXX: “Rei Davi”; M: “ele”.
====

[[v10-13-38]]

^<<v10-13-38,38>>^ Quanto a Absalão, fugiu e seguiu caminho para Gesur; e veio a ficar lá três anos.

[[v10-13-39]]

^<<v10-13-39,39>>^ Finalmente, [a alma de]^&#42;1^ Davi, o rei, ansiava de sair^&#42;2^ até Absalão, pois se havia consolado quanto a Amnom, visto que estava morto.

[NOTE]
====
. “A alma de”, inserido para concordar com o verbo hebr. fem. para “ansiava”, ao passo que “Davi, o rei”, é masc. no hebr.; LXX: “o espírito do rei”.
. Lit.: “deixava [com anseio] de sair”.
====

'''

xref:010-2-samuel/010-2-samuel-012.adoc#v10-12-0[&#60; Capítulo Anterior] | <<v10-13-0,Topo>> | xref:010-2-samuel/010-2-samuel-014.adoc#v10-14-0[Próximo Capítulo &#62;]