include::./index.adoc[]

[[v10-16-0]]
=== 2 Samuel, 16
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v10-16-1]]

^<<v10-16-1,1>>^ Quando o próprio Davi tinha passado um pouco além do cume, eis que vinha ao seu encontro Ziba, ajudante de Mefibosete, com um par de jumentos selados e sobre eles duzentos pães, e cem tortas de passas, e cem fardos de frutas de verão, e uma grande talha de vinho.

[[v10-16-2]]

^<<v10-16-2,2>>^ O rei disse então a Ziba: “Que significam estas coisas da tua parte?” A isto Ziba disse: “Os jumentos são para os da casa do rei montar neles, e o pão e os fardos de frutas de verão são para os moços comerem, e o vinho é para o cansado no ermo beber.”

[[v10-16-3]]

^<<v10-16-3,3>>^ O rei disse então: “E onde está o filho do teu amo?”^&#42;1^ Ziba disse então ao rei: “Eis que está morando em Jerusalém; pois ele disse: ‘É hoje que a casa de Israel me dará de volta o domínio real de meu pai.’”

[NOTE]
====
. “Teu amo.” Hebr.: ’adho·neí·kha, pl. de ’a·dhóhn, para denotar excelência.
====

[[v10-16-4]]

^<<v10-16-4,4>>^ O rei disse então a Ziba: “Eis que é teu tudo o que pertence a Mefibosete.” A isto Ziba disse: “Eu deveras me curvo. Ache eu favor aos teus olhos, meu senhor, o rei.”

[[v10-16-5]]

^<<v10-16-5,5>>^ E o Rei Davi chegou até Baurim, e eis que saía de lá um homem da família da casa de Saul, cujo nome era Simei, filho de Gera, saindo e invocando o mal ao sair.

[[v10-16-6]]

^<<v10-16-6,6>>^ E ele começou a atirar pedras a Davi e a todos os servos do Rei Davi; e todo o povo e todos os poderosos estavam à sua direita e à sua esquerda.

[[v10-16-7]]

^<<v10-16-7,7>>^ E isto foi o que Simei disse ao invocar o mal: “Sai, sai, homem culpado de sangue^&#42;1^ e homem imprestável!^&#42;2^

[NOTE]
====
. Lit.: “homem de sangues”. Hebr.: ’ish had·dam·mím, pl.
. Ou “e homem de inutilidade”. Lit.: “e homem do belial”. Hebr.: we’ísh hab·beli·yá·‛al.
====

[[v10-16-8]]

^<<v10-16-8,8>>^ Jeová trouxe de volta sobre ti toda a culpa de sangue pela casa de Saul em lugar de quem tens reinado; e Jeová entrega o reinado na mão de Absalão, teu filho. E eis que estás na tua calamidade, porque és um homem culpado de sangue!”

[[v10-16-9]]

^<<v10-16-9,9>>^ Finalmente, Abisai, filho de Zeruia, disse ao rei: “Por que deve este cão morto invocar o mal sobre meu senhor, o rei? Por favor, deixa-me ir para lá e tirar-lhe a cabeça.”

[[v10-16-10]]

^<<v10-16-10,10>>^ Mas o rei disse: “Que tenho eu convosco,^&#42;1^ filhos de Zeruia? Que invoque o mal, porque o próprio Jeová lhe disse: ‘Invoca o mal sobre Davi!’ Portanto, quem^&#42;2^ dirá: ‘Por que fizeste assim?’”

[NOTE]
====
. Lit.: “Que [há] para mim e para vós?” Esta é uma expressão idiomática hebr.; é uma pergunta de repulsa, indicando objeção à ação proposta por Abisai. Veja Ap. 7B.
. Segundo Mmargem; M: “Caso ele invoque o mal e caso Jeová lhe tenha dito: ‘Invoca o mal sobre Davi!’ quem, então?”
====

[[v10-16-11]]

^<<v10-16-11,11>>^ E Davi prosseguiu, dizendo a Abisai e a todos os seus servos: “Eis que meu próprio filho que saiu das minhas próprias entranhas está procurando a minha alma; e quanto mais agora um benjaminita! Deixai-o, para que invoque o mal, pois Jeová lhe disse isso!

[[v10-16-12]]

^<<v10-16-12,12>>^ Talvez Jeová veja com o seu olho^&#42;1^ e Jeová realmente me restitua a bondade em vez de sua invocação do mal neste dia.”

[NOTE]
====
. “Com o seu olho.” Uma das Dezoito Emendas. Aqui, os soferins fizeram com que o texto rezasse: “o meu erro”, isto é, o erro cometido contra mim. LXXSyVg: “minha aflição”. Veja Ap. 2B.
====

[[v10-16-13]]

^<<v10-16-13,13>>^ Com isto Davi e seus homens foram indo pela estrada, ao passo que Simei andava do lado do monte, mantendo o passo com ele para invocar o mal; e atirava pedras ao manter o passo com ele e jogava muito pó.

[[v10-16-14]]

^<<v10-16-14,14>>^ Finalmente, o rei e todo o povo com ele chegaram, cansados. Por isso tomaram ali fôlego.

[[v10-16-15]]

^<<v10-16-15,15>>^ Quanto a Absalão e todo o povo, os homens de Israel, entraram em Jerusalém; e Aitofel estava com ele.

[[v10-16-16]]

^<<v10-16-16,16>>^ E sucedeu que, assim que Husai, o arquita, companheiro de Davi, entrou até Absalão, Husai passou a dizer a Absalão: “Viva o rei! Viva o rei!”

[[v10-16-17]]

^<<v10-16-17,17>>^ Em vista disso, Absalão disse a Husai: “É esta a tua benevolência para com o teu companheiro? Por que não foste com o teu companheiro?”

[[v10-16-18]]

^<<v10-16-18,18>>^ Husai disse, pois, a Absalão: “Não; mas daquele a quem Jeová escolheu, e também este povo, bem como todos os homens de Israel, deste virei a ser^&#42;1^ e com ele morarei.

[NOTE]
====
. Ou “mostrarei ser”. Veja Êx 3:14.
====

[[v10-16-19]]

^<<v10-16-19,19>>^ E pela segunda vez [tenho de dizer]: A quem servirei eu? Não é diante de seu filho? Assim como servi diante de teu pai, assim mostrarei ser^&#42;1^ diante de ti.”

[NOTE]
====
. Veja v. 18 n.
====

[[v10-16-20]]

^<<v10-16-20,20>>^ Mais tarde disse Absalão a Aitofel: “Dai um conselho da vossa parte. Que faremos?”

[[v10-16-21]]

^<<v10-16-21,21>>^ Aitofel disse então a Absalão: “Tem relações com as concubinas de teu pai, que ele deixou atrás para tomarem conta da casa. E todo o Israel há de ouvir que te fizeste malcheiroso para teu pai e as mãos de todos os que estão contigo certamente se fortalecerão.”

[[v10-16-22]]

^<<v10-16-22,22>>^ Conseqüentemente, armaram para Absalão uma tenda sobre o terraço e Absalão começou a ter relações com as concubinas de seu pai sob os olhares de todo o Israel.

[[v10-16-23]]

^<<v10-16-23,23>>^ E o conselho de Aitofel, com que ele aconselhava naqueles dias, era como se um homem^&#42;1^ indagasse da palavra do [verdadeiro] Deus.^&#42;2^ Assim era todo o conselho de Aitofel, tanto para Davi como para Absalão.

[NOTE]
====
. “Um homem”, 30 mss. hebr.; no M aparece apenas o sinal vocálico. Trata-se de qere, não de kethib (lido, mas não escrito). Veja Jz 20:13 n.
. “Da palavra do [verdadeiro] Deus.” Hebr.: bidh·vár ha·’Elo·hím. O artigo definido ha, “o”, que precede ao título ’Elo·hím, é para ênfase. Esta é a primeira ocorrência desta expressão. Veja Ap. 1F.
====

'''

xref:010-2-samuel/010-2-samuel-015.adoc#v10-15-0[&#60; Capítulo Anterior] | <<v10-16-0,Topo>> | xref:010-2-samuel/010-2-samuel-017.adoc#v10-17-0[Próximo Capítulo &#62;]