include::./index.adoc[]

[[v10-17-0]]
=== 2 Samuel, 17
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v10-17-1]]

^<<v10-17-1,1>>^ E Aitofel passou a dizer a Absalão: “Por favor, deixa-me escolher doze mil homens e levantar-me, e ir hoje à noite no encalço de Davi.

[[v10-17-2]]

^<<v10-17-2,2>>^ E virei sobre ele quando estiver fatigado e fraco em ambas as suas mãos, e eu certamente o farei tremer; e todo o povo que está com ele terá de fugir, e eu hei de golpear o rei quando estiver sozinho.

[[v10-17-3]]

^<<v10-17-3,3>>^ E deixa-me trazer todo o povo de volta a ti. O homem a quem procuras é equivalente ao retorno de todos; [e] o próprio povo virá todo a estar em paz.”^&#42;1^

[NOTE]
====
. Possivelmente: “E deixa-me trazer todo o povo de volta a ti, assim como a noiva volta para seu marido. Estás buscando apenas a alma de um só homem, e o próprio povo virá todo a estar em paz.” LXX concorda com isso.
====

[[v10-17-4]]

^<<v10-17-4,4>>^ E a palavra estava direita aos olhos de Absalão e aos olhos de todos os anciãos de Israel.

[[v10-17-5]]

^<<v10-17-5,5>>^ No entanto, Absalão disse: “Por favor, chamai também a Husai, o arquita, e ouçamos o que há na sua boca, sim, na dele.”

[[v10-17-6]]

^<<v10-17-6,6>>^ Portanto, Husai entrou até Absalão. Absalão disse-lhe então: “Conforme esta palavra é que falou Aitofel. Devemos agir de acordo com a sua palavra? Se não, fala tu.”

[[v10-17-7]]

^<<v10-17-7,7>>^ Então Husai disse a Absalão: “Neste caso o conselho com que Aitofel aconselhou não é bom!”

[[v10-17-8]]

^<<v10-17-8,8>>^ E Husai prosseguiu, dizendo: “Tu mesmo bem conheces teu pai e os seus homens, que são poderosos, e eles estão amargurados de alma, como a ursa que perdeu os seus filhotes no campo; e teu pai é guerreiro e não passará a noite com o povo.

[[v10-17-9]]

^<<v10-17-9,9>>^ Eis que agora está escondido num dos barrancos ou num dos outros lugares; e certamente se dará que, assim que se lançar sobre eles no início, aquele que ouvir isso forçosamente ouvirá e dirá: ‘Houve uma derrota entre o povo que segue a Absalão!’

[[v10-17-10]]

^<<v10-17-10,10>>^ E até mesmo o homem valente, cujo coração é como o coração do leão,^&#42;1^ seguramente amolecerá em fraqueza; porque todo o Israel se apercebe de que teu pai é homem poderoso, e assim também os homens valentes que estão com ele.

[NOTE]
====
. “Do leão.” Hebr.: ha·’ar·yéh, o leão africano.
====

[[v10-17-11]]

^<<v10-17-11,11>>^ Eu mesmo digo em conselho: Ajunte-se todo o Israel a ti, sem falta, desde Dã até Berseba, em multidão como as partículas de areia junto ao mar, indo a tua própria pessoa^&#42;1^ à peleja.^&#42;2^

[NOTE]
====
. Lit.: “e tua própria face”.
. Ou “à batalha”. LXXSyVg: “entre eles”.
====

[[v10-17-12]]

^<<v10-17-12,12>>^ E teremos de ir contra ele num dos lugares onde será achado com certeza, e nós mesmos estaremos sobre ele assim como o orvalho cai sobre o solo; e certamente não sobrará nem sequer um entre ele e todos os homens que estão com ele.

[[v10-17-13]]

^<<v10-17-13,13>>^ E se ele se recolher a alguma cidade, então todo o Israel terá de carregar cordas àquela cidade e nós a havemos de arrastar para baixo ao vale da torrente, até que não se ache ali nem sequer uma pedrinha.”

[[v10-17-14]]

^<<v10-17-14,14>>^ Então Absalão e todos os homens de Israel disseram: “O conselho de Husai, o arquita, é melhor do que o conselho de Aitofel!” E o próprio Jeová dera ordens para frustrar o conselho de Aitofel, embora fosse bom, a fim de que Jeová trouxesse calamidade sobre Absalão.

[[v10-17-15]]

^<<v10-17-15,15>>^ Mais tarde, Husai disse a Zadoque e a Abiatar, os sacerdotes: “Foi assim e assim que Aitofel aconselhou a Absalão e aos anciãos de Israel; e foi assim e assim que eu mesmo dei conselho.

[[v10-17-16]]

^<<v10-17-16,16>>^ E agora mandai depressa informar Davi, dizendo: ‘Não pouses esta noite nas planícies desérticas do ermo, porém, tu também deves sem falta fazer a travessia, para que o rei e todo o povo com ele não sejam tragados.’”^&#42;1^

[NOTE]
====
. Ou “para que não se comunique isso ao rei e a todo o povo que está com ele”.
====

[[v10-17-17]]

^<<v10-17-17,17>>^ Visto que Jonatã e Aimaás estavam estacionados em En-Rogel, foi uma serva e os informou, uma vez que tinham de comunicá-lo a Davi; pois não podiam aparecer entrando na cidade.

[[v10-17-18]]

^<<v10-17-18,18>>^ Todavia, chegou a vê-los um moço e informou Absalão. Assim, os dois foram depressa e chegaram à casa de um homem em Baurim, o qual tinha um poço no seu pátio; e eles desceram nele.

[[v10-17-19]]

^<<v10-17-19,19>>^ Depois, a mulher tomou uma tela e a estendeu sobre a superfície do poço, e empilhou sobre ela grãos pilados; e não se soube coisa alguma disso.

[[v10-17-20]]

^<<v10-17-20,20>>^ Os servos de Absalão chegaram então à mulher na casa dela e disseram: “Onde estão Aimaás e Jonatã?” A isto a mulher lhes disse: “Passaram adiante para as águas.” Então continuaram a procurar e não os acharam, e por isso retornaram a Jerusalém.

[[v10-17-21]]

^<<v10-17-21,21>>^ E sucedeu, depois de terem ido embora, que saíram do poço e seguiram adiante, e informaram o Rei Davi e disseram a Davi: “Levantai-vos e atravessai depressa as águas; pois, o seguinte é o que Aitofel aconselhou contra vós.”

[[v10-17-22]]

^<<v10-17-22,22>>^ Davi se levantou imediatamente, bem como todo o povo que estava com ele, e foram atravessar o Jordão até clarear a manhã, até que não faltou mais nem sequer um que não tivesse passado o Jordão.

[[v10-17-23]]

^<<v10-17-23,23>>^ Quanto a Aitofel, viu que seu conselho não tinha sido posto em prática, e ele passou a selar um jumento, e a levantar-se, e a ir para a sua casa, para a sua própria cidade. Deu então ordens aos da sua casa e estrangulou-se,^&#42;1^ e assim morreu. Foi, portanto, enterrado na sepultura de seus antepassados.

[NOTE]
====
. Ou “enforcou-se”, LXX, como em Mt 27:5.
====

[[v10-17-24]]

^<<v10-17-24,24>>^ Quanto a Davi, chegou a Maanaim, e o próprio Absalão atravessou o Jordão, ele e todos os homens de Israel com ele.

[[v10-17-25]]

^<<v10-17-25,25>>^ E foi a Amasa que Absalão pôs no lugar de Joabe sobre o exército; e Amasa era filho dum homem cujo nome era Itra, o israelita,^&#42;1^ que teve relações com Abigail, filha de Naás,^&#42;2^ irmã de Zeruia, mãe de Joabe.

[NOTE]
====
. “Israelita”, MLXXSy; LXXA e 1Cr 2:17: “ismaelita”.
. “Naás”, MLXXSyVg; LXXL e 1Cr 2:12-16: “Jessé”.
====

[[v10-17-26]]

^<<v10-17-26,26>>^ E Israel e Absalão foram acampar-se na terra de Gileade.

[[v10-17-27]]

^<<v10-17-27,27>>^ E sucedeu, assim que Davi chegou a Maanaim, que Sobi, filho de Naás, de Rabá, dos filhos de Amom, e Maquir, filho de Amiel, de Lo-Debar, e Barzilai, o gileadita de Rogelim,

[[v10-17-28]]

^<<v10-17-28,28>>^ [trouxeram]^&#42;1^ camas e bacias, e vasos de oleiro, e trigo, e cevada, e farinha, e grãos torrados, e favas, e lentilhas, e grãos tostados;

[NOTE]
====
. “Trouxeram”, LXX.
====

[[v10-17-29]]

^<<v10-17-29,29>>^ e trouxeram mel, e manteiga, e ovelhas, e requeijão de gado vacum, para Davi e o povo que estava com ele comer, pois disseram: “O povo está faminto e cansado, e está com sede no ermo.”

'''

xref:010-2-samuel/010-2-samuel-016.adoc#v10-16-0[&#60; Capítulo Anterior] | <<v10-17-0,Topo>> | xref:010-2-samuel/010-2-samuel-018.adoc#v10-18-0[Próximo Capítulo &#62;]