include::./index.adoc[]

[[v10-19-0]]
=== 2 Samuel, 19
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v10-19-1]]

^<<v10-19-1,1>>^ Mais tarde se relatou a Joabe: “Eis que o rei está chorando e está pranteando por Absalão.”

[[v10-19-2]]

^<<v10-19-2,2>>^ De modo que a salvação, naquele dia, tornou-se uma ocasião de luto por parte de todo o povo, porque o povo ouviu dizer naquele dia: “O rei se sente magoado por causa de seu filho.”

[[v10-19-3]]

^<<v10-19-3,3>>^ E o povo, naquele dia, começou a entrar furtivamente na cidade, assim como o povo anda furtivamente quando se sente desacreditado por ter fugido na batalha.

[[v10-19-4]]

^<<v10-19-4,4>>^ E o próprio rei cobriu a sua face e o rei continuou a clamar em alta voz: “Meu filho Absalão! Absalão, meu filho, meu filho!”

[[v10-19-5]]

^<<v10-19-5,5>>^ Por fim, Joabe entrou até o rei, na casa, e disse: “Hoje envergonhaste a face de todos os teus servos, os que hoje puseram a salvo a tua alma e a alma dos teus filhos e das tuas filhas, e a alma das tuas esposas e a alma das tuas concubinas,

[[v10-19-6]]

^<<v10-19-6,6>>^ amando os que te odeiam e odiando os que te amam; pois informaste hoje que chefes e servos não significam nada para ti, porque eu bem sei hoje que, se tão-somente Absalão estivesse vivo e todos nós estivéssemos hoje mortos, ora, neste caso seria direito aos teus olhos.

[[v10-19-7]]

^<<v10-19-7,7>>^ E agora, levanta-te, sai e fala diretamente ao coração dos teus servos, porque juro deveras por Jeová que, se não saíres, nenhum homem pousará esta noite contigo; e isto certamente será para ti pior do que todo o mal que te sobreveio desde a tua mocidade até agora.”

[[v10-19-8]]

^<<v10-19-8,8>>^ Por conseguinte, o rei se levantou e se sentou no portão, e informou-se a todo o povo, dizendo: “Eis que o rei está sentado no portão.” E todo o povo começou a vir perante o rei.
Quanto a Israel, haviam fugido, cada um para o seu lar.^&#42;1^

[NOTE]
====
. Lit.: “tendas”.
====

[[v10-19-9]]

^<<v10-19-9,9>>^ E todo o povo ficou envolvido em disputas, em todas as tribos de Israel, dizendo: “Foi o rei quem nos livrou da palma dos nossos inimigos e foi ele quem nos pôs a salvo da palma da mão dos filisteus; e agora fugiu do país diante de Absalão.

[[v10-19-10]]

^<<v10-19-10,10>>^ Quanto a Absalão, a quem ungimos sobre nós, morreu na batalha. Portanto, agora, por que não fazeis nada para trazer o rei de volta?”

[[v10-19-11]]

^<<v10-19-11,11>>^ Quanto ao Rei Davi, mandou dizer a Zadoque e a Abiatar, os sacerdotes, dizendo: “Falai aos anciãos de Judá, dizendo: ‘Por que devíeis tornar-vos os últimos a trazer o rei de volta à sua casa, quando a própria palavra de todo o Israel chegou até o rei na sua casa?

[[v10-19-12]]

^<<v10-19-12,12>>^ Sois meus irmãos; sois meu osso e minha carne. Portanto, por que devíeis tornar-vos os últimos a trazer de volta o rei?’

[[v10-19-13]]

^<<v10-19-13,13>>^ E a Amasa deveis dizer: ‘Não és meu osso e minha carne? Assim me faça Deus e assim lhe acrescente mais, se não te tornares o chefe do exército diante de mim para sempre, em lugar de Joabe.’”

[[v10-19-14]]

^<<v10-19-14,14>>^ E ele passou a inclinar o coração de todos os homens de Judá como de um só homem, de modo que enviaram palavra ao rei: “Retorna, tu e todos os teus servos.”

[[v10-19-15]]

^<<v10-19-15,15>>^ E o rei começou a voltar e chegou até o Jordão. Quanto a Judá, chegaram até Gilgal para ir e se encontrar com o rei, a fim de conduzir o rei através do Jordão.

[[v10-19-16]]

^<<v10-19-16,16>>^ Então Simei, filho de Gera, o benjaminita, que era de Baurim, apressou-se e desceu com os homens de Judá ao encontro do Rei Davi.

[[v10-19-17]]

^<<v10-19-17,17>>^ E havia com ele mil homens de Benjamim. (E também Ziba, ajudante da casa de Saul, e seus quinze filhos, e vinte servos seus estavam com ele, e foram bem sucedidos^&#42;1^ em chegar ao Jordão perante o rei.

[NOTE]
====
. Ou “desceram apressadamente”.
====

[[v10-19-18]]

^<<v10-19-18,18>>^ E ele^&#42;1^ atravessou o vau para fazer passar os da casa do rei e fazer o que era bom aos seus olhos.) Quanto a Simei, filho de Gera, lançou-se diante do rei quando estava para atravessar o Jordão.

[NOTE]
====
. Possivelmente: “eles”.
====

[[v10-19-19]]

^<<v10-19-19,19>>^ Ele disse então ao rei: “Não me impute meu senhor o erro e não te lembres da falta que teu servo cometeu no dia em que meu senhor, o rei, saiu^&#42;1^ de Jerusalém, de modo que o rei tome isso ao coração.

[NOTE]
====
. “[Ele] saiu.” Hebr.: ya·tsá’. Sobre esta palavra aparecem três pontinhos para indicar que se deve substituí-la por ya·tsá’·tha, “[tu] saíste”, em harmonia com outra recensão do texto hebr. e de acordo com a expressão precedente: tiz·kór, “te lembres”. Veja Ap. 2A.
====

[[v10-19-20]]

^<<v10-19-20,20>>^ Pois o teu servo sabe muito bem que sou eu que pequei; e por isso vim hoje como primeiro de toda a casa de José para descer ao encontro de meu senhor, o rei.”

[[v10-19-21]]

^<<v10-19-21,21>>^ Abisai, filho de Zeruia, respondeu imediatamente e disse: “Em troca disso, não devia Simei ser morto, visto que invocou o mal sobre o ungido^&#42;1^ de Jeová?”

[NOTE]
====
. “O ungido de.” Hebr.: meshí·ahh; gr.: khri·stón; sir.: lam·shi·hheh; lat.: chrí·sto.
====

[[v10-19-22]]

^<<v10-19-22,22>>^ Mas Davi disse: “Que tenho eu convosco,^&#42;1^ filhos de Zeruia, que hoje vos devíeis tornar meu opositor?^&#42;2^ Será hoje alguém morto em Israel? Pois, não sei muito bem que hoje sou rei sobre Israel?”

[NOTE]
====
. Lit.: “Que [há] para mim e para vós?” Esta é uma expressão idiomática hebr.; é uma pergunta de repulsa, indicando objeção à ação proposta por Abisai. Veja Ap. 7B.
. “Opositor.” Hebr.: lesa·tán; sir.: sa·ta·na’; lat.: Sá·tan.
====

[[v10-19-23]]

^<<v10-19-23,23>>^ O rei disse então a Simei: “Não morrerás.” E o rei passou a jurar-lhe.

[[v10-19-24]]

^<<v10-19-24,24>>^ Quanto a Mefibosete, neto de Saul,^&#42;1^ desceu ao encontro do rei, e ele não tinha cuidado dos seus pés, nem tinha cuidado do seu bigode, nem tinha lavado as suas roupas desde o dia em que o rei foi embora até o dia em que veio em paz.

[NOTE]
====
. “Filho do filho de Saul”, LXXB; Sy: “filho de Jonatã, filho de Saul”; MVg: “filho de Saul”.
====

[[v10-19-25]]

^<<v10-19-25,25>>^ E sucedeu que, quando chegou a Jerusalém para se encontrar com o rei, então o rei lhe disse: “Por que não foste comigo, Mefibosete?”

[[v10-19-26]]

^<<v10-19-26,26>>^ A isto ele disse: “Meu senhor, o rei, foi meu servo quem me logrou. Pois o teu servo havia dito: ‘Deixa-me selar para mim a jumenta, para que eu monte nela e vá com^&#42;1^ o rei’, visto que o teu servo é coxo.

[NOTE]
====
. “Com”, MLXXSyVg; cerca de 60 mss. hebr.: “ao”.
====

[[v10-19-27]]

^<<v10-19-27,27>>^ De modo que ele caluniou o teu servo diante do meu senhor, o rei. Meu senhor, o rei, porém, é como um anjo do [verdadeiro] Deus, e, portanto, faze o que for bom aos teus olhos.

[[v10-19-28]]

^<<v10-19-28,28>>^ Porque todos os da casa de meu pai se teriam tornado nada mais que condenados à morte^&#42;1^ para meu senhor, o rei, e no entanto, puseste teu servo entre os que comem à tua mesa. Portanto, que direito tenho ainda de mesmo clamar mais ao rei?”

[NOTE]
====
. Lit.: “nada mais que homens da morte”.
====

[[v10-19-29]]

^<<v10-19-29,29>>^ No entanto, o rei disse-lhe: “Por que falas ainda as tuas palavras? Eu digo deveras: Tu e Ziba deveis compartilhar o campo.”

[[v10-19-30]]

^<<v10-19-30,30>>^ Então Mefibosete disse ao rei: “Que ele fique até com o inteiro, agora que meu senhor, o rei, veio em paz para a sua casa.”

[[v10-19-31]]

^<<v10-19-31,31>>^ E o próprio Barzilai, o gileadita, desceu de Rogelim, a fim de passar adiante para o Jordão com o rei, para escoltá-lo até o Jordão.

[[v10-19-32]]

^<<v10-19-32,32>>^ E Barzilai era muito idoso, tendo oitenta anos de idade; e ele mesmo supriu o rei de alimento enquanto morava em Maanaim, pois o homem era muito grande.

[[v10-19-33]]

^<<v10-19-33,33>>^ O rei disse, pois, a Barzilai: “Atravessa tu mesmo comigo e eu te hei de suprir de alimento comigo em Jerusalém.”

[[v10-19-34]]

^<<v10-19-34,34>>^ Mas Barzilai disse ao rei: “Como é que são os dias dos anos da minha vida, que eu devia subir com o rei a Jerusalém?

[[v10-19-35]]

^<<v10-19-35,35>>^ Tenho hoje oitenta anos de idade. Poderia eu distinguir entre o bom e o mau, ou poderia teu servo saborear o que comer ou o que beber, ou poderia ainda escutar a voz de cantores e de cantoras? Portanto, por que devia teu servo tornar-se ainda uma carga para meu senhor, o rei?

[[v10-19-36]]

^<<v10-19-36,36>>^ Pois, foi só um pouco que o teu servo pôde levar o rei até o Jordão, e por que devia o rei compensar-me com tal recompensa?

[[v10-19-37]]

^<<v10-19-37,37>>^ Por favor, deixa o teu servo voltar e deixa-me morrer na minha cidade perto da sepultura de meu pai e de minha mãe. Mas, eis o teu servo Quimão. Atravesse ele com o meu senhor, o rei; e faze com ele o que for bom aos teus olhos.”

[[v10-19-38]]

^<<v10-19-38,38>>^ Por conseguinte, o rei disse: “Quimão atravessará comigo e eu mesmo farei com ele o que for bom aos teus olhos; e tudo o que escolheres impor-me farei para ti.”

[[v10-19-39]]

^<<v10-19-39,39>>^ Todo o povo começou então a atravessar o Jordão e o próprio rei atravessou; mas o rei beijou Barzilai e o abençoou, após o que este voltou ao seu lugar.

[[v10-19-40]]

^<<v10-19-40,40>>^ Quando o rei atravessou para Gilgal, atravessou com ele o próprio Quimão e também todo o povo de Judá, bem como metade do povo de Israel, para fazerem o rei atravessar.

[[v10-19-41]]

^<<v10-19-41,41>>^ E eis que vinham todos os homens de Israel ao rei e passaram a dizer ao rei: “Por que te furtaram os nossos irmãos, os homens de Judá, para fazerem o rei e os da sua casa, bem como todos os homens de Davi com ele, passar o Jordão?”

[[v10-19-42]]

^<<v10-19-42,42>>^ Então responderam todos os homens de Judá aos homens de Israel: “Porque o rei é intimamente aparentado conosco;^&#42;1^ e por que é que vos irastes por causa deste assunto? Acaso temos comido às custas do rei ou nos foi trazido algum presente?”

[NOTE]
====
. Lit.: “comigo”, em sentido coletivo.
====

[[v10-19-43]]

^<<v10-19-43,43>>^ No entanto, os homens de Israel responderam aos homens de Judá e disseram: “Nós^&#42;1^ temos dez partes no rei, de modo que até mesmo em Davi somos mais do que vós.^&#42;2^ Então, por que nos^&#42;3^ tratastes com desprezo e por que não veio o nosso^&#42;4^ assunto em primeiro lugar para trazermos de volta o nosso rei?” Mas a palavra dos homens de Judá foi mais dura do que a palavra dos homens de Israel.

[NOTE]
====
. Lit.: “Eu”, em sentido coletivo.
. “Eu tenho dez partes no rei, e eu sou o primogênito em vez de o seres tu, e assim, em Davi, estou acima de ti”, LXX.
. Lit.: “me”.
. Lit.: “meu”.
====

'''

xref:010-2-samuel/010-2-samuel-018.adoc#v10-18-0[&#60; Capítulo Anterior] | <<v10-19-0,Topo>> | xref:010-2-samuel/010-2-samuel-020.adoc#v10-20-0[Próximo Capítulo &#62;]