include::./index.adoc[]

[[v10-18-0]]
=== 2 Samuel, 18
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v10-18-1]]

^<<v10-18-1,1>>^ E Davi passou a contar o povo que estava com ele e a colocar sobre eles chefes de mil e chefes de cem.

[[v10-18-2]]

^<<v10-18-2,2>>^ Além disso, Davi enviou um terço do povo debaixo da mão de Joabe, e um terço debaixo da mão de Abisai, filho de Zeruia, irmão de Joabe, e um terço debaixo da mão de Itai, o geteu. O rei disse então ao povo: “Eu mesmo também sairei sem falta convosco.”

[[v10-18-3]]

^<<v10-18-3,3>>^ O povo disse, porém: “Não deves sair, pois, se realmente fugirmos, não fixarão seu coração em nós; e se metade de nós morrer, não fixarão seu coração em nós, porque tu vales dez mil de nós; e agora, seria melhor se nos prestasses serviço dando ajuda desde a cidade.”

[[v10-18-4]]

^<<v10-18-4,4>>^ Portanto, o rei lhes disse: “Farei o que parecer bem aos vossos olhos.” E o rei ficou de pé ao lado do portão e o povo todo saiu por centenas e por milhares.

[[v10-18-5]]

^<<v10-18-5,5>>^ E o rei passou a ordenar a Joabe e a Abisai, e a Itai, dizendo: “Tratai suavemente o moço Absalão, por minha causa.” E o povo todo ouviu quando o rei deu ordens a todos os seus chefes no assunto de Absalão.

[[v10-18-6]]

^<<v10-18-6,6>>^ E o povo continuou saindo ao campo para enfrentar Israel; e a batalha veio a ser na floresta de Efraim.^&#42;1^

[NOTE]
====
. “Efraim”, MLXXVg; LXXL: “Maanaim”.
====

[[v10-18-7]]

^<<v10-18-7,7>>^ Finalmente foi derrotado ali o povo de Israel diante dos servos de Davi e a matança ali resultou ser grande naquele dia, sendo de vinte mil homens.

[[v10-18-8]]

^<<v10-18-8,8>>^ E a batalha ali se espalhou sobre toda a terra que se via. Outrossim, a floresta fez mais em devorar o povo do que a espada fez em devorá-lo naquele dia.

[[v10-18-9]]

^<<v10-18-9,9>>^ Por fim, Absalão achou-se diante dos servos de Davi. E Absalão montava num mulo, e o mulo entrou debaixo dum entrelaçamento de ramos duma grande árvore maciça, de modo que a sua cabeça ficou presa na grande árvore, e ele ficou suspenso entre os céus e a terra, ao passo que o próprio mulo debaixo dele foi para diante.

[[v10-18-10]]

^<<v10-18-10,10>>^ Então certo homem viu isso e o contou a Joabe, e disse: “Eis que vi Absalão pendurado numa grande árvore.”

[[v10-18-11]]

^<<v10-18-11,11>>^ Joabe disse então ao homem que lhe contava isso: “E eis que o viste e não o golpeaste lá por terra? Então teria sido a minha obrigação dar-te dez moedas de prata e um cinto.”

[[v10-18-12]]

^<<v10-18-12,12>>^ Mas o homem disse a Joabe: “E mesmo que se me pesasse nas minhas palmas mil moedas de prata, não estenderia a minha mão contra o filho do rei; pois, foi aos nossos ouvidos^&#42;1^ que o rei ordenou a ti e a Abisai, e a Itai, dizendo: ‘Quem quer [que seja], guardai-me o moço Absalão.’

[NOTE]
====
. Lit.: “orelhas”.
====

[[v10-18-13]]

^<<v10-18-13,13>>^ Senão eu teria agido traiçoeiramente contra a sua alma e o assunto inteiro não teria ficado oculto ao rei, e tu mesmo terias ficado de lado.”

[[v10-18-14]]

^<<v10-18-14,14>>^ A isto disse Joabe: “Não me detenha eu assim diante de ti!” Com isso tomou três hastes^&#42;1^ na sua palma e passou a traspassar com elas o coração de Absalão enquanto estava ainda vivo no coração da grande árvore.

[NOTE]
====
. Ou “armas”. Lit.: “varas”.
====

[[v10-18-15]]

^<<v10-18-15,15>>^ Então dez ajudantes que carregavam as armas de Joabe vieram dar volta e golpearam a Absalão, a fim de o entregarem à morte.

[[v10-18-16]]

^<<v10-18-16,16>>^ Joabe tocou então a buzina para que o povo voltasse de perseguir Israel; porque Joabe tinha refreado o povo.

[[v10-18-17]]

^<<v10-18-17,17>>^ Finalmente tomaram Absalão e o lançaram num grande barranco na floresta, e erigiram sobre ele uma pilha muito grande de pedras. Quanto a todo o Israel, fugiram, cada homem para o seu lar.^&#42;1^

[NOTE]
====
. Lit.: “tenda”.
====

[[v10-18-18]]

^<<v10-18-18,18>>^ Ora, o próprio Absalão, enquanto vivia, havia tomado e passado a erigir para si uma coluna, que está na Baixada do Rei, pois disse: “Não tenho filho para fazer meu nome ser lembrado.” De modo que chamou a coluna pelo seu próprio nome e ela continua a ser chamada de Monumento de Absalão até o dia de hoje.

[[v10-18-19]]

^<<v10-18-19,19>>^ Ora, no que se refere a Aimaás, filho de Zadoque, disse ele: “Por favor, deixa-me correr e levar a nova ao rei, porque Jeová o julgou [para livrá-lo] da mão dos seus inimigos.”

[[v10-18-20]]

^<<v10-18-20,20>>^ Mas Joabe lhe disse: “Neste dia não és homem de novas, e terás de levar as novas num outro dia; mas neste dia não deves levar as novas, pela razão de que^&#42;1^ morreu o próprio filho do rei.”

[NOTE]
====
. “Pela razão de que.” Hebr.: ki-‛a·lé. M tem sinais vocálicos para indicar a leitura de ki-‛al-kén, como em alguns mss. hebr. Trata-se de qere, não de kethib (lido, mas não escrito). Veja Jz 20:13 n.
====

[[v10-18-21]]

^<<v10-18-21,21>>^ Joabe disse então ao cusita: “Vai, comunica ao rei o que viste.” Então o cusita se curvou diante de Joabe e começou a correr.

[[v10-18-22]]

^<<v10-18-22,22>>^ Aimaás, filho de Zadoque, disse então mais uma vez a Joabe: “Agora, aconteça o que acontecer, por favor, deixa-me também correr atrás do cusita.” Todavia, Joabe disse: “Por que é que tu mesmo tens de correr, meu filho, quando não se acham novas para ti?”

[[v10-18-23]]

^<<v10-18-23,23>>^ [Contudo, ele disse:]^&#42;1^ “Ora, aconteça o que acontecer, deixa-me correr.” Ele lhe disse, pois: “Corre!” E Aimaás começou a correr pelo caminho do Distrito^&#42;2^ e por fim ultrapassou o cusita.

[NOTE]
====
. “Contudo, ele disse”, LXXSyVg.
. Ou “Bacia”. Veja Gên 13:10 n.: “Distrito”.
====

[[v10-18-24]]

^<<v10-18-24,24>>^ Ora, Davi estava sentado entre os dois portões. Entrementes, o vigia subiu ao terraço do portão na muralha. Por fim, ele levantou os olhos e olhou, e eis um homem correndo sozinho.

[[v10-18-25]]

^<<v10-18-25,25>>^ Portanto, o vigia chamou e informou o rei, a que o rei disse: “Se estiver sozinho, há novas na sua boca.” E ele vinha, aproximando-se cada vez mais.

[[v10-18-26]]

^<<v10-18-26,26>>^ O vigia viu então outro homem correndo. O vigia chamou por isso o porteiro e disse: “Eis que vem outro homem correndo sozinho!” a que o rei disse: “Este também é portador de novas.”

[[v10-18-27]]

^<<v10-18-27,27>>^ E o vigia prosseguiu, dizendo: “Vejo que o modo de correr do primeiro é como o modo de correr de Aimaás, filho de Zadoque”, ao que o rei disse: “Este é um homem bom e deve vir com boas novas.”

[[v10-18-28]]

^<<v10-18-28,28>>^ Por fim, Aimaás clamou e disse ao rei: “Tudo bem!”^&#42;1^ Com isso se curvou diante do rei com o rosto por terra. E prosseguiu, dizendo: “Bendito seja Jeová, teu Deus, que entregou os homens que levantaram a sua mão contra meu senhor, o rei!”

[NOTE]
====
. “Tudo bem!” Hebr.: sha·lóhm, “Paz!”. Veja vv. 29, 32.
====

[[v10-18-29]]

^<<v10-18-29,29>>^ No entanto, o rei disse: “Vai bem ao moço Absalão?” A isto Aimaás disse: “Vi uma grande comoção no momento em que Joabe enviou o servo do rei e teu servo, e eu não sabia o que era.”

[[v10-18-30]]

^<<v10-18-30,30>>^ O rei disse, pois: “Põe-te de lado, toma a tua posição aqui.” Assim se pôs de lado e ficou de pé.

[[v10-18-31]]

^<<v10-18-31,31>>^ E eis que vinha o cusita, e o cusita começou a dizer: “Aceite meu senhor, o rei, as novas, pois Jeová te julgou hoje [para te livrar] da mão de todos os que se levantam contra ti.”

[[v10-18-32]]

^<<v10-18-32,32>>^ Mas o rei disse ao cusita: “Vai bem ao moço Absalão?” A isto o cusita disse: “Que os inimigos do meu senhor, o rei, e todos os que se levantaram contra ti para o mal se tornem como o moço.”^&#42;1^

[NOTE]
====
. MLXX terminam aqui o capítulo 18.
====

[[v10-18-33]]

^<<v10-18-33,33>>^ Então o rei ficou comovido e subiu ao quarto de terraço por cima do portão, e entregou-se ao choro; e era isto o que dizia ao caminhar: “Meu filho Absalão, meu filho, meu filho Absalão! Oh! que eu, eu mesmo, tivesse morrido em teu lugar, Absalão, meu filho, meu filho!”

'''

xref:010-2-samuel/010-2-samuel-017.adoc#v10-17-0[&#60; Capítulo Anterior] | <<v10-18-0,Topo>> | xref:010-2-samuel/010-2-samuel-019.adoc#v10-19-0[Próximo Capítulo &#62;]