include::./index.adoc[]

[[v10-5-0]]
=== 2 Samuel, 5
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v10-5-1]]

^<<v10-5-1,1>>^ Com o tempo, todas as tribos de Israel vieram a Davi, a Hébron, e disseram: “Eis que nós mesmos somos teu osso e tua carne.

[[v10-5-2]]

^<<v10-5-2,2>>^ Tanto ontem como anteriormente, quando sucedia que Saul era rei sobre nós, tu mesmo te tornaste aquele que fazia Israel sair e o fazia entrar. E Jeová passou a dizer-te: ‘És tu que pastorearás meu povo Israel e és tu que te tornarás líder de Israel.’”

[[v10-5-3]]

^<<v10-5-3,3>>^ Vieram, pois, todos os anciãos de Israel ao rei em Hébron e o Rei Davi concluiu com eles um pacto em Hébron, perante Jeová; depois ungiram a Davi rei sobre Israel.^&#42;1^

[NOTE]
====
. “Sobre Israel”, MSyVg; LXX: “sobre Israel como um todo”.
====

[[v10-5-4]]

^<<v10-5-4,4>>^ Davi tinha trinta anos de idade quando se tornou rei. Reinou por quarenta anos.

[[v10-5-5]]

^<<v10-5-5,5>>^ Em Hébron reinou sobre Judá por sete anos e seis meses; e em Jerusalém reinou por trinta e três anos sobre todo o Israel e Judá.

[[v10-5-6]]

^<<v10-5-6,6>>^ Por conseguinte, o rei e seus homens foram a Jerusalém contra os jebuseus que habitavam no país, e estes começaram a dizer a Davi: “Aqui não entrarás, mas os cegos e os coxos hão de repelir-te”, pensando: “Davi não entrará aqui.”

[[v10-5-7]]

^<<v10-5-7,7>>^ Todavia, Davi passou a capturar a fortaleza de Sião, isto é, a Cidade de Davi.

[[v10-5-8]]

^<<v10-5-8,8>>^ De modo que Davi disse naquele dia: “Aquele que golpear os jebuseus estabeleça contato por meio do túnel de água tanto com os coxos como com os cegos que são odiosos para a alma de Davi!” Por isso é que se diz: “O cego e o coxo não entrarão na casa.”

[[v10-5-9]]

^<<v10-5-9,9>>^ E Davi passou a morar na fortaleza e ela veio a ser chamada de Cidade de Davi; e Davi começou a construir em todo o redor, desde o Aterro^&#42;1^ e para dentro.

[NOTE]
====
. Lit.: “o Milo (aterro)”. Hebr.: ham·mil·lóh’. Possivelmente uma construção semelhante a uma cidadela.
====

[[v10-5-10]]

^<<v10-5-10,10>>^ Davi foi assim ficando cada vez maior e Jeová, o Deus dos exércitos,^&#42;1^ era com ele.

[NOTE]
====
. “E Jeová, o Deus dos exércitos.” Hebr.: wa·Yhwáh ’Elo·héh tseva·’óhth; esta é a primeira ocorrência desta expressão. Veja 1Rs 19:10, 14.
====

[[v10-5-11]]

^<<v10-5-11,11>>^ E Hirão, rei de Tiro, passou a enviar mensageiros a Davi, bem como cedros e trabalhadores em madeira e trabalhadores em pedra para os muros, e eles começaram a construir uma casa para Davi.

[[v10-5-12]]

^<<v10-5-12,12>>^ E Davi ficou sabendo que Jeová o estabelecera firmemente como rei sobre Israel e que exaltara seu reino por causa do seu povo Israel.

[[v10-5-13]]

^<<v10-5-13,13>>^ No ínterim, Davi tomava mais concubinas e esposas de Jerusalém, depois de ter chegado de Hébron; e continuaram a nascer a Davi mais filhos e filhas.

[[v10-5-14]]

^<<v10-5-14,14>>^ E estes são os nomes dos que lhe nasceram em Jerusalém: Samua, e Sobabe, e Natã, e Salomão,

[[v10-5-15]]

^<<v10-5-15,15>>^ e Ibar, e Elisua, e Nefegue, e Jafia,

[[v10-5-16]]

^<<v10-5-16,16>>^ e Elisama, e Eliada, e Elifelete.

[[v10-5-17]]

^<<v10-5-17,17>>^ E os filisteus chegaram a ouvir que haviam ungido a Davi rei sobre Israel. Em vista disso subiram todos os filisteus para procurar a Davi. Quando Davi ouviu isso, então desceu ao lugar de difícil acesso.

[[v10-5-18]]

^<<v10-5-18,18>>^ E os filisteus, da sua parte, entraram e andaram percorrendo a baixada de Refaim.

[[v10-5-19]]

^<<v10-5-19,19>>^ E Davi começou a indagar de Jeová, dizendo: “Devo subir contra os filisteus? Entregar-mos-ás na mão?” A isto Jeová disse a Davi: “Sobe, porque sem falta entregarei os filisteus nas tuas mãos.”

[[v10-5-20]]

^<<v10-5-20,20>>^ Portanto, Davi chegou a Baal-Perazim e Davi foi golpeá-los ali. Por isso ele disse: “Jeová irrompeu através dos meus inimigos na minha frente, como uma brecha feita por águas.” É por isso que chamou aquele lugar pelo nome de Baal-Perazim.^&#42;1^

[NOTE]
====
. Significando “Senhor das Rupturas”.
====

[[v10-5-21]]

^<<v10-5-21,21>>^ Por conseguinte, deixaram ali os seus ídolos,^&#42;1^ e Davi e seus homens os levaram assim embora.

[NOTE]
====
. “Ídolos”, MSyVg; LXX e 1Cr 14:12: “deuses”.
====

[[v10-5-22]]

^<<v10-5-22,22>>^ Mais tarde, os filisteus subiram mais uma vez e andaram percorrendo a baixada de Refaim.

[[v10-5-23]]

^<<v10-5-23,23>>^ Em vista disso, Davi indagou de Jeová, mas ele disse: “Não deves subir. Vai em contorno até a retaguarda deles, e tens de chegar a eles defronte dos lentiscos.^&#42;1^

[NOTE]
====
. “Lentiscos.” Hebr.: bekha·’ím, pl.; LXX: “lugar de choro”.
====

[[v10-5-24]]

^<<v10-5-24,24>>^ E suceda que, quando ouvires o ruído de marcha^&#42;1^ nas copas dos lentiscos, nesta hora age com determinação, porque nesta hora Jeová terá ido na tua frente para golpear o acampamento dos filisteus.”

[NOTE]
====
. “Da marcha”, em 1Cr 14:15.
====

[[v10-5-25]]

^<<v10-5-25,25>>^ Por conseguinte, Davi fez assim, exatamente como Jeová lhe ordenara, e ele foi golpear os filisteus desde Geba^&#42;1^ até Gezer.

[NOTE]
====
. “Desde Geba.” Hebr.: mig·Gé·va‛; gr.: Ga·ba·ón; em 1Cr 14:16: “Gibeão”.
====

'''

xref:010-2-samuel/010-2-samuel-004.adoc#v10-4-0[&#60; Capítulo Anterior] | <<v10-5-0,Topo>> | xref:010-2-samuel/010-2-samuel-006.adoc#v10-6-0[Próximo Capítulo &#62;]