include::./index.adoc[]

[[v10-24-0]]
=== 2 Samuel, 24
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v10-24-1]]

^<<v10-24-1,1>>^ E novamente veio a acender-se a ira de Jeová contra Israel, quando se^&#42;1^ instigou Davi^&#42;2^ contra eles, dizendo: “Vai, faze a contagem de Israel e de Judá.”

[NOTE]
====
. Ou “ele”. Veja 1Cr 21:1.
. Ou “quando Davi foi instigado”.
====

[[v10-24-2]]

^<<v10-24-2,2>>^ O rei disse, pois, a Joabe, chefe^&#42;1^ das forças militares, que estava com ele:^&#42;2^ “Por favor, percorre todas as tribos de Israel, desde Dã até Berseba, e registrai o povo, e eu hei de saber o número do povo.”

[NOTE]
====
. “Chefe das.” Hebr.: sar; LXX: “governante”; Vg: “príncipe”.
. “A Joabe e aos chefes das forças militares que estavam com ele”, LXXL. Veja o v. 4; 1Cr 21:2.
====

[[v10-24-3]]

^<<v10-24-3,3>>^ Mas Joabe disse ao rei: “Acrescente Jeová, teu Deus, ainda cem vezes mais do que são, vendo-o os próprios olhos do meu senhor, o rei. Mas, quanto ao meu senhor, o rei, por que se deleitou nesta coisa?”

[[v10-24-4]]

^<<v10-24-4,4>>^ Por fim prevaleceu a palavra do rei sobre Joabe e os chefes das forças militares. Portanto, Joabe e os chefes das forças militares saíram de diante do rei para registrar o povo de Israel.

[[v10-24-5]]

^<<v10-24-5,5>>^ Cruzaram então o Jordão e foram acampar-se em Aroer, à direita da cidade^&#42;1^ que está no meio do vale da torrente, em direção aos gaditas e a Jázer.

[NOTE]
====
. “Foram acampar-se em Aroer, à direita da cidade”, M; LXXL: “começaram em Aroer e na cidade”; Vg: “chegaram a Aroer, à direita da cidade”.
====

[[v10-24-6]]

^<<v10-24-6,6>>^ Depois chegaram a Gileade e à terra de Tatim-Hodsi,^&#42;1^ e seguiram para Dã-Jaã e deram volta até Sídon.

[NOTE]
====
. “Terra de Tatim-Hodsi”, M; LXXL: “terra dos hititas em direção a Cades”.
====

[[v10-24-7]]

^<<v10-24-7,7>>^ Chegaram então à praça forte de Tiro e a todas as cidades dos heveus e dos cananeus, e chegaram ao ponto final no Negebe de Judá, em Berseba.

[[v10-24-8]]

^<<v10-24-8,8>>^ Assim percorreram todo o país e chegaram a Jerusalém ao fim de nove meses e vinte dias.

[[v10-24-9]]

^<<v10-24-9,9>>^ Joabe deu então ao rei o número do registro do povo; e Israel somou oitocentos mil homens valentes que puxavam da espada, e os homens de Judá eram quinhentos mil homens.

[[v10-24-10]]

^<<v10-24-10,10>>^ E o coração de Davi começou a bater nele depois de ter contado o povo. Por conseguinte, Davi disse a Jeová: “Pequei muitíssimo naquilo que fiz. E agora, Jeová, por favor, deixa passar o erro do teu servo; pois agi muito nesciamente.”

[[v10-24-11]]

^<<v10-24-11,11>>^ Quando Davi passou a levantar-se de manhã, veio a própria palavra de Jeová a Gade, o profeta, visionário de Davi, dizendo:

[[v10-24-12]]

^<<v10-24-12,12>>^ “Vai,^&#42;1^ e tens de dizer a Davi: ‘Assim disse Jeová: “Três coisas te imponho. Escolhe para ti uma delas, para que eu ta faça.”’”

[NOTE]
====
. Lit.: “Ir-se-á.” No hebr., este verbo está no infinitivo absoluto, indefinido quanto ao tempo e impessoal.
====

[[v10-24-13]]

^<<v10-24-13,13>>^ Concordemente, Gade entrou até Davi e informou-o, e disse-lhe: “Devem vir sobre ti sete^&#42;1^ anos de fome na tua terra, ou três meses em que foges diante dos teus adversários, perseguindo-te eles, ou a ocorrência de três dias de pestilência^&#42;2^ na tua terra? Agora sabe e vê o que devo responder Àquele que me envia.”

[NOTE]
====
. “Sete”, MSyVg; LXX e 1Cr 21:12: “três”.
. Ou “peste (bubônica)”. Lat.: pe·sti·lén·ti·a; LXX: “morte (praga mortífera)”.
====

[[v10-24-14]]

^<<v10-24-14,14>>^ Por isso Davi disse a Gade: “É muito aflitivo para mim. Por favor, caiamos na mão de Jeová, porque são muitas as suas misericórdias; mas não caia eu na mão dum homem.”^&#42;1^

[NOTE]
====
. “Homem.” Hebr.: ’a·dhám. LXX acrescenta: “E Davi escolheu a praga mortífera. (15) E eram os dias da colheita do trigo.”
====

[[v10-24-15]]

^<<v10-24-15,15>>^ Jeová deu então uma pestilência em Israel, desde a manhã até o tempo designado, de modo que pereceram dentre o povo setenta mil pessoas, desde Dã até Berseba.

[[v10-24-16]]

^<<v10-24-16,16>>^ E o anjo estava estendendo sua mão para Jerusalém, a fim de a arruinar; e Jeová começou a deplorar a calamidade e por isso disse ao anjo que causava a ruína entre o povo: “Basta! Abaixe-se agora a tua mão.” E sucedeu que o próprio anjo de Jeová estava perto da eira de Araúna, o jebuseu.

[[v10-24-17]]

^<<v10-24-17,17>>^ E Davi passou a dizer a Jeová, ao ver o anjo que golpeava o povo, sim, passou a dizer: “Eis que fui eu que pequei e fui eu que cometi a falta; mas estas ovelhas — que fizeram elas? Por favor, venha a tua mão sobre mim e sobre a casa de meu pai.”

[[v10-24-18]]

^<<v10-24-18,18>>^ Mais tarde, naquele dia, entrou Gade até Davi e disse-lhe: “Sobe, erige para Jeová um altar na eira de Araúna, o jebuseu.”

[[v10-24-19]]

^<<v10-24-19,19>>^ E Davi começou a subir de acordo com a palavra de Gade, segundo o que Jeová havia ordenado.

[[v10-24-20]]

^<<v10-24-20,20>>^ Quando Araúna olhou para baixo e viu o rei e seus servos avançar para ele, Araúna saiu imediatamente e se curvou diante do rei com o seu rosto por terra.

[[v10-24-21]]

^<<v10-24-21,21>>^ Araúna disse então: “Por que veio meu senhor, o rei, ao seu servo?” A isto Davi disse: “Para comprar de ti a eira, a fim de se construir um altar a Jeová, para que se faça parar o flagelo sobre o povo.”

[[v10-24-22]]

^<<v10-24-22,22>>^ Mas Araúna disse a Davi: “Tome-a meu senhor, o rei, e ofereça ele o que for bom aos seus olhos. Vê, o gado vacum para a oferta queimada, bem como o trenó debulhador e a apeiragem do gado, como lenha.

[[v10-24-23]]

^<<v10-24-23,23>>^ Tudo, ó rei, Araúna^&#42;1^ dá ao rei.” E Araúna prosseguiu, dizendo ao rei: “Mostre Jeová, teu Deus, ter prazer em ti.”

[NOTE]
====
. Ou: “Tudo Araúna, como rei.”
====

[[v10-24-24]]

^<<v10-24-24,24>>^ No entanto, o rei disse a Araúna: “Não, mas sem falta a comprarei de ti por um preço; e não oferecerei sacrifícios queimados a Jeová, meu Deus, sem custo.” Por conseguinte, Davi comprou a eira e o gado por cinqüenta siclos de prata.^&#42;1^

[NOTE]
====
. Para calcular o valor, veja Ap. 8A.
====

[[v10-24-25]]

^<<v10-24-25,25>>^ E Davi passou a construir ali um altar a Jeová e a oferecer sacrifícios queimados e sacrifícios de participação em comum, e Jeová começou a deixar-se suplicar a favor da terra, de modo que se fez parar o flagelo sobre Israel.

'''

xref:010-2-samuel/010-2-samuel-023.adoc#v10-23-0[&#60; Capítulo Anterior] | <<v10-24-0,Topo>> | xref:011-1-reis/011-1-reis-001.adoc#v11-1-0[Próximo Capítulo &#62;]