include::./index.adoc[]

[[v10-20-0]]
=== 2 Samuel, 20
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v10-20-1]]

^<<v10-20-1,1>>^ Ora, achava-se ali um homem imprestável,^&#42;1^ cujo nome era Seba, filho de Bicri, benjaminita; e ele passou a tocar a buzina e a dizer: “Não temos quinhão em Davi e não temos herança no filho de Jessé. Cada um aos seus deuses,^&#42;2^ ó Israel!”

[NOTE]
====
. Ou “patife”. Lit.: “homem de belial (inutilidade)”.
. “Aos seus deuses.” Lit.: “às suas tendas”. Hebr.: le’o·ha·láv. Esta é uma das Dezoito Emendas dos soferins, tendo o texto original hebr. supostamente rezado le’·lo·háv (de ’elo·hím, “deuses” ou “Deus”). Veja Ap. 2B.
====

[[v10-20-2]]

^<<v10-20-2,2>>^ Em vista disso, todos os homens de Israel começaram a subir [deixando] de seguir a Davi para seguir a Seba, filho de Bicri; mas, quanto aos homens de Judá, apegaram-se ao seu rei, desde o Jordão até Jerusalém.

[[v10-20-3]]

^<<v10-20-3,3>>^ Por fim chegou Davi à sua casa em Jerusalém. O rei tomou então as dez mulheres, as concubinas que deixara atrás para tomarem conta da casa, e as pôs numa casa de custódia, mas continuou a suprir-lhes alimento. E não teve mais relações com elas, mas elas continuaram encerradas até o dia da sua morte, em viuvez com um [marido] vivo.^&#42;1^

[NOTE]
====
. Lit.: “[em] viuvez de vivência”, M; LXX: “viúvas viventes”; Vg: “vivendo em viuvez”.
====

[[v10-20-4]]

^<<v10-20-4,4>>^ O rei disse então a Amasa: “Convoca os homens de Judá a mim dentro de três dias, e tu mesmo fica de pé aqui.”

[[v10-20-5]]

^<<v10-20-5,5>>^ Portanto, Amasa foi convocar Judá; mas, tardou mais do que o tempo marcado que se lhe tinha designado.

[[v10-20-6]]

^<<v10-20-6,6>>^ Davi disse então a Abisai: “Seba, filho de Bicri, será agora pior para nós do que Absalão. Toma tu mesmo os servos do teu senhor e vai no encalço dele, a fim de que não ache para si cidades fortificadas e escape diante dos nossos olhos.”^&#42;1^

[NOTE]
====
. Lit.: “e arrebate nosso olho”.
====

[[v10-20-7]]

^<<v10-20-7,7>>^ Conseqüentemente, os homens de Joabe, e os queretitas e os peletitas, e todos os poderosos saíram então atrás dele; e foram sair de Jerusalém para ir no encalço de Seba, filho de Bicri.

[[v10-20-8]]

^<<v10-20-8,8>>^ Estavam perto da pedra grande que há em Gibeão e o próprio Amasa veio ao encontro deles. Ora, Joabe estava cingido, trajado duma veste; e ele estava cingido duma espada, presa aos seus quadris, na sua bainha. E ele mesmo veio para a frente, e por isso ela^&#42;1^ caiu fora.

[NOTE]
====
. “Ela”, isto é, a espada.
====

[[v10-20-9]]

^<<v10-20-9,9>>^ E Joabe passou a dizer a Amasa: “Vais bem, meu irmão?” A mão direita de Joabe segurou então a barba de Amasa para o beijar.

[[v10-20-10]]

^<<v10-20-10,10>>^ Quanto a Amasa, não se preveniu contra a espada na mão de Joabe; de modo que o golpeou com ela no abdome, e derramaram-se-lhe os intestinos por terra, e não precisou fazer-lhe isso novamente. Assim morreu. E Joabe e Abisai, seu irmão, da sua parte, foram no encalço de Seba, filho de Bicri.

[[v10-20-11]]

^<<v10-20-11,11>>^ E certo dos moços de Joabe ficou de pé sobre ele e dizia: “Quem se agradar de Joabe e quem pertencer a Davi, siga a Joabe!”

[[v10-20-12]]

^<<v10-20-12,12>>^ Enquanto isso, Amasa se revolvia no sangue no meio da estrada principal. Quando o homem viu que todo o povo ficou parado, então removeu Amasa da estrada principal para o campo. Por fim lançou sobre ele uma veste, pois viu que todos os que chegavam até ele ficavam parados.

[[v10-20-13]]

^<<v10-20-13,13>>^ Assim que o tinha removido da estrada principal, cada homem passou seguindo a Joabe para ir no encalço de Seba, filho de Bicri.

[[v10-20-14]]

^<<v10-20-14,14>>^ E [Seba] foi passar por todas as tribos de Israel até Abel de Bete-Maacá. Quanto a todos os bicritas,^&#42;1^ congregaram-se então e também entraram atrás dele.

[NOTE]
====
. Mediante uma ligeira emenda; M: “beritas”.
====

[[v10-20-15]]

^<<v10-20-15,15>>^ E passaram a vir e a pôr sítio contra ele em Abel de Bete-Maacá, e levantaram contra a cidade um aterro de sítio, visto que ela se achava dentro de uma escarpa. E todo o povo que estava com Joabe minava a muralha para a derrubar.

[[v10-20-16]]

^<<v10-20-16,16>>^ E uma mulher sábia começou a clamar desde a cidade: “Escutai, homens, escutai! Por favor, dizei a Joabe: ‘Chega-te para cá e deixa-me falar contigo.’”

[[v10-20-17]]

^<<v10-20-17,17>>^ De modo que ele se chegou a ela e a mulher disse então: “És tu Joabe?” a que ele disse: “Sou.” Então ela lhe disse: “Escuta as palavras da tua escrava.” Ele disse, por sua vez: “Estou escutando.”

[[v10-20-18]]

^<<v10-20-18,18>>^ E ela prosseguiu, dizendo: “Outrora costumavam falar sem exceção, dizendo: ‘Indague-se em Abel e assim hão de pôr termo à questão.’

[[v10-20-19]]

^<<v10-20-19,19>>^ Eu represento os pacíficos e os fiéis de Israel. Estás procurando fazer morrer uma cidade e mãe em Israel. Por que devias tragar a herança de Jeová?”

[[v10-20-20]]

^<<v10-20-20,20>>^ A isto Joabe respondeu e disse: “É completamente inconcebível da minha parte tragar e arruinar.

[[v10-20-21]]

^<<v10-20-21,21>>^ O caso não é este, mas um homem da região montanhosa de Efraim, cujo nome é Seba, filho de Bicri, ergueu a sua mão contra o Rei Davi. Entregai-o, só a ele, e eu me retirarei da cidade.” A mulher disse então a Joabe: “Eis que a sua cabeça te [será] lançada por cima do muro!”

[[v10-20-22]]

^<<v10-20-22,22>>^ A mulher, na sua sabedoria, foi imediatamente a todo o povo, e passaram a decepar a cabeça de Seba, filho de Bicri, e a lançá-la a Joabe. Em vista disso, ele tocou a buzina e assim se espalharam da cidade, cada um para o seu lar;^&#42;1^ e o próprio Joabe voltou a Jerusalém, ao rei.

[NOTE]
====
. Lit.: “tendas”.
====

[[v10-20-23]]

^<<v10-20-23,23>>^ E Joabe estava sobre todo o exército de Israel; e Benaia, filho de Jeoiada, estava sobre os queretitas^&#42;1^ e sobre os peletitas.

[NOTE]
====
. “Queretitas”, Mmargem e muitos mss. hebr.; M: “escolta cariana”.
====

[[v10-20-24]]

^<<v10-20-24,24>>^ E Adorão estava sobre os recrutados para trabalho forçado; e Jeosafá, filho de Ailude, era o cronista.^&#42;1^

[NOTE]
====
. Ou “recordador”.
====

[[v10-20-25]]

^<<v10-20-25,25>>^ E Seva era secretário, e Zadoque e Abiatar eram sacerdotes.

[[v10-20-26]]

^<<v10-20-26,26>>^ E Ira, o jairita, também se tornou sacerdote^&#42;1^ de Davi.

[NOTE]
====
. Veja 8:18 n.: “sacerdotes”.
====

'''

xref:010-2-samuel/010-2-samuel-019.adoc#v10-19-0[&#60; Capítulo Anterior] | <<v10-20-0,Topo>> | xref:010-2-samuel/010-2-samuel-021.adoc#v10-21-0[Próximo Capítulo &#62;]