include::./index.adoc[]

[[v10-6-0]]
=== 2 Samuel, 6
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v10-6-1]]

^<<v10-6-1,1>>^ E Davi passou a ajuntar novamente todos os homens seletos em Israel, trinta mil.

[[v10-6-2]]

^<<v10-6-2,2>>^ Então se levantaram Davi e todo o povo que estava com ele, e foram a Baale-Judá para fazer subir de lá a arca do [verdadeiro] Deus, onde se invocava um nome, o nome de Jeová dos exércitos, sentado nos querubins.

[[v10-6-3]]

^<<v10-6-3,3>>^ No entanto, fizeram a arca do [verdadeiro] Deus andar numa carroça nova, para carregá-la da casa de Abinadabe, que estava no morro; e Uzá e Aiô, filhos de Abinadabe, conduziam a carroça nova.

[[v10-6-4]]

^<<v10-6-4,4>>^ Levaram-na assim da casa de Abinadabe, que estava no morro, — com a arca do [verdadeiro] Deus; e Aiô andava na frente da Arca.

[[v10-6-5]]

^<<v10-6-5,5>>^ E Davi e toda a casa de Israel festejavam perante Jeová com toda sorte de instrumentos de pau de junípero, e com harpas, e com instrumentos de cordas, e com pandeiros, e com sistros,^&#42;1^ e com címbalos.

[NOTE]
====
. Ou “chocalhos musicais”.
====

[[v10-6-6]]

^<<v10-6-6,6>>^ E por fim chegaram até a eira de Nacom,^&#42;1^ e Uzá estendeu então [a mão] à arca do [verdadeiro] Deus e segurou-a, porque o gado quase causara um transtorno.

[NOTE]
====
. “Quidom” em 1Cr 13:9.
====

[[v10-6-7]]

^<<v10-6-7,7>>^ Nisso se acendeu a ira de Jeová contra Uzá, e o [verdadeiro] Deus o golpeou ali pelo ato irreverente, de modo que morreu ali perto da arca do [verdadeiro] Deus.

[[v10-6-8]]

^<<v10-6-8,8>>^ E Davi ficou irado pelo fato de Jeová ter irrompido numa brecha contra Uzá, e aquele lugar veio a ser chamado de Peres-Uzá^&#42;1^ até o dia de hoje.

[NOTE]
====
. Significando “Ruptura Contra Uzá”.
====

[[v10-6-9]]

^<<v10-6-9,9>>^ E naquele dia Davi ficou com medo de Jeová e começou a dizer: “Como virá a mim a arca de Jeová?”

[[v10-6-10]]

^<<v10-6-10,10>>^ E Davi não estava disposto a remover a arca de Jeová para junto de si à Cidade de Davi. Portanto, Davi fez que fosse levada à casa de Obede-Edom, o geteu.

[[v10-6-11]]

^<<v10-6-11,11>>^ E a arca de Jeová ficou morando na casa de Obede-Edom, o geteu, por três meses; e Jeová abençoava a Obede-Edom e a todos os da sua casa.

[[v10-6-12]]

^<<v10-6-12,12>>^ Por fim se relatou ao Rei Davi, dizendo-se: “Jeová abençoou a casa de Obede-Edom e tudo o que é seu por causa da arca do [verdadeiro] Deus.” Então Davi passou a ir e a trazer a arca do [verdadeiro] Deus da casa de Obede-Edom para cima à Cidade de Davi, com alegria.

[[v10-6-13]]

^<<v10-6-13,13>>^ E sucedeu que, quando os carregadores da arca de Jeová tinham marchado seis passos, ele sacrificou imediatamente um touro e um animal cevado.

[[v10-6-14]]

^<<v10-6-14,14>>^ E Davi estava dançando diante de Jeová, com todo o seu poder, estando Davi cingido dum éfode de linho.

[[v10-6-15]]

^<<v10-6-15,15>>^ E Davi e toda a casa de Israel faziam subir a arca de Jeová com gritos de alegria e com toque de buzina.

[[v10-6-16]]

^<<v10-6-16,16>>^ E sucedeu que, entrando a arca de Jeová na Cidade de Davi, a própria Mical, filha de Saul, olhou pela janela e chegou a ver o Rei Davi pulando e dançando diante de Jeová; e ela começou a desprezá-lo no seu coração.

[[v10-6-17]]

^<<v10-6-17,17>>^ De modo que trouxeram a arca de Jeová para dentro e a colocaram no seu lugar dentro da tenda que Davi havia armado para ela; depois, Davi ofereceu sacrifícios queimados e sacrifícios de participação em comum perante Jeová.

[[v10-6-18]]

^<<v10-6-18,18>>^ E havendo Davi acabado de oferecer os sacrifícios queimados e os sacrifícios de participação em comum, então abençoou o povo em nome de Jeová dos exércitos.

[[v10-6-19]]

^<<v10-6-19,19>>^ Além disso, repartiu a todo o povo, a toda a massa de gente de Israel, tanto a homem como a mulher, a cada qual um bolo de pão de forma anular e um bolo de tâmaras, e um bolo de passas, todo o povo indo depois cada um para a sua própria casa.

[[v10-6-20]]

^<<v10-6-20,20>>^ Davi retornou então para abençoar os da sua própria casa, e Mical, filha de Saul, saiu ao encontro de Davi e disse então: “Quão glorioso se fez hoje o rei de Israel quando se descobriu hoje aos olhos das escravas dos seus servos, assim como um dos homens inanes^&#42;1^ se descobre de vez!”

[NOTE]
====
. “Homens inanes”, M; LXX: “dançarinos”.
====

[[v10-6-21]]

^<<v10-6-21,21>>^ Nisto Davi disse a Mical: “Foi perante Jeová, que^&#42;1^ escolheu antes a mim do que a teu pai e a todos os da sua casa para me pôr no comando como líder do povo de Jeová, Israel, e eu vou festejar perante Jeová.

[NOTE]
====
. “Foi perante Jeová, que”, M; LXX: “Perante Jeová eu hei de dançar. Bendito seja Jeová, que.”
====

[[v10-6-22]]

^<<v10-6-22,22>>^ E vou fazer-me ainda menos estimado do que isso e vou ficar rebaixado aos meus^&#42;1^ olhos; e com as escravas que mencionaste, com elas é que estou decidido a glorificar-me.”

[NOTE]
====
. “Meus”, MSyVg; LXX: “teus”.
====

[[v10-6-23]]

^<<v10-6-23,23>>^ Assim, no que se refere a Mical, filha de Saul, ela não veio a ter nenhum filho até o dia da sua morte.

'''

xref:010-2-samuel/010-2-samuel-005.adoc#v10-5-0[&#60; Capítulo Anterior] | <<v10-6-0,Topo>> | xref:010-2-samuel/010-2-samuel-007.adoc#v10-7-0[Próximo Capítulo &#62;]