include::./index.adoc[]

[[v30-7-0]]
=== Amós, 7
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v30-7-1]]

^<<v30-7-1,1>>^ Isto é o que o Soberano Senhor Jeová me fez ver, e eis que ele formou um enxame [de gafanhotos] no início da subida da sementeira serôdia.^&#42;1^ E eis que era a sementeira serôdia depois da grama cortada do rei.^&#42;2^

[NOTE]
====
. “Sementeira serôdia”, isto é, durante janeiro e fevereiro. Veja Ap. 8B.
. “E eis que um gafanhoto era Gogue, o rei”, LXX. Veja Ez 38:2.
====

[[v30-7-2]]

^<<v30-7-2,2>>^ E aconteceu que, quando terminou de consumir a vegetação da terra,^&#42;1^ passei a dizer: “Ó Soberano Senhor Jeová, perdoa, por favor. Quem se levantará de Jacó? Pois ele é pequeno!”

[NOTE]
====
. “Da terra.” Hebr.: ha·’á·rets.
====

[[v30-7-3]]

^<<v30-7-3,3>>^ Jeová deplorou isto. “Não acontecerá”, disse Jeová.

[[v30-7-4]]

^<<v30-7-4,4>>^ Isto é o que o Soberano Senhor Jeová me fez ver, e eis que o Soberano Senhor Jeová estava convocando a uma disputa por meio de fogo; e consumiu a vasta água de profundeza^&#42;1^ e consumiu o lote de terreno.

[NOTE]
====
. “Água de profundeza.” Ou “águas empoladas”. Hebr.: tehóhm; LXXVg: “abismo”. Veja Gên 1:2 n.: “profundeza”.
====

[[v30-7-5]]

^<<v30-7-5,5>>^ E eu passei a dizer: “Ó Soberano Senhor Jeová, refreia-te, por favor. Quem se levantará de Jacó? Pois ele é pequeno!”

[[v30-7-6]]

^<<v30-7-6,6>>^ Jeová deplorou isto. “Isto tampouco acontecerá”, disse o Soberano Senhor Jeová.

[[v30-7-7]]

^<<v30-7-7,7>>^ Isto é o que me fez ver, e eis que Jeová^&#42;1^ estava postado sobre uma muralha [feita com] o prumo, e havia um prumo na sua mão.

[NOTE]
====
. Uma das 134 mudanças de YHWH para ’Adho·naí feitas pelos escribas. Veja Ap. 1B.
====

[[v30-7-8]]

^<<v30-7-8,8>>^ Jeová disse-me então: “Que estás vendo, Amós?”^&#42;1^ De modo que eu disse: “Um prumo.” E Jeová^&#42;2^ prosseguiu, dizendo: “Eis que coloco um prumo no meio do meu povo de Israel. Não mais o desculparei.

[NOTE]
====
. Veja n. do Título.
. Veja v. 7 n.
====

[[v30-7-9]]

^<<v30-7-9,9>>^ E os altos de Isaque^&#42;1^ hão de ser desolados e os próprios santuários de Israel serão devastados; e levantar-me-ei contra a casa de Jeroboão^&#42;2^ com uma espada.”

[NOTE]
====
. “Isaque.” Hebr.: Yis·hháq, como no Sal 105:9 e em Je 33:26.
. Isto é, Jeroboão II, filho de Joás (Jeoás); não Jeroboão I, filho de Nebate. Veja 1:1.
====

[[v30-7-10]]

^<<v30-7-10,10>>^ E Amazias, o sacerdote de Betel, passou a enviar [mensageiros] a Jeroboão, rei de Israel, dizendo: “Amós tem conspirado contra ti dentro da própria casa de Israel. A terra^&#42;1^ não pode suportar todas as suas palavras.

[NOTE]
====
. “A terra.” Hebr.: ha·’á·rets.
====

[[v30-7-11]]

^<<v30-7-11,11>>^ Pois Amós disse assim: ‘Jeroboão morrerá à espada; e quanto a Israel, sem falta será exilado de seu próprio solo.’”

[[v30-7-12]]

^<<v30-7-12,12>>^ E Amazias passou a dizer a Amós: “Ó visionário, vai, foge para a terra de Judá e come pão ali, e ali podes profetizar.

[[v30-7-13]]

^<<v30-7-13,13>>^ Mas, não mais deves profetizar em Betel, pois é o santuário de um rei e é a casa de um reino.”

[[v30-7-14]]

^<<v30-7-14,14>>^ Então Amós respondeu e disse a Amazias: “Eu não era profeta, nem era filho de profeta;^&#42;1^ mas eu era boieiro e riscador de figos de sicômoros.

[NOTE]
====
. Ou “nem era membro do grupo de profetas”. Veja GK, sec. 128 v.
====

[[v30-7-15]]

^<<v30-7-15,15>>^ E Jeová passou a tomar-me de atrás do rebanho e Jeová prosseguiu, dizendo-me: ‘Vai, profetiza ao meu povo Israel.’

[[v30-7-16]]

^<<v30-7-16,16>>^ E agora ouve a palavra de Jeová: ‘Estás dizendo: “Não deves profetizar contra Israel e não deves soltar nenhuma [palavra] contra a casa de Isaque”?^&#42;1^

[NOTE]
====
. Veja v. 9 n.: “Isaque”.
====

[[v30-7-17]]

^<<v30-7-17,17>>^ Portanto, assim disse Jeová: “Quanto à tua esposa, tornar-se-á prostituta na cidade. E quanto aos teus filhos e às tuas filhas, cairão à espada. E quanto ao teu solo, será repartido com o cordel de medir. E quanto a ti mesmo, morrerás em solo impuro; e quanto a Israel, sem falta será exilado do seu próprio solo.”’”

'''

xref:030-amos/030-amos-006.adoc#v30-6-0[&#60; Capítulo Anterior] | <<v30-7-0,Topo>> | xref:030-amos/030-amos-008.adoc#v30-8-0[Próximo Capítulo &#62;]