include::./index.adoc[]

[[v66-3-0]]
=== Apocalipse, 3
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v66-3-1]]

^<<v66-3-1,1>>^ “E ao anjo da congregação em Sardes escreve: Estas coisas diz aquele que tem os sete espíritos de Deus e as sete estrelas: ‘Conheço as tuas ações, de que tens a fama de estar vivo, mas estás morto.

[[v66-3-2]]

^<<v66-3-2,2>>^ Fica vigilante e fortalece as coisas remanescentes que estavam prestes a morrer, porque não achei as tuas ações plenamente realizadas diante do meu Deus.

[[v66-3-3]]

^<<v66-3-3,3>>^ Portanto, continua a lembrar-te de como recebeste e como ouviste, e prossegue guardando [isso], e arrepende-te. Certamente, a menos que despertes, virei como ladrão, e não saberás absolutamente a que hora virei sobre ti.

[[v66-3-4]]

^<<v66-3-4,4>>^ “‘Não obstante, tens alguns nomes^&#42;1^ em Sardes que não poluíram as suas roupas exteriores, e estes andarão comigo em [roupas] brancas, porque são dignos.

[NOTE]
====
. Ou “pessoas”.
====

[[v66-3-5]]

^<<v66-3-5,5>>^ Aquele que vencer estará assim vestido de roupas exteriores brancas; e eu de modo algum apagarei o seu nome do livro da vida, mas reconhecerei o seu nome perante meu Pai e perante os seus anjos.

[[v66-3-6]]

^<<v66-3-6,6>>^ Quem tem ouvido ouça o que o espírito diz às congregações.’

[[v66-3-7]]

^<<v66-3-7,7>>^ “E ao anjo da congregação em Filadélfia escreve: Estas coisas diz aquele que é santo, que é verdadeiro, que tem a chave de Davi, que abre de modo que ninguém feche, e fecha de modo que ninguém abra:

[[v66-3-8]]

^<<v66-3-8,8>>^ ‘Conheço as tuas ações — eis que tenho posto diante de ti uma porta aberta, a qual ninguém pode fechar — que tens um pouco de poder, e que guardaste a minha palavra e não te mostraste falso para com o meu nome.

[[v66-3-9]]

^<<v66-3-9,9>>^ Eis que darei os da sinagoga de Satanás, que se dizem judeus, e que não são, mas estão mentindo — eis que os farei vir e prestar homenagem diante dos teus pés e os farei saber que eu te tenho amado.

[[v66-3-10]]

^<<v66-3-10,10>>^ Porque guardaste a palavra a respeito da minha perseverança,^&#42;1^ eu também te guardarei da hora da prova,^&#42;2^ que há de vir sobre toda a terra habitada, para pôr à prova os que moram na terra.

[NOTE]
====
. Ou “guardaste o que eu disse sobre a perseverança”.
. Lit.: “da hora da tentação”.
====

[[v66-3-11]]

^<<v66-3-11,11>>^ Venho depressa. Persiste em apegar-te ao que tens, para que ninguém tome a tua coroa.

[[v66-3-12]]

^<<v66-3-12,12>>^ “‘Aquele que vencer — eu o farei coluna no templo^&#42;1^ do meu Deus, e ele, de modo algum, jamais sairá [dele], e escreverei sobre ele o nome do meu Deus e o nome da cidade do meu Deus, a nova Jerusalém,^&#42;2^ que desce do céu da parte do meu Deus, e aquele meu novo nome.

[NOTE]
====
. Ou “habitação (morada) divina”. Gr.: na·oí, dativo, sing.; lat.: tém·plo; J17,18,22(hebr.): beheh·khál, no “palácio (templo) de”.
. “Jerusalém”, significando “Posse [ou: Alicerce] da Paz Dupla”.
====

[[v66-3-13]]

^<<v66-3-13,13>>^ Quem tem ouvido ouça o que o espírito diz às congregações.’

[[v66-3-14]]

^<<v66-3-14,14>>^ “E ao anjo da congregação em Laodicéia escreve: Estas coisas diz o Amém,^&#42;1^ a testemunha fiel e verdadeira, o princípio da criação de Deus:

[NOTE]
====
. “O Amém.” Gr.: ho A·mén; lat.: Á·men; J17,18,22(hebr.): ha·’A·mén, “o Assim Seja”.
====

[[v66-3-15]]

^<<v66-3-15,15>>^ ‘Conheço as tuas ações, que não és nem frio nem quente. Quisera eu que fosses frio ou quente.

[[v66-3-16]]

^<<v66-3-16,16>>^ Assim, porque és morno, e não és nem quente nem frio, vou vomitar-te^&#42;1^ da minha boca.

[NOTE]
====
. “Vou vomitar-te”, AVgSyh; א: “manter [tua boca] calada!”
====

[[v66-3-17]]

^<<v66-3-17,17>>^ Porque dizes: “Sou rico e adquiri riquezas, e não preciso de coisa alguma”, mas não sabes que és miserável, e coitado, e pobre, e cego, e nu,

[[v66-3-18]]

^<<v66-3-18,18>>^ aconselho-te que compres de mim ouro refinado pelo fogo, para que fiques rico, e roupas exteriores brancas, para que fiques trajado e não se torne manifesta a vergonha da tua nudez, e ungüento para os olhos, para passar nos teus olhos, para que vejas.

[[v66-3-19]]

^<<v66-3-19,19>>^ “‘A todos aqueles pelos quais tenho afeição, eu repreendo e disciplino. Portanto, sê zeloso e arrepende-te.

[[v66-3-20]]

^<<v66-3-20,20>>^ Eis que estou em pé à porta e estou batendo. Se alguém ouvir a minha voz e abrir a porta, entrarei na sua [casa] e tomarei a refeição noturna com ele e ele comigo.

[[v66-3-21]]

^<<v66-3-21,21>>^ Àquele que vencer, concederei assentar-se comigo no meu trono, assim como eu venci e me assentei com o meu Pai no seu trono.

[[v66-3-22]]

^<<v66-3-22,22>>^ Quem tem ouvido ouça o que o espírito diz às congregações.’”

'''

xref:066-apocalipse/066-apocalipse-002.adoc#v66-2-0[&#60; Capítulo Anterior] | <<v66-3-0,Topo>> | xref:066-apocalipse/066-apocalipse-004.adoc#v66-4-0[Próximo Capítulo &#62;]