include::./index.adoc[]

[[v66-17-0]]
=== Apocalipse, 17
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v66-17-1]]

^<<v66-17-1,1>>^ E um dos sete anjos, que tinham as sete tigelas, veio e falou comigo, dizendo: “Vem, mostrar-te-ei o julgamento da grande meretriz^&#42;1^ que está sentada sobre muitas^&#42;2^ águas,

[NOTE]
====
. Ou “fornicadora; prostituta”. Gr.: pór·nes. Veja Ap. 5A.
. Ou “grandes”.
====

[[v66-17-2]]

^<<v66-17-2,2>>^ com a qual os reis da terra cometeram fornicação, enquanto que os que habitam na terra se embriagaram com o vinho da fornicação^&#42;1^ dela.”

[NOTE]
====
. Gr.: por·neías. Veja Ap. 5A.
====

[[v66-17-3]]

^<<v66-17-3,3>>^ E ele me levou no [poder do] espírito para um ermo. E avistei uma mulher sentada numa fera cor de escarlate, que estava cheia de nomes blasfemos e que tinha sete cabeças e dez chifres.

[[v66-17-4]]

^<<v66-17-4,4>>^ E a mulher estava vestida de púrpura e de escarlate, e estava adornada de ouro, e de pedra preciosa, e de pérolas, e tinha na sua mão um copo de ouro cheio de coisas repugnantes e das coisas impuras da sua fornicação.

[[v66-17-5]]

^<<v66-17-5,5>>^ E na sua testa havia escrito um nome, um mistério:^&#42;1^ “Babilônia,^&#42;2^ a Grande, a mãe das meretrizes e das coisas repugnantes da terra.”

[NOTE]
====
. Ou “segredo religioso”, sagrado para Babilônia.
. Veja 16:19 n.
====

[[v66-17-6]]

^<<v66-17-6,6>>^ E eu vi que a mulher estava embriagada com o sangue dos santos e com o sangue das testemunhas de Jesus.
Pois bem, ao avistá-la, fiquei admirado com grande espanto.

[[v66-17-7]]

^<<v66-17-7,7>>^ E o anjo disse-me, assim: “Por que te admiras? Eu te direi o mistério^&#42;1^ da mulher e da fera que a carrega, que tem as sete cabeças e os dez chifres:

[NOTE]
====
. Ou “segredo religioso”. Gr.: my·sté·ri·on.
====

[[v66-17-8]]

^<<v66-17-8,8>>^ A fera que viste era, mas não é, contudo, está para ascender do abismo, e há de ir para a destruição. E quando virem que a fera era, mas não é, contudo estará presente, os que moram na terra se admirarão grandemente, mas os nomes deles não foram inscritos no rolo da vida desde a fundação^&#42;1^ do mundo.

[NOTE]
====
. Lit.: “o lançamento para baixo [de semente]”. Gr.: ka·ta·bo·lés.
====

[[v66-17-9]]

^<<v66-17-9,9>>^ “Aqui é que está a inteligência que tem sabedoria: As sete cabeças significam^&#42;1^ sete montes, onde a mulher está sentada no cume.

[NOTE]
====
. Ou “são”.
====

[[v66-17-10]]

^<<v66-17-10,10>>^ E há^&#42;1^ sete reis: cinco já caíram, um é, o outro ainda não chegou, mas, quando chegar, tem de permanecer por pouco tempo.

[NOTE]
====
. Ou: “E significam.”
====

[[v66-17-11]]

^<<v66-17-11,11>>^ E a fera que era, mas não é, é ela mesma também um oitavo [rei], mas procede dos sete,^&#42;1^ e vai para a destruição.

[NOTE]
====
. Ou “mas deve a sua existência aos sete”.
====

[[v66-17-12]]

^<<v66-17-12,12>>^ “E os dez chifres que viste significam dez reis, os quais ainda não receberam um reino, mas eles recebem autoridade como reis por uma hora, junto com a fera.

[[v66-17-13]]

^<<v66-17-13,13>>^ Estes têm um só pensamento, e assim, dão o seu poder e autoridade à fera.

[[v66-17-14]]

^<<v66-17-14,14>>^ Estes batalharão contra o Cordeiro, mas, porque ele é Senhor dos^&#42;1^ senhores e Rei dos^&#42;2^ reis, o Cordeiro os vencerá. Também [o farão] com ele os chamados, e escolhidos, e fiéis.”

[NOTE]
====
. Ou “sobre; entre”.
. Ou “sobre; entre”.
====

[[v66-17-15]]

^<<v66-17-15,15>>^ E ele me diz: “As águas que viste, onde a meretriz está sentada, significam povos, e multidões,^&#42;1^ e nações, e línguas.

[NOTE]
====
. Ou “massas [de gente]”.
====

[[v66-17-16]]

^<<v66-17-16,16>>^ E os dez chifres que viste, e a fera, estes odiarão a meretriz e a farão devastada e nua, e comerão as suas carnes e a queimarão completamente no fogo.

[[v66-17-17]]

^<<v66-17-17,17>>^ Porque Deus pôs nos seus corações executarem o pensamento dele, sim, executarem um só pensamento [deles] por darem^&#42;1^ o seu reino à fera, até que se tenham efetuado as palavras de Deus.

[NOTE]
====
. Ou “para cumprirem um só propósito e darem”. Lit.: “fazerem [segundo] uma só opinião e darem”.
====

[[v66-17-18]]

^<<v66-17-18,18>>^ E a mulher que viste significa^&#42;1^ a grande cidade que tem um reino sobre os reis da terra.”

[NOTE]
====
. Ou “é”.
====

'''

xref:066-apocalipse/066-apocalipse-016.adoc#v66-16-0[&#60; Capítulo Anterior] | <<v66-17-0,Topo>> | xref:066-apocalipse/066-apocalipse-018.adoc#v66-18-0[Próximo Capítulo &#62;]