include::./index.adoc[]

[[v66-14-0]]
=== Apocalipse, 14
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v66-14-1]]

^<<v66-14-1,1>>^ E eu vi, e eis o Cordeiro em pé no monte Sião, e com ele cento e quarenta e quatro mil, que têm o nome dele e o nome de seu Pai escrito nas suas testas.

[[v66-14-2]]

^<<v66-14-2,2>>^ E ouvi um som vindo do céu, como o som de muitas^&#42;1^ águas e como o som de forte trovão; e o som que eu ouvi era como de cantores ao acompanhamento de harpas, tocando as suas harpas.

[NOTE]
====
. Ou “grandes”.
====

[[v66-14-3]]

^<<v66-14-3,3>>^ E estão cantando como que um novo cântico diante do trono e diante das quatro criaturas viventes e dos anciãos;^&#42;1^ e ninguém podia aprender^&#42;2^ esse cântico, exceto os cento e quarenta e quatro mil que foram comprados da terra.

[NOTE]
====
. Gr.: pre·sby·té·ron.
. Ou “aprender plenamente”.
====

[[v66-14-4]]

^<<v66-14-4,4>>^ Estes são os que não se poluíram com mulheres; de fato, são virgens. Estes são os que estão seguindo o Cordeiro para onde quer que ele vá. Estes foram comprados dentre a humanidade como primícias para Deus e para o Cordeiro,

[[v66-14-5]]

^<<v66-14-5,5>>^ e não se achou falsidade na sua boca; não têm mácula.

[[v66-14-6]]

^<<v66-14-6,6>>^ E eu vi outro anjo voando pelo meio do céu,^&#42;1^ e ele tinha boas novas eternas para declarar, como boas notícias aos que moram na terra, e a toda nação, e tribo, e língua, e povo,

[NOTE]
====
. Ou “pelo meridiano; diretamente por cima”.
====

[[v66-14-7]]

^<<v66-14-7,7>>^ dizendo com voz alta: “Temei a Deus e dai-lhe glória, porque já chegou a hora do julgamento por ele, e assim, adorai Aquele que fez o céu, e a terra, e o mar, e as fontes das águas.”

[[v66-14-8]]

^<<v66-14-8,8>>^ E seguiu outro anjo,^&#42;1^ um segundo, dizendo: “Caiu! Caiu Babilônia, a Grande, aquela que fazia todas as nações beber do vinho da ira da sua fornicação!”^&#42;2^

[NOTE]
====
. “Anjo”, אcACSyh; P47א° omitem isso.
. Veja Ap. 5A.
====

[[v66-14-9]]

^<<v66-14-9,9>>^ E seguiu-lhes outro anjo, um terceiro, dizendo com voz alta: “Se alguém adorar a fera e a sua imagem, e receber uma marca na sua testa ou na sua mão,

[[v66-14-10]]

^<<v66-14-10,10>>^ beberá também do vinho da ira de Deus, derramado, não diluído, no copo do seu furor, e será atormentado com fogo e enxofre, à vista dos santos anjos e à vista do Cordeiro.

[[v66-14-11]]

^<<v66-14-11,11>>^ E a fumaça do tormento deles ascende para todo o sempre, e não têm descanso, dia e noite, os que adoram a fera e a sua imagem, e todo aquele que recebe a marca do seu nome.

[[v66-14-12]]

^<<v66-14-12,12>>^ Aqui é que significa perseverança para os santos, os que observam os mandamentos de Deus e a fé [que era] de Jesus.”

[[v66-14-13]]

^<<v66-14-13,13>>^ E ouvi uma voz saindo do céu dizer: “Escreve: Felizes os mortos que morrem em união com [o] Senhor, deste tempo em diante. Sim, diz o espírito, descansem eles^&#42;1^ dos seus labores, porque as coisas que fizeram^&#42;2^ os acompanham.”

[NOTE]
====
. Ou “para que possam descansar”.
. “As coisas que fizeram.” Lit.: “suas obras”.
====

[[v66-14-14]]

^<<v66-14-14,14>>^ E eu vi, e eis uma nuvem branca, e sobre a nuvem sentado alguém semelhante a um filho de homem, com uma coroa de ouro na cabeça e uma foice afiada na mão.

[[v66-14-15]]

^<<v66-14-15,15>>^ E do [santuário do] templo^&#42;1^ emergiu outro anjo, gritando com voz alta para o sentado na nuvem: “Mete a tua foice e ceifa, pois chegou a hora para ceifar, porque a colheita da terra está inteiramente madura.”^&#42;2^

[NOTE]
====
. Ou “da habitação (morada) divina”. Gr.: tou na·oú; J17,18,22(hebr.): ha·heh·khál, “do palácio (templo)”.
. Ou “está ressequida”.
====

[[v66-14-16]]

^<<v66-14-16,16>>^ E o sentado na nuvem meteu a sua foice na terra e a terra foi ceifada.

[[v66-14-17]]

^<<v66-14-17,17>>^ E ainda outro anjo emergiu do [santuário do] templo^&#42;1^ que está no céu, tendo também uma foice afiada.

[NOTE]
====
. Veja v. 15 n.: “templo”.
====

[[v66-14-18]]

^<<v66-14-18,18>>^ E ainda outro anjo emergiu do altar, e ele tem autoridade sobre o fogo. E ele clamou com voz alta para aquele que tinha a foice afiada, dizendo: “Mete a tua foice afiada e ajunta os cachos da videira da terra, porque as suas uvas ficaram maduras.”

[[v66-14-19]]

^<<v66-14-19,19>>^ E o anjo meteu a sua foice na terra e ajuntou a videira da terra, e lançou-a no grande lagar da ira de Deus.

[[v66-14-20]]

^<<v66-14-20,20>>^ E o lagar foi pisado fora da cidade, e saiu sangue do lagar, até à altura dos freios dos cavalos, a uma distância de mil e seiscentos estádios.^&#42;1^

[NOTE]
====
. Cerca de 296 km. O estádio equivalia a um oitavo de milha romana, 185 m.
====

'''

xref:066-apocalipse/066-apocalipse-013.adoc#v66-13-0[&#60; Capítulo Anterior] | <<v66-14-0,Topo>> | xref:066-apocalipse/066-apocalipse-015.adoc#v66-15-0[Próximo Capítulo &#62;]