include::./index.adoc[]

[[v66-1-0]]
=== Apocalipse, 1
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v66-1-1]]

^<<v66-1-1,1>>^ Revelação^&#42;1^ de Jesus Cristo, que Deus lhe deu, para mostrar aos seus escravos as coisas que têm de ocorrer em breve.^&#42;2^ E ele enviou o seu anjo e [a] apresentou por intermédio dele em sinais ao seu escravo João,

[NOTE]
====
. Lit.: “exposição; exibição”. Gr.: A·po·ká·ly·psis; lat.: A·po·ca·lý·psis.
. Lit.: “depressa”.
====

[[v66-1-2]]

^<<v66-1-2,2>>^ o qual deu testemunho da palavra dada por Deus e do testemunho dado por Jesus Cristo, sim, de todas as coisas que viu.

[[v66-1-3]]

^<<v66-1-3,3>>^ Feliz é quem lê em voz alta, e os que ouvem as palavras desta profecia e observam as coisas escritas nela, pois o tempo designado está próximo.

[[v66-1-4]]

^<<v66-1-4,4>>^ João, às sete congregações que estão no [distrito da] Ásia:
Que tenhais benignidade imerecida e paz da parte de “Aquele que é,^&#42;1^ e que era, e que vem”, e da parte dos sete espíritos que estão diante do seu trono,

[NOTE]
====
. Lit.: “O Ser; o Existente.” Gr.: ho on. Veja Êx 3:14 n.
====

[[v66-1-5]]

^<<v66-1-5,5>>^ e da parte de Jesus Cristo, “a Testemunha Fiel”, “o primogênito dentre os mortos” e “o Governante dos reis da terra”.
Àquele que nos ama e que nos soltou dos nossos pecados por meio de seu próprio sangue —

[[v66-1-6]]

^<<v66-1-6,6>>^ e ele fez de nós um reino, sacerdotes para seu Deus e Pai — sim, a ele seja a glória e o poderio para sempre. Amém.

[[v66-1-7]]

^<<v66-1-7,7>>^ Eis que ele vem com as nuvens e todo olho o verá, e aqueles que o traspassaram; e todas as tribos da terra baterão em si mesmas de pesar por causa dele. Sim, amém.

[[v66-1-8]]

^<<v66-1-8,8>>^ “Eu sou o Alfa e o Ômega”,^&#42;1^ diz Jeová^&#42;2^ Deus, “Aquele que é, e que era, e que vem, o Todo-poderoso”.^&#42;3^

[NOTE]
====
. Ou “o A e o Z”. Gr.: τὸ Ἄλφα καὶ τὸ Ὦ (to Ál·fa kai to O[·mé·ga]), a primeira e a última das letras do alfabeto gr.; SyhJ22: “o Álefe e o Tau”.
. Veja Ap. 1D.
. “O Todo-poderoso.” Gr.: ho Pan·to·krá·tor; lat.: O·mní·po·tens; J18(hebr.): ’El Shad·daí, “Deus Todo-poderoso”; J17,22(hebr.): ’Elo·héh tseva·’óhth, “Deus dos exércitos”. Veja Ru 1:20 n.: “Todo-poderoso.”
====

[[v66-1-9]]

^<<v66-1-9,9>>^ Eu, João, vosso irmão e compartilhador na tribulação, e no reino, e na perseverança em companhia de Jesus, vim a estar na ilha que se chama Patmos, por ter falado a respeito de Deus e ter dado testemunho^&#42;1^ de Jesus.^&#42;2^

[NOTE]
====
. “Ter dado testemunho.” Gr.: mar·ty·rí·an; lat.: te·sti·mó·ni·um.
. Lit.: “pela palavra de Deus e pelo testemunho de Jesus”.
====

[[v66-1-10]]

^<<v66-1-10,10>>^ Por inspiração,^&#42;1^ vim a estar no dia do Senhor,^&#42;2^ e ouvi atrás de mim uma forte voz, semelhante à duma trombeta,

[NOTE]
====
. “Por inspiração.” Ou: “No espírito.” Gr.: en pneú·ma·ti; lat.: in spí·ri·tu.
. Ou: “Vim a estar sob inspiração no dia do Senhor.”
====

[[v66-1-11]]

^<<v66-1-11,11>>^ dizendo: “O que vês, escreve num rolo e envia-o às sete congregações, em Éfeso, e em Esmirna, e em Pérgamo, e em Tiatira, e em Sardes, e em Filadélfia, e em Laodicéia.”

[[v66-1-12]]

^<<v66-1-12,12>>^ E eu me voltei para ver a voz que falava comigo, e, tendo-me voltado, vi sete candelabros de ouro,

[[v66-1-13]]

^<<v66-1-13,13>>^ e no meio dos candelabros alguém semelhante a um filho de homem, vestido duma roupa que chegava até os pés e cingido pelo peito com um cinto de ouro.

[[v66-1-14]]

^<<v66-1-14,14>>^ Além disso, sua cabeça e seus cabelos eram brancos como lã branca, como neve, e os seus olhos como chama ardente;

[[v66-1-15]]

^<<v66-1-15,15>>^ e os seus pés eram semelhantes a cobre excelente quando se escandesce na fornalha; e a sua voz era como o som de muitas águas.

[[v66-1-16]]

^<<v66-1-16,16>>^ E ele tinha na sua mão direita sete estrelas, e da sua boca se estendia uma longa espada afiada de dois gumes, e o seu semblante era como o sol quando brilha no seu poder.

[[v66-1-17]]

^<<v66-1-17,17>>^ E quando o vi, caí como que morto aos seus pés.
E ele pôs a sua mão direita sobre mim e disse: “Não temas. Eu sou o Primeiro^&#42;1^ e o Último,

[NOTE]
====
. “Primeiro”, אVgSyh; A: “Primogênito”.
====

[[v66-1-18]]

^<<v66-1-18,18>>^ e o vivente; e fiquei morto, mas, eis que vivo para todo o sempre, e tenho as chaves da morte e do Hades.^&#42;1^

[NOTE]
====
. “Hades”, אA; SyhJ7,8,13,16-18,22: “Seol”. Veja Ap. 4B.
====

[[v66-1-19]]

^<<v66-1-19,19>>^ Escreve, portanto, as coisas que viste, e as coisas que são, e as coisas que hão de ocorrer depois dessas.

[[v66-1-20]]

^<<v66-1-20,20>>^ Quanto ao segredo sagrado das sete estrelas que viste sobre a minha mão direita, e dos sete candelabros de ouro: As sete estrelas significam^&#42;1^ [os] anjos das sete congregações, e os sete candelabros significam sete congregações.

[NOTE]
====
. Ou “são”.
====

'''

xref:065-judas/065-judas-001.adoc#v65-1-0[&#60; Capítulo Anterior] | <<v66-1-0,Topo>> | xref:066-apocalipse/066-apocalipse-002.adoc#v66-2-0[Próximo Capítulo &#62;]