include::./index.adoc[]

[[v66-21-0]]
=== Apocalipse, 21
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v66-21-1]]

^<<v66-21-1,1>>^ E eu vi um novo céu e uma nova terra; pois o céu anterior e a terra anterior tinham passado, e o mar já não é.

[[v66-21-2]]

^<<v66-21-2,2>>^ Vi também a cidade santa, Nova Jerusalém, descendo do céu, da parte de Deus, e preparada como noiva adornada para seu marido.

[[v66-21-3]]

^<<v66-21-3,3>>^ Com isso ouvi uma voz alta do trono dizer: “Eis que a tenda^&#42;1^ de Deus está com a humanidade, e ele residirá^&#42;2^ com eles e eles serão os seus povos. E o próprio Deus estará com eles.

[NOTE]
====
. “Tenda.” Gr.: ske·né; lat.: ta·ber·ná·cu·lum; J17,18,22(hebr.): mish·kán. Veja Êx 25:8.
. Lit.: “morará em tenda”.
====

[[v66-21-4]]

^<<v66-21-4,4>>^ E enxugará dos seus olhos toda lágrima, e não haverá mais morte, nem haverá mais pranto, nem clamor, nem dor. As coisas anteriores já passaram.”

[[v66-21-5]]

^<<v66-21-5,5>>^ E O que estava sentado no trono disse: “Eis que faço novas todas as coisas.” Ele diz também: “Escreve, porque estas palavras são fiéis e verdadeiras.”

[[v66-21-6]]

^<<v66-21-6,6>>^ E ele me disse: “Estão feitas!^&#42;1^ Eu sou o Alfa e o Ômega,^&#42;2^ o princípio e o fim. A todo aquele que tiver sede darei gratuitamente da fonte da água da vida.

[NOTE]
====
. Ou: “São um fato!”
. Ou: “Eu sou o A e o Z.” Veja 1:8 n.: “Ômega”.
====

[[v66-21-7]]

^<<v66-21-7,7>>^ Todo aquele que vencer herdará estas coisas, e eu serei o seu Deus e ele será o meu filho.

[[v66-21-8]]

^<<v66-21-8,8>>^ Mas, quanto aos covardes, e aos que não têm fé, e aos que são repugnantes na sua sujeira, e aos assassinos, e aos fornicadores, e aos que praticam o espiritismo,^&#42;1^ e aos idólatras, e a todos os mentirosos, terão o seu quinhão no lago que queima com fogo e enxofre. Este significa^&#42;2^ a segunda morte.”

[NOTE]
====
. “Aos que praticam o espiritismo.” Ou “feiticeiros”. Lit.: “drogueadores”. Gr.: far·ma·koís.
. Ou: “Este quinhão é.”
====

[[v66-21-9]]

^<<v66-21-9,9>>^ E veio um dos sete anjos que tinham as sete tigelas cheias das últimas sete pragas, e falou comigo, dizendo: “Vem para cá, mostrar-te-ei a noiva, a esposa do Cordeiro.”

[[v66-21-10]]

^<<v66-21-10,10>>^ Levou-me assim no [poder do] espírito para um grande e alto monte, e mostrou-me a cidade santa de Jerusalém descendo do céu, da parte de Deus,

[[v66-21-11]]

^<<v66-21-11,11>>^ e tendo a glória de Deus. Seu resplendor^&#42;1^ era semelhante a uma pedra mui preciosa, como pedra de jaspe, brilhando como cristal.

[NOTE]
====
. Ou “iluminador”.
====

[[v66-21-12]]

^<<v66-21-12,12>>^ Tinha uma grande e alta muralha, e tinha doze portões, e, junto aos portões, doze anjos, e havia nomes inscritos, os quais são os das doze tribos dos filhos de Israel.

[[v66-21-13]]

^<<v66-21-13,13>>^ Ao leste havia três portões, e ao norte havia três portões, e ao sul havia três portões, e ao oeste havia três portões.

[[v66-21-14]]

^<<v66-21-14,14>>^ A muralha da cidade tinha também doze pedras de alicerce, e sobre elas os doze nomes dos doze apóstolos do Cordeiro.

[[v66-21-15]]

^<<v66-21-15,15>>^ Ora, aquele que falava comigo segurava como medida uma cana de ouro, para medir a cidade, e os seus portões, e a sua muralha.

[[v66-21-16]]

^<<v66-21-16,16>>^ E a cidade é quadrada, e o seu comprimento é tão grande como a sua largura. E ele mediu a cidade com a cana, doze mil estádios;^&#42;1^ o comprimento, e a largura, e a altura dela são iguais.

[NOTE]
====
. Cerca de 2.220 km. O estádio equivalia a um oitavo de milha romana, 185 m.
====

[[v66-21-17]]

^<<v66-21-17,17>>^ Ele mediu também a sua muralha, cento e quarenta e quatro côvados,^&#42;1^ segundo a medida de homem, sendo também a de anjo.^&#42;2^

[NOTE]
====
. Cerca de 64 m.
. Ou “isto é, a de anjo”.
====

[[v66-21-18]]

^<<v66-21-18,18>>^ Ora, a estrutura da sua muralha era de jaspe, e a cidade era de ouro puro, como vidro límpido.

[[v66-21-19]]

^<<v66-21-19,19>>^ E os alicerces da muralha da cidade estavam adornados com toda sorte de pedra preciosa: o primeiro alicerce era jaspe, o segundo, safira, o terceiro, calcedônia, o quarto, esmeralda,

[[v66-21-20]]

^<<v66-21-20,20>>^ o quinto, sardônio, o sexto, sárdio, o sétimo, crisólito, o oitavo, berilo, o nono, topázio, o décimo, crisópraso, o undécimo, jacinto, o duodécimo, ametista.

[[v66-21-21]]

^<<v66-21-21,21>>^ Também, os doze portões eram doze pérolas; cada um dos portões era de uma só pérola. E a rua larga da cidade era ouro puro, como vidro transparente.

[[v66-21-22]]

^<<v66-21-22,22>>^ E não vi templo^&#42;1^ nela, pois Jeová^&#42;2^ Deus, o Todo-poderoso,^&#42;3^ é o seu templo, também o Cordeiro [o é].

[NOTE]
====
. Ou “habitação (morada) divina”. Gr.: na·ón; lat.: tém·plum; J17,18(hebr.): weheh·khál, “e um palácio (templo)”.
. Veja Ap. 1D.
. “Todo-poderoso.” Gr.: Pan·to·krá·tor; lat.: O·mní·po·tens; J17,22(hebr.): ’Elo·hím tseva·’óhth, “Deus dos exércitos”. Veja Ru 1:20 n.: “Todo-poderoso.”
====

[[v66-21-23]]

^<<v66-21-23,23>>^ E a cidade não tinha necessidade do sol, nem da lua, para brilhar sobre ela, pois a glória de Deus a iluminava, e a sua lâmpada era o Cordeiro.

[[v66-21-24]]

^<<v66-21-24,24>>^ E as nações andarão por meio da sua luz, e os reis da terra lhe trarão a sua glória.

[[v66-21-25]]

^<<v66-21-25,25>>^ E os seus portões de modo algum se fecharão de dia, porque não haverá ali noite.

[[v66-21-26]]

^<<v66-21-26,26>>^ E trarão a ela a glória e a honra das nações.

[[v66-21-27]]

^<<v66-21-27,27>>^ Mas, tudo o que não for sagrado, e todo aquele que praticar uma coisa repugnante e a mentira, de modo algum entrará nela; somente os escritos no rolo da vida do Cordeiro [entrarão].

'''

xref:066-apocalipse/066-apocalipse-020.adoc#v66-20-0[&#60; Capítulo Anterior] | <<v66-21-0,Topo>> | xref:066-apocalipse/066-apocalipse-022.adoc#v66-22-0[Próximo Capítulo &#62;]