include::./index.adoc[]

[[v66-18-0]]
=== Apocalipse, 18
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v66-18-1]]

^<<v66-18-1,1>>^ Depois destas coisas vi outro anjo descer do céu, com grande autoridade; e a terra ficou iluminada com a sua glória.

[[v66-18-2]]

^<<v66-18-2,2>>^ E ele clamou com forte voz, dizendo: “Caiu! Caiu Babilônia,^&#42;1^ a Grande, e ela se tornou moradia de demônios, e guarida de toda exalação^&#42;2^ impura, e guarida de toda ave impura e odiada!

[NOTE]
====
. Gr.: Ba·by·lón; J17,18,22(hebr.): Ba·vél.
. Ou “espírito”.
====

[[v66-18-3]]

^<<v66-18-3,3>>^ Pois todas as nações caíram [vítimas] por causa do vinho da ira da sua fornicação,^&#42;1^ e os reis da terra cometeram fornicação com ela, e os comerciantes viajantes da terra ficaram ricos devido ao poder de sua impudente luxúria.”

[NOTE]
====
. Ou: “Pois . . . por causa do vinho apaixonante de sua fornicação.” A omite “do vinho”.
====

[[v66-18-4]]

^<<v66-18-4,4>>^ E ouvi outra voz saída do céu dizer: “Saí dela, povo meu, se não quiserdes compartilhar com ela nos seus pecados e se não quiserdes receber parte das suas pragas.

[[v66-18-5]]

^<<v66-18-5,5>>^ Pois os pecados dela acumularam-se até o céu, e Deus se lembrou dos atos injustos dela.

[[v66-18-6]]

^<<v66-18-6,6>>^ Fazei-lhe assim como ela mesma fez, e fazei-lhe duas vezes tanto, sim, duas vezes o número de coisas que ela fez; no copo em que ela pôs a mistura, ponde duas vezes tanto da mistura para ela.

[[v66-18-7]]

^<<v66-18-7,7>>^ Ao ponto que ela se glorificou e viveu em impudente luxúria, a tal ponto dai-lhe tormento e pranto. Porque ela está dizendo no seu coração: ‘Estou sentada como rainha, e não sou viúva, e nunca verei pranto.’

[[v66-18-8]]

^<<v66-18-8,8>>^ É por isso que as pragas dela virão num só dia, morte, e pranto, e fome, e ela será completamente queimada em fogo, porque Jeová^&#42;1^ Deus, quem a julga, é forte.

[NOTE]
====
. “Jeová”, J7,8,13,14,16-18,22-24,28; אcCSyh(gr.): Ký·ri·os; AVg omitem isso. Veja Ap. 1D.
====

[[v66-18-9]]

^<<v66-18-9,9>>^ “E os reis da terra, que cometeram fornicação com ela e viveram em impudente luxúria, chorarão e baterão em si mesmos de pesar por causa dela, ao olharem para a fumaça do incêndio dela,

[[v66-18-10]]

^<<v66-18-10,10>>^ enquanto estão parados à distância, por causa do [seu] temor do tormento dela, dizendo: ‘Ai, ai, ó grande cidade, Babilônia, forte cidade, porque numa só hora chegou o teu julgamento!’

[[v66-18-11]]

^<<v66-18-11,11>>^ “Também os comerciantes viajantes da terra estão chorando e pranteando por causa dela, porque não há mais ninguém para comprar todo o seu estoque,

[[v66-18-12]]

^<<v66-18-12,12>>^ todo um estoque de ouro, e de prata, e de pedra preciosa, e de pérolas, e de linho fino, e de púrpura, e de seda, e de escarlate; e tudo em [matéria de] madeira fragrante,^&#42;1^ e toda sorte de objeto de marfim, e toda sorte de objeto feito da madeira mais preciosa, e de cobre, e de ferro, e de mármore;

[NOTE]
====
. Ou “tuia[-da-argélia]”.
====

[[v66-18-13]]

^<<v66-18-13,13>>^ também canela, e especiaria indiana,^&#42;1^ e incenso, e óleo perfumado, e olíbano, e vinho, e azeite de oliveira, e flor de farinha, e trigo, e gado, e ovelhas, e cavalos, e carros, e escravos,^&#42;2^ e almas humanas.^&#42;3^

[NOTE]
====
. Ou “amomo”, uma planta condimentar indiana.
. Lit.: “corpos”.
. Ou “escravos, sim, almas de homens”.
====

[[v66-18-14]]

^<<v66-18-14,14>>^ Sim, o fruto excelente que a tua alma desejou^&#42;1^ afastou-se de ti, e todas as coisas delicadas e as coisas suntuosas pereceram de ti, e nunca mais as acharão.

[NOTE]
====
. Lit.: “fruto do desejo da tua alma”.
====

[[v66-18-15]]

^<<v66-18-15,15>>^ “Os comerciantes viajantes destas coisas, que se tornaram ricos por meio dela, estarão parados à distância por causa do [seu] temor do tormento dela, e chorarão e prantearão,

[[v66-18-16]]

^<<v66-18-16,16>>^ dizendo: ‘Ai, ai — a grande cidade, trajada de linho fino, e de púrpura, e de escarlate, e ricamente adornada de enfeite de ouro, e pedra preciosa, e pérola,

[[v66-18-17]]

^<<v66-18-17,17>>^ porque tais grandes riquezas foram devastadas numa só hora!’
“E todo capitão de navio e todo homem que viaja para alguma parte, e os marujos, e todos os que vivem do mar, estavam parados à distância

[[v66-18-18]]

^<<v66-18-18,18>>^ e clamavam ao olharem para a fumaça do incêndio dela, dizendo: ‘Que cidade é semelhante à grande cidade?’

[[v66-18-19]]

^<<v66-18-19,19>>^ E lançavam pó sobre as suas cabeças e clamavam, chorando e pranteando, e dizendo: ‘Ai, ai — a grande cidade, na qual todos os que têm barcos no mar ficaram ricos em razão da sua preciosidade, porque ela foi devastada numa só hora!’

[[v66-18-20]]

^<<v66-18-20,20>>^ “Alegra-te por causa dela, ó céu, e também vós, santos, e vós, apóstolos, e vós, profetas, porque por vós Deus exigiu dela judicialmente a punição!”

[[v66-18-21]]

^<<v66-18-21,21>>^ E um anjo forte levantou uma pedra semelhante a uma grande mó e lançou-a no mar, dizendo: “Assim, com um lance rápido, Babilônia, a grande cidade, será lançada para baixo, e ela nunca mais será achada.

[[v66-18-22]]

^<<v66-18-22,22>>^ E nunca mais se ouvirá em ti o som de cantores ao acompanhamento de harpas, e de músicos, e de flautistas, e de trombeteiros, e jamais se achará de novo em ti artífice algum de qualquer profissão,^&#42;1^ e jamais se ouvirá de novo em ti o som da mó,

[NOTE]
====
. “De qualquer profissão”, CVgSyh; אA omitem isso.
====

[[v66-18-23]]

^<<v66-18-23,23>>^ e jamais brilhará de novo em ti a luz de lâmpada, e jamais se ouvirá de novo em ti a voz de noivo e de noiva; porque os teus comerciantes viajantes eram os dignitários da terra, pois todas as nações foram desencaminhadas pelas tuas práticas espíritas.^&#42;1^

[NOTE]
====
. “Práticas espíritas.” Ou “feitiçaria”. Lit.: “drogueamento; drogaria”. Gr.: far·ma·kí·ai, no dativo, sing.
====

[[v66-18-24]]

^<<v66-18-24,24>>^ Sim, nela se achou o sangue dos profetas, e dos santos, e de todos os que foram mortos na terra.”

'''

xref:066-apocalipse/066-apocalipse-017.adoc#v66-17-0[&#60; Capítulo Anterior] | <<v66-18-0,Topo>> | xref:066-apocalipse/066-apocalipse-019.adoc#v66-19-0[Próximo Capítulo &#62;]