include::./index.adoc[]

[[v66-16-0]]
=== Apocalipse, 16
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v66-16-1]]

^<<v66-16-1,1>>^ E ouvi uma voz alta saindo do santuário dizer aos sete anjos: “Ide e derramai na terra as sete tigelas da ira de Deus.”

[[v66-16-2]]

^<<v66-16-2,2>>^ E o primeiro foi e derramou a sua tigela na terra. E veio a haver uma úlcera nociva e maligna nos homens que tinham a marca da fera e que adoravam a sua imagem.

[[v66-16-3]]

^<<v66-16-3,3>>^ E o segundo derramou a sua tigela no mar. E este se tornou em sangue como de um morto, e morreu toda alma vivente, [sim,] as coisas no mar.

[[v66-16-4]]

^<<v66-16-4,4>>^ E o terceiro derramou a sua tigela nos rios e nas fontes de águas. E eles se tornaram em sangue.

[[v66-16-5]]

^<<v66-16-5,5>>^ E ouvi o anjo sobre as águas dizer: “Tu,^&#42;1^ Aquele que é e que era, Aquele que é leal, és justo, porque fizeste estas decisões,

[NOTE]
====
. “Tu”, אACVgSyh; TR: “Tu, ó Senhor”; J7,8,13,14,16: “Tu, Jeová.”
====

[[v66-16-6]]

^<<v66-16-6,6>>^ pois derramaram o sangue dos santos e dos profetas, e tu lhes deste sangue para beber. Merecem isso.”

[[v66-16-7]]

^<<v66-16-7,7>>^ E ouvi o altar dizer: “Sim, Jeová^&#42;1^ Deus, o Todo-poderoso, verdadeiras e justas são as tuas decisões judiciais.”

[NOTE]
====
. Veja Ap. 1D.
====

[[v66-16-8]]

^<<v66-16-8,8>>^ E o quarto derramou a sua tigela sobre o sol; e concedeu-se [ao sol]^&#42;1^ abrasar os homens^&#42;2^ com fogo.

[NOTE]
====
. Lit.: “-lhe”.
. Ou “humanidade”.
====

[[v66-16-9]]

^<<v66-16-9,9>>^ E os homens foram abrasados por um grande calor, mas eles blasfemaram o nome de Deus, que tem a autoridade sobre estas pragas, e não se arrependeram de modo a lhe darem glória.

[[v66-16-10]]

^<<v66-16-10,10>>^ E o quinto derramou a sua tigela sobre o trono da fera. E o seu reino ficou obscurecido, e começaram a morder as suas línguas de dor,

[[v66-16-11]]

^<<v66-16-11,11>>^ mas blasfemaram o Deus do céu por causa das suas dores e das suas úlceras, e não se arrependeram das suas obras.

[[v66-16-12]]

^<<v66-16-12,12>>^ E o sexto derramou a sua tigela sobre o grande rio Eufrates, e a sua água se secou, para que se preparasse o caminho para os reis do nascente do sol.

[[v66-16-13]]

^<<v66-16-13,13>>^ E eu vi três impuras expressões inspiradas,^&#42;1^ semelhantes a rãs, sair da boca do dragão, e da boca da fera, e da boca do falso profeta.^&#42;2^

[NOTE]
====
. Ou “espíritos impuros”.
. “Falso profeta.” Gr.: pseu·do·pro·fé·tou; lat.: pseu·do·pro·phé·tae; J17,22(hebr.): neví’ hash·shé·qer.
====

[[v66-16-14]]

^<<v66-16-14,14>>^ São, de fato, expressões inspiradas por^&#42;1^ demônios e realizam sinais, e vão aos reis de toda a terra habitada,^&#42;2^ a fim de ajuntá-los para a guerra do grande dia de Deus, o Todo-poderoso.

[NOTE]
====
. Ou “de fato, espíritos de”.
. Lit.: “a habitada”. Gr.:  oi·kou·mé·nes,  fem.  sing.,  referindo-se  à terra.
====

[[v66-16-15]]

^<<v66-16-15,15>>^ “Eis que venho^&#42;1^ como ladrão. Feliz aquele que ficar desperto e guardar as suas roupas exteriores, para que não ande nu e olhem para a sua vergonha.”

[NOTE]
====
. “Venho”, אcAVgSyh; א°: “Ele vem.”
====

[[v66-16-16]]

^<<v66-16-16,16>>^ E ajuntaram-nos ao lugar^&#42;1^ que em hebraico se chama Har-Magedon.^&#42;2^

[NOTE]
====
. “Lugar”, אVgSyh; A: “rio”.
. Ou “Armagedom”. Gr.: Har Ma·ge·dón; lat.: Her·ma·gé·don. J18,22(hebr.): Har Meghid·dóhn, “Monte de Megido”.
====

[[v66-16-17]]

^<<v66-16-17,17>>^ E o sétimo derramou a sua tigela no ar. Saiu então uma voz alta do santuário, desde o trono, dizendo: “Está feito!”

[[v66-16-18]]

^<<v66-16-18,18>>^ E houve relâmpagos, e vozes, e trovões, e houve um grande terremoto, tal como nunca tinha havido desde que os homens vieram a estar na terra, tão extensivo [era] o terremoto, tão grande.

[[v66-16-19]]

^<<v66-16-19,19>>^ E a grande cidade fendeu-se em três partes, e caíram as cidades das nações; e Babilônia,^&#42;1^ a Grande, foi lembrada à vista de Deus, para dar-lhe o copo do vinho da ira do seu furor.

[NOTE]
====
. Em  gr.:  Ba·by·lón;  J17,22(hebr.): Ba·vél.
====

[[v66-16-20]]

^<<v66-16-20,20>>^ Também toda ilha fugiu e não se acharam montes.

[[v66-16-21]]

^<<v66-16-21,21>>^ E uma grande saraivada, cada pedra tendo aproximadamente o peso de um talento,^&#42;1^ caiu do céu sobre os homens,^&#42;2^ e os homens blasfemaram a Deus devido à praga da saraiva, porque a praga dela era extraordinariamente grande.

[NOTE]
====
. Cerca de 20,4 kg.
. Ou “humanidade”.
====

'''

xref:066-apocalipse/066-apocalipse-015.adoc#v66-15-0[&#60; Capítulo Anterior] | <<v66-16-0,Topo>> | xref:066-apocalipse/066-apocalipse-017.adoc#v66-17-0[Próximo Capítulo &#62;]