include::./index.adoc[]

[[v66-11-0]]
=== Apocalipse, 11
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v66-11-1]]

^<<v66-11-1,1>>^ E foi-me dada uma cana^&#42;1^ igual a uma vara, ao dizer-me ele: “Levanta-te e mede o [santuário do] templo^&#42;2^ de Deus^&#42;3^ e o altar, e os que nele adoram.

[NOTE]
====
. “Cana.” Gr.: ká·la·mos; lat.: cá·la·mus; J17,18,22(hebr.): qa·néh. Veja Ez 40:5 n.: “medir”.
. Ou “a habitação (morada) divina”. Gr.: ton na·ón; J17,18,22(hebr.): heh·khál, “palácio (templo) de”.
. “Deus”, אAVgSyh; J17: “Jeová”.
====

[[v66-11-2]]

^<<v66-11-2,2>>^ Mas, quanto ao pátio que está de fora do [santuário do] templo, lança-o completamente fora^&#42;1^ e não o meças, porque foi dado às nações, e elas pisarão a cidade santa por quarenta e dois meses.

[NOTE]
====
. Ou “deixa-o fora”.
====

[[v66-11-3]]

^<<v66-11-3,3>>^ E farei as minhas duas testemunhas profetizar por mil duzentos e sessenta dias trajadas de saco.”

[[v66-11-4]]

^<<v66-11-4,4>>^ Estas são [simbolizadas pelas] duas oliveiras e [pelos] dois candelabros, e estão em pé diante do Senhor^&#42;1^ da terra.

[NOTE]
====
. “Do Senhor”, אAVgSyh; Vgms. e mss. Minúsculos 1854, 2053: “Deus”.
====

[[v66-11-5]]

^<<v66-11-5,5>>^ E, se alguém quer causar-lhes dano, sai fogo das suas bocas e devora os seus inimigos; e se alguém quiser causar-lhes dano, terá de ser morto desta maneira.

[[v66-11-6]]

^<<v66-11-6,6>>^ Estas têm autoridade para fechar o céu, para que não caia chuva durante os dias do seu profetizar, e têm autoridade sobre^&#42;1^ as águas, para transformá-las em sangue, e para golpear a terra com toda sorte de praga, quantas vezes quiserem.

[NOTE]
====
. Gr.: e·pí, com o caso genitivo.
====

[[v66-11-7]]

^<<v66-11-7,7>>^ E quando tiverem terminado seu testemunho, a fera que ascende do abismo far-lhes-á guerra, e as vencerá, e as matará.

[[v66-11-8]]

^<<v66-11-8,8>>^ E os seus cadáveres jazerão na rua larga da grande cidade que em sentido espiritual se chama Sodoma e Egito, onde também o seu Senhor foi pregado numa estaca.^&#42;1^

[NOTE]
====
. Ou “fixado numa estaca (poste)”. Veja Ap. 5C.
====

[[v66-11-9]]

^<<v66-11-9,9>>^ E os dos povos, e tribos, e línguas, e nações olharão para os seus cadáveres por três dias e meio, e não deixam que os seus cadáveres sejam colocados num túmulo.

[[v66-11-10]]

^<<v66-11-10,10>>^ E os que moram na terra alegram-se por causa deles e regalam-se,^&#42;1^ e enviarão dádivas uns aos outros, porque estes dois profetas atormentavam os que moram na terra.

[NOTE]
====
. Lit.: “fazem-se bem dispostos”.
====

[[v66-11-11]]

^<<v66-11-11,11>>^ E depois dos três dias e meio entrou neles espírito de vida da parte de Deus, e puseram-se de pé, e caiu grande temor sobre os que os observavam.

[[v66-11-12]]

^<<v66-11-12,12>>^ E ouviram uma voz alta dizer-lhes desde o céu: “Subi para cá.” E subiram para o céu, numa nuvem, e seus inimigos os observavam.

[[v66-11-13]]

^<<v66-11-13,13>>^ E naquela hora houve um grande terremoto, e caiu um décimo da cidade; e sete mil pessoas^&#42;1^ foram mortas pelo^&#42;2^ terremoto, e os demais ficaram amedrontados e deram glória ao Deus do céu.

[NOTE]
====
. Lit.: “sete mil nomes de homens”.
. Ou “no”.
====

[[v66-11-14]]

^<<v66-11-14,14>>^ O segundo ai já passou. Eis que o terceiro ai vem depressa.

[[v66-11-15]]

^<<v66-11-15,15>>^ E o sétimo anjo tocou a sua trombeta. E houve vozes altas no céu, dizendo: “O reino do mundo^&#42;1^ tornou-se o reino de nosso Senhor e do seu Cristo, e ele reinará para todo o sempre.”

[NOTE]
====
. “Do mundo.” Gr.: tou kó·smou; lat.: mún·di; J17(hebr.): ha·‛oh·lám.
====

[[v66-11-16]]

^<<v66-11-16,16>>^ E os vinte e quatro anciãos,^&#42;1^ sentados nos seus tronos diante de Deus, prostraram-se sobre os seus rostos e adoraram a Deus,

[NOTE]
====
. Gr.: pre·sbý·te·roi.
====

[[v66-11-17]]

^<<v66-11-17,17>>^ dizendo: “Agradecemos-te, Jeová^&#42;1^ Deus, o Todo-poderoso, Aquele que é e que era, porque assumiste o teu grande poder e começaste a reinar.

[NOTE]
====
. Veja Ap. 1D.
====

[[v66-11-18]]

^<<v66-11-18,18>>^ Mas as nações ficaram furiosas, e veio teu próprio furor e o tempo designado para os mortos serem julgados, e para dar a recompensa aos teus escravos, os profetas, e aos santos e aos que temem o teu nome, a pequenos e a grandes, e para arruinar os que arruínam^&#42;1^ a terra.”

[NOTE]
====
. Lit.: “corrompem pela (através da)”.
====

[[v66-11-19]]

^<<v66-11-19,19>>^ E abriu-se o [santuário do] templo^&#42;1^ de Deus,^&#42;2^ que está no céu, e viu-se a arca do seu pacto no [santuário do] seu templo. E houve relâmpagos, e vozes, e trovões, e um terremoto, e grande saraivada.

[NOTE]
====
. Ou “a habitação (morada) divina”. Gr.: ho na·ós; J17,18,22(hebr.): heh·khál, “palácio (templo) de”.
. “Deus”, אAVgSyh; J17: “Jeová”.
====

'''

xref:066-apocalipse/066-apocalipse-010.adoc#v66-10-0[&#60; Capítulo Anterior] | <<v66-11-0,Topo>> | xref:066-apocalipse/066-apocalipse-012.adoc#v66-12-0[Próximo Capítulo &#62;]