include::./index.adoc[]

[[v66-20-0]]
=== Apocalipse, 20
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v66-20-1]]

^<<v66-20-1,1>>^ E eu vi descer do céu um anjo com a chave do abismo e uma grande cadeia na mão.

[[v66-20-2]]

^<<v66-20-2,2>>^ E ele se apoderou do dragão, a serpente original, que é o Diabo e Satanás, e o amarrou por mil anos.

[[v66-20-3]]

^<<v66-20-3,3>>^ E lançou-o no abismo, e fechou e selou [este] sobre ele, para que não mais desencaminhasse as nações até que tivessem terminado os mil anos. Depois destas coisas terá de ser solto por um pouco.

[[v66-20-4]]

^<<v66-20-4,4>>^ E eu vi tronos, e havia os que se assentavam neles, e foi-lhes dado poder para julgar. Sim, vi as almas dos executados com o machado, pelo testemunho que deram de Jesus e por terem falado a respeito de Deus,^&#42;1^ e os que não tinham adorado nem a fera nem a imagem dela, e que não tinham recebido a marca na sua testa e na sua mão. E passaram a viver e reinaram com o Cristo por mil anos.^&#42;2^

[NOTE]
====
. Lit.: “pelo testemunho de Jesus e pela palavra de Deus”.
. “Mil anos.” Gr.: khí·li·a é·te, donde se deriva a palavra “quiliastas”, isto é, os crentes no reinado milenar literal de Cristo sobre a humanidade na terra paradísica; lat.: míl·le án·nis, “milênio”.
====

[[v66-20-5]]

^<<v66-20-5,5>>^ (Os demais mortos não passaram a viver até terem terminado os mil anos.)^&#42;1^ Esta é a primeira ressurreição.^&#42;2^

[NOTE]
====
. “Os demais mortos . . . mil anos”, AVg; אSyp omitem isso.
. “Ressurreição.” Gr.: a·ná·sta·sis, “levantar; erguer” (de a·ná, “para cima”, e stá·sis, “estar de pé”); lat.: re·sur·réc·ti·o.
====

[[v66-20-6]]

^<<v66-20-6,6>>^ Feliz e santo é todo aquele que tem parte na primeira ressurreição; sobre estes a segunda morte não tem autoridade, mas serão sacerdotes de Deus e do Cristo, e reinarão com ele [durante] os mil anos.

[[v66-20-7]]

^<<v66-20-7,7>>^ Ora, assim que tiverem terminado os mil anos, Satanás será solto de sua prisão,

[[v66-20-8]]

^<<v66-20-8,8>>^ e ele sairá para desencaminhar aquelas nações nos quatro cantos^&#42;1^ da terra, Gogue e Magogue, a fim de ajuntá-los para a guerra. O número destes é como a areia do mar.

[NOTE]
====
. Ou “quadrantes; extremidades”. Veja 7:1.
====

[[v66-20-9]]

^<<v66-20-9,9>>^ E avançaram sobre a largura da terra e cercaram o acampamento^&#42;1^ dos santos e a cidade amada. Mas desceu fogo do céu e os devorou.

[NOTE]
====
. Ou “o exército em ordem de batalha”. Lit.: “acampamento”.
====

[[v66-20-10]]

^<<v66-20-10,10>>^ E o Diabo que os desencaminhava^&#42;1^ foi lançado no lago de fogo e enxofre, onde [já estavam] tanto a fera como o falso profeta; e serão atormentados dia e noite, para todo o sempre.

[NOTE]
====
. Lit.: “fazia errar”.
====

[[v66-20-11]]

^<<v66-20-11,11>>^ E eu vi um grande trono branco e o que estava sentado nele. De diante dele^&#42;1^ fugiam a terra e o céu, e não se achou lugar para eles.

[NOTE]
====
. Ou: “De diante da face dele.”
====

[[v66-20-12]]

^<<v66-20-12,12>>^ E eu vi os mortos, os grandes e os pequenos, em pé diante do trono, e abriram-se rolos.^&#42;1^ Mas outro rolo foi aberto; é o rolo da vida. E os mortos foram julgados pelas coisas escritas nos rolos, segundo as suas ações.

[NOTE]
====
. Lit.: “livrinhos”. Gr.: bi·blí·a.
====

[[v66-20-13]]

^<<v66-20-13,13>>^ E o mar entregou os mortos nele, e a morte e o Hades^&#42;1^ entregaram os mortos neles, e foram julgados individualmente segundo as suas ações.

[NOTE]
====
. “Hades.” Gr.: haí·des; Vg(lat.): ín·fe·rus; Vgc(lat.): in·fér·nus; SyhJ7,8,11-14,16-18,22: “Seol”. Veja Ap. 4B.
====

[[v66-20-14]]

^<<v66-20-14,14>>^ E a morte e o Hades foram lançados no lago de fogo.^&#42;1^ Este significa^&#42;2^ a segunda morte, o lago de fogo.

[NOTE]
====
. Veja Ap. 4C.
. Ou “é”.
====

[[v66-20-15]]

^<<v66-20-15,15>>^ Outrossim, todo aquele que não foi achado inscrito no livro da vida foi lançado no lago de fogo.

'''

xref:066-apocalipse/066-apocalipse-019.adoc#v66-19-0[&#60; Capítulo Anterior] | <<v66-20-0,Topo>> | xref:066-apocalipse/066-apocalipse-021.adoc#v66-21-0[Próximo Capítulo &#62;]