include::./index.adoc[]

[[v66-9-0]]
=== Apocalipse, 9
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v66-9-1]]

^<<v66-9-1,1>>^ E o quinto anjo tocou a sua trombeta. E eu vi uma estrela que caíra do céu à terra, e foi-lhe dada a chave da cova do abismo.

[[v66-9-2]]

^<<v66-9-2,2>>^ E ele abriu a cova do abismo, e ascendeu fumaça da cova, como a fumaça duma grande fornalha, e o sol ficou obscurecido, também o ar, pela fumaça da cova.

[[v66-9-3]]

^<<v66-9-3,3>>^ E do meio da fumaça saíram gafanhotos sobre a terra; e foi-lhes dada autoridade, a mesma autoridade que os escorpiões da terra têm.

[[v66-9-4]]

^<<v66-9-4,4>>^ E foi-lhes dito que não fizessem dano a nenhuma vegetação da terra, nem a qualquer coisa verde, nem a qualquer árvore, mas apenas àqueles homens que não têm o selo de Deus nas suas testas.

[[v66-9-5]]

^<<v66-9-5,5>>^ E foi concedido aos [gafanhotos], não que os matassem, mas que estes fossem atormentados por cinco meses, e o tormento deles era como o tormento [causado] por um escorpião quando ataca um homem.

[[v66-9-6]]

^<<v66-9-6,6>>^ E, naqueles dias, os homens procurarão a morte, mas de modo algum a acharão, e desejarão morrer, mas a morte estará fugindo deles.

[[v66-9-7]]

^<<v66-9-7,7>>^ E as semelhanças dos gafanhotos pareciam cavalos preparados para a batalha; e nas suas cabeças [havia] o que pareciam ser coroas como de ouro, e seus rostos [eram] como rostos de homens,

[[v66-9-8]]

^<<v66-9-8,8>>^ mas, tinham cabelo como o cabelo das mulheres. E os seus dentes eram como os de leões;

[[v66-9-9]]

^<<v66-9-9,9>>^ e tinham couraças como couraças de ferro. E o som das suas asas [era] como o som de carros de muitos cavalos correndo à batalha.

[[v66-9-10]]

^<<v66-9-10,10>>^ Também, têm caudas e aguilhões como os escorpiões; e a sua autoridade para fazer dano^&#42;1^ aos homens, por cinco meses, está nas suas caudas.

[NOTE]
====
. Literalmente: “tratar injustamente”.
====

[[v66-9-11]]

^<<v66-9-11,11>>^ Têm sobre si um rei, o anjo do abismo. Seu nome, em hebraico, é Abadon,^&#42;1^ mas em grego ele tem o nome de Apolion.^&#42;2^

[NOTE]
====
. “Abadon.” Ou “Destruição”. J17,18,22(hebr.): ’Avad·dóhn. Veja Jó 26:6 n.; Sal 88:11 n.; Pr 15:11 n.: “destruição”.
. “Apolion.” Ou “Destruidor”. Gr.: A·pol·lý·on. Vg acrescenta: “e em latim tem o nome Exterminador (Ex·tér·mi·nans)”. Veja Mt 7:13 n.
====

[[v66-9-12]]

^<<v66-9-12,12>>^ Um ai já passou. Eis que vêm mais dois ais depois destas coisas.^&#42;1^

[NOTE]
====
. Ou “das seguintes coisas”.
====

[[v66-9-13]]

^<<v66-9-13,13>>^ E o sexto anjo tocou a sua trombeta. E ouvi uma voz, do meio dos chifres^&#42;1^ do altar de ouro diante de Deus,

[NOTE]
====
. “Do meio dos chifres”, P47אcAItmss.Syh; Vgc: “do meio dos quatro chifres”.
====

[[v66-9-14]]

^<<v66-9-14,14>>^ dizer ao sexto anjo, que tinha a trombeta: “Desata os quatro anjos que estão amarrados junto ao grande rio Eufrates.”

[[v66-9-15]]

^<<v66-9-15,15>>^ E foram desatados os quatro anjos que têm sido preparados para a hora, e o dia, e o mês, e o ano, para matarem um terço dos homens.

[[v66-9-16]]

^<<v66-9-16,16>>^ E o número dos exércitos de cavalaria^&#42;1^ era de duas miríades de miríades:^&#42;2^ ouvi o número deles.

[NOTE]
====
. Ou “dos cavaleiros”.
. Ou “vinte mil vezes dez mil”, isto é, 200.000.000.
====

[[v66-9-17]]

^<<v66-9-17,17>>^ E é assim que eu vi os cavalos na visão, e os sentados neles: tinham couraças de cor de fogo, e de azul jacintino, e de amarelo sulfurino; e as cabeças dos cavalos eram como as cabeças de leões, e das suas bocas saía fogo, e fumaça, e enxofre.

[[v66-9-18]]

^<<v66-9-18,18>>^ Por estas três pragas foi morto um terço dos homens, pelo fogo, e pela fumaça, e pelo enxofre que saíam das suas bocas.

[[v66-9-19]]

^<<v66-9-19,19>>^ Pois a autoridade dos cavalos está nas suas bocas e nas suas caudas; porque as suas caudas são como serpentes e têm cabeças, e com estas fazem dano.

[[v66-9-20]]

^<<v66-9-20,20>>^ Mas os demais homens que não foram mortos por estas pragas não se arrependeram das obras das suas mãos, de modo a não adorarem os demônios e os ídolos de ouro, e de prata, e de cobre, e de pedra, e de madeira, que não podem nem ver, nem ouvir, nem andar;

[[v66-9-21]]

^<<v66-9-21,21>>^ e não se arrependeram dos seus assassínios, nem das suas práticas espíritas,^&#42;1^ nem da sua fornicação, nem dos seus furtos.

[NOTE]
====
. “Práticas espíritas.” Ou “feitiçarias”. Lit.: “drogas”. Gr.: far·má·kon.
====

'''

xref:066-apocalipse/066-apocalipse-008.adoc#v66-8-0[&#60; Capítulo Anterior] | <<v66-9-0,Topo>> | xref:066-apocalipse/066-apocalipse-010.adoc#v66-10-0[Próximo Capítulo &#62;]