include::./index.adoc[]

[[v66-13-0]]
=== Apocalipse, 13
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v66-13-1]]

^<<v66-13-1,1>>^ E ficou parado na areia do mar.
E eu vi ascender do mar uma fera, com dez chifres e sete cabeças, e nos seus chifres, dez diademas, mas nas suas cabeças, nomes blasfemos.

[[v66-13-2]]

^<<v66-13-2,2>>^ Ora, a fera que vi era semelhante a um leopardo, mas os seus pés eram como os dum urso, e a sua boca era como a boca dum leão. E o dragão deu [à fera]^&#42;1^ seu poder e seu trono, e grande autoridade.

[NOTE]
====
. Lit.: “deu-lhe”.
====

[[v66-13-3]]

^<<v66-13-3,3>>^ E eu vi uma das suas cabeças como que abatida até a morte, mas o golpe mortal que sofreu foi curado, e toda a terra seguia a fera com admiração.

[[v66-13-4]]

^<<v66-13-4,4>>^ E adoravam o dragão porque dera a autoridade à fera, e adoravam a fera com as palavras: “Quem é semelhante à fera e quem pode batalhar contra ela?”

[[v66-13-5]]

^<<v66-13-5,5>>^ E foi-lhe dada uma boca que falava grandes coisas e blasfêmias, e foi-lhe dada autoridade para agir por quarenta e dois meses.

[[v66-13-6]]

^<<v66-13-6,6>>^ E abriu a sua boca em blasfêmias contra Deus, para blasfemar do seu nome e da sua residência,^&#42;1^ mesmo dos que residem no céu.

[NOTE]
====
. Ou “tenda; tabernáculo”.
====

[[v66-13-7]]

^<<v66-13-7,7>>^ E foi-lhe concedido travar guerra com os santos e vencê-los,^&#42;1^ e foi-lhe dada autoridade sobre toda tribo, e povo, e língua, e nação.

[NOTE]
====
. “E foi-lhe concedido . . . vencê-los”, אVg; P47ACArm omitem isso.
====

[[v66-13-8]]

^<<v66-13-8,8>>^ E todos os que moram na terra a^&#42;1^ adorarão; o nome de nem sequer um deles está inscrito no rolo da vida do Cordeiro que foi morto, desde a fundação^&#42;2^ do mundo.

[NOTE]
====
. Ou “o”.
. Lit.: “o lançamento para baixo [de semente]”. Gr.: ka·ta·bo·lés.
====

[[v66-13-9]]

^<<v66-13-9,9>>^ Se alguém tiver ouvido, ouça.

[[v66-13-10]]

^<<v66-13-10,10>>^ Se alguém [é destinado] ao cativeiro, ele vai ao cativeiro. Se alguém matar com a espada, terá de ser morto com a espada. Aqui é que significa a perseverança e a fé dos santos.

[[v66-13-11]]

^<<v66-13-11,11>>^ E eu vi outra fera ascender da terra, e ela tinha dois chifres semelhantes aos dum cordeiro, mas começou a falar como dragão.

[[v66-13-12]]

^<<v66-13-12,12>>^ E exerce toda a autoridade da primeira fera à vista dela. E ela faz a terra e os que moram nela adorar a primeira fera, cujo golpe mortal ficou curado.

[[v66-13-13]]

^<<v66-13-13,13>>^ E ela realiza grandes sinais, para fazer até mesmo fogo descer do céu para a terra à vista da humanidade.

[[v66-13-14]]

^<<v66-13-14,14>>^ E desencaminha os que moram na terra, por causa dos sinais que lhe foi concedido realizar à vista da fera, ao passo que diz aos que moram na terra que façam uma imagem da fera que^&#42;1^ sofrera o golpe de espada e ainda assim reviveu.

[NOTE]
====
. Lit.: “quem”.
====

[[v66-13-15]]

^<<v66-13-15,15>>^ E foi-lhe concedido dar fôlego^&#42;1^ à imagem da fera, de modo que a imagem da fera falasse e fizesse matar a todos os que de modo algum adorassem a imagem da fera.

[NOTE]
====
. Ou “espírito; força ativa”. Gr.: pneú·ma; lat.: spí·ri·tum; J17,18,22(hebr.): rú·ahh.
====

[[v66-13-16]]

^<<v66-13-16,16>>^ E ela põe a todas as pessoas sob compulsão, pequenos e grandes, e ricos e pobres, e livres e escravos, para que dêem a estes uma marca na sua mão direita ou na sua testa,

[[v66-13-17]]

^<<v66-13-17,17>>^ e^&#42;1^ para que ninguém possa comprar ou vender, exceto aquele que tiver a marca,^&#42;2^ o nome da fera ou o número do seu nome.

[NOTE]
====
. “E”, P47אcAVg; א°CSyh omitem isso.
. Lit.: “gravura; talho”. Gr.: khá·rag·ma; J18,22(hebr.): hat·táw, “o tau”, letra hebr. correspondente à letra “T” em português. Veja Ez 9:4 n.
====

[[v66-13-18]]

^<<v66-13-18,18>>^ Aqui é que está a sabedoria: Quem tiver inteligência calcule o número da fera, pois é número de homem; e o seu número é seiscentos e sessenta e seis.^&#42;1^

[NOTE]
====
. “Seiscentos e sessenta e seis”, אA; P47 e ms. Minúsculo 046, χξςʹ, as letras gregas que representam 666. Aqui, o número 6 recebe destaque até o terceiro grau, a saber, 6 mais 60 mais 600.
====

'''

xref:066-apocalipse/066-apocalipse-012.adoc#v66-12-0[&#60; Capítulo Anterior] | <<v66-13-0,Topo>> | xref:066-apocalipse/066-apocalipse-014.adoc#v66-14-0[Próximo Capítulo &#62;]