include::./index.adoc[]

[[v66-2-0]]
=== Apocalipse, 2
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v66-2-1]]

^<<v66-2-1,1>>^ “Ao anjo da congregação em Éfeso escreve: Estas coisas diz aquele que segura na sua direita as sete estrelas, aquele que anda no meio dos sete candelabros de ouro:

[[v66-2-2]]

^<<v66-2-2,2>>^ ‘Conheço as tuas ações, e o teu labor e a [tua] perseverança, e que não podes suportar homens maus, e que puseste à prova os que se dizem apóstolos, mas não são, e que os achaste mentirosos.

[[v66-2-3]]

^<<v66-2-3,3>>^ Também estás mostrando perseverança, e suportaste por causa do meu nome e não esmoreceste.

[[v66-2-4]]

^<<v66-2-4,4>>^ Não obstante, tenho contra ti que tens abandonado o amor que tinhas no princípio.

[[v66-2-5]]

^<<v66-2-5,5>>^ “‘Portanto, lembra-te do que tens decaído, e arrepende-te e pratica as ações anteriores. Se não, virei a ti e removerei o teu candelabro do seu lugar, a menos que te arrependas.

[[v66-2-6]]

^<<v66-2-6,6>>^ Todavia, tens o seguinte, que odeias as ações da seita de Nicolau,^&#42;1^ que eu também odeio.

[NOTE]
====
. Ou “ações dos nicolaítas”.
====

[[v66-2-7]]

^<<v66-2-7,7>>^ Quem tem ouvido ouça o que o espírito diz às congregações: Àquele que vencer concederei comer da árvore da vida, que está no paraíso^&#42;1^ de Deus.’

[NOTE]
====
. “Paraíso”, אAVgSyhJ11-13,16; J17,18,22: “jardim”.
====

[[v66-2-8]]

^<<v66-2-8,8>>^ “E ao anjo da congregação em Esmirna escreve: Estas coisas diz aquele, ‘o Primeiro e o Último’, que ficou morto e passou a viver [novamente]:

[[v66-2-9]]

^<<v66-2-9,9>>^ ‘Conheço a tua tribulação e pobreza — mas tu és rico — e a blasfêmia dos que se dizem judeus, e que não são, mas que são sinagoga de Satanás.

[[v66-2-10]]

^<<v66-2-10,10>>^ Não tenhas medo das coisas que estás para sofrer. Eis que o Diabo estará lançando alguns de vós na prisão, para que sejais plenamente provados, e para que tenhais tribulação por dez dias. Mostra-te fiel até a morte,^&#42;1^ e eu te darei a coroa da vida.

[NOTE]
====
. Ou “mesmo até a morte; mesmo sob perigo de morte”.
====

[[v66-2-11]]

^<<v66-2-11,11>>^ Quem tem ouvido ouça o que o espírito diz às congregações: Àquele que vencer, a segunda morte de modo algum fará dano.’

[[v66-2-12]]

^<<v66-2-12,12>>^ “E ao anjo da congregação em Pérgamo escreve: Estas coisas diz aquele que tem a longa espada afiada de dois gumes:

[[v66-2-13]]

^<<v66-2-13,13>>^ ‘Sei onde estás morando, isto é, onde está o trono de Satanás; contudo, persistes em apegar-te ao meu nome e não negaste a tua fé em mim, mesmo nos dias de Ântipas, minha testemunha, o fiel, que foi morto ao vosso lado, onde Satanás está morando.

[[v66-2-14]]

^<<v66-2-14,14>>^ “‘Não obstante, tenho algumas coisas contra ti, que tens aí os que se apegam ao ensino de Balaão, o qual foi ensinar a Balaque a pôr uma pedra de tropeço diante dos filhos de Israel, para que comessem de coisas sacrificadas a ídolos e cometessem fornicação.

[[v66-2-15]]

^<<v66-2-15,15>>^ Assim, tu tens também os que se apegam igualmente ao ensino da seita de Nicolau.^&#42;1^

[NOTE]
====
. Ou “ensino dos nicolaítas”. Gr.: di·da·khén Ni·ko·la·i·tón; lat.: doc·trí·nam Ni·co·la·i·tá·rum.
====

[[v66-2-16]]

^<<v66-2-16,16>>^ Arrepende-te, portanto. Se não, virei a ti depressa e guerrearei com eles com a longa espada da minha boca.

[[v66-2-17]]

^<<v66-2-17,17>>^ “‘Quem tem ouvido ouça o que o espírito diz às congregações: Àquele que vencer darei do maná escondido,^&#42;1^ e eu lhe darei um seixo^&#42;2^ branco, e no seixo escrito um novo nome, que ninguém conhece, exceto aquele que o recebe.’

[NOTE]
====
. Ou “maná guardado”.
. Lit.: “seixo [de votação]”. Gr.: psé·fon. Veja At 26:10 n.
====

[[v66-2-18]]

^<<v66-2-18,18>>^ “E ao anjo da congregação em Tiatira escreve: Estas coisas diz o Filho de Deus, aquele cujos olhos são como chama ardente e cujos pés são como cobre excelente:

[[v66-2-19]]

^<<v66-2-19,19>>^ ‘Conheço as tuas ações, e teu amor, e fé, e ministério,^&#42;1^ e perseverança, e que as tuas ações mais recentes são mais do que as anteriores.

[NOTE]
====
. “Ministério.” Gr.: di·a·ko·ní·an.
====

[[v66-2-20]]

^<<v66-2-20,20>>^ “‘Não obstante, tenho contra ti que toleras aquela mulher Jezabel, que se chama profetisa, e ela ensina e desencaminha os meus escravos para cometerem fornicação e para comerem coisas sacrificadas a ídolos.

[[v66-2-21]]

^<<v66-2-21,21>>^ E eu lhe dei tempo para se arrepender, mas ela não está disposta a arrepender-se da sua fornicação.

[[v66-2-22]]

^<<v66-2-22,22>>^ Eis que estou para lançá-la num leito de doença, e os que cometem adultério com ela, em grande tribulação, a menos que se arrependam das ações dela.

[[v66-2-23]]

^<<v66-2-23,23>>^ E matarei os filhos dela com praga mortífera,^&#42;1^ de modo que todas as congregações saberão que sou eu quem pesquisa os rins^&#42;2^ e os corações, e eu vos darei individualmente segundo as vossas ações.

[NOTE]
====
. Ou “com morte”.
. Ou “as mais profundas emoções”. Lit.: “rins”. Veja Je (11:20; 17:10; 20:12).
====

[[v66-2-24]]

^<<v66-2-24,24>>^ “‘No entanto, digo aos demais de vós, os que estais em Tiatira, a todos os que não têm este ensino, aos mesmos que não chegaram a conhecer as “coisas profundas de Satanás”, conforme eles dizem: Não ponho sobre vós nenhum outro fardo.

[[v66-2-25]]

^<<v66-2-25,25>>^ Assim mesmo, apegai-vos ao que tendes até que eu venha.

[[v66-2-26]]

^<<v66-2-26,26>>^ E àquele que vencer e observar as minhas ações até o fim,^&#42;1^ eu darei autoridade sobre as nações,

[NOTE]
====
. Ou “fim completo”. Gr.: té·lous.
====

[[v66-2-27]]

^<<v66-2-27,27>>^ e ele pastoreará as pessoas com vara de ferro, de modo que serão despedaçadas como vasos de barro,^&#42;1^ assim como recebi de meu Pai,

[NOTE]
====
. Lit.: “com vara de ferro, assim como os vasos de barro são despedaçados”.
====

[[v66-2-28]]

^<<v66-2-28,28>>^ e eu lhe darei a estrela da manhã.

[[v66-2-29]]

^<<v66-2-29,29>>^ Quem tem ouvido ouça o que o espírito diz às congregações.’

'''

xref:066-apocalipse/066-apocalipse-001.adoc#v66-1-0[&#60; Capítulo Anterior] | <<v66-2-0,Topo>> | xref:066-apocalipse/066-apocalipse-003.adoc#v66-3-0[Próximo Capítulo &#62;]