include::./index.adoc[]

[[v66-12-0]]
=== Apocalipse, 12
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v66-12-1]]

^<<v66-12-1,1>>^ E viu-se um grande sinal no céu, uma mulher vestida do sol e tendo a lua debaixo dos seus pés, e na sua cabeça havia uma coroa de doze estrelas,

[[v66-12-2]]

^<<v66-12-2,2>>^ e ela estava grávida. E ela clama nas suas dores e na sua agonia de dar à luz.

[[v66-12-3]]

^<<v66-12-3,3>>^ E viu-se outro sinal no céu, e eis um grande dragão cor de fogo, com sete cabeças e dez chifres, e nas suas cabeças sete diademas;

[[v66-12-4]]

^<<v66-12-4,4>>^ e a sua cauda arrasta um terço das estrelas do céu, e as lançou para baixo à terra. E o dragão^&#42;1^ ficou parado diante da mulher, que estava para dar à luz, para que, quando desse à luz, pudesse devorar-lhe o filho.

[NOTE]
====
. Gr.: drá·kon; lat.: drá·co.
====

[[v66-12-5]]

^<<v66-12-5,5>>^ E ela deu à luz um filho, um varão, que há de pastorear todas as nações com vara de ferro. E o filho dela foi arrebatado para Deus e para o seu trono.

[[v66-12-6]]

^<<v66-12-6,6>>^ E a mulher fugiu para o ermo, onde ela tem um lugar preparado por Deus, para que a alimentem ali por mil duzentos e sessenta dias.

[[v66-12-7]]

^<<v66-12-7,7>>^ E irrompeu uma guerra no céu: Miguel^&#42;1^ e os seus anjos batalhavam com o dragão, e o dragão e os seus anjos batalhavam,

[NOTE]
====
. Significando: “Quem É Semelhante a Deus?” Gr.: Mi·kha·él.
====

[[v66-12-8]]

^<<v66-12-8,8>>^ mas ele não prevaleceu, nem se achou mais lugar para eles no céu.

[[v66-12-9]]

^<<v66-12-9,9>>^ Assim foi lançado para baixo o grande dragão, a serpente original, o chamado Diabo e Satanás, que está desencaminhando toda a terra habitada;^&#42;1^ ele foi lançado para baixo, à terra, e os seus anjos foram lançados para baixo junto com ele.

[NOTE]
====
. Lit.: “a habitada”. Gr.: oi·kou·mé·nen, fem. sing. referindo-se à terra.
====

[[v66-12-10]]

^<<v66-12-10,10>>^ E ouvi uma voz alta no céu dizer:
“Agora se realizou a salvação,^&#42;1^ e o poder,^&#42;2^ e o reino de nosso Deus, e a autoridade^&#42;3^ do seu Cristo, porque foi lançado para baixo o acusador dos nossos irmãos, o qual os acusa dia e noite perante o nosso Deus!

[NOTE]
====
. Ou “vitória”.
. “Poder.” Gr.: dý·na·mis; lat.: vír·tus; J17(hebr.): we‛uz·zóh, “e sua força”.
. “Autoridade.” Gr.: e·xou·sí·a; lat.: po·té·stas; J17,18,22(hebr.): u·mem·shé·leth, “e a autoridade do”.
====

[[v66-12-11]]

^<<v66-12-11,11>>^ E eles o venceram por causa do sangue do Cordeiro e por causa da palavra do seu testemunho, e não amaram as suas almas,^&#42;1^ nem mesmo ao encararem a morte.^&#42;2^

[NOTE]
====
. Ou “suas vidas”. Lit.: “sua alma”.
. Ou “mesmo apesar do perigo de morte”. Lit.: “até a morte”.
====

[[v66-12-12]]

^<<v66-12-12,12>>^ Por esta razão, regozijai-vos, ó céus, e vós os que neles residis! Ai da terra e do mar, porque desceu a vós o Diabo, tendo grande ira, sabendo que ele tem um curto período de tempo.”

[[v66-12-13]]

^<<v66-12-13,13>>^ Ora, quando o dragão se viu lançado à terra, perseguiu a mulher que dera à luz o filho varão.

[[v66-12-14]]

^<<v66-12-14,14>>^ Mas, deram-se à mulher as duas asas da grande águia, para que voasse ao ermo, para o seu lugar; ali é que ela é alimentada por um tempo, e tempos, e metade de um tempo,^&#42;1^ longe da face da serpente.

[NOTE]
====
. Ou “por um tempo designado, e tempos designados, e metade dum tempo designado”. Gr.: kai·rón kai kai·roús kai hé·mi·sy kai·roú. Veja Da 4:16 n.; Da 12:7 n.: “metade”.
====

[[v66-12-15]]

^<<v66-12-15,15>>^ E a serpente expeliu da sua boca água como um rio atrás da mulher, para que se afogasse no rio.

[[v66-12-16]]

^<<v66-12-16,16>>^ Mas a terra veio em ajuda da mulher, e a terra abriu a sua boca e tragou o rio que o dragão lançou da sua boca.

[[v66-12-17]]

^<<v66-12-17,17>>^ E o dragão ficou furioso com a mulher e foi travar guerra com os remanescentes da sua semente, que observam os mandamentos de Deus e têm a obra de dar testemunho^&#42;1^ de Jesus.

[NOTE]
====
. “Obra de dar testemunho.” Gr.: mar·ty·rí·an; lat.: te·sti·mó·ni·um.
====

'''

xref:066-apocalipse/066-apocalipse-011.adoc#v66-11-0[&#60; Capítulo Anterior] | <<v66-12-0,Topo>> | xref:066-apocalipse/066-apocalipse-013.adoc#v66-13-0[Próximo Capítulo &#62;]