include::./index.adoc[]

[[v46-16-0]]
=== 1 Coríntios, 16
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v46-16-1]]

^<<v46-16-1,1>>^ Agora, quanto à coleta que é para os santos, assim como dei ordens às congregações da Galácia, fazei do mesmo modo também vós.

[[v46-16-2]]

^<<v46-16-2,2>>^ Todo primeiro dia da semana, cada um de vós, na sua própria casa, ponha algo de lado, em reserva, conforme tiver prosperado, para que, quando eu chegar, não se façam então as coletas.

[[v46-16-3]]

^<<v46-16-3,3>>^ Mas, quando eu for aí, aos homens que vós aprovardes por cartas, a estes eu enviarei para levarem a vossa bondosa dádiva a Jerusalém.

[[v46-16-4]]

^<<v46-16-4,4>>^ No entanto, se for próprio que eu também vá para lá, irão comigo.

[[v46-16-5]]

^<<v46-16-5,5>>^ Mas, eu hei de ir ter convosco depois de ter passado pela Macedônia, pois vou passar pela Macedônia;

[[v46-16-6]]

^<<v46-16-6,6>>^ e talvez eu até fique ou passe o inverno convosco, para que possais acompanhar-me parte do caminho para onde vou.

[[v46-16-7]]

^<<v46-16-7,7>>^ Pois não quero ver-vos agora na [minha] passagem, porque espero permanecer convosco algum tempo, se Jeová^&#42;1^ permitir.

[NOTE]
====
. Veja Ap. 1D.
====

[[v46-16-8]]

^<<v46-16-8,8>>^ Mas, vou permanecer em Éfeso até [a festividade de] Pentecostes;

[[v46-16-9]]

^<<v46-16-9,9>>^ porque se me abriu uma porta larga para atividade, mas há muitos opositores.

[[v46-16-10]]

^<<v46-16-10,10>>^ No entanto, se Timóteo chegar, cuidai de que fique livre de temor entre vós, pois ele está realizando a obra de Jeová,^&#42;1^ assim como eu.

[NOTE]
====
. Veja Ap. 1D.
====

[[v46-16-11]]

^<<v46-16-11,11>>^ Portanto, que ninguém o menospreze. Acompanhai-o parte do caminho em paz, para que vá ter comigo, porque estou esperando por ele com os irmãos.

[[v46-16-12]]

^<<v46-16-12,12>>^ Agora, quanto a Apolo, nosso irmão, supliquei-lhe muitíssimo que fosse ter convosco com os irmãos, contudo, não foi absolutamente da vontade dele ir agora; mas ele irá quando tiver a oportunidade.

[[v46-16-13]]

^<<v46-16-13,13>>^ Ficai despertos, mantende-vos firmes na fé, procedei como homens, tornai-vos^&#42;1^ poderosos.

[NOTE]
====
. Ou “sede”.
====

[[v46-16-14]]

^<<v46-16-14,14>>^ Que todos os vossos assuntos se realizem com amor.

[[v46-16-15]]

^<<v46-16-15,15>>^ Exorto-vos^&#42;1^ agora, irmãos: sabeis que a família de Estéfanas é as primícias da Acaia^&#42;2^ e que eles se põem a ministrar aos santos.

[NOTE]
====
. Ou: “Rogo-vos.”
. A província romana do sul da Grécia, cuja capital era Corinto.
====

[[v46-16-16]]

^<<v46-16-16,16>>^ Que também vós vos sujeiteis a pessoas dessa espécie e a todo aquele que coopera e labuta.

[[v46-16-17]]

^<<v46-16-17,17>>^ Mas, eu me alegro com a presença^&#42;1^ de Estéfanas, e de Fortunato, e de Acaico, porque compensaram a vossa ausência aqui.

[NOTE]
====
. Veja Ap. 5B.
====

[[v46-16-18]]

^<<v46-16-18,18>>^ Pois eles reanimaram o meu espírito e o vosso. Portanto, reconhecei a homens desta sorte.

[[v46-16-19]]

^<<v46-16-19,19>>^ As congregações da Ásia enviam-vos os seus cumprimentos. Áquila e Prisca, junto com a congregação que está na casa deles, cumprimentam-vos cordialmente no Senhor.

[[v46-16-20]]

^<<v46-16-20,20>>^ Todos os irmãos vos cumprimentam. Cumprimentai-vos uns aos outros com beijo santo.

[[v46-16-21]]

^<<v46-16-21,21>>^ [Aqui está] o meu cumprimento, o de Paulo, pela minha própria mão.

[[v46-16-22]]

^<<v46-16-22,22>>^ Se alguém não tiver afeição pelo Senhor, seja amaldiçoado. Vem, nosso Senhor!^&#42;1^

[NOTE]
====
. Se a transliteração do aram. para o gr. for Ma·rá·na tha. Se for transliterado Ma·rán a·thá: “Nosso Senhor está vindo”, ou: “Nosso Senhor veio.”
====

[[v46-16-23]]

^<<v46-16-23,23>>^ A benignidade imerecida do Senhor Jesus seja convosco.

[[v46-16-24]]

^<<v46-16-24,24>>^ Meu amor seja com todos vós em união com Cristo Jesus.

'''

xref:046-1-corintios/046-1-corintios-015.adoc#v46-15-0[&#60; Capítulo Anterior] | <<v46-16-0,Topo>> | xref:047-2-corintios/047-2-corintios-001.adoc#v47-1-0[Próximo Capítulo &#62;]