include::./index.adoc[]

[[v46-5-0]]
=== 1 Coríntios, 5
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v46-5-1]]

^<<v46-5-1,1>>^ Realmente, relata-se entre vós fornicação,^&#42;1^ e fornicação tal como nem há entre as nações, que certo [homem] tenha por esposa [a] de [seu] pai.^&#42;2^

[NOTE]
====
. “Fornicação.” Gr.: por·neí·a; lat.: for·ni·cá·ti·o. Veja Núm 14:33 n.: “fornicação”; Ap. 5A.
. Ou “que certo [homem] tenha a esposa de [seu] pai”.
====

[[v46-5-2]]

^<<v46-5-2,2>>^ E estais vós enfunados, e nem ao menos pranteastes, a fim de que o homem que cometeu esta ação fosse tirado do vosso meio?

[[v46-5-3]]

^<<v46-5-3,3>>^ Eu, da minha parte, embora ausente em corpo, mas presente em espírito, certamente, como se estivesse presente, já tenho julgado o homem que agiu de tal modo,

[[v46-5-4]]

^<<v46-5-4,4>>^ para que, em nome de nosso Senhor Jesus, quando estiverdes ajuntados, também o meu espírito com o poder de nosso Senhor Jesus,

[[v46-5-5]]

^<<v46-5-5,5>>^ entregueis tal homem a Satanás, para a destruição da carne, a fim de que o espírito seja salvo no dia do Senhor.

[[v46-5-6]]

^<<v46-5-6,6>>^ A vossa [razão para] jactância não é excelente. Não sabeis que um pouco de fermento leveda a massa toda?

[[v46-5-7]]

^<<v46-5-7,7>>^ Retirai o velho fermento, para que sejais massa nova, conforme estiverdes livres do levedo. Pois, deveras, Cristo, a nossa páscoa, já tem sido sacrificado.

[[v46-5-8]]

^<<v46-5-8,8>>^ Conseqüentemente, guardemos a festividade, não com o velho fermento, nem com o fermento de maldade e iniqüidade, mas com os pães não fermentados da sinceridade e da verdade.

[[v46-5-9]]

^<<v46-5-9,9>>^ Eu vos escrevi na minha carta que cesseis de manter convivência com fornicadores,

[[v46-5-10]]

^<<v46-5-10,10>>^ não [querendo dizer] inteiramente com os fornicadores deste mundo, ou [com] os gananciosos e os extorsores, ou [com] os idólatras. Senão teríeis realmente de sair do mundo.

[[v46-5-11]]

^<<v46-5-11,11>>^ Mas, eu vos escrevo agora para que cesseis de ter convivência com^&#42;1^ qualquer que se chame irmão, que for fornicador, ou ganancioso, ou idólatra, ou injuriador, ou beberrão, ou extorsor, nem sequer comendo com tal homem.

[NOTE]
====
. Lit.: “não vos mistureis com”. Gr.: me sy·na·na·mí·gny·sthai; lat.: non com·mí·sce·ri.
====

[[v46-5-12]]

^<<v46-5-12,12>>^ Pois, o que tenho eu que ver com o julgamento dos de fora? Não julgais vós os de dentro,

[[v46-5-13]]

^<<v46-5-13,13>>^ ao passo que Deus julga os de fora? “Removei o [homem] iníquo de entre vós.”

'''

xref:046-1-corintios/046-1-corintios-004.adoc#v46-4-0[&#60; Capítulo Anterior] | <<v46-5-0,Topo>> | xref:046-1-corintios/046-1-corintios-006.adoc#v46-6-0[Próximo Capítulo &#62;]