include::./index.adoc[]

[[v46-7-0]]
=== 1 Coríntios, 7
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v46-7-1]]

^<<v46-7-1,1>>^ Agora, quanto às coisas sobre as quais escrevestes, é bom que o homem não toque em mulher;

[[v46-7-2]]

^<<v46-7-2,2>>^ contudo, por causa da prevalência da fornicação,^&#42;1^ tenha cada homem a sua própria esposa e tenha cada mulher o seu próprio marido.

[NOTE]
====
. “Prevalência da fornicação.” Lit.: “fornicações”.
====

[[v46-7-3]]

^<<v46-7-3,3>>^ O marido renda à esposa o que lhe é devido; mas, faça a esposa também o mesmo para com o marido.

[[v46-7-4]]

^<<v46-7-4,4>>^ A esposa não exerce autoridade sobre o seu próprio corpo, mas sim o seu marido; do mesmo modo, também, o marido não exerce autoridade sobre o seu próprio corpo, mas sim a sua esposa.

[[v46-7-5]]

^<<v46-7-5,5>>^ Não vos priveis um ao outro [disso], exceto por consentimento mútuo, por um tempo designado, para que possais devotar tempo à oração e possais ajuntar-vos novamente, a fim de que Satanás não vos tente pela vossa falta de comedimento.

[[v46-7-6]]

^<<v46-7-6,6>>^ No entanto, digo isso como concessão,^&#42;1^ não como mandado.^&#42;2^

[NOTE]
====
. Lit.: “opinião conjunta”.
. “Mandado.” Lit.: “imposição”.
====

[[v46-7-7]]

^<<v46-7-7,7>>^ Mas, eu queria que todos os homens fossem como eu. Não obstante, cada um tem o seu próprio dom da parte de Deus, um deste modo, outro daquele modo.

[[v46-7-8]]

^<<v46-7-8,8>>^ Digo, porém, aos não casados e às viúvas, que é bom que permaneçam assim como eu.

[[v46-7-9]]

^<<v46-7-9,9>>^ Mas, se não tiverem autodomínio, casem-se, pois é melhor casar-se do que estar inflamado [de paixão].

[[v46-7-10]]

^<<v46-7-10,10>>^ Aos casados dou ordens, contudo, não eu, mas o Senhor, que a esposa não se afaste de seu marido;

[[v46-7-11]]

^<<v46-7-11,11>>^ mas, se ela realmente se afastar, que permaneça sem se casar, ou, senão, que se reconcilie novamente com seu marido; e o marido não deve deixar a sua esposa.

[[v46-7-12]]

^<<v46-7-12,12>>^ Mas, aos outros digo eu, sim, eu, não o Senhor: Se algum irmão tiver esposa incrédula, e ela, contudo, estiver disposta a morar com ele, que ele não a deixe;

[[v46-7-13]]

^<<v46-7-13,13>>^ e a mulher que tiver marido incrédulo, e ele, contudo, estiver disposto a morar com ela, não deixe seu marido.

[[v46-7-14]]

^<<v46-7-14,14>>^ Pois o marido incrédulo está santificado em relação à [sua] esposa, e a esposa incrédula está santificada em relação ao irmão; de outro modo, os vossos filhos seriam realmente impuros, mas agora são santos.

[[v46-7-15]]

^<<v46-7-15,15>>^ Mas, se o incrédulo passar a afastar-se, deixa-o afastar-se; o irmão ou a irmã não está em servidão em tais circunstâncias, mas Deus vos chamou à paz.

[[v46-7-16]]

^<<v46-7-16,16>>^ Pois, esposa, como sabes se não hás de salvar o [teu] marido? Ou, marido, como sabes se não hás de salvar a [tua] esposa?

[[v46-7-17]]

^<<v46-7-17,17>>^ Apenas, conforme o quinhão que Jeová^&#42;1^ tem dado a cada um, ande cada um assim como Deus^&#42;2^ o chamou. E assim ordeno em todas as congregações.

[NOTE]
====
. “Jeová”, em harmonia com J28, Ro 12:3 e 2Co 10:13; P46אABCD(gr.): ho Ký·ri·os; Syh e TR: “Deus”. Veja Ap. 1D.
. “Deus”, P46אABCDVgSyp; Syh e TR: “o Senhor”; J7,8,10: “Jeová”.
====

[[v46-7-18]]

^<<v46-7-18,18>>^ Foi alguém chamado [no estado] circunciso? Que não se torne incircunciso. Tem alguém sido chamado na incircuncisão? Não seja circuncidado.

[[v46-7-19]]

^<<v46-7-19,19>>^ A circuncisão não significa coisa alguma e a incircuncisão não significa coisa alguma, mas [sim] a observância dos mandamentos de Deus.

[[v46-7-20]]

^<<v46-7-20,20>>^ Em qualquer estado^&#42;1^ em que cada um foi chamado, neste permaneça.

[NOTE]
====
. Ou “chamada”.
====

[[v46-7-21]]

^<<v46-7-21,21>>^ Foste chamado quando escravo? Não te preocupes com isso; mas, se também puderes ficar livre, então aproveita a oportunidade.

[[v46-7-22]]

^<<v46-7-22,22>>^ Pois, todo aquele, no Senhor, que foi chamado quando escravo, é o liberto do Senhor; igualmente, aquele que foi chamado quando era liberto, é escravo de Cristo.

[[v46-7-23]]

^<<v46-7-23,23>>^ Vós fostes comprados por um preço; parai de vos tornardes escravos de homens.

[[v46-7-24]]

^<<v46-7-24,24>>^ Qualquer que tenha sido a condição em que cada um foi chamado, irmãos, permaneça nela associado com Deus.

[[v46-7-25]]

^<<v46-7-25,25>>^ Agora, concernente às virgens, não tenho mandado da parte do Senhor, mas dou a minha opinião como alguém para com quem o Senhor mostrou misericórdia para ser fiel.

[[v46-7-26]]

^<<v46-7-26,26>>^ Portanto, acho bom, em vista da necessidade aqui conosco, que é bom que o homem continue assim como está.

[[v46-7-27]]

^<<v46-7-27,27>>^ Estás amarrado a uma esposa? Pára de buscar livramento. Estás solto duma esposa? Pára de buscar esposa.

[[v46-7-28]]

^<<v46-7-28,28>>^ Porém, mesmo se te casares, não cometes pecado. E, se uma [pessoa] virgem^&#42;1^ se casar, não comete pecado. No entanto, os que o fizerem, terão tribulação na sua carne. Mas eu vos estou poupando.

[NOTE]
====
. “Uma [pessoa] virgem”, B.
====

[[v46-7-29]]

^<<v46-7-29,29>>^ Outrossim, digo o seguinte, irmãos: o tempo que resta é reduzido. Doravante, os que tiverem esposas sejam como se não as tivessem,

[[v46-7-30]]

^<<v46-7-30,30>>^ e também os que choram sejam como os que não choram, e os que se alegram, como os que não se alegram, e os que compram, como os que não possuem,

[[v46-7-31]]

^<<v46-7-31,31>>^ e os que fazem uso do mundo, como os que não o usam plenamente; porque está mudando a cena deste mundo.

[[v46-7-32]]

^<<v46-7-32,32>>^ Deveras, quero que estejais livres de ansiedade. O homem não casado está ansioso das coisas do Senhor, de como pode ganhar a aprovação do Senhor.

[[v46-7-33]]

^<<v46-7-33,33>>^ Mas o homem casado está ansioso das coisas do mundo, de como pode ganhar a aprovação de sua esposa,

[[v46-7-34]]

^<<v46-7-34,34>>^ e ele está dividido. Além disso, a mulher não casada, e a virgem, está ansiosa das coisas do Senhor, para que seja santa tanto no seu corpo como no seu espírito. No entanto, a mulher casada está ansiosa das coisas do mundo, de como pode ganhar a aprovação de seu marido.

[[v46-7-35]]

^<<v46-7-35,35>>^ Mas, digo isso para a vossa vantagem pessoal, não para vos armar um laço, mas para induzir-vos ao que é decente e ao que significa assistir constantemente ao Senhor, sem distração.

[[v46-7-36]]

^<<v46-7-36,36>>^ Mas, se alguém pensa que se está comportando de modo impróprio para com a sua virgindade,^&#42;1^ se esta^&#42;2^ estiver além da flor da juventude,^&#42;3^ e este é o modo em que deve ocorrer, faça ele o que quiser; ele não peca. Casem-se.

[NOTE]
====
. Ou “virgem”. Gr.: par·thé·non; lat.: vír·gi·ne.
. Ou “ela”.
. Lit.: “além da flor da vida”. Gr.: hy·pér·ak·mos; lat.: su·per·a·dúl·ta.
====

[[v46-7-37]]

^<<v46-7-37,37>>^ Mas, se alguém estiver resolvido no seu coração, não tendo necessidade, mas tiver autoridade sobre a sua própria vontade e tiver feito esta decisão no seu próprio coração, de manter a sua própria virgindade, ele fará bem.

[[v46-7-38]]

^<<v46-7-38,38>>^ Conseqüentemente, também faz bem aquele que der a sua virgindade em casamento, mas, aquele que não a der em casamento fará melhor.

[[v46-7-39]]

^<<v46-7-39,39>>^ A esposa está amarrada durante todo o tempo em que seu marido estiver vivo. Mas, se o seu marido adormecer [na morte], ela está livre para se casar com quem quiser, somente no^&#42;1^ Senhor.

[NOTE]
====
. Ou “se ele estiver em união com”.
====

[[v46-7-40]]

^<<v46-7-40,40>>^ Ela será mais feliz, porém, se permanecer assim como está, segundo a minha opinião. Acho certamente ter também o espírito de Deus.

'''

xref:046-1-corintios/046-1-corintios-006.adoc#v46-6-0[&#60; Capítulo Anterior] | <<v46-7-0,Topo>> | xref:046-1-corintios/046-1-corintios-008.adoc#v46-8-0[Próximo Capítulo &#62;]