include::./index.adoc[]

[[v46-9-0]]
=== 1 Coríntios, 9
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v46-9-1]]

^<<v46-9-1,1>>^ Não estou livre? Não sou apóstolo? Não tenho visto a Jesus, nosso Senhor? Não sois vós a minha obra no Senhor?

[[v46-9-2]]

^<<v46-9-2,2>>^ Se eu não for apóstolo para os outros, mui certamente o sou para vós, pois vós sois o selo que confirma o meu apostolado em relação ao Senhor.

[[v46-9-3]]

^<<v46-9-3,3>>^ Minha defesa perante os que me examinam é a seguinte:

[[v46-9-4]]

^<<v46-9-4,4>>^ Será que não temos autoridade para comer e beber?

[[v46-9-5]]

^<<v46-9-5,5>>^ Será que não temos autoridade para levar conosco uma irmã como esposa, assim como os demais apóstolos e os irmãos do Senhor, e Cefas?

[[v46-9-6]]

^<<v46-9-6,6>>^ Ou é somente Barnabé e eu que não temos autoridade para nos abster de trabalho [secular]?

[[v46-9-7]]

^<<v46-9-7,7>>^ Quem é que jamais serve como soldado às suas próprias custas?^&#42;1^ Quem planta um vinhedo e não come do seu fruto? Ou quem pastoreia um rebanho e não come do leite do rebanho?

[NOTE]
====
. Lit.: “salários”. Lat.: sti·pén·di·is.
====

[[v46-9-8]]

^<<v46-9-8,8>>^ Falo estas coisas segundo o critério humano? Ou não diz também a Lei estas mesmas coisas?

[[v46-9-9]]

^<<v46-9-9,9>>^ Pois está escrito na lei de Moisés: “Não deves açaimar o touro quando debulha o grão.” Importa-se Deus com touros?

[[v46-9-10]]

^<<v46-9-10,10>>^ Ou é ao todo por nossa causa que ele diz isso? Realmente, foi escrito por nossa causa, porque o homem que lavra deve lavrar em esperança e o homem que debulha deve fazê-lo na esperança de ser participante.

[[v46-9-11]]

^<<v46-9-11,11>>^ Se temos semeado para vós coisas espirituais, é grande coisa que havemos de ceifar de vós coisas para a carne?

[[v46-9-12]]

^<<v46-9-12,12>>^ Se outros homens têm parte nesta autoridade sobre vós, não a temos nós ainda muito mais? Não obstante, não fizemos uso desta autoridade, mas estamos suportando todas as coisas, a fim de não oferecermos nenhum impedimento às boas novas a respeito do Cristo.

[[v46-9-13]]

^<<v46-9-13,13>>^ Não sabeis que os homens que cumprem deveres sagrados comem das coisas do templo e que os que assistem constantemente junto ao altar têm uma porção para si mesmos junto com o altar?

[[v46-9-14]]

^<<v46-9-14,14>>^ Deste modo, também, o Senhor ordenou que os que proclamam as boas novas vivam por meio das boas novas.

[[v46-9-15]]

^<<v46-9-15,15>>^ Mas, eu não tenho feito uso de nem uma única destas [provisões]. Deveras, não escrevi estas coisas para que se tornasse assim no meu caso, pois, para mim seria melhor morrer, do que — ninguém me vai invalidar a minha razão para jactância!

[[v46-9-16]]

^<<v46-9-16,16>>^ Se eu, agora, estou declarando as boas novas, não é razão para me jactar, pois me é imposta a necessidade. Realmente, ai de mim se eu não declarasse as boas novas!

[[v46-9-17]]

^<<v46-9-17,17>>^ Se eu realizar isso espontaneamente, tenho uma recompensa; mas, se eu o fizer contra a minha vontade, mesmo assim fui incumbido duma mordomia.

[[v46-9-18]]

^<<v46-9-18,18>>^ Qual é então a minha recompensa? É que, declarando as boas novas, eu forneça as boas novas sem custo, a fim de não abusar da minha autoridade nas boas novas.

[[v46-9-19]]

^<<v46-9-19,19>>^ Pois, embora eu esteja livre de todos, fiz-me escravo de todos, para ganhar o máximo [número deles].

[[v46-9-20]]

^<<v46-9-20,20>>^ E, assim, para os judeus tornei-me como judeu, para ganhar judeus; para os debaixo de lei tornei-me como debaixo de lei, embora eu mesmo não estivesse debaixo de lei, para ganhar os debaixo de lei.

[[v46-9-21]]

^<<v46-9-21,21>>^ Para os sem lei tornei-me como sem lei, embora eu não estivesse sem lei para com Deus, mas [estivesse] debaixo de lei para com Cristo, para ganhar os sem lei.

[[v46-9-22]]

^<<v46-9-22,22>>^ Para os fracos tornei-me fraco, para ganhar os fracos. Tornei-me todas as coisas para pessoas de toda sorte, para de todos os modos salvar alguns.

[[v46-9-23]]

^<<v46-9-23,23>>^ Mas, faço todas as coisas pela causa das boas novas, para tornar-me compartilhador delas com [outros].

[[v46-9-24]]

^<<v46-9-24,24>>^ Não sabeis que os corredores numa corrida correm todos, mas apenas um recebe o prêmio? Correi de tal modo, que o possais alcançar.

[[v46-9-25]]

^<<v46-9-25,25>>^ Além disso, cada homem que toma parte numa competição exerce autodomínio em todas as coisas. Ora eles, naturalmente, fazem isso para obterem uma coroa corruptível, mas nós, uma incorruptível.

[[v46-9-26]]

^<<v46-9-26,26>>^ Portanto, corro de modo nada incerto; dirijo os meus golpes de modo a não golpear o ar;

[[v46-9-27]]

^<<v46-9-27,27>>^ mas, surro^&#42;1^ o meu corpo e o conduzo como escravo, para que, depois de ter pregado a outros, eu mesmo não venha a ser de algum modo reprovado.

[NOTE]
====
. Lit.: “soco sob (o olho)”.
====

'''

xref:046-1-corintios/046-1-corintios-008.adoc#v46-8-0[&#60; Capítulo Anterior] | <<v46-9-0,Topo>> | xref:046-1-corintios/046-1-corintios-010.adoc#v46-10-0[Próximo Capítulo &#62;]