include::./index.adoc[]

[[v46-13-0]]
=== 1 Coríntios, 13
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v46-13-1]]

^<<v46-13-1,1>>^ Se eu falar em línguas de homens e de anjos, mas não tiver amor, tenho-me tornado um [pedaço de] latão que ressoa ou um címbalo que retine.

[[v46-13-2]]

^<<v46-13-2,2>>^ E se eu tiver o dom de profetizar e estiver familiarizado com todos os segredos sagrados e com todo o conhecimento, e se eu tiver toda a fé, de modo a transplantar^&#42;1^ montanhas, mas não tiver amor, nada sou.

[NOTE]
====
. Lit.: “a estar transferindo”.
====

[[v46-13-3]]

^<<v46-13-3,3>>^ E se eu der todos os meus bens para alimentar os outros, e se eu entregar o meu corpo, para jactar-me, mas não tiver amor, de nada me aproveita.

[[v46-13-4]]

^<<v46-13-4,4>>^ O amor^&#42;1^ é longânime e benigno. O amor não é ciumento, não se gaba, não se enfuna,

[NOTE]
====
. “Amor.” Gr.: he a·gá·pe.
====

[[v46-13-5]]

^<<v46-13-5,5>>^ não se comporta indecentemente, não procura os seus próprios interesses, não fica encolerizado. Não leva em conta o dano.

[[v46-13-6]]

^<<v46-13-6,6>>^ Não se alegra com a injustiça, mas alegra-se com a verdade.

[[v46-13-7]]

^<<v46-13-7,7>>^ Suporta todas as coisas, acredita todas as coisas, espera todas as coisas, persevera em todas as coisas.

[[v46-13-8]]

^<<v46-13-8,8>>^ O amor nunca falha. Mas, quer haja [dons de] profetizar, serão eliminados; quer haja línguas, cessarão; quer haja conhecimento, será eliminado.^&#42;1^

[NOTE]
====
. Lit.: “será tornado sem efeito”.
====

[[v46-13-9]]

^<<v46-13-9,9>>^ Pois temos^&#42;1^ conhecimento parcial e profetizamos parcialmente;

[NOTE]
====
. Ou “assimilamos”.
====

[[v46-13-10]]

^<<v46-13-10,10>>^ mas, quando chegar o que é completo, será eliminado o que é parcial.

[[v46-13-11]]

^<<v46-13-11,11>>^ Quando eu era pequenino, costumava falar como pequenino, pensar como pequenino, raciocinar como pequenino; mas agora que me tornei homem, eliminei as [características] de pequenino.

[[v46-13-12]]

^<<v46-13-12,12>>^ Pois, atualmente vemos em contorno indefinido^&#42;1^ por meio dum espelho de metal, mas então será face a face. Atualmente eu sei em parte,^&#42;2^ mas então saberei exatamente, assim como também sou conhecido exatamente.

[NOTE]
====
. Lit.: “numa expressão obscura”.
. Ou “assimilo conhecimento parcial”.
====

[[v46-13-13]]

^<<v46-13-13,13>>^ Agora, porém, permanecem a fé, a esperança, o amor, estes três; mas o maior destes é o amor.^&#42;1^

[NOTE]
====
. “Amor.” Gr.: a·gá·pe; lat.: cá·ri·tas; J17,18(hebr.): ha·’a·haváh, “o amor”.
====

'''

xref:046-1-corintios/046-1-corintios-012.adoc#v46-12-0[&#60; Capítulo Anterior] | <<v46-13-0,Topo>> | xref:046-1-corintios/046-1-corintios-014.adoc#v46-14-0[Próximo Capítulo &#62;]