include::./index.adoc[]

[[v46-6-0]]
=== 1 Coríntios, 6
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v46-6-1]]

^<<v46-6-1,1>>^ Atreve-se alguém de vós, que tenha uma causa contra outro, ir a juízo perante os injustos, e não perante os santos?

[[v46-6-2]]

^<<v46-6-2,2>>^ Ou não sabeis que os santos julgarão o mundo? E, se o mundo há de ser julgado por vós, sois vós inaptos para julgar assuntos muito triviais?

[[v46-6-3]]

^<<v46-6-3,3>>^ Não sabeis que havemos de julgar anjos? Por que, então, não assuntos desta vida?

[[v46-6-4]]

^<<v46-6-4,4>>^ Se vós, então, tiverdes assuntos desta vida para julgar, colocais como juízes a homens que são menosprezados na congregação?

[[v46-6-5]]

^<<v46-6-5,5>>^ Falo para induzir-vos à vergonha. É verdade que não há nem um só homem sábio entre vós, que possa julgar entre seus irmãos,

[[v46-6-6]]

^<<v46-6-6,6>>^ mas irmão vai a juízo contra irmão, e isso perante incrédulos?

[[v46-6-7]]

^<<v46-6-7,7>>^ Realmente, então, significa ao todo uma derrota para vós que tendes litígios entre vós. Por que não deixais antes que se vos faça injustiça? Por que não vos deixais antes defraudar?

[[v46-6-8]]

^<<v46-6-8,8>>^ Ao contrário, vós fazeis injustiça e defraudais, e isso a vossos irmãos.

[[v46-6-9]]

^<<v46-6-9,9>>^ O quê! Não sabeis que os injustos não herdarão o reino de Deus? Não sejais desencaminhados. Nem fornicadores, nem idólatras, nem adúlteros,^&#42;1^ nem homens mantidos para propósitos desnaturais, nem homens que se deitam com homens,^&#42;2^

[NOTE]
====
. “Adúlteros.” Lat.: a·dúl·te·ri.
. Ou “nem sodomitas”. Lit.: “nem os que se deitam com varões”. Gr.: oú·te ar·se·no·koí·tai; lat.: né·que ma·scu·ló·rum con·cu·bi·tó·res.
====

[[v46-6-10]]

^<<v46-6-10,10>>^ nem ladrões, nem gananciosos, nem beberrões, nem injuriadores, nem extorsores herdarão o reino de Deus.

[[v46-6-11]]

^<<v46-6-11,11>>^ E, no entanto, isso é o que fostes alguns de vós. Mas vós fostes lavados, mas vós fostes santificados,^&#42;1^ mas vós fostes declarados justos no nome de nosso^&#42;2^ Senhor Jesus Cristo e com o espírito de nosso Deus.

[NOTE]
====
. Ou “vós fostes tidos por sagrados (tratados como santos)”. Gr.: he·gi·á·sthe·te; lat.: sanc·ti·fi·cá·ti é·stis; J17,22(hebr.): qud·dash·tém.
. “Nosso”, BVgSypArm; P46אAD omitem isso.
====

[[v46-6-12]]

^<<v46-6-12,12>>^ Todas as coisas me são lícitas; mas nem todas as coisas são vantajosas. Todas as coisas me são lícitas; mas eu não me deixarei pôr sob autoridade por coisa alguma.

[[v46-6-13]]

^<<v46-6-13,13>>^ Os alimentos são para o ventre, e o ventre, para os alimentos; mas Deus reduzirá a nada tanto um como os outros. Ora, o corpo não é para fornicação, mas para o Senhor; e o Senhor é para o corpo.

[[v46-6-14]]

^<<v46-6-14,14>>^ Mas Deus tanto levantou o Senhor como levantará a nós da [morte] por intermédio de seu poder.

[[v46-6-15]]

^<<v46-6-15,15>>^ Não sabeis que os vossos corpos são membros de Cristo? Tirarei eu, então, os membros do Cristo e os farei membros duma meretriz?^&#42;1^ Que isso nunca aconteça!

[NOTE]
====
. Ou “fornicadora; prostituta”. Gr.: pór·nes.
====

[[v46-6-16]]

^<<v46-6-16,16>>^ O quê! Não sabeis que aquele que se junta a uma meretriz é um só corpo? Pois: “Os dois”, diz ele,^&#42;1^ “serão uma só carne”.

[NOTE]
====
. Ou “ela”, isto é, a escritura.
====

[[v46-6-17]]

^<<v46-6-17,17>>^ Mas aquele que é ajuntado ao Senhor é um só espírito.

[[v46-6-18]]

^<<v46-6-18,18>>^ Fugi da fornicação. Todo outro pecado que o homem possa cometer é fora de seu^&#42;1^ corpo, mas quem pratica a fornicação está pecando contra o seu próprio corpo.

[NOTE]
====
. Lit.: “do”.
====

[[v46-6-19]]

^<<v46-6-19,19>>^ O quê! Não sabeis que o corpo de vós [em conjunto] é [o] templo^&#42;1^ do espírito santo no vosso íntimo, o qual tendes da parte de Deus? Também, não pertenceis a vós mesmos,

[NOTE]
====
. Ou “habitação (morada) divina”. Gr.: na·ós; lat.: tém·plum; J17,22(hebr.): heh·khál, “palácio; templo”.
====

[[v46-6-20]]

^<<v46-6-20,20>>^ pois fostes comprados por um preço. Acima de tudo, glorificai a Deus no corpo de vós [em conjunto].

'''

xref:046-1-corintios/046-1-corintios-005.adoc#v46-5-0[&#60; Capítulo Anterior] | <<v46-6-0,Topo>> | xref:046-1-corintios/046-1-corintios-007.adoc#v46-7-0[Próximo Capítulo &#62;]