include::./index.adoc[]

[[v46-15-0]]
=== 1 Coríntios, 15
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v46-15-1]]

^<<v46-15-1,1>>^ Agora, irmãos, faço-vos saber as boas novas que vos declarei, as quais também recebestes [e] nas quais também estais de pé,

[[v46-15-2]]

^<<v46-15-2,2>>^ por intermédio das quais também estais sendo salvos, pela palavra com que vos declarei as boas novas, se é que vos apegais a elas, a menos que, de fato, vos tornastes crentes sem qualquer objetivo.

[[v46-15-3]]

^<<v46-15-3,3>>^ Pois eu vos transmiti, entre as primeiras coisas, aquilo que também recebi, que Cristo morreu pelos nossos pecados, segundo as Escrituras;

[[v46-15-4]]

^<<v46-15-4,4>>^ e que ele foi enterrado, sim, que foi ressuscitado no terceiro dia, segundo as Escrituras;

[[v46-15-5]]

^<<v46-15-5,5>>^ e que ele apareceu a Cefas, depois aos doze.

[[v46-15-6]]

^<<v46-15-6,6>>^ Depois disso apareceu a mais de quinhentos irmãos de uma só vez, a maioria dos quais permanece até o presente, mas alguns já adormeceram [na morte].

[[v46-15-7]]

^<<v46-15-7,7>>^ Depois disso apareceu a Tiago, [e] então a todos os apóstolos;

[[v46-15-8]]

^<<v46-15-8,8>>^ mas, por último de todos, apareceu também a mim, como a alguém nascido prematuramente.^&#42;1^

[NOTE]
====
. Ou “a um abortado”. Lat.: a·bor·tí·vo.
====

[[v46-15-9]]

^<<v46-15-9,9>>^ Pois eu sou o mínimo dos apóstolos, e não sou apto para ser chamado apóstolo, porque persegui a congregação de Deus.

[[v46-15-10]]

^<<v46-15-10,10>>^ Mas, pela benignidade imerecida de Deus, sou o que sou. E a sua benignidade imerecida para comigo não se mostrou vã, mas labutei mais do que todos eles, contudo, não eu, mas a benignidade imerecida de Deus que está comigo.

[[v46-15-11]]

^<<v46-15-11,11>>^ No entanto, quer seja eu quer eles, assim estamos pregando e assim acreditastes.

[[v46-15-12]]

^<<v46-15-12,12>>^ Ora, se se prega Cristo, que ele tem sido levantado dentre os mortos, como é que alguns entre vós dizem que não há ressurreição^&#42;1^ dos mortos?

[NOTE]
====
. “Ressurreição.” Gr.: a·ná·sta·sis, “levantar-se; erguer-se” (de a·ná, “para cima”, e stá·sis, “estar de pé”); lat.: re·sur·réc·ti·o.
====

[[v46-15-13]]

^<<v46-15-13,13>>^ Se, deveras, não há ressurreição dos mortos, tampouco Cristo foi levantado.

[[v46-15-14]]

^<<v46-15-14,14>>^ Mas, se Cristo não foi levantado, a nossa pregação certamente é vã e a nossa fé é vã.

[[v46-15-15]]

^<<v46-15-15,15>>^ Além disso, somos também achados como falsas testemunhas de Deus, porque temos dado testemunho contra Deus, de que ele levantou o Cristo, a quem ele, porém, não levantou, se realmente é que os mortos não hão de ser levantados.

[[v46-15-16]]

^<<v46-15-16,16>>^ Pois, se os mortos não hão de ser levantados, tampouco Cristo foi levantado.

[[v46-15-17]]

^<<v46-15-17,17>>^ Outrossim, se Cristo não foi levantado, a vossa fé é inútil; ainda estais em vossos pecados.

[[v46-15-18]]

^<<v46-15-18,18>>^ De fato, também pereceram os que adormeceram [na morte] em união com Cristo.

[[v46-15-19]]

^<<v46-15-19,19>>^ Se somente nesta vida temos esperado em Cristo, somos os mais lastimáveis de todos os homens.

[[v46-15-20]]

^<<v46-15-20,20>>^ No entanto, agora Cristo tem sido levantado dentre os mortos, as primícias dos que adormeceram [na morte].

[[v46-15-21]]

^<<v46-15-21,21>>^ Pois, visto que a morte é por intermédio dum homem, também a ressurreição dos mortos é por intermédio dum homem.

[[v46-15-22]]

^<<v46-15-22,22>>^ Porque, assim como em Adão todos morrem, assim também em Cristo todos serão vivificados.

[[v46-15-23]]

^<<v46-15-23,23>>^ Mas, cada um na sua própria categoria: Cristo, as primícias, depois os que pertencem a Cristo durante a sua presença.^&#42;1^

[NOTE]
====
. Veja Ap. 5B.
====

[[v46-15-24]]

^<<v46-15-24,24>>^ A seguir, o fim,^&#42;1^ quando ele entregar o reino ao seu Deus e Pai, tendo reduzido a nada todo governo, e toda autoridade e poder.

[NOTE]
====
. Ou “remate; fim (completo)”. Gr.: té·los.
====

[[v46-15-25]]

^<<v46-15-25,25>>^ Pois ele tem de reinar até que [Deus]^&#42;1^ lhe tenha posto todos os inimigos debaixo dos seus pés.

[NOTE]
====
. Lit.: “ele”.
====

[[v46-15-26]]

^<<v46-15-26,26>>^ Como último inimigo, a morte há de ser reduzida a nada.^&#42;1^

[NOTE]
====
. Ou “há de ser destruída”. Lit.: “é tornada sem efeito”. Gr.: ka·tar·geí·tai.
====

[[v46-15-27]]

^<<v46-15-27,27>>^ Pois [Deus] “lhe sujeitou todas as coisas debaixo dos pés”. Mas, quando diz que ‘todas as coisas foram sujeitas’, é evidente que se excetua aquele que lhe sujeitou todas as coisas.

[[v46-15-28]]

^<<v46-15-28,28>>^ Mas, quando todas as coisas lhe tiverem sido sujeitas, então o próprio Filho também se sujeitará^&#42;1^ Àquele que lhe sujeitou todas as coisas, para que Deus seja todas as coisas para com todos.^&#42;2^

[NOTE]
====
. Ou “ficará sujeito”.
. Ou “todas as coisas entre todas as pessoas”.
====

[[v46-15-29]]

^<<v46-15-29,29>>^ Senão, que farão os que estão sendo batizados com o objetivo de^&#42;1^ [serem] mortos? Se os mortos absolutamente não hão de ser levantados, por que estão sendo também batizados com o objetivo de [serem] tais?

[NOTE]
====
. Ou “batizados por motivo de”.
====

[[v46-15-30]]

^<<v46-15-30,30>>^ Por que estamos também cada hora em perigo?

[[v46-15-31]]

^<<v46-15-31,31>>^ Eu enfrento a morte diariamente. Isto afirmo pela exultação sobre vós, irmãos, a qual tenho em Cristo Jesus, nosso Senhor.

[[v46-15-32]]

^<<v46-15-32,32>>^ Se eu, igual aos homens,^&#42;1^ tenho lutado com feras em Éfeso, que me aproveita isso? Se os mortos não hão de ser levantados, “comamos e bebamos, pois amanhã morreremos”.

[NOTE]
====
. Ou: “Se eu, com motivos humanos.” Lit.: “Se eu, segundo o homem.” Gr.: ei ka·tá án·thro·pon.
====

[[v46-15-33]]

^<<v46-15-33,33>>^ Não sejais desencaminhados. Más associações estragam^&#42;1^ hábitos úteis.

[NOTE]
====
. Lit.: “corrompem”.
====

[[v46-15-34]]

^<<v46-15-34,34>>^ Despertai para a sobriedade dum modo justo, e não pratiqueis o pecado, pois alguns estão sem conhecimento de Deus. Estou falando para induzir-vos à vergonha.

[[v46-15-35]]

^<<v46-15-35,35>>^ Não obstante, alguém dirá: “Como hão de ser levantados os mortos? Sim, com que sorte de corpo hão de vir?”

[[v46-15-36]]

^<<v46-15-36,36>>^ Ó desarrazoado! Aquilo que semeias não é vivificado a menos que primeiro morra;

[[v46-15-37]]

^<<v46-15-37,37>>^ e, quanto ao que semeias, semeias, não o corpo que se há de desenvolver, mas o mero grão, seja de trigo, seja de qualquer dos outros;

[[v46-15-38]]

^<<v46-15-38,38>>^ mas Deus lhe dá um corpo assim como lhe agrada, e a cada uma das sementes o seu próprio corpo.

[[v46-15-39]]

^<<v46-15-39,39>>^ Nem toda a carne é a mesma carne, mas uma é a da humanidade, e outra é a carne do gado, e outra [é] a carne de aves, e outra de peixes.

[[v46-15-40]]

^<<v46-15-40,40>>^ E há corpos celestes^&#42;1^ e corpos terrestres;^&#42;2^ mas a glória dos corpos celestes é de uma sorte e a dos corpos terrestres é de sorte diferente.

[NOTE]
====
. Lat.: cae·lé·sti·a.
. Lat.: ter·ré·stri·a.
====

[[v46-15-41]]

^<<v46-15-41,41>>^ A glória do sol é de uma sorte e a glória da lua é de outra, e a glória das estrelas é de outra; de fato, estrela difere de estrela em glória.

[[v46-15-42]]

^<<v46-15-42,42>>^ Assim também é a ressurreição dos mortos. Semeia-se em corrupção, é levantado em incorrupção.

[[v46-15-43]]

^<<v46-15-43,43>>^ Semeia-se em desonra, é levantado em glória. Semeia-se em fraqueza, é levantado em poder.

[[v46-15-44]]

^<<v46-15-44,44>>^ Semeia-se corpo físico,^&#42;1^ é levantado corpo espiritual. Se há corpo físico, há também um espiritual.

[NOTE]
====
. Ou “[corpo-]alma; de alma”. Gr.: psy·khi·kón; lat.: a·ni·má·le.
====

[[v46-15-45]]

^<<v46-15-45,45>>^ Até mesmo está escrito assim: “O primeiro homem, Adão, tornou-se alma vivente.”^&#42;1^ O último Adão tornou-se espírito vivificante.

[NOTE]
====
. Ou “criatura respirante”. Veja Gên 2:7 n.: “vivente”; Ap. 4A.
====

[[v46-15-46]]

^<<v46-15-46,46>>^ Não obstante, o primeiro é, não o que é espiritual, mas o que é físico, depois aquilo que é espiritual.

[[v46-15-47]]

^<<v46-15-47,47>>^ O primeiro homem é da terra e feito de pó; o segundo homem é do céu.

[[v46-15-48]]

^<<v46-15-48,48>>^ Assim como [é] aquele feito de pó, assim [são] também esses feitos de pó; e assim como [é] o celestial, assim [são] também esses que são celestiais.

[[v46-15-49]]

^<<v46-15-49,49>>^ E assim como temos levado a imagem daquele feito de pó, levaremos^&#42;1^ também a imagem do celestial.

[NOTE]
====
. “Levaremos”, B; P46אADVg: “levemos”.
====

[[v46-15-50]]

^<<v46-15-50,50>>^ No entanto, digo isso, irmãos, que carne e sangue não podem herdar o reino de Deus, nem pode a corrupção herdar a incorrupção.

[[v46-15-51]]

^<<v46-15-51,51>>^ Eis que eu vos digo um segredo sagrado: Nem todos adormeceremos [na morte], mas todos seremos mudados,

[[v46-15-52]]

^<<v46-15-52,52>>^ num momento, num piscar de olhos, durante^&#42;1^ a última trombeta. Pois a trombeta soará, e os mortos serão levantados incorruptíveis, e nós seremos mudados.

[NOTE]
====
. Ou “na”.
====

[[v46-15-53]]

^<<v46-15-53,53>>^ Pois isto que é corruptível tem de revestir-se de incorrupção e isto que é mortal tem de revestir-se de imortalidade.^&#42;1^

[NOTE]
====
. “Imortalidade.” Gr.: a·tha·na·sí·an; lat.: in·mor·ta·li·tá·tem; J17,18(hebr.): ’al-má·weth, “não-morte”.
====

[[v46-15-54]]

^<<v46-15-54,54>>^ Mas, quando [isto que é corruptível se revestir de incorrupção e]^&#42;1^ isto que é mortal se revestir de imortalidade, então se cumprirá a palavra que está escrita: “A morte foi tragada para sempre.”^&#42;2^

[NOTE]
====
. ABDSyp incluem estas palavras entre colchetes; א°Vg omitem isso.
. “Para sempre.” Lit.: “na vitória”, como na LXX em 2Sa 2:26; La 5:20; Am 1:11; Am 8:7.
====

[[v46-15-55]]

^<<v46-15-55,55>>^ “Morte, onde está a tua vitória? Morte, onde está o teu aguilhão?”^&#42;1^

[NOTE]
====
. Paulo cita parte de Os 13:14 da Septuaginta. LXXBagster reza: “Onde está a tua penalidade [gr.: dí·ke], ó morte? Ó Hades, onde está o teu aguilhão?”
====

[[v46-15-56]]

^<<v46-15-56,56>>^ O aguilhão que produz a morte é o pecado, mas o poder para o pecado é a Lei.^&#42;1^

[NOTE]
====
. Lit.: “O aguilhão da morte é o pecado, e o poder do pecado é a Lei.”
====

[[v46-15-57]]

^<<v46-15-57,57>>^ Graças a Deus, porém, pois ele nos dá a vitória por intermédio de nosso Senhor Jesus Cristo!

[[v46-15-58]]

^<<v46-15-58,58>>^ Conseqüentemente, meus amados irmãos, tornai-vos constantes, inabaláveis, tendo sempre bastante para fazer na obra do Senhor, sabendo que o vosso labor não é em vão^&#42;1^ em conexão com [o] Senhor.

[NOTE]
====
. Lit.: “vazio”.
====

'''

xref:046-1-corintios/046-1-corintios-014.adoc#v46-14-0[&#60; Capítulo Anterior] | <<v46-15-0,Topo>> | xref:046-1-corintios/046-1-corintios-016.adoc#v46-16-0[Próximo Capítulo &#62;]