include::./index.adoc[]

[[v46-14-0]]
=== 1 Coríntios, 14
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v46-14-1]]

^<<v46-14-1,1>>^ Empenhai-vos pelo amor, contudo, persisti em buscar zelosamente os dons espirituais, preferivelmente, porém, que profetizeis.

[[v46-14-2]]

^<<v46-14-2,2>>^ Pois quem fala numa língua, fala, não a homens, mas a Deus, porque ninguém está escutando, mas ele fala segredos sagrados pelo espírito.

[[v46-14-3]]

^<<v46-14-3,3>>^ No entanto, quem profetiza, edifica, e encoraja, e conforta os homens pelo seu falar.

[[v46-14-4]]

^<<v46-14-4,4>>^ Quem fala numa língua, edifica a si mesmo, mas quem profetiza, edifica uma congregação.

[[v46-14-5]]

^<<v46-14-5,5>>^ Ora, eu gostaria que todos vós falásseis em línguas, mas prefiro que profetizeis. Deveras, quem profetiza é maior do que aquele que fala em línguas, a menos que, de fato, traduza, para que a congregação receba edificação.

[[v46-14-6]]

^<<v46-14-6,6>>^ Neste tempo, porém, irmãos, se eu fosse ter convosco falando em línguas, que bem vos faria eu, se não vos falasse quer com revelação,^&#42;1^ quer com conhecimento, quer com profecia, quer com ensino?

[NOTE]
====
. Lit.: “exposição; exibição”. Gr.: a·po·ka·lý·psei.
====

[[v46-14-7]]

^<<v46-14-7,7>>^ Do modo como é, as coisas inanimadas^&#42;1^ produzem som, quer seja flauta quer harpa; a menos que se faça um intervalo [melódico] nos tons, como se saberá o que se toca na flauta ou na harpa?

[NOTE]
====
. Ou “coisas sem alma”. Gr.: á·psy·kha.
====

[[v46-14-8]]

^<<v46-14-8,8>>^ Pois, verdadeiramente, se a trombeta der um toque incerto, quem se aprontará para a batalha?

[[v46-14-9]]

^<<v46-14-9,9>>^ Do mesmo modo, também, a menos que vós, por intermédio da língua, pronuncieis palavras facilmente entendidas, como se saberá o que se fala? Estareis, de fato, falando ao ar.

[[v46-14-10]]

^<<v46-14-10,10>>^ Pode haver muitas espécies de vozes faladas no mundo, contudo, nenhuma [espécie] é sem significado.

[[v46-14-11]]

^<<v46-14-11,11>>^ Se eu, pois, não entender a força da voz falada, serei estrangeiro para aquele que fala, e aquele que fala será estrangeiro para mim.

[[v46-14-12]]

^<<v46-14-12,12>>^ Assim também vós mesmos, visto que estais zelosamente desejosos [dos dons] do espírito,^&#42;1^ buscai abundar neles para a edificação da congregação.

[NOTE]
====
. Lit.: “zelosos de espíritos”.
====

[[v46-14-13]]

^<<v46-14-13,13>>^ Portanto, quem falar numa língua, ore para que a possa traduzir.

[[v46-14-14]]

^<<v46-14-14,14>>^ Pois, se eu orar numa língua, é o meu [dom do] espírito que está orando, mas a minha mente é infrutífera.

[[v46-14-15]]

^<<v46-14-15,15>>^ Que há de ser feito, então? Orarei com o [dom do] espírito, mas orarei também com a [minha] mente. Cantarei louvor com o [dom do] espírito, mas cantarei também louvor com a [minha] mente.

[[v46-14-16]]

^<<v46-14-16,16>>^ De outro modo, se ofereceres louvor com um [dom do] espírito, como é que o homem ocupando o assento da pessoa comum dirá “amém” aos teus agradecimentos, visto que não sabe o que estás dizendo?

[[v46-14-17]]

^<<v46-14-17,17>>^ Deveras, tu dás graças dum modo excelente, mas o outro não está sendo edificado.

[[v46-14-18]]

^<<v46-14-18,18>>^ Agradeço a Deus que falo mais línguas do que todos vós.

[[v46-14-19]]

^<<v46-14-19,19>>^ Não obstante, numa congregação quero antes falar cinco palavras com a minha mente, para instruir também oralmente os outros, do que dez mil palavras numa língua.

[[v46-14-20]]

^<<v46-14-20,20>>^ Irmãos, não vos torneis criancinhas na capacidade de entendimento, mas sede pequeninos quanto à maldade; contudo, ficai plenamente desenvolvidos na capacidade de entendimento.

[[v46-14-21]]

^<<v46-14-21,21>>^ Está escrito na Lei: “‘Pelas línguas de estrangeiros e pelos lábios de estranhos^&#42;1^ falarei a este povo, e, ainda assim, nem mesmo então me darão ouvidos’, diz Jeová.”^&#42;2^

[NOTE]
====
. Lit.: “de diferentes”.
. Veja Ap. 1D.
====

[[v46-14-22]]

^<<v46-14-22,22>>^ Conseqüentemente, as línguas são para sinal, não para os crentes, mas para os incrédulos, ao passo que o profetizar não é para os incrédulos, mas para os crentes.

[[v46-14-23]]

^<<v46-14-23,23>>^ Portanto, se a congregação inteira se reunir num só lugar e todos falarem em línguas, mas entrarem pessoas comuns ou incrédulos, não dirão que estais loucos?

[[v46-14-24]]

^<<v46-14-24,24>>^ Mas, se todos estiverdes profetizando e entrar qualquer incrédulo ou pessoa comum, é repreendido por todos, é examinado de perto por todos;

[[v46-14-25]]

^<<v46-14-25,25>>^ os segredos do seu coração se tornarão manifestos, de modo que se prostrará sobre o [seu] rosto e adorará a Deus, declarando: “Deus está realmente entre vós.”

[[v46-14-26]]

^<<v46-14-26,26>>^ Que há de ser feito, então, irmãos? Ao vos reunirdes, um tem salmo,^&#42;1^ outro tem ensino, outro tem revelação, outro tem língua, outro tem interpretação. Que todas as coisas ocorram para edificação.

[NOTE]
====
. Ou “composição sagrada”.
====

[[v46-14-27]]

^<<v46-14-27,27>>^ E, se alguém falar numa língua, seja isso limitado a dois ou no máximo três, e por turnos; e traduza alguém.

[[v46-14-28]]

^<<v46-14-28,28>>^ Mas, se não houver tradutor, então fique calado na congregação e fale consigo mesmo e com Deus.

[[v46-14-29]]

^<<v46-14-29,29>>^ Outrossim, falem dois ou três profetas, e que os outros discirnam o significado.

[[v46-14-30]]

^<<v46-14-30,30>>^ Mas, se outro tiver revelação enquanto está sentado ali, fique calado o primeiro.

[[v46-14-31]]

^<<v46-14-31,31>>^ Pois todos vós podeis profetizar um por um, para que todos aprendam e todos sejam encorajados.

[[v46-14-32]]

^<<v46-14-32,32>>^ E [os dons do] espírito^&#42;1^ dos profetas hão de ser controlados pelos profetas.

[NOTE]
====
. Lit.: “E espíritos.”
====

[[v46-14-33]]

^<<v46-14-33,33>>^ Pois Deus não é [Deus] de desordem, mas de paz.
Como em todas as congregações dos santos,

[[v46-14-34]]

^<<v46-14-34,34>>^ fiquem caladas as mulheres nas congregações, pois não se lhes permite falar, mas estejam em sujeição, assim como diz até mesmo a Lei.

[[v46-14-35]]

^<<v46-14-35,35>>^ Se, então, quiserem aprender algo, interroguem a seus próprios maridos em casa, pois é ignominioso para uma mulher falar na congregação.

[[v46-14-36]]

^<<v46-14-36,36>>^ O quê? Foi de vós que procedeu a palavra de Deus, ou atingiu ela só a vós?

[[v46-14-37]]

^<<v46-14-37,37>>^ Se alguém pensa que é profeta ou é dotado do espírito,^&#42;1^ reconheça as coisas que vos estou escrevendo, porque^&#42;2^ são o mandamento do Senhor.

[NOTE]
====
. “Dotado do espírito.” Lit.: “(alguém) espiritual”.
. Ou “que”.
====

[[v46-14-38]]

^<<v46-14-38,38>>^ Mas, se alguém é ignorante, ele continua ignorante.

[[v46-14-39]]

^<<v46-14-39,39>>^ Conseqüentemente, meus irmãos, persisti zelosamente em buscar o profetizar, contudo, não proibais o falar em línguas.

[[v46-14-40]]

^<<v46-14-40,40>>^ Mas, que todas as coisas ocorram decentemente e por arranjo.^&#42;1^

[NOTE]
====
. Ou “segundo a ordem”. Gr.: ka·tá tá·xin. Veja Núm 1:52 n.: “acampamento”.
====

'''

xref:046-1-corintios/046-1-corintios-013.adoc#v46-13-0[&#60; Capítulo Anterior] | <<v46-14-0,Topo>> | xref:046-1-corintios/046-1-corintios-015.adoc#v46-15-0[Próximo Capítulo &#62;]