include::./index.adoc[]

[[v46-2-0]]
=== 1 Coríntios, 2
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v46-2-1]]

^<<v46-2-1,1>>^ E assim, quando fui ter convosco, irmãos, não fui com extravagância^&#42;1^ de linguagem ou de sabedoria, declarando-vos o segredo sagrado de Deus.

[NOTE]
====
. Ou “superioridade”.
====

[[v46-2-2]]

^<<v46-2-2,2>>^ Pois decidi não saber coisa alguma entre vós, exceto Jesus Cristo, e este pregado numa estaca.

[[v46-2-3]]

^<<v46-2-3,3>>^ E fui ter convosco em fraqueza, e em temor, e com muito tremor;

[[v46-2-4]]

^<<v46-2-4,4>>^ e a minha linguagem e aquilo que preguei não foram em palavras persuasivas de sabedoria, mas numa demonstração de espírito e de poder,

[[v46-2-5]]

^<<v46-2-5,5>>^ para que a vossa fé não fosse na sabedoria de homens, mas no poder de Deus.

[[v46-2-6]]

^<<v46-2-6,6>>^ Ora, falamos sabedoria entre os que são maduros,^&#42;1^ mas não a sabedoria deste sistema de coisas, nem a dos governantes deste sistema de coisas,^&#42;2^ os quais hão de ficar reduzidos a nada.

[NOTE]
====
. Ou “os plenamente desenvolvidos”. Lit.: “os perfeitos”.
. Veja 1:20 n.
====

[[v46-2-7]]

^<<v46-2-7,7>>^ Mas falamos a sabedoria de Deus em segredo sagrado, a sabedoria escondida, que Deus predeterminou antes dos sistemas de coisas,^&#42;1^ para a nossa glória.

[NOTE]
====
. Ou “ordens de coisas”. Gr.: ai·ó·non; lat.: saé·cu·la; J22(hebr.): ha·‛oh·la·mím, “das ordens de coisas”.
====

[[v46-2-8]]

^<<v46-2-8,8>>^ Esta [sabedoria], nenhum dos governantes deste sistema veio a conhecer, pois, se [a] tivessem conhecido, não teriam pregado o glorioso Senhor numa estaca.

[[v46-2-9]]

^<<v46-2-9,9>>^ Mas, como está escrito: “O olho não tem visto e o ouvido não tem ouvido, nem foram concebidas no coração do homem as coisas que Deus tem preparado para os que o amam.”

[[v46-2-10]]

^<<v46-2-10,10>>^ Porque é a nós que Deus as tem revelado por intermédio de seu espírito, pois o espírito pesquisa todas as coisas, até mesmo as coisas profundas de Deus.

[[v46-2-11]]

^<<v46-2-11,11>>^ Pois, quem dentre os homens sabe as coisas do homem, exceto o espírito de homem que está nele? Assim, também, ninguém veio a saber as coisas de Deus, exceto o espírito de Deus.

[[v46-2-12]]

^<<v46-2-12,12>>^ Ora, não recebemos o espírito do mundo, mas o espírito que é de Deus, para que soubéssemos as coisas que nos foram dadas bondosamente por Deus.

[[v46-2-13]]

^<<v46-2-13,13>>^ Destas coisas também falamos, não com palavras ensinadas pela sabedoria humana, mas com as ensinadas pelo espírito, ao combinarmos [assuntos] espirituais com [palavras] espirituais.^&#42;1^

[NOTE]
====
. Ou “ao conjugarmos [assuntos] espirituais com [homens] espirituais”.
====

[[v46-2-14]]

^<<v46-2-14,14>>^ Mas o homem físico^&#42;1^ não aceita as coisas do espírito de Deus, porque para ele são tolice; e ele não pode chegar a conhecê-las, porque são examinadas espiritualmente.

[NOTE]
====
. Ou “[homem-]alma; de alma”. Gr.: psy·khi·kós; lat.: a·ni·má·lis.
====

[[v46-2-15]]

^<<v46-2-15,15>>^ No entanto, o homem espiritual^&#42;1^ examina deveras todas as coisas, mas ele mesmo não é examinado por homem algum.

[NOTE]
====
. Lit.: “o espiritual”. Gr.: ho . . . pneu·ma·ti·kós; Vgc(lat.): spi·ri·tu·á·lis.
====

[[v46-2-16]]

^<<v46-2-16,16>>^ Pois “quem veio a conhecer a mente de Jeová^&#42;1^ para o instruir?” Mas nós temos a mente de Cristo.^&#42;2^

[NOTE]
====
. Veja Ap. 1D.
. “Cristo”, P46אACVgSypJ17,18,22; BD°It: “Senhor”.
====

'''

xref:046-1-corintios/046-1-corintios-001.adoc#v46-1-0[&#60; Capítulo Anterior] | <<v46-2-0,Topo>> | xref:046-1-corintios/046-1-corintios-003.adoc#v46-3-0[Próximo Capítulo &#62;]