include::./index.adoc[]

[[v46-8-0]]
=== 1 Coríntios, 8
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v46-8-1]]

^<<v46-8-1,1>>^ Agora, acerca dos alimentos oferecidos a ídolos:^&#42;1^ sabemos que todos nós temos conhecimento. O conhecimento enfuna, mas o amor edifica.

[NOTE]
====
. Ou “das coisas sacrificadas a ídolos”.
====

[[v46-8-2]]

^<<v46-8-2,2>>^ Se alguém pensa que tem adquirido conhecimento de algo, ele ainda não [o] conhece como devia conhecer.

[[v46-8-3]]

^<<v46-8-3,3>>^ Mas, se alguém ama a Deus, este é conhecido por ele.

[[v46-8-4]]

^<<v46-8-4,4>>^ Ora, acerca de comer alimentos oferecidos a ídolos, sabemos que o ídolo nada é no mundo,^&#42;1^ e que não há Deus senão um só.

[NOTE]
====
. Ou “não é absolutamente nada”.
====

[[v46-8-5]]

^<<v46-8-5,5>>^ Pois, embora haja os que se chamem “deuses”, quer no céu, quer na terra, assim como há muitos “deuses” e muitos “senhores”,

[[v46-8-6]]

^<<v46-8-6,6>>^ para nós há realmente um só Deus,^&#42;1^ o Pai, de quem procedem todas as coisas, e nós para ele; e há um só Senhor, Jesus Cristo, por intermédio de quem são todas as coisas, e nós por intermédio dele.

[NOTE]
====
. “Um só Deus.” Gr.: heis The·ós; lat.: ú·nus Dé·us; J18,22(hebr.): ’Elo·hím ’e·hhádh.
====

[[v46-8-7]]

^<<v46-8-7,7>>^ Não obstante, nem em todos há tal conhecimento; mas alguns, acostumados até agora com o ídolo, comem o alimento como algo sacrificado a um ídolo, e a consciência deles, sendo fraca, fica poluída.

[[v46-8-8]]

^<<v46-8-8,8>>^ Mas, não é a comida que nos recomendará a Deus; se não comermos, não seremos faltosos, e, se comermos, não teremos méritos para nós mesmos.

[[v46-8-9]]

^<<v46-8-9,9>>^ Sede vigilantes, porém, para que esta autoridade vossa não se torne de algum modo uma pedra de tropeço para os que são fracos.

[[v46-8-10]]

^<<v46-8-10,10>>^ Pois, se alguém vir a ti, que tens conhecimento, recostado numa refeição num templo de ídolo,^&#42;1^ não se edificará a consciência daquele que é fraco ao ponto de comer alimentos oferecidos a ídolos?

[NOTE]
====
. Veja Jz 9:27.
====

[[v46-8-11]]

^<<v46-8-11,11>>^ Realmente, pelo teu conhecimento está sendo arruinado aquele que é fraco, [teu] irmão pelo qual Cristo morreu.

[[v46-8-12]]

^<<v46-8-12,12>>^ Mas, quando pecais assim contra os vossos irmãos e feris a sua consciência fraca, estais pecando contra Cristo.

[[v46-8-13]]

^<<v46-8-13,13>>^ Portanto, se o alimento fizer o meu irmão tropeçar, nunca mais comerei carne alguma, para que eu não faça meu irmão tropeçar.

'''

xref:046-1-corintios/046-1-corintios-007.adoc#v46-7-0[&#60; Capítulo Anterior] | <<v46-8-0,Topo>> | xref:046-1-corintios/046-1-corintios-009.adoc#v46-9-0[Próximo Capítulo &#62;]