include::./index.adoc[]

[[v9-20-0]]
=== 1 Samuel, 20
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v9-20-1]]

^<<v9-20-1,1>>^ E Davi fugiu de Naiote em Ramá. No entanto, veio e disse na frente de Jonatã: “Que fiz eu? Qual é meu erro e que pecado cometi perante teu pai, pois ele está procurando a minha alma?”

[[v9-20-2]]

^<<v9-20-2,2>>^ A isso lhe disse ele: “É inconcebível! Não morrerás. Eis que meu pai não fará nem coisa grande nem coisa pequena sem a revelar ao meu ouvido;^&#42;1^ e por que razão me esconderia meu pai este assunto? Tal não acontece.”

[NOTE]
====
. Lit.: “e não destapar meu ouvido”.
====

[[v9-20-3]]

^<<v9-20-3,3>>^ Davi, porém, jurou ainda em adição e disse: “Teu pai seguramente deve saber que tenho achado favor aos teus olhos e por isso dirá: ‘Não saiba disso Jonatã, para que não se sinta magoado.’ Mas, de fato, assim como vive Jeová e como vive a tua alma, há apenas um passo entre mim e a morte!”

[[v9-20-4]]

^<<v9-20-4,4>>^ E Jonatã prosseguiu, dizendo a Davi: “Farei para ti o que a tua alma disser.”^&#42;1^

[NOTE]
====
. “Disser”, MSyVg; TLXX: “desejar”.
====

[[v9-20-5]]

^<<v9-20-5,5>>^ A isso Davi disse a Jonatã: “Eis que amanhã é lua nova, e eu mesmo, sem falta, devia estar sentado com o rei para comer; e terás de mandar-me embora e eu terei de esconder-me no campo até à noitinha do terceiro dia.^&#42;1^

[NOTE]
====
. Lit. só “do terceiro”, M; LXX omite isso.
====

[[v9-20-6]]

^<<v9-20-6,6>>^ Se é que teu pai der falta de mim, então terás de dizer: ‘Davi pediu-me encarecidamente licença para correr a Belém, sua cidade, porque há ali um sacrifício anual para toda a família.’

[[v9-20-7]]

^<<v9-20-7,7>>^ Se ele disser assim: ‘Está bem!’ significa paz para o teu servo. Mas, se realmente ficar irado, sabe que resolveu aquilo que é mau.

[[v9-20-8]]

^<<v9-20-8,8>>^ E tens de usar de benevolência^&#42;1^ para com o teu servo, pois levaste o teu servo a um pacto de Jeová contigo. Mas, se houver erro em mim, entrega-me tu mesmo à morte, pois, por que me havias de levar a teu pai?”

[NOTE]
====
. Ou “amor leal”.
====

[[v9-20-9]]

^<<v9-20-9,9>>^ Então disse Jonatã: “Isso é inconcebível no que se refere a ti! Mas, se eu realmente souber que meu pai resolveu trazer sobre ti o mal, não te hei de informar?”

[[v9-20-10]]

^<<v9-20-10,10>>^ Então disse Davi a Jonatã: “Quem me informará sobre se aquilo que teu pai te responder é duro?”

[[v9-20-11]]

^<<v9-20-11,11>>^ Jonatã, por sua vez, disse a Davi: “Vem, e saiamos ao campo.” Assim, ambos saíram ao campo.

[[v9-20-12]]

^<<v9-20-12,12>>^ E Jonatã prosseguiu, dizendo a Davi: “Jeová, o Deus de Israel, [seja testemunha de]^&#42;1^ que sondarei meu pai por volta desta hora, amanhã ou no terceiro dia, e se ele estiver bem disposto para com Davi,^&#42;2^ não te enviarei [recado] e não o hei de revelar ao teu ouvido?^&#42;3^

[NOTE]
====
. “Seja testemunha de”, ou: “dá testemunho de”, Sy; LXX: “sabe”; M omite isso.
. Ou “se for bom para com Davi”.
. Lit.: “destapar teu ouvido”.
====

[[v9-20-13]]

^<<v9-20-13,13>>^ Assim faça Jeová a Jonatã e assim lhe acrescente mais, caso parecer bem a meu pai fazer-te mal, se eu deveras não o revelar ao teu ouvido e não te mandar embora, e tu não fores certamente em paz. E mostre Jeová estar contigo, assim como mostrou estar com meu pai.

[[v9-20-14]]

^<<v9-20-14,14>>^ E não usarás tu, se eu ainda estiver vivo, sim, não usarás tu da benevolência de Jeová para comigo, para que eu não morra?

[[v9-20-15]]

^<<v9-20-15,15>>^ E não^&#42;1^ deceparás a tua própria benevolência para com os da minha casa por tempo indefinido. Nem mesmo quando Jeová decepar os inimigos de Davi, cada um da superfície do solo,

[NOTE]
====
. “Para comigo. E se eu deveras morrer, (15) tu não”, LXXVg.
====

[[v9-20-16]]

^<<v9-20-16,16>>^ será decepado [o nome de] Jonatã da casa de Davi.^&#42;1^ E Jeová tem de requerer isso da mão dos inimigos de Davi.”

[NOTE]
====
. “Será decepado o nome de Jonatã da casa de Davi”, LXX; M: “E Jonatã passou a contratar (fazer um pacto) com a casa de Davi[, dizendo].”
====

[[v9-20-17]]

^<<v9-20-17,17>>^ E Jonatã, pois, jurou novamente a Davi^&#42;1^ por causa do seu amor por ele; porque o amava como amava a sua própria alma.

[NOTE]
====
. “Jurou novamente a Davi”, LXXVg; MSy: “fez Davi jurar novamente”.
====

[[v9-20-18]]

^<<v9-20-18,18>>^ E Jonatã prosseguiu, dizendo-lhe: “Amanhã é lua nova e certamente se dará falta de ti, porque o teu assento estará vago.

[[v9-20-19]]

^<<v9-20-19,19>>^ E certamente no terceiro dia se dará muita falta de ti; e terás de vir ao lugar onde te escondeste no dia de trabalho e terás de ficar perto desta pedra aqui.^&#42;1^

[NOTE]
====
. “Perto desse monte de terra”, mediante uma emenda do M, para concordar com LXX; Vg: “perto da pedra, cujo nome é Ezel”.
====

[[v9-20-20]]

^<<v9-20-20,20>>^ E no que toca a mim, atirarei três flechas^&#42;1^ para um lado dela, enviando-as a um alvo onde eu quiser.

[NOTE]
====
. Possivelmente: “no terceiro dia atirarei flechas”.
====

[[v9-20-21]]

^<<v9-20-21,21>>^ E eis que enviarei o ajudante, [dizendo]: ‘Vai, acha as flechas.’ Se eu disser especificamente ao ajudante: ‘Eis que as flechas estão para cá de ti, traze-as’,^&#42;1^ então vem, pois significa paz para ti e não há nada, por Jeová que vive.

[NOTE]
====
. Lit.: “traze-a”.
====

[[v9-20-22]]

^<<v9-20-22,22>>^ Mas, se eu disser ao mancebo o seguinte: ‘Eis que as flechas estão para lá de ti’, vai, porque Jeová te mandou embora.

[[v9-20-23]]

^<<v9-20-23,23>>^ E quanto à palavra que falamos, eu e tu, ora, esteja Jeová entre mim e ti por tempo indefinido.”

[[v9-20-24]]

^<<v9-20-24,24>>^ E Davi passou a esconder-se no campo. E veio a ser lua nova, e o rei foi sentar-se à refeição^&#42;1^ para comer.

[NOTE]
====
. “Refeição (pão)”, MSy; LXX: “mesa”.
====

[[v9-20-25]]

^<<v9-20-25,25>>^ E o rei estava sentado no seu assento, como das outras vezes, no assento junto à parede; e Jonatã estava defronte dele^&#42;1^ e Abner estava sentado ao lado de Saul, mas o lugar de Davi estava vago.

[NOTE]
====
. Em harmonia com LXX. Lit.: “mas Jonatã levantou-se”.
====

[[v9-20-26]]

^<<v9-20-26,26>>^ E Saul não disse absolutamente nada naquele dia, pois disse para si: “Aconteceu alguma coisa, de modo que não está limpo, por não ter sido purificado.”^&#42;1^

[NOTE]
====
. “Não ter sido purificado”, LXX; M: “ele não está limpo”.
====

[[v9-20-27]]

^<<v9-20-27,27>>^ E sucedeu, no dia depois da lua nova, no segundo dia, que o lugar de Davi continuou vago. Então Saul disse a Jonatã, seu filho: “Por que não veio à refeição o filho de Jessé, nem ontem nem hoje?”

[[v9-20-28]]

^<<v9-20-28,28>>^ Portanto, Jonatã respondeu a Saul: “Davi pediu-me encarecidamente licença [para ir] a Belém.

[[v9-20-29]]

^<<v9-20-29,29>>^ E prosseguiu, dizendo: ‘Por favor, manda-me embora, porque temos um sacrifício de família na cidade e foi o meu próprio irmão quem me deu ordem. Agora, pois, se eu tiver achado favor aos teus olhos, deixa-me escapulir, por favor, para que eu vá ver meus irmãos.’ É por isso que ele não veio à mesa do rei.”

[[v9-20-30]]

^<<v9-20-30,30>>^ Então se acendeu a ira de Saul contra Jonatã e ele lhe disse: “Filho duma moça rebelde, não sei muito bem que escolhes^&#42;1^ o filho de Jessé para a tua própria vergonha e para a vergonha das partes pudendas de tua mãe?

[NOTE]
====
. “És parceiro de”, LXX.
====

[[v9-20-31]]

^<<v9-20-31,31>>^ Pois, todos os dias que o filho de Jessé estiver vivo sobre o solo, tu e teu reinado não ficarão firmemente estabelecidos. Agora, pois, manda trazê-lo a mim, porque está destinado à morte.”^&#42;1^

[NOTE]
====
. Lit.: “porque é filho da morte”.
====

[[v9-20-32]]

^<<v9-20-32,32>>^ No entanto, Jonatã respondeu a Saul, seu pai, e lhe disse: “Por que deve ser entregue à morte? Que fez ele?”

[[v9-20-33]]

^<<v9-20-33,33>>^ A isso Saul foi arremessar a lança contra ele para golpeá-lo; e Jonatã ficou sabendo que tinha sido resolvido por seu pai entregar Davi à morte.

[[v9-20-34]]

^<<v9-20-34,34>>^ Jonatã levantou-se imediatamente da mesa em ira acesa e não comeu pão no segundo dia depois da lua nova, porque tinha sido magoado com respeito a Davi, visto que seu próprio pai o havia humilhado.

[[v9-20-35]]

^<<v9-20-35,35>>^ E sucedeu, de manhã, que Jonatã foi sair ao campo do lugar designado de Davi, e estava com ele um jovem ajudante.

[[v9-20-36]]

^<<v9-20-36,36>>^ E ele passou a dizer ao seu ajudante: “Corre, por favor, acha as flechas que atiro.” O ajudante correu, e ele mesmo atirou a flecha para a fazer passar além dele.

[[v9-20-37]]

^<<v9-20-37,37>>^ Quando o ajudante chegou até o lugar da flecha que Jonatã havia atirado, Jonatã começou a chamar atrás do ajudante e a dizer: “Não está a flecha mais além de ti?”

[[v9-20-38]]

^<<v9-20-38,38>>^ E Jonatã chamava atrás do ajudante: “Depressa! Age rapidamente! Não fiques parado!” E o ajudante de Jonatã foi apanhar as flechas e depois veio ao seu amo.^&#42;1^

[NOTE]
====
. “Seu amo.” Hebr.: ’adho·náv, pl. de ’a·dhóhn, para denotar excelência. Veja Gên 39:2 n.
====

[[v9-20-39]]

^<<v9-20-39,39>>^ Quanto ao ajudante, não sabia de nada; somente Jonatã e Davi sabiam do assunto.

[[v9-20-40]]

^<<v9-20-40,40>>^ Depois, Jonatã deu as suas armas ao ajudante que lhe pertencia e disse-lhe: “Vai, leva-as à cidade.”

[[v9-20-41]]

^<<v9-20-41,41>>^ O ajudante foi. Quanto a Davi, levantou-se dum lugar próximo, ao sul. Lançou-se então com o seu rosto por terra e curvou-se três vezes; e começaram a beijar-se um ao outro e a chorar um pelo outro, até que Davi o tinha feito muito mais.

[[v9-20-42]]

^<<v9-20-42,42>>^ E Jonatã foi dizer a Davi: “Vai em paz, visto que ambos juramos em nome de Jeová, dizendo: ‘Mostre o próprio Jeová estar entre mim e ti, e entre a minha descendência e a tua descendência, por tempo indefinido.’”^&#42;1^
Concordemente, Davi^&#42;2^ levantou-se e seguiu caminho, e o próprio Jonatã entrou na cidade.

[NOTE]
====
. MLXX terminam aqui o capítulo 20.
. “Davi”, LXXVgc; M: “ele”.
====

'''

xref:009-1-samuel/009-1-samuel-019.adoc#v9-19-0[&#60; Capítulo Anterior] | <<v9-20-0,Topo>> | xref:009-1-samuel/009-1-samuel-021.adoc#v9-21-0[Próximo Capítulo &#62;]