include::./index.adoc[]

[[v9-22-0]]
=== 1 Samuel, 22
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v9-22-1]]

^<<v9-22-1,1>>^ Portanto, Davi passou a ir-se dali e a escapar para a caverna de Adulão; e seus irmãos e toda a casa de seu pai chegaram a ouvir isso e foram descer a ele.

[[v9-22-2]]

^<<v9-22-2,2>>^ E todos os homens em aperto, e todos os homens que tinham credor, e todos os homens de alma amargurada começaram a reunir-se a ele, e ele veio a ser chefe^&#42;1^ sobre eles; e veio a haver com ele cerca de quatrocentos homens.

[NOTE]
====
. Lit.: “como príncipe”. Hebr.: lesár. Veja Gên 40:2 n.
====

[[v9-22-3]]

^<<v9-22-3,3>>^ Mais tarde, Davi foi de lá para Mispé, em Moabe, e disse ao rei de Moabe: “Por favor, deixa meu pai e minha mãe morar convosco^&#42;1^ até eu saber o que Deus fará comigo.”

[NOTE]
====
. Lit.: “por favor, . . . sair [para ficar] convosco”.
====

[[v9-22-4]]

^<<v9-22-4,4>>^ Por conseguinte, fixou-os ali perante o rei de Moabe, e continuaram a morar com ele todos os dias em que acontecia Davi estar no lugar inacessível.^&#42;1^

[NOTE]
====
. Ou “no baluarte”. Sy: “Mispá”.
====

[[v9-22-5]]

^<<v9-22-5,5>>^ Passado tempo, Gade, o profeta, disse a Davi: “Não deves ficar morando no lugar inacessível. Vai-te, e tu mesmo tens de entrar na terra de Judá.” Portanto, Davi foi embora e entrou na floresta de Herete.

[[v9-22-6]]

^<<v9-22-6,6>>^ E Saul chegou a ouvir que Davi e os homens com ele tinham sido descobertos, enquanto Saul estava sentado em Gibeá, debaixo da tamargueira, no alto,^&#42;1^ tendo na mão a sua lança, e todos os seus servos estavam em pé em volta dele.

[NOTE]
====
. “No alto.” Ou “em Ramá”. Hebr.: ba·ra·máh; LXXB,L: “em Bama”.
====

[[v9-22-7]]

^<<v9-22-7,7>>^ Saul disse então aos seus servos que estavam em pé em volta dele: “Escutai, por favor, ó benjaminitas. Dará também o filho de Jessé a todos vós campos e vinhedos? Designará a todos vós chefes de mil e chefes de cem?

[[v9-22-8]]

^<<v9-22-8,8>>^ Pois, conspirastes contra mim, todos vós; e não há quem o revele ao meu ouvido quando meu próprio filho conclui^&#42;1^ [um pacto] com o filho de Jessé, e não há nenhum de vós que se condoa de mim^&#42;2^ e revele ao meu ouvido que o meu próprio filho levantou o meu próprio servo contra mim como quem está de emboscada,^&#42;3^ assim como é no dia de hoje.”

[NOTE]
====
. Lit.: “corta”. Veja Gên 15:18 n.
. “Que se condoa de mim”; ou “que tenha dó de mim”.
. “Quem está de emboscada”, MVg; LXX: “inimigo”.
====

[[v9-22-9]]

^<<v9-22-9,9>>^ Nisto Doegue, o edomita, que estava posto sobre^&#42;1^ os servos de Saul, respondeu e disse: “Eu vi o filho de Jessé vir a Nobe, a Aimeleque, filho de Aitube.

[NOTE]
====
. Ou “ao lado dos”.
====

[[v9-22-10]]

^<<v9-22-10,10>>^ E ele passou a indagar de Jeová^&#42;1^ por ele; e deu-lhe provisões e deu-lhe a espada de Golias, o filisteu.”

[NOTE]
====
. “Jeová”, MVg; LXXSy: “Deus”.
====

[[v9-22-11]]

^<<v9-22-11,11>>^ O rei mandou chamar imediatamente Aimeleque, filho de Aitube, o sacerdote, e toda a casa de seu pai, os sacerdotes que estavam em Nobe. De modo que todos eles vieram ao rei.

[[v9-22-12]]

^<<v9-22-12,12>>^ Saul disse então: “Escuta, por favor, ó filho de Aitube!” a que ele disse: “Eis-me aqui, meu senhor.”

[[v9-22-13]]

^<<v9-22-13,13>>^ E Saul prosseguiu, dizendo-lhe: “Por que conspirastes contra mim, tu e o filho de Jessé, dando-lhe pão e uma espada, e fazendo-se indagação^&#42;1^ a Deus por ele, para se levantar contra mim como quem está de emboscada, assim como é no dia de hoje?”

[NOTE]
====
. “Fazendo-se indagação.” No hebr., este verbo está no infinitivo absoluto, indefinido quanto ao tempo e impessoal.
====

[[v9-22-14]]

^<<v9-22-14,14>>^ Aimeleque respondeu então ao rei e disse: “E quem dentre todos os teus servos é igual a Davi, fiel, e genro do rei, e chefe da tua escolta, e honrado na tua casa?

[[v9-22-15]]

^<<v9-22-15,15>>^ É de hoje que principiei a indagar a Deus por ele? É inconcebível da minha parte! Não impute o rei nada contra o seu servo [nem] contra a casa inteira de meu pai, pois em tudo isso teu servo não sabia coisa alguma, nem pequena nem grande.”

[[v9-22-16]]

^<<v9-22-16,16>>^ O rei, porém, disse: “Positivamente morrerás, Aimeleque, tu com toda a casa de teu pai.”

[[v9-22-17]]

^<<v9-22-17,17>>^ Então o rei disse aos batedores que estavam de pé em volta dele: “Voltai-vos e entregai à morte os sacerdotes de Jeová, porque a sua mão também está com Davi, e porque sabiam que ele era fugitivo e não o revelaram ao meu ouvido!” E os servos do rei não quiseram estender a sua mão para atacar os sacerdotes de Jeová.

[[v9-22-18]]

^<<v9-22-18,18>>^ Por fim, o rei disse a Doegue: “Volta-te e ataca os sacerdotes!” Doegue, o edomita, voltou-se imediatamente, e ele mesmo atacou os sacerdotes, e naquele dia entregou à morte oitenta e cinco homens que usavam um éfode de linho.^&#42;1^

[NOTE]
====
. “De linho”, MSyVg; LXX omite isso.
====

[[v9-22-19]]

^<<v9-22-19,19>>^ Até mesmo a Nobe, a cidade dos sacerdotes, ele golpeou com o fio da espada, tanto homem como mulher, tanto criança como bebê, bem como touro, e jumento, e ovídeo, com o fio da espada.

[[v9-22-20]]

^<<v9-22-20,20>>^ No entanto, um filho de Aimeleque, filho de Aitube, cujo nome era Abiatar, escapou-se e pôs-se em fuga para seguir Davi.

[[v9-22-21]]

^<<v9-22-21,21>>^ Abiatar comunicou então a Davi: “Saul matou os sacerdotes de Jeová.”

[[v9-22-22]]

^<<v9-22-22,22>>^ Então, Davi disse a Abiatar: “Eu bem sabia, naquele dia, estando lá Doegue, o edomita, que ele ia sem falta contá-lo a Saul. Eu pessoalmente fiz mal^&#42;1^ a toda alma da casa de teu pai.

[NOTE]
====
. Lit.: “Voltei-me contra”, M; SyVg: “Sou culpado com respeito a”; LXX: “Sou responsável por.”
====

[[v9-22-23]]

^<<v9-22-23,23>>^ Fica morando comigo. Não tenhas medo, pois, quem procura a minha alma [também] procura a tua alma, porque tu és quem necessitas de proteção comigo.”

'''

xref:009-1-samuel/009-1-samuel-021.adoc#v9-21-0[&#60; Capítulo Anterior] | <<v9-22-0,Topo>> | xref:009-1-samuel/009-1-samuel-023.adoc#v9-23-0[Próximo Capítulo &#62;]