include::./index.adoc[]

[[v9-25-0]]
=== 1 Samuel, 25
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v9-25-1]]

^<<v9-25-1,1>>^ Passado tempo morreu Samuel; e todo o Israel passou a reunir-se e a lamentá-lo, e foram enterrá-lo em sua casa,^&#42;1^ em Ramá. Davi levantou-se então e desceu ao ermo de Parã.^&#42;2^

[NOTE]
====
. “Em sua casa”, MLXXVg; Sy: “em seu sepulcro”.
. “Parã”, MSyVg; LXX: “Maom”.
====

[[v9-25-2]]

^<<v9-25-2,2>>^ Ora, havia em Maom um homem e seu trabalho era em Carmelo.^&#42;1^ E era muito grande o homem, e tinha três mil ovelhas e mil caprídeos; e ele veio a estar [empenhado] na tosquia das suas ovelhas em Carmelo.

[NOTE]
====
. Uma cidade na região montanhosa de Judá, 12 km ao sul de Hébron; sem relação com o monte Carmelo. Veja Jos 15:20, 54, 55.
====

[[v9-25-3]]

^<<v9-25-3,3>>^ E o nome do homem era Nabal e o nome de sua esposa era Abigail. E a esposa tinha boa discrição e bela figura, mas o marido era duro e mau nas suas práticas; e ele era calebita.

[[v9-25-4]]

^<<v9-25-4,4>>^ E Davi chegou a ouvir no ermo que Nabal estava tosquiando as suas ovelhas.

[[v9-25-5]]

^<<v9-25-5,5>>^ Portanto, Davi enviou dez moços e Davi disse aos moços: “Subi a Carmelo, e tendes de ir a Nabal e perguntar-lhe em meu nome sobre o seu bem-estar.

[[v9-25-6]]

^<<v9-25-6,6>>^ E isto é o que tendes de dizer ao meu irmão:^&#42;1^ ‘Que te vá bem a ti e que vá igualmente bem aos da tua casa, e que vá bem a tudo o que tens.

[NOTE]
====
. Mediante uma ligeira emenda do M; hebr.: le·hhaí, “ao vivente”.
====

[[v9-25-7]]

^<<v9-25-7,7>>^ E agora, eu ouvi [dizer] que tens tosquiadores. Ora, acontece que os próprios pastores que te pertencem estiveram conosco. Não os molestamos, e absolutamente coisa alguma deles se mostrou faltando, todos os dias em que sucedia estarem em Carmelo.

[[v9-25-8]]

^<<v9-25-8,8>>^ Pergunta aos teus próprios moços e eles te informarão, para que os [meus]^&#42;1^ moços achem favor aos teus olhos, porque chegamos num bom dia. Por favor, dá simplesmente aos teus servos e a teu filho Davi o que a tua mão achar.’”

[NOTE]
====
. Lit. sem “meus”.
====

[[v9-25-9]]

^<<v9-25-9,9>>^ Conseqüentemente, os moços de Davi foram e falaram a Nabal segundo todas estas palavras em nome de Davi e depois ficaram esperando.

[[v9-25-10]]

^<<v9-25-10,10>>^ Nabal respondeu então aos servos de Davi e disse: “Quem é Davi e quem é o filho de Jessé? Hoje em dia se tornaram muitos os servos que se escapam, cada um de diante do seu amo.^&#42;1^

[NOTE]
====
. “Seu amo.” Hebr.: ’adho·náv. Veja 20:38 n.
====

[[v9-25-11]]

^<<v9-25-11,11>>^ E tenho eu de tomar meu pão, e minha água,^&#42;1^ e minha carne de abate que abati para os meus tosquiadores, e dar isso a homens de quem nem mesmo sei donde são?”

[NOTE]
====
. “Água”, MSyVg; LXX: “vinho”.
====

[[v9-25-12]]

^<<v9-25-12,12>>^ Em vista disso, os moços de Davi deram volta no seu caminho e retornaram, e chegaram e informaram-no de acordo com todas estas palavras.

[[v9-25-13]]

^<<v9-25-13,13>>^ Davi disse imediatamente aos seus homens: “Cingi-vos cada um da sua espada!” Cingiram-se, pois, cada um da sua espada e também Davi cingiu-se da sua própria espada; e começaram a subir atrás de Davi, cerca de quatrocentos homens, ao passo que duzentos ficaram sentados junto à bagagem.

[[v9-25-14]]

^<<v9-25-14,14>>^ Entrementes, um dos moços informou Abigail, esposa de Nabal, dizendo: “Eis que Davi enviou mensageiros desde o ermo para congratular o nosso amo,^&#42;1^ mas ele lançou invectivas sobre eles.

[NOTE]
====
. Lit.: “para bendizer o nosso amo”.
====

[[v9-25-15]]

^<<v9-25-15,15>>^ E os homens foram muito bons para conosco e não nos molestaram, e não demos falta de nem uma única coisa todos os dias em que andamos com eles enquanto sucedia estarmos no campo.

[[v9-25-16]]

^<<v9-25-16,16>>^ Mostraram-se uma muralha em volta de nós, tanto de noite como de dia, todos os dias em que sucedia estarmos com eles, apascentando o rebanho.

[[v9-25-17]]

^<<v9-25-17,17>>^ E agora sabe e vê o que vais fazer, porque se resolveu a calamidade contra o nosso amo e contra toda a sua casa, visto que ele é um homem demasiado imprestável^&#42;1^ para se falar com ele.”

[NOTE]
====
. Lit.: “filho de belial (inutilidade)”.
====

[[v9-25-18]]

^<<v9-25-18,18>>^ Abigail apressou-se imediatamente e tomou duzentos pães, e duas grandes talhas de vinho, e cinco ovelhas preparadas, e cinco seás^&#42;1^ de grãos torrados, e cem tortas de passas, e duzentas tortas de figos prensados, e os pôs sobre os jumentos.

[NOTE]
====
. Um seá equivalia a 7,33 l.
====

[[v9-25-19]]

^<<v9-25-19,19>>^ Então ela disse aos seus moços: “Passai adiante de mim. Eis que venho atrás de vós.” Mas ela não contou nada a seu esposo Nabal.

[[v9-25-20]]

^<<v9-25-20,20>>^ E sucedeu que, seguindo ela montada no jumento e descendo o monte às escondidas, ora, eis que desciam Davi e seus homens ao seu encontro. De modo que se encontrou com eles.

[[v9-25-21]]

^<<v9-25-21,21>>^ Quanto a Davi, havia dito: “Foi só para decepção que guardei no ermo tudo o que pertence a este homem, e nem uma única coisa de tudo o que lhe pertence se mostrou faltando, e ainda assim ele me paga de volta o mal em troca do bem.

[[v9-25-22]]

^<<v9-25-22,22>>^ Assim faça Deus aos inimigos de Davi^&#42;1^ e assim lhe acrescente mais, se eu deixar restar até o amanhecer sequer um de todos os seus que urinam contra o muro.”^&#42;2^

[NOTE]
====
. “Faça a Davi”, LXX. Veja 2Sa 12:14 n.
. “Que urinam contra o muro.” Esta é uma expressão idiomática hebr. referindo-se a varões.
====

[[v9-25-23]]

^<<v9-25-23,23>>^ Quando Abigail avistou Davi, apressou-se imediatamente e desceu do jumento, e lançou-se com o rosto [por terra] diante de Davi e curvou-se para a terra.

[[v9-25-24]]

^<<v9-25-24,24>>^ Caiu então aos seus pés e disse: “Recaia sobre mim mesma o erro, ó meu senhor; e, por favor, deixa a tua escrava falar aos teus ouvidos e escuta as palavras da tua escrava.

[[v9-25-25]]

^<<v9-25-25,25>>^ Por favor, não fixe meu senhor seu coração neste homem imprestável, Nabal, pois ele é tal qual seu nome. Nabal^&#42;1^ é o seu nome e a insensatez^&#42;2^ está com ele. Quanto a mim, tua escrava, não vi os moços do meu senhor, que enviaste.

[NOTE]
====
. Significando “insensato”. Hebr.: Na·vál.
. “E a insensatez.” Hebr.: u·neva·láh.
====

[[v9-25-26]]

^<<v9-25-26,26>>^ E agora, meu senhor, assim como vive Jeová e assim como vive a tua alma, Jeová te impediu de entrar em culpa de sangue^&#42;1^ e de fazer a tua própria mão vir para a tua salvação.^&#42;2^ E agora, tornem-se iguais a Nabal os teus inimigos e os que procuram o prejuízo do meu senhor.

[NOTE]
====
. Lit.: “com sangues”.
. “Vir para . . . salvação.” No hebr., este é um verbo no infinitivo absoluto, indefinido quanto ao tempo e impessoal.
====

[[v9-25-27]]

^<<v9-25-27,27>>^ E agora, quanto a este presente de bênção que a tua serva trouxe ao meu senhor, tem de ser dado aos moços que andam nas pisadas do meu senhor.

[[v9-25-28]]

^<<v9-25-28,28>>^ Por favor, perdoa a transgressão da tua escrava, porque Jeová fará sem falta uma casa duradoura^&#42;1^ para meu senhor, pois meu senhor está travando as guerras de Jeová; e quanto à maldade, não se achará em ti durante os teus dias.^&#42;2^

[NOTE]
====
. Ou “uma casa fiel (firmemente estabelecida)”.
. Lit.: “em ti desde os teus dias”, isto é, todos os dias que viveste, desde o teu nascimento.
====

[[v9-25-29]]

^<<v9-25-29,29>>^ Quando um homem se levantar para te perseguir e para procurar a tua alma, a alma do meu senhor certamente mostrará estar embrulhada na bolsa da vida junto a Jeová, teu Deus; mas, quanto à alma dos teus inimigos, ele a atirará como que de dentro da concavidade duma funda.

[[v9-25-30]]

^<<v9-25-30,30>>^ E sucederá, por Jeová fazer ao meu senhor o bem para contigo, segundo tudo o que ele falou, que certamente te comissionará como líder de Israel.

[[v9-25-31]]

^<<v9-25-31,31>>^ E não se torne isso para ti uma razão para vacilação^&#42;1^ ou uma pedra de tropeço para o coração do meu senhor, tanto pelo derramamento de sangue sem causa como por fazer vir [a própria mão do] meu senhor^&#42;2^ para a sua salvação. E Jeová há de fazer o bem ao meu senhor, e tu terás de lembrar-te da tua escrava.”

[NOTE]
====
. “Vacilação.” Denotando escrúpulos de consciência.
. “A . . . mão do meu senhor”, LXX; M: “meu senhor”.
====

[[v9-25-32]]

^<<v9-25-32,32>>^ Então, Davi disse a Abigail: “Bendito seja Jeová, o Deus de Israel, que te enviou neste dia ao meu encontro!

[[v9-25-33]]

^<<v9-25-33,33>>^ E bendita seja a tua sensatez, e bendita sejas tu que neste dia me contiveste de entrar em culpa de sangue e de fazer a minha própria mão vir para a minha salvação.

[[v9-25-34]]

^<<v9-25-34,34>>^ E, por outro lado, assim como vive Jeová, o Deus de Israel, que me impediu de causar-te dano, se não te tivesses apressado para vir ao meu encontro, certamente não teria sobrado a Nabal até à luz da manhã ninguém que urinasse contra o muro.”^&#42;1^

[NOTE]
====
. Veja v. 22 n.: “muro”.
====

[[v9-25-35]]

^<<v9-25-35,35>>^ Com isso Davi aceitou da mão dela o que lhe tinha trazido e disse-lhe: “Sobe em paz para a tua casa. Vê, escutei a tua voz para ter consideração para com a tua pessoa.”

[[v9-25-36]]

^<<v9-25-36,36>>^ Mais tarde, Abigail entrou até Nabal e eis que ele realizava na sua casa um banquete como o banquete do rei; e o coração de Nabal se sentia bem dentro dele e ele estava bêbedo a mais não poder; e ela não lhe disse coisa alguma, nem pequena nem grande, até à luz da manhã.

[[v9-25-37]]

^<<v9-25-37,37>>^ E sucedeu, de manhã, quando o vinho havia deixado Nabal, que a sua esposa foi contar-lhe estas coisas. E o coração dele ficou morto dentro dele e ele próprio ficou como pedra.

[[v9-25-38]]

^<<v9-25-38,38>>^ Depois se passaram cerca de dez dias e então Jeová feriu a Nabal, de modo que morreu.

[[v9-25-39]]

^<<v9-25-39,39>>^ E Davi chegou a ouvir que Nabal havia morrido e por isso ele disse: “Bendito seja Jeová, que pleiteou a causa do meu vitupério [para me livrar] da mão de Nabal e que refreou seu servo da maldade, e Jeová fez a maldade de Nabal voltar sobre a sua própria cabeça!” E Davi mandou propor a Abigail tomá-la para si como esposa.

[[v9-25-40]]

^<<v9-25-40,40>>^ Os servos de Davi chegaram, pois, a Abigail, em Carmelo, e falaram-lhe, dizendo: “O próprio Davi nos enviou para tomar-te para ele por esposa.”

[[v9-25-41]]

^<<v9-25-41,41>>^ Ela se levantou imediatamente e curvou-se com o seu rosto por terra, e disse: “Eis a tua escrava como serva para lavar os pés dos servos do meu senhor.”

[[v9-25-42]]

^<<v9-25-42,42>>^ Abigail apressou-se então e levantou-se, e foi montada no jumento, com cinco criadas suas andando atrás dela;^&#42;1^ e ela foi acompanhar^&#42;2^ os mensageiros de Davi e tornou-se então esposa dele.

[NOTE]
====
. Lit.: “junto ao pé dela”.
. Ou “seguir”.
====

[[v9-25-43]]

^<<v9-25-43,43>>^ Davi havia também tomado a Ainoã, de Jezreel; e as mulheres vieram ambas a ser suas esposas.

[[v9-25-44]]

^<<v9-25-44,44>>^ Quanto a Saul, havia dado Mical, sua filha, esposa de Davi, a Palti, filho de Laís, que era de Galim.

'''

xref:009-1-samuel/009-1-samuel-024.adoc#v9-24-0[&#60; Capítulo Anterior] | <<v9-25-0,Topo>> | xref:009-1-samuel/009-1-samuel-026.adoc#v9-26-0[Próximo Capítulo &#62;]