include::./index.adoc[]

[[v22-1-0]]
=== Cântico de Salomão, 1
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v22-1-1]]

^<<v22-1-1,1>>^ O cântico superlativo,^&#42;1^ que é de Salomão:

[NOTE]
====
. Ou: “O cântico mais belo (excelente).” Lit.: “O cântico dos cânticos.”
====

[[v22-1-2]]

^<<v22-1-2,2>>^ “Beije-me ele com os beijos da sua boca, porque as tuas expressões de afeto^&#42;1^ são melhores do que o vinho.

[NOTE]
====
. Lit.: “teus afetos”. Hebr.: do·dheí·kha.
====

[[v22-1-3]]

^<<v22-1-3,3>>^ Teus óleos são bons em fragrância. Teu nome é como um óleo que se despeja. Por isso é que te amaram as próprias donzelas.

[[v22-1-4]]

^<<v22-1-4,4>>^ Puxa-me contigo;^&#42;1^ corramos. O rei me introduziu nos seus quartos interiores! Jubilemos e nos alegremos em ti. Mencionemos as tuas expressões de afeto mais do que o vinho. Amaram-te merecidamente.

[NOTE]
====
. Ou “atrás [de ti]”. Veja Jz 13:11 n.; Ru 1:16 n.
====

[[v22-1-5]]

^<<v22-1-5,5>>^ “Sou uma moça preta, mas linda, ó filhas de Jerusalém, como as tendas de Quedar, [contudo,] como os panos de tenda de Salomão.

[[v22-1-6]]

^<<v22-1-6,6>>^ Não olheis para mim, porque sou trigueira, pois o sol me avistou. Os filhos de minha própria mãe zangaram-se comigo; designaram-me guardiã dos vinhedos, [embora] eu não guardasse o meu vinhedo, aquele que era meu.

[[v22-1-7]]

^<<v22-1-7,7>>^ “Conta-me, ó tu a quem a minha alma tem amado, onde pastoreias, onde fazes o rebanho deitar-se ao meio-dia. Por que é que eu me devia tornar igual a uma mulher que se cobre de luto, entre as greis dos teus associados?”

[[v22-1-8]]

^<<v22-1-8,8>>^ “Se tu mesma não sabes, ó mais bela entre as mulheres, sai tu mesma nas pegadas do rebanho e apascenta tuas cabritinhas junto aos tabernáculos dos pastores.”

[[v22-1-9]]

^<<v22-1-9,9>>^ “Comparei-te a uma égua minha nos carros de Faraó, ó companheira minha.

[[v22-1-10]]

^<<v22-1-10,10>>^ Lindas são as tuas faces entre as tranças de cabelo, teu pescoço num colar de contas.

[[v22-1-11]]

^<<v22-1-11,11>>^ Nós te faremos argolinhas de ouro, junto com botõezinhos de prata.”

[[v22-1-12]]

^<<v22-1-12,12>>^ “Enquanto o rei está à sua mesa redonda, meu próprio nardo está dando a sua fragrância.

[[v22-1-13]]

^<<v22-1-13,13>>^ Como bolsa de mirra é para mim o meu querido; passará a noite entre os meus peitos.

[[v22-1-14]]

^<<v22-1-14,14>>^ Como cacho de hena é para mim o meu querido, entre os vinhedos de En-Gedi.”

[[v22-1-15]]

^<<v22-1-15,15>>^ “Eis que és bela, ó companheira minha! Eis que és bela! Teus olhos são [os das] pombas.”

[[v22-1-16]]

^<<v22-1-16,16>>^ “Eis que és belo,^&#42;1^ meu querido, também agradável. Também, o nosso divã é de folhagem.

[NOTE]
====
. “És belo”, hebr. masc., referindo-se ao seu amado pastor.
====

[[v22-1-17]]

^<<v22-1-17,17>>^ As vigas de nossa grandiosa casa^&#42;1^ são cedros, nossos caibros são juníperos.

[NOTE]
====
. Lit.: “nossas casas”.
====

'''

xref:021-eclesiastes/021-eclesiastes-012.adoc#v21-12-0[&#60; Capítulo Anterior] | <<v22-1-0,Topo>> | xref:022-cantico-de-salomao/022-cantico-de-salomao-002.adoc#v22-2-0[Próximo Capítulo &#62;]