include::./index.adoc[]

[[v12-8-0]]
=== 2 Reis, 8
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v12-8-1]]

^<<v12-8-1,1>>^ E o próprio Eliseu havia falado à mulher cujo filho fizera reviver, dizendo: “Levanta-te e vai, tu com os da tua casa, e reside como forasteira onde quer que puderes residir; pois Jeová convocou uma fome, e além disso, ela tem de vir^&#42;1^ sobre o país por sete anos.”

[NOTE]
====
. Ou “ela veio”.
====

[[v12-8-2]]

^<<v12-8-2,2>>^ Portanto, a mulher se levantou e fez segundo a palavra do homem do [verdadeiro] Deus e foi, ela com os da sua casa, e passou a residir como forasteira na terra dos filisteus, por sete anos.

[[v12-8-3]]

^<<v12-8-3,3>>^ E aconteceu, ao fim dos sete anos, que a mulher passou a retornar da terra dos filisteus e a sair para clamar ao rei pela sua casa e pelo seu campo.

[[v12-8-4]]

^<<v12-8-4,4>>^ Ora, o rei estava falando com Geazi, o ajudante do homem do [verdadeiro] Deus, dizendo: “Relata-me, por favor, todas as grandes coisas que Eliseu fez.”

[[v12-8-5]]

^<<v12-8-5,5>>^ E sucedeu que, enquanto relatava ao rei como este fizera reviver o morto, ora, eis a mulher cujo filho fizera reviver clamando ao rei pela sua casa e pelo seu campo. Geazi disse imediatamente: “Meu senhor, o rei, esta é a mulher e este é seu filho que Eliseu fez reviver.”

[[v12-8-6]]

^<<v12-8-6,6>>^ Então o rei perguntou à mulher e ela lhe relatou a história. O rei deu-lhe então um oficial da corte, dizendo: “Restitui tudo o que lhe pertence e todos os produtos do campo, desde o dia em que deixou o país até agora.”

[[v12-8-7]]

^<<v12-8-7,7>>^ E Eliseu passou a ir a Damasco; e Ben-Hadade, rei da Síria, estava doente. Por conseguinte, comunicou-se-lhe, dizendo: “O homem do [verdadeiro] Deus chegou até aqui.”

[[v12-8-8]]

^<<v12-8-8,8>>^ O rei disse então a Hazael: “Toma um presente na tua mão e vai encontrar-te com o homem do [verdadeiro] Deus, e tens de consultar a Jeová por intermédio dele, dizendo: ‘Reviverei desta doença?’”

[[v12-8-9]]

^<<v12-8-9,9>>^ Portanto, Hazael foi ao encontro dele e tomou um presente na sua mão, sim, toda sorte de coisa boa de Damasco, a carga de quarenta camelos, e veio e ficou de pé diante dele, e disse: “Teu filho, Ben-Hadade, rei da Síria, enviou-me a ti, dizendo: ‘Reviverei desta doença?’”

[[v12-8-10]]

^<<v12-8-10,10>>^ Então Eliseu lhe disse: “Vai, dize-lhe: ‘Positivamente^&#42;1^ reviverás’; e Jeová me mostrou que positivamente morrerá.”

[NOTE]
====
. “Dize-lhe: ‘Positivamente’”, Mmar-gemLXXSyVg e 18 mss. hebr.; M: “dize: ‘Positivamente não’”.
====

[[v12-8-11]]

^<<v12-8-11,11>>^ E ele manteve o olhar fixo e o manteve fixo ao ponto de embaraço. O homem do [verdadeiro] Deus entregou-se então ao choro.

[[v12-8-12]]

^<<v12-8-12,12>>^ Em vista disso, Hazael disse: “Por que está chorando meu senhor?” A isto ele disse: “Porque bem sei que dano causarás aos filhos de Israel. Suas praças fortes entregarás ao fogo, e seus homens seletos matarás à espada, e suas crianças despedaçarás, e suas mulheres grávidas estriparás.”

[[v12-8-13]]

^<<v12-8-13,13>>^ Então disse Hazael: “Que é o teu servo, [um mero] cão, que possa fazer esta grande coisa?” Mas Eliseu disse: “Jeová me mostrou que eras rei sobre a Síria.”

[[v12-8-14]]

^<<v12-8-14,14>>^ Depois ele foi embora de Eliseu e chegou ao seu próprio senhor, o qual lhe disse então: “Que te disse Eliseu?” A isto ele disse: “Ele me disse: ‘Positivamente reviverás.’”

[[v12-8-15]]

^<<v12-8-15,15>>^ E sucedeu, no dia seguinte, que ele passou a tomar uma colcha^&#42;1^ e a mergulhá-la^&#42;2^ na água e a estendê-la sobre a face dele, de modo que morreu. E Hazael tornou-se rei em seu lugar.

[NOTE]
====
. Ou “malha”.
. “E a mergulhá-la.” Hebr.: wai·yit·ból; gr.: é·ba·psen. Veja 5:14 n.
====

[[v12-8-16]]

^<<v12-8-16,16>>^ E no quinto ano de Jeorão,^&#42;1^ filho de Acabe, rei de Israel, enquanto Jeosafá era rei de Judá, tornou-se rei Jeorão, filho de Jeosafá, rei de Judá.

[NOTE]
====
. Lit.: “de Jorão”. Hebr.: leYoh·rám. Mas veja 1:17; 3:1.
====

[[v12-8-17]]

^<<v12-8-17,17>>^ Ele veio a ter trinta e dois anos de idade quando se tornou rei e reinou por oito anos em Jerusalém.

[[v12-8-18]]

^<<v12-8-18,18>>^ E ele andava no caminho dos reis de Israel, assim como os da casa de Acabe tinham feito; pois a filha de Acabe se tornou sua esposa, e ele fazia o que era mau aos olhos de Jeová.

[[v12-8-19]]

^<<v12-8-19,19>>^ E Jeová não quis arruinar Judá, por causa de Davi, seu servo, assim como lhe prometera dar sempre^&#42;1^ uma lâmpada a ele [e] aos seus filhos.^&#42;2^

[NOTE]
====
. Lit.: “todos os dias”.
. “Dar-lhe uma lâmpada e aos seus filhos”, Tmss.LXXVg e cerca de 60 mss. hebr. Veja 2Cr 21:7.
====

[[v12-8-20]]

^<<v12-8-20,20>>^ Nos seus dias se revoltou Edom debaixo da mão de Judá e então fez um rei reinar sobre si.

[[v12-8-21]]

^<<v12-8-21,21>>^ Por conseguinte, Jeorão passou para Zair, também todos os carros com ele. E aconteceu que ele mesmo se levantou de noite e foi golpear os edomitas que o cercavam, bem como os chefes dos carros; e o povo pôs-se em fuga para as suas tendas.

[[v12-8-22]]

^<<v12-8-22,22>>^ Mas Edom continuou na sua revolta de debaixo da mão de Judá até o dia de hoje. Foi então, naquele tempo, que Libna^&#42;1^ começou a revoltar-se.

[NOTE]
====
. “Libna”, uma cidade sacerdotal. Veja Jos 21:13.
====

[[v12-8-23]]

^<<v12-8-23,23>>^ E o resto dos assuntos de Jeorão e tudo o que ele fez, não estão escritos no livro dos assuntos dos dias dos reis de Judá?

[[v12-8-24]]

^<<v12-8-24,24>>^ Por fim, Jeorão deitou-se com os seus antepassados e foi enterrado com os seus antepassados na Cidade de Davi. E Acazias,^&#42;1^ seu filho, começou a reinar em seu lugar.

[NOTE]
====
. “Acazias.” Hebr.: ’Ahhaz·yá·hu. Veja 1Rs 22:40 n.
====

[[v12-8-25]]

^<<v12-8-25,25>>^ No décimo segundo ano de Jeorão, filho de Acabe, rei de Israel, tornou-se rei Acazias, filho de Jeorão, rei de Judá.

[[v12-8-26]]

^<<v12-8-26,26>>^ Acazias tinha vinte e dois anos de idade quando começou a reinar e reinou um ano em Jerusalém. E o nome de sua mãe era Atalia, neta^&#42;1^ de Onri, rei de Israel.

[NOTE]
====
. Lit.: “filha”.
====

[[v12-8-27]]

^<<v12-8-27,27>>^ E ele andava no caminho da casa de Acabe e fazia o que era mau aos olhos de Jeová, igual à casa de Acabe, pois era parente da casa de Acabe por casamento.

[[v12-8-28]]

^<<v12-8-28,28>>^ Conseqüentemente, ele foi com Jeorão, filho de Acabe, à guerra contra Hazael, rei da Síria, em Ramote-Gileade, mas os sírios golpearam a Jeorão.

[[v12-8-29]]

^<<v12-8-29,29>>^ Portanto, Jeorão, o rei, retornou para se curar em Jezreel das feridas que os sírios chegaram a infligir-lhe em Ramá,^&#42;1^ quando lutou contra Hazael, rei da Síria. Quanto a Acazias, filho de Jeorão, rei de Judá, desceu para visitar Jeorão, filho de Acabe, em Jezreel, pois estava doente.

[NOTE]
====
. Forma abreviada de “Ramote-Gileade”.
====

'''

xref:012-2-reis/012-2-reis-007.adoc#v12-7-0[&#60; Capítulo Anterior] | <<v12-8-0,Topo>> | xref:012-2-reis/012-2-reis-009.adoc#v12-9-0[Próximo Capítulo &#62;]