include::./index.adoc[]

[[v12-14-0]]
=== 2 Reis, 14
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v12-14-1]]

^<<v12-14-1,1>>^ No segundo ano de Jeoás, filho de Jeoacaz,^&#42;1^ rei de Israel, tornou-se rei Amazias,^&#42;2^ filho de Jeoás, rei de Judá.

[NOTE]
====
. “Jeoacaz.” Hebr.: Yoh·’a·hház.
. Significando “Jeová É Poderoso”. Hebr.: ’Amats·yá·hu.
====

[[v12-14-2]]

^<<v12-14-2,2>>^ Ele veio a ter vinte e cinco anos de idade quando começou a reinar e reinou por vinte e nove anos em Jerusalém. E o nome de sua mãe era Jeoadim, de Jerusalém.

[[v12-14-3]]

^<<v12-14-3,3>>^ E ele fazia o que era reto aos olhos de Jeová, apenas não como Davi, seu antepassado. Fazia segundo tudo o que Jeoás, seu pai, tinha feito.

[[v12-14-4]]

^<<v12-14-4,4>>^ Apenas os altos não desapareceram. O povo ainda oferecia sacrifícios e fazia fumaça sacrificial nos altos.

[[v12-14-5]]

^<<v12-14-5,5>>^ E sucedeu que, assim que o reino se tinha tornado firme na sua mão, começou a golpear os seus servos que haviam golpeado o rei, seu pai.

[[v12-14-6]]

^<<v12-14-6,6>>^ E não entregou à morte os filhos dos golpeadores, segundo o que está escrito no livro da lei de Moisés, que Jeová ordenou, dizendo: “Os pais não devem ser mortos por causa dos filhos e os próprios filhos não devem ser mortos por causa dos pais; mas cada um deve ser morto pelo seu próprio pecado.”

[[v12-14-7]]

^<<v12-14-7,7>>^ Ele mesmo golpeou os edomitas no Vale do Sal, dez mil homens, e chegou a tomar Sela em guerra, e ela veio a ser chamada pelo nome de Jocteel até o dia de hoje.

[[v12-14-8]]

^<<v12-14-8,8>>^ Foi então que Amazias enviou mensageiros a Jeoás, filho de Jeoacaz, filho de Jeú, rei de Israel, dizendo: “Vem deveras. Olhemo-nos um ao outro na face.”

[[v12-14-9]]

^<<v12-14-9,9>>^ Então Jeoás, rei de Israel, mandou dizer a Amazias, rei de Judá: “A própria planta espinhosa que estava no Líbano mandou dizer ao cedro que estava no Líbano: ‘Dá deveras a tua filha ao meu filho por esposa.’ Todavia, um animal selvático do campo, que estava no Líbano, passou por ali e pisou a planta espinhosa.

[[v12-14-10]]

^<<v12-14-10,10>>^ Indubitavelmente, golpeaste a Edom, e teu coração te elevou. Goza a tua honra e mora na tua própria casa. Então, por que devias empenhar-te numa luta em condições desfavoráveis e ter de cair, tu e Judá contigo?”

[[v12-14-11]]

^<<v12-14-11,11>>^ E Amazias não escutou.
De modo que Jeoás, rei de Israel, subiu e passaram a olhar-se um ao outro na face, ele e Amazias, rei de Judá, em Bete-Semes que pertence a Judá.

[[v12-14-12]]

^<<v12-14-12,12>>^ E Judá veio a ser derrotado diante de Israel, de modo que se puseram em fuga, cada um para a sua tenda.

[[v12-14-13]]

^<<v12-14-13,13>>^ E foi a Amazias, rei de Judá, filho de Jeoás, filho de Acazias, que Jeoás, rei de Israel, capturou em Bete-Semes, chegando eles depois a Jerusalém, e ele fez uma brecha na muralha de Jerusalém junto ao Portão de Efraim até o Portão da Esquina, quatrocentos côvados.^&#42;1^

[NOTE]
====
. Cerca de 178 m.
====

[[v12-14-14]]

^<<v12-14-14,14>>^ E tomou todo o ouro, e a prata, e todos os objetos que se achavam na casa de Jeová e nos tesouros da casa do rei, bem como os reféns,^&#42;1^ e então retornou a Samaria.

[NOTE]
====
. Lit.: “e os filhos dos penhores”.
====

[[v12-14-15]]

^<<v12-14-15,15>>^ Quanto ao resto dos assuntos de Jeoás, o que ele fez e sua potência, e como ele lutou contra Amazias, rei de Judá, não estão escritos no livro dos assuntos dos dias dos reis de Israel?

[[v12-14-16]]

^<<v12-14-16,16>>^ Por fim, Jeoás deitou-se com os seus antepassados e foi enterrado em Samaria com os reis de Israel, e Jeroboão,^&#42;1^ seu filho, começou a reinar em seu lugar.

[NOTE]
====
. Isto é, Jeroboão II.
====

[[v12-14-17]]

^<<v12-14-17,17>>^ E Amazias, filho de Jeoás, rei de Judá, seguiu vivendo depois da morte de Jeoás, filho de Jeoacaz, rei de Israel, por quinze anos.

[[v12-14-18]]

^<<v12-14-18,18>>^ Quanto ao resto dos assuntos de Amazias, não estão escritos no livro dos assuntos dos dias dos reis de Judá?

[[v12-14-19]]

^<<v12-14-19,19>>^ Por fim se coligaram contra ele numa conspiração em Jerusalém e ele se pôs em fuga para Laquis; porém, mandaram persegui-lo até Laquis e ali o entregaram à morte.

[[v12-14-20]]

^<<v12-14-20,20>>^ Carregaram-no, pois, sobre cavalos e ele foi enterrado em Jerusalém com os seus antepassados, na Cidade de Davi.

[[v12-14-21]]

^<<v12-14-21,21>>^ Todo o povo de Judá tomou então a Azarias, que naquele tempo tinha dezesseis anos de idade, e o fizeram rei em lugar de seu pai Amazias.

[[v12-14-22]]

^<<v12-14-22,22>>^ Foi ele quem construiu Elate e então a restituiu a Judá depois que o rei se deitara com os seus antepassados.

[[v12-14-23]]

^<<v12-14-23,23>>^ No décimo quinto ano de Amazias, filho de Jeoás, rei de Judá, Jeroboão, filho de Jeoás, rei de Israel, tornou-se rei em Samaria por quarenta e um anos.

[[v12-14-24]]

^<<v12-14-24,24>>^ E ele fazia o que era mau aos olhos de Jeová. Não se afastou de todos os pecados de Jeroboão, filho de Nebate, com que fez Israel pecar.

[[v12-14-25]]

^<<v12-14-25,25>>^ Foi ele quem restaurou o termo de Israel desde a entrada de Hamate até o mar do Arabá, segundo a palavra de Jeová, o Deus de Israel, que falou por intermédio do seu servo Jonas, filho de Amitai, o profeta que era de Gate-Héfer.

[[v12-14-26]]

^<<v12-14-26,26>>^ Pois Jeová tinha visto a tribulação muito amarga de Israel. Não havia nem incapacitado nem rejeitado,^&#42;1^ nem havia ajudador para Israel.

[NOTE]
====
. Lit.: “nem restrito nem largado (abandonado)”. Veja De 32:36 n.: “rejeitado”.
====

[[v12-14-27]]

^<<v12-14-27,27>>^ E Jeová prometera não extinguir o nome de Israel de debaixo dos céus. Por conseguinte, ele os salvou pela mão de Jeroboão, filho de Jeoás.

[[v12-14-28]]

^<<v12-14-28,28>>^ Quanto ao resto dos assuntos de Jeroboão e tudo o que ele fez, e sua potência, como lutou e como restaurou Damasco e Hamate a Judá, em Israel, não estão escritos no livro dos assuntos dos dias dos reis de Israel?

[[v12-14-29]]

^<<v12-14-29,29>>^ Por fim, Jeroboão deitou-se com os seus antepassados, com os reis de Israel, e Zacarias, seu filho, começou a reinar em seu lugar.

'''

xref:012-2-reis/012-2-reis-013.adoc#v12-13-0[&#60; Capítulo Anterior] | <<v12-14-0,Topo>> | xref:012-2-reis/012-2-reis-015.adoc#v12-15-0[Próximo Capítulo &#62;]