include::./index.adoc[]

[[v12-3-0]]
=== 2 Reis, 3
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v12-3-1]]

^<<v12-3-1,1>>^ Quanto a Jeorão, filho de Acabe, tornou-se rei sobre Israel em Samaria no décimo oitavo ano de Jeosafá, rei de Judá, e continuou a reinar por doze anos.

[[v12-3-2]]

^<<v12-3-2,2>>^ E ele fazia o que era mau aos olhos de Jeová, apenas não como seu pai nem como sua mãe, mas removeu a coluna sagrada de Baal que seu pai tinha feito.

[[v12-3-3]]

^<<v12-3-3,3>>^ Somente que se apegou aos pecados de Jeroboão, filho de Nebate, com que fizera Israel pecar. Não se afastou deles.

[[v12-3-4]]

^<<v12-3-4,4>>^ No que se refere a Mesa, rei de Moabe, tornou-se criador de ovelhas, e ele pagou ao rei de Israel cem mil cordeiros e cem mil carneiros não tosquiados.^&#42;1^

[NOTE]
====
. Ou “a lã de cem mil carneiros”.
====

[[v12-3-5]]

^<<v12-3-5,5>>^ E sucedeu que, assim que Acabe morreu, o rei de Moabe começou a revoltar-se contra o rei de Israel.

[[v12-3-6]]

^<<v12-3-6,6>>^ Por conseguinte, o Rei Jeorão saiu naquele dia de Samaria e passou em revista todo o Israel.

[[v12-3-7]]

^<<v12-3-7,7>>^ Foi mais além e mandou então dizer a Jeosafá, rei de Judá: “O próprio rei de Moabe se revoltou contra mim. Irás comigo a Moabe em guerra?” A isto ele disse: “Irei. Eu sou como tu; meu povo é como o teu povo; meus cavalos são como os teus cavalos.”

[[v12-3-8]]

^<<v12-3-8,8>>^ E prosseguiu, dizendo: “Por que caminho específico subiremos?” Ele disse, pois: “Pelo caminho do ermo de Edom.”

[[v12-3-9]]

^<<v12-3-9,9>>^ E o rei de Israel, e o rei de Judá, e o rei de Edom passaram a ir, e foram seguindo seu caminho em contorno por sete dias, e não se mostrou haver água para o acampamento e para os animais domésticos que seguiam as suas pisadas.

[[v12-3-10]]

^<<v12-3-10,10>>^ Por fim disse o rei de Israel: “Quão lamentável, que Jeová tenha convocado estes três reis para os entregar na mão de Moabe!”

[[v12-3-11]]

^<<v12-3-11,11>>^ Então disse Jeosafá: “Não há aqui um profeta de Jeová? Consultemos, pois, a Jeová por intermédio dele.” Assim, um dos servos do rei de Israel respondeu e disse: “Há aqui Eliseu, filho de Safate, que despejava água sobre as mãos de Elias.”

[[v12-3-12]]

^<<v12-3-12,12>>^ Jeosafá disse então: “Com ele há a palavra de Jeová.” Por conseguinte, o rei de Israel, e Jeosafá, e o rei de Edom desceram até ele.

[[v12-3-13]]

^<<v12-3-13,13>>^ E Eliseu passou a dizer ao rei de Israel: “Que tenho eu que ver contigo?^&#42;1^ Vai aos profetas de teu pai e aos profetas de tua mãe.” Mas o rei de Israel lhe disse: “Não, porque Jeová convocou estes três reis para os entregar na mão de Moabe.”

[NOTE]
====
. Lit.: “Que [há] para mim e para ti?” Esta é uma expressão idiomática hebr.; é uma pergunta de repulsa, indicando objeção. Veja Ap. 7B.
====

[[v12-3-14]]

^<<v12-3-14,14>>^ A isto disse Eliseu: “Assim como vive Jeová dos exércitos diante de quem deveras estou de pé,^&#42;1^ se não fosse que tenho consideração pela face de Jeosafá, rei de Judá, eu nem olharia para ti nem te veria.

[NOTE]
====
. Ou “a quem deveras assisto”.
====

[[v12-3-15]]

^<<v12-3-15,15>>^ E agora trazei-me um tocador de instrumento de cordas.” E sucedeu que, assim que o tocador do instrumento de cordas tocou, veio a estar sobre ele a mão de Jeová.

[[v12-3-16]]

^<<v12-3-16,16>>^ E ele prosseguiu, dizendo: “Assim disse Jeová: ‘Faça-se^&#42;1^ este vale de torrente cheio de valas;^&#42;2^

[NOTE]
====
. “Faça-se.” No hebr., este verbo está no infinitivo absoluto, indefinido quanto ao tempo e impessoal.
. Lit.: “valas, valas”.
====

[[v12-3-17]]

^<<v12-3-17,17>>^ pois assim disse Jeová: “Vós não vereis vento e não vereis aguaceiro; contudo, este vale de torrente se encherá de água e certamente bebereis [dela], vós e vosso gado, e vossos animais domésticos.”’

[[v12-3-18]]

^<<v12-3-18,18>>^ E esta será realmente uma coisa trivial aos olhos de Jeová, e ele certamente há de entregar Moabe na vossa mão.

[[v12-3-19]]

^<<v12-3-19,19>>^ E tereis de golpear toda cidade fortificada e toda cidade de escol, e deveis cortar toda árvore boa, e deveis tapar todos os mananciais de água, e deveis estragar com pedras todo lote bom de terreno.”

[[v12-3-20]]

^<<v12-3-20,20>>^ E aconteceu de manhã que, na hora da ascensão da oferta de cereais, eis que vinha água da direção de Edom e a terra se encheu de água.

[[v12-3-21]]

^<<v12-3-21,21>>^ Quanto a todos os moabitas, ouviram que os reis tinham subido para lutar contra eles. Por conseguinte, convocaram [homens] dentre tantos quantos cingiam um cinto, e dali para cima, e começaram a ficar de pé na fronteira.

[[v12-3-22]]

^<<v12-3-22,22>>^ Quando se levantaram de manhã cedo, o próprio sol raiou sobre a água, de modo que os moabitas, do lado oposto, viram a água vermelha como sangue.

[[v12-3-23]]

^<<v12-3-23,23>>^ E começaram a dizer: “Isto é sangue! Sem dúvida, os reis foram passados pela espada e foram golpear-se um ao outro. Agora, pois, ao despojo, ó Moabe!”

[[v12-3-24]]

^<<v12-3-24,24>>^ Quando entraram no acampamento de Israel, os israelitas se levantaram imediatamente e começaram a golpear os moabitas, de modo que se puseram em fuga diante deles. Entraram, pois, em Moabe,^&#42;1^ golpeando os moabitas na ida.^&#42;2^

[NOTE]
====
. Lit.: “nele”.
. “Chegaram, pois, a Moabe, golpeando . . . na ida”, mediante uma emenda do M, em harmonia com LXX.
====

[[v12-3-25]]

^<<v12-3-25,25>>^ E foram derrubar as cidades, e quanto a todo lote bom de terreno, lançavam [nele] cada um a sua pedra e realmente o enchiam; e tapavam todo manancial de água e cortavam toda árvore boa, até que só deixaram restar nele as pedras de Quir-Haresete; e os que atiravam com fundas começaram a andar em volta dela e a golpeá-la.

[[v12-3-26]]

^<<v12-3-26,26>>^ Quando o rei de Moabe viu que a batalha se mostrou forte demais para ele, tomou consigo imediatamente setecentos homens que puxavam da espada para romperem até o rei de Edom, mas não puderam.

[[v12-3-27]]

^<<v12-3-27,27>>^ Por fim tomou seu filho primogênito que ia reinar em seu lugar e o ofereceu como sacrifício queimado sobre a muralha. E veio a haver grande indignação contra Israel, de modo que se retiraram de ir contra ele e retornaram ao seu país.

'''

xref:012-2-reis/012-2-reis-002.adoc#v12-2-0[&#60; Capítulo Anterior] | <<v12-3-0,Topo>> | xref:012-2-reis/012-2-reis-004.adoc#v12-4-0[Próximo Capítulo &#62;]