include::./index.adoc[]

[[v12-1-0]]
=== 2 Reis, 1
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

_ou, segundo a Versão dos Setenta grega: O QUARTO DOS REIS_

[[v12-1-1]]

^<<v12-1-1,1>>^ E Moabe começou a revoltar-se contra Israel depois da morte de Acabe.

[[v12-1-2]]

^<<v12-1-2,2>>^ Então caiu Acazias pela gelosia do seu quarto de terraço, que estava em Samaria, e adoeceu. Enviou, pois, mensageiros e disse-lhes: “Ide, consultai a Baal-Zebube,^&#42;1^ deus^&#42;2^ de Ecrom, sobre se eu reviverei desta doença.”

[NOTE]
====
. “A Baal-Zebube.” Hebr.: beVá·‛al Zevúv, significando “Dono (Senhor) de Moscas”. Veja Mt 12:24 n.
. “Deus de.” Hebr.: ’elo·héh, pl. de ’elóh·ah, para denotar excelência, aplicado a Baal-Zebube. Veja Jz 16:23 n.
====

[[v12-1-3]]

^<<v12-1-3,3>>^ Quanto ao anjo de Jeová, ele falou a Elias,^&#42;1^ o tisbita: “Levanta-te, sobe para te encontrares com os mensageiros do rei de Samaria e dize-lhes: ‘É porque não há nenhum Deus em Israel que ides consultar a Baal-Zebube, deus de Ecrom?

[NOTE]
====
. “Elias.” Hebr.: ’E·li·yáh, significando “Meu Deus É Jah”; LXXBagster(gr.): E·li·oú; Vgc(lat.): E·lí·am. Veja v. 13 n.
====

[[v12-1-4]]

^<<v12-1-4,4>>^ Por esta razão, pois, assim disse Jeová: “No que se refere ao leito ao qual subiste, não descerás dele, porque positivamente morrerás.”’” Com isso Elias foi embora.

[[v12-1-5]]

^<<v12-1-5,5>>^ Quando os mensageiros voltaram a ele, disse-lhes imediatamente: “Por que é que voltastes?”

[[v12-1-6]]

^<<v12-1-6,6>>^ Disseram-lhe, pois: “Um homem veio ao nosso encontro e passou a dizer-nos: ‘Ide, retornai ao rei que vos enviou e tendes de falar-lhe: “Assim disse Jeová: ‘É porque não há nenhum Deus em Israel que mandas consultar a Baal-Zebube, deus de Ecrom? Portanto, no que se refere ao leito ao qual subiste, não descerás dele, porque positivamente morrerás.’”’”

[[v12-1-7]]

^<<v12-1-7,7>>^ Em vista disso, falou-lhes: “Qual era a aparência do homem que veio ao vosso encontro e então vos falou estas palavras?”

[[v12-1-8]]

^<<v12-1-8,8>>^ Disseram-lhe, pois: “Um homem que tinha uma vestimenta de pêlos^&#42;1^ e um cinto de couro cingido em volta dos lombos.” Ele disse imediatamente: “Foi Elias, o tisbita.”

[NOTE]
====
. Lit.: “Um homem dono [hebr.: bá·‛al] de pêlos.”
====

[[v12-1-9]]

^<<v12-1-9,9>>^ E passou a enviar a ele um chefe^&#42;1^ de cinqüenta com os seus cinqüenta. Quando este subiu até ele, eis que estava sentado no cume do monte. Falou-lhe então: “Homem do [verdadeiro] Deus,^&#42;2^ o próprio rei falou: ‘Desce.’”

[NOTE]
====
. “Chefe de.” Hebr.: sar; lat.: prín·ci·pem.
. “Homem do [verdadeiro] Deus.” Hebr.: ’ish ha·’Elo·hím. Veja Ap. 1F.
====

[[v12-1-10]]

^<<v12-1-10,10>>^ Mas Elias respondeu e falou ao chefe dos cinqüenta: “Ora, se eu sou homem de Deus,^&#42;1^ desça fogo dos céus, e devore a ti e os teus cinqüenta.” E veio fogo descendo dos céus e devorando a ele e os seus cinqüenta.

[NOTE]
====
. “Homem de Deus.” Hebr.: ’ish ’Elo·hím.
====

[[v12-1-11]]

^<<v12-1-11,11>>^ De modo que ele lhe enviou novamente outro chefe de cinqüenta com os seus cinqüenta. Este, por sua vez, respondeu e falou-lhe: “Homem do [verdadeiro] Deus, assim disse o rei: ‘Desce depressa.’”

[[v12-1-12]]

^<<v12-1-12,12>>^ Mas Elias respondeu e falou-lhes: “Se eu sou homem do [verdadeiro] Deus, desça fogo dos céus, e devore a ti e os teus cinqüenta.” E veio fogo de Deus descendo dos céus e devorando a ele e os seus cinqüenta.

[[v12-1-13]]

^<<v12-1-13,13>>^ E ele foi enviar novamente um terceiro chefe de cinqüenta e seus cinqüenta. Mas o terceiro chefe de cinqüenta subiu, e chegou e dobrou os joelhos diante de Elias,^&#42;1^ e começou a implorar-lhe favor e a falar-lhe: “Homem do [verdadeiro] Deus, por favor, seja preciosa aos teus olhos a minha alma e a alma destes cinqüenta servos teus.

[NOTE]
====
. Significando “Meu Deus É Jeová”. Hebr.: ’E·li·yá·hu, assim como no restante do relato até 10:17 e em 2Cr 21:12.
====

[[v12-1-14]]

^<<v12-1-14,14>>^ Eis que desceu fogo dos céus e foi devorar os precedentes dois chefes de cinqüenta e seus cinqüenta, mas agora, seja a minha alma preciosa aos teus olhos.”

[[v12-1-15]]

^<<v12-1-15,15>>^ Então falou o anjo de Jeová a Elias: “Desce com ele. Não tenhas medo dele.” Levantou-se, pois, e desceu com ele até o rei.

[[v12-1-16]]

^<<v12-1-16,16>>^ Então lhe falou: “Assim disse Jeová: ‘Visto que enviaste mensageiros para consultarem a Baal-Zebube, deus^&#42;1^ de Ecrom, é porque não há nenhum Deus em Israel cuja palavra se possa consultar? Portanto, no que se refere ao leito ao qual subiste, não descerás dele, porque positivamente morrerás.’”

[NOTE]
====
. “Deus de.” Hebr.: ’elo·héh. Veja v. 2 n.: “deus”.
====

[[v12-1-17]]

^<<v12-1-17,17>>^ E ele finalmente morreu, segundo a palavra de Jeová, que Elias falara; e em seu lugar começou a reinar Jeorão,^&#42;1^ no segundo ano de Jeorão, filho de Jeosafá, rei de Judá, porque não viera a ter filho.

[NOTE]
====
. Significando “Jeová É Alto (Exaltado)”. Hebr.: Yehoh·rám; LXXLSyVg: “Jeorão, seu irmão”.
====

[[v12-1-18]]

^<<v12-1-18,18>>^ Quanto ao resto das coisas de Acazias, que ele fez, não estão escritas no livro dos assuntos dos dias dos reis de Israel?

'''

xref:011-1-reis/011-1-reis-022.adoc#v11-22-0[&#60; Capítulo Anterior] | <<v12-1-0,Topo>> | xref:012-2-reis/012-2-reis-002.adoc#v12-2-0[Próximo Capítulo &#62;]