include::./index.adoc[]

[[v12-13-0]]
=== 2 Reis, 13
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v12-13-1]]

^<<v12-13-1,1>>^ No vigésimo terceiro ano de Jeoás, filho de Acazias, rei de Judá, Jeoacaz, filho de Jeú, tornou-se rei sobre Israel em Samaria, por dezessete anos.

[[v12-13-2]]

^<<v12-13-2,2>>^ E ele fazia o que era mau aos olhos de Jeová e andava atrás do pecado de Jeroboão, filho de Nebate, com que fez Israel pecar. Não se afastou dele.

[[v12-13-3]]

^<<v12-13-3,3>>^ E acendeu-se a ira de Jeová contra Israel, de modo que os entregou na mão de Hazael, rei da Síria, e na mão de Ben-Hadade, filho de Hazael, em todos os seus dias.

[[v12-13-4]]

^<<v12-13-4,4>>^ Com o tempo, Jeoacaz abrandou a face de Jeová, de modo que Jeová o escutou; pois tinha visto a opressão de Israel, porque o rei da Síria os oprimira.

[[v12-13-5]]

^<<v12-13-5,5>>^ Por conseguinte, Jeová deu a Israel um salvador, de modo que saíram de debaixo da mão da Síria, e os filhos de Israel continuaram a morar nos seus lares^&#42;1^ como anteriormente.

[NOTE]
====
. Lit.: “tendas”.
====

[[v12-13-6]]

^<<v12-13-6,6>>^ (Somente não se afastaram do pecado da casa de Jeroboão, com que fez Israel pecar. Nele andou; e até mesmo o próprio poste sagrado^&#42;1^ estava de pé em Samaria.)

[NOTE]
====
. Ou “a Axerá”.
====

[[v12-13-7]]

^<<v12-13-7,7>>^ Porque ele não deixara a Jeoacaz mais povo do que cinqüenta cavaleiros e dez carros, e dez mil homens a pé, porque o rei da Síria os tinha destruído para fazê-los igual ao pó na debulha.

[[v12-13-8]]

^<<v12-13-8,8>>^ Quanto ao resto dos assuntos de Jeoacaz e tudo o que ele fez, e sua potência, não estão escritos no livro dos assuntos dos dias dos reis de Israel?

[[v12-13-9]]

^<<v12-13-9,9>>^ Por fim, Jeoacaz deitou-se com os seus antepassados, e enterraram-no em Samaria; e Jeoás, seu filho, começou a reinar em seu lugar.

[[v12-13-10]]

^<<v12-13-10,10>>^ No trigésimo sétimo ano de Jeoás, rei de Judá, Jeoás, filho de Jeoacaz, tornou-se rei sobre Israel em Samaria, por dezesseis anos.

[[v12-13-11]]

^<<v12-13-11,11>>^ E ele fazia o que era mau aos olhos de Jeová. Não se afastou de todos os pecados de Jeroboão, filho de Nebate, com os quais fez Israel pecar. Neles andou.

[[v12-13-12]]

^<<v12-13-12,12>>^ Quanto ao resto dos assuntos de Jeoás e tudo o que ele fez, e sua potência [e] como lutou contra Amazias, rei de Judá, não estão escritos no livro dos assuntos dos dias dos reis de Israel?

[[v12-13-13]]

^<<v12-13-13,13>>^ Por fim, Jeoás deitou-se com os seus antepassados e o próprio Jeroboão^&#42;1^ se assentou no seu trono. Jeoás, por sua vez, foi enterrado em Samaria com os reis de Israel.

[NOTE]
====
. Isto é, Jeroboão II.
====

[[v12-13-14]]

^<<v12-13-14,14>>^ Quanto a Eliseu, havia adoecido com a doença de que havia de morrer. Portanto, Jeoás, rei de Israel, desceu a ele e começou a chorar sobre a sua face e a dizer: “Meu pai, meu pai, o carro de guerra^&#42;1^ de Israel e seus cavaleiros!”

[NOTE]
====
. Veja 2:12 n.
====

[[v12-13-15]]

^<<v12-13-15,15>>^ E Eliseu passou a dizer-lhe: “Toma um arco e flechas.” Tomou, pois, para si um arco e flechas.

[[v12-13-16]]

^<<v12-13-16,16>>^ E ele prosseguiu, dizendo ao rei de Israel: “Põe a tua mão no arco.”^&#42;1^ Portanto, ele pôs a sua mão nele, após o que Eliseu deitou as suas mãos sobre as mãos do rei.

[NOTE]
====
. Lit.: “Faça a tua mão montar no arco.”
====

[[v12-13-17]]

^<<v12-13-17,17>>^ Então ele disse: “Abre a janela para o leste.” Abriu-a, pois. Por fim Eliseu disse: “Atira!” De modo que atirou. Ele disse então: “A flecha de salvação da parte de Jeová, sim, a flecha de salvação contra a Síria! E certamente golpearás a Síria em Afeque até acabar.”

[[v12-13-18]]

^<<v12-13-18,18>>^ E ele prosseguiu, dizendo: “Toma as flechas.” Então [as] tomou. Ele disse então ao rei de Israel: “Golpeia a terra.” Ele golpeou, pois, três vezes e parou.

[[v12-13-19]]

^<<v12-13-19,19>>^ E o homem do [verdadeiro] Deus ficou indignado com ele; por isso disse: “Era para golpear cinco ou seis vezes!^&#42;1^ Neste caso terias certamente golpeado a Síria até acabar, mas agora é três vezes que golpearás a Síria.”

[NOTE]
====
. “Se tivesses golpeado cinco ou seis vezes”, LXX; Vg: “Se tivesses golpeado cinco, ou seis, ou sete vezes.”
====

[[v12-13-20]]

^<<v12-13-20,20>>^ Depois morreu Eliseu e eles o enterraram. E havia guerrilhas de moabitas que vinham regularmente ao país por volta da entrada do ano.

[[v12-13-21]]

^<<v12-13-21,21>>^ E sucedeu que, quando estavam enterrando um homem, ora, eis que viram a guerrilha. Lançaram imediatamente o homem na sepultura de Eliseu e foram embora. Quando o homem tocou nos ossos de Eliseu, reviveu imediatamente e se pôs de pé.

[[v12-13-22]]

^<<v12-13-22,22>>^ Quanto a Hazael, rei da Síria, oprimiu Israel em todos os dias de Jeoacaz.

[[v12-13-23]]

^<<v12-13-23,23>>^ No entanto, Jeová mostrou-lhes favor e teve misericórdia com eles, e virou-se para eles por causa do seu pacto com Abraão, Isaque e Jacó; e ele não quis arruiná-los e não os lançou fora diante da sua face até agora.

[[v12-13-24]]

^<<v12-13-24,24>>^ Por fim morreu Hazael, rei da Síria, e Ben-Hadade, seu filho, começou a reinar em seu lugar.

[[v12-13-25]]

^<<v12-13-25,25>>^ E Jeoás, filho de Jeoacaz, passou a retomar da mão de Ben-Hadade, filho de Hazael, as cidades que este tinha tirado da mão de Jeoacaz, seu pai, em guerra. Três vezes o golpeou Jeoás e foi recobrar as cidades de Israel.

'''

xref:012-2-reis/012-2-reis-012.adoc#v12-12-0[&#60; Capítulo Anterior] | <<v12-13-0,Topo>> | xref:012-2-reis/012-2-reis-014.adoc#v12-14-0[Próximo Capítulo &#62;]