include::./index.adoc[]

[[v12-5-0]]
=== 2 Reis, 5
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v12-5-1]]

^<<v12-5-1,1>>^ Ora, certo Naamã, chefe do exército do rei da Síria, tornara-se um grande homem diante do seu senhor^&#42;1^ e era estimado,^&#42;2^ pois fora por meio dele que Jeová dera salvação^&#42;3^ à Síria; e o próprio homem mostrara-se valente, poderoso, embora fosse leproso.^&#42;4^

[NOTE]
====
. “Seu senhor (amo).” Hebr.: ’adho·náv, pl. de ’a·dhóhn, para denotar excelência.
. Lit.: “erguido de face”.
. Ou “socorro; livramento”.
. Ou “atacado duma doença da pele”. O termo bíblico para lepra inclui o que hoje é chamado clinicamente de mal de Hansen.
====

[[v12-5-2]]

^<<v12-5-2,2>>^ E os sírios, da sua parte, tinham saído em guerrilhas, e chegaram a levar cativa da terra de Israel uma mocinha, e esta veio a ficar diante da esposa de Naamã.

[[v12-5-3]]

^<<v12-5-3,3>>^ Com o tempo ela disse à sua senhora: “Se tão-somente meu senhor estivesse diante do profeta que está em Samaria! Neste caso o restabeleceria de sua lepra.”

[[v12-5-4]]

^<<v12-5-4,4>>^ Subseqüentemente veio alguém e o relatou ao seu senhor, dizendo: “Foi assim e assim que falou a moça que é da terra de Israel.”

[[v12-5-5]]

^<<v12-5-5,5>>^ Então disse o rei da Síria: “Anda! Vem e deixa-me enviar uma carta ao rei de Israel.” Portanto, ele passou a ir e a tomar na sua mão dez talentos de prata e seis mil moedas de ouro, bem como dez mudas de roupa.

[[v12-5-6]]

^<<v12-5-6,6>>^ E veio trazer a carta ao rei de Israel, dizendo: “E agora, ao mesmo tempo em que recebes esta carta, eis que te envio eu Naamã, meu servo, para que o restabeleças da sua lepra.”

[[v12-5-7]]

^<<v12-5-7,7>>^ E sucedeu que, assim que o rei de Israel leu a carta, rasgou imediatamente as suas vestes e disse: “Acaso sou Deus, para entregar à morte e para preservar vivo? Pois esta pessoa me manda restabelecer um homem da sua lepra; ora, notai só, por favor, e vede como está procurando briga comigo.”

[[v12-5-8]]

^<<v12-5-8,8>>^ E sucedeu que, assim que Eliseu, o homem do [verdadeiro] Deus, ouviu [dizer] que o rei de Israel rasgara as suas vestes, mandou imediatamente dizer ao rei: “Por que rasgaste as tuas vestes? Que venha a mim, por favor, para que saiba que há um profeta em Israel.”

[[v12-5-9]]

^<<v12-5-9,9>>^ Portanto, Naamã veio com os seus cavalos e com os seus carros de guerra, e ficou de pé à entrada da casa de Eliseu.

[[v12-5-10]]

^<<v12-5-10,10>>^ Eliseu, todavia, enviou-lhe um mensageiro, dizendo: “Indo para lá,^&#42;1^ tens de banhar-te sete vezes no Jordão, para que a tua carne volte a ti; e sê limpo.”

[NOTE]
====
. “Indo [para lá].” No hebr., este verbo está no infinitivo absoluto, indefinido quanto ao tempo e impessoal.
====

[[v12-5-11]]

^<<v12-5-11,11>>^ Nisso Naamã ficou indignado e começou a ir-se embora e a dizer: “Eis que eu disse [a mim mesmo]: ‘Virá para fora a mim, e certamente se porá de pé e invocará o nome de Jeová, seu Deus, e moverá a sua mão para cá e para lá sobre o lugar, e realmente restabelecerá o leproso.’

[[v12-5-12]]

^<<v12-5-12,12>>^ Não são o Abana^&#42;1^ e o Farpar, os rios de Damasco, melhores do que todas as águas de Israel? Não me posso banhar neles e certamente ficar limpo?” Com isto se virou e foi embora em furor.

[NOTE]
====
. “Abana”, MLXXVg; MmargemTSy: “Amana”.
====

[[v12-5-13]]

^<<v12-5-13,13>>^ Seus servos aproximaram-se então, e falaram-lhe e disseram: “Meu pai, se tivesse sido uma grande coisa que o próprio profeta te falasse, não a farias? Quanto mais, então, quando ele te disse: ‘Banha-te e sê limpo’?”

[[v12-5-14]]

^<<v12-5-14,14>>^ Então ele desceu e começou a mergulhar^&#42;1^ no Jordão sete vezes, segundo a palavra do homem do [verdadeiro] Deus; depois disso lhe voltou a carne como a carne dum pequeno rapaz e ele ficou limpo.

[NOTE]
====
. “E começou a mergulhar (imergir-se).” Hebr.: wai·yit·ból; gr.: e·ba·ptí·sa·to (de ba·ptí·zo, “batizar”).
====

[[v12-5-15]]

^<<v12-5-15,15>>^ Retornou então ao homem do [verdadeiro] Deus, ele com todo o seu acampamento, e veio e ficou de pé diante dele, e disse: “Ora, eis que sei ao certo que não há Deus em parte alguma da terra a não ser em Israel. E agora, aceita, por favor, um presente de bênção do teu servo.”

[[v12-5-16]]

^<<v12-5-16,16>>^ No entanto, ele disse: “Assim como vive Jeová perante quem estou de pé,^&#42;1^ não o aceitarei.” E começou a instar com ele para que o aceitasse, mas ele o recusava.

[NOTE]
====
. Ou “a quem assisto”.
====

[[v12-5-17]]

^<<v12-5-17,17>>^ Por fim disse Naamã: “Se não, por favor, dê-se ao teu servo um pouco de solo, a carga de um par de mulos; porque o teu servo não mais fará oferta queimada nem sacrifício a quaisquer outros deuses, senão a Jeová.

[[v12-5-18]]

^<<v12-5-18,18>>^ Que Jeová perdoe ao seu servo na seguinte coisa: Quando meu senhor entrar na casa de Rimom, para se curvar ali, e ele se apoiar na minha mão, e eu tiver de curvar-me na casa de Rimom, quando eu me curvar na casa de Rimom, por favor, que Jeová perdoe ao teu servo neste respeito.”

[[v12-5-19]]

^<<v12-5-19,19>>^ Então lhe disse ele: “Vai em paz.” Por conseguinte, foi embora dele [percorrendo] um bom trecho de terra.

[[v12-5-20]]

^<<v12-5-20,20>>^ Então disse Geazi, ajudante de Eliseu, o homem do [verdadeiro] Deus: “Eis que meu amo^&#42;1^ poupou Naamã, este sírio, por não aceitar da sua mão o que ele trouxe. Por Jeová que vive, correrei atrás dele e tomarei algo dele.”

[NOTE]
====
. Ou “meu senhor”. Hebr.: ’a·dho·ní.
====

[[v12-5-21]]

^<<v12-5-21,21>>^ E Geazi foi no encalço de Naamã. Quando Naamã viu alguém correr atrás de si, desceu imediatamente do seu carro para ir ao encontro dele e então disse: “Está tudo bem?”

[[v12-5-22]]

^<<v12-5-22,22>>^ A isto ele disse: “Tudo bem. Meu próprio amo me enviou, dizendo: ‘Eis que agora mesmo vieram ter comigo dois moços da região montanhosa de Efraim, dos filhos dos profetas. Por favor, dá-lhes deveras um talento^&#42;1^ de prata e duas mudas de roupa.’”

[NOTE]
====
. Um talento pesava 34,2 kg.
====

[[v12-5-23]]

^<<v12-5-23,23>>^ A isso Naamã disse: “Vamos! Toma dois talentos.” E continuou a instar com ele e por fim amarrou dois talentos de prata em duas bolsas, com duas mudas de roupa, e deu-os a dois ajudantes seus para que os carregassem na frente dele.

[[v12-5-24]]

^<<v12-5-24,24>>^ Quando chegou a Ofel,^&#42;1^ tirou-os imediatamente da mão deles e os depositou na casa, e mandou os homens embora. Portanto, eles se foram.

[NOTE]
====
. Significando “Protuberância; Inchação; Saliência; Elevação”. Situada em Samaria.
====

[[v12-5-25]]

^<<v12-5-25,25>>^ E ele mesmo entrou e então ficou de pé junto ao seu amo. Eliseu disse-lhe então: “Donde [vieste], Geazi?” Mas ele disse: “Teu servo não foi a parte alguma.”

[[v12-5-26]]

^<<v12-5-26,26>>^ Então lhe disse ele: “Não foi o meu próprio coração contigo exatamente quando o homem se virou [para descer] do seu carro para ir ao teu encontro? É este o tempo de se aceitar prata, ou de se aceitar roupas, ou olivais, ou vinhedos, ou ovelhas, ou gado vacum, ou servos, ou servas?

[[v12-5-27]]

^<<v12-5-27,27>>^ De modo que a lepra de Naamã se apegará a ti e à tua descendência por tempo indefinido.” Saiu imediatamente de diante dele, leproso tão branco como a neve.

'''

xref:012-2-reis/012-2-reis-004.adoc#v12-4-0[&#60; Capítulo Anterior] | <<v12-5-0,Topo>> | xref:012-2-reis/012-2-reis-006.adoc#v12-6-0[Próximo Capítulo &#62;]