include::./index.adoc[]

[[v12-21-0]]
=== 2 Reis, 21
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v12-21-1]]

^<<v12-21-1,1>>^ Manassés tinha doze anos de idade quando começou a reinar e reinou por cinqüenta e cinco anos em Jerusalém. E o nome de sua mãe era Hefzibá.

[[v12-21-2]]

^<<v12-21-2,2>>^ E ele passou a fazer o que era mau aos olhos de Jeová, segundo as coisas detestáveis das nações que Jeová tinha desalojado de diante dos filhos de Israel.

[[v12-21-3]]

^<<v12-21-3,3>>^ De modo que construiu novamente os altos que Ezequias, seu pai, tinha destruído, e erigiu altares a Baal e fez um poste sagrado, assim como fizera Acabe, rei de Israel; e começou a curvar-se diante de todo o exército dos céus e a servi-los.^&#42;1^

[NOTE]
====
. Ou “e a adorá-los (prestar-lhes serviço sagrado)”. Hebr.: wai·ya·‛avódh.
====

[[v12-21-4]]

^<<v12-21-4,4>>^ E construiu altares na casa de Jeová, referente à qual Jeová dissera: “Em Jerusalém porei o meu nome.”

[[v12-21-5]]

^<<v12-21-5,5>>^ E foi construir altares a todo o exército dos céus em dois pátios da casa de Jeová.

[[v12-21-6]]

^<<v12-21-6,6>>^ E ele fez o seu próprio filho passar pelo fogo, e praticou a magia e procurou presságios, e constituiu médiuns espíritas e prognosticadores profissionais de eventos. Fez em grande escala o que era mau aos olhos de Jeová, para o ofender.

[[v12-21-7]]

^<<v12-21-7,7>>^ Além disso, a imagem esculpida do poste sagrado que fizera, ele colocou na casa da qual Jeová dissera a Davi e a Salomão, filho dele: “Nesta casa e em Jerusalém, que escolhi dentre todas as tribos de Israel, porei meu nome por tempo indefinido.

[[v12-21-8]]

^<<v12-21-8,8>>^ E não mais farei o pé de Israel vagar [para longe] do solo que dei aos seus antepassados, contanto que cuidem de fazer segundo tudo o que lhes mandei, sim, conforme toda a lei que meu servo Moisés lhes ordenou.”

[[v12-21-9]]

^<<v12-21-9,9>>^ E eles não escutaram, porém, Manassés continuou a seduzi-los para fazerem o que era mau, mais do que as nações que Jeová aniquilara de diante dos filhos de Israel.

[[v12-21-10]]

^<<v12-21-10,10>>^ E Jeová continuou a falar por meio dos seus servos, os profetas, dizendo:

[[v12-21-11]]

^<<v12-21-11,11>>^ “Visto que Manassés, rei de Judá, fez estas coisas detestáveis, ele agiu de modo mais iníquo do que todos os amorreus antes dele, e passou a fazer até mesmo Judá pecar com os seus ídolos sórdidos.

[[v12-21-12]]

^<<v12-21-12,12>>^ Por isso, assim disse Jeová, o Deus de Israel: ‘Eis que trago sobre Jerusalém e sobre Judá uma calamidade tal que, ouvindo alguém [falar dela], lhe tinirão ambos os ouvidos.

[[v12-21-13]]

^<<v12-21-13,13>>^ E certamente estenderei sobre Jerusalém o cordel de medir aplicado a Samaria e também o nível aplicado à casa de Acabe; e vou esfregar Jerusalém até ficar limpa, assim como se esfrega um tacho sem asas, esfregando-o e emborcando-o.^&#42;1^

[NOTE]
====
. Lit.: “virando-o sobre a sua face”.
====

[[v12-21-14]]

^<<v12-21-14,14>>^ E abandonarei deveras o restante da minha herança, e os entregarei à mão dos seus inimigos, e vão tornar-se saque e rapina para todos os seus inimigos,

[[v12-21-15]]

^<<v12-21-15,15>>^ visto que fizeram o que era mau aos meus olhos e me ofenderam continuamente, desde o dia em que seus antepassados saíram do Egito até o dia de hoje.’”

[[v12-21-16]]

^<<v12-21-16,16>>^ E também sangue inocente derramou Manassés em quantidade muito grande, até encher Jerusalém de ponta a ponta,^&#42;1^ além do pecado com que fez Judá pecar, fazendo o que era mau aos olhos de Jeová.

[NOTE]
====
. Lit.: “boca a boca”. Veja 10:21 n.
====

[[v12-21-17]]

^<<v12-21-17,17>>^ Quanto ao resto dos assuntos de Manassés e tudo o que ele fez, e seu pecado com que pecou, não estão escritos no livro dos assuntos dos dias dos reis de Judá?

[[v12-21-18]]

^<<v12-21-18,18>>^ Por fim, Manassés deitou-se com os seus antepassados e foi enterrado no jardim da sua casa, no jardim de Uza; e Amom, seu filho, começou a reinar em seu lugar.

[[v12-21-19]]

^<<v12-21-19,19>>^ Amom tinha vinte e dois anos de idade quando começou a reinar e reinou por dois anos em Jerusalém. E o nome de sua mãe era Mesulemete, filha de Haruz, de Jotbá.

[[v12-21-20]]

^<<v12-21-20,20>>^ E ele fazia o que era mau aos olhos de Jeová, assim como fizera Manassés, seu pai.

[[v12-21-21]]

^<<v12-21-21,21>>^ E andava em todo o caminho em que seu pai andara e servia os ídolos sórdidos os quais seu pai tinha servido, e curvava-se diante deles.

[[v12-21-22]]

^<<v12-21-22,22>>^ Assim abandonou a Jeová, o Deus de seus antepassados, e não andou no caminho de Jeová.

[[v12-21-23]]

^<<v12-21-23,23>>^ Finalmente, alguns servos de Amom conspiraram contra ele e entregaram o rei à morte, na sua própria casa.

[[v12-21-24]]

^<<v12-21-24,24>>^ Mas o povo da terra golpeou todos os que tinham conspirado contra o Rei Amom. O povo da terra fez então a Josias, seu filho, rei em lugar dele.

[[v12-21-25]]

^<<v12-21-25,25>>^ Quanto ao resto dos assuntos de Amom, o que ele fez, não estão escritos no livro dos assuntos dos dias dos reis de Judá?

[[v12-21-26]]

^<<v12-21-26,26>>^ Enterraram-no,^&#42;1^ pois, no seu sepulcro no jardim de Uza; e Josias, seu filho, começou a reinar em seu lugar.

[NOTE]
====
. “Enterraram-no”, TLagardianLXXSyVg; M: “enterrou-o”.
====

'''

xref:012-2-reis/012-2-reis-020.adoc#v12-20-0[&#60; Capítulo Anterior] | <<v12-21-0,Topo>> | xref:012-2-reis/012-2-reis-022.adoc#v12-22-0[Próximo Capítulo &#62;]