include::./index.adoc[]

[[v12-2-0]]
=== 2 Reis, 2
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v12-2-1]]

^<<v12-2-1,1>>^ E sucedeu que, quando Jeová estava para tomar Elias num vendaval para cima aos céus, Elias e Eliseu^&#42;1^ passaram a ir-se de Gilgal.^&#42;2^

[NOTE]
====
. Significando “Deus É Salvação”. LXX-Bagster(gr.): He·li·sai·é; Vgc(lat.): E·li·sé·us.
. Não a Gilgal perto de Jericó, no vale baixo do Jordão, mas a Gilgal na região das colinas perto de Betel, de onde podiam ‘descer’ a Betel, conforme se diz no v. 2. Veja 4:38.
====

[[v12-2-2]]

^<<v12-2-2,2>>^ E Elias começou a dizer a Eliseu: “Senta-te aqui, por favor, porque o próprio Jeová me enviou até Betel.” Mas Eliseu disse: “Por Jeová que vive e por tua alma que vive, não te deixarei.” Portanto, desceram a Betel.

[[v12-2-3]]

^<<v12-2-3,3>>^ Então os filhos dos profetas que estavam em Betel saíram a Eliseu e disseram-lhe: “Sabes realmente que Jeová tira hoje o teu amo^&#42;1^ de ser cabeça sobre ti?” A isto ele disse: “Bem que também o sei. Ficai quietos.”

[NOTE]
====
. “Teu amo (senhor).” Hebr.: ’adho·neí·kha, pl. de ’a·dhóhn, para denotar excelência.
====

[[v12-2-4]]

^<<v12-2-4,4>>^ Elias disse-lhe então: “Eliseu, por favor, senta-te aqui, porque o próprio Jeová me enviou a Jericó.” Ele disse, porém: “Por Jeová que vive e por tua alma que vive, não te deixarei.” Chegaram, pois, a Jericó.

[[v12-2-5]]

^<<v12-2-5,5>>^ Então os filhos dos profetas que estavam em Jericó se aproximaram de Eliseu e disseram-lhe: “Sabes realmente que Jeová tira hoje teu amo de ser cabeça sobre ti?” A isto ele disse: “Bem que também o sei. Ficai quietos.”

[[v12-2-6]]

^<<v12-2-6,6>>^ Elias disse-lhe então: “Por favor, senta-te aqui, porque o próprio Jeová me enviou ao Jordão.” Ele disse, porém: “Por Jeová que vive e pela tua alma que vive, não te deixarei.” Assim, ambos seguiram adiante.

[[v12-2-7]]

^<<v12-2-7,7>>^ E havia cinqüenta homens dos filhos dos profetas que foram e ficaram de pé à vista, de longe; mas, quanto aos dois, estavam parados junto ao Jordão.

[[v12-2-8]]

^<<v12-2-8,8>>^ Elias tomou então seu manto oficial e o enrolou, e golpeou as águas, e estas se dividiram gradualmente para este e para aquele lado, de modo que ambos fizeram a travessia em solo seco.

[[v12-2-9]]

^<<v12-2-9,9>>^ E sucedeu que, assim que tinham atravessado, o próprio Elias disse a Eliseu: “Pede o que devo fazer por ti antes de eu te ser tirado.” A isto Eliseu disse: “Por favor, venham a mim duas parcelas do teu espírito.”

[[v12-2-10]]

^<<v12-2-10,10>>^ Então ele disse: “Pediste uma coisa difícil. Se me vires quando eu te for tirado, [então] te acontecerá assim; mas, se não, não acontecerá.”

[[v12-2-11]]

^<<v12-2-11,11>>^ E aconteceu que, seguindo eles andando, falando ao andarem, ora, eis um carro de guerra, de fogo, e cavalos de fogo, e eles passaram a fazer uma separação entre os dois; e Elias foi subindo aos céus no vendaval.

[[v12-2-12]]

^<<v12-2-12,12>>^ Enquanto isso, Eliseu o via e clamava: “Meu pai, meu pai, o carro de guerra^&#42;1^ de Israel e seus cavaleiros!” E não o viu mais. Conseqüentemente, agarrou as suas próprias vestes e as rasgou em dois pedaços.

[NOTE]
====
. Ou “carros de guerra”. Hebr.: ré·khev, hebr. sing., possivelmente em sentido coletivo, como também no v. 11.
====

[[v12-2-13]]

^<<v12-2-13,13>>^ Depois apanhou o manto oficial de Elias, que caíra dele, e voltou e parou à beira do Jordão.

[[v12-2-14]]

^<<v12-2-14,14>>^ Tomou então o manto oficial de Elias, que caíra dele, e golpeou as águas e disse: “Onde está Jeová, o Deus de Elias, sim, Ele?” Quando golpeou as águas, então se dividiram gradualmente para este e para aquele lado, de modo que Eliseu atravessou.

[[v12-2-15]]

^<<v12-2-15,15>>^ Quando os filhos dos profetas, que estavam em Jericó, o viram de longe, começaram a dizer: “O espírito de Elias pousou sobre Eliseu.” Concordemente, vieram ao seu encontro e se curvaram^&#42;1^ diante dele até a terra.

[NOTE]
====
. “Se curvaram.” Gr.: pro·se·ký·ne·san. Veja He 1:6 n.
====

[[v12-2-16]]

^<<v12-2-16,16>>^ E foram dizer-lhe: “Ora, eis que há com os teus servos cinqüenta homens, pessoas valentes. Por favor, deixa-os ir e procurar teu amo. O espírito^&#42;1^ de Jeová talvez o tenha carregado e lançado sobre um dos montes ou num dos vales.” Mas ele disse: “Não deveis enviá-los.”

[NOTE]
====
. Ou “vento”. Hebr.: rú·ahh; gr.: pneú·ma; lat.: spí·ri·tus.
====

[[v12-2-17]]

^<<v12-2-17,17>>^ E instavam com ele até que se sentiu embaraçado, de modo que disse: “Enviai.” Enviaram então cinqüenta homens; e eles continuaram a procurar por três dias, mas não o acharam.

[[v12-2-18]]

^<<v12-2-18,18>>^ Quando retornaram a ele, ele morava em Jericó. Então lhes disse: “Não vos disse eu: ‘Não vades’?”

[[v12-2-19]]

^<<v12-2-19,19>>^ Com o tempo, os homens da cidade disseram a Eliseu: “Ora, eis que a localização da cidade é boa, conforme meu amo está vendo; mas a água é má e a terra causa abortos.”

[[v12-2-20]]

^<<v12-2-20,20>>^ Então ele disse: “Trazei-me uma tigelinha nova e ponde sal nela.” Trouxeram-na, pois, a ele.

[[v12-2-21]]

^<<v12-2-21,21>>^ Então saiu até à nascente da água e lançou sal nela, e disse: “Assim disse Jeová: ‘Deveras faço salutar esta água. Dela não resultará mais morte nem causa de aborto.’”

[[v12-2-22]]

^<<v12-2-22,22>>^ E a água continua curada até o dia de hoje, segundo a palavra de Eliseu, que ele havia falado.

[[v12-2-23]]

^<<v12-2-23,23>>^ E dali passou a subir a Betel. Quando subia pelo caminho, havia uns pequenos rapazes que saíram da cidade e começaram a fazer troça dele, e que lhe diziam: “Sobe, careca! Sobe, careca!”

[[v12-2-24]]

^<<v12-2-24,24>>^ Finalmente, ele se virou para trás e os viu, e invocou sobre eles o mal em nome de Jeová. Saíram então da floresta duas ursas e dilaceraram quarenta e dois meninos deles.

[[v12-2-25]]

^<<v12-2-25,25>>^ E ele seguiu de lá para o monte Carmelo, e de lá voltou a Samaria.

'''

xref:012-2-reis/012-2-reis-001.adoc#v12-1-0[&#60; Capítulo Anterior] | <<v12-2-0,Topo>> | xref:012-2-reis/012-2-reis-003.adoc#v12-3-0[Próximo Capítulo &#62;]