include::./index.adoc[]

[[v12-7-0]]
=== 2 Reis, 7
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v12-7-1]]

^<<v12-7-1,1>>^ Eliseu disse então: “Escutai a palavra de Jeová. Assim disse Jeová: ‘Amanhã, por volta desta hora, uma medida de seá^&#42;1^ de flor de farinha valerá um siclo^&#42;2^ e dois seás de cevada valerão um siclo no portão de Samaria.’”

[NOTE]
====
. Um seá equivalia a 7,33 l.
. Veja Ap. 8A.
====

[[v12-7-2]]

^<<v12-7-2,2>>^ Então, o ajudante-de-ordens, em cuja mão o rei se apoiava, respondeu ao homem do [verdadeiro] Deus e disse: “Se Jeová fizesse comportas nos céus, poderia acontecer tal coisa?” A isto ele disse: “Eis que o verás com os teus próprios olhos, mas não comerás disso.”

[[v12-7-3]]

^<<v12-7-3,3>>^ E havia quatro homens, leprosos, que vieram a estar junto à entrada do portão; e eles começaram a dizer um ao outro: “Por que estamos ainda sentados aqui até termos morrido?

[[v12-7-4]]

^<<v12-7-4,4>>^ Se disséssemos: ‘Vamos entrar na cidade’, quando há fome na cidade, então teríamos de morrer nela. E se ficarmos sentados aqui, também teremos de morrer. Portanto, vinde agora e invadamos o acampamento dos sírios. Se nos preservarem vivos, viveremos; mas, se nos entregarem à morte, então teremos de morrer.”

[[v12-7-5]]

^<<v12-7-5,5>>^ Por conseguinte, levantaram-se no crepúsculo vespertino para entrar no acampamento dos sírios; e chegaram até os limites do acampamento dos sírios, e eis que não havia ninguém ali.

[[v12-7-6]]

^<<v12-7-6,6>>^ E o próprio Jeová^&#42;1^ fizera que o acampamento dos sírios ouvisse o ruído de carros de guerra, o ruído de cavalos, o ruído duma grande força militar, de modo que disseram um ao outro: “Eis que o rei de Israel contratou contra nós os reis dos hititas e os reis do Egito, para virem contra nós!”

[NOTE]
====
. Uma das 134 mudanças de YHWH para ’Adho·naí feitas pelos escribas. Veja Ap. 1B.
====

[[v12-7-7]]

^<<v12-7-7,7>>^ Levantaram-se imediatamente e puseram-se em fuga no crepúsculo vespertino, e foram deixando atrás as suas tendas, e os seus cavalos, e os seus jumentos — o acampamento assim como estava — e seguiram fugindo pela sua alma.^&#42;1^

[NOTE]
====
. Ou “vida”.
====

[[v12-7-8]]

^<<v12-7-8,8>>^ Quando esses leprosos chegaram até os limites do acampamento, entraram numa tenda e começaram a comer e a beber, e carregaram dali prata, e ouro, e roupas, e foram e os encobriram. Depois retornaram e entraram em outra tenda, e carregaram dela coisas, e foram e as encobriram.

[[v12-7-9]]

^<<v12-7-9,9>>^ Por fim começaram a dizer um ao outro: “Não está direito o que estamos fazendo. Este dia é um dia de boas novas! Se hesitarmos e realmente esperarmos até à luz da manhã, então terá de alcançar-nos a culpa. Portanto, vinde agora e entremos, e informemos a casa do rei.”

[[v12-7-10]]

^<<v12-7-10,10>>^ Chegaram, pois, e chamaram os porteiros da cidade, e informaram-nos, dizendo: “Entramos no acampamento dos sírios e eis que não havia ninguém por lá, nem som de homem, mas apenas os cavalos presos e os jumentos presos, e as tendas assim como estavam.”

[[v12-7-11]]

^<<v12-7-11,11>>^ Os porteiros clamaram imediatamente e informaram a casa do rei, lá dentro.

[[v12-7-12]]

^<<v12-7-12,12>>^ O rei se levantou imediatamente de noite e disse aos seus servos: “Por favor, deixai-me dizer-vos o que os sírios nos fizeram. Bem sabem que estamos com fome; e por isso saíram do acampamento para se esconder no campo, dizendo: ‘Sairão da cidade e nós os pegaremos vivos, e entraremos na cidade.’”

[[v12-7-13]]

^<<v12-7-13,13>>^ Então respondeu um dos seus servos e disse: “Por favor, tomem-se cinco dos cavalos restantes que restaram na cidade. Eis que são iguais a toda a massa de gente de Israel que resta nela. Eis que são iguais a toda a massa de gente de Israel que pereceu. E mandemos ver.”

[[v12-7-14]]

^<<v12-7-14,14>>^ Conseqüentemente, tomaram dois carros com cavalos e o rei os enviou atrás do acampamento dos sírios, dizendo: “Ide e vede.”

[[v12-7-15]]

^<<v12-7-15,15>>^ Então seguiram atrás deles até o Jordão; e eis que todo o caminho estava cheio de roupas e utensílios que os sírios tinham lançado fora na sua corrida precipitada. Os mensageiros voltaram então e informaram o rei.

[[v12-7-16]]

^<<v12-7-16,16>>^ E o povo passou a sair e a saquear o acampamento dos sírios; e assim, uma medida de seá de flor de farinha chegou a valer um siclo e dois seás de cevada valiam um siclo, segundo a palavra de Jeová.

[[v12-7-17]]

^<<v12-7-17,17>>^ E o próprio rei encarregara do portão o ajudante-de-ordens em cuja mão se apoiava; e o povo foi atropelá-lo no portão, de modo que morreu, assim como falara o homem do [verdadeiro] Deus quando falou na ocasião em que o rei descera a ele.

[[v12-7-18]]

^<<v12-7-18,18>>^ Portanto, sucedeu exatamente assim como o homem do [verdadeiro] Deus falara ao rei, dizendo: “Duas medidas de seá de cevada valendo um siclo e um seá de flor de farinha valendo um siclo virá a haver amanhã, nesta hora, no portão de Samaria.”

[[v12-7-19]]

^<<v12-7-19,19>>^ Mas o ajudante-de-ordens respondera ao homem do [verdadeiro] Deus e dissera: “Mesmo se Jeová fizesse comportas nos céus, poderia suceder isso segundo esta palavra?” A isto ele dissera: “Eis que o verás com os teus próprios olhos, mas não comerás disso.”

[[v12-7-20]]

^<<v12-7-20,20>>^ De maneira que lhe aconteceu assim quando o povo o foi atropelar no portão de modo que morreu.

'''

xref:012-2-reis/012-2-reis-006.adoc#v12-6-0[&#60; Capítulo Anterior] | <<v12-7-0,Topo>> | xref:012-2-reis/012-2-reis-008.adoc#v12-8-0[Próximo Capítulo &#62;]