include::./index.adoc[]

[[v12-19-0]]
=== 2 Reis, 19
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v12-19-1]]

^<<v12-19-1,1>>^ E aconteceu que, assim que o Rei Ezequias [as] ouviu, rasgou imediatamente as suas vestes e cobriu-se de serapilheira, e entrou na casa de Jeová.

[[v12-19-2]]

^<<v12-19-2,2>>^ Além disso, enviou Eliaquim, que estava sobre os da casa, e Sebna, o secretário, e os anciãos dos sacerdotes, cobertos de serapilheira, a Isaías,^&#42;1^ o profeta, filho de Amoz.

[NOTE]
====
. Significando “Salvação de Jeová”. Hebr.: Yesha·‛eyá·hu; LXXVg: “Esaias”. Esta é a primeira ocorrência deste nome.
====

[[v12-19-3]]

^<<v12-19-3,3>>^ E passaram a dizer-lhe: “Assim disse Ezequias: ‘Este dia é um dia de aflição, e de repreensão, e de desaforo; porque os filhos chegaram até à boca da madre e não há poder para dar à luz.

[[v12-19-4]]

^<<v12-19-4,4>>^ Talvez Jeová, teu Deus, ouça todas as palavras de Rabsaqué, a quem o rei da Assíria, seu senhor, enviou para escarnecer do Deus vivente, e ele realmente o chame às contas pelas palavras que Jeová, teu Deus, ouviu. E terás de elevar oração a favor do restante que se pode achar.’”

[[v12-19-5]]

^<<v12-19-5,5>>^ Portanto, os servos do Rei Ezequias entraram até Isaías.

[[v12-19-6]]

^<<v12-19-6,6>>^ Isaías disse-lhes então: “Isto é o que deveis dizer ao vosso senhor: ‘Assim disse Jeová: “Não tenhas medo por causa das palavras que ouviste, com que os ajudantes do rei da Assíria me ultrajaram.

[[v12-19-7]]

^<<v12-19-7,7>>^ Eis que ponho nele um espírito, e ele terá de ouvir uma notícia e voltar à sua própria terra; e eu hei de fazê-lo cair pela espada na sua própria terra.”’”

[[v12-19-8]]

^<<v12-19-8,8>>^ Depois disso, Rabsaqué retornou e achou o rei da Assíria lutando contra Libna; pois ouvira [dizer] que tinha partido de Laquis.

[[v12-19-9]]

^<<v12-19-9,9>>^ Ele ouviu dizer a respeito de Tiraca, rei da Etiópia:^&#42;1^ “Eis que ele saiu para lutar contra ti.” Por isso enviou novamente mensageiros a Ezequias, dizendo:

[NOTE]
====
. “Etiópia (etíopes)”, LXXVg; hebr.: Kush.
====

[[v12-19-10]]

^<<v12-19-10,10>>^ “Isto é o que deveis dizer a Ezequias, rei de Judá: ‘Não te engane teu Deus, em quem confias, dizendo: “Jerusalém não será entregue na mão do rei da Assíria.”

[[v12-19-11]]

^<<v12-19-11,11>>^ Eis que tu mesmo ouviste o que os reis da Assíria fizeram a todas as terras, devotando-as à destruição; e serás tu mesmo livrado?

[[v12-19-12]]

^<<v12-19-12,12>>^ Livraram-nas os deuses das nações que meus antepassados arruinaram, sim, Gozã e Harã, e Rezefe, e os filhos de Éden, que estavam em Tel-Assar?

[[v12-19-13]]

^<<v12-19-13,13>>^ Onde está ele — o rei de Hamate, e o rei de Arpade, e o rei das cidades de Sefarvaim, Hena e Iva?’”

[[v12-19-14]]

^<<v12-19-14,14>>^ Ezequias tirou então as cartas da mão dos mensageiros e as leu, após o que Ezequias subiu à casa de Jeová e a estendeu diante de Jeová.

[[v12-19-15]]

^<<v12-19-15,15>>^ E Ezequias começou a orar diante de Jeová e a dizer: “Ó Jeová, Deus de Israel, sentado sobre os querubins, só tu és o [verdadeiro] Deus de todos os reinos da terra. És tu que fizeste os céus e a terra.

[[v12-19-16]]

^<<v12-19-16,16>>^ Inclina o teu ouvido, ó Jeová, e ouve. Abre os teus olhos, ó Jeová, e vê, e ouve as palavras de Senaqueribe, que ele enviou para escarnecer do Deus vivente.^&#42;1^

[NOTE]
====
. “Deus vivente.” Hebr.: ’Elo·hím, pl., seguido pelo adjetivo sing. hhai, “vivente”, como no v. 4.
====

[[v12-19-17]]

^<<v12-19-17,17>>^ É um fato, ó Jeová, que os reis da Assíria têm devastado as nações e sua terra.

[[v12-19-18]]

^<<v12-19-18,18>>^ E entregaram seus deuses ao fogo, porque não eram deuses,^&#42;1^ mas trabalho das mãos de homem, madeira e pedra; de modo que os destruíram.

[NOTE]
====
. Ou “não eram Deus”. Hebr.: lo’ ’elo·hím; LXXVg: “não eram deuses”.
====

[[v12-19-19]]

^<<v12-19-19,19>>^ E agora, ó Jeová, nosso Deus, salva-nos, por favor, da sua mão, para que todos os reinos da terra saibam que somente tu, ó Jeová, és Deus.”

[[v12-19-20]]

^<<v12-19-20,20>>^ E Isaías, filho de Amoz, passou a mandar dizer a Ezequias: “Assim disse Jeová, Deus de Israel: ‘Ouvi a oração que fizeste a mim referente a Senaqueribe, rei da Assíria.

[[v12-19-21]]

^<<v12-19-21,21>>^ Esta é a palavra que Jeová falou contra ele:
“A virgem filha de Sião te desprezou, caçoou de ti.
Atrás de ti, a filha de Jerusalém meneou a cabeça.

[[v12-19-22]]

^<<v12-19-22,22>>^ A quem escarneceste e ultrajaste?
E contra quem elevaste a voz
E ergues os teus olhos para o alto?
É contra o Santo de Israel!

[[v12-19-23]]

^<<v12-19-23,23>>^ Por meio dos teus mensageiros escarneceste de Jeová^&#42;1^ e dizes:
‘Com a multidão^&#42;2^ dos meus carros de guerra, eu mesmo—
Eu hei de subir ao alto das regiões montanhosas,
Às partes mais remotas do Líbano;
E deceparei os seus altos cedros, seus juníperos seletos,
E entrarei na sua pousada final, a floresta do seu pomar.

[NOTE]
====
. Uma das 134 mudanças de YHWH para ’Adho·naí feitas pelos escribas. Veja Ap. 1B.
. “Com a multidão”, MmargemLXXSyVg e Is 37:24.
====

[[v12-19-24]]

^<<v12-19-24,24>>^ Eu é que hei de cavar e beber águas estranhas,
E secarei com as solas dos meus pés todos os canais do Nilo do Egito.’

[[v12-19-25]]

^<<v12-19-25,25>>^ Não ouviste? Desde os tempos remotos é o que vou fazer.
Desde os dias de outrora o formei.
Agora o vou introduzir.
E tu servirás para fazer desoladas cidades fortificadas, como montões de ruínas.

[[v12-19-26]]

^<<v12-19-26,26>>^ E seus habitantes terão mãos fracas;
Estarão simplesmente aterrorizados e envergonhados.
Terão de tornar-se como a vegetação do campo e a tenra relva verde,
Grama dos telhados, quando há o crestamento diante do vento oriental.

[[v12-19-27]]

^<<v12-19-27,27>>^ E conheço bem teu sentar quieto, e tua saída e tua entrada,
E tua agitação contra mim,

[[v12-19-28]]

^<<v12-19-28,28>>^ Porque a tua agitação contra mim e a tua vociferação subiram aos meus ouvidos.
E hei de pôr meu gancho no teu nariz e meu freio entre os teus lábios,
E deveras te conduzirei de volta pelo caminho por onde vieste.”

[[v12-19-29]]

^<<v12-19-29,29>>^ “‘E este será o sinal para ti: Comer-se-á^&#42;1^ este ano do que crescer de grãos caídos, e no segundo ano, grãos que brotam por si mesmos; mas no terceiro ano, semeai e colhei, e plantai vinhedos, e comei dos seus frutos.

[NOTE]
====
. “Comer-se-á.” No hebr., este verbo está no infinitivo absoluto, indefinido quanto ao tempo e impessoal.
====

[[v12-19-30]]

^<<v12-19-30,30>>^ E os que escaparem, da casa de Judá, os que restarem, certamente lançarão raízes para baixo e produzirão frutos para cima.

[[v12-19-31]]

^<<v12-19-31,31>>^ Pois, de Jerusalém sairá um restante, e os que escapam, do monte Sião. O próprio zelo de Jeová dos exércitos^&#42;1^ fará isso.

[NOTE]
====
. “Jeová dos exércitos”, MmargemLXXSyVg, muitos mss. hebr. e Is 37:32. Trata-se de qere, não de kethib (lido, mas não escrito), onde se encontram os sinais vocálicos para a palavra “exércitos” sem consoantes no M.
====

[[v12-19-32]]

^<<v12-19-32,32>>^ “‘Por isso é que Jeová disse assim com respeito ao rei da Assíria: “Ele não entrará nesta cidade, nem atirará flecha nela, nem a confrontará com escudo, nem levantará um aterro de sítio contra ela.

[[v12-19-33]]

^<<v12-19-33,33>>^ Pelo caminho por onde passou a vir, ele voltará, e não entrará nesta cidade, é a pronunciação de Jeová.

[[v12-19-34]]

^<<v12-19-34,34>>^ E eu certamente defenderei esta cidade para a salvar por minha própria causa e por causa de Davi, meu servo.”’”

[[v12-19-35]]

^<<v12-19-35,35>>^ E sucedeu, naquela noite, que o anjo de Jeová passou a sair e a golpear cento e oitenta e cinco mil no acampamento dos assírios. Quando pessoas se levantaram de manhã cedo, ora, eis que todos eles eram cadáveres.

[[v12-19-36]]

^<<v12-19-36,36>>^ Partiu, pois, Senaqueribe, rei da Assíria, e foi e retornou, e passou a morar em Nínive.

[[v12-19-37]]

^<<v12-19-37,37>>^ E sucedeu que, curvando-se ele na casa de Nisroque, seu deus,^&#42;1^ os próprios Adrameleque e Sarezer, seus filhos,^&#42;2^ golpearam-no com a espada, e eles mesmos escaparam para a terra de Ararate.^&#42;3^ E Esar-Hadom, seu filho, começou a reinar em seu lugar.

[NOTE]
====
. “Seu deus.” Hebr.: ’elo·háv, pl. de ’elóh·ah, aplicado ao falso deus Nisroque para denotar excelência.
. “Seus filhos”, Mmar-gemLXXSyVg, muitos mss. hebr. e Is 37:38. Trata-se de qere, não de kethib (lido, mas não escrito). Veja v. 31 n.
. “De Ararate”, MLXXSy; Vg: “dos armênios”.
====

'''

xref:012-2-reis/012-2-reis-018.adoc#v12-18-0[&#60; Capítulo Anterior] | <<v12-19-0,Topo>> | xref:012-2-reis/012-2-reis-020.adoc#v12-20-0[Próximo Capítulo &#62;]