include::./index.adoc[]

[[v12-15-0]]
=== 2 Reis, 15
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v12-15-1]]

^<<v12-15-1,1>>^ No vigésimo sétimo ano de Jeroboão, rei de Israel, tornou-se rei Azarias, filho de Amazias, rei de Judá.

[[v12-15-2]]

^<<v12-15-2,2>>^ Veio a ter dezesseis anos de idade quando começou a reinar e reinou por cinqüenta e dois anos em Jerusalém. E o nome de sua mãe era Jecolia,^&#42;1^ de Jerusalém.

[NOTE]
====
. Significando “Jeová Tem Sido Capaz”. Hebr.: Yekhol·yá·hu.
====

[[v12-15-3]]

^<<v12-15-3,3>>^ E ele fazia o que era reto aos olhos de Jeová, segundo tudo o que Amazias, seu pai, tinha feito.

[[v12-15-4]]

^<<v12-15-4,4>>^ Apenas os altos não desapareceram. O povo ainda oferecia sacrifícios e fazia fumaça sacrificial nos altos.

[[v12-15-5]]

^<<v12-15-5,5>>^ Por fim, Jeová atingiu o rei com uma praga e ele ficou sendo leproso até o dia da sua morte, e morava na sua casa, livre de deveres, ao passo que Jotão, o filho do rei, estava sobre a casa, julgando o povo da terra.^&#42;1^

[NOTE]
====
. “O povo da terra.” Hebr.: ‛am ha·’á·rets. Veja Gên 23:7 n.
====

[[v12-15-6]]

^<<v12-15-6,6>>^ Quanto ao resto dos assuntos de Azarias^&#42;1^ e tudo o que ele fez, não estão escritos no livro dos assuntos dos dias dos reis de Judá?

[NOTE]
====
. Significando “Jeová Ajudou”. Hebr.: ‛Azar·yá·hu. No v. 13; em 2Cr 26:1-23; Is 6:1; Za 14:5: “Uzias”.
====

[[v12-15-7]]

^<<v12-15-7,7>>^ Por fim, Azarias deitou-se com os seus antepassados e enterraram-no com os seus antepassados na Cidade de Davi; e Jotão, seu filho, começou a reinar em seu lugar.

[[v12-15-8]]

^<<v12-15-8,8>>^ No trigésimo oitavo ano de Azarias, rei de Judá, Zacarias,^&#42;1^ filho de Jeroboão, tornou-se rei sobre Israel em Samaria, por seis meses.

[NOTE]
====
. Significando “Jeová Lembrou-se”. Hebr.: Zekhar·yá·hu.
====

[[v12-15-9]]

^<<v12-15-9,9>>^ E ele fazia o que era mau aos olhos de Jeová, assim como seus antepassados tinham feito. Não se afastou dos pecados de Jeroboão, filho de Nebate, com os quais fez Israel pecar.

[[v12-15-10]]

^<<v12-15-10,10>>^ Salum, filho de Jabes, conspirou então contra ele e o golpeou em Ibleão,^&#42;1^ e o entregou à morte, e começou a reinar em seu lugar.

[NOTE]
====
. “Em Ibleão”, LXXL; M: “perante o povo”; Vg: “publicamente”.
====

[[v12-15-11]]

^<<v12-15-11,11>>^ Quanto ao resto dos assuntos de Zacarias, eis que estão escritos no livro dos assuntos dos dias dos reis de Israel.

[[v12-15-12]]

^<<v12-15-12,12>>^ Esta foi a palavra de Jeová, que ele falara a Jeú, dizendo: “Os próprios filhos, até a quarta geração, se sentarão por ti no trono de Israel.” E assim sucedeu.

[[v12-15-13]]

^<<v12-15-13,13>>^ Quanto a Salum, filho de Jabes, tornou-se ele rei no trigésimo nono ano de Uzias,^&#42;1^ rei de Judá, e continuou a reinar um mês lunar inteiro^&#42;2^ em Samaria.

[NOTE]
====
. “De Uzias.” Hebr.: le‛U·zi·yáh, significando “Minha Força É Jah”; no v. 1: “Azarias”. Veja v. 6 n.
. Lit.: “um mês lunar de dias”.
====

[[v12-15-14]]

^<<v12-15-14,14>>^ Menaém, filho de Gadi, subiu então de Tirza e chegou a Samaria, e ele golpeou a Salum, filho de Jabes, em Samaria, e o entregou à morte; e começou a reinar em seu lugar.

[[v12-15-15]]

^<<v12-15-15,15>>^ Quanto ao resto dos assuntos de Salum e sua conspiração com que conspirou, eis que estão escritos no livro dos assuntos dos dias dos reis de Israel.

[[v12-15-16]]

^<<v12-15-16,16>>^ Foi então que Menaém passou a golpear a Tifsa e a tudo o que havia nela, e seu território fora de Tirza, porque não se abriu,^&#42;1^ e ele foi golpeá-la. Estripou todas as suas mulheres grávidas.

[NOTE]
====
. “Porque não lhe abriram (o portão)”, LXXSyVg.
====

[[v12-15-17]]

^<<v12-15-17,17>>^ No trigésimo nono ano de Azarias,^&#42;1^ rei de Judá, Menaém, filho de Gadi, tornou-se rei sobre Israel por dez anos, em Samaria.

[NOTE]
====
. “De Azarias.” Hebr.: la·‛Azar·yáh; no v. 13: “Uzias”. Veja v. 6 n.
====

[[v12-15-18]]

^<<v12-15-18,18>>^ E fazia o que era mau aos olhos de Jeová. Não se afastou de todos os pecados de Jeroboão, filho de Nebate, com que fez Israel pecar, em todos os seus dias.

[[v12-15-19]]

^<<v12-15-19,19>>^ Entrou no país Pul, o rei da Assíria. Conseqüentemente, Menaém deu a Pul mil talentos de prata, para que as suas mãos se mostrassem com ele para fortalecer o reino na sua própria mão.

[[v12-15-20]]

^<<v12-15-20,20>>^ Por isso, Menaém trouxe para fora a prata às custas de Israel, às custas de todos os valentes, poderosos, para dar ao rei da Assíria cinqüenta siclos^&#42;1^ de prata para cada homem. Em vista disso, o rei da Assíria recuou e não ficou ali no país.

[NOTE]
====
. Veja Ap. 8A.
====

[[v12-15-21]]

^<<v12-15-21,21>>^ Quanto ao resto dos assuntos de Menaém e tudo o que ele fez, não estão escritos no livro dos assuntos dos dias dos reis de Israel?

[[v12-15-22]]

^<<v12-15-22,22>>^ Por fim, Menaém deitou-se com os seus antepassados, e Pecaías, seu filho, começou a reinar em seu lugar.

[[v12-15-23]]

^<<v12-15-23,23>>^ No qüinquagésimo ano de Azarias, rei de Judá, Pecaías, filho de Menaém, tornou-se rei sobre Israel em Samaria, por dois anos.

[[v12-15-24]]

^<<v12-15-24,24>>^ E ele fazia o que era mau aos olhos de Jeová. Não se afastou dos pecados de Jeroboão, filho de Nebate, com que fez Israel pecar.

[[v12-15-25]]

^<<v12-15-25,25>>^ Então conspirou contra ele Peca, filho de Remalias,^&#42;1^ seu ajudante-de-ordens, e golpeou-o em Samaria, na torre de habitação da casa do rei, com Argobe e Arié, e com ele havia cinqüenta homens dos filhos de Gileade.^&#42;2^ De modo que o entregou à morte e começou a reinar em seu lugar.

[NOTE]
====
. Significando “Jeová Adornou”. Hebr.: Remal·yá·hu.
. Mediante uma emenda; M: “filhos de gileaditas”.
====

[[v12-15-26]]

^<<v12-15-26,26>>^ Quanto ao resto dos assuntos de Pecaías e tudo o que ele fez, eis que estão escritos no livro dos assuntos dos dias dos reis de Israel.

[[v12-15-27]]

^<<v12-15-27,27>>^ No qüinquagésimo segundo ano de Azarias, rei de Judá, Peca, filho de Remalias, tornou-se rei sobre Israel em Samaria, por vinte anos.

[[v12-15-28]]

^<<v12-15-28,28>>^ E ele fazia o que era mau aos olhos de Jeová. Não se afastou dos pecados de Jeroboão, filho de Nebate, com que fez Israel pecar.

[[v12-15-29]]

^<<v12-15-29,29>>^ Nos dias de Peca, rei de Israel, entrou Tiglate-Pileser, rei da Assíria, e passou a tomar Ijom, e Abel-Bete-Maacá, e Janoa, e Quedes, e Hazor, e Gileade, e a Galiléia,^&#42;1^ toda a terra de Naftali, e a levá-los ao exílio na Assíria.

[NOTE]
====
. Lit.: “a Galiléia”. Hebr.: hag·Ga·lí·lah; gr.: Ga·li·laí·an; lat.: Ga·li·lé·am. Veja Jos 20:7 n.: “Galiléia”.
====

[[v12-15-30]]

^<<v12-15-30,30>>^ Finalmente, Oséias, filho de Elá, formou uma conspiração contra Peca, filho de Remalias, e golpeou-o e entregou-o à morte; e começou a reinar em seu lugar no vigésimo ano de Jotão, filho de Uzias.^&#42;1^

[NOTE]
====
. “Azarias” no v. 1.
====

[[v12-15-31]]

^<<v12-15-31,31>>^ Quanto ao resto dos assuntos de Peca e tudo o que ele fez, eis que estão escritos no livro dos assuntos dos dias dos reis de Israel.

[[v12-15-32]]

^<<v12-15-32,32>>^ No segundo ano de Peca, filho de Remalias, rei de Israel, tornou-se rei Jotão, filho de Uzias, rei de Judá.

[[v12-15-33]]

^<<v12-15-33,33>>^ Veio a ter vinte e cinco anos de idade quando começou a reinar e reinou por dezesseis anos em Jerusalém. E o nome de sua mãe era Jerusa, filha de Zadoque.

[[v12-15-34]]

^<<v12-15-34,34>>^ E ele fazia o que era direito aos olhos de Jeová. Fazia segundo tudo o que Uzias, seu pai, tinha feito.

[[v12-15-35]]

^<<v12-15-35,35>>^ Apenas não desapareceram os altos. O povo ainda oferecia sacrifícios e fazia fumaça sacrificial nos altos. Foi ele quem construiu o portão superior da casa de Jeová.

[[v12-15-36]]

^<<v12-15-36,36>>^ Quanto ao resto dos assuntos de Jotão, o que ele fez, não estão escritos no livro dos assuntos dos dias dos reis de Judá?

[[v12-15-37]]

^<<v12-15-37,37>>^ Naqueles dias Jeová principiou a enviar contra Judá a Rezim, rei da Síria, e a Peca, filho de Remalias.

[[v12-15-38]]

^<<v12-15-38,38>>^ Por fim, Jotão deitou-se com os seus antepassados e foi enterrado com os seus antepassados na Cidade de Davi, seu antepassado; e Acaz, seu filho, começou a reinar em seu lugar.

'''

xref:012-2-reis/012-2-reis-014.adoc#v12-14-0[&#60; Capítulo Anterior] | <<v12-15-0,Topo>> | xref:012-2-reis/012-2-reis-016.adoc#v12-16-0[Próximo Capítulo &#62;]