include::./index.adoc[]

[[v12-9-0]]
=== 2 Reis, 9
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v12-9-1]]

^<<v12-9-1,1>>^ E Eliseu, o profeta, da sua parte, chamou um dos filhos dos profetas e disse-lhe então: “Cinge os teus lombos e toma este frasco^&#42;1^ de óleo na tua mão, e vai a Ramote-Gileade.

[NOTE]
====
. Ou “jarrinho”, de cerâmica.
====

[[v12-9-2]]

^<<v12-9-2,2>>^ Quando tiveres entrado lá, vê por lá a Jeú, filho de Jeosafá, filho de Ninsi; e tens de entrar e fazê-lo levantar-se do meio dos seus irmãos, e tens de levá-lo à câmara mais recôndita.

[[v12-9-3]]

^<<v12-9-3,3>>^ E tens de tomar o frasco de óleo e despejá-lo sobre a sua cabeça, e dizer: ‘Assim disse Jeová: “Deveras te unjo como rei sobre Israel.”’ E tens de abrir a porta e fugir, e não esperar.”

[[v12-9-4]]

^<<v12-9-4,4>>^ E o ajudante, o ajudante do profeta, pôs-se a caminho para Ramote-Gileade.

[[v12-9-5]]

^<<v12-9-5,5>>^ Quando entrou, ora, eis que os chefes da força militar estavam sentados. Ele disse então: “Tenho uma palavra para ti, ó chefe.” Jeú disse então: “Para qual de todos nós?” Então disse: “Para ti, ó chefe.”

[[v12-9-6]]

^<<v12-9-6,6>>^ Ele se levantou, pois, e entrou na casa; e passou a despejar o óleo sobre a cabeça dele e a dizer-lhe: “Assim disse Jeová, o Deus de Israel: ‘Deveras te unjo como rei sobre o povo de Jeová, isto é, sobre Israel.

[[v12-9-7]]

^<<v12-9-7,7>>^ E tens de golpear a casa de Acabe, teu senhor, e eu tenho de vingar o sangue dos meus servos, os profetas, e o sangue^&#42;1^ de todos os servos de Jeová da mão de Jezabel.

[NOTE]
====
. Lit.: “sangues”.
====

[[v12-9-8]]

^<<v12-9-8,8>>^ E tem de perecer toda a casa de Acabe; e tenho de decepar de Acabe aquele que urina contra o muro,^&#42;1^ bem como o incapacitado e o rejeitado^&#42;2^ em Israel.

[NOTE]
====
. “Que urina contra o muro.” Esta é uma expressão idiomática hebr. referindo-se a varões.
. Lit.: “o restrito e o largado (abandonado)”. Veja De 32:36 n.: “rejeitado”.
====

[[v12-9-9]]

^<<v12-9-9,9>>^ E tenho de constituir a casa de Acabe igual à casa de Jeroboão, filho de Nebate, e igual à casa de Baasa, filho de Aijá.

[[v12-9-10]]

^<<v12-9-10,10>>^ E a Jezabel os cães devorarão no pedaço de terreno de Jezreel, e não haverá quem a enterre.’” Com isso ele abriu a porta e se pôs em fuga.

[[v12-9-11]]

^<<v12-9-11,11>>^ Quanto a Jeú, saiu aos servos do seu senhor e eles começaram a dizer-lhe: “Está tudo bem? Por que veio a ti este louco?” Mas ele lhes disse: “Vós mesmos bem conheceis o homem e seu tipo de conversa.”

[[v12-9-12]]

^<<v12-9-12,12>>^ Mas eles disseram: “É falso!^&#42;1^ Conta-nos, por favor.” Então disse: “Foi assim e assim que ele me falou, dizendo: ‘Assim disse Jeová: “Deveras te unjo como rei sobre Israel.”’”

[NOTE]
====
. Lit.: “Falsidade!”
====

[[v12-9-13]]

^<<v12-9-13,13>>^ Em vista disso tomaram cada um apressadamente a sua veste e a puseram debaixo dele sobre os degraus nus, e começaram a tocar a buzina e a dizer: “Jeú tornou-se rei!”

[[v12-9-14]]

^<<v12-9-14,14>>^ E Jeú, filho de Jeosafá, filho de Ninsi, passou a conspirar contra Jeorão.^&#42;1^
E tinha acontecido que o próprio Jeorão ficara de guarda em Ramote-Gileade, ele com todo o Israel, por causa de Hazael, rei da Síria.

[NOTE]
====
. “Jeorão.” Hebr.: Yoh·rám, como em 8:16.
====

[[v12-9-15]]

^<<v12-9-15,15>>^ Mais tarde Jeorão, o rei, voltou para se curar em Jezreel das feridas que os sírios chegaram a infligir-lhe quando lutou contra Hazael, rei da Síria.
Jeú disse então: “Se a vossa alma concordar,^&#42;1^ não deixeis a ninguém sair escapando da cidade para ir e comunicar [isso] em Jezreel.”

[NOTE]
====
. Lit.: “Se houver vossa alma.”
====

[[v12-9-16]]

^<<v12-9-16,16>>^ E Jeú começou a guiar [um carro] e a ir a Jezreel, porque lá estava deitado Jeorão, e o próprio Acazias,^&#42;1^ rei de Judá, tinha descido para visitar Jeorão.

[NOTE]
====
. “E . . . Acazias.” Hebr.: wa·’Ahhaz·yáh. Veja 1Rs 22:40 n.
====

[[v12-9-17]]

^<<v12-9-17,17>>^ E o vigia estava de pé sobre a torre em Jezreel e via a massa movimentada [dos homens] de Jeú quando ele vinha, e disse imediatamente: “Eu estou vendo uma massa movimentada [de homens].” Então disse Jeorão: “Toma um cavalariano e envia-o ao encontro deles, e diga ele: ‘Há paz?’”

[[v12-9-18]]

^<<v12-9-18,18>>^ Concordemente, um cavaleiro num cavalo foi ao encontro dele e disse: “Assim disse o rei: ‘Há paz?’” Mas Jeú disse: “Que tens tu que ver com a ‘paz’?^&#42;1^ Dá volta até à minha retaguarda!”
E o vigia continuou a informar, dizendo: “O mensageiro chegou até eles, mas não voltou.”

[NOTE]
====
. Lit.: “Que [há] para ti e para a paz?” Veja Ap. 7B.
====

[[v12-9-19]]

^<<v12-9-19,19>>^ De modo que enviou um segundo cavaleiro num cavalo, o qual, chegando a eles, passou a dizer: “Assim disse o rei: ‘Há paz?’” Mas Jeú disse: “Que tens tu que ver com a ‘paz’? Dá volta até à minha retaguarda!”

[[v12-9-20]]

^<<v12-9-20,20>>^ E o vigia prosseguiu a informar, dizendo: “Chegou até eles, mas não voltou; e o guiar é como o guiar de Jeú, neto^&#42;1^ de Ninsi, pois é com loucura que ele guia [o carro].”

[NOTE]
====
. Lit.: “filho”.
====

[[v12-9-21]]

^<<v12-9-21,21>>^ Então disse Jeorão: “Atrelar!” Atrelou-se, pois, o seu carro, e saíram Jeorão, rei de Israel, e Acazias, rei de Judá, cada um no seu próprio carro de guerra. E saindo ao encontro de Jeú, foram encontrar-se com ele no lote de terreno de Nabote, o jezreelita.

[[v12-9-22]]

^<<v12-9-22,22>>^ E sucedeu que, assim que Jeorão viu a Jeú, disse imediatamente: “Há paz, Jeú?” Mas ele disse: “Que paz pode haver enquanto há as fornicações de Jezabel, tua mãe, e as suas muitas feitiçarias?”

[[v12-9-23]]

^<<v12-9-23,23>>^ Jeorão deu imediatamente volta com as suas mãos para fugir e disse a Acazias: “Há trapaça, Acazias!”

[[v12-9-24]]

^<<v12-9-24,24>>^ E o próprio Jeú encheu a sua mão com um arco e passou a flechar Jeorão entre os braços, de modo que a flecha lhe saiu pelo coração e ele tombou no seu carro de guerra.

[[v12-9-25]]

^<<v12-9-25,25>>^ Ele disse então a Bidcar,^&#42;1^ seu ajudante-de-ordens: “Levanta-o; lança-o no pedaço de campo de Nabote, o jezreelita; pois, lembra-te: eu e tu guiávamos parelhas atrás de Acabe, seu pai, e o próprio Jeová levantou contra ele a seguinte pronúncia:

[NOTE]
====
. “Bidcar”, M; Sy: “Bendequer”.
====

[[v12-9-26]]

^<<v12-9-26,26>>^ ‘“Eu certamente vi ontem o sangue de Nabote e o sangue de seus filhos”, é a pronunciação de Jeová, “e certamente te retribuirei neste lote de terreno”, é a pronunciação de Jeová.’ Agora, pois, levanta-o; lança-o no lote de terreno segundo a palavra de Jeová.”

[[v12-9-27]]

^<<v12-9-27,27>>^ E o próprio Acazias, rei de Judá, viu isso e se pôs em fuga pelo caminho da casa do jardim. (Mais tarde^&#42;1^ Jeú foi persegui-lo e disse: “Também a ele! Golpeai-o!” Assim, golpearam-no^&#42;2^ enquanto estava no carro subindo a Gur, que está junto a Ibleão. E ele prosseguiu na sua fuga a Megido e foi morrer lá.

[NOTE]
====
. Veja 2Cr 22:7-9.
. “Assim, golpearam-no”, SyVgc; M omite isso.
====

[[v12-9-28]]

^<<v12-9-28,28>>^ Seus servos carregaram-no então num carro a Jerusalém e enterraram-no assim no seu sepulcro, com os seus antepassados, na Cidade de Davi.

[[v12-9-29]]

^<<v12-9-29,29>>^ E foi no décimo primeiro ano de Jeorão, filho de Acabe, que Acazias se tornara rei sobre Judá.)

[[v12-9-30]]

^<<v12-9-30,30>>^ Finalmente, Jeú chegou a Jezreel e a própria Jezabel o soube. E ela passou a pintar os seus olhos de preto e a arrumar belamente a sua cabeça, e foi olhar pela janela.

[[v12-9-31]]

^<<v12-9-31,31>>^ E o próprio Jeú entrou pelo portão. Ela disse então: “Foi tudo bem com Zinri, matador de seu senhor?”

[[v12-9-32]]

^<<v12-9-32,32>>^ Então ele levantou a sua face para a janela e disse: “Quem é comigo? Quem?” Dois ou três oficiais da corte olharam imediatamente para baixo, para ele.

[[v12-9-33]]

^<<v12-9-33,33>>^ De modo que ele disse: “Deixai-a cair!” Então a deixaram cair, e um pouco do seu sangue salpicou o muro e os cavalos; e ele a atropelou então.

[[v12-9-34]]

^<<v12-9-34,34>>^ Depois entrou, e comeu e bebeu, e então disse: “Por favor, tomai conta desta maldita e enterrai-a, pois ela é filha de rei.”

[[v12-9-35]]

^<<v12-9-35,35>>^ Quando a foram enterrar, não acharam nada dela senão o crânio, e os pés, e as palmas das suas mãos.

[[v12-9-36]]

^<<v12-9-36,36>>^ Quando retornaram e o informaram, ele prosseguiu, dizendo: “É a palavra de Jeová, que ele falou por intermédio do seu servo Elias,^&#42;1^ o tisbita, dizendo: ‘No lote de terreno de Jezreel os cães comerão a carne de Jezabel.

[NOTE]
====
. “Elias.” Hebr.: ’E·li·yá·hu. Veja 1:13 n.
====

[[v12-9-37]]

^<<v12-9-37,37>>^ E o cadáver de Jezabel há de tornar-se estrume sobre a face do campo no lote de terreno de Jezreel, para que não se diga: “Esta é Jezabel.”’”

'''

xref:012-2-reis/012-2-reis-008.adoc#v12-8-0[&#60; Capítulo Anterior] | <<v12-9-0,Topo>> | xref:012-2-reis/012-2-reis-010.adoc#v12-10-0[Próximo Capítulo &#62;]