include::./index.adoc[]

[[v12-4-0]]
=== 2 Reis, 4
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v12-4-1]]

^<<v12-4-1,1>>^ Ora, havia certa mulher das esposas dos filhos dos profetas que clamou a Eliseu, dizendo: “Teu servo, meu esposo, morreu; e tu mesmo bem sabes que o teu próprio servo temia continuamente a Jeová, e veio o próprio credor para tomar ambos os meus filhos a fim de serem escravos seus.”

[[v12-4-2]]

^<<v12-4-2,2>>^ Eliseu disse-lhe então: “Que devo fazer por ti? Dize-me; o que tens na casa?” A isto ela disse: “Tua serva não tem absolutamente nada na casa a não ser um jarro de bico com azeite.”

[[v12-4-3]]

^<<v12-4-3,3>>^ Ele disse então: “Vai, pede para ti vasos, de fora, de todos os teus vizinhos, vasos vazios. Não te restrinjas a poucos.

[[v12-4-4]]

^<<v12-4-4,4>>^ E tens de ir e fechar a porta atrás de ti e de teus filhos, e tens de despejar em todos estes vasos, e os cheios tens de pôr de lado.”

[[v12-4-5]]

^<<v12-4-5,5>>^ Então ela se foi dele.
Quando fechou a porta atrás de si e de seus filhos, traziam-lhe [os vasos] perto e ela despejava [neles].

[[v12-4-6]]

^<<v12-4-6,6>>^ E sucedeu que, assim que os vasos estavam cheios, ela foi dizer a seu filho: “Traze-me ainda outro vaso.” Mas ele lhe disse: “Não há mais outro vaso.” Nisso o azeite parou.

[[v12-4-7]]

^<<v12-4-7,7>>^ Ela entrou, pois, e o contou ao homem do [verdadeiro] Deus, e este disse então: “Vai, vende o azeite e paga as tuas dívidas, e tu [e] teus filhos deveis viver do que sobrar.”

[[v12-4-8]]

^<<v12-4-8,8>>^ E sucedeu, certo dia, que Eliseu estava passando para Suném, onde havia uma mulher de destaque, e ela começou a constrangê-lo a comer pão. E aconteceu que, quantas vezes ele passasse, desviava-se para ali comer pão.

[[v12-4-9]]

^<<v12-4-9,9>>^ Por fim ela disse a seu esposo: “Ora, eis que bem sei que é um homem santo de Deus que está constantemente passando por nós.

[[v12-4-10]]

^<<v12-4-10,10>>^ Por favor, façamos um pequeno quarto de terraço junto ao muro e ponhamos lá para ele um leito, e uma mesa, e uma cadeira, e um candelabro; e terá de acontecer que, cada vez que ele chegar a nós, poderá desviar-se para lá.”

[[v12-4-11]]

^<<v12-4-11,11>>^ E certo dia sucedeu que ele entrou ali como de costume e se desviou para o quarto de terraço, e deitou-se ali.

[[v12-4-12]]

^<<v12-4-12,12>>^ Ele disse então a Geazi, seu ajudante: “Chama esta mulher sunamita.” Chamou-a, pois, para que ficasse de pé diante dele.

[[v12-4-13]]

^<<v12-4-13,13>>^ Então lhe disse ele: “Por favor, dize-lhe: ‘Eis que te restringiste por nós com toda esta restrição. Que se há de fazer por ti? Há algo a falar por ti ao rei ou ao chefe do exército?’” A isto ela disse: “Moro no meio do meu próprio povo.”

[[v12-4-14]]

^<<v12-4-14,14>>^ E ele prosseguiu, dizendo: “Então, o que se há de fazer por ela?” Geazi disse então: “É fato que ela não tem filho e que seu esposo é idoso.”

[[v12-4-15]]

^<<v12-4-15,15>>^ Ele disse imediatamente: “Chama-a.” Chamou-a, pois, e ela ficou de pé à entrada.

[[v12-4-16]]

^<<v12-4-16,16>>^ Então ele disse: “Neste tempo designado no ano que vem^&#42;1^ abraçarás um filho.” Mas ela disse: “Não, meu amo, homem do [verdadeiro] Deus! Não profiras mentiras no que se refere à tua serva.”

[NOTE]
====
. “Neste tempo designado no ano que vem.” Veja Gên 18:10 n.
====

[[v12-4-17]]

^<<v12-4-17,17>>^ No entanto, a mulher ficou grávida e deu à luz um filho no tempo designado do ano seguinte, assim como Eliseu lhe falara.

[[v12-4-18]]

^<<v12-4-18,18>>^ E o menino crescia, e aconteceu certo dia que ele saiu como de costume para ir ter com seu pai que estava com os ceifeiros.

[[v12-4-19]]

^<<v12-4-19,19>>^ E dizia a seu pai: “Minha cabeça, ai! minha cabeça!” Finalmente este disse ao ajudante: “Carrega-o à sua mãe.”

[[v12-4-20]]

^<<v12-4-20,20>>^ Por conseguinte, carregou-o e trouxe-o à sua mãe. E ele ficou sentado nos joelhos dela até o meio-dia, e por fim morreu.

[[v12-4-21]]

^<<v12-4-21,21>>^ Então ela subiu e o deitou no leito do homem do [verdadeiro] Deus, e fechou a porta sobre ele e saiu.

[[v12-4-22]]

^<<v12-4-22,22>>^ Ela chamou então seu esposo e disse: “Envia-me, por favor, um dos ajudantes e uma das jumentas, e deixa-me correr até o homem do [verdadeiro] Deus e voltar.”

[[v12-4-23]]

^<<v12-4-23,23>>^ Mas ele disse: “Por que vais a ele hoje? Não é lua nova nem sábado.” No entanto, ela disse: “Não faz mal.”

[[v12-4-24]]

^<<v12-4-24,24>>^ De modo que selou a jumenta e disse ao seu ajudante: “Guia e vai na frente. Não te detenhas, por minha causa, de seguir cavalgando, a menos que eu to diga.”

[[v12-4-25]]

^<<v12-4-25,25>>^ E ela passou a ir e a chegar ao homem do [verdadeiro] Deus, ao monte Carmelo. E sucedeu que, assim que o homem do [verdadeiro] Deus a viu lá adiante, disse imediatamente a Geazi, seu ajudante: “Eis lá a sunamita.

[[v12-4-26]]

^<<v12-4-26,26>>^ Por favor, corre agora ao encontro dela e dize-lhe: ‘Tudo bem contigo? Tudo bem com o teu marido? Tudo bem com o menino?’” A isto ela disse: “Tudo bem.”

[[v12-4-27]]

^<<v12-4-27,27>>^ Quando chegou ao homem do [verdadeiro] Deus ao monte, agarrou-o imediatamente pelos pés. Então se chegou Geazi para empurrá-la, mas o homem do [verdadeiro] Deus disse: “Deixa-a, porque a sua alma nela está amargurada; e o próprio Jeová mo ocultou e não me informou.”

[[v12-4-28]]

^<<v12-4-28,28>>^ Ela disse então: “Pedi eu algum filho por intermédio de meu senhor? Não disse eu: ‘Não me deves dar uma falsa esperança’?”

[[v12-4-29]]

^<<v12-4-29,29>>^ Ele disse imediatamente a Geazi: “Cinge os teus lombos e toma meu bastão na tua mão, e vai. Caso encontres alguém, não o deves cumprimentar; e caso alguém te cumprimente, não lhe deves responder. E tens de pôr meu bastão sobre a face do rapazinho.”

[[v12-4-30]]

^<<v12-4-30,30>>^ Então disse a mãe do rapazinho: “Por Jeová que vive e por tua alma que vive, não te deixarei.” Portanto, ele se levantou e foi com ela.^&#42;1^

[NOTE]
====
. Ou “após ela”. Em vez de dizer “junto com ela”, os hebreus amiúde diziam “atrás dela; após ela”.
====

[[v12-4-31]]

^<<v12-4-31,31>>^ E o próprio Geazi passou adiante deles e então pôs o bastão sobre a face do rapazinho, mas não havia voz nem se dava atenção. Por isso voltou ao encontro dele e informou-o, dizendo: “O rapazinho não acordou.”

[[v12-4-32]]

^<<v12-4-32,32>>^ Por fim entrou Eliseu na casa, e eis que o rapazinho estava morto, deitado no seu leito.

[[v12-4-33]]

^<<v12-4-33,33>>^ Então entrou e fechou a porta atrás de ambos, e começou a orar a Jeová.

[[v12-4-34]]

^<<v12-4-34,34>>^ Finalmente subiu e se deitou sobre o menino, e pôs a sua própria boca sobre a boca dele, e seus próprios olhos sobre os olhos dele, e as suas próprias palmas sobre as palmas das mãos dele, e ficou abaixado sobre ele, e a carne do menino aqueceu-se gradualmente.

[[v12-4-35]]

^<<v12-4-35,35>>^ Depois começou a andar novamente na casa, uma vez para cá e outra vez para lá, após o que subiu e se abaixou sobre ele. E o rapazinho começou a espirrar^&#42;1^ tantas quantas sete vezes, após o que o rapazinho abriu os seus olhos.

[NOTE]
====
. Ou “piscar”.
====

[[v12-4-36]]

^<<v12-4-36,36>>^ Ele chamou então a Geazi e disse: “Chama esta sunamita.” De modo que a chamou e ela entrou até ele. Então ele disse: “Levanta teu filho.”

[[v12-4-37]]

^<<v12-4-37,37>>^ E ela passou a entrar e a lançar-se aos seus pés e a curvar-se diante dele para a terra, após o que levantou seu filho e saiu.

[[v12-4-38]]

^<<v12-4-38,38>>^ E o próprio Eliseu retornou a Gilgal,^&#42;1^ e havia fome no país. Visto que os filhos dos profetas estavam sentados diante dele, disse então ao seu ajudante: “Põe a panela grande e faze um cozido para os filhos dos profetas.”

[NOTE]
====
. Veja 2:1 n.: “Gilgal”.
====

[[v12-4-39]]

^<<v12-4-39,39>>^ Concordemente, saiu um ao campo para colher malvas, e foi achar uma trepadeira silvestre e colher dela bagas, enchendo a sua veste, e depois veio e retalhou-as dentro da panela do cozido, porque não as conheciam.

[[v12-4-40]]

^<<v12-4-40,40>>^ Mais tarde o despejaram para os homens comerem. E sucedeu que, assim que comeram do cozido começaram a dizer: “Há morte na panela, homem do [verdadeiro] Deus.” E não puderam comer.

[[v12-4-41]]

^<<v12-4-41,41>>^ Ele disse, pois: “Trazei então farinha.” Depois de lançá-la na panela prosseguiu, dizendo: “Despejai para o povo comer.” E não se mostrou haver nada nocivo na panela.

[[v12-4-42]]

^<<v12-4-42,42>>^ E chegou um homem de Baal-Salisa e veio trazer ao homem do [verdadeiro] Deus pão dos primeiros frutos maduros, vinte pães de cevada, e cereal novo no seu saco de pão. Ele disse então: “Dá-o ao povo para que comam.”

[[v12-4-43]]

^<<v12-4-43,43>>^ No entanto, seu servente disse: “Como porei isto diante de cem homens?” A isto ele disse: “Dá-o ao povo para que comam, pois assim disse Jeová: ‘Comer-se-á e haverá sobras.’”^&#42;1^

[NOTE]
====
. “Comer-se-á e haverá sobras.” No hebr., estes verbos estão no infinitivo absoluto, indefinidos quanto ao tempo e impessoais.
====

[[v12-4-44]]

^<<v12-4-44,44>>^ Então o pôs diante deles e eles começaram a comer, e tiveram sobras, segundo a palavra de Jeová.

'''

xref:012-2-reis/012-2-reis-003.adoc#v12-3-0[&#60; Capítulo Anterior] | <<v12-4-0,Topo>> | xref:012-2-reis/012-2-reis-005.adoc#v12-5-0[Próximo Capítulo &#62;]