include::./index.adoc[]

[[v12-6-0]]
=== 2 Reis, 6
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v12-6-1]]

^<<v12-6-1,1>>^ E os filhos dos profetas começaram a dizer a Eliseu: “Ora, eis que o lugar em que estamos morando diante de ti é apertado demais para nós.

[[v12-6-2]]

^<<v12-6-2,2>>^ Por favor, vamos até o Jordão e tomemos de lá cada um uma viga, e façamos lá para nós um lugar para morar.” Ele disse, pois: “Ide.”

[[v12-6-3]]

^<<v12-6-3,3>>^ E um prosseguiu, dizendo: “Resolve-te, por favor, e vem com os teus servos.” A isto ele disse: “Eu mesmo irei.”

[[v12-6-4]]

^<<v12-6-4,4>>^ Por conseguinte, foi com eles, e por fim chegaram ao Jordão e começaram a cortar as árvores.

[[v12-6-5]]

^<<v12-6-5,5>>^ E sucedeu que um estava cortando a sua viga, e caiu na água o próprio ferro do machado.^&#42;1^ E ele começou a clamar e a dizer: “Ai! meu amo, porque foi tomado emprestado.”

[NOTE]
====
. Lit. só “o ferro”.
====

[[v12-6-6]]

^<<v12-6-6,6>>^ O homem do [verdadeiro] Deus disse então: “Onde caiu?” Mostrou-lhe, pois, o lugar. Ele cortou imediatamente um pedaço de lenha e o lançou para lá, e fez flutuar o ferro do machado.

[[v12-6-7]]

^<<v12-6-7,7>>^ Então disse: “Retira-o para ti.” Ele estendeu imediatamente a sua mão e tomou-o.

[[v12-6-8]]

^<<v12-6-8,8>>^ E o rei da Síria, da sua parte, ficou envolvido numa guerra contra Israel. Por conseguinte, aconselhou-se com os seus servos, dizendo: “Em tal e tal lugar vos acampareis comigo.”^&#42;1^

[NOTE]
====
. “Acampareis comigo”, mediante uma ligeira mudança no M.
====

[[v12-6-9]]

^<<v12-6-9,9>>^ Então o homem do [verdadeiro] Deus mandou dizer ao rei de Israel: “Guarda-te de passar por este lugar, porque é lá que os sírios estão descendo.”

[[v12-6-10]]

^<<v12-6-10,10>>^ Por isso o rei de Israel enviou [alguém] ao lugar que o homem do [verdadeiro] Deus lhe dissera. E avisou-o, e ele se manteve afastado de lá, não uma vez nem duas.

[[v12-6-11]]

^<<v12-6-11,11>>^ Conseqüentemente, o coração do rei da Síria ficou enfurecido por causa deste assunto, de modo que chamou os seus servos e lhes disse: “Não me informareis quem dentre os que me pertencem está do lado do rei de Israel?”

[[v12-6-12]]

^<<v12-6-12,12>>^ Um dos seus servos disse então: “Ninguém, meu senhor, o rei, mas é Eliseu, o profeta que está em Israel, quem informa o rei de Israel sobre as coisas que falas no teu dormitório interno.”

[[v12-6-13]]

^<<v12-6-13,13>>^ Ele disse, pois: “Ide e vede onde ele está, a fim de que eu mande trazê-lo.” Mais tarde foi-lhe comunicado, dizendo-se: “Eis que está em Dotã.”

[[v12-6-14]]

^<<v12-6-14,14>>^ Ele enviou imediatamente para lá cavalos, e carros de guerra, e uma pesada força militar; e eles passaram a vir de noite e a rodear a cidade.

[[v12-6-15]]

^<<v12-6-15,15>>^ Quando o ministro do homem do [verdadeiro] Deus madrugou para se levantar e saiu, ora, eis que uma força militar cercava a cidade com cavalos e com carros de guerra. Seu ajudante lhe disse imediatamente: “Ai! meu amo. Que faremos?”

[[v12-6-16]]

^<<v12-6-16,16>>^ Mas ele disse: “Não tenhas medo, porque mais são os que estão conosco do que os que estão com eles.”

[[v12-6-17]]

^<<v12-6-17,17>>^ E Eliseu começou a orar e a dizer: “Ó Jeová, por favor, abre-lhe os olhos para que veja.” Jeová abriu imediatamente os olhos do ajudante de modo que viu; e eis que a região montanhosa estava cheia de cavalos e de carros de guerra, de fogo, em torno de Eliseu.

[[v12-6-18]]

^<<v12-6-18,18>>^ Quando começaram a descer a ele, Eliseu prosseguiu orando a Jeová e dizendo: “Por favor, fere esta nação^&#42;1^ de cegueira.” De modo que os feriu de cegueira segundo a palavra de Eliseu.

[NOTE]
====
. Ou “estes gentios (pagãos)”.
====

[[v12-6-19]]

^<<v12-6-19,19>>^ Eliseu disse-lhes então: “Este não é o caminho e esta não é a cidade. Segui-me e deixai-me conduzir-vos ao homem que procurais.” Todavia, conduziu-os a Samaria.

[[v12-6-20]]

^<<v12-6-20,20>>^ E sucedeu que, assim que chegaram a Samaria, Eliseu disse então: “Ó Jeová, abre os olhos destes para que vejam.” Jeová abriu-lhes imediatamente os olhos e eles passaram a ver; e eis que estavam no meio de Samaria.

[[v12-6-21]]

^<<v12-6-21,21>>^ O rei de Israel disse então a Eliseu, assim que os viu: “Devo golpeá-los, devo golpeá-los, meu pai?”

[[v12-6-22]]

^<<v12-6-22,22>>^ Ele disse, porém: “Não deves golpeá-los. São estes os que capturaste com a tua espada e com o teu arco que estás golpeando? Põe diante deles pão e água para que comam e bebam, e para que vão para seu senhor.”

[[v12-6-23]]

^<<v12-6-23,23>>^ Por conseguinte, ofereceu-lhes um grande banquete; e começaram a comer e a beber, após o que os mandou embora e eles foram para seu senhor. E nem uma única vez vieram as guerrilhas dos sírios de novo à terra de Israel.

[[v12-6-24]]

^<<v12-6-24,24>>^ E depois sucedeu que Ben-Hadade, rei da Síria, passou a reunir todo o seu acampamento e a subir e sitiar Samaria.

[[v12-6-25]]

^<<v12-6-25,25>>^ Com o tempo veio a haver uma grande fome em Samaria, e eis que a sitiavam até que a cabeça dum jumento chegou a valer oitenta moedas de prata e um quarto da medida de um cabo^&#42;1^ de esterco de pombas valeu cinco moedas de prata.

[NOTE]
====
. Um cabo equivalia a 1,22 l.
====

[[v12-6-26]]

^<<v12-6-26,26>>^ E aconteceu que, passeando o rei de Israel em cima da muralha, clamou a ele certa mulher, dizendo: “Salva deveras, ó meu senhor, o rei!”

[[v12-6-27]]

^<<v12-6-27,27>>^ A isto ele disse: “Se Jeová não te salva, de que [fonte] te salvarei eu, quer procedente da eira, quer do lagar de vinho ou de azeite?”

[[v12-6-28]]

^<<v12-6-28,28>>^ E o rei prosseguiu, dizendo-lhe: “Que tens?” De modo que ela disse: “Esta mesma mulher me disse: ‘Dá o teu filho para que o comamos hoje, e amanhã comeremos o meu próprio filho.’

[[v12-6-29]]

^<<v12-6-29,29>>^ Por conseguinte, cozinhamos o meu filho e o comemos. Então eu lhe disse no dia seguinte: ‘Dá o teu filho para que o comamos.’ Mas ela escondeu o seu filho.”

[[v12-6-30]]

^<<v12-6-30,30>>^ E sucedeu que, assim que o rei ouviu as palavras da mulher, rasgou imediatamente as suas vestes; e passeando ele em cima da muralha, o povo chegou a ver, e eis que havia serapilheira por baixo, sobre a sua carne.

[[v12-6-31]]

^<<v12-6-31,31>>^ E ele prosseguiu, dizendo: “Assim me faça Deus e assim lhe acrescente mais, se a cabeça de Eliseu, filho de Safate, ficar hoje sobre ele!”

[[v12-6-32]]

^<<v12-6-32,32>>^ E Eliseu estava sentado na sua própria casa e com ele estavam sentados os anciãos,^&#42;1^ quando aquele enviou um homem de diante de si. Antes que o mensageiro pudesse chegar a ele, ele próprio disse aos anciãos: “Vistes como este filho dum assassino mandou tirar-me a cabeça? Vede: assim que o mensageiro chegar, fechai a porta, e tendes de premi-lo para trás com a porta. Não é este o som dos pés do seu senhor atrás dele?”

[NOTE]
====
. “E . . . os anciãos.” Hebr.: wehaz·zeqe·ním; gr.: pre·sbý·te·roi. Veja At 15:2 n.
====

[[v12-6-33]]

^<<v12-6-33,33>>^ Enquanto ainda falava com eles, eis que descia o mensageiro^&#42;1^ a ele, e [o rei]^&#42;2^ passou a dizer: “Eis que esta é a calamidade da parte de Jeová. Por que devia eu esperar mais por Jeová?”

[NOTE]
====
. Possivelmente: “o rei”. Veja 7:2.
. Lit.: “ele”. Veja 7:2.
====

'''

xref:012-2-reis/012-2-reis-005.adoc#v12-5-0[&#60; Capítulo Anterior] | <<v12-6-0,Topo>> | xref:012-2-reis/012-2-reis-007.adoc#v12-7-0[Próximo Capítulo &#62;]