include::./index.adoc[]

[[v1-38-0]]
=== Gênesis, 38
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v1-38-1]]

^<<v1-38-1,1>>^ Ora, entrementes sucedeu que, descendo Judá de [onde estavam] seus irmãos, armou [a sua tenda] perto dum homem, um adulamita, e o nome dele era Hira.

[[v1-38-2]]

^<<v1-38-2,2>>^ E ali Judá chegou a ver a filha de certo cananeu, e o nome dele^&#42;1^ era Sua. Tomou-a, pois, e teve relações com ela.

[NOTE]
====
. “Dele”, M; LXXSy: “dela”.
====

[[v1-38-3]]

^<<v1-38-3,3>>^ E ela ficou grávida. Mais tarde deu à luz um filho e chamou-o pelo nome de Er.

[[v1-38-4]]

^<<v1-38-4,4>>^ Ficou novamente grávida. A seu tempo, ela deu à luz um filho e chamou-o pelo nome de Onã.

[[v1-38-5]]

^<<v1-38-5,5>>^ Mais uma vez foi dar à luz um filho, e chamou-o então pelo nome de Selá. Ora, aconteceu que ele^&#42;1^ estava em Aczibe,^&#42;2^ no tempo em que ela o deu à luz.

[NOTE]
====
. “Ele”, isto é, Judá; LXX: “ela”.
. Entende-se tratar-se da mesma “Aczibe” de Jos 15:44 e Miq 1:14; M: “Quezibe”.
====

[[v1-38-6]]

^<<v1-38-6,6>>^ Com o tempo, Judá tomou uma esposa para Er, seu primogênito, e o nome dela era Tamar.

[[v1-38-7]]

^<<v1-38-7,7>>^ Mas Er, primogênito de Judá, mostrou-se mau aos olhos de Jeová; Jeová o entregou por isso à morte.

[[v1-38-8]]

^<<v1-38-8,8>>^ Em vista disso, Judá disse a Onã: “Tem relações com^&#42;1^ a esposa de teu irmão e realiza um casamento de cunhado^&#42;2^ com ela, e suscita descendência para teu irmão.”

[NOTE]
====
. Lit.: “Entra a.”
. Ou “casamento levirato”. Jeová deu posteriormente reconhecimento oficial a isso na Lei mosaica, em De 25:5-9.
====

[[v1-38-9]]

^<<v1-38-9,9>>^ Mas Onã sabia que a descendência não se tornaria sua; e deu-se que, quando teve relações com a esposa de seu irmão, desperdiçou o seu sêmen na terra,^&#42;1^ para não dar descendência a seu irmão.

[NOTE]
====
. Lit.: “desperdiçou[-o] na terra”.
====

[[v1-38-10]]

^<<v1-38-10,10>>^ Ora, o que ele fez era mau aos olhos de Jeová; por isso, entregou-o também à morte.

[[v1-38-11]]

^<<v1-38-11,11>>^ De modo que Judá disse a Tamar, sua nora: “Mora como viúva na casa de teu pai até crescer Selá, meu filho.” Pois ele disse para si mesmo:^&#42;1^ “Ele também poderia morrer como seus irmãos.” Concordemente, Tamar foi e continuou a morar na casa de seu próprio pai.

[NOTE]
====
. Ou: “Pois ele pensava.”
====

[[v1-38-12]]

^<<v1-38-12,12>>^ Passaram-se assim muitos dias, e morreu a filha de Sua, esposa de Judá; e Judá guardou o período de luto. Depois subiu até os tosquiadores de suas ovelhas, a Timná, ele e Hira, seu companheiro, o adulamita.

[[v1-38-13]]

^<<v1-38-13,13>>^ Então foi comunicado a Tamar: “Eis que o teu sogro está subindo a Timná para tosquiar as suas ovelhas.”

[[v1-38-14]]

^<<v1-38-14,14>>^ Em vista disso, removeu de si as roupas de sua viuvez e cobriu-se com um xale, e velou-se, e assentou-se à entrada de Enaim, que se acha na estrada de Timná. Pois ela via que Selá tinha crescido, contudo, não lhe tinha sido dada como esposa.

[[v1-38-15]]

^<<v1-38-15,15>>^ Quando Judá a avistou, teve-a imediatamente por meretriz,^&#42;1^ porque encobrira a sua face.

[NOTE]
====
. Ou “prostituta”. Gr.: pór·nen. Veja 1Co 6:15 n.
====

[[v1-38-16]]

^<<v1-38-16,16>>^ Desviou-se assim para ela à beira da estrada e disse: “Permite-me, por favor, ter relações contigo.” Pois não sabia que era sua nora. No entanto, ela disse: “O que me darás para ter relações comigo?”

[[v1-38-17]]

^<<v1-38-17,17>>^ A isso ele disse: “Eu mesmo enviarei um cabritinho do rebanho.” Mas ela disse: “Dar-me-ás uma garantia até o enviares?”

[[v1-38-18]]

^<<v1-38-18,18>>^ E ele continuou: “Que garantia te darei?” ao que ela disse: “Teu anel de chancela, e teu cordão, e a vara que tens na mão.” Entregou-lhos então e teve relações com ela, de modo que ela ficou grávida por ele.

[[v1-38-19]]

^<<v1-38-19,19>>^ Depois ela se levantou e foi embora, e removeu de si o xale e vestiu-se das roupas de sua viuvez.

[[v1-38-20]]

^<<v1-38-20,20>>^ E Judá passou a enviar o cabritinho pela mão de seu companheiro, o adulamita, a fim de receber a garantia de volta da mão da mulher, mas ele não a encontrou.

[[v1-38-21]]

^<<v1-38-21,21>>^ E indagava dos homens de seu lugar, dizendo: “Onde está aquela prostituta de templo, em Enaim, à beira da estrada?” Mas eles diziam: “Nunca houve neste lugar prostituta de templo.”

[[v1-38-22]]

^<<v1-38-22,22>>^ Por fim, voltou a Judá e disse: “Não a achei, e, além disso, os homens do lugar disseram: ‘Nunca houve neste lugar prostituta de templo.’”

[[v1-38-23]]

^<<v1-38-23,23>>^ De modo que Judá disse: “Que ela os tome para si, para que não venhamos a cair no desprezo. De qualquer modo, enviei este cabritinho, mas tu — tu não a achaste.”

[[v1-38-24]]

^<<v1-38-24,24>>^ No entanto, cerca de três meses depois, aconteceu que se informou a Judá: “Tamar, tua nora, fez-se de meretriz, e eis que está também grávida de seu meretrício.”^&#42;1^ Judá disse então: “Trazei-a para fora e seja queimada.”

[NOTE]
====
. Ou “fornicação”.
====

[[v1-38-25]]

^<<v1-38-25,25>>^ Quando estava sendo trazida para fora, ela mesma enviou [recado] ao seu sogro, dizendo: “Estou grávida do homem a quem pertencem estes.” E ela acrescentou: “Examina, por favor, a quem pertencem estes: o anel de chancela, e o cordão,^&#42;1^ e a vara.”

[NOTE]
====
. “Cordão”, TOLXXSyVg; M: “cordões”.
====

[[v1-38-26]]

^<<v1-38-26,26>>^ Judá examinou-os então e disse: “Ela é mais justa do que eu, visto que não a dei a Selá, meu filho.” E nunca mais teve relações com ela, depois disso.

[[v1-38-27]]

^<<v1-38-27,27>>^ Ora, sucedeu então, no tempo de ela dar à luz, que havia gêmeos no seu ventre.

[[v1-38-28]]

^<<v1-38-28,28>>^ Outrossim, resultou, quando ela dava à luz, que um estendeu a mão e a parteira tomou imediatamente um pedaço de escarlate e lho atou à mão, dizendo: “Este saiu primeiro.”

[[v1-38-29]]

^<<v1-38-29,29>>^ Finalmente, sucedeu que, assim que ele retirou a mão, ora, eis que saiu seu irmão, de modo que ela exclamou: “Que queres dizer com isso, produzires para ti uma ruptura perineal?” Por isso foi chamado pelo nome de Peres.^&#42;1^

[NOTE]
====
. Significando “Ruptura Perineal”.
====

[[v1-38-30]]

^<<v1-38-30,30>>^ E depois saiu seu irmão, que tinha sobre a mão o pedaço de escarlate, e ele veio a ser chamado pelo nome de Zerá.^&#42;1^

[NOTE]
====
. Significando “Resplendor; Ascensão”.
====

'''

xref:001-genesis/001-genesis-037.adoc#v1-37-0[&#60; Capítulo Anterior] | <<v1-38-0,Topo>> | xref:001-genesis/001-genesis-039.adoc#v1-39-0[Próximo Capítulo &#62;]