include::./index.adoc[]

[[v1-6-0]]
=== Gênesis, 6
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v1-6-1]]

^<<v1-6-1,1>>^ Ora, sucedeu que, quando os homens principiaram a aumentar em número na superfície do solo e lhes nasceram filhas,

[[v1-6-2]]

^<<v1-6-2,2>>^ então os filhos^&#42;1^ do [verdadeiro] Deus começaram a notar as filhas dos homens, que elas eram bem-parecidas; e foram tomar para si esposas, a saber, todas as que escolheram.

[NOTE]
====
. “Anjos”, LXXA.
====

[[v1-6-3]]

^<<v1-6-3,3>>^ Depois disso, Jeová disse: “Meu espírito não há de agir por tempo indefinido para com o homem, porquanto ele^&#42;1^ é carne. Concordemente, seus dias hão de somar cento e vinte anos.”

[NOTE]
====
. “Ele”, referindo-se ao “homem”, não a “meu espírito”.
====

[[v1-6-4]]

^<<v1-6-4,4>>^ Naqueles dias veio a haver os nefilins^&#42;1^ na terra, e também depois, quando os filhos do [verdadeiro] Deus continuaram a ter relações com as filhas dos homens e elas lhes deram filhos; eles eram os poderosos^&#42;2^ da antiguidade, os homens de fama.^&#42;3^

[NOTE]
====
. Ou “Os Derrubadores”. Hebr.: han·Nefi·lím, “os que fazem outros cair”.
. “Os poderosos.” Hebr.: hag·gib·bo·rím.
. Lit.: “nome”.
====

[[v1-6-5]]

^<<v1-6-5,5>>^ Por conseguinte, Jeová viu que a maldade do homem era abundante na terra e que toda inclinação dos pensamentos do seu coração era só má, todo o tempo.^&#42;1^

[NOTE]
====
. Lit.: “dia”.
====

[[v1-6-6]]

^<<v1-6-6,6>>^ E Jeová deplorou ter feito os homens na terra e sentiu-se magoado no coração.

[[v1-6-7]]

^<<v1-6-7,7>>^ De modo que Jeová disse: “Vou obliterar da superfície do solo os homens que criei, desde o homem até o animal doméstico, até o animal movente e até a criatura voadora dos céus, porque deveras deploro tê-los feito.”

[[v1-6-8]]

^<<v1-6-8,8>>^ Mas Noé achou favor aos olhos de Jeová.

[[v1-6-9]]

^<<v1-6-9,9>>^ Esta é a história de Noé.
Noé era homem justo. Mostrou-se sem defeito entre os seus contemporâneos.^&#42;1^ Noé andou com o [verdadeiro] Deus.

[NOTE]
====
. “Entre os seus contemporâneos.” Lit.: “entre as suas gerações”. Hebr.: bedho·ro·tháv.
====

[[v1-6-10]]

^<<v1-6-10,10>>^ Com o tempo, Noé tornou-se pai de três filhos: Sem, Cã e Jafé.

[[v1-6-11]]

^<<v1-6-11,11>>^ E a terra veio a estar arruinada à vista do [verdadeiro] Deus, e a terra ficou cheia de violência.

[[v1-6-12]]

^<<v1-6-12,12>>^ Deus viu, pois, a terra e eis que estava arruinada, porque toda a carne havia arruinado seu caminho na terra.

[[v1-6-13]]

^<<v1-6-13,13>>^ Depois, Deus disse a Noé: “Chegou o fim de toda a carne diante de mim, porque a terra está cheia de violência por causa deles; e eis que os arruíno juntamente com a terra.

[[v1-6-14]]

^<<v1-6-14,14>>^ Faze para ti uma arca^&#42;1^ da madeira duma árvore resinosa.^&#42;2^ Farás compartimentos^&#42;3^ na arca e terás de cobri-la com alcatrão por dentro e por fora.

[NOTE]
====
. Lit.: “uma caixa”. Hebr.: te·váth. Veja Êx 2:3, 5.
. Lit.: “árvores de gófer”, de madeira resinosa, possivelmente o cipreste.
. Ou “celas; câmaras; gabinetes”.
====

[[v1-6-15]]

^<<v1-6-15,15>>^ E é assim que a farás: trezentos côvados^&#42;1^ [será] o comprimento da arca, cinqüenta côvados a sua largura e trinta côvados a sua altura.

[NOTE]
====
. Um côvado era equivalente a 44,5 cm.
====

[[v1-6-16]]

^<<v1-6-16,16>>^ Farás um tsoar [teto; ou: janela]^&#42;1^ para a arca e a acabarás até um côvado para cima,^&#42;2^ e porás a entrada da arca no lado dela; far-lhe-ás um [pavimento] inferior, um segundo e um terceiro.

[NOTE]
====
. Ou “abertura para iluminação”. Hebr.: tsó·har.
. Lit.: “de cima”.
====

[[v1-6-17]]

^<<v1-6-17,17>>^ “E quanto a mim, eis que estou trazendo o dilúvio^&#42;1^ de águas sobre a terra, para arruinar debaixo dos céus toda a carne em que a força da vida está ativa.^&#42;2^ Tudo o que há na terra expirará.

[NOTE]
====
. Ou “o oceano celeste”. Hebr.: ham·mab·búl; lat.: di·lú·vi·i (raiz de “diluviano”). Veja 7:6 n.
. Lit.: “em que a força ativa (espírito) da vida [está]”. Hebr.: ’asher-bóh rú·ahh hhai·yím. Aqui, rú·ahh significa “força ativa; espírito”. Veja 1:2 n.: “ativa”.
====

[[v1-6-18]]

^<<v1-6-18,18>>^ E deveras estabeleço contigo meu pacto; e terás de entrar na arca, tu e teus filhos, e tua esposa, e as esposas de teus filhos contigo.

[[v1-6-19]]

^<<v1-6-19,19>>^ E de toda criatura vivente, de toda sorte de carne, levarás duas de cada uma para dentro da arca, a fim de as preservares vivas contigo. Serão macho e fêmea.

[[v1-6-20]]

^<<v1-6-20,20>>^ Das criaturas voadoras segundo as suas espécies e dos animais domésticos segundo as suas espécies, de todos os animais moventes do solo, segundo as suas espécies,^&#42;1^ dois de cada um virão a ti lá dentro para os preservares vivos.

[NOTE]
====
. Lit.: “segundo a sua espécie”. Hebr.: lemi·né·hu. Veja 1:11 n.
====

[[v1-6-21]]

^<<v1-6-21,21>>^ E quanto a ti, toma para ti toda sorte de alimento que se come; e tens de ajuntá-lo a ti e terá de servir de alimento para ti e para eles.”

[[v1-6-22]]

^<<v1-6-22,22>>^ E Noé passou a fazer segundo tudo o que Deus lhe mandara. Fez exatamente assim.

'''

xref:001-genesis/001-genesis-005.adoc#v1-5-0[&#60; Capítulo Anterior] | <<v1-6-0,Topo>> | xref:001-genesis/001-genesis-007.adoc#v1-7-0[Próximo Capítulo &#62;]