include::./index.adoc[]

[[v1-29-0]]
=== Gênesis, 29
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v1-29-1]]

^<<v1-29-1,1>>^ Depois, Jacó pôs os seus pés em movimento e continuou viagem para a terra dos orientais.^&#42;1^

[NOTE]
====
. Lit.: “para a terra dos filhos do Oriente”.
====

[[v1-29-2]]

^<<v1-29-2,2>>^ Olhou então e eis que havia um poço no campo, e eis que havia três greis de ovelhas^&#42;1^ deitadas junto dele, porque era daquele poço que se costumava dar de beber às greis; e havia uma grande pedra sobre a boca do poço.

[NOTE]
====
. Ou “gado miúdo”, inclusive caprídeos.
====

[[v1-29-3]]

^<<v1-29-3,3>>^ Quando todas as greis haviam sido ajuntadas ali, rolavam a pedra de cima da boca do poço e davam de beber aos rebanhos, retornando depois a pedra ao seu lugar sobre a boca do poço.

[[v1-29-4]]

^<<v1-29-4,4>>^ Jacó disse-lhes então: “Meus irmãos, donde sois?” ao que disseram: “Somos de Harã.”

[[v1-29-5]]

^<<v1-29-5,5>>^ Disse-lhes então: “Conheceis a Labão, neto de Naor?” ao que disseram: “Conhecemos.”

[[v1-29-6]]

^<<v1-29-6,6>>^ Disse-lhes então: “Ele está bem?”^&#42;1^ Disseram, por sua vez: “Está bem.^&#42;2^ E ali vem Raquel, sua filha, com as ovelhas!”

[NOTE]
====
. Lit.: “[Há] paz para ele?” Hebr.: hasha·lóhm loh?
. Lit.: “E disseram: ‘Paz!’” Hebr.: wai·yo’·merú sha·lóhm.
====

[[v1-29-7]]

^<<v1-29-7,7>>^ E ele prosseguiu, dizendo: “Ora, ainda é pleno dia.^&#42;1^ Não é hora de se recolherem as manadas. Dai de beber às ovelhas, depois ide apascentá-las.”

[NOTE]
====
. Ou: “Ora, ainda sobra muito do dia.”
====

[[v1-29-8]]

^<<v1-29-8,8>>^ A isso disseram: “Não se nos permite fazer isso até que todas as greis estejam recolhidas e eles realmente rolarem a pedra de cima da boca do poço. Então é que temos de dar de beber às ovelhas.”

[[v1-29-9]]

^<<v1-29-9,9>>^ Enquanto ainda falava com eles, veio Raquel com as ovelhas que pertenciam a seu pai, pois era pastora.

[[v1-29-10]]

^<<v1-29-10,10>>^ E sucedeu que, quando Jacó viu Raquel, filha de Labão, irmão de sua mãe, e as ovelhas de Labão, irmão de sua mãe, Jacó chegou-se imediatamente e rolou a pedra de cima da boca do poço e deu de beber às ovelhas de Labão, irmão de sua mãe.

[[v1-29-11]]

^<<v1-29-11,11>>^ Jacó beijou então Raquel, e levantou a sua voz e irrompeu em pranto.

[[v1-29-12]]

^<<v1-29-12,12>>^ E Jacó começou a contar a Raquel que era irmão^&#42;1^ de seu pai e que era filho de Rebeca. E ela foi correndo e o contou a seu pai.

[NOTE]
====
. “Irmão”, mas realmente sobrinho.
====

[[v1-29-13]]

^<<v1-29-13,13>>^ Ora, sucedeu que, assim que Labão ouviu a notícia a respeito de Jacó, filho de sua irmã, saiu correndo ao encontro dele. Abraçou-o então e beijou-o, e trouxe-o para dentro da sua casa. E ele começou a relatar a Labão todas estas coisas.

[[v1-29-14]]

^<<v1-29-14,14>>^ Labão disse-lhe depois: “Tu és deveras meu osso e minha carne.” Morou assim com ele um mês inteiro.^&#42;1^

[NOTE]
====
. Lit.: “um mês de dias”.
====

[[v1-29-15]]

^<<v1-29-15,15>>^ Depois, Labão disse a Jacó: “És meu irmão e tens de servir-me de graça? Declara-me: Qual há de ser o teu salário?”

[[v1-29-16]]

^<<v1-29-16,16>>^ Aconteceu que Labão tinha duas filhas. O nome da mais velha era Léia, e o nome da mais moça, Raquel.

[[v1-29-17]]

^<<v1-29-17,17>>^ Mas os olhos de Léia não tinham brilho,^&#42;1^ ao passo que Raquel se tinha tornado bela de figura e bela de semblante.

[NOTE]
====
. Ou “eram embaciados (fracos)”.
====

[[v1-29-18]]

^<<v1-29-18,18>>^ E Jacó amava Raquel. De modo que ele disse: “Estou disposto a servir-te sete anos por Raquel, tua filha mais moça.”

[[v1-29-19]]

^<<v1-29-19,19>>^ A isso Labão disse: “É melhor para mim dá-la a ti do que dá-la a outro homem. Fica morando comigo.”

[[v1-29-20]]

^<<v1-29-20,20>>^ E Jacó passou a servir sete anos por Raquel, mas eles se mostraram aos seus olhos como apenas alguns dias, por causa do seu amor por ela.

[[v1-29-21]]

^<<v1-29-21,21>>^ Jacó disse então a Labão: “Entrega-me a minha esposa, porque terminaram^&#42;1^ os meus dias, e tenha eu relações com ela.”

[NOTE]
====
. Ou “se cumpriram”.
====

[[v1-29-22]]

^<<v1-29-22,22>>^ Em vista disso, Labão ajuntou todos os homens do lugar e deu um banquete.

[[v1-29-23]]

^<<v1-29-23,23>>^ Deu-se, porém, que durante a noitinha recorreu a tomar Léia, sua filha, e a trazê-la a ele, para que tivesse relações com ela.

[[v1-29-24]]

^<<v1-29-24,24>>^ Além disso, Labão deu a ela Zilpa, sua serva, sim a Léia, sua filha, como serva.

[[v1-29-25]]

^<<v1-29-25,25>>^ Ora, sucedeu que, de manhã, eis que era Léia! Por conseguinte, ele disse a Labão: “Que é isso que me fizeste? Não foi por Raquel que te servi? Assim, por que me lograste?”

[[v1-29-26]]

^<<v1-29-26,26>>^ Labão disse a isso: “Não é costumeiro fazer assim no nosso lugar, dar a mais jovem antes da primogênita.

[[v1-29-27]]

^<<v1-29-27,27>>^ Celebra plenamente^&#42;1^ a semana desta mulher.^&#42;2^ Depois se há de dar a ti também esta outra mulher,^&#42;3^ pelo serviço que podes prestar-me por mais sete anos.”

[NOTE]
====
. Ou: “Cumpre.”
. Isto é, Léia.
. Isto é, Raquel.
====

[[v1-29-28]]

^<<v1-29-28,28>>^ Concordemente, Jacó fez assim e celebrou plenamente a semana desta mulher, após o que lhe deu Raquel, sua filha, por esposa.

[[v1-29-29]]

^<<v1-29-29,29>>^ Além disso, Labão deu Bila, sua serva, a Raquel, sua filha, como serva dela.

[[v1-29-30]]

^<<v1-29-30,30>>^ Daí teve também relações com Raquel e expressou também mais amor por Raquel do que por Léia, e foi servir-lhe mais sete anos.

[[v1-29-31]]

^<<v1-29-31,31>>^ Quando Jeová chegou a ver que Léia era odiada, abriu-lhe a madre, mas Raquel era estéril.

[[v1-29-32]]

^<<v1-29-32,32>>^ E Léia ficou grávida e deu à luz um filho, e então chamou-o pelo nome de Rubem,^&#42;1^ pois disse: “É porque Jeová tem olhado para a minha miséria, sendo que agora meu esposo começará a amar-me.”

[NOTE]
====
. Significando “Eis um Filho!” Hebr.: Re’u·vén.
====

[[v1-29-33]]

^<<v1-29-33,33>>^ E ela ficou novamente grávida e deu à luz um filho, e disse então: “É porque Jeová tem escutado, sendo que eu era odiada, e assim me deu também este.” Por isso o chamou pelo nome de Simeão.^&#42;1^

[NOTE]
====
. Significando “Ouvir”, isto é, com aceitação. Hebr.: Shim·‛óhn.
====

[[v1-29-34]]

^<<v1-29-34,34>>^ E mais uma vez ficou grávida e deu à luz um filho, e disse então: “Agora, esta vez se ajuntará a mim o meu esposo, porque lhe dei à luz três filhos.” Ele foi por isso chamado pelo nome de Levi.^&#42;1^

[NOTE]
====
. Significando “Adesão; Ligado”. Hebr.: Le·wí.
====

[[v1-29-35]]

^<<v1-29-35,35>>^ E mais uma vez ficou grávida e deu à luz um filho, e disse então: “Esta vez elogiarei a Jeová.” Por isso o chamou pelo nome de Judá.^&#42;1^ Depois parou de dar à luz.

[NOTE]
====
. Significando “Louvado; [Objeto de] Louvor”. Hebr.: Yehu·dháh.
====

'''

xref:001-genesis/001-genesis-028.adoc#v1-28-0[&#60; Capítulo Anterior] | <<v1-29-0,Topo>> | xref:001-genesis/001-genesis-030.adoc#v1-30-0[Próximo Capítulo &#62;]