include::./index.adoc[]

[[v1-32-0]]
=== Gênesis, 32
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v1-32-1]]

^<<v1-32-1,1>>^ E, quanto a Jacó, seguiu caminho, e os anjos^&#42;1^ de Deus encontraram-se então com ele.

[NOTE]
====
. Ou “mensageiros”, como nos vv. 3 e 6.
====

[[v1-32-2]]

^<<v1-32-2,2>>^ Jacó disse imediatamente, ao vê-los: “Este é o acampamento de Deus!” Chamou por isso aquele lugar pelo nome de Maanaim.^&#42;1^

[NOTE]
====
. Significando “Dois Acampamentos”.
====

[[v1-32-3]]

^<<v1-32-3,3>>^ Jacó enviou então mensageiros adiante de si a Esaú, seu irmão, à terra de Seir, o campo de Edom,

[[v1-32-4]]

^<<v1-32-4,4>>^ e ordenou-lhes, dizendo: “Isto é o que direis a meu senhor, a Esaú: ‘Assim disse o teu servo Jacó: “Residi com Labão como forasteiro e fiquei por muito tempo, até agora.

[[v1-32-5]]

^<<v1-32-5,5>>^ E vim a ter touros e jumentos, ovelhas, e servos e servas, e eu gostaria de mandar informar meu senhor, a fim de achar favor aos teus olhos.”’”

[[v1-32-6]]

^<<v1-32-6,6>>^ Passado tempo, os mensageiros voltaram a Jacó, dizendo: “Fomos ter com teu irmão Esaú, e ele está também a caminho para vir ao teu encontro, e com ele quatrocentos homens.”

[[v1-32-7]]

^<<v1-32-7,7>>^ E Jacó ficou com muito medo e estava aflito. De modo que dividiu o povo que estava com ele, e os rebanhos, e o gado vacum, e os camelos, em dois acampamentos,

[[v1-32-8]]

^<<v1-32-8,8>>^ e disse: “Se Esaú chegar a um acampamento e o assaltar, então resta certamente um acampamento para se escapar.”

[[v1-32-9]]

^<<v1-32-9,9>>^ Jacó disse depois: “Ó Deus de meu pai Abraão e Deus de meu pai Isaque, ó Jeová, tu que me dizes: ‘Volta à tua terra e à tua parentela, e eu te hei de tratar bem’,

[[v1-32-10]]

^<<v1-32-10,10>>^ sou indigno de todas as benevolências e de toda a fidelidade^&#42;1^ de que usaste para com o teu servo, pois atravessei este Jordão apenas com o meu bastão e agora me tornei dois acampamentos.

[NOTE]
====
. Ou “a verdade”. Hebr.: ha·’eméth.
====

[[v1-32-11]]

^<<v1-32-11,11>>^ Livra-me, eu te peço, da mão de meu irmão, da mão de Esaú, porque estou com medo dele, de que venha e certamente me assalte, a mãe junto com os filhos.

[[v1-32-12]]

^<<v1-32-12,12>>^ E tu, tu disseste: ‘Sem dúvida, tratar-te-ei bem e hei de fazer tua descendência^&#42;1^ como os grãos de areia do mar, que não podem ser contados por causa da [sua] multidão.’”

[NOTE]
====
. Ou “prole; posteridade”.
====

[[v1-32-13]]

^<<v1-32-13,13>>^ E ficou pousando ali naquela noite. E daquilo que lhe veio à mão, ele passou a tomar um presente para Esaú, seu irmão:

[[v1-32-14]]

^<<v1-32-14,14>>^ duzentas cabras e vinte cabritos, duzentas ovelhas e vinte carneiros,

[[v1-32-15]]

^<<v1-32-15,15>>^ trinta camelas que amamentavam e as suas crias, quarenta vacas e dez novilhos, vinte jumentas e dez jumentos adultos.

[[v1-32-16]]

^<<v1-32-16,16>>^ Então entregou aos seus servos uma grei após outra, separadas, e disse repetidamente aos seus servos: “Atravessai na minha frente, e deveis deixar espaço entre grei e grei.”

[[v1-32-17]]

^<<v1-32-17,17>>^ Ademais, ordenou ao primeiro, dizendo: “Caso Esaú, meu irmão, te encontre e te pergunte, dizendo: ‘A quem pertences, e para onde vais, e a quem pertencem estes adiante de ti?’

[[v1-32-18]]

^<<v1-32-18,18>>^ então terás de dizer: ‘Ao teu servo, a Jacó. É um presente, enviado a meu senhor, a Esaú, e eis que ele mesmo vem também atrás de nós!’”

[[v1-32-19]]

^<<v1-32-19,19>>^ E passou a ordenar também ao segundo, também ao terceiro, também aos que seguiam as greis, dizendo: “Deveis falar a Esaú segundo esta palavra, quando o encontrardes.

[[v1-32-20]]

^<<v1-32-20,20>>^ E tereis de dizer também: ‘Eis o teu servo Jacó atrás de nós.’” Pois dizia para si mesmo: “Talvez eu possa aplacá-lo com o presente que vai na minha frente, e depois verei a sua face. Talvez dê uma acolhida benévola.”

[[v1-32-21]]

^<<v1-32-21,21>>^ De modo que o presente atravessou na frente dele, mas ele mesmo pousou aquela noite no acampamento.

[[v1-32-22]]

^<<v1-32-22,22>>^ Mais tarde, durante aquela noite, levantou-se e tomou as suas duas esposas, e suas duas servas, e seus onze filhos moços, e atravessou o vau de Jaboque.

[[v1-32-23]]

^<<v1-32-23,23>>^ Assim, tomou-os e levou-os através do vale da torrente,^&#42;1^ e fez atravessar o que tinha.

[NOTE]
====
. Ou “o uádi; o arroio, a corrente [o uádi com curso de água]”.
====

[[v1-32-24]]

^<<v1-32-24,24>>^ Finalmente, Jacó ficou sozinho. Um homem começou então a engalfinhar-se com ele até subir a alva.

[[v1-32-25]]

^<<v1-32-25,25>>^ Quando viu que não tinha prevalecido contra ele, então lhe tocou na concavidade da articulação da coxa;^&#42;1^ e a concavidade da articulação da coxa de Jacó deslocou-se enquanto se engalfinhava com ele.

[NOTE]
====
. Ou “tocou na concavidade da sua coxa”.
====

[[v1-32-26]]

^<<v1-32-26,26>>^ Depois disse: “Deixa-me ir,^&#42;1^ pois já subiu a alva.” A isso ele disse: “Não te deixo ir, a menos que primeiro me abençoes.”

[NOTE]
====
. Lit.: “Manda-me embora.”
====

[[v1-32-27]]

^<<v1-32-27,27>>^ Disse-lhe, pois: “Qual é teu nome?” a que ele disse: “Jacó.”

[[v1-32-28]]

^<<v1-32-28,28>>^ Disse então: “Não serás mais chamado pelo nome de Jacó, mas, sim, Israel,^&#42;1^ pois contendeste^&#42;2^ com Deus e com homens, de modo que por fim prevaleceste.”

[NOTE]
====
. Significando “Deus Contende; Contendedor (Perseverador) com Deus”. Hebr.: Yis·ra·’él.
. Ou “persististe; esforçaste-te; perseveraste”, segundo BDB, p. 975.
====

[[v1-32-29]]

^<<v1-32-29,29>>^ Jacó, por sua vez, indagou e disse: “Declara-me o teu nome, por favor.” No entanto, ele disse: “Por que indagas o meu nome?” Abençoou-o então ali.

[[v1-32-30]]

^<<v1-32-30,30>>^ Jacó chamou por isso o lugar pelo nome de Peniel,^&#42;1^ porque, segundo ele: “Tenho visto a Deus face a face e ainda assim foi livrada a minha alma.”

[NOTE]
====
. Significando “Face de Deus”. Hebr.: Peni·’él.
====

[[v1-32-31]]

^<<v1-32-31,31>>^ E o sol começou a raiar sobre ele assim que tinha passado por Penuel, porém, manquejava por causa da sua coxa.

[[v1-32-32]]

^<<v1-32-32,32>>^ É por isso que os filhos de Israel não costumam comer o tendão do nervo da coxa,^&#42;1^ que está na concavidade da articulação da coxa, até o dia de hoje, porque ele tocou na concavidade da articulação da coxa de Jacó, no tendão do nervo da coxa.

[NOTE]
====
. Ou “veia da coxa”.
====

'''

xref:001-genesis/001-genesis-031.adoc#v1-31-0[&#60; Capítulo Anterior] | <<v1-32-0,Topo>> | xref:001-genesis/001-genesis-033.adoc#v1-33-0[Próximo Capítulo &#62;]