include::./index.adoc[]

[[v1-20-0]]
=== Gênesis, 20
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v1-20-1]]

^<<v1-20-1,1>>^ Abraão mudou então o acampamento dali para a terra do Negebe e passou a morar entre Cades e Sur, e foi residir como forasteiro em Gerar.

[[v1-20-2]]

^<<v1-20-2,2>>^ E Abraão repetiu com respeito a Sara, sua esposa: “Ela é minha irmã.” Em vista disso, Abimeleque,^&#42;1^ rei de Gerar, mandou tomar Sara.

[NOTE]
====
. Provavelmente um título oficial.
====

[[v1-20-3]]

^<<v1-20-3,3>>^ Posteriormente, Deus veio a Abimeleque num sonho, durante a noite, e disse-lhe: “Eis que a bem dizer já estás morto, por causa da mulher que tomaste, visto que ela pertence a outro dono como sua esposa.”

[[v1-20-4]]

^<<v1-20-4,4>>^ No entanto, Abimeleque não se havia chegado a ela. Disse, portanto: “Jeová,^&#42;1^ matarás uma nação que é realmente justa?

[NOTE]
====
. Uma das 134 mudanças de YHWH para ’Adho·naí feitas pelos escribas. Veja Ap. 1B.
====

[[v1-20-5]]

^<<v1-20-5,5>>^ Não me disse ele: ‘Ela é minha irmã’? e ela — não me disse também: ‘Ele é meu irmão’? Fiz isso na honestidade do meu coração e com a inocência das minhas mãos.”

[[v1-20-6]]

^<<v1-20-6,6>>^ O [verdadeiro] Deus disse-lhe então no sonho: “Eu também sabia que fizeste isso na honestidade do teu coração, e também te refreei de pecar contra mim. É por isso que não te permiti tocar nela.

[[v1-20-7]]

^<<v1-20-7,7>>^ Mas agora, restitui a esposa do homem, pois ele é profeta^&#42;1^ e fará intercessão por ti. Portanto, continua vivendo. Mas, se não a restituíres, sabe que positivamente morrerás, tu e todos os teus.”

[NOTE]
====
. “Profeta.” Hebr.: na·ví’; esta é a primeira ocorrência desta palavra.
====

[[v1-20-8]]

^<<v1-20-8,8>>^ Abimeleque levantou-se, pois, de manhã cedo e passou a chamar todos os seus servos e a falar de todas estas coisas aos seus ouvidos. E os homens ficaram com muito medo.

[[v1-20-9]]

^<<v1-20-9,9>>^ Abimeleque chamou então a Abraão e disse-lhe: “Que nos fizeste e que pecado cometi contra ti, de trazeres um grande pecado sobre mim e meu reino? Fizeste para comigo atos que não se deviam fazer.”

[[v1-20-10]]

^<<v1-20-10,10>>^ Abimeleque prosseguiu, dizendo a Abraão: “Que visaste, fazendo esta coisa?”

[[v1-20-11]]

^<<v1-20-11,11>>^ Abraão disse então: “Foi porque eu disse a mim mesmo: ‘Sem dúvida, não há temor de Deus^&#42;1^ neste lugar, e certamente me matarão por causa da minha esposa.’

[NOTE]
====
. Hebr.: ’Elo·hím, pl., para denotar a excelência do Deus de Abraão.
====

[[v1-20-12]]

^<<v1-20-12,12>>^ E, além disso, ela é realmente minha irmã, filha de meu pai, apenas não é filha de minha mãe; e ela se tornou minha esposa.

[[v1-20-13]]

^<<v1-20-13,13>>^ E sucedeu que, quando Deus me fez [sair] da casa de meu pai [para] andar vagueando,^&#42;1^ então eu disse a ela: ‘Esta é a tua benevolência^&#42;2^ de que podes usar para comigo: Em todo lugar a que chegarmos, dize a meu respeito: “Ele é meu irmão.”’”

[NOTE]
====
. “Fez . . . andar vagueando”, hebr. pl., para corresponder a ’Elo·hím, “Deus”; Sam: “fez vaguear”.
. Ou “o teu amor leal”. Hebr.: hhas·dékh.
====

[[v1-20-14]]

^<<v1-20-14,14>>^ A seguir, Abimeleque tomou ovelhas e gado vacum, e servos, e servas, e deu-os a Abraão e restituiu-lhe Sara, sua esposa.

[[v1-20-15]]

^<<v1-20-15,15>>^ Ademais, Abimeleque disse: “Eis que a minha terra está à tua disposição.^&#42;1^ Mora onde parecer bem aos teus olhos.”

[NOTE]
====
. Ou “aberta para ti”. Lit.: “diante de ti”.
====

[[v1-20-16]]

^<<v1-20-16,16>>^ E a Sara ele disse: “Eis que deveras dou mil [peças] de prata^&#42;1^ ao teu irmão. Eis que é para ti uma venda para os olhos^&#42;2^ de todos os que estão contigo, e perante todos, e estás livre de vitupério.”^&#42;3^

[NOTE]
====
. “Moedas de prata”, isto é, siclos de prata. Hebr.: ké·sef.
. “Venda para os olhos.” Expressão hebr. idiomática significando uma declaração legal de reputação feminina imaculada, livrando-a de acusação aos olhos de outros.
. Ou “‘perante todos’. E ela [Sara] foi posta na luz correta.”
====

[[v1-20-17]]

^<<v1-20-17,17>>^ E Abraão começou a fazer intercessão ao [verdadeiro] Deus; e Deus^&#42;1^ passou a curar Abimeleque e sua esposa, e suas escravas, e elas começaram a dar à luz filhos.

[NOTE]
====
. Hebr.: ’Elo·hím, sem o artigo definido ha.
====

[[v1-20-18]]

^<<v1-20-18,18>>^ Pois Jeová cerrara totalmente cada madre na casa de Abimeleque, por causa de Sara, esposa de Abraão.

'''

xref:001-genesis/001-genesis-019.adoc#v1-19-0[&#60; Capítulo Anterior] | <<v1-20-0,Topo>> | xref:001-genesis/001-genesis-021.adoc#v1-21-0[Próximo Capítulo &#62;]