include::./index.adoc[]

[[v1-33-0]]
=== Gênesis, 33
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v1-33-1]]

^<<v1-33-1,1>>^ Passado tempo, Jacó levantou seus olhos e olhou, e eis que vinha Esaú, e com ele quatrocentos homens. Por conseguinte, repartiu os filhos a Léia, e a Raquel, e às duas servas,

[[v1-33-2]]

^<<v1-33-2,2>>^ e pôs as servas e seus filhos na frente, e Léia e seus filhos após eles, e Raquel e José na retaguarda deles.

[[v1-33-3]]

^<<v1-33-3,3>>^ E ele mesmo passou adiante deles e foi curvar-se por terra, sete vezes, até chegar perto de seu irmão.

[[v1-33-4]]

^<<v1-33-4,4>>^ E Esaú foi correndo ao encontro dele, e começou a abraçá-lo e a lançar-se ao pescoço dele, e a beijá-lo,^&#42;1^ e romperam em pranto.

[NOTE]
====
. “E a beijá-lo”, MSamLXXBagsterVg. No M, esta expressão foi assinalada com pontos extraordinários pelos soferins, talvez para indicar que os soferins achavam que essas palavras deveriam ser omitidas. As n. de BHK e BHS sugerem que provavelmente foram acrescentadas ao texto. Veja Ap. 2A.
====

[[v1-33-5]]

^<<v1-33-5,5>>^ Levantou então seus olhos e viu as mulheres e os filhos, e disse: “Quem são estes contigo?” ao que ele disse: “Os filhos com que Deus tem favorecido teu servo.”

[[v1-33-6]]

^<<v1-33-6,6>>^ Aproximaram-se então as servas, elas e seus filhos, e curvaram-se;

[[v1-33-7]]

^<<v1-33-7,7>>^ e Léia também se aproximou, e seus filhos, e curvaram-se, e depois se aproximou José e Raquel, e curvaram-se.

[[v1-33-8]]

^<<v1-33-8,8>>^ Ele disse então: “Que queres dizer com todo^&#42;1^ este acampamento de viajantes que encontrei?” A isso ele disse: “A fim de achar favor aos olhos de meu senhor.”

[NOTE]
====
. Lit.: “Quem para ti é todo?”
====

[[v1-33-9]]

^<<v1-33-9,9>>^ Esaú disse então: “Eu tenho muitíssimos, meu irmão. Continue teu o que é teu.”

[[v1-33-10]]

^<<v1-33-10,10>>^ No entanto, Jacó disse: “Não, por favor. Se agora tenho achado favor aos teus olhos, então tens de tomar meu presente da minha mão, pois, em harmonia com o seu objetivo, vi a tua face como se visse a face de Deus, visto que me recebeste com prazer.

[[v1-33-11]]

^<<v1-33-11,11>>^ Toma, por favor, a dádiva que te foi trazida, expressando minha bênção, porque Deus me favoreceu e porque tenho tudo.” E continuou a instar com ele, de modo que a tomou.

[[v1-33-12]]

^<<v1-33-12,12>>^ Mais tarde, ele disse: “Partamos e vamos, e deixa-me ir na tua frente.”

[[v1-33-13]]

^<<v1-33-13,13>>^ Mas ele lhe disse: “Meu senhor se apercebe de que os filhos são delicados, e que há ao meu cargo ovelhas e gado vacum que amamenta, e se os fizerem andar depressa demais por um só dia, então certamente morrerá o rebanho inteiro.

[[v1-33-14]]

^<<v1-33-14,14>>^ Por favor, passe o meu senhor adiante do seu servo, mas continue eu mesmo a viagem segundo a minha conveniência, no passo do gado que está diante de mim e no passo dos filhos, até eu chegar a meu senhor em Seir.”

[[v1-33-15]]

^<<v1-33-15,15>>^ Esaú disse então: “Por favor, deixa-me pôr à tua disposição alguns do povo que está comigo.” A isso ele disse: “Por que isso? Ache eu favor aos olhos de meu senhor.”

[[v1-33-16]]

^<<v1-33-16,16>>^ Assim, naquele dia, Esaú voltou pelo seu caminho a Seir.

[[v1-33-17]]

^<<v1-33-17,17>>^ E Jacó partiu para Sucote^&#42;1^ e passou a construir para si uma casa, e fez barracas para a sua manada. Foi por isso que chamou o lugar pelo nome de Sucote.

[NOTE]
====
. Significando “Barracas; Baias Cobertas”.
====

[[v1-33-18]]

^<<v1-33-18,18>>^ Com o tempo, Jacó veio são e salvo à cidade de Siquém, que está na terra de Canaã, ao vir de Padã-Arã; e ele armou o seu acampamento defronte da cidade.

[[v1-33-19]]

^<<v1-33-19,19>>^ Adquiriu então um pedaço do campo onde armara a sua tenda, da mão dos filhos de Hamor, pai de Siquém, por cem peças de dinheiro.^&#42;1^

[NOTE]
====
. Lit.: “cem qesi·táh”. Unidade monetária de valor desconhecido.
====

[[v1-33-20]]

^<<v1-33-20,20>>^ Depois erigiu ali um altar e chamou-o de Deus, o Deus de Israel.^&#42;1^

[NOTE]
====
. “Deus, o Deus de Israel.” Ou “Deus é o Deus de Israel”. Hebr.: ’El ’Elo·héh Yis·ra·’él.
====

'''

xref:001-genesis/001-genesis-032.adoc#v1-32-0[&#60; Capítulo Anterior] | <<v1-33-0,Topo>> | xref:001-genesis/001-genesis-034.adoc#v1-34-0[Próximo Capítulo &#62;]