include::./index.adoc[]

[[v1-45-0]]
=== Gênesis, 45
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v1-45-1]]

^<<v1-45-1,1>>^ Em vista disso, José não se pôde mais conter diante de todos os que se achavam de pé junto dele. Clamou, pois: “Retirem-se todos de mim!” E ninguém ficou com ele quando José se deu a conhecer a seus irmãos.

[[v1-45-2]]

^<<v1-45-2,2>>^ E ele começou a elevar a sua voz em choro, de modo que os egípcios chegaram a ouvi-lo e a casa de Faraó chegou a ouvi-lo.

[[v1-45-3]]

^<<v1-45-3,3>>^ Finalmente, José disse aos seus irmãos: “Eu sou José. Ainda vive meu pai?” Mas os seus irmãos não lhe puderam responder nada, pois estavam perturbados por causa dele.

[[v1-45-4]]

^<<v1-45-4,4>>^ José disse então a seus irmãos: “Aproximai-vos, por favor.” Então se aproximaram dele.
Ele disse então: “Eu sou José, vosso irmão, que vendestes para o Egito.

[[v1-45-5]]

^<<v1-45-5,5>>^ Mas agora, não vos sintais magoados e não estejais irados com vós mesmos, por me terdes vendido para cá; porque foi para a preservação de vida que Deus me enviou na vossa frente.

[[v1-45-6]]

^<<v1-45-6,6>>^ Pois este é o segundo ano de fome no meio da terra, e ainda haverá cinco anos em que não haverá nem lavoura nem colheita.

[[v1-45-7]]

^<<v1-45-7,7>>^ Por conseguinte, Deus enviou-me na frente de vós, a fim de pôr para vós um restante^&#42;1^ na terra e para vos preservar vivos por meio dum grande escape.

[NOTE]
====
. Ou “sobreviventes; resto”. Hebr.: she’e·ríth.
====

[[v1-45-8]]

^<<v1-45-8,8>>^ Agora, pois, não fostes vós quem me enviastes para cá, mas foi o [verdadeiro] Deus, a fim de me designar pai para Faraó e senhor para toda a sua casa, e como aquele que domina sobre toda a terra do Egito.

[[v1-45-9]]

^<<v1-45-9,9>>^ “Subi depressa até meu pai, e tendes de dizer-lhe: ‘Assim disse teu filho José: “Deus me designou senhor para todo o Egito. Desce a mim. Não te demores.

[[v1-45-10]]

^<<v1-45-10,10>>^ E tens de morar na terra de Gósen e tens de continuar perto de mim, tu e teus filhos, e os filhos de teus filhos, e teus rebanhos, e tuas manadas, e tudo o que tens.

[[v1-45-11]]

^<<v1-45-11,11>>^ E vou suprir-te ali de alimento, pois haverá ainda cinco anos de fome, para que tu, e tua casa, e tudo o que tens, não venham a sofrer pobreza.”’

[[v1-45-12]]

^<<v1-45-12,12>>^ E eis que os vossos olhos e os olhos de meu irmão Benjamim estão vendo que é a minha boca que vos fala.

[[v1-45-13]]

^<<v1-45-13,13>>^ De modo que tendes de contar a meu pai toda a minha glória no Egito e tudo o que vistes; e tendes de apressar-vos e trazer meu pai cá para baixo.”

[[v1-45-14]]

^<<v1-45-14,14>>^ Lançou-se então ao pescoço de Benjamim, seu irmão, e entregou-se ao choro, e Benjamim chorava ao seu pescoço.

[[v1-45-15]]

^<<v1-45-15,15>>^ E ele passou a beijar a todos os seus irmãos e a chorar sobre eles, e depois seus irmãos falaram com ele.

[[v1-45-16]]

^<<v1-45-16,16>>^ E a nova foi ouvida na casa de Faraó, dizendo: “Vieram os irmãos de José!” E isso se mostrou bom aos olhos de Faraó e dos seus servos.

[[v1-45-17]]

^<<v1-45-17,17>>^ Por conseguinte, Faraó disse a José: “Dize a teus irmãos: ‘Fazei o seguinte: Carregai os vossos animais de carga e ide, entrai na terra de Canaã,

[[v1-45-18]]

^<<v1-45-18,18>>^ e tomai vosso pai e os da vossa casa, e vinde para cá, a mim, a fim de que eu vos dê o bom da terra do Egito; e comei a parte gorda do país.

[[v1-45-19]]

^<<v1-45-19,19>>^ E a ti mesmo se manda:^&#42;1^ “Fazei o seguinte: Tomai para vós carroças da terra do Egito, para os vossos pequeninos e para as vossas esposas, e tendes de colocar vosso pai numa delas e vir para cá.

[NOTE]
====
. “Ordena”, isto é, para dizer-lhes. LXX: “dá ordens”.
====

[[v1-45-20]]

^<<v1-45-20,20>>^ E não lastimem os vossos olhos o vosso equipamento, porque é vosso o bom de toda a terra do Egito.”’”

[[v1-45-21]]

^<<v1-45-21,21>>^ Em conseqüência, os filhos de Israel fizeram isso, e José deu-lhes carroças segundo as ordens de Faraó e deu-lhes provisões para o caminho.

[[v1-45-22]]

^<<v1-45-22,22>>^ A cada um deles deu mudas individuais de capas, mas a Benjamim deu trezentas moedas de prata e cinco mudas de capas.

[[v1-45-23]]

^<<v1-45-23,23>>^ E a seu pai enviou o seguinte: dez jumentos carregados das coisas boas do Egito e dez jumentas carregadas de cereais e de pão, e de sustento para seu pai, para o caminho.

[[v1-45-24]]

^<<v1-45-24,24>>^ Assim despachou os seus irmãos e eles partiram. Disse-lhes, no entanto: “Não fiqueis exasperados uns com os outros no caminho.”

[[v1-45-25]]

^<<v1-45-25,25>>^ E eles começaram a subir do Egito e chegaram por fim à terra de Canaã, a Jacó, seu pai.

[[v1-45-26]]

^<<v1-45-26,26>>^ Informaram-no então, dizendo: “José vive ainda, e é ele quem domina sobre toda a terra do Egito!” Mas o seu coração ficou entorpecido, porque não acreditava neles.

[[v1-45-27]]

^<<v1-45-27,27>>^ Quando prosseguiam falando com ele de todas as palavras que José lhes falara e ele chegou a ver as carroças que José enviara para transportá-lo, começou a reanimar-se o espírito de Jacó, seu pai.

[[v1-45-28]]

^<<v1-45-28,28>>^ Israel exclamou então: “Basta! José, meu filho, vive ainda! Ah! irei e o verei antes de eu morrer!”

'''

xref:001-genesis/001-genesis-044.adoc#v1-44-0[&#60; Capítulo Anterior] | <<v1-45-0,Topo>> | xref:001-genesis/001-genesis-046.adoc#v1-46-0[Próximo Capítulo &#62;]