include::./index.adoc[]

[[v1-43-0]]
=== Gênesis, 43
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v1-43-1]]

^<<v1-43-1,1>>^ E a fome era severa no país.

[[v1-43-2]]

^<<v1-43-2,2>>^ E sucedeu que, assim que acabaram de comer os cereais que trouxeram do Egito, seu pai passou a dizer-lhes: “Voltai, comprai-nos alguns mantimentos.”

[[v1-43-3]]

^<<v1-43-3,3>>^ Judá disse-lhe então: “O homem nos testificou definitivamente, dizendo: ‘Não mais deveis ver a minha face, a menos que vosso irmão esteja convosco.’

[[v1-43-4]]

^<<v1-43-4,4>>^ Se enviares conosco nosso irmão, estamos dispostos a descer e a comprar para ti mantimentos.

[[v1-43-5]]

^<<v1-43-5,5>>^ Mas, se não o enviares, não desceremos, porque o homem deveras nos disse: ‘Não mais deveis ver a minha face, a menos que vosso irmão esteja convosco.’”

[[v1-43-6]]

^<<v1-43-6,6>>^ E Israel exclamou: “Por que tivestes de fazer-me dano por contar ao homem que tínheis outro irmão?”

[[v1-43-7]]

^<<v1-43-7,7>>^ A isso disseram: “O homem indagou diretamente a respeito de nós e de nossa parentela, dizendo: ‘Vive ainda o vosso pai? Tendes outro irmão?’ e nós fomos contar-lhe segundo estes fatos. Como podíamos saber com certeza que diria: ‘Trazei vosso irmão para baixo’?”

[[v1-43-8]]

^<<v1-43-8,8>>^ Por fim, Judá disse a Israel, seu pai: “Envia o rapaz comigo, para que nos levantemos e vamos, e para que fiquemos vivos e não morramos, tanto nós, como tu e as nossas criancinhas.

[[v1-43-9]]

^<<v1-43-9,9>>^ Eu é que serei a fiança por ele. Da minha mão poderás demandar a penalidade por ele. Se eu falhar em trazê-lo e em apresentá-lo a ti, então terei pecado contra ti para sempre.^&#42;1^

[NOTE]
====
. Lit.: “todos os dias”.
====

[[v1-43-10]]

^<<v1-43-10,10>>^ Mas, se não nos tivéssemos demorado, já teríamos ido para lá e retornado estas duas vezes.”

[[v1-43-11]]

^<<v1-43-11,11>>^ Portanto, Israel, seu pai, disse-lhes: “Se este é então o caso, fazei o seguinte: Tomai nos vossos receptáculos os produtos mais excelentes do país e levai-os para baixo, ao homem, como presente: um pouco de bálsamo^&#42;1^ e um pouco de mel, ládano e casca resinosa, nozes de pistácia e amêndoas.

[NOTE]
====
. Isto é, de Gileade.
====

[[v1-43-12]]

^<<v1-43-12,12>>^ Tomai também o dobro do dinheiro^&#42;1^ na vossa mão; e o dinheiro que vos foi restituído na boca das vossas sacas levareis de volta na vossa mão. Talvez fosse engano.

[NOTE]
====
. Lit.: “prata”.
====

[[v1-43-13]]

^<<v1-43-13,13>>^ E tomai vosso irmão e levantai-vos, voltai ao homem.

[[v1-43-14]]

^<<v1-43-14,14>>^ E que [o] Deus Todo-poderoso^&#42;1^ vos dê misericórdia perante o homem, para que certamente vos livre o vosso outro irmão e Benjamim. Mas eu, caso eu tenha de ficar privado de filhos, certamente ficarei privado de filhos!”

[NOTE]
====
. “E . . . Deus Todo-poderoso.” Hebr.: we’Él Shad·daí. Nem ’El, “Deus”, nem Shad·daí, “Todo-poderoso”, tem o artigo definido.
====

[[v1-43-15]]

^<<v1-43-15,15>>^ Por conseguinte, os homens tomaram tal presente e tomaram o dobro do dinheiro na sua mão, e Benjamim. Levantaram-se então e foram descer ao Egito, e chegaram a estar de pé diante de José.

[[v1-43-16]]

^<<v1-43-16,16>>^ Quando José viu Benjamim com eles, disse imediatamente ao homem que estava sobre a sua casa: “Leva os homens para casa, e abate animais e faze preparativos, porque os homens hão de comer comigo ao meio-dia.”

[[v1-43-17]]

^<<v1-43-17,17>>^ O homem fez imediatamente assim como José lhe dissera. De modo que o homem levou os homens à casa de José.

[[v1-43-18]]

^<<v1-43-18,18>>^ Mas os homens ficaram com medo, porque tinham sido levados à casa de José, e começaram a dizer: “É por causa do dinheiro que voltou conosco nas nossas sacas, no início, que estamos sendo trazidos para cá, a fim de que caiam sobre nós e nos ataquem, e nos tomem como escravos, e também os nossos jumentos!”

[[v1-43-19]]

^<<v1-43-19,19>>^ Chegaram-se por isso ao homem que estava sobre a casa de José e falaram-lhe à entrada da casa,

[[v1-43-20]]

^<<v1-43-20,20>>^ e disseram: “Perdão, meu senhor! No início, realmente descemos para comprar mantimentos.

[[v1-43-21]]

^<<v1-43-21,21>>^ Mas o que se deu foi que, quando chegamos à pousada e começamos a abrir as nossas sacas, ora, eis que havia o dinheiro de cada um na boca da sua saca, nosso dinheiro no pleno peso. De modo que gostaríamos de restituí-lo com as nossas próprias mãos.

[[v1-43-22]]

^<<v1-43-22,22>>^ E trouxemos mais dinheiro para baixo, nas nossas mãos, para comprar mantimentos. Certamente não sabemos quem colocou o nosso dinheiro nas nossas sacas.”

[[v1-43-23]]

^<<v1-43-23,23>>^ Ele disse então: “Ficai tranqüilos. Não tenhais medo. Vosso Deus e o Deus de vosso pai deu-vos um tesouro nas vossas sacas. Vosso dinheiro veio primeiro a mim.” Depois lhes trouxe Simeão para fora.

[[v1-43-24]]

^<<v1-43-24,24>>^ O homem introduziu então os homens na casa de José e deu água para que se lavassem os seus pés, e deu forragem para os seus jumentos.

[[v1-43-25]]

^<<v1-43-25,25>>^ E eles passaram a aprontar o presente para a vinda de José ao meio-dia, porque souberam que era ali que iriam comer pão.

[[v1-43-26]]

^<<v1-43-26,26>>^ Entrando José na casa, trouxeram-lhe para dentro da casa o presente que tinham na mão e prostraram-se diante dele em terra.

[[v1-43-27]]

^<<v1-43-27,27>>^ Após isso, ele indagou se estavam passando bem,^&#42;1^ e disse: “Está passando bem o vosso pai,^&#42;2^ o homem idoso de quem me falastes? Ainda está vivo?”

[NOTE]
====
. Lit.: “ele perguntou-lhes sobre a paz (bem-estar)”.
. Lit.: “Tem paz (bem-estar) o vosso pai?”
====

[[v1-43-28]]

^<<v1-43-28,28>>^ A isso disseram: “Teu servo, nosso pai, está passando bem. Ainda está vivo.” Inclinaram-se então e prostraram-se em terra.

[[v1-43-29]]

^<<v1-43-29,29>>^ Quando ele levantou seus olhos e viu Benjamim, seu irmão, filho de sua mãe, prosseguiu dizendo: “É este o vosso irmão, o mais moço, de quem me falastes?” E acrescentou: “Que Deus te mostre seu favor, meu filho.”

[[v1-43-30]]

^<<v1-43-30,30>>^ José estava então com pressa, porque as suas emoções íntimas estavam agitadas para com seu irmão, de modo que procurou [um lugar] para chorar, e entrou num quarto interior e entregou-se ali ao pranto.

[[v1-43-31]]

^<<v1-43-31,31>>^ Depois lavou a face e saiu, e conteve-se e disse: “Servi a refeição.”

[[v1-43-32]]

^<<v1-43-32,32>>^ E passaram a servi-la a ele à parte, e a eles à parte, e aos egípcios que comiam com ele à parte; pois os egípcios não podiam comer uma refeição com os hebreus, visto que para os egípcios era algo detestável.

[[v1-43-33]]

^<<v1-43-33,33>>^ E foram assentados diante dele, o primogênito segundo o seu direito de primogênito e o mais jovem segundo a sua mocidade; e os homens se entreolhavam pasmados.

[[v1-43-34]]

^<<v1-43-34,34>>^ E ele fazia que de diante dele lhes fossem levadas porções, mas aumentava a porção de Benjamim cinco vezes mais que as porções de todos os outros. Continuaram assim a banquetear-se e a beber com ele fartamente.

'''

xref:001-genesis/001-genesis-042.adoc#v1-42-0[&#60; Capítulo Anterior] | <<v1-43-0,Topo>> | xref:001-genesis/001-genesis-044.adoc#v1-44-0[Próximo Capítulo &#62;]