include::./index.adoc[]

[[v1-35-0]]
=== Gênesis, 35
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v1-35-1]]

^<<v1-35-1,1>>^ Deus disse depois a Jacó: “Levanta-te, sobe a Betel e mora ali, e faze ali um altar ao [verdadeiro] Deus que te apareceu quando fugiste de Esaú, teu irmão.”

[[v1-35-2]]

^<<v1-35-2,2>>^ Jacó disse então aos da sua casa e a todos os que estavam com ele: “Removei os deuses^&#42;1^ estrangeiros que há no vosso meio, e purificai-vos e trocai as vossas capas,

[NOTE]
====
. Lit.: “deuses de”. Hebr.: ’elo·héh, pl. de ’elóh·ah, indicando uma pluralidade de deuses.
====

[[v1-35-3]]

^<<v1-35-3,3>>^ e levantemo-nos e subamos a Betel. E ali farei um altar ao [verdadeiro] Deus que me respondeu no dia da minha aflição, visto que mostrou estar comigo no caminho pelo qual andei.”

[[v1-35-4]]

^<<v1-35-4,4>>^ Assim, deram a Jacó todos os deuses estrangeiros que havia nas suas mãos e as arrecadas que havia nas suas orelhas, e Jacó os encobriu debaixo duma grande árvore que havia perto de Siquém.

[[v1-35-5]]

^<<v1-35-5,5>>^ Depois partiram dali, e o terror de Deus veio sobre as cidades que havia ao redor deles, de modo que não foram no encalço dos filhos de Jacó.

[[v1-35-6]]

^<<v1-35-6,6>>^ Por fim, Jacó chegou a Luz, que está na terra de Canaã, isto é, a Betel, ele e todo o povo que havia com ele.

[[v1-35-7]]

^<<v1-35-7,7>>^ Então construiu ali um altar e começou a chamar o lugar de El-Betel,^&#42;1^ porque o [verdadeiro] Deus se revelara ali a ele no tempo em que fugiu de seu irmão.

[NOTE]
====
. Significando “O Deus de Betel”.
====

[[v1-35-8]]

^<<v1-35-8,8>>^ Posteriormente morreu Débora, ama de Rebeca, e ela foi enterrada ao sopé de Betel, debaixo duma árvore maciça. Por isso chamou-a pelo nome de Alom-Bacute.^&#42;1^

[NOTE]
====
. Significando “Árvore Maciça de Choro”.
====

[[v1-35-9]]

^<<v1-35-9,9>>^ Deus apareceu então mais uma vez a Jacó durante a sua vinda de Padã-Arã e o abençoou.

[[v1-35-10]]

^<<v1-35-10,10>>^ E Deus prosseguiu, dizendo-lhe: “Teu nome é Jacó. Não mais hás de ser chamado pelo nome de Jacó, mas Israel virá a ser o teu nome.” E começou a chamá-lo pelo nome de Israel.

[[v1-35-11]]

^<<v1-35-11,11>>^ E Deus disse-lhe ainda mais: “Eu sou o Deus Todo-poderoso.^&#42;1^ Sê fecundo e torna-te muitos. De ti procederão nações^&#42;2^ e uma congregação de nações, e dos teus lombos sairão reis.

[NOTE]
====
. Veja 17:1 n.
. “Nações”, LXXVg; M: “uma nação”.
====

[[v1-35-12]]

^<<v1-35-12,12>>^ Quanto à terra que dei a Abraão e a Isaque, a ti a darei, e à tua descendência^&#42;1^ depois de ti darei a terra.”

[NOTE]
====
. Ou “prole; posteridade”.
====

[[v1-35-13]]

^<<v1-35-13,13>>^ Deus subiu depois de sobre ele no lugar onde lhe falara.

[[v1-35-14]]

^<<v1-35-14,14>>^ Jacó, por conseguinte, colocou uma coluna no lugar onde falara com ele, uma coluna de pedra, e derramou sobre ela uma oferta de bebida e despejou óleo sobre ela.

[[v1-35-15]]

^<<v1-35-15,15>>^ E Jacó continuou a chamar o lugar onde Deus lhe falara pelo nome de Betel.

[[v1-35-16]]

^<<v1-35-16,16>>^ Partiram então de Betel. E havendo ainda um bom trecho de terra antes de se chegar a Efrate, Raquel passou a dar à luz, e o parto lhe era difícil.

[[v1-35-17]]

^<<v1-35-17,17>>^ Mas, aconteceu que, enquanto estava tendo dificuldades no parto, a parteira lhe disse: “Não tenhas medo, pois terás também este filho.”

[[v1-35-18]]

^<<v1-35-18,18>>^ E o resultado foi que, enquanto a sua alma^&#42;1^ partia (porque estava morrendo), ela chamou-o pelo nome de Ben-Oni;^&#42;2^ mas o seu pai chamou-o de Benjamim.^&#42;3^

[NOTE]
====
. “Sua alma (vida).” Hebr.: naf·sháh; gr.: psy·khén.
. Significando “Filho do Meu Pesar”.
. Significando “Filho da Mão Direita”. Hebr.: Vin·ya·mín.
====

[[v1-35-19]]

^<<v1-35-19,19>>^ Raquel morreu assim e foi enterrada no caminho de Efrate, isto é, Belém.

[[v1-35-20]]

^<<v1-35-20,20>>^ Jacó colocou por isso uma coluna sobre o sepulcro dela. Esta é a coluna do sepulcro de Raquel até o dia de hoje.

[[v1-35-21]]

^<<v1-35-21,21>>^ Depois disso, Israel partiu e armou a sua tenda a certa distância além da torre de Éder.

[[v1-35-22]]

^<<v1-35-22,22>>^ E sucedeu, enquanto Israel residia naquela terra, que Rubem foi uma vez e se deitou com Bila, concubina de seu pai, e Israel soube disso.
Havia, pois, doze filhos de Jacó.

[[v1-35-23]]

^<<v1-35-23,23>>^ Os filhos de Léia eram: o primogênito de Jacó, Rubem, e Simeão, e Levi, e Judá, e Issacar, e Zebulão.

[[v1-35-24]]

^<<v1-35-24,24>>^ Os filhos de Raquel eram José e Benjamim.

[[v1-35-25]]

^<<v1-35-25,25>>^ E os filhos de Bila, serva de Raquel, eram Dã e Naftali.

[[v1-35-26]]

^<<v1-35-26,26>>^ E os filhos de Zilpa, serva de Léia, eram Gade e Aser. Estes eram os filhos de Jacó que lhe nasceram em Padã-Arã.

[[v1-35-27]]

^<<v1-35-27,27>>^ Por fim, Jacó chegou até Isaque, seu pai, a Manre, a Quiriate-Arba, isto é, Hébron, onde Abraão e também Isaque tinham residido como forasteiros.

[[v1-35-28]]

^<<v1-35-28,28>>^ E os dias de Isaque vieram a ser cento e oitenta anos.

[[v1-35-29]]

^<<v1-35-29,29>>^ Depois, Isaque expirou e morreu, e foi ajuntado ao seu povo, idoso e saciado de dias,^&#42;1^ e Esaú e Jacó, seus filhos, o enterraram.

[NOTE]
====
. Ou “cheio (saciado) de dias”, MLXXVg.
====

'''

xref:001-genesis/001-genesis-034.adoc#v1-34-0[&#60; Capítulo Anterior] | <<v1-35-0,Topo>> | xref:001-genesis/001-genesis-036.adoc#v1-36-0[Próximo Capítulo &#62;]