include::./index.adoc[]

[[v1-39-0]]
=== Gênesis, 39
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v1-39-1]]

^<<v1-39-1,1>>^ Quanto a José, ele foi levado para baixo ao Egito, e Potifar, oficial da corte de Faraó,^&#42;1^ chefe da guarda pessoal, egípcio, foi comprá-lo da mão dos ismaelitas que o levaram lá para baixo.

[NOTE]
====
. Veja 12:15 n.
====

[[v1-39-2]]

^<<v1-39-2,2>>^ Mas, Jeová mostrou-se com José, de modo que ele se tornou homem bem sucedido e veio a ser posto sobre a casa de seu amo,^&#42;1^ o egípcio.

[NOTE]
====
. “Seu amo.” Hebr.: ’adho·náv, pl. de ’a·dhóhn, para denotar excelência, como nos vv. 3, 7, 8, 16, 19 e 20.
====

[[v1-39-3]]

^<<v1-39-3,3>>^ E seu amo via que Jeová estava com ele e que tudo o que fazia, Jeová tornava bem sucedido na sua mão.

[[v1-39-4]]

^<<v1-39-4,4>>^ E José achava favor aos seus olhos e servia-o continuamente, de modo que ele o encarregou da sua casa, e tudo o que era seu entregou na mão dele.

[[v1-39-5]]

^<<v1-39-5,5>>^ E seguiu-se que, a partir do tempo em que o encarregou da sua casa e de tudo o que era seu, Jeová abençoava a casa do egípcio devido a José, e a bênção de Jeová veio a estar sobre tudo o que era seu na casa e no campo.

[[v1-39-6]]

^<<v1-39-6,6>>^ Finalmente deixou tudo o que era seu na mão de José; e não sabia nem o que possuía, exceto o pão que comia. Além disso, José tornou-se belo de porte e belo de aparência.

[[v1-39-7]]

^<<v1-39-7,7>>^ Ora, depois destas coisas sucedeu que a esposa de seu amo começou a levantar seus olhos para José e a dizer: “Deita-te comigo.”

[[v1-39-8]]

^<<v1-39-8,8>>^ Mas ele se negava e dizia à esposa de seu amo: “Eis que meu amo não sabe nem o que há comigo na casa, e tudo o que tem ele entregou na minha mão.

[[v1-39-9]]

^<<v1-39-9,9>>^ Não há quem seja maior do que eu nesta casa, e ele não me vedou absolutamente nada, exceto a ti, porque és sua esposa. Portanto, como poderia eu cometer esta grande maldade e realmente pecar contra Deus?”

[[v1-39-10]]

^<<v1-39-10,10>>^ Resultou então que, falando ela a José dia após dia, ele nunca a escutava de modo a se deitar ao seu lado, para continuar com ela.

[[v1-39-11]]

^<<v1-39-11,11>>^ Mas, aconteceu que certo dia, como nos outros dias,^&#42;1^ ele entrou na casa para tratar dos seus negócios, e não havia nenhum dos homens da casa ali na casa.

[NOTE]
====
. “Certo dia, como nos outros dias.” Quanto a esta versão, veja VT, Vol. II, 1952, pp. 85-87.
====

[[v1-39-12]]

^<<v1-39-12,12>>^ Ela o pegou então pela sua veste, dizendo: “Deita-te comigo!” Mas ele deixou a sua veste na mão dela e fugiu, e foi para fora.

[[v1-39-13]]

^<<v1-39-13,13>>^ Deu-se então que assim que ela viu que deixara a sua veste na mão dela, a fim de fugir para fora,

[[v1-39-14]]

^<<v1-39-14,14>>^ começou a clamar aos homens de sua casa e a dizer-lhes: “Vede! Ele nos trouxe um homem, um hebreu, para fazer de nós objeto de riso. Ele se chegou a mim para se deitar comigo, mas comecei a clamar ao máximo da minha voz.

[[v1-39-15]]

^<<v1-39-15,15>>^ E seguiu-se que, assim que ouviu que ergui a minha voz e comecei a clamar, deixou a sua veste ao meu lado e pôs-se em fuga, e foi para fora.”

[[v1-39-16]]

^<<v1-39-16,16>>^ Depois deixou a veste dele deitada ao seu lado até que o amo dele chegou à sua casa.

[[v1-39-17]]

^<<v1-39-17,17>>^ Falou-lhe então segundo estas palavras, dizendo: “O servo hebreu que nos trouxeste chegou-se a mim para fazer de mim objeto de riso.^&#42;1^

[NOTE]
====
. LXX acrescenta: “e ele me disse: ‘Vou coabitar contigo.’”
====

[[v1-39-18]]

^<<v1-39-18,18>>^ Mas, seguiu-se que, assim que ergui a minha voz e comecei a clamar, ele deixou a sua veste ao meu lado e fugiu para fora.”

[[v1-39-19]]

^<<v1-39-19,19>>^ O resultado foi que assim que seu amo ouviu as palavras de sua esposa, que ela lhe falou, dizendo: “Assim e assim me fez o teu servo”, acendeu-se a sua ira.

[[v1-39-20]]

^<<v1-39-20,20>>^ O amo de José tomou-o, pois, e entregou-o à casa da prisão,^&#42;1^ ao lugar onde os prisioneiros^&#42;2^ do rei eram mantidos presos,^&#42;3^ e ele continuou ali na casa da prisão.

[NOTE]
====
. Lit.: “casa do castelo [redondo]”.
. Lit.: “amarrados”.
. Lit.: “eram mantidos amarrados”.
====

[[v1-39-21]]

^<<v1-39-21,21>>^ No entanto, Jeová continuava com José e estendia-lhe benevolência, e concedia-lhe achar favor aos olhos do oficial principal^&#42;1^ da casa da prisão.

[NOTE]
====
. Ou “do príncipe”. Hebr.: sar.
====

[[v1-39-22]]

^<<v1-39-22,22>>^ Assim, o oficial principal da casa da prisão entregou à mão de José todos os prisioneiros que havia na casa da prisão; e em tudo o que faziam ali mostrava-se que era ele quem o fazia executar.

[[v1-39-23]]

^<<v1-39-23,23>>^ O oficial principal da casa da prisão não cuidava de coisa alguma que havia na sua mão, porque Jeová estava com [José],^&#42;1^ e aquilo que fazia, Jeová, por sua vez, fazia bem sucedido.

[NOTE]
====
. Lit.: “ele”.
====

'''

xref:001-genesis/001-genesis-038.adoc#v1-38-0[&#60; Capítulo Anterior] | <<v1-39-0,Topo>> | xref:001-genesis/001-genesis-040.adoc#v1-40-0[Próximo Capítulo &#62;]