include::./index.adoc[]

[[v1-25-0]]
=== Gênesis, 25
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v1-25-1]]

^<<v1-25-1,1>>^ Além disso, Abraão tomou novamente uma esposa, e o nome dela era Quetura.

[[v1-25-2]]

^<<v1-25-2,2>>^ Com o correr do tempo deu-lhe à luz Zinrã, e Jocsã, e Medã, e Midiã, e Isbaque, e Suá.

[[v1-25-3]]

^<<v1-25-3,3>>^ E Jocsã tornou-se pai de Sabá e Dedã.
E os filhos de Dedã tornaram-se assurins, e letusins, e leumins.^&#42;1^

[NOTE]
====
. Visto que cada um destes três nomes hebr. tem a terminação pl. im, entende-se que eles representam tribos ou povos.
====

[[v1-25-4]]

^<<v1-25-4,4>>^ E os filhos de Midiã foram Efá, e Efer, e Anoque, e Abida, e Elda.
Todos estes foram os filhos de Quetura.

[[v1-25-5]]

^<<v1-25-5,5>>^ Posteriormente, Abraão deu a Isaque tudo o que possuía,

[[v1-25-6]]

^<<v1-25-6,6>>^ mas, aos filhos das concubinas que Abraão tinha, Abraão deu dádivas. Então os enviou para longe de Isaque, seu filho, enquanto ainda vivia, para o leste, para a terra do Oriente.

[[v1-25-7]]

^<<v1-25-7,7>>^ E estes são os dias dos anos de vida de Abraão, que ele viveu, cento e setenta e cinco anos.

[[v1-25-8]]

^<<v1-25-8,8>>^ Abraão expirou então e morreu numa boa velhice, idoso e satisfeito,^&#42;1^ e foi ajuntado ao seu povo.

[NOTE]
====
. “Cheio de dias”, LXXSyVg.
====

[[v1-25-9]]

^<<v1-25-9,9>>^ De modo que Isaque e Ismael, seus filhos, o enterraram na caverna de Macpela, no campo de Efrom, filho de Zoar, o hitita, que está defronte de Manre,

[[v1-25-10]]

^<<v1-25-10,10>>^ o campo que Abraão tinha comprado dos filhos de Hete. Ali foi enterrado Abraão e também Sara, sua esposa.

[[v1-25-11]]

^<<v1-25-11,11>>^ E aconteceu, após a morte de Abraão, que Deus continuava a abençoar Isaque, seu filho, e Isaque morava perto de Beer-Laai-Roi.

[[v1-25-12]]

^<<v1-25-12,12>>^ E esta é a história de Ismael, filho de Abraão, a quem Agar, a egípcia, serva de Sara, deu à luz a Abraão.

[[v1-25-13]]

^<<v1-25-13,13>>^ Ora, estes são os nomes dos filhos de Ismael, pelos seus nomes, segundo as suas linhagens: o primogênito de Ismael, Nebaiote, e Quedar, e Adbeel, e Mibsão,

[[v1-25-14]]

^<<v1-25-14,14>>^ e Misma, e Dumá, e Massa,

[[v1-25-15]]

^<<v1-25-15,15>>^ Hadade e Tema, Jetur, Nafis e Quedemá.

[[v1-25-16]]

^<<v1-25-16,16>>^ Estes são os filhos de Ismael, e estes são os seus nomes pelos seus pátios e pelos seus acampamentos murados: doze maiorais, segundo os seus clãs.

[[v1-25-17]]

^<<v1-25-17,17>>^ E estes são os anos de vida de Ismael, cento e trinta e sete anos. Então expirou e morreu, e foi ajuntado ao seu povo.

[[v1-25-18]]

^<<v1-25-18,18>>^ E passaram a residir desde Havilá, perto de Sur, que está defronte^&#42;1^ do Egito, até a Assíria. Estabeleceu-se^&#42;2^ na frente de todos os seus irmãos.

[NOTE]
====
. Ou “ao leste”.
. Lit.: “caiu”, M; LXX: “morou (fixou-se)”; Vg: “morreu”.
====

[[v1-25-19]]

^<<v1-25-19,19>>^ E esta é a história de Isaque, filho de Abraão.
Abraão tornou-se pai de Isaque.

[[v1-25-20]]

^<<v1-25-20,20>>^ E Isaque era da idade de quarenta anos quando tomou por sua esposa a Rebeca, filha de Betuel, o sírio^&#42;1^ de Padã-Arã,^&#42;2^ irmã de Labão, o sírio.

[NOTE]
====
. Lit.: “o arameu”.
. Significando “Planície (Baixada) de Arã (Síria)”; parte da Mesopotâmia. Veja 28:2.
====

[[v1-25-21]]

^<<v1-25-21,21>>^ E Isaque suplicava a Jeová especialmente por sua esposa, porque ela era estéril; assim, Jeová deixou-se suplicar por ele, e Rebeca, esposa dele, ficou grávida.

[[v1-25-22]]

^<<v1-25-22,22>>^ E os filhos dentro dela começaram a lutar entre si, de modo que ela disse: “Se é assim, por que é que estou viva?”^&#42;1^ Com isso ela foi consultar Jeová.

[NOTE]
====
. “Viva”, inserido em harmonia com Sy. Veja 27:46.
====

[[v1-25-23]]

^<<v1-25-23,23>>^ E Jeová passou a dizer-lhe: “Há duas nações no teu ventre e dois grupos nacionais serão separados das tuas entranhas; e um grupo nacional será mais forte do que o outro grupo nacional, e o mais velho servirá ao mais jovem.”^&#42;1^

[NOTE]
====
. Ou “menor”.
====

[[v1-25-24]]

^<<v1-25-24,24>>^ Completaram-se gradualmente os seus dias para dar à luz, e eis que havia gêmeos no seu ventre.

[[v1-25-25]]

^<<v1-25-25,25>>^ Então saiu o primeiro, todo vermelho como um manto oficial de pêlo, de modo que o chamaram pelo nome de Esaú.^&#42;1^

[NOTE]
====
. Significando “Peludo”. Hebr.: ‛E·sáw.
====

[[v1-25-26]]

^<<v1-25-26,26>>^ E depois saiu seu irmão, e a mão dele segurava o calcanhar de Esaú, de modo que o chamou pelo nome de Jacó.^&#42;1^ E Isaque era da idade de sessenta anos quando ela os deu à luz.

[NOTE]
====
. Significando “Agarrando o Calcanhar; Suplantador”. Hebr.: Ya·‛aqóv.
====

[[v1-25-27]]

^<<v1-25-27,27>>^ E os rapazes cresciam, e Esaú tornou-se homem entendido na caça, homem do campo,^&#42;1^ mas Jacó [tornou-se] homem inculpe, morando em tendas.

[NOTE]
====
. Ou “homem selvagem”.
====

[[v1-25-28]]

^<<v1-25-28,28>>^ E Isaque amava Esaú, porque significava caça para a sua boca,^&#42;1^ ao passo que Rebeca amava Jacó.

[NOTE]
====
. Lit.: “porque havia caça na sua boca”.
====

[[v1-25-29]]

^<<v1-25-29,29>>^ Certa vez Jacó tinha ao fogo um cozido,^&#42;1^ quando Esaú veio do campo, cansado.

[NOTE]
====
. Ou “sopa de legumes”.
====

[[v1-25-30]]

^<<v1-25-30,30>>^ De modo que Esaú disse a Jacó: “Depressa, por favor, dá-me um bocado do vermelho — do vermelho^&#42;1^ aí, pois estou cansado!” É por isso que foi chamado pelo nome de Edom.^&#42;2^

[NOTE]
====
. “Do vermelho.” Hebr.: ha·’a·dhóm.
. Significando “Vermelho; Ruivo”. Hebr.: ’Edhóhm.
====

[[v1-25-31]]

^<<v1-25-31,31>>^ A isso Jacó disse: “Vende-me primeiro teu direito de primogênito!”

[[v1-25-32]]

^<<v1-25-32,32>>^ E Esaú continuou: “Eis que estou simplesmente morrendo, e de que proveito me é a primogenitura?”^&#42;1^

[NOTE]
====
. Ou “direito de primogênito”.
====

[[v1-25-33]]

^<<v1-25-33,33>>^ E Jacó acrescentou: “Jura-me primeiro!” E ele passou a jurar-lhe e a vender a Jacó seu direito como primogênito.

[[v1-25-34]]

^<<v1-25-34,34>>^ E Jacó deu a Esaú pão e cozido de lentilhas, e ele foi comer e beber. Depois se levantou e foi embora. Assim desprezou Esaú a primogenitura.

'''

xref:001-genesis/001-genesis-024.adoc#v1-24-0[&#60; Capítulo Anterior] | <<v1-25-0,Topo>> | xref:001-genesis/001-genesis-026.adoc#v1-26-0[Próximo Capítulo &#62;]