include::./index.adoc[]

[[v1-28-0]]
=== Gênesis, 28
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v1-28-1]]

^<<v1-28-1,1>>^ Por conseguinte, Isaque chamou Jacó e o abençoou, e ordenou-lhe e disse-lhe: “Não deves tomar esposa dentre as filhas de Canaã.^&#42;1^

[NOTE]
====
. Ou “dos cananeus”.
====

[[v1-28-2]]

^<<v1-28-2,2>>^ Levanta-te, vai a Padã-Arã,^&#42;1^ à casa de Betuel, pai de tua mãe, e ali toma para ti por esposa uma das filhas de Labão, irmão de tua mãe.

[NOTE]
====
. Veja 25:20 n.: “Padã-Arã.”
====

[[v1-28-3]]

^<<v1-28-3,3>>^ E o Deus Todo-poderoso te abençoará e te fará fecundo, e te multiplicará, e certamente hás de tornar-te uma congregação de povos.

[[v1-28-4]]

^<<v1-28-4,4>>^ E ele te dará a bênção de Abraão, a ti e à tua descendência contigo, para que tomes posse da terra das tuas residências como forasteiro, que Deus deu a Abraão.”

[[v1-28-5]]

^<<v1-28-5,5>>^ Portanto, Isaque mandou Jacó embora, e ele partiu para Padã-Arã, a fim de [ir ter com] Labão, filho de Betuel, o sírio,^&#42;1^ irmão de Rebeca, mãe de Jacó e Esaú.^&#42;2^

[NOTE]
====
. Lit.: “o arameu”.
. “Jacó e Esaú.” Jacó é posto antes de seu irmão gêmeo mais velho, denotando preferência.
====

[[v1-28-6]]

^<<v1-28-6,6>>^ Quando Esaú viu que Isaque tinha abençoado a Jacó e que o enviara a Padã-Arã, para lá tomar para si uma esposa, e que, ao abençoá-lo, lhe ordenara, dizendo: “Não tomes esposa dentre as filhas de Canaã”,

[[v1-28-7]]

^<<v1-28-7,7>>^ e que Jacó obedecia a seu pai e sua mãe, e que estava em caminho para Padã-Arã,

[[v1-28-8]]

^<<v1-28-8,8>>^ então Esaú viu que as filhas de Canaã desagradavam^&#42;1^ aos olhos de Isaque, seu pai.

[NOTE]
====
. Ou “eram más; perversas”.
====

[[v1-28-9]]

^<<v1-28-9,9>>^ Esaú foi por isso ter com Ismael^&#42;1^ e tomou por esposa a Maalate, filha de Ismael, filho de Abraão, a irmã de Nebaiote, além das suas outras esposas.

[NOTE]
====
. Ou “os ismaelitas”. Ismael então já estava morto e Esaú tinha cerca de 77 anos de idade. Veja 25:17, 26.
====

[[v1-28-10]]

^<<v1-28-10,10>>^ E Jacó seguiu caminho desde Berseba e dirigiu-se a Harã.

[[v1-28-11]]

^<<v1-28-11,11>>^ Com o tempo atingiu certo lugar e se preparou para pernoitar ali, visto que o sol já se tinha posto. Tomou, pois, uma das pedras do lugar e a pôs como apoio^&#42;1^ para a sua cabeça, e deitou-se naquele lugar.

[NOTE]
====
. Ou “seu travesseiro”.
====

[[v1-28-12]]

^<<v1-28-12,12>>^ E começou a sonhar, e eis que havia uma escada^&#42;1^ posta na terra e seu topo tocava nos céus; e eis que anjos de Deus subiam e desciam por ela.

[NOTE]
====
. Ou “escadaria ascendente de pedras”.
====

[[v1-28-13]]

^<<v1-28-13,13>>^ E eis que Jeová estava parado acima dela e passou a dizer:
“Eu sou Jeová, o Deus de Abraão, teu pai, e o Deus de Isaque. A terra em que estás deitado, eu vou dá-la a ti e à tua descendência.

[[v1-28-14]]

^<<v1-28-14,14>>^ E tua descendência há de tornar-se como as partículas de pó da terra, e tu te hás de espalhar para o oeste, e para o leste, e para o norte, e para o sul, e todas as famílias do solo hão de abençoar a si mesmas^&#42;1^ por meio de ti e por meio de tua descendência.

[NOTE]
====
. “Serão abençoadas”, LXXVg. Veja 22:18 n.
====

[[v1-28-15]]

^<<v1-28-15,15>>^ E eis que estou contigo e vou guardar-te em todo o caminho em que andares, e vou retornar-te a este solo, porque não te abandonarei até que eu tenha realmente feito o que te falei.”

[[v1-28-16]]

^<<v1-28-16,16>>^ Jacó acordou então do sono e disse: “Verdadeiramente, Jeová está neste lugar e eu mesmo não o sabia.”

[[v1-28-17]]

^<<v1-28-17,17>>^ E ficou temeroso e acrescentou: “Quão atemorizante é este lugar! Não é senão a casa de Deus e este é o portão dos céus.”

[[v1-28-18]]

^<<v1-28-18,18>>^ De modo que Jacó se levantou de manhã cedo e tomou a pedra que tivera ali como apoio para a sua cabeça, e erigiu-a como coluna e despejou óleo sobre o topo dela.

[[v1-28-19]]

^<<v1-28-19,19>>^ Ademais, chamou aquele lugar pelo nome de Betel;^&#42;1^ mas o fato é que o nome da cidade era anteriormente Luz.

[NOTE]
====
. Significando “Casa de Deus”. Hebr.: Behth-’Él.
====

[[v1-28-20]]

^<<v1-28-20,20>>^ E Jacó foi fazer um voto, dizendo: “Se Deus continuar comigo e certamente me guardar neste caminho em que estou andando, e certamente me der pão para comer e roupas para usar,

[[v1-28-21]]

^<<v1-28-21,21>>^ e eu certamente retornar em paz à casa de meu pai, então Jeová terá mostrado ser meu Deus.^&#42;1^

[NOTE]
====
. Ou “Deus para mim”. Hebr.: li lE’·lo·hím.
====

[[v1-28-22]]

^<<v1-28-22,22>>^ E esta pedra que ergui como coluna se tornará uma casa de Deus, e quanto a tudo o que me deres, dar-te-ei sem falta um décimo dele.”

'''

xref:001-genesis/001-genesis-027.adoc#v1-27-0[&#60; Capítulo Anterior] | <<v1-28-0,Topo>> | xref:001-genesis/001-genesis-029.adoc#v1-29-0[Próximo Capítulo &#62;]