include::./index.adoc[]

[[v1-44-0]]
=== Gênesis, 44
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v1-44-1]]

^<<v1-44-1,1>>^ Posteriormente ordenou ao homem que estava sobre a sua casa, dizendo: “Enche de mantimentos as sacas dos homens, com tanto quanto puderem transportar, e coloca o dinheiro de cada um na boca da sua saca.

[[v1-44-2]]

^<<v1-44-2,2>>^ Mas tens de colocar meu cálice, o cálice de prata, na boca da saca do mais moço, bem como o dinheiro pelos seus cereais.” Ele fez assim segundo a palavra falada por José.

[[v1-44-3]]

^<<v1-44-3,3>>^ De manhã, ao clarear, os homens foram mandados embora, tanto eles como seus jumentos.

[[v1-44-4]]

^<<v1-44-4,4>>^ Saíram da cidade. Não tinham ido longe, quando José disse ao homem que estava sobre a sua casa: “Levanta-te! Vai no encalço dos homens, e tem certeza de alcançá-los e de dizer-lhes: ‘Por que retribuístes o bem com o mal?

[[v1-44-5]]

^<<v1-44-5,5>>^ Não é esta a coisa de que meu amo bebe e por meio da qual interpreta peritamente os presságios? Procedestes mal no que fizestes.’”

[[v1-44-6]]

^<<v1-44-6,6>>^ Por fim os alcançou e lhes falou estas palavras.

[[v1-44-7]]

^<<v1-44-7,7>>^ Mas eles lhe disseram: “Por que fala meu senhor tais palavras? É inconcebível que teus servos façam tal coisa.

[[v1-44-8]]

^<<v1-44-8,8>>^ Ora, desde a terra de Canaã te trouxemos o dinheiro que achamos na boca das nossas sacas. Como, então, poderíamos furtar prata ou ouro da casa do teu amo?

[[v1-44-9]]

^<<v1-44-9,9>>^ Morra aquele dos teus escravos^&#42;1^ com quem for achado e tornemo-nos também escravos do meu amo.”

[NOTE]
====
. Ou “servos”.
====

[[v1-44-10]]

^<<v1-44-10,10>>^ De modo que ele disse: “Seja agora exatamente segundo as vossas palavras. Assim, aquele com quem for achado tornar-se-á meu escravo, mas vós mesmos sereis provados inocentes.”

[[v1-44-11]]

^<<v1-44-11,11>>^ Com isso puseram rapidamente a saca de cada um no chão e abriram cada um a sua própria saca.

[[v1-44-12]]

^<<v1-44-12,12>>^ E ele fez uma busca cuidadosa. Principiou com o mais velho e terminou com o mais moço. Por fim se achou o cálice na saca de Benjamim.

[[v1-44-13]]

^<<v1-44-13,13>>^ Rasgaram então as suas capas e puseram cada um a sua própria carga de volta no seu jumento, e voltaram à cidade.

[[v1-44-14]]

^<<v1-44-14,14>>^ E Judá e seus irmãos foram entrar na casa de José, e ele ainda estava ali; e passaram a lançar-se diante dele por terra.

[[v1-44-15]]

^<<v1-44-15,15>>^ José disse-lhes então: “Que sorte de ato é este que praticastes? Não sabíeis que um homem tal como eu pode interpretar peritamente os presságios?”

[[v1-44-16]]

^<<v1-44-16,16>>^ A isso Judá exclamou: “Que podemos dizer ao meu amo? Que podemos falar? E como nos podemos provar justos? O [verdadeiro] Deus descobriu o erro dos teus escravos. Eis que somos escravos de meu amo, tanto nós como aquele em cuja mão foi achado o cálice!”

[[v1-44-17]]

^<<v1-44-17,17>>^ No entanto, ele disse: “É inconcebível que eu faça isso! O homem em cuja mão se achou o cálice é quem se tornará meu escravo. Quanto aos demais de vós, ide em paz para o vosso pai.”

[[v1-44-18]]

^<<v1-44-18,18>>^ Judá aproximou-se então dele e disse: “Rogo-te, meu amo, por favor, deixa teu escravo falar uma palavra aos ouvidos do meu amo, e não se acenda a tua ira contra o teu escravo, porque contigo é o mesmo que com Faraó.^&#42;1^

[NOTE]
====
. Ou “tu és como Faraó”.
====

[[v1-44-19]]

^<<v1-44-19,19>>^ Meu amo^&#42;1^ perguntou aos seus escravos, dizendo: ‘Tendes pai ou irmão?’

[NOTE]
====
. Ou: “Meu senhor.”
====

[[v1-44-20]]

^<<v1-44-20,20>>^ De modo que dissemos ao meu amo: ‘Temos um pai idoso e um menino de sua velhice, o mais moço. Mas o irmão dele está morto, de modo que só ele resta de sua mãe, e seu pai deveras o ama.’

[[v1-44-21]]

^<<v1-44-21,21>>^ Depois disseste aos teus escravos: ‘Trazei-mo para baixo, a fim de que eu ponha os olhos nele.’

[[v1-44-22]]

^<<v1-44-22,22>>^ Mas dissemos ao meu amo: ‘O rapaz não pode deixar seu pai. Se deixasse seu pai, este certamente morreria.’

[[v1-44-23]]

^<<v1-44-23,23>>^ Disseste então aos teus escravos: ‘A menos que o vosso irmão mais moço desça convosco, não mais podereis ver a minha face.’

[[v1-44-24]]

^<<v1-44-24,24>>^ “E sucedeu que subimos até o teu escravo, meu pai, e lhe contamos então as palavras de meu amo.

[[v1-44-25]]

^<<v1-44-25,25>>^ Mais tarde, nosso pai disse: ‘Voltai, comprai-nos alguns mantimentos.’

[[v1-44-26]]

^<<v1-44-26,26>>^ Mas nós dissemos: ‘Não podemos descer. Se o nosso irmão mais moço estiver conosco, desceremos, porque não podemos ver a face do homem caso nosso irmão mais moço não esteja conosco.’

[[v1-44-27]]

^<<v1-44-27,27>>^ Teu escravo, meu pai, disse-nos então: ‘Vós mesmos bem sabeis que a minha esposa só me deu à luz dois filhos.

[[v1-44-28]]

^<<v1-44-28,28>>^ Mais tarde, um saiu da minha convivência e eu exclamei: “Ah! seguramente deve ter sido dilacerado!” e não o vi até agora.

[[v1-44-29]]

^<<v1-44-29,29>>^ Se fôsseis levar também a este fora da minha vista e lhe sobreviesse um acidente fatal, certamente faríeis os meus cabelos grisalhos descer com calamidade ao Seol.’

[[v1-44-30]]

^<<v1-44-30,30>>^ “E agora, assim que eu viesse a teu escravo, meu pai, sem que o rapaz estivesse conosco, quando a alma daquele está atada à alma deste,

[[v1-44-31]]

^<<v1-44-31,31>>^ então por certo se há de dar que, assim que vir que o rapaz não está ali, ele simplesmente morrerá, e teus escravos, deveras, farão os cabelos grisalhos de teu escravo, nosso pai, descer com pesar ao Seol.^&#42;1^

[NOTE]
====
. “Ao Seol.” Hebr.: she’ólah; gr.: eis haí·dou; sir.: la·shiul; lat.: ad ín·fe·ros. Veja Ap. 4B.
====

[[v1-44-32]]

^<<v1-44-32,32>>^ Pois o teu escravo tornou-se fiança pelo rapaz enquanto estiver longe de seu pai, dizendo: ‘Se eu falhar em trazê-lo de volta a ti, então terei pecado contra meu pai para sempre.’^&#42;1^

[NOTE]
====
. Lit.: “todos os dias”.
====

[[v1-44-33]]

^<<v1-44-33,33>>^ De modo que agora, por favor, deixa teu escravo ficar em lugar do rapaz, como escravo do meu amo, para que o rapaz possa subir com os seus irmãos.

[[v1-44-34]]

^<<v1-44-34,34>>^ Pois, como poderia eu subir até meu pai sem que o rapaz estivesse comigo, para não ser que eu olhe então para a calamidade que há de apanhar meu pai?”

'''

xref:001-genesis/001-genesis-043.adoc#v1-43-0[&#60; Capítulo Anterior] | <<v1-44-0,Topo>> | xref:001-genesis/001-genesis-045.adoc#v1-45-0[Próximo Capítulo &#62;]