include::./index.adoc[]

[[v1-47-0]]
=== Gênesis, 47
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v1-47-1]]

^<<v1-47-1,1>>^ José veio, portanto, e informou Faraó e disse: “Meu pai e meus irmãos, e seus rebanhos e suas manadas, e tudo o que eles têm, vieram da terra de Canaã e eis que estão na terra de Gósen.”

[[v1-47-2]]

^<<v1-47-2,2>>^ E do total de seus irmãos tomou cinco homens para apresentá-los a Faraó.

[[v1-47-3]]

^<<v1-47-3,3>>^ Faraó disse então aos irmãos dele: “Qual é a vossa ocupação?” Disseram, pois, a Faraó: “Teus servos são pastores de ovelhas, tanto nós como os nossos antepassados.”

[[v1-47-4]]

^<<v1-47-4,4>>^ Depois disseram a Faraó: “Viemos residir como forasteiros no país, porque não há pasto para o rebanho que é dos teus servos, pois a fome é severa na terra de Canaã. E agora, por favor, deixa os teus servos morar na terra de Gósen.”

[[v1-47-5]]

^<<v1-47-5,5>>^ Faraó disse então a José: “Teu pai e teus irmãos vieram para cá ter contigo.

[[v1-47-6]]

^<<v1-47-6,6>>^ A terra do Egito está à tua disposição. Faze teu pai e teus irmãos morar no melhor do país. Morem eles na terra de Gósen, e se souberes que há entre eles homens corajosos,^&#42;1^ tens de designá-los chefes^&#42;2^ do gado sobre o que é meu.”

[NOTE]
====
. “Homens diligentes”, Vg.
. Hebr.: sa·réh.
====

[[v1-47-7]]

^<<v1-47-7,7>>^ José introduziu então Jacó, seu pai, e apresentou-o a Faraó, e Jacó passou a abençoar Faraó.

[[v1-47-8]]

^<<v1-47-8,8>>^ Faraó disse então a Jacó: “Quantos são os dias dos anos da tua vida?”

[[v1-47-9]]

^<<v1-47-9,9>>^ Jacó disse, pois, a Faraó: “Os dias dos anos das minhas residências como forasteiro são cento e trinta anos. Os dias dos anos da minha vida mostraram-se poucos e aflitivos, e não alcançaram os dias dos anos das vidas de meus pais, nos dias das suas residências como forasteiros.”

[[v1-47-10]]

^<<v1-47-10,10>>^ Após isso, Jacó abençoou Faraó e saiu de diante de Faraó.

[[v1-47-11]]

^<<v1-47-11,11>>^ Deste modo, José fez seu pai e seus irmãos morar, e deu-lhes propriedade na terra do Egito, no melhor do país, na terra de Ramessés, assim como Faraó ordenara.

[[v1-47-12]]

^<<v1-47-12,12>>^ E José supria de pão seu pai e seus irmãos, e todos os da casa de seu pai, segundo o número dos pequeninos.^&#42;1^

[NOTE]
====
. Ou “das crianças”.
====

[[v1-47-13]]

^<<v1-47-13,13>>^ Ora, não havia pão em todo o país, porque a fome era muito severa; e a terra do Egito e a terra de Canaã ficaram exauridas em resultado da fome.

[[v1-47-14]]

^<<v1-47-14,14>>^ E José juntava todo o dinheiro que se achava na terra do Egito e na terra de Canaã pelos cereais que as pessoas compravam; e José trazia o dinheiro à casa de Faraó.

[[v1-47-15]]

^<<v1-47-15,15>>^ Com o tempo se esgotou o dinheiro da terra do Egito e da terra de Canaã, e todos os egípcios começaram a vir a José, dizendo: “Dá-nos pão! E por que devíamos morrer na tua frente por se ter acabado o dinheiro?”

[[v1-47-16]]

^<<v1-47-16,16>>^ José disse então: “Entregai o vosso gado e eu vos darei pão em troca do vosso gado, se o dinheiro se tiver acabado.”

[[v1-47-17]]

^<<v1-47-17,17>>^ E começaram a trazer seu gado a José; e José dava-lhes pão em troca dos seus cavalos^&#42;1^ e da criação do rebanho, e da criação de gado vacum, e dos jumentos, e abastecia-os de pão em troca de todo o seu gado, durante aquele ano.

[NOTE]
====
. Lit.: “pelos cavalos”. Hebr.: bas·su·sím; esta é a primeira menção bíblica de cavalos, pelos quais o Egito se tornou famoso.
====

[[v1-47-18]]

^<<v1-47-18,18>>^ Aquele ano chegou gradualmente ao fim, e começaram a vir a ele no ano seguinte^&#42;1^ e a dizer-lhe: “Não o ocultaremos do meu senhor, mas o dinheiro e a criação de animais domésticos esgotaram-se para meu senhor. Nada resta diante do meu senhor senão os nossos corpos e o nosso terreno.

[NOTE]
====
. Lit.: “segundo”.
====

[[v1-47-19]]

^<<v1-47-19,19>>^ Por que devíamos morrer diante dos teus olhos, tanto nós como o nosso terreno? Compra a nós e o nosso terreno por pão, e nós, junto com o nosso terreno, nos tornaremos escravos de Faraó; e dá-nos semente para que vivamos e não morramos, e o nosso terreno não fique desolado.”

[[v1-47-20]]

^<<v1-47-20,20>>^ José comprou assim todo o terreno dos egípcios para Faraó, porque os egípcios venderam cada um o seu campo, pois a fome se apoderara deles fortemente; e o país veio a ser de Faraó.

[[v1-47-21]]

^<<v1-47-21,21>>^ Quanto ao povo, transferiu-o para as cidades, de uma extremidade do território do Egito até à sua outra extremidade.

[[v1-47-22]]

^<<v1-47-22,22>>^ Somente não comprou o terreno dos sacerdotes, porque as rações dos sacerdotes provinham de Faraó e eles comiam as suas rações que Faraó lhes dava. É por isso que não venderam seu terreno.

[[v1-47-23]]

^<<v1-47-23,23>>^ José disse então ao povo: “Eis que hoje comprei tanto a vós como o vosso terreno para Faraó. Aqui há semente para vós, e tendes de semear com ela o terreno.

[[v1-47-24]]

^<<v1-47-24,24>>^ Quando tiver resultado em produtos, então tereis de dar um quinto a Faraó, mas quatro partes se tornarão vossas, como semente para o campo e como mantimento para vós, e para os que há nas vossas casas, e para os vossos pequeninos comerem.”

[[v1-47-25]]

^<<v1-47-25,25>>^ Por conseguinte, disseram: “Preservaste-nos a vida. Achemos favor aos olhos de meu senhor e nos tornaremos escravos de Faraó.”

[[v1-47-26]]

^<<v1-47-26,26>>^ E José passou a fazer disso um decreto até o dia de hoje, com respeito aos bens de terra do Egito, para que Faraó tivesse até o montante de um quinto. Somente o terreno dos sacerdotes, como grupo separado, não se tornou de Faraó.

[[v1-47-27]]

^<<v1-47-27,27>>^ E Israel continuou a morar na terra do Egito, na terra de Gósen; e estabeleceram-se nela e foram fecundos, e aumentaram muitíssimo.

[[v1-47-28]]

^<<v1-47-28,28>>^ E Jacó viveu na terra do Egito por dezessete anos, de modo que os dias de Jacó, os anos de sua vida, vieram a ser cento e quarenta e sete anos.

[[v1-47-29]]

^<<v1-47-29,29>>^ Chegaram-se gradualmente os dias de Israel morrer. Chamou assim seu filho José e disse-lhe: “Se eu tiver achado favor aos teus olhos, então, por favor, coloca tua mão debaixo da minha coxa, e tens de usar de benevolência e de fidedignidade^&#42;1^ para comigo. (Por favor, não me enterres no Egito.)

[NOTE]
====
. Ou “e de verdade; e de fidelidade”. Hebr.: we·’eméth.
====

[[v1-47-30]]

^<<v1-47-30,30>>^ E tenho de ficar deitado com os meus pais, e tens de transportar-me para fora do Egito e enterrar-me no sepulcro deles.” Portanto, ele disse: “Eu mesmo farei de acordo com a tua palavra.”

[[v1-47-31]]

^<<v1-47-31,31>>^ Ele disse então: “Jura-me.” De modo que lhe jurou. Israel debruçou-se então sobre a cabeceira do seu leito.^&#42;1^

[NOTE]
====
. “Leito.” Hebr.: ham·mit·táh; LXX: “E Israel adorava sobre (encostou-se no) o alto de seu bordão.” “Bordão” ou “vara” (hebr.: mat·téh, como em 38:25), e “cama” ou “leito” (hebr.: mit·táh, como em 48:2), têm consoantes idênticas, e quando não têm sinais vocálicos podem ser lidos de um modo ou de outro.
====

'''

xref:001-genesis/001-genesis-046.adoc#v1-46-0[&#60; Capítulo Anterior] | <<v1-47-0,Topo>> | xref:001-genesis/001-genesis-048.adoc#v1-48-0[Próximo Capítulo &#62;]