include::./index.adoc[]

[[v1-17-0]]
=== Gênesis, 17
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v1-17-1]]

^<<v1-17-1,1>>^ Quando Abrão atingiu a idade de noventa e nove anos, então apareceu Jeová a Abrão e lhe disse: “Eu sou o Deus Todo-poderoso.^&#42;1^ Anda diante de mim e mostra-te sem defeito.

[NOTE]
====
. “Deus Todo-poderoso.” Hebr.: ’El Shad·daí.
====

[[v1-17-2]]

^<<v1-17-2,2>>^ E vou fazer o meu pacto entre mim e ti, para multiplicar-te muitíssimo.”

[[v1-17-3]]

^<<v1-17-3,3>>^ Em vista disso, Abrão lançou-se com a face [por terra], e Deus^&#42;1^ continuou a falar com ele, dizendo:

[NOTE]
====
. Hebr.: ’Elo·hím, pl., sem o artigo definido.
====

[[v1-17-4]]

^<<v1-17-4,4>>^ “Quanto a mim, eis que meu pacto é contigo, e tu te tornarás certamente pai duma multidão de nações.

[[v1-17-5]]

^<<v1-17-5,5>>^ E não te chamarás mais pelo nome de Abrão,^&#42;1^ e teu nome tem de tornar-se Abraão,^&#42;2^ porque vou fazer-te pai duma multidão de nações.

[NOTE]
====
. Significando “Pai de Exaltação”. Hebr.: ’Av·rám.
. Significando “Pai Duma Multidão”. Hebr.: ’Av·ra·hám.
====

[[v1-17-6]]

^<<v1-17-6,6>>^ E vou fazer-te muitíssimo fecundo e vou fazer que te tornes nações, e reis sairão de ti.

[[v1-17-7]]

^<<v1-17-7,7>>^ “E vou cumprir meu pacto entre mim e ti, e teu descendente depois de ti, segundo as suas gerações, como pacto por tempo indefinido, a fim de mostrar-me Deus^&#42;1^ para ti e para o teu descendente depois de ti.

[NOTE]
====
. “[Mostrar-] me Deus.” Lit.: “para um Deus”. Hebr.: lE’·lo·hím, pl., sem o artigo definido.
====

[[v1-17-8]]

^<<v1-17-8,8>>^ E a ti e a teu descendente depois de ti vou dar a terra das tuas residências como forasteiro, sim, toda a terra de Canaã, como propriedade por tempo indefinido; e vou mostrar-me Deus para eles.”

[[v1-17-9]]

^<<v1-17-9,9>>^ E Deus disse mais a Abraão: “Quanto a ti, hás de guardar o meu pacto, tu e teu descendente depois de ti, segundo as suas gerações.

[[v1-17-10]]

^<<v1-17-10,10>>^ Este é o meu pacto que guardareis entre mim e vós, até mesmo teu descendente depois de ti: Cada macho vosso terá de ser circuncidado.

[[v1-17-11]]

^<<v1-17-11,11>>^ E tereis de ser circuncidados na carne dos vossos prepúcios, e isso terá de servir de sinal do pacto entre mim e vós.

[[v1-17-12]]

^<<v1-17-12,12>>^ E cada macho vosso, aos oito dias de idade, terá de ser circuncidado, segundo as vossas gerações, todo o nascido na casa^&#42;1^ e todo o comprado por dinheiro^&#42;2^ de qualquer estrangeiro que não procede de teu descendente.

[NOTE]
====
. Ou “todo filho de escravo”.
. Lit.: “prata”. Hebr.: ké·sef.
====

[[v1-17-13]]

^<<v1-17-13,13>>^ Cada homem nascido na tua casa e cada homem comprado por teu dinheiro, sem falta terá de ser circuncidado; e o meu pacto na vossa carne terá de servir de pacto por tempo indefinido.

[[v1-17-14]]

^<<v1-17-14,14>>^ E o macho incircunciso, que não fizer circuncidar a carne de seu prepúcio, sim, esta alma terá de ser decepada do seu povo. Violou o meu pacto.”

[[v1-17-15]]

^<<v1-17-15,15>>^ E Deus prosseguiu, dizendo a Abraão: “Quanto a Sarai, tua esposa, não deves chamá-la pelo nome de Sarai,^&#42;1^ porque Sara^&#42;2^ é o seu nome.

[NOTE]
====
. Significando “Contenciosa”. Hebr.: Sa·raí.
. Significando “Princesa”. Hebr.: Sa·ráh.
====

[[v1-17-16]]

^<<v1-17-16,16>>^ E vou abençoá-la e também dar-te dela um filho; e vou abençoá-la e ela se tornará nações; reis de povos procederão dela.”

[[v1-17-17]]

^<<v1-17-17,17>>^ Em vista disso, Abraão lançou-se com a face [por terra], e começou a rir-se e a dizer no seu coração: “Nascerá um filho a um homem de cem anos de idade, e dará à luz Sara, sim, uma mulher de noventa anos de idade?”

[[v1-17-18]]

^<<v1-17-18,18>>^ Abraão disse depois ao [verdadeiro] Deus:^&#42;1^ “Se Ismael tão-somente vivesse diante de ti!”

[NOTE]
====
. Veja Ap. 1F.
====

[[v1-17-19]]

^<<v1-17-19,19>>^ A isso Deus disse: “Sara, tua esposa, deveras te dará à luz um filho, e terás de chamá-lo pelo nome de Isaque.^&#42;1^ E vou estabelecer com ele o meu pacto como pacto por tempo indefinido para o seu descendente depois dele.

[NOTE]
====
. Significando “Riso”. Hebr.: Yits·hháq; um exemplo de onomatopéia, em que os sons sugerem o sentido.
====

[[v1-17-20]]

^<<v1-17-20,20>>^ Mas, quanto a Ismael, eu te ouvi. Eis que vou abençoá-lo e fazê-lo fecundo, e vou multiplicá-lo muitíssimo. Ele produzirá certamente doze maiorais,^&#42;1^ e eu vou fazer dele uma grande nação.

[NOTE]
====
. Ou “nases”. Hebr.: nesi·’ím; Vg: “duques; líderes”; LXX: “nações”.
====

[[v1-17-21]]

^<<v1-17-21,21>>^ No entanto, meu pacto eu estabelecerei com Isaque, que Sara te dará à luz neste tempo designado no ano que vem.”

[[v1-17-22]]

^<<v1-17-22,22>>^ Com isso, Deus acabou de falar com ele e ascendeu [de perto] de Abraão.

[[v1-17-23]]

^<<v1-17-23,23>>^ Abraão passou a tomar então Ismael, seu filho, e todos os homens nascidos na sua casa, e todo o comprado por dinheiro seu, cada macho dentre os homens da casa de Abraão, e neste mesmo dia foi circuncidar a carne dos seus prepúcios, assim como Deus lhe falara.

[[v1-17-24]]

^<<v1-17-24,24>>^ E Abraão tinha noventa e nove anos de idade quando lhe foi circuncidada a carne do prepúcio.

[[v1-17-25]]

^<<v1-17-25,25>>^ E Ismael, seu filho, tinha treze anos de idade quando lhe foi circuncidada a carne do prepúcio.

[[v1-17-26]]

^<<v1-17-26,26>>^ Neste mesmo dia foi circuncidado Abraão, e também Ismael, seu filho.

[[v1-17-27]]

^<<v1-17-27,27>>^ E todos os homens de sua casa, todo o nascido na casa e todo o comprado por dinheiro dum estrangeiro, foram circuncidados com ele.

'''

xref:001-genesis/001-genesis-016.adoc#v1-16-0[&#60; Capítulo Anterior] | <<v1-17-0,Topo>> | xref:001-genesis/001-genesis-018.adoc#v1-18-0[Próximo Capítulo &#62;]