include::./index.adoc[]

[[v1-37-0]]
=== Gênesis, 37
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v1-37-1]]

^<<v1-37-1,1>>^ E Jacó continuou a morar na terra das residências como forasteiro de seu pai, na terra de Canaã.

[[v1-37-2]]

^<<v1-37-2,2>>^ Esta é a história de Jacó.
José, aos dezessete anos de idade, estava zelando as ovelhas^&#42;1^ com os seus irmãos, no meio do rebanho, e sendo apenas rapaz, estava com os filhos de Bila e os filhos de Zilpa, esposas de seu pai. José trouxe então um relato mau sobre eles a seu pai.

[NOTE]
====
. Ou “estava-se associando”.
====

[[v1-37-3]]

^<<v1-37-3,3>>^ E Israel amava a José mais do que a todos os seus outros filhos, porque era o filho da sua velhice; e mandou fazer para ele uma comprida túnica listrada, tipo camisão.

[[v1-37-4]]

^<<v1-37-4,4>>^ Quando seus irmãos chegaram a ver que seu pai o amava mais do que a todos os seus irmãos, começaram a odiá-lo e não eram capazes de falar pacificamente com ele.

[[v1-37-5]]

^<<v1-37-5,5>>^ Mais tarde, José teve um sonho e o contou a seus irmãos, e eles acharam [nisso] razão adicional para o odiarem.

[[v1-37-6]]

^<<v1-37-6,6>>^ E ele prosseguiu, dizendo-lhes: “Escutai, por favor, este sonho que tive.

[[v1-37-7]]

^<<v1-37-7,7>>^ Pois bem, estávamos amarrando feixes no meio do campo, quando, eis que o meu feixe se levantou e também ficou ereto, e eis que os vossos feixes passaram a rodeá-lo e a curvar-se diante do meu feixe.”

[[v1-37-8]]

^<<v1-37-8,8>>^ E seus irmãos começaram a dizer-lhe: “Hás de ser realmente rei sobre nós? ou: Hás de dominar realmente sobre nós?” Acharam assim nova razão para o odiarem, por causa dos seus sonhos e das suas palavras.

[[v1-37-9]]

^<<v1-37-9,9>>^ Depois teve mais um sonho e o relatou aos seus irmãos, e disse: “Eis que tive mais uma vez um sonho, e eis que o sol, e a lua, e onze estrelas se curvaram diante de mim.”

[[v1-37-10]]

^<<v1-37-10,10>>^ Relatou-o então a seu pai, bem como a seus irmãos, e seu pai começou a censurá-lo e a dizer-lhe: “Que significa este sonho que tiveste? Havemos de vir eu, e também tua mãe e teus irmãos, e havemos de curvar-nos para a terra diante de ti?”

[[v1-37-11]]

^<<v1-37-11,11>>^ E seus irmãos ficaram com ciúmes dele; seu pai, porém, tomou nota da declaração.^&#42;1^

[NOTE]
====
. Ou “questão”.
====

[[v1-37-12]]

^<<v1-37-12,12>>^ Seus irmãos foram então apascentar o rebanho de seu pai^&#42;1^ perto de Siquém.

[NOTE]
====
. “O rebanho de seu pai”, MLXXSyVg. No M, a partícula hebr. ’eth, que modifica essas palavras, foi assinalada com pontos extraordinários pelos soferins, para indicar que essas palavras são duvidosas e devem ser omitidas. Se for assim, pode significar que os irmãos de José haviam ido alimentar-se. No v. 13, a palavra “rebanhos” não ocorre especificamente, mas o verbo é o mesmo que no v. 12. Veja Ap. 2A.
====

[[v1-37-13]]

^<<v1-37-13,13>>^ Depois de algum tempo, Israel disse a José: “Não estão teus irmãos cuidando [dos rebanhos] perto de Siquém? Vem e deixa-me enviar-te a eles.” A isso ele lhe disse: “Eis-me aqui!”

[[v1-37-14]]

^<<v1-37-14,14>>^ Disse-lhe então: “Vai, por favor. Vê se os teus irmãos estão sãos e salvos, e se o rebanho está são e salvo,^&#42;1^ e traze-me de volta informação.” Com isso o mandou embora da baixada de Hébron e ele seguiu para Siquém.

[NOTE]
====
. Lit.: “Vê a paz de teus irmãos e a paz do rebanho.”
====

[[v1-37-15]]

^<<v1-37-15,15>>^ Um homem o encontrou mais tarde, e eis que estava vagueando por um campo. O homem, pois, indagou dele, dizendo: “O que estás procurando?”

[[v1-37-16]]

^<<v1-37-16,16>>^ A isso ele disse: “É a meus irmãos que estou procurando. Informa-me, por favor: Onde estão cuidando dos rebanhos?”

[[v1-37-17]]

^<<v1-37-17,17>>^ E o homem continuou: “Partiram daqui, pois os ouvi dizer: ‘Vamos a Dotã.’” De modo que José foi atrás de seus irmãos e os achou em Dotã.

[[v1-37-18]]

^<<v1-37-18,18>>^ Ora, avistando-o de certa distância, e antes de ele poder chegar perto deles, começaram a conspirar astutamente contra ele para o entregarem à morte.

[[v1-37-19]]

^<<v1-37-19,19>>^ Disseram, pois, um ao outro: “Eis aqui vem aquele sonhador.^&#42;1^

[NOTE]
====
. “Aqui vem aquele sonhador.” Lit.: “O amo (senhor) de sonhos, aquele vem ali.”
====

[[v1-37-20]]

^<<v1-37-20,20>>^ E agora vinde e matemo-lo, e joguemo-lo numa das cisternas; e teremos de dizer que uma fera selvagem o devorou. Vejamos então o que será dos sonhos dele.”

[[v1-37-21]]

^<<v1-37-21,21>>^ Ouvindo isso Rubem, tentou livrá-lo da mão deles. De modo que disse: “Não golpeemos fatalmente a sua alma.”^&#42;1^

[NOTE]
====
. Lit.: “não lhe golpeemos a alma”.
====

[[v1-37-22]]

^<<v1-37-22,22>>^ E Rubem prosseguiu, dizendo-lhes: Não derrameis sangue. Jogai-o nesta cisterna que está no ermo e não deiteis mão violenta nele.” Seu objetivo era livrá-lo da mão deles, a fim de o restituir a seu pai.

[[v1-37-23]]

^<<v1-37-23,23>>^ Sucedeu, pois, assim que José veio ter com seus irmãos, que eles despiram José da sua túnica comprida, sim, da comprida túnica listrada que usava;

[[v1-37-24]]

^<<v1-37-24,24>>^ depois tomaram-no e jogaram-no na cisterna. Naquele tempo a cisterna estava vazia; não havia água nela.

[[v1-37-25]]

^<<v1-37-25,25>>^ Sentaram-se então para comer pão. Quando levantaram seus olhos e foram olhar, ora, eis que vinha uma caravana de ismaelitas desde Gileade, e seus camelos carregavam ládano, e bálsamo,^&#42;1^ e casca resinosa, indo levá-los para baixo ao Egito.

[NOTE]
====
. Isto é, de Gileade.
====

[[v1-37-26]]

^<<v1-37-26,26>>^ Judá disse então aos seus irmãos: “Que lucro haveria caso matássemos nosso irmão e encobríssemos seu sangue?

[[v1-37-27]]

^<<v1-37-27,27>>^ Vinde e vendamo-lo aos ismaelitas, e não deitemos mão nele. Afinal de contas, ele é nosso irmão, nossa carne.” Escutaram assim seu irmão.

[[v1-37-28]]

^<<v1-37-28,28>>^ Passavam então homens, mercadores midianitas. Portanto, puxaram e levantaram José para fora da cisterna, e venderam então José aos ismaelitas por vinte moedas de prata. Estes, por fim, levaram José ao Egito.

[[v1-37-29]]

^<<v1-37-29,29>>^ Rubem voltou mais tarde à cisterna, e eis que José não estava na cisterna. Rasgou, por isso, as suas vestes.

[[v1-37-30]]

^<<v1-37-30,30>>^ Voltando aos outros irmãos seus, exclamou: “O menino desapareceu! E eu — para onde é que irei eu?”

[[v1-37-31]]

^<<v1-37-31,31>>^ No entanto, tomaram a túnica comprida de José e abateram um bode, e mergulharam a túnica comprida repetidas vezes no sangue.

[[v1-37-32]]

^<<v1-37-32,32>>^ Depois enviaram a comprida túnica listrada e a fizeram levar a seu pai, e disseram: “Isto é o que encontramos. Examina, por favor, se é a túnica comprida de teu filho, ou não.”

[[v1-37-33]]

^<<v1-37-33,33>>^ E ele foi examiná-la e exclamou: “É a túnica comprida de meu filho! Uma fera selvagem deve tê-lo devorado! José está certamente dilacerado!”

[[v1-37-34]]

^<<v1-37-34,34>>^ Nisso Jacó rasgou as suas capas e pôs serapilheira em volta dos quadris, e pranteou muitos dias pelo seu filho.

[[v1-37-35]]

^<<v1-37-35,35>>^ E todos os seus filhos e todas as suas filhas se levantavam para consolá-lo, mas ele se negava a ser consolado e dizia: “Pois descerei pranteando para meu filho ao Seol!”^&#42;1^ E seu pai continuava a chorar por ele.

[NOTE]
====
. “Ao Seol.” Hebr.: she’ó·lah; gr.: eis haí·dou; sir.: la·shiul; lat.: in in·fér·num; esta é a primeira ocorrência desta palavra. Veja Ap. 4B.
====

[[v1-37-36]]

^<<v1-37-36,36>>^ No entanto, os midianitas venderam-no ao Egito, a Potifar, oficial da corte de Faraó,^&#42;1^ chefe da guarda pessoal.

[NOTE]
====
. Veja 12:15 n.
====

'''

xref:001-genesis/001-genesis-036.adoc#v1-36-0[&#60; Capítulo Anterior] | <<v1-37-0,Topo>> | xref:001-genesis/001-genesis-038.adoc#v1-38-0[Próximo Capítulo &#62;]