include::./index.adoc[]

[[v1-49-0]]
=== Gênesis, 49
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v1-49-1]]

^<<v1-49-1,1>>^ Mais tarde, Jacó convocou os seus filhos e disse: “Ajuntai-vos, para que eu vos possa declarar o que vos acontecerá na parte final dos dias.

[[v1-49-2]]

^<<v1-49-2,2>>^ Reuni-vos e escutai, ó filhos de Jacó, sim, escutai a Israel, vosso pai.

[[v1-49-3]]

^<<v1-49-3,3>>^ “Rubem, tu és o meu primogênito, meu vigor e o princípio da minha faculdade de procriação, a excelência da dignidade e a excelência da força.

[[v1-49-4]]

^<<v1-49-4,4>>^ Tendo impetuosidade leviana como as águas,^&#42;1^ não te sobressaias, pois subiste à cama de teu pai. Naquele tempo profanaste o meu leito [conjugal]. Subiu nele!

[NOTE]
====
. Ou: “Havia leviandade como águas impetuosas.”
====

[[v1-49-5]]

^<<v1-49-5,5>>^ “Simeão e Levi são irmãos.^&#42;1^ Instrumentos de violência são as suas armas de matança.^&#42;2^

[NOTE]
====
. “Corujões; hienas”, segundo outros sinais vocálicos.
. “Armas de matança.” Alguns encaram a palavra hebr. aqui como ainda sem explicação. v. 5 na LXXBagster: “Simeão e Levi, irmãos, realizaram a injustiça de seu decepamento.”
====

[[v1-49-6]]

^<<v1-49-6,6>>^ Não entres no seu grupo íntimo, ó minha alma. Não te unas à sua congregação, ó minha disposição,^&#42;1^ porque na sua ira mataram homens^&#42;2^ e na sua arbitrariedade jarretaram touros.

[NOTE]
====
. “Minha glória”, MVg; LXX: “meu fígado”. Veja VT, Vol. II, 1952, pp. 358-362.
. Ou “um homem”. Hebr.: ’ish, possivelmente em sentido coletivo.
====

[[v1-49-7]]

^<<v1-49-7,7>>^ Maldita seja a sua ira, porque é cruel, e a sua fúria, porque age impiedosamente. Distribua-os eu por Jacó, mas espalhe-os eu em Israel.

[[v1-49-8]]

^<<v1-49-8,8>>^ “Quanto a ti, Judá, teus irmãos te elogiarão.Tua mão estará sobre a cerviz dos teus inimigos. Os filhos de teu pai se prostrarão diante de ti.

[[v1-49-9]]

^<<v1-49-9,9>>^ Judá é um leãozinho. Subirás certamente da presa, filho meu. Abaixa-se, espicha-se como o leão,^&#42;1^ e como a um leão,^&#42;2^ quem se atreve a acordá-lo?

[NOTE]
====
. “Como o leão.” Hebr.: ke’ar·yéh, o leão africano.
. “E como a um leão.” Hebr.: u·khela·ví’, o leão asiático.
====

[[v1-49-10]]

^<<v1-49-10,10>>^ O cetro^&#42;1^ não se afastará de Judá, nem o bastão de comandante^&#42;2^ de entre os seus pés,^&#42;3^ até que venha Siló;^&#42;4^ e a ele pertencerá a obediência dos povos.^&#42;5^

[NOTE]
====
. “Cetro.” Hebr.: shé·vet; lat.: scép·trum; gr.: ár·khon, “governante”.
. Ou “nem um comandante”. Hebr.: lo’ . . . u·mehho·qéq.
. Ou “de diante dele”. Veja Jg 5:27.
. “Siló.” Ou “aquele de quem é”. Hebr.: Shi·lóh, significando “Aquele de Quem É”, ou: “Aquele a Quem Pertence”; LXX: “as coisas guardadas para ele”; Vg: “aquele que há de ser enviado”.
. “E ele será a expectativa das nações”, LXXVg.
====

[[v1-49-11]]

^<<v1-49-11,11>>^ Prendendo seu jumento adulto a uma videira e a cria de sua própria jumenta a uma videira seleta,^&#42;1^ lavará certamente a sua vestimenta em vinho e a sua roupa no sangue das uvas.

[NOTE]
====
. Ou “uma videira com uvas escarlates”.
====

[[v1-49-12]]

^<<v1-49-12,12>>^ Seus olhos são vermelho-escuros do vinho e a brancura dos seus dentes é do leite.

[[v1-49-13]]

^<<v1-49-13,13>>^ “Zebulão residirá junto à costa marítima e estará junto à costa onde ancoram os navios;^&#42;1^ e sua parte remota será pelos lados de Sídon.

[NOTE]
====
. Ou “descarregam os navios”.
====

[[v1-49-14]]

^<<v1-49-14,14>>^ “Issacar é jumento de ossos fortes, deitando-se entre os dois alforjes.

[[v1-49-15]]

^<<v1-49-15,15>>^ E ele verá que o lugar de descanso é bom e que o país é agradável; e encurvará seu ombro para levar fardos e ficará sujeito a trabalho forçado de escravo.^&#42;1^

[NOTE]
====
. Ou “tornar-se-á escravo sob trabalho forçado”.
====

[[v1-49-16]]

^<<v1-49-16,16>>^ “Dã julgará seu povo como uma das tribos de Israel.

[[v1-49-17]]

^<<v1-49-17,17>>^ Mostre-se Dã uma serpente à beira da estrada, uma cobra cornuda à beira da vereda, que morde os talões do cavalo, de modo que o seu cavaleiro cai para trás.

[[v1-49-18]]

^<<v1-49-18,18>>^ Deveras aguardarei^&#42;1^ a salvação [procedente] de ti,^&#42;2^ ó Jeová.

[NOTE]
====
. Ou “aguardei”.
. “A salvação [procedente] de ti.” Hebr.: li·shu·‛oth·khá; esta é a primeira ocorrência deste substantivo. A palavra hebr. yeshu·‛áh, “salvação”, tem a mesma raiz que os nomes bíblicos de Jesua, Josué e Jesus.
====

[[v1-49-19]]

^<<v1-49-19,19>>^ “Quanto a Gade, uma guerrilha o acometerá, mas ele acometerá a retaguarda.

[[v1-49-20]]

^<<v1-49-20,20>>^ “De Aser será gordo o seu pão, e ele dará os petiscos de rei.

[[v1-49-21]]

^<<v1-49-21,21>>^ “Naftali é uma corça esbelta.^&#42;1^ Ele dá palavras de elegância.^&#42;2^

[NOTE]
====
. Ou “ágil”.
. Ou: “Ele estende cornos ramificados.”
====

[[v1-49-22]]

^<<v1-49-22,22>>^ “Broto^&#42;1^ duma árvore frutífera, José é broto duma árvore frutífera junto à fonte, que estende seus ramos^&#42;2^ por cima do muro.

[NOTE]
====
. Lit.: “filho”.
. Lit.: “filhas”.
====

[[v1-49-23]]

^<<v1-49-23,23>>^ Mas os arqueiros o hostilizavam e atiravam contra ele, e lhe tinham rancor.

[[v1-49-24]]

^<<v1-49-24,24>>^ Contudo, seu arco morava num lugar permanente e a força^&#42;1^ das suas mãos era ágil.^&#42;2^ Das mãos do Potentado de Jacó, dali provém o Pastor, a Pedra de Israel.

[NOTE]
====
. Lit.: “os braços”.
. Ou “lesta”.
====

[[v1-49-25]]

^<<v1-49-25,25>>^ Ele provém do Deus^&#42;1^ de teu pai e ele te ajudará; e ele está com o Todo-poderoso e te abençoará com as bênçãos dos céus acima, com as bênçãos da água de profundeza^&#42;2^ jazendo em baixo, com as bênçãos dos peitos e da madre.

[NOTE]
====
. “Do Deus de.” Hebr.: me·’Él.
. Ou “águas empoladas”. Vg: “abismo”, como em 1:2.
====

[[v1-49-26]]

^<<v1-49-26,26>>^ As bênçãos de teu pai serão deveras superiores às bênçãos dos montes sempiternos, ao ornamento^&#42;1^ dos morros que duram indefinidamente. Continuarão sobre a cabeça de José, sim, sobre o alto da cabeça do selecionado^&#42;2^ dentre os seus irmãos.

[NOTE]
====
. Ou “desejo; morada”.
. Ou “escolhido”. Hebr.: nezír; em Núm 6:2, 13, 18-20 foi traduzido por “nazireu”, significando “escolhido; dedicado; separado”.
====

[[v1-49-27]]

^<<v1-49-27,27>>^ “Benjamim continuará a dilacerar como lobo. De manhã comerá o animal apanhado e à noitinha repartirá o despojo.”

[[v1-49-28]]

^<<v1-49-28,28>>^ Todos estes são as doze tribos de Israel, e isto é o que o seu pai lhes falou ao abençoá-los. Ele os abençoou, a cada um segundo a sua própria bênção.

[[v1-49-29]]

^<<v1-49-29,29>>^ Depois lhes ordenou e lhes disse: “Estou sendo ajuntado ao meu povo. Enterrai-me com os meus pais na caverna que está no campo de Efrom, o hitita,

[[v1-49-30]]

^<<v1-49-30,30>>^ na caverna que está no campo de Macpela, que está defronte de Manre, na terra de Canaã, o campo que Abraão comprou de Efrom, o hitita, como propriedade duma sepultura.

[[v1-49-31]]

^<<v1-49-31,31>>^ Ali enterraram Abraão e Sara, sua esposa. Ali enterraram Isaque e Rebeca, sua esposa, e ali enterrei Léia.

[[v1-49-32]]

^<<v1-49-32,32>>^ O campo comprado^&#42;1^ e a caverna que está nele eram dos filhos de Hete.”

[NOTE]
====
. Lit.: “A compra do campo.”
====

[[v1-49-33]]

^<<v1-49-33,33>>^ Assim Jacó terminou de dar ordens aos seus filhos. Recolheu então os seus pés ao leito e expirou, e foi ajuntado ao seu povo.

'''

xref:001-genesis/001-genesis-048.adoc#v1-48-0[&#60; Capítulo Anterior] | <<v1-49-0,Topo>> | xref:001-genesis/001-genesis-050.adoc#v1-50-0[Próximo Capítulo &#62;]