include::./index.adoc[]

[[v1-50-0]]
=== Gênesis, 50
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v1-50-1]]

^<<v1-50-1,1>>^ José lançou-se então sobre a face de seu pai e rompeu em pranto sobre ele, e beijou-o.

[[v1-50-2]]

^<<v1-50-2,2>>^ Depois, José ordenou aos seus servos, os médicos, que embalsamassem seu pai. De modo que os médicos embalsamaram Israel,

[[v1-50-3]]

^<<v1-50-3,3>>^ e levaram com ele quarenta dias inteiros, pois levam costumeiramente tantos dias para o embalsamamento, e os egípcios continuavam a verter lágrimas por ele, por setenta dias.

[[v1-50-4]]

^<<v1-50-4,4>>^ Finalmente se passaram os dias de choro por ele, e José falou aos da casa de Faraó, dizendo: “Se eu, pois, tiver achado favor aos vossos olhos, falai, por favor, aos ouvidos de Faraó, dizendo:

[[v1-50-5]]

^<<v1-50-5,5>>^ ‘Meu pai me fez jurar, dizendo: “Eis que estou morrendo. Hás de enterrar-me na minha sepultura que escavei para mim na terra de Canaã.” E agora, por favor, deixa-me subir e enterrar meu pai, após o que estou disposto a voltar.’”

[[v1-50-6]]

^<<v1-50-6,6>>^ Faraó disse, portanto: “Sobe e enterra teu pai, assim como te fez jurar.”

[[v1-50-7]]

^<<v1-50-7,7>>^ José subiu, pois, para enterrar seu pai, e com ele subiram todos os servos de Faraó, os anciãos da sua casa e todos os anciãos da terra do Egito,

[[v1-50-8]]

^<<v1-50-8,8>>^ e todos os da casa de José, e seus irmãos, e os da casa de seu pai. Deixaram somente suas criancinhas, e seus rebanhos, e suas manadas na terra de Gósen.

[[v1-50-9]]

^<<v1-50-9,9>>^ Subiram também com ele tanto carros como cavaleiros, e o acampamento ficou muito numeroso.

[[v1-50-10]]

^<<v1-50-10,10>>^ Chegaram então à eira de Atade,^&#42;1^ que está na região do Jordão, e ali realizaram um grande e forte lamento, e ele prolongou os ritos de luto por seu pai por sete dias.

[NOTE]
====
. Lit.: “o Espinheiro”. Hebr.: ha·’A·tádh.
====

[[v1-50-11]]

^<<v1-50-11,11>>^ E os habitantes do país, os cananeus, chegaram a ver os ritos de luto na eira de Atade, e exclamaram: “Este é um grave luto para os egípcios!” É por isso que foi chamado pelo nome de Abel-Mizraim,^&#42;1^ que está na região do Jordão.

[NOTE]
====
. Significando “Luto dos Egípcios”. “Mizraim” é a palavra hebr. para egípcios. Veja 10:13.
====

[[v1-50-12]]

^<<v1-50-12,12>>^ E os seus filhos passaram a fazer-lhe exatamente como lhes mandara.

[[v1-50-13]]

^<<v1-50-13,13>>^ Seus filhos transportaram-no assim para a terra de Canaã e enterraram-no na caverna do campo de Macpela, o campo que Abraão comprara de Efrom, o hitita, como propriedade duma sepultura, defronte de Manre.

[[v1-50-14]]

^<<v1-50-14,14>>^ Depois disso, José voltou ao Egito, ele e seus irmãos, e todos os que tinham subido com ele para enterrar seu pai, após ter enterrado seu pai.

[[v1-50-15]]

^<<v1-50-15,15>>^ Quando os irmãos de José viram que seu pai estava morto,^&#42;1^ começaram a dizer: “Pode ser que José nos tenha rancor, e seguramente nos pagará de volta por todo o mal que lhe fizemos.”

[NOTE]
====
. “Os irmãos de José viram que seu pai havia morrido e estavam com medo”, Sy; Vg: “Agora que estava morto, seus irmãos estavam com medo.”
====

[[v1-50-16]]

^<<v1-50-16,16>>^ Expressaram assim uma ordem a José, nas seguintes palavras: “Teu pai deu ordem, antes de sua morte, dizendo:

[[v1-50-17]]

^<<v1-50-17,17>>^ ‘Isto é o que haveis de dizer a José: “Rogo-te, perdoa, por favor, a revolta de teus irmãos e o pecado deles, por te terem feito o mal.”’ E agora, por favor, perdoa a revolta dos servos do Deus de teu pai.” E José rompeu em pranto quando lhe falaram.

[[v1-50-18]]

^<<v1-50-18,18>>^ A seguir, seus irmãos vieram também e lançaram-se diante dele, e disseram: “Eis que somos como teus escravos!”^&#42;1^

[NOTE]
====
. Ou “servos”.
====

[[v1-50-19]]

^<<v1-50-19,19>>^ José disse-lhes então: “Não tenhais medo, pois, estou eu no lugar de Deus?

[[v1-50-20]]

^<<v1-50-20,20>>^ Quanto a vós, tencionastes o mal contra mim. Deus tencionou-o para o bem, com o objetivo de agir assim como no dia de hoje, para preservar vivo a muito povo.

[[v1-50-21]]

^<<v1-50-21,21>>^ Agora, pois, não tenhais medo. Eu mesmo suprirei alimento a vós e às vossas criancinhas.” Assim os consolou e falou tranqüilizadoramente com eles.^&#42;1^

[NOTE]
====
. Lit.: “falou-lhes ao coração”.
====

[[v1-50-22]]

^<<v1-50-22,22>>^ E José continuou a morar no Egito, ele e a casa de seu pai; e José viveu cento e dez anos.

[[v1-50-23]]

^<<v1-50-23,23>>^ E José chegou a ver a terceira geração^&#42;1^ dos filhos de Efraim, também os filhos de Maquir, filho de Manassés. Eles nasceram sobre os joelhos de José.

[NOTE]
====
. Lit.: “filhos dos terceiros [gerados]”.
====

[[v1-50-24]]

^<<v1-50-24,24>>^ Por fim, José disse a seus irmãos: “Estou morrendo; mas Deus, sem falta, voltará a sua atenção para vós, e certamente vos fará subir desta terra para a terra que jurou^&#42;1^ a Abraão, a Isaque e a Jacó.”

[NOTE]
====
. Ou “terra que prometeu sob juramento”.
====

[[v1-50-25]]

^<<v1-50-25,25>>^ José fez por isso os filhos de Israel jurar, dizendo: “Deus, sem falta, voltará a sua atenção para vós. Portanto, tereis de levar meus ossos para fora daqui.”

[[v1-50-26]]

^<<v1-50-26,26>>^ Depois, José morreu à idade de cento e dez anos; e fizeram-no embalsamar, e ele foi posto num ataúde, no Egito.

'''

xref:001-genesis/001-genesis-049.adoc#v1-49-0[&#60; Capítulo Anterior] | <<v1-50-0,Topo>> | xref:002-exodo/002-exodo-001.adoc#v2-1-0[Próximo Capítulo &#62;]