include::./index.adoc[]

[[v1-19-0]]
=== Gênesis, 19
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v1-19-1]]

^<<v1-19-1,1>>^ Ora, os dois anjos chegaram a Sodoma ao anoitecer, e Ló estava sentado no portão de Sodoma. Avistando-os Ló, levantou-se para ir ao seu encontro e curvou-se com o rosto por terra.

[[v1-19-2]]

^<<v1-19-2,2>>^ E passou a dizer: “Ora, por favor, meus senhores, desviai-vos, por favor, para a casa do vosso servo e pernoitai ali, e lavem-se os vossos pés. Então tereis de levantar-vos cedo e seguir o vosso caminho.” A isto disseram: “Não, mas pernoitaremos na praça pública.”

[[v1-19-3]]

^<<v1-19-3,3>>^ Mas instava com eles, de modo que se desviaram para ele e entraram na sua casa. Preparou-lhes então um banquete e cozeu pães não fermentados, e eles passaram a comer.

[[v1-19-4]]

^<<v1-19-4,4>>^ Antes de se poderem deitar, os homens da cidade, os homens de Sodoma, cercaram a casa, desde o rapaz até o velho, todo o povo numa só turba.^&#42;1^

[NOTE]
====
. Ou “de cada canto”.
====

[[v1-19-5]]

^<<v1-19-5,5>>^ E chamavam a Ló e diziam-lhe: “Onde estão os homens que foram ter contigo hoje à noite? Traze-os para fora a nós, para que tenhamos relações com eles.”

[[v1-19-6]]

^<<v1-19-6,6>>^ Por fim, Ló saiu a eles à entrada, mas fechou a porta atrás de si.

[[v1-19-7]]

^<<v1-19-7,7>>^ Disse então: “Por favor, meus irmãos, não procedais mal.

[[v1-19-8]]

^<<v1-19-8,8>>^ Por favor, eis que tenho duas filhas que nunca tiveram relações com um homem. Por favor, deixai-me trazê-las para fora a vós. Fazei então com elas o que parecer bem aos vossos olhos. Somente não façais nada a esses homens, porque foi por isso que vieram sob a sombra do meu teto.”

[[v1-19-9]]

^<<v1-19-9,9>>^ A isso disseram: “Sai daí!” E acrescentaram: “Este homem solitário veio para cá residir como forasteiro e ainda assim quer fazer-se realmente de juiz. Agora vamos fazer a ti pior do que a eles.” E arremessaram-se fortemente contra o homem, contra Ló, e chegaram-se para arrombar a porta.

[[v1-19-10]]

^<<v1-19-10,10>>^ De modo que os homens estenderam as suas mãos e puxaram Ló para dentro da casa, e fecharam a porta.

[[v1-19-11]]

^<<v1-19-11,11>>^ Mas feriram de cegueira os homens que estavam à entrada da casa, do menor ao maior, de modo que se afadigaram tentando achar a entrada.

[[v1-19-12]]

^<<v1-19-12,12>>^ Os homens disseram então a Ló: “Tens mais alguém aqui? Genro, e teus filhos, e tuas filhas, e todos os que são teus na cidade, leva-os para fora do lugar!

[[v1-19-13]]

^<<v1-19-13,13>>^ Pois vamos arruinar este lugar, porque o clamor contra eles tornou-se alto perante Jeová, de modo que Jeová nos enviou para arruinar a cidade.”^&#42;1^

[NOTE]
====
. Lit.: “ela”, hebr. fem., referindo-se à “cidade”, fem.
====

[[v1-19-14]]

^<<v1-19-14,14>>^ Ló saiu, por isso, e começou a falar com os seus genros, que haviam de tomar^&#42;1^ suas filhas, e dizia-lhes: “Levantai-vos! Saí deste lugar, porque Jeová vai arruinar a cidade!” Mas ele parecia aos olhos de seus genros como quem estava brincando.

[NOTE]
====
. Ou “que pretendiam tomar”.
====

[[v1-19-15]]

^<<v1-19-15,15>>^ No entanto, ao subir a alva, os anjos ficaram insistentes com Ló, dizendo: “Levanta-te! Toma tua esposa e as duas filhas tuas que se acham aqui, para que não sejas arrasado no erro da cidade!”

[[v1-19-16]]

^<<v1-19-16,16>>^ Demorando-se ele ainda, então, na compaixão de Jeová para com ele, os homens agarraram-lhe a mão, e a mão de sua esposa, e as mãos de suas duas filhas, e passaram a levá-lo para fora e a deixá-lo fora da cidade.

[[v1-19-17]]

^<<v1-19-17,17>>^ E sucedeu que, assim que os tinham levado para fora, aos arrabaldes, começou^&#42;1^ a dizer: “Escapa-te, por tua alma! Não olhes para trás e não pares em todo o Distrito!^&#42;2^ Escapa para a região montanhosa, para que não sejas arrasado!”

[NOTE]
====
. “Começaram”, LXXSyVgc.
. Ou “a Bacia”. Veja 13:10 n.: “Distrito.”
====

[[v1-19-18]]

^<<v1-19-18,18>>^ Ló disse-lhes então: “Não isso, por favor, Jeová!^&#42;1^

[NOTE]
====
. Uma das 134 mudanças de YHWH para ’Adho·naí feitas pelos escribas. Veja Ap. 1B.
====

[[v1-19-19]]

^<<v1-19-19,19>>^ Ora, por favor, teu servo achou favor aos teus olhos, de modo que estás magnificando a tua benevolência^&#42;1^ de que usas para comigo, para preservar viva a minha alma, mas eu — eu não posso escapar para a região montanhosa, para que não se apegue a mim a calamidade e eu certamente morra.

[NOTE]
====
. Ou “o teu amor leal”. Hebr.: hhas·dekhá.
====

[[v1-19-20]]

^<<v1-19-20,20>>^ Ora, por favor, esta cidade está perto para se fugir para lá, e é uma coisa pequena. Por favor, posso escapar-me para lá — não é uma coisa pequena? — e minha alma viverá.”

[[v1-19-21]]

^<<v1-19-21,21>>^ Ele lhe disse então: “Eis que também neste ponto tenho deveras consideração^&#42;1^ para contigo, não subvertendo a cidade de que falaste.

[NOTE]
====
. Ou “nesta coisa . . . consideração”.
====

[[v1-19-22]]

^<<v1-19-22,22>>^ Apressa-te! Escapa para lá, porque não posso fazer coisa alguma até chegares lá!” É por isso que chamou a cidade pelo nome de Zoar.^&#42;1^

[NOTE]
====
. Significando “Pequenez”.
====

[[v1-19-23]]

^<<v1-19-23,23>>^ O sol já tinha saído sobre a terra quando Ló chegou a Zoar.

[[v1-19-24]]

^<<v1-19-24,24>>^ Jeová fez então chover enxofre e fogo sobre Sodoma e sobre Gomorra, da parte de Jeová, desde os céus.

[[v1-19-25]]

^<<v1-19-25,25>>^ Assim foi subverter essas cidades, sim, o Distrito inteiro, e todos os habitantes das cidades e as plantas do solo.

[[v1-19-26]]

^<<v1-19-26,26>>^ E a esposa dele começou a olhar em volta, por detrás dele,^&#42;1^ e ela se tornou uma coluna de sal.

[NOTE]
====
. “Olhar por detrás dela”, SyVg.
====

[[v1-19-27]]

^<<v1-19-27,27>>^ Ora, Abraão se encaminhou de manhã cedo para o lugar onde tinha estado em pé diante de Jeová.

[[v1-19-28]]

^<<v1-19-28,28>>^ Olhou então para baixo, para Sodoma e Gomorra, e para todo o país do Distrito, e viu um espetáculo. Ora, eis que subia fumaça grossa da terra, como a fumaça grossa dum forno de calcinação!

[[v1-19-29]]

^<<v1-19-29,29>>^ E aconteceu que, quando Deus arruinou as cidades do Distrito, Deus lembrou-se de Abraão, tomando medidas para mandar Ló para fora da demolição quando subverteu as cidades entre as quais Ló havia morado.

[[v1-19-30]]

^<<v1-19-30,30>>^ Mais tarde, Ló subiu de Zoar e começou a morar na região montanhosa, e com ele suas duas filhas, porque ficou com medo de morar em Zoar. Começou assim a morar numa caverna, ele e suas duas filhas.

[[v1-19-31]]

^<<v1-19-31,31>>^ E a primogênita passou a dizer à mais jovem: “Nosso pai já é velho e não há homem no país para ter relações conosco segundo o costume de toda a terra.

[[v1-19-32]]

^<<v1-19-32,32>>^ Vem, demos de beber vinho a nosso pai e deitemo-nos com ele, e preservemos descendência a nosso pai.”

[[v1-19-33]]

^<<v1-19-33,33>>^ Durante aquela noite, pois, foram dar de beber vinho a seu pai; então entrou a primogênita e se deitou com o seu pai, mas ele não percebeu nem quando ela se deitou nem quando se levantou.^&#42;1^

[NOTE]
====
. “Nem quando se levantou.” Hebr.: u·vequ·máh. No M, o segundo Vau foi assinalado com um ponto extraordinário pelos soferins (escribas), talvez para trazer à atenção a grafia. Veja Ap. 2A.
====

[[v1-19-34]]

^<<v1-19-34,34>>^ E no dia seguinte sucedeu que a primogênita disse à mais jovem: “Eis que na noite passada me deitei com o meu pai. Demos-lhe de beber vinho também hoje à noite. Depois entra, deita-te com ele, e preservemos descendência a nosso pai.”

[[v1-19-35]]

^<<v1-19-35,35>>^ Assim, também durante aquela noite deram de beber repetidamente vinho a seu pai; a mais jovem levantou-se então e deitou-se com ele, mas ele não percebeu nem quando ela se deitou nem quando se levantou.

[[v1-19-36]]

^<<v1-19-36,36>>^ E ambas as filhas de Ló ficaram grávidas de seu pai.

[[v1-19-37]]

^<<v1-19-37,37>>^ A seu tempo, a primogênita tornou-se mãe dum filho e chamou-o pelo nome de Moabe.^&#42;1^ Ele é o pai de Moabe, até o dia de hoje.

[NOTE]
====
. Significando “De Pai”. Hebr.: Moh·’áv. LXX acrescenta: “dizendo: ‘De meu pai’”.
====

[[v1-19-38]]

^<<v1-19-38,38>>^ Quanto à mais jovem, também ela deu à luz um filho e chamou-o então pelo nome de Ben-Ami.^&#42;1^ Ele é o pai dos filhos de Amom, até o dia de hoje.

[NOTE]
====
. Significando “Filho do Meu Povo”, quer dizer, filho dos meus parentes; não de estrangeiros tais como os sodomitas. Hebr.: Ben-‛am·mí.
====

'''

xref:001-genesis/001-genesis-018.adoc#v1-18-0[&#60; Capítulo Anterior] | <<v1-19-0,Topo>> | xref:001-genesis/001-genesis-020.adoc#v1-20-0[Próximo Capítulo &#62;]