include::./index.adoc[]

[[v1-24-0]]
=== Gênesis, 24
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v1-24-1]]

^<<v1-24-1,1>>^ Ora, Abraão era velho, avançado em anos;^&#42;1^ e Jeová abençoara Abraão em tudo.

[NOTE]
====
. Lit.: “dias”.
====

[[v1-24-2]]

^<<v1-24-2,2>>^ Por isso, Abraão disse ao seu servo, ao mais velho da sua casa, que administrava^&#42;1^ tudo o que possuía: “Por favor, põe a tua mão debaixo da minha coxa,

[NOTE]
====
. “Que administrava.” Lit.: “que governava”. Hebr.: ham·mo·shél; quer dizer, aquele que servia como mordomo, como administrador da casa. Veja Lu 12:42 n.
====

[[v1-24-3]]

^<<v1-24-3,3>>^ visto que tenho de fazer-te jurar por Jeová, o Deus dos céus e o Deus da terra, que não tomarás para meu filho esposa dentre as filhas dos cananeus, entre os quais estou morando,

[[v1-24-4]]

^<<v1-24-4,4>>^ mas que irás ao meu país e à minha parentela, e tomarás certamente uma esposa para meu filho, para Isaque.”

[[v1-24-5]]

^<<v1-24-5,5>>^ No entanto, o servo disse-lhe: “E se a mulher não quiser vir comigo para esta terra? Tenho de certificar-me de retornar teu filho à terra de que saíste?”

[[v1-24-6]]

^<<v1-24-6,6>>^ A isso lhe disse Abraão: “Guarda-te de que não retornes meu filho para lá.

[[v1-24-7]]

^<<v1-24-7,7>>^ Jeová, o Deus dos céus, que me tirou da casa de meu pai e da terra da minha parentela,^&#42;1^ e que me falou e que me jurou, dizendo: ‘Vou dar esta terra à tua descendência’, enviará o seu anjo adiante de ti e certamente tomarás dali uma esposa para meu filho.

[NOTE]
====
. Ou “lar”.
====

[[v1-24-8]]

^<<v1-24-8,8>>^ Mas, se a mulher não quiser vir contigo, então terás ficado livre deste juramento que me fizeste. Somente não deves retornar meu filho para lá.”

[[v1-24-9]]

^<<v1-24-9,9>>^ Com isso, o servo pôs a sua mão debaixo da coxa de Abraão, seu amo, e jurou-lhe com respeito a este assunto.

[[v1-24-10]]

^<<v1-24-10,10>>^ O servo tomou assim dez camelos dos camelos do seu amo e passou a ir com toda sorte de coisa boa do seu amo na sua mão. Levantou-se então e pôs-se a caminho para a Mesopotâmia,^&#42;1^ para a cidade de Naor.

[NOTE]
====
. “Mesopotâmia” (significando “[Terra] Entre Rios”), LXXVg; hebr.: ’Arám Na·hará·yim, significando “Arã dos Dois Rios”.
====

[[v1-24-11]]

^<<v1-24-11,11>>^ Por fim, fez os camelos ajoelhar-se, fora da cidade, junto a um poço de água, por volta do anoitecer,pela hora em que costumavam sair as mulheres que tiravam água.

[[v1-24-12]]

^<<v1-24-12,12>>^ E ele passou a dizer: “Jeová, Deus de meu amo Abraão, por favor, faze que aconteça diante de mim neste dia, e usa de benevolência para com o meu amo Abraão.

[[v1-24-13]]

^<<v1-24-13,13>>^ Eis que me acho de pé junto a uma fonte de água e vêm saindo as filhas dos homens da cidade para tirar água.

[[v1-24-14]]

^<<v1-24-14,14>>^ O que tem de acontecer é que a moça a quem eu disser: ‘Por favor, inclina o teu cântaro para que eu possa beber’, e que deveras disser: ‘Bebe, e darei de beber também aos teus camelos’, esta é a que tens de determinar ao teu servo, a Isaque; e deste modo deixa-me saber que usaste de amor leal para com o meu amo.”

[[v1-24-15]]

^<<v1-24-15,15>>^ Bem, sucedeu que, antes de ele ter acabado de falar, ora, eis que saía Rebeca, que nascera a Betuel, filho de Milca, esposa de Naor, irmão de Abraão, e ela tinha seu cântaro no ombro.

[[v1-24-16]]

^<<v1-24-16,16>>^ Ora, a moça^&#42;1^ era de aparência muito atraente, era virgem,^&#42;2^ e nenhum homem tivera relações sexuais com ela; e ela desceu até a fonte e começou a encher o seu cântaro, e depois subiu.

[NOTE]
====
. “Ora, a moça.” Hebr.: wehan·na·‛ará.
. “Virgem.” Hebr.: bethu·láh; gr.: par·thé·nos; lat.: vír·go.
====

[[v1-24-17]]

^<<v1-24-17,17>>^ O servo correu imediatamente ao seu encontro e disse: “Por favor, dá-me um gole de água do teu cântaro.”

[[v1-24-18]]

^<<v1-24-18,18>>^ Ela, por sua vez, disse: “Bebe, meu senhor.” Com isso ela abaixou depressa o seu cântaro sobre a sua mão e deu-lhe de beber.

[[v1-24-19]]

^<<v1-24-19,19>>^ Acabando de dar-lhe de beber, ela disse: “Tirarei também água para os teus camelos até que acabem de beber.”

[[v1-24-20]]

^<<v1-24-20,20>>^ De modo que ela esvaziou depressa o seu cântaro no bebedouro e correu ainda várias vezes ao poço para tirar água, e continuou a tirar [água] para todos os seus camelos.

[[v1-24-21]]

^<<v1-24-21,21>>^ Durante todo esse tempo o homem fitava-a admirado, mantendo-se calado para saber se Jeová fizera sua viagem bem sucedida ou não.

[[v1-24-22]]

^<<v1-24-22,22>>^ Por conseguinte, sucedeu que, quando os camelos tinham acabado de beber, o homem tomou uma argola de ouro para as narinas, de meio siclo^&#42;1^ de peso, e duas pulseiras para as mãos dela, do peso de dez siclos de ouro,

[NOTE]
====
. Um siclo pesava 11,4 g.
====

[[v1-24-23]]

^<<v1-24-23,23>>^ e prosseguiu, dizendo: “De quem és filha? Declara-me, por favor: Há um lugar na casa de teu pai para pernoitarmos?”

[[v1-24-24]]

^<<v1-24-24,24>>^ A isso ela lhe disse: “Sou filha de Betuel, filho de Milca, que ela deu à luz a Naor.”

[[v1-24-25]]

^<<v1-24-25,25>>^ E disse-lhe mais: “Temos tanto palha como muita forragem, também um lugar para se pernoitar.”

[[v1-24-26]]

^<<v1-24-26,26>>^ E o homem passou a inclinar-se e a prostrar-se diante de Jeová,

[[v1-24-27]]

^<<v1-24-27,27>>^ e a dizer: “Bendito seja Jeová, o Deus de meu amo Abraão, que não abandonou a sua benevolência e a sua fidedignidade para com o meu amo. Estando eu em caminho, Jeová me guiou à casa dos irmãos do meu amo.”

[[v1-24-28]]

^<<v1-24-28,28>>^ E a moça saiu correndo e foi contar estas coisas aos da casa de sua mãe.

[[v1-24-29]]

^<<v1-24-29,29>>^ Ora, Rebeca tinha um irmão, e o nome dele era Labão. Labão foi assim correndo até o homem que estava lá fora junto à fonte.

[[v1-24-30]]

^<<v1-24-30,30>>^ E sucedeu que, vendo ele a argola para as narinas e as pulseiras nas mãos de sua irmã, e ouvindo as palavras de Rebeca, sua irmã, dizendo: “Foi assim que o homem me falou”, veio ao homem, e eis que ele estava ali parado junto aos camelos, junto à fonte.

[[v1-24-31]]

^<<v1-24-31,31>>^ Ele disse imediatamente: “Vem, abençoado de Jeová. Por que ficas parado aí fora, quando eu mesmo aprontei a casa e o lugar para os camelos?”

[[v1-24-32]]

^<<v1-24-32,32>>^ Em vista disso, o homem entrou na casa, e ele foi desencilhar os camelos e dar palha e forragem aos camelos, e água para se lavarem os pés dele e os pés dos homens que estavam com ele.

[[v1-24-33]]

^<<v1-24-33,33>>^ Depois se pôs diante dele algo para comer, mas ele disse: “Não comerei até ter falado sobre os meus assuntos.” Portanto, ele disse: “Fala!”

[[v1-24-34]]

^<<v1-24-34,34>>^ Prosseguiu, então, dizendo: “Sou servo de Abraão.

[[v1-24-35]]

^<<v1-24-35,35>>^ E Jeová tem abençoado muitíssimo meu amo, pois continua a fazê-lo maior e a dar-lhe ovelhas, e gado vacum, e prata, e ouro, e servos, e servas, e camelos, e jumentos.

[[v1-24-36]]

^<<v1-24-36,36>>^ Além disso, Sara, esposa de meu amo, deu à luz um filho ao meu amo, depois de ela ter ficado velha; e ele lhe dará tudo o que possui.

[[v1-24-37]]

^<<v1-24-37,37>>^ De modo que meu amo me fez jurar, dizendo: ‘Não deves tomar para meu filho uma esposa dentre as filhas dos cananeus em cujo país estou morando.

[[v1-24-38]]

^<<v1-24-38,38>>^ Não, mas irás à casa de meu pai e à minha família, e tens de tomar uma esposa para meu filho.’

[[v1-24-39]]

^<<v1-24-39,39>>^ Mas eu disse ao meu amo: ‘E se a mulher não quiser vir comigo?’

[[v1-24-40]]

^<<v1-24-40,40>>^ Disse-me então: ‘Jeová, diante de quem tenho andado, enviará contigo o seu anjo e certamente fará bem sucedido o teu caminho; e tens de tomar para meu filho uma esposa dentre a minha família e dentre a casa de meu pai.

[[v1-24-41]]

^<<v1-24-41,41>>^ Nessa ocasião, quando chegares à minha família, ficarás desobrigado do juramento^&#42;1^ feito a mim, e se não a derem a ti, então ficarás livre da obrigação para comigo devido ao juramento.’

[NOTE]
====
. Ou “da maldição” à qual aquele que jura se sujeita ao violar seu juramento.
====

[[v1-24-42]]

^<<v1-24-42,42>>^ “Hoje, quando cheguei à fonte, eu disse: ‘Jeová, Deus de meu amo Abraão, se realmente fizeres bem sucedido o meu caminho em que estou andando,

[[v1-24-43]]

^<<v1-24-43,43>>^ eis que me acho de pé junto a uma fonte de água. O que terá de acontecer é que a donzela^&#42;1^ que sair para tirar água, a quem eu realmente disser: “Por favor, deixa-me beber um pouco de água do teu cântaro”,

[NOTE]
====
. “A donzela (virgem).” Hebr.: ha·‛al·máh; gr.: par·thé·nos; lat.: vír·go. Veja Is 7:14 n.: “donzela”.
====

[[v1-24-44]]

^<<v1-24-44,44>>^ e que realmente me disser: “Bebe não só tu, mas também tirarei água para os teus camelos”, esta é a mulher que Jeová determinou para o filho de meu amo.’

[[v1-24-45]]

^<<v1-24-45,45>>^ “Antes de eu acabar de falar no meu coração, ora, eis que saía Rebeca com o seu cântaro no ombro; e ela desceu à fonte e começou a tirar água. Então eu lhe disse: ‘Por favor, dá-me de beber.’

[[v1-24-46]]

^<<v1-24-46,46>>^ Então ela abaixou rapidamente o seu cântaro do [ombro] e disse: ‘Bebe, e darei de beber também aos teus camelos.’ Bebi então, e ela deu de beber também aos camelos.

[[v1-24-47]]

^<<v1-24-47,47>>^ Depois perguntei-lhe e disse: ‘Filha de quem és?’ ao que ela disse: ‘Filha de Betuel, filho de Naor, que Milca lhe deu à luz.’ Concordemente, pus-lhe a argola na narina e as pulseiras nas mãos.

[[v1-24-48]]

^<<v1-24-48,48>>^ E passei a inclinar-me e a prostrar-me perante Jeová, e a bendizer Jeová, o Deus de meu amo Abraão, que me guiara no caminho verdadeiro para tomar a filha do irmão do meu amo para seu filho.

[[v1-24-49]]

^<<v1-24-49,49>>^ E agora, se realmente usardes de benevolência e de fidedignidade para com o meu amo, informai-me; mas, se não, informai-me, para que eu me vire para a direita ou para a esquerda.”

[[v1-24-50]]

^<<v1-24-50,50>>^ Labão e Betuel responderam então e disseram: “Esta coisa procedeu de Jeová. Não podemos falar-te nem mal nem bem.

[[v1-24-51]]

^<<v1-24-51,51>>^ Eis que Rebeca está diante de ti. Toma-a e vai-te, e torne-se ela esposa do filho do teu amo, assim como Jeová falou.”

[[v1-24-52]]

^<<v1-24-52,52>>^ E sucedeu que, ouvindo o servo de Abraão as palavras deles, prostrou-se imediatamente em terra diante de Jeová.

[[v1-24-53]]

^<<v1-24-53,53>>^ E o servo começou a tirar objetos de prata e objetos de ouro, e roupa, e deu-os a Rebeca; e deu coisas seletas ao irmão dela e à mãe dela.

[[v1-24-54]]

^<<v1-24-54,54>>^ Depois comeram e beberam, ele e os homens que estavam com ele, e passaram ali a noite e levantaram-se de manhã.
Então ele disse: “Mandai-me embora para meu amo.”

[[v1-24-55]]

^<<v1-24-55,55>>^ A isto disseram o irmão e a mãe dela: “Deixa a moça^&#42;1^ ficar conosco pelo menos dez dias.^&#42;2^ Depois ela pode ir.”

[NOTE]
====
. “A moça (donzela; virgem).” Hebr.: han·na·‛ará; gr.: par·thé·nos.
. Lit.: “conosco dias ou dez [deles]”. Sy: “conosco um mês de dias”. Veja 29:14.
====

[[v1-24-56]]

^<<v1-24-56,56>>^ Mas ele lhes disse: “Não me retardeis, visto que Jeová me fez bem sucedido o caminho. Mandai-me embora para que eu vá ter com o meu amo.”

[[v1-24-57]]

^<<v1-24-57,57>>^ Disseram então: “Chamemos a moça e indaguemos da sua boca.”

[[v1-24-58]]

^<<v1-24-58,58>>^ Chamaram então Rebeca e disseram-lhe: “Irás com este homem?” Ela, por sua vez, disse: “Estou disposta a ir.”

[[v1-24-59]]

^<<v1-24-59,59>>^ Em vista disso, despediram Rebeca, sua irmã, e a ama dela, e o servo de Abraão e os homens dele.

[[v1-24-60]]

^<<v1-24-60,60>>^ E começaram a abençoar Rebeca e a dizer-lhe: “Que tu, nossa irmã, te tornes milhares de vezes dez mil,^&#42;1^ e que teu descendente tome posse do portão^&#42;2^ dos que o^&#42;3^ odeiam.”

[NOTE]
====
. Lit.: “milhares de miríades”.
. Isto é, da cidade.
. Ou “os”, isto é, a descendência, prole, posteridade.
====

[[v1-24-61]]

^<<v1-24-61,61>>^ Depois disso levantaram-se Rebeca e suas criadas de companhia,^&#42;1^ e montando camelos seguiam o homem; e o servo tomou Rebeca e pôs-se a caminho.

[NOTE]
====
. Ou “suas moças”.
====

[[v1-24-62]]

^<<v1-24-62,62>>^ Ora, Isaque viera do caminho que vai para Beer-Laai-Roi, pois morava na terra do Negebe.

[[v1-24-63]]

^<<v1-24-63,63>>^ E Isaque saíra a passear, a fim de meditar^&#42;1^ no campo, por volta do anoitecer. Levantando seus olhos e olhando, ora, eis que vinham camelos!

[NOTE]
====
. “Meditar”, LXXVg; isto é, falar consigo mesmo.
====

[[v1-24-64]]

^<<v1-24-64,64>>^ Levantando Rebeca os olhos, avistou Isaque e desmontou do camelo.

[[v1-24-65]]

^<<v1-24-65,65>>^ Ela disse então ao servo: “Quem é esse homem que vem andando pelo campo ao nosso encontro?” E o servo disse: “É meu amo.” E ela passou a tomar um lenço para a cabeça e a cobrir-se.

[[v1-24-66]]

^<<v1-24-66,66>>^ E o servo foi relatar a Isaque todas as coisas que tinha feito.

[[v1-24-67]]

^<<v1-24-67,67>>^ Isaque levou-a depois à tenda de Sara, sua mãe. Tomou assim Rebeca e ela se tornou sua esposa; e ele se enamorou dela, e Isaque encontrou consolo depois da perda de sua mãe.^&#42;1^

[NOTE]
====
. Lit.: “depois de sua mãe”. LXX: “a respeito de Sara, sua mãe”. Vg diz, na parte final deste versículo: “tanto [a] amou, que [isso] amainou o pesar causado pela morte de [sua] mãe”.
====

'''

xref:001-genesis/001-genesis-023.adoc#v1-23-0[&#60; Capítulo Anterior] | <<v1-24-0,Topo>> | xref:001-genesis/001-genesis-025.adoc#v1-25-0[Próximo Capítulo &#62;]