include::./index.adoc[]

[[v1-18-0]]
=== Gênesis, 18
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v1-18-1]]

^<<v1-18-1,1>>^ Jeová apareceu-lhe posteriormente entre as árvores grandes de Manre, enquanto estava sentado à entrada da tenda, por volta do calor do dia.

[[v1-18-2]]

^<<v1-18-2,2>>^ Ao levantar os seus olhos, olhou e eis que havia três homens parados a certa distância dele. Quando os avistou, começou a correr ao encontro deles, desde a entrada da tenda, e passou a curvar-se para a terra.

[[v1-18-3]]

^<<v1-18-3,3>>^ Disse então: “Jeová,^&#42;1^ se eu tiver agora achado favor aos teus olhos, por favor, não passes por teu servo.

[NOTE]
====
. Este é o primeiro dos 134 lugares em que os soferins judaicos trocaram YHWH por ’Adho·naí. Esta substituição foi feita por uma má aplicação da reverência pelo nome de Deus. Veja Ap. 1B.
====

[[v1-18-4]]

^<<v1-18-4,4>>^ Por favor, tome-se um pouco de água e terão de lavar-se os vossos pés. Recostai-vos então debaixo da árvore.

[[v1-18-5]]

^<<v1-18-5,5>>^ E deixai-me buscar um pedaço de pão, e revigorai os vossos corações. Depois podereis passar adiante, pois é por isso que passastes por aqui até o vosso servo.” A isto disseram: “Está bem. Podes fazer como falaste.”

[[v1-18-6]]

^<<v1-18-6,6>>^ Abraão foi então apressadamente à tenda, a Sara, e disse: “Depressa! Apanha três seás^&#42;1^ de flor de farinha, amassa-a e faze bolos redondos.”

[NOTE]
====
. Um seá equivalia a 7,33 l.
====

[[v1-18-7]]

^<<v1-18-7,7>>^ A seguir, Abraão correu à manada e foi apanhar um vitelo tenro e bom e entregá-lo ao ajudante, e este se apressou a aprontá-lo.

[[v1-18-8]]

^<<v1-18-8,8>>^ Tomou então manteiga e leite, bem como o vitelo que aprontara, e os pôs diante deles. Ele mesmo ficou então de pé perto deles, debaixo da árvore, enquanto comiam.

[[v1-18-9]]

^<<v1-18-9,9>>^ Disseram-lhe^&#42;1^ então: “Onde está Sara, tua esposa?” A isto ele disse: “Aqui na tenda!”

[NOTE]
====
. “Lhe.” Esta expressão no M foi assinalada com pontos extraordinários pelos soferins, mas não requer nenhuma mudança na tradução em português. Veja Ap. 2A.
====

[[v1-18-10]]

^<<v1-18-10,10>>^ De modo que continuou: “Seguramente retornarei a ti no ano que vem, neste mesmo tempo,^&#42;1^ e eis que Sara, tua esposa, terá um filho.” Ora, Sara estava escutando à entrada da tenda e esta estava atrás do homem.

[NOTE]
====
. Ou “neste tempo na primavera”. Sy: “neste tempo no ano que vem”; Vg: “neste [mesmo] tempo, se a vida for companheira”. Veja Ro 4:17-20.
====

[[v1-18-11]]

^<<v1-18-11,11>>^ E Abraão e Sara já eram velhos, avançados em anos. A Sara havia cessado a menstruação.^&#42;1^

[NOTE]
====
. Lit.: “o modo segundo as mulheres”. Esta é até hoje a expressão hebr. comum para o período menstrual.
====

[[v1-18-12]]

^<<v1-18-12,12>>^ Por isso, Sara começou a rir-se no íntimo, dizendo: “Depois de esgotada, terei realmente prazer, sendo velho também meu senhor?”^&#42;1^

[NOTE]
====
. Lit.: “e meu senhor”. Hebr.: wa’·dho·ní. Sara é elogiada por chamar seu marido de “meu senhor”. Veja 1Pe 3:6.
====

[[v1-18-13]]

^<<v1-18-13,13>>^ Jeová disse então a Abraão: “Por que foi que Sara se riu, dizendo: ‘Darei real e verdadeiramente à luz, embora eu tenha ficado velha?’

[[v1-18-14]]

^<<v1-18-14,14>>^ Há alguma coisa [que seja] extraordinária demais para Jeová? Retornarei a ti no tempo designado, no ano que vem, neste mesmo tempo, e Sara terá um filho.”

[[v1-18-15]]

^<<v1-18-15,15>>^ Sara, porém, começou a negá-lo, dizendo: “Não me ri!” Pois tinha medo. A isso ele disse: “Não, mas riste!”

[[v1-18-16]]

^<<v1-18-16,16>>^ Mais tarde, os homens levantaram-se dali e olharam para baixo, em direção a Sodoma, e Abraão andava com eles para acompanhá-los.

[[v1-18-17]]

^<<v1-18-17,17>>^ E Jeová^&#42;1^ disse: “Hei de manter encoberto a Abraão o que estou fazendo?

[NOTE]
====
. “E Jeová.” Hebr.: wa·Yho·wáh.
====

[[v1-18-18]]

^<<v1-18-18,18>>^ Ora, Abraão seguramente se tornará uma nação grande e forte, e todas as nações da terra terão de abençoar a si mesmas por meio dele.

[[v1-18-19]]

^<<v1-18-19,19>>^ Pois fui familiarizar-me com ele, para que ordenasse aos seus filhos e aos da sua casa depois dele que guardassem o caminho de Jeová para fazer a justiça e o juízo; a fim de que Jeová, com certeza, faça vir sobre Abraão aquilo que falou a respeito dele.”

[[v1-18-20]]

^<<v1-18-20,20>>^ Por conseguinte, Jeová disse: “O clamor de queixa a respeito de Sodoma e Gomorra, sim, é alto, e seu pecado, sim, é muito grave.

[[v1-18-21]]

^<<v1-18-21,21>>^ Estou de todo resolvido a descer para ver se de fato agem segundo o clamor sobre isso, que tem chegado a mim, e se não for assim, ficarei sabendo disso.”

[[v1-18-22]]

^<<v1-18-22,22>>^ Neste ponto, os homens viraram-se ali e seguiram caminho para Sodoma; mas, quanto a Jeová, ainda estava parado diante de Abraão.^&#42;1^

[NOTE]
====
. A primeira das Dezoito Emendas dos soferins, a única em Gên. M: “mas quanto a Abraão, ele ainda estava parado diante de Jeová”. Veja Ap. 2B.
====

[[v1-18-23]]

^<<v1-18-23,23>>^ Abraão aproximou-se então e começou a dizer: “Arrasarás realmente o justo junto com o iníquo?

[[v1-18-24]]

^<<v1-18-24,24>>^ Suponhamos que haja cinqüenta homens justos no meio da cidade. Arrasá-los-ás então e não perdoarás ao lugar por causa dos cinqüenta justos que há nele?

[[v1-18-25]]

^<<v1-18-25,25>>^ É inconcebível a teu respeito que atues desta maneira para entregar à morte o justo junto com o iníquo, de modo que se dê com o justo o que se dá com o iníquo! É inconcebível a teu respeito. Não fará o Juiz de toda a terra o que é direito?”

[[v1-18-26]]

^<<v1-18-26,26>>^ Jeová disse então: “Se eu achar em Sodoma cinqüenta homens justos no meio da cidade, hei de perdoar ao lugar inteiro por causa deles.”

[[v1-18-27]]

^<<v1-18-27,27>>^ Mas Abraão prosseguiu, respondendo e dizendo: “Por favor, eis que me dispus a falar a Jeová,^&#42;1^ sendo eu pó e cinzas.

[NOTE]
====
. Veja v. 3 n.
====

[[v1-18-28]]

^<<v1-18-28,28>>^ Suponhamos que faltem cinco para os cinqüenta justos. Arruinarás a cidade inteira por causa dos cinco?” A isso ele disse: “Não a arruinarei se achar ali quarenta e cinco.”

[[v1-18-29]]

^<<v1-18-29,29>>^ Mas, falou-lhe ainda mais uma vez e disse: “Suponhamos que se achem ali quarenta.” Ele, por sua vez, disse: “Não o farei por causa dos quarenta.”

[[v1-18-30]]

^<<v1-18-30,30>>^ Mas ele continuou: “Por favor, não se acenda a ira de Jeová,^&#42;1^ mas continue eu falando: Suponhamos que se achem ali trinta.” Ele, por sua vez, disse: “Não o farei se achar ali trinta.”

[NOTE]
====
. Veja v. 3 n.
====

[[v1-18-31]]

^<<v1-18-31,31>>^ Mas ele continuou: “Por favor, eis que me dispus a falar a Jeová:^&#42;1^ Suponhamos que se achem ali vinte.” Ele, por sua vez, disse: “Não a arruinarei por causa dos vinte.”

[NOTE]
====
. Veja v. 3 n.
====

[[v1-18-32]]

^<<v1-18-32,32>>^ Por fim disse: “Por favor, não se acenda a ira de Jeová,^&#42;1^ mas fale eu só mais esta vez: Suponhamos que se achem ali dez.” Ele, por sua vez, disse: “Não a arruinarei por causa dos dez.”

[NOTE]
====
. Veja v. 3 n.
====

[[v1-18-33]]

^<<v1-18-33,33>>^ Então, acabando de falar com Abraão, Jeová seguiu caminho e Abraão retornou ao seu lugar.

'''

xref:001-genesis/001-genesis-017.adoc#v1-17-0[&#60; Capítulo Anterior] | <<v1-18-0,Topo>> | xref:001-genesis/001-genesis-019.adoc#v1-19-0[Próximo Capítulo &#62;]