include::./index.adoc[]

[[v1-27-0]]
=== Gênesis, 27
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v1-27-1]]

^<<v1-27-1,1>>^ Sucedeu então que, quando Isaque já era velho e seus olhos eram fracos demais para enxergar, ele chamou Esaú, seu filho mais velho, e disse-lhe: “Meu filho!” ao que este lhe disse: “Eis-me aqui!”

[[v1-27-2]]

^<<v1-27-2,2>>^ E ele prosseguiu, dizendo: “Eis que tenho ficado velho. Não sei do dia da minha morte.

[[v1-27-3]]

^<<v1-27-3,3>>^ Portanto, nesta ocasião toma, por favor, os teus apetrechos, tua aljava e teu arco, e vai ao campo e caça-me alguma carne de veado.

[[v1-27-4]]

^<<v1-27-4,4>>^ Faze então para mim um prato gostoso tal como eu gosto e traze-mo, e, ah! deixa-me comer, para que a minha alma te abençoe antes de eu morrer.”

[[v1-27-5]]

^<<v1-27-5,5>>^ Rebeca, no entanto, estava escutando enquanto Isaque falava com Esaú, seu filho. E Esaú saiu para o campo, a fim de ir em busca de caça e trazê-la.

[[v1-27-6]]

^<<v1-27-6,6>>^ E Rebeca disse a Jacó, seu filho: “Eis que acabo de ouvir teu pai falar com Esaú, teu irmão, dizendo:

[[v1-27-7]]

^<<v1-27-7,7>>^ ‘Traze-me alguma caça e faze para mim um prato gostoso, e, ah! deixa-me comer, para que eu te abençoe perante Jeová antes da minha morte.’

[[v1-27-8]]

^<<v1-27-8,8>>^ E agora, meu filho, escuta a minha voz naquilo que te ordeno.

[[v1-27-9]]

^<<v1-27-9,9>>^ Vai, por favor, ao rebanho e traze-me de lá dois cabritinhos, dos bons, para que eu os prepare como prato gostoso para teu pai, tal como ele gosta.

[[v1-27-10]]

^<<v1-27-10,10>>^ Então tens de levá-lo a teu pai e ele tem de comê-lo, para que te abençoe antes da sua morte.”

[[v1-27-11]]

^<<v1-27-11,11>>^ E Jacó passou a dizer a Rebeca, sua mãe: “Mas Esaú, meu irmão, é homem peludo e eu sou homem liso.

[[v1-27-12]]

^<<v1-27-12,12>>^ E se meu pai me apalpar? Então hei de tornar-me aos seus olhos como quem está brincando, e certamente trarei sobre mim uma invocação do mal e não uma bênção.”

[[v1-27-13]]

^<<v1-27-13,13>>^ A isto sua mãe lhe disse: “Venha sobre mim a invocação do mal dirigida contra ti, meu filho. Apenas escuta a minha voz e vai, traze[-mos].”

[[v1-27-14]]

^<<v1-27-14,14>>^ Concordemente, ele foi e [os] apanhou, e trouxe[-os] à sua mãe, e sua mãe preparou um prato gostoso do modo como seu pai gostava.

[[v1-27-15]]

^<<v1-27-15,15>>^ Depois, Rebeca tomou vestes de Esaú, seu filho mais velho, as mais desejáveis que havia com ela na casa, e as pôs sobre Jacó, seu filho mais moço.

[[v1-27-16]]

^<<v1-27-16,16>>^ E ela lhe pôs as peles dos cabritinhos sobre as mãos e sobre a parte lisa do pescoço.

[[v1-27-17]]

^<<v1-27-17,17>>^ Entregou então na mão de Jacó, seu filho, o prato gostoso e o pão que tinha preparado.

[[v1-27-18]]

^<<v1-27-18,18>>^ Ele entrou, pois, até seu pai e disse: “Meu pai!” ao que este disse: “Eis-me aqui! Quem és, meu filho?”

[[v1-27-19]]

^<<v1-27-19,19>>^ E Jacó prosseguiu, dizendo a seu pai: “Eu sou Esaú, teu primogênito. Fiz exatamente como me falaste. Ergue-te, por favor. Senta-te e come da minha caça, para que a tua alma me abençoe.”

[[v1-27-20]]

^<<v1-27-20,20>>^ Isaque disse então a seu filho: “Como é que foste tão ligeiro em achá-la, meu filho?” Ele disse, por sua vez: “Porque Jeová, teu Deus, a fez vir ao meu encontro.”

[[v1-27-21]]

^<<v1-27-21,21>>^ Isaque disse então a Jacó: “Aproxima-te, por favor, para que eu te apalpe, meu filho, para saber se realmente és meu filho Esaú, ou não.”

[[v1-27-22]]

^<<v1-27-22,22>>^ Jacó aproximou-se então de Isaque, seu pai, e este passou a apalpá-lo, dizendo depois: “A voz é a voz de Jacó, mas as mãos são as mãos de Esaú.”

[[v1-27-23]]

^<<v1-27-23,23>>^ E não o reconheceu, porque as suas mãos se mostravam peludas como as mãos de Esaú, seu irmão. Por isso o abençoou.

[[v1-27-24]]

^<<v1-27-24,24>>^ Depois disse: “És realmente meu filho Esaú?” ao que este disse: “Sou.”

[[v1-27-25]]

^<<v1-27-25,25>>^ Então disse: “Traze-ma perto, para que eu coma da caça de meu filho, para que a minha alma te abençoe.” Então a trouxe para perto dele, e ele começou a comer, e trouxe-lhe vinho, e ele começou a beber.

[[v1-27-26]]

^<<v1-27-26,26>>^ Isaque, seu pai, disse-lhe então: “Aproxima-te, por favor, e beija-me, filho meu.”

[[v1-27-27]]

^<<v1-27-27,27>>^ Aproximou-se, pois, e beijou-o, e ele pôde cheirar o odor de suas vestes. E passou a abençoá-lo e a dizer:
“Vê! O cheiro de meu filho é como o cheiro do campo que Jeová tem abençoado.

[[v1-27-28]]

^<<v1-27-28,28>>^ E o [verdadeiro] Deus te dê os orvalhos dos céus e os solos férteis^&#42;1^ da terra, e abundância de cereais e de vinho novo.

[NOTE]
====
. “Os solos férteis.” Lit.: “as gorduras”, referindo-se à fertilidade.
====

[[v1-27-29]]

^<<v1-27-29,29>>^ Sirvam-te povos e curvem-se diante de ti grupos nacionais. Torna-te senhor sobre os teus irmãos e curvem-se diante de ti os filhos de tua mãe. Maldito seja cada um dos que te amaldiçoarem e bendito seja cada um dos que te abençoarem.”

[[v1-27-30]]

^<<v1-27-30,30>>^ Sucedeu então, assim que Isaque acabara de abençoar Jacó, sim, deveras sucedeu que, mal saíra Jacó de diante da face de Isaque, seu pai, voltou Esaú, seu irmão, da sua caçada.

[[v1-27-31]]

^<<v1-27-31,31>>^ E ele também foi preparar um prato gostoso. Trouxe-o então a seu pai e disse a seu pai: “Levante-se meu pai e coma da caça de seu filho, para que a tua alma me abençoe.”

[[v1-27-32]]

^<<v1-27-32,32>>^ Isaque, seu pai, disse-lhe então: “Quem és?” ao que este disse: “Sou teu filho, teu primogênito, Esaú.”

[[v1-27-33]]

^<<v1-27-33,33>>^ E Isaque começou a ser sacudido por forte tremor, de modo extraordinário, e assim ele disse: “Então quem é que foi em busca de caça e ma trouxe, de modo que comi de tudo antes de poderes entrar, e eu o abençoei? Também, há de tornar-se^&#42;1^ abençoado!”

[NOTE]
====
. Ou “continuar”.
====

[[v1-27-34]]

^<<v1-27-34,34>>^ Ouvindo as palavras de seu pai, Esaú começou a clamar de maneira extremamente alta e amargurada, e disse a seu pai: “Abençoa-me, sim, abençoa-me também a mim, meu pai!”

[[v1-27-35]]

^<<v1-27-35,35>>^ Mas ele prosseguiu, dizendo: “Teu irmão veio com engano, para obter a bênção destinada a ti.”

[[v1-27-36]]

^<<v1-27-36,36>>^ A isso ele disse: “Não é por isso que ele é chamado pelo nome de Jacó,^&#42;1^ que ele me suplantasse estas duas vezes? Já tomou a minha primogenitura, e eis que agora tomou a minha bênção!” Acrescentou então: “Não me reservaste alguma bênção?”

[NOTE]
====
. Significando “Agarrando o Calcanhar; Suplantador”.
====

[[v1-27-37]]

^<<v1-27-37,37>>^ Mas, em resposta a Esaú, Isaque continuou: “Eis que o constituí em senhor sobre ti, e dei-lhe todos os seus irmãos por servos, e conferi-lhe cereais e vinho novo para o seu sustento, e o que, pois, posso fazer por ti, meu filho?”

[[v1-27-38]]

^<<v1-27-38,38>>^ Esaú disse então a seu pai: “Tens apenas uma só bênção, meu pai? Abençoa-me também a mim, meu pai!” Com isso, Esaú levantou a sua voz e irrompeu em pranto.

[[v1-27-39]]

^<<v1-27-39,39>>^ Isaque, seu pai, disse-lhe assim em resposta:
“Eis que a tua morada achar-se-á longe dos solos férteis da terra e longe do orvalho dos céus acima.

[[v1-27-40]]

^<<v1-27-40,40>>^ E viverás pela tua espada e servirás a teu irmão. Mas, há de dar-se que, quando tiveres ficado desassossegado, deveras romperás o seu jugo de cima do teu pescoço.”

[[v1-27-41]]

^<<v1-27-41,41>>^ No entanto, Esaú tinha rancor a Jacó, por causa da bênção com que seu pai o tinha abençoado, e Esaú dizia no seu coração: “Estão chegando os dias do período de luto por meu pai. Depois vou matar a Jacó, meu irmão.”

[[v1-27-42]]

^<<v1-27-42,42>>^ Quando Rebeca foi informada das palavras de Esaú, seu filho mais velho, ela imediatamente mandou chamar Jacó, seu filho mais moço, e disse-lhe: “Eis que Esaú, teu irmão, consola-se^&#42;1^ a teu respeito — para matar-te.

[NOTE]
====
. Ou “alimenta vingança”.
====

[[v1-27-43]]

^<<v1-27-43,43>>^ Agora, pois, filho meu, escuta a minha voz e levanta-te, foge para Labão, meu irmão, em Harã.

[[v1-27-44]]

^<<v1-27-44,44>>^ E terás de morar com ele por alguns dias, até que se acalme o furor de teu irmão,

[[v1-27-45]]

^<<v1-27-45,45>>^ até que a ira de teu irmão se desvie de ti e ele tenha esquecido o que lhe fizeste. E eu certamente te mandarei trazer de lá. Por que hei de ficar privada também de vós dois num só dia?”

[[v1-27-46]]

^<<v1-27-46,46>>^ Depois, Rebeca dizia a Isaque: “Tenho chegado a abominar esta minha vida por causa das filhas de Hete. Se Jacó tomar esposa das filhas de Hete iguais a essas, dentre as filhas do país, de que me adianta^&#42;1^ a vida?”

[NOTE]
====
. Ou “serve”.
====

'''

xref:001-genesis/001-genesis-026.adoc#v1-26-0[&#60; Capítulo Anterior] | <<v1-27-0,Topo>> | xref:001-genesis/001-genesis-028.adoc#v1-28-0[Próximo Capítulo &#62;]