include::./index.adoc[]

[[v1-46-0]]
=== Gênesis, 46
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v1-46-1]]

^<<v1-46-1,1>>^ Concordemente, Israel e todos os que estavam com ele partiram e chegaram a Berseba, e ele passou a oferecer sacrifícios ao Deus de seu pai Isaque.

[[v1-46-2]]

^<<v1-46-2,2>>^ Deus falou então a Israel em visões noturnas e disse: “Jacó, Jacó!” ao que ele disse: “Eis-me aqui!”

[[v1-46-3]]

^<<v1-46-3,3>>^ E ele prosseguiu, dizendo: “Eu sou o [verdadeiro] Deus, o Deus de teu pai.^&#42;1^ Não tenhas medo de descer ao Egito, pois farei de ti uma grande nação.

[NOTE]
====
. Ou: “Eu, o [verdadeiro] Deus, sou o Deus de teu pai.”
====

[[v1-46-4]]

^<<v1-46-4,4>>^ Eu mesmo descerei contigo ao Egito e eu mesmo seguramente te farei também subir de lá; e José deitará a mão sobre os teus olhos.”^&#42;1^

[NOTE]
====
. Isto é, para fechá-los após a morte de Jacó.
====

[[v1-46-5]]

^<<v1-46-5,5>>^ Depois disso, Jacó se levantou de Berseba, e os filhos de Israel continuaram a transportar Jacó, seu pai, e seus pequeninos, e suas esposas, nas carroças que Faraó enviara para transportá-los.

[[v1-46-6]]

^<<v1-46-6,6>>^ Além disso, tomaram consigo suas manadas e seus bens que tinham acumulado na terra de Canaã. Por fim entraram no Egito, Jacó e toda a sua descendência com ele.

[[v1-46-7]]

^<<v1-46-7,7>>^ Trouxe consigo seus filhos e os filhos de seus filhos, suas filhas e as filhas de seus filhos, sim, toda a sua descendência [ele trouxe] consigo ao Egito.

[[v1-46-8]]

^<<v1-46-8,8>>^ Ora, estes são os nomes dos filhos de Israel que vieram ao Egito: Jacó e seus filhos: O primogênito de Jacó foi Rubem.

[[v1-46-9]]

^<<v1-46-9,9>>^ E os filhos de Rubem foram Anoque, e Palu, e Esrom, e Carmi.

[[v1-46-10]]

^<<v1-46-10,10>>^ E os filhos de Simeão foram Jemuel, e Jamim, e Oade, e Jaquim, e Zoar, e Saul, filho duma mulher cananéia.

[[v1-46-11]]

^<<v1-46-11,11>>^ E os filhos de Levi foram Gérson, Coate e Merari.

[[v1-46-12]]

^<<v1-46-12,12>>^ E os filhos de Judá foram Er, e Onã, e Selá, e Peres, e Zerá. No entanto, Er e Onã morreram na terra de Canaã.
E os filhos de Peres vieram a ser Esrom e Hamul.

[[v1-46-13]]

^<<v1-46-13,13>>^ E os filhos de Issacar foram Tola, e Puva, e Ió, e Sinrom.

[[v1-46-14]]

^<<v1-46-14,14>>^ E os filhos de Zebulão foram Serede, e Elom, e Jaleel.

[[v1-46-15]]

^<<v1-46-15,15>>^ Estes foram os filhos de Léia, que ela deu à luz a Jacó, em Padã-Arã, junto com sua filha Diná. Todas as almas dos seus filhos e das suas filhas foram trinta e três.

[[v1-46-16]]

^<<v1-46-16,16>>^ E os filhos de Gade foram Zifiom, e Hagi, Suni e Esbom, Eri e Arodi, e Areli.

[[v1-46-17]]

^<<v1-46-17,17>>^ E os filhos de Aser foram Imná, e Isvá, e Isvi, e Berias; e havia Sera, sua irmã.
E os filhos de Berias foram Héber e Malquiel.

[[v1-46-18]]

^<<v1-46-18,18>>^ Estes foram os filhos de Zilpa, que Labão deu à sua filha Léia. Com o tempo, ela deu à luz a Jacó os seguintes: dezesseis almas.

[[v1-46-19]]

^<<v1-46-19,19>>^ Os filhos de Raquel, esposa de Jacó, foram José e Benjamim.

[[v1-46-20]]

^<<v1-46-20,20>>^ E a José nasceram, na terra do Egito, Manassés e Efraim,^&#42;1^ que lhe deu à luz Asenate, filha de Potífera, sacerdote de Om.

[NOTE]
====
. Após “Efraim”, LXX acrescenta mais cinco nomes, rezando: “Mas nasceram filhos a Manassés, que lhe deu à luz sua concubina síria, a saber: Maquir. E Maquir tornou-se pai de Galaade. Mas os filhos de Efraim, irmão de Manassés, foram Sutalaam e Taam. E os filhos de Sutalaam foram Edem.” Isto talvez explique por que LXX, em Gên 46:27 e Êx 1:5, e Estêvão, em At 7:14, contam 75 almas, em vez de 70.
====

[[v1-46-21]]

^<<v1-46-21,21>>^ E os filhos de Benjamim foram Bela, e Bequer, e Asbel, e Gera e Naamã, Eí e Rôs, Mupim e Hupim, e Arde.

[[v1-46-22]]

^<<v1-46-22,22>>^ Estes foram os filhos de Raquel, que nasceram a Jacó. Todas as almas foram quatorze.

[[v1-46-23]]

^<<v1-46-23,23>>^ E os filhos de Dã: Husim.

[[v1-46-24]]

^<<v1-46-24,24>>^ E os filhos de Naftali foram Jazeel, e Guni, e Jézer, e Silém.

[[v1-46-25]]

^<<v1-46-25,25>>^ Estes foram os filhos de Bila, que Labão deu à sua filha Raquel. Com o tempo, ela deu à luz estes a Jacó; todas as almas foram sete.

[[v1-46-26]]

^<<v1-46-26,26>>^ Todas as almas que vieram a Jacó ao Egito foram os que procederam da parte superior de sua coxa, além das esposas dos filhos de Jacó. Todas as almas foram sessenta e seis.

[[v1-46-27]]

^<<v1-46-27,27>>^ E os filhos de José, que lhe nasceram no Egito, foram duas almas. Todas as almas da casa de Jacó, que vieram ao Egito, foram setenta.^&#42;1^

[NOTE]
====
. “Setenta”, MTSYVg; LXX: “setenta e cinco”.
====

[[v1-46-28]]

^<<v1-46-28,28>>^ E ele enviou Judá na sua frente a José, para mandar informação na sua frente^&#42;1^ a Gósen. Depois entraram na terra de Gósen.^&#42;2^

[NOTE]
====
. “A José, para que lhe anunciasse”, Vg.
. “A José, para encontrá-lo em Heroópolis, na terra de Ramessés”, LXX.
====

[[v1-46-29]]

^<<v1-46-29,29>>^ José fez então aprontar seu carro e subiu ao encontro de Israel, seu pai, a Gósen. Ao se lhe apresentar, lançou-se-lhe imediatamente ao pescoço e verteu lágrimas ao seu pescoço, vez após vez.

[[v1-46-30]]

^<<v1-46-30,30>>^ Por fim, Israel disse a José: “Esta vez estou pronto para morrer, já que tenho visto a tua face, pois ainda vives.”

[[v1-46-31]]

^<<v1-46-31,31>>^ José disse então aos seus irmãos e aos da casa de seu pai: “Vou subir e informar Faraó, e vou dizer-lhe: ‘Meus irmãos e os da casa de meu pai, que estavam na terra de Canaã, vieram ter comigo.

[[v1-46-32]]

^<<v1-46-32,32>>^ E os homens são pastores, porque se tornaram criadores de gado; e trouxeram para cá seus rebanhos e suas manadas, e tudo o que têm.’

[[v1-46-33]]

^<<v1-46-33,33>>^ E tem de se dar que, quando Faraó vos chamar e realmente disser: ‘Qual é a vossa ocupação?’

[[v1-46-34]]

^<<v1-46-34,34>>^ tereis de dizer: ‘Teus servos têm continuado a ser criadores de gado desde a nossa mocidade até agora, tanto nós como os nossos antepassados’, a fim de que possais morar na terra de Gósen, porque todo pastor de ovelhas é algo detestável para o Egito.”

'''

xref:001-genesis/001-genesis-045.adoc#v1-45-0[&#60; Capítulo Anterior] | <<v1-46-0,Topo>> | xref:001-genesis/001-genesis-047.adoc#v1-47-0[Próximo Capítulo &#62;]