include::./index.adoc[]

[[v51-2-0]]
=== Colossenses, 2
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v51-2-1]]

^<<v51-2-1,1>>^ Pois eu quero que vos deis conta de quão grande é a peleja que tenho a favor de vós e dos de Laodicéia, e de todos os que não viram o meu rosto na carne,

[[v51-2-2]]

^<<v51-2-2,2>>^ para que os seus corações sejam consolados, para que sejam harmoniosamente conjuntados em amor, e visando todas as riquezas da plena certeza do [seu] entendimento, visando um conhecimento exato do segredo sagrado de Deus, a saber, Cristo.^&#42;1^

[NOTE]
====
. “Do Deus de Cristo”, P46B; א°AVg: “de Deus, o Pai de (o) Cristo (Jesus)”.
====

[[v51-2-3]]

^<<v51-2-3,3>>^ Cuidadosamente ocultos nele se acham todos os tesouros da sabedoria e do conhecimento.

[[v51-2-4]]

^<<v51-2-4,4>>^ Digo isso para que nenhum homem vos iluda^&#42;1^ com argumentos persuasivos.

[NOTE]
====
. Ou “defraude”.
====

[[v51-2-5]]

^<<v51-2-5,5>>^ Pois, embora eu esteja ausente na carne, assim mesmo estou convosco no espírito, alegrando-me e observando a vossa boa ordem e a solidez da vossa fé para com Cristo.

[[v51-2-6]]

^<<v51-2-6,6>>^ Portanto, visto que aceitastes a Cristo Jesus, o Senhor, prossegui andando em união com ele,

[[v51-2-7]]

^<<v51-2-7,7>>^ arraigados, e sendo edificados nele e estabilizados na fé, assim como fostes ensinados, transbordando em agradecimentos com [fé].^&#42;1^

[NOTE]
====
. “Transbordando nela com agradecimentos”, BSyh,pArm; א°AVg: “transbordando em agradecimentos”.
====

[[v51-2-8]]

^<<v51-2-8,8>>^ Acautelai-vos: talvez haja alguém que vos leve embora como presa sua, por intermédio de filosofia e de vão engano,^&#42;1^ segundo a tradição de homens, segundo as coisas elementares do mundo e não segundo Cristo;

[NOTE]
====
. Lit.: “sedução”.
====

[[v51-2-9]]

^<<v51-2-9,9>>^ porque é nele que mora corporalmente toda a plenitude da qualidade divina.^&#42;1^

[NOTE]
====
. “Qualidade divina.” Lit.: “divindade”. Gr.: the·ó·te·tos; lat.: di·vi·ni·tá·tis.
====

[[v51-2-10]]

^<<v51-2-10,10>>^ E assim possuís uma plenitude por meio dele, sendo ele a cabeça de todo governo e autoridade.

[[v51-2-11]]

^<<v51-2-11,11>>^ Pela relação com ele, vós também fostes circuncidados com uma circuncisão realizada sem mãos, pelo desnudamento do corpo da carne, pela circuncisão que pertence ao Cristo,

[[v51-2-12]]

^<<v51-2-12,12>>^ pois fostes enterrados com ele no [seu]^&#42;1^ batismo, e, pela relação com ele, fostes também levantados junto por intermédio da [vossa] fé na operação de Deus, o qual o levantou dentre os mortos.

[NOTE]
====
. Lit.: “no (batismo)”.
====

[[v51-2-13]]

^<<v51-2-13,13>>^ Outrossim, embora estivésseis mortos nas vossas falhas e no estado incircunciso da vossa carne, [Deus]^&#42;1^ vos vivificou junto com ele. Ele nos perdoou bondosamente todas as nossas falhas

[NOTE]
====
. Lit.: “ele”.
====

[[v51-2-14]]

^<<v51-2-14,14>>^ e apagou^&#42;1^ o documento manuscrito^&#42;2^ [que era] contra nós, que consistia em decretos e que estava em oposição a nós; e Ele o tirou do caminho por pregá-lo na estaca de tortura.^&#42;3^

[NOTE]
====
. Lit.: “tendo abolido”.
. Ou “pacto”.
. Veja Ap. 5C.
====

[[v51-2-15]]

^<<v51-2-15,15>>^ Desnudando os governos e as autoridades, exibiu-os^&#42;1^ abertamente em público como vencidos, conduzindo-os por meio dela^&#42;2^ numa procissão triunfal.

[NOTE]
====
. Lit.: “os expôs”.
. Ou “dele”. Gr.: au·toí, dativo, sing.
====

[[v51-2-16]]

^<<v51-2-16,16>>^ Portanto, nenhum homem vos julgue pelo comer ou pelo beber, ou com respeito a uma festividade ou à observância da lua nova ou dum sábado;^&#42;1^

[NOTE]
====
. Ou “de sábados”.
====

[[v51-2-17]]

^<<v51-2-17,17>>^ pois estas coisas são sombra das coisas vindouras, mas a realidade^&#42;1^ pertence ao Cristo.

[NOTE]
====
. Ou “substância”. Lit.: “corpo”. Gr.: só·ma; lat.: cór·pus.
====

[[v51-2-18]]

^<<v51-2-18,18>>^ Nenhum homem vos prive do prêmio, tendo ele deleite numa humildade [fingida] e numa forma de adoração^&#42;1^ dos anjos, “tomando pé nas”^&#42;2^ coisas que viu, enfunado sem causa devida pela carnalidade de sua mente,

[NOTE]
====
. “Forma de adoração.” Lat.: re·li·gi·ó·ne, “religião”.
. Citado dos ritos de iniciação em mistérios pagãos.
====

[[v51-2-19]]

^<<v51-2-19,19>>^ ao passo que não se apega à cabeça, àquele de quem todo o corpo, suprido e harmoniosamente conjuntado por meio de suas juntas e ligamentos, vai crescendo com o desenvolvimento que Deus dá.

[[v51-2-20]]

^<<v51-2-20,20>>^ Se morrestes junto com Cristo para com as coisas elementares do mundo, por que, como se vivêsseis no mundo, vos sujeitais ainda aos decretos:

[[v51-2-21]]

^<<v51-2-21,21>>^ “Não manuseies, nem proves, nem toques”,

[[v51-2-22]]

^<<v51-2-22,22>>^ no que se refere às coisas que estão todas destinadas à destruição por serem consumidas pelo uso, de acordo com os mandados e ensinos de homens?

[[v51-2-23]]

^<<v51-2-23,23>>^ Estas mesmas coisas, deveras, têm aparência de sabedoria numa forma de adoração imposta a si próprio^&#42;1^ e em humildade [fingida], no tratamento severo do corpo; mas, não são de valor algum em combater a satisfação da carne.

[NOTE]
====
. Lit.: “forma voluntariosa de adoração”. Gr.: e·the·lo·thre·skí·ai; lat.: su·per·sti·ti·ó·ne, “superstição”.
====

'''

xref:051-colossenses/051-colossenses-001.adoc#v51-1-0[&#60; Capítulo Anterior] | <<v51-2-0,Topo>> | xref:051-colossenses/051-colossenses-003.adoc#v51-3-0[Próximo Capítulo &#62;]