include::./index.adoc[]

[[v51-3-0]]
=== Colossenses, 3
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v51-3-1]]

^<<v51-3-1,1>>^ Se, porém, fostes levantados junto com o Cristo, prossegui buscando as coisas de cima, onde o Cristo está sentado à direita de Deus.

[[v51-3-2]]

^<<v51-3-2,2>>^ Mantende as vossas mentes fixas nas coisas de cima, não nas coisas sobre a terra.

[[v51-3-3]]

^<<v51-3-3,3>>^ Pois morrestes, e a vossa vida tem sido escondida com o Cristo em união com Deus.

[[v51-3-4]]

^<<v51-3-4,4>>^ Quando for manifestado o Cristo, nossa vida, então também sereis manifestados com ele em glória.

[[v51-3-5]]

^<<v51-3-5,5>>^ Amortecei, portanto, os membros do vosso corpo que estão na terra, com respeito a fornicação,^&#42;1^ impureza,^&#42;2^ apetite sexual,^&#42;3^ desejo nocivo e cobiça, que é idolatria.

[NOTE]
====
. “Fornicação.” Gr.: por·neí·an; lat.: for·ni·ca·ti·ó·nem; J17,22(hebr.): haz·zenúth, “a fornicação”. Veja Ap. 5A.
. Ou “imundícia; depravação; lascívia”. Gr.: a·ka·thar·sí·an; J17,22(hebr.): wehat·tum·’áh, “e a impureza”. Veja 2Co 12:21 n.: “impureza”.
. Lit.: “paixão”. Gr.: pá·thos.
====

[[v51-3-6]]

^<<v51-3-6,6>>^ Por causa destas coisas [é que] vem o furor de Deus.

[[v51-3-7]]

^<<v51-3-7,7>>^ Nestas mesmas coisas vós também andastes outrora, quando costumáveis viver nelas.

[[v51-3-8]]

^<<v51-3-8,8>>^ Mas agora, realmente, afastai de vós a todas elas, o furor, a ira, a maldade, a linguagem ultrajante^&#42;1^ e a conversa obscena da vossa boca.

[NOTE]
====
. Ou “blasfêmia”.
====

[[v51-3-9]]

^<<v51-3-9,9>>^ Não estejais mentindo uns aos outros. Desnudai-vos da velha personalidade^&#42;1^ com as suas práticas

[NOTE]
====
. Lit.: “do velho homem”.
====

[[v51-3-10]]

^<<v51-3-10,10>>^ e revesti-vos da nova [personalidade], a qual, por intermédio do^&#42;1^ conhecimento exato, está sendo renovada segundo a imagem Daquele que a criou,

[NOTE]
====
. Ou “no”.
====

[[v51-3-11]]

^<<v51-3-11,11>>^ não havendo nem grego nem judeu, circuncisão nem incircuncisão, estrangeiro, cita, escravo, homem livre, mas Cristo é todas as coisas e em todos.

[[v51-3-12]]

^<<v51-3-12,12>>^ Concordemente, como escolhidos de Deus, santos e amados, revesti-vos das ternas afeições de compaixão, benignidade, humildade mental,^&#42;1^ brandura e longanimidade.

[NOTE]
====
. Ou, só “humildade”.
====

[[v51-3-13]]

^<<v51-3-13,13>>^ Continuai a suportar-vos uns aos outros e a perdoar-vos uns aos outros liberalmente, se alguém tiver razão para queixa contra outro. Assim como Jeová^&#42;1^ vos perdoou liberalmente, vós também o fazei.

[NOTE]
====
. “Jeová”, J23; P46ABD°(gr.): ho Ký·ri·os; אcCDcSyh,p: “o Cristo”; א°: “Deus”. Veja Ap. 1D.
====

[[v51-3-14]]

^<<v51-3-14,14>>^ Além de todas estas coisas, porém, [revesti-vos de] amor, pois é o perfeito vínculo de união.^&#42;1^

[NOTE]
====
. Lit.: “vínculo conjunto da perfeição”.
====

[[v51-3-15]]

^<<v51-3-15,15>>^ Também, a paz do Cristo^&#42;1^ domine nos vossos corações, pois, de fato, fostes chamados a ela em um só^&#42;2^ corpo. E mostrai-vos gratos.

[NOTE]
====
. “Do Cristo”, א°ABC°D°; אcCcDc: “de Deus”; J7,8: “de Jeová”.
. “Um só”, אADVgSyp; P46B omitem isso.
====

[[v51-3-16]]

^<<v51-3-16,16>>^ A palavra do Cristo^&#42;1^ resida em vós ricamente, em toda a sabedoria. Persisti em ensinar e em vos admoestar uns aos outros com salmos, [com] louvores a Deus,^&#42;2^ [com] cânticos espirituais com graça, cantando em vossos corações a Jeová.^&#42;3^

[NOTE]
====
. “Do Cristo”, P46אcBCcDVg; א°: “do Senhor”; AC°: “de Deus”.
. Lit.: “hinos”. Gr.: hý·mnois; lat.: hý·mnis.
. “A Jeová”, J7,8,13,14,16,17; CcDc(gr.): toi Ky·rí·oi; P46אABC°D°VgSyh,p: “a Deus”. Veja Ap. 1D.
====

[[v51-3-17]]

^<<v51-3-17,17>>^ E, o que for que fizerdes em palavra ou em obra, fazei tudo no nome do Senhor Jesus, agradecendo a Deus, o Pai, por intermédio dele.

[[v51-3-18]]

^<<v51-3-18,18>>^ Vós, esposas, estai sujeitas aos [vossos] maridos, assim como é decente no Senhor.

[[v51-3-19]]

^<<v51-3-19,19>>^ Vós, maridos, persisti em amar as [vossas] esposas e não vos ireis amargamente com elas.

[[v51-3-20]]

^<<v51-3-20,20>>^ Vós, filhos, em tudo sede obedientes aos [vossos] pais, pois isso é bem agradável no Senhor.

[[v51-3-21]]

^<<v51-3-21,21>>^ Vós, pais, não estejais exasperando os vossos filhos, para que não fiquem desanimados.

[[v51-3-22]]

^<<v51-3-22,22>>^ Vós, escravos, em tudo sede obedientes aos que são os [vossos] amos em sentido carnal, não com atos apenas ostensivos, como para agradar a homens, mas com sinceridade de coração, com temor de Jeová.^&#42;1^

[NOTE]
====
. “De Jeová”, J18,22,28; א°ABCD°(gr.): ton Ký·ri·on; P46אcDc: “de Deus”. Veja Ap. 1D.
====

[[v51-3-23]]

^<<v51-3-23,23>>^ O que for que fizerdes, trabalhai nisso de toda a alma como para Jeová,^&#42;1^ e não como para homens,

[NOTE]
====
. Veja Ap. 1D.
====

[[v51-3-24]]

^<<v51-3-24,24>>^ pois sabeis que é de Jeová^&#42;1^ que recebereis a devida recompensa da herança. Trabalhai como escravos para o Amo, Cristo.

[NOTE]
====
. Veja Ap. 1D.
====

[[v51-3-25]]

^<<v51-3-25,25>>^ Certamente, quem estiver fazendo o errado receberá de volta o que fez de errado, e não há parcialidade.

'''

xref:051-colossenses/051-colossenses-002.adoc#v51-2-0[&#60; Capítulo Anterior] | <<v51-3-0,Topo>> | xref:051-colossenses/051-colossenses-004.adoc#v51-4-0[Próximo Capítulo &#62;]