include::./index.adoc[]

[[v51-4-0]]
=== Colossenses, 4
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v51-4-1]]

^<<v51-4-1,1>>^ Vós, amos, persisti em tratar [vossos] escravos de modo justo e eqüitativo, sabendo que vós também tendes um Amo no céu.

[[v51-4-2]]

^<<v51-4-2,2>>^ Persisti em oração, permanecendo despertos nela com agradecimento,

[[v51-4-3]]

^<<v51-4-3,3>>^ orando ao mesmo tempo também por nós, para que Deus nos abra uma porta de pronunciação para falarmos o segredo sagrado acerca do Cristo, pelo qual, de fato, estou em cadeias;

[[v51-4-4]]

^<<v51-4-4,4>>^ para que eu o torne manifesto assim como devo falar.

[[v51-4-5]]

^<<v51-4-5,5>>^ Prossegui andando em sabedoria para com os de fora, comprando para vós todo o tempo oportuno.

[[v51-4-6]]

^<<v51-4-6,6>>^ Vossa pronunciação seja sempre com graça,^&#42;1^ temperada com sal, para que saibais como responder a cada um.

[NOTE]
====
. Ou “com o que é favorável”.
====

[[v51-4-7]]

^<<v51-4-7,7>>^ Tíquico, [meu] amado irmão, e fiel ministro, e co-escravo no Senhor, vos fará saber todos os meus negócios.

[[v51-4-8]]

^<<v51-4-8,8>>^ Com este mesmo propósito, para que saibais as coisas que têm que ver conosco e para que console os vossos corações, eu o envio a vós

[[v51-4-9]]

^<<v51-4-9,9>>^ junto com Onésimo, fiel e amado irmão meu, que é do vosso meio. Eles vos farão saber todas as coisas daqui.

[[v51-4-10]]

^<<v51-4-10,10>>^ Aristarco, meu companheiro de cativeiro, manda-vos os seus cumprimentos, e assim também Marcos, primo de Barnabé, (a respeito de quem recebestes mandado para o acolher, se for ter convosco,)

[[v51-4-11]]

^<<v51-4-11,11>>^ e Jesus, que é chamado Justo, sendo estes dos circuncisos.^&#42;1^ Somente estes são os meus colaboradores pelo reino de Deus, e estes mesmos se tornaram para mim um auxílio fortificante.

[NOTE]
====
. Lit.: “dentre a circuncisão”.
====

[[v51-4-12]]

^<<v51-4-12,12>>^ Epafras, que é do vosso meio, escravo de Cristo Jesus, manda-vos os seus cumprimentos, esforçando-se sempre a favor de vós nas [suas] orações, para que por fim estejais de pé, completos e com firme convicção, em toda a vontade de Deus.

[[v51-4-13]]

^<<v51-4-13,13>>^ Eu deveras lhe dou testemunho de que faz grande esforço a favor de vós e daqueles de Laodicéia, e dos de Hierápolis.

[[v51-4-14]]

^<<v51-4-14,14>>^ Lucas, o médico^&#42;1^ amado, manda-vos os seus cumprimentos, e o mesmo faz Demas.

[NOTE]
====
. “Médico.” Gr.: i·a·trós; lat.: mé·di·cus.
====

[[v51-4-15]]

^<<v51-4-15,15>>^ Dai os meus cumprimentos aos irmãos de Laodicéia, e a Ninfa, e à congregação na casa dela.

[[v51-4-16]]

^<<v51-4-16,16>>^ E, quando esta carta tiver sido lida entre vós, providenciai para que seja também lida na congregação dos laodicenses, e para que leiais também a de Laodicéia.

[[v51-4-17]]

^<<v51-4-17,17>>^ Também, dizei a Arquipo: “Persiste em vigiar o ministério que aceitaste no Senhor, para que o cumpras.”

[[v51-4-18]]

^<<v51-4-18,18>>^ [Aqui está] o meu cumprimento, o de Paulo, pela minha própria mão. Continuai a lembrar-vos das minhas cadeias. A benignidade imerecida seja convosco.

'''

xref:051-colossenses/051-colossenses-003.adoc#v51-3-0[&#60; Capítulo Anterior] | <<v51-4-0,Topo>> | xref:052-1-tessalonicenses/052-1-tessalonicenses-001.adoc#v52-1-0[Próximo Capítulo &#62;]