include::./index.adoc[]

[[v51-1-0]]
=== Colossenses, 1
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v51-1-1]]

^<<v51-1-1,1>>^ Paulo, apóstolo de Cristo Jesus, pela vontade de Deus, e Timóteo, [nosso] irmão,

[[v51-1-2]]

^<<v51-1-2,2>>^ aos santos e irmãos fiéis em união com Cristo, em Colossos:
Que tenhais benignidade imerecida e paz da parte de Deus, nosso Pai.

[[v51-1-3]]

^<<v51-1-3,3>>^ Agradecemos a Deus, o Pai de nosso Senhor Jesus Cristo,^&#42;1^ sempre que oramos^&#42;2^ por vós,

[NOTE]
====
. “Cristo”, אAVgSyp; B o omite.
. Ou “sempre orando”.
====

[[v51-1-4]]

^<<v51-1-4,4>>^ pois ouvimos [falar] da vossa fé em conexão com Cristo Jesus e do amor que tendes^&#42;1^ por todos os santos,

[NOTE]
====
. “Tendes”, אAVg; B omite isso.
====

[[v51-1-5]]

^<<v51-1-5,5>>^ por causa da esperança que está sendo reservada para vós nos céus. Desta [esperança] já ouvistes [falar] antes, por se contar a verdade daquelas boas novas

[[v51-1-6]]

^<<v51-1-6,6>>^ que se vos apresentaram, assim como estão dando fruto e estão aumentando em todo o mundo, do mesmo modo como [se dá] também entre vós, desde o dia em que ouvistes e conhecestes [de modo] exato a benignidade imerecida de Deus em verdade.

[[v51-1-7]]

^<<v51-1-7,7>>^ É isso o que aprendestes de Epafras, nosso amado co-escravo, que é ministro^&#42;1^ fiel do Cristo, da nossa parte,

[NOTE]
====
. Ou “servo”. Gr.: di·á·ko·nos; lat.: mi·ní·ster (de mí·nus, “menos”); J17,18(hebr.): mesha·réth, “ministro”.
====

[[v51-1-8]]

^<<v51-1-8,8>>^ o qual nos expôs também o vosso amor em sentido espiritual.^&#42;1^

[NOTE]
====
. Lit.: “em espírito”.
====

[[v51-1-9]]

^<<v51-1-9,9>>^ É também por isso que nós, desde o dia em que ouvimos [isso], não cessamos de orar por vós e de pedir^&#42;1^ que fiqueis cheios do conhecimento exato da sua vontade, em toda a sabedoria e compreensão espiritual,

[NOTE]
====
. Lit.: “rogar”.
====

[[v51-1-10]]

^<<v51-1-10,10>>^ para andardes dignamente de Jeová,^&#42;1^ com o fim de [lhe] agradardes plenamente, ao prosseguirdes em dar fruto em toda boa obra e em aumentar no conhecimento exato de Deus,

[NOTE]
====
. “De Jeová”, J7,8; אAB(gr.): tou Ky·rí·ou; Vg: “de Deus”. Veja Ap. 1D.
====

[[v51-1-11]]

^<<v51-1-11,11>>^ sendo fortalecidos com todo o poder, ao alcance de seu glorioso poderio, de modo a perseverardes plenamente e serdes longânimes com alegria,

[[v51-1-12]]

^<<v51-1-12,12>>^ agradecendo ao Pai, que vos tornou idôneos para a vossa participação na herança dos santos na luz.

[[v51-1-13]]

^<<v51-1-13,13>>^ Ele nos livrou da autoridade da escuridão e nos transferiu para o reino do Filho do seu amor,

[[v51-1-14]]

^<<v51-1-14,14>>^ mediante quem temos o nosso livramento por meio de resgate, o perdão dos nossos pecados.

[[v51-1-15]]

^<<v51-1-15,15>>^ Ele é a imagem do Deus invisível, o primogênito de toda a criação;

[[v51-1-16]]

^<<v51-1-16,16>>^ porque mediante ele foram criadas todas as [outras]^&#42;1^ coisas nos céus e na terra, as coisas visíveis e as coisas invisíveis, quer sejam tronos, quer senhorios, quer governos, quer autoridades. Todas as [outras] coisas foram criadas por intermédio dele e para ele.

[NOTE]
====
. “Todas as [outras]”, como em Lu 11:41, 42.
====

[[v51-1-17]]

^<<v51-1-17,17>>^ Também, ele é antes de todas as [outras] coisas e todas as [outras] coisas vieram a existir por meio dele,

[[v51-1-18]]

^<<v51-1-18,18>>^ e ele é a cabeça do corpo, a congregação. Ele é o princípio, o primogênito dentre os mortos, para se tornar aquele que é primeiro em todas as coisas;

[[v51-1-19]]

^<<v51-1-19,19>>^ porque [Deus]^&#42;1^ achou bom que morasse nele toda a plenitude,

[NOTE]
====
. Lit.: “ele”.
====

[[v51-1-20]]

^<<v51-1-20,20>>^ e, por intermédio dele, reconciliar novamente todas as [outras] coisas consigo mesmo, por fazer a paz por intermédio do sangue [que ele derramou] na estaca de tortura,^&#42;1^ quer sejam^&#42;2^ as coisas na terra, quer as coisas nos céus.

[NOTE]
====
. Veja Ap. 5C.
. “Quer sejam”, BD°Vg; P46אACDc: “sim, por meio dele, quer sejam”.
====

[[v51-1-21]]

^<<v51-1-21,21>>^ Deveras, a vós, os que outrora estáveis apartados e éreis inimigos, porque as vossas mentes se fixavam nas obras iníquas,

[[v51-1-22]]

^<<v51-1-22,22>>^ ele reconciliou agora novamente, mediante o corpo carnal daquele, por intermédio da morte [dele], a fim de vos apresentar santos e sem mácula, e não expostos a nenhuma acusação perante ele,

[[v51-1-23]]

^<<v51-1-23,23>>^ desde que, naturalmente, continueis na fé, estabelecidos no alicerce e constantes, e sem serdes deslocados da esperança daquelas boas novas que ouvistes e que foram pregadas em toda a criação debaixo do céu. Destas [boas novas] eu, Paulo, tornei-me ministro.

[[v51-1-24]]

^<<v51-1-24,24>>^ Eu me alegro agora dos meus sofrimentos por vós, e, por minha vez, estou preenchendo o que está faltando nas tribulações do Cristo na minha carne, a favor do seu corpo, que é a congregação.

[[v51-1-25]]

^<<v51-1-25,25>>^ Tornei-me ministro desta [congregação] de acordo com a mordomia que me foi dada da parte de Deus, no vosso interesse, para pregar plenamente a palavra de Deus,

[[v51-1-26]]

^<<v51-1-26,26>>^ o segredo sagrado que estava escondido dos passados sistemas de coisas^&#42;1^ e das gerações passadas. Mas agora tem sido manifesto aos seus santos,

[NOTE]
====
. Ou “ordens . . . de coisas”. Gr.: ai·ó·non; lat.: saé·cu·lis; J17,22(hebr.): me·‛oh·la·mím, “das ordens de coisas [passadas]”.
====

[[v51-1-27]]

^<<v51-1-27,27>>^ a quem Deus se agradou de dar a saber quais são as riquezas gloriosas deste segredo sagrado entre as nações. É Cristo em união convosco, a esperança da [sua]^&#42;1^ glória.

[NOTE]
====
. Lit.: “da (glória)”.
====

[[v51-1-28]]

^<<v51-1-28,28>>^ É a ele que estamos propalando, admoestando cada homem e ensinando a cada homem toda a sabedoria, a fim de que apresentemos cada homem completo^&#42;1^ em união com Cristo.

[NOTE]
====
. Ou “maduro; perfeito”. Gr.: té·lei·on.
====

[[v51-1-29]]

^<<v51-1-29,29>>^ Para este fim é que deveras trabalho arduamente, esforçando-me de acordo com a operação dele e que está agindo em mim com poder.

'''

xref:050-filipenses/050-filipenses-004.adoc#v50-4-0[&#60; Capítulo Anterior] | <<v51-1-0,Topo>> | xref:051-colossenses/051-colossenses-002.adoc#v51-2-0[Próximo Capítulo &#62;]