include::./index.adoc[]

[[v35-3-0]]
=== Habacuque, 3
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v35-3-1]]

^<<v35-3-1,1>>^ A oração de Habacuque, o profeta, em endechas:^&#42;1^

[NOTE]
====
. “Endechas.” Hebr.: shigh·yo·nóhth; LXX: “cântico”; Vg: “(por) atos ignorantes; (por) ignorâncias”. Veja Sal 7:cab n.: “Endecha”.
====

[[v35-3-2]]

^<<v35-3-2,2>>^ Ó Jeová, ouvi as notícias a teu respeito. Fiquei com medo da tua atuação, ó Jeová.
Aviva-a no meio dos anos! Torna-a conhecida no meio dos anos. Durante a agitação, que tu te lembres de ter misericórdia.

[[v35-3-3]]

^<<v35-3-3,3>>^ O próprio Deus^&#42;1^ passou a chegar de Temã,^&#42;2^ sim, um Santo desde o monte Parã. Selá.^&#42;3^
Sua dignidade cobriu [os] céus; e do seu louvor encheu-se a terra.

[NOTE]
====
. “Deus.” Hebr.: ’Elóh·ah, sing.; gr.: The·ós; lat.: Dé·us.
. “De Temã.” Hebr.: mit·Teh·mán; gr.: ek Thai·mán. Ou “do sul”, como na Vg; veja Êx 26:18, 35.
. “Selá.” Hebr.: sé·lah; gr.: di·á·psal·ma, “interlúdio musical”. Esta palavra ocorre três vezes nesta oração de Habacuque. Veja Sal 3:2 n.: “Selá.”
====

[[v35-3-4]]

^<<v35-3-4,4>>^ Quanto à [sua]^&#42;1^ claridade, chegou a ser igual à luz. Havia dois raios^&#42;2^ [saindo] da sua mão e ali se escondia a sua força.

[NOTE]
====
. “Sua”, LXXSyVg; M omite isso.
. Lit.: “chifres”. Veja Êx 34:29, 30, 35.
====

[[v35-3-5]]

^<<v35-3-5,5>>^ Diante dele andava a peste e junto aos seus pés saía a febre ardente.

[[v35-3-6]]

^<<v35-3-6,6>>^ Ele ficou parado para sacudir [a] terra. Ele viu, e então fez nações pular.
E as montanhas eternas foram despedaçadas; os morros de duração indefinida se encurvaram. Suas são as caminhadas de há muito tempo.

[[v35-3-7]]

^<<v35-3-7,7>>^ Vi as tendas de Cusã^&#42;1^ debaixo daquilo que é prejudicial. Os panos de tenda da terra de Midiã começaram a ficar agitados.

[NOTE]
====
. “Cusã”, MSy; LXX: “dos etíopes”; Vg: “Etiópia”.
====

[[v35-3-8]]

^<<v35-3-8,8>>^ É contra os rios, ó Jeová, é contra os rios que se acendeu a tua ira ou é a tua fúria contra o mar? Pois cavalgaste sobre os teus cavalos; teus carros eram salvação.

[[v35-3-9]]

^<<v35-3-9,9>>^ Teu arco vem a ser descoberto na [sua] nudez. A coisa dita^&#42;1^ são os juramentos das tribos. Selá. Com rios passaste a fender [a] terra.

[NOTE]
====
. “Na [sua] nudez. A coisa dita”, M; LXXBagster: “Certamente dobraste o teu arco diante de cetros, diz o Senhor [LXXVTS 10a: “Jeová”].” Veja Ap. 1C sec. 2.
====

[[v35-3-10]]

^<<v35-3-10,10>>^ Os montes te viram; chegaram a estar em severas dores. Passou um temporal de águas. A água de profundeza^&#42;1^ emitiu o seu som. Levantou alto a sua mão.

[NOTE]
====
. Ou “águas empoladas”. Hebr.: tehóhm; sir.: tehu·ma’; LXXVg: “abismo”. Veja Gên 1:2 n.: “profundeza”.
====

[[v35-3-11]]

^<<v35-3-11,11>>^ O sol — a lua — ficou parado na sua morada excelsa. Tuas próprias flechas iam como a luz. O relâmpago da tua lança serviu de claridade.

[[v35-3-12]]

^<<v35-3-12,12>>^ Marchaste com verberação [através] da terra. Em ira trilhaste [as] nações.

[[v35-3-13]]

^<<v35-3-13,13>>^ E saíste para a salvação do teu povo, para salvar o teu ungido.^&#42;1^ Despedaçaste o cabeça da casa do iníquo. Houve a exposição do alicerce até o pescoço. Selá.

[NOTE]
====
. “Teu ungido.” Hebr.: meshi·hhé·kha; LXXBagster(gr.): khri·stón; lat.: chrí·sto.
====

[[v35-3-14]]

^<<v35-3-14,14>>^ Com os seus próprios bastões furaste [a] cabeça dos seus guerreiros [quando] avançaram tempestuosamente para espalhar-me. Sua rejubilação era a dos decididos a devorar o atribulado num esconderijo.

[[v35-3-15]]

^<<v35-3-15,15>>^ Avançaste através do mar [com] os teus cavalos, [através] da massa das vastas águas.

[[v35-3-16]]

^<<v35-3-16,16>>^ Ouvi, e meu ventre começou a ficar agitado; meus lábios tremeram diante do som; a podridão começou a penetrar-me nos ossos; e eu estava agitado na minha situação, de aguardar tranqüilamente^&#42;1^ o dia da aflição, a [sua] vinda sobre o povo, [para que] ele os acometesse.

[NOTE]
====
. “De gemer (lamentar) diante do”, KB, p. 602.
====

[[v35-3-17]]

^<<v35-3-17,17>>^ Ainda que [a] própria figueira não floresça e não haja produção nas videiras, o trabalho da oliveira realmente resulte em fracasso e os próprios socalcos realmente não produzam alimento, [o] rebanho seja separado do redil e não haja manada nos currais;

[[v35-3-18]]

^<<v35-3-18,18>>^ Ainda assim, no que se refere a mim, vou rejubilar com o próprio Jeová; vou jubilar com o Deus^&#42;1^ da minha salvação.

[NOTE]
====
. “Com o Deus da.” Hebr.: bE’·lo·héh.
====

[[v35-3-19]]

^<<v35-3-19,19>>^ Jeová, o Soberano Senhor, é minha energia vital; e ele fará os meus pés semelhantes aos das corças e me fará pisar nos meus altos.
Ao regente, nos meus instrumentos de cordas.

'''

xref:035-habacuque/035-habacuque-002.adoc#v35-2-0[&#60; Capítulo Anterior] | <<v35-3-0,Topo>> | xref:036-sofonias/036-sofonias-001.adoc#v36-1-0[Próximo Capítulo &#62;]