include::./index.adoc[]

[[v35-2-0]]
=== Habacuque, 2
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v35-2-1]]

^<<v35-2-1,1>>^ Vou ficar de pé no meu posto de vigilância e vou ficar postado sobre [o] baluarte^&#42;1^ e estarei vigiando para ver o que ele há de falar por^&#42;2^ mim e o que hei de replicar à minha repreensão.

[NOTE]
====
. “Baluarte.” Hebr.: ma·tsóhr; gr.: pé·tran, e sir.: ki’·fa’, “rocha”; lat.: mu·ni·ti·ó·nem, “fortificação”.
. Ou “com[igo], a [mim]”.
====

[[v35-2-2]]

^<<v35-2-2,2>>^ E Jeová passou a responder-me e a dizer: “Escreve [a] visão e assenta-a de modo claro em tábuas, para que aquele que a lê alto possa fazê-lo fluentemente.^&#42;1^

[NOTE]
====
. Lit.: “possa correr”.
====

[[v35-2-3]]

^<<v35-2-3,3>>^ Porque [a] visão ainda é para o tempo designado e prossegue arfando até o fim,^&#42;1^ e não mentirá. Ainda que se demore, continua na expectativa dela; pois cumprir-se-á sem falta. Não tardará.

[NOTE]
====
. “É uma revelação para o fim”, mediante uma ligeira correção.
====

[[v35-2-4]]

^<<v35-2-4,4>>^ “Eis que a sua alma^&#42;1^ ficou inchada; não tem sido reta no seu íntimo.^&#42;2^ Mas, quanto ao justo, continuará a viver pela sua fidelidade.

[NOTE]
====
. “Sua alma.” Hebr.: naf·shóh; lat.: á·ni·ma. Veja Ap. 4A.
. “Se alguém retroceder, minha alma [gr.: psy·khé] não terá prazer nele”, LXX.
====

[[v35-2-5]]

^<<v35-2-5,5>>^ E deveras, visto que o vinho age traiçoeiramente, o varão vigoroso é pretensioso; e não atingirá seu alvo, aquele que ampliou a sua alma como o Seol^&#42;1^ e que é como a morte e não pode ser saciado. E ele continua a ajuntar a si todas as nações e reúne a si todos os povos.

[NOTE]
====
. “Como o Seol.” Hebr.: kish·’óhl; gr.: haí·des; sir.: shiul; lat.: in·fér·nus. Veja Ap. 4B.
====

[[v35-2-6]]

^<<v35-2-6,6>>^ Não encetarão estes mesmos, todos eles, uma expressão proverbial sobre ele e uma alusão [a ele], insinuações contra ele? E dir-se-á:
“‘Ai daquele que multiplica o que não é seu — oh! até quando! — e que se endivida pesadamente!

[[v35-2-7]]

^<<v35-2-7,7>>^ Não se levantarão repentinamente os que reivindicam juros de ti e [não] acordarão os que te sacodem violentamente, e [não] te tornarás certamente para eles algo a ser rapinado?

[[v35-2-8]]

^<<v35-2-8,8>>^ Porque tu mesmo assolaste muitas nações, todos os remanescentes dos povos te assolarão, por causa do derramamento de sangue do gênero humano^&#42;1^ e da violência [feita à] terra, [à] vila e a todos os que moram nela.

[NOTE]
====
. Ou “homens terrenos”. Hebr.: ’a·dhám, sing., mas em sentido coletivo.
====

[[v35-2-9]]

^<<v35-2-9,9>>^ “‘Ai daquele que obtém lucro vil para a sua casa, a fim de colocar seu ninho no alto, para estar fora do alcance^&#42;1^ do que é calamitoso!

[NOTE]
====
. Lit.: “da palma [da mão]”. Hebr.: mik·káf.
====

[[v35-2-10]]

^<<v35-2-10,10>>^ Aconselhaste algo vergonhoso à tua casa, o corte de muitos povos; e tua alma está pecando.

[[v35-2-11]]

^<<v35-2-11,11>>^ Pois de dentro da parede clamará em queixume a própria pedra e do madeiramento lhe responderá o próprio caibro.^&#42;1^

[NOTE]
====
. Possivelmente “o estuque”.
====

[[v35-2-12]]

^<<v35-2-12,12>>^ “‘Ai daquele que constrói uma cidade com derramamento de sangue,^&#42;1^ e que estabeleceu firmemente uma vila por meio de injustiça!

[NOTE]
====
. Lit.: “sangues”.
====

[[v35-2-13]]

^<<v35-2-13,13>>^ Ora! Não é da parte de Jeová dos exércitos^&#42;1^ que [os] povos labutam apenas para o fogo e que [os] grupos nacionais se cansam meramente em vão?

[NOTE]
====
. “Jeová dos exércitos”, MTVg; LXX: “Jeová Todo-poderoso.”
====

[[v35-2-14]]

^<<v35-2-14,14>>^ Pois a terra se encherá do conhecimento da glória de Jeová^&#42;1^ assim como as próprias águas cobrem [o] mar.

[NOTE]
====
. Veja Ap. 1C sec. 2.
====

[[v35-2-15]]

^<<v35-2-15,15>>^ “‘Ai daquele que dá aos seus companheiros algo para beber, agregando [a isso] teu furor^&#42;1^ e tua ira, a fim de embriagá-los, com o objetivo de olhar para as suas vergonhas.

[NOTE]
====
. “Agregando [a isso] teu furor.” Hebr.: מספ]ח[ חמתך; com a omissão da possível ditografia do ח: “da tigela [ou: taça] do teu furor”.
====

[[v35-2-16]]

^<<v35-2-16,16>>^ Certamente te fartarás com desonra em vez de com glória. Bebe também tu mesmo e sê considerado incircunciso. O copo da direita de Jeová^&#42;1^ chegará na ronda a ti e haverá ignomínia sobre a tua glória;

[NOTE]
====
. Veja Ap. 1C sec. 2.
====

[[v35-2-17]]

^<<v35-2-17,17>>^ pois cobrir-te-á a violência [feita] ao Líbano e a rapacidade contra [os] animais que os aterrorizam, por causa do derramamento de sangue do gênero humano^&#42;1^ e da violência [feita à] terra, à vila e a todos os que moram nela.

[NOTE]
====
. Ou “homem terreno”. Hebr.: ’a·dhám.
====

[[v35-2-18]]

^<<v35-2-18,18>>^ De que proveito tem sido a imagem esculpida, quando foi esculpida por aquele que a formou, uma estátua fundida e instrutora de falsidade, quando o formador da sua forma confia nela a ponto de fazer deuses que nada valem,^&#42;1^ que não podem falar?

[NOTE]
====
. Ou “deuses inúteis”. Hebr.: ’eli·lím; LXX: “ídolos”.
====

[[v35-2-19]]

^<<v35-2-19,19>>^ “‘Ai daquele que diz ao pedaço de pau: “Oh! acorda!” à pedra muda: “Oh! desperta! Ela mesma dará instrução”! Eis que está revestida de ouro e de prata, e não há absolutamente nenhum fôlego^&#42;1^ dentro dela.

[NOTE]
====
. “Fôlego.” Hebr.: rú·ahh; gr.: pneú·ma; lat.: spí·ri·tus.
====

[[v35-2-20]]

^<<v35-2-20,20>>^ Mas Jeová^&#42;1^ está no seu santo templo.^&#42;2^ Cala-te diante dele, toda a terra!’”

[NOTE]
====
. Veja Ap. 1C sec. 2.
. Ou “no templo de sua santidade”. Hebr.: beheh·khál qodh·shóh; gr.: na·oí ha·gí·oi. Veja Mt 23:16 n.
====

'''

xref:035-habacuque/035-habacuque-001.adoc#v35-1-0[&#60; Capítulo Anterior] | <<v35-2-0,Topo>> | xref:035-habacuque/035-habacuque-003.adoc#v35-3-0[Próximo Capítulo &#62;]