include::./index.adoc[]

[[v33-4-0]]
=== Miqueias, 4
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v33-4-1]]

^<<v33-4-1,1>>^ E na parte final dos dias terá de acontecer [que] o monte da casa de Jeová ficará firmemente estabelecido acima do cume dos montes e certamente se elevará acima dos morros; e a ele terão de afluir os povos.

[[v33-4-2]]

^<<v33-4-2,2>>^ E muitas nações certamente irão e dirão: “Vinde, e subamos ao monte de Jeová e à casa do Deus de Jacó; e ele nos instruirá sobre os seus caminhos e nós andaremos^&#42;1^ nas suas veredas.” Pois de Sião sairá a lei e de Jerusalém a palavra de Jeová.

[NOTE]
====
. Ou “iremos”.
====

[[v33-4-3]]

^<<v33-4-3,3>>^ E ele certamente fará julgamento entre muitos povos e resolverá as questões com respeito a poderosas nações longínquas. E terão de forjar das suas espadas relhas de arado, e das suas lanças, podadeiras. Não levantarão espada, nação contra nação, nem aprenderão mais a guerra.

[[v33-4-4]]

^<<v33-4-4,4>>^ E realmente sentar-se-ão,^&#42;1^ cada um^&#42;2^ debaixo da sua videira e debaixo da sua figueira, e não haverá quem [os] faça tremer; porque a própria boca de Jeová^&#42;3^ dos exércitos^&#42;4^ falou [isso].

[NOTE]
====
. Ou “morarão”.
. “Cada um.” Hebr.: ’ish.
. Veja Ap. 1C sec. 2.
. “Jeová dos exércitos”, MTVg; LXX: “Jeová Todo-poderoso.”
====

[[v33-4-5]]

^<<v33-4-5,5>>^ Porque todos os povos, da sua parte, andarão cada um no nome de seu deus;^&#42;1^ mas nós, da nossa parte, andaremos no nome de Jeová,^&#42;2^ nosso Deus,^&#42;3^ por tempo indefinido, para todo o sempre.^&#42;4^

[NOTE]
====
. Ou “seus deuses”. Hebr.: ’elo·háv; sir.: ’a·la·héh; lat.: dé·i.
. Veja Ap. 1C sec. 2.
. “Nosso Deus.” Hebr.: ’Elo·héh·nu; gr.: The·oú; lat.: Dé·i.
. “Para todo o sempre.” Veja Êx 15:18.
====

[[v33-4-6]]

^<<v33-4-6,6>>^ “Naquele dia”, é a pronunciação de Jeová, “vou ajuntar aquela que manquejava; e vou reunir a que estava dispersa, sim, aquela que tratei mal.

[[v33-4-7]]

^<<v33-4-7,7>>^ E certamente constituirei aquela que manquejava em um restante e aquela que fora removida para longe em uma nação poderosa; e Jeová^&#42;1^ realmente reinará sobre eles no monte Sião, desde agora e por tempo indefinido.

[NOTE]
====
. Veja Ap. 1C sec. 2.
====

[[v33-4-8]]

^<<v33-4-8,8>>^ “E quanto a ti,^&#42;1^ ó torre da grei,^&#42;2^ outeiro^&#42;3^ da filha de Sião, chegará até a ti, sim, certamente chegará o primeiro^&#42;4^ domínio, o reino pertencente à filha de Jerusalém.

[NOTE]
====
. “Ti”, hebr. masc. sing.
. Ou “de Éder”. Veja Gên 35:21, onde ocorre “torre de Éder”.
. Hebr.: ‛ó·fel, isto é, um morro ou uma colina. Veja 2Rs 5:24 n.
. Ou “anterior”.
====

[[v33-4-9]]

^<<v33-4-9,9>>^ “Ora, por que é que continuas^&#42;1^ a bradar? Não há rei em ti ou pereceu o teu próprio conselheiro, de modo que foste tomada de dores semelhantes às da mulher que dá à luz?

[NOTE]
====
. “Continuas”, hebr. fem. sing.
====

[[v33-4-10]]

^<<v33-4-10,10>>^ Tem severas dores e irrompe, ó filha de Sião, como a mulher que dá à luz, pois agora sairás duma vila e terás de residir no campo. E terás de chegar até Babilônia.^&#42;1^ Ali serás livrada. Ali Jeová te comprará de volta da palma da mão dos teus inimigos.

[NOTE]
====
. “Babilônia”, LXXVg; MTSy: “Babel”.
====

[[v33-4-11]]

^<<v33-4-11,11>>^ “E agora certamente serão ajuntadas contra ti muitas nações, os que dizem: ‘Seja poluída e olhem os nossos olhos para Sião.’

[[v33-4-12]]

^<<v33-4-12,12>>^ Mas, quanto a eles, não chegaram a conhecer os pensamentos de Jeová e não chegaram a entender seu conselho; pois ele certamente os reunirá na eira quais gavelas de cereal recém-segado.

[[v33-4-13]]

^<<v33-4-13,13>>^ “Levanta-te e trilha, ó filha de Sião; pois mudarei teu chifre em ferro e mudarei teus cascos em cobre, e hás de pulverizar muitos povos; e realmente devotarás a Jeová seu lucro injusto por meio duma proscrição, e seus recursos ao [verdadeiro] Senhor^&#42;1^ de toda a terra.”

[NOTE]
====
. “Ao [verdadeiro] Senhor.” Ca(hebr.): לאֲדוֹן (la·’Adhóhn); Leningrad B 19A(hebr.): לאֲדוֹן (la·’Adhóhn); gr.: Ky·rí·oi; sir.: leMa·ra’; lat.: Dó·mi·no. Veja Ap. 1H.
====

'''

xref:033-miqueias/033-miqueias-003.adoc#v33-3-0[&#60; Capítulo Anterior] | <<v33-4-0,Topo>> | xref:033-miqueias/033-miqueias-005.adoc#v33-5-0[Próximo Capítulo &#62;]