include::./index.adoc[]

[[v33-3-0]]
=== Miqueias, 3
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v33-3-1]]

^<<v33-3-1,1>>^ E passei a dizer: “Ouvi, por favor, vós cabeças de Jacó e vós comandantes da casa de Israel. Não é vosso negócio conhecerdes a justiça?

[[v33-3-2]]

^<<v33-3-2,2>>^ Vós odiadores do que é bom e amantes da maldade, arrancando das pessoas a sua pele e seu organismo de cima dos seus ossos;

[[v33-3-3]]

^<<v33-3-3,3>>^ vós, os que comestes também o organismo de meu povo e lhes tirastes a própria pele, e despedaçastes até os seus ossos, e [os] fizestes em pedaços como aquilo que está na panela de boca larga e como carne dentro dum caldeirão.

[[v33-3-4]]

^<<v33-3-4,4>>^ Naquele tempo clamarão a Jeová por socorro, mas ele não lhes responderá. E naquele tempo esconderá deles a sua face, conforme a maldade que praticaram nas suas ações.

[[v33-3-5]]

^<<v33-3-5,5>>^ “Assim disse Jeová contra os profetas que fazem meu povo transviar-se,^&#42;1^ que mordem com os seus dentes e que realmente clamam: ‘Paz!’, que, quando alguém não põe [nada] nas suas bocas, então santificam realmente a guerra contra ele:

[NOTE]
====
. Ou “errar”.
====

[[v33-3-6]]

^<<v33-3-6,6>>^ ‘Portanto, vós tereis noite, de modo que não haverá visão; e tereis escuridão, para que não se pratique a adivinhação. E o sol há de se pôr sobre os profetas e o dia terá de escurecer-se sobre eles.

[[v33-3-7]]

^<<v33-3-7,7>>^ E os visionários terão de ficar envergonhados e os adivinhos certamente ficarão desapontados. E terão de encobrir o bigode, todos eles, pois não há resposta da parte de Deus.’”^&#42;1^

[NOTE]
====
. “Deus.” Hebr.: ’Elo·hím; lat.: Dé·i.
====

[[v33-3-8]]

^<<v33-3-8,8>>^ E, por outro lado, eu mesmo fiquei cheio de poder com o espírito de Jeová, e de justiça e de potência, a fim de contar a Jacó a sua revolta e a Israel o seu pecado.

[[v33-3-9]]

^<<v33-3-9,9>>^ Por favor, ouvi isto, vós cabeças da casa de Jacó e vós comandantes da casa de Israel, os que detestais a justiça e que perverteis mesmo tudo o que é direito;

[[v33-3-10]]

^<<v33-3-10,10>>^ construindo Sião com atos de derramamento de sangue e Jerusalém com injustiça.

[[v33-3-11]]

^<<v33-3-11,11>>^ Seus próprios cabeças julgam apenas por suborno e seus próprios sacerdotes instruem somente por um preço, e seus próprios profetas praticam a adivinhação meramente por dinheiro;^&#42;1^ contudo, estribam-se em Jeová, dizendo: “Não está Jeová no nosso meio? Não virá sobre nós nenhuma calamidade.”

[NOTE]
====
. Ou “prata”.
====

[[v33-3-12]]

^<<v33-3-12,12>>^ Portanto, por vossa causa Sião será arada como mero campo e a própria Jerusalém se tornará meros montões de ruínas, e o monte da casa será como os altos duma floresta.

'''

xref:033-miqueias/033-miqueias-002.adoc#v33-2-0[&#60; Capítulo Anterior] | <<v33-3-0,Topo>> | xref:033-miqueias/033-miqueias-004.adoc#v33-4-0[Próximo Capítulo &#62;]