include::./index.adoc[]

[[v49-2-0]]
=== Efésios, 2
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v49-2-1]]

^<<v49-2-1,1>>^ Outrossim, [é a] vós [que Deus vivificou], embora estivésseis mortos nas vossas falhas e pecados,

[[v49-2-2]]

^<<v49-2-2,2>>^ nos quais andastes outrora segundo o sistema de coisas^&#42;1^ deste mundo,^&#42;2^ segundo o governante da autoridade do ar, o espírito que agora opera nos filhos da desobediência.

[NOTE]
====
. Ou “ordem de coisas”. Gr.: ai·ó·na; lat.: saé·cu·lum; J17(hebr.): dohr, “período, era; geração”; J18(hebr.): kemin·hágh, “segundo o costume”.
. “Mundo.” Gr.: kó·smou; J17,18,22(hebr.): ha·‛oh·lám, “o mundo”.
====

[[v49-2-3]]

^<<v49-2-3,3>>^ Sim, todos nós nos comportávamos outrora entre eles em harmonia com os desejos de nossa carne, fazendo as coisas da vontade da carne e dos pensamentos, e éramos por natureza filhos do furor, assim como os demais.

[[v49-2-4]]

^<<v49-2-4,4>>^ Mas Deus, que é rico em misericórdia, pelo seu grande amor com que nos amou,

[[v49-2-5]]

^<<v49-2-5,5>>^ vivificou-nos junto com o Cristo, mesmo quando estávamos mortos nas falhas — por benignidade imerecida é que fostes salvos —

[[v49-2-6]]

^<<v49-2-6,6>>^ e ele nos levantou junto e nos assentou junto nos lugares celestiais, em união com Cristo Jesus,

[[v49-2-7]]

^<<v49-2-7,7>>^ a fim de que, nos vindouros sistemas de coisas,^&#42;1^ se demonstrassem as riquezas sobrepujantes de sua benignidade imerecida na sua graça para conosco, em união com Cristo Jesus.

[NOTE]
====
. Ou “ordens de coisas”. Gr.: ai·ó·sin; lat.: saé·cu·lis.
====

[[v49-2-8]]

^<<v49-2-8,8>>^ Por esta benignidade imerecida é que fostes salvos por intermédio da fé; e isto não se deve a vós, é dádiva de Deus.

[[v49-2-9]]

^<<v49-2-9,9>>^ Não, não se deve a obras, a fim de que nenhum homem tenha base para jactância.

[[v49-2-10]]

^<<v49-2-10,10>>^ Pois nós somos produto de sua obra e, em união com Cristo Jesus, fomos criados para boas obras, que Deus preparou de antemão para andarmos nelas.

[[v49-2-11]]

^<<v49-2-11,11>>^ Portanto, persisti em lembrar-vos de que anteriormente éreis pessoas das nações quanto à carne; fostes chamados “incircuncisão” por aquilo que é chamado “circuncisão”, feita na carne, por mãos —

[[v49-2-12]]

^<<v49-2-12,12>>^ que naquele tempo específico estáveis sem Cristo, apartados do estado de Israel e estranhos aos pactos da promessa, e não tínheis esperança e estáveis sem Deus no mundo.^&#42;1^

[NOTE]
====
. “No mundo.” Gr.: en toi kó·smoi; J17,22(hebr.): ba·‛oh·lám.
====

[[v49-2-13]]

^<<v49-2-13,13>>^ Mas agora, em união com Cristo Jesus, vós, os que outrora estáveis longe, chegastes a estar perto pelo sangue do Cristo.

[[v49-2-14]]

^<<v49-2-14,14>>^ Pois ele é a nossa paz, aquele que das duas partes^&#42;1^ fez uma só e que destruiu o muro no meio,^&#42;2^ que os separava.

[NOTE]
====
. Ou “coisas”.
. Lit.: “muro do meio”. Esta é uma alusão ao muro (ou à mureta de treliça) na área do templo, que impedia a entrada dos adoradores gentios não santificados nos pátios internos, franqueados somente aos adoradores judaicos santificados. Segundo a Míxena (traduzida ao inglês por Danby, 1950, p. 592), esta mureta chamava-se “o Soregue”. Diz-se que este muro tinha a altura de 1,3 m. Veja Ap. 9F; também ad, sob o verbete “Templo”, no subtítulo: “O Pátio dos Gentios.”
====

[[v49-2-15]]

^<<v49-2-15,15>>^ Por meio de sua carne, ele aboliu a inimizade, a Lei de mandamentos, consistindo em decretos, para que dos dois povos, em união consigo mesmo, criasse um novo homem e fizesse paz;

[[v49-2-16]]

^<<v49-2-16,16>>^ e para que reconciliasse plenamente ambos os povos com Deus, em um só corpo, por intermédio da estaca de tortura, porque ele matara a inimizade por meio de si mesmo.^&#42;1^

[NOTE]
====
. Ou “dela”.
====

[[v49-2-17]]

^<<v49-2-17,17>>^ E ele veio e declarou as boas novas da paz a vós, os que estáveis longe, e paz aos [que estavam] perto,

[[v49-2-18]]

^<<v49-2-18,18>>^ porque, por intermédio dele, nós, ambos os povos, temos a aproximação ao Pai, por^&#42;1^ um só espírito.

[NOTE]
====
. Ou “em”.
====

[[v49-2-19]]

^<<v49-2-19,19>>^ Portanto, certamente não sois mais estranhos e residentes forasteiros, mas sois concidadãos dos santos e sois membros da família de Deus,

[[v49-2-20]]

^<<v49-2-20,20>>^ e fostes edificados sobre o alicerce^&#42;1^ dos apóstolos e profetas, ao passo que o próprio Cristo Jesus é a pedra angular de alicerce.

[NOTE]
====
. “Alicerce.” Gr.: the·me·lí·oi, dativo, sing.; lat. fun·da·mén·tum.
====

[[v49-2-21]]

^<<v49-2-21,21>>^ Em união com ele, o edifício inteiro, sendo harmoniosamente conjuntado,^&#42;1^ desenvolve-se num templo^&#42;2^ santo para Jeová.^&#42;3^

[NOTE]
====
. Lit.: “sendo conjuntado”.
. Ou “habitação (morada) divina”. Gr.: na·ón; lat.: tém·plum; J22(hebr.): heh·khál, “palácio; templo”.
. Veja Ap. 1D.
====

[[v49-2-22]]

^<<v49-2-22,22>>^ Em união com ele também vós estais sendo edificados juntamente como lugar para Deus habitar por espírito.

'''

xref:049-efesios/049-efesios-001.adoc#v49-1-0[&#60; Capítulo Anterior] | <<v49-2-0,Topo>> | xref:049-efesios/049-efesios-003.adoc#v49-3-0[Próximo Capítulo &#62;]