include::./index.adoc[]

[[v49-4-0]]
=== Efésios, 4
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v49-4-1]]

^<<v49-4-1,1>>^ Portanto eu, o prisioneiro no Senhor, suplico-vos que andeis dignamente da chamada com que fostes chamados,

[[v49-4-2]]

^<<v49-4-2,2>>^ com completa humildade mental e brandura, com longanimidade, suportando-vos uns aos outros em amor,

[[v49-4-3]]

^<<v49-4-3,3>>^ diligenciando observar a unidade do espírito no vínculo unificador da paz.

[[v49-4-4]]

^<<v49-4-4,4>>^ Há um só corpo e um só espírito, assim como também fostes chamados em uma só esperança a que fostes chamados;

[[v49-4-5]]

^<<v49-4-5,5>>^ um só Senhor, uma só fé, um só batismo;

[[v49-4-6]]

^<<v49-4-6,6>>^ um só Deus e Pai de todos, o qual é sobre todos, e por intermédio de todos, e em todos.

[[v49-4-7]]

^<<v49-4-7,7>>^ Ora, a cada um de nós se deu benignidade imerecida, conforme o Cristo repartiu a dádiva gratuita.

[[v49-4-8]]

^<<v49-4-8,8>>^ Por isso ele diz: “Quando ele ascendeu ao alto, levou consigo cativos; deu dádivas [em] homens.”^&#42;1^

[NOTE]
====
. Ou “consistindo em homens”, em harmonia com Sal 68:18 [68:19 M; 67:19 LXX]. Lit.: “aos homens”.
====

[[v49-4-9]]

^<<v49-4-9,9>>^ Ora, a expressão, “ele ascendeu”, o que significa senão que ele também desceu às regiões mais baixas, isto é, à terra?

[[v49-4-10]]

^<<v49-4-10,10>>^ O mesmo que desceu é também aquele que ascendeu muito acima de todos os céus, para que desse plenitude a todas as coisas.^&#42;1^

[NOTE]
====
. Ou “levasse todas as coisas ao cumprimento”.
====

[[v49-4-11]]

^<<v49-4-11,11>>^ E ele deu alguns como apóstolos, alguns como profetas, alguns como evangelizadores,^&#42;1^ alguns como pastores e instrutores,

[NOTE]
====
. Ou “missionários”. Gr.: eu·ag·ge·li·stás; lat.: e·van·ge·lí·stas.
====

[[v49-4-12]]

^<<v49-4-12,12>>^ visando o reajustamento^&#42;1^ dos santos para a obra ministerial, para a edificação do corpo do Cristo,

[NOTE]
====
. Ou: “colocar no alinhamento correto”.
====

[[v49-4-13]]

^<<v49-4-13,13>>^ até que todos alcancemos a unidade na fé e no conhecimento exato do Filho de Deus, como homem plenamente desenvolvido, à medida da estatura que pertence à plenitude do Cristo,

[[v49-4-14]]

^<<v49-4-14,14>>^ a fim de que não sejamos mais pequeninos, jogados como que por ondas e levados para cá e para lá por todo vento de ensino, pela velhacaria de homens, pela astúcia em maquinar o erro.

[[v49-4-15]]

^<<v49-4-15,15>>^ Mas, falando a verdade,^&#42;1^ cresçamos pelo amor em todas as coisas naquele que é a cabeça, Cristo.

[NOTE]
====
. Ou: “Mas, sendo verazes.”
====

[[v49-4-16]]

^<<v49-4-16,16>>^ Da parte dele, todo o corpo, por ser harmoniosamente conjuntado e feito cooperar^&#42;1^ por toda junta que dá o necessário, segundo o funcionamento de cada membro respectivo, na devida medida, produz o desenvolvimento do corpo para a edificação de si mesmo em amor.

[NOTE]
====
. Lit.: “feito harmonizar-se”.
====

[[v49-4-17]]

^<<v49-4-17,17>>^ Isto, portanto, digo, e dou testemunho no Senhor, que não mais andeis assim como também as nações andam na improficuidade das suas mentes,

[[v49-4-18]]

^<<v49-4-18,18>>^ ao passo que estão mentalmente em escuridão e apartados da vida que pertence a Deus, por causa da ignorância que há neles, por causa da insensibilidade dos seus corações.

[[v49-4-19]]

^<<v49-4-19,19>>^ Tendo ficado além de todo o senso moral, entregaram-se à conduta desenfreada^&#42;1^ para fazerem com ganância toda sorte de impureza.^&#42;2^

[NOTE]
====
. “À conduta desenfreada.” Gr.: tei a·sel·geí·ai, dativo, sing. Veja Gál 5:19 n.: “desenfreada”.
. Veja Gál 5:19 n.: “impureza”.
====

[[v49-4-20]]

^<<v49-4-20,20>>^ Mas vós não aprendestes que o Cristo seja assim,

[[v49-4-21]]

^<<v49-4-21,21>>^ se é que o ouvistes e fostes ensinados por meio dele, assim como a verdade está em Jesus,

[[v49-4-22]]

^<<v49-4-22,22>>^ de que deveis pôr de lado a velha personalidade que se conforma ao vosso procedimento anterior e que está sendo corrompida segundo os seus desejos enganosos;

[[v49-4-23]]

^<<v49-4-23,23>>^ mas que deveis ser feitos novos na força que ativa a vossa mente,^&#42;1^

[NOTE]
====
. Lit.: “ao espírito da vossa mente”.
====

[[v49-4-24]]

^<<v49-4-24,24>>^ e que vos deveis revestir da nova personalidade, que foi criada segundo a vontade de Deus, em verdadeira justiça e lealdade.

[[v49-4-25]]

^<<v49-4-25,25>>^ Sendo que agora pusestes de lado a falsidade, falai a verdade, cada um de vós com o seu próximo, porque somos membros que se pertencem uns aos outros.

[[v49-4-26]]

^<<v49-4-26,26>>^ Ficai furiosos,^&#42;1^ mas não pequeis; não se ponha o sol enquanto estais encolerizados,

[NOTE]
====
. Lit.: “Sede feitos furiosos.”
====

[[v49-4-27]]

^<<v49-4-27,27>>^ nem deis margem ao Diabo.

[[v49-4-28]]

^<<v49-4-28,28>>^ O gatuno não furte mais, antes, porém, trabalhe arduamente, fazendo com as mãos bom trabalho, a fim de que tenha algo para distribuir a alguém em necessidade.

[[v49-4-29]]

^<<v49-4-29,29>>^ Não saia da vossa boca nenhuma palavra pervertida, mas a que for boa para a edificação, conforme a necessidade, para que confira aos ouvintes aquilo que é favorável.

[[v49-4-30]]

^<<v49-4-30,30>>^ Também, não contristeis^&#42;1^ o espírito santo de Deus, com que fostes selados para um dia de livramento por meio de resgate.

[NOTE]
====
. Lit.: “não estejais entristecendo”.
====

[[v49-4-31]]

^<<v49-4-31,31>>^ Sejam tirados dentre vós toda a amargura maldosa, e ira, e furor, e brado, e linguagem ultrajante, junto com toda a maldade.

[[v49-4-32]]

^<<v49-4-32,32>>^ Mas, tornai-vos benignos uns para com os outros, ternamente compassivos, perdoando-vos liberalmente uns aos outros, assim como também Deus vos perdoou liberalmente por Cristo.

'''

xref:049-efesios/049-efesios-003.adoc#v49-3-0[&#60; Capítulo Anterior] | <<v49-4-0,Topo>> | xref:049-efesios/049-efesios-005.adoc#v49-5-0[Próximo Capítulo &#62;]