include::./index.adoc[]

[[v49-6-0]]
=== Efésios, 6
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v49-6-1]]

^<<v49-6-1,1>>^ Filhos, sede obedientes^&#42;1^ aos vossos pais em união com [o] Senhor,^&#42;2^ pois isto é justo:

[NOTE]
====
. Lit.: “estai obedecendo”.
. “Em união com [o] Senhor”, P46אADcVgSyh,pArm; BD° omitem isso.
====

[[v49-6-2]]

^<<v49-6-2,2>>^ “Honra a teu pai e [a tua] mãe”, que é o primeiro mandado com promessa:

[[v49-6-3]]

^<<v49-6-3,3>>^ “Para que te vá bem e perdures por longo tempo na terra.”

[[v49-6-4]]

^<<v49-6-4,4>>^ E vós, pais, não estejais irritando^&#42;1^ os vossos filhos, mas prossegui em criá-los na disciplina e na regulação mental^&#42;2^ de Jeová.^&#42;3^

[NOTE]
====
. Lit.: “não estejais provocando ao furor”.
. Lit.: “pôr mente em”.
. Veja Ap. 1D.
====

[[v49-6-5]]

^<<v49-6-5,5>>^ Vós, escravos, sede obedientes aos que são os [vossos] amos em sentido carnal, com temor e tremor, na sinceridade dos vossos corações, como ao Cristo,

[[v49-6-6]]

^<<v49-6-6,6>>^ não apenas ostensivamente, como os que agradam a homens, mas como escravos de Cristo, fazendo de toda a alma a vontade de Deus.

[[v49-6-7]]

^<<v49-6-7,7>>^ Sede escravos com boas inclinações, como a Jeová^&#42;1^ e não a homens,

[NOTE]
====
. Veja Ap. 1D.
====

[[v49-6-8]]

^<<v49-6-8,8>>^ pois sabeis que cada um, qualquer que seja o bem que fizer, receberá isso de volta de Jeová,^&#42;1^ quer seja escravo, quer homem livre.

[NOTE]
====
. Veja Ap. 1D.
====

[[v49-6-9]]

^<<v49-6-9,9>>^ Também vós, amos, persisti em fazer as mesmas coisas para com eles, deixando as ameaças, pois sabeis que o Amo,^&#42;1^ tanto deles como vosso, está nos céus, e com ele não há parcialidade.

[NOTE]
====
. Ou “Senhor”.
====

[[v49-6-10]]

^<<v49-6-10,10>>^ Finalmente, prossegui adquirindo poder no Senhor e na potência da sua força.

[[v49-6-11]]

^<<v49-6-11,11>>^ Revesti-vos da armadura completa de Deus, para que vos possais manter firmes contra as maquinações^&#42;1^ do Diabo;

[NOTE]
====
. Ou “artimanhas”. Gr.: me·tho·dí·as; lat.: in·sí·di·as.
====

[[v49-6-12]]

^<<v49-6-12,12>>^ porque temos uma pugna, não contra sangue e carne, mas contra os governos, contra as autoridades, contra os governantes mundiais^&#42;1^ desta escuridão, contra as forças espirituais iníquas nos lugares celestiais.

[NOTE]
====
. Lit.: “poderosos do mundo”. Gr.: ko·smo·krá·to·ras.
====

[[v49-6-13]]

^<<v49-6-13,13>>^ Por esta razão, tomai a armadura completa^&#42;1^ de Deus, para que possais resistir no dia iníquo, e, depois de terdes feito cabalmente todas as coisas, manter-vos firmes.

[NOTE]
====
. Lit.: “a panóplia”. Gr.: ten pa·no·plí·an; lat.: ar·ma·tú·ram.
====

[[v49-6-14]]

^<<v49-6-14,14>>^ Portanto, mantende-vos firmes, tendo os vossos lombos cingidos com a verdade, e vestindo a couraça da justiça,

[[v49-6-15]]

^<<v49-6-15,15>>^ e tendo os vossos pés calçados do equipamento^&#42;1^ das boas novas de paz.

[NOTE]
====
. “Do equipamento.” Lit.: “em prontidão; em [estado de] preparação”.
====

[[v49-6-16]]

^<<v49-6-16,16>>^ Acima de tudo, tomai o grande escudo da fé, com que podereis apagar todos os projéteis ardentes do iníquo.

[[v49-6-17]]

^<<v49-6-17,17>>^ Aceitai também o capacete de salvação e a espada do espírito, isto é, a palavra de Deus,

[[v49-6-18]]

^<<v49-6-18,18>>^ ao passo que com toda forma de oração e súplica, em todas as ocasiões, fazeis orações em espírito. E, para este fim, mantende-vos despertos com toda a constância e com súplica a favor de todos os santos,

[[v49-6-19]]

^<<v49-6-19,19>>^ também por mim, para que me seja dada a capacidade de falar, ao abrir a minha boca com franqueza no falar, a fim de tornar conhecido o segredo sagrado das boas novas,

[[v49-6-20]]

^<<v49-6-20,20>>^ para as quais atuo como embaixador em cadeias; para que, em conexão com ele, eu fale com denodo^&#42;1^ assim como devo falar.

[NOTE]
====
. Ou “com franqueza no falar”.
====

[[v49-6-21]]

^<<v49-6-21,21>>^ Agora, a fim de que saibais também dos meus assuntos, como estou passando, Tíquico, amado irmão e ministro fiel no Senhor, vos fará saber tudo.

[[v49-6-22]]

^<<v49-6-22,22>>^ Eu o envio a vós com este mesmo fim, para que saibais das coisas que têm que ver conosco e para que ele console os vossos corações.

[[v49-6-23]]

^<<v49-6-23,23>>^ Que os irmãos tenham paz e amor, com fé, da parte de Deus, o Pai, e do Senhor Jesus Cristo.

[[v49-6-24]]

^<<v49-6-24,24>>^ A benignidade imerecida seja com todos os que amam o nosso Senhor Jesus Cristo em incorrupção.

'''

xref:049-efesios/049-efesios-005.adoc#v49-5-0[&#60; Capítulo Anterior] | <<v49-6-0,Topo>> | xref:050-filipenses/050-filipenses-001.adoc#v50-1-0[Próximo Capítulo &#62;]