include::./index.adoc[]

[[v49-3-0]]
=== Efésios, 3
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v49-3-1]]

^<<v49-3-1,1>>^ Por causa disso, eu, Paulo, o prisioneiro de Cristo Jesus em benefício de vós, as pessoas das nações —

[[v49-3-2]]

^<<v49-3-2,2>>^ se realmente ouvistes [falar] da mordomia^&#42;1^ da benignidade imerecida de Deus, que me foi dada, visando a vós,

[NOTE]
====
. Ou “administração”. Veja 1:10 n.: “administração”.
====

[[v49-3-3]]

^<<v49-3-3,3>>^ de que o segredo sagrado me foi dado a conhecer à maneira duma revelação, assim como já vos escrevi resumidamente.

[[v49-3-4]]

^<<v49-3-4,4>>^ Em face disso, ao lerdes isso, podeis dar-vos conta da compreensão que eu tenho do segredo sagrado do Cristo.

[[v49-3-5]]

^<<v49-3-5,5>>^ Em outras gerações, este [segredo] não foi dado a conhecer aos filhos dos homens assim como agora tem sido revelado aos seus santos apóstolos e profetas, por espírito,

[[v49-3-6]]

^<<v49-3-6,6>>^ a saber, que os das nações haviam de ser co-herdeiros e membros associados do corpo, e co-participantes conosco da promessa, em união com Cristo Jesus, por intermédio das boas novas.

[[v49-3-7]]

^<<v49-3-7,7>>^ Eu me tornei ministro disso segundo a dádiva gratuita da benignidade imerecida de Deus, que me foi dada segundo o modo em que opera o seu poder.

[[v49-3-8]]

^<<v49-3-8,8>>^ A mim, um homem menor que o mínimo de todos os santos, foi dada esta benignidade imerecida para que eu declarasse às nações as boas novas acerca das riquezas insondáveis do Cristo,

[[v49-3-9]]

^<<v49-3-9,9>>^ e para que eu fizesse os homens ver^&#42;1^ como se administra o segredo sagrado,^&#42;2^ que desde o passado indefinido tem estado escondido em Deus, que criou todas as coisas.

[NOTE]
====
. Ou “trouxesse à luz”.
. Lit.: “qual é a administração doméstica do mistério (segredo sagrado)”.
====

[[v49-3-10]]

^<<v49-3-10,10>>^ [Isto se deu] com o fim de que, por intermédio da congregação, se desse agora a conhecer aos governos e às autoridades nos lugares celestiais a grandemente diversificada sabedoria de Deus,

[[v49-3-11]]

^<<v49-3-11,11>>^ segundo o propósito eterno que ele formou em conexão com o Cristo, Jesus, nosso Senhor,

[[v49-3-12]]

^<<v49-3-12,12>>^ por meio de quem temos esta franqueza no falar e uma aproximação confiante por intermédio de nossa fé nele.

[[v49-3-13]]

^<<v49-3-13,13>>^ Em vista disso, peço-vos que não desistais por causa dessas minhas tribulações em vosso benefício, pois estas significam^&#42;1^ glória para vós.

[NOTE]
====
. Ou “pois isto significa”. Lit.: “que é”.
====

[[v49-3-14]]

^<<v49-3-14,14>>^ Por causa disso dobro os joelhos diante do Pai,

[[v49-3-15]]

^<<v49-3-15,15>>^ a quem toda família no céu e na terra deve o seu nome,

[[v49-3-16]]

^<<v49-3-16,16>>^ com o fim de que ele vos conceda, segundo as riquezas de sua glória, que sejais feitos poderosos no homem que sois no íntimo, com poder por intermédio de seu espírito,

[[v49-3-17]]

^<<v49-3-17,17>>^ para que o Cristo more em vossos corações, com^&#42;1^ amor, por intermédio da [vossa] fé; para que fiqueis arraigados e estabelecidos sobre o alicerce,

[NOTE]
====
. Ou “em”.
====

[[v49-3-18]]

^<<v49-3-18,18>>^ a fim de que sejais cabalmente capazes de compreender, junto com todos os santos, qual é a largura, e o comprimento, e a altura, e a profundidade,

[[v49-3-19]]

^<<v49-3-19,19>>^ e para que conheçais o amor do Cristo, que ultrapassa o conhecimento, a fim de que estejais cheios de toda^&#42;1^ a plenitude dada por Deus.

[NOTE]
====
. Ou “sejais enchidos em toda”.
====

[[v49-3-20]]

^<<v49-3-20,20>>^ Ora, àquele que, segundo o seu poder que opera em nós, pode fazer mais do que superabundantemente além de todas as coisas que peçamos ou concebamos,

[[v49-3-21]]

^<<v49-3-21,21>>^ a ele seja a glória por meio da congregação e por meio de Cristo Jesus, por todas as gerações, para todo o sempre. Amém.

'''

xref:049-efesios/049-efesios-002.adoc#v49-2-0[&#60; Capítulo Anterior] | <<v49-3-0,Topo>> | xref:049-efesios/049-efesios-004.adoc#v49-4-0[Próximo Capítulo &#62;]