include::./index.adoc[]

[[v49-5-0]]
=== Efésios, 5
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v49-5-1]]

^<<v49-5-1,1>>^ Portanto, tornai-vos imitadores de Deus, como filhos amados,

[[v49-5-2]]

^<<v49-5-2,2>>^ e prossegui andando em amor, assim como também o Cristo vos amou e se entregou por vós como oferta e sacrifício a Deus para ser cheiro fragrante.

[[v49-5-3]]

^<<v49-5-3,3>>^ A fornicação e a impureza de toda sorte, ou a ganância,^&#42;1^ não sejam nem mesmo mencionadas entre vós, assim como é próprio dum povo santo;

[NOTE]
====
. Ou “cobiça”. Lit.: “ter mais”, isto é, o desejo de ter mais; insaciabilidade. Gr.: ple·o·ne·xí·a.
====

[[v49-5-4]]

^<<v49-5-4,4>>^ nem conduta vergonhosa, nem conversa tola, nem piadas obscenas, coisas que não são decentes, mas, antes, ações de graças.

[[v49-5-5]]

^<<v49-5-5,5>>^ Pois isso sabeis, reconhecendo-o por vós mesmos, que nenhum fornicador, nem pessoa impura, nem pessoa gananciosa — que significa [ser] idólatra — tem qualquer herança no reino do Cristo e de Deus.^&#42;1^

[NOTE]
====
. Veja Ap. 6E.
====

[[v49-5-6]]

^<<v49-5-6,6>>^ Nenhum homem vos engane com palavras vãs, pois, por causa das coisas já mencionadas^&#42;1^ vem o furor de Deus sobre os filhos da desobediência.

[NOTE]
====
. Ou “por causa destas coisas”.
====

[[v49-5-7]]

^<<v49-5-7,7>>^ Portanto, não vos torneis co-participantes deles;

[[v49-5-8]]

^<<v49-5-8,8>>^ pois outrora éreis escuridão, mas agora sois luz em conexão com [o] Senhor. Prossegui andando como filhos da luz,

[[v49-5-9]]

^<<v49-5-9,9>>^ pois os frutos da luz consistem em toda sorte de bondade, e justiça, e verdade.

[[v49-5-10]]

^<<v49-5-10,10>>^ Persisti em certificar-vos do que é aceitável para o Senhor;

[[v49-5-11]]

^<<v49-5-11,11>>^ e cessai de compartilhar com [eles] nas obras infrutíferas que pertencem à escuridão, mas, antes, até mesmo [as] repreendei,

[[v49-5-12]]

^<<v49-5-12,12>>^ pois as coisas que eles realizam em secreto são vergonhosas até mesmo para relatar.

[[v49-5-13]]

^<<v49-5-13,13>>^ Ora, todas as coisas que estão sendo repreendidas são tornadas manifestas pela luz, pois tudo o que está sendo manifestado é luz.

[[v49-5-14]]

^<<v49-5-14,14>>^ Por isso ele diz: “Desperta, ó tu que dormes, e surge dentre os mortos, e o Cristo brilhará sobre ti.”

[[v49-5-15]]

^<<v49-5-15,15>>^ Assim, mantende estrita vigilância para não andardes como néscios, mas como sábios,

[[v49-5-16]]

^<<v49-5-16,16>>^ comprando para vós todo o tempo oportuno, porque os dias são iníquos.

[[v49-5-17]]

^<<v49-5-17,17>>^ Por esta razão, deixai de ficar desarrazoados, mas prossegui percebendo qual é a vontade de Jeová.^&#42;1^

[NOTE]
====
. “De Jeová”, J7,8; אD(gr.): tou Ky·rí·ou; AVgcSyp: “de Deus”; B: “de nosso Senhor”; P46: “do Cristo”. Veja Ap. 1D.
====

[[v49-5-18]]

^<<v49-5-18,18>>^ Também, não fiqueis embriagados de vinho, em que há devassidão, mas ficai cheios de espírito,

[[v49-5-19]]

^<<v49-5-19,19>>^ falando a vós mesmos com salmos e louvores a Deus, e com cânticos espirituais, cantando e acompanhando-vos com música nos vossos corações, para Jeová,^&#42;1^

[NOTE]
====
. Veja Ap. 1D.
====

[[v49-5-20]]

^<<v49-5-20,20>>^ no nome de nosso Senhor Jesus Cristo, dando sempre graças por todas as coisas a nosso^&#42;1^ Deus e Pai.

[NOTE]
====
. Lit.: “ao”.
====

[[v49-5-21]]

^<<v49-5-21,21>>^ Estai sujeitos uns aos outros, no temor de Cristo.

[[v49-5-22]]

^<<v49-5-22,22>>^ As esposas estejam sujeitas aos seus maridos como ao Senhor,

[[v49-5-23]]

^<<v49-5-23,23>>^ porque o marido é cabeça de sua esposa, assim como também o Cristo é cabeça da congregação, sendo ele salvador [deste] corpo.

[[v49-5-24]]

^<<v49-5-24,24>>^ De fato, assim como a congregação está sujeita ao Cristo, também as esposas estejam [sujeitas] aos seus maridos, em tudo.

[[v49-5-25]]

^<<v49-5-25,25>>^ Maridos, continuai a amar as vossas esposas, assim como também o Cristo amou a congregação e se entregou por ela,

[[v49-5-26]]

^<<v49-5-26,26>>^ para que a santificasse, purificando-a com o banho de água por meio da palavra,

[[v49-5-27]]

^<<v49-5-27,27>>^ a fim de que apresentasse a congregação a si mesmo em todo o seu esplendor, não tendo nem mancha nem ruga, nem qualquer dessas coisas, mas para que fosse santa e sem mácula.

[[v49-5-28]]

^<<v49-5-28,28>>^ Deste modo, os maridos devem estar amando as suas esposas como aos seus próprios corpos. Quem ama a sua esposa, ama a si próprio,

[[v49-5-29]]

^<<v49-5-29,29>>^ pois nenhum homem jamais odiou a sua própria carne; mas ele a alimenta e acalenta, assim como também o Cristo faz com a congregação,

[[v49-5-30]]

^<<v49-5-30,30>>^ porque somos membros de seu corpo.

[[v49-5-31]]

^<<v49-5-31,31>>^ “Por esta razão deixará o homem [seu] pai e [sua] mãe e se apegará à sua esposa, e os dois se tornarão uma só carne.”

[[v49-5-32]]

^<<v49-5-32,32>>^ É grande este segredo sagrado. Agora estou falando com respeito a Cristo e à congregação.

[[v49-5-33]]

^<<v49-5-33,33>>^ Não obstante, também cada um de vós, individualmente, ame a sua esposa como a si próprio; por outro lado, a esposa deve ter profundo respeito pelo seu marido.

'''

xref:049-efesios/049-efesios-004.adoc#v49-4-0[&#60; Capítulo Anterior] | <<v49-5-0,Topo>> | xref:049-efesios/049-efesios-006.adoc#v49-6-0[Próximo Capítulo &#62;]