include::./index.adoc[]

[[v49-1-0]]
=== Efésios, 1
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v49-1-1]]

^<<v49-1-1,1>>^ Paulo, apóstolo de Cristo Jesus, pela vontade de Deus, aos santos que estão [em Éfeso]^&#42;1^ e fiéis em união com Cristo Jesus:

[NOTE]
====
. “Em Éfeso”, אcABcDVgSyh,p; P46א°B° omitem isso.
====

[[v49-1-2]]

^<<v49-1-2,2>>^ Que tenhais benignidade imerecida e paz da parte de Deus, nosso Pai, e do Senhor Jesus Cristo.

[[v49-1-3]]

^<<v49-1-3,3>>^ Bendito seja o Deus e Pai de nosso Senhor Jesus Cristo, pois ele nos tem abençoado com toda bênção espiritual nos lugares celestiais em união com Cristo,

[[v49-1-4]]

^<<v49-1-4,4>>^ assim como nos tem escolhido em união com ele antes da fundação^&#42;1^ do mundo, para que fôssemos santos e sem mácula diante dele em amor.

[NOTE]
====
. Lit.: “do lançamento para baixo [de semente]”. Gr.: ka·ta·bo·lés.
====

[[v49-1-5]]

^<<v49-1-5,5>>^ Pois ele nos predeterminou^&#42;1^ para a adoção como filhos para si mesmo, por intermédio de Jesus Cristo, segundo o beneplácito de sua vontade,

[NOTE]
====
. Ou “sem mácula diante dele. Pois em amor (5) ele nos predeterminou”.
====

[[v49-1-6]]

^<<v49-1-6,6>>^ em louvor de sua gloriosa benignidade imerecida, que ele nos concedeu bondosamente por meio do [seu] amado.

[[v49-1-7]]

^<<v49-1-7,7>>^ Mediante ele temos o livramento por meio de resgate, por intermédio do sangue desse, sim, o perdão de [nossas] falhas, segundo as riquezas de sua benignidade imerecida.

[[v49-1-8]]

^<<v49-1-8,8>>^ Esta ele fez abundar para conosco em toda a sabedoria e bom senso,

[[v49-1-9]]

^<<v49-1-9,9>>^ por^&#42;1^ nos fazer saber o segredo sagrado de sua vontade. É segundo o seu beneplácito, que ele se propôs em si mesmo,

[NOTE]
====
. “Por.” Ou “e”.
====

[[v49-1-10]]

^<<v49-1-10,10>>^ para uma administração^&#42;1^ no pleno limite dos tempos designados, a saber, ajuntar novamente^&#42;2^ todas as coisas no Cristo, as coisas nos céus e as coisas na terra. [Sim,] nele,

[NOTE]
====
. Lit.: “administração (gerência) doméstica”. Gr.: oi·ko·no·mí·an; lat.: di·spen·sa·ti·ó·nem. Veja Lu 12:42 n.
. “Ajuntar novamente.” Segundo o Greek-English Lexicon of the New Testament, de G. H. Thayer, quarta ed. (1901), p. 39: “reunir novamente para si”.
====

[[v49-1-11]]

^<<v49-1-11,11>>^ em união com quem também somos designados herdeiros, visto que fomos predeterminados segundo o propósito daquele que opera todas as coisas segundo o modo aconselhado por sua vontade,

[[v49-1-12]]

^<<v49-1-12,12>>^ a fim de que servíssemos para o louvor da sua glória, nós, os que temos sido os primeiros a esperar^&#42;1^ no Cristo.

[NOTE]
====
. Ou “nós os que esperamos de antemão”.
====

[[v49-1-13]]

^<<v49-1-13,13>>^ Mas vós também esperastes nele, depois de terdes ouvido a palavra da verdade, as boas novas acerca da vossa salvação. Por meio dele, também, depois de terdes crido,^&#42;1^ fostes selados com o prometido espírito santo,

[NOTE]
====
. Ou “depois de também terdes crido nele”.
====

[[v49-1-14]]

^<<v49-1-14,14>>^ que^&#42;1^ é penhor antecipado^&#42;2^ da nossa herança, com o propósito de livrar por meio dum resgate a propriedade do próprio [Deus],^&#42;3^ para o seu glorioso louvor.

[NOTE]
====
. “Que”, P46AB; אDVg: “quem”.
. Ou “sinal (pagamento) adiantado”. Gr.: ar·ra·bón; J18,22(hebr.): ‛e·ra·vóhn. Veja 2Co 1:22 n.
. Lit. só “a propriedade, para”.
====

[[v49-1-15]]

^<<v49-1-15,15>>^ É por isso que também eu, tendo ouvido [falar] da fé que tendes no Senhor Jesus e para com todos os santos,

[[v49-1-16]]

^<<v49-1-16,16>>^ não cesso de dar graças por vós. Continuo a mencionar-vos nas minhas orações,

[[v49-1-17]]

^<<v49-1-17,17>>^ para que o Deus de nosso Senhor Jesus Cristo, o Pai da glória, vos dê um espírito de sabedoria e de revelação^&#42;1^ no conhecimento exato dele,

[NOTE]
====
. Lit.: “exposição; exibição”. Gr.: a·po·ka·lý·pse·os.
====

[[v49-1-18]]

^<<v49-1-18,18>>^ tendo sido iluminados os olhos de vosso coração, para que saibais qual é a esperança a que fostes chamados por ele, quais são as gloriosas riquezas que ele segura como herança para^&#42;1^ os santos

[NOTE]
====
. Ou “que ele herda nos”.
====

[[v49-1-19]]

^<<v49-1-19,19>>^ e qual é a magnitude sobrepujante do seu poder para conosco, os que cremos. É segundo a operação da potência de sua força,

[[v49-1-20]]

^<<v49-1-20,20>>^ com que ele tem operado no caso do Cristo, quando o levantou dentre os mortos e o assentou à sua direita nos lugares celestiais,

[[v49-1-21]]

^<<v49-1-21,21>>^ muito acima de todo governo, e autoridade, e poder, e senhorio, e todo nome dado, não só neste sistema de coisas,^&#42;1^ mas também no que há de vir.

[NOTE]
====
. Ou “ordem de coisas”. Gr.: ai·ó·ni; lat.: saé·cu·lo; J17,18,22(hebr.): ba·‛oh·lám haz·zéh, “nesta ordem de coisas”.
====

[[v49-1-22]]

^<<v49-1-22,22>>^ Sujeitou também todas as coisas debaixo dos pés dele, e o fez cabeça sobre todas as coisas para a congregação,

[[v49-1-23]]

^<<v49-1-23,23>>^ a qual é o seu corpo, a plenitude daquele que em tudo preenche todas as coisas.

'''

xref:048-galatas/048-galatas-006.adoc#v48-6-0[&#60; Capítulo Anterior] | <<v49-1-0,Topo>> | xref:049-efesios/049-efesios-002.adoc#v49-2-0[Próximo Capítulo &#62;]