include::./index.adoc[]

[[v37-2-0]]
=== Ageu, 2
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v37-2-1]]

^<<v37-2-1,1>>^ No sétimo [mês], no vigésimo primeiro [dia] do mês, veio a haver a palavra de Jeová por intermédio de Ageu, o profeta, dizendo:

[[v37-2-2]]

^<<v37-2-2,2>>^ “Dize, por favor, a Zorobabel, filho de Sealtiel, governador de Judá, e a Josué, filho de Jeozadaque, o sumo sacerdote, e aos remanescentes do povo, dizendo:

[[v37-2-3]]

^<<v37-2-3,3>>^ ‘Quem resta entre vós que viu esta casa na sua glória anterior? E como a vedes agora? Não é, em comparação com aquela, como nada aos vossos olhos?’

[[v37-2-4]]

^<<v37-2-4,4>>^ “‘Mas agora, sê forte, ó Zorobabel’, é a pronunciação de Jeová, ‘e sê forte, ó Josué, filho de Jeozadaque, o sumo sacerdote’.
“‘E sede fortes, todos vós, povo da terra’,^&#42;1^ é a pronunciação de Jeová, ‘e trabalhai’.
“‘Pois eu estou convosco’, é a pronunciação de Jeová dos exércitos.

[NOTE]
====
. “Povo da terra.” Hebr.: ‛am ha·’á·rets. Posteriormente usado em sentido depreciativo. Veja Jo 7:47-49.
====

[[v37-2-5]]

^<<v37-2-5,5>>^ ‘[Lembrai-vos] da coisa^&#42;1^ que concluí^&#42;2^ convosco quando saístes do Egito e [quando] meu espírito estava posto entre vós. Não tenhais medo.’”

[NOTE]
====
. Lit.: “palavra”.
. Lit.: “cortei”.
====

[[v37-2-6]]

^<<v37-2-6,6>>^ “Pois assim disse Jeová dos exércitos: ‘Mais uma vez — dentro em pouco — e eu farei tremer os céus, e a terra, e o mar, e o solo seco.’

[[v37-2-7]]

^<<v37-2-7,7>>^ “‘E vou fazer tremer todas as nações,^&#42;1^ e terão de entrar as coisas desejáveis^&#42;2^ de todas as nações;^&#42;3^ e eu vou encher esta casa de glória’, disse Jeová dos exércitos.

[NOTE]
====
. Lit.: “E sacudirei todas as nações.”
. “Coisas desejáveis”, mediante uma mudança dos sinais vocálicos; M: “coisa desejável (preciosa)”, sing., mas evidentemente em sentido coletivo, porque esta palavra vem acompanhada por um verbo no pl.
. Ou “e elas, as coisas desejáveis de todas as nações, terão de entrar”.
====

[[v37-2-8]]

^<<v37-2-8,8>>^ “‘Minha é a prata e meu é o ouro’, é a pronunciação de Jeová dos exércitos.

[[v37-2-9]]

^<<v37-2-9,9>>^ “‘A glória desta última casa se tornará maior do [que a da] anterior’, disse Jeová dos exércitos.
“‘E darei paz neste lugar’, é a pronunciação de Jeová dos exércitos.”

[[v37-2-10]]

^<<v37-2-10,10>>^ No vigésimo quarto [dia] do nono [mês], no segundo ano de Dario, veio a haver a palavra de Jeová para Ageu, o profeta, dizendo:

[[v37-2-11]]

^<<v37-2-11,11>>^ “Assim disse Jeová dos exércitos: ‘Por favor, pergunta aos sacerdotes a respeito [da] lei, dizendo:

[[v37-2-12]]

^<<v37-2-12,12>>^ “Se um homem^&#42;1^ levar carne sagrada na aba da sua veste e ele realmente tocar com a [aba da] sua veste em pão, ou cozido, ou vinho, ou azeite, ou em qualquer tipo de alimento, tornar-se-á este santo?”’”
E os sacerdotes passaram a responder e a dizer: “Não!”

[NOTE]
====
. “Um homem.” Hebr.: ’ish.
====

[[v37-2-13]]

^<<v37-2-13,13>>^ E Ageu prosseguiu, dizendo: “Se alguém que ficou impuro por uma alma falecida^&#42;1^ tocar em alguma destas coisas, tornar-se-á ela impura?”
Os sacerdotes, por sua vez, responderam e disseram: “Tornar-se-á impura.”

[NOTE]
====
. Lit.: “uma alma”, isto é, uma alma morta. Hebr.: né·fesh; gr.: psy·kheí; lat.: á·ni·ma. Veja Le 21:11 n. e Núm 6:6 n.; Ap. 4A.
====

[[v37-2-14]]

^<<v37-2-14,14>>^ Concordemente, Ageu respondeu e disse: “‘Assim é este povo e assim é esta nação diante de mim’, é a pronunciação de Jeová, ‘e assim é todo o trabalho das suas mãos e tudo o que apresentam ali. É impuro.’

[[v37-2-15]]

^<<v37-2-15,15>>^ “‘Mas agora, por favor, fixai [nisso] vosso coração, deste dia em diante, antes de se colocar pedra sobre pedra no templo^&#42;1^ de Jeová,

[NOTE]
====
. “No templo de.” Hebr.: beheh·khál; gr.: na·oí; lat.: tém·plo. Veja Mt 23:16 n.
====

[[v37-2-16]]

^<<v37-2-16,16>>^ desde que aconteceram estas coisas — chegava-se a um monte de vinte [medidas], e mostrava ter dez; chegava-se ao tanque de lagar para retirar cinqüenta [medidas] do cocho, e mostrava ter vinte;

[[v37-2-17]]

^<<v37-2-17,17>>^ eu vos golpeei com crestamento, e com bolor, e com saraiva, sim, todo o trabalho das vossas mãos, e não havia convosco ninguém [que se voltasse] para mim’, é a pronunciação de Jeová —

[[v37-2-18]]

^<<v37-2-18,18>>^ “‘Por favor, fixai [nisso] vosso coração, deste dia em diante, desde o vigésimo quarto [dia] do nono [mês], desde o dia em que se lançou o alicerce do templo de Jeová; fixai [nisso] vosso coração:

[[v37-2-19]]

^<<v37-2-19,19>>^ Há ainda semente na cova^&#42;1^ de cereais? E até agora, a videira, e a figueira, e a romãzeira, e a oliveira — ela não produziu, não é? A partir deste dia concederei bênção.’”

[NOTE]
====
. Ou “depósito”.
====

[[v37-2-20]]

^<<v37-2-20,20>>^ E veio a haver a palavra de Jeová pela segunda vez para Ageu, no vigésimo quarto [dia] do mês, dizendo:

[[v37-2-21]]

^<<v37-2-21,21>>^ “Dize a Zorobabel, governador de Judá: ‘Eu faço tremer os céus e a terra.

[[v37-2-22]]

^<<v37-2-22,22>>^ E hei de subverter o trono de reinos e aniquilar a força dos reinos das nações; e vou subverter [o] carro e os que andam nele, e [os] cavalos e seus cavaleiros virão abaixo, cada um pela espada de seu irmão.’”

[[v37-2-23]]

^<<v37-2-23,23>>^ “‘Naquele dia’, é a pronunciação de Jeová dos exércitos, ‘tomar-te-ei, ó Zorobabel, filho de Sealtiel, meu servo’, é a pronunciação de Jeová; ‘e hei de constituir-te em anel de chancela, porque és tu a quem escolhi’, é a pronunciação de Jeová dos exércitos.”

'''

xref:037-ageu/037-ageu-001.adoc#v37-1-0[&#60; Capítulo Anterior] | <<v37-2-0,Topo>> | xref:038-zacarias/038-zacarias-001.adoc#v38-1-0[Próximo Capítulo &#62;]