include::./index.adoc[]

[[v60-4-0]]
=== 1 Pedro, 4
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v60-4-1]]

^<<v60-4-1,1>>^ Portanto, visto que Cristo sofreu na carne, armai-vos também da mesma disposição mental;^&#42;1^ porque aquele que tem sofrido na carne tem desistido dos pecados,

[NOTE]
====
. Lit.: “inclinação mental”.
====

[[v60-4-2]]

^<<v60-4-2,2>>^ com o fim de viver o resto do [seu] tempo na carne, não mais para os desejos dos homens, mas para a vontade de Deus.

[[v60-4-3]]

^<<v60-4-3,3>>^ Porque já basta o tempo decorrido para terdes feito a vontade das nações, quando procedestes em ações de conduta desenfreada,^&#42;1^ em concupiscências, em excessos com vinho, em festanças, em competições no beber e em idolatrias ilegais.

[NOTE]
====
. “Ações de conduta desenfreada.” Gr.: a·sel·geí·ais; J17,18,22(hebr.): zim·máh. Veja Gál 5:19 n.: “desenfreada”. Compare isso com Le 18:17 n.
====

[[v60-4-4]]

^<<v60-4-4,4>>^ Visto que não continuais a correr com eles neste proceder para o mesmo antro vil de devassidão, ficam intrigados e falam de vós de modo ultrajante.

[[v60-4-5]]

^<<v60-4-5,5>>^ Mas, estas pessoas prestarão contas àquele que está pronto para julgar os viventes e os mortos.

[[v60-4-6]]

^<<v60-4-6,6>>^ De fato, com este objetivo se declararam as boas novas também aos mortos, para que fossem julgados quanto à carne, do ponto de vista dos homens, mas vivessem quanto ao espírito, do ponto de vista de Deus.

[[v60-4-7]]

^<<v60-4-7,7>>^ Mas tem-se aproximado o fim^&#42;1^ de todas as coisas. Sede ajuizados, portanto, e sede vigilantes,^&#42;2^ visando as orações.

[NOTE]
====
. Ou “fim completo”. Gr.: té·los.
. Lit.: “sede sóbrios”.
====

[[v60-4-8]]

^<<v60-4-8,8>>^ Acima de tudo, tende intenso^&#42;1^ amor uns pelos outros, porque o amor cobre uma multidão de pecados.

[NOTE]
====
. Lit.: “esticado”.
====

[[v60-4-9]]

^<<v60-4-9,9>>^ Sede hospitaleiros uns para com os outros, sem resmungar.

[[v60-4-10]]

^<<v60-4-10,10>>^ Na proporção em que cada um recebeu um dom, usai-o em ministrar uns aos outros como mordomos^&#42;1^ excelentes da benignidade imerecida de Deus, expressa de vários modos.

[NOTE]
====
. Lit.: “administradores domésticos”. Gr.: oi·ko·nó·moi; lat.: di·spen·sa·tó·res; J22(hebr.): kesoh·khením, “como mordomos”.
====

[[v60-4-11]]

^<<v60-4-11,11>>^ Se alguém falar, [fale] como que [as] proclamações sagradas de Deus; se alguém ministrar, [ministre ele] como dependente da força que Deus fornece; para que, em todas as coisas, Deus seja glorificado por intermédio de Jesus Cristo. Dele são a glória e o poderio para todo o sempre. Amém.

[[v60-4-12]]

^<<v60-4-12,12>>^ Amados, não fiqueis intrigados com o ardor entre vós, que vos está acontecendo como provação, como se vos sobreviesse coisa estranha.

[[v60-4-13]]

^<<v60-4-13,13>>^ Ao contrário, prossegui em alegrar-vos por serdes partícipes dos sofrimentos do Cristo, para que vos alegreis e estejais também cheios de alegria durante a revelação^&#42;1^ de sua glória.

[NOTE]
====
. Lit.: “exposição; exibição”. Gr.: a·po·ka·lý·psei.
====

[[v60-4-14]]

^<<v60-4-14,14>>^ Se fordes vituperados pelo nome de Cristo, felizes sois, porque o espírito de glória, sim, o espírito de Deus, está repousando sobre vós.

[[v60-4-15]]

^<<v60-4-15,15>>^ No entanto, nenhum de vós sofra como assassino, ou como ladrão, ou como malfeitor, ou como intrometido nos assuntos dos outros.

[[v60-4-16]]

^<<v60-4-16,16>>^ Mas, se [ele sofrer] como cristão,^&#42;1^ não se envergonhe, mas persista em glorificar a Deus neste nome.

[NOTE]
====
. “Como cristão.” Gr.: hos Khri·sti·a·nós; lat.: ut Chri·sti·á·nus; J22(hebr.): kiM·shi·hhí, “como messianista”.
====

[[v60-4-17]]

^<<v60-4-17,17>>^ Pois é o tempo designado para o julgamento principiar com a casa de Deus. Ora, se primeiro começa conosco, qual será o fim daqueles que não são obedientes às boas novas de Deus?

[[v60-4-18]]

^<<v60-4-18,18>>^ “E, se o justo está sendo salvo com dificuldade, onde aparecerá o ímpio e o pecador?”

[[v60-4-19]]

^<<v60-4-19,19>>^ Assim, também, os que estão sofrendo em harmonia com a vontade de Deus persistam em recomendar as suas almas a um Criador fiel, enquanto estão fazendo o bem.^&#42;1^

[NOTE]
====
. Ou “a um Criador fiel em fazer o bem”.
====

'''

xref:060-1-pedro/060-1-pedro-003.adoc#v60-3-0[&#60; Capítulo Anterior] | <<v60-4-0,Topo>> | xref:060-1-pedro/060-1-pedro-005.adoc#v60-5-0[Próximo Capítulo &#62;]