include::./index.adoc[]

[[v60-1-0]]
=== 1 Pedro, 1
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v60-1-1]]

^<<v60-1-1,1>>^ Pedro,^&#42;1^ apóstolo de Jesus Cristo, aos residentes temporários espalhados por^&#42;2^ Ponto, Galácia, Capadócia, Ásia e Bitínia, aos escolhidos

[NOTE]
====
. “Pedro.” Gr.: Pé·tros, significando “Um Pedaço de Rocha”.
. Lit.: “residentes forasteiros da dispersão”. Veja Tg 1:1.
====

[[v60-1-2]]

^<<v60-1-2,2>>^ segundo a presciência de Deus, o Pai, com santificação pelo espírito, com o objetivo de que sejam obedientes e sejam aspergidos com o sangue de Jesus Cristo.
Benignidade imerecida e paz vos sejam aumentadas.

[[v60-1-3]]

^<<v60-1-3,3>>^ Bendito seja o Deus e Pai de nosso Senhor Jesus Cristo, pois, segundo a sua grande misericórdia, ele nos deu um novo nascimento^&#42;1^ para uma esperança viva por intermédio da ressurreição de Jesus Cristo dentre os mortos,

[NOTE]
====
. Lit.: “tendo regenerado a nós”. Gr.: a·na·gen·né·sas he·más; lat.: re·ge·ne·rá·vit nos.
====

[[v60-1-4]]

^<<v60-1-4,4>>^ para uma herança incorruptível, e imaculada, e imarcescível. Ela está reservada^&#42;1^ nos céus para vós,

[NOTE]
====
. Lit.: “Tendo sido guardada.”
====

[[v60-1-5]]

^<<v60-1-5,5>>^ os que estais sendo resguardados^&#42;1^ pelo poder de Deus, por intermédio da fé, para uma salvação pronta para ser revelada no último período de tempo.

[NOTE]
====
. Lit.: “sendo guardados sob vigilância”.
====

[[v60-1-6]]

^<<v60-1-6,6>>^ Vós vos alegrais grandemente com este fato, embora atualmente, por um pouco, se preciso, sejais contristados por várias provações,

[[v60-1-7]]

^<<v60-1-7,7>>^ a fim de que a qualidade provada^&#42;1^ da vossa fé, de muito mais valor do que o ouro perecível, apesar de ter sido provado por fogo, seja achada causa para louvor, e glória, e honra, na revelação^&#42;2^ de Jesus Cristo.

[NOTE]
====
. Lit.: “a (coisa) testada”.
. Lit.: “exposição; exibição”. Gr.: a·po·ka·lý·psei; lat.: re·ve·la·ti·ó·ne.
====

[[v60-1-8]]

^<<v60-1-8,8>>^ Embora nunca o tenhais visto, vós o amais. Embora atualmente não estejais olhando para ele, contudo, exerceis fé nele e vos alegrais grandemente com indizível e glorificada alegria,

[[v60-1-9]]

^<<v60-1-9,9>>^ recebendo^&#42;1^ o objetivo^&#42;2^ da vossa fé, a salvação das vossas almas.

[NOTE]
====
. Ou “levando embora como prêmio”.
. Ou “fim completo; remate”. Gr.: té·los.
====

[[v60-1-10]]

^<<v60-1-10,10>>^ Acerca desta mesma salvação fizeram diligente indagação e cuidadosa pesquisa os profetas que profetizaram a respeito da benignidade imerecida que vos era destinada.

[[v60-1-11]]

^<<v60-1-11,11>>^ Eles investigaram^&#42;1^ que época específica ou que sorte de [época] o espírito neles indicava a respeito de Cristo,^&#42;2^ quando de antemão dava testemunho dos sofrimentos por Cristo e das glórias que os seguiriam.

[NOTE]
====
. Lit.: “pesquisaram; buscaram”.
. Ou “o espírito de Cristo que estava neles indicava”.
====

[[v60-1-12]]

^<<v60-1-12,12>>^ Foi-lhes revelado que não era para eles, mas para vós, que ministravam as coisas que agora vos foram anunciadas por intermédio dos que vos declararam as boas novas com espírito santo enviado desde o céu. Nestas coisas é que os anjos estão desejosos de olhar de perto.^&#42;1^

[NOTE]
====
. Lit.: “abaixar-se ao lado”.
====

[[v60-1-13]]

^<<v60-1-13,13>>^ Por isso, avigorai as vossas mentes para atividade,^&#42;1^ mantendo inteiramente os vossos sentidos; fixai vossa esperança^&#42;2^ na benignidade imerecida que vos há de ser trazida na revelação de Jesus Cristo.

[NOTE]
====
. Lit.: “cingi os lombos de vossa mente (percepção mental)”.
. Ou “mantende-vos equilibrados e fixai vossa esperança completamente”.
====

[[v60-1-14]]

^<<v60-1-14,14>>^ Como filhos^&#42;1^ obedientes, deixai de ser modelados segundo os desejos que tínheis anteriormente na vossa ignorância,

[NOTE]
====
. Ou “pessoas”.
====

[[v60-1-15]]

^<<v60-1-15,15>>^ mas, de acordo com o Santo que vos chamou, vós, também, tornai-vos santos em toda a [vossa] conduta,

[[v60-1-16]]

^<<v60-1-16,16>>^ porque está escrito: “Tendes de ser santos, porque eu sou santo.”

[[v60-1-17]]

^<<v60-1-17,17>>^ Ademais, se invocais o Pai que julga imparcialmente^&#42;1^ segundo a obra de cada um, comportai-vos com temor durante o tempo da vossa residência como forasteiros.

[NOTE]
====
. Lit.: “sem acepção de faces”.
====

[[v60-1-18]]

^<<v60-1-18,18>>^ Pois sabeis que não foi com coisas corruptíveis, com prata ou ouro, que fostes livrados^&#42;1^ da vossa forma infrutífera de conduta, recebida por tradição de vossos antepassados.

[NOTE]
====
. Lit.: “fostes livrados por resgate”.
====

[[v60-1-19]]

^<<v60-1-19,19>>^ Mas foi com sangue precioso, como o de um cordeiro sem mácula nem mancha, sim, o de Cristo.

[[v60-1-20]]

^<<v60-1-20,20>>^ Deveras, ele era conhecido de antemão, antes da fundação^&#42;1^ do mundo, mas foi manifestado no fim dos tempos por causa de vós,

[NOTE]
====
. Lit.: “do lançamento para baixo [de semente]”. Gr.: ka·ta·bo·lés.
====

[[v60-1-21]]

^<<v60-1-21,21>>^ os que por intermédio dele sois crentes em Deus, que o levantou dentre os mortos e lhe deu glória, para que a vossa fé e esperança estejam em Deus.

[[v60-1-22]]

^<<v60-1-22,22>>^ Agora que purificastes as vossas almas^&#42;1^ pela [vossa] obediência à verdade, tendo por resultado a afeição fraternal sem hipocrisia, amai-vos uns aos outros intensamente^&#42;2^ de coração.

[NOTE]
====
. Ou “vidas”. Veja Ap. 4A.
. Lit.: “esticadamente”.
====

[[v60-1-23]]

^<<v60-1-23,23>>^ Pois recebestes um novo nascimento, não por semente^&#42;1^ [reprodutiva] corruptível, mas por incorruptível, por intermédio da palavra do Deus vivente e permanecente.

[NOTE]
====
. “Semente.” Gr.: spo·rás; lat.: sé·mi·ne.
====

[[v60-1-24]]

^<<v60-1-24,24>>^ Pois “toda a carne é como a erva, e toda a sua glória é como flor da erva; a erva se resseca e a flor cai,

[[v60-1-25]]

^<<v60-1-25,25>>^ mas a declaração de Jeová^&#42;1^ permanece para sempre”. Ora, esta é a “declaração”, esta que vos foi anunciada como boas novas.

[NOTE]
====
. “De Jeová”, J7,8,13,14,16-18,20,22,23; אAB(gr.): Ky·rí·ou; Syp: “de nosso Deus”. Veja Ap. 1D.
====

'''

xref:059-tiago/059-tiago-005.adoc#v59-5-0[&#60; Capítulo Anterior] | <<v60-1-0,Topo>> | xref:060-1-pedro/060-1-pedro-002.adoc#v60-2-0[Próximo Capítulo &#62;]