include::./index.adoc[]

[[v60-2-0]]
=== 1 Pedro, 2
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v60-2-1]]

^<<v60-2-1,1>>^ Concordemente, ponde de lado toda a maldade, e toda a fraudulência, e hipocrisia, e invejas, e toda sorte de maledicências,

[[v60-2-2]]

^<<v60-2-2,2>>^ [e,] como crianças recém-nascidas, ansiai o leite não adulterado pertencente à palavra, para que, por intermédio dela, cresçais para a salvação,

[[v60-2-3]]

^<<v60-2-3,3>>^ desde que provastes que o Senhor^&#42;1^ é benigno.

[NOTE]
====
. “O Senhor.” Gr.: ho Ký·ri·os. Num comentário sobre este v., F. J. A. Hort escreveu em The First Epistle of St Peter, Londres, 1898, p. 104: “No Salmo [34:8], ‛ο κύριος representa a Jeová, como amiúde faz, sendo que a LXX. insere e omite o artigo com κύριος sem qualquer princípio aparente. Por outro lado, o versículo seguinte mostra que S. Pedro usava ‛ο κύριος na sua acepção mais comum, embora não a universal do N.T., de Cristo. Seria, porém, temerário concluir disso que ele queria identificar Jeová com Cristo. Não se pode fazer claramente nenhuma identificação assim no N.T. S. Pedro não faz aqui nenhuma citação formal, mas apenas aproveita a linguagem do A.T. e a aplica da sua própria maneira. Seu uso assim, embora diferente daquele do Salmo, não o contraria, porque é por meio da χρηστότης [khre·stó·tes, “benignidade”] do Filho que a χρηστότης do Pai é claramente dada a conhecer aos cristãos: ‘quem me vê a mim, vê o Pai’.” Veja Ap. 6F.
====

[[v60-2-4]]

^<<v60-2-4,4>>^ Chegando-vos a ele, como a uma pedra vivente, rejeitada, é verdade, pelos homens, mas escolhida [e] preciosa para Deus,

[[v60-2-5]]

^<<v60-2-5,5>>^ vós mesmos também, como pedras viventes, estais sendo edificados como casa espiritual, tendo por objetivo um sacerdócio santo, para oferecerdes sacrifícios espirituais, aceitáveis a Deus, por intermédio de Jesus Cristo.

[[v60-2-6]]

^<<v60-2-6,6>>^ Pois isso está contido na Escritura: “Eis que ponho em Sião uma pedra, escolhida, uma pedra angular de alicerce, preciosa; e ninguém que nela exercer fé de modo algum ficará desapontado.”^&#42;1^

[NOTE]
====
. Ou “de modo algum ficará envergonhado”.
====

[[v60-2-7]]

^<<v60-2-7,7>>^ É para vós, portanto, que ele é precioso,^&#42;1^ porque vós sois crentes; mas, para os que não crêem, “a mesma pedra que os construtores rejeitaram tem-se tornado [a] principal do ângulo”,

[NOTE]
====
. Ou: “Sois vós, portanto, que tendes a preciosa estima.”
====

[[v60-2-8]]

^<<v60-2-8,8>>^ e “uma pedra para tropeço e uma rocha de ofensa”. Estes tropeçam porque são desobedientes à palavra.^&#42;1^ Foram também designados para este mesmo fim.

[NOTE]
====
. Ou “tropeçam na palavra, porque são desobedientes”.
====

[[v60-2-9]]

^<<v60-2-9,9>>^ Mas vós sois “raça^&#42;1^ escolhida, sacerdócio real, nação santa, povo para propriedade especial, para que divulgueis as excelências”^&#42;2^ daquele que vos chamou da escuridão para a sua maravilhosa luz.

[NOTE]
====
. “Raça.” Gr.: gé·nos; diferente de ge·ne·á, “geração”, como em Mt 24:34.
. Lit.: “virtudes”.
====

[[v60-2-10]]

^<<v60-2-10,10>>^ Porque vós, outrora, não éreis povo, mas agora sois povo de Deus; vós éreis aqueles a quem não se mostrara misericórdia, mas agora sois os a quem se mostrou misericórdia.

[[v60-2-11]]

^<<v60-2-11,11>>^ Amados, exorto-vos como a forasteiros e residentes temporários a que vos abstenhais dos desejos carnais, que são os que travam um combate contra a alma.^&#42;1^

[NOTE]
====
. Ou “contra a vida”. Gr.: ka·tá tes psy·khés; lat.: ad·vér·sus á·ni·mam; J17,18(hebr.): ban·ná·fesh.
====

[[v60-2-12]]

^<<v60-2-12,12>>^ Mantende a vossa conduta excelente entre as nações, para que, naquilo em que falam de vós como de malfeitores, eles, em resultado das vossas obras excelentes, das quais são testemunhas oculares, glorifiquem a Deus no dia da [sua] inspeção.

[[v60-2-13]]

^<<v60-2-13,13>>^ Pela causa do Senhor,^&#42;1^ sujeitai-vos a toda criação humana: quer a um rei, como sendo superior,

[NOTE]
====
. “Do Senhor”, אAB; VgcSyp: “de Deus”; J7,8: “de Jeová”.
====

[[v60-2-14]]

^<<v60-2-14,14>>^ quer a governadores, como enviados por ele para infligir punição a malfeitores, mas para louvar os que fazem o bem.

[[v60-2-15]]

^<<v60-2-15,15>>^ Pois a vontade de Deus é que, por fazerdes o bem, possais açaimar a conversa ignorante dos homens desarrazoados.^&#42;1^

[NOTE]
====
. Lit.: “insensatos”.
====

[[v60-2-16]]

^<<v60-2-16,16>>^ Sede como livres, contudo, mantende a vossa liberdade, não como disfarce para a maldade, mas como escravos de Deus.

[[v60-2-17]]

^<<v60-2-17,17>>^ Honrai [a homens] de toda sorte, tende amor à associação inteira dos irmãos,^&#42;1^ tende temor de Deus, dai honra ao rei.

[NOTE]
====
. “Associação inteira dos irmãos.” Lit.: “fraternidade”.
====

[[v60-2-18]]

^<<v60-2-18,18>>^ Os servos domésticos estejam sujeitos aos [seus] donos com todo o temor [devido], não somente aos bons e razoáveis, mas também aos difíceis de agradar.

[[v60-2-19]]

^<<v60-2-19,19>>^ Porque, se alguém, por causa da consciência para com Deus, agüenta coisas penosas e sofre injustamente, isto é algo agradável.

[[v60-2-20]]

^<<v60-2-20,20>>^ Pois, que mérito há nisso se, quando estais pecando e estais sendo esbofeteados,^&#42;1^ perseverais? Mas, se perseverais quando estais fazendo o bem e sofreis, isto é algo agradável a Deus.

[NOTE]
====
. Lit.: “socados”.
====

[[v60-2-21]]

^<<v60-2-21,21>>^ De fato, fostes chamados para este [proceder], porque até mesmo Cristo sofreu por vós, deixando-vos um modelo^&#42;1^ para seguirdes de perto os seus passos.

[NOTE]
====
. Ou “cópia”. Lit.: “um subscrito”. Gr.: hy·po·gram·món; lat.: ex·ém·plum, “exemplo; modelo”.
====

[[v60-2-22]]

^<<v60-2-22,22>>^ Ele não cometeu pecado, nem se achou engano na sua boca.

[[v60-2-23]]

^<<v60-2-23,23>>^ Quando estava sendo injuriado, não injuriava em revide. Quando sofria, não ameaçava, mas encomendava-se àquele que julga justamente.

[[v60-2-24]]

^<<v60-2-24,24>>^ Ele mesmo levou^&#42;1^ os nossos pecados no seu próprio corpo, no madeiro,^&#42;2^ a fim de que acabássemos com os pecados e vivêssemos para a justiça. E “pelos seus vergões fostes sarados”.

[NOTE]
====
. Ou: “Ele mesmo carregou com.”
. Ou “árvore”. Lit.: “madeira”. Gr.: xý·lon. Veja Ap. 5C.
====

[[v60-2-25]]

^<<v60-2-25,25>>^ Porque vós éreis como ovelhas, perdendo-vos; mas agora voltastes para o pastor e superintendente^&#42;1^ das vossas almas.^&#42;2^

[NOTE]
====
. “Superintendente.” Gr.: e·pí·sko·pon; J17(hebr.): peqídh.
. Ou “vidas”.
====

'''

xref:060-1-pedro/060-1-pedro-001.adoc#v60-1-0[&#60; Capítulo Anterior] | <<v60-2-0,Topo>> | xref:060-1-pedro/060-1-pedro-003.adoc#v60-3-0[Próximo Capítulo &#62;]