include::./index.adoc[]

[[v45-9-0]]
=== Romanos, 9
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v45-9-1]]

^<<v45-9-1,1>>^ Digo a verdade em Cristo; não estou mentindo, visto que a minha consciência dá testemunho comigo, em espírito santo,

[[v45-9-2]]

^<<v45-9-2,2>>^ de que tenho grande pesar e incessante dor no meu coração.

[[v45-9-3]]

^<<v45-9-3,3>>^ Pois, poderia desejar que eu mesmo fosse separado do Cristo como amaldiçoado,^&#42;1^ em favor dos meus irmãos, meus parentes segundo a carne,

[NOTE]
====
. Lit.: “anátema”. Gr. e lat.: a·ná·the·ma.
====

[[v45-9-4]]

^<<v45-9-4,4>>^ os quais, como tais, são israelitas, a quem pertencem a adoção como filhos, e a glória, e os pactos, e a promulgação da Lei, e o serviço sagrado,^&#42;1^ e as promessas;

[NOTE]
====
. “Serviço sagrado.” Gr.: la·treí·a; J17(hebr.): weha·‛avoh·dháh, “e o serviço (a adoração)”. Veja Êx 12:25 n.
====

[[v45-9-5]]

^<<v45-9-5,5>>^ a quem pertencem os antepassados e de quem [procedeu] o Cristo segundo a carne: Deus, que é sobre todos,^&#42;1^ [seja] bendito para sempre. Amém.

[NOTE]
====
. Veja Ap. 6D para um exame do assunto “Deus, que é sobre todos”.
====

[[v45-9-6]]

^<<v45-9-6,6>>^ No entanto, não é como se a palavra de Deus tivesse falhado. Porque nem todos os que [procedem] de Israel são realmente “Israel”.

[[v45-9-7]]

^<<v45-9-7,7>>^ Tampouco por serem o descendente de Abraão são todos eles filhos, mas: “O que será chamado ‘teu descendente’ será por intermédio de Isaque.”

[[v45-9-8]]

^<<v45-9-8,8>>^ Quer dizer, os filhos na carne não são realmente os filhos de Deus, mas os filhos da promessa é que são contados como o descendente.

[[v45-9-9]]

^<<v45-9-9,9>>^ Pois a palavra da promessa era como segue: “Virei neste tempo e Sara terá um filho.”

[[v45-9-10]]

^<<v45-9-10,10>>^ Contudo, não apenas este caso, mas também quando Rebeca concebeu gêmeos de um só [homem], Isaque, nosso antepassado:

[[v45-9-11]]

^<<v45-9-11,11>>^ pois, quando ainda não tinham nascido, nem tinham ainda praticado nada de bom ou de ruim, a fim de que o propósito de Deus, com respeito à escolha, continuasse dependente, não de obras, mas Daquele que chama,

[[v45-9-12]]

^<<v45-9-12,12>>^ foi dito a ela: “O mais velho será escravo do mais moço.”

[[v45-9-13]]

^<<v45-9-13,13>>^ Assim como está escrito: “Amei a Jacó, mas odiei a Esaú.”

[[v45-9-14]]

^<<v45-9-14,14>>^ Que diremos, então? Há injustiça da parte de Deus? Que isso nunca se torne tal!

[[v45-9-15]]

^<<v45-9-15,15>>^ Porque ele diz a Moisés: “Terei misericórdia de quem quer que eu tiver misericórdia, e mostrarei compaixão para com quem quer que eu mostrar compaixão.”

[[v45-9-16]]

^<<v45-9-16,16>>^ De modo que depende, então, não daquele que deseja, nem daquele que corre, mas de Deus, que tem misericórdia.

[[v45-9-17]]

^<<v45-9-17,17>>^ Pois a Escritura diz a Faraó: “Por esta mesma razão deixei-te permanecer,^&#42;1^ para que, em conexão contigo, eu mostre o meu poder, e para que o meu nome seja declarado em toda a terra.”

[NOTE]
====
. “Deixei-te permanecer”, J17,18,22; אAB: “suscitei-te”; Êx 9:16 na LXX, que Paulo cita aqui: “foste preservado”.
====

[[v45-9-18]]

^<<v45-9-18,18>>^ Assim, pois, ele tem misericórdia de quem quiser, mas deixa ficar obstinado a quem quiser.

[[v45-9-19]]

^<<v45-9-19,19>>^ Tu me dirás, portanto: “Por que acha ainda falta? Pois, quem é que tem resistido à sua expressa vontade?”

[[v45-9-20]]

^<<v45-9-20,20>>^ Quem realmente és tu, então, ó homem, para redargüires a Deus? Dirá a coisa moldada àquele que a moldou: “Por que me fizeste deste modo?”

[[v45-9-21]]

^<<v45-9-21,21>>^ O quê? Não tem o oleiro autoridade sobre o barro, para fazer da mesma massa um vaso para uso honroso, outro para uso desonroso?

[[v45-9-22]]

^<<v45-9-22,22>>^ Se Deus, pois, embora tendo vontade de demonstrar o seu furor e de dar a conhecer o seu poder, tolerou com muita longanimidade os vasos do furor, feitos próprios para a destruição,

[[v45-9-23]]

^<<v45-9-23,23>>^ a fim de dar a conhecer as riquezas de sua glória nos vasos de misericórdia, que ele preparou de antemão para glória,

[[v45-9-24]]

^<<v45-9-24,24>>^ a saber, nós, a quem ele chamou não somente dentre os judeus, mas também dentre as nações, [o que tem isso]?

[[v45-9-25]]

^<<v45-9-25,25>>^ É conforme ele diz também em Oséias: “Aos que não são meu povo, eu chamarei de ‘meu povo’, e àquela que não era amada, de ‘amada’;

[[v45-9-26]]

^<<v45-9-26,26>>^ e no lugar onde se lhes disse: ‘Vós não sois meu povo’, ali serão chamados de ‘filhos do Deus vivente’.”

[[v45-9-27]]

^<<v45-9-27,27>>^ Além disso, Isaías clama acerca de Israel: “Embora o número dos filhos de Israel seja como a areia do mar, é o restante que será salvo.

[[v45-9-28]]

^<<v45-9-28,28>>^ Pois Jeová^&#42;1^ fará uma prestação de contas na terra, concluindo-a e abreviando-a.”^&#42;2^

[NOTE]
====
. Veja Ap. 1D.
. Ou “executando-a velozmente”.
====

[[v45-9-29]]

^<<v45-9-29,29>>^ Também, assim como Isaías dissera outrora: “Se Jeová^&#42;1^ dos exércitos não nos tivesse deixado descendente, teríamos ficado assim como Sodoma, e teríamos sido feitos iguais a Gomorra.”

[NOTE]
====
. Veja Ap. 1D.
====

[[v45-9-30]]

^<<v45-9-30,30>>^ Que diremos, então? Que pessoas das nações, embora não se empenhassem pela justiça, alcançaram a justiça, a justiça que resulta da fé;

[[v45-9-31]]

^<<v45-9-31,31>>^ mas Israel, embora se empenhasse por uma lei da justiça, não alcançou a lei.

[[v45-9-32]]

^<<v45-9-32,32>>^ Por que razão? Porque se empenhou por ela, não pela fé, mas como por obras. Tropeçaram sobre a “pedra para tropeço”;

[[v45-9-33]]

^<<v45-9-33,33>>^ conforme está escrito: “Eis que eu ponho em Sião uma pedra para tropeço e uma rocha de ofensa, mas quem basear nela^&#42;1^ a sua fé não ficará desapontado.”^&#42;2^

[NOTE]
====
. Ou “nele”.
. Ou “não ficará envergonhado”.
====

'''

xref:045-romanos/045-romanos-008.adoc#v45-8-0[&#60; Capítulo Anterior] | <<v45-9-0,Topo>> | xref:045-romanos/045-romanos-010.adoc#v45-10-0[Próximo Capítulo &#62;]