include::./index.adoc[]

[[v45-1-0]]
=== Romanos, 1
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v45-1-1]]

^<<v45-1-1,1>>^ Paulo, escravo de Jesus Cristo e chamado para ser apóstolo, separado para as boas novas de Deus,

[[v45-1-2]]

^<<v45-1-2,2>>^ que ele prometeu outrora por intermédio de seus profetas, nas Escrituras sagradas,

[[v45-1-3]]

^<<v45-1-3,3>>^ a respeito de seu Filho, o qual procedeu do descendente^&#42;1^ de Davi segundo a carne,

[NOTE]
====
. Ou “prole”.
====

[[v45-1-4]]

^<<v45-1-4,4>>^ mas que, com poder, foi declarado^&#42;1^ Filho de Deus, segundo o espírito de santidade, por meio da ressurreição dentre os mortos — sim, Jesus Cristo, nosso Senhor,

[NOTE]
====
. Ou “determinado a ser”.
====

[[v45-1-5]]

^<<v45-1-5,5>>^ por intermédio de quem recebemos^&#42;1^ benignidade imerecida e um apostolado, a fim de que houvesse obediência de fé entre todas as nações com respeito ao seu nome,

[NOTE]
====
. “Recebemos”, usado em estilo editorial. Ou “recebi”.
====

[[v45-1-6]]

^<<v45-1-6,6>>^ [nações] entre as quais vós também sois dos chamados para pertencer a Jesus Cristo —

[[v45-1-7]]

^<<v45-1-7,7>>^ a todos os que estão em Roma, como amados de Deus, chamados para serem santos:
Que tenhais benignidade imerecida e paz da parte de Deus, nosso Pai, e [do] Senhor Jesus Cristo.

[[v45-1-8]]

^<<v45-1-8,8>>^ Primeiramente, agradeço a meu Deus, por intermédio de Jesus Cristo, concernente a todos vós, porque se fala da vossa fé em todo o mundo.

[[v45-1-9]]

^<<v45-1-9,9>>^ Pois Deus, a quem presto serviço sagrado^&#42;1^ com o meu espírito, em conexão com as boas novas a respeito de seu Filho, é minha testemunha de como eu, sem cessar, faço sempre menção de vós nas minhas orações,

[NOTE]
====
. “Presto serviço sagrado.” Gr.: la·treú·o; J17,18(hebr.): ’aní ‛o·védh, “sirvo (adoro)”. Veja Êx 3:12 n.
====

[[v45-1-10]]

^<<v45-1-10,10>>^ rogando que, se de todo possível, eu possa agora, por fim, ser próspero na vontade de Deus, de modo a ir ter convosco.

[[v45-1-11]]

^<<v45-1-11,11>>^ Porque anseio ver-vos, para vos conferir algum dom espiritual, a fim de que sejais firmados;

[[v45-1-12]]

^<<v45-1-12,12>>^ ou, antes, para que haja um intercâmbio de encorajamento^&#42;1^ entre vós, cada um por intermédio da fé que o outro tem, tanto a vossa como a minha.

[NOTE]
====
. Lit.: “sermos encorajados juntos”.
====

[[v45-1-13]]

^<<v45-1-13,13>>^ Mas, não quero que fiqueis sem saber, irmãos, que me propus muitas vezes ir ter convosco, mas tenho sido impedido até agora, a fim de que eu adquirisse alguns frutos também entre vós, assim como entre as demais nações.

[[v45-1-14]]

^<<v45-1-14,14>>^ Sou devedor tanto a gregos como a bárbaros,^&#42;1^ tanto a sábios como a insensatos:

[NOTE]
====
. Ou “estrangeiros”.
====

[[v45-1-15]]

^<<v45-1-15,15>>^ de modo que há um anelo da minha parte para declarar as boas novas também a vós aí em Roma.

[[v45-1-16]]

^<<v45-1-16,16>>^ Pois eu não me envergonho das boas novas; são, de fato, o poder de Deus para a salvação de todo aquele que tem fé, primeiro^&#42;1^ para o judeu, e também para o grego;

[NOTE]
====
. “Primeiro.” B omite isso.
====

[[v45-1-17]]

^<<v45-1-17,17>>^ pois nelas é que se revela a justiça de Deus em razão da fé e para com a fé, assim como está escrito: “Mas o justo — por meio da fé é que viverá.”

[[v45-1-18]]

^<<v45-1-18,18>>^ Pois o furor de Deus está sendo revelado desde o céu contra toda a impiedade e injustiça dos homens que suprimem a verdade de modo injusto,

[[v45-1-19]]

^<<v45-1-19,19>>^ porque aquilo que se pode saber sobre Deus é manifesto entre eles, porque Deus lho manifestou.

[[v45-1-20]]

^<<v45-1-20,20>>^ Pois as suas [qualidades] invisíveis são claramente vistas desde a criação do mundo^&#42;1^ em diante, porque são percebidas por meio das coisas feitas, mesmo seu sempiterno poder e Divindade,^&#42;2^ de modo que eles são inescusáveis;

[NOTE]
====
. “Do mundo.” Gr.: kó·smou; lat.: mún·di; J17,22(hebr.): ha·‛oh·lám, “o mundo”.
. “Divindade.” Gr.: Thei·ó·tes, relacionado com The·ós, “Deus”; lat.: Di·ví·ni·tas. Veja At 17:29 n.
====

[[v45-1-21]]

^<<v45-1-21,21>>^ porque, embora conhecessem a Deus, não o glorificaram como Deus, nem lhe agradeceram, mas tornaram-se inanes nos seus raciocínios e o seu coração ininteligente ficou obscurecido.

[[v45-1-22]]

^<<v45-1-22,22>>^ Embora asseverassem ser sábios, tornaram-se tolos

[[v45-1-23]]

^<<v45-1-23,23>>^ e transformaram a glória do Deus incorruptível em algo semelhante à imagem do homem corruptível, e de aves, e de quadrúpedes, e de bichos rastejantes.

[[v45-1-24]]

^<<v45-1-24,24>>^ Portanto Deus, em harmonia com os desejos dos seus corações, entregou-os à impureza, para que os seus corpos fossem desonrados entre si,

[[v45-1-25]]

^<<v45-1-25,25>>^ estes, os que trocaram a verdade de Deus pela mentira, e veneraram e prestaram serviço sagrado antes à criação do que Àquele que criou, que é bendito para sempre. Amém.^&#42;1^

[NOTE]
====
. Ou: “Assim seja.” Gr.: a·mén; lat.: á·men; J17,18,22(hebr.): ’a·mén. Veja Ne 5:13.
====

[[v45-1-26]]

^<<v45-1-26,26>>^ É por isso que Deus os entregou a ignominiosos apetites sexuais, pois tanto as suas fêmeas trocaram o uso natural de si mesmas por outro contrário à natureza;

[[v45-1-27]]

^<<v45-1-27,27>>^ e, igualmente, até os varões abandonaram o uso natural da fêmea e ficaram violentamente inflamados na sua concupiscência de uns para com os outros, machos com machos, praticando o que é obsceno^&#42;1^ e recebendo em si mesmos a plena recompensa, que se devia ao seu erro.

[NOTE]
====
. “O que é obsceno.” Lit.: “a indecência”.
====

[[v45-1-28]]

^<<v45-1-28,28>>^ E assim como não aprovaram reter Deus com um conhecimento exato, Deus entregou-os a um estado mental reprovado, para fazerem as coisas que não são próprias,

[[v45-1-29]]

^<<v45-1-29,29>>^ já que estavam cheios de toda a injustiça, iniqüidade, cobiça, maldade, cheios de inveja, assassínio, rixa, fraude, disposição maldosa, sendo cochichadores,

[[v45-1-30]]

^<<v45-1-30,30>>^ maldizentes, odiadores de Deus, insolentes, soberbos, pretensiosos, inventores de coisas prejudiciais, desobedientes aos pais,

[[v45-1-31]]

^<<v45-1-31,31>>^ sem entendimento, pérfidos nos acordos,^&#42;1^ sem afeição natural, desapiedados.

[NOTE]
====
. Ou “opostos a qualquer acordo”.
====

[[v45-1-32]]

^<<v45-1-32,32>>^ Embora estes conhecessem muito bem o decreto justo de Deus, de que os que praticam tais coisas merecem a morte, não somente persistem em fazê-las, mas também consentem com os que as praticam.

'''

xref:044-atos/044-atos-028.adoc#v44-28-0[&#60; Capítulo Anterior] | <<v45-1-0,Topo>> | xref:045-romanos/045-romanos-002.adoc#v45-2-0[Próximo Capítulo &#62;]