include::./index.adoc[]

[[v45-4-0]]
=== Romanos, 4
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v45-4-1]]

^<<v45-4-1,1>>^ Sendo assim, que diremos a respeito de Abraão, nosso antepassado segundo a carne?^&#42;1^

[NOTE]
====
. “Diremos a respeito de Abraão . . . carne”, B; אADVg: “diremos que Abraão, nosso antepassado segundo a carne, obteve”.
====

[[v45-4-2]]

^<<v45-4-2,2>>^ Se Abraão, por exemplo, tivesse sido declarado justo em resultado de obras, ele teria base para jactância; mas não para com Deus.

[[v45-4-3]]

^<<v45-4-3,3>>^ Pois o que diz a escritura? “Abraão exerceu fé em Jeová,^&#42;1^ e isso lhe foi contado como justiça.”

[NOTE]
====
. Veja Ap. 1D.
====

[[v45-4-4]]

^<<v45-4-4,4>>^ Ora, ao homem que trabalha se conta^&#42;1^ a remuneração, não como benignidade imerecida, mas como dívida.

[NOTE]
====
. Lit.: “está sendo computada”. Gr.: lo·gí·ze·tai; lat.: in·pu·tá·tur.
====

[[v45-4-5]]

^<<v45-4-5,5>>^ Por outro lado, ao homem que não trabalha, mas deposita fé naquele que ao ímpio declara justo, a sua fé é contada como justiça.

[[v45-4-6]]

^<<v45-4-6,6>>^ Assim como também Davi fala da felicidade^&#42;1^ do homem a quem Deus conta a justiça à parte de obras:

[NOTE]
====
. Ou “também Davi expressa a felicitação”.
====

[[v45-4-7]]

^<<v45-4-7,7>>^ “Felizes aqueles cujas ações contra a lei foram perdoadas e cujos pecados foram encobertos;

[[v45-4-8]]

^<<v45-4-8,8>>^ feliz o homem cujo pecado Jeová^&#42;1^ de modo algum levará em conta.”

[NOTE]
====
. Veja Ap. 1D.
====

[[v45-4-9]]

^<<v45-4-9,9>>^ Vem esta felicidade então sobre circuncisos ou também sobre incircuncisos? Visto que dizemos: “A Abraão foi contada a sua fé como justiça.”

[[v45-4-10]]

^<<v45-4-10,10>>^ Em que circunstâncias, pois, foi-lhe contada [assim]? Quando estava na circuncisão ou na incircuncisão? Não na circuncisão, mas na incircuncisão.

[[v45-4-11]]

^<<v45-4-11,11>>^ E ele recebeu um sinal, a saber, a circuncisão, como selo^&#42;1^ da justiça pela fé que teve enquanto estava no seu estado incircunciso, para que fosse pai de todos os que têm fé enquanto na incircuncisão, a fim de que se lhes contasse a justiça;

[NOTE]
====
. Ou “confirmação”.
====

[[v45-4-12]]

^<<v45-4-12,12>>^ e pai de descendência circuncisa, não somente dos que aderem à circuncisão, mas também dos que andam ordeiramente nas pisadas dessa fé que era de nosso pai Abraão, enquanto no estado incircunciso.

[[v45-4-13]]

^<<v45-4-13,13>>^ Porque não foi por intermédio de lei que Abraão, ou seu descendente, teve a promessa de ser herdeiro dum mundo, mas foi por intermédio da justiça pela fé.

[[v45-4-14]]

^<<v45-4-14,14>>^ Pois, se os que aderem à lei são herdeiros, foi inutilizada a fé e abolida a promessa.

[[v45-4-15]]

^<<v45-4-15,15>>^ Na realidade, a Lei produz furor, mas onde não há lei, tampouco há transgressão.

[[v45-4-16]]

^<<v45-4-16,16>>^ Por esta razão, foi em resultado da fé, para que fosse segundo a benignidade imerecida, a fim de que a promessa estivesse assegurada a todos os seus descendentes, não somente ao que adere à Lei, mas também ao que adere à fé que Abraão teve. (Ele é o pai de todos nós,

[[v45-4-17]]

^<<v45-4-17,17>>^ como está escrito: “Eu te designei pai de muitas nações.”) Isto se deu à vista Daquele em quem tinha fé, sim, de Deus, que vivifica os mortos e chama^&#42;1^ as coisas que não são como se fossem.

[NOTE]
====
. Ou “convoca”.
====

[[v45-4-18]]

^<<v45-4-18,18>>^ Embora além de esperança, contudo, baseado na esperança, ele teve fé, para tornar-se pai de muitas nações, de acordo com o que se dissera: “Assim será o teu descendente.”

[[v45-4-19]]

^<<v45-4-19,19>>^ E, embora não ficasse fraco na fé, tomava em conta o seu próprio corpo, então já amortecido, visto que tinha cerca de cem anos de idade, [e] também o amortecimento da madre de Sara.

[[v45-4-20]]

^<<v45-4-20,20>>^ Mas, por causa da promessa de Deus, não vacilou com falta de fé, mas tornou-se poderoso pela sua fé, dando glória a Deus

[[v45-4-21]]

^<<v45-4-21,21>>^ e estando plenamente convencido de que era também capaz de fazer aquilo que prometera.

[[v45-4-22]]

^<<v45-4-22,22>>^ Portanto, “isso lhe foi contado como justiça”.

[[v45-4-23]]

^<<v45-4-23,23>>^ Que “isso lhe foi contado”, foi escrito, porém, não somente por causa dele,

[[v45-4-24]]

^<<v45-4-24,24>>^ mas também por nossa causa, a quem se destina a ser contado, porque cremos naquele que levantou a Jesus, nosso Senhor, dentre os mortos.

[[v45-4-25]]

^<<v45-4-25,25>>^ Ele foi entregue por causa das nossas falhas e foi levantado para que fôssemos declarados justos.

'''

xref:045-romanos/045-romanos-003.adoc#v45-3-0[&#60; Capítulo Anterior] | <<v45-4-0,Topo>> | xref:045-romanos/045-romanos-005.adoc#v45-5-0[Próximo Capítulo &#62;]