include::./index.adoc[]

[[v45-15-0]]
=== Romanos, 15
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v45-15-1]]

^<<v45-15-1,1>>^ Nós, porém, os que somos fortes, devemos suportar as fraquezas dos que não são fortes, e não estar agradando a nós mesmos.

[[v45-15-2]]

^<<v45-15-2,2>>^ Que cada um de nós agrade [ao seu] próximo naquilo que é bom para a edificação [dele].

[[v45-15-3]]

^<<v45-15-3,3>>^ Pois até mesmo o Cristo não agradou a si mesmo; mas, assim como está escrito: “Os vitupérios daqueles que te vituperaram caíram sobre mim.”

[[v45-15-4]]

^<<v45-15-4,4>>^ Porque todas as coisas escritas outrora foram escritas para a nossa instrução, para que, por intermédio da nossa perseverança e por intermédio do consolo das Escrituras, tivéssemos esperança.^&#42;1^

[NOTE]
====
. “Esperança”, אAVgSyp; B: “esperança do consolo; a esperança consoladora”.
====

[[v45-15-5]]

^<<v45-15-5,5>>^ Ora, o Deus que provê perseverança e consolo vos conceda terdes entre vós próprios a mesma atitude mental que Cristo Jesus teve,

[[v45-15-6]]

^<<v45-15-6,6>>^ para que, de comum acordo, com uma só boca, glorifiqueis o Deus e Pai de nosso Senhor Jesus Cristo.

[[v45-15-7]]

^<<v45-15-7,7>>^ Portanto, acolhei-vos uns aos outros, assim como também o Cristo nos acolheu, visando glória para Deus.

[[v45-15-8]]

^<<v45-15-8,8>>^ Pois eu digo que Cristo se tornou realmente ministro dos circuncisos em favor da veracidade de Deus, a fim de confirmar as promessas que Ele fez aos antepassados deles,

[[v45-15-9]]

^<<v45-15-9,9>>^ e para que as nações glorificassem a Deus pela sua misericórdia. Assim como está escrito: “É por isso que eu te reconhecerei abertamente entre as nações^&#42;1^ e farei melodia para o teu nome.”

[NOTE]
====
. “Nações”, ABSyp; אcVgc: “nações, ó Senhor”.
====

[[v45-15-10]]

^<<v45-15-10,10>>^ E novamente ele diz: “Regozijai-vos, ó nações, com o seu povo.”

[[v45-15-11]]

^<<v45-15-11,11>>^ E novamente: “Louvai a Jeová,^&#42;1^ ó todas as nações, e louvem-no todos os povos.”

[NOTE]
====
. Veja Ap. 1D.
====

[[v45-15-12]]

^<<v45-15-12,12>>^ E, novamente, Isaías diz: “Haverá a raiz de Jessé, e haverá um surgindo para governar as nações; nele é que as nações basearão a sua esperança.”

[[v45-15-13]]

^<<v45-15-13,13>>^ Que o Deus que dá esperança vos encha de toda alegria e paz pela vossa crença, para que abundeis em esperança com poder de espírito santo.

[[v45-15-14]]

^<<v45-15-14,14>>^ Ora, eu mesmo também estou persuadido quanto a vós, meus irmãos, de que vós mesmos também estais cheios de bondade, visto que fostes enchidos de todo o conhecimento, e que também podeis admoestar-vos uns aos outros.

[[v45-15-15]]

^<<v45-15-15,15>>^ No entanto, eu vos escrevo com tanto mais franqueza sobre alguns pontos, como que para vos fazer lembrar novamente, por causa da benignidade imerecida que me foi dada da parte de Deus

[[v45-15-16]]

^<<v45-15-16,16>>^ para ser servidor público^&#42;1^ de Cristo Jesus para as nações, ocupado na obra santa das boas novas de Deus, a fim de que a oferta, a saber, estas nações, se mostrasse aceitável, sendo ela santificada com espírito santo.

[NOTE]
====
. “Servidor público.” Gr.: lei·tour·gón.
====

[[v45-15-17]]

^<<v45-15-17,17>>^ Portanto, tenho causa para exultar em Cristo Jesus, no que toca às coisas referentes a Deus.

[[v45-15-18]]

^<<v45-15-18,18>>^ Pois eu não me aventurarei a dizer nem uma só coisa que não for das coisas que Cristo produziu por intermédio de mim, para que as nações fossem obedientes, por [minha] palavra e ação,

[[v45-15-19]]

^<<v45-15-19,19>>^ com o poder de sinais e portentos, com o poder de espírito santo;^&#42;1^ de modo que, desde Jerusalém e num circuito até Ilírico, preguei cabalmente as boas novas a respeito do Cristo.

[NOTE]
====
. “Espírito santo”, AD°Vg; P46אSyh,p: “espírito de Deus”; B: “espírito”.
====

[[v45-15-20]]

^<<v45-15-20,20>>^ Deste modo, deveras, tomei por meu alvo não declarar as boas novas onde Cristo já tinha sido [mencionado] por nome, a fim de não edificar sobre o alicerce de outro homem;

[[v45-15-21]]

^<<v45-15-21,21>>^ mas, assim como está escrito: “Aqueles, a quem nenhum anúncio se fez a respeito dele, verão, e os que não ouviram entenderão.”

[[v45-15-22]]

^<<v45-15-22,22>>^ Portanto, fui também muitas vezes impedido de chegar a vós.

[[v45-15-23]]

^<<v45-15-23,23>>^ Mas agora que não tenho mais território [virgem] nestas regiões, e já por alguns anos tenho tido o anseio de chegar a vós

[[v45-15-24]]

^<<v45-15-24,24>>^ quando eu estiver em caminho para a Espanha, espero, acima de tudo quando eu estiver em viagem para lá, poder ver-vos e ser escoltado por vós parte do caminho para lá, depois de eu ter sido primeiro satisfeito, em alguma medida, pela vossa companhia.

[[v45-15-25]]

^<<v45-15-25,25>>^ Mas agora estou para viajar a Jerusalém, para ministrar aos santos.

[[v45-15-26]]

^<<v45-15-26,26>>^ Porque os da Macedônia e da Acaia^&#42;1^ agradaram-se em partilhar as suas coisas por meio duma contribuição para os pobres [que são] dos santos em Jerusalém.

[NOTE]
====
. A província romana do sul da Grécia, cuja capital era Corinto.
====

[[v45-15-27]]

^<<v45-15-27,27>>^ Verdadeiramente, eles se agradaram em fazer isso, e, contudo, eram devedores deles; pois, se as nações participaram das suas coisas espirituais, cabe-lhes também ministrar publicamente a estes com as coisas para o corpo carnal.

[[v45-15-28]]

^<<v45-15-28,28>>^ Assim, depois de eu ter terminado isso e de lhes ter levado em segurança este fruto, partirei, passando por vós, em caminho para a Espanha.

[[v45-15-29]]

^<<v45-15-29,29>>^ Além disso, sei que, quando eu chegar a vós, chegarei com uma plena medida de bênção da parte de Cristo.

[[v45-15-30]]

^<<v45-15-30,30>>^ Exorto-vos agora, irmãos,^&#42;1^ por intermédio de nosso Senhor Jesus Cristo e por intermédio do amor do espírito, que vos esforceis comigo em orações a Deus por mim,

[NOTE]
====
. “Irmãos”, אADVgSyp; P46B omitem isso.
====

[[v45-15-31]]

^<<v45-15-31,31>>^ para que eu seja livrado dos incrédulos na Judéia e para que o meu ministério, que é para Jerusalém, se mostre aceitável aos santos,

[[v45-15-32]]

^<<v45-15-32,32>>^ de modo que, quando eu chegar a vós com alegria, pela vontade de Deus, eu seja reanimado junto convosco.

[[v45-15-33]]

^<<v45-15-33,33>>^ O Deus, que dá paz, esteja com todos vós. Amém.

'''

xref:045-romanos/045-romanos-014.adoc#v45-14-0[&#60; Capítulo Anterior] | <<v45-15-0,Topo>> | xref:045-romanos/045-romanos-016.adoc#v45-16-0[Próximo Capítulo &#62;]