include::./index.adoc[]

[[v45-13-0]]
=== Romanos, 13
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v45-13-1]]

^<<v45-13-1,1>>^ Toda alma^&#42;1^ esteja sujeita às autoridades superiores, pois não há autoridade exceto por Deus; as autoridades existentes acham-se colocadas por Deus nas suas posições relativas.^&#42;2^

[NOTE]
====
. Ou: “Toda pessoa vivente.” Veja Ap. 4A.
. “Acham-se colocadas . . . nas suas posições relativas.” Lit.: “tendo sido postas em ordem, são”.
====

[[v45-13-2]]

^<<v45-13-2,2>>^ Portanto, quem se opõe^&#42;1^ à autoridade, tem tomado posição contra o arranjo de Deus; os que têm tomado posição contra este receberão um julgamento para si mesmos.

[NOTE]
====
. Lit.: “aquele (que) se coloca contra”.
====

[[v45-13-3]]

^<<v45-13-3,3>>^ Pois, os que governam são objeto de temor, não para as boas ações, mas para as más. Queres tu, pois, não ter temor da autoridade? Persiste em fazer o bem, e terás louvor dela;^&#42;1^

[NOTE]
====
. “Dela”, isto é, da “autoridade”.
====

[[v45-13-4]]

^<<v45-13-4,4>>^ pois é^&#42;1^ ministro^&#42;2^ de Deus para ti, para teu bem. Mas, se fizeres o que é mau, teme; porque não é sem objetivo que leva a espada; pois é ministro de Deus, vingador para expressar furor para com o que pratica o que é mau.

[NOTE]
====
. “É”, isto é, a “autoridade é”.
. Lit.: “servo”.
====

[[v45-13-5]]

^<<v45-13-5,5>>^ Há, portanto, uma razão compulsiva^&#42;1^ para que estejais em sujeição, não somente por causa desse furor, mas também por causa da [vossa] consciência.

[NOTE]
====
. Lit.: “necessidade”.
====

[[v45-13-6]]

^<<v45-13-6,6>>^ Pois é também por isso que pagais impostos; porque eles são servidores públicos^&#42;1^ de Deus, servindo constantemente com este mesmo objetivo.^&#42;2^

[NOTE]
====
. “Servidores públicos.” Gr.: lei·tour·goí.
. Ou “devotando-se a esta mesma coisa”.
====

[[v45-13-7]]

^<<v45-13-7,7>>^ Rendei^&#42;1^ a todos o que lhes é devido, a quem [exigir] imposto, o imposto; a quem [exigir] tributo, o tributo; a quem [exigir] temor, tal temor; a quem [exigir] honra, tal honra.

[NOTE]
====
. Lit.: “Devolvei.”
====

[[v45-13-8]]

^<<v45-13-8,8>>^ A ninguém fiqueis devendo coisa alguma, exceto que vos ameis uns aos outros; pois, quem ama o seu próximo^&#42;1^ tem cumprido a lei.

[NOTE]
====
. Ou “ama o outro”, isto é, o outro de dois.
====

[[v45-13-9]]

^<<v45-13-9,9>>^ Pois o [código da lei]: “Não deves cometer adultério,^&#42;1^ não deves assassinar, não deves furtar, não deves cobiçar”, e qualquer outro mandamento que haja, está englobado nesta palavra, a saber: “Tens de amar o teu próximo como a ti mesmo.”

[NOTE]
====
. Ou: “Não deves cometer infidelidade marital sexual.” Gr.: Ou moi·kheú·seis; lat.: non a·dul·te·rá·bis; J22(hebr.): lo’ tin·’áf. Veja Ez 16:32 n.
====

[[v45-13-10]]

^<<v45-13-10,10>>^ O amor não obra o mal para com o próximo; portanto, o amor é o cumprimento da lei.

[[v45-13-11]]

^<<v45-13-11,11>>^ [Fazei] isto também porque sabeis a época,^&#42;1^ que já é hora de despertardes do sono, pois agora a nossa salvação está mais próxima do que quando nos tornamos crentes.

[NOTE]
====
. Lit.: “o tempo designado”. Gr.: kai·rón.
====

[[v45-13-12]]

^<<v45-13-12,12>>^ A noite está bem avançada; o dia já se tem aproximado. Portanto, ponhamos de lado as obras pertencentes à escuridão e revistamo-nos das armas da luz.

[[v45-13-13]]

^<<v45-13-13,13>>^ Andemos decentemente, como em pleno dia, não em festanças e em bebedeiras, nem em relações ilícitas e em conduta desenfreada,^&#42;1^ nem em rixa e ciúme.

[NOTE]
====
. “Conduta desenfreada.” Gr.: a·sel·geí·ais; lat.: in·pu·di·cí·ti·is; J17,22(hebr.): zim·máh. Veja Gál 5:19 n.: “desenfreada”. Compare isso com Le 18:17 n.
====

[[v45-13-14]]

^<<v45-13-14,14>>^ Mas revesti-vos do Senhor^&#42;1^ Jesus Cristo e não estejais planejando antecipadamente os desejos da carne.

[NOTE]
====
. Ou “imitai os modos do Senhor”.
====

'''

xref:045-romanos/045-romanos-012.adoc#v45-12-0[&#60; Capítulo Anterior] | <<v45-13-0,Topo>> | xref:045-romanos/045-romanos-014.adoc#v45-14-0[Próximo Capítulo &#62;]