include::./index.adoc[]

[[v45-3-0]]
=== Romanos, 3
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v45-3-1]]

^<<v45-3-1,1>>^ Qual é então a superioridade do judeu, ou qual é o proveito da circuncisão?

[[v45-3-2]]

^<<v45-3-2,2>>^ Grande, de todo modo. Primeiramente, porque foram incumbidos das proclamações sagradas^&#42;1^ de Deus.

[NOTE]
====
. “Proclamações sagradas.” Lit.: “pequenas palavras”. Gr.: ló·gi·a; lat.: e·ló·qui·a; J17,18,22(hebr.): div·réh.
====

[[v45-3-3]]

^<<v45-3-3,3>>^ Qual [é o caso], então? Se alguns não expressaram fé, porventura fará a sua falta de fé que a fidelidade de Deus seja sem efeito?

[[v45-3-4]]

^<<v45-3-4,4>>^ Que isso nunca aconteça! Mas, seja Deus achado verdadeiro, embora todo homem seja achado mentiroso, assim como está escrito: “Que sejas mostrado justo nas tuas palavras e venças quando estiveres sendo julgado.”

[[v45-3-5]]

^<<v45-3-5,5>>^ No entanto, que diremos, se a nossa injustiça salienta a justiça de Deus? Será que Deus é injusto quando dá vazão ao seu furor? (Estou falando como homem.)

[[v45-3-6]]

^<<v45-3-6,6>>^ Que isso nunca aconteça! Senão, como julgará Deus o mundo?

[[v45-3-7]]

^<<v45-3-7,7>>^ Contudo, se por causa da minha mentira a verdade de Deus tem sido destacada ainda mais para a glória dele, por que, também, sou ainda julgado pecador?

[[v45-3-8]]

^<<v45-3-8,8>>^ E [por que] não [dizer], assim como se nos acusa falsamente e assim como alguns homens declaram que dizemos: “Façamos as coisas más, para que venham as coisas boas”? O julgamento contra tais [homens] está em harmonia com a justiça.

[[v45-3-9]]

^<<v45-3-9,9>>^ O que então? Estamos em melhor situação? Absolutamente não! Pois já fizemos antes a acusação de que tanto os judeus como os gregos estão todos debaixo de pecado;^&#42;1^

[NOTE]
====
. “Pecado.” Gr.: ha·mar·tí·an; lat.: pec·cá·to; J17(hebr.): ha·hhét’, “o pecado”; duma raiz que significa “errar o alvo [como no arremesso duma lança]”. Veja v. 23.
====

[[v45-3-10]]

^<<v45-3-10,10>>^ assim como está escrito: “Não há um justo, nem sequer um só;

[[v45-3-11]]

^<<v45-3-11,11>>^ não há ninguém que tenha perspicácia, não há ninguém que busque a Deus.

[[v45-3-12]]

^<<v45-3-12,12>>^ Todos se apartaram, todos eles juntos se tornaram inúteis; não há ninguém que faça benignidade, não há nem sequer um só.”

[[v45-3-13]]

^<<v45-3-13,13>>^ “Sua garganta é um sepulcro aberto, com as suas línguas usaram de fraude.” “Veneno de áspides está atrás dos seus lábios.”

[[v45-3-14]]

^<<v45-3-14,14>>^ “E a sua boca está cheia de maldição e expressão amarga.”

[[v45-3-15]]

^<<v45-3-15,15>>^ “Seus pés são velozes para derramar sangue.”

[[v45-3-16]]

^<<v45-3-16,16>>^ “Ruína e miséria estão nos seus caminhos,

[[v45-3-17]]

^<<v45-3-17,17>>^ e não conheceram o caminho da paz.”

[[v45-3-18]]

^<<v45-3-18,18>>^ “Não há temor de Deus diante dos seus olhos.”^&#42;1^

[NOTE]
====
. As citações nos vv. 13-18 encontram-se no Sal 13:3 na LXX. Veja Sal 14:3 n.
====

[[v45-3-19]]

^<<v45-3-19,19>>^ Ora, nós sabemos que todas as coisas ditas pela Lei^&#42;1^ ela dirige aos que estão debaixo da Lei, a fim de que se tape cada boca e todo o mundo fique sujeito a Deus para punição.

[NOTE]
====
. “[Pel]a Lei.” Gr.: ho nó·mos, com o artigo definido ho para especificá-la. Aqui, o contexto justifica a inicial maiúscula para indicar que se trata da “Lei” dada por meio de Moisés. Em The Bible Translator, Vol. 1, de janeiro de 1950, publicado pelas Sociedades Bíblicas Unidas, Londres, p. 165, J. Harold Greenlee declara: “A palavra ‘lei’ requer atenção individual. O artigo [gr.] indica uma lei específica, ou a lei mosaica; sem o artigo, pode referir-se à ‘lei’ como um princípio.”
====

[[v45-3-20]]

^<<v45-3-20,20>>^ Portanto, por obras de lei, nenhuma carne será declarada justa diante dele, pois pela lei vem o conhecimento exato do pecado.

[[v45-3-21]]

^<<v45-3-21,21>>^ Mas agora, à parte da lei, foi manifestada a justiça de Deus, conforme lhe dão testemunho a Lei e os Profetas;

[[v45-3-22]]

^<<v45-3-22,22>>^ sim, a justiça de Deus por intermédio da fé em Jesus^&#42;1^ Cristo, para todos os que têm fé. Porque não há distinção.

[NOTE]
====
. “Jesus.” B omite isso.
====

[[v45-3-23]]

^<<v45-3-23,23>>^ Pois todos pecaram e não atingem a glória de Deus,

[[v45-3-24]]

^<<v45-3-24,24>>^ e é como dádiva gratuita que estão sendo declarados justos pela benignidade imerecida dele, por intermédio do livramento pelo resgate [pago] por Cristo^&#42;1^ Jesus.

[NOTE]
====
. Ou “por meio da redenção que há em (por) Cristo”.
====

[[v45-3-25]]

^<<v45-3-25,25>>^ Deus o apresentou como oferta de propiciação^&#42;1^ por intermédio da fé no seu sangue. Isto se deu, a fim de exibir a sua própria justiça, porque ele estava perdoando os pecados que ocorreram no passado, enquanto Deus exercia indulgência;

[NOTE]
====
. “Oferta de propiciação.” Lit.: “propiciatório”. Gr.: hi·la·sté·ri·on; lat.: pro·pi·ti·a·ti·ó·nem; J17(hebr.): lekhap·pó·reth, “como tampa propiciatória”. Veja He 9:5.
====

[[v45-3-26]]

^<<v45-3-26,26>>^ a fim de exibir a sua própria justiça nesta época atual, para que fosse justo, mesmo ao declarar justo o homem que tem fé em Jesus.

[[v45-3-27]]

^<<v45-3-27,27>>^ Onde está então a jactância? Está excluída. Por intermédio de que lei? A das obras? Não, deveras, mas por intermédio da lei da fé.

[[v45-3-28]]

^<<v45-3-28,28>>^ Pois nós consideramos que o homem é declarado justo^&#42;1^ pela fé, à parte das obras da lei.

[NOTE]
====
. Lit.: “há de ser justificado”. Gr.: di·kai·oú·sthai; lat.: iu·sti·fi·cá·ri.
====

[[v45-3-29]]

^<<v45-3-29,29>>^ Ou é ele somente o Deus dos judeus? Não o é também de pessoas das nações? Sim, também de pessoas das nações,

[[v45-3-30]]

^<<v45-3-30,30>>^ se Deus verdadeiramente é um só, o qual declarará justos os circuncisos em resultado da fé e os incircuncisos por meio de sua fé.

[[v45-3-31]]

^<<v45-3-31,31>>^ Abolimos então a lei por meio de nossa fé? Que isso nunca aconteça! Ao contrário, estabelecemos lei.

'''

xref:045-romanos/045-romanos-002.adoc#v45-2-0[&#60; Capítulo Anterior] | <<v45-3-0,Topo>> | xref:045-romanos/045-romanos-004.adoc#v45-4-0[Próximo Capítulo &#62;]