include::./index.adoc[]

[[v45-5-0]]
=== Romanos, 5
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v45-5-1]]

^<<v45-5-1,1>>^ Portanto, agora que temos sido declarados justos em resultado da fé, gozemos de paz com Deus por intermédio de nosso Senhor Jesus Cristo,

[[v45-5-2]]

^<<v45-5-2,2>>^ por intermédio de quem também ganhamos a nossa aproximação pela fé^&#42;1^ a esta benignidade imerecida em que agora estamos; e exultemos, baseados na esperança da glória de Deus.

[NOTE]
====
. “Pela fé.” BD omitem isso.
====

[[v45-5-3]]

^<<v45-5-3,3>>^ E não somente isso, mas exultemos enquanto em tribulações, visto que sabemos que tribulação produz perseverança;

[[v45-5-4]]

^<<v45-5-4,4>>^ perseverança, por sua vez, uma condição aprovada; a condição aprovada, por sua vez, esperança,

[[v45-5-5]]

^<<v45-5-5,5>>^ e a esperança não conduz a desapontamento;^&#42;1^ porque o amor de Deus tem sido derramado em nossos corações por intermédio do espírito santo, que nos foi dado.

[NOTE]
====
. Ou “vergonha”.
====

[[v45-5-6]]

^<<v45-5-6,6>>^ Pois, deveras, Cristo, enquanto ainda éramos fracos, morreu por homens ímpios,^&#42;1^ no tempo designado.

[NOTE]
====
. Ou “[pelos] irreverentes”. Gr.: a·se·bón; lat.: ím·pi·is, “ímpios”.
====

[[v45-5-7]]

^<<v45-5-7,7>>^ Pois, dificilmente morrerá alguém por um justo; deveras, por um [homem] bom, talvez, alguém ainda se atreva a morrer.

[[v45-5-8]]

^<<v45-5-8,8>>^ Mas Deus recomenda a nós o seu próprio amor, por Cristo ter morrido por nós enquanto éramos ainda pecadores.

[[v45-5-9]]

^<<v45-5-9,9>>^ Muito mais, portanto, visto que agora fomos declarados justos pelo seu sangue, havemos de ser salvos do furor por intermédio dele.

[[v45-5-10]]

^<<v45-5-10,10>>^ Pois se nós, quando éramos inimigos, ficamos reconciliados com Deus por intermédio da morte de seu Filho, muito mais agora, que temos ficado reconciliados, seremos salvos pela sua vida.

[[v45-5-11]]

^<<v45-5-11,11>>^ E não somente isso, mas exultemos também em Deus por intermédio de nosso Senhor Jesus Cristo,^&#42;1^ por meio de quem temos agora recebido a reconciliação.

[NOTE]
====
. “Cristo.” B omite isso.
====

[[v45-5-12]]

^<<v45-5-12,12>>^ É por isso que, assim como por intermédio de um só homem entrou o pecado no mundo, e a morte por intermédio do pecado, e assim a morte se espalhou a todos os homens, porque todos tinham pecado —.

[[v45-5-13]]

^<<v45-5-13,13>>^ Pois, até à Lei havia pecado no mundo, mas o pecado não é imputado a ninguém quando não há lei.

[[v45-5-14]]

^<<v45-5-14,14>>^ Não obstante, a morte reinou desde Adão até Moisés, mesmo sobre os que não tinham pecado na semelhança da transgressão de Adão, o qual tem similaridade com aquele^&#42;1^ que havia de vir.

[NOTE]
====
. Ou “o qual é tipo dele”.
====

[[v45-5-15]]

^<<v45-5-15,15>>^ Mas, não é com o dom como é com a falha. Porque, se pela falha de um só homem muitos morreram, abundou muito mais, para com muitos, a benignidade imerecida de Deus e a sua dádiva gratuita com a benignidade imerecida por um só homem, Jesus Cristo.

[[v45-5-16]]

^<<v45-5-16,16>>^ Também, com a dádiva gratuita não é assim como se dava com as coisas por intermédio daquele um que pecou. Pois o julgamento resultou de uma só falha em condenação, mas o dom resultou de muitas falhas numa declaração de justiça.^&#42;1^

[NOTE]
====
. Ou “num ato de justificação”. Veja v. 18.
====

[[v45-5-17]]

^<<v45-5-17,17>>^ Porque, se pela falha de um só [homem] a morte reinou por intermédio daquele um, muito mais aqueles que recebem a abundância da benignidade imerecida e da dádiva gratuita^&#42;1^ da justiça reinarão em vida por intermédio de um só, Jesus Cristo.

[NOTE]
====
. “Da dádiva gratuita.” B omite isso.
====

[[v45-5-18]]

^<<v45-5-18,18>>^ Assim, pois, como por intermédio de uma só falha resultou a condenação para homens de toda sorte, do mesmo modo também por um só ato de justificação^&#42;1^ resulta para homens de toda sorte serem declarados justos para a vida.

[NOTE]
====
. Ou “um só ato justo”. Gr.: he·nós di·kai·ó·ma·tos; lat.: u·ní·us iu·stí·ti·am.
====

[[v45-5-19]]

^<<v45-5-19,19>>^ Pois, assim como pela desobediência de um só homem muitos foram constituídos pecadores, do mesmo modo também pela obediência de um só muitos serão constituídos justos.

[[v45-5-20]]

^<<v45-5-20,20>>^ Ora, a Lei veio além disso,^&#42;1^ a fim de que abundasse a falha. Mas, onde abundou o pecado, a benignidade imerecida abundou ainda mais.

[NOTE]
====
. Ou “entrou furtivamente”.
====

[[v45-5-21]]

^<<v45-5-21,21>>^ Para que fim? Para que, assim como o pecado reinou com a morte, do mesmo modo também a benignidade imerecida reinasse por intermédio da justiça, visando a vida eterna por intermédio de Jesus Cristo, nosso Senhor.

'''

xref:045-romanos/045-romanos-004.adoc#v45-4-0[&#60; Capítulo Anterior] | <<v45-5-0,Topo>> | xref:045-romanos/045-romanos-006.adoc#v45-6-0[Próximo Capítulo &#62;]