include::./index.adoc[]

[[v45-11-0]]
=== Romanos, 11
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v45-11-1]]

^<<v45-11-1,1>>^ Pergunto então: Será que Deus rejeitou o seu povo? Que isso nunca aconteça! Pois eu também sou israelita, do descendente de Abraão, da tribo de Benjamim.

[[v45-11-2]]

^<<v45-11-2,2>>^ Deus não rejeitou o seu povo, ao qual primeiro reconheceu.^&#42;1^ Ora, não sabeis o que a Escritura diz em conexão com Elias, quando ele pleiteou perante Deus contra Israel?

[NOTE]
====
. Ou “conheceu de antemão”.
====

[[v45-11-3]]

^<<v45-11-3,3>>^ “Jeová,^&#42;1^ mataram os teus profetas, solaparam os teus altares, e só eu sobrei, e eles estão procurando a minha alma.”^&#42;2^

[NOTE]
====
. Veja Ap. 1D.
. Ou “vida”. Veja Ap. 4A.
====

[[v45-11-4]]

^<<v45-11-4,4>>^ No entanto, o que lhe diz a proclamação divina? “Deixei remanescer para mim sete mil homens, os quais não dobraram o joelho diante de Baal.”

[[v45-11-5]]

^<<v45-11-5,5>>^ Deste modo, portanto, apresentou-se também na época atual um restante, segundo uma escolha devida à benignidade imerecida.

[[v45-11-6]]

^<<v45-11-6,6>>^ Ora, se é por benignidade imerecida, já não é mais devido a obras; senão, a benignidade imerecida não se mostraria mais benignidade imerecida.

[[v45-11-7]]

^<<v45-11-7,7>>^ O que então? A própria coisa que Israel está buscando seriamente, não obteve, mas os escolhidos^&#42;1^ a obtiveram. Os demais tiveram as suas sensibilidades embotadas;

[NOTE]
====
. “Os escolhidos.” Lit.: “a escolha; a eleição”.
====

[[v45-11-8]]

^<<v45-11-8,8>>^ assim como está escrito: “Deus^&#42;1^ lhes deu um espírito de profundo sono, olhos para que não vejam e ouvidos para que não ouçam, até o dia de hoje.”

[NOTE]
====
. “Deus”, אABVgSyp; J7,8,10,13-15,20: “Jeová”.
====

[[v45-11-9]]

^<<v45-11-9,9>>^ Também, Davi diz: “Que a sua mesa^&#42;1^ se torne para eles laço, e armadilha, e pedra de tropeço, e retribuição;

[NOTE]
====
. Isto é, uma mesa para sacrifícios. Ou “banquete”.
====

[[v45-11-10]]

^<<v45-11-10,10>>^ obscureçam-se-lhes os olhos, para que não vejam, e sempre curvem as suas costas.”

[[v45-11-11]]

^<<v45-11-11,11>>^ Portanto, pergunto: Tropeçaram eles, de modo que caíram completamente? Que isso nunca aconteça! Mas, por seu passo em falso há salvação para pessoas das nações, para incitá-los ao ciúme.

[[v45-11-12]]

^<<v45-11-12,12>>^ Ora, se o seu passo em falso significa riquezas para o mundo, e o seu decréscimo significa riquezas para pessoas das nações, quanto mais o significará o pleno número^&#42;1^ deles!

[NOTE]
====
. Ou “a plenitude”.
====

[[v45-11-13]]

^<<v45-11-13,13>>^ Agora falo a vós, os que sois pessoas das nações. Visto que sou, na realidade, apóstolo para as nações, glorifico o meu ministério,

[[v45-11-14]]

^<<v45-11-14,14>>^ para ver se de algum modo posso incitar ao ciúme [os que são] da minha própria carne e salvar alguns dentre eles.

[[v45-11-15]]

^<<v45-11-15,15>>^ Pois, se serem lançados fora significa reconciliação para o mundo, o que significará o acolhimento deles, senão vida dentre os mortos?

[[v45-11-16]]

^<<v45-11-16,16>>^ Além disso, se a [parte tomada como] primícias é santa, a massa também o é; e, se a raiz é santa, os ramos também o são.

[[v45-11-17]]

^<<v45-11-17,17>>^ No entanto, se alguns dos ramos foram arrancados, mas tu, embora sendo oliveira brava, foste enxertado entre eles e te tornaste compartilhador da raiz de untuosidade da oliveira,

[[v45-11-18]]

^<<v45-11-18,18>>^ não exultes sobre os ramos. Se, porém, exultares sobre eles, não és tu que suportas a raiz, mas a raiz [suporta] a ti.

[[v45-11-19]]

^<<v45-11-19,19>>^ Dirás, então: “Os ramos foram arrancados para que eu fosse enxertado.”

[[v45-11-20]]

^<<v45-11-20,20>>^ Está bem! Foram arrancados por [sua] falta de fé, mas tu estás de pé pela fé. Cessa de ter idéias altivas, mas tem temor.

[[v45-11-21]]

^<<v45-11-21,21>>^ Pois, se Deus não poupou os ramos naturais, tampouco te poupará a ti.

[[v45-11-22]]

^<<v45-11-22,22>>^ Eis, portanto, a benignidade e a severidade de Deus. Para com aqueles que caíram, há severidade, mas para contigo há a benignidade de Deus, desde que permaneças na sua benignidade; senão, tu também serás cortado fora.

[[v45-11-23]]

^<<v45-11-23,23>>^ Eles, também, se não permanecerem na sua falta de fé, serão enxertados; pois Deus é capaz de enxertá-los novamente.

[[v45-11-24]]

^<<v45-11-24,24>>^ Porque, se foste cortado da oliveira que é brava por natureza e foste enxertado, contrário à natureza, numa oliveira cultivada, quanto mais aqueles, que são naturais, serão enxertados na sua própria oliveira!

[[v45-11-25]]

^<<v45-11-25,25>>^ Pois não quero, irmãos, que sejais ignorantes deste segredo sagrado, a fim de que não sejais discretos aos vossos próprios olhos: que a obtusão das sensibilidades aconteceu em parte a Israel, até que tenha entrado o pleno número^&#42;1^ de pessoas das nações,

[NOTE]
====
. Ou “a plenitude”.
====

[[v45-11-26]]

^<<v45-11-26,26>>^ e desta maneira é que todo o Israel será salvo. Assim como está escrito: “O libertador sairá de Sião e afastará de Jacó as práticas ímpias.

[[v45-11-27]]

^<<v45-11-27,27>>^ E este é o pacto da minha parte com eles, quando eu tirar os seus pecados.”

[[v45-11-28]]

^<<v45-11-28,28>>^ Verdadeiramente, eles, com referência às boas novas, são inimigos por vossa causa, mas, com referência à escolha [de Deus],^&#42;1^ são amados por causa de seus antepassados.

[NOTE]
====
. “Escolha [de Deus].” Ou “a escolha; os escolhidos”.
====

[[v45-11-29]]

^<<v45-11-29,29>>^ Pois os dons e a chamada de Deus não são coisas que ele deplorará.

[[v45-11-30]]

^<<v45-11-30,30>>^ Pois, assim como fostes uma vez desobedientes a Deus, porém, mostrou-se agora misericórdia para convosco por causa da desobediência deles,

[[v45-11-31]]

^<<v45-11-31,31>>^ assim também estes têm sido agora desobedientes, resultando em misericórdia para vós, para que se mostrasse agora também misericórdia para com eles.

[[v45-11-32]]

^<<v45-11-32,32>>^ Porque Deus encerrou todos juntos na desobediência, a fim de mostrar misericórdia para com todos eles.

[[v45-11-33]]

^<<v45-11-33,33>>^ Ó profundidade das riquezas, e da sabedoria, e do conhecimento de Deus! Quão inescrutáveis [são] os seus julgamentos e além de pesquisa [são] os seus caminhos!

[[v45-11-34]]

^<<v45-11-34,34>>^ Pois, “quem veio a conhecer a mente de Jeová^&#42;1^ ou quem se tornou o seu conselheiro”?

[NOTE]
====
. Veja Ap. 1D.
====

[[v45-11-35]]

^<<v45-11-35,35>>^ Ou: “Quem primeiro lhe deu, de modo que se lhe tenha de pagar de volta?”

[[v45-11-36]]

^<<v45-11-36,36>>^ Porque todas as coisas são dele, e por ele, e para ele. Glória a ele para sempre. Amém.

'''

xref:045-romanos/045-romanos-010.adoc#v45-10-0[&#60; Capítulo Anterior] | <<v45-11-0,Topo>> | xref:045-romanos/045-romanos-012.adoc#v45-12-0[Próximo Capítulo &#62;]