include::./index.adoc[]

[[v45-10-0]]
=== Romanos, 10
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v45-10-1]]

^<<v45-10-1,1>>^ Irmãos, a boa vontade do meu coração e as minhas súplicas por eles a Deus são, deveras, para a salvação deles.

[[v45-10-2]]

^<<v45-10-2,2>>^ Pois eu lhes dou testemunho^&#42;1^ de que têm zelo de Deus, mas não segundo o conhecimento exato;

[NOTE]
====
. “Dou testemunho.” Gr.: mar·ty·ró; lat.: te·sti·mó·ni·um per·hí·be·o.
====

[[v45-10-3]]

^<<v45-10-3,3>>^ pois, por não conhecerem a justiça de Deus, mas buscarem estabelecer a sua própria, não se sujeitaram à justiça de Deus.

[[v45-10-4]]

^<<v45-10-4,4>>^ Porque Cristo é o fim^&#42;1^ da Lei, para que todo aquele que exercer fé possa ter justiça.

[NOTE]
====
. Ou “o remate; fim completo”. Gr.: té·los.
====

[[v45-10-5]]

^<<v45-10-5,5>>^ Pois Moisés escreve que o homem que tem feito a justiça da Lei viverá por ela.

[[v45-10-6]]

^<<v45-10-6,6>>^ Mas a justiça resultante da fé fala da seguinte maneira: “Não digas no teu coração: ‘Quem ascenderá ao céu?’ isto é, para fazer descer a Cristo;

[[v45-10-7]]

^<<v45-10-7,7>>^ ou: ‘Quem descerá ao abismo?’ isto é, para fazer subir a Cristo dentre os mortos.”

[[v45-10-8]]

^<<v45-10-8,8>>^ Mas, o que diz? “A palavra está perto de ti, na tua própria boca e no teu próprio coração”; isto é, a “palavra” da fé, que estamos pregando.^&#42;1^

[NOTE]
====
. Ou “estamos proclamando”. Gr.: ke·rýs·so·men; lat.: prae·di·cá·mus. Veja Da 5:29 n.: “proclamaram”.
====

[[v45-10-9]]

^<<v45-10-9,9>>^ Pois, se declarares publicamente essa ‘palavra na tua própria boca’, que Jesus é Senhor,^&#42;1^ e no teu coração exerceres fé, que Deus o levantou dentre os mortos, serás salvo.

[NOTE]
====
. Gr.: ký·ri·os; J12-14,16-18,22(hebr.): ha·’a·dhóhn, “o Senhor”. Não “Jeová”.
====

[[v45-10-10]]

^<<v45-10-10,10>>^ Porque com o coração se exerce fé para a justiça, mas com a boca se faz declaração pública para a salvação.

[[v45-10-11]]

^<<v45-10-11,11>>^ Pois a Escritura diz: “Ninguém que basear nele a sua fé ficará desapontado.”^&#42;1^

[NOTE]
====
. Ou “envergonhado”.
====

[[v45-10-12]]

^<<v45-10-12,12>>^ Pois não há distinção entre judeu e grego, porque há o mesmo Senhor sobre todos, que é rico para com todos os que o invocam.

[[v45-10-13]]

^<<v45-10-13,13>>^ Pois “todo aquele que invocar o nome de Jeová^&#42;1^ será salvo”.

[NOTE]
====
. Veja Ap. 1D.
====

[[v45-10-14]]

^<<v45-10-14,14>>^ No entanto, como invocarão aquele em quem não depositaram fé? Por sua vez, como depositarão fé naquele de quem não ouviram [falar]? Por sua vez, como ouvirão, se não houver quem pregue?

[[v45-10-15]]

^<<v45-10-15,15>>^ Por sua vez, como pregarão, a menos que tenham sido enviados? Assim como está escrito: “Quão lindos são os pés daqueles que declaram boas novas de coisas boas!”

[[v45-10-16]]

^<<v45-10-16,16>>^ Não obstante, nem todos obedeceram às boas novas. Pois Isaías diz: “Jeová,^&#42;1^ quem depositou fé na coisa ouvida de nós?”

[NOTE]
====
. Veja Ap. 1D.
====

[[v45-10-17]]

^<<v45-10-17,17>>^ De modo que a fé segue à coisa ouvida. Por sua vez, a coisa ouvida vem por intermédio da palavra acerca de Cristo.^&#42;1^

[NOTE]
====
. “Palavra acerca de Cristo”, P46א°BCD°Vg; אcASyp: “palavra de Deus”; J7,8,10: “palavra de Jeová”.
====

[[v45-10-18]]

^<<v45-10-18,18>>^ Não obstante, pergunto: Será que ficaram sem ouvir? Ora, de fato, “o som deles saiu por toda a terra, e as suas pronunciações, até às extremidades^&#42;1^ da terra habitada”.^&#42;2^

[NOTE]
====
. Veja Mt 12:42 n.
. “Terra habitada.” Lit.: “habitada”. Gr.: oi·kou·mé·nes, fem. sing., subentendendo-se a terra.
====

[[v45-10-19]]

^<<v45-10-19,19>>^ Não obstante, pergunto: Será que Israel ficou sem saber? Primeiro, Moisés diz: “Eu vos incitarei ao ciúme por intermédio daquilo que não é nação; eu vos incitarei à ira violenta por intermédio duma nação estúpida.”

[[v45-10-20]]

^<<v45-10-20,20>>^ Mas, Isaías torna-se muito ousado e diz: “Fui achado por aqueles que não me buscavam; tornei-me manifesto aos que não perguntavam por mim.”

[[v45-10-21]]

^<<v45-10-21,21>>^ Mas, com respeito a Israel, ele diz: “O dia inteiro estendi as minhas mãos para um povo desobediente e contradizente.”

'''

xref:045-romanos/045-romanos-009.adoc#v45-9-0[&#60; Capítulo Anterior] | <<v45-10-0,Topo>> | xref:045-romanos/045-romanos-011.adoc#v45-11-0[Próximo Capítulo &#62;]