include::./index.adoc[]

[[v45-14-0]]
=== Romanos, 14
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v45-14-1]]

^<<v45-14-1,1>>^ Acolhei o [homem] que tem fraquezas na [sua] fé, mas não para fazer decisões sobre questões subjetivas.

[[v45-14-2]]

^<<v45-14-2,2>>^ Um [homem] tem fé para comer de tudo, mas o [homem] que é fraco come hortaliças.

[[v45-14-3]]

^<<v45-14-3,3>>^ Quem come não menospreze ao que não come, e quem não come não julgue aquele que come, pois Deus tem acolhido a esse.

[[v45-14-4]]

^<<v45-14-4,4>>^ Quem és tu para julgares o servo doméstico de outro? Para o seu próprio amo está em pé ou cai. Deveras, far-se-á que ele fique em pé, pois Jeová^&#42;1^ pode fazê-lo ficar em pé.

[NOTE]
====
. “Jeová”, J18,23; P46אABC(gr.): ho Ký·ri·os; DVgSyh: “Deus”. Veja Ap. 1D.
====

[[v45-14-5]]

^<<v45-14-5,5>>^ Um [homem] julga um dia como superior a outro; outro [homem] julga um dia como todos os outros; esteja cada [homem] plenamente convencido na sua própria mente.

[[v45-14-6]]

^<<v45-14-6,6>>^ Quem observa o dia, observa-o para com Jeová.^&#42;1^ Também, quem come, come para com Jeová,^&#42;2^ pois dá graças a Deus; e aquele que não come, não come para com Jeová,^&#42;3^ contudo, dá graças a Deus.

[NOTE]
====
. Veja Ap. 1D.
. Veja Ap. 1D.
. Veja Ap. 1D.
====

[[v45-14-7]]

^<<v45-14-7,7>>^ Nenhum de nós, de fato, vive somente para si mesmo, e ninguém morre somente para si mesmo;

[[v45-14-8]]

^<<v45-14-8,8>>^ pois, quer vivamos, vivemos para Jeová,^&#42;1^ quer morramos, morremos para Jeová.^&#42;2^ Portanto, quer vivamos quer morramos, pertencemos a Jeová.^&#42;3^

[NOTE]
====
. Veja Ap. 1D.
. Veja Ap. 1D.
. Veja Ap. 1D.
====

[[v45-14-9]]

^<<v45-14-9,9>>^ Pois, para este fim morreu Cristo e passou a viver novamente, para que fosse Senhor tanto sobre mortos como [sobre] viventes.

[[v45-14-10]]

^<<v45-14-10,10>>^ Mas, por que julgas tu o teu irmão? Ou, por que menosprezas também o teu irmão? Porque nós todos ficaremos postados diante da cadeira de juiz de Deus;

[[v45-14-11]]

^<<v45-14-11,11>>^ pois está escrito: “‘Por minha vida’, diz Jeová,^&#42;1^ ‘todo joelho se dobrará diante de mim e toda língua reconhecerá abertamente a Deus’.”

[NOTE]
====
. Veja Ap. 1D.
====

[[v45-14-12]]

^<<v45-14-12,12>>^ Assim, pois, cada um de nós prestará contas de si mesmo a Deus.^&#42;1^

[NOTE]
====
. “A Deus”, אADVgSyh,p; B omite isso.
====

[[v45-14-13]]

^<<v45-14-13,13>>^ Portanto, não nos julguemos mais uns aos outros, mas, antes, tomai esta decisão, de não pordes diante dum irmão uma pedra de tropeço ou uma causa para cair.

[[v45-14-14]]

^<<v45-14-14,14>>^ Sei e estou persuadido no Senhor Jesus que nada é aviltado em si mesmo; somente quando um homem considera algo como aviltado, para ele é aviltado.

[[v45-14-15]]

^<<v45-14-15,15>>^ Porque, se teu irmão, por causa do alimento, está sendo contristado, não estás mais andando de acordo com o amor. Não arruínes pela tua comida aquele pelo qual Cristo morreu.

[[v45-14-16]]

^<<v45-14-16,16>>^ Portanto, não deixeis que se fale com dano para vós do bem que fazeis.

[[v45-14-17]]

^<<v45-14-17,17>>^ Pois o reino de Deus não significa^&#42;1^ comer e beber, mas [significa]^&#42;2^ justiça, e paz, e alegria com espírito santo.

[NOTE]
====
. Ou “não é”.
. Ou “mas [é]”.
====

[[v45-14-18]]

^<<v45-14-18,18>>^ Pois, quem neste sentido trabalhar como escravo para Cristo, é aceitável a Deus e tem aprovação da parte dos homens.

[[v45-14-19]]

^<<v45-14-19,19>>^ Assim, pois, empenhemo-nos pelas coisas que produzem paz e pelas coisas que são para a edificação mútua.

[[v45-14-20]]

^<<v45-14-20,20>>^ Parai de demolir a obra de Deus só por causa do alimento. Verdadeiramente, todas as coisas são limpas, mas é prejudicial para o homem que come com motivo para tropeço.

[[v45-14-21]]

^<<v45-14-21,21>>^ É bom não comer carne, nem beber vinho, nem fazer algo que faça teu irmão tropeçar.

[[v45-14-22]]

^<<v45-14-22,22>>^ A fé que tens, tem-na de acordo contigo mesmo à vista de Deus. Feliz é o homem que não se põe a si mesmo em julgamento por aquilo que ele aprova.

[[v45-14-23]]

^<<v45-14-23,23>>^ Mas, se tiver dúvidas, já está condenado, se comer, porque não [come] em fé. Deveras, tudo o que não vem da fé é pecado.

'''

xref:045-romanos/045-romanos-013.adoc#v45-13-0[&#60; Capítulo Anterior] | <<v45-14-0,Topo>> | xref:045-romanos/045-romanos-015.adoc#v45-15-0[Próximo Capítulo &#62;]