include::./index.adoc[]

[[v45-8-0]]
=== Romanos, 8
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v45-8-1]]

^<<v45-8-1,1>>^ Portanto, os em união com Cristo Jesus não têm nenhuma condenação.

[[v45-8-2]]

^<<v45-8-2,2>>^ Pois a lei desse espírito que dá vida em união com Cristo Jesus libertou-te da lei do pecado e da morte.

[[v45-8-3]]

^<<v45-8-3,3>>^ Porque, havendo incapacidade da parte da Lei, enquanto ela estava fraca por intermédio da carne, Deus, por enviar o seu próprio Filho na semelhança da carne pecaminosa e concernente ao pecado, condenou o pecado na carne,

[[v45-8-4]]

^<<v45-8-4,4>>^ para que a exigência justa da Lei se cumprisse em nós, os que andamos, não de acordo com a carne, mas de acordo com o espírito.

[[v45-8-5]]

^<<v45-8-5,5>>^ Pois, os que estão de acordo com a carne fixam as suas mentes nas coisas da carne, mas os que estão de acordo com o espírito, nas coisas do espírito.

[[v45-8-6]]

^<<v45-8-6,6>>^ Pois a mentalidade segundo a carne significa morte, mas a mentalidade segundo o espírito significa vida e paz;

[[v45-8-7]]

^<<v45-8-7,7>>^ porque a mentalidade segundo a carne significa inimizade com Deus, visto que não está em sujeição à lei de Deus, de fato, nem pode estar.

[[v45-8-8]]

^<<v45-8-8,8>>^ De modo que os que estão em harmonia com a carne não podem agradar a Deus.

[[v45-8-9]]

^<<v45-8-9,9>>^ No entanto, vós estais em harmonia, não com a carne, mas com o espírito, se o espírito de Deus verdadeiramente morar em vós. Mas, se alguém não tiver o espírito de Cristo, este não pertence a ele.

[[v45-8-10]]

^<<v45-8-10,10>>^ Se, porém, Cristo está em união convosco, o corpo, deveras, está morto por causa do pecado, mas o espírito é vida, por causa da justiça.

[[v45-8-11]]

^<<v45-8-11,11>>^ Então, se morar em vós o espírito daquele que levantou a Jesus dentre os mortos, aquele que levantou a Cristo Jesus dentre os mortos também vivificará os vossos corpos mortais por intermédio do seu espírito que reside em vós.

[[v45-8-12]]

^<<v45-8-12,12>>^ Assim, pois, irmãos, não temos obrigação para com a carne, para viver de acordo com a carne;

[[v45-8-13]]

^<<v45-8-13,13>>^ pois, se viverdes de acordo com a carne, certamente morrereis; mas, se pelo espírito entregardes à morte as práticas do corpo, vivereis.

[[v45-8-14]]

^<<v45-8-14,14>>^ Porque todos os que são conduzidos pelo espírito de Deus, estes são filhos de Deus.

[[v45-8-15]]

^<<v45-8-15,15>>^ Pois não recebestes um espírito de escravidão, causando novamente temor, mas recebestes um espírito de adoção, como filhos,^&#42;1^ espírito pelo qual clamamos: “Aba,^&#42;2^ Pai!”

[NOTE]
====
. “De adoção, como filhos.” Lit.: “de colocação como filho”. Gr.: hui·o·the·sí·as; lat.: a·do·pti·ó·nis fi·li·ó·rum.
. “Aba.” Palavra aram. que significa “o pai”, ou: “ó Pai!”
====

[[v45-8-16]]

^<<v45-8-16,16>>^ O próprio espírito dá testemunho com o nosso espírito de que somos filhos de Deus.

[[v45-8-17]]

^<<v45-8-17,17>>^ Então, se somos filhos, somos também herdeiros: deveras, herdeiros de Deus, mas co-herdeiros de Cristo, desde que soframos juntamente, para que também sejamos glorificados juntamente.

[[v45-8-18]]

^<<v45-8-18,18>>^ Conseqüentemente, eu considero os sofrimentos da época atual como não importando em nada, em comparação com a glória que há de ser revelada em nós.

[[v45-8-19]]

^<<v45-8-19,19>>^ Pois a expectativa ansiosa da criação está esperando a revelação dos filhos de Deus.

[[v45-8-20]]

^<<v45-8-20,20>>^ Porque a criação estava sujeita à futilidade, não de sua própria vontade, mas por intermédio daquele que a sujeitou, à base da esperança

[[v45-8-21]]

^<<v45-8-21,21>>^ de que^&#42;1^ a própria criação também será liberta da escravização à corrupção e terá a liberdade gloriosa dos filhos de Deus.

[NOTE]
====
. Ou “porque”.
====

[[v45-8-22]]

^<<v45-8-22,22>>^ Pois sabemos que toda a criação junta persiste em gemer e junta está em dores até agora.

[[v45-8-23]]

^<<v45-8-23,23>>^ Não somente isso, mas também nós mesmos, os que temos as primícias, a saber, o espírito, sim, nós mesmos gememos em nosso íntimo, ao passo que esperamos seriamente a adoção como filhos,^&#42;1^ sermos livrados de nossos corpos por meio de resgate.

[NOTE]
====
. “Adoção como filhos”, אABCVgSyh,p; P46D omitem isso.
====

[[v45-8-24]]

^<<v45-8-24,24>>^ Pois fomos salvos nesta esperança; mas a esperança que se vê não é esperança, porque quando um homem vê uma coisa, acaso está esperando por ela?

[[v45-8-25]]

^<<v45-8-25,25>>^ Mas, se esperamos por aquilo que não vemos, persistimos em esperar com perseverança.

[[v45-8-26]]

^<<v45-8-26,26>>^ De maneira semelhante, o espírito também se junta com ajuda para a nossa fraqueza; pois não sabemos o [problema de] em prol de que devemos orar assim como necessitamos, mas o próprio espírito implora por nós com gemidos não pronunciados.^&#42;1^

[NOTE]
====
. Ou “que não podem ser pronunciados”.
====

[[v45-8-27]]

^<<v45-8-27,27>>^ Contudo, aquele que pesquisa os corações sabe o sentido^&#42;1^ do espírito, porque está intercedendo de acordo com Deus, a favor dos santos.

[NOTE]
====
. Ou “a idéia; o pensamento”.
====

[[v45-8-28]]

^<<v45-8-28,28>>^ Ora, nós sabemos que Deus^&#42;1^ faz que todas as suas obras cooperem para o bem daqueles que amam a Deus, os que são os chamados segundo o seu propósito;

[NOTE]
====
. “Deus”, P46AB; אCDVgSyp omitem isso.
====

[[v45-8-29]]

^<<v45-8-29,29>>^ porque aqueles a quem deu o seu primeiro reconhecimento,^&#42;1^ a [esses] também predeterminou^&#42;2^ que fossem modelados segundo a imagem de seu Filho, para que este fosse primogênito entre muitos irmãos.

[NOTE]
====
. Ou “a quem conheceu de antemão”.
. Lit.: “definiu de antemão”.
====

[[v45-8-30]]

^<<v45-8-30,30>>^ Ademais, os que ele predeterminou são também os que chamou; e os que ele chamou são também os que declarou justos. Finalmente, os que ele declarou justos são também os que glorificou.

[[v45-8-31]]

^<<v45-8-31,31>>^ Que diremos, então, quanto a estas coisas? Se Deus é por nós, quem será^&#42;1^ contra nós?

[NOTE]
====
. Ou “é; pode ser”.
====

[[v45-8-32]]

^<<v45-8-32,32>>^ Aquele que nem mesmo poupou o seu próprio Filho, mas o entregou por todos nós, por que não nos dará também com ele bondosamente todas as outras coisas?

[[v45-8-33]]

^<<v45-8-33,33>>^ Quem levantará acusação contra os escolhidos de Deus? É Deus quem [os] declara justos.

[[v45-8-34]]

^<<v45-8-34,34>>^ Quem é que condenará? Cristo Jesus^&#42;1^ é aquele que morreu, sim, antes, [é] aquele que foi levantado dentre os mortos,^&#42;2^ que está à direita de Deus, que também intercede por nós.

[NOTE]
====
. “Jesus”, אAC; BDSyp omitem isso.
. “Dentre os mortos”, AC; P46BDVgSyp omitem isso.
====

[[v45-8-35]]

^<<v45-8-35,35>>^ Quem nos separará do amor do Cristo?^&#42;1^ Acaso tribulação, ou aflição, ou perseguição, ou fome, ou nudez, ou perigo, ou espada?

[NOTE]
====
. “Do Cristo”, CDItVgSyh,p; א: “Deus”; B: “Deus, que está em Cristo Jesus.”
====

[[v45-8-36]]

^<<v45-8-36,36>>^ Assim como está escrito: “Por tua causa estamos sendo entregues à morte o dia inteiro, temos sido considerados como ovelhas para a matança.”

[[v45-8-37]]

^<<v45-8-37,37>>^ Ao contrário, em todas estas coisas estamos sendo completamente vitoriosos, por intermédio daquele que nos amou.

[[v45-8-38]]

^<<v45-8-38,38>>^ Pois estou convencido de que nem a morte, nem a vida, nem anjos, nem governos, nem coisas presentes, nem coisas por vir, nem poderes,

[[v45-8-39]]

^<<v45-8-39,39>>^ nem altura, nem profundidade, nem qualquer outra criação será capaz de nos separar do amor de Deus, que está em Cristo Jesus, nosso Senhor.

'''

xref:045-romanos/045-romanos-007.adoc#v45-7-0[&#60; Capítulo Anterior] | <<v45-8-0,Topo>> | xref:045-romanos/045-romanos-009.adoc#v45-9-0[Próximo Capítulo &#62;]