include::./index.adoc[]

[[v45-2-0]]
=== Romanos, 2
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v45-2-1]]

^<<v45-2-1,1>>^ Por isso és inescusável, ó homem, quem quer que sejas, se julgares; pois, nas coisas em que julgas outro, condenas a ti mesmo, visto que tu, que julgas, praticas as mesmas coisas.

[[v45-2-2]]

^<<v45-2-2,2>>^ Ora, sabemos que o julgamento de Deus, de acordo com a verdade, é contra os que praticam tais coisas.

[[v45-2-3]]

^<<v45-2-3,3>>^ Mas, tens tu a idéia, ó homem, enquanto julgas os que praticam tais coisas e ainda assim tu mesmo as fazes, de que escaparás do julgamento de Deus?

[[v45-2-4]]

^<<v45-2-4,4>>^ Ou desprezas as riquezas de sua benignidade, e indulgência, e longanimidade, por não saberes que a [qualidade] benévola de Deus está tentando levar-te ao arrependimento?^&#42;1^

[NOTE]
====
. Lit.: “mudança de idéia”.
====

[[v45-2-5]]

^<<v45-2-5,5>>^ Mas, segundo a tua dureza e [teu] coração impenitente, armazenas para ti furor no dia do furor e da revelação do julgamento justo de Deus.

[[v45-2-6]]

^<<v45-2-6,6>>^ E ele dará a cada um segundo as suas obras:

[[v45-2-7]]

^<<v45-2-7,7>>^ vida eterna aos que estão buscando glória, e honra e incorruptibilidade, pela perseverança na obra que é boa;

[[v45-2-8]]

^<<v45-2-8,8>>^ no entanto, para os que são briguentos e que desobedecem à verdade, mas que obedecem à injustiça, haverá furor e ira,

[[v45-2-9]]

^<<v45-2-9,9>>^ tribulação e aflição sobre a alma de cada homem que fizer o que é prejudicial, primeiro do judeu, e também do grego;

[[v45-2-10]]

^<<v45-2-10,10>>^ mas glória, e honra, e paz para todo aquele que fizer o que é bom, primeiro para o judeu, e também para o grego.

[[v45-2-11]]

^<<v45-2-11,11>>^ Pois, com Deus não há parcialidade.

[[v45-2-12]]

^<<v45-2-12,12>>^ Por exemplo, todos os que sem lei pecaram, perecerão também sem lei; mas todos os que pecaram debaixo de lei, serão julgados por lei.

[[v45-2-13]]

^<<v45-2-13,13>>^ Porque não são os ouvintes da lei que são justos diante de Deus, mas os cumpridores da lei é que serão declarados justos.

[[v45-2-14]]

^<<v45-2-14,14>>^ Pois, sempre que pessoas das nações, que não têm lei, fazem por natureza as coisas da lei, tais pessoas, embora não tenham lei, são uma lei para si mesmas.

[[v45-2-15]]

^<<v45-2-15,15>>^ Elas é que são quem demonstra que a matéria da lei está escrita nos seus corações, ao passo que a sua consciência lhes dá testemunho e nos seus próprios pensamentos são acusadas ou até mesmo desculpadas.

[[v45-2-16]]

^<<v45-2-16,16>>^ Isto se dará no dia em que Deus, por intermédio de Cristo Jesus, julgar as coisas secretas da humanidade, segundo as boas novas que eu declaro.

[[v45-2-17]]

^<<v45-2-17,17>>^ Se, porém, tu és judeu de nome e descansas na lei, e te orgulhas de Deus,

[[v45-2-18]]

^<<v45-2-18,18>>^ e conheces a sua vontade e aprovas as coisas ótimas,^&#42;1^ sendo oralmente instruído pela Lei;

[NOTE]
====
. Ou “e testas as coisas que diferem”.
====

[[v45-2-19]]

^<<v45-2-19,19>>^ e estás persuadido de que és guia de cegos, uma luz para os na escuridão,

[[v45-2-20]]

^<<v45-2-20,20>>^ um que corrige os desarrazoados, instrutor de pequeninos, e tendo a estrutura^&#42;1^ do conhecimento e da verdade na Lei —

[NOTE]
====
. Lit.: “forma”. Gr.: mór·fo·sin.
====

[[v45-2-21]]

^<<v45-2-21,21>>^ tu, pois, que ensinas outro, não te ensinas a ti mesmo? Tu, que pregas: “Não furtes”, furtas?

[[v45-2-22]]

^<<v45-2-22,22>>^ Tu, que dizes: “Não cometas adultério”,^&#42;1^ cometes adultério? Tu, que expressas [a tua] abominação dos ídolos, roubas templos?

[NOTE]
====
. Veja 13:9 n.
====

[[v45-2-23]]

^<<v45-2-23,23>>^ Tu, que te orgulhas da lei, desonras a Deus pela tua transgressão da Lei?

[[v45-2-24]]

^<<v45-2-24,24>>^ Pois “o nome de Deus está sendo blasfemado entre as nações por causa de vós”; assim como está escrito.

[[v45-2-25]]

^<<v45-2-25,25>>^ A circuncisão, de fato, só é de proveito se praticares [a] lei; mas, se fores transgressor da lei, a tua circuncisão se tornou incircuncisão.

[[v45-2-26]]

^<<v45-2-26,26>>^ Portanto, se um incircunciso guardar as exigências justas da Lei, não será a sua incircuncisão considerada como circuncisão?

[[v45-2-27]]

^<<v45-2-27,27>>^ E o incircunciso, que é tal por natureza, executando a Lei, julgará a ti que, apesar do seu código escrito e da circuncisão, és transgressor da lei.

[[v45-2-28]]

^<<v45-2-28,28>>^ Porque não é judeu aquele que o é por fora, nem é circuncisão aquela que a é por fora, na carne.

[[v45-2-29]]

^<<v45-2-29,29>>^ Mas judeu é aquele que o é no íntimo, e a [sua] circuncisão é a do coração, por espírito, e não por um código escrito. O louvor desse não vem de homens, mas de Deus.

'''

xref:045-romanos/045-romanos-001.adoc#v45-1-0[&#60; Capítulo Anterior] | <<v45-2-0,Topo>> | xref:045-romanos/045-romanos-003.adoc#v45-3-0[Próximo Capítulo &#62;]