include::./index.adoc[]

[[v45-7-0]]
=== Romanos, 7
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v45-7-1]]

^<<v45-7-1,1>>^ Será que não sabeis, irmãos, (pois estou falando aos que conhecem lei,) que a Lei domina sobre o homem enquanto ele vive?

[[v45-7-2]]

^<<v45-7-2,2>>^ Por exemplo, a mulher casada^&#42;1^ está amarrada por lei ao seu marido enquanto ele viver; mas, se o seu marido morrer, ela está exonerada da lei de seu marido.

[NOTE]
====
. Ou “mulher sujeita a um marido”.
====

[[v45-7-3]]

^<<v45-7-3,3>>^ Assim, pois, enquanto o seu marido viver, ela seria denominada adúltera^&#42;1^ caso se tornasse de outro homem. Mas, se o seu marido morrer, ela está livre da lei dele, de modo que não é adúltera caso se tornar de outro homem.

[NOTE]
====
. “Adúltera.” Lat.: a·dúl·te·ra.
====

[[v45-7-4]]

^<<v45-7-4,4>>^ Assim, meus irmãos, vós também fostes mortos para com a Lei, por intermédio do corpo do Cristo, para que vos tornásseis de outro, daquele que foi levantado dentre os mortos, a fim de que déssemos fruto para Deus.

[[v45-7-5]]

^<<v45-7-5,5>>^ Pois, quando estávamos de acordo com a carne, as paixões pecaminosas, incitadas pela Lei, trabalhavam em nossos membros para que produzíssemos fruto para a morte.

[[v45-7-6]]

^<<v45-7-6,6>>^ Mas agora fomos exonerados da Lei, porque morremos para com aquilo que nos segurava, para que fôssemos escravos^&#42;1^ num novo sentido, pelo espírito, e não no velho sentido, pelo código escrito.

[NOTE]
====
. “Fôssemos escravos”, אAB; J18: “fôssemos servos de Jeová”.
====

[[v45-7-7]]

^<<v45-7-7,7>>^ O que diremos, então? É a Lei pecado? Que nunca se torne tal! Realmente, eu não teria chegado a conhecer o pecado, se não fosse a Lei; e, por exemplo, eu não teria conhecido a cobiça, se a Lei não dissesse: “Não deves cobiçar.”

[[v45-7-8]]

^<<v45-7-8,8>>^ Mas o pecado, recebendo induzimento por intermédio do mandamento, produziu em mim cobiça de toda sorte, pois, à parte da lei, o pecado estava morto.

[[v45-7-9]]

^<<v45-7-9,9>>^ De fato, eu estava uma vez vivo à parte da lei; mas, ao chegar o mandamento, o pecado passou a viver novamente, mas eu morri.

[[v45-7-10]]

^<<v45-7-10,10>>^ E o mandamento que era para a vida, este eu achei ser para a morte.

[[v45-7-11]]

^<<v45-7-11,11>>^ Pois o pecado, recebendo induzimento por intermédio do mandamento, seduziu-me e matou-me por intermédio dele.

[[v45-7-12]]

^<<v45-7-12,12>>^ Por conseguinte, a Lei, da sua parte, é santa, e o mandamento é santo, e justo, e bom.

[[v45-7-13]]

^<<v45-7-13,13>>^ Acaso o bom se tornou morte para mim? Que isso nunca aconteça! Mas o pecado sim, para que se mostrasse como pecado, produzindo para mim a morte por intermédio daquilo que é bom; para que o pecado se tornasse muito mais pecaminoso por intermédio do mandamento.

[[v45-7-14]]

^<<v45-7-14,14>>^ Pois sabemos que a Lei é espiritual; mas eu sou carnal, vendido sob o pecado.

[[v45-7-15]]

^<<v45-7-15,15>>^ Pois não sei o que estou produzindo. Porque aquilo que quero,^&#42;1^ isso não pratico; mas aquilo que odeio é o que faço.

[NOTE]
====
. Ou “tenciono [fazer]”.
====

[[v45-7-16]]

^<<v45-7-16,16>>^ No entanto, se aquilo que não quero é o que faço, estou concordando que a Lei é excelente.

[[v45-7-17]]

^<<v45-7-17,17>>^ Mas então, quem o produz não sou mais eu, mas o pecado que reside em mim.

[[v45-7-18]]

^<<v45-7-18,18>>^ Pois eu sei que em mim, isto é, na minha carne, não mora nada bom; porque a capacidade de querer está presente em mim, mas a capacidade de produzir o que é excelente não está [presente].

[[v45-7-19]]

^<<v45-7-19,19>>^ Pois o bem que quero, não faço, mas o mal que não quero, este é o que pratico.

[[v45-7-20]]

^<<v45-7-20,20>>^ Se aquilo que não quero é o que faço, então, quem o produz não sou mais eu, mas o pecado que mora em mim.

[[v45-7-21]]

^<<v45-7-21,21>>^ Acho assim a seguinte lei no meu caso: que, quando quero fazer o que é direito, está presente em mim aquilo que é mau.

[[v45-7-22]]

^<<v45-7-22,22>>^ Eu realmente me deleito na lei de Deus segundo o homem que sou no íntimo,

[[v45-7-23]]

^<<v45-7-23,23>>^ mas observo em meus membros outra lei guerreando contra a lei da minha mente e levando-me cativo à lei do pecado que está nos meus membros.

[[v45-7-24]]

^<<v45-7-24,24>>^ Homem miserável^&#42;1^ que eu sou! Quem me resgatará do corpo que é submetido a esta morte?

[NOTE]
====
. Lit.: “caloso; calejado”.
====

[[v45-7-25]]

^<<v45-7-25,25>>^ Graças a Deus, por intermédio de Jesus Cristo, nosso Senhor! Assim, pois, com a mente, eu mesmo sou escravo da lei de Deus, mas com a [minha] carne, [escravo] da lei do pecado.

'''

xref:045-romanos/045-romanos-006.adoc#v45-6-0[&#60; Capítulo Anterior] | <<v45-7-0,Topo>> | xref:045-romanos/045-romanos-008.adoc#v45-8-0[Próximo Capítulo &#62;]