include::./index.adoc[]

[[v52-1-0]]
=== 1 Tessalonicenses, 1
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v52-1-1]]

^<<v52-1-1,1>>^ Paulo, e Silvano,^&#42;1^ e Timóteo, à congregação dos tessalonicenses em união com Deus, o Pai, e [o] Senhor Jesus Cristo:
Que tenhais benignidade imerecida e paz.

[NOTE]
====
. Ou “Silas”.
====

[[v52-1-2]]

^<<v52-1-2,2>>^ Sempre agradecemos a Deus, ao fazermos menção de todos vós nas nossas orações,

[[v52-1-3]]

^<<v52-1-3,3>>^ pois nos lembramos incessantemente da vossa obra fiel,^&#42;1^ e do [vosso] labor amoroso,^&#42;2^ e da [vossa] perseverança devido à [vossa] esperança no nosso Senhor Jesus Cristo, perante nosso Deus e Pai.

[NOTE]
====
. Ou “vossa obra devido à fé”.
. Ou “[vossa] labuta devido ao amor”.
====

[[v52-1-4]]

^<<v52-1-4,4>>^ Pois sabemos da sua escolha de vós, irmãos amados por Deus,

[[v52-1-5]]

^<<v52-1-5,5>>^ porque as boas novas que pregamos não se apresentaram entre vós apenas em palavra, mas também com poder e com espírito santo, e com forte certeza,^&#42;1^ assim como sabeis que sorte de homens nos tornamos para vós por vossa causa;

[NOTE]
====
. Lit.: “plena garantia”.
====

[[v52-1-6]]

^<<v52-1-6,6>>^ e vós vos tornastes imitadores nossos e do Senhor, visto que aceitastes a palavra sob muita tribulação, com alegria de espírito santo,

[[v52-1-7]]

^<<v52-1-7,7>>^ de modo que viestes a ser um exemplo para todos os crentes na Macedônia e na Acaia.^&#42;1^

[NOTE]
====
. A província romana do sul da Grécia, cuja capital era Corinto.
====

[[v52-1-8]]

^<<v52-1-8,8>>^ O fato é que a palavra de Jeová,^&#42;1^ partindo de vós, fez-se ouvir não somente na Macedônia e na Acaia, mas em todo lugar em que se espalhou a vossa fé para com Deus, de modo que não precisamos dizer nada.

[NOTE]
====
. “De Jeová”, J7,8,17,18,22,23; אcB(gr.): tou Ky·rí·ou; א°: “de Deus”. Veja Ap. 1D.
====

[[v52-1-9]]

^<<v52-1-9,9>>^ Pois eles mesmos continuam relatando o modo em que primeiro entramos no meio de vós e como vos voltastes para Deus, [desviando-vos] dos [vossos] ídolos, a fim de trabalhar como escravos para um Deus vivente e verdadeiro,

[[v52-1-10]]

^<<v52-1-10,10>>^ e para aguardar o seu Filho vindo dos céus, a quem ele levantou dentre os mortos, a saber, Jesus, quem nos livra do vindouro furor.

'''

xref:051-colossenses/051-colossenses-004.adoc#v51-4-0[&#60; Capítulo Anterior] | <<v52-1-0,Topo>> | xref:052-1-tessalonicenses/052-1-tessalonicenses-002.adoc#v52-2-0[Próximo Capítulo &#62;]