include::./index.adoc[]

[[v52-5-0]]
=== 1 Tessalonicenses, 5
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v52-5-1]]

^<<v52-5-1,1>>^ Ora, quanto aos tempos e às épocas,^&#42;1^ irmãos, não necessitais de que se vos escreva.

[NOTE]
====
. Ou “aos tempos designados”. Gr.: kai·rón.
====

[[v52-5-2]]

^<<v52-5-2,2>>^ Pois vós mesmos sabeis muito bem que o dia de Jeová^&#42;1^ vem exatamente como ladrão, de noite.

[NOTE]
====
. Veja Ap. 1D.
====

[[v52-5-3]]

^<<v52-5-3,3>>^ Quando estiverem dizendo: “Paz e segurança!” então lhes há de sobrevir instantaneamente a repentina destruição, assim como as dores de aflição [vêm] sobre a mulher grávida, e de modo algum escaparão.

[[v52-5-4]]

^<<v52-5-4,4>>^ Mas vós, irmãos, não estais em escuridão, de modo que aquele dia vos sobrevenha assim como a ladrões,^&#42;1^

[NOTE]
====
. “Vos sobrevenha assim como a ladrões”, AB; אDItVgSyh,pArm: “vos sobrevenha como ladrão”.
====

[[v52-5-5]]

^<<v52-5-5,5>>^ porque todos vós sois filhos da luz e filhos do dia. Não pertencemos nem à noite nem à escuridão.

[[v52-5-6]]

^<<v52-5-6,6>>^ Assim, pois, não estejamos dormindo assim como fazem os demais, mas fiquemos despertos e mantenhamos os nossos sentidos.^&#42;1^

[NOTE]
====
. Lit.: “e fiquemos sóbrios”.
====

[[v52-5-7]]

^<<v52-5-7,7>>^ Pois, os que dormem estão acostumados a dormir de noite, e os que ficam embriagados usualmente estão embriagados de noite.

[[v52-5-8]]

^<<v52-5-8,8>>^ Mas, quanto a nós, os que pertencemos ao dia, mantenhamos os nossos sentidos, estando vestidos da couraça da fé e do amor, e [tendo] por capacete a esperança da salvação;

[[v52-5-9]]

^<<v52-5-9,9>>^ porque Deus não nos designou ao furor, mas à adquisição de salvação por intermédio de nosso Senhor Jesus Cristo.^&#42;1^

[NOTE]
====
. “Cristo”, אAVgSyp; B o omite.
====

[[v52-5-10]]

^<<v52-5-10,10>>^ Ele morreu por nós, para que, quer fiquemos despertos quer estejamos dormindo, vivamos junto com ele.

[[v52-5-11]]

^<<v52-5-11,11>>^ Portanto, persisti em consolar-vos uns aos outros e em edificar-vos uns aos outros, assim como de fato estais fazendo.

[[v52-5-12]]

^<<v52-5-12,12>>^ Solicitamo-vos agora, irmãos, que tenhais consideração para com os que trabalham arduamente entre vós e que presidem sobre^&#42;1^ vós no Senhor, e que vos admoestam;

[NOTE]
====
. Ou “dirigem a; tomam a dianteira entre”. Lit.: “postados diante”. Gr.: pro·i·sta·mé·nous.
====

[[v52-5-13]]

^<<v52-5-13,13>>^ e que lhes deis mais do que extraordinária consideração em amor, por causa do seu trabalho. Sede pacíficos uns com os outros.

[[v52-5-14]]

^<<v52-5-14,14>>^ Por outro lado, exortamo-vos, irmãos: admoestai os desordeiros, falai consoladoramente às almas deprimidas, amparai os fracos, sede longânimes para com todos.

[[v52-5-15]]

^<<v52-5-15,15>>^ Vede que ninguém pague a outro dano por dano, mas, empenhai-vos sempre pelo que é bom de uns para com os outros e para com todos os demais.

[[v52-5-16]]

^<<v52-5-16,16>>^ Estai sempre alegres.

[[v52-5-17]]

^<<v52-5-17,17>>^ Orai incessantemente.

[[v52-5-18]]

^<<v52-5-18,18>>^ Dai graças em conexão com tudo. Pois esta é a vontade de Deus em união com Cristo Jesus com respeito a vós.

[[v52-5-19]]

^<<v52-5-19,19>>^ Não extingais o fogo do espírito.

[[v52-5-20]]

^<<v52-5-20,20>>^ Não trateis com desprezo o profetizar.

[[v52-5-21]]

^<<v52-5-21,21>>^ Certificai-vos^&#42;1^ de todas as coisas; apegai-vos ao que é excelente.

[NOTE]
====
. Lit.: “Estai provando.”
====

[[v52-5-22]]

^<<v52-5-22,22>>^ Abstende-vos de toda forma de iniqüidade.

[[v52-5-23]]

^<<v52-5-23,23>>^ O próprio Deus de paz vos santifique completamente. Que em todo respeito sejam preservados sãos o espírito, e a alma, e o corpo de vós [irmãos], dum modo inculpe, na presença^&#42;1^ de nosso Senhor Jesus Cristo.

[NOTE]
====
. Veja Ap. 5B.
====

[[v52-5-24]]

^<<v52-5-24,24>>^ Aquele que vos chama é fiel, e ele também o fará.

[[v52-5-25]]

^<<v52-5-25,25>>^ Irmãos, continuai a orar por nós.

[[v52-5-26]]

^<<v52-5-26,26>>^ Cumprimentai todos os irmãos com beijo santo.

[[v52-5-27]]

^<<v52-5-27,27>>^ Eu vos ponho sob a solene obrigação, da parte do Senhor,^&#42;1^ de que esta carta seja lida a todos os irmãos.

[NOTE]
====
. “Do Senhor”, אABVg; J7,8,13,14,16: “Jeová”.
====

[[v52-5-28]]

^<<v52-5-28,28>>^ A benignidade imerecida de nosso Senhor Jesus Cristo seja convosco.^&#42;1^

[NOTE]
====
. אADcItVgSyh,p terminam com “Amém”; BD°SyhiArm omitem isso.
====

'''

xref:052-1-tessalonicenses/052-1-tessalonicenses-004.adoc#v52-4-0[&#60; Capítulo Anterior] | <<v52-5-0,Topo>> | xref:053-2-tessalonicenses/053-2-tessalonicenses-001.adoc#v53-1-0[Próximo Capítulo &#62;]