include::./index.adoc[]

[[v18-30-0]]
=== Jó, 30
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v18-30-1]]

^<<v18-30-1,1>>^ “E agora se riram de mim,
Os que são mais jovens do que eu,
Cujos pais eu teria recusado
Pôr com os cães do meu rebanho.

[[v18-30-2]]

^<<v18-30-2,2>>^ Mesmo o poder das suas mãos — que me adiantou?
Pereceu neles o vigor.

[[v18-30-3]]

^<<v18-30-3,3>>^ Por causa da carência e da fome são estéreis,
Roendo uma região árida
[Onde] ontem havia tempestade e desolação.

[[v18-30-4]]

^<<v18-30-4,4>>^ Arrancavam a erva salgada junto aos arbustos
E a raiz das giestas-das-vassouras era seu alimento.

[[v18-30-5]]

^<<v18-30-5,5>>^ Estavam sendo expulsos da comunidade;
Gritava-se contra eles como contra um ladrão.

[[v18-30-6]]

^<<v18-30-6,6>>^ [Têm de] residir na própria encosta dos vales de torrente,
Em buracos de pó e nas penhas.

[[v18-30-7]]

^<<v18-30-7,7>>^ Bramavam entre os arbustos;
Conchegavam-se debaixo das urtigas.

[[v18-30-8]]

^<<v18-30-8,8>>^ Filhos do insensato, também filhos daquele que não tem nome,
Foram enxotados da terra a chicotadas.

[[v18-30-9]]

^<<v18-30-9,9>>^ E agora eu me tornei até mesmo o assunto da sua canção,
E sou para eles um rifão.

[[v18-30-10]]

^<<v18-30-10,10>>^ Detestaram-me, mantiveram-se longe de mim;
E não se refrearam de cuspir-me na face.

[[v18-30-11]]

^<<v18-30-11,11>>^ Pois ele soltou [minha] própria corda de arco e passou a humilhar-me,
E por minha causa deixaram solto o freio.

[[v18-30-12]]

^<<v18-30-12,12>>^ Levantam-se à minha direita como uma laia;
Soltaram os meus pés,
Mas passaram a aterrar contra mim as suas desastrosas barreiras.

[[v18-30-13]]

^<<v18-30-13,13>>^ Desfizeram as minhas sendas;
Só foram de proveito para aquilo que me é adverso,
Sem que tivessem ajudador.

[[v18-30-14]]

^<<v18-30-14,14>>^ Passaram a vir como que por uma larga brecha;
Rolaram adiante sob uma tempestade.

[[v18-30-15]]

^<<v18-30-15,15>>^ Terrores repentinos foram voltados contra mim;
Meu porte nobre é perseguido como pelo vento,^&#42;1^
E como uma nuvem passou a minha salvação.

[NOTE]
====
. “Como pelo vento.” Hebr.: ka·rú·ahh. Veja Gên 1:2 n.: “ativa”.
====

[[v18-30-16]]

^<<v18-30-16,16>>^ E agora se derramou a minha alma dentro de mim;
Apoderam-se de mim dias de tribulação.

[[v18-30-17]]

^<<v18-30-17,17>>^ À noite, os próprios ossos meus foram furados [e caíram] de mim,
E [as dores] que me estão roendo não folgam.

[[v18-30-18]]

^<<v18-30-18,18>>^ Minha vestimenta muda pela abundância de poder;
Cinge-me como a gola da minha veste comprida.

[[v18-30-19]]

^<<v18-30-19,19>>^ Ele me fez descer ao barro,
De modo que mostro ser semelhante a pó e cinzas.

[[v18-30-20]]

^<<v18-30-20,20>>^ Clamo a ti por ajuda, mas não me respondes;
Fiquei de pé, para que atentasses em mim.

[[v18-30-21]]

^<<v18-30-21,21>>^ Transformas-te para ficar cruel comigo;
Com a plena força da tua mão me tens rancor.

[[v18-30-22]]

^<<v18-30-22,22>>^ Levantas-me ao vento, fazes-me cavalgá-lo;
Depois me dissolves com um estrondo.

[[v18-30-23]]

^<<v18-30-23,23>>^ Pois sei muito bem que me farás recuar à morte
E à casa de reunião para todo o vivente.

[[v18-30-24]]

^<<v18-30-24,24>>^ Somente que ninguém estende a sua mão contra um mero monte de escombros,
Nem se faz durante a decadência um clamor por ajuda a respeito de tais coisas.

[[v18-30-25]]

^<<v18-30-25,25>>^ Eu certamente chorei por aquele que teve um dia árduo;
Minha alma se penalizou pelo pobre.

[[v18-30-26]]

^<<v18-30-26,26>>^ Embora eu aguardasse o bem, chegou o mal;
E eu esperava a luz, mas chegaram as trevas.

[[v18-30-27]]

^<<v18-30-27,27>>^ Meus próprios intestinos foram postos a ferver e não ficaram quietos;
Confrontaram-me dias de tribulação.

[[v18-30-28]]

^<<v18-30-28,28>>^ Andei em volta triste quando não havia luz do sol;^&#42;1^
Levantei-me na congregação,^&#42;2^ continuei a clamar por ajuda.

[NOTE]
====
. “Luz do sol”, M; mediante uma correção: “consolo”.
. “Na congregação.” Hebr.: vaq·qa·hál; gr.: ek·kle·sí·ai.
====

[[v18-30-29]]

^<<v18-30-29,29>>^ Tornei-me irmão de chacais
E companheiro das filhas de avestruzes.

[[v18-30-30]]

^<<v18-30-30,30>>^ Minha própria pele ficou preta [e caiu] de mim,
E meus próprios ossos ficaram candentes por causa da sequidão.

[[v18-30-31]]

^<<v18-30-31,31>>^ E minha harpa ficou apenas para o pranto,
E meu pífaro, para a voz dos que choram.

'''

xref:018-jo/018-jo-029.adoc#v18-29-0[&#60; Capítulo Anterior] | <<v18-30-0,Topo>> | xref:018-jo/018-jo-031.adoc#v18-31-0[Próximo Capítulo &#62;]