include::./index.adoc[]

[[v18-31-0]]
=== Jó, 31
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v18-31-1]]

^<<v18-31-1,1>>^ “Concluí um pacto com os meus olhos.
Portanto, como poderia mostrar-me atento a uma virgem?

[[v18-31-2]]

^<<v18-31-2,2>>^ E que porção há da parte do Deus^&#42;1^ de cima,
Ou que herança da parte do Todo-poderoso desde o alto?

[NOTE]
====
. “Deus.” Hebr.: ’Elóh·ah; gr.: ho The·ós.
====

[[v18-31-3]]

^<<v18-31-3,3>>^ Não há desastre para um contraventor
E infortúnio para os que praticam o que é prejudicial?

[[v18-31-4]]

^<<v18-31-4,4>>^ Acaso não vê ele os meus caminhos
E conta até mesmo todos os meus passos?

[[v18-31-5]]

^<<v18-31-5,5>>^ Se eu tiver andado com [homens de] inveracidade,
E meu pé se apressar para o engano,

[[v18-31-6]]

^<<v18-31-6,6>>^ Ele me pesará em balança exata,^&#42;1^
E Deus^&#42;2^ chegará a saber a minha integridade.

[NOTE]
====
. Lit.: “em balança de justiça”.
. “Deus.” Hebr.: ’Elóh·ah; LXX: “Jeová”.
====

[[v18-31-7]]

^<<v18-31-7,7>>^ Se os meus passos se apartarem do caminho,
Ou meu coração apenas tiver andado atrás dos meus olhos,
Ou qualquer defeito se tiver apegado às palmas das minhas próprias mãos,

[[v18-31-8]]

^<<v18-31-8,8>>^ Lance eu semente e coma outro,
E sejam desarraigados os meus próprios descendentes.

[[v18-31-9]]

^<<v18-31-9,9>>^ Se meu coração tiver sido engodado referente a uma mulher
E tiver ficado de emboscada à própria entrada do meu companheiro,

[[v18-31-10]]

^<<v18-31-10,10>>^ Moa a minha esposa para outro homem,
E ajoelhe-se sobre ela outro homem.

[[v18-31-11]]

^<<v18-31-11,11>>^ Pois isso seria conduta desenfreada
E esta seria um erro, para [receber a atenção dos] magistrados.

[[v18-31-12]]

^<<v18-31-12,12>>^ Pois é um fogo que consumiria até à destruição,^&#42;1^
E se arraigaria entre todos os meus produtos.

[NOTE]
====
. “Destruição.” Hebr.: ’avad·dóhn. Veja 26:6 n.
====

[[v18-31-13]]

^<<v18-31-13,13>>^ Se eu costumava recusar o julgamento do meu escravo
Ou da minha escrava na sua causa comigo,

[[v18-31-14]]

^<<v18-31-14,14>>^ Então o que posso fazer quando Deus^&#42;1^ se levanta?
E quando demanda uma prestação de contas, que lhe posso responder?

[NOTE]
====
. “Deus.” Hebr.: ’El.
====

[[v18-31-15]]

^<<v18-31-15,15>>^ Não foi ele feito por Aquele que me fez no ventre
E não foi apenas Um que passou a preparar-nos na madre?

[[v18-31-16]]

^<<v18-31-16,16>>^ Se eu costumava negar aos de condição humilde o [seu] agrado
E fiz fraquejar os olhos da viúva,

[[v18-31-17]]

^<<v18-31-17,17>>^ E costumava comer meu bocado sozinho,
Não comendo dele o menino órfão de pai;

[[v18-31-18]]

^<<v18-31-18,18>>^ (Pois desde a minha mocidade cresceu comigo como que com um pai,
E desde o ventre de minha mãe eu a guiava;)

[[v18-31-19]]

^<<v18-31-19,19>>^ Se eu costumava ver alguém perecer por não ter vestimenta
Ou que o pobre não tinha cobertura;

[[v18-31-20]]

^<<v18-31-20,20>>^ Se os seus lombos não me abençoaram,
Nem ele se aquecia com a lã tosquiada dos meus carneirinhos;

[[v18-31-21]]

^<<v18-31-21,21>>^ Se sacudi a mão para lá e para cá contra o menino órfão de pai,
Quando via [a necessidade do] meu auxílio no portão,

[[v18-31-22]]

^<<v18-31-22,22>>^ Que caia a minha própria omoplata do seu ombro
E se quebre o meu próprio braço desde o seu osso superior.

[[v18-31-23]]

^<<v18-31-23,23>>^ Porque o desastre da parte de Deus^&#42;1^ era para mim um pavor,
E contra a sua dignidade eu nada podia.

[NOTE]
====
. “Deus.” Hebr.: ’El; gr.: Ky·rí·ou, “Jeová”.
====

[[v18-31-24]]

^<<v18-31-24,24>>^ Se pus no ouro^&#42;1^ a minha confiança
Ou disse ao ouro:^&#42;2^ ‘Em ti confio!’

[NOTE]
====
. “Ouro.” Hebr.: za·háv.
. “Ou . . . ao ouro.” Hebr.: welak·ké·them. Veja 28:16 n.
====

[[v18-31-25]]

^<<v18-31-25,25>>^ Se eu costumava alegrar-me por ter muita propriedade
E porque a minha mão tinha achado muitas coisas;

[[v18-31-26]]

^<<v18-31-26,26>>^ Se eu costumava ver a luz quando ela brilhava
Ou a preciosa lua andando,

[[v18-31-27]]

^<<v18-31-27,27>>^ E meu coração começou a ser engodado às escondidas,
E minha mão passou a beijar a minha boca,^&#42;1^

[NOTE]
====
. Pelo visto, é uma alusão a se lançar um beijo com a mão, numa prática idólatra. Beijar ídolos é mencionado em 1Rs 19:18; Os 13:2.
====

[[v18-31-28]]

^<<v18-31-28,28>>^ Isto também seria um erro a [receber a atenção dos] magistrados,
Pois eu teria renegado o [verdadeiro] Deus de cima.

[[v18-31-29]]

^<<v18-31-29,29>>^ Se eu costumava alegrar-me com a extinção daquele que me odiava intensamente,
Ou se fiquei agitado^&#42;1^ porque o atingiu o mal —

[NOTE]
====
. “Fiquei agitado”, M; T: “fiz um barulho alegre”.
====

[[v18-31-30]]

^<<v18-31-30,30>>^ E não permiti que o meu palato pecasse,
Pedindo uma imprecação contra a sua alma.

[[v18-31-31]]

^<<v18-31-31,31>>^ Se os homens da minha tenda não disseram:
‘Quem pode apresentar alguém que não se saciasse da sua comida?’^&#42;1^—

[NOTE]
====
. Lit.: “carne”.
====

[[v18-31-32]]

^<<v18-31-32,32>>^ Nenhum residente forasteiro passava a noite lá fora;
Mantive as minhas portas abertas para a vereda.^&#42;1^

[NOTE]
====
. “Vereda”, M; TLXXSyVg: “viajante”.
====

[[v18-31-33]]

^<<v18-31-33,33>>^ Se encobri as minhas transgressões como um homem terreno,^&#42;1^
Escondendo meu erro no bolso da minha camisa —

[NOTE]
====
. “Como um homem terreno (Adão; homem).” Hebr.: khe’a·dhám, possivelmente: “de homem; entre homens”.
====

[[v18-31-34]]

^<<v18-31-34,34>>^ Porque eu me assustava diante duma grande massa de gente,
Ou me aterrorizava o próprio desprezo das famílias,
E eu ficava quieto, não saía da entrada.

[[v18-31-35]]

^<<v18-31-35,35>>^ Quem me dera que eu tivesse alguém para escutar-me,
Que o próprio Todo-poderoso me respondesse segundo a minha assinatura!^&#42;1^
Ou que a pessoa^&#42;2^ em litígio comigo tivesse escrito um documento!

[NOTE]
====
. Lit.: “sinal”, evidentemente por escrito, confirmando um documento legal.
. Lit.: “homem”. Hebr.: ’ish.
====

[[v18-31-36]]

^<<v18-31-36,36>>^ Por certo o carregaria sobre o meu ombro;
Eu o enrolaria em volta de mim como a uma grandiosa coroa.

[[v18-31-37]]

^<<v18-31-37,37>>^ Comunicar-lhe-ia o número dos meus passos;
Como líder me chegaria a ele.

[[v18-31-38]]

^<<v18-31-38,38>>^ Se o meu próprio solo clamasse contra mim por socorro
E seus próprios sulcos chorassem juntos;

[[v18-31-39]]

^<<v18-31-39,39>>^ Se comi os seus frutos^&#42;1^ sem dinheiro
E fiz ofegar a alma dos seus donos,

[NOTE]
====
. Lit.: “seu poder”. Hebr.: ko·hháh.
====

[[v18-31-40]]

^<<v18-31-40,40>>^ Produza-se planta espinhosa em vez de trigo,
E erva malcheirosa em vez de cevada.”
As palavras de Jó chegaram ao fim.

'''

xref:018-jo/018-jo-030.adoc#v18-30-0[&#60; Capítulo Anterior] | <<v18-31-0,Topo>> | xref:018-jo/018-jo-032.adoc#v18-32-0[Próximo Capítulo &#62;]