include::./index.adoc[]

[[v18-27-0]]
=== Jó, 27
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v18-27-1]]

^<<v18-27-1,1>>^ E Jó passou a encetar novamente seu dito proverbial e prosseguiu, dizendo:

[[v18-27-2]]

^<<v18-27-2,2>>^ “Assim como vive Deus,^&#42;1^ que tirou de mim o julgamento,
E assim como [vive] o Todo-poderoso, que amargurou a minha alma,

[NOTE]
====
. “Deus.” Em hebr.: ’El.
====

[[v18-27-3]]

^<<v18-27-3,3>>^ Enquanto estiver ainda em mim todo o meu fôlego,
E o espírito de Deus^&#42;1^ estiver em minhas narinas,

[NOTE]
====
. “Deus.” Hebr.: ’Elóh·ah.
====

[[v18-27-4]]

^<<v18-27-4,4>>^ Meus lábios não falarão injustiça
E minha própria língua não murmurará dolo!

[[v18-27-5]]

^<<v18-27-5,5>>^ É inconcebível da minha parte declarar-vos justos!
Até eu expirar não removerei de mim a minha integridade!

[[v18-27-6]]

^<<v18-27-6,6>>^ Agarrei a minha justeza e não a largarei;
Meu coração não escarnecerá [de mim] por qualquer dos meus dias.

[[v18-27-7]]

^<<v18-27-7,7>>^ Torne-se meu inimigo de todo modo um homem iníquo,
E o que se revolta contra mim, realmente um contraventor.

[[v18-27-8]]

^<<v18-27-8,8>>^ Pois qual é a esperança dum apóstata caso ele der cabo [dele],
Caso Deus^&#42;1^ lhe tire a sua alma?

[NOTE]
====
. “Deus.” Hebr.: ’Elóh·ah.
====

[[v18-27-9]]

^<<v18-27-9,9>>^ Ouvirá Deus^&#42;1^ seu clamor
Caso venha sobre ele a aflição?

[NOTE]
====
. “Deus.” Hebr.: ’El.
====

[[v18-27-10]]

^<<v18-27-10,10>>^ Ou deleitar-se-á no Todo-poderoso?
Clamará a Deus todo o tempo?

[[v18-27-11]]

^<<v18-27-11,11>>^ Eu vos instruirei pela mão de Deus;
Não ocultarei aquilo que está com o Todo-poderoso.

[[v18-27-12]]

^<<v18-27-12,12>>^ Eis que vós mesmos, todos, tivestes visões;
Então por que vos mostrais inteiramente vãos?

[[v18-27-13]]

^<<v18-27-13,13>>^ Este é o quinhão do homem^&#42;1^ iníquo, da parte de Deus;
E a herança dos tiranos, eles receberão do próprio Todo-poderoso.

[NOTE]
====
. Ou “homem terreno”. Hebr.: ’a·dhám.
====

[[v18-27-14]]

^<<v18-27-14,14>>^ Se os seus filhos se tornarem muitos, será para a espada;
E seus próprios descendentes não terão bastante alimento.^&#42;1^

[NOTE]
====
. Ou “pão”.
====

[[v18-27-15]]

^<<v18-27-15,15>>^ Seus próprios sobreviventes serão enterrados durante uma praga mortífera,^&#42;1^
E as próprias viúvas deles não chorarão.

[NOTE]
====
. Lit.: “morte”.
====

[[v18-27-16]]

^<<v18-27-16,16>>^ Se ele amontoasse prata como o próprio pó
E preparasse vestuário como se fosse barro,

[[v18-27-17]]

^<<v18-27-17,17>>^ Ele prepararia, mas o justo seria quem se vestiria,
E o inocente partilharia na prata.

[[v18-27-18]]

^<<v18-27-18,18>>^ Construiu a sua casa como alguma traça,
E como a guarita construída pela sentinela.

[[v18-27-19]]

^<<v18-27-19,19>>^ Deitar-se-á rico, mas nada será ajuntado;^&#42;1^
Abre os olhos, mas não há nada.

[NOTE]
====
. Ou “ele não será ajuntado”, M; LXXSy: “ele nada acrescentará”.
====

[[v18-27-20]]

^<<v18-27-20,20>>^ Quais águas^&#42;1^ o alcançarão terrores repentinos;
Durante a noite o furtará um tufão.

[NOTE]
====
. “Quais águas.” Ou: “Durante o dia”, mediante uma correção.
====

[[v18-27-21]]

^<<v18-27-21,21>>^ Um vento oriental carregará com ele e ele se irá,
E de roldão o levará do seu lugar.

[[v18-27-22]]

^<<v18-27-22,22>>^ E lançar-se-á sobre ele e não terá compaixão;
E ele, sem falta, tentará fugir do seu poder.

[[v18-27-23]]

^<<v18-27-23,23>>^ Bater-se-ão palmas contra ele
E assobiar-se-á contra ele do seu lugar.^&#42;1^

[NOTE]
====
. Ou “[alguém passando] pelo seu lugar assobiará contra este”.
====

'''

xref:018-jo/018-jo-026.adoc#v18-26-0[&#60; Capítulo Anterior] | <<v18-27-0,Topo>> | xref:018-jo/018-jo-028.adoc#v18-28-0[Próximo Capítulo &#62;]