include::./index.adoc[]

[[v18-24-0]]
=== Jó, 24
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v18-24-1]]

^<<v18-24-1,1>>^ “Por que é que os tempos não foram guardados pelo próprio Todo-poderoso,
E os próprios que o conhecem não observaram os seus dias?

[[v18-24-2]]

^<<v18-24-2,2>>^ Há os que recuam os marcos divisórios;
Arrebataram uma grei, a fim de [a] apascentarem.^&#42;1^

[NOTE]
====
. “Junto com seu pastor”, LXX.
====

[[v18-24-3]]

^<<v18-24-3,3>>^ Levam até mesmo o jumento dum menino órfão de pai;
Tomam em penhor o touro da viúva.

[[v18-24-4]]

^<<v18-24-4,4>>^ Apartam os pobres do seu caminho;
Ao mesmo tempo, os atribulados da terra se mantiveram escondidos.

[[v18-24-5]]

^<<v18-24-5,5>>^ Eis que, [quais] zebras no ermo,
Saíram na sua atividade à procura de algo para comer.
A planície desértica [dá] a cada um pão para os rapazes.

[[v18-24-6]]

^<<v18-24-6,6>>^ No campo ceifam a sua forragem,
E despojam rapidamente o vinhedo do iníquo.

[[v18-24-7]]

^<<v18-24-7,7>>^ Passam a noite nus, sem vestimenta,
E sem qualquer cobertura no frio.

[[v18-24-8]]

^<<v18-24-8,8>>^ São ensopados pelo temporal dos montes,
E por não haver abrigo, precisam abraçar uma rocha.

[[v18-24-9]]

^<<v18-24-9,9>>^ Arrebatam o menino órfão de pai mesmo do peito,
E tomam em penhor o que há sobre o atribulado.

[[v18-24-10]]

^<<v18-24-10,10>>^ Têm de andar nus, sem vestimenta,
E famintos têm de carregar as espigas ceifadas.

[[v18-24-11]]

^<<v18-24-11,11>>^ Passam o meio-dia^&#42;1^ entre os muros do terraço;
Precisam pisar os lagares, e ainda assim passam sede.

[NOTE]
====
. Ou “extraem azeite”.
====

[[v18-24-12]]

^<<v18-24-12,12>>^ De dentro da cidade estão gemendo os moribundos,
E a alma dos mortalmente feridos clama por ajuda;
E o próprio Deus^&#42;1^ não considera [isso] algo impróprio.

[NOTE]
====
. “E . . . Deus.” Hebr.: we·’Elóh·ah.
====

[[v18-24-13]]

^<<v18-24-13,13>>^ Quanto a eles, mostraram estar entre os rebeldes contra a luz;
Não reconheceram os caminhos dela,
Nem moraram nas suas sendas.

[[v18-24-14]]

^<<v18-24-14,14>>^ O assassino levanta-se ao clarear o dia,
Passa a matar o atribulado e o pobre;
E durante a noite torna-se um verdadeiro ladrão.^&#42;1^

[NOTE]
====
. Ou “ele vai como arrombador”.
====

[[v18-24-15]]

^<<v18-24-15,15>>^ Quanto ao olho do adúltero, ficou à espreita do crepúsculo vespertino,
Dizendo: ‘Nenhum olho me avistará!’
E põe uma cobertura sobre a sua face.

[[v18-24-16]]

^<<v18-24-16,16>>^ Na escuridão penetra cavando nas casas;
De dia precisam manter-se encerrados.
Não conheceram a luz do dia.

[[v18-24-17]]

^<<v18-24-17,17>>^ Pois a manhã é para eles igual à sombra tenebrosa,
Porque reconhecem quais são os terrores repentinos da sombra tenebrosa.

[[v18-24-18]]

^<<v18-24-18,18>>^ Ele é ligeiro na superfície das águas.
O lote de terreno deles será amaldiçoado na terra.
Ele não se virará para o caminho dos vinhedos.

[[v18-24-19]]

^<<v18-24-19,19>>^ A seca, bem como o calor, arrebatam as águas da neve;
Assim faz também o Seol com os que pecaram!

[[v18-24-20]]

^<<v18-24-20,20>>^ A madre se esquecerá dele, o gusano saboreará a sua doçura,
Não mais será lembrado.
E a injustiça será destroçada como uma árvore.

[[v18-24-21]]

^<<v18-24-21,21>>^ Ele tem tratos com uma mulher estéril que não dá à luz,
E com uma viúva, a quem não faz bem.

[[v18-24-22]]

^<<v18-24-22,22>>^ E certamente arrastará gente possante com o seu poder;
Ele se levantará e não estará seguro da sua vida.^&#42;1^

[NOTE]
====
. “Sua vida”, LXXVg e três mss. hebr.; M: “vida”.
====

[[v18-24-23]]

^<<v18-24-23,23>>^ Conceder-lhe-á tornar-se confiante para que se ampare;
E seus olhos estarão sobre os caminhos deles.

[[v18-24-24]]

^<<v18-24-24,24>>^ Por um pouco ficaram elevados, depois não são mais,
E foram abaixados; são arrancados como os demais,
E são cortados como o topo duma espiga.

[[v18-24-25]]

^<<v18-24-25,25>>^ Por conseguinte, quem me fará de mentiroso
Ou reduzirá a nada a minha palavra?”

'''

xref:018-jo/018-jo-023.adoc#v18-23-0[&#60; Capítulo Anterior] | <<v18-24-0,Topo>> | xref:018-jo/018-jo-025.adoc#v18-25-0[Próximo Capítulo &#62;]