include::./index.adoc[]

[[v18-15-0]]
=== Jó, 15
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v18-15-1]]

^<<v18-15-1,1>>^ E Elifaz, o temanita, passou a responder e a dizer:

[[v18-15-2]]

^<<v18-15-2,2>>^ “Responderá o próprio sábio com conhecimento ventoso,^&#42;1^
Ou encherá seu ventre com o vento oriental?

[NOTE]
====
. Lit.: “conhecimento de vento”. Hebr.: dha·‛ath-rú·ahh.
====

[[v18-15-3]]

^<<v18-15-3,3>>^ De nada aproveitará apenas repreender com uma palavra,
E meras expressões, sozinhas, não serão de proveito.

[[v18-15-4]]

^<<v18-15-4,4>>^ Contudo, tu mesmo fazes que o temor [diante de Deus] não tenha força,
E reduzes qualquer preocupação perante Deus.^&#42;1^

[NOTE]
====
. “Deus.” Hebr.: ’El.
====

[[v18-15-5]]

^<<v18-15-5,5>>^ Porque teu erro treina a tua boca,^&#42;1^
E escolhes a língua dos arguciosos.

[NOTE]
====
. Ou “tua boca ensina teu erro”. LXX: “tu és culpado pelas palavras da tua boca”; Sy: “tua boca ensina pecado”.
====

[[v18-15-6]]

^<<v18-15-6,6>>^ Tua boca te pronuncia iníquo, e não eu;
E teus próprios lábios respondem contra ti.

[[v18-15-7]]

^<<v18-15-7,7>>^ Foste tu o primeiro homem^&#42;1^ a nascer,
Ou foste produzido com dores de parto antes dos morros?

[NOTE]
====
. “Homem.” Hebr.: ’a·dhám.
====

[[v18-15-8]]

^<<v18-15-8,8>>^ Acaso escutas a palestra confidencial de Deus,^&#42;1^
E limitas a sabedoria a ti mesmo?

[NOTE]
====
. “Deus.” Hebr.: ’Elóh·ah.
====

[[v18-15-9]]

^<<v18-15-9,9>>^ O que sabes realmente que nós não saibamos?
Que é que entendes que também não esteja conosco?

[[v18-15-10]]

^<<v18-15-10,10>>^ Conosco estão tanto o grisalho como o idoso,
Aquele que é maior em dias do que teu pai.

[[v18-15-11]]

^<<v18-15-11,11>>^ Não te bastam as consolações de Deus^&#42;1^
Ou a palavra [falada] suavemente contigo?

[NOTE]
====
. “Deus.” Hebr.: ’El.
====

[[v18-15-12]]

^<<v18-15-12,12>>^ Por que te arrebata teu coração,
E por que lampejam teus olhos?

[[v18-15-13]]

^<<v18-15-13,13>>^ Porque voltas teu espírito contra o próprio Deus,
E fizeste sair palavras da tua própria boca.

[[v18-15-14]]

^<<v18-15-14,14>>^ Que é o homem mortal,^&#42;1^ que seja puro,
Ou que alguém nascido de mulher tenha razão?

[NOTE]
====
. “Homem mortal.” Hebr.: ’enóhsh.
====

[[v18-15-15]]

^<<v18-15-15,15>>^ Eis que não confia nem nos seus santos,
E os próprios céus não são realmente puros aos seus olhos.

[[v18-15-16]]

^<<v18-15-16,16>>^ Quanto menos ainda quando alguém é detestável e corrupto,
Um homem que bebe injustiça como água!

[[v18-15-17]]

^<<v18-15-17,17>>^ Eu to declararei. Escuta-me!
Até mesmo isto eu observei, portanto, deixa-me relatá-lo,

[[v18-15-18]]

^<<v18-15-18,18>>^ O que os próprios sábios contam
E que não ocultaram, [por proceder] dos seus pais.

[[v18-15-19]]

^<<v18-15-19,19>>^ Só a eles foi dada a terra,
E nenhum estranho passou pelo seu meio.

[[v18-15-20]]

^<<v18-15-20,20>>^ Todos os seus dias é atormentado o iníquo,
Sim, o mesmo número de anos que foram reservados para o tirano.

[[v18-15-21]]

^<<v18-15-21,21>>^ O som de coisas pavorosas está nos seus ouvidos;
Durante a paz virá sobre ele o próprio assolador.

[[v18-15-22]]

^<<v18-15-22,22>>^ Não acredita que retornará da escuridão,
E está reservado à espada.

[[v18-15-23]]

^<<v18-15-23,23>>^ Está vagando em busca de pão^&#42;1^ — onde está?
Bem sabe que o dia da escuridão está preparado, à sua mão.

[NOTE]
====
. Ou “alimento”.
====

[[v18-15-24]]

^<<v18-15-24,24>>^ Apavoram-no aflição e angústia;
Levam-no de vencida como um rei pronto para o ataque.

[[v18-15-25]]

^<<v18-15-25,25>>^ Porque estende a mão contra o próprio Deus,^&#42;1^
E tenta mostrar-se superior ao Todo-poderoso;

[NOTE]
====
. “Deus.” Hebr.: ’El.
====

[[v18-15-26]]

^<<v18-15-26,26>>^ [Porque] corre contra ele com nuca dura,
Com os umbigos grossos dos seus escudos;

[[v18-15-27]]

^<<v18-15-27,27>>^ Pois, realmente cobre a sua face com a sua gordura
E desenvolve gordura sobre os seus lombos,

[[v18-15-28]]

^<<v18-15-28,28>>^ Apenas reside em cidades que vão ser eliminadas;
Em casas em que as pessoas não ficarão morando,
Que certamente mostrarão ser destinadas a ficar montões de pedras.

[[v18-15-29]]

^<<v18-15-29,29>>^ Não enriquecerá, nem se acumulará a sua riqueza,
Nem estenderá sua adquisição^&#42;1^ sobre a terra.

[NOTE]
====
. “Adquisição.” O significado no M é incerto; LXX: “sombra”; Vg: “raiz”.
====

[[v18-15-30]]

^<<v18-15-30,30>>^ Não se desviará da escuridão;
Uma chama ressecará seu rebento,
E ele será desviado por um sopro^&#42;1^ de Sua boca.

[NOTE]
====
. “Por um sopro de.” Hebr.: berú·ahh.
====

[[v18-15-31]]

^<<v18-15-31,31>>^ Não deposite ele fé na futilidade, sendo levado a andar perdido,
Pois o que recebe em troca mostrará ser mera futilidade;

[[v18-15-32]]

^<<v18-15-32,32>>^ Cumprir-se-á antes do seu dia.^&#42;1^
E o próprio rebento dele não crescerá frondosamente.

[NOTE]
====
. Lit.: “não no seu dia”.
====

[[v18-15-33]]

^<<v18-15-33,33>>^ Repelirá as suas uvas verdes, como a vide,
E lançará fora suas flores, como a oliveira.

[[v18-15-34]]

^<<v18-15-34,34>>^ Pois a assembléia dos apóstatas é estéril,
E o próprio fogo terá de consumir as tendas do suborno.

[[v18-15-35]]

^<<v18-15-35,35>>^ Concebe-se a desgraça e dá-se à luz o que é prejudicial,
E seu próprio ventre prepara o engano.”

'''

xref:018-jo/018-jo-014.adoc#v18-14-0[&#60; Capítulo Anterior] | <<v18-15-0,Topo>> | xref:018-jo/018-jo-016.adoc#v18-16-0[Próximo Capítulo &#62;]