include::./index.adoc[]

[[v18-36-0]]
=== Jó, 36
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v18-36-1]]

^<<v18-36-1,1>>^ E Eliú passou a dizer mais:

[[v18-36-2]]

^<<v18-36-2,2>>^ “Tem mais um pouco de paciência comigo e eu te declararei
Que há ainda palavras [a dizer] por Deus.^&#42;1^

[NOTE]
====
. “Por Deus.” Hebr.: le·’Elóh·ah.
====

[[v18-36-3]]

^<<v18-36-3,3>>^ Transportarei o meu conhecimento de longe
E atribuirei justiça ao meu Formador.^&#42;1^

[NOTE]
====
. Ou “e . . . Àquele Que me Fez”. Hebr.: u·leFol·‛alí.
====

[[v18-36-4]]

^<<v18-36-4,4>>^ Pois as minhas palavras, de fato, não são falsidade;
Aquele que é perfeito em conhecimento está contigo.

[[v18-36-5]]

^<<v18-36-5,5>>^ Eis que Deus^&#42;1^ é forte e não rejeitará [a ninguém];
[Ele é] forte em poder de coração;^&#42;2^

[NOTE]
====
. “Deus.” Hebr.: ’El.
. Ou “boa motivação”. Veja 34:34.
====

[[v18-36-6]]

^<<v18-36-6,6>>^ Não preservará vivo a alguém iníquo,
Mas dará o julgamento dos atribulados.

[[v18-36-7]]

^<<v18-36-7,7>>^ Não tirará os olhos de alguém justo;
Mesmo aos reis no trono —
Ele também os assentará para sempre e eles estarão enaltecidos.

[[v18-36-8]]

^<<v18-36-8,8>>^ E se estiverem presos em grilhões,
Estão cativos em cordas de tribulação.

[[v18-36-9]]

^<<v18-36-9,9>>^ Então os informará sobre a atuação deles
E sobre suas transgressões, porque assumem ares de superioridade.

[[v18-36-10]]

^<<v18-36-10,10>>^ E destapará seu ouvido à exortação
E dirá que devem recuar do que é prejudicial.

[[v18-36-11]]

^<<v18-36-11,11>>^ Se obedecerem e servirem,
Acabarão os seus dias no que é bom
E seus anos no agradável.

[[v18-36-12]]

^<<v18-36-12,12>>^ Mas, se não obedecerem, falecerão por causa duma arma de arremesso
E expirarão sem conhecimento.

[[v18-36-13]]

^<<v18-36-13,13>>^ E os apóstatas no coração são os que acumularão ira.
Não devem clamar por ajuda porque ele os prendeu.

[[v18-36-14]]

^<<v18-36-14,14>>^ Sua alma morrerá na própria infância,
E sua vida entre os homens que se prostituem no serviço dum templo.

[[v18-36-15]]

^<<v18-36-15,15>>^ Ele socorrerá o atribulado na sua tribulação
E destapará seu ouvido na opressão.

[[v18-36-16]]

^<<v18-36-16,16>>^ E certamente te engodará [para longe] da boca da aflição!
Um lugar mais amplo, não o aperto, haverá em seu lugar,
E o consolo da tua mesa será cheio de gordura.

[[v18-36-17]]

^<<v18-36-17,17>>^ Certamente serás enchido com a sentença judicial contra o iníquo;
A sentença judicial e o juízo é que segurarão.

[[v18-36-18]]

^<<v18-36-18,18>>^ Pois [cuida de] que o furor não te engode a bater palmas [por despeito],
E não te deixes desencaminhar por um grande resgate.

[[v18-36-19]]

^<<v18-36-19,19>>^ Terá efeito teu clamor por ajuda? Não, nem na aflição
Todos os [teus] poderosos esforços.

[[v18-36-20]]

^<<v18-36-20,20>>^ Não fiques suspirando pela noite,^&#42;1^
Para que os povos retrocedam [de] onde estão.

[NOTE]
====
. Ou “pelo [descanso] da noite”.
====

[[v18-36-21]]

^<<v18-36-21,21>>^ Guarda-te de não te virares para o que é prejudicial,
Pois escolheste isso em vez de tribulação.

[[v18-36-22]]

^<<v18-36-22,22>>^ Eis que o próprio Deus^&#42;1^ age de modo elevado com o seu poder;
Que instrutor há semelhante a ele?

[NOTE]
====
. “Deus.” Hebr.: ’El.
====

[[v18-36-23]]

^<<v18-36-23,23>>^ Quem demandou dele uma prestação de contas sobre o seu caminho,
E quem disse: ‘Cometeste injustiça’?

[[v18-36-24]]

^<<v18-36-24,24>>^ Lembra-te de que deves magnificar a sua atuação
Decantada pelos homens.

[[v18-36-25]]

^<<v18-36-25,25>>^ Todos os da humanidade^&#42;1^ a contemplaram;
O próprio homem mortal está olhando de longe.

[NOTE]
====
. “Humanidade.” Hebr.: ’a·dhám.
====

[[v18-36-26]]

^<<v18-36-26,26>>^ Eis que Deus é mais sublime do que podemos saber;
Em número, os seus anos estão além de esquadrinhamento.

[[v18-36-27]]

^<<v18-36-27,27>>^ Pois ele puxa para cima as gotas de água;
Filtram como chuva para a sua neblina,

[[v18-36-28]]

^<<v18-36-28,28>>^ De modo que as nuvens pingam,
Destilam abundantemente sobre a humanidade.

[[v18-36-29]]

^<<v18-36-29,29>>^ Deveras, quem pode entender as camadas de nuvens,
Os estrondos desde a sua barraca?

[[v18-36-30]]

^<<v18-36-30,30>>^ Eis que estendeu sobre ela a sua luz
E cobriu as raízes do mar.

[[v18-36-31]]

^<<v18-36-31,31>>^ Porque por estes [meios] pleiteia a causa dos povos;
Dá comida em abundância.

[[v18-36-32]]

^<<v18-36-32,32>>^ Nas suas mãos encobriu o raio^&#42;1^
E dá-lhe ordem contra o assaltante.

[NOTE]
====
. Lit.: “luz”. Hebr.: ’ohr, o mesmo substantivo que no v. 30.
====

[[v18-36-33]]

^<<v18-36-33,33>>^ Seu retumbo informa a respeito dele,
Também o gado, a respeito daquele que sobe.

'''

xref:018-jo/018-jo-035.adoc#v18-35-0[&#60; Capítulo Anterior] | <<v18-36-0,Topo>> | xref:018-jo/018-jo-037.adoc#v18-37-0[Próximo Capítulo &#62;]