include::./index.adoc[]

[[v18-2-0]]
=== Jó, 2
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v18-2-1]]

^<<v18-2-1,1>>^ Depois veio a ser o dia em que os filhos^&#42;1^ do [verdadeiro] Deus entraram para tomar a sua posição perante Jeová, e também Satanás^&#42;2^ passou a entrar no meio deles para tomar a sua posição perante Jeová.

[NOTE]
====
. “Os anjos”, LXX.
. Veja 1:6 n.: “Satanás”.
====

[[v18-2-2]]

^<<v18-2-2,2>>^ Jeová disse então a Satanás: “Donde é que vens?” Então Satanás respondeu a Jeová e disse: “De percorrer a terra e de andar nela.”

[[v18-2-3]]

^<<v18-2-3,3>>^ E Jeová prosseguiu, dizendo a Satanás: “Fixaste teu coração no meu servo Jó, que não há ninguém igual a ele na terra, homem inculpe e reto, temendo a Deus e desviando-se do mal? Ele ainda se agarra à sua integridade, embora me instigues contra ele para tragá-lo sem causa.”

[[v18-2-4]]

^<<v18-2-4,4>>^ Mas, Satanás respondeu a Jeová e disse: “Pele por pele, e tudo o que o homem tem dará pela sua alma.^&#42;1^

[NOTE]
====
. “Sua alma (vida).” Hebr.: naf·shóh; gr.: psy·khés; lat.: á·ni·ma. Veja Ap. 4A.
====

[[v18-2-5]]

^<<v18-2-5,5>>^ Ao invés disso, estende agora tua mão, por favor, e toca-lhe até o osso e a carne, [e vê] se não te amaldiçoará^&#42;1^ na tua própria face.”

[NOTE]
====
. Veja 1:5 n.
====

[[v18-2-6]]

^<<v18-2-6,6>>^ Por conseguinte, Jeová disse a Satanás: “Eis que está na tua mão! Somente cuida da própria alma^&#42;1^ dele!”

[NOTE]
====
. Veja v. 4 n.
====

[[v18-2-7]]

^<<v18-2-7,7>>^ Portanto, Satanás saiu de diante da pessoa^&#42;1^ de Jeová e golpeou a Jó com um furúnculo maligno, desde a sola de seu pé até o alto da sua cabeça.

[NOTE]
====
. Veja 1:12 n.
====

[[v18-2-8]]

^<<v18-2-8,8>>^ E este passou a tomar para si um caco para se raspar com ele; e estava sentado no meio de cinzas.

[[v18-2-9]]

^<<v18-2-9,9>>^ Finalmente, sua esposa lhe disse: “Ainda te aferras à tua integridade? Amaldiçoa^&#42;1^ a Deus e morre!”

[NOTE]
====
. Veja 1:5 n.
====

[[v18-2-10]]

^<<v18-2-10,10>>^ Mas ele lhe disse: “Como fala uma das mulheres insensatas, também tu falas. Devemos aceitar apenas o que é bom da parte do [verdadeiro] Deus e não aceitar também o que é mau?” Em tudo isso não pecou Jó com os seus lábios.

[[v18-2-11]]

^<<v18-2-11,11>>^ E três companheiros de Jó chegaram a ouvir toda esta calamidade que viera sobre ele e passaram a chegar, cada um de seu próprio lugar: Elifaz, o temanita, e Bildade, o suíta, e Zofar, o naamatita. Encontraram-se, pois, por combinação para chegarem e se compadecerem dele, e o consolarem.

[[v18-2-12]]

^<<v18-2-12,12>>^ Quando de longe levantaram os olhos, então não o reconheceram. E passaram a levantar a sua voz e a chorar, e a rasgar cada um a sua túnica sem mangas, e a atirar pó para os céus sobre as suas cabeças.

[[v18-2-13]]

^<<v18-2-13,13>>^ E ficaram sentados com ele na terra por sete dias e sete noites, e ninguém lhe falava uma palavra, pois viram que a dor era muito grande.

'''

xref:018-jo/018-jo-001.adoc#v18-1-0[&#60; Capítulo Anterior] | <<v18-2-0,Topo>> | xref:018-jo/018-jo-003.adoc#v18-3-0[Próximo Capítulo &#62;]