include::./index.adoc[]

[[v18-17-0]]
=== Jó, 17
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v18-17-1]]

^<<v18-17-1,1>>^ “Meu próprio espírito^&#42;1^ foi quebrantado, meus próprios dias foram extintos;
O cemitério é para mim.

[NOTE]
====
. Ou “fôlego”. Veja 12:10 n.: “espírito”.
====

[[v18-17-2]]

^<<v18-17-2,2>>^ Certamente se mofa de mim,
E meu olho se hospeda no meio do seu comportamento rebelde.

[[v18-17-3]]

^<<v18-17-3,3>>^ Por favor, coloca deveras meu penhor junto de ti.
Quem mais apertará as mãos comigo em compromisso?

[[v18-17-4]]

^<<v18-17-4,4>>^ Porque fechaste seu coração à discrição.
Por isso não os exaltas.

[[v18-17-5]]

^<<v18-17-5,5>>^ Talvez informe os companheiros para que tomem seu quinhão,
Mas os próprios olhos dos seus filhos falharão.

[[v18-17-6]]

^<<v18-17-6,6>>^ E ele me apresentou como ditado dos povos,
De modo que me torno alguém em cuja face se cospe.

[[v18-17-7]]

^<<v18-17-7,7>>^ E meu olho turva-se de vexame
E meus membros são todos eles como sombra.

[[v18-17-8]]

^<<v18-17-8,8>>^ Pessoas retas olham assombradas para isso,
E até mesmo o inocente fica agitado por causa do apóstata.

[[v18-17-9]]

^<<v18-17-9,9>>^ O justo prende-se ao seu caminho,
E quem tem mãos limpas está aumentando em força.

[[v18-17-10]]

^<<v18-17-10,10>>^ No entanto, podeis todos recomeçar. Portanto, vinde, por favor,
Visto que não acho nenhum sábio entre vós.

[[v18-17-11]]

^<<v18-17-11,11>>^ Meus próprios dias passaram adiante, romperam-se os meus próprios planos,
Os desejos do meu coração.

[[v18-17-12]]

^<<v18-17-12,12>>^ Estão pondo a noite pelo dia:
‘A luz está perto por causa da escuridão.’

[[v18-17-13]]

^<<v18-17-13,13>>^ Se eu ficar aguardando, o Seol será a minha casa;
Terei de estender na escuridão o meu leito [de repouso].

[[v18-17-14]]

^<<v18-17-14,14>>^ Terei de clamar à cova: ‘Tu és meu pai!’
Ao gusano: ‘Minha mãe e minha irmã!’

[[v18-17-15]]

^<<v18-17-15,15>>^ Então, onde está a minha esperança?
E minha esperança — quem é que a avista?

[[v18-17-16]]

^<<v18-17-16,16>>^ Elas^&#42;1^ descerão às barras do Seol,^&#42;2^
Quando juntos tivermos de descer ao próprio pó.”

[NOTE]
====
. “Elas”, hebr. fem., referindo-se à “esperança”, mencionada duas vezes no v. 15.
. “Seol.” Hebr.: she’ól; gr.: haí·den; lat.: in·fér·num. Veja Ap. 4B.
====

'''

xref:018-jo/018-jo-016.adoc#v18-16-0[&#60; Capítulo Anterior] | <<v18-17-0,Topo>> | xref:018-jo/018-jo-018.adoc#v18-18-0[Próximo Capítulo &#62;]