include::./index.adoc[]

[[v18-6-0]]
=== Jó, 6
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v18-6-1]]

^<<v18-6-1,1>>^ E Jó passou a responder e a dizer:

[[v18-6-2]]

^<<v18-6-2,2>>^ “Se tão-somente se pesasse cabalmente o meu vexame
E ao mesmo tempo se pusesse na própria balança a minha adversidade!

[[v18-6-3]]

^<<v18-6-3,3>>^ Pois agora ela é mais pesada do que mesmo as areias dos mares.
Por isso é que as minhas próprias palavras foram conversa irrefletida.

[[v18-6-4]]

^<<v18-6-4,4>>^ Porque estão comigo as flechas do Todo-poderoso,^&#42;1^
Sendo sua peçonha sorvida por meu espírito;
Enfileiram-se contra mim^&#42;2^ os terrores da parte de Deus.^&#42;3^

[NOTE]
====
. “Jeová”, LXXVg.
. “Expulsam-me do contato social”, mediante a transposição de duas letras no M.
. “Deus.” Hebr.: ’Elóh·ah.
====

[[v18-6-5]]

^<<v18-6-5,5>>^ Zurrará a zebra^&#42;1^ por causa da relva,
Ou mugirá o touro por causa da sua forragem?

[NOTE]
====
. Ou “onagro; jumento selvagem”.
====

[[v18-6-6]]

^<<v18-6-6,6>>^ Comer-se-ão coisas insípidas sem sal,
Ou há sabor na seiva viscosa da altéia?

[[v18-6-7]]

^<<v18-6-7,7>>^ Minha alma se negou a tocar [quaisquer coisas].
São como moléstia no meu alimento.

[[v18-6-8]]

^<<v18-6-8,8>>^ Quem me dera que chegasse o que pedi
E que Deus^&#42;1^ me concedesse mesmo a minha esperança!

[NOTE]
====
. “Deus.” Hebr.: ’Elóh·ah.
====

[[v18-6-9]]

^<<v18-6-9,9>>^ E que Deus se resolvesse e me esmigalhasse.
Que soltasse a sua mão e desse cabo de mim!

[[v18-6-10]]

^<<v18-6-10,10>>^ Mesmo assim seria meu consolo;
E eu pularia [de alegria] por causa das [minhas] dores de parto,
[Embora] ele não tivesse compaixão, pois não ocultei as declarações do Santo.

[[v18-6-11]]

^<<v18-6-11,11>>^ Qual é meu poder, que eu deva continuar a esperar?
E qual é meu fim, que eu deva prolongar a minha alma?^&#42;1^

[NOTE]
====
. Ou “minha vida [como alma]”. Hebr.: naf·shí; gr.: psy·khé.
====

[[v18-6-12]]

^<<v18-6-12,12>>^ É meu poder o poder das pedras?
Ou é a minha carne de cobre?

[[v18-6-13]]

^<<v18-6-13,13>>^ Acaso não há em mim auxílio próprio,
E foi afugentado de mim o trabalho eficiente?

[[v18-6-14]]

^<<v18-6-14,14>>^ Quem recusar ao seu próximo a benevolência,^&#42;1^
Abandonará também o próprio temor do Todo-poderoso.

[NOTE]
====
. Ou “amor leal”.
====

[[v18-6-15]]

^<<v18-6-15,15>>^ Meus próprios irmãos agiram traiçoeiramente, iguais a uma torrente hibernal,
Como o rego das torrentes hibernais que estão passando.

[[v18-6-16]]

^<<v18-6-16,16>>^ Turvas por causa do gelo,
Oculta-se sobre elas a neve.

[[v18-6-17]]

^<<v18-6-17,17>>^ No tempo devido ficam sem água, foram silenciadas;
Quando esquenta, secam-se do seu lugar.

[[v18-6-18]]

^<<v18-6-18,18>>^ As veredas do seu caminho são desviadas;
Sobem ao lugar deserto e perecem.

[[v18-6-19]]

^<<v18-6-19,19>>^ As caravanas de Tema olharam,
A companhia viajante de sabeus^&#42;1^ as aguardou.

[NOTE]
====
. Lit.: “Sabá”.
====

[[v18-6-20]]

^<<v18-6-20,20>>^ Certamente estão envergonhados por terem confiado;
Chegaram até o lugar e ficaram desapontados.

[[v18-6-21]]

^<<v18-6-21,21>>^ Pois agora viestes a ser nada;
Vedes terror e ficais com medo.

[[v18-6-22]]

^<<v18-6-22,22>>^ É porque eu disse: ‘Dai-me [algo],
Ou dai-me um presente do vosso poder;

[[v18-6-23]]

^<<v18-6-23,23>>^ E salvai-me da mão dum adversário,
E deveis remir-me da mão de tiranos’?

[[v18-6-24]]

^<<v18-6-24,24>>^ Instruí-me, e eu, da minha parte, ficarei calado;
E fazei-me entender que engano cometi.

[[v18-6-25]]

^<<v18-6-25,25>>^ As declarações de retidão — elas não foram penosas!
Mas o que repreende a repreensão^&#42;1^ da vossa parte?

[NOTE]
====
. “Repreensão.” No hebr., este é um verbo no infinitivo absoluto, indefinido quanto ao tempo e impessoal.
====

[[v18-6-26]]

^<<v18-6-26,26>>^ É para repreender palavras que estais maquinando,
Sendo que as declarações dum desesperado são apenas para o vento?

[[v18-6-27]]

^<<v18-6-27,27>>^ Quanto mais lançareis sortes sobre o órfão de pai
E regateareis o vosso companheiro!

[[v18-6-28]]

^<<v18-6-28,28>>^ E agora, prossegui, prestai atenção a mim
E [vede] se vou mentir na vossa própria face.

[[v18-6-29]]

^<<v18-6-29,29>>^ Voltai, por favor — não surja injustiça —
Sim, voltai — ainda há nisso a minha justiça.

[[v18-6-30]]

^<<v18-6-30,30>>^ Há injustiça na minha língua
Ou não discerne o meu próprio paladar a adversidade?

'''

xref:018-jo/018-jo-005.adoc#v18-5-0[&#60; Capítulo Anterior] | <<v18-6-0,Topo>> | xref:018-jo/018-jo-007.adoc#v18-7-0[Próximo Capítulo &#62;]