include::./index.adoc[]

[[v18-41-0]]
=== Jó, 41
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v18-41-1]]

^<<v18-41-1,1>>^ “Acaso podes puxar para fora o leviatã^&#42;1^ com um anzol
Ou podes manter-lhe a língua abaixada com uma corda?

[NOTE]
====
. “Leviatã”, M(hebr.: liw·ya·thán)Vg; LXX: “um dragão”.
====

[[v18-41-2]]

^<<v18-41-2,2>>^ Podes pôr-lhe um junco nas narinas
Ou furar-lhe a queixada com um espinho?

[[v18-41-3]]

^<<v18-41-3,3>>^ Far-te-á muitos rogos
Ou dir-te-á palavras suaves?

[[v18-41-4]]

^<<v18-41-4,4>>^ Concluirá contigo um pacto
Para que o tomes como escravo por tempo indefinido?

[[v18-41-5]]

^<<v18-41-5,5>>^ Divertir-te-ás com ele como se fosse um pássaro,
Ou o atarás para as tuas moças?

[[v18-41-6]]

^<<v18-41-6,6>>^ Acaso o regatearão^&#42;1^ sócios?
Acaso o dividirão entre os comerciantes?^&#42;2^

[NOTE]
====
. Ou “o festejarão”.
. Lit.: “cananeus”. Hebr.: kena·‛aním.
====

[[v18-41-7]]

^<<v18-41-7,7>>^ Porventura encherás a sua pele de arpões
Ou a sua cabeça de chuços de pesca?

[[v18-41-8]]

^<<v18-41-8,8>>^ Põe tua mão sobre ele.
Lembra-te da batalha. Não o faças de novo.^&#42;1^

[NOTE]
====
. MLXX terminam aqui o capítulo 40.
====

[[v18-41-9]]

^<<v18-41-9,9>>^ Eis que certamente ficará desapontada a expectativa que se tem dele.
Também se é arremessado para baixo à mera vista dele.

[[v18-41-10]]

^<<v18-41-10,10>>^ Ninguém é tão audaz que o incite.
E quem é que se pode manter firme diante de mim?

[[v18-41-11]]

^<<v18-41-11,11>>^ Quem me deu primeiro alguma coisa, que eu o deva recompensar?
Debaixo dos céus inteiros, é meu.

[[v18-41-12]]

^<<v18-41-12,12>>^ Não me calarei sobre as suas partes
Ou sobre a questão da [sua] potência e da graça das suas proporções.

[[v18-41-13]]

^<<v18-41-13,13>>^ Quem expôs a face da sua vestimenta?
Quem entrará na sua queixada dupla?^&#42;1^

[NOTE]
====
. Lit.: “freio”, M; LXX: “armadura imbricada [cota de malha]”.
====

[[v18-41-14]]

^<<v18-41-14,14>>^ Quem abriu as portas da sua face?^&#42;1^
Seus dentes em redor são aterradores.

[NOTE]
====
. “Face”, M; Sy: “boca”.
====

[[v18-41-15]]

^<<v18-41-15,15>>^ Leiras de escamas são a sua altivez,
Fechadas como que por um selo apertado.

[[v18-41-16]]

^<<v18-41-16,16>>^ Uma se ajusta bem à outra,
E nem mesmo o ar pode penetrar entre elas.

[[v18-41-17]]

^<<v18-41-17,17>>^ Cada uma é apegada à outra;^&#42;1^
Agarram-se uma à outra e não podem ser separadas.

[NOTE]
====
. Lit.: “ao seu irmão”.
====

[[v18-41-18]]

^<<v18-41-18,18>>^ Seus próprios espirros fazem brilhar a luz
E seus olhos são como os raios da alva.

[[v18-41-19]]

^<<v18-41-19,19>>^ Lampejos procedem da sua boca,
Sim, faíscas de fogo escapam.

[[v18-41-20]]

^<<v18-41-20,20>>^ Das suas narinas sai fumaça,
Igual a uma fornalha acesa com juncos.

[[v18-41-21]]

^<<v18-41-21,21>>^ A própria alma^&#42;1^ dele incendeia carvões,
E até mesmo uma chama sai da sua boca.

[NOTE]
====
. “Alma dele.” Hebr.: naf·shóh; gr.: psy·khé.
====

[[v18-41-22]]

^<<v18-41-22,22>>^ No seu pescoço hospeda-se a força,
E diante dele pula o desespero.^&#42;1^

[NOTE]
====
. “Pula o desespero”, M; LXX: “corre a destruição”.
====

[[v18-41-23]]

^<<v18-41-23,23>>^ As dobras da sua carne se apegam uma à outra;
Estão como que fundidas sobre ele, imóveis.

[[v18-41-24]]

^<<v18-41-24,24>>^ Seu coração é fundido como pedra,
Sim, fundido como a mó inferior.

[[v18-41-25]]

^<<v18-41-25,25>>^ Por ele se levantar, amedrontam-se os fortes;
Por causa da consternação, ficam confusos.

[[v18-41-26]]

^<<v18-41-26,26>>^ Ao alcançá-lo, a própria espada não se mostra à altura,
Nem tampouco a lança, o dardo ou a ponta da flecha.

[[v18-41-27]]

^<<v18-41-27,27>>^ Considera o ferro apenas como palha,
O cobre apenas como pau podre.

[[v18-41-28]]

^<<v18-41-28,28>>^ Uma flecha^&#42;1^ não o põe em fuga;
As pedras de funda foram transformadas para ele em mero restolho.

[NOTE]
====
. Lit.: “Um filho de arco.”
====

[[v18-41-29]]

^<<v18-41-29,29>>^ O cacete foi considerado [por ele] como mero restolho,
E ri-se do retinir do dardo.

[[v18-41-30]]

^<<v18-41-30,30>>^ Suas partes de baixo são como cacos pontiagudos;^&#42;1^
Estende sobre a lama um instrumento de debulhar.

[NOTE]
====
. Ou “os cacos mais pontiagudos (afiados)”, segundo a expressão idiomática hebr.
====

[[v18-41-31]]

^<<v18-41-31,31>>^ Faz as profundezas ferver como panela;
Faz o próprio mar igual a um pote de ungüento.

[[v18-41-32]]

^<<v18-41-32,32>>^ Atrás de si faz luzir a senda;^&#42;1^
Considerar-se-ia a água de profundeza como cãs.^&#42;2^

[NOTE]
====
. “E a parte mais inferior da profundeza [gr.: ton de tár·ta·ron tes a·býs·sou, “o tártaro do abismo”] como cativo”, LXX. Veja Ap. 4D.
. “Como cãs”, M; LXX: “como lugar para se andar”; Sy: “como a terra seca”.
====

[[v18-41-33]]

^<<v18-41-33,33>>^ Sobre o pó não há quem lhe seja igual,
Alguém feito para não ter terror.

[[v18-41-34]]

^<<v18-41-34,34>>^ Vê tudo o que é alto.
É rei sobre todas as feras majestosas.”^&#42;1^

[NOTE]
====
. Lit.: “todos os filhos de orgulho (dignidade)”.
====

'''

xref:018-jo/018-jo-040.adoc#v18-40-0[&#60; Capítulo Anterior] | <<v18-41-0,Topo>> | xref:018-jo/018-jo-042.adoc#v18-42-0[Próximo Capítulo &#62;]