include::./index.adoc[]

[[v18-13-0]]
=== Jó, 13
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v18-13-1]]

^<<v18-13-1,1>>^ “Eis que meu olho viu tudo isto,
Meu ouvido o ouviu e o considera.

[[v18-13-2]]

^<<v18-13-2,2>>^ O que vós sabeis, eu também sei muito bem;
Não sou inferior a vós.^&#42;1^

[NOTE]
====
. Veja 12:3 n.
====

[[v18-13-3]]

^<<v18-13-3,3>>^ No entanto, eu, da minha parte, falaria ao próprio Todo-poderoso,
E me agradaria em argumentar com Deus.^&#42;1^

[NOTE]
====
. “Deus.” Hebr.: ’El.
====

[[v18-13-4]]

^<<v18-13-4,4>>^ Por outro lado, vós sois homens que besuntam com falsidade;
Todos vós sois médicos sem valor algum.

[[v18-13-5]]

^<<v18-13-5,5>>^ Se tão-somente ficásseis absolutamente calados,
Para que mostrasse ser sabedoria da vossa parte!

[[v18-13-6]]

^<<v18-13-6,6>>^ Ouvi, por favor, os meus contra-argumentos,
E prestai atenção ao pleitear dos meus lábios.

[[v18-13-7]]

^<<v18-13-7,7>>^ Acaso falareis injustiça para com o próprio Deus,
E falareis dolo para ele?

[[v18-13-8]]

^<<v18-13-8,8>>^ Sereis parciais com ele,
Ou contendereis em juízo pelo [verdadeiro] Deus?

[[v18-13-9]]

^<<v18-13-9,9>>^ Porventura seria bom que ele vos sondasse?
Ou o ludibriareis assim como se ludibria o homem mortal?

[[v18-13-10]]

^<<v18-13-10,10>>^ Ele decididamente vos repreenderá
Se tentardes às escondidas ser parciais;^&#42;1^

[NOTE]
====
. “Ser parciais”, M; TSyVg: “tratá-lo com parcialidade”.
====

[[v18-13-11]]

^<<v18-13-11,11>>^ Não vos assustará a sua própria dignidade,
E não cairá sobre vós o próprio pavor dele?

[[v18-13-12]]

^<<v18-13-12,12>>^ Vossas declarações memoráveis são provérbios de cinzas;
Os umbigos dos vossos escudos^&#42;1^ são umbigos de barro.

[NOTE]
====
. Ou “vossos parapeitos”.
====

[[v18-13-13]]

^<<v18-13-13,13>>^ Calai-vos diante de mim, para que eu mesmo fale,
Então venha sobre mim o que vier!

[[v18-13-14]]

^<<v18-13-14,14>>^ Por que carrego a minha carne nos meus dentes
E coloco a minha própria alma^&#42;1^ na palma da minha mão?

[NOTE]
====
. “E . . . a minha própria alma.” Hebr.: wenaf·shí; gr.: psy·khén; lat.: á·ni·mam. Veja Jz 12:3; 1Sa 19:5.
====

[[v18-13-15]]

^<<v18-13-15,15>>^ Mesmo que me matasse, não esperaria eu?^&#42;1^
Eu apenas argumentaria à sua face em prol dos meus próprios caminhos.

[NOTE]
====
. Ou “eu não esperaria”, M; MmargemTSyVg: “por ele eu esperaria”.
====

[[v18-13-16]]

^<<v18-13-16,16>>^ Ele^&#42;1^ seria também a minha salvação,
Pois nenhum apóstata entrará diante dele.

[NOTE]
====
. Ou: “Isso”.
====

[[v18-13-17]]

^<<v18-13-17,17>>^ Ouvi cabalmente a minha palavra,
E tende nos ouvidos a minha declaração.

[[v18-13-18]]

^<<v18-13-18,18>>^ Por favor, eis que apresentei um pleito judicial;
Bem sei que eu é que tenho razão.

[[v18-13-19]]

^<<v18-13-19,19>>^ Quem contenderá comigo?
Pois, se eu ficasse agora calado, simplesmente expiraria!

[[v18-13-20]]

^<<v18-13-20,20>>^ Apenas não me faças^&#42;1^ duas coisas;
Neste caso não me esconderei só por tua causa;

[NOTE]
====
. “Faças.” O verbo hebr. está no sing. para concordar com “tu”, “teu”, “tua” e “ti”, falando-se a Deus, nos vv. 20-27.
====

[[v18-13-21]]

^<<v18-13-21,21>>^ Põe longe de mim a tua própria mão,
E não me apavore o horror de ti.

[[v18-13-22]]

^<<v18-13-22,22>>^ Ou chama para que eu mesmo responda,
Ou fale eu, e replica-me tu.

[[v18-13-23]]

^<<v18-13-23,23>>^ De que modo tenho erros e pecados?
Faze-me saber a minha própria revolta e o meu próprio pecado.

[[v18-13-24]]

^<<v18-13-24,24>>^ Por que escondes a tua própria face
E me consideras teu inimigo?

[[v18-13-25]]

^<<v18-13-25,25>>^ Farás estremecer a mera folha impelida [pelo vento]
Ou irás no encalço de mero restolho seco?

[[v18-13-26]]

^<<v18-13-26,26>>^ Pois continuas a escrever contra mim coisas amargas
E me fazes possuir [as conseqüências dos] erros da minha mocidade.

[[v18-13-27]]

^<<v18-13-27,27>>^ Manténs também meus pés no tronco,
E vigias todas as minhas veredas;
Traças a tua própria linha para a planta^&#42;1^ dos meus pés.

[NOTE]
====
. Lit.: “raízes dos”.
====

[[v18-13-28]]

^<<v18-13-28,28>>^ E ele^&#42;1^ é como algo podre^&#42;2^ que se gasta;
Como roupa que a traça realmente consome.

[NOTE]
====
. “Ele.” Isto é, Jó.
. “Algo podre (podridão)”, MVg; LXX: “odre”; Sy: “bolsa de couro”.
====

'''

xref:018-jo/018-jo-012.adoc#v18-12-0[&#60; Capítulo Anterior] | <<v18-13-0,Topo>> | xref:018-jo/018-jo-014.adoc#v18-14-0[Próximo Capítulo &#62;]