include::./index.adoc[]

[[v18-11-0]]
=== Jó, 11
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v18-11-1]]

^<<v18-11-1,1>>^ E Zofar, o naamatita, passou a responder e a dizer:

[[v18-11-2]]

^<<v18-11-2,2>>^ “Ficará a multidão de palavras sem resposta,
Ou terá razão o mero bazofiador?^&#42;1^

[NOTE]
====
. Lit.: “homem de lábios”.
====

[[v18-11-3]]

^<<v18-11-3,3>>^ Acaso teu palavrório oco fará os homens^&#42;1^ calar-se,
E continuarás a caçoar sem que alguém [te] reprove?

[NOTE]
====
. “Homens.” Hebr.: methím, varões adultos.
====

[[v18-11-4]]

^<<v18-11-4,4>>^ Também, dizes: ‘Meu ensinamento é puro
E mostrei ser realmente limpo aos teus olhos.’

[[v18-11-5]]

^<<v18-11-5,5>>^ No entanto, se tão-somente o próprio Deus falasse
E abrisse seus lábios para contigo!

[[v18-11-6]]

^<<v18-11-6,6>>^ Então te comunicaria os segredos da sabedoria,
Porque são múltiplas^&#42;1^ as coisas da sabedoria prática.
Também saberias^&#42;2^ que Deus permite que seja esquecida parte do teu erro.

[NOTE]
====
. Lit.: “dobradas”.
. Lit.: “E sabe”, imperativo.
====

[[v18-11-7]]

^<<v18-11-7,7>>^ Acaso podes descobrir as coisas profundas de Deus,
Ou podes descobrir o próprio limite do Todo-poderoso?

[[v18-11-8]]

^<<v18-11-8,8>>^ É mais alta do que o céu. Que podes tu conseguir?
É mais profunda do que o Seol. Que podes tu saber?

[[v18-11-9]]

^<<v18-11-9,9>>^ É mais extensa do que a terra em medida
E mais larga do que o mar.

[[v18-11-10]]

^<<v18-11-10,10>>^ Se ele passa adiante e entrega [alguém],
E convoca um tribunal, então quem lhe pode resistir?

[[v18-11-11]]

^<<v18-11-11,11>>^ Pois ele mesmo conhece muito bem os homens^&#42;1^ que não são verazes.
Quando vê o que é prejudicial, não se mostrará também atento?

[NOTE]
====
. Veja v. 3 n.
====

[[v18-11-12]]

^<<v18-11-12,12>>^ Até mesmo o homem^&#42;1^ [de cabeça] oca terá bom motivo
Assim que uma zebra asinina nascer como homem.^&#42;2^

[NOTE]
====
. “Até mesmo o homem.” Hebr.: we’ísh.
. Ou “homem terreno”. Hebr.: ’a·dhám.
====

[[v18-11-13]]

^<<v18-11-13,13>>^ Se tu mesmo realmente preparares teu coração
E realmente estenderes as palmas das tuas mãos para ele,

[[v18-11-14]]

^<<v18-11-14,14>>^ Se houver na tua mão o que é prejudicial, ponha-o para longe,
E não deixes nenhuma injustiça morar nas tuas tendas.

[[v18-11-15]]

^<<v18-11-15,15>>^ Pois então levantarás a tua face sem defeito
E certamente ficarás estabelecido, e não temerás.

[[v18-11-16]]

^<<v18-11-16,16>>^ Pois tu — tu te esquecerás da própria desgraça;
Lembrar-te-ás [dela] como que de águas que passaram adiante.

[[v18-11-17]]

^<<v18-11-17,17>>^ E mais clara que o meio-dia surgirá a duração da [tua] vida;
A escuridão se tornará igual à própria manhã.

[[v18-11-18]]

^<<v18-11-18,18>>^ E forçosamente terás confiança porque há esperança;
E hás de olhar cuidadosamente em volta — deitar-te-ás em segurança.

[[v18-11-19]]

^<<v18-11-19,19>>^ E tu te espicharás sem que alguém [te] faça tremer.
E muitos certamente te farão ficar com disposição branda;^&#42;1^

[NOTE]
====
. Lit.: “abrandarão tua face”.
====

[[v18-11-20]]

^<<v18-11-20,20>>^ E falharão os próprios olhos dos iníquos;
E perecerá deles o lugar de refúgio,
E sua esperança será a expiração da alma.”

'''

xref:018-jo/018-jo-010.adoc#v18-10-0[&#60; Capítulo Anterior] | <<v18-11-0,Topo>> | xref:018-jo/018-jo-012.adoc#v18-12-0[Próximo Capítulo &#62;]