include::./index.adoc[]

[[v18-1-0]]
=== Jó, 1
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v18-1-1]]

^<<v18-1-1,1>>^ Aconteceu haver na terra de Uz um homem^&#42;1^ cujo nome era Jó;^&#42;2^ e este homem mostrava ser inculpe e reto, e temia a Deus e desviava-se do mal.

[NOTE]
====
. “Homem.” Hebr.: ’ish.
. “Jó.” Hebr.: ’I·yóhv, significando “Objeto de Hostilidade”. Não é o mesmo que weYóhv, “e Ió”, em Gên 46:13.
====

[[v18-1-2]]

^<<v18-1-2,2>>^ E vieram nascer-lhe sete filhos e três filhas.

[[v18-1-3]]

^<<v18-1-3,3>>^ E seu gado chegou a ser de sete mil ovelhas,^&#42;1^ e três mil camelos, e quinhentas juntas de gado vacum, e quinhentas jumentas, junto com um grande corpo de servos; e este homem veio a ser o maior de todos os orientais.^&#42;2^

[NOTE]
====
. Ou “gado miúdo”, incluindo ovelhas e cabritos.
. Lit.: “filhos do Oriente”.
====

[[v18-1-4]]

^<<v18-1-4,4>>^ E seus filhos foram e realizaram um banquete na casa de cada um^&#42;1^ [deles] no seu próprio dia; e mandaram convidar suas três irmãs para comerem e beberem com eles.

[NOTE]
====
. Ou “cada um”. Hebr.: ’ish.
====

[[v18-1-5]]

^<<v18-1-5,5>>^ E dava-se que, tendo os dias de banquete completado o ciclo, Jó mandava santificá-los; e ele se levantava de manhã cedo e oferecia sacrifícios queimados segundo o número de todos eles; pois, dizia Jó, “meus filhos talvez tenham pecado e amaldiçoado^&#42;1^ a Deus no seu coração”. Assim Jó fazia sempre.

[NOTE]
====
. “Tenham . . . amaldiçoado” era a versão original. O texto foi mudado para rezar “tenham . . . abençoado”. LXX: “imaginado coisas más contra”; Sy: “injuriado”; Vg: “bendito”. Veja Ap. 2B.
====

[[v18-1-6]]

^<<v18-1-6,6>>^ Ora, veio a ser o dia em que os filhos^&#42;1^ do [verdadeiro] Deus^&#42;2^ entraram para tomar sua posição perante Jeová, e até mesmo Satanás^&#42;3^ passou a entrar no meio deles.

[NOTE]
====
. “Filhos do.” Hebr.: benéh; LXX: “anjos”.
. “Do [verdadeiro] Deus.” Hebr.: ha·’Elo·hím, com o artigo definido ha, “o”, precedendo ao título ’Elo·hím. Veja Ap. 1F.
. Hebr.: has·Sa·tán, “o Opositor”. Usado nos capítulos 1 e 2. Esta é a primeira ocorrência de has·Sa·tán no M, embora sa·tán, “opositor”, sem o artigo definido ha, ocorra nove vezes antes disso, começando em Núm 22:22. Gesenius’ Hebrew Grammar (GK), sec. 126 d e e, declara: “O artigo, de modo geral, é empregado para determinar um substantivo sempre que seja exigido pelo grego e pelo inglês; assim: . . . (d) Quando termos que se aplicam a classes inteiras são restritos (simplesmente pelo uso) a determinados indivíduos . . . ou a coisas, ex. שָׂטָן adversário, הַשטָן o adversário, Satanás (Satã) . . .”
====

[[v18-1-7]]

^<<v18-1-7,7>>^ Jeová disse então a Satanás: “Donde vens?” A isto respondeu Satanás a Jeová e disse: “De percorrer a terra e de andar nela.”

[[v18-1-8]]

^<<v18-1-8,8>>^ E Jeová prosseguiu, dizendo a Satanás: “Fixaste teu coração no meu servo Jó, que não há ninguém igual a ele na terra, homem inculpe e reto, temendo a Deus e desviando-se do mal?”

[[v18-1-9]]

^<<v18-1-9,9>>^ Então respondeu Satanás a Jeová e disse: “Acaso é por nada que Jó teme a Deus?

[[v18-1-10]]

^<<v18-1-10,10>>^ Não puseste tu mesmo uma sebe em volta dele, e em volta da sua casa, e em volta de tudo o que ele tem? Abençoaste o trabalho das suas mãos, e o próprio gado dele se tem espalhado pela terra.

[[v18-1-11]]

^<<v18-1-11,11>>^ Mas, ao invés disso, estende tua mão, por favor, e toca em tudo o que ele tem, [e vê] se não te amaldiçoará^&#42;1^ na tua própria face.”

[NOTE]
====
. Veja v. 5 n.
====

[[v18-1-12]]

^<<v18-1-12,12>>^ Por conseguinte, Jeová disse a Satanás: “Eis que tudo o que ele tem está na tua mão. Somente contra ele próprio não estendas a tua mão!” De modo que Satanás saiu de diante da pessoa^&#42;1^ de Jeová.

[NOTE]
====
. Lit.: “face”. Veja 2Sa 17:11 n.: “pessoa”.
====

[[v18-1-13]]

^<<v18-1-13,13>>^ Ora, veio a ser o dia em que seus filhos e suas filhas comiam e bebiam vinho na casa de seu irmão, o primogênito.

[[v18-1-14]]

^<<v18-1-14,14>>^ E um mensageiro chegou a Jó e passou a dizer: “Aconteceu que o próprio gado vacum estava arando e as jumentas estavam pastando ao lado dele,

[[v18-1-15]]

^<<v18-1-15,15>>^ quando os sabeus^&#42;1^ vieram fazer um assalto e os tomaram, e aos ajudantes golpearam com o fio da espada; e consegui escapar, somente eu sozinho, para te contar [isso].”

[NOTE]
====
. Lit.: “Sabá”.
====

[[v18-1-16]]

^<<v18-1-16,16>>^ Falando ainda este, chegou outro e passou a dizer: “O próprio fogo de Deus caiu dos céus e passou a arder entre as ovelhas e os ajudantes, e foi consumi-los; e consegui escapar, somente eu sozinho, para te contar [isso].”

[[v18-1-17]]

^<<v18-1-17,17>>^ Falando ainda este, chegou outro e passou a dizer: “Os caldeus constituíram três bandos e foram investir contra os camelos e tomá-los, e aos ajudantes golpearam com o fio da espada; e consegui escapar, somente eu sozinho, para te contar [isso].”

[[v18-1-18]]

^<<v18-1-18,18>>^ Falando ainda este, chegou ainda outro e passou a dizer: “Teus filhos e tuas filhas estavam comendo e bebendo vinho na casa de seu irmão, o primogênito.

[[v18-1-19]]

^<<v18-1-19,19>>^ E eis que veio um grande vento^&#42;1^ desde a região do ermo e passou a golpear os quatro cantos da casa, de modo que ela caiu sobre a gente moça e eles morreram. E consegui escapar, somente eu sozinho, para te contar [isso].”

[NOTE]
====
. “Vento.” Hebr.: rú·ahh. Veja Gên 1:2 n.: “ativa”.
====

[[v18-1-20]]

^<<v18-1-20,20>>^ E Jó passou a levantar-se e a rasgar a sua túnica sem mangas, e a raspar a cabeça, e a lançar-se por terra, e a curvar-se,

[[v18-1-21]]

^<<v18-1-21,21>>^ e passou a dizer:
“Nu saí do ventre de minha mãe
E nu voltarei para lá.
O próprio Jeová deu e o próprio Jeová tirou.
Continue a ser abençoado o nome de Jeová.”

[[v18-1-22]]

^<<v18-1-22,22>>^ Em tudo isso Jó não pecou, nem atribuiu a Deus algo impróprio.

'''

xref:017-ester/017-ester-010.adoc#v17-10-0[&#60; Capítulo Anterior] | <<v18-1-0,Topo>> | xref:018-jo/018-jo-002.adoc#v18-2-0[Próximo Capítulo &#62;]