include::./index.adoc[]

[[v18-21-0]]
=== Jó, 21
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v18-21-1]]

^<<v18-21-1,1>>^ E Jó passou a responder e a dizer:

[[v18-21-2]]

^<<v18-21-2,2>>^ “Escutai atentamente a minha palavra,
E torne-se isto a vossa consolação.

[[v18-21-3]]

^<<v18-21-3,3>>^ Suportai-me, e eu mesmo falarei;
E depois de eu falar, [cada um de vós] pode caçoar.

[[v18-21-4]]

^<<v18-21-4,4>>^ Quanto a mim, acaso [expresso] a minha preocupação ao homem?
Ou por que é que meu espírito não fica impaciente?

[[v18-21-5]]

^<<v18-21-5,5>>^ Virai as vossas faces para mim e olhai assombrados,
E ponde a mão sobre a boca.

[[v18-21-6]]

^<<v18-21-6,6>>^ E quando me lembrei, também fiquei perturbado,
E um estremecimento se apoderou da minha carne.

[[v18-21-7]]

^<<v18-21-7,7>>^ Por que é que os próprios iníquos continuam vivendo,
Têm envelhecido, também se tornaram superiores em riqueza?

[[v18-21-8]]

^<<v18-21-8,8>>^ Sua descendência está firmemente estabelecida com eles à sua vista,
E seus descendentes, diante dos seus olhos.

[[v18-21-9]]

^<<v18-21-9,9>>^ Suas casas são a própria paz, livres de pavor,
E a vara de Deus^&#42;1^ não está sobre eles.

[NOTE]
====
. “Deus.” Hebr.: ’Elóh·ah. Veja 3:4 n.
====

[[v18-21-10]]

^<<v18-21-10,10>>^ Seu próprio touro realmente fecunda e não desperdiça sêmen;
Sua vaca tem cria e não sofre aborto.

[[v18-21-11]]

^<<v18-21-11,11>>^ Continuam enviando seus garotos iguais a um rebanho,
E seus próprios meninos estão saltitando.

[[v18-21-12]]

^<<v18-21-12,12>>^ Continuam a elevar [a sua voz] com o pandeiro e a harpa,
E prosseguem alegrando-se ao som do pífaro.

[[v18-21-13]]

^<<v18-21-13,13>>^ Passam bem os seus dias,
E num instante baixam ao Seol.

[[v18-21-14]]

^<<v18-21-14,14>>^ E eles dizem ao [verdadeiro] Deus: ‘Desvia-te de nós!
E não nos agradamos no conhecimento dos teus caminhos.

[[v18-21-15]]

^<<v18-21-15,15>>^ Que é o Todo-poderoso, para que o sirvamos,^&#42;1^
E que nos aproveita termos entrado em contato com ele?’

[NOTE]
====
. Ou “que o adoremos (lhe prestemos serviço sagrado)”. Hebr.: na·‛av·dhén·nu.
====

[[v18-21-16]]

^<<v18-21-16,16>>^ Eis que seu bem-estar não está no seu próprio poder.^&#42;1^
O próprio conselho dos iníquos se manteve longe de mim.

[NOTE]
====
. Lit.: “mão”.
====

[[v18-21-17]]

^<<v18-21-17,17>>^ Quantas vezes se apaga a lâmpada dos iníquos,
E [quantas vezes] vem sobre eles o seu desastre?
Na sua ira, [quantas vezes] reparte ele a destruição?

[[v18-21-18]]

^<<v18-21-18,18>>^ Ficam eles como palha diante do vento,^&#42;1^
E como a pragana furtada pelo tufão?

[NOTE]
====
. “Vento.” Hebr.: rú·ahh; gr.: a·né·mou; lat.: vén·ti.
====

[[v18-21-19]]

^<<v18-21-19,19>>^ O próprio Deus^&#42;1^ guardará o prejudicial [do homem] para os próprios filhos dele;
Recompensá-lo-á para que saiba [isso].

[NOTE]
====
. “Deus.” Hebr.: ’Elóh·ah.
====

[[v18-21-20]]

^<<v18-21-20,20>>^ Seus olhos verão a sua decadência,
E beberá do furor do Todo-poderoso.

[[v18-21-21]]

^<<v18-21-21,21>>^ Pois, qual será seu agrado na sua casa depois dele,
Quando o número dos seus meses será realmente cortado em dois?

[[v18-21-22]]

^<<v18-21-22,22>>^ Ensinará ele conhecimento até mesmo a Deus,^&#42;1^
Quando é Este quem julga os elevados?

[NOTE]
====
. “Até mesmo a Deus.” Hebr.: hal·’Él. Veja 22:2 n.: “Deus”.
====

[[v18-21-23]]

^<<v18-21-23,23>>^ Ele mesmo morrerá durante a sua plena auto-suficiência,
Quando estiver inteiramente despreocupado e tranqüilo;

[[v18-21-24]]

^<<v18-21-24,24>>^ [Quando] as suas próprias coxas tiverem ficado cheias de gordura,
E o próprio tutano dos seus ossos for mantido úmido.

[[v18-21-25]]

^<<v18-21-25,25>>^ E este outro morrerá com alma amargurada,
Não tendo comido de coisas boas.

[[v18-21-26]]

^<<v18-21-26,26>>^ Juntos se deitarão no pó,
E os próprios gusanos formarão uma coberta sobre eles.

[[v18-21-27]]

^<<v18-21-27,27>>^ Eis que conheço bem os vossos pensamentos
E os desígnios com que pretendeis agir violentamente contra mim.

[[v18-21-28]]

^<<v18-21-28,28>>^ Pois dizeis: ‘Onde está a casa do nobre,
E onde está a tenda, os tabernáculos dos iníquos?’

[[v18-21-29]]

^<<v18-21-29,29>>^ Não perguntastes aos que viajam pelas estradas?
E não inspecionais cuidadosamente os próprios sinais deles,

[[v18-21-30]]

^<<v18-21-30,30>>^ Que no dia de desastre se poupa o mau,
Que ele é liberto^&#42;1^ no dia da fúria?

[NOTE]
====
. “Ele é liberto”, mediante uma correção; M: “levado”, como no v. 32.
====

[[v18-21-31]]

^<<v18-21-31,31>>^ Quem o informará na sua própria face sobre o seu caminho?
E quem o recompensará pelo que ele mesmo fez?

[[v18-21-32]]

^<<v18-21-32,32>>^ Quanto a ele, será levado ao cemitério,
E se fará vigília sobre um túmulo.^&#42;1^

[NOTE]
====
. Ou “monte de feixes”.
====

[[v18-21-33]]

^<<v18-21-33,33>>^ Para ele, os torrões de terra dum vale de torrente certamente se tornarão doces,
E arrastará atrás de si toda a humanidade,^&#42;1^
E os antes dele foram inúmeros.

[NOTE]
====
. Ou “todo homem terreno”. Hebr.: kol-’a·dhám.
====

[[v18-21-34]]

^<<v18-21-34,34>>^ Portanto, quão inutilmente tentais consolar-me,
E as vossas próprias réplicas deveras permanecem como infidelidade!”

'''

xref:018-jo/018-jo-020.adoc#v18-20-0[&#60; Capítulo Anterior] | <<v18-21-0,Topo>> | xref:018-jo/018-jo-022.adoc#v18-22-0[Próximo Capítulo &#62;]