include::./index.adoc[]

[[v18-33-0]]
=== Jó, 33
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v18-33-1]]

^<<v18-33-1,1>>^ “Agora, porém, ó Jó, por favor, ouve as minhas palavras,^&#42;1^
E dá ouvidos a tudo o que eu falar.^&#42;2^

[NOTE]
====
. “Minhas palavras.” Hebr.: mil·laí.
. Lit.: “[todas as] minhas palavras”. Hebr.: deva·raí.
====

[[v18-33-2]]

^<<v18-33-2,2>>^ Por favor, eis que tenho de abrir minha boca;
Minha língua com meu palato tem de falar.

[[v18-33-3]]

^<<v18-33-3,3>>^ Minhas declarações são a retidão de meu coração,
E conhecimento é o que meus lábios enunciam sinceramente.

[[v18-33-4]]

^<<v18-33-4,4>>^ O próprio espírito de Deus^&#42;1^ me fez
E o fôlego do próprio Todo-poderoso passou a fazer-me viver.

[NOTE]
====
. Lit.: “O . . . espírito de Deus.” Hebr.: ru·ahh-’Él.
====

[[v18-33-5]]

^<<v18-33-5,5>>^ Se puderes, replica-me,
Enfileira [palavras] diante de mim; toma deveras a tua posição.

[[v18-33-6]]

^<<v18-33-6,6>>^ Eis que sou para o [verdadeiro] Deus exatamente o que tu és;
Também eu fui moldado do barro.

[[v18-33-7]]

^<<v18-33-7,7>>^ Eis que nenhuma terribilidade minha te apavorará
E nenhuma pressão da minha parte pesará sobre ti.

[[v18-33-8]]

^<<v18-33-8,8>>^ Apenas tu disseste aos meus ouvidos,
E eu ouvia o som das [tuas] palavras:

[[v18-33-9]]

^<<v18-33-9,9>>^ ‘Sou puro, sem transgressão;
Estou limpo, não tenho erro.

[[v18-33-10]]

^<<v18-33-10,10>>^ Eis que ele acha ensejo para oposição contra mim,
Toma-me por inimigo seu.

[[v18-33-11]]

^<<v18-33-11,11>>^ Põe os meus pés no tronco,
Vigia todas as minhas veredas.’

[[v18-33-12]]

^<<v18-33-12,12>>^ Eis que nisto não tiveste razão, respondo-te eu;
Porque Deus^&#42;1^ é muito mais do que um homem mortal.

[NOTE]
====
. “Deus.” Hebr.: ’Elóh·ah.
====

[[v18-33-13]]

^<<v18-33-13,13>>^ Por que é que contendeste com ele,
Porque não responde a todas as tuas palavras?

[[v18-33-14]]

^<<v18-33-14,14>>^ Porque Deus^&#42;1^ fala uma vez
E duas vezes — embora não se repare nisso —

[NOTE]
====
. “Deus.” Hebr.: ’El.
====

[[v18-33-15]]

^<<v18-33-15,15>>^ Num sonho, numa visão da noite,
Quando profundo sono cai sobre os homens
Durante os cochilos sobre a cama.

[[v18-33-16]]

^<<v18-33-16,16>>^ É então que ele destapa o ouvido dos homens
E apõe seu selo à exortação [dada] a eles,

[[v18-33-17]]

^<<v18-33-17,17>>^ Para desviar o homem^&#42;1^ do seu ato
E para encobrir do varão vigoroso^&#42;2^ o próprio orgulho.

[NOTE]
====
. Ou “o homem terreno”. Hebr.: ’a·dhám.
. “Do varão vigoroso.” Hebr.: mig·gé·ver.
====

[[v18-33-18]]

^<<v18-33-18,18>>^ Refreia a sua alma de [ir à] cova
E sua vida de desaparecer por meio duma arma de arremesso.^&#42;1^

[NOTE]
====
. “De desaparecer por meio duma arma de arremesso.” BHK propõe correções que fariam isso rezar: “de passar para o Seol”, paralelizando assim com “cova” na primeira parte do v.
====

[[v18-33-19]]

^<<v18-33-19,19>>^ E ele é deveras repreendido com dor sobre a sua cama,
E a altercação dos seus ossos é contínua.

[[v18-33-20]]

^<<v18-33-20,20>>^ E sua vida certamente torna o pão repugnante
E a sua própria alma, comida desejável.

[[v18-33-21]]

^<<v18-33-21,21>>^ Sua carne se definha diante da vista
E seus ossos que não se viam certamente ficam expostos.

[[v18-33-22]]

^<<v18-33-22,22>>^ E sua alma se chega à cova
E sua vida aos que infligem a morte.^&#42;1^

[NOTE]
====
. “Aos que infligem a morte.” Mediante uma correção do M: “aos mortos”, ou: “ao lugar dos mortos”.
====

[[v18-33-23]]

^<<v18-33-23,23>>^ Se há para ele um mensageiro,^&#42;1^
Um porta-voz,^&#42;2^ um dentre mil,
Para contar ao homem a sua retidão,^&#42;3^

[NOTE]
====
. Ou “um anjo”. Lat.: án·ge·lus.
. Ou “um intérprete”.
. “Sua retidão”, M; LXX: “sua própria culpa. Ele mostrará a sua falta de entendimento”.
====

[[v18-33-24]]

^<<v18-33-24,24>>^ Então ele o favorece e diz:
‘Isenta-o de descer à cova!
Achei um resgate!^&#42;1^

[NOTE]
====
. Ou “cobertura”. Hebr.: khó·fer.
====

[[v18-33-25]]

^<<v18-33-25,25>>^ Torne-se a sua carne mais fresca do que na infância;
Volte ele aos dias do seu vigor juvenil.’

[[v18-33-26]]

^<<v18-33-26,26>>^ Suplicará a Deus^&#42;1^ para que tenha prazer nele,
E verá a sua face com gritos de alegria,
E Ele restituirá a Sua justiça ao homem mortal.^&#42;2^

[NOTE]
====
. “Deus.” Hebr.: ’Elóh·ah; LXX: “Jeová”.
. “Ao homem mortal.” Hebr.: le·’enóhsh.
====

[[v18-33-27]]

^<<v18-33-27,27>>^ Cantará para os homens e dirá:
‘Pequei; e perverti o que era reto
E certamente isso não era próprio para mim.

[[v18-33-28]]

^<<v18-33-28,28>>^ Ele remiu a minha^&#42;1^ alma de passar para a cova,
E a minha própria vida verá a luz.’

[NOTE]
====
. “Minha”, MLXXSy; MmargemTVg: “sua”.
====

[[v18-33-29]]

^<<v18-33-29,29>>^ Eis que todas estas são as coisas que Deus^&#42;1^ realiza,
Duas vezes, três vezes, no caso dum varão vigoroso,

[NOTE]
====
. “Deus.” Hebr.: ’El.
====

[[v18-33-30]]

^<<v18-33-30,30>>^ Para fazer a sua alma recuar da cova,
Para que fique esclarecido com a luz^&#42;1^ dos viventes.

[NOTE]
====
. Segundo M; Sy: “para ver a luz”.
====

[[v18-33-31]]

^<<v18-33-31,31>>^ Presta atenção, ó Jó! Escuta-me!
Cala-te, e eu mesmo continuarei a falar.

[[v18-33-32]]

^<<v18-33-32,32>>^ Se houver quaisquer palavras [para dizer], replica-me;
Fala, pois me agradei da tua justiça.

[[v18-33-33]]

^<<v18-33-33,33>>^ Se não houver nenhuma, escuta-me tu mesmo;
Cala-te, e eu te ensinarei sabedoria.”

'''

xref:018-jo/018-jo-032.adoc#v18-32-0[&#60; Capítulo Anterior] | <<v18-33-0,Topo>> | xref:018-jo/018-jo-034.adoc#v18-34-0[Próximo Capítulo &#62;]