include::./index.adoc[]

[[v18-19-0]]
=== Jó, 19
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v18-19-1]]

^<<v18-19-1,1>>^ E Jó passou a responder e a dizer:

[[v18-19-2]]

^<<v18-19-2,2>>^ “Até quando ficareis irritando a minha alma
E esmigalhando-me com palavras?

[[v18-19-3]]

^<<v18-19-3,3>>^ Estas dez vezes passastes a reprovar-me;
Não vos envergonhais de me tratar tão duramente.

[[v18-19-4]]

^<<v18-19-4,4>>^ E admitindo-se que eu tenha cometido um engano,
É comigo que se hospedará meu engano.^&#42;1^

[NOTE]
====
. LXX acrescenta: “por dizer algo que não era necessário, e minhas declarações (pronunciações) estão enganadas (erram) e não são oportunas (a propósito)”.
====

[[v18-19-5]]

^<<v18-19-5,5>>^ Se é de fato contra mim que assumis ares de grandeza,
E mostrais que o vitupério contra mim é próprio,

[[v18-19-6]]

^<<v18-19-6,6>>^ Sabei, então, que o próprio Deus^&#42;1^ me desencaminhou,
E sua rede para caçar se fechou sobre mim.

[NOTE]
====
. “Deus.” Hebr.: ’Elóh·ah, sing. de ’Elo·hím.
====

[[v18-19-7]]

^<<v18-19-7,7>>^ Eis que estou clamando: ‘Violência!’ mas não obtenho resposta;
Estou clamando por ajuda, mas não há justiça.

[[v18-19-8]]

^<<v18-19-8,8>>^ A própria vereda me tem sido bloqueada com um muro de pedras, e não posso passar;
E ele põe a própria escuridão sobre as minhas sendas.

[[v18-19-9]]

^<<v18-19-9,9>>^ Despiu-me da minha própria glória,
E tira-me a coroa da cabeça.

[[v18-19-10]]

^<<v18-19-10,10>>^ Demole-me por todos os lados e eu me vou embora;
E arranca a minha esperança como a uma árvore.

[[v18-19-11]]

^<<v18-19-11,11>>^ Também a sua ira se acende contra mim,
E ele me considera como seu adversário.

[[v18-19-12]]

^<<v18-19-12,12>>^ Suas tropas chegam unidas e aterram seu caminho contra mim,
E acampam-se ao redor da minha tenda.

[[v18-19-13]]

^<<v18-19-13,13>>^ A meus próprios irmãos ele pôs longe de mim,
E até os que me conhecem se alhearam de mim.

[[v18-19-14]]

^<<v18-19-14,14>>^ Meus conhecidos íntimos^&#42;1^ deixaram de existir,
E os que eu conheço esqueceram-se de mim,

[NOTE]
====
. Ou: “Meus parentes.”
====

[[v18-19-15]]

^<<v18-19-15,15>>^ Os que residem como forasteiros na minha casa; e as minhas próprias escravas me consideram como estranho;
Tornei-me um verdadeiro estrangeiro aos seus olhos.

[[v18-19-16]]

^<<v18-19-16,16>>^ Chamei o meu servo, mas ele não responde.
Com a minha própria boca imploro-lhe compaixão.

[[v18-19-17]]

^<<v18-19-17,17>>^ Meu próprio hálito^&#42;1^ se tornou nojento para minha esposa,
E eu me tornei fedorento para os filhos do ventre de minha [mãe].

[NOTE]
====
. “Meu . . . hálito (espírito).” Hebr.: ru·hhí; lat.: há·li·tum.
====

[[v18-19-18]]

^<<v18-19-18,18>>^ Também os próprios garotos me rejeitaram;
Basta eu me levantar, e começam a falar contra mim.

[[v18-19-19]]

^<<v18-19-19,19>>^ Todos os homens do meu grupo íntimo me detestam,
E os que eu amava se viraram contra mim.

[[v18-19-20]]

^<<v18-19-20,20>>^ Meus ossos realmente se apegam à minha pele e à minha carne,
E eu escapo com a pele dos meus dentes.^&#42;1^

[NOTE]
====
. “E minha carne fica calva nos meus dentes”, mediante outra derivação do verbo e com algumas correções do M. Veja 13:14.
====

[[v18-19-21]]

^<<v18-19-21,21>>^ Mostrai-me um pouco de favor, mostrai-me um pouco de favor, companheiros meus,
Porque a própria mão de Deus^&#42;1^ me tocou.

[NOTE]
====
. “De Deus.” Hebr.: ’Elóh·ah.
====

[[v18-19-22]]

^<<v18-19-22,22>>^ Por que continuais a perseguir-me assim como Deus^&#42;1^ faz,
E não ficais satisfeitos com a minha própria carne?

[NOTE]
====
. “Deus.” Hebr.: ’El.
====

[[v18-19-23]]

^<<v18-19-23,23>>^ Quem dera agora que as minhas palavras fossem assentadas por escrito!
Quem dera que fossem inscritas num livro!

[[v18-19-24]]

^<<v18-19-24,24>>^ Com um estilo de ferro e [com] chumbo,
Que fossem talhadas na rocha para sempre!

[[v18-19-25]]

^<<v18-19-25,25>>^ E eu mesmo bem sei que meu redentor^&#42;1^ está vivo,
E que, vindo depois [de mim], levantar-se-á sobre [o] pó.

[NOTE]
====
. “Meu redentor (resgatador).” Ampliando-se a idéia: “meu vingador (vindicador)”. Hebr.: gó·’ali; lat.: re·dém·ptor. Veja Núm 35:21; Sal 19:14; Pr 23:11; Is 63:16; Je 50:34.
====

[[v18-19-26]]

^<<v18-19-26,26>>^ E depois da minha pele, [que] esfolaram — isto!
Ainda que reduzido na minha carne,^&#42;1^ observarei a Deus,^&#42;2^

[NOTE]
====
. Lit.: “Ainda que fora da minha carne”, ou: “Ainda à parte da minha carne.”
. “Deus.” Hebr.: ’Elóh·ah.
====

[[v18-19-27]]

^<<v18-19-27,27>>^ A quem até mesmo eu observarei,
E [a quem] os meus próprios olhos hão de ver, mas não algum estranho.
Meus rins falharam no meu íntimo.

[[v18-19-28]]

^<<v18-19-28,28>>^ Pois vós dizeis: ‘Por que continuamos a persegui-lo?’
Quando a própria raiz da questão se acha em mim.^&#42;1^

[NOTE]
====
. Segundo M; LXX: “acharemos nele”.
====

[[v18-19-29]]

^<<v18-19-29,29>>^ Amedrontai-vos por causa duma espada,
Porque a espada significa furor contra os erros,
A fim de que saibais que há um juiz.”^&#42;1^

[NOTE]
====
. “Há um juiz”, T, e mediante sinais vocálicos diferentes no M (veja 1Sa 24:15); outros lhe dão a versão: “há um Todo-poderoso”.
====

'''

xref:018-jo/018-jo-018.adoc#v18-18-0[&#60; Capítulo Anterior] | <<v18-19-0,Topo>> | xref:018-jo/018-jo-020.adoc#v18-20-0[Próximo Capítulo &#62;]