include::./index.adoc[]

[[v18-39-0]]
=== Jó, 39
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v18-39-1]]

^<<v18-39-1,1>>^ “Ficaste conhecendo o tempo fixo de parirem as cabras-montesas do rochedo?
Observas tu exatamente quando é que as corças têm cria com dores?

[[v18-39-2]]

^<<v18-39-2,2>>^ Contas tu os meses lunares que cumprem
Ou vieste saber o tempo fixo de parirem?

[[v18-39-3]]

^<<v18-39-3,3>>^ Dobram-se para ter suas crias,
Livrando-se das suas dores cruciantes.^&#42;1^

[NOTE]
====
. Ou “soltando seus fetos”.
====

[[v18-39-4]]

^<<v18-39-4,4>>^ Seus filhotes se tornam robustos, crescem no campo aberto;
Deveras saem e não retornam a elas.

[[v18-39-5]]

^<<v18-39-5,5>>^ Quem pôs em liberdade a zebra,
E quem soltou as próprias ligaduras do jumento selvagem,

[[v18-39-6]]

^<<v18-39-6,6>>^ Ao qual designei por casa a planície desértica
E por sua moradia a terra salgada?

[[v18-39-7]]

^<<v18-39-7,7>>^ Ri-se do tumulto da vila;
Não ouve os ruídos do batedor.

[[v18-39-8]]

^<<v18-39-8,8>>^ Explora os montes pelo seu pasto
E busca toda sorte de planta verde.

[[v18-39-9]]

^<<v18-39-9,9>>^ Acaso quererá servir-te o touro selvagem,
Ou pernoitará ele junto à tua manjedoura?

[[v18-39-10]]

^<<v18-39-10,10>>^ Acaso atarás o touro selvagem ao sulco, com as suas cordas,
Ou gradará ele as baixadas atrás de ti?

[[v18-39-11]]

^<<v18-39-11,11>>^ Confiarás nele por ser abundante em poder
E deixarás para ele a tua labuta?

[[v18-39-12]]

^<<v18-39-12,12>>^ Acaso te fiarás nele, que te traga de volta a tua semente
E que ajunte à tua eira?

[[v18-39-13]]

^<<v18-39-13,13>>^ Acaso a asa da fêmea de avestruz bateu alegremente,
Ou [tem ela] as plumas duma cegonha e a plumagem?

[[v18-39-14]]

^<<v18-39-14,14>>^ Pois ela deixa seus ovos na própria terra
E os mantém quentes no pó,

[[v18-39-15]]

^<<v18-39-15,15>>^ E se esquece que algum pé pode esmagá-los
Ou mesmo uma fera do campo pode trilhá-los.

[[v18-39-16]]

^<<v18-39-16,16>>^ Trata rudemente os seus filhotes, como se não fossem seus —
Sua labuta é em vão, [porque não tem] pavor.

[[v18-39-17]]

^<<v18-39-17,17>>^ Porque Deus^&#42;1^ a fez esquecer a sabedoria
E não lhe deu parte na compreensão.

[NOTE]
====
. “Deus.” Hebr.: ’Elóh·ah.
====

[[v18-39-18]]

^<<v18-39-18,18>>^ No tempo em que bate [as asas] alto
Ela se ri do cavalo e do seu cavaleiro.

[[v18-39-19]]

^<<v18-39-19,19>>^ Podes dar potência ao cavalo?
Podes vestir seu pescoço com uma crina farfalhante?^&#42;1^

[NOTE]
====
. “Crina farfalhante”, M; T: “força”.
====

[[v18-39-20]]

^<<v18-39-20,20>>^ Podes fazê-lo pular como um gafanhoto?
A dignidade do seu resfôlego é aterradora.

[[v18-39-21]]

^<<v18-39-21,21>>^ Escarva^&#42;1^ na baixada e exulta em poder;
Sai para enfrentar armamento.

[NOTE]
====
. “Escarva”, LXXSyVg; M: “Escarvam.”
====

[[v18-39-22]]

^<<v18-39-22,22>>^ Ri-se do pavor e não está aterrorizado;
Nem retrocede por causa duma espada.

[[v18-39-23]]

^<<v18-39-23,23>>^ Sobre ele chocalha a aljava,
A lâmina duma lança e um dardo.

[[v18-39-24]]

^<<v18-39-24,24>>^ Com retumbo e agitação devora a terra,
E não acredita que seja o som duma buzina.

[[v18-39-25]]

^<<v18-39-25,25>>^ Assim que toca a buzina diz: Eia!
E de longe cheira a batalha,
A algazarra dos chefes^&#42;1^ e o grito de guerra.

[NOTE]
====
. Lit.: “príncipes”. Hebr.: sa·rím.
====

[[v18-39-26]]

^<<v18-39-26,26>>^ É devido à tua compreensão que esvoaça o falcão,
Que ele estende suas asas ao vento sulino?

[[v18-39-27]]

^<<v18-39-27,27>>^ Ou é às tuas ordens que a águia voa para cima
E que constrói o seu ninho no alto,

[[v18-39-28]]

^<<v18-39-28,28>>^ Que ela reside num rochedo e passa a noite
No pico dum rochedo e num lugar inacessível?

[[v18-39-29]]

^<<v18-39-29,29>>^ De lá tem de ir em busca de alimento;
Seus olhos olham para longe.

[[v18-39-30]]

^<<v18-39-30,30>>^ E seus próprios filhotes sorvem sangue;
E onde há os que foram mortos, ali está ela.”

'''

xref:018-jo/018-jo-038.adoc#v18-38-0[&#60; Capítulo Anterior] | <<v18-39-0,Topo>> | xref:018-jo/018-jo-040.adoc#v18-40-0[Próximo Capítulo &#62;]