include::./index.adoc[]

[[v18-42-0]]
=== Jó, 42
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v18-42-1]]

^<<v18-42-1,1>>^ E Jó passou a responder a Jeová e a dizer:

[[v18-42-2]]

^<<v18-42-2,2>>^ “Fiquei sabendo que és capaz de fazer todas as coisas,
E não há idéia que te seja inalcançável.

[[v18-42-3]]

^<<v18-42-3,3>>^ ‘Quem é este que está obscurecendo o conselho sem conhecimento?’
Por isso falei, mas não estava entendendo
Coisas maravilhosas demais para mim, as quais não conheço.

[[v18-42-4]]

^<<v18-42-4,4>>^ ‘Ouve, por favor, e eu mesmo falarei.
Eu te perguntarei e tu mo farás saber.’

[[v18-42-5]]

^<<v18-42-5,5>>^ Em rumores^&#42;1^ ouvi a teu respeito,
Mas agora é o meu próprio olho que te vê.

[NOTE]
====
. Ou: “Num relato para o ouvido.”
====

[[v18-42-6]]

^<<v18-42-6,6>>^ Por isso faço uma retratação
E deveras me arrependo^&#42;1^ em pó e cinzas.”

[NOTE]
====
. Ou “deploro”.
====

[[v18-42-7]]

^<<v18-42-7,7>>^ E sucedeu que, depois de Jeová ter falado estas palavras a Jó, Jeová passou a dizer a Elifaz, o temanita:
“Minha ira se acendeu contra ti e contra os teus dois companheiros, pois não falastes a verdade a meu respeito assim como fez meu servo Jó.

[[v18-42-8]]

^<<v18-42-8,8>>^ E agora, tomai para vós sete novilhos e sete carneiros, e ide ao meu servo Jó, e tereis de oferecer um sacrifício queimado em vosso próprio favor; e o próprio Jó, meu servo, orará por vós. Somente aceitarei a face dele, para não cometer uma ignominiosa insensatez convosco, pois não falastes a verdade a meu respeito assim como fez meu servo Jó.”

[[v18-42-9]]

^<<v18-42-9,9>>^ Por conseguinte, Elifaz, o temanita, e Bildade, o suíta, [e] Zofar, o naamatita, foram e fizeram assim como Jeová lhes falara; e, assim, Jeová aceitou a face de Jó.

[[v18-42-10]]

^<<v18-42-10,10>>^ E o próprio Jeová fez recuar a condição cativa de Jó quando ele orou a favor dos seus companheiros, e, adicionalmente, Jeová começou a dar em dobro tudo o que fora de Jó.

[[v18-42-11]]

^<<v18-42-11,11>>^ E foram ter com ele todos os seus irmãos e todas as suas irmãs, e todos os que antes o conheciam, e começaram a comer pão com ele na sua casa, e a compadecer-se dele, e a consolá-lo por toda a calamidade que Jeová deixara vir sobre ele; e passaram, cada um, a dar-lhe uma peça de dinheiro,^&#42;1^ e, cada um, uma argola de ouro.

[NOTE]
====
. Lit.: “dar-lhe um qesitah”. Moeda de valor desconhecido.
====

[[v18-42-12]]

^<<v18-42-12,12>>^ Quanto a Jeová, ele abençoou o fim posterior de Jó mais do que seu princípio, de modo que veio a ter quatorze mil ovelhas,^&#42;1^ e seis mil camelos, e mil juntas de gado vacum, e mil jumentas.

[NOTE]
====
. Veja 1:3 n.: “ovelhas”.
====

[[v18-42-13]]

^<<v18-42-13,13>>^ Veio a ter também sete filhos e três filhas.

[[v18-42-14]]

^<<v18-42-14,14>>^ E ele foi chamar a primeira pelo nome de Jemima, e a segunda pelo nome de Quezia, e a terceira pelo nome de Querém-Hapuque.

[[v18-42-15]]

^<<v18-42-15,15>>^ E não se achavam em todo o país mulheres mais bonitas do que as filhas de Jó, e seu pai passou a dar-lhes uma herança entre os seus irmãos.

[[v18-42-16]]

^<<v18-42-16,16>>^ Depois disso Jó continuou a viver por cento e quarenta anos,^&#42;1^ e chegou a ver seus filhos e seus netos — quatro gerações.

[NOTE]
====
. “Mas Jó viveu depois da praga cento e setenta anos; todos os [anos] que ele viveu foram duzentos e quarenta e oito [LXX‏,אB omitem “oito”] anos”, LXX.
====

[[v18-42-17]]

^<<v18-42-17,17>>^ E por fim morreu Jó, velho e saciado de dias.^&#42;1^

[NOTE]
====
. LXX acrescenta: “E escreveu-se que ele se levantará de novo junto com aqueles que Jeová levantar. Este [homem] é descrito no livro siríaco como residindo na terra de Ausitis [Uz], nas fronteiras da Iduméia e da Arábia. E seu nome era anteriormente Jobabe. Depois de tomar uma esposa árabe, tornou-se pai dum filho cujo nome era Enom. Mas ele mesmo era filho de seu pai Zare, filho dos filhos de Esaú, mas [filho] de sua mãe Bosorra, de modo que era o quinto [na linhagem] de Abraão. E estes são os reis que reinavam em Edom, país de que ele também era governante: primeiro, Balaque, filho de Beor, e o nome de sua cidade era Denaba; mas depois de Balaque, Jobabe, o chamado Jó; mas depois deste, Asom, era governador desde o país de Taimanitis; mas depois deste, Adade, filho de Barade, que decepou Madiã na planície de Moabe, e o nome de sua cidade era Getaim. Mas os amigos que vieram a ele [eram] Elifaz, dos filhos de Esaú, rei dos taimanitas; Bildade, governante absoluto dos saucaianos; Zofar, rei dos minaianos.”
====

'''

xref:018-jo/018-jo-041.adoc#v18-41-0[&#60; Capítulo Anterior] | <<v18-42-0,Topo>> | xref:019-salmo/019-salmo-001.adoc#v19-1-0[Próximo Capítulo &#62;]