include::./index.adoc[]

[[v18-18-0]]
=== Jó, 18
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v18-18-1]]

^<<v18-18-1,1>>^ E Bildade, o suíta, passou a responder e a dizer:

[[v18-18-2]]

^<<v18-18-2,2>>^ “Até quando levareis para pôr fim às palavras?
Deveis entender, para depois falarmos.

[[v18-18-3]]

^<<v18-18-3,3>>^ Por que deveríamos ser considerados como animais
[E] tomados por impuros aos vossos olhos?

[[v18-18-4]]

^<<v18-18-4,4>>^ Ele dilacera a sua alma na sua ira.
Por tua causa, acaso será abandonada a terra,
Ou uma rocha mudada do seu lugar?

[[v18-18-5]]

^<<v18-18-5,5>>^ Também será apagada a luz dos iníquos,
E não resplandecerá a faísca do seu fogo.

[[v18-18-6]]

^<<v18-18-6,6>>^ A própria luz se há de escurecer na sua tenda,
E nela a sua própria lâmpada se apagará.

[[v18-18-7]]

^<<v18-18-7,7>>^ Seus passos de vigor^&#42;1^ ficarão tolhidos.
Até mesmo seu conselho o lançará fora.

[NOTE]
====
. Ou “poder mágico”.
====

[[v18-18-8]]

^<<v18-18-8,8>>^ Pois, deveras se deixará que entre com os pés numa rede de caça,
E ele pisará numa rede.

[[v18-18-9]]

^<<v18-18-9,9>>^ Uma armadilha [o] segurará pelo calcanhar;
Uma esparrela o detém.

[[v18-18-10]]

^<<v18-18-10,10>>^ Uma corda para ele está encoberta na terra,
E uma laçada para ele na [sua] senda.

[[v18-18-11]]

^<<v18-18-11,11>>^ Em todo o redor, terrores repentinos certamente o assustarão
E deveras lhe acossarão os pés.

[[v18-18-12]]

^<<v18-18-12,12>>^ Seu vigor fica faminto,
E o desastre está pronto para fazê-lo mancar.

[[v18-18-13]]

^<<v18-18-13,13>>^ Comerá os pedaços da sua pele;^&#42;1^
O primogênito da morte^&#42;2^ comerá os seus membros.

[NOTE]
====
. “Sua pele será consumida pela doença”, mediante uma ligeira correção do M.
. “O primogênito da morte”, isto é, a doença mais mortífera.
====

[[v18-18-14]]

^<<v18-18-14,14>>^ Sua confiança será arrancada da sua própria tenda
E o fará marchar até o rei dos terrores.

[[v18-18-15]]

^<<v18-18-15,15>>^ Na sua tenda residirá algo que não é seu;
Espalhar-se-á enxofre sobre o seu próprio lugar de permanência.

[[v18-18-16]]

^<<v18-18-16,16>>^ Embaixo se secarão as suas próprias raízes,
E em cima, seu ramo murchará.

[[v18-18-17]]

^<<v18-18-17,17>>^ A própria menção dele há de perecer da terra,
E ele não terá nome lá fora na rua.

[[v18-18-18]]

^<<v18-18-18,18>>^ Empurrá-lo-ão da luz para a escuridão,
E afugentá-lo-ão do solo produtivo.^&#42;1^

[NOTE]
====
. “E . . . do solo produtivo.” Hebr.: u·mit·te·vél; lat.: et de ór·be, “e do círculo [terrestre]”.
====

[[v18-18-19]]

^<<v18-18-19,19>>^ Não terá progênie nem posteridade entre o seu povo,
E não haverá sobrevivente no seu lugar de residência como forasteiro.

[[v18-18-20]]

^<<v18-18-20,20>>^ O povo no Ocidente deveras olhará assombrado para o seu dia,
E certamente se apoderará um arrepio até mesmo do povo no Oriente.

[[v18-18-21]]

^<<v18-18-21,21>>^ Somente estes são os tabernáculos dum contraventor,
E este é o lugar de alguém que não conhece a Deus.”^&#42;1^

[NOTE]
====
. “Deus.” Hebr.: ’El.
====

'''

xref:018-jo/018-jo-017.adoc#v18-17-0[&#60; Capítulo Anterior] | <<v18-18-0,Topo>> | xref:018-jo/018-jo-019.adoc#v18-19-0[Próximo Capítulo &#62;]