include::./index.adoc[]

[[v54-4-0]]
=== 1 Timóteo, 4
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v54-4-1]]

^<<v54-4-1,1>>^ No entanto, a pronunciação inspirada^&#42;1^ diz definitivamente que nos períodos posteriores de tempo alguns se desviarão da fé, prestando atenção a desencaminhantes pronunciações inspiradas^&#42;2^ e a ensinos de demônios,

[NOTE]
====
. Ou “o espírito”.
. Ou “espíritos desencaminhantes”.
====

[[v54-4-2]]

^<<v54-4-2,2>>^ pela hipocrisia de homens que falam mentiras, marcados na sua consciência como que por um ferro de marcar;

[[v54-4-3]]

^<<v54-4-3,3>>^ proibindo o casar-se, mandando abster-se de alimentos que Deus criou para serem tomados com agradecimentos pelos que têm fé e que conhecem a verdade de modo exato.

[[v54-4-4]]

^<<v54-4-4,4>>^ A razão disso é que cada criação de Deus é excelente, e nada deve ser rejeitado se for recebido com agradecimento,

[[v54-4-5]]

^<<v54-4-5,5>>^ porque é santificado^&#42;1^ pela palavra de Deus e pela oração sobre [ele].

[NOTE]
====
. Ou “é tido por sagrado; é tratado como santo”. Gr.: ha·gi·á·ze·tai; lat.: sanc·ti·fi·cá·tur; J17(hebr.): yequd·dásh.
====

[[v54-4-6]]

^<<v54-4-6,6>>^ Por dares tais conselhos aos irmãos, serás ministro excelente de Cristo Jesus, nutrido com as palavras da fé e do ensino excelente que seguiste de perto.

[[v54-4-7]]

^<<v54-4-7,7>>^ Mas recusa as histórias falsas que violam o que é santo e que são contadas por mulheres velhas. Por outro lado, treina-te com a devoção piedosa^&#42;1^ por teu alvo.

[NOTE]
====
. “Devoção piedosa”, אAVg; J7,8: “temor de Jeová”.
====

[[v54-4-8]]

^<<v54-4-8,8>>^ Pois o treinamento corporal^&#42;1^ é proveitoso para pouca coisa, mas a devoção piedosa^&#42;2^ é proveitosa para todas as coisas, visto que tem a promessa da vida agora e daquela que há de vir.

[NOTE]
====
. Lit.: “a ginástica”. Gr.: gy·mna·sí·a; lat.: ex·er·ci·tá·ti·o, “exercício”.
. “Devoção piedosa”, אAVg; J7,8: “temor de Jeová”.
====

[[v54-4-9]]

^<<v54-4-9,9>>^ Fiel e merecedora de plena aceitação é essa declaração.

[[v54-4-10]]

^<<v54-4-10,10>>^ Pois, para este fim estamos trabalhando arduamente e nos esforçamos, porque baseamos a nossa esperança num Deus vivente, que é Salvador de toda sorte de homens, especialmente dos fiéis.

[[v54-4-11]]

^<<v54-4-11,11>>^ Persiste em dar estas ordens e em ensiná-las.

[[v54-4-12]]

^<<v54-4-12,12>>^ Nenhum homem jamais menospreze a tua mocidade. Ao contrário, torna-te exemplo para os fiéis, no falar, na conduta, no amor, na fé, na castidade.

[[v54-4-13]]

^<<v54-4-13,13>>^ Até eu chegar, continua a aplicar-te à leitura pública, à exortação, ao ensino.

[[v54-4-14]]

^<<v54-4-14,14>>^ Não negligencies o dom em ti, que te foi dado por intermédio duma predição e quando o corpo de anciãos^&#42;1^ pôs as suas mãos sobre ti.

[NOTE]
====
. “Corpo de anciãos.” Gr.: pre·sby·te·rí·ou; J17,18(hebr.): haz·zeqe·ním, “os anciãos”. Veja Núm 11:25.
====

[[v54-4-15]]

^<<v54-4-15,15>>^ Pondera estas coisas; absorve-te nelas, para que o teu progresso seja manifesto a todos.

[[v54-4-16]]

^<<v54-4-16,16>>^ Presta constante atenção a ti mesmo e ao teu ensino. Permanece nestas coisas, pois, por fazeres isso, salvarás tanto a ti mesmo como aos que te escutam.

'''

xref:054-1-timoteo/054-1-timoteo-003.adoc#v54-3-0[&#60; Capítulo Anterior] | <<v54-4-0,Topo>> | xref:054-1-timoteo/054-1-timoteo-005.adoc#v54-5-0[Próximo Capítulo &#62;]