include::./index.adoc[]

[[v54-6-0]]
=== 1 Timóteo, 6
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v54-6-1]]

^<<v54-6-1,1>>^ Tantos quantos forem escravos debaixo dum jugo estejam considerando os seus donos dignos de plena honra, para que nunca se fale de modo ultrajante do nome de Deus e do ensino.

[[v54-6-2]]

^<<v54-6-2,2>>^ Além disso, os que tiverem donos crentes não os menosprezem, porque são irmãos. Ao contrário, sejam escravos com tanto mais prontidão, porque os que recebem o proveito do seu bom serviço^&#42;1^ são crentes e amados.
Persiste em ensinar estas coisas e em dar estas exortações.

[NOTE]
====
. “Os que recebem o proveito do seu bom serviço”, אA; J7,8: “os que participam do bom de Jeová na terra”.
====

[[v54-6-3]]

^<<v54-6-3,3>>^ Se algum homem ensinar outra doutrina e não concordar com palavras salutares, as de nosso Senhor Jesus Cristo, nem com o ensino concordante com a devoção piedosa,^&#42;1^

[NOTE]
====
. “Devoção piedosa”, אAVg; J7,8: “temor de Jeová”.
====

[[v54-6-4]]

^<<v54-6-4,4>>^ ele está enfunado [de orgulho], não entendendo nada, mas tendo mania de criar questões e debates sobre palavras. Destas coisas procedem inveja, rixa, linguagem ultrajante, suspeitas iníquas,

[[v54-6-5]]

^<<v54-6-5,5>>^ disputas violentas sobre ninharias,^&#42;1^ da parte de homens corrompidos na mente e espoliados da verdade, pensando que a devoção piedosa é meio de ganho.

[NOTE]
====
. Ou “irritações mútuas”.
====

[[v54-6-6]]

^<<v54-6-6,6>>^ Decerto, é meio de grande ganho, [esta] devoção piedosa^&#42;1^ junto com a auto-suficiência.^&#42;2^

[NOTE]
====
. “Devoção piedosa”, אAVg; J7,8: “temor de Jeová”.
. Ou “com contentamento”.
====

[[v54-6-7]]

^<<v54-6-7,7>>^ Pois não trouxemos nada ao mundo, nem podemos levar nada embora.

[[v54-6-8]]

^<<v54-6-8,8>>^ Assim, tendo sustento e com que nos cobrir, estaremos contentes com estas coisas.

[[v54-6-9]]

^<<v54-6-9,9>>^ No entanto, os que estão resolvidos a ficar ricos caem em tentação e em laço, e em muitos desejos insensatos e nocivos, que lançam os homens na destruição e na ruína.

[[v54-6-10]]

^<<v54-6-10,10>>^ Porque o amor ao dinheiro é raiz de toda sorte de coisas prejudiciais,^&#42;1^ e alguns, por procurarem alcançar este amor, foram desviados da fé e se traspassaram todo com muitas dores.

[NOTE]
====
. Ou “de todas as coisas prejudiciais”.
====

[[v54-6-11]]

^<<v54-6-11,11>>^ No entanto, tu, ó homem de Deus, foge destas coisas. Mas empenha-te pela justiça, pela devoção piedosa,^&#42;1^ pela fé, pelo amor, pela perseverança, pela brandura de temperamento.

[NOTE]
====
. “Devoção piedosa”, אAVgSyp; J7,8: “temor de Jeová”.
====

[[v54-6-12]]

^<<v54-6-12,12>>^ Trava a luta excelente da fé,^&#42;1^ apega-te firmemente à vida eterna para a qual foste chamado e fizeste uma excelente declaração pública diante de muitas testemunhas.

[NOTE]
====
. Ou: “Contende pela vitória na competição correta da fé.”
====

[[v54-6-13]]

^<<v54-6-13,13>>^ À vista de Deus, que preserva vivas todas as coisas,^&#42;1^ e de Cristo Jesus,^&#42;2^ que, como testemunha, fez a excelente declaração pública perante Pôncio Pilatos, dou-te ordens

[NOTE]
====
. Ou “que faz viver todas as coisas”.
. Veja Ap. 6E.
====

[[v54-6-14]]

^<<v54-6-14,14>>^ para que observes o mandamento dum modo imaculado e irrepreensível, até a manifestação de nosso Senhor Jesus Cristo.

[[v54-6-15]]

^<<v54-6-15,15>>^ Esta [manifestação], o feliz e único Potentado mostrará nos seus próprios tempos designados, [ele,] o Rei dos que reinam e Senhor dos que dominam,

[[v54-6-16]]

^<<v54-6-16,16>>^ o único que tem imortalidade,^&#42;1^ que mora em luz inacessível, a quem nenhum dos homens tem visto nem pode ver. A ele seja honra e poderio eterno. Amém.

[NOTE]
====
. “Imortalidade.” Gr.: a·tha·na·sí·an; lat.: in·mor·ta·li·tá·tem.
====

[[v54-6-17]]

^<<v54-6-17,17>>^ Dá ordens aos que são ricos no atual sistema de coisas,^&#42;1^ que não sejam soberbos^&#42;2^ e que não baseiem a sua esperança nas riquezas incertas, mas em Deus, que nos fornece ricamente todas as coisas para o nosso usufruto;

[NOTE]
====
. Ou “ordem de coisas”. Gr.: ai·ó·ni; lat.: saé·cu·li; J17,18,22(hebr.): ha·‛oh·lám, “a ordem de coisas”.
. Ou “orgulhosos; arrogantes”.
====

[[v54-6-18]]

^<<v54-6-18,18>>^ para praticarem o bem, para serem ricos em obras excelentes, para serem liberais, prontos para partilhar,

[[v54-6-19]]

^<<v54-6-19,19>>^ entesourando para si seguramente um alicerce excelente para o futuro, a fim de que se apeguem firmemente à verdadeira vida.

[[v54-6-20]]

^<<v54-6-20,20>>^ Ó Timóteo, guarda o que te foi confiado, desviando-te dos falatórios vãos, que violam o que é santo, e das contradições do falsamente chamado “conhecimento”.

[[v54-6-21]]

^<<v54-6-21,21>>^ Por ostentarem tal [conhecimento], alguns se desviaram da fé.
A benignidade imerecida seja convosco.

'''

xref:054-1-timoteo/054-1-timoteo-005.adoc#v54-5-0[&#60; Capítulo Anterior] | <<v54-6-0,Topo>> | xref:055-2-timoteo/055-2-timoteo-001.adoc#v55-1-0[Próximo Capítulo &#62;]