include::./index.adoc[]

[[v54-2-0]]
=== 1 Timóteo, 2
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v54-2-1]]

^<<v54-2-1,1>>^ Exorto, portanto, em primeiro lugar, a que se façam súplicas, orações, intercessões [e] se dêem agradecimentos com respeito a^&#42;1^ toda sorte de homens,

[NOTE]
====
. Ou “a favor de”.
====

[[v54-2-2]]

^<<v54-2-2,2>>^ com respeito a reis e a todos os em altos postos, a fim de que continuemos a levar uma vida calma e sossegada, com plena devoção piedosa^&#42;1^ e seriedade.

[NOTE]
====
. “Devoção piedosa”, אAVg; J7,8: “temor de Jeová”.
====

[[v54-2-3]]

^<<v54-2-3,3>>^ Isto é excelente e aceitável à vista de nosso Salvador, Deus,

[[v54-2-4]]

^<<v54-2-4,4>>^ cuja vontade é que toda sorte de homens sejam salvos e venham a ter um conhecimento exato da verdade.

[[v54-2-5]]

^<<v54-2-5,5>>^ Pois há um só Deus e um só mediador entre Deus e homens, um homem, Cristo Jesus,

[[v54-2-6]]

^<<v54-2-6,6>>^ o qual se entregou como resgate correspondente^&#42;1^ por todos^&#42;2^ — [isto é] o que se há de testemunhar nos seus próprios tempos específicos.

[NOTE]
====
. “Resgate correspondente.” Gr.: an·tí·ly·tron (de an·tí, “contra; correspondente a; em lugar de”, e lý·tron, “resgate [preço pago]”). Veja Mt 20:28 n.: “resgate”.
. Ou “toda sorte de pessoas”.
====

[[v54-2-7]]

^<<v54-2-7,7>>^ Para dar este testemunho é que fui designado pregador e apóstolo — estou dizendo a verdade, não estou mentindo — instrutor de nações no assunto da fé e da verdade.

[[v54-2-8]]

^<<v54-2-8,8>>^ Desejo, portanto, que em todo lugar os homens façam orações, erguendo mãos leais, sem furor e [sem] debates.

[[v54-2-9]]

^<<v54-2-9,9>>^ Igualmente, desejo que as mulheres se adornem em vestido bem arrumado, com modéstia e bom juízo, não com estilos de trançados dos cabelos, e com ouro, ou pérolas, ou vestimenta muito cara,

[[v54-2-10]]

^<<v54-2-10,10>>^ mas dum modo próprio das mulheres que professam reverenciar a Deus,^&#42;1^ a saber, por intermédio de boas obras.

[NOTE]
====
. “Reverenciar a Deus”, אA; J7,8: “[ter] temor de Jeová”.
====

[[v54-2-11]]

^<<v54-2-11,11>>^ A mulher aprenda em silêncio^&#42;1^ com plena submissão.

[NOTE]
====
. Ou “sossego”.
====

[[v54-2-12]]

^<<v54-2-12,12>>^ Não permito que a mulher ensine ou exerça autoridade sobre o homem, mas que esteja em silêncio.

[[v54-2-13]]

^<<v54-2-13,13>>^ Porque Adão foi formado primeiro, depois Eva.

[[v54-2-14]]

^<<v54-2-14,14>>^ Também, Adão não foi enganado, mas a mulher foi totalmente enganada e veio a estar em transgressão.

[[v54-2-15]]

^<<v54-2-15,15>>^ No entanto, ela ficará a salvo^&#42;1^ por dar à luz filhos, desde que continuem na fé, e no amor, e na santificação junto com bom juízo.

[NOTE]
====
. Ou “será salva”.
====

'''

xref:054-1-timoteo/054-1-timoteo-001.adoc#v54-1-0[&#60; Capítulo Anterior] | <<v54-2-0,Topo>> | xref:054-1-timoteo/054-1-timoteo-003.adoc#v54-3-0[Próximo Capítulo &#62;]