include::./index.adoc[]

[[v54-5-0]]
=== 1 Timóteo, 5
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v54-5-1]]

^<<v54-5-1,1>>^ Não critiques severamente um ancião.^&#42;1^ Ao contrário, suplica-lhe como a um pai, os homens mais jovens, como a irmãos,

[NOTE]
====
. “Ancião.” Gr.: pre·sby·té·roi, dativo, sing.
====

[[v54-5-2]]

^<<v54-5-2,2>>^ as mulheres mais idosas, como a mães, as mulheres mais jovens, como a irmãs, com toda a castidade.

[[v54-5-3]]

^<<v54-5-3,3>>^ Honra as viúvas que são realmente viúvas.

[[v54-5-4]]

^<<v54-5-4,4>>^ Mas, se alguma viúva tiver filhos ou netos, que estes aprendam primeiro a praticar a devoção piedosa^&#42;1^ na sua própria família e a estar pagando a devida compensação aos seus pais e avós, pois isto é aceitável à vista de Deus.

[NOTE]
====
. “Devoção piedosa”, אA; J7,8: “sabedoria e temor de Jeová”.
====

[[v54-5-5]]

^<<v54-5-5,5>>^ Ora, a mulher que for realmente viúva e que tiver ficado sem recursos tem posto a sua esperança em Deus e persiste em súplicas e em orações, noite e dia.

[[v54-5-6]]

^<<v54-5-6,6>>^ Mas aquela que se entrega à satisfação sensual já está morta, embora esteja vivendo.

[[v54-5-7]]

^<<v54-5-7,7>>^ Portanto, persiste em dar estas ordens, para que sejam irrepreensíveis.

[[v54-5-8]]

^<<v54-5-8,8>>^ Certamente, se alguém não fizer provisões para os seus próprios, e especialmente para os membros de sua família, tem repudiado a fé e é pior do que alguém sem fé.^&#42;1^

[NOTE]
====
. “Alguém sem fé”, אAVgSyp; J13,14,18: “alguém que renegou a Jeová”.
====

[[v54-5-9]]

^<<v54-5-9,9>>^ Seja colocada na lista a viúva que não tiver menos de sessenta anos de idade, esposa de um só marido,

[[v54-5-10]]

^<<v54-5-10,10>>^ dando-se dela testemunho de obras excelentes, se tiver criado filhos, se tiver hospedado estranhos, se tiver lavado os pés dos santos, se tiver socorrido os em tribulação, se tiver seguido diligentemente toda boa obra.

[[v54-5-11]]

^<<v54-5-11,11>>^ Por outro lado, rejeita as viúvas mais jovens, pois, quando os seus impulsos sexuais se interpõem entre elas e o Cristo, querem casar-se,

[[v54-5-12]]

^<<v54-5-12,12>>^ sofrendo julgamento por terem desconsiderado a sua primeira [expressão de] fé.

[[v54-5-13]]

^<<v54-5-13,13>>^ Ao mesmo tempo, aprendem também a estar desocupadas, vadiando pelas casas; sim, [e] não somente desocupadas, mas também tagarelas e intrometidas nos assuntos dos outros, falando de coisas de que não deviam.

[[v54-5-14]]

^<<v54-5-14,14>>^ Portanto, desejo que as viúvas mais jovens se casem, que tenham filhos, que cuidem duma família, não dando induzimento ao opositor para injuriar.

[[v54-5-15]]

^<<v54-5-15,15>>^ De fato, algumas já se desviaram para seguir a Satanás.

[[v54-5-16]]

^<<v54-5-16,16>>^ Se alguma mulher crente tiver viúvas,^&#42;1^ que ela as socorra e a congregação não fique sob o fardo. Esta poderá então socorrer as que são realmente viúvas.

[NOTE]
====
. “Viúvas”, isto é, parentas enlutadas.
====

[[v54-5-17]]

^<<v54-5-17,17>>^ Os anciãos, que presidem de modo excelente, sejam contados dignos de dupla honra, especialmente os que trabalham arduamente no falar e no ensinar.

[[v54-5-18]]

^<<v54-5-18,18>>^ Porque a escritura diz: “Não deves açaimar o touro quando debulha o grão”; também: “O trabalhador é digno do seu salário.”

[[v54-5-19]]

^<<v54-5-19,19>>^ Não admitas acusação contra um ancião,^&#42;1^ exceto baseado na evidência de duas ou três testemunhas.

[NOTE]
====
. “Ancião.” Gr.: pre·sby·té·rou.
====

[[v54-5-20]]

^<<v54-5-20,20>>^ Repreende perante todos os espectadores aqueles que praticam o pecado, para que os demais também tenham temor.

[[v54-5-21]]

^<<v54-5-21,21>>^ Eu te mando solenemente, perante Deus, e Cristo Jesus,^&#42;1^ e os anjos escolhidos, que guardes estas coisas sem preconceito, não fazendo nada por parcialidade.

[NOTE]
====
. Veja Ap. 6E.
====

[[v54-5-22]]

^<<v54-5-22,22>>^ Nunca ponhas as mãos apressadamente sobre nenhum homem; tampouco sejas partícipe dos pecados de outros; mantém-te casto.

[[v54-5-23]]

^<<v54-5-23,23>>^ Não bebas mais água, mas usa de um pouco de vinho por causa do teu estômago e dos teus freqüentes casos de doença.

[[v54-5-24]]

^<<v54-5-24,24>>^ Os pecados de alguns homens manifestam-se publicamente, conduzindo diretamente ao julgamento, mas, quanto a outros homens, [os pecados deles] também se tornam manifestos mais tarde.

[[v54-5-25]]

^<<v54-5-25,25>>^ Do mesmo modo também se manifestam publicamente as obras excelentes, e as que são diferentes não podem ficar escondidas.

'''

xref:054-1-timoteo/054-1-timoteo-004.adoc#v54-4-0[&#60; Capítulo Anterior] | <<v54-5-0,Topo>> | xref:054-1-timoteo/054-1-timoteo-006.adoc#v54-6-0[Próximo Capítulo &#62;]