include::./index.adoc[]

[[v44-21-0]]
=== Atos, 21
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v44-21-1]]

^<<v44-21-1,1>>^ Então, tendo-nos separado deles a muito custo e feito ao mar, tomamos um rumo direto e chegamos a Cós, mas no [dia] seguinte a Rodes, e dali a Pátara.

[[v44-21-2]]

^<<v44-21-2,2>>^ E, quando achamos um barco que ia cruzar para a Fenícia, embarcamos e zarpamos.

[[v44-21-3]]

^<<v44-21-3,3>>^ Tendo avistado a [ilha de] Chipre, deixamo-la atrás, pela esquerda, e navegamos para a Síria e tocamos em Tiro, pois o barco ia desembarcar [a sua] carga.

[[v44-21-4]]

^<<v44-21-4,4>>^ Procurando, achamos os discípulos e permanecemos ali sete dias. Mas eles, por intermédio do espírito, disseram repetidas vezes a Paulo que não pusesse pé em Jerusalém.

[[v44-21-5]]

^<<v44-21-5,5>>^ Assim, ao completarmos os dias, partimos e iniciamos a viagem; todos eles, porém, junto com as mulheres e os filhos, acompanharam-nos para fora da cidade. E, ajoelhados na praia, fizemos oração

[[v44-21-6]]

^<<v44-21-6,6>>^ e nos despedimos uns dos outros, e subimos ao barco, mas eles voltaram para os seus lares.

[[v44-21-7]]

^<<v44-21-7,7>>^ Completamos então a viagem desde Tiro e chegamos a Ptolemaida, e cumprimentamos os irmãos e ficamos um dia com eles.

[[v44-21-8]]

^<<v44-21-8,8>>^ No dia seguinte partimos e chegamos a Cesaréia, e entramos na casa de Filipe, o evangelizador,^&#42;1^ que era um dos sete homens, e ficamos com ele.

[NOTE]
====
. Ou “missionário”. Gr.: eu·ag·ge·li·stoú; lat.: e·van·ge·lí·stae.
====

[[v44-21-9]]

^<<v44-21-9,9>>^ Este homem tinha quatro filhas, virgens, que profetizavam.

[[v44-21-10]]

^<<v44-21-10,10>>^ Mas, ao permanecermos ali muitos dias, desceu da Judéia certo profeta de nome Ágabo,

[[v44-21-11]]

^<<v44-21-11,11>>^ e ele veio ter conosco e tomou o cinto de Paulo, amarrou os seus próprios pés e mãos, e disse: “Assim diz o espírito santo: ‘Ao homem a quem pertence este cinto, os judeus amarrarão desta maneira em Jerusalém e o entregarão às mãos de pessoas das nações.’”

[[v44-21-12]]

^<<v44-21-12,12>>^ Ora, quando ouvimos isso, tanto nós como os daquele lugar começamos a suplicar-lhe que não subisse a Jerusalém.

[[v44-21-13]]

^<<v44-21-13,13>>^ Paulo respondeu então: “Que estais fazendo, chorando e enfraquecendo o meu coração? Ficai certos de que estou pronto não só para ser amarrado, mas também para morrer em Jerusalém pelo nome do Senhor Jesus.”

[[v44-21-14]]

^<<v44-21-14,14>>^ Quando ele não se deixou dissuadir, assentimos com as palavras: “Realize-se a vontade de Jeová.”^&#42;1^

[NOTE]
====
. Veja Ap. 1D.
====

[[v44-21-15]]

^<<v44-21-15,15>>^ Então, depois daqueles dias, preparamo-nos para a viagem e começamos a subir a Jerusalém.

[[v44-21-16]]

^<<v44-21-16,16>>^ Alguns dos discípulos de Cesaréia, porém, foram também conosco, para nos levar ao homem em cujo lar íamos ser hospedados, certo Mnáson, de Chipre, antigo discípulo.

[[v44-21-17]]

^<<v44-21-17,17>>^ Ao chegarmos a Jerusalém, os irmãos nos receberam de bom grado.

[[v44-21-18]]

^<<v44-21-18,18>>^ Mas no [dia] seguinte, Paulo foi conosco ter com Tiago; e todos os anciãos estavam presentes.^&#42;1^

[NOTE]
====
. Ou “compareceram”.
====

[[v44-21-19]]

^<<v44-21-19,19>>^ E ele cumprimentou-os e começou a dar em pormenores um relato das coisas que Deus fizera entre as nações por intermédio do ministério dele.

[[v44-21-20]]

^<<v44-21-20,20>>^ Ouvindo isso, começaram a glorificar a Deus, e disseram-lhe: “Observas, irmão, quantos milhares^&#42;1^ de crentes há entre os judeus; e todos eles são zelosos da Lei.

[NOTE]
====
. Lit.: “miríades; dezenas de milhares”.
====

[[v44-21-21]]

^<<v44-21-21,21>>^ Mas eles ouviram rumores a respeito de ti, de que tens ensinado a todos os judeus entre as nações uma apostasia^&#42;1^ contra Moisés, dizendo-lhes que não circuncidem os seus filhos nem andem nos costumes [solenes].

[NOTE]
====
. “Uma apostasia.” Gr.: a·po·sta·sí·an (do verbo a·fí·ste·mi, “apartar-se de”). O substantivo tem o sentido de deserção, abandono ou rebeldia (rebelião). Veja Jos 22:22; 2Cr 29:19; 2Te 2:3.
====

[[v44-21-22]]

^<<v44-21-22,22>>^ O que se há de fazer, então, a respeito disso? Em qualquer caso, eles vão ouvir que chegaste.

[[v44-21-23]]

^<<v44-21-23,23>>^ Faze, portanto, o que te vamos dizer: Há conosco quatro homens que têm um voto sobre si.

[[v44-21-24]]

^<<v44-21-24,24>>^ Toma contigo estes homens e purifica-te cerimonialmente junto com eles, e toma conta das despesas deles, para que se lhes rape a cabeça. E todos saberão assim que não há nada nos rumores que se contavam acerca de ti, mas que estás andando ordeiramente, guardando também tu mesmo a Lei.

[[v44-21-25]]

^<<v44-21-25,25>>^ Quanto aos crentes dentre as nações, já avisamos,^&#42;1^ dando a nossa decisão, de que se guardem do que é sacrificado a ídolos, bem como do sangue e do estrangulado,^&#42;2^ e da fornicação.”

[NOTE]
====
. Lit.: “enviamos”, BD; P74אAVg: “escrevemos”.
. Ou “do que é morto sem ser sangrado”.
====

[[v44-21-26]]

^<<v44-21-26,26>>^ Paulo tomou então consigo os homens, no dia seguinte, e purificou-se cerimonialmente junto com eles, e entrou no templo, notificando os dias a serem cumpridos para a purificação cerimonial, até se apresentar a oferta para cada um deles.

[[v44-21-27]]

^<<v44-21-27,27>>^ Ora, quando os sete dias estavam para se concluir, os judeus da Ásia, observando-o no templo, começaram a lançar toda a multidão em confusão, e deitaram mãos nele,

[[v44-21-28]]

^<<v44-21-28,28>>^ clamando: “Homens de Israel, acudi! Este é o homem que ensina a todos em toda a parte contra o povo, e a Lei, e este lugar, e, ainda mais, ele até mesmo trouxe gregos ao templo e aviltou este santo lugar.”

[[v44-21-29]]

^<<v44-21-29,29>>^ Porque previamente tinham visto Trófimo, o efésio, na cidade com ele, mas estavam imaginando que Paulo o havia trazido ao templo.

[[v44-21-30]]

^<<v44-21-30,30>>^ E toda a cidade ficou em alvoroço e houve uma afluência do povo; e agarraram Paulo e o arrastaram para fora do templo. E fecharam-se imediatamente as portas.

[[v44-21-31]]

^<<v44-21-31,31>>^ E enquanto buscavam matá-lo, o comandante^&#42;1^ do destacamento recebeu informação de que toda a Jerusalém estava em confusão;

[NOTE]
====
. Lit.: “quiliarca”, comandante de 1.000 soldados.
====

[[v44-21-32]]

^<<v44-21-32,32>>^ e ele tomou imediatamente soldados e oficiais do exército,^&#42;1^ e desceu correndo até eles. Quando avistaram o comandante militar e os soldados, deixaram de espancar Paulo.

[NOTE]
====
. Lit.: “centuriões”, oficiais comandantes de 100 soldados.
====

[[v44-21-33]]

^<<v44-21-33,33>>^ O comandante militar chegou-se então perto, agarrou-o e mandou que fosse amarrado com duas cadeias; e passou a indagar quem ele era e o que tinha feito.

[[v44-21-34]]

^<<v44-21-34,34>>^ Mas alguns da multidão começaram a gritar uma coisa e outros outra. Assim, não podendo por si mesmo saber nada de certo, por causa do tumulto, mandou que fosse levado ao quartel.

[[v44-21-35]]

^<<v44-21-35,35>>^ Mas, quando ele subia as escadas, a situação ficou tal, que estava sendo carregado pelos soldados, por causa da violência da multidão;

[[v44-21-36]]

^<<v44-21-36,36>>^ pois a multidão do povo seguia, clamando: “Fora com ele!”^&#42;1^

[NOTE]
====
. Ou: “Mata-o!”
====

[[v44-21-37]]

^<<v44-21-37,37>>^ E, quando estava para ser levado para dentro do quartel, Paulo disse ao comandante militar: “É-me permitido dizer-te algo?” Ele disse: “Sabes falar grego?

[[v44-21-38]]

^<<v44-21-38,38>>^ Não és tu realmente o egípcio que antes destes dias atiçou uma sedição e levou quatro mil faquistas^&#42;1^ para o ermo?”

[NOTE]
====
. Lit.: “sicários; assassinos”. Gr.: si·ka·rí·on.
====

[[v44-21-39]]

^<<v44-21-39,39>>^ Paulo disse então: “Sou, de fato, judeu, de Tarso, na Cilícia, cidadão duma cidade nada obscura. Rogo-te, portanto, que me permitas falar ao povo.”

[[v44-21-40]]

^<<v44-21-40,40>>^ Tendo-lhe ele dado permissão, Paulo, de pé na escadaria, fez sinal com a mão para o povo. Quando se fez um grande silêncio, dirigiu-se a eles no idioma hebraico, dizendo:

'''

xref:044-atos/044-atos-020.adoc#v44-20-0[&#60; Capítulo Anterior] | <<v44-21-0,Topo>> | xref:044-atos/044-atos-022.adoc#v44-22-0[Próximo Capítulo &#62;]