include::./index.adoc[]

[[v44-5-0]]
=== Atos, 5
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v44-5-1]]

^<<v44-5-1,1>>^ No entanto, certo homem, de nome Ananias, junto com Safira, sua esposa, vendeu uma propriedade

[[v44-5-2]]

^<<v44-5-2,2>>^ e reteve secretamente parte do preço, sabendo disso também a sua esposa, e trouxe apenas parte e a depositou aos pés dos apóstolos.

[[v44-5-3]]

^<<v44-5-3,3>>^ Mas Pedro disse: “Ananias, por que te afoitou^&#42;1^ Satanás a trapacear o espírito santo e a reter secretamente parte do preço do campo?

[NOTE]
====
. Lit.: “te encheu o coração”. Veja Est 7:5; Ec 8:11.
====

[[v44-5-4]]

^<<v44-5-4,4>>^ Enquanto permanecia contigo, não permanecia teu, e depois de ter sido vendido, não continuou a estar sob o teu controle? Por que é que propuseste uma ação dessas no teu coração? Trapaceaste, não homens, mas a Deus.”

[[v44-5-5]]

^<<v44-5-5,5>>^ Ao ouvir estas palavras, Ananias caiu e expirou. E veio grande temor sobre todos os que ouviram isso.

[[v44-5-6]]

^<<v44-5-6,6>>^ Mas os homens mais jovens levantaram-se, enrolaram-no em panos e o levaram para fora, e o enterraram.

[[v44-5-7]]

^<<v44-5-7,7>>^ Ora, depois de um intervalo de cerca de três horas entrou a esposa dele, não sabendo o que tinha acontecido.

[[v44-5-8]]

^<<v44-5-8,8>>^ Pedro disse-lhe: “Dize-me, vendestes vós [dois] o campo por tanto?” Ela disse: “Sim, por tanto.”

[[v44-5-9]]

^<<v44-5-9,9>>^ Pedro [disse-]lhe então: “Por que concordastes entre vós [dois] fazer uma prova com o espírito de Jeová?^&#42;1^ Eis que estão à porta os pés dos que enterraram teu marido, e eles te levarão para fora.”

[NOTE]
====
. Veja Ap. 1D.
====

[[v44-5-10]]

^<<v44-5-10,10>>^ Ela caiu instantaneamente aos pés dele e expirou. Quando os jovens entraram, acharam-na morta, e levaram-na para fora e a enterraram ao lado de seu marido.

[[v44-5-11]]

^<<v44-5-11,11>>^ Conseqüentemente, veio grande temor sobre toda a congregação^&#42;1^ e sobre todos os que ouviram estas coisas.

[NOTE]
====
. Lit.: “eclésia”. Gr.: ek·kle·sí·an; lat.: ec·clé·si·a; J17,18(hebr.): haq·qa·hál, “a congregação”.
====

[[v44-5-12]]

^<<v44-5-12,12>>^ Além disso, por intermédio das mãos dos apóstolos continuavam a ocorrer muitos sinais e portentos entre o povo; e todos eles estavam de comum acordo na colunata de Salomão.

[[v44-5-13]]

^<<v44-5-13,13>>^ Verdadeiramente, nem um só dos outros tinha a coragem de se juntar a eles; não obstante, o povo os afamava.

[[v44-5-14]]

^<<v44-5-14,14>>^ Mais do que isso, os crentes no Senhor continuavam a ser acrescidos, multidões [deles], tanto de homens como de mulheres;

[[v44-5-15]]

^<<v44-5-15,15>>^ de modo que traziam para fora os doentes, até mesmo às ruas largas, e os deitavam ali em pequenas camas e macas, a fim de que, quando Pedro estivesse passando, pelo menos a sua sombra caísse sobre alguns deles.

[[v44-5-16]]

^<<v44-5-16,16>>^ Também a multidão das cidades em volta de Jerusalém afluía, trazendo os doentes e os afligidos por espíritos impuros, e todos eles eram curados.

[[v44-5-17]]

^<<v44-5-17,17>>^ Mas, levantando-se o sumo sacerdote e todos os com ele, a então existente seita dos saduceus, ficaram cheios de ciúme,

[[v44-5-18]]

^<<v44-5-18,18>>^ e deitaram mãos nos apóstolos e os puseram no lugar público de detenção.

[[v44-5-19]]

^<<v44-5-19,19>>^ Mas, durante a noite, o anjo de Jeová^&#42;1^ abriu as portas da prisão, trouxe-os para fora e disse:

[NOTE]
====
. Veja Ap. 1D.
====

[[v44-5-20]]

^<<v44-5-20,20>>^ “Ide embora, e, tendo tomado posição no templo, persisti em falar ao povo [sobre] todas as declarações a respeito desta vida.”

[[v44-5-21]]

^<<v44-5-21,21>>^ Depois de ouvirem isso, entraram no templo de madrugada e começaram a ensinar.
Ora, chegando o sumo sacerdote e os com ele, convocaram o Sinédrio e toda a assembléia dos anciãos^&#42;1^ dos filhos de Israel, e mandaram trazê-los da cadeia.

[NOTE]
====
. Ou “e todo o Senado”.
====

[[v44-5-22]]

^<<v44-5-22,22>>^ Mas, ao chegarem lá os oficiais, não os acharam na prisão. Voltaram, assim, e relataram,

[[v44-5-23]]

^<<v44-5-23,23>>^ dizendo: “Encontramos a cadeia fechada com toda a segurança e os guardas postos às portas, mas, quando a abrimos, não achamos ninguém dentro.”

[[v44-5-24]]

^<<v44-5-24,24>>^ Ora, quando tanto o capitão do templo como os principais sacerdotes ouviram estas palavras, ficaram num aperto por causa destes assuntos, quanto a que se daria.

[[v44-5-25]]

^<<v44-5-25,25>>^ Mas, chegou certo homem e relatou-lhes: “Eis que os homens que pusestes na prisão estão no templo, em pé, e ensinando o povo.”

[[v44-5-26]]

^<<v44-5-26,26>>^ O capitão foi então com os seus oficiais e passou a trazê-los, mas sem violência, visto que tinham medo de ser apedrejados pelo povo.

[[v44-5-27]]

^<<v44-5-27,27>>^ Trouxeram-nos assim e os postaram na sala do Sinédrio. E o sumo sacerdote interrogou-os,

[[v44-5-28]]

^<<v44-5-28,28>>^ dizendo: “Nós vos ordenamos positivamente que não ensinásseis à base deste nome, e, ainda assim, eis que enchestes Jerusalém com o vosso ensino, e estais resolvidos a trazer sobre nós o sangue deste homem.”

[[v44-5-29]]

^<<v44-5-29,29>>^ Em resposta, Pedro e os [outros] apóstolos disseram: “Temos de obedecer a Deus como governante antes que aos homens.

[[v44-5-30]]

^<<v44-5-30,30>>^ O Deus de nossos antepassados levantou Jesus, a quem matastes por pendurá-lo num madeiro.^&#42;1^

[NOTE]
====
. Ou “árvore”. Gr.: xý·lou; J22(hebr.): ‛ets. Veja 2:36 n.
====

[[v44-5-31]]

^<<v44-5-31,31>>^ Deus enalteceu a este, como Agente Principal e Salvador, para a sua direita, para dar a Israel arrependimento e perdão de pecados.

[[v44-5-32]]

^<<v44-5-32,32>>^ E nós somos testemunhas destes assuntos, e assim é também o espírito santo, que Deus tem dado aos que obedecem a ele como governante.”

[[v44-5-33]]

^<<v44-5-33,33>>^ Quando ouviram isso, sentiram-se profundamente feridos e queriam eliminá-los.

[[v44-5-34]]

^<<v44-5-34,34>>^ Mas, levantou-se certo homem no Sinédrio, um fariseu de nome Gamaliel, instrutor da Lei, estimado por todo o povo, e mandou que pusessem os homens para fora por um pouco de tempo.

[[v44-5-35]]

^<<v44-5-35,35>>^ E ele lhes disse: “Homens de Israel, prestai atenção a vós mesmos quanto ao que pretendeis fazer com respeito a estes homens.

[[v44-5-36]]

^<<v44-5-36,36>>^ Por exemplo, antes destes dias, levantou-se Teudas, dizendo ser alguém, e certo número de homens, cerca de quatrocentos, juntaram-se ao seu partido. Mas ele foi eliminado, e todos os que lhe obedeciam foram dispersos e redundaram em nada.

[[v44-5-37]]

^<<v44-5-37,37>>^ Depois dele levantou-se Judas, o galileu, nos dias do registro, e arrastou muitos após si. Contudo, esse homem pereceu, e todos os que lhe obedeciam foram espalhados.

[[v44-5-38]]

^<<v44-5-38,38>>^ E assim, na atual situação, digo-vos: Não vos metais com estes homens, mas deixai-os [em paz]; (porque, se este desígnio ou esta obra for de homens, será derrubada;

[[v44-5-39]]

^<<v44-5-39,39>>^ mas, se for de Deus, não podereis derrubá-los;) senão podereis talvez ser realmente achados como lutadores contra Deus.”

[[v44-5-40]]

^<<v44-5-40,40>>^ Em vista disso, atenderam-no e mandaram chamar os apóstolos, chibatearam-nos e ordenaram-lhes que parassem de falar à base do nome de Jesus, e soltaram-nos.

[[v44-5-41]]

^<<v44-5-41,41>>^ Estes, portanto, retiraram-se do Sinédrio, alegrando-se porque tinham sido considerados dignos de ser desonrados a favor do nome dele.

[[v44-5-42]]

^<<v44-5-42,42>>^ E cada dia, no templo e de casa em casa,^&#42;1^ continuavam sem cessar a ensinar e a declarar as boas novas^&#42;2^ a respeito do Cristo, Jesus.

[NOTE]
====
. Lit.: “segundo [a] casa”. Gr.: kat’ oí·kon. Aqui, ka·tá é usado com o acusativo sing. no sentido distributivo. R. C. H. Lenski, na sua obra The Interpretation of The Acts of the Apostles, Minneapolis, EUA (1961), fez o seguinte comentário sobre At 5:42: “Os apóstolos nem por um instante pararam a sua bendita obra. ‘Cada dia’ eles continuavam, e isto abertamente, ‘no Templo’, onde o Sinédrio e a polícia do Templo podiam vê-los e ouvi-los, e, naturalmente, também κατ’ οἵκον, que é distributivo, ‘de casa em casa’, e não meramente adverbial, ‘em casa’.”
. Ou “declarar o evangelho”. Gr.: eu·ag·ge·li·zó·me·noi; lat.: e·van·ge·li·zán·tes, “evangelizar”.
====

'''

xref:044-atos/044-atos-004.adoc#v44-4-0[&#60; Capítulo Anterior] | <<v44-5-0,Topo>> | xref:044-atos/044-atos-006.adoc#v44-6-0[Próximo Capítulo &#62;]