include::./index.adoc[]

[[v44-20-0]]
=== Atos, 20
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v44-20-1]]

^<<v44-20-1,1>>^ Então, tendo diminuído o alvoroço, Paulo mandou chamar os discípulos, e, tendo-os encorajado e despedindo-se deles, saiu a fim de viajar para a Macedônia.

[[v44-20-2]]

^<<v44-20-2,2>>^ Depois de percorrer aquelas regiões e encorajar com muitas palavras os que havia ali, foi à Grécia.

[[v44-20-3]]

^<<v44-20-3,3>>^ E, tendo passado ali três meses, visto que os judeus formavam uma conspiração contra ele quando estava para navegar para a Síria, resolveu voltar pela Macedônia.

[[v44-20-4]]

^<<v44-20-4,4>>^ Acompanhava-o Sópater, filho de Pirro, de Beréia, Aristarco e Segundo, dos tessalonicenses, e Gaio, de Derbe, e Timóteo, e, [do distrito] da Ásia, Tíquico e Trófimo.

[[v44-20-5]]

^<<v44-20-5,5>>^ Estes foram adiante e esperaram por nós em Trôade,

[[v44-20-6]]

^<<v44-20-6,6>>^ mas nós nos fizemos ao mar, de Filipos, depois dos dias dos pães não fermentados, e em cinco dias fomos ter com eles em Trôade; e passamos ali sete dias.

[[v44-20-7]]

^<<v44-20-7,7>>^ No primeiro dia da semana, quando estávamos ajuntados para uma refeição,^&#42;1^ Paulo começou a dissertar para eles, visto que ia partir no dia seguinte; e ele prolongou as suas palavras até à meia-noite.

[NOTE]
====
. Lit.: “para partir pão”.
====

[[v44-20-8]]

^<<v44-20-8,8>>^ De modo que havia várias lâmpadas no quarto de andar superior onde estávamos ajuntados.

[[v44-20-9]]

^<<v44-20-9,9>>^ Certo jovem, de nome Êutico, sentado à janela, foi tomado de sono profundo enquanto Paulo falava, e, caindo durante o sono, despenhou-se do terceiro pavimento e foi apanhado morto.

[[v44-20-10]]

^<<v44-20-10,10>>^ Mas Paulo desceu, lançou-se sobre ele, e, abraçando-o, disse: “Parai de levantar um clamor, pois a sua alma^&#42;1^ está nele.”

[NOTE]
====
. Ou “vida”. Veja Ap. 4A.
====

[[v44-20-11]]

^<<v44-20-11,11>>^ Ele subiu então e começou a refeição^&#42;1^ e tomou alimento, e, tendo conversado por bastante tempo, até à madrugada, partiu por fim.

[NOTE]
====
. Lit.: “tendo partido o pão”.
====

[[v44-20-12]]

^<<v44-20-12,12>>^ De modo que levaram o rapaz vivo e foram consolados além de medida.

[[v44-20-13]]

^<<v44-20-13,13>>^ Fomos então na frente até o barco e navegamos para Assos, onde pretendíamos tomar Paulo a bordo, porque, depois de ter dado instruções neste sentido, ele mesmo pretendia ir a pé.

[[v44-20-14]]

^<<v44-20-14,14>>^ Assim, quando nos alcançou em Assos, nós o tomamos a bordo e fomos a Mitilene;

[[v44-20-15]]

^<<v44-20-15,15>>^ e, navegando dali no dia seguinte, chegamos defronte de Quios, mas no dia seguinte tocamos em Samos, e no dia seguinte chegamos a Mileto.

[[v44-20-16]]

^<<v44-20-16,16>>^ Pois Paulo tinha decidido navegar ao largo de Éfeso, a fim de não gastar tempo no [distrito da] Ásia; porque ele se apressava em chegar a Jerusalém, se possível, no dia [da festividade] de Pentecostes.

[[v44-20-17]]

^<<v44-20-17,17>>^ No entanto, de Mileto ele enviou a Éfeso e chamou os anciãos^&#42;1^ da congregação.

[NOTE]
====
. “Anciãos.” Em gr.: pre·sby·té·rous.
====

[[v44-20-18]]

^<<v44-20-18,18>>^ Quando foram ter com ele, disse-lhes: “Bem sabeis como, desde o primeiro dia em que pisei no [distrito da] Ásia, eu estive convosco todo o tempo,

[[v44-20-19]]

^<<v44-20-19,19>>^ trabalhando como escravo para o Senhor, com a maior humildade mental, e com lágrimas e provações, que me sobrevieram pelas conspirações dos judeus;

[[v44-20-20]]

^<<v44-20-20,20>>^ ao passo que não me refreei de vos falar coisa alguma que fosse proveitosa, nem de vos ensinar publicamente e de casa em casa.^&#42;1^

[NOTE]
====
. Ou “e em casas particulares”. Lit.: “e segundo casas”. Gr.: kai kat’ oí·kous. Aqui, ka·tá é usado com o acusativo pl. no sentido distributivo. Veja 5:42 n.: “casa”.
====

[[v44-20-21]]

^<<v44-20-21,21>>^ Mas, eu dei cabalmente testemunho, tanto a judeus como a gregos, do arrependimento para com Deus e da fé em nosso Senhor Jesus.

[[v44-20-22]]

^<<v44-20-22,22>>^ E agora, eis que, amarrado no espírito, viajo para Jerusalém, embora sem saber o que me acontecerá nela,

[[v44-20-23]]

^<<v44-20-23,23>>^ exceto que o espírito santo, de cidade em cidade, me dá repetidamente testemunho, dizendo que me aguardam laços e tribulações.

[[v44-20-24]]

^<<v44-20-24,24>>^ Não obstante, não levo a minha alma^&#42;1^ em conta como estimada por mim, desde que eu possa terminar a minha carreira e o ministério que recebi do Senhor Jesus, para dar testemunho cabal das boas novas da benignidade imerecida de Deus.

[NOTE]
====
. Ou “vida”.
====

[[v44-20-25]]

^<<v44-20-25,25>>^ “E agora, eis que sei que todos vós, entre os quais eu estive pregando^&#42;1^ o reino,^&#42;2^ não vereis mais o meu rosto.

[NOTE]
====
. Ou “proclamando”. Gr.: ke·rýs·son; lat.: praé·di·cans. Veja Da 5:29 n.: “proclamaram”.
. “Reino”, אAB; VgSyp: “reino de Deus”; J17: “reino de Jeová”.
====

[[v44-20-26]]

^<<v44-20-26,26>>^ Por isso, eu vos chamo como testemunhas, no dia de hoje, de que estou limpo do sangue de todos os homens,

[[v44-20-27]]

^<<v44-20-27,27>>^ pois não me refreei de falar a todos vós todo o conselho de Deus.

[[v44-20-28]]

^<<v44-20-28,28>>^ Prestai atenção a vós mesmos e a todo o rebanho, entre o qual o espírito santo vos designou superintendentes^&#42;1^ para pastorear a congregação de Deus,^&#42;2^ que ele comprou com o sangue do seu próprio [Filho].^&#42;3^

[NOTE]
====
. “Superintendentes.” Gr.: e·pi·skó·pous; J17(hebr.): lif·qi·dhím, “para superintendentes”. Veja Ne 11:9 n.
. “Deus”, אBVg; AD: “do Senhor”.
. Veja Ap. 6C para um exame mais detido de “o sangue do seu próprio [Filho]”.
====

[[v44-20-29]]

^<<v44-20-29,29>>^ Sei que depois de eu ter ido embora entrarão no meio de vós lobos opressivos e eles não tratarão o rebanho com ternura,

[[v44-20-30]]

^<<v44-20-30,30>>^ e dentre vós mesmos surgirão homens e falarão coisas deturpadas, para atrair a si os discípulos.

[[v44-20-31]]

^<<v44-20-31,31>>^ “Portanto, mantende-vos despertos e lembrai-vos de que por três anos, noite e dia, não cessei de admoestar a cada um de vós, com lágrimas.

[[v44-20-32]]

^<<v44-20-32,32>>^ E agora eu vos encomendo a Deus^&#42;1^ e à palavra de sua benignidade imerecida, [palavra] que vos pode edificar e [que vos pode] dar a herança entre todos os santificados.

[NOTE]
====
. “Deus”, אADVgSypJ8,17,18,22; B: “ao Senhor”.
====

[[v44-20-33]]

^<<v44-20-33,33>>^ De ninguém cobicei a prata, ou o ouro, ou a vestimenta.

[[v44-20-34]]

^<<v44-20-34,34>>^ Vós mesmos sabeis que estas mãos têm cuidado das minhas necessidades, bem como das daqueles que estavam comigo.

[[v44-20-35]]

^<<v44-20-35,35>>^ Eu vos exibi em todas as coisas que, por labutardes assim, tendes de auxiliar os que são fracos e tendes de ter em mente as palavras do Senhor Jesus, quando ele mesmo disse: ‘Há mais felicidade em dar do que há em receber.’”

[[v44-20-36]]

^<<v44-20-36,36>>^ E, dizendo estas coisas, ajoelhou-se com todos eles e orou.

[[v44-20-37]]

^<<v44-20-37,37>>^ Deveras, irrompeu muito choro entre eles todos, e lançaram-se ao pescoço de Paulo e o beijaram ternamente,

[[v44-20-38]]

^<<v44-20-38,38>>^ porque estavam especialmente condoídos por causa da palavra que ele falara, de que não mais iam ver o seu rosto. Passaram assim a acompanhá-lo até o barco.

'''

xref:044-atos/044-atos-019.adoc#v44-19-0[&#60; Capítulo Anterior] | <<v44-20-0,Topo>> | xref:044-atos/044-atos-021.adoc#v44-21-0[Próximo Capítulo &#62;]