include::./index.adoc[]

[[v44-3-0]]
=== Atos, 3
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v44-3-1]]

^<<v44-3-1,1>>^ Ora, Pedro e João estavam subindo ao templo para a hora da oração, a nona hora,^&#42;1^

[NOTE]
====
. Isto é, por volta das 15 horas, contada desde o nascer do sol.
====

[[v44-3-2]]

^<<v44-3-2,2>>^ e certo homem, coxo desde a madre de sua mãe, estava sendo carregado, e o punham diariamente perto da porta do templo, chamada Bela, a fim de pedir dádivas de misericórdia dos que entravam no templo.

[[v44-3-3]]

^<<v44-3-3,3>>^ Quando ele avistou Pedro e João entrando no templo, começou a solicitar, para obter dádivas de misericórdia.

[[v44-3-4]]

^<<v44-3-4,4>>^ Mas Pedro, junto com João, fitou os olhos nele e disse: “Olha para nós.”

[[v44-3-5]]

^<<v44-3-5,5>>^ De modo que ele fixou a sua atenção neles, esperando obter deles alguma coisa.

[[v44-3-6]]

^<<v44-3-6,6>>^ No entanto, Pedro disse: “Não possuo prata nem ouro, mas o que tenho é o que te dou: Em nome de Jesus Cristo, o nazareno, anda!”

[[v44-3-7]]

^<<v44-3-7,7>>^ Com isto o segurou pela mão direita e o levantou. As solas dos seus pés e os ossos dos seus tornozelos foram instantaneamente feitos firmes;

[[v44-3-8]]

^<<v44-3-8,8>>^ e, pulando, pôs-se em pé, e começou a andar, e entrou com eles no templo, andando, e pulando, e louvando a Deus.

[[v44-3-9]]

^<<v44-3-9,9>>^ E todo o povo avistava-o andando e louvando a Deus.

[[v44-3-10]]

^<<v44-3-10,10>>^ Além disso, começaram a reconhecê-lo, que este era o homem que costumava sentar-se [pedindo] dádivas de misericórdia no Portão Belo do templo, e ficaram cheios de assombro e de êxtase com o que lhe tinha acontecido.

[[v44-3-11]]

^<<v44-3-11,11>>^ Pois bem, sendo que o homem segurava Pedro e João, todo o povo, fora de si de surpresa, afluía a eles no que era chamado de colunata de Salomão.

[[v44-3-12]]

^<<v44-3-12,12>>^ Quando Pedro viu isso, ele disse ao povo: “Homens de Israel, por que vos admirais disso, ou por que estais fitando os olhos em nós como se nós o tivéssemos feito andar por intermédio de poder pessoal ou de devoção piedosa?

[[v44-3-13]]

^<<v44-3-13,13>>^ O Deus de Abraão, e de Isaque, e de Jacó, o Deus de nossos antepassados, glorificou o seu Servo, Jesus, a quem vós, da vossa parte, entregastes e repudiastes na face de Pilatos, quando ele tinha decidido livrá-lo.

[[v44-3-14]]

^<<v44-3-14,14>>^ Sim, vós repudiastes aquele santo e justo, e pedistes que um homem, um assassino, vos fosse concedido liberalmente,

[[v44-3-15]]

^<<v44-3-15,15>>^ ao passo que matastes o Agente Principal da vida. Mas, Deus levantou-o dentre os mortos, fato de que somos testemunhas.

[[v44-3-16]]

^<<v44-3-16,16>>^ Conseqüentemente, o seu nome, pela [nossa] fé no seu nome, tornou forte este homem que observais e conheceis, e a fé que é por intermédio dele tem dado ao homem esta saúde completa à vista de todos vós.

[[v44-3-17]]

^<<v44-3-17,17>>^ E agora, irmãos, sei que agistes em ignorância, assim como também fizeram vossos governantes.

[[v44-3-18]]

^<<v44-3-18,18>>^ Mas, deste modo Deus tem cumprido as coisas que ele anunciou de antemão por intermédio da boca de todos os profetas, que o seu Cristo havia de sofrer.

[[v44-3-19]]

^<<v44-3-19,19>>^ “Arrependei-vos, portanto, e dai meia-volta, a fim de que os vossos pecados sejam apagados, para que venham épocas^&#42;1^ de refrigério da parte da pessoa^&#42;2^ de Jeová^&#42;3^

[NOTE]
====
. Ou “tempos designados”. Gr.: kai·roí.
. Lit.: “da face”.
. Veja Ap. 1D.
====

[[v44-3-20]]

^<<v44-3-20,20>>^ e para que ele envie o Cristo designado a vós, Jesus,

[[v44-3-21]]

^<<v44-3-21,21>>^ a quem o céu, deveras, tem de reter^&#42;1^ até os tempos do restabelecimento de todas as coisas, das quais Deus falou por intermédio da boca dos seus santos profetas dos tempos antigos.

[NOTE]
====
. Ou “receber”.
====

[[v44-3-22]]

^<<v44-3-22,22>>^ De fato, Moisés disse: ‘Jeová^&#42;1^ Deus vos suscitará dentre os vossos irmãos um profeta semelhante a mim. A este tendes de escutar segundo todas as coisas que ele vos falar.

[NOTE]
====
. “Jeová”, J7,8,10-18,20,22-24,28 e LXXP. Fºuad Inv. 266 em De 18:15; gr.: Ký·ri·os. Veja Ap. 1D.
====

[[v44-3-23]]

^<<v44-3-23,23>>^ Deveras, toda alma^&#42;1^ que não escutar esse Profeta será completamente destruída dentre o povo.’

[NOTE]
====
. Ou “cada alma”.
====

[[v44-3-24]]

^<<v44-3-24,24>>^ E, de fato, todos os profetas, de Samuel em diante e os em sucessão, tantos quantos falaram, declararam também distintamente estes dias.

[[v44-3-25]]

^<<v44-3-25,25>>^ Vós sois os filhos dos profetas e do pacto que Deus celebrou com os vossos antepassados, dizendo a Abraão: ‘E em teu descendente^&#42;1^ serão abençoadas todas as famílias da terra.’

[NOTE]
====
. Ou “prole”.
====

[[v44-3-26]]

^<<v44-3-26,26>>^ Deus, depois de suscitar o seu Servo, enviou-o primeiro a vós, para vos abençoar, por desviar a cada um [de vós] das vossas ações iníquas.”

'''

xref:044-atos/044-atos-002.adoc#v44-2-0[&#60; Capítulo Anterior] | <<v44-3-0,Topo>> | xref:044-atos/044-atos-004.adoc#v44-4-0[Próximo Capítulo &#62;]