include::./index.adoc[]

[[v44-19-0]]
=== Atos, 19
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v44-19-1]]

^<<v44-19-1,1>>^ No desenrolar dos eventos, enquanto Apolo estava em Corinto, Paulo passava pelas regiões interiores e desceu a Éfeso, e achou alguns discípulos;

[[v44-19-2]]

^<<v44-19-2,2>>^ e ele lhes disse: “Recebestes espírito santo, quando vos tornastes crentes?” Disseram-lhe: “Ora, nunca ouvimos [falar] que há espírito santo.”

[[v44-19-3]]

^<<v44-19-3,3>>^ E ele disse: “Então, em que fostes batizados?” Disseram: “No batismo de João.”

[[v44-19-4]]

^<<v44-19-4,4>>^ Paulo disse: “João batizava com o batismo [em símbolo] de arrependimento, dizendo ao povo que cressem naquele que vinha após ele, isto é, em Jesus.”

[[v44-19-5]]

^<<v44-19-5,5>>^ Ouvindo isso, foram batizados no nome do Senhor Jesus.

[[v44-19-6]]

^<<v44-19-6,6>>^ E, quando Paulo pôs as suas mãos sobre eles, veio sobre eles o espírito santo e começaram a falar em línguas e a profetizar.

[[v44-19-7]]

^<<v44-19-7,7>>^ Ao todo havia cerca de doze homens.

[[v44-19-8]]

^<<v44-19-8,8>>^ Entrando na sinagoga, falou com denodo, por três meses, proferindo discursos e usando de persuasão a respeito do reino de Deus.

[[v44-19-9]]

^<<v44-19-9,9>>^ Mas, quando alguns prosseguiam em endurecer-se e em não crer, falando injuriosamente sobre O Caminho perante a multidão, retirou-se deles e separou deles os discípulos, proferindo diariamente discursos no [auditório da] escola de Tirano.^&#42;1^

[NOTE]
====
. DItmss. acrescentam: “desde a quinta hora até a décima”, isto é, desde cerca das 11 horas até por volta das 16 horas.
====

[[v44-19-10]]

^<<v44-19-10,10>>^ Isto se deu por dois anos, de modo que todos os que habitavam [no distrito da] Ásia, tanto judeus como gregos, ouviram a palavra do Senhor.

[[v44-19-11]]

^<<v44-19-11,11>>^ E Deus realizava obras extraordinárias de poder por intermédio das mãos de Paulo,

[[v44-19-12]]

^<<v44-19-12,12>>^ de modo que se levavam aos doentios até mesmo panos e aventais do seu corpo, e as moléstias os abandonavam e os espíritos iníquos saíam.

[[v44-19-13]]

^<<v44-19-13,13>>^ Mas, certos dos judeus itinerantes, que praticavam a expulsão dos demônios, também empreenderam usar por nome o nome do Senhor Jesus para com os que tinham espíritos iníquos, dizendo: “Eu vos advirto solenemente por Jesus, a quem Paulo prega.”

[[v44-19-14]]

^<<v44-19-14,14>>^ Ora, havia sete filhos dum certo Ceva, principal sacerdote judaico, que faziam isso.

[[v44-19-15]]

^<<v44-19-15,15>>^ Mas, o espírito iníquo disse-lhes, em resposta: “Eu sei de Jesus e estou familiarizado com Paulo; mas quem sois vós?”

[[v44-19-16]]

^<<v44-19-16,16>>^ Com isso, o homem em quem estava o espírito iníquo pulou sobre eles, dominou um após outro^&#42;1^ e prevaleceu contra eles, de modo que fugiram nus e feridos daquela casa.

[NOTE]
====
. Lit.: “ambos”.
====

[[v44-19-17]]

^<<v44-19-17,17>>^ Isto se tornou conhecido a todos, tanto aos judeus como aos gregos que moravam em Éfeso; e sobre todos eles caiu temor, e o nome do Senhor Jesus era magnificado.

[[v44-19-18]]

^<<v44-19-18,18>>^ E muitos dos que se tinham tornado crentes vinham e confessavam, e relatavam abertamente as suas práticas.

[[v44-19-19]]

^<<v44-19-19,19>>^ Deveras, um número considerável dos que haviam praticado artes mágicas trouxeram os seus livros e os queimaram diante de todos. E calcularam os preços deles e acharam que valiam cinqüenta mil moedas de prata.

[[v44-19-20]]

^<<v44-19-20,20>>^ A palavra de Jeová^&#42;1^ crescia e prevalecia assim de modo poderoso.

[NOTE]
====
. “De Jeová”, J7,8,10,13,15-18,23; gr.: tou Ky·rí·ou; VgSyp: “de Deus”. Veja Ap. 1D.
====

[[v44-19-21]]

^<<v44-19-21,21>>^ Ora, tendo sido completadas estas coisas, Paulo propôs-se no seu espírito que, depois de passar pela Macedônia e Acaia, viajaria para Jerusalém, dizendo: “Depois de chegar lá, terei de ver também Roma.”

[[v44-19-22]]

^<<v44-19-22,22>>^ Mandou assim à Macedônia dois daqueles que lhe ministravam, Timóteo e Erasto, mas ele mesmo se demorou algum tempo no [distrito da] Ásia.

[[v44-19-23]]

^<<v44-19-23,23>>^ Naquele mesmo tempo surgiu uma perturbação nada pequena a respeito do Caminho.^&#42;1^

[NOTE]
====
. “Do Caminho”, אAB; Vgc: “do caminho do Senhor”; Syp: “do caminho de Deus”; J17,18: “do caminho de Jeová”.
====

[[v44-19-24]]

^<<v44-19-24,24>>^ Pois um certo homem, de nome Demétrio, prateiro, fabricando santuários^&#42;1^ de prata para Ártemis,^&#42;2^ fornecia não pouco lucro aos artífices;

[NOTE]
====
. Ou “habitações (moradas) divinas”. Gr.: na·oús; J17(hebr.): heh·khelóhth, “palácios; templos”.
. Ou “Diana”. Gr.: Ar·té·mi·dos; lat.: Di·á·nae.
====

[[v44-19-25]]

^<<v44-19-25,25>>^ e ele os ajuntou, bem como os que trabalhavam em tais coisas, e disse: “Homens, bem sabeis que a nossa prosperidade vem deste negócio.

[[v44-19-26]]

^<<v44-19-26,26>>^ Também, observais e ouvis como não somente em Éfeso, mas em quase todo o [distrito da] Ásia, este Paulo tem persuadido uma multidão considerável, voltando-os para outra opinião, dizendo que não são deuses os feitos por mãos.

[[v44-19-27]]

^<<v44-19-27,27>>^ Ainda mais, não somente existe o perigo de que esta ocupação nossa venha a cair em descrédito, mas também que o templo da grande deusa Ártemis venha a ser estimado em nada, e que até mesmo a sua magnificência, que todo o [distrito da] Ásia e a terra habitada adora, esteja prestes a ser reduzida a nada.”

[[v44-19-28]]

^<<v44-19-28,28>>^ Ouvindo isso e ficando cheios de ira, os homens começaram a clamar, dizendo: “Grande é a Ártemis dos efésios!”

[[v44-19-29]]

^<<v44-19-29,29>>^ A cidade ficou assim cheia de confusão, e arremeteram de comum acordo ao teatro, arrastando consigo Gaio e Aristarco, macedônios, companheiros de viagem de Paulo.

[[v44-19-30]]

^<<v44-19-30,30>>^ Paulo, da sua parte, estava disposto a entrar para ir ter com o povo, mas os discípulos não lhe permitiram [isso].

[[v44-19-31]]

^<<v44-19-31,31>>^ Até mesmo alguns dos promotores de festividades e jogos,^&#42;1^ que lhe tinham amizade, enviaram e começaram a implorar-lhe que não se arriscasse no teatro.

[NOTE]
====
. Literalmente: “alguns dos asiarcas”.
====

[[v44-19-32]]

^<<v44-19-32,32>>^ O fato é que alguns estavam clamando uma coisa e outros outra; pois a assembléia estava em confusão, e a maioria deles nem sabia a razão por que se tinham reunido.

[[v44-19-33]]

^<<v44-19-33,33>>^ Juntos trouxeram assim Alexandre para fora da multidão, empurrando-o os judeus na sua frente; e Alexandre, acenando com a mão, queria fazer a sua defesa perante o povo.

[[v44-19-34]]

^<<v44-19-34,34>>^ Mas, quando reconheceram que ele era judeu, levantou-se um só grito da parte de todos, gritando eles por cerca de duas horas: “Grande é a Ártemis dos efésios!”

[[v44-19-35]]

^<<v44-19-35,35>>^ Quando, por fim, o escrivão da cidade tinha feito calar a multidão, ele disse: “Homens de Éfeso, quem há realmente na humanidade que não saiba que a cidade dos efésios é a guardiã do templo da grande Ártemis e da imagem que caiu do céu?^&#42;1^

[NOTE]
====
. “Que caiu do céu.” Lit.: “caída de Zeus (Júpiter)”.
====

[[v44-19-36]]

^<<v44-19-36,36>>^ Portanto, visto que estas coisas são indisputáveis, convém que vos mantenhais calmos e que não atueis irrefletidamente.

[[v44-19-37]]

^<<v44-19-37,37>>^ Pois trouxestes esses homens, que não são nem salteadores de templos nem blasfemadores de nossa deusa.

[[v44-19-38]]

^<<v44-19-38,38>>^ Portanto, se Demétrio e os artífices com ele tiverem um caso contra alguém, há audiências e há procônsules; que levantem acusações uns contra os outros.

[[v44-19-39]]

^<<v44-19-39,39>>^ Se, porém, estais procurando algo mais do que isso, tem de ser^&#42;1^ decidido numa assembléia regular.

[NOTE]
====
. Ou “será”.
====

[[v44-19-40]]

^<<v44-19-40,40>>^ Porque nós estamos realmente em perigo de ser acusados de sedição pela questão de hoje, não existindo nem uma única causa que nos permita apresentar uma razão para esta turba desordenada.”

[[v44-19-41]]

^<<v44-19-41,41>>^ E depois de dizer isso, dissolveu a assembléia.

'''

xref:044-atos/044-atos-018.adoc#v44-18-0[&#60; Capítulo Anterior] | <<v44-19-0,Topo>> | xref:044-atos/044-atos-020.adoc#v44-20-0[Próximo Capítulo &#62;]