include::./index.adoc[]

[[v44-28-0]]
=== Atos, 28
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v44-28-1]]

^<<v44-28-1,1>>^ Uma vez a salvo, soubemos que a ilha se chamava Malta.^&#42;1^

[NOTE]
====
. “Melita”, אAB.
====

[[v44-28-2]]

^<<v44-28-2,2>>^ E o povo de língua estrangeira^&#42;1^ teve conosco extraordinário humanitarismo,^&#42;2^ pois acenderam um fogo e acolheram-nos a todos prestimosamente, por causa da chuva que caía e por causa do frio.

[NOTE]
====
. Ou “os bárbaros”.
. Lit.: “afeição pela humanidade”. Gr.: fi·lan·thro·pí·an. Veja Tit 3:4 n.
====

[[v44-28-3]]

^<<v44-28-3,3>>^ Mas, quando Paulo reuniu certo feixe de gravetos e o deitou no fogo, saiu uma víbora, por causa do calor, e se prendeu à mão dele.

[[v44-28-4]]

^<<v44-28-4,4>>^ Quando o povo de língua estrangeira avistou a bicha venenosa pendendo da mão dele, começaram a dizer uns aos outros: “Certamente este homem é assassino, e, embora se salvasse do mar, a justiça vingativa não permitiu que permanecesse vivo.”

[[v44-28-5]]

^<<v44-28-5,5>>^ No entanto, ele sacudiu a bicha venenosa para dentro do fogo e não sofreu dano.

[[v44-28-6]]

^<<v44-28-6,6>>^ Mas eles esperavam que fosse inchar com uma inflamação ou cair repentinamente morto. Depois de terem esperado por muito tempo e terem observado que nada nocivo lhe acontecia, mudaram de idéia e começaram a dizer que ele era [um] deus.

[[v44-28-7]]

^<<v44-28-7,7>>^ Ora, na vizinhança daquele lugar havia terras pertencentes ao homem de destaque da ilha, de nome Públio; e ele nos acolheu hospitaleiramente e nos hospedou bondosamente por três dias.

[[v44-28-8]]

^<<v44-28-8,8>>^ Mas, aconteceu que o pai de Públio estava de cama, afligido por febre e disenteria, e Paulo entrou até ele e orou, deitou as suas mãos sobre ele e o sarou.

[[v44-28-9]]

^<<v44-28-9,9>>^ Ocorrendo isso, os demais do povo da ilha, com doenças, começaram também a vir e a ser curados.

[[v44-28-10]]

^<<v44-28-10,10>>^ E honraram-nos também com muitas dádivas, e, quando nos fizemos à vela, carregaram-nos de coisas para as nossas necessidades.

[[v44-28-11]]

^<<v44-28-11,11>>^ Três meses depois fizemo-nos à vela num barco de Alexandria, que invernara na ilha, e que tinha por figura de proa “Filhos de Zeus”.^&#42;1^

[NOTE]
====
. Ou “Dióscuros”, os irmãos gêmeos Castor e Pólux.
====

[[v44-28-12]]

^<<v44-28-12,12>>^ E, aportando em Siracusa, permanecemos [ali] três dias,

[[v44-28-13]]

^<<v44-28-13,13>>^ donde, costeando, chegamos a Régio. E um dia depois se levantou um vento sulino e alcançamos Putéoli,^&#42;1^ no segundo dia.

[NOTE]
====
. Agora chamada Pozzuoli.
====

[[v44-28-14]]

^<<v44-28-14,14>>^ Ali achamos irmãos, e suplicaram-nos que ficássemos com eles sete dias; e assim nos aproximamos de Roma.

[[v44-28-15]]

^<<v44-28-15,15>>^ E os irmãos de lá, quando ouviram a notícia a nosso respeito, vieram ao nosso encontro até a Feira de Ápio^&#42;1^ e as Três Tavernas,^&#42;2^ e, avistando-os, Paulo agradeceu a Deus e tomou coragem.

[NOTE]
====
. Ou “Foro de Ápio”. Lat.: Áp·pi·i Fó·rum.
. “Três Tavernas.” Vgc(lat.): tres Ta·bér·nas.
====

[[v44-28-16]]

^<<v44-28-16,16>>^ Quando por fim entramos em Roma, permitiu-se a Paulo que ficasse sozinho com um soldado para guardá-lo.

[[v44-28-17]]

^<<v44-28-17,17>>^ No entanto, três dias depois, convocou todos os homens de destaque dos judeus. Quando se tinham reunido, passou a dizer-lhes: “Homens, irmãos, embora eu não tivesse feito nada contrário ao povo ou aos costumes de nossos antepassados, fui entregue como prisioneiro, de Jerusalém, às mãos dos romanos.

[[v44-28-18]]

^<<v44-28-18,18>>^ E estes, depois de feito um exame, desejavam livrar-me, visto que não havia em mim nenhuma causa para a morte.

[[v44-28-19]]

^<<v44-28-19,19>>^ Mas, quando os judeus persistiam em falar contra isso, fiquei compelido a apelar para César,^&#42;1^ mas não como se tivesse algo para acusar a minha nação.

[NOTE]
====
. Ou “o imperador”.
====

[[v44-28-20]]

^<<v44-28-20,20>>^ Realmente, por esta razão supliquei para vos ver e falar, pois tenho estas cadeias em volta de mim por causa da esperança de Israel.”

[[v44-28-21]]

^<<v44-28-21,21>>^ Disseram-lhe: “Nós tampouco temos recebido cartas da Judéia a respeito de ti, nem tem qualquer dos irmãos que chegaram relatado ou falado algo iníquo a teu respeito.

[[v44-28-22]]

^<<v44-28-22,22>>^ Mas, achamos correto ouvir de ti quais os teus pensamentos, porque, deveras, quanto a esta seita, é sabido por nós que em toda a parte se fala contra ela.”

[[v44-28-23]]

^<<v44-28-23,23>>^ Combinaram assim um dia com ele e vieram em maior número ter com ele na sua pousada. E ele lhes explicou o assunto por dar cabalmente testemunho a respeito do reino de Deus e por usar de persuasão para com eles concernente a Jesus, tanto pela lei de Moisés como pelos Profetas, de manhã até à noite.

[[v44-28-24]]

^<<v44-28-24,24>>^ E alguns começaram a acreditar nas coisas ditas; outros não queriam acreditar.

[[v44-28-25]]

^<<v44-28-25,25>>^ Assim, visto haver desacordo entre eles, começaram a retirar-se, fazendo Paulo este único comentário:
“O espírito santo falou aptamente por intermédio de Isaías, o profeta, a vossos antepassados,

[[v44-28-26]]

^<<v44-28-26,26>>^ dizendo: ‘Vai a este povo e dize: “Ouvindo ouvireis, mas de modo algum entendereis; e, olhando olhareis, mas de modo algum vereis.

[[v44-28-27]]

^<<v44-28-27,27>>^ Pois o coração deste povo tem ficado embotado^&#42;1^ e com os seus ouvidos têm ouvido sem reação, e eles têm fechado os olhos; para que nunca vissem com os olhos, nem ouvissem com os ouvidos, nem entendessem com o coração e se voltassem, e eu os sarasse.”’

[NOTE]
====
. Lit.: “engrossado (engordado)”.
====

[[v44-28-28]]

^<<v44-28-28,28>>^ Seja, portanto, sabido por vós que este, o meio pelo qual Deus salva,^&#42;1^ tem sido enviado às nações; elas certamente o escutarão.”

[NOTE]
====
. Ou “esta salvação [da parte] de Deus”.
====

[[v44-28-29]]

^<<v44-28-29,29>>^ ^&#42;1^ ——

[NOTE]
====
. אAB omitem o v. 29; Itmss.Vgc: “E depois de dizer isso, os judeus foram embora, tendo entre si muita disputa.”
====

[[v44-28-30]]

^<<v44-28-30,30>>^ Permaneceu assim por dois anos inteiros na sua própria casa alugada e recebia benevolamente a todos os que vinham vê-lo,

[[v44-28-31]]

^<<v44-28-31,31>>^ pregando-lhes^&#42;1^ o reino de Deus e ensinando com a maior franqueza no falar as coisas concernentes ao Senhor Jesus Cristo, sem impedimento.

[NOTE]
====
. Ou “proclamando-lhes”. Gr.: ke·rýs·son; lat.: praé·di·cans. Veja Da 5:29 n.: “proclamaram”.
====

'''

xref:044-atos/044-atos-027.adoc#v44-27-0[&#60; Capítulo Anterior] | <<v44-28-0,Topo>> | xref:045-romanos/045-romanos-001.adoc#v45-1-0[Próximo Capítulo &#62;]