include::./index.adoc[]

[[v44-11-0]]
=== Atos, 11
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v44-11-1]]

^<<v44-11-1,1>>^ Ora, os apóstolos e os irmãos que estavam na Judéia ouviram que pessoas das nações também receberam a palavra de Deus.

[[v44-11-2]]

^<<v44-11-2,2>>^ De modo que, quando Pedro subiu a Jerusalém, os [patrocinadores] da circuncisão começaram a contender com ele,

[[v44-11-3]]

^<<v44-11-3,3>>^ dizendo que ele tinha ido à casa de homens incircuncisos e havia comido com eles.

[[v44-11-4]]

^<<v44-11-4,4>>^ Em vista disso, Pedro principiou e prosseguiu a explicar-lhes as circunstâncias, dizendo:

[[v44-11-5]]

^<<v44-11-5,5>>^ “Eu estava na cidade de Jope, orando, e tive num transe uma visão, alguma sorte de vaso descendo, como um grande lençol de linho sendo abaixado pelas suas quatro extremidades, desde o céu, e chegando-se a mim.

[[v44-11-6]]

^<<v44-11-6,6>>^ Fitando os olhos nele, fiz observações e vi quadrúpedes da terra, e feras, e bichos rastejantes, e aves do céu.

[[v44-11-7]]

^<<v44-11-7,7>>^ Ouvi também uma voz dizer-me: ‘Levanta-te, Pedro, abate e come!’

[[v44-11-8]]

^<<v44-11-8,8>>^ Mas eu disse: ‘Absolutamente não, Senhor, porque nunca entrou na minha boca nada aviltado ou impuro.’

[[v44-11-9]]

^<<v44-11-9,9>>^ Pela segunda vez, a voz do céu respondeu: ‘Pára de chamar de aviltadas as coisas que Deus purificou.’

[[v44-11-10]]

^<<v44-11-10,10>>^ Isto ocorreu pela terceira vez, e tudo foi novamente puxado para o céu.

[[v44-11-11]]

^<<v44-11-11,11>>^ Também, eis que naquele instante havia três homens parados junto à casa em que estávamos, tendo sido mandados a mim, desde Cesaréia.

[[v44-11-12]]

^<<v44-11-12,12>>^ O espírito me disse, assim, que eu fosse com eles, não duvidando nada. Mas, estes seis irmãos também foram comigo, e nós entramos na casa do homem.

[[v44-11-13]]

^<<v44-11-13,13>>^ “Ele nos relatou como tinha visto um anjo em pé na sua casa e dizendo: ‘Manda homens a Jope e manda buscar Simão, que é cognominado Pedro,

[[v44-11-14]]

^<<v44-11-14,14>>^ e ele te falará aquelas coisas pelas quais podes ser salvo, tu e toda a tua família.’

[[v44-11-15]]

^<<v44-11-15,15>>^ Mas, quando eu principiei a falar, caiu sobre eles o espírito santo, assim como tinha também caído sobre nós, no princípio.

[[v44-11-16]]

^<<v44-11-16,16>>^ Em vista disso lembrei-me da declaração do Senhor, como costumava dizer: ‘João, da sua parte, batizou com água, mas vós sereis batizados em espírito santo.’

[[v44-11-17]]

^<<v44-11-17,17>>^ Se Deus, portanto, deu a mesma dádiva gratuita a eles como também dera a nós, os que temos crido no Senhor Jesus Cristo, quem era eu para poder obstar a Deus?”

[[v44-11-18]]

^<<v44-11-18,18>>^ Ora, quando ouviram estas coisas, assentiram, e glorificaram a Deus, dizendo: “Pois bem, Deus tem concedido também a pessoas das nações o arrependimento com a vida por objetivo.”

[[v44-11-19]]

^<<v44-11-19,19>>^ Conseqüentemente, os que tinham sido espalhados pela tribulação que surgiu por causa de Estêvão foram até a Fenícia, e Chipre, e Antioquia, não falando a palavra a ninguém, senão a judeus.

[[v44-11-20]]

^<<v44-11-20,20>>^ No entanto, dentre eles havia alguns homens de Chipre e de Cirene, que vieram a Antioquia e começaram a falar ao povo que falava grego,^&#42;1^ declarando as boas novas do Senhor Jesus.

[NOTE]
====
. “Povo que falava grego.” Lit.: “helenistas”. AD°: “gregos”.
====

[[v44-11-21]]

^<<v44-11-21,21>>^ Além disso, a mão de Jeová^&#42;1^ estava com eles, e um grande número, tornando-se crentes, voltaram-se para o Senhor.

[NOTE]
====
. Veja Ap. 1D.
====

[[v44-11-22]]

^<<v44-11-22,22>>^ O relato sobre eles chegou aos ouvidos da congregação que estava em Jerusalém, e eles enviaram Barnabé até Antioquia.

[[v44-11-23]]

^<<v44-11-23,23>>^ Quando ele chegou e viu a benignidade imerecida de Deus, alegrou-se e começou a encorajar todos a que continuassem no Senhor, [tendo isso] por objetivo do coração;

[[v44-11-24]]

^<<v44-11-24,24>>^ pois ele era homem bom e cheio de espírito santo e de fé. E uma multidão considerável foi acrescentada ao Senhor.

[[v44-11-25]]

^<<v44-11-25,25>>^ De modo que ele partiu para Tarso, a fim de fazer uma busca cabal por Saulo,

[[v44-11-26]]

^<<v44-11-26,26>>^ e, depois de o achar, trouxe-o a Antioquia. Aconteceu assim que por um ano inteiro se ajuntaram com eles na congregação e ensinaram uma considerável multidão, e foi primeiro em Antioquia que os discípulos, por providência divina, foram chamados^&#42;1^ cristãos.^&#42;2^

[NOTE]
====
. Ou “denominados”.
. “Cristãos.” Gr.: Khri·sti·a·noús; lat.: Chri·sti·á·ni; J17,18,22(hebr.): Meshi·hhi·yím, “messianistas”.
====

[[v44-11-27]]

^<<v44-11-27,27>>^ Ora, naqueles dias desceram profetas de Jerusalém para Antioquia.

[[v44-11-28]]

^<<v44-11-28,28>>^ Um deles, de nome Ágabo, levantou-se e passou a indicar, por intermédio do espírito, que uma grande fome estava para vir sobre toda a terra habitada, a qual, de fato, ocorreu no tempo de Cláudio.

[[v44-11-29]]

^<<v44-11-29,29>>^ Assim, os dos discípulos resolveram, cada um deles segundo o que podia, prover aos irmãos que moravam na Judéia uma subministração de socorros;

[[v44-11-30]]

^<<v44-11-30,30>>^ e isto fizeram, mandando-a aos anciãos,^&#42;1^ pela mão de Barnabé e Saulo.

[NOTE]
====
. “Anciãos.” Gr.: pre·sby·té·rous.
====

'''

xref:044-atos/044-atos-010.adoc#v44-10-0[&#60; Capítulo Anterior] | <<v44-11-0,Topo>> | xref:044-atos/044-atos-012.adoc#v44-12-0[Próximo Capítulo &#62;]