include::./index.adoc[]

[[v44-7-0]]
=== Atos, 7
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v44-7-1]]

^<<v44-7-1,1>>^ Mas, o sumo sacerdote disse: “São assim estas coisas?”

[[v44-7-2]]

^<<v44-7-2,2>>^ Ele disse: “Homens, irmãos e pais, ouvi. O Deus da glória apareceu a nosso antepassado Abraão enquanto ele estava na Mesopotâmia, antes de fixar residência em Harã,

[[v44-7-3]]

^<<v44-7-3,3>>^ e disse-lhe: ‘Sai da tua terra e de teus parentes e vai para uma terra que eu te hei de mostrar.’

[[v44-7-4]]

^<<v44-7-4,4>>^ Ele saiu então da terra dos caldeus e fixou residência em Harã. E dali, depois de morrer seu pai, [Deus]^&#42;1^ o fez mudar de residência para esta terra em que agora morais.

[NOTE]
====
. Lit.: “Ele”, referindo-se ao “Deus da glória”, no v. 2.
====

[[v44-7-5]]

^<<v44-7-5,5>>^ Contudo, não lhe deu nela nenhuma propriedade transmissível por herança, não, nem mesmo da largura de um pé; mas prometeu dar-lha como propriedade, e depois dele, ao seu descendente,^&#42;1^ quando ainda não tinha filho.

[NOTE]
====
. Ou “prole; posteridade”.
====

[[v44-7-6]]

^<<v44-7-6,6>>^ Além disso, Deus falou neste sentido, que seu descendente seria residente forasteiro em terra estrangeira, e que o escravizariam e atribulariam por quatrocentos anos.

[[v44-7-7]]

^<<v44-7-7,7>>^ ‘E eu hei de julgar aquela nação para a qual trabalharão como escravos’, disse Deus, ‘e depois destas coisas sairão e me prestarão serviço sagrado^&#42;1^ neste lugar.’

[NOTE]
====
. “Prestarão serviço sagrado.” Gr.: la·treú·sou·sin; J17,18,22(hebr.): weya·‛av·dhú·ni, “e me servirão (adorarão)”. Veja Êx 3:12 n.
====

[[v44-7-8]]

^<<v44-7-8,8>>^ “Deu-lhe também um pacto de circuncisão; e assim, ele se tornou pai de Isaque, e o circuncidou no oitavo dia, e Isaque, de Jacó, e Jacó, dos doze chefes de família.

[[v44-7-9]]

^<<v44-7-9,9>>^ E os chefes de família ficaram ciumentos de José e o venderam ao Egito. Mas Deus estava com ele

[[v44-7-10]]

^<<v44-7-10,10>>^ e o livrou de todas as suas tribulações, e deu-lhe graça e sabedoria à vista de Faraó, rei do Egito. E ele o designou para governar o Egito e toda a sua casa.

[[v44-7-11]]

^<<v44-7-11,11>>^ Mas, veio uma fome sobre todo o Egito e Canaã, sim, uma grande tribulação; e os nossos antepassados não achavam quaisquer provisões.

[[v44-7-12]]

^<<v44-7-12,12>>^ Mas Jacó ouviu que havia comestíveis no Egito e enviou os nossos antepassados pela primeira vez.

[[v44-7-13]]

^<<v44-7-13,13>>^ E na segunda vez, José se deu a conhecer aos seus irmãos; e a linhagem de José tornou-se manifesta a Faraó.

[[v44-7-14]]

^<<v44-7-14,14>>^ Assim, José enviou e chamou a Jacó, seu pai, e todos os seus parentes daquele lugar, no número de setenta e cinco almas.^&#42;1^

[NOTE]
====
. Veja Gên 46:20, 27 n.
====

[[v44-7-15]]

^<<v44-7-15,15>>^ Jacó desceu ao Egito.^&#42;1^ E ele faleceu; e assim também os nossos antepassados,

[NOTE]
====
. “Ao Egito.” B omite isso.
====

[[v44-7-16]]

^<<v44-7-16,16>>^ e foram transferidos para Siquém^&#42;1^ e colocados no túmulo que Abraão havia comprado por certo preço, com dinheiro de prata, dos filhos de Emor,^&#42;2^ em Siquém.

[NOTE]
====
. “Siquém”, SyhJ17,18,22; אAB: “Sychem”.
. Lit.: “Hemor”.
====

[[v44-7-17]]

^<<v44-7-17,17>>^ “Justamente quando se aproximava o tempo [para o cumprimento] da promessa que Deus havia declarado abertamente a Abraão, o povo crescia e se multiplicava no Egito,

[[v44-7-18]]

^<<v44-7-18,18>>^ até que se levantou um rei diferente sobre o Egito, que não sabia nada sobre José.

[[v44-7-19]]

^<<v44-7-19,19>>^ Este usava de estadística contra a nossa raça^&#42;1^ e injustamente obrigava os pais a exporem suas crianças, para que não fossem preservadas vivas.

[NOTE]
====
. “Raça.” Gr.: gé·nos; diferente de ge·ne·á, “geração”, como em Mt 24:34.
====

[[v44-7-20]]

^<<v44-7-20,20>>^ Naquele mesmo tempo nasceu Moisés, e ele era divinamente belo.^&#42;1^ E ele foi criado por três meses no lar de [seu] pai.

[NOTE]
====
. Ou “extremamente belo”. Lit.: “belo para o Deus”. Gr.: a·steí·os toi The·oí. Veja Jon 3:3 n.: “grande”.
====

[[v44-7-21]]

^<<v44-7-21,21>>^ Mas, quando foi exposto, foi recolhido pela filha de Faraó e ela o criou como seu próprio filho.

[[v44-7-22]]

^<<v44-7-22,22>>^ Em conseqüência disso, Moisés foi instruído em toda a sabedoria dos egípcios. De fato, era poderoso nas suas palavras e ações.

[[v44-7-23]]

^<<v44-7-23,23>>^ “Então, quando se cumpriu o tempo de seu quadragésimo ano, veio-lhe ao coração fazer uma inspeção aos seus irmãos, os filhos de Israel.

[[v44-7-24]]

^<<v44-7-24,24>>^ E quando avistou que um certo [deles] estava sendo tratado injustamente, defendeu-o e executou vingança por aquele que estava sendo maltratado, abatendo o egípcio.

[[v44-7-25]]

^<<v44-7-25,25>>^ Supunha que os seus irmãos compreenderiam que Deus lhes estava dando salvação por sua mão, mas eles não [o] compreenderam.

[[v44-7-26]]

^<<v44-7-26,26>>^ E, no dia seguinte, apareceu-lhes quando estavam lutando, e tentou reuni-los novamente em paz, dizendo: ‘Homens, vós sois irmãos. Por que tratais um ao outro injustamente?’

[[v44-7-27]]

^<<v44-7-27,27>>^ Mas aquele que tratava seu próximo injustamente repeliu-o, dizendo: ‘Quem te designou governante e juiz sobre nós?

[[v44-7-28]]

^<<v44-7-28,28>>^ Será que queres eliminar-me da mesma maneira como eliminaste ontem o egípcio?’

[[v44-7-29]]

^<<v44-7-29,29>>^ Em vista desta palavra, Moisés fugiu e tornou-se residente forasteiro na terra de Midiã, onde se tornou pai de dois filhos.

[[v44-7-30]]

^<<v44-7-30,30>>^ “E, ao se cumprirem quarenta anos, apareceu-lhe no ermo do Monte Sinai um anjo,^&#42;1^ na chama ardente dum espinheiro.

[NOTE]
====
. “Um anjo”, P74אABCVg; DSyp: “um anjo de [o] Senhor”; J7,8,10-17,28: “o anjo de Jeová”.
====

[[v44-7-31]]

^<<v44-7-31,31>>^ Ora, quando Moisés viu isso, maravilhou-se do que via. Mas, ao se aproximar para investigar, veio a voz de Jeová:^&#42;1^

[NOTE]
====
. Veja Ap. 1D.
====

[[v44-7-32]]

^<<v44-7-32,32>>^ ‘Eu sou o Deus dos teus antepassados, o Deus de Abraão, e de Isaque, e de Jacó.’ Tomado de tremor, Moisés não se atreveu a investigar mais.

[[v44-7-33]]

^<<v44-7-33,33>>^ Jeová^&#42;1^ disse-lhe: ‘Tira as sandálias dos teus pés, pois o lugar em que estás parado é terreno santo.

[NOTE]
====
. Veja Ap. 1D.
====

[[v44-7-34]]

^<<v44-7-34,34>>^ Tenho certamente visto o tratamento injusto para com o meu povo que está no Egito, e tenho ouvido o seu gemido e tenho descido para livrá-los. E agora vem: Eu te enviarei ao Egito.’

[[v44-7-35]]

^<<v44-7-35,35>>^ A este Moisés, que eles repudiaram, dizendo: ‘Quem te designou governante e juiz?’, a este homem Deus enviou como governante e como libertador^&#42;1^ pela mão do anjo que lhe apareceu no espinheiro.

[NOTE]
====
. Ou “e . . . resgatador (redentor)”. Gr.: kai ly·tro·tén; lat.: et re·dem·ptó·rem; J17(hebr.): wegho·’él.
====

[[v44-7-36]]

^<<v44-7-36,36>>^ Este homem os conduziu para fora, depois de fazer portentos e sinais no Egito, e no Mar Vermelho, e no ermo, por quarenta anos.

[[v44-7-37]]

^<<v44-7-37,37>>^ “Este é o Moisés que disse aos filhos de Israel: ‘Deus^&#42;1^ vos suscitará dentre os vossos irmãos um profeta semelhante a mim.’

[NOTE]
====
. “Deus”, אABVg; CSyp: “O Senhor Deus”; J7,8,10-17: “Jeová, vosso Deus”; J28: “Jeová Deus.”
====

[[v44-7-38]]

^<<v44-7-38,38>>^ Este é aquele que veio a estar entre a congregação no ermo, com o anjo que falou com ele no Monte Sinai e com os nossos antepassados, e ele recebeu proclamações sagradas, vivas, para dar a vós.

[[v44-7-39]]

^<<v44-7-39,39>>^ A ele os nossos antepassados se negaram a tornar-se obedientes, mas repeliram-no, e nos seus corações voltaram-se para o Egito,

[[v44-7-40]]

^<<v44-7-40,40>>^ dizendo a Arão: ‘Faze-nos deuses para irem na nossa frente. Quanto a este Moisés, que nos conduziu para fora da terra do Egito, não sabemos o que lhe aconteceu.’

[[v44-7-41]]

^<<v44-7-41,41>>^ Fizeram, pois, naqueles dias, um bezerro e trouxeram um sacrifício ao ídolo, e começaram a regalar-se com as obras das suas mãos.

[[v44-7-42]]

^<<v44-7-42,42>>^ De modo que Deus se voltou e os entregou para prestarem serviço sagrado ao exército do céu, assim como está escrito no livro dos profetas: ‘Será que foi a mim que oferecestes vítimas e sacrifícios por quarenta anos no ermo, ó casa de Israel?

[[v44-7-43]]

^<<v44-7-43,43>>^ Mas, acolhestes para vós a tenda de Moloque e a estrela do deus Refã, as figuras que fizestes para adorá-las. Conseqüentemente, eu vos deportarei para além de Babilônia.’^&#42;1^

[NOTE]
====
. Gr.: Ba·by·ló·nos; J17,18,22(hebr.): me·há·le’ah leVa·vél, “além de Babel”.
====

[[v44-7-44]]

^<<v44-7-44,44>>^ “Nossos antepassados tinham no ermo a tenda do testemunho,^&#42;1^ assim como deu ordens quando falou a Moisés, para fazê-la segundo o modelo^&#42;2^ que tinha visto.

[NOTE]
====
. Ou “o tabernáculo do testemunho”.
. Ou “tipo”. Gr.: tý·pon.
====

[[v44-7-45]]

^<<v44-7-45,45>>^ E os nossos antepassados, que a tiveram em sucessão, também a trouxeram com Josué^&#42;1^ para a terra possuída pelas nações que Deus expulsou de diante dos nossos antepassados. Ali ela permaneceu até os dias de Davi.

[NOTE]
====
. “Jeosué”, J17,18,22; אAB: “Jesus”.
====

[[v44-7-46]]

^<<v44-7-46,46>>^ Ele achou favor à vista de Deus e pediu para [ter o privilégio de] prover^&#42;1^ uma habitação para o Deus de Jacó.

[NOTE]
====
. Ou “achar”.
====

[[v44-7-47]]

^<<v44-7-47,47>>^ No entanto, Salomão construiu uma casa para ele.

[[v44-7-48]]

^<<v44-7-48,48>>^ Não obstante, o Altíssimo não mora em casas^&#42;1^ feitas por mãos; assim como diz o profeta:

[NOTE]
====
. Ou “coisas; lugares”.
====

[[v44-7-49]]

^<<v44-7-49,49>>^ ‘O céu é o meu trono e a terra é o meu escabelo. Que sorte de casa construireis para mim? diz Jeová.^&#42;1^ Ou qual é o lugar para o meu descanso?

[NOTE]
====
. Veja Ap. 1D.
====

[[v44-7-50]]

^<<v44-7-50,50>>^ Não foi a minha mão que fez todas essas coisas?’

[[v44-7-51]]

^<<v44-7-51,51>>^ “Homens obstinados^&#42;1^ e incircuncisos nos corações e ouvidos, vós sempre resistis ao espírito santo; assim como fizeram os vossos antepassados, também vós fazeis.

[NOTE]
====
. Ou “teimosos”.
====

[[v44-7-52]]

^<<v44-7-52,52>>^ A qual dos profetas foi que os vossos antepassados não perseguiram? Sim, mataram os que faziam anúncio antecipado a respeito da vinda do Justo, cujos traidores e assassinos vós vos tornastes agora,

[[v44-7-53]]

^<<v44-7-53,53>>^ vós, os que recebestes a Lei, conforme transmitida por anjos,^&#42;1^ mas não a guardastes.”

[NOTE]
====
. Lit.: “a Lei como transmissões de anjos”. J17: “a Lei das mãos de comissões de anjos”; lat.: lé·gem in dis·po·si·ti·ó·nem an·ge·ló·rum, “a Lei pela disposição de anjos”. Em 2Cr 23:18, a Vg usa iúx·ta dis·po·si·ti·ó·nem na versão de “pelas mãos de”.
====

[[v44-7-54]]

^<<v44-7-54,54>>^ Pois bem, quando ouviram estas coisas, sentiram-se feridos nos corações e começaram a ranger^&#42;1^ os dentes contra ele.

[NOTE]
====
. Ou “rilhar; cerrar”.
====

[[v44-7-55]]

^<<v44-7-55,55>>^ Mas ele, cheio de espírito santo, fitou os olhos no céu e avistou a glória de Deus, e Jesus em pé à direita de Deus,

[[v44-7-56]]

^<<v44-7-56,56>>^ e disse: “Eis que eu observo o céu aberto e o Filho do homem em pé à direita de Deus.”

[[v44-7-57]]

^<<v44-7-57,57>>^ A isto eles clamaram ao máximo da sua voz e puseram as mãos sobre os ouvidos e arremeteram à uma contra ele.

[[v44-7-58]]

^<<v44-7-58,58>>^ E depois de o lançarem fora da cidade, começaram a atirar pedras nele. E as testemunhas deitaram as suas roupas exteriores aos pés dum jovem chamado Saulo.

[[v44-7-59]]

^<<v44-7-59,59>>^ E atiravam pedras em Estêvão, enquanto ele fazia apelo^&#42;1^ e dizia: “Senhor Jesus, recebe meu espírito.”

[NOTE]
====
. Ou “invocação; oração”.
====

[[v44-7-60]]

^<<v44-7-60,60>>^ Então, dobrando os joelhos, clamou com forte voz: “Jeová,^&#42;1^ não lhes imputes este pecado.” E, dizendo isso, adormeceu [na morte].

[NOTE]
====
. Veja Ap. 1D.
====

'''

xref:044-atos/044-atos-006.adoc#v44-6-0[&#60; Capítulo Anterior] | <<v44-7-0,Topo>> | xref:044-atos/044-atos-008.adoc#v44-8-0[Próximo Capítulo &#62;]