include::./index.adoc[]

[[v44-4-0]]
=== Atos, 4
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v44-4-1]]

^<<v44-4-1,1>>^ Então, enquanto os [dois]^&#42;1^ estavam falando ao povo, sobrevieram-lhes os principais sacerdotes e o capitão do templo, e os saduceus,

[NOTE]
====
. Lit.: “enquanto eles”.
====

[[v44-4-2]]

^<<v44-4-2,2>>^ aborrecidos porque estavam ensinando o povo e estavam declarando distintamente a ressurreição dentre os mortos, no caso de Jesus;

[[v44-4-3]]

^<<v44-4-3,3>>^ e deitaram mãos neles e os puseram em detenção até o dia seguinte, pois já era noitinha.

[[v44-4-4]]

^<<v44-4-4,4>>^ No entanto, muitos dos que tinham escutado o discurso creram, e o número dos homens chegou a cerca de cinco mil.

[[v44-4-5]]

^<<v44-4-5,5>>^ No dia seguinte, ocorreu em Jerusalém um ajuntamento dos seus governantes, e anciãos,^&#42;1^ e escribas

[NOTE]
====
. “Anciãos.” Gr.: tous pre·sby·té·rous.
====

[[v44-4-6]]

^<<v44-4-6,6>>^ (também Anás, o principal sacerdote, e Caifás, e João, e Alexandre, e tantos quantos eram da parentela do principal sacerdote),

[[v44-4-7]]

^<<v44-4-7,7>>^ e postaram-nos no meio deles e começaram a indagar: “Com que poder ou em nome de quem fizestes isso?”

[[v44-4-8]]

^<<v44-4-8,8>>^ Então Pedro, cheio de espírito santo, disse-lhes:
“Governantes do povo e anciãos,

[[v44-4-9]]

^<<v44-4-9,9>>^ se estamos sendo examinados neste dia à base duma boa ação para com um homem adoentado, quanto a por quem este homem ficou bom,^&#42;1^

[NOTE]
====
. Ou “foi salvo”.
====

[[v44-4-10]]

^<<v44-4-10,10>>^ seja sabido de todos vós e de todo o povo de Israel, que é no nome de Jesus Cristo, o nazareno, a quem pregastes numa estaca,^&#42;1^ mas a quem Deus levantou dentre os mortos, por esse^&#42;2^ é que este homem está aqui são em pé diante de vós.

[NOTE]
====
. Ou “fixastes numa estaca (poste)”. Veja Ap. 5C.
. Ou “neste nome”.
====

[[v44-4-11]]

^<<v44-4-11,11>>^ Esta é ‘a pedra que por vós, construtores, não foi levada em conta, que se tornou a principal do ângulo’.

[[v44-4-12]]

^<<v44-4-12,12>>^ Outrossim, não há salvação em nenhum outro, pois não há outro nome debaixo do céu, que tenha sido dado entre os homens, pelo qual tenhamos de ser salvos.”

[[v44-4-13]]

^<<v44-4-13,13>>^ Ora, quando observaram a franqueza de Pedro e João, e perceberam que eles eram homens indoutos e comuns, ficaram admirados. E começaram a reconhecer a respeito deles que costumavam estar com Jesus;

[[v44-4-14]]

^<<v44-4-14,14>>^ e, olhando para o homem que tinha sido curado, parado [ali] com eles, não tinham nada a dizer em refutação.

[[v44-4-15]]

^<<v44-4-15,15>>^ Ordenaram-lhes, assim, que saíssem da sala do Sinédrio e começaram a consultar-se entre si,

[[v44-4-16]]

^<<v44-4-16,16>>^ dizendo: “Que havemos de fazer com estes homens? Porque, de fato, tem ocorrido um sinal notável por intermédio deles, manifesto a todos os habitantes de Jerusalém; e não o podemos negar.

[[v44-4-17]]

^<<v44-4-17,17>>^ Não obstante, a fim de que isso não se espalhe ainda mais entre o povo, digamos-lhes com ameaças que não falem mais a nenhum homem à base deste nome.”

[[v44-4-18]]

^<<v44-4-18,18>>^ Com isso chamaram-nos e advertiram-nos que em nenhuma parte fizessem qualquer pronunciação, nem ensinassem à base do nome de Jesus.

[[v44-4-19]]

^<<v44-4-19,19>>^ Mas Pedro e João disseram-lhes, em resposta: “Se é justo, à vista de Deus, escutar antes a vós do que a Deus, julgai-o vós mesmos.

[[v44-4-20]]

^<<v44-4-20,20>>^ Mas, quanto a nós, não podemos parar de falar das coisas que vimos e ouvimos.”

[[v44-4-21]]

^<<v44-4-21,21>>^ Assim, tendo-os ameaçado ainda mais, livraram-nos, visto que não acharam nenhuma base para puni-los, e por causa do povo, porque todos estavam glorificando a Deus pelo que tinha ocorrido;

[[v44-4-22]]

^<<v44-4-22,22>>^ pois o homem em quem este sinal de cura tinha ocorrido tinha mais de quarenta anos.

[[v44-4-23]]

^<<v44-4-23,23>>^ Depois de terem sido livrados, foram para a sua própria gente e relataram as coisas que os principais sacerdotes e os anciãos lhes haviam dito.

[[v44-4-24]]

^<<v44-4-24,24>>^ Ouvindo isso, elevaram unanimemente as suas vozes a Deus e disseram:
“Soberano Senhor,^&#42;1^ tu és Aquele que fez o céu e a terra, e o mar, e todas as coisas neles,

[NOTE]
====
. “Soberano Senhor.” Gr.: Dé·spo·ta; lat.: Dó·mi·ne; J17,18(hebr.): ’Adho·naí. Veja Ap. 1E.
====

[[v44-4-25]]

^<<v44-4-25,25>>^ e quem, por intermédio de espírito santo, disse pela boca de nosso antepassado Davi, teu servo: ‘Por que se tumultuaram as nações e meditaram os povos coisas vãs?

[[v44-4-26]]

^<<v44-4-26,26>>^ Os reis da terra tomaram a sua posição e os governantes aglomeraram-se à uma contra Jeová^&#42;1^ e contra o seu ungido.’^&#42;2^

[NOTE]
====
. Veja Ap. 1D.
. Ou “seu Cristo”.
====

[[v44-4-27]]

^<<v44-4-27,27>>^ Mesmo assim, tanto Herodes como Pôncio Pilatos, com [homens das] nações e com povos de Israel, ajuntaram-se realmente nesta cidade contra o teu santo servo Jesus, a quem ungiste,^&#42;1^

[NOTE]
====
. Ou “fizeste Cristo”. Gr.: é·khri·sas.
====

[[v44-4-28]]

^<<v44-4-28,28>>^ a fim de fazerem as coisas que a tua mão e conselho predeterminaram que ocorressem.

[[v44-4-29]]

^<<v44-4-29,29>>^ E agora, Jeová,^&#42;1^ dá atenção às ameaças deles e concede aos teus escravos que persistam em falar a tua palavra com todo o denodo,

[NOTE]
====
. Veja Ap. 1D.
====

[[v44-4-30]]

^<<v44-4-30,30>>^ ao passo que estendes a tua mão para sarar e ao passo que ocorrem sinais e portentos por intermédio do nome de teu santo servo Jesus.”

[[v44-4-31]]

^<<v44-4-31,31>>^ E, quando haviam feito súplica, foi abalado o lugar onde estavam ajuntados; e todos juntos ficaram cheios de espírito santo e falaram a palavra de Deus com denodo.

[[v44-4-32]]

^<<v44-4-32,32>>^ Ainda mais, a multidão dos que haviam crido era de um só coração e alma, e nem mesmo um só dizia que qualquer das coisas que possuía fosse a sua própria; mas eles tinham todas as coisas em comum.

[[v44-4-33]]

^<<v44-4-33,33>>^ Também os apóstolos continuavam com grande poder a dar testemunho a respeito da ressurreição do Senhor Jesus; e sobre todos eles havia benignidade imerecida em grande medida.

[[v44-4-34]]

^<<v44-4-34,34>>^ De fato, não havia nem mesmo um só necessitado entre eles; porque todos os que eram proprietários de campos ou de casas vendiam-nos, e traziam os valores das coisas vendidas

[[v44-4-35]]

^<<v44-4-35,35>>^ e os depositavam aos pés dos apóstolos. Por sua vez, fazia-se distribuição a cada um, conforme tivesse necessidade.

[[v44-4-36]]

^<<v44-4-36,36>>^ De modo que José, que pelos apóstolos era cognominado Barnabé, que traduzido significa Filho de Consolo, um levita, natural de Chipre,

[[v44-4-37]]

^<<v44-4-37,37>>^ possuindo um pedaço de terra, vendeu-o, trouxe o dinheiro e o depositou aos pés dos apóstolos.

'''

xref:044-atos/044-atos-003.adoc#v44-3-0[&#60; Capítulo Anterior] | <<v44-4-0,Topo>> | xref:044-atos/044-atos-005.adoc#v44-5-0[Próximo Capítulo &#62;]