include::./index.adoc[]

[[v44-22-0]]
=== Atos, 22
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v44-22-1]]

^<<v44-22-1,1>>^ “Homens, irmãos e pais, ouvi agora a minha defesa perante vós.”

[[v44-22-2]]

^<<v44-22-2,2>>^ (Pois bem, quando ouviram que se dirigia a eles no idioma hebraico, ficaram ainda mais calados, e ele disse:)

[[v44-22-3]]

^<<v44-22-3,3>>^ “Eu sou judeu, nascido em Tarso da Cilícia, mas educado nesta cidade, aos pés de Gamaliel, instruído segundo o rigor da Lei ancestral, zeloso por Deus, assim como todos vós sois neste dia.

[[v44-22-4]]

^<<v44-22-4,4>>^ E eu perseguia este Caminho até à morte, amarrando e entregando às prisões tanto homens como mulheres,

[[v44-22-5]]

^<<v44-22-5,5>>^ conforme tanto o sumo sacerdote como toda a assembléia dos anciãos^&#42;1^ me podem dar testemunho. Fui também obter deles cartas para os irmãos em Damasco, e eu estava em caminho para trazer amarrados a Jerusalém também os que havia ali, para serem punidos.

[NOTE]
====
. “Assembléia dos anciãos”, ou: “presbitério”. Gr.: pre·sby·té·ri·on.
====

[[v44-22-6]]

^<<v44-22-6,6>>^ “Mas, enquanto eu viajava e chegava perto de Damasco, por volta do meio-dia, reluziu repentinamente do céu uma grande luz toda em volta de mim,

[[v44-22-7]]

^<<v44-22-7,7>>^ e eu caí ao chão e ouvi uma voz dizer-me: ‘Saulo, Saulo, por que me persegues?’

[[v44-22-8]]

^<<v44-22-8,8>>^ Eu respondi: ‘Quem és, Senhor?’ E ele me disse: ‘Eu sou Jesus, o nazareno, a quem persegues.’

[[v44-22-9]]

^<<v44-22-9,9>>^ Ora, os homens que estavam comigo deveras observaram a luz, mas não ouviram^&#42;1^ a voz daquele que falava comigo.

[NOTE]
====
. Ou “ouviram com entendimento”, assim como Paulo, no v. 7.
====

[[v44-22-10]]

^<<v44-22-10,10>>^ A isto eu disse: ‘Que devo^&#42;1^ fazer, Senhor?’ O Senhor me disse: ‘Levanta-te, vai a Damasco, e ali te será dito tudo o que te foi designado fazer.’

[NOTE]
====
. Ou “tenho de”.
====

[[v44-22-11]]

^<<v44-22-11,11>>^ Mas, visto que eu não podia ver nada, por causa da glória daquela luz, cheguei a Damasco levado pela mão daqueles que estavam comigo.

[[v44-22-12]]

^<<v44-22-12,12>>^ “Então, certo Ananias, homem reverente segundo a Lei, de boa reputação entre todos os judeus que moravam ali,

[[v44-22-13]]

^<<v44-22-13,13>>^ veio a mim, e, parando ao meu lado, disse-me: ‘Saulo, irmão, tem novamente a tua visão!’^&#42;1^ E naquela mesma hora olhei para ele.

[NOTE]
====
. Ou: “irmão, olha para cima!”
====

[[v44-22-14]]

^<<v44-22-14,14>>^ Ele disse: ‘O Deus de nossos antepassados escolheu-te para que venhas a saber a sua vontade e a ver o Justo, e a ouvir a voz de sua boca,

[[v44-22-15]]

^<<v44-22-15,15>>^ porque tu hás de ser testemunha dele, perante todos os homens, das coisas que viste e ouviste.

[[v44-22-16]]

^<<v44-22-16,16>>^ E agora, por que demoras? Levanta-te, sê batizado e lava os teus pecados por invocares^&#42;1^ o seu nome.’

[NOTE]
====
. Ou “lava os teus pecados e invoca”.
====

[[v44-22-17]]

^<<v44-22-17,17>>^ “Mas, tendo eu voltado a Jerusalém e estando a orar no templo, caí em transe^&#42;1^

[NOTE]
====
. “Caí em transe”, אAB; J13,14,17,22: “a mão de Jeová estava sobre mim”; J18: “o espírito de Jeová me revestiu”.
====

[[v44-22-18]]

^<<v44-22-18,18>>^ e o vi dizer-me: ‘Apressa-te e sai ligeiro de Jerusalém, porque não concordarão com o teu testemunho a respeito de mim.’

[[v44-22-19]]

^<<v44-22-19,19>>^ E eu disse: ‘Senhor, eles mesmos bem sabem que eu costumava encarcerar e chibatear, numa sinagoga após outra, os que criam em ti;

[[v44-22-20]]

^<<v44-22-20,20>>^ e quando se derramava o sangue de Estêvão, tua testemunha, eu mesmo também estava parado ali e aprovava [isso], e guardava as roupas exteriores dos que o eliminavam.’

[[v44-22-21]]

^<<v44-22-21,21>>^ Contudo, ele me disse: ‘Vai, porque eu hei de enviar-te a nações longínquas.’”

[[v44-22-22]]

^<<v44-22-22,22>>^ Ora, eles o escutaram até esta palavra, e elevaram as suas vozes, dizendo: “Tira tal [homem] da terra, pois não é apto para viver!”

[[v44-22-23]]

^<<v44-22-23,23>>^ E, visto que clamavam e lançavam em volta as suas roupas exteriores, e atiravam poeira ao ar,

[[v44-22-24]]

^<<v44-22-24,24>>^ o comandante militar^&#42;1^ mandou que fosse trazido ao quartel e disse que devia ser examinado sob açoites, a fim de que soubesse plenamente por que causa eles estavam gritando dessa maneira contra ele.

[NOTE]
====
. Lit.: “quiliarca”, comandante de 1.000 soldados.
====

[[v44-22-25]]

^<<v44-22-25,25>>^ Mas, quando o tinham esticado para a chicotada,^&#42;1^ Paulo disse ao oficial do exército^&#42;2^ parado ali: “É lícito que açoiteis um homem que é romano e que não está condenado?”

[NOTE]
====
. Ou “o tinham esticado com as correias”.
. Lit.: “centurião”, comandante de 100 soldados.
====

[[v44-22-26]]

^<<v44-22-26,26>>^ Pois bem, ouvindo isso o oficial do exército, foi ter com o comandante militar e fez um relatório, dizendo: “Que pretendes fazer? Ora, este homem é romano.”

[[v44-22-27]]

^<<v44-22-27,27>>^ De modo que o comandante militar se chegou e lhe disse: “Diz-me: És tu romano?” Ele disse: “Sim.”

[[v44-22-28]]

^<<v44-22-28,28>>^ O comandante militar respondeu: “Eu comprei estes direitos de cidadão^&#42;1^ por grande soma [de dinheiro].” Paulo disse: “Mas eu até nasci [com eles].”^&#42;2^

[NOTE]
====
. Ou “comprei esta cidadania”.
. Ou “[nela]”.
====

[[v44-22-29]]

^<<v44-22-29,29>>^ Portanto, os homens que estavam prestes a examiná-lo com tortura retiraram-se dele imediatamente; e o comandante militar ficou com medo ao averiguar que ele era romano e que o havia amarrado.

[[v44-22-30]]

^<<v44-22-30,30>>^ Portanto, no dia seguinte, querendo saber ao certo exatamente por que ele estava sendo acusado pelos judeus, soltou-o e mandou que se reunissem os principais sacerdotes e todo o Sinédrio. E ele trouxe Paulo para baixo e o postou no meio deles.

'''

xref:044-atos/044-atos-021.adoc#v44-21-0[&#60; Capítulo Anterior] | <<v44-22-0,Topo>> | xref:044-atos/044-atos-023.adoc#v44-23-0[Próximo Capítulo &#62;]