include::./index.adoc[]

[[v44-10-0]]
=== Atos, 10
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v44-10-1]]

^<<v44-10-1,1>>^ Havia então em Cesaréia certo homem de nome Cornélio, oficial do exército^&#42;1^ do chamado destacamento italiano,

[NOTE]
====
. Ou “centurião”, comandante de 100 soldados.
====

[[v44-10-2]]

^<<v44-10-2,2>>^ homem devoto e que temia a Deus, junto com toda a sua família, e ele fazia muitas dádivas de misericórdia ao povo e fazia continuamente súplica a Deus.

[[v44-10-3]]

^<<v44-10-3,3>>^ Cerca da nona hora^&#42;1^ do dia, ele viu claramente numa visão um anjo de Deus entrar até ele e dizer-lhe: “Cornélio!”

[NOTE]
====
. Isto é, por volta das 15 horas, contada desde o nascer do sol.
====

[[v44-10-4]]

^<<v44-10-4,4>>^ O homem fitou os olhos nele, e, ficando amedrontado, disse: “O que é, Senhor?” Disse-lhe ele: “Tuas orações e dádivas de misericórdia têm ascendido como memória perante Deus.

[[v44-10-5]]

^<<v44-10-5,5>>^ Assim, envia agora homens a Jope e convoca certo Simão, que é cognominado Pedro.

[[v44-10-6]]

^<<v44-10-6,6>>^ Este homem está sendo hospedado por certo Simão, curtidor, que tem uma casa à beira do mar.”

[[v44-10-7]]

^<<v44-10-7,7>>^ Assim que o deixou o anjo que lhe falara, ele chamou dois dos seus servos domésticos e um soldado devoto dentre os que constantemente o assistiam,

[[v44-10-8]]

^<<v44-10-8,8>>^ e relatou-lhes tudo e mandou-os a Jope.

[[v44-10-9]]

^<<v44-10-9,9>>^ No dia seguinte, enquanto prosseguiam na jornada e se aproximavam da cidade, Pedro subiu ao alto da casa para orar, perto da sexta hora.^&#42;1^

[NOTE]
====
. Isto é, por volta do meio-dia, contado desde o nascer do sol.
====

[[v44-10-10]]

^<<v44-10-10,10>>^ Mas, ele ficou com muita fome e queria comer. Enquanto faziam os preparativos, caiu em transe,

[[v44-10-11]]

^<<v44-10-11,11>>^ e observou o céu aberto e alguma sorte de vaso descendo, semelhante a um grande lençol de linho, sendo baixado pelas suas quatro extremidades para a terra;

[[v44-10-12]]

^<<v44-10-12,12>>^ e nele havia toda sorte de quadrúpedes e bichos rastejantes da terra, e aves do céu.

[[v44-10-13]]

^<<v44-10-13,13>>^ E veio a ele uma voz: “Levanta-te, Pedro, abate^&#42;1^ e come!”

[NOTE]
====
. Ou “sacrifica”.
====

[[v44-10-14]]

^<<v44-10-14,14>>^ Mas Pedro disse: “Absolutamente não, Senhor, porque nunca comi nada aviltado e impuro.”

[[v44-10-15]]

^<<v44-10-15,15>>^ E a voz [falou] novamente com ele, pela segunda vez: “Pára de chamar de aviltadas as coisas que Deus purificou.”

[[v44-10-16]]

^<<v44-10-16,16>>^ Isto ocorreu pela terceira vez, e, imediatamente, o vaso foi recolhido ao céu.

[[v44-10-17]]

^<<v44-10-17,17>>^ Ora, enquanto Pedro estava no íntimo em grande perplexidade quanto a que podia significar a visão que tinha visto, eis que os homens mandados por Cornélio haviam indagado acerca da casa de Simão e estavam parados ali no portão.

[[v44-10-18]]

^<<v44-10-18,18>>^ E eles clamaram e indagaram se ali se hospedava Simão, que era cognominado Pedro.

[[v44-10-19]]

^<<v44-10-19,19>>^ Enquanto Pedro repassava na mente a visão, o espírito disse: “Eis que três^&#42;1^ homens estão-te buscando.

[NOTE]
====
. “Três”, P74אACVgSyp; B: “dois”.
====

[[v44-10-20]]

^<<v44-10-20,20>>^ No entanto, levanta-te, desce e vai com eles, não duvidando nada, porque eu os mandei.”

[[v44-10-21]]

^<<v44-10-21,21>>^ Pedro desceu, assim, para junto dos homens e disse: “Eis que eu sou aquele a quem buscais. Qual é a causa de estardes aqui?”

[[v44-10-22]]

^<<v44-10-22,22>>^ Disseram: “Cornélio, oficial do exército, homem justo e temente a Deus, de boa reputação da parte de toda a nação dos judeus, recebeu instruções divinas^&#42;1^ por meio dum santo anjo para te mandar buscar para a sua casa e para ouvir as coisas que tens a dizer.”

[NOTE]
====
. “Recebeu instruções divinas”, אAB; J18: “recebeu ordem de Jeová”.
====

[[v44-10-23]]

^<<v44-10-23,23>>^ Portanto, ele os convidou a entrar e os hospedou.
No dia seguinte levantou-se e foi embora com eles, e alguns dos irmãos, que eram de Jope, foram com ele.

[[v44-10-24]]

^<<v44-10-24,24>>^ No dia seguinte entrou em Cesaréia. Cornélio, naturalmente, esperava-os e havia reunido seus parentes e amigos íntimos.

[[v44-10-25]]

^<<v44-10-25,25>>^ Quando Pedro entrou, Cornélio foi ao seu encontro, prostrou-se aos pés dele e prestou-lhe homenagem.

[[v44-10-26]]

^<<v44-10-26,26>>^ Mas Pedro ergueu-o, dizendo: “Levanta-te; eu mesmo também sou homem.”

[[v44-10-27]]

^<<v44-10-27,27>>^ E, conversando com ele, entrou e achou muitas pessoas reunidas,

[[v44-10-28]]

^<<v44-10-28,28>>^ e disse-lhes: “Vós bem sabeis quão ilícito é para um judeu juntar-se ou chegar-se a um homem de outra raça; contudo, Deus mostrou-me que eu não chamasse nenhum homem de aviltado ou impuro.

[[v44-10-29]]

^<<v44-10-29,29>>^ Por isso vim, realmente sem objeção, quando fui chamado. Portanto, indago a razão pela qual me mandastes chamar.”

[[v44-10-30]]

^<<v44-10-30,30>>^ Concordemente, Cornélio disse: “Há quatro dias, a contar desta hora, eu estava orando na minha casa, à nona hora,^&#42;1^ quando, eis que um homem em roupa vistosa estava em pé na minha frente

[NOTE]
====
. Veja v. 3 n.
====

[[v44-10-31]]

^<<v44-10-31,31>>^ e disse: ‘Cornélio, tua oração tem sido ouvida favoravelmente e as tuas dádivas de misericórdia têm sido lembradas diante de Deus.

[[v44-10-32]]

^<<v44-10-32,32>>^ Envia, portanto, a Jope e manda chamar Simão, que é cognominado Pedro. Este homem está sendo hospedado na casa de Simão, o curtidor, à beira do mar.’

[[v44-10-33]]

^<<v44-10-33,33>>^ Portanto enviei imediatamente a ti, e tu fizeste bem em vir para cá. E agora estamos aqui todos presentes perante Deus para ouvir todas as coisas que foste mandado dizer por Jeová.”^&#42;1^

[NOTE]
====
. “Jeová”, J17,18,23; P45אABC(gr.): tou Ky·rí·ou; P74DSyp: “Deus”. Veja Ap. 1D.
====

[[v44-10-34]]

^<<v44-10-34,34>>^ Em vista disso, Pedro abriu a boca e disse: “Certamente percebo que Deus não é parcial,

[[v44-10-35]]

^<<v44-10-35,35>>^ mas, em cada nação, o homem que o teme e que faz a justiça lhe é aceitável.

[[v44-10-36]]

^<<v44-10-36,36>>^ Ele enviou a palavra aos filhos de Israel, para declarar-lhes as boas novas de paz por intermédio de Jesus Cristo: Este é Senhor de todos [os demais].

[[v44-10-37]]

^<<v44-10-37,37>>^ Sabeis de que assunto se falava em toda a Judéia, principiando da Galiléia, depois do batismo pregado por João,

[[v44-10-38]]

^<<v44-10-38,38>>^ a saber, Jesus, que era de Nazaré, como Deus o ungiu com espírito santo e poder, e ele percorria o país, fazendo o bem e sarando a todos os oprimidos pelo Diabo; porque Deus estava com ele.

[[v44-10-39]]

^<<v44-10-39,39>>^ E nós somos testemunhas de todas as coisas que ele fez tanto no país dos judeus como em Jerusalém; mas eles também o eliminaram, pendurando-o num madeiro.^&#42;1^

[NOTE]
====
. Ou “árvore”. Veja Ap. 5C.
====

[[v44-10-40]]

^<<v44-10-40,40>>^ Deus ressuscitou a Este no terceiro dia e lhe concedeu tornar-se manifesto,

[[v44-10-41]]

^<<v44-10-41,41>>^ não a todo o povo, mas a testemunhas designadas de antemão por Deus, a nós, os que comemos e bebemos com ele depois do seu levantamento dentre os mortos.

[[v44-10-42]]

^<<v44-10-42,42>>^ Também, ele nos ordenou que pregássemos ao povo e que déssemos um testemunho cabal de que Este é o decretado por Deus para ser juiz dos vivos e dos mortos.

[[v44-10-43]]

^<<v44-10-43,43>>^ Dele é que todos os profetas dão testemunho, de que todo aquele que deposita fé nele recebe perdão de pecados por intermédio de seu nome.”

[[v44-10-44]]

^<<v44-10-44,44>>^ Enquanto Pedro ainda falava sobre estes assuntos, caiu o espírito santo sobre todos os que ouviam a palavra.

[[v44-10-45]]

^<<v44-10-45,45>>^ E os fiéis que tinham vindo com Pedro, que eram dos circuncisos, ficaram pasmados, porque a dádiva gratuita do espírito santo estava sendo derramada também sobre pessoas das nações.

[[v44-10-46]]

^<<v44-10-46,46>>^ Pois, ouviam-nos falar em línguas e magnificar a Deus. Pedro respondeu então:

[[v44-10-47]]

^<<v44-10-47,47>>^ “Pode alguém proibir a água, de modo que estes não sejam batizados, sendo que receberam o espírito santo assim como nós?”

[[v44-10-48]]

^<<v44-10-48,48>>^ Com isso mandou que fossem batizados no nome de Jesus Cristo. Solicitaram-lhe, então, que permanecesse alguns dias.

'''

xref:044-atos/044-atos-009.adoc#v44-9-0[&#60; Capítulo Anterior] | <<v44-10-0,Topo>> | xref:044-atos/044-atos-011.adoc#v44-11-0[Próximo Capítulo &#62;]