include::./index.adoc[]

[[v44-23-0]]
=== Atos, 23
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v44-23-1]]

^<<v44-23-1,1>>^ Olhando atentamente para o Sinédrio, Paulo disse: “Homens, irmãos, eu me comportei perante Deus com uma consciência perfeitamente limpa, até o dia de hoje.”

[[v44-23-2]]

^<<v44-23-2,2>>^ Em vista disso, o sumo sacerdote Ananias mandou que os que estavam em pé junto dele lhe batessem na boca.

[[v44-23-3]]

^<<v44-23-3,3>>^ Paulo disse-lhe então: “Deus te baterá, parede caiada. Assentas-te tu ao mesmo tempo para me julgar segundo a Lei, e, transgredindo a Lei, mandas que me batam?”

[[v44-23-4]]

^<<v44-23-4,4>>^ Os parados ali disseram: “Injurias tu o sumo sacerdote de Deus?”

[[v44-23-5]]

^<<v44-23-5,5>>^ E Paulo disse: “Irmãos, eu não sabia que era o sumo sacerdote. Pois está escrito: ‘Não deves falar injuriosamente dum governante do teu povo.’”

[[v44-23-6]]

^<<v44-23-6,6>>^ Ora, quando Paulo notou que uma parte era dos saduceus, mas a outra dos fariseus, passou a clamar no Sinédrio: “Homens, irmãos, eu sou fariseu, filho de fariseus. É por causa da esperança da ressurreição dos mortos que estou sendo julgado.”

[[v44-23-7]]

^<<v44-23-7,7>>^ Por dizer isso, surgiu uma dissensão entre fariseus e saduceus, e a multidão ficou dividida.

[[v44-23-8]]

^<<v44-23-8,8>>^ Pois os saduceus dizem não haver nem ressurreição, nem anjo, nem espírito, mas os fariseus declaram publicamente todos estes.^&#42;1^

[NOTE]
====
. Lit.: “ambas (as coisas)”.
====

[[v44-23-9]]

^<<v44-23-9,9>>^ Irrompeu assim uma grande gritaria, e alguns dos escribas do partido dos fariseus se levantaram e começaram a contender ferozmente, dizendo: “Não achamos nada de errado neste homem; mas, se um espírito ou um anjo falou com ele —.”

[[v44-23-10]]

^<<v44-23-10,10>>^ Ora, tornando-se grande a dissensão, o comandante militar ficou com medo de que Paulo fosse dilacerado por eles e mandou a força de soldados descer e arrancá-lo do meio deles, para o levarem ao quartel.

[[v44-23-11]]

^<<v44-23-11,11>>^ Mas, na noite seguinte, o Senhor estava em pé ao lado dele e disse: “Tem coragem! Pois assim como tens dado testemunho cabal em Jerusalém concernente às coisas a respeito de mim, terás de dar também testemunho em Roma.”

[[v44-23-12]]

^<<v44-23-12,12>>^ Então, ficando dia, os judeus formaram uma conspiração e obrigaram-se com uma maldição, dizendo que nem comeriam nem beberiam até matarem Paulo.

[[v44-23-13]]

^<<v44-23-13,13>>^ Foram mais de quarenta homens que formaram esta conspiração juramentada;

[[v44-23-14]]

^<<v44-23-14,14>>^ e eles foram ter com os principais sacerdotes e os anciãos,^&#42;1^ e disseram: “Obrigamo-nos solenemente com uma maldição, de não tomarmos nem um bocado de alimento até matarmos Paulo.

[NOTE]
====
. “Anciãos.” Em gr.: pre·sby·té·rois.
====

[[v44-23-15]]

^<<v44-23-15,15>>^ Assim, portanto, vós, junto com o Sinédrio, tornai claro ao comandante militar por que ele devia trazê-lo para baixo a vós, como se pretendêsseis resolver mais exatamente os assuntos que o envolvem. Mas, antes de ele chegar perto, estaremos prontos para eliminá-lo.”

[[v44-23-16]]

^<<v44-23-16,16>>^ No entanto, o filho da irmã de Paulo soube que estavam de tocaia, e veio e entrou no quartel, e relatou isso a Paulo.

[[v44-23-17]]

^<<v44-23-17,17>>^ Paulo chamou, assim, um dos oficiais do exército e disse: “Conduze este jovem ao comandante militar, pois tem algo para lhe relatar.”

[[v44-23-18]]

^<<v44-23-18,18>>^ Portanto, este homem o tomou e conduziu ao comandante militar, e disse: “O prisioneiro Paulo chamou-me e solicitou-me que conduzisse este jovem a ti, visto que ele tem algo para dizer-te.”

[[v44-23-19]]

^<<v44-23-19,19>>^ O comandante militar tomou-o pela mão e se retirou, e começou a interrogá-lo em particular: “Que é que tens para relatar-me?”

[[v44-23-20]]

^<<v44-23-20,20>>^ Ele disse: “Os judeus concordaram em solicitar-te que tragas Paulo para baixo ao Sinédrio, amanhã, como se pretendessem inteirar-se de algo mais exato a respeito dele.

[[v44-23-21]]

^<<v44-23-21,21>>^ Acima de tudo, não os deixes persuadir-te, pois mais de quarenta homens deles estão de tocaia contra ele, e eles se obrigaram com uma maldição, de nem comerem nem beberem, até que o tenham eliminado; e eles estão agora prontos, aguardando a tua promessa.”

[[v44-23-22]]

^<<v44-23-22,22>>^ Portanto, o comandante militar deixou o jovem ir embora, depois de lhe ordenar: “Não dês com a língua nos dentes para com ninguém, de que me esclareceste estas coisas.”

[[v44-23-23]]

^<<v44-23-23,23>>^ E ele convocou certos dois dos oficiais do exército e disse: “Aprontai duzentos soldados para marcharem até Cesaréia, também setenta cavaleiros e duzentos lanceiros, para a terceira hora^&#42;1^ da noite.

[NOTE]
====
. Isto é, por volta das 21 horas, contada desde o pôr-do-sol.
====

[[v44-23-24]]

^<<v44-23-24,24>>^ Também, provede animais de carga, para que façam Paulo cavalgar e o transportem a salvo até Félix, o governador.”

[[v44-23-25]]

^<<v44-23-25,25>>^ E ele escreveu uma carta, na seguinte forma:

[[v44-23-26]]

^<<v44-23-26,26>>^ “Cláudio Lísias, à Sua Excelência, o Governador Félix: Cumprimentos!

[[v44-23-27]]

^<<v44-23-27,27>>^ Os judeus apoderaram-se deste homem e ele estava prestes a ser eliminado por eles, mas eu vim repentinamente com uma força de soldados e o resgatei, porque fiquei sabendo que ele era romano.

[[v44-23-28]]

^<<v44-23-28,28>>^ E, querendo averiguar a causa pela qual o acusavam, levei-o para baixo ao Sinédrio deles.^&#42;1^

[NOTE]
====
. “Levei-o para baixo ao Sinédrio deles”, P74אAVgSyp; B° omite isso.
====

[[v44-23-29]]

^<<v44-23-29,29>>^ Verifiquei que estava sendo acusado por questões da Lei deles, mas não foi acusado de nem uma única coisa que merecesse a morte ou laços.

[[v44-23-30]]

^<<v44-23-30,30>>^ Mas, porque me foi exposta uma conspiração que se fazia contra o homem, envio-o imediatamente a ti e mando que os acusadores falem perante ti contra ele.”

[[v44-23-31]]

^<<v44-23-31,31>>^ Portanto, estes soldados tomaram Paulo, segundo as suas ordens, e o trouxeram de noite a Antipátride.

[[v44-23-32]]

^<<v44-23-32,32>>^ No dia seguinte, permitiram que os cavaleiros prosseguissem com ele, e voltaram para o quartel.

[[v44-23-33]]

^<<v44-23-33,33>>^ Os [cavaleiros] entraram em Cesaréia e entregaram a carta ao governador e apresentaram-lhe também Paulo.

[[v44-23-34]]

^<<v44-23-34,34>>^ Ele a leu, assim, e indagou de que província ele era, e averiguou que era da Cilícia.

[[v44-23-35]]

^<<v44-23-35,35>>^ “Eu te darei uma audiência cabal”, disse ele, “ao chegarem também os teus acusadores”. E mandou que fosse mantido sob guarda, no palácio pretoriano de Herodes.

'''

xref:044-atos/044-atos-022.adoc#v44-22-0[&#60; Capítulo Anterior] | <<v44-23-0,Topo>> | xref:044-atos/044-atos-024.adoc#v44-24-0[Próximo Capítulo &#62;]