include::./index.adoc[]

[[v44-13-0]]
=== Atos, 13
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v44-13-1]]

^<<v44-13-1,1>>^ Ora, havia em Antioquia profetas e instrutores na congregação local, Barnabé, bem como Simeão, que era chamado Níger, e Lúcio de Cirene, e Manaém, que tinha sido educado com Herodes, o governante distrital,^&#42;1^ e Saulo.

[NOTE]
====
. Lit.: “o tetrarca”, o príncipe territorial agindo pelo imperador.
====

[[v44-13-2]]

^<<v44-13-2,2>>^ Enquanto ministravam publicamente a Jeová^&#42;1^ e jejuavam, o espírito santo disse: “Dentre todas as pessoas, separai-me Barnabé e Saulo para a obra a que os chamei.”

[NOTE]
====
. Veja Ap. 1D.
====

[[v44-13-3]]

^<<v44-13-3,3>>^ Jejuaram então e oraram, e puseram as suas mãos sobre eles e os deixaram ir.

[[v44-13-4]]

^<<v44-13-4,4>>^ Concordemente, estes homens, enviados pelo espírito santo, desceram a Selêucia, e dali navegaram para Chipre.

[[v44-13-5]]

^<<v44-13-5,5>>^ E, tendo chegado a Salamina, começaram a publicar a palavra de Deus nas sinagogas dos judeus. Tinham também João por assistente.

[[v44-13-6]]

^<<v44-13-6,6>>^ Tendo percorrido toda a ilha até Pafos, encontraram certo homem, feiticeiro, falso profeta, um judeu cujo nome era Barjesus,

[[v44-13-7]]

^<<v44-13-7,7>>^ e ele estava com o procônsul^&#42;1^ Sérgio Paulo, homem inteligente. Chamando Barnabé e Saulo, este homem buscava seriamente ouvir a palavra de Deus.

[NOTE]
====
. Governador provincial agindo pelo Senado romano.
====

[[v44-13-8]]

^<<v44-13-8,8>>^ Mas Elimas, o feiticeiro, (é assim, de fato, que se traduz o seu nome,) começou a opor-se a eles, buscando desviar da fé o procônsul.

[[v44-13-9]]

^<<v44-13-9,9>>^ Saulo, que é também Paulo,^&#42;1^ ficando cheio de espírito santo, olhou para ele atentamente

[NOTE]
====
. Possivelmente significando “Pouco; Pequeno”. Gr.: Paú·los.
====

[[v44-13-10]]

^<<v44-13-10,10>>^ e disse: “Ó homem cheio de toda sorte de fraude e de toda sorte de vilania, ó filho do Diabo, inimigo de tudo o que é justo, não cessarás de torcer os caminhos direitos de Jeová?^&#42;1^

[NOTE]
====
. Veja Ap. 1D.
====

[[v44-13-11]]

^<<v44-13-11,11>>^ Pois bem, eis que a mão de Jeová^&#42;1^ está sobre ti e ficarás cego, não vendo a luz do sol por um período de tempo.” Densa névoa e escuridão caíram instantaneamente sobre ele, e ele andava em volta buscando homens para o conduzirem pela mão.

[NOTE]
====
. Veja Ap. 1D.
====

[[v44-13-12]]

^<<v44-13-12,12>>^ O procônsul, vendo então o que tinha acontecido, tornou-se crente, pois ficou assombrado com o ensino de Jeová.^&#42;1^

[NOTE]
====
. Veja Ap. 1D.
====

[[v44-13-13]]

^<<v44-13-13,13>>^ Os homens, junto com Paulo, fizeram-se então ao mar, partindo de Pafos, e chegaram a Perge, na Panfília. Mas João retirou-se deles e voltou para Jerusalém.

[[v44-13-14]]

^<<v44-13-14,14>>^ Eles, no entanto, seguiram de Perge e vieram a Antioquia, na Pisídia, e, entrando na sinagoga no dia de sábado, tomaram assento.

[[v44-13-15]]

^<<v44-13-15,15>>^ Depois da leitura pública da Lei e dos Profetas, os presidentes da sinagoga mandaram dizer-lhes: “Homens, irmãos, se tiverdes alguma palavra de encorajamento para o povo, dizei-a.”

[[v44-13-16]]

^<<v44-13-16,16>>^ Paulo levantou-se, assim, e, acenando com a mão, disse:
“Homens, israelitas e vós [outros] que temeis a Deus, ouvi.

[[v44-13-17]]

^<<v44-13-17,17>>^ O Deus deste povo de Israel escolheu os nossos antepassados e enalteceu o povo durante a sua residência como forasteiros na terra do Egito, e os tirou dela com braço erguido.

[[v44-13-18]]

^<<v44-13-18,18>>^ E, por um período de cerca de quarenta anos, suportou a sua maneira de agir no ermo.

[[v44-13-19]]

^<<v44-13-19,19>>^ Depois de destruir sete nações na terra de Canaã, distribuiu-lhes a terra por sorte:

[[v44-13-20]]

^<<v44-13-20,20>>^ tudo isso durante cerca de quatrocentos e cinqüenta anos.
“E, depois destas coisas,^&#42;1^ deu-lhes juízes, até Samuel, o profeta.

[NOTE]
====
. “Durante cerca de quatrocentos e cinqüenta anos. E, depois destas coisas”, P74אABCVg.
====

[[v44-13-21]]

^<<v44-13-21,21>>^ Mas, dali em diante reclamaram um rei, e Deus lhes deu Saul, filho de Quis, homem da tribo de Benjamim, por quarenta anos.

[[v44-13-22]]

^<<v44-13-22,22>>^ E, depois de removê-lo, suscitou-lhes Davi como rei, a respeito de quem deu testemunho e disse: ‘Achei Davi, filho de Jessé, homem agradável ao meu coração, que fará todas as coisas que desejo.’

[[v44-13-23]]

^<<v44-13-23,23>>^ Da descendência deste [homem], segundo a sua promessa, Deus trouxe a Israel um salvador, Jesus,

[[v44-13-24]]

^<<v44-13-24,24>>^ depois de João, em antecipação da entrada Desse, ter pregado publicamente, a todo o povo de Israel, [o] batismo [em símbolo] de arrependimento.

[[v44-13-25]]

^<<v44-13-25,25>>^ Mas João, enquanto cumpria a sua carreira, dizia: ‘O que supondes que eu sou? Eu não sou aquele.^&#42;1^ Mas, eis que depois de mim vem alguém, cujas sandálias não sou digno de desatar.’

[NOTE]
====
. Ou: “O que supondes que eu sou, eu não sou.”
====

[[v44-13-26]]

^<<v44-13-26,26>>^ “Homens, irmãos, filhos da linhagem de Abraão, e aqueles [outros] entre vós que temeis a Deus, a nós nos foi enviada a palavra desta salvação.

[[v44-13-27]]

^<<v44-13-27,27>>^ Pois os habitantes de Jerusalém e os seus governantes não conheceram a Este, mas, ao agirem como juízes, cumpriram as coisas expressas pelos Profetas, coisas que são lidas em voz alta cada sábado,

[[v44-13-28]]

^<<v44-13-28,28>>^ e, embora não achassem causa para morte, reclamaram de Pilatos que fosse executado.

[[v44-13-29]]

^<<v44-13-29,29>>^ Quando, então, tinham efetuado todas as coisas escritas a respeito dele, tiraram-no do madeiro^&#42;1^ e deitaram-no num túmulo memorial.

[NOTE]
====
. Ou “árvore”. Veja Ap. 5C.
====

[[v44-13-30]]

^<<v44-13-30,30>>^ Mas Deus o levantou dentre os mortos;

[[v44-13-31]]

^<<v44-13-31,31>>^ e, durante muitos dias, ele se tornou visível aos que tinham subido com ele da Galiléia para Jerusalém, que agora são suas testemunhas junto ao povo.

[[v44-13-32]]

^<<v44-13-32,32>>^ “E, assim, nós vos declaramos as boas novas concernentes à promessa feita aos antepassados,

[[v44-13-33]]

^<<v44-13-33,33>>^ que Deus a cumpriu inteiramente a nós, seus^&#42;1^ filhos, por ter ressuscitado a Jesus; assim como está escrito no segundo salmo: ‘Tu és meu filho, hoje eu me tornei teu Pai.’

[NOTE]
====
. “A nós, seus”, Syp; P74אABC°DVg: “a nossos”.
====

[[v44-13-34]]

^<<v44-13-34,34>>^ E este fato, de que o ressuscitou dentre os mortos, destinado a nunca mais voltar à corrupção, foi declarado por ele do seguinte modo: ‘Eu vos darei as benevolências para com Davi, que são fiéis.’

[[v44-13-35]]

^<<v44-13-35,35>>^ Por isso ele diz também em outro salmo: ‘Não permitirás que aquele que te é leal veja a corrupção.’

[[v44-13-36]]

^<<v44-13-36,36>>^ Pois Davi, por um lado, serviu à vontade expressa de Deus na sua própria geração e adormeceu [na morte], e foi deitado com os seus antepassados e viu a corrupção.

[[v44-13-37]]

^<<v44-13-37,37>>^ Por outro lado, aquele a quem Deus levantou não viu a corrupção.

[[v44-13-38]]

^<<v44-13-38,38>>^ “Sabei, portanto, irmãos, que por intermédio Deste se publica a vós o perdão de pecados;

[[v44-13-39]]

^<<v44-13-39,39>>^ e que, de todas as coisas das quais não podíeis ser declarados inculpes por meio da lei de Moisés, todo aquele que crê é declarado inculpe por meio Deste.

[[v44-13-40]]

^<<v44-13-40,40>>^ Portanto, cuidai de que aquilo que se disse nos Profetas não venha sobre vós:

[[v44-13-41]]

^<<v44-13-41,41>>^ ‘Observai-o, desdenhadores, e admirai-vos disso, e desaparecei, porque estou fazendo uma obra nos vossos dias, uma obra que de modo algum acreditareis, mesmo que alguém a relatasse a vós em pormenores.’”

[[v44-13-42]]

^<<v44-13-42,42>>^ Então, ao saírem, o povo começou a suplicar que se lhes falasse destes assuntos no sábado seguinte.

[[v44-13-43]]

^<<v44-13-43,43>>^ Assim, depois de se dissolver a reunião da sinagoga, muitos dos judeus e dos prosélitos que adoravam [a Deus]^&#42;1^ seguiram a Paulo e Barnabé, os quais, falando com eles, começaram a instar com eles para que continuassem na benignidade imerecida de Deus.

[NOTE]
====
. “Que adoravam (temiam) a Deus”, SyP; J18: “que temiam a Jeová”.
====

[[v44-13-44]]

^<<v44-13-44,44>>^ No sábado seguinte, quase toda a cidade se ajuntou para ouvir a palavra de Jeová.^&#42;1^

[NOTE]
====
. “De Jeová”, J17,22; P74אABc(gr.): tou Ky·rí·ou; B°CSyh,p: “de Deus”. Veja Ap. 1D.
====

[[v44-13-45]]

^<<v44-13-45,45>>^ Quando os judeus chegaram a ver as multidões, ficaram cheios de ciúme e começaram a contradizer de modo blasfemo as coisas faladas por Paulo.

[[v44-13-46]]

^<<v44-13-46,46>>^ E assim, falando com denodo, Paulo e Barnabé disseram: “Era necessário que a palavra de Deus fosse falada primeiro a vós. Visto que a repelis e não vos julgais dignos da vida eterna, eis que nos voltamos para as nações.

[[v44-13-47]]

^<<v44-13-47,47>>^ De fato, Jeová^&#42;1^ nos tem imposto o mandamento nas seguintes palavras: ‘Eu te designei como luz das nações, para que sejas uma salvação até à extremidade^&#42;2^ da terra.’”

[NOTE]
====
. Veja Ap. 1D.
. “Extremidade.” Ou “parte mais distante”. Gr.: e·skhá·tou. Veja 1:8 n.: “distante”.
====

[[v44-13-48]]

^<<v44-13-48,48>>^ Quando os das nações ouviram isso, começaram a alegrar-se e a glorificar a palavra de Jeová,^&#42;1^ e todos os corretamente dispostos para com a vida eterna tornaram-se crentes.

[NOTE]
====
. “De Jeová”, J7,8,10,13,15-17,22,23; P45,74אAC(gr.): tou Ky·rí·ou; BD: “de Deus”. Veja Ap. 1D.
====

[[v44-13-49]]

^<<v44-13-49,49>>^ Outrossim, a palavra de Jeová^&#42;1^ estava sendo levada através de todo o país.

[NOTE]
====
. Veja Ap. 1D.
====

[[v44-13-50]]

^<<v44-13-50,50>>^ Mas os judeus atiçaram as mulheres bem conceituadas, que adoravam [a Deus],^&#42;1^ e os homens de destaque da cidade, e levantaram uma perseguição contra Paulo e Barnabé, e lançaram-nos fora dos seus termos.

[NOTE]
====
. “Que adoravam (temiam) a Deus”, Syp; J7,8,10,18: “que temiam a Jeová”.
====

[[v44-13-51]]

^<<v44-13-51,51>>^ Estes sacudiram contra eles o pó dos seus pés e foram para Icônio.

[[v44-13-52]]

^<<v44-13-52,52>>^ E os discípulos continuavam cheios de alegria e de espírito santo.

'''

xref:044-atos/044-atos-012.adoc#v44-12-0[&#60; Capítulo Anterior] | <<v44-13-0,Topo>> | xref:044-atos/044-atos-014.adoc#v44-14-0[Próximo Capítulo &#62;]