include::./index.adoc[]

[[v44-18-0]]
=== Atos, 18
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v44-18-1]]

^<<v44-18-1,1>>^ Depois destas coisas, ele partiu de Atenas e chegou a Corinto.

[[v44-18-2]]

^<<v44-18-2,2>>^ E achou certo judeu de nome Áquila, natural de Ponto, que viera recentemente da Itália, e Priscila, sua esposa, por causa do fato de que Cláudio tinha ordenado que todos os judeus se afastassem de Roma. De modo que foi ter com eles,

[[v44-18-3]]

^<<v44-18-3,3>>^ e, em razão de serem da mesma profissão, ficou no lar deles, e trabalhavam, pois eram fabricantes de tendas por profissão.

[[v44-18-4]]

^<<v44-18-4,4>>^ No entanto, cada sábado, ele dava um discurso na sinagoga e persuadia judeus e gregos.^&#42;1^

[NOTE]
====
. Lit.: “helenos”. Gr.: Hél·le·nas.
====

[[v44-18-5]]

^<<v44-18-5,5>>^ Então, tendo descido tanto Silas como Timóteo da Macedônia, Paulo começou a ocupar-se intensamente com a palavra, testemunhando aos judeus para provar que Jesus é o Cristo.

[[v44-18-6]]

^<<v44-18-6,6>>^ Mas, quando persistiam em opor-se e em falar de modo ultrajante, sacudiu a sua roupa e disse-lhes: “O vosso sangue caia sobre as vossas cabeças. Eu estou limpo. Doravante irei às pessoas das nações.”

[[v44-18-7]]

^<<v44-18-7,7>>^ Concordemente, saiu dali e entrou na casa dum homem de nome Tício Justo, adorador de Deus, cuja casa era contígua à sinagoga.

[[v44-18-8]]

^<<v44-18-8,8>>^ Mas Crispo, o presidente da sinagoga, tornou-se crente no Senhor, e assim também todos os de sua família. E muitos dos coríntios, que tinham ouvido, começaram a crer e a ser batizados.

[[v44-18-9]]

^<<v44-18-9,9>>^ Ademais, o Senhor disse de noite a Paulo, por intermédio duma visão: “Não temas, mas persiste em falar e em não ficar calado,

[[v44-18-10]]

^<<v44-18-10,10>>^ porque eu estou contigo e nenhum homem te assaltará para fazer-te dano; porque tenho muito povo nesta cidade.”

[[v44-18-11]]

^<<v44-18-11,11>>^ Destarte, demorou ali um ano e seis meses, ensinando entre eles a palavra de Deus.

[[v44-18-12]]

^<<v44-18-12,12>>^ Então, enquanto Gálio era procônsul^&#42;1^ da Acaia,^&#42;2^ os judeus levantaram-se de comum acordo contra Paulo e levaram-no perante a cadeira de juiz,

[NOTE]
====
. Governador provincial agindo pelo Senado romano.
. A província romana do sul da Grécia, cuja capital era Corinto.
====

[[v44-18-13]]

^<<v44-18-13,13>>^ dizendo: “Esta pessoa, contrário à lei, conduz os homens a outra persuasão na adoração de Deus.”

[[v44-18-14]]

^<<v44-18-14,14>>^ Mas, quando Paulo estava para abrir a sua boca, Gálio disse aos judeus: “Se se tratasse deveras de alguma injustiça ou dum ato iníquo de vilania, ó judeus, eu, com razão, vos suportaria pacientemente.

[[v44-18-15]]

^<<v44-18-15,15>>^ Mas, se se trata de controvérsias sobre palavras e nomes, e a lei entre vós, isso é convosco. Não quero ser juiz dessas coisas.”

[[v44-18-16]]

^<<v44-18-16,16>>^ Com isso os enxotou de diante da cadeira de juiz.

[[v44-18-17]]

^<<v44-18-17,17>>^ Agarraram assim Sóstenes, o presidente da sinagoga, e espancaram-no na frente da cadeira de juiz. Mas Gálio não se incomodava nada com estas coisas.

[[v44-18-18]]

^<<v44-18-18,18>>^ No entanto, depois de demorar-se mais alguns dias, Paulo despediu-se dos irmãos e passou a navegar para a Síria, e com ele Priscila e Áquila, visto que em Cencréia^&#42;1^ cortara rente o cabelo de sua cabeça, pois tinha um voto.

[NOTE]
====
. O porto de Corinto para pontos orientais.
====

[[v44-18-19]]

^<<v44-18-19,19>>^ Chegaram assim a Éfeso, e ele os deixou ali; ele mesmo, porém, entrou na sinagoga e raciocinou com os judeus.

[[v44-18-20]]

^<<v44-18-20,20>>^ Embora lhe solicitassem que permanecesse por mais tempo, não consentiu nisso,

[[v44-18-21]]

^<<v44-18-21,21>>^ mas despediu-se e disse-lhes: “Voltarei novamente a vós, se Jeová^&#42;1^ quiser.” E, de Éfeso, fez-se ao mar

[NOTE]
====
. Veja Ap. 1D.
====

[[v44-18-22]]

^<<v44-18-22,22>>^ e desceu a Cesaréia. Subiu^&#42;1^ e cumprimentou a congregação, e desceu a Antioquia.

[NOTE]
====
. Evidentemente a Jerusalém.
====

[[v44-18-23]]

^<<v44-18-23,23>>^ E, tendo passado ali algum tempo, partiu e foi de lugar em lugar através do país da Galácia e da Frígia, fortalecendo todos os discípulos.

[[v44-18-24]]

^<<v44-18-24,24>>^ Ora, chegou a Éfeso certo judeu de nome Apolo, natural de Alexandria, homem eloqüente; e ele era bem versado nas Escrituras.

[[v44-18-25]]

^<<v44-18-25,25>>^ Este [homem] tinha sido oralmente instruído no caminho de Jeová,^&#42;1^ e, visto que era fervoroso no espírito, falava e ensinava com precisão as coisas a respeito de Jesus, mas estava familiarizado apenas com o batismo de João.

[NOTE]
====
. Veja Ap. 1D.
====

[[v44-18-26]]

^<<v44-18-26,26>>^ E este [homem] principiou a falar denodadamente na sinagoga. Ouvindo-o Priscila e Áquila, acolheram-no na sua companhia e expuseram-lhe mais corretamente o caminho de Deus.

[[v44-18-27]]

^<<v44-18-27,27>>^ Além disso, já que ele desejava passar para a Acaia, os irmãos escreveram aos discípulos, exortando-os a que o recebessem benevolamente. Assim, chegando ele lá, ajudou grandemente os que tinham crido por causa da benignidade imerecida [de Deus];^&#42;1^

[NOTE]
====
. Lit. só “da benignidade imerecida”.
====

[[v44-18-28]]

^<<v44-18-28,28>>^ pois provava cabalmente, com intensidade e em público, que os judeus estavam errados, demonstrando pelas Escrituras que Jesus era o Cristo.

'''

xref:044-atos/044-atos-017.adoc#v44-17-0[&#60; Capítulo Anterior] | <<v44-18-0,Topo>> | xref:044-atos/044-atos-019.adoc#v44-19-0[Próximo Capítulo &#62;]