include::./index.adoc[]

[[v44-14-0]]
=== Atos, 14
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v44-14-1]]

^<<v44-14-1,1>>^ Ora, em Icônio entraram juntos na sinagoga dos judeus e falaram de tal maneira, que uma grande multidão, tanto de judeus como de gregos, se tornaram crentes.

[[v44-14-2]]

^<<v44-14-2,2>>^ Mas os judeus que não criam atiçavam e influenciavam injustamente as almas das pessoas das nações contra os irmãos.

[[v44-14-3]]

^<<v44-14-3,3>>^ Passaram, portanto, um tempo considerável falando com denodo pela autoridade de Jeová,^&#42;1^ o qual dava testemunho da palavra de sua benignidade imerecida por conceder que ocorressem sinais e portentos por intermédio das mãos deles.

[NOTE]
====
. Veja Ap. 1D.
====

[[v44-14-4]]

^<<v44-14-4,4>>^ No entanto, a multidão da cidade estava dividida, e alguns eram a favor dos judeus, mas outros a favor dos apóstolos.

[[v44-14-5]]

^<<v44-14-5,5>>^ Então, ocorrendo uma tentativa violenta, tanto da parte das pessoas das nações como dos judeus com os seus governantes, para os tratarem com insolência e lhes jogarem pedras,

[[v44-14-6]]

^<<v44-14-6,6>>^ eles, informados disso, fugiram para as cidades da Licaônia, Listra e Derbe, e a região circunvizinha;

[[v44-14-7]]

^<<v44-14-7,7>>^ e declaravam ali as boas novas.

[[v44-14-8]]

^<<v44-14-8,8>>^ Ora, em Listra estava sentado certo homem, incapacitado dos pés, coxo desde a madre de sua mãe, e ele nunca jamais tinha andado.

[[v44-14-9]]

^<<v44-14-9,9>>^ Este homem escutava Paulo falar, sendo que este, olhando para ele atentamente e vendo que tinha fé para ficar bom,^&#42;1^

[NOTE]
====
. Ou “para ser salvo”.
====

[[v44-14-10]]

^<<v44-14-10,10>>^ disse com voz alta: “Ergue-te ereto sobre os teus pés.” E ele pulou e começou a andar.

[[v44-14-11]]

^<<v44-14-11,11>>^ E as multidões, vendo o que Paulo tinha feito, elevaram as suas vozes, dizendo na língua licaônica: “Os deuses tornaram-se iguais a humanos e desceram a nós!”

[[v44-14-12]]

^<<v44-14-12,12>>^ E passaram a chamar a Barnabé de Zeus,^&#42;1^ mas a Paulo de Hermes,^&#42;2^ visto que ele tomava a dianteira no falar.

[NOTE]
====
. Ou “Júpiter”. Gr.: Dí·a; lat.: Ió·vem.
. Ou “Mercúrio”. Gr.: Her·mén; lat.: Mer·cú·ri·um.
====

[[v44-14-13]]

^<<v44-14-13,13>>^ E o sacerdote de Zeus, cujo [templo] estava diante da cidade,^&#42;1^ trouxe touros e grinaldas até os portões, e estava desejando oferecer sacrifícios com as multidões.

[NOTE]
====
. Lit.: “(que) estava diante da cidade”.
====

[[v44-14-14]]

^<<v44-14-14,14>>^ No entanto, quando os apóstolos Barnabé e Paulo ouviram isso, rasgaram as suas roupas exteriores e pularam para o meio da multidão, clamando

[[v44-14-15]]

^<<v44-14-15,15>>^ e dizendo: “Homens, por que estais fazendo estas coisas? Nós também somos humanos, tendo os mesmos padecimentos que vós, e vos estamos declarando as boas novas, para que vos desvieis destas coisas vãs para o Deus vivente, que fez o céu e a terra, e o mar, e todas as coisas neles.

[[v44-14-16]]

^<<v44-14-16,16>>^ Ele permitiu, nas gerações passadas, que todas as nações andassem nos seus [próprios] caminhos,

[[v44-14-17]]

^<<v44-14-17,17>>^ embora, deveras, não se deixou sem testemunho, por fazer o bem, dando-vos chuvas do céu e estações frutíferas, enchendo os vossos corações plenamente de alimento e de bom ânimo.”

[[v44-14-18]]

^<<v44-14-18,18>>^ Contudo, por dizerem estas coisas, mal continham as multidões de lhes oferecerem sacrifícios.

[[v44-14-19]]

^<<v44-14-19,19>>^ Mas, chegaram judeus de Antioquia e de Icônio, e persuadiram as multidões, e apedrejaram Paulo e o arrastaram para fora da cidade, julgando-o morto.

[[v44-14-20]]

^<<v44-14-20,20>>^ No entanto, quando os discípulos o cercaram, ele se levantou e entrou na cidade. E no dia seguinte partiu com Barnabé para Derbe.

[[v44-14-21]]

^<<v44-14-21,21>>^ E depois de declararem as boas novas àquela cidade e fazerem não poucos discípulos, voltaram a Listra, e a Icônio, e a Antioquia,

[[v44-14-22]]

^<<v44-14-22,22>>^ fortalecendo as almas dos discípulos, encorajando-os a permanecerem na fé e [dizendo]: “Temos de entrar no reino de Deus através de muitas tribulações.”

[[v44-14-23]]

^<<v44-14-23,23>>^ Outrossim, designaram-lhes^&#42;1^ anciãos em cada congregação, e, oferecendo orações com jejuns, encomendaram-nos a Jeová,^&#42;2^ em quem se tinham tornado crentes.

[NOTE]
====
. Lit.: “tendo designado [por mão estendida]”.
. Veja Ap. 1D.
====

[[v44-14-24]]

^<<v44-14-24,24>>^ E passando pela Pisídia, entraram na Panfília,

[[v44-14-25]]

^<<v44-14-25,25>>^ e, depois de falarem a palavra^&#42;1^ em Perge, desceram a Atália.

[NOTE]
====
. “Palavra”, BD; אACVgSyp: “palavra do Senhor”; P74: “palavra de Deus”; J17,28: “palavra de Jeová”.
====

[[v44-14-26]]

^<<v44-14-26,26>>^ E dali navegaram para Antioquia, onde tinham sido confiados à benignidade imerecida de Deus para a obra que tinham realizado plenamente.

[[v44-14-27]]

^<<v44-14-27,27>>^ Tendo chegado e tendo ajuntado a congregação, passaram a relatar as muitas coisas que Deus tinha feito por meio deles, e que ele abrira às nações a porta da fé.

[[v44-14-28]]

^<<v44-14-28,28>>^ Passaram assim não pouco tempo com os discípulos.

'''

xref:044-atos/044-atos-013.adoc#v44-13-0[&#60; Capítulo Anterior] | <<v44-14-0,Topo>> | xref:044-atos/044-atos-015.adoc#v44-15-0[Próximo Capítulo &#62;]