include::./index.adoc[]

[[v44-16-0]]
=== Atos, 16
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v44-16-1]]

^<<v44-16-1,1>>^ Chegou assim a Derbe e também a Listra. E, eis que havia ali um certo discípulo de nome Timóteo, filho duma mulher judia crente, mas de pai grego,

[[v44-16-2]]

^<<v44-16-2,2>>^ e os irmãos em Listra e Icônio davam dele bom relato.

[[v44-16-3]]

^<<v44-16-3,3>>^ Paulo expressou o desejo de que este homem fosse com ele, e, tomando-o, circuncidou-o por causa dos judeus que havia naqueles lugares, pois todos eles sabiam que seu pai era grego.

[[v44-16-4]]

^<<v44-16-4,4>>^ Ora, enquanto viajavam através das cidades, entregavam aos que estavam ali, para a sua observância, os decretos decididos pelos apóstolos e anciãos,^&#42;1^ que estavam em Jerusalém.

[NOTE]
====
. “Anciãos.” Veja 15:2 n.
====

[[v44-16-5]]

^<<v44-16-5,5>>^ Portanto, as congregações continuavam deveras a ser firmadas na fé e a aumentar em número, dia a dia.

[[v44-16-6]]

^<<v44-16-6,6>>^ Ainda mais, passaram pela Frígia e pelo país da Galácia, porque^&#42;1^ estavam proibidos pelo espírito santo de falar a palavra dentro [do distrito] da Ásia.

[NOTE]
====
. Ou “e”.
====

[[v44-16-7]]

^<<v44-16-7,7>>^ Outrossim, descendo a Mísia, fizeram esforços para entrar na Bitínia, mas o espírito de Jesus não lhes permitiu isso.

[[v44-16-8]]

^<<v44-16-8,8>>^ De modo que deixaram Mísia de lado e desceram a Trôade.

[[v44-16-9]]

^<<v44-16-9,9>>^ E, durante a noite, apareceu a Paulo uma visão: certo homem macedônio estava em pé, suplicando-lhe e dizendo: “Passa à Macedônia e ajuda-nos.”

[[v44-16-10]]

^<<v44-16-10,10>>^ Ora, assim que ele viu a visão, procuramos passar à Macedônia, tirando a conclusão de que Deus nos convocara para declarar-lhes as boas novas.^&#42;1^

[NOTE]
====
. “Declarar . . . as boas novas.” Gr.: eu·ag·ge·lí·sa·sthai; lat.: e·van·ge·li·zá·re.
====

[[v44-16-11]]

^<<v44-16-11,11>>^ Portanto, de Trôade fizemo-nos ao mar e fomos diretamente à Samotrácia, mas, no dia seguinte, a Neápolis,

[[v44-16-12]]

^<<v44-16-12,12>>^ e dali a Filipos, uma colônia, que é a cidade principal do distrito da Macedônia. Continuamos nesta cidade, passando [ali] alguns dias.

[[v44-16-13]]

^<<v44-16-13,13>>^ E, no dia de sábado, fomos para fora do portão, para junto dum rio, onde pensávamos haver um lugar de oração; e assentamo-nos e começamos a falar às mulheres que se haviam reunido.

[[v44-16-14]]

^<<v44-16-14,14>>^ E certa mulher, de nome Lídia, vendedora de púrpura, da cidade de Tiatira, e adoradora de Deus, estava escutando, e Jeová^&#42;1^ abriu-lhe amplamente o coração para prestar atenção às coisas faladas por Paulo.

[NOTE]
====
. Veja Ap. 1D.
====

[[v44-16-15]]

^<<v44-16-15,15>>^ Então, quando ela e sua família foram batizadas, disse, suplicando: “Se vós me julgastes fiel a Jeová,^&#42;1^ entrai na minha casa e ficai.” E ela simplesmente nos fez ir.

[NOTE]
====
. “A Jeová”, J7,8,10; אAB(gr.): toi Ky·rí·oi; D: “a Deus”. Veja Ap. 1D.
====

[[v44-16-16]]

^<<v44-16-16,16>>^ E aconteceu que, quando íamos para o lugar de oração, veio-nos ao encontro certa serva com um espírito, um demônio de adivinhação.^&#42;1^ Ela costumava fornecer muito ganho aos seus amos por praticar a arte do vaticínio.

[NOTE]
====
. Lit.: “com um espírito de píton”, termo associado com o oráculo de Delfos. Gr.: é·khou·san pneú·ma pý·tho·na.
====

[[v44-16-17]]

^<<v44-16-17,17>>^ Esta [moça] seguia Paulo e a nós, e clamava com as palavras: “Estes homens são escravos do Deus Altíssimo, que vos estão publicando o caminho da salvação.”

[[v44-16-18]]

^<<v44-16-18,18>>^ Ela fazia isso por muitos dias. Por fim, Paulo ficou cansado disso, e, voltando-se, disse ao espírito: “Ordeno-te em nome de Jesus Cristo que saias dela.” E saiu dela naquela mesma hora.

[[v44-16-19]]

^<<v44-16-19,19>>^ Pois bem, quando os amos dela viram que acabara sua esperança de ganho, agarraram Paulo e Silas e os arrastaram para a feira,^&#42;1^ perante os governantes,

[NOTE]
====
. Ou “foro”. Gr.: a·go·rán; lat.: fó·rum. Lugar de reuniões públicas.
====

[[v44-16-20]]

^<<v44-16-20,20>>^ e, conduzindo-os até os magistrados civis, disseram: “Estes homens estão perturbando muito a nossa cidade, sendo eles judeus,

[[v44-16-21]]

^<<v44-16-21,21>>^ e publicam costumes que não nos é lícito adotar ou praticar, por sermos romanos.”

[[v44-16-22]]

^<<v44-16-22,22>>^ E a multidão levantou-se toda contra eles; e os magistrados civis, depois de lhes arrancarem as roupas exteriores, mandaram que fossem espancados com varas.

[[v44-16-23]]

^<<v44-16-23,23>>^ Depois de lhes terem infligido muitos golpes, lançaram-nos na prisão, ordenando ao carcereiro que os mantivesse seguros.

[[v44-16-24]]

^<<v44-16-24,24>>^ Ele, por ter recebido tal ordem, lançou-os na prisão interior e prendeu os seus pés no tronco.

[[v44-16-25]]

^<<v44-16-25,25>>^ Mas, pelo meio da noite, Paulo e Silas estavam orando e louvando a Deus com cântico; sim, os prisioneiros os ouviam.

[[v44-16-26]]

^<<v44-16-26,26>>^ Repentinamente, houve um grande terremoto, de modo que os alicerces da cadeia foram abalados. Ademais, abriram-se instantaneamente todas as portas e soltaram-se os laços de todos.

[[v44-16-27]]

^<<v44-16-27,27>>^ O carcereiro, acordando do sono e vendo abertas as portas da prisão, puxou a sua espada e estava prestes a acabar consigo, imaginando que os prisioneiros tinham escapado.

[[v44-16-28]]

^<<v44-16-28,28>>^ Mas Paulo clamou com voz alta, dizendo: “Não te faças dano, pois estamos todos aqui!”

[[v44-16-29]]

^<<v44-16-29,29>>^ Ele pediu assim luzes e pulou para dentro, e, tomado de tremor, prostrou-se diante de Paulo e Silas.

[[v44-16-30]]

^<<v44-16-30,30>>^ E ele os trouxe para fora e disse: “Senhores, o que tenho de fazer para ser salvo?”

[[v44-16-31]]

^<<v44-16-31,31>>^ Disseram: “Crê no Senhor Jesus e serás salvo, tu e a tua família.”

[[v44-16-32]]

^<<v44-16-32,32>>^ E falaram a palavra de Jeová^&#42;1^ a ele e a todos os na sua casa.

[NOTE]
====
. “De Jeová”, J7,8,10,17,18,22,23,28; P45,74אcAC(gr.): tou Ky·rí·ou; א°B: “de Deus”. Veja Ap. 1D.
====

[[v44-16-33]]

^<<v44-16-33,33>>^ E ele os levou consigo naquela hora da noite e banhou os seus vergões; e todos juntos, ele e os seus, foram batizados sem demora.

[[v44-16-34]]

^<<v44-16-34,34>>^ E ele os trouxe à sua casa e pôs a mesa diante deles, e alegrou-se grandemente, com toda a sua família, agora que tinha crido em Deus.

[[v44-16-35]]

^<<v44-16-35,35>>^ Quando ficou dia, os magistrados civis mandaram os esbirros para dizer: “Livra estes homens.”

[[v44-16-36]]

^<<v44-16-36,36>>^ O carcereiro relatou assim as palavras deles a Paulo: “Os magistrados civis mandaram homens para que vós [dois] fôsseis livrados. Agora, portanto, saí e ide em paz.”

[[v44-16-37]]

^<<v44-16-37,37>>^ Mas Paulo disse-lhes: “Chibatearam-nos publicamente sem condenação, a homens que são romanos, e lançaram-nos na prisão; e agora nos lançam fora secretamente? Não, deveras, mas que venham eles mesmos e nos levem para fora.”

[[v44-16-38]]

^<<v44-16-38,38>>^ De modo que os esbirros relataram estas declarações aos magistrados civis. Estes ficaram temerosos quando ouviram que os homens eram romanos.

[[v44-16-39]]

^<<v44-16-39,39>>^ Conseqüentemente, vieram e suplicaram-lhes, e, depois de os trazerem para fora, solicitaram-lhes que partissem da cidade.

[[v44-16-40]]

^<<v44-16-40,40>>^ Mas eles saíram da prisão e foram ao lar de Lídia, e quando viram os irmãos, encorajaram-nos e partiram.

'''

xref:044-atos/044-atos-015.adoc#v44-15-0[&#60; Capítulo Anterior] | <<v44-16-0,Topo>> | xref:044-atos/044-atos-017.adoc#v44-17-0[Próximo Capítulo &#62;]