include::./index.adoc[]

[[v44-9-0]]
=== Atos, 9
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v44-9-1]]

^<<v44-9-1,1>>^ Saulo, porém, respirando ainda ameaça e assassínio contra os discípulos do Senhor, foi ao sumo sacerdote

[[v44-9-2]]

^<<v44-9-2,2>>^ e pediu-lhe cartas para as sinagogas em Damasco, a fim de trazer amarrados, para Jerusalém, quaisquer que achasse pertencendo ao Caminho,^&#42;1^ tanto homens como mulheres.

[NOTE]
====
. “Ao Caminho.” Gr.: tes ho·doú.
====

[[v44-9-3]]

^<<v44-9-3,3>>^ Então, na viagem, aproximava-se de Damasco, quando repentinamente reluziu em volta dele uma luz do céu,

[[v44-9-4]]

^<<v44-9-4,4>>^ e ele caiu ao chão e ouviu uma voz dizer-lhe: “Saulo, Saulo, por que me persegues?”

[[v44-9-5]]

^<<v44-9-5,5>>^ Ele disse: “Quem és, Senhor?” Ele disse: “Eu sou Jesus, a quem tu persegues.

[[v44-9-6]]

^<<v44-9-6,6>>^ Não obstante, levanta-te e entra na cidade, e ser-te-á dito o que tens de fazer.”

[[v44-9-7]]

^<<v44-9-7,7>>^ Ora, os homens que viajavam com ele ficaram parados sem fala, ouvindo, deveras, o som duma voz, mas não observando nenhum homem.

[[v44-9-8]]

^<<v44-9-8,8>>^ Saulo, porém, levantou-se do chão, e, embora se lhe abrissem os olhos, não via nada. De modo que o levaram pela mão e o conduziram a Damasco.

[[v44-9-9]]

^<<v44-9-9,9>>^ E ele não viu nada, por três dias, e não comeu nem bebeu.

[[v44-9-10]]

^<<v44-9-10,10>>^ Havia em Damasco certo discípulo de nome Ananias, e o Senhor disse-lhe numa visão: “Ananias!” Ele disse: “Eis-me aqui, Senhor.”

[[v44-9-11]]

^<<v44-9-11,11>>^ O Senhor disse-lhe: “Levanta-te, vai à rua chamada Direita, e procura na casa de Judas um homem de nome Saulo, de Tarso. Pois, eis que está orando,

[[v44-9-12]]

^<<v44-9-12,12>>^ e ele viu numa visão^&#42;1^ um homem de nome Ananias entrar e pôr as suas mãos sobre ele, para que recuperasse a vista.”

[NOTE]
====
. “Numa visão”, BCSyh,pArm; P74אAVg omitem isso.
====

[[v44-9-13]]

^<<v44-9-13,13>>^ Mas, Ananias respondeu: “Senhor, eu ouvi muitos [falar] deste homem, quantas coisas prejudiciais ele fez aos teus santos em Jerusalém.

[[v44-9-14]]

^<<v44-9-14,14>>^ E ele tem aqui autoridade dos principais sacerdotes para pôr em laços a todos os que invocam o teu nome.”

[[v44-9-15]]

^<<v44-9-15,15>>^ Mas o Senhor lhe disse: “Vai, porque este homem é para mim um vaso escolhido, para levar o meu nome às nações, bem como a reis e aos filhos de Israel.

[[v44-9-16]]

^<<v44-9-16,16>>^ Pois eu lhe mostrarei claramente quantas coisas ele tem de sofrer por meu nome.”

[[v44-9-17]]

^<<v44-9-17,17>>^ Ananias foi, assim, e entrou na casa, e pôs as suas mãos sobre ele e disse: “Saulo, irmão, o Senhor, o Jesus que te apareceu na estrada pela qual vieste, enviou-me a fim de que recuperasses a vista e ficasses cheio de espírito santo.”

[[v44-9-18]]

^<<v44-9-18,18>>^ E imediatamente caíram-lhe dos olhos o que parecia escamas, e ele recuperou a vista; e, levantando-se, foi batizado,

[[v44-9-19]]

^<<v44-9-19,19>>^ e tomou alimento e ganhou força.
Ele ficou alguns dias com os discípulos em Damasco

[[v44-9-20]]

^<<v44-9-20,20>>^ e começou imediatamente, nas sinagogas, a pregar Jesus, que Este é o Filho de Deus.

[[v44-9-21]]

^<<v44-9-21,21>>^ Mas todos os que o ouviam foram tomados de assombro e diziam: “Não é este o homem que devastava em Jerusalém os que invocavam este nome, e que viera para cá com o mesmo propósito, para levá-los amarrados aos principais sacerdotes?”

[[v44-9-22]]

^<<v44-9-22,22>>^ Mas, Saulo adquiria ainda mais poder e confundia os judeus que moravam em Damasco, ao provar logicamente que este é o Cristo.

[[v44-9-23]]

^<<v44-9-23,23>>^ Decorrido um bom número de dias, os judeus realizaram entre si uma consulta para o eliminarem.

[[v44-9-24]]

^<<v44-9-24,24>>^ No entanto, Saulo ficou sabendo da sua conspiração contra ele. Mas, eles estavam também vigiando de perto os portões, tanto de dia como de noite, a fim de o eliminarem.

[[v44-9-25]]

^<<v44-9-25,25>>^ De modo que seus discípulos o tomaram e o arriaram de noite através duma abertura no muro, fazendo-o descer num cesto.

[[v44-9-26]]

^<<v44-9-26,26>>^ Chegando a Jerusalém, fez esforços para se juntar aos discípulos; mas todos eles estavam com medo dele, porque não acreditavam que fosse discípulo.

[[v44-9-27]]

^<<v44-9-27,27>>^ Barnabé veio, assim, em seu auxílio e o conduziu aos apóstolos, e ele lhes contou em pormenores como tinha visto o Senhor na estrada e que este lhe tinha falado, e como em Damasco falara denodadamente no nome de Jesus.

[[v44-9-28]]

^<<v44-9-28,28>>^ E continuou com eles, entrando e saindo,^&#42;1^ em Jerusalém, falando denodadamente no nome do Senhor;

[NOTE]
====
. Ou “levando a sua vida cotidiana”.
====

[[v44-9-29]]

^<<v44-9-29,29>>^ e falava e discutia com os judeus que falavam grego.^&#42;1^ Mas estes fizeram tentativas para o eliminarem.

[NOTE]
====
. Lit.: “os helenistas”. J17: “os judeus gregos”.
====

[[v44-9-30]]

^<<v44-9-30,30>>^ Quando os irmãos perceberam isso, trouxeram-no para baixo a Cesaréia e o enviaram a Tarso.

[[v44-9-31]]

^<<v44-9-31,31>>^ Deveras, a congregação através de toda a Judéia, e Galiléia, e Samaria, entrou então num período de paz, sendo edificada; e, como andava no temor de Jeová^&#42;1^ e no consolo do espírito santo, multiplicava-se.

[NOTE]
====
. Veja Ap. 1D.
====

[[v44-9-32]]

^<<v44-9-32,32>>^ Então, passando Pedro através de todas [as partes], desceu também aos santos que moravam em Lida.

[[v44-9-33]]

^<<v44-9-33,33>>^ Ali ele achou certo homem de nome Enéias que já por oito anos jazia na sua maca, visto que era paralítico.

[[v44-9-34]]

^<<v44-9-34,34>>^ E Pedro disse-lhe: “Enéias, Jesus Cristo te sara. Levanta-te e arruma a tua cama.” E ele se levantou imediatamente.

[[v44-9-35]]

^<<v44-9-35,35>>^ E todos os que habitavam em Lida e [na planície de] Sarom^&#42;1^ o viram, e estes se voltaram para o Senhor.

[NOTE]
====
. “Sarona”, J17,18,22; אAB: “Sarom”.
====

[[v44-9-36]]

^<<v44-9-36,36>>^ Mas, havia em Jope certa discípula de nome Tabita, que, traduzido, significa Dorcas.^&#42;1^ Ela abundava em boas ações e nas dádivas de misericórdia que fazia.

[NOTE]
====
. “Dorcas” (gr.), correspondente a “Tabita” (aram.); ambos os nomes significam “Gazela”.
====

[[v44-9-37]]

^<<v44-9-37,37>>^ Mas, aconteceu que naqueles dias ela adoeceu e morreu. De modo que a banharam e deitaram num quarto de andar superior.

[[v44-9-38]]

^<<v44-9-38,38>>^ Ora, visto que Lida era perto de Jope, quando os discípulos ouviram que Pedro estava naquela cidade, mandaram a ele dois homens para [lhe] suplicarem: “Por favor, não hesites^&#42;1^ em vir ter conosco.”

[NOTE]
====
. Ou “não demores”.
====

[[v44-9-39]]

^<<v44-9-39,39>>^ Em vista disso, Pedro levantou-se e foi com eles. E, ao chegar, conduziram-no para cima ao quarto de andar superior; e todas as viúvas apresentaram-se a ele chorando e mostrando muitas roupas interiores e roupas exteriores que Dorcas costumava fazer enquanto estava com elas.

[[v44-9-40]]

^<<v44-9-40,40>>^ Mas Pedro pôs a todos para fora, e, dobrando os joelhos, orou, e, voltando-se para o corpo, disse: “Tabita,^&#42;1^ levanta-te!” Ela abriu os olhos, e, avistando Pedro, sentou-se.

[NOTE]
====
. Veja v. 36 n.
====

[[v44-9-41]]

^<<v44-9-41,41>>^ Dando-lhe a mão, ele a levantou e chamou os santos, e as viúvas, e a apresentou viva.

[[v44-9-42]]

^<<v44-9-42,42>>^ Isto se tornou conhecido em toda a Jope, e muitos ficaram crentes no Senhor.

[[v44-9-43]]

^<<v44-9-43,43>>^ Ele ficou muitos dias em Jope com um certo Simão, [que era] curtidor.

'''

xref:044-atos/044-atos-008.adoc#v44-8-0[&#60; Capítulo Anterior] | <<v44-9-0,Topo>> | xref:044-atos/044-atos-010.adoc#v44-10-0[Próximo Capítulo &#62;]