include::./index.adoc[]

[[v44-8-0]]
=== Atos, 8
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v44-8-1]]

^<<v44-8-1,1>>^ Saulo, da sua parte, aprovava o assassínio dele.
Naquele dia levantou-se grande perseguição contra a congregação que estava em Jerusalém; todos, exceto os apóstolos, foram espalhados através das regiões da Judéia e de Samaria.

[[v44-8-2]]

^<<v44-8-2,2>>^ Homens reverentes, porém, levaram Estêvão para o enterrarem, e fizeram grande lamentação sobre ele.

[[v44-8-3]]

^<<v44-8-3,3>>^ Saulo, porém, começou a tratar a congregação de modo ultrajante. Invadindo uma casa após outra, e, arrastando para fora tanto homens como mulheres, entregava-os à prisão.

[[v44-8-4]]

^<<v44-8-4,4>>^ No entanto, os que tinham sido espalhados iam pelo país declarando as boas novas da palavra.

[[v44-8-5]]

^<<v44-8-5,5>>^ Quanto a Filipe, desceu à cidade de Samaria e começou a pregar-lhes o Cristo.

[[v44-8-6]]

^<<v44-8-6,6>>^ As multidões, de comum acordo, prestavam atenção às coisas ditas por Filipe, escutando e olhando para os sinais que ele realizava.

[[v44-8-7]]

^<<v44-8-7,7>>^ Pois havia muitos que tinham espíritos impuros, e estes clamavam com voz alta e saíam. Além disso, foram curados muitos paralíticos e coxos.

[[v44-8-8]]

^<<v44-8-8,8>>^ De modo que havia muita alegria naquela cidade.

[[v44-8-9]]

^<<v44-8-9,9>>^ Ora, havia na cidade certo homem de nome Simão, o qual, antes disso, praticara as artes mágicas e pasmara a nação de Samaria, dizendo ser alguém grande.

[[v44-8-10]]

^<<v44-8-10,10>>^ E todos eles, desde o menor até o maior, prestavam-lhe atenção e diziam: “Este homem é o Poder de Deus, que pode ser chamado Grande.”

[[v44-8-11]]

^<<v44-8-11,11>>^ De modo que lhe prestavam atenção, por tê-los deixado pasmados por bastante tempo com as suas artes mágicas.

[[v44-8-12]]

^<<v44-8-12,12>>^ Mas, quando acreditaram em Filipe, que estava declarando as boas novas do reino de Deus e do nome de Jesus Cristo, passaram a ser batizados, tanto homens como mulheres.

[[v44-8-13]]

^<<v44-8-13,13>>^ O próprio Simão também se tornou crente, e, tendo sido batizado, assistia constantemente Filipe; e ele pasmava-se, observando a ocorrência de sinais e grandes obras poderosas.

[[v44-8-14]]

^<<v44-8-14,14>>^ Quando os apóstolos em Jerusalém ouviram que Samaria havia aceito a palavra de Deus, mandaram-lhes Pedro e João;

[[v44-8-15]]

^<<v44-8-15,15>>^ e estes desceram e oraram para que recebessem espírito santo.

[[v44-8-16]]

^<<v44-8-16,16>>^ Porque não tinha ainda caído sobre nenhum deles, mas eles tinham sido batizados apenas no nome do Senhor Jesus.

[[v44-8-17]]

^<<v44-8-17,17>>^ Impuseram-lhes então as suas mãos e eles começaram a receber espírito santo.

[[v44-8-18]]

^<<v44-8-18,18>>^ Ora, vendo Simão que o espírito era dado pela imposição das mãos dos apóstolos, ofereceu-lhes dinheiro,

[[v44-8-19]]

^<<v44-8-19,19>>^ dizendo: “Dai-me também esta autoridade, para que todo aquele a quem eu impuser as minhas mãos receba espírito santo.”

[[v44-8-20]]

^<<v44-8-20,20>>^ Mas Pedro disse-lhe: “Pereça contigo a tua prata, porque pensaste obter posse da dádiva gratuita de Deus por meio de dinheiro.

[[v44-8-21]]

^<<v44-8-21,21>>^ Não tens nem parte nem quinhão neste assunto, porque o teu coração não é reto à vista de Deus.

[[v44-8-22]]

^<<v44-8-22,22>>^ Arrepende-te, portanto, desta maldade tua, e suplica a Jeová,^&#42;1^ para que, se possível, te seja perdoada esta astúcia do teu coração;

[NOTE]
====
. “Jeová”, J18,22,23; gr.: tou Ky·rí·ou; VgSyp: “Deus”. Veja Ap. 1D.
====

[[v44-8-23]]

^<<v44-8-23,23>>^ pois vejo que tu és um^&#42;1^ fel venenoso e um laço de injustiça.”

[NOTE]
====
. “Estás num”, D°Vg.
====

[[v44-8-24]]

^<<v44-8-24,24>>^ Simão disse em resposta: “Fazei súplica a Jeová^&#42;1^ por mim, para que nenhuma destas coisas que dissestes venha sobre mim.”

[NOTE]
====
. “Jeová”, J7,8,10,13,15-18,22,23; אAB(gr.): ton Ký·ri·on; DVgmss.Syh,p: “Deus”. Veja Ap. 1D.
====

[[v44-8-25]]

^<<v44-8-25,25>>^ Portanto, tendo eles dado cabalmente testemunho e falado a palavra de Jeová,^&#42;1^ voltaram a Jerusalém, e declaravam as boas novas a muitas aldeias dos samaritanos.

[NOTE]
====
. “De Jeová”, J7,8,10,17,18; אBCD(gr.): tou Ky·rí·ou; P74ASyp: “de Deus”. Veja Ap. 1D.
====

[[v44-8-26]]

^<<v44-8-26,26>>^ No entanto, o anjo de Jeová^&#42;1^ falou a Filipe, dizendo: “Levanta-te e vai para o sul, à estrada que desce de Jerusalém para Gaza.” (Esta é a estrada do deserto.)

[NOTE]
====
. Veja Ap. 1D.
====

[[v44-8-27]]

^<<v44-8-27,27>>^ Em vista disso, levantou-se e foi, e eis um eunuco etíope, homem de poder sob Candace, rainha dos etíopes, que estava sobre todo o tesouro dela. Tinha ido a Jerusalém para adorar,

[[v44-8-28]]

^<<v44-8-28,28>>^ mas regressava e estava sentado no seu carro, e lia em voz alta o profeta Isaías.

[[v44-8-29]]

^<<v44-8-29,29>>^ De modo que o espírito disse a Filipe: “Aproxima-te e junta-te a este carro.”

[[v44-8-30]]

^<<v44-8-30,30>>^ Filipe correu ao lado [dele] e ouviu-o lendo em voz alta Isaías, o profeta, e disse: “Sabes realmente o que estás lendo?”

[[v44-8-31]]

^<<v44-8-31,31>>^ Ele disse: “Realmente, como é que eu posso, a menos que alguém me guie?” E suplicou que Filipe subisse e se assentasse com ele.

[[v44-8-32]]

^<<v44-8-32,32>>^ Ora, a passagem da Escritura que estava lendo em voz alta era: “Como ovelha ele foi levado à matança e como cordeiro que está sem voz diante do seu tosquiador, assim não abre a sua boca.

[[v44-8-33]]

^<<v44-8-33,33>>^ Durante a sua humilhação foi-lhe tirado o julgamento. Quem contará os pormenores de sua geração?^&#42;1^ Porque a sua vida lhe é tirada da terra.”

[NOTE]
====
. Ou “seu modo de vida”.
====

[[v44-8-34]]

^<<v44-8-34,34>>^ Em resposta, o eunuco disse a Filipe: “Rogo-te: A respeito de quem diz isso o profeta? A respeito de si mesmo ou a respeito de outro homem?”

[[v44-8-35]]

^<<v44-8-35,35>>^ Filipe abriu a sua boca e, principiando com esta escritura, declarou-lhe as boas novas a respeito de Jesus.

[[v44-8-36]]

^<<v44-8-36,36>>^ Então, ao avançarem pela estrada, chegaram a certo corpo de água, e o eunuco disse: “Eis um corpo de água! O que me impede ser batizado?”

[[v44-8-37]]

^<<v44-8-37,37>>^ ^&#42;1^ ——

[NOTE]
====
. P45,74אABCVgSyp omitem o v. 37; ItVgcArm: “Filipe disse-lhe: ‘Se crês de todo o coração, é permissível.’ Em resposta ele disse: ‘Creio que Jesus Cristo é o Filho de Deus.’”
====

[[v44-8-38]]

^<<v44-8-38,38>>^ Com isso mandou parar o carro, e ambos desceram à água, tanto Filipe como o eunuco; e ele o batizou.

[[v44-8-39]]

^<<v44-8-39,39>>^ Tendo eles saído da água, o espírito de Jeová^&#42;1^ conduziu Filipe rapidamente dali, e o eunuco não o viu mais, pois seguiu caminho, alegrando-se.

[NOTE]
====
. Veja Ap. 1D.
====

[[v44-8-40]]

^<<v44-8-40,40>>^ Mas Filipe achou-se em Asdode,^&#42;1^ e, passando pelo território, declarava as boas novas a todas as cidades, até chegar a Cesaréia.

[NOTE]
====
. “Asdode”, J17,18,22; אAB: “Azoto”.
====

'''

xref:044-atos/044-atos-007.adoc#v44-7-0[&#60; Capítulo Anterior] | <<v44-8-0,Topo>> | xref:044-atos/044-atos-009.adoc#v44-9-0[Próximo Capítulo &#62;]