include::./index.adoc[]

[[v14-26-0]]
=== 2 Crônicas, 26
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v14-26-1]]

^<<v14-26-1,1>>^ Então todo o povo de Judá tomou Uzias,^&#42;1^ que tinha dezesseis anos de idade, e o fez rei em lugar de seu pai Amazias.

[NOTE]
====
. Significando “Minha Força É Jeová”. Hebr.: ‛Uz·zi·yá·hu.
====

[[v14-26-2]]

^<<v14-26-2,2>>^ Foi ele quem reconstruiu Elote e então a restituiu a Judá, depois que o rei se deitara com os seus antepassados.

[[v14-26-3]]

^<<v14-26-3,3>>^ Uzias tinha dezesseis anos de idade quando começou a reinar e reinou por cinqüenta e dois anos em Jerusalém. E o nome de sua mãe era Jecolia, de Jerusalém.

[[v14-26-4]]

^<<v14-26-4,4>>^ E ele fazia o que era direito aos olhos de Jeová, segundo tudo o que Amazias, seu pai, tinha feito.

[[v14-26-5]]

^<<v14-26-5,5>>^ E tendia continuamente a buscar a Deus nos dias de Zacarias, instrutor no temor do [verdadeiro] Deus; e nos dias em que buscava a Jeová, o [verdadeiro] Deus o tornou próspero.

[[v14-26-6]]

^<<v14-26-6,6>>^ E ele passou a sair e a lutar contra os filisteus, e a romper pela muralha de Gate, e pela muralha de Jabné, e pela muralha de Asdode, construindo depois cidades no [território de] Asdode e entre os filisteus.

[[v14-26-7]]

^<<v14-26-7,7>>^ E o [verdadeiro] Deus continuou a ajudá-lo contra os filisteus e contra os árabes que moravam em Gurbaal, e os meunins.

[[v14-26-8]]

^<<v14-26-8,8>>^ E os amonitas começaram a dar tributo a Uzias. Finalmente, a sua fama ia até o Egito, pois demonstrou ter força num grau extraordinário.

[[v14-26-9]]

^<<v14-26-9,9>>^ Além disso, Uzias construiu torres em Jerusalém, junto ao Portão da Esquina, e junto ao Portão do Vale, e junto ao Contraforte, e os reforçou.

[[v14-26-10]]

^<<v14-26-10,10>>^ Outrossim, construiu torres no ermo e escavou muitas cisternas (porque muitíssimo gado se tornara seu), e também na Sefelá e no planalto. Havia lavradores e vinhateiros nos montes e no Carmelo, pois mostrava ser amante da agricultura.

[[v14-26-11]]

^<<v14-26-11,11>>^ Ademais, Uzias veio a ter uma força empenhada em guerra, os que saíam no serviço militar em tropas, segundo o número do seu registro pela mão de Jeiel, o secretário, e de Maaséias, oficial sob o controle de Hananias, dos príncipes do rei.

[[v14-26-12]]

^<<v14-26-12,12>>^ O número inteiro dos cabeças das casas paternas, dos homens poderosos, valentes, era de dois mil e seiscentos.

[[v14-26-13]]

^<<v14-26-13,13>>^ E sob o seu controle, as forças armadas eram de trezentos e sete mil e quinhentos homens empenhados em guerra, com o poder duma força militar para ajudar o rei contra o inimigo.

[[v14-26-14]]

^<<v14-26-14,14>>^ E Uzias continuou a fazer preparativos para eles, para o exército inteiro, escudos, e lanças, e capacetes, e cotas de malha, e arcos, e pedras de funda.

[[v14-26-15]]

^<<v14-26-15,15>>^ Ainda mais, fez em Jerusalém máquinas de guerra, invenção de engenheiros, para que viessem a ficar sobre as torres e sobre as esquinas para atirar flechas e grandes pedras. Em conseqüência disso, sua fama saiu à grande distância, porque foi ajudado maravilhosamente até ficar forte.

[[v14-26-16]]

^<<v14-26-16,16>>^ Todavia, assim que ficou forte, ensoberbeceu-se o seu coração a ponto de causar a ruína, de modo que agiu de maneira infiel contra Jeová, seu Deus, e entrou no templo de Jeová para queimar incenso sobre o altar do incenso.

[[v14-26-17]]

^<<v14-26-17,17>>^ Azarias, o sacerdote, e com ele sacerdotes de Jeová, oitenta homens valentes, entraram imediatamente atrás dele.

[[v14-26-18]]

^<<v14-26-18,18>>^ Puseram-se então de pé contra Uzias, o rei, e disseram-lhe: “Não cabe a ti, ó Uzias, queimar incenso a Jeová, mas cabe aos sacerdotes, filhos de Arão, aos santificados, queimar incenso. Sai do santuário; pois agiste de modo infiel e não te é para glória da parte de Jeová Deus.”

[[v14-26-19]]

^<<v14-26-19,19>>^ Uzias, porém, foi tomado de fúria enquanto havia na sua mão um incensário para queimar incenso, e durante o seu acesso de fúria contra os sacerdotes apareceu subitamente a própria lepra na testa dele diante dos sacerdotes na casa de Jeová, ao lado do altar do incenso.

[[v14-26-20]]

^<<v14-26-20,20>>^ Quando Azarias, o sacerdote principal,^&#42;1^ e todos os sacerdotes se viraram para ele, ora, eis que estava atacado de lepra na sua testa! De modo que eles, exaltados, começaram a levá-lo para fora e ele mesmo se apressou também a sair, porque Jeová o havia atingido.

[NOTE]
====
. Ou “o sumo sacerdote”. LXX: “o primeiro sacerdote”; lat.: pón·ti·fex.
====

[[v14-26-21]]

^<<v14-26-21,21>>^ E Uzias, o rei, continuou a ser leproso até o dia da sua morte e ficou morando numa casa, livre de deveres, como leproso; porque tinha sido cortado da casa de Jeová, ao passo que Jotão, seu filho, estava sobre a casa do rei, julgando o povo da terra.

[[v14-26-22]]

^<<v14-26-22,22>>^ E o resto dos assuntos de Uzias, os primeiros e os últimos, foram escritos por Isaías,^&#42;1^ filho de Amoz, o profeta.

[NOTE]
====
. Significando “Salvação de Jeová”. Hebr.: Yesha·‛eyá·hu.
====

[[v14-26-23]]

^<<v14-26-23,23>>^ Por fim, Uzias deitou-se com os seus antepassados; e enterraram-no, pois, com os seus antepassados, [mas] no campo de inumação pertencente aos reis, porque disseram: “Ele é leproso.” E Jotão, seu filho, começou a reinar em seu lugar.

'''

xref:014-2-cronicas/014-2-cronicas-025.adoc#v14-25-0[&#60; Capítulo Anterior] | <<v14-26-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-027.adoc#v14-27-0[Próximo Capítulo &#62;]