include::./index.adoc[]

[[v14-35-0]]
=== 2 Crônicas, 35
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v14-35-1]]

^<<v14-35-1,1>>^ Josias celebrou então em Jerusalém uma páscoa a Jeová, e eles abateram a vítima pascoal no décimo quarto dia do primeiro mês.

[[v14-35-2]]

^<<v14-35-2,2>>^ Assim, ele pôs os sacerdotes sobre as coisas sob o seu cuidado e encorajou-os no serviço da casa de Jeová.

[[v14-35-3]]

^<<v14-35-3,3>>^ E prosseguiu, dizendo aos levitas, os instrutores de todo o Israel, os que eram santos para Jeová: “Ponde a Arca sagrada na casa construída por Salomão, filho de Davi, rei de Israel; não é vossa como carga sobre o ombro. Agora servi a Jeová, vosso Deus, e ao seu povo Israel.

[[v14-35-4]]

^<<v14-35-4,4>>^ E fazei preparativos conforme a casa de vossos antepassados, segundo as vossas turmas, pelo que foi escrito por Davi, rei de Israel, e pelo que foi escrito por Salomão, seu filho.

[[v14-35-5]]

^<<v14-35-5,5>>^ E ficai de pé no lugar santo segundo os grupos^&#42;1^ da casa dos antepassados, para os vossos irmãos, os filhos do povo, e o quinhão duma casa paterna, pertencente aos levitas.

[NOTE]
====
. Lit.: “divisões”.
====

[[v14-35-6]]

^<<v14-35-6,6>>^ E abatei a vítima pascoal e santificai-vos, e fazei preparativos para os vossos irmãos, para fazer segundo a palavra de Jeová por intermédio de Moisés.”

[[v14-35-7]]

^<<v14-35-7,7>>^ Josias contribuiu então, para os filhos do povo, rebanhos, cordeiros e cabritinhos,^&#42;1^ todos como vítimas pascoais, para todos os que se podiam achar, no número de trinta mil, e gado vacum, três mil. Estes procediam dos bens do rei.

[NOTE]
====
. Lit.: “filhos dos bodes”.
====

[[v14-35-8]]

^<<v14-35-8,8>>^ E os próprios príncipes dele fizeram uma contribuição como oferta voluntária para o povo, para os sacerdotes e para os levitas. Mesmo Hilquias,^&#42;1^ e Zacarias, e Jeiel, como líderes da casa do [verdadeiro] Deus, deram aos sacerdotes, como vítimas pascoais, dois mil e seiscentos, bem como trezentas cabeças de gado vacum.

[NOTE]
====
. “Hilquias.” Hebr.: Hhil·qi·yáh.
====

[[v14-35-9]]

^<<v14-35-9,9>>^ E Conanias, e Semaías, e Netanel, seus irmãos, bem como Hasabias, e Jeiel, e Jozabade, chefes dos levitas, contribuíram para os levitas, como vítimas pascoais, cinco mil, bem como quinhentas cabeças de gado vacum.

[[v14-35-10]]

^<<v14-35-10,10>>^ E preparou-se o serviço e os sacerdotes ficaram de pé nos seus lugares, e os levitas, segundo as suas turmas, de acordo com o mandamento do rei.

[[v14-35-11]]

^<<v14-35-11,11>>^ E passaram a abater a vítima pascoal e os sacerdotes aspergiram [o sangue] da mão deles,^&#42;1^ enquanto os levitas tiravam as peles.

[NOTE]
====
. “O sangue da mão deles”, LXX; Sy: “um pouco do sangue”.
====

[[v14-35-12]]

^<<v14-35-12,12>>^ Além disso, prepararam^&#42;1^ as ofertas queimadas de modo a dá-las aos grupos segundo a casa paterna, aos filhos do povo, para fazer uma apresentação a Jeová de acordo com o que está escrito no livro de Moisés; e assim também com o gado vacum.

[NOTE]
====
. “Prepararam”, LXX; M: “removeram”.
====

[[v14-35-13]]

^<<v14-35-13,13>>^ E foram cozinhar a oferta pascoal sobre o fogo, segundo o costume; e as coisas tornadas sagradas cozinharam em panelas, e em caldeirões, e em tachos de banquete, trazendo-as depois depressa a todos os filhos do povo.

[[v14-35-14]]

^<<v14-35-14,14>>^ E posteriormente fizeram preparativos para si mesmos e para os sacerdotes, porque os sacerdotes, os filhos de Arão, estavam empenhados em oferecer os sacrifícios queimados e os pedaços gordos até à noite, e os levitas, da sua parte, fizeram preparativos para si e para os sacerdotes, os filhos de Arão.

[[v14-35-15]]

^<<v14-35-15,15>>^ E os cantores, os filhos de Asafe, estavam na sua função segundo o mandamento de Davi, e de Asafe, e de Hemã, e de Jedutum, visionário do rei; e os porteiros estavam nos diversos portões. Não havia necessidade de se desviarem do seu serviço, porque seus irmãos, os próprios levitas, fizeram preparativos para eles.

[[v14-35-16]]

^<<v14-35-16,16>>^ E todo o serviço de Jeová foi preparado naquele dia para se celebrar a páscoa e para se oferecerem as ofertas queimadas sobre o altar de Jeová, segundo o mandamento do Rei Josias.

[[v14-35-17]]

^<<v14-35-17,17>>^ E os filhos de Israel, que se podiam achar, passaram a celebrar a páscoa naquele tempo, e também a festividade dos pães não fermentados, por sete dias.

[[v14-35-18]]

^<<v14-35-18,18>>^ E nunca se celebrara em Israel uma páscoa igual a esta, desde os dias de Samuel, o profeta, nem fez qualquer um dos outros reis de Israel celebrar uma páscoa igual à celebrada por Josias, e pelos sacerdotes, e pelos levitas, e por todo o Judá e Israel, que se podiam achar, e pelos habitantes de Jerusalém.

[[v14-35-19]]

^<<v14-35-19,19>>^ Esta páscoa se celebrou no décimo oitavo ano do reinado de Josias.

[[v14-35-20]]

^<<v14-35-20,20>>^ Após tudo isso, quando Josias tinha preparado a casa, subiu Neco,^&#42;1^ rei do Egito, para lutar em Carquemis, junto ao Eufrates. Josias saiu então ao encontro dele.

[NOTE]
====
. Ou “Necao (Necau)”.
====

[[v14-35-21]]

^<<v14-35-21,21>>^ Em vista disso, este enviou-lhe mensageiros, dizendo: “Que tenho eu que ver contigo,^&#42;1^ ó rei de Judá? Não venho hoje contra ti,^&#42;2^ mas a minha luta é contra outra casa e o próprio Deus disse que devo causar perturbação. Refreia-te para o teu próprio bem por causa de Deus, que está comigo, e não deixes que te arruíne.”

[NOTE]
====
. Lit.: “Que [há] para mim e para ti?” Esta é uma expressão idiomática hebr.; é uma pergunta de repulsa, indicando objeção à intervenção de Josias. Veja Ap. 7B.
. “Não venho hoje contra ti”, LXXSyVg; M: “Não é contra ti mesmo, hoje.”
====

[[v14-35-22]]

^<<v14-35-22,22>>^ E Josias não virou sua face dele, mas disfarçou-se para lutar contra ele e não escutou as palavras de Neco provenientes da boca de Deus. Chegou assim para lutar no vale plano de Megido.

[[v14-35-23]]

^<<v14-35-23,23>>^ E os atiradores foram atirar contra o Rei Josias, de modo que o rei disse aos seus servos: “Tirai-me daqui, porque fui seriamente ferido.”

[[v14-35-24]]

^<<v14-35-24,24>>^ Portanto, seus servos tiraram-no do carro e fizeram-no andar no segundo carro de guerra que era dele, e levaram-no a Jerusalém. Assim morreu ele e foi enterrado no cemitério de seus antepassados; e todo o Judá e Jerusalém pranteavam por Josias.

[[v14-35-25]]

^<<v14-35-25,25>>^ E Jeremias^&#42;1^ começou a entoar um canto fúnebre por Josias; e todos os cantores e todas as cantoras falam sobre Josias nas suas endechas até o dia de hoje; e puseram-nas por regulamento em Israel, e eis que estão escritas entre as endechas.

[NOTE]
====
. “Jeremias.” Hebr.: Yir·meyá·hu.
====

[[v14-35-26]]

^<<v14-35-26,26>>^ Quanto ao resto dos assuntos de Josias e dos seus atos de benevolência,^&#42;1^ segundo o que está escrito na lei de Jeová,

[NOTE]
====
. Ou “amor leal”.
====

[[v14-35-27]]

^<<v14-35-27,27>>^ bem como seus assuntos, os primeiros e os últimos, eis que estão escritos no Livro dos Reis de Israel e de Judá.

'''

xref:014-2-cronicas/014-2-cronicas-034.adoc#v14-34-0[&#60; Capítulo Anterior] | <<v14-35-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-036.adoc#v14-36-0[Próximo Capítulo &#62;]