include::./index.adoc[]

[[v14-13-0]]
=== 2 Crônicas, 13
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v14-13-1]]

^<<v14-13-1,1>>^ Foi no décimo oitavo ano do Rei Jeroboão que Abias começou a reinar sobre Judá.

[[v14-13-2]]

^<<v14-13-2,2>>^ Ele reinou três anos em Jerusalém e o nome de sua mãe era Micaías,^&#42;1^ filha de Uriel de Gibeá. E sucedeu haver mesmo guerra entre Abias e Jeroboão.

[NOTE]
====
. “Micaia”, MVg; LXXSy, 11:20-22 e 1Rs 15:2: “Maacá”.
====

[[v14-13-3]]

^<<v14-13-3,3>>^ Assim, Abias travou guerra com uma força militar de quatrocentos mil homens poderosos de guerra, homens seletos. E o próprio Jeroboão pôs-se em formação de batalha contra ele com oitocentos mil homens seletos, homens poderosos, valentes.

[[v14-13-4]]

^<<v14-13-4,4>>^ Abias levantou-se então no monte Zemaraim, que está na região montanhosa de Efraim, e disse: “Ouvi-me, ó Jeroboão e todo o Israel.

[[v14-13-5]]

^<<v14-13-5,5>>^ Não vos cabe saber que o próprio Jeová, o Deus de Israel, deu a Davi um reino sobre Israel por tempo indefinido, a ele e a seus filhos, por meio de um pacto de sal?

[[v14-13-6]]

^<<v14-13-6,6>>^ E Jeroboão, filho de Nebate, servo de Salomão, filho de Davi, passou a levantar-se e a rebelar-se contra seu senhor.^&#42;1^

[NOTE]
====
. “Seu senhor.” Hebr.: ’adho·náv, pl. de ’a·dhóhn, para denotar excelência.
====

[[v14-13-7]]

^<<v14-13-7,7>>^ E com ele foram reunir-se homens vadios, imprestáveis. Por fim se mostraram superiores a Roboão, filho de Salomão, quando acontecia ser o próprio Roboão moço e de coração receoso, e ele não lhes pôde resistir.

[[v14-13-8]]

^<<v14-13-8,8>>^ “E agora pensais em resistir ao reino de Jeová na mão dos filhos de Davi, quando sois uma grande massa de gente e estão convosco os bezerros de ouro que Jeroboão fez para vós como deuses.^&#42;1^

[NOTE]
====
. “Como deuses.” Ou “como deus”. Hebr.: le’·lo·hím, pl. de ’elóh·ah. Veja 1Rs 12:28 n.: “Deus”.
====

[[v14-13-9]]

^<<v14-13-9,9>>^ Não expelistes os sacerdotes de Jeová, os filhos de Arão e os levitas, e não estais constituindo para vós sacerdotes, como os povos das terras? Quanto a qualquer um que chegou e encheu a sua mão de poder^&#42;1^ por meio dum novilho^&#42;2^ e de sete carneiros, tornou-se ele sacerdote daquilo que não são deuses.^&#42;3^

[NOTE]
====
. Ou “e instalou-se”.
. “Novilho.” Lit.: “touro, filho da manada”.
. “Daquilo que não são deuses.” Hebr.: leló’ ’elo·hím.
====

[[v14-13-10]]

^<<v14-13-10,10>>^ Quanto a nós, Jeová é o nosso Deus e nós não o abandonamos; mas há sacerdotes que ministram a Jeová, filhos de Arão, e também os levitas na obra.

[[v14-13-11]]

^<<v14-13-11,11>>^ E eles fazem fumegar ofertas queimadas a Jeová, manhã após manhã, e noitinha após noitinha, e também incenso perfumado; e as pilhas de pão estão sobre a mesa de [ouro] puro, e há o candelabro de ouro e suas lâmpadas para acender noitinha após noitinha; porque estamos cumprindo a obrigação para com Jeová, nosso Deus, mas vós mesmos o abandonastes.

[[v14-13-12]]

^<<v14-13-12,12>>^ E eis que conosco está à cabeça o [verdadeiro] Deus com seus sacerdotes e as trombetas de sinal para tocar o alarme de batalha contra vós. Ó filhos de Israel, não luteis contra Jeová, o Deus de vossos antepassados, porque não vos mostrareis bem sucedidos.”

[[v14-13-13]]

^<<v14-13-13,13>>^ E Jeroboão, da sua parte, mandou os duma emboscada dar volta para ficarem atrás deles, de modo que mostraram estar na frente de Judá e a emboscada atrás deles.

[[v14-13-14]]

^<<v14-13-14,14>>^ Quando os de Judá se viraram, ora, eis que tinham a batalha tanto na frente como atrás. E começaram a clamar a Jeová, ao passo que os sacerdotes tocavam alto as trombetas.

[[v14-13-15]]

^<<v14-13-15,15>>^ E os homens de Judá irromperam num grito de guerra. E sucedeu que, quando os homens de Judá deram o grito de guerra, então o próprio Deus [verdadeiro] derrotou a Jeroboão e a todo o Israel diante de Abias e de Judá.

[[v14-13-16]]

^<<v14-13-16,16>>^ E os filhos de Israel puseram-se em fuga diante de Judá, e então Deus os entregou na sua mão.

[[v14-13-17]]

^<<v14-13-17,17>>^ E Abias e seu povo passaram a golpeá-los com uma enorme matança; e os que foram mortos de Israel continuaram a cair, quinhentos mil homens seletos.

[[v14-13-18]]

^<<v14-13-18,18>>^ Assim foram humilhados os filhos de Israel naquele tempo, mas os filhos de Judá mostraram-se superiores porque se estribaram em Jeová, o Deus de seus antepassados.

[[v14-13-19]]

^<<v14-13-19,19>>^ E Abias continuou no encalço de Jeroboão e chegou a capturar dele cidades: Betel e suas aldeias dependentes, e Jesana e suas aldeias dependentes, e Efraíne^&#42;1^ e suas aldeias dependentes.

[NOTE]
====
. “Efraíne”, Mmargem; MLXXSyVg: “Efrom”.
====

[[v14-13-20]]

^<<v14-13-20,20>>^ E Jeroboão não reteve mais poder nos dias de Abias;^&#42;1^ mas Jeová deu-lhe um golpe, de modo que morreu.

[NOTE]
====
. “Abias.” Hebr.: ’Avi·yá·hu.
====

[[v14-13-21]]

^<<v14-13-21,21>>^ E Abias continuou a fortalecer-se. Com o tempo obteve para si quatorze esposas e tornou-se pai de vinte e dois filhos e de dezesseis filhas.

[[v14-13-22]]

^<<v14-13-22,22>>^ E o resto dos assuntos de Abias, sim, seus caminhos e suas palavras, estão escritos na explanação^&#42;1^ do profeta Ido.

[NOTE]
====
. Ou “comentário; midraxe”. Esta é a primeira de duas ocorrências de “midraxe” no M. Veja 24:27 e n.
====

'''

xref:014-2-cronicas/014-2-cronicas-012.adoc#v14-12-0[&#60; Capítulo Anterior] | <<v14-13-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-014.adoc#v14-14-0[Próximo Capítulo &#62;]