include::./index.adoc[]

[[v14-24-0]]
=== 2 Crônicas, 24
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v14-24-1]]

^<<v14-24-1,1>>^ Jeoás^&#42;1^ tinha sete anos de idade quando começou a reinar e reinou por quarenta anos em Jerusalém. E o nome de sua mãe era Zibiá, de Berseba.

[NOTE]
====
. Lit.: “Joás.” Veja 2Rs 11:21 n.
====

[[v14-24-2]]

^<<v14-24-2,2>>^ E Jeoás fazia o que era direito aos olhos de Jeová todos os dias de Jeoiada, o sacerdote.

[[v14-24-3]]

^<<v14-24-3,3>>^ E Jeoiada passou a tomar duas esposas para ele e ele se tornou pai de filhos e de filhas.

[[v14-24-4]]

^<<v14-24-4,4>>^ Ora, depois aconteceu que ficou achegado ao coração de Jeoás renovar a casa de Jeová.

[[v14-24-5]]

^<<v14-24-5,5>>^ Por conseguinte, reuniu os sacerdotes e os levitas e disse-lhes: “Saí às cidades de Judá e reuni dinheiro de todo o Israel para se consertar a casa de vosso Deus, de ano em ano; e vós, da vossa parte, deveis agir depressa neste assunto.” E os levitas não agiram depressa.

[[v14-24-6]]

^<<v14-24-6,6>>^ De modo que o rei chamou Jeoiada, o cabeça, e disse-lhe: “Por que é que não exigistes uma prestação de contas dos levitas pela entrada do imposto sagrado de Judá e de Jerusalém, ordenado por Moisés, o servo de Jeová, sim, o da congregação de Israel para a tenda do Testemunho?

[[v14-24-7]]

^<<v14-24-7,7>>^ Pois, quanto a Atalia, a mulher iníqua, os próprios filhos dela tinham arrombado a casa do [verdadeiro] Deus e tinham até mesmo ofertado aos Baalins todas as coisas sagradas da casa de Jeová.”

[[v14-24-8]]

^<<v14-24-8,8>>^ Então o rei disse [a palavra], e eles fizeram então um cofre e o puseram do lado de fora do portão da casa de Jeová.

[[v14-24-9]]

^<<v14-24-9,9>>^ Depois fizeram uma proclamação em Judá e em Jerusalém, para que se trouxesse a Jeová o imposto sagrado ordenado a Israel no ermo por Moisés, o servo do [verdadeiro] Deus.^&#42;1^

[NOTE]
====
. “Servo do [verdadeiro] Deus.” Hebr.: ‛e·vedh-ha·’Elo·hím; Sy: “servo de Jeová”. Veja Ap. 1F.
====

[[v14-24-10]]

^<<v14-24-10,10>>^ E todos os príncipes e todo o povo começaram a alegrar-se, e foram trazê-lo e lançá-lo no cofre até que todos [o] tinham dado.

[[v14-24-11]]

^<<v14-24-11,11>>^ E sucedia, no tempo devido, que ele levava o cofre aos cuidados do rei pela mão dos levitas, e assim que viam que havia bastante dinheiro, chegava o secretário do rei e o comissário do sacerdote principal, e então esvaziavam o cofre e o levantavam e o punham de volta no seu lugar. Assim faziam de dia em dia, de modo que ajuntaram dinheiro em abundância.

[[v14-24-12]]

^<<v14-24-12,12>>^ O rei e Jeoiada davam-no então aos que faziam a obra do serviço da casa de Jeová, e eles vieram a ser contratadores de talhadores de pedras bem como de artífices para a renovação da casa de Jeová, e também de trabalhadores em ferro e em cobre para consertar a casa de Jeová.

[[v14-24-13]]

^<<v14-24-13,13>>^ E os que faziam a obra começaram a trabalhar, e a obra de conserto progredia na sua mão, e por fim fizeram a casa do [verdadeiro] Deus ficar no seu estado devido e fizeram-na forte.

[[v14-24-14]]

^<<v14-24-14,14>>^ E assim que acabaram, levaram perante o rei e Jeoiada o restante do dinheiro, e passaram a fazer utensílios para a casa de Jeová, utensílios para o ministério e para se fazer ofertas, e taças, e utensílios de ouro e de prata; e vieram a ser ofertantes de sacrifícios queimados na casa de Jeová, constantemente, todos os dias de Jeoiada.

[[v14-24-15]]

^<<v14-24-15,15>>^ E Jeoiada ficou velho e farto em anos, e por fim morreu, tendo cento e trinta anos de idade por ocasião da sua morte.

[[v14-24-16]]

^<<v14-24-16,16>>^ Enterraram-no, pois, na Cidade de Davi, junto aos reis, porque fizera o bem em Israel, e com o [verdadeiro] Deus e Sua casa.

[[v14-24-17]]

^<<v14-24-17,17>>^ E depois da morte de Jeoiada entraram os príncipes de Judá e passaram a curvar-se diante do rei. Naquele tempo o rei os escutou.

[[v14-24-18]]

^<<v14-24-18,18>>^ E aos poucos deixaram a casa de Jeová, o Deus de seus antepassados, e começaram a servir aos postes sagrados e aos ídolos, de modo que veio a haver indignação contra Judá e contra Jerusalém por causa desta culpa sua.

[[v14-24-19]]

^<<v14-24-19,19>>^ E ele enviava profetas entre eles para trazê-los de volta a Jeová; e estes testificavam^&#42;1^ contra eles, mas não deram ouvidos.

[NOTE]
====
. “Testificavam.” Lat.: pro·te·stán·tes.
====

[[v14-24-20]]

^<<v14-24-20,20>>^ E o próprio espírito de Deus envolveu^&#42;1^ a Zacarias, filho de Jeoiada, o sacerdote, de modo que se pôs de pé acima do povo e lhes disse: “Assim disse o [verdadeiro] Deus: ‘Por que infringis os mandamentos de Jeová, de modo que não vos podeis mostrar bem sucedidos? Visto que abandonastes a Jeová, ele, por sua vez, também vos abandonará.’”

[NOTE]
====
. Lit.: “revestiu”.
====

[[v14-24-21]]

^<<v14-24-21,21>>^ Por fim conspiraram contra ele e atiraram pedras nele ao mandamento do rei, no pátio da casa de Jeová.

[[v14-24-22]]

^<<v14-24-22,22>>^ E Jeoás, o rei, não se lembrou da benevolência que Jeoiada, pai daquele, teve para com ele, matando-lhe assim o filho, o qual, estando para morrer, disse: “Que Jeová o veja e o exija de volta.”

[[v14-24-23]]

^<<v14-24-23,23>>^ E aconteceu, na volta do ano, que subiu contra ele uma força militar da Síria, e eles começaram a invadir Judá e Jerusalém. Arruinaram então dentre o povo todos os príncipes do povo e enviaram todo o seu despojo ao rei de Damasco.

[[v14-24-24]]

^<<v14-24-24,24>>^ Porque a força militar dos sírios fez a invasão com um pequeno número de homens e o próprio Jeová lhes entregou na mão uma força militar muito grande em número, por terem abandonado a Jeová, o Deus de seus antepassados; e eles executaram atos de julgamento em Jeoás.

[[v14-24-25]]

^<<v14-24-25,25>>^ E quando foram embora dele (pois o deixaram com muitas enfermidades), seus próprios servos conspiraram contra ele por causa do sangue dos filhos^&#42;1^ de Jeoiada, o sacerdote; e foram matá-lo sobre o seu próprio leito, de modo que morreu. Enterraram-no então na Cidade de Davi, mas não o enterraram nas sepulturas dos reis.

[NOTE]
====
. “Filhos”, MSy; LXXVg: “filho”. É possível que M use aqui o pl. para denotar a excelência e o valor do filho de Jeoiada, Zacarias, o profeta-sacerdote.
====

[[v14-24-26]]

^<<v14-24-26,26>>^ E foram estes os que conspiraram contra ele: Zabade, filho de Simeate, a amonita, e Jeozabade, filho de Sinrite, a moabita.

[[v14-24-27]]

^<<v14-24-27,27>>^ Quanto aos seus filhos e a abundância de pronúncia contra ele, e a fundação da casa do [verdadeiro] Deus, eis que estão escritos na explanação^&#42;1^ do Livro dos Reis. E Amazias, seu filho, começou a reinar em seu lugar.

[NOTE]
====
. Ou “midraxe”. Hebr.: midh·rásh. A única outra ocorrência desta palavra hebr. no M existe em 13:22; veja ali a n.
====

'''

xref:014-2-cronicas/014-2-cronicas-023.adoc#v14-23-0[&#60; Capítulo Anterior] | <<v14-24-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-025.adoc#v14-25-0[Próximo Capítulo &#62;]