include::./index.adoc[]

[[v14-27-0]]
=== 2 Crônicas, 27
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v14-27-1]]

^<<v14-27-1,1>>^ Jotão tinha vinte e cinco anos de idade quando começou a reinar e reinou por dezesseis anos em Jerusalém. E o nome de sua mãe era Jerusá, filha de Zadoque.

[[v14-27-2]]

^<<v14-27-2,2>>^ E ele fazia o que era direito aos olhos de Jeová, segundo tudo o que Uzias,^&#42;1^ seu pai, tinha feito. Apenas não invadiu o templo de Jeová. No entanto, o povo ainda agia ruinosamente.

[NOTE]
====
. Veja 26:1 n.
====

[[v14-27-3]]

^<<v14-27-3,3>>^ Ele mesmo construiu o portão superior da casa de Jeová e fez muita construção na muralha de Ofel.

[[v14-27-4]]

^<<v14-27-4,4>>^ E construiu cidades na região montanhosa de Judá e construiu fortes e torres nos bosques.

[[v14-27-5]]

^<<v14-27-5,5>>^ E ele mesmo guerreou contra o rei dos filhos de Amom e por fim se mostrou mais forte do que eles, de modo que os filhos de Amom lhe deram naquele ano cem talentos^&#42;1^ de prata e dez mil coros^&#42;2^ de trigo, bem como dez mil de cevada. Foi isto o que lhe pagaram os filhos de Amom, também no segundo ano e no terceiro.

[NOTE]
====
. Veja Ap. 8A.
. Um coro equivalia a 220 l.
====

[[v14-27-6]]

^<<v14-27-6,6>>^ Portanto, Jotão se fortalecia, pois preparava seu caminho perante Jeová, seu Deus.

[[v14-27-7]]

^<<v14-27-7,7>>^ Quanto ao resto dos assuntos de Jotão e todas as suas guerras e seus caminhos, eis que estão escritos no Livro dos Reis de Israel e de Judá.

[[v14-27-8]]

^<<v14-27-8,8>>^ Viera a ter vinte e cinco anos de idade quando começou a reinar e reinou por dezesseis anos em Jerusalém.

[[v14-27-9]]

^<<v14-27-9,9>>^ Por fim, Jotão deitou-se com os seus antepassados e enterraram-no na Cidade de Davi. E Acaz, seu filho, começou a reinar em seu lugar.

'''

xref:014-2-cronicas/014-2-cronicas-026.adoc#v14-26-0[&#60; Capítulo Anterior] | <<v14-27-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-028.adoc#v14-28-0[Próximo Capítulo &#62;]