include::./index.adoc[]

[[v14-6-0]]
=== 2 Crônicas, 6
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v14-6-1]]

^<<v14-6-1,1>>^ Foi então que Salomão disse: “O próprio Jeová disse que ia residir em densas trevas;

[[v14-6-2]]

^<<v14-6-2,2>>^ e eu, da minha parte, construí para ti uma casa de morada excelsa e um lugar estabelecido para nele morares por tempo indefinido.”^&#42;1^

[NOTE]
====
. “Por tempo indefinido.” Lit.: “tempos indefinidos”. Hebr.: ‛oh·la·mím, pl.
====

[[v14-6-3]]

^<<v14-6-3,3>>^ O rei voltou então a sua face e começou a abençoar toda a congregação^&#42;1^ de Israel, enquanto toda a congregação de Israel estava de pé.

[NOTE]
====
. “Congregação de.” Hebr.: qehál; gr.: ek·kle·sí·an.
====

[[v14-6-4]]

^<<v14-6-4,4>>^ E ele prosseguiu, dizendo: “Bendito seja Jeová, o Deus de Israel, que falou com a sua própria boca com Davi, meu pai, e que pelas suas próprias mãos deu cumprimento, dizendo:

[[v14-6-5]]

^<<v14-6-5,5>>^ ‘Desde o dia em que fiz meu povo sair da terra do Egito não escolhi cidade dentre todas as tribos de Israel, a fim de construir uma casa para que o meu nome mostrasse estar ali, e não escolhi homem para que se tornasse líder do meu povo Israel.

[[v14-6-6]]

^<<v14-6-6,6>>^ Mas escolherei Jerusalém para que o meu nome mostre estar ali e escolherei a Davi para vir a estar sobre o meu povo Israel.’

[[v14-6-7]]

^<<v14-6-7,7>>^ E ficou achegado ao coração de Davi, meu pai, construir uma casa ao nome de Jeová, o Deus de Israel.

[[v14-6-8]]

^<<v14-6-8,8>>^ Mas Jeová disse a Davi, meu pai: ‘Visto que ficou achegado ao teu coração construir uma casa ao meu nome, fizeste bem, pois isso se mostrou achegado ao teu coração.

[[v14-6-9]]

^<<v14-6-9,9>>^ Apenas tu mesmo não construirás a casa, mas teu filho, que sai dos teus lombos, é quem construirá a casa ao meu nome.’

[[v14-6-10]]

^<<v14-6-10,10>>^ E Jeová passou a cumprir a sua palavra que falara, para que eu me levantasse em lugar de Davi, meu pai, e me sentasse no trono de Israel, assim como Jeová havia falado, e para que eu construísse a casa ao nome de Jeová, o Deus de Israel,

[[v14-6-11]]

^<<v14-6-11,11>>^ e para que eu colocasse ali a Arca, onde está o pacto de Jeová, que ele concluiu com os filhos de Israel.”

[[v14-6-12]]

^<<v14-6-12,12>>^ E ele começou a ficar de pé diante do altar de Jeová, na frente de toda a congregação de Israel, e então estendeu as palmas das suas mãos.

[[v14-6-13]]

^<<v14-6-13,13>>^ (Porque Salomão tinha feito uma tribuna de cobre e a pôs então no centro do cercado. Tinha cinco côvados^&#42;1^ de comprimento, e cinco côvados de largura, e três côvados de altura; e ele ficou de pé sobre ela.) E passou a dobrar os joelhos na frente de toda a congregação de Israel e a estender as palmas das suas mãos para os céus.

[NOTE]
====
. Um côvado equivalia a 44,5 cm.
====

[[v14-6-14]]

^<<v14-6-14,14>>^ E prosseguiu, dizendo: “Ó Jeová, Deus de Israel, não há Deus^&#42;1^ igual a ti nos céus nem na terra, guardando o pacto e a benevolência para com os teus servos que andam diante de ti de todo o seu coração;

[NOTE]
====
. “Deus.” Hebr.: ’Elo·hím; gr.: The·ós; lat.: Dé·us.
====

[[v14-6-15]]

^<<v14-6-15,15>>^ tu, que cumpriste para com o teu servo Davi, meu pai, aquilo que lhe prometeste, de modo que fizeste a promessa^&#42;1^ com a tua boca e deste cumprimento com a tua própria mão, como no dia de hoje.

[NOTE]
====
. Lit.: “falaste”.
====

[[v14-6-16]]

^<<v14-6-16,16>>^ E agora, ó Jeová, Deus de Israel, cumpre para com o teu servo Davi, meu pai, aquilo que lhe prometeste, dizendo: ‘Não se decepará diante de mim homem teu, [impedindo-o] de sentar-se no trono de Israel, se os teus filhos tão-somente cuidarem do seu caminho, andando na minha lei, assim como tu andaste diante de mim.’

[[v14-6-17]]

^<<v14-6-17,17>>^ E agora, ó Jeová, Deus de Israel, mostre-se fidedigna a tua promessa^&#42;1^ que fizeste ao teu servo Davi.

[NOTE]
====
. Lit.: “palavra”.
====

[[v14-6-18]]

^<<v14-6-18,18>>^ “Porém, morará Deus verdadeiramente com a humanidade^&#42;1^ na terra? Eis que o céu, sim, o céu dos próprios céus não te podem conter; quanto menos, então, esta casa que construí!

[NOTE]
====
. Lit.: “o homem terreno”. Hebr.: ha·’a·dhám.
====

[[v14-6-19]]

^<<v14-6-19,19>>^ E terás de virar-te para a oração de teu servo e para o seu pedido de favor, ó Jeová, meu Deus, escutando o clamor suplicante e a oração com que teu servo está orando diante de ti,

[[v14-6-20]]

^<<v14-6-20,20>>^ a fim de que os teus olhos se mostrem abertos para com esta casa, dia e noite, para com o lugar de que disseste que porias nele o teu nome, escutando a oração com que teu servo ora em direção a este lugar.

[[v14-6-21]]

^<<v14-6-21,21>>^ E terás de escutar os rogos do teu servo e do teu povo Israel quando orarem em direção a este lugar, para que tu mesmo ouças desde o lugar da tua morada, desde os céus; e terás de ouvir e perdoar.

[[v14-6-22]]

^<<v14-6-22,22>>^ “Se um homem pecar contra o seu próximo e realmente puser sobre ele uma maldição, para sujeitá-lo à maldição, e ele realmente vier [dentro da] maldição perante o teu altar nesta casa,

[[v14-6-23]]

^<<v14-6-23,23>>^ então que tu mesmo ouças desde os céus, e terás de agir e julgar os teus servos, a fim de pagar de volta ao iníquo, lançando o seu proceder^&#42;1^ sobre a sua própria cabeça e declarando justo ao justo, dando-lhe segundo a sua própria justiça.

[NOTE]
====
. Ou “seu modo”. Hebr.: dar·kóh.
====

[[v14-6-24]]

^<<v14-6-24,24>>^ “E se o teu povo Israel for derrotado diante dum inimigo, porque estiveram pecando contra ti, e eles deveras voltarem e elogiarem o teu nome, e orarem e fizerem um pedido de favor diante de ti nesta casa,

[[v14-6-25]]

^<<v14-6-25,25>>^ então que tu mesmo ouças desde os céus, e terás de perdoar o pecado do teu povo Israel e trazê-los de volta ao solo que deste a eles e aos seus antepassados.

[[v14-6-26]]

^<<v14-6-26,26>>^ “Quando os céus estiverem cerrados de modo que não venha a haver chuva, porque estiveram pecando contra ti, e eles realmente orarem em direção a este lugar e elogiarem o teu nome, [e] recuarem do seu pecado, por tu os teres atribulado,

[[v14-6-27]]

^<<v14-6-27,27>>^ então que tu mesmo ouças desde os céus, e terás de perdoar o pecado dos teus servos, sim, do teu povo Israel, porque os instruis quanto ao bom caminho em que devem andar; e terás de dar chuva sobre a tua terra que deste ao teu povo como propriedade hereditária.

[[v14-6-28]]

^<<v14-6-28,28>>^ “Caso ocorra uma fome no país, caso ocorra uma pestilência, caso venha a haver crestamento e bolor, gafanhotos e baratas; caso seus inimigos os sitiem na terra dos seus portões^&#42;1^ — qualquer tipo de praga, qualquer tipo de enfermidade —

[NOTE]
====
. Ou “cidades”, conforme representadas pelos seus portões.
====

[[v14-6-29]]

^<<v14-6-29,29>>^ qualquer oração, qualquer pedido de favor que venha a haver da parte de qualquer homem ou de todo o teu povo Israel, por conhecerem, cada um, a sua própria praga e a sua própria dor; quando ele realmente estender as palmas das suas mãos para esta casa,

[[v14-6-30]]

^<<v14-6-30,30>>^ então que tu mesmo ouças desde os céus, lugar da tua morada, e terás de perdoar e dar a cada um segundo todos os seus caminhos, porque conheces o seu coração (pois somente tu mesmo conheces bem o coração dos filhos da humanidade);

[[v14-6-31]]

^<<v14-6-31,31>>^ a fim de que te temam, andando nos teus caminhos todos os dias em que estiverem vivos na superfície do solo que deste aos nossos antepassados.

[[v14-6-32]]

^<<v14-6-32,32>>^ “E também ao estrangeiro que não faz parte do teu povo Israel e que realmente vem duma terra distante por causa do teu grande nome, e da tua forte mão, e do teu braço estendido, e eles realmente vêm e oram em direção a esta casa,

[[v14-6-33]]

^<<v14-6-33,33>>^ então que tu mesmo ouças desde os céus, do teu lugar estabelecido de morada, e terás de fazer segundo tudo aquilo pelo qual o estrangeiro te invocar; para que todos os povos da terra conheçam o teu nome e te temam assim como teu povo Israel faz, e para que saibam que o teu nome tem sido invocado sobre esta casa que construí.

[[v14-6-34]]

^<<v14-6-34,34>>^ “Caso teu povo saia à guerra contra os seus inimigos no caminho em que os envias e eles deveras orem a ti em direção a esta cidade que escolheste e à casa que construí ao teu nome,

[[v14-6-35]]

^<<v14-6-35,35>>^ então terás de ouvir desde os céus a sua oração e o seu pedido de favor, e terás de executar o julgamento para eles.

[[v14-6-36]]

^<<v14-6-36,36>>^ “Caso pequem contra ti, (pois não há homem que não peque,) e tenhas de irar-te com eles e entregá-los a um inimigo, e seus captores realmente os levem cativos a uma terra distante ou próxima;

[[v14-6-37]]

^<<v14-6-37,37>>^ e eles deveras voltem ao seu juízo^&#42;1^ na terra à qual foram levados cativos, e realmente retornem e te façam um pedido de favor na terra em que estiverem cativos, dizendo: ‘Pecamos, erramos e agimos iniquamente’;

[NOTE]
====
. Veja 1Rs 8:47 n.
====

[[v14-6-38]]

^<<v14-6-38,38>>^ e eles deveras retornem a ti de todo o seu coração e de toda a sua alma, na terra onde forem cativos dos que os levaram cativos, e deveras orem em direção à sua terra que deste aos seus antepassados, e à cidade que escolheste, e à casa que construí ao teu nome;

[[v14-6-39]]

^<<v14-6-39,39>>^ então, desde os céus, do teu lugar estabelecido de morada, terás de ouvir a sua oração e o seu pedido de favor, e terás de executar julgamento para eles e perdoar ao teu povo que pecou contra ti.

[[v14-6-40]]

^<<v14-6-40,40>>^ “Agora, ó meu Deus, por favor, mostrem-se os teus olhos abertos e os teus ouvidos atentos à oração concernente a este lugar.

[[v14-6-41]]

^<<v14-6-41,41>>^ E agora levanta-te, ó Jeová Deus, [entrando] no teu descanso, tu e a Arca da tua força. Vistam-se de salvação os próprios sacerdotes teus, ó Jeová Deus, e alegrem-se em bondade aqueles mesmos que te são leais.

[[v14-6-42]]

^<<v14-6-42,42>>^ Ó Jeová Deus, não faças recuar a face do teu ungido.^&#42;1^ Lembra-te deveras das benevolências^&#42;2^ para com Davi, teu servo.”

[NOTE]
====
. “Teu ungido.” Lit.: “teus ungidos”. Hebr.: meshí·hheí·kha, pl.; gr.: khri·stoú; sir.: dam·shi·hhakh; lat.: chrí·sti.
. Ou “[casos de] amor leal”.
====

'''

xref:014-2-cronicas/014-2-cronicas-005.adoc#v14-5-0[&#60; Capítulo Anterior] | <<v14-6-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-007.adoc#v14-7-0[Próximo Capítulo &#62;]