include::./index.adoc[]

[[v14-17-0]]
=== 2 Crônicas, 17
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v14-17-1]]

^<<v14-17-1,1>>^ E Jeosafá, seu filho, começou a reinar em seu lugar e a fortalecer a sua posição sobre Israel.

[[v14-17-2]]

^<<v14-17-2,2>>^ E passou a pôr forças militares em todas as cidades fortificadas de Judá e a pôr guarnições na terra de Judá bem como nas cidades de Efraim, que Asa, seu pai, havia capturado.

[[v14-17-3]]

^<<v14-17-3,3>>^ E Jeová continuou com Jeosafá por ele andar nos caminhos anteriores de Davi, seu antepassado, e não buscar os Baalins.

[[v14-17-4]]

^<<v14-17-4,4>>^ Porque buscava o Deus de seu pai e andava no seu mandamento, e não segundo os feitos de Israel.

[[v14-17-5]]

^<<v14-17-5,5>>^ E Jeová manteve o reino firmemente estabelecido na sua mão; e todo o Judá continuava a dar a Jeosafá presentes, e ele veio a ter riquezas e glória em abundância.

[[v14-17-6]]

^<<v14-17-6,6>>^ E seu coração tornou-se ousado nos caminhos de Jeová e ele até mesmo removeu de Judá os altos e os postes sagrados.

[[v14-17-7]]

^<<v14-17-7,7>>^ E no terceiro ano do seu reinado mandou [chamar] seus príncipes, a saber, Ben-Hail, e Obadias, e Zacarias, e Netanel, e Micaías, para que ensinassem nas cidades de Judá,

[[v14-17-8]]

^<<v14-17-8,8>>^ e com eles os levitas Semaías, e Netanias, e Zebadias, e Asael, e Semiramote, e Jeonatã, e Adonias, e Tobijá, e Tobe-Adonias, os levitas, e com eles Elisama e Jeorão, os sacerdotes.

[[v14-17-9]]

^<<v14-17-9,9>>^ E eles começaram a ensinar em Judá e tinham consigo o livro da lei de Jeová; e eles davam volta através das cidades de Judá e ensinavam entre o povo.

[[v14-17-10]]

^<<v14-17-10,10>>^ E o pavor de Jeová veio a estar sobre todos os reinos dos países que havia ao redor de Judá e eles não lutaram contra Jeosafá.

[[v14-17-11]]

^<<v14-17-11,11>>^ E dos filisteus traziam-se a Jeosafá presentes e dinheiro como tributo. Também os árabes lhe traziam rebanhos, sete mil e setecentos carneiros e sete mil e setecentos cabritos.

[[v14-17-12]]

^<<v14-17-12,12>>^ E Jeosafá continuou a progredir e a tornar-se grande num grau superior; e ele prosseguiu, construindo em Judá fortes e cidades-armazéns.

[[v14-17-13]]

^<<v14-17-13,13>>^ E veio a ter muitos interesses nas cidades de Judá; e havia em Jerusalém guerreiros, homens poderosos, valentes.

[[v14-17-14]]

^<<v14-17-14,14>>^ E seus cargos eram estes, segundo a casa de seus antepassados: De Judá, os chefes de mil: Adná, o chefe, e com ele havia trezentos mil homens poderosos, valentes.

[[v14-17-15]]

^<<v14-17-15,15>>^ E sob o seu controle estava Jeoanã, o chefe, e com ele havia duzentos e oitenta mil.

[[v14-17-16]]

^<<v14-17-16,16>>^ E sob o seu controle estava Amasia, filho de Zicri, voluntário de Jeová, e com ele havia duzentos mil homens poderosos, valentes.

[[v14-17-17]]

^<<v14-17-17,17>>^ E de Benjamim havia o poderoso, valente Eliada, e com ele havia duzentos mil homens armados de arco e escudo.

[[v14-17-18]]

^<<v14-17-18,18>>^ E sob o seu controle estava Jeozabade, e com ele havia cento e oitenta mil homens equipados para o exército.

[[v14-17-19]]

^<<v14-17-19,19>>^ Estes eram os que ministravam ao rei, além dos que o rei colocou nas cidades fortificadas por todo o Judá.

'''

xref:014-2-cronicas/014-2-cronicas-016.adoc#v14-16-0[&#60; Capítulo Anterior] | <<v14-17-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-018.adoc#v14-18-0[Próximo Capítulo &#62;]