include::./index.adoc[]

[[v14-23-0]]
=== 2 Crônicas, 23
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v14-23-1]]

^<<v14-23-1,1>>^ E no sétimo ano, Jeoiada mostrou-se corajoso e passou a tomar os chefes de cem, a saber, Azarias, filho de Jeroão, e Ismael, filho de Jeoanã, e Azarias, filho de Obede, e Maaséias, filho de Adaías, e Elisafate, filho de Zicri, fazendo com eles um pacto.

[[v14-23-2]]

^<<v14-23-2,2>>^ Depois fizeram a ronda através de Judá e reuniram os levitas de todas as cidades de Judá, bem como os cabeças das casas paternas de Israel. Chegaram, pois, a Jerusalém.

[[v14-23-3]]

^<<v14-23-3,3>>^ Toda a congregação concluiu então um pacto com o rei na casa do [verdadeiro] Deus, dizendo-lhes ele depois:
“Eis que reinará o próprio filho do rei, assim como Jeová prometeu referente aos filhos de Davi.

[[v14-23-4]]

^<<v14-23-4,4>>^ Esta é a coisa que fareis: um terço de vós que estais entrando no sábado, dos sacerdotes e dos levitas, sereis guardas das portas;

[[v14-23-5]]

^<<v14-23-5,5>>^ e um terço ficará na casa do rei; e um terço ficará no Portão do Fundamento; e todo o povo ficará nos pátios da casa de Jeová.

[[v14-23-6]]

^<<v14-23-6,6>>^ E não deixeis a ninguém entrar na casa de Jeová, exceto os sacerdotes e aqueles dos levitas que estiverem ministrando. Estes são os que entrarão, porque são um grupo santo, e todos os do próprio povo cumprirão a obrigação para com Jeová.

[[v14-23-7]]

^<<v14-23-7,7>>^ E os levitas terão de rodear o rei em toda a volta, cada um com as suas armas nas mãos; e quanto a alguém que entrar na casa, deve ser morto. E permanecei com o rei quando ele entrar e quando sair.”

[[v14-23-8]]

^<<v14-23-8,8>>^ E os levitas e todo o Judá passaram a fazer segundo tudo o que Jeoiada, o sacerdote, ordenara. Portanto, tomaram cada um os seus homens que estavam entrando no sábado, junto com os que iam sair no sábado, porque Jeoiada não dispensara as turmas do dever.

[[v14-23-9]]

^<<v14-23-9,9>>^ Além disso, Jeoiada, o sacerdote, deu aos chefes de cem as lanças e os escudos, e os escudos redondos, que pertenceram ao Rei Davi, os quais estavam na casa do [verdadeiro] Deus.

[[v14-23-10]]

^<<v14-23-10,10>>^ E foi colocar todo o povo, sim, cada um com a sua arma de arremesso na mão, desde o lado direito da casa até o lado esquerdo da casa, junto ao altar e junto à casa, em todo o redor, perto do rei.

[[v14-23-11]]

^<<v14-23-11,11>>^ Trouxeram então para fora o filho do rei e puseram sobre ele o diadema e o Testemunho, e fizeram-no rei, e assim o ungiram Jeoiada e seus filhos e disseram: “Viva o rei!”

[[v14-23-12]]

^<<v14-23-12,12>>^ Quando Atalia ouviu o ruído do povo correndo e louvando o rei, foi imediatamente ter com o povo na casa de Jeová.

[[v14-23-13]]

^<<v14-23-13,13>>^ Então ela viu, e eis o rei de pé junto à sua coluna^&#42;1^ na entrada, e os príncipes e as trombetas junto ao rei, e todo o povo da terra alegrando-se e tocando as trombetas, e os cantores com os instrumentos de canto, bem como os que davam o sinal para se oferecer louvor. Atalia rasgou imediatamente as suas vestes e disse: “Conspiração! Conspiração!”

[NOTE]
====
. Possivelmente: “seu lugar de parada”.
====

[[v14-23-14]]

^<<v14-23-14,14>>^ Mas Jeoiada, o sacerdote, fez sair os chefes de cem, os encarregados da força militar, e disse-lhes: “Levai-a para fora das fileiras; e quanto a qualquer que for atrás dela, deve ser morto à espada!” Porque o sacerdote havia dito: “Não a deveis entregar à morte na casa de Jeová.”

[[v14-23-15]]

^<<v14-23-15,15>>^ De modo que deitaram mãos nela. E chegando ela à entrada do portão dos cavalos, da casa do rei, entregaram-na ali imediatamente à morte.

[[v14-23-16]]

^<<v14-23-16,16>>^ Jeoiada concluiu então um pacto entre si^&#42;1^ e todo o povo, e o rei, de que continuariam como povo de Jeová.

[NOTE]
====
. “Jeová” em 2Rs 11:17.
====

[[v14-23-17]]

^<<v14-23-17,17>>^ Depois chegou todo o povo à casa de Baal e a demoliu; e destroçaram os seus altares e as suas imagens, e mataram a Matã, sacerdote de Baal, diante dos altares.

[[v14-23-18]]

^<<v14-23-18,18>>^ Outrossim, Jeoiada pôs os cargos da casa de Jeová na mão dos sacerdotes [e] dos levitas,^&#42;1^ a quem Davi tinha posto em turmas sobre a casa de Jeová para oferecer os sacrifícios queimados de Jeová, conforme o que está escrito na lei de Moisés, com alegria e com cântico, pelas mãos de Davi.

[NOTE]
====
. “Dos sacerdotes e dos levitas”, LXXSyVg e alguns mss. hebr.; M: “dos sacerdotes, dos levitas”.
====

[[v14-23-19]]

^<<v14-23-19,19>>^ De modo que colocou em posição os porteiros nos portões da casa de Jeová para que não entrasse ninguém que de algum modo fosse impuro.

[[v14-23-20]]

^<<v14-23-20,20>>^ Tomou então os chefes de cem, e os majestosos, e os governantes do povo, e todo o povo da terra, e fez o rei descer da casa de Jeová. Então chegaram à casa do rei através do portão superior e fizeram o rei assentar-se no trono do reino.

[[v14-23-21]]

^<<v14-23-21,21>>^ E todo o povo da terra continuou a alegrar-se; e a própria cidade teve sossego, e a Atalia tinham entregue à morte pela espada.

'''

xref:014-2-cronicas/014-2-cronicas-022.adoc#v14-22-0[&#60; Capítulo Anterior] | <<v14-23-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-024.adoc#v14-24-0[Próximo Capítulo &#62;]