include::./index.adoc[]

[[v14-4-0]]
=== 2 Crônicas, 4
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v14-4-1]]

^<<v14-4-1,1>>^ Então fez o altar de cobre, tendo ele vinte côvados de comprimento, e vinte côvados de largura, e dez côvados de altura.

[[v14-4-2]]

^<<v14-4-2,2>>^ E ele passou a fazer o mar de fundição de dez côvados de uma borda à sua outra borda, circular em toda a volta, e sua altura era de cinco côvados e requeria um cordel de trinta côvados para circundá-lo em toda a volta.

[[v14-4-3]]

^<<v14-4-3,3>>^ E havia a semelhança de ornamentos em forma de bagas^&#42;1^ abaixo dele em toda a volta, circundando-o, dez por côvado, rodeando o mar em toda a volta. Os ornamentos em forma de bagas estavam em duas fileiras, fundidos na sua fundição.

[NOTE]
====
. “Ornamentos em forma de bagas”, mediante uma correção, em harmonia com 1Rs 7:24. Lit.: “touros”.
====

[[v14-4-4]]

^<<v14-4-4,4>>^ Estava posto sobre doze touros, três enfrentando o norte, e três enfrentando o oeste, e três enfrentando o sul, e três enfrentando o leste; e o mar estava sobre eles, e todas as suas partes posteriores convergiam para o centro.

[[v14-4-5]]

^<<v14-4-5,5>>^ E tinha a grossura da largura da mão;^&#42;1^ e sua borda era do trabalho da borda dum copo, uma flor de lírio. Como receptáculo, podia conter [a medida de] três mil batos.^&#42;2^

[NOTE]
====
. Cerca de 7,4 cm.
. Cerca de 66.000 l quando enchido até o limite. Veja 1Rs 7:26 n.: “batos”.
====

[[v14-4-6]]

^<<v14-4-6,6>>^ Além disso, fez dez bacias e pôs cinco à direita e cinco à esquerda, para se fazer a lavagem nelas. Enxaguavam nelas as coisas que tinham que ver com a oferta queimada. O mar, porém, era para os sacerdotes se lavarem nele.

[[v14-4-7]]

^<<v14-4-7,7>>^ Fez então candelabros de ouro, dez deles do mesmo plano, e os pôs no templo, cinco à direita e cinco à esquerda.

[[v14-4-8]]

^<<v14-4-8,8>>^ Além disso, fez dez mesas e as colocou no templo, cinco à direita e cinco à esquerda, e fez cem tigelas de ouro.

[[v14-4-9]]

^<<v14-4-9,9>>^ Ele fez então o pátio dos sacerdotes e o grande cercado, bem como as portas pertencentes ao cercado, e suas portas ele recobriu de cobre.

[[v14-4-10]]

^<<v14-4-10,10>>^ E colocou o mar ao lado direito, ao leste, para o sul.

[[v14-4-11]]

^<<v14-4-11,11>>^ Finalmente, Hirão^&#42;1^ fez os recipientes, e as pás, e as tigelas.
Assim Hirão acabou de fazer a obra que fez para o Rei Salomão na casa do [verdadeiro] Deus.

[NOTE]
====
. “Hirão”, LXXVg; M: “Hurão”.
====

[[v14-4-12]]

^<<v14-4-12,12>>^ As duas colunas e os capitéis redondos no topo das duas colunas, e as duas redes para cobrir os dois capitéis redondos que havia no topo das colunas,

[[v14-4-13]]

^<<v14-4-13,13>>^ e as quatrocentas romãs para as duas redes, duas fileiras de romãs para cada rede, para cobrir os dois capitéis redondos que havia nas colunas,^&#42;1^

[NOTE]
====
. “Nas colunas”, LXX; M: “diante das colunas”.
====

[[v14-4-14]]

^<<v14-4-14,14>>^ e os dez carrocins e as dez bacias nos carrocins;

[[v14-4-15]]

^<<v14-4-15,15>>^ o único mar e os doze touros por baixo dele,

[[v14-4-16]]

^<<v14-4-16,16>>^ e os recipientes, e as pás, e os garfos, e todos os seus utensílios foram feitos por Hirão-Abive^&#42;1^ para o Rei Salomão, para a casa de Jeová, de cobre polido.

[NOTE]
====
. Ou “Hirão, seu pai”. Veja 2:13 n.
====

[[v14-4-17]]

^<<v14-4-17,17>>^ O rei os fundiu no Distrito do Jordão no solo grosso^&#42;1^ entre Sucote e Zereda.

[NOTE]
====
. Lit.: “na grossura (na compacidade) do solo”, isto é, em solo argiloso. Possivelmente, mediante uma correção do M: “junto ao vau de Adamá”. Veja 1Rs 7:46 n.: “argila”.
====

[[v14-4-18]]

^<<v14-4-18,18>>^ Assim fez Salomão todos estes utensílios em quantidade muito grande, pois não se averiguou o peso do cobre.

[[v14-4-19]]

^<<v14-4-19,19>>^ E Salomão passou a fazer todos os utensílios que estavam na casa do [verdadeiro] Deus, e o altar de ouro e as mesas com o pão da proposição^&#42;1^ sobre elas,

[NOTE]
====
. Veja 1Rs 7:48 n.
====

[[v14-4-20]]

^<<v14-4-20,20>>^ e os candelabros e suas lâmpadas, de ouro puro, para que fossem acesas diante do compartimento mais recôndito, segundo a regra;

[[v14-4-21]]

^<<v14-4-21,21>>^ e as flores, e as lâmpadas, e as espevitadeiras, de ouro, (era o ouro mais puro,)

[[v14-4-22]]

^<<v14-4-22,22>>^ e os apagadores, e as tigelas, e as taças, e os porta-lumes, de ouro puro, e a entrada da casa, [os batentes da] sua porta interna para o Santíssimo e [os batentes da] porta da casa do templo, de ouro.

'''

xref:014-2-cronicas/014-2-cronicas-003.adoc#v14-3-0[&#60; Capítulo Anterior] | <<v14-4-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-005.adoc#v14-5-0[Próximo Capítulo &#62;]