include::./index.adoc[]

[[v14-10-0]]
=== 2 Crônicas, 10
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v14-10-1]]

^<<v14-10-1,1>>^ E Roboão passou a ir a Siquém, pois foi a Siquém que todos os israelitas vieram para fazê-lo rei.

[[v14-10-2]]

^<<v14-10-2,2>>^ E sucedeu que, assim que Jeroboão, filho de Nebate, ouviu isso enquanto estava ainda no Egito, (pois havia fugido por causa de Salomão, o rei,) Jeroboão voltou imediatamente do Egito.

[[v14-10-3]]

^<<v14-10-3,3>>^ Portanto, mandaram chamá-lo, e Jeroboão e todo o Israel vieram e falaram a Roboão, dizendo:

[[v14-10-4]]

^<<v14-10-4,4>>^ “Teu pai, da sua parte, fez duro o nosso jugo, e agora alivia o serviço duro de teu pai e o jugo pesado que ele pôs sobre nós, e te serviremos.”

[[v14-10-5]]

^<<v14-10-5,5>>^ Então ele lhes disse: “Haja ainda três dias. Então retornai a mim.” Portanto, o povo foi embora.

[[v14-10-6]]

^<<v14-10-6,6>>^ E o Rei Roboão começou a aconselhar-se com os anciãos que haviam assistido continuamente a Salomão, seu pai, enquanto vivia, dizendo: “Como aconselhais que se deve responder a este povo?”

[[v14-10-7]]

^<<v14-10-7,7>>^ Por conseguinte, falaram-lhe, dizendo: “Se te mostrares bom para com este povo, e realmente lhes deres prazer, e deveras lhes falares boas palavras, então eles certamente se tornarão teus servos para sempre.”

[[v14-10-8]]

^<<v14-10-8,8>>^ No entanto, ele abandonou o conselho dos anciãos, com que o tinham aconselhado, e começou a aconselhar-se com os jovens que haviam crescido com ele, os quais eram os que assistiam diante dele.

[[v14-10-9]]

^<<v14-10-9,9>>^ E prosseguiu, dizendo-lhes: “O que ofereceis vós como conselho para que respondamos a este povo que me falou, dizendo: ‘Alivia o jugo que teu pai pôs sobre nós’?”

[[v14-10-10]]

^<<v14-10-10,10>>^ Por sua vez, os jovens que haviam crescido com ele falaram-lhe, dizendo: “Isto é o que deves dizer ao povo que te falou, dizendo: ‘Teu pai, da sua parte, fez pesado o nosso jugo, mas tu, alivia-o para nós’; isto é o que deves dizer-lhes: ‘Meu próprio dedo mínimo há de ser mais grosso do que os quadris de meu pai.

[[v14-10-11]]

^<<v14-10-11,11>>^ E agora, meu pai, da sua parte, carregou-vos dum jugo pesado, mas eu, da minha parte, aumentarei o vosso jugo. Meu pai, da sua parte, castigou-vos com chicotes, mas eu, da minha parte, com azorragues.’”

[[v14-10-12]]

^<<v14-10-12,12>>^ E Jeroboão e todo o povo passaram a vir a Roboão no terceiro dia, assim como o rei havia falado, dizendo: “Retornai a mim no terceiro dia.”

[[v14-10-13]]

^<<v14-10-13,13>>^ E o rei começou a responder-lhes rispidamente. Assim abandonou o Rei Roboão o conselho dos anciãos,

[[v14-10-14]]

^<<v14-10-14,14>>^ e prosseguiu, falando-lhes segundo o conselho dos jovens, dizendo: “Farei mais pesado o vosso jugo, e eu, da minha parte, acrescentarei a ele. Meu pai, da sua parte, castigou-vos com chicotes, mas eu, da minha parte, com azorragues.”

[[v14-10-15]]

^<<v14-10-15,15>>^ E o rei não escutou o povo; pois isso mostrou ser um desenvolvimento da parte do [verdadeiro] Deus, a fim de que Jeová executasse a sua palavra que falara por intermédio de Aijá,^&#42;1^ o silonita, a Jeroboão, filho de Nebate.

[NOTE]
====
. Significando “Irmão de Jeová”. Hebr.: ’Ahhi·yá·hu.
====

[[v14-10-16]]

^<<v14-10-16,16>>^ Quanto a todo o Israel, visto que o rei não os escutou, o povo replicou então ao rei, dizendo: “Que quinhão temos em Davi? E não há herança no filho de Jessé. Cada um aos seus deuses,^&#42;1^ ó Israel! Olha agora pela tua própria casa, ó Davi.” Com isso todo o Israel começou a ir para as suas tendas.

[NOTE]
====
. “Aos seus deuses.” Lit.: “às suas tendas”. Hebr.: le’o·ha·leí·kha. Esta é uma das Dezoito Emendas dos soferins. Afirma-se que o texto original hebr. tenha rezado le’·lo·heí·kha (de ’elo·hím, “deuses” ou “Deus”), mas, pela transposição de l e de h, a segunda e a terceira consoante da palavra hebr. ’elo·hím, os soferins fizeram o M rezar “tendas”. Veja Ap. 2B.
====

[[v14-10-17]]

^<<v14-10-17,17>>^ Quanto aos filhos de Israel que moravam nas cidades de Judá, sobre estes Roboão continuou a reinar.

[[v14-10-18]]

^<<v14-10-18,18>>^ Subseqüentemente, o Rei Roboão enviou Hadorão,^&#42;1^ que estava sobre os recrutados para o trabalho forçado, mas os filhos de Israel atiraram pedras nele, de modo que morreu. E o próprio Rei Roboão conseguiu subir ao seu carro, a fim de fugir para Jerusalém.

[NOTE]
====
. “Adonirão” em 1Rs 4:6; em 1Rs 12:18: “Adorão”.
====

[[v14-10-19]]

^<<v14-10-19,19>>^ E os israelitas têm persistido na sua revolta contra a casa de Davi até o dia de hoje.

'''

xref:014-2-cronicas/014-2-cronicas-009.adoc#v14-9-0[&#60; Capítulo Anterior] | <<v14-10-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-011.adoc#v14-11-0[Próximo Capítulo &#62;]