include::./index.adoc[]

[[v14-11-0]]
=== 2 Crônicas, 11
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v14-11-1]]

^<<v14-11-1,1>>^ Quando Roboão chegou a Jerusalém, congregou imediatamente a casa de Judá e de Benjamim, cento e oitenta mil homens seletos, aptos para a guerra, para lutar contra Israel, a fim de fazer voltar o reino a Roboão.

[[v14-11-2]]

^<<v14-11-2,2>>^ Então veio a palavra de Jeová a Semaías,^&#42;1^ homem do [verdadeiro] Deus, dizendo:

[NOTE]
====
. Significando “Jeová Ouviu”. Hebr.: Shema·‛eyá·hu.
====

[[v14-11-3]]

^<<v14-11-3,3>>^ “Dize a Roboão, filho de Salomão, rei de Judá, e a todo o Israel em Judá e em Benjamim, dizendo:

[[v14-11-4]]

^<<v14-11-4,4>>^ ‘Assim disse Jeová: “Não deveis subir e lutar contra os vossos irmãos. Voltai cada um para a sua casa, pois é da minha parte que esta coisa sucedeu.”’” Obedeceram, pois, à palavra de Jeová e retornaram de ir contra Jeroboão.

[[v14-11-5]]

^<<v14-11-5,5>>^ E Roboão continuou morando em Jerusalém e passou a construir cidades fortificadas em Judá.

[[v14-11-6]]

^<<v14-11-6,6>>^ Assim reconstruiu Belém, e Étão, e Tecoa,

[[v14-11-7]]

^<<v14-11-7,7>>^ e Bete-Zur, e Soco, e Adulão,

[[v14-11-8]]

^<<v14-11-8,8>>^ e Gate, e Maressa, e Zife,

[[v14-11-9]]

^<<v14-11-9,9>>^ e Adoraim, e Laquis, e Azeca,

[[v14-11-10]]

^<<v14-11-10,10>>^ e Zorá, e Aijalom, e Hébron, cidades fortificadas que se achavam em Judá e em Benjamim.

[[v14-11-11]]

^<<v14-11-11,11>>^ Além disso, reforçou as fortificações e pôs nelas líderes, e suprimentos de alimentos, e azeite, e vinho,

[[v14-11-12]]

^<<v14-11-12,12>>^ e em todas as diversas cidades escudos grandes e lanças; e prosseguiu reforçando-as a um grau muito alto. E Judá e Benjamim continuaram a ser seus.

[[v14-11-13]]

^<<v14-11-13,13>>^ E os próprios sacerdotes e levitas que estavam em todo o Israel tomaram a sua posição ao lado dele, procedentes de todos os seus territórios.

[[v14-11-14]]

^<<v14-11-14,14>>^ Pois os levitas abandonaram os seus pastios e sua propriedade, e então vieram a Judá e a Jerusalém, porque Jeroboão e seus filhos os tinham dispensado de atuar como sacerdotes para com Jeová.

[[v14-11-15]]

^<<v14-11-15,15>>^ E ele passou a constituir para si sacerdotes para os altos, e para os demônios caprinos,^&#42;1^ e para os bezerros que tinha feito.

[NOTE]
====
. “Demônios caprinos.” Talvez os que os adoravam achassem que se tratava de criaturas peludas em forma de bode. Veja Le 17:7 n.: “caprinos”.
====

[[v14-11-16]]

^<<v14-11-16,16>>^ E seguiam-nos de todas as tribos de Israel os que davam seu coração para procurar a Jeová, o Deus de Israel, vindo eles mesmos a Jerusalém para oferecer sacrifícios a Jeová, o Deus de seus antepassados.

[[v14-11-17]]

^<<v14-11-17,17>>^ E continuaram a fortalecer o reinado de Judá e a confirmar Roboão, filho de Salomão, por três anos, pois andavam no caminho de Davi e de Salomão por três anos.

[[v14-11-18]]

^<<v14-11-18,18>>^ Roboão tomou então por esposa a Maalate, filha de Jerimote, filho de Davi, e de Abiail, filha de Eliabe, filho de Jessé.

[[v14-11-19]]

^<<v14-11-19,19>>^ Com o tempo ela lhe deu à luz filhos, Jeús e Semarias, e Zaão.

[[v14-11-20]]

^<<v14-11-20,20>>^ E após ela tomou a Maacá, neta de Absalão. Com o tempo ela lhe deu à luz Abias, e Atai, e Ziza, e Selomite.

[[v14-11-21]]

^<<v14-11-21,21>>^ E Roboão amava mais a Maacá, neta de Absalão, do que a todas as suas outras esposas e suas concubinas; pois havia tomado dezoito esposas, também sessenta concubinas, de modo que se tornou pai de vinte e oito filhos e sessenta filhas.

[[v14-11-22]]

^<<v14-11-22,22>>^ Por conseguinte, Roboão constituiu a Abias, filho de Maacá, como cabeça, como líder entre os seus irmãos, pois [pensava em] fazê-lo rei.

[[v14-11-23]]

^<<v14-11-23,23>>^ No entanto, ele agiu com entendimento e distribuiu alguns dentre todos os seus filhos por todas as terras de Judá e de Benjamim, por todas as cidades fortificadas, e deu-lhes alimento em abundância e providenciou [para eles] uma multidão de esposas.

'''

xref:014-2-cronicas/014-2-cronicas-010.adoc#v14-10-0[&#60; Capítulo Anterior] | <<v14-11-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-012.adoc#v14-12-0[Próximo Capítulo &#62;]