include::./index.adoc[]

[[v14-9-0]]
=== 2 Crônicas, 9
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v14-9-1]]

^<<v14-9-1,1>>^ E a própria rainha de Sabá ouviu as notícias a respeito de Salomão e ela passou a vir, para pôr Salomão à prova com perguntas difíceis, em Jerusalém, junto com um séquito bem impressionante e com camelos carregando óleo de bálsamo, e ouro em grande quantidade, e pedras preciosas. Por fim ela entrou até Salomão e falou com ele sobre tudo o que lhe veio a ser achegado ao coração.

[[v14-9-2]]

^<<v14-9-2,2>>^ Salomão, por sua vez, informava-a sobre todos os assuntos dela e nenhum assunto ficou oculto a Salomão, que ele não lhe comunicasse.

[[v14-9-3]]

^<<v14-9-3,3>>^ Quando a rainha de Sabá chegou a ver a sabedoria de Salomão e a casa que tinha construído,

[[v14-9-4]]

^<<v14-9-4,4>>^ e o alimento da sua mesa, e a maneira de se assentarem os seus servos, e o serviço à mesa^&#42;1^ dos seus garçons e o vestuário deles, e seu serviço de bebida e o vestuário deles, e seus sacrifícios queimados que oferecia regularmente na casa de Jeová, então se mostrou não haver mais espírito nela.

[NOTE]
====
. Lit.: “ficar de pé”.
====

[[v14-9-5]]

^<<v14-9-5,5>>^ De modo que ela disse ao rei: “Veraz foi a palavra que ouvi na minha própria terra sobre os teus assuntos e sobre a tua sabedoria.

[[v14-9-6]]

^<<v14-9-6,6>>^ E eu não tive fé nas suas palavras até que vim ver com os meus próprios olhos; e eis que não me foi contada nem a metade da abundância da tua sabedoria. Ultrapassaste as notícias que ouvi.

[[v14-9-7]]

^<<v14-9-7,7>>^ Felizes são os teus homens e felizes são estes servos teus que estão constantemente de pé diante de ti e escutam a tua sabedoria.

[[v14-9-8]]

^<<v14-9-8,8>>^ Que venha a ser bendito Jeová, teu Deus, aquele que se agradou de ti, pondo-te no seu trono como rei por Jeová, teu Deus; porque o teu Deus amou Israel para fazê-lo ficar de pé por tempo indefinido, de modo que te pôs sobre eles como rei para executar decisões judiciais e justiça.”

[[v14-9-9]]

^<<v14-9-9,9>>^ Então ela deu ao rei cento e vinte talentos^&#42;1^ de ouro, e óleo de bálsamo em quantidade muito grande, e pedras preciosas; e nunca viera a ter óleo de bálsamo semelhante a este que a rainha de Sabá deu ao Rei Salomão.

[NOTE]
====
. Veja Ap. 8A.
====

[[v14-9-10]]

^<<v14-9-10,10>>^ E além disso, os servos de Hirão e os servos de Salomão, que trouxeram ouro de Ofir, trouxeram também madeira de algum e pedras preciosas.

[[v14-9-11]]

^<<v14-9-11,11>>^ E o rei passou a fazer da madeira de algum escadas para a casa de Jeová e para a casa do rei, e também harpas e instrumentos de cordas para os cantores, e nunca antes se vira tais na terra de Judá.

[[v14-9-12]]

^<<v14-9-12,12>>^ E o próprio Rei Salomão deu à rainha de Sabá tudo do seu agrado que ela havia pedido, além [do valor] daquilo que ela trouxe ao rei. Portanto, ela se virou e foi para a sua própria terra, ela junto com os seus servos.

[[v14-9-13]]

^<<v14-9-13,13>>^ E o peso do ouro que chegou a Salomão num só ano ascendeu a seiscentos e sessenta e seis talentos^&#42;1^ de ouro,

[NOTE]
====
. Veja Ap. 8A.
====

[[v14-9-14]]

^<<v14-9-14,14>>^ além do que entrou dos viajantes^&#42;1^ e dos mercadores, e de todos os reis dos árabes e dos governadores do país que traziam ouro e prata a Salomão.

[NOTE]
====
. Ou “negociantes”. Possivelmente, mediante uma correção do M: “os navios de Társis”.
====

[[v14-9-15]]

^<<v14-9-15,15>>^ E o Rei Salomão foi fazer duzentos escudos grandes de liga de ouro (passou a pôr em cada escudo grande seiscentos [siclos] de liga de ouro),

[[v14-9-16]]

^<<v14-9-16,16>>^ e trezentos broquéis de liga de ouro (passou a pôr em cada broquel três minas^&#42;1^ de ouro). O rei os colocou então na Casa da Floresta do Líbano.

[NOTE]
====
. “Minas”, Sy e 1Rs 10:17; M: “centos”.
====

[[v14-9-17]]

^<<v14-9-17,17>>^ Além disso, o rei fez um grande trono de marfim e o recobriu de ouro puro.

[[v14-9-18]]

^<<v14-9-18,18>>^ E havia seis degraus [levando] ao trono, e havia um escabelo de ouro para o trono, (estes estavam fixos,) e havia braços deste e daquele lado junto ao assento, e dois leões estavam em pé ao lado dos braços.

[[v14-9-19]]

^<<v14-9-19,19>>^ E havia doze leões em pé sobre os seis degraus, deste e daquele lado. Nenhum outro reino tinha feito um exatamente igual a ele.

[[v14-9-20]]

^<<v14-9-20,20>>^ E todos os vasos para beber, do Rei Salomão, eram de ouro, e todos os vasos da Casa da Floresta do Líbano eram de ouro puro. Não havia nada de prata; nos dias de Salomão não se lhe dava nenhuma importância.

[[v14-9-21]]

^<<v14-9-21,21>>^ Pois, navios pertencentes ao rei iam a Társis com os servos de Hirão. Uma vez em cada três anos os navios de Társis vinham trazendo ouro e prata, marfim, e macacos e pavões.

[[v14-9-22]]

^<<v14-9-22,22>>^ De modo que o Rei Salomão era maior em riquezas e em sabedoria do que todos os outros reis da terra.

[[v14-9-23]]

^<<v14-9-23,23>>^ E todos os reis da terra procuravam a face de Salomão para ouvir a sua sabedoria, que o [verdadeiro] Deus lhe pusera no coração.

[[v14-9-24]]

^<<v14-9-24,24>>^ E traziam cada um o seu presente: objetos de prata e objetos de ouro, e mantos, armamento e óleo de bálsamo, cavalos e mulos, como questão rotineira anual.

[[v14-9-25]]

^<<v14-9-25,25>>^ E Salomão veio a ter quatro mil baias para cavalos, e carros, e doze mil corcéis,^&#42;1^ e manteve-os aquartelados em cidades de carros e perto do rei em Jerusalém.

[NOTE]
====
. Ou “cavaleiros”.
====

[[v14-9-26]]

^<<v14-9-26,26>>^ E ele veio a ser governante sobre todos os reis, desde o Rio^&#42;1^ para baixo até a terra dos filisteus e até o termo do Egito.

[NOTE]
====
. Isto é, o Eufrates.
====

[[v14-9-27]]

^<<v14-9-27,27>>^ Outrossim, o rei tornou a prata em Jerusalém igual às pedras; e a madeira de cedro ele tornou igual aos sicômoros que há na Sefelá,^&#42;1^ por causa da sua abundância.

[NOTE]
====
. Ou “na terra baixa”.
====

[[v14-9-28]]

^<<v14-9-28,28>>^ E havia os que traziam a Salomão cavalos do Egito e de todas as outras terras.

[[v14-9-29]]

^<<v14-9-29,29>>^ Quanto ao restante dos assuntos de Salomão, os primeiros e os últimos, não estão escritos entre as palavras de Natã, o profeta, e na profecia de Aijá, o silonita, e no registro das visões de Ido,^&#42;1^ o visionário, referente a Jeroboão, filho de Nebate?

[NOTE]
====
. Lit.: “Jedi”, M; Mmargem: “Jedo”. Veja 12:15.
====

[[v14-9-30]]

^<<v14-9-30,30>>^ E Salomão continuou a reinar em Jerusalém sobre todo o Israel por quarenta anos.

[[v14-9-31]]

^<<v14-9-31,31>>^ Por fim, Salomão deitou-se com os seus antepassados. Portanto, enterraram-no na Cidade de Davi, seu pai; e Roboão, seu filho, começou a reinar em seu lugar.

'''

xref:014-2-cronicas/014-2-cronicas-008.adoc#v14-8-0[&#60; Capítulo Anterior] | <<v14-9-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-010.adoc#v14-10-0[Próximo Capítulo &#62;]