include::./index.adoc[]

[[v14-33-0]]
=== 2 Crônicas, 33
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v14-33-1]]

^<<v14-33-1,1>>^ Manassés tinha doze anos de idade quando começou a reinar e reinou por cinqüenta e cinco anos em Jerusalém.

[[v14-33-2]]

^<<v14-33-2,2>>^ E ele passou a fazer o que era mau aos olhos de Jeová, segundo as coisas detestáveis das nações que Jeová tinha desalojado de diante dos filhos de Israel.

[[v14-33-3]]

^<<v14-33-3,3>>^ De modo que reconstruiu os altos que Ezequias, seu pai, tinha demolido, e erigiu altares aos Baalins e fez postes sagrados, e começou a curvar-se diante de todo o exército dos céus e a servi-los.

[[v14-33-4]]

^<<v14-33-4,4>>^ E construiu altares na casa de Jeová, referente à qual Jeová dissera: “Em Jerusalém mostrará estar meu nome por tempo indefinido.”

[[v14-33-5]]

^<<v14-33-5,5>>^ E foi construir altares a todo o exército dos céus em dois pátios da casa de Jeová.

[[v14-33-6]]

^<<v14-33-6,6>>^ E ele mesmo fez os seus próprios filhos passar pelo fogo no vale do filho de Hinom,^&#42;1^ e praticou a magia, e fez uso da adivinhação, e praticou a feitiçaria, e constituiu médiuns espíritas e prognosticadores profissionais de eventos. Fez em grande escala o que era mau aos olhos de Jeová para o ofender.

[NOTE]
====
. Veja Ap. 4C.
====

[[v14-33-7]]

^<<v14-33-7,7>>^ Além disso, a imagem esculpida que fizera ele colocou na casa do [verdadeiro] Deus, a respeito da qual Deus dissera a Davi e a Salomão, seu filho: “Nesta casa e em Jerusalém, que escolhi dentre todas as tribos de Israel, porei meu nome por tempo indefinido.

[[v14-33-8]]

^<<v14-33-8,8>>^ E não removerei mais o pé de Israel do solo que designei aos seus^&#42;1^ antepassados, se tão-somente cuidarem de fazer tudo o que lhes ordenei referente a toda a lei, e aos regulamentos, e às decisões judiciais, pela mão de Moisés.”

[NOTE]
====
. “Seus”, LXXSyVg e 2Rs 21:8; M: “teus”.
====

[[v14-33-9]]

^<<v14-33-9,9>>^ E Manassés continuou a seduzir Judá e os habitantes de Jerusalém para fazerem pior do que as nações que Jeová aniquilara de diante dos filhos de Israel.

[[v14-33-10]]

^<<v14-33-10,10>>^ E Jeová falava a Manassés e a seu povo, mas eles não prestavam atenção.

[[v14-33-11]]

^<<v14-33-11,11>>^ Por fim, Jeová trouxe contra eles os chefes do exército que pertencia ao rei da Assíria e eles capturaram, pois, a Manassés nos recessos e prenderam-no com dois grilhões de cobre, e levaram-no a Babilônia.

[[v14-33-12]]

^<<v14-33-12,12>>^ E assim que isto lhe causou aflição, abrandou a face de Jeová, seu Deus, e continuou a humilhar-se grandemente por causa do Deus de seus antepassados.

[[v14-33-13]]

^<<v14-33-13,13>>^ E orava a Ele, de modo que se deixou suplicar por ele e ouviu seu pedido de favor, e restaurou-o a Jerusalém ao seu reinado; e Manassés veio a saber que Jeová é o [verdadeiro] Deus.

[[v14-33-14]]

^<<v14-33-14,14>>^ E depois construiu uma muralha externa para a Cidade de Davi, ao oeste de Giom, no vale da torrente e até o Portão do Peixe, e [a] fez dar volta até Ofel e passou a fazê-la muito alta. Além disso, pôs chefes da força militar em todas as cidades fortificadas de Judá.

[[v14-33-15]]

^<<v14-33-15,15>>^ E passou a remover da casa de Jeová os deuses estrangeiros^&#42;1^ e o ídolo, bem como todos os altares que tinha construído no monte da casa de Jeová e em Jerusalém, e então os fez lançar fora da cidade.

[NOTE]
====
. Veja 1Sa 7:3 n.
====

[[v14-33-16]]

^<<v14-33-16,16>>^ Outrossim, preparou o altar de Jeová e começou a sacrificar sobre ele sacrifícios de participação em comum e sacrifícios de agradecimento, e prosseguiu, dizendo a Judá que servisse a Jeová, o Deus de Israel.

[[v14-33-17]]

^<<v14-33-17,17>>^ Não obstante, o povo ainda oferecia sacrifícios sobre os altos; apenas o faziam a Jeová, seu Deus.

[[v14-33-18]]

^<<v14-33-18,18>>^ Quanto ao resto dos assuntos de Manassés, e à sua oração a seu Deus, e às palavras dos visionários que lhe falavam em nome de Jeová, o Deus de Israel, eis que estão entre os assuntos dos reis de Israel.

[[v14-33-19]]

^<<v14-33-19,19>>^ Quanto à sua oração e como se lhe concedeu a sua súplica, e todo o seu pecado, e sua infidelidade, e os locais onde construiu os altos e pôs os postes sagrados^&#42;1^ e as imagens entalhadas antes de se humilhar, eis que estão escritos entre as palavras dos seus visionários.^&#42;2^

[NOTE]
====
. Ou “as Axerás”.
. Ou “seus videntes”. LXX: “os videntes”.
====

[[v14-33-20]]

^<<v14-33-20,20>>^ Por fim, Manassés deitou-se com os seus antepassados e enterraram-no na sua casa; e Amom, seu filho, começou a reinar em seu lugar.

[[v14-33-21]]

^<<v14-33-21,21>>^ Amom tinha vinte e dois anos de idade quando começou a reinar e reinou por dois anos em Jerusalém.

[[v14-33-22]]

^<<v14-33-22,22>>^ E ele passou a fazer o que era mau aos olhos de Jeová, assim como Manassés, seu pai, tinha feito; e Amom ofereceu sacrifícios a todas as imagens entalhadas que Manassés, seu pai, tinha feito, e continuou a servi-las.

[[v14-33-23]]

^<<v14-33-23,23>>^ E não se humilhou por causa de Jeová assim como Manassés, seu pai, se humilhou, porque foi Amom quem fez aumentar a culpa.

[[v14-33-24]]

^<<v14-33-24,24>>^ Finalmente conspiraram contra ele seus servos e o entregaram à morte, na sua própria casa.

[[v14-33-25]]

^<<v14-33-25,25>>^ Mas o povo da terra golpeou todos os que conspiraram contra o Rei Amom e o povo da terra fez então rei a Josias, seu filho, em seu lugar.

'''

xref:014-2-cronicas/014-2-cronicas-032.adoc#v14-32-0[&#60; Capítulo Anterior] | <<v14-33-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-034.adoc#v14-34-0[Próximo Capítulo &#62;]