include::./index.adoc[]

[[v14-18-0]]
=== 2 Crônicas, 18
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v14-18-1]]

^<<v14-18-1,1>>^ E Jeosafá veio a ter riquezas e glória em abundância; mas ele formou uma aliança matrimonial com Acabe.

[[v14-18-2]]

^<<v14-18-2,2>>^ Portanto, anos mais tarde desceu a Acabe, a Samaria; e Acabe passou a sacrificar ovelhas e gado vacum em abundância para ele e para o povo que estava com ele. E começou a engodá-lo a subir contra Ramote-Gileade.

[[v14-18-3]]

^<<v14-18-3,3>>^ E Acabe, rei de Israel, prosseguiu, dizendo a Jeosafá, rei de Judá: “Irás comigo a Ramote-Gileade?” A isto lhe disse ele: “Eu sou como tu, e meu povo é como o teu povo e está contigo na guerra.”

[[v14-18-4]]

^<<v14-18-4,4>>^ No entanto, Jeosafá disse ao rei de Israel: “Por favor, consulta primeiro de tudo a palavra de Jeová.”

[[v14-18-5]]

^<<v14-18-5,5>>^ Reuniu, pois, o rei de Israel os profetas, quatrocentos homens, e disse-lhes: “Devemos ir contra Ramote-Gileade em guerra ou devo refrear-me?” E eles começaram a dizer: “Sobe, e o [verdadeiro] Deus [a] entregará na mão do rei.”

[[v14-18-6]]

^<<v14-18-6,6>>^ Jeosafá disse, porém: “Não há aqui ainda um profeta de Jeová? Então consultemos por intermédio dele.”

[[v14-18-7]]

^<<v14-18-7,7>>^ Então disse o rei de Israel a Jeosafá: “Ainda há um homem por meio de quem se pode consultar a Jeová, mas eu mesmo certamente o odeio, pois profetiza a meu respeito não o bem, senão o mal, todos os seus dias. É Micaías,^&#42;1^ filho de Inlá.” Todavia, Jeosafá disse: “Não diga o rei uma coisa dessas.”

[NOTE]
====
. Veja 1Rs 22:8 n.
====

[[v14-18-8]]

^<<v14-18-8,8>>^ Por conseguinte, o rei chamou um oficial da corte e disse: “Traze depressa a Micaías, filho de Inlá.”

[[v14-18-9]]

^<<v14-18-9,9>>^ Ora, o rei de Israel e Jeosafá, rei de Judá, estavam sentados, cada um no seu trono, vestidos de roupagem, e estavam sentados na eira à entrada do portão de Samaria; e todos os profetas procediam como profetas diante deles.

[[v14-18-10]]

^<<v14-18-10,10>>^ Então Zedequias, filho de Quenaaná, fez para si chifres de ferro e disse: “Assim disse Jeová: ‘Com estes marrarás os sírios até os exterminares.’”

[[v14-18-11]]

^<<v14-18-11,11>>^ E todos os outros profetas estavam profetizando a mesma coisa, dizendo: “Sobe a Ramote-Gileade e mostra-te bem sucedido, e Jeová certamente [a] entregará na mão do rei.”

[[v14-18-12]]

^<<v14-18-12,12>>^ E o mensageiro que foi chamar Micaías falou-lhe, dizendo: “Eis que as palavras dos profetas são unanimemente^&#42;1^ de bem para o rei; por favor, torne-se a tua palavra igual a uma deles, e tens de falar o bem.”

[NOTE]
====
. Lit.: “uma só boca”.
====

[[v14-18-13]]

^<<v14-18-13,13>>^ Micaías^&#42;1^ disse, porém: “Por Jeová que vive, o que meu Deus disser é o que falarei.”

[NOTE]
====
. Hebr.: Mi·khá·yehu. Veja Miq Título n.
====

[[v14-18-14]]

^<<v14-18-14,14>>^ Então entrou até o rei e o rei passou a dizer-lhe: “Micaías,^&#42;1^ devemos ir a Ramote-Gileade em guerra ou devo refrear-me?” Ele disse imediatamente: “Sobe e mostra-te bem sucedido; e serão entregues na vossa mão.”

[NOTE]
====
. Lit.: “Micá”.
====

[[v14-18-15]]

^<<v14-18-15,15>>^ Então o rei lhe disse: “Quantas vezes já te ponho sob juramento para não me falares nada senão a verdade em nome de Jeová?”

[[v14-18-16]]

^<<v14-18-16,16>>^ De modo que ele disse: “Deveras vejo todos os israelitas espalhados pelos montes como ovelhas sem pastor. E Jeová prosseguiu, dizendo: ‘Estes não têm amos. Que voltem cada um para a sua casa em paz.’”

[[v14-18-17]]

^<<v14-18-17,17>>^ O rei de Israel disse então a Jeosafá: “Não te disse eu: ‘Ele profetizará a meu respeito não boas coisas, senão más’?”

[[v14-18-18]]

^<<v14-18-18,18>>^ E ele prosseguiu, dizendo: “Portanto, ouvi a palavra de Jeová: Deveras vejo a Jeová sentado no seu trono e todo o exército dos céus de pé à sua direita e à sua esquerda.

[[v14-18-19]]

^<<v14-18-19,19>>^ E Jeová passou a dizer: ‘Quem logrará a Acabe, rei de Israel, para que suba e caia em Ramote-Gileade?’ E havia conversa, este dizendo uma coisa e aquele dizendo outra coisa.

[[v14-18-20]]

^<<v14-18-20,20>>^ Por fim saiu um espírito e ficou de pé perante Jeová, e disse: ‘Eu mesmo o lograrei.’ Então lhe disse Jeová: ‘Por meio de quê?’

[[v14-18-21]]

^<<v14-18-21,21>>^ A isto ele disse: ‘Sairei e certamente me tornarei um espírito enganoso na boca de todos os seus profetas.’ De modo que ele disse: ‘Tu o lograrás, e ainda mais, sairás vencedor. Sai e faze assim.’

[[v14-18-22]]

^<<v14-18-22,22>>^ E agora, eis que Jeová pôs um espírito enganoso na boca destes profetas teus; mas o próprio Jeová falou de calamidade a teu respeito.”

[[v14-18-23]]

^<<v14-18-23,23>>^ Zedequias, filho de Quenaaná, aproximou-se então e deu uma bofetada em Micaías, e disse: “Por que caminho é que passou o espírito de Jeová de mim para falar contigo?”

[[v14-18-24]]

^<<v14-18-24,24>>^ Então disse Micaías: “Eis que estarás vendo [por que caminho], naquele dia em que entrarás na câmara mais recôndita para te esconder.”

[[v14-18-25]]

^<<v14-18-25,25>>^ Disse então o rei de Israel: “Tomai a Micaías e fazei-o voltar a Amom, chefe da cidade, e a Joás, filho do rei.

[[v14-18-26]]

^<<v14-18-26,26>>^ E tereis de dizer: ‘Assim disse o rei: “Ponde a este na casa de detenção e alimentai-o com uma ração reduzida de pão e com uma ração reduzida de água até eu retornar em paz.”’”

[[v14-18-27]]

^<<v14-18-27,27>>^ A isso Micaías disse: “Se de fato voltares em paz, Jeová não falou comigo.”^&#42;1^ E acrescentou: “Ouvi, todos os povos.”

[NOTE]
====
. Ou “por mim”.
====

[[v14-18-28]]

^<<v14-18-28,28>>^ E o rei de Israel e Jeosafá, rei de Judá, passaram a subir a Ramote-Gileade.

[[v14-18-29]]

^<<v14-18-29,29>>^ O rei de Israel disse então a Jeosafá: “[Para mim é] disfarçar e entrar^&#42;1^ na batalha, mas tu, da tua parte, põe a tua roupagem.” Por conseguinte, o rei de Israel disfarçou-se, após o que entrou na batalha.

[NOTE]
====
. “Disfarçar e entrar”, isto é, da parte de Acabe. No hebr., trata-se de verbos entendidos como estando no infinitivo absoluto, indefinidos quanto ao tempo e impessoais.
====

[[v14-18-30]]

^<<v14-18-30,30>>^ Quanto ao rei da Síria, tinha ordenado aos chefes dos carros que eram dele, dizendo: “Não deveis lutar nem com pequeno nem com grande, mas somente com o rei de Israel.”

[[v14-18-31]]

^<<v14-18-31,31>>^ E sucedeu que, assim que os chefes dos carros viram Jeosafá, eles, da sua parte, disseram para si: “É o rei de Israel.” De modo que se voltaram contra ele para lutar; e Jeosafá começou a clamar por socorro e o próprio Jeová o ajudou, e Deus os engodou imediatamente para longe dele.

[[v14-18-32]]

^<<v14-18-32,32>>^ E sucedeu que, assim que os chefes dos carros viram que não mostrara ser o rei de Israel, retornaram imediatamente de segui-lo.

[[v14-18-33]]

^<<v14-18-33,33>>^ E havia um homem que entesou o arco na sua inocência, mas foi atingir o rei de Israel entre as peças acessórias e a cota de malha, de modo que este disse ao condutor do carro: “Dá volta com a tua mão, e tens de levar-me para fora do acampamento, porque fui seriamente ferido.”

[[v14-18-34]]

^<<v14-18-34,34>>^ E a batalha aumentava em intensidade naquele dia, e o próprio rei de Israel teve de ser mantido em pé no carro, enfrentando os sírios até à noitinha; e por fim morreu na hora do pôr do sol.

'''

xref:014-2-cronicas/014-2-cronicas-017.adoc#v14-17-0[&#60; Capítulo Anterior] | <<v14-18-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-019.adoc#v14-19-0[Próximo Capítulo &#62;]