include::./index.adoc[]

[[v14-28-0]]
=== 2 Crônicas, 28
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v14-28-1]]

^<<v14-28-1,1>>^ Acaz tinha vinte anos de idade quando começou a reinar e reinou por dezesseis anos em Jerusalém, e não fez o que era direito aos olhos de Jeová, igual a Davi, seu antepassado.

[[v14-28-2]]

^<<v14-28-2,2>>^ Mas andou nos caminhos dos reis de Israel e fez até mesmo estátuas fundidas dos Baalins.

[[v14-28-3]]

^<<v14-28-3,3>>^ E ele mesmo fez fumaça sacrificial no vale do filho de Hinom^&#42;1^ e passou a queimar seus filhos^&#42;2^ no fogo, segundo as coisas detestáveis das nações que Jeová havia desalojado de diante dos filhos de Israel.

[NOTE]
====
. “No vale do filho de Hinom.” Hebr.: beghéh’ ven-Hin·nóm; gr.: en Gai·be·ne·nóm; Vgc(lat.): in vál·le Be·nén·nom. Veja Ap. 4C.
. “Filhos”, MVg; Sy e 2Rs 16:3: “filho”.
====

[[v14-28-4]]

^<<v14-28-4,4>>^ E oferecia regularmente sacrifícios e fazia fumaça sacrificial nos altos, e nos morros, e debaixo de toda sorte de árvore frondosa.

[[v14-28-5]]

^<<v14-28-5,5>>^ Por conseguinte, Jeová, seu Deus, entregou-o na mão do rei da Síria, de modo que o golpearam e levaram dele grande número de cativos, e trouxeram-nos a Damasco. E ele foi dado também na mão do rei de Israel, de modo que o golpeou com uma grande matança.

[[v14-28-6]]

^<<v14-28-6,6>>^ Conseqüentemente, Peca, filho de Remalias, matou em Judá cento e vinte mil num só dia, todos homens valentes, por terem abandonado a Jeová, o Deus de seus antepassados.

[[v14-28-7]]

^<<v14-28-7,7>>^ Além disso, Zicri, homem poderoso de Efraim, matou a Maaséias, filho do rei, e a Azricão, líder dos da casa, e a Elcana, o segundo depois do rei.

[[v14-28-8]]

^<<v14-28-8,8>>^ Outrossim, os filhos de Israel tomaram cativos a duzentos mil dos seus irmãos, mulheres, filhos e filhas; e também muitíssimo despojo tomaram para si como saque, levando depois o despojo a Samaria.

[[v14-28-9]]

^<<v14-28-9,9>>^ E aconteceu que havia ali um profeta de Jeová, cujo nome era Odede. Ele saiu, pois, diante do exército que chegava a Samaria e disse-lhes: “Eis que foi por causa do furor de Jeová, o Deus de vossos antepassados, contra Judá, que ele os entregou na vossa mão, de modo que fizestes uma matança entre eles com uma fúria que chegou até os céus.

[[v14-28-10]]

^<<v14-28-10,10>>^ E agora pensais^&#42;1^ em reduzir os filhos de Judá e de Jerusalém a servos e a servas para vós. Todavia, não há com vós mesmos casos de culpa contra Jeová, vosso Deus?

[NOTE]
====
. Lit.: “dizeis [a vós mesmos]”.
====

[[v14-28-11]]

^<<v14-28-11,11>>^ E agora escutai-me e devolvei os cativos que capturastes de vossos irmãos, porque a ira ardente de Jeová está contra vós.”

[[v14-28-12]]

^<<v14-28-12,12>>^ Em vista disso, [certos] homens dos cabeças dos filhos de Efraim, Azarias, filho de Jeoanã, e Berequias, filho de Mesilemote, e Jeisquias, filho de Salum, e Amasa, filho de Hadlai, levantaram-se contra os que entravam da campanha militar

[[v14-28-13]]

^<<v14-28-13,13>>^ e disseram-lhes: “Não deveis trazer para cá os cativos, pois resultará em culpa da nossa parte contra Jeová. Pensais em acrescentar aos nossos pecados e à nossa culpa, porque abundante é a culpa que temos e há ira ardente contra Israel.”

[[v14-28-14]]

^<<v14-28-14,14>>^ Por conseguinte, os homens armados deixaram os cativos e o saque diante dos príncipes e de toda a congregação.

[[v14-28-15]]

^<<v14-28-15,15>>^ Então os homens designados por nomes levantaram-se e tomaram os cativos, e vestiram do despojo todos os que deles estavam nus. Vestiram-nos, pois, e forneceram-lhes sandálias, e alimentaram-nos, e deram-lhes de beber, e untaram-nos. Além disso, no caso de todos os que cambaleavam, deram-lhes transporte em jumentos e levaram-nos a Jericó, a cidade das palmeiras, para junto dos seus irmãos. Depois retornaram a Samaria.

[[v14-28-16]]

^<<v14-28-16,16>>^ Naquele tempo, o Rei Acaz enviou [mensageiros] aos reis da Assíria para que lhe ajudassem.

[[v14-28-17]]

^<<v14-28-17,17>>^ E novamente entraram os próprios edomitas, e então golpearam a Judá e levaram [consigo] cativos.

[[v14-28-18]]

^<<v14-28-18,18>>^ Quanto aos filisteus, fizeram uma incursão contra as cidades da Sefelá^&#42;1^ e do Negebe^&#42;2^ de Judá, e foram capturar Bete-Semes, e Aijalom, e Gederote, e Soco e suas aldeias dependentes, e Timná e suas aldeias dependentes, e Ginzo e suas aldeias dependentes; e passaram a morar ali.

[NOTE]
====
. Ou “da terra baixa”.
. Ou “do sul”. Veja Gên 12:9 n.
====

[[v14-28-19]]

^<<v14-28-19,19>>^ Pois Jeová humilhou a Judá por causa de Acaz, rei de Israel,^&#42;1^ porque deixara aumentar o desenfreio em Judá, e agia-se com grande infidelidade^&#42;2^ para com Jeová.

[NOTE]
====
. “Israel”, M; TLXXSyVg e cerca de 12 mss. hebr.: “Judá”.
. “Agia-se com . . . infidelidade.” No hebr., este verbo está no infinitivo absoluto, indefinido quanto ao tempo e impessoal.
====

[[v14-28-20]]

^<<v14-28-20,20>>^ Por fim chegou contra ele Tilgate-Pilneser, rei da Assíria, e causou-lhe aflição, e não o fortaleceu.

[[v14-28-21]]

^<<v14-28-21,21>>^ Porque Acaz despojou a casa de Jeová e a casa do rei e dos príncipes, e assim deu um presente ao rei da Assíria; mas isso não lhe era de auxílio.

[[v14-28-22]]

^<<v14-28-22,22>>^ Todavia, no tempo em que lhe causava aflição, ele agiu de modo ainda mais infiel para com Jeová, isto é, o Rei Acaz o fez.

[[v14-28-23]]

^<<v14-28-23,23>>^ E começou a oferecer sacrifícios aos deuses de Damasco que o golpeavam, e prosseguiu, dizendo: “Uma vez que os deuses dos reis da Síria os ajudam, oferecerei sacrifícios a eles para que me ajudem.” E estes mesmos se tornaram causa de tropeço para ele e para todo o Israel.

[[v14-28-24]]

^<<v14-28-24,24>>^ Ainda mais, Acaz ajuntou os utensílios da casa do [verdadeiro] Deus e retalhou os utensílios da casa do [verdadeiro] Deus, e fechou as portas da casa de Jeová e fez para si altares em cada esquina de Jerusalém.

[[v14-28-25]]

^<<v14-28-25,25>>^ E em todas as cidades, sim, nas cidades de Judá, ele fez altos para fazer fumaça sacrificial a outros deuses, de modo que ofendeu a Jeová, o Deus de seus antepassados.

[[v14-28-26]]

^<<v14-28-26,26>>^ Quanto ao resto dos seus assuntos e de todos os seus caminhos, os primeiros e os últimos, eis que estão escritos no Livro dos Reis de Judá e de Israel.

[[v14-28-27]]

^<<v14-28-27,27>>^ Por fim, Acaz deitou-se com os seus antepassados e enterraram-no na cidade, em Jerusalém, pois não o levaram às sepulturas dos reis de Israel. E Ezequias, seu filho, começou a reinar em seu lugar.

'''

xref:014-2-cronicas/014-2-cronicas-027.adoc#v14-27-0[&#60; Capítulo Anterior] | <<v14-28-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-029.adoc#v14-29-0[Próximo Capítulo &#62;]