include::./index.adoc[]

[[v14-25-0]]
=== 2 Crônicas, 25
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v14-25-1]]

^<<v14-25-1,1>>^ Amazias tornou-se rei à idade de vinte e cinco anos e reinou por vinte e nove anos em Jerusalém. E o nome de sua mãe era Jeoadã, de Jerusalém.

[[v14-25-2]]

^<<v14-25-2,2>>^ E ele fazia o que era direito aos olhos de Jeová, apenas não de pleno coração.

[[v14-25-3]]

^<<v14-25-3,3>>^ E sucedeu que, assim que o reino se tornara forte sobre ele, matou prontamente os seus servos que tinham golpeado o rei, seu pai.

[[v14-25-4]]

^<<v14-25-4,4>>^ E não entregou à morte os filhos deles, mas [fez] conforme o que está escrito na lei, no livro de Moisés, que Jeová ordenou, dizendo: “Os pais não devem morrer por causa dos filhos, nem devem os próprios filhos morrer por causa dos pais; mas cada um deve morrer pelo seu próprio pecado.”

[[v14-25-5]]

^<<v14-25-5,5>>^ E Amazias passou a reunir Judá e a fazê-los ficar de pé, segundo a casa de seus antepassados, pelos chefes de mil e pelos chefes de cem para todo o Judá e Benjamim; e ele foi registrá-los da idade de vinte anos para cima, e por fim achou que [eram] trezentos mil homens seletos que saíam para o exército, manejando a lança e o escudo grande.

[[v14-25-6]]

^<<v14-25-6,6>>^ Além disso, contratou de Israel cem mil homens poderosos, valentes, por cem talentos^&#42;1^ de prata.

[NOTE]
====
. Veja Ap. 8A.
====

[[v14-25-7]]

^<<v14-25-7,7>>^ E chegou a ele certo homem do [verdadeiro] Deus, dizendo: “Ó rei, não deixes vir contigo o exército de Israel, porque Jeová não está com Israel, [isto é,] todos os filhos de Efraim.

[[v14-25-8]]

^<<v14-25-8,8>>^ Mas vem tu mesmo, age, sê corajoso para a guerra. O [verdadeiro] Deus poderia fazer-te tropeçar diante dum inimigo; porque com Deus^&#42;1^ há poder para ajudar e para fazer tropeçar.”

[NOTE]
====
. “Deus”, MVg; LXX: “Jeová”.
====

[[v14-25-9]]

^<<v14-25-9,9>>^ Em vista disso, Amazias disse ao homem do [verdadeiro] Deus: “Mas que se deve fazer a respeito dos cem talentos que dei às tropas de Israel?” A isto disse o homem do [verdadeiro] Deus: “Há com Jeová o meio de dar-te muito mais do que isso.”

[[v14-25-10]]

^<<v14-25-10,10>>^ Por conseguinte, Amazias separou-os, a saber, as tropas que chegaram a ele de Efraim, para que fossem ao seu próprio lugar. No entanto, a ira deles acendeu-se muito contra Judá, de modo que retornaram ao seu próprio lugar em ira acesa.

[[v14-25-11]]

^<<v14-25-11,11>>^ E Amazias, da sua parte, tomou coragem e passou a chefiar seu próprio povo e a ir ao Vale do Sal; e ele foi golpear os filhos de Seir, dez mil [deles].

[[v14-25-12]]

^<<v14-25-12,12>>^ E havia dez mil que os filhos de Judá capturaram vivos. Levaram-nos, pois, ao cume do rochedo e passaram a lançá-los do cume do rochedo; e todos eles rebentaram.

[[v14-25-13]]

^<<v14-25-13,13>>^ Quanto aos membros da tropa que Amazias fez retornar de ir com ele à guerra, começaram a fazer incursões contra as cidades de Judá, desde Samaria até Bete-Horom, e foram golpear três mil deles e tomar grande saque.

[[v14-25-14]]

^<<v14-25-14,14>>^ Sucedeu, porém, depois de Amazias chegar de golpear os edomitas, que ele trouxe então os deuses dos filhos de Seir e os estabeleceu para si como deuses e começou a curvar-se diante deles, e a eles começou a fazer fumaça sacrificial.

[[v14-25-15]]

^<<v14-25-15,15>>^ Conseqüentemente, acendeu-se a ira de Jeová contra Amazias, e por isso lhe enviou um profeta e disse-lhe: “Por que buscaste os deuses do povo, que não livraram o seu próprio povo da tua mão?”

[[v14-25-16]]

^<<v14-25-16,16>>^ E aconteceu que, falando-lhe ele, [o rei] lhe disse imediatamente: “Acaso te constituímos conselheiro do rei? Deixa isso, por tua própria causa. Por que se devia golpear-te?” Por conseguinte, o profeta cessou, mas disse: “Sei com certeza que Deus resolveu arruinar-te por teres feito isto e por não teres escutado meu conselho.”

[[v14-25-17]]

^<<v14-25-17,17>>^ Amazias, o rei de Judá, aconselhou-se então e mandou dizer a Jeoás, filho de Jeoacaz, filho de Jeú, rei de Israel: “Vem! Olhemo-nos um ao outro na face.”

[[v14-25-18]]

^<<v14-25-18,18>>^ Então Jeoás, rei de Israel, mandou dizer a Amazias, rei de Judá: “A própria planta espinhosa que estava no Líbano mandou dizer ao cedro que estava no Líbano: ‘Dá deveras a tua filha ao meu filho por esposa.’ Todavia, um animal selvático do campo, que estava no Líbano, passou por ali e pisou a planta espinhosa.

[[v14-25-19]]

^<<v14-25-19,19>>^ Disseste a ti mesmo: Eis que golpeei Edom. E teu coração te elevou para ser glorificado. Agora, fica deveras morando na tua própria casa. Por que devias empenhar-te numa luta em posição má e ter de cair, tu e Judá contigo?”

[[v14-25-20]]

^<<v14-25-20,20>>^ Mas Amazias não escutou; porque isto era da parte do [verdadeiro] Deus, com o fim de entregá-los na sua mão, visto que tinham buscado os deuses de Edom.

[[v14-25-21]]

^<<v14-25-21,21>>^ De modo que subiu Jeoás, rei de Israel, e passaram a olhar-se um ao outro na face, ele e Amazias, rei de Judá, em Bete-Semes, que pertence a Judá.

[[v14-25-22]]

^<<v14-25-22,22>>^ E Judá veio a ser derrotado diante de Israel, de modo que se puseram em fuga, cada um para a sua tenda.^&#42;1^

[NOTE]
====
. Lit.: “tendas”.
====

[[v14-25-23]]

^<<v14-25-23,23>>^ E foi a Amazias, rei de Judá, filho de Jeoás, filho de Jeoacaz, que Jeoás, rei de Israel, capturou em Bete-Semes, levando-o depois a Jerusalém e fazendo uma brecha na muralha de Jerusalém, desde o Portão de Efraim até o Portão da Esquina, quatrocentos côvados.^&#42;1^

[NOTE]
====
. Cerca de 178 m.
====

[[v14-25-24]]

^<<v14-25-24,24>>^ E [tomou]^&#42;1^ todo o ouro e a prata, bem como todos os objetos que se achavam na casa do [verdadeiro] Deus com Obede-Edom, e os tesouros da casa do rei e os reféns, e então retornou a Samaria.

[NOTE]
====
. “Tomou”, Sy; MLXXVg omitem isso.
====

[[v14-25-25]]

^<<v14-25-25,25>>^ E Amazias, filho de Jeoás, rei de Judá, seguiu vivendo depois da morte de Jeoás, filho de Jeoacaz, rei de Israel, por quinze anos.

[[v14-25-26]]

^<<v14-25-26,26>>^ Quanto ao resto dos assuntos de Amazias, os primeiros e os últimos, não estão escritos no Livro dos Reis de Judá e de Israel?

[[v14-25-27]]

^<<v14-25-27,27>>^ E desde o tempo em que Amazias se desviou de seguir a Jeová passaram a formar uma conspiração contra ele em Jerusalém. Por fim ele fugiu para Laquis; porém, mandaram persegui-lo até Laquis e ali o entregaram à morte.

[[v14-25-28]]

^<<v14-25-28,28>>^ Carregaram-no, pois, sobre cavalos e enterraram-no com os seus antepassados na cidade de Judá.^&#42;1^

[NOTE]
====
. “Judá”, M; LXXSyVg, 12 mss. hebr. e 2Rs 14:20: “Davi”.
====

'''

xref:014-2-cronicas/014-2-cronicas-024.adoc#v14-24-0[&#60; Capítulo Anterior] | <<v14-25-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-026.adoc#v14-26-0[Próximo Capítulo &#62;]