include::./index.adoc[]

[[v14-30-0]]
=== 2 Crônicas, 30
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v14-30-1]]

^<<v14-30-1,1>>^ E Ezequias passou a enviar [mensageiros] a todo o Israel e Judá, e escreveu até mesmo cartas a Efraim e a Manassés para que viessem à casa de Jeová em Jerusalém, para celebrar a páscoa a Jeová, o Deus de Israel.

[[v14-30-2]]

^<<v14-30-2,2>>^ No entanto, o rei e seus príncipes, bem como toda a congregação em Jerusalém resolveram celebrar a páscoa no segundo mês;

[[v14-30-3]]

^<<v14-30-3,3>>^ pois não a puderam celebrar naquele tempo, porque, por um lado, não se haviam santificado sacerdotes suficientes, e por outro lado, o povo não se ajuntara a Jerusalém.

[[v14-30-4]]

^<<v14-30-4,4>>^ E a coisa era direita aos olhos do rei e aos olhos de toda a congregação.

[[v14-30-5]]

^<<v14-30-5,5>>^ Decidiram, pois, fazer uma proclamação^&#42;1^ por todo o Israel, de Berseba a Dã, para vir e celebrar a páscoa a Jeová, o Deus de Israel, em Jerusalém; porque não tinham feito assim como multidão segundo o que está escrito.

[NOTE]
====
. Lit.: “voz”. Hebr.: qohl; gr.: ké·ryg·ma, “proclamação; pregação”. Veja Mt 12:41 n.
====

[[v14-30-6]]

^<<v14-30-6,6>>^ Por conseguinte, os correios com as cartas da mão do rei e dos seus príncipes passaram por todo o Israel e Judá, sim, conforme o mandamento do rei, dizendo: “Filhos de Israel, voltai a Jeová, o Deus de Abraão, Isaque e Israel, para que ele retorne aos que escaparam, os que restam de vós, da palma da mão do rei da Assíria.

[[v14-30-7]]

^<<v14-30-7,7>>^ E não vos torneis iguais aos vossos antepassados e iguais aos vossos irmãos que agiram de modo infiel para com Jeová, o Deus de seus antepassados, de maneira que fez deles objeto de assombro, assim como estais vendo.

[[v14-30-8]]

^<<v14-30-8,8>>^ Agora, não endureçais a vossa cerviz, assim como fizeram os vossos antepassados. Dai lugar^&#42;1^ a Jeová e vinde ao seu santuário que ele santificou por tempo indefinido, e servi a Jeová, vosso Deus, para que a sua ira ardente recue de vós.

[NOTE]
====
. Lit.: “mão”.
====

[[v14-30-9]]

^<<v14-30-9,9>>^ Pois, se voltardes a Jeová, vossos irmãos e vossos filhos serão objetos de misericórdia diante dos que os mantêm cativos e terão permissão de voltar a esta terra; porque Jeová, vosso Deus, é clemente e misericordioso, e não desviará de vós a sua face se voltardes a ele.”

[[v14-30-10]]

^<<v14-30-10,10>>^ Assim, os correios foram passando de cidade em cidade através da terra de Efraim e de Manassés, até mesmo a Zebulão; estes, porém, continuavam a motejar e a caçoar deles.

[[v14-30-11]]

^<<v14-30-11,11>>^ Apenas pessoas de Aser, e de Manassés, e de Zebulão se humilharam a ponto de vir a Jerusalém.

[[v14-30-12]]

^<<v14-30-12,12>>^ A mão do [verdadeiro] Deus mostrou estar também em Judá para dar-lhes um só coração, a fim de que cumprissem o mandamento do rei e dos príncipes no assunto de Jeová.

[[v14-30-13]]

^<<v14-30-13,13>>^ E passaram a ajuntar-se em Jerusalém, um povo numeroso, para celebrar a festividade dos pães não fermentados no segundo mês, uma congregação muito numerosa.

[[v14-30-14]]

^<<v14-30-14,14>>^ Então se levantaram e removeram os altares que havia em Jerusalém, e removeram todos os altares do incenso e então [os] lançaram no vale da torrente do Cédron.

[[v14-30-15]]

^<<v14-30-15,15>>^ Depois abateram a vítima pascoal no décimo quarto [dia] do segundo mês; e os próprios sacerdotes e levitas tinham sido humilhados, de modo que se santificaram e trouxeram ofertas queimadas à casa de Jeová.

[[v14-30-16]]

^<<v14-30-16,16>>^ E ficaram de pé no seu lugar segundo a sua regra, conforme a lei de Moisés, o homem do [verdadeiro] Deus,^&#42;1^ os sacerdotes aspergindo o sangue recebido da mão dos levitas.

[NOTE]
====
. “O homem do [verdadeiro] Deus.” Hebr.: ’ish-ha·’Elo·hím.
====

[[v14-30-17]]

^<<v14-30-17,17>>^ Pois havia muitos na congregação que não se tinham santificado; e os levitas estavam encarregados do abate das vítimas pascoais para todos os que não estavam limpos, para santificá-los a Jeová.

[[v14-30-18]]

^<<v14-30-18,18>>^ Pois havia um grande número do povo, muitos de Efraim e de Manassés, de Issacar e de Zebulão, que não se tinham purificado, porque não comeram a páscoa segundo o que está escrito; mas Ezequias orou por tais, dizendo: “Que o bom Jeová faça ele mesmo uma concessão a

[[v14-30-19]]

^<<v14-30-19,19>>^ todo aquele que preparou seu coração para buscar o [verdadeiro] Deus, Jeová, o Deus de seus antepassados, embora sem a purificação para o que é santo.”

[[v14-30-20]]

^<<v14-30-20,20>>^ Concordemente, Jeová escutou a Ezequias e sarou o povo.

[[v14-30-21]]

^<<v14-30-21,21>>^ Assim, os filhos de Israel que se achavam em Jerusalém celebraram a festividade dos pães não fermentados por sete dias, com grande alegria; e os levitas e os sacerdotes davam louvor a Jeová, dia a dia, com instrumentos altissonantes, sim, a Jeová.

[[v14-30-22]]

^<<v14-30-22,22>>^ Ademais, Ezequias falou ao coração de todos os levitas que agiam com boa discrição para com Jeová. E passaram a comer o banquete designado, por sete dias, oferecendo sacrifícios de participação em comum e fazendo confissão a Jeová, o Deus de seus antepassados.

[[v14-30-23]]

^<<v14-30-23,23>>^ Toda a congregação decidiu então realizá-lo por mais sete dias, e assim o realizaram por [mais] sete dias com alegria.

[[v14-30-24]]

^<<v14-30-24,24>>^ Pois o próprio Ezequias, rei de Judá, contribuiu para a congregação mil novilhos e sete mil ovelhas, e os próprios príncipes contribuíram para a congregação mil novilhos e dez mil ovelhas; e os sacerdotes santificavam-se em grande número.

[[v14-30-25]]

^<<v14-30-25,25>>^ E toda a congregação de Judá, e os sacerdotes, e os levitas, e toda a congregação que chegara de Israel e os residentes forasteiros^&#42;1^ que chegaram da terra de Israel, bem como os que moravam em Judá, continuavam a alegrar-se.

[NOTE]
====
. Ou “e os residentes temporários”. Hebr.: wehag·ge·rím; LXXVg: “prosélitos”.
====

[[v14-30-26]]

^<<v14-30-26,26>>^ E veio a haver grande alegria em Jerusalém, pois desde os dias de Salomão, filho de Davi, rei de Israel, não houve nada igual a isso em Jerusalém.

[[v14-30-27]]

^<<v14-30-27,27>>^ Por fim se levantaram os sacerdotes, os levitas, e abençoaram o povo; e deu-se ouvido à sua voz, de modo que a sua oração chegou à santa habitação dele, os céus.

'''

xref:014-2-cronicas/014-2-cronicas-029.adoc#v14-29-0[&#60; Capítulo Anterior] | <<v14-30-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-031.adoc#v14-31-0[Próximo Capítulo &#62;]