include::./index.adoc[]

[[v14-32-0]]
=== 2 Crônicas, 32
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v14-32-1]]

^<<v14-32-1,1>>^ Depois destas coisas e deste proceder fiel, chegou Senaqueribe, rei da Assíria, e passou a invadir Judá e a acampar-se contra as cidades fortificadas, e ele pensava em fazê-las suas, penetrando à força.

[[v14-32-2]]

^<<v14-32-2,2>>^ Quando Ezequias viu que Senaqueribe veio com a sua face fixa na guerra contra Jerusalém,

[[v14-32-3]]

^<<v14-32-3,3>>^ então decidiu com os seus príncipes e seus poderosos tapar as águas das fontes que se achavam fora da cidade; e eles lhe ajudaram, portanto.

[[v14-32-4]]

^<<v14-32-4,4>>^ Por conseguinte, reuniu-se muito povo e eles foram tapar todos os mananciais e a torrente que fluía pelo meio da terra, dizendo: “Por que deviam os reis da Assíria chegar e realmente achar grande quantidade de água?”

[[v14-32-5]]

^<<v14-32-5,5>>^ Além disso, tomou coragem e reconstruiu toda a muralha decaída e ergueu sobre ela torres, e por fora [construiu] outra muralha, e consertou o Aterro^&#42;1^ da Cidade de Davi, e fez armas de arremesso em abundância, bem como escudos.

[NOTE]
====
. “O Aterro da.” Hebr.: ham·mil·lóh’.
====

[[v14-32-6]]

^<<v14-32-6,6>>^ E passou a colocar chefes militares sobre o povo e a reuni-los a si na praça pública do portão da cidade, e foi falar-lhes ao coração, dizendo:

[[v14-32-7]]

^<<v14-32-7,7>>^ “Sede corajosos e fortes. Não tenhais medo nem fiqueis aterrorizados por causa do rei da Assíria e por causa de toda a massa de gente com ele; pois conosco há mais do que os que estão com ele.

[[v14-32-8]]

^<<v14-32-8,8>>^ Com ele há um braço de carne, mas conosco está Jeová, nosso Deus, para nos ajudar e para travar as nossas batalhas.” E o povo começou a firmar-se nas palavras de Ezequias, o rei de Judá.

[[v14-32-9]]

^<<v14-32-9,9>>^ Foi depois disso que Senaqueribe, rei da Assíria, enviou seus servos a Jerusalém, enquanto estava em Laquís, ele e com ele todo o seu poderio imperial, a Ezequias, rei de Judá, e a todos os de Judá que estavam em Jerusalém, dizendo:

[[v14-32-10]]

^<<v14-32-10,10>>^ “Assim disse Senaqueribe, rei da Assíria: ‘Em que é que estais confiando, sentados quietos debaixo de sítio em Jerusalém?

[[v14-32-11]]

^<<v14-32-11,11>>^ Acaso não vos engoda Ezequias para vos entregar à morte pela fome e pela sede, dizendo: “O próprio Jeová, nosso Deus, nos livrará da palma da mão do rei da Assíria”?

[[v14-32-12]]

^<<v14-32-12,12>>^ Não foi o próprio Ezequias quem removeu seus altos e seus altares, dizendo então a Judá e a Jerusalém: “Diante de um só altar deveis curvar-vos e sobre ele deveis fazer fumaça sacrificial”?

[[v14-32-13]]

^<<v14-32-13,13>>^ Não sabeis o que eu mesmo e os meus antepassados fizemos a todos os povos das terras? Acaso mostraram-se os deuses das nações dos países realmente capazes de livrar a sua terra da minha mão?

[[v14-32-14]]

^<<v14-32-14,14>>^ Qual dentre todos os deuses destas nações que meus antepassados devotaram à destruição mostrou-se capaz de livrar seu povo da minha mão, de modo que o vosso Deus seja capaz de livrar-vos da minha mão?

[[v14-32-15]]

^<<v14-32-15,15>>^ E agora, não vos engane Ezequias nem vos engode ele assim, e não tenhais fé nele, porque nenhum deus^&#42;1^ de qualquer nação ou reino foi capaz de livrar seu povo da minha mão e da mão de meus antepassados. Quanto menos, então, vos livrará^&#42;2^ o vosso próprio Deus da minha mão!’”

[NOTE]
====
. Lit.: “nem sequer um deus”. Hebr.: lo’ . . . kol-’elóh·ah, sing. de ’elo·hím.
. “Livrará”, pl. no hebr., para concordar com o sujeito ’Elo·heh·khém, “vosso próprio Deus”, que é pl. no hebr. para denotar majestade e poderes divinos. Em LXXVg, este verbo está no sing.; assim também no M, v. 17b.
====

[[v14-32-16]]

^<<v14-32-16,16>>^ E seus servos falaram ainda mais contra Jeová, o [verdadeiro] Deus, e contra Ezequias, seu servo.

[[v14-32-17]]

^<<v14-32-17,17>>^ Escreveu até mesmo cartas para vituperar a Jeová, o Deus de Israel, e para falar contra ele, dizendo: “Igual aos deuses das nações dos países que não livraram seu povo da minha mão, assim o Deus de Ezequias não livrará seu povo da minha mão.”

[[v14-32-18]]

^<<v14-32-18,18>>^ E clamavam com alta voz no idioma judaico ao povo de Jerusalém que estava sobre a muralha para amedrontá-los e perturbá-los, a fim de que pudessem capturar a cidade.

[[v14-32-19]]

^<<v14-32-19,19>>^ E prosseguiram falando contra o Deus de Jerusalém assim como contra os deuses dos povos da terra, trabalho das mãos do homem.

[[v14-32-20]]

^<<v14-32-20,20>>^ Mas Ezequias, o rei, e Isaías,^&#42;1^ filho de Amoz, o profeta, oravam referente a isso e clamavam aos céus por socorro.

[NOTE]
====
. “E Isaías.” Hebr.: wI·sha·‛eyá·hu, significando “Salvação de Jeová”; LXX: “Esaias”; Vgc: “Isaías”.
====

[[v14-32-21]]

^<<v14-32-21,21>>^ E Jeová passou a enviar um anjo e a eliminar todo homem poderoso, valente, e todo líder e chefe no acampamento do rei da Assíria, de modo que ele retornou com face envergonhada à sua própria terra. Mais tarde entrou na casa de seu deus^&#42;1^ e ali se lançaram sobre ele com a espada certos [homens] que tinham saído das suas próprias entranhas.

[NOTE]
====
. “Seu deus.” Hebr.: ’elo·háv, pl. de ’elóh·ah, aplicado ao falso deus de Senaqueribe para denotar majestade; gr.: the·oú; lat.: dé·i.
====

[[v14-32-22]]

^<<v14-32-22,22>>^ Assim salvou Jeová a Ezequias e os habitantes de Jerusalém da mão de Senaqueribe, rei da Assíria, e da mão de todos os outros e deu-lhes descanso em todo o redor.

[[v14-32-23]]

^<<v14-32-23,23>>^ E havia muitos que traziam presentes a Jeová a Jerusalém e coisas seletas a Ezequias, rei de Judá, e depois disso ele ficou elevado aos olhos de todas as nações.

[[v14-32-24]]

^<<v14-32-24,24>>^ Naqueles dias Ezequias ficou doente até à morte, e ele começou a orar a Jeová. Portanto, Ele lhe falou e lhe deu um portento.

[[v14-32-25]]

^<<v14-32-25,25>>^ Mas Ezequias nada retribuiu de acordo com o benefício que se lhe concedeu, porque o seu coração se ensoberbeceu e veio a haver indignação contra ele e contra Judá e Jerusalém.

[[v14-32-26]]

^<<v14-32-26,26>>^ Todavia, Ezequias humilhou-se pela soberba do seu coração, ele e os habitantes de Jerusalém, e a indignação de Jeová não veio sobre eles nos dias de Ezequias.

[[v14-32-27]]

^<<v14-32-27,27>>^ E Ezequias veio a ter riquezas e glória em abundância muito grande; e fez para si depósitos para a prata, e para o ouro, e para as pedras preciosas, e para o óleo de bálsamo, e para os escudos, e para todos os objetos desejáveis;

[[v14-32-28]]

^<<v14-32-28,28>>^ e também armazéns para a safra de cereais, e de vinho novo, e de azeite, e também baias para todos os diversos tipos de animais e abrigos para as greis.

[[v14-32-29]]

^<<v14-32-29,29>>^ E adquiriu para si cidades e também gado do rebanho e da manada em abundância, porque Deus lhe deu muitíssimos bens.

[[v14-32-30]]

^<<v14-32-30,30>>^ E foi Ezequias quem tapou a nascente superior das águas de Giom e canalizou-as diretamente para baixo, para o oeste da Cidade de Davi, e Ezequias continuou a mostrar-se bem sucedido em todo o seu trabalho.

[[v14-32-31]]

^<<v14-32-31,31>>^ E assim foi que, por meio dos porta-vozes dos príncipes de Babilônia,^&#42;1^ que lhe foram enviados para consultá-lo a respeito do portento que ocorrera no país, o [verdadeiro] Deus o abandonou, para que fosse posto à prova, a fim de saber tudo [o que havia] no seu coração.

[NOTE]
====
. “Babilônia”, LXXVg; M: “Babel”.
====

[[v14-32-32]]

^<<v14-32-32,32>>^ Quanto ao resto dos assuntos de Ezequias e dos seus atos de benevolência,^&#42;1^ eis que estão escritos na visão de Isaías,^&#42;2^ o profeta, filho de Amoz, no Livro dos Reis de Judá e de Israel.

[NOTE]
====
. Ou “amor leal”.
. “Isaías.” Hebr.: Yesha·‛eyá·hu.
====

[[v14-32-33]]

^<<v14-32-33,33>>^ Por fim, Ezequias deitou-se com os seus antepassados e enterraram-no na subida às sepulturas dos filhos de Davi; e na sua morte, todo o Judá e os habitantes de Jerusalém deram-lhe honra. E Manassés, seu filho, começou a reinar em seu lugar.

'''

xref:014-2-cronicas/014-2-cronicas-031.adoc#v14-31-0[&#60; Capítulo Anterior] | <<v14-32-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-033.adoc#v14-33-0[Próximo Capítulo &#62;]