include::./index.adoc[]

[[v14-20-0]]
=== 2 Crônicas, 20
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v14-20-1]]

^<<v14-20-1,1>>^ E depois sucedeu que os filhos de Moabe e os filhos de Amom, e com eles alguns dos amonins^&#42;1^ vieram contra Jeosafá em guerra.

[NOTE]
====
. Lit.: “dentre os amonins”. Hebr.: me·ha·‛Am·moh·ním; mediante uma transposição de letras no M; “dos meunins; meunitas”; LXX: “dos minaianos”; Vgc: “dos amonitas”.
====

[[v14-20-2]]

^<<v14-20-2,2>>^ Vieram então pessoas e informaram Jeosafá, dizendo: “Veio contra ti uma grande massa de gente da região do mar,^&#42;1^ de Edom;^&#42;2^ e eis que estão em Hazazom-Tamar, isto é, En-Gedi.”

[NOTE]
====
. Isto é, o Mar Morto.
. “De Edom”, um ms. hebr.; hebr.: me·’Arám, “da Síria”; gr.: Sy·rí·as; lat.: Sý·ri·a; Sy: “do Mar Vermelho”.
====

[[v14-20-3]]

^<<v14-20-3,3>>^ Então Jeosafá ficou com medo e pôs a sua face a buscar a Jeová. Proclamou, pois, um jejum para todo o Judá.

[[v14-20-4]]

^<<v14-20-4,4>>^ Finalmente se reuniram os de Judá para consultar a Jeová. Mesmo de todas as cidades de Judá vieram consultar a Jeová.

[[v14-20-5]]

^<<v14-20-5,5>>^ Jeosafá pôs-se então de pé na congregação^&#42;1^ de Judá e de Jerusalém, na casa de Jeová, diante do pátio novo,

[NOTE]
====
. “Na congregação de.” Hebr.: biq·hál; gr.: ek·kle·sí·ai.
====

[[v14-20-6]]

^<<v14-20-6,6>>^ e passou a dizer:
“Ó Jeová, Deus de nossos antepassados, acaso não és Deus nos céus e não dominas sobre todos os reinos das nações, e não há na tua mão poder e potência, não havendo quem se mantenha firme contra ti?

[[v14-20-7]]

^<<v14-20-7,7>>^ Não foste tu, ó Deus nosso, quem desalojaste os habitantes desta terra de diante do teu povo Israel e então a deste à descendência de Abraão, aquele que te amou,^&#42;1^ por tempo indefinido?

[NOTE]
====
. Ou “teu amigo”. Lat.: a·mí·ci.
====

[[v14-20-8]]

^<<v14-20-8,8>>^ E passaram a morar nela e passaram a construir-te nela um santuário ao teu nome, dizendo:

[[v14-20-9]]

^<<v14-20-9,9>>^ ‘Se vier sobre nós calamidade, espada, julgamento adverso, ou pestilência ou fome, fiquemos de pé diante desta casa e diante de ti (pois o teu nome está nesta casa) para clamar a ti por socorro na nossa aflição, e que tu ouças e salves.’

[[v14-20-10]]

^<<v14-20-10,10>>^ E agora, eis os filhos de Amom e de Moabe, e [os] da região montanhosa de Seir, que não deixaste Israel invadir quando saíam da terra do Egito, mas se desviaram deles e não os aniquilaram,

[[v14-20-11]]

^<<v14-20-11,11>>^ sim, eis que nos recompensam por chegarem para nos expulsar da nossa posse que nos fizeste possuir.

[[v14-20-12]]

^<<v14-20-12,12>>^ Ó nosso Deus, não executarás neles o julgamento? Porque não há em nós poder diante desta grande massa de gente que vem contra nós; e nós mesmos não sabemos o que devemos fazer, mas os nossos olhos se fixam em ti.”

[[v14-20-13]]

^<<v14-20-13,13>>^ No ínterim, todos os de Judá estavam de pé diante de Jeová, mesmo os seus pequeninos, suas esposas e seus filhos.

[[v14-20-14]]

^<<v14-20-14,14>>^ Ora, quanto a Jaaziel, filho de Zacarias, filho de Benaia, filho de Jeiel, filho de Matanias, levita dos filhos de Asafe, veio sobre ele o espírito de Jeová no meio da congregação.

[[v14-20-15]]

^<<v14-20-15,15>>^ Portanto ele disse: “Prestai atenção, todo o Judá e vós habitantes de Jerusalém, e Rei Jeosafá! Assim vos disse Jeová: ‘Não tenhais medo nem fiqueis aterrorizados por causa desta grande massa de gente; pois a batalha não é vossa, mas de Deus.

[[v14-20-16]]

^<<v14-20-16,16>>^ Descei amanhã contra eles. Eis que estão subindo pelo passo de Ziz; e certamente os encontrareis no fim do vale da torrente, defronte do ermo de Jeruel.

[[v14-20-17]]

^<<v14-20-17,17>>^ Não tereis de lutar neste caso. Tomai a vossa posição, ficai parados e vede a salvação da parte de Jeová a vosso favor. Ó Judá e Jerusalém, não tenhais medo nem fiqueis aterrorizados. Saí amanhã contra^&#42;1^ eles e Jeová será convosco.’”

[NOTE]
====
. Ou “diante”. Veja Gên 10:9 n.: “em oposição a”.
====

[[v14-20-18]]

^<<v14-20-18,18>>^ Jeosafá inclinou-se imediatamente com o rosto por terra, e todo o Judá e os próprios habitantes de Jerusalém lançaram-se de bruços diante de Jeová para prestar homenagem a Jeová.

[[v14-20-19]]

^<<v14-20-19,19>>^ Então se levantaram os levitas dos filhos dos coatitas e dos filhos dos coraítas para louvar a Jeová, o Deus de Israel, com voz extraordinariamente alta.

[[v14-20-20]]

^<<v14-20-20,20>>^ E passaram a levantar-se de manhã cedo e a sair ao ermo de Tecoa. E ao saírem, Jeosafá pôs-se de pé e então disse: “Ouvi-me, ó Judá e vós habitantes de Jerusalém! Tende fé em Jeová, vosso Deus, para que mostreis ser de longa duração. Tende fé nos seus profetas e mostrai-vos assim bem sucedidos.”

[[v14-20-21]]

^<<v14-20-21,21>>^ Ademais, aconselhou-se com o povo e colocou em posição cantores para Jeová e os que ofereciam louvor em santo adorno, os quais saíam na frente dos homens armados e diziam: “Louvai a Jeová, pois a sua benevolência^&#42;1^ é por tempo indefinido.”

[NOTE]
====
. Ou “amor leal”.
====

[[v14-20-22]]

^<<v14-20-22,22>>^ No tempo em que principiaram a clamar alegremente e a dar louvor, Jeová colocou homens de emboscada contra os filhos de Amom, de Moabe e da região montanhosa de Seir, que estavam entrando em Judá, e eles se feriram mutuamente.

[[v14-20-23]]

^<<v14-20-23,23>>^ E os filhos de Amom e de Moabe puseram-se de pé contra os habitantes da região montanhosa de Seir para devotá-los à destruição e para aniquilá-los; e assim que acabaram com os habitantes de Seir, ajudaram a arruinar cada um ao seu próprio próximo.

[[v14-20-24]]

^<<v14-20-24,24>>^ Quanto a Judá, porém, chegou à torre de vigia do ermo. Quando viraram as faces para a massa de gente, ora, eis que ali estavam, seus cadáveres caídos por terra sem que alguém tivesse escapado.

[[v14-20-25]]

^<<v14-20-25,25>>^ De modo que Jeosafá e seu povo vieram para saquear deles o despojo, e foram achar entre eles uma abundância de bens, e de roupas,^&#42;1^ e de objetos desejáveis; e foram tirá-los para si até que não podiam carregar mais. E veio a ser três dias que saquearam o despojo, porque era abundante.

[NOTE]
====
. “Roupas”, Vg e sete mss. hebr.; M: “cadáveres”.
====

[[v14-20-26]]

^<<v14-20-26,26>>^ E no quarto dia congregaram-se na baixada de Beraca, pois ali bendisseram a Jeová. É por isso que chamaram aquele lugar pelo nome de Baixada de Beraca^&#42;1^ — até o dia de hoje.

[NOTE]
====
. Significando “Bênção”.
====

[[v14-20-27]]

^<<v14-20-27,27>>^ Então retornaram todos os homens de Judá e de Jerusalém, com Jeosafá à sua cabeça, voltando a Jerusalém com alegria, pois Jeová os fizera alegrar-se sobre os seus inimigos.

[[v14-20-28]]

^<<v14-20-28,28>>^ Chegaram assim a Jerusalém com instrumentos de cordas, e com harpas, e com trombetas à casa de Jeová.

[[v14-20-29]]

^<<v14-20-29,29>>^ E o pavor de Deus veio a estar sobre todos os reinos dos países quando ouviram que Jeová lutara contra os inimigos de Israel.

[[v14-20-30]]

^<<v14-20-30,30>>^ Assim o domínio real de Jeosafá teve sossego e seu Deus continuou a dar-lhe descanso em todo o redor.

[[v14-20-31]]

^<<v14-20-31,31>>^ E Jeosafá continuou reinando sobre Judá. Tinha trinta e cinco anos de idade quando começou a reinar e reinou por vinte e cinco anos em Jerusalém. E o nome de sua mãe era Azuba, filha de Sili.

[[v14-20-32]]

^<<v14-20-32,32>>^ E ele andava no caminho de seu pai Asa e não se desviou dele, fazendo o que era direito aos olhos de Jeová.

[[v14-20-33]]

^<<v14-20-33,33>>^ Apenas os altos é que não desapareceram; e o próprio povo não preparara ainda seu coração para o Deus de seus antepassados.

[[v14-20-34]]

^<<v14-20-34,34>>^ Quanto ao resto dos assuntos de Jeosafá, os primeiros e os últimos, eis que estão escritos entre as palavras de Jeú, filho de Hanani, que foram incluídas no Livro dos Reis de Israel.

[[v14-20-35]]

^<<v14-20-35,35>>^ E depois, Jeosafá, rei de Judá, fez sociedade com Acazias, rei de Israel, o qual agiu de modo iníquo.

[[v14-20-36]]

^<<v14-20-36,36>>^ Assim, fez dele seu sócio para fazerem navios, para que fossem a Társis, e fizeram navios em Eziom-Géber.

[[v14-20-37]]

^<<v14-20-37,37>>^ No entanto, Eliézer, filho de Dodavaú, de Maressa, falou profeticamente contra Jeosafá, dizendo: “Visto que te associaste a Acazias, Jeová certamente derrocará os teus trabalhos.” Por conseguinte, os navios sofreram naufrágio e não retiveram força para ir a Társis.

'''

xref:014-2-cronicas/014-2-cronicas-019.adoc#v14-19-0[&#60; Capítulo Anterior] | <<v14-20-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-021.adoc#v14-21-0[Próximo Capítulo &#62;]