include::./index.adoc[]

[[v2-10-0]]
=== Êxodo, 10
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v2-10-1]]

^<<v2-10-1,1>>^ Jeová disse então a Moisés: “Entra até Faraó, porque eu é que deixei seu coração e o coração de seus servos ficar insensível, para pôr estes meus sinais diretamente na frente dele,^&#42;1^

[NOTE]
====
. “Estes (meus) sinais entre eles”, TJSy; LXX: “estes sinais sobre eles”.
====

[[v2-10-2]]

^<<v2-10-2,2>>^ e para que declares aos ouvidos de teu filho e do filho de teu filho^&#42;1^ quão severamente lidei com o Egito e meus sinais que estabeleci entre eles; e sabereis certamente que eu sou Jeová.”

[NOTE]
====
. Ou “e do teu neto”.
====

[[v2-10-3]]

^<<v2-10-3,3>>^ Portanto, Moisés e Arão entraram até Faraó e disseram-lhe: “Assim disse Jeová, o Deus dos hebreus: ‘Até quando te negarás a te submeter a mim? Manda embora meu povo, para que me sirvam.

[[v2-10-4]]

^<<v2-10-4,4>>^ Pois, se continuares a negar-te a mandar meu povo embora, eis que trarei amanhã gafanhotos para dentro dos teus termos.

[[v2-10-5]]

^<<v2-10-5,5>>^ E eles cobrirão literalmente a superfície visível^&#42;1^ da terra e não será possível ver a terra; e eles simplesmente devorarão o resto do que escapou, o que vos foi deixado pela saraiva, e certamente comerão do campo toda árvore vossa que brota.

[NOTE]
====
. Lit.: “o olho”.
====

[[v2-10-6]]

^<<v2-10-6,6>>^ E tuas casas e as casas de todos os teus servos, e as casas de todo o Egito, encher-se-ão a tal ponto como nunca o viram teus pais nem os pais de teus pais,^&#42;1^ desde o dia em que existiram sobre o solo até o dia de hoje.’” Com isso se virou e saiu de diante de Faraó.

[NOTE]
====
. Ou “teus avós”.
====

[[v2-10-7]]

^<<v2-10-7,7>>^ Os servos de Faraó disseram-lhe depois: “Até quando se mostrará este homem um laço para nós? Manda os homens embora, para que sirvam a Jeová, seu Deus. Não sabes ainda que o Egito pereceu?”

[[v2-10-8]]

^<<v2-10-8,8>>^ Moisés e Arão foram assim levados de volta a Faraó, e ele lhes disse: “Ide, servi a Jeová, vosso Deus. Especificamente,^&#42;1^ quem é que vai?”

[NOTE]
====
. Lit.: “Quem e quem?”
====

[[v2-10-9]]

^<<v2-10-9,9>>^ Moisés disse então: “Iremos com os nossos moços e com os nossos velhos. Iremos com os nossos filhos e com as nossas filhas, com as nossas ovelhas e com o nosso gado vacum, pois temos uma festividade para com Jeová.”

[[v2-10-10]]

^<<v2-10-10,10>>^ Ele, por sua vez, disse-lhes: “Venha a ser assim, que Jeová esteja convosco quando eu mandar embora a vós e os vossos pequeninos! Vede! Ao contrário, tendes más intenções.^&#42;1^

[NOTE]
====
. Lit.: “algo de mau está diante das vossas faces”.
====

[[v2-10-11]]

^<<v2-10-11,11>>^ Assim não! Por favor, ide vós que sois varões vigorosos e servi a Jeová, porque é isso que procurais alcançar.” Com isso foram expulsos de diante de Faraó.

[[v2-10-12]]

^<<v2-10-12,12>>^ Jeová disse então a Moisés: “Estende tua mão sobre a terra do Egito, para [haver] gafanhotos, para que venham sobre a terra do Egito e devorem toda a vegetação do país, tudo o que a saraiva deixou sobrar.”

[[v2-10-13]]

^<<v2-10-13,13>>^ Moisés estendeu imediatamente seu bastão sobre a terra do Egito e Jeová fez soprar um vento^&#42;1^ oriental sobre o país por todo aquele dia e toda aquela noite. Veio a manhã, e o vento oriental trouxe os gafanhotos.

[NOTE]
====
. “Vento.” Hebr.: rú·ahh; gr.: á·ne·mon; lat.: vén·tum. Veja Gên 1:2 n.: “ativa”.
====

[[v2-10-14]]

^<<v2-10-14,14>>^ E os gafanhotos começaram a vir sobre toda a terra do Egito e a pousar sobre todo o território do Egito. Foram muito molestos. Antes deles nunca houve deste modo gafanhotos semelhantes a eles e nunca os haverá deste modo após eles.

[[v2-10-15]]

^<<v2-10-15,15>>^ E cobriam a superfície visível do país inteiro, e a terra ficou escura; e devoravam toda a vegetação do país e todos os frutos das árvores que a saraiva deixara sobrar; e não ficou nada verde nas árvores nem na vegetação do campo, em toda a terra do Egito.

[[v2-10-16]]

^<<v2-10-16,16>>^ Portanto, Faraó chamou apressadamente Moisés e Arão e disse: “Pequei contra Jeová, vosso Deus, e contra vós.

[[v2-10-17]]

^<<v2-10-17,17>>^ E agora, por favor, perdoai só esta vez o meu pecado e suplicai a Jeová, vosso Deus, para que somente afaste de mim esta praga mortífera.”^&#42;1^

[NOTE]
====
. Lit.: “esta morte”.
====

[[v2-10-18]]

^<<v2-10-18,18>>^ De modo que saiu de diante de Faraó e fez súplica a Jeová.

[[v2-10-19]]

^<<v2-10-19,19>>^ Jeová causou então uma mudança para um forte vento ocidental, e este levou os gafanhotos embora e os lançou no Mar Vermelho.^&#42;1^ Não se deixou sobrar nem um único gafanhoto em todo o território do Egito.

[NOTE]
====
. Lit.: “mar de ervas daninhas; mar de juncos”.
====

[[v2-10-20]]

^<<v2-10-20,20>>^ No entanto, Jeová deixou o coração de Faraó ficar obstinado, e ele não mandou embora os filhos de Israel.

[[v2-10-21]]

^<<v2-10-21,21>>^ Jeová disse então a Moisés: “Estende tua mão para os céus, para que haja escuridão sobre a terra do Egito e se possa apalpar a escuridão.”

[[v2-10-22]]

^<<v2-10-22,22>>^ Moisés estendeu imediatamente a mão para os céus e começou a haver uma escuridão sombria em toda a terra do Egito, por três dias.

[[v2-10-23]]

^<<v2-10-23,23>>^ Não se viam uns aos outros e nenhum deles se levantou do seu lugar por três dias; mas para todos os filhos de Israel mostrou-se haver luz nas suas moradas.

[[v2-10-24]]

^<<v2-10-24,24>>^ Depois, Faraó chamou Moisés e disse: “Ide, servi a Jeová. Somente as vossas ovelhas e o vosso gado vacum ficarão detidos. Também os vossos pequeninos poderão ir convosco.”

[[v2-10-25]]

^<<v2-10-25,25>>^ Moisés disse, porém: “Tu mesmo também entregarás às nossas mãos sacrifícios e ofertas queimadas, visto que temos de ofertá-los a Jeová, nosso Deus.

[[v2-10-26]]

^<<v2-10-26,26>>^ E nosso gado irá também conosco. Nem um único casco se deixará remanescer, porque é deles que tomaremos alguns para adorar^&#42;1^ a Jeová, nosso Deus, e nós mesmos não sabemos o que havemos de oferecer em adoração a Jeová até chegarmos lá.”

[NOTE]
====
. “Para adorar (servir).” Hebr.: la‛avódh; gr.: la·treú·sai, “para prestar serviço sagrado”. Veja 3:12 n.
====

[[v2-10-27]]

^<<v2-10-27,27>>^ Nisso Jeová deixou o coração de Faraó ficar obstinado, e ele não consentiu em mandá-los embora.

[[v2-10-28]]

^<<v2-10-28,28>>^ De modo que Faraó lhe disse: “Sai da minha frente! Guarda-te! Não tentes ver novamente a minha face, porque no dia em que vires a minha face morrerás.”

[[v2-10-29]]

^<<v2-10-29,29>>^ A isso Moisés disse: “É assim que falaste. Não tentarei mais ver a tua face.”

'''

xref:002-exodo/002-exodo-009.adoc#v2-9-0[&#60; Capítulo Anterior] | <<v2-10-0,Topo>> | xref:002-exodo/002-exodo-011.adoc#v2-11-0[Próximo Capítulo &#62;]