include::./index.adoc[]

[[v2-36-0]]
=== Êxodo, 36
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v2-36-1]]

^<<v2-36-1,1>>^ “E Bezalel terá de trabalhar, também Ooliabe e todo homem de coração sábio a quem Jeová tiver dado sabedoria e entendimento destas coisas para saber fazer toda a obra do serviço sagrado segundo tudo o que Jeová mandou.”

[[v2-36-2]]

^<<v2-36-2,2>>^ E Moisés passou a chamar Bezalel e Ooliabe, e todo homem de coração sábio, em cujo coração Jeová pusera sabedoria, todo aquele cujo coração o impelia a se chegar à obra, a fim de fazê-la.

[[v2-36-3]]

^<<v2-36-3,3>>^ Tomaram então de diante de Moisés toda a contribuição que os filhos de Israel haviam trazido para a obra do serviço sagrado, a fim de fazê-la, e quanto a ele, trouxeram-lhe ainda uma oferta voluntária, manhã após manhã.

[[v2-36-4]]

^<<v2-36-4,4>>^ E começaram a vir todos os sábios que faziam toda a obra sagrada, um após outro, da sua obra que estavam fazendo,

[[v2-36-5]]

^<<v2-36-5,5>>^ e disseram a Moisés: “O povo está trazendo muito mais do que o serviço requer para a obra que Jeová mandou fazer.”

[[v2-36-6]]

^<<v2-36-6,6>>^ De modo que Moisés mandou que fizessem um anúncio através do acampamento, dizendo: “Homens e mulheres, não produzais mais material para a santa contribuição.” Com isso se conteve o povo de trazê-la.

[[v2-36-7]]

^<<v2-36-7,7>>^ E o material mostrou-se suficiente para toda a obra a ser feita, e mais do que suficiente.

[[v2-36-8]]

^<<v2-36-8,8>>^ E todos os de coração sábio entre os que faziam a obra foram fazer o tabernáculo, os dez panos de tenda de linho fino retorcido, e de linha azul, e de lã tingida de roxo, e de fibras carmíneas; com querubins, trabalho de bordador, os fez.^&#42;1^

[NOTE]
====
. “Fez”, evidentemente se referindo a Bezalel.
====

[[v2-36-9]]

^<<v2-36-9,9>>^ O comprimento de cada pano de tenda era de vinte e oito côvados, e a largura de cada pano de tenda, quatro côvados. Havia uma só medida para todos os panos de tenda.

[[v2-36-10]]

^<<v2-36-10,10>>^ Depois uniu cinco panos de tenda, um ao outro, e uniu os outros cinco panos de tenda, um ao outro.

[[v2-36-11]]

^<<v2-36-11,11>>^ Depois fez presilhas de linha azul na beira de um pano de tenda na extremidade da junção. Fez o mesmo na beira do mais extremo pano de tenda no outro ponto de junção.

[[v2-36-12]]

^<<v2-36-12,12>>^ Fez cinqüenta presilhas num pano de tenda e fez cinqüenta presilhas na extremidade do pano de tenda que estava no outro ponto de junção, as presilhas estando contrapostas umas às outras.

[[v2-36-13]]

^<<v2-36-13,13>>^ Por fim fez cinqüenta colchetes de ouro e uniu os panos de tenda um ao outro por meio dos colchetes, de modo que se tornou um só tabernáculo.

[[v2-36-14]]

^<<v2-36-14,14>>^ E ele foi fazer panos de tenda de pêlos de cabra para a tenda sobre o tabernáculo. Onze panos de tenda foram os que ele fez.

[[v2-36-15]]

^<<v2-36-15,15>>^ O comprimento de cada pano de tenda era de trinta côvados e a largura de cada pano de tenda, quatro côvados. Havia uma só medida para os onze panos de tenda.

[[v2-36-16]]

^<<v2-36-16,16>>^ Então uniu cinco panos de tenda entre si e os outros seis panos de tenda entre si.

[[v2-36-17]]

^<<v2-36-17,17>>^ A seguir fez cinqüenta presilhas na beira do mais extremo pano de tenda, no ponto de junção, e fez cinqüenta presilhas na beira do outro pano de tenda que se unia a ele.

[[v2-36-18]]

^<<v2-36-18,18>>^ Depois fez cinqüenta colchetes de cobre para unir a tenda, para se tornar uma só peça.

[[v2-36-19]]

^<<v2-36-19,19>>^ E passou a fazer uma cobertura para a tenda, de peles de carneiros tingidas de vermelho e uma cobertura de peles de focas por cima.

[[v2-36-20]]

^<<v2-36-20,20>>^ Então fez as armações de painel para o tabernáculo, de madeira de acácia, postas em pé.

[[v2-36-21]]

^<<v2-36-21,21>>^ Dez côvados era o comprimento de uma armação de painel e um côvado e meio a largura de cada armação de painel.

[[v2-36-22]]

^<<v2-36-22,22>>^ Cada armação de painel tinha duas espigas ligadas uma à outra. Assim fez todas as armações de painel do tabernáculo.

[[v2-36-23]]

^<<v2-36-23,23>>^ De modo que ele fez as armações de painel para o tabernáculo, vinte armações de painel para o lado do Negebe, o meridional.

[[v2-36-24]]

^<<v2-36-24,24>>^ E fez quarenta pedestais de encaixe de prata, para [ficarem] debaixo das vinte armações de painel, dois pedestais de encaixe debaixo de uma armação de painel com as suas duas espigas e dois pedestais de encaixe debaixo da outra armação de painel com as suas duas espigas.

[[v2-36-25]]

^<<v2-36-25,25>>^ E para o outro lado do tabernáculo, o lado setentrional, fez vinte armações de painel

[[v2-36-26]]

^<<v2-36-26,26>>^ e seus quarenta pedestais de encaixe de prata, dois pedestais de encaixe debaixo de uma armação de painel e dois pedestais de encaixe debaixo da outra armação de painel.

[[v2-36-27]]

^<<v2-36-27,27>>^ E para os fundos do tabernáculo, ao oeste,^&#42;1^ fez seis armações de painel.

[NOTE]
====
. Lit.: “mar”, isto é, o Mediterrâneo.
====

[[v2-36-28]]

^<<v2-36-28,28>>^ E fez duas armações de painel como escoras de esquina do tabernáculo, nas suas duas partes dos fundos.

[[v2-36-29]]

^<<v2-36-29,29>>^ E elas se mostraram duplicadas na parte de baixo e juntas vieram a ser gêmeas até o topo de cada uma, na primeira argola. Assim fez com ambas, com as duas escoras de esquina.

[[v2-36-30]]

^<<v2-36-30,30>>^ Somaram assim oito armações de painel, e seus pedestais de encaixe de prata, dezesseis, dois pedestais de encaixe junto a dois pedestais de encaixe debaixo de cada armação de painel.

[[v2-36-31]]

^<<v2-36-31,31>>^ E ele foi fazer trancas de madeira de acácia, cinco para as armações de painel de um lado do tabernáculo

[[v2-36-32]]

^<<v2-36-32,32>>^ e cinco trancas para as armações de painel do outro lado do tabernáculo, e cinco trancas para as armações de painel do tabernáculo para as duas partes dos fundos, ao oeste.

[[v2-36-33]]

^<<v2-36-33,33>>^ Fez então a tranca do meio passar ao meio das armações de painel de uma extremidade à outra.

[[v2-36-34]]

^<<v2-36-34,34>>^ E recobriu de ouro as armações de painel e fez de ouro suas argolas como suportes para as trancas, e foi recobrir de ouro as trancas.

[[v2-36-35]]

^<<v2-36-35,35>>^ E passou a fazer uma cortina de linha azul, e de lã tingida de roxo, e de fibras carmíneas, e de linho fino retorcido. Ele a fez trabalho de bordador, com querubins.

[[v2-36-36]]

^<<v2-36-36,36>>^ Depois fez para ela quatro colunas de acácia e as recobriu de ouro, seus pinos sendo de ouro, e fundiu para elas quatro pedestais de encaixe de prata.

[[v2-36-37]]

^<<v2-36-37,37>>^ E para a entrada da tenda foi fazer um reposteiro de linha azul, e de lã tingida de roxo, e de fibras carmíneas, e de linho fino retorcido, trabalho de tecelão,

[[v2-36-38]]

^<<v2-36-38,38>>^ e suas cinco colunas e seus pinos. E recobriu de ouro seus topos e suas ligações, mas os seus cinco pedestais de encaixe eram de cobre.

'''

xref:002-exodo/002-exodo-035.adoc#v2-35-0[&#60; Capítulo Anterior] | <<v2-36-0,Topo>> | xref:002-exodo/002-exodo-037.adoc#v2-37-0[Próximo Capítulo &#62;]