include::./index.adoc[]

[[v2-35-0]]
=== Êxodo, 35
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v2-35-1]]

^<<v2-35-1,1>>^ Mais tarde, Moisés congregou a assembléia inteira dos filhos de Israel e disse-lhes: “Estas são as palavras^&#42;1^ que Jeová ordenou que se cumprissem:

[NOTE]
====
. Ou “coisas”.
====

[[v2-35-2]]

^<<v2-35-2,2>>^ Seis dias se pode fazer alguma obra, mas no sétimo dia virá a ser algo santo para vós, um sábado de completo repouso para Jeová. Todo aquele que nele fizer alguma obra será morto.

[[v2-35-3]]

^<<v2-35-3,3>>^ Não deveis acender fogo em nenhum dos vossos lugares de morada no dia de sábado.”

[[v2-35-4]]

^<<v2-35-4,4>>^ E Moisés prosseguiu, dizendo à assembléia inteira dos filhos de Israel: “Esta é a palavra que Jeová ordenou, dizendo:

[[v2-35-5]]

^<<v2-35-5,5>>^ ‘Recolhei dentre vós uma contribuição para Jeová. Cada um de coração disposto a traga como contribuição [pertencente a] Jeová, a saber, ouro e prata, e cobre,

[[v2-35-6]]

^<<v2-35-6,6>>^ e linha azul, e lã tingida de roxo, e fibras carmíneas, e linho fino, e pêlos de cabra,

[[v2-35-7]]

^<<v2-35-7,7>>^ e peles de carneiros tingidas de vermelho, e peles de focas, e madeira de acácia,

[[v2-35-8]]

^<<v2-35-8,8>>^ e óleo para o luzeiro, e óleo de bálsamo para o óleo de unção e para o incenso perfumado,

[[v2-35-9]]

^<<v2-35-9,9>>^ e pedras de ônix e pedras de engaste para o éfode e para o peitoral.

[[v2-35-10]]

^<<v2-35-10,10>>^ “‘E venham todos os de coração sábio dentre vós e façam tudo o que Jeová mandou,

[[v2-35-11]]

^<<v2-35-11,11>>^ a saber, o tabernáculo com a sua tenda e sua cobertura, seus colchetes e suas armações de painel,^&#42;1^ suas trancas, suas colunas e seus pedestais de encaixe;

[NOTE]
====
. Veja 26:15 n.
====

[[v2-35-12]]

^<<v2-35-12,12>>^ a Arca e seus varais, a tampa e a cortina do reposteiro;

[[v2-35-13]]

^<<v2-35-13,13>>^ e a mesa e seus varais, e todos os seus utensílios e os pães da proposição;^&#42;1^

[NOTE]
====
. Ou “pão da Presença”. Vg: “pães da apresentação”. Veja 25:30.
====

[[v2-35-14]]

^<<v2-35-14,14>>^ e o candelabro de iluminação e seus utensílios, e suas lâmpadas, e o óleo para a iluminação;^&#42;1^

[NOTE]
====
. Ou “a luminária; a lâmpada”.
====

[[v2-35-15]]

^<<v2-35-15,15>>^ e o altar do incenso e seus varais; e o óleo de unção e o incenso perfumado; e o reposteiro da entrada para a entrada do tabernáculo;

[[v2-35-16]]

^<<v2-35-16,16>>^ o altar da oferta queimada e a grelha de cobre que há para ele, seus varais e todos os seus utensílios; a bacia^&#42;1^ e seu suporte;

[NOTE]
====
. Ou “lavatório”.
====

[[v2-35-17]]

^<<v2-35-17,17>>^ os cortinados do pátio, suas colunas e seus pedestais de encaixe; e o reposteiro do portão do pátio;

[[v2-35-18]]

^<<v2-35-18,18>>^ as estacas de tenda do tabernáculo e as estacas de tenda do pátio, e seus cordões;

[[v2-35-19]]

^<<v2-35-19,19>>^ as vestes de tricô^&#42;1^ para se ministrar no santuário, as vestes sagradas para Arão, o sacerdote, e as vestes dos seus filhos, para atuarem como sacerdotes.’”

[NOTE]
====
. Ou “vestes de traje oficial”.
====

[[v2-35-20]]

^<<v2-35-20,20>>^ Concordemente, toda a assembléia dos filhos de Israel saiu de diante de Moisés.

[[v2-35-21]]

^<<v2-35-21,21>>^ Eles vieram então, todo aquele cujo coração o impelia, e trouxeram, todo aquele cujo espírito o incitava, a contribuição [pertencente a] Jeová para a obra da tenda de reunião e para todo o seu serviço, e para as vestes sagradas.

[[v2-35-22]]

^<<v2-35-22,22>>^ E continuaram a vir, os homens junto com as mulheres, todo aquele que estava de coração disposto. Trouxeram broches,^&#42;1^ e arrecadas, e anéis, e enfeites femininos, toda sorte de objetos de ouro, isto é, todo aquele que apresentava a Jeová a oferta movida de ouro.

[NOTE]
====
. Ou “fivelas”.
====

[[v2-35-23]]

^<<v2-35-23,23>>^ E todos os com quem se achavam linha azul, e lã tingida de roxo, e fibras carmíneas, e linho fino, e pêlos de cabra, e peles de carneiros tingidas de vermelho, e peles de focas, trouxeram-nos.

[[v2-35-24]]

^<<v2-35-24,24>>^ Todos os que faziam a contribuição de prata e de cobre trouxeram a contribuição [pertencente a] Jeová, e todos os com quem se achava madeira de acácia para toda a obra do serviço, trouxeram-na.

[[v2-35-25]]

^<<v2-35-25,25>>^ E todas as mulheres de coração sábio fiavam com as suas mãos e traziam como fio a linha azul e a lã tingida de roxo, as fibras carmíneas e o linho fino.

[[v2-35-26]]

^<<v2-35-26,26>>^ E todas as mulheres cujos corações as impeliam com sabedoria fiavam os pêlos de cabra.

[[v2-35-27]]

^<<v2-35-27,27>>^ E os maiorais trouxeram pedras de ônix e pedras de engaste para o éfode e para o peitoral,

[[v2-35-28]]

^<<v2-35-28,28>>^ e o óleo de bálsamo, e o azeite para a iluminação e para o óleo de unção, e para o incenso perfumado.

[[v2-35-29]]

^<<v2-35-29,29>>^ Cada homem e mulher, cujos corações os incitavam a trazer algo para toda a obra que Jeová mandara fazer por meio de Moisés, fazia isso; os filhos de Israel trouxeram uma oferta voluntária a Jeová.

[[v2-35-30]]

^<<v2-35-30,30>>^ Moisés disse então aos filhos de Israel: “Vede! Jeová tem chamado por nome a Bezalel, filho de Uri, filho de Hur, da tribo de Judá.

[[v2-35-31]]

^<<v2-35-31,31>>^ E ele passou a enchê-lo do espírito de Deus em sabedoria, em entendimento e em conhecimento, e em toda sorte de artesanato

[[v2-35-32]]

^<<v2-35-32,32>>^ e para elaborar projetos, para trabalhar em ouro, e em prata, e em cobre,

[[v2-35-33]]

^<<v2-35-33,33>>^ e em lavrar pedras para engastá-las e em trabalhar madeira para fazer toda sorte de trabalhos engenhosos.

[[v2-35-34]]

^<<v2-35-34,34>>^ E pôs-lhe no coração que ensinasse, ele e Ooliabe, filho de Aisamaque, da tribo de Dã.

[[v2-35-35]]

^<<v2-35-35,35>>^ Encheu-os com sabedoria de coração para fazerem toda a obra de artífice, e de bordador, e de tecelão em linha azul e lã tingida de roxo, em fibras carmíneas e linho fino, e de tecedor, homens que fazem toda sorte de obra e que elaboram projetos.

'''

xref:002-exodo/002-exodo-034.adoc#v2-34-0[&#60; Capítulo Anterior] | <<v2-35-0,Topo>> | xref:002-exodo/002-exodo-036.adoc#v2-36-0[Próximo Capítulo &#62;]