include::./index.adoc[]

[[v2-18-0]]
=== Êxodo, 18
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v2-18-1]]

^<<v2-18-1,1>>^ Ora, Jetro, sacerdote de Midiã, sogro de Moisés,^&#42;1^ chegou a ouvir de tudo o que Deus tinha feito por Moisés e por Israel, seu povo, como Jeová fizera Israel sair do Egito.

[NOTE]
====
. Ou “cujo genro Moisés era”.
====

[[v2-18-2]]

^<<v2-18-2,2>>^ Assim, Jetro, sogro de Moisés, tomou Zípora, esposa de Moisés, depois de ela ter sido mandada embora,^&#42;1^

[NOTE]
====
. Lit.: “esposa de Moisés, depois de se mandá-la embora”.
====

[[v2-18-3]]

^<<v2-18-3,3>>^ e os dois filhos dela, o nome de um sendo Gersom,^&#42;1^ “porque”, disse ele, “tornei-me residente forasteiro numa terra estrangeira”;

[NOTE]
====
. Significando “Residente Forasteiro Ali”.
====

[[v2-18-4]]

^<<v2-18-4,4>>^ e o nome do outro era Eliézer,^&#42;1^ “porque”, conforme disse, “o Deus de meu pai é meu ajudador, visto que me livrou da espada de Faraó”.

[NOTE]
====
. Significando “Meu Deus É Ajudador”.
====

[[v2-18-5]]

^<<v2-18-5,5>>^ Portanto, Jetro, sogro de Moisés, e os filhos e a esposa deste vieram ter com Moisés no ermo, onde estava acampado, junto ao monte do [verdadeiro] Deus.

[[v2-18-6]]

^<<v2-18-6,6>>^ Então mandou dizer a Moisés: “Eu,^&#42;1^ teu sogro^&#42;2^ Jetro, vim ter contigo, e comigo estão também tua esposa e seus dois filhos com ela.”

[NOTE]
====
. “Eu”, MVg; SamLXXSy: “Vê!”
. Ou: “Eu, de quem és genro.”
====

[[v2-18-7]]

^<<v2-18-7,7>>^ Moisés saiu imediatamente ao encontro de seu sogro, e passou a prostrar-se e a beijá-lo; e começaram a perguntar um ao outro como estava passando. Depois entraram na tenda.

[[v2-18-8]]

^<<v2-18-8,8>>^ E Moisés foi relatar a seu sogro tudo o que Jeová tinha feito a Faraó e ao Egito, por causa de Israel, e toda a dificuldade que lhes sobreveio no caminho, e que ainda assim Jeová os havia livrado.

[[v2-18-9]]

^<<v2-18-9,9>>^ Jetro regozijou-se então com todo o bem que Jeová fizera a Israel, por tê-los livrado^&#42;1^ da mão do Egito.

[NOTE]
====
. Ou “Israel, a quem livrou”.
====

[[v2-18-10]]

^<<v2-18-10,10>>^ Por conseguinte, Jetro disse: “Bendito seja Jeová, que vos livrou da mão do Egito e da mão de Faraó, e que livrou o povo de debaixo da mão do Egito.

[[v2-18-11]]

^<<v2-18-11,11>>^ Agora sei deveras que Jeová é maior do que todos os [demais] deuses^&#42;1^ por causa deste assunto em que agiram presunçosamente contra eles.”^&#42;2^

[NOTE]
====
. “Os [demais] deuses.” Hebr.: ha·’elo·hím; gr.: tous the·oús, pl.
. “Eles”, isto é, os israelitas.
====

[[v2-18-12]]

^<<v2-18-12,12>>^ Jetro, o sogro de Moisés, tomou então uma oferta queimada e sacrifícios para Deus; e Arão e todos os anciãos de Israel vieram comer pão com o sogro de Moisés, diante do [verdadeiro] Deus.

[[v2-18-13]]

^<<v2-18-13,13>>^ E sucedeu, no dia seguinte, que Moisés se assentou como de costume para servir de juiz ao seu povo, e o povo ficou de pé diante de Moisés, desde a manhã até à noite.

[[v2-18-14]]

^<<v2-18-14,14>>^ E o sogro de Moisés chegou a ver tudo o que ele fazia para o povo. De modo que disse: “Que espécie de negócio é este que estás fazendo para o povo? Por que é que só tu continuas sentado e todo o povo continua a postar-se diante de ti, desde a manhã até à noite?”

[[v2-18-15]]

^<<v2-18-15,15>>^ Moisés disse então ao seu sogro: “É porque o povo está vindo a mim para consultar a Deus.

[[v2-18-16]]

^<<v2-18-16,16>>^ Caso lhes surja uma causa, ela tem de ser apresentada a mim e eu tenho de julgar entre um litigante e outro, e tenho de tornar conhecidas as decisões do [verdadeiro] Deus e suas leis.”

[[v2-18-17]]

^<<v2-18-17,17>>^ Em vista disso, o sogro de Moisés disse-lhe: “Não é bom o modo como [o] fazes.

[[v2-18-18]]

^<<v2-18-18,18>>^ Por certo te esgotarás, tanto tu como este povo que está contigo, porque este assunto é pesado demais para ti. Não podes fazer isso sozinho.

[[v2-18-19]]

^<<v2-18-19,19>>^ Agora, escuta a minha voz. Eu te aconselharei e Deus mostrará estar contigo. Serve tu mesmo como representante do povo diante do [verdadeiro] Deus e tu mesmo tens de apresentar as causas ao [verdadeiro] Deus.

[[v2-18-20]]

^<<v2-18-20,20>>^ E tens de avisá-los de quais são os regulamentos e as leis e tens de fazê-los saber o caminho em que devem andar, e o trabalho que devem fazer.

[[v2-18-21]]

^<<v2-18-21,21>>^ Mas tu mesmo deves selecionar dentre todo o povo homens capazes, tementes a Deus, homens fidedignos,^&#42;1^ que odeiam o lucro injusto; e tens de pô-los sobre eles como chefes^&#42;2^ de mil,^&#42;3^ chefes de cem,^&#42;4^ chefes de cinqüenta e chefes de dez.^&#42;5^

[NOTE]
====
. Ou “verazes; fiéis”.
. “Chefes.” Hebr.: sa·réh.
. “Chefes de mil.” Gr.: khi·li·ár·khous, “quiliarcas”.
. “Chefes de cem.” Lat.: cen·tu·ri·ó·nes, “centuriões”.
. “Chefes de dez.” Lat.: de·cá·nos, “decanos; deãos”.
====

[[v2-18-22]]

^<<v2-18-22,22>>^ E eles têm de julgar o povo em toda ocasião propícia; e tem de dar-se que toda causa grande trarão a ti, mas toda causa pequena resolverão eles mesmos como juízes. Portanto, faze-o mais leve para ti, e eles têm de levar o fardo contigo.

[[v2-18-23]]

^<<v2-18-23,23>>^ Se fizeres esta coisa, e Deus te tiver mandado [isso], então poderás certamente suportá-lo, e, além disso, todo este povo irá ao seu próprio lugar em paz.”

[[v2-18-24]]

^<<v2-18-24,24>>^ Moisés escutou imediatamente a voz de seu sogro e fez tudo o que este dissera.

[[v2-18-25]]

^<<v2-18-25,25>>^ E Moisés passou a escolher homens capacitados dentre todo o Israel e a dar-lhes posições como cabeças sobre o povo, como chefes de mil, chefes de cem, chefes de cinqüenta e chefes de dez.

[[v2-18-26]]

^<<v2-18-26,26>>^ E julgaram o povo em toda ocasião propícia. Qualquer causa difícil traziam a Moisés, mas toda causa pequena resolveram eles mesmos como juízes.

[[v2-18-27]]

^<<v2-18-27,27>>^ Depois, Moisés despediu-se de seu sogro, e este seguiu caminho para a sua terra.

'''

xref:002-exodo/002-exodo-017.adoc#v2-17-0[&#60; Capítulo Anterior] | <<v2-18-0,Topo>> | xref:002-exodo/002-exodo-019.adoc#v2-19-0[Próximo Capítulo &#62;]