include::./index.adoc[]

[[v2-29-0]]
=== Êxodo, 29
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v2-29-1]]

^<<v2-29-1,1>>^ “E esta é a coisa que deves fazer-lhes para santificá-los, a fim de atuarem para mim como sacerdotes: Toma um novilho^&#42;1^ e dois carneiros, sadios,

[NOTE]
====
. Lit.: “um touro, filho da manada”.
====

[[v2-29-2]]

^<<v2-29-2,2>>^ e pão não fermentado, e bolos não fermentados, de forma anular, umedecidos com azeite, e obreias não fermentadas, untadas com azeite. Fá-los-ás de flor de farinha de trigo.

[[v2-29-3]]

^<<v2-29-3,3>>^ E tens de pô-los num cesto e apresentá-los no cesto, e também o novilho e os dois carneiros.

[[v2-29-4]]

^<<v2-29-4,4>>^ “E apresentarás Arão e seus filhos à entrada da tenda de reunião, e tens de lavá-los com água.

[[v2-29-5]]

^<<v2-29-5,5>>^ Então tens de tomar as roupas e vestir Arão com a veste comprida e a túnica sem mangas do éfode, e com o éfode e o peitoral, e tens de atá-lo bem a ele com o cinto do éfode.

[[v2-29-6]]

^<<v2-29-6,6>>^ E tens de colocar o turbante na sua cabeça e pôr o sinal sagrado de dedicação^&#42;1^ no turbante.

[NOTE]
====
. Ou “o diadema sagrado; o diadema de santidade”. Veja 39:30 n.: “dedicação”.
====

[[v2-29-7]]

^<<v2-29-7,7>>^ E tens de tomar o óleo de unção e despejá-lo sobre a sua cabeça e ungi-lo.

[[v2-29-8]]

^<<v2-29-8,8>>^ “Então farás chegar os seus filhos e tens de vesti-los com as vestes compridas.

[[v2-29-9]]

^<<v2-29-9,9>>^ E tens de cingi-los com as faixas, tanto Arão como seus filhos, e tens de enrolar neles a cobertura para a cabeça; e o sacerdócio tem de se tornar seu como estatuto por tempo indefinido.^&#42;1^ Assim tens de encher de poder a mão de Arão e a mão dos seus filhos.

[NOTE]
====
. “E eles terão um cargo sacerdotal para comigo para sempre”, LXX. Veja He 7:28.
====

[[v2-29-10]]

^<<v2-29-10,10>>^ “Então tens de apresentar o novilho diante da tenda de reunião, e Arão e seus filhos têm de pôr suas mãos sobre a cabeça do novilho.

[[v2-29-11]]

^<<v2-29-11,11>>^ E tens de abater o novilho diante de Jeová, à entrada da tenda de reunião.

[[v2-29-12]]

^<<v2-29-12,12>>^ E tens de tomar um pouco do sangue do novilho e pô-lo com o teu dedo nos chifres do altar, e todo o resto do sangue derramarás junto à base do altar.

[[v2-29-13]]

^<<v2-29-13,13>>^ E tens de tomar toda gordura que cobre os intestinos e a acrescência sobre o fígado, e os dois rins e a gordura sobre eles, e tens de fazê-los fumegar sobre o altar.

[[v2-29-14]]

^<<v2-29-14,14>>^ Mas a carne do novilho e sua pele, e seu esterco queimarás em fogo fora do acampamento. É uma oferta pelo pecado.

[[v2-29-15]]

^<<v2-29-15,15>>^ “Então tomarás um carneiro, e Arão e seus filhos têm de deitar suas mãos sobre a cabeça do carneiro.

[[v2-29-16]]

^<<v2-29-16,16>>^ E tens de abater o carneiro, e tens de tomar seu sangue e aspergi-lo ao redor sobre o altar.

[[v2-29-17]]

^<<v2-29-17,17>>^ E cortarás o carneiro nos seus pedaços, e tens de lavar seus intestinos e suas pernas, e tens de pôr seus pedaços um junto ao outro e até a sua cabeça.

[[v2-29-18]]

^<<v2-29-18,18>>^ E tens de fazer o carneiro inteiro fumegar sobre o altar. É uma oferta queimada a Jeová, um cheiro repousante. É uma oferta feita por fogo^&#42;1^ a Jeová.

[NOTE]
====
. “Uma oferta feita por fogo.” Esta é a versão usual, como que derivada de ’esh, “fogo”. Outros, derivando-o de ’nsh, acham que significa “os meios pelos quais se estabelecem relações amistosas com Deus”.
====

[[v2-29-19]]

^<<v2-29-19,19>>^ “A seguir tens de tomar o outro carneiro, e Arão e seus filhos têm de deitar suas mãos sobre a cabeça do carneiro.

[[v2-29-20]]

^<<v2-29-20,20>>^ E tens de abater o carneiro, e tens de tomar um pouco do seu sangue e pô-lo sobre a ponta da orelha direita de Arão, e sobre a ponta da orelha direita dos seus filhos, e sobre o polegar da sua mão direita, e sobre o dedo grande do seu pé direito, e tens de aspergir o sangue ao redor sobre o altar.

[[v2-29-21]]

^<<v2-29-21,21>>^ E tens de tomar um pouco do sangue que está sobre o altar e um pouco do óleo de unção, e tens de espargi-lo sobre Arão e suas vestes, e sobre seus filhos e as vestes de seus filhos com ele, para que ele e suas vestes, e seus filhos e as vestes de seus filhos com ele sejam deveras santos.

[[v2-29-22]]

^<<v2-29-22,22>>^ “E do carneiro tens de tomar a gordura e a cauda gorda, e a gordura que cobre os intestinos, e a acrescência do fígado, e os dois rins e a gordura que há sobre eles, e a perna direita, pois é um carneiro de investidura;^&#42;1^

[NOTE]
====
. Lit.: “enchimento”, isto é, o enchimento da mão de poder, empossar.
====

[[v2-29-23]]

^<<v2-29-23,23>>^ também um pão redondo e um bolo de forma anular de pão azeitado, e uma obreia do cesto dos pães não fermentados que está diante de Jeová.

[[v2-29-24]]

^<<v2-29-24,24>>^ E tens de colocar todos estes sobre as palmas das mãos de Arão e sobre as palmas dos seus filhos, e tens de movê-los para lá e para cá como oferta movida perante Jeová.

[[v2-29-25]]

^<<v2-29-25,25>>^ E tens de tirá-los das mãos deles e fazê-los fumegar sobre o altar, sobre a oferta queimada, como cheiro repousante perante Jeová. É uma oferta feita por fogo a Jeová.

[[v2-29-26]]

^<<v2-29-26,26>>^ “E tens de tomar o peito do carneiro da investidura, que é para Arão, e tens de movê-lo para lá e para cá como oferta movida perante Jeová, e ele tem de tornar-se tua porção.

[[v2-29-27]]

^<<v2-29-27,27>>^ E tens de santificar o peito da oferta movida e a perna do quinhão sagrado,^&#42;1^ que foi movida e que foi contribuída do carneiro da investidura, daquilo que era para Arão e daquilo que era para seus filhos.

[NOTE]
====
. Ou “oferta movida; contribuição”.
====

[[v2-29-28]]

^<<v2-29-28,28>>^ E tem de tornar-se de Arão e dos seus filhos por um regulamento por tempo indefinido a ser cumprido pelos filhos de Israel, porque é um quinhão sagrado; e tornar-se-á um quinhão sagrado a ser entregue pelos filhos de Israel. Dos seus sacrifícios de participação em comum^&#42;1^ é seu quinhão sagrado para Jeová.

[NOTE]
====
. Ou: “Dos sacrifícios de suas ofertas pacíficas.”
====

[[v2-29-29]]

^<<v2-29-29,29>>^ “E as vestes sagradas que são de Arão servirão para seus filhos após ele, para ungi-los nelas e nelas encher-lhes a mão de poder.

[[v2-29-30]]

^<<v2-29-30,30>>^ Por sete dias as usará o sacerdote que lhe suceder dentre seus filhos e que entrar na tenda de reunião para ministrar no lugar santo.

[[v2-29-31]]

^<<v2-29-31,31>>^ “E tomarás o carneiro da investidura, e tens de cozinhar a sua carne num lugar santo.

[[v2-29-32]]

^<<v2-29-32,32>>^ E Arão e seus filhos têm de comer a carne do carneiro e o pão que há no cesto à entrada da tenda de reunião.

[[v2-29-33]]

^<<v2-29-33,33>>^ E eles têm de comer as coisas com as quais se fez expiação^&#42;1^ para encher-lhes a mão de poder, a fim de santificá-los. Mas o estranho^&#42;2^ não pode comer delas, porque são algo sagrado.

[NOTE]
====
. Lit.: “cobertura”.
. Ou “não-aronita”, isto é, um homem que não era da família de Arão.
====

[[v2-29-34]]

^<<v2-29-34,34>>^ E se sobrar algo da carne do sacrifício da investidura e do pão até à manhã, então terás de queimar em fogo o que sobrar. Não deve ser comido, porque é algo sagrado.

[[v2-29-35]]

^<<v2-29-35,35>>^ “E assim terás de fazer a Arão e aos seus filhos, segundo tudo o que te mandei. Levarás sete dias para encher-lhes a mão de poder.

[[v2-29-36]]

^<<v2-29-36,36>>^ E oferecerás diariamente o novilho da oferta pelo pecado como expiação, e terás de purificar de pecado o altar por fazer expiação sobre ele, e terás de ungi-lo para o santificar.

[[v2-29-37]]

^<<v2-29-37,37>>^ Levarás sete dias para fazer expiação sobre o altar e terás de santificá-lo para que deveras se torne um altar santíssimo. Todo aquele que^&#42;1^ tocar no altar deve ser santo.

[NOTE]
====
. Ou: “Tudo o que.”
====

[[v2-29-38]]

^<<v2-29-38,38>>^ “E isto é o que oferecerás sobre o altar: carneirinhos de um ano cada um, dois por dia, continuamente.

[[v2-29-39]]

^<<v2-29-39,39>>^ E oferecerás um carneirinho^&#42;1^ pela manhã e oferecerás o outro carneirinho entre as duas noitinhas.^&#42;2^

[NOTE]
====
. Ou “um cordeiro”.
. Veja 12:6 n.
====

[[v2-29-40]]

^<<v2-29-40,40>>^ E a décima parte de uma medida de efa^&#42;1^ de flor de farinha umedecida com um quarto de him^&#42;2^ de azeite batido e uma oferta de bebida de um quarto de him de vinho serão para o primeiro carneirinho.

[NOTE]
====
. “E a décima parte duma medida de efa”, segundo Núm 15:4 em LXXVg. Lit.: “E uma décima parte de.” Veja Ap. 8A.
. Um him equivalia a 3,67 l.
====

[[v2-29-41]]

^<<v2-29-41,41>>^ E oferecerás o segundo carneirinho entre as duas noitinhas. Entregá-lo-ás com uma oferta de cereais igual à da manhã e com uma oferta de bebida igual à sua, como cheiro repousante, uma oferta feita por fogo a Jeová.

[[v2-29-42]]

^<<v2-29-42,42>>^ É uma contínua oferta queimada nas vossas gerações, à entrada da tenda de reunião perante Jeová, onde me apresentarei a vós para falar-te ali.

[[v2-29-43]]

^<<v2-29-43,43>>^ “E ali vou apresentar-me aos filhos de Israel, e ele^&#42;1^ certamente será santificado^&#42;2^ pela minha glória.

[NOTE]
====
. “Ele”, M; Vg: “o altar”.
. “E ele certamente será santificado (tido como sagrado; tratado como santo).” Hebr.: weniq·dásh; lat.: sanc·ti·fi·cá·bi·tur; gr.: ha·gi·a·sthé·so·mai, “serei santificado”. Veja Mt 6:9 n.
====

[[v2-29-44]]

^<<v2-29-44,44>>^ E vou santificar a tenda de reunião e o altar; e santificarei Arão e seus filhos, a fim de atuarem para mim como sacerdotes.

[[v2-29-45]]

^<<v2-29-45,45>>^ E vou residir no meio dos filhos de Israel e vou mostrar-me seu Deus.

[[v2-29-46]]

^<<v2-29-46,46>>^ E saberão certamente que eu sou Jeová, seu Deus, que os fiz sair da terra do Egito para residir no meio deles. Eu sou Jeová, seu Deus.

'''

xref:002-exodo/002-exodo-028.adoc#v2-28-0[&#60; Capítulo Anterior] | <<v2-29-0,Topo>> | xref:002-exodo/002-exodo-030.adoc#v2-30-0[Próximo Capítulo &#62;]