include::./index.adoc[]

[[v2-3-0]]
=== Êxodo, 3
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v2-3-1]]

^<<v2-3-1,1>>^ E Moisés tornou-se pastor do rebanho de Jetro, sacerdote de Midiã, de quem era genro.^&#42;1^ Quando estava conduzindo o rebanho para o lado ocidental do ermo, chegou por fim ao monte do [verdadeiro] Deus, a Horebe.

[NOTE]
====
. Ou “Jetro, . . . seu sogro”.
====

[[v2-3-2]]

^<<v2-3-2,2>>^ O anjo de Jeová^&#42;1^ apareceu-lhe então numa chama de fogo no meio dum espinheiro. Enquanto ele olhava, ora, eis que o espinheiro ardia com fogo, contudo, o espinheiro não se consumia.

[NOTE]
====
. Hebr.: Yeho·wáh. Veja Ap. 1A.
====

[[v2-3-3]]

^<<v2-3-3,3>>^ Em vista disso, Moisés disse: “Deixa-me desviar-me para inspecionar este grande fenômeno, por que o espinheiro não se queima.”

[[v2-3-4]]

^<<v2-3-4,4>>^ Quando Jeová^&#42;1^ viu que se desviara para inspecionar, Deus o chamou imediatamente do meio do espinheiro e disse: “Moisés! Moisés!” ao que ele disse: “Eis-me aqui.”

[NOTE]
====
. “Deus”, Sam; isto é, o anjo de Jeová que falou por Ele. Veja v. 2.
====

[[v2-3-5]]

^<<v2-3-5,5>>^ Então disse: “Não te chegues para cá. Remove as tuas sandálias dos teus pés, porque o lugar em que estás parado é solo sagrado.”

[[v2-3-6]]

^<<v2-3-6,6>>^ E prosseguiu, dizendo: “Eu sou o Deus de teu pai,^&#42;1^ o Deus de Abraão, o Deus de Isaque e o Deus de Jacó.” Moisés escondeu então a sua face, porque estava com medo de olhar para o [verdadeiro] Deus.^&#42;2^

[NOTE]
====
. “Pai”, MLXXSyVg; Sam: “pais”.
. Veja Ap. 1F.
====

[[v2-3-7]]

^<<v2-3-7,7>>^ E Jeová acrescentou: “Indubitavelmente, tenho visto a tribulação do meu povo que está no Egito e tenho ouvido seu clamor por causa daqueles que os compelem a trabalhar; porque eu bem sei das dores que sofrem.

[[v2-3-8]]

^<<v2-3-8,8>>^ E estou para descer, a fim de livrá-los da mão dos egípcios e para fazê-los subir daquela terra para uma terra boa e espaçosa, para uma terra que mana leite e mel, para o lugar dos cananeus, e dos hititas, e dos amorreus, e dos perizeus, e dos heveus, e dos jebuseus.

[[v2-3-9]]

^<<v2-3-9,9>>^ E agora, eis que chegou a mim o clamor dos filhos de Israel e eu vi também a opressão com que os egípcios os oprimem.

[[v2-3-10]]

^<<v2-3-10,10>>^ E agora vem, e deixa-me enviar-te a Faraó, e faze que meu povo, os filhos de Israel, saia do Egito.”

[[v2-3-11]]

^<<v2-3-11,11>>^ No entanto, Moisés disse ao [verdadeiro] Deus: “Quem sou eu para ir a Faraó e para ter de fazer os filhos de Israel sair do Egito?”

[[v2-3-12]]

^<<v2-3-12,12>>^ A isso ele disse: “Porque mostrarei estar contigo, e este é o sinal para ti de que sou eu quem te enviou: Depois de teres feito o povo sair do Egito, servireis^&#42;1^ o [verdadeiro] Deus neste monte.”

[NOTE]
====
. “Servireis (adorareis).” Hebr.: ta·‛av·dhún; gr.: la·treú·se·te, “prestareis serviço sagrado”. Veja KB, p. 671, a respeito da tradução “adorar um deus”. Veja também Mt 4:10 n.: “sagrado”.
====

[[v2-3-13]]

^<<v2-3-13,13>>^ Não obstante, Moisés disse ao [verdadeiro] Deus: “Suponhamos que eu vá ter com os filhos de Israel e deveras lhes diga: ‘O Deus de vossos antepassados enviou-me a vós’, e eles deveras me digam: ‘Qual é o seu nome?’ O que hei de dizer-lhes?”

[[v2-3-14]]

^<<v2-3-14,14>>^ Então disse Deus a Moisés: “MOSTRAREI SER O QUE EU MOSTRAR SER.”^&#42;1^ E acrescentou: “Isto é o que deves dizer aos filhos de Israel: ‘MOSTRAREI SER enviou-me a vós.’”

[NOTE]
====
. “MOSTRAREI SER O QUE EU MOSTRAR SER.” Hebr.: אֶהְיֶֽה אֲשֶֽׁר אֶהְיֶֽה (’Eh·yéh ’Ashér ’Eh·yéh), o nome que Deus deu a si mesmo; Leeser: “SEREI O QUE EU FOR”; Rotherham: “Tornar-me-ei o que eu quiser.” Gr.: E·gó ei·mi ho on, “Eu sou O Ser”, ou: “Eu sou O Existente”; lat.: é·go sum qui sum, “Eu sou Quem sou”. ’Eh·yéh deriva do verbo hebr. ha·yáh, “vir a ser; tornar-se; mostrar ser”. Aqui, ’Eh·yéh está no imperfeito, na primeira pessoa sing., significando “virei a ser; tornar-me-ei”; ou: “mostrarei ser”. Esta referência não é à auto-existência de Deus, mas ao que pretende tornar-se para com outros. Veja Ge 2:4 n.: “Jeová”, onde o verbo hebr. similar, mas diferente, ha·wáh aparece no nome divino.
====

[[v2-3-15]]

^<<v2-3-15,15>>^ Deus disse então mais uma vez a Moisés:
“Isto é o que deves dizer aos filhos de Israel: ‘Jeová, o Deus de vossos antepassados, o Deus de Abraão, o Deus de Isaque e o Deus de Jacó enviou-me a vós.’ Este é o meu nome por tempo indefinido^&#42;1^ e esta é a recordação de mim^&#42;2^ por geração após geração.

[NOTE]
====
. “Meu nome por tempo indefinido.” Hebr.: shemí le‛o·lám.
. “A recordação de mim.” Hebr.: zikh·rí; lat.: me·mo·ri·á·le mé·um.
====

[[v2-3-16]]

^<<v2-3-16,16>>^ Vai, e tens de ajuntar os anciãos de Israel e tens de dizer-lhes: ‘Apareceu-me Jeová, o Deus de vossos antepassados, o Deus de Abraão, Isaque e Jacó, dizendo: “Sem falta hei de dar atenção a vós e ao que se está fazendo a vós no Egito.

[[v2-3-17]]

^<<v2-3-17,17>>^ E por isso digo: Eu vos farei subir da vossa tribulação da parte dos egípcios para a terra dos cananeus, e dos hititas, e dos amorreus, e dos perizeus, e dos heveus, e dos jebuseus, para uma terra que mana leite e mel.”’

[[v2-3-18]]

^<<v2-3-18,18>>^ “E certamente escutarão a tua voz, e terás de ir ao rei do Egito, tu e os anciãos de Israel, e tereis de dizer-lhe: ‘Jeová, o Deus dos hebreus, entrou em contato conosco, e agora, por favor, queremos ir numa jornada de três dias ao ermo e queremos oferecer sacrifícios a Jeová, nosso Deus.’

[[v2-3-19]]

^<<v2-3-19,19>>^ E eu é que bem sei que o rei do Egito não vos dará permissão para ir, exceto por mão forte.

[[v2-3-20]]

^<<v2-3-20,20>>^ E terei de estender a minha mão e golpear o Egito com todos os meus atos maravilhosos que farei no meio dele; e depois ele vos mandará sair.

[[v2-3-21]]

^<<v2-3-21,21>>^ E vou dar a este povo favor aos olhos dos egípcios; e certamente se dará que, quando fordes, não ireis de mãos vazias.

[[v2-3-22]]

^<<v2-3-22,22>>^ E cada mulher terá de pedir de sua vizinha e da mulher que reside como forasteira na sua casa objetos de prata e objetos de ouro, e capas, e tereis de pô-los sobre vossos filhos e vossas filhas; e tereis de despojar os egípcios.”

'''

xref:002-exodo/002-exodo-002.adoc#v2-2-0[&#60; Capítulo Anterior] | <<v2-3-0,Topo>> | xref:002-exodo/002-exodo-004.adoc#v2-4-0[Próximo Capítulo &#62;]