include::./index.adoc[]

[[v2-30-0]]
=== Êxodo, 30
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v2-30-1]]

^<<v2-30-1,1>>^ “E terás de fazer um altar como lugar para se queimar incenso; fá-lo-ás de madeira de acácia.

[[v2-30-2]]

^<<v2-30-2,2>>^ De um côvado de comprimento e de um côvado de largura, deverá ser quadrado, e sua altura dois côvados. Seus chifres se estenderão dele.

[[v2-30-3]]

^<<v2-30-3,3>>^ E terás de recobri-lo de ouro puro, sua parte superior e seus lados^&#42;1^ ao redor, e seus chifres; e terás de fazer-lhe uma bordadura de ouro ao redor.

[NOTE]
====
. Lit.: “paredes”.
====

[[v2-30-4]]

^<<v2-30-4,4>>^ Far-lhe-ás também duas argolas de ouro. Fá-las-ás abaixo da sua bordadura em dois dos seus lados, em dois lados opostos dele, visto que terão de servir de suportes para os varais com que será carregado.

[[v2-30-5]]

^<<v2-30-5,5>>^ E terás de fazer os varais de madeira de acácia e recobri-los de ouro.

[[v2-30-6]]

^<<v2-30-6,6>>^ E terás de pô-lo diante da cortina que está perto da arca do testemunho, diante da tampa que há sobre o Testemunho, onde me apresentarei a ti.

[[v2-30-7]]

^<<v2-30-7,7>>^ “E Arão terá de fazer fumegar incenso perfumado sobre ele. Fá-lo-á fumegar manhã após manhã, ao aprontar as lâmpadas.

[[v2-30-8]]

^<<v2-30-8,8>>^ E fá-lo-á fumegar quando Arão acender as lâmpadas entre as duas noitinhas. É um incenso contínuo perante Jeová nas vossas gerações.

[[v2-30-9]]

^<<v2-30-9,9>>^ Não deveis oferecer sobre ele nenhum incenso ilegítimo,^&#42;1^ nem oferta queimada, nem oferta de cereais;^&#42;2^ e não deveis derramar sobre ele nenhuma oferta de bebida.

[NOTE]
====
. Lit.: “estranho”.
. Lit.: “dádiva”.
====

[[v2-30-10]]

^<<v2-30-10,10>>^ E uma vez por ano Arão terá de fazer expiação sobre os seus chifres. Com um pouco de sangue da oferta pelo pecado, da expiação, fará expiação por ele uma vez por ano, nas vossas gerações. É santíssimo para Jeová.”

[[v2-30-11]]

^<<v2-30-11,11>>^ E Jeová prosseguiu falando a Moisés, dizendo:

[[v2-30-12]]

^<<v2-30-12,12>>^ “Sempre que fizeres a soma dos filhos de Israel como recenseamento deles,^&#42;1^ então cada um terá de dar a Jeová um resgate^&#42;2^ pela sua alma^&#42;3^ quando^&#42;4^ se fizer o recenseamento deles, para que não venha sobre eles alguma praga ao se fazer o seu recenseamento.

[NOTE]
====
. Ou “pelos seus registrados”.
. Ou “reparação”. Lit.: “cobertura”. Gr.: lý·tra, pl.
. “Sua alma (vida).” Hebr.: naf·shóh; gr.: psy·khés.
. Ou “por”.
====

[[v2-30-13]]

^<<v2-30-13,13>>^ Isto é o que darão todos os que passarem para os contados: meio siclo segundo o siclo^&#42;1^ do lugar santo.^&#42;2^ Vinte geras^&#42;3^ são iguais a um siclo. Meio siclo é a contribuição a Jeová.

[NOTE]
====
. “Siclo”, MSy; LXX: “didracma”. Veja Ap. 8A.
. Ou “segundo o siclo sagrado”. Este era um peso-padrão mantido no tabernáculo; ou, possivelmente, para enfatizar que o peso devia ser exato. Veja 2Sa 14:26 n.: “pedra”.
. Veja Ap. 8A.
====

[[v2-30-14]]

^<<v2-30-14,14>>^ Todo aquele que passar para os registrados, de vinte anos de idade e para cima, dará a contribuição [pertencente a] Jeová.

[[v2-30-15]]

^<<v2-30-15,15>>^ O rico não deve dar mais e o de condição humilde não deve dar menos de meio siclo, a fim de dar a contribuição [pertencente a] Jeová para se fazer expiação pelas vossas almas.

[[v2-30-16]]

^<<v2-30-16,16>>^ E terás de tomar dos filhos de Israel o dinheiro de prata da expiação e dá-lo em benefício do serviço da tenda de reunião, para que deveras sirva de recordação perante Jeová para os filhos de Israel, a fim de se fazer expiação pelas vossas almas.”

[[v2-30-17]]

^<<v2-30-17,17>>^ E Jeová falou mais a Moisés, dizendo:

[[v2-30-18]]

^<<v2-30-18,18>>^ “Tens de fazer uma bacia^&#42;1^ de cobre e seu suporte de cobre, para a lavagem, e tens de pô-la entre a tenda de reunião e o altar, e tens de pôr água nela.

[NOTE]
====
. Ou “lavatório”.
====

[[v2-30-19]]

^<<v2-30-19,19>>^ E Arão e seus filhos terão de lavar ali suas mãos e seus pés.

[[v2-30-20]]

^<<v2-30-20,20>>^ Quando entrarem na tenda de reunião, lavar-se-ão com água para que não morram, ou quando se aproximarem do altar para ministrar, a fim de fazerem fumegar uma oferta feita por fogo a Jeová.

[[v2-30-21]]

^<<v2-30-21,21>>^ E terão de lavar as mãos e os pés, para que não morram, e isso terá de servir-lhes de regulamento por tempo indefinido, para ele e para sua descendência, nas suas gerações.”

[[v2-30-22]]

^<<v2-30-22,22>>^ E Jeová continuou a falar a Moisés, dizendo:

[[v2-30-23]]

^<<v2-30-23,23>>^ “Quanto a ti, toma para ti os mais seletos perfumes: mirra em gotas solidificadas,^&#42;1^ quinhentas unidades, e canela fragrante na metade desta quantidade, duzentas e cinqüenta unidades, e cálamo fragrante, duzentas e cinqüenta unidades,

[NOTE]
====
. Ou “mirra de pérolas”, quer dizer, gotas brancas de mirra, solidificadas, que ficaram vermelho-escuras ou pretas.
====

[[v2-30-24]]

^<<v2-30-24,24>>^ e cássia, quinhentas unidades segundo o siclo do lugar santo, e um him de azeite de oliveira.

[[v2-30-25]]

^<<v2-30-25,25>>^ Então tens de fazer disso um óleo de santa unção, um ungüento, uma mistura que é obra de fabricante de ungüento. Deve ser um óleo de santa unção.

[[v2-30-26]]

^<<v2-30-26,26>>^ “E com ele terás de ungir a tenda de reunião e a arca do testemunho,

[[v2-30-27]]

^<<v2-30-27,27>>^ e a mesa e todos os seus utensílios, e o candelabro e seus utensílios, e o altar do incenso,

[[v2-30-28]]

^<<v2-30-28,28>>^ e o altar da oferta queimada e todos os utensílios, e a bacia e seu suporte.

[[v2-30-29]]

^<<v2-30-29,29>>^ E terás de santificá-los para que deveras se tornem santíssimos. Quem^&#42;1^ os tocar deve ser santo.

[NOTE]
====
. Ou: “Tudo o que.”
====

[[v2-30-30]]

^<<v2-30-30,30>>^ E ungirás Arão e seus filhos, e terás de santificá-los, a fim de atuarem para mim como sacerdotes.

[[v2-30-31]]

^<<v2-30-31,31>>^ “E falarás aos filhos de Israel, dizendo: ‘Isto deve continuar como óleo de santa unção para mim nas vossas gerações.

[[v2-30-32]]

^<<v2-30-32,32>>^ Não deve ser esfregado em carne humana, e com a sua composição não deveis fazer nada igual a ele. É algo sagrado. Deve continuar como algo sagrado para vós.

[[v2-30-33]]

^<<v2-30-33,33>>^ Quem fizer um ungüento semelhante a ele e quem puser dele num estranho^&#42;1^ terá de ser decepado do seu povo.’”

[NOTE]
====
. “Estranho”, isto é, um não-aronita. Veja 29:32, 33.
====

[[v2-30-34]]

^<<v2-30-34,34>>^ E Jeová prosseguiu, dizendo a Moisés: “Toma para ti perfumes: gotas de estoraque, e onicha, e gálbano perfumado, e olíbano puro. Deve haver a mesma porção de cada um.

[[v2-30-35]]

^<<v2-30-35,35>>^ E tens de fazer disso um incenso, uma mistura aromática, trabalho de fabricante de ungüento, salgado, puro, algo sagrado.

[[v2-30-36]]

^<<v2-30-36,36>>^ E um pouco dele tens de reduzir a pó fino e tens de pôr um pouco dele diante do Testemunho na tenda de reunião, onde me apresentarei a ti. Deve ser santíssimo para vós.

[[v2-30-37]]

^<<v2-30-37,37>>^ E o incenso que farás com esta composição não deveis fazer para vós mesmos. Deve continuar para ti como algo sagrado para Jeová.

[[v2-30-38]]

^<<v2-30-38,38>>^ Quem fizer um igual a este para regalar-se com o seu cheiro tem de ser decepado do seu povo.”

'''

xref:002-exodo/002-exodo-029.adoc#v2-29-0[&#60; Capítulo Anterior] | <<v2-30-0,Topo>> | xref:002-exodo/002-exodo-031.adoc#v2-31-0[Próximo Capítulo &#62;]