include::./index.adoc[]

[[v2-8-0]]
=== Êxodo, 8
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v2-8-1]]

^<<v2-8-1,1>>^ ^&#42;1^Jeová disse então a Moisés: “Entra até Faraó, e tens de dizer-lhe: ‘Assim disse Jeová: “Manda embora meu povo, para que me sirvam.

[NOTE]
====
. MLXX têm isso como 7:26.
====

[[v2-8-2]]

^<<v2-8-2,2>>^ E se continuares a negar-te a mandá-los embora, eis que ferirei com rãs a todo o teu território.

[[v2-8-3]]

^<<v2-8-3,3>>^ E o rio Nilo a bem dizer pululará de rãs, e elas hão de subir e entrar na tua casa e no teu dormitório interno, e no teu leito, e nas casas dos teus servos, e [estarão] sobre teu povo, e nos teus fornos, e nas tuas amassadeiras.

[[v2-8-4]]

^<<v2-8-4,4>>^ E as rãs subirão em ti e no teu povo, e em todos os teus servos.”’”

[[v2-8-5]]

^<<v2-8-5,5>>^ ^&#42;1^ Mais tarde, Jeová disse a Moisés: “Dize a Arão: ‘Estende tua mão com o teu bastão sobre os rios, sobre os canais do Nilo e sobre os banhados de juncos, e faze subir as rãs sobre a terra do Egito.’”

[NOTE]
====
. MLXX começam aqui o capítulo 8.
====

[[v2-8-6]]

^<<v2-8-6,6>>^ Arão estendeu então sua mão sobre as águas do Egito, e as rãs começaram a subir e a cobrir a terra do Egito.

[[v2-8-7]]

^<<v2-8-7,7>>^ No entanto, os sacerdotes-magos fizeram a mesma coisa com as suas artes secretas e fizeram subir rãs sobre a terra do Egito.

[[v2-8-8]]

^<<v2-8-8,8>>^ Com o tempo, Faraó chamou Moisés e Arão, e disse: “Suplicai a Jeová para que remova as rãs de mim e do meu povo, visto que quero mandar o povo embora, para que ofereçam sacrifícios a Jeová.”

[[v2-8-9]]

^<<v2-8-9,9>>^ Moisés disse então a Faraó: “Tem sobre mim a glória de dizer^&#42;1^ quando devo fazer súplica por ti e pelos teus servos, e pelo teu povo, para eliminar as rãs de cima de ti e das tuas casas. Somente no rio Nilo serão deixadas.”

[NOTE]
====
. Alternativa possível: “explicar-me”.
====

[[v2-8-10]]

^<<v2-8-10,10>>^ A isso ele disse: “Amanhã.” De modo que ele disse: “Será segundo a tua palavra, para que saibas que ninguém mais é como Jeová, nosso Deus,

[[v2-8-11]]

^<<v2-8-11,11>>^ visto que as rãs certamente se retirarão de ti e das tuas casas, e dos teus servos, e do teu povo. Somente no rio Nilo serão deixadas.”

[[v2-8-12]]

^<<v2-8-12,12>>^ Concordemente, Moisés e Arão saíram de diante de Faraó, e Moisés clamou a Jeová por causa das rãs que Ele pusera sobre Faraó.

[[v2-8-13]]

^<<v2-8-13,13>>^ Jeová fez então segundo a palavra de Moisés e as rãs começaram a morrer nas casas, nos pátios e nos campos.

[[v2-8-14]]

^<<v2-8-14,14>>^ E empilhavam-nas, montão sobre montão, e a terra começou a cheirar mal.

[[v2-8-15]]

^<<v2-8-15,15>>^ Quando Faraó viu que houve alívio, fez o seu coração insensível;^&#42;1^ e não os escutou, assim como Jeová havia falado.

[NOTE]
====
. “Fez . . . insensível”, em harmonia com Sam. No M, este verbo está no infinitivo absoluto, indefinido quanto ao tempo.
====

[[v2-8-16]]

^<<v2-8-16,16>>^ Jeová disse então a Moisés: “Dize a Arão: ‘Estende teu bastão e golpeia o pó da terra, e este tem de tornar-se em borrachudos em toda a terra do Egito.’”

[[v2-8-17]]

^<<v2-8-17,17>>^ E passaram a fazer isso. De modo que Arão estendeu sua mão com o seu bastão e golpeou o pó da terra, e houve borrachudos^&#42;1^ em homem e animal. Todo o pó da terra tornou-se em borrachudos em toda a terra do Egito.

[NOTE]
====
. Ou “mosquitos”. Hebr.: hak·kin·nám. Sem haver muita probabilidade para isso, o historiador Josefo (Jewish Antiquities, Livro II, capítulo 14, § 3) explica esta palavra como significando piolhos, e o Talmude também usa a forma kin·ním para piolhos.
====

[[v2-8-18]]

^<<v2-8-18,18>>^ E os sacerdotes-magos procuraram fazer o mesmo com as suas artes secretas, para fazer sair borrachudos, mas não puderam. E houve borrachudos em homem e animal.

[[v2-8-19]]

^<<v2-8-19,19>>^ Os sacerdotes-magos disseram, por isso, a Faraó: “É o dedo de Deus!” Mas o coração de Faraó continuou obstinado e ele não os escutou, assim como Jeová havia falado.

[[v2-8-20]]

^<<v2-8-20,20>>^ Jeová disse então a Moisés: “Levanta-te de manhã cedo e toma posição diante de Faraó. Eis que ele está saindo à água! E tens de dizer-lhe: ‘Assim disse Jeová: “Manda embora meu povo, para que me sirvam.^&#42;1^

[NOTE]
====
. “Para que me sirvam (adorem).” Hebr.: weya·‛av·dhú·ni; gr.: la·treú·so·sin, “para que prestem serviço sagrado”. Veja 3:12 n.
====

[[v2-8-21]]

^<<v2-8-21,21>>^ Mas se não mandares embora meu povo, eis que enviarei o moscão^&#42;1^ sobre ti, e sobre os teus servos, e sobre o teu povo, e às tuas casas; e as casas do Egito estarão simplesmente cheias de moscões, e também o solo em que estão.

[NOTE]
====
. “Mosca-dos-estábulos”, LXX.
====

[[v2-8-22]]

^<<v2-8-22,22>>^ E naquele dia certamente farei ficar à parte a terra de Gósen em que está meu povo, para que não haja ali nenhum moscão; a fim de que saibas que eu sou Jeová no meio da terra.^&#42;1^

[NOTE]
====
. Ou “eu, Jeová, estou no meio da terra (país)”.
====

[[v2-8-23]]

^<<v2-8-23,23>>^ E deveras porei uma demarcação entre meu povo e teu povo. Amanhã ocorrerá este sinal.”’”

[[v2-8-24]]

^<<v2-8-24,24>>^ E Jeová passou a fazer isso; e densos enxames de moscões começaram a invadir a casa de Faraó e as casas dos seus servos, e toda a terra do Egito. O país ficou arruinado por causa dos moscões.

[[v2-8-25]]

^<<v2-8-25,25>>^ Por fim, Faraó chamou Moisés e Arão, e disse: “Ide, oferecei sacrifícios ao vosso Deus^&#42;1^ no país.”

[NOTE]
====
. “Ao vosso Deus.” Hebr.: lE’·lo·heh·khém; TJLXXBagsterSy: “Jeová, vosso Deus”.
====

[[v2-8-26]]

^<<v2-8-26,26>>^ Moisés disse, porém: “Não é admissível fazer isso, pois ofereceríamos em sacrifício a Jeová, nosso Deus, algo detestável para os egípcios. Suponhamos que sacrificássemos algo detestável para os egípcios, diante dos seus olhos; não nos apedrejariam?

[[v2-8-27]]

^<<v2-8-27,27>>^ Iremos numa jornada de três dias ao ermo e ofereceremos definitivamente sacrifícios a Jeová, nosso Deus, assim como ele nos disse.”

[[v2-8-28]]

^<<v2-8-28,28>>^ Faraó disse então: “Eu é que vos mandarei embora, e haveis de oferecer sacrifícios a Jeová, vosso Deus, no ermo. Somente não o façais indo tão longe. Fazei súplica por mim.”

[[v2-8-29]]

^<<v2-8-29,29>>^ Moisés disse então: “Eis que saio de diante de ti e farei deveras súplica a Jeová, e os moscões certamente se retirarão amanhã de Faraó, dos seus servos e do seu povo. Apenas não proceda Faraó de novo com ludíbrio por não mandar o povo embora para oferecer sacrifícios a Jeová.”

[[v2-8-30]]

^<<v2-8-30,30>>^ Depois, Moisés saiu de diante de Faraó e fez súplica a Jeová.

[[v2-8-31]]

^<<v2-8-31,31>>^ Assim, Jeová fez segundo a palavra de Moisés e os moscões se retiraram de Faraó, dos seus servos e do seu povo. Não sobrou nem sequer um.

[[v2-8-32]]

^<<v2-8-32,32>>^ No entanto, Faraó fez seu coração insensível também esta vez e não mandou o povo embora.

'''

xref:002-exodo/002-exodo-007.adoc#v2-7-0[&#60; Capítulo Anterior] | <<v2-8-0,Topo>> | xref:002-exodo/002-exodo-009.adoc#v2-9-0[Próximo Capítulo &#62;]