include::./index.adoc[]

[[v2-37-0]]
=== Êxodo, 37
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v2-37-1]]

^<<v2-37-1,1>>^ Bezalel fez então a Arca de madeira de acácia. Dois côvados e meio era seu comprimento, e um côvado e meio sua largura, e um côvado e meio sua altura.

[[v2-37-2]]

^<<v2-37-2,2>>^ Recobriu-a então de ouro puro por dentro e por fora, e fez-lhe uma bordadura de ouro ao redor.

[[v2-37-3]]

^<<v2-37-3,3>>^ Depois fundiu para ela quatro argolas de ouro, para [que ficassem] acima dos seus quatro pés, com duas argolas num lado dela e duas argolas noutro lado dela.

[[v2-37-4]]

^<<v2-37-4,4>>^ A seguir fez varais de madeira de acácia e os recobriu de ouro.

[[v2-37-5]]

^<<v2-37-5,5>>^ Passou então os varais pelas argolas nos lados da Arca, para se carregar a Arca.

[[v2-37-6]]

^<<v2-37-6,6>>^ E ele foi fazer a tampa^&#42;1^ de ouro puro. Dois côvados e meio era seu comprimento e um côvado e meio era sua largura.

[NOTE]
====
. Ou “trono de misericórdia; propiciatório”, LXXVg(lat.: pro·pi·ti·a·tó·ri·um); hebr.: kap·pó·reth. Veja 25:17 n.
====

[[v2-37-7]]

^<<v2-37-7,7>>^ Além disso, fez dois querubins de ouro. Fê-los de obra batida ao martelo em ambas as extremidades da tampa.

[[v2-37-8]]

^<<v2-37-8,8>>^ Um querubim estava na extremidade de lá e o outro querubim estava na extremidade de cá. Fez os querubins na tampa, em ambas as extremidades da mesma.

[[v2-37-9]]

^<<v2-37-9,9>>^ E vieram a ser querubins que estendiam duas asas para cima, abrigando a tampa com as suas asas e tendo suas faces [voltadas] um para o outro. As faces dos querubins mostravam-se [inclinadas] para a tampa.

[[v2-37-10]]

^<<v2-37-10,10>>^ E ele passou a fazer a mesa de madeira de acácia. Dois côvados era seu comprimento, e um côvado sua largura, e um côvado e meio sua altura.

[[v2-37-11]]

^<<v2-37-11,11>>^ Recobriu-a então de ouro puro e fez-lhe uma bordadura de ouro ao redor.

[[v2-37-12]]

^<<v2-37-12,12>>^ A seguir, fez-lhe ao redor uma borda da largura da mão e fez uma bordadura para a sua borda ao redor.

[[v2-37-13]]

^<<v2-37-13,13>>^ Além disso, fundiu para ela quatro argolas de ouro e pôs as argolas nos quatro cantos que eram para os quatro pés.

[[v2-37-14]]

^<<v2-37-14,14>>^ As argolas mostravam estar perto da borda, como suportes para os varais, para se carregar a mesa.

[[v2-37-15]]

^<<v2-37-15,15>>^ Fez então os varais de madeira de acácia e recobriu-os de ouro, para se carregar a mesa.

[[v2-37-16]]

^<<v2-37-16,16>>^ Depois fez de ouro puro os utensílios que há na mesa, seus pratos, e suas taças, e suas tigelas, e suas bilhas com as quais se derramam^&#42;1^ [as libações].

[NOTE]
====
. Lit.: “com as quais é derramada”.
====

[[v2-37-17]]

^<<v2-37-17,17>>^ Fez então o candelabro de ouro puro. Fez o candelabro obra batida ao martelo. Seus lados e suas hastes, seus cálices, seus botões e suas flores procediam dele.

[[v2-37-18]]

^<<v2-37-18,18>>^ E dos seus lados saíam seis hastes, três hastes do candelabro de um dos seus lados e três hastes do candelabro do seu outro lado.

[[v2-37-19]]

^<<v2-37-19,19>>^ Três cálices em forma de flores de amêndoa estavam num grupo de hastes, alternando-se botões e flores; e três cálices em forma de flores de amêndoa estavam no outro grupo de hastes, alternando-se botões e flores. Assim era com as seis hastes que saíam do candelabro.

[[v2-37-20]]

^<<v2-37-20,20>>^ E no candelabro havia quatro cálices em forma de flores de amêndoa, alternando-se seus botões e suas flores.

[[v2-37-21]]

^<<v2-37-21,21>>^ E o botão debaixo de duas hastes provinha dele, e o botão debaixo de outras duas hastes provinha dele, e o botão debaixo de mais duas hastes provinha dele, para as seis hastes que saíam do candelabro.

[[v2-37-22]]

^<<v2-37-22,22>>^ Seus botões e suas hastes procediam dele. Todo ele era uma só peça de obra batida ao martelo, de ouro puro.

[[v2-37-23]]

^<<v2-37-23,23>>^ Fez então de ouro puro suas sete lâmpadas, e suas espevitadeiras e seus porta-lumes.

[[v2-37-24]]

^<<v2-37-24,24>>^ De um talento de ouro puro fez tanto a ele como a todos os seus utensílios.

[[v2-37-25]]

^<<v2-37-25,25>>^ Fez então o altar do incenso de madeira de acácia. Um côvado^&#42;1^ era seu comprimento e um côvado sua largura, sendo quadrado, e dois côvados era sua altura. Seus chifres procediam dele.

[NOTE]
====
. Cerca de 44,5 cm.
====

[[v2-37-26]]

^<<v2-37-26,26>>^ Recobriu-o então de ouro puro, sua parte superior e seus lados ao redor, e seus chifres, e fez-lhe uma bordadura de ouro ao redor.

[[v2-37-27]]

^<<v2-37-27,27>>^ E fez-lhe duas argolas de ouro abaixo da sua bordadura em dois dos seus lados, em dois lados opostos dele, como suportes para os varais com que era carregado.

[[v2-37-28]]

^<<v2-37-28,28>>^ Depois fez os varais de madeira de acácia e os recobriu de ouro.

[[v2-37-29]]

^<<v2-37-29,29>>^ Fez adicionalmente o óleo sagrado de unção e o incenso puro, perfumado, obra de fabricante de ungüento.

'''

xref:002-exodo/002-exodo-036.adoc#v2-36-0[&#60; Capítulo Anterior] | <<v2-37-0,Topo>> | xref:002-exodo/002-exodo-038.adoc#v2-38-0[Próximo Capítulo &#62;]