include::./index.adoc[]

[[v2-40-0]]
=== Êxodo, 40
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v2-40-1]]

^<<v2-40-1,1>>^ Jeová falou então a Moisés, dizendo:

[[v2-40-2]]

^<<v2-40-2,2>>^ “No dia do primeiro mês, no primeiro do mês, deves erigir o tabernáculo da tenda de reunião.

[[v2-40-3]]

^<<v2-40-3,3>>^ E terás de colocar nele a arca do testemunho e vedar com a cortina a aproximação à Arca.

[[v2-40-4]]

^<<v2-40-4,4>>^ E terás de levar para dentro a mesa e pôr em ordem a sua disposição, e terás de levar para dentro o candelabro e acender suas lâmpadas.

[[v2-40-5]]

^<<v2-40-5,5>>^ E terás de pôr o altar de ouro para o incenso diante da arca do testemunho e pôr no lugar o reposteiro da entrada do tabernáculo.

[[v2-40-6]]

^<<v2-40-6,6>>^ “E terás de pôr o altar da oferta queimada diante da entrada do tabernáculo da tenda de reunião,

[[v2-40-7]]

^<<v2-40-7,7>>^ e terás de pôr a bacia entre a tenda de reunião e o altar, e pôr nela água.

[[v2-40-8]]

^<<v2-40-8,8>>^ E terás de colocar o pátio ao redor e terás de pendurar o reposteiro do portão do pátio.

[[v2-40-9]]

^<<v2-40-9,9>>^ E terás de tomar o óleo de unção e ungir o tabernáculo e tudo o que há nele, e terás de santificá-lo, bem como todos os seus utensílios, e assim se terá de tornar algo santo.

[[v2-40-10]]

^<<v2-40-10,10>>^ E terás de ungir o altar da oferta queimada e todos os seus utensílios, e terás de santificar o altar, e assim se terá de tornar um altar santíssimo.

[[v2-40-11]]

^<<v2-40-11,11>>^ E terás de ungir a bacia e seu suporte, e terás de santificá-la.

[[v2-40-12]]

^<<v2-40-12,12>>^ “Então terás de fazer chegar Arão e seus filhos perto da entrada da tenda de reunião e terás de lavá-los com água.

[[v2-40-13]]

^<<v2-40-13,13>>^ E terás de vestir Arão com as vestes sagradas, e terás de ungi-lo e santificá-lo, e assim ele terá de atuar para mim como sacerdote.

[[v2-40-14]]

^<<v2-40-14,14>>^ Depois farás chegar seus filhos e terás de vesti-los com vestes compridas.

[[v2-40-15]]

^<<v2-40-15,15>>^ E terás de ungi-los assim como ungiste seu pai, e assim eles terão de atuar para mim como sacerdotes, e sua unção terá de servir-lhes continuamente como sacerdócio por tempo indefinido nas suas gerações.”

[[v2-40-16]]

^<<v2-40-16,16>>^ E Moisés passou a fazer segundo tudo o que Jeová lhe mandara. Fez exatamente assim.

[[v2-40-17]]

^<<v2-40-17,17>>^ Concordemente, no primeiro mês, no segundo ano, no primeiro dia do mês, sucedeu que se erigiu o tabernáculo.

[[v2-40-18]]

^<<v2-40-18,18>>^ Quando Moisés passou a erigir o tabernáculo, ele foi assentar seus pedestais de encaixe e colocar suas armações de painel, e foi introduzir suas trancas e erigir suas colunas.

[[v2-40-19]]

^<<v2-40-19,19>>^ Depois estendeu a tenda sobre o tabernáculo e colocou-lhe por cima a cobertura da tenda, assim como Jeová mandara a Moisés.

[[v2-40-20]]

^<<v2-40-20,20>>^ Depois tomou o Testemunho e o pôs na Arca, e meteu os varais na Arca e pôs a tampa por cima da Arca.

[[v2-40-21]]

^<<v2-40-21,21>>^ Levou então a Arca para dentro do tabernáculo e pôs no lugar a cortina do reposteiro, e vedou a aproximação à arca do testemunho, assim como Jeová mandara a Moisés.

[[v2-40-22]]

^<<v2-40-22,22>>^ A seguir pôs a mesa na tenda de reunião, do lado setentrional do tabernáculo, fora da cortina,

[[v2-40-23]]

^<<v2-40-23,23>>^ e pôs em ordem a disposição dos pães sobre ela perante Jeová, assim como Jeová mandara a Moisés.

[[v2-40-24]]

^<<v2-40-24,24>>^ Então colocou o candelabro na tenda de reunião, defronte da mesa, do lado meridional^&#42;1^ do tabernáculo.

[NOTE]
====
. Lit.: “Negebe”.
====

[[v2-40-25]]

^<<v2-40-25,25>>^ Acendeu então as lâmpadas perante Jeová, assim como Jeová mandara a Moisés.

[[v2-40-26]]

^<<v2-40-26,26>>^ A seguir colocou o altar de ouro na tenda de reunião diante da cortina,

[[v2-40-27]]

^<<v2-40-27,27>>^ para fazer^&#42;1^ fumegar incenso perfumado sobre ele, assim como Jeová mandara a Moisés.

[NOTE]
====
. Ou “e começou a”.
====

[[v2-40-28]]

^<<v2-40-28,28>>^ Por fim pôs no lugar o reposteiro da entrada do tabernáculo.

[[v2-40-29]]

^<<v2-40-29,29>>^ E colocou o altar da oferta queimada à entrada do tabernáculo da tenda de reunião, para oferecer nele a oferta queimada e a oferta de cereais, assim como Jeová mandara a Moisés.

[[v2-40-30]]

^<<v2-40-30,30>>^ Então colocou a bacia entre a tenda de reunião e o altar e pôs água nela para a lavagem.

[[v2-40-31]]

^<<v2-40-31,31>>^ E Moisés, e Arão e seus filhos lavaram ali suas mãos e seus pés.

[[v2-40-32]]

^<<v2-40-32,32>>^ Lavavam-se quando entravam na tenda de reunião e quando se aproximavam do altar, assim como Jeová mandara a Moisés.

[[v2-40-33]]

^<<v2-40-33,33>>^ Por fim erigiu o pátio em volta do tabernáculo e do altar, e pendurou o reposteiro do portão do pátio.
Assim acabou Moisés a obra.

[[v2-40-34]]

^<<v2-40-34,34>>^ E a nuvem começou a cobrir a tenda de reunião e a glória de Jeová encheu o tabernáculo.

[[v2-40-35]]

^<<v2-40-35,35>>^ E Moisés não pôde entrar na tenda de reunião, porque a nuvem residia sobre ela e a glória de Jeová enchia o tabernáculo.

[[v2-40-36]]

^<<v2-40-36,36>>^ E quando a nuvem se elevava de cima do tabernáculo, os filhos de Israel levantavam acampamento em todas as suas etapas de viagem.

[[v2-40-37]]

^<<v2-40-37,37>>^ No entanto, se a nuvem não se elevava, então não levantavam acampamento até o dia em que se elevava.

[[v2-40-38]]

^<<v2-40-38,38>>^ Pois a nuvem de Jeová estava sobre o tabernáculo durante o dia e um fogo continuava sobre ele durante a noite, à vista de toda a casa de Israel, em todas as suas etapas de viagem.

'''

xref:002-exodo/002-exodo-039.adoc#v2-39-0[&#60; Capítulo Anterior] | <<v2-40-0,Topo>> | xref:003-levitico/003-levitico-001.adoc#v3-1-0[Próximo Capítulo &#62;]