include::./index.adoc[]

[[v2-34-0]]
=== Êxodo, 34
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v2-34-1]]

^<<v2-34-1,1>>^ Jeová disse então a Moisés: “Lavra para ti duas tábuas de pedra iguais às primeiras, e eu terei de escrever nas tábuas as palavras^&#42;1^ que apareceram nas primeiras tábuas que destroçaste.

[NOTE]
====
. Ou “ordens”.
====

[[v2-34-2]]

^<<v2-34-2,2>>^ E apronta-te para a manhã, visto que de manhã tens de subir ao monte Sinai e postar-te junto a mim, lá no cume do monte.

[[v2-34-3]]

^<<v2-34-3,3>>^ Mas ninguém pode subir contigo, nem tampouco se veja alguém mais em todo o monte. Ainda mais, nem rebanho nem manada devem pastar diante deste monte.”

[[v2-34-4]]

^<<v2-34-4,4>>^ De acordo com isso, Moisés lavrou duas tábuas de pedra iguais às primeiras, e levantou-se de manhã cedo e foi subir ao monte Sinai, assim como Jeová lhe mandara, e levava na mão as duas tábuas de pedra.

[[v2-34-5]]

^<<v2-34-5,5>>^ E Jeová passou a descer na nuvem e a pôr-se ali junto dele, e passou a declarar^&#42;1^ o nome de Jeová.

[NOTE]
====
. Ou “pregar”. Lit.: “invocar”.
====

[[v2-34-6]]

^<<v2-34-6,6>>^ E Jeová ia passando diante da sua face e declarando:^&#42;1^ “Jeová, Jeová, Deus^&#42;2^ misericordioso e clemente, vagaroso em irar-se e abundante em benevolência^&#42;3^ e em verdade,^&#42;4^

[NOTE]
====
. Lit.: “e invocando”.
. “Deus.” Hebr.: ’El; gr.: The·ós.
. Ou “amor leal”.
. Ou “fidelidade”.
====

[[v2-34-7]]

^<<v2-34-7,7>>^ preservando a benevolência para com milhares, perdoando o erro, e a transgressão, e o pecado, mas de modo algum isentará da punição, trazendo punição pelo erro dos pais sobre os filhos e sobre os netos, sobre a terceira geração e sobre a quarta geração.”^&#42;1^

[NOTE]
====
. Lit.: “até os terceiros e os quartos [gerados]”.
====

[[v2-34-8]]

^<<v2-34-8,8>>^ Moisés apressou-se imediatamente a inclinar-se para a terra e a prostrar-se.

[[v2-34-9]]

^<<v2-34-9,9>>^ Disse então: “Agora, se eu tiver achado favor aos teus olhos, ó Jeová,^&#42;1^ por favor, que Jeová^&#42;2^ vá junto no nosso meio, porque é um povo de dura cerviz, e deves perdoar nosso erro e nosso pecado, e tens de tomar-nos como a tua posse.”

[NOTE]
====
. Uma das 134 mudanças de YHWH para ’Adho·naí feitas pelos escribas. Veja Ap. 1B.
. Veja n. precedente.
====

[[v2-34-10]]

^<<v2-34-10,10>>^ Ele disse, por sua vez: “Eis que estou concluindo um pacto: Diante de todo o teu povo farei coisas maravilhosas que nunca foram criadas em toda a terra, nem entre todas as nações; e todo o povo no meio do qual estás há de ver o trabalho de Jeová, porque coisa atemorizante é o que faço contigo.

[[v2-34-11]]

^<<v2-34-11,11>>^ “No que se refere a ti, guarda o que hoje te ordeno. Eis que expulso diante de ti os amorreus, e os cananeus, e os hititas, e os perizeus, e os heveus, e os jebuseus.

[[v2-34-12]]

^<<v2-34-12,12>>^ Guarda-te de não concluíres nenhum pacto com os habitantes do país para o qual vais, para que isso não se mostre um laço no teu meio.

[[v2-34-13]]

^<<v2-34-13,13>>^ Mas deveis demolir seus altares e deveis destroçar suas colunas sagradas, e deveis decepar seus postes sagrados.^&#42;1^

[NOTE]
====
. Ou “suas axerás”.
====

[[v2-34-14]]

^<<v2-34-14,14>>^ Pois, não deves prostrar-te diante de qualquer outro deus,^&#42;1^ porque Jeová, cujo nome é Ciumento,^&#42;2^ é um Deus ciumento;^&#42;3^

[NOTE]
====
. “Diante de . . . deus.” Hebr.: le’él.
. Lit.: “Ciumento [é] seu nome.” Hebr.: Qan·ná’ shemóh.
. “Um Deus ciumento.” Ou “um Deus que exige devoção exclusiva”. Hebr.: ’El qan·ná’; gr.: The·ós ze·lo·tés. Veja 20:5 n.: “exclusiva”.
====

[[v2-34-15]]

^<<v2-34-15,15>>^ para que não concluas nenhum pacto com os habitantes do país, visto que certamente terão relações imorais^&#42;1^ com os seus deuses^&#42;2^ e oferecerão sacrifícios aos seus deuses, e alguém por certo te convidará e certamente comerás do seu sacrifício.

[NOTE]
====
. Ou “certamente cometerão fornicação”.
. “Seus deuses.” Hebr.: ’elo·heh·hém.
====

[[v2-34-16]]

^<<v2-34-16,16>>^ Então terás de tomar algumas das suas^&#42;1^ filhas para teus filhos, e suas filhas certamente terão relações imorais^&#42;2^ com os seus deuses e farão teus filhos ter relações imorais com os seus deuses.

[NOTE]
====
. Lit.: “sua”, mas em sentido coletivo.
. Lit.: “e [suas filhas] fornicarão”. Hebr.: weza·nú; gr.: kai ek·por·neú·so·sin; lat.: fú·e·rint for·ni·cá·tae.
====

[[v2-34-17]]

^<<v2-34-17,17>>^ “Não deves fazer para ti deuses-ídolos fundidos.

[[v2-34-18]]

^<<v2-34-18,18>>^ “Deves guardar a festividade dos pães não fermentados. Comerás pães não fermentados, assim como te mandei, por sete dias, no tempo designado no mês de abibe,^&#42;1^ porque foi no mês de abibe que saíste do Egito.

[NOTE]
====
. Veja 13:4 n.
====

[[v2-34-19]]

^<<v2-34-19,19>>^ “Tudo o que primeiro abrir a madre é meu, e quanto a todo o teu gado, todo macho primeiro nascido do touro e do ovídeo.

[[v2-34-20]]

^<<v2-34-20,20>>^ E o primeiro nascido dum jumento deves remir com um ovídeo. Mas, se não o remires, então terás de quebrar-lhe a nuca. Todo primogênito dos teus filhos deves remir. E eles não devem comparecer diante de mim de mãos vazias.

[[v2-34-21]]

^<<v2-34-21,21>>^ “Seis dias deves labutar,^&#42;1^ mas no sétimo dia guardarás o sábado.^&#42;2^ Guardarás o sábado no tempo da lavoura e no tempo da colheita.

[NOTE]
====
. Ou “prestar serviço”. Gr.: er·gaí.
. Ou “repousarás”.
====

[[v2-34-22]]

^<<v2-34-22,22>>^ “E realizarás a tua festividade das semanas^&#42;1^ com os primeiros frutos maduros da sega do trigo e a festividade do recolhimento^&#42;2^ na volta do ano.

[NOTE]
====
. Ou “Pentecostes”, 6 de sivã, o 50.º dia a partir de 16 de nisã. Veja Ap. 8B.
. Ou “colheita”.
====

[[v2-34-23]]

^<<v2-34-23,23>>^ “Três vezes no ano, todo macho teu deve comparecer diante do [verdadeiro] Senhor, Jeová,^&#42;1^ o Deus de Israel.

[NOTE]
====
. “Do [verdadeiro] Senhor, Jeová.” Hebr.: ha·’A·dhón Yehwáh; Vg: “o onipotente Senhor”. Veja Ap. 1H.
====

[[v2-34-24]]

^<<v2-34-24,24>>^ Pois desalojarei as nações de diante de ti e vou fazer espaçoso o teu território; e ninguém desejará a tua terra enquanto subires três vezes por ano para ver a face de Jeová, teu Deus.

[[v2-34-25]]

^<<v2-34-25,25>>^ “Não deves abater o sangue do meu sacrifício junto com o que é levedado. E o sacrifício da festividade da páscoa não deve ficar toda a noite até à manhã.

[[v2-34-26]]

^<<v2-34-26,26>>^ “Deves trazer à casa de Jeová, teu Deus, o melhor dos primeiros frutos maduros do teu solo.
“Não deves cozinhar o cabritinho no leite de sua mãe.”

[[v2-34-27]]

^<<v2-34-27,27>>^ E Jeová prosseguiu, dizendo a Moisés: “Escreve para ti estas palavras, porque é de acordo com estas palavras que deveras concluo um pacto contigo e com Israel.”

[[v2-34-28]]

^<<v2-34-28,28>>^ E ele continuou ali com Jeová quarenta dias e quarenta noites. Não comeu pão nem bebeu água. E ele^&#42;1^ passou a escrever nas tábuas as palavras do pacto, as Dez Palavras.^&#42;2^

[NOTE]
====
. “Ele.” Veja v. 1.
. “As Dez Palavras.” Hebr.: ‛asé·reth had·deva·rím; gr.: tous dé·ka ló·gous; isto é, as dez palavras de ordem, as dez coisas a fazer, o Decálogo ou os Dez Mandamentos. Veja De 4:13 n.
====

[[v2-34-29]]

^<<v2-34-29,29>>^ Então, quando Moisés desceu do Monte Sinai, sucedeu que as duas tábuas do Testemunho estavam na mão de Moisés quando desceu do monte, e Moisés não sabia que a pele da sua face emitia raios por ter falado com ele.

[[v2-34-30]]

^<<v2-34-30,30>>^ Quando Arão e todos os filhos de Israel chegaram a ver Moisés, ora, eis que a pele da sua face emitia raios e eles ficaram com medo de se aproximar dele.

[[v2-34-31]]

^<<v2-34-31,31>>^ E Moisés passou a chamá-los. Assim, Arão e todos os maiorais^&#42;1^ dentre a assembléia voltaram a ele e Moisés começou a falar-lhes.

[NOTE]
====
. Ou “nases”.
====

[[v2-34-32]]

^<<v2-34-32,32>>^ Só depois disso aproximaram-se dele todos os filhos de Israel, e ele começou a ordenar-lhes tudo o que Jeová lhe falara no monte Sinai.

[[v2-34-33]]

^<<v2-34-33,33>>^ Sempre que Moisés acabava de falar com eles, punha um véu sobre a sua face.

[[v2-34-34]]

^<<v2-34-34,34>>^ Mas quando Moisés entrava perante Jeová para falar com ele, tirava o véu até sair. E saía e falava aos filhos de Israel o que se lhe mandava.

[[v2-34-35]]

^<<v2-34-35,35>>^ E os filhos de Israel viram a face de Moisés, que a pele da face de Moisés emitia raios; e Moisés pôs o véu de volta sobre a sua face até entrar para falar com ele.

'''

xref:002-exodo/002-exodo-033.adoc#v2-33-0[&#60; Capítulo Anterior] | <<v2-34-0,Topo>> | xref:002-exodo/002-exodo-035.adoc#v2-35-0[Próximo Capítulo &#62;]