include::./index.adoc[]

[[v2-14-0]]
=== Êxodo, 14
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v2-14-1]]

^<<v2-14-1,1>>^ Jeová^&#42;1^ falou então a Moisés, dizendo:

[NOTE]
====
. Hebr.: Yeho·wáh. Veja Ap. 1A.
====

[[v2-14-2]]

^<<v2-14-2,2>>^ “Fala aos filhos de Israel que voltem e se acampem diante de Pi-Hairote, entre Migdol e o mar, à vista de Baal-Zefom. Deveis acampar-vos defronte dele, junto ao mar.

[[v2-14-3]]

^<<v2-14-3,3>>^ Faraó certamente dirá então com respeito aos filhos de Israel: ‘Estão vagueando em confusão pelo país. O ermo os encerrou.’

[[v2-14-4]]

^<<v2-14-4,4>>^ Assim, hei de deixar o coração de Faraó ficar obstinado e ele certamente irá no encalço deles, e eu obterei glória para mim por meio de Faraó e todas as suas forças militares; e os egípcios saberão certamente que eu sou Jeová.” Concordemente, fizeram exatamente assim.

[[v2-14-5]]

^<<v2-14-5,5>>^ Mais tarde foi comunicado ao rei do Egito que o povo tinha fugido. O coração de Faraó, bem como dos seus servos, mudou imediatamente para com o povo, de modo que disseram: “Que é que fizemos, despedindo Israel de trabalhar como escravos para nós?”

[[v2-14-6]]

^<<v2-14-6,6>>^ De modo que passou a aprontar seus carros de guerra e tomou consigo seu povo.

[[v2-14-7]]

^<<v2-14-7,7>>^ E passou a tomar seiscentos carros seletos e todos os outros carros do Egito, e guerreiros^&#42;1^ em cada um deles.

[NOTE]
====
. “E guerreiros.” Lit.: “e terceiros homens”. Hebr.: wesha·li·shím; gr.: tri·stá·tas. Embora os monumentos egípcios usualmente não o mostrem, num carro de guerra andavam três homens, um deles dirigindo os cavalos, enquanto os outros dois lutavam de cima do carro; também baixos-relevos assírios mostram um terceiro homem como portando armas ou um guarda-sol.
====

[[v2-14-8]]

^<<v2-14-8,8>>^ Assim Jeová^&#42;1^ deixou ficar obstinado o coração de Faraó, rei do Egito, e este foi no encalço dos filhos de Israel, enquanto os filhos de Israel saíam de mão erguida.

[NOTE]
====
. Hebr.: Yeho·wáh. Veja Ap. 1A.
====

[[v2-14-9]]

^<<v2-14-9,9>>^ E os egípcios foram no encalço deles, e todos os cavalos dos carros de Faraó, e os seus cavalarianos, e suas forças militares os alcançaram enquanto estavam acampados junto ao mar, junto a Pi-Hairote, à vista de Baal-Zefom.

[[v2-14-10]]

^<<v2-14-10,10>>^ Quando Faraó chegou perto, os filhos de Israel começaram a levantar os olhos e eis que os egípcios vinham marchando atrás deles; e os filhos de Israel ficaram muito amedrontados e começaram a clamar a Jeová.

[[v2-14-11]]

^<<v2-14-11,11>>^ E passaram a dizer a Moisés: “É porque não há nenhumas sepulturas no Egito que nos trouxeste para cá, para morrermos no ermo? Que é que nos fizeste, conduzindo-nos para fora do Egito?

[[v2-14-12]]

^<<v2-14-12,12>>^ Não foi esta a palavra que te falamos no Egito, dizendo: ‘Deixa-nos, para servirmos os egípcios’? Pois é melhor servirmos os egípcios do que morrermos no ermo.”

[[v2-14-13]]

^<<v2-14-13,13>>^ Moisés disse então ao povo: “Não tenhais medo. Mantende-vos firmes e vede a salvação da parte de Jeová, que ele realizará hoje para vós. Pois os egípcios que hoje deveras vedes, nunca mais vereis, não, nunca mais.

[[v2-14-14]]

^<<v2-14-14,14>>^ O próprio Jeová lutará por vós e vós mesmos ficareis calados.”

[[v2-14-15]]

^<<v2-14-15,15>>^ Jeová disse então a Moisés: “Por que persistes em clamar a mim? Fala aos filhos de Israel para que levantem acampamento.

[[v2-14-16]]

^<<v2-14-16,16>>^ Quanto a ti, ergue teu bastão e estende tua mão sobre o mar e parte-o, para que os filhos de Israel possam passar pelo meio do mar em terra seca.

[[v2-14-17]]

^<<v2-14-17,17>>^ Quanto a mim, eis que deixo os corações dos egípcios ficar obstinados para que entrem atrás deles e a fim de que eu obtenha glória para mim por meio de Faraó e todas as suas forças militares, seus carros de guerra e seus cavalarianos.

[[v2-14-18]]

^<<v2-14-18,18>>^ E os egípcios hão de saber que eu sou Jeová, quando eu obtiver glória para mim por meio de Faraó, seus carros de guerra e seus cavalarianos.”

[[v2-14-19]]

^<<v2-14-19,19>>^ Então o anjo do [verdadeiro] Deus, que ia na frente do acampamento de Israel, afastou-se e foi para a sua retaguarda, e a coluna de nuvem afastou-se da sua vanguarda e pôs-se na retaguarda deles.

[[v2-14-20]]

^<<v2-14-20,20>>^ Assim veio a estar entre o acampamento dos egípcios e o acampamento de Israel. Dum lado mostrou-se uma nuvem com escuridão. Do outro lado iluminava a noite. E este grupo não chegava perto daquele grupo durante toda a noite.

[[v2-14-21]]

^<<v2-14-21,21>>^ Moisés estendeu então a mão sobre o mar; e Jeová começou a fazer o mar retroceder por meio dum forte vento oriental, durante toda a noite, e a converter o leito do mar em solo seco, e as águas foram partidas.

[[v2-14-22]]

^<<v2-14-22,22>>^ Por fim, os filhos de Israel passaram pelo meio do mar em terra seca, enquanto as águas eram para eles como muralha à sua direita e à sua esquerda.

[[v2-14-23]]

^<<v2-14-23,23>>^ E os egípcios foram no encalço deles, e todos os cavalos de Faraó, seus carros de guerra e seus cavalarianos começaram a entrar atrás deles no meio do mar.

[[v2-14-24]]

^<<v2-14-24,24>>^ E sucedeu, durante a vigília da madrugada,^&#42;1^ que Jeová começou a olhar para o acampamento dos egípcios, desde a coluna de fogo e de nuvem, e passou a lançar o acampamento dos egípcios em confusão.

[NOTE]
====
. A terceira e última vigília segundo os hebreus, aproximadamente das 2 às 6 horas da manhã.
====

[[v2-14-25]]

^<<v2-14-25,25>>^ E ele desprendia as rodas dos seus carros, de modo que os dirigiam com dificuldade; e os egípcios começaram a dizer: “Fujamos de qualquer contato com Israel, porque Jeová certamente está lutando por eles contra os egípcios.”

[[v2-14-26]]

^<<v2-14-26,26>>^ Finalmente, Jeová disse a Moisés: “Estende tua mão sobre o mar, para que as águas voltem sobre os egípcios, sobre seus carros de guerra e seus cavalarianos.”

[[v2-14-27]]

^<<v2-14-27,27>>^ Moisés estendeu imediatamente a mão sobre o mar, e, ao amanhecer, o mar começou a voltar ao seu estado normal. Nesse ínterim, os egípcios fugiam do seu encontro com ele, mas Jeová desembaraçou-se dos egípcios no meio do mar.

[[v2-14-28]]

^<<v2-14-28,28>>^ E as águas voltavam. Por fim cobriam os carros de guerra e os cavalarianos, pertencentes a todas as forças militares de Faraó e que haviam entrado no mar atrás deles. Nem mesmo um só deles se deixou sobrar.

[[v2-14-29]]

^<<v2-14-29,29>>^ Quanto aos filhos de Israel, andaram em terra seca no meio do leito do mar, e as águas foram para eles como muralha à sua direita e à sua esquerda.

[[v2-14-30]]

^<<v2-14-30,30>>^ Assim, naquele dia, Jeová salvou Israel da mão dos egípcios e Israel chegou a ver os egípcios mortos à beira do mar.

[[v2-14-31]]

^<<v2-14-31,31>>^ Israel chegou também a ver a grande mão que Jeová pôs em ação contra os egípcios; e o povo começou a temer a Jeová e a ter fé em Jeová e em Moisés, seu servo.

'''

xref:002-exodo/002-exodo-013.adoc#v2-13-0[&#60; Capítulo Anterior] | <<v2-14-0,Topo>> | xref:002-exodo/002-exodo-015.adoc#v2-15-0[Próximo Capítulo &#62;]