include::./index.adoc[]

[[v2-6-0]]
=== Êxodo, 6
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v2-6-1]]

^<<v2-6-1,1>>^ Jeová disse então a Moisés: “Agora verás o que farei a Faraó, pois, por causa duma forte mão ele os mandará embora e por causa duma forte mão os expulsará de sua terra.”

[[v2-6-2]]

^<<v2-6-2,2>>^ E Deus^&#42;1^ prosseguiu, falando a Moisés e dizendo-lhe: “Eu sou Jeová.

[NOTE]
====
. “Deus”, MLXX; SamSyVg: “Jeová”.
====

[[v2-6-3]]

^<<v2-6-3,3>>^ E eu costumava aparecer a Abraão, a Isaque e a Jacó como Deus Todo-poderoso,^&#42;1^ mas com respeito ao meu nome Jeová^&#42;2^ não me dei a conhecer a eles.^&#42;3^

[NOTE]
====
. “Como Deus Todo-poderoso.” Hebr.: be’Él Shad·daí; lat.: in Dé·o o·mni·po·tén·te (onipotente).
. “Mas com respeito ao meu nome Jeová [יהוה, YHWH].” Hebr.: u·she·mí Yehwáh; lat.: et nó·men mé·um A·do·ná·i.
. Ou “também, com respeito ao meu nome Jeová não me dei a conhecer a eles?” James Washington Watts (1977), “por meu nome Yahweh eu não me fiz cabalmente compreensível a eles”.
====

[[v2-6-4]]

^<<v2-6-4,4>>^ E estabeleci também o meu pacto com eles, para dar-lhes a terra de Canaã, a terra das suas residências como forasteiros em que residiram.

[[v2-6-5]]

^<<v2-6-5,5>>^ E eu é que tenho ouvido os gemidos dos filhos de Israel, que os egípcios escravizaram, e lembro-me do meu pacto.

[[v2-6-6]]

^<<v2-6-6,6>>^ “Portanto, dize aos filhos de Israel: ‘Eu sou Jeová, e certamente vos farei sair de debaixo dos fardos dos egípcios e vos livrarei da sua escravidão, e deveras vos reivindicarei com braço estendido e com grandes julgamentos.

[[v2-6-7]]

^<<v2-6-7,7>>^ E certamente vos tomarei para mim como um povo^&#42;1^ e deveras mostrarei ser Deus^&#42;2^ para vós;^&#42;3^ e sabereis certamente que eu sou Jeová, vosso Deus, que vos faz sair de debaixo dos fardos do Egito.

[NOTE]
====
. Ou “tomar-vos como o meu povo”.
. Lit.: “como Deus”. Hebr.: lE’·lo·hím; gr.: The·ós.
. Ou “mostrarei ser vosso Deus”.
====

[[v2-6-8]]

^<<v2-6-8,8>>^ E hei de levar-vos à terra a respeito da qual levantei minha mão em juramento para dá-la a Abraão, Isaque e Jacó; e hei de dá-la a vós como possessão. Eu sou Jeová.’”

[[v2-6-9]]

^<<v2-6-9,9>>^ Posteriormente, Moisés falou neste sentido aos filhos de Israel, mas eles, de desânimo^&#42;1^ e devido à dura escravidão, não escutaram Moisés.

[NOTE]
====
. Lit.: “curteza de espírito [hebr.: rú·ahh]”.
====

[[v2-6-10]]

^<<v2-6-10,10>>^ Jeová falou então a Moisés, dizendo:

[[v2-6-11]]

^<<v2-6-11,11>>^ “Entra, fala a Faraó, rei do Egito, para que mande os filhos de Israel para fora da sua terra.”

[[v2-6-12]]

^<<v2-6-12,12>>^ No entanto, Moisés falou perante Jeová, dizendo: “Eis que os filhos de Israel não me escutaram; e como é que Faraó me irá escutar, visto que sou de lábios incircuncisos?”^&#42;1^

[NOTE]
====
. “Lábios incircuncisos”, como se os lábios tivessem prepúcio sobre eles, sendo assim longos e grossos demais para proferir palavras com facilidade.
====

[[v2-6-13]]

^<<v2-6-13,13>>^ Mas, Jeová continuou a falar a Moisés e a Arão, e a dar por meio deles ordens aos filhos de Israel e a Faraó, rei do Egito, para fazer os filhos de Israel sair da terra do Egito.

[[v2-6-14]]

^<<v2-6-14,14>>^ Estes eram os cabeças da casa de seus pais: Os filhos de Rubem, primogênito de Israel, eram Anoque e Palu, Esrom e Carmi. Estas eram as famílias de Rubem.

[[v2-6-15]]

^<<v2-6-15,15>>^ E os filhos de Simeão eram Jemuel, e Jamim, e Oade, e Jaquim, e Zoar, e Saul, filho duma mulher cananéia. Estas eram as famílias de Simeão.

[[v2-6-16]]

^<<v2-6-16,16>>^ E estes eram os nomes dos filhos de Levi, segundo as suas linhagens: Gérson, e Coate, e Merari. E os anos da vida de Levi foram cento e trinta e sete anos.

[[v2-6-17]]

^<<v2-6-17,17>>^ Os filhos de Gérson eram Libni e Simei, segundo as suas famílias.

[[v2-6-18]]

^<<v2-6-18,18>>^ E os filhos de Coate eram Anrão, e Izar, e Hébron, e Uziel. E os anos da vida de Coate foram cento e trinta e três anos.

[[v2-6-19]]

^<<v2-6-19,19>>^ E os filhos de Merari eram Mali e Musi.
Estas eram as famílias dos levitas, segundo as suas linhagens.

[[v2-6-20]]

^<<v2-6-20,20>>^ Ora, Anrão tomou Joquebede, irmã de seu pai, por sua esposa. Mais tarde ela lhe deu à luz Arão e Moisés. E os anos da vida de Anrão foram cento e trinta e sete anos.

[[v2-6-21]]

^<<v2-6-21,21>>^ E os filhos de Izar eram Corá, e Nefegue, e Zicri.

[[v2-6-22]]

^<<v2-6-22,22>>^ E os filhos de Uziel eram Misael, e Elzafã, e Sitri.

[[v2-6-23]]

^<<v2-6-23,23>>^ Arão tomou então Eliseba, filha de Aminadabe, irmã de Nasom, por sua esposa. Mais tarde ela lhe deu à luz Nadabe e Abiú, Eleazar e Itamar.

[[v2-6-24]]

^<<v2-6-24,24>>^ E os filhos de Corá eram Assir, e Elcana, e Abiasafe. Estas eram as famílias dos coraítas.

[[v2-6-25]]

^<<v2-6-25,25>>^ E Eleazar, filho de Arão, tomou para si uma das filhas de Putiel por sua esposa. Mais tarde ela lhe deu à luz Finéias.
Estes são os cabeças dos pais dos levitas, segundo as suas famílias.

[[v2-6-26]]

^<<v2-6-26,26>>^ Este é o Arão e o Moisés a quem Jeová disse: “Fazei os filhos de Israel sair da terra do Egito, segundo os seus exércitos.”

[[v2-6-27]]

^<<v2-6-27,27>>^ Eles eram os que falavam a Faraó, rei do Egito, para fazer os filhos de Israel sair do Egito. Este é o Moisés e o Arão.

[[v2-6-28]]

^<<v2-6-28,28>>^ E sucedeu, no dia em que Jeová falou a Moisés, na terra do Egito,

[[v2-6-29]]

^<<v2-6-29,29>>^ que Jeová prosseguiu falando a Moisés, dizendo: “Eu sou Jeová. Fala a Faraó, rei do Egito, tudo o que eu te falar.”

[[v2-6-30]]

^<<v2-6-30,30>>^ Moisés disse então perante Jeová: “Eis que sou de lábios incircuncisos; portanto, como é que me escutará Faraó?”

'''

xref:002-exodo/002-exodo-005.adoc#v2-5-0[&#60; Capítulo Anterior] | <<v2-6-0,Topo>> | xref:002-exodo/002-exodo-007.adoc#v2-7-0[Próximo Capítulo &#62;]