include::./index.adoc[]

[[v2-15-0]]
=== Êxodo, 15
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v2-15-1]]

^<<v2-15-1,1>>^ Naquele tempo, Moisés e os filhos de Israel passaram a cantar este cântico a Jeová e a dizer o seguinte:
“Cante eu a Jeová, porque ficou grandemente enaltecido.
Lançou no mar o cavalo e seu cavaleiro.

[[v2-15-2]]

^<<v2-15-2,2>>^ Minha força e [meu] poder^&#42;1^ é Jah,^&#42;2^ visto que ele me é por salvação.
Este é meu Deus, e eu o elogiarei; o Deus de meu pai, e eu o exaltarei.

[NOTE]
====
. “E [meu] poder.” Possivelmente: “e [minha] melodia”. Hebr.: wezim·ráth; Sam e três mss. hebr. acrescentam “meu”; lat.: laus mé·a, “meu louvor”.
. “Jah.” Hebr.: Yah; esta é a primeira ocorrência desta abreviatura do nome “Jeová”. Veja Ap. 1A.
====

[[v2-15-3]]

^<<v2-15-3,3>>^ Jeová é pessoa varonil de guerra. Jeová é o seu nome.

[[v2-15-4]]

^<<v2-15-4,4>>^ Atirou no mar os carros de Faraó e suas forças militares,
E a elite dos seus guerreiros foi afundada no Mar Vermelho.

[[v2-15-5]]

^<<v2-15-5,5>>^ As águas empoladas^&#42;1^ passaram a cobri-los; como pedra desceram às profundidades.

[NOTE]
====
. “As águas empoladas.” Hebr.: teho·móth; lat.: a·býs·si. Veja Gên 1:2 n.: “profundeza”.
====

[[v2-15-6]]

^<<v2-15-6,6>>^ Tua direita, ó Jeová, mostra-se poderosa em capacidade,
Tua direita, ó Jeová, pode despedaçar o inimigo.

[[v2-15-7]]

^<<v2-15-7,7>>^ E na abundância da tua superioridade podes derrubar os que se levantam contra ti;
Envias a tua ira ardente, ela os consome como restolho.

[[v2-15-8]]

^<<v2-15-8,8>>^ E pelo sopro^&#42;1^ das tuas narinas^&#42;2^ amontoaram-se as águas;
Pararam como dique de enchentes;
As águas empoladas solidificaram-se no coração do mar.

[NOTE]
====
. “E pelo sopro.” Hebr.: u·verú·ahh; gr.: pneú·ma·tos. Veja Gên 1:2 n.: “ativa”.
. Ou “ira”.
====

[[v2-15-9]]

^<<v2-15-9,9>>^ O inimigo disse: ‘Perseguirei! Alcançarei!
Repartirei os despojos! Minha alma se encherá deles!
Puxarei da minha espada! Minha mão os desalojará!’^&#42;1^

[NOTE]
====
. Ou “os desapossará”.
====

[[v2-15-10]]

^<<v2-15-10,10>>^ Sopraste com o teu fôlego, o mar os cobriu;
Afundaram como chumbo em águas majestosas.

[[v2-15-11]]

^<<v2-15-11,11>>^ Quem entre os deuses^&#42;1^ é semelhante a ti, ó Jeová?
Quem é semelhante a ti, mostrando-se poderoso em santidade?
Aquele a ser temido com cânticos de louvor, Aquele que faz maravilhas.

[NOTE]
====
. “Entre os deuses.” Hebr.: ba·’e·lím, pl. de ’el.
====

[[v2-15-12]]

^<<v2-15-12,12>>^ Estendeste a tua direita, a terra passou a engoli-los.

[[v2-15-13]]

^<<v2-15-13,13>>^ Tu, na tua benevolência,^&#42;1^ guiaste o povo que recuperaste;^&#42;2^
Tu, na tua força, certamente os conduzirás ao teu santo lugar de permanência.

[NOTE]
====
. Ou “no teu amor leal”.
. Ou “recobraste; remiste”.
====

[[v2-15-14]]

^<<v2-15-14,14>>^ Os povos terão^&#42;1^ de ouvir, ficarão agitados;
Dores de parto terão de apoderar-se dos habitantes da Filístia.

[NOTE]
====
. Ou “certamente terão”.
====

[[v2-15-15]]

^<<v2-15-15,15>>^ Nesse tempo os xeques de Edom ficarão deveras perturbados;
Quanto aos déspotas de Moabe, apoderar-se-á deles o tremor.
Todos os habitantes de Canaã deveras esmorecerão.

[[v2-15-16]]

^<<v2-15-16,16>>^ Horror e pavor cairá sobre eles.
Por causa da magnitude do teu braço ficarão imóveis feito pedra,
Até que passe teu povo, ó Jeová,
Até que passe o povo que produziste.^&#42;1^

[NOTE]
====
. Ou “adquiriste”.
====

[[v2-15-17]]

^<<v2-15-17,17>>^ Tu os trarás e plantarás no monte da tua herança,^&#42;1^
Lugar estabelecido^&#42;2^ que aprontaste para habitares [nele], ó Jeová,
Um santuário, ó Jeová,^&#42;3^ que as tuas mãos estabeleceram.

[NOTE]
====
. Ou “possessão”.
. Ou “local”.
. Uma das 134 mudanças de YHWH para ’Adho·naí feitas pelos escribas. Veja Ap. 1B.
====

[[v2-15-18]]

^<<v2-15-18,18>>^ Jeová reinará por tempo indefinido, para todo o sempre.

[[v2-15-19]]

^<<v2-15-19,19>>^ Quando os cavalos de Faraó com seus carros de guerra e seus cavalarianos entraram no mar,
Então Jeová fez retornar sobre eles as águas do mar,
Ao passo que os filhos de Israel andaram em terra seca pelo meio do mar.”

[[v2-15-20]]

^<<v2-15-20,20>>^ E Miriã, a profetisa, irmã de Arão, passou a tomar um pandeiro na mão; e todas as mulheres começaram a sair com ela com pandeiros e em danças.^&#42;1^

[NOTE]
====
. Ou “danças de roda”.
====

[[v2-15-21]]

^<<v2-15-21,21>>^ E Miriã respondia aos homens:^&#42;1^
“Cantai^&#42;2^ a Jeová, pois ele ficou grandemente enaltecido.
Lançou no mar o cavalo e seu cavaleiro.”

[NOTE]
====
. “Aos homens.” Lit.: “a eles”, hebr. masc.
. “Cantai”, M; LXXVg: “Cantemos.”
====

[[v2-15-22]]

^<<v2-15-22,22>>^ Mais tarde, Moisés fez Israel partir do Mar Vermelho e eles foram ao ermo de Sur, e marcharam por três dias no ermo, mas não acharam água.

[[v2-15-23]]

^<<v2-15-23,23>>^ Afinal chegaram a Mara, mas não puderam beber a água de Mara, porque era amarga. É por isso que ele o chamou pelo nome de Mara.^&#42;1^

[NOTE]
====
. Significando “Amargura”.
====

[[v2-15-24]]

^<<v2-15-24,24>>^ E o povo começou a resmungar contra Moisés, dizendo: “O que havemos de beber?”

[[v2-15-25]]

^<<v2-15-25,25>>^ Ele clamou então a Jeová. Portanto, Jeová o dirigiu a uma árvore, e ele a lançou na água e a água se tornou doce.
Ali Ele lhes^&#42;1^ estabeleceu um regulamento e um caso para julgamento, e ali os pôs à prova.

[NOTE]
====
. “Lhes”, referindo-se “ao povo”. Lit.: “lhe”.
====

[[v2-15-26]]

^<<v2-15-26,26>>^ E prosseguiu, dizendo: “Se escutares estritamente a voz de Jeová, teu Deus, e fizeres o que é direito aos seus olhos, e deveras deres ouvido aos seus mandamentos e guardares todos os seus regulamentos, não porei sobre ti nenhuma das enfermidades que pus sobre os egípcios; porque eu sou Jeová, quem te sara.”

[[v2-15-27]]

^<<v2-15-27,27>>^ Depois chegaram a Elim, onde havia doze fontes de água e setenta palmeiras. De modo que foram acampar-se ali junto à água.

'''

xref:002-exodo/002-exodo-014.adoc#v2-14-0[&#60; Capítulo Anterior] | <<v2-15-0,Topo>> | xref:002-exodo/002-exodo-016.adoc#v2-16-0[Próximo Capítulo &#62;]