include::./index.adoc[]

[[v2-26-0]]
=== Êxodo, 26
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v2-26-1]]

^<<v2-26-1,1>>^ “E o tabernáculo^&#42;1^ deves fazer de dez panos de tenda, de linho fino retorcido, e de linha azul, e de lã tingida de roxo, e de fibras carmíneas. Deves fazê-los com querubins, trabalho de bordador.

[NOTE]
====
. Ou “residência”.
====

[[v2-26-2]]

^<<v2-26-2,2>>^ O comprimento de cada pano de tenda é de vinte e oito côvados e a largura de cada pano de tenda é de quatro côvados. Há uma só medida para todos os panos de tenda.

[[v2-26-3]]

^<<v2-26-3,3>>^ Cinco panos de tenda devem formar uma série, sendo um unido ao outro, e cinco panos de tenda, outra série, sendo um unido ao outro.

[[v2-26-4]]

^<<v2-26-4,4>>^ E tens de fazer presilhas de linha azul na beira de um pano de tenda, no fim da série; e deves fazer o mesmo na beira do mais extremo pano de tenda, no outro ponto de junção.

[[v2-26-5]]

^<<v2-26-5,5>>^ Farás cinqüenta presilhas num pano de tenda e farás cinqüenta presilhas na extremidade do pano de tenda que está no outro ponto de junção, as presilhas estando contrapostas umas às outras.

[[v2-26-6]]

^<<v2-26-6,6>>^ E tens de fazer cinqüenta colchetes de ouro e unir os panos de tenda um ao outro por meio dos colchetes, e tem de tornar-se um só tabernáculo.

[[v2-26-7]]

^<<v2-26-7,7>>^ “E tens de fazer panos de pêlos de cabra para a tenda sobre o tabernáculo. Farás onze panos de tenda.

[[v2-26-8]]

^<<v2-26-8,8>>^ O comprimento de cada pano de tenda é de trinta côvados e a largura de cada pano de tenda é de quatro côvados. Há uma só medida para os onze panos de tenda.

[[v2-26-9]]

^<<v2-26-9,9>>^ E tens de unir cinco panos de tenda entre si e seis panos de tenda entre si, e tens de dobrar o sexto pano de tenda na parte dianteira da tenda.

[[v2-26-10]]

^<<v2-26-10,10>>^ E tens de fazer cinqüenta presilhas na beira de um pano de tenda, no mais extremo da série, e cinqüenta presilhas na beira do pano de tenda no outro ponto de junção.

[[v2-26-11]]

^<<v2-26-11,11>>^ E tens de fazer cinqüenta colchetes de cobre e pôr os colchetes nas presilhas e unir a tenda, e ela tem de se tornar uma só.

[[v2-26-12]]

^<<v2-26-12,12>>^ E o que sobrar dos panos da tenda ficará como excedente. Metade do pano de tenda que sobrar deve ficar pendendo na parte posterior do tabernáculo.

[[v2-26-13]]

^<<v2-26-13,13>>^ E o côvado deste lado e o côvado daquele lado no que sobrar no comprimento dos panos da tenda ficará como excedente nos lados do tabernáculo, para cobri-lo deste lado e daquele lado.

[[v2-26-14]]

^<<v2-26-14,14>>^ “E tens de fazer para a tenda uma cobertura de peles de carneiros tingidas de vermelho e uma cobertura de peles de focas por cima.

[[v2-26-15]]

^<<v2-26-15,15>>^ “E as armações de painel^&#42;1^ para o tabernáculo tens de fazer de madeira de acácia, postas em pé.

[NOTE]
====
. “Armações de painel”, em vez de tábuas, as quais teriam sido de madeira sólida, e, por isso, difíceis de manejar, por causa do seu tamanho e de seu peso.
====

[[v2-26-16]]

^<<v2-26-16,16>>^ Dez côvados é o comprimento de uma armação de painel e um côvado e meio é a largura de cada armação de painel.

[[v2-26-17]]

^<<v2-26-17,17>>^ Cada armação de painel tem duas espigas unidas uma à outra. É assim que farás com todas as armações de painel do tabernáculo.

[[v2-26-18]]

^<<v2-26-18,18>>^ E tens de fazer as armações de painel para o tabernáculo, vinte armações de painel para o lado do Negebe, o meridional.

[[v2-26-19]]

^<<v2-26-19,19>>^ “E farás quarenta pedestais de encaixe de prata, sob as vinte armações de painel; dois pedestais de encaixe sob uma armação de painel com as suas duas espigas e dois pedestais de encaixe sob a outra armação de painel com as suas duas espigas.

[[v2-26-20]]

^<<v2-26-20,20>>^ E para o outro lado do tabernáculo, o lado setentrional, vinte armações de painel

[[v2-26-21]]

^<<v2-26-21,21>>^ e seus quarenta pedestais de encaixe de prata, dois pedestais de encaixe sob uma armação de painel e dois pedestais de encaixe sob a outra armação de painel.

[[v2-26-22]]

^<<v2-26-22,22>>^ E para os fundos do tabernáculo, ao oeste, farás seis armações de painel.

[[v2-26-23]]

^<<v2-26-23,23>>^ E farás duas armações de painel como escoras de esquina do tabernáculo nas suas duas partes dos fundos.

[[v2-26-24]]

^<<v2-26-24,24>>^ E devem ser duplicadas na parte de baixo e ambas devem ser duplicadas até o topo de cada uma na primeira argola. É assim que deve ser para as duas. Servirão de duas escoras de esquina.

[[v2-26-25]]

^<<v2-26-25,25>>^ E tem de haver oito armações de painel e seus pedestais de encaixe de prata, dezesseis pedestais, dois pedestais de encaixe sob uma armação de painel e dois pedestais de encaixe sob a outra armação de painel.

[[v2-26-26]]

^<<v2-26-26,26>>^ “E tens de fazer trancas de madeira de acácia, cinco para as armações de painel de um lado do tabernáculo

[[v2-26-27]]

^<<v2-26-27,27>>^ e cinco trancas para as armações de painel do outro lado do tabernáculo, e cinco trancas para as armações de painel do lado ocidental do tabernáculo, para as duas partes dos fundos.

[[v2-26-28]]

^<<v2-26-28,28>>^ E a tranca do meio, no centro das armações de painel, está passando de uma extremidade à outra extremidade.

[[v2-26-29]]

^<<v2-26-29,29>>^ “E recobrirás de ouro as armações de painel e farás de ouro as suas argolas como suportes para as trancas; e as trancas tens de recobrir de ouro.

[[v2-26-30]]

^<<v2-26-30,30>>^ E tens de erigir o tabernáculo segundo o seu plano que te foi mostrado no monte.

[[v2-26-31]]

^<<v2-26-31,31>>^ “E tens de fazer uma cortina de linha azul, e de lã tingida de roxo, e de fibras carmíneas, e de linho fino retorcido. Ele a fará com querubins, trabalho de bordador.

[[v2-26-32]]

^<<v2-26-32,32>>^ E tens de pô-la em quatro colunas de acácia, recobertas de ouro. Seus pinos são de ouro. Estão sobre quatro pedestais de encaixe de prata.

[[v2-26-33]]

^<<v2-26-33,33>>^ E tens de pôr a cortina sob os colchetes e levar a arca do testemunho para dentro da cortina; e a cortina tem de fazer para vós uma separação entre o Santo e o Santíssimo.^&#42;1^

[NOTE]
====
. Ou “o Santo de Santos”. Lit.: “Santo dos Santos”. Hebr.: Qó·dhesh haq·Qodha·shím.
====

[[v2-26-34]]

^<<v2-26-34,34>>^ E tens de pôr a tampa sobre a arca do testemunho no Santíssimo.

[[v2-26-35]]

^<<v2-26-35,35>>^ “E tens de colocar a mesa fora da cortina, e o candelabro defronte da mesa, do lado meridional do tabernáculo; e porás a mesa do lado setentrional.

[[v2-26-36]]

^<<v2-26-36,36>>^ E para a entrada da tenda tens de fazer um reposteiro de linha azul, e de lã tingida de roxo, e de fibras carmíneas, e de linho fino retorcido, trabalho de tecelão.

[[v2-26-37]]

^<<v2-26-37,37>>^ E para o reposteiro tens de fazer cinco colunas de acácia e recobri-las de ouro. Seus pinos são de ouro. E tens de fundir para elas cinco pedestais de encaixe de cobre.

'''

xref:002-exodo/002-exodo-025.adoc#v2-25-0[&#60; Capítulo Anterior] | <<v2-26-0,Topo>> | xref:002-exodo/002-exodo-027.adoc#v2-27-0[Próximo Capítulo &#62;]