include::./index.adoc[]

[[v2-4-0]]
=== Êxodo, 4
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v2-4-1]]

^<<v2-4-1,1>>^ No entanto, Moisés disse em resposta: “Mas, suponhamos que não me acreditem e não escutem a minha voz, pois irão dizer: ‘Jeová não te apareceu.’”

[[v2-4-2]]

^<<v2-4-2,2>>^ Jeová disse-lhe então: “Que é isso na tua mão?” ao que ele disse: “Um bastão.”

[[v2-4-3]]

^<<v2-4-3,3>>^ Disse-lhe, pois: “Lança-o na terra.” De modo que o lançou na terra e ele se tornou uma serpente; e Moisés começou a fugir dela.

[[v2-4-4]]

^<<v2-4-4,4>>^ Jeová disse então a Moisés: “Estende tua mão e segura-a pela cauda.” De modo que estendeu sua mão e a segurou, e ela se tornou um bastão na palma da sua mão.

[[v2-4-5]]

^<<v2-4-5,5>>^ “A fim de que”, conforme disse, “eles acreditem que te apareceu Jeová, o Deus de seus antepassados, o Deus de Abraão, o Deus de Isaque e o Deus de Jacó”.

[[v2-4-6]]

^<<v2-4-6,6>>^ Jeová disse-lhe então mais uma vez: “Por favor, mete tua mão na dobra superior da tua roupa.” De modo que meteu sua mão na dobra superior da sua roupa. Quando a retirou, ora, eis que sua mão estava atacada de lepra semelhante à neve!

[[v2-4-7]]

^<<v2-4-7,7>>^ Depois disse: “Retorna tua mão à dobra superior da tua roupa.” De modo que retornou sua mão à dobra superior da sua roupa. Quando a retirou da dobra superior da sua roupa, ora, eis que se restabelecera igual ao resto da sua carne!

[[v2-4-8]]

^<<v2-4-8,8>>^ “E tem de dar-se que”, conforme disse, “se não te acreditarem e não escutarem a voz do primeiro sinal, então certamente acreditarão na voz do sinal posterior.

[[v2-4-9]]

^<<v2-4-9,9>>^ Contudo, tem de dar-se que, se não acreditarem nem mesmo nestes dois sinais e não escutarem a tua voz, então terás de tomar água do rio Nilo e derramá-la na terra seca; e a água que tomarás do rio Nilo certamente se tornará, sim, deveras se tornará sangue em terra seca.”

[[v2-4-10]]

^<<v2-4-10,10>>^ Moisés disse então a Jeová: “Perdão, Jeová,^&#42;1^ mas eu não sou orador fluente, nem desde ontem, nem desde antes, nem desde que falaste a teu servo, pois sou vagaroso de boca e vagaroso de língua.”

[NOTE]
====
. Uma das 134 mudanças de YHWH para ’Adho·naí feitas pelos escribas. Veja Ap. 1B.
====

[[v2-4-11]]

^<<v2-4-11,11>>^ A isso Jeová lhe disse: “Quem designou a boca ao homem ou quem designa o mudo, ou o surdo, ou o de vista clara, ou o cego? Não sou eu, Jeová?

[[v2-4-12]]

^<<v2-4-12,12>>^ Agora, pois, vai, e eu mesmo mostrarei estar com a tua boca e hei de ensinar-te o que deves dizer.”

[[v2-4-13]]

^<<v2-4-13,13>>^ Mas ele disse: “Perdão, Jeová,^&#42;1^ mas, por favor, envia pela mão daquele a quem hás de enviar.”

[NOTE]
====
. Veja v. 10 n.
====

[[v2-4-14]]

^<<v2-4-14,14>>^ Acendeu-se então a ira de Jeová contra Moisés e ele disse: “Não é Arão, o levita, teu irmão? Sei deveras que ele pode realmente falar. E além disso, eis que está saindo ao teu encontro. Ao ver-te, certamente se alegrará no seu coração.

[[v2-4-15]]

^<<v2-4-15,15>>^ E tens de falar-lhe e pôr-lhe as palavras na boca; e eu mesmo mostrarei estar com a tua boca e com a sua boca, e hei de ensinar-vos o que deveis fazer.

[[v2-4-16]]

^<<v2-4-16,16>>^ E ele tem de falar por ti ao povo; e tem de dar-se que ele te servirá de boca e tu lhe servirás de Deus.^&#42;1^

[NOTE]
====
. “De Deus.” Hebr.: le’·lo·hím, pl.; gr.: the·ón; lat.: Dé·um.
====

[[v2-4-17]]

^<<v2-4-17,17>>^ E tomarás este bastão na tua mão, para realizar com ele os sinais.”

[[v2-4-18]]

^<<v2-4-18,18>>^ Concordemente, Moisés foi e voltou a Jetro,^&#42;1^ seu sogro, e disse-lhe: “Por favor, quero ir e voltar aos meus irmãos que estão no Egito, para ver se ainda vivem.” Portanto, Jetro disse a Moisés: “Vai em paz.”

[NOTE]
====
. Hebr.: Yé·ther.
====

[[v2-4-19]]

^<<v2-4-19,19>>^ Depois, Jeová disse a Moisés em Midiã: “Vai, volta ao Egito, porque todos os homens que estavam à caça da tua alma^&#42;1^ estão mortos.”

[NOTE]
====
. “Tua alma (vida).” Hebr.: naf·shé·kha; gr.: psy·khén.
====

[[v2-4-20]]

^<<v2-4-20,20>>^ Moisés tomou então sua esposa e seus filhos, e os fez montar num jumento, e passou a voltar à terra do Egito. Além disso, Moisés tomou na sua mão o bastão do [verdadeiro] Deus.

[[v2-4-21]]

^<<v2-4-21,21>>^ E Jeová prosseguiu, dizendo a Moisés: “Depois de teres ido e voltado ao Egito, vê que realmente realizes diante de Faraó todos os milagres que pus na tua mão. Quanto a mim, deixarei o coração dele ficar obstinado;^&#42;1^ e ele não mandará o povo embora.

[NOTE]
====
. Ou “duro”.
====

[[v2-4-22]]

^<<v2-4-22,22>>^ E tens de dizer a Faraó: ‘Assim disse Jeová: “Israel é meu filho, meu primogênito.

[[v2-4-23]]

^<<v2-4-23,23>>^ E eu te digo: Manda embora meu filho, para que me sirva.^&#42;1^ Mas, caso te negues a mandá-lo embora, eis que mato teu filho, teu primogênito.”’”

[NOTE]
====
. “Para que me sirva (adore).” Hebr.: weya·‛av·dhé·ni; gr.: la·treú·sei. Veja 3:12 n.
====

[[v2-4-24]]

^<<v2-4-24,24>>^ Ora, sucedeu na estrada, na pousada, que Jeová^&#42;1^ foi encontrá-lo e procurava um modo de entregá-lo à morte.

[NOTE]
====
. “Jeová”, MSam; TLXX: “o anjo de Jeová”.
====

[[v2-4-25]]

^<<v2-4-25,25>>^ Por fim, Zípora tomou uma pederneira e cortou o prepúcio de seu filho, e fez que tocasse nos pés dele e disse:^&#42;1^ “É porque és para mim um noivo de sangue.”^&#42;2^

[NOTE]
====
. “E disse: ‘O sangue da circuncisão do meu filhinho parou (estancou)’”, LXX.
. Lit.: “sangues”.
====

[[v2-4-26]]

^<<v2-4-26,26>>^ Por conseguinte, ele o largou. Naquele tempo ela disse: “Noivo de sangue”, por causa da circuncisão.^&#42;1^

[NOTE]
====
. Lit.: “circuncisões”.
====

[[v2-4-27]]

^<<v2-4-27,27>>^ Jeová disse então a Arão: “Vai ao encontro de Moisés no ermo.” Com isso ele foi e o encontrou no monte do [verdadeiro] Deus, e beijou-o.

[[v2-4-28]]

^<<v2-4-28,28>>^ E Moisés passou a contar a Arão todas as palavras de Jeová, que o enviara, e todos os sinais que lhe ordenara [fazer].^&#42;1^

[NOTE]
====
. “Lhe ordenara fazer”, Sy; MLXXVg: “(lhe) mandara”.
====

[[v2-4-29]]

^<<v2-4-29,29>>^ Depois, Moisés e Arão foram e ajuntaram todos os anciãos dos filhos de Israel.

[[v2-4-30]]

^<<v2-4-30,30>>^ Arão falou então todas as palavras que Jeová falara a Moisés, e realizou os sinais sob o olhar do povo.

[[v2-4-31]]

^<<v2-4-31,31>>^ Em vista disso, o povo creu. Quando ouviram que Jeová voltara sua atenção para os filhos de Israel e que vira sua tribulação, inclinaram-se e prostraram-se.

'''

xref:002-exodo/002-exodo-003.adoc#v2-3-0[&#60; Capítulo Anterior] | <<v2-4-0,Topo>> | xref:002-exodo/002-exodo-005.adoc#v2-5-0[Próximo Capítulo &#62;]