include::./index.adoc[]

[[v7-9-0]]
=== Juízes, 9
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v7-9-1]]

^<<v7-9-1,1>>^ Passado tempo, Abimeleque, filho de Jerubaal, foi a Siquém ter com os irmãos de sua mãe, e começou a falar com eles e com toda a família da casa do pai de sua mãe, dizendo:

[[v7-9-2]]

^<<v7-9-2,2>>^ “Por favor, falai aos ouvidos de todos os proprietários de terras^&#42;1^ de Siquém: ‘O que é melhor para vós, que setenta homens, todos os filhos de Jerubaal, dominem sobre vós ou que um só homem domine sobre vós? E tendes de lembrar-vos de que sou vosso osso e vossa carne.’”

[NOTE]
====
. “Proprietários de terras de.” Hebr.: ba·‛aléh; LXXVg: “homens”.
====

[[v7-9-3]]

^<<v7-9-3,3>>^ Portanto, os irmãos de sua mãe começaram a falar todas essas palavras a respeito dele aos ouvidos de todos os proprietários de terras de Siquém, de modo que o coração deles se inclinou para Abimeleque, pois disseram: “Ele é nosso irmão.”

[[v7-9-4]]

^<<v7-9-4,4>>^ Deram-lhe então setenta moedas de prata da casa de Baal-Berite, e com elas Abimeleque passou a contratar homens vadios e insolentes para o acompanharem.

[[v7-9-5]]

^<<v7-9-5,5>>^ Depois foi à casa de seu pai em Ofra e matou seus irmãos, os filhos de Jerubaal, setenta homens, sobre uma só pedra, mas sobrou Jotão, filho mais moço de Jerubaal, porque se tinha escondido.

[[v7-9-6]]

^<<v7-9-6,6>>^ A seguir se ajuntaram todos os proprietários de terras de Siquém e toda a casa de Milo, e foram e fizeram Abimeleque reinar como rei, perto da árvore grande, a coluna que havia em Siquém.

[[v7-9-7]]

^<<v7-9-7,7>>^ Quando se comunicou isso a Jotão, ele foi imediatamente e se pôs de pé no cume do monte Gerizim, e levantou a sua voz e clamou, e disse-lhes: “Escutai-me, ó proprietários de terras de Siquém, e escute-vos Deus:

[[v7-9-8]]

^<<v7-9-8,8>>^ “Aconteceu uma vez que as árvores foram ungir um rei sobre si. Disseram, pois, à oliveira: ‘Reina sobre nós.’

[[v7-9-9]]

^<<v7-9-9,9>>^ Mas a oliveira lhes disse: ‘Deveria eu renunciar à minha gordura com que se glorifica a Deus e os homens e deveria ir para oscilar sobre as outras árvores?’

[[v7-9-10]]

^<<v7-9-10,10>>^ As árvores disseram então à figueira: ‘Vem, reina sobre nós.’

[[v7-9-11]]

^<<v7-9-11,11>>^ Mas a figueira disse-lhes: ‘Deveria eu renunciar à minha doçura e ao meu bom produto e deveria ir para oscilar sobre as outras árvores?’

[[v7-9-12]]

^<<v7-9-12,12>>^ A seguir, as árvores disseram à videira: ‘Vem, reina sobre nós.’

[[v7-9-13]]

^<<v7-9-13,13>>^ A videira, por sua vez, disse-lhes: ‘Deveria eu renunciar ao meu vinho novo que alegra a Deus e os homens e deveria ir para oscilar sobre as árvores?’

[[v7-9-14]]

^<<v7-9-14,14>>^ Por fim, todas as outras árvores disseram ao espinheiro-de-casca-branca: ‘Vem, reina sobre nós.’

[[v7-9-15]]

^<<v7-9-15,15>>^ Em vista disso, o espinheiro-de-casca-branca disse às árvores: ‘Se verdadeiramente me ungis como rei sobre vós, vinde, refugiai-vos debaixo da minha sombra. Mas, se não, saia fogo do espinheiro-de-casca-branca e consuma os cedros do Líbano.’

[[v7-9-16]]

^<<v7-9-16,16>>^ “E agora, se foi em verdade e sem defeito que agistes e fostes fazer Abimeleque rei, e se usastes de bondade para com Jerubaal e para com os da sua casa, e se lhe fizestes conforme merece o feito das suas mãos,

[[v7-9-17]]

^<<v7-9-17,17>>^ sendo que meu pai lutou por vós e foi arriscar sua alma^&#42;1^ para vos livrar da mão de Midiã;

[NOTE]
====
. “Sua alma (vida).” Hebr.: naf·shóh; gr.: psy·khén; lat.: á·ni·mam.
====

[[v7-9-18]]

^<<v7-9-18,18>>^ e vós, da vossa parte, vos levantastes hoje contra os da casa de meu pai para matar seus filhos, setenta homens, sobre uma só pedra, e para fazer Abimeleque, filho de sua escrava, rei sobre os proprietários de terras de Siquém, só porque é vosso próprio irmão;

[[v7-9-19]]

^<<v7-9-19,19>>^ sim, se foi em verdade e sem defeito que agistes para com Jerubaal e para com os da sua casa no dia de hoje, alegrai-vos com Abimeleque e alegre-se ele convosco.

[[v7-9-20]]

^<<v7-9-20,20>>^ Mas, se não, saia fogo de Abimeleque e consuma os proprietários de terras de Siquém e a casa de Milo, e saia fogo dos proprietários de terras de Siquém e da casa de Milo e consuma a Abimeleque.”

[[v7-9-21]]

^<<v7-9-21,21>>^ Jotão pôs-se então em fuga e saiu correndo, e seguiu caminho até Beer, e passou a morar ali por causa de Abimeleque, seu irmão.

[[v7-9-22]]

^<<v7-9-22,22>>^ E por três anos Abimeleque desempenhava o papel de príncipe^&#42;1^ sobre Israel.

[NOTE]
====
. Ou “exercia domínio”.
====

[[v7-9-23]]

^<<v7-9-23,23>>^ Então Deus deixou que se desenvolvesse^&#42;1^ um espírito mau entre Abimeleque e os proprietários de terras de Siquém, e os proprietários de terras de Siquém passaram a agir traiçoeiramente com Abimeleque,

[NOTE]
====
. Lit.: “Deus enviou”.
====

[[v7-9-24]]

^<<v7-9-24,24>>^ para que viesse a violência feita aos setenta filhos de Jerubaal^&#42;1^ e para que ele pusesse o sangue deles sobre Abimeleque, seu irmão, por ele os ter matado, e sobre os proprietários de terras de Siquém, por lhe terem fortalecido as mãos para matar seus irmãos.

[NOTE]
====
. “Para que trouxesse a violência feita aos setenta filhos de Jerubaal”, LXX.
====

[[v7-9-25]]

^<<v7-9-25,25>>^ Portanto, os proprietários de terras de Siquém puseram-lhe homens de emboscada sobre os cumes dos montes e estes roubavam a todo aquele que passava por eles na estrada. Com o tempo se contou isso a Abimeleque.

[[v7-9-26]]

^<<v7-9-26,26>>^ Então veio Gaal, filho de Ebede, e seus irmãos, e eles passaram para Siquém, e os proprietários de terras de Siquém começaram a confiar nele.

[[v7-9-27]]

^<<v7-9-27,27>>^ E saíram ao campo, como de costume, e se empenharam em colher as uvas dos seus vinhedos e em pisá-las, e se entregaram a uma exultação festiva, entrando depois na casa de seu deus, e comeram e beberam, e invocaram o mal sobre Abimeleque.

[[v7-9-28]]

^<<v7-9-28,28>>^ E Gaal, filho de Ebede, prosseguiu, dizendo: “Quem é Abimeleque e quem é Siquém,^&#42;1^ que devamos servir a ele? Não é ele filho de Jerubaal, e não é Zebul seu comissário? Servi vós outros aos homens de Hamor, pai de Siquém, mas por que devíamos nós servir a ele?

[NOTE]
====
. “Siquém”, MSyVg; LXX: “o filho de Siquém”.
====

[[v7-9-29]]

^<<v7-9-29,29>>^ E se este povo tão-somente estivesse na minha mão!^&#42;1^ Então eu removeria a Abimeleque.” E prosseguiu, dizendo^&#42;2^ a Abimeleque: “Faze numeroso o teu exército e vem para fora.”

[NOTE]
====
. Lit.: “E quem entregará este povo na minha mão?”
. “E eu removeria a Abimeleque e diria”, LXX; Vg: “‘para que eu removesse a Abimeleque!’ E disse-se.”
====

[[v7-9-30]]

^<<v7-9-30,30>>^ E Zebul, príncipe da cidade, chegou a ouvir as palavras de Gaal, filho de Ebede. Então se acendeu a sua ira.

[[v7-9-31]]

^<<v7-9-31,31>>^ Por isso enviou por um subterfúgio mensageiros a Abimeleque,^&#42;1^ dizendo: “Eis que Gaal, filho de Ebede, e seus irmãos vieram agora a Siquém, e eis que estão conglomerando a cidade contra ti.

[NOTE]
====
. “Por um subterfúgio . . . a Abimeleque.” Possivelmente: “a Abimeleque em Tormá (Arumá)”. Veja v. 41.
====

[[v7-9-32]]

^<<v7-9-32,32>>^ E agora, levanta-te de noite, tu e o povo que há contigo, e põe-te de emboscada no campo.

[[v7-9-33]]

^<<v7-9-33,33>>^ E tem de dar-se, de manhã, que assim que o sol raiar deves levantar-te cedo e tens de investir contra a cidade; e quando ele e o povo que há com ele saírem contra ti, então terás de fazer-lhe assim como a tua mão achar possível.”

[[v7-9-34]]

^<<v7-9-34,34>>^ Por conseguinte, Abimeleque e todo o povo que havia com ele levantaram-se de noite e começaram a ficar de emboscada contra Siquém, em quatro companhias.

[[v7-9-35]]

^<<v7-9-35,35>>^ Mais tarde saiu Gaal, filho de Ebede, e ficou de pé à entrada do portão da cidade. Levantaram-se então Abimeleque e o povo que havia com ele do lugar da emboscada.

[[v7-9-36]]

^<<v7-9-36,36>>^ Quando Gaal avistou o povo, disse imediatamente a Zebul: “Eis que desce gente dos cumes dos montes.” Mas Zebul lhe disse: “Estás vendo as sombras dos montes como se fossem homens.”

[[v7-9-37]]

^<<v7-9-37,37>>^ Depois Gaal falou mais uma vez e disse: “Eis que desce gente saindo do meio da terra e uma companhia vem pelo caminho da árvore grande de Meonenim.”^&#42;1^

[NOTE]
====
. Significando “Os Que Praticam Magia”. Veja De 18:14.
====

[[v7-9-38]]

^<<v7-9-38,38>>^ Nisso lhe disse Zebul: “Onde está agora a declaração da tua boca:^&#42;1^ ‘Quem é Abimeleque que devamos servir a ele?’ Não é este o povo que rejeitaste? Sai agora, por favor, e luta contra ele.”

[NOTE]
====
. Ou “essa tua boca quando disseste”.
====

[[v7-9-39]]

^<<v7-9-39,39>>^ Portanto, Gaal saiu à testa dos proprietários de terras de Siquém e foi lutar contra Abimeleque.

[[v7-9-40]]

^<<v7-9-40,40>>^ E Abimeleque foi atrás dele, e este se pôs em fuga diante dele; e os que eram mortos caíam em quantidade até a entrada do portão.

[[v7-9-41]]

^<<v7-9-41,41>>^ E Abimeleque continuou a morar em Arumá,^&#42;1^ e Zebul passou a expulsar Gaal e seus irmãos da morada em Siquém.

[NOTE]
====
. Possivelmente: “Ruma.” Veja 2Rs 23:36.
====

[[v7-9-42]]

^<<v7-9-42,42>>^ E sucedeu, no dia seguinte, que o povo começou a sair ao campo. De modo que o contaram a Abimeleque.

[[v7-9-43]]

^<<v7-9-43,43>>^ Em vista disso, tomou o povo e o dividiu em três companhias e começou a ficar de emboscada no campo. Depois olhou e eis que o povo saía da cidade. Levantou-se então contra eles e os golpeou.

[[v7-9-44]]

^<<v7-9-44,44>>^ E Abimeleque e as companhias^&#42;1^ que havia com ele investiram para ficar de pé à entrada do portão da cidade, ao passo que duas companhias investiram contra todos os que estavam no campo, e foram golpeá-los.

[NOTE]
====
. “Companhias”, M; Vg: “companhia”.
====

[[v7-9-45]]

^<<v7-9-45,45>>^ E Abimeleque lutou contra a cidade todo aquele dia e chegou a capturar a cidade; e matou o povo que havia nela, depois demoliu a cidade e a semeou com sal.

[[v7-9-46]]

^<<v7-9-46,46>>^ E ouvindo isso os proprietários de terras da torre de Siquém, foram imediatamente à cripta da casa de El-Berite.^&#42;1^

[NOTE]
====
. Significando “Deus dum Pacto”; LXXA: “Baal dum pacto”.
====

[[v7-9-47]]

^<<v7-9-47,47>>^ Comunicou-se então a Abimeleque que todos os proprietários de terras da torre de Siquém se tinham reunido.

[[v7-9-48]]

^<<v7-9-48,48>>^ Abimeleque subiu, pois, ao monte Zalmom, ele e todo o povo que havia com ele. Abimeleque tomou então um machado na mão e cortou um galho das árvores, e ele o levantou e pôs sobre o ombro, e disse ao povo que estava com ele: “O que me vistes fazer, apressai-vos, fazei igual a mim!”

[[v7-9-49]]

^<<v7-9-49,49>>^ De modo que todo o povo cortou também um galho, cada um para si, e seguiu a Abimeleque. Puseram-nos então contra a cripta e puseram fogo à cripta, sobre eles, de modo que morreram também todos os homens da torre de Siquém, cerca de mil homens e mulheres.

[[v7-9-50]]

^<<v7-9-50,50>>^ E Abimeleque passou a ir a Tebes e a acampar-se contra Tebes, e foi capturá-la.

[[v7-9-51]]

^<<v7-9-51,51>>^ Visto que havia uma torre forte no meio da cidade, foi para lá que fugiram todos os homens e mulheres, e todos os proprietários de terras da cidade, fechando-a depois atrás de si e subindo ao terraço da torre.

[[v7-9-52]]

^<<v7-9-52,52>>^ E Abimeleque veio até a torre e começou a lutar contra ela, e foi-se chegando à entrada da torre para queimá-la com fogo.

[[v7-9-53]]

^<<v7-9-53,53>>^ Então, certa mulher jogou uma mó superior na cabeça de Abimeleque e quebrou-lhe o crânio.

[[v7-9-54]]

^<<v7-9-54,54>>^ Ele chamou assim depressa o ajudante que carregava as suas armas e lhe disse: “Puxa a tua espada e entrega-me à morte, para que não se diga de mim: ‘Foi uma mulher que o matou.’” Seu ajudante o traspassou imediatamente, de modo que morreu.

[[v7-9-55]]

^<<v7-9-55,55>>^ Quando os homens de Israel viram que Abimeleque havia morrido, foram então cada um para o seu lugar.

[[v7-9-56]]

^<<v7-9-56,56>>^ Assim fez Deus voltar o mal de Abimeleque que este causara a seu pai ao matar os seus setenta irmãos.

[[v7-9-57]]

^<<v7-9-57,57>>^ E Deus fez voltar todo o mal dos homens de Siquém sobre as suas próprias cabeças, para que viesse sobre eles a invocação do mal da parte de Jotão, filho de Jerubaal.

'''

xref:007-juizes/007-juizes-008.adoc#v7-8-0[&#60; Capítulo Anterior] | <<v7-9-0,Topo>> | xref:007-juizes/007-juizes-010.adoc#v7-10-0[Próximo Capítulo &#62;]