include::./index.adoc[]

[[v7-11-0]]
=== Juízes, 11
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v7-11-1]]

^<<v7-11-1,1>>^ Ora, Jefté, o gileadita, tornara-se homem poderoso, valente, e ele era filho duma mulher prostituta, e Gileade veio a ser o pai de Jefté.

[[v7-11-2]]

^<<v7-11-2,2>>^ E a esposa de Gileade dava-lhe à luz filhos. Quando os filhos da esposa se tornaram grandes, passaram a expulsar Jefté e a dizer-lhe: “Não deves ter herança na casa de nosso pai, por seres filho de outra mulher.”

[[v7-11-3]]

^<<v7-11-3,3>>^ Assim, Jefté fugiu por causa de seus irmãos e passou a morar na terra de Tobe. E homens ociosos foram juntar-se a Jefté e saíam com ele.

[[v7-11-4]]

^<<v7-11-4,4>>^ E depois de algum tempo sucedeu que os filhos de Amom começaram a lutar contra Israel.

[[v7-11-5]]

^<<v7-11-5,5>>^ E aconteceu que, quando os filhos de Amom lutaram contra Israel, os anciãos de Gileade mandaram trazer imediatamente Jefté da terra de Tobe.

[[v7-11-6]]

^<<v7-11-6,6>>^ Disseram então a Jefté: “Vem deveras e serve como nosso comandante, e lutemos contra os filhos de Amom.”

[[v7-11-7]]

^<<v7-11-7,7>>^ Mas Jefté disse aos anciãos de Gileade: “Não fostes vós os que me odiastes a ponto de me expulsar da casa de meu pai? E por que é que agora viestes a mim quando estais em aflição?”

[[v7-11-8]]

^<<v7-11-8,8>>^ A isso os anciãos de Gileade disseram a Jefté: “É por isso que agora voltamos a ti, e tu tens de vir conosco e lutar contra os filhos de Amom, e tens de tornar-te para nós o cabeça de todos os habitantes de Gileade.”

[[v7-11-9]]

^<<v7-11-9,9>>^ De modo que Jefté disse aos anciãos de Gileade: “Se me levardes de volta para lutar contra os filhos de Amom e Jeová deveras mos entregar, eu, da minha parte, me tornarei vosso cabeça!”

[[v7-11-10]]

^<<v7-11-10,10>>^ Os anciãos de Gileade disseram por sua vez a Jefté: “Mostre-se Jeová ouvinte entre nós, se não fizermos segundo a tua palavra.”

[[v7-11-11]]

^<<v7-11-11,11>>^ Por conseguinte, Jefté foi com os anciãos de Gileade e o povo o pôs sobre si como cabeça e comandante. E Jefté passou a falar todas as suas palavras perante Jeová, em Mispá.

[[v7-11-12]]

^<<v7-11-12,12>>^ Jefté enviou então mensageiros ao rei dos filhos de Amom, dizendo: “Que tenho eu que ver contigo,^&#42;1^ uma vez que vieste contra mim para lutar na minha terra?”

[NOTE]
====
. Lit.: “Que [há] para mim e para ti?” Esta é uma expressão idiomática hebr.; é uma pergunta de repulsa, indicando objeção. Veja Ap. 7B.
====

[[v7-11-13]]

^<<v7-11-13,13>>^ Assim, o rei dos filhos de Amom disse aos mensageiros de Jefté: “É porque Israel tomou a minha terra, ao saírem do Egito, desde o Árnon até o Jaboque, e até o Jordão. E agora, restitui-a deveras em paz.”

[[v7-11-14]]

^<<v7-11-14,14>>^ Jefté, porém, enviou mais uma vez mensageiros ao rei dos filhos de Amom

[[v7-11-15]]

^<<v7-11-15,15>>^ e disse-lhe:
“Assim disse Jefté: ‘Israel não tomou a terra de Moabe, nem a terra dos filhos de Amom.

[[v7-11-16]]

^<<v7-11-16,16>>^ Pois, quando subiram do Egito, Israel foi andando pelo ermo até o Mar Vermelho e chegou a Cades.

[[v7-11-17]]

^<<v7-11-17,17>>^ Israel enviou então mensageiros ao rei de Edom, dizendo: “Por favor, deixa-me passar pela tua terra”, e o rei de Edom não escutou. E enviaram também [mensageiros] ao rei de Moabe, mas ele não consentiu. E Israel ficou morando em Cades.

[[v7-11-18]]

^<<v7-11-18,18>>^ Quando seguiram andando pelo ermo, foram contornar a terra de Edom e a terra de Moabe, de modo que foram para o nascente do sol, no que se refere à terra de Moabe,^&#42;1^ e passaram a acampar-se na região do Árnon; e não entraram no termo de Moabe, visto que o Árnon era o termo de Moabe.

[NOTE]
====
. Ou “foram para o leste da terra de Moabe”.
====

[[v7-11-19]]

^<<v7-11-19,19>>^ “‘Israel enviou depois mensageiros a Síon, rei dos amorreus, rei de Hésbon, e Israel lhe disse: “Por favor, deixa-nos passar pelo teu país para o meu próprio lugar.”

[[v7-11-20]]

^<<v7-11-20,20>>^ E Síon não se sentia seguro quanto à passagem de Israel pelo seu território, e Síon foi ajuntar todo o seu povo e acampar-se em Jaaz, e foi lutar contra Israel.

[[v7-11-21]]

^<<v7-11-21,21>>^ Em vista disso, Jeová, o Deus de Israel, entregou Síon e todo o seu povo na mão de Israel, de modo que os golpearam, e Israel tomou posse de toda a terra dos amorreus que habitavam naquela terra.

[[v7-11-22]]

^<<v7-11-22,22>>^ Assim tomaram posse de todo o território dos amorreus, desde o Árnon até o Jaboque, e desde o ermo até o Jordão.

[[v7-11-23]]

^<<v7-11-23,23>>^ “‘E agora, foi Jeová, o Deus de Israel, quem desapossou os amorreus de diante do seu povo de Israel, e tu, da tua parte, os desapossarias.^&#42;1^

[NOTE]
====
. “Os herdarias”, LXX; Vg: “tomarias posse de sua terra”.
====

[[v7-11-24]]

^<<v7-11-24,24>>^ Não é que desapossas^&#42;1^ aquele que Quemós, teu deus,^&#42;2^ te faz desapossar? E a todo aquele que Jeová, nosso Deus, desapossou de diante de nós é que nós desapossaremos.^&#42;3^

[NOTE]
====
. “Herdas”, LXX; Vg: “é de direito [teu]”.
. “Teu deus.” Hebr.: ’elo·heí·kha; gr.: the·ós; lat.: dé·us; LXXVg entenderam estar ’elo·heí·kha (de ’elo·hím) no pl. para denotar excelência, e por isso verteram a palavra no sing.
. “Herdaremos”, LXX; Vg: “passará a ser nossa propriedade”.
====

[[v7-11-25]]

^<<v7-11-25,25>>^ E agora, és tu melhor do que Balaque, filho de Zipor, rei de Moabe? Contendeu ele alguma vez com Israel ou lutou ele jamais contra eles?

[[v7-11-26]]

^<<v7-11-26,26>>^ Enquanto Israel morava em Hésbon e nas suas aldeias dependentes, e em Aroer e nas suas aldeias dependentes, e em todas as cidades que se acham à beira do Árnon, por trezentos anos, ora, por que nunca as arrebatastes deles durante esse tempo?

[[v7-11-27]]

^<<v7-11-27,27>>^ Quanto a mim, não pequei contra ti, mas tu me fazes mal por lutar contra mim. Julgue hoje Jeová, o Juiz, entre os filhos de Israel e os filhos de Amom.’”

[[v7-11-28]]

^<<v7-11-28,28>>^ E o rei dos filhos de Amom não escutou as palavras de Jefté, que este lhe enviara.

[[v7-11-29]]

^<<v7-11-29,29>>^ Então veio o espírito de Jeová sobre Jefté, e ele passou a atravessar Gileade e Manassés, e a atravessar Mispé de Gileade, e de Mispé de Gileade passou adiante até os filhos de Amom.

[[v7-11-30]]

^<<v7-11-30,30>>^ Jefté fez então um voto a Jeová e disse: “Se tu, sem falta, me entregares os filhos de Amom na mão,

[[v7-11-31]]

^<<v7-11-31,31>>^ então terá de dar-se que aquele que sair, quem sair da porta da minha casa ao meu encontro, quando eu voltar em paz dos filhos de Amom, terá de tornar-se então de Jeová, e eu terei de oferecer a tal como oferta queimada.”

[[v7-11-32]]

^<<v7-11-32,32>>^ Assim, Jefté passou adiante até os filhos de Amom para lutar contra eles e Jeová passou a dá-los na sua mão.

[[v7-11-33]]

^<<v7-11-33,33>>^ E ele foi golpeá-los desde Aroer até Minite — vinte cidades — e até Abel-Queramim, com uma matança muito grande. Assim foram subjugados os filhos de Amom diante dos filhos de Israel.

[[v7-11-34]]

^<<v7-11-34,34>>^ Finalmente, Jefté chegou a Mispá, à sua casa, e eis que lhe saía ao encontro sua filha, tocando pandeiro e dançando!^&#42;1^ Ora, ela era absolutamente filha única.^&#42;2^ Fora dela não tinha filho nem filha.

[NOTE]
====
. Lit.: “com pandeiros e danças”.
. “Ora, ela era absolutamente filha única.” Lit.: “E só ela, somente ela.” Hebr.: weráq hí yehhi·dháh; gr.: mo·no·ge·nés, “unigênita”; lat.: u·ni·gé·ni·ta. Compare isso com Gên 22:2. Veja Lu 8:42 n.
====

[[v7-11-35]]

^<<v7-11-35,35>>^ E sucedeu que, quando a avistou, começou a rasgar suas roupas e a dizer: “Ai, minha filha! Fizeste deveras que eu me dobrasse, e tu te tornaste aquele a quem eu bania. E eu é que abri a minha boca a Jeová e não posso voltar atrás.”

[[v7-11-36]]

^<<v7-11-36,36>>^ Mas ela lhe disse: “Meu pai, se abriste a tua boca a Jeová, faze comigo segundo tudo o que saiu da tua boca, visto que Jeová executou para ti atos de vingança sobre os teus inimigos, os filhos de Amom.”

[[v7-11-37]]

^<<v7-11-37,37>>^ E ela prosseguiu, dizendo a seu pai: “Faça-se esta coisa comigo: Deixa-me a sós por dois meses e deixa-me ir, e eu hei de descer sobre os montes, e deixa-me chorar a minha virgindade, eu e as minhas companheiras.”

[[v7-11-38]]

^<<v7-11-38,38>>^ A isso ele disse: “Vai!” Mandou-a embora, pois, por dois meses; e ela ia, ela com as suas companheiras, e chorava sobre os montes a sua virgindade.

[[v7-11-39]]

^<<v7-11-39,39>>^ E sucedeu que, ao fim dos dois meses, foi retornar a seu pai, após o que ele cumpriu seu voto que fizera referente a ela. Quanto a ela, nunca teve relações [sexuais] com qualquer homem. E veio a ser um regulamento em Israel:

[[v7-11-40]]

^<<v7-11-40,40>>^ As filhas de Israel subiam de ano em ano para decantar^&#42;1^ a filha de Jefté, o gileadita, por quatro dias no ano.

[NOTE]
====
. “Lamentar”, LXX; mediante uma correção do M: “ir para responder (conversar com)”. Veja 5:11, onde se usa o mesmo verbo hebr., ta·náh, “narrar”.
====

'''

xref:007-juizes/007-juizes-010.adoc#v7-10-0[&#60; Capítulo Anterior] | <<v7-11-0,Topo>> | xref:007-juizes/007-juizes-012.adoc#v7-12-0[Próximo Capítulo &#62;]