include::./index.adoc[]

[[v7-1-0]]
=== Juízes, 1
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v7-1-1]]

^<<v7-1-1,1>>^ E aconteceu depois da morte de Josué que os filhos de Israel passaram a indagar de Jeová, dizendo: “Quem de nós subirá primeiro aos cananeus para lutar contra eles?”

[[v7-1-2]]

^<<v7-1-2,2>>^ A isso Jeová disse: “Judá subirá. Eis que lhe hei de entregar o país na mão.”

[[v7-1-3]]

^<<v7-1-3,3>>^ Então disse Judá a Simeão, seu irmão: “Sobe comigo à minha sorte e lutemos contra os cananeus, e eu, da minha parte, irei contigo à tua sorte.” Por conseguinte, Simeão foi com ele.

[[v7-1-4]]

^<<v7-1-4,4>>^ Com isso Judá subiu, e Jeová lhes entregou na mão os cananeus e os perizeus, de modo que os derrotaram em Bezeque, dez mil homens.

[[v7-1-5]]

^<<v7-1-5,5>>^ E encontrando Adoni-Bezeque em Bezeque, lutaram então contra ele e derrotaram os cananeus e os perizeus.

[[v7-1-6]]

^<<v7-1-6,6>>^ Quando Adoni-Bezeque se pôs em fuga, então foram no encalço dele e o seguraram, e amputaram-lhe os polegares das mãos e os dedos grandes dos pés.

[[v7-1-7]]

^<<v7-1-7,7>>^ A isso Adoni-Bezeque disse: “Chegou a haver setenta reis, com os polegares das suas mãos e os dedos grandes dos seus pés amputados, apanhando comida debaixo da minha mesa. Assim como eu fiz, assim me retribuiu Deus.” Depois o levaram a Jerusalém e ali morreu.

[[v7-1-8]]

^<<v7-1-8,8>>^ Outrossim, os filhos de Judá travaram guerra contra Jerusalém e chegaram a capturá-la, e foram golpeá-la com o fio da espada, e a cidade ficou entregue ao fogo.

[[v7-1-9]]

^<<v7-1-9,9>>^ E depois desceram os filhos de Judá para lutar contra os cananeus que habitavam na região montanhosa, e no Negebe, e na Sefelá.

[[v7-1-10]]

^<<v7-1-10,10>>^ Judá marchou, pois, contra os cananeus que moravam em Hébron, (ora, o nome anterior de Hébron era Quiriate-Arba,) e foram golpear a Sesai, e a Aimã, e a Talmai.

[[v7-1-11]]

^<<v7-1-11,11>>^ E dali marcharam contra os habitantes de Debir. (Ora, o nome anterior de Debir era Quiriate-Sefer.)

[[v7-1-12]]

^<<v7-1-12,12>>^ Calebe disse então: “Quem golpear Quiriate-Sefer e deveras a capturar, ora, a este darei Acsa, minha filha, por esposa.”

[[v7-1-13]]

^<<v7-1-13,13>>^ E foi capturá-la Otniel, filho de Quenaz, irmão mais moço de Calebe. Por isso lhe deu por esposa Acsa, sua filha.

[[v7-1-14]]

^<<v7-1-14,14>>^ E sucedeu que, enquanto ela ia para casa, instigava-o a pedir do pai dela um campo. Então bateu palmas enquanto estava montada no jumento.^&#42;1^ Então Calebe lhe disse: “Que queres?”

[NOTE]
====
. Ou “então ela deslizou (apeou) do jumento”.
====

[[v7-1-15]]

^<<v7-1-15,15>>^ Ela lhe disse, portanto: “Concede-me deveras uma bênção, pois me deste uma terra sulina, e tens de dar-me Gulote-Maim.”^&#42;1^ Por conseguinte, Calebe lhe deu Gulote Alta e Gulote Baixa.^&#42;2^

[NOTE]
====
. Significando “Bacias de Água”.
. Ou “a bacia superior e a bacia inferior”.
====

[[v7-1-16]]

^<<v7-1-16,16>>^ E os filhos do queneu, de quem Moisés era genro,^&#42;1^ subiram com os filhos de Judá da cidade das palmeiras ao ermo de Judá, que está ao sul de Arade. Então foram e passaram a morar com o povo.

[NOTE]
====
. Ou “do queneu, sogro de Moisés”.
====

[[v7-1-17]]

^<<v7-1-17,17>>^ Mas Judá marchou adiante com Simeão, seu irmão, e eles passaram a golpear os cananeus que habitavam em Zefate e a devotá-la à destruição. Por isso se chamou a cidade pelo nome de Hormá.^&#42;1^

[NOTE]
====
. Significando “Devotamento à Destruição”; LXXB: “Anátema”; Vg: “Hormá, isto é, anátema.”
====

[[v7-1-18]]

^<<v7-1-18,18>>^ Depois, Judá capturou Gaza e seu território, e Ascalom e seu território, e Ecrom e seu território.

[[v7-1-19]]

^<<v7-1-19,19>>^ E Jeová continuou com Judá, de modo que tomou posse da região montanhosa, mas não pôde desapossar os habitantes da baixada, porque tinham carros de guerra com foices de ferro.^&#42;1^

[NOTE]
====
. Lit.: “carros de guerra, de ferro”.
====

[[v7-1-20]]

^<<v7-1-20,20>>^ Quando deram Hébron a Calebe, assim como Moisés prometera, então ele desalojou dali os três filhos de Anaque.

[[v7-1-21]]

^<<v7-1-21,21>>^ E os filhos de Benjamim não desalojaram os jebuseus que habitavam em Jerusalém, mas os jebuseus continuam morando com os filhos de Benjamim em Jerusalém até o dia de hoje.

[[v7-1-22]]

^<<v7-1-22,22>>^ Entrementes, a própria casa de José subiu também contra Betel, e Jeová estava com eles.

[[v7-1-23]]

^<<v7-1-23,23>>^ E a casa de José começou a espiar Betel (incidentalmente, o nome anterior da cidade era Luz),

[[v7-1-24]]

^<<v7-1-24,24>>^ e os espias chegaram a ver um homem saindo da cidade. Portanto, disseram-lhe: “Por favor, mostra-nos o caminho para entrarmos na cidade e certamente usaremos de benignidade para contigo.”

[[v7-1-25]]

^<<v7-1-25,25>>^ Por conseguinte, o homem lhes mostrou o caminho para se entrar na cidade; e eles foram golpear a cidade com o fio da espada, mas deixaram ir o homem e toda a sua família.

[[v7-1-26]]

^<<v7-1-26,26>>^ O homem foi então para a terra dos hititas e construiu uma cidade, e chamou-a pelo nome de Luz. Este é o seu nome até o dia de hoje.

[[v7-1-27]]

^<<v7-1-27,27>>^ E Manassés não tomou posse de Bete-Seã e das suas aldeias dependentes, nem de Taanaque e das suas aldeias dependentes,^&#42;1^ nem dos habitantes de Dor e das suas aldeias dependentes, nem dos habitantes de Ibleão e das suas aldeias dependentes, nem dos habitantes de Megido e das suas aldeias dependentes, mas os cananeus estavam resolvidos a morar nesta terra.

[NOTE]
====
. Lit.: “suas filhas”.
====

[[v7-1-28]]

^<<v7-1-28,28>>^ E sucedeu que Israel ficou forte e passou a sujeitar os cananeus a trabalho forçado, e não os desalojaram completamente.

[[v7-1-29]]

^<<v7-1-29,29>>^ Tampouco Efraim desalojou os cananeus que moravam em Gezer, mas os cananeus continuavam a morar no meio deles em Gezer.

[[v7-1-30]]

^<<v7-1-30,30>>^ Zebulão não desalojou os habitantes de Quitrom, nem os habitantes de Naalol, mas os cananeus continuavam a morar no meio deles e vieram a ficar sujeitos a trabalho forçado.

[[v7-1-31]]

^<<v7-1-31,31>>^ Aser não desalojou os habitantes de Aco,^&#42;1^ nem os habitantes de Sídon, e de Alabe, e de Aczibe, e de Helba, e de Afique, e de Reobe.

[NOTE]
====
. Mais tarde chamada Ptolemaida. Veja At 21:7.
====

[[v7-1-32]]

^<<v7-1-32,32>>^ E os aseritas continuavam a morar no meio dos cananeus que habitavam no país, porque não os desalojaram.

[[v7-1-33]]

^<<v7-1-33,33>>^ Naftali não desalojou os habitantes de Bete-Semes, nem os habitantes de Bete-Anate, mas eles continuavam a morar no meio dos cananeus que habitavam no país; e os habitantes de Bete-Semes e de Bete-Anate tornaram-se seus para trabalho forçado.

[[v7-1-34]]

^<<v7-1-34,34>>^ E os amorreus apertavam os filhos de Dã na região montanhosa, pois não lhes permitiam descer à baixada.

[[v7-1-35]]

^<<v7-1-35,35>>^ De modo que os amorreus estavam resolvidos a morar na montanha de Heres, e em Aijalom, e em Saalbim. Mas a mão da casa de José ficou tão pesada que foram obrigados a trabalho forçado.

[[v7-1-36]]

^<<v7-1-36,36>>^ E o território dos amorreus era da subida de Acrabim, de Sela^&#42;1^ para cima.

[NOTE]
====
. Ou “da Rocha”. Hebr.: me·has·Sé·la‛.
====

'''

xref:006-josue/006-josue-024.adoc#v6-24-0[&#60; Capítulo Anterior] | <<v7-1-0,Topo>> | xref:007-juizes/007-juizes-002.adoc#v7-2-0[Próximo Capítulo &#62;]