include::./index.adoc[]

[[v7-19-0]]
=== Juízes, 19
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v7-19-1]]

^<<v7-19-1,1>>^ Ora, aconteceu que naqueles dias não havia rei em Israel. E sucedeu que certo levita residia por um tempo nas partes mais remotas da região montanhosa de Efraim. Com o tempo tomou para si uma esposa, uma concubina, de Belém de Judá.

[[v7-19-2]]

^<<v7-19-2,2>>^ E sua concubina começou a cometer fornicação^&#42;1^ contra ele.^&#42;2^ Por fim ela se foi embora dele para a casa de seu pai em Belém de Judá e permaneceu lá por quatro meses inteiros.

[NOTE]
====
. “E . . . começou a cometer fornicação.” Hebr.: wat·tiz·néh.
. “Sua concubina zangou-se com ele”, LXXA.
====

[[v7-19-3]]

^<<v7-19-3,3>>^ Seu esposo se levantou então e foi atrás dela para falar-lhe consoladoramente,^&#42;1^ a fim de a trazer de volta; e havia com ele seu ajudante^&#42;2^ e uma parelha de jumentos. Assim, ela o fez entrar na casa de seu pai. E vendo-o o pai da moça, alegrou-se imediatamente de se encontrar com ele.

[NOTE]
====
. Lit.: “falar-lhe ao coração”.
. Ou “moço; rapaz”.
====

[[v7-19-4]]

^<<v7-19-4,4>>^ Por conseguinte, seu sogro, o pai da moça, agarrou-o, de modo que ficou morando com ele por três dias; e comiam e bebiam, e ele^&#42;1^ pernoitava ali.

[NOTE]
====
. “Ele”, LXXmss.It; MSy: “eles”.
====

[[v7-19-5]]

^<<v7-19-5,5>>^ E sucedeu que, no quarto dia, quando se levantaram de manhã cedo, como de costume, ele se levantou então para ir, mas o pai da moça disse a seu genro: “Revigora teu coração com um pedaço de pão e depois podeis ir.”

[[v7-19-6]]

^<<v7-19-6,6>>^ Assentaram-se, pois, e ambos começaram a comer e a beber juntos; depois, o pai da moça disse ao homem: “Resolve-te, por favor, e pernoita, e sinta-se bem o teu coração.”

[[v7-19-7]]

^<<v7-19-7,7>>^ Quando o homem se levantou para ir, seu sogro continuou a instar com ele, de modo que pernoitou novamente ali.

[[v7-19-8]]

^<<v7-19-8,8>>^ Quando se levantou de manhã cedo para ir, no quinto dia, então lhe disse o pai da moça: “Por favor, toma sustento para o teu coração.” E demoraram-se até se desvanecer o dia. E ambos continuavam comendo.

[[v7-19-9]]

^<<v7-19-9,9>>^ O homem levantou-se então para ir, ele e sua concubina, bem como seu ajudante; mas seu sogro, o pai da moça, disse-lhe: “Eis que já declinou o dia, tornando-se noitinha. Por favor, pernoitai. Eis que o dia está por acabar. Pernoita hoje aqui e sinta-se bem o teu coração. E amanhã tendes de levantar-vos cedo para a vossa jornada, e tens de ir para a tua tenda.”

[[v7-19-10]]

^<<v7-19-10,10>>^ No entanto, o homem não concordou em pernoitar, mas levantou-se e pôs-se a caminho, e ele chegou até defronte de Jebus, isto é, Jerusalém; e havia com ele a parelha de jumentos selados, bem como sua concubina e seu ajudante.^&#42;1^

[NOTE]
====
. “Bem como sua concubina e seu ajudante”, para concordar com os vv. 9 e 11; M: “e sua concubina estava com ele”.
====

[[v7-19-11]]

^<<v7-19-11,11>>^ Estando perto de Jebus, visto que a luz do dia declinara consideravelmente, o ajudante disse então ao seu amo:^&#42;1^ “Vem agora e desviemo-nos para esta cidade dos jebuseus, e pernoitemos nela.”

[NOTE]
====
. “Seu amo.” Hebr.: ’adho·náv, pl., para denotar excelência; gr.: ký·ri·on; lat.: dó·mi·num. Veja Gên 39:2 n.
====

[[v7-19-12]]

^<<v7-19-12,12>>^ Seu amo, porém, lhe disse: “Não nos desviemos para uma cidade de estrangeiros que não são parte dos filhos de Israel; e temos de passar adiante até Gibeá.”

[[v7-19-13]]

^<<v7-19-13,13>>^ E prosseguiu, dizendo ao seu ajudante: “Vem e cheguemo-nos a um dos lugares, e temos de pernoitar quer em Gibeá, quer em Ramá.”

[[v7-19-14]]

^<<v7-19-14,14>>^ Passaram assim adiante e seguiram seu caminho, e o sol começou a pôr-se quando estavam perto de Gibeá, que pertence a Benjamim.

[[v7-19-15]]

^<<v7-19-15,15>>^ Por conseguinte, desviaram-se ali para entrar, a fim de pernoitar em Gibeá. E passaram^&#42;1^ a entrar e a sentar-se na praça pública da cidade, e não houve quem os acolhesse em casa para pernoitarem.

[NOTE]
====
. “Passaram”, LXXSyVg; M: “passou”.
====

[[v7-19-16]]

^<<v7-19-16,16>>^ Finalmente, eis que vinha um homem idoso do seu trabalho no campo, ao anoitecer, e o homem era da região montanhosa de Efraim e residia por um tempo em Gibeá; mas os homens do lugar eram benjamitas.

[[v7-19-17]]

^<<v7-19-17,17>>^ Quando levantou os seus olhos, estava vendo o homem, o viajante, na praça pública da cidade. Disse, pois, o homem idoso: “Para onde vais e donde vens?”

[[v7-19-18]]

^<<v7-19-18,18>>^ Ele lhe disse, por sua vez: “Estamos de passagem de Belém de Judá para as partes mais remotas da região montanhosa de Efraim. Sou de lá, mas fui a Belém de Judá; e vou para a minha própria casa,^&#42;1^ e não há quem me acolha em casa.

[NOTE]
====
. “Para a minha própria casa”, LXX (veja o v. 29); MSy: “para a casa de Jeová”; Vg: “para a casa de Deus”. Mas KB, na p. 369, declara que, neste caso, talvez se confunda “Jeová” com o pronome possessivo hebr. da primeira pessoa do singular, “minha”.
====

[[v7-19-19]]

^<<v7-19-19,19>>^ E há tanto palha como forragem para os nossos jumentos, e há tanto pão como vinho para mim e para a tua escrava, e para o ajudante com o teu servo.^&#42;1^ Não há falta de coisa alguma.”

[NOTE]
====
. “Servo”, TSy; M: “servos”.
====

[[v7-19-20]]

^<<v7-19-20,20>>^ No entanto, o homem idoso disse: “Paz seja contigo!^&#42;1^ Deixa só ao meu cargo qualquer carência tua. Somente não pernoites na praça pública.”

[NOTE]
====
. Lit.: “Paz para ti.” Hebr.: sha·lóhm lakh.
====

[[v7-19-21]]

^<<v7-19-21,21>>^ Com isso o levou à sua casa e deu pasto aos jumentos. Depois lavaram os pés e começaram a comer e a beber.

[[v7-19-22]]

^<<v7-19-22,22>>^ Enquanto faziam seus corações sentir-se bem, eis que homens da cidade, homens imprestáveis,^&#42;1^ cercaram a casa, empurrando-se um ao outro contra a porta; e diziam ao homem idoso, o dono da casa: “Traze para fora o homem que veio à tua casa para que tenhamos relações com ele.”

[NOTE]
====
. Lit.: “homens dos filhos de belial (inutilidade)”.
====

[[v7-19-23]]

^<<v7-19-23,23>>^ Em vista disso, o dono da casa saiu a ter com eles e disse-lhes: “Não, meus irmãos, por favor, não cometais nenhum mal, visto que este homem entrou na minha casa. Não cometais esta ignominiosa insensatez.

[[v7-19-24]]

^<<v7-19-24,24>>^ Eis a minha filha virgem e a concubina dele. Por favor, deixai-mas trazer para fora, e violentai-as e fazei com elas o que for bom aos vossos olhos. Mas não deveis fazer a este homem tal coisa ignominiosa, insensata.”

[[v7-19-25]]

^<<v7-19-25,25>>^ E os homens não quiseram escutá-lo. Portanto, o homem agarrou a sua concubina e levou-a para fora a eles; e eles começaram a ter relações com ela e continuaram a abusar dela a noite inteira, até à manhã, mandando-a depois embora quando subiu a alva.

[[v7-19-26]]

^<<v7-19-26,26>>^ A mulher veio então por volta do amanhecer e caiu à entrada da casa do homem onde se achava seu amo — até a luz do dia.

[[v7-19-27]]

^<<v7-19-27,27>>^ Mais tarde se levantou seu amo, de manhã, e abriu as portas da casa e saiu para se pôr a caminho, e eis a mulher, sua concubina, caída à entrada da casa com as suas mãos sobre o limiar!

[[v7-19-28]]

^<<v7-19-28,28>>^ Disse-lhe, pois: “Levanta-te e vamos.” Mas não houve quem respondesse. O homem a pôs então sobre o jumento, e se levantou e foi para seu lugar.

[[v7-19-29]]

^<<v7-19-29,29>>^ Entrou então na sua casa e tomou o cutelo, e agarrou sua concubina e cortou-a em doze pedaços, conforme os seus ossos, e enviou-a a todo o território de Israel.

[[v7-19-30]]

^<<v7-19-30,30>>^ E sucedeu que todo aquele que viu isso disse: “Nunca aconteceu tal coisa nem se viu desde o dia em que os filhos de Israel subiram da terra do Egito até o dia de hoje. Fixai nisso os vossos corações,^&#42;1^ aconselhai-vos e falai.”

[NOTE]
====
. “Vossos corações”, T; M: “para vós mesmos”.
====

'''

xref:007-juizes/007-juizes-018.adoc#v7-18-0[&#60; Capítulo Anterior] | <<v7-19-0,Topo>> | xref:007-juizes/007-juizes-020.adoc#v7-20-0[Próximo Capítulo &#62;]