include::./index.adoc[]

[[v7-18-0]]
=== Juízes, 18
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v7-18-1]]

^<<v7-18-1,1>>^ Naqueles dias não havia rei em Israel. E naqueles dias, a tribo dos danitas procurava para si uma herança para nela morar; pois, até aquele dia não lhes havia caído nenhuma herança no meio das tribos de Israel.

[[v7-18-2]]

^<<v7-18-2,2>>^ Finalmente, os filhos de Dã enviaram cinco homens da sua família, homens dentre eles, homens valentes, desde Zorá e Estaol, para espionar o país e para explorá-lo. Disseram-lhes, pois: “Ide, explorai o país.” Com o tempo chegaram à região montanhosa de Efraim, até a casa de Micá e foram passar a noite ali.

[[v7-18-3]]

^<<v7-18-3,3>>^ Achando-se perto da casa de Micá, reconheceram a voz do moço, o levita, de modo que se desviaram para lá. E passaram a dizer-lhe: “Quem te trouxe para cá e que estás fazendo neste lugar, e que interesse tens aqui?”

[[v7-18-4]]

^<<v7-18-4,4>>^ Ele lhes disse, por sua vez: “Assim e assim me fez Micá para me contratar e para que eu lhe servisse de sacerdote.”

[[v7-18-5]]

^<<v7-18-5,5>>^ Então lhe disseram: “Por favor, indaga de Deus para sabermos se seremos bem sucedidos no nosso caminho em que andamos.”

[[v7-18-6]]

^<<v7-18-6,6>>^ Assim, o sacerdote lhes disse: “Ide em paz. Vosso caminho em que andais está diante de Jeová.”

[[v7-18-7]]

^<<v7-18-7,7>>^ Portanto, os cinco homens prosseguiram e chegaram a Laís, e viram como o povo que havia nela morava confiante em si, segundo o costume dos sidônios, sossegado e insuspeitoso, e não havia conquistador opressivo^&#42;1^ que molestasse coisa alguma no país, ao passo que se achavam longe dos sidônios e não tinham nada que ver com a humanidade.^&#42;2^

[NOTE]
====
. Ou “desapossador opressivo”. Lit.: “desapossador (ocupante) de opressão”. Veja VT, Vol. II, 1952, pp. 67-69.
. “Com a Síria”, LXXASymSyHexapla.
====

[[v7-18-8]]

^<<v7-18-8,8>>^ Por fim chegaram a seus irmãos em Zorá e Estaol, e seus irmãos começaram a dizer-lhes: “Como foi convosco?”

[[v7-18-9]]

^<<v7-18-9,9>>^ A isso disseram: “Levantai-vos deveras, e subamos contra eles; pois vimos o país e eis que é muito bom. E vós hesitais. Não sejais indolentes quanto a andar para entrar, a fim de tomar posse do país.

[[v7-18-10]]

^<<v7-18-10,10>>^ Entrando, chegareis a um povo insuspeitoso, e a terra é bastante ampla;^&#42;1^ pois, Deus^&#42;2^ a entregou na vossa mão, um lugar em que não há falta de coisa alguma que há na terra.”

[NOTE]
====
. Lit.: “ampla em ambos os lados”, isto é, espaçosa.
. “Deus”, MLXXSy; TVg: “Jeová”.
====

[[v7-18-11]]

^<<v7-18-11,11>>^ Então seiscentos homens, cingidos de armas de guerra, da família dos danitas, partiram dali, isto é, de Zorá e Estaol.

[[v7-18-12]]

^<<v7-18-12,12>>^ E seguiram para cima e foram acampar-se em Quiriate-Jearim, em Judá. É por isso que chamaram aquele lugar de Maané-Dã^&#42;1^ até o dia de hoje. Eis que está ao oeste^&#42;2^ de Quiriate-Jearim.

[NOTE]
====
. Significando “Acampamento de Dã”.
. Lit.: “atrás”, isto é, quando se encara o leste.
====

[[v7-18-13]]

^<<v7-18-13,13>>^ Depois passaram dali adiante para a região montanhosa de Efraim e chegaram até a casa de Micá.

[[v7-18-14]]

^<<v7-18-14,14>>^ Responderam então os cinco homens que haviam ido espionar a terra de Laís e disseram a seus irmãos: “Sabíeis que nestas casas há um éfode, e terafins, e uma imagem esculpida, e uma estátua fundida? E agora considerai o que deveis fazer.”

[[v7-18-15]]

^<<v7-18-15,15>>^ Por isso se desviaram para lá e chegaram à casa do moço, o levita, junto à casa de Micá, e começaram a perguntar como estava passando.

[[v7-18-16]]

^<<v7-18-16,16>>^ Enquanto isso, os seiscentos homens cingidos das suas armas de guerra, que eram dos filhos de Dã, ficaram de pé à entrada do portão.

[[v7-18-17]]

^<<v7-18-17,17>>^ Os cinco homens que haviam ido espionar o país subiram então para entrar, a fim de tomar^&#42;1^ a imagem esculpida, e o éfode, e os terafins, e a imagem fundida. (E o sacerdote estava de pé junto à entrada do portão com os seiscentos homens cingidos de armas de guerra.)^&#42;2^

[NOTE]
====
. Lit.: “subiram, entraram ali, tomaram”.
. Ou “e a imagem fundida, e o sacerdote, enquanto os seiscentos homens cingidos de armas de guerra estavam de pé à entrada do portão”.
====

[[v7-18-18]]

^<<v7-18-18,18>>^ E estes entraram na casa de Micá e passaram a tomar a imagem esculpida, o éfode e os terafins, e a imagem fundida. Em vista disso, o sacerdote lhes disse: “Que estais fazendo?”

[[v7-18-19]]

^<<v7-18-19,19>>^ Mas eles lhe disseram: “Cala-te. Põe a mão sobre a boca e vem conosco, e torna-te para nós pai e sacerdote. O que é melhor, continuares como sacerdote para a casa de um só homem ou te tornares sacerdote para uma tribo e família em Israel?”

[[v7-18-20]]

^<<v7-18-20,20>>^ E o coração do sacerdote se agradou disso, e ele tomou então o éfode, e os terafins, e a imagem esculpida, e entrou no meio do povo.

[[v7-18-21]]

^<<v7-18-21,21>>^ Então se viraram e seguiram caminho, e puseram os pequeninos e o gado, bem como as coisas valiosas, na sua frente.

[[v7-18-22]]

^<<v7-18-22,22>>^ Eles mesmos tinham atingido certa distância da casa de Micá quando os homens nas casas próximas da casa de Micá foram convocados e tentaram alcançar os filhos de Dã.

[[v7-18-23]]

^<<v7-18-23,23>>^ Quando clamaram para os filhos de Dã, então estes voltaram as suas faces e disseram a Micá: “Que tens que foste convocado?”

[[v7-18-24]]

^<<v7-18-24,24>>^ Ele disse, pois: “Tomastes os meus deuses que eu fiz, também o sacerdote, e seguis caminho, e o que me resta? Como é, então, que me podeis dizer: ‘Que tens?’”

[[v7-18-25]]

^<<v7-18-25,25>>^ A isso os filhos de Dã lhe disseram: “Não se ouça a tua voz perto de nós, para que homens de alma amargurada não vos ataquem e tenhas de perder a tua própria alma^&#42;1^ e a alma dos da tua casa.”

[NOTE]
====
. “Tua própria alma (vida).” Hebr.: naf·shekhá; LXXA(gr.): psy·khén sou; sir.: naf·shakh.
====

[[v7-18-26]]

^<<v7-18-26,26>>^ E os filhos de Dã seguiram seu caminho; e Micá via que eram mais fortes do que ele, e por isso se virou e voltou para a sua casa.

[[v7-18-27]]

^<<v7-18-27,27>>^ Quanto a eles, tomaram o que Micá tinha feito, bem como o sacerdote que se tornara seu, e foram para Laís, contra um povo sossegado e insuspeitoso. E passaram a golpeá-los com o fio da espada e queimaram a cidade com fogo.

[[v7-18-28]]

^<<v7-18-28,28>>^ E não houve quem [os] livrasse, pois era longe de Sídon e não tinham absolutamente nada que ver com a humanidade; e achava-se na baixada que pertencia a Bete-Reobe. Construíram então a cidade e passaram a morar nela.

[[v7-18-29]]

^<<v7-18-29,29>>^ Além disso, chamaram a cidade pelo nome de Dã, segundo o nome de seu pai, Dã, que nascera a Israel. Não obstante, no princípio o nome da cidade era Laís.

[[v7-18-30]]

^<<v7-18-30,30>>^ Após isso, os filhos de Dã erigiram para si a imagem esculpida; e Jonatã,^&#42;1^ filho de Gersom, filho de Moisés,^&#42;2^ ele e seus filhos se tornaram sacerdotes para a tribo dos danitas até o dia em que o país^&#42;3^ foi levado ao exílio.

[NOTE]
====
. Lit.: “Jeonatã”, significando “Jeová Deu”.
. “De Moisés”, LXXAVg; MLXXBSy: “de Manassés”. Por respeito a Moisés, os escribas inseriram no M a letra hebr. suspensa nune, “n”, no nome original, fazendo com que rezasse “de Manassés”.
. “O país.” Hebr.: ha·’á·rets. Alguns afirmam que deveria rezar “a arca” (ארון, ’aróhn), em vez de “o país (ou: a terra)” (ארץ, ’á·rets), referindo-se a 1Sa 4:3–7:2.
====

[[v7-18-31]]

^<<v7-18-31,31>>^ E a imagem esculpida de Micá, que este tinha feito, mantiveram erigida para si todos os dias em que a casa do [verdadeiro] Deus permanecia em Silo.

'''

xref:007-juizes/007-juizes-017.adoc#v7-17-0[&#60; Capítulo Anterior] | <<v7-18-0,Topo>> | xref:007-juizes/007-juizes-019.adoc#v7-19-0[Próximo Capítulo &#62;]