include::./index.adoc[]

[[v7-2-0]]
=== Juízes, 2
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v7-2-1]]

^<<v7-2-1,1>>^ O anjo de Jeová subiu então de Gilgal a Boquim e disse: “Passei a fazer-vos subir do Egito e a trazer-vos à terra a respeito da qual jurei^&#42;1^ aos vossos antepassados. Ademais, eu disse: ‘Nunca violarei meu pacto convosco.

[NOTE]
====
. Ou “terra que prometi sob juramento”.
====

[[v7-2-2]]

^<<v7-2-2,2>>^ E vós, da vossa parte, não deveis concluir nenhum pacto com os habitantes desta terra. Deveis demolir seus altares.’ Mas não escutastes a minha voz. Por que fizestes isso?

[[v7-2-3]]

^<<v7-2-3,3>>^ Por isso eu disse, da minha parte: ‘Não os expulsarei de diante de vós, e eles têm de tornar-se ciladas para vós, e seus deuses servirão de laço para vós.’”

[[v7-2-4]]

^<<v7-2-4,4>>^ E sucedeu que, assim que o anjo de Jeová havia falado estas palavras a todos os filhos de Israel, o povo começou a levantar a sua voz e a chorar.

[[v7-2-5]]

^<<v7-2-5,5>>^ Por isso chamaram o lugar pelo nome de Boquim.^&#42;1^ E passaram a oferecer ali sacrifícios a Jeová.

[NOTE]
====
. Significando “Chorões”.
====

[[v7-2-6]]

^<<v7-2-6,6>>^ Quando Josué mandou o povo embora, então os filhos de Israel seguiram seu caminho, cada um para a sua herança, para tomar posse do país.

[[v7-2-7]]

^<<v7-2-7,7>>^ E o povo continuou a servir a Jeová todos os dias de Josué e todos os dias dos anciãos^&#42;1^ que prolongaram os seus dias depois de Josué,^&#42;2^ e que tinham visto todo o grande trabalho de Jeová, que ele fizera para Israel.

[NOTE]
====
. “Dos anciãos.” Hebr.: haz·zeqe·ním; gr.: pre·sby·té·ron. Veja At 15:2 n.
. Ou “que sobreviveram a Josué”.
====

[[v7-2-8]]

^<<v7-2-8,8>>^ Josué, filho de Num, servo de Jeová, morreu então à idade de cento e dez anos.

[[v7-2-9]]

^<<v7-2-9,9>>^ Enterraram-no, pois, no território de sua herança, em Timnate-Heres,^&#42;1^ na região montanhosa de Efraim, ao norte do monte Gaás.

[NOTE]
====
. “Timnate-Heres”, MLXX; SyVg: “Timnate-Sera”. Veja Jos 19:50; Jos 24:30.
====

[[v7-2-10]]

^<<v7-2-10,10>>^ E também toda aquela geração foi ajuntada aos seus pais, e após eles começou a surgir outra geração que não conhecia a Jeová, nem o trabalho que tinha feito para Israel.

[[v7-2-11]]

^<<v7-2-11,11>>^ E os filhos de Israel puseram-se a fazer o que era mau aos olhos de Jeová e a servir^&#42;1^ aos Baalins.

[NOTE]
====
. “E a servir (adorar).” Hebr.: wai·ya·‛av·dhú; LXXA(gr.): e·lá·treu·on, “e a prestar serviço sagrado”. Veja Êx 3:12 n.
====

[[v7-2-12]]

^<<v7-2-12,12>>^ Deste modo abandonaram a Jeová, o Deus de seus pais, que os havia trazido para fora da terra do Egito, e foram seguir a outros deuses dentre os deuses dos povos ao redor deles e começaram a curvar-se diante deles, de modo que ofenderam a Jeová.

[[v7-2-13]]

^<<v7-2-13,13>>^ Assim abandonaram a Jeová e passaram a servir a Baal e às imagens de Astorete.^&#42;1^

[NOTE]
====
. “E às imagens de Astorete.” Lit.: “e às Astarotes”, isto é, às imagens ou manifestações desta deusa pagã. Hebr.: wela·‛Ash·ta·róhth; gr.: tais A·stár·tais, “às Astartes”; lat.: Á·stha·roth.
====

[[v7-2-14]]

^<<v7-2-14,14>>^ Em vista disso acendeu-se a ira de Jeová contra Israel, de modo que os entregou nas mãos de rapinantes e estes começaram a rapiná-los; e ele passou a vendê-los^&#42;1^ à mão dos seus inimigos ao redor e não mais se puderam manter de pé diante dos seus inimigos.

[NOTE]
====
. “Entregá-los”, LXX.
====

[[v7-2-15]]

^<<v7-2-15,15>>^ Por onde quer que saíssem, a mão de Jeová se mostrava contra eles para calamidade, assim como Jeová havia falado e assim como Jeová lhes havia jurado; e ficaram em sério aperto.

[[v7-2-16]]

^<<v7-2-16,16>>^ Portanto, Jeová suscitava juízes e estes os salvavam da mão dos seus rapinantes.

[[v7-2-17]]

^<<v7-2-17,17>>^ E não escutaram nem mesmo os seus juízes, mas tiveram relações imorais^&#42;1^ com outros deuses e foram curvar-se diante deles. Desviaram-se depressa do caminho em que seus antepassados haviam andado por obedecerem aos mandamentos de Jeová. Eles não fizeram assim.

[NOTE]
====
. Ou “cometeram fornicação (imoralidade)”. Gr.: e·xe·pór·neu·san. Veja Ap. 5A.
====

[[v7-2-18]]

^<<v7-2-18,18>>^ E quando Jeová lhes suscitou juízes, Jeová mostrou estar com o juiz e os salvou da mão dos seus inimigos, todos os dias do juiz; pois Jeová deplorava seu gemido por causa dos seus opressores e dos que os empurravam.

[[v7-2-19]]

^<<v7-2-19,19>>^ E acontecia que, morrendo o juiz, voltavam atrás e agiam mais ruinosamente do que seus pais, andando após outros deuses para os servir e se curvar diante deles. Não desistiram das suas práticas, nem do seu proceder obstinado.

[[v7-2-20]]

^<<v7-2-20,20>>^ Por fim se acendeu a ira de Jeová contra Israel e ele disse: “Visto que esta nação infringiu meu pacto que ordenei aos seus antepassados e não escutou a minha voz,

[[v7-2-21]]

^<<v7-2-21,21>>^ eu, da minha parte, tampouco desalojarei mais de diante deles nem uma única das nações que Josué deixou quando morreu,

[[v7-2-22]]

^<<v7-2-22,22>>^ para por elas provar a Israel, se guardarão ou não o caminho de Jeová, andando nele assim como seus antepassados o guardaram.”

[[v7-2-23]]

^<<v7-2-23,23>>^ Por conseguinte, Jeová deixou estas nações ficar, não as desalojando depressa, e ele não as entregou na mão de Josué.

'''

xref:007-juizes/007-juizes-001.adoc#v7-1-0[&#60; Capítulo Anterior] | <<v7-2-0,Topo>> | xref:007-juizes/007-juizes-003.adoc#v7-3-0[Próximo Capítulo &#62;]