include::./index.adoc[]

[[v7-16-0]]
=== Juízes, 16
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v7-16-1]]

^<<v7-16-1,1>>^ Certa vez, Sansão foi a Gaza e viu ali uma mulher prostituta, e entrando, foi ter com ela.

[[v7-16-2]]

^<<v7-16-2,2>>^ E relatou-se^&#42;1^ aos gazitas, dizendo-se: “Sansão entrou aqui.” Cercaram-no, pois, e ficaram de emboscada contra ele a noite inteira no portão da cidade. E ficaram quietos a noite inteira, dizendo: “Assim que a manhã clarear, então teremos de matá-lo.”

[NOTE]
====
. “E relatou-se”, LXX; M omite isso.
====

[[v7-16-3]]

^<<v7-16-3,3>>^ No entanto, Sansão ficou deitado até à meia-noite, e então se levantou à meia-noite e foi segurar as portas do portão da cidade e as duas ombreiras, e arrancou-as junto com a tranca, e as pôs sobre os seus ombros e foi carregá-las para cima ao cume do monte que está defronte de Hébron.^&#42;1^

[NOTE]
====
. LXX acrescenta: “e as colocou ali”.
====

[[v7-16-4]]

^<<v7-16-4,4>>^ E sucedeu, depois, que ele se enamorou duma mulher no vale da torrente de Soreque, e o nome dela era Dalila.

[[v7-16-5]]

^<<v7-16-5,5>>^ E os senhores do eixo dos filisteus passaram a subir até ela e a dizer-lhe: “Logra-o e vê em que consiste seu grande poder, e com que podemos prevalecer contra ele, e com que podemos com certeza amarrá-lo para o dominar; e nós, da nossa parte, te daremos cada um mil e cem moedas de prata.”

[[v7-16-6]]

^<<v7-16-6,6>>^ Posteriormente, Dalila disse a Sansão: “Por favor, declara-me deveras: Em que consiste teu grande poder e com que podes ser amarrado para alguém te dominar?”

[[v7-16-7]]

^<<v7-16-7,7>>^ Sansão lhe disse então: “Se me amarrarem com sete tendões ainda úmidos, que não se secaram, então terei de ficar fraco e tornar-me igual a um homem comum.”

[[v7-16-8]]

^<<v7-16-8,8>>^ Portanto, os senhores do eixo dos filisteus trouxeram-lhe sete tendões ainda úmidos que não se secaram. Depois ela o amarrou com eles.

[[v7-16-9]]

^<<v7-16-9,9>>^ Ora, [os da] emboscada estavam sentados no quarto interior dela, e ela começou a dizer-lhe: “Os filisteus estão sobre ti, Sansão!” Nisso ele rompeu os tendões, assim como se rompe o fio retorcido da estopa quando cheira fogo. E não se ficou conhecendo seu poder.

[[v7-16-10]]

^<<v7-16-10,10>>^ Subseqüentemente, Dalila disse a Sansão: “Eis que zombaste de mim para falar-me mentiras. Agora, por favor, dize-me deveras com que podes ser amarrado.”

[[v7-16-11]]

^<<v7-16-11,11>>^ Ele lhe disse, portanto: “Se me amarrarem firmemente com cordas novas com que não se fez ainda nenhuma obra, então terei de ficar fraco e tornar-me igual a um homem comum.”

[[v7-16-12]]

^<<v7-16-12,12>>^ Dalila tomou, pois, cordas novas e o amarrou com elas, e disse-lhe: “Os filisteus estão sobre ti, Sansão!” Enquanto isso, os da emboscada estavam sentados no quarto interior. Nisso as rompeu, arrancando-as dos seus braços como se fossem um fio.

[[v7-16-13]]

^<<v7-16-13,13>>^ Mais tarde, Dalila disse a Sansão: “Até agora zombaste de mim para falar-me mentiras. Declara-me deveras com que podes ser amarrado.” Então ele lhe disse: “Se teceres as sete tranças da minha cabeça com o fio da urdidura.”

[[v7-16-14]]

^<<v7-16-14,14>>^ Concordemente, ela as fixou com o pino,^&#42;1^ dizendo-lhe: “Os filisteus estão sobre ti, Sansão!” Ele acordou então do seu sono e arrancou o pino de tear e o fio da urdidura.

[NOTE]
====
. “E aconteceu que, enquanto ele estava dormindo, Dalila tomou as sete tranças da cabeça dele e as teceu na urdidura, e as prendeu ao pino na parede”, LXXB.
====

[[v7-16-15]]

^<<v7-16-15,15>>^ Ela lhe disse então: “Como te atreves a dizer: ‘Eu te amo’, quando teu coração não está comigo? Zombaste de mim estas três vezes e não me declaraste em que consiste teu grande poder.”

[[v7-16-16]]

^<<v7-16-16,16>>^ E sucedeu que, assediando-o ela todo o tempo com as suas palavras e instando com ele, a alma dele ficou impaciente até à morte.

[[v7-16-17]]

^<<v7-16-17,17>>^ Por fim lhe expôs todo o seu coração e lhe disse: “Nunca veio navalha sobre a minha cabeça, por ser eu nazireu de Deus desde o ventre de minha mãe. Se eu fosse rapado, então certamente se retiraria de mim o meu poder, e eu ficaria deveras fraco e me tornaria igual a todos os demais homens.”

[[v7-16-18]]

^<<v7-16-18,18>>^ E vendo Dalila que lhe revelara todo o seu coração, mandou chamar imediatamente os senhores do eixo filisteus, dizendo: “Subi esta vez, pois ele me expôs todo o seu coração.” E os senhores do eixo filisteus subiram até ela para trazer o dinheiro na sua mão.

[[v7-16-19]]

^<<v7-16-19,19>>^ E ela passou a fazê-lo dormir sobre os seus joelhos. Chamou então o homem e fez que lhe rapasse as sete tranças da cabeça, após o que principiou a mostrar seu domínio sobre ele, e o poder dele continuou a se retirar dele.

[[v7-16-20]]

^<<v7-16-20,20>>^ Ela disse então: “Os filisteus estão sobre ti, Sansão!” Com isto ele acordou do seu sono e disse: “Eu me sairei disso como das outras vezes e me desembaraçarei.” E ele mesmo não sabia que foi Jeová quem se retirara dele.

[[v7-16-21]]

^<<v7-16-21,21>>^ Portanto, os filisteus o seguraram e lhe furaram os olhos, e levaram-no para baixo a Gaza, e prenderam-no com dois grilhões de cobre; e ele veio a ser moedor na casa dos presos.

[[v7-16-22]]

^<<v7-16-22,22>>^ Entrementes principiou a crescer-lhe abundantemente o cabelo da cabeça, desde que fora rapado.

[[v7-16-23]]

^<<v7-16-23,23>>^ Quanto aos senhores do eixo filisteus, ajuntaram-se para oferecer um grande sacrifício a Dagom, seu deus, e para alegrar-se, e diziam: “Nosso deus^&#42;1^ nos deu na mão a Sansão, nosso inimigo!”

[NOTE]
====
. “Nosso deus.” Hebr.: ’elo·héh·nu, pl., para denotar excelência, aplicado a Dagom, e com o verbo no sing.; LXXA(gr.): the·ós; lat.: dé·us. Veja 1Sa 5:7; 2Rs 19:37.
====

[[v7-16-24]]

^<<v7-16-24,24>>^ E vendo-o o povo, foram imediatamente louvar seu deus, “porque”, diziam eles, “nosso deus nos entregou na mão o nosso inimigo e o devastador de nossa terra, e aquele que multiplicava os nossos mortos”.

[[v7-16-25]]

^<<v7-16-25,25>>^ E sucedeu que, estando alegre o coração deles, começaram a dizer: “Chamai a Sansão, para que nos divirta.” De modo que chamaram a Sansão da casa dos presos para servir de diversão diante deles; e passaram a fazê-lo ficar de pé entre as colunas.

[[v7-16-26]]

^<<v7-16-26,26>>^ Sansão disse então ao rapaz que lhe segurava a mão: “Deixa-me apalpar as colunas em que se firma a casa e deixa-me encostar-me nelas.”

[[v7-16-27]]

^<<v7-16-27,27>>^ (Incidentalmente, a casa estava cheia de homens e de mulheres, e estavam ali todos os senhores do eixo filisteus; e no terraço havia cerca de três mil homens e mulheres que olhavam enquanto Sansão os divertia.)

[[v7-16-28]]

^<<v7-16-28,28>>^ Sansão clamou então a Jeová e disse: “Soberano Senhor Jeová,^&#42;1^ por favor, lembra-te de mim e fortalece-me só esta vez, por favor, ó tu, o [verdadeiro] Deus, e vingue-me eu dos filisteus com vingança por um dos meus dois olhos.”^&#42;2^

[NOTE]
====
. “Soberano Senhor Jeová.” Hebr.: ’Adho·naí Yeho·wíh; LXXB(gr.): A·do·na·i·é Ký·ri·e; lat.: Dó·mi·ne Dé·us. Veja Ap. 1E.
. “E eu me vingarei dos estrangeiros (filisteus) com uma só vingança pelos meus dois olhos”, LXX; Vg: “que eu me vingue dos meus inimigos e receba uma só vingança pela perda dos dois olhos”.
====

[[v7-16-29]]

^<<v7-16-29,29>>^ Com isso, Sansão se firmou nas duas colunas do meio em que a casa se fundava firmemente e foi segurá-las, uma com a sua direita e a outra com a sua esquerda.

[[v7-16-30]]

^<<v7-16-30,30>>^ E Sansão passou a dizer: “Morra a minha alma com os filisteus.” Então se encurvou com poder e a casa foi cair sobre os senhores do eixo e sobre todo o povo que havia nela, de modo que os mortos, que entregou à morte ao ele mesmo morrer, vieram a ser mais do que os que entregara à morte durante a sua vida.

[[v7-16-31]]

^<<v7-16-31,31>>^ Mais tarde desceram seus irmãos e todos os da casa de seu pai e o levantaram, e levaram-no para cima e enterraram-no entre Zorá e Estaol, na sepultura de Manoá, seu pai. Quanto a ele, julgara a Israel por vinte anos.

'''

xref:007-juizes/007-juizes-015.adoc#v7-15-0[&#60; Capítulo Anterior] | <<v7-16-0,Topo>> | xref:007-juizes/007-juizes-017.adoc#v7-17-0[Próximo Capítulo &#62;]