include::./index.adoc[]

[[v7-15-0]]
=== Juízes, 15
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v7-15-1]]

^<<v7-15-1,1>>^ E depois de algum tempo, nos dias da sega do trigo, sucedeu que Sansão foi visitar sua esposa, levando um cabritinho. Disse, pois: “Hei de entrar, indo ter com a minha esposa no quarto interior.” E o pai dela não o deixou entrar.

[[v7-15-2]]

^<<v7-15-2,2>>^ Mas o pai dela disse: “Eu disse realmente comigo: ‘Sem dúvida a deves odiar.’ Por isso a dei a teu padrinho. Não é sua irmã mais moça melhor do que ela? Por favor, torne-se ela tua em lugar da outra.”

[[v7-15-3]]

^<<v7-15-3,3>>^ No entanto, Sansão lhes disse: “Esta vez tenho de estar livre de culpa contra os filisteus, caso eu trate com eles para o seu prejuízo.”

[[v7-15-4]]

^<<v7-15-4,4>>^ E Sansão seguiu seu caminho e passou a apanhar trezentas raposas^&#42;1^ e a tomar tochas, e passou a virar cauda a cauda e a pôr uma tocha entre duas caudas, bem no meio.

[NOTE]
====
. Possivelmente “chacais”.
====

[[v7-15-5]]

^<<v7-15-5,5>>^ Então, pôs fogo às tochas e soltou-as nos campos de cereais em pé, pertencentes aos filisteus. Assim pôs fogo a tudo, desde os feixes até os cereais em pé, e até os vinhedos e os olivais.

[[v7-15-6]]

^<<v7-15-6,6>>^ E os filisteus começaram a dizer: “Quem fez isso?” Então disseram: “Foi Sansão, genro do timnita, porque lhe tomou a esposa e então a deu ao padrinho dele.” Em vista disso, os filisteus subiram e queimaram tanto a ela como a seu pai com fogo.

[[v7-15-7]]

^<<v7-15-7,7>>^ Sansão disse-lhes, por sua vez: “Se procedeis assim, nada me resta senão vingar-me de vós, e depois vou cessar.”

[[v7-15-8]]

^<<v7-15-8,8>>^ E ele foi golpeá-los, [empilhando] pernas sobre coxas, com uma grande matança, após o que desceu e começou a morar numa fenda do rochedo de Étão.

[[v7-15-9]]

^<<v7-15-9,9>>^ Mais tarde, os filisteus subiram e se acamparam em Judá, e andaram percorrendo Leí.

[[v7-15-10]]

^<<v7-15-10,10>>^ Então disseram os homens de Judá: “Por que subistes contra nós?” ao que disseram: “Subimos para prender Sansão, para fazer com ele assim como ele fez conosco.”

[[v7-15-11]]

^<<v7-15-11,11>>^ Portanto, três mil homens de Judá desceram à fenda do rochedo de Étão e disseram a Sansão: “Não sabes que os filisteus estão dominando sobre nós? Assim, pois, o que quer dizer isso que nos fizeste?” Ele lhes disse então: “Assim como me fizeram a mim, eu fiz a eles.”

[[v7-15-12]]

^<<v7-15-12,12>>^ Mas eles lhe disseram: “Foi para prender-te que descemos, para entregar-te na mão dos filisteus.” A isso Sansão lhes disse: “Jurai-me que vós mesmos não me atacareis.”

[[v7-15-13]]

^<<v7-15-13,13>>^ E eles prosseguiram, dizendo-lhe: “Não, mas apenas te prenderemos e te entregaremos na sua mão; mas nós de modo algum te faremos morrer.”
Por conseguinte, prenderam-no com duas cordas novas e fizeram-no subir do rochedo.

[[v7-15-14]]

^<<v7-15-14,14>>^ Ele, da sua parte, veio até Leí, e os filisteus, da parte deles, gritaram de júbilo ao se encontrarem com ele. E o espírito de Jeová tornou-se ativo nele e as cordas que havia sobre os seus braços vieram a ser como fios de linho quando abrasados pelo fogo, de modo que seus grilhões se derreteram de cima das suas mãos.

[[v7-15-15]]

^<<v7-15-15,15>>^ Ele achou então uma queixada^&#42;1^ fresca de jumento, e estendeu a mão e tomou-a, e com ela foi matar a golpes mil homens.

[NOTE]
====
. “Queixada . . . de.” Hebr.: lehhí.
====

[[v7-15-16]]

^<<v7-15-16,16>>^ Sansão disse então:
“Com a queixada dum jumento — um montão, dois montões!^&#42;1^
Com a queixada dum jumento golpeei mil homens.”

[NOTE]
====
. “Um montão, dois montões!” Alterando-se os sinais vocálicos: “empilhei-os bem”; LXX: “exterminei-os cabalmente”.
====

[[v7-15-17]]

^<<v7-15-17,17>>^ E sucedeu que, acabando ele de falar, lançou imediatamente a queixada da sua mão e chamou aquele lugar de Ramate-Leí.^&#42;1^

[NOTE]
====
. Significando “O Lugar Elevado da Queixada”.
====

[[v7-15-18]]

^<<v7-15-18,18>>^ Ficou então com muita sede, e começou a invocar a Jeová e a dizer: “Foste tu quem deste esta grande salvação na mão do teu servo, e agora, morrerei de sede e terei de cair na mão dos incircuncisos?”

[[v7-15-19]]

^<<v7-15-19,19>>^ Portanto, Deus^&#42;1^ fendeu uma cavidade em forma de almofariz, que havia em Leí,^&#42;2^ e dela começou a sair água,^&#42;3^ e ele passou a beber, voltando-lhe depois o espírito, e ele se reanimou. Foi por isso que a chamou pelo nome de En-Hacoré,^&#42;4^ que se acha em Leí até o dia de hoje.

[NOTE]
====
. “Deus”, MLXX; Sy: “Jeová Deus”; TVg: “Jeová”.
. Lit.: “na Leí”. Hebr.: bal·Lé·hhi. “Leí” significa “Queixada”.
. “E Deus rachou a concavidade que havia na maxila e dela saiu água”, LXXB; Sy: “E Jeová rachou a maxila da face do jumento e dela saiu água”; Vg: “De modo que Jeová [lat.: Dó·mi·nus] abriu um molar na queixada do jumento e dele saíram águas.”
. Significando “Fonte do Homem Que Chama”.
====

[[v7-15-20]]

^<<v7-15-20,20>>^ E ele continuou a julgar Israel nos dias dos filisteus por vinte anos.

'''

xref:007-juizes/007-juizes-014.adoc#v7-14-0[&#60; Capítulo Anterior] | <<v7-15-0,Topo>> | xref:007-juizes/007-juizes-016.adoc#v7-16-0[Próximo Capítulo &#62;]