include::./index.adoc[]

[[v7-17-0]]
=== Juízes, 17
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v7-17-1]]

^<<v7-17-1,1>>^ Ora, aconteceu que havia um homem da região montanhosa de Efraim, cujo nome era Micá.^&#42;1^

[NOTE]
====
. Significando “Quem É Semelhante a Jeová?” Hebr.: Mi·khá·yehu.
====

[[v7-17-2]]

^<<v7-17-2,2>>^ Passado tempo, ele disse à sua mãe: “As mil e cem moedas de prata que te foram tiradas e sobre as quais proferiste uma maldição, e também a disseste aos meus ouvidos — eis que a prata está comigo. Fui eu quem a tomou.” A isso sua mãe disse: “Bendito de Jeová seja meu filho.”

[[v7-17-3]]

^<<v7-17-3,3>>^ Por conseguinte, ele devolveu à sua mãe as mil e cem moedas de prata; e sua mãe prosseguiu, dizendo: “Sem falta tenho de santificar a prata a Jeová, da minha mão, por meu filho, para fazer uma imagem esculpida e uma estátua fundida; e agora a devolverei a ti.”^&#42;1^

[NOTE]
====
. “E agora a devolverei a ti.” Alguns sugerem que esta frase deveria ser transferida para o v. 2, após as palavras: “Fui eu quem a tomou.”
====

[[v7-17-4]]

^<<v7-17-4,4>>^ De modo que ele restituiu a prata à sua mãe, e sua mãe tomou duzentas moedas de prata e as deu ao prateiro. E ele foi fazer uma imagem esculpida e uma estátua fundida; e esta veio a ficar na casa de Micá.

[[v7-17-5]]

^<<v7-17-5,5>>^ Quanto ao homem Micá,^&#42;1^ tinha uma casa de deuses,^&#42;2^ e ele passou a fazer um éfode e terafins,^&#42;3^ e passou a encher de poder a mão de um dos seus filhos^&#42;4^ para que lhe servisse de sacerdote.

[NOTE]
====
. “Micá.” Hebr.: Mi·kháh.
. “Deuses.” Hebr.: ’elo·hím; gr.: the·oú, “deus”. Veja 18:24.
. Veja Gên 31:19 n.
. Ou “e a instalar um dos seus filhos”.
====

[[v7-17-6]]

^<<v7-17-6,6>>^ Naqueles dias não havia rei em Israel. No que se referia a cada um, fazia o que era direito aos seus próprios olhos.

[[v7-17-7]]

^<<v7-17-7,7>>^ Ora, aconteceu que havia um moço de Belém, em Judá, da família de Judá,^&#42;1^ e ele era levita.^&#42;2^ E residia ali por um tempo.

[NOTE]
====
. Possivelmente: “da família de Moisés”. Veja 18:30.
. Ou “e que era levita”, MLXXVg; Sy: “e seu nome era Levi”.
====

[[v7-17-8]]

^<<v7-17-8,8>>^ E o homem passou a sair da cidade de Belém, em Judá, para residir por um tempo onde quer que achasse lugar. Por fim, seguindo seu caminho, chegou à região montanhosa de Efraim, até a casa de Micá.

[[v7-17-9]]

^<<v7-17-9,9>>^ Micá lhe disse então: “Donde vens?” A isso lhe disse: “Sou levita de Belém, em Judá, e estou indo para residir por um tempo onde quer que eu ache lugar.”

[[v7-17-10]]

^<<v7-17-10,10>>^ Micá lhe disse, pois: “Mora deveras comigo e serve-me de pai e de sacerdote, e eu, da minha parte, te darei dez moedas de prata por ano e a costumeira muda de roupa, e teu sustento.” Por conseguinte, o levita entrou.

[[v7-17-11]]

^<<v7-17-11,11>>^ Assim, o levita resolveu-se a morar com o homem, e o moço ficou sendo para ele como um dos seus filhos.

[[v7-17-12]]

^<<v7-17-12,12>>^ Além disso, Micá encheu de poder a mão do levita para que o moço lhe servisse de sacerdote e continuasse na casa de Micá.

[[v7-17-13]]

^<<v7-17-13,13>>^ Micá disse então: “Agora sei que Jeová me fará o bem, pois o levita se tornou sacerdote para mim.”

'''

xref:007-juizes/007-juizes-016.adoc#v7-16-0[&#60; Capítulo Anterior] | <<v7-17-0,Topo>> | xref:007-juizes/007-juizes-018.adoc#v7-18-0[Próximo Capítulo &#62;]