include::./index.adoc[]

[[v7-7-0]]
=== Juízes, 7
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v7-7-1]]

^<<v7-7-1,1>>^ Então Jerubaal, isto é, Gideão, se levantou cedo, bem como todo o povo que estava com ele, e foram acampar-se junto ao poço de Harode;^&#42;1^ e o acampamento de Midiã ficava ao norte dele, junto ao morro de Moré, na baixada.

[NOTE]
====
. Significando “Tremor”.
====

[[v7-7-2]]

^<<v7-7-2,2>>^ Jeová disse então a Gideão: “É demais o povo que está contigo para eu entregar Midiã na tua mão. Israel talvez se gabe contra mim, dizendo: ‘Foi a minha mão que me salvou.’

[[v7-7-3]]

^<<v7-7-3,3>>^ E agora, por favor, clama aos ouvidos do povo, dizendo: ‘Quem está com medo e treme? Retire-se ele.’” Gideão os pôs assim à prova.^&#42;1^ Com isso se retiraram vinte e dois mil do povo e restaram dez mil.

[NOTE]
====
. “Gideão os pôs assim à prova”, mediante uma correção; M: “e parta ele cedo do monte Gileade”. Alguns rezam aqui “Gilboa” em vez de “Gileade”.
====

[[v7-7-4]]

^<<v7-7-4,4>>^ Contudo, Jeová disse a Gideão: “Ainda há povo demais. Faze-os descer até a água para que eu os ponha ali à prova para ti. E tem de dar-se que aquele de quem eu disser: ‘Este irá contigo’, o tal irá contigo, mas todo aquele de quem eu disser: ‘Este não irá contigo’, o tal não irá junto.”

[[v7-7-5]]

^<<v7-7-5,5>>^ De modo que fez o povo descer à água.
Jeová disse então a Gideão: “Todo aquele que beber da água lambendo com a língua assim como lambe o cão, a este porás à parte, também a todo aquele que se puser de joelhos para beber.”

[[v7-7-6]]

^<<v7-7-6,6>>^ E o número dos que bebiam lambendo com a sua mão à boca resultou ser trezentos homens. Quanto a todo o resto do povo, puseram-se de joelhos para beber água.

[[v7-7-7]]

^<<v7-7-7,7>>^ Jeová disse então a Gideão: “Por meio dos trezentos homens que beberam lambendo eu vos salvarei, e hei de entregar Midiã na tua mão. Quanto a todo o resto do povo, que cada um vá para o seu lugar.”

[[v7-7-8]]

^<<v7-7-8,8>>^ Tomaram, pois, as provisões do povo na mão,^&#42;1^ bem como suas buzinas, e ele mandou embora a todos os homens de Israel, cada um para o seu lar;^&#42;2^ e ele reteve trezentos homens. Quanto ao acampamento de Midiã, sucedia estar abaixo dele, na baixada.

[NOTE]
====
. Possivelmente: “Tomou, pois, os jarros grandes para água, do povo, das mãos deste.”
. Lit.: “tendas”.
====

[[v7-7-9]]

^<<v7-7-9,9>>^ E aconteceu, durante aquela noite, que Jeová passou a dizer-lhe: “Levanta-te, desce sobre o acampamento, pois o entreguei na tua mão.

[[v7-7-10]]

^<<v7-7-10,10>>^ Mas, se tiveres medo de descer, desce ao acampamento com Pura, teu ajudante.^&#42;1^

[NOTE]
====
. Ou “moço; rapaz; menino”.
====

[[v7-7-11]]

^<<v7-7-11,11>>^ E tens de escutar o que se fala, e depois as tuas mãos certamente ficarão fortes e descerás com certeza sobre o acampamento.” Em vista disso, ele e Pura, seu ajudante, foram descer até à beirada dos que estavam em formação de batalha, que se achavam no acampamento.

[[v7-7-12]]

^<<v7-7-12,12>>^ Ora, Midiã e Amaleque, e todos os orientais, achavam-se estirados na baixada, tão numerosos como os gafanhotos; e seus camelos eram inúmeros, tão numerosos como os grãos de areia que há à beira do mar.

[[v7-7-13]]

^<<v7-7-13,13>>^ Gideão veio, pois, e eis que havia um homem contando um sonho ao seu companheiro, e ele dizia: “Eis um sonho que tive. E eis que havia um bolo redondo de pão de cevada rodando para dentro do acampamento de Midiã. Chegou então a uma tenda e bateu nela de modo que ela caiu, e virou-a de baixo para cima, e a tenda caiu rente ao chão.”

[[v7-7-14]]

^<<v7-7-14,14>>^ Nisto lhe respondeu seu companheiro e disse: “Isto não é senão a espada de Gideão, filho de Joás, homem de Israel. O [verdadeiro] Deus lhe entregou na mão a Midiã e a todo o acampamento.”

[[v7-7-15]]

^<<v7-7-15,15>>^ E sucedeu que, assim que Gideão ouviu a narração do sonho e a sua explicação, começou a adorar.^&#42;1^ Depois retornou ao acampamento de Israel e disse: “Levantai-vos, pois Jeová vos entregou na mão o acampamento de Midiã.”

[NOTE]
====
. Ou “a curvar-se (prostrar-se)”.
====

[[v7-7-16]]

^<<v7-7-16,16>>^ Dividiu então os trezentos homens em três companhias e pôs buzinas na mão de todos, bem como jarros grandes, vazios, e tochas dentro dos jarros grandes.

[[v7-7-17]]

^<<v7-7-17,17>>^ E ele foi dizer-lhes: “Deveis aprender por observar-me,^&#42;1^ e assim deveis fazer. E quando eu tiver chegado à beirada do acampamento, então terá de dar-se que, conforme eu fizer, assim fareis vós.

[NOTE]
====
. Lit.: “De mim deveis ver.”
====

[[v7-7-18]]

^<<v7-7-18,18>>^ Quando eu tiver tocado a buzina, eu e todos os que estiverem comigo, vós também tereis de tocar as buzinas, também vós, ao redor de todo o acampamento, e tereis de dizer: ‘De Jeová e de Gideão!’”

[[v7-7-19]]

^<<v7-7-19,19>>^ Então Gideão com os cem homens que estavam com ele chegou à beirada do acampamento, no começo da vigília média da noite. Acabaram de colocar-se as sentinelas. E eles passaram a tocar as buzinas, e espatifaram-se os jarros grandes para água que tinham nas mãos.

[[v7-7-20]]

^<<v7-7-20,20>>^ Nisto as três companhias tocaram as buzinas e destroçaram os jarros grandes, e foram segurar de novo as tochas com a mão esquerda e tinham na mão direita as buzinas para tocá-las, e começaram a clamar: “A espada de Jeová e de Gideão!”

[[v7-7-21]]

^<<v7-7-21,21>>^ Ao mesmo tempo ficaram parados, cada um no seu lugar, ao redor do acampamento, e o acampamento inteiro pôs-se a correr, e irrompeu em gritos e pôs-se em fuga.

[[v7-7-22]]

^<<v7-7-22,22>>^ E os trezentos continuaram a tocar as buzinas e Jeová passou a tornar a espada de cada um contra o outro, em todo o acampamento; e o acampamento continuou na sua fuga até Bete-Sita, de lá para Zererá,^&#42;1^ até as cercanias de Abel-Meolá, junto a Tabate.

[NOTE]
====
. Possivelmente a mesma que “Zaretã” em 1Rs 4:12; “Zereda”, em 20 mss. hebr.
====

[[v7-7-23]]

^<<v7-7-23,23>>^ No ínterim foram convocados os homens de Israel, desde Naftali e Aser, e todo o Manassés, e eles foram no encalço de Midiã.

[[v7-7-24]]

^<<v7-7-24,24>>^ E Gideão enviou mensageiros a toda a região montanhosa de Efraim, dizendo: “Descei ao encontro de Midiã e capturai na frente deles as águas até Bete-Bara e o Jordão.” Por isso foram convocados todos os homens de Efraim, e eles foram capturar as águas até Bete-Bara e o Jordão.

[[v7-7-25]]

^<<v7-7-25,25>>^ Capturaram também os dois príncipes de Midiã, a saber, Orebe e Zeebe; e passaram a matar Orebe na rocha de Orebe e mataram Zeebe junto ao tanque de vinho de Zeebe. E continuaram a perseguir a Midiã, e trouxeram a cabeça de Orebe e a de Zeebe a Gideão, na região do Jordão.^&#42;1^

[NOTE]
====
. Ou “na terra fronteiriça do Jordão”; ou: “na terra do Jordão”.
====

'''

xref:007-juizes/007-juizes-006.adoc#v7-6-0[&#60; Capítulo Anterior] | <<v7-7-0,Topo>> | xref:007-juizes/007-juizes-008.adoc#v7-8-0[Próximo Capítulo &#62;]