include::./index.adoc[]

[[v7-20-0]]
=== Juízes, 20
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v7-20-1]]

^<<v7-20-1,1>>^ Por conseguinte, todos os filhos de Israel saíram e a assembléia congregou-se como um só homem a Jeová em Mispá, desde Dã para baixo até Berseba,^&#42;1^ junto com a terra de Gileade.

[NOTE]
====
. “Desde Dã para baixo até Berseba.” Hebr.: lemid-Dán we‛adh·Be’ér Shé·va‛; esta é a primeira ocorrência desta expressão.
====

[[v7-20-2]]

^<<v7-20-2,2>>^ Assim, os homens-chave^&#42;1^ de todo o povo e todas as tribos de Israel tomaram sua posição na congregação^&#42;2^ do povo do [verdadeiro] Deus, quatrocentos mil homens a pé, que puxavam da espada.

[NOTE]
====
. Lit.: “as torres de ângulo”, representativas de homens vitais ou importantes, de chefes.
. “Congregação do.” Gr.: ek·kle·sí·ai; lat.: ec·clé·si·am.
====

[[v7-20-3]]

^<<v7-20-3,3>>^ E os filhos de Benjamim souberam que os filhos de Israel haviam subido a Mispá.
Os filhos de Israel disseram então: “Falai. Como se deu esta coisa má?”

[[v7-20-4]]

^<<v7-20-4,4>>^ Nisso o homem, o levita, esposo da mulher assassinada, respondeu e disse: “Cheguei a Gibeá, que pertence a Benjamim, eu e minha concubina, para pernoitar.

[[v7-20-5]]

^<<v7-20-5,5>>^ E os proprietários de terras de Gibeá passaram a levantar-se contra mim e a cercar a casa contra mim de noite. Era a mim que tencionaram matar, mas foi a minha concubina que violentaram, e ela por fim morreu.

[[v7-20-6]]

^<<v7-20-6,6>>^ Por isso segurei a minha concubina e a cortei em pedaços, e enviei-a a todo campo da herança de Israel, porque se haviam empenhado em conduta desenfreada e em ignominiosa insensatez em Israel.

[[v7-20-7]]

^<<v7-20-7,7>>^ Eis todos vós, filhos de Israel, dai aqui vossa palavra e vosso conselho.”

[[v7-20-8]]

^<<v7-20-8,8>>^ Todo o povo levantou-se, pois, como um só homem, dizendo: “Nenhum de nós irá para a sua tenda, nem se retirará qualquer de nós para a sua casa.

[[v7-20-9]]

^<<v7-20-9,9>>^ E agora, esta é a coisa que faremos a Gibeá. Subamos^&#42;1^ por sortes contra ela.

[NOTE]
====
. “Subamos”, LXX; M omite isso.
====

[[v7-20-10]]

^<<v7-20-10,10>>^ E temos de tomar dez homens dentre cem de todas as tribos de Israel, e cem dentre mil, e mil dentre dez mil, a fim de obterem provisões para o povo, para que tomem ação, indo contra Gibeá^&#42;1^ de Benjamim, em vista de toda a ignominiosa insensatez que fizeram^&#42;2^ em Israel.”

[NOTE]
====
. “Gibeá.” Lit.: “Geba”. Ambos os nomes significam “Colina”.
. “Fizeram”, LXXASy; M: “fez”.
====

[[v7-20-11]]

^<<v7-20-11,11>>^ Assim se ajuntaram todos os homens de Israel contra a cidade, como um só homem, como aliados.

[[v7-20-12]]

^<<v7-20-12,12>>^ Concordemente, as tribos de Israel enviaram homens a todos os membros da tribo^&#42;1^ de Benjamim, dizendo: “Que coisa má é esta que se deu entre vós?

[NOTE]
====
. Lit.: “tribos”, M; LXXVg: “tribo”; Sy: “casa”.
====

[[v7-20-13]]

^<<v7-20-13,13>>^ E agora, entregai os homens, os homens imprestáveis que há em Gibeá, para os entregarmos à morte, e eliminemos de Israel o mal.” E os filhos de Benjamim^&#42;1^ não quiseram escutar a voz de seus irmãos, os filhos de Israel.

[NOTE]
====
. “Os filhos de Benjamim”, TLXXSy e muitos mss. hebr. rezam assim. M tem sinais vocálicos de qere para “filhos de”, antes de Benjamim, mas sem as consoantes hebr.; trata-se de qere, não de kethib (lido, mas não escrito).
====

[[v7-20-14]]

^<<v7-20-14,14>>^ Então os filhos de Benjamim foram ajuntar-se das cidades a Gibeá, para saírem a batalhar contra os filhos de Israel.

[[v7-20-15]]

^<<v7-20-15,15>>^ De modo que naquele dia foram arrolados os filhos de Benjamim dentre as cidades, vinte e seis mil homens que puxavam da espada, além dos habitantes de Gibeá, dos quais foram arrolados setecentos homens seletos.

[[v7-20-16]]

^<<v7-20-16,16>>^ Entre todo este povo havia setecentos homens seletos que eram canhotos.^&#42;1^ Cada um destes podia atirar com a funda pedras num cabelo, e não errava.

[NOTE]
====
. “Ambidestros”, LXX. Veja 3:15 n.: “canhoto”.
====

[[v7-20-17]]

^<<v7-20-17,17>>^ E os homens de Israel foram recrutados separados de Benjamim, quatrocentos mil homens que puxavam da espada. Cada um destes era homem de guerra.

[[v7-20-18]]

^<<v7-20-18,18>>^ E passaram a levantar-se e a subir a Betel, e a indagar de Deus. Então disseram os filhos de Israel: “Quem de nós deve subir na dianteira à batalha contra os filhos de Benjamim?” A isso Jeová disse: “Judá na dianteira.”

[[v7-20-19]]

^<<v7-20-19,19>>^ Depois, os filhos de Israel se levantaram de manhã e se acamparam contra Gibeá.

[[v7-20-20]]

^<<v7-20-20,20>>^ Os homens de Israel saíram então à batalha contra Benjamim; e os homens de Israel passaram a pôr-se em formação de batalha contra eles em Gibeá.

[[v7-20-21]]

^<<v7-20-21,21>>^ Saíram, pois, os filhos de Benjamim de Gibeá e causaram a ruína a vinte e dois mil homens em Israel, derrubando-os por terra naquele dia.

[[v7-20-22]]

^<<v7-20-22,22>>^ No entanto, o povo, os homens de Israel, mostraram-se corajosos e foram novamente pôr-se em formação de batalha no lugar em que se puseram em formação de batalha no primeiro dia.

[[v7-20-23]]

^<<v7-20-23,23>>^ Os filhos de Israel subiram então e choraram perante Jeová até à noitinha e indagaram de Jeová, dizendo: “Devo novamente chegar-me à batalha contra os filhos de Benjamim, meu irmão?” A isso Jeová disse: “Subi contra ele.”

[[v7-20-24]]

^<<v7-20-24,24>>^ Portanto, os filhos de Israel chegaram-se aos filhos de Benjamim no segundo dia.

[[v7-20-25]]

^<<v7-20-25,25>>^ Benjamim, por sua vez, saiu de Gibeá ao encontro deles, no segundo dia, e causou a ruína a mais dezoito mil homens dentre os filhos de Israel, derrubando-os por terra, todos estes sendo dos que puxavam da espada.

[[v7-20-26]]

^<<v7-20-26,26>>^ Em vista disso, todos os filhos de Israel, sim, todo o povo, subiram e vieram a Betel,^&#42;1^ e choraram e se sentaram ali perante Jeová, e jejuaram naquele dia até à noitinha, e fizeram ofertas queimadas e ofertas de participação em comum perante Jeová.

[NOTE]
====
. “Vieram à casa de Deus”, Vg.
====

[[v7-20-27]]

^<<v7-20-27,27>>^ Após isso, os filhos de Israel indagaram de Jeová, pois era ali que se achava a arca do pacto do [verdadeiro] Deus naqueles dias.

[[v7-20-28]]

^<<v7-20-28,28>>^ Ora, Finéias, filho de Eleazar, filho de Arão, estava de pé diante dela naqueles dias, dizendo: “Devo ainda sair à batalha contra os filhos de Benjamim, meu irmão, ou devo desistir?” A isso Jeová disse: “Subi, porque amanhã o entregarei na tua mão.”

[[v7-20-29]]

^<<v7-20-29,29>>^ Então Israel pôs homens de emboscada contra Gibeá, em todo o redor.

[[v7-20-30]]

^<<v7-20-30,30>>^ E os filhos de Israel passaram a subir contra os filhos de Benjamim no terceiro dia e a pôr-se em formação de batalha contra Gibeá, assim como das outras vezes.

[[v7-20-31]]

^<<v7-20-31,31>>^ Quando os filhos de Benjamim saíram ao encontro do povo, foram afastados da cidade. Então, assim como das outras vezes, principiaram a golpear alguns do povo, ferindo-os mortalmente, nas estradas principais, uma das quais sobe a Betel e a outra a Gibeá, no campo, cerca de trinta homens em Israel.

[[v7-20-32]]

^<<v7-20-32,32>>^ De modo que os filhos de Benjamim começaram a dizer: “Estão sendo derrotados diante de nós como no princípio.” Quanto aos filhos de Israel, disseram: “Fujamos, e havemos de afastá-los da cidade para as estradas principais.”

[[v7-20-33]]

^<<v7-20-33,33>>^ E todos os homens de Israel se levantaram dos seus lugares e foram pôr-se em formação em Baal-Tamar, enquanto os de Israel na emboscada lançaram um ataque dos seus lugares na vizinhança de Gibeá.

[[v7-20-34]]

^<<v7-20-34,34>>^ Assim, dez mil homens seletos de todo o Israel chegaram diante de Gibeá e a luta foi intensa; e os benjamitas^&#42;1^ não sabiam que os aguardava uma calamidade.

[NOTE]
====
. Lit.: “e eles”.
====

[[v7-20-35]]

^<<v7-20-35,35>>^ E Jeová passou a derrotar Benjamim diante de Israel, de modo que, naquele dia, os filhos de Israel causaram a ruína a vinte e cinco mil e cem homens em Benjamim, todos estes sendo dos que puxavam da espada.

[[v7-20-36]]

^<<v7-20-36,36>>^ No entanto, os filhos de Benjamim imaginavam que os homens de Israel enfrentavam a derrota, quando cediam diante de Benjamim por confiarem na emboscada que tinham posto contra Gibeá.

[[v7-20-37]]

^<<v7-20-37,37>>^ Quanto aos da emboscada, agiram rapidamente e investiram contra Gibeá. Os da emboscada se espalharam então e golpearam toda a cidade com o fio da espada.

[[v7-20-38]]

^<<v7-20-38,38>>^ Ora, os homens de Israel tinham combinado com [os da] emboscada^&#42;1^ para fazerem subir um sinal de fumaça^&#42;2^ da cidade.

[NOTE]
====
. “Os da emboscada.” Hebr.: ha·’o·rév. A palavra seguinte, hé·rev, deve ser omitida por se tratar duma evidente ditografia.
. Lit.: “uma elevação de fumaça”.
====

[[v7-20-39]]

^<<v7-20-39,39>>^ Quando os filhos de Israel se voltaram na batalha, Benjamim principiou a golpear cerca de trinta homens dentre os filhos de Israel, ferindo-os mortalmente, pois disseram: “Sem dúvida, não estão senão sofrendo derrota diante de nós, como na primeira batalha.”

[[v7-20-40]]

^<<v7-20-40,40>>^ E o sinal principiou a subir da cidade numa coluna de fumaça. Portanto, virando Benjamim a face para trás, eis que a cidade inteira subia [em fumo] para o céu.

[[v7-20-41]]

^<<v7-20-41,41>>^ E os filhos de Israel deram meia-volta e os homens de Benjamim ficaram perturbados, pois viam que os atingira a calamidade.

[[v7-20-42]]

^<<v7-20-42,42>>^ Por isso se viraram diante dos homens de Israel para o ermo e a batalha seguia-os de perto, enquanto os homens saindo das cidades lhes causavam a ruína, derrubando-os no seu meio.

[[v7-20-43]]

^<<v7-20-43,43>>^ Cercaram a Benjamim. Perseguiram-no sem lhe deixar lugar de descanso. Pisaram-no logo defronte de Gibeá em direção ao nascente do sol.

[[v7-20-44]]

^<<v7-20-44,44>>^ Finalmente, caíram dezoito mil homens de Benjamim, todos estes sendo homens valentes.

[[v7-20-45]]

^<<v7-20-45,45>>^ Viraram-se, pois, e foram fugir para o ermo, para o rochedo de Rimom. E fizeram uma rebusca de cinco mil homens deles nas estradas principais, e seguiam-nos de perto até Gidom e assim mataram a golpes mais dois mil homens deles.

[[v7-20-46]]

^<<v7-20-46,46>>^ E todos os de Benjamim que caíram naquele dia somaram por fim vinte e cinco mil homens que puxavam da espada, todos estes sendo homens valentes.

[[v7-20-47]]

^<<v7-20-47,47>>^ Seiscentos homens, porém, viraram-se e puseram-se em fuga para o ermo, para o rochedo de Rimom, e ficaram morando no rochedo de Rimom por quatro meses.

[[v7-20-48]]

^<<v7-20-48,48>>^ E os homens de Israel se voltaram contra os filhos de Benjamim e foram golpear os da cidade com o fio da espada, [desde] os homens até o animal doméstico, todos os que acharam. Também todas as cidades que acharam entregaram ao fogo.

'''

xref:007-juizes/007-juizes-019.adoc#v7-19-0[&#60; Capítulo Anterior] | <<v7-20-0,Topo>> | xref:007-juizes/007-juizes-021.adoc#v7-21-0[Próximo Capítulo &#62;]