include::./index.adoc[]

[[v7-6-0]]
=== Juízes, 6
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v7-6-1]]

^<<v7-6-1,1>>^ Os filhos de Israel começaram então a fazer o que era mau aos olhos de Jeová. Portanto, Jeová os entregou na mão de Midiã, por sete anos.

[[v7-6-2]]

^<<v7-6-2,2>>^ E a mão de Midiã veio a prevalecer sobre Israel. Por causa de Midiã, os filhos de Israel fizeram para si os depósitos subterrâneos que estavam nos montes, e as cavernas e os lugares de difícil acesso.

[[v7-6-3]]

^<<v7-6-3,3>>^ E sucedia que, semeando Israel, subiam Midiã, e Amaleque, e os orientais,^&#42;1^ sim, subiam contra eles.

[NOTE]
====
. Lit.: “e os filhos do Oriente”. Vg: “e outros das nações orientais”.
====

[[v7-6-4]]

^<<v7-6-4,4>>^ E acampavam-se contra eles e arruinavam a produção da terra, por toda a extensão até Gaza, e não deixavam restar nem sustento, nem ovídeo, nem touro, nem jumento em Israel.

[[v7-6-5]]

^<<v7-6-5,5>>^ Porque subiam eles e seu gado, com as suas tendas. Vinham tão numerosos como os gafanhotos, e tanto eles como os seus camelos eram sem número; e entravam no país para arruiná-lo.

[[v7-6-6]]

^<<v7-6-6,6>>^ E Israel ficou muito empobrecido por causa de Midiã; e os filhos de Israel começaram a clamar a Jeová por socorro.

[[v7-6-7]]

^<<v7-6-7,7>>^ E sucedeu que, por terem os filhos de Israel clamado a Jeová por socorro, por causa de Midiã,

[[v7-6-8]]

^<<v7-6-8,8>>^ Jeová passou a enviar um homem, um profeta, aos filhos de Israel e a dizer-lhes: “Assim disse Jeová, o Deus de Israel: ‘Fui eu que vos fiz subir do Egito e assim vos fiz sair da casa dos escravos.

[[v7-6-9]]

^<<v7-6-9,9>>^ De modo que vos livrei da mão do Egito e da mão de todos os vossos opressores, e eu os expulsei de diante de vós e vos dei a sua terra.

[[v7-6-10]]

^<<v7-6-10,10>>^ Ademais, eu vos disse: “Eu sou Jeová, vosso Deus. Não deveis temer os deuses dos amorreus em cuja terra morais.” E vós não escutastes a minha voz.’”

[[v7-6-11]]

^<<v7-6-11,11>>^ Mais tarde veio o anjo de Jeová e se sentou debaixo da árvore grande que havia em Ofra, que pertencia a Joás, o abiezrita, enquanto Gideão, seu filho, estava malhando trigo no lagar de vinho, para pô-lo depressa fora da vista de Midiã.

[[v7-6-12]]

^<<v7-6-12,12>>^ Apareceu-lhe então o anjo de Jeová e disse-lhe: “Jeová está contigo, ó valente, poderoso.”

[[v7-6-13]]

^<<v7-6-13,13>>^ A isso Gideão lhe disse: “Perdão, meu senhor, mas se Jeová está conosco, então por que nos sobreveio tudo isso e onde estão todos os seus atos maravilhosos que nossos pais nos relataram, dizendo: ‘Não foi do Egito que Jeová nos fez subir?’ E agora Jeová nos abandonou, e ele nos entrega na palma da mão de Midiã.”

[[v7-6-14]]

^<<v7-6-14,14>>^ Em vista disso, Jeová^&#42;1^ se virou para ele e disse: “Vai neste teu poder e certamente salvarás a Israel da palma da mão de Midiã. Não te envio eu?”

[NOTE]
====
. “Jeová”, M; gr.: ho ág·ge·los Ky·rí·ou, “o anjo de Jeová”.
====

[[v7-6-15]]

^<<v7-6-15,15>>^ Ele lhe disse, por sua vez: “Perdão, Jeová.^&#42;1^ Com que salvarei a Israel? Eis que o meu milhar^&#42;2^ é o mínimo em Manassés e eu sou o menor na casa de meu pai.”

[NOTE]
====
. Uma das 134 mudanças de YHWH para ’Adho·naí feitas pelos escribas. Veja Ap. 1B.
. “Milhar.” Uma subdivisão nas tribos de Israel.
====

[[v7-6-16]]

^<<v7-6-16,16>>^ Jeová, porém, lhe disse: “Porque eu mostrarei estar contigo, e certamente golpearás a Midiã como a um só homem.”

[[v7-6-17]]

^<<v7-6-17,17>>^ A isso lhe disse ele: “Se eu, pois, tenho achado favor aos teus olhos, então tens de fazer um sinal para mim, de que és tu quem falas comigo.

[[v7-6-18]]

^<<v7-6-18,18>>^ Por favor, não te afastes daqui até que eu venha ter contigo e te tenha trazido meu presente e o tenha colocado diante de ti.” Ele disse, pois: “Eu, da minha parte, ficarei sentado aqui até que voltes.”

[[v7-6-19]]

^<<v7-6-19,19>>^ E Gideão entrou e passou a aprontar um cabritinho, e dum efa^&#42;1^ de farinha, pães não fermentados. A carne ele pôs no cesto e o caldo na caçarola, levando-os depois a ele lá fora debaixo da árvore grande e servindo-o.

[NOTE]
====
. Cerca de 22 l.
====

[[v7-6-20]]

^<<v7-6-20,20>>^ O anjo do [verdadeiro] Deus^&#42;1^ disse-lhe então: “Toma a carne e os pães não fermentados, e coloca-os lá sobre a grande penha,^&#42;2^ e derrama o caldo.” E ele foi fazer isso.

[NOTE]
====
. “Do [verdadeiro] Deus.” Hebr.: ha·’Elo·hím; LXXAVg: “Jeová”; LXXB: “Deus”. Veja Ap. 1F.
. Lit.: “o rochedo ali”.
====

[[v7-6-21]]

^<<v7-6-21,21>>^ O anjo de Jeová estendeu então a ponta do seu bastão que tinha na mão e tocou na carne e nos pães não fermentados, e começou a subir fogo da rocha e a consumir a carne e os pães não fermentados. Quanto ao anjo de Jeová, desapareceu da sua vista.

[[v7-6-22]]

^<<v7-6-22,22>>^ Por conseguinte, Gideão percebeu que era o anjo de Jeová.
Gideão disse imediatamente: “Ai! Soberano Senhor Jeová, pois vi o anjo de Jeová face a face!”

[[v7-6-23]]

^<<v7-6-23,23>>^ Mas Jeová disse-lhe: “Paz seja contigo. Não temas. Não morrerás.”

[[v7-6-24]]

^<<v7-6-24,24>>^ Portanto, Gideão construiu ali um altar a Jeová, e até o dia de hoje continua a ser chamado^&#42;1^ de Jeová-Salom.^&#42;2^ Ainda está em Ofra dos abiezritas.

[NOTE]
====
. Ou “e passou a chamá-lo”.
. Significando “Jeová É Paz”.
====

[[v7-6-25]]

^<<v7-6-25,25>>^ E sucedeu, durante aquela noite, que Jeová foi dizer-lhe: “Toma o novilho, o touro que pertence a teu pai, isto é, o segundo novilho de sete anos, e tens de derrubar o altar de Baal que é de teu pai, e deves cortar o poste sagrado^&#42;1^ que se acha junto dele.

[NOTE]
====
. Ou “a Axerá”.
====

[[v7-6-26]]

^<<v7-6-26,26>>^ E tens de construir um altar a Jeová, teu Deus, no topo deste baluarte, com a fileira de pedras, e tens de tomar o segundo novilho e oferecê-lo como oferta queimada sobre os pedaços de madeira do poste sagrado que cortarás.”

[[v7-6-27]]

^<<v7-6-27,27>>^ Por conseguinte, Gideão tomou dez homens dos seus servos e pôs-se a fazer assim como Jeová lhe falara; mas, sucedeu que, temendo ele demais os da casa de seu pai e os homens da cidade para fazê-lo de dia, foi fazê-lo de noite.

[[v7-6-28]]

^<<v7-6-28,28>>^ De manhã cedo, quando os homens da cidade se levantaram como de costume, ora, eis que se tinha demolido o altar de Baal e se tinha cortado o poste sagrado que havia ao lado dele, e se tinha oferecido o segundo novilho no altar que se havia construído.

[[v7-6-29]]

^<<v7-6-29,29>>^ E começaram a dizer um ao outro: “Quem fez esta coisa?” E foram consultar e procurar. Por fim disseram: “Foi Gideão, filho de Joás, quem fez esta coisa.”

[[v7-6-30]]

^<<v7-6-30,30>>^ Portanto, os homens da cidade disseram a Joás: “Traze teu filho para fora, para que morra, porque demoliu o altar de Baal, e porque cortou o poste sagrado que havia ao lado dele.”

[[v7-6-31]]

^<<v7-6-31,31>>^ Então Joás disse a todos os que estavam de pé contra ele: “Sereis vós os que pleiteareis em defesa de Baal, para ver se vós mesmos o podeis salvar? Quem pleitear em defesa dele devia ser morto ainda esta manhã. Se ele é Deus, que pleiteie em defesa de si mesmo, visto que alguém demoliu o seu altar.”

[[v7-6-32]]

^<<v7-6-32,32>>^ E naquele dia começou a chamá-lo de Jerubaal,^&#42;1^ dizendo: “Pleiteie Baal em sua própria defesa, visto que alguém demoliu o seu altar.”

[NOTE]
====
. Significando “Pleiteie Baal em Defesa Contra Ele”.
====

[[v7-6-33]]

^<<v7-6-33,33>>^ E ajuntaram-se à uma todo o Midiã, e Amaleque, e os orientais, e passaram a atravessar e a acampar-se na baixada de Jezreel.

[[v7-6-34]]

^<<v7-6-34,34>>^ E o espírito de Jeová envolveu^&#42;1^ Gideão de modo que ele foi tocar a buzina,^&#42;2^ e os abiezritas^&#42;3^ foram convocados a ele.

[NOTE]
====
. Ou “revestiu”.
. Ou “shofar”.
. Lit.: “e Abiezer”.
====

[[v7-6-35]]

^<<v7-6-35,35>>^ E enviou mensageiros através de todo o Manassés, e também foram convocados a ele. Enviou também mensageiros através de Aser, e Zebulão, e Naftali, e estes subiram ao seu^&#42;1^ encontro.

[NOTE]
====
. “Seu (dele)”, LXXAVg; MLXXBSy: “seu (deles)”.
====

[[v7-6-36]]

^<<v7-6-36,36>>^ Gideão disse então ao [verdadeiro] Deus: “Se salvares a Israel por meu intermédio, assim como prometeste,

[[v7-6-37]]

^<<v7-6-37,37>>^ eis que mantenho um velo de lã exposto na eira. Se vier a haver orvalho somente no velo, mas todo o chão ali estiver seco, então terei de saber que salvarás a Israel por meu intermédio, assim como prometeste.”

[[v7-6-38]]

^<<v7-6-38,38>>^ E assim se deu. Quando se levantou cedo no dia seguinte e torceu o velo, espremeu do velo bastante orvalho para encher de água uma grande taça de banquete.

[[v7-6-39]]

^<<v7-6-39,39>>^ No entanto, Gideão disse ao [verdadeiro] Deus: “Não se acenda a tua ira contra mim, mas fale eu somente mais uma vez. Por favor, deixa-me fazer apenas mais uma prova com o velo. Por favor, fique apenas o velo seco e venha a haver orvalho em todo o chão.”

[[v7-6-40]]

^<<v7-6-40,40>>^ De modo que Deus fez assim naquela noite; e só o velo ficou seco e em todo o chão veio a haver orvalho.

'''

xref:007-juizes/007-juizes-005.adoc#v7-5-0[&#60; Capítulo Anterior] | <<v7-6-0,Topo>> | xref:007-juizes/007-juizes-007.adoc#v7-7-0[Próximo Capítulo &#62;]