include::./index.adoc[]

[[v29-2-0]]
=== Joel, 2
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v29-2-1]]

^<<v29-2-1,1>>^ “Tocai a buzina^&#42;1^ em Sião e dai um grito de guerra no meu santo monte. Fiquem agitados todos os habitantes da terra;^&#42;2^ pois está chegando o dia de Jeová, pois está perto!

[NOTE]
====
. Ou “shofar”. Hebr.: shoh·fár.
. “Da terra.” Hebr.: ha·’á·rets.
====

[[v29-2-2]]

^<<v29-2-2,2>>^ É um dia de escuridão e de trevas, dia de nuvens e de densas trevas, como a luz da alva difundida sobre os montes.
“Há um povo numeroso e poderoso; semelhante a ele não se fez existir nenhum, desde o passado indefinido, e depois dele não haverá mais nenhum até os anos de geração após geração.

[[v29-2-3]]

^<<v29-2-3,3>>^ Adiante dele um fogo devora e atrás dele uma chama consome. Adiante dele a terra está como o jardim do Éden;^&#42;1^ mas atrás dele é um ermo desolado, e também se mostrou que dela nada escapa.

[NOTE]
====
. “Como o jardim do Éden.” Hebr.: keghan-‛É·dhen; gr.: hos pa·rá·dei·sos try·fés, “como um paraíso de deleite”; sir.: ’aikh par·dai·sa’ da‛·den; lat.: quá·si hór·tus vo·lu·ptá·tis, “como um jardim de prazer”.
====

[[v29-2-4]]

^<<v29-2-4,4>>^ “Sua aparência é como a aparência de cavalos e correm como corcéis.

[[v29-2-5]]

^<<v29-2-5,5>>^ Saltitam como que com o ruído de carros nos cumes dos montes, como que com o ruído dum fogo chamejante que devora o restolho. É como um povo forte, posto em ordem de batalha.

[[v29-2-6]]

^<<v29-2-6,6>>^ Por causa dele, povos terão dores agudas. Quanto a todas as faces, certamente ficarão coradas [de excitação].

[[v29-2-7]]

^<<v29-2-7,7>>^ “Correm como homens poderosos.^&#42;1^ Sobem a muralha como homens de guerra. E vão, cada um, nos seus próprios caminhos e não trocam de veredas.

[NOTE]
====
. “Como homens poderosos.” Hebr.: keghib·boh·rím.
====

[[v29-2-8]]

^<<v29-2-8,8>>^ E não empurram um ao outro. Prosseguem andando assim como o varão vigoroso^&#42;1^ no seu rumo; e se alguns caírem mesmo entre os projéteis, os [outros] não interrompem o avanço.

[NOTE]
====
. “O varão vigoroso.” Hebr.: gé·ver.
====

[[v29-2-9]]

^<<v29-2-9,9>>^ “Investem para dentro da cidade. Correm sobre a muralha. Sobem às casas. Entram pelas janelas como o ladrão.

[[v29-2-10]]

^<<v29-2-10,10>>^ Diante dele [a] terra ficou agitada, [os] céus tremeram. Mesmo o sol e a lua ficaram escuros e as próprias estrelas recolheram a sua claridade.

[[v29-2-11]]

^<<v29-2-11,11>>^ E o próprio Jeová certamente fará [ouvir] a sua voz perante a sua força militar, pois o seu acampamento é muito numeroso. Pois, aquele que cumpre a sua palavra é forte; porque o dia de Jeová é grande e muito atemorizante, e quem poderá resistir nele?”

[[v29-2-12]]

^<<v29-2-12,12>>^ “E também agora”, é a pronunciação de Jeová, “retornai a mim de todo o vosso coração, e com jejum, e com choro, e com lamento.

[[v29-2-13]]

^<<v29-2-13,13>>^ E rasgai os vossos corações e não as vossas vestes; e retornai a Jeová, vosso Deus, porque ele é clemente e misericordioso, vagaroso em irar-se e abundante em benevolência,^&#42;1^ e certamente deplorará a calamidade.

[NOTE]
====
. Ou “amor leal”. Hebr.: hhé·sedh.
====

[[v29-2-14]]

^<<v29-2-14,14>>^ Quem sabe se não voltará e realmente [o] deplorará, e [se não] deixará depois uma bênção, uma oferta de cereais e uma oferta de bebida para Jeová, vosso Deus?

[[v29-2-15]]

^<<v29-2-15,15>>^ “Tocai a buzina em Sião. Santificai um tempo de jejum. Convocai uma assembléia solene.

[[v29-2-16]]

^<<v29-2-16,16>>^ Ajuntai [o] povo. Santificai^&#42;1^ uma congregação. Reuni [os] homens idosos. Ajuntai as crianças e os que mamam aos peitos. Saia [o] noivo do seu quarto interior e [a] noiva da sua câmara nupcial.

[NOTE]
====
. Ou: “Tende por sagrada; tratai como santa.” Hebr.: qad·deshú; gr.: ha·gi·á·sa·te; lat.: sanc·ti·fi·cá·te.
====

[[v29-2-17]]

^<<v29-2-17,17>>^ “Chorem os sacerdotes, os ministros de Jeová, entre o pórtico e o altar, e digam: ‘Tem pena do teu povo, ó Jeová, e não constituas a tua herança em vitupério, para as nações dominarem sobre eles. Por que se havia de dizer entre os povos: “Onde está o seu Deus?”’

[[v29-2-18]]

^<<v29-2-18,18>>^ E Jeová será zeloso para com a sua terra e se compadecerá do seu povo.

[[v29-2-19]]

^<<v29-2-19,19>>^ E Jeová responderá e dirá ao seu povo: ‘Eis que vos envio o cereal, e o vinho novo, e o azeite, e vós certamente vos fartareis com isso; e não mais farei de vós um vitupério entre as nações.

[[v29-2-20]]

^<<v29-2-20,20>>^ E ao nortenho^&#42;1^ afastarei para longe de vós e realmente o dispersarei para uma terra árida e um baldio desolado, com a sua face [virada] para o mar oriental e o seu lado posterior para o mar ocidental.^&#42;2^ E certamente subirá o mau cheiro dele e continuará a subir o fedor dele; porque Ele fará realmente uma grande coisa naquilo que fará.’

[NOTE]
====
. Possivelmente “chilreador”, mediante uma correção.
. Lit.: “de trás”, isto é, atrás das costas, quando se encara o leste.
====

[[v29-2-21]]

^<<v29-2-21,21>>^ “Não tenhas medo, ó solo. Jubila e alegra-te; porque Jeová fará realmente uma grande coisa naquilo que fará.

[[v29-2-22]]

^<<v29-2-22,22>>^ Não tenhais medo, vós animais da campina, porque as pastagens do ermo hão de ficar verdes. Porque a árvore dará realmente seu fruto. A figueira e a videira terão de dar a sua energia vital.

[[v29-2-23]]

^<<v29-2-23,23>>^ E jubilai e alegrai-vos em Jeová, vosso Deus,^&#42;1^ vós filhos de Sião; porque forçosamente ele vos dará a chuva outonal^&#42;2^ na medida certa e fará descer sobre vós o aguaceiro, a chuva outonal e a chuva primaveril, como no princípio.

[NOTE]
====
. “Vosso Deus.” Hebr.: ’Elo·heh·khém.
. “Chuva outonal”, mediante uma correção; M: “instrutor”.
====

[[v29-2-24]]

^<<v29-2-24,24>>^ E as eiras terão de estar cheias de cereais [limpos] e os tanques de lagar terão de transbordar de vinho novo e de azeite.

[[v29-2-25]]

^<<v29-2-25,25>>^ E eu vou compensar-vos pelos anos em que o gafanhoto, a larva de gafanhoto, e a barata e a lagarta comeram, minha grande força militar que enviei entre vós.

[[v29-2-26]]

^<<v29-2-26,26>>^ E certamente comereis, comendo e fartando-vos, e forçosamente louvareis o nome de Jeová, vosso Deus, que agiu convosco tão maravilhosamente; e meu povo não se envergonhará por tempo indefinido.

[[v29-2-27]]

^<<v29-2-27,27>>^ E tereis de saber que estou no meio de Israel e que eu sou Jeová, vosso Deus, e que não há outro. E meu povo não se envergonhará por tempo indefinido.^&#42;1^

[NOTE]
====
. MLXX terminam aqui o cap. 2; TLXXBagsterSyVg continuam o cap. 2 até o v. 32 (3:5 do M).
====

[[v29-2-28]]

^<<v29-2-28,28>>^ “E depois terá de acontecer que derramarei meu espírito^&#42;1^ sobre toda sorte de carne, e vossos filhos e vossas filhas certamente profetizarão. Quanto aos vossos homens idosos, terão sonhos. Quanto aos vossos jovens, terão visões.

[NOTE]
====
. “Meu espírito.” Hebr.: ru·hhí; gr.: pneú·ma·tos; lat.: spí·ri·tum.
====

[[v29-2-29]]

^<<v29-2-29,29>>^ E até mesmo sobre os servos e sobre as servas derramarei naqueles dias meu espírito.

[[v29-2-30]]

^<<v29-2-30,30>>^ “E vou dar portentos nos céus e na terra: sangue e fogo, e colunas de fumaça.

[[v29-2-31]]

^<<v29-2-31,31>>^ O próprio sol será transformado em escuridão e a lua em sangue, antes de chegar o grande e atemorizante dia de Jeová.

[[v29-2-32]]

^<<v29-2-32,32>>^ E terá de acontecer que todo aquele que invocar o nome de Jeová salvar-se-á; pois no monte Sião e em Jerusalém virão a estar os que escaparam, assim como Jeová disse, e entre os sobreviventes^&#42;1^ que Jeová está chamando.”^&#42;2^

[NOTE]
====
. “Entre os sobreviventes”, MVg; gr.: eu·ag·ge·li·zó·me·noi, “os que proclamam boas novas; os que evangelizam”.
. MLXX terminam aqui o cap. 3; TLXXBagsterSyVg terminam aqui o cap. 2.
====

'''

xref:029-joel/029-joel-001.adoc#v29-1-0[&#60; Capítulo Anterior] | <<v29-2-0,Topo>> | xref:029-joel/029-joel-003.adoc#v29-3-0[Próximo Capítulo &#62;]