include::./index.adoc[]

[[v29-3-0]]
=== Joel, 3
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v29-3-1]]

^<<v29-3-1,1>>^ “Pois, eis que naqueles dias e naquele tempo, quando eu trouxer de volta os cativos de Judá e de Jerusalém,

[[v29-3-2]]

^<<v29-3-2,2>>^ vou também reunir todas as nações e fazê-las descer à baixada de Jeosafá; e ali vou pôr-me em julgamento com elas por causa do meu povo e da minha herança de Israel, que dispersaram entre as nações; e repartiram a minha própria terra.

[[v29-3-3]]

^<<v29-3-3,3>>^ E continuaram a lançar sortes sobre o meu povo; e foram dar o menino por uma prostituta,^&#42;1^ e venderam a menina por vinho, para beberem.

[NOTE]
====
. Lit.: “pela prostituta”. Hebr.: baz·zoh·náh; lat.: in pro·stí·bu·lum; gr.: pór·nais, “por prostitutas”.
====

[[v29-3-4]]

^<<v29-3-4,4>>^ “E também, que tendes vós comigo,^&#42;1^ ó Tiro e Sídon, e todas as regiões da Filístia? É este o tratamento que me dais em recompensa? E se vós me dais tal tratamento, pagarei de volta veloz e rapidamente vosso tratamento às vossas cabeças.

[NOTE]
====
. Lit.: “que sois vós para mim?” Esta é uma expressão idiomática hebr.; é uma pergunta de repulsa, indicando objeção ao “tratamento”. Veja Ap. 7B.
====

[[v29-3-5]]

^<<v29-3-5,5>>^ Porque vós tomastes a minha própria prata e o meu próprio ouro e introduzistes nos vossos templos as minhas próprias boas coisas desejáveis;

[[v29-3-6]]

^<<v29-3-6,6>>^ e vendestes os filhos de Judá e os filhos de Jerusalém aos filhos dos gregos,^&#42;1^ a fim de removê-los para longe do seu próprio território;

[NOTE]
====
. “Dos gregos”, LXXVg; hebr.: hai·Yewa·ním, “dos iônios (ou: jônios)”.
====

[[v29-3-7]]

^<<v29-3-7,7>>^ eis que os desperto [para virem] do lugar ao qual os vendestes e vou pagar de volta vosso tratamento às vossas próprias cabeças.

[[v29-3-8]]

^<<v29-3-8,8>>^ E vou vender vossos filhos e vossas filhas à mão dos filhos de Judá, e terão de vendê-los aos homens de Sabá, a uma nação longínqua; porque o próprio Jeová [o] falou.

[[v29-3-9]]

^<<v29-3-9,9>>^ “Proclamai isto entre as nações: ‘Santificai a guerra! Despertai os poderosos!^&#42;1^ Aproximem-se eles! Subam todos os homens^&#42;2^ de guerra!

[NOTE]
====
. Veja 2:7 n.
. “Homens de.” Hebr.: ’an·shéh, pl. de ’ish.
====

[[v29-3-10]]

^<<v29-3-10,10>>^ Forjai espadas das vossas relhas de arado e lanças das vossas podadeiras. Quanto ao fraco, diga: “Sou homem poderoso.”

[[v29-3-11]]

^<<v29-3-11,11>>^ Acudi e vinde, todas as nações ao redor, e reuni-vos.’”
Àquele lugar faze baixar os teus poderosos, ó Jeová.

[[v29-3-12]]

^<<v29-3-12,12>>^ “Despertem as nações e subam à baixada de Jeosafá; pois ali me assentarei para julgar todas as nações ao redor.

[[v29-3-13]]

^<<v29-3-13,13>>^ “Metei a foicinha, porque a colheita ficou madura. Vinde, descei, porque [o] lagar de vinho ficou cheio. Os tanques de lagar estão realmente transbordando; porque se tornou abundante a sua maldade.

[[v29-3-14]]

^<<v29-3-14,14>>^ Massas de gente, massas de gente estão na baixada da decisão, porque está próximo o dia de Jeová na baixada da decisão.

[[v29-3-15]]

^<<v29-3-15,15>>^ Mesmo o sol e a lua hão de ficar escuros e as próprias estrelas recolherão realmente a sua claridade.

[[v29-3-16]]

^<<v29-3-16,16>>^ E de Sião bramirá o próprio Jeová e de Jerusalém fará [ouvir] a sua voz. E hão de tremer céu e terra; mas Jeová será refúgio para o seu povo e baluarte para os filhos de Israel.

[[v29-3-17]]

^<<v29-3-17,17>>^ E vós tereis de saber que eu sou Jeová, vosso Deus, residindo em Sião, meu santo monte. E Jerusalém terá de tornar-se um lugar santo; e quanto aos estranhos, não mais passarão por ela.

[[v29-3-18]]

^<<v29-3-18,18>>^ “E naquele dia terá de acontecer que os montes gotejarão vinho doce,^&#42;1^ e os próprios morros manarão^&#42;2^ leite, e os próprios regos de Judá correrão todos [cheios] de água. E da casa de Jeová procederá um manancial e terá de irrigar o vale da torrente das Acácias.^&#42;3^

[NOTE]
====
. Ou “suco de uva fresco”.
. Lit.: “irão com”.
. Ou “vale de Sitim”.
====

[[v29-3-19]]

^<<v29-3-19,19>>^ Quanto ao Egito, tornar-se-á um baldio desolado; e no que se refere a Edom, tornar-se-á um ermo de desolação, por causa da violência [feita] aos filhos de Judá, em cuja terra derramaram sangue inocente.

[[v29-3-20]]

^<<v29-3-20,20>>^ Mas, no que se refere a Judá, será habitada por tempo indefinido, e Jerusalém, por geração após geração.

[[v29-3-21]]

^<<v29-3-21,21>>^ E vou considerar inocente o sangue^&#42;1^ deles que eu não tinha considerado inocente;^&#42;2^ e Jeová estará residindo em Sião.”

[NOTE]
====
. Isto é, a morte por derramamento de sangue.
. “E vou vingar o sangue deles e de modo algum vou considerá[-los] inocentes”, LXX; Vg: “E vou limpar o sangue deles que eu não havia limpado.”
====

'''

xref:029-joel/029-joel-002.adoc#v29-2-0[&#60; Capítulo Anterior] | <<v29-3-0,Topo>> | xref:030-amos/030-amos-001.adoc#v30-1-0[Próximo Capítulo &#62;]