include::./index.adoc[]

[[v23-63-0]]
=== Isaías, 63
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v23-63-1]]

^<<v23-63-1,1>>^ Quem é este que está chegando de Edom, o que tem vestes de cores brilhantes de Bozra, este que é honroso na sua vestimenta, marchando na abundância do seu poder?
“Eu, Aquele que fala em justiça, Aquele que abunda [em poder] para salvar.”

[[v23-63-2]]

^<<v23-63-2,2>>^ Por que é que a tua vestimenta está vermelha e tuas vestes estão como as de alguém que pisa no lagar de vinho?

[[v23-63-3]]

^<<v23-63-3,3>>^ “Pisei sozinho a cuba de vinho, não havendo comigo nenhum homem^&#42;1^ dos povos. E continuei a pisá-los na minha ira e continuei a calcá-los no meu furor. E seu sangue em jorros salpicava minhas vestes, e poluí toda a minha vestimenta.

[NOTE]
====
. “Homem.” Hebr.: ’ish.
====

[[v23-63-4]]

^<<v23-63-4,4>>^ Porque o dia de vingança está no meu coração, e tem chegado o próprio ano dos meus resgatados.

[[v23-63-5]]

^<<v23-63-5,5>>^ E eu estava olhando, mas não havia nenhum ajudador; e comecei a mostrar-me espantado, mas não havia quem oferecesse apoio. De modo que meu braço me proveu salvação e foi meu furor que me sustentou.

[[v23-63-6]]

^<<v23-63-6,6>>^ E continuei a calcar povos na minha ira, e passei a embriagá-los^&#42;1^ com o meu furor e a fazer seu sangue em jorros descer à terra.”

[NOTE]
====
. “Passei a quebrantá-los”, alguns mss. hebr. e antigas ed. impressas deles.
====

[[v23-63-7]]

^<<v23-63-7,7>>^ Mencionarei as benevolências^&#42;1^ de Jeová, os louvores de Jeová, segundo tudo o que Jeová nos fez, sim, a bondade abundante para com a casa de Israel, que teve para com eles segundo as suas misericórdias e segundo a abundância das suas benevolências.

[NOTE]
====
. Ou “os atos de amor leal”.
====

[[v23-63-8]]

^<<v23-63-8,8>>^ E ele prosseguiu, dizendo: “Por certo, são o meu povo, filhos que não se mostrarão falsos.” Portanto, foi para eles que se tornou Salvador.

[[v23-63-9]]

^<<v23-63-9,9>>^ Durante toda a aflição deles, foi aflitivo para ele.^&#42;1^ E seu próprio mensageiro pessoal^&#42;2^ os salvou. Ele mesmo os resgatou no seu amor e na sua compaixão, e passou a levantá-los e a carregá-los todos os dias de há muito tempo.

[NOTE]
====
. Segundo Mmargem e 17 mss. hebr.; M: “Durante toda a aflição deles, ele não foi adversário.”
. Lit.: “E o mensageiro da sua face.”
====

[[v23-63-10]]

^<<v23-63-10,10>>^ Mas eles mesmos se rebelaram e fizeram seu espírito santo sentir-se magoado. Transformou-se então em inimigo deles; ele mesmo guerreou contra eles.

[[v23-63-11]]

^<<v23-63-11,11>>^ E começaram^&#42;1^ a ser lembrados os dias de há muito tempo, Moisés, seu servo:^&#42;2^ “Onde está Aquele que os fez subir do mar com os pastores^&#42;3^ do seu rebanho? Onde está Aquele que pôs nele Seu próprio espírito santo?

[NOTE]
====
. Ou “começou”.
. “Seu servo”, Sy e alguns mss. hebr.; 1QIsaMVg: “[e] seu povo”.
. “Pastores”, 1QIsaMVg; TLXXSy e 11 mss. hebr.: “pastor”.
====

[[v23-63-12]]

^<<v23-63-12,12>>^ Aquele que fez o Seu belo braço ir à direita de Moisés; Aquele que partiu as águas diante deles, a fim de fazer para si um nome de duração indefinida;

[[v23-63-13]]

^<<v23-63-13,13>>^ Aquele que os fez andar através das águas empoladas,^&#42;1^ de modo que, qual cavalo no ermo, não tropeçaram?

[NOTE]
====
. Ou “através das águas de profundeza”. Hebr.: bat·teho·móhth.
====

[[v23-63-14]]

^<<v23-63-14,14>>^ Assim como quando o próprio animal desce ao vale plano, o próprio espírito de Jeová passou a fazê-los descansar.”
Assim conduziste o teu povo, a fim de fazer para ti mesmo um belo nome.

[[v23-63-15]]

^<<v23-63-15,15>>^ Olha desde o céu e vê desde a tua morada excelsa de santidade e beleza. Onde estão o teu zelo e a tua plena potência, a comoção das tuas entranhas e as tuas misericórdias? Refrearam-se para comigo.^&#42;1^

[NOTE]
====
. Ou: “misericórdias, [que] se refrearam até mesmo para comigo?”
====

[[v23-63-16]]

^<<v23-63-16,16>>^ Pois tu és nosso Pai; ainda que o próprio Abraão não nos conhecesse e o próprio Israel não nos reconhecesse, tu, ó Jeová, és nosso Pai. Nosso Resgatador^&#42;1^ de há muito tempo é o teu nome.

[NOTE]
====
. “Nosso Resgatador (Redentor).” Ampliando-se a idéia: “Nosso Vingador (Vindicador).” Hebr.: go·’alé·nu; lat.: re·dém·ptor nó·ster. Veja Jó 19:25 n. e Sal 19:14 n.
====

[[v23-63-17]]

^<<v23-63-17,17>>^ Por que, ó Jeová, continuas a fazer-nos vaguear dos teus caminhos? Por que endureces o nosso coração contra o temor de ti? Retorna por causa dos teus servos, as tribos de tua propriedade hereditária.

[[v23-63-18]]

^<<v23-63-18,18>>^ Por um pouco de tempo teu povo santo estava de posse. Nossos próprios adversários calcaram o teu santuário.

[[v23-63-19]]

^<<v23-63-19,19>>^ Por muito tempo nos tornamos como aqueles sobre os quais não governaste, como aqueles sobre os quais não se invocou teu nome.

'''

xref:023-isaias/023-isaias-062.adoc#v23-62-0[&#60; Capítulo Anterior] | <<v23-63-0,Topo>> | xref:023-isaias/023-isaias-064.adoc#v23-64-0[Próximo Capítulo &#62;]