include::./index.adoc[]

[[v23-41-0]]
=== Isaías, 41
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v23-41-1]]

^<<v23-41-1,1>>^ “Atentai para mim caladas, ó ilhas;^&#42;1^ e recuperem poder os próprios grupos nacionais. Aproximem-se eles. Falem nesse tempo. Cheguemo-nos perto para o próprio julgamento.

[NOTE]
====
. Ou “litorais”, isto é, do Mar Mediterrâneo.
====

[[v23-41-2]]

^<<v23-41-2,2>>^ “Quem despertou [alguém] do nascente? [Quem] passou a chamá-lo em justiça a Seus pés, para dar diante dele as nações e para fazê-lo subjugar até mesmo reis? [Quem] continuou a entregá-los como pó à espada, de modo que foram impelidos pelo seu arco como o mero restolho?

[[v23-41-3]]

^<<v23-41-3,3>>^ [Quem] os esteve perseguindo, passando pacificamente adiante com os seus pés na vereda [pela qual] não passou a vir?

[[v23-41-4]]

^<<v23-41-4,4>>^ Quem tem estado ativo e tem feito [isso], convocando as gerações desde o começo?
“Eu, Jeová, o Primeiro; e sou o mesmo com os últimos.”

[[v23-41-5]]

^<<v23-41-5,5>>^ As ilhas viram [isso] e começaram a temer. As próprias extremidades da terra começaram a tremer. Chegaram-se e continuaram a vir.

[[v23-41-6]]

^<<v23-41-6,6>>^ Foram ajudar cada um ao seu companheiro, e ele dizia ao seu irmão: “Sê forte.”

[[v23-41-7]]

^<<v23-41-7,7>>^ De modo que o artífice foi fortalecer o trabalhador em metal; aquele que fazia o alisamento com o malho, ao que martelava na bigorna, dizendo referente à soldadura: “É boa.” Finalmente, alguém o prendeu com pregos para que não pudesse ser abalado.

[[v23-41-8]]

^<<v23-41-8,8>>^ “Mas tu, ó Israel, és meu servo, tu, ó Jacó, a quem escolhi, a descendência^&#42;1^ de Abraão, meu amigo;^&#42;2^

[NOTE]
====
. Ou “prole”.
. Ou “aquele que me ama”.
====

[[v23-41-9]]

^<<v23-41-9,9>>^ tu, a quem agarrei desde as extremidades da terra, e tu, a quem convoquei mesmo das suas partes remotas. E, assim, eu te disse: ‘Tu és meu servo; eu te escolhi e não te rejeitei.

[[v23-41-10]]

^<<v23-41-10,10>>^ Não tenhas medo, pois estou contigo. Não olhes em volta, pois eu sou teu Deus.^&#42;1^ Vou fortificar-te. Vou realmente ajudar-te. Vou deveras segurar-te firmemente com a minha direita de justiça.’

[NOTE]
====
. “Teu Deus.” Hebr.: ’Elo·heí·kha.
====

[[v23-41-11]]

^<<v23-41-11,11>>^ “Eis que ficarão envergonhados e humilhados todos os que se acaloram contra ti. Os homens que têm uma altercação contigo ficarão como nada e perecerão.

[[v23-41-12]]

^<<v23-41-12,12>>^ Tu os procurarás, mas não os acharás, estes homens que estão em briga contigo. Tornar-se-ão como algo inexistente e como nada, estes homens em guerra contigo.

[[v23-41-13]]

^<<v23-41-13,13>>^ Pois eu, Jeová, teu Deus, agarro a tua direita, Aquele que te diz: ‘Não tenhas medo. Eu mesmo te ajudarei.’

[[v23-41-14]]

^<<v23-41-14,14>>^ “Não tenhas medo, ó verme Jacó, homens^&#42;1^ de Israel. Eu mesmo te^&#42;2^ ajudarei”, é a pronunciação de Jeová, sim, teu Resgatador, o Santo de Israel.

[NOTE]
====
. Ou “varões”. Hebr.: methéh.
. “Te”, hebr. fem. sing., referindo-se a “verme”, hebr. fem.
====

[[v23-41-15]]

^<<v23-41-15,15>>^ “Eis que fiz de ti um trenó debulhador, um instrumento de debulhar novo, com [dentes de] fio duplo. Trilharás os montes e [os] esmagarás; e farás os morros iguais à pragana.

[[v23-41-16]]

^<<v23-41-16,16>>^ Tu os joeirarás e o próprio vento os levará embora, e o próprio vendaval os impelirá por caminhos diferentes. E tu mesmo jubilarás em Jeová. No Santo de Israel jactar-te-ás de ti mesmo.”

[[v23-41-17]]

^<<v23-41-17,17>>^ “Os atribulados e os pobres estão procurando água, mas não há nenhuma. Por causa da sede ressecou-se a própria língua deles. Eu mesmo, Jeová, lhes responderei. Eu, o Deus de Israel,^&#42;1^ não os abandonarei.

[NOTE]
====
. “O Deus de Israel.” Hebr.: ’Elo·héh Yis·ra·’él.
====

[[v23-41-18]]

^<<v23-41-18,18>>^ Em morros calvos abrirei rios, e no meio dos vales planos, mananciais. Farei do ermo um banhado de juncos e da terra árida, nascentes de água.

[[v23-41-19]]

^<<v23-41-19,19>>^ Porei no ermo o cedro, a acácia e a murta, e o oleastro. Na planície desértica^&#42;1^ colocarei ao mesmo tempo o junípero, o freixo e o cipreste;

[NOTE]
====
. Ou: “No Arabá.” Veja De 1:1 n.: “desérticas”.
====

[[v23-41-20]]

^<<v23-41-20,20>>^ a fim de que as pessoas ao mesmo tempo vejam, e saibam, e atentem, e tenham perspicácia, que a própria mão de Jeová fez isso e o próprio Santo de Israel o criou.”

[[v23-41-21]]

^<<v23-41-21,21>>^ “Apresentai o vosso litígio”, diz Jeová. “Exponde os vossos argumentos”, diz o Rei de Jacó.

[[v23-41-22]]

^<<v23-41-22,22>>^ “Exponde e contai-nos as coisas que vão acontecer. As primeiras coisas — quais foram — contai-nos deveras, para que empenhemos nosso coração e saibamos o futuro delas. Ou fazei-nos ouvir até mesmo as coisas vindouras.

[[v23-41-23]]

^<<v23-41-23,23>>^ Contai as coisas que hão de vir posteriormente, para que saibamos que sois deuses.^&#42;1^ Sim, devíeis fazer o bem ou fazer o mal, para que possamos olhar em volta e ao mesmo tempo vê-lo.

[NOTE]
====
. Lit.: “que deuses sois”. Hebr.: ki ’elo·hím ’at·tém.
====

[[v23-41-24]]

^<<v23-41-24,24>>^ Eis que sois algo inexistente e vossa realização não é nada. Coisa detestável é todo aquele que vos escolhe.

[[v23-41-25]]

^<<v23-41-25,25>>^ “Despertei [alguém] do norte, e ele virá. Do nascente do sol ele invocará meu nome. E ele virá sobre os delegados governantes como [se fossem] barro e assim como o oleiro pisa a massa úmida.

[[v23-41-26]]

^<<v23-41-26,26>>^ “Quem é que contou alguma coisa desde o começo, para que [a] saibamos, ou dos tempos passados, para que digamos: ‘Ele tem razão’? Realmente, não há quem conte [algo]. Realmente, não há quem faça [outro] ouvir. Realmente, não há quem ouça quaisquer declarações de vós.”

[[v23-41-27]]

^<<v23-41-27,27>>^ Há primeiro um, [dizendo] a Sião: “Eis que estão aqui!” e eu darei a Jerusalém um portador de boas novas.

[[v23-41-28]]

^<<v23-41-28,28>>^ E eu estava vendo, e não havia homem; e dentre estes tampouco havia quem desse conselho. E continuei a perguntar-lhes, para que dessem uma resposta.

[[v23-41-29]]

^<<v23-41-29,29>>^ Eis que todos eles são algo inexistente.^&#42;1^ Seus trabalhos não são coisa alguma. Suas imagens fundidas são vento^&#42;2^ e irrealidade.

[NOTE]
====
. “Algo inexistente”, mediante uma ligeira correção em harmonia com 1QIsaTSy; M: “prejuízo; algo prejudicial”.
. “Vento.” Hebr.: rú·ahh. Veja Gên 1:2 n.: “ativa”.
====

'''

xref:023-isaias/023-isaias-040.adoc#v23-40-0[&#60; Capítulo Anterior] | <<v23-41-0,Topo>> | xref:023-isaias/023-isaias-042.adoc#v23-42-0[Próximo Capítulo &#62;]