include::./index.adoc[]

[[v23-3-0]]
=== Isaías, 3
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v23-3-1]]

^<<v23-3-1,1>>^ Pois, eis que o [verdadeiro] Senhor,^&#42;1^ Jeová dos exércitos, está removendo de Jerusalém e de Judá o sustento e o apoio, todo o sustento de pão e todo o sustento de água,

[NOTE]
====
. Veja 1:24 n.
====

[[v23-3-2]]

^<<v23-3-2,2>>^ o poderoso e o guerreiro,^&#42;1^ o juiz e o profeta, e o adivinho, e o homem idoso,

[NOTE]
====
. Lit.: “e homem de guerra”. Hebr.: we’ísh mil·hha·máh.
====

[[v23-3-3]]

^<<v23-3-3,3>>^ o chefe de cinqüenta, e o homem muito respeitado,^&#42;1^ e o conselheiro, e o hábil em artes mágicas, e o encantador perito.^&#42;2^

[NOTE]
====
. Lit.: “um de face erguida”.
. Ou “perito em encantar serpentes”. Veja Ap. 7A.
====

[[v23-3-4]]

^<<v23-3-4,4>>^ E certamente farei rapazes os seus príncipes, e o mero poder arbitrário^&#42;1^ dominará sobre eles.

[NOTE]
====
. “Poder arbitrário.” Ou “caprichos”.
====

[[v23-3-5]]

^<<v23-3-5,5>>^ E o povo realmente tiranizará um ao outro, sim, cada um o seu próximo. Arremeterão, o rapaz contra o homem idoso, e o de pouca estima contra aquele que é para ser honrado.

[[v23-3-6]]

^<<v23-3-6,6>>^ Pois cada um pegará seu irmão na casa de seu pai, [dizendo:] “Tens uma capa. Devias tornar-te ditador para nós, e esta massa derrocada devia estar debaixo de tua mão.”

[[v23-3-7]]

^<<v23-3-7,7>>^ Naquele dia ele levantará [a voz], dizendo: “Não me tornarei pensador de feridas; e na minha casa não há nem pão nem capa. Não me deveis constituir ditador sobre o povo.”

[[v23-3-8]]

^<<v23-3-8,8>>^ Pois Jerusalém tropeçou e a própria Judá caiu, porque sua língua e suas ações são contra Jeová, comportando-se rebeldemente aos olhos da sua glória.

[[v23-3-9]]

^<<v23-3-9,9>>^ A própria expressão das suas faces^&#42;1^ testifica realmente contra eles, e contam deveras seu pecado semelhante ao de Sodoma. Não [o] ocultaram. Ai da sua alma! Pois trouxeram calamidade sobre si mesmos.

[NOTE]
====
. Ou: “Um mero olhar para as suas faces”; ou: “Sua mera consideração para com faces.”
====

[[v23-3-10]]

^<<v23-3-10,10>>^ Dizei que [irá] bem ao justo, porque eles comerão dos próprios frutos das suas ações.

[[v23-3-11]]

^<<v23-3-11,11>>^ Ai do iníquo! — Calamidade; pois o tratamento [dispensado] pelas suas próprias mãos será dispensado a ele!

[[v23-3-12]]

^<<v23-3-12,12>>^ Quanto ao meu povo, seus feitores^&#42;1^ agem com severidade^&#42;2^ e meras mulheres estão realmente dominando sobre ele. Ó meu povo, os que te encaminham fazem-te vaguear, e confundiram o caminho das tuas veredas.

[NOTE]
====
. Ou “seu governo”.
. “Crianças são seus feitores”, mediante uma correção do M.
====

[[v23-3-13]]

^<<v23-3-13,13>>^ Jeová toma posição para contender e se põe de pé para sentenciar povos.

[[v23-3-14]]

^<<v23-3-14,14>>^ O próprio Jeová entrará em julgamento com os idosos do seu povo e com os seus príncipes.
“E vós mesmos queimastes o vinhedo. Aquilo que foi roubado do atribulado está nas vossas casas.

[[v23-3-15]]

^<<v23-3-15,15>>^ Que quereis dizer com isso, que esmigalhais meu povo e que moeis as próprias faces dos atribulados?” é a pronunciação do Soberano Senhor, Jeová dos exércitos.

[[v23-3-16]]

^<<v23-3-16,16>>^ E Jeová disse: “Visto que as filhas de Sião se ensoberbeceram e andam com as gargantas esticadas e com olhares requebrados, andam com passinhos miúdos e fazem um som tilintante com os seus pés,^&#42;1^

[NOTE]
====
. Ou “nos seus pés sacodem manilhas (axorcas)”.
====

[[v23-3-17]]

^<<v23-3-17,17>>^ também Jeová^&#42;1^ fará realmente tinhoso o alto da cabeça das filhas de Sião, e Jeová mesmo exporá a própria testa delas.

[NOTE]
====
. Uma das 134 mudanças de YHWH para ’Adho·naí feitas pelos escribas. Veja Ap. 1B.
====

[[v23-3-18]]

^<<v23-3-18,18>>^ Naquele dia Jeová^&#42;1^ tirará a beleza das manilhas,^&#42;2^ e as fitas para a cabeça,^&#42;3^ e os ornamentos em forma de lua,^&#42;4^

[NOTE]
====
. Veja v. 17 n.
. Ou “axorcas”.
. Lit.: “pequenos sóis”.
. Ou “pequenas luas”.
====

[[v23-3-19]]

^<<v23-3-19,19>>^ os pingentes, e os braceletes, e os véus,

[[v23-3-20]]

^<<v23-3-20,20>>^ as coberturas para a cabeça, e as correntinhas para os passos, e as faixas para o busto,^&#42;1^ e as ‘casas da alma’,^&#42;2^ e as ornamentais conchas zunzunantes,^&#42;3^

[NOTE]
====
. Ou “as cintas”.
. Provavelmente receptáculos para perfume.
. Ou “os amuletos”.
====

[[v23-3-21]]

^<<v23-3-21,21>>^ os anéis, e as argolas para as narinas,

[[v23-3-22]]

^<<v23-3-22,22>>^ os trajes de gala, e as sobrevestes, e as mantas, e as bolsas,

[[v23-3-23]]

^<<v23-3-23,23>>^ e os espelhos de mão, e as peças de roupa interior, e os turbantes, e os véus largos.

[[v23-3-24]]

^<<v23-3-24,24>>^ “E tem de se dar que em vez de óleo de bálsamo virá a haver apenas um cheiro de mofo; e em vez de um cinto, uma corda; e em vez de um penteado artístico, a calvície; e em vez de uma veste suntuosa, um envoltório de serapilheira; marca de fogo em vez de lindeza.

[[v23-3-25]]

^<<v23-3-25,25>>^ Teus^&#42;1^ próprios homens cairão à espada, e tua potência,^&#42;2^ pela guerra.

[NOTE]
====
. “Teus”, hebr. fem. sing., referindo-se a Sião ou Jerusalém.
. “Potentes (fortes)”, LXXSyVg.
====

[[v23-3-26]]

^<<v23-3-26,26>>^ E as entradas dela terão de estar de luto e expressar tristeza, e ela certamente será esvaziada. Sentar-se-á no próprio chão.”

'''

xref:023-isaias/023-isaias-002.adoc#v23-2-0[&#60; Capítulo Anterior] | <<v23-3-0,Topo>> | xref:023-isaias/023-isaias-004.adoc#v23-4-0[Próximo Capítulo &#62;]