include::./index.adoc[]

[[v23-28-0]]
=== Isaías, 28
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v23-28-1]]

^<<v23-28-1,1>>^ Ai da coroa altaneira^&#42;1^ dos ébrios de Efraim e da flor desvanecente do seu ornato de beleza que está na cabeceira do vale fértil^&#42;2^ dos que foram vencidos pelo vinho!

[NOTE]
====
. Lit.: “coroa de alteza”.
. Lit.: “do vale de gorduras [ou: solos férteis]”.
====

[[v23-28-2]]

^<<v23-28-2,2>>^ Eis que Jeová^&#42;1^ tem alguém forte e vigoroso. Qual temporal trovejante de saraiva, uma tempestade destrutiva, qual temporal trovejante de fortes águas inundantes, ele certamente lançará por terra com força.^&#42;2^

[NOTE]
====
. Uma das 134 mudanças de YHWH para ’Adho·naí feitas pelos escribas. Veja Ap. 1B.
. Lit.: “mão”.
====

[[v23-28-3]]

^<<v23-28-3,3>>^ Com os pés serão pisadas as coroas altaneiras dos ébrios de Efraim.

[[v23-28-4]]

^<<v23-28-4,4>>^ E a flor desvanecente do seu ornato de beleza, que está na cabeceira do vale fértil, terá de tornar-se como o figo temporão antes do verão, o qual, vendo-o aquele que o vê, ele engole enquanto ainda está na palma da sua mão.

[[v23-28-5]]

^<<v23-28-5,5>>^ Naquele dia, Jeová dos exércitos tornar-se-á como coroa de ornato e como grinalda de beleza para os remanescentes^&#42;1^ do seu povo,

[NOTE]
====
. Ou “para o restante”.
====

[[v23-28-6]]

^<<v23-28-6,6>>^ e como espírito de justiça^&#42;1^ para o sentado em julgamento, e como potência [para] os que fazem recuar a batalha do portão.

[NOTE]
====
. Ou “julgamento”. Hebr.: mish·pát.
====

[[v23-28-7]]

^<<v23-28-7,7>>^ E também estes — por causa do vinho, perderam-se, e por causa da bebida inebriante, [andaram] vagueando. Sacerdote e profeta — perderam-se por causa da bebida inebriante, ficaram confusos em resultado do vinho, [andaram] vagueando em resultado da bebida inebriante; perderam-se na sua visão, vacilaram quanto à decisão.

[[v23-28-8]]

^<<v23-28-8,8>>^ Porque as próprias mesas ficaram todas cheias de vômito asqueroso — não há lugar [sem ele].

[[v23-28-9]]

^<<v23-28-9,9>>^ A quem se instruirá em conhecimento e a quem se fará compreender o que se ouviu?^&#42;1^ Os que foram desmamados do leite, os que foram afastados dos peitos?

[NOTE]
====
. Ou “compreender o relato”.
====

[[v23-28-10]]

^<<v23-28-10,10>>^ Pois é “ordem sobre ordem, ordem sobre ordem, cordel de medir sobre cordel de medir, cordel de medir sobre cordel de medir, um pouco aqui, um pouco ali”.^&#42;1^

[NOTE]
====
. Lit.: “Pois é ‘tsaw sobre tsaw, tsaw sobre tsaw, qaw sobre qaw, qaw sobre qaw, um pouco aqui, um pouco ali’”, em imitação dos sons das palavras do profeta. Hebr.: ki tsaw la·tsáw tsaw la·tsáw, qaw la·qáw qaw la·qáw, ze‛éhr sham ze‛éhr sham.
====

[[v23-28-11]]

^<<v23-28-11,11>>^ Porque por meio dos que gaguejam com os seus lábios e por uma língua diferente ele falará a este povo,

[[v23-28-12]]

^<<v23-28-12,12>>^ aqueles a quem ele disse: “Este é o lugar de descanso. Dai descanso ao cansado. E este é o lugar de folga”, mas que não quiseram ouvir.

[[v23-28-13]]

^<<v23-28-13,13>>^ E para eles a palavra de Jeová certamente se tornará “ordem sobre ordem, ordem sobre ordem, cordel de medir sobre cordel de medir, cordel de medir sobre cordel de medir, um pouco aqui, um pouco ali”, a fim de que vão e certamente tropecem [caindo] para trás, e realmente sejam quebrados, e enlaçados, e apanhados.

[[v23-28-14]]

^<<v23-28-14,14>>^ Portanto, ouvi a palavra de Jeová, ó fanfarrões,^&#42;1^ ó governantes deste povo que estais em Jerusalém:

[NOTE]
====
. Lit.: “vós homens de fanfarronada”.
====

[[v23-28-15]]

^<<v23-28-15,15>>^ Visto que dissestes: “Concluímos um pacto com a Morte; e realizamos uma visão^&#42;1^ com o Seol; a enxurrada transbordante, caso ela passe, não chegará a nós, pois fizemos da mentira o nosso refúgio e nos escondemos na falsidade”;

[NOTE]
====
. Lit.: “um visionário”, M; T: “paz”; LXXVg: “pacto(s)”.
====

[[v23-28-16]]

^<<v23-28-16,16>>^ por isso, assim disse o Soberano Senhor Jeová: “Eis que lanço^&#42;1^ por alicerce em Sião uma pedra,^&#42;2^ uma pedra provada, ângulo precioso de um alicerce seguro.^&#42;3^ Ninguém que exercer fé ficará em pânico.^&#42;4^

[NOTE]
====
. “Eis que lanço”, em harmonia com TLXXSyVg; M: “Eis-me, [Aquele que] lançou.”
. “Em Sião uma pedra.” Hebr.: be·Tsi·yóhn ’á·ven; gr.: Si·ón lí·thon; lat.: Sí·on lá·pi·dem; sir.: beTse·hiun ki’·fa’; T(aram.): beTsi·yóhn mé·lekh, “em Sião um rei”.
. Ou “ângulo de encontro de alicerce com alicerce”. A expressão “alicerce seguro” lit. é: “alicerce alicerçado”.
. Ou “agirá precipitadamente”.
====

[[v23-28-17]]

^<<v23-28-17,17>>^ E eu vou fazer do juízo^&#42;1^ o cordel de medir e da justiça o nível; e a saraiva terá de arrasar o refúgio da mentira e as águas é que levarão de enxurrada o próprio esconderijo.

[NOTE]
====
. Ou “julgamento”. Hebr.: mish·pát.
====

[[v23-28-18]]

^<<v23-28-18,18>>^ E vosso pacto com a Morte há de ser dissolvido^&#42;1^ e esta vossa visão com o Seol não ficará de pé. A enxurrada transbordante, quando passar — então tereis de tornar-vos para ela um lugar pisado.

[NOTE]
====
. Lit.: “E . . . foi coberto”. Hebr.: wekhup·pár.
====

[[v23-28-19]]

^<<v23-28-19,19>>^ Quantas vezes ela passar vos levará embora, pois passará manhã após manhã, durante o dia e durante a noite; e terá de tornar-se nada mais que uma razão para estremecimento, para fazer [outros] compreender o que se ouviu.”^&#42;1^

[NOTE]
====
. Ou “o relato”.
====

[[v23-28-20]]

^<<v23-28-20,20>>^ Pois o leito mostrou-se curto demais para se estirar nele, e o próprio lençol tecido é [demasiado] estreito para se enrolar nele.

[[v23-28-21]]

^<<v23-28-21,21>>^ Porque Jeová se levantará assim como no monte Perazim, ficará agitado como na baixada perto de Gibeão, para fazer o seu ato — seu ato é estranho — e para executar a sua obra^&#42;1^ — sua obra é incomum.

[NOTE]
====
. Ou “seu serviço”. Hebr.: ‛avo·dha·thóh.
====

[[v23-28-22]]

^<<v23-28-22,22>>^ E agora, não vos mostreis zombadores, para que as vossas ligaduras não se tornem fortes, pois há um extermínio, sim, algo determinado, de que ouvi [falar] da parte do Soberano Senhor, Jeová dos exércitos, para toda a terra.^&#42;1^

[NOTE]
====
. “A terra.” Hebr.: ha·’á·rets.
====

[[v23-28-23]]

^<<v23-28-23,23>>^ Dai ouvidos e escutai a minha voz; prestai atenção e escutai a minha declaração.

[[v23-28-24]]

^<<v23-28-24,24>>^ Acaso é o dia inteiro que o lavrador ara a fim de semear, que ele afrouxa e grada seu solo?

[[v23-28-25]]

^<<v23-28-25,25>>^ Tendo aplainado a sua superfície, não espalha ele então o cominho preto e esparrama o cominho, e não tem de plantar o trigo, o sorgo^&#42;1^ e a cevada no lugar designado,^&#42;2^ e espelta como seu termo?

[NOTE]
====
. “O trigo, o sorgo.” Ou “trigo em fileiras”. O significado da segunda palavra hebr. é incerto.
. Ou “no tempo designado”; ou: “na parte determinada”. O significado é incerto.
====

[[v23-28-26]]

^<<v23-28-26,26>>^ E corrige-se a ele segundo o que é direito.^&#42;1^ Seu próprio Deus^&#42;2^ o instrui.

[NOTE]
====
. Ou “quanto ao julgamento”.
. “Seu próprio Deus.” Hebr.: ’Elo·háv.
====

[[v23-28-27]]

^<<v23-28-27,27>>^ Pois não é com o debulhador que se trilha o cominho preto; e sobre o cominho não se revolve nenhuma roda de carroça. Pois é com um bastão que geralmente se malha o cominho preto, e o cominho, com uma vara.

[[v23-28-28]]

^<<v23-28-28,28>>^ Costuma-se pulverizar o próprio cereal do pão? Pois nunca se continua incessantemente a trilhá-lo. E ele terá de pôr em movimento o rolo da sua carroça, bem como seus próprios corcéis, [mas] não o pulverizará.

[[v23-28-29]]

^<<v23-28-29,29>>^ Isto também é o que procedeu do próprio Jeová dos exércitos, que tem sido maravilhoso no conselho, que tem agido grandiosamente em trabalho eficiente.

'''

xref:023-isaias/023-isaias-027.adoc#v23-27-0[&#60; Capítulo Anterior] | <<v23-28-0,Topo>> | xref:023-isaias/023-isaias-029.adoc#v23-29-0[Próximo Capítulo &#62;]