include::./index.adoc[]

[[v23-15-0]]
=== Isaías, 15
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v23-15-1]]

^<<v23-15-1,1>>^ A pronúncia contra Moabe: Visto que foi assolada durante a noite, a própria Ar de Moabe foi silenciada. Visto que foi assolada durante a noite, a própria Quir de Moabe foi silenciada.

[[v23-15-2]]

^<<v23-15-2,2>>^ Ele subiu até A Casa e a Díbon,^&#42;1^ aos altos, para choro. O próprio Moabe uiva por Nebo e por Medeba. Em todas as cabeças nele há calvície; toda barba está cortada.

[NOTE]
====
. Segundo 1QIsaM; T: “às casas de Díbon”; Sy: “à casa de Ríbon”; Vg: “A Casa e Díbon.”
====

[[v23-15-3]]

^<<v23-15-3,3>>^ Nas suas ruas cingiram-se de serapilheira. Nos seus^&#42;1^ terraços e nas suas praças públicas, cada um dos seus uiva, descendo com choro.

[NOTE]
====
. Lit.: “nos . . . dela”.
====

[[v23-15-4]]

^<<v23-15-4,4>>^ E Hésbon e Eleale estão clamando. Sua voz ouviu-se até Jaaz. Por isso é que os próprios homens armados de Moabe estão bradando. Sua própria alma tem tiritado no seu íntimo.

[[v23-15-5]]

^<<v23-15-5,5>>^ Meu próprio coração clama por causa de Moabe. Seus fugitivos já chegaram até Zoar [e] Eglate-Selisaia. Pois na subida de Luíte — [cada] um sobe por ela com choro; pois no caminho para Horonaim levantam o clamor sobre a catástrofe.

[[v23-15-6]]

^<<v23-15-6,6>>^ Pois as próprias águas de Ninrim se tornam puras desolações. Porque secou-se a grama verde, acabou-se a relva; nada ficou verde.

[[v23-15-7]]

^<<v23-15-7,7>>^ Por isso é que as sobras e seus bens que armazenaram, eles continuam carregando sobre o vale da torrente dos choupos.

[[v23-15-8]]

^<<v23-15-8,8>>^ Pois o clamor tem dado volta pelo território de Moabe. Seu uivo vai até Eglaim; seu uivo vai até Beer-Elim.

[[v23-15-9]]

^<<v23-15-9,9>>^ Porque as próprias águas de Dimom ficaram cheias de sangue. Pois porei sobre Dimom coisas adicionais, tais como um leão para os escapados de Moabe, que se escapam, e para os remanescentes do solo.

'''

xref:023-isaias/023-isaias-014.adoc#v23-14-0[&#60; Capítulo Anterior] | <<v23-15-0,Topo>> | xref:023-isaias/023-isaias-016.adoc#v23-16-0[Próximo Capítulo &#62;]