include::./index.adoc[]

[[v23-51-0]]
=== Isaías, 51
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v23-51-1]]

^<<v23-51-1,1>>^ “Escutai-me, vós os que ides no encalço da justiça, vós os que procurais a Jeová. Olhai para a rocha de que fostes talhados e para a cavidade do poço de que fostes extraídos.

[[v23-51-2]]

^<<v23-51-2,2>>^ Olhai para Abraão, vosso pai, e para Sara, que gradualmente vos deu à luz com dores de parto. Pois ele foi um só quando o chamei, e eu passei a abençoá-lo e a fazê-lo muitos.

[[v23-51-3]]

^<<v23-51-3,3>>^ Porque Jeová certamente consolará Sião. Com certeza consolará todos os lugares devastados dela, e fará seu ermo igual ao Éden e sua planície desértica igual ao jardim^&#42;1^ de Jeová. Exultação e alegria é que se acharão nela, agradecimentos e voz de melodia.

[NOTE]
====
. “Paraíso”, LXXSy.
====

[[v23-51-4]]

^<<v23-51-4,4>>^ “Presta atenção a mim, ó meu povo; e tu, meu grupo nacional, dá-me ouvidos. Pois de mim sairá uma lei^&#42;1^ e farei a minha decisão judicial ficar em repouso mesmo como uma luz para os povos.^&#42;2^

[NOTE]
====
. Ou “a própria instrução”.
. “E minha decisão judicial como uma luz para os povos num instante”, mediante uma ligeira correção.
====

[[v23-51-5]]

^<<v23-51-5,5>>^ Perto está a minha justiça. Há de sair a minha salvação e meus próprios braços julgarão até os povos. Em mim terão esperança as próprias ilhas e por meu braço esperarão.

[[v23-51-6]]

^<<v23-51-6,6>>^ “Levantai os vossos olhos para os próprios céus e olhai para a terra embaixo. Pois os próprios céus terão de ser dispersados em fragmentos como a fumaça, e a própria terra se gastará como uma veste, e seus próprios habitantes morrerão como um mero borrachudo. Mas, quanto à minha salvação, mostrará ser mesmo por tempo indefinido, e a minha própria justiça não será desbaratada.

[[v23-51-7]]

^<<v23-51-7,7>>^ “Escutai-me, vós os que conheceis a justiça, povo em cujo coração está a minha lei. Não tenhais medo do vitupério de homens mortais^&#42;1^ e não fiqueis aterrorizados por causa das suas palavras injuriosas.

[NOTE]
====
. “Homens mortais.” Hebr.: ’enóhsh.
====

[[v23-51-8]]

^<<v23-51-8,8>>^ Porque a traça^&#42;1^ os consumirá como se fossem uma veste e a traça roedora^&#42;2^ os consumirá como se fossem lã. Mas, quanto à minha justiça, mostrará ser mesmo por tempo indefinido, e minha salvação, por inúmeras gerações.”^&#42;3^

[NOTE]
====
. “A traça.” Hebr.: ‛ash.
. “A traça roedora.” Hebr.: sas.
. Lit.: “por geração de gerações”.
====

[[v23-51-9]]

^<<v23-51-9,9>>^ Desperta, desperta, reveste-te de força, ó braço de Jeová! Desperta como nos dias de outrora, como durante as gerações de tempos há muito passados. Não és tu^&#42;1^ aquele que despedaçou Raabe,^&#42;2^ que traspassou o monstro marinho?^&#42;3^

[NOTE]
====
. “Tu”, hebr. fem., referindo-se ao “braço”, hebr. fem.
. Ou “o Arremetedor”. Vg: “o altivo (orgulhoso)”, hebr. masc.
. “O dragão”, Vg.
====

[[v23-51-10]]

^<<v23-51-10,10>>^ Não és tu aquele que secou o mar, as águas da vasta profundeza?^&#42;1^ Aquele que fez das funduras do mar um caminho a ser atravessado pelos resgatados?

[NOTE]
====
. “Da . . . profundeza.” Hebr.: tehóhm; LXXVg: “do abismo”. Veja Gên 1:2 n.: “profundeza”.
====

[[v23-51-11]]

^<<v23-51-11,11>>^ Então retornarão os próprios remidos de Jeová e terão de chegar a Sião com clamor jubilante, e sobre a sua cabeça haverá alegria por tempo indefinido. Alcançarão exultação e alegria. O pesar e o suspiro certamente fugirão.

[[v23-51-12]]

^<<v23-51-12,12>>^ “Eu é que sou Aquele que vos consola.
“Quem és tu^&#42;1^ para temer o homem mortal que morrerá, e o filho da humanidade^&#42;2^ que será constituído em mera erva verde?

[NOTE]
====
. “Tu”, hebr. fem. sing., referindo-se a “Sião”.
. Ou “homem terreno”. Hebr.: ’a·dhám.
====

[[v23-51-13]]

^<<v23-51-13,13>>^ E para te esqueceres de Jeová, Aquele que te^&#42;1^ fez, Aquele que estendeu os céus e lançou o alicerce da terra, de modo que estiveste constantemente apavorado, o dia inteiro, por causa do furor daquele que [te] assediava, como se ele estivesse pronto para [te] arruinar? E onde está o furor daquele que [te] assediava?

[NOTE]
====
. “Te”, hebr. masc. sing.
====

[[v23-51-14]]

^<<v23-51-14,14>>^ “O encurvado em cadeias há de ser prontamente solto, para que não vá morto à cova e para que não lhe falte o pão.

[[v23-51-15]]

^<<v23-51-15,15>>^ “Mas eu, Jeová, sou teu Deus,^&#42;1^ Aquele que agita o mar para tumultuar as suas ondas. Jeová dos exércitos é seu nome.

[NOTE]
====
. “Teu [hebr. masc. sing.] Deus [hebr. pl.].” Hebr.: ’Elo·heí·kha.
====

[[v23-51-16]]

^<<v23-51-16,16>>^ E porei as minhas palavras na tua boca e hei de cobrir-te com a sombra da minha mão, a fim de plantar os céus e lançar o alicerce da terra, e para dizer a Sião: ‘Tu és meu povo.’

[[v23-51-17]]

^<<v23-51-17,17>>^ “Desperta, desperta, levanta-te, ó Jerusalém, tu que bebeste da mão de Jeová o copo do seu furor. O grande cálice, o copo que atordoa bebeste, o esvaziaste.

[[v23-51-18]]

^<<v23-51-18,18>>^ Não havia nenhum de todos os filhos que ela deu à luz que a conduzisse e não havia nenhum de todos os filhos que ela criou que a tomasse pela mão.

[[v23-51-19]]

^<<v23-51-19,19>>^ Estas duas coisas te sobrevieram. Quem se compadecerá de ti? Assolação e desmoronamento, e fome e espada! Quem^&#42;1^ te consolará?

[NOTE]
====
. “Quem [te consolará]?” 1QIsaLXXSyVg; M: “Quem — eu [te consolarei]”; T: “Ninguém senão eu [te consolarei].”
====

[[v23-51-20]]

^<<v23-51-20,20>>^ Teus próprios filhos desmaiaram. Deitaram-se na cabeceira de todas as ruas como ovelhas selváticas na rede, como os que estão cheios do furor de Jeová, da censura de teu Deus.”

[[v23-51-21]]

^<<v23-51-21,21>>^ Portanto, escuta isto, por favor, ó mulher atribulada e embriagada, mas não de vinho.

[[v23-51-22]]

^<<v23-51-22,22>>^ Assim disse o teu Senhor,^&#42;1^ Jeová, sim, teu Deus, que contende pelo seu povo: “Eis que vou tirar-te da mão o copo que atordoa. O grande cálice, meu copo de furor — não mais repetirás o beber dele.

[NOTE]
====
. “Teu [hebr. fem. sing.] Senhor.” Hebr.: ’Adho·ná·yikh, pl. de ’A·dhóhn, para denotar grandiosidade ou majestade.
====

[[v23-51-23]]

^<<v23-51-23,23>>^ E eu vou pô-lo na mão dos que te irritam, os que disseram à tua alma: ‘Curva-te, para que possamos atravessar’, de modo que costumavas fazer as tuas costas como a terra e como a rua para os que atravessavam.”

'''

xref:023-isaias/023-isaias-050.adoc#v23-50-0[&#60; Capítulo Anterior] | <<v23-51-0,Topo>> | xref:023-isaias/023-isaias-052.adoc#v23-52-0[Próximo Capítulo &#62;]