include::./index.adoc[]

[[v23-30-0]]
=== Isaías, 30
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v23-30-1]]

^<<v23-30-1,1>>^ “Ai dos filhos obstinados”, é a pronunciação de Jeová, “[os que estão dispostos] a executar o conselho, mas não o procedente de mim; e a derramar uma libação,^&#42;1^ mas não com o meu espírito, a fim de acrescentar pecado a pecado;

[NOTE]
====
. Ou “formar uma aliança”, por se derramar uma libação. Ou “entretecer uma cobertura”.
====

[[v23-30-2]]

^<<v23-30-2,2>>^ os que se põem a caminho para descer ao Egito e que não foram consultar a minha própria boca, para se abrigarem no baluarte de Faraó e para se refugiarem na sombra do Egito!

[[v23-30-3]]

^<<v23-30-3,3>>^ E o baluarte de Faraó terá de tornar-se mesmo para vós razão para vergonha, e o refúgio na sombra do Egito, causa para humilhação.

[[v23-30-4]]

^<<v23-30-4,4>>^ Pois os seus príncipes vieram a estar na própria Zoã e os seus próprios enviados^&#42;1^ atingem até mesmo Hanes.

[NOTE]
====
. Ou “mensageiros”.
====

[[v23-30-5]]

^<<v23-30-5,5>>^ Cada um ficará certamente envergonhado de um povo que não aproveita a ninguém, que não é de ajuda e que não traz proveito, mas que é razão para vergonha e também causa para vitupério.”

[[v23-30-6]]

^<<v23-30-6,6>>^ A pronúncia contra os animais do sul:^&#42;1^ Através^&#42;2^ da terra de aflição e de condições difíceis, do leão e do leopardo rosnante,^&#42;3^ da víbora e da cobra ardente, voadora, carregam seus recursos nos lombos de jumentos adultos e seus suprimentos nas corcovas de camelos. Não se mostrarão de proveito algum para o povo.

[NOTE]
====
. Lit.: “Negebe”. Hebr.: né·ghev.
. Ou: “Na; para dentro da”.
. “Rosnante”, mediante uma correção; M: “deles”.
====

[[v23-30-7]]

^<<v23-30-7,7>>^ E os egípcios são apenas vaidade e sua ajuda será apenas em vão. Por isso chamei a esta:^&#42;1^ “Raabe — são para ficar sentados quietos.”

[NOTE]
====
. “Esta”, hebr. fem.
====

[[v23-30-8]]

^<<v23-30-8,8>>^ “Agora, vem, escreve isso numa tábua, com eles, e inscreve-o até mesmo num livro, a fim de que sirva para um dia futuro, como testemunho^&#42;1^ por tempo indefinido.

[NOTE]
====
. “Como testemunho”, TSyVg; hebr.: la·‛ádh, “para sempre”.
====

[[v23-30-9]]

^<<v23-30-9,9>>^ Pois é um povo rebelde, filhos inverídicos, filhos que não quiseram ouvir a lei de Jeová;

[[v23-30-10]]

^<<v23-30-10,10>>^ que disseram aos que vêem: ‘Não deveis ver’, e aos que têm visões: ‘Não deveis visionar para nós nenhumas coisas diretas. Falai-nos coisas macias;^&#42;1^ visionai coisas enganosas.

[NOTE]
====
. Ou “bem-vindas; lisonjeiras”.
====

[[v23-30-11]]

^<<v23-30-11,11>>^ Desviai-vos do caminho; apartai-vos da vereda. Fazei o Santo de Israel cessar só por causa de nós.’”

[[v23-30-12]]

^<<v23-30-12,12>>^ Portanto, assim disse o Santo de Israel: “Visto que rejeitastes esta palavra e [visto que] confiais na defraudação, e no que é sinuoso, e vos estribais nisso,

[[v23-30-13]]

^<<v23-30-13,13>>^ por isso se tornará este erro para vós como um setor arrombado, prestes a cair, um bojo numa muralha muito elevada, cujo desmoronamento pode vir repentinamente, num instante.

[[v23-30-14]]

^<<v23-30-14,14>>^ Certamente se desmoronará assim como na quebra duma grande talha dos oleiros, esmiuçada sem dó, de modo que não se pode achar entre os seus destroços nenhum caco para retirar fogo da lareira ou para escumar a água dum charco.”^&#42;1^

[NOTE]
====
. “Para escumar a água dum charco.” Veja VT, Vol. VII, 1957, pp. 203-207.
====

[[v23-30-15]]

^<<v23-30-15,15>>^ Pois assim disse o Soberano Senhor Jeová, o Santo de Israel: “Por retornardes e descansardes, sereis salvos. Vossa potência se mostrará em simplesmente ficardes sossegados e confiantes.” Mas, vós não quisestes.

[[v23-30-16]]

^<<v23-30-16,16>>^ E passastes a dizer: “Não, mas fugiremos em cavalos!” Por isso é que fugireis. “E montaremos [cavalos] ligeiros!” Por isso é que se mostrarão ligeiros os que vos perseguem.

[[v23-30-17]]

^<<v23-30-17,17>>^ Mil tremerão^&#42;1^ por causa da censura de um só; por causa da censura de cinco fugireis até sobrardes tal qual um mastro no cume dum monte e como um sinal de aviso^&#42;2^ num morro.

[NOTE]
====
. “Mil tremerão”, mediante uma correção; M: “Mil, um”.
. “E como um sinal de aviso.” Hebr.: wekhan·nés.
====

[[v23-30-18]]

^<<v23-30-18,18>>^ E por isso Jeová ficará à espera para mostrar-vos favor e por isso ele se erguerá para ter misericórdia convosco. Porque Jeová é Deus de julgamento.^&#42;1^ Felizes todos os que ficam à espera dele.

[NOTE]
====
. “Deus de julgamento.” Hebr.: ’Elo·héh mish·pát.
====

[[v23-30-19]]

^<<v23-30-19,19>>^ Quando o próprio povo em Sião morar em Jerusalém, tu^&#42;1^ de modo algum chorarás. Sem falta ele^&#42;2^ te mostrará favor ao som do teu clamor; assim que ele o ouvir, realmente te responderá.

[NOTE]
====
. “Tu”, hebr. masc. sing.
. “Ele”, MTVg; 1QIsa: “Jeová”.
====

[[v23-30-20]]

^<<v23-30-20,20>>^ E Jeová^&#42;1^ certamente vos dará pão em forma de aflição e água em forma de opressão; contudo, teu Grandioso Instrutor^&#42;2^ não mais se esconderá, e teus olhos terão de tornar-se [olhos] que vêem o teu Grandioso Instrutor.

[NOTE]
====
. Uma das 134 mudanças de YHWH para ’Adho·naí feitas pelos escribas. Veja Ap. 1B.
. “Teu Grandioso Instrutor.” Lit.: “teus instrutores”. Hebr.: Moh·reí·kha, pl. para denotar grandiosidade ou excelência, e por isso tem um verbo no sing.
====

[[v23-30-21]]

^<<v23-30-21,21>>^ E teus próprios ouvidos ouvirão atrás de ti uma palavra, dizendo: “Este é o caminho. Andai nele”, caso vades para a direita ou caso vades para a esquerda.

[[v23-30-22]]

^<<v23-30-22,22>>^ E tereis^&#42;1^ de aviltar o revestimento de tuas^&#42;2^ imagens entalhadas de prata e a cobertura bem ajustada de tua estátua fundida de ouro. Tu as espalharás. Assim como a mulher menstruada, dir-lhe-ás: “Mera sujeira!”

[NOTE]
====
. “Tereis”, MTSy; LXXVg: “Terás”.
. “Tuas”, hebr. sing., referindo-se à de cada um, MVg; TSy: “vossas”, pl.
====

[[v23-30-23]]

^<<v23-30-23,23>>^ E ele certamente dará a chuva para a tua semente com que semeias o solo e pão como produto do solo, que terá de tornar-se pingue e oleoso. Teu gado pastará naquele dia num pasto amplo.

[[v23-30-24]]

^<<v23-30-24,24>>^ E o gado vacum e os jumentos adultos que lavram o solo comerão forragem temperada com azeda, joeirada com a pá e com o forcado.

[[v23-30-25]]

^<<v23-30-25,25>>^ E em cada monte alto e em cada morro elevado terá de vir a haver correntes, valas de água, no dia da grande chacina, quando as torres caírem.

[[v23-30-26]]

^<<v23-30-26,26>>^ E a luz da lua cheia terá de tornar-se como a luz do [sol] brilhante; e a própria luz do [sol] brilhante se tornará sete vezes maior, como a luz de sete dias, no dia em que Jeová pensa o quebrantamento do seu povo e sara mesmo o ferimento sério causado pelo golpe dado por ele.

[[v23-30-27]]

^<<v23-30-27,27>>^ Eis que o nome de Jeová está vindo de longe, ardendo com a sua ira e com pesadas nuvens. Quanto aos seus lábios, ficaram cheios de verberação, e sua língua é como um fogo devorador.

[[v23-30-28]]

^<<v23-30-28,28>>^ E seu espírito^&#42;1^ é como uma torrente inundante que chega até o pescoço, para sacudir as nações para lá e para cá com uma peneira de futilidade; e um freio, que faz vaguear, estará na queixada dos povos.

[NOTE]
====
. “E seu espírito (fôlego).” Hebr.: weru·hhóh; gr.: pneú·ma; lat.: spí·ri·tus.
====

[[v23-30-29]]

^<<v23-30-29,29>>^ Vireis a ter uma canção igual à da noite em que a pessoa se santifica para uma festividade, e alegria de coração igual à de alguém andando com uma flauta para entrar no monte de Jeová, até a Rocha^&#42;1^ de Israel.

[NOTE]
====
. “Rocha de.” Hebr.: Tsur; TSy: “o Poderoso”; LXX: “o Deus”; Vg: “o Forte”.
====

[[v23-30-30]]

^<<v23-30-30,30>>^ E Jeová certamente fará ouvir a dignidade de sua voz e fará ver a descida do seu braço, na fúria da ira e na chama dum fogo devorador, [e] na pancada de chuva, e no temporal, e nas pedras de saraiva.

[[v23-30-31]]

^<<v23-30-31,31>>^ Pois, por causa da voz de Jeová, a Assíria ficará aterrorizada; ele [a] golpeará até com uma vara.

[[v23-30-32]]

^<<v23-30-32,32>>^ E cada batida do seu bastão de castigo,^&#42;1^ que Jeová fará descer sobre [a Assíria], certamente mostrará ser com pandeiros e com harpas; e lutará realmente contra eles com batalhas de brandimento^&#42;2^ [de armas].

[NOTE]
====
. “Castigo”, mediante uma ligeira correção; M: “alicerce”.
. “Com procissões da oferta movida”, mediante uma ligeira correção.
====

[[v23-30-33]]

^<<v23-30-33,33>>^ Pois o seu Tofete^&#42;1^ está posto em ordem desde tempos recentes; está também preparado para o próprio rei. Ele fez profunda a sua pilha [de lenha]. Há fogo e lenha em abundância. O sopro^&#42;2^ de Jeová arde contra ele como uma torrente de enxofre.

[NOTE]
====
. “Seu Tofete”, mediante sinais vocálicos diferentes; M: “Tofté”.
. “Sopro de.” Hebr.: nish·máth; em Gên 2:7: “fôlego”.
====

'''

xref:023-isaias/023-isaias-029.adoc#v23-29-0[&#60; Capítulo Anterior] | <<v23-30-0,Topo>> | xref:023-isaias/023-isaias-031.adoc#v23-31-0[Próximo Capítulo &#62;]