include::./index.adoc[]

[[v23-34-0]]
=== Isaías, 34
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v23-34-1]]

^<<v23-34-1,1>>^ Chegai-vos, nações, para ouvir; e prestai atenção, grupos nacionais. Escute a terra e aquilo que a enche, o solo produtivo^&#42;1^ e todo o seu produto.

[NOTE]
====
. Veja 13:11 n.: “produtivo”.
====

[[v23-34-2]]

^<<v23-34-2,2>>^ Porque Jeová tem indignação contra todas as nações e furor contra todo o seu exército. Ele terá de devotá-las à destruição; terá de entregá-las ao abate.

[[v23-34-3]]

^<<v23-34-3,3>>^ E seus mortos serão lançados fora; e quanto aos seus cadáveres, ascenderá o seu mau cheiro; e os montes terão de derreter-se por causa do sangue deles.

[[v23-34-4]]

^<<v23-34-4,4>>^ E todos os do exército dos céus terão de apodrecer. E os céus terão de ser enrolados, como o rolo dum livro; e todo o seu exército terá de engelhar-se, assim como se engelha a folhagem [caindo] da videira e como [o figo] engelhado da figueira.

[[v23-34-5]]

^<<v23-34-5,5>>^ “Pois a minha espada certamente ficará encharcada nos céus. Eis que descerá sobre Edom e sobre o povo que em justiça devotei à destruição.

[[v23-34-6]]

^<<v23-34-6,6>>^ Jeová tem uma espada; terá de ficar cheia de sangue; terá de ficar untada de gordura, do sangue de carneirinhos e de cabritos, da gordura dos rins de carneiros. Porque Jeová tem um sacrifício em Bozra e um grande abate na terra de Edom.

[[v23-34-7]]

^<<v23-34-7,7>>^ E os touros selvagens terão de descer com eles, e os novilhos, com os poderosos; e sua terra terá de ser encharcada com sangue e o próprio pó deles ficará untado de gordura.”

[[v23-34-8]]

^<<v23-34-8,8>>^ Porque Jeová tem um dia de vingança, um ano de retribuições pela causa jurídica relativa a Sião.

[[v23-34-9]]

^<<v23-34-9,9>>^ E as torrentes dela^&#42;1^ terão de transformar-se em piche e seu pó em enxofre; e sua terra terá de tornar-se como piche ardente.

[NOTE]
====
. “Dela”, referindo-se a Bozra, capital de Edom.
====

[[v23-34-10]]

^<<v23-34-10,10>>^ Não se apagará nem de noite nem de dia; sua fumaça continuará a ascender por tempo indefinido. De geração em geração será abrasada; nunca jamais passará alguém por ela.

[[v23-34-11]]

^<<v23-34-11,11>>^ E o pelicano e o porco-espinho terão de tomar posse dela, e os próprios mochos-orelhudos e os corvos residirão nela; e ele terá de estender sobre ela o cordel de medir do vácuo e as pedras do vazio.

[[v23-34-12]]

^<<v23-34-12,12>>^ Seus nobres — não há ali nenhuns chamados ao próprio reinado, e os próprios príncipes dela tornar-se-ão todos em nada.

[[v23-34-13]]

^<<v23-34-13,13>>^ Espinhos terão de subir nas suas torres de habitação, urtigas e plantas espinhosas, nas suas praças fortes; e ela terá de tornar-se lugar de permanência de chacais, pátio para avestruzes.^&#42;1^

[NOTE]
====
. Veja 13:21 n.: “avestruzes”.
====

[[v23-34-14]]

^<<v23-34-14,14>>^ E os freqüentadores de regiões áridas terão de encontrar-se com animais uivantes, e até mesmo o demônio caprino chamará o seu companheiro. Sim, ali o curiango^&#42;1^ certamente ficará em repouso e achará para si um lugar de descanso.

[NOTE]
====
. Hebr.: li·líth; provavelmente uma ave noturna.
====

[[v23-34-15]]

^<<v23-34-15,15>>^ Ali a cobra-cuspideira fez o seu ninho e bota [ovos], e ela terá de chocá-los e ajuntá-los sob a sua sombra. Sim, ali se terão de reunir [as fêmeas dos] miotos, cada uma com seu companheiro.

[[v23-34-16]]

^<<v23-34-16,16>>^ Buscai vós mesmos no livro de Jeová e lede em voz alta: nenhuma delas tem faltado; realmente, não deixam de ter cada uma delas seu companheiro, pois foi a boca de Jeová^&#42;1^ que deu a ordem e foi o seu espírito que as reuniu.

[NOTE]
====
. “A boca de Jeová”, cinco mss. hebr.; 1QIsaSy: “sua boca”; LXX e árabe: “Jeová”; MVg: “minha boca”. Veja notas de BHK e BHS; veja também Ap. 1A.
====

[[v23-34-17]]

^<<v23-34-17,17>>^ E foi Ele quem lançou para elas a sorte, e sua própria mão lhes repartiu o lugar^&#42;1^ com o cordel de medir. Tomarão posse dele por tempo indefinido; residirão nele de geração em geração.

[NOTE]
====
. Lit.: “ela”. Ou “isso”. Isto é, um lugar, tal como Bozra.
====

'''

xref:023-isaias/023-isaias-033.adoc#v23-33-0[&#60; Capítulo Anterior] | <<v23-34-0,Topo>> | xref:023-isaias/023-isaias-035.adoc#v23-35-0[Próximo Capítulo &#62;]