include::./index.adoc[]

[[v23-23-0]]
=== Isaías, 23
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v23-23-1]]

^<<v23-23-1,1>>^ A pronúncia de Tiro:^&#42;1^ Uivai, navios de Társis, porque foi assolada [para não ser] porto,^&#42;2^ [para não ser lugar] em que se entre. Isto lhes foi revelado desde a terra de Quitim.^&#42;3^

[NOTE]
====
. Significando “Rocha”. Hebr.: Tsor.
. Lit.: “casa”.
. Ou “dos cipriotas”.
====

[[v23-23-2]]

^<<v23-23-2,2>>^ Ficai quietos, ó habitantes do litoral.^&#42;1^ Os mercadores de Sídon, os que cruzam o mar — eles te encheram.

[NOTE]
====
. Ou “ilha”.
====

[[v23-23-3]]

^<<v23-23-3,3>>^ A semente de Sior, a colheita do Nilo, a renda dela, tem estado sobre muitas águas; e veio a ser o ganho das nações.

[[v23-23-4]]

^<<v23-23-4,4>>^ Envergonha-te, ó Sídon; porque o mar, ó tu baluarte do mar, disse: “Não tive dores de parto e não dei à luz, nem criei jovens, nem eduquei virgens.”

[[v23-23-5]]

^<<v23-23-5,5>>^ Assim como diante da notícia referente ao Egito, as pessoas terão igualmente dores agudas diante da notícia sobre Tiro.

[[v23-23-6]]

^<<v23-23-6,6>>^ Atravessai para Társis; uivai, ó habitantes do litoral.

[[v23-23-7]]

^<<v23-23-7,7>>^ É esta a vossa [cidade] que rejubilava desde os dias de outrora, [desde] os seus tempos primitivos? Seus pés costumavam levá-la longe para residir como forasteira.

[[v23-23-8]]

^<<v23-23-8,8>>^ Quem é que deu este conselho contra Tiro, a coroadora, cujos mercadores eram príncipes, cujos comerciantes eram os honrados da terra?

[[v23-23-9]]

^<<v23-23-9,9>>^ O próprio Jeová dos exércitos deu este conselho, para profanar o orgulho de toda a beleza, para tratar com desprezo todos os honrados da terra.

[[v23-23-10]]

^<<v23-23-10,10>>^ Atravessa a tua terra como o rio Nilo, ó filha de Társis. Não há mais estaleiro.

[[v23-23-11]]

^<<v23-23-11,11>>^ Ele estendeu a sua mão sobre o mar; fez os reinos ficar agitados. O próprio Jeová deu ordem contra a Fenícia,^&#42;1^ para aniquilar os seus baluartes.

[NOTE]
====
. Lit.: “Canaã”; ou: “terra de mercadores”. Veja Gên 10:15; 1Cr 1:13.
====

[[v23-23-12]]

^<<v23-23-12,12>>^ E ele diz: “Nunca mais deves rejubilar, ó oprimida, filha virgem de Sídon. Levanta-te, atravessa para a própria Quitim. Nem ali será de descanso para ti.”

[[v23-23-13]]

^<<v23-23-13,13>>^ Eis a terra dos caldeus! Este é o povo — a Assíria não [o] mostrou ser — fundaram-na para os freqüentadores do deserto. Erigiram suas torres de sítio; esvaziaram as torres de habitação dela; ela foi constituída em ruína desmoronada.

[[v23-23-14]]

^<<v23-23-14,14>>^ Uivai, navios de Társis, pois o vosso baluarte foi assolado.

[[v23-23-15]]

^<<v23-23-15,15>>^ E naquele dia terá de acontecer que Tiro terá de ser esquecida por setenta anos, igual aos dias de um só rei. Ao fim de setenta anos acontecerá a Tiro assim como no cântico de uma prostituta:^&#42;1^

[NOTE]
====
. Ou “meretriz”.
====

[[v23-23-16]]

^<<v23-23-16,16>>^ “Toma uma harpa, faze a ronda da cidade, ó prostituta esquecida. Toca o melhor possível nas cordas; faze muitas as tuas canções, a fim de que sejas lembrada.”

[[v23-23-17]]

^<<v23-23-17,17>>^ E ao fim de setenta anos terá de acontecer que Jeová voltará a sua atenção para Tiro, e ela terá de retornar à sua paga e cometer prostituição com todos os reinos da terra sobre a superfície do solo.

[[v23-23-18]]

^<<v23-23-18,18>>^ E seu ganho e sua paga terão de tornar-se algo sagrado para Jeová. Não será armazenada nem acumulada, porque a sua paga virá a ser para os que moram diante de Jeová, para que se coma até à saciedade e para cobertura elegante.

'''

xref:023-isaias/023-isaias-022.adoc#v23-22-0[&#60; Capítulo Anterior] | <<v23-23-0,Topo>> | xref:023-isaias/023-isaias-024.adoc#v23-24-0[Próximo Capítulo &#62;]