include::./index.adoc[]

[[v23-22-0]]
=== Isaías, 22
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v23-22-1]]

^<<v23-22-1,1>>^ A pronúncia do vale da visão:^&#42;1^ Que é que há contigo^&#42;2^ agora, que subiste na tua inteireza aos terraços?

[NOTE]
====
. “Da visão”, MVg; LXX: “Sião”.
. “Contigo”, hebr. fem., dirigido à “cidade”, hebr. fem., no v. 2.
====

[[v23-22-2]]

^<<v23-22-2,2>>^ Estiveste cheia de alarido, uma cidade turbulenta, uma vila rejubilante. Os teus que foram mortos não são os que foram mortos à espada, nem os mortos em batalha.

[[v23-22-3]]

^<<v23-22-3,3>>^ Todos os próprios ditadores teus fugiram de uma só vez. Foram tomados prisioneiros sem [necessidade de] um arco. Todos os teus que se acharam foram tomados juntamente prisioneiros. Tinham fugido para longe.

[[v23-22-4]]

^<<v23-22-4,4>>^ Por isso é que eu disse: “Desviai de mim o vosso olhar. Vou mostrar amargura em choro. Não insistais em consolar-me pela assolação da filha do meu povo.

[[v23-22-5]]

^<<v23-22-5,5>>^ Pois é o dia de confusão, e de calcadura, e de consternação, que o Soberano Senhor, Jeová dos exércitos, tem no vale da visão.^&#42;1^ Há o demolidor do muro e o grito^&#42;2^ ao monte.

[NOTE]
====
. “Da visão”, MVg; LXX: “Sião”.
. “Grito”, quer um grito por ajuda, quer um grito de guerra.
====

[[v23-22-6]]

^<<v23-22-6,6>>^ E o próprio Elão levantou a aljava no carro de guerra do homem terreno, [com] corcéis; e o próprio Quir expôs o escudo.

[[v23-22-7]]

^<<v23-22-7,7>>^ E acontecerá que as mais seletas das tuas^&#42;1^ baixadas terão de ficar cheias de carros de guerra, e os próprios corcéis, sem falta, terão de colocar-se em posição junto ao portão,

[NOTE]
====
. “Tuas”, hebr. fem. sing., referindo-se à “filha do meu povo” no v. 4.
====

[[v23-22-8]]

^<<v23-22-8,8>>^ e remover-se-á o reposteiro de Judá. E naquele dia olharás para a armaria da casa da floresta,

[[v23-22-9]]

^<<v23-22-9,9>>^ e vós haveis de ver as próprias brechas da Cidade de Davi, pois serão deveras muitas. E apanhareis as águas do reservatório inferior.

[[v23-22-10]]

^<<v23-22-10,10>>^ E contareis realmente as casas de Jerusalém. Também demolireis as casas para fazer a muralha inexpugnável.

[[v23-22-11]]

^<<v23-22-11,11>>^ E haverá um açude que tereis de fazer entre as duas muralhas para as águas do reservatório antigo. E certamente não olhareis para o grandioso que o fez, e certamente não vereis aquele que o formou há muito.

[[v23-22-12]]

^<<v23-22-12,12>>^ “E o Soberano Senhor, Jeová dos exércitos, convocará naquele dia ao choro, e ao lamento, e à calvície, e ao cingimento de serapilheira.

[[v23-22-13]]

^<<v23-22-13,13>>^ Mas, eis que há exultação e alegria, a matança de gado vacum e o abate de ovelhas, o consumo de carne e o beber de vinho: ‘Comamos e bebamos, pois amanhã morreremos.’”

[[v23-22-14]]

^<<v23-22-14,14>>^ E Jeová dos exércitos revelou-se aos meus ouvidos: “‘Este erro não será expiado a vosso favor, até que morrais’, disse o Soberano Senhor, Jeová dos exércitos.”

[[v23-22-15]]

^<<v23-22-15,15>>^ Assim disse o Soberano Senhor, Jeová dos exércitos: “Vai, entra até este mordomo,^&#42;1^ até Sebna, que está sobre a casa:

[NOTE]
====
. “Este mordomo.” Hebr.: has·so·khén haz·zéh.
====

[[v23-22-16]]

^<<v23-22-16,16>>^ ‘Que é que te interessa aqui e quem é que te interessa aqui, que aqui escavaste para ti uma sepultura?’ Está escavando sua sepultura numa elevação; num rochedo está talhando para si um domicílio.

[[v23-22-17]]

^<<v23-22-17,17>>^ ‘Eis que Jeová te está arremessando para baixo com um arremesso violento, ó varão vigoroso, e te agarrará à força.

[[v23-22-18]]

^<<v23-22-18,18>>^ Sem falta te enrolará bem apertado,^&#42;1^ como uma bola para uma terra ampla.^&#42;2^ Ali morrerás, e ali os carros da tua glória serão a desonra da casa de teu amo.^&#42;3^

[NOTE]
====
. Lit.: “[com] enrolamento (enroscamento)”.
. Lit.: “terra ampla em ambos os lados (mãos)”.
. “Teu amo.” Hebr.: ’adho·neí·kha, pl. de ’a·dhóhn, para denotar excelência.
====

[[v23-22-19]]

^<<v23-22-19,19>>^ E eu vou empurrar-te do teu posto;^&#42;1^ e derrubar-te-ão da tua posição oficial.^&#42;2^

[NOTE]
====
. Ou “cargo”.
. Ou “tua função”.
====

[[v23-22-20]]

^<<v23-22-20,20>>^ “‘E naquele dia terá de acontecer que irei chamar meu servo,^&#42;1^ a saber, Eliaquim, filho de Hilquias.^&#42;2^

[NOTE]
====
. Lit.: “para meu servo”. Hebr.: le‛av·dí; lat.: sér·vum mé·um.
. Significando “Meu Quinhão É Jeová”. Hebr.: Hhil·qi·yá·hu.
====

[[v23-22-21]]

^<<v23-22-21,21>>^ E vou vesti-lo com a tua veste comprida, e atar firmemente em volta dele a tua faixa, e entregarei teu domínio^&#42;1^ na mão dele; e ele terá de tornar-se pai para o habitante de Jerusalém e para a casa de Judá.

[NOTE]
====
. “E . . . teu domínio.” Hebr.: u·mem·shel·tekhá; gr.: oi·ko·no·mí·an sou, “tua mordomia (cargo de mordomo)”.
====

[[v23-22-22]]

^<<v23-22-22,22>>^ E eu vou pôr a chave da casa de Davi sobre o seu ombro, e ele terá de abrir sem que alguém feche e terá de fechar sem que alguém abra.

[[v23-22-23]]

^<<v23-22-23,23>>^ E vou pregá-lo como tarugo num lugar duradouro, e ele terá de tornar-se como trono de glória para a casa de seu pai.

[[v23-22-24]]

^<<v23-22-24,24>>^ E terão de pendurar nele toda a glória da casa de seu pai, os descendentes e a prole, todos os vasos do tipo pequeno, os vasos do tipo tigela bem como todos os vasos das grandes talhas.

[[v23-22-25]]

^<<v23-22-25,25>>^ “‘Naquele dia’, é a pronunciação de Jeová dos exércitos, ‘o tarugo pregado num lugar duradouro será removido, e terá de ser cortado e terá de cair, e a carga que há sobre ele terá de ser decepada, pois o próprio Jeová falou [isso].’”

'''

xref:023-isaias/023-isaias-021.adoc#v23-21-0[&#60; Capítulo Anterior] | <<v23-22-0,Topo>> | xref:023-isaias/023-isaias-023.adoc#v23-23-0[Próximo Capítulo &#62;]