include::./index.adoc[]

[[v23-29-0]]
=== Isaías, 29
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v23-29-1]]

^<<v23-29-1,1>>^ “Ai de Ariel,^&#42;1^ de Ariel, a vila onde Davi se acampou! Acrescentai ano a ano; deixai as festividades correr o ciclo.

[NOTE]
====
. Possivelmente significando “A Lareira do Altar de Deus”; ou: “O Leão de Deus”, referindo-se a Jerusalém.
====

[[v23-29-2]]

^<<v23-29-2,2>>^ E terei de fazer as coisas apertadas para Ariel, e terá de chegar a haver luto e lamentação, e ela terá de tornar-se para mim como a lareira do altar de Deus.^&#42;1^

[NOTE]
====
. Ou “como Ariel”.
====

[[v23-29-3]]

^<<v23-29-3,3>>^ E terei de acampar-me contra ti^&#42;1^ em todos os lados, e terei de sitiar-te com uma paliçada^&#42;2^ e erigir contra ti obras de sítio.

[NOTE]
====
. “Ti”, hebr. fem. sing., referindo-se à vila.
. Ou “sentinelas; postos avançados”.
====

[[v23-29-4]]

^<<v23-29-4,4>>^ E terás de ficar rebaixada de modo que falarás desde a própria terra, e tua declaração soará baixo, como que do pó. E tua voz terá de tornar-se como [a de] um médium espírita, da própria terra, e tua própria declaração chilrará desde o pó.

[[v23-29-5]]

^<<v23-29-5,5>>^ E a massa de gente dos que te são estranhos terá de tornar-se como a poeira fina, e a massa dos tiranos, igual ao restolho que passa. E terá de acontecer num instante, repentinamente.

[[v23-29-6]]

^<<v23-29-6,6>>^ Receberás atenção da parte de Jeová dos exércitos, com trovão e com tremor, e com um grande ruído, com tufão e tormenta, e com a chama dum fogo devorador.”

[[v23-29-7]]

^<<v23-29-7,7>>^ E terá de acontecer como num sonho, numa visão da noite, com respeito à massa de gente de todas as nações que travam guerra contra Ariel, sim, todos os que guerreiam contra ela, e as torres de cerco contra ela e os que fazem as coisas apertadas para ela.

[[v23-29-8]]

^<<v23-29-8,8>>^ Sim, terá de acontecer como quando um faminto sonha, e eis que está comendo, e ele na realidade acorda e sua alma está vazia; e como quando um sedento sonha, e eis que está bebendo, e ele na realidade acorda, e eis que está cansado e sua alma está ressequida; assim acontecerá com a massa de gente de todas as nações que travam guerra contra o monte Sião.

[[v23-29-9]]

^<<v23-29-9,9>>^ Demorai-vos, e ficai pasmados; cegai-vos, e ficai cegos.^&#42;1^ Ficaram embriagados, mas não de vinho; cambalearam, mas não por causa de bebida inebriante.

[NOTE]
====
. Lit.: “besuntai-vos e sede besuntados”. Veja 6:10: “gruda os próprios olhos deles”.
====

[[v23-29-10]]

^<<v23-29-10,10>>^ Pois Jeová tem derramado sobre vós um espírito de profundo sono; e ele fecha os vossos olhos, os profetas, e encobriu até mesmo as vossas cabeças, os visionários.

[[v23-29-11]]

^<<v23-29-11,11>>^ E para vós, a visão de tudo torna-se igual às palavras do livro que foi selado, que se entrega a alguém que sabe escrever, dizendo: “Lê isto em voz alta, por favor”, e ele tem de dizer: “Não posso, pois está selado”;

[[v23-29-12]]

^<<v23-29-12,12>>^ e o livro tem de ser dado a alguém que não conhece a escrita, dizendo-se: “Lê isto em voz alta, por favor”, e ele tem de dizer: “Não sei nada de escrita.”

[[v23-29-13]]

^<<v23-29-13,13>>^ E Jeová^&#42;1^ diz: “Visto que este povo se aproxima com a sua boca, e eles me glorificaram apenas com os seus lábios e removeram seu próprio coração para longe de mim, e seu temor para comigo se torna mandamento de homens, que está sendo ensinado,

[NOTE]
====
. Uma das 134 mudanças de YHWH para ’Adho·naí feitas pelos escribas. Veja Ap. 1B.
====

[[v23-29-14]]

^<<v23-29-14,14>>^ por isso, eis-me aqui, Aquele que de novo agirá maravilhosamente com este povo, dum modo maravilhoso e com algo maravilhoso; e terá de perecer a sabedoria dos seus sábios e se esconderá a própria compreensão dos seus homens discretos.”

[[v23-29-15]]

^<<v23-29-15,15>>^ Ai dos que se aprofundam muito em esconder o conselho diante do próprio Jeová, e cujos atos ocorreram num lugar escuro, ao passo que dizem: “Quem é que nos vê e quem é que sabe de nós?”

[[v23-29-16]]

^<<v23-29-16,16>>^ A perversidade de vós, homens! Deve o próprio oleiro^&#42;1^ ser considerado igual ao barro? Acaso deve a coisa feita dizer referente àquele que a fez: “Ele não me fez”? E acaso a própria coisa formada diz realmente referente àquele que a formou: “Ele não mostrou entendimento”?

[NOTE]
====
. Lit.: “aquele que forma; o moldador”.
====

[[v23-29-17]]

^<<v23-29-17,17>>^ Não é somente mais um pouquinho e o Líbano terá de ser tornado em pomar, e o próprio pomar será considerado como floresta?

[[v23-29-18]]

^<<v23-29-18,18>>^ E naquele dia os surdos hão de ouvir as palavras do livro, e dentre as trevas e dentre a escuridão até mesmo os olhos dos cegos verão.

[[v23-29-19]]

^<<v23-29-19,19>>^ E os mansos certamente incrementarão a sua alegria no próprio Jeová e até mesmo os pobres da humanidade^&#42;1^ jubilarão no próprio Santo de Israel,

[NOTE]
====
. Ou “homem terreno”. Hebr.: ’a·dhám.
====

[[v23-29-20]]

^<<v23-29-20,20>>^ porque o tirano terá de chegar ao seu fim e o fanfarrão terá de acabar, e todos os que se mantêm alerta para causar dano terão de ser decepados,

[[v23-29-21]]

^<<v23-29-21,21>>^ os que levam o homem ao pecado pela [sua] palavra, e os que põem engodo mesmo para aquele que repreende no portão, e os que repelem o justo com argumentos vãos.

[[v23-29-22]]

^<<v23-29-22,22>>^ Portanto, assim disse Jeová à casa de Jacó, aquele que remiu a Abraão: “Jacó não se envergonhará agora, nem empalidecerá agora a sua própria face;

[[v23-29-23]]

^<<v23-29-23,23>>^ pois, ao ver ele os seus filhos, trabalho das minhas mãos, no meio dele, santificarão^&#42;1^ o meu nome e certamente santificarão o Santo de Jacó, e considerarão ao Deus de Israel^&#42;2^ com susto.

[NOTE]
====
. “Santificarão.” Hebr.: yaq·dí·shu; gr.: ha·gi·á·sou·sin; lat.: sanc·ti·fi·cán·tes.
. “Deus de Israel.” Hebr.: ’Elo·héh Yis·ra·’él.
====

[[v23-29-24]]

^<<v23-29-24,24>>^ E os que erram no [seu] espírito chegarão realmente a conhecer a compreensão e os que murmuram aprenderão a instrução.”

'''

xref:023-isaias/023-isaias-028.adoc#v23-28-0[&#60; Capítulo Anterior] | <<v23-29-0,Topo>> | xref:023-isaias/023-isaias-030.adoc#v23-30-0[Próximo Capítulo &#62;]