include::./index.adoc[]

[[v23-57-0]]
=== Isaías, 57
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v23-57-1]]

^<<v23-57-1,1>>^ O próprio justo pereceu, mas não há quem fixe [isso] no coração. E homens de benevolência^&#42;1^ estão sendo recolhidos [aos mortos], ao passo que ninguém discerne que é por causa da calamidade que o justo foi recolhido.

[NOTE]
====
. Ou “amor leal”.
====

[[v23-57-2]]

^<<v23-57-2,2>>^ Ele entra na paz; eles descansam sobre as suas camas, [todo] aquele que anda de modo direito.

[[v23-57-3]]

^<<v23-57-3,3>>^ “Quanto a vós, chegai-vos para cá, vós filhos duma agoureira, descendência duma pessoa adúltera e duma mulher que comete prostituição:

[[v23-57-4]]

^<<v23-57-4,4>>^ A respeito de quem vos divertis? Contra quem estais abrindo largamente a boca, estais estendendo a língua para fora? Não sois filhos da transgressão, descendência da falsidade,

[[v23-57-5]]

^<<v23-57-5,5>>^ os que excitam a paixão entre as grandes árvores, debaixo de cada árvore frondosa, chacinando os filhos nos vales de torrente, debaixo das fendas dos rochedos?

[[v23-57-6]]

^<<v23-57-6,6>>^ “Teu^&#42;1^ quinhão estava com as pedras lisas do vale de torrente. Elas é que eram a tua sorte. Ademais, foi a elas que derramaste uma oferta de bebida, ofertaste um presente. Por estas coisas, acaso devo consolar-me?

[NOTE]
====
. “Teu”, hebr. fem. sing., referindo-se a Sião ou Jerusalém.
====

[[v23-57-7]]

^<<v23-57-7,7>>^ Colocaste a tua cama sobre um monte alto e elevado. Subiste também para lá a fim de oferecer sacrifícios.

[[v23-57-8]]

^<<v23-57-8,8>>^ E colocaste a tua recordação^&#42;1^ atrás da porta e da ombreira. Pois [te] descobriste à parte de mim e passaste a subir; ampliaste a tua cama. E tu, para ti mesma, foste concluir com eles [um pacto]. Amaste a cama com eles. Contemplaste o membro masculino.^&#42;2^

[NOTE]
====
. “A tua recordação”, M(hebr.: zikh·roh·nékh)LXXSyVg; T: “recordação de teus ídolos”. Alguns derivam a palavra hebr. aqui de za·khár, “varão”, e entendem zikh·roh·nékh como significando um símbolo fálico.
. “O membro masculino.” Lit.: “mão”. Hebr.: yadh.
====

[[v23-57-9]]

^<<v23-57-9,9>>^ E passaste a descer a Meleque^&#42;1^ com óleo e continuaste a fazer abundantes os teus ungüentos. E continuaste a mandar teus enviados para longe, de modo que rebaixaste as coisas até o Seol.

[NOTE]
====
. Ou “ao rei”.
====

[[v23-57-10]]

^<<v23-57-10,10>>^ Labutaste na multidão dos teus caminhos. Não disseste: ‘É sem esperança!’ Encontraste a reanimação do teu próprio poder.^&#42;1^ Por isso é que não ficaste doente.

[NOTE]
====
. Lit.: “mão”.
====

[[v23-57-11]]

^<<v23-57-11,11>>^ “De quem ficaste^&#42;1^ receosa e [a quem] começaste a temer, de modo que passaste a mentir? Mas, de mim é que não te lembraste. Não fixaste nada no coração. Não estava eu ficando quieto e ocultando as coisas?^&#42;2^ Portanto, de mim é que não tiveste medo.

[NOTE]
====
. “Ficaste”, hebr. fem. sing., referindo-se a Sião ou Jerusalém.
. “E ocultando as coisas”, mediante um ajuste dos sinais vocálicos; M: “mesmo de há muito tempo”.
====

[[v23-57-12]]

^<<v23-57-12,12>>^ Eu mesmo é que contarei a tua justiça e os teus trabalhos, que eles não te aproveitarão.

[[v23-57-13]]

^<<v23-57-13,13>>^ Quando clamares por socorro, a tua coleção de coisas^&#42;1^ não te livrará, mas um vento^&#42;2^ carregará mesmo com todas elas. Uma exalação as levará embora, mas aquele que se refugiar em mim herdará a terra e tomará posse do meu santo monte.

[NOTE]
====
. Evidentemente: “massas (de ídolos)”, BDB, p. 868.
. “Vento.” Hebr.: rú·ahh; gr.: á·ne·mos; lat.: vén·tus.
====

[[v23-57-14]]

^<<v23-57-14,14>>^ E certamente se dirá:^&#42;1^ ‘Aterrai, aterrai! Desobstruí o caminho. Removei todo obstáculo do caminho do meu povo.’”

[NOTE]
====
. “E dirão”, LXXSy; Vg: “E direi.”
====

[[v23-57-15]]

^<<v23-57-15,15>>^ Pois assim disse o Enaltecido e Elevado, que reside para todo o sempre e cujo nome é santo: “No alto e no lugar santo é onde resido, também com o quebrantado e o humilde no espírito,^&#42;1^ para reavivar o espírito dos humildes e para reavivar o coração dos que estão sendo esmigalhados.

[NOTE]
====
. “Espírito.” Hebr.: rú·ahh.
====

[[v23-57-16]]

^<<v23-57-16,16>>^ Pois não contenderei por tempo indefinido, nem ficarei indignado perpetuamente; pois, por minha causa o próprio espírito se debilitaria, até mesmo as criaturas que respiram,^&#42;1^ que eu mesmo fiz.

[NOTE]
====
. Lit.: “os fôlegos”. Veja Sal 150:6 n.: “respira”.
====

[[v23-57-17]]

^<<v23-57-17,17>>^ “Fiquei indignado com o erro do seu lucro injusto e passei a golpeá-lo, escondendo [o meu rosto] enquanto eu estava indignado. Mas ele continuou a andar como renegado no caminho do seu coração.

[[v23-57-18]]

^<<v23-57-18,18>>^ Vi os próprios caminhos dele; e comecei a sará-lo, e a guiá-lo, e a compensá-lo com consolação para ele e para os seus pranteadores.”

[[v23-57-19]]

^<<v23-57-19,19>>^ “Estou criando o fruto dos lábios. Haverá paz contínua^&#42;1^ para o que está longe e para o que está perto”, disse Jeová, “e vou sará-lo”.

[NOTE]
====
. Lit.: “Paz, paz.”
====

[[v23-57-20]]

^<<v23-57-20,20>>^ “Mas os iníquos são como o mar revolto, quando não pode sossegar, cujas águas lançam de si algas e lama.

[[v23-57-21]]

^<<v23-57-21,21>>^ Não há paz para os iníquos”, disse o meu Deus.^&#42;1^

[NOTE]
====
. “Meu Deus”, 1QIsaMTSyVg; LXXVgc: “Jeová Deus”; cerca de 50 mss. hebr.: “Jeová”.
====

'''

xref:023-isaias/023-isaias-056.adoc#v23-56-0[&#60; Capítulo Anterior] | <<v23-57-0,Topo>> | xref:023-isaias/023-isaias-058.adoc#v23-58-0[Próximo Capítulo &#62;]