include::./index.adoc[]

[[v23-43-0]]
=== Isaías, 43
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v23-43-1]]

^<<v23-43-1,1>>^ E agora, assim disse Jeová, teu Criador, ó Jacó, e teu Formador, ó Israel: “Não tenhas medo, porque eu te resgatei. Eu [te] chamei pelo teu nome. Tu és meu.

[[v23-43-2]]

^<<v23-43-2,2>>^ Se passares pelas águas, vou estar contigo; e pelos rios, eles não passarão por cima de ti. Se andares através do fogo, não ficarás chamuscado, nem te crestará a própria chama.

[[v23-43-3]]

^<<v23-43-3,3>>^ Porque eu sou Jeová, teu Deus,^&#42;1^ o Santo de Israel, teu Salvador. Dei o Egito como resgate por ti,^&#42;2^ a Etiópia^&#42;3^ e Sebá, em lugar de ti.

[NOTE]
====
. “Teu Deus.” Hebr.: ’Elo·heí·kha.
. Ou “preço de expiação por ti”. Lit.: “tua cobertura”. Hebr.: khof·rekhá.
. “Etiópia”, LXXVg; MTSy: “Cus”.
====

[[v23-43-4]]

^<<v23-43-4,4>>^ Devido ao fato de que tens sido precioso aos meus olhos, foste considerado honroso e eu mesmo te amei. Darei homens^&#42;1^ em lugar de ti e grupos nacionais em lugar da tua alma.

[NOTE]
====
. Lit.: “homem terreno”. Hebr.: ’a·dhám.
====

[[v23-43-5]]

^<<v23-43-5,5>>^ “Não tenhas medo, porque eu estou contigo. Do nascente trarei a tua descendência e do poente te reunirei.

[[v23-43-6]]

^<<v23-43-6,6>>^ Direi ao norte: ‘Entrega!’ e ao sul:^&#42;1^ ‘Não retenhas. Traze meus filhos de longe, e minhas filhas, da extremidade da terra,

[NOTE]
====
. Ou “e para Temã”. Hebr.: u·letheh·mán.
====

[[v23-43-7]]

^<<v23-43-7,7>>^ todo aquele que for chamado pelo meu nome e que eu criei para a minha glória, que eu formei, sim, que eu fiz.’

[[v23-43-8]]

^<<v23-43-8,8>>^ “Faze sair um povo cego, embora existam os próprios olhos, e os surdos, embora tenham ouvidos.

[[v23-43-9]]

^<<v23-43-9,9>>^ Sejam reunidas todas as nações^&#42;1^ num só lugar e sejam ajuntados os grupos nacionais. Quem dentre eles pode contar isso? Ou podem fazer-nos ouvir mesmo as primeiras coisas? Forneçam as suas testemunhas, para que sejam declarados justos, ou ouçam e digam: ‘É verdade!’”^&#42;2^

[NOTE]
====
. Em harmonia com TSy; MLXX: “Todas as nações reuniram-se.”
. “É verdade!” Lit.: “Verdade!” Hebr.: ’eméth.
====

[[v23-43-10]]

^<<v23-43-10,10>>^ “Vós sois as minhas testemunhas”,^&#42;1^ é a pronunciação de Jeová, “sim, meu servo^&#42;2^ a quem escolhi, para que saibais e tenhais fé em mim, e para que entendais que eu sou o Mesmo. Antes de mim não foi formado nenhum Deus^&#42;3^ e depois de mim continuou a não haver nenhum.^&#42;4^

[NOTE]
====
. “Vós sois as minhas testemunhas.” Hebr.: ’at·tém ‛e·dhaí, pl.; lat.: vos té·stes mé·i, pl.
. “Sim, meu servo”, M(hebr.: we‛av·dí, sing.)LXXVg; T(aram.): we‛av·dí meshi·hhá’, “sim, meu servo, o ungido”; Sy: “servos”.
. “Deus.” Hebr.: ’El.
. Ou “e depois de mim não veio [ou: virá] a haver nenhum”.
====

[[v23-43-11]]

^<<v23-43-11,11>>^ Eu é que sou Jeová, e além de mim não há salvador.”

[[v23-43-12]]

^<<v23-43-12,12>>^ “Eu mesmo [o] comuniquei, e salvei, e fiz que fosse ouvido, quando entre vós não havia nenhum [deus] estranho.^&#42;1^ Portanto, vós sois as minhas testemunhas”, é a pronunciação de Jeová, “e eu sou Deus.^&#42;2^

[NOTE]
====
. Ou “nenhum estranho”.
. “Deus.” Hebr.: ’El.
====

[[v23-43-13]]

^<<v23-43-13,13>>^ Também, em todo o tempo^&#42;1^ sou o Mesmo; e não há quem livre da minha própria mão. Serei ativo, e quem a^&#42;2^ fará recuar?”

[NOTE]
====
. Lit.: “desde [o] dia”. LXXVg: “desde o princípio”.
. “A”, hebr. fem., referindo-se à “mão”, fem.
====

[[v23-43-14]]

^<<v23-43-14,14>>^ Assim disse Jeová, o vosso Resgatador, o Santo de Israel: “Por vossa causa vou enviar [alguém] a Babilônia e fazer descer as grades das prisões^&#42;1^ e os caldeus nos navios com clamores lamuriantes da sua parte.

[NOTE]
====
. “As grades das prisões”, mediante uma correção; M: “os fugitivos, todos eles”; Vg: “todas as grades (barreiras)”.
====

[[v23-43-15]]

^<<v23-43-15,15>>^ Eu sou Jeová, vosso Santo,^&#42;1^ o Criador de Israel, vosso Rei.”

[NOTE]
====
. Ou: “Eu, Jeová, sou vosso Santo.” Hebr.: ’aní Yehwáh Qedho·shekhém.
====

[[v23-43-16]]

^<<v23-43-16,16>>^ Assim disse Jeová, Aquele que faz um caminho através do próprio mar e uma senda mesmo através de fortes águas,

[[v23-43-17]]

^<<v23-43-17,17>>^ Aquele que faz sair o carro de guerra e o cavalo, a força militar e os fortes,^&#42;1^ ao mesmo tempo: “Deitar-se-ão. Não se levantarão. Serão certamente extinguidos. Qual mecha de linho terão de ser apagados.”

[NOTE]
====
. Lit.: “e um forte”, hebr. sing., mas em sentido coletivo.
====

[[v23-43-18]]

^<<v23-43-18,18>>^ “Não vos lembreis das primeiras coisas e não deis consideração às coisas anteriores.

[[v23-43-19]]

^<<v23-43-19,19>>^ Eis que eu faço algo novo. Agora é que surgirá. Acaso não o sabereis vós? De fato, porei um caminho através do ermo, rios através do deserto.

[[v23-43-20]]

^<<v23-43-20,20>>^ O animal selvático do campo me glorificará, os chacais e as avestruzes;^&#42;1^ porque terei dado água até mesmo no ermo, rios no deserto, para fazer beber meu povo, meu escolhido,

[NOTE]
====
. Veja 13:21 n.: “avestruzes”.
====

[[v23-43-21]]

^<<v23-43-21,21>>^ o povo que formei para mim, para que narrassem o meu louvor.

[[v23-43-22]]

^<<v23-43-22,22>>^ “Mas tu não me invocaste, ó Jacó, porque te fatigaste de mim, ó Israel.

[[v23-43-23]]

^<<v23-43-23,23>>^ Não me trouxeste o ovídeo do teu holocausto e não me glorificaste com os teus sacrifícios. Não te compeli a servir-me com um presente, nem te fatiguei com olíbano.

[[v23-43-24]]

^<<v23-43-24,24>>^ Não compraste para mim nenhuma cana [doce] com dinheiro;^&#42;1^ e não me saturaste com a gordura dos teus sacrifícios. Na realidade, tu me compeliste a servir, por causa dos teus pecados; fatigaste-me com os teus erros.

[NOTE]
====
. Ou “prata”.
====

[[v23-43-25]]

^<<v23-43-25,25>>^ Eu é que sou Aquele que oblitera as tuas transgressões por minha própria causa, e não me lembrarei dos teus pecados.

[[v23-43-26]]

^<<v23-43-26,26>>^ Faze-me lembrar; entremos juntamente em julgamento;^&#42;1^ narra o teu próprio relato disso para que tenhas razão.

[NOTE]
====
. Ou “entremos numa controvérsia; pleiteemos”.
====

[[v23-43-27]]

^<<v23-43-27,27>>^ Teu próprio pai, o primeiro, pecou, e teus próprios porta-vozes^&#42;1^ transgrediram contra mim.

[NOTE]
====
. Ou “intérpretes”.
====

[[v23-43-28]]

^<<v23-43-28,28>>^ Portanto, profanarei os príncipes do lugar santo^&#42;1^ e vou entregar Jacó como homem devotado à destruição, e Israel, a palavras de injúria.

[NOTE]
====
. Ou “profanarei os santos príncipes”.
====

'''

xref:023-isaias/023-isaias-042.adoc#v23-42-0[&#60; Capítulo Anterior] | <<v23-43-0,Topo>> | xref:023-isaias/023-isaias-044.adoc#v23-44-0[Próximo Capítulo &#62;]