include::./index.adoc[]

[[v23-24-0]]
=== Isaías, 24
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v23-24-1]]

^<<v23-24-1,1>>^ Eis que Jeová está esvaziando a terra^&#42;1^ e devastando-a, e ele entortou^&#42;2^ a face dela e espalhou os seus habitantes.

[NOTE]
====
. “A terra.” Hebr.: ha·’á·rets.
. Ou “desconcertou”.
====

[[v23-24-2]]

^<<v23-24-2,2>>^ E terá de ser o mesmo para o povo como para o sacerdote; o mesmo para o servo como para o seu amo;^&#42;1^ o mesmo para a serva como para a sua senhora; o mesmo para o comprador como para o vendedor; o mesmo para quem empresta como para quem toma emprestado; o mesmo para quem cobra juros^&#42;2^ como para quem paga juros.^&#42;3^

[NOTE]
====
. “Como para o seu amo.” Hebr.: ka’·dho·náv, pl. de ’a·dhóhn, para denotar excelência.
. Ou “o credor”.
. Ou “o devedor; mutuário”.
====

[[v23-24-3]]

^<<v23-24-3,3>>^ A terra, sem falta, será esvaziada, e, sem falta, será saqueada, porque o próprio Jeová falou esta palavra.

[[v23-24-4]]

^<<v23-24-4,4>>^ A terra pôs-se a prantear, desvaneceu-se. O solo produtivo^&#42;1^ murchou, desvaneceu-se. Definharam-se os altos do povo da terra.

[NOTE]
====
. Veja 13:11 n.: “produtivo”.
====

[[v23-24-5]]

^<<v23-24-5,5>>^ E a própria terra foi poluída sob os seus habitantes, pois deixaram de lado as leis, mudaram o regulamento, violaram o pacto de duração indefinida.

[[v23-24-6]]

^<<v23-24-6,6>>^ Por isso é que a própria maldição consumiu a terra e os que habitam nela são considerados culpados. Por isso é que os habitantes da terra diminuíram em número e restaram muito poucos homens mortais.

[[v23-24-7]]

^<<v23-24-7,7>>^ O vinho novo pôs-se a prantear, e a videira murchou, todos os alegres de coração puseram-se a suspirar.

[[v23-24-8]]

^<<v23-24-8,8>>^ Cessou a exultação dos pandeiros, interrompeu-se o barulho dos grandemente rejubilantes, cessou a exultação da harpa.

[[v23-24-9]]

^<<v23-24-9,9>>^ É sem canção que bebem vinho; a bebida inebriante torna-se amarga para os que a bebem.

[[v23-24-10]]

^<<v23-24-10,10>>^ A vila deserta foi destroçada; cada casa foi fechada para não se entrar [nela].

[[v23-24-11]]

^<<v23-24-11,11>>^ Há um clamor nas ruas por [falta de] vinho. Passou^&#42;1^ toda a alegria; desapareceu a exultação da terra.

[NOTE]
====
. Lit.: “virou como que noite; ficou escura”.
====

[[v23-24-12]]

^<<v23-24-12,12>>^ Na cidade deixou-se atrás uma condição assombrosa; o portão foi esmiuçado a um mero monte de destroços.

[[v23-24-13]]

^<<v23-24-13,13>>^ Pois assim virá a ser no meio da terra, no meio dos povos, igual à batedura da oliveira, igual à rebusca quando acabou a vindima.

[[v23-24-14]]

^<<v23-24-14,14>>^ Eles mesmos elevarão a sua voz, gritarão de júbilo. Na superioridade de Jeová certamente gritarão estridentemente desde o mar.^&#42;1^

[NOTE]
====
. Ou “oeste”.
====

[[v23-24-15]]

^<<v23-24-15,15>>^ Por isso é que, na região da luz,^&#42;1^ terão de glorificar a Jeová, nas ilhas do mar, o nome de Jeová, o Deus^&#42;2^ de Israel.

[NOTE]
====
. Lit.: “das luzes”. Evidentemente, a região ou o horizonte oriental.
. “O Deus de.” Hebr.: ’Elo·héh.
====

[[v23-24-16]]

^<<v23-24-16,16>>^ Desde a extremidade^&#42;1^ da terra temos ouvido melodias: “Ornato para o Justo!”
Mas eu digo: “Para mim há magreza, para mim há magreza! Ai de mim! Os traiçoeiros agiram traiçoeiramente. Com traição é que os traiçoeiros agiram traiçoeiramente.”

[NOTE]
====
. Lit.: “asa”.
====

[[v23-24-17]]

^<<v23-24-17,17>>^ O pavor, e o barranco, e a armadilha estão sobre ti, ó habitante da terra.

[[v23-24-18]]

^<<v23-24-18,18>>^ E terá de acontecer que todo aquele que fugir do som da coisa apavorante cairá no barranco, e todo aquele que subir de dentro do barranco será apanhado pela armadilha. Pois abrir-se-ão realmente as comportas^&#42;1^ no alto e tremerão os alicerces da terra.

[NOTE]
====
. Ou “janelas”.
====

[[v23-24-19]]

^<<v23-24-19,19>>^ A terra rebentou completamente, a terra foi sacudida completamente, a terra foi abalada completamente.

[[v23-24-20]]

^<<v23-24-20,20>>^ A terra oscila completamente igual a um bêbedo, e ela tem balançado para lá e para cá como um rancho de vigia. E sua transgressão se tornou pesada sobre ela e ela terá de cair, de modo que não se levantará mais.

[[v23-24-21]]

^<<v23-24-21,21>>^ E naquele dia terá de acontecer que Jeová voltará a sua atenção para o exército do alto, no alto, e para os reis do solo sobre o solo.

[[v23-24-22]]

^<<v23-24-22,22>>^ E eles hão de ser ajuntados com um ajuntamento como que de presos no poço e ser encerrados no calabouço; e depois de uma abundância de dias dar-se-á atenção a eles.

[[v23-24-23]]

^<<v23-24-23,23>>^ E a lua cheia ficou encabulada e o [sol] brilhante ficou envergonhado, pois, Jeová dos exércitos tornou-se rei no monte Sião e em Jerusalém, e diante dos seus homens idosos, com glória.

'''

xref:023-isaias/023-isaias-023.adoc#v23-23-0[&#60; Capítulo Anterior] | <<v23-24-0,Topo>> | xref:023-isaias/023-isaias-025.adoc#v23-25-0[Próximo Capítulo &#62;]