include::./index.adoc[]

[[v23-14-0]]
=== Isaías, 14
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v23-14-1]]

^<<v23-14-1,1>>^ Pois, Jeová terá misericórdia com Jacó, e certamente escolherá ainda Israel; e dar-lhes-á realmente descanso sobre o seu solo, e o residente forasteiro^&#42;1^ terá de ser juntado a eles, e terão de agregar-se à casa de Jacó.

[NOTE]
====
. Ou “o residente temporário”. Hebr.: hag·gér.
====

[[v23-14-2]]

^<<v23-14-2,2>>^ E povos realmente os tomarão e os levarão ao próprio lugar deles, e a casa de Israel terá de tomá-los para si como propriedade no solo de Jeová, como servos e como servas; e terão de tornar-se os captores dos que os mantinham cativos e terão de ter em sujeição aqueles que os compeliam a trabalhar.

[[v23-14-3]]

^<<v23-14-3,3>>^ E terá de acontecer, no dia em que Jeová te^&#42;1^ der descanso da tua dor, e da tua agitação, e da dura escravidão em que foste escravizado,

[NOTE]
====
. “Te”, hebr. masc. sing.
====

[[v23-14-4]]

^<<v23-14-4,4>>^ que terás de encetar esta expressão proverbial contra o rei de Babilônia e dizer:
“Como cessou^&#42;1^ aquele que compelia [outros] a trabalhar, [como] cessou a opressão!^&#42;2^

[NOTE]
====
. “Cessou.” Ou “parou”. Hebr.: sha·váth.
. Ou “potência; poder”. Veja VT, Vol. VII, 1957, pp. 202, 203. 1QIsa(hebr.): mar·he·váh, “ataque”; LXXSy: “o feitor”; Vg: “o tributo”.
====

[[v23-14-5]]

^<<v23-14-5,5>>^ Jeová destroçou o bastão dos iníquos, a vara dos governantes,

[[v23-14-6]]

^<<v23-14-6,6>>^ aquele que incessantemente golpeava povos em fúria com um golpe, aquele que subjugava nações em pura ira, com perseguição sem freio.

[[v23-14-7]]

^<<v23-14-7,7>>^ A terra inteira chegou a descansar, ficou sossegada. As pessoas ficaram animadas, com clamores jubilantes.

[[v23-14-8]]

^<<v23-14-8,8>>^ Até mesmo os juníperos se alegraram de ti,^&#42;1^ os cedros do Líbano, [dizendo:] ‘Desde que te deitaste, não sobe contra nós nenhum lenhador.’

[NOTE]
====
. “Ti”, hebr. masc. sing.
====

[[v23-14-9]]

^<<v23-14-9,9>>^ “Até mesmo o Seol,^&#42;1^ embaixo, ficou agitado por tua causa, para encontrar-se contigo ao entrares. Por ti tem despertado os impotentes na morte,^&#42;2^ todos os líderes caprinos^&#42;3^ da terra. Fez que todos os reis das nações se levantassem dos seus tronos.

[NOTE]
====
. “Seol”, 1QIsaM(hebr.: she’óhl)T; gr.: haí·des; lat.: in·fér·nus.
. “Os impotentes na morte.” Hebr.: refa·’ím; LXXSyVg: “os gigantes”. Veja Jó 26:5 n.; Sal 88:10 n.
. Lit.: “os bodes”.
====

[[v23-14-10]]

^<<v23-14-10,10>>^ Todos eles respondem e te dizem: ‘Foste tu mesmo também debilitado^&#42;1^ igual a nós? É a nós que te tornaste comparável?

[NOTE]
====
. Ou “adoentado”.
====

[[v23-14-11]]

^<<v23-14-11,11>>^ Ao Seol se fez descer o teu orgulho, a barulhada dos teus instrumentos de cordas. Abaixo de ti, os gusanos estão estendidos como leito; e vermes são a tua cobertura.’

[[v23-14-12]]

^<<v23-14-12,12>>^ “Como caíste do céu, ó tu brilhante,^&#42;1^ filho da alva! Como foste cortado rente à terra, tu que prostravas as nações!

[NOTE]
====
. “Brilhante”, BDB, p. 237; hebr.: heh·lél. Gr.: ho he·o·sfó·ros, “aquele que traz a alva (manhã)”; lat.: lú·ci·fer, “portador de luz”. Veja Jó 38:32 n.: “constelação de Mazarote”.
====

[[v23-14-13]]

^<<v23-14-13,13>>^ No que se refere a ti, disseste no teu coração: ‘Subirei aos céus. Enaltecerei o meu trono acima das estrelas de Deus^&#42;1^ e assentar-me-ei no monte de reunião, nas partes mais remotas do norte.

[NOTE]
====
. “Deus.” Hebr.: ’El; lat.: Dé·i; LXX: “do céu”.
====

[[v23-14-14]]

^<<v23-14-14,14>>^ Subirei acima dos altos das nuvens; assemelhar-me-ei ao Altíssimo.’

[[v23-14-15]]

^<<v23-14-15,15>>^ “Todavia, no Seol^&#42;1^ serás precipitado, nas partes mais remotas do poço.

[NOTE]
====
. “Seol”, 1QIsaM(hebr.: she’óhl)T; gr.: haí·dou; lat.: in·fér·num.
====

[[v23-14-16]]

^<<v23-14-16,16>>^ Os que te virem te fitarão; examinar-te-ão de perto, [dizendo:] ‘É este o homem^&#42;1^ que agitava a terra, que fazia tremer os reinos,

[NOTE]
====
. “O homem.” Hebr.: ha·’ísh; gr.: ho án·thro·pos; sir.: gab·ra’; lat.: vir.
====

[[v23-14-17]]

^<<v23-14-17,17>>^ que fez o solo produtivo^&#42;1^ como o ermo, que lhe derrubou as próprias cidades, que nem aos seus prisioneiros abriu o caminho para casa?’

[NOTE]
====
. Veja 13:11 n.: “produtivo”.
====

[[v23-14-18]]

^<<v23-14-18,18>>^ Todos os outros reis das nações, sim, todos eles, deitaram-se em glória, cada um na sua própria casa.

[[v23-14-19]]

^<<v23-14-19,19>>^ Mas, no que se refere a ti, foste lançado fora sem sepultura para ti,^&#42;1^ qual rebentão^&#42;2^ detestado, revestido de homens mortos, traspassados com a espada, que descem às pedras de um poço, como um cadáver calcado.

[NOTE]
====
. Lit.: “fora da tua sepultura”.
. “Qual rebentão.” Hebr.: kené·tser.
====

[[v23-14-20]]

^<<v23-14-20,20>>^ Não te unirás a eles num sepulcro,^&#42;1^ pois arruinaste a tua própria terra, mataste o teu próprio povo. Por tempo indefinido não se mencionará^&#42;2^ o nome da descendência^&#42;3^ dos malfeitores.

[NOTE]
====
. Ou “no sepultamento”.
. Ou “chamará”.
. Ou “semente”.
====

[[v23-14-21]]

^<<v23-14-21,21>>^ “Aprontai um cepo de matança para os seus próprios filhos, por causa do erro dos antepassados deles, para que não se levantem e realmente tomem posse da terra, e encham de cidades a face do solo produtivo.”^&#42;1^

[NOTE]
====
. Veja 13:11 n.: “produtivo”.
====

[[v23-14-22]]

^<<v23-14-22,22>>^ “E eu vou levantar-me contra eles”, é a pronunciação de Jeová dos exércitos.
“E vou decepar de Babilônia^&#42;1^ o nome, e o restante,^&#42;2^ e a progênie, e a posteridade”, é a pronunciação de Jeová.

[NOTE]
====
. “Babilônia”, Vg; MTSy: “Babel”.
. Ou “os restantes”.
====

[[v23-14-23]]

^<<v23-14-23,23>>^ “E vou constituí-la em propriedade de porcos-espinhos e em banhados de juncos, e vou varrê-la com a vassoura do aniquilamento”, é a pronunciação de Jeová dos exércitos.

[[v23-14-24]]

^<<v23-14-24,24>>^ Jeová dos exércitos jurou, dizendo: “Seguramente, assim como tencionei, assim terá de acontecer; e assim como aconselhei, deste modo se efetuará,

[[v23-14-25]]

^<<v23-14-25,25>>^ para destroçar o assírio^&#42;1^ na minha terra e para calcá-lo nos meus próprios montes; e que seu jugo realmente se retire de cima deles e seu próprio fardo suma de cima do ombro deles.”^&#42;2^

[NOTE]
====
. “O assírio.” Hebr.: ’Ash·shúr; LXX: “os assírios”.
. “Deles”, TVg; M: “dele”.
====

[[v23-14-26]]

^<<v23-14-26,26>>^ Este é o conselho que se aconselha contra toda a terra, e esta é a mão que se estende contra todas as nações.

[[v23-14-27]]

^<<v23-14-27,27>>^ Pois o próprio Jeová dos exércitos tem aconselhado, e quem [o] pode desfazer? E sua mão é a que está estendida, e quem a pode fazer recuar?

[[v23-14-28]]

^<<v23-14-28,28>>^ No ano em que morreu o Rei Acaz ocorreu esta pronúncia:

[[v23-14-29]]

^<<v23-14-29,29>>^ “Não te alegres, ó Filístia, qualquer um de ti, só porque foi destroçada a vara de quem te golpeava. Porque da raiz da serpente sairá uma cobra venenosa, e seu fruto será uma cobra ardente, voadora.

[[v23-14-30]]

^<<v23-14-30,30>>^ E os primogênitos dos de condição humilde certamente pastarão, e os próprios pobres se deitarão em segurança. E vou matar a tua raiz à fome, e o que restar de ti^&#42;1^ será morto.^&#42;2^

[NOTE]
====
. Ou “e o restante de ti”. Hebr.: u·she’e·ri·thékh.
. Ou “alguém matará”.
====

[[v23-14-31]]

^<<v23-14-31,31>>^ Uiva, ó portão! Clama, ó cidade! Tu tens de ficar esmorecida, ó Filístia toda! Pois, procedente do norte vem uma fumaça, e ninguém fica isolado das suas fileiras.”

[[v23-14-32]]

^<<v23-14-32,32>>^ E o que se dirá em resposta aos mensageiros da nação? Que o próprio Jeová lançou o alicerce de Sião, e nela se refugiarão os atribulados do seu povo.

'''

xref:023-isaias/023-isaias-013.adoc#v23-13-0[&#60; Capítulo Anterior] | <<v23-14-0,Topo>> | xref:023-isaias/023-isaias-015.adoc#v23-15-0[Próximo Capítulo &#62;]