include::./index.adoc[]

[[v23-60-0]]
=== Isaías, 60
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v23-60-1]]

^<<v23-60-1,1>>^ “Levanta-te, ó mulher,^&#42;1^ dá luz, pois chegou a tua luz e raiou sobre ti a própria glória de Jeová.

[NOTE]
====
. “Ó mulher”, porque os pronomes e os verbos no hebr. estão no fem. sing. TLXXVgc: “ó Jerusalém!”
====

[[v23-60-2]]

^<<v23-60-2,2>>^ Pois, eis que a própria escuridão cobrirá a terra e densas trevas os grupos nacionais; mas sobre ti raiará Jeová e sobre ti se verá a sua própria glória.

[[v23-60-3]]

^<<v23-60-3,3>>^ E nações hão de ir à tua luz e reis à claridade do teu raiar.

[[v23-60-4]]

^<<v23-60-4,4>>^ “Levanta^&#42;1^ os olhos [olhando] ao redor e vê! Todos eles foram reunidos; chegaram a ti. De longe estão chegando os teus próprios filhos e tuas filhas, das quais se cuidará sobre o lado.

[NOTE]
====
. “Levanta”, hebr. fem. sing., como no v. 1.
====

[[v23-60-5]]

^<<v23-60-5,5>>^ Naquele tempo verás^&#42;1^ e certamente ficarás radiante, e teu coração realmente tremerá e se expandirá, porque a ti se encaminhará a opulência do mar; os próprios recursos das nações chegarão a ti.

[NOTE]
====
. “Verás”, 1QIsaMTLXXSyVg; 15 ou mais mss. hebr.: “temerás”.
====

[[v23-60-6]]

^<<v23-60-6,6>>^ A própria massa movimentada de camelos te cobrirá, os machos novos dos camelos de Midiã e de Efá. Todos os de Sabá — eles chegarão. Carregarão ouro e olíbano. Anunciarão os louvores de Jeová.

[[v23-60-7]]

^<<v23-60-7,7>>^ Todos os rebanhos de Quedar — serão reunidos a ti. Os carneiros de Nebaiote — ministrarão a ti.^&#42;1^ Subirão com aprovação ao meu altar e eu embelezarei a minha própria casa de beleza.

[NOTE]
====
. “Ministrarão (atenderão) a ti.” Hebr.: yeshor·thú·nekh; lat.: mi·ni·strá·bunt.
====

[[v23-60-8]]

^<<v23-60-8,8>>^ “Quem são estes que vêm voando como nuvem e como pombas para as aberturas de seu pombal?

[[v23-60-9]]

^<<v23-60-9,9>>^ Pois em mim as próprias ilhas continuarão a ter esperança, também os navios de Társis, como no começo, a fim de trazer de longe teus filhos, estando com eles sua prata e seu ouro, ao nome de Jeová, teu Deus,^&#42;1^ e ao Santo de Israel, porque ele te terá embelezado.

[NOTE]
====
. “Teu Deus.” Hebr.: ’Elo·há·yikh.
====

[[v23-60-10]]

^<<v23-60-10,10>>^ E estrangeiros^&#42;1^ construirão realmente as tuas muralhas, e seus próprios reis ministrarão^&#42;2^ a ti; pois na minha indignação eu te terei golpeado, mas na minha boa vontade vou certamente ter misericórdia de ti.

[NOTE]
====
. Lit.: “filhos dum (país) estrangeiro”.
. Veja v. 7 n.
====

[[v23-60-11]]

^<<v23-60-11,11>>^ “E os teus portões ficarão de fato constantemente abertos;^&#42;1^ não serão fechados nem de dia nem de noite, a fim de que se tragam a ti os recursos das nações, e seus reis tomarão a dianteira.

[NOTE]
====
. “Teus portões ficarão de fato . . . abertos”, mediante uma correção em harmonia com TLXXSyVg; 1QIsaM: “abre os teus portões”.
====

[[v23-60-12]]

^<<v23-60-12,12>>^ Porque a nação e o reino que não te servirem perecerão; e as próprias nações, sem falta, sofrerão a devastação.

[[v23-60-13]]

^<<v23-60-13,13>>^ “A ti chegará a própria glória do Líbano, o junípero, o freixo e o cipreste, ao mesmo tempo, a fim de embelezar o lugar do meu santuário; e eu glorificarei o próprio lugar dos meus pés.

[[v23-60-14]]

^<<v23-60-14,14>>^ “E terão de ir a ti os filhos dos que te atribulam, encurvando-se; e todos os que te tratam com desrespeito terão de curvar-se junto às próprias solas dos teus pés e terão de chamar-te de cidade de Jeová, Sião do Santo de Israel.

[[v23-60-15]]

^<<v23-60-15,15>>^ “Em vez de mostrares estar completamente abandonada e odiada, sem que alguém passe [por ti], vou pôr-te como uma coisa de orgulho, por tempo indefinido, como exultação, de geração em geração.

[[v23-60-16]]

^<<v23-60-16,16>>^ E realmente sugarás o leite de nações e mamarás aos peitos de reis; e certamente saberás que eu, Jeová, sou teu Salvador, e que o Potentado de Jacó é teu Resgatador.^&#42;1^

[NOTE]
====
. Ou “eu sou Jeová, teu Salvador e teu Resgatador, o Potentado de Jacó”.
====

[[v23-60-17]]

^<<v23-60-17,17>>^ Em lugar de cobre trarei ouro, e em lugar de ferro trarei prata, e em lugar de madeira, cobre, e em lugar de pedras, ferro; e eu vou designar a paz como teus superintendentes^&#42;1^ e a justiça como teus feitores.

[NOTE]
====
. Lit.: “tua superintendência”.
====

[[v23-60-18]]

^<<v23-60-18,18>>^ “Não mais se ouvirá de violência na tua terra, de assolação ou de desmoronamento dentro dos teus termos. E certamente chamarás as tuas próprias muralhas de Salvação e os teus portões de Louvor.

[[v23-60-19]]

^<<v23-60-19,19>>^ Para ti, o sol não mais se mostrará uma luz de dia, e para claridade, a própria lua não mais te dará luz. E Jeová terá de tornar-se para ti uma luz de duração indefinida, e teu Deus,^&#42;1^ a tua beleza.

[NOTE]
====
. “E teu Deus.” Hebr.: wE’·lo·há·yikh.
====

[[v23-60-20]]

^<<v23-60-20,20>>^ Não mais se porá o teu sol, nem minguará a tua lua; pois o próprio Jeová se tornará para ti uma luz de duração indefinida e terão acabado os dias do teu pranto.

[[v23-60-21]]

^<<v23-60-21,21>>^ E quanto ao teu povo, todos eles serão justos; por tempo indefinido terão posse da terra, rebentão da minha^&#42;1^ plantação, trabalho das minhas mãos, para [eu] ser embelezado.

[NOTE]
====
. “Minha”, TSyVg e 14 ou mais mss. hebr.; 1QIsa: “de Jeová”; M: “sua”.
====

[[v23-60-22]]

^<<v23-60-22,22>>^ O próprio pequeno tornar-se-á mil e o menor, uma nação forte. Eu mesmo, Jeová, apressarei isso ao seu próprio tempo.”

'''

xref:023-isaias/023-isaias-059.adoc#v23-59-0[&#60; Capítulo Anterior] | <<v23-60-0,Topo>> | xref:023-isaias/023-isaias-061.adoc#v23-61-0[Próximo Capítulo &#62;]