include::./index.adoc[]

[[v23-8-0]]
=== Isaías, 8
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v23-8-1]]

^<<v23-8-1,1>>^ E Jeová passou a dizer-me: “Toma para ti uma grande tábua e escreve nela com o estilo do homem mortal:^&#42;1^ ‘Maer-Salal-Hás-Baz.’^&#42;2^

[NOTE]
====
. Ou “com um estilo comum”.
. Significando “Apressa-te ó [ou: Apressando-se ao] Despojo! Ele Veio Rapidamente à Pilhagem”.
====

[[v23-8-2]]

^<<v23-8-2,2>>^ E haja para mim uma testificação por testemunhas fiéis: Urias, o sacerdote, e Zacarias,^&#42;1^ filho de Jeberequias.”^&#42;2^

[NOTE]
====
. Significando “Jeová Lembrou-se”. Hebr.: Zekhar·yá·hu.
. Significando “Jeová Abençoa”. Hebr.: Yeve·rekh·yá·hu.
====

[[v23-8-3]]

^<<v23-8-3,3>>^ Cheguei-me então à profetisa, e ela ficou grávida, e no tempo devido deu à luz um filho. Jeová disse-me então: “Chama-o pelo nome de Maer-Salal-Hás-Baz,

[[v23-8-4]]

^<<v23-8-4,4>>^ pois antes que o rapazinho saiba chamar: ‘Meu pai!’ e: ‘Minha mãe!’ carregar-se-á com os recursos de Damasco e com o despojo de Samaria perante o rei da Assíria.”

[[v23-8-5]]

^<<v23-8-5,5>>^ E Jeová passou a falar ainda mais comigo, dizendo:

[[v23-8-6]]

^<<v23-8-6,6>>^ “Visto que este povo rejeitou as águas de Siloé,^&#42;1^ que correm suavemente, e há exultação por causa de Rezim e do filho de Remalias;^&#42;2^

[NOTE]
====
. Significando “Remetente”, indicando um conduto de água; LXX: “Siloé”.
. Veja 2Rs 15:25 n.: “Remalias”.
====

[[v23-8-7]]

^<<v23-8-7,7>>^ por isso, pois, eis que Jeová^&#42;1^ está trazendo contra eles as águas potentes e numerosas do Rio, o rei da Assíria e toda a sua glória. E subirá certamente sobre todos os seus leitos e transbordará todas as suas ribanceiras,

[NOTE]
====
. Uma das 134 mudanças de YHWH para ’Adho·naí feitas pelos escribas. Veja Ap. 1B.
====

[[v23-8-8]]

^<<v23-8-8,8>>^ e avançará através de Judá. Realmente inundará e passará. Chegará até o pescoço. E terá de ocorrer o esticamento das suas asas para encher a largura da tua terra, ó Emanuel!”^&#42;1^

[NOTE]
====
. Veja 7:14 n.: “Emanuel”.
====

[[v23-8-9]]

^<<v23-8-9,9>>^ Sede ruinosos,^&#42;1^ ó povos, e sede desbaratados; e dai ouvidos, todas as partes longínquas da terra! Cingi-vos, e sede desbaratados! Cingi-vos, e sede desbaratados!

[NOTE]
====
. “Sabei”, LXX e mediante uma correção do M, em harmonia com a expressão paralela: “dai ouvidos”.
====

[[v23-8-10]]

^<<v23-8-10,10>>^ Formai um plano, e será desfeito! Falai qualquer palavra, e ela não se efetuará, porque Deus está conosco!^&#42;1^

[NOTE]
====
. “Deus está conosco.” Hebr.: ‛im·má·nu ’El; LXX: “Jeová Deus está conosco”.
====

[[v23-8-11]]

^<<v23-8-11,11>>^ Pois assim me disse Jeová, com força da mão, para desviar-me^&#42;1^ de andar no caminho deste povo, dizendo:

[NOTE]
====
. “Para, admoestando, afastar-me”, mediante outra derivação do verbo hebr.
====

[[v23-8-12]]

^<<v23-8-12,12>>^ “Não deveis dizer: ‘Conspiração!’ no que se refere a tudo de que este povo está dizendo: ‘Conspiração!’ e não deveis temer aquilo de que eles têm medo, nem deveis estremecer diante dele.

[[v23-8-13]]

^<<v23-8-13,13>>^ Jeová dos exércitos — é a Ele que deveis tratar como santo e Ele deve ser o objeto de vosso medo, e Ele é quem vos deve fazer estremecer.”

[[v23-8-14]]

^<<v23-8-14,14>>^ E ele terá de tornar-se como um lugar sagrado;^&#42;1^ mas como pedra contra que se esbarra e como rocha em que se tropeça, para ambas as casas de Israel, como armadilha e como laço para os habitantes^&#42;2^ de Jerusalém.

[NOTE]
====
. Ou “um santuário”.
. “Habitantes”, LXXSyVg e sete mss. hebr.; 1QIsaM: “habitante”.
====

[[v23-8-15]]

^<<v23-8-15,15>>^ E muitos entre eles hão de tropeçar e cair, e ser quebrados, e ser enlaçados e capturados.

[[v23-8-16]]

^<<v23-8-16,16>>^ Embrulha a atestação,^&#42;1^ põe um selo em volta da lei entre os meus discípulos!^&#42;2^

[NOTE]
====
. Ou “testemunho”.
. Ou “meus ensinados”.
====

[[v23-8-17]]

^<<v23-8-17,17>>^ E eu vou ficar à espera de Jeová, que esconde a sua face da casa de Jacó, e nele vou esperar.

[[v23-8-18]]

^<<v23-8-18,18>>^ Eis que eu e os filhos que Jeová me deu somos como sinais e como milagres^&#42;1^ em Israel, da parte de Jeová dos exércitos, que reside no monte Sião.

[NOTE]
====
. Ou “maravilhas; portentos; indícios”.
====

[[v23-8-19]]

^<<v23-8-19,19>>^ E caso vos digam: “Recorrei aos médiuns espíritas ou aos que têm espírito de predição, que chilram e fazem pronunciações em voz baixa”,^&#42;1^ não é a seu Deus que qualquer povo devia recorrer? [Acaso se deve recorrer] a pessoas mortas a favor de pessoas vivas?

[NOTE]
====
. Ou “e fazem ventriloquia”.
====

[[v23-8-20]]

^<<v23-8-20,20>>^ À^&#42;1^ lei e à atestação!
Seguramente persistirão em dizer o que é segundo esta declaração^&#42;2^ que não terá a luz da alva.

[NOTE]
====
. Ou: “Para a”; ou: “Pertence à.”
. Ou “palavra; coisa falada”.
====

[[v23-8-21]]

^<<v23-8-21,21>>^ E cada um^&#42;1^ há de atravessar a terra^&#42;2^ em duro aperto e faminto; e terá de acontecer que, por ter fome e se ter indignado, ele realmente invocará o mal sobre o seu rei e sobre o seu Deus,^&#42;3^ e certamente olhará para cima.

[NOTE]
====
. Ou “eles”. Lit.: “alguém (um)”.
. Lit.: “ela”; hebr. fem., isto é, a terra.
. “E sobre o seu Deus.” Hebr.: u·vE’·lo·háv.
====

[[v23-8-22]]

^<<v23-8-22,22>>^ E olhará para a terra, e eis aflição e escuridão, negrume, tempos difíceis e trevas, sem claridade.^&#42;1^

[NOTE]
====
. “Sem claridade”, mediante uma ligeira correção; LXX: “para não ver”; M: “[nas quais] se é empurrado (lançado)”.
====

'''

xref:023-isaias/023-isaias-007.adoc#v23-7-0[&#60; Capítulo Anterior] | <<v23-8-0,Topo>> | xref:023-isaias/023-isaias-009.adoc#v23-9-0[Próximo Capítulo &#62;]