include::./index.adoc[]

[[v23-10-0]]
=== Isaías, 10
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v23-10-1]]

^<<v23-10-1,1>>^ Ai dos que legislam regulamentos prejudiciais e dos que, escrevendo constantemente, têm escrito pura desgraça,

[[v23-10-2]]

^<<v23-10-2,2>>^ a fim de apartar os de condição humilde de alguma causa jurídica e para arrebatar dos atribulados do meu povo a justiça, para que as viúvas se tornem seu despojo e para que saqueiem até mesmo os meninos órfãos de pai!

[[v23-10-3]]

^<<v23-10-3,3>>^ E o que fareis vós no dia de se dar atenção e na ruína, quando vier de longe? Para quem fugireis por auxílio e onde deixareis a vossa glória,

[[v23-10-4]]

^<<v23-10-4,4>>^ senão para ter de dobrar-se sob os presos e para as pessoas continuarem a cair debaixo dos que foram mortos? Sua ira não recuou em vista de tudo isso, mas a sua mão ainda está estendida.

[[v23-10-5]]

^<<v23-10-5,5>>^ “Ah! o assírio, a vara para a minha ira e o bastão na mão deles para a verberação por mim!

[[v23-10-6]]

^<<v23-10-6,6>>^ Enviá-lo-ei contra uma nação apóstata e dar-lhe-ei uma ordem contra o povo da minha fúria, para tomar muito despojo e tomar muito saque,^&#42;1^ e para fazer dele^&#42;2^ um lugar pisado como o barro das ruas.

[NOTE]
====
. Lit.: “despojar despojo e saquear saque”.
. “Dele”, hebr. masc., referindo-se ao “povo” ou à “nação”.
====

[[v23-10-7]]

^<<v23-10-7,7>>^ Embora ele talvez não seja assim, sentir-se-á inclinado [a isso]; embora seu coração talvez não seja assim, maquinará, porque tem no coração aniquilar e decepar não poucas nações.

[[v23-10-8]]

^<<v23-10-8,8>>^ Pois dirá: ‘Não são os meus príncipes ao mesmo tempo reis?

[[v23-10-9]]

^<<v23-10-9,9>>^ Não é Calno como Carquemis? Não é Hamate como Arpade? Não é Samaria como Damasco?

[[v23-10-10]]

^<<v23-10-10,10>>^ Quando minha mão tiver alcançado os reinos do deus que nada vale, cujas imagens entalhadas são mais do que as em Jerusalém e em Samaria,

[[v23-10-11]]

^<<v23-10-11,11>>^ não se dará que, como terei feito a Samaria e aos seus deuses que nada valem, assim farei a Jerusalém e aos seus ídolos?’

[[v23-10-12]]

^<<v23-10-12,12>>^ “E terá de acontecer que, quando Jeová^&#42;1^ terminar todo o seu trabalho no monte Sião e em Jerusalém, ajustarei contas pelos frutos da insolência do coração do rei da Assíria e pela vanglória do seu enaltecimento de olhos.

[NOTE]
====
. Uma das 134 mudanças de YHWH para ’Adho·naí feitas pelos escribas. Veja Ap. 1B.
====

[[v23-10-13]]

^<<v23-10-13,13>>^ Porque ele disse: ‘Hei de agir com o poder de minha mão e com a minha sabedoria, pois deveras tenho entendimento; e removerei os termos de povos e certamente rapinarei as suas coisas armazenadas, e submeterei os habitantes como alguém forte.

[[v23-10-14]]

^<<v23-10-14,14>>^ E como se fosse a um ninho, minha mão alcançará os recursos dos povos; e assim como se ajuntam os ovos que foram deixados, eu é que vou ajuntar até mesmo toda a terra, e certamente não haverá quem bata as [suas] asas, ou abra a [sua] boca, ou chilre.’”

[[v23-10-15]]

^<<v23-10-15,15>>^ Realçar-se-á o machado sobre aquele que corta com ele, ou magnificar-se-á a própria serra sobre aquele que a move para lá e para cá, como se a vara movesse para lá e para cá aqueles^&#42;1^ que a erguem, como se o bastão erguesse aquele que não é pau?

[NOTE]
====
. Ou “o Grandioso”, pl. no hebr., possivelmente para denotar a grandiosidade duma pessoa.
====

[[v23-10-16]]

^<<v23-10-16,16>>^ Por isso, o [verdadeiro] Senhor,^&#42;1^ Jeová dos exércitos, continuará a enviar a emaciação sobre os seus gordos, e sob a sua glória estará acesa uma queima como a queima de fogo.

[NOTE]
====
. “O [verdadeiro] Senhor.” Hebr.: ha·’A·dhóhn; lat.: Do·mi·ná·tor. Veja Ap. 1H.
====

[[v23-10-17]]

^<<v23-10-17,17>>^ E a Luz de Israel terá de tornar-se um fogo, e seu Santo, uma chama; e terá de chamejar e consumir suas ervas daninhas e seus espinheiros num só dia.

[[v23-10-18]]

^<<v23-10-18,18>>^ E Ele acabará com a glória da sua floresta e do seu pomar, desde a própria alma até a carne, e terá de tornar-se igual ao definhamento de quem padece de doença.^&#42;1^

[NOTE]
====
. Ou “que fraqueja”.
====

[[v23-10-19]]

^<<v23-10-19,19>>^ E o restante^&#42;1^ das árvores da sua floresta — ficarão em número tal que um mero rapaz as poderá anotar.

[NOTE]
====
. Ou “o restante”. Veja 7:3 n.
====

[[v23-10-20]]

^<<v23-10-20,20>>^ E naquele dia certamente acontecerá que os restantes de Israel e os fugitivos^&#42;1^ da casa de Jacó nunca mais se apoiarão naquele que os golpeia, e certamente se apoiarão em Jeová, o Santo de Israel, em veracidade.^&#42;2^

[NOTE]
====
. Ou “a parte que fugiu”.
. “Em veracidade (verdade).” Hebr.: be·’eméth.
====

[[v23-10-21]]

^<<v23-10-21,21>>^ Um mero restante^&#42;1^ retornará,^&#42;2^ o restante de Jacó, ao Deus Poderoso.^&#42;3^

[NOTE]
====
. Ou: “Os restantes”, como no v. 20.
. “Um mero restante retornará.” Hebr.: she’ár ya·shúv, a mesma expressão hebr. que no nome “Sear-Jasube” em 7:3, cuja n. veja.
. “Ao Deus Poderoso.” Hebr.: ’El Gib·bóhr. Veja 9:6 n.: “Poderoso”.
====

[[v23-10-22]]

^<<v23-10-22,22>>^ Pois, mesmo que teu povo, ó Israel, mostre ser como os grãos de areia do mar, um mero restante^&#42;1^ entre eles retornará. Um extermínio determinado passará inundando em justiça,

[NOTE]
====
. Ou “os restantes”, como no v. 20.
====

[[v23-10-23]]

^<<v23-10-23,23>>^ porque o Soberano Senhor, Jeová dos exércitos, executará uma exterminação e uma determinação estrita no meio de todo o país.^&#42;1^

[NOTE]
====
. Ou “terra”.
====

[[v23-10-24]]

^<<v23-10-24,24>>^ Portanto, assim disse o Soberano Senhor, Jeová dos exércitos: “Não tenhas medo, povo meu, que moras em Sião, por causa do assírio que costumava golpear-te com a vara e que costumava levantar contra ti o seu próprio bastão, à maneira do Egito.

[[v23-10-25]]

^<<v23-10-25,25>>^ Pois ainda um pouquinho — e a verberação terá chegado ao fim, e a minha ira, no desgaste deles.

[[v23-10-26]]

^<<v23-10-26,26>>^ E Jeová dos exércitos certamente brandirá contra ele um chicote, como na derrota de Midiã junto à rocha de Orebe; e seu bastão estará sobre o mar, e certamente o levantará na maneira como fez com o Egito.

[[v23-10-27]]

^<<v23-10-27,27>>^ “E naquele dia terá de acontecer que o fardo dele sumirá de cima de teu ombro, e o jugo dele, de cima de teu pescoço, e o jugo certamente será destroçado por causa do óleo.”^&#42;1^

[NOTE]
====
. Possivelmente óleo como o usado para as tochas dos 300 homens de Gideão; ou o óleo com que os reis de Israel eram ungidos.
====

[[v23-10-28]]

^<<v23-10-28,28>>^ Ele chegou sobre Aiate; passou por Migrom; deposita seus objetos em Micmás.

[[v23-10-29]]

^<<v23-10-29,29>>^ Passaram o vau,^&#42;1^ Geba é lugar para pernoitarem, Ramá tremeu, a própria Gibeá de Saul fugiu.

[NOTE]
====
. Ou “travessia; passagem”.
====

[[v23-10-30]]

^<<v23-10-30,30>>^ Emite a tua voz estridentemente, ó filha de Galim. Presta atenção, ó Laísa. Ó atribulada Anatote!

[[v23-10-31]]

^<<v23-10-31,31>>^ Madmena fugiu. Os próprios habitantes de Gebim se abrigaram.

[[v23-10-32]]

^<<v23-10-32,32>>^ Ainda é dia em Nobe, para fazer uma parada. Sacode [ameaçadoramente] a sua mão^&#42;1^ contra o monte da filha de Sião, o morro de Jerusalém.

[NOTE]
====
. Ou “sacode . . . o punho”.
====

[[v23-10-33]]

^<<v23-10-33,33>>^ Eis que o [verdadeiro] Senhor,^&#42;1^ Jeová dos exércitos, está truncando galhos com terrível estrondo; e os que cresceram altos, estão sendo cortados, e os próprios eminentes ficam rebaixados.

[NOTE]
====
. Veja Ap. 1H.
====

[[v23-10-34]]

^<<v23-10-34,34>>^ E ele derrubou as moitas da floresta com um instrumento de ferro, e o próprio Líbano cairá por meio de um poderoso.

'''

xref:023-isaias/023-isaias-009.adoc#v23-9-0[&#60; Capítulo Anterior] | <<v23-10-0,Topo>> | xref:023-isaias/023-isaias-011.adoc#v23-11-0[Próximo Capítulo &#62;]