include::./index.adoc[]

[[v23-27-0]]
=== Isaías, 27
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v23-27-1]]

^<<v23-27-1,1>>^ Naquele dia, Jeová, com a sua espada dura, e grande, e forte, voltará sua atenção para [o] leviatã,^&#42;1^ a serpente deslizadora, sim, para [o] leviatã, a serpente sinuosa, e certamente matará o monstro marinho que há no mar.

[NOTE]
====
. “Leviatã”, MSyVg; LXX: “o dragão”.
====

[[v23-27-2]]

^<<v23-27-2,2>>^ Naquele dia cantai para ela: “Uma vinha de vinho espumante!^&#42;1^

[NOTE]
====
. “Vinho espumante.” AlCa(hebr.): hhé·mer; isto é, vinho em fermentação.
====

[[v23-27-3]]

^<<v23-27-3,3>>^ Eu, Jeová, a resguardo. A todo instante a regarei. Para que ninguém volte a sua atenção contra ela, resguardá-la-ei mesmo noite e dia.

[[v23-27-4]]

^<<v23-27-4,4>>^ Não tenho furor algum. Quem me dará espinheiros [e] ervas daninhas na batalha? Vou pisar em tais. Ao mesmo tempo vou pôr fogo a tais.

[[v23-27-5]]

^<<v23-27-5,5>>^ Senão, que tome o meu baluarte, que faça paz comigo; faça ele paz comigo.”

[[v23-27-6]]

^<<v23-27-6,6>>^ Nos [dias] vindouros, Jacó lançará raízes, Israel produzirá flores e realmente florescerá; e eles simplesmente encherão de produtos a superfície do solo produtivo.^&#42;1^

[NOTE]
====
. Veja 13:11 n.: “produtivo”.
====

[[v23-27-7]]

^<<v23-27-7,7>>^ Terá de ser golpeado como que com o golpe de quem o golpeia? Ou terá de ser morto como que com a chacina^&#42;1^ dos seus que foram mortos?

[NOTE]
====
. Lit.: “matança”.
====

[[v23-27-8]]

^<<v23-27-8,8>>^ Contenderás com ela com um grito para assustar quando a mandares embora. Ele terá de expulsá-la com o seu sopro, um forte, no dia do vento oriental.

[[v23-27-9]]

^<<v23-27-9,9>>^ Portanto, por este meio se expiará o erro de Jacó, e este é todo o fruto, [quando] tirar o pecado dele, quando fizer todas as pedras do altar como pedras de cal que foram pulverizadas, de modo que não se erigirão os postes sagrados^&#42;1^ e os pedestais-incensários.

[NOTE]
====
. Ou “as Axerás”.
====

[[v23-27-10]]

^<<v23-27-10,10>>^ Porque a cidade fortificada ficará solitária, a pastagem será deixada só e abandonada qual ermo. Ali pastará o bezerro e ali se deitará; e ele consumirá realmente os ramos dela.

[[v23-27-11]]

^<<v23-27-11,11>>^ Quando os raminhos dela se tiverem secado, mulheres, entrando, [os] quebrarão, incendiando-os. Pois não é um povo de nítida compreensão. Por isso é que Aquele que o fez não lhe terá misericórdia, e seu próprio Formador não lhe mostrará favor.

[[v23-27-12]]

^<<v23-27-12,12>>^ E naquele dia terá de acontecer que Jeová abaterá [os frutos], desde o caudal do Rio^&#42;1^ até o vale da torrente do Egito, e assim vós mesmos sereis apanhados um após outro, ó filhos de Israel.

[NOTE]
====
. Isto é, o Eufrates.
====

[[v23-27-13]]

^<<v23-27-13,13>>^ E naquele dia terá de acontecer que se tocará uma grande buzina,^&#42;1^ e os que estiverem perecendo na terra da Assíria e os que estiverem dispersos na terra do Egito certamente chegarão e se curvarão diante de Jeová no santo monte em Jerusalém.

[NOTE]
====
. Ou “shofar”.
====

'''

xref:023-isaias/023-isaias-026.adoc#v23-26-0[&#60; Capítulo Anterior] | <<v23-27-0,Topo>> | xref:023-isaias/023-isaias-028.adoc#v23-28-0[Próximo Capítulo &#62;]