include::./index.adoc[]

[[v23-66-0]]
=== Isaías, 66
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v23-66-1]]

^<<v23-66-1,1>>^ Assim disse Jeová: “Os céus são o meu trono e a terra é o meu escabelo. Onde, então, está a casa que vós me podeis construir, e onde, então, é o lugar como lugar de descanso para mim?”

[[v23-66-2]]

^<<v23-66-2,2>>^ “Ora, todas estas coisas foram feitas pela minha própria mão, de modo que todas elas vieram a existir”,^&#42;1^ é a pronunciação de Jeová. “Olharei, pois, para este, para o atribulado e para o contrito no espírito e que treme da^&#42;2^ minha palavra.

[NOTE]
====
. “Vieram a existir”, MT; LXXSy: “são minhas”.
. “Treme da.” Ou “está ansioso para com”.
====

[[v23-66-3]]

^<<v23-66-3,3>>^ “Quem abate o touro é como quem golpeia um homem.^&#42;1^ Quem sacrifica o ovídeo é como quem quebra a nuca de um cão. Quem oferece um presente — sangue de porco! Quem apresenta uma recordação de olíbano é como quem diz uma bênção com palavras mágicas.^&#42;2^ Eles são também os que escolheram os seus próprios caminhos e a própria alma deles agradou-se das suas coisas repugnantes.

[NOTE]
====
. “Homem.” Hebr.: ’ish.
. Ou “sobre coisas mágicas”.
====

[[v23-66-4]]

^<<v23-66-4,4>>^ Eu mesmo, da minha parte, escolherei modos de maltratá-los; e trarei sobre eles as coisas que amedrontam; visto que eu chamei, mas não houve quem respondesse; falei, mas não houve quem escutasse; e eles continuaram a fazer o que era mau aos meus olhos e escolheram a coisa de que não me agradei.”

[[v23-66-5]]

^<<v23-66-5,5>>^ Ouvi a palavra de Jeová, vós os que tremeis da sua palavra: “Vossos irmãos que vos odeiam, que vos excluem por causa do meu nome, disseram: ‘Glorificado seja Jeová!’ Ele terá de aparecer também com alegria da vossa parte, e eles serão os envergonhados.”

[[v23-66-6]]

^<<v23-66-6,6>>^ Há o som de um rebuliço procedente da cidade, um som procedente do templo! É o som de Jeová retribuindo aos seus inimigos o que merecem.

[[v23-66-7]]

^<<v23-66-7,7>>^ Antes de começar a ter dores de parto, ela deu à luz. Antes de lhe chegarem as dores agudas ao dar à luz, teve o parto de um filho varão.

[[v23-66-8]]

^<<v23-66-8,8>>^ Quem é que já ouviu uma coisa destas? Quem é que já viu coisas como estas? Porventura será uma terra dada à luz com dores de parto num só dia? Ou nascerá uma nação de uma só vez?^&#42;1^ Pois Sião teve dores de parto bem como deu à luz seus filhos.

[NOTE]
====
. Ou: “a um só tempo?”
====

[[v23-66-9]]

^<<v23-66-9,9>>^ “Quanto a mim, acaso causaria o irrompimento e não faria que se desse à luz?” diz Jeová. “Ou causo eu o parto e realmente faço haver um fechamento?” disse o teu^&#42;1^ Deus.^&#42;2^

[NOTE]
====
. “Teu”, hebr. fem. sing., referindo-se a “Sião” ou “Jerusalém”.
. “Teu Deus.” Hebr.: ’Elo·há·yikh.
====

[[v23-66-10]]

^<<v23-66-10,10>>^ Alegrai-vos com Jerusalém e jubilai com ela, todos os que a amais. Exultai grandemente com ela, todos os que estais pranteando por ela,

[[v23-66-11]]

^<<v23-66-11,11>>^ visto que mamareis e certamente vos fartareis do peito de plena consolação por ela;^&#42;1^ visto que sorvereis e tereis deleite com a mama de sua glória.

[NOTE]
====
. Ou então “de suas consolações”.
====

[[v23-66-12]]

^<<v23-66-12,12>>^ Pois assim disse Jeová: “Eis que lhe estendo a paz como um rio e a glória de nações como torrente inundante, e vós haveis de mamar. Sobre o lado sereis carregados e sobre os joelhos sereis afagados.

[[v23-66-13]]

^<<v23-66-13,13>>^ Como a um homem^&#42;1^ a quem a sua própria mãe está consolando, assim eu mesmo continuarei a consolar-vos; e no caso de Jerusalém, sereis consolados.

[NOTE]
====
. “Como a um homem.” Hebr.: ke’ísh.
====

[[v23-66-14]]

^<<v23-66-14,14>>^ E certamente vereis, e vosso coração forçosamente exultará, e os vossos próprios ossos florescerão como a tenra relva. E a mão de Jeová há de ser dada a conhecer aos seus servos, mas ele verberará realmente os seus inimigos.”

[[v23-66-15]]

^<<v23-66-15,15>>^ “Pois eis que Jeová mesmo chega como o próprio fogo, e seus carros são como um tufão, a fim de pagar de volta a sua ira com puro furor e sua censura com chamas de fogo.

[[v23-66-16]]

^<<v23-66-16,16>>^ Pois, como fogo, o próprio Jeová, de fato, encetará a controvérsia, sim, com a sua espada, contra toda a carne; e os mortos de Jeová tornar-se-ão certamente muitos.

[[v23-66-17]]

^<<v23-66-17,17>>^ Os que se santificam e purificam para os jardins, atrás de um^&#42;1^ no centro, comendo carne de porco e aquilo que é repugnante, até mesmo o roedor saltante,^&#42;2^ chegarão todos juntos ao seu término”, é a pronunciação de Jeová.

[NOTE]
====
. “Um”, hebr. masc. no M, mas fem. no Mmargem e em 13 mss. hebr.
. Ou “o gerbo”.
====

[[v23-66-18]]

^<<v23-66-18,18>>^ “E quanto aos seus trabalhos e seus pensamentos, estou chegando para reunir todas as nações e línguas; e terão de chegar e ver a minha glória.”

[[v23-66-19]]

^<<v23-66-19,19>>^ “E eu vou pôr entre eles um sinal^&#42;1^ e vou enviar alguns dos que escaparam às nações, [a] Társis, Pul^&#42;2^ e Lude, os que entesam o arco,^&#42;3^ Tubal e Javã, as ilhas^&#42;4^ longínquas, que não ouviram notícias sobre mim nem viram a minha glória; e por certo contarão a minha glória entre as nações.

[NOTE]
====
. “Sinal.” Hebr.: ’ohth; lat.: sí·gnum.
. “Pul”, 1QIsaMSy; LXX: “Pute”.
. “Os que entesam o arco”, 1QIsaMSy; LXX: “Meseque”.
. Ou “litorais”.
====

[[v23-66-20]]

^<<v23-66-20,20>>^ E realmente trarão todos os vossos irmãos dentre todas as nações como presente a Jeová, em cavalos e em carros, e em carroças cobertas, e em mulos, e em velozes fêmeas de camelo, ao meu santo monte,^&#42;1^ Jerusalém”, disse Jeová, “assim como quando os filhos de Israel trazem o presente num vaso limpo à casa de Jeová”.

[NOTE]
====
. “Monte”, 1QIsaMTSyVg; LXX: “cidade”.
====

[[v23-66-21]]

^<<v23-66-21,21>>^ “E dentre eles tirarei também alguns para os sacerdotes, para os levitas”,^&#42;1^ disse Jeová.

[NOTE]
====
. “Para os levitas”, 1QIsaM; TLXXSyVg e alguns mss. hebr.: “e para os levitas”.
====

[[v23-66-22]]

^<<v23-66-22,22>>^ “Pois assim como os novos céus e a nova terra que eu faço estão postos diante de mim”, é a pronunciação de Jeová, “assim ficarão postos a vossa descendência^&#42;1^ e o vosso nome”.

[NOTE]
====
. Lit.: “semente”.
====

[[v23-66-23]]

^<<v23-66-23,23>>^ “E há de acontecer que de lua nova a lua nova^&#42;1^ e de sábado a sábado^&#42;2^ chegará a mim toda a carne para se curvar diante de mim”, disse Jeová.

[NOTE]
====
. Ou “de mês em mês”.
. Ou “de semana em semana”.
====

[[v23-66-24]]

^<<v23-66-24,24>>^ “E realmente sairão e olharão para os cadáveres dos homens^&#42;1^ que transgrediram contra mim; pois os próprios vermes sobre eles^&#42;2^ não morrerão e o próprio fogo deles não se apagará, e terão de tornar-se algo repulsivo para toda a carne.”

[NOTE]
====
. “Dos homens.” Hebr.: ha·’ana·shím, pl. de ’ish.
. Lit.: “seu próprio verme”.
====

'''

xref:023-isaias/023-isaias-065.adoc#v23-65-0[&#60; Capítulo Anterior] | <<v23-66-0,Topo>> | xref:024-jeremias/024-jeremias-001.adoc#v24-1-0[Próximo Capítulo &#62;]