include::./index.adoc[]

[[v23-19-0]]
=== Isaías, 19
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v23-19-1]]

^<<v23-19-1,1>>^ A pronúncia contra o Egito: Eis que Jeová está cavalgando numa nuvem veloz e está entrando no Egito! E os deuses que nada valem, do Egito, certamente estremecerão por causa dele, e o próprio coração do Egito se derreterá no seu íntimo.

[[v23-19-2]]

^<<v23-19-2,2>>^ “E eu vou incitar egípcios contra egípcios, e certamente guerrearão cada um contra o seu irmão e cada um contra o seu companheiro, cidade contra cidade, reino contra reino.

[[v23-19-3]]

^<<v23-19-3,3>>^ E o espírito do Egito terá de ficar desnorteado no meio dele, e confundirei seu próprio conselho. E por certo hão de recorrer aos deuses que nada valem, e aos encantadores, e aos médiuns espíritas,^&#42;1^ e aos prognosticadores profissionais de eventos.

[NOTE]
====
. “Médiuns espíritas.” Agentes usados como instrumentos de um demônio de adivinhação. Lat.: py·thó·nes. Veja At 16:16.
====

[[v23-19-4]]

^<<v23-19-4,4>>^ E eu vou entregar o Egito na mão de um amo^&#42;1^ duro, e será forte o rei que dominará sobre eles”, é a pronunciação do [verdadeiro] Senhor,^&#42;2^ Jeová dos exércitos.

[NOTE]
====
. “Amo.” Hebr.: ’adho·ním, pl. de ’a·dhóhn, para denotar majestade, modificado pelo adjetivo hebr. sing. “duro”.
. Veja Ap. 1H.
====

[[v23-19-5]]

^<<v23-19-5,5>>^ E há de secar-se a água do mar, e o próprio rio ficará árido e realmente se secará.

[[v23-19-6]]

^<<v23-19-6,6>>^ E os rios terão de exalar mau cheiro; os canais do Nilo do Egito^&#42;1^ terão de ficar rasos e áridos. A própria cana e o junco terão de esboroar-se.^&#42;2^

[NOTE]
====
. “Egito.” Hebr.: Ma·tsóhr.
. Ou “terão de ser tomados por piolhos”.
====

[[v23-19-7]]

^<<v23-19-7,7>>^ Os lugares escalvados^&#42;1^ junto ao rio Nilo, na desembocadura do rio Nilo, e toda terra de sementeira do rio Nilo secar-se-á. Há de ser levada para longe e não existirá mais.

[NOTE]
====
. Ou: “Os juncos.”
====

[[v23-19-8]]

^<<v23-19-8,8>>^ E os pescadores terão de estar de luto, e todos os que lançam anzóis ao rio Nilo terão de expressar tristeza, e mesmo os que estendem redes de pesca sobre a superfície da água realmente se definharão.

[[v23-19-9]]

^<<v23-19-9,9>>^ Os que trabalham em linho cardado terão de ficar envergonhados; também os tecedores de tecidos brancos.

[[v23-19-10]]

^<<v23-19-10,10>>^ E seus tecelões terão de ficar esmigalhados, todos os trabalhadores assalariados, de alma pesarosa.

[[v23-19-11]]

^<<v23-19-11,11>>^ Os príncipes de Zoã são deveras tolos. Quanto aos sábios dos conselheiros de Faraó, [seu] conselho é algo desarrazoado. Como direis vós a Faraó: “Sou filho de sábios, filho de reis de outrora”?

[[v23-19-12]]

^<<v23-19-12,12>>^ Então, onde é que estão — os vossos sábios — para que te informem, pois, e para que saibam que Jeová dos exércitos deu conselho a respeito do Egito?^&#42;1^

[NOTE]
====
. “Egito.” Hebr.: Mits·rá·yim.
====

[[v23-19-13]]

^<<v23-19-13,13>>^ Os príncipes de Zoã agiram tolamente, os príncipes de Nofe^&#42;1^ foram enganados, os homens-chave das suas tribos fizeram o Egito andar vagueando.

[NOTE]
====
. Ou “Mênfis”.
====

[[v23-19-14]]

^<<v23-19-14,14>>^ O próprio Jeová misturou no meio da sua [terra]^&#42;1^ o espírito de desorientação; e eles fizeram o Egito andar vagueando em todo o seu trabalho, assim como se faz um bêbedo vaguear no seu vômito.

[NOTE]
====
. Lit.: “dela”, evidentemente referindo-se à terra, hebr. fem.; LXX: “delas”.
====

[[v23-19-15]]

^<<v23-19-15,15>>^ E o Egito não virá a ter qualquer trabalho que possa ser feito pela cabeça ou pela cauda, pelo broto ou pelo junco.

[[v23-19-16]]

^<<v23-19-16,16>>^ Naquele dia, o Egito tornar-se-á quais mulheres, e certamente tremerá e estará apavorado por causa da sacudida da mão de Jeová dos exércitos, que este está sacudindo contra ele.

[[v23-19-17]]

^<<v23-19-17,17>>^ E o solo de Judá terá de tornar-se para o Egito causa de rodopiar. Todo aquele a quem é mencionado^&#42;1^ está apavorado por causa do conselho de Jeová dos exércitos, que este está aconselhando contra ele.

[NOTE]
====
. Referindo-se ao “solo”.
====

[[v23-19-18]]

^<<v23-19-18,18>>^ Naquele dia virá a haver cinco cidades na terra do Egito, falando o idioma de Canaã e jurando a Jeová dos exércitos. Cidade de Derrubamento^&#42;1^ se chamará uma [cidade].

[NOTE]
====
. “Derrubamento.” M(hebr.): ha·Hé·res; 1QIsa(hebr.): ha·Hhé·res, “o Sol”; sir.: He·res; lat.: Só·lis, “(do) Sol”; gr.: A·se·dék, transliteração da palavra hebr. hats·tsé·dheq, “a justiça”. (Veja Gins.Int, pp. 406, 407.) T parafraseia isso para rezar: “(Cidade de) a Casa do Sol, que há de ser destruída.”
====

[[v23-19-19]]

^<<v23-19-19,19>>^ Naquele dia virá a haver um altar a Jeová no meio da terra do Egito, e uma coluna a Jeová ao lado do seu termo.

[[v23-19-20]]

^<<v23-19-20,20>>^ E terá de mostrar ser como sinal e como testemunha para Jeová dos exércitos na terra do Egito; pois clamarão a Jeová por causa dos opressores, e ele lhes enviará um salvador, sim, alguém grandioso, que^&#42;1^ realmente os livrará.

[NOTE]
====
. Ou “e”; ou: “e ele”.
====

[[v23-19-21]]

^<<v23-19-21,21>>^ E Jeová certamente se tornará conhecido aos egípcios; e os egípcios terão de conhecer a Jeová naquele dia, e terão de oferecer sacrifício e presente, e terão de fazer um voto a Jeová e pagá-lo.

[[v23-19-22]]

^<<v23-19-22,22>>^ E Jeová certamente ferirá o Egito. Ferir-se-á e curar-se-á;^&#42;1^ e terão de retornar a Jeová, e terá de deixar-se suplicar por eles e terá de curá-los.

[NOTE]
====
. Ou “ferir o Egito, ferindo[-o] e curando[-o]”. No hebr., estes dois últimos verbos estão no infinitivo absoluto, indefinidos quanto ao tempo e impessoais.
====

[[v23-19-23]]

^<<v23-19-23,23>>^ Naquele dia virá a haver uma estrada principal saindo do Egito para a Assíria, e a Assíria entrará realmente no Egito, e o Egito na Assíria; e certamente prestarão serviço, o Egito com a Assíria.

[[v23-19-24]]

^<<v23-19-24,24>>^ Naquele dia, Israel virá a ser o terceiro, junto com o Egito e com a Assíria, a saber, uma bênção no meio da terra,^&#42;1^

[NOTE]
====
. “Da terra.” Hebr.: ha·’á·rets.
====

[[v23-19-25]]

^<<v23-19-25,25>>^ porque Jeová dos exércitos o terá abençoado, dizendo: “Bendito seja meu povo, o Egito, e o trabalho das minhas mãos, a Assíria, e minha herança, Israel.”

'''

xref:023-isaias/023-isaias-018.adoc#v23-18-0[&#60; Capítulo Anterior] | <<v23-19-0,Topo>> | xref:023-isaias/023-isaias-020.adoc#v23-20-0[Próximo Capítulo &#62;]