include::./index.adoc[]

[[v23-50-0]]
=== Isaías, 50
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v23-50-1]]

^<<v23-50-1,1>>^ Assim disse Jeová: “Onde está então o certificado de divórcio da vossa mãe, que eu mandei embora? Ou a qual dos meus credores foi que vos vendi? Eis que fostes vendidos por causa dos vossos próprios erros e vossa mãe foi mandada embora por causa das vossas próprias transgressões.

[[v23-50-2]]

^<<v23-50-2,2>>^ Por que é que não havia ninguém^&#42;1^ quando entrei? Quando chamei, não havia quem respondesse? Acaso ficou a minha mão de fato tão curta que não possa remir, ou não há em mim poder para livrar? Eis que com a minha censura seco o mar; faço de rios um ermo. Seus peixes cheiram mal por não haver água e morrem de sede.

[NOTE]
====
. Ou “homem”. Hebr.: ’ish.
====

[[v23-50-3]]

^<<v23-50-3,3>>^ Visto os céus de negrume e faço da própria serapilheira sua cobertura.”

[[v23-50-4]]

^<<v23-50-4,4>>^ O próprio Soberano Senhor Jeová me deu a língua dos instruídos,^&#42;1^ para que eu soubesse responder ao cansado com uma palavra. Ele me desperta de manhã em manhã; desperta-me o ouvido para ouvir como os instruídos.

[NOTE]
====
. Ou “dos discípulos (seguidores)”.
====

[[v23-50-5]]

^<<v23-50-5,5>>^ O próprio Soberano Senhor Jeová me abriu o ouvido, e eu, da minha parte, não fui rebelde. Não me virei na direção oposta.

[[v23-50-6]]

^<<v23-50-6,6>>^ Dei as minhas costas aos que golpeavam e as minhas faces aos que arrancavam [o cabelo]. Não escondi a minha face de coisas humilhantes^&#42;1^ e do escarro.

[NOTE]
====
. Ou “de insultos”.
====

[[v23-50-7]]

^<<v23-50-7,7>>^ Mas o próprio Soberano Senhor Jeová me ajudará. Por isso não terei de sentir-me humilhado. Por isso fiz a minha face como pederneira e sei que não serei envergonhado.

[[v23-50-8]]

^<<v23-50-8,8>>^ Está perto Aquele que me declara justo.^&#42;1^ Quem pode contender comigo? Fiquemos juntos de pé. Quem é meu adversário em juízo?^&#42;2^ Aproxime-se ele de mim.

[NOTE]
====
. Ou “me pronuncia inocente”.
. “Meu adversário em juízo.” Lit.: “o dono [hebr.: vá·‛al, de bá·‛al] do meu julgamento”.
====

[[v23-50-9]]

^<<v23-50-9,9>>^ Eis que o próprio Soberano Senhor Jeová me ajudará. Quem é que me pode pronunciar iníquo?^&#42;1^ Eis que todos eles se gastarão iguais a uma veste. A mera traça os consumirá.

[NOTE]
====
. Ou: “me pode condenar?”
====

[[v23-50-10]]

^<<v23-50-10,10>>^ Quem dentre vós está em temor de Jeová, escutando a voz de seu servo, que tenha andado em contínua escuridão e para quem não tenha havido nenhuma claridade? Confie ele no nome de Jeová e estribe-se ele em seu Deus.^&#42;1^

[NOTE]
====
. “Em seu Deus.” Hebr.: bE’·lo·háv.
====

[[v23-50-11]]

^<<v23-50-11,11>>^ “Eis que todos vós os que acendeis um fogo, fazendo faíscas luzir,^&#42;1^ andais na luz do vosso fogo e entre as faíscas que acendestes. Certamente vireis a ter da minha mão o seguinte: Deitar-vos-eis em pura dor.

[NOTE]
====
. Mediante uma correção; lit.: “cingindo-se bem das faíscas (flechas ardentes)”.
====

'''

xref:023-isaias/023-isaias-049.adoc#v23-49-0[&#60; Capítulo Anterior] | <<v23-50-0,Topo>> | xref:023-isaias/023-isaias-051.adoc#v23-51-0[Próximo Capítulo &#62;]