include::./index.adoc[]

[[v23-26-0]]
=== Isaías, 26
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v23-26-1]]

^<<v23-26-1,1>>^ Naquele dia se cantará este cântico na terra de Judá: “Temos uma cidade forte. Ele põe a própria salvação por muralha e por escarpa.

[[v23-26-2]]

^<<v23-26-2,2>>^ Abri os portões, para que entre a nação justa que mantém uma conduta fiel.

[[v23-26-3]]

^<<v23-26-3,3>>^ Resguardarás em contínua paz^&#42;1^ a inclinação bem firmada,^&#42;2^ porque é em ti que se faz a pessoa^&#42;3^ confiar.

[NOTE]
====
. Lit.: “[em] paz, paz”.
. Ou “inabalável”.
. Ou “isso”.
====

[[v23-26-4]]

^<<v23-26-4,4>>^ Confiai em Jeová para todo o sempre, pois em Jah^&#42;1^ Jeová^&#42;2^ está a Rocha dos tempos indefinidos.

[NOTE]
====
. Veja 12:2 n.: “Jah”.
. “Em Jah Jeová.” Hebr.: beYáh Yehwáh. Veja 12:2 n.: “Jeová”.
====

[[v23-26-5]]

^<<v23-26-5,5>>^ “Pois ele pôs abaixo os que habitavam na altura, na vila elevada. Ele a rebaixa, ele a rebaixa até a terra; ele a traz em contato com o pó.

[[v23-26-6]]

^<<v23-26-6,6>>^ O pé a pisará, os pés do atribulado, as pisadas dos de condição humilde.”

[[v23-26-7]]

^<<v23-26-7,7>>^ A vereda do justo é retidão. Sendo tu reto, aplainarás o próprio rumo do justo.

[[v23-26-8]]

^<<v23-26-8,8>>^ Sim, pela vereda dos teus julgamentos, ó Jeová, temos esperado em ti. O desejo da alma tem sido por teu nome e por tua recordação.

[[v23-26-9]]

^<<v23-26-9,9>>^ Almejei-te com a minha alma durante a noite; sim, com o meu espírito dentro de mim estou à procura de ti; porque, quando há julgamentos teus para a terra, os habitantes do solo produtivo^&#42;1^ certamente aprenderão a justiça.

[NOTE]
====
. Veja 13:11 n.: “produtivo”.
====

[[v23-26-10]]

^<<v23-26-10,10>>^ Ainda que se mostre favor ao iníquo, ele simplesmente não aprenderá a justiça. Na terra da direiteza ele agirá injustamente e não verá a alteza de Jeová.

[[v23-26-11]]

^<<v23-26-11,11>>^ Ó Jeová, tua mão ficou elevada, [mas] eles não [a] observam. Observarão e ficarão envergonhados diante do zelo pelo [teu] povo. Sim, o fogo para os teus próprios adversários é que os consumirá.^&#42;1^

[NOTE]
====
. “E agora o fogo consumirá os que estão em oposição”, LXX. Veja He 10:27.
====

[[v23-26-12]]

^<<v23-26-12,12>>^ Ó Jeová, tu nos determinarás judicialmente a paz, porque realizaste para nós até mesmo todos os nossos trabalhos.

[[v23-26-13]]

^<<v23-26-13,13>>^ Ó Jeová, nosso Deus,^&#42;1^ outros amos,^&#42;2^ além de ti, têm agido como donos de nós. Somente por ti faremos menção de teu nome.

[NOTE]
====
. “Nosso Deus.” Hebr.: ’Elo·héh·nu, pl.
. “Amos.” Hebr.: ’adho·ním, pl. de ’a·dhóhn.
====

[[v23-26-14]]

^<<v23-26-14,14>>^ Eles estão mortos; não viverão. Impotentes na morte,^&#42;1^ não se levantarão. Por isso voltaste a tua atenção para os aniquilares e para destruíres toda menção deles.

[NOTE]
====
. “Impotentes na morte.” Hebr.: refa·’ím; Vg: “gigantes”.
====

[[v23-26-15]]

^<<v23-26-15,15>>^ Acrescentaste à nação; ó Jeová, acrescentaste à nação; glorificaste-te a ti mesmo. Estendeste para longe todos os limites da terra.^&#42;1^

[NOTE]
====
. “Terra.” Hebr.: ’á·rets.
====

[[v23-26-16]]

^<<v23-26-16,16>>^ Ó Jeová, durante a aflição, voltaram para ti a sua atenção; despejaram um murmúrio [de orações] quando receberam a tua disciplina.

[[v23-26-17]]

^<<v23-26-17,17>>^ Assim como a mulher grávida se chega para dar à luz, tem dores de parto, grita nas suas dores agudas ao dar à luz, assim nos tornamos nós por tua causa, ó Jeová.

[[v23-26-18]]

^<<v23-26-18,18>>^ Ficamos em gravidez, tivemos dores de parto; é como se tivéssemos dado à luz o vento.^&#42;1^ Não conseguimos nenhuma salvação real no que se refere à terra, e nenhuns habitantes para o solo produtivo passam a [nascer].

[NOTE]
====
. “Vento.” Hebr.: rú·ahh. Veja Gên 1:2 n.: “ativa”.
====

[[v23-26-19]]

^<<v23-26-19,19>>^ “Os teus mortos viverão. Um cadáver meu^&#42;1^ — eles se levantarão. Acordai e gritai de júbilo, os que residis no pó! Pois o teu orvalho é como o orvalho das malvas, e a própria terra deixará [nascer] mesmo os impotentes na morte.^&#42;2^

[NOTE]
====
. “Um cadáver meu.” Hebr.: neve·la·thí, sing., mas provavelmente em sentido coletivo: “Cadáveres meus”; LXX: “Os [que estão] nos túmulos memoriais”; Vg: “Meus [que foram] mortos.”
. Veja v. 14 n.
====

[[v23-26-20]]

^<<v23-26-20,20>>^ “Vai, povo meu, entra nos teus quartos interiores e fecha as tuas portas atrás de ti. Esconde-te por um instante, até que passe a verberação.

[[v23-26-21]]

^<<v23-26-21,21>>^ Pois, eis que Jeová está saindo do seu lugar para ajustar contas pelo erro do habitante da terra contra ele, e a terra certamente exporá seu derramamento de sangue^&#42;1^ e não mais encobrirá os seus que foram mortos.”

[NOTE]
====
. Lit.: “sangues”.
====

'''

xref:023-isaias/023-isaias-025.adoc#v23-25-0[&#60; Capítulo Anterior] | <<v23-26-0,Topo>> | xref:023-isaias/023-isaias-027.adoc#v23-27-0[Próximo Capítulo &#62;]