include::./index.adoc[]

[[v23-59-0]]
=== Isaías, 59
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v23-59-1]]

^<<v23-59-1,1>>^ Eis que a mão de Jeová não ficou tão curta que não possa salvar, nem ficou seu ouvido tão pesado que não possa ouvir.

[[v23-59-2]]

^<<v23-59-2,2>>^ Não, mas os vossos próprios erros tornaram-se as coisas que causam separação entre vós e vosso Deus,^&#42;1^ e os vossos próprios pecados fizeram que escondesse de vós a [sua] face para não ouvir.

[NOTE]
====
. “Vosso Deus.” Hebr.: ’Elo·heh·khém.
====

[[v23-59-3]]

^<<v23-59-3,3>>^ Pois as palmas das vossas próprias mãos ficaram poluídas com sangue, e os vossos dedos, com erro. Vossos próprios lábios falaram falsidade. Vossa própria língua tem murmurado pura injustiça.

[[v23-59-4]]

^<<v23-59-4,4>>^ Não há quem clame em justiça e absolutamente ninguém foi a juízo em fidelidade. Confiava-se na irrealidade e falava-se futilidade. Concebia-se desgraça e dava-se à luz o que é prejudicial.

[[v23-59-5]]

^<<v23-59-5,5>>^ Ovos duma cobra venenosa é o que eles chocaram e estavam tecendo a mera teia duma aranha. Qualquer que comia dos seus ovos morria e o [ovo] esmagado era chocado para resultar numa víbora.

[[v23-59-6]]

^<<v23-59-6,6>>^ A mera teia deles não servirá de roupa, nem se cobrirão eles com os seus trabalhos. Seus trabalhos são trabalhos prejudiciais e há atividade de violência nas palmas das suas mãos.

[[v23-59-7]]

^<<v23-59-7,7>>^ Seus próprios pés estão correndo para a pura maldade e eles se apressam a derramar sangue inocente. Seus pensamentos são pensamentos prejudiciais; a assolação e o desmoronamento estão nas suas estradas principais.^&#42;1^

[NOTE]
====
. “A assolação e o desmoronamento estão nas suas estradas principais”, M; LXX: “ruína e miséria estão nos seus caminhos”. Veja Ro 3:16.
====

[[v23-59-8]]

^<<v23-59-8,8>>^ Desconheceram o caminho da paz e não há juízo nos seus trilhos. Suas sendas eles perverteram para si mesmos. Absolutamente ninguém que pisar nelas^&#42;1^ conhecerá realmente a paz.

[NOTE]
====
. “Nelas”, TSyVgc e um ms. hebr.; 1QIsaM: “nela”.
====

[[v23-59-9]]

^<<v23-59-9,9>>^ Por isso é que o juízo ficou longe de nós e a justiça não nos alcança. Continuamos a esperar luz, mas eis a escuridão; a claridade, [mas] estávamos andando em contínuas trevas.

[[v23-59-10]]

^<<v23-59-10,10>>^ Continuamos a tatear pelo muro assim como os cegos e prosseguimos tateando como os que não têm olhos. Tropeçamos ao meio-dia como no crepúsculo vespertino; entre os robustos [somos] como mortos.

[[v23-59-11]]

^<<v23-59-11,11>>^ Estamos gemendo, todos nós, assim como ursos; e como pombas arrulhamos em lamento. Esperávamos o juízo, mas não havia nenhum; a salvação, [mas] ela ficou longe de nós.

[[v23-59-12]]

^<<v23-59-12,12>>^ Pois as nossas revoltas tornaram-se muitas diante de ti; e quanto aos nossos pecados, cada um testificou contra nós. Porque as nossas revoltas estão conosco; e quanto aos nossos erros, conhecemo-los bem.

[[v23-59-13]]

^<<v23-59-13,13>>^ Houve transgressão e renegação de Jeová; e recuou-se de nosso Deus,^&#42;1^ falando-se de opressão e de revolta, concebendo-se e murmurando-se palavras de falsidade procedentes do próprio coração.

[NOTE]
====
. “Nosso Deus.” Hebr.: ’Elo·héh·nu.
====

[[v23-59-14]]

^<<v23-59-14,14>>^ E o juízo foi forçado a recuar e a própria justiça ficou simplesmente parada de longe. Pois a verdade tropeçou mesmo na praça pública, e aquilo que é direito não pode entrar.

[[v23-59-15]]

^<<v23-59-15,15>>^ E a verdade mostra estar faltando, e quem se desvia da maldade está sendo despojado.
E Jeová chegou a ver [isso], e era mau aos seus olhos que não havia juízo.

[[v23-59-16]]

^<<v23-59-16,16>>^ E quando viu que não havia homem,^&#42;1^ começou a mostrar-se espantado que não havia quem intercedesse. E seu braço passou a salvá-lo e sua própria justiça era o que o sustentava.

[NOTE]
====
. “Homem.” Hebr.: ’ish.
====

[[v23-59-17]]

^<<v23-59-17,17>>^ Então vestiu a justiça qual cota de malha e [pôs] o capacete de salvação na cabeça. Além disso, trajou as vestes da vingança qual vestimenta e envolveu-se no zelo como se fosse uma túnica sem mangas.

[[v23-59-18]]

^<<v23-59-18,18>>^ De acordo com as ações, retribuirá correspondentemente: furor aos seus adversários, o tratamento devido aos seus inimigos. Retribuirá às ilhas^&#42;1^ o tratamento devido.

[NOTE]
====
. Ou “aos litorais”.
====

[[v23-59-19]]

^<<v23-59-19,19>>^ E começarão a temer o nome de Jeová desde o poente e a glória dele desde o nascente do sol, pois ele chegará como um rio de aflição,^&#42;1^ impelido pelo próprio espírito^&#42;2^ de Jeová.

[NOTE]
====
. Ou “a aflição chegará como um rio”.
. Ou “vento; sopro”. Veja Gên 1:2 n.: “ativa”.
====

[[v23-59-20]]

^<<v23-59-20,20>>^ “E o Resgatador certamente chegará a Sião e aos que recuam da transgressão^&#42;1^ em Jacó”, é a pronunciação de Jeová.

[NOTE]
====
. “E aos que recuam da transgressão”, MVg; LXX: “e ele desviará as práticas ímpias”; Sy: “e aos que desviam a injustiça”.
====

[[v23-59-21]]

^<<v23-59-21,21>>^ “E quanto a mim, é este o meu pacto com eles”, disse Jeová.
“Meu espírito que está sobre ti^&#42;1^ e minhas palavras que pus na tua boca — não se removerão da tua boca, nem da boca da tua descendência,^&#42;2^ nem da boca da descendência da tua descendência”, disse Jeová, “desde agora e por tempo indefinido”.

[NOTE]
====
. “Ti”, hebr. masc. sing.
. Lit.: “semente”.
====

'''

xref:023-isaias/023-isaias-058.adoc#v23-58-0[&#60; Capítulo Anterior] | <<v23-59-0,Topo>> | xref:023-isaias/023-isaias-060.adoc#v23-60-0[Próximo Capítulo &#62;]