include::./index.adoc[]

[[v23-54-0]]
=== Isaías, 54
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v23-54-1]]

^<<v23-54-1,1>>^ “Grita de júbilo, ó mulher estéril que não deste à luz! Fica animada com clamor jubilante e grita estridentemente, tu que não tiveste dores de parto, porque os filhos da desolada são mais numerosos do que os filhos da mulher que tem um dono marital”, disse Jeová.

[[v23-54-2]]

^<<v23-54-2,2>>^ “Faze mais espaçoso o lugar da tua tenda. E estendam-se^&#42;1^ os panos de tenda do teu grandioso tabernáculo.^&#42;2^ Não te refreies. Alonga os teus cordões de tenda e faze fortes as tuas estacas de tenda.

[NOTE]
====
. “Estendam-se”, M; 1QIsa: “estenda-se ela”; LXXSyVg: “estende”.
. “Grandioso tabernáculo.” Lit.: “tabernáculos”, pl., evidentemente para denotar grandiosidade.
====

[[v23-54-3]]

^<<v23-54-3,3>>^ Pois irromperás pela direita e pela esquerda, e tua própria descendência^&#42;1^ tomará posse até mesmo de nações, e eles habitarão até mesmo nas cidades desoladas.

[NOTE]
====
. Lit.: “semente”.
====

[[v23-54-4]]

^<<v23-54-4,4>>^ Não tenhas medo, pois não serás envergonhada; e não te sintas humilhada, pois não ficarás desapontada. Porque te esquecerás até mesmo da vergonha do teu tempo de juventude e não te lembrarás mais do vitupério da tua contínua viuvez.”^&#42;1^

[NOTE]
====
. “Tua contínua viuvez.” Lit.: “tuas viuvezes”, pl., para denotar prolongamento.
====

[[v23-54-5]]

^<<v23-54-5,5>>^ “Pois o Grandioso que te fez^&#42;1^ é teu dono marital,^&#42;2^ cujo nome é Jeová dos exércitos; e o Santo de Israel é teu Resgatador. Será chamado de Deus de toda a terra.^&#42;3^

[NOTE]
====
. “O Grandioso que . . . fez.” Lit.: “fazedores”, pl., para denotar grandiosidade ou excelência.
. “Dono marital”, pl. no M, para denotar grandiosidade ou excelência, em harmonia com “Grandioso que . . . fez”.
. “Deus de toda a terra.” Hebr.: ’Elo·héh khol-ha·’á·rets.
====

[[v23-54-6]]

^<<v23-54-6,6>>^ Porque Jeová te chamou como se fosses uma esposa^&#42;1^ completamente abandonada e de espírito magoado, e como esposa do tempo da mocidade, que então foi rejeitada”, disse o teu Deus.

[NOTE]
====
. Ou “como se fosses uma mulher”. Hebr.: khe’ish·sháh.
====

[[v23-54-7]]

^<<v23-54-7,7>>^ “Por um pequeno instante^&#42;1^ te abandonei completamente, mas com grandes misericórdias te reunirei.

[NOTE]
====
. “Por um pequeno instante”, MLXXVg; TSy: “Com um pouco de ira.”
====

[[v23-54-8]]

^<<v23-54-8,8>>^ Numa onda de indignação escondi de ti a minha face apenas por um instante, mas vou ter misericórdia de ti com benevolência^&#42;1^ por tempo indefinido”, disse teu Resgatador, Jeová.

[NOTE]
====
. Ou “mas . . . com amor leal”. Hebr.: u·vehhé·sedh.
====

[[v23-54-9]]

^<<v23-54-9,9>>^ “Isto é para mim como os dias de Noé. Assim como jurei que as águas de Noé não mais passariam sobre a terra, assim jurei que não vou ficar indignado contigo nem vou censurar-te.

[[v23-54-10]]

^<<v23-54-10,10>>^ Pois os próprios montes podem ser removidos e os próprios morros podem ser abalados, mas a minha benevolência é que não será removida de ti, nem tampouco será abalado o meu pacto de paz”, disse Jeová, Aquele que tem misericórdia de ti.

[[v23-54-11]]

^<<v23-54-11,11>>^ “Ó mulher atribulada, sacudida pela tormenta, não consolada, eis que assento as tuas pedras com argamassa dura e vou lançar teu alicerce com safiras.

[[v23-54-12]]

^<<v23-54-12,12>>^ E eu vou fazer as tuas ameias de rubis e teus portões de pedras fulgurosas, e todos os teus termos de pedras agradáveis.

[[v23-54-13]]

^<<v23-54-13,13>>^ E todos os teus filhos serão pessoas ensinadas^&#42;1^ por Jeová e a paz de teus filhos será abundante.

[NOTE]
====
. Ou “serão discípulos”. Veja 8:16 n.: “discípulos”.
====

[[v23-54-14]]

^<<v23-54-14,14>>^ Mostrar-te-ás firmemente estabelecida na própria justiça. Estarás longe^&#42;1^ da opressão — pois não temerás a ninguém — e daquilo que aterroriza, porque não se chegará a ti.

[NOTE]
====
. Lit.: “Fica longe!” Imperativo.
====

[[v23-54-15]]

^<<v23-54-15,15>>^ Se é que alguém fizer um ataque, não será às minhas ordens. Quem fizer um ataque contra ti cairá mesmo por tua causa.”

[[v23-54-16]]

^<<v23-54-16,16>>^ “Eis que eu mesmo criei o artífice, aquele que sopra o fogo de carvão de lenha e produz uma arma como sua feitura. Eu mesmo, também, criei o homem ruinoso para trabalho de demolição.

[[v23-54-17]]

^<<v23-54-17,17>>^ Nenhuma arma que se forjar contra ti será bem sucedida, e condenarás^&#42;1^ toda e qualquer língua que se levantar contra ti em julgamento. Esta é a propriedade hereditária dos servos de Jeová, e sua justiça procede de mim”, é a pronunciação de Jeová.

[NOTE]
====
. Ou “pronunciarás iníqua (culpada)”.
====

'''

xref:023-isaias/023-isaias-053.adoc#v23-53-0[&#60; Capítulo Anterior] | <<v23-54-0,Topo>> | xref:023-isaias/023-isaias-055.adoc#v23-55-0[Próximo Capítulo &#62;]