include::./index.adoc[]

[[v23-45-0]]
=== Isaías, 45
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v23-45-1]]

^<<v23-45-1,1>>^ Assim disse Jeová ao seu ungido,^&#42;1^ a Ciro,^&#42;2^ cuja direita tomei para sujeitar diante dele nações, a fim de eu descingir até mesmo os quadris de reis; para abrir diante dele as portas duplas, de modo que nem mesmo os portões se fecharão:

[NOTE]
====
. “Ao seu ungido.” Hebr.: lim·shi·hhóh; gr.: khri·stoí; sir.: lam·shi·hheh; lat. chrí·sto.
. “A Ciro”, M(hebr.: leKhóh·resh)TLXXVg.
====

[[v23-45-2]]

^<<v23-45-2,2>>^ “Eu mesmo irei na tua frente e endireitarei as ondulações do terreno. Destroçarei as portas de cobre e cortarei as trancas de ferro.

[[v23-45-3]]

^<<v23-45-3,3>>^ E vou dar-te os tesouros na escuridão e os tesouros escondidos nos esconderijos, para que saibas que eu sou Jeová, Aquele que [te] chama por teu nome, o Deus^&#42;1^ de Israel.

[NOTE]
====
. “O Deus de.” Hebr.: ’Elo·héh.
====

[[v23-45-4]]

^<<v23-45-4,4>>^ Por causa do meu servo Jacó e de Israel, meu escolhido, passei mesmo a chamar-te pelo teu nome; passei a dar-te um nome honorífico, embora não me conhecesses.

[[v23-45-5]]

^<<v23-45-5,5>>^ Eu sou Jeová, e não há outro. Além de mim não há Deus. Cingir-te-ei bem, embora não me conhecesses,

[[v23-45-6]]

^<<v23-45-6,6>>^ para que pessoas desde o nascente do sol e desde o seu poente saibam que não há outro além de mim. Eu sou Jeová, e não há outro.

[[v23-45-7]]

^<<v23-45-7,7>>^ Formando a luz e criando a escuridão, fazendo paz e criando calamidade, eu, Jeová, faço todas estas coisas.

[[v23-45-8]]

^<<v23-45-8,8>>^ “Ó céus, fazei-o destilar de cima; e escoe o próprio céu nublado a justiça. Abra-se a terra e seja ela frutífera com salvação, e faça ela a própria justiça brotar ao mesmo tempo. Eu mesmo, Jeová, o^&#42;1^ criei.”

[NOTE]
====
. “O”, hebr. masc.
====

[[v23-45-9]]

^<<v23-45-9,9>>^ Ai daquele que contendeu com o seu Formador, como um caco com outros cacos do solo! Devia o barro dizer àquele que o forma: “Que estás fazendo?” E [devia dizer] tua realização: “Ele não tem mãos”?

[[v23-45-10]]

^<<v23-45-10,10>>^ Ai daquele que diz a um pai: “De que te tornas pai?” e à esposa:^&#42;1^ “De que estás em dores de parto?”

[NOTE]
====
. Ou “mulher”.
====

[[v23-45-11]]

^<<v23-45-11,11>>^ Assim disse Jeová, o Santo de Israel e o Formador dele: “Pergunta-me mesmo sobre as coisas vindouras, referentes aos meus filhos; e acerca da atividade das minhas mãos deveis ordenar-me.

[[v23-45-12]]

^<<v23-45-12,12>>^ Eu é que fiz a terra e criei até mesmo o homem^&#42;1^ sobre ela. Eu — minhas próprias mãos estenderam os céus, e dei ordens a todo o seu exército.”

[NOTE]
====
. “E . . . homem.” Hebr.: we’a·dhám.
====

[[v23-45-13]]

^<<v23-45-13,13>>^ “Eu é que despertei alguém em justiça e endireitarei todos os seus caminhos. É ele quem construirá a minha cidade e soltará^&#42;1^ os meus que estão no exílio, não por um preço nem por suborno”, disse Jeová dos exércitos.

[NOTE]
====
. Ou “mandará embora”. Hebr.: yeshal·lé·ahh.
====

[[v23-45-14]]

^<<v23-45-14,14>>^ Assim disse Jeová: “Os próprios labutadores não remunerados do Egito, e os mercadores da Etiópia,^&#42;1^ e os sabeus, homens altos,^&#42;2^ virão a ti^&#42;3^ e se tornarão teus. Andarão atrás de ti; virão em grilhões e se curvarão diante de ti. Orarão a ti, [dizendo:] ‘Deveras, Deus está em união contigo,^&#42;4^ e não há outro; não há [outro] Deus.’”^&#42;5^

[NOTE]
====
. “Etiópia”, Vg; LXX: “etíopes”; MTSy: “Cus”.
. Lit.: “homens de medida”.
. “Ti”, hebr. fem., referindo-se a um povo ou a uma cidade.
. “Deus está em união contigo.” Lit.: “em ti [está] Deus”. Hebr.: bakh ’El.
. “Não . . . [outro] Deus.” Hebr.: ’éfes ’Elo·hím.
====

[[v23-45-15]]

^<<v23-45-15,15>>^ Verdadeiramente, tu és um Deus que se mantém escondido, o Deus de Israel, Salvador.

[[v23-45-16]]

^<<v23-45-16,16>>^ Certamente ficarão envergonhados e até mesmo humilhados, todos eles. Os fabricantes de figuras [de ídolos] terão de andar juntos em humilhação.

[[v23-45-17]]

^<<v23-45-17,17>>^ Quanto a Israel, há de ser salvo em união com Jeová com uma salvação por tempos indefinidos. Vós não vos envergonhareis, nem sereis humilhados, pelos tempos indefinidos da eternidade.

[[v23-45-18]]

^<<v23-45-18,18>>^ Pois assim disse Jeová, o Criador dos céus, Ele, o [verdadeiro] Deus, o Formador da terra e Aquele que a fez, Aquele que a estabeleceu firmemente, que não a criou simplesmente para nada, que a formou mesmo para ser habitada: “Eu sou Jeová, e não há outro.

[[v23-45-19]]

^<<v23-45-19,19>>^ Não falei num esconderijo, num lugar escuro da terra; nem disse eu à descendência^&#42;1^ de Jacó: ‘Procurai-me simplesmente para nada.’ Eu sou Jeová, falando o que é justo, contando o que é reto.

[NOTE]
====
. Ou “prole”.
====

[[v23-45-20]]

^<<v23-45-20,20>>^ “Reuni-vos e chegai. Aproximai-vos juntos, vós fugitivos das nações. Os que carregam a madeira^&#42;1^ da sua imagem esculpida não vieram a ter conhecimento, nem tampouco os que oram a um deus que não pode salvar.^&#42;2^

[NOTE]
====
. Ou “árvore da”. Hebr.: ‛ets.
. “Um deus que não pode salvar.” Hebr.: ’el lo’ yoh·shí·a‛; gr.: the·oús; lat.: dé·um.
====

[[v23-45-21]]

^<<v23-45-21,21>>^ Fazei a vossa comunicação e a vossa apresentação. Sim, consultem-se eles em união. Quem fez que se ouvisse isso desde outrora? [Quem] o comunicou desde aquele tempo? Não fui eu, Jeová, além de quem não há outro Deus;^&#42;1^ Deus justo^&#42;2^ e Salvador, não havendo outro além de mim?

[NOTE]
====
. “Deus.” Hebr.: ’Elo·hím.
. “Deus justo.” Hebr.: ’El-tsad·díq; lat.: Dé·us iú·stus.
====

[[v23-45-22]]

^<<v23-45-22,22>>^ “Virai-vos para mim e sede salvos, todos vós [nos] confins da terra; pois eu sou Deus, e não há outro.

[[v23-45-23]]

^<<v23-45-23,23>>^ Jurei por mim mesmo — da minha própria boca saiu a palavra em justiça, de modo que não retornará — que diante de mim se dobrará todo joelho, jurará toda língua,^&#42;1^

[NOTE]
====
. “Todo joelho se dobrará diante de mim, e toda língua reconhecerá abertamente a Deus”, LXX. Veja Ro 14:11.
====

[[v23-45-24]]

^<<v23-45-24,24>>^ dizendo: ‘Seguramente há plena justiça e força em Jeová. Todos os que se acaloram contra ele virão diretamente a ele e ficarão envergonhados.

[[v23-45-25]]

^<<v23-45-25,25>>^ Toda a descendência de Israel mostrar-se-á direita em Jeová e jactar-se-á.’”

'''

xref:023-isaias/023-isaias-044.adoc#v23-44-0[&#60; Capítulo Anterior] | <<v23-45-0,Topo>> | xref:023-isaias/023-isaias-046.adoc#v23-46-0[Próximo Capítulo &#62;]