include::./index.adoc[]

[[v24-5-0]]
=== Jeremias, 5
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v24-5-1]]

^<<v24-5-1,1>>^ Percorrei as ruas de Jerusalém e vede, pois, e sabei e procurai vós mesmos nas suas praças públicas se podeis achar um homem, se existe alguém que pratique a justiça, alguém que procure a fidelidade, e eu perdoarei a ela.

[[v24-5-2]]

^<<v24-5-2,2>>^ Mesmo que dissessem: “Por Jeová que vive!” estariam com isso jurando pura falsidade.

[[v24-5-3]]

^<<v24-5-3,3>>^ Ó Jeová, não estão estes teus olhos [dirigidos] para a fidelidade? Tu os golpeaste, mas não ficaram doentes. Tu os exterminaste. Negaram-se a aceitar a disciplina. Endureceram as suas faces mais do que um rochedo. Negaram-se a recuar.

[[v24-5-4]]

^<<v24-5-4,4>>^ Até mesmo eu disse: “Seguramente são de classe baixa. Agiram tolamente, pois desconsideraram o caminho de Jeová, o julgamento de seu Deus.^&#42;1^

[NOTE]
====
. “Seu Deus.” Hebr.: ’Elo·heh·hém, pl.
====

[[v24-5-5]]

^<<v24-5-5,5>>^ Vou seguir meu caminho para os grandes e vou falar com eles; pois eles mesmos devem ter notado o caminho de Jeová, o julgamento de seu Deus. Seguramente, eles mesmos, juntos, devem ter quebrado o jugo; devem ter rompido as ligaduras.”

[[v24-5-6]]

^<<v24-5-6,6>>^ Por isso é que os golpeou um leão [saindo] da floresta, um lobo das planícies desérticas é que os está assolando, um leopardo se mantém alerta junto às suas cidades. Todo aquele que delas sai é dilacerado. Pois as suas transgressões tornaram-se muitas; seus atos de infidelidade tornaram-se numerosos.

[[v24-5-7]]

^<<v24-5-7,7>>^ Como posso perdoar-te^&#42;1^ tal coisa? Teus próprios filhos me deixaram e estão jurando por aquilo que não é Deus.^&#42;2^ E eu continuei a satisfazê-los, mas eles continuaram a cometer adultério e vão em bandos à casa duma mulher prostituta.

[NOTE]
====
. “Te”, hebr. fem. sing.
. Ou “por aquilo que não são deuses”. Hebr.: beló’ ’elo·hím.
====

[[v24-5-8]]

^<<v24-5-8,8>>^ Tornaram-se [como] cavalos em cio, tendo [fortes] testículos. Rincham cada um à mulher do seu companheiro.

[[v24-5-9]]

^<<v24-5-9,9>>^ “Não devia eu ajustar contas por causa de tais coisas?” é a pronunciação de Jeová. “Ou não devia a minha alma vingar-se de uma nação tal como esta?”

[[v24-5-10]]

^<<v24-5-10,10>>^ “Subi contra as suas fileiras^&#42;1^ [de videiras] e causai a ruína, mas não causeis um verdadeiro extermínio. Tirai-lhe os profusos raminhos, pois não pertencem a Jeová.

[NOTE]
====
. “Seus muros de terraço”, mediante uma ligeira mudança dos sinais vocálicos.
====

[[v24-5-11]]

^<<v24-5-11,11>>^ Porque a casa de Israel e a casa de Judá foram positivamente traiçoeiras para comigo”, é a pronunciação de Jeová.

[[v24-5-12]]

^<<v24-5-12,12>>^ “Renegaram a Jeová e estão dizendo: ‘Ele não existe. E não nos sobrevirá nenhuma calamidade e não veremos nenhuma espada ou fome.’

[[v24-5-13]]

^<<v24-5-13,13>>^ E os próprios profetas tornam-se vento e a palavra não está neles. É assim que se lhes fará.”

[[v24-5-14]]

^<<v24-5-14,14>>^ Portanto, assim disse Jeová, o Deus dos exércitos: “Visto que dizeis tal coisa, eis que faço das minhas palavras um fogo na tua boca, e este povo será pedaços de lenha, e certamente os devorará.”

[[v24-5-15]]

^<<v24-5-15,15>>^ “Eis que farei chegar sobre vós uma nação longínqua, ó casa de Israel”, é a pronunciação de Jeová. “É uma nação resistente. É uma nação de há muito tempo, uma nação cuja língua não conheces, e não podes ouvir [inteligivelmente] o que eles falam.

[[v24-5-16]]

^<<v24-5-16,16>>^ Sua aljava é como uma sepultura aberta; todos eles são homens poderosos.

[[v24-5-17]]

^<<v24-5-17,17>>^ Certamente consumirão também a tua colheita e o teu pão. Os homens consumirão teus filhos e tuas filhas. Consumirão teus rebanhos e tuas manadas. Consumirão tua videira e tua figueira. Destroçarão com a espada as tuas cidades fortificadas em que confias.”

[[v24-5-18]]

^<<v24-5-18,18>>^ “E mesmo naqueles dias”, é a pronunciação de Jeová, “não executarei o vosso extermínio.

[[v24-5-19]]

^<<v24-5-19,19>>^ E terá de acontecer que direis: ‘Devido a que fato nos fez Jeová, nosso Deus, todas estas coisas?’ E terás de dizer-lhes: ‘Assim como vós me abandonastes e fostes servir a um deus estrangeiro^&#42;1^ na vossa terra, assim servireis a estranhos numa terra que não é vossa.’”

[NOTE]
====
. Ou “deuses estrangeiros”. Lit.: “um deus [ou: deuses] dum (país) estrangeiro”. Hebr.: ’elo·héh ne·khár. A forma pl. de “deus” talvez denote excelência.
====

[[v24-5-20]]

^<<v24-5-20,20>>^ Contai isto na casa de Jacó e publicai-o em Judá, dizendo:

[[v24-5-21]]

^<<v24-5-21,21>>^ “Ouvi, pois, o seguinte, ó povo estulto, sem coração:^&#42;1^ Eles têm olhos, mas não podem ver; têm ouvidos, mas não podem ouvir.

[NOTE]
====
. Ou “boa motivação”. Hebr.: lev.
====

[[v24-5-22]]

^<<v24-5-22,22>>^ ‘Não temeis nem mesmo a mim’, é a pronunciação de Jeová, ‘ou não estais em severas dores, nem mesmo por causa de mim, que pus a areia como termo do mar, para regulamento de duração indefinida, de modo que não pode passar além? Ainda que as ondas se encapelem, contudo, não podem prevalecer; e [ainda que] deveras fiquem turbulentas, contudo, não podem passar além dela.

[[v24-5-23]]

^<<v24-5-23,23>>^ Mas este mesmo povo veio a ter um coração obstinado e rebelde; desviaram-se e estão andando no seu [próprio] rumo.

[[v24-5-24]]

^<<v24-5-24,24>>^ Mas não disseram no seu coração: “Temamos, pois, a Jeová, nosso Deus, Aquele que dá o aguaceiro, e a chuva outonal e a chuva primaveril na sua estação, Aquele que guarda até mesmo as semanas prescritas da colheita para nós.”

[[v24-5-25]]

^<<v24-5-25,25>>^ Vossos próprios erros é que apartaram estas coisas e os vossos próprios pecados negaram-vos o que é bom.

[[v24-5-26]]

^<<v24-5-26,26>>^ “‘Pois entre o meu povo foram encontrados homens iníquos. Estão espreitando como quando os passarinheiros se agacham. Armaram uma [armadilha] ruinosa.^&#42;1^ É a homens^&#42;2^ que eles capturam.

[NOTE]
====
. “Uma [armadilha] ruinosa.” Ou “arruinamento”, isto é, na forma duma armadilha ou dum laço.
. “Homens.” Hebr.: ’ana·shím.
====

[[v24-5-27]]

^<<v24-5-27,27>>^ Assim como a gaiola está cheia de criaturas voadoras, assim as suas casas estão cheias de engano. Por isso é que se tornaram grandes e se enriquecem.

[[v24-5-28]]

^<<v24-5-28,28>>^ Engordaram; ficaram reluzentes. Transbordaram também com coisas^&#42;1^ más. Não pleitearam nenhuma causa jurídica, nem mesmo a causa jurídica do menino órfão de pai, para serem bem sucedidos; e não tomaram conta do julgamento dos pobres.’”

[NOTE]
====
. Ou “palavras; assuntos”.
====

[[v24-5-29]]

^<<v24-5-29,29>>^ “Não devia eu ajustar contas por causa destas mesmas coisas”, é a pronunciação de Jeová, “ou não devia vingar-se a minha alma duma nação tal como esta?

[[v24-5-30]]

^<<v24-5-30,30>>^ Uma situação assombrosa, mesmo uma coisa horrível fez-se existir^&#42;1^ no país:

[NOTE]
====
. Veja De 27:9 n.
====

[[v24-5-31]]

^<<v24-5-31,31>>^ Os próprios profetas realmente profetizam em falsidade; e quanto aos sacerdotes, estão subjugando segundo os seus poderes.^&#42;1^ E meu próprio povo amou-o assim; e que fareis vós ao final disso?”

[NOTE]
====
. Lit.: “mãos”.
====

'''

xref:024-jeremias/024-jeremias-004.adoc#v24-4-0[&#60; Capítulo Anterior] | <<v24-5-0,Topo>> | xref:024-jeremias/024-jeremias-006.adoc#v24-6-0[Próximo Capítulo &#62;]