include::./index.adoc[]

[[v24-48-0]]
=== Jeremias, 48
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v24-48-1]]

^<<v24-48-1,1>>^ Para Moabe, assim disse Jeová dos exércitos, o Deus de Israel: “Ai de Nebo, porque ela foi assolada! Quiriataim foi envergonhada, foi capturada. A altura protetora foi envergonhada e aterrorizada.

[[v24-48-2]]

^<<v24-48-2,2>>^ Não há mais louvor de Moabe. Em Hésbon inventaram contra ela uma calamidade: ‘Vinde, homens, e decepemo-la de ser nação.’
“Também tu, ó Madmém, deves ficar quieta. Atrás de ti anda uma espada.

[[v24-48-3]]

^<<v24-48-3,3>>^ Há o som dum clamor procedente de Horonaim, assolação e grande desmoronamento.

[[v24-48-4]]

^<<v24-48-4,4>>^ Moabe foi destroçada. Seus pequenos fizeram ouvir um clamor.

[[v24-48-5]]

^<<v24-48-5,5>>^ Pois na subida de Luíte sobe-se com choro — há choro. Pois na descida de Horonaim há um clamor aflitivo pelo desmoronamento de que se ouviu [falar].

[[v24-48-6]]

^<<v24-48-6,6>>^ “Ponde-vos em fuga; ponde as vossas almas^&#42;1^ a salvo, e deveis tornar-vos como o junípero^&#42;2^ no ermo.

[NOTE]
====
. Lit.: “vossa alma”, hebr. sing., mas em sentido coletivo. Hebr.: naf·shekhém; gr.: psy·khás; lat.: á·ni·mas.
. “O junípero.” O significado desta palavra hebr. é incerto; mediante uma correção, em harmonia com LXX: “jumento selvagem”.
====

[[v24-48-7]]

^<<v24-48-7,7>>^ Visto que confias^&#42;1^ nos teus trabalhos e nos teus tesouros, tu mesma também serás capturada. E Quemós certamente sairá para o exílio, seus sacerdotes e seus príncipes, ao mesmo tempo.

[NOTE]
====
. “Confias”, hebr. fem. sing., referindo-se a Moabe.
====

[[v24-48-8]]

^<<v24-48-8,8>>^ E o assolador entrará em cada cidade e não haverá cidade que possa escapar. E a baixada há de perecer e a planície há de ser aniquilada, o que foi dito por Jeová.

[[v24-48-9]]

^<<v24-48-9,9>>^ “Dai um marco de estrada a Moabe, pois sairá ao cair em ruínas; e as próprias cidades dela tornar-se-ão mero assombro, sem que alguém more nelas.

[[v24-48-10]]

^<<v24-48-10,10>>^ “Maldito aquele que cumprir a missão de Jeová com negligência; e maldito aquele que retiver a sua espada do sangue!

[[v24-48-11]]

^<<v24-48-11,11>>^ “Os moabitas^&#42;1^ estiveram despreocupados desde a sua^&#42;2^ mocidade e ficam^&#42;3^ sossegados na sua borra. E não foram despejados de um vaso para outro vaso e não foram ao exílio. Por isso é que se manteve neles^&#42;4^ o seu sabor e o próprio aroma deles não se modificou.

[NOTE]
====
. Lit.: “Moabe”.
. Lit.: “sua”, com o sujeito no sing.
. Lit.: “fica”.
. Lit.: “nele”. “Moabe” é hebr. fem. nos vv. 1-9.
====

[[v24-48-12]]

^<<v24-48-12,12>>^ “‘Portanto, eis que vêm dias’, é a pronunciação de Jeová, ‘e eu vou enviar-lhes entornadores [de vasos] e estes certamente os entornarão; e esvaziarão seus vasos e espatifarão suas^&#42;1^ grandes talhas.

[NOTE]
====
. “Suas”, hebr. masc. pl., referindo-se aos homens de Moabe.
====

[[v24-48-13]]

^<<v24-48-13,13>>^ E os moabitas terão de envergonhar-se de Quemós, assim como os da casa de Israel se envergonharam de Betel, sua confiança.

[[v24-48-14]]

^<<v24-48-14,14>>^ Como vos atreveis a dizer: “Somos homens poderosos e homens de energia vital para a guerra”?’

[[v24-48-15]]

^<<v24-48-15,15>>^ “‘Moabe foi assolada, e subiu-se contra as próprias cidades dela. E seus jovens mais seletos é que desceram para o abate’, é a pronunciação do Rei, cujo nome é Jeová dos exércitos.

[[v24-48-16]]

^<<v24-48-16,16>>^ “O desastre dos moabitas está prestes a chegar e a própria calamidade deles apressa-se realmente muitíssimo.

[[v24-48-17]]

^<<v24-48-17,17>>^ Todos os ao redor deles terão de compadecer-se deles, sim todos os que conhecem seu nome. Dizei: ‘Oh! como foi quebrado o bastão de força, o bordão de beleza!’

[[v24-48-18]]

^<<v24-48-18,18>>^ “Desce da glória e senta-te com sede, ó moradora da filha de Díbon; porque subiu contra ti o assolador de Moabe. Ele realmente arruinará as tuas praças fortes.

[[v24-48-19]]

^<<v24-48-19,19>>^ “Fica parada e vigia o próprio caminho, ó moradora de Aroer. Pergunta àquele que foge e àquela que se escapa. Dize: ‘Que aconteceu?’

[[v24-48-20]]

^<<v24-48-20,20>>^ Moabe foi envergonhada, porque ficou aterrorizada. Uiva e clama. Contai em Árnon que Moabe foi assolada.

[[v24-48-21]]

^<<v24-48-21,21>>^ E o próprio julgamento chegou à terra da planície, a Holom e a Jaaz,^&#42;1^ e contra Mefaate,

[NOTE]
====
. Hebr.: Yáh·tsah.
====

[[v24-48-22]]

^<<v24-48-22,22>>^ e contra Díbon, e contra Nebo, e contra Bete-Diblataim,

[[v24-48-23]]

^<<v24-48-23,23>>^ e contra Quiriataim, e contra Bete-Gamul, e contra Bete-Meom,

[[v24-48-24]]

^<<v24-48-24,24>>^ e contra Queriote, e contra Bozra, e contra todas as cidades da terra de Moabe, as longínquas e as próximas.

[[v24-48-25]]

^<<v24-48-25,25>>^ “‘Foi cortado o chifre de Moabe e foi quebrado seu próprio braço’, é a pronunciação de Jeová.

[[v24-48-26]]

^<<v24-48-26,26>>^ ‘Embriagai-o, porque assumiu ares de grandeza contra o próprio Jeová; e Moabe debateu-se no seu vômito e tornou-se alvo de ridículo, sim, ele mesmo.

[[v24-48-27]]

^<<v24-48-27,27>>^ “‘E não se tornou Israel um mero alvo de ridículo para ti?^&#42;1^ Ou foi ele^&#42;2^ achado no meio de flagrantes ladrões? Pois tu te sacudias tantas vezes quantas falavas contra ele.

[NOTE]
====
. “Ti”, hebr. masc. sing.
. “Ele”, Mmargem; M: “ela”.
====

[[v24-48-28]]

^<<v24-48-28,28>>^ “‘Deixai as cidades e residi no rochedo, habitantes de Moabe, e tornai-vos como a pomba que faz seu ninho nas regiões da boca do barranco.’”

[[v24-48-29]]

^<<v24-48-29,29>>^ “Ouvimos [falar] do orgulho de Moabe — ele é muito altivo — de sua soberba, e de seu orgulho, e de sua altivez, e do enaltecimento do seu coração.”

[[v24-48-30]]

^<<v24-48-30,30>>^ “‘Eu mesmo conhecia a sua fúria’, é a pronunciação de Jeová, ‘e não ficará assim; seu palavreado oco — realmente não [o] farão exatamente assim.

[[v24-48-31]]

^<<v24-48-31,31>>^ Por isso é que uivarei sobre Moabe e clamarei por todo o Moabe. Gemer-se-á pelos homens de Quir-Heres.

[[v24-48-32]]

^<<v24-48-32,32>>^ “‘Com mais choro do que o por Jázer chorarei por ti, ó videira de Sibma. Teus próprios brotos florescentes cruzaram o mar. Estenderam-se até o mar — [até] Jázer. O próprio assolador caiu sobre os teus frutos de verão e sobre a tua vindima.

[[v24-48-33]]

^<<v24-48-33,33>>^ E a alegria e o júbilo foram tirados do pomar e da terra de Moabe. E dos lagares fiz cessar o próprio vinho. Ninguém fará a pisa com exclamação. A exclamação não será exclamação.’”

[[v24-48-34]]

^<<v24-48-34,34>>^ “‘Desde o clamor em Hésbon até Eleale, até Jaaz, deram vazão à sua voz, desde Zoar até Horonaim, até Eglate-Selisaia; porque até mesmo as próprias águas de Ninrim tornar-se-ão meras desolações.

[[v24-48-35]]

^<<v24-48-35,35>>^ E eu vou fazer cessar em Moabe’, é a pronunciação de Jeová, ‘aquele que leva uma oferta para cima ao alto e aquele que faz fumaça sacrificial ao seu deus.^&#42;1^

[NOTE]
====
. Ou “aos seus deuses”. Hebr.: le’·lo·háv; lat.: dí·is.
====

[[v24-48-36]]

^<<v24-48-36,36>>^ Por isso é que o meu próprio coração ficará turbulento pelo próprio Moabe, igual a flautas; e meu próprio coração ficará turbulento pelos homens de Quir-Heres, igual a flautas. Por isso é que certamente perecerá a própria abundância que ele produziu.

[[v24-48-37]]

^<<v24-48-37,37>>^ Porque sobre toda cabeça há calvície e toda barba está cortada. Em todas as mãos há cortes e sobre os quadris há serapilheira!’”

[[v24-48-38]]

^<<v24-48-38,38>>^ “‘Em todos os terraços de Moabe e nas suas praças públicas — em todas elas — há lamento; porque destrocei Moabe como a um vaso que não agrada’, é a pronunciação de Jeová.

[[v24-48-39]]

^<<v24-48-39,39>>^ ‘Oh! como ela ficou aterrorizada!^&#42;1^ Uivai! Oh! como Moabe virou as costas! Ele ficou envergonhado. E Moabe tornou-se alvo de ridículo e algo aterrorizante para todos em volta dele.’”

[NOTE]
====
. Ou: “ela foi destroçada!”
====

[[v24-48-40]]

^<<v24-48-40,40>>^ “Pois assim disse Jeová: ‘Eis que, assim como arremete a águia, alguém terá de estender também as suas asas sobre Moabe.

[[v24-48-41]]

^<<v24-48-41,41>>^ As vilas serão realmente capturadas e seus próprios fortes serão certamente tomados. E o coração dos poderosos de Moabe terá de tornar-se naquele dia igual ao coração duma esposa na aflição do parto.’”

[[v24-48-42]]

^<<v24-48-42,42>>^ “‘E Moabe há de ser aniquilado [deixando] de ser um povo, porque foi contra Jeová que ele assumiu ares de grandeza.

[[v24-48-43]]

^<<v24-48-43,43>>^ O pavor, e o barranco, e a armadilha estão sobre ti, ó habitante de Moabe’, é a pronunciação de Jeová.

[[v24-48-44]]

^<<v24-48-44,44>>^ ‘Quem fugir por causa do pavor cairá no barranco; e quem sair do barranco será apanhado pela armadilha.’
“‘Pois trarei sobre ela, sobre Moabe, o ano de se fixar a atenção neles’, é a pronunciação de Jeová.

[[v24-48-45]]

^<<v24-48-45,45>>^ ‘Os que fugiram ficaram parados, sem poder, à sombra de Hésbon. Pois é um fogo que há de sair de Hésbon e uma chama do meio de Síon; e devorará as têmporas de Moabe e o alto da cabeça dos filhos do rebuliço.’

[[v24-48-46]]

^<<v24-48-46,46>>^ “‘Ai de ti,^&#42;1^ ó Moabe! Pereceu o povo de Quemós. Porque teus filhos foram levados como cativos e tuas filhas como cativas.

[NOTE]
====
. “Ti”, hebr. masc. sing.
====

[[v24-48-47]]

^<<v24-48-47,47>>^ E eu vou recolher os cativos de Moabe na parte final dos dias’, é a pronunciação de Jeová. ‘Até este ponto vai o julgamento de Moabe.’”

'''

xref:024-jeremias/024-jeremias-047.adoc#v24-47-0[&#60; Capítulo Anterior] | <<v24-48-0,Topo>> | xref:024-jeremias/024-jeremias-049.adoc#v24-49-0[Próximo Capítulo &#62;]