include::./index.adoc[]

[[v24-4-0]]
=== Jeremias, 4
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v24-4-1]]

^<<v24-4-1,1>>^ “Se voltares, ó Israel”, é a pronunciação de Jeová, “podes voltar a mim mesmo. E se tirares as tuas coisas repugnantes por minha causa,^&#42;1^ então não andarás como fugitivo.

[NOTE]
====
. Lit.: “da minha face”.
====

[[v24-4-2]]

^<<v24-4-2,2>>^ E [se] certamente jurares: ‘Por Jeová que vive em verdade, em juízo e em justiça!’ então é realmente nele^&#42;1^ que as nações abençoarão a si mesmas e se jactarão.”

[NOTE]
====
. “Nele.” Possivelmente referindo-se a “Israel”.
====

[[v24-4-3]]

^<<v24-4-3,3>>^ Pois assim disse Jeová aos homens^&#42;1^ de Judá e a Jerusalém: “Lavrai para vós terra de lavoura e não continueis a semear entre^&#42;2^ os espinhos.

[NOTE]
====
. “Aos homens de.” Hebr.: le’ísh, hebr. sing., mas usado em sentido coletivo.
. Lit.: “aos”; ou: “para os”.
====

[[v24-4-4]]

^<<v24-4-4,4>>^ Fazei-vos circuncidar para Jeová e tirai os prepúcios de vossos corações, ó homens^&#42;1^ de Judá e habitantes de Jerusalém; para que o meu furor não saia como um fogo e certamente arda sem haver quem [o] apague, por causa da ruindade das vossas ações.”

[NOTE]
====
. “Homens de.” Hebr.: ’ish, hebr. sing., mas usado em sentido coletivo.
====

[[v24-4-5]]

^<<v24-4-5,5>>^ Contai-o em Judá e publicai-o mesmo em Jerusalém, e dizei-o, e tocai uma buzina^&#42;1^ através do país. Clamai alto^&#42;2^ e dizei: “Ajuntai-vos, e entremos nas cidades fortificadas.

[NOTE]
====
. Ou “shofar”.
. Lit.: “Clamai, enchei [fazei-o plenamente].”
====

[[v24-4-6]]

^<<v24-4-6,6>>^ Levantai um sinal de aviso rumo a Sião. Providenciai abrigo. Não fiqueis parados.” Pois há uma calamidade que estou trazendo desde o norte, sim, uma grande derrocada.

[[v24-4-7]]

^<<v24-4-7,7>>^ Ele subiu como um leão da sua moita, e aquele que arruína as nações partiu; saiu do seu lugar, a fim de fazer da tua^&#42;1^ terra um assombro. Tuas próprias cidades cairão em ruínas, de modo que não haverá habitante.

[NOTE]
====
. “Tua”, hebr. fem. sing.
====

[[v24-4-8]]

^<<v24-4-8,8>>^ Por causa disso, cingi-vos de serapilheira. Batei-vos no peito e uivai, porque a ira ardente de Jeová não recuou de nós.

[[v24-4-9]]

^<<v24-4-9,9>>^ “E naquele dia terá de acontecer”, é a pronunciação de Jeová, “que perecerá o coração do rei, também o coração dos príncipes; e os sacerdotes serão certamente levados ao assombro e os próprios profetas ficarão pasmados”.

[[v24-4-10]]

^<<v24-4-10,10>>^ E passei a dizer: “Ai! Soberano Senhor Jeová! Verdadeiramente, enganaste por completo este povo e Jerusalém, dizendo: ‘A própria paz virá a ser vossa’, e é a espada que atingiu até à alma.”^&#42;1^

[NOTE]
====
. “À alma.” Hebr.: han·ná·fesh; gr.: psy·khés; lat.: á·ni·mam. Veja Ap. 4A.
====

[[v24-4-11]]

^<<v24-4-11,11>>^ Naquele tempo se dirá a este povo e a Jerusalém: “Há um vento causticante das veredas batidas através do ermo [no] caminho para a filha do meu povo; não é para joeirar, nem para se fazer limpeza.

[[v24-4-12]]

^<<v24-4-12,12>>^ O próprio vento, em cheio, vem a mim até mesmo procedente destas. Agora eu mesmo também proferirei os julgamentos para com eles.

[[v24-4-13]]

^<<v24-4-13,13>>^ Eis que ele subirá como nuvens de chuva e seus carros são como o tufão. Seus cavalos são mais velozes do que as águias.^&#42;1^ Ai de nós, porque fomos assolados!

[NOTE]
====
. Ou “abutres”.
====

[[v24-4-14]]

^<<v24-4-14,14>>^ Lava teu coração da pura maldade, ó Jerusalém, para que sejas salva. Até quando se alojarão no teu íntimo os teus pensamentos errôneos?

[[v24-4-15]]

^<<v24-4-15,15>>^ Porque uma voz está informando desde Dã e está publicando algo prejudicial desde a região montanhosa de Efraim.

[[v24-4-16]]

^<<v24-4-16,16>>^ Fazei menção [disso], sim, às nações. Publicai-o contra Jerusalém.”
“Sentinelas estão chegando desde uma terra longínqua, e eles darão vazão à sua voz contra as próprias cidades de Judá.

[[v24-4-17]]

^<<v24-4-17,17>>^ Vieram a ser contra ela em todos os lados quais guardas da campina, porque ela se rebelou até mesmo contra mim”, é a pronunciação de Jeová.

[[v24-4-18]]

^<<v24-4-18,18>>^ “Teu^&#42;1^ proceder e tuas ações — estas [coisas] se farão^&#42;2^ a ti.^&#42;3^ Esta é a calamidade sobre ti, pois é amarga; porque atingiu até o teu coração.”

[NOTE]
====
. “Teu”, hebr. fem. sing.
. “Se farão.” No hebr., este verbo está no infinitivo absoluto, indefinido quanto ao tempo e impessoal.
. “Teu proceder e tuas ações fizeram estas coisas a ti”, em harmonia com TLXXSyVg e alguns mss. hebr.
====

[[v24-4-19]]

^<<v24-4-19,19>>^ Ai! meus intestinos, meus intestinos! Estou com severas dores nas paredes de meu coração. Meu coração está turbulento dentro de mim. Não posso calar-me, porque a minha alma ouviu o som da buzina, o rebate de guerra.

[[v24-4-20]]

^<<v24-4-20,20>>^ Derrocada sobre derrocada é que foram convocadas, porque a terra inteira foi assolada. Repentinamente foram assoladas as minhas tendas, num instante, os meus panos de tenda.

[[v24-4-21]]

^<<v24-4-21,21>>^ Até quando estarei vendo o sinal de aviso, estarei ouvindo o som da buzina?

[[v24-4-22]]

^<<v24-4-22,22>>^ Pois meu povo é tolo. Não fizeram caso de mim. São filhos estultos; e não são os que têm entendimento. São sábios para fazer o mal, mas para fazer o bem eles realmente não têm conhecimento.

[[v24-4-23]]

^<<v24-4-23,23>>^ Eu vi a terra,^&#42;1^ e eis que [estava] deserta e vazia; e [olhei] para os céus, e sua luz não existia mais.

[NOTE]
====
. “A terra.” Hebr.: ha·’á·rets.
====

[[v24-4-24]]

^<<v24-4-24,24>>^ Vi os montes, e eis que tremiam, e os próprios morros estavam todos sendo sacudidos.

[[v24-4-25]]

^<<v24-4-25,25>>^ Vi, e eis que não havia homem terreno,^&#42;1^ e as criaturas voadoras dos céus tinham todas fugido.

[NOTE]
====
. “Homem terreno.” Hebr.: ha·’a·dhám.
====

[[v24-4-26]]

^<<v24-4-26,26>>^ Vi, e eis que o próprio pomar era um ermo, e suas próprias cidades tinham todas sido demolidas. Foi por causa de Jeová, por causa da sua ira ardente.

[[v24-4-27]]

^<<v24-4-27,27>>^ Pois assim disse Jeová: “Um baldio desolado é o que se tornará a terra inteira, e não executarei eu uma exterminação cabal?^&#42;1^

[NOTE]
====
. Ou “mas não executarei uma exterminação”.
====

[[v24-4-28]]

^<<v24-4-28,28>>^ Por esta causa pranteará a terra e certamente se escurecerão os céus acima. É porque eu falei, eu cogitei e não senti lástima, nem recuarei disso.

[[v24-4-29]]

^<<v24-4-29,29>>^ Por causa do ruído dos cavaleiros e dos arqueiros, a cidade inteira está fugindo. Entraram nas moitas e subiram às penhas.^&#42;1^ Cada cidade está abandonada e não há homem^&#42;2^ morando nelas.”

[NOTE]
====
. “E . . . às penhas.” Hebr.: u·vak·ke·fím; gr.: pé·tras. Veja Mt 16:18 n.: “rocha”.
. “Homem.” Hebr.: ’ish.
====

[[v24-4-30]]

^<<v24-4-30,30>>^ Agora que estás^&#42;1^ assolada, o que farás, visto que costumavas vestir-te de escarlate, visto que costumavas ataviar-te com enfeites de ouro, visto que costumavas alargar os teus olhos com pintura preta? Foi em vão que costumavas fazer-te bonita. Os apaixonados por [ti] te rejeitaram; estão procurando a tua própria alma.

[NOTE]
====
. “Estás”, hebr. fem. sing., dirigido a Sião ou Jerusalém.
====

[[v24-4-31]]

^<<v24-4-31,31>>^ Pois ouvi uma voz como a duma mulher doente,^&#42;1^ aflição como a duma mulher dando à luz seu primeiro filho, a voz da filha de Sião, que faz esforços para respirar. Ela está estendendo as palmas das suas mãos: “Ai de mim, pois, porque a minha alma está cansada dos matadores!”

[NOTE]
====
. “Duma mulher com dores de parto”, mediante uma ligeira correção.
====

'''

xref:024-jeremias/024-jeremias-003.adoc#v24-3-0[&#60; Capítulo Anterior] | <<v24-4-0,Topo>> | xref:024-jeremias/024-jeremias-005.adoc#v24-5-0[Próximo Capítulo &#62;]