include::./index.adoc[]

[[v24-52-0]]
=== Jeremias, 52
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v24-52-1]]

^<<v24-52-1,1>>^ Zedequias tinha vinte e um anos quando começou a reinar e reinou onze anos em Jerusalém. E o nome de sua mãe era Hamutal, filha de Jeremias, de Libna.

[[v24-52-2]]

^<<v24-52-2,2>>^ E ele fazia o que era mau aos olhos de Jeová, segundo tudo o que Jeoiaquim fizera.

[[v24-52-3]]

^<<v24-52-3,3>>^ Pois, por causa da ira de Jeová, aconteceu em Jerusalém e em Judá, até que os tinha lançado fora de diante da sua face, que Zedequias passou a rebelar-se contra o rei de Babilônia.

[[v24-52-4]]

^<<v24-52-4,4>>^ Finalmente, aconteceu no nono ano de ele ser rei, no décimo mês, no dia décimo do mês, que chegou Nabucodorosor, rei de Babilônia, ele e toda a sua força militar, contra Jerusalém, e começaram a acampar-se contra ela e a construir contra ela um muro de sítio ao redor.

[[v24-52-5]]

^<<v24-52-5,5>>^ De modo que a cidade veio a estar sob sítio até o décimo primeiro ano do Rei Zedequias.

[[v24-52-6]]

^<<v24-52-6,6>>^ No quarto mês, no nono dia do mês, a fome ficou então severa na cidade e não se mostrava haver pão para o povo da terra.^&#42;1^

[NOTE]
====
. “Para o povo da terra.” Hebr.: le‛ám ha·’á·rets.
====

[[v24-52-7]]

^<<v24-52-7,7>>^ Por fim se abriu uma brecha na cidade; e no que se refere a todos os homens de guerra, começaram a fugir e a sair da cidade à noite pelo caminho do portão entre a muralha dupla que há junto ao jardim do rei, enquanto os caldeus estavam em toda a volta contra a cidade; e seguiram pelo caminho do Arabá.

[[v24-52-8]]

^<<v24-52-8,8>>^ E a força militar dos caldeus foi no encalço do rei, e chegaram a alcançar Zedequias nas planícies desérticas de Jericó; e toda a sua própria força militar foi espalhada do seu lado.

[[v24-52-9]]

^<<v24-52-9,9>>^ Pegaram então o rei e trouxeram-no para cima ao rei de Babilônia, em Ribla, na terra de Hamate, para que pronunciasse sobre ele decisões judiciais.

[[v24-52-10]]

^<<v24-52-10,10>>^ E o rei de Babilônia passou a abater os filhos de Zedequias diante dos seus olhos, e também a todos os príncipes de Judá ele abateu em Ribla.

[[v24-52-11]]

^<<v24-52-11,11>>^ E ele cegou os olhos de Zedequias, após o que o rei de Babilônia o prendeu com grilhões de cobre e o levou a Babilônia, e o pôs na casa de custódia, até o dia da sua morte.

[[v24-52-12]]

^<<v24-52-12,12>>^ E no quinto mês, no décimo dia do mês, isto é, [no] décimo nono ano do Rei Nabucodorosor, rei de Babilônia, Nebuzaradã, chefe da guarda pessoal, que estava de pé perante o rei de Babilônia, entrou em Jerusalém.

[[v24-52-13]]

^<<v24-52-13,13>>^ E ele passou a queimar a casa de Jeová e a casa do rei, bem como todas as casas de Jerusalém; e a toda casa grande ele queimou com fogo.

[[v24-52-14]]

^<<v24-52-14,14>>^ E todas as forças militares dos caldeus que estavam com o chefe da guarda pessoal demoliram todas as muralhas de Jerusalém, em todo o redor.

[[v24-52-15]]

^<<v24-52-15,15>>^ E a alguns dos de condição humilde do povo, e o resto do povo que fora deixado na cidade, e os desertores que se bandearam para o rei de Babilônia, e o resto dos operários-mestres, Nebuzaradã, chefe da guarda pessoal, levou ao exílio.

[[v24-52-16]]

^<<v24-52-16,16>>^ E alguns dos de condição humilde do país foram deixados por Nebuzaradã, chefe da guarda pessoal, como vinhateiros e como trabalhadores compulsórios.

[[v24-52-17]]

^<<v24-52-17,17>>^ E as colunas de cobre pertencentes à casa de Jeová, bem como os carrocins e o mar de cobre que havia na casa de Jeová, os caldeus destroçaram e foram carregar todo o cobre deles para Babilônia.

[[v24-52-18]]

^<<v24-52-18,18>>^ E levaram os recipientes, e as pás, e os apagadores, e as tigelas, e as taças, e todos os utensílios de cobre com que se costumava ministrar.

[[v24-52-19]]

^<<v24-52-19,19>>^ E o chefe da guarda pessoal tomou as bacias, e os porta-lumes, e as tigelas, e os recipientes, e os candelabros, e as taças, e as tigelas, que eram de ouro genuíno e que eram de prata genuína.

[[v24-52-20]]

^<<v24-52-20,20>>^ E as duas colunas, o único mar e os doze touros de cobre que havia por baixo [do mar], os carrocins,^&#42;1^ que o Rei Salomão fizera para a casa de Jeová. Não se veio a [tomar] o peso ao cobre deles — de todos estes objetos.

[NOTE]
====
. “Por baixo [do mar], os carrocins”, MTVg; LXX: “por baixo do mar”; Sy: “por baixo dos lados do mar”.
====

[[v24-52-21]]

^<<v24-52-21,21>>^ E quanto às colunas, cada coluna tinha dezoito côvados^&#42;1^ de altura e um cordão de doze côvados é que a rodearia; e sua grossura era da largura de quatro dedos,^&#42;2^ sendo oca.

[NOTE]
====
. O côvado equivalia a 44,5 cm.
. A largura dum dedo equivalia a 1,85 cm.
====

[[v24-52-22]]

^<<v24-52-22,22>>^ E o capitel sobre ela era de cobre, e a altura de um capitel era de cinco côvados; e quanto à rede e às romãs sobre o capitel, em todo o redor, tudo era de cobre; e a segunda coluna tinha o mesmo que estas, também as romãs.

[[v24-52-23]]

^<<v24-52-23,23>>^ E as romãs vieram a ser noventa e seis, aos lados,^&#42;1^ todas as romãs sendo cem sobre a rede em todo o redor.

[NOTE]
====
. Lit.: “barlavento; de onde sopra o vento”.
====

[[v24-52-24]]

^<<v24-52-24,24>>^ Além disso, o chefe da guarda pessoal tomou Seraías, o sacerdote principal, e Sofonias, o segundo sacerdote, e os três guardas das portas,

[[v24-52-25]]

^<<v24-52-25,25>>^ e da cidade ele tomou um oficial da corte, que viera a ser o comissário sobre os homens de guerra, e sete homens dos que tinham acesso ao rei,^&#42;1^ que se achavam na cidade, e o secretário do chefe do exército, e aquele que recrutava o povo da terra,^&#42;2^ e sessenta homens^&#42;3^ do povo da terra, que se achavam no meio da cidade.

[NOTE]
====
. Lit.: “dos que viam a face do rei”.
. “O povo da terra.” Hebr.: ‛am ha·’á·rets.
. “Homens.” Hebr.: ’ish.
====

[[v24-52-26]]

^<<v24-52-26,26>>^ De modo que Nebuzaradã, chefe da guarda pessoal, tomou a estes e os levou ao rei de Babilônia em Ribla.

[[v24-52-27]]

^<<v24-52-27,27>>^ E a estes o rei de Babilônia passou a golpear e a entregar à morte em Ribla, na terra de Hamate. Assim foi Judá ao exílio de cima do seu solo.

[[v24-52-28]]

^<<v24-52-28,28>>^ Este é o povo que Nabucodorosor levou ao exílio no sétimo ano: três mil e vinte e três judeus.

[[v24-52-29]]

^<<v24-52-29,29>>^ No décimo oitavo ano de Nabucodorosor havia de Jerusalém oitocentas e trinta e duas almas.

[[v24-52-30]]

^<<v24-52-30,30>>^ No vigésimo terceiro ano de Nabucodorosor, Nebuzaradã, chefe da guarda pessoal, levou judeus ao exílio: setecentas e quarenta e cinco almas.
Todas as almas foram quatro mil e seiscentas.^&#42;1^

[NOTE]
====
. LXX e 2Rs 25 omitem o conteúdo dos vv. 28-30.
====

[[v24-52-31]]

^<<v24-52-31,31>>^ Por fim aconteceu, no trigésimo sétimo ano do exílio de Joaquim, rei de Judá, no décimo segundo mês, no vigésimo quinto dia do mês, que Evil-Merodaque, rei de Babilônia, no ano em que se tornou rei,^&#42;1^ ergueu a cabeça de Joaquim, rei de Judá, e passou a fazê-lo sair da casa do cárcere.

[NOTE]
====
. Lit.: “de seu reinado”. Hebr.: mal·khu·thóh.
====

[[v24-52-32]]

^<<v24-52-32,32>>^ E começou a falar com ele coisas boas e a pôr seu trono^&#42;1^ mais alto do que os tronos dos [outros] reis que estavam com ele em Babilônia.

[NOTE]
====
. Ou “assento”.
====

[[v24-52-33]]

^<<v24-52-33,33>>^ E tirou-lhe^&#42;1^ sua roupa de preso, e este comia pão diante dele, constantemente, todos os dias da sua vida.

[NOTE]
====
. Lit.: “mudou-lhe”.
====

[[v24-52-34]]

^<<v24-52-34,34>>^ E, quanto à sua subsistência, dava-se-lhe, como questão diária,^&#42;1^ contínua subsistência da parte do rei de Babilônia, até o dia da sua morte, todos os dias da sua vida.

[NOTE]
====
. Lit.: “a coisa dum dia no seu dia”.
====

'''

xref:024-jeremias/024-jeremias-051.adoc#v24-51-0[&#60; Capítulo Anterior] | <<v24-52-0,Topo>> | xref:025-lamentacoes/025-lamentacoes-001.adoc#v25-1-0[Próximo Capítulo &#62;]