include::./index.adoc[]

[[v24-50-0]]
=== Jeremias, 50
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v24-50-1]]

^<<v24-50-1,1>>^ A palavra que Jeová falou a respeito de Babilônia,^&#42;1^ concernente à terra dos caldeus, por meio de Jeremias, o profeta:

[NOTE]
====
. “Babilônia”, LXXVg; MTSy: “Babel”.
====

[[v24-50-2]]

^<<v24-50-2,2>>^ “Contai-o entre as nações e publicai-o. Levantai um sinal de aviso;^&#42;1^ publicai-o. Não oculteis nada. Dizei: ‘Babilônia foi capturada. Bel^&#42;2^ foi envergonhado. Merodaque ficou aterrorizado. As imagens dela foram envergonhadas. Seus ídolos sórdidos ficaram aterrorizados.’

[NOTE]
====
. “Sinal de aviso.” Hebr.: nes.
. “Belus”, LXX.
====

[[v24-50-3]]

^<<v24-50-3,3>>^ Pois subiu contra ela uma nação desde o norte. É aquela que faz da sua terra um assombro, de modo que não se mostrará haver ninguém que more nela. Tanto o homem^&#42;1^ como o animal doméstico se puseram em fuga. Foram-se.”

[NOTE]
====
. “Tanto o homem.” Hebr.: me·’a·dhám.
====

[[v24-50-4]]

^<<v24-50-4,4>>^ “Naqueles dias e naquele tempo”, é a pronunciação de Jeová, “chegarão os filhos de Israel, eles e os filhos de Judá juntos. Andarão, chorando ao andarem, e procurarão a Jeová, seu Deus.

[[v24-50-5]]

^<<v24-50-5,5>>^ Continuarão a perguntar pelo caminho para Sião, com as suas faces naquela direção, [dizendo:] ‘Vinde e juntemo-nos a Jeová num pacto de duração indefinida que não será esquecido.’

[[v24-50-6]]

^<<v24-50-6,6>>^ Meu povo tornou-se um rebanho de criaturas perecedoras. Seus próprios pastores fizeram-nos andar vagueando. Nos montes é que os levaram embora. Do monte foram para o morro. Esqueceram-se do seu lugar de repouso.

[[v24-50-7]]

^<<v24-50-7,7>>^ Todos os que os encontraram devoraram-nos, e seus próprios adversários disseram: ‘Não ficaremos culpados devido ao fato de que pecaram contra Jeová, o lugar de permanência da justiça e a esperança de seus antepassados, Jeová.’”

[[v24-50-8]]

^<<v24-50-8,8>>^ “Ponde-vos em fuga do meio de Babilônia e saí até mesmo da terra dos caldeus, e tornai-vos como os animais de guia^&#42;1^ na frente do rebanho.

[NOTE]
====
. Ou “carneiros e bodes”. Vg: “cabritinhos”.
====

[[v24-50-9]]

^<<v24-50-9,9>>^ Pois eis que desperto e faço subir contra Babilônia uma congregação de grandes nações da terra do norte, e elas certamente se enfileirarão contra ela. De lá é que ela será capturada. Suas flechas são como as de um poderoso, causando a privação de filhos, que não volta sem resultados.

[[v24-50-10]]

^<<v24-50-10,10>>^ E a Caldéia^&#42;1^ tem de tornar-se despojo. Todos os que a despojarem fartar-se-ão”, é a pronunciação de Jeová.

[NOTE]
====
. “Caldéia”, LXXVg; TSy: “a terra dos caldeus”; M: “os caldeus”, mas com um verbo hebr. fem. no sing.
====

[[v24-50-11]]

^<<v24-50-11,11>>^ “Porque vós vos alegráveis, porque vós rejubiláveis quando rapinastes a minha própria herança. Pois escarváveis como a novilha na relva tenra e rincháveis como garanhões.

[[v24-50-12]]

^<<v24-50-12,12>>^ A mãe de vós, homens, ficou muito envergonhada. Aquela que vos deu à luz ficou desapontada. Eis que ela é a menos importante das nações, um ermo árido e uma planície desértica.

[[v24-50-13]]

^<<v24-50-13,13>>^ Por causa da indignação de Jeová, ela não será habitada e terá de tornar-se inteiramente um baldio desértico. Todo aquele que passar por Babilônia olhará espantado e assobiará por causa de todas as suas pragas.

[[v24-50-14]]

^<<v24-50-14,14>>^ “Enfileirai-vos contra Babilônia em todos os lados, todos vós os que entesais o arco. Atirai contra ela. Não poupeis a flecha, pois foi contra Jeová que ela pecou.

[[v24-50-15]]

^<<v24-50-15,15>>^ Lançai um grito de guerra contra ela em todos os lados. Ela deu a sua mão. Suas colunas caíram. Suas muralhas foram derrubadas. Porque é a vingança de Jeová. Vingai-vos dela. Fazei-lhe assim como ela fez.

[[v24-50-16]]

^<<v24-50-16,16>>^ Decepai de Babilônia o semeador e aquele que maneja a foicinha no tempo da ceifa. Por causa da espada que maltrata virar-se-ão, cada um para o seu próprio povo, e fugirão, cada um para a sua própria terra.

[[v24-50-17]]

^<<v24-50-17,17>>^ “Israel é um ovídeo disperso. Os leões é que [o] dispersaram. No primeiro caso, o rei da Assíria o devorou, e neste último caso, Nabucodorosor, rei de Babilônia, roeu-lhe os ossos.

[[v24-50-18]]

^<<v24-50-18,18>>^ Portanto, assim disse Jeová dos exércitos, o Deus de Israel: ‘Eis que volto a minha atenção para o rei de Babilônia e para a sua terra do mesmo modo como voltei a minha atenção para o rei da Assíria.

[[v24-50-19]]

^<<v24-50-19,19>>^ E eu vou trazer Israel de volta à sua pastagem e ele há de pastar no Carmelo e em Basã; e sua alma se saciará na região montanhosa de Efraim e de Gileade.’”

[[v24-50-20]]

^<<v24-50-20,20>>^ “E naqueles dias e naquele tempo”, é a pronunciação de Jeová, “procurar-se-á o erro de Israel, mas ele não existirá; e os pecados de Judá, e não serão achados, pois perdoarei aos que eu deixar remanescer”.

[[v24-50-21]]

^<<v24-50-21,21>>^ “Contra a terra de Merataim^&#42;1^ — sobe contra ela e contra os habitantes de Pecode. Haja um massacre e um devotamento à destruição logo atrás deles”, é a pronunciação de Jeová, “e faze segundo tudo o que te ordenei.

[NOTE]
====
. Significando “Dupla Rebelião”; ou: “Dupla Amargura”.
====

[[v24-50-22]]

^<<v24-50-22,22>>^ Há o ruído de guerra no país e um grande desmoronamento.

[[v24-50-23]]

^<<v24-50-23,23>>^ Oh! como foi cortado e está sendo destroçado o malho de toda a terra! Oh! como Babilônia se tornou um mero assombro entre as nações!

[[v24-50-24]]

^<<v24-50-24,24>>^ Armei-te um laço e foste também apanhada, ó Babilônia, e tu mesma não [o] sabias. Foste achada e também pegada, porque fora contra Jeová que te excitaste.

[[v24-50-25]]

^<<v24-50-25,25>>^ “Jeová abriu seu depósito, e ele traz para fora as armas da sua verberação. Pois há uma obra que o Soberano Senhor, Jeová dos exércitos, tem na terra dos caldeus.

[[v24-50-26]]

^<<v24-50-26,26>>^ Entrai nela desde a parte mais longínqua. Abri os celeiros dela. Aterrai-a, assim como se fazem montes, e devotai-a à destruição. Não venha a ter remanescentes.

[[v24-50-27]]

^<<v24-50-27,27>>^ Massacrai-lhe todos os novilhos. Desçam eles ao abate. Ai deles, pois chegou o seu dia, o tempo de se fixar a atenção neles!

[[v24-50-28]]

^<<v24-50-28,28>>^ “Há o ruído dos que fogem e dos que escapam da terra de Babilônia para contar em Sião a vingança de Jeová, nosso Deus, a vingança pelo seu templo.

[[v24-50-29]]

^<<v24-50-29,29>>^ “Convocai arqueiros contra Babilônia, todos os que entesam o arco. Acampai-vos ao redor dela. Não venha a haver nenhuns que escapem. Retribuí-lhe segundo a sua atuação. Fazei-lhe segundo tudo o que ela fez. Pois foi contra Jeová que ela agiu presunçosamente, contra o Santo de Israel.

[[v24-50-30]]

^<<v24-50-30,30>>^ Por isso cairão os seus jovens nas suas praças públicas e mesmo todos os seus homens de guerra serão silenciados naquele dia”, é a pronunciação de Jeová.

[[v24-50-31]]

^<<v24-50-31,31>>^ “Eis que sou contra ti, ó Presunção”, é a pronunciação do Soberano Senhor, Jeová dos exércitos, “pois tem de chegar o teu dia, o tempo em que terei de fixar a atenção em ti.

[[v24-50-32]]

^<<v24-50-32,32>>^ E a Presunção há de tropeçar e cair, e não terá quem a faça levantar-se. E eu vou acender um fogo nas suas cidades e este terá de devorar todos os seus arredores.”

[[v24-50-33]]

^<<v24-50-33,33>>^ Assim disse Jeová dos exércitos: “Os filhos de Israel e os filhos de Judá estão sendo oprimidos juntos e são agarrados por todos os que os levam cativos. Negaram-se a deixá-los ir.

[[v24-50-34]]

^<<v24-50-34,34>>^ Forte é seu Resgatador,^&#42;1^ cujo nome é Jeová dos exércitos. Sem falta, ele pleiteará a sua causa, para dar realmente repouso à terra^&#42;2^ e causar agitação aos habitantes de Babilônia.”

[NOTE]
====
. “Seu Resgatador (Redentor).” Ampliando-se a idéia: “Seu Vingador (Vindicador).” Hebr.: go·’alám; lat.: re·dém·ptor e·ó·rum. Veja Jó 19:25 n. e Sal 19:14 n.
. “À terra.” Hebr.: ha·’á·rets.
====

[[v24-50-35]]

^<<v24-50-35,35>>^ “Há uma espada contra os caldeus”, é a pronunciação de Jeová, “e contra os habitantes de Babilônia, e contra os seus príncipes, e contra os seus sábios.

[[v24-50-36]]

^<<v24-50-36,36>>^ Há uma espada contra os paroleiros e eles hão de agir tolamente. Há uma espada contra os seus poderosos e eles ficarão realmente aterrorizados.

[[v24-50-37]]

^<<v24-50-37,37>>^ Há uma espada contra os seus cavalos, e contra os seus carros de guerra, e contra toda a mistura de gente que há no seu meio, e eles hão de tornar-se [como] mulheres. Há uma espada contra os seus tesouros e estes serão realmente saqueados.

[[v24-50-38]]

^<<v24-50-38,38>>^ Há uma devastação sobre as suas águas e elas terão de secar-se. Pois é uma terra de imagens entalhadas, e por causa das [suas] visões aterradoras continuam a agir como doidos.

[[v24-50-39]]

^<<v24-50-39,39>>^ Por isso morarão os freqüentadores de regiões áridas^&#42;1^ com os animais uivantes, e terão de morar nela avestruzes;^&#42;2^ e nunca mais se morará nela, nem residirá ela de geração em geração.”

[NOTE]
====
. “Os dragões”, lat.: dra·có·nes.
. “Avestruzes.” Hebr.: benóhth ya·‛anáh. Veja Le 11:16 n.: “avestruz”.
====

[[v24-50-40]]

^<<v24-50-40,40>>^ “Assim como se deu no derrubamento de Sodoma e de Gomorra, e das suas [cidades] vizinhas, por Deus”, é a pronunciação de Jeová, “não morará ali nenhum homem,^&#42;1^ nem residirá nela o filho da humanidade^&#42;2^ como forasteiro.

[NOTE]
====
. “Homem.” Hebr.: ’ish.
. Ou “o filho de homens”. Hebr.: ben-’a·dhám.
====

[[v24-50-41]]

^<<v24-50-41,41>>^ “Eis que do norte está chegando um povo; e mesmo uma grande nação e grandiosos reis serão despertados desde as partes mais remotas da terra.

[[v24-50-42]]

^<<v24-50-42,42>>^ Eles manejam o arco e o dardo. São cruéis e não terão misericórdia. O ruído deles é como o mar turbulento, e montarão cavalos; estão enfileirados como um só homem para a guerra contra ti, ó filha de Babilônia.

[[v24-50-43]]

^<<v24-50-43,43>>^ “O rei de Babilônia ouviu a notícia sobre eles e suas mãos se abaixaram. Há aflição! foi tomado de dores agudas, igual à mulher que dá à luz.

[[v24-50-44]]

^<<v24-50-44,44>>^ “Eis que subirá alguém qual leão desde as orgulhosas [moitas] junto ao Jordão ao durável lugar de permanência, mas num instante os farei correr para longe dela. E encarregarei dela o escolhido. Pois quem é igual a mim e quem me desafiará, e quem, pois, é o pastor que pode ficar de pé diante de mim?

[[v24-50-45]]

^<<v24-50-45,45>>^ Portanto, ouvi o conselho de Jeová, que formulou contra Babilônia, e seus pensamentos, que teve contra a terra dos caldeus. Por certo, os filhotes do rebanho serão arrastados. Seguramente, por causa deles fará que se torne desolado seu lugar de permanência.

[[v24-50-46]]

^<<v24-50-46,46>>^ Diante do ruído, [quando] Babilônia tiver sido tomada, certamente se fará tremer a terra e entre as nações se ouvirá um clamor.”

'''

xref:024-jeremias/024-jeremias-049.adoc#v24-49-0[&#60; Capítulo Anterior] | <<v24-50-0,Topo>> | xref:024-jeremias/024-jeremias-051.adoc#v24-51-0[Próximo Capítulo &#62;]