include::./index.adoc[]

[[v24-10-0]]
=== Jeremias, 10
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v24-10-1]]

^<<v24-10-1,1>>^ Ouvi a palavra que Jeová falou contra vós, ó casa de Israel.

[[v24-10-2]]

^<<v24-10-2,2>>^ Assim disse Jeová: “Não aprendais absolutamente o caminho das nações e não fiqueis aterrorizados mesmo diante dos sinais dos céus, porque as nações ficam aterrorizadas com eles.

[[v24-10-3]]

^<<v24-10-3,3>>^ Pois os costumes^&#42;1^ dos povos são apenas uma exalação, porque foi somente uma árvore da floresta que se cortou, trabalho das mãos do artífice com o podão.

[NOTE]
====
. Ou “estatutos”. Sy: “objetos de medo; ídolos”.
====

[[v24-10-4]]

^<<v24-10-4,4>>^ Embelezam-no com prata e com ouro. Firmam-nos com pregos e com martelos, para que nenhum vacile.

[[v24-10-5]]

^<<v24-10-5,5>>^ São como o espantalho do pepinal e não podem falar. Impreterivelmente são carregados, porque não podem dar passos. Não tenhais medo deles, porque não podem fazer nada calamitoso, e ainda mais, não está neles fazer qualquer bem.”

[[v24-10-6]]

^<<v24-10-6,6>>^ De modo algum há alguém igual a ti, ó Jeová. Tu és grande e teu nome é grande em potência.

[[v24-10-7]]

^<<v24-10-7,7>>^ Quem não te temeria, ó Rei das nações, pois isto é próprio para contigo; porque entre todos os sábios das nações e entre todos os seus reinados, de modo algum há alguém igual a ti.

[[v24-10-8]]

^<<v24-10-8,8>>^ E ao mesmo tempo mostram ser irracionais e estúpidos. Uma árvore é meramente uma exortação de vaidades.

[[v24-10-9]]

^<<v24-10-9,9>>^ Prata laminada é o que se traz até mesmo de Társis, e ouro de Ufaz,^&#42;1^ trabalho de artífice e das mãos dum trabalhador em metal; sua vestimenta é de linha azul e de lã tingida de roxo. São todos trabalho de gente hábil.

[NOTE]
====
. “Ufaz”, MVg; TThSy: “Ofir”.
====

[[v24-10-10]]

^<<v24-10-10,10>>^ Mas Jeová é verdadeiramente Deus.^&#42;1^ Ele é o Deus vivente e o Rei por tempo indefinido. Por causa da sua indignação tremerá a terra, e nação alguma poderá suportar a sua verberação.

[NOTE]
====
. “É verdadeiramente Deus.” Hebr.: ’Elo·hím ’eméth.
====

[[v24-10-11]]

^<<v24-10-11,11>>^ Assim lhes direis vós: “Os deuses^&#42;1^ que não fizeram os próprios céus e a terra são os que perecerão da terra e de debaixo destes céus.”^&#42;2^

[NOTE]
====
. “Os deuses.” Aram.: ’ela·hai·yá’. Este v. inteiro foi escrito em aram.
. “Céus.” Aram.: shemai·yá’.
====

[[v24-10-12]]

^<<v24-10-12,12>>^ Ele^&#42;1^ é Quem fez a terra pelo seu poder, Aquele que estabeleceu firmemente o solo produtivo^&#42;2^ pela sua sabedoria, e Aquele que pelo seu entendimento estendeu os céus.

[NOTE]
====
. “Ele”, MVg; LXXSy: “Jeová”.
. “Solo produtivo.” Hebr.: te·vél; LXX: “terra habitada”; lat.: ór·bem, “círculo”, isto é, da terra.
====

[[v24-10-13]]

^<<v24-10-13,13>>^ À [sua] voz dá-se por ele uma turbulência de águas nos céus e ele faz vapores^&#42;1^ ascender desde a extremidade^&#42;2^ da terra. Fez até mesmo condutos^&#42;3^ para a chuva e faz sair o vento^&#42;4^ dos seus depósitos.

[NOTE]
====
. Ou “nuvens vaporosas”.
. Veja 25:31, 33 n.
. “Condutos”, quando se lê beda·qím em vez de bera·qím, “relâmpagos”; MTLXXSyVg: “relâmpagos”. Veja JTS, Vol. 3, 1952, pp. 214-216. Veja Sal 135:7 n.: “condutos”.
. “Vento.” Hebr.: rú·ahh; lat.: vén·tum; gr.: fos, “luz”.
====

[[v24-10-14]]

^<<v24-10-14,14>>^ Cada homem^&#42;1^ se comportou tão irracionalmente de modo que não sabe [nada]. Cada trabalhador em metal certamente se sentirá envergonhado da imagem esculpida; porque a sua imagem fundida é uma falsidade, e não há espírito^&#42;2^ nelas.

[NOTE]
====
. “Homem.” Hebr.: ’a·dhám.
. Ou “fôlego”. Hebr.: rú·ahh; gr.: pneú·ma; lat.: spí·ri·tus.
====

[[v24-10-15]]

^<<v24-10-15,15>>^ São vaidade,^&#42;1^ trabalho de zombaria. Perecerão no tempo de se fixar a atenção nelas.

[NOTE]
====
. Ou “uma exalação”.
====

[[v24-10-16]]

^<<v24-10-16,16>>^ O Quinhão de Jacó não é como tais coisas, porque ele é o Formador de tudo, e Israel é a vara^&#42;1^ da sua herança. Jeová dos exércitos é o seu nome.

[NOTE]
====
. Ou “tribo”. Hebr.: shé·vet.
====

[[v24-10-17]]

^<<v24-10-17,17>>^ Recolhe do chão o teu fardo de carga, ó mulher que moras em aperto.

[[v24-10-18]]

^<<v24-10-18,18>>^ Pois assim disse Jeová: “Eis que nesta ocasião atiro com a funda os habitantes da terra, e vou causar-lhes aflição, para que descubram [isso].”

[[v24-10-19]]

^<<v24-10-19,19>>^ Ai de mim por causa do meu quebrantamento! Meu golpe tornou-se mórbido.^&#42;1^ E eu mesmo disse: “Decerto esta é a minha doença e eu a suportarei.

[NOTE]
====
. Ou “crônico; incurável”.
====

[[v24-10-20]]

^<<v24-10-20,20>>^ Minha própria tenda foi assolada e meus próprios cordões de tenda foram todos rompidos. Meus próprios filhos se foram de mim e não existem mais. Não há mais ninguém que arme a minha tenda ou levante os meus panos de tenda.

[[v24-10-21]]

^<<v24-10-21,21>>^ Porque os pastores se comportaram irracionalmente e nem mesmo buscaram a Jeová. Por isso é que não agiram com perspicácia e foram espalhados todos os seus animais de pasto.”

[[v24-10-22]]

^<<v24-10-22,22>>^ Escuta! Uma notícia! Eis que ela^&#42;1^ chegou, também um grande retumbo desde a terra do norte, a fim de fazer das cidades de Judá um baldio desolado, guarida de chacais.

[NOTE]
====
. “Ela”, hebr. fem. sing., referindo-se à “notícia”.
====

[[v24-10-23]]

^<<v24-10-23,23>>^ Bem sei, ó Jeová, que não é do homem terreno^&#42;1^ o seu caminho. Não é do homem^&#42;2^ que anda o dirigir o seu passo.

[NOTE]
====
. “Do homem terreno.” Hebr.: la·’a·dhám.
. “Não é do homem.” Hebr.: lo’-le’ísh.
====

[[v24-10-24]]

^<<v24-10-24,24>>^ Corrige-me, ó Jeová, porém, com julgamento; não na tua ira, para que não me reduzas a nada.

[[v24-10-25]]

^<<v24-10-25,25>>^ Derrama teu furor sobre as nações que te desconsideraram^&#42;1^ e sobre as famílias que nem mesmo invocaram o teu nome. Pois consumiram a Jacó. Sim, consumiram-no e persistem em exterminá-lo; e desolaram-lhe o lugar de permanência.

[NOTE]
====
. Ou “que não chegaram a conhecer-te”.
====

'''

xref:024-jeremias/024-jeremias-009.adoc#v24-9-0[&#60; Capítulo Anterior] | <<v24-10-0,Topo>> | xref:024-jeremias/024-jeremias-011.adoc#v24-11-0[Próximo Capítulo &#62;]