include::./index.adoc[]

[[v24-36-0]]
=== Jeremias, 36
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v24-36-1]]

^<<v24-36-1,1>>^ Aconteceu, então, no quarto ano de Jeoiaquim, filho de Josias, rei de Judá, que veio a haver esta palavra para Jeremias, da parte de Jeová, dizendo:

[[v24-36-2]]

^<<v24-36-2,2>>^ “Toma para ti um rolo de livro e tens de escrever nele todas as palavras que te falei contra Israel e contra Judá, e contra todas as nações, desde o dia em que te falei, desde os dias de Josias, até o dia de hoje.

[[v24-36-3]]

^<<v24-36-3,3>>^ Talvez os da casa de Judá escutem [falar de] toda a calamidade que penso em causar-lhes, com o fim de que recuem, cada um do seu mau caminho, e para que eu realmente perdoe seu erro e seu pecado.”

[[v24-36-4]]

^<<v24-36-4,4>>^ E Jeremias passou a chamar Baruque,^&#42;1^ filho de Nerias, para que Baruque escrevesse da boca de Jeremias todas as palavras de Jeová, que Ele lhe falara, no rolo do livro.

[NOTE]
====
. É provável que seu nome completo fosse Berequias, significando “Abençoado por Jeová”.
====

[[v24-36-5]]

^<<v24-36-5,5>>^ Jeremias ordenou então a Baruque, dizendo: “Estou encerrado. Não posso entrar na casa de Jeová.

[[v24-36-6]]

^<<v24-36-6,6>>^ E tu mesmo tens de entrar e ler alto, do rolo que escreveste da minha boca, as palavras de Jeová aos ouvidos do povo na casa de Jeová, no dia do jejum; e também aos ouvidos de todo o Judá, que estão entrando das suas cidades, deves lê-las alto.

[[v24-36-7]]

^<<v24-36-7,7>>^ Talvez se lance seu pedido de favor diante de Jeová e eles recuem, cada um do seu mau caminho, pois grande é a ira e o furor de que Jeová falou contra este povo.”

[[v24-36-8]]

^<<v24-36-8,8>>^ E Baruque, filho de Nerias, passou a fazer segundo tudo o que Jeremias, o profeta, lhe ordenara, para ler alto do livro as palavras de Jeová, na casa de Jeová.

[[v24-36-9]]

^<<v24-36-9,9>>^ Aconteceu, então, no quinto ano de Jeoiaquim, filho de Josias, rei de Judá, no nono mês, que todo o povo em Jerusalém e todo o povo que entrava das cidades de Judá em Jerusalém proclamaram um jejum perante Jeová.

[[v24-36-10]]

^<<v24-36-10,10>>^ E Baruque começou a ler alto do livro as palavras de Jeremias, na casa de Jeová, no refeitório de Gemarias,^&#42;1^ filho de Safã, o copista, no pátio superior, à entrada do portão novo da casa de Jeová, aos ouvidos de todo o povo.

[NOTE]
====
. Significando “Jeová Aperfeiçoou”. Hebr.: Gemar·yá·hu.
====

[[v24-36-11]]

^<<v24-36-11,11>>^ E Micaías,^&#42;1^ filho de Gemarias, filho de Safã, chegou a ouvir do livro todas as palavras de Jeová.

[NOTE]
====
. Significando: “Quem É Semelhante a Jeová?” Hebr.: Mi·khaí·hu.
====

[[v24-36-12]]

^<<v24-36-12,12>>^ Então desceu à casa do rei, ao refeitório do secretário, e eis que estavam ali sentados todos os príncipes: Elisama, o secretário, e Delaías,^&#42;1^ filho de Semaías,^&#42;2^ e Elnatã, filho de Acbor, e Gemarias, filho de Safã, e Zedequias, filho de Hananias,^&#42;3^ e todos os outros príncipes.

[NOTE]
====
. “E Delaías.” Hebr.: u·Dhela·yá·hu, significando “Jeová Puxou Para Cima [para libertação]”.
. Significando “Jeová Ouviu”. Hebr.: Shema‛·yá·hu.
. Significando “Jeová Tem Mostrado Favor; Jeová Tem Sido Clemente”. Hebr.: Hhanan·yá·hu.
====

[[v24-36-13]]

^<<v24-36-13,13>>^ E Micaías passou a contar-lhes todas as palavras que ouvira quando Baruque leu alto do livro aos ouvidos do povo.

[[v24-36-14]]

^<<v24-36-14,14>>^ Então todos os príncipes mandaram Jeudi, filho de Netanias,^&#42;1^ filho de Selemias,^&#42;2^ filho de Cusi, dizer a Baruque: “O rolo do qual estavas lendo alto aos ouvidos do povo — toma-o na tua mão e vem.” Concordemente, Baruque, filho de Nerias,^&#42;3^ tomou o rolo na mão e entrou até eles.

[NOTE]
====
. Significando “Jeová Deu”. Hebr.: Nethan·yá·hu.
. Significando “Jeová É Recompensa”; ou: “Sacrifício de Participação em Comum de Jeová.” Hebr.: She·lem·yá·hu.
. Significando “Minha Lâmpada É Jeová”. Hebr.: Ne·ri·yá·hu.
====

[[v24-36-15]]

^<<v24-36-15,15>>^ Então disseram-lhe: “Senta-te, por favor, e lê-o alto aos nossos ouvidos.” De modo que Baruque o leu alto aos ouvidos deles.

[[v24-36-16]]

^<<v24-36-16,16>>^ Ora, aconteceu que, assim que ouviram todas as palavras, olharam-se uns aos outros apavorados; e passaram a dizer a Baruque: “Sem falta contaremos todas estas palavras ao rei.”

[[v24-36-17]]

^<<v24-36-17,17>>^ E perguntaram a Baruque, dizendo: “Conta-nos, por favor: Como é que escreveste todas estas palavras da sua boca?”

[[v24-36-18]]

^<<v24-36-18,18>>^ Baruque disse-lhes então: “Da sua boca ele me declarava todas estas palavras e eu escrevia com tinta no livro.”

[[v24-36-19]]

^<<v24-36-19,19>>^ Por fim disseram os príncipes a Baruque: “Vai, esconde-te, tu e Jeremias, para que absolutamente ninguém saiba onde estais.”

[[v24-36-20]]

^<<v24-36-20,20>>^ Eles entraram então até o rei, no pátio, e o rolo eles confiaram ao refeitório de Elisama, o secretário; e começaram a contar todas as palavras aos ouvidos do rei.

[[v24-36-21]]

^<<v24-36-21,21>>^ Portanto, o rei mandou Jeudi apanhar o rolo. Concordemente, ele o tirou do refeitório de Elisama, o secretário. E Jeudi começou a lê-lo alto aos ouvidos do rei e aos ouvidos de todos os príncipes que estavam de pé junto ao rei.

[[v24-36-22]]

^<<v24-36-22,22>>^ E o rei estava sentado na casa de inverno, no nono mês,^&#42;1^ havendo um braseiro aceso diante dele.

[NOTE]
====
. “No nono mês”, isto é, quisleu, nome pós-exílico do nono mês lunar judaico que corresponde à última parte de novembro e à primeira parte de dezembro. Veja Ap. 8B.
====

[[v24-36-23]]

^<<v24-36-23,23>>^ Sucedeu então que, assim que Jeudi lera três ou quatro páginas-colunas, passou a rasgá-lo com a faca do secretário, lançando-o então no fogo que [ardia] no braseiro, até que o rolo inteiro acabou no fogo que [ardia] no braseiro.

[[v24-36-24]]

^<<v24-36-24,24>>^ E não estavam apavorados; o rei e todos os seus servos, que estavam escutando todas estas palavras, tampouco rasgaram as suas vestes.

[[v24-36-25]]

^<<v24-36-25,25>>^ E até mesmo Elnatã, e Delaías,^&#42;1^ e Gemarias^&#42;2^ instaram com o rei para que não queimasse o rolo, mas ele não os escutou.

[NOTE]
====
. Veja v. 12 n.: “Delaías”.
. Veja v. 10 n.
====

[[v24-36-26]]

^<<v24-36-26,26>>^ Além disso, o rei ordenou a Jerameel, filho do rei, e a Seraías,^&#42;1^ filho de Azriel, e a Selemias,^&#42;2^ filho de Abdeel, que trouxessem Baruque, o secretário, e Jeremias, o profeta. Mas Jeová os manteve escondidos.

[NOTE]
====
. Significando “Jeová Contendeu (Perseverou)”. Hebr.: Sera·yá·hu.
. Veja v. 14 n.: “Selemias”.
====

[[v24-36-27]]

^<<v24-36-27,27>>^ E veio a haver adicionalmente a palavra de Jeová para Jeremias, depois que o rei queimara o rolo com as palavras que Baruque escrevera da boca de Jeremias, dizendo:

[[v24-36-28]]

^<<v24-36-28,28>>^ “Toma para ti novamente um rolo, um outro, e escreve nele todas as primeiras palavras que mostraram estar no primeiro rolo, queimado por Jeoiaquim, rei de Judá.

[[v24-36-29]]

^<<v24-36-29,29>>^ E deves dizer contra Jeoiaquim, rei de Judá: ‘Assim disse Jeová: “Tu mesmo queimaste este rolo, dizendo: ‘Por que é que escreveste nele, dizendo: “O rei de Babilônia virá sem falta e certamente arruinará esta terra e fará cessar nela homem^&#42;1^ e animal”?’

[NOTE]
====
. Ou “homem terreno”. Hebr.: ’a·dhám.
====

[[v24-36-30]]

^<<v24-36-30,30>>^ Portanto, assim disse Jeová contra Jeoiaquim, rei de Judá: ‘Ele não virá a ter ninguém sentado no trono de Davi e seu próprio cadáver tornar-se-á algo lançado fora ao calor do dia e à geada da noite.

[[v24-36-31]]

^<<v24-36-31,31>>^ E eu vou ajustar contas com ele, e com a sua descendência, e com os seus servos, pelo seu erro, e vou trazer sobre eles e sobre os habitantes de Jerusalém, bem como sobre os homens^&#42;1^ de Judá, toda a calamidade que proferi contra eles, e eles não escutaram.’”’”

[NOTE]
====
. “Homens de.” Hebr.: ’ish.
====

[[v24-36-32]]

^<<v24-36-32,32>>^ E o próprio Jeremias tomou outro rolo e deu-o então a Baruque, filho de Nerias, o secretário, que passou a escrever nele da boca de Jeremias todas as palavras do livro que Jeoiaquim, rei de Judá, queimara no fogo; e acrescentaram-se-lhes muitas outras palavras semelhantes a estas.

'''

xref:024-jeremias/024-jeremias-035.adoc#v24-35-0[&#60; Capítulo Anterior] | <<v24-36-0,Topo>> | xref:024-jeremias/024-jeremias-037.adoc#v24-37-0[Próximo Capítulo &#62;]