include::./index.adoc[]

[[v24-9-0]]
=== Jeremias, 9
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v24-9-1]]

^<<v24-9-1,1>>^ Quem dera que a minha cabeça fosse [de] águas e que os meus olhos fossem uma fonte de lágrimas! Então eu poderia chorar dia e noite pelos mortos da filha do meu povo.^&#42;1^

[NOTE]
====
. MLXX terminam aqui o capítulo 8, sendo este o v. 23.
====

[[v24-9-2]]

^<<v24-9-2,2>>^ Quem me dera ter no ermo uma pousada para viajantes! Então eu deixaria meu povo e iria para longe dele, porque todos eles são adúlteros,^&#42;1^ uma assembléia solene de [homens] traiçoeiros;

[NOTE]
====
. “Adúlteros.” Lat.: a·dúl·te·ri.
====

[[v24-9-3]]

^<<v24-9-3,3>>^ e eles retesam a sua língua em falsidade, como seu arco; mas não foi em fidelidade que se mostraram poderosos na terra.
“Pois saíram de maldade em maldade, e desconsideraram até mesmo a mim”, é a pronunciação de Jeová.

[[v24-9-4]]

^<<v24-9-4,4>>^ “Guardai-vos, cada um do seu próprio companheiro, e não confieis em nenhum irmão. Porque até mesmo cada irmão positivamente [o] suplantaria e mesmo cada companheiro andaria como mero caluniador,

[[v24-9-5]]

^<<v24-9-5,5>>^ e continuam a ludibriar cada um o seu companheiro; e não falam absolutamente a verdade. Ensinaram sua língua a falar falsidade. Fatigaram-se apenas em cometer faltas.

[[v24-9-6]]

^<<v24-9-6,6>>^ “Estás assentado no meio de engano. Por meio de engano negaram-se a conhecer-me”, é a pronunciação de Jeová.

[[v24-9-7]]

^<<v24-9-7,7>>^ Portanto, assim disse Jeová dos exércitos: “Eis que os estou refinando e terei de examiná-los, pois, de que outro modo agiria por causa da filha do meu povo?

[[v24-9-8]]

^<<v24-9-8,8>>^ Sua língua é uma flecha mortífera.^&#42;1^ Engano é o que falou. Com a sua boca, é de paz que [a pessoa] está falando com o seu próprio companheiro; mas no seu íntimo arma a sua emboscada.”

[NOTE]
====
. “Uma flecha mortífera”, M; Mmargem: “uma flecha martelada”; mediante outra derivação: “uma flecha de madeira [arco] especial”.
====

[[v24-9-9]]

^<<v24-9-9,9>>^ “Por causa destas coisas, acaso não devia eu ajustar contas com eles?” é a pronunciação de Jeová. “Ou não devia a minha alma vingar-se de uma nação tal como esta?

[[v24-9-10]]

^<<v24-9-10,10>>^ Sobre os montes levantarei choro e lamentação, e sobre as pastagens do ermo, uma endecha; pois terão sido queimados, de modo que não há homem que passe [ali] e realmente não se ouvirá o som de gado. Terão fugido tanto a criatura voadora dos céus como o animal; terão ido embora.

[[v24-9-11]]

^<<v24-9-11,11>>^ E eu vou fazer de Jerusalém montões de pedras, guarida de chacais; e das cidades de Judá farei um baldio desolado, sem habitante.

[[v24-9-12]]

^<<v24-9-12,12>>^ “Quem é o homem sábio, para que entenda isto, sim, aquele a quem falou a boca de Jeová, para que o conte? Por que razão devia o país realmente perecer, ser realmente queimado como o ermo, sem que alguém passe por ele?”

[[v24-9-13]]

^<<v24-9-13,13>>^ E Jeová passou a dizer: “Por terem abandonado a minha lei que dei [para estar] diante deles, e [por] não terem obedecido à minha voz e não terem andado nela,^&#42;1^

[NOTE]
====
. “Nela”, hebr. fem. sing., referindo-se à “lei”.
====

[[v24-9-14]]

^<<v24-9-14,14>>^ mas terem andado atrás da obstinação do seu coração e atrás das imagens de Baal,^&#42;1^ que seus pais lhes ensinaram;

[NOTE]
====
. Ou “os Baalins”.
====

[[v24-9-15]]

^<<v24-9-15,15>>^ por isso, assim disse Jeová dos exércitos, o Deus^&#42;1^ de Israel: ‘Eis que faço que eles, isto é, este povo, comam absinto, e vou fazê-los beber água envenenada;

[NOTE]
====
. “O Deus de.” Hebr.: ’Elo·héh.
====

[[v24-9-16]]

^<<v24-9-16,16>>^ e vou espalhá-los entre nações que nem eles nem seus pais conheciam e vou enviar atrás deles a espada até que eu os tenha exterminado.’

[[v24-9-17]]

^<<v24-9-17,17>>^ “Assim disse Jeová dos exércitos: ‘Comportai-vos com entendimento e chamai as cantoras de endechas, para que venham; e até mesmo mandai [chamar] as mulheres hábeis,^&#42;1^ para que venham,

[NOTE]
====
. Lit.: “sábias”.
====

[[v24-9-18]]

^<<v24-9-18,18>>^ e para que se apressem e elevem sobre nós uma lamentação. E vertam os nossos olhos lágrimas e escorra água dos nossos próprios olhos radiantes.

[[v24-9-19]]

^<<v24-9-19,19>>^ Pois é a voz de lamentação que se ouviu de Sião: “Como fomos assolados! Como nos sentimos envergonhados! Pois abandonamos o país; pois lançaram^&#42;1^ fora as nossas residências.”^&#42;2^

[NOTE]
====
. “Lançaram”, MSy; LXX: “lançamos”.
. Ou “pois as nossas residências foram lançadas fora”, em harmonia com Vg.
====

[[v24-9-20]]

^<<v24-9-20,20>>^ Mas ouvi, ó mulheres, a palavra de Jeová, e aceite vosso ouvido a palavra da sua boca. Ensinai então às vossas filhas uma lamentação, e cada mulher à sua companheira, uma endecha.

[[v24-9-21]]

^<<v24-9-21,21>>^ Porque a morte subiu pelas nossas janelas; entrou nas nossas torres de habitação, a fim de decepar da rua a criança, das praças públicas, os jovens.’

[[v24-9-22]]

^<<v24-9-22,22>>^ “Fala: ‘Assim é a pronunciação de Jeová: “Os cadáveres do gênero humano^&#42;1^ também terão de cair qual estrume sobre a face do campo e quais gavelas de cereal recém-segado atrás do ceifeiro, sem que alguém faça o recolhimento.”’”

[NOTE]
====
. Ou “homens”. Hebr.: ha·’a·dhám.
====

[[v24-9-23]]

^<<v24-9-23,23>>^ Assim disse Jeová: “Não se jacte o sábio da sua sabedoria, nem se jacte o poderoso da sua potência. Não se jacte o rico das suas riquezas.”

[[v24-9-24]]

^<<v24-9-24,24>>^ “Mas quem se jacta, jacte-se da seguinte coisa: de ter perspicácia e de ter conhecimento de mim, que eu sou Jeová, Aquele que usa de benevolência, de juízo^&#42;1^ e de justiça na terra; porque é destas coisas que me agrado”, é a pronunciação de Jeová.

[NOTE]
====
. Ou “julgamento”. Hebr.: mish·pát.
====

[[v24-9-25]]

^<<v24-9-25,25>>^ “Eis que vêm dias”, é a pronunciação de Jeová, “e eu vou ajustar contas com todo o circunciso [mas ainda] na incircuncisão,^&#42;1^

[NOTE]
====
. Ou “no [seu] prepúcio”, sinal de incircuncisão. Ou “entre a incircuncisão [os incircuncisos, que têm prepúcio]”.
====

[[v24-9-26]]

^<<v24-9-26,26>>^ com o Egito, e com Judá, e com Edom, e com os filhos de Amom, e com Moabe, e com todos os de cabelo cortado nas têmporas, que moram no ermo; porque todas as nações são incircuncisas e toda a casa de Israel é incircuncisa no coração”.

'''

xref:024-jeremias/024-jeremias-008.adoc#v24-8-0[&#60; Capítulo Anterior] | <<v24-9-0,Topo>> | xref:024-jeremias/024-jeremias-010.adoc#v24-10-0[Próximo Capítulo &#62;]