include::./index.adoc[]

[[v24-43-0]]
=== Jeremias, 43
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v24-43-1]]

^<<v24-43-1,1>>^ Ora, aconteceu que, assim que Jeremias acabara de falar a todo o povo todas as palavras de Jeová, seu Deus, com que Jeová, seu Deus, o enviara a eles, sim, todas estas palavras,

[[v24-43-2]]

^<<v24-43-2,2>>^ Azarias, filho de Osaías, e Joanã, filho de Careá, e todos os homens presunçosos passaram a dizer a Jeremias: “É uma falsidade o que estás falando. Jeová, nosso Deus, não te enviou, dizendo: ‘Não entreis no Egito para residir ali como forasteiros.’

[[v24-43-3]]

^<<v24-43-3,3>>^ Mas Baruque, filho de Nerias, te está instigando contra nós com o objetivo de nos entregar na mão dos caldeus, para sermos mortos ou para sermos levados ao exílio em Babilônia.”

[[v24-43-4]]

^<<v24-43-4,4>>^ E Joanã, filho de Careá, e todos os chefes das forças militares, bem como todo o povo, não obedeceram à voz de Jeová para continuar a morar na terra de Judá.

[[v24-43-5]]

^<<v24-43-5,5>>^ Portanto, Joanã, filho de Careá, e todos os chefes das forças militares tomaram todo o restante de Judá que retornara de todas as nações, às quais tinham sido dispersos, para residirem por um tempo na terra de Judá,

[[v24-43-6]]

^<<v24-43-6,6>>^ sim, os varões vigorosos, e as esposas, e as criancinhas, e as filhas do rei, e toda alma^&#42;1^ que Nebuzaradã, chefe da guarda pessoal, deixara ficar com Gedalias, filho de Aicão, filho de Safã, e Jeremias, o profeta, e Baruque, filho de Nerias.

[NOTE]
====
. Veja Ap. 4A.
====

[[v24-43-7]]

^<<v24-43-7,7>>^ E por fim entraram na terra do Egito, pois não obedeceram à voz de Jeová; e aos poucos chegaram até Tafnes.

[[v24-43-8]]

^<<v24-43-8,8>>^ Então veio a haver a palavra de Jeová para Jeremias em Tafnes, dizendo:

[[v24-43-9]]

^<<v24-43-9,9>>^ “Toma na tua mão grandes pedras e tens de encobri-las na argamassa no terraço de tijolos à entrada da casa de Faraó, em Tafnes, perante os olhos dos homens judeus.

[[v24-43-10]]

^<<v24-43-10,10>>^ E tens de dizer-lhes: ‘Assim disse Jeová dos exércitos, o Deus de Israel: “Eis que envio [mensageiros] e vou trazer Nabucodorosor, rei de Babilônia, meu servo, e vou colocar seu trono diretamente por cima destas pedras que encobri, e ele certamente armará sobre elas sua tenda de gala.^&#42;1^

[NOTE]
====
. Ou “seu dossel”; ou: “seu tapete”.
====

[[v24-43-11]]

^<<v24-43-11,11>>^ E ele terá de entrar e golpear a terra do Egito. Quem estiver [destinado] para a praga mortífera, ficará para a praga mortífera, e quem estiver [destinado] para o cativeiro, ficará para o cativeiro, e quem estiver [destinado] para a espada, ficará para a espada.

[[v24-43-12]]

^<<v24-43-12,12>>^ E eu vou acender um fogo nas casas dos deuses do Egito; e ele certamente os queimará e os levará cativos, e envolver-se-á na terra do Egito assim como o pastor se envolve na sua veste, e realmente sairá dali em paz.

[[v24-43-13]]

^<<v24-43-13,13>>^ E ele certamente destroçará as colunas de Bete-Semes,^&#42;1^ que está na terra do Egito; e as casas dos deuses do Egito ele queimará com fogo.”’”

[NOTE]
====
. Lit.: “Casa do Sol.” Hebr.: Behth Shé·mesh; lat.: dó·mus só·lis; gr.: He·lí·ou pó·le·os, “Cidade do Sol”.
====

'''

xref:024-jeremias/024-jeremias-042.adoc#v24-42-0[&#60; Capítulo Anterior] | <<v24-43-0,Topo>> | xref:024-jeremias/024-jeremias-044.adoc#v24-44-0[Próximo Capítulo &#62;]