include::./index.adoc[]

[[v24-6-0]]
=== Jeremias, 6
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v24-6-1]]

^<<v24-6-1,1>>^ Abrigai-vos, ó filhos de Benjamim, do meio de Jerusalém; e tocai a buzina^&#42;1^ em Tecoa. E levantai um sinal de fogo sobre Bete-Haquerem; porque a própria calamidade olhou para baixo desde o norte, sim, uma grande derrocada.

[NOTE]
====
. Ou “shofar”.
====

[[v24-6-2]]

^<<v24-6-2,2>>^ A filha de Sião assemelhou-se deveras a uma mulher graciosa e mimosa.

[[v24-6-3]]

^<<v24-6-3,3>>^ A ela passaram a vir os pastores e suas greis. Armaram as [suas] tendas contra ela em todo o redor. Pastaram cada um a sua própria parte.

[[v24-6-4]]

^<<v24-6-4,4>>^ Santificaram a guerra contra ela: “Levantai-vos e subamos ao meio-dia!”
“Ai de nós, porque o dia já declinou, porque as sombras da noitinha se estão estendendo!”

[[v24-6-5]]

^<<v24-6-5,5>>^ “Levantai-vos e subamos durante a noite, e arruinemos as suas torres de habitação.”

[[v24-6-6]]

^<<v24-6-6,6>>^ Pois assim disse Jeová dos exércitos: “Cortai lenha^&#42;1^ e levantai contra Jerusalém um aterro de sítio. Ela é a cidade com a qual se tem de ajustar contas. Ela não é senão opressão no meio dela.

[NOTE]
====
. “Lenha”, MT; LXXSyVg: “suas árvores”.
====

[[v24-6-7]]

^<<v24-6-7,7>>^ Assim como a cisterna mantém a sua água fresca, assim ela manteve fresca a sua maldade. Ouvem-se nela violência e assolação; doença e praga estão constantemente diante da minha face.

[[v24-6-8]]

^<<v24-6-8,8>>^ Sê corrigida, ó Jerusalém, para que a minha alma não se aparte de ti em desgosto; para que eu não faça de ti um baldio desolado, uma terra desabitada.”

[[v24-6-9]]

^<<v24-6-9,9>>^ Assim disse Jeová dos exércitos: “Sem falta se rebuscará o restante de Israel como a uma videira. Põe a tua mão para trás como quem colhe uvas dos sarmentos.”

[[v24-6-10]]

^<<v24-6-10,10>>^ “A quem falarei e advertirei, para que ouçam? Eis que seu ouvido é incircunciso, de modo que não podem prestar atenção. Eis que a própria palavra de Jeová se tornou para eles um vitupério, [palavra] de que^&#42;1^ não se podem agradar.

[NOTE]
====
. “Que”, referindo-se à “própria palavra”, ambos hebr. masc. sing.
====

[[v24-6-11]]

^<<v24-6-11,11>>^ E fiquei cheio do furor de Jeová. Estou fatigado de o conter.”
“Derrama-o sobre a criança na rua e, ao mesmo tempo, sobre o grupo íntimo dos jovens; porque eles também serão apanhados, o homem^&#42;1^ junto com sua esposa,^&#42;2^ o velho junto com aquele que está cheio de dias.

[NOTE]
====
. Ou “marido”. Hebr.: ’ish.
. Ou “mulher”. Hebr.: ’ish·sháh.
====

[[v24-6-12]]

^<<v24-6-12,12>>^ E suas casas certamente se tornarão propriedade de outros, os campos e as esposas, ao mesmo tempo. Pois estenderei a minha mão contra os habitantes do país”, é a pronunciação de Jeová.

[[v24-6-13]]

^<<v24-6-13,13>>^ “Desde o menor até mesmo ao maior deles, cada um obtém para si um lucro injusto; e desde o profeta até mesmo ao sacerdote, cada um age de modo falso.

[[v24-6-14]]

^<<v24-6-14,14>>^ E tentam sarar superficialmente^&#42;1^ o quebrantamento^&#42;2^ do meu povo, dizendo: ‘Há paz! Há paz!’^&#42;3^ quando não há paz.

[NOTE]
====
. Ou “levemente”.
. Ou “a fratura”.
. Ou “dizendo: ‘Perfeita paz!’” Lit.: “dizendo: ‘Paz! Paz!’” Veja Is 26:3 n.: “paz”.
====

[[v24-6-15]]

^<<v24-6-15,15>>^ Acaso se envergonharam de terem feito algo detestável? Em primeiro lugar, eles positivamente não sentem vergonha alguma; em segundo lugar, não chegaram a saber nem mesmo como sentir-se humilhados. Por isso cairão entre os que estão caindo; tropeçarão no tempo em que eu terei de ajustar contas com eles”, disse Jeová.

[[v24-6-16]]

^<<v24-6-16,16>>^ Assim disse Jeová: “Ficai parados nos caminhos e vede, e perguntai pelas sendas de há muito tempo, onde é que está o bom caminho; e andai nele e achai folga para as vossas almas.” Mas eles continuaram a dizer: “Não vamos andar.”

[[v24-6-17]]

^<<v24-6-17,17>>^ “E eu suscitei sobre vós^&#42;1^ vigias: ‘Prestai atenção ao som da buzina!’” Mas eles continuaram a dizer: “Não vamos prestar atenção.”

[NOTE]
====
. “Vós”, MTLXXSyVg; dois mss. hebr.: “eles”.
====

[[v24-6-18]]

^<<v24-6-18,18>>^ “Portanto ouvi, ó nações! E sabe, ó assembléia, o que haverá entre eles.

[[v24-6-19]]

^<<v24-6-19,19>>^ Escuta, ó terra! Eis que trago calamidade sobre este povo, como frutos dos seus pensamentos, pois não prestaram atenção às minhas próprias palavras; e a minha lei — também persistiram em rejeitá-la.”

[[v24-6-20]]

^<<v24-6-20,20>>^ “Que me importa isto, que trazes até mesmo olíbano desde Sabá e a cana boa^&#42;1^ desde a terra longínqua? Os vossos holocaustos não dão prazer e os vossos próprios sacrifícios não me deram satisfação.”

[NOTE]
====
. Ou “a cana doce”.
====

[[v24-6-21]]

^<<v24-6-21,21>>^ Portanto, assim disse Jeová: “Eis que ponho pedras de tropeço para este povo e certamente tropeçarão sobre elas, pais e filhos juntos; o vizinho e seu companheiro — eles perecerão.”

[[v24-6-22]]

^<<v24-6-22,22>>^ Assim disse Jeová: “Eis que está chegando um povo desde a terra do norte e uma grande nação será despertada desde as partes mais remotas da terra.

[[v24-6-23]]

^<<v24-6-23,23>>^ Agarrarão o arco e o dardo. É^&#42;1^ cruel, e não terão piedade. Sua própria voz ressoará como o mar e eles montarão cavalos. Está posto em ordem de batalha como um homem de guerra contra ti, ó filha de Sião.”

[NOTE]
====
. “É”, isto é, o “povo” ou a “nação”.
====

[[v24-6-24]]

^<<v24-6-24,24>>^ Ouvimos a notícia a respeito dele.^&#42;1^ Abaixaram-se as nossas mãos. Fomos tomados da própria aflição, de dores de parto iguais às da mulher que dá à luz.

[NOTE]
====
. Veja v. 23 n.
====

[[v24-6-25]]

^<<v24-6-25,25>>^ Não saias^&#42;1^ ao campo e não andes nem mesmo pelo caminho; porque há uma espada pertencente ao inimigo, há horror ao redor.

[NOTE]
====
. “Não saias”, hebr. fem., dirigido à “filha” de Sião, no v. 23.
====

[[v24-6-26]]

^<<v24-6-26,26>>^ Ó filha do meu povo, cinge-te de serapilheira e revolve-te em cinzas. Faze o teu pranto aquele por um [filho] único, o lamento da amargura; porque repentinamente virá sobre nós o assolador.

[[v24-6-27]]

^<<v24-6-27,27>>^ “Fiz de ti^&#42;1^ um examinador de metal entre meu povo, um que esquadrinha cabalmente;^&#42;2^ e notarás e terás de examinar^&#42;3^ seu caminho.

[NOTE]
====
. “Ti”, hebr. masc. sing.
. “Um que esquadrinha cabalmente” (tal como o colhedor de uvas), mediante a mudança dos sinais vocálicos; M: “como lugar fortificado”.
. Ou “analisar”.
====

[[v24-6-28]]

^<<v24-6-28,28>>^ Todos eles são os homens mais obstinados,^&#42;1^ andando como caluniadores — cobre e ferro. Todos eles são nocivos.

[NOTE]
====
. Lit.: “os taciturnos dos obstinados”.
====

[[v24-6-29]]

^<<v24-6-29,29>>^ Os foles foram chamuscados.^&#42;1^ Do seu fogo procede chumbo. Continuou-se a refinar intensamente, apenas em vão, e os maus não foram retirados.

[NOTE]
====
. “Foram chamuscados”, mediante uma derivação do verbo hebr.; mediante outra derivação: “resfolegaram”.
====

[[v24-6-30]]

^<<v24-6-30,30>>^ Prata rejeitada é o que as pessoas hão de chamá-los, porque Jeová os rejeitou.”

'''

xref:024-jeremias/024-jeremias-005.adoc#v24-5-0[&#60; Capítulo Anterior] | <<v24-6-0,Topo>> | xref:024-jeremias/024-jeremias-007.adoc#v24-7-0[Próximo Capítulo &#62;]