include::./index.adoc[]

[[v24-23-0]]
=== Jeremias, 23
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v24-23-1]]

^<<v24-23-1,1>>^ “Ai dos pastores que destroem e espalham as ovelhas do meu pasto!” é a pronunciação de Jeová.

[[v24-23-2]]

^<<v24-23-2,2>>^ Portanto, assim disse Jeová, o Deus de Israel, contra os pastores que pastoreiam meu povo: “Vós é que espalhastes as minhas ovelhas; e continuastes a dispersá-las e não voltastes a vossa atenção para elas.”
“Eis que volto minha atenção para vós pela ruindade de vossas ações”, é a pronunciação de Jeová.

[[v24-23-3]]

^<<v24-23-3,3>>^ “E eu mesmo reunirei o restante das minhas ovelhas dentre todas as terras às quais eu as dispersara e vou trazê-las de volta à sua pastagem, e certamente se tornarão fecundas e se tornarão muitas.

[[v24-23-4]]

^<<v24-23-4,4>>^ E vou suscitar sobre elas pastores que realmente as apascentarão; e não terão mais medo, nem ficarão aterrorizadas, e nenhuma delas estará faltando”, é a pronunciação de Jeová.

[[v24-23-5]]

^<<v24-23-5,5>>^ “Eis que vêm dias”, é a pronunciação de Jeová, “e eu vou suscitar a Davi um renovo justo. E um rei há de reinar e agir com discrição, e executar o juízo e a justiça na terra.

[[v24-23-6]]

^<<v24-23-6,6>>^ Nos seus dias, Judá será salvo e o próprio Israel residirá em segurança. E este é o nome pelo qual será chamado: Jeová É Nossa Justiça.”^&#42;1^

[NOTE]
====
. “Jeová É Nossa Justiça.” Hebr.: Yehwáh Tsidh·qé·nu.
====

[[v24-23-7]]

^<<v24-23-7,7>>^ “Portanto, eis que vêm dias”, é a pronunciação de Jeová, “e não mais dirão: ‘Jeová está vivo, aquele que fez os filhos de Israel subir da terra do Egito’,

[[v24-23-8]]

^<<v24-23-8,8>>^ mas: ‘Jeová está vivo, aquele que fez subir e que fez entrar a descendência^&#42;1^ da casa de Israel da terra do norte e de todas as terras às quais eu os dispersara’, e certamente morarão no seu próprio solo.”

[NOTE]
====
. Lit.: “semente”.
====

[[v24-23-9]]

^<<v24-23-9,9>>^ Quanto aos profetas, quebrantou-se-me o coração no meu íntimo. Todos os meus ossos começaram a tremer. Tornei-me como um homem^&#42;1^ bêbedo e como um varão vigoroso^&#42;2^ vencido pelo vinho, por causa de Jeová e por causa das suas santas palavras.

[NOTE]
====
. “Como um homem.” Hebr.: ke’ísh.
. “E como um varão vigoroso.” Hebr.: u·kheghé·ver.
====

[[v24-23-10]]

^<<v24-23-10,10>>^ Porque a terra se encheu de adúlteros.^&#42;1^ Pois, por causa da maldição,^&#42;2^ a terra passou a prantear, as pastagens do ermo se secaram; e seu modo de proceder mostra ser mau e sua potência não está direita.

[NOTE]
====
. “Adúlteros.” Lat.: a·dúl·te·ris.
. Ou “maldição juramentada”. Hebr.: ’a·láh.
====

[[v24-23-11]]

^<<v24-23-11,11>>^ “Porque tanto o próprio profeta como o sacerdote ficaram poluídos. Também na minha própria casa encontrei a maldade deles”, é a pronunciação de Jeová.

[[v24-23-12]]

^<<v24-23-12,12>>^ “Portanto, seu caminho se tornará para eles como lugares escorregadios nas trevas, aos quais serão empurrados e [nos quais] certamente cairão.”
“Pois trarei sobre eles uma calamidade, o ano de se fixar a atenção neles”, é a pronunciação de Jeová.

[[v24-23-13]]

^<<v24-23-13,13>>^ “E nos profetas de Samaria eu vi o que é impróprio.^&#42;1^ Agiram como profetas [incitados] por Baal, e estão fazendo meu povo, sim, Israel, andar vagueando.

[NOTE]
====
. Ou “indecência”.
====

[[v24-23-14]]

^<<v24-23-14,14>>^ E nos profetas de Jerusalém vi coisas horríveis, cometendo eles adultério e andando em falsidade; e eles fortaleceram as mãos dos malfeitores para que não recuassem cada um da sua própria maldade. Para mim, todos eles se tornaram como Sodoma, e os habitantes dela, como Gomorra.”

[[v24-23-15]]

^<<v24-23-15,15>>^ Portanto, assim disse Jeová dos exércitos contra os profetas: “Eis que os faço comer absinto e vou dar-lhes de beber água envenenada. Pois dos profetas de Jerusalém saiu apostasia a todo o país.”

[[v24-23-16]]

^<<v24-23-16,16>>^ Assim disse Jeová dos exércitos: “Não escuteis as palavras dos profetas que vos profetizam. Eles fazem que vos torneis vãos. O que falam é a visão do seu próprio coração — não da boca de Jeová.

[[v24-23-17]]

^<<v24-23-17,17>>^ Dizem vez após vez aos que são desrespeitosos para comigo: ‘Jeová falou: “Paz é o que vós ireis ter.”’ E [a] todo aquele que anda na obstinação de seu coração disseram: ‘Nenhuma calamidade virá sobre vós.’

[[v24-23-18]]

^<<v24-23-18,18>>^ Pois, quem estava de pé no grupo íntimo de Jeová para ver e ouvir a sua palavra? Quem deu atenção à sua palavra para ouvi-la?

[[v24-23-19]]

^<<v24-23-19,19>>^ Eis que certamente sairá o vendaval de Jeová, o próprio furor, sim, uma tormenta rodopiante. Rodopiará sobre a cabeça dos iníquos.

[[v24-23-20]]

^<<v24-23-20,20>>^ A ira de Jeová não recuará até que ele tenha executado e até que tenha realizado as idéias de seu coração. Na parte final dos dias dareis a isso vossa consideração com compreensão.

[[v24-23-21]]

^<<v24-23-21,21>>^ “Não enviei os profetas, no entanto, eles mesmos correram. Não falei com eles, no entanto, eles mesmos profetizaram.

[[v24-23-22]]

^<<v24-23-22,22>>^ Mas, se tivessem estado de pé no meu grupo íntimo, então teriam feito meu povo ouvir as minhas próprias palavras, e teriam feito que recuassem do seu mau caminho e da ruindade das suas ações.”

[[v24-23-23]]

^<<v24-23-23,23>>^ “Sou eu um Deus^&#42;1^ que está próximo”, é a pronunciação de Jeová, “e não um Deus longínquo?”

[NOTE]
====
. “Deus.” Hebr.: ha·’Elo·héh. Aqui, ha é uma partícula interrogatória introduzindo uma pergunta.
====

[[v24-23-24]]

^<<v24-23-24,24>>^ “Ou pode algum homem^&#42;1^ estar escondido em esconderijos sem que eu mesmo o veja?” é a pronunciação de Jeová.
“Não é os céus e a terra que eu mesmo realmente encho?” é a pronunciação de Jeová.

[NOTE]
====
. “Algum homem.” Hebr.: ’ish.
====

[[v24-23-25]]

^<<v24-23-25,25>>^ “Ouvi o que disseram os profetas que profetizam falsidade em meu próprio nome, dizendo: ‘Tive um sonho! Tive um sonho!’

[[v24-23-26]]

^<<v24-23-26,26>>^ Até quando existirá no coração dos profetas que profetizam a falsidade e que são profetas da ardileza do seu próprio coração?

[[v24-23-27]]

^<<v24-23-27,27>>^ Pensam em fazer meu povo esquecer-se do meu nome mediante os seus sonhos que continuam a narrar um ao outro, assim como seus pais se esqueceram do meu nome mediante Baal.

[[v24-23-28]]

^<<v24-23-28,28>>^ O profeta com quem há um sonho narre o seu sonho; mas aquele com quem está a minha palavra fale a minha palavra verazmente.”
“Que tem a palha que ver com o grão?” é a pronunciação de Jeová.

[[v24-23-29]]

^<<v24-23-29,29>>^ “Não é a minha palavra correspondentemente como um fogo”, é a pronunciação de Jeová, “e como o malho que despedaça o rochedo?”

[[v24-23-30]]

^<<v24-23-30,30>>^ “Por isso, eis que sou contra os profetas”, é a pronunciação de Jeová, “aqueles que furtam as minhas palavras, cada um do seu companheiro”.

[[v24-23-31]]

^<<v24-23-31,31>>^ “Eis que sou contra os profetas”, é a pronunciação de Jeová, “aqueles que empregam a sua língua para pronunciar: ‘Uma pronunciação!’”^&#42;1^

[NOTE]
====
. “E dizem: ‘Jeová diz’”, Vg; Sy: “e estão dizendo: ‘O próprio Jeová disse assim.’”
====

[[v24-23-32]]

^<<v24-23-32,32>>^ “Eis que sou contra os profetas de sonhos falsos”, é a pronunciação de Jeová, “que os narram e fazem meu povo vaguear por causa das suas falsidades e por causa da sua gabação”.
“Mas eu mesmo não os enviei nem lhes dei ordem. Assim, de modo algum trarão proveito a este povo”, é a pronunciação de Jeová.

[[v24-23-33]]

^<<v24-23-33,33>>^ “E quando este povo, ou o profeta, ou o sacerdote te perguntar, dizendo: ‘Qual é a carga^&#42;1^ de Jeová?’ então terás de dizer-lhes: ‘“Vós sois — ó que carga!^&#42;2^ E eu certamente vos abandonarei”, é a pronunciação de Jeová.’

[NOTE]
====
. Ou: “Qual é a declaração?” Hebr.: mah-mas·sá’.
. “Vós sois — ó que carga!” quando se lê o hebraico como ’at·tém mah-mas·sá’; LXXVgc: “Vós sois a carga”; M(hebr.): ’eth-mah-mas·sá’, “esta expressão: ‘Qual é a carga?’!” Em resposta à pergunta do povo, Jeremias foi orientado a responder com um jogo de palavras (trocadilho).
====

[[v24-23-34]]

^<<v24-23-34,34>>^ Quanto ao profeta, ou ao sacerdote, ou ao povo que disser: ‘A carga de Jeová!’ eu também vou voltar a minha atenção para tal homem^&#42;1^ e para os da sua casa.

[NOTE]
====
. “Tal homem.” Hebr.: ha·’ísh ha·hú’.
====

[[v24-23-35]]

^<<v24-23-35,35>>^ Assim é que estais dizendo, cada um ao seu próximo e cada um ao seu irmão: ‘Que respondeu Jeová? E que falou Jeová?’

[[v24-23-36]]

^<<v24-23-36,36>>^ Mas não mais mencioneis a carga de Jeová, porque a própria carga torna-se para cada um a sua própria palavra, e mudastes as palavras do Deus vivente,^&#42;1^ Jeová dos exércitos, nosso Deus.

[NOTE]
====
. “Deus vivente.” Hebr.: ’Elo·hím hhai·yím, ambas as palavras no pl.
====

[[v24-23-37]]

^<<v24-23-37,37>>^ “Assim dirás ao profeta: ‘Que resposta te deu Jeová? E que falou Jeová?

[[v24-23-38]]

^<<v24-23-38,38>>^ E se o que continuais a dizer é: “A carga de Jeová!” então é assim que disse Jeová: “Visto que dizeis: ‘Esta palavra é a própria carga de Jeová’, quando eu vos mandava dizer: ‘Não deveis dizer: “A carga de Jeová!”’,

[[v24-23-39]]

^<<v24-23-39,39>>^ portanto, eis-me aqui! E eu vou negligenciar-vos terminantemente, e vou abandonar a vós e a cidade que dei a vós e aos vossos antepassados — de diante de mim.

[[v24-23-40]]

^<<v24-23-40,40>>^ E vou pôr sobre vós vitupério por tempo indefinido e humilhação por tempo indefinido, que não será esquecida.”’”

'''

xref:024-jeremias/024-jeremias-022.adoc#v24-22-0[&#60; Capítulo Anterior] | <<v24-23-0,Topo>> | xref:024-jeremias/024-jeremias-024.adoc#v24-24-0[Próximo Capítulo &#62;]