include::./index.adoc[]

[[v24-44-0]]
=== Jeremias, 44
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v24-44-1]]

^<<v24-44-1,1>>^ A palavra que veio a haver para Jeremias para todos os judeus que moravam na terra do Egito, os que moravam em Migdol, e em Tafnes, e em Nofe,^&#42;1^ e na terra de Patros, dizendo:

[NOTE]
====
. “Nofe”, M; TSy: “Mafas (Mênfis)”; Vg: “Mênfis”.
====

[[v24-44-2]]

^<<v24-44-2,2>>^ “Assim disse Jeová dos exércitos, o Deus de Israel: ‘Vós mesmos vistes toda a calamidade que eu fiz chegar sobre Jerusalém e sobre todas as cidades de Judá, e eis que são hoje em dia um lugar devastado e não há ali habitante.

[[v24-44-3]]

^<<v24-44-3,3>>^ É por causa da sua maldade que fizeram para me ofender por irem e fazerem fumaça sacrificial, e prestarem serviço a outros deuses que nem eles mesmos conheceram, nem vós, nem os vossos antepassados.

[[v24-44-4]]

^<<v24-44-4,4>>^ E eu continuei a enviar-vos todos os meus servos, os profetas, levantando-me cedo e enviando-os, dizendo: “Por favor, não façais esta espécie de coisa detestável que tenho odiado.”

[[v24-44-5]]

^<<v24-44-5,5>>^ Mas eles não escutaram, nem inclinaram seu ouvido para recuarem da sua maldade por não fazerem fumaça sacrificial a outros deuses.

[[v24-44-6]]

^<<v24-44-6,6>>^ Por isso se derramou o meu furor e a minha ira, e ela ardeu nas cidades de Judá e nas ruas de Jerusalém; e elas vieram a ser um lugar devastado, um baldio desolado, como no dia de hoje.’

[[v24-44-7]]

^<<v24-44-7,7>>^ “E agora, assim disse Jeová, o Deus dos exércitos, o Deus de Israel: ‘Por que é que causais uma grande calamidade às vossas almas, a fim de decepardes de vós homem e mulher, criança e bebê, do meio de Judá, de modo que não vos deixais sobrar um restante;

[[v24-44-8]]

^<<v24-44-8,8>>^ ofendendo-me com os trabalhos das vossas mãos por fazerdes fumaça sacrificial a outros deuses na terra do Egito, na qual entrais para residir como forasteiros; com o fim de causardes o decepamento de vós mesmos e com o fim de vos tornardes uma invocação do mal e um vitupério entre todas as nações da terra?

[[v24-44-9]]

^<<v24-44-9,9>>^ Acaso vos esquecestes das maldades dos vossos antepassados, e das maldades dos reis de Judá, e das maldades das suas esposas, e das vossas próprias maldades, e das maldades das vossas esposas, que fizeram na terra de Judá e nas ruas de Jerusalém?

[[v24-44-10]]

^<<v24-44-10,10>>^ E até o dia de hoje não se sentiram esmigalhados e não ficaram com medo, nem andaram na minha lei e nos meus estatutos que pus diante de vós e diante dos vossos antepassados.’

[[v24-44-11]]

^<<v24-44-11,11>>^ “Portanto, assim disse Jeová dos exércitos, o Deus de Israel: ‘Eis que fixo minha face contra vós para calamidade e para decepar todo o Judá.

[[v24-44-12]]

^<<v24-44-12,12>>^ E tomarei o restante de Judá, que fixaram suas faces para entrar na terra do Egito, a fim de residir ali como forasteiros, e todos eles hão de chegar ao seu fim na terra do Egito. Cairão à espada; [e] pela fome chegarão ao seu fim, desde o menor até o maior; morrerão à espada e pela fome. E terão de tornar-se uma maldição, um assombro, e uma invocação do mal, e um vitupério.

[[v24-44-13]]

^<<v24-44-13,13>>^ E eu vou ajustar contas com os que moram na terra do Egito, assim como ajustei contas com Jerusalém, com a espada, com a fome e com a pestilência.

[[v24-44-14]]

^<<v24-44-14,14>>^ E não virá a haver nenhum que escape, nem sobrevivente para o restante de Judá, os que estão entrando na terra do Egito para residir ali como forasteiros, sim, para retornar à terra de Judá à qual elevam [o desejo da] sua alma, a fim de voltarem para morar; pois não retornarão, com exceção de alguns fugitivos.’”

[[v24-44-15]]

^<<v24-44-15,15>>^ E todos os homens que sabiam que suas esposas tinham feito fumaça sacrificial a outros deuses^&#42;1^ e todas as esposas que estavam de pé como grande congregação, bem como todo o povo que morava na terra do Egito, em Patros, passaram a responder a Jeremias, dizendo:

[NOTE]
====
. “A . . . deuses.” Hebr.: le’·lo·hím.
====

[[v24-44-16]]

^<<v24-44-16,16>>^ “No que se refere à palavra que nos falaste em nome de Jeová, não te escutamos;

[[v24-44-17]]

^<<v24-44-17,17>>^ mas faremos positivamente toda palavra que saiu da nossa boca, a fim de fazer fumaça sacrificial à ‘rainha dos céus’^&#42;1^ e a fim de derramar^&#42;2^ para ela ofertas de bebida, assim como fizemos nós e os nossos antepassados, nossos reis e nossos príncipes nas cidades de Judá e nas ruas de Jerusalém, quando estávamos saciados de pão e nos ia bem, e não vimos nenhuma calamidade.

[NOTE]
====
. “À obra (adoração) dos céus”, cerca de 30 mss. hebr. Veja 7:18 n.: “rainha”.
. Lit.: “derramar-se-á”. No hebr., este verbo está no infinitivo absoluto.
====

[[v24-44-18]]

^<<v24-44-18,18>>^ E desde o tempo em que deixamos de fazer fumaça sacrificial à ‘rainha dos céus’ e de derramar ofertas de bebida para ela estamos carecendo de tudo, e chegamos ao nosso fim pela espada e pela fome.

[[v24-44-19]]

^<<v24-44-19,19>>^ “Também, quando^&#42;1^ fazíamos fumaça sacrificial à ‘rainha dos céus’ e [nos dispúnhamos a] derramar para ela ofertas de bebida, acaso foi sem perguntarmos aos nossos maridos que fizemos para ela bolos de oferenda, a fim de fazer uma imagem dela e derramar para ela ofertas de bebida?”

[NOTE]
====
. “Também, quando”, M; Sy: “E todas as mulheres responderam e disseram: ‘Quando.’”
====

[[v24-44-20]]

^<<v24-44-20,20>>^ Por sua vez, Jeremias disse a todo o povo, aos varões vigorosos, e às esposas, e a todo o povo, que lhe respondiam com uma palavra, dizendo:

[[v24-44-21]]

^<<v24-44-21,21>>^ “No que se refere à fumaça sacrificial que fizestes nas cidades de Judá e nas ruas de Jerusalém, vós e os vossos antepassados, vossos reis e vossos príncipes, bem como o povo da terra,^&#42;1^ não foi disso que Jeová se lembrou e que passou a subir-lhe ao coração?

[NOTE]
====
. “Bem como o povo da terra.” Hebr.: we‛ám ha·’á·rets.
====

[[v24-44-22]]

^<<v24-44-22,22>>^ Finalmente, Jeová não pôde mais suportá-lo, por causa da maldade das vossas ações, por causa das coisas detestáveis que fizestes, e por isso se tornou a vossa terra um lugar devastado, e um assombro, e uma invocação do mal, sem habitante, como no dia de hoje.

[[v24-44-23]]

^<<v24-44-23,23>>^ Pelo fato de que fizestes fumaça sacrificial e que pecastes contra Jeová, e não obedecestes à voz de Jeová, e não andastes na sua lei, e nos seus estatutos, e nas suas advertências, é que vos sobreveio esta calamidade, como no dia de hoje.”

[[v24-44-24]]

^<<v24-44-24,24>>^ E Jeremias continuou a dizer a todo o povo e a todas as mulheres: “Ouvi a palavra de Jeová, todo o Judá, que estais na terra do Egito.

[[v24-44-25]]

^<<v24-44-25,25>>^ Assim disse Jeová dos exércitos, o Deus de Israel: ‘Quanto a vós, homens, e vossas esposas, vós mulheres também falais com as vossas bocas, (e com as vossas mãos destes cumprimento,) dizendo: “Sem falta executaremos os nossos votos que fizemos, de fazermos fumaça sacrificial à ‘rainha dos céus’ e de derramarmos para ela ofertas de bebida.” Vós mulheres, sem falta, cumprireis os vossos votos e sem falta executareis os vossos votos.’

[[v24-44-26]]

^<<v24-44-26,26>>^ “Portanto, ouvi a palavra de Jeová, todo o Judá, que estais morando na terra do Egito: ‘“Eis que eu mesmo jurei pelo meu grande nome”, disse Jeová, “que meu nome não mais mostrará ser algo invocado pela boca de qualquer homem^&#42;1^ de Judá, dizendo: ‘Pelo Soberano Senhor Jeová que vive!’ em toda a terra do Egito.

[NOTE]
====
. Ou “todo homem de”. Hebr.: kol-’ísh.
====

[[v24-44-27]]

^<<v24-44-27,27>>^ Eis que me mantenho alerta para com eles para calamidade e não para bem; e todos os homens de Judá, que estão na terra do Egito, certamente chegarão ao seu fim pela espada e pela fome, até que deixem de existir.

[[v24-44-28]]

^<<v24-44-28,28>>^ E quanto aos que escaparem da espada, retornarão da terra do Egito à terra de Judá, poucos em número; e todos os do restante de Judá, os que estão entrando na terra do Egito para residir ali como forasteiros, certamente saberão a palavra de quem se cumpre, a minha ou a deles.”’”

[[v24-44-29]]

^<<v24-44-29,29>>^ “‘E este é o sinal para vós’, é a pronunciação de Jeová, ‘que eu volto a minha atenção para vós neste lugar, a fim de que saibais que as minhas palavras se cumprirão impreterivelmente em vós para calamidade:

[[v24-44-30]]

^<<v24-44-30,30>>^ Assim disse Jeová: “Eis que entrego Faraó Hofra, rei do Egito, na mão dos seus inimigos e na mão dos que procuram a sua alma, assim como entreguei Zedequias, rei de Judá, na mão de Nabucodorosor, rei de Babilônia, seu inimigo e aquele que procurava a sua alma.”’”

'''

xref:024-jeremias/024-jeremias-043.adoc#v24-43-0[&#60; Capítulo Anterior] | <<v24-44-0,Topo>> | xref:024-jeremias/024-jeremias-045.adoc#v24-45-0[Próximo Capítulo &#62;]