include::./index.adoc[]

[[v24-32-0]]
=== Jeremias, 32
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v24-32-1]]

^<<v24-32-1,1>>^ A palavra que veio a haver para Jeremias da parte de Jeová no décimo ano de Zedequias, rei de Judá, isto é, no décimo oitavo ano de Nabucodorosor.

[[v24-32-2]]

^<<v24-32-2,2>>^ E naquele tempo, as forças militares do rei de Babilônia sitiavam Jerusalém; e quanto a Jeremias, o profeta, viera a estar sob restrição no Pátio da Guarda, que há na casa do rei de Judá;

[[v24-32-3]]

^<<v24-32-3,3>>^ porque Zedequias, rei de Judá, restringira-o, dizendo:
“Por que é que profetizas, dizendo: ‘Assim disse Jeová: “Eis que entrego esta cidade na mão do rei de Babilônia e ele certamente a capturará;

[[v24-32-4]]

^<<v24-32-4,4>>^ e o próprio Zedequias, rei de Judá, não escapará da mão dos caldeus, pois sem falta será entregue na mão do rei de Babilônia, e sua boca falará realmente com a boca deste e seus próprios olhos verão até mesmo os olhos deste”’;

[[v24-32-5]]

^<<v24-32-5,5>>^ ‘e ele levará Zedequias a Babilônia, e lá continuará até que eu volte a minha atenção para ele’, é a pronunciação de Jeová; ‘embora continueis a guerrear contra os caldeus, não sereis bem sucedidos’?”

[[v24-32-6]]

^<<v24-32-6,6>>^ E Jeremias passou a dizer: “Veio a haver para mim a palavra de Jeová, dizendo:

[[v24-32-7]]

^<<v24-32-7,7>>^ ‘Eis que está chegando a ti Hanamel, filho de Salum, teu tio paterno, dizendo: “Compra para ti meu campo que está em Anatote, porque a ti pertence o direito de resgate para [o] comprar.”’”

[[v24-32-8]]

^<<v24-32-8,8>>^ Com o tempo chegou a mim Hanamel, filho de meu tio paterno, segundo a palavra de Jeová, ao Pátio da Guarda, e passou a dizer-me: “Por favor, compra^&#42;1^ meu campo que está em Anatote, que está na terra de Benjamim, porque é teu o direito da posse hereditária e é teu o poder de resgate. Compra-o para ti.” Então fiquei sabendo que fora a palavra de Jeová.

[NOTE]
====
. Ou “adquire”.
====

[[v24-32-9]]

^<<v24-32-9,9>>^ De modo que passei a comprar de Hanamel, filho de meu tio paterno, o campo que estava em Anatote. E comecei a pesar-lhe o dinheiro, sete siclos^&#42;1^ e dez moedas de prata.

[NOTE]
====
. Um siclo pesava 11,4 g.
====

[[v24-32-10]]

^<<v24-32-10,10>>^ Escrevi então numa escritura e apus o selo, e tomei testemunhas ao pesar o dinheiro na balança.

[[v24-32-11]]

^<<v24-32-11,11>>^ Depois tomei a escritura de compra, a que estava selada segundo o mandamento e os regulamentos, e a deixada aberta;

[[v24-32-12]]

^<<v24-32-12,12>>^ e então entreguei a escritura de compra a Baruque, filho de Nerias, filho de Maséias, perante os olhos de Hanamel, [filho de] meu tio paterno, e perante os olhos das testemunhas, os que escreveram na escritura de compra, perante os olhos de todos os judeus sentados no Pátio da Guarda.

[[v24-32-13]]

^<<v24-32-13,13>>^ Dei então ordens a Baruque perante os olhos deles, dizendo:

[[v24-32-14]]

^<<v24-32-14,14>>^ “Assim disse Jeová dos exércitos, Deus de Israel: ‘Tomando estas escrituras, esta escritura de compra, sim, a selada, e a outra deixada aberta, tens de pô-las então num vaso de barro, a fim de que durem por muitos dias.’

[[v24-32-15]]

^<<v24-32-15,15>>^ Pois assim disse Jeová dos exércitos, o Deus de Israel: ‘Ainda se comprarão casas, e campos, e vinhedos nesta terra.’”

[[v24-32-16]]

^<<v24-32-16,16>>^ E comecei a orar a Jeová, depois de ter dado a escritura de compra a Baruque, filho de Nerias, dizendo:

[[v24-32-17]]

^<<v24-32-17,17>>^ “Ai! Soberano Senhor Jeová! Eis que tu mesmo fizeste os céus e a terra com o teu grande poder e com o teu braço estendido. O assunto inteiro não é maravilhoso demais para ti,

[[v24-32-18]]

^<<v24-32-18,18>>^ Aquele que usa de benevolência para com milhares e retribui o erro dos pais ao seio dos seus filhos após eles, o [verdadeiro] Deus,^&#42;1^ o Grande, o Poderoso,^&#42;2^ cujo nome é Jeová dos exércitos,

[NOTE]
====
. “O [verdadeiro] Deus.” Hebr.: ha·’Él. Veja Ap. 1G.
. “O Poderoso.” Hebr.: hag·Gib·bóhr. Veja Is 9:6 n. e Is 10:21 n.: “Poderoso”.
====

[[v24-32-19]]

^<<v24-32-19,19>>^ grande em conselho e abundante em atos, tu, cujos olhos estão abertos para com todos os caminhos dos filhos dos homens,^&#42;1^ a fim de dar a cada um segundo os seus caminhos e segundo os frutos das suas ações;

[NOTE]
====
. “Dos filhos dos homens.” Hebr.: benéh ’a·dhám.
====

[[v24-32-20]]

^<<v24-32-20,20>>^ tu que puseste sinais e milagres na terra do Egito, até o dia de hoje, e em Israel, e entre homens,^&#42;1^ a fim de fazeres um nome para ti mesmo, assim como no dia de hoje.

[NOTE]
====
. Ou “e entre outros homens”. Hebr.: u·va·’a·dhám.
====

[[v24-32-21]]

^<<v24-32-21,21>>^ E passaste a tirar teu povo Israel da terra do Egito, com sinais e com milagres, e com mão forte e com braço estendido, e com coisa muito espantosa.

[[v24-32-22]]

^<<v24-32-22,22>>^ “Com o tempo deste-lhes esta terra de que juraste aos seus antepassados que lhes havias de dar, uma terra que mana leite e mel.

[[v24-32-23]]

^<<v24-32-23,23>>^ E eles passaram a entrar e a tomar posse dela, mas não obedeceram à tua voz e não andaram na tua lei. Todas as coisas que lhes mandaste fazer, eles não fizeram, de modo que fizeste que lhes sobreviesse toda esta calamidade.

[[v24-32-24]]

^<<v24-32-24,24>>^ Eis que vieram homens com aterros de sítio à cidade para capturá-la e a própria cidade há de ser entregue na mão dos caldeus que lutam contra ela, por causa da espada, e da fome, e da pestilência; e aconteceu o que disseste e eis que [o] estás vendo.

[[v24-32-25]]

^<<v24-32-25,25>>^ No entanto, tu mesmo me disseste, ó Soberano Senhor Jeová: ‘Compra para ti o campo com dinheiro e toma testemunhas’, embora a própria cidade tenha de ser entregue na mão dos caldeus.”

[[v24-32-26]]

^<<v24-32-26,26>>^ Então veio a haver para Jeremias a palavra de Jeová, dizendo:

[[v24-32-27]]

^<<v24-32-27,27>>^ “Eis-me aqui, Jeová, o Deus de toda a carne. Existe alguma coisa que seja maravilhosa demais para mim?

[[v24-32-28]]

^<<v24-32-28,28>>^ Portanto, assim disse Jeová: ‘Eis que entrego esta cidade na mão dos caldeus e na mão de Nabucodorosor, rei de Babilônia, e ele a tem de capturar.

[[v24-32-29]]

^<<v24-32-29,29>>^ E os caldeus que lutam contra esta cidade têm de entrar e atear fogo a esta cidade, e têm de queimá-la, bem como as casas sobre cujos terraços fizeram fumaça sacrificial a Baal e derramaram ofertas de bebida a outros deuses,^&#42;1^ com o fim de me ofenderem.’

[NOTE]
====
. “A . . . deuses.” Hebr.: le’·lo·hím.
====

[[v24-32-30]]

^<<v24-32-30,30>>^ “‘Pois os filhos de Israel e os filhos de Judá mostraram ser meros malfeitores aos meus olhos, desde a sua mocidade; porque os filhos de Israel me ofendem até mesmo com o trabalho das suas mãos’, é a pronunciação de Jeová.

[[v24-32-31]]

^<<v24-32-31,31>>^ ‘Pois esta cidade, desde o dia em que a construíram até o dia de hoje, mostrou ser nada mais do que causa para ira em mim e causa para furor em mim, a fim de removê-la de diante da minha face,

[[v24-32-32]]

^<<v24-32-32,32>>^ em razão de toda a maldade dos filhos de Israel e dos filhos de Judá, que fizeram para me ofender, eles, seus reis, seus príncipes, seus sacerdotes e seus profetas, e os homens^&#42;1^ de Judá e os habitantes de Jerusalém.

[NOTE]
====
. “E os homens de.” Hebr.: we’ísh, sing., mas em sentido coletivo.
====

[[v24-32-33]]

^<<v24-32-33,33>>^ E persistiram em virar as costas para mim e não a face; embora se lhes ensinasse, levantando-se cedo e ensinando, mas não havia nenhum deles que escutasse para receber disciplina.

[[v24-32-34]]

^<<v24-32-34,34>>^ E foram pôr suas coisas repugnantes na casa sobre a qual se invocou meu próprio nome, a fim de a aviltar.

[[v24-32-35]]

^<<v24-32-35,35>>^ Outrossim, construíram os altos de Baal, que estão no vale do filho de Hinom,^&#42;1^ para fazerem seus filhos e suas filhas passar [pelo fogo] a Moloque, coisa que não lhes ordenei, nem me subiu ao coração fazer tal coisa detestável com o fim de fazer Judá pecar.’

[NOTE]
====
. Veja Ap. 4C.
====

[[v24-32-36]]

^<<v24-32-36,36>>^ “E agora, pois, assim disse Jeová, o Deus de Israel, com respeito a esta cidade que vós dizeis será certamente entregue na mão do rei de Babilônia pela espada, e pela fome, e pela pestilência:

[[v24-32-37]]

^<<v24-32-37,37>>^ ‘Eis que os reúno de todas as terras às quais eu os terei dispersado na minha ira e no meu furor, e em grande indignação; e vou trazê-los de volta a este lugar e fazê-los morar em segurança.

[[v24-32-38]]

^<<v24-32-38,38>>^ E eles hão de tornar-se meu povo e eu mesmo me tornarei seu Deus.

[[v24-32-39]]

^<<v24-32-39,39>>^ E vou dar-lhes um só coração e um só caminho, a fim de me temerem para sempre,^&#42;1^ para o bem deles e dos seus filhos após eles.

[NOTE]
====
. Lit.: “todos os dias”.
====

[[v24-32-40]]

^<<v24-32-40,40>>^ E vou concluir com eles um pacto de duração indefinida, de que não recuarei de trás deles, para que eu lhes faça o bem; e porei no seu coração o temor de mim para não se desviarem de mim.

[[v24-32-41]]

^<<v24-32-41,41>>^ E vou exultar sobre eles para fazer-lhes o bem e vou plantá-los nesta terra em veracidade,^&#42;1^ de todo o meu coração e de toda a minha alma.’”

[NOTE]
====
. “Em veracidade (verdade).” Hebr.: be·’eméth.
====

[[v24-32-42]]

^<<v24-32-42,42>>^ “Pois assim disse Jeová: ‘Assim como fiz chegar sobre este povo toda esta grande calamidade, assim faço chegar sobre eles toda a bondade de que falo referente a eles.

[[v24-32-43]]

^<<v24-32-43,43>>^ E certamente se comprarão campos^&#42;1^ nesta terra de que direis: “É um baldio desolado, sem homem^&#42;2^ nem animal doméstico. Foi entregue na mão dos caldeus.”’

[NOTE]
====
. Lit.: “o campo”, hebr. sing., mas em sentido coletivo.
. “Homem.” Hebr.: ’a·dhám.
====

[[v24-32-44]]

^<<v24-32-44,44>>^ “‘Campos é que serão comprados com dinheiro pelas pessoas, e haverá o registro na escritura, e a selagem, e a tomada de testemunhas na terra de Benjamim, e nos arredores de Jerusalém, e nas cidades de Judá, e nas cidades da região montanhosa, e nas cidades da terra baixa,^&#42;1^ e nas cidades do sul,^&#42;2^ porque trarei de volta seus cativos’, é a pronunciação de Jeová.”

[NOTE]
====
. Ou “da Sefelá”.
. Ou “do Negebe”.
====

'''

xref:024-jeremias/024-jeremias-031.adoc#v24-31-0[&#60; Capítulo Anterior] | <<v24-32-0,Topo>> | xref:024-jeremias/024-jeremias-033.adoc#v24-33-0[Próximo Capítulo &#62;]