include::./index.adoc[]

[[v24-8-0]]
=== Jeremias, 8
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v24-8-1]]

^<<v24-8-1,1>>^ “Naquele tempo”, é a pronunciação de Jeová, “as pessoas também tirarão das suas sepulturas os ossos dos reis de Judá, e os ossos dos seus príncipes, e os ossos dos sacerdotes, e os ossos dos profetas, e os ossos dos habitantes de Jerusalém.

[[v24-8-2]]

^<<v24-8-2,2>>^ E realmente os estenderão ao sol, e à lua, e a todo o exército dos céus, que amaram e que serviram, e atrás dos quais andaram, e que buscaram, e diante dos quais se curvaram. Não serão recolhidos nem enterrados. Tornar-se-ão como estrume sobre a superfície do solo.”

[[v24-8-3]]

^<<v24-8-3,3>>^ “E certamente será escolhida antes a morte do que a vida pelos de todo o restante dos remanescentes desta má família, em todos os lugares dos remanescentes aonde eu os terei dispersado”, é a pronunciação de Jeová dos exércitos.

[[v24-8-4]]

^<<v24-8-4,4>>^ “E tens de dizer-lhes: ‘Assim disse Jeová: “Cairão e não se levantarão novamente? Se um voltar, não voltará também o outro?

[[v24-8-5]]

^<<v24-8-5,5>>^ Por que é que este povo, Jerusalém, é infiel com infidelidade duradoura? Agarraram-se à ardileza; negaram-se a voltar.

[[v24-8-6]]

^<<v24-8-6,6>>^ Prestei atenção e estive escutando. Não era correto como falavam. Não havia homem que se arrependesse de sua maldade, dizendo: ‘Que é que eu fiz?’ Cada um retorna ao proceder popular, qual cavalo que se arroja à batalha.

[[v24-8-7]]

^<<v24-8-7,7>>^ Até mesmo a cegonha nos céus — ela conhece bem seus tempos designados; e a rola, e o andorinhão, e o bulbul — eles observam bem o tempo da entrada de cada um. Quanto ao meu povo, porém, não vieram a conhecer o julgamento de Jeová.”’

[[v24-8-8]]

^<<v24-8-8,8>>^ “‘Como podeis dizer: “Somos sábios e a lei de Jeová está conosco”? Seguramente, pois, o estilo falso dos secretários trabalhou em pura falsidade.

[[v24-8-9]]

^<<v24-8-9,9>>^ Os sábios ficaram envergonhados. Ficaram aterrorizados e serão apanhados. Eis que rejeitaram a própria palavra de Jeová, e que sabedoria é que eles têm?

[[v24-8-10]]

^<<v24-8-10,10>>^ Por isso entregarei as suas esposas a outros homens, seus campos, aos que tomam posse; pois, desde o menor até mesmo ao maior, cada um está obtendo lucro injusto; desde o profeta até mesmo ao sacerdote, cada um age de modo falso.

[[v24-8-11]]

^<<v24-8-11,11>>^ E tentam sarar superficialmente^&#42;1^ o quebrantamento^&#42;2^ da filha do meu povo, dizendo: “Há paz! Há paz!”^&#42;3^ quando não há paz.

[NOTE]
====
. Ou “levemente”.
. Ou “fratura”.
. Veja 6:14 n.: “paz”.
====

[[v24-8-12]]

^<<v24-8-12,12>>^ Acaso sentiram vergonha por terem feito o que era detestável? Em primeiro lugar, eles positivamente não podiam sentir-se envergonhados; em segundo lugar, não sabem nem mesmo como sentir-se humilhados.
“‘Por isso cairão entre os que estão caindo. Tropeçarão no tempo de se fixar a atenção neles’, disse Jeová.

[[v24-8-13]]

^<<v24-8-13,13>>^ “‘Ao fazer o ajuntamento, darei cabo deles’,^&#42;1^ é a pronunciação de Jeová. ‘Não haverá uvas na videira e não haverá figos na figueira, e a própria folhagem há de murchar. E as coisas que lhes dou passarão por eles.’”

[NOTE]
====
. “[Quando] eu, sem falta, os ajuntar”, mediante uma mudança no M.
====

[[v24-8-14]]

^<<v24-8-14,14>>^ “Por que é que ficamos sentados? Ajuntai-vos, e entremos nas cidades fortificadas e fiquemos quietos ali. Porque o próprio Jeová, nosso Deus,^&#42;1^ nos silenciou,^&#42;2^ e ele nos dá água envenenada para beber, porque pecamos contra Jeová.

[NOTE]
====
. “Nosso Deus.” Hebr.: ’Elo·héh·nu.
. Ou “nos colocou fora de ação”, isto é, fez-nos perecer.
====

[[v24-8-15]]

^<<v24-8-15,15>>^ Esperava-se a paz, mas [não veio] nenhum bem; um tempo de cura, mas eis terror!

[[v24-8-16]]

^<<v24-8-16,16>>^ Desde Dã se ouviu o resfolegar dos seus cavalos. Devido ao som do rincho dos seus garanhões, a terra toda começou a tremer. E eles entram e consomem a terra^&#42;1^ e o que a enche, a cidade e seus habitantes.”

[NOTE]
====
. “Terra.” Hebr.: ’é·rets.
====

[[v24-8-17]]

^<<v24-8-17,17>>^ “Pois, eis que envio entre vós serpentes, cobras venenosas, para as quais não há encantamento, e elas certamente vos morderão”, é a pronunciação de Jeová.

[[v24-8-18]]

^<<v24-8-18,18>>^ Um pesar além de cura me sobreveio. Meu coração está enfermo.

[[v24-8-19]]

^<<v24-8-19,19>>^ Eis aqui o som do grito por ajuda da filha do meu povo, desde uma terra longínqua: “Não está Jeová em Sião? Ou não está nela seu rei?”
“Por que é que me ofenderam com as suas imagens entalhadas, com os seus vãos deuses estrangeiros?”

[[v24-8-20]]

^<<v24-8-20,20>>^ “Já passou a colheita, acabou o verão; quanto a nós, porém, não fomos salvos!”

[[v24-8-21]]

^<<v24-8-21,21>>^ Fiquei quebrantado por causa do quebrantamento da filha do meu povo. Fiquei entristecido. Fui tomado de franco assombro.

[[v24-8-22]]

^<<v24-8-22,22>>^ Não há nenhum bálsamo em Gileade? Ou não há ali ninguém que cure? Por que se dá, então, que não surgiu o restabelecimento da filha do meu povo?

'''

xref:024-jeremias/024-jeremias-007.adoc#v24-7-0[&#60; Capítulo Anterior] | <<v24-8-0,Topo>> | xref:024-jeremias/024-jeremias-009.adoc#v24-9-0[Próximo Capítulo &#62;]