include::./index.adoc[]

[[v24-31-0]]
=== Jeremias, 31
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v24-31-1]]

^<<v24-31-1,1>>^ “Naquele tempo”, é a pronunciação de Jeová, “tornar-me-ei Deus para todas as famílias de Israel; e quanto a eles, tornar-se-ão meu povo”.

[[v24-31-2]]

^<<v24-31-2,2>>^ Assim disse Jeová: “O povo composto dos sobreviventes da espada achou favor no ermo, quando Israel andava^&#42;1^ para obter seu repouso.”

[NOTE]
====
. Lit.: “andava-se”. No hebr., este verbo está no infinitivo absoluto, indefinido quanto ao tempo e impessoal.
====

[[v24-31-3]]

^<<v24-31-3,3>>^ De longe apareceu-me o próprio Jeová, [dizendo:] “E eu te^&#42;1^ amei com um amor por tempo indefinido. Por isso é que te atraí com benevolência.^&#42;2^

[NOTE]
====
. “Te”, hebr. fem. sing., referindo-se à “virgem” no v. 4.
. Ou “amor leal”. Hebr.: hhá·sedh.
====

[[v24-31-4]]

^<<v24-31-4,4>>^ Ainda te reedificarei e serás realmente reedificada, ó virgem de Israel. Ainda te ataviarás com os teus pandeiros e realmente sairás na dança dos que estão rindo.

[[v24-31-5]]

^<<v24-31-5,5>>^ Ainda plantarás vinhedos nos montes de Samaria. Os plantadores certamente plantarão e principiarão a usá-los.

[[v24-31-6]]

^<<v24-31-6,6>>^ Pois há um dia em que as sentinelas na região montanhosa de Efraim realmente clamarão: ‘Levantai-vos, homens, e subamos a Sião, a Jeová, nosso Deus.’”

[[v24-31-7]]

^<<v24-31-7,7>>^ Pois assim disse Jeová: “Gritai alto a Jacó, com alegria, e gritai estridentemente à cabeça das nações. Publicai-o. Dai louvor e dizei: ‘Salva teu povo, ó Jeová, o restante de Israel.’

[[v24-31-8]]

^<<v24-31-8,8>>^ Eis que os trago da terra do norte e vou reuni-los das partes mais remotas da terra. Entre eles haverá o cego e o coxo, a mulher grávida e a parturiente, todos juntos. Retornarão para cá como grande congregação.

[[v24-31-9]]

^<<v24-31-9,9>>^ Virão com choro, e eu os trarei com os [seus] rogos de favor. Fá-los-ei andar a vales de torrente de água, num caminho direito em que não se fará que tropecem. Porque eu me tornei Pai para Israel; e quanto a Efraim, ele é meu primogênito.”

[[v24-31-10]]

^<<v24-31-10,10>>^ Ouvi a palavra de Jeová, ó nações, e contai-a entre as ilhas^&#42;1^ longínquas e dizei: “Aquele que espalhou Israel é quem o reunirá e certamente o guardará como o pastor faz com a sua grei.

[NOTE]
====
. Ou “litorais”.
====

[[v24-31-11]]

^<<v24-31-11,11>>^ Porque Jeová realmente remirá a Jacó e o reivindicará da mão do mais forte do que ele.

[[v24-31-12]]

^<<v24-31-12,12>>^ E certamente chegarão e gritarão de júbilo na altura de Sião, e ficarão radiantes com a bondade de Jeová, com o cereal, e com o vinho novo, e com o azeite, e com as crias^&#42;1^ do rebanho e do gado vacum. E sua alma se tornará simplesmente como um jardim bem regado e nunca mais desfalecerão.”

[NOTE]
====
. Lit.: “os filhos”.
====

[[v24-31-13]]

^<<v24-31-13,13>>^ “Naquele tempo alegrar-se-á a virgem com a dança, também os jovens e os velhos, todos juntos. E eu vou transformar seu pranto em exultação, e vou consolá-los e fazê-los alegrar-se, afastando-se do seu pesar.

[[v24-31-14]]

^<<v24-31-14,14>>^ E vou saturar de gordura a alma do sacerdote e meu próprio povo se saciará com a minha bondade”, é a pronunciação de Jeová.

[[v24-31-15]]

^<<v24-31-15,15>>^ “Assim disse Jeová: ‘Ouve-se uma voz em Ramá, lamentação e choro amargo; Raquel chorando por seus filhos. Negou-se a ser consolada por causa dos seus filhos, porque eles já não existem.’”

[[v24-31-16]]

^<<v24-31-16,16>>^ Assim disse Jeová: “‘Retém a tua^&#42;1^ voz do choro e teus olhos das lágrimas, pois há uma recompensa pela tua atividade’, é a pronunciação de Jeová, ‘e certamente retornarão da terra do inimigo’.

[NOTE]
====
. “Tua”, hebr. fem. sing., dirigido a “Raquel”.
====

[[v24-31-17]]

^<<v24-31-17,17>>^ “‘E existe esperança para o teu futuro’, é a pronunciação de Jeová, ‘e os filhos certamente retornarão ao seu próprio território’.”

[[v24-31-18]]

^<<v24-31-18,18>>^ “Ouvi positivamente Efraim lastimar-se: ‘Corrigiste-me, para que eu ficasse corrigido, como o bezerro que não foi treinado. Faze-me voltar e eu voltarei prontamente, porque tu és Jeová, meu Deus.

[[v24-31-19]]

^<<v24-31-19,19>>^ Pois, após a minha volta senti lástima; e depois que se me fez saber bati na coxa. Fiquei envergonhado e senti-me também humilhado, porque eu levara o vitupério da minha mocidade.’”

[[v24-31-20]]

^<<v24-31-20,20>>^ “É Efraim para mim um filho precioso ou um menino tratado com mimo? Pois, ao ponto de eu falar contra ele, sem falta me lembrarei dele ainda mais. Por isso é que as minhas entranhas ficaram turbulentas por ele. Decididamente terei piedade dele”, é a pronunciação de Jeová.

[[v24-31-21]]

^<<v24-31-21,21>>^ “Erige para ti^&#42;1^ marcos de estrada. Coloca para ti postes indicadores. Fixa teu coração na estrada principal, no caminho pelo qual terás de ir.^&#42;2^ Volta, ó virgem de Israel. Volta a estas tuas cidades.

[NOTE]
====
. “Ti”, hebr. fem. sing., dirigido à “virgem”.
. Ou “no caminho pelo qual andaste”.
====

[[v24-31-22]]

^<<v24-31-22,22>>^ Até quando te virarás para este e para aquele lado, ó filha infiel? Pois Jeová criou uma coisa nova na terra: A mera fêmea cercará estreitamente o varão vigoroso.”^&#42;1^

[NOTE]
====
. “Varão vigoroso.” Hebr.: gá·ver.
====

[[v24-31-23]]

^<<v24-31-23,23>>^ Assim disse Jeová dos exércitos, o Deus de Israel: “Ainda se dirá esta palavra na terra de Judá e nas suas cidades, quando eu recolher seus cativos: ‘Que Jeová te^&#42;1^ abençoe, ó moradia justa, ó monte santo.’

[NOTE]
====
. “Te”, hebr. masc. sing.
====

[[v24-31-24]]

^<<v24-31-24,24>>^ E nela^&#42;1^ hão de morar juntos Judá e todas as suas cidades, os lavradores e os que partiram com a grei.

[NOTE]
====
. “Nela”, hebr. fem., referindo-se à “terra”.
====

[[v24-31-25]]

^<<v24-31-25,25>>^ Pois eu vou saturar a alma cansada e vou tornar cheia toda alma desfalecente.”

[[v24-31-26]]

^<<v24-31-26,26>>^ Nisto eu acordei e comecei a ver; e quanto ao meu sono, fora agradável para mim.

[[v24-31-27]]

^<<v24-31-27,27>>^ “Eis que vêm dias”, é a pronunciação de Jeová, “e eu vou semear a casa de Israel e a casa de Judá com semente de homem e com semente de animal doméstico”.

[[v24-31-28]]

^<<v24-31-28,28>>^ “E terá de acontecer que assim como fiquei alerta para com eles para desarraigar, e para demolir, e para derrubar, e para destruir, e para danificar, assim ficarei alerta para com eles para edificar e para plantar”, é a pronunciação de Jeová.

[[v24-31-29]]

^<<v24-31-29,29>>^ “Naqueles dias não se dirá mais: ‘Os pais foram os que comeram a uva verde, mas foram os dentes dos filhos que ficaram embotados.’^&#42;1^

[NOTE]
====
. Lit.: “obtusos (rombudos)”.
====

[[v24-31-30]]

^<<v24-31-30,30>>^ Mas cada um morrerá pelo seu próprio erro. Qualquer homem que comer uva verde, os seus é que serão os dentes que ficarão embotados.”

[[v24-31-31]]

^<<v24-31-31,31>>^ “Eis que vêm dias”, é a pronunciação de Jeová, “e eu vou concluir^&#42;1^ um novo pacto^&#42;2^ com a casa de Israel e com a casa de Judá;

[NOTE]
====
. Lit.: “cortar”.
. “Um novo pacto.” Hebr.: beríth hhadha·sháh.
====

[[v24-31-32]]

^<<v24-31-32,32>>^ não um igual ao pacto que concluí com os seus antepassados no dia em que os tomei pela mão para os tirar da terra do Egito, ‘pacto meu que eles próprios violaram, embora^&#42;1^ eu mesmo tivesse a posse marital deles’,^&#42;2^ é a pronunciação de Jeová”.

[NOTE]
====
. Lit.: “e”.
. “Tivesse a posse marital deles”, MVg; T: “achasse para mim prazer neles”; LXX: “deixei de me importar com eles”; Sy: “os desprezasse”.
====

[[v24-31-33]]

^<<v24-31-33,33>>^ “Pois este é o pacto que concluirei com a casa de Israel depois daqueles dias”, é a pronunciação de Jeová. “Vou pôr a minha lei no seu íntimo e a escreverei no seu coração.^&#42;1^ E vou tornar-me seu Deus e eles mesmos se tornarão meu povo.”

[NOTE]
====
. “Certamente porei minhas leis na mente deles e as escreverei no seu coração”, LXX.
====

[[v24-31-34]]

^<<v24-31-34,34>>^ “E não mais ensinarão, cada um ao seu companheiro e cada um ao seu irmão, dizendo: ‘Conhecei a Jeová!’ porque todos eles me conhecerão, desde o menor deles até o maior deles”, é a pronunciação de Jeová. “Porque perdoarei seu erro e não me lembrarei mais do seu pecado.”

[[v24-31-35]]

^<<v24-31-35,35>>^ Assim disse Jeová, o Dador do sol para luz de dia, dos estatutos da^&#42;1^ lua e das estrelas para luz de noite, o Agitador do mar, para que as suas ondas se tornem turbulentas, Aquele cujo nome é Jeová dos exércitos:

[NOTE]
====
. “Dos estatutos da”, MTSyVg; LXX e um ms. hebr. omitem isso.
====

[[v24-31-36]]

^<<v24-31-36,36>>^ “‘Se estes regulamentos pudessem ser removidos de diante de mim’, é a pronunciação de Jeová, ‘estes que são a descendência de Israel poderiam igualmente cessar de mostrar ser para sempre uma nação diante de mim’.”

[[v24-31-37]]

^<<v24-31-37,37>>^ Assim disse Jeová: “‘Se os céus acima pudessem ser medidos e os alicerces da terra embaixo pudessem ser descobertos, eu mesmo também poderia rejeitar toda a descendência de Israel por causa de tudo o que fizeram’, é a pronunciação de Jeová.”

[[v24-31-38]]

^<<v24-31-38,38>>^ “Eis que vêm^&#42;1^ dias”, é a pronunciação de Jeová, “e certamente se construirá a cidade para Jeová, desde a Torre de Hananel até o Portão da Esquina.

[NOTE]
====
. “Vêm”, MmargemTLXXSyVg e 48 mss. hebr. No M, as consoantes hebr. desta forma verbal estão faltando, mas os sinais vocálicos foram inseridos para indicar que se devia ler “vêm”. Trata-se de qere, não de kethib (lido, mas não escrito).
====

[[v24-31-39]]

^<<v24-31-39,39>>^ E o cordel para medir realmente sairá ainda direto para o morro de Garebe e certamente dará volta para Goa.

[[v24-31-40]]

^<<v24-31-40,40>>^ E toda a baixada dos cadáveres e das cinzas gordurosas, e todos os socalcos até o vale da torrente do Cédron, até a esquina do Portão dos Cavalos, na direção do nascente, serão algo sagrado para Jeová. Não será desarraigada, nem será mais derrubada, por tempo indefinido.”

'''

xref:024-jeremias/024-jeremias-030.adoc#v24-30-0[&#60; Capítulo Anterior] | <<v24-31-0,Topo>> | xref:024-jeremias/024-jeremias-032.adoc#v24-32-0[Próximo Capítulo &#62;]