include::./index.adoc[]

[[v24-40-0]]
=== Jeremias, 40
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v24-40-1]]

^<<v24-40-1,1>>^ A palavra que veio a haver para Jeremias da parte de Jeová, depois de Nebuzaradã, chefe da guarda pessoal, o ter enviado de Ramá, tomando-o enquanto estava preso com algemas no meio de todos os exilados de Jerusalém e de Judá, que estavam sendo levados ao exílio em Babilônia.

[[v24-40-2]]

^<<v24-40-2,2>>^ O chefe da guarda pessoal tomou então Jeremias e disse-lhe: “O próprio Jeová, teu Deus, proferiu esta calamidade contra este lugar,

[[v24-40-3]]

^<<v24-40-3,3>>^ para que Jeová [a] cumprisse e fizesse assim como falou, porque vós pecastes contra Jeová e não obedecestes à sua voz. E esta coisa vos aconteceu.

[[v24-40-4]]

^<<v24-40-4,4>>^ E agora, eis que te livrei hoje das algemas que havia nas tuas mãos. Se for bom aos teus olhos vir comigo a Babilônia, vem, e eu manterei os meus olhos fixos em ti. Mas, se for mau aos teus olhos vir comigo a Babilônia, refreia-te. Vê! O país inteiro está diante de ti. Vai para onde quer que for bom e direito aos teus olhos ir.”

[[v24-40-5]]

^<<v24-40-5,5>>^ E ele ainda não ia retornar, quando [Nebuzaradã disse]: “Retorna deveras a Gedalias, filho de Aicão, filho de Safã, a quem o rei de Babilônia encarregou das cidades de Judá, e mora com ele no meio do povo; ou vai para onde quer que for direito aos teus olhos ir.”
E o chefe da guarda pessoal deu-lhe então uma subsistência alimentícia e um presente, e deixou-o ir.

[[v24-40-6]]

^<<v24-40-6,6>>^ Conseqüentemente, Jeremias chegou a Gedalias, filho de Aicão, em Mispá, e passou a morar com ele no meio do povo que fora deixado no país.

[[v24-40-7]]

^<<v24-40-7,7>>^ Com o tempo, todos os chefes^&#42;1^ das forças militares que estavam no campo, eles e seus homens, chegaram a ouvir que o rei de Babilônia encarregara do país a Gedalias, filho de Aicão, e que o encarregara dos homens, e das mulheres, e das criancinhas, e de alguns dos de condição humilde do país, que não tinham sido levados ao exílio em Babilônia.

[NOTE]
====
. Ou “os príncipes das”. Hebr.: sa·réh.
====

[[v24-40-8]]

^<<v24-40-8,8>>^ Chegaram, pois, a Gedalias em Mispá, sim, Ismael, filho de Netanias,^&#42;1^ e Joanã e Jonatã, filhos de Careá, e Seraías, filho de Tanumete, e os filhos de Efai, o netofatita, e Jezanias,^&#42;2^ filho do maacatita, eles e seus homens.

[NOTE]
====
. Significando “Jeová Deu”. Hebr.: Nethan·yá·hu.
. “E Jezanias.” Hebr.: wI·zan·yá·hu, significando “Jeová Dá Ouvidos”.
====

[[v24-40-9]]

^<<v24-40-9,9>>^ E Gedalias, filho de Aicão, filho de Safã, passou a jurar a eles e aos seus homens, dizendo: “Não tenhais medo de servir os caldeus. Continuai a morar no país e servi o rei de Babilônia, e vos irá bem.

[[v24-40-10]]

^<<v24-40-10,10>>^ E quanto a mim, eis que estou morando em Mispá, a fim de ficar de pé perante os caldeus que virão a nós. E quanto a vós mesmos, recolhei vinho, e frutas de verão, e azeite, e ponde [isso] nos vossos vasos e morai nas vossas cidades que tomastes.”

[[v24-40-11]]

^<<v24-40-11,11>>^ E todos os judeus que estavam em Moabe e entre os filhos de Amom, e em Edom, e os que estavam em todos os [outros] países, também ouviram que o rei de Babilônia dera um restante a Judá e que encarregara deles Gedalias, filho de Aicão, filho de Safã.

[[v24-40-12]]

^<<v24-40-12,12>>^ E todos os judeus começaram a retornar de todos os lugares aos quais tinham sido dispersos, e continuaram a entrar na terra de Judá, [chegando] a Gedalias, em Mispá. E foram recolher vinho e frutas de verão em quantidade muito grande.

[[v24-40-13]]

^<<v24-40-13,13>>^ Quanto a Joanã, filho de Careá, e todos os chefes das forças militares que estavam no campo, chegaram eles a Gedalias, em Mispá.

[[v24-40-14]]

^<<v24-40-14,14>>^ E passaram a dizer-lhe: “Acaso não sabes que o próprio Baalis, rei dos filhos de Amom, enviou Ismael, filho de Netanias, para golpear-te a alma?” Mas Gedalias, filho de Aicão, não lhes deu crédito.

[[v24-40-15]]

^<<v24-40-15,15>>^ E o próprio Joanã, filho de Careá, disse a Gedalias num esconderijo em Mispá: “Quero ir agora e golpear Ismael, filho de Netanias, visto que ninguém saberá de nada. Por que devia ele golpear-te a alma^&#42;1^ e por que teriam de ser espalhados todos os de Judá que estão sendo reunidos a ti e perecer o restante de Judá?”

[NOTE]
====
. “Devia ele golpear-te a alma”, isto é, mortalmente. Hebr.: yak·kék·kah né·fesh; gr.: pa·tá·xei sou psy·khén; lat.: in·ter·fí·ci·at á·ni·mam tú·am. Veja Ap. 4A.
====

[[v24-40-16]]

^<<v24-40-16,16>>^ Mas Gedalias, filho de Aicão, disse a Joanã, filho de Careá: “Não faças tal coisa, pois é uma falsidade o que estás falando a respeito de Ismael.”

'''

xref:024-jeremias/024-jeremias-039.adoc#v24-39-0[&#60; Capítulo Anterior] | <<v24-40-0,Topo>> | xref:024-jeremias/024-jeremias-041.adoc#v24-41-0[Próximo Capítulo &#62;]