include::./index.adoc[]

[[v24-17-0]]
=== Jeremias, 17
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v24-17-1]]

^<<v24-17-1,1>>^ “O pecado de Judá está assentado por escrito com um estilo de ferro. Com ponta de diamante foi gravado na tábua do seu coração e nos chifres dos seus^&#42;1^ altares,

[NOTE]
====
. “Seus”, ThSyVg e cerca de 170 mss. hebr.; M: “vossos”.
====

[[v24-17-2]]

^<<v24-17-2,2>>^ quando seus filhos se lembrarem dos seus altares e dos seus postes sagrados^&#42;1^ ao lado duma árvore frondosa, sobre os morros altos,

[NOTE]
====
. Ou “suas Axerás”.
====

[[v24-17-3]]

^<<v24-17-3,3>>^ [nas] montanhas no campo. Teus^&#42;1^ recursos, todos os teus tesouros, entregarei ao mero saque — teus altos, por causa do pecado em todos os teus territórios.

[NOTE]
====
. “Teus”, hebr. masc. sing.
====

[[v24-17-4]]

^<<v24-17-4,4>>^ E largaste, mesmo espontaneamente, a tua propriedade hereditária que eu te dera. Também eu vou fazer que sirvas aos teus inimigos na terra que não conheceste; pois fostes acesos como fogo na minha ira. Ficará aceso por tempo indefinido.”

[[v24-17-5]]

^<<v24-17-5,5>>^ Assim disse Jeová: “Maldito o varão vigoroso^&#42;1^ que confia no homem terreno^&#42;2^ e que realmente faz da carne o seu braço, e cujo coração se desvia do próprio Jeová.

[NOTE]
====
. “O varão vigoroso.” Hebr.: hag·gé·ver.
. “No homem terreno.” Hebr.: ba·’a·dhám.
====

[[v24-17-6]]

^<<v24-17-6,6>>^ E ele certamente se tornará qual árvore solitária na planície desértica e não verá quando vem o bem; mas terá de residir em lugares secos^&#42;1^ no ermo, numa terra salgada que não é habitada.

[NOTE]
====
. Ou “trechos cobertos de lava”.
====

[[v24-17-7]]

^<<v24-17-7,7>>^ Bendito o varão vigoroso que confia em Jeová e cuja confiança veio a ser Jeová.

[[v24-17-8]]

^<<v24-17-8,8>>^ E ele certamente se tornará qual árvore plantada junto às águas, que envia suas raízes diretamente junto ao curso de água; e ele não verá o calor chegar, mas a sua folhagem mostrará ser realmente frondosa. E no ano da seca não se inquietará, nem deixará de produzir fruto.

[[v24-17-9]]

^<<v24-17-9,9>>^ “O coração é mais traiçoeiro do que qualquer outra coisa e está desesperado. Quem o pode conhecer?

[[v24-17-10]]

^<<v24-17-10,10>>^ Eu, Jeová, esquadrinho o coração, examino os rins,^&#42;1^ sim, para dar a cada um segundo os seus caminhos,^&#42;2^ segundo os frutos das suas ações.

[NOTE]
====
. Veja 11:20 n.
. “Caminhos”, TLXXSy e cerca de 130 mss. hebr.
====

[[v24-17-11]]

^<<v24-17-11,11>>^ [Como] a perdiz que tem ajuntado^&#42;1^ o que não botou é aquele que produz riquezas, mas não com justiça. Na metade dos seus dias as deixará, e no seu final mostrará ser insensato.”

[NOTE]
====
. Ou “chocou (ovos)”.
====

[[v24-17-12]]

^<<v24-17-12,12>>^ Há o trono glorioso no alto, desde o princípio; é o lugar do nosso santuário.

[[v24-17-13]]

^<<v24-17-13,13>>^ Ó Jeová, esperança de Israel, envergonhados serão todos os que te abandonam. Os que apostatam de mim serão inscritos até mesmo na terra, porque abandonaram a fonte de água viva, Jeová.

[[v24-17-14]]

^<<v24-17-14,14>>^ Cura-me, ó Jeová, e ficarei curado. Salva-me, e estarei salvo; porque tu és meu louvor.

[[v24-17-15]]

^<<v24-17-15,15>>^ Eis que há os que me dizem: “Onde está a palavra de Jeová? Que entre, por favor.”

[[v24-17-16]]

^<<v24-17-16,16>>^ Quanto a mim, porém, não me precipitei para deixar de ser um pastor que te segue, e não mostrei almejo do dia de desespero. Tu mesmo conheceste a expressão dos meus lábios; ela se deu diante da tua face.

[[v24-17-17]]

^<<v24-17-17,17>>^ Não te tornes para mim algo aterrorizante. Tu és meu refúgio no dia da calamidade.

[[v24-17-18]]

^<<v24-17-18,18>>^ Sejam envergonhados os meus perseguidores, mas não seja eu pessoalmente envergonhado. Sejam eles os que ficam aterrorizados, mas não fique eu pessoalmente aterrorizado. Traze sobre eles o dia de calamidade e destroça-os até mesmo com o dobro de quebrantamento.

[[v24-17-19]]

^<<v24-17-19,19>>^ Assim me disse Jeová: “Vai,^&#42;1^ e tens de ficar de pé no portão dos filhos do povo, pelo qual os reis de Judá entram e pelo qual saem, e em todos os portões de Jerusalém.

[NOTE]
====
. Veja 2:2 n.: “Vai.”
====

[[v24-17-20]]

^<<v24-17-20,20>>^ E tens de dizer-lhes: ‘Ouvi a palavra de Jeová, ó reis de Judá, e todo o Judá, e todos vós habitantes de Jerusalém, que entrais por estes portões.

[[v24-17-21]]

^<<v24-17-21,21>>^ Assim disse Jeová: “Guardai as vossas almas^&#42;1^ e não carregueis no dia de sábado nenhuma carga que tenhais de fazer entrar pelos portões de Jerusalém.

[NOTE]
====
. “As vossas almas.” Hebr.: benaf·shoh·theh·khém, pl. de né·fesh; gr.: psy·khás; lat.: á·ni·mas. Veja Ap. 4A.
====

[[v24-17-22]]

^<<v24-17-22,22>>^ E não deveis tirar nenhuma carga dos vossos lares no dia de sábado; e não deveis fazer absolutamente nenhuma obra. E tendes de santificar o dia de sábado, assim como mandei aos vossos antepassados;

[[v24-17-23]]

^<<v24-17-23,23>>^ mas eles não escutaram nem inclinaram seus ouvidos, e passaram a endurecer a sua cerviz para não ouvir e para não receber disciplina.”’

[[v24-17-24]]

^<<v24-17-24,24>>^ “‘“E terá de acontecer que, se me obedecerdes estritamente”, é a pronunciação de Jeová, “não fazendo entrar nenhuma carga pelos portões desta cidade no dia de sábado e santificando o dia de sábado por não fazerdes nele nenhuma obra,

[[v24-17-25]]

^<<v24-17-25,25>>^ então certamente entrarão pelos portões desta cidade reis com príncipes, sentando-se no trono de Davi, andando em carros e montando cavalos, eles e seus príncipes, os homens^&#42;1^ de Judá e os habitantes de Jerusalém; e esta cidade certamente será habitada por tempo indefinido.

[NOTE]
====
. “Homens de.” Hebr.: ’ish, sing., mas em sentido coletivo.
====

[[v24-17-26]]

^<<v24-17-26,26>>^ E as pessoas virão realmente das cidades de Judá, e dos arredores de Jerusalém, e da terra de Benjamim, e da terra baixa,^&#42;1^ e da região montanhosa, e do Negebe,^&#42;2^ trazendo holocausto, e sacrifício, e oferta de cereais, e olíbano, e trazendo sacrifício de agradecimento à casa de Jeová.

[NOTE]
====
. Ou “da Sefelá”. Hebr.: hash·shefe·láh.
. Ou “do sul”.
====

[[v24-17-27]]

^<<v24-17-27,27>>^ “‘“Mas, se não me obedecerdes pela santificação do dia de sábado e por não carregardes nenhuma carga, mas se se entrar [com ela] pelos portões de Jerusalém no dia de sábado, então vou acender um fogo nos seus portões e este há de devorar as torres de habitação de Jerusalém e não será apagado.”’”

'''

xref:024-jeremias/024-jeremias-016.adoc#v24-16-0[&#60; Capítulo Anterior] | <<v24-17-0,Topo>> | xref:024-jeremias/024-jeremias-018.adoc#v24-18-0[Próximo Capítulo &#62;]