include::./index.adoc[]

[[v24-18-0]]
=== Jeremias, 18
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v24-18-1]]

^<<v24-18-1,1>>^ A palavra que veio a haver para Jeremias,^&#42;1^ da parte de Jeová, dizendo:

[NOTE]
====
. Veja 1:1 n.: “Jeremias”.
====

[[v24-18-2]]

^<<v24-18-2,2>>^ “Levanta-te, e tens de descer à casa do oleiro e ali te farei ouvir as minhas palavras.”

[[v24-18-3]]

^<<v24-18-3,3>>^ E passei a descer à casa do oleiro, e eis que ele fazia uma obra na roda de oleiro.

[[v24-18-4]]

^<<v24-18-4,4>>^ E o vaso que fazia do barro foi estragado pela mão do oleiro, e ele tornou e foi fazer dele outro vaso, conforme parecia direito fazer aos olhos do oleiro.^&#42;1^

[NOTE]
====
. Lit.: “formador”, ou: “aquele que forma (molda)”. Veja v. 11.
====

[[v24-18-5]]

^<<v24-18-5,5>>^ E continuou a vir a haver para mim a palavra de Jeová, dizendo:

[[v24-18-6]]

^<<v24-18-6,6>>^ “‘Não posso eu fazer a vós como este oleiro [fez], ó casa de Israel?’ é a pronunciação de Jeová. ‘Eis que, como o barro na mão do oleiro, assim sois vós na minha mão, ó casa de Israel.

[[v24-18-7]]

^<<v24-18-7,7>>^ Em qualquer momento em que eu falar contra uma nação e contra um reino, para [a] desarraigar, e para [a] demolir, e para [a] destruir,

[[v24-18-8]]

^<<v24-18-8,8>>^ e esta nação realmente recuar da sua maldade contra a qual falei, também eu vou deplorar a calamidade que pensei em executar sobre ela.

[[v24-18-9]]

^<<v24-18-9,9>>^ Mas, em qualquer momento em que eu falar a respeito de uma nação e a respeito de um reino, para [a] edificar e para [a] plantar,

[[v24-18-10]]

^<<v24-18-10,10>>^ e ela realmente fizer o que é mau aos meus olhos por não obedecer à minha voz, também eu vou deplorar o bem que eu disse [para mim] fazer-lhe para seu bem.’

[[v24-18-11]]

^<<v24-18-11,11>>^ “E agora, por favor, dize aos homens de Judá e aos habitantes de Jerusalém: ‘Assim disse Jeová: “Eis que formo contra vós uma calamidade e cogito contra vós um pensamento. Recuai, por favor, cada um do seu mau caminho, e tornai bons os vossos caminhos e vossas ações.”’”

[[v24-18-12]]

^<<v24-18-12,12>>^ E eles disseram: “É sem esperança! Pois andaremos seguindo os nossos próprios pensamentos e vamos executar cada um a obstinação de seu mau coração.”

[[v24-18-13]]

^<<v24-18-13,13>>^ Portanto, assim disse Jeová: “Perguntai vós mesmos, por favor, entre as nações. Quem já ouviu coisas como estas? Há uma coisa horrível que a virgem de Israel fez em demasia.

[[v24-18-14]]

^<<v24-18-14,14>>^ Acaso desaparecerá a neve do Líbano de cima da rocha da campina? Ou secar-se-ão águas estranhas, frescas, correntes?

[[v24-18-15]]

^<<v24-18-15,15>>^ Porque meu povo se esqueceu de mim, visto que fazem fumaça sacrificial a algo fútil, e nisto fazem os homens tropeçar nos seus caminhos, [nas] veredas de há muito tempo, para andarem em sendas, [num] caminho não aterrado,

[[v24-18-16]]

^<<v24-18-16,16>>^ a fim de fazer da sua terra um assombro, objeto de assobios, por tempo indefinido. Todo aquele que passar por ela olhará espantado e meneará a cabeça.

[[v24-18-17]]

^<<v24-18-17,17>>^ Eu os espalharei diante do inimigo como que com um vento oriental. As costas, e não a face, lhes mostrarei no dia do seu desastre.”

[[v24-18-18]]

^<<v24-18-18,18>>^ E passaram a dizer: “Vinde, homens, e cogitemos contra Jeremias alguns pensamentos, porque do sacerdote não perecerá a lei, nem do sábio o conselho, nem do profeta a palavra. Vinde e golpeemo-lo com a língua e não prestemos atenção a nenhuma das suas palavras.”

[[v24-18-19]]

^<<v24-18-19,19>>^ Dá-me deveras atenção, ó Jeová, e escuta a voz dos meus oponentes.^&#42;1^

[NOTE]
====
. Ou “contendedores”. LXX: “pleito”; Sy: “opressão”.
====

[[v24-18-20]]

^<<v24-18-20,20>>^ Acaso retribuir-se-á mal por bem? Pois escavaram uma cova para a minha alma. Lembra-te da minha posição perante ti, para falar bem, mesmo a respeito deles, para fazer recuar deles o teu furor.

[[v24-18-21]]

^<<v24-18-21,21>>^ Portanto, entrega seus filhos à fome e passa-os ao poder^&#42;1^ da espada; e tornem-se as suas esposas mulheres privadas de filhos e viúvas. E tornem-se os seus próprios homens os que foram mortos por uma praga mortífera, seus jovens, os que foram golpeados com a espada na batalha.

[NOTE]
====
. Lit.: “mãos”.
====

[[v24-18-22]]

^<<v24-18-22,22>>^ Ouça-se um grito procedente das suas casas, quando trouxeres sobre eles repentinamente uma guerrilha. Pois escavaram um fojo para capturar-me e encobriram armadilhas para os meus pés.

[[v24-18-23]]

^<<v24-18-23,23>>^ Mas tu mesmo, ó Jeová, conheces bem todo o seu conselho contra mim para a [minha] morte. Não encubras^&#42;1^ o seu erro e não obliteres este pecado deles diante de ti; mas tornem-se eles os que se fazem tropeçar diante de ti. No tempo da tua ira, toma ação contra eles.

[NOTE]
====
. Ou: “Não faças expiação por.” Hebr.: ’al·tekhap·pér ‛al.
====

'''

xref:024-jeremias/024-jeremias-017.adoc#v24-17-0[&#60; Capítulo Anterior] | <<v24-18-0,Topo>> | xref:024-jeremias/024-jeremias-019.adoc#v24-19-0[Próximo Capítulo &#62;]