include::./index.adoc[]

[[v24-49-0]]
=== Jeremias, 49
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v24-49-1]]

^<<v24-49-1,1>>^ Para os filhos de Amom, assim disse Jeová: “Porventura não tem Israel filhos e não tem herdeiro? Por que é que Malcão^&#42;1^ tomou posse de Gade^&#42;2^ e seu próprio povo passou a morar nas próprias cidades [de Israel]?”^&#42;3^

[NOTE]
====
. “Malcão” (significando “Seu Rei”), M; LXXSyVg: “Melcom”; LXXא,B: “Melcol”; T: “seu rei”.
. “Gade”, MLXXSyVg; T: “a terra de Gade”; LXXא,A,B: “Gileade”.
. Lit.: “dele”.
====

[[v24-49-2]]

^<<v24-49-2,2>>^ “‘Portanto, eis que vêm dias’, é a pronunciação de Jeová, ‘e eu vou fazer ouvir um rebate de guerra mesmo contra Rabá dos filhos de Amom; e ela certamente se tornará um monte de terra dum baldio desolado e as suas próprias aldeias dependentes^&#42;1^ serão incendiadas com o próprio fogo’.
“‘E Israel realmente se apossará dos que estão de posse dele’, disse Jeová.

[NOTE]
====
. Lit.: “suas filhas”.
====

[[v24-49-3]]

^<<v24-49-3,3>>^ “‘Uiva, ó Hésbon, porque Ai foi assolada! Gritai, ó aldeias dependentes de Rabá. Cingi-vos de serapilheira. Lamuriai e percorrei os redis de pedra, porque até mesmo o próprio Malcão será exilado, seus sacerdotes e seus príncipes, todos juntos.

[[v24-49-4]]

^<<v24-49-4,4>>^ Por que gabas as baixadas, tua baixada manante, ó filha infiel, tu, aquela que confiava nos seus tesouros, [dizendo:] “Quem chegará a mim?”’”

[[v24-49-5]]

^<<v24-49-5,5>>^ “‘Eis que trago sobre ti^&#42;1^ uma coisa pavorosa’, é a pronunciação do Soberano Senhor, Jeová dos exércitos, ‘de todos os ao teu redor. E vós haveis de ser dispersos, cada um na sua própria direção, e não haverá quem reúna os fugitivos.’”

[NOTE]
====
. “Ti”, hebr. fem. sing.
====

[[v24-49-6]]

^<<v24-49-6,6>>^ “‘Mas depois recolherei os cativos dos filhos de Amom’, é a pronunciação de Jeová.”

[[v24-49-7]]

^<<v24-49-7,7>>^ Para Edom, assim disse Jeová dos exércitos: “Há ainda qualquer sabedoria em Temã? Pereceu o conselho daqueles que têm entendimento?^&#42;1^ Putrefez-se a sua sabedoria?

[NOTE]
====
. “Daqueles que têm entendimento”, M, em harmonia com LXXSy; TVg e mediante outra derivação do M: “dos filhos”.
====

[[v24-49-8]]

^<<v24-49-8,8>>^ Fugi! Desandai! Descei fundo para morar, ó habitantes de Dedã! Porque vou fazer chegar sobre ele o desastre de Esaú, o tempo em que terei de voltar a minha atenção para ele.

[[v24-49-9]]

^<<v24-49-9,9>>^ Se realmente chegassem a ti vindimadores, não deixariam eles algumas rebuscas? Se [entrassem] ladrões de noite, certamente causariam apenas a ruína que quisessem.

[[v24-49-10]]

^<<v24-49-10,10>>^ Mas, no que se refere a mim, vou desnudar a Esaú. Vou expor seu esconderijo e ninguém poderá esconder-se. Sua descendência, e seus irmãos, e seus vizinhos hão de ser assolados, e ele não existirá.

[[v24-49-11]]

^<<v24-49-11,11>>^ Abandona teus meninos órfãos de pai. Eu mesmo [os] preservarei vivos e em mim é que confiarão as tuas próprias viúvas.”

[[v24-49-12]]

^<<v24-49-12,12>>^ Pois assim disse Jeová: “Eis que embora não seja seu costume beber o copo, beberão impreterivelmente. E tu mesmo, acaso ficarás inteiramente impune? Não ficarás impune, pois beberás impreterivelmente.”

[[v24-49-13]]

^<<v24-49-13,13>>^ “Pois jurei por mim mesmo”, é a pronunciação de Jeová, “que Bozra se tornará nada mais que um assombro, um vitupério, uma devastação e uma invocação do mal; e todas as suas próprias cidades tornar-se-ão lugares devastados por tempo indefinido.”

[[v24-49-14]]

^<<v24-49-14,14>>^ Há uma notícia que ouvi da parte de Jeová e há um emissário que foi enviado entre as nações, [dizendo:] “Reuni-vos e vinde contra ela, e levantai-vos para a batalha.”

[[v24-49-15]]

^<<v24-49-15,15>>^ “Pois, eis que te fiz deveras pequeno entre as nações, desprezado entre a humanidade.^&#42;1^

[NOTE]
====
. Ou “entre homens”. Hebr.: ba·’a·dhám.
====

[[v24-49-16]]

^<<v24-49-16,16>>^ Enganou-te o estremecimento que causavas, a presunção de teu coração, ó tu que resides nos retiros do rochedo, ocupando o alto do morro. Ainda que construas alto o teu ninho, igual à águia, de lá te farei descer”, é a pronunciação de Jeová.

[[v24-49-17]]

^<<v24-49-17,17>>^ “E Edom terá de tornar-se um assombro. Todo aquele que passar por ela olhará espantado e assobiará por causa de todas as suas pragas.

[[v24-49-18]]

^<<v24-49-18,18>>^ Como no derrubamento de Sodoma e de Gomorra, bem como de suas [cidades] vizinhas”, disse Jeová, “não morará ali nenhum homem e nenhum filho da humanidade^&#42;1^ residirá nela como forasteiro.

[NOTE]
====
. Ou “filho de homem terreno”. Hebr.: ben-’a·dhám.
====

[[v24-49-19]]

^<<v24-49-19,19>>^ “Eis que subirá alguém qual leão desde as orgulhosas [moitas] junto ao Jordão ao durável lugar de permanência, mas num instante vou fazê-lo correr para longe dela. E encarregarei dela o escolhido. Pois quem é igual a mim e quem me desafiará, e quem, pois, é o pastor que pode ficar de pé diante de mim?

[[v24-49-20]]

^<<v24-49-20,20>>^ Portanto, ouvi o conselho de Jeová, que formulou contra Edom, e seus pensamentos, que teve contra os habitantes de Temã: Por certo, os filhotes do rebanho serão arrastados. Seguramente, por causa deles fará que se torne desolada a sua moradia.

[[v24-49-21]]

^<<v24-49-21,21>>^ Ao ruído da sua queda começou a tremer a terra. Há um grito! O som dele foi ouvido até mesmo junto ao Mar Vermelho.

[[v24-49-22]]

^<<v24-49-22,22>>^ Eis que alguém subirá como águia e arremeterá, e estenderá suas asas sobre Bozra; e o coração dos poderosos de Edom, naquele dia, ficará realmente como o coração da esposa que tem aflição no parto.”

[[v24-49-23]]

^<<v24-49-23,23>>^ Para Damasco: “Hamate e Arpade ficaram envergonhadas, pois ouviram uma notícia má. Desintegraram-se. No mar há ansiedade; não pode ficar sossegado.

[[v24-49-24]]

^<<v24-49-24,24>>^ Damasco perdeu a coragem. Virou-se para fugir, e ela foi tomada de puro pânico. Apoderaram-se dela a própria aflição e as dores agudas do parto, como se dá com a mulher que dá à luz.

[[v24-49-25]]

^<<v24-49-25,25>>^ Como é que não foi abandonada a cidade de louvor, a vila de exultação?

[[v24-49-26]]

^<<v24-49-26,26>>^ “Por isso, seus jovens cairão nas suas praças públicas e mesmo todos os homens de guerra serão silenciados naquele dia”, é a pronunciação de Jeová dos exércitos.

[[v24-49-27]]

^<<v24-49-27,27>>^ “E eu vou acender um fogo na muralha de Damasco e este há de devorar as torres de habitação de Ben-Hadade.”

[[v24-49-28]]

^<<v24-49-28,28>>^ Para Quedar e os reinos de Hazor, golpeados por Nabucodorosor, rei de Babilônia, Jeová disse assim: “Levantai-vos, subi a Quedar e assolai os filhos do Oriente.

[[v24-49-29]]

^<<v24-49-29,29>>^ Tomar-se-ão suas próprias tendas e seus próprios rebanhos, seus panos de tenda e todos os seus objetos. E seus próprios camelos serão tirados deles. E certamente clamarão a eles: ‘Há horror ao redor!’”

[[v24-49-30]]

^<<v24-49-30,30>>^ “Fugi, ponde-vos em fuga para longe; descei fundo para morar, ó habitantes de Hazor”, é a pronunciação de Jeová. “Porque Nabucodorosor, rei de Babilônia, formulou um conselho até mesmo contra vós e teve contra vós^&#42;1^ um pensamento.”

[NOTE]
====
. “Vós”, MmargemTLXXVg e mais de 100 mss. hebr.; MSy: “eles”.
====

[[v24-49-31]]

^<<v24-49-31,31>>^ “Levantai-vos, subi contra a nação que está tranqüila, morando em segurança!” é a pronunciação de Jeová.
“Não tem portas nem tranca. Residem solitários.

[[v24-49-32]]

^<<v24-49-32,32>>^ E seus camelos terão de tornar-se saque e a multidão do seu gado, despojo. E eu vou espalhá-los a todo vento, os que têm seu cabelo cortado nas têmporas; e de todas as regiões próximas farei chegar seu desastre”, é a pronunciação de Jeová.

[[v24-49-33]]

^<<v24-49-33,33>>^ “E Hazor terá de tornar-se guarida de chacais, um baldio desolado por tempo indefinido. Nenhum homem^&#42;1^ morará ali e nenhum filho da humanidade^&#42;2^ residirá nela como forasteiro.”

[NOTE]
====
. “Homem.” Hebr.: ’ish.
. Veja v. 18 n.
====

[[v24-49-34]]

^<<v24-49-34,34>>^ Isto é o que veio a haver para Jeremias, o profeta, como a palavra de Jeová a respeito de Elão, no princípio do reinado de Zedequias, rei de Judá, dizendo:

[[v24-49-35]]

^<<v24-49-35,35>>^ “Assim disse Jeová dos exércitos: ‘Eis que quebro o arco de Elão, o princípio da sua potência.

[[v24-49-36]]

^<<v24-49-36,36>>^ E eu vou fazer chegar sobre Elão os quatro ventos das quatro extremidades dos céus. E vou espalhá-los a todos estes ventos e não se mostrará haver nação à qual não tenham chegado os dispersos de Elão.’”^&#42;1^

[NOTE]
====
. “De Elão”, MmargemTLXXSyVg e muitos mss. hebr.; M: “por (de) tempo indefinido”.
====

[[v24-49-37]]

^<<v24-49-37,37>>^ “E vou desbaratar os elamitas diante dos seus inimigos e diante dos que procuram a sua alma; e vou trazer sobre eles uma calamidade, minha ira ardente”, é a pronunciação de Jeová. “E vou enviar atrás deles a espada até que eu os tenha exterminado.”

[[v24-49-38]]

^<<v24-49-38,38>>^ “E eu vou colocar meu trono em Elão e vou destruir dali o rei e os príncipes”, é a pronunciação de Jeová.

[[v24-49-39]]

^<<v24-49-39,39>>^ “E certamente acontecerá na parte final dos dias que recolherei os cativos de Elão”, é a pronunciação de Jeová.

'''

xref:024-jeremias/024-jeremias-048.adoc#v24-48-0[&#60; Capítulo Anterior] | <<v24-49-0,Topo>> | xref:024-jeremias/024-jeremias-050.adoc#v24-50-0[Próximo Capítulo &#62;]