include::./index.adoc[]

[[v24-20-0]]
=== Jeremias, 20
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v24-20-1]]

^<<v24-20-1,1>>^ Ora, Pasur, filho de Imer, o sacerdote, que era também o comissário que liderava na casa de Jeová, estava escutando Jeremias enquanto profetizava estas palavras.

[[v24-20-2]]

^<<v24-20-2,2>>^ Pasur golpeou então Jeremias, o profeta, e o pôs no tronco que havia no Portão Superior de Benjamim, na casa de Jeová.

[[v24-20-3]]

^<<v24-20-3,3>>^ Mas, sucedeu no dia seguinte que Pasur passou a soltar Jeremias do tronco e Jeremias lhe disse então:
“Jeová não te chamou pelo nome de Pasur,^&#42;1^ mas de Horror ao redor.^&#42;2^

[NOTE]
====
. “Pasur.” Segundo a derivação judeu-aramaica, este nome significa “O Que Resta ao Redor” (hebr.: pash, “resta” e sehhóhr, “ao redor”).
. “Horror ao redor.” Ou “Magormissabib”. Hebr.: Ma·ghóhr mis·sa·vív.
====

[[v24-20-4]]

^<<v24-20-4,4>>^ Pois assim disse Jeová: ‘Eis que te faço um horror para ti mesmo e para todos os que te amam,^&#42;1^ e eles hão de cair pela espada dos seus inimigos enquanto os teus olhos estiverem olhando; e todo o Judá eu entregarei na mão do rei de Babilônia e ele realmente os levará ao exílio em Babilônia e os golpeará com a espada.

[NOTE]
====
. Ou “amigos”.
====

[[v24-20-5]]

^<<v24-20-5,5>>^ E vou entregar todas as coisas armazenadas desta cidade, e todo o seu produto, e todas as suas coisas preciosas; e todos os tesouros dos reis de Judá vou entregar na mão dos seus inimigos. E eles certamente os saquearão, e os tomarão e os levarão a Babilônia.^&#42;1^

[NOTE]
====
. “Babilônia”, LXXVg; MTSy: “Babel”.
====

[[v24-20-6]]

^<<v24-20-6,6>>^ E no que se refere a ti, ó Pasur, e a todos os habitantes da tua casa, vós ireis ao cativeiro; e chegarás a Babilônia e ali morrerás, e ali serás enterrado com todos os que te amam, porque lhes profetizaste em falsidade.’”

[[v24-20-7]]

^<<v24-20-7,7>>^ Tu me lograste, ó Jeová, de modo que fui logrado. Usaste a tua força contra mim, de modo que prevaleceste. Tornei-me objeto de riso o dia inteiro; todos caçoam de mim.

[[v24-20-8]]

^<<v24-20-8,8>>^ Pois, quantas vezes falo, eu clamo. Violência e assolação é o que clamo. Porque a palavra de Jeová tornou-se para mim uma causa para vitupério e para troça, o dia inteiro.

[[v24-20-9]]

^<<v24-20-9,9>>^ E eu disse: “Não farei menção dele e não vou mais falar em seu nome.” E isto mostrou ser no meu coração como um fogo aceso encerrado nos meus ossos; e fiquei fatigado de contê-lo e não pude [mais suportá-lo].^&#42;1^

[NOTE]
====
. “Suportá-lo”, em harmonia com LXXVg.
====

[[v24-20-10]]

^<<v24-20-10,10>>^ Pois ouvi o relato mau de muitos. Havia horror ao redor.^&#42;1^ “Contai-o, para que [o] contemos a respeito dele.” Todo homem mortal me deseja: “Paz!”^&#42;2^ — estão vigiando para [ver-me] manquejar: “Talvez seja logrado para que possamos prevalecer contra ele e vingar-nos dele.”

[NOTE]
====
. “Horror ao redor.” Hebr.: ma·ghóhr mis·sa·vív. Veja v. 3 n.: “ao redor”.
. Lit.: “homem mortal [hebr.: ’enóhsh] da minha paz”.
====

[[v24-20-11]]

^<<v24-20-11,11>>^ Mas Jeová estava comigo como um poderoso terrível. Por isso é que os que me perseguem tropeçarão e não prevalecerão. Certamente serão muito envergonhados, porque não terão prosperado. [Sua] humilhação de duração indefinida será tal que não será esquecida.

[[v24-20-12]]

^<<v24-20-12,12>>^ Mas tu, ó Jeová dos exércitos, examinas o justo; vês os rins^&#42;1^ e o coração. Veja eu a tua vingança contra eles, porque te revelei a minha causa.

[NOTE]
====
. Veja 11:20 n.
====

[[v24-20-13]]

^<<v24-20-13,13>>^ Cantai a Jeová! Louvai a Jeová! Porque livrou a alma do pobre da mão dos malfeitores.

[[v24-20-14]]

^<<v24-20-14,14>>^ Maldito o dia em que nasci! Não fique abençoado o dia em que a minha mãe me deu à luz!

[[v24-20-15]]

^<<v24-20-15,15>>^ Maldito o homem^&#42;1^ que trouxe boas novas a meu pai, dizendo: “Nasceu-te um filho, um macho!” Ele positivamente o fez alegrar-se.

[NOTE]
====
. “O homem.” Hebr.: ha·’ísh.
====

[[v24-20-16]]

^<<v24-20-16,16>>^ E este mesmo homem terá de tornar-se igual a cidades que Jeová subverteu, sem que Ele o deplorasse. E ele terá de ouvir um clamor de manhã e um sinal de alarme ao tempo do meio-dia.

[[v24-20-17]]

^<<v24-20-17,17>>^ Por que é que ele não me entregou definitivamente à morte, desde a madre, para que minha mãe se tornasse para mim a minha sepultura e sua madre estivesse grávida por tempo indefinido?

[[v24-20-18]]

^<<v24-20-18,18>>^ Por que é que saí da própria madre, a fim de ver trabalho árduo e pesar, e que meus dias devam chegar ao seu fim em mera vergonha?

'''

xref:024-jeremias/024-jeremias-019.adoc#v24-19-0[&#60; Capítulo Anterior] | <<v24-20-0,Topo>> | xref:024-jeremias/024-jeremias-021.adoc#v24-21-0[Próximo Capítulo &#62;]