include::./index.adoc[]

[[v24-41-0]]
=== Jeremias, 41
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v24-41-1]]

^<<v24-41-1,1>>^ Sucedeu, pois, no sétimo mês, que Ismael, filho de Netanias, filho de Elisama, da descendência real^&#42;1^ e [dos] homens principais do rei, e mais dez homens com ele, chegaram a Gedalias,^&#42;2^ filho de Aicão, em Mispá. E ali começaram a comer juntos pão, em Mispá.

[NOTE]
====
. Ou “prole do reinado”.
. Veja 38:1 n.: “Gedalias”.
====

[[v24-41-2]]

^<<v24-41-2,2>>^ Então se levantaram Ismael, filho de Netanias, e os dez homens que vieram a estar com ele, e golpearam a Gedalias, filho de Aicão, filho de Safã, com a espada. De modo que entregou à morte aquele a quem o rei de Babilônia encarregara do país.

[[v24-41-3]]

^<<v24-41-3,3>>^ E Ismael golpeou a todos os judeus que vieram a estar com ele, isto é, com Gedalias, em Mispá, e os caldeus que se achavam ali, isto é, os homens de guerra.

[[v24-41-4]]

^<<v24-41-4,4>>^ E sucedeu que, no segundo dia de se ter morto Gedalias, não havendo ninguém que [o] soubesse,

[[v24-41-5]]

^<<v24-41-5,5>>^ chegaram então homens de Siquém, de Silo e de Samaria, oitenta homens com as suas barbas raspadas, e com as suas vestes rasgadas, e com cortes feitos em si mesmos, e havia oferta de cereais e olíbano na sua mão para levar à casa de Jeová.

[[v24-41-6]]

^<<v24-41-6,6>>^ Portanto, Ismael, filho de Netanias, saiu de Mispá ao encontro deles, chorando enquanto caminhava. E sucedeu que, assim que se encontrou com eles, passou a dizer-lhes: “Vinde a Gedalias, filho de Aicão.”

[[v24-41-7]]

^<<v24-41-7,7>>^ Mas, aconteceu que, assim que entraram no meio da cidade, Ismael, filho de Netanias, foi abatê-los [e lançá-los]^&#42;1^ dentro da cisterna, ele e os homens que estavam com ele.

[NOTE]
====
. “E lançá-los”, Sy. Veja v. 9.
====

[[v24-41-8]]

^<<v24-41-8,8>>^ Mas entre eles se achavam dez homens que disseram imediatamente a Ismael: “Não nos entregues à morte, pois estamos de posse de tesouros escondidos no campo, trigo, e cevada, e azeite, e mel.” De modo que se refreou e não os entregou à morte no meio dos seus irmãos.

[[v24-41-9]]

^<<v24-41-9,9>>^ Ora, a cisterna na qual Ismael lançou todos os cadáveres dos homens que golpeara era uma cisterna grande,^&#42;1^ aquela que o Rei Asa fizera por causa de Baasa, rei de Israel. Foi esta que Ismael, filho de Netanias,^&#42;2^ encheu com os que foram mortos.

[NOTE]
====
. “Era uma cisterna grande”, LXX; M: “pela mão (às instâncias) de Gedalias”.
. Veja 36:14 n.: “Netanias”.
====

[[v24-41-10]]

^<<v24-41-10,10>>^ Ismael levou então cativo todo o restante do povo que estava em Mispá, as filhas do rei e todo o povo que restava em Mispá, que Nebuzaradã, chefe da guarda pessoal, entregara aos cuidados de Gedalias, filho de Aicão. De modo que Ismael, filho de Netanias, levou-os cativos e se foi para passar aos filhos de Amom.

[[v24-41-11]]

^<<v24-41-11,11>>^ Com o tempo, Joanã, filho de Careá, e todos os chefes das forças militares que estavam com ele chegaram a ouvir todo o mal feito por Ismael, filho de Netanias.

[[v24-41-12]]

^<<v24-41-12,12>>^ Por conseguinte, tomaram todos os homens e se foram para lutar contra Ismael, filho de Netanias, e acharam-no junto às águas abundantes que havia em Gibeão.

[[v24-41-13]]

^<<v24-41-13,13>>^ Aconteceu então que, assim que todo o povo que estava com Ismael viu Joanã, filho de Careá, e todos os chefes das forças militares que estavam com ele, começaram a alegrar-se.

[[v24-41-14]]

^<<v24-41-14,14>>^ E todo o povo que Ismael levara cativo de Mispá passou a dar volta e a retornar, e a ir a Joanã, filho de Careá.

[[v24-41-15]]

^<<v24-41-15,15>>^ E no que se refere a Ismael, filho de Netanias, escapou com oito homens de diante de Joanã para ir ter com os filhos de Amom.

[[v24-41-16]]

^<<v24-41-16,16>>^ Joanã, filho de Careá, e todos os chefes das forças militares que estavam com ele tomaram então todo o restante do povo que trouxeram de volta de Ismael, filho de Netanias, de Mispá, depois que golpeara a Gedalias, filho de Aicão, varões vigorosos, homens de guerra, e as esposas e as criancinhas, bem como os oficiais da corte que trouxera de volta de Gibeão.

[[v24-41-17]]

^<<v24-41-17,17>>^ Eles foram, pois, e passaram a morar na hospedaria de Quimão, que estava perto de Belém, a fim de seguirem adiante e entrarem no Egito,

[[v24-41-18]]

^<<v24-41-18,18>>^ por causa dos caldeus; pois tinham ficado com medo deles, visto que Ismael, filho de Netanias, golpeara a Gedalias, filho de Aicão, a quem o rei de Babilônia encarregara do país.

'''

xref:024-jeremias/024-jeremias-040.adoc#v24-40-0[&#60; Capítulo Anterior] | <<v24-41-0,Topo>> | xref:024-jeremias/024-jeremias-042.adoc#v24-42-0[Próximo Capítulo &#62;]