include::./index.adoc[]

[[v24-33-0]]
=== Jeremias, 33
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v24-33-1]]

^<<v24-33-1,1>>^ E passou a vir a haver a palavra de Jeová para Jeremias pela segunda vez, enquanto ele ainda estava encerrado no Pátio da Guarda, dizendo:

[[v24-33-2]]

^<<v24-33-2,2>>^ “Assim disse Jeová, Aquele que fez [a terra],^&#42;1^ Jeová, o Formador dela para a estabelecer firmemente, cujo nome é Jeová:

[NOTE]
====
. Lit.: “a fez”.
====

[[v24-33-3]]

^<<v24-33-3,3>>^ ‘Chama-me e eu te^&#42;1^ responderei e te contarei prontamente coisas grandes e incompreensíveis que não sabias.’”

[NOTE]
====
. “Te”, hebr. masc. sing.
====

[[v24-33-4]]

^<<v24-33-4,4>>^ “Pois assim disse Jeová, o Deus de Israel, a respeito das casas desta cidade e a respeito das casas dos reis de Judá, que estão demolidas por causa dos aterros de sítio e por causa da espada;

[[v24-33-5]]

^<<v24-33-5,5>>^ [a respeito] dos que estão chegando para lutar contra os caldeus e para encher espaços com os cadáveres dos homens^&#42;1^ que golpeei na minha ira e no meu furor, e por cuja maldade toda eu escondi minha face desta cidade:

[NOTE]
====
. “Dos homens.” Hebr.: ha·’a·dhám.
====

[[v24-33-6]]

^<<v24-33-6,6>>^ ‘Eis que suscito para ela restabelecimento e saúde; e eu vou sará-los e revelar-lhes uma abundância de paz e de verdade.

[[v24-33-7]]

^<<v24-33-7,7>>^ E vou trazer de volta os cativos de Judá e os cativos de Israel, e vou edificá-los assim como no princípio.

[[v24-33-8]]

^<<v24-33-8,8>>^ E eu vou purificá-los de todo o seu erro com que pecaram contra mim e vou perdoar-lhes todos os erros com que pecaram contra mim e com que transgrediram contra mim.

[[v24-33-9]]

^<<v24-33-9,9>>^ E ela certamente se tornará para mim um nome de exultação, louvor e beleza para com todas as nações da terra, que ouvirão [falar] de toda a bondade que eu lhes faço. E certamente ficarão apavorados e agitados por causa de toda a bondade e por causa de toda a paz que faço [vir] a ela.’”

[[v24-33-10]]

^<<v24-33-10,10>>^ “Assim disse Jeová: ‘Neste lugar de que direis que está deserto, sem homem^&#42;1^ nem animal doméstico, nas cidades de Judá e nas ruas de Jerusalém, que estão desoladas sem homem, nem habitante, nem animal doméstico, ainda se ouvirá

[NOTE]
====
. “Homem.” Hebr.: ’a·dhám.
====

[[v24-33-11]]

^<<v24-33-11,11>>^ o som de exultação e o som de alegria, a voz do noivo e a voz da noiva, a voz dos que dizem: “Elogiai a Jeová dos exércitos, porque Jeová é bom; pois a sua benevolência^&#42;1^ é por tempo indefinido!”’
“‘Trarão ofertas de agradecimento à casa de Jeová, pois trarei de volta os cativos da terra assim como no princípio’, disse Jeová.”

[NOTE]
====
. Ou “seu amor leal”. Hebr.: hhas·dóh.
====

[[v24-33-12]]

^<<v24-33-12,12>>^ “Assim disse Jeová dos exércitos: ‘Neste lugar deserto, sem homem nem mesmo animal doméstico, bem como em todas as suas cidades, ainda virá a haver a pastagem dos pastores que fazem o rebanho deitar-se.’

[[v24-33-13]]

^<<v24-33-13,13>>^ “‘Nas cidades da região montanhosa, nas cidades da terra baixa, e nas cidades do sul, e na terra de Benjamim, e nos arredores de Jerusalém, e nas cidades de Judá, ainda passarão os rebanhos debaixo da mão daquele que faz a contagem’, disse Jeová.”

[[v24-33-14]]

^<<v24-33-14,14>>^ “‘Eis que vêm dias’, é a pronunciação de Jeová, ‘e eu certamente cumprirei a boa palavra que falei, referente à casa de Israel e referente à casa de Judá.

[[v24-33-15]]

^<<v24-33-15,15>>^ Naqueles dias e naquele tempo farei brotar um renovo justo para Davi, e ele certamente executará o juízo e a justiça no país.^&#42;1^

[NOTE]
====
. Ou “na terra”. Hebr.: ba·’á·rets.
====

[[v24-33-16]]

^<<v24-33-16,16>>^ Naqueles dias, Judá será salva e a própria Jerusalém residirá em segurança. E isto é o que ela será chamada: Jeová É Nossa Justiça.’”^&#42;1^

[NOTE]
====
. Veja 23:6 n.
====

[[v24-33-17]]

^<<v24-33-17,17>>^ “Pois assim disse Jeová: ‘No caso de Davi, não se decepará homem [seu, impedindo-o] de sentar-se^&#42;1^ no trono da casa de Israel.

[NOTE]
====
. Lit.: “homem sentado”. Hebr.: ’ish yo·shév.
====

[[v24-33-18]]

^<<v24-33-18,18>>^ E no caso dos sacerdotes, os levitas,^&#42;1^ não se decepará de diante de mim homem [impedindo-o] de oferecer holocaustos, e de fazer fumaça com a oferta de cereais, e de ofertar sacrifício, para sempre.’”^&#42;2^

[NOTE]
====
. Ou “dos sacerdotes levitas”.
. Lit.: “todos os dias”. Hebr.: kol·hai·ya·mím.
====

[[v24-33-19]]

^<<v24-33-19,19>>^ E a palavra de Jeová veio adicionalmente a Jeremias, dizendo:

[[v24-33-20]]

^<<v24-33-20,20>>^ “Assim disse Jeová: ‘Se vós pudésseis violar meu pacto do dia e meu pacto da noite, sim, para não haver mais dia e noite no seu tempo,

[[v24-33-21]]

^<<v24-33-21,21>>^ também se poderia violar meu próprio pacto com Davi, meu servo, para que não viesse a ter um filho reinando no seu trono; também com os levitas, os sacerdotes, meus ministros.

[[v24-33-22]]

^<<v24-33-22,22>>^ Assim como não se pode contar o exército dos céus, nem se pode medir a areia do mar, assim multiplicarei a descendência de Davi, meu servo, e os levitas que me ministram.’”

[[v24-33-23]]

^<<v24-33-23,23>>^ E continuou a vir a haver para Jeremias a palavra de Jeová, dizendo:

[[v24-33-24]]

^<<v24-33-24,24>>^ “Não viste o que os deste povo têm falado, dizendo: ‘As duas famílias que Jeová escolheu, ele também as rejeitará’? E o meu próprio povo eles estão tratando com desrespeito, para que não continue mais a ser nação diante deles.

[[v24-33-25]]

^<<v24-33-25,25>>^ “Assim disse Jeová: ‘Se não fosse o fato de eu ter designado meu próprio pacto do dia e da noite, os estatutos do céu e da terra,

[[v24-33-26]]

^<<v24-33-26,26>>^ então, também, eu rejeitaria a descendência de Jacó e de Davi, meu servo, de modo a não tomar da sua descendência^&#42;1^ governantes sobre a descendência de Abraão, de Isaque e de Jacó. Pois recolherei os seus cativos e terei piedade deles.’”

[NOTE]
====
. Ou “prole; posteridade”.
====

'''

xref:024-jeremias/024-jeremias-032.adoc#v24-32-0[&#60; Capítulo Anterior] | <<v24-33-0,Topo>> | xref:024-jeremias/024-jeremias-034.adoc#v24-34-0[Próximo Capítulo &#62;]