include::./index.adoc[]

[[v24-14-0]]
=== Jeremias, 14
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v24-14-1]]

^<<v24-14-1,1>>^ [Isto é] o que veio a haver para Jeremias^&#42;1^ como a palavra de Jeová, referente aos assuntos das secas:

[NOTE]
====
. Veja 1:1 n.: “Jeremias”.
====

[[v24-14-2]]

^<<v24-14-2,2>>^ Judá pôs-se a prantear e seus próprios portões se desfizeram. Ficaram acabrunhados até à terra, e subiu até mesmo o clamor de Jerusalém.

[[v24-14-3]]

^<<v24-14-3,3>>^ E os próprios majestosos deles mandaram os seus insignificantes^&#42;1^ [buscar] água. Chegaram às valas. Não acharam água. Retornaram com os seus vasos vazios. Foram envergonhados e ficaram desapontados, e cobriram a sua cabeça.

[NOTE]
====
. Ou “pequenos; jovens”, tais como ajudantes ou servos.
====

[[v24-14-4]]

^<<v24-14-4,4>>^ Por causa do solo que ficou fragmentado, visto que não ocorreu aguaceiro no país, os lavradores ficaram envergonhados; cobriram a sua cabeça.

[[v24-14-5]]

^<<v24-14-5,5>>^ Porque até mesmo a gama no campo pariu, abandonando,^&#42;1^ porém, [o filhote], porque não se mostrou haver relva tenra.

[NOTE]
====
. No hebr., este verbo está no infinitivo absoluto.
====

[[v24-14-6]]

^<<v24-14-6,6>>^ E as próprias zebras ficaram paradas sobre os morros calvos; fungaram o vento como os chacais; seus olhos falharam por não haver vegetação.

[[v24-14-7]]

^<<v24-14-7,7>>^ Ainda que os nossos próprios erros testifiquem contra nós, ó Jeová, age por causa do teu nome; pois, tornaram-se muitos os nossos atos de infidelidade; é contra ti que pecamos.

[[v24-14-8]]

^<<v24-14-8,8>>^ Ó tu, esperança de Israel,^&#42;1^ Salvador dele no tempo da aflição, por que te tornas como um residente forasteiro no país e como o viajante que se desviou para passar a noite?

[NOTE]
====
. LXX e 13 mss. hebr. acrescentam: “Jeová”.
====

[[v24-14-9]]

^<<v24-14-9,9>>^ Por que te tornas como um homem^&#42;1^ surpreso, como um poderoso^&#42;2^ que não pode salvar? No entanto, tu mesmo estás no nosso meio, ó Jeová, e sobre nós é que foi invocado o teu próprio nome. Não nos desampares.

[NOTE]
====
. “Como um homem.” Hebr.: ke’ísh.
. “Como um poderoso.” Hebr.: keghib·bóhr.
====

[[v24-14-10]]

^<<v24-14-10,10>>^ Assim disse Jeová a respeito deste povo: “Assim amaram andar errantes; não refrearam seus pés. Por isso, o próprio Jeová não teve prazer neles. Agora se lembrará do erro deles e dará atenção aos seus pecados.”

[[v24-14-11]]

^<<v24-14-11,11>>^ E Jeová passou a dizer-me: “Não ores a favor deste povo por qualquer bem.

[[v24-14-12]]

^<<v24-14-12,12>>^ Quando jejuam, não escuto seu clamor suplicante; e quando oferecem o holocausto e a oferta de cereais, não tenho prazer neles; porque estou acabando com eles por meio da espada, e da fome, e da pestilência.”

[[v24-14-13]]

^<<v24-14-13,13>>^ A isto eu disse: “Ai! ó Soberano Senhor Jeová! Eis que os profetas lhes estão dizendo: ‘Não vereis a espada e não virá a haver fome para vós, mas é a verdadeira paz^&#42;1^ que vos darei neste lugar.’”

[NOTE]
====
. Ou “paz em veracidade”.
====

[[v24-14-14]]

^<<v24-14-14,14>>^ E Jeová prosseguiu, dizendo-me: “Falsidade é o que os profetas estão profetizando em meu nome. Não os enviei, nem lhes dei ordem, nem falei com eles. Falam-vos profeticamente duma visão falsa, e de adivinhação, e duma coisa que nada vale, e da ardileza de seu coração.

[[v24-14-15]]

^<<v24-14-15,15>>^ Portanto, assim disse Jeová a respeito dos profetas que profetizam em meu nome e que eu mesmo não enviei, e que estão dizendo que não virá a haver nem espada nem fome nesta terra: ‘Pela espada e pela fome chegarão ao seu fim estes profetas.

[[v24-14-16]]

^<<v24-14-16,16>>^ E o próprio povo a quem eles profetizam tornar-se-á gente lançada nas ruas de Jerusalém, por causa da fome e da espada, sem haver quem os enterre — eles, suas esposas e seus filhos, e suas filhas. E eu vou derramar sobre eles a sua calamidade.’

[[v24-14-17]]

^<<v24-14-17,17>>^ “E tens de dizer-lhes esta palavra: ‘Vertam meus olhos lágrimas, noite e dia, e não parem, porque a virgem filha do meu povo foi quebrantada com uma grande derrocada, com um golpe extremamente mórbido.

[[v24-14-18]]

^<<v24-14-18,18>>^ Se eu realmente saio ao campo, eis, pois, os mortos pela espada! E se eu realmente entro na cidade, eis, também, as enfermidades devido à fome! Porque tanto o próprio profeta como o sacerdote foram dando voltas até um país que não conheceram.’”

[[v24-14-19]]

^<<v24-14-19,19>>^ Rejeitaste completamente a Judá ou aborreceu a tua alma até mesmo Sião? Por que é que nos golpeaste, de modo que não há cura para nós? Esperava-se a paz, mas [não veio] nenhum bem; e um tempo de cura, mas eis terror!

[[v24-14-20]]

^<<v24-14-20,20>>^ Reconhecemos deveras a nossa iniqüidade, ó Jeová, o erro de nossos antepassados, pois pecamos contra ti.

[[v24-14-21]]

^<<v24-14-21,21>>^ Não [nos] desrespeites, por causa do teu nome; não desprezes o teu glorioso trono. Lembra-te; não rompas o teu pacto conosco.

[[v24-14-22]]

^<<v24-14-22,22>>^ Acaso há entre os ídolos vãos das nações quaisquer que possam fazer chover, ou podem até mesmo os próprios céus dar chuvas copiosas? Não és tu Aquele, ó Jeová, nosso Deus? E nós esperamos em ti, porque tu mesmo fizeste todas estas coisas.

'''

xref:024-jeremias/024-jeremias-013.adoc#v24-13-0[&#60; Capítulo Anterior] | <<v24-14-0,Topo>> | xref:024-jeremias/024-jeremias-015.adoc#v24-15-0[Próximo Capítulo &#62;]