include::./index.adoc[]

[[v24-3-0]]
=== Jeremias, 3
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v24-3-1]]

^<<v24-3-1,1>>^ Há um ditado: “Se um homem^&#42;1^ mandasse embora a sua esposa^&#42;2^ e ela realmente se afastasse dele e se tornasse de outro homem, deveria ele ainda retornar a ela?”
Não foi decididamente poluída essa terra?^&#42;3^
“E tu^&#42;4^ mesma cometeste prostituição com muitos companheiros; e deveria haver um retorno a mim?” é a pronunciação de Jeová.

[NOTE]
====
. Ou “marido”. Hebr.: ’ish.
. “Sua esposa (mulher).” Hebr.: ’ish·tóh.
. “Terra”, MTSy; LXXVg: “mulher”.
. “Tu”, hebr. fem. sing., dirigido a Jerusalém ou Sião.
====

[[v24-3-2]]

^<<v24-3-2,2>>^ “Levanta os olhos para as veredas batidas e vê. Onde é que não foste estuprada?^&#42;1^ Tu te sentaste para eles à beira dos caminhos, assim como o árabe no ermo; e continuas a poluir a terra com os teus atos de prostituição e com a tua maldade.

[NOTE]
====
. “Estuprada”, M; Mmargem, “se deitaram contigo”.
====

[[v24-3-3]]

^<<v24-3-3,3>>^ Por isso se retém as chuvas copiosas e não veio a haver nem mesmo chuva primaveril. E testa de uma esposa que comete prostituição é que se tornou a tua. Tu te negaste a sentir-te humilhada.

[[v24-3-4]]

^<<v24-3-4,4>>^ Não clamaste a mim, daí para diante: ‘Meu Pai, tu és o amigo íntimo da minha mocidade!

[[v24-3-5]]

^<<v24-3-5,5>>^ Deve-se ficar ressentido por tempo indefinido ou ficar vigiando [algo] para sempre’? Eis que falaste, e prosseguiste a fazer coisas más e a prevalecer.”

[[v24-3-6]]

^<<v24-3-6,6>>^ E Jeová passou a dizer-me nos dias de Josias, o rei: “‘Viste o que fez a infiel Israel?^&#42;1^ Ela anda sobre todo monte alto e debaixo de toda árvore frondosa, para ali cometer prostituição.

[NOTE]
====
. Lit.: “a infidelidade (apostasia), Israel”, citando-se assim Israel como exemplo concreto de infidelidade ou apostasia.
====

[[v24-3-7]]

^<<v24-3-7,7>>^ E depois de ela fazer todas estas coisas, eu continuava a dizer que devia voltar a mim, mas ela não voltou; e Judá olhava para a sua própria irmã traiçoeira.

[[v24-3-8]]

^<<v24-3-8,8>>^ Quando cheguei a ver isso, pela própria razão de que a infiel Israel cometera adultério, mandei-a embora e passei a dar-lhe um certificado de seu pleno divórcio, contudo, a traiçoeira Judá, sua irmã, não ficou com medo, mas ela mesma também começou a ir e a cometer prostituição.

[[v24-3-9]]

^<<v24-3-9,9>>^ E a sua prostituição veio a dar-se por causa do [seu] conceito frívolo, e ela continuou a poluir a terra e a cometer adultério com pedras e com árvores;

[[v24-3-10]]

^<<v24-3-10,10>>^ e mesmo apesar de tudo isso, sua traiçoeira irmã Judá não voltou a mim de todo o seu coração, [mas] somente de modo falso’, é a pronunciação de Jeová.”

[[v24-3-11]]

^<<v24-3-11,11>>^ E Jeová prosseguiu, dizendo-me: “A infiel Israel mostrou que a sua própria alma era mais justa do que a traiçoeira Judá.

[[v24-3-12]]

^<<v24-3-12,12>>^ Vai,^&#42;1^ e tens de proclamar estas palavras ao norte e dizer:
“‘“Volta deveras, ó renegada Israel”, é a pronunciação de Jeová.’ ‘“Não deixarei a minha face decair [em ira] para convosco, porque sou leal”, é a pronunciação de Jeová.’ ‘“Não ficarei ressentido por tempo indefinido.

[NOTE]
====
. Veja 2:2 n.: “Vai.”
====

[[v24-3-13]]

^<<v24-3-13,13>>^ Tão-somente nota o teu erro, pois é contra Jeová, teu Deus,^&#42;1^ que transgrediste.^&#42;2^ E continuaste a dispersar os teus caminhos para os estranhos, debaixo de cada árvore frondosa, mas a minha voz é que não escutastes”, é a pronunciação de Jeová.’”

[NOTE]
====
. “Teu Deus.” Hebr.: ’Elo·há·yikh, pl.
. “Transgrediste”, hebr. fem. sing.
====

[[v24-3-14]]

^<<v24-3-14,14>>^ “Voltai, ó filhos renegados”, é a pronunciação de Jeová. “Pois eu mesmo me tornei dono marital de vós; e vou tomar-vos, um dentre uma cidade e dois dentre uma família, e vou trazer-vos a Sião.

[[v24-3-15]]

^<<v24-3-15,15>>^ E vou dar-vos pastores de acordo com o meu coração, e eles hão de alimentar-vos^&#42;1^ com conhecimento e perspicácia.

[NOTE]
====
. Ou “pastorear-vos”.
====

[[v24-3-16]]

^<<v24-3-16,16>>^ E terá de acontecer que vós vos tornareis muitos e certamente dareis fruto na terra,^&#42;1^ naqueles dias”, é a pronunciação de Jeová. “Não mais dirão: ‘A arca do pacto de Jeová!’ nem subirá ao coração, nem se lembrarão dela ou sentirão sua falta, e não mais será feita.

[NOTE]
====
. “Na terra.” Hebr.: ba’á·rets.
====

[[v24-3-17]]

^<<v24-3-17,17>>^ Naquele tempo chamarão Jerusalém de trono de Jeová; e a ela terão de ser ajuntadas todas as nações, ao nome de Jeová em Jerusalém, e não mais andarão seguindo a obstinação do seu mau coração.”

[[v24-3-18]]

^<<v24-3-18,18>>^ “Naqueles dias andarão, a casa de Judá ao lado^&#42;1^ da casa de Israel, e juntas sairão da terra do norte para a terra que dei como propriedade hereditária aos vossos^&#42;2^ antepassados.

[NOTE]
====
. Ou “até à”.
. “Vossos”, pl., MVg; TLXXSy: “seus”.
====

[[v24-3-19]]

^<<v24-3-19,19>>^ E eu mesmo disse: ‘Oh! como passei a pôr-te^&#42;1^ entre os filhos e a dar-te a terra desejável, a propriedade hereditária do ornato dos exércitos das nações!’ E eu disse mais: ‘“Meu Pai!” vós me chamareis, e não recuareis de seguir-me.’

[NOTE]
====
. “Te”, hebr. fem. sing.
====

[[v24-3-20]]

^<<v24-3-20,20>>^ ‘Verdadeiramente, [assim como] a esposa^&#42;1^ se afastou traiçoeiramente do seu companheiro, assim vós, ó casa de Israel, agistes traiçoeiramente para comigo’, é a pronunciação de Jeová.”

[NOTE]
====
. Ou “mulher”. Hebr.: ’ish·sháh.
====

[[v24-3-21]]

^<<v24-3-21,21>>^ Nas veredas batidas ouviu-se um som, o choro, os rogos dos filhos de Israel. Pois entortaram seu caminho; esqueceram-se de Jeová, seu Deus.^&#42;1^

[NOTE]
====
. “Seu Deus.” Hebr.: ‘Elo·heh·hém, pl.
====

[[v24-3-22]]

^<<v24-3-22,22>>^ “Voltai, filhos renegados. Sararei a vossa condição de renegados.”^&#42;1^
“Eis-nos aqui! Chegamos a ti, pois tu, ó Jeová, és nosso Deus.

[NOTE]
====
. Ou “vosso estado de infidelidade”. Lit.: “vossas infidelidades”.
====

[[v24-3-23]]

^<<v24-3-23,23>>^ Verdadeiramente, tanto os morros como o tumulto nos montes são da falsidade. Verdadeiramente, em Jeová, nosso Deus, está a salvação de Israel.

[[v24-3-24]]

^<<v24-3-24,24>>^ Mas a própria coisa vergonhosa consumiu o fruto da labuta dos nossos antepassados, desde a nossa mocidade, seus rebanhos e suas manadas, seus filhos e suas filhas.

[[v24-3-25]]

^<<v24-3-25,25>>^ Deitamo-nos em nossa vergonha e a nossa humilhação nos está cobrindo; pois foi para com Jeová, nosso Deus, que pecamos, nós e os nossos pais, desde a nossa mocidade e até o dia de hoje, e não obedecemos à voz de Jeová, nosso Deus.”

'''

xref:024-jeremias/024-jeremias-002.adoc#v24-2-0[&#60; Capítulo Anterior] | <<v24-3-0,Topo>> | xref:024-jeremias/024-jeremias-004.adoc#v24-4-0[Próximo Capítulo &#62;]