include::./index.adoc[]

[[v24-13-0]]
=== Jeremias, 13
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v24-13-1]]

^<<v24-13-1,1>>^ Assim me disse Jeová: “Vai,^&#42;1^ e tens de obter para ti um cinto de linho e tens de pô-lo sobre os teus quadris, mas não deves metê-lo em nenhuma água.”

[NOTE]
====
. Veja 2:2 n.: “Vai.”
====

[[v24-13-2]]

^<<v24-13-2,2>>^ Obtive, pois, o cinto de acordo com a palavra de Jeová e o pus sobre os meus quadris.

[[v24-13-3]]

^<<v24-13-3,3>>^ E passou a vir a haver para mim a palavra de Jeová pela segunda vez, dizendo:

[[v24-13-4]]

^<<v24-13-4,4>>^ “Toma o cinto que obtiveste, que está sobre os teus quadris, e levanta-te, vai ao Eufrates e encobre-o ali numa fenda do rochedo.”

[[v24-13-5]]

^<<v24-13-5,5>>^ Eu fui, pois, e encobri-o junto ao Eufrates, assim como Jeová me ordenara.

[[v24-13-6]]

^<<v24-13-6,6>>^ Mas, sucedeu ao fim de muitos dias que Jeová passou a dizer-me: “Levanta-te, vai ao Eufrates e toma de lá o cinto que te mandei encobrir por lá.”

[[v24-13-7]]

^<<v24-13-7,7>>^ Conseqüentemente, fui ao Eufrates e cavei, e tomei o cinto do lugar onde o encobrira, e eis que o cinto ficara arruinado; não prestava para nada.

[[v24-13-8]]

^<<v24-13-8,8>>^ Então veio a haver para mim a palavra de Jeová, dizendo:

[[v24-13-9]]

^<<v24-13-9,9>>^ “Assim disse Jeová: ‘Do mesmo modo arruinarei o orgulho de Judá e o orgulho abundante de Jerusalém.

[[v24-13-10]]

^<<v24-13-10,10>>^ Este povo mau que se nega a obedecer às minhas palavras, que está andando na obstinação do seu coração e que prossegue andando atrás de outros deuses,^&#42;1^ a fim de os servir e de se curvar diante deles, também se tornará igual a este cinto que não presta para nada.’

[NOTE]
====
. “Deuses.” Hebr.: ’elo·hím.
====

[[v24-13-11]]

^<<v24-13-11,11>>^ ‘Pois assim como o cinto se apega aos quadris do homem,^&#42;1^ assim fiz toda a casa de Israel e toda a casa de Judá apegar-se a mim mesmo’, é a pronunciação de Jeová, ‘a fim de que se tornassem para mim um povo, e um nome, e louvor, e algo belo; mas eles não obedeceram’.

[NOTE]
====
. “Homem.” Hebr.: ’ish.
====

[[v24-13-12]]

^<<v24-13-12,12>>^ “E tens de dizer-lhes esta palavra: ‘Assim disse Jeová, o Deus^&#42;1^ de Israel: “Toda talha grande é algo que se enche de vinho.”’ E certamente te dirão: ‘Acaso não sabemos positivamente que toda talha grande é algo que se enche de vinho?’

[NOTE]
====
. “O Deus de.” Hebr.: ’Elo·héh, pl.
====

[[v24-13-13]]

^<<v24-13-13,13>>^ E tens de dizer-lhes: ‘Assim disse Jeová: “Eis que encho de embriaguez todos os habitantes desta terra, e os reis que se assentam por Davi no seu trono, e os sacerdotes, e os profetas, e todos os habitantes de Jerusalém.

[[v24-13-14]]

^<<v24-13-14,14>>^ E vou espatifá-los um contra o outro, tanto os pais como os filhos, ao mesmo tempo”, é a pronunciação de Jeová. “Não terei compaixão, nem terei dó, nem terei misericórdia, de modo a não arruiná-los.”’

[[v24-13-15]]

^<<v24-13-15,15>>^ “Ouvi e dai ouvidos. Não vos ensoberbeçais, porque o próprio Jeová falou.

[[v24-13-16]]

^<<v24-13-16,16>>^ Dai glória a Jeová, vosso Deus,^&#42;1^ antes que ele cause a escuridão e antes que os vossos pés batam um no outro nos montes, no crepúsculo. E certamente esperareis a luz, e ele realmente fará dela sombra tenebrosa; ele [a] tornará em densas trevas.

[NOTE]
====
. “Vosso Deus.” Hebr.: ’Elo·heh·khém.
====

[[v24-13-17]]

^<<v24-13-17,17>>^ E se não ouvirdes [isto], minha alma chorará em esconderijos, por causa de orgulho, e positivamente deitará lágrimas; e meus olhos verterão lágrimas, porque a grei de Jeová terá sido levada cativa.

[[v24-13-18]]

^<<v24-13-18,18>>^ “Dize ao rei e à senhora: ‘Sentai-vos num lugar mais baixo, pois certamente descerá das vossas cabeças^&#42;1^ a vossa coroa de beleza.’

[NOTE]
====
. “Das vossas cabeças”, mediante uma correção em harmonia com LXXSyVg.
====

[[v24-13-19]]

^<<v24-13-19,19>>^ As próprias cidades do sul^&#42;1^ foram fechadas, de modo que não há quem [as] abra. Judá inteiro foi levado ao exílio. Foi completamente levado ao exílio.

[NOTE]
====
. Ou “do Negebe”.
====

[[v24-13-20]]

^<<v24-13-20,20>>^ “Levanta^&#42;1^ os olhos^&#42;2^ e vê os que estão chegando do norte. Onde está a grei que te^&#42;3^ foi dada, teu belo rebanho?

[NOTE]
====
. “Levanta”, sing., mediante uma correção em harmonia com LXX; MSyVg: “Levantai”, pl.
. LXX acrescenta: “ó Jerusalém”.
. “Te”, hebr. fem. sing.
====

[[v24-13-21]]

^<<v24-13-21,21>>^ Que dirás quando se^&#42;1^ volta a atenção para ti, sendo que tu mesma os ensinaste no começo como amigos íntimos junto a ti? Não se apoderarão de ti dores agudas de parto, como as de uma esposa^&#42;2^ que dá à luz?

[NOTE]
====
. Ou “ele”. LXX: “eles”.
. Ou “mulher”.
====

[[v24-13-22]]

^<<v24-13-22,22>>^ E quando dirás no teu coração: ‘Por que é que me sobrevieram estas coisas?’ por causa da abundância do teu erro tiraram-se as orlas da tua [veste] qual cobertura; teus calcanhares foram tratados com violência.

[[v24-13-23]]

^<<v24-13-23,23>>^ “Pode o cusita^&#42;1^ mudar a sua pele ou o leopardo as suas malhas? Então também vós poderíeis fazer o bem, sendo que sois pessoas ensinadas a fazer o mal.

[NOTE]
====
. Ou “etíope”, LXXVg.
====

[[v24-13-24]]

^<<v24-13-24,24>>^ De modo que os espalharei como o restolho arrastado pelo vento procedente do ermo.

[[v24-13-25]]

^<<v24-13-25,25>>^ Esta é a tua^&#42;1^ sorte, a tua porção medida proveniente de mim”, é a pronunciação de Jeová, “porque te esqueceste de mim e continuas a confiar na falsidade.

[NOTE]
====
. “Tua”, hebr. fem. sing.
====

[[v24-13-26]]

^<<v24-13-26,26>>^ E eu mesmo também vou levantar as orlas da tua [veste] sobre a tua face e certamente se verá a tua desonra,

[[v24-13-27]]

^<<v24-13-27,27>>^ teus atos de adultério e teus rinchos, tua conduta desenfreada na prostituição. Sobre os morros, nos campos, vi as tuas coisas repugnantes. Ai de ti, ó Jerusalém! Não podes ficar limpa — depois de quanto tempo mais?”

'''

xref:024-jeremias/024-jeremias-012.adoc#v24-12-0[&#60; Capítulo Anterior] | <<v24-13-0,Topo>> | xref:024-jeremias/024-jeremias-014.adoc#v24-14-0[Próximo Capítulo &#62;]