include::./index.adoc[]

[[v24-30-0]]
=== Jeremias, 30
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v24-30-1]]

^<<v24-30-1,1>>^ A palavra que veio a haver para Jeremias da parte de Jeová, dizendo:

[[v24-30-2]]

^<<v24-30-2,2>>^ “Assim disse Jeová, o Deus de Israel: ‘Escreve para ti num livro todas as palavras que vou falar-te.

[[v24-30-3]]

^<<v24-30-3,3>>^ Pois “eis que vêm dias”, é a pronunciação de Jeová, “e eu vou recolher os cativos do meu povo, Israel e Judá”, disse Jeová, “e vou trazê-los de volta à terra que dei aos seus antepassados e eles certamente se reapossarão dela”.’”

[[v24-30-4]]

^<<v24-30-4,4>>^ E estas são as palavras que Jeová falou a Israel e a Judá.

[[v24-30-5]]

^<<v24-30-5,5>>^ Pois assim disse Jeová: “Ouvimos o som dum tremor, pavor, e não há paz.

[[v24-30-6]]

^<<v24-30-6,6>>^ Perguntai, por favor, e vede se um macho dá à luz. Por que é que vi todo varão vigoroso com as mãos nos lombos, igual à fêmea que dá à luz, e todas as faces ficaram pálidas?

[[v24-30-7]]

^<<v24-30-7,7>>^ Ai! Porque aquele dia é grande, de modo que não há nenhum outro igual a ele, e é o tempo de aflição para Jacó. Mas, até mesmo disso ele será salvo.”

[[v24-30-8]]

^<<v24-30-8,8>>^ “E terá de acontecer naquele dia”, é a pronunciação de Jeová dos exércitos, “que quebrarei o jugo de alguém de cima do teu pescoço e romperei as tuas ligaduras, e não mais o explorarão estranhos como servo.

[[v24-30-9]]

^<<v24-30-9,9>>^ E certamente servirão a Jeová, seu Deus, e a Davi, seu rei, a quem levantarei para eles.”

[[v24-30-10]]

^<<v24-30-10,10>>^ “E quanto a ti, não tenhas medo, ó meu servo Jacó”, é a pronunciação de Jeová, “e não fiques aterrorizado, ó Israel. Eis que te salvo do [lugar] longínquo, e a tua descendência, da terra do seu cativeiro. E Jacó certamente retornará, e terá sossego, e estará despreocupado, e não haverá quem faça tremer.”

[[v24-30-11]]

^<<v24-30-11,11>>^ “Pois eu estou contigo”, é a pronunciação de Jeová, “para te salvar; mas farei uma exterminação entre todas as nações às quais te espalhei. Entretanto, no que se refere a ti, não farei nenhuma exterminação. E terei de corrigir-te no grau correto, visto que de modo algum te deixarei impune.”

[[v24-30-12]]

^<<v24-30-12,12>>^ Pois assim disse Jeová: “Não há cura para o teu^&#42;1^ quebrantamento. Teu golpe é crônico.

[NOTE]
====
. “Teu”, hebr. fem. sing., referindo-se à cidade de Sião.
====

[[v24-30-13]]

^<<v24-30-13,13>>^ Não há quem pleiteie a tua causa, para a [tua] úlcera. Não há meio de cura, nem restabelecimento para ti.

[[v24-30-14]]

^<<v24-30-14,14>>^ Todos os que te amavam intensamente são os que se esqueceram de ti. Não é a ti que estão buscando. Pois, golpeei-te com o golpe dum inimigo, com o castigo de alguém cruel, por causa da abundância do teu erro; teus pecados tornaram-se numerosos.

[[v24-30-15]]

^<<v24-30-15,15>>^ Por que clamas por causa do teu quebrantamento? Tua dor é incurável por causa da abundância do teu erro; teus pecados tornaram-se numerosos. Eu fiz estas coisas a ti.

[[v24-30-16]]

^<<v24-30-16,16>>^ Portanto, todos os que te devoram serão eles mesmos devorados; e quanto a todos os teus adversários, todos eles irão para o cativeiro. E os que te^&#42;1^ rapinam ficarão certamente para a rapina, e todos os que te saqueiam, eu os entregarei ao saque.”

[NOTE]
====
. Veja v. 12 n.
====

[[v24-30-17]]

^<<v24-30-17,17>>^ “Pois farei surgir para ti o restabelecimento e te sararei dos teus golpes”, é a pronunciação de Jeová. “Pois, chamaram-te de mulher afugentada: ‘Esta é Sião, que ninguém busca.’”

[[v24-30-18]]

^<<v24-30-18,18>>^ Assim disse Jeová: “Eis que recolho os cativos das tendas de Jacó e apiedar-me-ei dos seus tabernáculos. E a cidade será realmente reconstruída sobre o seu montão; e a própria torre de habitação ficará assentada no seu local legítimo.

[[v24-30-19]]

^<<v24-30-19,19>>^ E certamente sairá deles agradecimento e o som dos que estão rindo. E eu vou multiplicá-los e não se tornarão poucos; e vou fazê-los ponderosos em número, e não se tornarão insignificantes.

[[v24-30-20]]

^<<v24-30-20,20>>^ E os filhos dele terão de tornar-se como outrora e a própria assembléia dele ficará firmemente estabelecida perante mim. E vou voltar minha atenção para todos os seus opressores.

[[v24-30-21]]

^<<v24-30-21,21>>^ E seu majestoso certamente virá a proceder dele e do meio dele sairá o seu próprio governante; e vou fazê-lo chegar perto e ele terá de aproximar-se a mim.”
“Pois, então, quem é este que deu seu coração em penhor, a fim de se aproximar a mim?” é a pronunciação de Jeová.

[[v24-30-22]]

^<<v24-30-22,22>>^ “E vós haveis de tornar-vos meu povo e eu mesmo me tornarei vosso Deus.”

[[v24-30-23]]

^<<v24-30-23,23>>^ Eis que saiu de Jeová um vendaval, o próprio furor, uma tormenta impetuosa.^&#42;1^ Rodopiará sobre a cabeça dos iníquos.

[NOTE]
====
. Ou “tormenta rugidora”.
====

[[v24-30-24]]

^<<v24-30-24,24>>^ A ira ardente de Jeová não recuará até que ele tenha executado e até que tenha realizado as idéias de seu coração. Na parte final dos dias vós lhe dareis a vossa consideração.

'''

xref:024-jeremias/024-jeremias-029.adoc#v24-29-0[&#60; Capítulo Anterior] | <<v24-30-0,Topo>> | xref:024-jeremias/024-jeremias-031.adoc#v24-31-0[Próximo Capítulo &#62;]