include::./index.adoc[]

[[v24-16-0]]
=== Jeremias, 16
// Rbi8 1986, Rbi8 - Tradução do Novo Mundo das Escrituras Sagradas com Referências

[[v24-16-1]]

^<<v24-16-1,1>>^ E continuou a vir a haver para mim a palavra de Jeová, dizendo:

[[v24-16-2]]

^<<v24-16-2,2>>^ “Não deves tomar para ti uma esposa e não deves vir a ter filhos e filhas neste lugar.

[[v24-16-3]]

^<<v24-16-3,3>>^ Pois assim disse Jeová referente aos filhos e referente às filhas que nascem neste lugar, e referente às suas mães que os dão à luz e referente aos seus pais que causam seu nascimento nesta terra:

[[v24-16-4]]

^<<v24-16-4,4>>^ ‘De mortes por enfermidades morrerão. Não serão lamentados, nem serão enterrados. Tornar-se-ão como estrume sobre a superfície do solo; e chegarão ao fim pela espada e pela fome, e seus cadáveres servirão realmente de alimento para as criaturas voadoras dos céus e para os animais da terra.’

[[v24-16-5]]

^<<v24-16-5,5>>^ “Pois assim disse Jeová: ‘Não entres na casa dum banquete de luto, e não vás para lamentar e não te compadeças deles.’
“‘Porque tirei deste povo a minha paz’, é a pronunciação de Jeová, ‘sim, a benevolência^&#42;1^ e as misericórdias.

[NOTE]
====
. Ou “amor leal”.
====

[[v24-16-6]]

^<<v24-16-6,6>>^ E eles certamente morrerão, os grandes e os pequenos, nesta terra. Não serão enterrados, nem as pessoas se baterão no peito por causa deles, nem fará alguém cortes em si mesmo, nem se fará calvo por causa deles.

[[v24-16-7]]

^<<v24-16-7,7>>^ E não partilharão entre eles nenhum pão por causa do luto, para consolar alguém pelo morto; nem lhes darão o copo de consolação para beber por causa do pai de alguém e por causa da mãe de alguém.

[[v24-16-8]]

^<<v24-16-8,8>>^ E não deves entrar em nenhuma casa de banquete para te assentar com eles para comer e beber.’

[[v24-16-9]]

^<<v24-16-9,9>>^ “Pois assim disse Jeová dos exércitos, o Deus^&#42;1^ de Israel: ‘Eis que neste lugar, perante os vossos olhos e nos vossos dias, faço cessar a voz de exultação e a voz de alegria, a voz do noivo e a voz da noiva.’

[NOTE]
====
. “O Deus de.” Hebr.: ’Elo·héh.
====

[[v24-16-10]]

^<<v24-16-10,10>>^ “E terá de acontecer que, quando contares a este povo todas estas palavras e eles realmente te disserem: ‘Por que razão proferiu Jeová contra nós toda esta grande calamidade, e qual é nosso erro e qual é nosso pecado com que pecamos contra Jeová, nosso Deus?’,

[[v24-16-11]]

^<<v24-16-11,11>>^ então terás de dizer-lhes: ‘“Pelo fato de que os vossos pais me abandonaram”, é a pronunciação de Jeová, “e seguiram andando atrás de outros deuses,^&#42;1^ e continuaram a servi-los e a curvar-se diante deles. Mas a mim me deixaram, e a minha lei não guardaram.

[NOTE]
====
. “Deuses.” Hebr.: ’elo·hím.
====

[[v24-16-12]]

^<<v24-16-12,12>>^ E vós mesmos agistes pior do que vossos pais, naquilo que fizestes, e eis que estais andando, cada um, atrás da obstinação de seu mau coração, não me obedecendo.

[[v24-16-13]]

^<<v24-16-13,13>>^ E eu vou arremessar-vos para fora desta terra, para uma terra que não conhecestes, nem vós, nem vossos pais, e lá tereis de servir a outros deuses, dia e noite, porque não vos concederei nenhum favor.”’

[[v24-16-14]]

^<<v24-16-14,14>>^ “‘Por isso,^&#42;1^ eis que vêm dias’, é a pronunciação de Jeová, ‘em que não mais se dirá: “Por Jeová que vive, que fez os filhos de Israel subir da terra do Egito!”,

[NOTE]
====
. Ou: “Em resultado.”
====

[[v24-16-15]]

^<<v24-16-15,15>>^ mas: “Por Jeová que vive, que fez os filhos de Israel subir da terra do norte e de todas as terras às quais os dispersara!” e hei de fazê-los voltar ao seu solo, que dei aos seus antepassados.’

[[v24-16-16]]

^<<v24-16-16,16>>^ “‘Eis que mando [vir] muitos pescadores’, é a pronunciação de Jeová, ‘e eles certamente os pescarão; e depois mandarei [vir] muitos caçadores, e eles certamente os caçarão de todo monte, e de todo morro, e das fendas dos rochedos.

[[v24-16-17]]

^<<v24-16-17,17>>^ Pois os meus olhos estão em todos os seus caminhos. Não ficaram escondidos de diante de mim, nem ficou oculto seu erro de diante dos meus olhos.

[[v24-16-18]]

^<<v24-16-18,18>>^ E, em primeiro lugar, retribuirei o pleno montante^&#42;1^ do seu erro e do seu pecado, por terem profanado a minha terra. Encheram a minha herança com os cadáveres das suas coisas repugnantes e das suas coisas detestáveis.’”

[NOTE]
====
. “Pleno montante.” Ou “montante duplo; o dobro”. Hebr.: mish·néh.
====

[[v24-16-19]]

^<<v24-16-19,19>>^ Ó Jeová, minha força e meu baluarte, e meu lugar de refúgio no dia de aflição, a ti virão as próprias nações desde os confins da terra^&#42;1^ e dirão: “Deveras, os nossos antepassados vieram a possuir pura falsidade, vaidade e coisas em que não havia nada proveitoso.”

[NOTE]
====
. “Desde os confins (terminações) da terra.” Hebr.: me·’af·seh-’á·rets. Veja 25:31.
====

[[v24-16-20]]

^<<v24-16-20,20>>^ Pode o homem terreno fazer para si deuses que não são deuses?

[[v24-16-21]]

^<<v24-16-21,21>>^ “Portanto, eis que lhes faço saber; esta vez os farei conhecer a minha mão e a minha potência, e terão de saber que meu nome é Jeová.”

'''

xref:024-jeremias/024-jeremias-015.adoc#v24-15-0[&#60; Capítulo Anterior] | <<v24-16-0,Topo>> | xref:024-jeremias/024-jeremias-017.adoc#v24-17-0[Próximo Capítulo &#62;]